### ISSUE TITLE
Redacted image somehow reappeared in E2E room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10006]
<img width="721" alt="Screenshot 2019-06-10 at 23 40 00" src="https://user-images.githubusercontent.com/1294269/59231644-5dd64b80-8bd9-11e9-95f6-2e27b7e2e510.png">

**Comment by bwindels** [comment]
This might be related to the local echo for redaction changes I made last week. Did the text go away after a while (e.g. when the redaction was sent)?

**Comment by bwindels** [comment]
Found a way to repro this, you need two riot sessions:
 1. open riot with session 1
 1. send a message
 1. edit it
 1. redact it
 1. send +10 messages to trigger a limited sync in session 2 later on
 1. open riot with session 2, let it sync
 1. the edited and then redacted message should now have it's content visible through the redaction lozenge.

**Comment by SimonBrandner** [comment]
@ara4n, have you ever seen this again?

**Comment by t3chguy** [comment]
Closing due to lack of info
