### ISSUE TITLE
Logging into a brand new account can leave you with no room in the central pane

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#10013]
<img width="950" alt="Screenshot 2019-06-11 at 14 34 38" src="https://user-images.githubusercontent.com/1922197/59276420-22c62d80-8c56-11e9-8e35-53c61f500897.png">

To reproduce:
- create new account
- log out
- log in

What I expected to happen:
- probably show the chat with Riot Bot?

**Comment by aaronraimist** [comment]
> probably show the chat with Riot Bot?

Why would it?

**Comment by t3chguy** [comment]
We now have a home page
