### ISSUE TITLE
Password reset sometimes gives you a 'failed to reset password' error modal when actually it succeeded.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#10023]
The UX behind the error modal eventually changes to read that the password was updated successfully.

My guess is that this is another instance of Riot polling a registration endpoint and also initiating requests in response to user interface actions - in this case I think the pw reset ux is polling the registration APi, but it is the result of clicking the 'I verified my email' button that appears in the feedback modal. And the password reset API is not idempotent, so if the polling has successfully completed password reset then the button click will fail.

Would it be possible for password reset to be complete upon clicking password reset link? It's easy to miss the final step and think your pw reset failed.

**Comment by dbkr** [comment]
I have no idea how you managed this - there's no polling in the background, it only does the request when you press the, "I verified..." button.

If we're making any significant changes to password reset (by which, read: any that involve spec changes) I'd really like to make it a normal password reset flow, ie. you enter a new password on the page you get after clicking the link.

**Comment by richvdh** [comment]
I think this might have been a dup of https://github.com/vector-im/element-web/issues/11531?

**Comment by Palid** [comment]
Duplicate, closing in favor of https://github.com/vector-im/element-web/issues/11531
