### ISSUE TITLE
Reply button ignores first click on FF, and then cues up two replies...

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10024]
Weird misbehaviour:
 * If i click reply button on a msg, nothing happens.
 * If i click it again, i start composing a reply \o/
 * I send a reply...
 * ...and the reply overlay is still present, until I explicitly close it with the X button.
 * subsequent messages do not send as a reply though, despite the overlay being present.

**Comment by jryans** [comment]
I don't believe I have observed this on Firefox (or any other browser) so far... @ara4n, does it reproduce every time for you?

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
