### ISSUE TITLE
Video calls perform poorly on Kubuntu 18.04

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/element-web#10050]
### Description

Almost nothing works: riot on web browser does not see the images of the other person, riot on desktop has no tray icon and / or if it closes it does not reopen anymore; both (broser-based and desktop) have distorted audio and volume that changes.  
So for some time I had to give up riot.  
I hope you solve it soon these problems.

### Steps to reproduce

- try to do a video call
- no video (for one person)
- audio very bad

Log: not sent    

### Version information

- **Platform**: both

For the web app:

- **Browser**: Firefox 67
- **OS**: Kubuntu 18.04
- **URL**: riot.im/app 

For the desktop app:

- **OS**: Kubuntu 18.04
- **Version**: 1.2.1

**Comment by jryans** [comment]
Sorry to hear about the trouble. What happens if you try a WebRTC testing page in the same browser, such as https://appr.tc/?

**Comment by DoctorSubtilis** [comment]
I see myself in the browser.

**Comment by jryans** [comment]
Possibly related: https://github.com/vector-im/riot-web/issues/10021

**Comment by SimonBrandner** [comment]
@DoctorSubtilis, is this still an issue for you?

**Comment by DoctorSubtilis** [comment]
To be honest, I didn't try, recently

Jul 30, 2021 10:02:35 Šimon Brandner ***@***.***>:

**Comment by SimonBrandner** [comment]
Ok, then I am going to close this as the issue seems to be quite old. If you ever see this again feel free to reopen/create a new issue
