### ISSUE TITLE
Recycle addresses of empty rooms

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10065]
This will become irrelevant once empty rooms will be garbage collected, but until then it might be a good idea to strip all assigned room addresses off a room when the last user leaves.  That will make those addresses available again - including for a new version of the same room.

**Comment by jryans** [comment]
Should this issue move to Synapse instead? It doesn't sound like a client issue...

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/issues/1201
