### ISSUE TITLE
Reference theme images via CSS instead of using the img tag

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#10062]
Please reference theme images via CSS instead of using the img tag.

**Comment by jryans** [comment]
I assume because you want to override them in some way...? It helps us prioritise if you also include more details about your use case for this.

**Comment by menturion** [comment]
You are right. This is one reason. 
Another resaon is: Use the <img > tag if the image is part of the content. If not use CSS. 
The logo is the only theme image that should be considered as part of the conent.

**Comment by t3chguy** [comment]
We're using svg masks for vast majority of things now
