### ISSUE TITLE
No text hint when hover over emoticon in a message

### ISSUE THREAD

**Issue by spasmarinov** [vector-im/element-web#10074]
### Description

When you place the mouse over emoticon in a message in native Windows client no text hint is displayed.

### Steps to reproduce

- Install Riot for Windows
- Join/create a room and chat with somebody
- Send a message with a single emoticon only (to show the large emoticon)
- Hover the mouse over the large emoticon- no text hint is displayed

Describe how what happens differs from what you expected.

It used to show a text hint, on macOS works as expected.

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows 8.1

- **Version**: 1.x.y 
riot-web version: 1.2.1
olm version: 3.1.0

**Comment by t3chguy** [comment]
This got fixed
