### ISSUE TITLE
Devtools State Explorer should show empty/whitespace State Keys better

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10082]
It shows two state events with no state key, and the buttons are weird for those events

**Comment by t3chguy** [comment]
Looks fine here:
![image](https://user-images.githubusercontent.com/2403652/59670185-63bcc580-91b3-11e9-9dce-99c0696ff68a.png)

**Comment by jryans** [comment]
I think the issue occurs after you click on `im.verctor.web.settings`. It then shows two empty buttons.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/59672732-f3647300-91b7-11e9-886d-3cf204c73490.png)

Indeed it does

**Comment by turt2live** [comment]
We can just upgrade the room to hide and correct our past mistakes.

Looks like it's not a bug though

**Comment by t3chguy** [comment]
Empty buttons are not super useful, going to hijack this issue

**Comment by t3chguy** [comment]
This got fixed
