### ISSUE TITLE
Why is the sign out dialog warning me that I'll lose access to encrypted messages slow

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#10106]
Why does the "You'll lose access to your encrypted messages" dialog have a spinner at all? Sometimes I just want to sign out of an account and I know the dialog is coming but I can't sign out because the dialog just has a loading spinner that is just spinning and spinning but there is nothing I can do to sign out faster.

Surely it doesn't have to load the text or the buttons and can just display those instantly while loading whatever it needs to in the background. If it isn't complete with loading whatever it needs to load by the time I click one of the buttons, it should show the spinner then.

**Comment by ousia** [comment]
Would it be possible that this could be avoided when there was no encrypted message to be saved (or even read)?

Many thanks for your help.

**Comment by aaronraimist** [comment]
@ousia that is https://github.com/vector-im/riot-web/issues/11684

**Comment by ousia** [comment]
Many thanks, @aaronraimist.

**Comment by aaronraimist** [comment]
Haven't seen this in a while
