### ISSUE TITLE
Can not invite Matrix user with their email address

### ISSUE THREAD

**Issue by schiessle** [vector-im/element-web#10102]
### Description

I can't invite Matrix users to a room by their email address, invitation only works if I use their matrix ID

### Steps to reproduce

1. create a new room
2. click on "invite to this room"
3. enter a email address to the dialog, as you can see the matrix user is detected:
![image](https://user-images.githubusercontent.com/1589737/59719512-d3b36600-921c-11e9-9c4d-63608ce5fb75.png)
4. select the user
5. click on "send invite"
6. result in a "unknown server error"
![image](https://user-images.githubusercontent.com/1589737/59719576-03626e00-921d-11e9-8f24-d78a83c00893.png)

If I enter the matrix ID instead of the email address `@<user>:matrix.org` the invitation works.

### Version information

- **Platform**: I tried both, web (in-browser) and desktop

For the web app:

- **Browser**: Firefox 67
- **OS**: Linux
- **URL**:  riot.im/app 

For the desktop app:

- **OS**: Linux
- **Version**: 1.2.1

**Comment by t3chguy** [comment]
Which identity server are you using? Can be checked in settings

**Comment by schiessle** [comment]
Both parties use the default one which is used when registering a matrix.org account with riot.im

**Comment by nesnera** [comment]
+1 (At matrix.org)

**Comment by nesnera** [comment]
It works well for me today 2019-08-13

**Comment by Brixy** [comment]
Sorry for bothering. I just want to confirm that we have the same issue even with Riot 1.5 (encrypted and non-encrypted rooms).

The only chance to invite somebody via email is using Riot iOS (Riot Android untested).

**Comment by t3chguy** [comment]
Given the age of this, logs would no longer be available to chase. If you are still experiencing this please open a new issue
