### ISSUE TITLE
Sending reactions in an e2e room with unknown devices leads to unclear errors

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10108]
![image](https://user-images.githubusercontent.com/1190097/59778471-c9708680-9273-11e9-8712-765bdf56b5ab.png)

I didn't send a message though, I clicked a button. It's not clear that my reaction was not sent either.

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/issues/9692 discuss some approaches to the more general problem of errors, but let's keep this as will in case we want something more targeted for this case.

**Comment by turt2live** [comment]
We don't have this banner anymore
