### ISSUE TITLE
We should introduce new default-on features with a mini-tutorial or something

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10119]
Breadcrumbs is an example of this: people are generally angry that we introduced them as default-on, and we didn't put a tooltip to say 'This is where your recent rooms are. You can disable this in the settings. [Got it button]'.

**Comment by notramo** [comment]
A **Disable** button should be also shown next to the **Got it** button.

**Comment by turt2live** [comment]
The design team takes this and similar features into consideration these days - we don't need to consider the developer design of the past.
