### ISSUE TITLE
Historical section jumps around when you click through rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10129]
It's hard to keep track of which rooms I've addressed when they keep changing order. There's no new messages there, so they should be fairly static. Probably the recents-first sorting algo interfering

**Comment by turt2live** [comment]
this is a bug in the algorithm, not a suggestion. It shouldn't be causing rooms to jump around and instead should be freezing the current selection if there are any changes (which there won't be, it's historical).

**Comment by jryans** [comment]
I don’t think this is valid with the new room list.
