### ISSUE TITLE
riot not showing full size avatar after upgrading riot web and matrix server to latest stable version

### ISSUE THREAD

**Issue by akhiljalagam** [vector-im/element-web#10133]
matrix version : 1.0.0
riot web : 1.2.2
when clicked on avatar image..showing this one
![image](https://user-images.githubusercontent.com/21128035/59903564-ec8b6980-941e-11e9-85d7-2df73003c7ef.png)

but its working when reuploaded avatar..

**Comment by jryans** [comment]
Thanks for filing! Are all avatars for all users on the HS affected?

**Comment by akhilin** [comment]
> Thanks for filing! Are all avatars for all users on the HS affected?

YES.affected on all users and rooms.

**Comment by jryans** [comment]
I would recommend asking in #riot-web:matrix.org and / or #synapse:matrix.org to see if other people have similar issues.

**Comment by akhiljalagam** [comment]
> @akhiljalagam Are you still able to reproduce this?

no. it's resolved on updating to the latest version. thanks.
