### ISSUE TITLE
Allow configuring behaviour of right panel

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#10147]
I'd personally prefer always having it show mentions but it defaults to users when you enter a room so a setting for this would be nice.

**Comment by jryans** [comment]
Can you add more detail here? I can think of many possible things you might mean... Which left side pane, room list or communities? What should be configurable?

**Comment by BearerOfHonesty** [comment]
Apparently I wasn't awake when I wrote this, I meant right-side not left. The one with room users and mentions.

I'd personally prefer always having it show mentions but it defaults to users when you enter a room so a setting for this would be nice. 

Alternatively just remember which view was open in the previous room and open that in the current room.

Both equally good to me.

**Comment by t3chguy** [comment]
> Alternatively just remember which view was open in the previous room and open that in the current room.

is https://github.com/vector-im/riot-web/issues/10149

**Comment by jryans** [comment]
Okay, could you rewrite the issue title and original post to cover your suggestion (or else close and file a new issue that captures it)?

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3703
