### ISSUE TITLE
Forward message modal looks strange

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#10165]
I am not sure what the intended appearance is, but at the moment, when you choose forward message, we show some text and the top of the screen and an oddly placed close button:

<img width="791" alt="2019-06-25 at 11 15" src="https://user-images.githubusercontent.com/279572/60090805-1ef8d780-973b-11e9-93e1-73f1eaac0260.png">

We currently appear to have no CSS for `mx_ForwardMessage`. We could do some archaeology to find what was their historically, but it might be easier to just design what we want to have now.

**Comment by bwindels** [comment]
I've added this to the design board, probably not worth starting on it before there is some design.

**Comment by niquewoodhouse** [comment]
There was a similar issue raised recently, where I dropped in some design options, if helpful #14690
