### ISSUE TITLE
Login/auth pages don't have a dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10198]
This was never designed, but when people set the default theme to the dark theme it'd be nice to have the login be dark themed

**Comment by jryans** [comment]
The auth flows currently duplicate various styles to enforce light theme for auth even dark theme is the default. If we get designs for dark theme auth, it would likely be easier to maintain technically as we can remove this duplication and allow the theme to work naturally.

**Comment by turt2live** [comment]
I don't personally believe this is an issue anymore, so would like to take my name off of it. If folks feel strongly that the auth pages need a dark theme mode, please open a new issue for the design team to consider.
