### ISSUE TITLE
Consider a dedicated +1 reaction button

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10207]
Next to the 'more reactions' tooltip thing. It's more frequent than the other reactions, and it's already a bit annoying to have to go through a menu system to add it

**Comment by t3chguy** [comment]
@turt2live I see words I read words but I have no idea what they try to say

**Comment by turt2live** [comment]
I don't personally believe in this issue anymore and would like to take my name off of it. If folks are still looking for this functionality, please open a new issue for the design/product teams to consider.
