### ISSUE TITLE
Marking a room as not a direct chat doesn't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10210]
It's still a direct chat, despite all account data, requests, etc saying it's not

**Comment by rxl881** [comment]
According to (unconfirmed) customer reports, this is a regression, introduced in Synapse 1.5.0 and is a breaking change for their client:

![Selection_062](https://user-images.githubusercontent.com/6763606/68195670-282e6680-ffaf-11e9-8194-1a8f4f6c9cd7.png)

**Comment by t3chguy** [comment]
Luckily the button is now gone
