### ISSUE TITLE
Code line that creates the path to the icon is not working in packaged desktop version of riot-web application

### ISSUE THREAD

**Issue by denpad** [vector-im/element-web#10215]
### Description

The code in the line https://github.com/vector-im/riot-web/blob/v1.2.2/electron_app/src/electron-main.js#L298 is not working as intended in the packaged version of the app. Because in the packaged version of the app the image is stored in the app.asar file so that relative paths don't work any more and the file can't be accessed.

Solution that worked for me is to replace the code line mentioned in the link above with following code line:

```javascript
const iconPath = path.normalize(`${__dirname}/../img/riot.${process.platform === 'win32' ? 'ico' : 'png'}`);
``` 

Before I implemented my solution. I have tried the code from the develop branch on the lines 303 and 304.
The code on the line 304: https://github.com/vector-im/riot-web/blob/develop/electron_app/src/electron-main.js#L304 is also wrong the correct one is:

```javascript
const iconPath = path.join(__dirname, "..", "img", iconFile);
```

### Steps to reproduce

- Download source package from https://github.com/vector-im/riot-web/archive/v1.2.2.tar.gz
- Build the desktop app by following the build instructions
- start: `yarn build:electron:linux`
- After build is finished change directory : `cd electron_app/dist/linux-unpacked/`
- Start app with: `./riot-web`

Expected behavior is that application window is shown and riot.png icon is shown in the tray part of the task bar. What happens is that no tray icon is displayed in the task bar.

Log: There is no message in the log.

### Version information

- **Platform**: desktop
- **OS**: Manjaro Linux, gnome desktop
- **Version**: 1.2.2

**Comment by jryans** [comment]
I agree the path is not correct in 1.2.2. The code from develop won't work unless you also apply the packaging changes from the [same commit](https://github.com/vector-im/riot-web/commit/292427c275cfad9458be23b3326fd18d9437c387).

What happens if you build the develop branch as it is (instead of copying specific lines from it)?

**Comment by denpad** [comment]
Hi, indeed I agree. I will try to build development Branch and report back .


Am 2. Juli 2019 10:43:01 MESZ schrieb "J. Ryan Stinnett" <notifications@github.com>:
>I agree the path is not correct in 1.2.2. The code from develop won't
>work unless you also apply the packaging changes from the [same
>commit](https://github.com/vector-im/riot-web/commit/292427c275cfad9458be23b3326fd18d9437c387).
>
>What happens if you build the develop branch as it is (instead of
>copying specific lines from it)?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/10215#issuecomment-507581142

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jryans** [comment]
This seems very specific to a single user, and they haven't responded with more details, so for now I'll close this. If it's still an issue, feel free to file a new issue about this.
