### ISSUE TITLE
[Feature] Active separated featured topics 

### ISSUE THREAD

**Issue by blackPantherOS** [vector-im/element-web#10228]
**Is your suggestion related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Messages push out the older important questions. 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Pinned important "main-topics"

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Like Facebook  comments under the pinned main topic

**Additional context**
_Add any other context or screenshots about the feature request here._

Mockup: (rethought the default layout for pinned topics idea)
![matrix_fix](https://user-images.githubusercontent.com/12883566/60456074-909fbc80-9c38-11e9-8846-c529983b35aa.png)

**Comment by robintown** [comment]
This use-case is covered by threads, which are now in beta.
