### ISSUE TITLE
Account Data button in devtools has too big text

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#10246]
![image](https://user-images.githubusercontent.com/1342360/60591491-7bd93b00-9d96-11e9-8689-f52dda389f0b.png)

### Description

It doesn't look nice and makes me sad :crying_cat_face: 

Log: not sent

- **Platform**: web
- **Browser**: Firefox v69.0a1
- **OS**: Debian Stretch
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
That's not how I left it :'(

**Comment by t3chguy** [comment]
Weirdly I cannot repro regardless of how narrow I make the window :(
![image](https://user-images.githubusercontent.com/2403652/60754441-c1854600-9fd8-11e9-9a79-9f7afc95cdbf.png)
![image](https://user-images.githubusercontent.com/2403652/60754453-ee395d80-9fd8-11e9-8ac2-dbedfe9ca61e.png)

**Comment by anoadragon453** [comment]
Odd. My setup had a full screen riot btw

**Comment by anoadragon453** [comment]
I can no longer reproduce this either on Firefox or Element Desktop, and nobody else has shouted about it in 2 years. Closing for now.
