### ISSUE TITLE
Media flashes black when mouse enters/leaves message scrollback area

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#10258]
Video demonstration: https://streamable.com/wofhz

### Description

Images/videos flicker black when the mouse moves in and out of the message area. This happens whether the mouse is moving over the input box, room list, etc. As long as it's exiting and entering the chat scrollback component, media flickers. I assume this is because the component is being rerendered? The only other item that seems to change is the right scrollbar appears/disappears. Is the component getting redrawn because of this?

Log: not sent

### Version information

- **Platform**: web
- **Browser**: Firefox v69.0a1
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by jryans** [comment]
Hmm, this doesn't appear to happen with Firefox on macOS. Could you try a different browser and check your experience there?

**Comment by michaelkaye** [comment]
I've replicated this on my firefox / Ubuntu Linux / 68.0.1

**Comment by jryans** [comment]
Does it also happen in some non-Firefox browser? I'd like to know if it's specific to Firefox on Linux, or a broader issue.

**Comment by jryans** [comment]
Which Riot theme are you using?

**Comment by michaelkaye** [comment]
> Which Riot theme are you using?

dark

**Comment by anoadragon453** [comment]
I haven't seen this in a good long time, so closing for now.

**Comment by anoadragon453** [comment]
Juuuuust kidding, just saw it happen again :)

Firefox v72.0a1, Debian Buster

**Comment by anoadragon453** [comment]
I haven't seen this in ages, so going to assume it was a rendering artifact of a specific browser on a specific set of hardware and move on.
