### ISSUE TITLE
Unable to submit a bug report

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#10259]
![Screenshot_2019-07-04_14-56-25](https://user-images.githubusercontent.com/1342360/60671837-ea3bfd00-9e6b-11e9-8395-52b78c41b016.png)

Error from JS console:

```
Warning: Failed prop type: The prop `id` is marked as required in `Field`, but its value is `undefined`.
    in Field (created by BugReportDialog)
    in BugReportDialog (created by AsyncWrapper)
    in AsyncWrapper
    in div
    in div
```

Firefox Nightly v69.0a1, Debian Linux

**Comment by turt2live** [comment]
The error is actually below that, I think. It seems to have failed to load at all. Does `mxSendRageshake` work?

**Comment by jryans** [comment]
It looks like your server is missing some of the Riot JS files?

**Comment by anoadragon453** [comment]
Annoyingly the field seems to work fine now as I refreshed.

**Comment by anoadragon453** [comment]
> It looks like your server is missing some of the Riot JS files?

Could be a possible cause, seeing as I don't see any missing files this time around. Could've been caused by a botched upgrade on the server side (Riot is updated hourly on the last, successful /develop build).

**Comment by anoadragon453** [comment]
Notably

```
Warning: Failed prop type: The prop `id` is marked as required in `Field`, but its value is `undefined`.
    in Field (created by BugReportDialog)
    in BugReportDialog (created by AsyncWrapper)
    in AsyncWrapper
    in div
    in div
```

is still in the JS console even though submitting a report works now.

**Comment by jryans** [comment]
Yes, that warning is mostly just noise... It should be fixed (or removed) but that won't prevent a bug report from being sent.

**Comment by anoadragon453** [comment]
I'll assume it was just my server then, and move that error to another issue.

**Comment by anoadragon453** [comment]
Actually, I'm still getting this.

**Comment by anoadragon453** [comment]
But I don't seem to be anymore! :tada:
