### ISSUE TITLE
feature request: sync only some communities to 1 device

### ISSUE THREAD

**Issue by Rik44444** [vector-im/element-web#10271]
hi all,
i have the following use case: i use Matrix chat for both personal and work chats. On my laptop it's fine to have both in Riot.im (or another client), but on my phone i'd like to be able to only see and sync my personal people and rooms. 
Therefore my feature request is: developing the ability to sync only some communities (e.g. personal, or work) to a device. 
many thanks! 
Rik

**Comment by nadonomy** [comment]
Closing as communities are deprecated, superceded by Spaces.

@Rik44444 if you still have this need, feel free to open a new issue. Note though that 'sync' is generally a term we use for the client syncing to the server, you might want to consider whether you want the ability to show/hide specific Spaces instead.
