### ISSUE TITLE
Window placement not saving

### ISSUE THREAD

**Issue by catvvvveasel** [vector-im/element-web#10291]
Window always opens off screen from when I had a different layout, I have to reconfigure montors, drag the window to monitor one. CLose and reopen, and its offscreen again. Windows <- keys dont move the window

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
Are you using a display which is only available sometimes? Like an external monitor attached to a laptop

**Comment by catvvvveasel** [comment]
Yes I am. But I’ve moved it multiple times back from its offscreen position And even with the same layout when restarted it’s gone rogue again! I haven’t used that other layout in months!

**Comment by catvvvveasel** [comment]
Just in case it’s relevant, the saved position is from when I had the monitors arranged one above the other, now they are side by side

**Comment by turt2live** [comment]
hmm, that indeed does sound like a bug. Windows in particular has a bug where things go off screen easily, but usually the windows keys fix it (if it doesn't, try right clicking the preview from the taskbar and select "Maximize")

**Comment by ssbarnea** [comment]
Clearly there is something broken about window placement on MacOS as I ended up with a Riot that I can use only when in full screen mode. Every attempt to use in non-full screen ends up with no visible window. I will attach debug logs.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/20940
