### ISSUE TITLE
Dragging the separators between room list sections doesn't work on maximized and all chats spread riot-desktop-windows client

### ISSUE THREAD

**Issue by dreamerchris** [vector-im/element-web#10294]
between favorites-people-rooms one can be dragged up and down those parts in web version of riot but in the desktop-windows-client (freshly installed) I noticed I cant, the drag pointer appears but hold-clicking and dragging does nothing

edit: after further examination there is no faulty behavior, it was just that I was fullscreen and all rooms and favorites and people had their space so dragging had no use.

maybe add a notification/error popup that when there is room and all chats are viewable, it displays, "cannot drag, all chats are spaced out and visible"!!!!

**Comment by turt2live** [comment]
We don't have these anymore.
