### ISSUE TITLE
Handling „dead devices“

### ISSUE THREAD

**Issue by invertor** [vector-im/element-web#10300]
By dead device I mean already logged out. This is most interesting for Web-based uses.

Description: I open Riot via Web-browser, visit an encrypted room and then log out. Then on my mobile I would see a message if I want to verify or share my keys with that device. Well, the device doesn't exist anymore! I can't verify it. Other devices and other users will be warned that the keys may be sent to an “unknown device” (which is also not true) and I keep see that “dead device” in the list.

I would suggest/expect the following: as long as the new device is logged in, the same current message (would you like to verify/share keys) will show on the other devices, till one of these devices verify (or maybe even share?), then it disappears everywhere. If the new device was logged out: so the message would become something like: „a new device was logged in“; with new choices „it was me“: this would deletes the device from the devices' list; or „it wasn't me“: this would make Riot suggests changing the password)

I'm trying in the last few weeks to introduce non-technical users to Riot. The Keys' and Devices management is what confuses them the most. I hope most of these warnings will disappear after having „cross-signing“

**Comment by dbkr** [comment]
This looks like it was written pre-cross-signing and so hopefully is no longer relevant.
