### ISSUE TITLE
/_matrix/client/r0/publicRooms does not return recently updated room avatars.

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-web#10326]
When a mod changes the avatar of a public room, the new avatar url is not returned in the /_matrix/client/r0/publicRooms response until the mod invites somebody else to the room.  It is unclear what other actions can trigger the update.

**Comment by neilisfragile** [comment]
Recording here because it not clear if this is a Riot or Synapse bug. Though it may be fixed when https://github.com/matrix-org/synapse/issues/4043 lands

**Comment by turt2live** [comment]
If it's indeed not being returned by the API endpoint, there's not much Riot can do. Counting this as a synapse bug until proven otherwise

**Comment by t3chguy** [comment]
Closing, if you still see this bug please open an issue in https://github.com/matrix-org/synapse/
