### ISSUE TITLE
Editing a message which has an h2 in the middle loses the h2

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10333]
First screenshot becomes the second screenshot: 
![](https://i.imgur.com/ng7503y.png)
![](https://i.imgur.com/lfFrEWy.png)

**Comment by bwindels** [comment]
Possible related: https://github.com/vector-im/riot-web/issues/10316

**Comment by robintown** [comment]
This has apparently been fixed:

![Screenshot 2022-03-07 at 22-54-53 Element  1  Test room](https://user-images.githubusercontent.com/48614497/157163218-3c35d3ce-12cc-4294-8caf-4b5fd3de81ee.png)
