### ISSUE TITLE
Emoji autocomplete with enter & emojify on paste :emoji:

### ISSUE THREAD

**Issue by jtagcat** [vector-im/element-web#10339]
![emojicomplete](https://user-images.githubusercontent.com/38327267/61176347-dcdeeb00-a5ae-11e9-9883-733a8b477889.gif)
Note: first message was with mouse, but peek didn't capture it for some reason
- **Platform**: web (in-browser) or desktop? Desktop, Fedora via tawk repo, 1.2.4

**Comment by vc7ee** [comment]
Edit: apparently tab works, but enter key should work as well.
Copy-Pasta should work anyways.

**Comment by Auroch** [comment]
So, is it normal for now that emoji codes like: dog: are not interpreted when they appear in the text?
I have a particular problem with the octoprint plugin (and I imagine with other "bot") which allows me to send printer states, prints, etc. emoji codes appear as text and not emoji...

**Comment by t3chguy** [comment]
Bots should send actual emojis, as defined by the consortium, not ambiguous short codes which are poorly defined

**Comment by gmiller01** [comment]
Hi, the emoji auto incomplete without a space after the emoji, is frustating me also. I have using a lot of chat applications and every app can change ":-)" to smile, without an extra space after it.

**Comment by hho** [comment]
This is not an exact duplicate (on paste), but at least related to #7256 (on enter)

**Comment by SimonBrandner** [comment]
I am going to close this in favour of https://github.com/vector-im/element-web/issues/7256, so that we don't have duplicates
