### ISSUE TITLE
We have a regular flow of "Unrecognised access token" errors being received from the homeserver

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10354]
Independent of matrix.org logging everyone out, we have been getting reports of at least 1 user per week being logged out due to "Unrecognised access token". It's unclear what is causing these, however it smells of a Synapse bug and/or regular password resets.

Without more logs to correlate what happened, I can only assume it's a Synapse bug or unexpected behaviour of the app. The "delete my data" flag mentioned in https://github.com/vector-im/riot-web/issues/2671#issuecomment-511681003 might reduce the number of complaints?

Flagging this as a `question` as it needs more investigation. Rageshakes should also be associated with this issue to track frequency going forward.

**Comment by richvdh** [comment]
seems like the flow has abated; closing.
