### ISSUE TITLE
riot-web 1.3.0 under linux - typing ":" does not directly deliver the emoji picker

### ISSUE THREAD

**Issue by chrissi55** [vector-im/element-web#10378]
### Description

In riot-web 1.3.0 under zorinos 15 what is based on ubuntu 18.04.2 the emoji picker doesn't pop up immediately when typing ":"

![no_emoji](https://user-images.githubusercontent.com/22561479/61587776-92ea9c00-ab90-11e9-89a9-f8e8b3c56169.png) 

### Steps to reproduce

- Open riot-web under zorin15 and type ":"
- if you don't  know the emoji text replacement you have to wait for the picker
- ...wait, and wait, and wait after 5-10 seconds (it differs from time to time) the picker comes up

As you can see, i had enough time to start my screenshot tool, taking a screenshot ...

under Windows riot-web (desktop) reacts immediately - picker pops up like popcorn!!

Don't know what causes this bad delay in linux version...

Describe how what happens differs from what you expected.
-> in earlier versions the picker comes up under linux immediately

![Bildschirmfoto vom 2019-07-21 08-15-03](https://user-images.githubusercontent.com/22561479/61587819-46539080-ab91-11e9-8eb1-b0ec6eb4e0e1.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu, zorin15 Linux
- **Version**: 18.04.2

**Comment by t3chguy** [comment]
The autocomplete delay option in settings was fixed, try tweak that one to your liking

**Comment by chrissi55** [comment]
> try tweak that one to your liking

How or where do i have to make changes?

**Comment by SimonBrandner** [comment]
@chrissi55, is this still a problem? You can change the delay in here:

![Screenshot_20210626_175101](https://user-images.githubusercontent.com/25768714/123518645-1b401880-d6a7-11eb-8c7b-544dc44b600f.png)

**Comment by SimonBrandner** [comment]
We have changed the way emoji autocomplete works since, so let's close this now. Please be sure to open a new issue if you ever see a behaviour like this again
