### ISSUE TITLE
Cannot leave community located on a dead homeserver

### ISSUE THREAD

**Issue by pacien** [vector-im/element-web#10383]
### Description

It's not possible to leave a community hosted on a homeserver which died.

The community can be hidden from the side filter panel, but will stay in the user's communities page forever.

Trying to open the community's information page to leave it displays "Failed to load +community:deadhomeserver", giving the user no way to leave the community.

### Steps to reproduce

* Create a community on homeserver A
* Join this community using an account on homeserver B
* Shutdown homeserver A
* => It's now impossible for the account on homeserver B to display the community's page to leave it.

### Version information

- **Platform**: desktop
- **OS**: Linux
- **Version**: 1.3.0

**Comment by TheOneValen** [comment]
This is exactly what happened to me.
- **Platform**: Web (selfhosted)
- **OS**: Linux
- **Version**: 1.3.0

**Comment by aaronraimist** [comment]
Not sure how useful it is to track it here. It is really a Synapse issue. https://github.com/matrix-org/synapse/issues/5254

**Comment by pacien** [comment]
> Not sure how useful it is to track it here. It is really a Synapse issue. [matrix-org/synapse#5254](https://github.com/matrix-org/synapse/issues/5254)

It's both since Riot's UI offers no way to hit the "leave community" button in such situation.

**Comment by Twi1ightSparkle** [comment]
For those stumbling across this looking for a possible solution: https://github.com/Twi1ightSparkle/matrix-documentation/wiki/Leave-Community-on-Dead-Homeserver

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
