### ISSUE TITLE
Repeatedly clicking the camera icon starts multiple video calls in a direct chat

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10395]
Multiple calls in the same room seem useless, so I suppose this is unintended behaviour.  One might even want to disallow multiple calls started by different room members.  Instead, if a video call already is in progress, clicking the camera should either join it or ask whether one wants to end the call.

**Comment by turt2live** [comment]
how many people were in the room?

**Comment by Biep** [comment]
Just two.

**Comment by turt2live** [comment]
This is probably a condition of glare: https://github.com/vector-im/riot-web/issues/1325

**Comment by SimonBrandner** [comment]
Fixed by [#5712](https://github.com/matrix-org/matrix-react-sdk/pull/5712)
