### ISSUE TITLE
Can't add multiple rooms to community without manual entering each room to textfield

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#10404]
I have list of many room, that need add to community (both variants - room primary aliases and room id's), but can't do this via Riot-web interface window "Add rooms to the community".

When I manually type several rooms id's or aliases to textfield, it shows autocomplete for each room, where I can select it for convert plaintext to rendered room.

But when I paste to this textbox plaintext with list of rooms id's (like `!togciVWbBMlIUHgyVA:matrix.org, !tdGCWSxlGxRrMrRXZX:matrix.org`), it shows me error:
```
You have entered an invalid address.
Try using one of the following valid address types: Matrix Room ID.
```

I try to split room ids via space, line break, comma, quotes, etc - nothing works. Can you describe which format of room list string must I use for Riot accepts it successfully?

**Comment by turt2live** [comment]
Highly related to https://github.com/vector-im/riot-web/issues/9956 (it's the same underlying component)

**Comment by MurzNN** [comment]
Thanks, fixed via https://github.com/matrix-org/matrix-react-sdk/pull/3249 together with #9956

**Comment by t3chguy** [comment]
Not exactly, it doesn't work for room aliases as per your original issue.

**Comment by MurzNN** [comment]
As I understand, form submit accepts only ids, and when manual typing room name or alias, it replaces it to room id on demand via autocomplete.

If this will not to hard, will be good to make resolver works for bulk paste list of rooms, so let's reopen?

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
