### ISSUE TITLE
Annoying log messages in chat 

### ISSUE THREAD

**Issue by dkotrada** [vector-im/element-web#10414]
**Is your suggestion related to a problem? Please describe.**
I'am always frustrated when I look at those log messages in a chat window

```
y hat den Raum betreten.
y hat den Raum auf eingeladene User beschränkt.
y hat den zukünftigen Chatverlauf sichtbar gemacht für: Alle Raum-Mitglieder.
y erlaubte Gäste diesem Raum beizutreten.
y hat alfalive eingeladen.
x hat den Raum betreten.
x startete einen video-Anruf.
y startete einen video-Anruf.
y hat den Anruf beendet.
x hat den Anruf beendet. (Unbekannter Fehler: true)
x hat den Anruf angenommen.
x startete einen video-Anruf.
x hat den Anruf beendet. (keine Antwort)
y hat den Anruf beendet.
```

**Describe the solution you'd like**
Put those log messages in a separate tab or into setting do not show log messages

That is so obvious. Who needs those messages there? They are garbage.

**Comment by jryans** [comment]
You may be interested in these options in top left menu -> Settings -> Preferences:

<img width="577" alt="2019-07-26 at 10 21" src="https://user-images.githubusercontent.com/279572/61941340-2eb04980-af8f-11e9-87a2-481442430060.png">

**Comment by dkotrada** [comment]
Thank you. Why are those switched on by default? 
I can not find those settings on iOS client.

**Comment by jryans** [comment]
> Why are those switched on by default?

I am unsure of the history, but I would assume the idea is to make things as explicit as possible.

> I can not find those settings on iOS client.

This is the repo for Riot Web and Riot Desktop. The options may not exist on Riot iOS. You can open an issue at https://github.com/vector-im/riot-ios to request them.

**Comment by t3chguy** [comment]
Closing as it is an iOS complaint
