### ISSUE TITLE
Allow image rotation at up/download

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10431]
Currently it is possible to rotate images when viewing them, which is great.  It would be a good thing too if I could rotate an image in the process of uploading it, so that it will appear upright immediately.  Likewise, when downloading an incorrectly-oriented image, it would be good to have the option to download it in the currently-shown orientation.  I realise this means physically changing the file, and it should be opt-in.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23388
