### ISSUE TITLE
UX: Encrypted channel number of devices to verify just keeps going up

### ISSUE THREAD

**Issue by Frijol** [vector-im/element-web#10449]
![Screen Shot 2019-07-30 at 8 29 15 AM](https://user-images.githubusercontent.com/454690/62143009-23696080-b2a4-11e9-96af-fea204f0c724.png)

### Description
I'm in an encrypted room with only two people, though we're both accessing over web + Android apps. Originally, the number of devices to verify seemed reasonable (if combinatoric).  But as we keep using this room, it keeps asking us to re-verify our devices, flagging errors around unverified devices.

I understand that this is related to challenges in the underlying technology, such that you're unable to guarantee security without verifying each potentially different device. But as a UX bug, it's alarming, reduces sense of security, and inhibits adoption (e.g. I can't recommend this to my family members because they will not understand why it's telling them there are all these issues).

Potential fix: informational? A clear dialog around what that exclamation mark really means/likelihood of a real problem might help

### Steps to reproduce

- Log in on web
- Close the window
- Log in on web
- Keep doing that

Logs being sent: no (lmk if this is needed)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 
- **OS**: MacOS
- **URL**:  riot.im/app /

![Screen Shot 2019-07-30 at 8 37 16 AM](https://user-images.githubusercontent.com/454690/62143666-48aa9e80-b2a5-11e9-94d4-4135b3eeb08a.png)

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by dbkr** [comment]
Hopefully this is much better now cross-signing has landed!
