### ISSUE TITLE
Migration tool: Give admin permissions for the new account

### ISSUE THREAD

**Issue by vranki** [vector-im/element-web#10457]
This is related to the migration tool, just posted here as instructed by Matthew on Matrix HQ.

Simple feature suggestion: When the new account joins a room, the old account should give it the same admin permissions it had, if possible.

Currently after migration user must manually set admins on all channels where old account used to have admin status. This is quite annoying.

**Comment by turt2live** [comment]
I assume this is https://www.modular.im/tools/matrix-migration

**Comment by t3chguy** [comment]
This got done
