### ISSUE TITLE
Easily add translations within embeddedPages.welcomeUrl HTML file

### ISSUE THREAD

**Issue by eMPee584** [vector-im/element-web#10468]
(repost of https://github.com/matrix-org/matrix-android-sdk/issues/461)
We have a customized welcome.html and have a few strings in there that we would like to provide translations for into another language. Is there any way (`<script>magic</script>`) to add these translations from within that file without modding `i18n/strings/X.json`, recompiling it into a bundle and overlaying it into the docker image we use?

**Comment by turt2live** [comment]
Copying the code from the existing welcome page (`_t("your string here")`) and runnign `yarn i18n` over the project should pick them up. From there all you need to do is add the translations manually to the other language files and you're set.

If your audience is in a single specific language, I wouldn't bother with trying to translate anything and just put that language directly into the welcome page.

**Comment by jryans** [comment]
Hopefully the comment above answers your question. 😁 If you need further help with this, I'd suggest asking in #riot-web:matrix.org, as the interactive medium is a bit better for support.

**Comment by eMPee584** [comment]
> Copying the code from the existing welcome page (`_t("your string here")`) and runnign `yarn i18n` over the project should pick them up.

Well not all that easy; debian stretch on that server =  no yarn in repo. So by help of `docker run -it --rm --name yarn -v /usr/src/repos/riot-web:/usr/src/riot-web -w /usr/src/riot-web node bash` and manually yarn linking with `matrix-react-sdk` and stuff, I get the updated `src/i18n/strings/en_EN.json`. Now I can manually transfer the strings to my target language JSON then, and ...
> From there all you need to do is add the translations manually to the other language files and you're set.
… then still would have to rebuild the whole thing and deploy my own riot version. Which I'm not going to do because of two-five strings. Which is why I specifically asked for a way to append a small number of translations from within the HTML itself using JS.

So, my issue is not resolved as I still have untranslated strings with a target audience of two languages (EN, DE)..

**Comment by eMPee584** [comment]
Ok so basically, the `t()` function is defined in `matrix-react-sdk/src/languageHandler.js` and uses the [`counterpart`](https://github.com/martinandert/counterpart) library, which uses an in-memory dict. So there should be an easy way to insert a few keys into that array after `i18n/languages.json` has finished loading..

**Comment by jryans** [comment]
> Well not all that easy; debian stretch on that server = no yarn in repo.

It's likely possible to use `npm` as well, if that's easier to access. (We moved away from it because the linking behaviour is not great: the links are removed every time you `npm install`, so you have to keep relinking.)

**Comment by jryans** [comment]
Okay, I have flipped this back to a suggestion and reopened since it seems like there's some space to simplify this process somehow.

**Comment by eMPee584** [comment]
So to pick this back up, what I'm looking for is a small JS solution that will append particular strings to the translation tables, after they have been loaded, from within the `welcome.html` .. (this should be rather easy)

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/blob/master/docs/config.md `custom_translations_url`
