### ISSUE TITLE
State events from before join are shown in timeline

### ISSUE THREAD

**Issue by f0x52** [vector-im/element-web#10477]
After joining a room with history_visibility set to join, there's 5 state events visible in the timeline
![image](https://user-images.githubusercontent.com/23422690/62292448-bb16ac80-b466-11e9-9fd1-1ec024ebe33a.png)

**Comment by ara4n** [comment]
surely these guy should be in the state block but not the timeline block of the /sync response

**Comment by t3chguy** [comment]
Confirmed as a Synapse bug

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2403652/165925074-39afa44a-f22f-48f6-9b8e-7c7f944e3b06.png">

**Comment by t3chguy** [comment]
Moved to https://github.com/matrix-org/synapse/issues/12590
