### ISSUE TITLE
Can't paste text to Add rooms to the community text field

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#10481]
After fixing #9956 we can't paste free text to `Invite new members`, `Start a chat`, and `Add rooms to the community` text fields - every paste, even `a` symbol immediately converts them to "Unknown address" widget without visible pasted text and without ability to edit and extend them!

Here is result of pasting `a` text from clipboard:
![image](https://user-images.githubusercontent.com/336662/62313608-dd75ed80-b499-11e9-8757-4f3bd3520a82.png)

For pasting multiple items with parse and convert to widgets, I describe my suggestion here: https://github.com/vector-im/riot-web/issues/9956#issuecomment-516348155

Also maybe good to fix this issue together with #10404

**Comment by turt2live** [comment]
This now only affects the community stuff

**Comment by kettenfett** [comment]
came across this behaviour today, as community admin. It's highly irritating and should be fixed.
Not being able to edit text in field is the *worst*.

**Comment by robintown** [comment]
Communities have been replaced by Spaces
