### ISSUE TITLE
Spinner for a pending sync has gone missing

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10514]
I suspect this is what is causing https://github.com/vector-im/riot-web/issues/10513

Steps:
1. Have a large account with saved sync data
2. Send some messages before the app saves sync data again (about every 5min)
3. Refresh the app
4. See the app restore the last saved sync
5. **Expected**: A spinner to show that a `/sync` request is in flight.

This used to happen, but went away recently. Last time I remember seeing it was ~4-6 days ago.

**Comment by bwindels** [comment]
I can't reproduce this with the above steps, and haven't personally seen this either.
How large is a large account? I've tried with davetest (a fresh login though, so not too much accumulated sync data).

**Comment by turt2live** [comment]
My account has just over 3000 known rooms now.

**Comment by bwindels** [comment]
Just tried with my personal account as well, which is smaller but should have a lot more accumulated sync data, and I also manage to see the spinner when refreshing:

![spinneronrefresh](https://user-images.githubusercontent.com/274386/63533883-3d8e0b80-c4fd-11e9-9236-ccaa9ae5f858.gif)

**Comment by bwindels** [comment]
This was supposed to be fixed with https://github.com/matrix-org/matrix-js-sdk/pull/702 from september 2018 as well...

**Comment by turt2live** [comment]
I think it's a rendering problem then: I just refreshed a few times and it seems like the chrome tab freezes at different places when trying to switch from the full page spinner to the app.

Sometimes it freezes with no spinner, sometimes with spinner, and sometimes it freezes at the full page spinner and springs to life when the sync is ready.

If that's the case, I'd be happy to downgrade this to a regular bug instead of a p1 fire.

**Comment by bwindels** [comment]
Sounds good to me, and we keep an eye out for more reports.

**Comment by bwindels** [comment]
Asked Matthew if he could repro, and he couldn't either (but interestingly did see rendering blocked elsewhere while refreshing). So your theory does sound plausibly @turt2live. Would still be helpful if you could post a screen recording here if you can still repro.

Removing fire label for now though, as nobody else seems to be able to repro this.

**Comment by turt2live** [comment]
screen recordings are a bit difficult for me to do, but one of these days I'll do so with a profiler running to try and identify what's causing all the bugs like this one.

**Comment by turt2live** [comment]
I believe this has been fixed. If someone is still seeing this, please report a new issue.
