### ISSUE TITLE
Repair redacting unsent messages

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10565]
Currently, it is possible to redact messages that have not been sent (e.g. due to a broken connection).  Such redactions are not permanent, however - they undo themselves.
Either allow redacting, but then make the changes permanent, or disallow redacting unsent messages.

**Comment by t3chguy** [comment]
Probably related https://github.com/vector-im/riot-web/issues/5898

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/1345
