### ISSUE TITLE
numbers in MemberInfo power level dropdown have the wrong font

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10560]

**Comment by ara4n** [comment]
<img width="344" alt="Screenshot 2019-08-14 at 18 38 32" src="https://user-images.githubusercontent.com/1294269/63042816-bb7d6180-bec2-11e9-9206-2574397c8f03.png">

on FF68.0.1 and macOS 10.14.6

**Comment by t3chguy** [comment]
Appears to be macOS specific, the below is FF68.0.1 and Windows 10:
![image](https://user-images.githubusercontent.com/2403652/63061276-7d953300-beec-11e9-8222-42a5f517778b.png)

**Comment by t3chguy** [comment]
Cannot reproduce on FF 115.0.2 (64-bit) on macOS
