### ISSUE TITLE
Video Call doesnt use audio output option

### ISSUE THREAD

**Issue by blackshadev** [vector-im/element-web#10567]
### Description

When video calling the windows default audio device is used instead of the audio device selected in the Riot settings menu.

### Steps to reproduce

- Change the windows default audio device to something besides your headphones.
- Set the Riot voice & video  audio output to your headphones
- Start a video call
- Notice the output it the windows default instead of the riot default

I checked this with Firefox and with the desktop client. 
Moreover when doing a voice call, the device specified in the settings menu is used. So this seems like a discrepancy between the video and voice call. 

Logs being sent: yes

### Version information

For the web app:
- **Browser**: Firefox 68.0.2
- **OS**: Windows 10
- **URL**: riot.im/app/

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.3.2

**Comment by arozhankov** [comment]
+1

Desktop app:
OS: MacOS 10.15.4
Version: 1.5.15

**Comment by arozhankov** [comment]
+1 

**OS:** MacOS 10.15.4
**Version:** 1.5.15

**Comment by gutoandreollo** [comment]
+1 to this on Windows client, still persists up to Element version: 1.7.7

**Comment by SimonBrandner** [comment]
Are you all still seeing this?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
