### ISSUE TITLE
Add ability to scroll and zoom  image preview

### ISSUE THREAD

**Issue by bradinator** [vector-im/element-web#10617]
**Is your suggestion related to a problem? Please describe.**
It is a pain to be sent a large image, click to preview, and always have to download to actually see full size and details.

**Describe the solution you'd like**
Add ability to zoom and scroll on the image preview.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/3323

**Comment by robintown** [comment]
This is now a thing.
