### ISSUE TITLE
Direct chats appear in rooms list

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#10612]
### Description

Often, a new Direct Chat will not have the flag set. When I set the flag (using the menu), it won't always move from the rooms section to the Direct Chat section of the left panel. Sometimes reloading the riot page will help.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 68
- **OS**: macOS
- **URL**: riot.im/develop

<img width="482" alt="Screenshot 2019-08-22 at 10 52 26" src="https://user-images.githubusercontent.com/1197991/63505462-83ca7700-c4cb-11e9-9d8a-72dd8dcc5af5.png">

**Comment by turt2live** [comment]
@benparsons is it possible to get debug logs for this, including the room ID of that room?

**Comment by benparsons** [comment]
I'll DM you

**Comment by turt2live** [comment]
From the looks of this it wasn't sent as a DM, and when fixed the issue became one of the old room list being slow/unhelpful.
