### ISSUE TITLE
Desktop notifications from Chrome on Windows 10 are after I've read the message

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10616]
This is a recent change, as of today. It's very annoying to tab away and see a notification for the message I just finished reading

**Comment by daniellekirkwood** [comment]
This issue is old - is it still relevant? Are we still experiencing this issue?

**Comment by turt2live** [comment]
I have no reason to believe it's been fixed, but have disabled desktop notifications since 2019 and wouldn't be able to confirm reliably anymore.

**Comment by Johennes** [comment]
@turt2live I don't have access to a Windows machine. Would it be possible for you to re-test this. The original report being 3 years old and nobody else having chimed in since then looks a little odd at least.

**Comment by turt2live** [comment]
My status update from 4 months ago still applies: my environment would not be reliable for testing this.
