### ISSUE TITLE
Add an option to set default room access

### ISSUE THREAD

**Issue by sephii** [vector-im/element-web#10625]
When creating rooms, to make them appear in the rooms directory for other users, you need to set 2 options: "publish this room to the public in xxx room directory" and "anyone who knows the room's link" in "who can access this room?".

This isn't very user-friendly for people who don't know how Matrix works, and it can make it hard for new users to understand how to make their rooms public. For example I'd like to use Riot for my association, and in the current state I know people won't understand why other people cannot see their rooms or join them, and I'll probably need to give them a guide so they understand how to create public rooms.

It would be nice to either have an option so set the default "visibility" of newly created rooms, or ask the user when creating a room, whether they want it to be public or private.

**Comment by robintown** [comment]
Nowadays, creating a room prompts for whether you want to make it public or private
