### ISSUE TITLE
New composer: improve performance (if needed)

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#10631]
see how to improve performance a bit. It should be better than slate already, but profiling has shown there is probably some low-hanging fruit. It hasn't really been optimized for speed yet.

**Comment by yannicka** [comment]
If this ticket is used to track performance issues or improvements, it would be nice to indicate them here. Otherwise what is the purpose of this ticket?

**Comment by SimonBrandner** [comment]
@bwindels, have you ever looked into this or is looking into performance improvements yet to be done?

**Comment by robintown** [comment]
Closing, as this does not seem to constitute a user-facing issue at the moment. If there are specific performance bottlenecks that should be improved, new issues should be opened.
