### ISSUE TITLE
Cannot scroll using arrow keys anymore even when unfocusing message input field

### ISSUE THREAD

**Issue by jdreichmann** [vector-im/element-web#10644]
### Description

After editing messages has been introduced, the possibility to scroll through the room history using the arrow keys (up & down) has been removed, as the up arrow now selects the last sent message for editing.

Even when manually defocusing the message input field, scrolling through history using arrow keys is not possible, only with page up/down, whiich scrolls an entire half page at a time.

### Steps to reproduce

- De-focus the input field by focusing on the room history
- use the arrow keys

My expectation is that when explicitly not focusing on the input field, i can use the arrow keys to scroll. Instead it shows the box used to edit the message.

### Version information

- **Platform**: web (in-browser)?

For the web app:

- **Browser**: Firefox 68.0.1
- **OS**: Arch Linux
- **URL**: riot-web 1.3.2 self-hosted

**Comment by emiliogon** [comment]
I hope this is addressed soon, as I am frustrated by this behavior at least once a day.  I press up to go to the start of the entry field, which is completely normal for macOS.

In general, Riot should always default to the text engine behavior of its host OS, as that is what's expected by users.

**Comment by t3chguy** [comment]
This got fixed
