### ISSUE TITLE
Quoting a message with an ordered list makes the list disappear

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#10648]
# Description

Quoting a message (via Options > Quote) that contains an ordered list produces
a Markdown quote that omits this list.

### Steps to reproduce

1. Send the following message.

```markdown
test foo

1. test
2. test
3. test

test bar
```

2. Hovering over the message, select Options > Quote.

3. Observe that the produced quote is

```markdown
> test foo
>
> test bar
```

instead of the expected

```markdown
> test foo
>
> 1. test
> 2. test
> 3. test
>
> test bar
```

### Version information

- **Platform**: desktop (but I also tried it on Riot Web develop)
- **OS**: Arch Linux
- **Version**: 1.3.3

**Comment by yannicka** [comment]
I can't reproduce the issue (on Riot Desktop 1.6.0). Do you still have it?

![Peek 21-05-2020 18-49](https://user-images.githubusercontent.com/22885898/82583798-d9839b00-9b93-11ea-987a-25a9bd4a72e7.gif)

**Comment by dkasak** [comment]
No, the bug I described is not present anymore. The quoting feature is still quite buggy, though. For instance, as can be seen in your demo, the line between first two paragraphs (the text `test foo` and the list) gets eaten when it is quoted. If that message is then sent and the quoting operation repeated, more aberrant behaviour appears.

So, quoting the first message produces (also note the extra whitespace at the end):

```
> test foo
> 1. test
> 2. test
> 3. test
> 
> test bar


```

Then quoting that message produces

```
> 
test foo
> 1. test
> 2. test
> 3. test
> 
test bar


```

Then:

```


test foo
> 1. test
> 2. test
> 3. test

test bar


```

Finally:

```
> test foo
> 1. test
> 2. test
> 3. test

test bar


```

This appears to be a fixpoint and further quoting doesn't change it anymore.

**Comment by yannicka** [comment]
The composer is known to change the Markdown formatting (on edit, but it looks like it's the same with the quote): #13474, #12535, etc.

**Comment by robintown** [comment]
Most of the issues here have since been resolved, so it looks like the only thing left to fix is that quoting a quoted message (`> foo`) doesn't produce a double-quote (`> > foo`).
