### ISSUE TITLE
User confused between account and room settings

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#10655]
Account settings are accessible in the left pane under the user.
Room settings are accessible on the right.

This makes perfect sense if you grok the separation between left and right, i.e. everything right of the room list is "the room". But buttons at the top right of the window are also often global/static buttons in other apps. So this can be confusing.

Maybe a solution would be to merge account and room settings into the same dialog, and using the left and right buttons to bring up different entry points into that common dialog?

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/vector-im/riot-web/issues/9060

**Comment by aaronraimist** [comment]
Can this get needs design and FTUE labels?

**Comment by turt2live** [comment]
We don't have a FTUE label for this kind of thing, but needs-design should get it onto one of the project tracks.

**Comment by invertor** [comment]
I really do wish this gets FTUE label and attention.

Maybe as an easy short-term solution, on the room settings panel, a button of "All Settings" or "User Settings" can be simply added on the left side, which takes the user to user settings.
So if someone doesn't know where the user settings are "hidden" and clicked on the symbol of room settings ... he/she can at least reach what they were looking for.

**Comment by aaronraimist** [comment]
Mozilla has also found this 

> so there are two "Settings" menus with identical text and icons
> it just surprising how people manage to screw up with simple UI in 2020

https://matrix.to/#/!gTeEstkMlPUdxvIdCE:mozilla.org/$kY9QE2yu3XfKzRvFTuOSf0A5kkEO8QD53y0fnVkDqz0?via=mozilla.org&via=matrix.org&via=raim.ist

**Comment by aaronraimist** [comment]
I think this is pretty much fixed in 1.7.7

**Comment by turt2live** [comment]
yea, I agree
