### ISSUE TITLE
I'm not getting red highlights for most things anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10681]
Maybe messages sent by CIDER? Too many surrounding characters? They're pills with my name - it should be highlighting

**Comment by bwindels** [comment]
Hmm, can't reproduce at first sight:

![notify](https://user-images.githubusercontent.com/274386/63939014-bd642a80-ca55-11e9-94bf-04d417da438e.gif)

Any pointers?

**Comment by turt2live** [comment]
Just that messages like this don't ping:
![image](https://user-images.githubusercontent.com/1190097/63966498-a7a43480-ca58-11e9-8f9d-40d6ff8b3888.png)

```
{
    "body": "@travis:t2l.io: is this something you'd be happy to take a look at?",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@travis:t2l.io\">TravisR</a>: is this something you'd be happy to take a look at?",
    "msgtype": "m.text"
  }
```

**Comment by turt2live** [comment]
This is because of my push rules and how the highlights work rather than the new composer. 

The mscbot posts the anchor tag in the `body` which is pinging my mxid, however the label for the anchor is just "travis" when it should be "TravisR".

The new composer was doing a similar thing.

**Comment by turt2live** [comment]
... and Riot should be calculating the push rules for keywords and highlighting the message red, but it doesn't. My push rules are highly customized though, so I'm not surprised it's a bit sad

**Comment by turt2live** [comment]
I haven't seen this in the last 12 months.
