### ISSUE TITLE
Consider highlighting the chosen reactions in the picker

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10699]
Like github's new feature released today: ![](https://i.imgur.com/bRbilAN.png)

**Comment by jryans** [comment]
At the moment, we fade them if selected, but that can be a bit hard to see.

**Comment by turt2live** [comment]
I totally didn't realize that we did, but we do:
![image](https://user-images.githubusercontent.com/1190097/64029315-8ea38e00-cb01-11e9-8595-228bdde1a649.png)

**Comment by robintown** [comment]
They are now highlighted, like so:

![Screenshot 2022-04-24 at 21-20-28 Element Šimon Brandner](https://user-images.githubusercontent.com/48614497/165005918-a2935bec-7e48-47f3-b9b4-92cc1962f892.png)
