### ISSUE TITLE
keyboard focus on the enable E2E dialog defaults to cancel rather than OK

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10702]
very confusing, given the OK is a big green button, so when you hit enter, you think it's been selected rather than cancelled

**Comment by tredondo** [comment]
This is worse because when typing normally, Space will activate 'Cancel' and the user may not even notice the dialog was displayed for a split second.

We just ran into this in v1.5.15:

![image](https://user-images.githubusercontent.com/10043369/79807600-887b5e00-83bf-11ea-98bf-c2efc1d49e40.png)

**Comment by t3chguy** [comment]
The `Incoming Verification Request` dialog is going away.

**Comment by tredondo** [comment]
Ok. I also see this in the console,

![image](https://user-images.githubusercontent.com/10043369/79808943-5cfa7280-83c3-11ea-81ba-b28c187acb19.png)

Probably moot?

**Comment by weeman1337** [comment]
This dialog no longer exists
