### ISSUE TITLE
New composer: Tiny text below compose is illegable and dissappears when you click it.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#10724]
### Steps to reproduce

When I mouse over and enable text entry in the compose, there seems to be a "Code" button that is highlighted - if it's like a lot of things, I can click to select/deselect to enable or disable code mode, or something.

![click here](https://user-images.githubusercontent.com/1917473/64126527-fb3eb700-cda5-11e9-963c-948c56866faa.png)

I moved my mouse there and clicked and it went away. Success! I thought, I've done something so i won't be in Code mode.

I then started typing and it came back. 

It appears in an area of the screen that is normally otherwise empty, and it comes back every time you type, maybe just show it all the time and save cycles making it show and hide?

Also it's unfeasably small - and there's no way to resize /just/ that part of the UI, nor can you select the text to copy it into another window (see above about how it goes away when you click it) so it's not very accessible to those with normal or worse than normal vision.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 68
- **OS**: linux
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
yup, we're iterating on it (cc @nadonomy)

**Comment by yannicka** [comment]
Does this Markdown tag display still exist?

**Comment by t3chguy** [comment]
It does not, we have this now 
![image](https://user-images.githubusercontent.com/2403652/100522160-b835e400-31a0-11eb-828c-1608a086d75b.png)
