### ISSUE TITLE
Outdated rooms shouldn't show up in room searches

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10732]
When searching for this room by clicking on the plus and typing some relevant text (e.g. 'Desktop', or even 'iOS'), the first hit is the outdated version.
![afbeelding](https://user-images.githubusercontent.com/12461597/64131194-46b58d00-cdc7-11e9-8953-c2e51ee679e7.png)

**Comment by aaronraimist** [comment]
Hopefully maybe fixed on the server side https://github.com/matrix-org/synapse/issues/6638

**Comment by MadLittleMods** [comment]
Closing as the issue @aaronraimist pointed out seems like it would fix this and there hasn't been activity on this issue since ⏩

**Comment by aaronraimist** [comment]
It definitely hasn't been fixed but it is probably a server side issue https://github.com/matrix-org/synapse/issues/10075

<img width="753" src="https://user-images.githubusercontent.com/5855073/188743813-c1448e1f-8b29-447c-9b7b-a1a6cbf7e3bb.png">
