### ISSUE TITLE
CIDER: converting nested inline formatting from html > md fails

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#10745]
for example entering 
```
**`some bold code`**
```
is converted back to
```
**some bold code**
```
e.g. the backticks are missing.

**Comment by bwindels** [comment]
I think we just take the inner text when encountering an inline formatting elements, we should instead recursively look for more formatting.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8004
