### ISSUE TITLE
Hint on room directory that rooms can be unpublished

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#10740]
Today I learnt you can delete local aliases and unpublish rooms from the room directory by clicking the room in the directory while holding "shift" 💪

![Selection_267](https://user-images.githubusercontent.com/1174866/64187527-6d340080-ce79-11e9-9b99-ece1da3a22e4.png)

Would be good to have a hint to users of this possibility in the UI.

**Comment by t3chguy** [comment]
This behaviour is gone
