### ISSUE TITLE
Endless loop trying to add Slack integration

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#10743]
> I've been advised to duplicate https://github.com/matrix-org/matrix-appservice-slack/issues/182 here, because the problem may be with `vector.im` infrastructure.

I'm trying to add the Slack bridge to an existing Matrix room, using event bridging, and the bridge running on the integrations server at `scalar-staging.vector.im`. I'm using `riot-web` as provided by `https://riot.im/#/develop`

I complete all the steps up until Slack tells me that I've completed the authorization ("Your Matrix-Slack account is now correctly authorized.").

But when I close the window, the Matrix dialog goes back to the beginning and asks me to authorize with Slack, i.e. I am supposed to start from when I chose "event bridging".

I've recorded a screencast of the loop to help illustrate the point:

![slack-matrix](https://user-images.githubusercontent.com/195073/63001155-0ef1ae80-bec7-11e9-9894-e00d4dd0acf7.gif)

**Comment by YoochanMyung** [comment]
Similar issue.
In my case, I can see 'List Channels' after adding the App to Slack, but the link doesn't work (fail to show the list of channels).
<img width="456" alt="Screen Shot 2019-10-07 at 12 44 08 am" src="https://user-images.githubusercontent.com/16929897/66270118-9f32eb00-e89b-11e9-972b-ce658fdaa857.png">

**Comment by Half-Shot** [comment]
@YoochanMyung do you have any public channels on the workspace you are logged into. Also, can you share your team name (either here or in a PM to @Half-Shot:half-shot.uk)

**Comment by lspg** [comment]
Hi, same here with brand new self-hosted synapse server.
What is weird is that i managed to make it work 2 days ago with my first test install.
But now clicking the list channel has no effect anymore.
Even more weird, seems to also appends on riot.im/app, using matrix.org public server.
JS console returns "SlackScalarApi.js:76 Bridge returned HTTP 404 Not Found: Link not found"

**Comment by t3chguy** [comment]
@madduck / @YoochanMyung are you still experiencing this?

**Comment by turt2live** [comment]
Closing as presumed fixed.
