### ISSUE TITLE
FTUE: Don't distract new users with banners

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#10768]
- [ ] Include analytics consent as a checkbox when creating an account
- [ ] Display the notifications banner when the user receives their first notification instead

Notes
- Design comps are outstanding for consenting to analytics on account creation, as privacy work is up in the air. Best to quickly converge on the correct implementation when we pick up dev.
- Defer solving ILAG related banners for now (as we deemed ILAG related issues to not have a high enough ROI to track within the first round of FTUE tasks)

**Comment by t3chguy** [comment]
> Include analytics consent as a checkbox when creating an account

this would mean storing it in their account, currently, we let them control it per-device.

**Comment by daniellekirkwood** [comment]
@nadonomy  I'm going to close this as the requested items are being handled as a part of other items. Reopen if you disagree 👍
