### ISSUE TITLE
Dark theme formatting bar has very hard to see tooltip

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10784]
This is just another in the series of "X tooltip is hard to see":
![image](https://user-images.githubusercontent.com/1190097/64445561-02aadc80-d094-11e9-80bc-52d87559b519.png)

**Comment by t3chguy** [comment]
it has the same shadow as the context menus nowadays, that good enough for you?

**Comment by turt2live** [comment]
Won't know until I can test again :)

**Comment by robintown** [comment]
The app and color scheme has undergone a redesign since then
