### ISSUE TITLE
Hard crash in Chrome using formatting bar when editing

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#10787]
Wrote this message:

`- for bold, _ for italics sounds good to me`

Keyed up to edit. CMD+A to select all. Then, clicking on the code block button in the formatting bar producers a hard Chrome 'Aw, snap' crash.

Latest develop & Chrome on macOS.

**Comment by aaronraimist** [comment]
Can you still reproduce this?

**Comment by SimonBrandner** [comment]
@nadonomy, is this still an issue?
