### ISSUE TITLE
Format bar doesn't make sense on whitespace

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10788]
I'd like to bold this space please

**Comment by bwindels** [comment]
True, but unaware of any editor that disables formatting when selecting just spaces... For example, just tried in libreoffice and you can happily bold your spaces.

**Comment by turt2live** [comment]
I played with it a bit more and I think my concern is actually that it shows up too quickly. A small delay might help because it showing up right away on text I want to delete is the annoying part.

**Comment by yannicka** [comment]
I am not shocked by the presence of the formatting bar, on the other hand the behavior is astonishing:

1. It duplicate whitespaces:
![Peek 28-11-2020 14-13](https://user-images.githubusercontent.com/22885898/100516410-f4a71700-3183-11eb-9bda-4e404a5300d2.gif)

2. It ignore whitespaces:
![Peek 28-11-2020 14-16](https://user-images.githubusercontent.com/22885898/100516457-48b1fb80-3184-11eb-8363-de2877b57e5e.gif)

**Comment by t3chguy** [comment]
Nowadays it seems to no-op on whitespace so really needs to not show up
