### ISSUE TITLE
Line breaks missing when editing a numbered list with CIDER

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#10808]
When editing messages, line breaks aren't represented:

![CIDER lists](https://user-images.githubusercontent.com/4626865/64545477-a63afd80-d2dd-11e9-8fbf-221deb689efa.gif)

Related issue: https://github.com/vector-im/riot-web/issues/10807

**Comment by bwindels** [comment]
As mentioned in https://github.com/vector-im/riot-web/issues/10807#issuecomment-529556818, this is how markdown works... To change it, we'd need to define our own version of markdown and fork the parser.

**Comment by aaronraimist** [comment]
> As mentioned in #10807 (comment), this is how markdown works 

If that was how markdown worked then how can the message have line breaks in the first place?

**Comment by aaronraimist** [comment]
Code blocks do this too btw, not just numbered lists

<img width="723" alt="Screen Shot 2020-01-25 at 1 19 49 AM" src="https://user-images.githubusercontent.com/5855073/73117809-c8da5580-3f10-11ea-9844-7a3cd94ef13c.png">
<img width="720" alt="Screen Shot 2020-01-25 at 1 19 57 AM" src="https://user-images.githubusercontent.com/5855073/73117814-cd067300-3f10-11ea-91ac-8e90a6eb65f1.png">

**Comment by weeman1337** [comment]
> Code blocks do this too btw, not just numbered lists
> 
> <img alt="Screen Shot 2020-01-25 at 1 19 49 AM" width="723" src="https://user-images.githubusercontent.com/5855073/73117809-c8da5580-3f10-11ea-9844-7a3cd94ef13c.png">
> 
> <img alt="Screen Shot 2020-01-25 at 1 19 57 AM" width="720" src="https://user-images.githubusercontent.com/5855073/73117814-cd067300-3f10-11ea-91ac-8e90a6eb65f1.png">

Cannot reproduce for code blocks any more.

**Comment by weeman1337** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/25952 which has better reproduction steps.
