### ISSUE TITLE
Performance: timeline often forces layout to be calculated, taking +30ms

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#10806]
When typing in the composer (as the composer grows with newlines?), or sending a message, the timeline code will often be blocked on layout being trashed, taking over 30ms (more than the frame budget) to complete. This is causing the UI to freeze when sending messages fast for example.

![image](https://user-images.githubusercontent.com/274386/64543432-bae6b800-d314-11e9-8ee0-80201d7484ba.png)

**Comment by gsouquet** [comment]
I will be closing this issue as I believe what is described in above has been adressed

Nowadays the timeline does not get resized when a new line appears on the composer. There are other issues when sending a new message but they are not related to layout trashing as described in this ticket
