### ISSUE TITLE
Github URL should be auto-focused when opening rageshake dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10822]

**Comment by BhuvaneshPatil** [comment]
Hello @turt2live , I am relatively new to element and matrix, I don't know about rageshake, can you please me some info about it and also provide more detailed explanation about the issue. Thanks.

**Comment by vannekariabhiram** [comment]
can you please provide description

**Comment by ShivamSpm** [comment]
Hi, I am new to contributing here and would like to work on this issue. What do you mean by Github URL should be auto-focused? Do you mean when we open the 'Submit debug logs' modal, the 'GitHub issue' input box should be auto focused (screenshot attached below)? Thanks!
 
![image](https://user-images.githubusercontent.com/43480557/227811478-eb96e9ad-95a1-4da8-898f-fbe7652e885e.png)

**Comment by t3chguy** [comment]
@ShivamSpm yes

**Comment by ShivamSpm** [comment]
> @ShivamSpm yes

Thanks! Will start to work on this issue

**Comment by ShivamSpm** [comment]
I have created a [PR](https://github.com/matrix-org/matrix-react-sdk/pull/10479) for this issue
