### ISSUE TITLE
There's a weird condition that can be triggered with respect to the formatting bar

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10820]
I'll need to investigate this more before it's really possible to work on. I was typing in an encrypted room and at pixel (0,0) I had a tooltip for what the Bold button did. I did not have text selected, but the tooltip flickered with every character I sent

**Comment by SimonBrandner** [comment]
@turt2live, is this still an issue?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
