### ISSUE TITLE
URL Previews should be entirely disabled in E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10853]
i'm hearing anecdotal reports that they appear for some users in E2E rooms

**Comment by CEbhNwPM** [comment]
Please make this a priority. Currently, unprivileged users can subvert E2E encryption of private rooms by enabling URL previews. In my server logs, I found requests from the homeserver to URLs on my site that were only shared in a private Matrix room.

The fact that URLs have to be sent to the homeserver in plaintext for this feature is only an afterthought in the description of this option, yet it is far from obvious that this is somehow necessary.

There should at least be a very big warning and it should be a setting only a room admin (or someone else with explicit permission) can enable in encrypted rooms. The fact that the option says "only affects you" is very troublesome as well, when leaking all URLs clearly affects everyone in the room.

**Comment by SimonBrandner** [comment]
While I agree, users who don't know the risks of enabling URL previews isn't great, I think it should always be an option. While I want my conversations to be E2EE, I usually don't tend to mine the URLs leaking

**Comment by turt2live** [comment]
Closing because we already have this. If people are seeing otherwise, please open bug reports with new information.
