### ISSUE TITLE
The example placeholder text should be grey

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#10862]
### Description

![image](https://user-images.githubusercontent.com/1342360/64873502-1f6d8400-d641-11e9-98c4-0ea3b703fe20.png)

The placeholder text that shows when creating a community is not grey, leading me to believe that the word "example is already in there, but it's not.

### Steps to reproduce

- Go to the communities page
- Click Create Community

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v71
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17243
