### ISSUE TITLE
Home/End buttons behave unexpectedly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10916]
Currently it seems that Home/End (fn-Left/Right on macOS) are completely ignored, whereas they should presumably move the cursor to the start or end of the current line being edited.

Meanwhile, ctrl-Home/End end up scrolling the timeline to its current top or bottom.  This is of questionable use in an infinite scrolling timeline; instead it might be better (especially for screenreaders) to just have home/end and ctrl+home/end navigate the textbox instead.

Does anyone actually use Home/End (or ctrl-Home/End) to navigate the timeline?

**Comment by gergof** [comment]
On Linux and Windows when focused on the editor the home/end buttons jump to the start/end of the line as expected, but when using Ctrl+Home for example to jump to the start of the message you edit, it instead scrolls the message timeline.

**Comment by MadLittleMods** [comment]
> just have home/end and ctrl+home/end navigate the textbox instead.

This seems to work nowadays ⏩

```
Element version: 674bba1e15d2-react-2cd5b731bfb5-js-5ce68b6c1265
Olm version: 3.2.3
```
