### ISSUE TITLE
uploading large images silently fail and produce blank thumbnails

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#10914]

**Comment by ara4n** [comment]
(e.g. https://matrix.org/_matrix/media/r0/download/matrix.org/YMGWVTMYFjtsLILmqvrMpVwV). same symptoms on Riot/iOS too

**Comment by ara4n** [comment]
this turns out to be a bug in https://github.com/turt2live/matrix-media-repo

**Comment by turt2live** [comment]
riot should probably show something other than a big empty space if the image failed to render though...

**Comment by t3chguy** [comment]
This got fixed
