### ISSUE TITLE
Avatar updates don't always propagate to all rooms

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10921]
Sometimes a few rooms still use the old avatar - rooms in which /myroomavatar has NOT been used.

**Comment by aaronraimist** [comment]
I had this with display name a while back

**Comment by t3chguy** [comment]
This'll be a synapse issue, riot just calls an api to tell synapse to change it everywhere

**Comment by t3chguy** [comment]
I believe this is fixed in latest synapse, either way does not belong here.
