### ISSUE TITLE
Unnamed 1:1 rooms shouldn't change to the room alias

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#10937]
When I give a 1:1 room an alias its display name changes to that alias.  I think that is almost always unwanted.

**Comment by t3chguy** [comment]
This is in line with https://matrix.org/docs/spec/client_server/r0.5.0#calculating-the-display-name-for-a-room

**Comment by Biep** [comment]
Yes, that was pointed out to me.  Yet it seems not to serve any practical purpose in the case of 1:1 rooms.

**Comment by t3chguy** [comment]
If you still value this then please open an issue in https://github.com/matrix-org/matrix-spec
