### ISSUE TITLE
Support "hidden" private channels in Groups/Communities

### ISSUE THREAD

**Issue by joshuaboniface** [vector-im/element-web#10935]
**Is your suggestion related to a problem? Please describe.**
I'd like to take advantage of the channel grouping abilities of Communities in the Riot WebUI for private channels, *without* having those channels visible in the Community channel list.

**Describe the solution you'd like**
I'd like to the ability to add "hidden" rooms to a Community. That is, have a private invite-only room in a Community group, but only have it visible to those present in the room, and not others in the group.

**Describe alternatives you've considered**
As far as I can tell (hopefully wrong though) there really isn't a way to do this. The room shows up in the list and prevents uninvited users from joining, which is 3/4 of the way there, but it would be nice to also have it hidden from the group list while still appearing to me, a member of the room, in the group (e.g. having it shown if the Group is selected in the left group bar). Perhaps a per-channel option like "hide from community list"?

**Additional context**
Would go a long way to making Riot/Matrix more similar to Slack/Mattermost/RocketChat in this regard. I've recently replaced RocketChat with Riot for my friend chats, but we have a large number of private channels that we don't want *everyone* in the chat to know about, both for privacy and social reasons.

I'd consider this a UI feature, rather than a core Matrix feature, but if I'm wrong there please let me know!

**Comment by Viohl** [comment]
Would like to move my community off Discord, and this is a per-requisite for that to be possible

**Comment by beppe9000** [comment]
We also want to use this for internal community forum

**Comment by t3chguy** [comment]
Spaces will support this concept of secret rooms within a Space.

**Comment by tulir** [comment]
Element doesn't currently show secret rooms in spaces (rooms with `m.space.parent` events but no corresponding `m.space.child` in the space), but it should be fairly easy to show them for users who are in both the space and room.

There was some confusion about the exact power level requirements for `m.space.parent`, but it seems that checking that the sender *currently* has sufficient power level in the space is enough (no need to check what the power level was at the time of the `m.space.parent` event). The MSC mentions an issue with that system, but some support for secret rooms is better than no support.

> The requirement that `m.space.parent` links be ignored unless the sender has a high PL in the parent room could lead to suprising effects where a parent link suddenly ceases to take effect because a user loses their PL in the parent room. This is mitigated in the general case by honouring the parent link when there is a corresponding `m.space.child` event, however it remains a problem for "secret" rooms.

**Comment by t3chguy** [comment]
> I'd like to the ability to add "hidden" rooms to a Community. That is, have a private invite-only room in a Community group, but only have it visible to those present in the room, and not others in the group.

This is already possible with Spaces, you'll only see a room if you are able to join it without an invite.
