### ISSUE TITLE
Better Olm logging

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#10955]
There's a number of things in Olm that would be really useful when diagnosing UISIs but are only visible within the c layer of Olm, most notably the state of the Olm ratchets for Olm sessions.

It would be super useful to add, say, olm_describe() which returns a string description of a given object - in the case of sessions, including the ratchet state. We'd then have to do a release of olm and add logging that called it in all 3 SDKs.

**Comment by turt2live** [comment]
Closing in favour of https://gitlab.matrix.org/matrix-org/olm/-/issues/11
