### ISSUE TITLE
Impossible to rejoin specific room (MatrixHQ)

### ISSUE THREAD

**Issue by Xananax** [vector-im/element-web#10976]
### Description

After having been banned by mistake from MatrixHQ, my ban was lifted, but I was unable to join, because of https://github.com/matrix-org/synapse/issues/1563#issuecomment-297949541. My local Synapse server still thought I was banned.
As instructed in the issue above, I created a new user ("imbanned:mutnt.io"), and joined the room, which kicked my Synapse into gear; I was not considered banned anymore.
Following that, I tried joining the room, but only got the spinner for an indefinite amount of time, and as a result am never able to speak in the room

Strange things:
1. My other user, as well as users on other instances, do see my main user joining correctly
2. As far as I can tell, my Synapse is doing nothing weird
3. As far as I can tell, my network calls are all succeeding

### Steps to reproduce

- Get banned from a large and old room
- Get unbanned
- ...?
- Profit!

#### What I see from  `imbanned:mutnt.io`
![image](https://user-images.githubusercontent.com/836082/65766738-88222980-e134-11e9-9a28-e674feef7276.png)
> The view from my new user. Notice "xananax" has joined, was kicked, joined again

#### What I see from  `xananax:mutnt.io`
![image](https://user-images.githubusercontent.com/836082/65766809-b1db5080-e134-11e9-8b55-089938ab530b.png)
> The view from my main user. Notice the room as synchronized, but I can still not write. If I press "join", I just get an infinite spinner

Log: sent

### Version information

- **Platform**: Riot web and Riot desktop both

For the web app:

- **Browser**: Firefox 69.01
- **OS**: Arch Latest as of yesterday
- **URL**: riot.im/app, Latest version as of today

For the desktop app:

- **OS**: Arch Latest as of yesterday
- **Version**: 1.3.6

**Comment by aaronraimist** [comment]
Is this a Riot issue or just https://github.com/matrix-org/synapse/issues/1563?

**Comment by Xananax** [comment]
Unfortunatetely, I do not know enough nor Synapse, nor the Matrix protocol, nor Riot enough to know.

As far as I can observe, it seems to me like all calls are being sent correctly (Riot does send a request to join), are answered correctly (I receive a 200), and other people see me as having joined.  
Because of this, I cannot discount the possibility that this is an interface problem, Riot somehow not "realizing" I have actually joined the room.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/1563
