### ISSUE TITLE
I18n strings contains several references to turn.matrix.org, which should be parameters

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#10999]
This was reported by someone attempting to translate the strings, and pointed out to me that there isn't much point asking translators to translate strings with hardcoded values like this which will only create more work should the turn server ever be changed.

It would surely be preferable to hard-code this in the application, and make this a string parameter?

Offenders are:
- https://github.com/matrix-org/matrix-react-sdk/blob/55e834f0aeb6bdcd94894cf5b61e15bb13f73489/src/i18n/strings/en_EN.json#L33
- https://github.com/matrix-org/matrix-react-sdk/blob/55e834f0aeb6bdcd94894cf5b61e15bb13f73489/src/i18n/strings/en_EN.json#L34
- https://github.com/matrix-org/matrix-react-sdk/blob/55e834f0aeb6bdcd94894cf5b61e15bb13f73489/src/i18n/strings/en_EN.json#L370
- https://github.com/matrix-org/matrix-react-sdk/blob/55e834f0aeb6bdcd94894cf5b61e15bb13f73489/src/i18n/strings/en_EN.json#L1697

**Comment by turt2live** [comment]
The strings mentioned are a last resort to try and get calls working, so it makes sense to hardcode the thing into it because it's also hardcoded into the code.

**Comment by Half-Shot** [comment]
Fair, but if we ever did want to change that server, we would have to ask every translation to be done again. I guess if we are fine with that, this can be closed.

**Comment by turt2live** [comment]
tbh it's probably something we should fix, but I don't imagine it being near the top of the list. Getting new translations for strings happens very often anyhow.
