### ISSUE TITLE
Make visibility of user list room-dependent

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#11002]
In 1:1 rooms I normally don't want to see the userlist, whereas in group discussions I might.  Currently, that means I need to change this whenever I change rooms.  I would be better if this setting was remembered per room - and if defaults for 1:1 rooms and multiperson rooms could be set.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/11000

**Comment by robintown** [comment]
The state of the right panel is now remembered per-room
