### ISSUE TITLE
After sending a reaction, focus should be returned to the composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11023]
I'm using CIDER, if it matters

**Comment by jryans** [comment]
@turt2live We now focus the composer when typing, is that enough? It's not quite the same, but at least your characters go to the composer if typed...

**Comment by turt2live** [comment]
It'd be better if the cursor was in the right place, as generally the confidence in riot doing the right thing when smashing the keyboard is a bit low.

**Comment by yannicka** [comment]
I don't know if this is necessary since writing puts the focus back on the composer (and for example, neither Discord nor Slack puts the focus back on the composer).
