### ISSUE TITLE
1:1 voip just doesn't work on FF any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11053]
i can't remember the last time I placed or answered a 1:1 call on FF and got anything other than call media failed

**Comment by bwindels** [comment]
related: https://github.com/vector-im/riot-web/issues/10993

**Comment by bwindels** [comment]
Fwiw, I have managed to do a video webrtc call a two days ago on FF 69 on Linux. Audio did not seem to work for some reason. I only tried once though, and video work straight away after that.

**Comment by jryans** [comment]
This appears to work for @lampholder and I when we're both on Firefox for macOS at least.

@ara4n, can you provide more details here? Any idea what browser the other party is using? Are you allowing peer to peer for 1:1 calls in Settings?

**Comment by jryans** [comment]
Removing from inferno for now until we better understand the impact.

**Comment by ara4n** [comment]
Amandine & I just went through testing the permutations of { Chrome, FF, Riot/iOS } <-> FF on both wifi & mobile data.  The main flakey one was Chrome->FF both on same wifi, as per https://github.com/matrix-org/riot-web-rageshakes/issues/1944 and https://github.com/matrix-org/riot-web-rageshakes/issues/1945. Two different failure modes; first time the call was instantly rejected; second time there was no video.

**Comment by ara4n** [comment]
(FF->Riot/iOS video was also broken as per https://github.com/vector-im/riot-ios/issues/2841)

**Comment by Newbytee** [comment]
I'm experiencing this calling an Android client from Firefox. I was able to receive a call, however it errored out saying "unknown error" and I did not get a popup asking me whether to accept it or not. Also, when I pressed the call button nothing visibly happened at all.

**Comment by SimonBrandner** [comment]
Are you all still having issues with this?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
