### ISSUE TITLE
Video Thumbnail is stretched/rotated

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#11068]
Step to reproduce:

1) upload the following video by drag n drop in riot-web https://matrix.org/_matrix/media/r0/download/matrix.org/JYlXQXkhRoQAzYcWXKRThjqm

2) -> the video thumbnail looks like this:
<img width="215" alt="image" src="https://user-images.githubusercontent.com/9841565/66292292-3facfd80-e8e4-11e9-8acb-14de04035fd4.png">

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/ed1fc2a7-163e-46a6-8d55-af2b44ec9768)

Looks to have been fixed
