### ISSUE TITLE
Rageshakes should include the HS version

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11070]
It would be helpful to include the homeserver version in the rageshake metadata. 

I suppose the `Server` header on responses is not a reliable indicator (as it can be masked by a CDN), but maybe still worth including?

We could also request `_synapse/admin/v1/server_version` from the HS, but that's obviously Synapse-specific.

**Comment by t3chguy** [comment]
> We could also request _synapse/admin/v1/server_version from the HS, but that's obviously Synapse-specific.

And not exposed on matrix.org as it does not forward `/_synapse/` reqs beyond the HAProxy

**Comment by turt2live** [comment]
Would be good for a server info endpoint, if we ever pick one of the 3 MSCs...
