### ISSUE TITLE
Consider a Telegram-like tab shutdown

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11088]
When you open multiple Telegram tabs, your older tabs close themselves with a dialog saying you opened a new tab

**Comment by t3chguy** [comment]
What if you want two rooms open side-by-side without our dead grid support :(

**Comment by turt2live** [comment]
Riot murders itself if you have multiple tabs open, so that sounds like the least of your problems

**Comment by jryans** [comment]
Hmm, the seems a bit arbitrary and goes against how most things on the web work today...

@turt2live What do mean it "murders itself"...?

**Comment by turt2live** [comment]
it tends to have conflicting writes to the underlying store, which leads to all kinds of fun problems. It's unlikely to be noticed as murdered until the page reloads or further down the line.

**Comment by turt2live** [comment]
we value multi-tab as a feature these days
