### ISSUE TITLE
Missed calls are entirely wrong in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1108]

**Comment by ara4n** [comment]
<img width="495" alt="screen shot 2016-03-04 at 22 51 20" src="https://cloud.githubusercontent.com/assets/1294269/13543771/70f4be06-e266-11e5-9115-cfb2c2514920.png">

**Comment by ara4n** [comment]
can't work out how to repro this...

**Comment by SimonBrandner** [comment]
Doesn't look like a problem anymore
