### ISSUE TITLE
Production error log viewer that translates stacks (Sentry)

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11111]
A lot of time is wasted when investigating stack traces from production when we have to translate stacks from minified code into something human readable.

Source maps contain the info needed to do this translation. We should either create a log viewer that does the translation or send errors to a self-hosted Sentry-like tool that already handles this step.

**Comment by t3chguy** [comment]
+11111 for Sentry

**Comment by turt2live** [comment]
Sentry is already used by the synapse team, so it seems logical to use that

**Comment by jryans** [comment]
I'll attempt a prototype in this space.
