### ISSUE TITLE
DC: Hide avatar and username

### ISSUE THREAD

**Issue by jolyjf** [vector-im/element-web#11127]
I would suggest removing some of the visual clutter in a Direct Chat. Doesn't seem necessary to include the avatar and the username for every event. You can tell who you're having a conversation with just by looking at the room's title. Maybe use 2 colors to differentitate between yourself and the other party? I feel like it would make the conversation more fluid.

Alternatively, and more in line with IRC, the username could appear in front of each message instead of on top of it. This would save some screen real estate.

**Comment by aaronraimist** [comment]
Closing in favor of #16220 since it has more thumbs
