### ISSUE TITLE
Voice/video conference has microphone/camera enabled by default

### ISSUE THREAD

**Issue by Hi-Angel** [vector-im/element-web#11130]
### Description

When joining a voice/video conference, camera and microphone are always enabled by default. This creates a bunch of useless noise when there're many people, especially if they left/join as the conference goes.

### Steps to reproduce

1. Create a new room
2. In the room, click `Manage integrations` icon, and choose `Jitsi`.
3. Press `Join conference` *(this should result in you joining the meeting/conference)*.

#### Expected

Your camera and microphone are disabled until you explicitly decide to turn them on.

#### Actual

Camera and microphone are already enabled.

### Version information

- **Platform**: desktop
- **OS**: Archlinux
- **Version**: 1.4.2

**Comment by Mathias-g** [comment]
Yeah, this is creepy and a rather big issue for people who don't want to show their face.

**Comment by ErikPrantare** [comment]
This has been bugging me too for a while, creates unnecessary risk when people don't expect to be seen.

**Comment by apbendi** [comment]
Sill experiencing this in 2022 with version 1.9.8 on macOS 12.0.1. Disappointed to see it's been a problem for 2 years! Any plans to fix this?

**Comment by novocaine** [comment]
The newest version of Jitsi - now that we've deployed it to Element's default Jitsi instance - prompts you to choose this option, which I think resolves this issue for most people: 

<img width="554" alt="Screenshot 2022-01-10 at 12 08 29" src="https://user-images.githubusercontent.com/57377/148763821-60fe2ca1-06fb-404d-8061-8576b62ebdd9.png">

Does this not work for someone's use case?

**Comment by novocaine** [comment]
Closing, please raise if this doesn't help you
