### ISSUE TITLE
If you disable notifications for the account Riot still asks you to enable notifications after login

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#11144]
https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$k-lk1uuD0STfP4H32XZeBCNmJUfPuA61KmN0uHKOsHA?via=matrix.org&via=privacytools.io&via=feneas.org

![Screen Shot 2019-10-15 at 1 13 36 PM](https://user-images.githubusercontent.com/5855073/66857799-a4540200-ef4d-11e9-9329-a43468734ca3.png)
![Screen Shot 2019-10-15 at 1 13 18 PM](https://user-images.githubusercontent.com/5855073/66857801-a4540200-ef4d-11e9-9b85-601fb0cba480.png)

The prompt to enable notifications doesn't even work since they are disabled for the entire account. What the user would like is that if they have notifications disabled on the account then they don't want to be prompted to enable notifications on login.

**Comment by Biep** [comment]
Both options - turning them off for the device and turning them off for the account - should exist.

**Comment by aaronraimist** [comment]
@Biep they do.

**Comment by Biep** [comment]
Oh - so one just isn't working then..?

**Comment by t3chguy** [comment]
This got fixed
