### ISSUE TITLE
Integrate Emote Librarys

### ISSUE THREAD

**Issue by 240hz** [vector-im/element-web#11152]
**Is your suggestion related to a problem? Please describe.**
NO.

**Describe the solution you'd like**
ad the ability to Integrate and use FFZ/BTTV emote librarys.

**Describe alternatives you've considered**
Copy and paste the desierd emote's *.png when wanting to use an emote.

**Additional context**
Emote Library:
https://betterttv.com/emotes/top
https://www.frankerfacez.com/emoticons/

Project pages:
https://github.com/FrankerFaceZ/FrankerFaceZ
https://github.com/night/BetterTTV

**Comment by robintown** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/2648
