### ISSUE TITLE
seshat doesn't understand room versions

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11155]

**Comment by jryans** [comment]
@poljar Is this a Seshat issue or something in the Riot integration layer?

**Comment by poljar** [comment]
Both, some initial table changes for Seshat were made to support this, but no public API yet. The crawler logic will need to be slightly modified as well.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-desktop/issues/909
