### ISSUE TITLE
Name and avatar changes should not trigger rooms to become unread

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11162]
When someone changes their name or avatar, we seem to mark every room that we shared with them as unread (because of the `m.room.member` event).

At first glance, we already try to filter these events out of the unread handling, so something a bit more mysterious must be happening...

**Comment by turt2live** [comment]
If the room is mentions only then this doesn't happen. If you're seeing it after refresh, it's a duplicate of one of the other "randomly bold" bugs.

All Messages tends to do this iirc.

**Comment by turt2live** [comment]
Duplicate of 
https://github.com/vector-im/element-web/issues/110 and/or https://github.com/vector-im/element-web/issues/12063
