### ISSUE TITLE
image lightbox UX bad

### ISSUE THREAD

**Issue by hramrach** [vector-im/element-web#11163]
### Description

The lihgtbox requires a lot of mousing around to use. You click an image, the lightbox opens, to the right is the download button, to the far top-right are the rotation buttons and the close button.

I don't expect people mass-rotate images in the Matrix web ui which leaves two most commonly used functions: close and download, in this order. As in you need to close nearly every image and you might want to download some. The download button is decent size and not too far from the image itself which is acceptable. However, the X close button is tiny and very far from the middle of the window where you clicked to open the light box in the first place. You can use the Esc key but  this is not obvious and you have to reach for the keyboard which may be even worse than reaching for the X button in various situations.

There is not good reason for these common actions to be so hard to perform. Most of the lightbox does absolutely nothing.

So the proposed change:

- when you click outside of the image and any other controls the lightbox should close. This is most common action and gets large target.
- when you click the image perform download or full-size view if/when that gets implemented.

related: #3323 #10617

### Version information

- **Platform**: web 
- **Browser**: Chromium 77.0.3865.90  
- **OS**: Linux
- **URL**: riot.im/app 
matrix-react-sdk version: <local>
riot-web version: 1.5.0
olm version: 3.1.3

**Comment by aaronraimist** [comment]
Clicking outside the image does close it now, is that sufficient for you to close this issue? Any future behavior for viewing as full size would be covered under https://github.com/vector-im/riot-web/issues/3323

**Comment by hramrach** [comment]
There is still #12933 which prevents this from really working

**Comment by jackkinsey** [comment]
I'd add to this--I use a vertical monitor for Element, and due to the way the lightbox sizes images/the presence of the UI widget on the right side, viewing an image in the lightbox usually ends up not making it any larger. I'd propose slimming down that UI, probably placing it in a line below the image being displayed, which would work for both landscape and portrait aspect ratios.
