### ISSUE TITLE
Allow pills for absent people

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#11166]
I just discover that I can no longer copy pills.  As one cannot make pills for invited people who haven't entered yet, I used to copy their pills from other rooms when I wanted to write them messages.
Please allow pills for people not present!

**Comment by Biep** [comment]
The popup when typing @ could have a (+) sign at the end, and clicking that would open the general name picker that also shows when inviting new people to a room.
Making pills for absent people is also useful when referring someone: _here is the general admin of the community, click on the pill to get into contact_.

**Comment by aaronraimist** [comment]
Just a note: you should be able to copy pills into other rooms again now

**Comment by Biep** [comment]
Yes - in fact I have done so already.  But it is clumsyish, and still only allows for people you are in contact with.

**Comment by MadLittleMods** [comment]
With the [recent pills update](https://github.com/matrix-org/matrix-react-sdk/pull/10417), I see one for "Unknown user permalink" which seems to address this issue:

![](https://user-images.githubusercontent.com/558581/233143198-8c7ec66a-e480-4d93-80e7-ef80108919b7.png)
