### ISSUE TITLE
/plain doesn't work with replies or edits

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#11170]
When trying to reply with /plain, the reply is just ignored. When trying to edit with /plain, the /plain is taken literally and the message is parsed as markdown

![plain reply](https://user-images.githubusercontent.com/4224639/67191338-1dde6b00-f3fa-11e9-87f3-d030ce41d19e.gif)

![plain edit](https://user-images.githubusercontent.com/4224639/67191326-19b24d80-f3fa-11e9-8893-cfc03a69df4f.gif)

**Comment by grinapo** [comment]
same with 
```
/plain - hello
- what
- nothing
```

**Comment by aaronraimist** [comment]
Since the reply part has been fixed maybe this should be closed in favor of https://github.com/vector-im/element-web/issues/16531
