### ISSUE TITLE
Lost I-beam cursor on multiline timeline messages that I sent, but only on the first line

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11191]
I don't really know what happened. Screenshots:

![](https://i.imgur.com/LcmVSZA.png)
This is good. I have the right cursor.

![](https://i.imgur.com/86N0jlC.png)
I should have an I-beam cursor, but what?

![](https://i.imgur.com/x7Yxvvo.png)
But when the message fits on one line, it's fine?

----

Worse: it seems to only affect messages that I've sent. Other people's messages don't have the same behaviour.

Chrome on Windows 10, web. riot.im/develop

**Comment by turt2live** [comment]
@t3chguy have your accessibility changes affected the timeline at all yet?

**Comment by t3chguy** [comment]
Not yet

**Comment by t3chguy** [comment]
Cannot reproduct in Desktop app, also cannot screenshot as it doesn't include cursor

**Comment by t3chguy** [comment]
Can reproduce on desktop. Can "fix" by removing 
![image](https://user-images.githubusercontent.com/2403652/75116392-d3972000-565f-11ea-9ef0-e85f87712da7.png)
from `.mx_EventTile_body` but cannot explain why
