### ISSUE TITLE
Unable to decrypt message error hidden for edited messages

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#11194]
### Description

![image](https://user-images.githubusercontent.com/1342360/67380228-eac6e380-f581-11e9-9814-ec27e55fde65.png)

The usual Unable To Decrypt error is hidden on non-decryptable messages which have been edited.

It's worth noting that my homeserver was experiencing some slowness during this time, which would explain the UTD errors, but not why the error was hidden.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v72a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by anoadragon453** [comment]
Getting this again today:

![image](https://user-images.githubusercontent.com/1342360/72424939-b0cf3d00-377e-11ea-92e5-b68e62e3554c.png).

Sending more logs.

**Comment by turt2live** [comment]
This is a feature for "show hidden events".
