### ISSUE TITLE
Able to kick myself 

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-web#11273]
### Steps to reproduce

-create a room
-make sure you are the owner
-kick or ban yourself
-observe

### 

- **Platform**: Desktop

- **OS**: Windows
- **Version**: 1.5.0

**Comment by aaronraimist** [comment]
When all the members of a room leave it becomes unjoinable. Hopefully soon the server will fully delete the room once all members leave (https://github.com/matrix-org/synapse/issues/6586).

**Comment by t3chguy** [comment]
Closing as per above, there's a myriad of other issues re joining an empty room
