### ISSUE TITLE
investigate using picture-in-picture API for Jitsi & Native videocalling

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#11361]

**Comment by t3chguy** [comment]
https://caniuse.com/#search=picture%20in%20picture

**Comment by turt2live** [comment]
please let's not confuse ourselves with python...

**Comment by bwindels** [comment]
Chrome supports the API to do this programatically already, but firefox doesn't yet. https://caniuse.com/#feat=mdn-api_pictureinpicture says it's not on a standards track in spite of https://w3c.github.io/picture-in-picture/ :thinking: 

Also, you can only do this to one video, so you probably can only show the remote feed?

**Comment by SimonBrandner** [comment]
Closing in favour of [#15887](https://github.com/vector-im/element-web/issues/15887)
