### ISSUE TITLE
Implement all states for new IconButton as per design

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#11390]
Design at https://www.figma.com/file/KhVjYAzy4oX3eIqwu9KQxN/Design-Kit?node-id=434%3A28

Split of from https://github.com/vector-im/riot-web/issues/11222

**Comment by kittykat** [comment]
I'm going to close this issue for now as designs have changed since it's been filed. Please open a new issue if you feel that there are improvements to be made.
