### ISSUE TITLE
Consider adding an 'edit' button to state events in the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11397]
for devtools. Almost certainly would need a developer flag to enable this. Use case is trying to edit widgets in a room, which have about 4000 options because the state key changes often

**Comment by t3chguy** [comment]
You can always go via devtools -> explore room state -> ... -> ... -> Edit

![image](https://user-images.githubusercontent.com/2403652/70228152-c9920f00-174b-11ea-8efe-daf112358661.png)

**Comment by turt2live** [comment]
Yes, though if you are trying to figure out which state_key you need to care about it gets difficult. Another option is an edit button on the view source dialog.

**Comment by t3chguy** [comment]
reusing the same dialog between devtools and view source would be sane and allow for that. If it only shows for people with perms then i don't think it'd need to be behind a switch

**Comment by turt2live** [comment]
This is one of those features we should mock up ourselves and shove into the product team's view for input.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/6429

**Comment by t3chguy** [comment]
Before:
![image](https://user-images.githubusercontent.com/2403652/71785179-88b04300-2ff4-11ea-9257-b41ad699a6e4.png)
After:
![image](https://user-images.githubusercontent.com/2403652/71785203-bbf2d200-2ff4-11ea-886e-2be6dda44cda.png)

The `Edit` would only show if permissions allow for it obviously, if someone is looking at event sources then they can be trusted with this surely.
