### ISSUE TITLE
powerlevel level in the new UserInfo is confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11415]
saying i am 'Default in Matthew' is... weird. 'Default permissions' perhaps?  Also, should we even expose this in DMs?  We certainly shouldn't label the PL based on the name of the user in a DM (as amusing as declaring that Matthew is 'Default in Alice' is).

**Comment by turt2live** [comment]
+1 to not showing this in DMs.

**Comment by niquewoodhouse** [comment]
imo its confusing to have this in DMs.  DMs are direct conversations between equals, or at least places where people should feel they're equals in terms of rights to communicate.  Showing this goes against that sentiment.  So I'd +1 on not having this for DMs.
