### ISSUE TITLE
h265 issues

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#11417]
riot-web version: 1.5.3 opened as app from https://packages.riot.im/debian plays sound but no video (preview image is always shown)

android and ios clients works fine, video is taken with org.lineageos.snap v 2.02.015 from LNGOS 16 (Android 9) H265 720p

**Comment by 532910** [comment]
mpv plays it:
```
...
[vd] Codec list:
[vd]     hevc - HEVC (High Efficiency Video Coding)
[vd]     hevc_qsv (hevc) - HEVC (Intel Quick Sync Video acceleration)
[vd]     hevc_v4l2m2m (hevc) - V4L2 mem2mem HEVC decoder wrapper
[vd]     hevc_cuvid (hevc) - Nvidia CUVID HEVC decoder
[vd] Opening decoder hevc
...
```

**Comment by 532910** [comment]
H264 works fine in web version: 1.5.3 opened as app from https://packages.riot.im/debian, but in ff it says the same: "No video with supported format and MIME type found."

**Comment by spacemanspiff2007** [comment]
I have the same issue and it is quite confusing since it shows the bar with video controls and the preview window but doesn't play the video. 

At least a proper error message would be nice.

**Comment by t3chguy** [comment]
https://caniuse.com/#feat=hevc
Browsers just don't seem to support this yet. I don't know if the app can easily tell if your browser successfully plays the thing or not.

**Comment by spacemanspiff2007** [comment]
I understand where this is coming from, but it is really annoying that I can play some videos directly on my mobile devices but it still shows the play button in the desktop client even though it doesn't work :-(

**Comment by t3chguy** [comment]
Not really something riot can do much about. Youd have to download and use a proper media player if your browser doesn't support it

**Comment by 532910** [comment]
1. riot should warn about this on upload
2. riot-web should show exact error instead of just showing no video
3. riot can recode video on upload

**Comment by spacemanspiff2007** [comment]
> Not really something riot can do much about. Youd have to download and use a proper media player if your browser doesn't support it

It's okay that it doesn't play, but I expect some kind of error message.

**Comment by t3chguy** [comment]
> riot should warn about this on upload

I don't think the browser even tells riot, it'll just say `video/mp4`

> riot-web should show exact error instead of just showing no video

same case with browser not disclosing this.

> riot can recode video on upload

riot-web can't without huge WASM libraries: https://www.libde265.org/blog/2014/04/10/libde265-js-javascript-hevch-265-bitstream-decoder/

**Comment by 532910** [comment]
> riot-web can't without huge WASM libraries

What about riot for android? I'm sure hevc uploading is more frequent for android (ios?).

**Comment by t3chguy** [comment]
wrong repo for riot-android queries, android devs don't monitor riot-web issues.

**Comment by spacemanspiff2007** [comment]
It plays on android, depending on the hardware. 
I have a Sony which plays anything until x265 1080p and then just shows the image again, my OnePlus plays x265 4k.

**Comment by G2G2G2G** [comment]
This is likely never going to get added because of AV1 
https://caniuse.com/av1
it's already at the status of vp9 / vp8, they're barely gaining apple support.. 
https://caniuse.com/webm
since apple's an AOM member I expect it'll take less than 10 years for them to add this one, hopefully.
so yea I don't see them ever adding h265 support because of royalties. 
h264 has a royalty too but [Cisco](https://www.cisco.com/) basically bought a license for the entire planet.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14330 to encompass h265/hevc issues

AV1 and WEBM should both already work
