### ISSUE TITLE
Show room avatar on invites in the room list

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#11423]
<img width="284" alt="Screenshot 2019-11-19 at 11 06 48" src="https://user-images.githubusercontent.com/4626865/69142116-06a8a100-0abe-11ea-8b28-8c93506f8fcb.png">

Not sure if this is a bug or a thinko.

In the room list, invites display the room name with the user avatar of the person who invited you. The mismatch of information feels incorrect & misleading.

We should show the room avatar & name in the room list, and then expand with tertiary information (i.e. who invited you) when viewing the invite.

**Comment by turt2live** [comment]
I feel like we used to show the room avatar, though it's possible that we have a bug where if the room has no avatar (as is the case with seshat) then we use the sender?

**Comment by nadonomy** [comment]
If it turns out to be a bug, then I think we should fall back to the first letter of the room name on a background, as we do for users & groups.

**Comment by turt2live** [comment]
going to count it as a bug for now until proven otherwise

**Comment by t3chguy** [comment]
This is a server/spec issue where we don't get sent an avatar so instead we fall back to the avatar of our inviter because we don't know better: https://github.com/matrix-org/matrix-react-sdk/blob/38549ecf4c8a2e645f636a5639fc67399d59653c/src/Avatar.js#L169

**Comment by turt2live** [comment]
This seems fixed: 
![image](https://user-images.githubusercontent.com/1190097/91758717-ad61b800-eb8d-11ea-99f5-3031f1a5209e.png)
![image](https://user-images.githubusercontent.com/1190097/91758731-b2266c00-eb8d-11ea-9a13-ab24ef1526d5.png)

If it's not fixed on matrix.org, those folks should update their synapse config to send avatars in the invite state.
