### ISSUE TITLE
User directory results very often have no avatar

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11433]
The user directory results very often have no avatar making it incredibly hard to guess which of the various kegans I'm inviting is the right one.

**Comment by MadLittleMods** [comment]
It seems like this issue pertains to the `Invite to xxx` modal that you find from going to the member list in the right panel -> **Invite to this room**

![](https://user-images.githubusercontent.com/558581/131784804-f9bfa35c-74e6-429e-9035-5a42a516b925.png)



Which also seems to share UI with the `Direct Messages` conversation starting modal accessed via the people section in the left menu -> **+ Start chat**

![chrome_2021-09-02_00-01-05](https://user-images.githubusercontent.com/558581/131784652-1508aebd-7042-4973-9cfc-959d2bde7fd9.png)

**Comment by t3chguy** [comment]
Closing, if you still see this bug please open an issue in https://github.com/matrix-org/synapse/
