### ISSUE TITLE
red badges in room list when not being mentioned

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#11476]
after changing my displayname to '[uhoreg]', I sometimes get red badges in my room list, indicating a mention, but I'm not mentioned.  It seems to be somewhat random -- I haven't been able to figure out what in the message causes it

**Comment by daniellekirkwood** [comment]
Is this still a relevant issue?

**Comment by uhoreg** [comment]
I don't remember filing this in element-web.  This turned out to be a backend issue, which I think has since been fixed.
