### ISSUE TITLE
A message sometimes appears again in the composer after sending, switching rooms and then switching back

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#11470]
### Description

I've noticed this only very recently, but it's happened twice now. Seems to happen sporadically. 

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v72.0a1
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by yannicka** [comment]
Do we have more information on when this happens?

**Comment by SimonBrandner** [comment]
@anoadragon453, have you seen this recently, I've never seen this before and there don't seem to be any other reports of this

**Comment by anoadragon453** [comment]
Nope! Probably an old bug that's long since been fixed. Thanks for checking in!
