### ISSUE TITLE
Message Composer Bugs

### ISSUE THREAD

**Issue by jph168** [vector-im/element-web#11477]
### Description

When you post a message with two automated addins(BOLD/Italics etc) on one word and edit that same line, message composer removes the 2nd addin on the word. Another easily reproducible issue is not being able to use "/" commands while in message editing composer(After you've posted the message the first time you cannot).

### Steps to reproduce(Gladly this is easily reproducible)

- Post a message with two addins on one word or more using the highlight tool
- Go to edit message and one of the addins on it will be gone.

### Describe how what happens differs from what you expected
A menial bug but expected it to keep what a user had typed.

Debug Log: sent   

![Screenshot_2019-11-22_15-15-15](https://user-images.githubusercontent.com/31376624/69466968-ffda9200-0d3a-11ea-8bf3-1ee344a2bf45.png)
![Screenshot_2019-11-22_12-10-17](https://user-images.githubusercontent.com/31376624/69457613-4e2f6700-0d22-11ea-872c-c3d03f3dfb84.png)
![Screenshot_2019-11-22_12-10-52](https://user-images.githubusercontent.com/31376624/69457627-58e9fc00-0d22-11ea-9fe1-9fa164eabe58.png)
![Screenshot_2019-11-22_12-11-21](https://user-images.githubusercontent.com/31376624/69457636-5be4ec80-0d22-11ea-9c21-deb29c8eec51.png)
### Version information
1.5.4-rc.1

- **Platform**: web (in-browser) or desktop?
Both Web and Desktop Platforms + Stable/Unstable
For the web app: Chrome

- **Browser**: Chrome Version 78.0.3904.97-1
- **OS**: Manjaro
- **URL**: Affects riot.im/develop, riot.im/app 

For the desktop app:

- **OS**: Manjaro
- **Version**: 1.5.4-rc.1

**Comment by MadLittleMods** [comment]
Thanks for creating an issue to track this! 🙂  I'm closing in favor of https://github.com/vector-im/element-web/issues/17610 which reads a bit easier to get acquainted with the problem.

Also related to https://github.com/vector-im/element-web/issues/10725
