### ISSUE TITLE
It's extremely difficult to tell whether or not you are muted on a HIDPI screen

### ISSUE THREAD

**Issue by Kommynct** [vector-im/element-web#11485]
It'd be much better if the mute icon became red, but as is there seems to be a 1px wide line through it.

I like to keep my stuff TINY, and as a result its basically invisible.

**Comment by SimonBrandner** [comment]
![Screenshot_20210301_153214](https://user-images.githubusercontent.com/25768714/109511429-4fae1a00-7aa3-11eb-9557-bcb831a01114.png)

Closing as this has been improved
