### ISSUE TITLE
Unknown devices in DM break verification.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#11487]
If you verify somebody after they've added new devices in your DM then that the verification request will trip on the "there are unknown devices in here" prompt and break the verification flow. _However_, after you've been ditched out of the verificaiton flow, you can then click on 'send anyway', triggering a disconnected verification process that the verifcatee can the verficator cannot pick up and complete.

**Comment by ara4n** [comment]
(we should probably skip the "unknown devices" check here, as well as handle overlapping verification requests more intelligently)

**Comment by dbkr** [comment]
Should be fixed now we have cross-signing
