### ISSUE TITLE
Canonical DMs behaviour touchups

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11495]
* [ ] Make DMs canonical (matrix-org/matrix-doc#2199)
* [ ] Don’t send room invite until inviting user sends first message -> https://github.com/vector-im/element-web/issues/14736
* [ ] In a 1:1 DM should simply reveal the user profile
* [ ] In a group DM, should reveal the member list

**Comment by MadLittleMods** [comment]
@turt2live What does "reveal the user profile" and "reveal the member list" mean? The room member list seems to work in DM's

**Comment by turt2live** [comment]
way back in 2019 the designs called for no information card or member list, but simply the member/user info card instead.

**Comment by MadLittleMods** [comment]
It seems like we're good to close this then as the reveal stuff doesn't seem relevant anymore and the others are tracked by their own issues 🎉
