### ISSUE TITLE
"Match system dark mode setting" doesn't actually match dark theme of the system

### ISSUE THREAD

**Issue by strixaluco** [vector-im/element-web#11509]
### Description

Even though "Match system dark mode setting" is turned on in Riot Web Desktop 1.5.4, it doesn't actually match dark theme of the system.

### Steps to reproduce

- have a dark theme for your desktop environment being set;
- launch Riot Web 1.5.4;
- witness light theme of Riot Web, while "Match system dark mode setting" is turned on

### Screenshot

![Riot - dark theme issue](https://user-images.githubusercontent.com/10875796/69604410-535d2080-1058-11ea-91c9-f4aa34bc18a4.png)

### Version information

- **Platform**: Desktop

- **OS**: Debian GNU/Linux 
- **Version**: 10.2 (GNOME 3.30.2), Sid (GNOME 3.34)

**Comment by OffifialMITX** [comment]
Just came here to report the same issue.

**Comment by turt2live** [comment]
Possibly related: https://github.com/flathub/im.riot.Riot/issues/77

**Comment by turt2live** [comment]
oops, wrong issue.

**Comment by jryans** [comment]
I guess GH still automated the same closure during release... 😓

**Comment by t3chguy** [comment]
@strixaluco can you confirm whether you still have this issue?
Did you install via Flatpak?
Can you show what https://codepen.io/kleinfreund/pen/NmpKZM shows for you?

**Comment by MrHeating** [comment]
At this point, using the yaru theme, I figured out that Element only checks once at startup, so in ordertotake effect I need to restart itcompletely. Installation is done via the default PPA and updated regularly.
-- 
Sent with K-9 Mail. Please excuse my brevity.

**Comment by strixaluco** [comment]
@t3chguy Element 1.7.8 doesn't have this issue anymore. Thanks for fixing! I'm using official Debian repo from Element team.

> Can you show what https://codepen.io/kleinfreund/pen/NmpKZM shows for you?

Sure, but I don't quite understand which part should I show. Sorry.

**Comment by t3chguy** [comment]
If it works then no bother!

Thanks for the update

**Comment by strixaluco** [comment]
You're very welcome and thanks again for fixing.
