### ISSUE TITLE
.well-known server discovery places cursor back in username after pessing tab

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/element-web#11506]
### Description

After filling in the full MXID and pressing tab, the homeserver gets discovered. This places the cursor back in the username field, rather than the expected password field. This means that if you're not paying attention you'll fill in both the username and password in the username field.

This is particularly a problem when using the autotype feature of a password manager such as keepass, which typically uses the sequence <username> <tab> <password> <enter>

### Steps to reproduce

- open a logged out riot with a different server preconfigured than you want to log in to.
- type the full mxid
- press tab
- cursor stays in the username section

I would have expected the cursor to move to the password field.

- **Platform**: web,

For the web app:

- **Browser**: firefox 70.0.1 
- **OS**:  kubuntu
- **URL**: riot.im/develop /

**Comment by aaronraimist** [comment]
Also if your password manager fills in both the username and password, the password field gets cleared out when the form "reloads". This seems like a recent regression. I can't remember this happening before.

**Comment by t3chguy** [comment]
This has been fixed
