### ISSUE TITLE
If Riot is open in two tabs, we can end up with a UISI if megolm keys are delayed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11504]
* Delph had two Riot tabs open with the same device
* Erik started a new megolm session to him
* For some reason, the event came through before the keys did \(not enough logging to see why\)
* One tab did a successful keyshare req to get the key
* The other tab raced with this to also to a keyshare req; it ended up requesting it from itself and getting a response from itself.
* However, this tab failed to then update the display to decrypt the message, perhaps because of getting confused with self-fulfilling its keyshare request and thinking it didn't need to notify the app about the new inbound session.
* Subsequently this got fixed \(perhaps when switching room & back again\).

https://github.com/matrix-org/riot-web-rageshakes/issues/1972 has full details.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11425
