### ISSUE TITLE
Clean up docs on native Node modules

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#11517]
https://github.com/vector-im/riot-web/pull/11125 adds integration and docs for manually enabling Seshat for desktop Riot.

At the moment it recommends:

* `yarn add matrix-seshat` in `electron_app` for initial install
* Usage of `electron-build-env` for rebuilds

There are a few issues here that leave some room for improvement:

* The main purpose of `electron-build-env` seems to be ensuring that [certain env vars](https://github.com/dherman/electron-build-env/blob/b7542d079b20e67a844cfd3eec603873d42c4030/index.js#L96-L104) are set, including `npm_config_runtime` which `neon` [seems to need for at least Windows](https://github.com/neon-bindings/neon/blob/72e83f0f4f11132710116b3491235e7c7310b193/crates/neon-build/src/lib.rs#L26)
  * This suggests we need some mechanism of settings these env vars for both initial install and rebuilds
* Installing `matrix-seshat` as a dependency will compile a build for plain Node as part of it's own scripts, but we probably need the adjusted Electron build instead, which may awkwardly mean building it twice with `electron-build-env` from the parent Electron app as well
  * Despite the wasted time of two builds, this seems to be what the Neon [example for Electron](https://github.com/neon-bindings/examples/blob/71e66cb66bafbf660690ffa2fc6d2fe5e3be2a41/electron-app/package.json) suggests

**Comment by jryans** [comment]
We now have an auto-build process after https://github.com/vector-im/riot-web/issues/12452, so I suppose all that's left here is to clean up docs on our support for native node modules.

**Comment by t3chguy** [comment]
Fixed
