### ISSUE TITLE
Sometimes there's a blank line when 'show hidden events' is enabled

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11510]
<img width="1178" alt="Screenshot 2019-11-26 at 10 06 43" src="https://user-images.githubusercontent.com/1294269/69620026-91e0e400-1034-11ea-9198-4c38fb43d3eb.png">

**Comment by t3chguy** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/2403652/69637780-3e30c380-1051-11ea-96e2-0862333671e1.png)

Code applies "_shouldShowEvent" just like it did pre-grouping

**Comment by turt2live** [comment]
This is because of the "show hidden events" setting, which is a developer tool and realistically not something we prioritize fixes for.

**Comment by t3chguy** [comment]
Going to fix this because of how many duplicates it has seen.
