### ISSUE TITLE
Encrypted rooms have a read marker at the bottom of the timeline on reload

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11537]
Unencrypted rooms are fine.
![](https://i.imgur.com/lYWtpVH.png)

**Comment by turt2live** [comment]
and when switching rooms (my read marker behaviour is set to sub-second times).

**Comment by turt2live** [comment]
... and when refocusing chrome.

@dbkr this seems like a regression from the css changes

**Comment by kittykat** [comment]
@turt2live I haven't seen this, are you still experiencing it?

**Comment by turt2live** [comment]
I haven't really seen this in a while either. It's possible I've just grown used to it.
