### ISSUE TITLE
Same message multiple time in history

### ISSUE THREAD

**Issue by kroeckx** [vector-im/element-web#11538]
When I type `!ping` in `#ping:maunium.net`, I sometimes see my own message repeated several times. I can't always reproduce this, but can most of the time.

At least 2 times, either directly after typing it, or after scrolling in the room, it crashed.

I'm now using 1.5.4 (.deb package, on Debian testing). I've only seen the crashes with 1.5.3 so far.

**Comment by t3chguy** [comment]
@kroeckx are you a :matrix.org user? There is a Synapse bug which if combined with high server load can cause message duplication on-send.

**Comment by kroeckx** [comment]
No, I'm running my own server, which is still running 1.3.0

**Comment by kroeckx** [comment]
Still seeing this with a 1.6.1 server

**Comment by kroeckx** [comment]
Still seeing this with synapse 1.12 and riot-web 1.5.15.

Sometimes I have the effect that the last message I've send stays at the bottom in riot-web, while other people have said multiple things. If I scroll up, my message usually appear multiple times in the history, and I then scroll down again, it multiplies again. The only fix for that is to restart riot-web, which is something I need very often.

**Comment by t3chguy** [comment]
Does https://github.com/matrix-org/synapse/issues/7206 apply to you?

**Comment by kroeckx** [comment]
> Does https://github.com/matrix-org/synapse/issues/7206 apply to you?

I don't know, but this is not a new issue. I've had this issue for
over a year.

I almost always have it after a resume. I guess it's busy doing
all kinds of request at that time. In general, riot is very
unresponsive at that time. I think I need to wait about 10 minutes
before saying something not to have it.

**Comment by kroeckx** [comment]
Maybe unresponive is the wrong way to say it. It seems to be busy
with updating the members of the room, filling the scroll back
buffer, and all those things take a long time.

**Comment by MadLittleMods** [comment]
@kroeckx Has this changed at all now that the message send status UX is different?

![](https://user-images.githubusercontent.com/558581/130536106-e118eb57-8348-4237-8869-6a292ae34eb2.png)

**Comment by kroeckx** [comment]
I haven't seen this issue in a while
