### ISSUE TITLE
Cursor has gone missing from room list filter when in insert mode

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11542]
The box expands, but my cursor is missing

**Comment by t3chguy** [comment]
The caret or the editable text cursor when you hover on it? pre or post expansion? screenshot?

**Comment by turt2live** [comment]
I was getting there... 

![image](https://user-images.githubusercontent.com/1190097/69764051-4d387400-112c-11ea-99b4-0e25335f4afc.png)

Turns out your keyboard has to be in insert mode.

**Comment by MadLittleMods** [comment]
@turt2live What platform are you reproducing this on? I'm trying to reproduce and pressing insert on keyboard does not toggle insert mode in Element Desktop or in Chrome (on Windows 10 or macOS). And I've confirmed insert mode works in text editing apps.

**Comment by turt2live** [comment]
Let's consider it fixed. I probably accidentally triggered this somehow
