### ISSUE TITLE
Integrations manager modal is blank when tracking protection is enabled

### ISSUE THREAD

**Issue by soufda** [vector-im/element-web#11569]
### Description

When I click the icon for "manage integrations" in the top right of the app, I get a blank modal.

**update**: it works when I disable tracking protection, I guess displaying a message stating that integrations don't work while tracking protection is enabled would be a good solution.

### Steps to reproduce

- Be in a room
- Click "manage integrations" top right icons.

The expected is to show the different integrations possible or a message stating there are no integrations available.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox Nightly 72, Brave stable
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by soufda** [comment]
here is javascript log showing some errors, when trying to perform this action.

`Starting load of AsyncWrapper for modal NotificationUtils.js:32:4
Starting load of AsyncWrapper for modal NotificationUtils.js:32:4
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 3
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Request to access cookie or storage on “<URL>” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. 5
Initialising scalar app.. index.js:8:8
Rendering... index.js:10:9
Scalar-web No screen specified MainPage.js:61:20
Unhandled rejection componentWillMount@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:67:20915
performInitialMount@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:78:8963
mountComponent@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:78:8131
mountComponent@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:7:576
performInitialMount@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:78:9245
mountComponent@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:78:8131
mountComponent@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:7:576
a@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:40:351
perform@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:24:8570
s@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:40:572
perform@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:24:8570
batchedUpdates@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:79:2768
i@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:6:17923
_renderNewRootComponent@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:40:1831
_renderSubtreeIntoContainer@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:40:2828
render@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:40:2955
@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:734
o@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:14632
e.exports/i.prototype._settlePromiseFromHandler@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:186
e.exports/i.prototype._settlePromise@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:989
e.exports/i.prototype._settlePromise0@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:1690
e.exports/i.prototype._settlePromises@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:3045
e.exports/i.prototype._fulfill@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:2061
e.exports/i.prototype._resolveCallback@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:74:30933
e.exports/i.prototype._settlePromiseFromHandler@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:341
e.exports/i.prototype._settlePromise@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:989
e.exports/i.prototype._settlePromise0@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:1690
e.exports/i.prototype._settlePromises@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:3045
e.exports/i.prototype._fulfill@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:2061
e.exports/i.prototype._resolveCallback@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:74:30933
e.exports/i.prototype._settlePromiseFromHandler@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:341
e.exports/i.prototype._settlePromise@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:989
e.exports/i.prototype._settlePromise0@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:1690
e.exports/i.prototype._settlePromises@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:3045
e.exports/i.prototype._fulfill@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:2061
i/<@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:39:16413
u@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:76:1030
r@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:76:459
EventHandlerNonNull*t@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:76:1376
e@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:31869
u@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:75:7470
value@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:39:5057
value@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:39:4893
value@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:39:4765
value@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:39:5108
value@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:10607
@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:673
t@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:107
@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:194
@https://scalar.vector.im/scalar-030e2d2b6028892bd251.bundle.js:1:199
debuggability.js:892
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
`

**Comment by aaronraimist** [comment]
@turt2live Shouldn't the title say enabled?

**Comment by turt2live** [comment]
I meant "tracking is disabled", though it could be easily flipped to "tracking protection is enabled" for clarity.

**Comment by sumpfralle** [comment]
The issue still exists.

The two possible workarounds are:
* A) disable *tracking protection* (or disable blocking *third party cookies*)
* B) add `scalar.vector.im` to the whitelist of allowed cookie domains

Both options are a bit cumbersome for a casual user (especially for privacy aware people).

Maybe there is a proper (site-wide) way around this?

**Comment by t3chguy** [comment]
develop.element.io now shows the correct failed to load state. The copy might yet undergo tweaking to cover some of the situations which may cause this. But there are literally infinite so anti tracking configurations may not make it in
