### ISSUE TITLE
Streamline "Roles & Permissions" screen

### ISSUE THREAD

**Issue by frandavid100** [vector-im/element-web#11597]
The "Roles & Permissions" screen can be made much easier to read, and also save space. Here's a mockup of how that could be done:

![image](https://user-images.githubusercontent.com/694794/70086823-7157f180-1613-11ea-8728-8d0f36e64bda.png)

The idea is: each role is in a box showing its power level, users with that role, and permissions for that role. Users and permissions can be added to a role by typing their names in the box.

A "New role" button lets you create custom roles, and there's a dropdown that lets you edit their power level and their name (if naming them is even possible), as well as delete them.

**Comment by HarHarLinks** [comment]
I think this is a good idea to view users' roles, but I'm not sure about permissions for the simple reason that it is nontrivial to find the role that has a certain permission.

**Comment by SimonBrandner** [comment]
I am going to close this in favour of https://github.com/vector-im/element-web/issues/22774 as the whole tab should probably be redesigned, so it makes sense to keep it in one issue
