### ISSUE TITLE
Edit history won't show on given message

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#11601]
Rageshake: https://github.com/matrix-org/riot-web-rageshakes/issues/2003

Message where the problem occurs: https://riot.im/develop/#/room/!AZozoWghOYSIAfaZjJ:matrix.org/$4PSjkPQuoBp4AqQVhzCJ6qXJoxivvNCKu8BSd-WhX5c

**Comment by t3chguy** [comment]
This got fixed
