### ISSUE TITLE
No emoji for gender-variant People Raising Hand emojis

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#11615]
![Screenshot 2019-12-06 at 13 24 57](https://user-images.githubusercontent.com/986903/70326283-14835380-182c-11ea-9ff6-994411fb120b.png)

Our emoji picker has entries for the gender-specific 'person raising hand' emojis but displays them as the two separate glyphs.

**Comment by yannicka** [comment]
Is this an Element issue? On my side, I can see the emojis as expected (Element Desktop 1.7.14 on Debian Unstable):
![image](https://user-images.githubusercontent.com/22885898/100472042-cbcb4700-30db-11eb-8321-c2ff156a8bba.png)

**Comment by turt2live** [comment]
This was probably fixed in an emoji library update
