### ISSUE TITLE
Changing power level in new member info doesn't work?

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11620]
I might have walked away from the room too quickly, but I had to op someone via devtools isntead

**Comment by t3chguy** [comment]
I cannot reproduce it working, I'm guessing you forgot to click save: https://github.com/vector-im/riot-web/issues/11619

**Comment by turt2live** [comment]
I was clicking save at this point, but I definitely was not waiting for the spinner to stop

**Comment by t3chguy** [comment]
Closing due to lack of repro
