### ISSUE TITLE
Prevent the user from creating multiple devices whereas a session is available

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#11643]
Some Riot-web users add to their Favourites or Bookmarks the [welcome](https://riot.im/app/#/welcome) or the [login](https://riot.im/app/#/login) url screen.

When these users want to go back to Riot, they land on the login screen and fill their credentials. This creates a new device in their account (most of them are not aware of that). They don't understand why the app fails to decrypt the room history in the encrypted rooms.

Would it be possible to check the local storage when the login screen is loaded by the browser in order to prevent them from logging in again?

**Comment by nadonomy** [comment]
Great idea! Few questions:

- If we detect a session in local storage, what account info does the browser know? If we know the matrix id, it'd be great to then display the avatar/username/id with a [Continue as Nad] experience
- Would the user need to enter their password/re-authenticate?

**Comment by uhoreg** [comment]
If the app detects that the user is already logged in, it should be able to redirect to the main screen with no interaction, and allow the user to just start using Riot.

**Comment by dbkr** [comment]
We're tracking this in https://github.com/vector-im/riot-web/issues/12476

**Comment by t3chguy** [comment]
templating from https://github.com/matrix-org/matrix-react-sdk/pull/4279 should also switch out the sso/cas URLs with a link back to the logged in app if the user is already logged in.
