### ISSUE TITLE
Copy / paste limited to 60 lines of messages

### ISSUE THREAD

**Issue by arthurlutz** [vector-im/element-web#11673]
### Description

I'm trying to copy some text from Riot-web to a text editor. 

When I select "large" number of messages, I only get the last 60 or so messages in my clipboard. 

### Steps to reproduce

- One a room
- select text over multiple messages using the mouse
- ctrl-C
- go to an editor (text based for example)
- ctrl-V

Describe how what happens differs from what you expected.

First messages are not present, only last messages. 

### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**:  Ubuntu, 
- **Version**: 1.5.6

**Comment by arthurlutz** [comment]
Tried out on encrypted and not encrypted rooms, and on web version, the same problem occurs.

**Comment by robintown** [comment]
This use case of extracting large numbers of messages is now covered by the 'export chat' feature.
