### ISSUE TITLE
multiple modals can be closed by one ESCAPE

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#11678]
it should only hit the top most one (image view over settings, escape closes both ☹️)

**Comment by MadLittleMods** [comment]
I can no longer reproduce this.

 1. Open settings (one modal) -> Labs -> Press **Feedback** for threads or the new search  (second modal)
 1. Pressing escape closes the feedback modal
 1. Pressing escape again closes the settings modal
  
 Same with settings and submit debug logs
