### ISSUE TITLE
Remove interstitial screen on migrating a key backup to SSSS

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#11696]
While cross signing is in development we have a screen in the setup flow telling people their key backup will be migrated. This is just whilst it's in testing so people are aware they're letting an unstable feature make changes to their account. Once we're confident this works we can do this automatically.

This is so we remember to remove the screen.

**Comment by dbkr** [comment]
One way or another this is no longer relevant: we launched it.

**Comment by richvdh** [comment]
There's still a TODO in the code, saying this screen needs removing: https://github.com/matrix-org/matrix-react-sdk/blob/v3.76.0/src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx#L579-L583

I'm not really sure if the screen actually still needs removing, or if it got removed and somebody didn't update the comment.

@dbkr can you shed any light here?

**Comment by richvdh** [comment]
Hrm, looks like https://github.com/matrix-org/matrix-react-sdk/pull/3897/files#diff-657d7d234bf7e8e748303399b1becd5fb5ea86b1616bf2b3822d19e55a8a2d04L312-R403 substantially changed this.

My impression is that the remaining dialog is not intended to be temporary, and hence the comment should be removed?
