### ISSUE TITLE
[Feature Request] Improved incoming call UX/notifications

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#11705]
The primary inspiration here is that when I receive a call on riot, there is no desktop notification/popup showing a call is coming in on riot. I hear the audible cue, however no graphical cue happens. This is a broken UX, wherein the user needs to scramble to find the application that is making the noise (assuming the user doesn't realise it is riot), or scrambling to find riot (if they realise riot is the source of the noise).

Specifically for calls, a pop-up in some way to accept/reject, or something like that, would do wonders to the UX for calls.

Can we get this added to the pipeline please? :)

(Also, if we could see the user name and avatar of who is calling in, and make it nice and polished, I think that would be stellar).

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_180023](https://user-images.githubusercontent.com/25768714/109426616-d8b74980-79ee-11eb-9483-5cc7724b0ab6.png)
This seems to have been added
