### ISSUE TITLE
Under some conditions, a 1:1 DM can be considered to have 3 people in it

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11757]
A clear cache and reload fixes it, but for some unknown reason my local riot was considering a 1:1 DM to have 3 people in it, despite only 2 members (none left).

**Comment by yannicka** [comment]
Where is it displayed that there are 3 people? in the sidebar?

Do we have more information on what can cause this?

**Comment by turt2live** [comment]
There's no information on what causes this. It's deep within the DMRoomMap, so any usages of that are affected.

**Comment by turt2live** [comment]
Closing as unactionable. If people see this, please open a new issue with fresh information.
