### ISSUE TITLE
Previews of Riot in instagram are massive

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11753]
Presumably because we don't offer much in terms of images for it to use.
![](https://i.imgur.com/bf5GGBW.png)

**Comment by t3chguy** [comment]
@foldleft would this be resolved by https://github.com/vector-im/riot-web/pull/13488 or https://github.com/vector-im/riot-web/pull/13461

I don't have IG to check.

**Comment by turt2live** [comment]
Doesn't seem to be fixed:
![image](https://user-images.githubusercontent.com/1190097/81773585-deff2800-94a5-11ea-91dd-6393cffa75d3.png)

**Comment by foldleft** [comment]
we've not yet followed up on https://github.com/vector-im/riot-web/issues/12014 as to whether this even looks okay in slack; problem is it's a bit hard to really validate =/

**Comment by aaronraimist** [comment]
Seems to be fixed

![image](https://user-images.githubusercontent.com/5855073/127754683-cbc44062-cfe7-4c9f-a61f-3e94f049af69.png)
