### ISSUE TITLE
Use SSSS master key for key backups created with SSSS enabled

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#11766]
Right now, if we create a key backup with SSSS (ie click the "Start using Key Backup with Secure Secret Storage" button) the key backup key will be random and stored in SSSS, so there will be no way for the user to restore the key backup from a device that doesn't support SSSS.

When we migrate key backup to cross-signing, we re-use the key backup key for the SSSS default key so they will be the same. We could likewise, for a transition period, use the SSSS default key as the key backup key when creating a key backup.

This would allow the user to enter their "security" (ie. SSSS) passphrase / recovery key to restore their key backup, which is nonideal and confusing in the sense that the UI is asking them for a different key to what it was called when they were given it, but at least it would work.

**Comment by jryans** [comment]
For the moment, I am thinking we can do without this by assuming all key backup devices are Riots that will update to 4S. Does that sounds reasonable @dbkr?

**Comment by dbkr** [comment]
No longer relevant since we launched it.
