### ISSUE TITLE
Sender displayName is replaced by user_id in FilePanel

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#11761]
![Capture du 2020-01-03 11-22-53](https://user-images.githubusercontent.com/57274151/71718429-762ee180-2e1b-11ea-9ec9-c6ae46a38a68.png)

### Description

The displayName of the sender is replaced by the user_id when scrollback in the filePanel.

Only the events fetched when paginate are concerned (=> onMessageListFillRequest), not the ones displayed from the beginning which do not require moving the _timelineWindow.

Strangely the displayName is always correctly displayed in the RoomView even though they are based on the same generic component chain (TimelinePanel > MessagePanel...).

### Steps to reproduce

- create a new room at https://riot.im/app (no need to invite anyone)
- send enough files so that the scrollHeight of the filePanel is at least twice as big as the clientHeight (faster with images!).
- log out and clear the browser cache
- log back in and scrollback in the filePanel to observe the issue

The user_id should never appear, only the displayName

Logs being sent: no

### Version information

- riot-web : 1.5.6
- **Platform**: web (in-browser)

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: https://riot.im/app

For the desktop app:

idem with the last flatpak

**Comment by c-cal** [comment]
Is that related to https://github.com/vector-im/riot-web/issues/7417

**Comment by turt2live** [comment]
This is more of an artifact of the UX not being updated in that area for 3-4 years now. Definitely needs a redesign.
