### ISSUE TITLE
Resuming laptop from sleep causes every notification to replay

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11782]
After it syncs and realizes I've read all the notifications, they all still show up.

**Comment by Half-Shot** [comment]
I've encountered this for as long as I can remember, kinda got used to it. Slightly annoying though.

**Comment by aaronraimist** [comment]
Related: #2608

**Comment by hanthor** [comment]
Is this still happening? Is there any way to mitigate? Especially if the messages are already read on Mobile or another session. It can be disturbing to see all these messages come back apparently unread

**Comment by turt2live** [comment]
I have not seen this in a while - closing as fixed.
