### ISSUE TITLE
Homeserver URL Change page: "Next" button is misleading 

### ISSUE THREAD

**Issue by gdvine** [vector-im/element-web#11818]
### Description

The button actually takes you back, not next. It takes you to the sign-in page.

### Steps to reproduce

- Go to sign-in page
- Click Change

The button to go to sign-in should be big and green, but "Next" is very misleading. It should probably say "Sign In". 

### Version information

MacOS Desktop client v1.5.6

**Comment by aaronraimist** [comment]
Screenshot to help others visualize:
<img width="720" alt="Screen Shot 2020-01-11 at 12 49 40 AM" src="https://user-images.githubusercontent.com/5855073/72200217-40d25700-340c-11ea-9bff-09547a03eaf2.png">

I don't think Sign In makes sense. You aren't signing it at that point. Maybe "Set Homeserver" or something.

Even better I think would be to remove that screen completely now that the identity server isn't set at login time. Instead the homeserver URL text box could just appear in the place of the homeserver URL on the main login page when you click Change

Kinda like:
<img width="532" alt="Screen Shot 2020-01-11 at 12 57 59 AM" src="https://user-images.githubusercontent.com/5855073/72200296-6b70df80-340d-11ea-8da6-1cc3b7b2564a.png">
except on the same line

**Comment by gdvine** [comment]
You're right, and I like your idea about having the homeserver URL on the same page.

**Comment by awitherow** [comment]
I now have to create a new account because of this 👎

**Comment by t3chguy** [comment]
This screen has totally changed so not sure how you are hitting this issue @awitherow unless you're on an old version.

![image](https://user-images.githubusercontent.com/2403652/109868823-06ef9000-7c60-11eb-9eaf-fb6db25307ee.png)

@gdvine / @aaronraimist do you consider the issue fixed given that the original UX that was being complained about is now a popup with a Continue button which makes a lot more sense especially as you can see the contextual relationship between your actions

**Comment by gdvine** [comment]
Yes! That looks much better now.
