### ISSUE TITLE
Quick way to get back to showing all joined rooms and conversations for user account

### ISSUE THREAD

**Issue by brylie** [vector-im/element-web#11828]
**Is your suggestion related to a problem? Please describe.**
When I have clicked a community to "filter" rooms, it is difficult to get back to showing all the rooms that I have joined. E.g., I have to modify the URL to take off the community segment, so that only `/app` remains after the domain name.

**Describe the solution you'd like**
Some way to get back to my personal user rooms/conversation list, e.g., by a single click on my avatar or a "Home" button at the top of the Communities sidebar.

**Describe alternatives you've considered**
I have tried hacking the URL, and it works.

**Additional context**
Often, people would navigate between groups on Riot.im and then want to view the full rooms list for their account. This use-case could be more streamlined.

**Comment by brylie** [comment]
Ah, it seems that clicking the sidebar does reset the "Communities" filter. This could be made obvious with a metaphoric signifier, like a button with a Home icon.

**Comment by brylie** [comment]
Ah, it seems that clicking the sidebar does reset the "Communities" filter. This action could be made evident with a metaphoric signifier, like a button with a Home icon.

**Comment by aaronraimist** [comment]
Are you using Riot 1.5.7? You should be able to just click on the community again to toggle it off.

**Comment by brylie** [comment]
Hm, I am using whatever version that is deployed at riot.im/app. I will try to find the version number via riot.im.

**Comment by brylie** [comment]
Riot.im/app is running riot-web version: 1.5.7. However, clicking on the community name does not seem to remove the filter. Perhaps this "remove filter" feature is in a later release?

**Comment by t3chguy** [comment]
![toggle](https://user-images.githubusercontent.com/2403652/72322759-0df3c180-369f-11ea-972d-0b51a8aa9d82.gif)
Works fine here

**Comment by brylie** [comment]
It doesn't work in Firefox 72.0.1 (Ubuntu):

![Peek 2020-01-14 11-12](https://user-images.githubusercontent.com/17307/72330230-cbda7800-36be-11ea-8e79-1e1672564c06.gif)

**Comment by t3chguy** [comment]
Riot 1.5.7 has a different highlight style, see bar to left of my communities, you're still running 1.5.6 somehow

**Comment by brylie** [comment]
Hm, strange. I just opened https://riot.im/app in Chrome 79.0.3945.117 (Official Build) (64-bit), verified that it is supposed to be running Riot 1.5.7, and the issue persists:

![Peek 2020-01-14 11-36](https://user-images.githubusercontent.com/17307/72332160-350fba80-36c2-11ea-994f-4c7a64d98161.gif)

**Comment by t3chguy** [comment]
Could you send a bug report from settings? Thanks

**Comment by robintown** [comment]
Spaces are now in beta! (and they present you an obvious 'all rooms' button)

**Comment by ShadowJonathan** [comment]
The "all rooms" way of doing things is sorta contested right now, but that's #17203
