### ISSUE TITLE
RoomUpgradeWarningBar: Unstable room version v5, upgrade to v4

### ISSUE THREAD

**Issue by jomat** [vector-im/element-web#11820]
### Description
Users sometimes see the RoomUpgradeWarningBar in v5 rooms, clicking on upgrade tries to downgrade to v4. This message also disappears again when switching rooms.
![unstableroom](https://user-images.githubusercontent.com/381286/72205488-706c7800-347b-11ea-8ebc-db62dc8de957.png)

### Steps to reproduce

- Be admin in a v5 room

### Version information

riot-web 1.5.7-rc.2, but also happened in older versions.

**Comment by turt2live** [comment]
@jomat please rageshake for this issue.

**Comment by jomat** [comment]
How? I only know the rageshake on riot-android.

**Comment by turt2live** [comment]
Settings -> help -> submit debug logs

**Comment by yangm97** [comment]
Just sent some logs for this.

**Comment by aaronraimist** [comment]
Related: #11636

**Comment by turt2live** [comment]
One instance of this is the homeserver being offline/slow during startup, so Riot thinks that there's no capabilities and therefore nothing is safe. We could probably fix this by altering the defaults a bit, or by being less aggressive when the request fails.

**Comment by turt2live** [comment]
keeping this open to track the cache problem (and when this happens again for v6)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/16068
