### ISSUE TITLE
See if we can ditch browserify in the js-sdk

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11876]
It's just annoying to maintain. Can we use webpack instead?

**Comment by richvdh** [comment]
> The current browserify works well enough that it probably does not warrant the time

As https://github.com/matrix-org/matrix-js-sdk/issues/3182 suggests, we probably need to do some work on the browserify artifacts in the near future, so I'm not sure this will continue to be the case.

**Comment by richvdh** [comment]
Have opened https://github.com/matrix-org/matrix-js-sdk/issues/3189 to follow up on this
