### ISSUE TITLE
Explore doesn't really give hints on how to join rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#11899]
It assists discovery, though many show up to the app wondering how to join a room.

**Comment by GReagle** [comment]
I think that adding the word "rooms" would be helpful so it would be "Explore rooms".  Or if there is space, even more clear would be "Explore and join rooms".

**Comment by gsouquet** [comment]
Closing as this will be addressed as part of https://github.com/vector-im/element-web/issues/21947
