### ISSUE TITLE
Allow hiding avatars in chat

### ISSUE THREAD

**Issue by reuben** [vector-im/element-web#11900]
**Is your suggestion related to a problem? Please describe.**
I want to see timestamps on all messages, so I enabled that option in my preferences. This clutters up the left side of the chat, making some timestamps almost overlap with avatars. I think it's also making the avatars not line up with the center of the messages, which makes it hard to see at a glance what message corresponds to each avatar.

**Describe the solution you'd like**
I'd rather have the timestamps clearly visible than have avatars at all, so a preference to not show avatars in the chat would solve this.

**Describe alternatives you've considered**
None.

**Additional context**
Screenshot. Note how the timestamps on the last two messages almost touch the avatars, and how the avatars are up from the center line, almost entering the area of the message above it. I don't know if that's related to the timestamps.

<img width="760" alt="Screen Shot 2020-01-17 at 10 02 59" src="https://user-images.githubusercontent.com/477142/72598729-49dd8f80-3908-11ea-8c11-be8561c250e3.png">

**Comment by dralley** [comment]
@reuben I just discovered an existing issue for this feature with more traction, it'd probably be better if you closed this issue and we both added to the discussion on the original one.

https://github.com/vector-im/element-web/issues/11900

**Comment by dralley** [comment]
Also https://github.com/vector-im/element-web/issues/11051 is more specific to your exact problem

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/4403

Thanks for pointing it out @dralley 😀
