### ISSUE TITLE
Events appear multiple times in timeline

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#11933]
I saw 3 copies of Dave's "I would like to understand ..." message while scrolling up and down.

Screenshot at https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$15795126101165575qxcVE:matrix.org?via=matrix.org&via=vector.modular.im&via=lant.uk

**Comment by bwindels** [comment]
It's an entire range of events that seems to appear multiple times, including date separator. Another screenshot at https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$15795130791166859HDqhz:matrix.org?via=matrix.org&via=vector.modular.im&via=lant.uk

**Comment by bwindels** [comment]
Scrolling up I just get the same range repeated. The console is full of the following error:
```
Event $1579260867626816aYHiK:matrix.org already in timeline !RbKRuLTvHIhArQcvjr:matrix.org:2020-01-20T09:39:19.900Z
```

**Comment by bwindels** [comment]
A refresh fixes the issue.

**Comment by bwindels** [comment]
also saw double read markers fwiw

**Comment by bwindels** [comment]
Events seem to rendered multiple times, this seems to be triggered by scrolling. Could this be the (un)filling stuff messing something up and putting events multiple times in the timeline? This is something we could add logging for I suppose?

**Comment by t3chguy** [comment]
Was this after peeking a room?

**Comment by bwindels** [comment]
> Was this after peeking a room?

No, when I hit this it was in rooms I had been a member of for a long time already.

**Comment by t3chguy** [comment]
Closing as likely temporal, given no other reports of it
