### ISSUE TITLE
Notification settings are hard to find

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#11937]
Room settings would be the logical place to look for per-room notification settings (e.g. that's how it works in Slack). There is indeed a notification panel in room settings, but it's rather useless:
![riot notifications menu](https://user-images.githubusercontent.com/145412/72721433-e6827600-3b30-11ea-9c27-28894a214188.png)

The actual notifications menu is a dropdown the affordance for which only shows up when hovering on the room name in the left sidebar:
![riot-notifications](https://user-images.githubusercontent.com/145412/72721484-04e87180-3b31-11ea-9d8b-db6b70f05372.png)
which is easy to miss, making users assume that Riot has no notification management to speak of.

The notification "volume" settings should probably be repeated in the room settings menu, or at least there should be some text explaining that this is not the right place to change them.

(Tested in riot.im/web and /develop, on Chrome 79 / Ubuntu 18.04.)

**Comment by jplatte** [comment]
This is worse after the redesign, where the menu isn't available at all when the sidebar is collapsed.

**Comment by MadLittleMods** [comment]
Notifications are now available under **Room settings** -> **Notifications** 🎉. Looks like this was added a while back in https://github.com/matrix-org/matrix-react-sdk/pull/7072

![](https://user-images.githubusercontent.com/558581/171955279-1b9eeec1-944d-402d-b721-4a224c307365.png)

Also available under the room heading dropdown:
![](https://user-images.githubusercontent.com/558581/171955286-892520be-39b4-4e6b-b998-a8bdc886cac9.png)

And still from the room list bell:
<img width="506" alt="" src="https://user-images.githubusercontent.com/558581/171955585-a74543f7-adcb-4de6-87b5-bd0a14d277e9.png">

Happy to see this fixed! This was one of my [major initial user experience notes](https://docs.google.com/document/d/1PkUlVyZFM1stDdXbrJXuHPnQ-1S1Dh5KiDaGlYhiTAU/edit#bookmark=id.tjt5givt945).
