### ISSUE TITLE
"Close" button for user sidebar actually brings up user list

### ISSUE THREAD

**Issue by jdm** [vector-im/element-web#11965]
### Description

When I click on a user's avatar in a room, it brings up the user sidebar. When I press the button labeled close in order to close this sidebar, it gets replaced with the room member list. I then have to press the "Members" button to hide this sidebar.

### Steps to reproduce

- click on an avatar in a room
- click on the sidebar's close button

My expectation is that pressing the button labeled "Close" will cause the room to return to its state from before I clicked on the avatar.

Logs being sent: no

Base room state, about to click on stas' avatar:
<img width="1440" alt="Screen Shot 2020-01-21 at 11 32 30 AM" src="https://user-images.githubusercontent.com/27658/72801617-c7273e00-3c41-11ea-94bc-15547a161962.png">

Before pressing the "<" button labelled "Close":
<img width="1440" alt="Screen Shot 2020-01-21 at 11 32 39 AM" src="https://user-images.githubusercontent.com/27658/72801658-e3c37600-3c41-11ea-89fa-8cd0d5152559.png">

After pressing the "<" button labelled "Close":
<img width="1440" alt="Screen Shot 2020-01-21 at 11 32 44 AM" src="https://user-images.githubusercontent.com/27658/72801687-f63daf80-3c41-11ea-95fc-1f223e1ce573.png">

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 74 (nightly)
- **OS**: macOS 10.14
- **URL**: chat.mozilla.org

**Comment by morteify** [comment]
At this point I find it very confusing what that button is intended to do. It tells user neither to collapse sidepanel (I'd expect the arrow to be turned the other way- to the right: ">"), nor to display list of all users in a room (its label says "Close"). It kind of contradicts itself and there should be made some decision what's the real intention and deliver it to the end user more clearly. Anyway, It looks like it's more of a displaying all room's members than closing sidebar entirely so I'd opt for changing the label.

**Comment by t3chguy** [comment]
It's intended to close the User Info panel, and reveal the Member List panel below it, but in your case you're right the Member List should not be waiting there below it.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5167
