### ISSUE TITLE
Rendering large MELS is very slow

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#11963]
If you have tens/hundreds of membership changes in a row, MELS takes a surprisingly long time to render when viewing a timeline for the first time.  It's as if every new event added to scrollback calls the MELS (or the whole timeline?) to re-render from scratch.  Instead, we should only update the MELS atomically for every batch of scrollback loaded via /messages, rather than on a message by message basis.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/11604 https://github.com/vector-im/riot-web/issues/9200 https://github.com/vector-im/riot-web/issues/9192
