### ISSUE TITLE
OLM.UNKNOWN_MESSAGE_INDEX

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#11962]
### Description

Message could not be decrypted:

`** Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX **`

### Steps to reproduce

The receiver, test4, has the `cross_signing` labs flag enabled.

test4 had exactly one device when receiving this message. test4 logged out, and back in, and re-signed the new device from a key backup, as well as recovering encrypted history.

surrounding messages are recovered just fine.

### Additional data

```
{
  "type": "m.room.encrypted",
  "sender": "@test3:localhost",
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "sender_key": "PkeuRwEkyZl/9gxEVqHr4CZdJ6VhmlrNGskzvPxiAy0",
    "ciphertext": "AwgAEqABLutzvJm2CcrZwubBD7S94fE0PCkGwMEBgCD9MOtvqayH2kVE9CnLEqBvhIh/E7Wbo2cmUfHDDgg4DV++k6EiG0O9ThX0sH7pOcoxSlCdNRrnFvQfh567i89kiPfTimucw4In7UR0yQLABuu/7Z1KgpZkrTe+7Nbto9v2YhxHgzwroq25MCbBwOXVHTQkvEKnLqVp5vGUg6FS+sCZWHnh/0xsxItyNAV8377ehvt1PfGert6lNgMhKBaP5VEwNLvDnLdvb7QGHIqazXX+yrihF/SkB7F25e84B1b/Nkwm7bVsIOj8j28eCA",
    "session_id": "GIb9WWgCCvt37bDNHLo56SU+zuWpQMw4hllh554ffgc",
    "device_id": "CTJMIMCGSM"
  },
  "origin_server_ts": 1579533283878,
  "unsigned": {
    "age": 68248725
  },
  "event_id": "$6T3IxfTzDX7PwL7PSY0paqKDeA-CVLR8_GubrRB0S7M",
  "room_id": "!FvYCOictdDeEgPobtG:localhost"
}
```

Log: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **version**: matrix-react-sdk a984f9acf3e168f3d9c35e0dab1a66afc84707b6

**Comment by chagai95** [comment]
I just had the same error but in a different case? Would it not make sense to hide this from the end user?


[rageshake.zip](https://github.com/vector-im/element-web/files/6487827/rageshake.zip)

**Comment by richvdh** [comment]
There is no value in having millions of uninvestigated "can't decrypt" issues open. Closing in favour of https://github.com/vector-im/element-meta/issues/245
