### ISSUE TITLE
Number/Amount of users in explore list

### ISSUE THREAD

**Issue by Chatcloud** [vector-im/element-web#11982]
### Steps to reproduce

Click "Explore" in Riot Web. It shows an amount of users in the room. It also counts users who are marked as inactive in my DB - i mean deleted users.

**Comment by turt2live** [comment]
if they're still members of the room then they'll be counted. How have they been deleted?

**Comment by wuhlheide** [comment]
The have been deleted via
`curl -X POST 'https://matrix.xxxxx.net/_matrix/client/r0/admin/deactivate` and marked as deactivated in table "users"

**Comment by t3chguy** [comment]
Did they leave the room?

**Comment by Andre2344** [comment]
After disabeling they do not get listet as user in riot anymore.

**Comment by turt2live** [comment]
I suspect this might be a Synapse issue for failing to count the users as left.

**Comment by schopenhauer** [comment]
I encounter the same issue, where some of my rooms show 8-9 participants in the "Explore rooms" panel, when there are in fact only 3 people in each of those rooms at this point in time.

**Comment by jryans** [comment]
This likely connected to Synapse issue https://github.com/matrix-org/synapse/issues/1294

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/issues/1294 claims it is fixed
