### ISSUE TITLE
/join command acts incorrectly when provided a room id

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12022]
### Description

The `/join <alias>` command allows you to enter a room ID instead, which causes the client to attempt a join that never completes.

For instance, typing `/join !asdasd:asdasd.com` results in the following request being sent to the homeserver:

```
POST https://my.homeserver.org/_matrix/client/r0/join/!asdasd%3Aasdasd.com?server_name=%21asdasd%3Aasdasd.com
```

which will fail for obvious reasons.

Ideally Riot should make sure the input provided to `/join` matches `#something:domain.xxx` before carrying out the command.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
`/join` indeed does more than than aliases. The command itself has the alias `/goto`, which means both will take permalinks and can accept server names in the format `/join !room:example.org matrix.org otherserver.com` (iirc). 

Does it actually send the room ID as a server_name or is that a typo?

**Comment by anoadragon453** [comment]
> Does it actually send the room ID as a server_name or is that a typo?

It does indeed do this :|

**Comment by turt2live** [comment]
The help text is intentionally limited to avoid making the command a confusing nightmare of arguments.

**Comment by anoadragon453** [comment]
Fair enough, but I was lead by the help text to tell a user that they need to join a room via the URL bar in Riot instead of this command.

**Comment by turt2live** [comment]
but it doesn't support `/join <room id>` unless you give it more stuff...

**Comment by t3chguy** [comment]
The issue with the via being wrong was fixed.
The only issue here is the routability of roomIds.
If your server knows the roomId then you can use `/join !roomId`

**Comment by anoadragon453** [comment]
I don't think there's much left to do here, thanks all :)
