### ISSUE TITLE
Video thumbnails

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1207]
If I upload a .mov it'd be nice if it was thumbnailed.

**Comment by MadLittleMods** [comment]
Current state: works for `mp4` but not `mov`

![](https://user-images.githubusercontent.com/558581/132074984-80e4be87-90a1-4ef5-a7dd-296e01ca7612.png)

**Comment by t3chguy** [comment]
This is simply lack of browser support for `mov` - https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

Mov support in the web:

> Only older versions of Safari, plus other browsers that supported Apple's QuickTime plugin

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2023
