### ISSUE TITLE
Make own preview window smaller or option to  disable

### ISSUE THREAD

**Issue by stefonarch** [vector-im/element-web#12085]
At the moment making a video call the own webcam view is quite big related to the counterpart.
**Describe the solution you'd like**
 Adding an option to customize it's size or make it smaller would be a solution, maybe somebody would like also  an option for disabling it (or fading out after some sec).

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18262
