### ISSUE TITLE
Category should be highlighted if it contains groups with unread messages

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#12087]
Groups with unread messages may be hidden below the fold.  If the header ('People', 'Rooms', 'Low Priority', ...) were highlighted, such messages would still have a marker.

**Comment by turt2live** [comment]
The badge is already added to the header. Is there something more you're after?

**Comment by t3chguy** [comment]
thats for notifications, which may not include unreads (bolds) depending on settings

**Comment by turt2live** [comment]
it also brings up the unread notifications. Bold rooms are indeed a different story, but the theory at that point is why would you want to see the tag decorated if you've selected such a low-noise option?

**Comment by aaronraimist** [comment]
If https://github.com/vector-im/riot-web/issues/3374 was an option then I wouldn't have to set every room to mentions only

**Comment by Biep** [comment]
It is nice to be able to discern various levels of importance.  On the lowest level, I want no badges, but I'd still want to be reminded there is something.

**Comment by turt2live** [comment]
The sublist header now has a badge.
