### ISSUE TITLE
Many instances of "InRoomChannel: validateEvent: no valid txnId undefined" in logs during Riot startup

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12098]
### Description

This may be harmless, but as you know it takes quite a while for my Riot to start up, which looks to be due to it processing encrypted rooms.

However, today I just noticed that I'm getting many instances of the line:

```
InRoomChannel: validateEvent: no valid txnId undefined
```

per-room in my logs as it processes encrypted rooms. Some rooms even spewing the message out many hundreds of times.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1
- **OS**: Linux
- **URL**: riot.im/develop

Cross-signing is enabled.

**Comment by jryans** [comment]
@anoadragon453, can you check again after reloading develop? A fix was recently merged for this in https://github.com/matrix-org/matrix-js-sdk/pull/1172.

**Comment by anoadragon453** [comment]
I don't see this error in my current Element logs. So as far as I know it's been fixed!
