### ISSUE TITLE
riot-web's fetch-develop-deps uses the wrong branch name for tests

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12109]
```
+ git clone git://github.com/matrix-org/matrix-react-sdk.git matrix-react-sdk --branch HEAD --depth 1

Cloning into 'matrix-react-sdk'...

warning: Could not find remote branch HEAD to clone.

fatal: Remote branch HEAD not found in upstream origin
```

**Comment by jryans** [comment]
Hmm, that's quite puzzling at first glance... It's like it didn't go down the BK branch... the environment flag is definitely set, so...

**Comment by jryans** [comment]
Oh wait, which log are you looking at @turt2live? Is it https://buildkite.com/matrix-dot-org/riot-web/builds/1858#3d3c13be-9e49-4ff9-a3f6-a47a970d5287? (That one seems to find develop eventually...)

**Comment by turt2live** [comment]
it was 1858, but the problem still stands: it didn't check out the `travis/skinning` branch, and instead chose `HEAD` to check out. Using `develop` would have been the problem.

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/element-web/pull/22054
