### ISSUE TITLE
Consider only using a canonical alias for room name, otherwise member names

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12132]
### Description

While fixing [a UX issue on the mx-puppet-discord bridge](https://github.com/matrix-discord/mx-puppet-discord/issues/49), we found that Riot couldn't display bridged Discord Group DMs in a nice way.

For context, on Discord a group DM is a private room between a set of users, and looks like:

![image](https://user-images.githubusercontent.com/1342360/73382778-11529400-42c0-11ea-8a81-048499203253.png)

This is currently bridged in Riot as the following:

![image](https://user-images.githubusercontent.com/1342360/73382813-229ba080-42c0-11ea-9486-6e050fac74f8.png)

Which is due to a `#_discordpuppet2_1_6706...` non-canonical alias being set in the room. This alias is necessary to allow linking the user to the room.

The spec currently dictates how a room name should be calculated [here](https://matrix.org/docs/spec/client_server/r0.6.0#calculating-the-display-name-for-a-room). Using non-canonical aliases is marked as "optional", stating it is "a temporary measure while clients do not promote canonical aliases as prominently. This step may be removed in a future version of the specification."

Which seems like a good reason to get on with removing the behaviour.

We of course need to take into consideration that room names may change in people's room list due to this. Although for new users the canonical alias becoming the name of the room in a room without a set name makes sense. There's a question then whether Riot wants to only make this change for new rooms or whether that's worth the tech debt.

Assuming this is removed from the spec at some point this would need to do this anyways.

### Version information

- **Platform**: web
- **Browser**: Firefox v74.0a1
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Its recommended by the spec though :(
https://matrix.org/docs/spec/client_server/r0.6.0#calculating-the-display-name-for-a-room

**Comment by Sorunome** [comment]
No, it is not recommended. The spec says that it is optional. And that it will likely be removed in the future.

Am 29. Januar 2020 21:34:21 MEZ schrieb Michael Telatynski <notifications@github.com>:

**Comment by t3chguy** [comment]
This was done
