### ISSUE TITLE
Include gstatic.cn in CSP for reCAPTCHA when visiting from mainland China

### ISSUE THREAD

**Issue by PeterCxy** [vector-im/element-web#12137]
### Description

Google's reCAPTCHA service will load a script from `https://www.gstatic.cn` instead of `https://www.gstatic.com` when visited from mainland China. Current CSP blocks such requests so reCAPTCHA do not work on riot.im (and potentially other Riot instances copying your CSP policy) for users in mainland China.

### Steps to reproduce

- Go to China
- Try to register from Riot on a server that requires reCAPTCHA

Logs being sent: yes/no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Unrelated
- **OS**: Unrelated
- **URL**: Unrelated

**Comment by turt2live** [comment]
Doing this safely is a bit difficult. We'd probably actually want to rip out the reCAPTCHA support for some other captcha solution instead, though that's better tracked here: #3606

**Comment by PeterCxy** [comment]
> Doing this safely is a bit difficult.

Sorry but I don't quite get this? There is no need to modify anything in Riot itself -- `recaptcha.net` works totally fine in China, it's just that it loads `gstatic.cn` instead when the client IP is from China mainland, which is not included in the Content Security Policy of Riot.Im (gstatic.cn is controlled by Google and host the same content as gstatic.com, just that the server location is different). It just works(tm) on other self-hosted instances without restrictive CSP (which is not a good thing)

> We'd probably actually want to rip out the reCAPTCHA support for some other captcha solution instead

A self-hostable CAPTCHA looks better to me too. But the issue here is not about switching out the CAPTCHA itself, though. The current solution works 100% fine with a simple addition to CSP.

**Comment by turt2live** [comment]
adding to the CSP can potentially open us up to more attack vectors, and something like gstatic is very wide and far-reaching, so we don't really want to open ourselves up to that at the moment.

**Comment by t3chguy** [comment]
`script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.recaptcha.net https://www.gstatic.com;`

but if its just a mirror of gstatic.com then how can it be opening us up any more?

**Comment by turt2live** [comment]
not sure personally, just relaying the conversation from ops. At the moment I'm a bit focused on other things.

**Comment by 2403772980ygy** [comment]
Proved that this can't work in HonkKnog too.

**Comment by ash0080** [comment]
Not work in China,  even using a globle proxy,  I think the dependency module has some problem, cuz I can use reCAPTCHA in many different services and websites

**Comment by PeterCxy** [comment]
@ash0080 no, it's because the Content Security Policy, which is not used by every service and website but on Riot.im. Your "global proxy" may not actually make reCAPTCHA load from the global domain `gstatic.com` if you don't proxy every DNS request too. You can confirm this by using the developer tools by pressing F12 and look at what domain (`gstatic.com` or `gstatic.cn`) the reCAPTCHA script tries to load from.

**Comment by ash0080** [comment]
![截屏2020-03-1614 46 35](https://user-images.githubusercontent.com/2803210/76729832-029f3e00-6795-11ea-8e0c-690e7df24ceb.png)

![截屏2020-03-1614 53 36](https://user-images.githubusercontent.com/2803210/76730321-f5cf1a00-6795-11ea-9189-980d1e75d9dc.png)

I have proxy all my income and outcome traffics, 
and flush all DNS cache, 
and using DNSpod and V2rayDNS for all DNS resolving, 
but it still directs me to gstatis.cn

means that, there're no way to register from China, at lease now
never faced that issue

**Comment by PeterCxy** [comment]
@ash0080 that's no longer an issue of Riot or Matrix anymore and thus I don't think it is appropriate for discussion under this issue. You should better check the documentation of your proxy software, especially DNS ones, for that matter. I am aware that many of such software simply does not proxy any DNS request to domains that are known reachable from China.

Also, there are Matrix instances that do not require reCAPTCHA upon registration, though I do not think it is appropriate for me to name any one of them here. There are also Riot instances that do not have CSP / have different CSP than the official instance. For your last resort, it is possible to temporarily disable Content Security Policy checks during registration in most browsers (consult search engines yourself), though I __highly recommend against__ doing so and even if you decide to do so, please remember to turn it back on after you pass the reCAPTCHA test.

**Comment by ash0080** [comment]
OK, but still need to say 'Disable CSP not work!' 
'Change system language not work'

**Comment by PeterCxy** [comment]
@ash0080  I can confirm disabling CSP makes it work in my case. No clue about your issue there.

**Comment by ash0080** [comment]
> @ash0080 I can confirm disabling CSP makes it work in my case. No clue about your issue there.

Thanks, finally it works 

with firefox -> about:config -> search csp -> set false
as a ref

**Comment by PeterCxy** [comment]
@ash0080 and for anybody else that may come across, PLEASE find another instance that does not use reCAPTCHA or another Riot instance before deciding to use the last resort of disabling CSP. If you really want to go down this route, __always turn in back ON IMMEDIATELY after you finish registration__.

**Comment by jryans** [comment]
We'd prefer to resolve this by changing to a better captcha, which is tracked in https://github.com/vector-im/riot-web/issues/3606.

As this is quite a distinct problem from captchas generally, it's helpful to keep this issue open until a solution is found.

**Comment by lilydjwg** [comment]
Two years have passed and I decide to use matrix, and I find me blocked by this. I'm searching how to disable csp now....

**Comment by lilydjwg** [comment]
OK, I finally worked around it by doing the following:

* close Firefox
* delete all lines containing `element.io` from `SiteSecurityServiceState.txt`
* start Firefox
* open `about:config` and set `network.stricttransportsecurity.preloadlist` to `false`
* run `mitmproxy --modify-body "#script-src 'self' 'unsafe-eval' https://www.recaptcha.net https://www.gstatic.com;#script-src 'self' 'unsafe-eval' https://www.recaptcha.net https://www.gstatic.com https://www.gstatic.cn;"`
* go ahead registering

I know this is super unsecure, but I have no other ways. Don't remember to revert all the changes afterwards. I hate when security becomes obstacles :-(

**Comment by linsui** [comment]
It's not so difficult for me. As long as the recaptcha.net script is fetched via a proxy it will use gstatic.com. You can open the script directly and check it.

**Comment by robintown** [comment]
As per the decision of the security team in https://github.com/vector-im/element-web/pull/22149#pullrequestreview-998004953, whitelisting gstatic.cn is not something we're comfortable doing. If you are affected by this, the current recommendation is to use a modified version of Element Web/Desktop. Contributions that make it easier to work around this issue in vanilla Element Desktop are still welcome.

**Comment by jackyzy823** [comment]
Here to provide a hacky solution:

Using Firefox as an example:

Open Developer Tools (F12) on the page, then got Debugger , find the script ( https://www.recaptcha.net/recaptcha/api.js?onload=mxOnRecaptchaLoaded&render=explicit ) (note this script will only be loaded after you clicking register ) and pretty print it.

Add breakpoint after `po.src = 'https://www.gstatic.cn/recaptcha/releases/<random_string>/recaptcha__en.js'; `

Then reload the page, and do register again,  When break point is hit (Note: may hit twice so you need do it twice), enter following line (just change .cn to .com)  in console `po.src =  'https://www.gstatic.com/recaptcha/releases/<random_string>/recaptcha__en.js';` and then continue and the problem solved.
