### ISSUE TITLE
last seen date/time would be useful in the 'review unverified session' popup

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#12147]
... as would an option to say 'yeah that was me but I don't need that device any more, you can vape it'

**Comment by ara4n** [comment]
but a malicious server trying to make you trust a ghost device will lie about the date/time. unconvinced this is the right solution.

**Comment by Half-Shot** [comment]
I'd like for the *client* to track last seen / first seen times for a device for my own and other users devices. There doesn't need to be trust on the server, but it lets me know if a device has been recently maliciously injected or it's an older one. Most people don't rename their devices and the names are basically useless if you're calling it "riot.im/develop"

**Comment by kittykat** [comment]
@richvdh The Security & Privacy settings now have this information, is this enough to consider the issue resolved?

![Screenshot from 2021-12-29 10-57-34](https://user-images.githubusercontent.com/51663/147655414-ca6c2e8b-5537-4c14-9eab-d53f1238b5ff.png)

**Comment by richvdh** [comment]
I think this was specifically a request to add the info to the pop up, which currently looks like:

![image](https://user-images.githubusercontent.com/1389908/148101260-6f617351-5549-4f06-923b-bc235ac81804.png)

However, I don't feel particularly strongly about it - as you say, its presence on the S&P dialogue is sufficient.
