### ISSUE TITLE
sending emoji with : after a word without a space eats the word

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/element-web#12154]
if I type `text here:happy<tab>` I get `text 😄` sent

**Comment by mvgorcum** [comment]
looks like this is related or dup of  #11546

**Comment by yannicka** [comment]
When I press `<tab>` it flashes red without eating the word (on Element Web 1.7.14):

![Peek 28-11-2020 14-28](https://user-images.githubusercontent.com/22885898/100516730-1b664d00-3186-11eb-8170-746e64a3e493.gif)
