### ISSUE TITLE
New Invite dialog can have two scrollbars

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#12159]
![image](https://user-images.githubusercontent.com/2403652/73477333-ed5c8480-438b-11ea-8297-31744e015a66.png)

**Comment by turt2live** [comment]
Is your vertical height narrow by chance?

**Comment by t3chguy** [comment]
Yes, I have devtools up

**Comment by turt2live** [comment]
well, at least it's an easy diagnosis: the dialog should have a `max-height` on it or something.

**Comment by turt2live** [comment]
I can no longer reproduce this issue. If you're still running into it, please open a new issue with fresh information.
