### ISSUE TITLE
DM should say name of user is using an unknown session instead of "Someone"

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12162]
<img width="279" alt="Screen Shot 2020-01-30 at 5 06 07 PM" src="https://user-images.githubusercontent.com/5855073/73498397-d8c7be80-4382-11ea-8d99-253e1fbcd7df.png">

"Someone is using an unknown session" when it is a direct message could be pretty concerning. It should probably say "Aaron is using an unknown session" or "Aaron isn't verified". Otherwise it could sound like someone is eavesdropping on the room.

Maybe this needs canonical DMs.

**Comment by turt2live** [comment]
The new room list doesn't have this.
