### ISSUE TITLE
`enable_presence_by_hs_url` seems not to be working

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#12164]
If it's supposed to work like I think it is, I think it is meant to suppress any visualisation of presence for users on a given homeserver (specified by homeserver URL).

Connecting at least from https://riot.im/develop to `lant.uk`, all the `matrix.org` users appear offline.

**Comment by turt2live** [comment]
It only works if your homeserver URL is `https://matrix.org` (or whatever it is nowadays). Because you're connecting from not-matrix.org, your homeserver URL doesn't match.

**Comment by MadLittleMods** [comment]
Is this just a configuration problem? Seems like `enable_presence_by_hs_url` just needs to match your homeserver if you want to see presence.

Element `config.json`
```json5
{
    // [...]
    "enable_presence_by_hs_url": {
        "https://lant.uk": true
    }
}
