### ISSUE TITLE
You can type multiple lines into the new direct message starting dialog

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12163]
I typed in part of a username and then assumed that hitting enter would choose the only suggestion. Instead it started a new line which hid what I had typed in.

**Comment by turt2live** [comment]
Merging into https://github.com/vector-im/riot-web/issues/12163

**Comment by turt2live** [comment]
*https://github.com/vector-im/riot-web/issues/12205

**Comment by ara4n** [comment]
I don't understand why this has been closed in favour of a "switch to using CIDER" bug.

Right now...

> I typed in part of a username and then assumed that hitting enter would choose the only suggestion. Instead it started a new line which hid what I had typed in.

...is still a massive problem, which feels orthogonal to the entry method being used.

**Comment by aaronraimist** [comment]
Seems to have been fixed, probably by https://github.com/matrix-org/matrix-react-sdk/pull/5387
