### ISSUE TITLE
"This wasn't me" should delete/log out the device

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12177]

**Comment by kittykat** [comment]
> If this refers to the "New login. Was this you?" popup, then the UI has since changed. There is an option "Check your devices" which takes you to a screen where you can select and remove the device. This looks like a request for UI enhancement, so that this become a one-click operation.

Closing as the UI has changed, please open a new issue with clear ACs if any improvements are needed to the new UI.
