### ISSUE TITLE
RoomPreview layout in auxpanel is broken and scrolls if the height is too short

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1218]

**Comment by MadLittleMods** [comment]
This doesn't seem to be the case anymore.

I can resize to the minium 150px height in Chrome and it is still functional:

![](https://user-images.githubusercontent.com/558581/132074193-d3ac09d2-909c-4cde-94cf-60ea66cc4bd1.png)

![](https://user-images.githubusercontent.com/558581/132074285-fbf02acd-9f3c-4130-9348-de1629207664.png)
