### ISSUE TITLE
Pressing ESC when editing a message should stop editing the message if no changes were made

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12190]
So that it does the same as pressing the down arrow when editing a message.

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by krkc** [comment]
I'm trying to recreate your issue. When I'm in edit mode for a message, hitting the Esc key exits edit mode for that message and moves focus down to the main composer input at the bottom. If I had made changes, those changes get scrapped. Down arrow moves edit mode down to my following message, but only if there aren't changes. This isn't happening for you?

**Comment by t3chguy** [comment]
Debugged this with anoa irl, it happened on both his machines which are running Linux with i3, only in FIrefox Nightly, in Chrome it was fine. Could not reproduce in FIrefox Nightly on Firefox

**Comment by t3chguy** [comment]
@anoadragon453 are you still hitting this? I could never repro it :(

**Comment by anoadragon453** [comment]
Right, I think I've pinned this down to my [Vimium-FF](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) add-on. Once turning that off, ESC behaves as normal.

Apologies for the late reply and wild goose chase :)
