### ISSUE TITLE
Solution for solve issue of breadcrumbs implementation

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#12200]
** I heard before in matrix live from some members of the matrix.org team, questioning if breadcrumbs should be implemented by default or not. So will present a solution that will not be necessary to implement breadcrumbs by default. But can fix the issue that breadcrumbs is trying to solve. **
So the problem that is causing problems, is when some post starts a new prolonged discussion, and because this is taking place, the room ends up in a way being "spammed", My proposal would make this problem go way, not having the need to implement the breadcrumbs feature has a default. Because this would fix it in a more practical and intuitive way.

** So my proposal is to create a drop-down button/interaction, when somebody responds to a specific issue (so the person that posted the originally would have the option to concatenate it). So basically would be like the sub feature of raddle/reddit. Or the drop-down feature of youtube comments. **
When you would press to reply, your answer would go inside this drop-down "sub-thread" and it would be closed/pushed-up by default. Once you click the button/feature, the conversation related(replied) to that post, would drop-down between to lines (has shown in the picture in attachments). Making it possible for other people to continue with other conversations in the room, while not spamming the whole room, with a conversation that might not be relevant for many of the room members.
P.S. Would be more practical if the matrix.org back-end (protocol edit feature) would be used to show the latest response, instead of just the original post, so people with the conversation hidden can still follow it (you would have the original question/suggestion and then the latest response to it), while having the possibility to post new subjects.
(also maybe if the dropdown feature could be on or off by default depending on the number of room members, so if the room has more than 35 members make it on(hidde answers) by default, while if less then 35 members make it off(show all answers)by default).

** Edit and breadcrumbs feature. **
This features could solve the problem, but for example (has discussed by the team before, making it a default would not be the best move for a user-friendly/intuitive experience) the breadcrumb could be helpful in solving the problem but more geared toward power user and not the everyday user.

** Additional context. **
Of course this could be done just by rethinking the way the breadcrumb feature is used or by extension to it, but so its easier the understatement of my proposal. Preferred to call it a separate feature (though again is just a re-implementation/extension of the breadcrumb feature with assistance of the edit feature).
Here I presented a template of what I'm suggesting being the situation on the left the default position of the toggle/drop-down button the middle one when text is appearing and growing from hidden to a drop-down and them finally the situation on the right the "on switch" situation.
![breadcrumbsPROPOUSAL](https://user-images.githubusercontent.com/47955574/73612899-f77abf00-45e7-11ea-802f-14cfb2127687.png).

**Comment by robintown** [comment]
This sounds exactly like threads, which we now have.
