### ISSUE TITLE
Latest events not shown

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#12225]
In certain rooms (eg `!bNAPsppHlSHCDvMRhh:abolivier.bzh`) I can't see events that I know were sent overnight. Will rageshake.

**Comment by richvdh** [comment]
fixed itself on reload

**Comment by bwindels** [comment]
possibly related to https://github.com/vector-im/riot-web/issues/12216

**Comment by t3chguy** [comment]
Closing in favour of #12216 due to lack of info to discern it
