### ISSUE TITLE
Riot won't reload cache from IDB if initial sync doesn't contain push rules

### ISSUE THREAD

**Issue by neilalexander** [vector-im/element-web#12247]
### Description

Dendrite doesn't currently implement the push rules API and therefore didn't return any push rules in the initial sync. This resulted in Riot being unable to reload the cache from IndexedDB after page refreshes.

A temporary workaround was added into Dendrite in the form of matrix-org/dendrite#862 but we would like to revert this when the problem is fixed as it breaks one of the sytests.

### Steps to reproduce

- Log into a homeserver that doesn't send push rules in the initial sync
- Refresh the page

The cache doesn't load from IDB due to an unmarshalling nil error.

### Version information

- **Platform**: web

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I can no longer reproduce this - manually deleted the `accountData` store in the sync accumulator - though it still relies on https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3pushrules being correctly implemented - and will not be catering to invalid implementations
