### ISSUE TITLE
Unable to decrypt: The secure channel with the sender was corrupted. Trying to create a new secure channel and re-requesting the keys.

### ISSUE THREAD

**Issue by neutralinsomniac** [vector-im/element-web#12250]
### Description
Got a random "Sender hasn't sent us the keys for this message" incoming message on Riot iOS during one of my 1-1 chats, so I fired up one of my riot web instances to check the room there, and instead was greeted with the message in the title (and messages that I could decrypt on iOS are not able to be decrypted on riot web). Logs will be attached to this issue.

### Steps to reproduce
Was having a conversation in a long-running e2ee 1-1 room with a friend from riot iOS, got an unable to decrypt, fired up riot web, got corrupt session errors.

![2020-02-05-082201_1002x536_scrot](https://user-images.githubusercontent.com/92071/73845488-c3261f00-47f0-11ea-8ec3-ce748b14b3b2.png)

### Version information
riot iOS v0.10.4
riot-web develop (c3e6a3078958-react-73b177d07567-js-312976294b7e)

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 72.0.2
- **OS**: Debian 9
- **URL**: riot.im/develop

**Comment by neutralinsomniac** [comment]
Also ran into this issue on latest chromium. debug logs have been sent

**Comment by jaredsmith** [comment]
I'm seeing this more and more as well...

**Comment by drahnr** [comment]
Killed the `riot-desktop` application once, restored from key backup and then _most_ already received messages get decrypted successfully afterwards. But most new messages are again showing

```
** Unable to decrypt: The secure channel with the sender was corrupted. Trying to create a new secure channel and re-requesting the keys. **
```

. Re-importing an exported e2e keyset from device #2 (Android, which still works flawlessly) and importing with Device #1 does not change the fact.

Pressing the `Re-request encrypted keys` link does not do anything.

1.6.2

**Comment by richvdh** [comment]
Nobody has had time to investigate the rageshakes, but likely due to one of the causes already listed at https://github.com/vector-im/element-meta/issues/245.
