### ISSUE TITLE
Mentions shouldn't look like unsent messages

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#12287]
In contexts with unreliable connections, it is quite normal to see a bunch of red messages (in black theme) at the bottom of the messages area - those are the ones that haven't been sent yet.
Mentions are flagged in the same way, and easily get missed because of that - epecially if they are sitting right at the top of a stack of unsent messages.

**Comment by aaronraimist** [comment]
Related: #441 #6520 #11927

**Comment by robintown** [comment]
Unsent messages now look like this rather than being highlighted red:

![](https://user-images.githubusercontent.com/2403652/128317926-158e0870-2bcc-4cc4-91e5-b2163bd554eb.png)
