### ISSUE TITLE
inviting a user who's already in the room no longer gives a sensible error

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12281]
it just says 'invite failed' and you have to guess why

**Comment by turt2live** [comment]
it tries very hard to exclude users already in the room - how did you end up getting that far?

**Comment by t3chguy** [comment]
Similar to https://github.com/vector-im/riot-web/issues/12051

**Comment by t3chguy** [comment]
Turns out I fixed this and then broke it in a totally new way, who'd have though `throw new new MatrixError` wouldn't do the right thing 🤦
