### ISSUE TITLE
Room passwords

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#12290]
In most West-African countries (and no doubt elsewhere) smartphones are a rare luxury article, used by large communities (i.e. often the whole village).  Since those people are mostly hardly literate, logging out and in is not a live option.  Allowing simple passwords for rooms would go a long way to providing some privacy in their communications.

**Comment by Biep** [comment]
In fact, a line pattern (as with many modern 'phones) would even be better.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/51
