### ISSUE TITLE
Breadcrumbs fade effect can become slightly offset when scrolling

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12296]
### Description

![image](https://user-images.githubusercontent.com/1342360/74105317-9fe2d300-4b54-11ea-8352-f5daa2dea884.png)

When scrolling, the fader bit can become slightly detached from the side of the breadcrumbs window, producing this obvious breakage.

Scrolling over one more time fixes it though.

![image](https://user-images.githubusercontent.com/1342360/74105341-d4568f00-4b54-11ea-8eb2-c0c5b8df1977.png)

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly v74.0a1
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I refuse to believe this is a bug given how much time we've spent mitigating it. 

In helpful news: does this only happen on nightly?

**Comment by anoadragon453** [comment]
I haven't seen this recently, and given nobody else has weighed in over the course of a year and a half it's probably no longer an issue.
