### ISSUE TITLE
Unencrypted messages after encryption was turned on.

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#12313]
![image](https://user-images.githubusercontent.com/195073/74204008-5fab5e00-4cd6-11ea-9da2-5360e45a953c.png)

My colleague turned on encryption. The next couple of messages I sent from Riot-Web still went unencrypted. Then, a message sent from Android to the room was encrypted properly. And when I went to create this bug report, also Riot-Web sent encrypted messages.

Maybe the keys took a bit longer to exchange, but Riot should definitely not claim that it turned on encrypted, and then proceed to send unencrypted messages.

riot-web version: 1.5.7.9
olm version: 3.1.3
FF: 72.0.2

**Comment by kittykat** [comment]
I'm going to close this issue as we cannot reproduce it any more. If you are still experiencing it, please comment with @kittykat and I will reopen it.
