### ISSUE TITLE
Links in communities break riot

### ISSUE THREAD

**Issue by theotheroracle** [vector-im/element-web#12330]
### Description

I made an `<a href="https://riot.im/app/#/user/@ellietheoracle:the-apothecary.club">The Oracle</a>` tag, and it crashed riot and it wouldn't re-open, even after clicking the clear cache and re-load button.
### Steps to reproduce

- Create community
- add `<a href="https://riot.im/app/#/user/@ellietheoracle:the-apothecary.club">The Oracle</a>` to the Long HTML description.
- Click on the link

Describe how what happens differs from what you expected.

I would expect it to open a link to my account but instead it crashes.

![image](https://user-images.githubusercontent.com/20211219/74289478-c2abed80-4cf4-11ea-94ac-9f0e769e2a85.png)

### Version information

- **Platform**: web (in-browser) or desktop?

Windows, Chromium - Edge, /develop

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
