### ISSUE TITLE
Can't disable inline URL previews in user settings

### ISSUE THREAD

**Issue by jdm** [vector-im/element-web#12339]
### Description

Toggling the "Enable inline URL previews by default" option does not preserve the new value when closing the settings windows.

### Steps to reproduce

- open the user settings dialog
- go to the preferences tab
- toggle "Enable inline URL previews by default"
- press the X to close the settings window
- open the user settings dialog
- go to the preferences tab

Instead of display the new toggled value that I chose, I see the original value from before I toggled it. Other preferences retain their toggled values without any difficulty.

Logs being sent: no

Before toggling:
<img width="1440" alt="Screen Shot 2020-02-12 at 9 07 39 AM" src="https://user-images.githubusercontent.com/27658/74342229-2d9e0880-4d77-11ea-957d-8f52be880405.png">
After toggling:
<img width="1440" alt="Screen Shot 2020-02-12 at 9 07 46 AM" src="https://user-images.githubusercontent.com/27658/74342256-368eda00-4d77-11ea-95ac-aeb76a24a07b.png">
After closing and reopening the settings:
<img width="1440" alt="Screen Shot 2020-02-12 at 9 07 53 AM" src="https://user-images.githubusercontent.com/27658/74342286-3ee71500-4d77-11ea-8a6e-75ee9c757a23.png">

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 74 nightly
- **OS**: macOS
- **URL**: chat.mozilla.org

**Comment by SeerLite** [comment]
Getting the same issue on the Desktop version on Linux. I want to enable it however, it reverts to disabled when closing.

**Comment by SimonBrandner** [comment]
@jdm Are you still able to reproduce this on a non-`matrix.org` server? I am not

@SeerLite On which server are you? If it's `matrix.org`, it might be a global server problem

**Comment by SimonBrandner** [comment]
Also note that for end-to-end encrypted rooms you have to enable it, in the room settings

**Comment by SeerLite** [comment]
Sorry, I got confused, I didn't have this exact issue. I was having the problem with the URL previews in the room settings on E2E chats, not the user settings.
I'm not having the issue anymore though, it's working fine on matrix.org. You may have been right about it being a server problem (that got fixed?). Thanks

**Comment by jryans** [comment]
I believe this is an operational issue that should now be fixed. If others are seeing this, please check with your homeserver admin.
