### ISSUE TITLE
Formatting bar doesn't understand where the top of the composer is

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12359]
When highlighting a large selection (~20 lines) and scrolled down, the formatting bar shows up in the middle of the timeline:
![](https://i.imgur.com/p0rk7u3.png)

**Comment by dkasak** [comment]
More info: for me this happens when selecting text from top to bottom, but not in the other direction. If the text is long enough, the bar scrolls beyond the edge of the screen and disappears completely.

**Comment by turt2live** [comment]
well, I got this from a <kbd>Ctrl</kbd>+<kbd>A</kbd> on my end, and still do.
