### ISSUE TITLE
Hitting insert on CIDER editor on mac puts editor into insert mode

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#12355]
...by making the cursor a 1 character wide selection, thus overwriting the selected character when you press a key. This is pretty much a correct implementation of overwrite vs insert mode, but I did this by accident and it took someone else telling me what it was for me to realise what was happening. This is probably not a feature people expect in modern text entry and I don't think it's a feature we have intentionally.

**Comment by t3chguy** [comment]
Cannot reproduce this anymore
