### ISSUE TITLE
don't autodetect language formatting in inline code blocks

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12366]
it rarely makes sense, is often wrong, and you can't override it

**Comment by turt2live** [comment]
this is an option that can be turned off. Preferably we'd keep it so there's at least some syntax highlighting. It can also be overridden with the language name after the opening backticks.

**Comment by t3chguy** [comment]
I think M is meaning single backtick blocks (inline) which cannot have the language name specified so you're always at the whim of autodetect if you want autodetect on your code blocks.
