### ISSUE TITLE
UI feedback during cross-signing is a bit awful with slow network

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#12376]
I artificially slowed down my connection to repro this, but believe me it was awful when I first tried it and the network was just busy.

![Peek 2020-02-14 16-03](https://user-images.githubusercontent.com/1389908/74547254-b9fd2680-4f43-11ea-8f8c-8d643792e2e9.gif)

* when you click "continue" on the "New session" dialog, nothing happens, so you hammer on it a bit to check it's been sent. Eventually it changes to "verification request"
* then you get 5 verification requests at the other end. If you accept one, it seems like it might not be the one that the initiator is showing, so nothing happens until you cancel the request from the initiator...
* which doesn't cancel the remaining pop-up on the receiver so then you have another verification request which goes nowhere.

**Comment by foldleft** [comment]
a lot has changed in the cross-signing world, it's possible this one's handled already.  Anyway, I'll try to generate some action items.

**Comment by foldleft** [comment]
... I've found a blocker that makes it difficult to do that, so I'm hopping off this task and filing other ones for now :D

**Comment by kittykat** [comment]
This has been redesigned so closing this issue for now, please open a new one for further improvements :+1:
