### ISSUE TITLE
Some reactions don't render with twemoji on Fedora 31 + Epiphany

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12378]
![image](https://user-images.githubusercontent.com/1294269/74573988-2b57cc00-4f7a-11ea-82b7-bb9bbd91791d.png)

Fedora 31, GNOME
(Epiphany 3.34.3.1-4-gcc40c9a02, WebKitGTK 2.26.3)

However, the emoji renders correctly in the composer:

![image](https://user-images.githubusercontent.com/1294269/74574019-3874bb00-4f7a-11ea-9a01-57006da3b6dc.png)

**Comment by Exalm** [comment]
So, looks like the char from the reaction is different from normal ☝️:

☝︎
☝️

**Comment by Exalm** [comment]
```
E2 98 9D EF B8 8E
E2 98 9D EF B8 8F
```
So, looks like a wrong bit at the very last position?..

**Comment by ara4n** [comment]
Looks like the problem is that the reaction uses  `e2 98 9d ef b8 8e` but the emoji uses `e2 98 9d ef b8 8f` - and for whatever reason, twemoji fails to render the former on that OS and it falls through to the system font.

This sounds suspiciously like a COLR versus SBIX thing.

What does https://pixelambacht.nl/chromacheck/ show?

**Comment by Exalm** [comment]
Well, not just to system font, it also falls through the system emoji font.

![Screenshot from 2020-02-15 03-45-39](https://user-images.githubusercontent.com/1510457/74574486-bdac9f80-4f7b-11ea-9dbf-e026ee71ed5d.png)

**Comment by ara4n** [comment]
it's using SBIX apparently. perhaps the glyph is missing.

**Comment by ara4n** [comment]
the glyph isn't missing. instead, somehow we have a variant selector applied to the codepoint
the black and white one has https://codepoints.net/U+FE0E?lang=en applied
the colour one has https://codepoints.net/U+FE0F?lang=en applied
FE0E apparently means " If that is a symbol, dingbat or emoji, U+FE0E forces it to be rendered in a textual fashion as compared to a colorful image."
FE0F apparently means "If that is a symbol, dingbat or emoji, U+FE0F forces it to be rendered as a colorful image as compared to a monochrome text variant."

@tulir: any idea why the one in the reaction picker would have ended up with a black & white variant selector applied to it?

**Comment by Exalm** [comment]
Looks like same thing happens in Safari:

![Screenshot from 2020-02-15 22-29-44](https://user-images.githubusercontent.com/1510457/74592418-2b5ad900-5019-11ea-8c5e-3f28e780815b.png)

**Comment by aaronraimist** [comment]
The Safari issue is https://github.com/vector-im/riot-web/issues/9895

**Comment by t3chguy** [comment]
I believe this is fixed, the upstream lib fixed their unicode
