### ISSUE TITLE
pasting multiline msgs into CIDER ends up with CRLFs getting swallowed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12398]

**Comment by gllyons** [comment]
I think I am seeing the same issue. some of my chats  seem to lose the newlines I put in and just get bunched up on one line, but others work. I am having trouble telling what the difference between the working and nonworking ones. It seems sometimes the newline gets sent  as <p> in the source and other times as \n

**Comment by t3chguy** [comment]
Is this in the input box or once sent?

Is it https://github.com/vector-im/riot-web/issues/12493?
