### ISSUE TITLE
Cross-signing issues when using a fresh riotx install

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#12407]
### Description

When I re-installed riotx from scratch I ended up with a bad flow. I've numbered the issues - they may be all unrelated bugs.

### What happen

1) While riotx was still initial-syncing, riot-web popup'd to let me start verification. I did so, but riotx was still syncing, unable to respond. RiotX completed sync, did not acknowledge the verification. At this point I was left to cancel on the riot-web side.

2) Initiating from the riotX side, I began verification. This gave me a modal on riot-web with a QR code that took multiple attempts to read successfully from a Pixel 2, on a well-lit screen right in front of me.

3) After successfully scanning, riotX confirms all is well. riot-web presents the following:

```
#### Verification Request
Verification cancelled

benpa cancelled verification. Start verification again from their profile.
```

When I refresh riot-web, I see that riotX ("Mobile") is still in the list of devices not verified.

### Version information

riot-web: 5ac9902384c0 (/develop)
riotX: 0.16 from play store

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot debug it further and functionality has changed since it's been filed. Please open a new issue with a rageshake if you are still experiencing the problem.
