### ISSUE TITLE
"Help" doesn't actually provide any assistance

### ISSUE THREAD

**Issue by bjherbison** [vector-im/element-web#12415]
As a user of Matrix I want to learn how to use it, but no answers are given

### Steps to reproduce

- Log into a Matrix instance.
- Click my name in the upper left.
- Click help.

Expected:
I get information on how to get help in using Matrix.

Actual:
A popup appears with this message:
Report bugs & give feedback
If you run into any bugs or have feedback you'd like to share, please let us know on GitHub.
To help avoid duplicate issues, please view existing issues first (and add a +1) or create a new issue if you can't find it.

I tried clicking many other places on the page and none gave me any assistance or any links to any tutorials or documentation.

### Version information

- **Platform**: web

- **Browser**: Firefox Nightly 75/
- **OS**:  Ubuntu with XFCE.
- **URL**: https://chat.mozilla.org/

**Comment by t3chguy** [comment]
Help has since been renamed to Feedback and made a little more useful

![image](https://user-images.githubusercontent.com/2403652/97856342-0cf65400-1cf4-11eb-91c1-715c4e18623b.png)

**Comment by aaronraimist** [comment]
There is now a link to https://element.io/help at the top of the Help & About section of settings.

**Comment by turt2live** [comment]
Between marketing and improvements over the years, I think we can close this. If folks run into further issues with the availability of documentation, please open a new issue with fresh information.
