### ISSUE TITLE
10 minute timer on verifications doesn't work anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12424]
I was staring at a QR code for 10 minutes and it never cancelled the verification

**Comment by bwindels** [comment]
There is currently a time-out to accept the verification request of 10 minutes, and another time-out of 10 minutes to finish SAS verification once you've started it. So yeah, it wouldn't currently time-out after having accepted and showing your verification options.

Re-reading the spec, it looks like we're not 100% compliant indeed ([and should only have one time-out of 10 minutes after sending the request OR 2 minutes after receiving it](https://matrix.org/docs/spec/client_server/latest#key-verification-framework)) but it doesn't seem to imply there should be a time-out when showing the QR code. [MSC2366](https://github.com/uhoreg/matrix-doc/blob/key_verification_accept/proposals/2366-key-verification-accept.md) doesn't say anything about time-outs :thinking:

**Comment by turt2live** [comment]
At one point we knowingly did not follow the spec perfectly and just had a 10 minute timeout after the last event in the sequence.

**Comment by t3chguy** [comment]
My bad, the above PR only fixes the pre-accept timeouts, this is about some off-the-spec 10 minute post-accept timeout (during SAS/QR)

**Comment by t3chguy** [comment]
I cannot reproduce this, whilst in the SAS (emoji) phase I observed a 10 minute timeout.
The only place I couldn't see a timeout was here:

![image](https://user-images.githubusercontent.com/2403652/83261613-86bd6b00-a1b3-11ea-9967-fb80f67eff5d.png)

Which should happen if there is a QR code, as anything extending Base.js will timeout in 10 minutes but here there is no verification. The solution is to skip this view and jump straight into SAS Verification if QR is not available ( https://github.com/vector-im/riot-web/issues/12995 )

**Comment by kittykat** [comment]
Faye and I can confirm that it times out now.
