### ISSUE TITLE
Share room button should use alias instead of room ID

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12447]
Even when there is a canonical alias set

<img width="1004" alt="Screen Shot" src="https://user-images.githubusercontent.com/5855073/74989666-b1ef2c00-5406-11ea-99b1-4e6c8815dbe2.png">

**Comment by turt2live** [comment]
This is currently a feature: the room is permalinked, not using an alias.

**Comment by aaronraimist** [comment]
It would make the links even longer but what if you could include an alias and a room ID in a matrix.to link. That way you have a pretty alias but the fallback of a room ID. I guess the client would have to figure out if that alias is actually pointing at that room ID. It would allow you to get rid of one of the via servers which would help with https://github.com/vector-im/riot-web/issues/11143.

This is biting Mozilla. See convo in #livehacking:mozilla.org today.
