### ISSUE TITLE
URL preview settings page tells lies

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12445]
<img width="596" alt="Screenshot 2020-02-20 at 21 01 40" src="https://user-images.githubusercontent.com/1294269/74978343-4b790680-5424-11ea-82d8-92f3f14c57f2.png">

In this room, URL previews were not disabled by default for participants in the room - there were no state events at all to specify their behaviour....

**Comment by Infinity-Intellect** [comment]
@ara4n I would like to work on this issue.

**Comment by jryans** [comment]
@Infinity-Intellect In general, feel free to work on unassigned issues and submit PRs. If you're unsure how to proceed, I'd suggest asking in #riot-dev:matrix.org about whichever issues interests you the most.

**Comment by Infinity-Intellect** [comment]
@jryans Thank you, I'm new to the community and was feeling kind of lost.

**Comment by MadLittleMods** [comment]
This looks to be updated now to not mention the behavior of other participants ⏩

**Room settings** -> **General** -> **URL Previews**

> **URL Previews**
> 
> When someone puts a URL in their message, a URL preview can be shown to give more information about that link such as the title, description, and an image from the website.
> 
> In encrypted rooms, like this one, URL previews are disabled by default to ensure that your homeserver (where the previews are generated) cannot gather information about links you see in this room.
> 
> Enable URL previews for this room (only affects you) [x]

![chrome_2021-09-24_18-15-10](https://user-images.githubusercontent.com/558581/134748780-cd1fe0bf-a63b-42ae-99bf-a77a5636c6cb.png)
