### ISSUE TITLE
Visual hierarchy in Settings is not distinct enough

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12457]
Particularly on Dark theme, the headings & sections for settings jumble together badly.  It needs more whitespace - possibly vertical between the sections; possibly indenting the contents.

<img width="575" alt="Screenshot 2020-02-21 at 14 07 31" src="https://user-images.githubusercontent.com/1294269/75041287-31870480-54b4-11ea-8c8d-4aa33e6d3a7f.png">

**Comment by robintown** [comment]
It now has more whitespace
