### ISSUE TITLE
Riot should not overrestrict alias character set

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12455]
Riot randomly refuses to let me use capital letters in alias names. This is very frustrating when trying to add alt aliases with different capitalisation...

**Comment by bwindels** [comment]
Alt aliases or local aliases? There's no UI yet for the former though? Latter seems to work for me:

![capalias](https://user-images.githubusercontent.com/274386/75038432-4496d600-54ae-11ea-9c1e-2d3df278aaca.gif)

**Comment by aaronraimist** [comment]
Yeah as far as I can tell Riot doesn't do this (but it should, until the spec finally decides to make aliases all lowercase Riot should at least enforce this)

**Comment by t3chguy** [comment]
Closing as cannot reproduce.
