### ISSUE TITLE
The 'update' button on stable should link to a changelog

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12456]

**Comment by dreamerchris** [comment]
Great Idea! I was suggesting something else on chat.

this should be next to the update button and maybe also functionality to hide the update notification if you would rather stay with an old version

**Comment by jryans** [comment]
I am not convinced we actually want to present the current changelog on stable, as the PRs are quite low level...

It's a bit more work, but some polished release notes as in https://github.com/vector-im/riot-web/issues/9899 would be better.

**Comment by t3chguy** [comment]
Closing in favour of #9899
