### ISSUE TITLE
Ability to disable (some) keyboard shortcuts

### ISSUE THREAD

**Issue by Timvde** [vector-im/element-web#12492]
**Is your suggestion related to a problem? Please describe.**
Some keyboard shortcuts that I use are overwritten by Riot. The major one is ctrl-k, which I use to focus my search bar (I'm using Firefox), but focuses the room filter instead. Another one I stumbled on is ctrl-shift-a, which should open the add-on manager, but pops up some style picker when the input bar is focused.

**Describe the solution you'd like**
The option to disable keyboard shortcuts, or at the very least ctrl-k.

**Describe alternatives you've considered**
I could probably write some userscript, but I haven't looked into it yet.

**Additional context**
The Slack web client allows users to disable ctrl-k specifically (and ctrl-f, but that's not overwritten by Riot, so irrelevant at this moment)

**Comment by DanielGibson** [comment]
Yes, it should be possible to disable this.
I've been using Ctrl-K in Firefox to get to the search bar since forever, it's super annoying when web apps/web sites hijack that combination

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15076 which lets you change your keybinds (including disable)
