### ISSUE TITLE
Allow sorting/reordering of channels in the channel list.

### ISSUE THREAD

**Issue by travis79** [vector-im/element-web#12525]
**Is your suggestion related to a problem? Please describe.**
I have a few rooms/channels that are closely named that I follow, and it sometimes means I have to be deliberate about which one I post in.  

**Describe the solution you'd like**
If I could reorder the channels to some meaningful order, and not just the order that they were favorited in, etc. it would be very useful to me.

**Describe alternatives you've considered**
The only other way I've found to order my list, is to remove the channels and add them in the order I want.  If I add a new channel, I basically had to start over and remove all my channels to add the new one in the order I wanted.

**Additional context**
N/A

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/8614

**Comment by turt2live** [comment]
This is largely asking for a tagging implementation and/or manual ordering, which is covered by https://github.com/vector-im/element-web/issues/3338
