### ISSUE TITLE
Invite dialog "recently messaged" has wrong value for "days ago"

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#12520]
e.g. it says that I DM'ed Michael 408 days ago, despite talking to him today.

I *think* this is because I have two DMs with him, one of which was last used 408 days ago.

**Comment by turt2live** [comment]
it does indeed pick the first one. Canonical DMs (or a version thereof) would fix this.

I guess it should probably pick the most recent as a stopgap.

**Comment by turt2live** [comment]
I don't think this will be an issue for accounts created/used in the last couple years, so closing as unfortunately such low priority we can't reasonably triage it. If this is untrue, please open a new issue with fresh information for re-triage.
