### ISSUE TITLE
I had two new signin toasts, but when I clicked 'later' they both disappeared

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12540]

**Comment by turt2live** [comment]
ftr I signed in from RiotX, and the first login timed out.

**Comment by MurzNN** [comment]
Now this toast is redesigned to jump to "Check your devices". And now it works well if I have two notifications about new login (it shows 1/2 counter), when I close first one (or press the "Check your devices"), second toast is still visible.
So seems this issue is fixed and we may close it.
