### ISSUE TITLE
Option to skip welcome page

### ISSUE THREAD

**Issue by yesennes** [vector-im/element-web#12551]
**Is your suggestion related to a problem? Please describe.**
I am setting up a private server and would like users to be able to log in as quickly as possible. I don't need a welcome page explaining what riot and matrix are.

**Describe the solution you'd like**
I would like a server wide config option that if true takes the user to the log in page whenever it would take them to the welcome page, i.e. whenever a unauthenticated users goes to the main page or any room's url, or logs out.

**Describe alternatives you've considered**
It would be sufficient to redirect unauthenticated users to the login page whenever they go to and address like #/home or #/roomid.

**Additional context**

**Comment by t3chguy** [comment]
the homepage can be already disabled in config.json

**Comment by yesennes** [comment]
I am having trouble finding that option. I tried setting `embeddedPages.welcomeUrl` to "/#/login" and "login.html" but that gives me a couldn't load page error.

**Comment by t3chguy** [comment]
Null should do it.

**Comment by turt2live** [comment]
There's not currently an option to skip the welcome page. You can change the welcome page content, but if you set the setting to `null` or something like that it will just default to the built-in page. Edit `welcome.html` to do a redirect in the meantime.

**Comment by yesennes** [comment]
That works but causes awkward flashing. Scripts I write in the welcome page don't seem to run either. I can add a config option a make a merge request if you want.

**Comment by turt2live** [comment]
I'd want to check with the product team and development team before recommending a PR on this, only because this particular area of the code is hard enough to maintain and another config option might make it worse/impossible.

**Comment by hex-m** [comment]
> Edit `welcome.html` to do a redirect in the meantime.

How?

I tried putting a `location.href = ..` into `welcome.html` but as @yesennes already mentioned it's not loaded.

**Comment by MadLittleMods** [comment]
This now exists as the [`embedded_pages.login_for_welcome`](https://github.com/vector-im/element-web/blob/c463a50159881669a48a9d330685173c51a41cdc/docs/config.md#branding-and-embedded_pages) option.

>  `login_for_welcome`: When `true` (default `false`), the app will use the login form as a welcome page instead of the welcome
   page itself. This disables use of `welcome_url` and all welcome page functionality.
   
We used this on https://app.gitter.im/ and it works great!
