### ISSUE TITLE
Invite failure error message should be more explicit

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#1256]
Today: 

> Malformed ID. Should be an email address or a Matrix ID like '@localpart:domain'

Suggestion: 

> Unknown user name or malformed ID. To invite a user, enter either their email address or their Matrix ID (e.g. @localpart:domain.com'). Check the spelling of the name you provided if searching among existing contacts.

**Comment by ara4n** [comment]
I would prefer it if we steered them better before they hit this error msg, rather than needing to make the error msg so comprehensive....

**Comment by AmandineLP** [comment]
But the other dis is not going to land before ages so we need a temporary solution

- Amandine
Sent from my mobile - Please excuse typos...

Le 23 mars 2016 à 19:14, Matthew Hodgson <notifications@github.com<mailto:notifications@github.com>> a écrit :


I would prefer it if we steered them better before they hit this error msg, rather than needing to make the error msg so comprehensive....

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/vector-im/vector-web/issues/1256#issuecomment-200473139>

This message and the information contained herein is proprietary and confidential and subject to the Amdocs policy statement,
you may review at http://www.amdocs.com/email_disclaimer.asp

**Comment by turt2live** [comment]
The new invite dialog tries to fix this sort of problem up front
