### ISSUE TITLE
Support account movement

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#12577]
When people move from one server to another (as many are forced to do now that mainland China has blocked matrix.org) they normally want to keep their room memberships and keys.
Of course distributed accounts should become a higher priority now that China starts blocking servers, but until then, it would be great to have a simple way to copy all the relevant account information from one server to another - maybe by, when creating an account on the new server, providing the data for the other account (including password and passphrase).

**Comment by t3chguy** [comment]
https://modular.im/tools/matrix-migration

**Comment by Biep** [comment]
OK - I meant if the old account is unreachable by the user (but still by the server of the new account).
And does the migration tool move decryption keys?

**Comment by t3chguy** [comment]
Given that it doesn't ask you for e2ee passphrases I'd wager not.

**Comment by Biep** [comment]
OK, so then my request is for a feature where an account on a non-blocked server can import the whole state (including keys) of an account on a blocked server.
But still your link is very useful.  Thanks!

**Comment by t3chguy** [comment]
Related https://github.com/matrix-org/matrix-doc/issues/883

**Comment by ibotty** [comment]
> https://modular.im/tools/matrix-migration

Is there some source so it can be run without trusting modular.im?

**Comment by t3chguy** [comment]
It runs entirely in your browser, feel free to Ctrl+S and direct the javascript.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/246 + https://github.com/matrix-org/matrix-spec-proposals/pull/2783
