### ISSUE TITLE
riot crawled to a halt, having gotten worse over the spam of several hours

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12598]
feels like a memory leak but riot was 'only' holding on to ~700mb or so of ram

**Comment by bwindels** [comment]
I measured memory with `about:memory` and it said there were +1000 event listeners on the DOM though

**Comment by bwindels** [comment]
not sure I didn't have the devtools open though :(

**Comment by t3chguy** [comment]
@bwindels do you consider this issue to still be relevant?

**Comment by turt2live** [comment]
Unfortunately for this issue, the app has changed quite a bit over the years. If folks are still seeing performance issues then please open fresh issues with fresh information for us to take a look at.
