### ISSUE TITLE
Notifications don't work anymore with 1.5.11 on Xfce, worked fine on 1.5.10

### ISSUE THREAD

**Issue by promi** [vector-im/element-web#12592]
The Xfce notification applet does not show the Riot icon in 1.5.11, but it works with 1.5.10 (on Debian using the official Riot repo).

The OS is Debian Buster (stable).

If I downgrade to 1.5.10 with the .deb from the local archives cache it works again.

**Comment by turt2live** [comment]
This is highly related to https://github.com/vector-im/riot-web/issues/12518 and might be because of the Electron version increase we did. Should be reverting it for a release tomorrow.

**Comment by promi** [comment]
Yes, looks like it's a duplicate then.

**Comment by jryans** [comment]
This should be fixed in 1.5.12 by reverting Electron back to 7, but we probably want to keep this issue to track a fix for our next attempt to use 8.

**Comment by gerroon** [comment]
Hi,

I have Riot icon on the tray but I am not getting any notifications there at all. There is no indication of new messages. Is this related?

This used to be working perfectly until couple versions ago.

Debian  Testing, Fluxbox with LXDE tray,  Riot 1.5.12

**Comment by foresto** [comment]
I have this problem with Riot 1.6.0 installed from the flathub.org's flatpak. Anyone have a fix?

**Comment by anon88391** [comment]
Experiencing the same thing after updating Riot to 1.6.0 on newest Debian Buster with Xfce.

**Comment by jryans** [comment]
@promi Is this still an issue with current versions of Element?

**Comment by promi** [comment]
The issue has been solved.
