### ISSUE TITLE
Room tombstone and "Encryption enabled" alignment is inconsistent in the timeline

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#12607]
![image](https://user-images.githubusercontent.com/26059643/75893133-a7835800-5e32-11ea-92e1-702717222c8f.png)

The panels should be aligned equally.

### Version information
Riot Desktop on Linux 1.15.10

**Comment by ThobyV** [comment]
Can I be assigned this issue please? Fixed it on my branch

**Comment by t3chguy** [comment]
Design can be inferred from https://github.com/matrix-org/matrix-react-sdk/pull/4218#issuecomment-603291517
