### ISSUE TITLE
Key backup indexedDB transaction is failing

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12625]
I get plenty of these logs on my local test account:

```
Key backup request failed DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at eval (webpack-internal:///83:715:28)
    at new Promise (<anonymous>)
    at Backend.getSessionsNeedingBackup (webpack-internal:///83:712:12)
    at IndexedDBCryptoStore.getSessionsNeedingBackup (webpack-internal:///81:537:26)
    at Crypto._backupPendingKeys (webpack-internal:///85:2072:44)
    at Crypto.scheduleKeyBackupSend (webpack-internal:///85:2028:40)
```

This is on an account where I have skipped completing security, so key backup is not enabled. I'm not seeing this elsewhere.

**Comment by jryans** [comment]
Hmm, this is quite curious... You have persisted storage and you are within the size quota, so there's no issue there.

The stores were just cleared in the same session since you signed out and in with a new account. It seems like most things are able to successfully read and write with IDB, but just not this one function...

I think we would need to step through `getSessionsNeedingBackup` to see what step is failing.

**Comment by bwindels** [comment]
Happy to do ... although interesting that function is running to begin with given that I hadn't enabled key backup. Shall I just put a breakpoint in that function and wait for it to halt?

**Comment by jryans** [comment]
> Happy to do ... although interesting that function is running to begin with given that I hadn't enabled key backup. 

Ah right, skipped over that part before... I wonder if there is a path into `scheduleKeyBackupSend` that we aren't guarding on whether key backup is enabled correctly? Perhaps `scheduleAllGroupSessionsForBackup` needs a guard added...? Similarly, `scheduleKeyBackupSend` should probably ensure it is enabled as well.

> Shall I just put a breakpoint in that function and wait for it to halt?

Yes, that's probably easiest. It should happen fairly fast either after startup or after sending a few messages.

**Comment by richvdh** [comment]
seems like progress has stalled on this.
