### ISSUE TITLE
Add custom theme variable to set user/room pill color

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#12629]
This causes them to blend in on some custom themes such as our Discord dark theme

<img width="274" alt="Screen Shot 2020-03-05 at 6 59 35 PM" src="https://user-images.githubusercontent.com/5855073/76039922-7890e300-5f13-11ea-8ab3-62a1868e46eb.png">

https://github.com/aaronraimist/riot-web-themes/issues/10

**Comment by turt2live** [comment]
Needs design largely to approve the idea of more variables (or to pick variables that will work)

**Comment by bwindels** [comment]
Might also be that we don't have a SASS variable for pill background, and are reusing another variable.

**Comment by d2dyno** [comment]
Updates on this?

**Comment by Oha-you** [comment]
@SimonBrandner I think this issue can also be closed thanks to matrix-org/matrix-react-sdk/pull/7270 😊

**Comment by SimonBrandner** [comment]
True, thanks!
