### ISSUE TITLE
Join Chat Room Dialog Overshadowed by Create New Room

### ISSUE THREAD

**Issue by fantasai** [vector-im/element-web#12641]
![Screenshot_2020-03-06_16-02-40](https://user-images.githubusercontent.com/725717/76131602-f44a6880-5fc3-11ea-9185-e7a9e87f420d.png)

### Description

UI lends itself to creating new rooms much more easily and obviously than finding existing rooms.

### Steps to reproduce

- Sign on with a new account.
- Try to find chat rooms by clicking on "rooms" or the + sign next to it
- Click on various other parts of the UI and find the correct dialog under Explore.

### Suggestions

* Given that "Create a new room" is already part of the Explore dialog, consider removing the Explore button from its current location and making the Explore dialog the target of the + sign next to Rooms. (It doesn't have anything to do with Direct Messages, so it kinda belongs under Rooms rather than over both Rooms and Direct Messages anyway.) This would also be more consistent with how the + sign next to Direct Messages searches for existing people rather than e.g. offering to invite someone onto the server by email.
* If the Rooms drop-down is empty, consider populating it with an Explore option.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/11133 https://github.com/vector-im/riot-web/issues/11899 https://github.com/vector-im/riot-web/issues/8771 https://github.com/vector-im/riot-web/issues/7715

**Comment by Infinity-Intellect** [comment]
I would like to work on this issue. I'm confused as to where would we put the "Add room" feature if we were to make the Explore dialog the target of the + sign.

**Comment by t3chguy** [comment]
There is little point beginning work on this without design sign off.

**Comment by Infinity-Intellect** [comment]
@t3chguy So, as of now this is to be left as is ?

**Comment by t3chguy** [comment]
Yes until design team has time to get around to it. It seems to be a small scale complaint atm as it is. If it gets more thumbs up maybe it will be prioritised

**Comment by jryans** [comment]
Thanks for the feedback @fantasai! 😄 I'm sure this will be on the mind of our design team as we improve the overall first-time user experience and smooth over hurdles like this.
