### ISSUE TITLE
Make screen share option more obvious (and toggle from normal call)

### ISSUE THREAD

**Issue by BloodRaven0** [vector-im/element-web#12652]
**Is your suggestion related to a problem? Please describe.**
The share screen option is pretty hidden right now (in fact, I was gonna suggest adding it, since I had no idea it existed). Why couldn't it be its own button, instead of awkwardly shift-clicking on another button?

**Describe the solution you'd like**
Just add screen share as its own button. Also make it toggle-able from a normal call, instead of being its own call, so you can switch to it without hanging up and calling again.

**Comment by rkaminsk** [comment]
The screen sharing functionality is actually hidden so well that I did not manage to find it. This might not be the best place to ask but it is where google let me. Can someone tell me how to share the screen (I am using element-desktop on Ubuntu) or provide a link to the documentation? A dedicated button would be wonderful! :wink:

**Comment by Isti115** [comment]
As far as I can tell, screen sharing is currently only available from the browser version (Chrome and Firefox are supposed to work) and you can start a screen sharing session by shift+clicking the video call button.

**Comment by SimonBrandner** [comment]
@Isti115 This should be eventually fixed by [this](https://github.com/matrix-org/matrix-react-sdk/pull/5525)

**Comment by morngrar** [comment]
It is also possible to shift-click the video-call-button in the desktop client, just checked now. This is really inconvienient, And it should be possible to switch between these mode on the fly :/

**Comment by SimonBrandner** [comment]
[MSC3077](https://github.com/matrix-org/matrix-doc/pull/3077)
