### ISSUE TITLE
Feature Request: Private Communities

### ISSUE THREAD

**Issue by jtrees** [vector-im/element-web#12658]
**Is your suggestion related to a problem? Please describe.**
I'd like to use Riot for family communication. We want several different rooms (like "planning", "random" or "bob's birthday"). Ideally, we would group all rooms under a community but this community should be private and invite-only.

**Describe the solution you'd like**
The perfect solution would have the following:
- All details about the community (including description, room list and members etc.) would be hidden to users not in the community.
- All created rooms would, by default, be hidden to users not in the community.
- Only invited users can join the community.

**Describe alternatives you've considered**
Perhaps this can be achieved by self-hosting and turning off federation? I have considered this but...
- I'd love to avoid the maintenance burden.
- I want to be part of several communities and have the other communities be federated. This alternative "solution" would require me to have two accounts.

**Related Issues**
#10935 is somewhat related in that it also mentions hidden rooms but it doesn't address the "hidden community" part that this issue is about.

_EDIT: Added hidden members to solution._

**Comment by SimonBrandner** [comment]
Spaces are now in beta
