### ISSUE TITLE
Read Receipt is not in the expected location

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#12660]
<img width="745" alt="Screenshot 2020-03-09 at 12 01 07" src="https://user-images.githubusercontent.com/1197991/76211947-45926c00-61ff-11ea-9aab-8b664ca0373a.png">

Version: 71f2f0e7c98d-react-49fe1887dffc-js-074e02ccf2f9

The blue circle on the right should be after the messages from Friday, not below the "Today" line.

**Comment by t3chguy** [comment]
Possibly caused by https://github.com/matrix-org/matrix-react-sdk/pull/3892

**Comment by SimonBrandner** [comment]
Is this still an issue? I don't think I can reproduce this

**Comment by jryans** [comment]
Hmm, it would be nice to have a set of events in a test room to check definitively... @SimonBrandner, did you set up something like that to check it...?

**Comment by SimonBrandner** [comment]
@jryans I've tried scrolling through some rooms and haven't been able to find anything like this. I also assumed it's not an issue anymore due to [this](https://github.com/vector-im/element-web/issues/4377#issuecomment-597215631).

**Comment by jryans** [comment]
Aha okay, then indeed probably fixed by the revert, thanks for testing! 😄
