### ISSUE TITLE
Remove all references of `m.room.aliases` in react and js-sdk

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12680]
All tasks mentioned in https://github.com/vector-im/riot-web/issues/12337 have been implemented as part of [MSC2432](https://github.com/matrix-org/matrix-spec-proposals/pull/2432), but when searching for `m.room.aliases` in the code, there are still a few occurrences. I've postponed getting rid of those because we're still in the cross-signing sprint, but afterwards we probably want to clean that up.

### `m.room.aliases` references to remove

`matrix-react-sdk`:

 - [ ] [`src/SlashCommands.tsx#L728`](https://github.com/matrix-org/matrix-react-sdk/blob/81533b905fb3b6f1796fed4f4b180ddc524fe78d/src/SlashCommands.tsx#L728)
 - [ ] [`src/Unread.ts#L45`](https://github.com/matrix-org/matrix-react-sdk/blob/81533b905fb3b6f1796fed4f4b180ddc524fe78d/src/Unread.ts#L45)
 - [ ] [`test/Unread-test.ts#L106`](https://github.com/matrix-org/matrix-react-sdk/blob/81533b905fb3b6f1796fed4f4b180ddc524fe78d/test/Unread-test.ts#L106)

`matrix-js-sdk`:

 - [ ] [`src/@types/event.ts#L36-L39`](https://github.com/matrix-org/matrix-js-sdk/blob/12a4d2a7490c13d29a3ce3e1ec3e3929eb51620f/src/%40types/event.ts#L36-L39)
 - [ ] [`src/models/room.ts#L1378`](https://github.com/matrix-org/matrix-js-sdk/blob/12a4d2a7490c13d29a3ce3e1ec3e3929eb51620f/src/models/room.ts#L1378)
  - [ ] [`src/models/event.ts#L1588`](https://github.com/matrix-org/matrix-js-sdk/blob/12a4d2a7490c13d29a3ce3e1ec3e3929eb51620f/src/models/event.ts#L1588)
  - [ ] [`src/models/room.ts#L1383`](https://github.com/matrix-org/matrix-js-sdk/blob/12a4d2a7490c13d29a3ce3e1ec3e3929eb51620f/src/models/room.ts#L1383)

**Comment by MadLittleMods** [comment]
Added a list of references to clean-up to the description.

Looks like a pretty easy technical debt to resolve.
