### ISSUE TITLE
Switch release tarball building to auto-builder

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#12706]
* [ ] Add to riot-builder a mechanism to poll for new release tags (by some metric...) and build the riot-web tarball, sign it and create the github release with the tarball, tarball signature and source tarball signature as an artifact.
 * [ ] Remove these steps from the riot-web release script

Split out from https://github.com/vector-im/riot-web/issues/12452

**Comment by jryans** [comment]
@dbkr If I understand correctly, these parts are only nice to have and do not block release, as we could continue to do them from the riot-web build laptop as before, right?

**Comment by dbkr** [comment]
Sorry - yes, and indeed we did release. This isn't really related to cross-signing any more, just helping us get rid of the release laptop.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23538
