### ISSUE TITLE
Build develop tarball with riot-builder

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#12708]
Now we have our dedicated build box, it would make sense to use it to build the tarballs of the develop branch.

This will necessitate hosting them somewhere else which also has the advantage of not having to go through buildkite to access them (and so everyone would be able to get them in an automated way without having to have a buildkite API key).

Split from https://github.com/vector-im/riot-web/issues/12452

**Comment by jryans** [comment]
@dbkr Should this get the same phasing labels as the others, or is it lower priority?

**Comment by dbkr** [comment]
Lower priority as we have it working as-is, so not necessary for any of the cross-signing stuff.

**Comment by t3chguy** [comment]
We ended up doing something else
