### ISSUE TITLE
if you insert a pill by clicking on someone's senderprofile in the timeline, you can edit inside the pill in the composer

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12728]
<img width="385" alt="Screenshot 2020-03-13 at 11 49 49" src="https://user-images.githubusercontent.com/1294269/76618619-ed21de00-6520-11ea-9702-1eb6bc453b16.png">

**Comment by bwindels** [comment]
Is this on Firefox 73 on macOS?

**Comment by bwindels** [comment]
confirmed to be on firefox on macos, likely to be (close to) latest version (74 or 73)

**Comment by yannicka** [comment]
Does the error still appear on Mac? On Element Web 1.7.14 (nor Element Desktop) on Debian Unstable, I don't have this issue:

![Peek 28-11-2020 14-33](https://user-images.githubusercontent.com/22885898/100516813-c70f9d00-3186-11eb-810b-77bb45f85121.gif)

**Comment by aaronraimist** [comment]
I can't reproduce it in Element in Firefox or Element Desktop on Mac
