### ISSUE TITLE
wording when someone adds a jitsi conf to a room should be more explicit

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#12726]
Today it says 'Jitsi widget added by @xxx:yy.modular.im', it would be good to also tell them what to do to join it: 'Jitsi widget added by @xxx:yy.modular.im. Click on the banner to join the conference.'

**Comment by turt2live** [comment]
@vector-im/design can we get copy for this?

**Comment by nadonomy** [comment]
@turt2live sorry triaging through some older issue, can you expand on the context where this is shown & I can suggest some copy from there?

**Comment by turt2live** [comment]
Starting a jitsi call results in the message Amandine references in the timeline.

**Comment by nadonomy** [comment]
Ah gotcha. I just benchmarked production. I think it'd make sense to add a generic [Show]/[Hide] text toggle every time a widget is shown, so instead of:

- 'x widget added by y.'

you can toggle between:

- 'x widget added by x. Show'
- 'x widget added by x. Hide'

We should be able to just use the text link styles with our accent colours. If we need designs before dev if whoever works on this pings design for them we can attack them ad hoc.

**Comment by turt2live** [comment]
What is being shown and hidden there @nadonomy ?

**Comment by nadonomy** [comment]
The widget itself, so it solves the core of this issue and helps with widget discovery in general, toggling:

<img width="1904" alt="Screenshot 2020-06-19 at 20 02 25" src="https://user-images.githubusercontent.com/4626865/85171917-e0bbc880-b267-11ea-8fd7-2968687586c7.png">
<img width="1904" alt="Screenshot 2020-06-19 at 20 02 29" src="https://user-images.githubusercontent.com/4626865/85171924-e3b6b900-b267-11ea-9310-38130a6df442.png">

**Comment by turt2live** [comment]
oh, interesting. Presumably the show/hide button goes away once the widget is removed.

**Comment by nadonomy** [comment]
@turt2live sounds great!

**Comment by t3chguy** [comment]
This is not easy as the codepaths in that area only allow strings so will need a bit of reworking

**Comment by t3chguy** [comment]
It has been updated slightly now, but does not have the desired interaction yet: 
![image](https://user-images.githubusercontent.com/2403652/94442955-7a1a4500-019c-11eb-8244-57cf87fe84b5.png)

**Comment by turt2live** [comment]
ah ha, there is an issue for this apparently. https://github.com/matrix-org/matrix-react-sdk/pull/5222 fixes this.
