### ISSUE TITLE
Joining rooms may take a while; why not background it?

### ISSUE THREAD

**Issue by IngwiePhoenix** [vector-im/element-web#12747]
### Description

While joining rooms from my own homeserver on "foreign" homeservers, I have to sit through the spinner sometimes for about five minutes. This is due to all the federation requests being done meanwhile - and untill I actually get to see the room view, it can take quite some time.

So, how about backgrounding the room joining process? I went up and down the Matrix and Librem room list, so there are a lot of rooms I want to join...but now it's gonna take possibly forever. I am possibl ynot the first to do that, so being able to basically "background" this task would help a lot.

One way to do it would be to add a section of "in progress" to the UI. The reason I posted this as a UI ticket is precisely due to that - it's because this is already possible with the plain Matrix API, but the UI has to just display this as an in-progress thing instead of making the user sit through the spinner.

### Steps to reproduce

- Install Synapse on your server.
- Find a bunch of rooms on various servers you want to join.
- Join them, and watch as your logs spike and the spinner spins...eventually you will either time out, and have to retry, or succeed and get into the room, at which point you can do the next `/join`.

### Version information

- **Platform**: Web, via Ferdi ( https://getferdi.com/ )
- **Browser**: Ferdi is Electron-based. I don't know it's version...
- **OS**: Windows 10 (1909)
- **URL**: riot.im/app

**Comment by aaronraimist** [comment]
It does keep joining in the background if you switch to another room btw. You don't have to stare at the spinner.

**Comment by ShadowJonathan** [comment]
I heard some suggestions somewhere to move the room-joining to the room list, where instead of the room icon, a spinner would show, with the room details grayed out.

**Comment by SimonBrandner** [comment]
We seem to have this now (https://github.com/matrix-org/matrix-react-sdk/pull/6085), shout if I am missing something!
