### ISSUE TITLE
Avatars jump out of user pills when an inline image is in the same message

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#12750]
### Description

![image](https://user-images.githubusercontent.com/1342360/76787180-6aaf4d80-67b0-11ea-915f-bfa0d17fe7c8.png)

### Steps to reproduce

- Open up /devtools and send a custom `m.room.message` event with the following content:

```
"msgtype": "m.text",
"body": "Location Bot: :hahaha:",
"format": "org.matrix.custom.html",
"formatted_body": "<a href=\"https://matrix.to/#/@location_bot:amorgan.xyz\">Location Bot</a>: <img alt=\"hahaha\" title=\"hahaha\" height=\"32\" src=\"mxc://matrix.amorgan.xyz/5366c4dbd599878ce7b52210ec7c430a002441a6\" />"
```

See the avatar go flying:

![image](https://user-images.githubusercontent.com/1342360/76792447-ff1ead80-67ba-11ea-9bed-d6f374efd2ae.png)

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly v75.0a1
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by robintown** [comment]
A quick test of a message like the given example indicates that this has been fixed
