### ISSUE TITLE
New room directory add screen hits the server on ever re-render

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12778]
Clicking the 'add' button on a bad server causes at least 4 requests for instance. Clicking outside of the box causes another two. Closing the dialog even causes a couple

**Comment by t3chguy** [comment]
So most of the requests will be from verifying the server is valid for the Field verification.
but agreed our Field verification should cache the last value's computation to prevent these duplicate calls.

![server1](https://user-images.githubusercontent.com/2403652/77012666-4e551180-6966-11ea-9be6-66f7d512bc02.gif)

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/10714
