### ISSUE TITLE
New messages are not shown after catchup sync

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12770]
Title is a suspicion of what is happening, but these shakes seem to indicate this:
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2387
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2415

Switching room and back makes the messages appear as far as I know

**Comment by bwindels** [comment]
Could be something with timelines resetting that is not working properly?

**Comment by dbkr** [comment]
This doesn't sound likely to be a problem any more
