### ISSUE TITLE
Jitsi wrapper: Add PTT support

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12795]

**Comment by jaywink** [comment]
@turt2live is this actually still relevant? There is a TODO in jitsi.html linking here, but #12780 claims to "effectively fix" this.

**Comment by turt2live** [comment]
It's still relevant. The effectively fixed part is where the library happens to support this.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8084/
