### ISSUE TITLE
Soft-crash on opening riot with existing session.

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12803]
Rageshake at https://github.com/matrix-org/riot-web-rageshakes/issues/2430

`MatrixClientPeg.get()` is returning `null` somewhere in `RoomView.render` apparently. Only previous error was failing to upload one time keys.

**Comment by t3chguy** [comment]
Not sure what the next best steps are, I think we need to see if we get more reports of it with a build including https://github.com/matrix-org/matrix-react-sdk/pull/4258

**Comment by t3chguy** [comment]
This got fixed
