### ISSUE TITLE
Use distinct user badging for non-cross-signing users

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#12806]
For those users who don't want to use cross-signing, we should use a distinct badge to mark their user profile. Perhaps a gray shield instead of a black shield, but design is still TBD.

**Comment by nadonomy** [comment]
@jryans sorry missed this, can you trace me with the logic/decision making on this one? One of the foundational principles for the new icon language is that existing of a shield simply states whether or not encryption exists, and then we have the verified & unverified states from there.

We could expose this by using an HTML tooltip on a black shield? Relabelling this as suggestion until we chew the fat on this more.

**Comment by jryans** [comment]
@nadonomy This came about when [discussing TOFU options](https://docs.google.com/document/d/1yebJ48PvB2u10N9UjZwdjlxdzkZIxBqsbfnHHLaYkvU/edit) with @ara4n.

We said things like "People who have cross-signing disabled are decorated distinctly/grey", but the exact meaning of that design was not determined.

**Comment by nadonomy** [comment]
@Jryans that was my understanding too, but that entire document is WIP, and is an encapsulated body of work slated for future. 

I think we might be wiser to not leave open issues for things like this— for TOFU specifically other than perhaps one parent issue describing our intentions as far as we understand them at a high level, linking to the doc. Or, we could rename this as a suggestion for now until we commit to it as part of a holistic solution.

As it stands this issue is written as absolute and is focused on an exact solution we’ve yet to validate. In the past that’s tripped us up when picking up again after time as it can mislead requirements.

**Comment by jryans** [comment]
@nadonomy Hmm, okay I think we interpreted the situation differently... I guess when talking about it at the time, I had interpreted this precise piece about "People who have cross-signing disabled" as something we want to label / denote whether or not any other piece of TOFU work happens.

In my mind, this current issue applies also to users who disable cross-signing (we already added such an option as part of [assisting those who require manual key comparison](https://github.com/vector-im/riot-web/issues/12589#issuecomment-595213232)).

> I think we might be wiser to not leave open issues for things like this— for TOFU specifically other than perhaps one parent issue describing our intentions as far as we understand them at a high level, linking to the doc. Or, I’m also happy leaving it open with the suggestion label until we commit to it as part of a holistic solution.

If it were just about TOFU, I would likely agree, but that's the confusion I think: there already si a set of users without cross-signing that this issue applies to with the product in-flight on develop without doing anything about TOFU.

> As it stands this issue is written as absolute and is focused on an exact solution we’ve yet to validate. In the past that’s tripped us up when picking up again after time as it can mislead requirements.

Okay, just trying to capture what we discussed, as it seemed highly likely to be forgotten otherwise, and again it is something that exists outside of the TOFU context. We can happily edit the issue however we need to, or close it if we are fine with people that opt out of cross-signing receiving the default badging.

**Comment by nadonomy** [comment]
> Okay, just trying to capture what we discussed, as it seemed highly likely to be forgotten otherwise, and again it is something that exists outside of the TOFU context. We can happily edit the issue however we need to, or close it if we are fine with people that opt out of cross-signing receiving the default badging.

I'd be inclined to close this out. The issue description doesn't describe a user goal we're trying to satisfy.

**Comment by kittykat** [comment]
I'm going to close this issue for now as per N4d's comment as designs have changed since it's been filed. Please open a new issue if you feel that there are improvements to be made.
