### ISSUE TITLE
clicking on a jitsi widget in the LeftPanel should surely take you to the room it's in (or otherwise expand it)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12813]

**Comment by t3chguy** [comment]
So do we want the iframe to not be interactable with and any attempted interaction to just take you into the room/expand it?

![image](https://user-images.githubusercontent.com/2403652/77224807-21208300-6b61-11ea-853b-6f2657640ef6.png)

**Comment by turt2live** [comment]
Unclear on what this is supposed to do, but one of our many "conferencing sucks" issues will take care of it. We've since moved it to a more useful location.
