### ISSUE TITLE
Right sidebar as generic widget tray

### ISSUE THREAD

**Issue by nivekuil** [vector-im/element-web#12827]
Currently, the right sidebar seems underutilized.  I propose that it be turned into a generic widget tray.

A quick mockup:
![riot_mockup](https://user-images.githubusercontent.com/4633048/77258967-5d281680-6c3b-11ea-9bbd-1328ac569678.png)

Some notes:
- I'd like to see the 3 right sidebar menus on the top right become widgets themselves, so they can be added to (or omitted from) the widget tray along with the existing integration widgets.  Then, instead of three specialized tabs, there could be many generic tabs, each being a widget tray.
- Being able to add multiple jitsi widgets enables a discord-esque interface, satisfying https://github.com/vector-im/riot-web/issues/3546 to an extent.

**Comment by turt2live** [comment]
We've done something similar which we're currently running with.
