### ISSUE TITLE
Uploading corrupted files leaves the upload bar stuck

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#12847]
### during file upload if error occurs or broken link uploading enters a endless loop, both in riot-web and RiotX.

So bassically the uploading was initiated but because it never actually ended sending the content is stuck in the uploading UX, and because this content is still in the process of sending, is impossible to delete that message/content. So ends up jaming the UX riot screen 

### Steps to reproduce

- Upload a file/image etc
- use broken link, maybe a file not present locally etc
- or use a corrupted file, which will start a error on upload

So therefore, never exits the upload progress bar.

### riot-web version: 1.5.13

**GNU/linuxLIBRE, openBSD, Windows, MacOS**
**webrowser:Basilik/Iceweasel/Chrome/gnomeWEB(epiphany)**

riot.im/app

![screenshot](https://user-images.githubusercontent.com/47955574/77461620-c0ac7280-6dfa-11ea-9951-b6da4a6deb35.png)

**Comment by sk-alexis** [comment]
could anyone add label:type:file-upload.

**Comment by sk-alexis** [comment]
@turt2live I think is also important to mentio n that is not only corrupted files but also broken links, so non exitent files locally. And sorry if it is a repetied bug but couldnt find anything similar. cheers

**Comment by turt2live** [comment]
Those are all counted as corrupted here. The issue title is just to give people an idea of what the problem is, then more information is provided in the description.

**Comment by sk-alexis** [comment]
Sounds Good. Cheers. I believe the #11974 is about the same issue it doesnt have a description though.

**Comment by bwindels** [comment]
Broken links make sense to me, but when would a file be considered corrupted? If reading it generates I/O errors?

**Comment by sk-alexis** [comment]
@bwindels I tried this with a bad storage usb I had, where some parts of the file were missing. And Riot instead of, when uploading the file recognizing the error, it just enters in a endless loop. Cheers

**Comment by t3chguy** [comment]
Cannot reproduce since
