### ISSUE TITLE
Clicking the 'Direct message' link in the memberinfo panel to create a DM (with a user with whom you don't already have a DM) gives no feedback and is not debounced...

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#12848]
...leading to a legion of invites:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1922197/77458960-e172c900-6df6-11ea-8aaf-d511ed213662.png">
![image](https://user-images.githubusercontent.com/1922197/77458899-cf912600-6df6-11ea-8e37-8afddd8a7587.png)

Pls add some feedback and some debouncing 👍

**Comment by jryans** [comment]
Thanks for filing! 😁 I'll track this for post-release cross-signing work.

**Comment by lampholder** [comment]
It bit me again! I am not a patient man and all my new friends end up with a million DMs by way of introductiong!

**Comment by t3chguy** [comment]
So you're the invite spammer in the wild!

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot reproduce it. Please open a new issue if you are still experiencing the problem.

**Comment by t3chguy** [comment]
It is still reproducible, but a duplicate of https://github.com/vector-im/element-web/issues/7763 anyhow
