### ISSUE TITLE
Update features for Etherpad

### ISSUE THREAD

**Issue by CsatiZoltan** [vector-im/element-web#12908]
### Description

Riot seems to use a different (older?) version of Etherpad than what the Etherpad website shows. Riot version:

![Riot version](https://user-images.githubusercontent.com/12742890/77786008-55aea600-705d-11ea-927b-16a675d83b5f.png)

On the Etherpad GitHub site:
![online version](https://camo.githubusercontent.com/accef6d646656f22274284ae8518d2b1c3871252/68747470733a2f2f692e696d6775722e636f6d2f7a5972476b67332e676966)

### Version information

- **Platform**: web (in-browser)
- **URL**: https://riot.im/app
- **Version**: 1.5.13 
- **Browser**: Firefox 74.0
- **OS**: Windows 7, Ubuntu 18.04

**Comment by jaywink** [comment]
Etherpad instance for Element widgets has been updated to the latest version.
