### ISSUE TITLE
Etherpad doesn't work in recent Chrome

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-web#12900]
### Description

Etherpad widget shows an error on loading in Chrome 80. The error says
```
An error occurred
The error was reported with the following id: '<redacted>'
Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: DRZzGT6IVQQKtTWm9tzH
URL: https://scalar.vector.im/etherpad/p/<redacted>?showControls=true&showChat=false&chatAndUsers=false&alwaysShowChat=false&showLineNumbers=true&useMonospaceFont=false&userName=<redacted>
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://scalar.vector.im/etherpad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
```

### Steps to reproduce

- Open the Etherpad widget in Chrome 80 (tested in 80.0.3987.149) on Linux
- The error appears

The pad should open normally like it does in Firefox or in the desktop client. It also works fine in Chrome if opened in a separate tab but breaks in the iframe inside the page. Probably a security issue.

Logs being sent: no

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome/80.0.3987.149
- **OS**: Debian testing amd64
- **URL**: anywhere

**Comment by turt2live** [comment]
Seems to be working fine for me: 
![image](https://user-images.githubusercontent.com/1190097/77771434-4b17f080-700c-11ea-8a19-b614ee2a23a2.png)

Looks like you might have some extension or browser feature blocking something it needs.

**Comment by rkfg** [comment]
I use a clear new profile and Riot from riot.im:
![2020-03-27_18-34-13](https://user-images.githubusercontent.com/184066/77772750-b0de9980-7059-11ea-9cec-39844ba973e6.png)
![2020-03-27_18-33-51](https://user-images.githubusercontent.com/184066/77772754-b20fc680-7059-11ea-9221-97c0e9775d24.png)

**Comment by rkfg** [comment]
Maybe this could be of use: 
![2020-03-27_18-37-18](https://user-images.githubusercontent.com/184066/77772974-031fba80-705a-11ea-90d5-6b866c34c7fe.png)

When I press the popout button it loads fine in a new tab and there are no such errors in the console.

**Comment by rkfg** [comment]
https://support.google.com/chrome/thread/33543699?hl=en I think this is the root of the issue, will keep digging for a while. Indeed, document.cookie doesn't work in Etherpad.

**Comment by turt2live** [comment]
I've raised this with the Scalar team to hopefully resolve soon. I still can't personally reproduce it, but all the links you've included here do indicate an impending problem.

**Comment by rkfg** [comment]
If it helps my `google-chrome-stable` is installed from `deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main`, the full version string in that repo is `80.0.3987.149-1`. As of now there's no more recent version available except `google-chrome-beta 81.0.4044.83-1` and  `google-chrome-unstable 83.0.4093.3-1`, both of which don't block these cookies so the issue doesn't arise. Thanks for pushing the issue forward, hopefully it'll get resolved soon.

**Comment by bbigras** [comment]
Any progress on this?

**Comment by t3chguy** [comment]
Looks like an upstream issue which has been fixed and Etherpad needs updating
https://github.com/ether/etherpad-lite/issues/3405
https://github.com/ether/etherpad-lite/issues/3691

**Comment by jaywink** [comment]
This should hopefully be fixed now with an update to the latest Etherpad release. Please reopen or comment with issues if this is not the case for you.
