### ISSUE TITLE
Upgrade encryption flow is dissatisfying

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12903]
A 'you did it!' dialog at the end would help

**Comment by jryans** [comment]
I _think_ this issue only applies to the one-time 4S symmetric migration variant, but we should double check the flow seen by pre-cross-signing accounts that upgrade to cross-signing as well.

**Comment by dbkr** [comment]
Given it will be vanishingly rare for anyone to go through this flow now, it seems extremely unlikely we still care.
