### ISSUE TITLE
images in lightbox have dimensions set

### ISSUE THREAD

**Issue by hramrach** [vector-im/element-web#12933]
### Description

In the lightbox the image has both max-width, max-height, width and height.

width and height are superfluous. In fact they are harmful because the div containing the image has a click action that cannot be activated because the image is in the way.

`<img src="https://matrix.org/_matrix/media/r0/download/matrix.org/uequdgRfSSpZZKKmNMXWWVRw" title="VectorImage_2019-11-25_021140.jpg" class="mainImage" style="transform: rotate(0deg); width: 390px; height: 520px;">`

### Steps to reproduce

Click image in a timeline. Click empty space next to image.

Expected: light box closes
Actual: click delivered to image which has no click action

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chromium 80.0.3987.132
- **OS**: Linux (openSUSE Tumbleweed)
- **URL**:  riot.im/app 
- **Version**: riot-web version: 1.5.14 olm version: 3.1.3

**Comment by danger89** [comment]
This is really an issue indeed. Big images aren't easy to view in the element desktop client. Look (this is 'fullscreen'):

![image](https://user-images.githubusercontent.com/628926/102416728-ace51400-3ffa-11eb-9638-9ddb51a53659.png)
