### ISSUE TITLE
SlashCommands: leave as alias for part

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#12945]

**Comment by julianfoad** [comment]
Within Riot's UI, the use of "/leave" would align with the use of the word "Leave" in the room list context menu. Improving consistency in that way is good.

While aliases matching IRC commands are nice for IRC die-hards, adding aliases to a UI may make the UI incrementally worse for most users. The slash-commands pop-up window is already cluttered with items that general users will find confusing or unnecessary.

Given those two points, and that Riot is aimed at general users (of whom IRC users are only a small minority), it may be better to change it to "/leave", removing "/part".

**Comment by t3chguy** [comment]
the way the autocomplete works is it doesn't show the command & all its aliases, it just autocomplete with both.

![image](https://user-images.githubusercontent.com/2403652/80588975-3c5c9900-8a11-11ea-8c97-083f18db63f0.png)
![image](https://user-images.githubusercontent.com/2403652/80588988-3ff02000-8a11-11ea-9132-2039927734f7.png)

Only the canonical is listed in `/help`

**Comment by t3chguy** [comment]
This got done
