### ISSUE TITLE
Security events copy needs iteration

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#12962]
@nadonomy to expand on this

* ‘You verified’ security event uses mxid rather than displayname in the title?
* Prints ‘displayname accepted’ rather than ‘They accepted’
* Use caption style for mxids?
* E2E enabled tile has extraneous words

**Comment by jryans** [comment]
Seems like this will be happening post-release at the current pace.

**Comment by nadonomy** [comment]
@jryans yup, sorry should've communicated more proactively on this. Best to descope for now and tackle holistically with the myriad of other UX issues we rescoped to phase:4.

**Comment by kittykat** [comment]
I'm going to close this issue for now as designs have changed since it's been filed. Please open a new issue if you feel that there are improvements to be made.
