### ISSUE TITLE
verif in DM shouldn't try to verify using DMs with >2 members

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#12987]
it's very confusing to see e2e verifications end up in DMs with >2 people. but currently apparently we support that. we should only ever use 1:1 DMs (until canonical DMs are a thing)

**Comment by t3chguy** [comment]
A DM with bots is perfectly valid though so this might be hard to solve pre-canonical DMs

**Comment by unclechu** [comment]
I use few accounts for many DMs, so DMs for me are not technically 1to1s. When I've tried to verify one of my own accounts being in some room it sent a bunch of messages to a random DM with my friend who has nothing to do with verification of my own devices. So that's why I'm strongly upvote this.

**Comment by ShadowJonathan** [comment]
Cannot reproduce, probably fixed, as when i invited and joined another user in a preexisting DM, it created another one to verify in.
