### ISSUE TITLE
clicking on empty space in community filter panel doesn't unselect all communities anymore 

### ISSUE THREAD

**Issue by Jaytie2k7** [vector-im/element-web#12988]
**Description**

When I start up Riot, no communities are selected, which allows me to see all rooms I'm in + all private messages. (no filtering by communty)
After clicking on a community I was able to see all rooms and conversations again by clicking in the empty space under the communities on the left. 

Now when I click on a community, I can only select another one but I'm not able to completely unselect communities.

**Steps to reproduce**
- Start Riot
- select community on the left
- try to unselect it

#9858 doesn't work

![Unbenannt](https://user-images.githubusercontent.com/63009998/78164679-63dc3800-744a-11ea-9ca9-b07d4b46e60a.JPG)

**Version information**

- **Platform**: web (in-browser) or desktop?

both

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
Chrome 80.0.3987.162
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows 10 1909

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows 10 1909

**Comment by t3chguy** [comment]
You can click to toggle communities now

**Comment by t3chguy** [comment]
Indeed the empty-space-to-clear has regressed but you can toggle them nowadays.

![com](https://user-images.githubusercontent.com/2403652/78165398-2cb65880-7443-11ea-9e29-be1b31ebd86f.gif)

**Comment by Jaytie2k7** [comment]
ah got it. Unselecting via left ctrl works. You can also combine communities. didn't know that! thanks :)

**Comment by t3chguy** [comment]
Hmm, I wasn't using control to unselect, just clicking on a community should toggle it on-off without any modifiers

**Comment by Jaytie2k7** [comment]
You are right, no need to use control. Just clicking the community again, was too obvious for me to find out :p thank you!

**Comment by HansJK** [comment]
We used to be able to just click the community bar in order to get out of the community. But this feature is gone now. I think that feature should come back.

**Comment by t3chguy** [comment]
Yes. That's why this is a *regression*

> Indeed the empty-space-to-clear has regressed
