### ISSUE TITLE
The service worker use too much CPU and RAM

### ISSUE THREAD

**Issue by Jack-Works** [vector-im/element-web#12993]
### Description

![image](https://user-images.githubusercontent.com/5390719/78194091-c0713e80-74ae-11ea-8889-8d3643c88b56.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 83
- **OS**: Windows 10
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
That sure is worrying given that it is empty: https://github.com/vector-im/riot-web/blob/a41484cb35351fbf8e56d8ae35d8b47f24516a61/res/sw.js#L1

**Comment by turt2live** [comment]
Chrome sometimes does this, and no one has figured out why.

**Comment by Jack-Works** [comment]
Maybe should report it to chrome team

**Comment by dbkr** [comment]
Do we have any concrete repro steps that will get it into this state?

**Comment by Jack-Works** [comment]
Hmm, I can't reproduce that now. Maybe a random problem.

**Comment by jryans** [comment]
Seems like this has gone away now...? Or if not, I am not really sure what Element can do...

Anyway, if it is still happening, we can reopen or track a fresh issue.
