### ISSUE TITLE
Revamp "compact timeline" mode

### ISSUE THREAD

**Issue by Fnux** [vector-im/element-web#12998]
Hello there,

I'm currently looking at what can be done to improve the current compact timeline layout style. What I have in mind would perhaps remove avatars to gain space / change a bit the structure instead of only applying CSS. It should help with:

  * #6982
  * #11051
  * #11185
  * #4403

I will use this issue to keep track of my work.

**Comment by robintown** [comment]
Closing this as the author's PR has gone stale
