### ISSUE TITLE
Re-clicking on email validation link now breaks with ugly error page

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#13002]
Synapse now deletes 3pid validation sessions once they've been checked (https://github.com/matrix-org/synapse/blob/b98971e8a437eb3903506eadbefdf6cb2e0853d6/synapse/handlers/ui_auth/checkers.py#L184) so if you click on an email validation link again you get dumped into an unstyled page from synapse telling you the validation failed because of an unknown session_id.

![Screenshot from 2021-10-06 10-19-22](https://user-images.githubusercontent.com/51663/136175628-9dd453a9-ba2c-429e-9414-31debb803dd2.png)

Previously this took the user straight into their account again, for as long as the validation session remained valid. This is quite nice from a UX perspective but does offer a way into your account if the validation secret is somehow compromised.

Not entirely clear what the correct thing to do here is, but it should probably not be an unstyled error page.

**Comment by t3chguy** [comment]
Moved to https://github.com/matrix-org/synapse/issues/12658
