### ISSUE TITLE
problem establishing (video) calls

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/element-web#13006]
### Description

(Video) call quality was fine once the connection was established. But getting there was a big problem.

It seems that when you are connected the same time with an other client, calls sometimes end up on the wrong device or cannot be seen at all. Is getting worse if you try more often since one of the devices might get stuck trying to enable a connection that does not work.

### Steps to reproduce

In our case we had Riot-web (PC 1) and Riot-Android (Phone 1) running on one side, while running Riot-web (Phone 2) and Nheko (PC 2) on the other side. The goal was to establish a call from PC 1 to Phone 2.

So just try running Riot on phone and PC and you'll run into problems. If still all works fine, try to disconnect and call again.

### Version information

- **Platform**: Browser
- **Browser**: Vivaldi
- **OS**: Windows 19
- **URL**: riot.im/app

**Comment by dbkr** [comment]
Sorry, not sure I understand what's going on here at all. Could you be a bit clearer on what you do and what you see on each device? The device in the version info section is PC 1? What is the phone running riot-web you're trying to call? Can you send bug reports from both the caller and callee side?

**Comment by Flexmaen** [comment]
Yes, PC 1 is the one mentioned here, but we tried to call from both sides by turns. And the whole thing was soo unstable, that I'd be surprised if its not possible to reproduce this by just calling end ending calls randomly with some friends. This happened with other calls and other people as well.
However once the call was established, quality was fine.

**Comment by Flexmaen** [comment]
Thinking about this again, I do not think that this particularly is the fault of riot-web. It rather seems to be a problem of the underlaying protocol or general cross-device parts of the software. The whole handling of calls if more clients are involved, or if you hang up during a try and try to call again does not seem to be very stable. I wonder if this really works flawlessly for you, so if you cannot reproduce this please let me know and I try to narrow it down a little more.

**Comment by Flexmaen** [comment]
Another test today:
Calling from PC to Phone.
1st call: PC transmitted video and audio, the Phone just sent audio.
2nd call: PC transmitted video but no audio, the Phone sent both
The next tries, even after restarting the browser, there was no Audio coming from PC.

I did check the settings to make sure the correct video and audio source was selected.
I did also do a Test-Call with Google Hangouts using the same browser. This worked fine, so the fault does not seem to be on the browsers side.

**Comment by Flexmaen** [comment]
This also is valid for voice calls. They are completely unreliably, maybe 1 of 10 connection attempts will work.

**Comment by moorepants** [comment]
I'm not sure if this is related, but it often takes ~3 attempts to call with the video call button for video and audio to actually be transmitted for our setup.

**Comment by jryans** [comment]
There definitely are some issues with VoIP calls, but we are actively working on improving this area. I think this issue is bit too general too be useful, so I close this one, but please do open new issues and submit debug logs for new problems as they happen.
