### ISSUE TITLE
Wrong Homeserver: Signed Out For security, this session has been signed out. Please sign in again

### ISSUE THREAD

**Issue by the-moog** [vector-im/element-web#13005]
### Description

Unfortunately I can't include a screenshot as the only way I know to trigger this is to do
an upgrade.  Simply restarting the homeserver does not trigger this.
When you are signed out because the homeserver restarts due to an upgrade.
You get a message "Signed Out For security, this session has been signed out. Please sign in again"
The login dialog give you the wrong homeserver, rather than the one the user was prevously logged into, they get https://matrix-client.matrix.org.
People then fail to login as they don't read the dialog properly and change the homeserver.
Often what happens then is people re-register (with the wrong site) and wonder where their rooms have gone.

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce
- Login a desktop client to a private homeserver
- Upgrade the server
- Follow the instructions

Describe how what happens differs from what you expected.
- The user is logged out "For security reasons"
- The user is presented with a login dialog
- The wrong server is used

- **Platform**: desktop?

- **OS**: Windows
- **Version**:
This bug has been in previous versions for as long as I can remember.
- Server <any> but I'm now running 1.12.0
- Client <any> but I'm now running 1.5.15

**Comment by aaronraimist** [comment]
How are you upgrading your server? Users shouldn't be logged out by an upgrade.

**Comment by the-moog** [comment]
apt-get upgrade

**Comment by aaronraimist** [comment]
and it is saving your config? You aren't asking it to like give you a fresh config or anything right?

**Comment by the-moog** [comment]
Annoyingly the Ubuntu Xenial package destroys the config file so you have to preserve it before the upgrade and restore it afterwards.

**Comment by aaronraimist** [comment]
Hmm that definitely shouldn't be happening. May want to raise an issue on https://github.com/matrix-org/synapse/issues.

This does sound like a good feature request though to prefill the server info when the server logs you out, though hopefully that is pretty rare.

**Comment by t3chguy** [comment]
It is intentional that when you get logged out everything gets wiped, including the memory of what server you were once logged into.

**Comment by the-moog** [comment]
https://github.com/matrix-org/synapse/issues/7222

**Comment by the-moog** [comment]
> This does sound like a good feature request though to prefill the server info when the server logs you out, though hopefully that is pretty rare.

I would say that should be the default behavour as anything else complicates things for users.

**Comment by richvdh** [comment]
I'm having a hard time understanding what the issue is here. Obviously it's intentional that if the server logs you out we say so.

It sounds like the complaint was that synapse logs you out on upgrade - but that shouldn't be happening, and would be a Synapse issue if it was?

I feel like we should close this unless there's something I'm missing.
