### ISSUE TITLE
Clicking on your own untrusted device in the right panel gives a confusing dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13013]
![image](https://user-images.githubusercontent.com/1190097/78290478-0646fa80-74e1-11ea-9d29-5cfff8cf94c8.png)

Up to this point I've been presented with buttons like 'verify with emoji' and 'continue', but this dialog has an OK button (which dismisses the dialog) and a 'manually verify' button. The verify button feels like a cancel button or otherwise not an option I want (I'm expecting to see base64 strings of keys and comparing them), but it in fact starts emoji verification. So instead I click 'OK' and nothing happens, but I would expect the verification to begin given the dialog is telling me to do so.

This dialog probably makes a bit more sense when its applied to the context of other users, but when I'm verifying myself I would expect to be able to just mash buttons in the dialog without having to read too much text.

**Comment by turt2live** [comment]
cc @vector-im/design

**Comment by jryans** [comment]
For the moment, I'll consider this UX polish for after release, but agreed it's a bit odd.

**Comment by kittykat** [comment]
I'm going to close this issue for now as this has been redesigned, please open a new issue for further improvements
