### ISSUE TITLE
BigBlueButton support for conferencing 

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#13022]
Would it be possible to integrate [BigBlueButton](https://docs.bigbluebutton.org/dev/api.html) as was also done with [Jitsi](https://matrix.org/blog/2017/08/23/introducing-matrix-widgets)?

**Comment by t3chguy** [comment]
Jitsi is far easier to integrate as it allows iframing (which is what Widgets are)
BigBlueButton has framing options set to same-origin only:
![image](https://user-images.githubusercontent.com/2403652/78365890-a2dbcc00-75b7-11ea-87ec-5086b315d04b.png)

**Comment by fooness** [comment]
Could this be changed, if self-hosting BigBlueButton?

**Comment by t3chguy** [comment]
I'm not familiar with BigBlueButton but yes you could always specify a different X-Frame-Options via a reverse proxy (e.g Nginx) if they don't support changing it at the application level

**Comment by anoadragon453** [comment]
BigBlueButton support has been implemented in both Modular and Dimension (though the latter [still needs merging](https://github.com/turt2live/matrix-dimension/pull/367)). Embedding does indeed require a slight change as @t3chguy mentioned. It can either be done at the reverse proxy level, or doing so in the ruby code itself as described here: https://github.com/bigbluebutton/greenlight/issues/873#issuecomment-652510142

I think this issue can now be closed :slightly_smiling_face:

**Comment by jryans** [comment]
Thanks @anoadragon453, I agree that work seems to resolve this issue. 😄

**Comment by fooness** [comment]
@jryans Could we please re-open this conversation?

> […] This conversation probably belongs in an issue on the Element-web repo, as that would be where a non-integration manager based approach would need to be made. Feel free to create one for a local, jitsi-style iframe BBB widget :)

_Originally posted by @anoadragon453 in https://github.com/turt2live/matrix-dimension/pull/367#issuecomment-675528102_

It would be interesting what would need to be made to not only use BBB in one single room, but basically provide the same functionality as for the jitsi widget which keeps the connection even when switching rooms.

**Comment by anoadragon453** [comment]
@fooness I'd probably recommend a new issue that's specifically for a local BBB widget ala. jitsi. This issue seems to just be for a BBB widget in general, which is what we got with the integration manager solution.

**Comment by t3chguy** [comment]
That's not related to it being local. Widgets can request the persistent capability `m.always_on_screen`

**Comment by fooness** [comment]
I’m not sure I can fully grasp these technical details.

@t3chguy How would some custom widget request this persistent capability? For this the content of the custom widget itself would probably have to be modified?

I’m not completely sure how jitsi is integrated into Element. There’s the `jitsi.html` file in the root of element-web which itself references some javascript files. Would something like this need to be done to be able to use BBB properly (i.e. like jitsi) inside of element? 🤔

Once I kind of grasp how things work together here, I could open a new issue (if that would be okay for everyone in here).

**Comment by t3chguy** [comment]
Widgets communicate with Element using the postMessage API, they would have to request that capability over that API.
The widget would *not* have to be made "local" like the jitsi.html you found.

**Comment by t3chguy** [comment]
> I could open a new issue (if that would be okay for everyone in here).

The issue would have to be with the BBB widget itself, not on this repo.

**Comment by anoadragon453** [comment]
Element currently only allows Jitsi widgets to request this capability. I've created an issue about this here: https://github.com/vector-im/element-web/issues/15001
