### ISSUE TITLE
Stronger wording in warning for signup without email

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#13024]
**Is your suggestion related to a problem? Please describe.**
Too many people emailing support asking to reset their password and don't have an email attached to their account. Cannot verify their identity so will not reset the password. They loose access to their account forever.

**Describe the solution you'd like**
When signing up without providing an email address there is a warning popping up saying `Warning! If you don't specify an email address, you won't be able to reset your password. Are you sure?`
This should be worded stronger. Add something like `If you forget your password you will loose access to your account. Support will never reset passwords.`

Should likely be actioned on all platforms

**Comment by t3chguy** [comment]
> If you forget your password you will loose access to your account. Support will never reset passwords.

For LDAP backed instances this may be very very wrong.

**Comment by Twi1ightSparkle** [comment]
I was told to create this issue after asking specifcally for matrix.org internally

**Comment by t3chguy** [comment]
Am just leaving it there are my view on it for the conversation which needs to take place. Not as a rejection of your proposal

**Comment by Twi1ightSparkle** [comment]
👍make sense

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/9883
