### ISSUE TITLE
Community icons are not centered in the left left sidebar

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#13037]
![image](https://user-images.githubusercontent.com/1342360/78511221-e179ae00-7792-11ea-937d-2830fdd66e86.png)

### Description

The community icons are slightly left-offset in the sidebar. I imagine this is due to badges being on the top right of community icons and thus everything is centered if a badge is in place.

But oftentimes a badge is not in place, and the icons are off-center. I think it'd make more sense if icons themselves were centered. This may also save a few pixel's width for the size of the sidebar.

### Version information

- **Platform**: web
- **Browser**: Firefox nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
why did you have to point this out, now I can't unsee it >:(

**Comment by anoadragon453** [comment]
Sounds like better motivation to fix it :D

**Comment by anoadragon453** [comment]
Actually, it might be due to the scrollbar:

![image](https://user-images.githubusercontent.com/1342360/78806819-22eca200-79bb-11ea-8543-043d273fc1ce.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/78977869-c6030000-7b10-11ea-9813-100715b402e3.png)
![image](https://user-images.githubusercontent.com/2403652/78977943-e3d06500-7b10-11ea-95db-5ce9f23e043a.png)
![image](https://user-images.githubusercontent.com/2403652/78977903-d4e9b280-7b10-11ea-8295-e4b5608399cb.png)


I tried in Chrome and Firefox on Windows and can't see it D:

**Comment by anoadragon453** [comment]
Huh, well I still have it here:

![image](https://user-images.githubusercontent.com/1342360/79132871-f6fa6380-7da2-11ea-8933-b6afa587eec2.png)

Maybe get some notifications in your groups?

**Comment by SimonBrandner** [comment]
Spaces are now in beta
