### ISSUE TITLE
Inviting by mxid in the new invite dialog is very unreliable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13064]
It fails to autocomplete the mxid to a valid pill which you can select (and the fact you have to click on the autocomplete option at all to actually select it is painful).  You end up having to delete & re-add letters to make it actually 'take'.

https://youtu.be/dDddKmdLEdg?t=999 shows this happening live.

**Comment by turt2live** [comment]
This feels like it might have gotten stuck doing a large number of profile requests to make that pill. Should probably debounce a bit stronger and just put the mxid into the suggestions while the profile resolves.

**Comment by ara4n** [comment]
worth noting this was (obviously) on a virgin HS which was doing absolutely nothing else.

**Comment by turt2live** [comment]
Browsers often refuse to do more than about 15-20 requests concurrently, and I can believe the code broke to send a flood of profile requests.

**Comment by dbkr** [comment]
Looks like maybe a case of not getting the requesting logic right for as-you-type searching, which is a surprisingly subtle art form. On wondering if someone has written a library for this, it looks like https://www.npmjs.com/package/autocomplete.js may be worth a look.

**Comment by turt2live** [comment]
For clarity, it took a full 20-30 seconds for the UI to transition from this:
![image](https://user-images.githubusercontent.com/1190097/167232093-e12edc29-4606-4eaa-b72a-ac07ac9a1fa3.png)

to this:
![image](https://user-images.githubusercontent.com/1190097/167232096-572816a9-a3c9-4c27-9acc-07722b6c5d24.png)

**Comment by t3chguy** [comment]
It is now intentional that the MXID pill doesn't come up when the profile call fails, but you no longer need the pill, clicking invite works.
