### ISSUE TITLE
The self-cross-sign modal should not be cancellable by hitting the background

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13067]
After hitting the 'review' button on the 'new login' toast, @BillCarsonFr was managing to hit the bg and cancel the modal, with no easy way to resume the flow.  Perhaps we should disable modal-cancelling-by-clicking-in-the-bg for scenarios like this?

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/6109
