### ISSUE TITLE
Write up on how I'd like state management to look

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13085]
As someone quite new to the codebase (ie naïve of its full horrors), I'm gonna write up my ideal world notion of what state should look like.  This will, no doubt, not be achievable, but it's a good place to start the discussion from.

**Comment by foldleft** [comment]
got a document ready to go but I won't paste it in public just yet

**Comment by robintown** [comment]
Closing since this was a personal to-do item that is no longer relevant
