### ISSUE TITLE
The field allowing to edit the displayname in the parameters displays the userId when you're not part of any room

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#13093]
![Screenshot_2020-04-09 Riot(2)](https://user-images.githubusercontent.com/57274151/78883875-5fbba600-7a5a-11ea-8010-b78faaa94677.png)

### Description

The field allowing to edit the displayname in the parameters displays the userId when you're not part of any room

### Steps to reproduce

- not be a member of any salon
- open the parameter window and see that the field for editing the displayname contains the userId independently of the real displayname
- edit the displayname, close then reopen the parameters window to see that it's always the iserId that is displayed in the field (but the modification is effective on the server side)

### Version information

https://riot.im/app/version: 1.5.15

**Comment by t3chguy** [comment]
This is fundamentally caused by the same as https://github.com/vector-im/riot-web/issues/9551

**Comment by c-cal** [comment]
indeed, strange that there is a per-room displayname / avatars while apparently the UI doesn't allow to edit it independently of the global profile state.

**Comment by t3chguy** [comment]
There's just no UI for it but there is `/myroomnick` slash command to affect it.
