### ISSUE TITLE
if you're slightly scrolled up (e.g. by <1 line) then sending a message should force-scroll to the bottom

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13090]

**Comment by cpeterso** [comment]
Force-scrolling to the bottom of the room's message backlog when I send a message is what Slack does. That doesn't necessarily mean it's the best user experience 😁 but it is my personal preference.

**Comment by SeerLite** [comment]
I also miss this a lot and feel it's really unintuitive how it is right now for new users. Maybe it could even be a client setting to make everyone happy?
