### ISSUE TITLE
“Hide profile/room images” settings option …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#13100]
It would be very good to offer an option to “Hide profile/room images”, or, `enable` and `disable` said images via some settings option. Definitely would be good for distractionless mode …

**Comment by aaronraimist** [comment]
Are you talking about the 
- avatars in the room list and the user list
- images posted in rooms
- or the messages in the room saying that someone has changed their profile picture or the room avatar?

**Comment by fooness** [comment]
Avatars in the room list and the user list.

**Comment by aaronraimist** [comment]
This is basically duplicate of https://github.com/vector-im/riot-web/issues/6982 then

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/11900 since the focus seems to be on "Avatars, everywhere."
