### ISSUE TITLE
Community avatar fails to switch context 

### ISSUE THREAD

**Issue by hebrides** [vector-im/element-web#13127]
### Description

On the web app and desktop app, clicking a community avatar on the vertical left select bar fails to switch context to the represented community. (i.e., Avatars do not function like comparable Slack workspace icons.) 

### Steps to reproduce

- Create two or more communities
- Attempt to use left avatar icon to switch community
- Green bar will highlight community
- UI to the right (Rooms view and Room Chat view) does not switch appropriately
- Create a room for green bar highlighted community
- Room may or may not appear in correct community 

![Community-Avatar-UIX-Error-Matrix](https://user-images.githubusercontent.com/7585440/79027921-4f372880-7b4b-11ea-8172-23cae2232bae.gif)

### Version information

Web App: Safari 13.0.0, Chrome 80.0.3987.163 on OSX Mojave 10.14.6
Desktop: Version 1.5.15 (1.5.15) on OSX Mojave 10.14.6

### Suggestions
1. Fix this bug. :)
2. For the create room modal, give user feedback about room community:

![image](https://user-images.githubusercontent.com/7585440/79028583-c1107180-7b4d-11ea-8227-82f7e6882e8c.png)

3. Bonus Fix: The avatar Initials in the selection bar also do not update until a page refresh when updating the community name.

**Comment by t3chguy** [comment]
You can actually select multiple communities (using shift/control), additionally you may not have permissions to add rooms to the communities. 
The add room dialog creates a room which is in **0** communities. After creation you can add it to any number of communities where you have control (yes a room can be in any quantity of communities).

The TagPanel you are referencing in your gif is for filtering the room list, but given a room may be in many communities it may not always work as you expect.

If you click on the options `...` menu and view the community, then look at its room list `#` in the **right** panel are the rooms you think are in the community actually in it?

**Comment by robintown** [comment]
Spaces are now in beta!
