### ISSUE TITLE
Add a tag panel button for rooms-not-in-a-community

### ISSUE THREAD

**Issue by morris-t** [vector-im/element-web#13141]
**Is your suggestion related to a problem? Please describe.**
Currently in Riot web and desktop, there is no explicit part of the UI that indicates to the user where to click, in order to get back to their home page. 

For example if they add a community they can click on the community and a green bar indicates their location.  However, in order to get back to their home they have to click on the community icon again, which removes the green bar from the community icon and displays the home page.

I find this quite jarring from the UX point of view, I also think it makes it harder for the user to conceptualise where they are in the program.

**Describe the solution you'd like**
Ideally I would like an icon added for the home page to be added to the top of the communities sidebar, which would use the green bar to indicate when you are on the home page:

![Riot_Home](https://user-images.githubusercontent.com/20741651/79069940-ed50fd00-7cc9-11ea-99b4-ec88dd6ea1e0.jpg)

I think this would make the program easier to navigate, especially for new users.

**Comment by t3chguy** [comment]
If the riot has a home page configured then there is a button for it:
![image](https://user-images.githubusercontent.com/2403652/79070034-bcbd9300-7cca-11ea-91fa-febef8a83b17.png)

Its `Strona startowa` there

**Comment by morris-t** [comment]
@t3chguy that would be great, how do you configure the home page? I looked through the settings and cant see an option to configure the home page.

**Comment by t3chguy** [comment]
See `embeddedPages.homeUrl` in https://chat.mozilla.org/config.json

**Comment by morris-t** [comment]
I logged into https://chat.mozilla.org/ and had a look at that implementation, unfortunately it seems to have the same issue. 

Maybe I am causing some confusion by calling what I want the home page, maybe I should be referring it to it as a "home sidebar" instead? 

I see what you mean by the home page with the link to view rooms, but that isn't what I was looking for. When clicking on the home icon, I would want the direct messages/rooms sidebar to update to the "home sidebar". 

I created some edited screenshots using the Mozilla instance for reference.

When the user logs in I would like there to see a home icon at the top, which displays the rooms in the "home sidebar" e.g. Mozilla general:

![Home_Selected](https://user-images.githubusercontent.com/20741651/79071364-45403180-7cd3-11ea-9be2-11c24e4d936a.jpg)

I then created a test community on chat.mozilla, when the test community is selected I would like it to look like this:

![Community_Selected](https://user-images.githubusercontent.com/20741651/79071395-6acd3b00-7cd3-11ea-9d80-ae0ebcb4e303.jpg)

When the user has a different community selected, they can then easily get back to their "home sidebar" by clicking on the home icon at the top of the communities sidebar.

**Comment by t3chguy** [comment]
One spanner here is you can select as many/few communities as you want, between 0 and all of them:

![image](https://user-images.githubusercontent.com/2403652/79071794-876a7280-7cd5-11ea-92db-2049da791e6c.png)

**Comment by morris-t** [comment]
Aha I didn't realise, I have never had more than one community. So the communities bar acts more like a filter for the sidebar vs switching between different communities. 

I guess in this instance having an Icon for the default community of your home server at the top of the list might still be helpful, as it would let you filter the default rooms and direct messages?

I guess the key issue for more me as a new user, is I don't understand why the default community of your home server is treated differently than other communities?

**Comment by t3chguy** [comment]
There is *no default community of your home server*

Rooms by default are in 0 communities, they can be added to any quantity (multiple) communities.

**Comment by morris-t** [comment]
Oh ok, in that case I guess what I would like is an icon in the communities sidebar that would allow you to filter the rooms that haven't been assigned to a community, in the same context as the buttons that allow you to filter rooms that have been assigned to communities.

**Comment by t3chguy** [comment]
Spaces accomplished this
