### ISSUE TITLE
Can only re-order communities that are initially on screen (not those that are only visible once you scroll down)

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#13144]
### Description

![Peek 2020-04-12 20-12](https://user-images.githubusercontent.com/1342360/79077480-01acee00-7cfa-11ea-8649-fc5bbad27676.gif)

Communities that you don't have to scroll down to see do not move out of the way when you try to move communities around. Minimizing your screen zoom such that more appear on screen allow those new communities that now show to move around, but again if you scroll down those that are initially hidden do not move.

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Manjaro Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/element-web/issues/14508
