### ISSUE TITLE
'Verify this session' toast is shown after skipping complete security when I am logged out of all other devices

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#13157]
So there is no other device to verify with. I would have expected to see a setup encryption toast rather.

**Comment by bwindels** [comment]
Repro steps would be:
 - delete all other sessions for a given user
 - logout
 - log back in, skipping complete security
 - refresh

Now you see a verify this session toast, while there is no other device to verify with.

**Comment by bwindels** [comment]
We're just not checking if there is another device to verify with when there are already cross-signing keys uploaded for our user.

If there isn't another device to verify with, we should show the setup encryption toast and reset the cross-signing keys, probably showing a warning when resetting. `phase:4` seems adequate.

**Comment by kittykat** [comment]
I believe this is fixed now as we were unable to reproduce so I will close the issue. Please re-open if you still get the problem.
