### ISSUE TITLE
if you log out too quickly after sending an e2ee message, your key doesn't get backed up

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#13151]
possibly also happens on incoming sessions.  `_backupPendingKeys` should be triggered on logout.

**Comment by jryans** [comment]
Seems like something we should look into, but not really specific to the core of cross-signing work, so could come after release.

**Comment by kittykat** [comment]
@jryans @uhoreg Can either of you still reproduce this? We couldn't during the community testing session, so this issue is a candidate for closing.

**Comment by uhoreg** [comment]
As far as I can tell from reading the code, it hasn't been fixed yet.
