### ISSUE TITLE
Typing animation maxes out CPU

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1315]
@aviraldg i've had to comment out https://github.com/vector-im/vector-web/pull/1292 for now, as it maxes out a full core on Chrome on my MBP whilst the animation is playing.  Tightlooping the CPU for 30s every time someone types for something purely cosmetic is unfortunately not an option.  The animation performance was also weirdly bad, despite the maxed out CPU - unsure why.

Suggestions for a fix would be very welcome, as I don't know off the top of my head how to stop CSS animations going wild and eating all the available CPU....

**Comment by aviraldg** [comment]
@ara4n I don't have an OS X machine handy to test, and it seems to work fine on Chrome or Firefox, but https://github.com/aviraldg/vector-web/commit/ad22e24fb8b15668d8ef532314fdc393fbebcfad might fix it. Could you give it a try?

**Comment by gsouquet** [comment]
Closing as there are no animations when typing anymore
And after scanning through the code the `bounce` animation is nowhere to be found
