### ISSUE TITLE
Space and other word breaks should pillify entries in the dialog

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13168]
If you enter an email address or a random mxid, you have to click on a 'suggestion' in the new invite UI to actually pillify it and invite it (assuming that the pill shows up at all, which it doesn't always thanks to https://github.com/vector-im/riot-web/issues/13064).

This is very confusing though because it implies that nonexistent users (e.g. rando emails or typoed mxids) might actually exist - hence them showing up as 'suggestions'.  Instead, i'd expect that hitting space or comma or tab or something would pillify and the ID wouldn't show up in 'suggestions' at all.

N.B. that this is *not* a question of accessibility, but the fact the UI is just very confusing still.

**Comment by arcalinea** [comment]
Was confused by this, thought the suggestion for an invalid address I typed meant it existed. The 'suggestion' also disappears sometimes before you can click it, making the invite process a frustrating experience. 

Attaching a picture to illustrate the incorrect address suggestion.
![riot-glitch](https://user-images.githubusercontent.com/12245008/79264261-24015180-7e49-11ea-81dd-ce6ed609991e.jpg)
