### ISSUE TITLE
Build and release Electron app for Windows 32-bit

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#13175]
Splitting this out from https://github.com/vector-im/riot-web/issues/12707, as we're leaving Windows 32-bit for after release.

This still depends on https://github.com/neon-bindings/neon/pull/491 or taking some other approach.

**Comment by ara4n** [comment]
Looks like https://github.com/neon-bindings/neon/pull/491 has merged now

**Comment by dm-msk** [comment]
When will the x32 client be released?

**Comment by dm-msk** [comment]
> When will the x32 client be released?

If somebody can hear me, answer me please

**Comment by jryans** [comment]
At the moment, there is no specific timeline for Windows 32-bit. We are waiting to see if demand warrants the work involved to rework build systems to provide them again.

**Comment by dm-msk** [comment]
Hello. We have old RiotIM client for x32 PCs. After last upgrade we got an error "device_keys values must be a list of strings" during send of message. Can we have temporary workaroud, may be some options in client or server, while we'll migrating to x64 PCs?

**Comment by t3chguy** [comment]
Seshat already updated to neon^0.8 so should be completely free of this issue
https://github.com/matrix-org/seshat/blob/6b53fe86318552a12c916c47fba3f47dc294d1b1/seshat-node/native/Cargo.lock#L952
