### ISSUE TITLE
Debugging wishlist meta-issue

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13177]
* Log lines should indicate the file/function they came from
* The flow of user activity should be easily followed –– and parsed
* We should try to preserve context –– logging the traceback as well as an error if we use `console.error`

**Comment by t3chguy** [comment]
> Log lines should indicate the file/function they came from


This is possible if you Blackbox rageshake.js in devtools

**Comment by Johennes** [comment]
Closing as this hasn't received a lot of traction in the past three years.
