### ISSUE TITLE
If you enter incorrect SSSS passphrase to auth at "Complete security" it silently fails

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13180]
You get a plausible error in the console:

 Error: "Error decrypting secret m.cross_signing.master: bad MAC"
    decryptBrowser aes.js:184

...but it returns you back to the same dialog with no explanation:

<img width="638" alt="Screenshot 2020-04-15 at 19 45 45" src="https://user-images.githubusercontent.com/1294269/79376853-ae81a800-7f52-11ea-9414-46d966fcc414.png">

**Comment by jryans** [comment]
Seems not ideal, but could be improved post-release.

**Comment by kittykat** [comment]
I'm going to close this issue for now as the UI has changed sufficiently that this is not reproducible. Please open a new bug for further improvements, if needed.
