### ISSUE TITLE
"Unverified login" toaster doesn't disappear immediately after reviewing new login

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13181]
After self-signing new login toaster for "unverified login, was this you?" hung around for 5-10s before spontaneously disappearing

**Comment by jryans** [comment]
I think the issue is that the toaster waits around for remote echo effectively. We'd need to add some form of local echo / optimistically clear it after completing verification.

**Comment by kittykat** [comment]
We cannot reproduce this and there have been many changes to the area so I will close this issue for now. Please reopen if you continue to experience the problem.
