### ISSUE TITLE
After bootstrapping cross-signing, you're prompted to verify yourself.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13203]
* Log into riot 1.6 on a pre-cross-signing account
 * It prompts you to bootstrap via popup
 * After having bootstrapped, it tells you to 'verify your session' (sometimes this then disappears) - surely it should know to trust this session.

**Comment by jryans** [comment]
This sounds similar to https://github.com/vector-im/riot-web/issues/13181, but for the current device case. I assume the toast is waiting for remote echo of some data, so we'd need to resolve toasts locally / optimistically in some way to avoid this.
