### ISSUE TITLE
Failed verification prompts the user with "Got it!" making it sound like it succeeded

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13219]
When verification fails, or is cancelled, we get a cheery "Got it!" button on the error state.  This is a bit confusing, as "Got it!" sounds pretty positive given the bad news...

**Comment by kittykat** [comment]
I'm going to close this issue for now as the UI has changed since it's been filed and we cannot reproduce it. Please open a new issue if you feel that there are improvements to be made.
