### ISSUE TITLE
Failed setting up keys - Unable to set up secret storage

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13249]
Rick couldn't bootstrap.

**Comment by dbkr** [comment]
What I see here is a verification request that gets cancelled from the other side, but that doesn't sounds like what you're reporting? Rick: what were you doing when yo got the error and can you rageshake from AKYTREWRUB please?

**Comment by schildbach** [comment]
I've got this exact same issue from riot-desktop 1.6.0 on MacOS. What is the equivalent of "rageshake" on MacOS?

**Comment by t3chguy** [comment]
Settings > Help & About > Submit debug logs

**Comment by schildbach** [comment]
On Riot-Desktop, that is still in the initial setup. There is no UI except "Retry" and "Cancel".

**Comment by t3chguy** [comment]
You can open devtools (Cmd Shift I) and type `mxSendRageshake("Message goes here", true);` into the console to send a rageshake too

**Comment by schildbach** [comment]
Cmd Shift I does nothing. Tried both left and right. (I'm new to Macs)

**Comment by t3chguy** [comment]
that's I as in "I am" not `l` (L) btw

**Comment by schildbach** [comment]
Yes I tried i.

**Comment by schildbach** [comment]
Developer Tools is Alt-Cmd-I we just found out in the menu. Is that what you mean?

**Comment by t3chguy** [comment]
Yes, my bad, am not a Mac user. Sorry

**Comment by schildbach** [comment]
Ok we just sent a report - message is "Unable to set up secret storage - to t3chguy".

**Comment by t3chguy** [comment]
`ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/keys/device_signing/upload`
looks like a matrix.org issue/partial outage :(

**Comment by schildbach** [comment]
Ok so we'll retry later. Thanks!

**Comment by Neikius** [comment]
> `ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/unstable/keys/device_signing/upload`
> looks like a matrix.org issue/partial outage :( probably a timeout

Exact same problem, linux, 17 hours later. Does not seem to make sense that outage is taking that long eh?

**Comment by schildbach** [comment]
After many retries each failing the same way, we cancelled the encryption setup and restarted it via the Settings → Bootstrap cross signing dialog. We had to reenter the various passphrases again, got a new (different) recovery key to write down, and then the setup succeeded without any retry.

Which makes me think this wasn't really a timeout problem.

**Comment by Ezwen** [comment]
I encounter a similar problem on an account, using element-web 1.7.8 on Firefox, and I get these logs:

```
Starting load of AsyncWrapper for modal 2 rageshake.js:65:16
XHRGEThttps://myhomeserver.org/_matrix/client/unstable/room_keys/version
[HTTP/2 404 Not Found 25ms]

Key backup is absent or missing required data rageshake.js:65:16
XHRPOSThttps://myhomeserver.org/_matrix/client/unstable/keys/device_signing/upload
[HTTP/2 401 Unauthorized 49ms]

Forcing cross-signing and secret storage reset rageshake.js:65:16
Bootstrapping Secure Secret Storage rageshake.js:65:16
Secret storage does not exist, creating new storage key rageshake.js:65:16
Creating new message key backup version rageshake.js:65:16
Error bootstrapping secret storage Error: Attempted to sign with master key but no such key present
    signObject CrossSigning.js:435
    bootstrapSecretStorage index.js:793
    n client.js:1095
    f CreateSecretStorageDialog.js:285
    f CreateSecretStorageDialog.js:368
    s index.js:91
    p index.js:124
    _ index.js:146
    _ index.js:9
    React 5
    q index.js:77
    React 2
    unstable_runWithPriority scheduler.production.min.js:13
    React 3
rageshake.js:65:16
```

How to solve ` Attempted to sign with master key but no such key present` ? Can I reobtain a master key?

**Comment by Ezwen** [comment]
Here is the rageshake: 
[rageshake.zip](https://github.com/vector-im/element-web/files/5334334/rageshake.zip)

**Comment by jryans** [comment]
I think this issue is lacking details we need to move forward. For anyone affected by something similar, please file a new issue.
