### ISSUE TITLE
room list in community page is cut off

### ISSUE THREAD

**Issue by lub** [vector-im/element-web#13257]
### Description

It seems the last room isn't completely displayed:
![image](https://user-images.githubusercontent.com/1029578/79640305-2b01ca00-8191-11ea-9f3a-6cc9cefafc1e.png)
![image](https://user-images.githubusercontent.com/1029578/79640343-67352a80-8191-11ea-96f7-ce20f87a0b4e.png)

### Steps to reproduce

- open a community with enough rooms to force scrolling (or use a smaller window I guess)
- scroll to the bottom
- the last room lacks description, alias and member count

I'd expect the last room completely displayed just like the others.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.15 (develop @ 19130dc70550895518df7e60ce87f40e205061fd)

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
