### ISSUE TITLE
Key backup should have an option to use account passphrase as passphrase

### ISSUE THREAD

**Issue by 35609902357** [vector-im/element-web#13263]
For ease of use by non-technical users, who are easily scared away, and because account passphrases should be mandatorily safe (matrix-org/synapse#5112, [MSC2000](https://github.com/matrix-org/matrix-doc/pull/2000), matrix-org/synapse#5214 and matrix-org/synapse#7118), this option would be the best compromise for those users who are overwhelmed by simple choices. This will give them the experience of "easy to use" applications such as Telegram. This will allow [this option](https://github.com/vector-im/riot-web/issues/8751#issuecomment-615835543).

**Comment by jryans** [comment]
What is an "account passphrase"? Do you mean your account password? Sorry to be pedantic, but there many variations of password and passphrase floating around, so it's important to agree on wording first. 😄

**Comment by 35609902357** [comment]
Yes, I intended passphrase as a more complex password. I meant the password you use for the account itself.

**Comment by cedricvanrompay** [comment]
Note that the homeserver sees the account password *in plaintext* every time the user logs in.

**Comment by richvdh** [comment]
using the account password for the secure backup passphrase would be a very bad idea.
