### ISSUE TITLE
Can't accept call when Riot runs on multiple devices

### ISSUE THREAD

**Issue by mxmlnkn** [vector-im/element-web#13277]
### Description

I have the Riot application (non-web) running on my PC, notebook and smartphone. When I receive a call all three devices begin to ring. When I accept the call on one of the devices, e.g., PC, the other devices still keep ringing and the voice call does not correctly initiate. Declining the call on the other devices also does not seem to help either.

### Steps to reproduce

- Open Riot desktop on on multiple devices with the same account
- Get someone to voice call you
- Accepting the call on one device should initiate the call like expected and maybe end the ringing on the other devices. Neither does accepting the call on one device initiate a working voice call nor does the ringing on the other devices stop.

Logs being sent: no

### Version information

PC
 - Ubuntu 19.10
 - desktop
 - riot-web version: 1.5.13
 - olm version: 3.1.3

Notebook:
 - Ubuntu 18.04
 - desktop
 - riot-web version: 1.5.12
 - olm version: 3.1.3

Smartphone:
 - App
 - Version 0.9.10
 - olm version: 3.1.2

**Comment by SimonBrandner** [comment]
@mxmlnkn, is this still a problem?

**Comment by mxmlnkn** [comment]
I think it worked last time. I mean to say, at least it didn't keep on ringing on the other device. However, in general voice calls still seem unusable to me. There always is one or another issue. Last time, it connected but one of us couldn't be heard. It's not urgent to me anymore because the modus operandi changed to using jitsi, even for 1-on-1 sessions.

**Comment by jryans** [comment]
Let's assume this specific issue is fixed then. In general, VoIP is actively being improved, so I expect things should continue to get better, but also please file specific issues as they occur with debug logs so they can be investigated.
