### ISSUE TITLE
Long strings break the Create DM/invite dialog

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#13278]
<img width="994" alt="Screenshot 2020-04-20 at 11 26 14" src="https://user-images.githubusercontent.com/4626865/79742170-55bb6200-82fa-11ea-8077-536ef8c76057.png">

Horizontal scroll should always be disabled. To fix, we should consider:

- Implementing some kind of max char count on the strings (clipping with ellipsis), considering the security trade-off
- Just letting the strings span multiple lines

**Comment by turt2live** [comment]
tagging as needs-design to answer the question of what to do

**Comment by turt2live** [comment]
I believe the layout here has been improved over the years. If this is untrue, please open a new issue with fresh information.
