### ISSUE TITLE
Performance issue in event decryption

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13284]
User reports decrypting messages is extremely slow on startup, taking 5 minutes.

Logs are extremely full of messages saying that messages are already in the middle of being decrypted and will be retried.

Either a performance issue in the decryption, or some kind of tight loop, I think.

https://github.com/matrix-org/riot-web-rageshakes/issues/2637

**Comment by ara4n** [comment]
I've been seeing this pretty constantly on launch over the last 3-4 days.  (The user c'est moi)

**Comment by gsouquet** [comment]
Closing as it is a duplicate of vector-im/element-web#13266
