### ISSUE TITLE
Login asks you to verify on one of your other devices when there are none

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13289]
If you're signing in to your account after having logged out everywhere it shouldn't ask you to use those devices. Gives a bit of a scare as it implies there's a session out there somewhere.

**Comment by jryans** [comment]
Related to https://github.com/vector-im/riot-web/issues/13281, https://github.com/vector-im/riot-web/issues/13237. I think this variant could wait until post-release, but good to track.
