### ISSUE TITLE
Editing the session Public Name with the linux Desktop Client

### ISSUE THREAD

**Issue by banjo8675309** [vector-im/element-web#13302]
### Description

Renaming the Public Name is not intuitive

### Steps to reproduce

It is not intuitive that you can click on the Public Name in order to rename it.  Also, it will only save your changes if you press enter (clicking off of the edit box will counter-intuitively keep your changes in the text box, but yet not propagate them or save them permanently)
Describe how what happens differs from what you expected.
Under Settings -> Privacy and Security -> Sessions -> Public Name 

![image](https://user-images.githubusercontent.com/64051199/79814996-9db7a480-834d-11ea-8c70-41f63fabc0a3.png)

Possible solutions are to add an edit and save icon (much as used when editing your own messages)

**Comment by immanuelfodor** [comment]
Thank you for pointing out that the name is clickable! I haven't known how to rename the sessions until now, it's a life saver.

**Comment by aaronraimist** [comment]
Related: #7808

**Comment by uhoreg** [comment]
I think this is fixed by the new design, which has "Rename" buttons next to the devices.
