### ISSUE TITLE
Spellcheck language switcher

### ISSUE THREAD

**Issue by geckolinux** [vector-im/element-web#13317]
Hi there, would it be possible to add an item to the spellcheck context menu to change to a different language? This is important for multilingual users. Bonus points if it remembers the language for each room and/or user. Thanks!

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/7773

**Comment by geckolinux** [comment]
Hi again, wouldn't multi-language spellchecking come along "for free" by virtue of being an Electron app? Chromium for example has this:

![Screenshot_2020-10-12_08-20-49](https://user-images.githubusercontent.com/2692138/95751437-3b888e00-0c64-11eb-99e7-4c347625f7b7.png)

**Comment by t3chguy** [comment]
Yes, but the UI to manage it does not.

**Comment by SimonBrandner** [comment]
I've been looking into adding multi-language `spell-check` recently. This seems to be related to this issue.

### UI

I would go for something similar to the way email addresses and phone numbers are handled.

### Electron

Electron already seems to support [this](https://github.com/vector-im/element-desktop/blob/239bab38cabcb5589ce63751a0c1f7fcc6b09b8d/src/electron-main.js#L389-L432). So does [the function](https://github.com/vector-im/element-web/blob/301ea6a5f30bc3acf775500c29be9b86cc89e169/src/vector/platform/ElectronPlatform.tsx#L492-L497) in `element-web` which talks to Electron through `IPC` and sets the language for the spell checker. Thus implementing this in the desktop app shouldn't be problematic.

### Browser

I don't really know how to implement this in the browser. Does anyone know?

### Implementation

I could probably implement this, at least on the desktop. I would go about in the following way:

+ Add UI as I described before. The UI would include a comment saying that it is currently supported only on the desktop. Even better would be hiding this option in the browser. Though I don't know how to check if the app is running in Electron. I'll take a look.
+ Add setting for storing a list of languages to spell-check. If it would be empty the spell check could be disabled to satisfy #13543.
+ Add a special case for setting spell-check language in [`electron-main.js`](https://github.com/vector-im/element-desktop/blob/develop/src/electron-main.js)

This would solve this problem for the desktop app and leave space for later implementation in the browser.

Should I attempt to implement this? Even if it was only for the Desktop, for now?

**Comment by geckolinux** [comment]
Thanks a lot @SimonBrandner , I'd really appreciate any implementation, even if only for the Desktop.

> I don't really know how to implement this in the browser. Does anyone know?

This might be a bit of a long stretch, but the TinyMCE WYSIWYG editor has an option to allow the browser's native right-click context menu, which includes the browser's native spellchecker:

https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/

Maybe you could have a look at their JS code for that? Sorry if this is a totally irrelevant suggestion.

**Comment by SimonBrandner** [comment]
> browser's native right-click context menu, which includes the browser's native spellchecker

@geckolinux I think I failed to explain what I wanted to do. 

The right-click menu seems to work fine for me in the browser (at least in Firefox). 

What I want to implement is a spell-checker that will check multiple languages at once. Meaning it wouldn't mark any part of `Hello world; Hola Mundo` incorrect if I selected that I want it to check for English and Spanish. 

I find this much more friendly because I sometimes use multiple languages in one message and even if I didn't the right-click menu is just not very elegant, at least not from my perspective. This also eliminates the need for having per-room spell-check language.

`Electron` allows for:

```js
mainWindow.webContents.session.setSpellCheckerLanguages(languages)
``` 

where `languages` are an array. The thing is I don't know how to do this in the browser. I don't even know if it is possible.

**Comment by SimonBrandner** [comment]
I made a [draft PR](https://github.com/matrix-org/matrix-react-sdk/pull/5452).

**Comment by SimonBrandner** [comment]
The [PR](https://github.com/matrix-org/matrix-react-sdk/pull/5452) is ready

**Comment by geckolinux** [comment]
Nice! Thank you very much!
