### ISSUE TITLE
rageshake/react-devtools interaction

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13323]
It looks like react devtools also overwrites the console. I have been deliberately throwing errors (from a bundle) and they're not making it into the rageshake logs.

Update: this only seems to happen with the tools open. I think the action here is trying to catch this condition and log it.

**Comment by jryans** [comment]
I would hope that at least they only modify the console when the tools are open...

**Comment by foldleft** [comment]
ah, that's the case

**Comment by turt2live** [comment]
Closing as a development environment issue - this should never happen in production.
