### ISSUE TITLE
The "hopeful" emoji looks sad/distressed

### ISSUE THREAD

**Issue by tredondo** [vector-im/element-web#13334]
![image](https://user-images.githubusercontent.com/10043369/80036458-dcb04a80-8545-11ea-8bf9-09536ae258f0.png)

Desktop 1.5.15.

**Comment by t3chguy** [comment]
This is an upstream issue: https://github.com/milesj/emojibase/blob/31c189b92422ab0fc1625ac5a14585b1aafd5d92/packages/generator/src/resources/shortcodes.ts#L103-L104

**Comment by strixaluco** [comment]
This is in the process of being fixed by https://github.com/milesj/emojibase/pull/64
