### ISSUE TITLE
FTUE: history visibility settings lie in E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13349]
given we can't see history from before you join an E2E room, the history visibility settings should not claim that you can.

**Comment by valkum** [comment]
Just hit this with a room on our homeserver. It seems RiotX handles this differently, as it shows the encrypted events before the invite (without a way to request keys from the senders (would that be even possible?)). Riot-web and desktop just don't show anything. Even non-encrypted previous events (before e2e was activated) are hidden.
May I suggest to show at least some form of banner (like the encryption activated banner in riotX) that informs the user about this fact? Could be a short term solution before much time flies by for reworking the history wording or something else.

**Comment by t3chguy** [comment]
> Even non-encrypted previous events (before e2e was activated) are hidden.

it has no way of knowing they exist, if riot-web/desktop see undecryptable events from before your join then they hide them for a better first time user experience

**Comment by jryans** [comment]
> can't see history from before you join an E2E room

To be a bit more precise (and to verify my own understanding), it's before the point you were invited, not joined, right?

**Comment by t3chguy** [comment]
Yes, my bad, assuming the right join rules;

**Comment by t3chguy** [comment]
Unclear what we want done here, blindly hiding those settings seems wrong. Probably needs better copy for e2ee rooms?

**Comment by jryans** [comment]
In the duplicate issue https://github.com/vector-im/element-web/issues/14889, @lampholder said:

> When you join an encrypted room you don't see the message history.
> This makes sense, because a bunch of UISIs you can never fix is a nice thing to avoid.
> 
> However, it is suprising because:
> 
> * the room settings still say you should have access to old messages
> * joining the room, you have no signal as to whether you're landing in a brand new room or one in which discussion is already in flight
> 
> This last point is probably more important - I find landing in such a room I don't know quite how to behave.

**Comment by avalenn** [comment]
This is even more confusing when you leave the room and then rejoin it.
On element-android I can see the old messages (excepting those posted when I was not in the room which are rightfully marked as impossible to decrypt).
On element-web my history is completely truncated at my last join, even if I would be able to decrypt some of the older messages.

**Comment by jryans** [comment]
We have now [enabled](https://github.com/matrix-org/matrix-react-sdk/pull/5839) key sharing on invite, so I believe the visibility settings now make sense for E2EE rooms.

**Comment by aaronraimist** [comment]
@jryans the "Anyone" option still exists for E2E rooms which is a lie

**Comment by SimonBrandner** [comment]
Maybe a new issue for that specifically might be better?
