### ISSUE TITLE
Desktop seshat search: No results is scrolled out of view

### ISSUE THREAD

**Issue by steef435** [vector-im/element-web#13348]
Steps to reproduce:
1. Open an encrypted chat
2. Search for something that will yield no results
3. The container containing "no results" is scrolled up so that "No results" is not visible in full (alternatively, the results are way too big for no results). See screenshots.

Encrypted chat (seshat search):
![image](https://user-images.githubusercontent.com/1906214/80129155-f928a300-8596-11ea-83e3-f73056ff3759.png)

Compared with (server-side?) search in an unencrypted chat:
![image](https://user-images.githubusercontent.com/1906214/80129301-24ab8d80-8597-11ea-8dda-971d228d2806.png)

I've found the scrollbar behaves weirdly while searching as well, but that's not a big issues since it will behave properly once the results are there.

### Version information
- **Platform**: desktop
- **OS**: Linux (Arch)
- **Version**: v1.6.0-rc.4

**Comment by t3chguy** [comment]
Haven't seen this since, presuming fixed
