### ISSUE TITLE
In an encrypted room search results displayed are much fewer than the number of results the search supposedly yielded

### ISSUE THREAD

**Issue by starcraft66** [vector-im/element-web#13353]
### Description

I've noticed that when searching in encrypted rooms, the actual search results displayed are much fewer than the number of results the search supposedly yielded. If I search for a term and it says "(125 results)", it will only display 10 of them.

I was told this was due to a lack of pagination support.

### Steps to reproduce

* Search for something in an encrypted room.

I searched for reddit links in a room, it yielded 578 results and only rendered 10.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS 10.14
- **Version**: 2020042302

**Comment by turt2live** [comment]
This appears to have been fixed.
