### ISSUE TITLE
xsign / verification: Verifying in a DM requires manually enabling encryption

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-web#13377]
### Description

Verifying a person requires that you turn encryption on in the DM.

### Steps to reproduce

- Have unencrypted DM with person
- click "verify" in profile
- verification request is sent
- verification request is immediately cancelled with no feedback as to why

enabling encryption in the DM and trying again worked. I would expect a prompt to enable encryption if it's needed to do the verification.

### Version information

Riot desktop nightly.

**Comment by dbkr** [comment]
A brief test suggests this is no longer the case.
