### ISSUE TITLE
Accepting an invite by email can result in a wedged room join "IDBDatabase.transaction: Can't start a transaction on a closed database"

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#13371]
To repro:
- invite unregistered user by email to private room
- user accepts invite
- user registers with email address, sending verification link to email
- user clicks link in verif email, opening a second tab
- first tab prompts for IS t's and c's - accept these
- first tab reminds you that the invite was sent to an email address and you should link it - click 'join the conversation'
- oh no, first tab is stuck infinitely spinning
- the second tab has joined the room, though

There's a bonus 'Error uploading one-time keys' in there, too (dunno if it's related).

**Comment by turt2live** [comment]
@lampholder for these kinds of issues, please submit rageshakes. If the button isn't present, `mxSendRageshake("https://github.com/vector-im/riot-web/issues/13371")` in the console.

**Comment by turt2live** [comment]
Without logs we will never be able to troubleshoot this.

**Comment by MadLittleMods** [comment]
See https://github.com/vector-im/element-web/issues/24831 as a sorta continuation to this
