### ISSUE TITLE
prompt for passphrase again

### ISSUE THREAD

**Issue by ousia** [vector-im/element-web#13386]
### Description

Wrong passphrase to decrypt or encrypt messages shows the following message:

> Incorrect recovery passphrase
> 
> Backup could not be decrypted with this passphrase: please verify that you entered the correct recovery passphrase.

### Steps to reproduce

1. Fail to enter your passphrase when asked for it.

Simply prompting for the passphrase again is better and simpler for the average users.

The long explanation is misleading to newcomers (even if they would normally understand what is going on).

Sorry, but this has to be simpler, if you expect laypersons to use encryption.

Don’t get me wrong, but right now encryption seems a headache to standard users.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 66
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Fedora
- **URL**: https://riot.im/app

**Comment by kittykat** [comment]
I'm going to close this for now as the UI has been redesigned :+1: Please open a new issue for further improvements
