### ISSUE TITLE
Rename "Secret storage" to "encrypted storage on server" in Settings

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#13398]
It doesn't mention that
- it is saved on the server (some users don't want to upload keys to server)
- it is encrypted

![image](https://user-images.githubusercontent.com/26059643/80357333-22894d80-887b-11ea-9d83-68c0e97ad961.png)

Proposal:
![image](https://user-images.githubusercontent.com/26059643/80357603-801d9a00-887b-11ea-95dc-3b734a73d496.png)

**Comment by dbkr** [comment]
This button no longer exists.
