### ISSUE TITLE
I get a Set up encryption toast every time I refresh the page even if I disable cross signing

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#13390]
<img width="323" alt="Screen Shot 2020-04-26 at 7 01 07 PM" src="https://user-images.githubusercontent.com/5855073/80323318-49e70880-87f0-11ea-9763-e12386f27340.png">

<img width="601" alt="Screen Shot 2020-04-26 at 7 01 18 PM" src="https://user-images.githubusercontent.com/5855073/80323328-510e1680-87f0-11ea-8c84-4509765c4dbc.png">

**Comment by 153** [comment]
I just checked my current settings; while `manually verify all remote sessions` is not enabled, I am still prompted to setup encryption every time I reload the Riot tab in my browser.

**Comment by t3chguy** [comment]
> disable cross signing

That setting doesn't disable cross signing, it just stops the implicit trust of others via cross-signing, does not disable other people trusting you over cross-signing.

**Comment by aaronraimist** [comment]
Well how do you disable cross signing? It seems like a pretty rare scenario to be someone paranoid enough to not use cross signing but still want other people to be able to cross sign their accounts.

**Comment by t3chguy** [comment]
I don't think its possible, but in the next release it should be less pushy and set up the bare minimum itself locally in the bg

**Comment by aaronraimist** [comment]
I don't think this toast exists anymore
