### ISSUE TITLE
Copy is wrong for "Encryption enabled" tile in Rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13435]
If you create a new e2e-by-default private room, the tile says:

<img width="570" alt="Screenshot 2020-04-28 at 22 51 55" src="https://user-images.githubusercontent.com/1294269/80541368-f2d56500-89a2-11ea-8290-50788999963f.png">

The "verify this user in their user profile" makes no sense - this is an empty room.

"Learn more & verify users in their user profiles" presumably would be the right copy.

**Comment by aaronraimist** [comment]
What is the learn more part referring to?
