### ISSUE TITLE
Default room alias dropdown looks ridiculous if numbers are in the name

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13445]
<img width="624" alt="Screenshot 2020-04-29 at 14 39 06" src="https://user-images.githubusercontent.com/3935731/80603043-cc0d4200-8a27-11ea-95df-ba4fa4b2e69c.png">

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/10560
