### ISSUE TITLE
'Verify new login' toasts should be cleared when you've verified using a different device

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13457]
otherwise it makes you feel like you need to verify the new login from all your devices, defeating the point of cross-signing

**Comment by jryans** [comment]
Okay, let's track post-release along with local echo etc.

**Comment by ShadowJonathan** [comment]
Original session was A, i verified B with it, then i verified C with B, the "verify login" prompt goes away on A.

**Comment by kittykat** [comment]
Closing as we cannot reproduce. Please re-open if it's still a problem for anyone.
