### ISSUE TITLE
Messages can decrypt successfully on a retry but still show as UTD

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#13473]
A number of rageshakes seem to be indicating that we're decrypting messages on a retry but they're still showing as undecryptable, according to the user.

Only pattern is that the message arrives before the key, the event fails to decrypt, a key request gets queued, the key gets decrypted, a decryption retry gets queued for the event, and then the key request gets cancelled, implying that the event decrypted successfully.

May perhaps be more common during a large catchup sync when the client will have a big sync result to process with a number of toDevice messages with keys.

**Comment by jryans** [comment]
Assuming @dbkr is investigating this.
