### ISSUE TITLE
Edit composer doesn't show the original markdown and can mess up the formatting of lists

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#13474]
Sorry if this is a duplicate, I couldn't find any other issue about this.

For example, let's consider this message:

```
Here's a list:

1. foo
    - bar
    - baz
```

Which renders like this on Riot:

![image](https://user-images.githubusercontent.com/5547783/80822938-fdc70a00-8bdb-11ea-9606-b948061e7900.png)

When sent, if I click the edit button, this is what appears in the edit composer:

```
Here's a list:
1. foo
  - bar
  - baz
```

Which doesn't have the same level of indentation, and also removed the blank line between the paragraph and the line (this latter point doesn't affect rendering here, but I've seen cases where it did).

If I edit this message (e.g. adding an extra r to bar) without fixing the markdown by hand, the message renders like this:

![image](https://user-images.githubusercontent.com/5547783/80823148-5e564700-8bdc-11ea-8439-ef9c9bd9a10f.png)

Without having any knowledge of how the composer works under the hood, it seems weird to me that it doesn't just show what's in the `body` of the original event.

I can't see any error in the console when showing up the composer.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7300

**Comment by babolivier** [comment]
I'm not sure this is fixed. It looks like the linked PR only fixes a symptom of this issue, which is the bad indentation of ordered lists.

If I send

```
Here's a list:

1. foo
    * bar
    * baz
```

and edit that message, the edit composer shows

```
Here's a list:
1. foo
    - bar
    - baz
```

which isn't the original markdown I sent. It's also not the markdown that's in the event's `body` (which does reflect what I originally sent).

I think this issue needs to be reopened (I seem to have lost perms to do this, which is probably a good thing, but means that I can't do it by myself anymore).

**Comment by t3chguy** [comment]
> which isn't the original markdown I sent. It's also not the markdown that's in the event's body (which does reflect what I originally sent).

As per the spec, the `body` is a plaintext representation, not specifically markdown so it can't be trusted as such esp as markdown dialects can vary between clients. `*` and `-` are both list notations so are pretty much equivelant.

**Comment by robintown** [comment]
What @t3chguy said, but there are also https://github.com/vector-im/element-web/issues/10725 and https://github.com/vector-im/element-web/issues/20387 to track the more general idea of preserving Markdown verbatim

**Comment by babolivier** [comment]
Oh right so it's not closed by https://github.com/matrix-org/matrix-react-sdk/pull/7300 but as a duplicate of https://github.com/vector-im/element-web/issues/10725 (now that the list formatting part of the problem is fixed). Gotcha, thanks :)
