### ISSUE TITLE
Breadcrumb shows different number of notifications than roomlist does

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#13484]
<img width="47" alt="Screen Shot 2020-05-03 at 10 11 10 PM" src="https://user-images.githubusercontent.com/5855073/80933853-ff830000-8d8a-11ea-8ddf-93b5433c472f.png">
<img width="243" alt="Screen Shot 2020-05-03 at 10 11 54 PM" src="https://user-images.githubusercontent.com/5855073/80933871-19bcde00-8d8b-11ea-9ccb-71d16be2b4b3.png">

**Comment by turt2live** [comment]
@aaronraimist did it correct itself eventually?

**Comment by aaronraimist** [comment]
Well I clicked on the room right after filing the issue so yes they both went to zero at that point.

**Comment by turt2live** [comment]
hmm, next time this happens please submit a rageshake. Also if possible, see if it resolves on its own after 30-60 seconds (this would indicate which component is problematic)

**Comment by aaronraimist** [comment]
I don't think I have seen this recently so closing
