### ISSUE TITLE
I got prompted for a recovery key as well as doing an emoji verification

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#13495]
I signed in on a new device, did an emoji verification from an existing (but not very old) device, and was then *also* prompted to enter a recovery key

**Comment by jryans** [comment]
My suspicion so far is that the existing device did not have private keys, so as a fallback, the new device presenting a 4S prompt, which is expected if that's what happened. Unfortunately, the logs are swamped with UTDs, so it's hard say for sure.

@richvdh Could you screenshot the Settings -> Security -> Cross-signing -> Advanced areas on each device? That may help to confirm if that's what happened.

**Comment by richvdh** [comment]
New device:

![image](https://user-images.githubusercontent.com/1389908/81055179-15461180-8ec0-11ea-9744-7de58ae5c9d9.png)

existing device:

![image](https://user-images.githubusercontent.com/1389908/81055305-576f5300-8ec0-11ea-93c7-debf616c12f7.png)

**Comment by jryans** [comment]
Hmm, it's definitely puzzling, since the existing device claims to have all keys cached locally, so it should have been able to gossip them.

**Comment by kittykat** [comment]
I'm going to close this issue for now as designs and functionality have changed since it's been filed. Please open a new issue if you feel that there are improvements to be made.
