### ISSUE TITLE
Upgrading a room does not migrate roomnick and roomavatar

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#13499]
### Description

Upgrading a room loses the room specific nick and avatar set by participants as set by `/myroomnick` and `/myroomavatar`.

### Steps to reproduce

- Set `/myroomnick` and `/myroomavatar`
- Upgrade room via `/upgraderoom X`

`/myroomnick` and `/myroomavatar` are lost in the upgrade.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: riot-web version: 1.5.15

**Comment by t3chguy** [comment]
If you are still experiencing this issue I suggest opening a https://github.com/matrix-org/synapse/
