### ISSUE TITLE
Small ux improvements to aliases

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13501]
Per https://github.com/vector-im/riot-web/issues/13077#issuecomment-621905451

- [x] Inline progress feedback when adding aliases
- [x] Indicate what the attempted change was in the error message

**Comment by aaronraimist** [comment]
The improvements listed here are checked off but the PR was closed without being merged and I don't think they ever happened in another PR. What happened?

**Comment by t3chguy** [comment]
The author is no longer involved. Closing in favour of the broader #13077
