### ISSUE TITLE
Unable to verify session

### ISSUE THREAD

**Issue by Autre31415** [vector-im/element-web#13507]
With the cross-signing update hitting all devices simultaneously I've found myself in a scenario where both my desktop app and my phone app are not verified and therefore cannot verify one another. At the same time I'm unable to verify with my passphrase, when I attempt to it will kick me back to the verify session screen as if nothing happened, or sometimes will give a success message followed by another verify screen in an infinite loop.

**Comment by jryans** [comment]
@Autre31415 It would be good to submit debug logs to investigate if there is a bug or if the backup key truly is wrong.

For immediate next steps, are you able to proceed by saying the backup key is forgotten and creating a new key?

**Comment by Autre31415** [comment]
At first the verify screen was telling me the backup key is wrong, after trying it some more now it leads me into an infinite loop where I put in the passphrase, it tells me it worked, then it asks me to verify again and asks for the passphrase again and so forth.

**Comment by jryans** [comment]
@Autre31415 Okay, can you submit debug logs from Settings -> Help in Riot and reference this issue? That should help us better understand what's happened.

**Comment by pelzvieh** [comment]
Same here. Started with MacOS desktop client. Key recovery works in the sense that I successfully set up RiotX on two devices and they can decrypt encrypted rooms. However, the recovery passphrase does not verify any of the sessions for cross signing. I submitted a bug report from one of the devices a minute ago, unfortunately missing to reference this issue, sorry.

**Comment by ccjon** [comment]
This looks similar to my issues right now except that I do not have, and never have had, Key Backup enabled (since it keeps asking for a phrase or key that I've never been given a chance to create)

I have a web session and a macos app session open and can read all the messages that are not blocked by senders' setting for hiding from unverified sessions.

I can't verify either session b/c I can't get past the same passhrase/key dialog that comes up when I choose to setup Key Backup.

**Comment by aaronraimist** [comment]
@ccjon well you set the passphrase or downloaded the security key at some point on some client or it wouldn't be asking you for it. If you don't know the password then you should reset it and start over. Settings -> Security & Privacy -> Reset cross-signing and secret storage

**Comment by ccjon** [comment]
Alright, I'll have to admit that I could have not followed my normal 'protocols' for such things and set a passphrase that I couldn't recover. I was really worried about resetting it all; But I have and it the world is still turning. So I have that going for me. Thanks.

**Comment by Sieboldianus** [comment]
> Settings -> Security & Privacy -> Reset cross-signing

This setting does not exist, neither in Element Desktop, nor in Element Web

**Comment by dbkr** [comment]
We haven't heard from the issue creator in a while & others are getting confused by the info here which is now outdated, so I'm going to close this before more semi-related problems get lumped into it.
