### ISSUE TITLE
Enable sharing an application window (instead of the whole screen) in video calls

### ISSUE THREAD

**Issue by aral-matrix** [vector-im/element-web#13518]
**Is your suggestion related to a problem? Please describe.**
Related:
 https://github.com/vector-im/riot-web/issues/4880 
 https://github.com/vector-im/riot-web/issues/12652

**Describe the solution you'd like**
There should be a button next to the camera on/off button, that can be used *during* a video call to select an application window (or the screen) to be shared.

**Describe alternatives you've considered**
not really any alternatives I see

**Additional context**
n/a

**Comment by t3chguy** [comment]
Presumably this is for the electron app as this is supported in the browser?

**Comment by aral-matrix** [comment]
My bad! The suggestions template didn't ask for software versions. Yes, this is for the riot-desktop app (on debian), which appears to be what you refer to as the "electron" app.

**Comment by SimonBrandner** [comment]
I believe this can be closed since this already works in Chrome and Firefox and [a fix](https://github.com/matrix-org/matrix-react-sdk/pull/5525) for the desktop is waiting for review.

**Comment by SimonBrandner** [comment]
Oh, I just realized I hadn't read the full description. But making screen sharing more obvious is cover by [#12652](https://github.com/vector-im/element-web/issues/12652), so I guess this should still be closed
