### ISSUE TITLE
design for room tile error handler

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#13548]
The error handler for `RoomTile` is very minimal – enough to stop a render issue from cascading upwards to the `RoomSubList`.  It could use some improvement:

- [ ] Relocate error handler to `RoomTile` itself rather than `RoomSubList`
- [ ] Add a click handler so the user can open the room
- [ ] Pop up a modal at least once, but at most once per session, so that we get feedback if errors occur

**Comment by robintown** [comment]
There's no longer a separate error boundary for room tiles
