### ISSUE TITLE
Sidebar Section heights are reset regularly

### ISSUE THREAD

**Issue by mgaudet** [vector-im/element-web#13579]
### Description

On a regular basis (but not _every load_) I find my sidebar section heights are changed. This is most noticeable in my _Favourites_ section, which has two channels. Yet when I load Riot-Web (chat.mozilla.org) I very often find I have to adjust the side bar section size so that I can see both my favourite channels. 

### Steps to reproduce
1. Load Riot-Web: 
2. Side bar section heights don't match my expectation. 

I expect that every time I open Riot-Web, the section heights are preserved. 

Or at least that the Favourites section is prioritized rather than being pushed out of the way by other sections. 

Logs being sent: Not at the moment; can do on request should it be believed that it will help. May take some time to reproduce. 

In the screenshot below you can see my favourites section has only one visible channel, despite having only two inside it. 
<img width="293" alt="Screen Shot 2020-05-07 at 9 04 10 AM" src="https://user-images.githubusercontent.com/2906003/81310772-c7f1ad80-9041-11ea-80fb-cdce5c3583ee.png">

### Version information

- **Platform**: web (in-browser) or desktop? Web

For the web app:

- **Browser**: Firefox Nightly (77.0a at the moment, but changes frequently)
- **OS**: macOS (this makes the problem worse via the default hiding of scrollbars. 
- **URL**: chat.mozilla.org

**Comment by jryans** [comment]
Thanks for the feedback! We have some room list UX improvements in the works that I believe will address this in the near future.

**Comment by turt2live** [comment]
@mgaudet does this happen after resizing the window in any way? Such as deliberately resizing, moving the window to another monitor, etc

**Comment by mgaudet** [comment]
Maybe? Honestly, it happens when I'm not looking for it, and so I don't have a reliable STR -- I just know I find myself adjusting the height of that section frequently enough that it's annoying.

**Comment by mgaudet** [comment]
I do unplug my laptop regularly -- perhaps it's resolution changes from when I unplug.

**Comment by yannicka** [comment]
I've the same issue and it also it happens when I'm not looking for it.

**Comment by turt2live** [comment]
This shouldn't be relevant with the new room list.
