### ISSUE TITLE
DM creation fails if POST /_matrix/client/r0/keys/query fails

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#13598]
So for example Dendrite cannot use the DM invite dialog. Instead, a 404 appears in the console and the invite dialog is stuck in a busy state (spinning wheel of death). It feels like we could assume a 404 means the user does not wish to be E2E encrypted by default.

**Comment by Half-Shot** [comment]
I would share logs, but the bug reporter fails on private browser sessions with: `Failed to send logs: No connected database`

**Comment by jryans** [comment]
> I would share logs, but the bug reporter fails on private browser sessions with: `Failed to send logs: No connected database`

@Half-Shot About this part, we're tracking the problem in https://github.com/vector-im/riot-web/issues/13290, but as a workaround (since debug logs are hugely valuable for many issues), I'd suggest using Firefox containers as way to log in to test accounts, since IDB and rageshakes work fine there.

**Comment by Half-Shot** [comment]
Of course. I really need to start using containers over private windows.

**Comment by Half-Shot** [comment]
I don't have a way to test this now that Dendrite supports it.
