### ISSUE TITLE
Option to remove verification for a certain user

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/element-web#13591]
**Is your suggestion related to a problem? Please describe.**
Before the 1.6.0 update, you could toggle verification status for each individual device (and Blacklist status). Now, there doesn't seem to be an option to remove verification status for a user.

This could be useful if you know someone is no longer using devices, but they're still a part of a room you participate in, but you can't kick them.

It could also be useful if you want to re-verify someone's devices after a long period of not communicating.

**Describe the solution you'd like**
Re-add the option to toggle verification and blacklist status for each device.

You could make the text of each session (Desktop, mobile, etc.) clickable. Once clicked, it would open a menu with the device ID, and an option to toggle verification and blacklist status.

Alternatively, bring up a pop-up menu when clicking the "# verified sessions" text, instead of expanding. The pop-up menu could show all the information for all devices.

**Describe alternatives you've considered**
If the granularity of toggling verification and blacklist status for each device is too confusing, consider adding a "Reset" button to unverify all devices for a user.

**Comment by jryans** [comment]
Related: https://github.com/vector-im/riot-web/issues/13505

**Comment by dbkr** [comment]
I think this is covered by the above liked issue and https://github.com/vector-im/element-web/issues/11751
