### ISSUE TITLE
Ensure data: URLs are handled okay in OG metadata

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1359]

**Comment by ara4n** [comment]
e.g. bing.com

**Comment by MadLittleMods** [comment]
This seems to work if you turn on the few settings to enable URL previews:

 1. **All settings** -> **Preferences** -> **Enable inline URL previews by default**
 1. **Room settings** -> **URL Previews** 
 
 
![](https://user-images.githubusercontent.com/558581/134748657-4c5660cb-1d38-4148-8160-3884f05c7422.png)
