### ISSUE TITLE
User profile does not show session IDs, so it's difficult to delete old unverified sessions

### ISSUE THREAD

**Issue by chr-1x** [vector-im/element-web#13596]
![image](https://user-images.githubusercontent.com/1606822/81359692-b5ea2c00-908e-11ea-817a-739c731a25e5.png)

### Description

The list of sessions under "Settings" -> "Security and privacy" is sorted in a different order than the list of sessions on one's own user profile. Furthermore, many clients use nondescript names for sessions, so it's difficult to distinguish between them. Session ID would be sufficient to tell them apart, but the list of sessions on the user profile does not show the session IDs. This makes it difficult to delete the unverified ones from the "Security and privacy" section.

### Steps to reproduce

Log in on several devices and then attempt to figure out which of your sessions is verified.

I would expect an easy way to delete / log out of my unverified sessions.

### Version information

- **Platform**: Web, desktop

For the web app:

- **Browser**: Firefox
- **OS**: Linux
- **URL**: https://matrix.cybre.space

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.6.0

**Comment by t3chguy** [comment]
You can hover over the session in the right panel to get its Session ID.
For Not Trusted sessions you can also click on them to see it there.

![image](https://user-images.githubusercontent.com/2403652/81401636-a7038800-9127-11ea-9828-bbe4695de8fd.png)

**Comment by chr-1x** [comment]
That's good to know, but it still requires me to go back and forth between my profile and the settings page, since I can't hover over them while the settings modal is open. Ideally the security and privacy modal would just show me whether each session is verified in the same table where I can delete them.

**Comment by t3chguy** [comment]
Cool, so to close this issue would the following be okay:

+ Use same list order in both
+ Show verification status in Settings > Sessions

**Comment by chr-1x** [comment]
yeah, I think both of those would be improvements

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/issues/11221 will also show verification state in Settings, so that's likely to be main path to resolving this.

**Comment by matthijskooijman** [comment]
Another path would be to allow deleting sessions directly from the profile page (subject of #13187).

**Comment by stragu** [comment]
I agree that consolidation is very much needed to improve the security / privacy user experience (and not make people feel like "it's too much effort").
As for how the information should be split between the user's right-side panel and the Settings > Security & privacy tab: I think the side panel should show minimal information (i.e. enough to identify that sessions need verification, which it already currently does), and the settings dialogue should show _all_ the information that is available (i.e. at least add the colour-coded status of the sessions).

**Comment by aaronraimist** [comment]
The user profile in the right panel still only shows device IDs on hover.

However the session management settings page has been redesigned to show verification status which I think solves your problem of finding unverified sessions in a better way. Let me know if you consider this to be fixed @chr-1x.

<img width="981" src="https://user-images.githubusercontent.com/5855073/141104359-0e9a9115-0e64-4ce1-88ae-c77e4d0da855.png">

**Comment by chr-1x** [comment]
Yep, this solves it. Much easier to manage devices now, thanks.
