### ISSUE TITLE
riot-desktop seems to depend on deprecated(?) riot-web (debian)

### ISSUE THREAD

**Issue by cloudyfuel** [vector-im/element-web#13597]
After upgrading the system, both `riot-web` and `riot-desktop` are installed. AFAIK riot-web should be deleted. When I do `apt purge riot-web -s` I see:
```
The following packages were automatically installed and are no longer required:
  libsqlcipher0 riot-desktop
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  riot-web*
```

It's not obvious what should be done and none of it is done automatically for me. It's non obvious whether I should do `apt remove` or `apt purge`. Doing `apt autoremove` should do the job, it didn't. Plus the riot icon disappeared from the launcher.

I suggest looking into shipping Riot in Debian repositories as is good practice. Either maintaining packages or supporting debian packagers. I have to tinker with riot way too often for what it is and non tech-savvy relatives cannot do it themselves.

**Comment by t3chguy** [comment]
Related to closed https://github.com/vector-im/riot-web/issues/13509

**Comment by jryans** [comment]
`riot-web` is now an empty package that depends on the new package `riot-desktop`. You could remove `riot-web` and use only `riot-desktop` going forward, but so far we haven't found a way of tweaking the package to cause `apt` to auto-migrate `riot-web` installs to `riot-desktop` and also remove `riot-web`.

The current state should be that both people who historically had `riot-web` installed and also new people installing `riot-desktop` directly are getting the latest 1.6+ versions.

We're happy to tweak the packages if it would help, but we'll likely need advice from Debian experts on how to do so.

**Comment by cloudyfuel** [comment]
`apt install riot-desktop` fixes the problem.

You have to make the `riot-desktop` package be marked as manually installed - that tells the dpkg that the riot-desktop isn't a mere dependency, but a main package. Also mark `riot-web` package as a redundant package (probably called `automatically installed`) so that `apt autoremove` removes it after the switch.

**Comment by jryans** [comment]
> You have to make the `riot-desktop` package be marked as manually installed - that tells the dpkg that the riot-desktop isn't a mere dependency, but a main package.

Isn't that something only the user can do manually though?

> Also mark `riot-web` package as a redundant package (probably called `automatically installed`) so that `apt autoremove` removes it after the switch.

Is this something we can do from the packaging side? If so, how?

**Comment by ge-fa** [comment]
Probably [this](https://wiki.debian.org/RenamingPackages) gives some insights how to handle this.

**Comment by jryans** [comment]
I agree that page describes this topic, but unfortunately I don't have enough Debian knowledge to translate it into what we should do here. If someone has a more detailed proposal of what should be changed in our packages, we can give it a try.

**Comment by ge-fa** [comment]
Is there someone in your team who takes care of the Debian packages? It should be trivial for them to handle this.

**Comment by jryans** [comment]
Not really, that's why I asking here for suggestions. We already made one attempt at this, but it doesn't seem to have worked, so I am wary of flailing about without very specific guidance.

**Comment by t3chguy** [comment]
This is no longer the case with `element-desktop`

![image](https://user-images.githubusercontent.com/2403652/93783298-711cf700-fc23-11ea-9252-9e790d739462.png)
