### ISSUE TITLE
Unexpected message after successful x-sign verification

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/element-web#13601]
### Description

I did some cross signing today, and after verifying @babolivier I got a message from him:

```json
{
  "content": {
    "code": "m.unexpected_message",
    "reason": "the device received an unexpected message"
  },
  "room_id": "!gQoLsXlrIxtrpqqktS:abolivier.bzh",
  "type": "m.key.verification.cancel"
}
```
```json
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "ciphertext": "AwgDEsABhbTbWkhyi91QuVd5gfGTn6sCnOh7yVW5agzXrsYjORQqrBZ9CV9czNh4FvI6Nf9GOSRJ+UDNMjucM10uaklqEv2d9jxXTaXOBvxLL5PSwO7j8j2W3mPqUzFt7Diw7EdstrblQVPHoTPVBCj5svITDfHH/8GACOww/6YMsjps8fP/vIfqLGQ/sht1/2qhgMld3vhtGbw3voXmxYfOWW2HZmVacI9nVEdCUOfQNLFL4n/G2lSri84+1zQ72OYoBLiForD0GabtWP1dbgVfgCZlBH3vXViQmYiSaOSRDgXp/QELdnEcQoplHSmOTp8yfjaI/qLqu2N3p17cXZcYbYgPMWroYHy10TcI",
    "device_id": "XMMOBAZDPQ",
    "m.relates_to": {
      "event_id": "$158894640311366lBepo:gruenhage.xyz",
      "rel_type": "m.reference"
    },
    "sender_key": "OoJKpW4H3Lu4gAx+GhqLxURX8UOEE4BfpAp7/PfGtHU",
    "session_id": "DtGtL9VhxBlQT/nVW2hOjaRn97zNoLbZ3xQzoL5Tzxg"
  },
  "event_id": "$158894845415skdok:abolivier.bzh",
  "origin_server_ts": 1588948454890,
  "sender": "@brendan:abolivier.bzh",
  "type": "m.room.encrypted",
  "unsigned": {
    "age": -1349
  },
  "room_id": "!gQoLsXlrIxtrpqqktS:abolivier.bzh"
}
```

Log: will send my side after creating the issue.

### Version information

This stuff is for my install, @babolivier will have to add their stuff themselves.

- **Platform**: web

For the web app:

- **Browser**: Firefox 75
- **OS**: Void Linux
- **URL**: riot.gruenhage.xyz, riot-web v1.6.0-rc.4

**Comment by babolivier** [comment]
In terms of my version info:

* Platform: web
* URL: https://riot.im/develop
* Browser: Firefox 75
* OS: Arch Linux

**Comment by kittykat** [comment]
@jcgruenhage @babolivier Have you experienced this again? If not, it would be worth considering closing this issue as we haven't had any other reports.

**Comment by kittykat** [comment]
I'm going to close this issue for now as we haven't had another report of the same problem since, so we can probably assume that it has been resolved. Please re-open if you experience this again.
