### ISSUE TITLE
`TypeError: Cannot read property 'getDisplayName' of null` during verification

### ISSUE THREAD

**Issue by Cokemonkey11** [vector-im/element-web#13607]
### Description

I was prompted to send debug logs.

What did I do before this? I opened the riot IM desktop app just after verifying a web client and then later signing out of the web client. Both of those flows worked fine.

### Steps to reproduce

Unattempted

Describe how what happens differs from what you expected.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10 x64
- **Version**:

riot-web version: 1.6.0
olm version: 3.1.3

**Comment by Cokemonkey11** [comment]
I've submitted debug logs via the app

**Comment by jryans** [comment]
Seems like a error occurred during verification: `TypeError: Cannot read property 'getDisplayName' of null`

**Comment by kittykat** [comment]
I'm going to close this for now due to the age of the issue and because we haven't had more reports of it. In the mean time, the code around this has changed since the issue was filed.
