### ISSUE TITLE
Inviting someone to a direct chat breaks the chat

### ISSUE THREAD

**Issue by Demi-Marie** [vector-im/element-web#13622]
### Description

Inviting someone to a direct chat breaks the chat

### Steps to reproduce

- Create a direct chat
- Set “visible to all members, from the point they were invited”
- Invite someone
- They try to send a message

### Expected behavior

They can successfully send a message.

### Actual behavior

They cannot send a message.

Logs being sent: Not yet.  I might be able to send them if needed.

### Version information

- **Platform**: Desktop
- **OS**: Debian Linux
- **Version**: 1.6.0

**Comment by t3chguy** [comment]
> Describe how what happens differs from what you expected.

**Comment by DemiMarie-parity** [comment]
@t3chguy fixed

**Comment by t3chguy** [comment]
> They cannot send a message.


What happens when they try? Any errors? does it just never send or what?

**Comment by DemiMarie-parity** [comment]
> > They cannot send a message.
> 
> What happens when they try? Any errors? does it just never send or what?

At least in one case, it just fails to send.

**Comment by turt2live** [comment]
Fails to send how? Red? Forever grey? Looks-sent-but-not-received?

**Comment by DemiMarie-parity** [comment]
Red

**Comment by t3chguy** [comment]
Sending logs would certainly be helpful.

**Comment by DemiMarie-parity** [comment]
I will see if I am able to do so.

**Comment by robintown** [comment]
Closing, as we're not able to investigate this further without logs
