### ISSUE TITLE
Message deleted icon clips strangely when zooming in

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#13634]
Latest chrome, /develop, bottom clipped @ 110%:

<img width="277" alt="Screenshot 2020-05-11 at 18 06 00" src="https://user-images.githubusercontent.com/4626865/81591068-bbf44b80-93b3-11ea-88f0-1b43e9fc23a9.png">

**Comment by aaronraimist** [comment]
Hmm can't reproduce in Firefox or Chrome on macOS

**Comment by t3chguy** [comment]
Closing due to no reproductions since
