### ISSUE TITLE
Undecryptable edited messages appear blank?

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#13660]
Looked like 

![image](https://user-images.githubusercontent.com/2072976/81845627-bed47500-9548-11ea-8584-f871b463fec5.png)

**Comment by dbkr** [comment]
This looks like the key being slow to get from matrix.org to HS's HS (key arrives about 5 mins after the message) but it looks like the fact that the message is edited causes it to not display as a undecryptable message and instead just appear blank.

**Comment by Half-Shot** [comment]
Not seen this one in  while.
