### ISSUE TITLE
/part jumps to next room when request finishes even if you've already switched to another room

### ISSUE THREAD

**Issue by jo-so** [vector-im/element-web#13687]
### Description

Updated title after discussion below: seems like the problem here is that it switches to the next room when the request finishes, even if you've already switched to a different room. Original description follows.

After I left the room with `/part` riot-web opens a random room.

### Steps to reproduce

- Go to a room you want to leave.
- Enter `/part` in the message field and hit Enter
- When the room is closed and saved to *Archive*, a random other room gets opened.

I would expect the next screen after a part in #/home or something, but it should not trigger a load of data (events in a room).

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 78 (nightly)
- **OS**: Debian Linux
- **URL**: somewhere 1.6.0

**Comment by t3chguy** [comment]
> I would expect the next screen after a part in #/home or something, but it should not trigger a load of data (events in a room).

It loads the next sequential joined room. The data is already locally stored, pushed from the server via `/sync`.

**Comment by jo-so** [comment]
> It loads the next sequential joined room. The data is already locally stored, pushed from the server via `/sync`.

At least for me, I can tell that I see often the spinner, when it opens
the new room. (I've joined more than 200 rooms.)

And it's a problem when you've switched to another room in the meantime.
Then the leave event triggers the jump to the “random” room.

**Comment by t3chguy** [comment]
Then sending it to home in the same way would incur the same bug. The bug itself should be solved.

**Comment by dbkr** [comment]
Updated title & description to reflect the above.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/commit/06f69abad9871920e9ca471887b18cd5c90bb679
