### ISSUE TITLE
Prominently display session ID in Riot UI

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#13681]
**Is your suggestion related to a problem? Please describe.**

Now that device cross-signing is turned on, I get scary warning messages popping up from time to time, asking me if FHJKEFGHUISDKHJ is one of my sessions. Unless I've memorized the gibberish ID for each of my sessions, how should I know? I have to dig multiple clicks into the Settings for each one of my sessions to find out if FHJKEFGHUISDKHJ is me or a Bad Actor trying to login to my account.

**Describe the solution you'd like**

The session ID for the session I'm currently using needs to be prominently displayed somewhere on the Riot UI, so I can see at a glance if a verification message is talking about a session I am using.

**Describe alternatives you've considered**

Is there a way for users to give sessions human-recognizable names (eg "Bob's phone"), so that the verification messages can use those instead of (or as well as) the gibberish string?

**Additional context**

Having all your private chats encrypted is fantastic, and the cross-signing makes encryption much more user-friendly, but anything that can be done to reduce the user confusion associated with managing encryption security will make Riot comprehensible to a wider range of users.

**Comment by aaronraimist** [comment]
You aren't intended to have to look at those session IDs. Riot tries to name devices in a friendly way like "riot.im/app (Firefox, macOS)". Is that not working for you?

**Comment by strypey** [comment]
On 2020-05-20 05:57, Aaron Raimist wrote:
> You aren't intended to have to look at those session IDs. Riot tries to name devices in a friendly way like "riot.im/app (Firefox, macOS)". Is that not working for you?

For that to be useful, the names have to be *much* more specific. Let's
say I have a work phone and a personal phone, each with Riot-Android
installed. Both sessions get named as "Riot Mobile". Let's say I have a
desktop with a dual-boot, one with my GNU/Linux daily driver, one that's
for testing purposes. If I use Riot-web on both, both sessions get named
something like "Riot web on Linux". My experience so far is that the
only way to be sure I'm selecting the correct session is to check IDs,
which currently requires diving multiple clicks and scrolls into the
Settings.

**Comment by t3chguy** [comment]
Or you could rename your devices to be appropriate to your usage

**Comment by strypey** [comment]
That's true, but I guess the question for the Riot devs is; what's the likely overlap between Matrix newbies who don't know how to rename their devices, and users who have multiple sessions that end up with the same default name. If they evaluate that overlap as low (eg just me ;), then I guess they will just just close the issue. If they evaluate that overlap as moderate or high, other UX tweaks might be worth considering.

**Comment by strypey** [comment]
Another possible solution would be to prompt the user to name their new session on first use? Maybe as part of the device verification workflow?

**Comment by aaronraimist** [comment]
That's planned eventually https://github.com/vector-im/riot-web/issues/2295

**Comment by afranke** [comment]
Closing, considering the above comments (i.e. they aren’t supposed to be visible and there is another issue about making them more personal/intelligible).
