### ISSUE TITLE
Events sent by guests appear twice for the sender

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#13706]
### Description

Guest Events everytime duplicated / Reload fixed the View but not the Problem.

Normal User  see one Text, only the Guest View seems broken, not in Auth State.

### Steps to reproduce

[My Support Channel to reproduce](https://chat.3dns.eu/#/room/#support:matrix.3dns.eu)

![image](https://user-images.githubusercontent.com/1436958/82241665-d773cf00-993c-11ea-9de3-01b1e32469e1.png)
![image](https://user-images.githubusercontent.com/1436958/82258858-df426c00-995a-11ea-9167-403e6f4099fc.png)

### Version information
v1.6.1-rc.1

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Opera
- **OS**: Windows
- **URL**: https://chat.3dns.eu/#/room/#support:matrix.3dns.eu

**Comment by turt2live** [comment]
On the surface this looks to be a server-side issue in that the local echo indications aren't present on the event. 

Likely, Synapse isn't associating the guest's access token with the token used in the sync, so isn't sending the transaction ID. Or Riot is somehow acquiring a second access token.

**Comment by DoM1niC** [comment]
> On the surface this looks to be a server-side issue in that the local echo indications aren't present on the event.
> 
> Likely, Synapse isn't associating the guest's access token with the token used in the sync, so isn't sending the transaction ID. Or Riot is somehow acquiring a second access token.

THX for your reply, so its not a wrong config or so on myself ?

**Comment by turt2live** [comment]
It looks like your config is fine, unless you've done something extremely weird with your reverse proxy.

**Comment by DoM1niC** [comment]
its just NGINX so I tried some other forwarding method now but doen't change at all, I never had this issue before.

**Comment by galaxyoyo** [comment]
The problem is still here.

**Comment by DoM1niC** [comment]
> The problem is still here.

yep for me too and currently I need Matrix as Guest Login for a Project to embed a simple Chat :( I hope some could help to fix it or could explain whats the problem is.

**Comment by t3chguy** [comment]
The sync response looks fine, will try to figure out what's going wrong in the depths of the js-sdk here:

![image](https://user-images.githubusercontent.com/2403652/93578954-d2c83180-f995-11ea-91a0-9c5e58654ce4.png)

**Comment by t3chguy** [comment]
Actually never mind, looking at how js-sdk associates things, it uses the unsigned.transaction_id which Synapse isn't sending back

**Comment by t3chguy** [comment]
This is a Synapse issue where for whatever reason it is not performing in a spec-compliant manner: https://matrix.org/docs/spec/client_server/r0.6.1#room-event-fields

**Comment by freshprince** [comment]
Is there a issue that tracks this problem in synapse?

**Comment by ynerant** [comment]
@freshprince did you find any related issue in Synapse?

**Comment by t3chguy** [comment]
Nope, will report it now
