### ISSUE TITLE
Hoverover breaks right-alignment on displayname on IRC skin

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13722]
<img width="553" alt="Screenshot 2020-05-19 at 23 56 44" src="https://user-images.githubusercontent.com/1294269/82386491-7297a200-9a2c-11ea-9e90-932e9ed5ebbc.png">

**Comment by JorikSchellekens** [comment]
I addressed this in the pr https://github.com/matrix-org/matrix-react-sdk/pull/4531#discussion_r426619732. I can't think of a css only fix to this.

**Comment by yannicka** [comment]
I can't reproduce this problem, is it still relevant?

**Comment by aaronraimist** [comment]
No
