### ISSUE TITLE
replies don't respect IRC layout

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13723]

**Comment by JorikSchellekens** [comment]
In what way? 
![image](https://user-images.githubusercontent.com/23084468/82559843-336e6b80-9b68-11ea-8944-a3b9b3d205af.png)

**Comment by yannicka** [comment]
Margins are not good (from my point of view):
![image](https://user-images.githubusercontent.com/22885898/100545657-2c35c200-325d-11eb-9b3d-c5f1b1598771.png)
