### ISSUE TITLE
Tap topic to edit when allowed

### ISSUE THREAD

**Issue by WillPittenger** [vector-im/element-web#13742]
**Is your suggestion related to a problem? Please describe.**
In order to make a minor change to an existing topic, you have to go into the channel settings.  With a touch screen, that's at at least two extra taps.

**Describe the solution you'd like**
ChatZilla has had a much better solution for ages.  In there (see screenshots), you click the topic to edit it.  Given not every channel lets the average user edit topics, when the topic isn't editable, it should have a lock next to it.  Like cZ, the topic edit box should be visible as an edit box only when it has the focus.  Pressing return or moving the focus elsewhere would save the changes.  Pressing Escape would cancel the changes and move the focus to where it was before topic edit box received the focus.

**Describe alternatives you've considered**
I couldn't think of any.

**Additional context**
![cZ topic in display mode](https://user-images.githubusercontent.com/5451058/82508894-14ba9700-9acc-11ea-8613-c36e07f5b713.png)
![cZ topic in edit mode](https://user-images.githubusercontent.com/5451058/82508897-15532d80-9acc-11ea-9d49-008f9fdb1ceb.png)

**Comment by t3chguy** [comment]
This got done

<img width="719" alt="image" src="https://user-images.githubusercontent.com/2403652/232818905-4b79d1c8-97d2-47ba-8f6d-6ac415e200c0.png">
