### ISSUE TITLE
avatar positioning in textual RRs has gone wibbly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#13741]
behold the wibble

<img width="70" alt="Screenshot 2020-05-21 at 00 43 53" src="https://user-images.githubusercontent.com/1294269/82508203-3cc1ee80-9afc-11ea-8cd8-acb5d0fd6906.png">

**Comment by robintown** [comment]
Empirically no longer wibbly
![Screenshot 2021-07-16 at 00-29-09 Element](https://user-images.githubusercontent.com/48614497/125891934-1d601987-5a8b-4695-9809-c4a36ab030b5.png)
