### ISSUE TITLE
Create a modern appearance tab

### ISSUE THREAD

**Issue by JorikSchellekens** [vector-im/element-web#13750]
![image](https://user-images.githubusercontent.com/23084468/82561141-c01a2900-9b6a-11ea-8020-d639ecc39579.png)

**Comment by yannicka** [comment]
On "Message layout", is "Modern" the right term? Shouldn't we use a more timeless term like "Wide" for example?

**Comment by aaronraimist** [comment]
It might also be helpful to show multiple messages in the message layout area to get a better sense of the difference between the two.

I like the way Discord does their appearance settings where it shows you a little preview of several messages at the top of the screen and then has all of the appearance settings below that. As you change settings it affects the preview.

https://support.discord.com/hc/en-us/articles/207260127-How-can-I-change-Discord-s-appearance-theme-

**Comment by ingingin** [comment]
This... is **HOT**

**Comment by ingingin** [comment]
Now I like the rounded corners. No, I love rounded corners, but on Riot, it doesn't fit.
![dw](https://user-images.githubusercontent.com/65529926/82739326-4df24180-9d2e-11ea-80c8-9f3cd5f11f43.png)
The Default is best

**Comment by robintown** [comment]
We now have this since the launch of message bubbles
