### ISSUE TITLE
Awkward to use the room directory to copy content

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#13751]
I'm trying to copy room IDs and/or aliases from the room directory, which is impossible because everything is clickable. Would be good if the subtext for the aliases was always visible and selectable.

**Comment by Biep** [comment]
Ideally there would be two things to copy:
- something that will become a pill when pasted in a message;
- an external (matrix.to) link for sharing over other media.

(Or, even better, matrix.to links would translate into pills if pasted in a message.)
