### ISSUE TITLE
Cannot fully leave a community you were removed from

### ISSUE THREAD

**Issue by cloudrac3r** [vector-im/element-web#13765]
Please tell me if you need screenshots or logs.

I have tried to search GitHub for duplicates and did not find any.

### Description

Admins of a community have the option to remove a community member from the community. Removing members seems to remove them from the perspective of other members, but for the person that was removed, the community remains in the filter panel and in their communities gallery. They can still view the community and its members, but they can't open the community settings control to be able to fully leave the community. It is not possible to leave the community.

### Steps to reproduce

1. As a community admin, open the community view
1. Select another member in the community using the member list
1. Click "remove from community"

The removed member is now experiencing bad UI.

### I expected one of these things to happen

- All traces of the community are removed from the recipient's app, including the icon in the filter panel and the listing in the communities gallery.

/OR/

- When the user next tries to view the community, instead of displaying the usual community UI, the user sees a message saying "You were removed from this community by an admin." with a prominent "Leave Community" button. Clicking "Leave Community" removes all traces of the community from that person's app, including the icon in the filter panel and the listing in the communities gallery, then boots them to the home screen.

### Workaround

Remember that the community is stuck there forever in the communities gallery with no option to leave the community or remove it from the list. To remove it, I had to ask the community admin in person to re-invite me to the community, I had to accept their invite, and then I had to view the community, open its settings, and press "leave community".

### Version information

Desktop app 1.6.0 on Ubuntu 19.10.

**Comment by t3chguy** [comment]
Cannot reproduce, sounds like a server bug. Community vanished for me.

**Comment by cloudrac3r** [comment]
I can still reproduce this issue, as of just now. My homeserver is Synapse 1.17.0. The homeserver that holds the community is a different homeserver, tchncs.de.

Here's a screenshot of what it looks like for me after I am removed from a community.

cc @t3chguy 

![](https://user-images.githubusercontent.com/28467304/89525166-e9795580-d839-11ea-927f-de4e06b086d1.png)

**Comment by cloudrac3r** [comment]
This time, I managed to leave the community completely by being reinvited by the admin, restarting Element, and then declining the community invite.

**Comment by robintown** [comment]
Spaces have replaced communities
