### ISSUE TITLE
Video or Audio call has no microphone in Windows 10 but Jitsi plugin does

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#13793]
### Description
When I place a video or audio call from my installed Riot.im desktop app in Windows 10 machine there is no audio pickup from the Mic.  However if I join a conference using the Jitsi plugin in Riot.im app the mic works fine.  Another friend had the same problem.

### Steps to reproduce
-Installed Riot.im desktop app on Windows 10
-Connected Logitech C510 usb camera w/built in mic
-Started Riot.IM and created new account
-Verified the audio and video settings in Riot.IM were set for the camera
-Joined a group room and started a Jitsi conference
-Mic worked as expected
-Joined a direct chat with another user
-Placed a video call
-Mic did not work as expected
-Verify Windows permissions

There is no picked up audio in the Video Call but there is in the Jitsi Conference

Logs being sent: yes

- **Platform**: Desktop App
-Windows 10 Pro Version 1909
-Riot.IM desktop app Version 1.6.2
-OLM Version 3.1.3
-Camera and Mic are a Logitech C510 usb camera

**Comment by ariannabotaku** [comment]
Additional Trouble Shooting.
The receiving machine is a Linux Mint 19.3 Lenovo X1 4th generation Carbon with the desktop app installed.

**Comment by bwindels** [comment]
So did the video stream work in the video call? It was just the audio not working, right?

**Comment by ariannabotaku** [comment]
Yes, just the Audio.

Arianna Christina Brandstetter (They/Them/She/Her/Hers)
-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/IT d+(-) s++:++ a C++++$ UBLISXC*++++$ P++++$ L+++$ E--
W+++ N+ o K- w-- O M++$ V PS+ PE Y+ PGP++ t++ 5+++>5++++
X+ R- tv-- b+>+++ DI D+ G+ e+ h++ r z?
------END GEEK CODE BLOCK------

PGP Key: 67d5669747db913288d73aaf6965b4e4e8111ef0

**Comment by SimonBrandner** [comment]
Closing as the author of the issue seems to have deleted their account
