### ISSUE TITLE
Disabling messages to unverified sessions makes cross-signing verification impossible

### ISSUE THREAD

**Issue by Reisen** [vector-im/element-web#13794]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/158967/82765118-6a13e280-9e03-11ea-8bbe-708056ced099.png">

I would like to include a better screenshot, but it includes usernames and I do not want to expose personal information. This goes on for multiple pages of backlog.

### Description

A user in our Riot channel decided to move to another homeserver, in doing so, they tried to verify with me. I have *Never send encrypted messages to unverified sessions from this session* enabled, as do they. In order to verify they had to disable this setting for me to receive valid verification messages. There is nothing in the UI that makes this obvious. It took almost two hours of experimenting to uncover that disabling of this setting fixed the problem.

### Steps to reproduce

- Create a user on an alternate homeserver.
- Enable *Never send encrypted messages to unverified sessions from this session*
- Invite that user to a private chat room.
- Try and initiate a new verification with that user.

### Describe what happens differs from what you expected.

Expected: Verify user without pain.
Actuality: Undecryptable PMs in the form of spam.

### Version information

Latest Riot.im on MacOS

- **Platform**: web (in-browser) or desktop?

Desktop, MacOS, Latest Riot at time of writing

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/82765487-49518a00-9e0f-11ea-949d-e7eba6889007.png)

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/element-web/issues/13656 I think
