### ISSUE TITLE
New read-receipts can unstick the bottom of the timeline scroll

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1381]
I /think/ I just saw a situation where I switched to a room where the most recent message had not yet been read by anyone.  A RR then descended from the heavens... and caused the height of the event tile to slightly increase as it nestled into the msgOption div within the tile.  This caused the scroll offset to unstick from the bottom, and cause a "(v) unread messages" statusbar prompt to appear.

(There's a small chance that I may have accidentally scrolled up manually at the same time by slipping on my trackpad, but I don't think so).

**Comment by richvdh** [comment]
Ever seen this since? Can we close it?

**Comment by SimonBrandner** [comment]
Looks like this isn't a problem anymore
