### ISSUE TITLE
Clicking on an unverified user's device says the device is not trusted

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13830]
I haven't verified M4tthew yet, so all of his devices are black shields for me (as is he). However, when I click on one of his devices Riot blames him for not verifying his 'new signin':![](https://i.imgur.com/G95fqRO.png)Surely he's verified this device, I just don't know that.

**Comment by bwindels** [comment]
Yeah, I guess we should make the copy depend on whether you have verified the user or not.

**Comment by turt2live** [comment]
can't click on devices anymore
