### ISSUE TITLE
Mark rooms as read without opening them

### ISSUE THREAD

**Issue by SuperSandro2000** [vector-im/element-web#13859]
**Is your suggestion related to a problem? Please describe.**
I want to mark rooms as read without opening them.

**Describe the solution you'd like**
Telegram Desktop has an option to mark rooms as read in the context menu over a room in the left list.

**Describe alternatives you've considered**
Opening the room and scrolling down which lags the browser when you have hundreads of unread messages in a room.

**Additional context**
![image](https://user-images.githubusercontent.com/7258858/83242904-700c1980-a19d-11ea-8768-beff1fcbddea.png)

**Comment by arunsathiya** [comment]
This would be a nice feature indeed. Also related: Mark all rooms as read using a hotkey (like `Shift + Esc` on Slack)

**Comment by t3chguy** [comment]
Shift + Esc conflicts with Chrome Task Manager so is an awful choice tbh.

![image](https://user-images.githubusercontent.com/2403652/83331722-bcd01d00-a28f-11ea-823a-a52d341b7fa3.png)

**Comment by arunsathiya** [comment]
I didn't realize that was a feature, interesting!

**Comment by MyriaCore** [comment]
It should definitely be possible to mark rooms as read. At the very least it should be in this context menu:

![image](https://user-images.githubusercontent.com/35076430/105402514-8582f780-5bf5-11eb-9ba5-55cdb6778d8f.png)

**Comment by weeman1337** [comment]
In the meantime, there is a room list menu item for this → close

![image](https://user-images.githubusercontent.com/6216686/233017148-b11ce02a-4d6e-48c1-a5b1-3280c3539440.png)
