### ISSUE TITLE
CSP: a note about frame-ancestors

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#13870]
`frame-ancestors` directive is not supported in the <meta> element.
Should readme add a note for adding it on the web-server side for increasing security level?

**Comment by t3chguy** [comment]
> Should readme add a note for adding it on the web-server side for increasing security level?

Whether or not a riot instance is framable is up to the instance, some want it as a form of integration. Thus leaving it down to X-Frame-Options seems sane.

**Comment by 532910** [comment]
> Whether or not a riot instance is framable is up to the instance, some want it as a form of integration. 

Sure!

> Thus leaving it down to X-Frame-Options seems sane.

`frame-ancestors` obsoletes `X-Frame-Options`
It doesn't matter as this is an HTTP server setting, not riot-web. I meant to add a note into README.md about it.

**Comment by t3chguy** [comment]
I mean sure, but that's just Web Hosting 101. We don't currently seem to have anything about the use of `X-Framing-Options`

**Comment by 532910** [comment]
I'm about instructions for sefl-hosted riot-web, not about riot.im instance.
