### ISSUE TITLE
Room names are calculated incorrectly 

### ISSUE THREAD

**Issue by jmastr** [vector-im/element-web#13887]
### Description

```
Alright, that looks like a riot-web bug, then. They are not following the spec by not ignoring alt_aliases
```

https://github.com/Sorunome/mx-puppet-slack/issues/50
https://github.com/Sorunome/mx-puppet-slack/issues/72

### Steps to reproduce

- /

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- **OS**: macOS 10.15.4
- **URL**: https://riot.trust2core.rocks/ v1.6.2

For the desktop app:

- **OS**: macOS 10.15.4
- **Version**: 1.6.2

**Comment by t3chguy** [comment]
its a js-sdk bug if anything, but can stay here for visibility

**Comment by jmastr** [comment]
@t3chguy is that the same reason why it works in the iOS app correctly?

**Comment by t3chguy** [comment]
the iOS app is an entirely separate codebase

**Comment by jmastr** [comment]
Thought so. The maintainer mx puppet Slack bridge says: “spec says that alt_aliases must be ignored when calculating the room name, which doesn't seem to be the case here”. Does that mean anything to you? Not following the specs in this case?

**Comment by t3chguy** [comment]
The spec says `Note that clients should avoid using alt_aliases when calculating the room name.`
Note it does not say `must` so it is not in breach of the spec.

**Comment by jmastr** [comment]
Thanks for clarifying. Will forward the information.

**Comment by t3chguy** [comment]
Indeed, am not saying it shouldn't be changed, am just saying its not a spec compliance breach

**Comment by t3chguy** [comment]
> trust issues

what trust issues though? isn't `alt_aliases` controlled by room admins?

**Comment by t3chguy** [comment]
Very simple to implement by removing https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/room.js#L1843-L1849 - this needs a product decision and the be consistent between Riot apps.

**Comment by turt2live** [comment]
> what trust issues though? isn't alt_aliases controlled by room admins?

Moderators, but yes. The challenge is that they are expected to be on different servers which can more easily change where they point without ability to update them, leading to inaccuracies. It's a similar problem with the canonical alias, though much less likely (as it'd only drift in the case of abuse or server admin action). 

There's also a theory that if you want your room name to match the `alt_aliases`, you should make one of them canonical.

**Comment by jmastr** [comment]
Thanks for all the effort!

> and to be consistent between Riot apps.

Don't know where to find it in source code, but like I mentioned above Riot iOS app has this behaviour already.

**Comment by matejdro** [comment]
Just want to mention that RiotX on android also handles that properly.

Maybe this trust issue could be resolved by giving user a toggle in Room Settings that allows him to decide whether to use alt aliases or not?

**Comment by jmastr** [comment]
@t3chguy is this enough in terms of product decision?

**Comment by t3chguy** [comment]
@jmastr sorry, is what enough in terms of a product decision?

**Comment by jmastr** [comment]
@t3chguy sorry, highlighted the wrong text:

> and to be consistent between Riot apps

is there any more apps I am not aware of?

**Comment by t3chguy** [comment]
Right, but the mobile apps made the decision autonomously and it may be undesirable, so product has to make *the* decision which all Riot clients should follow

**Comment by seanfarley** [comment]
Thanks for starting the conversation, @jmastr; I, too, am seeing this behavior.

**Comment by Sorunome** [comment]
please note that leaving `alias` as null and providing an `alt_alias` gives bridges an easy way to e.g. give a DM room an alias and not have riot FUBAR the room name

**Comment by jmastr** [comment]
@t3chguy @turt2live What is the process of getting a product decision?

**Comment by t3chguy** [comment]
Waiting. Its on their TODO.

**Comment by yousefamar** [comment]
I was wondering if anything has happened on this front? Thanks

**Comment by fancypantalons** [comment]
Agreed, I'd really like to see movement on this.  Right now the Slack puppet bridge is basically unusable for me due to the broken group chat names that are a consequence of this issue.

**Comment by dreamflasher** [comment]
Currently there's an inconstency between riot web and mobile. @t3chguy If it's that easy to implement, can we just remove those lines, to make it consistent, and whenever the product people get the time (seriously they weren't able to decide this within one year‽) they can revert it.

**Comment by kittykat** [comment]
Thank you all for the reports and comments. The team at Element are making an active effort to triage and resolve these older issues and your patience is appreciated.
