### ISSUE TITLE
[feature-request] self defined alias cmds

### ISSUE THREAD

**Issue by cremesk** [vector-im/element-web#13891]
Hello,

would it be possible to introduce self-defined aliases?

suggestion:
```
/alias <list|add|del>

/alias list
/alias add <name> <value>
/alias del <name>
```

Thanks a lot!

EDIT:
eg: `/alias add hello "Hey there! Welcome to #community, how are you?"`
to use `/hello`

**Comment by Palid** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/19747
