### ISSUE TITLE
Support SSSS sharing of cross signing master key

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#13896]
We now want to transfer the cross-signing master key over SSSS sharing too, such that we can operate without SSSS storage at all.

 * Request the master key along with other cross-signing private key parts
 * Allow the master key to be shared

Related to https://github.com/vector-im/riot-web/issues/13895
Related to https://github.com/vector-im/riot-web/issues/13825

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/3346)
