### ISSUE TITLE
Move SSSS storage setup to key backup setup time

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#13895]
We now want to have cross-signing work out-of-the-box but delay setting up SSSS storage until the user has started interacting with e2e as we currently do for key backup.

 * Disentangle cross-signing and SSSS storage setup in the js-sdk
 * Create cross-signing keys automatically on login / registration if they're not present. Save all private key parts (including the master key) in the cache.
 * Delay setting up SSSS storage (and therefore recovery key creation) until later. We can use the old key backup nag screens for this (at least initially), ie. we should set up key backup and SSSS storage as one.

Related to https://github.com/vector-im/riot-web/issues/13825

**Comment by dbkr** [comment]
Blocked on https://github.com/vector-im/riot-web/issues/13581

**Comment by jryans** [comment]
Updated original comment to remove the MSK wiping step, as we appear to have agreed to keep it on all platforms.
