### ISSUE TITLE
Large tooltips/popovers can get cut off no matter the direction they pick

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13898]
Note how my bookmarks bar prevents me from searching:
![](https://i.imgur.com/05IDcEM.png)

**Comment by turt2live** [comment]
This appears to happen when neither direction is a good option ftr. If it went down, the bottom would be clipped. If it goes up, the top is clipped.

**Comment by turt2live** [comment]
an option might be to limit the number of visible rows when this happens

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7863
