### ISSUE TITLE
Shield on room can lie

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#13917]
### Steps to reproduce

- have cross signing enabled but only some of your devices verified
- create an E2E room with yourself

Describe how what happens differs from what you expected.

Shield on the room says everyone in the room is verified
<img width="38" alt="Screen Shot 2020-06-03 at 7 13 35 PM" src="https://user-images.githubusercontent.com/5855073/83701163-713eab80-a5ce-11ea-9232-c049f2915f1e.png">

but the only member of the room, which is yourself, is not actually completely verified
<img width="53" alt="Screen Shot 2020-06-03 at 7 13 38 PM" src="https://user-images.githubusercontent.com/5855073/83701159-700d7e80-a5ce-11ea-826e-ac22ef734903.png">

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: macOS
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
Cannot reproduce, I had the green verified shield then logged in with a new session:
(didn't even refresh/reopen any panels)

![image](https://user-images.githubusercontent.com/2403652/83888669-13cb6b80-a742-11ea-8ede-aa26fcab73bc.png)

**Comment by aaronraimist** [comment]
Ok I should have been more clear in the steps to reproduce. This occurred during the initial setup of cross signing. I can also reproduce it working correctly when I sign in to additional sessions now after all of my other sessions are verified.

**Comment by aaronraimist** [comment]
Going to close, haven't seen this in a while and probably not worth investigating
