### ISSUE TITLE
Guests can only join room alias via the room explorer, not via direct link. No Join as Guest button.

### ISSUE THREAD

**Issue by oehaas55** [vector-im/element-web#13945]
### Description

Guest accessible rooms can be joined via the room explorer, but not via the direct room address. There are only `Sign Up` and `Sign In` buttons to join the room with an account. There is no button to join the room as guest.

### Steps to reproduce

- create a room on a matrix server with guest access enabled
- add a local address and set it as main address (e.g. `#room:example.com`)
- set room access to `Anyone who knows the room's link, including guests`
- try to join the room as guest via direct link (e.g. https://riot.im/app/#/room/#room:example.com)

You can only `Sign Up` or `Sign In` to join. There is no `Join as Guest` button. You **can't** join the room as guest.
![image](https://user-images.githubusercontent.com/66521145/83948049-1057e300-a81b-11ea-88ea-8f5149b853de.png)
- join the room through the room explorer by typing the room address and clicking the `Join` button

You **can** join the room as guest.
![image](https://user-images.githubusercontent.com/66521145/83948108-53b25180-a81b-11ea-89a2-7e2dcda41ecc.png)

- Alternatively, try this with an existing guest accessible room from the matrix.org room directory.

### Version information
- **Platform**: web (in-browser)
- **Browser**: Firefox 76.0.1
- **OS**: Arch Linux
- **URL**: https://riot.im/app/#/room/#room:example.com

**Comment by chris-aeviator** [comment]
Also facing this and was looking for hrs already for a misconfiguration of synapse. Can someone confirm that guest access is broken in element?

**Comment by t3chguy** [comment]
> Can someone confirm that guest access is broken in element?

Element Web does not permit Guests to join rooms.
This is a product choice.


> Guest accessible rooms can be joined via the room explorer, but not via the direct room address.

this was a mistake which has since been fixed.

Related https://github.com/vector-im/element-web/issues/16164 https://github.com/vector-im/element-web/issues/3076 https://github.com/vector-im/element-web/issues/9264
