### ISSUE TITLE
Rageshake command needs to give the logs prompt

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13950]
It's extremely important that users know what is going to be included in their logs, so we should be giving them the prompt

**Comment by basxto** [comment]
Does `/rageshake` submit a screenshot like the mobile app?

**Comment by t3chguy** [comment]
Nope, that's https://github.com/vector-im/riot-web/issues/12227

Don't use issues for support, join the Matrix room.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5189
