### ISSUE TITLE
Would like to hide invites and their concomitant joins

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#13954]
**Is your suggestion related to a problem? Please describe.**
I don't need to know when people invite others to the rooms I'm in. I don't need to know when people join / leave the rooms I'm in. I want to focus on the conversation, not the ephemeral nature of IRC/matrix. One of the first things I do when setting up irssi is ignore joins, parts, quits, all that stuff. It's just noise to me.

**Describe the solution you'd like**
I'd like the "hide joins/parts" preference to hide these, or, alternately, a "no, really, I just want to focus on the conversation" option that hides *all* this stuff.

**Describe alternatives you've considered**
There are no alternatives since the software just doesn't do what I want

**Additional context**
N/A

**Comment by t3chguy** [comment]
> ephemeral

Membership in Matrix is not ephemeral, it is as burned into the Room DAG as a message is, more so even.

**Comment by anahata0108** [comment]
The correction is nice and all but I don't see how it solves the issue.

**Comment by Schnabelriechen** [comment]
While beeing i bridged room, where IRC users get invited/leave everytime the whole conversation gets spammed with "Brdige-bot ivited blabla", "Blabla joined", "blabla left".
Why are those invite messages this important? People don´t need these, so please give them an opportunity to hide them.

**Comment by MadLittleMods** [comment]
It's possible to hide all join/leave messages in the timeline with **Settings** -> **Preferences** -> **Timeline** section -> toggle the **Show join/leave messages (invites/removes/bans unaffected)** (`showJoinLeaves`) setting.

![](https://user-images.githubusercontent.com/558581/163335241-18fbcf81-9d50-4fa7-9cd3-cae97cdafae5.png)

**Comment by t3chguy** [comment]
@MadLittleMods the title of the PR is asking to hide invites too, which is specifically excluded from the preference you are suggesting
