### ISSUE TITLE
Redesign Account Notification Settings

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#13959]
https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=593%3A2447

- [x] State for master push rule inhibiting everything
- [x] Notify me with... UI
- [x] Notify me with... connected to push rules
- [x] Mentions & Keywords checkboxes
- [x] Mentions & Keywords textarea
- [ ] Sound options
- [ ] Room notification overrides list
- [ ] Per-section contextual warning if any push rules misalign
- [ ] JSON Viewer in context menu for the contextual warnings
- [x] Email notifications
- [x] Appearance options
- [x] Desktop notifications
- [ ] Verify copy

![image](https://user-images.githubusercontent.com/2403652/84840791-75d87a80-b038-11ea-8fa7-609760f80665.png)

~~Requires https://github.com/matrix-org/matrix-react-sdk/pull/4778~~

**Comment by ingingin** [comment]
Is it possible to get access to these files?

**Comment by jryans** [comment]
> Is it possible to get access to these files?

In general, we do try to share designs openly. At the moment, the designs for this project are still evolving rapidly, so for now the Design team would prefer to keep them private until they are ready to share.

**Comment by timokoesters** [comment]
I didn't see anything about display name push rules, is that just a keyword now?

**Comment by t3chguy** [comment]
`mentions`

**Comment by timokoesters** [comment]
That's the userid, not the displayname though, right?

**Comment by t3chguy** [comment]
That'll be for @richvdh to determine when he plots out which push rules each of the radios wires up to :D

**Comment by auscompgeek** [comment]
Personally, I would like to keep username and display name push rules as separate options, since `david` is a pretty common name…

**Comment by richvdh** [comment]
the intention here would be that there would be a single switch for "mentions". People that find that gives too many false positives can turn the switch off and add keyword rules instead.

**Comment by auscompgeek** [comment]
Right. I actually want to keep the display name rule enabled though, since that's not replicable with keywords if you have different display names in different rooms.

**Comment by t3chguy** [comment]
Very good point!

**Comment by richvdh** [comment]
[internal docs for this project are/were at https://drive.google.com/drive/u/2/folders/1NjX0aYIU_OtoypKo3kucBOiEkLvXrHIz]

**Comment by turt2live** [comment]
Closing as we've done a lighter weight UI refresh for now. If we do a more involved one in the future, we can refer back to the work here.
