### ISSUE TITLE
Notices for reactions/editions/deletions

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#13967]
Sometimes people act upon messages that are way up in the timeline.  Yet, one might be interested in those - and for editions a notification may appear, triggering interest.  There ought to be notices in the timeline (maybe switched off by default) mentioning these events, and containing a link to them - the way they are for changes of name or avatar, or joins, and so on.

**Comment by turt2live** [comment]
Effective duplicate of https://github.com/vector-im/element-web/issues/9792
