### ISSUE TITLE
Redesign Room Notification Settings

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#13960]
https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=593%3A3302

- [x] State for master push rule inhibiting everything
- [x] Notify me with... UI
- [ ] Notify me with... connected to push rules
- [ ] Per-section contextual warning if any push rules misalign
- [ ] JSON Viewer in context menu for the contextual warnings
- [x] Appearance options
- [x] Sound upload section
- [ ] Verify copy

**Comment by MadLittleMods** [comment]
Closing as this looks like was tracking a TODO list that never happened.

And this is now being iterated in a new sprint as ["Get your updates (GYU)"](https://github.com/vector-im/element-web/issues?q=is%3Aopen+is%3Aissue+label%3AZ-GetYourUpdates)

For example:

 - https://github.com/vector-im/element-web/issues/24512
 - https://github.com/vector-im/element-web/issues/24511
