### ISSUE TITLE
"Re-join" button on the "You were kicked" footer gives no feedback

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#13969]
Apparently it works, because it eventually joined me, but at spinner or something would be nice.

**Comment by ilmari** [comment]
This just happened to me too, and not only did the button give no feedback, I had to clear cache and reload for Element Web to notice that the rejoin had succeeded.

**Comment by aaronraimist** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/24598 which has a screen recording and more labels.
