### ISSUE TITLE
Issues with registration flow remain in 1.6.4

### ISSUE THREAD

**Issue by the-moog** [vector-im/element-web#13979]
# Description

Issues like this have been reported before and behaviour HAS changed in recent Matrix/Riot releases with some improvement.
But it's still far from user friendly and for a new user that's the whole point.
As I have found to huge cost, a bad first impression puts them right off Riot/Matrix.

Please confirm my expected behaviour is what devs also intend, or am I expecting the wrong results?

### Steps to reproduce
Repeat on privately hosted Matrix/Riot server.

- Open a new private browsing browser window (to prevent previous sessions screwing things up)
- Invite a user by email from Riot/Desktop
- I use gmail address extension, e.g. my-user+test1234@gmail.com
- Matrix sends invite email
- Open email and click link, tab opens in browser.
Note: email field is now filled correctly - yay, thank you!
- Enter new userid, password and confirmation
- X: Riot displays an email sent message
- Matrix sends a validation email.
FYI: validtion link looks like 
https://matrix.myserver.com/_matrix/client/unstable/registration/email/submit_token?client_secret=LKB...setE14dsRxJg&sid=ljXfxmN...aJq&token=hdDrwpPySj...FELGLB 
- Click the validation link in email, new tab opens in browser.
- Existing tab ('X', above) now says Registration Successful, login

### What happens:
Existing tab (X, above) Invites the user to login "Registration Successful"
New (and focused) tab goes back to the "Create your account" page, but freezes, only half drawn with a spinning circle.

### What should happen:
A 2nd tab should not open and certainly should not freeze.
Existing tab should log in as an authentication token was passed rather than presenting the sign-in page.

In Matrix/Riot of about 2 years ago this used to work.

Logs being sent: no

![firefox_90f6uJSoKa](https://user-images.githubusercontent.com/3725802/84282470-b2384200-ab31-11ea-8523-4ed35b43ea70.png)

### Version information

- **Browser**: Firefox 77.0.1
- **OS**: Windows10
- **Riot**: Riot/Web + Riot/Desktop 1.6.4
- **Matrix**: 1.14.0

**Comment by turt2live** [comment]
I'm not able to reproduce this particular failure mode anymore, so assuming it is fixed. The number of clicks involved is still the same, however there are plenty of other issues to track this.

**Comment by anushaharish538** [comment]
Hi, @turt2live  Is it fixed. Its still happening for me.
