### ISSUE TITLE
Can not use desktop client in China

### ISSUE THREAD

**Issue by hydrandt** [vector-im/element-web#13988]
### Description

When attempting to log into Riot Windows or Mac in China, it is not possible to get to the login screen and change server to one that is not blocked (both riot.im and matrix.org are not accessible in China).

### Steps to reproduce

- Download latest Riot release for Mac or Windows
- Install
- Open

Error message: 

Your Riot is misconfigured 

Invalid homeserver discovery response

![55905877](https://user-images.githubusercontent.com/11388094/84342864-3691d000-abd9-11ea-99db-e300b18d63e1.jpg)

### Version information

- **Platform**: desktop
- **OS**: Windows, macOS
- **Version**: 1.6.2

**Comment by AnonymousWebHacker** [comment]
Prueba usando un VPN y verifica, seguro por politicas, esta cerrado para china [spanish]

**Comment by jryans** [comment]
Thanks for the report. At the moment, we have some strict validation in place that does indeed check whether matrix.org is reachable. We're reviewing that behaviour at the moment, so we'll keep this symptom in mind as part of that.

**Comment by GammaPi** [comment]
> Thanks for the report. At the moment, we have some strict validation in place that does indeed check whether matrix.org is reachable. We're reviewing that behaviour at the moment, so we'll keep this symptom in mind as part of that.

Some users use personal servers. This restriction will prohibit them from logging into their home server since no login page is shown.

**Comment by mytbk** [comment]
I can still see this problem in a fresh installed Arch Linux using the element-desktop package. The only way to solve this is to modify the config file.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/11154

**Comment by AsceticBear** [comment]
> I can still see this problem in a fresh installed Arch Linux using the element-desktop package. The only way to solve this is to modify the config file.

I encountered the same problem, did you know how to modify the config file to avoid this problem.
