### ISSUE TITLE
Leaving a DM before the other participant has accepted the invite should withdraw the invite

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#13998]
I've been getting a few occurrences of someone inviting me in a DM then leaving the room before I've accepted the invite, causing me to stumble into an empty room upon accepting the invite, which is pretty confusing. It'd be great if the client withdrew the invite when the user leaves the room.

This is also a server bug, but implementing it on the server would probably require [MSC2199](https://github.com/matrix-org/matrix-doc/blob/travis/msc/immutable-dms/proposals/2199-canonical-dms.md) (canonical DMs) to happen as otherwise we don't have a good definition of what a DM is server-side.

**Comment by t3chguy** [comment]
In a DM we don't have permission to de-invite someone as we cannot Kick someone with the same PL.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/2212

**Comment by babolivier** [comment]
Oh that's right, I forgot about that. Ugh.

**Comment by t3chguy** [comment]
If you still care about this I suggest opening an issue in https://github.com/matrix-org/matrix-spec
