### ISSUE TITLE
Reset keybackup is failing with crosssigning/4S configured

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#13992]
https://github.com/matrix-org/riot-web-rageshakes/issues/2990

My account has cross signing and backup enabled (probably from migration flow)

Step to reproduce

1) Go to settings > Security
2) Tap on Delete Keybackup
3) Now Tap 'connect this session to keybackup' 

=> Web is prompting me for recovery passphrase

<img width="455" alt="image" src="https://user-images.githubusercontent.com/9841565/84383286-5088de00-abec-11ea-8643-ac896a764885.png">

My passphrase is correct but I get the following error
<img width="803" alt="image" src="https://user-images.githubusercontent.com/9841565/84383332-639bae00-abec-11ea-9ec6-4940f750265f.png">

Which is strange because I am not trying to decrypt any backup, just want to generate a new one

**Comment by jryans** [comment]
@BillCarsonFr Unfortunately, I don't see anything obvious in the logs, so I am a bit unsure what to do with this one. We have landed a few tweaks on develop recently, are you able to retest?

**Comment by jryans** [comment]
I suspect this has been fixed with other reset fixes in 2020.
