### ISSUE TITLE
Power level edit-button nearly invisible on :hover

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#14001]
In riot-web 1.6.4, when hovering the edit-button next to the power levels in some room, the following css gets active:

```
.mx_IconButton:hover {
  opacity: 1%;
}
```

Assuming that’s some bug, right? As the icon/button is not visible on :hover …

<img width="273" alt="Screenshot 2020-06-12 at 14 53 21" src="https://user-images.githubusercontent.com/11408027/84504600-82697580-acbc-11ea-99cc-e7bff1909d52.png">

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/b278531f2fbabfdee31bd46434f30f9e462e56ea/res/css/views/elements/_IconButton.scss#L34
The code here sets it to 90%
I am not sure where your 1% is coming from.

**Comment by yannicka** [comment]
I've the same issue on Element Web 1.7.1 (Firefox 78) and Element Desktop 1.7.1.

**Comment by daniel-nk** [comment]
I see the same behaviour in element-web 1.7.2 and element desktop 1.7.2. It would be useful to know where this can be changed (I can't find that scss file on my webserver) because the icon was hardly visible for me to begin with and it becomes virtually invisible on mouseover.
