### ISSUE TITLE
Substring search doesn't work in encrypted rooms.

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#14018]
While searching `Marvell` in encrypted room works fine, `Marvel` gives zero results.

**Comment by t3chguy** [comment]
Is this an encrypted or unencrypted room? If unencrypted then its server-side search and depends on the implementation your server is using.

**Comment by 532910** [comment]
encrypted

**Comment by 532910** [comment]
For unencrypted it works fine.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/1479
