### ISSUE TITLE
Search failed for quoted string in an encrypted room

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#14016]
I got 
```
Search failed
Index error: An invalid argument was passed: 'Query is invalid. SyntaxError'
```
trying to search `"hell"` in an ncrypted room while for All Rooms it works fine.

riot-electron 1.6.4 from https://packages.riot.im/debian sid

**Comment by t3chguy** [comment]
Is the room encrypted or not?

**Comment by 532910** [comment]
encrypted, for unencrypted it works fine

**Comment by novocaine** [comment]
Fixed by https://github.com/matrix-org/seshat/pull/104

**Comment by t3chguy** [comment]
Closing as fixed

**Comment by 532910** [comment]
Can confirm it works fine now! Thank you!
