### ISSUE TITLE
Ctrl+F should start search

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#14027]
Ctrl+F is a standard hotkey for search in most applications that have search.

**Comment by t3chguy** [comment]
Doing this in a browser is horrendous as it makes Find-in-page which is also an accessibility feature hard to reach.

Plus clashes with https://github.com/vector-im/riot-web/issues/2764

**Comment by sirocyl** [comment]
As this was the issue I found when reporting this/making a +1, I'd like to link a pointer over to #15816 for further discussion.

**Comment by SimonBrandner** [comment]
We have this now, it just has to be turned on Preferences
