### ISSUE TITLE
Direct Message room detection logic not in sync with the spec

### ISSUE THREAD

**Issue by gnieto** [vector-im/element-web#14046]
### Description

Direct Message (DM) rooms are not detected on Riot according to the spec. According to the spec, the unique requirement for servers is set the `is_direct` flag on the invite "m.room_member" event (https://matrix.org/docs/spec/client_server/r0.6.1#id140).

I was checking why riot was not marking rooms as DM when using Conduit (https://conduit.rs) and I've found that it requires that `prev_sender` is stored on the event unsigned data. The specific block code that does this check is this one: https://github.com/matrix-org/matrix-js-sdk/blob/505915528f4b0c2e0a56809675529cd8d418508f/src/models/room-member.js#L227-L238.

I couldn't find any reference to `prev_sender` on the matrix spec (except for an example), but maybe I missed something. Also, it's not clear for me if the prevContent should be present on the "join" event or not, or if setting the `is_direct` flag on invite event should be enough.

I was not sure if this was the appropiate repository to open the issue. If it isn't, please let me know where i should open the issue .

### Steps to reproduce

- Create a Direct room on Riot with a Conduit homeserver

The created room is shown on DM on creators Riot. When the invited user accepts the DM, it's shown as a generic room (instead of DM) on invited user's Riot. This also mean that `m.direct` account data on invited user is never updated with the create room id.

### Version information

- **Platform**: web 
- riot-web docker image (vectorim/riot-web:v1.6.4)

**Comment by t3chguy** [comment]
Likely this won't get fixed until the Canonical DMs MSC.

**Comment by notfoss** [comment]
For the record, I just experienced this on RiotX Android (using chat.privacytools.io).

Confusingly, it showed up under direct messages for my contact, but for me, it showed up under rooms.

**Comment by turt2live** [comment]
I believe we fixed this. If not, please open a new issue with fresh information.

**Comment by gnieto** [comment]
Looking at the code on matrix-js-sdk, it seems that the logic has not changed. It still relies on checking the `prev_sender` flag. See: https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/room-member.ts#L270-L294

Apparently it's working on conduit now because they add the `prev_sender` field. Anyway, I could not find any reference to this field on the spec. My impression is that the issue should be re-opened, because it's still unaligned with the spec (or adapt the spec to reference the prev_sender field).
