### ISSUE TITLE
Extra verification request came in after verifying a new riot-web from an existing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#14068]
Started up a new riot.im/app on my account, and tried to verify from an existing riot.im/develop.

Verification went smoothly, but after I verified both emoji, the new Riot-web had an unactionable "Incoming verification request" dialogue simply filled with a spinner on top of the "Verification succeeded!" message. I closed the request dialogue, and could continue, but it shouldn't be there in the first place.

Unfortunately I wasn't able to get a bug report from the new device, but I do have one from the existing device.

Firefox Nightly v79.0a1, Linux. Both instances were on the same computer.

**Comment by MightyCreak** [comment]
I have the same issue, and it's reproducible (thus the first step). As explained on Matrix, here are my steps to reproduce:
1. I revoke the session that doesn't work
2. I log in again (on Riot desktop)
3. I am asked to verify my connexion
4. I take another verified device (RiotX on my tablet)
5. I find my newly connected device with a red shield and select on it
5. I start the verification with emojis
6. I validate the emoji list
7. My tablet says my new session is now verified; I click on "Finish"
8. But on my desktop app, my new sessions is stuck here:
![image](https://user-images.githubusercontent.com/6382548/85048819-dadbbf80-b161-11ea-82bc-628990eb7fd5.png)

**Comment by kittykat** [comment]
@anoadragon453 Could we close this one or are you still getting it?

**Comment by anoadragon453** [comment]
Indeed. Just tried again from two Element Web sessions (Element version: ef9335697e05-react-b8355883313e-js-6fc586598a98
Olm version: 3.2.8), Firefox, same computer and verified with no issues. Steps were:

- Log into one Element Web, resetting and setting a new security phrase.
- Log into another Element Web.
- Initiate verification from the second, and accept from the first.
- Complete emoji verification, both shields match.
- The second Element Web is now verified, with no stuck modals or annoying notifications.
