### ISSUE TITLE
Default Output Device Resets When Switching Rooms

### ISSUE THREAD

**Issue by monstro1** [vector-im/element-web#14119]
### Description

My output device resets when switching rooms. Also, if I switch my output device while in a call, the changes don't take effect unless I leave the call and rejoin.

### Steps to reproduce

- I open my settings and go to Voice & Video
- My audio output is _Default - Speakers (Yeti Stereo Microphone)_
- I change the audio output to _Speakers / Headphones (Realtek High Definition Audio)_
- I exit out of settings.
- I enter a different room to the one I was in and open my Voice & Video settings
- My default audio device has been switched back to _Default - Speakers (Yeti Stereo Microphone)_

I had assumed that perhaps my audio settings were tied to the room I was in, but that doesn't seem to be the case. If I change my settings while in Room A, go into Room B, then immediately back into Room A, my audio settings still reset. Also, this isn't entirely related, but I think there desperately needs to be an "Apply Changes" button, as I wasn't even actually sure if my settings were saving most of the time.

### Version information

- **OS**: Windows 10
- **Version**: 1.6.5

**Comment by ara4n** [comment]
This was Riot Desktop i think?

**Comment by monstro1** [comment]
Yes, the desktop version. The browser version doesn't have this issue.

**Comment by ara4n** [comment]
what sort of call is it? a 1-to-1 call, or a multiparty conference?

**Comment by monstro1** [comment]
Sorry for the late reply. A 1 on 1 call.

**Comment by 532910** [comment]
Looks like I have the same issue. riot-electron 1.6.6 debian sid.

**Comment by progserega** [comment]
Also have such bug on ubuntu 16.04:
`riot-desktop                                  1.6.6                                                    amd64 `

**Comment by SimonBrandner** [comment]
Is this still an issue for you?

**Comment by monstro1** [comment]
> Is this still an issue for you?

no, although i'm not using windows anymore so i couldn't tell you if the issue persists there

**Comment by SimonBrandner** [comment]
Then I think I am going to close, shout if you ever see this again
