### ISSUE TITLE
Replies to /me formatted incorrectly

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#14166]
### Description

Messages that don't display the user name in the usual manner (i.e. at least `/me does something`) mess up the formatting when replied to. Note the timestamp overlayed on the avatar when it should be below.

For example: 
![image](https://user-images.githubusercontent.com/2803622/85467923-159f8680-b5ac-11ea-9dbb-cf0a2673a1e3.png)

(https://matrix.to/#/!AnacGSwlCZcUuAfcEU:matrix.org/$SccGH9_De9Boael7YvVQbmvbR3l7Cr21bbYnLTZzfMQ?via=matrix.org&via=privacytools.io&via=mozilla.org)

### Steps to reproduce

- see description

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.6.6

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3553
