### ISSUE TITLE
Add command to scroll back to specific time, or by relative amount of time

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/element-web#14173]
**Is your suggestion related to a problem? Please describe.**
It's quite annoying to catch up on backlog or refer to old messages. I've just recently run into an issues where replying to an old message sent me back to the present. After minutes of scrolling and waiting for loading, I still can't get back. I'd intended to read and reply to things in the order they happened from the last couple days.

**Describe the solution you'd like**
Something like irssi's scrollback command. You can do `/scrollback goto 22:11` and have it jump back so that the stated timestamp is at the top of your window and you can start reading from there. You can also do `/scrollback end` to instantly jump back to the bottom. Having some similar commands I could run in Riot would be very very nice. For relative scrollback we can look at weechat where you can do something like `/window scroll -24h` or `/window scroll -10d` to go back 24 hours or 10 days, respectively. Having both options (absolute and relative) of backtracking would be ideal, but if there's a problem getting timezone info, relative stuff could still work.

**Describe alternatives you've considered**
Something graphical in the UI could be another option, though I imagine it being harder to implement well without looking sloppy. Maybe just show a small calendar where you can click any day of the current month or change month/year with an arrow. (if going this route, I suggest not making someone go back month by month to change the year, this is a common problem in calendar UI)

**Comment by jryans** [comment]
Related to browsing by date: https://github.com/vector-im/riot-web/issues/7677

**Comment by MadLittleMods** [comment]
`/jumptodate 2022-01-01` was added in https://github.com/matrix-org/matrix-react-sdk/pull/7372

(please close this issue)
