### ISSUE TITLE
New room list: State for unsent message: "error" icon next to room name

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14181]
> "It would be anazing to have a state for unsent messages too as it often happens when the server is dying that we have unsent msg in a room and don't notice. It could be the same icon tbh (file upload fail)" ALP

**Comment by niquewoodhouse** [comment]
For context, the middle below is the icon being referred to.  

- Row 1: File uploading
- Row 2: File upload fail

<img width="488" alt="Screenshot 2020-07-01 at 14 26 01" src="https://user-images.githubusercontent.com/1587166/86249313-08375d00-bba7-11ea-8f7e-75e1b6f3ee24.png">

I'm not sure if this should be in this position, or next to the avatar (see below) as with the context menu/notification icons appearing on hover, the user wouldn't be able to know what the error means (by hovering for a tool tip).

<img width="828" alt="Screenshot 2020-07-01 at 14 52 16" src="https://user-images.githubusercontent.com/1587166/86252271-e7710680-bbaa-11ea-83a2-466e9a18bea0.png">

I think a better solution to this might be to have a global notifications center, that lets the user know when something erroneous has happened with their message/uploads.

Interested in your thoughts @nadonomy

**Comment by turt2live** [comment]
ftr we have this already, but it's obviously not great:

![image](https://user-images.githubusercontent.com/1190097/129390084-26d699fd-8996-4e90-b206-9d2c7f294021.png)

**Comment by Palid** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/14181
