### ISSUE TITLE
Change 'set up secure backup' copy for backup reset

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#14190]
The screens for setting up secure backup have different copy and different danger-level of buttons when they're resetting an existing backup rather than creating a new one, although they refer specifically to resetting the *backup* and *not* cross-signing. Once we can reset the backup and *not* cross-signing, we should update the copy.

**Comment by kittykat** [comment]
@dbkr we can't figure out which screen this is about, could you expand or close please?

**Comment by richvdh** [comment]
closing this pending relevant information
