### ISSUE TITLE
Styling for checked and disabled checkboxes and radiobuttons

### ISSUE THREAD

**Issue by JorikSchellekens** [vector-im/element-web#14204]
This is to track design's final decision on checkable inputs once the design kit is reviewed. Currently the options are:

- muted accent color
![image](https://user-images.githubusercontent.com/23084468/85731140-29ed9b80-b6f2-11ea-84c0-3a879da4503a.png)

![image](https://user-images.githubusercontent.com/23084468/85731121-265a1480-b6f2-11ea-9d70-7b8f193ca22b.png)

- muted fg color
![image](https://user-images.githubusercontent.com/23084468/85731428-6c16dd00-b6f2-11ea-966c-aca2fb02d898.png)

![image](https://user-images.githubusercontent.com/23084468/85731436-6d480a00-b6f2-11ea-866d-51175388a6e1.png)

Note: disbaled inputs have `cursor: not-allowed` on them

**Comment by t3chguy** [comment]
Bootstrap does the latter

![image](https://user-images.githubusercontent.com/2403652/85732099-01b26c80-b6f3-11ea-9ec4-75f8f42a4527.png)

UIKit does the latter

![image](https://user-images.githubusercontent.com/2403652/85732278-26a6df80-b6f3-11ea-800c-e3fc8b389b71.png)

Semantic UI doesn't do colours at all

![image](https://user-images.githubusercontent.com/2403652/85732509-57871480-b6f3-11ea-9923-6e74341a7dfa.png)

Material React UI does the latter

![image](https://user-images.githubusercontent.com/2403652/85732828-9917bf80-b6f3-11ea-8b60-8cab7b117171.png)

**Comment by JorikSchellekens** [comment]
I have a bet on typo'd branch joriks/check-disbaled-input. Book's open, ante 50c.

**Comment by nadonomy** [comment]
@JorikSchellekens in lieu of doing independent research, I think we'd be wise to just stand on the shoulders of Bootstrap, UIKit & Material and follow suit with desaturated disabled states.

**Comment by JorikSchellekens** [comment]
@t3chguy have we actioned this?

**Comment by t3chguy** [comment]
Not yet

**Comment by JorikSchellekens** [comment]
On my todo

**Comment by t3chguy** [comment]
@germain-gg's work on compound will bring us perfect checkboxes and radio buttons

**Comment by germain-gg** [comment]
Closing as compound implementation will be the future of checkboxes and radio buttons. 

See https://compound.element.io/?path=/story/compound-web_checkbox--primary for example. This will be rolled out on web in the coming months
