### ISSUE TITLE
App will not verify new device

### ISSUE THREAD

**Issue by merrpink** [vector-im/element-web#14217]
### Description

I have added a new device. On my laptop app there is now a little sign that says to verify the new device. I click yes, then a popup comes that gives me the device code. I click ok, verify. The popup spins a bit then says, "Waiting for you to accept on your other session…"  Nothing ever comes to my other device and the popup does not stop spinning until it times out. Nothing happens and nothing gets verified.

On my other device, I click "fetch keys" from one of the "unable to decrypt" messages, and it says "getting keys" but nothing happens. I am unable to verify my new device. I've tried about 10 times.

### Steps to reproduce

Try to verify new device on my machine is the only way to reproduce.

Describe how what happens differs from what you expected.
I expected it to verify with the first attempt.

Log: sent/not sent?    

### Version information
Latest

- **Platform**: web (in-browser) or desktop?
Linux desktop and android is the other device.
For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 
Ubuntu 20.04 Desktop version
riot-web version: 1.6.6
olm version: 3.1.3

**Comment by lgblgblgb** [comment]
The very same problem here. Just mentioning, because slightly different version:

Ubuntu 20.04 desktop, 64 bit, DEB packages: riot-desktop version: 1.6.8 , libolm3 version: 3.1.3

**Comment by jryans** [comment]
A lot has changed since this was filed, and as far as I can see, log were not sent at the time. If anyone is still experiencing such issues, please file a fresh issue and send logs as well.
