### ISSUE TITLE
Add the abiliity to rageshake to the feedback popup

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#14222]
it will probably bring much more feedback (and higher quality feedback) than having to deal with github, esp for people not used to github. Conscious this is a question tto desiign too

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/13823
Related https://github.com/vector-im/riot-web/issues/12415

(Help got renamed to Feedback as part of new room list stuff I believe)

**Comment by t3chguy** [comment]
This is now done
