### ISSUE TITLE
Seshat DB error disables search on desktop

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#14229]
### Description

>Message search
>Riot can't securely cache encrypted messages locally while running in a web browser. Use Riot Desktop for encrypted messages to appear in search results.

Message search is disabled although I'm using the riot-desktop app.
This worked when the feature was introduced. I recently enabled labs settings on desktop by adding the respective file `%appdata%/Riot/config.json`, which is my best guess as to what might have messed things up, although my impression is that it shouldn't have. `config.json` contents:

```
{
    "default_server_name": "myserver.url",
    "brand": "some name",
    "features": {
        "feature_font_scaling": "labs",
        "feature_pinning": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_state_counters": "labs",
        "feature_many_integration_managers": "labs",
        "feature_mjolnir": "labs",
        "feature_dm_verification": "labs",
        "feature_bridge_state": "labs",
        "feature_presence_in_room_list": "labs",
        "feature_custom_themes": "labs",
        "feature_new_room_list": "labs",
        "feature_irc_ui": "labs"
    },
    "showLabsSettings": true
}
```

### Steps to reproduce

- install riot desktop
- customize `config.json`

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.6.6

**Comment by jryans** [comment]
@HarHarLinks If you temporarily move the custom config out of the way to test the default and restart, what behaviour do you see?

**Comment by HarHarLinks** [comment]
I renamed the file and restarted. It still displays the same message, nor does search seem to work.

**Comment by jryans** [comment]
The log seems to say:

```
2020-06-28T10:41:26.443Z I EventIndex: Error initializing the event index {"message":"Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: \"Invalid MAC\" } }))"}
```

@poljar, any suggestions on how best to resolve that?

**Comment by poljar** [comment]
Deleting the `EventStore` folder is always an option. I wonder what happened to the index files that the MAC doesn't match anymore.

**Comment by HarHarLinks** [comment]
I renamed `EventStore` temporarily to test this and it works, even with the custom `config.json`. Would deleting `EventStore` delete anything other than seshat data, or am I save to do that?
Is there any more info I can provide about this issue?

**Comment by poljar** [comment]
It only contains Seshat data and it will get rebuilt from the data from the server. Nothing valuable is lost.

A indexer file got somehow corrupted could be by a unclean shutdown, not sure. There's not much to investigate here since we don't have specific logs for this as it's deep in the belly of Seshat. We could offer a better UI for when this happens though.

**Comment by ScottRochford** [comment]
Multiple users in our organisation have had the same problem, including myself.  Removing `EventStore` also fixed it for me.

Currently running Element 1.7.13 with a custom `config.json`.

Another thing I noticed was that before fixing it "Use the Desktop app to search encrypted messages" was displayed under the search field (despite the fact that I'm using the Desktop app), and after applying the workaround that message is gone.

**Comment by jryans** [comment]
> Another thing I noticed was that before fixing it "Use the Desktop app to search encrypted messages" was displayed under the search field (despite the fact that I'm using the Desktop app), and after applying the workaround that message is gone.

Yes, it's quite confusing that indexing errors currently make the desktop app say "use desktop"... 😖 We have https://github.com/vector-im/element-web/issues/15168 to track this aspect.

**Comment by jryans** [comment]
@poljar What would be a good way to help people here? Maybe a toast that ask permission to delete and rebuild the index...?

**Comment by poljar** [comment]
> @poljar What would be a good way to help people here? Maybe a toast that asks permission to delete and rebuild the index...?

Yes that does sound sensible.

**Comment by anna2828** [comment]
P2

**Comment by Yajo** [comment]
For whoever comes here, the fix is:

1. Exit Element with <kbd>Ctrl</kbd>+<kbd>Q</kbd>
1. `rm -Rf ~/.config/Element/EventStore`
1. Enter Element again.

**Comment by jryans** [comment]
For those affected by this, does it just happen out of nowhere with seemingly no other changes, or did something else change e.g. you logged in again for the first time in a while...?

**Comment by Yajo** [comment]
It was a friend, with Element just installed for the 1st time. He tried both flatpak and .deb versions, and the same happened with both.

**Comment by jryans** [comment]
Hmm, thanks for the detail. I wonder if there's some race condition in the Seshat init path that is setting things up with e.g. a bad database key or similar...

**Comment by MadLittleMods** [comment]
Reproduced this installing Element Desktop version 1.7.16 for the first time on macOS 10.15.7. I can also reproduce on Windows 10 (first time install).

Trying to use search -> `Use the Desktop app to search encrypted messages`

Settings -> Security & Privacy ->Message search
```
Message search
Element can't securely cache encrypted messages locally while running in a web browser. Use Element Desktop for encrypted messages to appear in search results.
```

How do I find the logs that show `IndexError` error mentioned above?


---

It might have been a coincidence but after starting it manually from the package contents binary in the terminal, search started to work. Before that, I did try restarting the app multiple times from the normal spotlight launcher but was broken each time.

```
$ /Applications/Element.app/Contents/MacOS/Element
/Users/eric/Library/Application Support/Element exists: yes
/Users/eric/Library/Application Support/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
```

Given that I did the same on Windows 10 and didn't fix the problem, I am leaning toward coincidence and race condition.

```
$ "C:\Users\MLM\AppData\Local\element-desktop\app-1.7.16\Element.exe"
Starting auto update with base URL: https://packages.riot.im/desktop/update/
(node:18016) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by HarHarLinks** [comment]
Happened again, Windows 10 20H2, up to date Element Desktop that had been installed for some weeks. Deleting EventStore helped.

**Comment by geckolinux** [comment]
> Deleting the `EventStore` folder is always an option. I wonder what happened to the index files that the MAC doesn't match anymore.

Thanks! This fixed it for me.

@jryans 
> For those affected by this, does it just happen out of nowhere with seemingly no other changes, or did something else change e.g. you logged in again for the first time in a while...?

Just out of nowhere. I have Element running all day every day. It appeared to correspond to one of the recent X.y.z point releases, but might have been unrelated.

**Comment by progserega** [comment]
>     2\. rm -Rf ~/.config/Element/EventStore

not help me on Element-desktop: 1.7.17
ubuntu 16.04 amd64

**Comment by jryans** [comment]
@progserega Did you also check also names for the directories, such as Riot as well?

**Comment by lampholder** [comment]
I experienced this issue, too. Just 'cause it took me a little while to find it, on Windows 10 the folder I needed to remove was located at `C:\Users\lamph\AppData\Roaming\Riot Nightly\Event Store`

**Comment by jaywink** [comment]
Got hit by this too, Element nightly (Ubuntu) 2021012001

Confusingly, `~/.config` has two nightly folders:

```
Element Nightly/
Element-Nightly/
```

`Element-Nightly` seemed to be the right one and deleting `EventStore` under there got rid of the "use desktop" warning.

**Comment by poljar** [comment]
Nightly had an issue which corrupted the db, the issue was caught before it went into a release.

**Comment by geckolinux** [comment]
@poljar I've never run Nightly though, only release versions.

**Comment by poljar** [comment]
Ah sorry, this was a direct comment for @jaywink. The db can get corrupted for other reasons as well.

**Comment by geckolinux** [comment]
@poljar Ah ya, gotcha. Well at least for me it still seems to be working fine after I fixed it [4 days ago](https://github.com/vector-im/element-web/issues/14229#issuecomment-761814293).

**Comment by progserega** [comment]
> @progserega Did you also check older names for the directories, such as Riot as well?

I try remove all:
```
 $ rm -Rf ~/.config/Riot/EventStore
 $ rm -Rf ~/.config/Ele/EventStore
Element/        Element (Riot)/ 
 $ rm -Rf ~/.config/Element/EventStore
 $ rm -Rf ~/.config/Element\ \(Riot\)/EventStore
```
not help :-(

**Comment by cryptid11** [comment]
removing the folder EventStore:
on linux says `request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/search`
on windows simply doesnt work
