### ISSUE TITLE
Widget UX - possible quick wins

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#14230]
- [ ] Remove the maximum width limitation
- [ ] Make drawer resizable vertically
- [ ] Make each widget resizable horizontally
- [ ] Remove (or increase from two) the widget limit
- [ ] Move the 'minimize widget' UX from the widget to the drawer

Stretch goal:
- [ ] Try and persist the relative sizings of the widgets and drawer such that they can be restored when you return to the room (or when you close/open the drawer)

I tried mangling this behavior together using CSS alone (flexbox + resize:vertical/horizontal), with [some success](https://matrix.lant.uk/_matrix/media/r0/download/lant.uk/sofPzOBKQZrdsVMjVcvZFzzv). The only functionality flaw was that dragging the resize handle often dropped the handle mid resize.

**Comment by GuidoAdam** [comment]
Releated: [https://github.com/jitsi/jitsi-meet/issues/5416](https://github.com/jitsi/jitsi-meet/issues/5416)

**Comment by turt2live** [comment]
Through a number of other issues and trackers, this is covered elsewhere.
