### ISSUE TITLE
User Info "Back" Button is labelled as "Close"

### ISSUE THREAD

**Issue by Blumlaut** [vector-im/element-web#14239]
## Description
When viewing a user on the Right "Members" Sidebar, the Design Language says that you are moving pages via a `>` and `<` Button, however, when hovering over the "back" button on someone's profile, the tooltip will say "Close", implying that it would close the whole sidebar, not go back a page, i would consider changing this to "Back" instead.

![](https://flausch.biz/jtirg/j02yn.png)
![](https://flausch.biz/ia11e/s9qta.png)
![](https://flausch.biz/7w454/sgzqp.png)

**Comment by jryans** [comment]
Seems reasonable enough to me, I'd welcome anyone to submit a PR to update it.

**Comment by t3chguy** [comment]
The issue there is sometimes there is no MemberInfo behind it, where you might open the User Info panel from the timeline when the Right Panel was collapsed. So it would have to be conditional as `Back` doesn't make sense for that situation.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5167
