### ISSUE TITLE
New room list: Badge counts and badge behaviour (FTUE notifications)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14261]
Placement TBD

**Comment by nadonomy** [comment]
We're not able to port over any of the WIP notiications work without MSC2654, so suggest we just follow todays decoration logic for badges etc per the [notifications proposal](https://github.com/vector-im/riot-web/issues/13961#issuecomment-651902498), with the addition of us just displaying a dot whenever we're bolding the font weight too to help the eye read unreads.

**Comment by turt2live** [comment]
Re-scoped to handle more than the badges: also includes things like red for DMs automatically, when and when not to show counts, etc.

**Comment by turt2live** [comment]
Removing this from the room list tracking: it's squarely in the notifications track now.

**Comment by daniellekirkwood** [comment]
Given the lack of description/clarity here, and our updates to the panel and notifications in general, I'm going to close this issue. If you think it needs to be open, feel free to re-open with the info I'm missing :)
