### ISSUE TITLE
Uploaded image aspect ratios are not preserved in chat.

### ISSUE THREAD

**Issue by flackr** [vector-im/element-web#14284]
### Description

The rendering of images in the chat stream does not preserve image aspect ratios, stretching portrait images to be landscape.

### Steps to reproduce

- Upload a portrait image from a phone
- View the message in riot-web

Expect the aspect ratio to be preserved, instead the image is stretched to the width of the chat.

Logs being sent: no

![Screenshot 2020-07-01 at 9 36 21 PM](https://user-images.githubusercontent.com/366761/86306697-f07dca00-bbe2-11ea-8b70-52a3f0198603.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 83.0.4103.119 (Official Build) (64-bit)
- **OS**: ChromeOS
- **URL**: private server running riot-v1.6.8-rc.1 from https://github.com/vector-im/riot-web/releases

**Comment by flackr** [comment]
Note that clicking on the photo to view it fullscreen does show it at the correct aspect ratio.

**Comment by jryans** [comment]
Hmm, which client are you uploading from? Does it apply to all images?

**Comment by flackr** [comment]
It was uploaded from RiotX on android. The same thing happened for many other non-landscape orientation images uploaded on RiotX, including a square cropped image.

**Comment by toger5** [comment]
Is there an issue about the image preview in general. I have the same issue (not recently anymore.) There is room for improovemtn for the image previous anyways. Especially images in portrait fromat are HUGE. because only the width gets taken into consideration when placing them

**Comment by t3chguy** [comment]
It is up to the sending client to set the right width & height attributes of the image in the orientation which it is rendered. If you see this again please send the `View source` and the EXIF data of the image. For now considering this an issue with the sending client and also most likely already fixed.
