### ISSUE TITLE
New room list: Preview shows reactions?

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#14298]
If the latest event is a reaction we get e.g. "uhoreg: :tada:" as the preview, which I find a bit confusing when opening up the room and that is not the latest message event. I don't know if it'd be better if we a) leave it as is, b) ignore reactions or c) render reactions in a different way

**Comment by nadonomy** [comment]
+1 to finding it jarring sometimes, that said, in low signal:noise ratio rooms (e.g. DMs) it's also nice in other apps to get 'x reacted to y' notifications/previews.

@turt2live for this I'd advocate for us to stick it in medium-high priority in nice to have where we can do some more critical thinking on it then if we can get to it.

**Comment by jryans** [comment]
Yeah, personally I actually quite like having the reactions appear as preview, at least for DMs, where it's easy to see at glance.

**Comment by jryans** [comment]
Maybe as a compromise we could only show a reaction in the room preview if it's attached to the most recent N messages? 

That would retain utility for the DM use case, and also filter out the case of someone reacting to something days ago in large room which is way off screen.

**Comment by erikjohnston** [comment]
I'd quite like it if the preview instead said `jryans reacted with :+1:` or some other such wording

**Comment by babolivier** [comment]
To me it's fundamentally wrong that message previews show reactions (or edits), since these are not new messages but metadata to existing ones. I've started turning message preview off in some places because I'm wasting so much time wondering why a message doesn't appear in my timeline, only to realise (sometimes after having rageshaken) that it's a reaction or edit to a message much higher up on the timeline.
I'd consider it acceptable if it showed only edits to the latest message in the room (and maybe reactions but I'd think it a bit useless, the point imho is to show me the latest message in a room and not to show me what others think of it), as is I find it really confusing and low snr :/

**Comment by niquewoodhouse** [comment]
> To me it's fundamentally wrong that message previews show reactions (or edits), because these are not messages but metadata to messages (same reason we don't plan on notifying on reactions in the notifications rework for example).

On reflection, I'd personally agree with @babolivier.  They feel, in practice, at best a distraction from what I'm doing and, at worst, clickbait that slows down my ability to use Element for work.   

That said, for work, I often use reactions to signify that I understand something/agree.  I think a number of people behave like this.  So reactions do have their usefulness but I don't think the solution is anything that looks like it could be interpreted as a message in itself.  I've seen some suggestions like put an asterisk at the start but I think that's probably too subtle and not universally obvious - when someone is scanning their list for what's new, they might not see the difference.

Maybe in the near future, there's an iteration that presents them in a different way but for now, I'd suggest we turn them off as that would need to explored comprehensively with all the edge cases to test suitability.

<img width="173" alt="reactions@2x" src="https://user-images.githubusercontent.com/1587166/88634871-da164180-d0ae-11ea-8703-41606f466237.png">

**Comment by nadonomy** [comment]
> On reflection, I'd personally agree with @babolivier. They feel, in practice, at best a distraction from what I'm doing and, at worst, clickbait that slows down my ability to use Element for work.

(For posterity— writing up some slightly belated notes from a design critique we had last week).

This sounds principally correct to me for the common case. One thing that came up in the sync, is it could be worth experimenting with some labs options like:

- Enabling 'x reacted with y' in previews in all rooms
- Enabling 'x reacted with y' in previews in DMs only

to dogfood different behaviour over time and see how it feels in practise, as it's the type of feature which is incredibly easy to bike shed, and easy to make bad decisions on without using it over time in different contexts in the thick of actual day-to-day communication.

**Comment by niquewoodhouse** [comment]
Just looking to confirm the product decision to update the tags/move the ticket (@nadonomy lmk if this I've misunderstood pls):

- remove reactions from the default room list behaviour 
- have a lab option that includes reactions in the message preview and changes their behaviour to*

> ...'x reacted with y' in previews in all rooms
> ...'x reacted with y' in previews in DMs only

*So we can keep testing to come up with something better/rounded in the future.
