### ISSUE TITLE
riot-electron, chrome and chromium can't send HEVC video

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#14328]
While riot-web in ff works fine, riot-electron can't send the same 5Mb video. It just says Uploading ...mp4 and that's all:
![image](https://user-images.githubusercontent.com/14617699/86512619-55683880-be0c-11ea-9e16-43cb89dfe189.png)

v1.6.8

chromium 83, chrome 83 and chrome beta 84, has the same issue:
```
Uncaught TypeError: Cannot read property 'type' of null
    at ContentMessages.tsx:130
(anonymous) @ ContentMessages.tsx:130
```

**Comment by 532910** [comment]
In fact I can't send even 5Mb video from riot-electron, it just says Uploading ...mp4 and that's all:
![image](https://user-images.githubusercontent.com/14617699/86512619-55683880-be0c-11ea-9e16-43cb89dfe189.png)

**Comment by t3chguy** [comment]
Could you send debug logs from Settings > Help & About please

**Comment by 532910** [comment]
Done

**Comment by 532910** [comment]
The same way I can't upload 5Mb video to matrix.org from chromium 83.

**Comment by 532910** [comment]
And google chrome 83

**Comment by 532910** [comment]
And google chrome beta 84:

```
Uncaught TypeError: Cannot read property 'type' of null
    at ContentMessages.tsx:130
(anonymous) @ ContentMessages.tsx:130
```

**Comment by t3chguy** [comment]
```
    at ContentMessages.tsx:130
(anonymous) @ ContentMessages.tsx:130
```

This is a canvas issue. Where the canvas output is saying `type=null` on the file

What encoding is that mp4 file?

**Comment by 532910** [comment]
HEVC

**Comment by t3chguy** [comment]
Well that's why then: https://caniuse.com/#feat=hevc

**Comment by 532910** [comment]
File shouldn't be supported to be able to send it, FF has no HEVC support but successfully sends it.

**Comment by t3chguy** [comment]
Oh it literally crashes, I got tangled between this and your other issue about no thumbnail, my bad.

**Comment by t3chguy** [comment]
This raises a product question.

When thumbnailing fails, do we send without a thumbnail or do we error

**Comment by t3chguy** [comment]
This will hopefully be dealt with shortly: https://github.com/matrix-org/design/projects/2#card-42103287

**Comment by 532910** [comment]
> https://github.com/matrix-org/design/projects/2#card-42103287

says 404

**Comment by t3chguy** [comment]
Oh argh, their workflow board isn't public, either way, its in the `Next` column so hopefully shortly.

**Comment by t3chguy** [comment]
It now falls back to `m.file`
