### ISSUE TITLE
accesibility outline is poor on new styled radio/checkbox components

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#14342]
it is just a small dot in the bottom left corner rather than an outline around the form element

![image](https://user-images.githubusercontent.com/2403652/86538183-4e185c00-beec-11ea-88d5-f48228022b75.png)

**Comment by turt2live** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/1190097/173435304-60c09f62-3ec7-4a0c-8b26-f678cf64c941.png)
