### ISSUE TITLE
Compatibility policy for element-web and Matrix home server version

### ISSUE THREAD

**Issue by PeterSR** [vector-im/element-web#14382]
According to the [specification](https://matrix.org/docs/spec/#client-server-api-v1), the current client-server-API version is 0.6.1.

Does riot-web have any compatibility policy of what versions of home servers it supports? Either specifically Synapse versions or spec versions.

It would be very nice to know when one is forced to update Synapse to still be able to use all the features of riot-web. 
What happens if Synapse suddenly doesn't "speak the same language" anymore?

As an example, Kubernetes has a [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/) where it specifies what older minor versions it supports.

Any thoughts on this? Or pointers where this is documented?

**Comment by PeterSR** [comment]
Any news on this? Is it the wrong forum to discuss this here?

**Comment by turt2live** [comment]
We typically support the most adopted version, but do not have a formal policy at the moment.

One of the first troubleshooting steps is "update everything", fwiw

**Comment by PeterSR** [comment]
> We typically support the most adopted version, but do not have a formal policy at the moment.
> 
> One of the first troubleshooting steps is "update everything", fwiw

Thanks! I will try to keep my Synapse server up-to-date. Sometimes it is just nice to know where the limits are. 
Do you guys want to keep this issue open?

**Comment by jryans** [comment]
At this time, I'd describe it as we do our best to support all active / supported versions of the protocol. There are multiple homeserver implementations, so I don't we would make any statement on specific server versions, but instead talk about protocols, which are on then on the servers to implement correctly.

I don't think there's much to document on this front at the moment, but we can tune that if needed in the future.
