### ISSUE TITLE
Changing the UI font to a custom font makes emojis change

### ISSUE THREAD

**Issue by pioneer** [vector-im/element-web#14398]
Default UI font:
![Выделение_198](https://user-images.githubusercontent.com/200538/87146581-d82d3f80-c2b3-11ea-910f-29797f205892.png)

Roboto:
![Выделение_199](https://user-images.githubusercontent.com/200538/87146604-e3806b00-c2b3-11ea-847f-329a15ae1d4d.png)

### Steps to reproduce

- OS, DE: Manjaro/Cinnamon
- the nightly Riot-desktop build I'm using is https://packages.riot.im/debian/pool/main/r/riot-nightly/riot-nightly_2020070901_amd64.deb
- go to `Settings -> Appearance -> Show advanced -> Use a system font`
- tick the checkbox, type `Roboto` (the `Roboto` font should be installed)
- emoji reactions will become black and white

### Expected result:
Although design-wise I'm not 100% sure which solution is the best, I believe changing the UI font should not lead to such an unexpected thing. Instead, either the look of emojis should not be changed, or the user can select the emojis look independently using one of the predefined packs, for example.

**Comment by pioneer** [comment]
I was given this link - https://blog.livthomas.net/adding-color-emojis-to-chrome-on-fedora/, and seems it's very relevant, but I haven't used it just because installing the following packages from AUR and restarting Riot helped without any additional action: `noto-fonts-emoji-flags`, `noto-fonts-emoji-fontconfig`.

**Comment by Pestdoktor** [comment]
You are overriding the entire stack with that setting, so for your desired result you'd have to append the fallback fonts again:
`Roboto,Twemoji,Apple Color Emoji,Segoe UI Emoji,Arial,Helvetica,Sans-Serif,Noto Color Emoji` or something to that effect.

Maybe this should be done transparently by riot?

**Comment by geckolinux** [comment]
I'm also running into this on openSUSE Tumbleweed when trying to use the `Ubuntu` font. I don't mind the B&W emojis, but the problem is that some of them are wrong. For example, here there should just be 3 "facepalms" (nothing to do with Riot :wink: ) :

![Screenshot at 2020-07-14 08-43-19](https://user-images.githubusercontent.com/2692138/87433699-42ddc400-c5af-11ea-9720-75d80e3b58f3.png)

So from @pioneer 's link, do I understand that I would have to use a font that specifically has a color emoji subset? Or can I put more than one font in the field?

Would it be possible to just make Riot always use its default font for emojis?

**Comment by Pestdoktor** [comment]
> Or can I put more than one font in the field?

Yes, put a comma-seperated list ordered by descending priority and it will use the first font which supports any given character.

**Comment by Pestdoktor** [comment]
#14494 could be solved independently by removing the non-alphanumeric glyphs from the Inter font files.

**Comment by iav** [comment]
Workaround work for me on windows 10:
set font string `Arial,Twemoji,Apple Color Emoji,Segoe UI Emoji`
I have arial text and good emoji.

**Comment by maralorn** [comment]
For what it's worth: For me personally knowing that you can enter a list of fonts and not just one font into the field helped me a lot. If the tool tip could be a little bit more precise and maybe show the default setting that would probably help a lot.

**Comment by frakic** [comment]
Retested on both Element Web and Nightly 1.10.12 by adding Open Sans as a custom font.
Emojis appear different and some of them seem to be missing entirely:
![image](https://user-images.githubusercontent.com/18530109/168589817-86c70105-7432-4063-a528-d9356048857e.png)

The workaround, as mentioned above, is to set custom font to `Open Sans,Twemoji,Apple Color Emoji,Segoe UI Emoji`
That way I have Open Sans set as my default font and emojis look fine:
![image](https://user-images.githubusercontent.com/18530109/168589855-dcf630ad-4803-4abd-a291-610513cfd576.png)

I say we leave this issue open but with low priority.

**Comment by CutestNekoAqua** [comment]
For you all who may wanna use noto emojis: 
`Roboto,Segoe UI Emoji,Arial,Helvetica,Sans-Serif,Noto Color Emoji`

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9790
