### ISSUE TITLE
Improve UI/UX for session verification when logging on a new device

### ISSUE THREAD

**Issue by maskedriotuser** [vector-im/element-web#14415]
Hello,

This is a follow up on https://github.com/vector-im/riot-web/issues/14414. Thank you again for your work on Riot!

When logging on a new device, this first toast is perfectly clear:

![riot01](https://user-images.githubusercontent.com/68146982/87221723-ba1c1980-c35d-11ea-8db6-55d35415f8c1.png)

However, the following dialog box could be improved in my opinion:

![riot02](https://user-images.githubusercontent.com/68146982/87221724-bab4b000-c35d-11ea-8e62-a3b255419135.png)

Thought process: The dialog box seems to require some action. Yes I have the latest version of Riot installed on other devices. Can I click on the screen or smartphone icons to initiate the verification with the classic emoji technique? No, it doesn't seem to work, they are not clickable.

"Use Recovery Key" is clickable, but why is it a link and not a button like "Skip"? It seems to imply that the recovery key is a fallback method, even though it's in green. But a fallback method compared to what?

Oh OK, the first line says "Confirm your identity by verifying this login **from** one of your other sessions". I can't initiate the verification from this new device, except using the recovery key method. Why is it possible with one method but not another?

I think it's a little confusing. Could it be possible to replace the icons with the list of the other sessions, and to make them clickable so that it's possible to start the verification from this dialog box?

If it's technically not possible, I still think the icons drag to much attention. Just after the first line, could it then be possible to add one clear instruction like: "Use one of your other devices to initiate the verification"?

**Comment by PureTryOut** [comment]
> Just after the first line, could it then be possible to add one clear instruction like: "Use one of your other devices to initiate the verification"?

This so much. Today I finally got my immediate family to use Matrix (and Element), or at least try it out, to replace Telegram with. However this was one of the things that went wrong, as they just didn't know how to verify their device from this screen. A simple sentence telling them to look on their other devices now (where there was indeed a notification to verify) would've been good enough.

**Comment by jryans** [comment]
This dialog has changed significantly in last month or so, so we I suspect it's best to close this and open new issues for feedback on the latest version.
