### ISSUE TITLE
Suggestion for reduced amount of top-right icons to reduce confusion

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#14425]
**Is your suggestion related to a problem? Please describe.**
The UI was pretty confusing to me at first, especially the many unfamiliar icons ~~and their seemingly random ordering.~~ I think currently riot gives off a sub-optimal first impression due to that. I might suggest improvements for other areas later, but for now I am starting off with the top-right icons.

**Describe the solution you'd like**
I am suggesting ~~a~~ different (better?) icons ~~ordering~~ for the top-right corner:

Edit: **see this comment for an updated, better suggestion:** https://github.com/vector-im/riot-web/issues/14425#issuecomment-657184351

---

*outdated suggestion:*
![ux_icons](https://user-images.githubusercontent.com/64124388/87239840-3c124e00-c403-11ea-9c25-341a4814a7ff.png)

~~The things I attempted to improve:~~

~~1. The vertical bar now separates things that default to room-scope (left side of separator/closer to room topic) from things that default to wider scope (right side of separator). I don't know what the separator meant before it seemed pretty random, so I am suggesting this hopefully more obvious separation.~~

~~2. I removed the integrations button, and I think that should go into the settings dialog as a new category.~~

~~3. I removed the sharing button, and moved it into the room settings menu.~~

~~4. I moved the member list button to the very right (of the left separator side area of course, since room-scoped) since it seems to be the most important one to keep you "grounded" in where you are. I think the outer corner makes most sense for that. The files and search button are then sorted right-to-left in what I think is likely the most-used-to-least-used. The same was applied to settings and notifications right to the separator, with notifications going to far right since likely most used and settings further left.~~

~~I would also suggest to not add any more buttons to the top-right corner in the future unless there is an extremely important reason to do so. I find even this new trimmed down amount already borderline questionable for keeping the UI easy to grasp, I think keeping this area minimal is really essential to keep the UI intuitive for new users.~~

**Describe alternatives you've considered**
none

**Additional context**

**Comment by t3chguy** [comment]
By your reasoning wouldn't the settings button which is for room settings need to be on the left of the divide? Along with the other room specific things? And wouldn't search need to be in its own place altogether as it can be both room specific and not?

**Comment by ell1e** [comment]
Oops, yeah you're right on both points. Somehow I thought the settings cogwheel led to the regular user settings.

What about this ordering then?
![newordering](https://user-images.githubusercontent.com/64124388/87240114-323e1a00-c406-11ea-97fe-9c7d3ffacd98.png)
And I get that search could be both sides, but I think it makes sense to at least try to separate it meaningfully. I was torn on that one before, but with the settings moved to the left it feels very balanced and nice to the right. In a way the left-side now feels more "concrete" (like, showing things as-is without input with increasing detail level to the left) while the right-side is more "abstract" (more user-involved wider searches like general search & notifications). I do kind of like that, although I admit it's in any case kind of made up and still has some smell of random.

**Comment by t3chguy** [comment]
I am not a designer and have no real input as to what a good order/separation here is

**Comment by t3chguy** [comment]
Additionally, there is already a show Pinned Messages toggle in Labs:
![image](https://user-images.githubusercontent.com/2403652/87240314-77674980-c410-11ea-85af-9af4f0fadb2b.png)

The current split is very much things on the right side affect the right panel only, the rest do not.

**Comment by ell1e** [comment]
Ok. yes with your explanation the ordering makes more sense as-is.

However, I am quite concerned seeing "Labs" even *added* another icon. I think this is the completely wrong direction to go, and quite a fundamental issue for the UI as-is. But I have a suggestion for that too:
maybe the files icon could be removed too, and instead be added back as a button inside the search bar (the one that pops up when clicking the search icon with the `[Search...]` input field) to the right. It would then open up the file search sidebar as before.

**Comment by ell1e** [comment]
I realize I made a bunch of suggestions in one go again, so here is a quick updated mockup to show it all:

![mockup2](https://user-images.githubusercontent.com/64124388/87241019-4ede5000-c40e-11ea-93dd-da29ac54c701.png)


(I left out how exactly the text search would look like if done in the sidebar like discord, but at least it should give you or designers an idea how it could otherwise integrate in overall)

**Comment by t3chguy** [comment]
Fixed https://github.com/matrix-org/matrix-react-sdk/pull/5167
