### ISSUE TITLE
Verification doesn't work

### ISSUE THREAD

**Issue by Sav22999** [vector-im/element-web#14431]
### Description

When I try to verify my session, it doesn't finish correctly. It asked to me "verification via emojies", then it returned "The user cancelled the request", but it's not true, because on the verification device I've pressed "Done".

### Steps to reproduce

- Try to verify a session from RiotX Android app
- After emojies verification, it says the operation is cancelled

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: Web, Android (RiotX) and Windows 10 software

For the web app:

- **Browser**: Firefox (77,78,79dev)
- **OS**: Windows and Linux
- **URL**: chat.mozilla.org

For the desktop app:

- **OS**: Windows
- **Version**: 10 (version code: `2004`)

**Comment by Sav22999** [comment]
![image](https://user-images.githubusercontent.com/32335378/87258090-2b181a00-c4a1-11ea-820a-c74a8b88cf44.png)
![image](https://user-images.githubusercontent.com/32335378/87258097-3bc89000-c4a1-11ea-9991-61759f31b1d0.png)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18165
