### ISSUE TITLE
New room list: Easy to forget you're filtering

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14466]

**Comment by turt2live** [comment]
Github seems to handle this nicely with the project interface btw:
![image](https://user-images.githubusercontent.com/1190097/87979052-afb0fc80-ca8e-11ea-9504-a238142b1ebf.png)

By saying how many results there are, it's easy to remember that you're filtering because you're seeing 2/41 cards.

**Comment by niquewoodhouse** [comment]
I really really like the example @turt2live, it's simple and helpful so I'd suggest something quite similar as the first iteration.  
With just giving the active state a different visual treatment (background colour and border) it should be enough to help.

<img width="1199" alt="room list - searching - light" src="https://user-images.githubusercontent.com/1587166/88381363-2e16e280-cd9e-11ea-9d78-82507cd535b0.png">
<img width="1199" alt="room list - searching - dark" src="https://user-images.githubusercontent.com/1587166/88381364-2f480f80-cd9e-11ea-820c-2578de5745c6.png">

I've included a couple of things in the above mockups that I don't think are really required for the first iteration, I just include them for my own reference/to enable people to feedback on the ideas:

- By removing all rooms when the filter is active, but with no input we can make space for suggested searches (eg "/notifications" shows all rooms with notifications) and recent searches (searches the user has made previously, which can be cleared by them).

- Adding an explore button to the bottom of the list to potentially educate that there are other rooms. I'm not sold on this idea as I think the flow isn't super (search > can't find > open link > search again).
