### ISSUE TITLE
Unable to verify people using cross-signing

### ISSUE THREAD

**Issue by DylanVanAssche** [vector-im/element-web#14463]
marks will be invisible in the report.
-->

### Description

For some time I experience issues with cross-signing.
I tried already to clear the caches of the Riot Desktop clients, logging in and out, etc. but still no difference.
I think they are related to each other, that's why I created a single issue.

**1. Verifying another person:**
In Riot Desktop I click on the person's profile --> Verify button --> the spinning wheel appears.
However, the message 'You send a verification request' doesn't appear in the chat.
If the other person starts it, the same happens.

**2. Key exchanges are not propagated:**
On my desktop I have a Riot Desktop running. Messages I send from there appear on my laptop \(Riot Desktop\) as encrypted.
The keys are not properly exchanged between both devices, even if they are all verified. I have to restore them using Key backup on my laptop. It's always a one way street. Messages I send from my laptop are not affected when I read them on my desktop again. Messages from the desktop are marked on the laptop's Riot Desktop as 'The authenticity of this message can not be verified'.

**3. Losing verified people:**
Sometimes people I verified become unverified, even though they have verified all their sessions.
When I verify them again manually, the shield becomes green again. However, a day later they lose their verified status again.

### Steps to reproduce

**1. Verifying another person:**
- Click on a person's profile
- Click verify
- Nothing appears in the chat, the person doesn't notice the request at all.

**2. Key exchanges are not propagated:**
- Send messages from the desktop
- Try to read them on the laptop, all encrypted, missing keys
- Use key back restore to make them readable again
- Messages are marked as 'The authenticity of this message can not be verified'

**3. Losing verified people:**
- Verify someone
- After some time they are suddenly unverified

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: Riot Desktop
- **OS**: Arch Linux on the desktop, Ubuntu 20.04 LTS on the laptop
- **Version**: 1.6.4

**Comment by richvdh** [comment]
given this hasn't had any investigation in a year and a half, I don't think it's going to get it now.
