### ISSUE TITLE
Not enough alarm bells when redacting `m.room.server_acl` state

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/element-web#14468]
Way too easy to brick a room without realising, see [conversation in #synchronicity:mozilla.org](https://matrix.to/#/!pcfWjiETvnVuspPLPl:mozilla.org/$l-Vgd17qN2RSQKgBKwHU5vZZKvJQzRZN8mrnU9bZbJ8?via=mozilla.org&via=matrix.org&via=feneas.org).

**Comment by turt2live** [comment]
Critical because the room breaks and is not recoverable.

**Comment by t3chguy** [comment]
We no longer allow it via UI, and servers block it.
![image](https://user-images.githubusercontent.com/2403652/189130793-39305389-88b0-473a-a50c-0914fdebf53a.png)

![image](https://user-images.githubusercontent.com/2403652/189130747-163ece97-b718-4dda-837c-8c937a7aea72.png)
