### ISSUE TITLE
Redacting `m.room.server_acl` state hides the result

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/element-web#14470]
### Description

With "show hidden events" disabled, redacting an `m.room.server_acl` state event hides the "All servers have been banned" message that does show with "show hidden events" enabled.

See-also: #14468

### Steps to reproduce

> **Warning**: Do not attempt to reproduce this in a room you don't want bricked.

- Ensure "show hidden events" is disabled.
- Set a server ACL in a room.
- Redact the resulting event.

The new server ACL is not shown.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: riot.im/develop / Radical 1.6.8

**Comment by turt2live** [comment]
raised as critical given https://github.com/vector-im/element-web/issues/14468 is also a critical bug. This side acknowledges that the timeline should show the "🎉 this room is broken" message.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/189130688-f64489e6-a7d2-496b-9d8e-838bbb1967cf.png)

It is no longer a possible state to get into

Also the message renders regardless:
![image](https://user-images.githubusercontent.com/2403652/189131232-051d5218-6d8c-46fe-9137-146d49373c1d.png)
