### ISSUE TITLE
welcome screen not usable in firefox https://staging.element.io/#/welcome

### ISSUE THREAD

**Issue by nebocamin** [vector-im/element-web#14480]
the welcome screen of the new staging.element.io site is not usable in firefox 78. the blurry stuff is above the buttons. but works in chromium.
![shot-element-staging-welcome](https://user-images.githubusercontent.com/3319621/87547047-d0520e80-c6aa-11ea-9808-81b48c4dc257.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/87547152-9846cd80-c6a2-11ea-8f30-fc039a7646f6.png)

works fine here, looks like css didn't load for you, check if anything is getting blocked in the console, likely one of your browser extensions

**Comment by nebocamin** [comment]
you are right, firefox with a clean profile is showing it correctly.

**Comment by t3chguy** [comment]
Did you narrow down the problematic extension/setting? Does this issue need to remain open?

**Comment by nebocamin** [comment]
I have some errors found in the console. so I have an issue, but dont know what it is exactly. is it migrating my data? because i host my own synapse and have a non-default setting?


Uncaught (in promise) TypeError: i.getAttribute(...) is null
    h theme.js:1
    te init.tsx:138
    <anonymous> index.ts:142
theme.js:1
Uncaught (in promise) M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
    m http-api.js:590
    i http-api.js:499
    p http-api.js:544
    _ http-api.js:403
    onreadystatechange index.js:294
    onreadystatechange index.js:244
http-api.js:590:16
Uncaught (in promise) M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
    m http-api.js:590
    i http-api.js:499
    p http-api.js:544
    _ http-api.js:403
    onreadystatechange index.js:294
    onreadystatechange index.js:244
http-api.js:590:16
Uncaught (in promise) M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
    m http-api.js:590
    i http-api.js:499
    p http-api.js:544
    _ http-api.js:403
    onreadystatechange index.js:294
    onreadystatechange index.js:244
http-api.js:590:16
/sync error ORG.MATRIX.JSSDK_TIMEOUT: Locally timed out waiting for a response submit-rageshake.ts:132:24
    n submit-rageshake.ts:132
    methodFactory logger.js:44
    _onSyncError sync.js:677
    _sync sync.js:574
ORG.MATRIX.JSSDK_TIMEOUT: Locally timed out waiting for a response
    m http-api.js:590
    g http-api.js:367
    d index.js:23
submit-rageshake.ts:132:24
    n submit-rageshake.ts:132
    methodFactory logger.js:44
    _onSyncError sync.js:677
    _sync sync.js:574
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix-client.matrix.org/_matrix/client/versions. (Reason: CORS request did not succeed).

​

**Comment by t3chguy** [comment]
So `Uncaught (in promise) TypeError: i.getAttribute(...) is null` is causing the css to not load. This is not related to you running your own Synapse. Looks like something is causing mutations to the `<link` DOM elements which load the CSS.

Do you have any browser extensions?

**Comment by nebocamin** [comment]
now the first error is another one: Uncaught (in promise) DOMException: IDBDatabase.transaction: Can't start a transaction on a closed database
(cleared cookies and site data made a difference, havent seen a change disabling extensions one by one)

**Comment by nebocamin** [comment]
now its down to:


Uncaught (in promise) TypeError: i.getAttribute(...) is null
    h theme.js:1
    te init.tsx:138
    <anonymous> index.ts:142
theme.js:1
XML Parsing Error: not well-formed
Location: https://matrix.org/.well-known/matrix/client
Line Number 1, Column 1: client:1:1
Failed to register as guest M_UNKNOWN: Unable to find a suitable guest user ID
    m http-api.js:590
    i http-api.js:499
    p http-api.js:544
    _ http-api.js:403
    onreadystatechange index.js:294
    onreadystatechange index.js:244

**Comment by florianjacob** [comment]
We have the same issue as well, but could not nail down the add-on or config causing this yet.

**Comment by florianjacob** [comment]
Seems like it was the [Firefox Darkmode extension](https://addons.mozilla.org/de/firefox/addon/dark-mode-webextension/)

**Comment by jryans** [comment]
It sounds like the several issues reported here are resolved / not something Element can act on.
