### ISSUE TITLE
reliable repro: duplicates in new room list

### ISSUE THREAD

**Issue by colemickens** [vector-im/element-web#14508]
### Description

I can reliably repro duplicates in the new room list. This repro'd on /develop and now repros on app.element.io.

### Steps to reproduce

1) (not sure if necessary) Have a bunch of rooms.
2) it doesn't seem to matter which lists are collapsed or expanded
3) click on a low priority room so that it's visible/active
4) right click on the room, make it a favorite
5) click on any other room
6) expand/look at the favorite list, it will have at least two copies of the newly favorited room.

Often from this point on the list is just broken and requires a reload. Seems like some messy state somewhere.

### Version information

- **Platform**: **web (in-browser)**

In this screenshot, I did the repro instructions:

1) I was in `Rust (lang)` (the orange icon).
2) I changed it's priority.
3) It didn't move. It wouldn't move. I collapsed the Favorite list
4) I clicked on an old room i nteh room list.
5) All of the sudden `Rust (lang)` disappeared from Low Priority
6) I expanded the Favorite list and this is what it looked like:

![output](https://user-images.githubusercontent.com/327028/87594535-f626e580-c6a1-11ea-969d-84fe31488c88.png)

For the web app:

- **Browser**: Firefox
- **OS**: NixOS
- **URL**: app.element.io

**Comment by benparsons** [comment]
I am seeing this. I just sent logs against this issue.

I had an issue where an invite did not go away after joining. But then I found that whenever I searched and cleared, that room with the invite would be gradually duplicated in the list. Selecting worked correctly (i.e. when the room was entered, all the duplicates are correctly highlighted).
![Screenshot 2020-07-16 at 17 09 17](https://user-images.githubusercontent.com/1197991/87695893-fe595080-c787-11ea-9870-35de895b4f73.png)
![Screenshot 2020-07-16 at 17 08 43](https://user-images.githubusercontent.com/1197991/87695897-ff8a7d80-c787-11ea-8dde-665c1246a8a7.png)

**Comment by turt2live** [comment]
@colemickens @benparsons I cannot reproduce this, but can believe it exists as a bug. https://github.com/matrix-org/matrix-react-sdk/pull/5005 adds some logging, and should be on develop.element.io (or tomorrow's nightly) shortly. Please turn on the logging from the labs tab ***before*** the issue happens again, then send logs *immediately* after seeing the problem.

**Comment by colemickens** [comment]
On first few attempts, I can't repro. The room immediately jumps to the Favorites list as I might expect and there is no duplication. Hopefully it's not a fluke of enabling the logs, heh.

(For what it's worth, I had *not* been using develop.element.io (didn't know) but had been using riot.im/develop until... mid-day yesterday.)

**Comment by benparsons** [comment]
I haven't seen this on Element Nightly or develop.element.io in weeks. I vote to close.

**Comment by turt2live** [comment]
There's at least one rageshake which hasn't been investigated for this, and appears to be reliable.

**Comment by williamkray** [comment]
i'm seeing this again with the latest spaces beta codebase (my own deployment). rageshake being sent to this issue as i cannot find a more recent version of this but i know it's cropped up again recently. i don't know what i did to trigger it in this case.

**Comment by MightyCreak** [comment]
Same here, three DM rooms with the same user appeared in my room list. Depending on the selected space, I got two or three duplicated rooms.

**Comment by Twi1ightSparkle** [comment]
This is now happening several times daily to me. Sometimes so bad that the duplicated room stack up several pages height and it takes a couple of seconds every time I need to scroll past them one way or the other.
It started for me after enabling spaces beta in Element and on my homeserver.

I'm not able to reliable reproduce the issue, and not entirely sure exactly what actions cause it, but it seems to be related to me being active in the room somehow?

It also seem to randomly resolve itself when I'm not looking.

Have rageshaked a couple of times, please let me know if I can provide any other info.

**Comment by pranavmishra90** [comment]
Had same issue for the first time. can't reproduce, but I did not follow a similar process as OP.

![Duplicated Chats](https://user-images.githubusercontent.com/62562712/119250039-f108b180-bb62-11eb-9082-cd2098bba965.png)


Windows 10
Element Nightly version: 0.0.1-nightly.2021052201
Synapse 1.34.0
Python 3.8.10

Chat was with a single user over a Whatsapp Bridge. Was not listed as a favorite. Could only expand one of the "3 dot room options" menus. The number of unread messages was inconsistent. Closed Element Nightly and reopened it. Problem fixed.

**Comment by ShadowJonathan** [comment]
i'm seeing this more and more often with the spaces beta

**Comment by turt2live** [comment]
For the record, this issue and the recent issue are different, but it's too late to separate them now :(

Please don't comment "I get this too" without logs. Specifically, we need to have the advanced room logging turned on *before* the duplication, and the logs need to mention the room ID which is duplicating.

**Comment by pranavmishra90** [comment]
> Specifically, we need to have the advanced room logging turned on _before_ the duplication

I'll try and grab the logs if possible. Not running into this issue at present

**Comment by ShadowJonathan** [comment]
I seem to have found some correlation between search and switching spaces immediately after, I cant give an exact repro, but I think that direction is warm.

**Comment by sumnerevans** [comment]
Found a (fairly) reliable repro (90+% of the time):

1. Go to a space and select a room.
2. Use the "Filter all spaces" function and search for a room that is not in any space. That is, a room that is only in "Home". For example, a DM with someone who you share no spaces with.
3. Select that room.
4. Profit! (Actually, not really profit, more like cry, but at least you reproduced the bug!)

**Comment by williamkray** [comment]
i can confirm this triggers the bug for me as well, thanks for putting that one together @sumnerevans!

**Comment by callahad** [comment]
Toggling the room list appearance options ("Sort by" and "Show rooms with unread messages first") seems to cause already-duplicated rooms to further multiply:

![Screen Shot 2021-06-03 at 10 57 15](https://user-images.githubusercontent.com/24193/120627005-2498e500-c45b-11eb-9046-a9ead21b017e.png)

**Comment by unclechu** [comment]
![2021-06-09 12-29-30](https://user-images.githubusercontent.com/799353/121332034-1d248080-c920-11eb-9938-8cd0b70c5fc3.png)

**Comment by unclechu** [comment]
![2021-06-16 00-20-02](https://user-images.githubusercontent.com/799353/122124975-acf28f00-ce38-11eb-9d46-a515190f3262.png)

Some items are being active at the same time

**Comment by ara4n** [comment]
I just had a repro of these symptoms; have rageshaked (and have `Enable advanced debugging for the room list` turned on)

**Comment by Kreyren** [comment]
AAaaaaaaaAAAaaAaaAaaAAaaaaaaaaaa it spreads on matrix now too!

![image](https://user-images.githubusercontent.com/11302521/124797407-81a02300-df52-11eb-8e3d-cdeba41a3a64.png)

**Comment by sumnerevans** [comment]
I was still able to reproduce on Element 1.7.33 with the following steps:

1. Go to a space
1. Search for a space that is not in the current space
1. Click on the room that is not in the current space

![image](https://user-images.githubusercontent.com/16734772/126812363-2a42ad1b-5eca-4a70-bf87-01c3e1fad2bf.png)

I have "Show all rooms in Home" turned off (although I think that this repro works with that enabled as well)

Should I create a new issue for this?

**Comment by t3chguy** [comment]
That screenshot doesn't show any duplicates though?

**Comment by t3chguy** [comment]
The PR also landed after the RC cut for 1.7.33 - so it won't be in until the following release.

**Comment by sumnerevans** [comment]
> The PR also landed after the RC cut for 1.7.33 - so it won't be in until the following release.

Oh! Sorry! I thought that since the release cut was 4 days ago, that this would be included.

**Comment by t3chguy** [comment]
RCs tend to happen on Tuesday/Wednesday with the release the following Monday so this was missed (on purpose to give it time for testing)

**Comment by ShadowJonathan** [comment]
> That screenshot doesn't show any duplicates though? 

FWIW that screenshot doesn't have a duplicate, but it does have a "ghost sticky" which'd show in that room list in every space, and eventually maybe bug out into duplicates.
