### ISSUE TITLE
leftpanel blur sometimes disappears for a frame on Chrome, flashing your avatar at you.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14531]
on Chrome 83.0.4103.116 on macOS 10.15.5 using integrated graphics, every ~1 hour or so something causes the LeftPanel to refresh in such a way that the background-blur and also 80% opaque background vanishes for a single frame on the LeftPanel (but not the LLP, i /think/).  This is very disconcerting, as it causes a subliminal flash of your face suddenly peering back at you from the RoomList.  I assume this might be React remounting the RoomList somehow? It may coincide with changing rooms; i haven't spotted the pattern yet.

**Comment by ara4n** [comment]
just had it again, this time just when hoverovering the breadcrumbs, so it's not related to switching room.

**Comment by ara4n** [comment]
and again, this time when scrolling the roomlist via two-finger swipes

**Comment by turt2live** [comment]
for me this was happening because of a `[x] disable cache` checkbox - does that roughly align with what you were seeing?

**Comment by ara4n** [comment]
my 'disable cache' is not checked.

i've been able to reproduce quite a lot when scrolling both room history and leftpanel and breadcrumbs, but not when screencapturing.

**Comment by turt2live** [comment]
it might just be that disabling the cache exacerbates the issue rather than causes it. With cache disabled, the image flickers a lot presumably with every mount or layout change - it's possible that what you're seeing is the same thing, however most people will not see the effect happening.

Maybe we can download and convert the avatar to a blob to avoid relying on http and potential delays there?

**Comment by ara4n** [comment]
i'm wondering if we're talking about remotely the same thing. i don't think there's any reason that the avatar should be reloaded, least of all via http from the network? it looks more like a GPU rendering bug, where sometimes incomplete layers are being swapbuffered...

**Comment by turt2live** [comment]
it kinda sounds like we are: we set the avatar URL on every render, which is often.

https://github.com/matrix-org/matrix-react-sdk/blob/b1444146e632579e58575814786c7d0ba1fd9607/src/components/structures/UserMenu.tsx#L311

**Comment by ara4n** [comment]
This is weirdly more and more reproduceable for me. Have uploaded a video (internal only) at https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1594995153111370IMyax:matrix.org?via=matrix.org&via=t2l.io&via=riot.ovh

**Comment by ara4n** [comment]
i get this constantly, fwiw, and it's incredibly ugly. (not just 'cos it's my face)

**Comment by turt2live** [comment]
from what I remember it's a mac-specific issue.

**Comment by t3chguy** [comment]
I had it on my windows 10 laptop but rarely, get it a bit more frequently on my MacBook though

**Comment by ara4n** [comment]
it's got even worse since enabling the Spaces labs flag (and really screws up my demos)

**Comment by Palid** [comment]
This will be probably fixed by with https://github.com/vector-im/element-web/issues/15594

**Comment by deniseal** [comment]
I am getting this on Element desktop version 1.8.1 on macOS Big Sur 11.5.2

It's quite regular, but it mainly happens when switching room and/or space

**Comment by ara4n** [comment]
confirmed fixed by #15594 - huge huge thanks to @Palid and @gsouquet :D
