### ISSUE TITLE
Only keep N develop jobs laying around, delete the rest

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14559]
Where N is either a number or an amount of time

**Comment by turt2live** [comment]
for clarity, this is develop.element.io builds on the web server. This is still an issue, and ops would like us to clean them up regularly for them.

**Comment by t3chguy** [comment]
Ops no longer cares due to having moved develop over to R2 where the limits are insane, keeping this issue open to create some sort of cleanup job, but there's very little rush on it.

**Comment by t3chguy** [comment]
Blocking on R2 lifecycle policy support

**Comment by t3chguy** [comment]
https://developers.cloudflare.com/r2/buckets/object-lifecycles/

**Comment by t3chguy** [comment]
Fixed by https://gitlab.matrix.org/infrastructure/cloudflare/-/merge_requests/208
