### ISSUE TITLE
Sometimes the new room list shows far fewer rooms than are actually there

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14554]
Unknown cause, has happened twice to my knowledge

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/5005 adds a button to turn on logging for this. It needs to be turned on *before* the problem happens, otherwise the logs produced won't be of help.

**Comment by Half-Shot** [comment]
There were some more reports in #14647, so it's definitely still a thing.

**Comment by turt2live** [comment]
It's impossible to debug without logs. Please turn on the logging *before* the issue happens and rageshake immediately after it happens.

**Comment by t3chguy** [comment]
@turt2live have you seen this since?

**Comment by turt2live** [comment]
Even if I have, there's no logs associated with the issue. Closing.

If people are still seeing this, please open a new issue with fresh information.
