### ISSUE TITLE
transgender flag in emoji 13 is broken on Chrome 83

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14564]
The ligature is ignored, meaning you get a white flag + a transgender symbol, rather than the actual trans flag.  Firefox gets it right however, at least on macOS.

Looks to be a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1061910

**Comment by ara4n** [comment]
Looks like it'll be fixed shortly, based on https://bugs.chromium.org/p/chromium/issues/detail?id=1064326

**Comment by t3chguy** [comment]
Closing as 83 is no longer on our mainline supported browsers (84-85 are)
