### ISSUE TITLE
drop & drag target needs to be redesigned for Element

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14589]

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/8614

**Comment by t3chguy** [comment]
Is it? That one is about room lists 

This looks to be about 
![image](https://user-images.githubusercontent.com/2403652/87796984-070e5d00-c842-11ea-9e31-5af7e705029e.png)

**Comment by turt2live** [comment]
Descriptive titles help :|

**Comment by SimonBrandner** [comment]
Closing as this has already happened, see [#5505](https://github.com/matrix-org/matrix-react-sdk/pull/5505)
