### ISSUE TITLE
I find the currently-selected community highlight very easy to miss on light theme, especially next to the shiny black bezel of my macbook air.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#14591]
![Community Highlight](https://user-images.githubusercontent.com/1922197/87797767-0de99f80-c843-11ea-9276-5ba4601b4e59.png)

**Comment by niquewoodhouse** [comment]
I'm not in any communities - tried to create one but couldn't add it to my `communities list`, so can't test this.  Does anyone know what's the width of the currently-selected community highlight, please?  Thanks

**Comment by t3chguy** [comment]
Drag the community from the "communities" view onto the bar as per the copy in that view

**Comment by niquewoodhouse** [comment]
Thanks, @t3chguy - done.  I was previously dragging the avatar over to random spots on the bar itself, I didn't realise "far left" in the copy meant above the "plus" icon 😄 

Looks like the absolute left positioning is too much and pushing the highlight off the screen, and it's size is a bit off.  I'm using Chrome Version 84.0.4147.105 (Official Build) (64-bit) if that helps at all.

.mx_TagPanel .mx_TagTile.mx_TagTile_selected::before
width: 4px ~~5px~~
left: -12px ~~-15px~~ 

I don't understand why this highlight should be different from the ones in the room list for the currently-selected room but that's a different issue I think.
