### ISSUE TITLE
Communities panel should get some ARIA love

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#14609]
Currently each tagtile is 2 tab stops (one for dnd)
And it is not possible to access the context menu

**Comment by t3chguy** [comment]
This isn't something we can do much about due to how beautiful DND works, its not really intended for dragging around individual buttons, more for entire containers

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md#keyboard-shortcuts-keyboard-dragging

**Comment by SimonBrandner** [comment]
Spaces are now in beta
