### ISSUE TITLE
Misaligned profile photo when list of rooms is minimized

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/element-web#14613]
### Description

The profile photo is misaligned when the list of rooms bar is collapsed, it should be in the center. It seems like that when you collapse it the room icons do move to the center, and the profile photo remains at the same location, hence the misalignment.

[Screenshot here.](https://i.imgur.com/RWyoMYX.png)

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by niquewoodhouse** [comment]
<img width="690" alt="collapsed - user avatar" src="https://user-images.githubusercontent.com/1587166/88383731-f494a600-cda2-11ea-8792-a26b02823710.png">

[Figma reference](https://www.figma.com/file/rHnynEgrePUtXVear8rGT0/34-Room-List?node-id=2016%3A95705)

**Comment by aaronraimist** [comment]
This particular issue seems to be fixed but there are many other things which are misaligned. https://github.com/vector-im/element-web/issues/19332
