### ISSUE TITLE
ddg command is confusing

### ISSUE THREAD

**Issue by lulucasono** [vector-im/element-web#14625]
### Description
I type /ddg eyebleach and got confused
### Steps to reproduce
type /d  you will see a proposition for /ddg [query]
<img width="676" alt="Screenshot 2020-07-19 at 00 55 26" src="https://user-images.githubusercontent.com/22883663/87863394-d2da8f80-c95a-11ea-9676-f9c2cad88524.png">

try to use using any query.

expectation: none

result: got an error message

<img width="758" alt="Screenshot 2020-07-19 at 00 55 37" src="https://user-images.githubusercontent.com/22883663/87863392-d1a96280-c95a-11ea-82c1-832a2a39bc36.png">

Logs being sent: no

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Firefox Nightly 80.0a1 (2020-07-17)
- **OS**:  MacOs
- **URL**: app.element.io

**Comment by t3chguy** [comment]
Not everything gets a coherent result; see how it is meant to work:

![image](https://user-images.githubusercontent.com/2403652/87872423-3cd15400-c9b0-11ea-832e-f05a530aac3c.png)

**Comment by lulucasono** [comment]
/ddg matrix doesn't work either.

I have been told by a friend that /ddg is an integration(i don't know what an integration is). does this mean that the use(me) should do something to make it work ?(I just want to share how lost I am, and I am not using the issues as support)

I don't know what I have to do because all i get when i search for matrix duckduck go command on my search engine there are mostly results about the movie. (just proving how frustrating this can be)

My problem isn't with /ddg working, it is that it doesn't work and the message I get is confusing.
The suggestion tab is who suggested me to use the /ddg command.
When the interface tell me that the command doesn't exist it contradicts itself.

I could RTFM, if i can find it, and fix /ddg on my computer. But what I am trying to express here is that the interface is giving me mixed signals and I can't easily find proper help.
Maybe a link to the doc in that message would help, or changing the message explaining what we can do to make it work.

**Comment by t3chguy** [comment]
I didn't hit enter, I just type `/ddg matrix` and wait for results

Do you have any browser extensions which like to block things, such as privacy badger or uMatrix?

**Comment by lulucasono** [comment]
Hello,
and thank you for the replies

I have tried to wait for results
I have disabled privacy badger to be able to connect to element, i also have uBlock origin. I have disabled and enabled all my extensions, it works in both cases.

<img width="569" alt="Screenshot 2020-07-19 at 13 17 30" src="https://user-images.githubusercontent.com/22883663/87873485-364bd800-c9c2-11ea-9de4-6c36c69a65bc.png">

That was unexpected hahaha.

I was confused by
> To use it, just wait for autocomplete results to load and tab through them.

Autocomplete results can mean the duckduckgo results but also command automplete results.
With the window title being 
> /ddg is not a command

i was more inclined to believe that /ddg was not working. 
Maybe there are things on element that start with / and are not commands, but command being such a general noun, it is easier to read it as /ddg is not recognized instead of /ddg is from another category of things that start with / and you can't use it like a command.

Sorry if this is annoying, I am just trying to provide the most accurate feedback on why I got confused.

**Comment by aaronraimist** [comment]
The /ddg command has been removed
