### ISSUE TITLE
Room list chevrons are different weights

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14663]
Work out which room list chevron is the correct weight: [right](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/img/feather-customised/chevron-right.svg) or [down](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/img/feather-customised/chevron-down.svg).

The main step is working with Design to resolve the difference.

**Comment by benedikrok** [comment]
The correct chevron is this one (used for right and down): https://www.figma.com/file/KhVjYAzy4oX3eIqwu9KQxN/Design-Kit?node-id=2753%3A8454
the thickness of it is set to: 1.5px
