### ISSUE TITLE
Dragging groups in the TagPanel has regressed

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14668]
It seems like it no longer considers the height of the tile when it is being dragged, leading to all kinds of weird artifacts and jumping

**Comment by t3chguy** [comment]
It also goes under the room list on Chrome :D

![image](https://user-images.githubusercontent.com/2403652/88101324-b5453a00-cb95-11ea-9ad4-154a68a943ce.png)

**Comment by turt2live** [comment]
SUCCESS
