### ISSUE TITLE
links from the matrix.to site are broken

### ISSUE THREAD

**Issue by awesome-michael** [vector-im/element-web#14661]
### Description

When a share link for a room is generated the corresponding homeserver is attached with the via parameter to the URL (e.g. `https://app.element.io/#/room/!<room id>:example.org?via=example.org`). When the link is opened with a browser the client tries to register a guest account on matrix-client.matrix.org instead of example.org or (if a user is already logged in) tries to open the room with the given room id on matrix-client.matrix.org instead of example.org.

### Steps to reproduce

- Create a share link to a room on a non matrix.org homeserver
- Use that link on another browser
- The other browser registers a guest account at matrix.org or tries to log into the room with the given id on matrix.org

Expectation:

The client should use the homeserver given by the via parameter in the link to register the guest account or trying to join the room.

### Version information

web version

Tested in Chrome, Safari on macOS

**Comment by turt2live** [comment]
how are you copying this link? It shouldn't mention app.element.io anywhere.

**Comment by awesome-michael** [comment]
Sorry I left out the step via matrix.to. I generate the link in the webclient, translate it through matrix.to and get the link mentioned above.

**Comment by awesome-michael** [comment]
Honestly I don't think the links are broken, its the client that defaults to the configured default homeserver instead of using the homeserver given by the link in the via parameter.

**Comment by turt2live** [comment]
that sounds super broken to me - it should be using the logged in session, and should be able to use the via params.

**Comment by awesome-michael** [comment]
Hmm maybe I misinterpreted the title. It sounds like the link generation on matrix.to is broken.

Also just for clarification: the logged in session is used. But the via parameter is not.

**Comment by t3chguy** [comment]
The via parameter is passed to the server to specify what server to use to bootstrap the join. It does not specify what server to connect to as a user.

**Comment by awesome-michael** [comment]
Is that the way it is supposed to be? So I can't create invite links to rooms that are not on matrix.org or a server federated with matrix.org?

**Comment by t3chguy** [comment]
> not on matrix.org

Rooms don't belong to a server, the `via` in the link should instruct the client to perform the join via that server, regardless of what server you are registered on, so it should work as long as federation is functional.

**Comment by awesome-manuel** [comment]
But we need it for a server without federation. Which means the room actually does belong to that server.
This is especially relevant if the user has no account yet and could join as a guest.

**Comment by t3chguy** [comment]
I believe the ongoing matrix.to (two) redesign is going to address unfederated servers better.

**Comment by awesome-manuel** [comment]
> I believe the ongoing matrix.to (two) redesign is going to address unfederated servers better.

Again, it's not a problem of the links or matrix.to, it's the client that does not correctly handle the links.

**Comment by t3chguy** [comment]
Yes but part of that project is changing how Element deals with the links after updating the spec with provisions for other clients to follow suit

**Comment by turt2live** [comment]
Currently using matrix.to for an unfederated environment isn't supported (this is something that project is working on, but not something that should be tracked here). Element does support a `permalinkPrefix` config option for this exact scenario though: making useful links from a self-hosted non-federated environment.
