### ISSUE TITLE
TagPanel and TagOrderStore should be called something like GroupFilterPanel and GroupFilterOrderStore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14670]
They do nothing with tags, and it's confusing.

**Comment by RinkiyaKeDad** [comment]
Hey @turt2live I'd like to work on this. Can you tell me a bit more about it. Where can I find TagPanel and TagOrderStore?

**Comment by turt2live** [comment]
They'll be in the matrix-react-sdk - the vast majority of Element is stored there.

#element-dev:matrix.org is best for these sorts of questions
