### ISSUE TITLE
Square windows borders on macOS desktop app

### ISSUE THREAD

**Issue by alicerunsonfedora** [vector-im/element-web#14678]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

The window chrome in the desktop version on macOS seems to have square borders instead of the default rounded ones. I'm unsure if this is a Big Sur or Electron bug.

### Steps to reproduce

- Install Element.
- Open the window.
- Look at the window chrome and wonder which carpenter forgot to sand off the corners...

Describe how what happens differs from what you expected.

I expected the window corners to match the other corners in macOS windows with the same border radius.

Logs being sent: yes

<img width="206" alt="image" src="https://user-images.githubusercontent.com/13445064/88062826-5355e780-cb37-11ea-873c-14f0c49d1364.png"/>

### Version information

- **Platform**: Desktop, v1.7.1

For the desktop app:

- **OS**: macOS
- **Version**: 11.0/10.16 (20A4300b)

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/8749

**Comment by alicerunsonfedora** [comment]
Appears to be more on the Electron/Big Sur end: https://github.com/electron/electron/issues/24319#issuecomment-661986360

**Comment by t3chguy** [comment]
This got fixed
