### ISSUE TITLE
Custom tags are missing indication for unreads / need design

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#14679]
I think riot with the old roomlist had some indicators that in the custom tags had rooms with unread messages. This seems to be missing in the new implementations. I know this feature will never get much love (which is really sad as it is a very good feature as long no alternative like groups exist properly) but I would like to at least have the same behaviour as the old room list had.

**Comment by turt2live** [comment]
Going to hijack this for general custom tag design as well, as it's all roughly in the same area.

**Comment by niquewoodhouse** [comment]
What's the best way to see what custom tags/this issue used to look like, to be able to port it into the new designs?

**Comment by t3chguy** [comment]
https://riots.im + https://tags.t2bot.io

**Comment by niquewoodhouse** [comment]
Thanks @t3chguy.  

So I just made a custom tag, put rooms in it and save > return to Element > can't see them anywhere.  Is anyone else getting that?  Have I missed something?

**Comment by turt2live** [comment]
@niquewoodhouse they also need to be enabled from Settings -> Labs -> Group & filter rooms by custom tags, then refresh the page.

**Comment by turt2live** [comment]
it's also worth noting that there's quite a few thoughts about how the previous behaviour worked, so ideally this gets more treatment than just bringing it into the new design.

**Comment by MTRNord** [comment]
PS: as you mentioned above that you hijack this for general design stuff with custom tags: Wanted to mention that since some of the last commits the "clicked" indicator bar left of the "badge" in the far left column seems to be offset by a few pixel to the bottom instead of being centered. Which also causes the div in which the custom tag round things are to overflow a bit when clicking the last tag in the list :)

![grafik](https://user-images.githubusercontent.com/1374914/88444227-6d841400-ce1c-11ea-9535-b977a87681b6.png)

**Comment by niquewoodhouse** [comment]
> it's also worth noting that there's quite a few thoughts about how the previous behaviour worked, so ideally this gets more treatment than just bringing it into the new design.

Cool, thanks.  Who do you think would be best placed to summarise those thoughts?  Sounds like I should have a session with them before considering design.

**Comment by turt2live** [comment]
We're removing custom tags in favour of spaces. This is more formal as https://github.com/matrix-org/matrix-react-sdk/pull/8027
