### ISSUE TITLE
If a search criterium doesn't include persons, make DownArrow skip the persons node

### ISSUE THREAD

**Issue by MarcoZehe** [vector-im/element-web#14713]
In the room list side bar, after pressing CTRL+K and entering a search term, if the search results don't contain persons, Down Arrow should skip the empty Persons node and move straight to Rooms.

**Comment by t3chguy** [comment]
If this was done, then you would lose the ability to reach `Start Chat` which is accessible via Tab from the `People` treeitem

**Comment by t3chguy** [comment]
Searching the treeview isn't a thing anymore
