### ISSUE TITLE
Error when integrations manager can't be loaded

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#14718]
A number of things can cause the integrations manager not to load, eg. being on a homeserver that the integrations manager can't contact, a browser extension blocking the integration manager iframe URL, a bad integration manager being set in the config or the integration manager itself being down. The failure mode in, I think, all of these cases is that you get a white box where the integration manager should be.

There should be at least some kind of error message, ideally one that gives you some idea which of the above failure modes you're encountering today.

**Comment by philibertc** [comment]
On some browsers there is an integrated third-party cookie blocker. The cookie "scalar.vector.im" is blocked by default.

**Comment by t3chguy** [comment]
We seem to have this already?

![image](https://user-images.githubusercontent.com/2403652/96259547-ae23a180-0fb5-11eb-86ba-39aa0b3e395a.png)


Will try to repro the case where it may not show up.

**Comment by t3chguy** [comment]
So we show the error if we don't have a token for it, but if we do and the iframe loads then we don't

**Comment by t3chguy** [comment]
I'm going to try repro any additional edge cases in some paranoid browser envs
