### ISSUE TITLE
consider bringing back link underlines for a11y

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#14737]

**Comment by erikkroes** [comment]
The blue color is the only way to distinguish a link from normal text right now. Not everybody is able to see this difference. Adding underlines would clarify this and adhere to expectations from users as it has affordability.
https://adrianroselli.com/2019/01/underlines-are-beautiful.html

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/24932
