### ISSUE TITLE
Room list search should get an explicit title/aria-label

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#14733]
as the placeholder vanishes whilst you are using it

**Comment by turt2live** [comment]
Related: we might need to work on the label for the search field https://github.com/dequelabs/axe-core/issues/2413

**Comment by erikkroes** [comment]
Title and aria-label is also redundant in most cases. The preferred solution is a visual label when possible. This helps everybody. When a visual label is not possible, text can be put inside a node but visually hidden (so screen readers can still pronounce it). When picking between aria-label and title, the first is a much more solid solution.

**Comment by t3chguy** [comment]
This got fixed with Spotlight
