### ISSUE TITLE
Add a confirmation dialog to the "ignore" button

### ISSUE THREAD

**Issue by MatMaul** [vector-im/element-web#14746]
So I got burn a month ago and @richvdh just got burn too: would it be possible to add a confirmation dialog to the `ignore` button ?

There is currently none, and 0 visual feedback => it's really easy to do that unwillingly.

**Comment by t3chguy** [comment]
>  0 visual feedback

It changes to an `Unignore` button no?

![image](https://user-images.githubusercontent.com/2403652/88390432-3546ec00-cdb0-11ea-8585-5250a33597bc.png)

**Comment by richvdh** [comment]
mine was in riot-x actually

**Comment by MatMaul** [comment]
Indeed :) I went to fast for my homeserver when doing so.

**Comment by richvdh** [comment]
cf https://github.com/vector-im/riotX-android/issues/1318

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/14633 https://github.com/matrix-org/matrix-doc/issues/1803
