### ISSUE TITLE
Initializing desktop client with verification shows loading screen for more than 2 minutes

### ISSUE THREAD

**Issue by Y0hy0h** [vector-im/element-web#14749]
### Description

I've just started playing around with the new Element clients and I'm mostly really happy.

After installing it on my Android phone, I wanted to try out the desktop client on Windows. I logged in and it prompted me to verify the device. I scanned the QR code and the desktop client started showing a loading screen stating something like "Verifying..." But that screen never away.

I could stop the desktop client via the Windows menu bar thing and it would load the chats, but asking me to verify the device as apparently it failed previously. When I accepted to verify, I waited a short while but no toast appeared on mobile.

I then disabled the desktop session from mobile and logged in on desktop a few times, but always with the same loading problem. Once I received a message while it was loading and I heard a sound and a Windows toast appeared showing the message.

Interestingly, I had sent one message from my phone with the security option named something like "Only send to verified sessions", so that message said it couldn't show. I clicked the link below that said something like "request session keys" and suddenly the message appeared and my phone shows the desktop session as verified. However, restarting the desktop client 
still asks to verify its session.

### Steps to reproduce

A friend had the same loading screen on Windows, so I assume:

1. Log into Element on your phone.
2. Install Element on your Windows desktop.
3. Attempt to verify the desktop session.
4. Stare at the loading screen.

I expected the loading screen to finish in a reasonable amount of time and show the desktop session as verified.

Logs being sent: yes

The following is a screenshot from my friend's loading screen that does not finish in a reasonable time. (Mine is in German.)
![loading screen](https://user-images.githubusercontent.com/11377826/88421821-790a1780-cde9-11ea-9cc7-94113f391a6b.png)

### Version information

- **Platform**: Desktop

- **OS**: Windows 10 (Version 1909)
- **Element Version**: 1.7.2 (olm 3.1.3)

**Comment by easyKL** [comment]
Same here.
Mobile verified straight away, but desktop stuck on that same screen (as screenshot shows).
I can close, reopen and I'll end up there.
Verification is not asked again, just the turning wheel of verification.
Also on **v1.7.2** but this time running on **Ubuntu 20.04**

**Comment by Y0hy0h** [comment]
@easyKL Closing the window is not enough; when you reopen it will still show the loading screen.

However, you should have some option to quit Element. On Windows it's in the bottom right toolbar, sometimes hidden in the overflow menu. Right clicking the Element icon should give you the option to stop Element. When you restart it then, it should load up correctly, though verification does not work.

**Comment by easyKL** [comment]
@Y0hy0h Yeah! Quitting instead of just closing the window. I'm sure I tried before.
Now that I open it again, it works!

I manage to have access to my account on the desktop! (mobile was OK)
I had a warning telling me the account was not verified. I skipped it that pop up.
It happens the account was indeed verified. Yeah!

**Comment by Y0hy0h** [comment]
Yes, my phone says the session is verified, but the desktop client says it's not verified.

**Comment by easyKL** [comment]
Remember the distinction between sessions and ~accounts~ clients.

**Comment by imkreislaufen** [comment]
I can confirm this. My Android device shows my desktop session as verified, but the desktop client still asks for verification + gets stuck during the verification process as the screenshot shows. The same problem occurs when loggin in over the web-platform.

**Comment by jryans** [comment]
Thanks for the feedback and sorry for the trouble here. I believe this is the same as https://github.com/vector-im/element-web/issues/14970, which has some fixes in progress, so this should soon be working. I'll close this as a duplicate.
