### ISSUE TITLE
Add ability to show/hide community filter panel from the main UI

### ISSUE THREAD

**Issue by dannycolin** [vector-im/element-web#14744]
**Is your suggestion related to a problem? Please describe.**

I'm on a laptop and I often have two browser windows side-by-side. In order to maximize the screen space, I hide the userlist but I can't do the same with the community filter panel. Currently, the only way to show/hide it is via the settings but it's a bit cumbersome when you have to do it frequently.

**Describe the solution you'd like**

I'd like to have a button like the one for the user list that let me toggle on/off the community filter panel

**Describe alternatives you've considered**

Having a custom JS script injected with violentmonkey addon but It doesn't work on Firefox due to CORS blocking it

**Additional context**

none

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18898
