### ISSUE TITLE
Hoverover displayname on IRC layout shouldn't left-align

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14757]
I'm not sure there's any point in left aligning; it just makes things pop, and you can resize the column width anyway now if you want to peek.

**Comment by t3chguy** [comment]
This was done on purpose in response to https://github.com/vector-im/riot-web/issues/13724

See https://github.com/matrix-org/matrix-react-sdk/pull/4990

**Comment by yannicka** [comment]
On my side, the displayname is always aligned to the left, even when not hovered.

**Comment by aaronraimist** [comment]
Yeah it appears this has been changed to always left align so this bug doesn't exit anymore https://github.com/matrix-org/matrix-react-sdk/commit/1a9487f1bea05865c23705aa82aaedd43f33bafb
