### ISSUE TITLE
Link to configure the app is invalid

### ISSUE THREAD

**Issue by raphael247** [vector-im/element-web#14751]
### Description

When visiting self hosted version of riot-web with different homeserver and identityserver settings, the "configure your app"-link on mobile_guide/index.html is wrong. This results in "404 not found".

The url is specified in bundles/.../mobileguide.js 
https://app.element.io/config/config?hs_url=....

In former versions it was 
https://riot.im/config/config?hs_url=....
which was working.

Please correct the url or provide correct target.

**Comment by jryans** [comment]
We need to workout with Ops what we want to do with this page... It was not previously hosted inside the app, but rather part of the outer website.

**Comment by jryans** [comment]
Also, if we're changing things here anyway, I'd really like to remove the `/config/config` duplication... Can we make it just be `/config` or something sane like that?

**Comment by t3chguy** [comment]
Surely that'd break backwards compatibility with the apps which likely have that `/config/config` hardcoded?

**Comment by bwindels** [comment]
> Surely that'd break backwards compatibility with the apps which likely have that `/config/config` hardcoded?

the riot.im one is still in place though (for as long as riot.im is in place), and the element.io one is currently broken, so asking people to update for it to work again should be fine.

**Comment by t3chguy** [comment]
> the riot.im one is still in place though (for as long as riot.im is in place)

Sure but riot-web's mobile_guide now links to the new one which the old apps won't intercept.

**Comment by bwindels** [comment]
The work on riot-web is done, but to be fixed the mobile apps need to do something as well, as captured in https://github.com/vector-im/riot-ios/issues/3483 and https://github.com/vector-im/riotX-android/issues/1833

**Comment by kittykat** [comment]
Closing as work is done on all three platforms according to comments and PRs ↑
