### ISSUE TITLE
Cannot select first character of line in IRC mode

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#14764]
Cannot select first character of line in IRC mode

> In IRC mode, I cannot select the first character of a line of a message.  It seems the "change the margin position" interferes.  When copying a line, I have to select all but the first character, and type that myself when pasting.
>
> -- https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$y1xLPOa1zv70Bo2miLmL6_v9S4QeWszl0_QndFe8eIE?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by yannicka** [comment]
> In IRC mode, I cannot select the first character of a line of a message.  It seems the "change the margin position" interferes.  When copying a line, I have to select all but the first character, and type that myself when pasting.

I can't reproduce the problem, is it happening again?

**Comment by Biep** [comment]
Yes, it is still happening on 1.7.14 Desktop under Ubuntu.  Clicking somewhere in a line of a message, and then dragging for selection to the left does select more and more of the line, but when I reach the first character, the cursor changes to a horizontal double arrow, and the selection expands to include all previous text in the timeline.

**Comment by luixxiul** [comment]
It looks the issue is caused by the resizer area covering the first character, as displayed below:

> ![before1](https://user-images.githubusercontent.com/3362943/178091049-d09d217a-f2c7-4288-a60d-a55ea72d659c.png)

See: https://github.com/vector-im/element-web/issues/22782 for the original image.
