### ISSUE TITLE
Having multiple of the same widget makes it impossible to manage the integrations

### ISSUE THREAD

**Issue by msuess** [vector-im/element-web#14771]
### Description

Adding multiple instances of the same widget to a room makes it impossible to change their settings later.

### Steps to reproduce

- Open the integrations manager
- Follow the steps to add any widget to the room, eg. EtherPad
- Add the same widget to the room again
- Open the integrations manager
- It will look like this:

![imbug](https://user-images.githubusercontent.com/337886/88505828-d1533c00-cfd8-11ea-91db-572f281c5034.png)

- Click on the greyed out integration icon
- An alert will pop up saying "You can edit these widgets by clicking on the pen icon at the top of the widget frame."
- There is no pen icon:

<img width="1028" alt="nopen" src="https://user-images.githubusercontent.com/337886/88505997-3f97fe80-cfd9-11ea-8010-f53e8728707d.png">

- Clicking on the three dots menu reveals an edit item
- Clicking on "edit" reveals the integration manager with the greyed-out icon again, making it impossible to change the widget settings

Clicking on "edit" should open the settings page of the widget in the integration-manager iframe. The alert message should include instructions to open the three-dots-menu.

Logs being sent: yes/no

### Version information

- **Platform**: web
- **Browser**: latest Chrome, latest Firefox
- **OS**: macOS, Ubuntu
- **URL**: riot.im/develop / riot.im/app

### Additional Info

There is a `screen` query param in the iframe url of the integration manager but it's set to `type_undefined`:

`http://localhost:5051/?scalar_token=REDACTED&room_id=REDACTED&room_name=REDACTED&theme=light&integ_id=REDACTED&screen=type_undefined`

**Comment by jryans** [comment]
@msuess Is this fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5081?

**Comment by msuess** [comment]
@jryans yes!
