### ISSUE TITLE
After every update the Windows Firewall promts on first call

### ISSUE THREAD

**Issue by bessw** [vector-im/element-web#14788]
### Description

After every update of Element / Riot, when I'm receiving or starting the first voice call after the update, the Windows Firewall promts that a new application requested to open a port.

This probably happens because the path of the executable changes with every update (version number in its name).

### Steps to reproduce

- restart after an update of Element
- start / receive a call

Describe how what happens differs from what you expected.

I would expect that calls still work after a update and you don't have to have your system administrator around when you want to answer a call after an update.

Logs being sent: no

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Windows
- **Version**: any until now (1.7.2)

**Comment by novocaine** [comment]
Note that this bug refers to the firewall triggering on *calls* whereas https://github.com/vector-im/element-web/issues/15973 seems to be about the firewall triggering in general.

**Comment by novocaine** [comment]
Our plan is to try building with `enable-webrtc-hide-local-ips-with-mdns` disabled to see if that prevents the firewall from prompting.

**Comment by t3chguy** [comment]
Close in favour of https://github.com/vector-im/element-web/issues/18338
