### ISSUE TITLE
Share message is the only action in message context menus using colour

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#14786]
<img width="232" alt="Screenshot 2020-07-28 at 10 36 30" src="https://user-images.githubusercontent.com/4626865/88648893-531d9500-d0bf-11ea-926d-b40e30866dcf.png">

This is (deliberate?) due to it picking up styling from a class indicating it can be right clicked/copied to clipboard. The incidental effect though is that it's highlighted in the hierarchy with little affordance why. We should iterate on this considering any of:

- Not applying colours to this action
- Adding a copy to clipboard quick action/icon
- Improving legibility & ability to scan by splitting up actions into a hierarchy of groups (using horizontal rules)
- Improving ability to scan by using iconography on actions

**Comment by t3chguy** [comment]
This is no longer the case
