### ISSUE TITLE
Avatars in Replies are visually noisy

### ISSUE THREAD

**Issue by polwel** [vector-im/element-web#14794]
### Description

In replies the name and avatar of the original poster are quoted. They are not easily distinguished from actual messages.

In the screenshot, the entire screen shows messages posted by a single user. The avatar of the OP is further up, off-screen.

The reply disrupts the message, and *many* readers were confused that the following part of the message was not by the quoted person.

I have redacted the content, in reality the crisp text makes the issue much worse for some reason.

To a lesser extend, the same problem applies to the mention. A mention at the start of the message (as it often is) looks like the mentioned user actually authored the message.

![image](https://user-images.githubusercontent.com/7679808/88679197-7ceeb000-d0ef-11ea-8068-e584892d9d2c.png)

While I am at it, I suggest a border/drop-shadow around uploaded images. RN, they blend into the text message a bit too well. Given that there already is a *'Download image'* button, they shouldn't.

### Suggested changes

Maybe mute the avatar/name in quotes? Make the avatar smaller? In the latter case, the flair icons will probably be too distracting.

### Version information

- **Platform**: Element Web 1.7.2, hosted on-premises. All browsers.

**Comment by polwel** [comment]
Actually, thinking about it some more, it might be best if the quoted message has

- a smaller avatar,
- muted user name,
- muted body text,
- collapsed body if the length exceeds a few lines.

The horizontal indent of the quote body takes up precious space, and might not be necessary.

**Comment by t3chguy** [comment]
Most of your complaints are already tracked: https://github.com/vector-im/riot-web/issues/7633 https://github.com/vector-im/riot-web/issues/7530

**Comment by polwel** [comment]
Oh wow, matrix-org/matrix-react-sdk#3553 looks like it will solve all my gripes!

Thanks @t3chguy, I came across the PR when browsing the issues you linked. Fingers crossed it can be merged soon.

**Comment by robintown** [comment]
@polwel https://github.com/matrix-org/matrix-react-sdk/pull/3553 has been merged :)
