### ISSUE TITLE
couldn't reply to my own messages immediately after sending

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#14803]
they had fully sent, but until i switched away and back to the room, i only had an edit + context menu button on the eventtiles - no react or reply

**Comment by turt2live** [comment]
was seeing this:
![image](https://user-images.githubusercontent.com/1190097/88722593-bec62900-d0e4-11ea-89ec-a62ff6ef1209.png)

**Comment by t3chguy** [comment]
Sounds like MessageActionBar isn't updating on event status changing

**Comment by Cadair** [comment]
This is very annoying in a room where the slack bridge lives as you can't reply into threads any more :cry:

**Comment by freelock** [comment]
Same here, annoying enough to come here to report...

**Comment by ara4n** [comment]
this is driving me nuts; turns out i constantly reply to my own messages in order to help with threading (even in pure Matrix).
