### ISSUE TITLE
Add Element to Windows Chocolatey

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#14809]
**Is your suggestion related to a problem? Please describe.**
I would greatly simplify mass adoption in companies (and for lazy windows users !).

**Describe the solution you'd like**
Release Element to Chocolatey as part of the regular Element release cycle.

**Comment by t3chguy** [comment]
> and for lazy windows users

Doesn't it have no auto-update mechanism so that laziness would mean running outdated (insecure?) code?

**Comment by Twi1ightSparkle** [comment]
Dunno, never used Chocolatey. But from what I gather it's `homebrew` for Windows. And I assume it can be used to mass-deploy and update software?

Also presumably, once you `chocolate install element` (or whatever the command is), the E app will update itself anyway when a new version is released?

**Comment by t3chguy** [comment]
Ah yes, looks like the chocolatey literally just downloads our installer and runs it.

https://github.com/TakataSanshiro/Chocolatey-Packages/blob/master/automatic/riot-web/tools/chocolateyInstall.ps1

**Comment by t3chguy** [comment]
It does seem like a pain for the team to have to keep up to date on every release, seems like a nice thing for the community to pick up.

**Comment by Twi1ightSparkle** [comment]
The PowerShell script cannot be modified to just always grab the latest installer instead of a specific version?

**Comment by t3chguy** [comment]
Sure it could, but I don't think that'd be acceptable for Chocolatey which is versioned and requires a fixed checksum (so unless we make an installer for the installer) it wouldn't work

**Comment by t3chguy** [comment]
https://github.com/TakataSanshiro/Chocolatey-Packages/blob/master/automatic/riot-web/tools/chocolateyInstall.ps1#L8-L11

**Comment by t3chguy** [comment]
It seems strange that they stopped maintaining at the same time as we stopped supporting 32 bit, the ps1 script has both 32 and 64 bit listed

**Comment by t3chguy** [comment]
Wait, surely given that the autoupdater works doesn't https://chocolatey.org/packages/riot-web complete this goal? User installs it and the app self updates.

**Comment by t3chguy** [comment]
https://community.chocolatey.org/packages/element-desktop is a thing, @Twi1ightSparkle is there any good reason this must be a first party package? Part of spirit of open source is community maintained packaging.

**Comment by turt2live** [comment]
At the moment we're not able to justify this as a first-party deployment (far too many complications for our release process). If at a later date this is highly requested we can take a second look, however for the time being we don't have plans to do this.
