### ISSUE TITLE
Creating new room with 3pid invite doesn't include id server access token

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#14814]
https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-createroom says that `Invite3pid` *requires* an `id_access_token` (it was added in a breaking change in r0.6.0). Currently, element-web doesn't seem to be sending one.

The result of this is that Synapse falls back to the deprecated `/_matrix/identity/api/v1/lookup`, which, via other bugs, leads to the createRoom request failing with a 500 error (see https://github.com/matrix-org/synapse/issues/5253).

**Comment by richvdh** [comment]
I think some ID servers will reject lookup requests without access tokens, so presumably anyone trying to use one is going to have a bad time here.

**Comment by t3chguy** [comment]
I came accross this when typing the createRoom class and was almost sure it was js-sdk injecting it. Will double check this if I have time
