### ISSUE TITLE
Appending mxids to display names is strange

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#14825]
<img width="398" alt="Screenshot 2020-07-30 at 13 45 51" src="https://user-images.githubusercontent.com/4626865/88925229-25c21a00-d26c-11ea-8749-a9e572dba8f0.png">

<img width="360" alt="Screenshot 2020-07-30 at 13 53 14" src="https://user-images.githubusercontent.com/4626865/88925226-2490ed00-d26c-11ea-813f-667ca7bb902b.png">

It appears we have some logic to append mxid's to display names in the member list & on reaction tooltips on occasion, presumably when multiple matching display names are detected.

The current implementation suffers from poor legibility when scanning, harming usability.

We should consider either (a) not doing this at all, leveraging the social dynamics of people using different display names/profile pictures/contextual mxid's in profiles (b) if we need to explicitly print mxid's, stylising them differently

**Comment by t3chguy** [comment]
> not doing this at all,

Huge privacy issue

**Comment by nadonomy** [comment]
> > not doing this at all,
> 
> Huge privacy issue

I'm not sure it's this black and white at all— mxid's are available contextually, through hover interactions, when accepting invites etc, and through master/detail views (e.g. profile pictures). There are likely other opportunities too in other hover interactions (like, when we display admin/mod on hover).

**Comment by babolivier** [comment]
I'm also seeing the issue with my account, but only in some rooms, following splitting my Matrix activity between two accounts last week (so in a bunch of rooms I had my previous account invite the new then leave). In some of these rooms Element displays me as "Brendan Abolivier", in some others "Brendan Abolivier ([my new MXID])", despite the fact that in both cases there's only my new account in the room (the previous one has left).
I've rageshaken in case logs help.

**Comment by t3chguy** [comment]
Sure but I can come into a room, craft an mxid and have the same displayname avatar and colour as you and impersonate you

**Comment by aaronraimist** [comment]
This has been pretty much fixed now in the timeline by https://github.com/matrix-org/matrix-react-sdk/pull/5880

Would be nice to bring a similar change to the right panel

**Comment by SimonBrandner** [comment]
> Would be nice to bring a similar change to the right panel

/me adds it to his TODO list

**Comment by aaronraimist** [comment]
Reopening since it was reverted. New PR is https://github.com/matrix-org/matrix-react-sdk/pull/8110
