### ISSUE TITLE
Element won't open at all.

### ISSUE THREAD

**Issue by GentleJr** [vector-im/element-web#14835]
I'm having a problem where Element won't open at all. When I click the exe nothing happens.

I tried reinstalling and that fixed it until I restarted my PC and it was broken again with the same issue.

I've tried looking for it in the task manager but don't see it there. On windows 10 64x.

**Comment by Restioson** [comment]
Same for me on Windows 10 AMD64.

**Comment by t3chguy** [comment]
Should be fixed in latest release, see https://github.com/vector-im/element-web/issues/14789
