### ISSUE TITLE
Invite context

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#14832]
I'm _sure_ we've discussed this before but I can't for the life of me find the issue.

Anyway, it would be nice to share some additional context when you invite a user to a chat room - this could (and perhaps should) be as simple as a message from the inviter. To try to avoid misuse as a spam/harassment vector, I think the invite UX should hide the invite context by default.

I mocked this up a short while ago, but the idea came up in conversation today so filing as a suggestion here:
![Invite Context](https://user-images.githubusercontent.com/1922197/88951009-56ff1200-d28d-11ea-905c-1695ce838a80.png)

**Comment by turt2live** [comment]
fwiw invites can now contain a `reason` field, we just ignore it.

**Comment by robintown** [comment]
@turt2live Is that documented somewhere? I would like to try to implement this.

**Comment by robintown** [comment]
nvm, found it in the unstable spec

**Comment by SimonBrandner** [comment]
[#16300](https://github.com/vector-im/element-web/issues/16300) is somewhat related. Maybe merging these into one woldn't be a bad idea
