### ISSUE TITLE
Supervised accounts

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#14849]
Please allow accounts where each room automatically invites a given supervisor.  Parents and teachers could use that to check for possible abuse.  A person with a restricted account cannot enter a room unless that account's supervisor has entered.  (I thought I had already proposed that, but can't find it.)

**Comment by turt2live** [comment]
This would be best implemented on a custom server implementation.

**Comment by KB1RD** [comment]
Implementation could be complicated and there are a few things that might need to be considered:
1. Who enforces this? Presumably the originating server for the supervised account
2. How is this enforced in an invite-only room where the supervised account cannot invite? Or any situation where the supervisor cannot access the room?
3. How do you enforce sender encryption to both the supervised account and the supervisor in E2EE?
I've been thinking about doing this in a fork of Matrix Corporal, but it could get fairly complicated.
