### ISSUE TITLE
Upgrade Weblate on translate.riot.im

### ISSUE THREAD

**Issue by tjhietala** [vector-im/element-web#14846]
**Is your suggestion related to a problem? Please describe.**
Weblate version 3.6.1 on translate.riot.im is over a year old now and many improvements have been made upstream since then, including improved search and the ability to share glossaries across projects.

**Describe the solution you'd like**
Upgrade to the latest version (4.1.1)

Also, shouldn't the URL be changed to translate.element.io now?

**Comment by turt2live** [comment]
this is tracked internally
