### ISSUE TITLE
Automatically generate i18n strings for |few, |many, |other, |zero, and |one

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14845]

**Comment by strixaluco** [comment]
Thanks for opening the issue. I'll leave several references below.

[Weblate administrator docs - Language definitions - Plural formula](https://docs.weblate.org/en/latest/user/translating.html#plurals)
[Weblate user docs - Translating using Weblate - Plurals](https://docs.weblate.org/en/latest/admin/languages.html#plural-formula)
[CLDR v37.0 Language Plural Rules chart](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html)

**Comment by gsouquet** [comment]
It appears that counterpart only supports `zero`, `one` and, `other` https://github.com/vector-im/element-web/issues/16463#issuecomment-779816281.

An upstream issue has been created martinandert/counterpart#50 
We might want to revise the target of this issue once the above has been tackled

**Comment by waclaw66** [comment]
@gsouquet Many, few, ... are already supported for languages which distiguesh them, check upstream https://github.com/martinandert/pluralizers/blob/master/ru.js

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/13061
