### ISSUE TITLE
Hide from user

### ISSUE THREAD

**Issue by chadcoulter** [vector-im/element-web#14842]
So when using chat sometimes a particular user can start harassing or creeping that user or sometimes its just a history that creates conflict.  

Lets implement a feature that is like forcing someone else to ignore you.  but the control is competely in the control of the taking the action.

I would limit the action to taking affect the next time the target user is logged in to avoid allowing a user to harass another user by causing their messages to blink off and on by repeatedly setting and then unselecting the hide from user feature.

**Comment by t3chguy** [comment]
The way that Matrix works this is not possible. You send your message into a Room and that Room has exactly 1 copy of the message (replicated to all servers within that room)
Then any users in that room are able to request that copy from their server.

If you want this to be possible in Matrix then I suggest opening an issue in https://github.com/matrix-org/matrix-doc/issues

For encrypted rooms this is kind of possible using blacklisting: https://github.com/vector-im/element-web/issues/11751
