### ISSUE TITLE
Toggling message previews in the room list does nothing

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/element-web#14853]
### Description

Toggling on the "show previews of messages" checkbox in the room list does nothing.

### Steps to reproduce

- In the room list, hover over the rooms section and open the meatball menu.
- Turn on the "show previews of messages" option.

No message previews appear. I expected message previews to show underneath each room name in the room list.

Logs being sent: yes

![screenshot](https://user-images.githubusercontent.com/128854/89097579-7af45c00-d423-11ea-8a43-1ae77712a2a4.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 79
- **OS**: Arch Linux
- **URL**: riot.im/develop and Radical 1.7.2

**Comment by turt2live** [comment]
Fixed in the RC

**Comment by auscompgeek** [comment]
It still seems broken for me on 1.7.3.

**Comment by t3chguy** [comment]
I can reproduce
