### ISSUE TITLE
SSO web link asking to open with an application

### ISSUE THREAD

**Issue by IgnisFlamme** [vector-im/element-web#14854]
### Description

Not redirecting from the browser to the Element app.

### Steps to reproduce

- Compile from Git repository
- Sign in with mozilla.modular.im homeserver
- Get redirected to SSO
- Press "I trust this service"
- Get the "This link needs to be opened with an application"

It is supposed to seamlessly redirect and log me into Element
![Screenshot_20200801_181951](https://user-images.githubusercontent.com/40430739/89099680-b0994500-d423-11ea-9db9-9957805eae63.png)

Ignore the entries on the selection. I was trying to get it to work but none work properly.

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop (Compiled from Github Release 1.7.2)

For the desktop app:

- **OS**: Manjaro (Arch based distro)
- **Version**: 1.7.2

**Comment by t3chguy** [comment]
Sounds like a bug with the arch distribution of the app where it is creating two protocol handlers. 
Whether or not it is a seamless experience is up to your OS and Browser.

**Comment by IgnisFlamme** [comment]
@t3chguy This only happens on the new Element app. Riot still works properly. The two handlers you see in the screenshot is my attempts to get it to work.

**Comment by t3chguy** [comment]
> Compiled from Github Release 1.7.2

If you compiled it yourself then it looks like you didn't set up the protocol handler accordingly if it doesn't work.

I suggest checking out the content of the old riot-desktop.desktop file to see how it does it and replicating it for your element-desktop.desktop file.

**Comment by IgnisFlamme** [comment]
@t3chguy 
Whatever changed between Version 1.7.2 and 1.7.3-rc1 has fixed my issue. I recompiled it from the AUR again and now it is working properly.
