### ISSUE TITLE
/msg always creates encrypted rooms even if recipient can't use encryption

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#14851]
User in #element:matrix.org wanted to use @appservice-irc:matrix.org so they typed `/msg @appservice-irc:matrix.org whatever` and it created an encrypted room. It shouldn't do that since @appservice-irc:matrix.org doesn't have any devices capable of encryption. Using the UI to create the DM works correctly.

**Comment by t3chguy** [comment]
Hmm, both paths use `canEncryptToAllUsers`

**Comment by t3chguy** [comment]
Cannot reproduce,
I used `/query @appservice-irc:matrix.org` and it opened the room in plaintext
![image](https://user-images.githubusercontent.com/2403652/89707658-2e030f00-d968-11ea-9ad7-79ff07029029.png)

Same for `/msg`

![image](https://user-images.githubusercontent.com/2403652/89707667-41ae7580-d968-11ea-84f9-4807bffd74cd.png)

**Comment by wylel** [comment]
Sorry for the late reply. This is what I see, still on the latest release.

![appserviceencrypt](https://user-images.githubusercontent.com/617189/94500119-10ae2c80-01c4-11eb-82bb-e615dcabd4cf.png)

`/query` does the same thing, starts an encrypted chat.

**Comment by t3chguy** [comment]
Yes they both use the same code path. If the user has any e2ee devices then it'll use encryption.

**Comment by wylel** [comment]
Not sure why mine is doing that, even on different Element instances. What can I do to see whats causing this?

**Comment by t3chguy** [comment]
In the room it creates, can you select the other user in the right panel and show a screenshot of the device list

**Comment by wylel** [comment]
This is all that I see when I click on appservice-irc

![appserviceside](https://user-images.githubusercontent.com/617189/94522019-934ee000-01f4-11eb-898f-c6b6c125313a.png)

**Comment by t3chguy** [comment]
Weird, based on that it should not be encrypted

**Comment by t3chguy** [comment]
I just reproduced, investigating
