### ISSUE TITLE
Lost Security Key and Phrase

### ISSUE THREAD

**Issue by hrqmonteiro** [vector-im/element-web#14874]
### Description

Lost my security key and phrase, cause i changed phone, and my laptop which i had the key on was stolen month ago. So now i lost my account?

### Steps to reproduce

I'm just trying to have the encrypted messages..

### Version information

- **Platform**: web or desktop

For the web app:

- **Browser**: Firefox
- **OS**: Void Linux
- **URL**: app.element.io

**Comment by t3chguy** [comment]
You can reset secure storage in Settings > Security & Privacy

![image](https://user-images.githubusercontent.com/2403652/89391771-8b952280-d700-11ea-8cde-6628b11e2cf4.png)

If you have no devices with decryption keys then you will lose access to encrypted history

This is a bug tracker, use https://matrix.to/#/#element-web:matrix.org for support.

**Comment by cassandracomar** [comment]
this prompts me for the security key which I no longer have? I don't care about losing the encrypted history, I'd just like to restore my account to functionality without deleting my account.

**Comment by rkfg** [comment]
Something is not right. There's no such button as in @t3chguy screenshot, there are two separate `Reset` buttons for secure backup and cross-signing.
![2020-10-22_19-41-01](https://user-images.githubusercontent.com/184066/96903463-8db88300-149e-11eb-86bc-2c9a263af31f.png)
Resetting cross-signing requires a security phrase that I don't have. Resetting secure backup works, I can generate a new key (or enter a new security phrase) but then it asks for it and doesn't accept any of those, neither the phrase nor the key that I've just generated. I tried both desktop and web version and am currently stuck at it.

**Comment by rkfg** [comment]
I opened a new issue about this: #15530

**Comment by t3chguy** [comment]
Yes well my screenshot is from 2 months ago before it changed. Reset is still reset.

**Comment by cassandracomar** [comment]
yeah, the reset button doesn't work. it prompts for the security key and
won't accept the one it just generated.

**Comment by gbt1988** [comment]
So, anyone who knows how to fix this problem? I didn't saved my Security Key and now it shows red nexclamation point everywhere OLO

**Comment by jryans** [comment]
The core team generally does not follow comments on closed issues. In this case, there is now https://github.com/vector-im/element-web/issues/15530, so if that matches your case, either follow along there or please open your own new issue if something is different.
