### ISSUE TITLE
No scrollbar / no scrolling in Favorites/People/Rooms column in Safari 

### ISSUE THREAD

**Issue by badboy** [vector-im/element-web#14877]
## Description

I'm using Element Web in Safari.
There's no scrollbar visible on the Favorites/People/Rooms column on the left,
scrolling in that area doesn't work.
I'm therefore unable to switch to DMs/Rooms further down in the list, especially once I clicked "Show more" in either category.

### Steps to reproduce

- Open chat.mozilla.org in Safari
- Login
- Try to scroll in the left-most column

In Safari, I expect to be able to scroll in the left column. I can't (and no scrollbar is visible).

It works fine in Firefox, and a scrollbar is visible.

### Version information

- Element Web on chat.mozilla.org
- Safari 13.1.2 (on macOS Catalina)
- Firefox 81 (there it works)

**Comment by Twi1ightSparkle** [comment]
Also broken in the same way with my main account using develop.element.io fwiw
