### ISSUE TITLE
Room replicated when added to favourites

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#14871]
Created new room and added to favourites, each new message within the room creates a new entry on the room list:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/51328716/89299083-bbd3b700-d655-11ea-978d-066cb65b438e.png">

Have submitted debug logs.
### Version information

- **Platform**: macOS desktop
Version: Element version: 1.7.2
olm version: 3.1.3

**Comment by t3chguy** [comment]
No reports of this since 2020, shout if you're still seeing this
