### ISSUE TITLE
Early users might struggle to find rooms they should join

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#14870]
**Is your suggestion related to a problem? Please describe.**
As mentioned by @dannycolin in this  #14617 - early users will likely struggle with knowing how to find rooms they should join.

**Describe the solution you'd like**
A clear way of onboarding people - like a welcome room/message, and a search that can help people more.  

**Describe alternatives you've considered**
Make the search and explore buttons the same as they used to be in older room list

**Additional context**
Early users might not think they need to decide between "searching" and "exploring" to find a room.

**Comment by t3chguy** [comment]
> Early users might not think they need to decide between "searching" and "exploring" to find a room.

This issue is less major now given the prompt:

![image](https://user-images.githubusercontent.com/2403652/96724425-bad63a00-13a7-11eb-9a64-2ec5cfc35f20.png)
