### ISSUE TITLE
Autodeclining DM invitations

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#14879]
This should probably be an integral part of a larger autodecline feature (for specific rooms, users, from certain servers, for rooms with keywords in the name, ..) - but one important use for me will be to autodecline invitations to canonical DMs.  I don't want to be in any, and will make my own tag for direct messages.
(Originally created [here](https://github.com/vector-im/element-web/issues/14878).)

**Comment by t3chguy** [comment]
Still the wrong repo.
