### ISSUE TITLE
Autodeclining DM invitations

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#14878]
This should probably be an integral part of a larger autodecline feature (for specific rooms, users, from certain servers, for rooms with keywords in the name, ..) - but one important use for me will be to autodecline invitations to canonical DMs.  I don't want to be in any, and will make my own tag for direct messages.

**Comment by t3chguy** [comment]
This should be done at the spec/server level so that it doesn't leak activity + is consistent between platforms.
I suggest a matrix-doc issue.

**Comment by Biep** [comment]
Moved it to matrix - but isn't declining invitations a client issue?  Manual declining is done through the client, so autodecline would be as well?  Or can't the client see whether a room is a DM before the invitation is accepted?

**Comment by t3chguy** [comment]
Automatic anything would be a privacy risk leaking activity and also why implement something N times, once in each client, rather than once consistently in the server?

> Or can't the client see whether a room is a DM before the invitation is accepted?

Invitations have untrusted state, I believe it can see it but it would be very easy to fake.

**Comment by Biep** [comment]
I tried [vector-im/matrix-doc], but I get `Failed to create issue. HTTP 404`.
I see the *once for all* point, and trust you are right on the leakage thing.

**Comment by t3chguy** [comment]
`[vector-im/matrix-doc]` if you're referring to `!github create` then this is not the place for support for it but square brackets look wrong. Square brackets in a usage mean optional, do not mean use square brackets.

**Comment by Biep** [comment]
Of course - I was stupid (even more than normally).  Thanks!
