### ISSUE TITLE
Advise users when room history is being hidden because it would be undecryptable

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#14889]
When you join an encrypted room you don't see the message history.
This makes sense, because a bunch of UISIs you can never fix is a nice thing to avoid.
However, it is suprising because:
- the room settings still say you should have access to old messages
- joining the room, you have no signal as to whether you're landing in a brand new room or one in which discussion is already in flight

This last point is probably more important - I find landing in such a room I don't know quite how to behave.

**Comment by jryans** [comment]
This is effectively a duplicate of https://github.com/vector-im/element-web/issues/13349.
