### ISSUE TITLE
uploading media isn't working

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#14881]
Attempts to upload media spin for 30s, then time out.

Network inspector shows, and reverse-proxy logs confirm, that the upload request never leaves the browser:

![image](https://user-images.githubusercontent.com/1389908/89398703-622cc480-d709-11ea-8319-b7e4938fcc09.png)

(the 204 is the OPTIONS request)

**Comment by odiferousmint** [comment]
I just wanted to submit a similar issue. I can upload a video converted to using video codec `libx264`, but not `libx265`! I wonder why that is.

**Comment by richvdh** [comment]
@odiferousmint that sounds like a separate problem. suggest you create a separate issue describing the symptoms you see.

It looks like my HS is generally struggling today so my problem could be caused by that. investigating.

**Comment by t3chguy** [comment]
```
2020-08-05T09:45:57.031Z E Operation aborted
AbortError: Operation aborted
    at XMLHttpRequest.xhr.onreadystatechange (webpack-internal:///472:286:23)
```

Sounds like the client timeout was reached

**Comment by richvdh** [comment]
yeah, the question was why the request wasn't even getting as far as my reverse-proxy.

I *suspect* the answer was that element had filled up all its connection slots with URL preview requests (which were timing out on the server side). I've now unbroken my HS, which has made things better.

You can probably close this, but I do think there is an outstanding issue about how element uses its connection slots.

**Comment by t3chguy** [comment]
> You can probably close this, but I do think there is an outstanding issue about how element uses its connection slots.


Yup, I know @turt2live had plans to use fancy prioritisations to deprio URL Previews but that's stuck on us switching to Fetch in js-sdk which I believe @Half-Shot had at one point
