### ISSUE TITLE
Client well-known isnt looked up for custom URLs

### ISSUE THREAD

**Issue by NHAS** [vector-im/element-web#14887]
### Description

When entering in a custom homeserver URL I am expecting to see the Element client lookup the `https://homeserver/.well-known/matrix/client` path. 
Then connect to the delegated matrix server. 

This does not happen, instead the homeserver url given previous is queried directly for "versions". 

### Steps to reproduce

- Setup custom synapse matrix server with `.well-known/matrix/client`
- Click on "Advanced" and enter in homeserver URL, open the console and view requests
- On clicking "next" no request to `.well-known/matrix/client` is made

Describe how what happens differs from what you expected.

Logs being sent: no

![Screen Capture_select-area_20200806222736](https://user-images.githubusercontent.com/6820641/89521706-19bdf580-d834-11ea-8ecd-896dbee8a8f0.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**:  Arch Linux
- **Version**: 1.7.2

**Comment by t3chguy** [comment]
https://matrix.org/docs/spec/client_server/r0.6.1#well-known-uri only defines it from Usernames, not from URLs.

If you were to put `@user:certainlyawesome.com` into the username field and blur it then it would do the lookup.

**Comment by turt2live** [comment]
Use the login endpoint override options to specify a well-known file. Synapse has options to populate this somewhere.
