### ISSUE TITLE
Three backtick block parsing is way too strict compared to other messengers, making element comparatively annoying to use

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#14898]
### Description

Three backtick block parsing is too strict compared to other messengers, making element comparatively annoying to use in coding channels when sharing snippets. It just feels like element goes out of its way to make exchanging code snippets hard for the sake of wanting me to teach markdown, instead of just getting out of the way of painless conversation. Here are a few examples where the strictness is problematic:

#### Example 1

Input:

> hello this is my code example: \`\`\`
> test code line 1
> test code line 2\`\`\`

Telegram: :heavy_check_mark: 

![ex1telegram](https://user-images.githubusercontent.com/64124388/89568926-896fb880-d813-11ea-89b6-d9bc464978be.png)

Discord: :heavy_check_mark: 

![ex1discord](https://user-images.githubusercontent.com/64124388/89568971-99879800-d813-11ea-860a-df472e3924e7.png)

Element: :-1: 

![ex1element](https://user-images.githubusercontent.com/64124388/89568992-9f7d7900-d813-11ea-9b63-a5a8c397d559.png)

#### Example 2

Input:

> \`\`\`
> test code line 1
> test code line 2\`\`\` < see my code here

Telegram: :heavy_check_mark: 

![ex2telegram](https://user-images.githubusercontent.com/64124388/89569415-321e1800-d814-11ea-9c7f-fb3860e6af97.png)

Discord: :heavy_check_mark: 

![ex2discord](https://user-images.githubusercontent.com/64124388/89569429-377b6280-d814-11ea-9eef-dd7a583d3cdb.png)

Element: :-1: 

![ex2element](https://user-images.githubusercontent.com/64124388/89569465-42ce8e00-d814-11ea-814e-b08f87cf5a05.png)

#### Example 3

Input:

> more code:
> \`\`\`test code line 1
> test code line 2\`\`\`

*(Note: I realize this one flies in the face of having the programming language specified in the first line. However, even this can be made to work without breaking legitimate markdown by just assuming anything with a space char or brackets or semicolons on the first line likely doesn't use the first line to specify a programming language. And this example happens more often for me than you'd think when not paying attention)*

Telegram: :heavy_check_mark: 

![ex3telegram](https://user-images.githubusercontent.com/64124388/89569840-cf794c00-d814-11ea-9fa6-331a02d6de85.png)

Discord: :heavy_check_mark: 

![ex3discord](https://user-images.githubusercontent.com/64124388/89569997-0ea79d00-d815-11ea-8be7-9c300d91b0a8.png)

Element: :-1: 

![ex3element](https://user-images.githubusercontent.com/64124388/89570005-1404e780-d815-11ea-8d16-82bf4372f76d.png)

### Steps to reproduce

Steps to reproduce:
- Connect to matrix using Element
- Copy the input for any of the examples above, make sure it copies as you see it (GitHub appears to like to insert empty lines in between which you will need to take out again)
- Paste example into Element chat bar and hit send

Describe how what happens differs from what you expected:

As written above, when just exchanging some snippets really quick in a discussion I don't want to be judged as if I'm writing a readme, and this works in all other messengers. As messy and non-standard as this is, I think the user intent of all examples is very clear and this is a real annoyance in conversation. So I think all of these examples should work in element.

There woud also IMHO be no need to make these work in more complex scenarios, like inside a quote or an indented block. But at least the super plain examples like in an otherwise unformatted message as above should work.

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Fedora Linux
- **URL**: app.element.io

Tickets vector-im/element-web#4674 and vector-im/element-meta#330 might be connected to fixing this.

**Comment by t3chguy** [comment]
This is just how https://spec.commonmark.org/dingus/ works.
The only solution would be to change Markdown dialects.

**Comment by ell1e** [comment]
@t3chguy I think a good solution might be to expand the currently used parser to handle this, might e.g. also work nicely with a pre-parser that only detects and finds and reformats these special cases. Switching the entire dialect possibly impacting lots of other things doesn't really seem like it's a good approach, *unless* the other changes that would bring also are beneficial of course.

**Comment by t3chguy** [comment]
That would mean running a custom dialect which is not going to happen due to maintainability and interoperability

**Comment by ell1e** [comment]
If I had to guess, I would assume custom parser tweaks that is what all these other messengers are doing. And interoperability in what sense? Right now Element seems to be doing a worse job at that by not recognizing things that work in almost all others. And what exactly do I gain if a really complicated markdown readme pastes perfectly fine as-is, but the short snippet stuff I actually type in daily use doesn't work? I think adhering perfectly to some widely shared variant down to every detail might be overrated in this context

**Comment by t3chguy** [comment]
Ever more reason to switch to something like GFM rather than making our own thing which is hard to maintain exactly between all the platforms and still won't match anything else exactly

**Comment by ell1e** [comment]
GitHub doesn't seem to pass the examples above. So if GFM means it matches GitHub's behavior exactly then it won't do anything useful to solve this issue, so I'm not sure why you'd bring it up

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-meta/issues/330 as the general markdown bug

**Comment by ell1e** [comment]
Does GFM support all these weird chat-specific corner cases though? Otherwise I'm not sure it's an "equivalent" bug

**Comment by t3chguy** [comment]
Nope, that's why I turned it into the general markdown bug, to pick the right dialect, with the current suggestion of gfm, I'd suggest arguing against gfm there if you don't like it's back tick handling.
