### ISSUE TITLE
Can't add a profile picture

### ISSUE THREAD

**Issue by Meandmyfurbies** [vector-im/element-web#14899]
### Description

When I add a profile picture in settings it just reverts back to default when you close the settings window. This could be because I'm trying a large profile picture but that should at least give me an error message.

### Steps to reproduce

- Open app
- Click the 3 dots to the right of the username. 
- Click 'All Settings'
- Click 'Upload' below the default profile picture
- Select a profile picture
It does not save the uploaded profile picture but it should either save it or give me an error message saying it is too large. 

Log: sent

### Version information

- **Platform**: tried both

For the web app:

- **Browser**: Brave 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

- **OS**: Linux Mint 19.0 "Tara" Cinnamon
- **URL**: element.io

For the desktop app:

- **OS**: Linux Mint 19.0 "Tara" Cinnamon(Flathub)
- **Version**: 1.7.2

**Comment by t3chguy** [comment]
Sounds like you aren't clicking Save.

**Comment by t3chguy** [comment]
For future support queries use the help room.
