### ISSUE TITLE
Bridge state info has stopped working

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#14906]
I'm seeing "This room isn’t bridging messages to any platforms. Learn more." in a room that has a bridge, as seen in the room state:

![Screenshot from 2020-08-07 13-58-00](https://user-images.githubusercontent.com/2072976/89647780-0c494f80-d8b6-11ea-834a-4f98314d4966.png)

**Comment by t3chguy** [comment]
Ah yes, it was broken by js-sdk changing to Maps
