### ISSUE TITLE
E does not ask the system for "Screen Recording" permission in Catalina

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#14907]
### Description

When trying to share your screen in a Jitsi call from the Element Mac client on Catalina, E never asks for permissions to record the screen so the "Share" button is grayed out.

<img width="1013" alt="Screen_Shot_2020-08-07_at_2_37_45_PM" src="https://user-images.githubusercontent.com/19155609/89651657-2e45d080-d8bc-11ea-8d39-6f8c4849e907.png">

E asks for microphone permissions as expected.

### Steps to reproduce

- Add Jitsi to a room
- Join call
- Click "Share your screen"

E need to ask the system for permission to "Record Screen"

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS Catalina  10.15.6
- **Version**: 1.7.3

**Comment by t3chguy** [comment]
That's actually not what is happening at all, we are missing the special bits of code for Jitsi screen sharing electron support because they are hard for us to integrate. https://github.com/vector-im/element-web/issues/4880
