### ISSUE TITLE
Element starts with white screen

### ISSUE THREAD

**Issue by rebastion** [vector-im/element-web#14916]
Installed Element from Ubuntu Software on a fresh Ubuntu 20.04.1 installation (snapcraft), but it starts with a white screen....

EDIT (see further down): The reason it seems to start blank because it is indeed already running (but not showing anywhere, including tray - which may thus be the primary bug - on the other hand, it could be more user friendly by showing a message also in the UI that it is already running)

EDIT 2: Occurs with the snap install only.

![Screenshot from 2020-08-09 09-45-24](https://user-images.githubusercontent.com/13915837/89727436-34a38c00-da25-11ea-8cc8-03c4bfd7f4ba.png)

**Comment by t3chguy** [comment]
Ctrl Shift `I`

should bring up the javascript console
Any errors there?

**Comment by rebastion** [comment]
No javascript console opens.... unfortunately. Any other shortcuts to try? Is there an error log maybe?

**Comment by t3chguy** [comment]
> Is there an error log maybe?

Try run it in the command line

**Comment by rebastion** [comment]
![Screenshot from 2020-08-11 11-51-31](https://user-images.githubusercontent.com/13915837/89884084-52a9f180-dbc9-11ea-8994-3bf0fbc95b39.jpg)

Interesting. Any ideas?

**Comment by t3chguy** [comment]
So that just means it is already running in the background. Should be on your tray. Try kill the process and then run in command line again.

**Comment by rebastion** [comment]
We are getting closer to the root of the issue. So I rebooted my system, just to make sure. Then opened system monitor to check if Element is running. It was not running. Then I open Element, and suddenly Element seems to be running, but nowhere to be seen. Not in the tray, and no app in the task bar.
Assumption: There is a problem with the app showing in the tray. What now?

**Comment by t3chguy** [comment]
`[6401:0811/120436.993137:FATAL:platform_shared_memory_region_posix.cc(254)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.` looks like a culprit

**Comment by rebastion** [comment]
Yea I could try chmodding around my system folders, but it puzzles me that a standard app wouldn't run without chmodding around an Ubuntu system folder, which is already drwxrwxrwt, isn't that 1777 ?

**Comment by rebastion** [comment]
Anyways, I removed the snap and installed it from the deb archive, and it starts perfectly. Maybe something was wrong with the way it was packaged or regarding the permissions snaps have to access the tray dbus/architecture or whatever (there are some similar issues on that open I think)

**Comment by t3chguy** [comment]
That is possible, the Snap is unofficial so I recommend you reach out to its community maintainers.
