### ISSUE TITLE
Resize handle on right panel interferes with the timeline scrollbar

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/element-web#14910]
### Description

Scrollbar keeps jumping around when you hover over the chat's scrollbar if and only if one of the three bars (are they really called bars?) is opened. Those are the following: Members, Files, and Notifications.

### Steps to reproduce

1. Open Members bar (or Files, or Notifications)
2. Try to scroll the chat using the scrollbar

When you try to scroll using the scrollbar, you will notice that it is jumping around.

### Version information

- **OS**: Arch Linux
- **Version**: element-desktop 1.7.3

**Comment by t3chguy** [comment]
Are you referring to this?
![image](https://user-images.githubusercontent.com/2403652/89708433-ffd4fd80-d96e-11ea-9e35-04ea6cec7fca.png)

That's not a scroll bar but the resize handle for the right panel

**Comment by odiferousmint** [comment]
Yeah, but it interferes in such a way that it does not matter if the cursor is on that handle or not. It keeps jumping around if the cursor is outside of that handle.

**Comment by t3chguy** [comment]
Yup, definitely!
