### ISSUE TITLE
Cannot create a room without a name

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#14926]
The create room dialog offers you no option to create a nameless room. Even if it was an advanced-mode thing, it's quite annoying when you just want to create a small ad-hoc room.

**Comment by t3chguy** [comment]
This was by design

**Comment by Half-Shot** [comment]
*nods* I'm just putting down an unhappy flag

**Comment by Half-Shot** [comment]
I suspect this is probably acceptable in the end. I just need to be more creative with my names.
