### ISSUE TITLE
Malwarebytes blocks Element Windows as trojan

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#14920]
### Description

Report from a customer. I don't have a Windows VM available at the moment to reproduce. Sorry for vague report 

![image](https://user-images.githubusercontent.com/19155609/89777495-bb2e9b00-db03-11ea-8c9e-d1fbb3a1aa90.png)

### Steps to reproduce

- Install Malwarebytes and Element Desktop I guess?

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.3

**Comment by Twi1ightSparkle** [comment]
The problem is not the executable itself, but the domain matrix.org. 
During testing, Malwarebytes browser protection thing blocks connection attempts to https://matrix.org/ even without having Element installed

**Comment by Twi1ightSparkle** [comment]
Actually, this just got a bit more complicated. It's the IP 104.20.20.236 (what matrix.org resolves to) that is blocked. That is a CloudFlare IP. I'm assuming that IP is shared with other CF customers?

**Comment by resynth1943** [comment]
*Nooooo*, they've unfurled our plan to distribute malware via matrix.org!
On a more serious note, has anyone reported this to Malwarebytes?

**Comment by t3chguy** [comment]
This is stale
