### ISSUE TITLE
Old link to Desktop app from personal settings is wrong

### ISSUE THREAD

**Issue by steveloynes** [vector-im/element-web#14928]
### Description

Link to download for Element Desktop from 'Security & Privacy' under 'Message Search' goes to Riot, not Element.

Should link to element.io/???

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

Element Web 1.7.3

**Comment by jryans** [comment]
Thanks for the feedback! This has been changed to https://element.io/get-started on develop, and will go out with the next release.
