### ISSUE TITLE
Community Members visible if commuinity ID known? Why?

### ISSUE THREAD

**Issue by kettenfett** [vector-im/element-web#14923]
**Is your suggestion related to a problem? Please describe.**
Community IDs are rather short and not cryptic, thus they can potentially be guessed by someone. How is it a good idea, to reveal all members of a community to non-members then (which is the current behaviour)?

**Describe the solution you'd like**
I want to be able to configure, whether community members should be visible to non-community-members at all.

**Comment by t3chguy** [comment]
In the new Spaces world, members will only be visible if your Space is public/peekable

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
