### ISSUE TITLE
Use local captcha

### ISSUE THREAD

**Issue by xcasxcursex** [vector-im/element-web#14933]
Since many browsers and addons, especially those closely related to a privacy and open-source focussed community like matrix.org, block third-party tracking content, using recaptcha.net does not work:

![image](https://user-images.githubusercontent.com/58130821/89961306-a2012800-dc84-11ea-9e8c-c839986f8a6b.png)

**Describe the solution you'd like**
Use a local captcha

**Describe alternatives you've considered**
https://alternativeto.net/software/recaptcha/

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/3606

Given that Element runs entirely in your browser, it cannot use a `Local` captcha as it has to use the one the service the user is trying to connect to is asking for.

**Comment by xcasxcursex** [comment]
> Given that Element runs entirely in your browser, it cannot use a `Local` captcha as it has to use the one the service the user is trying to connect to is asking for.

By "local" I am referring to the host, not the client.

**Comment by t3chguy** [comment]
Well the host again is not Element, you can run Element from your filesystem using a naive web server.

**Comment by xcasxcursex** [comment]
In which case the host would be the local system running said web server.

Anyway, enough talk of semantics, I thought you didn't understand the point here but it's clear that it's well understood that recaptcha is a privacy and security problem, and shouldn't be used. This has all been covered in the three year old issue of which you marked this as a dupe. I'd continue the conversation there but it's all been said already ad after that amount of time it's clear that there's no solution in sight.

**Comment by t3chguy** [comment]
> In which case the host would be the local system running said web server.

Given the web server would just be hosting static files and unable to perform any captcha validation that is not possible.

Element is just a client. If you're connecting to a website using your favourite web client (browser) that browser doesn't get to choose which Captcha you use, the service you're connecting to does.

**Comment by xcasxcursex** [comment]
Of course it's possible, how do you think the other captcha services do it? Magic space voodoo? No, it's a web server.

> that browser doesn't get to choose which Captcha you use, the service you're connecting to does.

Exactly, and the service I connected to, chose spyware, hich is bad, and it's all been covered in the other thread. 

You seem to just want to argue and like I said, it's terrible the way it works now, it's been a known issue for over three years and it's all been said. I don't need to continue this conversation and there's no way you can defend it. Unsubbed.
