### ISSUE TITLE
The left two corners of images are rounded, but not the right two

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#14948]
![](https://i.imgur.com/d1zI6qT.png)

**Comment by t3chguy** [comment]
Cannot reproduce, is that not just transparency?

![image](https://user-images.githubusercontent.com/2403652/90099389-3d9ca200-dd32-11ea-9258-288fd0288f20.png)

**Comment by turt2live** [comment]
This is a solid white square with no transparency or other effects:
![image](https://user-images.githubusercontent.com/1190097/90165493-f7f1d080-dd55-11ea-8fea-1885acb949e7.png)

**Comment by t3chguy** [comment]
"Please fill in the issue template" - what version :P?

![image](https://user-images.githubusercontent.com/2403652/90234971-744ce800-de18-11ea-95c8-663ae6a08aa0.png)

I cannot repro on nightly

**Comment by turt2live** [comment]
Chrome, develop, nightly. Doesn't seem to be platform or version specific.

**Comment by t3chguy** [comment]
Ah, so its a combination of a newer update + having a wide viewport so that the image doesn't take up the full width

Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/1d6c2b786ebece54f7c429464d915b6d6c26cc43#diff-d670e69d462d2068a8026946020fc004R38
