### ISSUE TITLE
Closing Element doesn't end processes

### ISSUE THREAD

**Issue by rebastion** [vector-im/element-web#14941]
Using latest Ubuntu 20.04 and Element Desktop from ppa/deb as per official website.

Element has rather high CPU usage (about 17 percent), and when you close it (i.e. no more tray icon either), it remains active (system monitor shows the same two processes using 17 percent CPU).

**Comment by t3chguy** [comment]
How do you close it? Clicking `X` or `Exit`

![image](https://user-images.githubusercontent.com/2403652/90032453-49e31980-dcb6-11ea-89f9-d1dec607c162.png)

**Comment by rebastion** [comment]
Quit

![Screenshot from 2020-08-12 17-15-21](https://user-images.githubusercontent.com/13915837/90033200-7a7b8100-dcbf-11ea-9e27-f3f9f9b90a9c.png)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14123
