### ISSUE TITLE
Give a way to mark room as DM back

### ISSUE THREAD

**Issue by JuniorJPDJ** [vector-im/element-web#14942]
Sometimes some chats are getting bugged, eg. rooms created by bridges aren't getting marked as DM or those are marked by mistake.
There were an option to mark chat as DM manually in Riot, it was taken from us in Element after redesign.
Maybe it should be in advanced room settings, not exposed in context menu, but IMO it should still be there.

**Comment by t3chguy** [comment]
It was removed on purose; https://github.com/vector-im/element-web/issues/14221

In future in Matrix with the Canonical DMs project it will not be possible to change after creation

**Comment by JuniorJPDJ** [comment]
So as a temporary solution could I you please give me a way to correct my rooms?
It's getting horribly annoying. A command or request, idk.

**Comment by t3chguy** [comment]
https://matrix.org/docs/spec/client_server/r0.6.1#m-direct

**Comment by Ezwen** [comment]
Hi there! I have the same problem. Thanks for the link, however, I am not sure how it can be used to actually fix the issue?

**Comment by JuniorJPDJ** [comment]
@Ezwen I just started old version of riot in docker for a while to fix my DMs, maybe it will be fitting workaround also for you.

**Comment by Ezwen** [comment]
> @Ezwen I just started old version of riot in docker for a while to fix my DMs, maybe it will be fitting workaround also for you.

Interesting, thanks :)! Which version did you use?

**Comment by JuniorJPDJ** [comment]
`image: vectorim/riot-web:v1.6.8`
Last before this option disappeared ;)

**Comment by Ezwen** [comment]
> `image: vectorim/riot-web:v1.6.8`
> Last before this option disappeared ;)

Brilliant, that worked like a charm! Thank you very much! :D

**Comment by MightyCreak** [comment]
I found a way to use @t3chguy's hint to change room "type":
* In a non-DM room, write `/devtools` in the message area and hit <kbd>Enter</kbd>
* In the pop-up window, click on "Explore Account Data", then "m.direct", then "Edit" (you need to scroll all the way down)
* Once in edit mode, copy the "Room ID" on the top-right corner of the pop-up
* Add the copied room in the array of each person present in the room (be careful to you must respect the JSON syntax)
* If a person is not in the list, it means you don't have a DM with this person yet, so add it like the other people in the list and add the room in its array.

**Comment by huguesdk** [comment]
if the dm/group setting will not be changeable in the future, how about a room that starts as a dm, but then an extra person is invited. shouldn’t the room become a group chat at that point? i think that the ability to let the user change the type is great.

i’ve recently had both scenarios:

1.  a dm where a 3rd account was added and then one of the original accounts was removed, because one person wanted to use another of their accounts in this dm, while keeping history. after that the dm was considered a group chat while i want it to be a dm.
2.  a dm where a 3rd person was invited, but is still considered a dm, while i want it to be a group chat.

i use an old riot android version to be able to change the type, but for scenario 2, it works for a while, then it switches back to being a dm.

**Comment by heyakyra** [comment]
> `image: vectorim/riot-web:v1.6.8` Last before this option disappeared ;)

How do you log in after running this? It directs to https://matrix-client.matrix.org/_synapse/client/pick_idp?redirectUrl=http%3A%2F%2Flocalhost%2F which only has options for google, gitlab, etc SSO

**Comment by t3chguy** [comment]
Old Riot Web didn't handle multi-auth properly, so due to that it only lets you use SSO in a case of a server supporting SSO or Password, so you cannot.

**Comment by passw0rd123** [comment]
There are slash commands for that in element (tested in element 1.9.7)

```
/converttodm

/converttoroom
```

**Comment by heyakyra** [comment]
Thanks, do those affect only the user which enters the command, or change the actual room for both users?

**Comment by t3chguy** [comment]
Whether a room is a DM or not is based on perspective, there's no way to mark a room as a DM for all users as per the spec.
