### ISSUE TITLE
`Remove from community` is not shown as a link

### ISSUE THREAD

**Issue by wvffle** [vector-im/element-web#14946]
### Description

`Remove from community` in community admin tools is not rendered as a link. I had some problems to find that button due to that.
![image](https://user-images.githubusercontent.com/13330620/90039207-dc36ed80-dcb5-11ea-9834-b2659f79a6a2.png)

### Steps to reproduce

- Create community
- Add a channel to the community
- Click on the channel in the right panel

`Remove from community` should be renderd as a link or button

Logs being sent: no

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 78
- **OS**: Arch Linux
- **Version**: 788a6f05274f-react-788a6f05274f-js-788a6f05274f

**Comment by samhh** [comment]
Is this still an issue for anyone watching? Locally it looks linkified for me both via community and room member lists.

**Comment by wvffle** [comment]
Still occuring on 1.7.24
![image](https://user-images.githubusercontent.com/13330620/114587461-36d57e80-9c75-11eb-90a0-bc3281b9c56c.png)

**Comment by samhh** [comment]
Ah my mistake, I see it now, it's in the room information bit. Still present on `develop`.

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
