### ISSUE TITLE
Invitation loop

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/element-web#14950]
### Description

I'm using a third party matrix server ([here](https://element.gemeinsam.jetzt)) and tried to `join #_oftc_#realraum:matrix.org` which causes an undefined error.
However, `@_oftc_r3bot:matrix.org` tries to contact me afterwards. I can neither accept, nor ignore this. ("Denieing failed. Not a known user). So I'll stuck in the invitation loop, and always have 1 unread message.

### Steps to reproduce

The result was not the same everywhere, but it caused different issues:
- Using an account on an other server than matrix.org (in my case gemeinsam.jetzt)
- Trying` /join #_oftc_#realraum:matrix.org`

### Describe how what happens differs from what you expected.

You'd be able to join the room.
However if this does not work because of some server issues (maybe this is a synapse bug?), Element-Web should not be stuck in this kind of invitation-look.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Vivaldi
- **OS**: Windows 10
- **URL**:  gemeinsam.jetzt, Riot/Element 1.7.1

**Comment by t3chguy** [comment]
Sounds similar to https://github.com/vector-im/element-web/issues/13919

**Comment by Flexmaen** [comment]
Is it possible that this is a synapse bug?
I have the same problem on Element for Android now. Or should I file a bug there?

**Comment by t3chguy** [comment]
> I can neither accept, nor ignore this.

Is definitely a server issue.
