### ISSUE TITLE
In compact mode, the contextual message buttons can be hard to reach

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#14957]
Most of the time the focus moves to the message above before my cursor can reach them:

![Peek 2020-08-14 10-49](https://user-images.githubusercontent.com/5547783/90237292-f5f24500-de1b-11ea-83d2-48ad5dadb7d8.gif)

**Comment by t3chguy** [comment]
That bug got fixed last night

**Comment by babolivier** [comment]
Interesting, that gif was recorded less than an hour ago on develop.element.io (sorry for forgetting to mention it in the original comment), so it doesn't look like it was actually fixed?

**Comment by babolivier** [comment]
Bleh, I refreshed and it's gone, so *shrug*
