### ISSUE TITLE
Trying to set power levels triggers error in element-web

### ISSUE THREAD

**Issue by daniel-nk** [vector-im/element-web#14951]
### Description

If I try to set a user's power level I get an error message Command error - Can not find user in room but I can clearly see that the user is there and they are even marked online.

I _can_ set the power level with the little icon below a user's name in the side panel. It took me some time to realize this is an icon though.

### Steps to reproduce

- enter the command /op _userid_ _powerlevel_

Describe how what happens differs from what you expected.

I would expect the command to set the desired powerlevel

Logs being sent: no

Neither my synapse homeserver nor the logs of my nginx proxy show any activity on execution of that command.

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: 84.0.4147.89,  Firefox 78.0.2
- **OS**: Arch Linux, Ubuntu Linux
- **URL**: private server  element-web 1.7.2

**Comment by t3chguy** [comment]
Can you give an example of the userid you are entering?
The graphical way is simple.

![14951](https://user-images.githubusercontent.com/2403652/90150955-19ff4900-dd7e-11ea-919a-0e3bc09cc9b1.gif)

**Comment by daniel-nk** [comment]
Hello, thanks for the quick reply. I hardly saw that little icon, it's pretty dark on my screen. Good to know.
Now to answer your question

I am entering the exact user-id as it is visible in the side-panel for example @wilcobh:matrix.nikhef.nl (the latter being the address of my homeserver)

**Comment by t3chguy** [comment]
Found the bug, `/op` is broken with the power level argument, will fix in a second
