### ISSUE TITLE
Prominent Display of Communities in UI

### ISSUE THREAD

**Issue by traek** [vector-im/element-web#14965]
Currently the community is used as a filter for People and Rooms. While this allows for the greatest flexibility, including having people and rooms in multiple communities, it makes communities very much secondary. Rather, it would be nice to have two distinct views, one is all of the rooms and people you are active in and another view from communities using a top-down tree structure on the left.

Level 1: Community
 + Level 2: Rooms

On the right would be any users in a given selection. For example, if I have the Community itself highlighted, I would see a list of all rooms underneath that community on the left and all users that have joined the community on the right. Once a given room is selected, you would enter and see the room participants as normal on the right.

This additional view would make communities more prominent and make joining and even searching for public communities a possibility in the future.

**Comment by MarkWieczorek** [comment]
A simple fix for me would be the following:

When clicking on the community icon, this should go directly to the "view community" page, which gives a list of all the rooms in the community. I suspect that most people are not aware that the "view community" option even exists...

**Comment by robintown** [comment]
This has been fixed by spaces
