### ISSUE TITLE
Slash command for upvote/thumbs up

### ISSUE THREAD

**Issue by swapnilraj** [vector-im/element-web#14966]
**Is your suggestion related to a problem? Please describe.**
I am able to navigate the element web app mostly with my keyboard but I have to reach for the mouse when trying to upvote/react to a message. It would be nice if I could accomplish the same with a slash command.

**Describe the solution you'd like**
A new slash command which reacts to the last message. The command could be /upvote, /thumbsup or any better term. The solution could even be extended to /react :emoji-name: but this sounds needlessly complex.

**Comment by aaronraimist** [comment]
It seems like /react <emoji character> or :shortname: would be a better solution then creating /thumbsup /thumbsdown /laugh etc which would just be a never ending list of more individual slash commands.

**Comment by t3chguy** [comment]
This seems very restrictive and prone to errors, by the time you type out the command a new message may have come in and you are now reacting to the wrong thing. Standard accessibility using shift/tab to navigate around would be far more flexible if it was fixed.

**Comment by SimonBrandner** [comment]
I believe this is now fixed with the `+:+1:` syntax, so I am going to close this. 

Let me know if you disagree
