### ISSUE TITLE
On Signin Matrix Server Delegation is Ignored

### ISSUE THREAD

**Issue by NHAS** [vector-im/element-web#14969]
### Description

When a homeserver uses delegation this is ignored on element-web causing the wrong server to be queried. 
i.e On signing although the delegation is queried, the original domain is still queried as if it is the synapse server. 

### Steps to reproduce

0. Have a main domain, and a matrix domain. 
`certainlyawesome.com`
`matrix.certainlyawesome.com`

1. Setup `.well-known` delegation  as follows:

`.well-known/matrix/client`
```
{
  "m.homeserver": {
    "base_url": "https://matrix.certainlyawesome.com"
  }
}
```
Which is on the main domain `certainlyawesome.com`, with the accompanying `.well-known/matrix/server` delegation.

2. Attempt to log in to https://app.element.io/#/login with `@test_user:certainlyawesome.com`
See that the web application attempts to communicate with `certainlyawesome.com` instead of `matrix.certainlyawesome.com`.

![Screen Capture_select-area_20200815202925](https://user-images.githubusercontent.com/6820641/90308738-31813200-df36-11ea-93be-604f5c3a8384.png)

CORS requests failing as `certainlyawesome.com` does not point to a matrix server. 
![Screen Capture_select-area_20200815202942](https://user-images.githubusercontent.com/6820641/90308740-32b25f00-df36-11ea-904a-1de6eecc5ba0.png)

What I expect to happen: 

When delegation is given to the client, the delegated server is then communicated to. Rather than the original domain. 

Logs being sent: no (As was not able to log in)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome & Firefox
- **OS**:  Arch Linux
- **URL**: https://app.element.io/#/login

**Comment by t3chguy** [comment]
Define how you are doing this

> Attempt to log in to https://app.element.io/#/login with @test_user:certainlyawesome.com

**Comment by NHAS** [comment]
By entering the user id @test_user:certainlyawesome.com as shown below.  

![Screen Capture_select-area_20200815220006](https://user-images.githubusercontent.com/6820641/90310139-d144bd00-df42-11ea-9bfb-bfc99ac4718d.png)

I have also tried using both `matrix.certainlyawesome.com` and `certainlyawesome.com` in the "Change server" dialog. As shown below:

![Screen Capture_select-area_20200815220147](https://user-images.githubusercontent.com/6820641/90310147-ec173180-df42-11ea-8c89-8873f0998edd.png)

**Comment by t3chguy** [comment]
So entering the full username as you did should trigger the `.well-known` lookup.
Entering a Homeserver URL will not as the well-known is only defined in the Matrix spec from Matrix usernames.

![image](https://user-images.githubusercontent.com/2403652/90310176-04f1f980-dee7-11ea-8587-2f177acc6eab.png)

Entering the username as you did works for me, I tried with a dummy password and it tried to log into matrix.certainlyawesome.com. See above.

**Comment by NHAS** [comment]
Sorry, this is a miswording on my behalf. 

When logging in, after you've entered credentials the account never syncs with the issues I've shown previously. I've put in place a fix so that the mobile and web apps work as well.

**Comment by NHAS** [comment]
If there is a way of getting it to you safely, I am more than happy to give you the creds to that test account to have a look.

**Comment by t3chguy** [comment]
You can reach out to me on Matrix at `@x:riot.ovh` or via e-mail at 7t3chguy@gmail.com

**Comment by NHAS** [comment]
Thanks so much to @t3chguy 

For anyone else finding this: 
The issue was that `public_baseurl` in the synapse homserver config was set to `certainlyawesome.com`. 

It should have been set to `matrix.certainlyawesome.com`
