### ISSUE TITLE
no Regional Indicator Symbol Letter emoji reactions

### ISSUE THREAD

**Issue by ZerataX** [vector-im/element-web#14963]
### Description

emoji reactions don't include any Regional Indicator Symbol Letter emoji(, well I guess technically they are being used for flags, but I would like to use them on their own)

![image of emoji picker missing the "G" emoji](https://user-images.githubusercontent.com/5024958/90304774-4bc9fa00-debb-11ea-8485-73ef9bfb64c1.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox? 79
- **OS**: Linux 5.4.57, NixOS, 20.09pre237781.32b46dd897a
- **URL**: https://chat.dmnd.sh
- **Version**: 1.7.3-12-g84ddc114

**Comment by t3chguy** [comment]
The emoji set provided is from https://github.com/milesj/emojibase/
I would recommend you suggest that change there

**Comment by ZerataX** [comment]
apparently this was already once briefly discussed, but I tried to explain my case in detail here: https://github.com/milesj/emojibase/issues/19#issuecomment-674471474

**Comment by t3chguy** [comment]
Looks like you have caused it to be reconsidered upstream, awesome
