### ISSUE TITLE
room stays unread if no messages due to retention policy

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/element-web#14976]
![Screenshot from 2020-08-16 23-25-07](https://user-images.githubusercontent.com/7166727/90343301-e4758c80-e017-11ea-9e4c-982371df0a09.png)

Element version: 1.7.3
Synapse version: 1.18.0

Room has state:
```
{
  "unsigned": {
    "age": 8670200875
  },
  "type": "m.room.retention",
  "sender": "XXX",
  "content": {
    "max_lifetime": 604800000,
    "min_lifetime": 604800000
  },
  "state_key": "",
  "event_id": "XXX",
  "origin_server_ts": 1588934470418,
  "room_id": "XXX"
}
```

If older messages gets removed due to [retention policies](https://github.com/matrix-org/synapse/blob/develop/docs/message_retention_policies.md) and no new messages after 7 days, room becomes unread forever until new message is inserted.

**Comment by turt2live** [comment]
what retention policy? what version/brand of homeserver? what version of element? Please fill in the template.

**Comment by 4nd3r** [comment]
updated parent.

**Comment by turt2live** [comment]
flagging as a likely synapse bug - needs investigation

**Comment by t3chguy** [comment]
I'm not sure that's the case as the dot alone with no count means the local unread check is being used (Bold state)

**Comment by rettichschnidi** [comment]
Everyone (seemingly) on my homeserver is experiencing this issue. Rentention policy is enabled (1 to 90d). What can I do to help investigating this issue?

**Comment by catfly1** [comment]
Does anyone have some javascript that can be run in the console to dismiss these ghost unread notifications? It seems to mess up the sort by 'Activity' UI functionality, making matrix/vector/riot/element notifications useless. Clicking on the room results in a 404 from POST `rooms/<roomid>/read_markers`  request.

Our retention policy is min:1d, max:7d, and I have 15 'unread' notifications from DM rooms.

**Comment by 4nd3r** [comment]
I see same issue with Element for Android/iOS too.

So this issue should be moved to [matrix-org/synapse](https://github.com/matrix-org/synapse), because it feels like Synapse issue.

Same time, if you read [this comment](https://github.com/matrix-org/synapse/issues/10071#issuecomment-849492416), it seems any report about retention issues will be ignored until it becomes stable feature.

Also https://github.com/matrix-org/synapse/issues/6832.

So I'm closing this issue and make new one to Synapse issues to track this problem with experimental retention feature.
