### ISSUE TITLE
Trying to cross sign after logging in fails.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#14970]
Was working with a user over the weekend on setting up Element desktop.

They tried to log into Element web, but it failed at the last verification step:

Flow:
  - User on Element Android is signed in, cross signed.
  - User on Element Web is not.
  - User on Element Web tries to log in. Gets prompted to verify their device.
  - They verify successfully with the QR code method.
  - Element Android gives the all clear and works, device is visibly verified in the UI.
  - Element Web shows a infinite spinner which never completes. Restarting the app will leave the device unverified and will not allow you to retry, as the other device believes it to be verified.
 - Further attempts to log out and in again cause the same problem.

We tried waiting for the logs to stop requesting all messages from all the rooms and all the scrollback (wtf, why does it block the app on requesting all messages from all encrypted rooms?!) to see if it would eventually complete, but it did not. 

I'm not really sure how to debug this further, but it is concerning. We currently can't verify this users device at all.

**Comment by Half-Shot** [comment]
Interesting, even though it failed to actually decrypt any of the messages it fetched during the sync mentioned, clicking to request keys on individual messages works fine. Very strange.

**Comment by srehm** [comment]
I can confirm this. The behavior is exactly as Half-Shot described it.

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/element-android-rageshakes/issues/14302

**Comment by jryans** [comment]
@Half-Shot @bwindels @srehm This issue is now believed to be fixed on develop. Please re-test with a fresh web session that you started from develop.element.io, as it would be great to verify the fix for this.

**Comment by Y0hy0h** [comment]
I just logged in for the first time on develop.element.io. I initiated the cross-signing request from my Android phone and verified the emojis on both sides. Now develop.element.io is stuck loading. The message (German) says something like "Incoming verification request. Waiting for confirmation by the conversation partner."

So it appears that the issue is not resolved. Unless I need to delete some caches somewhere, or something like that.

**Comment by jryans** [comment]
@Y0hy0h Hmm, could you try again and submit a debug log from web? Since this happens during login, the usual debug log UI is not available, but you can use your browser's console: `mxSendRageshake("Some meaningful description here")`.

**Comment by Y0hy0h** [comment]
I tried again, same result. I sent that command with a description and it responded that the bug report was sent.

A few more things I've noticed: It doesn't matter if I first check the emojis on Android, or first on the web. And in the background behind the spinner there is a green shield saying that the verification was successfull.

**Comment by jryans** [comment]
@Y0hy0h Thanks, the debug log arrived. Could you also take a screenshot of web as well? When trying to reproduce, I want to make sure I reach exactly the same state. On Android after trying to verify with web, does Element Android's security section believe the web device is verified?

**Comment by Y0hy0h** [comment]
![grafik](https://user-images.githubusercontent.com/11377826/92802289-ad945b80-f3b6-11ea-9e86-c58c76867e32.png)

And yes, at the point where the web is loading as shown above, Android shows the session as verified.
![grafik](https://user-images.githubusercontent.com/11377826/92802375-c270ef00-f3b6-11ea-8d54-5a081e028ce9.png)

**Comment by jryans** [comment]
@Y0hy0h Thanks for the screenshots and extra info. It's a bit challenging to investigate and reproduce this, but anyway to ensure it is not lost, I have created a new issue https://github.com/vector-im/element-web/issues/15225 to track this.

**Comment by monochromec** [comment]
This bug surfaced in 1.9.0 once again. Any chance to provide a fix / work-around for this is as this is *REALLY* annoying?

**Comment by andzejsp** [comment]
starting to have this problem again :(
![image](https://github.com/element-hq/element-web/assets/80409979/8cec8ab4-7bb9-4f38-af32-17247fab67a3)

Windows 10
Element desktop app
"Synapse/1.98.0" homeserver
Element version: 1.11.58
Crypto version: Rust SDK 0.7.0 (691ec63), Vodozemac 0.5.0

If you force end task of the element app then reopen it it loads the chats but does not decrypt the rooms. Have to manually export rooom keys from other device and upload to this device.. :(

**Comment by raingloom** [comment]
I have the same issue, it would seem, although *some* messages are decrypted.  But the ones that two of my contacts couldn't open are also undecryptable by me.
