### ISSUE TITLE
Joining a room with an alias via Explore is a little confusing

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-web#14980]
### Description

When attempting to join a room with an alias (take `#general:mozilla.org` as an example) it is confusing to use the explore dialog. Assuming you work out to put the alias in the search box, you can get no results:

![Screenshot from 2020-08-17 13-05-40](https://user-images.githubusercontent.com/1391051/90394796-386d8900-e08b-11ea-83bf-ed9c8ea8f98d.png)

While there is the `Join` hint at the end of the search box, it can be confusing to people to not get any results under the search bar. Perhaps there should be a line showing up saying something like "this looks like a room address would you like to try and join it?".

### Steps to reproduce

- Type a room alias not in your servers directory into the explore search box.
- Witness the confusing lack of results.

### Version information

- **Platform**: desktop?
For the desktop app:

- **OS**: Arch Linux
- **Version**: Nightly 2020081701

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/17088 bears a good suggestion to show a fake tile at the top if the alias isn't returned by the server as a public room

**Comment by t3chguy** [comment]
This got fixed 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2403652/234298933-b1b993f8-bf7d-40c4-9711-e70fffd32339.png">
