### ISSUE TITLE
Editing out a link from a message leaves the link preview

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#14989]
### Description

When a message is edited to remove a previously present link, the link preview will remain. If the link is replaced with another, the preview will also be replaced with the new link, but never removed.

### Steps to reproduce

- Send a message with a link
- Edit the message to remove the link
- The link preview remains in place even though the message has no link in it

The link preview should disappear as there is no link to be previewed.

Logs being sent: no

![image](https://user-images.githubusercontent.com/37966924/90442770-74303f00-e0db-11ea-93b5-924483b843b1.png)

### Version information

- **Platform**: Desktop
- **OS**: Ubuntu 20.04
- **Version**: 1.7.4

**Comment by t3chguy** [comment]
This only happens when editing it to have 0 links, 2->1 works

**Comment by TR-SLimey** [comment]
Issue gets "minor" label. Gets fixed within a day :P

**Comment by t3chguy** [comment]
Fit perfectly between meetings :P
Quick 4 minute jobbie
