### ISSUE TITLE
Element desktop 1.7.4 refuses to start when --no-sandbox is specified

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#14982]
### Description

Element-desktop refuses to start on Ubuntu groovy proposed when it is started with `element-desktop --no-sandbox`, the tray icon will show (_until 1.7.3, not on 1.7.4_)  but won't expand to windowed/full screen unless toggled from tray and then the screen stays white, ultimately forcing the user to quit.

### Steps to reproduce

1. Install element-desktop from the repo mentioned in website on groovy.
2. I updated to 1.7.4 just now, but issue was on 1.7.3 also.
3. Start element with `/opt/Element/element-desktop --no-sandbox` or simply `element-desktop --no-sandbox` in a terminal.

### Describe how what happens differs from what you expected.

Most electron based applications start okay with `--no-sandbox` on Ubuntu rather on Debian where due to the kernel policy they refuse to start with/without the flag.

For the current Ubuntu kernel:

```
cat /proc/sys/kernel/unprivileged_userns_clone
1
```
### Version information

1.7.4 ... -1.7.13
```
# ls -lZd /dev/shm

drwxrwxrwt 2 root root ? 60 Aug 18 15:08 /dev/shm
```
`/run/shm` is a symlink `/dev/shm`

Kernel ( `cat /proc/version_signature` ): Ubuntu 5.8.0-16.17-generic 5.8.0

Error:

```
$ /opt/Element/element-desktop --no-sandbox
/home/user/.config/Element exists: yes
/home/user/.config/Riot exists: no
xdg-settings: default-url-scheme-handler not implemented for xfce
(node:14725) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform

(element-desktop:14725): GLib-GIO-CRITICAL **: 15:13:18.969: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[14766:0817/151319.050250:FATAL:platform_shared_memory_region_posix.cc(254)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```

**Comment by hlauer0** [comment]
Same here on Buster: Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux.
Additionally when starting a remote X connection without --no-sandbox, the elements window shows nothing in it - only the window title is set to the last conversation partner.
Tried version 1.7.3 and 1.7.4 with the same result.
Howto debug this  ?

```
cat /proc/sys/kernel/unprivileged_userns_clone
0
```

**Comment by jryans** [comment]
Are both @kortewegdevries and @hlauer0 seeing this in remote X sessions by chance? If so, [this Electron issue](https://github.com/electron/electron/issues/22775#issuecomment-616023334) seems related.

**Comment by kortewegdevries** [comment]
> Are both @kortewegdevries and @hlauer0 seeing this in remote X sessions by chance? If so, [this Electron issue](https://github.com/electron/electron/issues/22775#issuecomment-616023334) seems related.

Yeah probabaly related, I have to check I don't have ot set up.
