### ISSUE TITLE
my element has queued up 12 requests to GET /publicised_groups

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#14998]
... which means that no other requests are going through. could it cancel them after a while rather than letting them stack up indefinitely?

**Comment by richvdh** [comment]
It's rubbish that synapse blocks for so long, but the client shouldn't just stack them up infinitely.

this waterfall might illustrate the problem: note the overlap in requests:

![image](https://user-images.githubusercontent.com/1389908/90541620-d3915c00-e17a-11ea-8ee0-c9a8dce54ec9.png)

**Comment by t3chguy** [comment]
Well presumably it should not do it in an interval but with a given period between requests

**Comment by turt2live** [comment]
I can't find the issue now, but this also applies when the media repo is slow/overwhelmed: switching rooms can cause a ton of media requests to start up, blocking requests, therefore preventing sync, and starting a death spiral.

**Comment by richvdh** [comment]
Given that /publicised_groups is no longer a thing, presumably this is fixed.
