### ISSUE TITLE
Upgrade from riot-im docker

### ISSUE THREAD

**Issue by dreamflasher** [vector-im/element-web#14994]
### Description

I want to upgrade from an old riot-im docker image, to the new element-web image.

### Steps to reproduce

- `docker pull vectorim/riot-web`
- stop the old container (bubuntux/riot-web:v1.5.0)
- `docker run -p 80:80 -v /etc/riot-web/config.json:/app/config.json vectorim/riot-web`

Describe how what happens differs from what you expected.

After stopping the old container it restarts after a minute. Also updating the old container with restart=no does not help. Stopping it and quickly starting the new one does not help either, only the old one restarts. Even if I quickly prune the old image and container.

### Version information

For the web app:

- **OS**: Ubuntu 18.04

**Comment by turt2live** [comment]
There is no element-web image yet. https://github.com/vector-im/element-web/issues/14930

If you're having issues with the image, visit #element-web:matrix.org for troubleshooting.
