### ISSUE TITLE
=> gets turned into a ligature

### ISSUE THREAD

**Issue by ashkitten** [vector-im/element-web#15006]
### Description

the font element uses turns "=>" into a ligature, both in the message box and the chat log

expected:
![image](https://user-images.githubusercontent.com/9281956/90675760-c1adc880-e20f-11ea-8fdc-ecf3afd07bf1.png)

actual:
![image](https://user-images.githubusercontent.com/9281956/90675700-b22e7f80-e20f-11ea-8fea-0632e65c6e51.png)

this issue occurs on element-web version 1.7.4

**Comment by t3chguy** [comment]
This was intentional as part of the redesign and switch to the `Inter` font. You are welcome to specify your own font choices in Settings > Appearance:

![image](https://user-images.githubusercontent.com/2403652/90750853-50cce600-e2cd-11ea-85f3-e1108663fc14.png)
