### ISSUE TITLE
Notifications remains empty

### ISSUE THREAD

**Issue by annevk** [vector-im/element-web#15009]
I have "Enable notifications for this account" enabled and the other three options disabled (I don't care for getting system-level notifications), but my Notifications view (i.e., the one behind the bell icon) remains empty.

**Comment by t3chguy** [comment]
Which options do you have set to `Noisy`?

Those are the ones which will be shown in the server-side populated notifications timeline. (set_tweak highlight in the push rules API)

![image](https://user-images.githubusercontent.com/2403652/90750541-dc924280-e2cc-11ea-950f-0aaaa96ef5cb.png)

**Comment by annevk** [comment]
I see, I have nothing set to Noisy. I didn't really make the connection with that being noisy...

**Comment by t3chguy** [comment]
Notifications is currently getting an overhaul which will fix things like that.

**Comment by annevk** [comment]
That sounds great, thanks for the heads up and teaching me a new thing.
