### ISSUE TITLE
Widgets other than Jitsi requesting m.always_on_screen are not treated as persistent widgets

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15001]
While developing the [BigBlueButton widget for Dimension](https://github.com/turt2live/matrix-dimension/pull/367), I found that although I requested the `m.always_on_screen` capability, Element would not keep the widget on screen while changing rooms. I found a whitelist for Jitsi widgets looks to currently be hardcoded in Element, ignoring the request capability from any other widget type:

https://github.com/matrix-org/matrix-react-sdk/commit/8f10ee01c6392c7d28d5586f235ee90df18e8419

It would be nice to allow other widgets to successfully request the same capability for this and future conferencing widget types :slightly_smiling_face:

**Comment by fooness** [comment]
It would even be nicer if this would also be possible for e.g. a BigBlueButton widget which was added via `/addwidget` … maybe there’s some way to hardcode this … if it was done for Jitsi, maybe this could also be done for BigBlueButton.

**Comment by turt2live** [comment]
@fooness that would be a different issue.

**Comment by turt2live** [comment]
This required a bit of work, but it's possible now:
![image](https://user-images.githubusercontent.com/1190097/99860150-73ca9880-2b4f-11eb-89e4-b3a848c3c4a7.png)

PR coming shortly
