### ISSUE TITLE
Persistent widget capability `m.always_on_screen` for custom widgets added via `/addwidget` …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15004]
In addition to `Widgets other than Jitsi requesting m.always_on_screen are not treated as persistent widgets` https://github.com/vector-im/element-web/issues/15001, it would be very helpful if custom widgets added via `/addwiget` could also somehow request the `m.always_on_screen` capability to be persistent.

This would allow for example some BigBlueButton widget that was added via `/addwidget` to stay in focus even when changing to some other channel which the widget does not originate from.

**Comment by anoadragon453** [comment]
I believe they can already do this, it's just that https://github.com/vector-im/element-web/issues/15001 is causing the request to be ignored.

Closing this as I believe https://github.com/vector-im/element-web/issues/15001 will solve this issue as well.
