### ISSUE TITLE
Hide Homeserver and always use the server part of the MXID

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#15000]
### Description

From the perspective of a user, the "Homeserver" is the server-part of the Matrix ID. The user should not (and usually does not) care about what redirects are in place to which "real-hostname" of a server.

### Example where the "technical homeserver" is used:

- Sign in screen: `Sign in to your Matrix account on matrix0.example.com` -> should be `Sign in to your Matrix account on example.com` (assuming example.com is the server part of the MXID)

### General wording

Consequently the term Homeserver should only be used for one of the two things and we may need another term for "server part of the MXID" to use in the UI and documentation.

**Comment by hex-m** [comment]
More discussion here: #13661

**Comment by t3chguy** [comment]
This is already possible using well-known config.

https://chat.mozilla.org/#/login is actually https://mozilla.modular.im
![image](https://user-images.githubusercontent.com/2403652/90759252-17e63e80-e2d8-11ea-98b8-4d360e52c65b.png)

https://app.element.io/#/login is actually https://matrix-client.matrix.org
![image](https://user-images.githubusercontent.com/2403652/90759311-2a607800-e2d8-11ea-89f0-5d4037d888a8.png)

If you enter `@x:mozilla.org` in https://app.element.io/#/login it'll say `Sign in to your Matrix account on mozilla.org` but under the tooltip say the actual address; 

![image](https://user-images.githubusercontent.com/2403652/90759406-46fcb000-e2d8-11ea-965c-019ccca2d1be.png)

**Comment by hex-m** [comment]
I figured out what was wrong with my config. The [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md) mentions it actually.

You have to configure the `.well-known` URL and use
```
    "default_server_name": "matrix.org"
```
instead of
```
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix-client.matrix.org",
            "server_name": "matrix.org"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
```
Which  was hard to figure out for me because I started with the [sample config](https://github.com/vector-im/element-web/blob/develop/config.sample.json) which uses the latter approach.
