### ISSUE TITLE
Add mDNS service discovery for Element Desktop

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/element-web#15029]
From a web browser, Element can use mDNS to discover & connect to homeservers on the local network, given that mDNS discovery is installed on the host machine. However, this does not work in the desktop / Electron version of Element, where attempts to resolve names via mDNS fails with `net::ERR_NAME_NOT_RESOLVED`.

It would be convenient if Element Desktop could support mDNS. Apparently, Electron doesn't come with mDNS discovery, but it can be added via a node module:
* https://jbavari.github.io/blog/2016/12/29/multicast-service-discovery-in-electron/
* https://github.com/electron/electron/issues/5612
* https://github.com/electron/electron/issues/2961

Until then, connecting via static IP addresses works just fine.

**Comment by t3chguy** [comment]
Matrix servers don't support mDNS, the spec doesn't say anything about it, so it can't be used for autodiscovery
