### ISSUE TITLE
Community filter page/room list merger

### ISSUE THREAD

**Issue by Fidgetcetera** [vector-im/element-web#15020]
**Is your suggestion related to a problem? Please describe.**
The community pages are... a bit of a mess, and the filter buttons don't make sense, and actually viewing a community's description, especially if there are rules or other important info, is hard to even realize how to reach. Filtering the rooms you're in, and the DMs you have with people in the community, is neat but feels... incomplete.

**Describe the solution you'd like**
I'm thinking about a sort of merger between the room list of communites' description pages, and the room list of filtering, as well as a few tweaks to the filter page to make it stand out.
1. Most importantly: When you filter by rooms in the community, give a big, clear button with the community avatar as the icon, that lets you view the community's long description and user list. (The room list in the longdesc view should be relatively less necessary given the next bit.)
2. Add a hidable section under "rooms" (which could be "community rooms") that is "unjoined rooms", which lists any publicly joinable rooms in the community. 
3. Move "people" below one or both of those, or allow people to move around the "rooms" and "people" lists so that they can prioritize as they like.
4. Also probably show "people" as "people in community", for extra clarity.

**Describe alternatives you've considered**
There's a lot of ways you could take this - minor and major tweaks. You could even make the opposite suggestion to what we did, and remove filtering in favor of just the community description/room list page? It's a bit hard to think of any one specific alternative design here, though.

**Additional context**
If I get the spoons, I'd try to mock this up, especially if someone isn't sure what this design would look like, but I extremely cannot guarantee anything.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
