### ISSUE TITLE
Narrow window squishes text to 1 vertical line

### ISSUE THREAD

**Issue by Prohias** [vector-im/element-web#15038]
### Description

When the screen is narrow, it renders messages in a single vertical line of text.

### Steps to reproduce

Shrink width of window until text goes to a single line

It should probably display a minimum of 12 characters horizontally, anything less is frustrating to users and not the best experience to have to adjust. Ask yourself, "what would Apple's design team do?"

- **Platform**: web (in-browser) or desktop?

Desktop App

**Comment by t3chguy** [comment]
You can disable the community panel and read receipts to allocate more space to the timeline text.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19734
