### ISSUE TITLE
docs question: how does one allow guest access?

### ISSUE THREAD

**Issue by akvadrako** [vector-im/element-web#15033]
I have the following configuration so that I can allow guest access:
```
{
"disable_guests": false,
}
```

The docs mention that it allows "guest access tokens and auto-guest registrations". How does one use these?

**Comment by t3chguy** [comment]
Element only support guests for peeking into rooms. It enforces registration/login at time of joining a room. For future *support* queries use the help room.

Sounds like you want https://github.com/vector-im/element-web/issues/9264

**Comment by akvadrako** [comment]
I looked around quite a bit for a "help room" or other support forum, like on https://element.io/help and the README.md.

Can you supply a link?

**Comment by t3chguy** [comment]
http://matrix.to/#/#element-web:matrix.org
