### ISSUE TITLE
Forgotten chat/room under Historical does not disappear until restarting client

### ISSUE THREAD

**Issue by Rares95** [vector-im/element-web#15031]
1. Leave room/chat, that room will appear under Historical now
2. Forget Room

Observe that the room still appears under Historical until you restart the app. Running latest **Element APP** on Windows (not Web)

**Comment by turt2live** [comment]
this is known, and to be fixed with https://github.com/vector-im/element-web/issues/14038

**Comment by chagai95** [comment]
#15559

**Comment by chagai95** [comment]
This is a slightly related issue, for those of you who might actually be looking for this:
https://github.com/vector-im/element-web/issues/18473
