### ISSUE TITLE
Allow http:// scheme for identity servers

### ISSUE THREAD

**Issue by mrjohnson22** [vector-im/element-web#15030]
In Settings->Discovery, entering an `http://` address as the identity server has it get prefixed with `https://`, so that the final address becomes `https://http://actual_address`. As a result, the connection always fails, as if an invalid address was entered.

It would be nice if identity server didn't get prefixed with `https://` so that connections to `http://` addresses (such as ones on the local network) could be supported. Since homeserver connections can use `http://`, then identity server connections should be able to, as well.

If this was done to prevent connections to `http://` identity servers for security reasons, then a warning dialog should appear to explain that.

**Comment by turt2live** [comment]
The spec requires us to talk HTTPS to identity servers, sorry.
