### ISSUE TITLE
Element Desktop screensharing does not work.

### ISSUE THREAD

**Issue by strobili** [vector-im/element-web#15040]
### Description

When attempting to screen share on the Element Desktop app, it fails with two varying errors seemingly picked at random.

### Steps to reproduce

- Shift-click with your left click on the camera icon in a DM/room to attempt to start a screen sharing call on the desktop app.

When attempting to start a screen sharing call, I would expect to start a screen sharing call as the web version works fine.

- Logs being sent: No

### Screenshots
![image](https://user-images.githubusercontent.com/45148684/91183159-2017f280-e6b9-11ea-83a6-bd5e80204183.png)

![image](https://user-images.githubusercontent.com/45148684/91183245-3d4cc100-e6b9-11ea-9994-d0c779046928.png)

- (The Second one is a lot less common and most often happens after ending a normal voice call and then trying to start a screen sharing call.)

### Version information

- **Platform**: Desktop
- **OS**: Arch Linux
- **Version**: Arch does not have any specific "versions" as it's a rolling release. The best I can do is provide the date at which I installed it: August 15th, 2020.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/1276

**Comment by ixxie** [comment]
I'm reproducing the second error message.


-     Platform: Desktop
-     OS: NixOS (unstable channel)
-     Version:
  *       Element version: 1.7.5
  *       olm version: 3.1.3

**Comment by jezekus** [comment]
Hello I am getting same error: "Failed to get screen-sharing stream: NotAllowedError: Permission denied"

- Platform: Linux Desktop

Versions:

- Element: 1.7.8

- olm: 3.1.3

**Comment by Kommynct** [comment]
I think the goal should be to support xdg-desktop-portal for wayland setups, right?

**Comment by r4dh4l** [comment]
Same here pressing the video call button holding shift key:

> Call Failed
> Failed to get screen-sharing stream: NotFoundError: Requested device not found

Platform: GNU/Linux Desktop
OS: Debian 10.6
Element version: 1.7.10
olm version: 3.2.1

**Comment by CarsonVB** [comment]
Call Failed
Failed to get screen-sharing stream. :NotAllowedError: Permission denied
Platform: Windows Desktop App
OS: Windows 10
Element version: 1.7.11
olm version: 3.2.1

**Comment by QEDeD** [comment]
Call Failed
Failed to get screen-sharing stream: : NotAllowedError: Permission denied

Platform: Desktop
OS: Windows 10
Version: Version 10.0.19041 Build 19041
Element version: 1.7.12
Olm version: 3.2.1

**Comment by JPustkuchen** [comment]
Same problem here on windows.

After the error message you can't create a regular call anymore. The error says "You're already in a call"

Platform: Desktop
OS: Windows 10
Version: Version 10
Element version: 1.7.13
Olm version: 3.2.1

**Comment by SimonBrandner** [comment]
I believed this is cause by [this](https://github.com/electron/electron/issues/25534) Electron issue.

**Comment by SimonBrandner** [comment]
I've been doing some research and it may be worth looking into [Wire webapp](https://github.com/wireapp/wire-webapp)'s source.

**Comment by SimonBrandner** [comment]
I think I can maybe manage to get this working using [this](https://github.com/electron/electron/issues/16513#issuecomment-602070250)

**Comment by jasonmerc** [comment]
This issue persists once again in the element desktop app, tested in both Windows and Debian.  It just shows an infinite loading screen when you click Share Screen in a Jitsi call.  This does NOT happen in the browser app (app.element.io), it works perfectly fine there.

**Comment by SimonBrandner** [comment]
@jasonmerc, you're talking about https://github.com/vector-im/element-web/issues/4880 which is about group (Jitsi) calls. This issue was about the 1:1 calls

**Comment by jasonmerc** [comment]
Didn't realize they were different, thought "matrix calls" referred to Jitsi calls (as in that's the service they used for all calls).  Thanks for the clarification.
