### ISSUE TITLE
highlight with color nickname in result of /me command

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#15041]
![1](https://user-images.githubusercontent.com/1297163/91248674-832c8680-e798-11ea-87f2-a1a3ae96d375.png)

Result (2) of `/me` command not highlight by color as (1)

element-desktop 1.7.3
ubuntu 16.04 amd64

**Comment by turt2live** [comment]
effectively https://github.com/vector-im/element-web/issues/9482
