### ISSUE TITLE
When creating a DM with someone, it's now labelled 'empty room'

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15047]
Clicked on someone's avatar to get to their user profile, then clicked, "Direct Message" which created a room since I didn't already have one. The room was shown as "Empty Room" in the room list for some time, although eventually updated even without them joining.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/6535 which has a plausible explanation in the title for how/why this happens.

Possible that there are multiple causes for this though.
