### ISSUE TITLE
Missing session data

### ISSUE THREAD

**Issue by popindavibe** [vector-im/element-web#15053]
### Description

Browser cannot decrypt messages posted from Element Android app (installed from F-Droid) when computer resume in the morning. This used to work fine with Riot-Web. Now the request to get the keys does not result in anything, and I need to log out and back in with my encryption passphrase to decrypt the messages written last night.

### Steps to reproduce

- Authenticate in Element-Web in desktop browser
- Authenticate in Element app in Android
- Suspend desktop
- Send messages from Android to an encrypted room or DM
- Resume desktop
- Element-Web cannot decrypt the messages, and on refresh displays:

![](https://pic.nomagic.uk/LBzwwWYX)

Describe how what happens differs from what you expected.

Log: sent  

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 68.10.0esr
- **OS**: Debian Buster
- **URL**: riot.nomagic.uk  v1.7.4

**Comment by turt2live** [comment]
As mentioned in the dialog, your browser has decided to delete some of your session data.

**Comment by popindavibe** [comment]
Why now and not before then? The website is whitelisted everywhere on all plugins. Maybe a plugin that was installed recently? I'll check. But there is no memory issue, I have more than enough to keep things in cache.

**Comment by turt2live** [comment]
Browsers tend to do all kinds of weird things we can't control, like delete data when they think you aren't using it anymore.

**Comment by popindavibe** [comment]
hmm, ok. But it's hampering usability quite a bit, I had to re-auth + passphrase for 2 consecutive days, when it used to work like a breeze.
If I see any change (or if it stops) I'll update here for reference. Thanks for looking into it.

**Comment by popindavibe** [comment]
Well, looks like this fixed itself after a few days. All good now.
