### ISSUE TITLE
Making use of SRV-Record or .well-known to set Homeserver

### ISSUE THREAD

**Issue by dymattic** [vector-im/element-web#15054]
**Is your suggestion related to a problem? Please describe.**
Right now element defaults to matrix.org Homeserver.

For a not so tech savvy person to change the homeserver address to the one that the account is using, it can be a hastle.
It gets even more complicated when the homeserver adddress is "subdomain.domain.tld", but the homeserver name is "domain.tld".

I had some people already complain about not being to log in because of this.

**Describe the solution you'd like**
Matrix or rather synapse already utilize the .well-known method for finding the appropriate settings for homeservers.
Another way that should be considered are SRV-Records in DNS.

It would drastically enhance usability with relatively little effort, if element would try to resolve the right homeserver address by extracting the "domain.tld" from the username "@user:domain.tld" to search for SRV-Records or .well-known entries and set the used homeserver accordingly. 

This could still be overridden by manually setting the homeserver address.

If the resolution didn't find any results, matrix.org can still be defaulted to.

Example nginx-vhost/ location block for .well-known:

```
location /.well-known/matrix/client {
    default_type application/json;
    return 200 '{
        "m.homeserver": {
             "base_url": "https://subdomain.domain.tld"
        }
}
```

**Comment by turt2live** [comment]
This would require changes to the spec: https://github.com/matrix-org/matrix-doc

When running your own homeserver with significant user base, it's highly recommended to run your own Element with your homeserver pre-configured, thus avoiding the matrix.org issue.

**Comment by dymattic** [comment]
Sorry for replying on a closed issue, but:

Maybe I should have opened this issue at the element-android and element-ios repositories, but I thought this could apply here as well.
This is an issue for element-desktop as well.

I am hosting an element instance where this isn't an issue.

Though I don't quite understand how this would require changing the spec, if the .well-known record already is being used.
Do you mean you would have to change the spec, because the m.matrix-client entry is intended for being used by homeservers at the moment?

**Comment by turt2live** [comment]
When I first read this it sounded like you were proposing something other than the discovery method already defined by the spec. 

If this is an issue with the mobile apps, please use their issue trackers instead.

**Comment by t3chguy** [comment]
In the Web and Desktop apps if you enter `@foo:mozilla.org` in the Username field of login and then blur it, it'll look up the well-known record and pre-fill the HS url.

It cannot use SRV as SRV is only for federation delegation and web apps cannot look up SRV records.

**Comment by dymattic** [comment]
@turt2live Alright I'll open an issue there 👍 

@t3chguy OK that's neat, I thought it did not, would be awesome if it would do that also when you type i.e. : foo@mozilla.org

**Comment by t3chguy** [comment]
How with `foo@mozilla.org`

That is an e-mail address which would suggest logging in by e-mail, no?

**Comment by dymattic** [comment]
Yikes, you're right.

I tried logging in with @username:foo.bar and it didn't work (on app.element.io)
Does it just use foo.bar as HS or does it actually try to resolve the .well-known?

**Comment by t3chguy** [comment]
Looks up the well-known from `https://foo.bar:443/.well-known/matrix/client`

**Comment by t3chguy** [comment]
in the case of `@foo:mozilla.org` the HS URL is `https://mozilla.modular.im`

**Comment by dymattic** [comment]
OK, seems to be a misconfiguration on my end.
Awesome, thanks for the help!
