### ISSUE TITLE
Is e2e available on camera and audio calls for element-web and native clients?

### ISSUE THREAD

**Issue by gafarma89** [vector-im/element-web#15057]
Hi,

Is e2e available on camera and audio calls for element-web and native clients?

Or is there a misinformation on this thread:

https://www.reddit.com/r/privacytoolsIO/comments/iecqnu/e2e_encryption_elementio_vs_signal/

If not can you please support it?

Thank you

**Comment by t3chguy** [comment]
This is a bug tracker, please use the Matrix room for queries; https://matrix.to/#/#element-web:matrix.org

Matrix & Element support full e2ee (p2p or via TURN) using WebRTC for voice & video calls.
Element only uses them for 1:1, for conferencing it uses Jitsi.
