### ISSUE TITLE
wrong audio settings some times

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#15068]
Some times I do not hear voice at of 1:1 voip.

When I open sound settings of element-desktop - I see more devices for record voice and play voice:
![1](https://user-images.githubusercontent.com/1297163/91648853-08bd7880-eab0-11ea-80eb-7c75abe13602.png)

In result - I can not select properly device for hear remote voice in 1:1.

At next day I switch on my PC and in sound settings of element-desktop I see, that many settings set at "Default" values. If I try change it - I see other situation:
![3](https://user-images.githubusercontent.com/1297163/91648877-7cf81c00-eab0-11ea-965f-154c890ff2ef.png)
![2](https://user-images.githubusercontent.com/1297163/91648879-7e294900-eab0-11ea-9334-24025983e4d2.png)

It is more usable and understand.

version of Element: 1.7.3
Ubuntu 16.04 amd64
Audio system: pulseaudio

**Comment by progserega** [comment]
some times it reproduce at Element-desktop 1.7.20

If bug occur - quit and start element-desktop (without exit from account) - fix problem at current seance. But at next boot - can occur again. 
Today I receive 1:1 voip call and remote user can not listen my voice. Only when I quit/start element-desktop on localhost, wait sync end - voice call stay work.

**Comment by SimonBrandner** [comment]
Hmm, this seems like an upstream issue rather than an Element one. @progserega, do you still see this sometimes? If you ever see this again, could you please try to run 

```
await window.navigator.mediaDevices.enumerateDevices()
``` 

in the dev console (`Ctrl-Shift-I`) and share the output with us?

**Comment by progserega** [comment]
At last time this bug not more occur in my situation. May be it fixed? :-) 
May be it fixed because I migrate from ubuntu 16.04 -> Ubuntu 20.04...

**Comment by SimonBrandner** [comment]
Ah, let's close this then. Let us know if you see ever this again
