### ISSUE TITLE
some messages appearing in triplicate

### ISSUE THREAD

**Issue by simonmichael** [vector-im/element-web#15063]
Beginning today, several messages I have posted appeared in triplicate (two extra copies). Other users have noticed and are inclined to grumble, so I'd welcome any pointers to help diagnose/prevent this. Nobody else seems to be talking about it in the matrix/element rooms.

- I use a matrix.org account

- One of the repeated messages was posted in #lambdahack:mozilla.org, with Element IOS
  ![Screen Shot 2020-08-28 at 11 54 41 AM](https://user-images.githubusercontent.com/10144/91605405-45109d80-e925-11ea-89df-b111243442e2.png)

- The other was posted in #freenode_#plaintextaccounting:matrix.org, with Element desktop (mac).
    ![Screen Shot 2020-08-28 at 11 55 22 AM](https://user-images.githubusercontent.com/10144/91605477-5fe31200-e925-11ea-96f5-815ccc24b2c6.png)

Usually I see a single copy of my messages, as expected.

Logs being sent: yes

- Element macos 1.7.4
- Element IOS 1.0.0 rebranding #20200713192130

**Comment by turt2live** [comment]
This appears to be a server-side issue, likely https://github.com/matrix-org/synapse/issues/3365

**Comment by simonmichael** [comment]
Thanks.

Maybe @reivilibre will make progress on this soon. If not, might an interim workaround in the client be possible ? Eg, wait longer before retrying, or ask the user before retrying (maybe it does this ? If so I have a solution, and I'll be slower to click "resend").
