### ISSUE TITLE
Desktop: Setting To Launch Element Minimized To Tray

### ISSUE THREAD

**Issue by trymeouteh** [vector-im/element-web#15078]
Please add a setting to allow Element to be launched minimised to the tray. This way when I set Element to be a startup application on my computer it will startup in the background.

**Comment by t3chguy** [comment]
That's what it does when you enable start at system launch in Settings > Preferences.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/91956629-d9e81200-ecfc-11ea-96b4-6862e8a9bac6.png)

Bottom option

Additionally, you can pass `--hidden` as a command line arg to your autostart script and it'll do the same thing.

**Comment by trymeouteh** [comment]
> ![image](https://user-images.githubusercontent.com/2403652/91956629-d9e81200-ecfc-11ea-96b4-6862e8a9bac6.png)
> 
> Bottom option
> 
> Additionally, you can pass `--hidden` as a command line arg to your autostart script and it'll do the same thing.

The settings does not work on Linux at least. And this settings seems to be designed to launch the app on startup, not launch the app mininized.

**Comment by t3chguy** [comment]
> And this settings seems to be designed to launch the app on startup, not launch the app mininized.

It does both, it launches it with `--hidden`. You can add `--hidden` to your shortcuts/autostart.
