### ISSUE TITLE
Ethercalc widget incorrectly points to ethercalc.org instead of ethercalc.net

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-web#15074]
The ethercalc widget currently is not working. The origin of this problem seems to be that all links are pointing to ethercalc.org instead of ethercalc.net. 

Perhaps they recently changed their domain name...

**Comment by jaller94** [comment]
This commit might be helpful as to what needs to be changed:
https://github.com/matrix-org/scalar/commit/7e64af991849eb370186da1937d196765821b572

**Comment by jaller94** [comment]
A statement that confirms the domain change:
https://github.com/audreyt/ethercalc/issues/725#issuecomment-684599376

**Comment by MarkWieczorek** [comment]
> This commit might be helpful as to what needs to be changed:
> [matrix-org/scalar@7e64af9](https://github.com/matrix-org/scalar/commit/7e64af991849eb370186da1937d196765821b572)

That link gives a 404 error. Is it a private repo or something?

**Comment by jaywink** [comment]
Ethercal widgets have been fixed, by pointing to ethercalc.net instead of ethercalc.org. The owner recently switched domains. Existing sheets should all work fine assuming the new domain has the old data. Thanks for reporting!
