### ISSUE TITLE
Notification setting radio button descriptions are not clear

### ISSUE THREAD

**Issue by Gnuxie** [vector-im/element-web#15070]
**Is your suggestion related to a problem? Please describe.**
For example 'Messages sent by bot' does this mean we're being notified of every message ever sent by a bot or something like 'when a bot mentions your name, you will be notified'? It seems sort of really unrealistic someone would want to be notified of every bot message, yet this appears to be what the setting does? I also don't get notified when mentioned from the irc bridge accounts and I thought that was due to this setting?

**Describe the solution you'd like**
A clarification that says what it's actually doing. I want notifications when a bot mentions my name, but not when it's unrelated. I guess part of the problem is whether the different settings in this table can 'clobber' each other for example:

When selecting 'Messages containing my username' but not 'Messages in group chats', does this mean you don't get mentions from group chats anymore?

There doesn't seem to be an example for any setting that is in a list like this in the app with a detailed explanation.

**Comment by turt2live** [comment]
Effectively fixed by https://github.com/vector-im/element-web/issues/13959
