### ISSUE TITLE
Element opens a new DM for users where I already have a DM with them

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15075]
# Description

In the right panel, I click @babolivier:vector.modular.im -> Direct Message. This creates a new room instead of opening our existing DM

Element Nightly version: 2020082801

**Comment by benparsons** [comment]
Logs sent

**Comment by t3chguy** [comment]
> I already have a canonical DM

Can you define what you mean by this?

Is the room ID listed in `m.direct` account_data under their MXID? (You can use /devtools to check)

**Comment by benparsons** [comment]
Yes, meant to say `m.direct`, rather than canonical.

In my `m.direct` I now see:

```
    "@babolivier:vector.modular.im": [
      "!v...Z:bpulse.org",
      "!J...z:bpulse.org"
    ]
```

**Comment by turt2live** [comment]
We have a poor amount of logging for this area of the app and can't really diagnose what went wrong without knowing what the account data was *before* the invite was sent.

Would be fixed by https://github.com/vector-im/element-web/issues/3457

**Comment by Half-Shot** [comment]
This happened again, so I've added logs. They might not be useful, but as they say: rageshake away.

**Comment by turt2live** [comment]
I haven't heard of this happening recently, so closing for now. If this happens in the future, please open a new issue with fresh information.
