### ISSUE TITLE
Replace background-image with mask-image for search icon in members tab …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15084]
The members tab (clicking the members icon in the top right) still uses a background-image for the search icon …

<img width="331" alt="Screenshot 2020-09-02 at 13 29 28" src="https://user-images.githubusercontent.com/11408027/91975888-6526cf00-ed20-11ea-910b-38548c6515a9.png">

This was already changed in the search bar (clicking the search icon in the top right) so that it uses mask-image and can therefore better be addressed in css e.g. by colors (relevant for theming).

<img width="557" alt="Screenshot 2020-09-02 at 13 27 54" src="https://user-images.githubusercontent.com/11408027/91976044-ad45f180-ed20-11ea-95c9-e53b522482f5.png">

_Also this was already changed in the new room list, but this is probably a completely new search component as it also uses a different search icon, I suppose …_

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/85698511-6dea-425e-9c94-a8fafbdf1e90)

This happened
