### ISSUE TITLE
Mention or username pill in “In reply to <username>” does not respect setting for showing avatar in mentions …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15080]
The mention or username pill in “In reply to <username>” does not respect the Element setting `Show avatars in user and room mentions` …

Picked this screenshot from Matrix HQ …

<img width="243" alt="Screenshot 2020-09-02 at 08 15 28" src="https://user-images.githubusercontent.com/11408027/91938715-c5078080-ecf4-11ea-80c3-f200636959e3.png">

PS: The same is kind of true for events like “Custom Widget added by”, which only shows the user’s avatar right before the text message but without pill or usersname. I think this status message should be adapted to behave like the others (show pill with avatar plus username, or only username if Element is configured that way.)

**Comment by t3chguy** [comment]
> PS: The same is kind of true for events like “Custom Widget added by”, which only shows the user’s avatar right before the text message but without pill or usersname. I think this status message should be adapted to behave like the others (show pill with avatar plus username, or only username if Element is configured that way.)

Not at all, those aren't pills or mentions. They are Sender Profiles.
