### ISSUE TITLE
Sorry, Riot is not supported by your browser

### ISSUE THREAD

**Issue by CEO-VISION-MatthiaS** [vector-im/element-web#15086]
### Description

Message indicating that Riot is not supported by my browser when I am on Chrome

### Steps to reproduce

- When riot is instantiated.

It seems obvious that riot is supported on chrome, it should just show me riot.

It is impossible for me to provide you the logs for this bug

![riot_warning](https://user-images.githubusercontent.com/70635044/91983225-ab356000-ed2b-11ea-9586-c6398930f49a.JPG)

### Version information

- **Browser**: 
Version 85.0.4183.83 (Build officiel) (64 bits)

- **Version of riot-web**: 
1.6.0-rc.3
https://github.com/vector-im/element-web/blob/develop/CHANGELOG.md#changes-in-160-rc3-2020-04-17

**Comment by t3chguy** [comment]
That version is very old. Please update. Additionally check your Javascript console to see what feature is missing.

**Comment by CEO-VISION-MatthiaS** [comment]
> Cette version est très ancienne. Veuillez mettre à jour. Vérifiez également votre console Javascript pour voir quelle fonctionnalité manque.

![dev_riot](https://user-images.githubusercontent.com/70635044/91993560-cdcc7680-ed35-11ea-8a44-8297426ca7b7.JPG)

And 1.7.3 version ...
https://github.com/vector-im/element-web/blob/develop/CHANGELOG.md#changes-in-173-2020-08-05

**Comment by turt2live** [comment]
Visit #element-web:matrix.org for support.

**Comment by CEO-VISION-MatthiaS** [comment]
Hello, just for info for others, errors occur when the iframe loads with `display: none` and not with `visibility: hidden`

**Comment by t3chguy** [comment]
Check the console to see which Modernizr checks fail in that scenario.
