### ISSUE TITLE
while registration: ERROR for site owner: Invalid domain for site key

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-web#15104]
# Steps:

- OS: Linux Mint, using https://app.element.io/#/register
- Enter Username
- Enter Passwort 123 (was not allowed to simple)
- Enter Passwort 12345 (was not allowed to simple)
- Enter Passwort 12345789 (was not allowed to simple)
- Enter Passwort .12345789 (was not allowed to simple)
- Enter Passwort  ... working
- Enter Homeserver:  tchncs.de
-- error message
- Enter other Homeserver:  https://matrix-tchncs.de
- Enter Username
- Enter Passwort  ... working
-- wrong homeserver
- Homeserver:  https://matrix-tchncs.de
- Enter Homeserver: https://tchncs.de
- Enter Username
- Enter Passwort

# ERROR: 

**ERROR for site owner: Invalid domain for site key**

# suggestions:

Please have a bot that makes suggestions in case of home server errors (typical errors): 
- no https
- no https://
- wrong subdomain in correct domain. 
- Perhaps also several home servers in a selection list. 3 most used servers in country? 

Please add a link to your servers picture:
![image](https://user-images.githubusercontent.com/5634759/92304473-8553c980-ef7e-11ea-8aff-78f30a6a8f62.png)

Please dont delete all entries while changing the homeserver

**Comment by t3chguy** [comment]
Sounds like the homeserver are you trying to register on has a broken recaptcha config. Contact their operators.

**Comment by verymilan** [comment]
the new (sub)domain for this homeserver is `https://matrix.tchncs.de`.
this error tends to appear on desktop clients like element-desktop only, the webclient at `chat.tchncs.de` should work.

**Comment by sl5net** [comment]
> `homeserver is https://matrix.tchncs.de`
Error is not changing here https://app.element.io/#/register :
```
This homeserver would like to make sure you are not a robot.
ERROR for site owner: Invalid domain for site key**
```

**Comment by sl5net** [comment]
if i use `https://chat.tchncs.de` in https://app.element.io/#/register
```
Cannot reach homeserver
Ensure you have a stable internet connection, or get in touch with the server admin

**Comment by verymilan** [comment]
You should not use the element-web issueticker for this ... anyway, try https://chat.tchncs.de/#/register for creating your account.

**Comment by turt2live** [comment]
This issue doesn't appear related to element.
