### ISSUE TITLE
In Windows OS, second registration failes with cryptical Error-Mesage

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-web#15103]
### Description long 

Friend created account yesterday. First a Matrix - Home-Server, with email address. That works and we confirmed the email in the email client.

At the same time, the coffee and cake conversation continued and he wanted a faster home server from Germany (tchncs.de).
From my address we did not know tchncs.de but the home server address. 

It was almost impossible for me to help because I didn't have a computer with me. This caused a lot of frustration and took up a lot of time. I guessed the address was correct, but he had some difficulties using the keyboard (no 10-finger technique).

After many minutes, we had an error message that was just a numeric code in red. He has given up.

I **hope** he might try again in a few months. Should I happen to see him again earlier, and maybe even have his laptop with him again. Let's try again.

**Please** also test the system for Windows users with a poor Internet connection and Skype that is (unfortunately) installed at the same time. Please have a bot that makes suggestions in case of home server errors (typical errors). Perhaps also several Reverent home servers in a selection list.

**Please** test with windows. 

Unfortunately I cannot change it. Windows is a reality. I can't tell the friends that you have to install Linux first. Unfortunately. I also have virtual machines running Windows. When I have time, I can handle it. Simple people who use Windows are influencers, teachers, civil servants, principals.

### Version information

I only could say it was Windows OS laptop. 

- **Platform**: We instlled it as recomandet from the element.io Website

**Comment by sl5net** [comment]
i send this error messege from my Linux - System, the day after. He used a Windows OS

**Comment by turt2live** [comment]
it looks like this is a problem with the homeserver and not Element, sorry. You'll have to contact the operators.
