### ISSUE TITLE
Users suddenly can't send messages in rooms on different devices

### ISSUE THREAD

**Issue by biglypiglywigly** [vector-im/element-web#15105]
### Description

Recently users have been suddenly unable to send messages in rooms on different devices for no reason and can't fix the issue

### Steps to reproduce

- Unable to reproduce the bug 

Users should still be able to send messages on all devices

Logs being sent: no

### Version information

- **Platform**: desktop and web

For the web app:

- **Browser**: Chrome
- **OS**: Windows 10 Home
- **URL**: https://app.element.io

For the desktop app:

- **OS**: Windows, Mac OS, Linux, etc
- **Version**: 17.4

**Comment by turt2live** [comment]
what is the error they are getting?

**Comment by biglypiglywigly** [comment]
It never produces an error message, but gives the default response when you typically can't send a message.

**Comment by turt2live** [comment]
what sort of behaviour is giving the indication that it's not working then?

**Comment by biglypiglywigly** [comment]
First time it occurred was after encryption was enabled in a room long after the room was created. Also worth noting was that room creation was during Riot.im, and happened after rebrand. Everyone had to abandon it since they were unable to messsages on primary devices. 

One other side effect was that messages from other users said they were not encrypted, even though encryption was enabled for the room.

**Comment by turt2live** [comment]
So what happens when they send a message? If there's no error, then we need to know what exactly they are seeing so we can look into it.

**Comment by biglypiglywigly** [comment]
Sorry. To clarify, the error is something like "Unable to send message"

**Comment by turt2live** [comment]
Can you have those users go to Settings -> Help -> Submit Debug Logs and use this issue for the github url please?

**Comment by kittykat** [comment]
I'm going to close this issue for now as we haven't had any updates with more information, which means that we are unable to debug it. Please open a new issue with rageshakes if you are still experiencing it.
