### ISSUE TITLE
Settings > Profile doesn't make it clear enough that changes are pending

### ISSUE THREAD

**Issue by ananace** [vector-im/element-web#15108]
### Description

With our increasing usercounts, we've been getting reports on people who are annoyed that changes to their user profile don't seem to apply. Often because they don't realize that their changes are unsaved data.

I've had people suggest making the save button more prominent when unsaved data's present - instead of just the slight dimming it currently has. Or perhaps giving a small "Are you sure you don't want to save your changes?" question if closing the dialog with unsaved changes.

### Steps to reproduce

- Open profile settings
- Click to upload avatar
- See avatar image change
- Close the settings dialog
- Don't have the newly set avatar applied

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Chrome, Firefox
- **OS**: Windows, Ubuntu, Debian
- **URL**: Private, version 1.7.4

**Comment by turt2live** [comment]
tbh I've witnessed internal folk running into the exact same issue

**Comment by RinkiyaKeDad** [comment]
Hey, I'm new to Element development and would like to work on this issue if someone isn't already working on it. I was thinking of creating a modal like the one we show whe user clicks on the "Change Password" button without entering any new password. I'll triger a modal like that when user closes the settings window but has some unsaved changes. Can I work on this?
