### ISSUE TITLE
Popups on load never go away

### ISSUE THREAD

**Issue by Gibbz** [vector-im/element-web#15101]
### Description

Every time I login to matrix/element there is a few popup's that never go away. The security review is the main one. How many times do I need to do the security review for the popup to go away?

### Steps to reproduce

- Login to matrix/element from the web interface
- Popups!

Describe how what happens differs from what you expected.
Remember that you have closed it.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox
- **OS**:  Arch Linux
- **URL**: https://app.element.io

**Comment by turt2live** [comment]
@Gibbz it sounds like you haven't verified one or more devices on your account if you're seeing that popup.

**Comment by Gibbz** [comment]
Yes, there are numerous ones in the list that are not verified (about 20 or so).... But I can find no way to delete them from the list as they are old logins.

**Comment by t3chguy** [comment]
Settings > Security & Privacy

**Comment by turt2live** [comment]
Closing as this is solved by deleting/verifying the affected devices
