### ISSUE TITLE
Can't verify my session

### ISSUE THREAD

**Issue by stemy2** [vector-im/element-web#15110]
**Description**
I'm prompted to verify my session, but nothing happens when i'm logging into another device. And i don't get what "recovery keys" means.

### Steps to reproduce

-Install the desktop app
-Log into the desktop app
-Install mobile app
-Log into mobile app

Describe how what happens differs from what you expected.

I'm not sure, but verification should work when i'm connected with 2 devices.
Logs being sent: no

I'm not connected, so i can't access to the logs.

### Version information

- **Platform**: Samsung S7 + Android 7.1.2

For the desktop app:

- **OS**: Debian
- **Version**: 1.7.5

**Comment by turt2live** [comment]
On a previous device you should have been asked to set up/upgrade encryption, which will be the device you need to verify with.
