### ISSUE TITLE
trying to download m4a opens it in a new tab/browser

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15117]
![image](https://user-images.githubusercontent.com/14617699/92470814-ac5d0600-f1df-11ea-8db2-594cb305ffdf.png)

Clicking on `Download` just opens it in a new tab / browser.

Element 1.7.5 desktop or web in FF 80.0.1 Debian sid.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/12405

**Comment by 532910** [comment]
Thank you.
