### ISSUE TITLE
1 to 1 rooms appear under Rooms section and not under People

### ISSUE THREAD

**Issue by pabelenda** [vector-im/element-web#15116]
### Description

I'm a synapse admin and many of my users have reported thru the last 3 years that they have 1 to 1 rooms under the Rooms section, not at People one. In previous versions of element/riot, there was an option to mark the room as 1 to 1 like. This option is gone and so our workaround to mend the situation.

### Steps to reproduce

I really don't know what causes this. I'm not aware of any steps that can lead to such a situation.

Logs being sent: no

### Version information

- **Platform**: both web and desktop

For the web app:

- **Browser**: All of them
- **OS**: All of them
- **URL**: It's a private server. This has been happening on the many versions we've went through in the last years. Currently running 1.7.1. I've tested 1.7.5 on our beta environment, and the option to mark the room as 1 to 1 is missing too, so I guess this is still a thing.

For the desktop app:

- **OS**: All of them
- **Version**: 1.7.X

**Comment by t3chguy** [comment]
Do you have any bridges running?
The issue tends to be faulty clients but element-web tends not to be one of them.
The option was removed and the issue is https://github.com/vector-im/element-web/issues/14942

**Comment by pabelenda** [comment]
In this case, we are not using any bridge at all. Anyway, thanks for the pointer to the issue. Seems like some of my users didn't changed their rooms before I upgraded to newer versions.
