### ISSUE TITLE
3pid invites dump you on the welcome page

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15130]
We could probably do better than this

**Comment by turt2live** [comment]
1. Invite someone by email to your room
2. That person opens the email link
3. "Welcome to Element!" -> Should probably be some sort of "Travis has invited you to join Secret Room"

**Comment by niquewoodhouse** [comment]
Hey @turt2live Im just looking through some issues for things that might be relevant for early user retention and think this might fit.  I don't want to assume anything so, would you mind confirming if the 1,2,3 you've written above is pretty much how it ended up?  Or do you feel there's some outstanding iteration to it?  Thanks
