### ISSUE TITLE
the section resize handles have become very fiddly to use

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15145]
on the rightpanel and the auxpanel, you have to drag the hoverover handle itself rather than any point along the edge - unlike the leftpanel. please can we make the whole edge draggable?

**Comment by lampholder** [comment]
The right panel can be dragged anywhere along the edge, but the dragabble region seems _much_ narrower than on the roomlist panel - ideally the rightpanel dragwindow would be the same as on the roomlist (which seems pretty easy to use imo).

The auxpanel/widget drawer is only draggable by the handle - this would be great to fix.
