### ISSUE TITLE
e.grecaptcha.render is not a function

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15142]
Might be matrix.org specific:
![](https://i.imgur.com/T7RU1ND.png)

The captcha works fine despite the error

**Comment by t3chguy** [comment]
Isn't that error in the thing that recaptcha renders and thus not an eleweb issue?

**Comment by turt2live** [comment]
"might be matrix.org specific" :p

**Comment by t3chguy** [comment]
So this looks like a race condition as we render it multiple times and seems like sometimes ordering makes things unhappy
