### ISSUE TITLE
Event links are rendered as room ID pills - trampled/mangled inline markdown link

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#15159]
### Description

When sending an inline link to an event, it's rendered as a room ID pill instead of showing the text in the link.

### Steps to reproduce

- Send an event link (`[foo](https://matrix.to/#/!jhpZBTbckszblMYjMK:matrix.org/$1599910718168033gYYvs:matrix.org?via=matrix.org&via=maunium.net&via=sorunome.de)`)

<details>
<summary>Event JSON</summary>

```json
{
  "content": {
    "body": "[foo](https://matrix.to/#/!jhpZBTbckszblMYjMK:matrix.org/$1599910718168033gYYvs:matrix.org?via=matrix.org&via=maunium.net&via=sorunome.de)",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/!jhpZBTbckszblMYjMK:matrix.org/$1599910718168033gYYvs:matrix.org?via=matrix.org&amp;via=maunium.net&amp;via=sorunome.de\">foo</a>",
    "msgtype": "m.text"
  },
  "event_id": "$1599910724168059ebMEv:matrix.org",
  "origin_server_ts": 1599910724947,
  "sender": "@tulir:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 226
  },
  "room_id": "!jhpZBTbckszblMYjMK:matrix.org"
}
```

</details>

Expected result: [foo](https://matrix.to/#/!jhpZBTbckszblMYjMK:matrix.org/$1599910718168033gYYvs:matrix.org?via=matrix.org&via=maunium.net&via=sorunome.de)

![image](https://user-images.githubusercontent.com/4224639/92994787-fc044000-f505-11ea-97d5-e85671b6c041.png)

Actual result: a pill that shows the room ID, confusing anyone receiving the link

![image](https://user-images.githubusercontent.com/4224639/92994785-f7d82280-f505-11ea-895b-f46ec069ad21.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 81
- **OS**: Ubuntu 20.04
- **URL**: develop.element.io, mau.chat

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/0a7090dd64a5d648d371281d09a924d11ad82945/src/components/views/elements/Pill.js#L31 THE COMMENT LIES!

**Comment by turt2live** [comment]
that regex needs to die

**Comment by MadLittleMods** [comment]
I added "trampled/mangled inline markdown link" to the title to more easily find this in the future. We have a similar issue on Gitter https://gitlab.com/gitlab-org/gitter/webapp/-/issues/326 that I am comparing it to.
