### ISSUE TITLE
[UX] feature_custom_status could be displayed in People list (on left) instead of Members (on the right)

### ISSUE THREAD

**Issue by arthurlogilab** [vector-im/element-web#15154]
### Description

Right now `feature_custom_status` displays in the room Members list on the right 

![Screenshot from 2020-09-11 15-10-18](https://user-images.githubusercontent.com/445200/92929610-1e805580-f441-11ea-8844-65b2c8c8c9ce.png)

which is a great first step ! Thanks and kudos for making this go forward... 

On the right we have the People list 

![Screenshot from 2020-09-11 15-10-33](https://user-images.githubusercontent.com/445200/92929653-31932580-f441-11ea-8c2c-3ed83da44f20.png)

It would be great to have this custom status displayed there instead (or in addition) to the member list. Some of our users don't display that members list. 

### Version information

- **Platform**: both web and desktop

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu/Debian
- **URL**: private server, Element version: 1.7.4

#### Question : 

Can this be obtained by using the custom themes ? https://github.com/vector-im/element-web/blob/develop/docs/theming.md

**Comment by turt2live** [comment]
This was intentionally removed from the room list in favour of message previews.

**Comment by arthurlogilab** [comment]
@turt2live good news, in which version has this change been shipped (sorry for the duplicate)

**Comment by turt2live** [comment]
With the rebrand, which was 1.7.0 I think.

**Comment by arthurlogilab** [comment]
We're running 1.7.5 (and tested 1.7.7 through desktop) can't see the change you're referring to, should I open a new issue ?
