### ISSUE TITLE
[UX][labs] with feature_custom_status some of our users are confused as to if they are setting the status for a room, or global

### ISSUE THREAD

**Issue by arthurzenika** [vector-im/element-web#15156]
### Description

When setting a custom status, one has to click on the icon that is next to "Send message" 

![Screenshot from 2020-09-11 15-21-22](https://user-images.githubusercontent.com/445200/92930565-84b9a800-f442-11ea-8ad7-26e74f600bf2.png)

This has led to users asking "am I setting the status for the room I'm in at that point, or for all rooms and users?" 

For context, these users come from a jabber/xmpp culture (for example in pidgin client, you had some custom status to choose from). 

### Suggestion

Not a UX designer but maybe if the status setting with on the left user icon this confusion would not appear. 

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: private server Element version: 1.7.4

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
