### ISSUE TITLE
[labs] feature_custom_status can be unreliable, old status still appears

### ISSUE THREAD

**Issue by arthurlogilab** [vector-im/element-web#15155]
### Description

We use feature_custom_status (yeah congrats on pushing this feature forward!) for status updates such as "in a meeting" or "on lunch break" or "Location" (see screenshots in https://github.com/vector-im/element-web/issues/15154 ) But sometimes a colleague  which is clearly not on her lunch break still shows as "on lunch break" eventhough she has changed her status to "working".

### Steps to reproduce

- Two users
- One user sets his status to "on break"
- The other user confirms it sees "on break"
- The first user switches back to "working" 
- The other user (sometimes) doesn't see "working", but still "on break"

Would be happy to help debug this, but I don't know where to start. 

### Version information

- **Platform**: both

For the web app:

- **Browser**: Firefox
- **OS**:  Ubuntu, Debian
- **URL**: private server Element version: 1.7.4

**Comment by turt2live** [comment]
This is an artifact of how the custom status feature works. Unfortunately, it's not in a state where it can be maintained. Adjusting the rate limit on the server often helps.

**Comment by arthurlogilab** [comment]
@turt2live Where is appropriate place to discuss and give feed back on labs features ? Can you be more specific on the "rate limit on server"  ? Where can we change this setting ?
