### ISSUE TITLE
Spanish update.

### ISSUE THREAD

**Issue by discapacidad5** [vector-im/element-web#15165]
Hello, I just translated element-web Spanish in its entirety. I would like to see soon the update registered.

**Comment by jryans** [comment]
Thanks for working on translations! 😄 I believe that may have already been merged in https://github.com/matrix-org/matrix-react-sdk/pull/5183/files#diff-69402b7961895490501f7ceaf9e8c331?

We typically pull in updated translations at least once per release cycle (every two weeks). The merged changes above are live on develop.element.io and will be included in the next release going out today.

**Comment by discapacidad5** [comment]
I am checking the translation and I see that these buttons do not know translated.

[url=https://ibb.co/tbCpbZJ][img]https://i.ibb.co/hK8FKXm/Captura.png[/img][/url]
