### ISSUE TITLE
Hook up Electron's crash reporter to something

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15162]
It's incredibly useful in diagnosing crashes

**Comment by jryans** [comment]
Yes, seems like a good thing to do, assuming we can keep privacy in mind and ensure people agree to have them sent etc.

**Comment by jryans** [comment]
@turt2live Is there a larger context that caused you to file this?

**Comment by turt2live** [comment]
yea, debugging an internal issue was only possible by hooking up a local crash reporter. Generally it'd be good to get this sort of thing hooked up somehow (maybe similar to firefox's "it crashed! Help us out by sending logs" dialog?) for all the times someone reports seeing a blank screen instead of a chat window.
