### ISSUE TITLE
Application locks up after large amount of text placed in "send an encrypted message" box. Does not go away after reboot or reinstallation.

### ISSUE THREAD

**Issue by vonbraun1969** [vector-im/element-web#15161]
### Description

With a large amount of unicode data in the message box, the program starts to hang and I was unable to delete the data I accidentally put in the message box.

While attempting to paste an image into the chat to send it to all members of the room, accidentally copied the contents of the png file rather than the file itself, and hit ctrl+v in the message box.

This resulted in a several minute long hang of the software wherein I was unable to kill it.

After it stops being frozen, can see this in the message window, typical for what happens if you tried to view such a binary file in a text editor.

![2020-09-12-132139_741x148_scrot](https://user-images.githubusercontent.com/59466379/93004445-8a90b580-f536-11ea-9d3f-51bb63b60f51.png)

Attempted to delete this by hitting ctrl+a and then delete, but command did not go through or it did not interpret the inputs at all.

Rebooted software. Item remained in the box, and was unable to delete it.
Rebooted computer. Item remained in the box, and was unable to delete it.
Unistalled element rebooted computer, and reinstalled element. Item remained in the box, and was unable to delete it.

### Steps to reproduce

in a bash running terminal, run
 ```
xclip -i filename.png 
```
in order to grab the contents of any png file into the system clipboard

click into the message window in element and hit ctrl+v

I am uncertain if this would happen with any large amount of text.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:
Running Manjaro Linux 20.1

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
This is a browser problem - on both Chrome and Firefox over 70 seconds of the time is spent rendering the text whereas only 100-200ms is spent actually handling the text. The same happens with a normal text field.
