### ISSUE TITLE
Micro copy & Explore interaction doesn't scale down well to collapsed room list state

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#15166]
<img width="100" alt="Screenshot 2020-09-14 at 11 36 16" src="https://user-images.githubusercontent.com/4626865/93076024-9c7d7000-f67e-11ea-81a5-ed719ed8e7c2.png">

**Comment by t3chguy** [comment]
The bug here surely is collapsing should clear the filter as you cannot filter whilst it is collapsed.

**Comment by nadonomy** [comment]
Great point— sounds good to me to just hide it when the room list is collapsed.

**Comment by t3chguy** [comment]
Hide it or undo your filtering? It would be very confusing to still be filtering once the Filter field is hidden away

**Comment by nadonomy** [comment]
> Hide it or undo your filtering? It would be very confusing to still be filtering once the Filter field is hidden away

I've been dogfooding the behaviour on production throughout today before replying, where the filtering persists and you can click filter to re-expand, and it doesn't feel broken in practise. Afaik we haven't received (m)any complaints from users either. 

I'm cautious about the alternative of clearing the filter being unexpected usability wise, so think for this issue we should hide the micro copy when collapsed, and consider exposing an explore interaction if we can without usability suffering.
