### ISSUE TITLE
newly installed element desktop insists on dark theme, even when switching to light

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#15167]
having just installed element web, it switched to the dark theme after logging in and verifying. I went to the settings to try and set it to light, which didn't change anything. Checking and unchecking match system theme didn't do anything either. I have not activated dark theme system-wide AFAIK

**Comment by bwindels** [comment]
Closing and opening element desktop fixed the issue.

**Comment by turt2live** [comment]
@bwindels did you previously select the dark theme at an account level before we made changes to the theme behaviour (roughly around the rebrand)?

**Comment by t3chguy** [comment]
Closing due to lack of response
