### ISSUE TITLE
Indexing errors show up as indexing not supported

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15168]
We should refine our error handling for event indexing. At the moment, if you have [some error](https://github.com/vector-im/element-web/issues/15120#issuecomment-691990391) such as:

```
EventIndex: Error initializing the event index {"message":"Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: \"Invalid MAC\" } }))"}
```

the Settings UI manifests this as if you are on web / a platform that does not support indexing at all:

![](https://user-images.githubusercontent.com/38109047/92488742-54190a80-f1c5-11ea-903e-3375230ca479.png)

At the very least, Settings UI should reflect that indexing is supported on your platform, but some error has occurred. Even better would be highlighting the error details as well.

**Comment by thomasfrobieter** [comment]
I still get:

> Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: "Invalid MAC" } }))

In Element Desktop (Win 10):
Version von Element: 1.10.1
Version von Olm: 3.2.8
