### ISSUE TITLE
UI Feature Flag: No more advanced settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15179]
* [x] Hide "Advanced" in room/user settings
* [x] Hide advanced settings under user security
* [x] Fix copy in user preferences: rename to General
* [x] Move "show avatars in user and room mentions" to timeline section

This should be done with a UIFeature flag

**Comment by t3chguy** [comment]
>  Hide "Advanced" in room/user settings

Which one in user settings?
