### ISSUE TITLE
UI Feature Flag: Disable VoIP

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15175]
* [ ] Not Jitsi
* [x] Hide call buttons in composer row
* [x] Hide options in user settings
* [x] Ignore inbound 1:1 calls (non-jitsi)

This should be done with a UIFeature flag

**Comment by t3chguy** [comment]
> Not Jitsi

What does that mean?

**Comment by turt2live** [comment]
Widgets and widgets functionality are left alone, with the exception of the call buttons.
