### ISSUE TITLE
Disable rageshakes if the report URL is empty

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15172]
null/not present is common in use cases, so only disable the thing if it's empty (a more intentional action).

**Comment by jryans** [comment]
If it's null / not present but still displayed, doesn't that mean it will error on use? If so, maybe it's better to not show it for that case as well?

**Comment by turt2live** [comment]
We apply defaults in those cases currently

**Comment by jryans** [comment]
Hmm, are you sure? We seem to [default it to... `null`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/SdkConfig.ts#L30).

The UI is still accessible, but fails with an error when you attempt to submit:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/279572/93214848-97432280-f75d-11ea-946c-a2ccd00e4019.png">

**Comment by turt2live** [comment]
I swear we were, but @t3chguy's PRs prove otherwise :D
