### ISSUE TITLE
"Bridges" in room settings crashes

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#15170]
### Description

When opening the "Bridges" tab (labs setting) in the room settings, it crashes with: "Uncaught TypeError: Cannot read property 'values' of undefined"

Will submit logs.

### Steps to reproduce

- Go to a room, with or without a bridge
- Open settings
- Click on "Bridges"

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 2020091401

**Comment by t3chguy** [comment]
Works fine here on 2020091401

![image](https://user-images.githubusercontent.com/2403652/93099903-77015e00-f6a0-11ea-80da-1195fbd04344.png)
