### ISSUE TITLE
UI Feature Flag: 3PID contact information (HS 3pids)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15187]
* [x] Only support logging in with a username
* [x] Hide 3PID sections (non-discovery - that's the ID server)
* [ ] Hide explanatory copy for 3PIDs

The first should be possible through auth flows. The second and third should be possible via a UIFeature flag. Ideally this would be matched with a server-side flag, however this particular issue is hard to detect server-side and thus we're going with client config for now (to match whatever server-side config is available).

**Comment by t3chguy** [comment]
>  Only support logging in with a username

`disable_3pid_login`
