### ISSUE TITLE
Seshat disablement in web/clarified documentation flags

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15184]
Proposal is to use a new config option to repoint the download URL, however this feels a bit awkward so might have to reconsider. The issue title is somewhat reflective of this undecidedness. 

**See comments before tackling**. This is mostly a judgement call on whether or not to use a UIFeature flag or instead support a download URL.

**Comment by jryans** [comment]
An additional thought behind making the download URL configurable is that some group may want to rebrand Element Web and also offer rebranded Element Desktops to match... Of course, if they are doing that, it's perhaps likely they are also customising the source for other reasons as well.

**Comment by turt2live** [comment]
tbh if they're running a customized version like that then I think they can modify the source. Making it easier for people to get unofficial builds doesn't seem like it's the best idea for us.

**Comment by lampholder** [comment]
If we're [modifying the file panel to drive users to the desktop app](https://github.com/vector-im/element-web/issues/12896), too, then we should extend whatever we impl for this issue to do the same thing to the file panel copy.
