### ISSUE TITLE
UI Feature Flag: Account management

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15188]
* [x] Remove/redirect 'Register' to somewhere else
* [x] Remove/redirect logged-out password reset to somewhere else
* [x] Remove/redirect deactivate account to somewhere else

This should be done by a UIFeature flag.

**Comment by antonbrall** [comment]
Thanks for adding these.
Could you give me a hint where I can set these? I don't seem to be able to find the right block and/or syntax in the config to set these.

**Comment by hex-m** [comment]
You can add the settings in the `settingsDefault` section where the [sample config](https://github.com/vector-im/element-web/blob/develop/config.sample.json) lists `breadcrumbs`. e.g.
```
    "settingDefaults": {
        "breadcrumbs": false,
        "UIFeature.deactivate": false,
        "UIFeature.registration": false,
        "UIFeature.passwordReset": false
    },
```
More explanations of the settings are in the [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md#ui-features).

**Comment by devopsy-ir** [comment]
> You can add the settings in the `settingsDefault` section where the [sample config](https://github.com/vector-im/element-web/blob/develop/config.sample.json) lists `breadcrumbs`. e.g.
> 
> ```
>     "settingDefaults": {
>         "breadcrumbs": false,
>         "UIFeature.deactivate": false,
>         "UIFeature.registration": false,
>         "UIFeature.passwordReset": false
>     },
> ```
> 
> More explanations of the settings are in the [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md#ui-features).

Excellent! Working for me. Thanks a lot
