### ISSUE TITLE
CoinJoin Integration

### ISSUE THREAD

**Issue by zero77** [vector-im/element-web#15193]
**Is your suggestion related to a problem? Please describe.**
limited privacy for transaction when there are options available.

**Describe the solution you'd like**
Could you consider adding support for CoinJoin.

CoinJoin is a special kind of bitcoin transaction where multiple people or entities cooperate to create a single transaction involving all their inputs

**Describe alternatives you've considered**

**Additional context**
https://en.bitcoin.it/Privacy#CoinJoin

**Comment by jryans** [comment]
I must admit I don't really follow how this relates to Element or even Matrix at all... If there is some connection, I would guess it belongs at the [Matrix spec level](https://github.com/matrix-org/matrix-doc), rather than over here in Element.
