### ISSUE TITLE
Confusing screen when skipping secure backup configuration during account registration

### ISSUE THREAD

**Issue by cloudrac3r** [vector-im/element-web#15191]
### Steps to see this screen

When registering an account, the person is asked whether they would like to enable secure backup. They can choose to generate a recovery key or to pick a passphrase, but they can also skip this and not configure secure backup at all. If they choose to skip, this confirmation screen is then displayed:

![Screenshot_2020-09-15_17-55-38](https://user-images.githubusercontent.com/28467304/93172058-42fc6a80-f77e-11ea-93a7-13211f354e5c.png)

### Problems with this screen

This screen is very confusing. The options are "cancel" and "go back", which are almost synonyms. It is not clear what each button will do when pressed, yet both sound dangerous. I do not expect anyone to be confident that they understand this screen.

### An idea for this screen

I suggest changing the screen to read something like this:

> **Skip secure backup?**
> 
> If you skip secure backup, you may lose the content of your encrypted messages when you log out.
> 
> You will still be able to set up secure backup later in Settings.
>
> [ Button: "I changed my mind, set up secure backup now" ]
>
> [ Button: "Skip setting up secure backup" ]

This explains the problem better and makes it very clear what each button will do.

### Version information

Firefox accessing the website app.element.io which is currently version 1.7.7.

**Comment by jryans** [comment]
Thanks for the feedback, agreed this could use some improvement.

**Comment by cloudrac3r** [comment]
I found a similarly confusing screen when selecting to upgrade the encryption session after logging in, but then clicking cancel when asked for the secure backup passphrase.

![image](https://user-images.githubusercontent.com/28467304/93431513-55aaa700-f918-11ea-9e98-d252a6614df8.png)

**Comment by kittykat** [comment]
I'm going to close this issue for now as the UI has changed significantly in the latest redesign. If you feel that there are further improvements to be made, please open a new issue :+1:
