### ISSUE TITLE
[labs] feature_custom_status - using it re-orders the contact list

### ISSUE THREAD

**Issue by arthurzenika** [vector-im/element-web#15194]
### Description

When setting a custom status 

![Screenshot from 2020-09-11 15-21-22](https://user-images.githubusercontent.com/445200/93197986-a79ed180-f74c-11ea-9b58-5c3337bd84e6.png)

the list of People (on the right) changes order. 

### Steps to reproduce

- Activate in Labs the custom_status feature
- change your status
- see the list of people where you have your most recent contacts changed

We had a similar issue (if not exactly the same) when changing the name of a user in the settings. 

### Version information

- **Platform**: both web and desktop

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu/Debian
- **URL**: private server, Element version: 1.7.4

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
