### ISSUE TITLE
clicking on a pinned app in the rightpanel index page unexpectedly unpins it

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15195]
<img width="372" alt="Screenshot 2020-09-15 at 11 13 44" src="https://user-images.githubusercontent.com/1294269/93198196-93ef6d00-f744-11ea-97a0-7186b3ac03d0.png">

It's very surprising that clicking on the "Custom" widget here acts to unpin it from the room and move it into the RightPanel.  I'd expect instead to be taken to the pinned widget (expanding it if it were collapsed).  Unpinning should surely be a separate operation.

**Comment by t3chguy** [comment]
It does say unpin in the tooltip, its because the behaviour of showing a Widget in two places is poor. Joining a Jitsi conference twice for example.

**Comment by toger5** [comment]
This is fixed nowadays:
![image](https://user-images.githubusercontent.com/16718859/147575400-81ef4e5e-c4cd-4f18-a6f6-9b6c41f9a653.png)
