### ISSUE TITLE
In-app search completely ignores urls or nicknames

### ISSUE THREAD

**Issue by Porkepix** [vector-im/element-web#15197]
### Description

The search in the application should also try to match message's author, or urls within messages.

### Steps to reproduce

- Try to search for a past message either by the name of the person who wrote it, or by an url contained within the message.
- See that it finds nothing
- Try with words of the message: it does find it

Describe how what happens differs from what you expected.

The search should consider message's author or urls, but it isn't.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.4

**Comment by t3chguy** [comment]
The search is server-side, See issues like https://github.com/matrix-org/synapse/issues/3024
