### ISSUE TITLE
Room search shows predecessor rooms

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15203]
![image](https://user-images.githubusercontent.com/1342360/93232658-0fb3de80-f772-11ea-8d51-aafc0349bd64.png)

Room search seems to surface rooms that have been upgraded. This confused me as a user, as I didn't really know which room was the latest iteration.

Ideally one would access predecessor rooms via the latest room's room settings, rather than through search or another method. 

### Steps to reproduce

- Create a room
- Upgrade the room
- Put in a search term that matches both room names
- See both rooms instead of just the latest iteration

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Linux
- **Version**: 1.7.7

**Comment by turt2live** [comment]
@anoadragon453 does a clear cache and reload fix it?

**Comment by anoadragon453** [comment]
@turt2live It seems to be, yes.

**Comment by turt2live** [comment]
It's a server issue then :D

**Comment by turt2live** [comment]
(likely a form of state reset or other condition which causes the bidirectional link to go missing)

**Comment by anoadragon453** [comment]
@turt2live Ah, you know I think these rooms were upgraded the "manual and hacky" way. So there's no predecessor linkage from the new room.

**Comment by anoadragon453** [comment]
I'll just leave the rooms then.
