### ISSUE TITLE
Widget credentials request would require some cleaning

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#15208]
![image](https://user-images.githubusercontent.com/1174866/93316790-527ac280-f815-11ea-927b-e5129f89c23a.png)

The OpenID token credentials request (as per MSC1960) from a widget breaks with a widget URL like above.

Possibly would be nice to clean the widget URL a bit. Based on the widget spec, possibly any of the [mentioned](https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit#) `$` parameters could be cleaned out. In the above example, the credential request container would still break however, so maybe the simplest solution would be to just hide it X characters after the first URL parameter with a "click to show" action if the user wants to see the full URL?

### Version information

- **Platform**: desktop

- **OS**: Ubuntu
- **Version**: 2020091601

**Comment by turt2live** [comment]
this will get implicitly fixed with https://github.com/vector-im/element-web/issues/13111 though we might want to send the dialog through a designer.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/commit/997679e648eb99f9064009b8e472e01946a5c1d4
