### ISSUE TITLE
Can't become admin even if there's none in a room

### ISSUE THREAD

**Issue by Destroyer** [vector-im/element-web#15209]
I have a room in which I am a single user (admin left) and yet I can't gain admin level via Riot-web GUI (as far as I can see). Is there any other way to do so?

**Comment by t3chguy** [comment]
Nope, Matrix being a federated consensus-based protocol does not have that feature.
Only Admins can promote other Admins.
Use http://matrix.to/#/#matrix:matrix.org for future support queries.
