### ISSUE TITLE
Roomlist icons needlessly reloaded when roomlist size changed

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#15216]
### Description

When the roomlist is re-sized (mini version to larger version) all the icons are reloaded needlessly, as they do not seem to actually change size or anything of the sort. 

### Steps to reproduce

- Open dev tools (some icon requests should already appear as the window is re-sized)
- Change the roomlist size a few times
- Many icon requests should have now been made and logged

The icons should not be reloaded except possibly if they are actually resized.

### Version information

- **Platform**: Desktop
- **OS**: Linux (openSUSE)
- **Version**: 1.7.7

**Comment by turt2live** [comment]
do you have the "disable cache" checkbox on?

**Comment by TR-SLimey** [comment]
Well that's awkward. Yes... Yes I do :P

**Comment by turt2live** [comment]
at least it's an easy fix :)
