### ISSUE TITLE
Files in encrypted rooms do not download in Firefox

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15210]
Clicking the timeline link to decrypt a file in Firefox does not download it. Manually clicking the transformed download link also does not work. However, you manually copy the download link (`blob:` URL) and open it in a new tab, it saves successfully.

Desktop and web via Chrome are not affected.

**Comment by t3chguy** [comment]
Hmm, we do specify sandbox flags `allow-downloads allow-downloads-without-user-activation` for that iframe, will do a quick little bit of digging

**Comment by t3chguy** [comment]
Cannot reproduce with Firefox 80.0.1 (64-bit) on macOS on develop.element.io

Worked for both images and zip files.
This is a pretty bare FF, with just React Devtools installed, maybe try with your add-ons disabled.

**Comment by jryans** [comment]
Hmm, okay, it does seem to work in Firefox Release (80) but not in Nightly (82). I'll try to work out if it's already filed upstream with Mozilla.

**Comment by jryans** [comment]
It seems related to the sandbox flag `allow-downloads` which Firefox recently [implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1558394) and [enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1656212) in 82.

There appears to be some bug or difference in behaviour from Chrome's implementation of this. With Firefox 82, I only seem to get working downloads by disabling sandboxing or adding `allow-same-origin` to the sandbox flags (which effectively disables the sandboxing anyway), so I'll try to raise this on the Firefox side to see if can be fixed.

**Comment by jryans** [comment]
After further investigation, it's actually not related to the sandbox flag `allow-downloads`, that was just a likely suspect that happened to be enabled around the same time.

Instead, the cause is [recent work](https://bugzilla.mozilla.org/show_bug.cgi?id=1658878) to isolate blob URLs by [agent cluster](https://html.spec.whatwg.org/multipage/webappapis.html#similar-origin-window-agent) (roughly meaning similar origins). It's currently unclear to me if this work purposefully breaks blob URLs in sandboxed iframes. I have filed [an upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1667348) for analysis.

At the moment, this privacy feature is Nightly only and is not proceeding to further release channels yet. For anyone using Firefox Nightly who would like to disable this privacy feature for the moment so that encrypted file downloads work again, you can set the pref `privacy.partition.bloburl_per_agent_cluster` to false.

**Comment by thomaswucher** [comment]
Just discovered an easy workaround for this issue: Right click the download link, click "Save link as...". This will download the file with the correct filename without an issue.

**Comment by heftig** [comment]
This has started affecting unencrypted rooms as well. Disabling `privacy.partition.bloburl_per_agent_cluster` is still a workaround.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/18315

**Comment by jryans** [comment]
As of Firefox 93 (via https://bugzilla.mozilla.org/show_bug.cgi?id=1728192), the problematic Firefox feature is no longer enabled by default, so I guess we can call this fixed for now (may change if they try to enable it again later).
