### ISSUE TITLE
Show fewer (rooms), not less.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15220]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1922197/93390094-10796d00-f865-11ea-89a4-bae82ecb0769.png">

The implied 'Room' is a countable noun; the full sentence would read "Show fewer rooms" so the fragment should read "Show fewer"

**Comment by t3chguy** [comment]
This was done on purpose to match the likes of Apple

**Comment by turt2live** [comment]
Fewer is incorrect. We've recorded this decision somewhere public, but of course the keywords are awful.

**Comment by t3chguy** [comment]
The gist of it was to read https://www.reddit.com/r/iphone/comments/apbjkn/just_noticed_this_grammar_mistake_pretty_sure_it/
