### ISSUE TITLE
Remove / rewrite message key warning on password change

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15226]
Now that key backup exists, we should remove / rewrite this dialog shown on password change:

![Screen Shot 2020-09-17 at 5 28 52 PM](https://user-images.githubusercontent.com/279572/93501590-905b1200-f90d-11ea-86a1-fd3c169b87e4.png)

**Comment by 2580ayush2580** [comment]
shall I work on this?
can you explain what solution would you like?

**Comment by unyin** [comment]
tested as part of community testing session today; message on password change is still the same as it was as of 17/09/20 when ticket was opened. 

What should the new message be? Should it also include an option to activate key backup if it isn't already active?

**Comment by Palid** [comment]
@unyin moved it to design

**Comment by t3chguy** [comment]
This got fixed
