### ISSUE TITLE
screen flashing while scrolling on Macbook pro

### ISSUE THREAD

**Issue by wsmwk** [vector-im/element-web#15223]
Version 1.7.7 (1.7.7) on Macbook Pro element native app

Frequently, but not always, scrolling causes flicker. maybe 20% of the time?  

Both light and dark theme but more noticeable with dark, and I use dark normally.

Can't say I have identified unique steps to reproduce

**Comment by ara4n** [comment]
can you describe the flicker?

**Comment by ara4n** [comment]
or even better, take a (slow mo?) video of it?

**Comment by wsmwk** [comment]
I haven't seen this in a while.
