### ISSUE TITLE
can not integrate integration server

### ISSUE THREAD

**Issue by ralfi** [vector-im/element-web#15224]
### Description

v1.7.5 last time inbound integrations manager works 
ex. dimension.t2bot.io or selfhosted based from t2bot.io docker image

### Steps to reproduce

- use 1.7.5, enable integrations, config and check if rss feeds works
- update to 1.7.6 or 1.7.7
- integration dos not appears or is usable 

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 85,86; FF 80

**Comment by ralfi** [comment]
![image](https://user-images.githubusercontent.com/294423/93474706-03598e00-f8f8-11ea-9da5-64aeb7bcb1a8.png)

integrations in menu bar, does not appear in 1.7.6 or 1.7.7

**Comment by t3chguy** [comment]
Yup. It is in Right Panel now. under the `i` - `Add apps, bridges & bots`

**Comment by ralfi** [comment]
Yeah, you are right, all fine ...
