### ISSUE TITLE
default_server_name config option deprecation notification

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#15222]
### Description

In the Web Console i read the following warning:

`DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.`

But the [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md) does not mention anything in that regard.

I think it's the more elegant option to let clients fetch the config-details from the `.well-known` URL. But if it is really going to be deprecated it should be mentioned in the documentation.

### Version information

- **Browser**: Firefox 68 ESR 
- **OS**: Debian
- **URL**: private server hosting Element 1.7.7

**Comment by jryans** [comment]
> But the [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md) does not mention anything in that regard.

It does though, even if it's not really organised for easy reading, it says:

> Alternatively, the config can contain a `default_server_name` instead which is where Element will go to get that same object, although this option is deprecated

> I think it's the more elegant option to let clients fetch the config-details from the `.well-known` URL. But if it is really going to be deprecated it should be mentioned in the documentation.

While I can understand the appeal of this for some deployments, many Element settings are not specific to single homeserver. Even in the case where they are meant to be used with a single homeserver, sometimes HS admins aren't able to set up a `.well-known` file.

I think it would be good to file a new issue with more context on your specific use case to help us understand why you'd prefer to have config coming from the HS.

**Comment by hex-m** [comment]
As it really is deprecated and thus discouraged, it should also be removed from the [good example config](https://develop.element.io/config.json) linked in the documentation.
