### ISSUE TITLE
Official docker image for ARM

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#15227]
**Is your suggestion related to a problem? Please describe.**
I noticed that the only official Docker image available for Element Web is for amd64. This is unfortunate as I'm looking at moving my homeserver and web client to an ARM-based machine.

**Describe the solution you'd like**
Since the Docker build for ARM is apparently working now ( see #14522 ), maybe we can get an official ARM image too?

**Describe alternatives you've considered**
I guess I could use one of the [unofficial Docker images supporting ARM](https://hub.docker.com/search?q=riot-web&type=image&architecture=arm%2Carm64) but considering how secure Matrix is supposed to be, I don't think using some random untrusted client with it is the way to go here.

Also, while unrelated, I'm not sure if this warrants a separate issue, so I'll ask here; are there any plans to rename the Docker image to element-web over riot-web? Perhaps leave riot-web unmaintained and create a new repo for element-web?

**Comment by jryans** [comment]
> lso, while unrelated, I'm not sure if this warrants a separate issue, so I'll ask here; are there any plans to rename the Docker image to element-web over riot-web? Perhaps leave riot-web unmaintained and create a new repo for element-web?

Yes, it's planned but low priority at the moment: https://github.com/vector-im/element-web/issues/14930

**Comment by TR-SLimey** [comment]
Thanks for the reply. That's good to hear. Any plans to create an ARM version also or is that not planned yet?

**Comment by mattcen** [comment]
I've been trying to get a reliable Docker image built for arm/v7 and/or arm64 for a few months now. I thought I'd sorted this with #14522, but a recent build has given additional grief:

```
#13 425.8 <s> [webpack.Progress] 92% additional asset processing
#13 425.8 <s> [webpack.Progress] 92% chunk asset optimization
#13 425.8 <s> [webpack.Progress] 92% chunk asset optimization TerserPlugin
#13 477.3 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#13 484.4 Segmentation fault (core dumped)
#13 484.5 error Command failed with exit code 139.
#13 484.5 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#13 484.6 error Command failed with exit code 139.
#13 484.6 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#13 ERROR: executor failed running [/bin/sh -c yarn build]: buildkit-runc did not terminate successfully
------
 > [builder 7/9] RUN yarn build:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn build]: buildkit-runc did not terminate successfully
##[error]Process completed with exit code 1.
```
(Full transcript at https://github.com/mattcen/riot-web/runs/1141554281?check_suite_focus=true#step:5:4508).

My *suspicion* was that yet again, `yarn build` is running out of memory. The error I'm getting seems consistent with https://github.com/terser/terser/issues/164 and https://github.com/webpack-contrib/terser-webpack-plugin/issues/143.

Most workarounds suggest adding `--max-old-space-size=8192` (or some large amount of MiB) to the node options, but not being a regular node user, I'm not sure whether this can be added to `yarn build`; when I tried this it didn't seem to help, and I'm not sure where else to add it. I also tried setting `ENV NODE_OPTIONS --max-old-space-size=8192` in the Dockerfile, but that also didn't seem to help. I'm still poking at it.

Anyway, if anybody knows how to implement this workaround, that'd get us closer to a reliable Docker build, and I've already got a GitHub action set up to do multi-arch builds, as linked to above for the transcript; I'm not sure how Element's Docker images are currently built; I suspect via Docker Hub automated builds, which don't support multi-arch building currently.

**Comment by ja2142** [comment]
It seems that I've run into the same, or very similar problem as @mattcen, when building docker image on arm64. For me the build also breaks on TerserPlugin, but it's js that reports lack of memory, here are relevant lines of output:

```
<s> [webpack.Progress] 91% recording
<s> [webpack.Progress] 92% additional asset processing
<s> [webpack.Progress] 92% additional asset processing PersistentChildCompilerSingletonPlugin
<s> [webpack.Progress] 92% chunk asset optimization
<s> [webpack.Progress] 92% chunk asset optimization TerserPlugin

<--- Last few GCs --->

[145:0x3fe4e820]   162958 ms: Scavenge 771.5 (824.0) -> 772.4 (824.0) MB, 26.8 / 0.0 ms  (average mu = 0.785, current mu = 0.735) allocation failure 
[145:0x3fe4e820]   162983 ms: Scavenge 772.5 (824.0) -> 771.5 (824.0) MB, 24.1 / 0.0 ms  (average mu = 0.785, current mu = 0.735) allocation failure 
[145:0x3fe4e820]   164017 ms: Scavenge 774.8 (825.5) -> 771.6 (824.0) MB, 2.0 / 0.0 ms  (average mu = 0.785, current mu = 0.735) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa18da8 node::Abort() [/usr/local/bin/node]
 2: 0x969880 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb74138 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb742c4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xd1c820 v8::internal::Heap::EnsureFromSpaceIsCommitted() [/usr/local/bin/node]
 6: 0xd4a278 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 7: 0xd55094 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
 8: 0xd42e20 v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
 9: 0xd430b8 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
10: 0xd36758 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
11: 0xd56b40 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
12: 0xd572b8 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
13: 0xd5744c v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
14: 0xd681c0 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
15: 0xd29fa4 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
16: 0xd2b520 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
17: 0xd2e41c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
18: 0xcf73c8 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
19: 0xcf0f40 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/usr/local/bin/node]
20: 0xcf3318 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
21: 0x10aac30 v8::internal::IncrementalStringBuilder::Extend() [/usr/local/bin/node]
22: 0xe0957c v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
23: 0xe09368 v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
24: 0xe0eaa4 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
25: 0xe0f68c v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
26: 0xe0f68c v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
27: 0xe1097c v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
28: 0xc18b90 v8::internal::Builtin_JsonStringify(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
29: 0x137bbcc  [/usr/local/bin/node]


Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 134
```

I've been able to build the image by adding `--max_old_space_size` to the `build:bundle` script in package.json, I've replaced
```
"build:bundle": "webpack --progress --bail --mode production"
```
with
```
"build:bundle": "node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --progress --bail --mode production"
```
and build finished without errors.

**Comment by samyak-jain** [comment]
Are there any plans to publish an ARM image on the official DockerHub? Changing CI to build a multi-arch image should be a pretty low hanging fuit. I am willing to work on this if that help move the needle.

**Comment by mattcen** [comment]
@samyak-jain the biggest challenge to using CI to build the ARM image is that the CI infrastructure needs enough memory to do its WebPack. Everytime I tried to do this via CI, it would spend an hour trying to build everything and then fail when yarn got OOM killed at the WebPack stage. I had to resort to building on my Raspberry Pi 4 8GB, and even then, if too much is running, I need to free up some RAM to finish the build.

I would like to hope if you could work out how to reduce the time and memory requirements for the build, that is would pave the way for CI building but I suspect unless that happens, it might be deemed too high a cost.

**Comment by aaronraimist** [comment]
@mattcen see https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1357 for the solution matrix-docker-ansible-deploy implemented. There was an attempt to upstream it but it was rejected probably just due to a misunderstanding.

**Comment by samyak-jain** [comment]
@mattcen Isn't there already CI for the current images for x86? How are the current docker images published? Or does building for ARM take significantly more resources for some reason? Taking what @aaronraimist and @ja2142 said into account, if the OOM issue can be solved for github actions, can we consider this then? I still see the build taking a very long time though. Maybe migrating from webpack to something like esbuild can help?

**Comment by artonge** [comment]
It would indeed be nice to have an official armv7 image. But honestly, I have the feeling the armv7 is being slowly abandoned docker wise. Even the docker images for docker are not built for armv7 anymore :/ https://github.com/docker-library/docker/issues/260

But regarding this issue, for now, I am using some sort of "hack" to build Element images for armv7. I use a two steps build. The first one is based on the official amd64 image so I can simply copy the already built sources into the second step, avoiding the problematic webpack build.

Here is the Dockerfile: https://gitlab.com/flap-box/element/-/blob/flap/Dockerfile.flap

**Comment by erulabs** [comment]
Just a note that ARM64 would go a very long way, and is typically much easier to get working than ARMv7. For whatever it's worth, I built `v1.11.0` for ARM64 at https://hub.docker.com/r/erulabs/element-web (still uploading as of this comment but the build worked fine).

**Comment by t3chguy** [comment]
@erulabs https://github.com/vector-im/element-web/pull/22026 adds ARM64

**Comment by adamcstephens** [comment]
Will the arm64 build automatically push, or is there a manual step to push the docker images?

**Comment by t3chguy** [comment]
It'll automatically push on releases, and develop will push twice a day
