### ISSUE TITLE
Fix Join button from Preview (peeking) view

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#15228]
until peeking over federation works. There must be an issue for this already but I can't find it.

**Comment by t3chguy** [comment]
Hmm, but there is a chance it is still possible to peek that as there may already be a user from your server in that room.
Similarly, a Room Directory may contain a room without any users on that server in that room and it be unpeekable.

**Comment by aaronraimist** [comment]
Yeah I should actually clarify. This issue is coming from `#synapse:matrix.org` where a user thought their server was broken because they couldn't join any rooms. What they were doing was clicking on Preview and then clicking Join.

This doesn't work, I assume because Element is just trying to join using the room ID so Synapse returns the no known servers error. So a better solution might be just to get that join button on the Preview page working. Either by using ?via= or by remembering the alias from the room directory rather than trying to join using the room ID.
