### ISSUE TITLE
Sometimes the 'set up encryption' toast shows up after registering and generating a key

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15239]
I went through all the hard work of copying the recovery key it generated for me, but I still get a 'set up encryption' toast as a welcome.

**Comment by turt2live** [comment]
this doesn't happen all the time

**Comment by jryans** [comment]
I believe this no longer matches the latest flows on develop: we now no longer prompt for passphrases until your first E2EE room. If there are problems with the new flows from develop, please of course file new issues.
