### ISSUE TITLE
yarn start:js exited with code SIGTERM

### ISSUE THREAD

**Issue by ph2k** [vector-im/element-web#15242]
### Description

Trying to build element-web client from source following this [documentation](https://github.com/vector-im/element-web#setting-up-a-dev-environment). It fails on third step (Finally, build and start Element itself) on last command `yarnpkg start`.

### Steps to reproduce

- Install local virtual private server using [debian-10.5.0-amd64-netinst.iso](https://www.debian.org/distrib/netinst).
- Follow this [documentation](https://github.com/vector-im/element-web#setting-up-a-dev-environment).
- Last command (`yarnpkg start`) on third step fails.

The command fails, but it should succeed.

Error code: yarn start:js exited with code SIGTERM (as seen in screenshots)

Sometimes it fails on 69%, sometimes on 94%.

As a last resort, I have tried to run `yarnpkg upgrade` and then repeating the start command, but no luck.

![screenshot](https://user-images.githubusercontent.com/71549289/93664733-691d5580-fa71-11ea-8270-ea0f96b89346.png)

![screenshot2](https://user-images.githubusercontent.com/71549289/93664766-a4b81f80-fa71-11ea-8826-657c3e200103.png)

### Version information
vps cpu: 1
vps ram: 512MB
vps hdd: 8GB

I have enough free space on the vps. I have tried with 768MB, 1024MB and 2048MB of ram. Also have tried with 2 cpus. Nothing changed.

I'm using the latest files from GitHub, downloaded yesterday.

Host os: Debian 10

**Note:** This is possible a yarn bug/conflict.

Just wanted this documented in case someone runs on the same error, because I couldn't find any similar errors in issue list.

### Solution that worked for me
Use releases rather than building from source.

**Comment by t3chguy** [comment]
Please paste the whole log.
Please also make sure you have sufficient fs watchers. See https://github.com/vector-im/element-web#setting-up-a-dev-environment

**Comment by ph2k** [comment]
I have tried with more max_user_watches, what the documentation suggests (131072) and double (262144). Both commands fail. I have tried with 768MB ram, again fail.

[Here is the latest full log.](https://paste.ubuntu.com/p/R6kQ4rnjSc/) It expires in a year.

I found a solution that works for me and that is using your releases.

**Comment by t3chguy** [comment]
Yeah that's not enough RAM, webpack is very RAM heavy: https://github.com/benweet/stackedit/issues/1177

**Comment by ph2k** [comment]
@t3chguy Set max_user_watches to 131072 and increased server ram to 2048MB. Success!

```
2020-09-20 11:46:14.984 [riot-js] <s> [webpack.Progress] 100%
2020-09-20 11:46:14.985 [riot-js] 
2020-09-20 11:46:15.024 [riot-js] ℹ ｢wdm｣:    1591 modules
2020-09-20 11:46:15.025 [riot-js] ℹ ｢wdm｣: Compiled successfully.
```

Problem solved!
