### ISSUE TITLE
Notifications button is in wrong place

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15245]
![kép](https://user-images.githubusercontent.com/26059643/93705955-50fd1300-fb11-11ea-8e4b-6f81f2204b34.png)

The **global** Notifications button is between the Search In **Room** button and the **Room** Preferences button. So users might think it is a room specific thing.
Proposed design: move it to the account-specific left side of the top bar.
[
![notifications-design](https://user-images.githubusercontent.com/26059643/93705983-a0434380-fb11-11ea-83fb-6e2ac2af7b4d.png)
](url)

**Comment by t3chguy** [comment]
Yup. This is planned just needs more work.

**Comment by SimonBrandner** [comment]
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously - see https://github.com/vector-im/element-web/issues/5383. I'm going to close this issue now so we can focus on https://github.com/vector-im/element-web/issues/5383. Please watch, vote or comment on https://github.com/vector-im/element-web/issues/5383 if there is any additional information you can provide.
