### ISSUE TITLE
Cannot send in many groups

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#15240]
With the same account I CAN send from an old Riot instance, but not from Element 1.7.7.  When I try to, I IMMEDIATELY get 'Cannot send message.  Retry/Abort'.  Possibly this only concerns encrypted rooms.  I create this issue in order to link a rageshake.

**Comment by Biep** [comment]
I cannot find a clear rule regarding which rooms can and cannot be written in.  1:1 encrypted mostly fails; unencrypted tends to succeed.

**Comment by turt2live** [comment]
based on the logs, your server is having problems.
