### ISSUE TITLE
Verification fails after entering recovery passphrase

### ISSUE THREAD

**Issue by sphinxc0re** [vector-im/element-web#15249]
### Description

When trying to verify my mobile phone session from Desktop, after entering my passphrase the session seems to be verified on mobile, but canceled on Desktop

### Steps to reproduce

- Start the verification of the mobile phone on Desktop
- choose Emoji verification
- Verify (in my case, they match)
- Both devices tap (or click) "They match"

On Desktop, a password prompt pops up and asks for the recovery passphrase.

- the recovery phrase is typed in (correctly)
- the Desktop shows "you canceled the verification"
- mobile phone shows "verification successful"

### Version information

- **OS**: macOS, Manjaro (Problem on both systems)
- **Version**: 1.7.7

**Comment by jryans** [comment]
@sphinxc0re Thanks for reporting. From the debug logs, it seems as if the cross-signing private keys in secret storage do not match the public keys. It also seems like the mobile device did not sign itself when creating the cross-signing keys originally.

To resolve this inconsistency, I would recommend resetting cross-signing keys. I believe the reset function only exists on web currently, in Settings -> Security -> Cross-signing section.

In case of any further trouble with verification, it would be even better to have debug logs for the mobile side as well.

**Comment by sphinxc0re** [comment]
Resetting cross signing also fails, sadly. And I already (in my despair) tried deleting the key backup and now it can't recreate it either 🙈

**Comment by jryans** [comment]
@sphinxc0re Hmm, could you try going to the develop version at https://develop.element.io and resetting cross-signing keys again? There have been some recent changes in this area. If it still fails, please submit more debug logs from that session on develop, and we'll continue the investigation.

**Comment by invertor** [comment]
Thanks @jryans. This is great! I'm having since problem since the releasing of cross-signing!
I can confirm that resetting cross-signing keys solves the issue.

**Comment by sphinxc0re** [comment]
Using develop to reset cross signing solved the problem for me. Thanks! 😁

**Comment by jryans** [comment]
Wonderful, glad to hear that has fixed things for everyone here. 😄
