### ISSUE TITLE
‘Zoomed’ in Firefox on iOS makes UI unusable

### ISSUE THREAD

**Issue by OddHouseGames** [vector-im/element-web#15257]
Using the web based version with iOS 14 set to zoomed mode (accessibility feature) makes the UI unusable. Firefox, iPhone 6S

![image](https://user-images.githubusercontent.com/62911518/93874336-35287700-fca1-11ea-87eb-02833cc765be.jpeg)

**Comment by t3chguy** [comment]
You can disable the left most bar and the read receipt columns in Settings > Preferences to get back some of the space but fundamentally this is why element-ios exists.

**Comment by Githubuxer** [comment]
Thanks, Element on iOS doesn't accept my login and switch's to single sign in mode, then the email verification fails every time.

**Comment by Githubuxer** [comment]
> You can disable the left most bar and the read receipt columns in Settings > Preferences to get back some of the space but fundamentally this is why element-ios exists.

Thanks, Element on iOS doesn't accept my login and switch's to single sign in mode, then the email verification fails every time.

**Comment by jryans** [comment]
Element Web on mobile is currently experimental only, so it's likely we would need some tweaks from the community to improve here.

**Comment by kittykat** [comment]
@OddHouseGames it would be great if you could help improve Element on iOS by [filing the issues you're encountering](https://github.com/vector-im/element-ios/issues)

**Comment by SimonBrandner** [comment]
> @OddHouseGames it would be great if you could help improve Element on iOS by [filing the issues you're encountering](https://github.com/vector-im/element-ios/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

This doesn't seem to be an issue about Element iOS, it seems to be about Element Web on iOS

**Comment by OddHouseGames** [comment]
Apologies all, I've been able to use the iOS app for the last few months due to updates the fixed the login issue, this issue can be closed.
