### ISSUE TITLE
link must be emphasized on mouse over

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15252]
All ways are good: underline, bold...

![image](https://user-images.githubusercontent.com/14617699/93813886-7185b400-fc5c-11ea-93d4-ad04a1558914.png)
What link will be opened by click?

**Comment by t3chguy** [comment]
What apps do that?

**Comment by 532910** [comment]
All good web sites emphasizes links on mouse over.
The screenshot is from latest element and in firefox it looks the same.

**Comment by 532910** [comment]
End even [tilix](https://github.com/gnunn1/tilix) and urxvt underline links.

**Comment by fooness** [comment]
Some links are correctly underlined when hovering or focusing them … and I don’t figure out why others aren’t.

`bundle.css`:
```
.markdown-body a:active, .markdown-body a:focus, .markdown-body a:hover {
  text-decoration: underline;
}
```

But I agree to OP, there should be an indication (underline) when hovering or focusing links. (font-weight variations aren’t a good idea, as also the width is increased and this will cause flickering.)

**Comment by 532910** [comment]
> I don’t figure out why others aren’t.
> ```
> .markdown-body a:active, .markdown-body a:focus, .markdown-body a:hover {
>   text-decoration: underline;
> }
> ```

This is the answer: markdown links are underlined, other --- not.

> font-weight variations aren’t a good idea, as also the width is increased and this will cause flickering.

Agree, but a color change will be fine too. Though markdown links are already underlined, all links must be underlined, as consistent behaviour is a priority.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6513
