### ISSUE TITLE
Show error when displayname cannot be changed

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#15255]
### Description

Element silently fails when I try to change my Display Name but the server does not allow it.

### Steps to reproduce

- set `enable_set_displayname: false` in your Synapse `homeserver.yaml`
- change Display Name in Element
- click "Save"
- close the Settings window
- Display Name is not changed

I would assume that Element gives an indication that the change was not successful (and why). Ideally the text field "Display Name" would be greyed out to indicate it can't be changed.

### Version information

- **Platform**: web (in-browser) and desktop
- **Version**: element-web 1.7.7

Side note: this leads to an additional UX problem where an avatar change is not applied (even though it's allowed on the server) if I also change the Display Name before clicking Save.

**Comment by t3chguy** [comment]
> Ideally the text field "Display Name" would be greyed out to indicate it can't be changed.

Synapse does not indicate this impossibility to the client.

**Comment by Half-Shot** [comment]
Synapse should be raising you a 400 "Changing display name is disabled on this server" when failing to change the display name, so we could show some helpful error text. Sadly, for whatever reason we didn't include this in `/capabilities`
