### ISSUE TITLE
Doesn't work with the new Microsoft Edge

### ISSUE THREAD

**Issue by poqdavid** [vector-im/element-web#15269]
### Description

Well I wanted to use the web client on `Microsoft Edge Version 85.0.564.63 (Official Build) (64-bit)` which its chromium based but it doesn't even give me the login screen

### Steps to reproduce

- Open Microsoft Edge stable
- Try to load https://app.element.io/ with Microsoft Edge

Well I expect to be able to at least login but can't even do that

Logs being sent: no

![msedge_2020-09-24_01-14-10](https://user-images.githubusercontent.com/9592210/94119148-57d2a100-fe03-11ea-8bd4-c4fd5b908d27.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Microsoft Edge Version 85.0.564.63 (Official Build) (64-bit)
- **OS**: Windows Home 64bit
- **URL**: https://app.element.io/

**Comment by t3chguy** [comment]
This is not a supported environment: https://github.com/vector-im/element-web#supported-environments

It works fine here though `Version 85.0.564.51 (Official build) (64-bit)`, it is likely one of your extensions causing this:
![image](https://user-images.githubusercontent.com/2403652/94119627-149a2180-fe47-11ea-9ca1-29c06a26654b.png)
