### ISSUE TITLE
Summary of Room Invite Dialog problems

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15264]
This is a bit of a meta-bug to document things that prevented me from successfully using the room invite dialog whilst testing bridges.

1. Pasting an address in was bringing up this dialog:
    <img width="798" alt="Screenshot 2020-09-08 at 11 18 19" src="https://user-images.githubusercontent.com/986903/94037967-d1e03700-fdbd-11ea-96d0-ef39fe721b6c.png">
    Which is a different dialog to the 'this user might not exist, do you want to try anyway?' dialog which was what I was expecting. This one has no option to invite anyway and both buttons do the same thing (just close the dialog).
2. Pasting an address in tries to interpret the pasted address straight away meaning you can't paste in part of an address and then type the rest
3. The text area is only about 30% of the width of the container box
4. The text box is in fact a text area and so spills onto multiple lines when it reaches the end, so the first part just scrolls out of view

<img width="725" alt="Screenshot 2020-09-08 at 11 27 26" src="https://user-images.githubusercontent.com/986903/94038645-9f830980-fdbe-11ea-8924-2748f3e406e9.png">

**Comment by mrjohnson22** [comment]
A workaround for 1. and 2. is to type any character before pasting an mxid (and deleting it afterwards), or to just type the entire mxid entirely.

**Comment by jryans** [comment]
I believe most of these issues have now been addressed. If any have not, let's re-file them as separate issues.
