### ISSUE TITLE
Support a flag on widgets to automatically pin them to the room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15267]
Widgets are useful for some interactions with bridges, bots, etc where it'd be nice to have the widget pre-pinned so the bot doesn't have to explain where to find the thing

**Comment by Cadair** [comment]
@Half-Shot and I were talking about using a widget in the slack bridge DM room to provide a nice "click this to login to slack" way of authenticating with the bridge, and the openid stuff for widgets would allow you to do this without having to send commands to the bridge bot, but the current widget UX doesn't really make it work.

**Comment by fooness** [comment]
We kinda relied on automatic widget pinning for the start of our semester on November 1st, as this feature was the default for the last months. Is there any way this feature will be (re-)implemented soon-ish? We would be very happy about this, the current state is rather non-ideal.

Thank you very much!

**Comment by t3chguy** [comment]
Shouldn't this be a spec issue?

**Comment by turt2live** [comment]
Element made the UI decision, not the spec. Element then is in a position to solve the problem (if it wants to), which might result in a MSC down the line, however this is largely something that would be client-specific and not part of the spec.

**Comment by t3chguy** [comment]
Good point.

**Comment by fooness** [comment]
Any news on reverting this breaking change? 😔

**Comment by t3chguy** [comment]
How would such a flag work with regards to the pinning limit? E.g what if a user already has two pinned widgets and an admin adds a new widget with this proposed flag, what would happen?

**Comment by turt2live** [comment]
the same thing that happened before: pin it anyways

**Comment by t3chguy** [comment]
With our stricter sizing requirements that simply won't be possible. The resizer will fail to function with >3 pinned due to the complexity of the behavioural requirements.

**Comment by turt2live** [comment]
then don't auto-pin past 3 and leave them unpinned? The problem statement is "I added a widget for the first time, and it's completely missing from my room". Most of the use cases for this will have no more than 1 widget they need to worry about.

Quite frankly, it's extremely irritating that custom widgets don't auto-pin as it prevents the vast majority of use cases for widgets from functioning. Can we please just make `m.custom` auto-pin?

**Comment by t3chguy** [comment]
I believe design wants auto-pinning gone altogether so unlikely

**Comment by turt2live** [comment]
That'll get added to the reasons I can't recommend Element to people, then.

**Comment by fooness** [comment]
Any news on this topic? We’re having an extremely hard time organizing classes in our channels since widgets are treated differently for each and every user. Removing this functionality unfortunately introduced huuuge and basically “deal-breaking” problems for us.

**Comment by lampholder** [comment]
I just wanted to add - this is under active consideration, and the need for auto-pinning is certainly understood (particularly for the education use case).
