### ISSUE TITLE
Unable to set up secret storage.

### ISSUE THREAD

**Issue by PeterBadzhakov** [vector-im/element-web#15278]
### Description

Clicking "Reset cross-signing and secret storage" and generating a new Security Key nets this message. Clicking retry makes it immediately pop up again.
I want to get a new security key to verify all new sessions permanently, since my last key comprises random symbols I don't remember.

### Steps to reproduce

- Enter the Security options menu.
- Click "Reset cross-signing and secret storage".
- Click Generate new Security key.

I expected to receive a new security key, save it in my password manager, be able to verify all sessions from all logins with it and unlock past messages with it.

# Debug logs to be sent momentarily.

### Version information

- **Platform**: element-desktop.

For the desktop app:

- **OS**: Windows 10 Education.
- **Version**: Element version: 1.7.7 , olm version: 3.1.3

**Comment by dbkr** [comment]
Thanks for the additional logs: merging this into the main bug: https://github.com/vector-im/element-web/issues/15230
