### ISSUE TITLE
Bring back the scrollbars on People and Rooms list

### ISSUE THREAD

**Issue by DJViking** [vector-im/element-web#15270]
The People and Rooms list are capped, showing only a few, but can be expanded to show more.

Bring back the scroll bars please. Expanding either list will hide the other. If you have many people and rooms, this makes it difficult to see both lists.

It was better in Riot old UI/UX where each list was shown in the left side separated by the vertical slider, but with a scrollbar inside each list. Then you could scroll through all people, and still see the rooms.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14538

**Comment by DJViking** [comment]
Thanks. I tried to search, but with over 4000 open issues it was not easy.
