### ISSUE TITLE
Markdown inconsistent / not standardized

### ISSUE THREAD

**Issue by Krauus** [vector-im/element-web#15288]
### Description
With manual input, markdown appears as such:

1 `*italic*`
2 `**bold**`
3 `***bold / italic***`
4 `****bold****`

Underscores:

1 `_italic_`
2 `__bold__`
3 `___bold / italic____`
4 `____bold____`

Since using asterisk or underscore makes no difference, why have both?

The WYSIWYG markdown tool auto-chooses:

2 asterisks for bold
1 underscore for italic

Things get weirder for Strikethrough. It uses `<del></del>` (HTML markup), but the client does not accept `<i></i>` for italics or `<b></b>` for bold. Totally inconsistent!

Perhaps you might want to adopt [Discord's markdown standard](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-)?

`*italics*`
`_italics_`
`__*underline italics*__`
`**bold**`
`__**underline bold**__`
`***bold italics***`
`__***underline bold italics***__`
`__underline__`
`~~Strikethrough~~`

Would make it easier for those transitioning between that platform to this one, and it would be more versatile.

### Version information

Element Desktop 1.7.7
Ubuntu 20.04

**Comment by turt2live** [comment]
We use commonmark, and there's several issues already reported for changing it
