### ISSUE TITLE
Suggestion: treat Direct Chats as a special case, not like any old room

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#15294]
The Element UI may need to treat a Direct Chat (DC) as a special case, not just like any other matrix room, to prevent the following weirdness I've experienced in Element-web (and in some cases Element-Android):

* If I'm already in a DC with a user, either of us can still create or receive an invite to create a new DC between the same two accounts. I can think of some edge cases where this would be useful (eg wanting to scrub chat history, 2 DCs with different uses), so having an option for it would be good, but it doesn't make sense for it to be the default. 

* If a user leaves a DC with me, it still sticks around in the "people" section of the Element UI, even though it's useless except as an archive. It would be better if it was automatically moved to the "historical" section. 

* If a user leaves a DC with me then invites me to a DC using the same account (or vice-versa), it would make sense to reactivate and continue the original DC (unless I opt out of that because of an edge case, as mentioned above). Instead, Element creates a new DC. Even if the old one is still hanging around in "people" with only me in it.

* If a user invites me to a DC, then invites me again from the same account, I can end up with 2 invites that will create two separate DC, between the same two user accounts. 

* I've been in a DC where starting verification starts a new DC. That would be fine if the new chat imported (and ideally encrypted) the message history of the legacy one, but it starts it as a fresh DC with no history. Obviously this is a bug that only affects us early adopters, who had unencrypted DCs before cross-signing was shipped and all DCs became encrypted by default. But it's still an example of what can come from not treating DCs as a special case.

**Comment by dbkr** [comment]
Thanks for the feedback: I think most of this is already covered by separate bugs, eg. https://github.com/vector-im/element-web/issues/15075, https://github.com/vector-im/element-web/issues/13647 and there is the immutable DMs project which encompasses some of this. I'm going to close this so we can open more specific bugs where necessary.
