### ISSUE TITLE
Desktop client stops receiving messages randomly during calls

### ISSUE THREAD

**Issue by hej2010** [vector-im/element-web#15291]
### Description

The Windows 10 client sometimes stops receiving updates/messages when I'm in a call. I receive all messages and such on my phone at the same time, but the desktop client shows that no new messages have arrived. 
I have to restart the desktop client for it to receive the "new" messages.

If the one I'm talking to disconnects (ends) the call I won't even notice (except that the other person is quiet) if I don't check my phone.

### Steps to reproduce

- Start/join a call
- Messages sometimes stops receiving randomly

Logs being sent: yes

### Version information

- **Platform**: desktop (Windows 10), Element 1.7.7, olm 3.1.3
- **OS**: Windows 10
- **Version**: 2004 (19041.508)

**Comment by dbkr** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1486
