### ISSUE TITLE
Can't get access token from the new Element client

### ISSUE THREAD

**Issue by adalvigi** [vector-im/element-web#15296]
### Description

Since there is still no mass redaction feature (check #7660 for more info), I am trying to find alternative ways to do it. I found https://github.com/xwiki-labs/matrix-stfu which looks like it's not been updated in a while, but I still want to give it a try. The tool asks me to provide my access token, which in riot was in Settings --> Advanced --> Access Token. Here I don't find such a thing, and I wonder how can I get my access token.
### Version information

- **Platform**: Desktop
- **OS**: Ubuntu
- **Version**: 1.7.7

**Comment by t3chguy** [comment]
It is Settings > Help & About > Advanced > Access Token
