### ISSUE TITLE
Stop displaying id of user but only nickname

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#15295]
![image](https://user-images.githubusercontent.com/464782/94365447-635aec00-00d1-11eb-889e-2cf09f1557a6.png)

### Description

Some contact in my contact list are shown with their nickname + their id whereas most of them are displayed with only their nickname.
Here is a picture taken from one of my friend list where I appear with my nickname + my ID whereas all his other contacts display only with their nickname.

Describe how what happens differs from what you expected.

I would like that all my contacts display only with their nicknam.

### Version information

- **Platform**:  desktop last version
For the web app:

For the desktop app:

- **OS**: Debian buster
- **Version**: 1.7.7

**Comment by dbkr** [comment]
This is intentional where two of your contacts have the same display name. This is necessary to prevent impersonation, although we'd like to find a more elegant way to do it.

**Comment by Thatoo** [comment]
As you can see on this picture, in this room we are only two users left.
An old user (my old account) have used the same display name but right now, this user is not in the room (has left for good) so there is no reason to prevent impersonation at all in this case.

Room that are considered as direct chat should not prevent impersonation between present users!
Maybe it should write the id of an old user who has left the room next to his/her display name (in the history of the room) but not next to the current user present in the room.
What do you think? I'm not asking for changing the whole prevent impersonation current system but only to give priority to present account (no id next to their display name) on old account who have left (they have id next to their display name). Especially on room that have been set as direct chat.

**Comment by Thatoo** [comment]
please @dbkr if you understood better my request, could you reopen my issue.
