### ISSUE TITLE
Users randomly cannot decrypt messages

### ISSUE THREAD

**Issue by igbjnI05bF** [vector-im/element-web#15301]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

Multiple users on my homserver have the issue where they suddenly cannot decrypt messages. Sometimes this occurs even when the users are verified with each other. They have cross signing set up and all devices verified. 

### Steps to reproduce
1. Be in a group room 
2. Chat back and forth 
3. Watch as suddenly certain users complain about not being able to decrypt messages
- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs are being sent

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by dbkr** [comment]
There doesn't appear to be a message being sent in these logs: a session is started (presumably when a user starts typing into the message box), so I can't find an example message where the sender's logs show them sending it and the receiver's logs show them failing to decrypt it.
