### ISSUE TITLE
Security key stored in form history

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15305]
### Description

When you log in to Element using your Security Key to authenticate/validate this new session, your security key is stored in clear text by the browser and suggested automatically on subsequent logins. The Security key field have form history enabled.

### Steps to reproduce

- Use a browser configured to remember form history
- Sign in to Element Web using your Security key to validate this new session
- Close the tab
- Clear cookies
- Sign in to Element Web using your Security key to validate this new session
- Your browser will now suggest your key to you in cleartext

Describe how what happens differs from what you expected.

As this is highly sensitive information, arguably more so than the password, form fields which ask for it should be either password fields or have autocomplete=off.

Logs being sent: no, not required

<img width="860" alt="Screen_Shot_2020-09-28_at_2_52_57_PM" src="https://user-images.githubusercontent.com/19155609/94441475-b6e53c80-019a-11eb-869f-8a2788087285.png">

### Version information

- **Platform**: web (in-browser)

For the web app:

Tested with Chromium on Mac, but very likely affects all browsers and operating systems

- **Browser**: Chromium 87.0.4269.0 (Developer Build) (x86_64)
- **OS**: macOS Catalina 10.15.6 (19G73)
- **URL**: app.element.io - v1.7.7 - but very likely affects all E web deployments

For the desktop app:

The desktop app is not affected. (At least not Element 1.7.7  on Mac)

**Comment by t3chguy** [comment]
just FYI, password fields don't support `autoComplete=false` because browsers think they know better, `new-password` is a hint which should work though

**Comment by turt2live** [comment]
maybe it thinks the new-password input is actually the username?

**Comment by t3chguy** [comment]
We haven't applied it to this field yet, we do to most other such fields.

![image](https://user-images.githubusercontent.com/2403652/94450999-d33aa680-01a5-11eb-98c0-c4a58686cf5f.png)
