### ISSUE TITLE
The room's files menu not showing anything 

### ISSUE THREAD

**Issue by janos-szenfner** [vector-im/element-web#15318]
I have problem with the desktop version. The room's files menu not showing anything althogh the android app yes. And the correct is the android's answer.
Even there is media and files nothing appears in the menu. 

Browser: Firefox and Brave latest 
Os: Windows 10 latest updates

**Comment by t3chguy** [comment]
As the web version says:

![image](https://user-images.githubusercontent.com/2403652/94618041-72dd5f00-02a2-11eb-9685-83bb3741f3f1.png)

In the desktop version, check Settings > Security & Privacy > Message Search to check on the indexing progress for this panel.

**Comment by janos-szenfner** [comment]
![elents-error](https://user-images.githubusercontent.com/27774520/94618729-e6d03500-02ab-11eb-9602-f5b71abdec0e.PNG)

No files or media. It was screenshot-ed from the app.

**Comment by t3chguy** [comment]
> In the desktop version, check Settings > Security & Privacy > Message Search to check on the indexing progress for this panel.

**Comment by janos-szenfner** [comment]
![elents-error2](https://user-images.githubusercontent.com/27774520/94619962-17b16980-02ae-11eb-9f6b-2b7b5266039e.PNG)

Screenshot attached. Still no info in file menu, although it looks like the indexing happened.

**Comment by janos-szenfner** [comment]
Any news on this? Do you need some extra information?

**Comment by jryans** [comment]
@turt2live Do you think this another version of https://github.com/vector-im/element-web/issues/12490?

**Comment by janos-szenfner** [comment]
Connected maybe, although in this case there is no media or file element in the file panel. And never appear in it anything.

**Comment by turt2live** [comment]
> @turt2live (in your maintainer capacity...) Do you think this another version of #12490?

Not particularly. It looks different and unrelated.

**Comment by turt2live** [comment]
Has anyone been able to narrow down reproduction steps for this? is this still happening?

**Comment by turt2live** [comment]
Closing this as we don't have reproduction steps and I haven't personally seen users mention it lately. Presuming fixed.

If this continues to happen, please open a new issue with fresh information.
