### ISSUE TITLE
Room "unread notification in a prior version of this room" have started popping up more often

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15312]
I've seen 0 notifications from prior rooms for a long time, and suddenly they are popping up fairly frequently in lots of older larger rooms like #dendrite:matrix.org and #thisweekin:matrix.org. I don't see any messages which could have notified me either, as the old rooms are just full of membership events.

I'm wondering if the way we ping for old rooms has been changed recently?

**Comment by dbkr** [comment]
Hmm, I don't believe we've changed anything. Any chance you've installed the desktop app with seshat recently?

**Comment by Half-Shot** [comment]
I've been running desktop with seshat for the last few months and it's been fine

**Comment by andybalaam** [comment]
@Half-Shot is this still happening?

**Comment by turt2live** [comment]
This is not an active issue, though if it continues to happen then please open a new issue with fresh information (and rageshake). I believe it was fixed long ago with server-side changes.
