### ISSUE TITLE
Double click and format includes space character on Windows

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-web#15310]
### Description
Element doesn't recognise that formatting should be applied up to the end of a string and not the space after it.

### Steps to reproduce

- Double click on a word. It gets highlighted along with the space after it. This is expected and normal.
- Select any of the formatting options, for example italics.

Element just adds two underscores to the ends of the highlighted string. This breaks the formatting and just shows the bare underscores. For example, "hello world" would become "_hello _world" and not "_hello_ world".

If you try the same thing in Github, the underscores get applied correctly. It takes care of the extra space on its own.

### Version information

- **Platform**: web
- **Browser**: Firefox 81.
- **OS**: Windows.
- **URL**: chat.fairydust.space
- **Version**: 1.7.8.

**Comment by dbkr** [comment]
Looks like the space after the word getting highlighted is indeed a thing that windows does.

**Comment by opusforlife2** [comment]
Thank you, that was fast! :D
