### ISSUE TITLE
Conference interactions are questionable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15314]
Hangup buttons, the word 'conference', etc. Requires design work.

**Comment by RinkiyaKeDad** [comment]
Hey @turt2live! I'd like to work on this. Can you tell me what exactly to look at what kind of changes you'd prefer?

**Comment by turt2live** [comment]
This is something that is likely to take shape through a larger project, sorry. There's a whole lot of critical thinking to be done and not a lot of design team bandwidth to do that thinking. Other issues in the issue tracker would be more complete to pick up - visit #element-dev:matrix.org and someone might be able to help guide you into something interesting :)
