### ISSUE TITLE
Unable to set up keys after registration on fresh account

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15319]
```
 Error bootstrapping cross-signing TypeError: device is undefined
    signDevice CrossSigning.js:480
    resetCrossSigning index.js:517
    bootstrapCrossSigning index.js:557
    name client.js:1105
    CreateCrossSigningDialog CreateCrossSigningDialog.js:142
    componentDidMount CreateCrossSigningDialog.js:62
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
    setStateForNewView MatrixChat.tsx:483
    MatrixChat MatrixChat.tsx:1948
    MatrixChat MatrixChat.tsx:1818
    Registration Registration.js:380
rageshake.js:65:27
    fnName rageshake.js:65
    CreateCrossSigningDialog CreateCrossSigningDialog.js:148
    componentDidMount CreateCrossSigningDialog.js:62
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
    setStateForNewView MatrixChat.tsx:483
    MatrixChat MatrixChat.tsx:1948
    MatrixChat MatrixChat.tsx:1818
    Registration Registration.js:380
    UNSAFE_componentWillMount InteractiveAuth.js:130
    (Async: promise callback)
    UNSAFE_componentWillMount InteractiveAuth.js:125
    React 9
    unstable_runWithPriority scheduler.development.js:653
    React 21
    unstable_runWithPriority scheduler.development.js:653
    React 6
    setStateForNewView MatrixChat.tsx:483
    onLoggedIn MatrixChat.tsx:1211
    MatrixChat MatrixChat.tsx:732
    _invokeCallback Dispatcher.js:198
    dispatch Dispatcher.js:174
    dispatch dispatcher.ts:51
```
![](https://i.imgur.com/LUeVT4y.png)

**Comment by turt2live** [comment]
develop, btw

**Comment by dbkr** [comment]
Apparently it was unable to find a stored device for itself. Maybe a race condition where it managed to set up cross signing before having downloaded the device list perhaps, although, I think we might inject our own device there anyway.

**Comment by jryans** [comment]
@dbkr Where does the own device injection happen? Can't seem to find it so far...

We could certainly sprinkle in even more `await this.downloadKeys([this._userId])` calls, at least as one possible path here.

**Comment by jryans** [comment]
From chat, @dbkr points out https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/crypto/index.js#L307 for adding the device, which happens quite early on...

@turt2live, can you send a rageshake instead of just this snippet? The full logs would be helpful here.

**Comment by turt2live** [comment]
@jryans done. It's in log-0001 about a mile down (ctrl+f for `device is undefined`)

**Comment by jryans** [comment]
The rough timeline of events seems to be:

1. We upload device keys for the new device
2. The new device is not present the device list at startup, so we inject it local as part of crypto init
3. The device list's initial sync response does not contain the local device, so **the injected one is removed**
4. Cross-signing tries to bootstrap, but fails because the local device went missing from the device list
5. Some other process triggers another device list sync
6. The uploaded device key comes down, re-creating the device in the device list ~150 ms after bootstrap failed
