### ISSUE TITLE
Line breaks removed when escaping characters

### ISSUE THREAD

**Issue by kalenpw** [vector-im/element-web#15320]
### Description

Line breaks are stripped out when escaping characters in a message

### Steps to reproduce

- Type the following
- \\> text [SHIFT ENTER] \\> text 2
- post message
- New lines will be stripped from post 

Describe how what happens differs from what you expected.

Expectation is line breaks are preserved 

Logs being sent: no

![riot](https://user-images.githubusercontent.com/13550971/94624828-8ffb3900-0274-11eb-8cf2-b9b20b841367.png)
(Left becomes right when you enter it)

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Verified on Chrome and Microsoft Edge
- **OS**: macOS Mojave and Ubuntu 18.04
- **URL**: Elsewhere, version 1.7.7

For the desktop app: 

I'm fairly certain this happens on Desktop version but will update here later after I confirm

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by dbkr** [comment]
I can repro this but only by putting backslashes before, as in your screenshot, rather than without as in your repro steps, ie:

````
\> test
\> test
```

**Comment by kalenpw** [comment]
Good catch, they were stripped out of the Markdown. 

I believe the issue is here: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/editor/serialize.ts#L40-L50

Would the best course of action be editing `toPlainText()` [here](https://github.com/matrix-org/matrix-react-sdk/blob/97ebfa02c31492abbf577ec4fc6bf9ca5718027c/src/Markdown.js#L174)? This is my first time looking at the Matrix/Element codebase so I'm not positive

**Comment by ChristianTacke** [comment]
Things are rendered correctly, if there is other (normal) markdown in the message.
```
\*with asterisks\* is shown *correctly*, when using formatting elsewhere.
```

**Comment by ShadowJonathan** [comment]
FWIW https://github.com/vector-im/element-web/issues/17933 contains a little more diagnostic event info as to what could be going on. I currently think its an in-between step being triggered improperly, and all of the markdown output being thrown in formatted_body because `*` or such was detected in the input.
