### ISSUE TITLE
No more widget popout button or action

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#15321]
For example for Etherpad widgets, when in the sidebar, there is no way to popout the widget like before. Getting to the URL of the widget now requires clicking "Edit" and copypasting it from there.

Now when in sidebar, no popout action:

![Selection_756](https://user-images.githubusercontent.com/1174866/94658482-85d84980-030b-11eb-99f2-afe4de39e99d.png)

Before (and when pinned), popout action:

![Selection_755](https://user-images.githubusercontent.com/1174866/94658518-925ca200-030b-11eb-9103-9acb774529c6.png)

**Comment by t3chguy** [comment]
With the undergoing auth work it's not always possible to pop out widgets so I believe it simply will no longer be supported. Full screen interactions are planned however.

**Comment by turt2live** [comment]
I think this is a feature of that particular widget, or it got fixed. Either way, if the intention is different then I think the change would be on the Scalar side.
