### ISSUE TITLE
room list filter sometimes doesn't

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15322]
Sometimes typing in the room list filter returns all of my rooms as the results no matter what I type. Unsure what the pattern is: I tried to repro with advanced logging on but then it stopped doing it. Turned logging back off and it's still fine.

**Comment by dbkr** [comment]
Or possibly it's only filtering by the first character I type, but now I can't repro that either.

**Comment by dbkr** [comment]
Just reproed this again just after signing in - debug logs attached

**Comment by bwindels** [comment]
I hit this too, and it was indeed as well after a new login.

**Comment by t3chguy** [comment]
This will be fixed with spotlight
