### ISSUE TITLE
Missing context menu when room tiles are minimized

### ISSUE THREAD

**Issue by lvlte** [vector-im/element-web#15339]
# Description

When room tiles are minimized (only displaying user avatars) objects that usually allow to display room context menus are not rendered into the DOM (namely `.mx_RoomTile_menuButton` and `.mx_RoomTile_notificationsButton`) and thus users can't access these settings using right-click as they were able to do in the past (lastly we upgraded from 1.6.0 to 1.7.3). 

### Steps to reproduce

- In a standard browser window, when the room list is expanded, can right-click on a room's display-name to get context menu 
- Reduce the viewport width until the rooms list get collapsed
- right-click does not do anything, DOM elements that would trigger context menus have been removed

Maybe this issue won't be considered as a bug as it seems DOM elements are only rendered if they have the ..room to expand (?) but in this case consider this as a feature request : it would be nice to get back context menu on right-click on a room tile whatever the state collapsed/expanded of the rooms list - at least for the favorites/priority settings now that these settings are split in 2 different menus). 

Context menu in 1.7.3, available only if room tiles are expanded :
![Screenshot 2020-09-30 154029](https://user-images.githubusercontent.com/39483232/94693374-ec715d80-0333-11eb-8fb1-f236776b6b7a.png)

Context menu on 1.6.0, available whatever the state of the room list :
![index](https://user-images.githubusercontent.com/39483232/94693724-57bb2f80-0334-11eb-8746-42eb365229c5.png)

### Version information

- **Platform**: web (in-browser) , whatever the browser
- Version: 1.7.3

**Comment by t3chguy** [comment]
You *CAN* use your context menu button or right click to bring up the general menu on them even when collapsed.

![image](https://user-images.githubusercontent.com/2403652/94694715-06f40880-032d-11eb-9ca8-1912d85622be.png)

The notifications menu is not visible via this method though.

**Comment by lvlte** [comment]
Maybe I missed something but it seems no I can't, on my side the DOM element looks like below, is this what is expected ?  
![Screenshot 2020-09-30 160058](https://user-images.githubusercontent.com/39483232/94695477-41ae6e80-0336-11eb-9cd8-ca4ea0cc4a7a.png)

**Comment by t3chguy** [comment]
Yes, and the `mx_RoomTile_minimized` has an onContextMenu handler.

**Comment by lvlte** [comment]
I got only one listener for 'click' events, not 'contextmenu'. 

![Screenshot 2020-09-30 164346](https://user-images.githubusercontent.com/39483232/94700779-29415280-033c-11eb-979c-835253271ecc.png)

**Comment by t3chguy** [comment]
Probably because you are ignoring the root level React listeners, it has its own bubbling. https://reactjs.org/docs/handling-events.html

**Comment by lvlte** [comment]
Thank you to point this out. 
Well, next issue.. the React extension won't load on my side. :/ do you know how can I get react handlers info in vanilla js ?

**Comment by t3chguy** [comment]
> do you know how can I get react handlers info in vanilla js ?

Nope

**Comment by t3chguy** [comment]
What are you trying to achieve?

**Comment by lvlte** [comment]
I want to check if the `mx_RoomTile_minimized` elements are correctly bound to a contextmenu handler, and if it's the case find if the handler is actually triggered or not, eventually catch another handler that would prevent the expected behavior, or it does trigger find out why we can't see the context menu. I'm just thinking about a display issue, we have a lot of css override.

**Comment by t3chguy** [comment]
Yeah I suggest getting React Devtools working, as `correct` is contextual.

> correctly bound

It is in the React world

**Comment by lvlte** [comment]
I didn't manage to get React devtools working, but I tried upgrading to 1.7.5 and contextmenu is now triggered as expected (however 1.7.4 behaves like 1.7.3).

**Comment by t3chguy** [comment]
Right, well that's probably when I added it. Latest is 1.7.8 - if you want valid support I suggest you keep up to date

**Comment by lvlte** [comment]
Yep thanks
