### ISSUE TITLE
"Rejoindre" ("Join" in french) button in explore room modal doesn't fit

### ISSUE THREAD

**Issue by henricazottes** [vector-im/element-web#15347]
![style_bug_element](https://user-images.githubusercontent.com/5214384/94782140-1aee4780-03cb-11eb-898f-273cb16343ae.png)

### Description

This image is speaking for itself, the join button doesn't fit in the modal for french language.

### Steps to reproduce

- set language to French
- click on explore rooms

### Version information

- **Platform**: web in-browser

For the web app:

- **Browser**: Firefox 81.0
- **OS**: Elementary OS
- **URL**: https://app.element.io/

**Comment by slsimic** [comment]
Does this fix consider space for the Preview translated string also?
See #16244 for the screenshot

**Comment by jryans** [comment]
> Does this fix consider space for the Preview translated string also?

Yes, it adapts for both.
