### ISSUE TITLE
Right sidebar broken when previewing a room (possibly only predecessor rooms)

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15349]
### Description

![image](https://user-images.githubusercontent.com/1342360/94800994-4da13b80-03dd-11eb-88fb-6880120d548c.png)

While previewing a predecessor of an upgraded room (`!HsxjoYRFsDtWBgDQPh:matrix.org` is room ID of the predecessor), I find that I'm unable to see the right hand sidebar. I can click the info and notifications buttons at the top, but the sidebar does not open.

### Steps to reproduce

- Go into a room that has been upgraded, aka `#synapse:matrix.org`.
- Go into room settings -> advanced.
- Click "View older messages in `#synapse-dev:matrix.org`.
- Start previewing the old room if you aren't already in it. See that you can't open the sidebar.

Either I should be able to open the sidebar, or those tantilising buttons at the top right of the screen shouldn't appear.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Debian Linux
- **Version**: 1.7.7

**Comment by t3chguy** [comment]
It was disabled on purpose some time back, I don't recall why

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/commit/dd911d18cb2209a8db603732919e602528f25f68 - though the comment seems redundant given the redesign of the right panel

**Comment by anoadragon453** [comment]
Woot, thanks for the quick fix.
