### ISSUE TITLE
Allow DMs to be created without E2EE

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#15342]
Quite a few clients don't support E2EE yet. The only solution seems to be to disable E2EE-by-default for the _entire_ server using [.well-known](https://github.com/vector-im/element-web/blob/develop/docs/e2ee.md#disabling-encryption-by-default), which feels a bit convoluted and something only a server admin can do, so quite far from an ideal solution. So it's currently impossible for most users to create working DMs with users using clients that don't support E2EE.

It would be nice to have e.g. an "advanced" settings section when creating a DM that would allow creating the DM without encryption.

**Comment by babolivier** [comment]
FTR I tried searching for this issue in the list of open ones before opening this one, but I haven't found any. Sorry if I created a duplicate on accident.

**Comment by t3chguy** [comment]
This was done on purpose to not dilute the security of the brand. It only creates encrypted DMs if your peer has e2ee pubkeys uploaded.

**Comment by dbkr** [comment]
Sounds like this i a thing we don't intend to do then, so I guess we re-open if our intentions change in the future.

**Comment by babolivier** [comment]
> This was done on purpose to not dilute the security of the brand. It only creates encrypted DMs if your peer has e2ee pubkeys uploaded.

Oh, it's slightly less annoying then. My issue was when the other side is using a client that had to drop E2EE, e.g. FluffyChat temporarily, due to legal restrictions.
