### ISSUE TITLE
config.sample.json sets a bad example

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15357]

**Comment by ara4n** [comment]
it suggests you have riot-bot as a welcome bot, and possibly other bad practices. needs to be brought in line with whatever our best recommended defaults are.

**Comment by aaronraimist** [comment]
Should `config.sample.json` show a recommended default or show every possible config option? https://github.com/vector-im/element-web/blob/develop/docs/config.md says 

> For a good example, see https://develop.element.io/config.json.

so presumably `config.sample.json` is trying to show the examples for most/all of the available config options.

**Comment by ara4n** [comment]
i don't mind particularly, as long as it doesn't provide bad sample content for the config options. for welcome-bot i'd just leave it out.

**Comment by aaronraimist** [comment]
Ah I see this came out of the IETF trial.

In addition to removing it from the sample config, @riot-bot:matrix.org should probably also be taken offline. The tutorial is totally out of date so I can't imagine it is helpful to anyone.

**Comment by jryans** [comment]
I believe riot-bot is the only outlier here: the remaining items are redundant (since they re-state the default value), but seem useful to keep for demonstrative purposes.

Let's fix this by removing the riot-bot part then.
