### ISSUE TITLE
Etherpad Issues

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15353]
We've upgraded to the latest etherpad (which is very pretty) but there still seem to be some issues. Cataloguing here:

All in Element 1.7.8:
- [ ] Etherpad widget in **Safari** Version 14.0 (14610.1.28.1.9) says _Sorry, this content is not embeddable in Matrix_ (broken no-banana image)
- [ ] Etherpad widget in **Firefox** Nightly (82.0a1 (2020-09-20) (64-bit)) complains about a cookie when you first open it. If you ignore the red warning, close and reopen the widget the warning is gone.
     <img width="322" alt="image" src="https://user-images.githubusercontent.com/1922197/94832079-61f92e80-0405-11eb-86b3-6d44eaab1f27.png">
- [ ] Etherpad widget in **Chrome** (Version 85.0.4183.102 (Official Build) (64-bit)) shows the same red warning, but it reappears each time you reopen the widget

In Element Nightly Desktop version: 2020092801 everything works perfectly.

**Comment by jaywink** [comment]
@lampholder which integration manager is this tied to, `scalar.vectorm.im` or `scalar-staging.vector.im`?

**Comment by jaywink** [comment]
Looks like the cookie warning is not related to whether it is scalar or scalar-staging.

**Comment by jaywink** [comment]
This should be fixed - can you confirm @lampholder
