### ISSUE TITLE
The volume level of the stereo mix changes on its own during a voice call with Element

### ISSUE THREAD

**Issue by AndyBRoswell** [vector-im/element-web#15351]
### Description

During a voice call using Element, the volume of stereo mix is changing automatically.
Other software such as Zoom don't have this issue when having a voice call.

### Steps to reproduce

-Using stereo mix as audio input.

1. Initiate a voice call to an arbitrary people or room. One side of the call is a Windows PC.
2. Disable the microphone of the other side of the voice call.
3. Play a song with the Windows PC. 
4. Listen to the sound via the other side of the call. 

I heard the music being played don't have a proper sound pressure level. I saw in the sound control panel that the volume level of the stereo mix changes on its own.
I need to broadcast audio files to others. Hence this makes the playback effect unsatisfying.

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows 10 Professional (x64)
- **Version**: 1.7.8

**Comment by dbkr** [comment]
Can you be a bit clearer about what's happening here? You're capturing the stereo mix output and playing a song on a Windows PC and on the other side, the volume isn't correct? Is it too loud or too quiet?

Seems like something is adjusting the input level of the capture device to get the levels to what it thinks is correct, although I'm not sure what that would be: definitely not code in Element itself - it could be Chromium/Electron doing it if you say it doesn't happen in Zoom.

**Comment by AndyBRoswell** [comment]
> 
> 
> Can you be a bit clearer about what's happening here? You're capturing the stereo mix output and playing a song on a Windows PC and on the other side, the volume isn't correct? Is it too loud or too quiet?
> 
> Seems like something is adjusting the input level of the capture device to get the levels to what it thinks is correct, although I'm not sure what that would be: definitely not code in Element itself - it could be Chromium/Electron doing it if you say it doesn't happen in Zoom.

Yes. I play a song on Windows PC with Element. I use the stereo mix instead of microphones as input. 
What's unexpected is that when I listen to the music being played on the other side (an Android phone, for example) , I find that the volume level fluctuates. Sometimes it gets too loud and sometimes it gets too quiet. 
Then I open the sound control panel on my Windows PC. I see the slider of the stereo mix sliding left and right as time passes.
![image](https://user-images.githubusercontent.com/46857536/94981647-65f09200-0566-11eb-9a91-9145a9dcd786.png)

In addition, when I hold a voice call via Telegram, the identical problem arises. But most of softwares which supports voice call (voice conference) my computer installed don't have this problem.

**Comment by t3chguy** [comment]
Sounds like https://github.com/vector-im/element-web/issues/6278 / https://github.com/vector-im/element-web/issues/4634

**Comment by dbkr** [comment]
Yeah, I think #6278 sounds like the solution to this - marking as duplicate.
