### ISSUE TITLE
downgrade attack on m.room.encryption events are incorrectly shown as successful in the timeline.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15362]
If someone edits the `m.room.encryption` event in a room to try to downgrade the encryption, we show a big beautiful "Encryption has been disabled" tile in the timeline... except in practice (thankfully) the downgrade attack isn't successful, and the room continues to be encrypted for the client.  It's very confusing/scary though; instead the tile should be "Ignored attempt to change encryption for this room" or something.

**Comment by t3chguy** [comment]
FTR its not talking about disablement

> Encryption has been disabled

It does not say that. It says

> Encryption not enabled
> The encryption used by this room isn't supported.

Do we want to simply hide the tile if we are still treating the room as valid & encrypted because of the cache within js-sdk?

**Comment by ara4n** [comment]
> Encryption not enabled

This is still a lie :)

I think it's useful to warn the user that hijinks are going on. "Ignored attempt to disable encryption" would be good enough imo.
