### ISSUE TITLE
If you have notifs off and your roomlist is filtered, there's no way to tell you have new invites

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15363]
Also, invites no longer seem to reliably push on iOS, so you can't even rely on looking there to see that someone's trying to talk to you.  I suggest we at least include the header of the Invites section when you're filtered, so you can see if it sprouts a badge or not

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/15088
