### ISSUE TITLE
Let admin verify keys in channels and groups

### ISSUE THREAD

**Issue by Oymate** [vector-im/element-web#15360]
**Is your suggestion related to a problem? Please describe.**
This would avoid everyone having to verify key and getting a scary message.

**Describe the solution you'd like**
Allow admin to accept this(optionally moderators)

**Describe alternatives you've considered**
Not any, yet.

**Comment by dbkr** [comment]
A generalised concept of a delegate that you trust to vouch for the identity of keys is a thing that's on the roadmap (somewhere). This would be a derivative of that.
