### ISSUE TITLE
/rainbow and /rainbowme heterogeneous in perceived brightness → poor legibility

### ISSUE THREAD

**Issue by hcsch** [vector-im/element-web#15369]
### Description

The `/rainbow` and `/rainbowme` commands produce text of which each character is rendered in a different hue. This currently seems to be done with in a color space like HSL which is not very uniform in perceived brightness, so changes in hue also affect the perceived brightness of the text, not only the chroma. This leads to poor legibility for some parts of the text (as can be seen in the screenshots below), more specifically the blue text on a dark background and the yellow text on a bright background.
![image](https://user-images.githubusercontent.com/34245439/95003964-71cf6900-05e5-11eb-8d23-a9b3b43e1237.png)
![image](https://user-images.githubusercontent.com/34245439/95003968-8b70b080-05e5-11eb-9131-5dc80818ad1f.png)

### Steps to reproduce

1. Choose either the light or dark theme of the element-desktop client
2. In any room write a message utilizing on of the `/rainbow` or `/rainbowme` commands

I would expect the rainbow of colors to be produced by making use of a perceptually more uniform color space like [HSLuv](https://www.hsluv.org/), [CIELCh](https://en.wikipedia.org/wiki/CIELAB_color_space#Cylindrical_representation:_CIELCh_or_CIEHLC), or the like. These allow for the generation of color gradients that are more uniform in perceived brightness and as such can be used to produce rainbow text with better, although admittedly still not perfect, legibility (see mockup images below). Notice in particular, that there is no overly bright yellow and no overly dark blue present. I can understand if this is simply not a priority, since I imagine `/rainbow` and `/rainbowme` are just a bit of a gimmick, but this color generation approach is also useful for other aspects of the UI (e.g. generating nick colors, or similar tasks).
Note also, that I am neither an expert on this topic, nor do I have any significant experience in UI design, I just ended up messing around with some color spaces like CIELCh for fun and like what you can do with them. So please do correct me or further improve upon my critiques of the status quo and suggestions for improvement.

Some mockup images made with GIMP using colors generated by evenly stepping through the hue component values of the HSLuv color space with S=100 & L = 50:
![hsluv-rainbow-text-mockup-dark](https://user-images.githubusercontent.com/34245439/95004847-ebb91f80-05f0-11eb-9c0b-6ec8a7bfae6c.png)
![hsluv-rainbow-text-mockup-light](https://user-images.githubusercontent.com/34245439/95004848-ec51b600-05f0-11eb-9cfa-00b5a9f34af1.png)
(excuse the green tint in white text, that is a GIMP issue)

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.5

**Comment by dbkr** [comment]
Are we expecting anyone to maintain these features?
