### ISSUE TITLE
As a community admin, leaving a community room makes the room listed as "Unnamed room" in the community

### ISSUE THREAD

**Issue by Ezwen** [vector-im/element-web#15375]
# Description

I am the admin of a matrix community in a homeserver (that coincidentally I also administer). Once in a while I add a new room to this community. Usually I simply join (or create) the room I want to add, then I use the community UI to add the room to the community. I also make sure that the room has a canonical name and can be joined by anyone. If I am not personally interested in the room, I then leave the room, and the room remains in the community. This worked well so far.

However today the following happened:
- First, I joined a room and added it to the community: the room showed up properly in the community room directory, with correct title and icon. 
- **Then**, since I was not interested in the room, I left the room. After doing that, the room was instantly relabeled as "Unnamed room" in the community directory, and lost its icon. Trying to join the room by clicking on the "Unnamed room" item leads to a mysterious "No known servers" error.
- Last but not least: if as an admin I join the room once again (eg. using its canonical name), the room is instantly relabeled correctly in the community directory (and regains its icon). The problem can be triggered and triggered at will by leaving/joining the room as a community admin.

I do not understand what made today different from previous cases.

I could not find any similar issue, except maybe this one: https://github.com/vector-im/element-web/issues/5866
But it describes a problem involving multiple admins, while here there is only one.

### Steps to reproduce

- Have an existing community with rooms and members. The community has one admin.
- Have the admin join a room with a canonical name and that anyone can join.
- Have the admin add the room to the community directory. The rooms appears in the directory as expected.
- Have the admin leave the room. The room gets instantly relabeled as "Unnamed room" in the community directory, and loses its icon. Trying to join the room by clicking on the "Unnamed room" item leads to a mysterious "No known servers" error.

I expect the room to still correctly show up in the community directory, even if the community admin leaves it.

Logs being sent: the errors appearing in element-web when trying to join the room shown as "Unnamed room" from the community directory (I anonymised the IDs and server names) :
```
RVS update: !FOMElCxrJvSDGezNlWCMeGVZG:myserver.com undefined loading? false joining? true initial? undefined shouldPeek? true
XHRPOSThttps://myhomeserver.org/_matrix/client/r0/join/!FOMElCxrJvSDGezNlWCMeGVZG%3Aanotherserver.com
[HTTP/2 404 Not Found 27ms]

Failed to join room: No known servers 
Starting load of AsyncWrapper for modal
RVS update: !FOMElCxrJvSDGezNlWCMeGVZG:3Aanotherserver.com undefined loading? false joining? false initial? undefined shouldPeek? true
```

Note: the very same room can be joined without problem using its canonical name directly.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 81.0
- **OS**: Fedora Linux
- **URL**: radical

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
