### ISSUE TITLE
trim spurious whitespace of nicknames

### ISSUE THREAD

**Issue by hydrargyrum** [vector-im/element-web#15374]
### Description

When changing nickname, trailing whitespace is kept, which is useless and confusing, and also makes it harder to highlight people.

### Steps to reproduce

- change nickname to "foo " (with a trailing space)
- nickname is "foo " instead of "foo"

**Comment by smitoi** [comment]
Could I work on this?

**Comment by smitoi** [comment]
Could I work on this?

**Comment by t3chguy** [comment]
Sure, no need to ask.
