### ISSUE TITLE
Suggestion: requiring cross-signing to give a session access to encrypted chats

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#15372]
**Is your suggestion related to a problem? Please describe.**

It's difficult to convince people to do the encryption verification dances, either to verify each other's accounts, or to cross-sign their own sessions. The result is a communication system that promises private messaging protected strong encryption, but doesn't consistently deliver that result. People thinking they're communicating more securely when they aren't is *worse* than when they know they're not communicating securely.

**Describe the solution you'd like**

Encrypted chats are only available to a session that has been cross-signed from a trusted session. Until a new session has been cross-signed, it can be used to access public chat rooms and unencrypted group chats, but encrypted chats don't even appear. This protects important metadata (who this user has been having encrypted chats with). The scary red shield warning is no longer necessary, because a session that hasn't been cross-signed can't access anything encrypted. The UI only needs black shield (Trust On First Use) and green shield (other user verified out-of-band).

Another advantage is that we can access public chats using whatever apps work on the devices we are using, even if they haven't implemented cross-signing yet, or haven't even implemented encryption yet. Fractal on the PinePhone is an example. It's not yet possible to cross-sign Fractal sessions and worse, Fractal seems to create a new session every time I login. Yet it's currently the only app usable on PinePhone with which I can access public chat rooms on matrix.

**Comment by dbkr** [comment]
Interesting idea, and could tie in nicely with the fact that you won't have history for any of those rooms without verifying anyway. Closing for now as this isn't a thing ready to be an issue on the bug tracker yet, but will feed into design.
