### ISSUE TITLE
Integration Manager no longer works in Firefox due to CORS

### ISSUE THREAD

**Issue by Midar** [vector-im/element-web#15371]
### Description

Integration Manager no longer works in Firefox due to CORS.

### Steps to reproduce

- Click on "Add apps, bridges & bots"
- Immediately get an error that the Integration Manager is unavailable
- Check console and see:
```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://scalar.vector.im/api/account?scalar_token=XXX&v=1.1. (Grund: CORS-Anschlag schlug fehl).

Error: CORS request rejected: https://scalar.vector.im/api/register?v=1.1
    u index.js:259 xxx
    onreadystatechange index.js:242
submit-rageshake.ts:150:25
    n submit-rageshake.ts:150
    open ScalarAuthClient.js:199
```
(Roughly translated: CORS request blocked: Same Origin Policy prohibits reading of exernal Resource)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 81.0.1
- **OS**: Tested on macOS, but I suppose it's not specific
- **URL**: app.element.io, webchat.kde.org, localhost (running 1.7.7)

Also, I accidentally pasted in my `scalar_token` in here at first. What mischieve can be done with it and how can it be invalidated?

**Comment by dbkr** [comment]
I can't repro this: is it possible scalar or your net connection was having a blip at the time?

I believe the leaked scalar token was sorted out-of-band, FTR, your scalar token is used to auth you to scalar so people could create bridges / bots on your behalf.

**Comment by Midar** [comment]
Nope, this is consistently happening, so I'd rule out the network connection.
