### ISSUE TITLE
Broken invite that can't be removed

### ISSUE THREAD

**Issue by RebelCoderRU** [vector-im/element-web#15370]
### Description

A new invite was added (just appeared) to the list, but can't be accepted, rejected or ignored.

### Screenshots:

Invite:
![Screenshot_20201004_095831](https://user-images.githubusercontent.com/20476773/95009124-2d18f180-0628-11eb-99dd-187071b1e7d0.png)

![Screenshot_20201004_095346](https://user-images.githubusercontent.com/20476773/95009047-82a0ce80-0627-11eb-8b69-03679713bd87.png)

**If Accepted:**
![Screenshot_20201004_095308](https://user-images.githubusercontent.com/20476773/95009053-a3692400-0627-11eb-8f69-5f6d10eadf71.png)

**If Rejected or Reject & Ignore user:**
![Screenshot_20201004_095315](https://user-images.githubusercontent.com/20476773/95009056-a5cb7e00-0627-11eb-8a59-3ba3fa720ff9.png)

### Version information
Element version: 1.7.5
olm version: 3.1.3

**Comment by dbkr** [comment]
Dup of something, probably https://github.com/vector-im/element-web/issues/4225
