### ISSUE TITLE
Element Desktop does not handle running out of disk space gracefully

### ISSUE THREAD

**Issue by fridtjof** [vector-im/element-web#15378]
### Description

After running out of disk space, I encountered an encryption related error message in a direct chat. I restarted Element Desktop, after which it complained about something related to missing session data. That's where I'm sending debug logs from.

### Steps to reproduce

- run out of disk space
- get an encrypted message (presumably while there is no space left, not sure)
- clear some disk space
- restart element desktop

I expected Element to come back normally and retry decrypting the message, but it gave me this error message instead.

Log: sent

<img width="773" alt="grafik" src="https://user-images.githubusercontent.com/2780577/95101538-8b31fb80-0732-11eb-9255-559581814b65.png">

### Version information

- **Platform**: desktop

- **OS**: macOS 10.14.6
- **Version**: 1.7.8

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/element-web/issues/4014
