### ISSUE TITLE
Mention everyone in a room at the same time.

### ISSUE THREAD

**Issue by frostraver** [vector-im/element-web#15385]
When you're in a room and want to mention someone you can type "@Username", but I would like to mention everyone in that room at the same time.
Discord has something like this where they can type "@Everyone" and then everyone gets a notification.

I could try working on this if this is an accepted feature, but I could use some guidance on where to start in the project.

**Comment by t3chguy** [comment]
`@room` - it is available to Moderators by default but that is configurable by the room's ownership.
