### ISSUE TITLE
Consider using optional chaining for JS in combination with Flow

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15387]
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining 
To make the transition to TypeScript as close as possible to an extension change, we should write better JS. This is one of the ways we can do that.

**Comment by jryans** [comment]
@turt2live What does Flow have to with this...?

**Comment by turt2live** [comment]
Flow is the step between JS and TS by giving types to JS. If the JS can be written to look like TS, then in the future all we'd need to do is change the file extension.

This is just one of the components that would let us do that.

**Comment by jryans** [comment]
But... we don't use Flow today...?

Also, the optional chaining proposal is already enabled, at least [at the Element Web level](https://github.com/vector-im/element-web/blob/57d5206592d09ab573b11e801d5f734a8f2d2f95/babel.config.js#L22)... but not in React SDK, so maybe that's what you want? (But we can _use_ it in React SDK, so slightly more mysterious, perhaps already enabled by the preset...?)

I don't understand what you want to change here. 😕

**Comment by turt2live** [comment]
oh, but we do use flow :D 
![image](https://user-images.githubusercontent.com/1190097/112521187-da5ffd00-8d61-11eb-9bb6-5d6b5cc73bfb.png)

It's buried under a ton of babel and isn't annotated, but it is sprinkled throughout the project.

If we get optional chaining in JS files without a babel plugin, I'm happy to close this. Otherwise this is very much a p3 nice to have for our transition to TS.

**Comment by t3chguy** [comment]
We have this now
