### ISSUE TITLE
Error on sign-up using Firefox on macOS

### ISSUE THREAD

**Issue by tim-seoss** [vector-im/element-web#15386]
### Error on sign-up using Firefox on MacOS

I requested a user visit https://app.element.io to sign-up, they got the response:

```
Failed to start

Your Element is misconfigured

Invalid homeserver discovery response
```

### Steps to reproduce

Unable to reproduce, possibly due to transient home server error.

This looks like a serious first-impressions failure unfortunately, when encouraging others to try Matrix / Element...

### What I expected to see

I think Element should try hard not to show a message which is either baffling or flaky looking to users.

Perhaps it should either retry silently, prompt the user to retry, and/or display a more human-readable message.

Logs being sent: yes/no

<img width="1627" alt="Screenshot 2020-10-06 at 12 52 12" src="https://user-images.githubusercontent.com/5011760/95200397-3e9ffc00-07d6-11eb-8521-201aa4c14e1e.png">

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 
- **OS**: macOS 
- **URL**: https://app.element.io

**Comment by dbkr** [comment]
Sounds like https://github.com/vector-im/element-web/issues/11154
