### ISSUE TITLE
Hide "Jump to read receipt" option for invited users

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-web#15380]
Sorry if the issue already exists, I've not found any, but it would be not the first time that I don't find an issue, so I create a new one and a few minutes later I got some comments with "duplicate of..." 😄 

So: in the room member detail panel of an **invited** user, the action "Jump to read receipt" is displayed, but has no effect. It should be hidden, because there is no read receipt data available for such users.

<img width="183" alt="image" src="https://user-images.githubusercontent.com/3940906/95108577-bf5dea00-073b-11eb-8903-664be6329fd1.png">

FTR I'm currently implementing that on EA and I will hide this action for invited users.

**Comment by t3chguy** [comment]
This should not pivot on whether a user is invited as they may still have an RR if they were in the room previously

**Comment by bmarty** [comment]
Yes, true, so maybe only show the action if a read receipt is available for this user
