### ISSUE TITLE
Where did the per-room notification settings go?

### ISSUE THREAD

**Issue by vmedea** [vector-im/element-web#15381]
https://element.io/help mentions, under "How do I change my notification settings?", a per-room notification setting, which could be set to:

- Mute
- Mentions only
- All messages
- All messages (noisy):

 I remember this setting appeared when clicking the right mouse button on a room in the overview frame to the left. However I only see:

- Favorite
- Low priority
- Settings
- Leave room

I've looked under *settings* but couldn't find it. What am I missing? Did this get removed (I hope not).

**Comment by turt2live** [comment]
There's now a bell icon next to the 3 dots where this can be changed.

**Comment by vmedea** [comment]
Oh, I didn't notice it because I had the left frame collapsed to icons only. Thanks!
