### ISSUE TITLE
Rarely used call buttons have too prominent of a location

### ISSUE THREAD

**Issue by Avamander** [vector-im/element-web#15397]
### Description

The "Send a message..." bar contains buttons for "Start a video call" and "Start a voice call". 

There's three issues that I and probably many others will stumble upon:

* Those buttons are rarely used, that space is somewhat wasted. 

* There's the expectation that a send button is there. Like on every other chat platform out there.

* Nobody wants to start a call willy-nilly, the action is intentional, infrequent and the button could be on the top bar instead.

* The button should be where it can't be accidentally clicked and it should be consistent with other chat platforms.

### Version information

- **Platform**: web (in-browser) or desktop? Latest web.

For the web app:

- **URL**: app.element.io

**Comment by dbkr** [comment]
We'll be looking at this UI very soon so this is useful feedback - thanks. The bug tracker isn't the right home for it though, so I'll close this bug.

**Comment by Avamander** [comment]
The "New Issue" button does show "UI/UX issues" as a separate category, plus why close it if it's not really improved yet?
