### ISSUE TITLE
'Enter your custom identity server URL. What does this mean?' in registration modal gives wrong text

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15399]
It should tell you what an identity server (IS) is. instead it tells you what a homeserver (HS) is.

**Comment by t3chguy** [comment]
Yeah we show the same modal on both the HS `what does this mean` and the IS one :(

**Comment by t3chguy** [comment]
We got rid of this during auth, now it is in settings with some supporting copy

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2403652/178987638-07af1a9c-af9f-48ef-a62c-e10e63988407.png">
