### ISSUE TITLE
Unable to "View Source" on broken messages

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#15409]
### Description

![image](https://user-images.githubusercontent.com/1342360/95342509-69aa4e80-08af-11eb-890a-c8e30762e985.png)

When seeing a broken event in a room, it can be really handy to immediately open up the source of that message, and see what happened.

Unfortunately, upon hovering over the event I find that this option isn't presented, unlike most other events that come through timeline.

This would make debugging breaking events a lot easier.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Linux
- **Version**: 1.7.8

**Comment by turt2live** [comment]
tbh the console is more important in these cases

**Comment by anoadragon453** [comment]
True, and I suppose one could argue that the commoner being able to see and easily replicate an event that broke something would be bad.

But when you're just testing things in a closed group, it can be easier for others to quickly gain access to the event source.

¯\\\_(ツ)_/¯

**Comment by t3chguy** [comment]
View Source is now shown there if you have Developer Mode enabled in /devtools
