### ISSUE TITLE
Rooms with multiple tags shouldn't disappear from secondary tag

### ISSUE THREAD

**Issue by apetresc** [vector-im/element-web#15418]
### Description

This is with the labs `feature_custom_tags`. If you have a room with multiple tags, it will only persist on the *first* tag's list. It will appear on secondary tags initially, but once the room is selected, focus is switched to the first tag's entry, and the room disappears from all other tags until Element is restarted.

### Steps to reproduce

- Enable `feature_custom_tags` in Element (Desktop)
- Add a room to multiple tags (in my case, I did that via gomuks since Element doesn't currently support tagging)
- Start Element, and confirm that the room appears in both tag lists
- Click the room on the _second_ tag that room was added to.

*What I expected*: For that room to open from the list I clicked, retain focus, and stay in that second list as well as the first list.
*What actually happened*: As soon as I clicked the room in the second list, the room disappeared from the second list, and focus jumped to the same room in its first tag list. The room remained completely invisible on the second list, until I restarted Element.

(The actual `room-account-data` still has all the tags correctly, it's just not showing up there in Element)

### Version information
- **Platform**: Desktop

For the desktop app:

- **OS**: Windows,
- **Version**: 1.7.8

**Comment by turt2live** [comment]
This is an intentional feature of the room list, but indeed it is a bit awkward

**Comment by turt2live** [comment]
Custom tags are replaced by spaces, and removed formally in https://github.com/matrix-org/matrix-react-sdk/pull/8027
