### ISSUE TITLE
Element erroneously starts E2EE conversation with bridged IRC user when using /query, silently breaking the conversation

### ISSUE THREAD

**Issue by joepie91** [vector-im/element-web#15417]
### Description

When using `/query` (or `/msg` apparently, but I have not verified this) to start a new private conversation with an IRC-bridged user, the newly-created conversation will erroneously have E2EE enabled. Since this is not understood by the receiving party, all messages get lost in the void without the sender being aware of this.

This issue __does not__ occur when selecting "Direct message" in the user profile pane, weirdly; only with the textual commands.

### Steps to reproduce

- Execute `/query @freenode_someuser:pixie.town` on a user that one has not created a conversation with before
- Observe the "end-to-end encrypted" header in the resulting room
- Try to send a message
- Get very confused when the recipient never replies and turns out to never have received it

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Linux
- **Version**: 1.7.7

**Comment by t3chguy** [comment]
This is fixed in the latest RC.
