### ISSUE TITLE
Smart(er)-ish Search bar

### ISSUE THREAD

**Issue by yuuki-san** [vector-im/element-web#15415]
**Is your suggestion related to a problem? Please describe.**
It makes me furious when I search for something, its not present in my people and rooms lists so I click on the "Explore all public rooms" thingy and it forces me to type it again

**Describe the solution you'd like**
When I use the "Search" bar and I type in something that isn't present in my rooms, I want the "Explore all public rooms" text/button to be smart(er) and copy my searched text straight into the search bar of "Explore rooms".

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by robintown** [comment]
This appears to be fixed.

**Comment by t3chguy** [comment]
Yup!
