### ISSUE TITLE
Personal avatar shows-up as room avatar (with room power 0)

### ISSUE THREAD

**Issue by danger89** [vector-im/element-web#15411]
### Description

I'm seeing the personal avatar as room avatar.

### Steps to reproduce

- Create a room.
- Have a second user join.
- Have the second user change their avatar.
- Observe the room's avatar in Element Web switch to the second user's avatar.
- Inspect the room state and note there is no m.room.avatar event.
- Update the room avatar.
- Observe the room's avatar in Element Web switch to the room avatar.

I would expect that a user (without any power level), should NOT be able display his/her avatar as room avatar.

However, as you will see it is possible.. and very confusing. 

### Version information
- **Platform**: Both web & desktop

For the web app:

- **Browser**: All browsers
- **OS**: All OS
- **URL**: app.element.io & Element Desktop

For the desktop app:

- **OS**: All distros
- **Version**:  1.7.8

Note: This issue was first identified as a server-side issue (Synapse), but most likely this is definitely a client-side problem --> Element.

See related issue: https://github.com/matrix-org/synapse/issues/8483

Regards,
Melroy van den Berg

**Comment by clokep** [comment]
I was able to reproduce this -- I'm unsure if it is a bug or working as expected, but it seems Element Web might be getting confused at whether the room is a private conversation or not?

**Comment by t3chguy** [comment]
This is DM naming/avatar rules,DMs are not very distinct from rooms.

**Comment by turt2live** [comment]
This is expected behaviour.

**Comment by danger89** [comment]
Well this was not expected behaviour for me.

Again this is a public #welcome room. Set as auto-join room in the homeserver.yml file.

**Comment by danger89** [comment]
Personally I think you need to separate private rooms with public rooms, this should not be expected behaviour in mine opinion.

**Comment by turt2live** [comment]
The avatar changes to a generic one once the third person joins. Public rooms should also have manually set avatars in our opinion.

**Comment by danger89** [comment]
OK well, we need to deal with it. Please note I will not be the first person that maybe create a ticket in the future regarding this behaviour. 

Thanks for you replies!
