### ISSUE TITLE
Quotation Marks in Display Name cause problems in Settings window

### ISSUE THREAD

**Issue by wklaebe** [vector-im/element-web#15419]
### Description

When my Display Name contains at least one Quotation Mark (U+0022), the Settings window closes when changing to "Appearance"

### Steps to reproduce

- open User menu
- click All settings
- change Display Name so that it contains a quotation mark (U+0022)
- click Save
- click Appearance

The Settings window then closes. This happened on a privately run Element instance and on app.element.io too.

This does not happen without the U+0022 character in the display name.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium "Version 83.0.4103.116 (Developer Build) built on Debian bullseye/sid"
- **OS**: Devuan testing/unstable
- **URL**: app.element.io

**Comment by turt2live** [comment]
I'm not able to reproduce this - can you send logs with the `/rageshake` slash command?

**Comment by rubo77** [comment]
Maybe it only happens if you use LDAP for the local users

**Comment by t3chguy** [comment]
The rageshake is needed to know what the crash was.

**Comment by wklaebe** [comment]
yee-haw. cannot drag-and-drop rageshake.tar because github does not support tar, cannot drag-and-drop rageshake.zip containing just rageshake.tar because "Something went really wrong, and we can't process that file."

**Comment by wklaebe** [comment]
https://wilfried.klaebe.de/tmp/rageshake.tar

**Comment by turt2live** [comment]
thanks - for future rageshakes we generally recommend using the submit button rather than the download button to avoid accidentally disclosing personal/sensitive information publicly.
