### ISSUE TITLE
No way to join an existing community (desktop/web)

### ISSUE THREAD

**Issue by NukeManDan** [vector-im/element-web#15425]
**Is your suggestion related to a problem? Please describe.**
I am missing something, or there is no way to browse, search or join an existing community. I only have the option to create a new one as far as I can tell 

**Describe the solution you'd like**
An easy way to browse or directly add a community (+parity:matrix.parity.io)

**Describe alternatives you've considered**
I have dug, but can't find a way in the gui

**Additional context**

clicking the "+" icon in the communities tab:
![image](https://user-images.githubusercontent.com/35669742/95524711-52db2900-098f-11eb-98a9-f6953149020a.png)

from here I see no way to find or add **or join** an existing one

**Comment by turt2live** [comment]
you can send the ID into a room and click on it, though obviously this is not the greatest.

The whole feature is slated for a rework.

**Comment by NukeManDan** [comment]
appears `https://matrix.to/#/+parity:matrix.parity.io` works to _view_ the room on the browser, but as you mention you need to click on a link in chat to the reference `+parity:matrix.parity.io` to view it.

This might be particular to this community - or that it is on a private server - but I can't join it. I see no gear/settings icon to be able to do so... Only share
![image](https://user-images.githubusercontent.com/35669742/95535662-3dbdc480-09a6-11eb-923f-a27acfa36754.png)

**Comment by turt2live** [comment]
That would be a community setting - they haven't made it open to join.

**Comment by houstdav000** [comment]
Adding a way to join or even list the public communities would be nice for sure. 

I'm currently instead having to check a room's settings, see if it has a flair setting (something probably indicating an official community), copying that community address into my web browser as `https://matrix.to/#/<community>`, and then joining it. 

It feels pretty excessive right now, so an in-gui way to search and join public communities would definitely be preferable.

**Comment by SimonBrandner** [comment]
@houstdav000, communities will be replaced by spaces (communities v2) soon, so this won't be a problem anymore

**Comment by ptman** [comment]
Spaces are here. For flairs it may still be useful to join old communities.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17264
