### ISSUE TITLE
missing translation: en-us|Upload files

### ISSUE THREAD

**Issue by mmahmoudian** [vector-im/element-web#15438]
### Description

While trying to paste a screenshot in https://app.element.io/ I got the following:

![image](https://user-images.githubusercontent.com/390889/95723182-8793fc80-0c7d-11eb-9c4e-f41e1493b624.png)

### Steps to reproduce

- open https://app.element.io/ and login
- go to any room
- paste a photo from clipboard (this is probably for any file, but this is how I got this error)

I also got these by seeing the info of a room that I'm the only member of (hence "1 people") but you get it for any room:
![image](https://user-images.githubusercontent.com/390889/95723695-17d24180-0c7e-11eb-985f-12e83af212d1.png)

**Describe how what happens differs from what you expected.**

I expected not to see the text before the "|"

### Version information

- **Platform**: web (in-browser) and perhaps the latest version (I couldn't find a place that shows the version!)

For the web app:

- **Browser**: Firefox 81.0 (64-bit)
- **OS**: Manjaro Linux 20.1.1 kernel 5.8.11-1-MANJARO
- **URL**: app.element.io

**Comment by t3chguy** [comment]
Clear your browser cache please

**Comment by mmahmoudian** [comment]
@t3chguy worked, thanks
