### ISSUE TITLE
without internet it doesn't work

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vector-im/element-web#15433]
1 - Matrix server without internet access and self signed certificate
2 - Element-web on a server and self signed certificate

The server and the element-web, having internet, works perfectly, but not without internet.
![perfect](https://user-images.githubusercontent.com/43164089/95667746-8625df80-0b6a-11eb-9898-c16c93ea6d05.png)

When opening the Mozilla Firefox development tools without internet, I notice that it makes a request to vector.im
![blok1](https://user-images.githubusercontent.com/43164089/95667763-b40b2400-0b6a-11eb-8580-4af7b0747cb9.png)

With the Mozilla Firefox development tools, if I block that path as you see in the photo above.  or I don't have internet access at the moment , I get this.
![err red](https://user-images.githubusercontent.com/43164089/95667802-34318980-0b6b-11eb-82b4-d617116512cf.png)
or
![err naranja](https://user-images.githubusercontent.com/43164089/95667804-43183c00-0b6b-11eb-820f-72512be49728.png)

What I mean is that if I don't have internet access at the time, it won't let me log in. Without internet, it doesn't work.

I can delete this line from the config.json of the element-web, but it would not let me enter HTTPS, only HTTP (without activating notifications, without calls ... etc)
`       "m.identity_server": {
            "base_url": "https://vector.im"
        }
`

My question, Can I create a vector.im [https://vector.im/_matrix/identity/api/v1] like the photo to let me enter without internet access?

**Comment by turt2live** [comment]
https://github.com/vector-im/element-web/blob/develop/docs/config.md explains the various ways to set up the identity server, including how to make it not required during the login and registration phases.

For assistance, please use #element-web:matrix.org

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/11655

**Comment by t3chguy** [comment]
That error says it is unable to reach `beta-nodex.azeroth.cu`
Is that service available to you offline? What does your Browser's Network console say?

**Comment by AnonymousWebHacker** [comment]
What I mean is that if I access my homeserver, without internet, it won't let me access, but with internet server and web client access, if it enters without any problem. I already said before that it tries to access the vector.im, as you mentioned in the above commit

**Comment by t3chguy** [comment]
Can you show the exact request it is making?
If it is not in the config then it is not hard-coded anywhere.
Check the network console of your browser.

**Comment by AnonymousWebHacker** [comment]
![console1](https://user-images.githubusercontent.com/43164089/95895126-1d2e9b00-0d15-11eb-9753-8252850e9141.png)
![console2](https://user-images.githubusercontent.com/43164089/95895132-1ef85e80-0d15-11eb-9cdf-4033545634ed.png)
the error that comes out, is for a self-signed certificate, but it is something that lets me access via normal element-android and element-web. but it won't let me log in. 
I am accessing my server (desktop / web / android) via HTTP, and in the case of ndroid, it lets me enter with HTTPS. But element web and desktop, they don't let me access via https, because they don't accept the certificate.

**Comment by t3chguy** [comment]
Element Web *CANT* let you accept the certificate, it doesn't even get told that is what the error is, your browser blocks the request and Element Web just gets told "Failed to request" 

You have to trust the cert in your browser.

**Comment by AnonymousWebHacker** [comment]
Chorme, accept the certificate  :)
![chrome](https://user-images.githubusercontent.com/43164089/95896474-39333c00-0d17-11eb-9bc1-59c5bbbec4e3.png)
