### ISSUE TITLE
Element Desktop and Nightly can fight over the same pickle key

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15432]
Both Desktop and Nightly assume they own the pickle key stored via `keytar`, so you were to e.g. login on both apps, they would each attempt to set pickle keys and conflict with each other.

It's probably fairly rare for people to test multiple channels of the app at the same time, so hopefully this doesn't affect too many people in practice.

**Comment by ara4n** [comment]
Hm, isn't it super likely that anyone installing Nightly will also have Desktop installed?

**Comment by jryans** [comment]
After checking again, it looks like I misinterpreted how the keys are saved, and I had thought it was using user ID only, but it uses both user ID and device ID, so the clash is avoided. I have also confirmed running both seems to set and keep keys for each app just fine, so seems like everything's actually okay here. 😅
