### ISSUE TITLE
Ctrl-k sometimes lags so that entered text is added to room input widget, not the room search bar

### ISSUE THREAD

**Issue by eras** [vector-im/element-web#15436]
### Description

Sometimes, perhaps more likely when the device or the browser is on the slow side, I can enter ctrl-k <word> and <word> is entered to the room input widget, not the room search bar. It doesn't seem that it can be reliably replicated, 

It seems the inverse is also true sometimes; finishing a search with enter does not immediately bring the focus back to room input widget, resulting in changing the search criteria.

### Steps to reproduce

- Have a laggy browser
- Enter a room; ensure the message entering area is active
- Rapidly enter ctrl-k term
- Witness that "term" is actually in the messaging area, not the room search bar
- If you failed to reproduce this, then it seems unlikely it will occur the next time either

I expect that the search term would go inside the room search bar.

No logs, as nothing relevant seems to go there.

### Version information

Element/Web 1.7.8

- **Platform**: webF

or the web app:

- **Browser**: Firefox,  78.0.2, though I've seen this on earlier versions as well
- **OS**: Debian Stable
- **URL**:  app.element.io

**Comment by t3chguy** [comment]
Not sure what can be done here as its the browser buffering the inputs whilst it is falling behind

**Comment by eras** [comment]
I'm sure the browser provides the input in the correct order, though, so it should be possible to determine which is the correct input field for the data; at worst it could be moved there after-the-fact.

**Comment by t3chguy** [comment]
Sure but the complexity of every input in the app being able to recognise every shortcut to move to another input (including tabbing) would be insane

**Comment by eras** [comment]
You put the logic in one base input which you reuse everywhere, right?-)

**Comment by t3chguy** [comment]
Sure except some inputs are textareas, some are contenteditable divs with very complex logic (called CIDER) for the composer which supports things like pills. The logic would be quite different for that.

**Comment by t3chguy** [comment]
This will be fixed by Spotlight
