### ISSUE TITLE
Clicking "When rooms are upgraded > On" in Settings > Notifications does not work

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15439]
The allowed values of Settings -> Notifications -> `When rooms are upgraded` appear to be "Off" and "Noisy". Clicking "On" when "Off" will cause the notifications to be noisy.

If room upgrades cannot be "On", we should remove the option. If they can, we should fix the bug.

**Comment by t3chguy** [comment]
This issue will be going away with the new notifications apis

**Comment by jaller94** [comment]
@turt2live This does not actually seem `p1` `severity: major`, if it hasn't been worked on since October.
I just ran into this in Element Web Stable. The issue is still around.

If it has been accidentally forgotten, here's a ping.

**Comment by turt2live** [comment]
Priority and severity don't dictate time in our issue tracker, sorry.

**Comment by robintown** [comment]
The new notification APIs were part of the FTUE Notifications project that got put on hold, so they haven't happened yet

**Comment by turt2live** [comment]
So it does work - the UI is just wrong. I wonder if that's what's causing https://github.com/vector-im/element-web/issues/10500
