### ISSUE TITLE
After logging in and out on a different browser, element-web keeps reminding me of reviewing logins

### ISSUE THREAD

**Issue by xuhdev** [vector-im/element-web#15437]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Log in using element-web in browser A.
- Log into the same account using element-web in browser B using private mode.
- Refresh the page in browser A. You should be reminded of reviewing new login. Click on "later".
- Close browser B, so that session is no longer accessible.
- Now go back to browser A. Every time you refresh browser A, the reminder would be there. There's no way to suppress this reminder (AFAIK).

Describe how what happens differs from what you expected.

There should be a way to mark a login session as "logged out" or "not to be verified" and dismiss the reminder.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 81.0.1
- **OS**: Debian
- **URL**: private server, 1.7.8

**Comment by t3chguy** [comment]
> Log out from browser B.

How did you log out, did you use the `Sign out` button in the app?

Is the session still listed in Sessions > Security?

> There should be a way to mark a login session as "logged out" or "not to be verified" and dismiss the reminder.

There is. Remove it in Settings > Security.

**Comment by xuhdev** [comment]
Hmm, ok, I didn't know I could remove it in settings. Feel free to close this, or it makes more sense to mark it as a minor UI enhancement?

I also updated the description, sorry I meant to lose access to the session in browser B.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/13187
