### ISSUE TITLE
popping out v1 jitsi widgets is broken

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15443]
Related to https://github.com/vector-im/element-web/issues/15427

**Comment by skolmer** [comment]
@turt2live  We tested the fix in our dev environment and the popout window is now opening. But when I click the join conference button nothing happens and the console is full of errors of this kind: `Failed to parse URL parameter value: jitsi.riot.im SyntaxError: Unexpected token j in JSON at position 0`

**Comment by t3chguy** [comment]
@skolmer that is unrelated to this issue.
Those are not new and can be safely ignored.

**Comment by skolmer** [comment]
@t3chguy Thanks for the quick response! Good to know that those errors are unrelated. Can you confirm in your environment that the join conference button is working in popout mode? On our systems it only works inside the room.

**Comment by t3chguy** [comment]
I can reproduce the Join Conference button not working

This is because the popout URL is still incorrect.
It should omit widgetId/parentUrl to disable the widgetAPI which is broken here.
