### ISSUE TITLE
Cross-signing failure: a device i've manually verified appears trusted to me but not other people

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15445]
My view:

<img width="267" alt="Screenshot 2020-10-12 at 17 57 09" src="https://user-images.githubusercontent.com/1294269/95772510-c42f1a80-0cb4-11eb-9115-8d8d8c13ecfe.png">

Amandine's view:

![image](https://user-images.githubusercontent.com/1294269/95772525-c98c6500-0cb4-11eb-8acf-cb71fabfe7c7.png)

(the hydrogen in question is the bottommost one, which i manually verified).

Relatedly: there appears to be no way to mark devices as untrusted any more.

**Comment by turt2live** [comment]
@ara4n are there logs for this?

**Comment by kittykat** [comment]
Closing as there is not enough information to reproduce or debug. Please reopen with logs if it happens again.
