### ISSUE TITLE
Mentions/Replies are not appearing in the "Notifications" panel

### ISSUE THREAD

**Issue by artiblaster** [vector-im/element-web#15447]
### Description

When someone mentions me or replies, no notification appears in the "Notifications" panel. The only notification I see in the "Notifications" panel is one from 2 weeks ago.

### Steps to reproduce

Logs being sent: yes/no

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: macOS 10.13.6
- **Version**: Version 1.7.9 (1.7.9)

**Comment by turt2live** [comment]
are the mentions encrypted?

**Comment by artiblaster** [comment]
Yes

**Comment by turt2live** [comment]
That would be why - encrypted mentions currently don't show up there. 

Duplicate of https://github.com/vector-im/element-web/issues/6874
