### ISSUE TITLE
Create event is a sliver of a tile

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15456]
We shouldn't render it if its just going to be empty:
![](https://i.imgur.com/qiJZ4iU.png)

**Comment by t3chguy** [comment]
We only render if it has a predecessor: https://github.com/matrix-org/matrix-react-sdk/blob/fbcea7d2ccbac68e4e28f4baf6e37941c5ac3675/src/components/views/rooms/EventTile.js#L992 which is when it is not a sliver. 

I cannot reproduce seeing such a sliver of a tile by creating a new room.

**Comment by t3chguy** [comment]
Ah this is related to Show hidden events.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11510
