### ISSUE TITLE
Our spinners are ugly.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15450]
<img width="240" alt="Screenshot 2020-10-13 at 10 34 47" src="https://user-images.githubusercontent.com/1294269/95843569-c2f6ff80-0d3f-11eb-8a59-f3f84887d095.png">

n.b. the white fringing on the dark theme.

**Comment by t3chguy** [comment]
There's a new spinner in Labs. Design needs to send one they are happy with though.

**Comment by niquewoodhouse** [comment]
I'm a bit concerned about this in a couple of ways.

### 1. Using spinners at all for this kind of thing.

Can we consider other ways of indicating progress?  Skeleton UIs for example.  Spinners are known to add to a sense of frustration and slowness in products.  Short example post https://www.lukew.com/ff/entry.asp?1797.  The more other products people use have things like skeleton UIs, the more spinners will stick out and add to that frustration.


### 2. Using the brand for spinners everywhere

I don't think it's a good idea to use the brand whenever there's something that needs a spinner, if spinners are needed.   Leaving aside things like it potentially cheapening the brand (which is a very subjective discussion), there are studies around how custom spinners make users blame your product, and not their device or wifi, for example.  https://blog.mercury.io/the-psychology-of-waiting-loading-animations-and-facebook/

**Comment by rosacola** [comment]
@niquewoodhouse just a dark spinner would suffice, the current one makes me uneasy.
