### ISSUE TITLE
Composer buttons do not have a useful "disabled" state

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15454]
Before you click Join Conference even as the creator of the conf

**Comment by turt2live** [comment]
this is expected

**Comment by t3chguy** [comment]
A button which does not work is expected, Nad and I were shocked by it when we tested it.

**Comment by turt2live** [comment]
I've made this the generic problem then.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/95876938-8640fd80-0d6b-11eb-90de-b5f5cf5b208b.png)

Currently looks very interactive, including pointer cursor

**Comment by turt2live** [comment]
yup, that's the issue. It's `disabled` though.

**Comment by t3chguy** [comment]
Part of the issue is the explicit cursor then 
![image](https://user-images.githubusercontent.com/2403652/95877287-d91ab500-0d6b-11eb-959f-7c4f9dc41979.png)

**Comment by turt2live** [comment]
in fairness, that was a product requirement at the time.

**Comment by SimonBrandner** [comment]
We don't have VoIP buttons in the composer anymore
