### ISSUE TITLE
'Allow Peer-to-Peer for 1:1 calls' setting does not make it clear that P2P shares your IP

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15460]
...and that the reason for disabling P2P is to avoid sharing your IP with the other party

**Comment by genewitch** [comment]
Since this is literally the only search result for the phrase "Allow Peer-to-Peer for 1:1 calls" - Does having this enabled bypass the TURN server? If i want to use the TURN server 100% of the time, should i disable this?

**Comment by SimonBrandner** [comment]
From my understanding: If you enable this, the other side might be able to see your IP. If you disable this a TURN server will always be used - the other side will never be able to see your IP.
