### ISSUE TITLE
Your Element is misconfigured, Invalid homeserver discovery response

### ISSUE THREAD

**Issue by zhangchunsheng** [vector-im/element-web#15467]
Your Element is misconfigured, Invalid homeserver discovery response

web

https://app.element.io/?pk_vid=81ba15ebc3bce61316027288379ec5bc

![image](https://user-images.githubusercontent.com/831839/96069564-12206a00-0ed1-11eb-8f7c-20340996350f.png)

mac app

![image](https://user-images.githubusercontent.com/831839/96069455-d8e7fa00-0ed0-11eb-938f-96c685a03281.png)

**Comment by turt2live** [comment]
Use #element-web:matrix.org for support
