### ISSUE TITLE
Horizontal scrollbar in chat window while video preview loads

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#15477]
### Description

After switching to a room with a video file, before the preview loads, I can see a horizontal scrollbar.

![Selection_777](https://user-images.githubusercontent.com/1174866/96175585-c4891900-0f33-11eb-8495-0c14a73944d1.png)

Once the preview loads, the scrollbar disappears.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu 20.04
- **Version**: nightly 2020101401

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/6881

**Comment by jaywink** [comment]
After it loads the preview is quite small in screen estate:

![Selection_780](https://user-images.githubusercontent.com/1174866/96176245-c6071100-0f34-11eb-8206-7f7a6759969b.png)

The decrypted message with some bits replaced:

```
{
  "room_id": "!foobar:domain.tld",
  "type": "m.room.message",
  "content": {
    "body": "video.m4v",
    "info": {
      "size": 73622443,
      "mimetype": "video/mp4",
      "thumbnail_info": {
        "w": 800,
        "h": 450,
        "mimetype": "image/jpeg",
        "size": 2459
      },
      "w": 1280,
      "h": 720,
      "thumbnail_file": {
        "v": "v2",
        "key": {
           .....
        },
        "iv": "...",
        "hashes": {
          "sha256": "..."
        },
        "url": "mxc://domain.tld/foobar",
        "mimetype": "image/jpeg"
      }
    },
    "msgtype": "m.video",
    "file": {
      "v": "v2",
      "key": {
          ....
      },
      "iv": "....",
      "hashes": {
        "sha256": "....."
      },
      "url": "mxc://domain.tld/foobar",
      "mimetype": "video/mp4"
    }
  }
}
```

**Comment by t3chguy** [comment]
This got fixed
