### ISSUE TITLE
Timestamps on email notifs only show HH:MM, not full disambiguous dates etc

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1547]

**Comment by ara4n** [comment]
they also need to be in the right TZ locale for the receiver.

**Comment by edgardmota** [comment]
Hi... may I have a try on this issue? Perhaps I'll ask for more info, but I have the willing to help.

**Comment by sonumeewa** [comment]
I can fix it, could you assign it to me?

**Comment by aaronraimist** [comment]
Feel free to work on it. GitHub won't allow issues to be assigned to people who aren't already contributors, see https://github.com/isaacs/github/issues/100.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/3111
