### ISSUE TITLE
Rooms and direct messages sometimes appear in wrong category.

### ISSUE THREAD

**Issue by golanv** [vector-im/element-web#15474]
### Description

Rooms and direct messages sometimes appear in the wrong category.  From time to time, certain direct messages appear in the "Rooms" category on the rooms list, and certain rooms appear under the "People" category.  The improper category placement seems to happen consistently with specific rooms.  If the cause is not obvious, perhaps the ability to move rooms from one category to another manually would be a good workaround.

### Steps to reproduce

Unknown, other than joining specific rooms from some accounts.

Logs being sent: yes/no

### Version information

- **Platform**: Element for Desktop

For the desktop app:

- **OS**: Fedora Linux 32
- **Version**: 1.7.9

**Comment by turt2live** [comment]
How were the rooms created and what has you thinking they are in the wrong category?

**Comment by golanv** [comment]
After further exploration, the best I can tell, is that this might be somewhat tied to the specific account and platform.  The room in question on Element for Android does not display the room name properly (showing "<user> and ### others", however it does group properly.  When the same room is joined from a different Matrix account, the issue does not appear.

**Comment by golanv** [comment]
Seems the m.direct "flag" was set for this room by mistake somehow.  Manually removing this room from m.direct with devtools resolves if in this instance, although I'm not sure how it got added here.  Perhaps bringing back a way to add or remove a room from the direct messages list would be nice...

**Comment by Dzordzu** [comment]
> Seems the m.direct "flag" was set for this room by mistake somehow. Manually removing this room from m.direct with devtools resolves if in this instance, although I'm not sure how it got added here. Perhaps bringing back a way to add or remove a room from the direct messages list would be nice...

@golanv How did you solved this issue? I've got similar situation, but in my case direct chat is marked as room. How can I set `m.direct` to the room? 
Disclaimer: I'm quite a new user in a matrix community, have searched API (via available swagger) and could not find any solution

**Comment by golanv** [comment]
> > Seems the m.direct "flag" was set for this room by mistake somehow. Manually removing this room from m.direct with devtools resolves if in this instance, although I'm not sure how it got added here. Perhaps bringing back a way to add or remove a room from the direct messages list would be nice...
> 
> @golanv How did you solved this issue? I've got similar situation, but in my case direct chat is marked as room. How can I set `m.direct` to the room?
> Disclaimer: I'm quite a new user in a matrix community, have searched API (via available swagger) and could not find any solution

@Dzordzu There are a couple of ways to change this:

1.  You can type /devtools in a chat (press "Enter"), then go to "Explore Account Data", then select "m.direct", and add the room you wish to appear in your direct messages to the list.  You'll need the Internal Room ID, which can be found in the "Advanced" section or the room setting.

However, I'd recommend an easier approach:

2.  Go to https://tags.t2bot.io/ and log in with your user account.  From here, you can just drag the room from the "Default" list to the "Direct Chats" list.  Much easier (arguably less fun though).
