### ISSUE TITLE
Question: Is it possible to change the color of a text or the text's background?

### ISSUE THREAD

**Issue by Kourgiantakis** [vector-im/element-web#15478]
Sorry, not an issue but i didnt now where else to ask.

Is it possible to either change the text color or the background color of a text?

If it is possible: How?

Thanks in advance!

**Comment by t3chguy** [comment]
This is an issue tracker. For support use http://matrix.to/#/#element-web:matrix.org

Closing in favour of https://github.com/vector-im/element-web/issues/5462
