### ISSUE TITLE
Support for custom backgrounds

### ISSUE THREAD

**Issue by resynth1943** [vector-im/element-web#15482]
Have been in touch with the Element team, and they're alright with the addition of this feature.
I'm working on this locally, along with a new Labs toggle. Will add more details soon.

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/element-web/issues/6356

**Comment by resynth1943** [comment]
@turt2live not exactly. This is a user setting. Can you reopen this?

**Comment by turt2live** [comment]
The solution would be the same, just with additional setting levels
