### ISSUE TITLE
"Show rooms with unread messages first" checkbox is buggy

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#15491]
Element version: 1.7.9 (app.element.io)

Pressing the "Show rooms with unread messages first" checkbox produces weird but deterministic behaviour. Clicking it does not toggle the checkbox unless pressing more times or reopening the dialog. When pressing multiple times it always shows the wrong state.

Video:

![untitled](https://user-images.githubusercontent.com/25297359/96377598-ed551c80-1186-11eb-9056-5399f28625d0.GIF)

**Comment by timokoesters** [comment]
Pressing any of the other buttons in the popup will update the "Show rooms with unread messages first" checkbox to the correct state

**Comment by t3chguy** [comment]
I believe it won't detect its update if the list does not re-order.
