### ISSUE TITLE
Wrong new messages count

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15505]
It looks like missed calls are counted multiple times:
![image](https://user-images.githubusercontent.com/14617699/96571058-c0625000-12d3-11eb-8b31-b958912dbd5f.png)
![image](https://user-images.githubusercontent.com/14617699/96571598-70d05400-12d4-11eb-9106-f2ff96470187.png)

**Comment by t3chguy** [comment]
The count is from the server and it includes things like voip events & also edits. So if that message was edited then the count would increase.

**Comment by 532910** [comment]
The message was not edited.

**Comment by 532910** [comment]
One missed call, one message.

**Comment by t3chguy** [comment]
Given the counts are generated by the server, I suggest opening a bug report there with more details of the events which took place, maybe using Settings > Labs > Show hidden events

**Comment by 532910** [comment]
With `Show hidden events` there 5 events:
![image](https://user-images.githubusercontent.com/14617699/96577332-1fc45e00-12dc-11eb-8a07-c7f2197fee74.png)

So I still believe this is a client issue, isn't it?

**Comment by t3chguy** [comment]
Nope, the count is calculated by the server; `notification_count` https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-sync
