### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by zimbipw** [vector-im/element-web#15508]
### Description

unable to login to element-web, with error message incorrect user name and/or password. I know it's correct since login credentials work with weechat and fractal

- **Platform**: web (in-browser)?

For the web app:

- **Browser**:  Firefox 81.0.2, Epiphany 3.38.1
- **OS**: Arch Linux
- **URL**:  https://webchat.freitrix.de/#/login

**Comment by t3chguy** [comment]
I suggest verifying the password is sent correctly in the request using your browser's Network Tools, this sounds more like a server failure.

**Comment by jryans** [comment]
Agreed this sounds like a server issue. Will close for now, but please let us know if there's more info to clarify why it's a client bug.
