### ISSUE TITLE
Explain flair better

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#15502]
No one knows what flair is. There should be a sentence near the flair settings explaining what it is (or a link to Office Space 😄).

Maybe there should even be an example showing the flair that the user has enabled, like the font size example.
<img width="590" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/96528524-99127100-1248-11eb-8fcf-e6e229a5283e.png">

**Comment by niquewoodhouse** [comment]
Love that, I have no idea what flair is.

**Comment by t3chguy** [comment]
Given that Spaces doesn't support Flair at this time it is something we can ignore for now

**Comment by niquewoodhouse** [comment]
This is separate to Spaces beta, right?  Flair exists for anyone, regardless of whether on beta or not? Eg it might be a papercut issue.

**Comment by t3chguy** [comment]
Flair is a Communities feature, given that the Beta is incompatible with Communities: Flair also gets disabled.

**Comment by niquewoodhouse** [comment]
Thanks for explaining

**Comment by t3chguy** [comment]
Flair will be rebuilt from the ground up
