### ISSUE TITLE
User is default permission level on one server, and admin on another.

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/element-web#15515]
### Description

Viewing the same room from both matrix.org and perthchat.org, the permission level of a user is different in each. :P

First user: @PC-Admin:perthchat.org, Element 1.7.8 on Debian. Observing the permission level of @PC-Admin:matrix.org:

![Screenshot from 2020-10-21 15-05-32](https://user-images.githubusercontent.com/29645145/96685358-91211100-13af-11eb-904c-7e8acc69ca69.png)

Second user: @PC-Admin:matrix.org, Element 1.7.8 in Firefox on Debian (https://app.element.io/). Observing his own permission level in the same room:

![Screenshot from 2020-10-21 15-05-14](https://user-images.githubusercontent.com/29645145/96685386-9bdba600-13af-11eb-99cc-0956374a7ca1.png)

### Steps to reproduce

Not sure how to reproduce.

**Comment by PC-Admin** [comment]
After an hour of trying to leave this room (holy #$@! matrix.org is slow) and re-join it, the permissions displayed correctly after re-joining. :S

**Comment by t3chguy** [comment]
This looks like a server issue where it missed telling your client in ` /sync` - you should have tried a clear cache and reload to invalidate all local data and fetch from scratch.

> Viewing the same room from both matrix.org and perthchat.org, the permission level of a user is different in each. :P

If this experience wasn't limited to you then it definitely is a server issue.

**Comment by jryans** [comment]
Agreed, I would assume a server issue as well, will close for now as I can't imagine what we'd do client side here, but if there's further evidence that it's a client bug, we can reopen.
