### ISSUE TITLE
collaborator sends message, but not received on our end

### ISSUE THREAD

**Issue by theoryshaw** [vector-im/element-web#15510]
I have a collaborator that receives my messages, but when they reply, and hit return, it registers on their end, but I do not get the message on my end. 

Are we missing something?

**Comment by turt2live** [comment]
This sounds like a server issue and not one for Element.

Please use the issue templates.

**Comment by theoryshaw** [comment]
Is there an alternate forum where users can ask high level questions?

**Comment by jryans** [comment]
Rooms like #element-web:matrix.org or #synapse:matrix.org are likely good places, depending on the question.
