### ISSUE TITLE
Room preview user profile went wrong

### ISSUE THREAD

**Issue by microsoft-sucks** [vector-im/element-web#15523]
### Description

>Something went wrong!
>
>Please create a new issue on GitHub so that we can investigate this bug.

![image](https://user-images.githubusercontent.com/67187266/96756077-13670080-13c3-11eb-9e27-04a04765f75c.png)

### Steps to reproduce

- Preview a room
- Access a user. Either by clicking on their profile picture in chat, or via `i` > "x people" and then their name,

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: app.element.io  1.7.10

**Comment by jryans** [comment]
Thanks for the report! I agree this was broken on app, but it seems fixed now on develop.

**Comment by jryans** [comment]
@microsoft-sucks Could you test develop.element.io to confirm that it is fixed for you as well?

**Comment by microsoft-sucks** [comment]
yes, works on develop fine :+1:
