### ISSUE TITLE
IRC users with backtick (`) in their nickname break nickname autocompletion/mention visually in element

### ISSUE THREAD

**Issue by rubinlinux** [vector-im/element-web#15525]
### Description

If I mention a user from IRC who has a backtick in their nickname, it interprets the backtick in their nick as a code block and shows the code behind the mention instead of the mention.

### Steps to reproduce

Connect an irc-matrix bridge, and find a friend on IRC whose nickname contains a backtick (\`). My friend for this example is named "d0nk`"

Join a channel with this irc friend using element client (In my case Desktop client version 1.7.8 (olm 3.1.3) but I have observed this in other versions and operating systems.

Type the begining of the persons nick and press tab. In this case I type d0n\<tab\>

I see their IRC nickname auto-complete as expected:

  d0nk\`[i]:

type a message to them after the :

  d0nk\`[i]: hey there

Observe that when you press enter to send, the mention of their name turns into:

  [d0nk \[i\]](https://matrix.to/#/@_afternet_d0nk :afternet.org): hey there

I would expect to see a colored "d0nk\`", but instead if see the raw code behind that (See image)

I suspect the solution is to properly escape the ` in the nickname so it is not interpreted by the display routine as a code block.

![Screenshot from 2020-10-21 11-59-29](https://user-images.githubusercontent.com/1413897/96771542-a6d60c80-1396-11eb-9c37-fcce72fd0b6a.png)

Thanks!

**Comment by clarkf** [comment]
I think this is fixed? Unless this is specific to IRC users (which I don't think it can be, given bridges). It works for matrix users with backticks in their display names.

```json5
{
  "content": {
    "body": "hi`there:  hey there",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@clarkf.test:matrix.org\">hi`there</a>:  hey there",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1674175798205,
  "type": "m.room.message",
  // ...
}
```
Rendered (eaace937b874):
<img width="266" alt="image" src="https://user-images.githubusercontent.com/439978/213595036-41a91ede-77f0-407a-b0d0-5fa85c65fd00.png">
