### ISSUE TITLE
Users can send empty messages

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#15524]
### Description

Element makes it very easy to send empty messages (consisting only of whitespaces). This seems like a bug and has no precedent in other messaging applications I know of, which all forbid this.

### Steps to reproduce

- In any room, click the message input
- Press the spacebar (or Shift+Enter)
- Press enter

I would expect nothing to happen (or the input field being cleared), but instead an empty message is sent.

### Version information

- **Platform**: desktop
- **OS**: arch linux
- **Version**: 1.7.10

**Comment by ara4n** [comment]
Very happy to refuse to let people send whitespace messages. </product decision>

**Comment by t3chguy** [comment]
What do we do in such a situation:
+ Clear the input
+ Fire a modal
+ Nothing, refuse to send with no user-visible reaction

**Comment by turt2live** [comment]
We previously refused.
