### ISSUE TITLE
Send files by copy-paste

### ISSUE THREAD

**Issue by hohlfury** [vector-im/element-web#15536]
May I ask you to add the ability to transfer files by copying the file in the explorer and pasting into the chat?

**Comment by t3chguy** [comment]
That's not something a browser supports conventionally.
If you paste a file from Windows Explorer into http://madebyevan.com/clipboard-test/ it does not work.

**Comment by hohlfury** [comment]
This is a desktop client Element.

**Comment by t3chguy** [comment]
Which is just element-web inside Electron which is Embedded Chromium

**Comment by t3chguy** [comment]
This is possible on MacOS which actually copies the file.
Linux copies the path which we cannot access, Windows copies some internal reference iirc

**Comment by t3chguy** [comment]
If you want this to work on Element-Desktop I suggest opening an electron bug about this
