### ISSUE TITLE
Hide "Add an email address to configure email notifications" message when UIFeature.thirdPartyId = false

### ISSUE THREAD

**Issue by jamescl** [vector-im/element-web#15543]
**Is your suggestion related to a problem? Please describe.**
When UIFeature.thirdPartyId = false, the user can no longer enter an email address. On the notifications page there is a message to "Add an email address to configure email notifications", but the use has no way of entering an email address.

**Describe the solution you'd like**
This message should be hidden when UIFeature.thirdPartyId = false,

**Comment by jryans** [comment]
Hmm, this one is more like a bug or perhaps needs a different UI feature to control it: setting an email on your account (for e.g. notifications) does _not_ automatically set it as a 3PID (that is a separate step), so the input for adding an email should still be present when `UIFeature.thirdPartyId == false`.

**Comment by jryans** [comment]
> Hmm, this one is more like a bug or perhaps needs a different UI feature to control it: setting an email on your account (for e.g. notifications) does _not_ automatically bind it on the identity server (that is a separate step), so the input for adding an email should still be present when `UIFeature.thirdPartyId == false`.

Ah hmm, I think I confused myself a bit. I see there is `thirdPartyId` for account contact info (a bit confusing to my mind but in any case) and `identityServer` for those bound to the IS.

So, `thirdPartyId` is perhaps a confusing name, but that's a separate topic and your original report seems correct. 😅
