### ISSUE TITLE
can't change profile picture

### ISSUE THREAD

**Issue by Wafelack** [vector-im/element-web#15540]
### Description

I can't change my profile picture

### Steps to reproduce

- I click on the picture symbol ![image](https://user-images.githubusercontent.com/61330081/97042304-1bfd3980-1571-11eb-9120-08cfa7d57f9b.png)

- I select my picture

- I click on "Save"

- I exit the settings

- My profile picture hadn't change and when i go back to settings the default picture is again here

Describe how what happens differs from what you expected.

The profile picture hadn't  change

### Version information

- **Platform**: Desktop

For the desktop app:

- Windows
- 1.7.10

**Comment by t3chguy** [comment]
Sounds like your server is rejecting the change. 
Can you send debug logs from Settings?

**Comment by Wafelack** [comment]
![image](https://user-images.githubusercontent.com/61330081/97043894-79928580-1573-11eb-9dda-afaaf4116409.png)
?

**Comment by ara4n** [comment]
yup, received - thanks.

**Comment by jryans** [comment]
Hmm, the log doesn't reveal much unfortunately... @Wafelack, is this the first time you've tried to set one, or has it worked in the past? Trying to understand more about what's happening here.

**Comment by Wafelack** [comment]
No it is the first time i tried.

**Comment by jryans** [comment]
@Wafelack Okay, thanks. I assume this happens every time you attempt to set a picture? What file format / type are you trying?

**Comment by Wafelack** [comment]
I'm trying with a .png file

**Comment by jryans** [comment]
@Wafelack Perhaps try some different files? Maybe something is wrong with the first one.

**Comment by andybalaam** [comment]
@Wafelack are you still seeing this problem?

**Comment by turt2live** [comment]
Closing as a presumably fixed issue. If folks are still seeing this, please open a new issue.
