### ISSUE TITLE
Unnecessary mouse hand when # of read receipts < 5

### ISSUE THREAD

**Issue by azizLIGHT** [vector-im/element-web#15548]
### Description

When hovering mouse over read receipts, the mouse turns into a hand indicating that it can be clicked. When the number of read receipts is greater than 5, clicking expands to show all read receipts. However, when the number or read receipts is 5 or less, clicking does nothing

### Steps to reproduce

- Wait for a new message and people to read it
- Before the number of read receipts goes over 5, click any of the user icons
- nothing will happen if the # of icons are less than 5

Describe how what happens differs from what you expected.

The mouse hand indicator implies something will happen when you click. If there is nothing to happen, the mouse hand shouldnt be there. The mouse hand should only appear when there is expansion to be done, ie: when the number of read receipts exceeds 5

Logs being sent: no

![Peek 2020-10-25 13-06](https://user-images.githubusercontent.com/8013867/97113774-e700fc00-16c2-11eb-82c1-b5c7509ce73d.gif)
### Version information

- **Platform**: desktop
- **OS**: Manjaro
- **Version**: 1.7.5

**Comment by t3chguy** [comment]
This is no longer relevant with the redesigned read receipts
