### ISSUE TITLE
Sync fails due to timeout in Firefox

### ISSUE THREAD

**Issue by jellykells** [vector-im/element-web#15545]
### Description

Sync fails only in Firefox. Logging out and back in temporarily fixes the issue. The error returned follows:
```
/sync error ORG.MATRIX.JSSDK_TIMEOUT: Locally timed out waiting for a response error-codes.js:44:4
    n error-codes.js:44
    methodFactory logger.js:45
    _onSyncError sync.js:677
    _sync sync.js:574
    _onSyncError sync.js:703
    (Async: promise callback)
    _onSyncError sync.js:689
    _sync sync.js:574
    e sync.js:424
    s sync.js:424
    e sync.js:478
    sync sync.js:478
    startClient client.js:4817
    start MatrixActionCreators.js:253
    re Lifecycle.js:276
    re Lifecycle.js:375
    Q DeviceListener.ts:235
    Q DeviceListener.ts:250
    loadSession MatrixChat.tsx:244
    (Async: promise callback)
    loadSession MatrixChat.tsx:242
    ge MatrixChat.tsx:1896
    (Async: promise callback)
    ge MatrixChat.tsx:1831
    React 12
    ne init.tsx:149
    59 index.ts:200
    59 index.ts:211
    Webpack 3

```

### Steps to reproduce

- visit Element Web using Firefox after logging in

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox 82
- **OS**: Arch Linux
- **URL**: self-hosted Element Web 1.7.10

**Comment by t3chguy** [comment]
Which matrix server are you connecting to? Likely they are running slow, that's where the timeout is from.

**Comment by jellykells** [comment]
@t3chguy I'm using a self-hosted homeserver, but I only encounter this issue when using Firefox.
If it is a server issue do you know why logging out and back in would work fine without timing out? I thought the initial sync was the most resource intensive.

**Comment by t3chguy** [comment]
Yes but it's also heavily cached
Can you reproduce this issue on a public server to verify it isn't related to your server?
Check the Firefox network tools too, they are good at saying why a request failed.

**Comment by jellykells** [comment]
Alright sure I'll attempt to reproduce it on another server.

**Comment by jryans** [comment]
So far, this seems like a server or network issue, so I will close this for now. Please let us know if there is more evidence to suspect a client problem here.
