### ISSUE TITLE
Sometimes switching to previous room clears composer content

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#15541]
### Description

I was writing a message in a room and halfway through wanted to refer to another message in the previous room I had viewed, so I did "alt-left" to go to the previous room and then "alt+right" to go back, and suddenly my composer had emptied itself.

When writing messages and clicking between rooms the composer doesn't empty itself, so switching rooms using hotkeys should probably not either.

### Steps to reproduce

- View room A
- View room B
- Start writing a message
- Press "alt-left"
- Press "alt-right"

Describe how what happens differs from what you expected.

Composer should contain message that was being written. It doesn't.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: nightly 2020102201

**Comment by jryans** [comment]
@jaywink Is this still the case for you? Just tried to test quickly on develop.element.io in Firefox, and composer content seems preserved... Maybe it's desktop specific...?

**Comment by jaywink** [comment]
Indeed, I can't seem to reproduce this anymore. Possibly fixed on develop? Now running nightly 2020102601

Anyway, closing, thanks!

**Comment by t3chguy** [comment]
I still see this sometimes, think its a race condition or similar. Not only with alt-left navigation.

**Comment by jaywink** [comment]
Yeah I've ran into this a few times as well after reporting not seeing it, just forgot to re-open this while cursing and rewriting a message :sweat_smile:

**Comment by SimonBrandner** [comment]
@jaywink, is this still an issue?

**Comment by jaywink** [comment]
TBH I've avoided using keyboard based room switching to previous room due to fear of losing the message. I'll try start doing that again. Wondering if @t3chguy has seen it recently as they we're the one reporting it also in November?

**Comment by t3chguy** [comment]
Hmm, I think there's another issue describing this which I re-opened as I had it happen to me in the past month or two

**Comment by jaywink** [comment]
I've been using keyboard navigation for a while and it feels reliable! And based on https://github.com/vector-im/element-web/issues/15541#issuecomment-873965674 we can probably close this until it comes up again, thanks!
