### ISSUE TITLE
Jitsi popout url contains untemplated variables

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#15551]
### Description

Cannot pop out jitsi window from app.element.io in firefox: i get this URL instead:

https://app.element.io/jitsi.html#conferenceDomain=$domain&conferenceId=$conferenceId&isAudioOnly=$isAudioOnly&displayName=$matrix_display_name&avatarUrl=$matrix_avatar_url&userId=$matrix_user_id&roomId=$matrix_room_id

### Steps to reproduce

- Visit a room with a jitsi video call in place
- Click the [arrow] link to pop out the widget
- end up with above URL in address bar.

Describe how what happens differs from what you expected.

I should get into jitsi conference.

### Version information

- **Platform**: web 1.7.10

For the web app:

- **Browser**: Firefox 81.0
- **OS**: Linux ubuntu
- **URL**:  app.element.io

**Comment by michaelkaye** [comment]
Update: Refreshing the browser page with app.element.io entirely causes the link to work normally.

But i did check in the config settings that I was on 1.7.10 at the time...

**Comment by turt2live** [comment]
Writing this off as a strange caching bug for now.
