### ISSUE TITLE
"Forget Room" button visually doesn't do anything

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15559]
It does the web request in the background, but the view doesn't update to show that the room has been forgotten. Refreshing/restarting the app fixes it.

This was originally considered not worthy of fixing because it was soon going to be replaced by https://github.com/vector-im/element-web/issues/14038

**Comment by SimonBrandner** [comment]
As far as I can tell you actually have to restart the app twice for it to disappear. I have no idea what could be the cause of this

**Comment by DC4JG** [comment]
Just had the same issue (desktop client), can confirm. Forget room feature seemingly does nothing (but correctly syncs and removes it on my android client). After a single restart nothing changed, the room still showed up, the second restart did the trick and the room vanished.

**Comment by chagai95** [comment]
just confirming that I too have to refresh the page at least twice.

**Comment by chagai95** [comment]
This is a slightly related issue, for those of you who might actually be looking for this:
https://github.com/vector-im/element-web/issues/18473
