### ISSUE TITLE
Unclosable "Jitsi Video Conference" box follows around the app

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15554]
![Screenshot 2020-10-26 at 11 42 29](https://user-images.githubusercontent.com/1197991/97168650-b1bae380-1780-11eb-81f5-41752cf5652f.png)

I would like to be able to close this box without joining the call.

**Comment by turt2live** [comment]
Version information? This is supposed to be fixed.

**Comment by benparsons** [comment]
Desktop `Element Nightly version: 2020102201`

**Comment by turt2live** [comment]
do you remember the steps it took to get the box to be there?

**Comment by benparsons** [comment]
* Call was started in a room I'm in
* I entered that room and clicked the widgets button at the top
* I joined the jitsi call, then exited
  * but the call continued
* I switched room
* box appeared

**Comment by turt2live** [comment]
when you exited, did you dismiss the feedback popup or were you still staring at it?

**Comment by benparsons** [comment]
I think it disappeared when the call was ended.

**Comment by turt2live** [comment]
I can't reproduce this. If someone has reliable reproduction steps, please post them.

**Comment by jaller94** [comment]
Happened to me now on staging today.
I have not been able to reproduce it so far. :confused:

**Comment by benparsons** [comment]
Pretty sure this no longer occurs - I don't remember seeing it.
