### ISSUE TITLE
Cannot decrypt messages from desktop on mobile after yesterday's update

### ISSUE THREAD

**Issue by kepi** [vector-im/element-web#15555]
### Description

Yesterday I updated Element on Android and I'm not able to receive new messages at least from Element desktop linux client (latest version 1.7.10). Old messages are ok, new messages displays only _Waiting for this message, this may take a while._

Messages from another Android arrives without any issue.

Tested on two accounts, two different mobile phones.

### Steps to reproduce

- write message on desktop client in encrypted channel (all sides verified)
- try to read it on android mobile

### Version information

- **Platform**: desktop 1.7.10 and android mobile (Oct 19, 2020)

**Comment by jryans** [comment]
@kepi Please submit debug logs (top left menu -> Settings -> Help & About -> Submit debug logs) and reference this issue so we can investigate further, ideally from both devices. It will be quite hard to investigate this unfortunately without more detail from the logs.

**Comment by kepi** [comment]
I tried but only way to submit debug logs is possible to create bug report with hand shake. I don't see *Submit debug logs* in specified path not anywhere else.

Anyway, not sure why/how but when I tried to send logs today I find out that problem is gone. I still can't see those previous messages but new ones arrives without any trouble, so closing this.

**Comment by jryans** [comment]
Glad it's resolved... for future reference, the logs submission UI looks like this in web / desktop:

![image](https://user-images.githubusercontent.com/279572/97442601-f03bd400-1921-11eb-8b4f-d3a22ef1317e.png)
