### ISSUE TITLE
guest with a direct link have its own messages accumulating at the bottom

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#15567]
### Description

Entering the server by [clicking this](https://riot.grin.hu/#/room/#tarsalgo:grin.hu) on a private browser, then start typing, and the result is something like that, using Firefox nightly on Linux:

![2020-10-26_22-00-50_screenshot](https://user-images.githubusercontent.com/1056054/97228501-51a35c00-17d7-11eb-9124-39ea6777fa4f.png)

The messages I type get sent, but stay on the bottom. The responses appear above them.

Reload fixes it until the next message. Can't clear cache since gues has no setup menu.

Describe how what happens differs from what you expected.

### Version information
- **Platform**: web 
- **Browser**: FF nightly on linux, private window
- **OS**: LInux debian/sid
- **URL**: https://riot.grin.hu/#/room/#tarsalgo:grin.hu

(Tried to search for it, haven't found a duplicate, but in case I have missed please help to connect them, thanks.)

**Comment by turt2live** [comment]
This is a synapse issue: https://github.com/matrix-org/synapse/issues/8521

**Comment by grinapo** [comment]
(Maybe not related, but leaving the room don't let me join again, it says "Join the conversation with an account / Sign up Sign In")
