### ISSUE TITLE
Jitsi widget broken with custom themes which contain spaces

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15571]
Created this issue to send my debug logs to.

In Element-Web `1.7.10` everything worked fine. The screenshot below shows the very same widget in the very same channel right after upgrading to `1.7.11` …

This is true for the scalar jitsi widget, the scalar custom widget as well as the `/addwidget` command.

<img width="920" alt="Screenshot 2020-10-27 at 11 06 23" src="https://user-images.githubusercontent.com/11408027/97287658-222b3880-1845-11eb-80cb-da1f82289924.png">

**Comment by t3chguy** [comment]
`Error setting up Jitsi widget DOMException: String contains an invalid character index.ts:131:16`
