### ISSUE TITLE
display target url on mouse hover

### ISSUE THREAD

**Issue by py-b** [vector-im/element-web#15572]
### Description

When there is a caption on an hyperlink, the target url should be displayed somewhere (task bar, tooltip...) on mouse hover.

### Steps to reproduce

- Create message with a link (here with markdown syntax) : `[CLICK HERE](https://github.com/vector-im/element-web)`
- Result : [CLICK HERE](https://github.com/vector-im/element-web)
- Hovering the link **without clicking** should indicate which url will be opened.

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.7.9 (olm : 3.2.1)

**Comment by t3chguy** [comment]
It is visible on right click btw

**Comment by py-b** [comment]
Thank you. If you think this is intuitive enough for the user, you can close this.

**Comment by t3chguy** [comment]
I'm just letting you know of existing behaviour, there is a more generic issue about how this should be handled better not only on desktop where we can do smarter things.
I think https://github.com/vector-im/element-web/issues/6532 tracks this issue more generically

**Comment by py-b** [comment]
Thanks again. Phishing was my concern indeed (I didn't see this issue when searching).
