### ISSUE TITLE
Jitsi and E2EE config in .well-known/matrix/client are ignored by element-desktop

### ISSUE THREAD

**Issue by behrmann** [vector-im/element-web#15587]
### Description

I have a standalone unfederated matrix server running at `foo.example.org` and an instance of element-web running on `bar.example.org`. Both foo and bar serve a `/.well-known/matrix/client` of this form
```js
{
  "im.vector.riot.jitsi": {
    "preferredDomain": "jitsi.example.org"
  },
  "io.element.e2ee": {
    "default": false
  }
}
```
and a `/.well-known/matrix/server`
```js
{
  "m.server": "foo.example.org:443"
}
```

The preferred Jitsi domain is also set in the element-web config file. 

On element web the proper Jitsi domain is used when opening a video chat via the "Video call" button, whereas on element-desktop `jitsi.riot.im` is used.

Setting an empty `preferredDomain` setting in the element-web config file or setting it to `jitsi.riot.im` uses `jitsi.riot.im` instead of the preferred Domain from `/.well-known/matrix/client`.

I've scoured the bug reports mentioning `well-known/matrix/client` and decided to open a new bug report after finding somebody describing the same problem in #13678, but no corresponding bug report.

### Steps to reproduce

- Install a non-federated synapse behind a nginx reverse proxy
- have nginx return
  ```
    location /.well-known/matrix/client {
        default_type application/json;
        return 200 '<above json>';
    }
   ```
   Same for `/.well-known/matrix-server`
- Check via curl that the well-known endpoints are served
- Point element-desktop to `foo.example.org` or go to `bar.example.org`
- Start a video chat in a room and see that the Jitsi room is on `jitsi.riot.im`

Describe how what happens differs from what you expected.

### Version information

- **Platform**: web and desktop
- **OS**: Arch Linux
- **Version**: 1.7.11
- **Browser** (only for the element-web case): Firefox 82

**Comment by t3chguy** [comment]
It looks like your well-known is in the wrong place, it should be at `https://example.org/.well-known/matrix/client` (and same for server for delegation to work) where `example.org` is the server_name from your Synapse config, and it is also used in your Identifiers, e.g your users are `@localpart:example.org`

**Comment by behrmann** [comment]
Ah, I had misunderstood the docs and thought `hostname` meant `foo.example.org` instead of `example.org`. Thanks for the clarification.
