### ISSUE TITLE
Reply state disappears when you change room

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15586]
### Steps to reproduce

- click to reply to a message
- start typing your reply
- click another room
- click back to the first room
- the *text* you typed is still present, but the reply-mode is no longer active

I would expect that reply-state be the same if the text is still there.

### Version information

desktop, nightly, macos Element Nightly version: 2020102201

**Comment by t3chguy** [comment]
Argh i thought I fixed this but turns out the order of the things happening during a room view change makes it not persist correctly :(
