### ISSUE TITLE
UX to open chrome dev tools in electron

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15585]
This is probably just me, but I _always_ forget the keyboard shortcut to open the chrome devtools in electron. Anything to make this easier would be appreciated.

I would also love for Element desktop to report where it is storing files on disk, since this seems very tricky to work out.

**Comment by jryans** [comment]
> I would also love for Element desktop to report where it is storing files on disk, since this seems very tricky to work out.

Please move this to its own issue, along with a hint of where you'd imagine such a report appearing.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/97432742-57eb2280-1914-11eb-8e4e-b3a75fdbc7dd.png)

You mean like the application menu :P?

**Comment by lampholder** [comment]
Hah, yeah, that's perfect :D Thanks.

**Comment by lampholder** [comment]
> 
> 
> > I would also love for Element desktop to report where it is storing files on disk, since this seems very tricky to work out.
> 
> Please move this to its own issue, along with a hint of where you'd imagine such a report appearing.

https://github.com/vector-im/element-web/issues/15612, thanks
