### ISSUE TITLE
Getting stuck at "Verify this login" when dismissing the "Use recovery key" dialog

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-web#15584]
### Description

It's possible to get stuck at "Verify this login" if you choose to confirm the session with a recovery key but then change your mind and press "Go Back".

### Steps to reproduce

- login to Element
- at "Verify this login" press "Use Recovery Key"
- press "Go Back" 3 times (one should be enough — bug)
- nothing can be done at this point, all you see is "Verify this login" text and a spinner

![2020-10-28_14-32-55](https://user-images.githubusercontent.com/184066/97430840-807e1700-192a-11eb-932a-818b292db40a.jpg)

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 86.0.4240.111
- **OS**: Debian Linux testing
- **URL**: https://develop.element.io

**Comment by jryans** [comment]
Thanks for the report, I can reproduce it here as well. I think it's okay for current release to go out without a fix for this, as this is not entirely broken, just quite confusing, and also the fix seems like it would be a bit nuanced and could use additional testing time on develop.

**Comment by gonzalloe** [comment]
I am also having the same issue where I get stuck at "Verify this login" when trying to verify the session using security passphrase. This happens on every time I re-login and try to verify the login session. Have to refresh the page to get it back to normal. But sometimes the session isn't verified at all. Is there any solution yet?

**Comment by jryans** [comment]
I've submitted PRs that fix this for me locally, but I'll need to test more flows next week to ensure I haven't disturbed anything else along the way. 😅

**Comment by jryans** [comment]
I think it's okay... let's see what happens!
