### ISSUE TITLE
Stop deliberately lying to the public

### ISSUE THREAD

**Issue by fakkunamae** [vector-im/element-web#15599]
**Is your suggestion related to a problem? Please describe.**
My "suggestion" is related to this remark and the remarks that this default server, Matrix.org, is private.
>Our mission is to preserve your right to privacy, in the face of an increasingly centralised internet, and routine surveillance.

**Describe the solution you'd like**
Removal of these statements, and a public apology for being con artists, who have blatantly rejected all peacible discussions on moving to different recaptchas after being made fully aware of the ability to do so and the security voulnerability being connected to google represents. 

**Describe alternatives we've considered**
None, despite being given 10s of them

**Additional context**
Lets not mince words here, you are not going to do this, and your work on this project easily represents yet another chilling honey pot for privacy minded people to be tracked and tagged by google by at least a marginal ammount. This kind of false privacy is not some mistake on your part but a deliberate action, and the development of this project exists to popularize an alternative that's not really an alternative, much like proton mail. There is no reason for any privacy minded company to use these services outside of ignorance, and you have objectively shown, as counter-intuitively is usual for this kind of situation, that you should never ascribe ignorance where malice suffices.

**Comment by ara4n** [comment]
dup https://github.com/matrix-org/matrix-doc/issues/1281, which is indeed on our radar, irrespective of what this bug's author might think.
