### ISSUE TITLE
Sometimes I can't send messages to particular users but sending messages to other users is fine.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15593]
Earlier it was messages to @turt2live; clear cache and refresh seemed to fix that but now it's a different user.

Console complains unhelpfully about CORS stuff:
![image](https://user-images.githubusercontent.com/1922197/97471332-83840200-1940-11eb-9c5c-e08ea656ce86.png)

But, my network tab doesn't show Element trying to send the message at all, and there are no errors at send time in my Synapse log.

**Comment by lampholder** [comment]
I should have said - in the UX you get this:

![image](https://user-images.githubusercontent.com/1922197/97472411-baa6e300-1941-11eb-854f-4b86bc17ac03.png)

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1531
