### ISSUE TITLE
Post-reg prompt to set a display name & pic

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#15606]
-----

**Effort + Impact**

Medium + High

<br> 

**Problem**

Users do not set names & avatars, making the platform feel less personable

<br>

**Solved looks like**

% of users with no displayname / avatar down

**Comment by t3chguy** [comment]
@gsouquet / @daniellekirkwood / @niquewoodhouse this borders on work you seem to be exploring right now

**Comment by gsouquet** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21946
