### ISSUE TITLE
Defer toasts, primary post-reg actions on finding rooms & people

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#15604]
**Effort + Impact**

Low-Medium + High

<br> 

**Problem**

We throw too many confusing prompts at users during onboarding. By lowering this we improve the signal-to-noise of how they can progress with the app and lower cognitive load.

<br>

**Solved looks like**

% retention up

**Comment by niquewoodhouse** [comment]
**1. Defer toasts**

Tested creating a new account on web and got 3 toasts.  It seems the following rules exist:

- Desktop notifications: asked for after you've created/joined your first DM/Room;
- Update Element: I guess when an update is ready? So nothing to do with a user's behaviour;
- Set up secure backup: asked for after you've created/joined your first DM/Room.

These are my first suggestions:

<img width="1440" alt="defer toasts matrix 1" src="https://user-images.githubusercontent.com/1587166/97697045-577e9300-1a9e-11eb-9327-92d51e1d2baf.png">

**Comment by t3chguy** [comment]
> Desktop notifications: asked for after you've created/joined your first DM/Room;

I believe it just happens when you log in/register regardless

> Set up secure backup: asked for after you've created/joined your first DM/Room.

This should be happening when you join your first encrypted room

**Comment by t3chguy** [comment]
You're also somehow missing the analytics toast, does your browser have doNotTrack enabled?

![image](https://user-images.githubusercontent.com/2403652/97697866-88ab9300-1a9f-11eb-8fee-9e4a3d9575de.png)

**Comment by niquewoodhouse** [comment]
@t3chguy my browser does have doNotTrack enabled yes.  When does this appear?

**Comment by t3chguy** [comment]
When you log in/register, same as the desktop notifications one

**Comment by t3chguy** [comment]
(equally both re-appear when you open a new session if you ignored them last time)

**Comment by niquewoodhouse** [comment]
thanks @t3chguy.  I don't think it makes sense for the analytics prompt to be a toast.  It's of no value to the user, whereas the other toasts are in some way (enable notifications, back things up), so I think it mixes things up a bit and our hypothesis is helping users easily get to value early on will increase retention.

**Ideas for that one:**

- Could we easily enough add a checkbox to this part of registration instead:
<img width="785" alt="Screenshot 2020-10-30 at 11 32 09" src="https://user-images.githubusercontent.com/1587166/97700395-a7ac2400-1aa3-11eb-9352-e62be25f40a0.png">

- Ask in a more emotive modal that blocks progress, as an example:
![image](https://user-images.githubusercontent.com/1587166/97700835-610af980-1aa4-11eb-95d1-9d9dbee7c896.png).  Would prefer the first one, open to other ideas.

**Comment by t3chguy** [comment]
That part of registration doesn't always exist, its server-dependent. Many servers don't expose their terms via it yet analytics will still be needed. It'd be tricky to conflate it into the UIA (User Interactive Authentication) flows as such

**Comment by t3chguy** [comment]
Plus that flow only happens during registration, what about users logging in, where would they be asked to consent as it is not synced between devices currently

**Comment by niquewoodhouse** [comment]
> That part of registration doesn't always exist, its server-dependent. Many servers don't expose their terms via it yet analytics will still be needed. It'd be tricky to conflate it into the UIA (User Interactive Authentication) flows as such

For this test, we could limit our changes to Matrix.org?  We just want to know if delaying/moving these early toasts in some way helps users get value. If it works, great - _then_ we come up with an idea that would help each server.

Or we could, considering this is supposed to be low effort work, just delay this one until day 2?

**Comment by t3chguy** [comment]
> For this test, we could limit our changes to Matrix.org? We just want to know if delaying/moving these early toasts in some way helps users get value. If it works, great - then we come up with an idea that would help each server.

We don't have any matrix.org-specific features in the App, matrix.org isn't hardcoded anywhere so this might be very controversial

> Or we could, considering this is supposed to be low effort work, just delay this one until day 2?

By doing this we'd be losing analytics from users at the start of their journeys so we'd be completely blind to when they fall off

**Comment by niquewoodhouse** [comment]
> By doing this we'd be losing analytics from users at the start of their journeys so we'd be completely blind to when/why they fall off. Without consent we can't store their actions for upload once they consent either.

@t3chguy do we know the % of users opting into analytics from this toast?  Are the tests we're currently running with analytics intended to replace this toast in some way, or is it expected this toast will remain? Thanks

**Comment by t3chguy** [comment]
> @t3chguy do we know the % of users opting into analytics from this toast? Are the tests we're currently running with analytics intended to replace this toast in some way, or is it expected this toast will remain? Thanks

Nope, it'd be fairly hard to tell as we'd have to correlate data between Matomo and web server logs, given that anyone can report to Matomo and it is a mess, it'd be very lossy.

The toast currently lets you ignore/opt-in
In future if we choose to proceed with Countly it may become tri-state: disable/stay anonymous/opt-in

**Comment by niquewoodhouse** [comment]
Ok, thanks for going through those suggestions with me @t3chguy.  Appreciate it.

Considering all the above I think we should leave the opt-in toast as it is for now then and just diminish it's importance by introducing more primary buttons to the screen, something like this (as a rough example).

<img width="1440" alt="basic example-1" src="https://user-images.githubusercontent.com/1587166/97714240-d2ed3e00-1ab8-11eb-827b-14ca9eb09e1d.png">

So my suggestion for the toasts:

- Anonymous usage toast: do nothing, _designer slowly backs away_ 
- Enable desktop notifications toast goes to after you type a message (and it's content is more about not missing a reply)
- Update Element toast delayed until day 2 (or some measure that means it won't appear in their first session)
- Secure backup toast: I'm a bit more vague on this one.  I'd like to delay it so it won't appear in the first session, regardless of if someone has joined/started an encrypted.  Maybe it should be the same as desktop notifications, and based on you having successfully sent a message.  Or having received 10 messages.  I'm not sure, just want to explore if there's ways to delay it being promoted to early users, especially as it's a slightly hard to flow - it could put people off.

**Comment by t3chguy** [comment]
Plan:

- [ ] Delay analytics toast by ~30s

- [ ] Defer Desktop notifications toast until the first of:
  + When you send a message and you are not the only person in the room (including invited): “Don’t miss a reply”
  + Day after register show the Desktop notifications prompt “Notifications”

- [ ] Defer Upgrade toasts if the user registered today (only show them from day after register)

- [ ] Leave the Secure Backup toast as it is

- [ ] Add new after-registration page

- [ ] Tweak existing default home page to make the buttons more obvious

**Comment by notramo** [comment]
What about completely removing the Secure Backup toast?
If the user has another session which has the keys, it is not needed because in case of logging out of either, the other has the keys. With the new cross-user key share request feature, the risk of losing access is even lower.
In case there is only one active session, there is already the logout Key Backup warning dialog.

**Comment by notramo** [comment]
What about not asking the Desktop Notifications in a toast, but automatically requesting it? (only in browsers) The browser will ask the user, and if the user rejects it in the browser's UI, then disable it in Element config.

**Comment by t3chguy** [comment]
There's no way of knowing if they still have access to the other session which has keys without asking them.

**Comment by t3chguy** [comment]
> What about not asking the Desktop Notifications in a toast, but automatically requesting it? (only in browsers) The browser will ask the user, and if the user rejects it in the browser's UI, then disable it in Element config.

This is considered impolite, and if a user clicks `Refuse` here then they have to dig deep within Browser settings to remove that rejection, the app can't re-prompt at that point.

**Comment by notramo** [comment]
> > If the user has another session which has the keys, it is not needed because in case of logging out of either, the other has the keys. With the new cross-user key share request feature, the risk of losing access is even lower.
> 
> There's no way of knowing if they still have access to the other session which has keys without asking them.
> Plus that doesn't concern the primary goal of this which is users which have just registered.

What about delaying it at least a few hours after registration? During this time, they maybe log in from mobile too.
Or maybe simply mention that if they log in from another device, the keys can be backed up there too.
