### ISSUE TITLE
Trial Count.ly for better analytics

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15608]
Including:
+ Cookieless analytics
+ Onboarding analytics
+ NPS user feedback

**Comment by resynth1943** [comment]
Hmm, just to confirm: you would be running your own instance, right?

**Comment by ara4n** [comment]
At the moment we're just experimenting with it as an alternative to Matomo, as we're trying to pinpoint where users are currently bouncing from the app and getting stuck doing so with Matomo.  For the initial evaluation of Countly we're using their SaaS offering, as there's zero point deploying it if it isn't going to work.  Obviously we're not going to release this until we've deployed our own and updated the privacy policies etc... *if* we switch to it.

**Comment by resynth1943** [comment]
Alright @ara4n, thanks for the explanation. 👍🏼
