### ISSUE TITLE
New user, first experience.

### ISSUE THREAD

**Issue by the-moog** [vector-im/element-web#15603]
**Is your suggestion related to a problem? Please describe.**
Users find the concept of URLs, 'servers' and 'identity stores' too complex and confusing.
They hate having to enter the name of the server when they first install the app.
Have a way to send a link that 'builds' a preconfigured app for the user.

**Describe the solution you'd like**
Have a URL link (and perhaps a QR) that delivers the user a preconfigured app for their platform.
No need to remember or (mis) type urls any more.

It could be nothing more than an on-ramp app that is downloaded first.

**Describe alternatives you've considered**
Trying to educate users.

**Additional context**

**Comment by jryans** [comment]
Thanks for the feedback! We're aware of these challenges, and I'll pass your feedback on to the Design team. I don't think it makes sense to track this as an issue, so I'll close it.
