### ISSUE TITLE
Videos say 'error decrypting video' when trying to play them with autoplay disabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15613]
The trigger for this appears to be disabling the autoplay gifs/videos setting, then trying to play a video. The video is *not* encrypted, so the error is wrong.

**Comment by turt2live** [comment]
Likely regressed by https://github.com/matrix-org/matrix-react-sdk/pull/5352

**Comment by turt2live** [comment]
(release blocker because there's a good chance it was introduced this cycle)

**Comment by Half-Shot** [comment]
Gah

**Comment by Half-Shot** [comment]
Playing the video causes `Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.`
