### ISSUE TITLE
copy & pasting an image to resend it converts jpegs to pngs

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15618]
which increases the filesize significantly for photos

**Comment by t3chguy** [comment]
I'm sad to tell you that this is your browser's doing; upon copying a jpg I only get an `image/png` in my clipboard 

![image](https://user-images.githubusercontent.com/2403652/97710652-efd34280-1ab3-11eb-83be-9ad6ecb1db66.png)
