### ISSUE TITLE
Reloading registration page with F5 key breaks the flow

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15616]
Sometimes it gets stuck because of network problems.
If it is timed out, and the page is reloaded, entered credentials are lost, and the progress of the flow is aborted.
It throws the user back to the server selection screen (complete restarting of the registration).
It can cause problems if an add-on (like uMatrix) blocks reCRAPTCHA, and after allowing it, the page have to be refreshed.

**Comment by t3chguy** [comment]
So you'd rather it store your entered credentials in plaintext? That'd be especially awful for users who reuse passwords between services

**Comment by notramo** [comment]
It should be stored in session storage, or somehow to persist between reloads, but after closing the tab, it should be deleted.
Or maybe only not store password, but everything else.
The following are not private:
- e-mail address (it is included cleartext in every email you get)
- selected server to register on
- Matrix username

So these fields could persist between reloads.

**Comment by t3chguy** [comment]
We now warn the user that data will be lost to prevent f5-ing
