### ISSUE TITLE
Search highlight breaks links

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#1561]
![screenshot from 2016-05-31 10 27 40](https://cloud.githubusercontent.com/assets/8428120/15669867/64d09fe8-271a-11e6-87ec-b6990c889f51.png)

This was on /develop:

```
Version 0.5.2
vector-dda212935444-react-a145ab7e285b-js-2c40932080f6
```

**Comment by SimonBrandner** [comment]
I will close this as I can not reproduce this. _Feel free_ to reopen or ping me if this is still a problem.
