### ISSUE TITLE
Indicate that the domain used for registration is not allowed for reCAPTCHA

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15617]
Google reCAPTCHA can only be used from one domain which the HS admin configures.
![kép](https://user-images.githubusercontent.com/26059643/97702629-3a9a8d80-1aa7-11eb-877f-0a84ef0bdc4d.png)
The error message says that the hosted Element (staging.element.io) is not valid for that server (matrix.grin.hu HS with riot.grin.hu hosted Element validated in reCAPTCHA).
This should be autodetected without filling the form. If reCAPTCHA will be needed in the registration flow, redirect it to the configured domain.

**Comment by t3chguy** [comment]
There is no way to query the list of whitelisted domains from Google.

**Comment by t3chguy** [comment]
> Google reCAPTCHA can only be used from one domain which the HS admin configures.

That is not true, you can (AND SHOULD) just allow it from all domains otherwise it won't work on Element Desktop which runs on `vector://vector`

**Comment by t3chguy** [comment]
Yup, this is impossible.
Even once it is rendered it is not possible.
Calling `getResponse` on it just returns `""` - same as if the user hadn't yet clicked the checkbox.

**Comment by notramo** [comment]
> There is no way to query the list of whitelisted domains from Google.

Then the admins should set it in the .well-known config. I know it can become inconsistent with the actual reCAPTCHA config, but it's better than nothing.
