### ISSUE TITLE
Cant edit sticker menu

### ISSUE THREAD

**Issue by Reglament989** [vector-im/element-web#15623]
### Description

Cannot edit sticker menu

#### Desktop
+ Open stickers menu
+ tap on three dots
+ edit
+ [ERROR] cannot connect to your homeserver
![element-bug-edit png](https://user-images.githubusercontent.com/52096394/97777320-1955a200-1b78-11eb-818c-b1aadca066f9.png)
```
TypeError: Cannot read property 'roomId' of null
at getScalarInterfaceUrlForRoom (vendors~init.js:2)
at b.open (vendors~init.js:2)
```
#### Mobile app
+ chat 
+ send sticker
+ edit
+ Work!

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: Element version: 1.7.12, olm version: 3.2.1

**Comment by jryans** [comment]
Hmm, I'm not able to reproduce this... @Reglament989, are you still seeing this issue?

**Comment by kojid0** [comment]
I can reproduce this issue. Let me know if I can help you figure out what's going on.

Being on matrix.org server
Version von Element: 1.7.16
Version von olm: 3.2.1

**Comment by rkfg** [comment]
In the current stable version on https://app.element.io clicking the options button causes reloading of the sticker widget with a similar error in the console: 
![2021-02-11_16-21-28](https://user-images.githubusercontent.com/184066/107641945-4ccebf00-6c85-11eb-8302-bfd6d9a3f252.png)

The only way to edit stickers is to open integrations from the room menu.

**Comment by SimonBrandner** [comment]
Hmm, I can reproduce this

**Comment by jryans** [comment]
I do see those console errors as well, it would be good to patch those up regardless of what happens with stickers here.

**Comment by rkfg** [comment]
I can only speculate but it seems that stickers are "integrations without a room" i.e. it's an omnipresent integration and the shared code doesn't like it when there's no room attached. Because the same widget (and integrations manager) works fine when opened from the room integrations menu where the roomId variable probably contains a valid value.

**Comment by SimonBrandner** [comment]
[This](https://github.com/SimonBrandner/matrix-react-sdk/blob/da93be467731f8cb518f7d339642095e4a38c6ad/src/components/views/context_menus/WidgetContextMenu.tsx#L52) line seems to be the problem. I don't know why

**Comment by rkfg** [comment]
Looks like the context menu is outside the RoomContext and that's why it doesn't have access to the currently opened room. It affects both the OP bug and what happens on my screenshot.

**Comment by t3chguy** [comment]
Hierarchy-wise it looks fine though

![image](https://user-images.githubusercontent.com/2403652/107677045-b654ca80-6c91-11eb-979c-8328663f8d16.png)

**Comment by rkfg** [comment]
Interesting. It doesn't look like that for me at all on `app.element.io`:
![2021-02-11_21-16-36](https://user-images.githubusercontent.com/184066/107680073-7223f300-6cae-11eb-9ed5-6af7926f99da.png)

It's completely outside the main tree and MatrixClientContext.Provider is a root element. Probably it jumps out of the tree if any sticker packs are selected?

**Comment by SimonBrandner** [comment]
Weird, I can reproduce what @rkfg has

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/107681179-a4c1f180-6c96-11eb-8627-bbda39f42836.png)

Yup. It does break once you add a strickerpack, because it uses a PersistedElement which is impossible to put in the right place hierarchically without a complex reverse-portal or real re-parenting approach

**Comment by rkfg** [comment]
I see. After I deleted the account data related to widgets and refreshed the page I indeed have the same hierarchy with this element inside the tree.

**Comment by t3chguy** [comment]
Is anyone still able to reproduce this? Lots of changes happened

**Comment by rkfg** [comment]
Seems to work fine now
