### ISSUE TITLE
apt autoremove removes element-desktop on ubuntu 

### ISSUE THREAD

**Issue by tigexplorer** [vector-im/element-web#15625]
### Description

If performing a `apt autoremove` on ubuntu, element-desktop will removed

### Steps to reproduce

Try to clean the installed packages on ubuntu with:

`sudo apt autoremove`

element-desktop is listed as not required

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 18.04 and 20.04

### Element was installed according the guide on

https://element.io/get-started

```
sudo apt install -y wget apt-transport-https

sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list

sudo apt update

sudo apt install element-desktop
```

**Comment by t3chguy** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/2403652/97861975-842fe600-1cfc-11eb-83b2-522095bedd40.png)

**Comment by tigexplorer** [comment]
After element-desktop was autoremoved, I've reinstalled it. Now, it's also on my machines no more in the list, like according your test.
Maybe, it was loosing it's dependancy after the change from riot-desktop?
