### ISSUE TITLE
Add a global "mute" button for Desktop version

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15628]
**Is your suggestion related to a problem? Please describe.**
When I'm on a video call on external jitsi Element bloop bloop sounds constantly. 

**Describe the solution you'd like**
Would be helpful to be able to mute the application without changing server-side notifcations.

**Comment by t3chguy** [comment]
You mean like this?
![image](https://user-images.githubusercontent.com/2403652/97878284-5788c800-1d16-11eb-954e-2fa62426c1ea.png)

**Comment by dbkr** [comment]
We could perhaps dig this out of settings and make it more like a silent switch (and make it include things like VoIP tones which it currently does not).

**Comment by benparsons** [comment]
I do mean like that! I would like that button to be higher up in the UI.

**Comment by askat86** [comment]
Hey, do you have any updates on this?
We like Element with Jitsi, but we would love to have the feature to mute ourselves for sneezes or coughs like in teamspeak with a self defined mute button. That is also nice if you leave your place and come back later. 

Important here is the functionality outside of the Element window. (global)

**Comment by benparsons** [comment]
"Do not disturb" mode is this.
