### ISSUE TITLE
Allow custom link text in markdown room links without alias/address …

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#15626]
It would be very helpful to allow custom link text for room links which don’t have a local/public address, e.g. `[some_custom_link_text](https://example.org/element/!forROOMnamesWITHOUTalias18723789:example.org)` …

Is there any chance of this being fixed?

**Comment by t3chguy** [comment]
It is purposefully not allowed for phishing reasons

**Comment by fooness** [comment]
While this totally makes sense for public servers, I think there could be an option for customizing/allowing this on homeservers.

**Comment by dbkr** [comment]
Referring to rooms by ID like this isn't going to work in the general case either. I think we'd want to find a better way to make this work (probably that didn't require the user to craft a markdown link to refer to the room). Also if you could use the template when filing issues, that really helps.
