### ISSUE TITLE
Emoji autocomplete now requires spaces between emojis

### ISSUE THREAD

**Issue by inducer** [vector-im/element-web#15635]
### Steps to reproduce

1. In the message composer, type `:thumbs<Tab><Enter>:thumbs`.
2. In previous versions (1.7.4-ish?), this used to open the emoji autocompleter a second time. Now it does not, unless you type `:thumbs<Tab><Enter><Space>:thumbs`.

This is particularly annoying since the Android mobile app (1.0.16) will only render emoji-only text enlarged if the text does not contains spaces (unlike Element web), which makes it difficult to type multi-emoji messages that render consistently across platforms.

### Version information

- **Platform**: web
- **Browser**: Firefox, 82.0.1
- **OS**: Debian testing/unstable
- **URL**: https://element.tiker.net, 1.7.12

**Comment by dbkr** [comment]
Looks like this actually changed in 1.7.0

**Comment by yannicka** [comment]
Is this still an issue? The behavior seems to have changed since then.

**Comment by SimonBrandner** [comment]
This still seems to be an issue, though we changed how emoji behave in the composer quite a bit
