### ISSUE TITLE
Problems with several error messages: Unable to decrypt

### ISSUE THREAD

**Issue by lvoss99** [vector-im/element-web#15630]
Dear community,

this is my first post, so please forgive me if I don't use every convention correctly.
I am using the element messenger and it is one specific group chat that I receive several different errors in about why I can't read the sent messages. Such as the following

** Unable to decrypt: Error: OLM.BAD_MESSAGE_MAC **

** Unable to decrypt: Error: Duplicate message index, possible replay attack: vT4f4OJSyZmjlObOmIE/CsZRY+saT4RGKhxEXA8oeSw|O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik|0 **

** Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !XdAQbEbtBibsXlkixO:digipeg.de, was !hyzVdkvmOKXVoNHWLm:digipeg.de) **

I have already rebooted the server what seemed to have fixed at least the second error for a couple of days. But then it reoccured now on a daily basis. The errors occur on group participants that are using the firefox browser version of the element messenger.

Have you any recommendations what to do about these issues?
I would really appreciate your help, thanks.

L

**Comment by turt2live** [comment]
Please use #element-web:matrix.org for support, not the issue tracker.

**Comment by lvoss99** [comment]
Thank you for your feedback. Do you suggest to post this in the repository element-web:matrix.org or something else?
