### ISSUE TITLE
Prompted to share identity with jitsi widget every time I open it

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15631]
![image](https://user-images.githubusercontent.com/1922197/97899257-f4f0f580-1d30-11eb-9743-00d0501c999b.png)

I can share more details about the deployment if necessary.

I can say that:
- the URL blurred out in that screenshot
- config.json's `integrations_jitsi_widget_url`
- config.json's `jitsi: preferredDomain`
- the domain hosting the element instance

are all different subdomains (dunno if that's relevant).

**Comment by t3chguy** [comment]
Do you make use of `Remember my selection for this widget` and it is not functioning as you expect?

**Comment by turt2live** [comment]
it came through as a report that the remember me button isn't working
