### ISSUE TITLE
Horizontally scrolling icon list underneath the search bar is not very useful

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15658]
### Description
Below the search field is a horizontally scrolling list of icons representing all my chats which constantly re-arranges itself:

![Screenshot_20201105_160331](https://user-images.githubusercontent.com/1097249/98306231-ab96e500-1f80-11eb-89b3-8273592c15f8.jpeg)

It appears to sort itself by recency of visitation, which does not seem useful. I've never once used it and the animation is rather distracting. Alas, there is no way to turn it off.

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by turt2live** [comment]
They can be turned off here:
![image](https://user-images.githubusercontent.com/1190097/98307069-3af0c800-1f82-11eb-87c5-b4e6d0cd9c54.png)

**Comment by Pointedstick** [comment]
Thank you! Somehow that description didn't connect with the feature in my mind.
