### ISSUE TITLE
Auto-scrolling to the latest message loses your place in the conversation

### ISSUE THREAD

**Issue by Pointedstick** [vector-im/element-web#15652]
### Description
When visiting a chat with a lot of new messages, you are automatically scrolled to the latest one, and there is a button to return to the oldest unread message. This requires manual action to resume your place and keep reading the conversation in the order that it happened, and can cause various bugs related to losing your place.

### Steps to reproduce
- Connect to a busy chat
- Switch to viewing a different chat
- Step away or quit the app
- Return to see, say, 150 new messages in the first chat
- Click on it

At this point, the view automatically scrolls to latest message. To returning the view to where it was before resume reading the conversation, you can click on the "jump to oldest unread message" button, or manually scroll there. However if you forget to click the button or manually scroll instead and don't quite reach the oldest message, then the internal state for "oldest unread message" does not get reset; then the next time you do click on the "jump to oldest unread message" button, it will take you to an ancient message form days ago and you will lose your place in the chat.

All of these problems would disappear if, when clicking on a room with a lot of unread messages, it did not auto-scroll to the latest unread message and instead left the view where it was before.

### Version information
- **Platform**: desktop
- **OS**: Linux: openSUSE Tumbleweed
- **Version**: 1.7.10

**Comment by t3chguy** [comment]
> When visiting a chat with a lot of new messages, you are automatically scrolled to the latest one

That is not the case. If you are scrolled up then that will be recalled when you return to that room.
Only if you are at the very bottom then you will be put to the new bottom

Sounds like you want https://github.com/vector-im/element-web/issues/11235

**Comment by Pointedstick** [comment]
> Only if you are at the very bottom then you will be put to the new bottom

Yeah, that's what I don't want. Indeed, seems like a duplicate of https://github.com/vector-im/element-web/issues/11235.
