### ISSUE TITLE
Give desktop users the ability to define their own local plugins using a scripting lanuage(or more)

### ISSUE THREAD

**Issue by farooqkz** [vector-im/element-web#15650]
**Is your suggestion related to a problem? Please describe.**
I want to do some processing on incoming messages for example or do some action when a particular message is received and a lot of other stuff which Element developers can't do for me(they are either my personal use case or Element developers don't have enough time adding all these features)

**Describe the solution you'd like**
A plugin system supporting a scripting language(Javascript or Python or both?) with access to all necessary APIs(permissions can be defined in manifest of a plugin).
 - Users should be able to install plugins by selecting their files(a ZIP archive?) which contain plugin files(including script files, media files and manifest).
 - There should be features which ease the task of creating and debugging plugins for plugin developers(e.g. verbose messages when exceptions occur, traceback, plugins which disappear after Element restarts and ...)
 - Optionally a marketplace in which developers can distribute their plugins(in multiple categories. rating would be good, too!)

**Comment by bsimjoo** [comment]
Yeah, I'm so agree. I need it!

**Comment by t3chguy** [comment]
What things would you want this to do you can't just write scripts using the Matrix API, maybe combined with user widgets or similar?

**Comment by bsimjoo** [comment]
I recommend to run a service that bind at a port on localhost. plugins can connect and do something!

**Comment by bsimjoo** [comment]
> 
> 
> What things would you want this to do you can't just write scripts using the Matrix API, maybe combined with user widgets or similar?

I need to create my own message narrator and S2T text input

**Comment by farooqkz** [comment]
I should think more on that and others should comment, too. My current ideas are:
 - Plugins which transform messages control how messages are delivered to users. They could automatically send messages back to Matrix server, too. Like in Hexchat (an IRC client) there are many scripts in which make a client act like a bot and at the same time controlled by a human.
 - Many plugins could use System API. Imagine a plugin which reads every incoming message with something like espeak or sends some requests to another server.
 - Many others could work with GUI(e.g. have buttons or commands)

These are just ideas from my limited mind. I am pretty sure use-cases of plugins are much more.

**Comment by dbkr** [comment]
Most of the above seems equally feasible using the client / server API: this really wouldn't be all that different to connecting to a service on localhost. Seems like you'd only need this if you wanted to alter the behaviour of element itself, which I don't think any of the above require?

**Comment by farooqkz** [comment]
I see your point. Closing this for now. I will message again if I thought it is something which should be added to Element itself.
