### ISSUE TITLE
Some images are not shown in the file list

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#15667]
### Description

I was searching for an image I knew was sent to a room I'm in in the past couple of days. I noticed it wasn't showing in the room's file list where it was supposed to be so I had to scroll backwards to find it.

I compared its event content with the event of another image that does appear in the file list. They differ in that the former file doesn't have `thumbnail_url` inside `content` and `thumbnail_info` inside `content.info` so I think this is the cause, but I don't have time to check right now.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.12

**Comment by turt2live** [comment]
Is the room encrypted?

**Comment by dkasak** [comment]
It's not.

**Comment by t3chguy** [comment]
Closing as duplicate of https://github.com/vector-im/element-web/issues/12490
