### ISSUE TITLE
riot.im/app is stuck on an ancient version of Element

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15669]
Loads of websites etc direct link to riot.im/app URLs - but it seems that riot.im/app is stuck on an ancient version of the app (1.7.1) rather than tracking the latest releases pushed to app.element.io (1.7.12 at current time of writing).

Given we can't 302 them to the new URL without losing their session, **please** can we keep riot.im/app using the same codebase as app.element.io?

**Comment by jryans** [comment]
I had somewhat purposefully left it on that specific version as it still contains the rebranding modal that tells you to change to the new domain.

In the past, we have had to manually update all 4 of staging Element, app Element, staging Riot, and app Riot separately, which gets to be annoying work after a while. I guess here you're proposing that riot.im/app points to app.element.io without any changes...? But should it still have a rebranding modal (which no longer exists in new versions, so would need to be revived), or does it just let you use riot.im/app to load Element without explaining anything?

**Comment by turt2live** [comment]
or have we hit a point where we can just 302/1 it?

**Comment by ara4n** [comment]
I'm suggesting we just mount the same app from riot.im/app at app.element.io without any changes. I don't care about the rebranding modal, which is an edge case now.  We can't just 302/1 it because we'll kick out a bunch of confused users.

**Comment by jryans** [comment]
This is now fixed: riot.im/app shows the same content as app.element.io without redirecting.
