### ISSUE TITLE
Living room named Empty Room for me and with another name for the others, which becomes empty, then disappears entirely

### ISSUE THREAD

**Issue by CEO-VISION-MatthiaS** [vector-im/element-web#15665]
### Description 

- Living room named Empty Room for me and with another name for the others, which becomes empty, then disappears entirely
- After logging in some rooms disappeared and the living room called Empty Room had ended up disappearing too

### Steps to reproduce

I don't know..

The name of the room should be the same for me as for the others and should not go blank and then disappear

### Version information

For the web app:

- **Browser**: 
Google Chrome
Version 86.0.4240.183 (Build officiel) (64 bits)

- **OS**: Windows 10 pro
- **Element Web**: 1.7.5

**Comment by turt2live** [comment]
1.7.5 is a bit old - please try a newer version, and if the problem persists then visit #element-web:matrix.org on matrix for troubleshooting.

**Comment by CEO-VISION-MatthiaS** [comment]
Hello, I currently have the same problem as last time but this time I can see it on the desktop app which is up to date

![Empty room](https://user-images.githubusercontent.com/70635044/101176779-400b6a80-3647-11eb-9b5d-d9fe7f58195d.JPG)

### Version information

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.14
