### ISSUE TITLE
Verification during login can be incredibly slow due to background initial /sync.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15673]
When you log in, the verification flow coincides with running the initial /sync in the background.  As a result, the browser is very busy, which is compounded by it emitting tonnes of keyshare requests because the session is not yet verified and has no 4S.  This conspires to slow down verification enormously on both the new login and your other devices (which are being DoSed by keyshare requests).

To fix it, I suggest we delay the main initial /sync until verification is complete, and starting off with a heavy filter so we only get the to-device msgs needed to do the initial verification.  While this might slow down initial sync a bit, it's worth it if the verification actually works.

See also https://github.com/vector-im/element-web/issues/15642 for a relatedish problem during verification at login.

**Comment by turt2live** [comment]
We need to sync to do the verification though?

**Comment by jryans** [comment]
This has changed somewhat after https://github.com/matrix-org/matrix-react-sdk/pull/5727, as now the flow has the new device sending the verification request. Still, it may be quite slow, as the sync is still happening as before.

**Comment by kittykat** [comment]
I'm going to close this for now as verification blocks on sync (which is still slow and we have a performance bug for that somewhere). This does mean that when the verification does eventually happen, it is at an acceptable speed.
