### ISSUE TITLE
Clicking Re-join on kick no longer provokes a visible spinner

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15679]
Clicking rejoin after being kicked seems to perform no visible UI action, although I can see the join requests going through in the logs.

https://chaotic.half-shot.uk/_matrix/media/r0/download/half-shot.uk/24abf08e4249618a7b29a6674ad1a4056c7dd878

Element version: 1.7.12

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/9850
