### ISSUE TITLE
adding screen share

### ISSUE THREAD

**Issue by CardboardTurtle** [vector-im/element-web#15671]
switched to this from discord, and i have only two issues so far. adding a screen share like in discord is the biggest one. so yeah screenshare pls, doesn't have to be good just has to be like 480p 15fps or something.

**Comment by t3chguy** [comment]
It is possible to screenshare already, using shift + click video call button or use the button inside Jitsi.
Closing in favour of caveat issues.

https://github.com/vector-im/element-web/issues/15040
https://github.com/vector-im/element-web/issues/4880
https://github.com/vector-im/element-web/issues/239

**Comment by mklhmnn** [comment]
I'm using the Element Windows desktop app and have the same issue - couldn't find the screensharing feature. I don't know what Jitsi is - did not see this name on the interface somewhere.
