### ISSUE TITLE
Inline bolding sends literal input not bolded text

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#15684]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

I wanted to send the three characters: \o/ with the last / bolded. In HTML it might look like this:

`\o<b>/</b>`

### Steps to reproduce

On element web

* Type `\o/` into the compose bar
* Select the final `/`
* Click B. 
* `**` appears around the final `/`
* Click send

Describe how what happens differs from what you expected.

The sent result is
`\o**/**` not `\o/` with the last character in bold.

Generated content is:
```
"content": {
    "body": "\\o**/**",
    "format": "org.matrix.custom.html",
    "formatted_body": "\\o**/**",
    "msgtype": "m.text"
  },
```

Logs being sent: yes/no

![bug](https://user-images.githubusercontent.com/1917473/98560669-eca03980-229f-11eb-9494-f00c15cea48a.png)

### Version information

- **Platform**: web 
For the web app:

- **Browser**: Firefox 81.0
- **OS**:  Ubuntu
- **URL**: app.element.io

**Comment by michaelkaye** [comment]
It's interesting that the same thing seems to apply on github:

\o**/** doesn't work

`\o**/** doesn't work`
but:

\o**x** does
`\o**x** does`

**Comment by t3chguy** [comment]
Yeah this is a markdown issue rather than an Element one, specifically can reproduce in Dingus https://spec.commonmark.org/dingus/:

![image](https://user-images.githubusercontent.com/2403652/98562297-cc717a00-22a1-11eb-91b5-cc89dbad7f2c.png)

**Comment by turt2live** [comment]
We've historically closed issues like this, so closing. Somewhere we have an issue for using GFM which can still receive 👍
