### ISSUE TITLE
Jitsi picture-in-picture (PIP) snagging list

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15682]
- [x] Read receipt avatars appear on top of the PIP
- [x] Message hover actions (reply, react, etc.) appear on top of the PIP
- [ ] Clicking the PIP doesn't return you to the related room (like it does when you click on the P2P PIP)
- [ ] The PIP looks like a strange grey rectangle if you have lots of participants and on grid view - it would be better to switch to whatever the opposite of grid view is called when you move to PIP:
    ![image](https://user-images.githubusercontent.com/1922197/98533695-3591c700-227b-11eb-9551-096413e7465e.png)

**Comment by turt2live** [comment]
The first two are https://github.com/vector-im/element-web/issues/15221

> Clicking the PIP doesn't return you to the related room (like it does when you click on the P2P PIP)

This is intentional so you can (un)mute yourself and generally interact with Jitsi.

**Comment by lampholder** [comment]
> This is intentional so you can (un)mute yourself and generally interact with Jitsi.

Makes sense, but:
- the Jitsi PIP needs to provide a way to return to its room; currently it doesn't
- users shouldn't have to think about Jitsi and P2P being different - if the "click to go home" UX can't work for jitsi, then we need something else that works for both

**Comment by lampholder** [comment]
It looks the PIP for p2p calls has been designed with exactly this in mind:
![image](https://user-images.githubusercontent.com/1922197/110317654-5a693180-8004-11eb-9c11-e9bd36fd43cb.png)

Is it on anyone's immediate agenda to apply this to jitsi calls, too?

**Comment by toger5** [comment]
I want to change the `CallPreview` class to `PiPContainer`. It is already used to either display the p2p call or a persistent widget.
I also want to reuse the container things: header/borader/goToAssociatedRoom button.
(the `PictureInPictureDragger`>`CallViewHeader` should also wrap the sticky PiP widget (the jitsi call))

Can this get signed of by design? @vector-im/design
