### ISSUE TITLE
Long mxids word-break weirdly when inviting a user to a DM

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#15695]
### Description

When attempting to invite
`@startTypingAndKeepOnTyping:matrix.org` to a PM, the text box doesn't fill with the name to the end and instead breaks onto a new line.

### Steps to reproduce

- Open the Start Chat and see the Direct Messages modal window
- type `@startTypingAndKeepOnTypin`

![starttypingandkeepontypin](https://user-images.githubusercontent.com/1917473/98711396-d5834980-237c-11eb-9def-da435b23cf65.png)
- type `g`
![g](https://user-images.githubusercontent.com/1917473/98711399-d61be000-237c-11eb-8e0a-275832712d75.png)

Describe how what happens differs from what you expected.

All should be on one line.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 81
- **OS**: Ubuntu
- **URL**: app.element.io

**Comment by t3chguy** [comment]
This is fixed on develop 
![image](https://user-images.githubusercontent.com/2403652/98711813-64906180-237d-11eb-82b7-4af1b4fcc51e.png)
