### ISSUE TITLE
"Go back" button in "Report a bug" dialog doesn't have any effect

### ISSUE THREAD

**Issue by nidico** [vector-im/element-web#15698]
Opening "Feedback" from the user menu opens a "Feedback / Report a bug" lightbox.

That lightbox contains a "Go back" button. Clicking on it doesn't have any effect. The only way to close the lightbox is to click somewhere beside the lightbox.

While at it, I'd suggest that the dialog should also be closed by pressing the escape key.

### Version information

- **Platform**: desktop
- **OS**: Debian Linux
- **Version**: 1.7.13

**Comment by dbkr** [comment]
Tested and indeed it does nothing (although the button is 'Cancel', and neither does the top right 'x')
