### ISSUE TITLE
Video previews don't work with autoplay disabled since 1.7.13

### ISSUE THREAD

**Issue by boogewooge** [vector-im/element-web#15694]
### Description

Since upgrading to 1.7.13, several different clients (both Windows and Linux) have been unable to play any uploaded embedded videos while the "autoplay gifs and videos" setting is off. Only while this setting is turned on, the videos work as expected.

With autoplay off, the player frame is shown, but all its function buttons are greyed out, black background and 0:00 timestamp.

The video is still downloadable via the link below. 

First client to upgrade to 1.7.13 reported this. Others reported no problems with 1.7.12 after this, then these very same clients reported the same problem after upgrading to 1.7.13 themselves.

**Update:** This only happens in encrypted rooms.

### Steps to reproduce

- Use element version 1.7.13.
- Turn off "Autoplay GIFs and videos" option under Settings -> Preferences.
- Try to watch any video in the embedded player. **Update:** While in an encrypted room.

### Version information

- **Platform**: Desktop
- **OS**: Windows, Debian
- **Version**: 1.7.13

**Comment by t3chguy** [comment]
Is this in encrypted rooms or both?

**Comment by boogewooge** [comment]
Only in encrypted rooms! Your hunch was correct. 

We just tested this in an unencrypted room and there the clients in question could watch embedded videos just fine.

**Comment by karlprieb** [comment]
I'm also having this issue. Only in encrypted rooms.
