### ISSUE TITLE
Unable to copy data from the room topic, if unable to edit room topic (textarea has disabled="")

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#15693]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

I want to join a room and copy a piece of information from the room topic. I don't have permission to edit the topic.

I am unable to use ^C or right-click to copy information from the grey-ed out "Room Name" or "Room Topic" boxes.

I don't think it's a human error because I can use ^C or right-click copy to copy the word "Room Addresses" on the room settings page.

It sounds like there is an attribute "readonly" that can be used instead of "disabled" to allow it to be part of the tab flow (for accessibility?) and also to be highlighted and copied from. Doing this means i can't edit the form field but I can tab to it, select and copy from it.

### Steps to reproduce

- Join a room that requires non-default level to edit the topic
- Go to the "Room Settings" page via the right hand panel
- Attempt to use ^C or right-click-copy to copy the room topic.
- Attempt to use `<tab>` to move to the text element.

Describe how what happens differs from what you expected.

I want to get the topic into my clipboard.

If i update the page via the inspector, and change `disabled=""` to `readonly=""` then the functionality I want is restored.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 81
- **OS**: Ubuntu
- **URL**: app.element.io

**Comment by t3chguy** [comment]
This is down to your browser, works on the Desktop app;

![image](https://user-images.githubusercontent.com/2403652/98701008-bb436e80-2370-11eb-8c0d-7d7800b8ad3c.png)

Closing in favour of https://github.com/vector-im/element-web/issues/9623
