### ISSUE TITLE
Joined room ended up in the Historical section

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15696]
![image](https://user-images.githubusercontent.com/2072976/98712492-49722180-237e-11eb-80f4-75b60f867dd7.png)

Element Desktop: 1.7.9

**Comment by t3chguy** [comment]
Can you please update and try to reproduce, additionally if you could check your sync response to see where the room falls, I don't think its possible for the room to be in the right place for this to occur.

**Comment by turt2live** [comment]
it wouldn't move because of the sync response - the room list actively ignores the section of the sync the room is in. Instead, it relies on the membership event.

**Comment by Half-Shot** [comment]
I've not seen this in quite a while. Tempted to close this unless someone else confirms it still happens.
