### ISSUE TITLE
Pinned widget visible in wrong room.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15705]
![image](https://user-images.githubusercontent.com/2072976/98854238-3466c280-2452-11eb-8b0d-9334ba4cbbee.png)

The room the widget is part of is: `!DrLYEBNfrhEncSEsSj:lant.uk`

But somehow it ended up showing in `!xYvNcQPhnkrdUmYczI:matrix.org`. Clicking and out of the room will cause it to always appear.

**Comment by lampholder** [comment]
I think I have this same problem - that same Bifrost deck appears for me in the Lightning Talks room :\ (it still appears for me in our DM, too)

**Comment by Half-Shot** [comment]
>that same Bifrost deck appears for me in the Lightning Talks room :\

Strangely it doesn't for me, only appears in the TWIM room and our DM.

**Comment by turt2live** [comment]
I believe this is fixed - if it continues, please open a new issue and submit logs.
