### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#15708]
![Screenshot from 2020-11-12 10-46-51](https://user-images.githubusercontent.com/10190/98923843-76384d00-24d4-11eb-8d48-38fac67b115a.png)

I got this today.

Running Firefox Nightly on Ubuntu in en-US.

**Comment by Yoric** [comment]
Note: after reloading, the error disappears.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/12591
