### ISSUE TITLE
Vertical spacing of the new welcome page is off

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15706]
We're not correctly vertically centring the Welcome to Element page (or presumably the "get started" page).  Particularly noticeable if your browser height is a bit short.

<img width="1227" alt="Screenshot 2020-11-11 at 20 35 05" src="https://user-images.githubusercontent.com/1294269/98861626-852fe880-245d-11eb-8d87-70ed6ed977dd.png">

**Comment by ara4n** [comment]
also:

<img width="626" alt="Screenshot 2020-11-11 at 21 06 01" src="https://user-images.githubusercontent.com/1294269/98864405-bca09400-2461-11eb-8d1b-ef86895242dd.png">

**Comment by t3chguy** [comment]
Ah yes, they used to look more sensible vertical before we gave them all backgrounds off-hover
