### ISSUE TITLE
Pinned jitsi widget for a video conference sometimes doesn't appear (if it's been added before I join a room) and I have to unpin/pin it to get it to appear.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15718]
I don't know if this happens every time, but it's happened frequently. I use the Element Nightly Desktop build.

Repro steps:
- somebody initiates a video conference, I think using the standard interface (clicking the video call button in a room with >2 people)
- I'm not in the room when they do that
- I switch to the room
- no widget at the top
- go to right panel, unpin, pin
- join the conference

**Comment by t3chguy** [comment]
Do you not have the `Show widgets` button available in the top right in that situation?
A widget can be pinned yet the whole widget section hidden.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/99068450-74d65580-25a4-11eb-83ad-48177c5f9a77.png)

**Comment by lampholder** [comment]
That's not how I'm expected to find a video conference, surely?

**Comment by t3chguy** [comment]
For the time being until the VoIP team put Jitsi where it belongs with some dedicated UI, yes
