### ISSUE TITLE
Ability to reply to email notifications.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/element-web#1572]

**Comment by ara4n** [comment]
Two ways of doing this: an email->matrix bridge, or 'reply' links on the notifs. We already have the latter, so I assume this is the former.  The bridge would not be easy though as if you have multiple notifs in the email, which are you responding to?

A better solution would be a separate email<->matrix bridge I suspect.

**Comment by t3chguy** [comment]
Moved to https://github.com/matrix-org/synapse/issues/12758
