### ISSUE TITLE
Allow to set a customized room invitation message

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15738]
**Is your suggestion related to a problem? Please describe.**

We are creating rooms from a widget and want to communicate more detailed information about the room on user invitation. 

**Describe the solution you'd like**

Allow to set some metadata on room creation to display a custom invitation message

![image](https://user-images.githubusercontent.com/2427106/99264559-e7ec0000-2820-11eb-917b-8f86cfba328c.png)

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/element-web/issues/7477
