### ISSUE TITLE
Add emoji which banging head against the wall

### ISSUE THREAD

**Issue by arch1tect0r** [vector-im/element-web#15736]
I'd like to have emoji which banging head against the wall like  [this](https://cs9.pikabu.ru/images/big_size_comm_an/2019-06_5/1561488758146013993.webm)

**Comment by t3chguy** [comment]
I suggest you open a request with the consortium then: https://unicode.org/emoji/emoji-requests.html

**Comment by arch1tect0r** [comment]
O_0 Something new to me. Thanks )
