### ISSUE TITLE
Find users Widget API function

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15747]
**Is your suggestion related to a problem? Please describe.**

We want to search for users from within a widget.

**Describe the solution you'd like**

The widget API should allow a widget to search for users and return a result containing username, display-name and picture of the users.

**Comment by turt2live** [comment]
@skolmer does this mean searching within the current room or across the entire homeserver?

**Comment by skolmer** [comment]
@turt2live Our use-case is to list and find users within the room of the widget.

**Comment by turt2live** [comment]
So I've proposed this as https://github.com/matrix-org/matrix-doc/pull/2876 as it allows one to grab all the `m.room.member` events in a room instead of us having a dedicated action for searching/finding users.
