### ISSUE TITLE
Hide rooms from room list

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15745]
**Is your suggestion related to a problem? Please describe.**

We are creating lots of child rooms from a widget that are accessible via the widgets own UI. These rooms are cluttering up the room navigation. We want to be able to hide rooms from the navigation.

**Describe the solution you'd like**

Allow to set some metadata on room creation that allows us to hide a room from the navigation

**Comment by turt2live** [comment]
This is likely to be more possible with the communities (spaces) rewrite - blocking this behind that.

**Comment by turt2live** [comment]
I think there's actually a way to not have this blocked - taking it on.

**Comment by turt2live** [comment]
well, that was surprisingly easy :s https://github.com/matrix-org/matrix-react-sdk/pull/5445
