### ISSUE TITLE
Provide language settings to the widget iframe

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15742]
**Is your suggestion related to a problem? Please describe.**

We want to show the same language in our widget as selected by the user in the element settings.

**Describe the solution you'd like**

Add the selected language to the URL hash of the widget's iframe. To be accessible as early as the widget loads.

**Comment by turt2live** [comment]
The MSC for this is https://github.com/matrix-org/matrix-doc/pull/2873
