### ISSUE TITLE
Remember identity verification for widgets

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15740]
### Description

When allowing a widget to access my user token I can select to remember my decision for the next time. Unfortunately my decision is not remembered and the dialog returns on every token request.

### Steps to reproduce

- Add a widget to the room that requires the users open id token
- A modals opens and asks if the widget can access my token
- Allow the widget to access your token and also set the checkbox to remember this decision
- Close the widget and re-open it

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.7.13

**Comment by lampholder** [comment]
We think that this was fixed - @skolmer are you still seeing this? If so, can you provide a minimal test case for us to reproduce?

**Comment by skolmer** [comment]
@lampholder I can't reproduce it on my local machine. I will talk to my colleges if someone can still reproduce it and which version they are using. If it can be reproduced in a 1.7.13 client I will let you know.

**Comment by Ais8Ooz8** [comment]
I can say that the decision is forgotten every time after log out. That is how it should be? 

Checked for  v1.7.23
