### ISSUE TITLE
Allow widgets to use maximum vertical space

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15741]
**Is your suggestion related to a problem? Please describe.**

In the current version of element the widget's vertical space is limited to leave about 5 text-lines below to the chat window. This really limits the space for video conferences on clients with small resolutions.

**Describe the solution you'd like**

Limit the widget space to only leave 1.5 lines of text visible in the chat room. This is enough to show that there is some content behind the widget and to indicate resizability of the widget.

**Comment by jryans** [comment]
The [maximised widgets project](https://github.com/vector-im/element-web/issues?q=label%3AZ-Maximised-Widgets) intends to make this possible, and is in development now, so there should hopefully be news here soon.

**Comment by toger5** [comment]
This is now at a stage were testing is possible. There probably are still some bumps but it might be worth mentioning, that there is a feature flag for maximised widgets in the labs settings (on develop)

**Comment by skolmer** [comment]
> This is now at a stage were testing is possible. There probably are still some bumps but it might be worth mentioning, that there is a feature flag for maximised widgets in the labs settings (on develop)

Great news, thanks for sharing! Is it something that is enabled for all widgets by default or do we need to implement something in the widget?

**Comment by jryans** [comment]
Maximised widgets are now [enabled by default on develop](https://github.com/vector-im/element-web/issues/20432) and on track to ship with the next release (planned for 17 Jan). 🎉 

I believe this feature addresses the core desire here, so I'll close this issue. For further refinements and tweaks, please file new issues.
