### ISSUE TITLE
Provide dark theme setting to the widget iframe

### ISSUE THREAD

**Issue by skolmer** [vector-im/element-web#15743]
**Is your suggestion related to a problem? Please describe.**

We want to show the same theme in our widget as selected by the user in the element settings.

**Describe the solution you'd like**

Add the selected theme to the URL hash of the widget's iframe. To be accessible as early as the widget loads.

**Comment by t3chguy** [comment]
This is already possible, just use `$theme` in your Widget URL and it'll get populated with light/dark

**Comment by skolmer** [comment]
@t3chguy @turt2live The suggested solution is working fine for sidepanel and room widgets but if I set the URL parameter for a modal widget it is not being replaced. 
I think this will be solved by https://github.com/matrix-org/matrix-doc/pull/2873 or should I open another issue?

![image](https://user-images.githubusercontent.com/2427106/99957741-795ef300-2d88-11eb-93e4-e30a4db97dfd.png)

![image](https://user-images.githubusercontent.com/2427106/99957594-3e5cbf80-2d88-11eb-9887-63b037c90ccf.png)

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-doc/pull/2873 is one option, though in practice might take a bit longer to implement. https://github.com/vector-im/element-web/issues/15800 is the issue for tracking it for now.
