### ISSUE TITLE
Room list seems to often show N-1 rooms when N is small

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15756]
I have a private server account where i'm in ~8 rooms (4 DMs and 4 rooms or so).  The room list often seems to only show 7 though, which means i have to manually expand the sublist to see all of them, which is clunky at best

**Comment by dstaley** [comment]
It's especially annoying when you have a large amount of vertical space in which to show rooms, and _incredibly_ annoying when the one room that's not shown is the room triggering an unread notification 😛

![image](https://user-images.githubusercontent.com/88163/103313992-864db280-49d6-11eb-9988-964c9cdeeb51.png)
