### ISSUE TITLE
clicking on the room header no longer takes you to settings, but unexpectedly toggles the rightpanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15755]
i can't think of any world in which it's helpful for clicking on the room header to hide the rightpanel. can we go back to it taking you to the settings view, so operations like setting topic & name & avatar is a single click?

**Comment by nadonomy** [comment]
Ah, I hadn't quite realised we'd changed this interaction (or; I have amnesia).

I'm not sure that clicking on the room header to enter settings is intuitive, and think we'll end up double handling this when we look at improving the room header with iconography, exposing the number of people in the room, etc.

That said, it's no less usable than toggling the info panel, so would be happy for us to revert Title -> Settings until we get round to improving room decoration in earnest.
