### ISSUE TITLE
Unable to decrypt messages after log back in

### ISSUE THREAD

**Issue by nikeshvpatel** [vector-im/element-web#15752]
Hello Folks,

I need help to understand what should I do in order to tackle this issue.

Issue:
8:00 A.M. to 4:00 P.M - use element without any issue.

04:01 P.M. -- log out from element. due to end of shift

Next-Day......

08:00 A.M. -- security key is attached while login and unable to decrypt messages which were sent between 04:00 P.M. yesterday to 08:00 A.M. today

now how to solve this issue.

**Comment by t3chguy** [comment]
If you have 0 other sessions then there are no e2ee devices for messages to be encrypted for. An upcoming feature called dehydration will help you but otherwise I suggest logging in on another device if possible.

See https://github.com/vector-im/element-web/issues/2286#issuecomment-299532155
