### ISSUE TITLE
Couldn't terminate video call

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15759]
What happened:
- Alice tried to use the 'easter egg' screenshare feature - didn't seem to work
- My Element sessions (two of them) rang and the event said it as a voice call
- My Element sessions rang out
- Alice set up a jitsi widget
- I initiated a 1:1 video call very shortly after
- Call connected successfully, great success
- I clicked 'End conference'
- Call would not end
- Alice couldn't end the call either
- Awkward permanent video connection

**Comment by t3chguy** [comment]
So this is likely a combination of undefined behaviour when there is both a Jitsi and Matrix call + https://github.com/vector-im/element-web/issues/15454

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
