### ISSUE TITLE
Unlock login keyring window when run element-desktop in Debian 9

### ISSUE THREAD

**Issue by iago-pssjd** [vector-im/element-web#15764]
### Description

When I run element-desktop on debian 9 (from Applications menu or from command line), I get the `Unlock login keyring` window, the same you can see here. 

![ulk2](https://user-images.githubusercontent.com/40892925/99531595-4345fb80-29a3-11eb-87b7-b7c79ccee9f3.png)

It asks for a password to unlock my login keyring. I can remove it through `Cancel`, but it is annoying. Further, when I Cancel it, a message appears as you can see in the last line below:
```
:~$ element-desktop
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
/home/iago/.config/Element exists: yes
/home/iago/.config/Riot exists: no
xdg-settings: default-url-scheme-handler not implemented for xfce
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
** Message: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection

```

This is an issue that also happens with chromium based browsers, and as explained in https://tipsonubuntu.com/2017/12/20/google-chrome-asks-password-unlock-login-keyring/, for browsers like `opera` or `brave` I can solve it adding to the run command the option `--password-store=basic`, but it does not work with `element-desktop`.

I would expect this window does not appear. Otherwise, having such an option as above to avoid it.

Thank you!

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian 9
- **Version**: 
Element version: 1.7.13
olm version: 3.2.1

**Comment by t3chguy** [comment]
The keyring is used to store a pickle key which is used to secure the encryption (megolm session) keys which are stored on your disk. If you do not store that pickle key in the keyring then these keys will be stored in plaintext on your disk and this is not recommended.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/15683

**Comment by iago-pssjd** [comment]
Thank you, finally I have [found](http://forums.debian.net/viewtopic.php?f=6&t=21477&hilit=%27login+keyring%27) the problem, which would be that the gnome keyring is not activated when used with a display manager not being `GDM` like in my case would be `lighdm`. 

Then, if `element-desktop` uses the GNOME keyring, are there other possible keyrings to use? Otherwise, what could be do through the installation process?

Please, feel free to close the issue if you believe you cannot do anything for it.

Thanks again.

**Comment by t3chguy** [comment]
Keytar supports any keyring via the Secret Service API/libsecret https://wiki.gnome.org/Projects/Libsecret
