### ISSUE TITLE
Message Search section of security settings shows [Object object] in desktop nightly

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#15766]
Something seems wrong here:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/279572/99538666-30ccc180-29a5-11eb-958b-897f0cbde87a.png">

**Comment by lampholder** [comment]
I see this instead:
![image](https://user-images.githubusercontent.com/1922197/99539073-b0f32700-29a5-11eb-88ff-bb06fe93a520.png)

On Element Nightly version: 0.0.1-nightly.2020111701 and then also on 0.0.1-nightly.2020111801

**Comment by jryans** [comment]
> I see this instead:

That seems like a separate issue where Seshat's database is confused, see https://github.com/vector-im/element-web/issues/15168.
