### ISSUE TITLE
Clicking "All rooms" in the room directory modal closes it

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15761]
Steps are clicking on the domain dropdown, then "All rooms". Error in the console about instances.

**Comment by t3chguy** [comment]
Out of spec room directory response, `instances` is undefined.

`2020-11-17T16:41:09.344Z E e[n].instances is undefined`

https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-thirdparty-protocols states it is Required
