### ISSUE TITLE
Jitsi screenshare didn't work, error message for the sharer was rubbish.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15760]
- Alice shared her screen with me in Jitsi (1:1 call)
- I got a black rectangle (no error message)
- Alice saw ![image](https://user-images.githubusercontent.com/1922197/99406532-e6384000-28e5-11eb-994d-3f79c32ec7b1.png)

**Comment by t3chguy** [comment]
I'm not sure there is anything we can do about Jitsi's internal error messaging.

**Comment by turt2live** [comment]
we need to identify why screensharing is suddenly broken though

**Comment by t3chguy** [comment]
Closing as an outdated upstream issue, if you keep seeing issues like this please open a ticket in https://github.com/jitsi/jitsi-meet
