### ISSUE TITLE
Allow Changing of a Display Name for other Users Locally

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#15778]
**Is your suggestion related to a problem? Please describe.**
Other users sometimes set display names(or lack thereof) that I would prefer to be changed. Sadly though, you can't change other users' display names

**Describe the solution you'd like**
Make it where you can change a user's display name, and only have that name display for the current account that's logged in. This would allow users to change other user's names locally on their account without it changing for other users.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/element-web/issues/3130
