### ISSUE TITLE
room_id is shown instead of in reply to is shown

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15773]
![image](https://user-images.githubusercontent.com/14617699/99668913-6645dd80-2a7f-11eb-9a9d-a08cf3b19a35.png)

I dunno how to reproduce this, know only that the message was send from element ios.

element 1.7.13 (web and electron)

**Comment by t3chguy** [comment]
This is that client sending an invalid edit event which includes the reply fallback wrongly, against the spec. I suggest opening an issue with that client.

**Comment by 532910** [comment]
https://github.com/vector-im/element-ios/issues/3820
