### ISSUE TITLE
Filter room list by rooms I've typed in the composer but not sent

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15772]
**Is your suggestion related to a problem? Please describe.**
I've just had a fast customer call where I ended up using the composer in various rooms to take notes, because those notes would become questions sent into those rooms.

**Describe the solution you'd like**
A button that makes the room list show only rooms with unset composer content. Works like the communities buttons do today.

**Describe alternatives you've considered**
The breadcrumbs almost suffice for this task, but my breadcrumbs quickly overflow from clicking around.

**Comment by jryans** [comment]
It seems interesting conceptually... I think the largest hurdle would be working out what a sensible button might look like and where it would go.

**Comment by benparsons** [comment]
I'm not sure this is very helpful. Would have been very helpful to me one time, but that doesn't mean it needs to be a feature. Would vote to close.

**Comment by turt2live** [comment]
I think this would be better solved with something like https://github.com/vector-im/element-web/issues/14181 or https://github.com/vector-im/element-web/issues/11838
