### ISSUE TITLE
Email validation doesn't match RFC 3696 on email addresses

### ISSUE THREAD

**Issue by okc-prof** [vector-im/element-web#15777]
### Description

Email validation is too strict disallowing addresses that're valid.

<img width="1006" alt="Screen Shot 2020-11-19 at 1 17 20 PM" src="https://user-images.githubusercontent.com/73511667/99725544-26c0c680-2a6a-11eb-975f-6b2eabc1e4ba.png">
<img width="714" alt="Screen Shot 2020-11-19 at 1 18 17 PM" src="https://user-images.githubusercontent.com/73511667/99725559-2a544d80-2a6a-11eb-9325-cc9b4855508a.png">
<img width="850" alt="Screen Shot 2020-11-19 at 1 18 37 PM" src="https://user-images.githubusercontent.com/73511667/99725561-2aece400-2a6a-11eb-9ff7-e359b84479cb.png">
<img width="600" alt="Screen Shot 2020-11-19 at 1 31 36 PM" src="https://user-images.githubusercontent.com/73511667/99726632-8f5c7300-2a6b-11eb-95f8-03976a268f2d.png">

### Steps to reproduce

Enter an email address that contains one or more of `?` or `=`.

**Comment by t3chguy** [comment]
Ftr the right rfc is RFC2822 - RFC3696 just references it and pulls some examples
