### ISSUE TITLE
yarn start:js exited with code SIGTERM error Command failed with exit code 1.

### ISSUE THREAD

**Issue by nashi24** [vector-im/element-web#15774]
### Description

this error comes on yarn start in element web folder only after 94% completion
yarn installation works well

2020-11-19 23:01:18.721 [riot-js] <s> [webpack.Progress] 93% after chunk asset optimization
2020-11-19 23:01:18.721 [riot-js] <s> [webpack.Progress] 93% asset optimization
2020-11-19 23:01:18.721 [riot-js] <s> [webpack.Progress] 94% after asset optimization
2020-11-19 23:01:18.722 [riot-js] <s> [webpack.Progress] 94% after seal
2020-11-19 23:01:18.777 [riot-js] yarn start:js exited with code SIGTERM
error Command failed with exit code 1.

error Command failed with exit code 1.

### Steps to reproduce

-Run yarn start

Describe how what happens differs from what you expected.

Logs being sent: yes

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: , Ubuntu
- **Version**: 16.04
- **Node**: 10.17.0
- **Yarn**: 1.21.1

**Comment by turt2live** [comment]
it looks like you've run out of memory on your system. Visit #element-dev:matrix.org for further troubleshooting.

**Comment by nashi24** [comment]
system has 8 GB RAM, I don't have any other project installed. Then how I am getting this space error.

**Comment by SimonBrandner** [comment]
I've created a StackOverflow question as this isn'ŧ an `element-web` issue.  More info [here](https://stackoverflow.com/questions/64919108/error-emfile-too-many-open-files-watch-unless-i-use-sudo).

**Comment by SimonBrandner** [comment]
@nashi24 I think I've solved the problem. Here's the [answer](https://stackoverflow.com/a/64941113/10822785). Did it work for you? If not make a comment on StackOverflow, so that we don't unnecessarily annoy the devs here.

**Comment by nashi24** [comment]
Yes that worked. Thanks!
