### ISSUE TITLE
Show all Users from Homeserver

### ISSUE THREAD

**Issue by thomas81x** [vector-im/element-web#15783]
When i want to create a direct message to a new user on the same homeserver i have to search for the user with @xyz:test.test.com. This is to difficult for some users. Is there any option to list all Users on that homeserver without typing the hole Usersearch?

**Comment by t3chguy** [comment]
Nope, the user_directory API does not give that.
Furthermore by default Synapse only lets you search for users you have rooms in common with or users which are in public rooms.

For support use http://matrix.to/#/#element-web:matrix.org

**Comment by hex-m** [comment]
The [spec](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-user-directory-search) says:
> The homeserver may determine which subset of users are searched

So this would be a feature request for Synapse or other Homeserver implementations.

In the meantime you can use [ma1sd](https://github.com/ma1uta/ma1sd/blob/master/docs/features/directory.md) to make all local users available in the user directory.
