### ISSUE TITLE
Full harddisk kills keys and renders all chats unusable(?)

### ISSUE THREAD

**Issue by c33s** [vector-im/element-web#15788]
### Description

had a running riot 1.6.0 installation with working keys and working chats (not backuped on server because of #13685). was away from my computer for a few hours while i made a download. have not noticed that my harddisk was running full.  no error was shown from riot. another different app complained about not being able to write to disk. i freed up the space again. 
later that day i received a message in riot which was showing me:

> ** Unable to decrypt: The sender's device has not sent us the keys for this message. **

the previous messages where still readable. thought it might was because of the full harddisk. restarted the riot. now my whole history is gone. every message now shows this error message.

looks like riot rotated some keys and has not checked there is enough space on the disk which also killed my previous keys.

think this should not be like that.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.6.0

**Comment by turt2live** [comment]
1.6.0 is unsupported. There's not much we can do about keeping the history when the browser (electron in the case of the desktop app) decides to purge the data - https://github.com/vector-im/element-web/issues/4014
