### ISSUE TITLE
Deleted messages still appear in the room list message preview

### ISSUE THREAD

**Issue by benbz** [vector-im/element-web#15782]
### Description

![image](https://user-images.githubusercontent.com/1325121/99806835-7a004b00-2b36-11eb-8b79-863546db82f5.png)

### Steps to reproduce

- Have message previews turned on
- Someone posts message in room and then redacts it
- Un-redacted message still in room list message preview

This was experienced using Element Desktop, but when opening an Element web session that hadn't been opened for days the message preview for this room was still the un-redacted message.

I would expect either to see Message deleted in the preview or whatever should be in the preview if neither the original message or redaction were ever sent.

Related to # #14872 ?

### Version information

- **Platform**:  Desktop & Web
For the web app:

- **Browser**: FF 83
- **OS**: Ubuntu
- **URL**: Private 1.7.13

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.7.13

**Comment by t3chguy** [comment]
This looks like it is the issue you linked completely, as the message you show was likely edited before being redacted, and redactions do not affect all instances of the message. 

Testing with a redaction alone it does not happen:

![image](https://user-images.githubusercontent.com/2403652/99807690-c5ffbf80-2b37-11eb-942c-11fcbe08b3c3.png)

**Comment by benbz** [comment]
I think you're right. Looking the source of the events below, there's `m.relates_to` -> `rel_type: m.replace`. I can't reproduce with a simple message -> delete flow.

![image](https://user-images.githubusercontent.com/1325121/99809336-09f3c400-2b3a-11eb-9cfd-c9eb4ecc25e5.png).

/me resolves and follows #14872 instead
