### ISSUE TITLE
Distorted audio on voice/video call

### ISSUE THREAD

**Issue by aethralis** [vector-im/element-web#15780]
### Description

I call another element user via voice or video calling within the desktop or web app.
The other side hears me perfectly.
On my side the video is fine, but I hear distorted unintelligible voice (squeaky? chipmunky?). 

Through google duo, google meet there are no problems.

### Steps to reproduce

- Call user

### Version information

- **Platform**: both on web (in-browser) and desktop.

For the web app:

- **Browser**: Firefox 83.0
- **OS**: Ubuntu 20.04
- **URL**: app.element.io

For the desktop app:

- **OS**: Ubuntu 20.04
- **Version**: element 1.7.13

**Comment by jryans** [comment]
@aethralis Hmm, interesting, I don't think we've heard this feedback generally... Are you able to try a different browser or device to see if the same thing happens there?

**Comment by aethralis** [comment]
This maybe a network issue, as today it once connected exactly as before (distorted) and the second time I tried (via desktop app) the audio worked fine. This mostly happens with one specific user, other users are fine.

**Comment by jryans** [comment]
Hmm, okay, in that case, it sounds most likely to a be system or network issue related to that one user, and I don't know there's much Element as a product can do.

**Comment by aethralis** [comment]
Could be, however google meet has worked without problems - so there must be also some Element specific quirk somewhere.

**Comment by jryans** [comment]
It may be hard to investigate this issue, but let's try to collect some more details on this.

What client and version is the other user with distorted audio using?

Please also submit debug logs (top left menu -> Settings -> Help & About -> Submit debug logs) yourself and ask the other user to also do so. When submitting logs, you can reference this issue so we can investigate further.

**Comment by aethralis** [comment]
It increasingly seems to be network issue, I've had similar distorted audio now also on google meet, so it seems that it is not element specific.

**Comment by jryans** [comment]
Okay, with that in mind, I don't think there's much we can do here in Element, unfortunately. Hopefully resolving the network issues will fix it here as well.
