### ISSUE TITLE
Videos do not work in any Chromium verison of Element, including Element Desktop

### ISSUE THREAD

**Issue by compu42** [vector-im/element-web#15789]
### Description

When using Element on Chromium, or in the Desktop application (which is Chromium-based), videos cannot be played by the user. It doesn't matter if the user sent the video or if it comes from another user. This forces the user to download the video to watch it. This does **NOT** appear to happen in Firefox, or in unencrypted rooms for some reason.

### Steps to reproduce

- Create or join an _encrypted_ room with any number of users, or no users but yourself.
- Send or receive an MP4 or WEBM (there could be more formats with this problem, haven't checked.)
- See this (note that the video dimensions are correct, and in some cases, the thumbnail can be seen.)
![image](https://user-images.githubusercontent.com/56663749/99881056-4e9d5f00-2c0f-11eb-99fc-950edc05d43b.png)
- The user cannot press play or use any of the player controls
- The user must download the video to watch it.

Logs being sent: no

### Version information

- **Platform**: Web + Desktop

For the web app:

- **Browser**: Chromium Version 86.0.4240.198 (Developer Build) Fedora Project
- **OS**: Fedora Linux 33
- **URL**: https://app.element.io | Element version 1.7.13

For the desktop app:

- **OS**: Fedora Linux 33 using Flatpak(possibly on other OSes as well)
- **Version**: 1.7.13

**Comment by t3chguy** [comment]
This is already fixed on Develop and will be included in the next release.
