### ISSUE TITLE
Active call indicator is broken

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15787]
When swithcing to another room.
![kép](https://user-images.githubusercontent.com/26059643/99860799-10129080-2b8c-11eb-9b56-4d00628d47ec.png)

**Comment by dbkr** [comment]
Is this referring to the fact that the 'T' is off-center? It's not really clear what exactly this is referring to. *Please* use the template when reporting bugs: it really helps to provide the right information.

Either way though, this has all just been replaced the other day, so closing this issue.
