### ISSUE TITLE
Message previews not shown at launch

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#15793]
### Description

I have "Show previews of messages" enabled for all sections of the room list, and they normally display as expected. However, whenever I open or reload Element, no message previews are displayed until I take some manual action to update the room list UI, such as activating a community filter or toggling message previews off and back on.

### Steps to reproduce

- Enable message previews
- Reload Element
- Toggle a community filter on and off to make them appear

Message previews should be loaded in automatically without having to interact with the room list.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox 83.0
- **OS**: Debian bullseye
- **URL**: https://app.element.io/

**Comment by robintown** [comment]
I can no longer reproduce this issue in 1.7.14.

**Comment by robintown** [comment]
Hmm, actually I'm getting this bug quite frequently again. Whereas it wasn't entirely reliable to reproduce before, I can now reproduce it 100% of the time just by refreshing the page (using 1.7.24).

**Comment by turt2live** [comment]
Please open a new issue with new logs - this one will have fallen off all applicable trackers.
