### ISSUE TITLE
Filtering by community/group does not filter out rooms in which you are alone

### ISSUE THREAD

**Issue by Midar** [vector-im/element-web#15791]
### Description

Filtering by community/group does not filter out rooms in which you are alone.

### Steps to reproduce
Create a new room. Be the only person in it. Select a community.

Any community now contains that room in which you are along.

Expected: Rooms in which you are alone and which are not part of a community are not shown when filtering by community.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 83
- **OS**: macOS
- **URL**: localhost, 1.7.12

**Comment by anna2828** [comment]
Read me

**Comment by jryans** [comment]
Hmm, I attempted to reproduce this, but when I clicked a community in the far left bar, the new room is filtered away as expected.

@Midar, can you include a video that show the steps you are taking?

**Comment by Midar** [comment]
Interesting - I tried on app.element.io (to not leak PII), and there I cannot repro it.

**Comment by Midar** [comment]
Only one specific room was affected by it. I could not deliberately get another room into that state. Closing.
