### ISSUE TITLE
element-desktop does not start; only showing spinning wheel

### ISSUE THREAD

**Issue by br-olf** [vector-im/element-web#15807]
### Description
Since my last reboot, when I'm starting element-desktop I only see a spinning wheel.
This is maybe a duplicate of #7730 but because this ticket is very old I don't want to resurrect it.

### Steps to reproduce

- start element-desktop

Sry, I don't have an idea how to reproduce this bug. I'll probably start over with a new profile, this seems to work.

Logs are attached:
The web-console log: [Element-electron__vector.log](https://github.com/vector-im/element-web/files/5589600/Element-electron__vector.log)
Command line output when started with `--enable-logging`: [Element-console.log](https://github.com/vector-im/element-web/files/5589601/Element-console.log)

Maybe the reboot corrupted my profiles? 
This would be a very bad bug in my opinion but I admit I don't understand JavaScript and this is only based on `Failed to open log database: UnknownError`. 

### Version information

- **Platform**: desktop app

- **OS**: `Linux M09998 5.9.10-1-MANJARO #1 SMP PREEMPT Sun Nov 22 11:25:19 UTC 2020 x86_64 GNU/Linux`
- **Version**: element-desktop 1.7.13-1 (AUR package)

**Comment by jryans** [comment]
From the logs, it looks like the data in the profile directory believe it is locked for some reason, and so it gives up on trying to use it. You could try quitting Element, then removing `/home/myname/.config/Element-profilename/IndexedDB/vector_vector_0.indexeddb.leveldb/LOCK` and starting Element again.

If that does not work, then I would recommend a fresh profile indeed, which you've mentioned does seem to work.

**Comment by br-olf** [comment]
Thank you very much, this worked :+1: 

Also, I had to force close all `electron` processes in addition to the `element-desktop` processes:

```
killall -9 element-desktop
killall -9 electron
rm ~/.config/Element-$PROFILE/IndexedDB/vector_vector_0.indexeddb.leveldb/LOCK

element-desktop --profile $PROFILE
```
