### ISSUE TITLE
Cannot find module 'olm' or its corresponding type declarations

### ISSUE THREAD

**Issue by imtbl** [vector-im/element-web#15803]
### Description

I've been building Element from source for a while now, which has usually been working fine. But now I'm getting the following error when installing dependencies (using `yarn`, I assume during the automatically executed `build` script after installation) for `matrix-react-sdk` on the current `master` branch (release 3.9.0):

```
$ tsc --emitDeclarationOnly --jsx react
node_modules/matrix-js-sdk/src/@types/global.d.ts:18:22 - error TS2307: Cannot find module 'olm' or its corresponding type declarations.

18 import * as Olm from "olm"; // eslint-disable-line @typescript-eslint/no-unused-vars
                        ~~~~~


Found 1 error.

error Command failed with exit code 2.
```

### Steps to reproduce

```bash
git clone https://github.com/matrix-org/matrix-react-sdk.git
cd matrix-react-sdk
git checkout -b master origin/master
yarn
```

I've tried with both Node v15.2.1 and 14.15.1.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.14

**Comment by cryzed** [comment]
I can confirm exactly the same behavior on my end.

**Comment by imtbl** [comment]
To clarify the context further, I maintain forks of [matrix-react-sdk](https://github.com/imtbl/matrix-react-sdk) and [element-web](https://github.com/imtbl/element-web) (that mainly add hacky support for custom emotes).

The forks are based on the `master` branches of both repos and I merge the changes from upstream every few versions (to somewhat keep up to date with new releases).

I then publish my fork of matrix-react-sdk [on npm](https://www.npmjs.com/package/@mtbl/matrix-react-sdk); that package is then [used by my element-web fork](https://github.com/imtbl/element-web/blob/6ad34450d1c1f8b1bc89c67e6a8de66ea5279b94/package.json#L64).

I didn't encounter that error in the past when installing dependencies for matrix-react-sdk (the last version of it I successfully built and published is based on release 3.6.1). The issue seems to occur because `olm` is required by both element-web and matrix-js-sdk (as a dev dependency there), but not matrix-react-sdk. Therefore, one viable solution would be permanently adding `olm` as dev dependency to my matrix-react-sdk fork.

But that would mean, that you are not supposed to do what I'm trying to do (build matrix-react-sdk "out of context"; without linking matrix-js-sdk, for example). Is that assumption correct or am I missing something?

**Comment by jryans** [comment]
> But that would mean that you are not supposed to do what I'm trying to do (build matrix-react-sdk "out of context"; without linking matrix-js-sdk, for example). Is that assumption correct or am I missing something?

At the moment, we do generally make some assumptions that you are using a [linked setup](https://github.com/vector-im/element-web/#setting-up-a-dev-environment) for development. I believe everyone on the core team uses this style, for example. We're open to changes to make other workflows easier, but they may break from time to time, since they are not used by the core team.

**Comment by imtbl** [comment]
Thanks for the clarification. For now, I've added `olm` as dev dependency to my matrix-react-sdk fork and that seems to work.

**Comment by turt2live** [comment]
I'm bumping this to p1 because it affected the build for a customer.
