### ISSUE TITLE
Community "Invite …" and "Add rooms …" buttons have a repeating background

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#15809]
![Screenshot_2020-11-24_15-42-36](https://user-images.githubusercontent.com/10872136/100109021-b51eb900-2e6b-11eb-95ae-35d2f5f52f9a.png)

![Screenshot_2020-11-24_15-37-21](https://user-images.githubusercontent.com/10872136/100108402-07aba580-2e6b-11eb-94a2-43e9a053e965.png)

### Description

The tiled background shouldn't be on the button.

### Steps to reproduce

- Create a community
- Open the right sidebar "Members" or "Rooms"

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox Dev 84.0b1
- **OS**: Manjaro Linux (based on Arch repo)
- **URL**: app.element.io and staging.element.io

**Comment by sagarkumar3105** [comment]
can I solve this bug.

**Comment by jryans** [comment]
@sagarkumar3105 Sure, feel free to submit a PR for this! I imagine it's somewhere in the `_MemberList.scss` file.

**Comment by sagarkumar3105** [comment]
@jryans but it is not available. can you share with me the location of the file

**Comment by t3chguy** [comment]
@sagarkumar3105 https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/rooms/_MemberList.scss

**Comment by sagarkumar3105** [comment]
I have figured out the issue with this bug. The reason for the repeating background is that the image being used in the background has less height than the required/mentioned size. So if another image with sufficient height is sed then it won't repeat. 

2nd thing: If you can tell me about which IDE or Platform you are using for getting and viewing the output then I can check it out myself and then upload the corrected code.

**Comment by jryans** [comment]
@sagarkumar3105 Please see our the repo README for more details on getting setup for development.

**Comment by t3chguy** [comment]
Communities are replaced by Spaces
