### ISSUE TITLE
_buildSuggestions should filter deactivated users

### ISSUE THREAD

**Issue by baireutherjonas** [vector-im/element-web#15806]
Hi, i think the [_buildSuggestions-Function](https://github.com/matrix-org/matrix-react-sdk/blob/9b2143742ab6d2fa71dd9769c1e8f9e355ab972e/src/components/views/dialogs/InviteDialog.js#L433) creates the suggestions for new chats for the web and the mobile client. 
I would prefere it, if deactivated users are filtered, because they aren't reachable for other users anymore.

**Comment by t3chguy** [comment]
I don't think the server tells us which users have been deactivated. https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-user-directory-search

**Comment by pierre-alain-b** [comment]
I totally agree this is needed!
I've asked a related question here: https://github.com/matrix-org/synapse/issues/11185

**Comment by t3chguy** [comment]
Closing as not an Element issue
