### ISSUE TITLE
Clicking on user avatar at top bar doesn't work

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15815]
### Description
I started a DM. The Encryption Enabled tile says I can verify the user by clicking on their avatar, but when I click the user's avatar at the top bar, nothing happens. When I click the avatar in the timeline, it works.

### Steps to reproduce

1. Start an encrypted DM
2. Click on user's avatar at top bar

**Comment by turt2live** [comment]
Which top bar?

**Comment by notramo** [comment]
How many top bars are there with profile pictures?
![image](https://user-images.githubusercontent.com/26059643/100140906-8283b900-2e89-11eb-8b9f-a43470f50df6.png)

**Comment by jryans** [comment]
I think we can collapse this into https://github.com/vector-im/element-web/issues/15831, as it's quite similar.
