### ISSUE TITLE
_t and parentheses is visible, when used in win7 in welcome page

### ISSUE THREAD

**Issue by sagarkumar3105** [vector-im/element-web#15813]
when the project is run in windows & it shows _t and parentheses which gives a very awkward feeling.

![issue with welcome page](https://user-images.githubusercontent.com/74974420/100125854-42c9cb00-2ea3-11eb-818a-ed586854fd08.png)

**Comment by turt2live** [comment]
Sorry, windows 7 is not a supported platform for this project.
