### ISSUE TITLE
T&C consent dialog is really ugly.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15826]
<img width="452" alt="Screenshot 2020-11-25 at 16 29 04" src="https://user-images.githubusercontent.com/1294269/100255500-77896100-2f3b-11eb-9caa-256919153342.png">

I think this is a quick fix which doesn't input from design - can we please:
 * [ ] increase margin between the checkbox and the T&C link
 * [ ] vertically center-align the two
 * [ ] Have balanced vertical space above and below the Accept button (otherwise it's horribly squidged between Accept & go back)

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/5cd3a180-fd98-4ff5-b3e1-71c777cdcd36)

Ignore the forced dark mode, but this got fixed
