### ISSUE TITLE
Custom redirect location after logout

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#15829]
**Is your suggestion related to a problem? Please describe.**
When logging out of Element, it should be possible to set a custom location to redirect to.

**Describe the solution you'd like**
I would like to be able to set a web location in config.json, and have the webapp redirect there on logout.

**Describe alternatives you've considered**
Hitting an endpoint during the logout flow could also work

**Additional context**
This is to support users with custom SSO setups.

**Comment by jryans** [comment]
I do imagine we'll want something like this, but I think we'll need input from several SSO deployments before it's clear what shape it should take. For example, I think it would be surprising to a user if they are redirected to an SSO portal when logging out of Element.

**Comment by jonathanmmm** [comment]
> I do imagine we'll want something like this, but I think we'll need input from several SSO deployments before it's clear what shape it should take. For example, I think it would be surprising to a user if they are redirected to an SSO portal when logging out of Element.

For keycloak you could use something like this:
`https://keycloak.example.com/auth/realms/MY_REALM/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Felement-web.example.com%2F` it would logout of keycloak and keycloak would redirect to `https://element-web.example.com`

Even with landing on an SSO portal, that would be the choice of the one deploying element web.

**Comment by t3chguy** [comment]
Otherwise Element Desktops won't be affected by a EW config.json

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/blob/develop/docs/config.md#sso-setup `logout_redirect_url`
