### ISSUE TITLE
Clicking a permalink while composing a reply loses reply context

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15830]

**Comment by yannicka** [comment]
I can't reproduce the problem. Is it possible to have more details?

**Comment by SimonBrandner** [comment]
> I can't reproduce the problem. Is it possible to have more details?

+ Get a matrix.to link
+ Send the link in a room
+ Click the reply button on a message in that room
+ Click the sent permalink
+ The reply pop up will disappear

**Comment by aaronraimist** [comment]
Accidentally opened a dup of this but I think mine has more context https://github.com/vector-im/element-web/issues/21462
