### ISSUE TITLE
Active Call is on top of last message in conversations

### ISSUE THREAD

**Issue by grische** [vector-im/element-web#15839]
### Description

![image](https://user-images.githubusercontent.com/2787581/100375965-f6030300-300e-11eb-84e5-89d1a45eb01e.png)

The "Active Call" button does not seem to be movable and causes a few issues (visible in this screenshot):
1. It hides parts of the last message which cannot be viewed no matter the scrolling
1. It hides which participants have read the last message for short messages

### Steps to reproduce

- Start a call
- Go into a group conversation 
- See issues above

It would be great if the active call button would be either movable or simply in a different location (top right would improve situation a lot).

### Version information

- **Platform**: desktop electron app

For the desktop app:

- **OS**: Windows
- **Version**: Versions
  Element version: 1.7.14
  olm version: 3.2.1

**Comment by fadenb** [comment]
I have experienced the same issue.
Sometimes the box is overshadowing an important word of a conversation which is really annoying.

The ability to move it or make it "jump" to another location when hovering over it would be nice.

**Comment by grische** [comment]
This just got a lot worse with the most recent (1.7.15) version, as the "Active Call" button is huge and overlaps several lines of text in most cases.

**Comment by SimonBrandner** [comment]
Closing in favour of [#16116](https://github.com/vector-im/element-web/issues/16116)
