### ISSUE TITLE
Community Membership Privacy

### ISSUE THREAD

**Issue by andrewperry** [vector-im/element-web#15834]
This comment a couple of years ago may have been lost in a discussion on another issue, but seems perfectly reasonable. Perhaps it is more appropriate for a matrix/synapse issue though?

> Warning: any person you add to a community will be publicly visible to anyone who knows the community ID

What would it take to make a community where membership is only visible to other members who have been invited?

_Originally posted by @stuartpb in https://github.com/vector-im/element-web/issues/2454#issuecomment-362479587_

**Comment by t3chguy** [comment]
This will be possible for Private Matrix Spaces which are being worked on right now.

**Comment by andrewperry** [comment]
Great - ironically was just watching the Matrix Live S06E01 that mentioned Spaces so was just coming back here to update this.  I am a little worried about the proposal to remove the flexible HTML in the Community/Space page as that is at least one way to more expressively give people information about the Space.

**Comment by t3chguy** [comment]
A community description is planned, which supports the same HTML as a message does (which is the same as the Community landing page had) but won't be in the initial release

**Comment by andrewperry** [comment]
Essentially a duplicate of #14923
