### ISSUE TITLE
Multi-party (i.e. not p2p) Jitsi is unreliable in certain networking conditions (VPN)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#15838]
Specifically, we observed:
- one party on a VPN (no specific details here)
- the call works fine when routing peer to peer
- call starts to fail (or even more bafflingly, lose video whilst maintaining audio) when another party joins and flips out of P2P mode

**Comment by andybalaam** [comment]
@lampholder is this something you are still seeing? Given we are working towards native group call support in Element Web maybe this is no longer relevant?

**Comment by turt2live** [comment]
Closing for now - no followup received. If this is still a problem, please open a new issue with modern information.
