### ISSUE TITLE
Yellow gradient appears when you start element web/desktop client

### ISSUE THREAD

**Issue by senorsi** [vector-im/element-web#15849]
### Description

Hello, there's a yellow gradient when I start the desktop client or login on the web client. This issue happens both on light and dark theme. Switching from light to dark and vice-versa fixes the issue until it happens again after some certain(?) events. I had this issue on two different 64bit win 10 pcs, one being home edition and the other is professional.

### Steps to reproduce

- Start either the desktop or web client

![yellow](https://user-images.githubusercontent.com/64203699/100497878-80a64800-315e-11eb-98f5-9ee9e1798370.png)

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chrome (87.0.4280.66), Firefox 83
- **OS**: Windows
- **URL**: Latest versions of Element Web, for several months now

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.14, and several previous versions

**Comment by t3chguy** [comment]
That is a blur of your avatar

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14665
