### ISSUE TITLE
product about info missing in UI

### ISSUE THREAD

**Issue by jimmont** [vector-im/element-web#15848]
Description:
I cannot find the current product information in the user interface;

Expected:
when clicking the (i) information ui control, and on the "home" page, and at the bottom of my user-profile panel, I expect to see at the bottom, or somewhere in the resulting room-info panel information about the product overall--I myself don't think a separate ui is required, simply a statement of what I'm using and who it is by, probably hyperlinked appropriately (to a company website and version release notes)

Version:
current 2020-11-28 releases, iOS and web versions;

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/100513746-70469b00-3167-11eb-848d-71d5ee232312.png)


Its in Settings > Help & About

**Comment by jryans** [comment]
I believe the above comment covers this issue.
