### ISSUE TITLE
Search in encrypted room "download desktop app" message displays on desktop

### ISSUE THREAD

**Issue by CubeOfCheese** [vector-im/element-web#15856]
### Description

I tried searching for messages in an encrypted room on the web app. It showed this message so I downloaded the desktop client and it shows the same message.

### Steps to reproduce

- Search on desktop client in encrypted room

Describe how what happens differs from what you expected.

Logs being sent: yes/no

<img width="1089" alt="Screen Shot 2020-11-30 at 12 27 15 AM" src="https://user-images.githubusercontent.com/16740469/100585686-cec46400-32a2-11eb-95aa-a4d159456440.png">

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop
For the desktop app:

- **OS**: macOS
- **Version**: 
Element version: 1.7.14
olm version: 3.2.1

**Comment by CubeOfCheese** [comment]
Maybe this should be a seperate bug but a similar message displays in the files tab. The room hasn't had any files shared in it yet. Also using the MacOS Desktop app
<img width="1089" alt="Screen Shot 2020-11-30 at 12 42 23 AM" src="https://user-images.githubusercontent.com/16740469/100587030-eac90500-32a4-11eb-9ce9-fc9e44a85450.png">

**Comment by t3chguy** [comment]
This happens when Seshat's db failed to load, try restart the app completely (Quit and restart)

Your logs show `2020-11-30T08:17:30.843Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseError(SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some(\"file is not a database\")))"}`

**Comment by jryans** [comment]
Thanks for the report, we're tracking this in https://github.com/vector-im/element-web/issues/14229. For now, I'd suggest the workaround there of clearing out Seshat files and restarting.

**Comment by CubeOfCheese** [comment]
I came back a day later and it worked as expected. I had just created this room shortly before trying to search so maybe that has something to do with. Thanks y'all

**Comment by florian6973** [comment]
I created a new encrypted room and I had the bug too. I had to totally restart element.io to make it work.
