### ISSUE TITLE
Tooltip for adding an avatar goes over top of dialogs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15854]
![](https://i.imgur.com/bL0dsxU.png)

**Comment by jryans** [comment]
See also https://github.com/vector-im/element-web/issues/15786

**Comment by jryans** [comment]
In https://github.com/vector-im/element-web/issues/15957, @ara4n describes this as:

> The tooltip used in the timeline to nag users to set an avatar for newly created rooms seems to have an infinite z-index, in that if you do things like open up Room Settings the tooltip hovers over the modal - and if you scroll the timeline, it hovers over the RoomTitle etc.

**Comment by t3chguy** [comment]
This is fixed
