### ISSUE TITLE
Bot names are too verbose

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-web#15857]
In my opinion, the names of Bot account are way too verbose. Instead of using something simple, like "Github Bot", or "RSS Bot", the bot name includes the user who created it, as well as a long identifying string afterwards. 

<img width="630" alt="Screen Shot 2020-11-30 at 10 32 35" src="https://user-images.githubusercontent.com/8697285/100592742-cfd3b080-32f7-11eb-9fac-a4502d4f2255.png">
<img width="639" alt="Screen Shot 2020-11-30 at 10 32 16" src="https://user-images.githubusercontent.com/8697285/100592748-d104dd80-32f7-11eb-8de3-e2456594e528.png">

For my personal rooms, this doesn't really bother me. However, when using one of the above bots in a room with many users, I don't see any purpose to displaying the full, long, bot name.

**Comment by jryans** [comment]
Hmm, the names might be long, but at the same time, I don't know what Element Web can do about this... Was there something you had in mind?

**Comment by MarkWieczorek** [comment]
On Android element, they are shorter: Only "RSS Bot [@mark-wieczorek:matrix.org]" appears, without "(@_neb_rss....)". This is better, but in my opinion, their is still no reason to include my username in brackets. Perhaps Element itself can't do anything about this, and it is the RSS and Github bots need to be modified.

**Comment by t3chguy** [comment]
Yes, Element Web/Desktop shows the `(@MXID)` at the end if it thinks that the displayname looks/contains an MXID to help prevent phishing (i.e I change my displayname to `Mr Mayor (@mayor:office)`)

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/5914

**Comment by turt2live** [comment]
Closing as not something we can practically resolve at our level.
