### ISSUE TITLE
element-desktop window stops redrawing

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#15869]
The element-desktop window freezes and doesn't redraw. It *does* seem to be working - clicking where the room list ought to be updates the title bar to show the new room - it's just not drawing the contents of the window. Resizing the window sometimes seems to wake it up.

Seems to have started between nightly 2020110901 and 2020112701.

See below for an example view. It's just stuck like this, until I resize. (The room list is pixelated for privacy, obvs)

![image](https://user-images.githubusercontent.com/1389908/100735971-ffeb8400-33c9-11eb-9802-8b0c7163b9a0.png)

**Comment by jryans** [comment]
@richvdh has bisected further, and it seems the first bad nightly build is 2020-11-24, which is coincidently when we changed to Electron 11.x.

**Comment by jryans** [comment]
As a first attempt, I'll try updating to the latest 11.x version (11.0.3), which includes Chromium changes as well.

**Comment by richvdh** [comment]
more platform info: I'm using xfwm on X, on ubuntu 18.04 LTS.

**Comment by jryans** [comment]
That did not help. I'll try going back to the 10.x series, though it would be best if we can still pull in the minor updates there while avoiding this issue.

**Comment by jryans** [comment]
Looks like 10.1.6 is safe, so we're effectively locked to the 10.x series for now until we can isolate this issue / a fix appears upstream.

**Comment by jryans** [comment]
We have now upgraded to Electron 11.2.3 in today's nightly, and @richvdh says it's better than the last upgrade attempt, though it can still get stuck time to time. Since we currently only know of one affected user here, and the latest upgrade has improved the issue, I think we should keep the upgrade for now and collect more feedback.

Since there's still some amount of trouble, I'll keep this open but downgrade the priority. @richvdh, have the symptoms changed at all? Please add updated screenshots / notes if so.

**Comment by richvdh** [comment]
So, it's still getting stuck; I'm not sure there have been any real changes to the symptoms.

I've now updated to ubuntu 20.04 LTS, with no improvement.

**Comment by jryans** [comment]
@richvdh Hmm, thanks for the update. Do you perhaps have any other systems or display environments you can test in to try to isolate why this seems to only happening for you so far that we know of?

**Comment by jryans** [comment]
@richvdh Also, do you have any other Electron-based applications on your system? For example, [VS Code's stable release](https://code.visualstudio.com/#alt-downloads) has now updated to use Electron 11.x, so it would be interesting to know if you see the same graphical artefacts there as well.

**Comment by richvdh** [comment]
well, what do you know:

![image](https://user-images.githubusercontent.com/1389908/108243300-d418a880-7145-11eb-81fb-1e7c1cede23f.png)

**Comment by richvdh** [comment]
It seems happy if I turn off display compositing. I'll continue to experiment when I get time.

**Comment by richvdh** [comment]
I tried it under GNOME3/Mutter, which didn't seem much different.

**Comment by jryans** [comment]
> I'm sort of at a loss here for how to proceed here. I guess the right thing to do is for me to file an issue with upstream electron.

Yes, I think that's the best path forward!

> To help with that, can anyone point me to a minimal electron app that might reproduce the problem? (I tried https://github.com/electron/electron-api-demos, but it seems to use old versions of electron.)

I'd suggest downloading [Electron Fiddle](https://www.electronjs.org/fiddle). It contains editable panes for the core of an Electron app, and supports many different versions of Electron, including all the latest ones. It's handy for regression testing Electron changes such as this.

**Comment by richvdh** [comment]
Well, the good(?) news is that I don't seem to have this problem with Electron 12...

**Comment by jryans** [comment]
The next nightly build will be based on Electron 12, so hopefully that will finally resolve this.

**Comment by richvdh** [comment]
It has resolved it! hurrah! :dancing_men:
