### ISSUE TITLE
Toggle-all button for sessions in Security settings

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#15863]
**Is your suggestion related to a problem? Please describe.**
If you have a lot of sessions and want to remove all except n, then it's tedious to manually check the 148 you want to delete.

**Describe the solution you'd like**
The option to click "Toggle All", and then uncheck the 2 you want to keep would be nice.

**Describe alternatives you've considered**
You could send something in the console to check all, but this is not very user friendly. Resetting password also work (unless you are on SSO), but also not an ideal solution.

**Comment by kerryarchibald** [comment]
Solved in new session manager (in beta) with 'Sign out all other sessions' option, and 'select all' in the sessions list:
<img width="736" alt="Screenshot 2022-10-18 at 12 41 31" src="https://user-images.githubusercontent.com/3055605/196408715-b3b59b8c-ba27-4e66-b088-9d89cd3c4874.png">
<img width="729" alt="Screenshot 2022-10-18 at 12 41 09" src="https://user-images.githubusercontent.com/3055605/196408719-c851d960-c892-400e-8242-8025ec9a8958.png">

**Comment by t3chguy** [comment]
Closing as solved in labs
