### ISSUE TITLE
Setting default language is invalid

### ISSUE THREAD

**Issue by lostmaniac** [vector-im/element-web#15868]
I configure in the default config.json

   "settingDefaults": {
"language": "zh_Hans"
}

Cannot take effect

**Comment by t3chguy** [comment]
I believe the language will only be considered if the user's browser doesn't have a specified language.

**Comment by MSG-maniac** [comment]
But my browser is in Chinese, and the English version is still open.

**Comment by t3chguy** [comment]
Sounds like your account already has English pre-set, try to reproduce using a new account.

**Comment by MSG-maniac** [comment]
![捕获](https://user-images.githubusercontent.com/6057477/100751731-a9f6fa80-3422-11eb-9e2b-5e1c6fc1b7a4.PNG)

**Comment by MSG-maniac** [comment]
The Chinese language of the code is: zh_Hans
The Chinese language identifier of the browser is: zh-CN

----
navigator.languages

(4) ["zh-CN", "en", "en-GB", "en-US"]
0: "zh-CN"
1: "en"
2: "en-GB"
3: "en-US"

**Comment by MSG-maniac** [comment]
https://github.com/vector-im/element-web/issues/5913

**Comment by jryans** [comment]
Hmm, perhaps we need to some specialised mapping to account for different language codes like this case...

**Comment by MSG-maniac** [comment]
Is there any temporary solution?

**Comment by MSG-maniac** [comment]
Or how long can the repair be completed? thank you very much

**Comment by MSG-maniac** [comment]
Now that there is an option to prohibit switching languages, it is reasonable to have an option to configure the default language, right?

**Comment by jryans** [comment]
> Is there any temporary solution?

You can adjust the language in every session, but I don't think that's what you want...

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/5913

**Comment by qzicxjmozbxameuhnk** [comment]
@lostmaniac in https://github.com/vector-im/element-web/issues/15868#issuecomment-737187050
> 有什么临时解决办法吗？

Here is a temporary solution with one line of code: 
https://github.com/vector-im/element-web/issues/5913#issuecomment-883257145
