### ISSUE TITLE
Electron app won't list audio device and thus fails to play audio.

### ISSUE THREAD

**Issue by Bumbadawg** [vector-im/element-web#15862]
### Description

- no audio output
- no audio output device in pulseaudio
- in video/audio settings, only "Default" is available. No actual device. Pulse audio doesn't list the application when playing inchat audio file.
- executing in the console `navigator.mediaDevices.enumerateDevices()` returns nothing but the pending Promise.
- audio works fine in Firefox

### Steps to reproduce
- start desktop app.
- play inchat audio file, or start/receive a call

Logs: nuh, forcingWebRTC_TURN as default if you wonder.

- **OS**: Void Linux with a fully glib operational PulseAudio (no JACK) pipeline.
- **Version**: Element version: 1.7.14 and olm version: 3.2.1 (it was the it in earlier versions, it might come from the Electron app)

**Comment by jryans** [comment]
So far, it sounds like an Electron / OS issue, so I am not sure there's much that Element itself can do for this.

**Comment by SimonBrandner** [comment]
@Bumbadawg, are you still seeing this?

**Comment by Bumbadawg** [comment]
It's fixed thank you @SimonBrandner
