### ISSUE TITLE
It was confusing to work out how to add an alias to a room

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#15872]
### Description

I was aiming to add a room alias to a room, this issue attempts to explain how I failed to do this with the existing UI.

I tried this twice, stopping partway on one occasion as I believed I had added the alias but I hadn't actually.

### Steps to reproduce

Start by attempting to add a published room alias in a new room with no existing aliases. First realise there's nothing in the publish drop down.

Read down the page to the next bit which talks about adding aliases, attempt to fill in a room alias there and submit

Get an error dialog in the client

![foobar](https://user-images.githubusercontent.com/1917473/100750995-b3f70a00-33de-11eb-8049-29e1368ef15d.png)

Actual error:  `M_INVALID_PARAM: Expected RoomAlias of the form '#localname:domain'

I shouldn't be getting the words in the error box - it's a validation error in the client, and ideally should be rejected client side before submission, or the error passed through from the server. We could also use a better input control (like the one we use later to create local aliases) to help the user do the right thing here.

Anyway, this error makes me feel like I don't have permissions to do this change, so i leave the screen and check I'm an admin on the room. Things look OK so I come back in to this dialog.

I now try to add the room alias again to the room, this time including the full alias that i want to add, I get an error message the same as before, but I now notice that the UI has updated to show the alias in the list added to the room:

![worked](https://user-images.githubusercontent.com/1917473/100751097-d426c900-33de-11eb-8b07-73809603c409.png)

I believe this is the point in the previous attempt to add an alias to the room where i discounted the error as "not really a problem" or "something to do with publishing the alias" and could see the new room alias in the list, so thought I'd succeeded and so stopped trying further.

I know now that it failed because a few weeks later, someone asked me to create the room alias again, so i come back into the settings, look confused because I thought I'd added it, then repeat the above steps. This time thought I /don't/ believe the alias has been added even though it's displayed, and keep on trying:

I now scroll downwards and open up a "see more" option which hides a list of zero items and a new alias box. Filling data in this box seems to do the right thing as well as filling in the main room alias automatically.

I'm then confused about whether i need to enable the publish to the room directory button or not - I wanted to add an alias, but i don't want to make it public, but it reads as if i need to do this to make it usable by people not on matrix.org. I'm not sure what my options here are - i don't want it published on matrix.org or outside of matrix.org, but i do want people not on matrix.org to be able to use the alias.

What should happen instead:

Part one - technical issues / incorrect information displayed

Adding a published address should involve validation client side, or should parse and pass through the error ` Expected RoomAlias of the form '#localname:domain'` from the server to the user. Somewhere i should be reminded of the correct format when submission occurs.

If a failure to publish an alias occurs, it shouldn't show up in the UI in the list of aliases - there should be no changes, or perhaps the client should refresh this information from the server (the server is aware that it isn't set, as exiting and re-entering this dialog  removed the incorrect information)

Part two - the whole flow

When you come to this page and no main alias is set, instead of the multiple levels of options here, if there are zero local aliases and no main alias, then instead of the UI as it stands, the UI should be simplified and ask a single question, possibly with the remaining existing options in the UI behind an "Show More":

"""
If you want to make this room easily accessible to other users, using links or similar, you can give it an alias on your homeserver (matrix.org)". Please add one below, and we will set it as the main alias for this room. You can remove or replace this alias later and also choose whether or not to add it to the public room directory.

`[# (room alias) : matrix.org ] [ SUBMIT ] `

"""

Having done this one-off operation, then we can show the rest of the UI, which will now make more sense as it's partially filled in and shouldn't need more changes for basic use..

We definitely shouldn't have the first step you need to take be hidden under the fold of the config pane (I had to scroll down to see it) and behind a "show more" clickable link.

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Linux
- **URL**:  app.element.io

**Comment by t3chguy** [comment]
@michaelkaye does https://github.com/vector-im/element-web/issues/13077 cover your complaints?

**Comment by michaelkaye** [comment]
@t3chguy yes, with the caveat that fixing the UI showing incorrect results (wrong error reasons, appearing to add items that aren't) is probably more important than having the end to end flow work.

Not sure how i didn't find that one, but yeah, the above is just another iteration of the same issues.
