### ISSUE TITLE
Resizeable call UI

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#15876]
Like widgets can now be resized

**Comment by KennethCipriano** [comment]
Sorry for bumping a closed issue, I didn't want to open a new one.
I've tried the latest Element Desktop 1.8.2 and while the call box is now resizable it barely moves and the chat space is still largely obstructed. Unlike the demo in #5170 my window can't go up that high.
I was wondering maybe a chat pop-out button similar to when you switch rooms would be useful.
