### ISSUE TITLE
A room created by the DM modal ended up in the Rooms list, not the People list

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15878]
I swear we have a bug for this already, but cannot find it. Opening this for rage shaky.

**Comment by turt2live** [comment]
How many people were invited? Did it go into the correct section after a short while?

**Comment by Half-Shot** [comment]
One person, via the Start Chat dialog. It didn't correct itself.

**Comment by Half-Shot** [comment]
Curiously, the account data is correct:
```

    "@rolandelement:vector.modular.im": [
      "!QLqciWpxLFzSSEUQlg:half-shot.uk"
    ]
```

**Comment by panoschal** [comment]
Does this happen always or only some times?
When I try it, the conversation goes to the Rooms list for about 1 sec and then it moves to the People list.

**Comment by andybalaam** [comment]
@Half-Shot is this still happening for you? Does it happen every time?

**Comment by Half-Shot** [comment]
I've not seen it recently. It happened occasionally before.

**Comment by andybalaam** [comment]
I'm going to guess this is fixed. Please re-open if you see it.
