### ISSUE TITLE
hangup button turns into a dial button at the end of a call

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15881]
which means that if you both hang up at the same time on a fast server, whoever loses the race can embarrassingly dial back the other person

> https://github.com/matrix-org/matrix-vr-demo/issues/67

**Comment by SimonBrandner** [comment]
Closing this since the hangup button has been completely removed in [#5693](https://github.com/matrix-org/matrix-react-sdk/pull/5693)
