### ISSUE TITLE
parting a room should not throw you into another room at random.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15882]
i just typed /part on some random room i didn't want to be in any more. in exchange, i got teleported into a room i'd been studiously ignoring for the last few years, and the last place i wanted to send a read receipt to :|

**Comment by t3chguy** [comment]
So two options for where we could send the user are:

+ to `/#/home`
+ to wherever they were before, (equiv of pressing back in their browser)

**Comment by turt2live** [comment]
home seems the most reasonable as an alternative imo
