### ISSUE TITLE
Answered Elsewhere should not require user interaction

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#15885]
For every incoming call that was answered on mobile I must to press OK on all other desktop clients:
![image](https://user-images.githubusercontent.com/14617699/100885593-e3cc0d80-34c3-11eb-9fe5-cf1052cc8946.png)

**Comment by 532910** [comment]
Twenty calls - twenty clicks on each client.

**Comment by jryans** [comment]
@532910 Are you using the latest versions of Element on all devices? This behaviour has changed recently, and now you should only see this modal if you try to answer the call on multiple devices and one loses the race.

**Comment by 532910** [comment]
I'm always on the latest version. When I reported this it was 1.7.14, and I can't reproduce it on 1.7.15.
