### ISSUE TITLE
@room does not make a notification noise, but does show a notification

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15883]
This is despite the room being set to noisy AND my account settings showing @\room should be noisy. RoomID is `!ZJGrSmcqAqlZPugUuM:amorgan.xyz`;

**Comment by daniellekirkwood** [comment]
@Half-Shot is this still valid? We've made some updates to notifications recently so this should have been fixed but wasn't on our radar to close... Please check when you're available to

**Comment by t3chguy** [comment]
Closing due to no response
