### ISSUE TITLE
"Failed to find any key to satisfy VerifyJsonRequest"

### ISSUE THREAD

**Issue by bretellesMaster** [vector-im/element-web#15889]
Hello everyone,

![issueGit](https://user-images.githubusercontent.com/60695647/101054908-b053b680-3589-11eb-8177-1043fca3d69f.png)

### Description

I followed the "Running your own secure communication service with Matrix and Jitsi" guide to have my own homeserver.

### Steps to reproduce

- Followed the walkthrough to "Riot/Web"
- I can access to my URL: riot.bservices.tk 
- I can _Sign Up_ and _Log In_ but when i try to access to _matrix.org_ public room's i got this error.

Thank you for your time.

For the web app:

- **Browser**: Chrome
- **OS**: Windows
- **URL**: riot.bservices.tk (private server on a Debian 10.6)

**Comment by lenormf** [comment]
I'm also facing this issue.

* Element `v1.7.14`
* Synapse `v1.23.0`

Maybe the federated port needs to be exposed?

**Comment by lenormf** [comment]
I went over the federation/delegation configuration, made sure my network passed the [Federation Test](https://federationtester.matrix.org/), and now I can list rooms on Gitter.

Same error when trying to list Matrix rooms so far.

One error I made in the original configuration was the wrong `m.homeserver` address in `/.well-known/matrix/server`.

**Comment by bretellesMaster** [comment]
I made a new installation, because i think i made a mistake with the key registration/signing.

I followed the step on the video and everything went fine. I could invite someone from an other homeserver (we followed the same tutorial) send messages and make video calls.

My website didn't pass the federationtester, i'll explore this error.

Thank you for your message

**Comment by lenormf** [comment]
No problems!

Now it'd be great to have an official answer as to the cause(s) of this issue, and maybe have the UI handle this error better via a human-friendly message if applicable. All I had to work with to solve this problem was Synapse logging a 401 in the logs, and retro-actively check the entire configuration — a directed pointer (if this is indeed a symptom of a single issue) would have been welcome.

For example: *Element couldn't do XXX, check that YYY*.

**Comment by jryans** [comment]
As far as I can tell, this is an issue with Synapse federation. I would recommend asking in #synapse:matrix.org about this.
