### ISSUE TITLE
Messages are not being decrypted 

### ISSUE THREAD

**Issue by harrisondean** [vector-im/element-web#15888]
### Description

When receiving messages from Matthew they are not being decrypted, said token was not being received or had been rejected. 

### Steps to reproduce

Not sure how to reproduce but I do know this happened in the Element internal channel for some else last week as well. 

Possibly just need to get a message from Matthew? 

Describe how what happens differs from what you expected.

Log: sent/not sent?  Attaching via settings  

### Version information

- **Platform**: web (in-browser) or desktop?

Desktop app:

macOS: 11.0.1
Element version: 1.7.14
olm version: 3.2.1

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/2996
