### ISSUE TITLE
Erimayas Fink can make an appearance on the appearance tab if the profile is slow to load

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15897]
https://github.com/matrix-org/matrix-react-sdk/blob/bce0204eb68f1fedf84193b6ca1c6fde27923bd7/src/components/views/elements/EventTilePreview.tsx#L58 

This can show up if for some reason the user's profile takes a while to load, which can happen fairly often. Maybe we should make it just 'You' instead?

**Comment by ShadowJonathan** [comment]
@robintown just out of curiosity, where did that original name come from?

**Comment by robintown** [comment]
No idea, I wasn't the one who added it
