### ISSUE TITLE
Error bootstrapping secret storage Error: Attempted to sign with master key but no such key present

### ISSUE THREAD

**Issue by hausheer** [vector-im/element-web#15909]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

I am trying to "Reset cross-signing and secret storage", but it fails with the message "Unable to set up secret storage" (even after shift-refreshing the page, deleting the site data and do a fresh login). This bug is similar as issue #15337, but the suggestion there (to do a "shift-refresh") didn't work in my case.

Specifically, the logs are as follows:

rageshake.js:65 Forcing cross-signing and secret storage reset
rageshake.js:65 Bootstrapping Secure Secret Storage
rageshake.js:65 Secret storage does not exist, creating new storage key
rageshake.js:65 Creating new message key backup version
rageshake.js:65 Error bootstrapping secret storage Error: Attempted to sign with master key but no such key present
    at u.signObject (CrossSigning.js:441)
    at N.bootstrapSecretStorage (index.js:796)
    at async v._bootstrapSecretStorage (CreateSecretStorageDialog.js:284)
e.<computed> @ rageshake.js:65

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 87.0.4280.88 and Firefox 83.0
- **OS**: Windows 10
- **URL**: It's a private server (previously running riot now element), version of Element Web: v1.7.7

**Comment by jryans** [comment]
@hausheer It looks you're using an older version of Element (1.7.7), and there have been several changes and fixes to this path since then. Are you able to upgrade?

In more recent versions, there are separate buttons for resetting secret storage vs. cross-signing, which may help with your issue.

**Comment by hausheer** [comment]
@jryans Indeed upgrading to a new version (1.7.15) made the problem go away!
