### ISSUE TITLE
Element Web will load very slowly if *Room Info* is open

### ISSUE THREAD

**Issue by tmuehlbacher** [vector-im/element-web#15905]
### Description

Firefox will pop up its "A web page is slowing down your browser"/"Stop
it" or "Wait" bar when opening Element or switching to a large room
(like #matrix:matrix.org) from a small one (like DMs).

### Steps to reproduce

- Open *Room Info* pane on the right
- Switch to large room like `#matrix:matrix.org`
- Reload the browser tab

The issue only happens if I leave the *Room Info* pane on the right
open. If I open Element or reload the browser tab, the chats in the
center will load, the pane on the right will also load, but only show a
limited number of people to be in the room (like 10 or 12 instead of
8231).

The left pane with the chats will not load, if Element was loaded with
the big room currently selected but it will have, if I switched to it
from a small room. Scrolling up the chat will also not work while
Element is slow. After clicking "Wait" a couple of times, eventually
everything will load and normalize. (The room member count will also fix
itself.)

I usually have uBlock Origin and Privacy Badger extensions loaded but
this happens even after disabling them. (They don't show any blocks on
app.element.io anyway for me.)

Logs being sent: Only if necessary. (on demand)

![Screenshot from 2020-12-07 12-15-06](https://user-images.githubusercontent.com/21159584/101345674-b0083380-3887-11eb-938c-ff9cba9d5e21.png)

### Version information

- **Platform**: web (in-browser)

> Element version: 1.7.14\
> olm version: 3.2.1

- **Browser**: Firefox 83 (Debian package version: 83.0-1)
- **OS**: Debian unstable
- **URL**: https://app.element.io/

**Comment by t3chguy** [comment]
This is related to lazy-loading and happens when you have the Members panel open too, looks to be happening in the guts of js-sdk but that is unconfirmed

**Comment by t3chguy** [comment]
It looks like js-sdk might be emitting an event for each lazy-loaded member which slows things down, throttling it makes it feel much faster, will continue to play with this

**Comment by t3chguy** [comment]
Thanks for identifying the culprit to being the right panel being open, I noticed slowdowns when viewing HQ but didn't realise that was the cause.

**Comment by tmuehlbacher** [comment]
I've just tried reproducing it again with the newly released v1.7.16 and it doesn't happen anymore. The *Room Info* panel now displays the member count much quicker and things appear normal. Thank you!

**Comment by t3chguy** [comment]
Thank you for spotting the culprit, massively accelerated things!
