### ISSUE TITLE
Name of icons isn't the same for device verification

### ISSUE THREAD

**Issue by kroeckx** [vector-im/element-web#15900]
This is a split of #10798.

I have 2 devices, 1 running Linux, the other using Windows, both running the same versionof element-desktop, and they actually show exactly the same icons. But they have a different name for 1 icon: Wrench on Windows, Spanner on Linux.

My locale on Linux is set to en_US.utf8. Windows has the display language set to "English (United States)".

**Comment by jryans** [comment]
It sounds like your Linux session is set to "English" instead of "English (US)". You can check in top left menu -> Settings -> General -> Language and region. This setting is per-session, so each one may have something different.

**Comment by kroeckx** [comment]
My Linux session says: "English (US)".

**Comment by jryans** [comment]
Hmm, then that is perplexing... 🤔
