### ISSUE TITLE
Remove Recent Messages + Cache Clear = Client Crash + Media Files Error

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#15903]
### Description

If an user removes an entire set of recent messages, thus clearing a room, and then goes on to clear the cache, the entire Element client freezes up and eventually crashes. It also makes sending messages from another session impossible until the crash takes place and Element is forced to close on the session which it froze up on. The messages that were supposed to be removed will still be there upon the client rebooting. In some cases it will also make it impossible to send media in group rooms any longer, so I'm not sure what is going on there.

### Steps to reproduce

- Remove recent messages from a room
- Clear the cache of the client
- Watch your client freeze up
- Give it about 30 minutes to either self reboot or just force close it
- Find that nothing in the room actually got removed
- It also will affect your ability to send media files in group rooms

### Describe how what happens differs from what you expected.

I expected it to clear the room of the messages and not crash the client while also preventing me from sending media files.

### Version information

**Platform**: Desktop Windows Version 1.7.14

**Comment by jryans** [comment]
Hmm, interesting. I don't think we've heard of this before, but it's obviously not great!

I suspect the details might be important here, so what do you mean by "removes an entire set of recent messages"? Just several messages, or something more specific...? _All_ of the messages in the room?

**Comment by jryans** [comment]
Hmm, the user is gone, and we need more info, so I guess I'll close this.
