### ISSUE TITLE
Can no longer build the production app on Windows

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15911]
```
95% emitting OptimizeCssAssetsWebpackPluginError: EINVAL: invalid argument, mkdir 'F:\Workspaces\riot-web\riot-web\webapp\F:\Workspaces\riot-web\riot-web\node_modules\katex\dist\fonts'

```

This is because `katex` uses relative pathing which makes Windows very angry.

**Comment by jryans** [comment]
@turt2live Is this something you do often? Just trying to assess the priority relative to everything else.

**Comment by turt2live** [comment]
About once every couple weeks, yes.
