### ISSUE TITLE
Layout uglinesses on 1:1 video calls

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15918]
* There's no padding between the LeftPanel and the video view
* The top of the video view isn't aligned with the top of the RightPanel

![image](https://user-images.githubusercontent.com/1294269/101476425-a34a1500-3945-11eb-944e-d91923f39144.png)

(see red/pink arrows)

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_181619](https://user-images.githubusercontent.com/25768714/109427098-11582280-79f1-11eb-8aba-2abc5255eb80.png)

This seems to have been fixed
