### ISSUE TITLE
New .well-known lookup doesn't work for mozilla.org for some reason

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#15914]
If you enter `mozilla.org` into the new server picker on the login screen then you get an error. The .well-known lookup doesn't seem to work properly, maybe something to do with their redirects.

<img width="535" alt="" src="https://user-images.githubusercontent.com/5855073/101427443-7f92ba80-38c4-11eb-9a89-fea88d8b44f0.png">

<img width="725" alt="" src="https://user-images.githubusercontent.com/5855073/101427510-a4872d80-38c4-11eb-9e42-fd094558edda.png">

**Comment by t3chguy** [comment]
Mozilla.org has a missing ACAO header. I raised it with them yesterday afternoon. Nothing element can do about failing CORS.
