### ISSUE TITLE
Document tools needed to build Element Desktop's native modules

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#15915]
Currently the documentation for building the desktop app says 

> This ... will require a number of native tools to be installed, depending on your OS (eg. rust, tcl, make/nmake)

but does not list them all. stoic says on ubuntu you also need `libsqlcipher0 libsqlcipher-dev libsecret-1-dev`

https://github.com/vector-im/element-desktop#building
https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$e51rALbMvdJn4mvBy_8XH1NsulcNflaYYUCLL6Ebv-U?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by jryans** [comment]
The desktop builder's [Dockerfile](https://github.com/vector-im/element-desktop/blob/develop/dockerbuild/Dockerfile) is a good place to look at the moment, but I agree proper docs would be better.

**Comment by t3chguy** [comment]
Now there are also github actions which can be referenced for a bit more guidance

https://github.com/vector-im/element-desktop/blob/develop/docs/native-node-modules.md
https://github.com/vector-im/element-desktop/pull/344 improves the situation

**Comment by t3chguy** [comment]
Closing in favour of new docs & example github actions workflows
