### ISSUE TITLE
Server selector field should be a textbox

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15924]
![screenshot](https://matrix.grin.hu:8448/_matrix/media/r0/download/grin.hu/ibQmbAgCzHeEtkuUtrruwKgd)
It should be a textbox, and the grey description text of the popup  (*We call the places where[...]*) should be under the information button, or directly in the interface.

**Comment by t3chguy** [comment]
Rather than providing your idea of solution, explain your problems with the current solution so that the designers can that and the vast other facets into account together. I suggest adding to https://github.com/vector-im/element-web/issues/15891
