### ISSUE TITLE
.well-known resolution makes app feel unresponsive

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15925]
With the new server selector, when I enter a server name e.g. **grin.hu** (instead of https://matrix.grin.hu), and click **Continue**, Element does a search for the actual server address. While this is done, the app is unresponsive. It **should display a spinner**, or simply print **Finding server...**.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/11941
