### ISSUE TITLE
You can't click on the video PiP any more to go to the room in question

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15920]
I spent a few seconds clicking on things at random to try to get from the video pip back to the room where the call's happening.  I never thought to try clicking on the avatar (which i've been trained to believe will take me to a MemberInfo, or possibly zoom the avatar).

Please can we have "click on video itself" take back to the main room?  (Obviously overlay video controls for mute/hangup etc shouldn't be trapped by that)

**Comment by ara4n** [comment]
so the good(?) news is that we now have a maximise button in the top right of the PIP which... doesn't really maximise the video, but it does take you back to the right room.   Given elsewhere we use maximise to mean maximise or go fullscreen, I still find myself clicking on the video expecting it to take me back to the right room.  Is there a reason not to?

cc @gaelledel

**Comment by toger5** [comment]
This is an issue for all sticky widgets. They all should benefit from the addition done to the VoIP PIP frame, where the whole frame can be moved around and has the not-a-maximise button to jump to the room.
What are the opinions, on adding the VoIP PIP functionalities to all sticky room widgets?

**Comment by gaelledel** [comment]
Let's enable > go back to the call full room View on double click on PIP @SimonBrandner
