### ISSUE TITLE
Remote rooms in the room directory do not render with avatars

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#15926]
Despite the remote server setting and returning avatars to the client, we are rendering the room tiles with boring fallback icons. This is quite ugly looking when viewing the gitter.im room directory for instance.

![image](https://user-images.githubusercontent.com/2072976/101482751-1015dd00-394f-11eb-8b4d-2d07530278c7.png)

room dir excerpt:
```
{
	"2": {
		"room_id": "!cfGXyggEuIOKeYabpu:gitter.im",
		"name": "neovim/neovim",
		"topic": "vim out of the box | https://neovim.io | posts by @matrixbot are from #neovim on freenode\nBreaking changes at https://github.com/neovim/neovim/wiki/Following-HEAD",
		"canonical_alias": "#neovim_neovim:gitter.im",
		"num_joined_members": 77,
		"avatar_url": "mxc://gitter.im/2079b1e48db9491c28da4e7593d2ce7d45c52dd0",
		"world_readable": false,
		"guest_can_join": false
	}
}
```

**Comment by Half-Shot** [comment]
Turns out that matrix.org is having trouble rendering thumbnails from gitter.im, so this is NotABug.

**Comment by t3chguy** [comment]
ftr my HS had the same thumbnailing issue

**Comment by Half-Shot** [comment]
This is https://github.com/matrix-org/synapse/issues/8893
