### ISSUE TITLE
Kiwi browser incompatibility 

### ISSUE THREAD

**Issue by laem** [vector-im/element-web#15928]
![Screenshot_20201208-133716_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101485145-085c3580-395b-11eb-9ee8-8b6c448d7862.jpg)

### Description

Kiwi browser in desktop mode isn't allowed to access element.io. I suspect it's just a matter of allowed useragents.

### Steps to reproduce

- download Kiwi browser on your android device
- check the option "desktop mode"
- go to app.element.io
- get the unsupported message

### Version information

Kiwi november 2020

**Comment by t3chguy** [comment]
There is no user agent filtering done. Everything is done using Modernizr's feature detection.
If you do not have a `I understand the risks and wish to continue` button then your browser is incapable of even running React.

I suggest you look at your browser logs.

**Comment by laem** [comment]
That's right, I've changed the user agent to Firefox 81 (Kiwi lets you install desktop chrome extensions) and it still doesn't work.
I'll raise an issue there. 
> I suggest you look at your browser logs.
Unfortunately, mobile browsers don't have a js console, and I can't run a remote console right now.
