### ISSUE TITLE
element issue

### ISSUE THREAD

**Issue by gravedigger121** [vector-im/element-web#15929]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment]
Please fill the issue template.

**Comment by gravedigger121** [comment]
i can't get on to element general i am using Firefox URL: develop.element.io / app.element.io / not a privet server i am 73 years old and make mistakes i cant get on to general on element my fault something to do with putting numbers in and i did not i went in to a privet room on invite and left after without doing anything now i frigged something up trying to fix it could i get some help please name hellcat@pei.sympatico is someone could help me ge on general please i wont go in to any rooms any more thank you
