### ISSUE TITLE
Unable to interact with gitter.im issue links

### ISSUE THREAD

**Issue by msrd0** [vector-im/element-web#15927]
### Description

I just tried out the new and fancy gitter integration with matrix and noticed that element does not correctly render links to GitHub issues. The issue number appears blue as if it was a link, but has no interaction as if it was normal text. It is not possible to click the link, nor copy the link address, as is possible with other links. From _View Source_, the link looks like this:

```html
<a target="_blank" data-link-type="issue" data-issue="395" class="issue">#395</a>
```

### Steps to reproduce

- join a room on the gitter.im matrix server that is connected to a git repository
- post a message through the gitter.im web interface that references an issue
- try to interact with the link in element

### Version information

- **Platform**: electron
- **OS**: Arch Linux
- **Version**: 1.7.14-1

**Comment by t3chguy** [comment]
This is not an issue with Element but with the Bridge which must translate the links into ones which match the Matrix spec. `data-link-type` and `data-issue` are unrecognized in Matrix.

**Comment by t3chguy** [comment]
@MadLittleMods this might be one for you

**Comment by MadLittleMods** [comment]
@msrd0 I've created an issue on the Gitter webapp side to track this problem: https://gitlab.com/gitterHQ/webapp/-/issues/2694
