### ISSUE TITLE
SignUp UI: E-Mail Wrapper icon overlaps text

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#15936]
![Screenshot_2020-12-09_12-12-12](https://user-images.githubusercontent.com/10872136/101622918-f42a3e00-3a17-11eb-9c8a-a2627e2ef95a.png)

`.mx_InteractiveAuthEntryComponents_emailWrapper::after` or `.mx_InteractiveAuthEntryComponents_emailWrapper::before` seems to hold this image that's in front of the text.

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Create an account in Element Web
- Pass the "I'm not a robot" step

Describe how what happens differs from what you expected.

The image should not overlap the text.
"Do you even flex( box)?"

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox Dev 84.0b4
- **OS**: Manjaro Linux
- **URL**: Current version on EMS

**Comment by t3chguy** [comment]
Strange, it was fine when PR'd

![image](https://user-images.githubusercontent.com/2403652/101624660-289afb80-3a12-11eb-8ebe-fa806f41a05a.png)

**Comment by jaller94** [comment]
This is on EMS staging. Element version: v1.7.14
