### ISSUE TITLE
Start automatically after system login on ArchLinux brings up electron window

### ISSUE THREAD

**Issue by amalon** [vector-im/element-web#15943]
### Description

The "Start automatically after system login" preference just brings up the Electron window (same as when you just run electron without an app) after login rather than element.

### Steps to reproduce

- Settings, Preferences, General, "Start automatically after system login"
- logout, login

I expect element to start, presumably minimised / in the status bar.
Instead I just get the electron window.

Logs being sent: no

Element is started using KDE, presumably the element-desktop command, which runs:
```
electron /usr/lib/element/app.asar "$@"
```

When the option is ticked, it creates ~/.config/autostart/electron.desktop containing:
```
[Desktop Entry]
Type=Application
Version=1.0
Name=electron
Comment=electronstartup script
Exec=/usr/lib/electron/electron --hidden
StartupNotify=false
Terminal=false
```

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: Element 1.7.14
- **Packages**: element-desktop-1.7.14-1 element-web-1.7.14-1 electron-10.1.5-1

**Comment by t3chguy** [comment]
Sounds like a bug with https://github.com/Teamwork/node-auto-launch 's auto-detection

**Comment by amalon** [comment]
I suppose this one is relevant then:
https://github.com/Teamwork/node-auto-launch/issues/48

Particularly https://github.com/Teamwork/node-auto-launch/issues/48#issuecomment-287653412 :
> Ok, I answer to myself and @amalbose in case it could still help...
> 
> Basically you should have done as me, i.e. defining something like
> ` launch = new AutoLaunch({ name: app.getName() });`
> 
> For Electron as quoted in doc, path, is automatically filled with
> 
> > process.execPath
> 
> This means that it cannot work in development, as it will always map to your electron executable.
> The only way to make it work is simply to build a deb package and install it, you'll see that works perfectly fine once it is bundled in a packaged application.

So perhaps this is a packaging issue. No idea how it's supposed to be launched without going via the electron binary though...

**Comment by amalon** [comment]
Also of interest:
https://wiki.archlinux.org/index.php/Electron_package_guidelines
which seems to suggest using a wrapper, which is apparently triggering the problem here

**Comment by steef435** [comment]
Yeah, Arch likes to keep one copy of electron instead of all apps bringing their own.

Judging from your research, a solution from the Arch side would be to patch [src/electron-main.js](https://github.com/vector-im/element-desktop/blob/302f25054a7b6723c3a86389d765c91176536020/src/electron-main.js) so that the two AutoLaunch constructor's option objects include `path: /usr/bin/element-desktop`. I don't see a neat way to fix this from the node-auto-launch side.

Have you created a bug report at the Arch bugtracker @amalon?

**Comment by amalon** [comment]
I hadn't yet, as it seemed rather unclear where the bug should/can really be fixed. Here goes:
https://bugs.archlinux.org/task/69019

If it can't really be fixed in node-auto-launch reliably, and the path depends on the distro, I think you could be right it should be resolved at the distro level. Is there no generic way for element code to detect the app path via electron though to allow a cross-distro solution that isn't quite so subtle?

**Comment by amalon** [comment]
If not, perhaps it would be prudent to document this somewhere for packagers to take note of

**Comment by steef435** [comment]
Ah, great! Just asking in case I would have made a double one.

> Is there no generic way for element code to detect the app path via electron though to allow a cross-distro solution that isn't quite so subtle?

What I was thinking was that it's not nicely fixable in node-auto-launch because I think there is no way to differentiate between "started using `electron <appfile>`" and "my electron app is just called electron for some odd but not impossible reason". But maybe there is a way?

**Comment by ArchangeGabriel** [comment]
@steef435 So if I get things correctly, the change would be:
```diff
     launcher = new AutoLaunch({
         name: vectorConfig.brand || 'Element',
         isHidden: true,
+        path: /usr/bin/element-desktop,
         mac: {
             useLaunchAgent: true,
         },
```

**Comment by steef435** [comment]
@ArchangeGabriel Yes, I believe so! (With quotes around the path string, my bad.)

Users that already had the autostart setting anbled will probably have to disable and then enable it again in order it to be fixed.

**Comment by ArchangeGabriel** [comment]
Done in latest release (1.7.34). I’m wondering if something like that should be use for the tooltip on the tray icon that currently displays `electron`, which I guess comes from the fact we launch system electron and not a renamed one.

**Comment by t3chguy** [comment]
Closing as resolved above
