### ISSUE TITLE
The bottom of the VoIP PIP is clipped off.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15958]
<img width="355" alt="Screenshot 2020-12-14 at 17 03 21" src="https://user-images.githubusercontent.com/1294269/102111490-5fb44700-3e2e-11eb-9a20-26cedd02cde0.png">

(plus suffering still from the frame colour clashing with the rightpanel bg colour)

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_183417](https://user-images.githubusercontent.com/25768714/109427640-95130e80-79f3-11eb-8cc2-d92c49c4b917.png)

This seems to have been fixed
