### ISSUE TITLE
Instructions to build ARM builds

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#15952]
The [Element Desktop page](https://github.com/vector-im/element-desktop) does not include instructions to build ARM builds.

However, there are four opened issues that would benefit from having clear instruction for arm builds :
- Manjaro : https://github.com/vector-im/element-web/issues/13885
- Debian : https://github.com/vector-im/element-web/issues/6153
- Docker : https://github.com/vector-im/element-web/issues/15227
- Appimage: https://github.com/vector-im/element-web/issues/4766

**Comment by t3chguy** [comment]
Closing in favour of the specific issues above
