### ISSUE TITLE
Finalize repository renaming and remove outdated installation instructions to avoid confusion

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#15950]
Probably you are already aware of this, but I couldn't find any issue that I get follow to track this:

The APT repositories should be renamed to use element in their name - not riot: packages.element.io or sth. like that. The installation instructions should be adapted accordingly.
And this page here should IMHO be removed completely:
https://riot.im/download/desktop/
It even mentions the old package name instead of "element-desktop"...

**Comment by jryans** [comment]
Thanks, yes, I agree these points should be addressed, and they are on our backlog.

**Comment by t3chguy** [comment]
Instructions updated https://element.io/download#linux
