### ISSUE TITLE
Automatic Recovery Prompt

### ISSUE THREAD

**Issue by jjabinx** [vector-im/element-web#15956]
Hello everyone! I'm trying to get some people at my company to work with Element (Desktop version mostly) and I've come across a slight problem.

When a user installs the Element-Desktop app, the app of course doesn't close or sign out by itself, which is good. But I've had a user sign out and skipping on all the Passphrase and Recovery Key steps when trying out the app.
(Assuming every user has their own personal computer) is there a way to cause the desktop app to automatically prompt the user to save a recovery key on first login so there would be no case in which a user accidentally loses their messages because of not reading?
Or perhaps (although this is probably not recommended) is it possible to disable the Passphrase/Recovery and rely on the authentication of the user alone?

Any help would be much appreciated! Thanks!

**Comment by notramo** [comment]
It would be better to use Argon2 on the account passphrase with a different salt used for login, to derive the SSSS key automatically.

**Comment by t3chguy** [comment]
> It would be better to use Argon2 on the account passphrase with a different salt used for login, to derive the SSSS key automatically.

That would mean that LDAP-backed auth would no longer work given it needs the raw password.

**Comment by notramo** [comment]
When raw password is available, use it. If not (e.g. social login), then use the current workflow for setting it up.

**Comment by t3chguy** [comment]
What??

If you are using Argon2 to derive passwords then how will that work? A rogue server could always just claim its LDAP backed to coerce the client into sending the raw password.

**Comment by notramo** [comment]
(I edited my above comment to clarify it.)

If the **user logged in with entering the password**, then use Argon2 in the client to derive key for 4S, and use that key as if it were entered via the current backup passphrase prompt (so don't show the prompt, but derive a key from account password and use it).
So basically: use the same password for login and 4S. (Just use different salt.)
If the user logged in via other method, e.g. SSO, then ask for the 4S password with the current workflow.

**Comment by t3chguy** [comment]
> If the user logged in with entering the password, then use Argon2 in the client to derive key for 4S, and use that key as if it were entered via the current backup passphrase prompt (so don't show the prompt, but derive a key from account password and use it).

But that means that all homeserver admins can now unlock your 4S, no?

> So basically: use the same password for login and 4S. (Just use different salt.)

This implies sending a salted hash as the password to the server for auth, which is not compatible with LDAP, which is not SSO. LDAP happens using the regular Username+Password, its just that the password store is not owned by Synapse but read by it.

**Comment by notramo** [comment]
> But that means that all homeserver admins can now unlock your 4S, no?

If the password is sent to the server in cleartext during auth, then yes.
In this case I recommend adding another auth method, which would differ from the current `password` method, e.g. it could be called `storepassword`, and it would not work on LDAP configs. The procedure would be the following:

- User enters password.
- Element **derives 2 keys* with Argon2 from that password using different salt and different iteration.
- The **first derived key** is used for **authentication** i.e. as login pasword (similarly to current workflow, that key is sent to server in cleartext, then server hashes it again - SHA is enough here - to compare with the one in the DB).
- The **second derived key** would be used for **encryption**, to set up/unlock 4S.
- Wherever password auth is required, and is not login procedure (e.g. changing password, deleting devices, etc.), then it should always use the first salt to derive the authentication key (first key).

**Comment by t3chguy** [comment]
> it would not work on LDAP configs

What do you propose for enterprise instances which use LDAP for everything? https://github.com/matrix-org/matrix-synapse-ldap3

**Comment by notramo** [comment]
This idea is not intended to be used in enterprise environment. I don't have a solution for LDAP.
The purpose of this new login method would be that regular users (coming from WhatsApp, Messenger, Hangouts etc.) wouldn't have to enter a different passphrase.
Should I open a new issue for separating enterprise and personal communication situations?

**Comment by t3chguy** [comment]
Okay but the issue is, at any point a server could be modified to tell clients that its "LDAP-backed" so that they send the plaintext password, as which point the server operator can just go and apply Argon2 and unlock people's 4S... No?

**Comment by notramo** [comment]
If the client can be tricked by a malicious server to send the password in cleartext, there is no solution for that.

**Comment by t3chguy** [comment]
Exactly, which is a massive security issue prohibitive to any Argon2-like auth system which remains compatible with LDAP-backed password stores.

**Comment by notramo** [comment]
Only one solution is possible: if the method is displayed for the user with proper UX indicating that it is unsecure.
Make locally encrypted (Argon2 clientside then SHA serverside) login default. Brand it as **Secure Login** or something similar. Display a green shield icon next to the **Secure Login** text on the log-in screen (the same log-in screen as currently, but it would use the `storepassword` backend). If an user registers on a Secure Login enabled server, then display a warning:
> **From now on, you must log in _only_ with Secure Login.** Your password is now used for protecting your messages. If you log in with unsecure login methods, your server administrator will be able to decrypt and read your messages, and you will not be able to read them.

If plaintext auth is required, only display a button: **Log in with company account**. If it is clicked, then show a warning banner:
> **Warning**: This authentication method will make your messages readable to the server administrator and your company.

Maybe a **?** button, which displays a dialog explaining it (maybe needs better wording):
> Companies use log-in methods which requires your **passphrase** to be sent to the server **unprotected**. If you were told by Element to **only use Secure Login, then YOU MUST NOT USE THIS METHOD**. If you use this method despite you have Secure Login enabled in your account, your messages will be readable by the server administrator and your company. **If this is not a company server**, but Secure Login is not offered, then **you are being attacked by a malicious server.**

Having the authentication method protect the password even from the server, it opens up the possibilities to derive more keys from it later when needed for new protocol extensions (e.g. when P2P stuff introduced, it will maybe require more keys, then just use a third, different salt).

**Comment by jryans** [comment]
Coming back to the original question... If you have message keys from talking in an encrypted room, then logging out should display a warning already. Isn't that what the OP is asking for? If so, that already exists, as far as I know...

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot reproduce it because the UI has changed. Please comment with @kittykat if you are still experiencing it and I will reopen the issue for you.
