### ISSUE TITLE
Leaving a chat blocks the app with a full screen spinner

### ISSUE THREAD

**Issue by pingiun** [vector-im/element-web#15954]
### Description

I am cleaning up some chats by leaving them. However my server isn't super fast, and when the client is leaving the chat, it shows a full screen spinner (visible on screenshot). This blocks the usage of the app, I would like to keep using it instead so I can leave more chats.

### Steps to reproduce

- Leave any room
- See a full screen spinner 

#### Describe how what happens differs from what you expected.

I would like to instead see a spinner next to the chat being deleted. Or possibly just deleting the chat from the list immediately, and only showing an error when the request didn't work.

Logs being sent: n/a

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1576660/101989649-323a9280-3ca2-11eb-91df-e1aa58389687.png">

### Version information

- **Platform**: macOS desktop and web

For the web app:

- **Browser**: Firefox
- **OS**: macOS
- **URL**: tried on develop.element.io and app.element.io

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.15

**Comment by jryans** [comment]
Thanks for the feedback! I believe this is similar to https://github.com/vector-im/element-web/issues/13911, so let's track it there.
