### ISSUE TITLE
Change camera input live during call

### ISSUE THREAD

**Issue by em0lar** [vector-im/element-web#15955]
**Is your suggestion related to a problem? Please describe.**
I'm always frustrated when I do a video call with element and want to change the camera input.

**Describe the solution you'd like**
Ability to change the camera during a call. An example solution would be during a call:
1. Change the camera in settings
2. Turn camera off and on again (maybe also doing that automatically when changing the camera in settings)
3. See the usage of the other camera

**Describe alternatives you've considered**
The only current possibility is to change the camera in the settings and restart the call. 

**Additional context**
None

**Comment by jpggithub** [comment]
This change is possible when you do a simple video call with Jitsi (aka out of a element call).

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15595
