### ISSUE TITLE
Dropdown "Rooms" does not allow to search for remote rooms (only create local room)

### ISSUE THREAD

**Issue by xundeenergie** [vector-im/element-web#15964]
### Description

In Rios-Desktop-Client for linux i can not search for remote rooms, clicking on the "+" beside "Rooms" in roomlist. Only create local room is possible. In Web-Client a click on the same button "+" give me the 2 options for local and remote rooms.

Describe how what happens differs from what you expected.

Log: sent/not sent?   Logs will come through Reporting-tool 

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Fedors 32
- **Version**: 1.7.15

**Comment by t3chguy** [comment]
User is actually on `1.6.8` and is confused by the UI differences between his Web client on 1.7.15 having the explore button in a different place.
