### ISSUE TITLE
New users cannot not read the room history after joining

### ISSUE THREAD

**Issue by periodicpoint** [vector-im/element-web#15965]
### Description
The following problem persists in the web app in the browser (Brave Browser version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)) and in the desktop app (version: element-desktop 1.7.14-1.) under Arch Linux (64-bit).

**New users are unable to see the room history after initially joining the room, even when the room security and privacy settings are set to “anyone” can read the room history.** I tried different constellations and timings of settings, invitations, etc. without success. Changing the security setting has no effect whatsoever.

### Steps to reproduce issue:

1. Create a new room with enabled encryption.
2. Post some messages in this room.
3. Then invite new user to this room.
4. Issue: The new members cannot read your previous messages nor the messages of anyone else.

### Changing the settings have **no effect**
You can change the security settings of the room under: “Room info (i)“ > “Room settings” > “Security & Privacy” > “Who can read history?”. There you have the following four options:
- Anyone
- Members only (since the point in time of selecting this option) [Default]
- Members only (since they were invited)
- Members only (since they joined)

None of these options seem to have an effect on the visibility of the room history for new users. New room member are unable to see the room history irrespective of the option chosen. 

### Expected behaviour
The entire room history should be visible to new members unless the option “Members only (since they were invited)” or the option “Members only (since they joined)” is set. In particular, the room history should be visible if the option “Anyone” or the default option is set.

Maybe I am missing something and it is not a bug but a feature. But there should definitely be an option to make the room history visible to all subsequent members. This feature is important to avoid having to resend important standard information every time (resulting in bad redundancy). Only in this way can (growing) teams work effectively with element IMHO.

**Comment by jryans** [comment]
Thanks for the report. This is a known issue and that needs some technical design work to resolve. The room history settings do work as you expect them to in unencrypted rooms. And at a technical level, they "work" in an encrypted room: new users actually can _receive_ the old encrypted messages, but they will be missing keys to _decrypt_ them.

At the moment, Element Web hides these undecryptable messages to avoid presenting you with an ocean of error message that you can't do anything to fix.

To resolve this, we'll need a way to somehow safely allow new member decrypt old messages, but that will require some design work on the encryption side. Anyway, it's definitely something we want to fix, but it's a bit more complex that it seems on the surface.

I think we can use https://github.com/vector-im/element-web/issues/13349 to track this, so I'll mark this as a duplicate.

**Comment by periodicpoint** [comment]
Thank you very much for your detailed answer. It now all makes sense to me. I can well imagine that this problem is cryptographically non-trivial. Your workaround sounds reasonable. Thanks again, I really appreciate it.

**Comment by IIerpos** [comment]
I am still having this problem. Is there any progress on it at this point? Is there any workaround that I can use to allow people who join a room to get the message history at all on an encrypted room?
