### ISSUE TITLE
UISI me to Amandine

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#15975]
### Description

Amandine was getting UISI from me on Element desktop, on macOS. Related bug from Amandine here: https://github.com/matrix-org/element-web-rageshakes/issues/3936

### Steps to reproduce

- sent message from macOS to Amandine

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.15

**Comment by jryans** [comment]
Thanks for the report. Let's track this under the general UISI issue (https://github.com/vector-im/element-web/issues/2996).
