### ISSUE TITLE
Bug report HPI Schul-Cloud

### ISSUE THREAD

**Issue by schroederkkg** [vector-im/element-web#15976]
### Description
The bug occurs as soon as I acces the HPI Chul-Cloud. I can make it go away for a short while by refreshing the browser window. However, it'll reappear after a short while and block a large part of my screen.
![Bildschirmfoto 2020-12-14 um 10 31 32](https://user-images.githubusercontent.com/76054313/102227328-b894e580-3ee9-11eb-9b67-975c48ab964c.png)

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
This appears to be a problem with the provider's setup. Their support should be able to handle the issue.
