### ISSUE TITLE
Element says verification of new device was canceled by me. But it wasn't. 

### ISSUE THREAD

**Issue by halb9** [vector-im/element-web#15970]
### Description

When trying to cross-sign a new device Element is telling me at the end I had canceled the verification. But I didn't. 

### Steps to reproduce

Starting in Element. Element informs me about a device that is unverified and therefore untrusted. 
![01](https://user-images.githubusercontent.com/18451020/102202634-7b1b6280-3ebf-11eb-8b26-8f0e7ead789f.png)

Element shows me the unverified devices. We're focusing on "Mobilgerät" (meaning mobile device / smartphone). 
![02](https://user-images.githubusercontent.com/18451020/102202666-88d0e800-3ebf-11eb-9c79-4358efe735e7.png)

I initiate the verification process from within Element. 
![03](https://user-images.githubusercontent.com/18451020/102202750-9c7c4e80-3ebf-11eb-90c3-6c3fc84378fc.png)

On the mobile device the emojis verfication appear. And they are the same. So I click the green button "Sie passen zueinander" (meaning they match) in Element. 
![04](https://user-images.githubusercontent.com/18451020/102202834-b3bb3c00-3ebf-11eb-95e0-9f273dbf4edf.png)

Element says it is wating for the other connection. 
![05](https://user-images.githubusercontent.com/18451020/102202876-c03f9480-3ebf-11eb-94cf-93ee3229a8bc.png)

A couple of secons later a dialog appears telling me the verification was canceled by me. Which it was not. 
![06](https://user-images.githubusercontent.com/18451020/102202905-ca619300-3ebf-11eb-9f33-3695dbff7abf.png)

And so basically I'm back at the beginning. 
![07](https://user-images.githubusercontent.com/18451020/102202965-e6653480-3ebf-11eb-9263-629359751ed0.png)

This happens regardless of the verification method. Emoji or Text. 
It also doesn't matter from where I start the verification. 
This happens only with this person/account/device. 
The server is used by about 10 people. None of the others are facing this issue. 

I managed to capture a debuglog from within Element. As this log contains a lot of personal informations I'm hesitant to upload it publicly. However it can be provided in private if necessary. 

Thanks in advance!

have a nice day

### Describe how what happens differs from what you expected.

I expected to have a new verified device ;)

Logs being sent: Logs are available upon request. 

### Version information

For the smartphone app:

- **OS**: iOS 14.2
- **App-Version**: 1.1.1 v1.1.1 #20201124183047

For the desktop app:

- **OS**: macOS
- **Version**: 1.7.15

**Comment by jryans** [comment]
Sorry for this trouble, and thanks for the feedback.

I would recommend resetting your security settings as a possible workaround:

0. Consider exporting room keys to a file as a backup in an existing session via top left menu -> Settings -> Security -> Export E2E room keys (but you've said you don't have encrypted rooms at the moment)
1. If you don't have an existing develop session, it should be fine to login and skip any verification prompts
2. Reset secure backup first (this should now succeed without confusingly asking for previous keys)
3. Reset cross-signing keys (this may prompt for security key / phrase, it's expecting the new one you just made in step 2)
4. On other sessions, you should be able to either verify the new session and receive new keys or go to Settings and "setup" Secure Backup (green button instead of the red "reset"), which maybe prompt for the new security key / phrase as part of downloading your keys

**Comment by halb9** [comment]
> Sorry for this trouble, and thanks for the feedback.

Hey, thanks for taking the time!

> 
> I would recommend resetting your security settings as a possible workaround:
> 
>     1. Consider exporting room keys to a file as a backup in an existing session via top left menu -> Settings -> Security -> Export E2E room keys (but you've said you don't have encrypted rooms at the moment)
We have a couple of 1:1 rooms with E2EE. But this specific one the issue is referring to, no it is not an E2EE room. 
> 
>     2. If you don't have an existing develop session, it should be fine to login and skip any verification prompts
> 
>     3. Reset secure backup first (this should now succeed without confusingly asking for previous keys)
> 
>     4. Reset cross-signing keys (this may prompt for security key / phrase, it's expecting the new one you just made in step 2)
> 
>     5. On other sessions, you should be able to either verify the new session and receive new keys or go to Settings and "setup" Secure Backup (green button instead of the red "reset"), which maybe prompt for the new security key / phrase as part of downloading your keys

I'll try that. Hopefully there will be someone in the office tomorrow. Otherwise I'm going to test this in the new year. 

Again, thanks for the reply!

**Comment by halb9** [comment]
Hi there, 
I tried today the suggested steps. 
- Made a backup of the room keys
- Reset the secure backup
- Reset cross-signing

After that tried to cross-sign the "new" device. Issue is exactly the same as described in the original post. Verification process starts, emojis match, but in the end it says the verification was canceled by me. 

Is there anything I can do that would help tracking down this issue?

Thanks

**Comment by jryans** [comment]
@halb9 Hmm, I know several issues have since been fixed in the iOS app, any chance it is better now?

**Comment by halb9** [comment]
> @halb9 Hmm, I know several issues have since been fixed in the iOS app, any chance it is better now?

Hey, sorry it took so long. 
We did try this the other day. No success. 

As we are able to reproduce this are there any logfiles that might help narrow this down? 
I do have full access to the server and clients. 

Thanks for your time anyhow!

**Comment by jryans** [comment]
@halb9 If you can send debug logs from each client and mention this issue, then we can see if anything stands out.

**Comment by jryans** [comment]
Working this out requires an active conversation with reporter, and we haven't heard back in a while, so let's close this for now.

**Comment by Redsandro** [comment]
Did anyone figure this out? I'm having the same issue between Element Desktop app and Element Android app. I'm guessing the Desktop app is an Electron app using Element-web, but I am not sure. Either way, from both devices I'm getting the same "canceled" accusation, which is not a nice message (because it's a lie) and should probably be changed into _"something went wrong"_.

**Comment by gracks** [comment]
I'm running into this issue and it's incredibly frustrating.  I can't get my Windows session to verify my iOS session, because it always says the session was verified after I scan qr code or match emojis, and then immediately says the verification was cancelled due to some ambiguous issue.

It just started prompting me for this type of cross-signing verification today.

**Comment by yancyscot** [comment]
It's April 28, 2023, having this issue. What's the gameplan to sort this out?

**Comment by chrs4711** [comment]
Just ran into this issue trying to verify my iOS session using a session on macOS. Any help would be appreciated.

**Comment by samcat116** [comment]
I've had this issue as long as I've used Element and still do to this day

**Comment by leo-nine** [comment]
The issue is still occurring, going around and around. Both element Android and web were just updated.

**Comment by yaomtc** [comment]
I also can't verify my session on Android from element-desktop on Arch Linux. I can scan the QR code, and then the two shields are the same, but clicking to verify is shown as canceling.

**Comment by Redsandro** [comment]
![image](https://github.com/vector-im/element-web/assets/1702193/0b37c2fa-043e-4606-86d5-e659c99b66ad)

![image](https://github.com/vector-im/element-web/assets/1702193/b927fe01-a37f-46d4-b1a9-dceeb53b46c4)

![image](https://github.com/vector-im/element-web/assets/1702193/96ef2007-ee36-4a72-9a32-8eded7f7f788)

# Yes, dear God YES

![image](https://github.com/vector-im/element-web/assets/1702193/648199d8-5773-4c30-a597-9edeacdcc7e4)

**Comment by Redsandro** [comment]
@jryans could you take another look at this issue?

```
app = element-web
version = 1.11.50
user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.50 Chrome/118.0.5993.89 Electron/27.0.2 Safari/537.36
installed_pwa = false
touch_input = false
crypto_version = Olm 3.2.15
matrix_hs_server_version = 1.96.1
```

```
18:38:11.333Z D received to-device m.key.verification.request from: @myuser:matrix.test.com id: undefined
18:38:11.334Z D Verification request ae78d5cfb8ae56fcdba75dcae8b75d8a: m.key.verification.request event with id:undefined, content:{"from_device":"XXXXXXXXXX","transaction_id":"ae78d5cfb8ae56fcdba75dcae8b75d8a","methods":["m.sas.v1","m.qr_code.show.v1","m.qr_code.scan.v1","m.reciprocate.v1"],"timestamp":1701196692105} deviceId:XXXXXXXXXX, sender:@myuser:matrix.test.com, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:1=>2, observeOnly:false=>false
18:38:12.639Z D PUT /sendToDevice/m.key.verification.ready/m1701196692639.0 {}
18:38:12.781Z D Verification request ae78d5cfb8ae56fcdba75dcae8b75d8a: m.key.verification.ready event with id:undefined, content:{"methods":["m.sas.v1","m.qr_code.show.v1","m.reciprocate.v1"],"transaction_id":"ae78d5cfb8ae56fcdba75dcae8b75d8a","from_device":"RNQVWSHYZH"} deviceId:XXXXXXXXXX, sender:@myuser:matrix.test.com, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:2=>3, observeOnly:false=>false
18:38:15.878Z D received to-device m.key.verification.start from: @myuser:matrix.test.com id: undefined
18:38:15.879Z I Refreshing/starting the verification transaction timeout timer
18:38:15.879Z D Verification request ae78d5cfb8ae56fcdba75dcae8b75d8a: m.key.verification.start event with id:undefined, content:{"from_device":"XXXXXXXXXX","transaction_id":"ae78d5cfb8ae56fcdba75dcae8b75d8a","method":"m.reciprocate.v1","secret":"d4K+VZ8lwQM/y20"} deviceId:XXXXXXXXXX, sender:@myuser:matrix.test.com, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:3=>4, observeOnly:false=>false
18:38:18.622Z I Verification completed! Marking devices verified:  [["XXXXXXXXXX","ed25519:XXXXXXXXXX","****"]]
18:38:18.622Z I Own device XXXXXXXXXX marked verified: signing
18:38:18.627Z D PUT /sendToDevice/m.key.verification.cancel/m1701190000000.1 {}
18:38:18.627Z D FetchHttpApi: --> PUT https://matrix.test.com/_matrix/client/v3/sendToDevice/m.key.verification.cancel/m1701190000000.1
18:38:18.628Z E error verify getCrossSigningKey callback for self_signing returned falsey
Error: getCrossSigningKey callback for self_signing returned falsey
    at m.getCrossSigningKey (vector://vector/webapp/bundles/f512ff169a3069015b9a/bundle.js:2:1021103)
    at async m.signObject (vector://vector/webapp/bundles/f512ff169a3069015b9a/bundle.js:2:1024950)
    at async J.setDeviceVerification (vector://vector/webapp/bundles/f512ff169a3069015b9a/bundle.js:2:438212)
    at async m.verifyKeys (vector://vector/webapp/bundles/f512ff169a3069015b9a/bundle.js:2:1479351)
    at async m.doVerification (vector://vector/webapp/bundles/f512ff169a3069015b9a/bundle.js:2:1193539)
18:38:18.717Z D FetchHttpApi: <-- PUT https://matrix.test.com/_matrix/client/v3/sendToDevice/m.key.verification.cancel/m1701190000000.1 [90ms 200]
18:38:18.893Z D FetchHttpApi: <-- GET https://matrix.test.com/_matrix/client/v3/sync?filter=xxx&timeout=xxx&set_presence=xxx&since=xxx [3001ms 200]
18:38:18.948Z D received to-device m.key.verification.cancel from: @myuser:matrix.test.com id: undefined
```

Hopefully I removed all private data from log.

**Comment by andrew8er** [comment]
I get the same error:

Element Web console:
```
error verify Error: Key type self_signing from getCrossSigningKey callback did not match
    getCrossSigningKey CrossSigning.ts:156
    signObject CrossSigning.ts:451
    signDevice CrossSigning.ts:476
    setDeviceVerification index.ts:2513
    verifyKeys Base.ts:372
    checkMAC SAS.ts:483
    verifyAndCheckMAC SAS.ts:327
    doSendVerification SAS.ts:389
    ae SAS.ts:254
    verify Base.ts:319
    promise callback*verify Base.ts:319
    startVerification VerificationRequest.ts:477
    E VerificationPanel.tsx:401
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
```

Failing request:
```
PUT /_matrix/client/v3/sendToDevice/m.key.verification.cancel/m1704924562805.162 HTTP/2
Host: matrix-client.matrix.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 207
Origin: https://app.element.io
DNT: 1
Sec-GPC: 1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Authorization: Bearer XXX
Connection: keep-alive
Cache-Control: max-age=0
```

Body:
```json
{"messages":{"@aw8:matrix.org":{"DATDUULJIF":{"code":"m.unknown","reason":"Error: Key type self_signing from getCrossSigningKey callback did not match","transaction_id":"f341e602e13c44ccba60139b418f6e98"}}}}
```

**Comment by evaporei** [comment]
I just had the same issue too :/

Verifier device: Brave, Arch Linux
Device to be verified: Android app, unihertz phone
