### ISSUE TITLE
Change microphone during call

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#15981]
**Is your suggestion related to a problem? Please describe.**
It is cumbersome to change microphone during call (e.g. headset mic or notebook built-in mic).
It should be done in 1-2 clicks, similarly to switching audio output of call on phone.

**Describe the solution you'd like**
Have a dropdown menu of microphones in the call screen **if there are more than one**.

**Comment by SimonBrandner** [comment]
Duplicate of [#15595](https://github.com/vector-im/element-web/issues/15595)
