### ISSUE TITLE
Shortened view of quotes when replying via reply-button in chat

### ISSUE THREAD

**Issue by Gulaschmoerser** [vector-im/element-web#15980]
When replying to a lengthy post in chat via the "reply" button next to a post, the quote above ones answer can take up A LOT of space in chat, wich isn´t great when reading up on an ongoing discussion, especially when an answer to said lenghty post is short, a post is replied to more than once and/or there are parallel strings of chat in one room going on.

It would help with general overview if the quotes were displayed in a shortened way, maybe with a fixed field-length for the quote and a button that gets you to the full related post in a room, or better, if the quote also had a little dropdownbutton to view the full quote above the answer to it instead of the way it is set up now.

Thank you for your great work, stay safe and healthy!

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3553, as replies now limit the quoted message to ~2 lines, and you can easily click the quoted message to jump to it and read the full thing
