### ISSUE TITLE
Update emojibase

### ISSUE THREAD

**Issue by gemstonevirus** [vector-im/element-web#15982]
**Description**
Updating emojibase-data and emojibase-regex would fix https://github.com/vector-im/element-web/issues/14963 as well as https://github.com/vector-im/element-web/issues/13857 as the current version of emojibase-regex includes Regional Indicator Symbol Letter emoji and the current version of emojibase-data contains emoji names that describe their appearance rather than their meaning and are therefore more similar to other platforms (the current names are now legacy). 

Emojibase changelog:
https://github.com/milesj/emojibase/blob/master/packages/data/CHANGELOG.md
https://github.com/milesj/emojibase/blob/master/packages/regex/CHANGELOG.md

**Version information**
- **Platform**: web

For the web app:

- **Browser**: Firefox 84.0
- **OS**: Kubuntu 20.10
- **URL**: https://element.definitionhub.com
- **Version**: 1.7.15

**Comment by ShadowJonathan** [comment]
#13857 has more comments and is older, and is basically the same issue, could this be closed as duplicate?

**Comment by SimonBrandner** [comment]
Closing in favour of #13857
