### ISSUE TITLE
State corruption on unclean exit

### ISSUE THREAD

**Issue by DemiMarie** [vector-im/element-web#15995]
### Description

If Element exits uncleanly (such as with `SIGKILL`), there is a high likelyhood that its data will be corrupted, requiring a restore.  This is particularly important with Flatpaks, which never seem to exit cleanly.

### Steps to reproduce

1. Start Element Desktop
2. Kill Element Desktop with `SIGKILL`.
3. Restart Element Desktop

I expect that Element Desktop will recover successfully, but it does not.

### Version information

- **Platform**: Desktop
- **OS**: Fedora Flatpak
- **Version**: Latest Flatpak

**Comment by novocaine** [comment]
In order to action this, we need logs with the errors experienced on restart showing corruption.

**Comment by turt2live** [comment]
Closing as this is not currently in an actionable state. If this is still happening to people, please open a new issue with fresh information.
