### ISSUE TITLE
A room with two custom widgets doesn't let you distinguish them in RightPanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#15992]
only one widget appears in the RightPanel.

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/ceb521f5-54a9-4ca0-9f3e-016fd9c376f1)
![image](https://github.com/vector-im/element-web/assets/2403652/073bf933-ec42-4397-80fd-76733dac40e7)

No longer an issue
