### ISSUE TITLE
Uncaught TypeError in console: Service workers on desktop

### ISSUE THREAD

**Issue by DemiMarie** [vector-im/element-web#16008]
### Description

I get this message from the console during startup:

```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('vector://vector') is not supported.
```

followed by a backtrace that isn’t particularly meaningful.

### Steps to reproduce

Open the desktop app :smile:

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.15

**Comment by t3chguy** [comment]
This is safe to ignore, its just because we haven't enabled service workers in the desktop app, but the code still tries to register one, the service worker serves only one purpose on the web app, to enable "installation" - which doesn't apply to the desktop app anyway.

**Comment by DemiMarie** [comment]
Understandable!
