### ISSUE TITLE
tabbed view for "View Source"

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#16002]
I often try to "View Source" on an event, only to find that it's in an encrypted room, which means that I need to close the dialog, re-find the event, hit the "..." button again, and then click on "View Decrypted Source".  It would be nice instead of having two menu options to view the event source, there was just a single one that gave you a tabbed view to switch between the encrypted and decrypted versions. e.g. something like

![image](https://user-images.githubusercontent.com/1012976/102658450-94cddb80-4145-11eb-9957-1813c4623197.png)
![image](https://user-images.githubusercontent.com/1012976/102658482-a3b48e00-4145-11eb-9fa6-458b231edc3e.png)

**Comment by harsh7g** [comment]
Hey! I am new to the Matrix Codebase and was looking at this issue to work on. Could someone give pointers to the relevant files in the codebase for this issue ?

**Comment by SimonBrandner** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/context_menus/MessageContextMenu.js
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/ViewSource.js

@harsh7g I think it would be these two files. There's already a vertical tabbed view but I don't think we have a horizontal tabbed view component. If you could create it, it would be great because we could reuse it.

**Comment by SimonBrandner** [comment]
@harsh7g And if you had more questions you can ask in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org?via=matrix.org&via=vector.modular.im&via=mozilla.org)

**Comment by harsh7g** [comment]
Thanks! @SimonBrandner

**Comment by harsh7g** [comment]
@SimonBrandner Could you also put up a link to that Vertical Tabbed View bit ? I'd have a look at that as well.
P.S: Follow-up question so asking here itself.

**Comment by SimonBrandner** [comment]
@harsh7g I think it's this: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/TabbedView.tsx

**Comment by harsh7g** [comment]
I got caught up with something else so was unable to continue work on this. Not sure when I will be able to pick it up again. So anyone else interested, please go ahead and take it up as you wish. Thanks!
