### ISSUE TITLE
Import room keys doesn't work on linux desktop

### ISSUE THREAD

**Issue by pschrammel** [vector-im/element-web#16012]
### Description

Importing room keys don't work.

### Steps to reproduce

 * Export on my phone (android) to gdrive
 * import in element desktop (linux)

Don't know where to find the logs...sorry. Tried to import that file into a browser session seems to work.

![image](https://user-images.githubusercontent.com/27882/102769044-62f58880-4382-11eb-8643-f050b9231339.png)

### Version information

For the desktop app:

- **OS**: Linux
- **Version**: 1.7.15

**Comment by jryans** [comment]
Can you try sending debug logs (top left menu -> Settings -> Help & About -> Submit debug logs) and reference this issue so we can investigate further? Please try importing again just before this.

**Comment by pschrammel** [comment]
version 3.2.1 has resolved it, can't reproduce any more.
