### ISSUE TITLE
Send button

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#16010]
### Description

There's no send button:
![image](https://user-images.githubusercontent.com/973709/102758159-3cc3ee80-436a-11eb-9179-0dd9d9286586.png)

When responding with an emoji, for example, this is very uncomfortable.

### Version information

- **Platform**:  desktop
- **OS**: Fedora 33 Silverblue
- **Version**: 1.7.15

**Comment by SimonBrandner** [comment]
If this were to be implemented, there should definitely be a way to hide it

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/4963
