### ISSUE TITLE
glitchy effects with snowflake and confetti in a single message

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#16017]
### Description

If someone sends a message containing both ❄️ and 🎉 (or 🎆) the effects alternate rapidly.

### Steps to reproduce
Send `❄️ 🎉`

Watch glitchy effect

### Version information

- **Platform**: desktop

- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.16

**Comment by jryans** [comment]
Thanks for the report! 
I think this is effectively the same as https://github.com/vector-im/element-web/issues/16015, so let's track it over there.
