### ISSUE TITLE
Notification Centre design and confusion

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16011]
### The current situation

Currently, there is a button labelled `Notifications` in the top right corner of the app. As I understand it, this is the current `Notification Centre`.

### The problems

This can get confusing. The way the `Notification Centre` is placed makes it seem like the notifications are room-specific.

You have to go to the settings to configure which notifications are going to be displayed. It is in `Settings` > `Notifications` under the `Noisy` column. `Noisy` doesn't indicate to me that it is what will be shown in the `Notification Centre`. This is also quite a slow way to change things.

### Proposal

On the [Element Public Roadmap](https://github.com/vector-im/roadmap/projects/1) you can find [Notifications](https://github.com/vector-im/roadmap/issues/6). It says that a `Notification Centre` is planned.

I think that the `Noisy` column from the `Settings` should be moved into the `Notification Centre` so that you could quickly filter what you see. It should be easily accessible using something like checkboxes.

The `Notification Centre` should also be placed somewhere else, so that it doesn't seem room-specific.

### Additional context

Thank you to @MurzNN and @t3chguy for explaining to me what the current situation is!

**Comment by t3chguy** [comment]
The current Notifications pane is not just for mentions. It's for whatever you configure it in Settings > Notifications under the Noisy column.

**Comment by SimonBrandner** [comment]
@t3chguy Ok, now I think finally understand :D Thank you! I am sorry for all the confusion on my side. I will do some edits to remove the things that are irrelevant.

**Comment by notramo** [comment]
Related: #15245

**Comment by SimonBrandner** [comment]
I am going to close this in favour of [#15245](https://github.com/vector-im/element-web/issues/15245) as I think it mostly covers the issue.
