### ISSUE TITLE
Flatpak for ARM64 Linux

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#16021]
**Is your suggestion related to a problem? Please describe.**
I am trying to run a matrix client on a PinePhone.

**Describe the solution you'd like**
flatpak element. while that exists, it is only packaged for x64 right now.

**Describe alternatives you've considered**
Using a different client might work, but many lack an ARM64 option. Web login also, but it's a bit fiddly since none of the web browsers on the PinePhone have a good UI.

**Additional context**
related to #3718 except that one appears to be kind of focused on the x64 side of things

**Comment by t3chguy** [comment]
The flatpak is unofficial, you ought to reach out to its maintainers. https://github.com/vector-im/element-web/issues/15227 is about an official ARM/64 image.

**Comment by ell1e** [comment]
@t3chguy I'm asking for an official ARM64 **flatpak** image though, not docker. (I believe these are packaged differently, even though they are obviously both containerization technologies.) So I'm not sure #15227 is related, however I can put this into a comment on #3718 if you want me to

**Comment by t3chguy** [comment]
Yeah comment on #3718 would be sane, but it'd likely be much quicker to reach out to the party maintaining the existing flatpak.
