### ISSUE TITLE
```diff highlighting colors are really low contrast

### ISSUE THREAD

**Issue by amstan** [vector-im/element-web#16029]
### Description

Using this syntax in an element message:
~~~
```diff
there already
+addition
-substraction
something that was there already
```
~~~

results in:
```diff
there already
+addition
-substraction
something that was there already
```

The problem here is that the + and - green and red colors in element are really low constrast compared to the background.
I think it looks particularly hard to see in the dark theme (note, you might want to see this image surrounded by dark backgrounds):
![dark](https://user-images.githubusercontent.com/160217/103080086-fb118e80-4589-11eb-848b-13a252877a8c.png)
Note how it's not even green and red, but turqoise and purple.

@teknikaldomain thinks it looks even more unreadable on the light theme (I say it's bearable):
![light](https://user-images.githubusercontent.com/160217/103080182-2a280000-458a-11eb-83f7-03df1634519c.png)

I narrowed down the offending css to https://github.com/highlightjs/highlight.js/search?q=background%3A+%23dfd%3B
But I didn't want to get into making pull requests there, no idea which theme we're actually using for element.

I would do something like:
```diff
.hljs-addition {
-  background: #fdd;
+  background: #f8f;
}

.hljs-deletion {
-  background: #dfd;
+  background: #8ff;
 }
```

This is easy to test with the `Inspect` tool in Chrome.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome, probably irrelevant
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by amstan** [comment]
* insert `good first issue` label here!

**Comment by TeknikalDomain** [comment]
I'm sorry, but if my color math is correct, that's close to magenta and bright cyan, neither of which I think would have contast on a light background, and might pop a little hard on a dark background, depending on how the colors are added.

Feel free to correct my math, but... I don't see that working "better" per se

**Comment by amstan** [comment]
>  https://github.com/highlightjs/highlight.js/search?q=background%3A+%23dfd%3B
> I would do something like:

Now that i look at it again, element doesn't seem to use any of those themes I linked.

> I'm sorry, but if my color math is correct

You are very correct. For some reason the dark theme does something weird where it inverts the color and shows that. Chrome `Inspect` tool confirms it.

> Note how it's not even green and red, but turqoise and purple.

It's like someone swapped the addition and removal colors to 'fix' the invert, turqoise and purple were close enough given the low cotrast.

**Comment by jryans** [comment]
Seems like a visual bug, I'd suggest a PR if you see a clear way to fix it.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6320

**Comment by justin-sleep** [comment]
The dark theme might need darker diff colors than the light theme's. They are currently very low contrast:

![2021-07-20-19:32:46](https://user-images.githubusercontent.com/14955039/126412049-ccb432ff-5c0c-432f-a11f-e634a8535296.png)

**Comment by robintown** [comment]
@justin-sleep Already a PR for that, too: https://github.com/matrix-org/matrix-react-sdk/pull/6355
