### ISSUE TITLE
Ability to Optionally set Email Confirmation upon New Logins

### ISSUE THREAD

**Issue by jph168** [vector-im/element-web#16030]
**An Extra Step to Security**
Suggestion

**Describe the solution you'd like**
An option to enable email confirmation on new logins that works much like steams confirmation process where
a message prompts saying we've sent a code to your email except it can be just a confirmation email or whatever is best suited for this method.

**Why Optional**
I realize not everyone has an email tied to their account understandably but if so this can be a very useful extra measure for security protection to prevent an intruder that figures someones login credentials to delete and or change password etc without being verified.

**Comment by t3chguy** [comment]
This would not be a client option as element runs entirely on your personal machine. This would be a spec or server issue.

**Comment by jph168** [comment]
> This would not be a client option as element runs entirely on your personal machine. This would be a spec or server issue.

O ok thanks should I create an issue report for this default functionality on the server side then that isn't specific to me :)
