### ISSUE TITLE
Visual: custom font not applied on some buttons in the individual session verify dialog

### ISSUE THREAD

**Issue by intelfx** [vector-im/element-web#16038]
### Description

Custom font is not applied on certain buttons in the individual session verify dialog.

### Steps to reproduce

- identity A: start a conversation with identity B
- identity B: log in and cross-sign some sessions
- identity B: log into another session without cross-signing
- identity A: go into info panel, click on identity B, click on the unverified session to invoke the individual session verification dialog

![изображение](https://user-images.githubusercontent.com/1158172/103167453-4bb01280-483c-11eb-9fd1-3c221baa54b3.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 84.0.1
- **OS**: Windows 10
- **URL**: develop.element.io
- Version info:
  ```
  Element version: 852b7d0b8980-react-777c0ca1efd2-js-79fb7bab0b62
  olm version: 3.2.1
  ```

**Comment by tawfiek** [comment]
I want help with this
