### ISSUE TITLE
Very strange graphical bug

### ISSUE THREAD

**Issue by d4f5409d** [vector-im/element-web#16034]
### Description

When I downloaded Element to PC (Windows) I've noticed a very strange graphical bug.

### Steps to reproduce

- Nothing, just using it

Describe how what happens differs from what you expected.

I'll include logs in the app.

Image of the problem:
![elementbug](https://user-images.githubusercontent.com/76624594/103155962-620a8f80-47a4-11eb-96ab-d70befeb550d.png)

### Version information

- **Platform**: Desktop

- **OS**: Windows
- **Version**: 1.7.16

**Comment by Oymate** [comment]
If you could reproduce it please tell the steps

**Comment by d4f5409d** [comment]
### Answering to Oymate:
> If you could reproduce it please tell the steps

### Not reproducible
1. I mean **it is not that type what I specially can reproduce.** 
2. It is the type of bug that is **happening all the time when I use the desktop version.** When I start the app it's okay, but after a few minutes it gets looking like this. 
3. When I open for instance an image, it does not look buggy (_It resets the screen?_) but a few minutes later it is again so weird.


**_I don’t really understand these type of things, but there may be a problem with rendering._**

**Comment by d4f5409d** [comment]
### Final post

After seeing this bug in other applications, I've decided to search up this on Microsoft Forums, and I've found the problem's origin. As I see, we can't fix this issue, and it is not the program's fault.

**_A link to the thread: [click here](https://answers.microsoft.com/en-us/windows/forum/all/weird-visual-glitch-in-apps/49770bd2-3cf9-4952-88ed-7c395ae15dcc)_**


I hope that anyone, who has the same issue, I did help them.

**Comment by jryans** [comment]
Glad to see we've worked out the culprit. Let's use https://github.com/vector-im/element-web/issues/13648 to track adding an option.

**Comment by ara4n** [comment]
for the record, this was fixed by upgrading to Electron 12 - without needing to disable GPU acceleration.
