### ISSUE TITLE
Bridge info settings tab: Clickable url to targeted room from external_url field is disappeared

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#16032]
### Description

Via merge [Bridge info settings tab](https://github.com/matrix-org/matrix-react-sdk/pull/3693) from @Half-Shot there was added page with bridge info, that uses [MSC2346: Bridge information state event](https://github.com/matrix-org/matrix-doc/pull/2346). 

But this page now didn't shows the clickable link to targeted room from `content.channel.external_url` field of `m.bridge` state event, as displayed in merge screenshot, seems something broken?

This link is very useful for quickly jump from Matrix room to same room in native interface of bridged protocol.

### Steps to reproduce

For example, Gitter bridge in [Microsoft/vscode](https://matrix.to/#/#Microsoft_vscode:gitter.im?via=gitter.im&via=matrix.org&via=ru-matrix.org) room was filled this field by right value `"external_url": "https://gitter.im/Microsoft/vscode"`, here is full state event:
```
{
  "content": {
    "bridgebot": "@gitter-badger:gitter.im",
    "channel": {
      "avatar_url": "mxc://gitter.im/eae049e13477aada11ae48458e89a673c5c5aee1",
      "displayname": "Microsoft/vscode",
      "external_url": "https://gitter.im/Microsoft/vscode",
      "id": "55a40f2a5e0d51bd787b439c"
    },
    "protocol": {
      "avatar_url": "mxc://gitter.im/5ca06a9ec041815b7bfe089ec2733507753aa43c",
      "displayname": "Gitter",
      "external_url": "https://gitter.im/",
      "id": "gitter"
    }
  },
  "origin_server_ts": 1608274509929,
  "sender": "@gitter-badger:gitter.im",
  "state_key": "",
  "type": "uk.half-shot.bridge",
  "unsigned": {
    "age": 381213202
  },
  "event_id": "$KqMoNwFVQIpE3jVYNimmOypo3mFWrzXwLmwE-uPbBF4",
  "room_id": "!fxZxLvWcibVaFxWjxq:gitter.im"
}
```

And in Element interface I didn't see this link, here is screenshot:
![image](https://user-images.githubusercontent.com/336662/103137864-fcec6680-46dd-11eb-8bb6-c2276ba95c2e.png)

Can we give back, or re-invent this very useful link in interface?

### Version information
- **URL**: develop.element.io

**Comment by Half-Shot** [comment]
This is fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5454
