### ISSUE TITLE
Room Header: one2one room avatar is not updated correctly

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#1604]
Have changed testbill's photo and it is showing up in the room history but not on the room header.
(For information, testbill's photo was not defined when the room was created)

![ima](https://matrix.org/_matrix/media/v1/download/matrix.org/tEMyrOzmzeJgYBHhLMsmmooU)

**Comment by ara4n** [comment]
I'm also surprised that the colours of the avatars don't match.  Something weird going on there...

**Comment by turt2live** [comment]
I believe we've fixed this. If not, please open a new issue with fresh information.
