### ISSUE TITLE
Guest user message is sent twice

### ISSUE THREAD

**Issue by vonkoff** [vector-im/element-web#16045]
### Description

When a guest joins chat and starts typing then what they wrote out appears twice when sent. Other users in the chat don't see, but the guest user does on his screen. 

### Steps to reproduce

-Join room as guest.
-Join any room.
-Start typing and sending in chats to see the error.

Logs being sent:  yes

![image](https://user-images.githubusercontent.com/16548992/103247425-dbd18300-4934-11eb-8ec1-c0d0bba9cf54.png)

### Version information

- **Platform**:  **Web app**

For the web app:

- **Browser**:  **Chrome**
- **OS**:  **Windows 10**
- **URL**:  Element version: 1.7.16

**Comment by jryans** [comment]
Thanks for the issue, I can reproduce this. I wonder how long it's been this way... 😅

**Comment by t3chguy** [comment]
This looks like https://github.com/matrix-org/synapse/issues/8521

**Comment by t3chguy** [comment]
Yes, closing in favour of https://github.com/matrix-org/synapse/issues/8521
