### ISSUE TITLE
Grouping channels are only limited to the matrix homeserver instead of all servers.

### ISSUE THREAD

**Issue by Oymate** [vector-im/element-web#16047]
### Description
Trying to create group/communities the hone server cannot be changed from matrix to Mozilla or KDE or other servers.

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Press + button in community ribbon
- Try to change the hone server from matrix.org to Mozilla.org/KDE.org
- It doesn't change
- 
### Version information
1.7.16

- **Platform**: web (in-browser) or desktop?
Desktop

For the desktop app:

- **OS**: PopOS
- **Version**: 1.7.16

**Comment by turt2live** [comment]
Communities are currently created on the homeserver you registered with. To create a community on another homeserver you'll need to be using an account on that homeserver.

**Comment by Oymate** [comment]
Is it planned to allow it in future? This is a bit of lock-in to which ever server I first registered.
