### ISSUE TITLE
Creating an account generates but does not save auto suggested Keychain passwords

### ISSUE THREAD

**Issue by doctorpangloss** [vector-im/element-web#16044]
### Description

Creating an account generates but does not save auto suggested Keychain passwords.

### Steps to reproduce

 - Visit matrix.org
 - Click Try Now
 - Click Start Element Web
 - Click Try Element
 - Click Open in your browser
 - Click Create Account
 - Enter a username
 - Click the password field.
 - Click "Use strong password" when Safari suggested a strong password.
 - Observe both password fields are complete.
 - Enter an email address.
 - Click Register
 - Complete the captcha
 - Check the terms of service box and click accept.
 - In a new tab, open your e-mail and accept the verification.
 - Observe "Registration Successful. You can now close this window or log in to your new account."
 - Click the Log In URL
 - Observe the automatically saved password is not shown.

The saved account information should be shown.

<img width="870" alt="Screen Shot 2020-12-28 at 1 30 19 PM" src="https://user-images.githubusercontent.com/2229300/103244123-d6fad800-4910-11eb-8db3-e77e2b84195a.png">

### Version information

- **Platform**: web (in-browser)

- **Browser**: Safari 13.1.2
- **OS**: macOS
- **URL**: app.element.io

For the desktop app:

- **OS**: macOS
- **Version**: 10.15.6

**Comment by aaronraimist** [comment]
It works fine for me in the current version of Safari (14.0.2)
