### ISSUE TITLE
message sticks to the bottom and is not sent

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#16050]
the room is encrypted, the message shows the normal black as if sent, but doesn't appear on other clients

**Comment by bwindels** [comment]
there was no remove or cancel sending or whatever we call it option in the context menu of the stuck event, but restarting eleweb got rid of it unsurprisingly.

**Comment by t3chguy** [comment]
This sounds like a Synapse issue with missing remote echo or broken echo (missing transaction_id)

**Comment by jryans** [comment]
I am going to assume this is an operational / Synapse issue. Feel free to reopen if I misunderstood, or there's something Element should be doing here.
