### ISSUE TITLE
Server Options info dialogue is a bit confusing if the Element config prevents choosing another homeserver

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#16053]
How this dialog normally looks:

![image](https://user-images.githubusercontent.com/1342360/103369961-6e079180-4ac3-11eb-9b03-775b3de2611e.png)

How it looks on Element configs that disable custom server URLs:

![image](https://user-images.githubusercontent.com/1342360/103368819-74e0d500-4ac0-11eb-9471-a257d5f9daa9.png)

(Notice the lack of an Edit button). There is no button for custom server options, so this help dialog is a bit confusing. Perhaps it should be hidden entirely if it's not possible to edit the server URL.

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Linux
- **URL**: https://gnome.element.io

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7215
