### ISSUE TITLE
Stream Screen Option

### ISSUE THREAD

**Issue by TSC255** [vector-im/element-web#16056]
It would be really appreciated if a stream screen feature could be added. It would save lots of time explaining.

I would like to see the stream screen feature in private calls and group calls.

If this isn't possible to add to both maybe just a stream screen option just in group calls.

Regards,

**Comment by t3chguy** [comment]
Its already possible in both. In 1:1 calls it is a little hidden as Shift Click video call button. In Jitsi (group) calls there's a button for it.

![image](https://user-images.githubusercontent.com/2403652/103438557-e721f880-4c2b-11eb-83c3-697fa0658a37.png)

**Comment by SimonBrandner** [comment]
@TSC255 If you are on the desktop there are some problems, see #4880 and #15040. I have a [fix](https://github.com/matrix-org/matrix-react-sdk/pull/5525) for the 1:1 calls hopefully, it will be merged

**Comment by TSC255** [comment]
> Its already possible in both. In 1:1 calls it is a little hidden as Shift Click video call button. In Jitsi (group) calls there's a button for it.
> 
> ![image](https://user-images.githubusercontent.com/2403652/103438557-e721f880-4c2b-11eb-83c3-697fa0658a37.png)

Hello,
I cannot see that option.
Any ideas?

**Comment by SimonBrandner** [comment]
@TSC255 The button is there only in group calls (Jitsi calls). You're probably using the classic Matrix 1:1 calls, in that case, you have to shift-click the call icon as @t3chguy said. 

If this doesn't help can you send a screenshot?

**Comment by TSC255** [comment]
![image](https://user-images.githubusercontent.com/63733044/103440738-2ce8bc00-4c40-11eb-8adf-ec907f590c70.png)

This is what I see in a group call @SimonBrandner

**Comment by t3chguy** [comment]
How many joined members are in the group? That's the 1:1 call UI

**Comment by SimonBrandner** [comment]
@t3chguy Is using a 1:1 call for a group with 2 people intentional? I guess it can be confusing for new users

**Comment by t3chguy** [comment]
Yes, they are more secure given the full end to end encryption.

**Comment by TSC255** [comment]
Ah there is only 2 people in the group, that explains it.
But in the 1:1 call when I shift click the call nothing happens

**Comment by t3chguy** [comment]
Your screenshot is of a Voice call, you have to shift click the Video call button, given its a video stream.

**Comment by TSC255** [comment]
![image](https://user-images.githubusercontent.com/63733044/103441302-d6ca4780-4c44-11eb-9020-2c3f0f80dc1b.png)
When I shift click it just highlights the video call option.

**Comment by SimonBrandner** [comment]
@TSC255 Aren't you on the desktop app? If so, it won't work.

Btw, I am sorry if I confused you by saying `Call button`

**Comment by TSC255** [comment]
@SimonBrandner Thanks again

**Comment by SimonBrandner** [comment]
You're welcome
