### ISSUE TITLE
Indentention using tabs in composer

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16061]
**Is your suggestion related to a problem? Please describe.**
I can't use the tab key for indentation in the message composer.

**Describe the solution you'd like**
Pressing the tab key should either write a tab character or it should write `n` spaces. Ideally, this should be configurable.

**Describe alternatives you've considered**
I can hit the spacebar 4 times every time I would normally hit tab. Or I could write the code somewhere else and then copy and paste it. Both solutions are obviously impractical.

**Comment by t3chguy** [comment]
This would conflict with accessibility where tab should navigate around the app (not that it rightly does now but that's a known issue)

It'd have to be opt-in at minimum

**Comment by SimonBrandner** [comment]
That makes sense :+1: Maybe a solution would be to unfocus the composer when the user presses escape or something like that.

**Comment by t3chguy** [comment]
That would still be non-obvious for users relying on ARIA standards. Also it conflicts with other things like dismissing reply status and marking room as fully read

**Comment by SimonBrandner** [comment]
Then, I guess making it opt-in is the only way.

I've also thought about using `Ctrl + tab` for indentation but that is unintuitive and there's probably a better use for it (maybe switching between spaces).

**Comment by t3chguy** [comment]
Ctrl Tab is already used for going to next tab in browsers, overriding it would likely piss off a lot of people

**Comment by SimonBrandner** [comment]
Oh, yeah I was thinking in terms of the Electron app. Discord uses `Ctrl + Tab` for switching between "server"

**Comment by SimonBrandner** [comment]
I am going to close this as I can't really see an intelligent way to make this work and it would just lie here for eternity. If anyone has any solutions, _feel free_ to ping me
