### ISSUE TITLE
No send button is available for sending messages

### ISSUE THREAD

**Issue by 2580ayush2580** [vector-im/element-web#16076]
**Is your suggestion related to a problem? Please describe.**

when I tried to send a message in the element web app then I noticed that there is no send message button.
My keyboard's enter key is not working and that's why I am not able to send any message. 

![issue3](https://user-images.githubusercontent.com/56980422/103675372-dd8aee80-4fa5-11eb-85e6-68bdb9ba92fa.png)

**Describe the solution you'd like**
I think we should add a send button.

**Describe alternatives you've considered**

**Additional context**

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/4963
