### ISSUE TITLE
Element gets stuck when you back out of entering your security key during login

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#16072]
Steps to reproduce:
1. Login to your account
2. When you see the "Verify this login" screen, click "Use Recovery Key"
<img width="623" src="https://user-images.githubusercontent.com/5855073/103593785-63cb0600-4ebc-11eb-92d4-0a023a6df29c.png">
3. Click "Go Back"
<img width="835" alt="Screen Shot 2021-01-04 at 6 41 28 PM" src="https://user-images.githubusercontent.com/5855073/103593824-7f361100-4ebc-11eb-8768-2f44e706550d.png">

Element gets stuck, this spinner will spin forever:
<img width="1367" src="https://user-images.githubusercontent.com/5855073/103592891-e0101a00-4eb9-11eb-9015-302d3ef1b56d.png">

**Comment by jryans** [comment]
Thanks, I believe this is a duplicate of https://github.com/vector-im/element-web/issues/15584, but please reopen if I misunderstood.
