### ISSUE TITLE
Apple silicon: build and publish nightly builds

### ISSUE THREAD

**Issue by blackcodefr** [vector-im/element-web#16075]
Make element compile for both x86_64 and arm64 versions using electron 11.

---

@jryans: Tasks needed to support this:

* [x] Upgrade to Electron 11 (first version to support macOS aarch64)
* [x] Work out some way to access macOS aarch64 for testing
* [x] Configure `electron-builder` to build for new architectures
* [x] Add macOS aarch64 support to desktop's native build pipeline

**Comment by jryans** [comment]
Thanks, we indeed intend to offer this in the future. At the moment, we slightly stuck as [Electron 11 introduces graphical issues](https://github.com/vector-im/element-web/issues/15869) for some users. We'll need to get past that, and then work out various build related activities from the new architecture.

**Comment by t3chguy** [comment]
@jryans now that we're on Electron 11 what is the plan here?

**Comment by jryans** [comment]
I written out some more detail on the remaining tasks [above](https://github.com/vector-im/element-web/issues/16075#issue-779098622). At the moment, the Web Platform team doesn't have any macOS aarch64 hardware, so testing whether things work might be a bit slow. I'll check on what we want to do about that.

@blackcodefr, @robintown, et al: For those on macOS aarch64 / Apple Silicon / M1 machines today, how urgent is this? Is the app still usable for you via Rosetta today?

**Comment by blackcodefr** [comment]
The app is usable today. It would be a better macOS citizen and would use less ressources if it was native though. I am willing to try beta builds if you want, just le me know.

**Comment by blackcodefr** [comment]
Otherwise of you have some budget, you can rent a M1 Mac mini on macstadium starting 109$ per month. https://www.macstadium.com/configure?p=minii58250&c=VGS2

**Comment by aaronraimist** [comment]
Wow it was surprisingly easy to build. I was able to build an Apple Silicon version out of the box without any real issues. Only tested things briefly but everything seemed to work including seshat. The only issue I ran in to was when I used Node 16 I hit https://github.com/electron-userland/electron-builder/issues/5668 but downgrading to Node 14 made everything work.

It does use a less RAM, not a huge amount less but it is noticeable.

Native:
<img width="930" alt="Apple Silicon" src="https://user-images.githubusercontent.com/5855073/116345376-9a02fd00-a7ad-11eb-859a-eda4f958ef8f.png">

x86 through Rosetta:
<img width="930" alt="Intel" src="https://user-images.githubusercontent.com/5855073/116345367-97080c80-a7ad-11eb-88dd-6132031849f4.png">

The universal version comes out to 426MB on disk whereas the Apple Silicon version is 266MB and the x86 only version is 255MB. I would still vote for doing only a universal binary though. I think the reduced confusion and reduced packaging/distributing complexity makes up for the file size.

**Comment by blackcodefr** [comment]
I believe that at install, the unused binary is removed from disk. Is that so ?

**Comment by aaronraimist** [comment]
No Element doesn't have any installation process. You download the app and then you run it. Nothing is discarded.

**Comment by blackcodefr** [comment]
I believe the system may handle that by itself. Maybe at first run ? Anyway, doesn't matter that much.

**Comment by avion540** [comment]
Personally I'm most interested in the energy impact difference between the AS vs Universal versions.

**Comment by aaronraimist** [comment]
> I believe the system may handle that by itself. Maybe at first run ? Anyway, doesn't matter that much.

If you find any documentation to that affect I'd like to see it but I have not heard of anything like that and the binary definitely does not get smaller after first run. Part of the selling point of the universal binary is that the user has the option to run the software under Rosetta if they want. For example Photoshop offers a universal binary but told users if they were using some specific plugins then they may have to run it under Rosetta. If the system discarded the x86 portion then it wouldn't be possible to do that.

> Personally I'm most interested in the energy impact difference between the AS vs Universal versions.

Presumably you mean AS vs Intel. AS vs Universal is no difference because Universal just means if you are on an M1 then it runs AS code and if you are on an Intel Mac then it runs x86 code.

Not super scientific but I looked at the energy usage according to activity monitor while the app was idle as well as scrolled through a room and there is not a significant difference between the AS and Intel versions. It's still Electron which is still Chrome. Unfortunately It's not going to be magically battery friendly.

**Comment by blackcodefr** [comment]
You're right. That must have been a thing only in the PowerPC->Intel era.

**Comment by aaronraimist** [comment]
There might be an option that can be set to do that but I haven't seen it in the docs.

**Comment by jryans** [comment]
I have restructured the issues here a bit: this one is now focused on only building and publishing nightly builds for Apple silicon, which is nearly done.

The remaining bits and open questions are now in separate issues:

* https://github.com/vector-im/element-web/issues/17757
* https://github.com/vector-im/element-web/issues/17758
* https://github.com/vector-im/element-web/issues/17759

**Comment by jryans** [comment]
Nightly builds of Element Desktop optimised for Apple silicon are [now available](https://packages.riot.im/nightly/install/macos/arm64/Element%20Nightly.dmg) for testing! Please give it a try and report any issues.

The remaining tasks have separate issues, so it looks like we're done over here. 🎉
