### ISSUE TITLE
Missing session data

### ISSUE THREAD

**Issue by zsinskri** [vector-im/element-web#16078]
### Description

After rebooting my laptop, Element Desktop has signed me out.

### Steps to reproduce

Unknown, I don't expect to be able to reproduce this, it did never happen before.

Logs being sent: yes

![image](https://user-images.githubusercontent.com/19800705/103679487-2ed6b600-4f85-11eb-8d18-8b30f81f6538.png)

### Version information

- **Platform**: Element Desktop

For the desktop app:

- **OS**: Guix GNU/Linux
- **Version**: 1.7.16 from flathub

**Comment by zsinskri** [comment]
I also have captured Element's stdout/stderr. `--- booting shepherd ---` lines correspond to PC boots, `Connecting......` is from `nm-online -t 8`:
```
--- booting shepherd ---
Connecting...............    8s [online]
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
Connecting.                  8sTerminated
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
--- booting shepherd ---
Connecting...............    8s [online]
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
--- booting shepherd ---
Connecting...............    8s [online]
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
Error: Could not create NMClient object: Could not connect: No such file or directory
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
Error: Could not create NMClient object: Could not connect: No such file or directory
--- booting shepherd ---
Connecting...............    8s [online]
/home/zsin/.var/app/im.riot.Riot/config/Element exists: yes
/home/zsin/.var/app/im.riot.Riot/config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
```

The last one is the instance the showed above error message.

**Comment by zsinskri** [comment]
Interestingly after loging in I was on the light theme, but by restarting the dark theme was restored.

Also the "Security & Privacy" settings show the old session in a bold font (i.e. as active?) but the "Last seen" date is updated on the new session.

**Comment by zsinskri** [comment]
Another restart and I'm logged out again, this time without popup message.

I removed `~/.var/app/im.riot.Riot` and now have a third session created on this device. This session is both shown in bold and updates it's `Last seen` date.

I've again send the debug logs.

**Comment by jryans** [comment]
Thanks for filing and sorry for these troubles. The debug logs unfortunately don't provide much additional insight... Mainly they just emphasise that the app storage was somehow cleared.

You mentioned that you are using the Flathub package... This is an unofficial package that is community maintained. It's possible that Flathub sandboxing might be getting in the way here...?

**Comment by zsinskri** [comment]
The same issue happened shortly after to someone using the Flatpak on Ubuntu. Migrating them to the official deb / apt-repo has apparently prevented the issue from reoccurring.

To me on Flatpak (can't install the deb as easily on GNU Guix) it did happen a few additional times early on, though now it's been stable for quite some time.

So it seems the Issue was infact with the Flatpak packaging (and even that might be resolved by now).

… thanks for the great app, anyways!

**Comment by dylangerdaly** [comment]
This has happened to me just now, it's happened before also.

**Comment by dylangerdaly** [comment]
It's literally wiped E2EE Seshat (EventStore)

**Comment by SimonBrandner** [comment]
@dylangerdaly, please open a new issue
