### ISSUE TITLE
Ongoing rooms /events stream for a joined room

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#1607]
After creating a 1:1 room there is an ongoing events stream, e.g.:

```
/_matrix/client/r0/events?room_id=!nSDXcqITYQOwemzUEf%3Amatrix.org&timeout=30000&from=s23723119_10771800_2748_1816477_7197_2731&access_token=...
```

**Comment by ara4n** [comment]
this is confused peeking code, I guess.  It sounds like you're about to remove the v1 peeking crap whilst doing paginated sync, which will help this a lot...

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/1229 I think
