### ISSUE TITLE
No "send" button to actually send a message on a keyboard-less tablet

### ISSUE THREAD

**Issue by muelli** [vector-im/element-web#16089]
![Screenshot 2021-01-07 at 12 27 18](https://user-images.githubusercontent.com/322807/103992524-84cd7880-5194-11eb-92f4-6ae06f8425a6.png)

### Description

I cannot send a message, because there is no send button and the soft keyboard does not send "enter", but rather makes it a new-line.

### Steps to reproduce

- Get a ChromeOS tablet
- open the element client in the Chrome browser
- try to send a message
- see no button to send a message

I expected to be able to actually send a message with the chat client.

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome 87.0.4280.109
- **OS**: ChromeOS
- **URL**: gnome.element.io it says it's v1.7.16.

**Comment by SimonBrandner** [comment]
I believe this is a diplicate of #4963

**Comment by muelli** [comment]
Yeah, looks like. Sorry, I did search, but obviously for the wrong things. I've tried "tablet" and "send button". Sorry for the noise.

**Comment by SimonBrandner** [comment]
@muelli It's fine. You can close this and add a comment to the already exsiting issue.
