### ISSUE TITLE
Can't login on Firefox 78.6.0esr; spinner infinitely hangs 

### ISSUE THREAD

**Issue by christophehenry** [vector-im/element-web#16082]
### Description

I haven't been able to connect to Matrix uging app.element.io using Firefox 78.6.0esr for a few weeks now. 
When I hit the login button, the loader just hangs infinitely.

The JS console displays a `DOMException` in ` MatrixChat.tsx`. Here is the full message:

```
Uncaught (in promise) DOMException: The operation failed for an operation-specific reason MatrixChat.tsx:706:17
    ge MatrixChat.tsx:706
    AsyncFunctionThrow self-hosted:698
```

### Steps to reproduce

- Use Firefox 78.6.0esr
- try to login
- spinner infinitely hangs
- console should display the error mentionned above.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 78.6.0esr 
- **OS**: Mageia 7
- **URL**: app.element.io

**Comment by t3chguy** [comment]
Unfortunately Firefox 78 is not a supported environment, it is likely it lacks some WebCrypto or otherwise feature or implements it differently hence not being able to complete certain actions https://github.com/vector-im/element-web#supported-environments
