### ISSUE TITLE
Video call shows black screen and no audio

### ISSUE THREAD

**Issue by luckshot** [vector-im/element-web#16088]
### Description

Initiating video call rings and answers correctly, but no remote video or aduio.  Local camera picture-in-picture works, but call video is just a black screen with no audio.

### Steps to reproduce

- join DM with someone
- press video call button
- have DM target answer call
- observe call is answered

Expectation:  Caller can see target's camera feed and hear audio.
Actual:  No video from target.   Target also has no video/audio from caller.

Log: sent/not sent? Sent. 

### Version information

- **Platform**: web (in-browser) or desktop? 
- Windows 10 desktop app
- Versions
Element version: 1.7.16
olm version: 3.2.1

**Comment by luckshot** [comment]
debug logs attached.
[rageshake.zip](https://github.com/vector-im/element-web/files/5783928/rageshake.zip)

**Comment by alexei-g-aloteq** [comment]
It seems that you need to install and configure a TURN server. I did it and video works pretty well.

**Comment by luckshot** [comment]
I think you're right.  Some of our users have slightly different clients
that show an error message to that effect, but it's very random.
Interesting that there's an error message only sometimes.  Guess that
should have a bug report of its own.

**Comment by dbkr** [comment]
Yep, looks like the client the logs are from is only getting host candidates, and hasn't got any candidates at all from the other side, so installing a turn server is probably the way to go.

**Comment by luckshot** [comment]
We got a Turn server up and going, after clients are restarted everything works as it should!  

Thanks everyone looks like maybe the desktop client should have a warning about not having a turn server, but otherwise this bug's probably solved as EBKAC.

**Comment by jryans** [comment]
I sounds like the immediate issue is resolved here, so I'll close this. The VoIP team is separately considering better diagnostics.
