### ISSUE TITLE
Registration process: Ask if user wants to add phone number

### ISSUE THREAD

**Issue by jwsp1** [vector-im/element-web#16098]
I believe most mainstream users want to connect their phone number to the account in order to be found faster by contacts easier.
I understand that many don't want to enter a phone number, so this should be just opt-in.

Something like: "Do you want to add your phone number to this account in order to be found faster by your contacts?"
Yes --> Let user enter the number. No --> Show how to find friends (e.g. show how a username looks like, match via QR-Code,...)

Otherwise, new users might get frustrated right at the beginning because they can't find any contacts in their contact list and think that no one else is using Matrix (because they are used to see all contacts from the phone book).

**Comment by jryans** [comment]
We used to have something like this, but found it caused registration to drop if there was any deliverability issues with the phone number.

We are very aware of the need to find each other as other apps do, so we’ll keep this in mind. Thanks for the feedback!
