### ISSUE TITLE
Reject and ignore may ignore unrelated user?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16097]
https://twitter.com/whitequark/status/1347918499876925445?s=20 says that a failed reject + ignore managed to ignore the wrong user after the reject failed.

**Comment by whitequark** [comment]
If I remember correctly, what happened is that I had both the Freenode bridge and the contact at issue send me an invite (no idea why the bridge would invite me, whatever technical reason) and when I tried to reject + ignore contact at issue, it didn't do anything (didn't update the UI either) and I clicked on it a few more times. I might have clicked again on the contact at issue to refresh that UI pane. I think some of that might have caused a race condition.

**Comment by ara4n** [comment]
so the user which got accidentally ignored was the Freenode bridge? (the reason the bridge DMs you is to send you status updates - e.g. telling you whether you're currently connected, as which user, and gives you a way to set your nick on IRC etc, ftr).

**Comment by whitequark** [comment]
Yes, it was the Freenode bridge, and the user I tried to ignore was *not* ignored.

**Comment by t3chguy** [comment]
Given 0 recurrence of this going to close it as an act of cosmic rays
