### ISSUE TITLE
Search broken on Element desktop app: "Use the Desktop app to search encrypted messages"

### ISSUE THREAD

**Issue by geckolinux** [vector-im/element-web#16091]
Hi there, I'm running Element 1.7.16 (olm version: 3.2.1) on openSUSE Tumbleweed, installed from [this RPM repo](https://download.copr.fedorainfracloud.org/results/taw/element/opensuse-tumbleweed-x86_64/). I also tried this [AppImage](https://github.com/srevinsaju/element-appimage/releases/download/stable/Element-v1.7.16-GLIBC-2.17.AppImage). They both behave the same, local searching on encrypted chats no longer works, instead it throws this erroneous message:

> **Message search**
> Element can't securely cache encrypted messages locally while running in a web browser. Use Element Desktop for encrypted messages to appear in search results.

![Screenshot_2021-01-08_08-44-20](https://user-images.githubusercontent.com/2692138/104022137-df170b00-518d-11eb-844a-8633c3cc17b6.png)

This appears to be a regression on version Element 1.7.16, as it used to work, I believe it was with <=Element 1.7.15.

I'd prefer to not submit my Debug Logs because I don't want my username to be published. Please let me know if I can help with any other information. Thanks!

**Comment by florian6973** [comment]
I'm experiencing the same issue. And will it be implemented on Android?

**Comment by uhoreg** [comment]
If you are using Element desktop packaged by someone else (e.g. the rpm or AppImage builds), you may have to contact the packagers.  It could be that they are not building or packaging the components needed for searching.

**Comment by florian6973** [comment]
Thanks for the tip. It seems to be working again for me.

**Comment by geckolinux** [comment]
@uhoreg Thanks for the reply. There used to be problems with searching with builds from this RPM maintainer, but the [errors it threw](https://github.com/taw00/element-rpm/issues/36) were different, and eventually it was fixed. So I don't think it's a problem with the package, as the maintainer is aware of how to enable support for searching.

**Comment by progserega** [comment]
I expect this issue in 1.7.13, try update to 1.7.16 - and this not help - bug was not gone.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/14229

**Comment by geckolinux** [comment]
Nice find, thanks!

This fixed it for me:
https://github.com/vector-im/element-web/issues/14229#issuecomment-745276193
We'll see if it keeps happening though.

Closed as dupe with #14229
