### ISSUE TITLE
Certain stickers fail to load

### ISSUE THREAD

**Issue by blissfulkittyninja** [vector-im/element-web#16107]
### Description

Certain stickers such as the Monero girl crying and Monero girl happy fail to load.

### Steps to reproduce

- Send a "Monero girl crying" sticker.
- The sticker never loads and instead just displays the element smiling placeholder picture. This issue seems to be similar to #14048.

![element-placeholder-1](https://user-images.githubusercontent.com/77218163/104113328-931bb180-52c6-11eb-8749-8d53df5f20ce.PNG)

Logs being sent: no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.6

**Comment by ara4n** [comment]
This was theoretically fixed in https://github.com/matrix-org/synapse/issues/4988 - but having landed the function, was it ever actually configured on matrix.org?

**Comment by blissfulkittyninja** [comment]
It's fixed, thank you!
