### ISSUE TITLE
no way to proceed after verification requests for both login sessions fail

### ISSUE THREAD

**Issue by ckhung** [vector-im/element-web#16108]
### Description and Steps to reproduce

- I login the web app using firefox.
- Then I login using the element.io app from my android phone.
- The android app asks for verification.
- I accept the verification in firefox.
- But the verification step never completes (it keeps circling .. I hope you know what I am saying)
- After a while, I (maybe did a few stupid things I don't remember and then) logout from the app and close the firefox tab
- Login to the android app and fo the web app again.
- Now both ask for verification as shown in the attached screenshots and I have no way to proceed :-(

Will submit the debug log in a few minutes.

I have found a few related issues such as #15225 and have read people mentioning QR code and/or passphrase but I don't see any such option in these two screen shots. Can we add some such button to the verification dialog as an alternative to verifying from the other devices? And also please advise exactly what I can do now to get out of this deadlock. Thanks!

### Version information

For the web app:
- Firefox 79.0 on Linux mint 20 (ulyana)
- https://app.element.io/#/home

For the android app:
- element 1.0.11 [40100110] (F-dffdcfe1) installed from f-droid
- OS is LineageOS 17.1 (android 10)

![lineage](https://user-images.githubusercontent.com/3609806/104113418-85047a00-5334-11eb-92bf-1d252ebd8c90.jpg)
![webapp](https://user-images.githubusercontent.com/3609806/104113420-8635a700-5334-11eb-8948-07369a994620.jpg)

**Comment by jryans** [comment]
As far as I can tell, this seems like the same issue as https://github.com/vector-im/element-web/issues/16184, so it seems to be a bit of UX gap at the moment. I would suggest choosing "Skip" on the verification prompt in web. You can then use the Security settings to reset your passphrase if you wish.
