### ISSUE TITLE
Error building element desktop

### ISSUE THREAD

**Issue by hramrach** [vector-im/element-web#16104]
### Description

element-desktop fails to build

### Steps to reproduce

Follow the element-desktop readme:

git clone https://github.com/vector-im/element-desktop
cd element-desktop
yarn install
yarn run fetch --importkey
yarn run fetch --cfgdir ''
yarn run build:native

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp',
  path: '/usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp',
  spawnargs: [ 'rebuild' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version information

v1.7.16-3-g8ae1a51

For the web app:

- **OS**: openSUSE Tumbleweed
- **URL**: https://github.com/vector-im/element-desktop

**Comment by jryans** [comment]
Does node-gyp exist at the path mentioned?

**Comment by hramrach** [comment]
Why it should?

**Comment by jryans** [comment]
What? 😕 Does the file `/usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp` exist or not...?

**Comment by hramrach** [comment]
ls -lh /usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp
ls: cannot access '/usr/src/element-desktop/.hak/keytar/build/node_modules/.bin/node-gyp': No such file or directory

**Comment by jryans** [comment]
@hramrach Hmm, I am wondering if it's an ordering issue... Looks like our [official builds](https://github.com/vector-im/element-builder/blob/1d386b6918b14b032188eaf4eeb4026a0879bfe1/src/desktop_release.js#L330-L338) run `yarn run hak check` before building native components. Does this change anything?

**Comment by hramrach** [comment]
no change

**Comment by jryans** [comment]
Hmm, I've run out of ideas. Since I haven't heard of trouble from others, this feels like a system specific issue. I would recommend discussing this in #element-web:matrix.org instead for more interactive discussion.

**Comment by hramrach** [comment]
Seems to be incompatible with node16. After switching the default to node10 while building a package that requests a specific version in build instructions the problem went away.
