### ISSUE TITLE
Need a way to verify logins when all sessions have been closed

### ISSUE THREAD

**Issue by ninjapretzel** [vector-im/element-web#16109]
**Is your suggestion related to a problem? Please describe.**
When logging in again, I was constantly prompted to use sessions that no longer exist to verify new logins.
This may be because I have an old account, but I reinstalled my computer (blowing away my old OS HDD) and installed element on a fresh install of windows.

Prior, I had not even been prompted to export security key or anything (after having this happen a few times, I found the setting and exported my security key and stored it alongside my password information in a password manager.)

**Describe the solution you'd like**
When logging in for the first time, prompt and encourage the user to export the a secret key as a backup.
If you already do that (since I'm not a 'new user' again), then cool.

**Describe alternatives you've considered**
Other ideas include maybe offer a tutorial on first login, which walks the user through the security around account sessions and verification.

**Comment by jryans** [comment]
Thanks for the report. I believe this is the same as https://github.com/vector-im/element-web/issues/16184, so let's focus on that as the canonical issue.
