### ISSUE TITLE
Field doesn't contain a valid alias configuration error on docker build

### ISSUE THREAD

**Issue by AyoubGhaddab** [vector-im/element-web#16119]
### Description

Hello, i wanted to install Element develop branch using docker; I have foloowed the steps mentioned in github:
sudo docker build -t chat

--build-arg USE_CUSTOM_SDKS=true 

--build-arg REACT_SDK_REPO="https://github.com/matrix-org/matrix-react-sdk.git" 

--build-arg REACT_SDK_BRANCH="develop" 

--build-arg JS_SDK_REPO="https://github.com/matrix-org/matrix-js-sdk.git" 

--build-arg JS_SDK_BRANCH="develop" 

.
during the yarn install step, i have got this error:
using description file: /src/react-sdk/package.json (relative path: ./src)
Field 'matrix_src_browser' doesn't contain a valid alias configuration
Field 'browser' doesn't contain a valid alias configuration
using description file: /src/react-sdk/package.json (relative path: ./src/component-index)
no extension

how can I solve this ? thank you
### Steps to reproduce

- run `docker build -t chat` in Element web project

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **OS**: Ubuntu

**Comment by kkorniszuk** [comment]
Did you find any solution?

**Comment by jryans** [comment]
Thanks for the report, I can see that Docker Hub builds of `develop` are also failing, likely in a similar way. (Though release builds are working.) I'll take a look soon, hopefully on Monday.

**Comment by jryans** [comment]
Docker Hub develop builds are working again, so I assume this also fixes the issue for reporters here as well, but do let us know if there's further trouble.
