### ISSUE TITLE
Element Desktop freezes in Debian Testing/Bullseye

### ISSUE THREAD

**Issue by wytchmaster** [vector-im/element-web#16115]
### Description

After updating my Debian testing machines last week (ca. 07./08. january 2021), all chromium-based programs hang after start. And so does element-desktop. 

### Steps to reproduce

- start element-desktop
- after 1-2 seconds the program becomes unresponsive

I already tried the latest nightly build, but element-desktop does not want to work anymore. Other chromium-based programs (brave browser, vivaldi-browser & google chrome) work after installing the latest nightlies. The stable versions and beta versions don't seem to work.

This is reproducable on most of my machines. (AMD Ryzen with AMD Vega Graphics, Intel Core i7 and Core i5 with Intel HD Graphics or Intel with dedicated NVidia Graphics). 

I have one machine with Intel Xeon CPU and dedicated AMD Radeon Pro Graphics and one Laptop with Intel Core i7 and Intel GPU which doesn't have this problem.

This bug seems to exist in Vivaldi too: https://forum.vivaldi.net/topic/55268/debian-testing-vivaldi-not-working-anymore-after-dist-upgrade-vb-75804

### Version information

- **Platform**: Desktop 

For the desktop app:

- **OS**: Debian testing (bullseye) AMD64
- **Version**: 1.7.16

**Comment by SimonBrandner** [comment]
Weird, I am on Debian testing/Bullseye as well. I upgrade every day and everything works just fine.

Info:

Operating System: Debian GNU/Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-1-amd64
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6400 CPU @ 2.70GHz
Graphics Processor: GeForce GTX 1060 3GB/PCIe/SSE2

**Comment by lefcha** [comment]
@wytchmaster What version is your `libx11-xcb1`? I got this problem when I upgraded this package to `2:1.7.0-1` (from `2:1.6.12-1`).  I downgraded it, and `element-desktop` works again now.

Also the problems with chromium are probably somewhat related to `libx11-xcb1`, too:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979590
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979443

**Comment by SimonBrandner** [comment]
@wytchmaster I am on `2:1.6.12-1` too

**Comment by wytchmaster** [comment]
The PC which is working has libx11-xcb 1.6.12-1, the machines which have the problem have 1.7.0. I will try to downgrade that machines when I am back in office. Thanks for the hint.

**Comment by lefcha** [comment]
@SimonBrandner Do you have any idea if this mean that `element-desktop` will have to be updated/fixed in regards to the newer version of `libx11-xcb1`?  Debian unstable/sid already uses that version, and probably testing/bullseye will get it in a few days.

**Comment by SimonBrandner** [comment]
@lefcha No, I don't know. This may be a bit of a problem...

**Comment by SimonBrandner** [comment]
@lefcha Do you know if updating Electron fixes this?

**Comment by lefcha** [comment]
@SimonBrandner Good point, it's probably related to Electron than Element... I have no idea though.

**Comment by wytchmaster** [comment]
As far as I can say, the nightly builds of the chromium-based browsers work ( tested Vivaldi, Google Chrome & Brave). The betas and stable versions suffer from this problem. So maybe an electron update will fix it.

**Comment by wytchmaster** [comment]
As said in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979590 there are 2 options working: downgrade libx11-xcb1 to 1.6.12-1 or upgrade libx11-6 to 1.7.0. It is important that both packages have the same version number. Unfortunately some of the software packages mentioned above has only the dependency for libx11-xcb1. So libx11-6 stays the old version. BTW this solution solved a problem with KDE 5.20 in Debian testing also :-)
So it **is not a problem of the element-messenger**. Thank you for the fast support and for this great piece of software.

**Comment by lefcha** [comment]
I just verified that Element works fine in Debian unstable/sid with the new `libx11-xcb1` so it's a combination with `libx11-6` that is the problem in testing/bullseye. So it should be also fixed in testing/bullseye a few days.
