### ISSUE TITLE
Submit Element.io brand logo to fontawesome

### ISSUE THREAD

**Issue by c-nv-s** [vector-im/element-web#16117]
Is it possible for somebody to submit the element.io brand logo to fontawesome
[https://fontawesome.com/icons?d=gallery&s=brands](https://fontawesome.com/icons?d=gallery&s=brands)

or otherwise just make the brand media assets pack ( .svg .png etc ) available somewhere

**Comment by jryans** [comment]
Various logos are available in https://github.com/vector-im/logos. Fork Awesome [already has](https://forkaweso.me/Fork-Awesome/icon/matrix-org/) at least the Matrix icon, which is perhaps better to use as it's more general than one client. In any case, I don't think it makes sense to track this here in Element Web.
