### ISSUE TITLE
Video PiP overlay makes it impossible to read messages in other rooms

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-web#16116]
I really like the new PiP overlay but having it in the bottom corner of the room view is very very frustrating. When PiP is active it's because you want to interact with another room while being on the call. With the overlay in the bottom right of the room this is largely impossible. I can't read long messages and I can't reply or react to messages because the immovable PiP overlay is covering all of them up.

I would suggest that this overlay is made to be moveable around the room, but also it should **default to the top corner of the room** as this is where it would be least in the way (also this is where most peoples webcams are, so it would be closer to eye line).

**Comment by c33s** [comment]
should be additionally labeld with ui/ux
 
### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: win
- **Version**: 1.7.16

![image](https://user-images.githubusercontent.com/649209/105249744-e28c9800-5b78-11eb-9610-5646bfdbf7fe.png)


![image](https://user-images.githubusercontent.com/649209/105249763-e9b3a600-5b78-11eb-9f24-fd8ec05556bf.png)
