### ISSUE TITLE
Clean the Dockerfile and use Docker compose

### ISSUE THREAD

**Issue by danger89** [vector-im/element-web#16121]
**Is your suggestion related to a problem? Please describe.**

I'm running already a reverse proxy (Nginx), I do not want to run the Docker image with another nginx server.

**Describe the solution you'd like**

The best solution would to clean the Dockerfile, by just providing the element web service. And create a docker-compose.yml file if you want to link the service with other services (like Nginx).

**Describe alternatives you've considered**

Trying to disable the Nginx in the Dockerfile, which is not possible, unless you create your own copy of the Dockerfile.

**Additional context**

[Read more](https://docs.docker.com/compose/)

**Comment by turt2live** [comment]
Element web is just a pile of static assets that can be thrown onto a webserver. This is all the Docker image is.

If you want to avoid using a second nginx the best thing would be to deploy the assets manually to your own webserver.

**Comment by danger89** [comment]
@turt2live  That is not true! How to manage the versions? And why is there still a `yarn build` need?

**Comment by turt2live** [comment]
The build steps are needed to get that pile of static assets. You don't need to run them at production.

Visit #element-web:matrix.org for further support.
