### ISSUE TITLE
Run the desktop to report an error. By prompting the error step by step, I don't know what the reason is and can't run

### ISSUE THREAD

**Issue by hero008** [vector-im/element-web#16126]
![image](https://user-images.githubusercontent.com/35803375/104322018-55fe2c00-551f-11eb-813d-c3a912787c01.png)
![image](https://user-images.githubusercontent.com/35803375/104322030-5a2a4980-551f-11eb-9380-dadc1f0c584b.png)

**Comment by hero008** [comment]
run in window

**Comment by t3chguy** [comment]
Did you run `yarn run build:native` as per the docs?

https://github.com/vector-im/element-desktop#building

**Comment by hero008** [comment]
I just want to run Element locally

**Comment by hero008** [comment]
![Uploading image.png…]()

**Comment by t3chguy** [comment]
I suggest you install one of the prebuilt ones from https://element.io/get-started or from other distributions. Otherwise you must follow all the build instructions, including `build:native`.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104323430-1fc1ac00-5521-11eb-9224-93652ea534d0.png)

**Comment by t3chguy** [comment]
As per the README, if you want to build it yourself you must have a lot of build tools:

> will require a number of native tools to be installed, depending on your OS (eg. rust, tcl, make/nmake)

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104323561-45e74c00-5521-11eb-99d4-d0b212ce411c.png)

**Comment by t3chguy** [comment]
Yes, that won't include the native extensions keytar or seshat, those are optional and must be built using `build:native`.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104324534-885d5880-5522-11eb-950d-c3981056d0cf.png)
![image](https://user-images.githubusercontent.com/35803375/104324642-a925ae00-5522-11eb-9deb-07fce21d8563.png)

**Comment by t3chguy** [comment]
Yes, you did not follow the instructions. You do not have the build tools set up.

> will require a number of native tools to be installed, depending on your OS (eg. rust, tcl, make/nmake)


Seshat and Keytar require those tools to be built, so if you want those extensions, you must have the tools to build them.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104334724-aed4c100-552d-11eb-84a2-c3e8332e92fc.png)
run yarn run build:native  error

**Comment by hero008** [comment]
I'm a novice. Thank you

**Comment by t3chguy** [comment]
> will require a number of native tools to be installed, depending on your OS (eg. rust, tcl, make/nmake)

That error shows you do not have tcl installed.

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104338623-a9797580-5531-11eb-9f17-9f98e26c105a.png)

**Comment by hero008** [comment]
![image](https://user-images.githubusercontent.com/35803375/104339509-a2069c00-5532-11eb-9e17-bb3c37e2e098.png)

**Comment by jryans** [comment]
I would recommend joining #element-web:matrix.org (perhaps via a browser or another client) to ask these support questions, as it will be easier to resolve this interactively.
