### ISSUE TITLE
Handle web+ protocol to be able to open links in custom element clients

### ISSUE THREAD

**Issue by PhieF** [vector-im/element-web#16124]
**Is your suggestion related to a problem? Please describe.**

I'd like to be able to open rooms by just sharing a link, with any registered clients. Matrix.to only allows some predefined apps

**Describe the solution you'd like**
Firefox provides a ways to register a protocol
I know other browser don't but since it doesn't seem hard to implement, it could even be implemented in android

it would be some kind of link like

web+matrix://join?#room:server

for example
see here:
https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers

Thanks !!

**Comment by bkil** [comment]
Related https://github.com/vector-im/element-web/issues/16875

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16875
