### ISSUE TITLE
hitting cancel on 'enter security passphrase' during login doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16134]
it keeps reprompting you, and then it leaves you stranded on an infinispinner

**Comment by ara4n** [comment]
![Uploading Screenshot 2021-01-13 at 14.39.28.png…]()

**Comment by ara4n** [comment]
i also had a failure mode where the 'enter security passphrase' prompt didn't appear at all, and so i was left staring at this infinispinner from the outset.

**Comment by jryans** [comment]
I believe this is effectively the same as https://github.com/vector-im/element-web/issues/15584.
