### ISSUE TITLE
custom audible notifications not working

### ISSUE THREAD

**Issue by UnConundrum** [vector-im/element-web#16141]
<img width="603" alt="Screen Shot 2021-01-13 at 8 11 22 PM" src="https://user-images.githubusercontent.com/789152/104532058-6248be80-55dd-11eb-898f-f4bdb27e05d0.png">

### Description
I have about 15 stagnate rooms for users I communicate with frequently.  For each I've made a recording of their name and set it as a custom notification sound for that room.  They work well in Element's desktop client, but don't work at all in the NextCloud app.
For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?

I use chrome and Safari.  Noticed the same issue in both.

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
macOS

- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

Private server
For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 

Element version 1.7.16
olm version 3.2.1

latest NextCloud desktop

version 0.34.0.1-0matrix-synapse

**Comment by t3chguy** [comment]
What happens there, no audio at all? That app is completely not maintained by this project so might be better worth reaching out to them.

**Comment by UnConundrum** [comment]
Correct, no audio.

**Comment by t3chguy** [comment]
Does video playback audio work in Element via NextCloud Desktop?

**Comment by UnConundrum** [comment]
Uhhhh, I didn’t know there was a NextCloud Desktop that would support a gui.  I have NextCloud installed on my desktop so I can easily transfer files to the server and maintain my personal items, but no gui, just a dropdown from the menubar.  

I have the Element desktop installed and that works properly.

**Comment by t3chguy** [comment]
Oh, sorry I presumed that's what you were using since

> latest NextCloud desktop



I mean, when using Element within NextCloud 

> but don't work at all in the NextCloud app.

Does Audio from Element, e.g from a Video within Element, work?

**Comment by UnConundrum** [comment]
Never received a video via Element, but voice calls using Element work.

**Comment by t3chguy** [comment]
Voip uses a different stack, it'd be possible for nextcloud to mute audio but not voip. Maybe try sending a video in a room with just yourself

**Comment by UnConundrum** [comment]
Not exactly sure what you were suggesting,  but I created a new room in NC’s Element with just myself.  I dragged one of the files I want to use for notifications onto the page, clicked ok to upload it, and it indicates “error.”  If I click on the play button nothing happens.

**Comment by jryans** [comment]
@UnConundrum It sounds like the browser possibly can't play the audio file? Can you try a different format?

**Comment by t3chguy** [comment]
Closing due to no response and in an unsupported environment
