### ISSUE TITLE
Sudden 'find a room' UI shows up when the only room moves to favourites

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16149]
![](https://i.imgur.com/xl4oLdJ.png)

It wasn't there before moving the room, and the list is not being filtered.

**Comment by 2580ayush2580** [comment]
shall I work on this?

**Comment by turt2live** [comment]
@2580ayush2580 if you like, sure. The best place to ask these questions is on [#element-dev:matrix.org](http://matrix.to/#/#element-dev:matrix.org) as we aren't always monitoring comments on issues.

**Comment by 2580ayush2580** [comment]
can you describe what solution would you like?

**Comment by turt2live** [comment]
For this one I think we need to just hide the additional UI unless the user is explicitly filtering the list

**Comment by 2580ayush2580** [comment]
okay sure 😃
