### ISSUE TITLE
Crash durning building on docker image

### ISSUE THREAD

**Issue by kkorniszuk** [vector-im/element-web#16144]
I got this error while building Element Web locally as a docker image: 
![Zrzut ekranu 2021-01-14 o 12 43 38](https://user-images.githubusercontent.com/39081940/104586718-2148bc80-5666-11eb-8d64-f2efcc5e9f59.png)

**Comment by jryans** [comment]
@kkorniszuk Hmm, haven't seen this one before. What precise build command are you running? How much memory is available to Docker?

**Comment by kkorniszuk** [comment]
It was a problem with my local Docker instance. I fixed it right now.

**Comment by jryans** [comment]
Great, then sounds like this can be closed, thanks!
