### ISSUE TITLE
[Bug?] Youtube Video Previews Are Not Showing Up

### ISSUE THREAD

**Issue by Kittai** [vector-im/element-web#16152]
### Description

Youtube Link Previews are simply not working. Other websites previews work just fine.

### Steps to reproduce

- Post a normal link like https://google.com
- Then post https://youtube.com links
- Youtube Link Preview Doesn't Pop Up, But Googles Does

Log: sent/not sent?    

![](https://i.gyazo.com/28e54f720ddf20f421b8825f39c768a9.png)

### Version information

- **Platform**: 
- 
- **OS**: Windows
- **Version**: 1.7.16

**Comment by t3chguy** [comment]
Those URL previews are fetched by your Matrix homeserver.
Youtube has a habit of ratelimiting/blocking large singular points fetching many requests, either way its not an Element issue but rather one you should take up with the admins of your Matrix homeserver.

![image](https://user-images.githubusercontent.com/2403652/104668591-4d008c80-56d0-11eb-956e-95f6b5dcb64d.png)
