### ISSUE TITLE
Application windows are inaccessible

### ISSUE THREAD

**Issue by mmagician** [vector-im/element-web#16159]
![Screenshot 2021-01-15 at 13 13 39](https://user-images.githubusercontent.com/8402446/104726279-a948c800-5733-11eb-9064-3b25b996f8d3.png)

### Description

There are no windows to show. `Bring All to Front` or `Show All Windows` doesn't reveal anything, except the outline of a window as seen in screenshot.

Happens no matter if I'm using an extra screen or just the built-in display.

### Steps to reproduce

Not sure, I noticed it after upgrading to BigSur, but it might have been an issue earlier too, can't remember honestly.

### Version information

- **Platform**: desktop
- **OS**: macOS Big Sur
- **Version**: 1.7.16 (installed with brew, but same thing happens using the provided [.dmg`](https://packages.riot.im/desktop/install/macos/Element.dmg) )

**Comment by jryans** [comment]
1.7.19 which will be released later this week may resolve this issue. I'd ask you to check the [nightly build](https://packages.riot.im/nightly/install/macos/), except the issue only occurs for existing installs...

**Comment by mmagician** [comment]
@jryans At least for me it was buggy for new installations as well.
Fortunately in the latest nightly it works just fine. Thanks for the tip!

**Comment by jryans** [comment]
@mmagician Now that 1.7.19 has been released, is that any better?

**Comment by jryans** [comment]
@mmagician First, quit the app. In the app's profile directory (`~/Library/Application Support/[Element|Riot]`), try removing `window-state.json`, then start the app again.

**Comment by mmagician** [comment]
Yup that did the trick. I guess we can close the issue then? 
Big thanks for support @jryans!

**Comment by jryans** [comment]
Glad to hear it's resolved! 😄
