### ISSUE TITLE
Verification inconsistent

### ISSUE THREAD

**Issue by ManDay** [vector-im/element-web#16156]
This is a sister bug to https://github.com/vector-im/element-android/issues/2602, but since Element Web is in a more mature state, it might be easier to find a common cause (Synapse? Spec?). Also, this bug is fairly well defined. I have submitted a verbose description in the room, I will simply repeat:

In an encrypted room, I have a user whose **one and only** session I verified (due to the overall strange inconsistencies as by https://github.com/vector-im/element-android/issues/2602 I had to do it twice, on my Phone and my Computer, although I have cross-verification enabled) and whose session now shows with a **green** 🛡️ on all my devices. Yet, contrary to what I see in (for example) _my_ profile where it says "_3 verified sessions_", what I see in _their_ profile is actually
- The user's profile shows a **grey** 🛡️ (mouse-over hint: *You have not verified this user*), same in the room's user list
- Where it says "_3 verified sessions_" in my profile, it literally says a clickable "_Verify_" followed by "**grey** 🛡️ _1 sessions_"
- When I click on "_1 sessions_" it expands to only that one session with a **green** 🛡️

Meanwhile, the room as a whole shows with a **grey** 🛡️.

*(curiously, the exact same combination of grey and green shields shows on Element Android, too; with the only slight difference that there, the user's profile shows a green 🛡️ - but not in the user list)*

![User Profile](https://user-images.githubusercontent.com/1059827/104715956-e14e0c00-572f-11eb-8026-247f5e1e9ca5.png)

*Click on "1 session"*

![User Profile after expanding sessions](https://user-images.githubusercontent.com/1059827/104716000-ec08a100-572f-11eb-905e-7e6df3850b8f.png)

**Comment by t3chguy** [comment]
Given that the `Verify` button is still there, it shows that you have verified that user's device "Mobilgerat" but you have not verified that user ('s cross signing keys)

> (due to the overall strange inconsistencies as by vector-im/element-android#260 I had to do it twice, on my Phone and my Computer, although I have cross-verification enabled)

This would be the cause for this too. If clicking `Verify` didn't take you to a DM and do a verification there in the timeline then it is likely that user doesn't have cross-signing set up and thus you cannot cross-sign them.

**Comment by ManDay** [comment]
Thank you for resolving this, seems to be a misunderstanding on my part. I will also revisit https://github.com/vector-im/element-android/issues/2602 with this new understanding.
