### ISSUE TITLE
'the following users may not exist' dialog should only show if a profile lookup is an explicit fail

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16168]
general errors and timeouts should not trigger it. it's particularly embarassing if the invited user was proposed by the userdir in the first place.

**Comment by hex-m** [comment]
I have this problem for users that actually exist in my organization but are not known to Synapse yet. Technically it makes sense that Synapse only knows about SSO users (SAML in our case) that logged in at least once, but from the user perspective it is confusing.
