### ISSUE TITLE
Debian Repository Dependency Issue with Bullseye

### ISSUE THREAD

**Issue by Atera** [vector-im/element-web#16174]
### Description

Following the installation instructions on the website, one adds https://packages.riot.im/debian/ to the apt sources list. I specifically added the Bullseye build since that is the version I am running. However, doing a simple `apt install element-desktop` fails because of a dependency on libappindicator3-1, a package which has been removed from Bullseye (it was deprecated in Buster). Therefore, following the instructions on the website, it is not possible to install Element Desktop on Debian Bullseye.

### Steps to reproduce

1. Add https://packages.riot.im/debian/ to the apt sources, such as by running `echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list` or alternatively for Bullseye specifically, `echo "deb https://packages.riot.im/debian/ bullseye main" > '/etc/apt/sources.list.d/riot-im.list'`.
2. Update to include the new repository. `sudo apt update`
3. Attempt to install; install fails. `sudo apt install element-desktop`

Describe how what happens differs from what you expected.

Instead of installing element-desktop, an error appears stating that there is a dependency on libappindicator3-1, but that this dependency is not installable.

### Version information

Running an up‐to‐date version of Debian Bullseye (testing) which has now begun its freeze period prior to final release.
Linux DebianBox 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux

**Comment by Atera** [comment]
Per the discussion on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037 it appears that the package libayatana-appindicator can be used instead, and will be mantained both upstream and by Debian downstream.

**Comment by SimonBrandner** [comment]
I can confirm that this is a problem. Although, I am not sure we can do anything about it. It seems like an electron issue. 

@Atera, for now, you can manually install `libappindicator3-1` using `dpkg`.

**Comment by damnms** [comment]
> libappindicator3

thats not working

```
root@lucy:/home/oli/Downloads# dpkg -i libappindicator3-1_0.4.92-7_amd64.deb 
Vormals nicht ausgewähltes Paket libappindicator3-1:amd64 wird gewählt.
(Lese Datenbank ... 311246 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von libappindicator3-1_0.4.92-7_amd64.deb ...
Entpacken von libappindicator3-1:amd64 (0.4.92-7) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von libappindicator3-1:amd64:
 libappindicator3-1:amd64 hängt ab von libindicator3-7; aber:
  Paket libindicator3-7 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes libappindicator3-1:amd64 (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für libc-bin (2.31-9) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 libappindicator3-1:amd64
root@lucy:/home/oli/Downloads# apt-get install libindicator3-7
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Paket libindicator3-7 ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.

E: Für Paket »libindicator3-7« existiert kein Installationskandidat.
root@lucy:/home/oli/Downloads# apt-cache search libindicator3

```

**Comment by SimonBrandner** [comment]
@damnms, I am sorry, I am having trouble reading the error (I don't speak German...). Could you perhaps set the `LANG` (or something like that) env variable to English? I _might_ be able to help you then

**Comment by damnms** [comment]
```
root@lucy:/home/oli# su -
root@lucy:~# export LANG=en_US.UTF-8
export LANGUAGE=en
root@lucy:~# cd /home/oli/Downloads/
root@lucy:/home/oli/Downloads# dpkg -i libappindicator3-1_0.4.92-7_amd64.deb 
(Reading database ... 311254 files and directories currently installed.)
Preparing to unpack libappindicator3-1_0.4.92-7_amd64.deb ...
Unpacking libappindicator3-1:amd64 (0.4.92-7) over (0.4.92-7) ...
dpkg: dependency problems prevent configuration of libappindicator3-1:amd64:
 libappindicator3-1:amd64 depends on libindicator3-7; however:
  Package libindicator3-7 is not installed.

dpkg: error processing package libappindicator3-1:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-9) ...
Errors were encountered while processing:
 libappindicator3-1:amd64

```

**Comment by damnms** [comment]
i installed now also https://packages.debian.org/stretch/amd64/libindicator3-7/download, seems to work now, so it requires 2 packages

**Comment by fnetX** [comment]
It sounds like a weird idea to install oldstable packages into a testing system ...

**Comment by damnms** [comment]
at least it works, even tho i hope its not the solution but a workaround until this is fixed

**Comment by ronnystandtke** [comment]
Signal fixed the same issue in their latest release, see:
https://github.com/signalapp/Signal-Desktop/pull/5031

Could this please be fixed for Element, too? It's the latest roadblock for a migration to Debian 11 in some schools here.

**Comment by fnetX** [comment]
There is already this pull request which was already mentioned earlier in this thread, please read about any updates there: https://github.com/vector-im/element-desktop/pull/170

**Comment by novocaine** [comment]
Is this still reproducible now that https://github.com/vector-im/element-desktop/pull/170 has been merged?

**Comment by fnetX** [comment]
No, I think this works now. I can install element-desktop from the sources at `https://packages.riot.im/debian default/main amd64 Packages` without any dependency issues on my Debian 11 / Bullseye machine.
