### ISSUE TITLE
Filter messages in room

### ISSUE THREAD

**Issue by trymeouteh** [vector-im/element-web#16172]
A handy feature to cut down on the noise in a large room would be to have filters. Filter your messages, filter mentions directed to you, etc.

**Comment by SimonBrandner** [comment]
@trymeouteh You can already search a room but it can't really filter be the person who sends the message. In general, I think it would be awesome to have Discord style search.

![Screenshot_20210116_082143](https://user-images.githubusercontent.com/25768714/104805914-df3d8900-57d3-11eb-9718-23d6152ea0c9.png)

**Comment by SimonBrandner** [comment]
I made an issue at `matrix-doc`. [Here](https://github.com/matrix-org/matrix-doc/issues/2981) it is

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/1156
