### ISSUE TITLE
Re-implementation of the message context menu

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#16182]
**Is your suggestion related to a problem? Please describe.**

As far as I understood the "new menu component" is in use for the ["click your name" menu](https://user-images.githubusercontent.com/6216686/104843898-5276f600-58cd-11eb-8553-c17aab56d431.png). The [message menu](https://user-images.githubusercontent.com/6216686/104843914-6589c600-58cd-11eb-8b63-8ecf61804e5c.png) uses an older implementation that behaves differently.

**Describe the solution you'd like**

* Use the new menu components for the message context menu.
* As mentioned in #element-web:matrix.org the new menus also contain icons. So these have to be figured out before.

**Describe alternatives you've considered**

None

**Additional context**

* Based on messages #element-web:matrix.org from today
* Replaces #16178 

**Icons**

See PR matrix-org/matrix-react-sdk#5671

**Comment by weeman1337** [comment]
I would like to implement that. But I require the icons before. Is there any icon library where the Element icons are taken from?

**Comment by t3chguy** [comment]
Most of element's icons are modified from feather https://feathericons.com/ but quite a lot of drawn by the design team too.

**Comment by weeman1337** [comment]
Update: I have added icon suggestions to the description.

**Comment by SimonBrandner** [comment]
A while ago, I made this [PR](https://github.com/matrix-org/matrix-react-sdk/pull/5489). I am happy to reimplement it when this gets fixed, but I thought I'd mention it here

**Comment by SimonBrandner** [comment]
> I would like to implement that. But I require the icons before. Is there any icon library where the Element icons are taken from?

@weeman1337, I _think_ since you have some icons, you can start working on this if _you want_. It shouldn't be a problem to change the icons when the PR is ready if the design team wants that. If you don't want to, would you mind if worked on this? I'd like to see [#16480](https://github.com/vector-im/element-web/issues/16480) fixed but we first need to fix this...

**Comment by weeman1337** [comment]
> It shouldn't be a problem to change the icons when the PR is ready if the design team wants that.

@SimonBrandner true. I've already started working on this one. Expect a PR within the next days.
