### ISSUE TITLE
when clicking on cancel button in a room settings it also clear the selected image while we have a separate remove button

### ISSUE THREAD

**Issue by 2580ayush2580** [vector-im/element-web#16186]
When I was changing the room settings I selected an image. After selecting an image I tried to change the room topic and clicked on cancel, the image got unselected. Why this happening while we have separate remove button.

**Describe the solution you'd like**
When clicking on cancel after selecting the image it should not unselect the image because we have already remove button for unselecting the image.
**Describe alternatives you've considered**

**Additional context**
![e1](https://user-images.githubusercontent.com/56980422/104856614-b931f900-5939-11eb-9407-40e7d7430ffa.png)
![e2](https://user-images.githubusercontent.com/56980422/104856615-bafbbc80-5939-11eb-88b6-324af6308e84.png)

**Comment by aaronraimist** [comment]
Related to these closed issues https://github.com/vector-im/element-web/issues/15108 https://github.com/vector-im/element-web/issues/10170

**Comment by t3chguy** [comment]
Presumably it happens because you'd expect clicking `Cancel` to disable `Save` but if it doesn't clear your uploaded avatar then Save would still be available and you might keep clicking Cancel thinking its broken

**Comment by 2580ayush2580** [comment]
> Presumably it happens because you'd expect clicking `Cancel` to disable `Save` but if it doesn't clear your uploaded avatar then Save would still be available and you might keep clicking Cancel thinking its broken

let assume if I have to change my avatar and I selected an avatar. after selecting avatar I tried to change the room topic and decided not to change the room topic and clicked on cancel. I saw that avatar is unselected and I have to select again avatar to change avatar.

**Comment by t3chguy** [comment]
Okay but `Remove` and `Cancel` do different things for the Avatar.

`Cancel` reverts to the currently set avatar
`Remove` stages a change (for when you click Save) to remove the currently set Avatar.

If Cancel didn't revert to the currently set avatar then how would one revert without having to upload the exact same avatar again?

**Comment by t3chguy** [comment]
Actually looks like Cancel always blanks out the Avatar preview, so its broken in either way

**Comment by 2580ayush2580** [comment]
> Actually looks like Cancel always blanks out the Avatar preview, so its broken in either way

yes, same I want to say.
