### ISSUE TITLE
Electron app window positioning can get so confused it's invisible.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16189]
After unplugging a 4K external display:

```
bucephalus:Riot Nightly matthew$ cat window-state.json 
{"width":1,"height":22,"x":0,"y":1258,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":2048,"height":1280}}
```

I had to delete window-state.json and relaunch to make the app visible again.  It wasn't showing in Exposé or otherwise in the window manager, seemingly.

Presumably we should as a minimum put some sanity checks on minimum width & height.

**Comment by jryans** [comment]
https://github.com/vector-im/element-desktop/pull/166 upgraded `electron-window-state`, and it claims to include a fix for issues like this, so let's assume fixed for now.
