### ISSUE TITLE
Layout broken on Eleweb on Mobile Safari

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16199]
This is relevant because 3PID invite flow on iOS requires Mobile Safari.

In general the layout isn't /that/ bad - but when the LeftPanel collapses the chevrons end up floating over the body of the page (position: fixed, it seems) as you scroll the page left & right.

**Comment by jryans** [comment]
@ara4n Hmm, so this is receiving a 3PID invite email link?

Please include screenshots, it's a bit hard to guess what you mean.

**Comment by Thaodan** [comment]
I have a similar issue in the Sailfish OS browser and Firefox if set in mobile layout (for reproducing).

**Comment by paboum** [comment]
I can confirm the same for Firefox on Android. In general, basic functionality such as browsing room, reading and writing messages, should be available in a mobile browser, without installing an app. This is a major blocker for "normies" who are afraid of new "chat app" as it might be malware.
