### ISSUE TITLE
E2EE hints via .well-known/matrix/client seem to be ignored by element-desktop

### ISSUE THREAD

**Issue by nblock** [vector-im/element-web#16191]
E2EE hints via `.well-known/matrix/client` seem to be ignored by element-desktop but they are honored by element-web.

### Steps to reproduce with element-desktop

- Configure and serve `.well-known/matrix/client`
- Obtain element-desktop
- Login with private synapse instance
- Create a new room
- The flag "Enable E2EE" is enabled (although the default is `false`)

### Steps to reproduce with element-web

- Configure and serve `.well-known/matrix/client`
- Open a browser and connect to `https://matrix.example.com`
- Login with private synapse instance
- Create a new room
- The flag "Enable E2EE" is disabled (as expected)

The file `.well-known/matrix/client` contains the following content:

```
$ curl -s https://matrix.example.com/.well-known/matrix/client | jq .
{
  "m.homeserver": {
    "base_url": "https://matrix.example.com"
  },
  "io.element.e2ee": {
    "default": false
  },
  "im.vector.riot.e2ee": {
    "default": false
  }
}
```
I tried multiple different versions of the above (only `io.element.e2ee` object, only `im.vector.riot.e2ee` object, or both). They don't seem to make a difference to element-desktop.

Both clients, element-desktop and element-web request the .well-known file as seen from the reverse proxy logs. 

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.16
- **server_name**: `matrix.example.com`

**Comment by t3chguy** [comment]
Sounds related to https://github.com/vector-im/element-web/issues/14315

**Comment by nblock** [comment]
@t3chguy Thx for the pointer! The mentioned issue revealed the culprit: a missing CORS header for `.well-known/matrix/client`.
