### ISSUE TITLE
Extra renegotiation offer when handling incoming m.call.negotiate with description type offer

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16190]
When handling an incoming `m.call.negotiate` event (MSC2746) with `offer` as the type of its description, Element Web sends one in response with `answer` as the description type, but also an extra one with `offer` as the description type:

![image](https://user-images.githubusercontent.com/5547783/104904359-5c5a3100-5981-11eb-914d-c778841b3dd2.png)

The first event is sent by the user initiating the renegotiation, the two following ones are immediately sent by Element Web on behalf of the other user as a response to that first event.

**Comment by dbkr** [comment]
hmm, I can't repro this with just two plain element-webs. do you have logs?

**Comment by babolivier** [comment]
As per internal discussion, this bug seems to only happen on Firefox. It might be a Firefox bug itself, @dbkr is currently investigating it.
