### ISSUE TITLE
Searching Contacts when starting a new Chat

### ISSUE THREAD

**Issue by jstampfer** [vector-im/element-web#16209]
I have installed a Homeserver with spantaleevs ansible playbook. It works really fine.
But one problem I have, is when I try to search for contacts - in Element-Web and in
Element-IOs and Android App too.
Some Users I can find without any problems, others just seems to be case sensitive
an I can just find it if i write the correct uppercases. Some users I just can find
if I enter a "@" in the searchfield, and then I have to find it in the list.
Does anybody have the same problem?

Thx in advance :-)

**Comment by t3chguy** [comment]
The user directory search is server-side. There is a Synapse config privacy option for who you can see in the list.

**Comment by jstampfer** [comment]
thx a lot. will ask there :-)
