### ISSUE TITLE
Ability to mute notifications from rooms in a given space

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16211]
Once we have spaces, and once we return to finishing reworking Notifications, i think it could be super useful to be able to adjust notifs on a per-space level (e.g. i'm off work; i want to mute everything in my work space.

**Comment by t3chguy** [comment]
Would this be just for mute or for notification levels as a whole?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15529
