### ISSUE TITLE
Guests can unexpectedly join from the room directory

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16213]
In most parts of the UI, we currently require guests to create an account before they can e.g. send messages, join rooms, etc. However, at the moment, the room directory does present join buttons to guest users.

To make the UX more consistent, we should only show preview buttons to guest users.

**Comment by viveknagar0301** [comment]
@jryans Any update on this ?

**Comment by ChenSun-Phys** [comment]
I'm also curious that has the guest access been stripped or fully added back?
