### ISSUE TITLE
Ghost encrypted sessions, both verified and unverified

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#16214]
### Description

On a 1-to-1 room, the other person has 2 cross-verified sessions. This is how he sees his own profile:

![imagen](https://user-images.githubusercontent.com/973709/105050771-090dde80-5a66-11eb-8461-4ebb944e83fd.png)

However, he appears to me like with 3 verified sessions + 1 unverified session. This is how I see him:

![imagen](https://user-images.githubusercontent.com/973709/105045204-8d109800-5a5f-11eb-88fe-7e5f55818578.png)

Of course, the unverified session and one of the desktop ones are wrong. But I see no way to remove them.

### Steps to reproduce

I have no idea on how to get to this situation. It must have been some sort of out-of-sync/network
Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**:  desktop

For the web app:

- **OS**: Fedora (me), Ubuntu (him)

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.7.16

cc @ernestotejeda

**Comment by Yajo** [comment]
Hello, I'm sorry to insist. I'd like to know if at least there's a way to reject a specific session.

It seems strange to me that I have one session that I know can't be trusted, but element only lets me know that... that seems not much secure... I should be able to blacklist it somehow, right? 🤔

**Comment by t3chguy** [comment]
Settings > Security & Privacy and log it out from there.

**Comment by jryans** [comment]
As for the sessions list being out of sync, this typically indicates a homeserver bug. I would suggest ensuring both you and the other user are on the latest versions of your homeservers. As a "workaround", you may be about to force a device list sync by editing the name of one your devices. If the issue persists, I recommend filing an issue with your homeserver software.

**Comment by Yajo** [comment]
Thanks for your answers.



> As a "workaround", you may be about to force a device list sync by editing the name of one your devices

I tried this and it still doesn't help. I'll open an issue on synapse. I use 1.23.1 and my friend is on matrix.org.

In the mean time, I opened also https://github.com/vector-im/element-web/issues/16341 to track the client problem more specifically.
