### ISSUE TITLE
When trying to "Add widgets, bridges & bots" while using EMS homeserver, the dialog is blank.

### ISSUE THREAD

**Issue by maxamillion** [vector-im/element-web#16225]
### Description

When trying to "Add widgets, bridges & bots" while using EMS homeserver, the dialog is blank.

### Steps to reproduce

- Open right panel in element web UI, click "Add widgets, bridges & bots"

Describe how what happens differs from what you expected.

pop-up dialog is blank

Log: sent

![ems_element_blank_dialog](https://user-images.githubusercontent.com/839000/105213631-8bed7280-5b14-11eb-93d5-92820f668078.png)

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Brave - Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
- **OS**: Red Hat Enterprise Linux 8
- **URL**: https://rellim.element.io/

**Comment by Twi1ightSparkle** [comment]
Brave Shield was blocking the integration manager. It's apparently lying about not blocking things
