### ISSUE TITLE
Date changes should be more obvious

### ISSUE THREAD

**Issue by domoritz** [vector-im/element-web#16221]
The date change to "Today" in the screenshot below is super hard to see in a long thread. Since the individual messages only show the time but not the date, date changes need to be more visible. 

<img width="822" alt="Screen Shot 2021-01-20 at 13 45 50" src="https://user-images.githubusercontent.com/589034/105176731-76f3ed80-5ada-11eb-9a6f-0ee12f513f7a.png">

**Comment by SimonBrandner** [comment]
Discord uses a horizontal line and it's quite easy to see:

![Screenshot_20210129_135448](https://user-images.githubusercontent.com/25768714/106277523-8e00b100-6239-11eb-9b76-a231ed43c0ad.png)

I'd like to add this but it would make replies look this way:

![Screenshot_20210129_135638](https://user-images.githubusercontent.com/25768714/106277705-d029f280-6239-11eb-948c-ea890ffc371f.png)

It might be best to wait for [#3553](https://github.com/matrix-org/matrix-react-sdk/pull/3553) to get merged...

**Comment by domoritz** [comment]
So does Slack. 

<img width="456" alt="Screen Shot 2021-01-29 at 14 00 02" src="https://user-images.githubusercontent.com/589034/106278036-da72cf00-61ee-11eb-999f-a532c48edd76.png">

**Comment by tawfiek** [comment]
Is there any decisions will be taken here ?!

**Comment by domoritz** [comment]
It looks like there is a more obvious indicator now.

**Comment by SimonBrandner** [comment]
@tawfiek, I think we are waiting right now, see [#16221 (comment)](https://github.com/vector-im/element-web/issues/16221#issuecomment-769790278)

**Comment by tawfiek** [comment]
Oh, so a big change is coming ... interesting @SimonBrandner
