### ISSUE TITLE
Suggestion: Improve direct message UI

### ISSUE THREAD

**Issue by domoritz** [vector-im/element-web#16220]
The direct message UI is a lot busier in element compared to other messengers. I don't think the profile images need to be repeated for every message block in a direct conversation with one other person.

**Comment by SimonBrandner** [comment]
Related to or duplicate of [#19](https://github.com/vector-im/roadmap/issues/19). Possibly could be improved by [#4635](https://github.com/vector-im/element-web/issues/4635)

**Comment by domoritz** [comment]
Thank you for finding the related issues @SimonBrandner. I will leave this issue open since https://github.com/vector-im/roadmap/issues/19 does not cover UI changes and https://github.com/vector-im/element-web/issues/4635 does not address direct messages as being different.
