### ISSUE TITLE
-> gets replaced with the arrow symbol

### ISSUE THREAD

**Issue by c33s** [vector-im/element-web#16223]
![El1IEvQk7X](https://user-images.githubusercontent.com/649209/105198196-b3a50080-5b3d-11eb-8e94-047aa9bdd9c9.gif)

 even when `Enable Emoji suggestions while typing` and `Automatically replace plain text emoji` is disabled.

there should be a setting where my text i entered is applied as is with no changes done to it.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: win
- **Version**: 1.7.16

**Comment by SimonBrandner** [comment]
@c33s I can't reproduce this on Linux with `Enable Emoji suggestions while typing` and `Automatically replace plain text emoji` enabled. Is there any chance this is actually caused by the OS?

**Comment by t3chguy** [comment]
This is a ligature in the default font. You can change the font you wish to use in Settings > Appearance.

**Comment by c33s** [comment]
yeah, changed the system font to verdana. works now :)
