### ISSUE TITLE
Numerous reports of favouriting rooms not working

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16228]
This may be an operational issue with matrix.org due to lack of echo, but it could also be a bug. Needs investigation

**Comment by SimonBrandner** [comment]
The `Favorite` button can have weird delays sometimes. But it doesn't work at all on `matrix.org`. I am also unable to permanently change any account level settings on `matrix.org`... That might also be a cause of [this](https://github.com/vector-im/element-web/issues/12339#issuecomment-763969070)

**Comment by jryans** [comment]
I have also had trouble as well... I'd suspect a server issue, but either way it needs to be triaged.

**Comment by jryans** [comment]
We believe this is now fixed on matrix.org.
