### ISSUE TITLE
Call occupies the entire chat space

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vector-im/element-web#16229]
**Is your suggestion related to a problem? Please describe.**
During the 1x1 call, if while you are talking to that person and they want to send each other images, or written things, there is no space for this. The call banner, occupies all the space, and does not allow to resize it as the jistis widget does for example.

**Describe the solution you'd like**
There are 2 possible variants
1 - Let that banner resize in size
or
2 - Move it to the bottom right panel (where the drawing is), or as it is put, when you change rooms, and call it, it is placed in a corner

![call](https://user-images.githubusercontent.com/43164089/105256231-561bae80-5b53-11eb-9aee-480d76a6a677.png)

**Comment by t3chguy** [comment]
> Let that banner resize in size

Indeed, that would match Jitsi conferences too which are resizable.

**Comment by SimonBrandner** [comment]
Closing in favour of [#15876](https://github.com/vector-im/element-web/issues/15876)
