### ISSUE TITLE
Roomlist background flickers with an image

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#16233]
Is the roomlist background still somehow using the user profile picture? It's very unnerving to have a flickering image there.

Element Nightly version: 2021012101
OS: MacOS 10.15.6

**Comment by benparsons** [comment]
Ideally we could disable this feature.

**Comment by t3chguy** [comment]
Yes, it is still using the user's profile picture. Firefox doesn't support it. There is also a secret console command you can run to change the avatar it uses to something else.

**Comment by benparsons** [comment]
I'm using Element Nightly on MacOS.

**Comment by t3chguy** [comment]
Then that is Chromium based, Chromium supports the backdrop filter hence it being used.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14531
