### ISSUE TITLE
Automatic e2ee key-backup on registration

### ISSUE THREAD

**Issue by a000a** [vector-im/element-web#16234]
Getting new users to matrix is hard, especially the ones that are used to whatsapp and other easy-ui clients.
a lot of non-tech people are confused with the e2ee procedure.
since e2ee is default now, why not try to make the whole encryption initialization with at least clicks as possible?

Suggestion:
1st form: People enter homeserver, nic, password, (optional email, phone).
2nd form: choose `passphase` or `backup-key` or `dismiss and do later`. depending on the choice, the form changes to either `enter a passphrase (with an input field)` or `generate key` or closes.
3rd form only opens if key is generated and offers a download or copy (as it had been)

sorry if a similar issue was already opened - didn't find any

**Comment by jryans** [comment]
There are many similar proposals, but agreed it's tricky to find in the sea of issues... Currently we believe setting up key backup once you join an E2EE room (like Element Web does currently) is a good fit, but we'll continue tweaking as needed if we believe there's a better balance in the future. Thanks for your feedback.
