### ISSUE TITLE
Wording on sticker permissions is very broken English.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16237]
<img width="752" alt="Screenshot 2021-01-21 at 21 45 55" src="https://user-images.githubusercontent.com/1294269/105417041-e8df4a80-5c32-11eb-92e3-f95447b7e45b.png">

**Comment by ara4n** [comment]
presumably "The visibility capability" should be "Send messages to your rooms" or something.

**Comment by ara4n** [comment]
and i question why stickers should have a permissions dialog anyway; can we just autotrust them given they're already special cased and not user configurable in Element?

**Comment by turt2live** [comment]
Ah ha, we missed that capability in the proper english translations. 

(It's asking to be told when you're viewing it - we need to add it to the automatic allow list)
