### ISSUE TITLE
Voice call is not connected between web and Android

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#16231]
### Description

The voice call cannot be connected between web client and Android in different networks

### Steps to reproduce

- Let assume two accounts on matrix.org server (but this is not important, it happens in federation too)
- Web client in home network and Android client in mobile network, both behind the NAT in two different networks
- Initiate a call from web to Android and vice versa
- The call cannot be connected, showing "Connecting call..." on Android side

There is no problem between two Android phones in any situation at all, in same network, federation with my own server, everything works, also two web clients work properly (same network, different networks).
The call was sucessfully connected (both directions) from web client on restricted corporate network (http proxy, TCP/80,443 only) to web client at home PC 😮, but not to Android mobile at the same home network.

### Version information

For the web app:
- Web client 1.7.17 on app.element.io (Firefox 85b9, Chrome 87 on Windows 10, it doesn't matter, same behaviour)
- Element 1.0.14 in mobile network

### Logs
[call initiated from Android](https://pastebin.com/r9RVqVd5)
[call initiated from web](https://pastebin.com/S2qUAxMN)

Maybe related to https://github.com/vector-im/element-web/issues/3278

**Comment by horstvogel** [comment]
I can confirm the problem. Electron 1.17 Windows with Android 1.0.13 from the google playstore, no video / audio call possible. Android to Android or Electron to Elektron  works.

**Comment by waclaw66** [comment]
> I can confirm the problem. Electron 1.17 Windows with Android 1.0.13 from the google playstore, no video / audio call possible. Android to Android or Electron to Elektron works. With Electron 1.16 there was no problem

Thanks for the hint. Element 1.7.16 works properly, 1.7.17 is affected with described bug.

**Comment by waclaw66** [comment]
Duplicates: #16239 #16249

**Comment by jryans** [comment]
Thanks for the report, this should be resolved now on develop.element.io by the fix for https://github.com/vector-im/element-web/issues/16239. Please test and let us know if it's still an issue.
