### ISSUE TITLE
Can not add reactions to some messages.

### ISSUE THREAD

**Issue by kevincox** [vector-im/element-web#16238]
### Description

Sometimes when hovering over a message in element-web the reaction and edit buttons are missing. Instead just the three dot button is shown.

### Steps to reproduce

- Receive a message.
- Be unlucky.
- Hover over the message.

Describe how what happens differs from what you expected.

The react button is not available on some messages.

Reloading fixes the issue. 

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 84.0.2
- **OS**: NixOS
- **URL**: app.element.io

**Comment by kevincox** [comment]
Had this happen again. The last two messages can't be reacted to.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/494012/105533123-b9bfec00-5cb9-11eb-801b-1434909dac9b.png">

<img width="156" alt="image" src="https://user-images.githubusercontent.com/494012/105533011-9ac15a00-5cb9-11eb-973d-1660a1a21d59.png">

Three messages ago is fine:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/494012/105533193-c47a8100-5cb9-11eb-8437-1bf7b86f3398.png">

After reload is fine:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/494012/105533285-e83dc700-5cb9-11eb-9560-1320ffd0358b.png">

I uploaded logs linking to this ticket.

**Comment by jryans** [comment]
We made need to discover a clear reproduction case for this to ease finding a fix.

**Comment by kevincox** [comment]
It happened to be a number of times yesterday however I haven't noticed a pattern. It seems to come in bursts. Is there anything I can do to get more debugging info if I spot it again?

On the other hand shouldn't it be fairly easy to look at the code and see what could cause those buttons not to render?

**Comment by deepbluev7** [comment]
One easy way to reproduce that, is when the other client sends the message before the encryption keys. Then the undecryptable message is shown for a bit, before it decrypts automatically. But you can't react to it after that until you switch rooms.

**Comment by t3chguy** [comment]
I saw that exact case today too. Sounds like a case where the code to decide which buttons to show doesn't run when the event is updated like in the case of decryption and probably echo

**Comment by deepbluev7** [comment]
Agreed.

**Comment by turt2live** [comment]
it appears as though activity on this bug was random and short-lived. As such, I'm inclined to believe it was a temporary regression fixed (and broken) by accident. 

If this issue is still happening, please open a new issue with fresh information for the team to take a look.
