### ISSUE TITLE
element isn't compatible with v0 VoIP clients

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16239]
### Description

Due to element web now using the v1 version of the voice calls, element android will still attempt to call with v0, which element web accepts, this'll result in a call where element android cannot "send" candidates to element web, due to element web requiring `party_id`s in the events, as per [MSC2746](https://github.com/matrix-org/matrix-doc/pull/2746)

### Version information

- **Platform**: web

- **Browser**: Chromium Edge
- **OS**: Windows
- **URL**: app.element.io, version 1.7.17

**Comment by progserega** [comment]
may be I create some issue: #16249
