### ISSUE TITLE
Twitter URL previews

### ISSUE THREAD

**Issue by Murenu** [vector-im/element-web#16257]
The app doesn't show twitter URL previews like, say, Discord or Telegram does. I think it's a feature that should be added.

**Comment by t3chguy** [comment]
Works fine here,

![image](https://user-images.githubusercontent.com/2403652/105619167-e7a34e80-5de7-11eb-99d3-cd8a99b54a41.png)

Might be that the Matrix server you are using has URL previews disabled or is blacklisted by Twitter.

**Comment by SimonBrandner** [comment]
Also, in end-to-end encrypted rooms URL previews are disabled by default and have to be enabled in the room settings

**Comment by jryans** [comment]
I don't believe there's any Element issue here, as it should be working, but could be disabled in the room / your device. If previewing is working for other links but not Twitter, your server may need to upgrade Synapse, as there were some changes to support Twitter (https://github.com/matrix-org/synapse/pull/7920, https://github.com/matrix-org/synapse/issues/8022).
