### ISSUE TITLE
The iOS app and android app dramatically lag behind the desktop/web app

### ISSUE THREAD

**Issue by artiblaster** [vector-im/element-web#16251]
**Is your suggestion related to a problem? Please describe.**
The iOS app is lacking in numerous ways. For example: Joining rooms in the app doesn't work properly. When I search for a room and click the join button, the loading icon flashes and then nothing happens. clicking a matrix.to link doesn't do anything, besides bring up a loading icon.

Android was better. In the brief time i used it, i only noticed that it cannot follow #example:matrix.org links within chat rooms.

This is a really big deal, a lot of people use mobiles. Other apps (whatsapp) out compete element in terms of mobile usability and that must hurt element's growth.

**Describe the solution you'd like**
If possible, port the android app to ios. If fluffychat works better, focus dev power on that.

**Describe alternatives you've considered**
Fluffychat, complaining

**Comment by SimonBrandner** [comment]
@artiblaster This sounds like an issue that should be in the Android/iOS repository. I doubt porting the Android app to iOS is possible, but I am not an expert in the area. I am not sure if I understand you correctly speaking of Fluffychat. Fluffychat and Element aren't being worked on by the same devs, so something like focusing the dev power from Element to Fluffychat probably won't happen

**Comment by aaronraimist** [comment]
The Android app is a native Kotlin app, it cannot run on iOS.

https://github.com/vector-im/element-ios is the place to file issues with improving the iOS app. There are existing issues for at least some of those things.
