### ISSUE TITLE
Confusing mobile verification flow

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#16252]
### Description

I just needed to relogin to element-android a couple of times in a row and could observe the different verification flows that you end up in when doing slightly different things. The happy path works very well, but it's tricky to actually get there as element-web by default pushes you to a fairly broken flow. Let me try to explain

### Steps to reproduce

* be signed into element-web, cross-signing, etc. all set up.
* login to elemandroid
* ele-web will show this prompt, before elemandroid has completed initial-synching:
![image](https://user-images.githubusercontent.com/105185/105579521-86e42980-5d87-11eb-9a5b-a4f623a34383.png)

* You need to press Later, or you'll end up in the very confusing verification interactions, see below.
* (continuing after pressing "later" as noted above): Next elemandroid will show a "verify this login banner". That can be pressed and leads to a new similar but different notification in web.
* If you then click that you'll be on a good path to the QR code flow and everything should work.

* If you happen to press "Verify" above it gets confusing, ele-web will show this:
![image](https://user-images.githubusercontent.com/105185/105579622-d75b8700-5d87-11eb-8d97-8017e384584c.png)
* while elemandroid will show this:
![image](https://user-images.githubusercontent.com/105185/105579629-e0e4ef00-5d87-11eb-9134-50cf00137691.png)

* The easiest way to recover from this seems to be aborting the ongoing web verification and instead accepting the incoming verification from mobile which should have popped up in the background.

* it gets even more confusing when you first press skip on mobile. I think I did that the first time and restarted the verification from web. Then ele-web prompted for scanning a QR code but elemandroid never suggested how I could scan the code. I even tried scanning it via the main menu QR button, but that only told my that the QR code is not a valid matrix.to link :roll_eyes: . And scanning the code from the system barcode scanner wasn't helping either.
* You can fall back to emoji verification at that point, which will work.

element-desktop: 1.7.17
element-android 1.0.13

**Comment by jryans** [comment]
@Bubu Thanks for this feedback. Is it possible for you to send debug logs from both Element Web and Android devices involved in verification? These logs will be critical to work out what's happening here.

**Comment by Bubu** [comment]
Sorry for the delay, I realistically won't get around to sending debug logs for another month or two.

It should be fairly easy to reproduce the behaviour by following the steps in the initial issue though. Acting on the "New Login, was this you?" -> "Verify" prompt in the existing web session.
