### ISSUE TITLE
Pasting an image just pastes the file://url/to/image

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#16255]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Open an image in gnome image viewer
- right-click + copy
- try to paste into element-desktop

Only get this in the composer: `file:///home/bubu/IMG_20210123_203406.jpg`

I can paste the same clipboard buffer content into this very bug report field on github (via Firefox). So it seems that uploading the image instead of pasting the uri should be possible in this case.

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.17

**Comment by t3chguy** [comment]
Can you screenshot the output of pasting it into https://madebyevan.com/clipboard-test/

**Comment by Bubu** [comment]
Uhm, that site doesn't work :(

![image](https://user-images.githubusercontent.com/105185/105613426-b82e1b00-5dc2-11eb-8e24-7a1c5434e223.png)

**Comment by t3chguy** [comment]
See my edited link, non-https

**Comment by Bubu** [comment]
(Needed to do a "forget about this page" in firefox history, then it worked)

![image](https://user-images.githubusercontent.com/105185/105613523-5a4e0300-5dc3-11eb-8772-ea2331a0ce0f.png)

**Comment by Bubu** [comment]
I wanted to add that Nheko correctly uploads the image when being given the same paste buffer,

**Comment by t3chguy** [comment]
So I think the issue here is some code to work around a Microsoft office issue where it copies both text and a bitmap of the text. So when element sees both it prefers the text.
