### ISSUE TITLE
Allow room search to filter by mxid, room alias, etc

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#16253]
**Is your suggestion related to a problem? Please describe.**
I'm always frustrated when I try to find my smartass friend who uses a single unicode special character (♠) as display name in my people/room list, and they're not in the top 5 recent people I talked to. So this means I have to (either type alt-codes?, or) "Show 420 more" people and scroll down while scanning for the right room.
Sure, I could warn them about this and then stop messaging them unless they change their display name, but I think Element could simply handle such things better.

**Describe the solution you'd like**
I want to be able to just search them by their known MXID, which to my knowledge is even restricted to sane characters.
It's probably reasonable to allow the same with room #adresses.
It might be possible and reasonable to enhance this by limiting the search to these cases using the appropriate prefix character `@`, `#`, etc but then the results need also include users and rooms with these characters in their display names. Just slap a toggle in the advanced section of the settings menu.

**Describe alternatives you've considered**
.... colon based emoji composer for the filter field? Actually that doesn't work since there are several:
- ♠ (`\u2660` or `&#x2660;`)
- ♠️ emoji (`\u2660\uFE0F` or `&#x2660;&#xFE0F;`)

**Additional context**
-/-

**Comment by SimonBrandner** [comment]
I've opened an issue at `matrix-doc`. [Here](https://github.com/matrix-org/matrix-doc/issues/2981) it is. Duplicate/related to [#16172](https://github.com/vector-im/element-web/issues/16172)

**Comment by HarHarLinks** [comment]
Thanks for bringing it up. That's a good issue for the doc.

To be clear, I am talking about the top left input box, in between your account name and the room list, labeled "Filter".
The discord feature you're relating to allows to search all places at once and is nice, but I believe it's more about finding messages rather than rooms? The equivalent Discord search box to that is located on your home screen, also in the top left, labeled "Find or start a conversation".

**Comment by SimonBrandner** [comment]
Oh, I am sorry, I somehow thought you were talking about the event search

**Comment by t3chguy** [comment]
@HarHarLinks whilst the new modal doesn't have explicit filters, does it behave better for your usecase?

**Comment by HarHarLinks** [comment]
The "New Search Experience" has been working fine. In the meantime, not having the same ability to search in the forwarding dialogue (#21338) or on the android platform has been fairly annoying...

**Comment by t3chguy** [comment]
@HarHarLinks for Android I suggest https://github.com/vector-im/element-android

So is this issue resolved for the room filtering (to view) case? #21338 tracking the fowarding case?
