### ISSUE TITLE
Security key reset isn't working?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16263]
I have a FOSDEM admin who tried to reset their security key, but the new security key isn't accepted.

**Comment by SimonBrandner** [comment]
I think this might be a duplicate of [#16118](https://github.com/vector-im/element-web/issues/16118)

**Comment by schuhmi2** [comment]
Just read that bug, and confirmed, duplicate.
I experience exactly the same with the same process and workflow
