### ISSUE TITLE
"Forgot passord?" link on Sign in page needs customizable URL

### ISSUE THREAD

**Issue by plinss** [vector-im/element-web#16260]
### Description

The "Forgot password?" link on the Sign in page takes the user to a "Set a new password" page. For those using an LDAP backend this is useless and confusing to the end user.

It would be useful if the configuration allowed a custom URL for that link to take users to their LDAP password reset page.

### Steps to reproduce

- Setup a homeserver using LDAP authentication
- Click "Sign in" on the welcome page
- Click "Forgot password?" on the Sign in page
- The flow does not reset the LDAP password.

### Version information

- **Platform**: web 

For the web app:

- **Browser**: All
- **OS**: All
- **URL**: Private server, V1.7.17

**Comment by t3chguy** [comment]
If you still care about this please open an issue in https://github.com/matrix-org/matrix-spec
