### ISSUE TITLE
List of a community's rooms is cut off

### ISSUE THREAD

**Issue by lioncage** [vector-im/element-web#16267]
### Description

<img width="1680" alt="Screen Shot 2021-01-24 at 3 42 30 PM" src="https://user-images.githubusercontent.com/76915718/105644477-6d141680-5e5b-11eb-8ed1-6880fa762ac5.png">

When viewing a community, the full list of the rooms is cut off at the very bottom, as outlined in red in the above screenshot. I can scroll through the list of rooms, but I can't scroll down to see the full icon, name, and description of the last room. The issue persists no matter the size of the Element window, as seen below.

<img width="1680" alt="Screen Shot 2021-01-24 at 3 56 48 PM" src="https://user-images.githubusercontent.com/76915718/105644789-114a8d00-5e5d-11eb-850c-3de1a0f92247.png">

### Steps to reproduce

- Hover over a community and click on the ellipses.
- Click on view community.
- Scroll down through the rooms to the bottom of the scroll bar.

Expected: I can see the full list of all the rooms, with no information being cut off.
Actual: The name, icon, and description of the last room is cut off.

### Version information

- **Platform**: desktop

- **OS**: macOS Big Sur Version 11.1
- **Version**: Element version: 1.7.17; olm version: 3.2.1

Additionally, it would be preferable if there was the ability to toggle how the rooms were listed. Right now, the rooms are listed based off of the number of users in a room, but I would prefer the ability to list the rooms alphabetically by name.

**Comment by robintown** [comment]
Will be fixed by Spaces, I assume: https://github.com/vector-im/element-web/issues/15930

**Comment by lioncage** [comment]
@robintown @t3chguy Sorry, complete newbie to FLOSS and GitHub as a whole. What is Spaces? Sounds like an extension for Element

**Comment by t3chguy** [comment]
Spaces is a Communities v2 from scratch with less limitations

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
