### ISSUE TITLE
Have Escape key on the input box cancel response

### ISSUE THREAD

**Issue by SeerLite** [vector-im/element-web#16268]
**Is your suggestion related to a problem? Please describe.**
It's a feature I miss from other messaging apps. It's annoying to have to reach for the mouse to cancel the response and send it as is.

**Describe the solution you'd like**
Pressing the Escape key when focusing the input box should dismiss the response, as if the X key was pressed.

**Describe alternatives you've considered**
None, it's specific.

**Additional context**
![image](https://user-images.githubusercontent.com/21978144/105644887-f2f18b00-5e76-11eb-87c0-9a14c280b82a.png)
Pressing Escape while focusing the input box would dismiss the "Replying" thing above.

**Comment by t3chguy** [comment]
It should do this, there is code which is meant to do this, the fact it doesn't is a bug.
