### ISSUE TITLE
Rip out colour support from the settings handlers

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16278]
We don't have the feature, and the rest of it was ripped out already.

**Comment by t3chguy** [comment]
This seems to be gone

![image](https://user-images.githubusercontent.com/2403652/170825217-7e8c98d5-fa85-4dd0-aed0-674c06d1dc61.png)
![image](https://user-images.githubusercontent.com/2403652/170825224-702dee19-9f08-4fc5-ae3d-764ffc3892b8.png)
