### ISSUE TITLE
Nothing happens upon adding a server with `matrix.` prefix

### ISSUE THREAD

**Issue by Hi-Angel** [vector-im/element-web#16271]
### Description

Radicle community have a link, `https://matrix.radicle.community`, so it is easy to make a mistake by trying to add a server `matrix.radicle.community` instead of the `radicle.community`. Attempt in doing so results in nothing happening: server does not get added, and no error appears. There should be either one of:

1. an error message instead *(possibly even handling the case with `matrix.` prefix separately, because as people share links like above this could be a frequent mistake)*
2. alternatively, client could handle the case by implicitly removing `matrix.` prefix.

### Steps to reproduce

1. Press `Explore rooms` icon in the upper-left part of the window
2. In the popped up window press the drop-down list of rooms
3. In the list press `+ Add a new server`
4. In the popped up window, insert `matrix.radicle.community` into the textbox and press `Add` button.

### Expected

Either an error message appears or the client figures that `matrix.` prefix needs to be removed and does so implicitly for a user.

### Actual

Nothing happens.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.16

**Comment by t3chguy** [comment]
An error does come up once your server responds with one

![image](https://user-images.githubusercontent.com/2403652/105692013-d8122b80-5ef5-11eb-8b4b-252a3570a4f7.png)

![image](https://user-images.githubusercontent.com/2403652/105692059-dfd1d000-5ef5-11eb-93be-350a0546e2d0.png)

**Comment by t3chguy** [comment]
> client figures that matrix. prefix needs to be removed and does so implicitly for a user.

Given the subdomain may be anything + one may need to be added instead this is totally infeasible.
The only API that we can use for this unfortunately only takes a Matrix server_name, where a server_name is the latter half of a user's full Matrix ID

Related https://github.com/vector-im/element-web/issues/13661

**Comment by Hi-Angel** [comment]
Thanks, although I couldn't reproduce it, but after talking on chat it seems that the actual problem here is that server takes to long to respond for me. I'll report a separate issue on the matter that it should be visible that Element is waiting for server reply
