### ISSUE TITLE
Make it visible that Element waits for server to respond

### ISSUE THREAD

**Issue by Hi-Angel** [vector-im/element-web#16273]
**Is your suggestion related to a problem? Please describe.**

As shown in https://github.com/vector-im/element-web/issues/16271, when adding a server, sometimes they may take very long time to respond. Long enough that it looks to a user as if Element is broken. To avoid such bad experience there should be a feedback showing a user it is actually waiting on server.

**Describe the solution you'd like**

The `Add` button in the dialog for adding a server

<details>
    <summary>Path to diallog</summary>

1. Press `Explore rooms` icon in the upper-left part of the window
2. In the popped up window press the drop-down list of rooms
3. In the list press `+ Add a new server`
</details>

should change its appearance while Element is waiting for server to answer. Simplest solution: gray button out and replace the text with `Loading…`. An even better one could be making it a spinner.

**Comment by jaiwanth-v** [comment]
Hi, can I work on this issue?

**Comment by jaiwanth-v** [comment]
Hi, can I work on this issue?

**Comment by t3chguy** [comment]
Sure
