### ISSUE TITLE
New Rooms are titled "Empty Room"

### ISSUE THREAD

**Issue by leviathan009** [vector-im/element-web#16270]
### Description

Creating a new room makes it appear in the room list with the title "Empty Room" instead of the actual room title. The correct title is used after a click on any room.

### Steps to reproduce

-from left side menu, unter rooms click the plus icon
-enter settings for new room and click "create"
-see room appear in room list with faulty title

Describe how what happens differs from what you expected.

I expect the room title to appear immediately without manually triggering it with a workaround!

### Version information

- **Platform**: 

web (in-browser) 

For the web app:

- **Browser**:  Firefox 84.0.2
- **OS**: Windows 10 20h2
- **URL**: private server, version 1.7.17

**Comment by dangwynne** [comment]
I've fixed this is PR https://github.com/matrix-org/matrix-react-sdk/pull/5587
