### ISSUE TITLE
Sending message to Slack with hyphens truncates it

### ISSUE THREAD

**Issue by jborichevskiy** [vector-im/element-web#16279]
### Description

Sending a message to a Slack channel, such as this one:

```
line a
- test
```

Will only deliver the following:

![image](https://user-images.githubusercontent.com/7939255/105735765-ef96e780-5ee8-11eb-99fc-d105de9c9cc9.png)

### Steps to reproduce

- open slack channel
- type in message from above
- click send

Expected to see the second line included, but it was only the first.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop? Mac Desktop olm version: 3.2.1
nova-web commit hash: e6423fa0df83-react-21b8067d5f0c-js-2f71feedb1c1
nova-desktop version: 1.22.2

For the desktop app:

- **OS**: MacOS 10.15.7
- **Version**: 1.22.2

**Comment by t3chguy** [comment]
You should open this issue on whichever Slack bridge you are using, if you're using the matrix.org one then its https://github.com/matrix-org/matrix-appservice-slack

**Comment by jborichevskiy** [comment]
> You should open this issue on whichever Slack bridge you are using, if you're using the matrix.org one then its https://github.com/matrix-org/matrix-appservice-slack

Apologies- followed the link from Beeper without looking. Will do, thanks.
