### ISSUE TITLE
if you take too long over an sso login flow, you get dumped back at the login screen with no clues as to what went on

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#16281]
If you perform an SSO login flow, but get distracted by the "are you sure you want to allow this client access to your account" page for long enough that the login token times out, then when control comes back to eleweb, and the token login fails, you end up back at the "sign in" page, which is a bit confusing.

**Comment by t3chguy** [comment]
Can repro

![image](https://user-images.githubusercontent.com/2403652/106014406-5ec13700-60b5-11eb-9855-d9f0d4a1a5da.png)

**Comment by niquewoodhouse** [comment]
Is there anything we can/should do to help the user on the "are you sure you want to allow this client access to your account" page to help them continue.  Eg after X seconds, something says "for security, you'll be auto-logged out in XX:XX and need to start again" or "for security, your apple id will be auto-logged out in XX:XX unless you proceed"?

If that's a bit much, my suggestion for the modal is something like this.  I've assumed we have a generic modal component.

<img width="1152" alt="modal 3" src="https://user-images.githubusercontent.com/1587166/106459901-75d3a080-648a-11eb-9560-33f4e66d222d.png">

> **For security, you’ll need to try again**
> 
> For your security, you were automatically logged out of your Google account and sent back here, as your were idle for too long.  To create your account, please try again.

**Comment by t3chguy** [comment]
So we could do that but we would have to be super conservative as after they click that button on the previous page they get redirected to the client which may have more buttons for them to click and that timer is still ticking until the client sends off the token.

@richvdh might be good idea to add something to that server template though.

@niquewoodhouse 
I think a Modal is still required for the two errors:

+ Token rejected, your server said no, probably timeout
+ We don't know what server to connect to, your browser forgot it, uh oh
