### ISSUE TITLE
Invalid room ID when adding a room to a community

### ISSUE THREAD

**Issue by PhieF** [vector-im/element-web#16298]
Hi there, a bit of a UX issue....

On Element web, when adding a room to a community, the following pattern won't work

```#room:server``` 

I've tried many times because to me THIS is a room ID, this is how I share and join the room
after looking to some logs matrix asks for this kind of room id
```
!id:server 
```

I don't know anything at all about this kind of room ID.
On this part, element was not helpful at all,always telling me that it was expecting a room ID. I guess a better message would be great
but

Why can't we but the room ID we actually use instead of a one no one know about ? I finally found it in advanced parameters of the room but I wonder how any body would find it

Thanks for your answers and your time

Take care :)

Phie

**Comment by SimonBrandner** [comment]
Spaces are now in beta
