### ISSUE TITLE
why piwik.riot.im  ?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vector-im/element-web#16296]
It is an instance of Matrix on a SNET (without internet).
I do not see well that Element is connecting to another domain below the API, I see that very badly.

Element should only connect to matrix instance, custom jitsi instance, not forced to piwik.riot.im

![error](https://user-images.githubusercontent.com/43164089/106041890-5fa09b80-60aa-11eb-8cdb-9d4aab4db4c1.png)
![error'log](https://user-images.githubusercontent.com/43164089/106041914-64fde600-60aa-11eb-96fa-fd512807be38.png)

**Comment by t3chguy** [comment]
Because you have analytics enabled in settings and th element instance you are using is configured to use piwik.riot.im.

Both of those are optional.

**Comment by AnonymousWebHacker** [comment]
I see https://github.com/vector-im/element-web/pull/7435 and https://github.com/vector-im/element-web/issues/6738, and I fix on config.json ` "bug_report_endpoint_url": "",`  tanks :)
