### ISSUE TITLE
Add option to merge People and Rooms into single list in sidebar

### ISSUE THREAD

**Issue by lukas-lang** [vector-im/element-web#16306]
**Is your suggestion related to a problem? Please describe.**
I am having a very hard time keeping track of new messages in different types of chats. I can order the "People" and "Rooms" list to show active rooms first, but the People list is so long that I have to scroll for a while to check whether there are Rooms with unread messages.

**Describe the solution you'd like**
It would be nice if the grouping of chats into "People" and "Rooms" could be disabled, so that there is only one list that can be sorted. This would enable seeing all unread messages at a glance.

**Describe alternatives you've considered**
Not sure about other ways to do this that are as simple as "do less grouping". It might be worth to note that e.g. WhatsApp already does this, i.e. there is only a single list for both normal chats and group chats.

**Additional context**
None

**Comment by SimonBrandner** [comment]
Closing in favour of [#15657](https://github.com/vector-im/element-web/issues/15657)
