### ISSUE TITLE
Require confirmation to start a direct message from right panel

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#16300]
**Is your suggestion related to a problem? Please describe.**
I find myself accidentally creating a DM with someone every week or two. I think what is happening is I expect the Mention button to be first in the list but Direct Message is the first option listed so if I am rushing then I'll accidentally click that instead.

**Describe the solution you'd like**
I would like Element to make me confirm I want to start a DM by clicking a button in a dialog box. In addition to preventing accidental DMs this dialog box could also have a text field for adding an invite reason https://github.com/matrix-org/matrix-doc/pull/2367.

**Describe alternatives you've considered**
Another solution to fix my particular problem would be to reorder the list of options in the right panel to put Mention first but it probably doesn't make sense to break the muscle memory of everyone else who was able to properly learn the order.

**Additional context**
<img width="257" alt="Screen Shot" src="https://user-images.githubusercontent.com/5855073/106119056-61a24300-611a-11eb-9d98-baf55fc94148.png">

**Comment by 2580ayush2580** [comment]
shall I work on this? I
Can you please describe more about what solution would you like?

**Comment by aaronraimist** [comment]
Yes you can work on it if you would like to. I would like a dialog box to show up when you click on "Direct message" in the right panel.  I imagine it would look similar to the dialog box that shows up when you remove a message.

<img width="766" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/106199230-c1303b00-617a-11eb-8016-a165b74c211e.png">

but instead would say something like "Are you sure you wish to start a direct message with USER? You can optionally provide a reason that will be shown to the other user before they accept the invite."

The code for that dialog is here if you want to use that for inspiration https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/dialogs/ConfirmRedactDialog.js

**Comment by 2580ayush2580** [comment]
okay sure!
I am working on this

**Comment by jryans** [comment]
As mentioned on the first PR attempted here, @nadonomy [would like to see](https://github.com/matrix-org/matrix-react-sdk/pull/5599#issuecomment-774080891) a different approach which avoids adding friction to the DM process by improving the styling of the panel to avoid accidental actions.

**Comment by SimonBrandner** [comment]
Discord has this:

![Screenshot_20210205_162122](https://user-images.githubusercontent.com/25768714/107052629-31b80700-67ce-11eb-9186-1475a82cd937.png)

Maybe we could use something similar and maybe use the invite reason instead of the message

**Comment by nadonomy** [comment]
@SimonBrandner that's an interesting suggestion. I wonder if it opens up pandoras box on cross-platform users expecting the same functionality on mobile, and also if there might be any implementation implications related to [Canonical DMs](https://github.com/matrix-org/matrix-doc/pull/2199).

**Comment by SimonBrandner** [comment]
Hmmm, the more I think about this, I think it would be better not to have an invite reason for Canonical DMs and have the UI work in a similar way to Discord. 

No matter what we end up doing with the invite reason I think the button that starts the DM should differentiate itself from the rest of the things in the panel. I think this way the chance that the user clicks it by accident is smaller. Discord's solution is even better for this because the user needs to click the text box, type the message and press enter.

Maybe something like this?

![Screenshot_20210205_210532](https://user-images.githubusercontent.com/25768714/107083420-e44f9000-67f5-11eb-897e-c69306c1b468.png)

**Comment by aaronraimist** [comment]
<img width="351" alt="screenshot" src="https://user-images.githubusercontent.com/5855073/107102769-1b677680-67e1-11eb-9368-d87a32352f85.png">

Whatever happened to this UI where DMs were a separate section? I guess it was removed in preparation for canonical DMs or something but I liked it being a separate section showing any DMs you already had. A big Direct Message button could go into that section.

**Comment by Half-Shot** [comment]
Pleeease can we look at something for this. I've had to apologise a lot for creating spam rooms because Element doesn't treat some of my legacy rooms as DMs, nor rooms with 3 people. It's actually causing me to avoid using the button entirely because the behaviour is non-deterministic.

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14736
