### ISSUE TITLE
API to return username matrix, and QR from email 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vector-im/element-web#16302]
Is there an API, or query, that from an email from a user registered in the matrix, returns the username and QR?

The idea is to link your matrix user to a site. In such a way that they scan your QR they can connect you directly.
The only thing in common between the matrix user and a site, is the user's email.
I think that with some API, knowing the mail, you can know the matrix user and its QR

In this way, any site or service where the user registers with said email, would generate a QR or link of the user to contact him

**Comment by turt2live** [comment]
QR codes can be generated from matrix.to URLs. Usernames can be looked up using an identity server - see the spec for details.
