### ISSUE TITLE
Design suggestions for mobile guide toast

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16311]
In https://github.com/matrix-org/matrix-react-sdk/pull/5586, we added an optional mobile guide toast to nudge people towards the native apps. It's disabled by default.

@niquewoodhouse [provided some good feedback](https://github.com/matrix-org/matrix-react-sdk/pull/5586#issuecomment-769815047) we may want to address in the future:

> **- When does this appear? Is it noticeable enough?**
> 
> If people's experience of Element will be broken, they'll be more likely to decide not to return/think of the product as useful. So, if we have a modal component, I'd suggest it might be better to block people briefly, but at least be sure they know we have stable options somewhere?
> 
> Basic example
> <img alt="Screenshot 2021-01-29 at 12 16 24" width="432" src="https://user-images.githubusercontent.com/1587166/106274203-d022f600-622b-11eb-89bf-b31db640563d.png">

One thing to keep in mind is that we're expecting some users to complete a 3PID room invite flow and **after that** head to a mobile app, so we wouldn't necessarily want to overlay the whole screen when you first land. Ideally, we can revisit this invite flow holistically, as it's all a bit of a mess at the moment.

**Comment by niquewoodhouse** [comment]
I think a custom toast/banner could work fine but I think using [smart app banners](https://github.com/vector-im/element-web/issues/21763) is more familiar to users.
