### ISSUE TITLE
Unable to join room (M_UNKNOWN)

### ISSUE THREAD

**Issue by clehner** [vector-im/element-web#16315]
When I attempt to join room `#riot-dev:matrix.org`, I get the following error:

![element-join-room-error-2021-01-29](https://user-images.githubusercontent.com/95347/106305250-7110b180-622a-11eb-931b-9455be9e7676.png)
Error text:
> #riot-dev:matrix.org is not accessible at this time.
>
> Try again later, or ask a room admin to check if you have access.
>
> M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please submit a bug report.
> 

This is on an EMS instance, https://spruce.element.io/, using latest Firefox on Debian Linux amd64.

Web Inspector network log shows the following failing request:
GET https://spruce.ems.host/_matrix/client/r0/directory/room/%23riot-dev%3Amatrix.org
Response status: `500 Internal Server Error`
Response body: `{"errcode":"M_UNKNOWN","error":"Internal server error"}`

The same happens when trying to join `#element-dev:matrix.org`.

**Comment by t3chguy** [comment]
I suggest reaching out to your EMS support contact as this isn't an Element Web issue but an instance/synapse one.

**Comment by clehner** [comment]
Thanks, @t3chguy

**Comment by EasternPA** [comment]
@clehner did you ever resolve this? Can you provide any hints? I've been trying to play with a self-hosted instance for a couple of years. I reinstalled early, and I get this exact error instantly every time I try to browse public rooms at matrix.org. I can't contact the EMS owner as I _am_ the EMS owner. No idea how to get matrix.org to let me federate again.

**Comment by clehner** [comment]
@EasternPA I think it was resolved with EMS support - I don't remember exactly.

**Comment by EasternPA** [comment]
> @EasternPA I think it was resolved with EMS support - I don't remember exactly.

Thank you. I'm sure I blew away and rebuilt my instance using the same FQDN but didn't retain some key somewhere. No one will peer with me now, presumably due to a key mismatch. But I'm only guessing. I will rebuild again with a new FQDN one day and see if that fixes it.
