### ISSUE TITLE
Tab completion of emojis can erase a message draft

### ISSUE THREAD

**Issue by callahad** [vector-im/element-web#16312]
### Description

Quickly typing and sending a message which ends with an auto-completed emoji can result in *only* the emoji being sent.

### Steps to reproduce

Do the following, rapidly:

- Type a message ending with an emoticon
- Hit tab to convert it to an emoji
- Hit return to send the message

For example, type:

- `hello :)` <kbd>Tab</kbd> <kbd>Return</kbd>

Expected Message:

> Hello 🙂

Actual Message Sent:

> 🙂

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox (all versions); other browsers not tested
- **OS**: macOS, NixOS Linux
- **URL**: develop.element.io

**Comment by t3chguy** [comment]
I cannot repro on macos on FF or Chrome

**Comment by SimonBrandner** [comment]
Neither can I

**Comment by callahad** [comment]
Hrmph. This has happened to me multiple times across two physically distinct computers with completely different software stacks. I'll keep poking and see if I can get a reliable repro.

**Comment by jryans** [comment]
Hmm, I don't think I've seen this before either, so quite curious what's happening here...

**Comment by SimonBrandner** [comment]
@callahad, is this still an issue?

**Comment by callahad** [comment]
Yes, I'm still encountering it regularly

**Comment by Epy** [comment]
Hello
I'm not sure it's the same problem, but I have something very similar

`In a Matrix chat room, with Element web (Firefox 78) I write some words, then a text smiley like this :) without replacing it by the UTF8 emoji ; then some other words and a text shortcut for an emoji, like <3` at the end of sentence

If I use the keyboard (tab key) to validate remplacement of <3 by :heart: it erases the sentence between the :) smiley and the heart to only let the heart.

My sentence ends like this in the edit zone.
`In a Matrix chat room, with Element web (Firefox 78) I write some words, then a text smiley like this` :heart: 

I use the Element app from https://app.element.io/
I hope that will help. If it's not the same bug, I'll make a new issue if you prefer.

Thanks

**Comment by SimonBrandner** [comment]
Yeah, I can repro the above with _Automatically replace plain text Emoji_ off, though I think it's a separate issue. @Epy, could you please open a separate issue?

**Comment by Epy** [comment]
Ok, I'll do it 
thanks

**Comment by SimonBrandner** [comment]
We changed the way emoji behave since, so this no longer seems relevant, so I am going to close this, scream if I am wrong
