### ISSUE TITLE
Phonetic Symbol Issue

### ISSUE THREAD

**Issue by TheWayOfYahweh** [vector-im/element-web#16320]
Desktop, Win10, Element version: 1.7.18, olm version: 3.2.1

Copy/Pasted partial text of another message from another room member into a new message text box for editing. Edits made included phonetic symbols, then sent/posted. After the first word edited using phonetic symbols, the text after this was black barred out, including the last phonetic symbol of the first word (**`**) and last phonetic symbol of the last word (**`**) and text size minimized after the first word edited with phonetic symbols until the end of the sentence (when a period was reached).

This shows up the same way on Android app Version 1.0.12 [40100120] (F-1946058c), Matrix SDK Version 0.0.1 (1946058c), olm version 3.1.2

![Element issue](https://user-images.githubusercontent.com/31078076/106364516-3aec3400-62f5-11eb-9a63-f6245bb6549c.JPG)

**Comment by TheWayOfYahweh** [comment]
Workaround provided by @turt2live on another post:

"This is markdown. To avoid this, type /plain before the message."

Now, just remembering to do this for each of these types of posts - would be great if this were already built in.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/483
