### ISSUE TITLE
Flair is missing in IRC mode

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16329]
This is a shame for FOSDEM, where we expect people to be using IRC layout.

**Comment by turt2live** [comment]
Looks to be an onHover bug:

![image](https://user-images.githubusercontent.com/1190097/106392543-8ebb5380-63af-11eb-9391-30630ec343c0.png)

(hovering over the message shows flair, but not by default)

**Comment by ghosty-be** [comment]
indeed the flair shows when hovering over a name...
Just a random thought but would it make sense in IRC layout to put the flair next to the profile picture? (so left align that or something?)
