### ISSUE TITLE
Joining #mozilla_#rust:matrix.org spammed me with 100s of desktop notifications.

### ISSUE THREAD

**Issue by rryan** [vector-im/element-web#1632]
Platform: web
Repro steps: join a "big" room like #mozilla_#rust:matrix.org

The UI became unresponsive (presumably as history was flowing in?). When it got unstuck, I was spammed with desktop notifications for (every?) message in the room -- it lasted a couple of minutes.

**Comment by ara4n** [comment]
How did you join it? via /join? or the room directory (if so, tapping on 
the listing, or entering it in the textbox and hitting enter)?

**Comment by rryan** [comment]
I joined via /join

**Comment by 4311021x** [comment]
I've noticed something similar. I've got notifications on my mobile and reviewed them. When my computer woke up from sleep, each notification appeared on riot web again.

**Comment by ara4n** [comment]
@0xC4N1 you're hitting #1015 which is similar but not the same.

I think we just have to repro this. @rryan: was this over federation or local on matrix.org?

**Comment by yannicka** [comment]
I couldn't reproduce the problem. Is it still relevant?

**Comment by SimonBrandner** [comment]
I will close this as I can not reproduce this. _Feel free_ to reopen or ping me if this is still a problem.
