### ISSUE TITLE
Room/DM backgrounds

### ISSUE THREAD

**Issue by TheWayOfYahweh** [vector-im/element-web#16323]
Not related to a particular problem.

Some users who have been referred to Element have expressed not liking the limit of background wallpaper and text colors in the chat sessions like they experienced on say Telegram which offers this.

Please do consider adding more than just white, dark and black for background wallpapers and plain white text.

Thanks.

**Comment by TheTimeWalker** [comment]
There is a labs feature which allows for custom themes support, which could alleviate at least some concerns like the plain white text

**Comment by TheWayOfYahweh** [comment]
Hi,

Where do we find the labs feature?

Thanks!


________________________________

**Comment by jryans** [comment]
Labs are available on the development build at https://develop.element.io or self-hosted deployments.

**Comment by SimonBrandner** [comment]
Also, you can configure them on desktop:

https://github.com/vector-im/element-web/blob/develop/docs/labs.md
https://github.com/vector-im/element-desktop#user-specified-configjson

**Comment by expipiplus1** [comment]
See also https://github.com/vector-im/element-android/issues/2425

As far as I can tell, themes don't allow one to set background images.

**Comment by jman-schief** [comment]
I'll check the provided resources, thanks.

But please consider that not being able to distinguish rooms at a glance can lead to awkward or outright embarassing situations (did anyone reply to a heated email with the wrong recipients? Same issue here)

**Comment by Palid** [comment]
> I'll check the provided resources, thanks.
> 
> But please consider that not being able to distinguish rooms at a glance can lead to awkward or outright embarassing situations (did anyone reply to a heated email with the wrong recipients? Same issue here)

Neither Telegram nor Whatsapp give you ability to personalize a single chat. Some of the communicators allow for setting custom name and avatar, but none of them lets you choose a custom background and fonts only for one chat. In all apps I recognize it's an all-or-nothing setting.


Duplicate (a newer one, hopefully with more feedback from Nad): https://github.com/vector-im/element-web/issues/18691
Related for Android https://github.com/vector-im/element-android/issues/2425
