### ISSUE TITLE
GIF with transparent background gets grey background in thumbnail

### ISSUE THREAD

**Issue by sia1984** [vector-im/element-web#16326]
Steps to reproduce:

Take this gif:

![gw2_eod2_500](https://user-images.githubusercontent.com/65598902/106381260-c928ee80-63b7-11eb-8b1f-0735e6f7aaa8.gif)

Set it as icon for a chat. If you click on it, it has the proper transparent bg:

![grafik](https://user-images.githubusercontent.com/65598902/106381290-ff666e00-63b7-11eb-9698-9707f4b77320.png)

But the thumb looks like this:

![grafik](https://user-images.githubusercontent.com/65598902/106381301-0ab99980-63b8-11eb-96ba-f2d290258820.png)

pls fix. Works flawlessly with PNG.

**Comment by t3chguy** [comment]
The thumbnails are generated by the server, probably synapse in your case

**Comment by jryans** [comment]
I don't believe there's anything a client (such as Element) could do to improve this, so I recommend filing this in the Synapse repo. (I'd transfer it if I could, but it's a different org...)

If I have misunderstood, feel free to reopen.
