### ISSUE TITLE
Add messages to favorites

### ISSUE THREAD

**Issue by lukaszpolowczyk** [vector-im/element-web#16331]
I need a feature:
Add the selected message to "Favorites".
Later I want to view my "favorite" messages in one place.

These are the things I want to refer to later or I need something else.

Currently, I can only add a link to the message to the bookmark in the web browser.
I can't do this in the app.

This feature exists at slack.com.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2938
