### ISSUE TITLE
Message tray refinement, simplification/improvement

### ISSUE THREAD

**Issue by irelativism** [vector-im/element-web#16333]
Currently in element,

The message tray has 5 options/buttons attachments, emoji, stickers, voice-call, conference-call.

I believe such should be simplified to 3 buttons so attachments, emoji, calls.

PROPOSAL:

1. Integrate sticker-packs inside emoji tray, is unproductive to waste such prime real-state in something not many users utilize.
2. Merge VOIP calls (colturn) and conference calls (jitsi/BBB) under a single button/interface were if the video button is activated them it would use jitsi widget instead, this might be complex to solve but very important for a smooth user experience

This 2 improvements would make the overall app more refined, and less noisy and hard to use, simpler, straight to the point. and overall a fluid and smooth experience.

CURRENTLY:
![Screenshot from 2021-01-31 19-52-00](https://user-images.githubusercontent.com/75645715/106397213-18950c00-6404-11eb-9f3f-749d8bfd59c0.png)

IMPROVEMENTS:
![Screenshot from 2021-01-31 19-01-41](https://user-images.githubusercontent.com/75645715/106397210-17fc7580-6404-11eb-98ac-c3eb1224e0b0.png)

**Comment by SimonBrandner** [comment]
Closing as I believe this is covered by [#5693](https://github.com/matrix-org/matrix-react-sdk/pull/5693)

**Comment by irelativism** [comment]
not really, the second issues was not adressed. @SimonBrandner please stop closing issues without any logic behind it Cheers.

**Comment by jryans** [comment]
@irelativism I agree with @SimonBrandner's decision to close here, it seems like the main concern is resolved. If you see further issues, please open a new issue which is tightly focused on a single problem.

**Comment by irelativism** [comment]
there are 2 problems presented here @jryans :
one relating calls, wich yes there was some progress there but still didnt implement or solved the issue of having 2 separate buttons one for video and one for voice. Wich is partialy solved yes.
second  the merger of stickers and emojis, wich was never adressed so really not logical to close it
so has you can see neither are solved, if you want to disregard those issues/problem then that is a diferent history, not also the first time I see disregard coming from element time but anyway, matrix is the only one that looses in the end.
Cheers nontheless.

**Comment by jryans** [comment]
The challenge is that meta-issues like this which combine several problems are not very actionable. One part might be valid, while another might not, etc. One part might get prioritised while another might not. There's no way to reflect that when they are all jammed together. That's why I am suggesting you should file a new issue for anything that seems unresolved, as that one will then be more tightly scoped.

**Comment by irelativism** [comment]
Unfortunately when I was discussing this and try to reach-out to people involved in this work on the related room design, to try to separate it in 2 issues while still creating a meta-issue with a small syntheses, was pushed out and in a way censored just because I'm not part of the element team. So in the endand so the idea didnt got lost, or went straight to the bin. I rushly scramble everything here @jryans jryans, before shutting down my matrix server. Im focusing my efforts in tox as of latelly. So you can do as you perfer. But Im most defenately not for this targeted closing of my issues by Simon, this has been happening the last few days a lot of then were closed so Im afraid some kind of bias is involved, ego's such be kept out of this matters.

**Comment by jryans** [comment]
No one is targetting your issues specifically, and I do not see any evidence of bias. Simon happened to close it because he's diligently triaging our issues at the moment. I would have done the same. Please stop making assumptions and accusations.

Open a new issue if you wish. If you insist on continuing this off topic conversation here on the issue tracker, we may ban you GitHub account from our org.

**Comment by irelativism** [comment]
@jryans is hard to have a different approach when you have been in justly banned from other communications channels just because you presented a alternate solution to travis MSC, favouritism is a very problematic thing, but at the end again the only one that looses is the element team. Please do that if you wish to I dont really care anymore honestly. Wouldnt suprise me to see yet another abusive action by another element team member. Getting back to the topic Simon decided to close all issue posted regarding this topic just after my ban from matrix rooms, which I think is self evident by itself. So please read carefully again the reasons I believe this Closure is unsubstantiated. If you are not sure about what I talking about I would advise you go check the logs and other issues closed. Is very easy to say "assumptions and accusations" if you didnt actually bother to check it. That is all I have to say, if you wish to correct the situation great there is at least some integrity in the team, if not oh well I will focus my efforts on an alternative like TOX or GNUjami, and write an article about this abusive actions. Cheers nontheless.

**Comment by turt2live** [comment]
@irelativism this continued abuse will not be tolerated. You are no longer welcome to comment on our issues.
