### ISSUE TITLE
Trapped in boot loop if keytar pickle key is wrong?

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16343]
We seem to have an increasing number of rageshakes that look like this:

```
I Got pickle key
E Unable to load session Error decrypting secret access_token: bad MAC
Error: Error decrypting secret access_token: bad MAC
    at vector://vector/webapp/bundles/5db2874a2d57ea01b83e/vendors~init.js:2:739130
    at async vector://vector/webapp/bundles/5db2874a2d57ea01b83e/vendors~init.js:2:775674
    at async Object.F (vector://vector/webapp/bundles/5db2874a2d57ea01b83e/vendors~init.js:2:775273)
```

...followed by more reports of the same thing. @uhoreg, does this mean the pickle key in `keytar` storage exists, but doesn't match what the app expects? How can we provide a better experience for this case? Perhaps a modal to the user?

**Comment by gsouquet** [comment]
My initial research here did not made me trap in a boot loop but instead prompted me that my session could not be recovered

![Screen Shot 2021-04-08 at 12 23 14](https://user-images.githubusercontent.com/769871/114018617-56c80500-9865-11eb-9875-5269b1b09a4d.png)

After speaking with @uhoreg he is unsure at this stage what you make the key corrupted in the first place. 
The experience is far from ideal but the user can recover from it by themselves

@jryans how did you envision fixing that issue? Prompting the user being already in place, are there any other sensible steps you reckon we could take here?

**Comment by jryans** [comment]
@gsouquet Have you tested both of the following paths?

* Changing the pickle key value in keychain to something other than expected
* Removing the pickle key value from the keychain entirely

If both present the "unable to restore" dialog, then that's probably good enough for now. At least the user has a way to proceed, even if it's a bit drastic. I don't think there's any way for us to magically recover the expected pickle key, so we're in tough spot if something goes wrong.

As for how it happens, unsure... some theories include:

* application bug
* restoring computer from a backup (which puts the keychain out of sync with the app)
* transferring the application and it's internal data to a new computer without realising there's something in the keychain as well

**Comment by gsouquet** [comment]
> @gsouquet Have you tested both of the following paths?
> 
>     * Changing the pickle key value in keychain to something other than expected
> 
>     * Removing the pickle key value from the keychain entirely

I have tested both scenario

1. Corrupting the key displays the Unable to restore session modal
2. Deleting the key flats out display the login screen when launching the app

I'll probably close this as I believe that a user can recover from that issue even though it might not be the best path
