### ISSUE TITLE
UI way to blacklist an untrusted device from the other party

### ISSUE THREAD

**Issue by Yajo** [vector-im/element-web#16341]
**Is your suggestion related to a problem? Please describe.**
Yes, the one described at https://github.com/vector-im/element-web/issues/16214#issue-789179345.

**Describe the solution you'd like**
Be able to blacklist a friend's device. Specially if it is reported as not trusted.

**Describe alternatives you've considered**
Still I have no solution for the problem. It might be a bug on synapse, but anyway it reveals a UX+security problem.

**Additional context**
Here I think you can see what I'm missing:

![screenshot-2021-02-02-08-50-59](https://user-images.githubusercontent.com/973709/106575280-d10d9d80-6533-11eb-87e5-a3363bff09cb.png)

After all, what's the point of having a nice red shield that tells you this conversation is insecure if you can't escape that situation? 🤷🏼‍♂️

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11751
