### ISSUE TITLE
Community buttons out of function

### ISSUE THREAD

**Issue by leviathan009** [vector-im/element-web#16353]
<img width="286" alt="ElementUI_bug" src="https://user-images.githubusercontent.com/50360080/106679766-a10adc80-65bd-11eb-88a0-fa0549847ca9.png">

### Description

Clicking on the community icons on the left side of the app panel has no effect besides the general room list appears/disappears

### Steps to reproduce

Click on a community button. 

I expect the community content to show up, like using the 3dot menu on the community buttons and choosing "View Community" from that context menu.

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop?
Desktop

For the desktop app:

- **OS**: Windows 
- **Version**: 10 (20H2)

**Comment by SimonBrandner** [comment]
@leviathan009 The current Communities are quite inituitive... They will soon be replaced by _Spaces_, which are much better and much more intuitive.

**Comment by robintown** [comment]
@leviathan009 In the mean time, note that clicking on a community simply filters your room list to rooms and members of that community, which is intended.

**Comment by jryans** [comment]
The behaviour described here is expected, though known to be confusing. Spaces should resolve this soon.

**Comment by t3chguy** [comment]
> The behaviour described here is expected, though known to be confusing. Spaces should resolve this soon.

Spaces will also be just used for filtering the Room List.

**Comment by SimonBrandner** [comment]
@t3chguy Yep, but as far as I know there should be a home button, which makes everything more sensible in my mind
