### ISSUE TITLE
Weird CORS issues and no avatars with element-desktop

### ISSUE THREAD

**Issue by pretentious7** [vector-im/element-web#16351]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

I can't see user avatars and am disconnected randomly every now and again while using element-desktop

### Steps to reproduce
- homeserver at aod.ems.host, CNAMEd to matrix.aodesign.tech.
- login at aod.ems.host
- profile pictures not visible

Describe how what happens differs from what you expected.

Log: sent    

### Version information

- **Platform**: desktop
For the desktop app:

- **OS**:Ubuntu
- **Version**: 1.7.18

**Comment by SimonBrandner** [comment]
@pretentious7 If this doesn't happen on any other homeserver this probably not going to be an Element issue...

**Comment by pretentious7** [comment]
yea I guess the EMS nickel hosts aren't fully ready yet... :/

Although I suspect there's some CORS issues with the CNAME stuff.

**Comment by jryans** [comment]
This sounds like an EMS-specific issue, so I'd recommend raising it via their support channels.
