### ISSUE TITLE
element-desktop not displaying external notifications

### ISSUE THREAD

**Issue by Kratacoa** [vector-im/element-web#16352]
### Description

I do not get any notifications whatsoever coming via `dunst` on messages I get on Element, no matter whether the chat is open or not, or whether the app is focused on my window manager (bspwm).

### Version information

- **Platform**: desktop
- **OS**: Void Linux, musl version
- **Version**: 1.7.18

**Comment by jryans** [comment]
@Kratacoa Do you get notifications in other apps? Do you have notifications enabled in Element settings?

**Comment by Kratacoa** [comment]
Yes to both.

**Comment by SimonBrandner** [comment]
@Kratacoa, do you have any Electron apps which have notifications, if so do these work?

**Comment by jryans** [comment]
Debugging this will require active replies. I suggest chatting about this in a room instead, and then an issue can be filed once we understand what might be wrong.
