### ISSUE TITLE
More chat effects

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#16368]
ROTFL, can't believe I'm filing this, but: Everyone (me included) *loves* those chat effects (confetti & snow). This feature alone has probably increased the popularity of Matrix/Element on our user-base by a 1000x ;-) We can't get enough & want more of those - not only 2.

Some proposals:

* Rain
* Stars
* Coins
* Leaves

**Comment by joepie91** [comment]
For what it's worth, there's also `:fireworks:` already :)

**Comment by rgpublic** [comment]
Woooow. Thanks a lot @joepie91 . Absolutely amazing! Didn't know about that. There's still a problem with discoverability I guess. Perhaps there should be some tab on the smiley selector for this or sth. like that.

**Comment by joepie91** [comment]
I think that imperfect discovery could actually be better here, makes it more fun to discover new ones :) But I agree that right now it's completely hidden.

Maybe a nice middle ground would be to modify the emoji selector so that it shows a small special marker/icon on emoji that have a chat effect attached to them? That way people can still have the fun of discovering them over time, but there's a visual cue helping them along.

**Comment by rgpublic** [comment]
@joepie91: 100% agree

**Comment by burdges** [comment]
I'd think discoverability could be handled by trigering effects on multiple emojis, like you already do.

**Comment by Mehavingfun** [comment]
What about falling leaves (the brown autumn one)? Or butterflies? Or aliens descending? Or what about a cherry blossom rain for spring season? 

The firework by the way is awesome. Thank you for that whoever it created.

**Comment by rgpublic** [comment]
The alien idea is genius. Like flying saucers appearing, an alien waving quickly & then they are gone. Hahaha. Great. Anyone remembering the monodental & monoocular alien from Commander Keen ;-) ?
![grafik](https://user-images.githubusercontent.com/17726950/107642978-db3b4480-6c75-11eb-9c4a-69242a362836.png)

**Comment by burdges** [comment]
Aside form chat effects, could we get :joint: and :weed: somehow?  Not animated, just the usual little icons.

**Comment by t3chguy** [comment]
@burdges https://unicode.org/emoji/proposals.html

**Comment by justjosias** [comment]
Rain addressed in https://github.com/matrix-org/matrix-react-sdk/pull/7086/

**Comment by rafaelbn** [comment]
![balloon-colors](https://user-images.githubusercontent.com/8736623/162434547-068fbd7a-cef5-4e6f-a72c-eed86ffde30a.gif)

**Comment by robintown** [comment]
The product team has decided to not add any more effects beyond the five that are currently offered. See [this document](https://github.com/vector-im/element-meta/blob/develop/docs/chat_effects.md) for the rationale.

**Comment by skolmer** [comment]
> The product team has decided to not add any more effects beyond the five that are currently offered. See [this document](https://github.com/vector-im/element-meta/blob/develop/docs/chat_effects.md) for the rationale.

Thanks for sharing your thoughts. Totally makes sense to me. Just noticed that the shared document is missing the "fireworks" effect.
