### ISSUE TITLE
Unable to access the official site

### ISSUE THREAD

**Issue by pofart** [vector-im/element-web#16360]
Hello Dear community and developers!
I can not go to the site element.io , I have a constant load site, and the problem is specifically in my ip (I think so), I have to use tor to access the site, although other people with the same provider do not have such a problem.
My system - elementary os(Linux)
My country - Ukraine

**Comment by jryans** [comment]
This seems like a local / regional networking issue, and I don't believe we can do anything about this unfortunately. For support questions like, feel free to ask in #element-web:matrix.org.
