### ISSUE TITLE
Field to describe your experience too small

### ISSUE THREAD

**Issue by pofart** [vector-im/element-web#16361]
System OS - Elementary OS (but bug have and on Manjaro)
App - official system app
A field to describe your experience too small
![Screenshot from 2021-02-04 00-07-23_modified](https://user-images.githubusercontent.com/74756033/106816053-784a1c00-667d-11eb-9dac-701af532a54c.png)

**Comment by SimonBrandner** [comment]
Duplicate of [#15984](https://github.com/vector-im/element-web/issues/15984)
