### ISSUE TITLE
Call did not connect on first try

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16373]
### Description

Video Call did not connect on first try - ringing and answering work but then there is no connection

### Steps to reproduce

- No idea it just happens

Logs being sent: yes from both clients

### Version information

- **Platform**: web (in-browser) or desktop?

Microsoft Edge latest version (Element v1.7.13) calling Windows client (Element v1.7.20)

**Comment by SimonBrandner** [comment]
@chagai95 Please fill in the issue template

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
