### ISSUE TITLE
On reacting to a message higher up in the timeline, focus jumps to end of timeline

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#16378]
### Description

On reacting to a message higher up in the timeline, focus jumps to end of timeline.

Seems to be a regression on develop only from https://github.com/matrix-org/matrix-react-sdk/pull/5565

### Steps to reproduce

- Scroll up
- React to something

![Peek 2021-02-05 15-54](https://user-images.githubusercontent.com/1174866/107042451-7641a380-67ca-11eb-8f8d-fb5a97ed2243.gif)

**Comment by jryans** [comment]
@SimonBrandner, could you look into fixing this?

**Comment by SimonBrandner** [comment]
@jryans Sure
