### ISSUE TITLE
/html should support more tags

### ISSUE THREAD

**Issue by f0obar** [vector-im/element-web#16376]
When sending my colleague messages formatted by html code i was very frustrated to find out that `<marquee>` tags do not work.

**Comment by t3chguy** [comment]
https://matrix.org/docs/spec/client_server/r0.6.1#m-room-message-msgtypes has a list of suggested permitted tags which Element follows.

**Comment by f0obar** [comment]
The guide you linked doesn't list a msgtype specifically for html, which indicates to me that these messages get send via the normal text type, so supporting my requested tag seems to be just a problem with element-web and not the underlying limitations by matrix.

**Comment by t3chguy** [comment]
```
Some message types support HTML in the event content that clients should prefer to display if available. Currently m.text, m.emote, and m.notice support an additional format parameter of org.matrix.custom.html. When this field is present, a formatted_body with the HTML must be provided. The plain text version of the HTML should be provided in the body.
```

It is not a technical limitation, but a choice based on a suggestion from the Matrix spec.
The Matrix spec suggests what things to allow in `org.matrix.custom.html` - Element respects that suggestion and thus does not allow marquees.

**Comment by f0obar** [comment]
Oh I'm sorry I should've read the whole document you linked. I fully respect the choice to follow the suggested guideline to avoid security issues.

I'm saddened to hear my request can't be added, I'll try suggesting a change in the matrix spec for adding the corressponding tag in the official documentation, because there aren't any known security issues with it to my knowledge.

Thank you for your help!
