### ISSUE TITLE
Feature request: Compress (just) images / pictures before sending

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-web#16388]
Hi,

just to explain why another ticket: https://github.com/vector-im/element-web/issues/14047 is a similar request but want compression for audio and video as well. I think this is not necessary: When you want to compress a Video on a desktop system there is Handbrake as very easy to use software to do so and Audacity for audio files - one can argue this is the same for for sharing pictures / images but from my experience it is exhausting to open another tool for this. So my request:

Would you add a function to compress pictures on default (with opt-in for original size sending) similar to what the mobile versions of Element do? This behaviour is a really great feature expecially for home server admins to "nudge" people to save server disk space.

I don't want to argue with the author of https://github.com/vector-im/element-web/issues/14047 to change the request so I thought it is better to create a dedicated feature request issue because because @t3chguy commented in https://github.com/vector-im/element-web/issues/14047#issuecomment-644401329

> This is hard to implement on a web client for things other than images.

so video and audio compression seems to be the "showstopper" for image compressing in the other ticket.

However: Thank you for Element!

**Comment by t3chguy** [comment]
Right but in either case, best to track this as client-side compression, what exact media that supports is a different story. No point having two distinct issues with such significant overlap. Closing in favour of #14047
