### ISSUE TITLE
Embedded Element in js frameworks

### ISSUE THREAD

**Issue by kkorniszuk** [vector-im/element-web#16382]
Is there any possibility to run Element as embedded component in Angular app without running webpack to get bundle? I tried to use loadApp() method from app.tsx, but I got lots of errors connected with matrix-react-sdk.
#riot-web:matrix.org

**Comment by t3chguy** [comment]
Maybe you should share the errors...?

**Comment by kkorniszuk** [comment]
I'm trying to do it with bundled Element (after calling `yarn build`). The main problem is the fact that all scripts from Element look for other scripts not relative to the place where I call them (for example index.html in Angular app). So for example bundle.js looks for init.js not relative to bundle.js, but from the root. Is there any way to set up a webpack to handle this in another way?

**Comment by jryans** [comment]
I think it would be best to discuss this in a room like #element-web:matrix.org instead of an issue here.
