### ISSUE TITLE
Unable to embed nextloud calendar as custom widget

### ISSUE THREAD

**Issue by andrejohansson** [vector-im/element-web#16386]
### Description

I'm trying to embed a nextcloud shared calendar into a room as a custom widget. But whatever I do, it will not embed. My element web is hosted at `https://im.my.domain` and my nextcloud instance is at `https://cloud.my.domain`.

### Steps to reproduce

1. Share a calendar in nextcloud
        
    ![image](https://user-images.githubusercontent.com/2828428/107118681-acdaf500-6882-11eb-8a6f-3193ec100eb2.png)

1. Add the url as a custom widget in Element
    
    ![image](https://user-images.githubusercontent.com/2828428/107118719-e1e74780-6882-11eb-80f2-be51cf55ef99.png)

1. Make sure that your web server + nextcloud is setting the correct `content-security-policy` header where your domain and `scalar.vector.im` is allowed. My server responds with the following headers

      ```
      HTTP/2.0 200 OK
      cache-control: no-cache, no-store, must-revalidate
      content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: https://source.unsplash.com https://images.unsplash.com;font-src 'self' data:;connect-src 'self';media-src 'self';frame-src 'self' https://im.my.domain/ https://scalar.vector.im/ https://riot.im/ https://matrix.org/ https://*.my.domain/;frame-ancestors 'self' https://im.my.domain/ https://scalar.vector.im/ https://riot.im/ https://matrix.org/ https://*.my.domain/;worker-src 'self' blob:;form-action 'self'
      content-type: text/html; charset=UTF-8
      date: Sat, 06 Feb 2021 12:56:16 GMT
      expires: Thu, 19 Nov 1981 08:52:00 GMT
      feature-policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'
      pragma: no-cache
      referrer-policy: no-referrer
      server: nginx/1.14.2
      set-cookie: oc_sessionPassphrase=Wm8bsTmwXLpstp3aXsQHvrSOMhbRBLZI2rc0Ike4rKaJ29qQX14F1ItGtjEeV%2Fuh4tFCnS7cMCTo%2Fpp8rWxDWvtuYoBFyStqlOB2lwJzCh2SyVYZkMxhEJE0%2BHM; path=/; secure; HttpOnly; SameSite=Lax
      set-cookie: ocz4429llas4a=5obck4ubou3ht7mi9iufqrd3pb; path=/; secure; HttpOnly; SameSite=Lax
      set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
      set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
      x-content-type-options: nosniff
      x-download-options: noopen
      x-permitted-cross-domain-policies: none
      x-robots-tag: none
      x-robots-tag: none
      x-xss-protection: 1; mode=block
      ```
1. The result is a non embedable error

    ![image](https://user-images.githubusercontent.com/2828428/107118811-75207d00-6883-11eb-8633-b15b9b1f08da.png)

## Notes

- The header `x-frame-options` is obsolete and replaced with `content-security-policy`, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

    - Even if it´s obsolete, it does not help to set it at the webserver. I've tried using `x-frame-options: ALLOW-FROM riot.im`, `x-frame-options: ALLOW-FROM https://scalar.vector.im` and `x-frame-options: ALLOW-FROM https://im.my.domain` and others with no luck

- Testing to embed the url `https://example.com` works fine, the headers sent from example.com are

    ```
      HTTP/2.0 200 OK
      age: 271785
      cache-control: max-age=604800
      content-type: text/html; charset=UTF-8
      date: Sat, 06 Feb 2021 12:40:21 GMT
      etag: "3147526947+gzip"
      expires: Sat, 13 Feb 2021 12:40:21 GMT
      last-modified: Thu, 17 Oct 2019 07:18:26 GMT
      server: ECS (nyb/1DCD)
      vary: Accept-Encoding
      x-cache: HIT
    ```

- I've noticed that even if i **unselect Check if content is embeddable** there are still requests going out to `https://scalar.vector.im/api/widgets/embeddable?curl=https://cloud.my.domain/apps/calendar/p/kHx9F3NwsxB5kjoF` to check if the url is embeddable and this is where the response is

    ```json
      {"message":"Embedding content forbidden - X-Frame-Options: SAMEORIGIN","user_error":"X-Frame-Options: SAMEORIGIN"}
    ```

- I suspect that two things might be wrong here

    - https://scalar.vector.im/api/widgets/embeddable should **not** be called if I do not wish the check to be made
    - When https://scalar.vector.im/api/widgets/embeddable is called, it does not know about the `content-security-policy` header and looks for the obsolete `x-frame-options` header and thus gives an erroneous response that the content cannot be embedded

- If this is not the case, I suspect that some of the other headers my server responds with have an impact. If so, which one?

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 86.0b6 (64-bit)
- **OS**: Windows 10
- **URL**: private server, element web version 
app = element-web
version = 1.7.16
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

### Related issues

#10304

**Comment by t3chguy** [comment]
Can you try adding it using `/addwidget <URL>` instead of Scalar?

**Comment by andrejohansson** [comment]
> 
> 
> Can you try adding it using `/addwidget <URL>` instead of Scalar?

This worked, thank you! Is there any way I can set the name of the widget? 
![image](https://user-images.githubusercontent.com/2828428/107129480-e4b75c00-68c5-11eb-8a05-b003feab4f56.png)

**Comment by jryans** [comment]
> Is there any way I can set the name of the widget instead of having "Custom widget"?

I don't believe there's a good way in the UI, feel free to file an issue to suggest it.

> Is there a list of all /commmands somewhere?

`/help` should list them.

If I understand correctly, the main issue is resolved, so I'll close this. #element-web:matrix.org or similar rooms might be a better place for future questions.
