### ISSUE TITLE
Improvements to keyboard/gestural ergonomics

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16384]
1) A user-configurable option to enter messages with Ctrl-Enter instead of Enter would useful when composing longer messages.
2) Placing the Edit action, now on a button, in the context menu and on a mnemonic shortcut key would speed editing.

**Comment by t3chguy** [comment]
1.
Already in settings
![image](https://user-images.githubusercontent.com/2403652/107106701-b46bb100-6824-11eb-932d-91a638db7203.png)


2.
You can edit using keyboard by using arrow keys from the composer.
![image](https://user-images.githubusercontent.com/2403652/107106715-c6e5ea80-6824-11eb-986f-ff3644a34e16.png)

**Comment by Shaping** [comment]
Thanks.  I don't see how to configure the context menu.

**Comment by SimonBrandner** [comment]
@Shaping You currently can't configure these :( I am actually playing with the idea of adding configurable keybindings, so this may be added at some point

**Comment by t3chguy** [comment]
Closing this as per the existing functionality existing.
