### ISSUE TITLE
Flatpak gives all kinds of problems

### ISSUE THREAD

**Issue by 35609902357** [vector-im/element-web#16387]
I installed the Flatpak app on Fedora 33 and it hangs at login screen (not the first login where you must input username/password), the call function doesn't work (there's no "user started call" indication but there's only the "user ended call" indication. I also tried it with the GNOME DE since I read Flatpaks work better with Wayland and it's even worse, it brings me to the login screen (the one where you must input username/password), but if I move the data to another distro it's actually logged in. I don't have these issues on Debian, but to be fair I don't have any issues with other Flatpaks either, they all work as expected on Fedora.

**Comment by t3chguy** [comment]
The flatpak is community maintained. Given that you don't have these issues on Debian it feels like a build/package gone wrong, best to contact the flatpak maintainers

**Comment by aaronraimist** [comment]
Closing in favor of https://github.com/flathub/im.riot.Riot/issues/161
