### ISSUE TITLE
Current element calling sound is so bad it actually hurts, and it will 100% scare people away from what is otherwise a good app.

### ISSUE THREAD

**Issue by michaelharmonart** [vector-im/element-web#16390]
Honestly there's not much to say here, essentially the sound you hear when making or receiving a call is piercing and harsh.
Obviously this isn't a HUGE deal, but these things do add up over time.
It's a small change for a big increase in user experience.

That's all.

**Comment by jryans** [comment]
Yes, we're aware it needs to change, see https://github.com/vector-im/element-web/issues/5031 and similar. Hopefully it will happen soon!
