### ISSUE TITLE
Make "Popout widget" button as real HTML link

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#16396]
### Description

At now in widget area the "Popout widget" button clicks are implemented in JS, so there are no ways to copy that link, for manually open in other app.

### Steps to reproduce

- Open Element-web in some messengers aggregator (Rambox, Ferdi) and room with some widget.
- Click on "Popout widget" button - nothing happens, because opening new windows via JS is blocked.
- Can't find the way to copy-paste the widget URL, for open it manually in some browser

### Proposal

Make the "Popout widget" button in widgets as real HTML link, for make it clickable and with ability to copy link via standard way.

**Comment by SimonBrandner** [comment]
A possible alternative is to add a share/copy button

**Comment by t3chguy** [comment]
The pop out feature is slated for removal as a growing number of widgets rely on the widget API which only works from within the app, this is used for auth and other integrations

**Comment by HarHarLinks** [comment]
The feature appears to have been removed(?) so the issue is invalid. I would like to see it added back, at least for those cases where it does *not* use said API.

**Comment by t3chguy** [comment]
> The feature appears to have been removed(?) so the issue is invalid. I would like to see it added back, at least for those cases where it does not use said API.

It is there, for all widgets which do not say they need a Client via the caps interface.

![image](https://user-images.githubusercontent.com/2403652/152767349-1ed3c4ed-1f83-4333-8139-9fc14eddeb24.png)


The pop-out feature needs to run some code to clean up the widget first (e.g hang up on a Jitsi call so you don't join the same conference twice, discard the pip view etc) so it cannot be a real HTML link which if you copy paste/open in new tab manually would not allow the app to do any such thing.

**Comment by HarHarLinks** [comment]
> would not allow the app to do any such thing

... so the issue is invalid

**Comment by MurzNN** [comment]
Yes, let's close it, thank you for explanation!
