### ISSUE TITLE
Width of audio clip element varies as clip playtime indicator progresses

### ISSUE THREAD

**Issue by wolterhv** [vector-im/element-web#16398]
### Description

(Same as title: width of audio clip element varies as clip playtime indicator progresses.)

### Steps to reproduce

- Upload sound file to chat.
- Play sound file from within element.
- Observe as the progression of the playtime indicator makes the width of the audio element vary.

The width of the audio clip element should stay constant.

![image](https://user-images.githubusercontent.com/347533/107157817-302d4100-697e-11eb-943d-2a18a3b8abed.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 82.0.2
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by t3chguy** [comment]
That looks like your browser's native audio playback widget?

**Comment by wolterhv** [comment]
You're right! To be honest, I had no idea Ff could embed such widgets. Sorry for the trouble, I'll close this ticket now.
