### ISSUE TITLE
"Failed to forget room M_UNKNOWN" error when trying to forget a blocked room

### ISSUE THREAD

**Issue by robertfw** [vector-im/element-web#16392]
### Description

After not using Element for a while, a room that I was in had been blocked. (Pre-emptive self defense, I have no idea what the room content was. I had fired up Element for a brief time and had been poking around various rooms)

It is listed under "Historical". Selecting it shows a message " THE HAPPENING can't be previewed. Do you want to join it? <Join the discussion". Clicking "Join the discussion" shows "Failed to join room: This room has been blocked on this server". 

The above is fine, but when I right click the room in the list and select "Forget room", I get the following error:

"Failed to forget room M_UNKNOWN: User (my user id):matrix.org in room !LTMzhqwoznLaKDLYTc:nerdsin.space"

### Steps to reproduce

I'm not sure how to reproduce this. 

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: Element 1.7.20, olm 3.2.1

**Comment by t3chguy** [comment]
`M_UNKNOWN` is an error from the server, I suggest contacting your server admin to report a bug with their server logs to the software they use for their server.
Related to https://github.com/vector-im/element-web/issues/15559
