### ISSUE TITLE
VOIP call history currently takes way too much space in the message history, and reduces usability and readability. 

### ISSUE THREAD

**Issue by michaelharmonart** [vector-im/element-web#16409]
Currently, the number of line items for even just a single call is kind of ridiculous, and when you end up switching devices, hanging up, switching to a video call, changing camera, etc, the number of lines just skyrockets, filling what's supposed to be a useful history of your conversation with someone into a crowded mess.

Here's an example of a normal conversation, and how many call related lines there are:
[
<img width="392" alt="Screenshot 2021-02-08 100748" src="https://user-images.githubusercontent.com/15620900/107257116-94d8b200-69f7-11eb-9354-d5371e42090d.png">
](url)

The best solution I see is having the call related lines collapsed by default, such as with the beginning of a room.

For instance, if all the calls were missed it could look something like this:
[
<img width="641" alt="Screenshot 2021-02-08 101729" src="https://user-images.githubusercontent.com/15620900/107257251-b6d23480-69f7-11eb-9ed2-190d068d8bd0.png">
](url)

Or if some of the calls were missed and some weren't it could be less specific and look something like this:
[
<img width="646" alt="Screenshot 2021-02-08 101752" src="https://user-images.githubusercontent.com/15620900/107257335-cbaec800-69f7-11eb-8dce-2070711eca15.png">
](url)

And if all the calls are from the same person it could have their display name in the line, such as "4 missed calls from Eric Hendengren" or if it's in a room and with calls from separate people it could be something like "5 Calls from 3 People" with the expand button next to it. Etc.

This significantly improves readability and usability, without sacrificing the ability to click "expand" and see all the details.

Obviously the specifics of exactly what this would look like still need ironed out, but hopefully you get the concept.

I can't really think of any alternatives, other than being able to completely turn off call related lines in the settings, similar to how you can hide the "Deleted Message" placeholders. But I don't see why you wouldn't just have both features.

Of course you would want the calls to be collapsed by default for the sake of space and readability, but it could also be nice to have an option in settings to revert it to being expanded by default, for the occasional person who actually prefers the current look.

This is also platform independent, I think the web, ios, and android version would all benefit from this kind of improvement, but I didn't want to create a bug report for each individually if there's a better way to do it.

Thanks for all the fantastic work on Element everyone, I really appreciate what a great client you've made, and I'm excited to see it improve!

**Comment by michaelharmonart** [comment]
Also, If someone could add the UI/UX label that would be great. I'm assuming I don't have the ability to add it myself (but let me know if that's incorrect).

**Comment by eric-hedengren** [comment]
Thing is, I think this is so well summed up by Michael and I completely agree especially as this was exactly what happened the other day, so I feel like no other comments will come to bring the attention that it needs, so please upvote it.
