### ISSUE TITLE
Room Topic Change not possible (Permission bug)

### ISSUE THREAD

**Issue by chris246** [vector-im/element-web#16407]
### Description

In a room that requires permission "default" to change the room topic, users with role "default" are not allowed to change the room topic.
The Topic field is editable, but the "Cancel" and "Save" Buttons are missing.

### Steps to reproduce
- Create a room
- Allow default users to edit the topic
- As a default user, try to change the topic

Describe how what happens differs from what you expected.
According to the permissions, all uses should be allowed to change the room topic

Logs being sent: no

![element room topic bug](https://user-images.githubusercontent.com/14861996/107241096-f23a2680-6a2a-11eb-9d3f-f214a07c7b5a.png)

### Version information

- **Platform**: Desktop

For the web app:
(There it works using 1.7.13)
- **Browser**: Firefox 85.0
- **OS**: Fedora
- **URL**: private server

For the desktop app:

- **OS**: Linux (Fedora) via Flathub
- **Version**: 1.7.20

**Comment by t3chguy** [comment]
This is already fixed on develop - https://github.com/matrix-org/matrix-react-sdk/pull/5620

**Comment by chris246** [comment]
Thanks
Sorry, I only searched the open issues.
