### ISSUE TITLE
Browser session data lost on web client

### ISSUE THREAD

**Issue by MPeti1** [vector-im/element-web#16411]
### Description

The web client just notified me that some data was lost, and I need to log in again.

### Steps to reproduce
I don't have specific steps to reproduce. I was actually opening [this](https://element.io/get-started) link, which was embedded in a text looking like a Matrix group link.

### Describe how what happens differs from what you expected.

I didn't expect that some session data was removed.

Log: not sent, because the dialog asked me to make an issue first. I am doing that now.    

### Version information

- **Platform**: web

- **Browser**: Firefox 85.0
- **OS**: Windows
- **URL**: app.element.io

**Comment by jryans** [comment]
@MPeti1 Is your browser set to delete storage on quit, or anything like that? 

There's not very much we can do about the browser decided to delete things out from under us unfortunately...

**Comment by MPeti1** [comment]
> 
> 
> @MPeti1 Is your browser set to delete storage on quit, or anything like that?
> 
> There's not very much we can do about the browser decided to delete things out from under us unfortunately...

It isn't. I have an extension that can delete on tab close or some other events, but I haven't set it up so, and also I would notice it by the notification it makes.

Is there a way I could help in finding out what happens, if it happens again? I'm familiar with the browser dev ools.

**Comment by jryans** [comment]
Unfortunately, the browser diagnostics are not very helpful for this case... The debug logs you've sent seem to only contain from after storage is lost, so they don't help much either.

When you do see the message, perhaps check the console for `StorageManager` logs. Are you low on disk space?

**Comment by MPeti1** [comment]
> When you do see the message, perhaps check the console for `StorageManager` logs.
I'll look for it

> Are you low on disk space?
Currently I'm not, and I usually have more than 10 GB of free space, but there can be occasions when I reach 0 bytes free, because I use my system drive for temporary download location of big files before I move them somewhere else, and from time to time it occurs that I forget to move them before I run out of space.
Is it possible that localstorage gets corrupted when this happens while a webpage tries to write to it?

**Comment by t3chguy** [comment]
> Do you think it's possible that localstorage gets corrupted when this happens while a webpage tries to write to it?

Your browser is likely to evict localStorage before that happens but corruption is possible too

**Comment by MPeti1** [comment]
I think I close this for now because it's probable that it was caused by localstorage corruption.
Or at least it's not a problem that I can realiably reproduce, and probably not even a problem on your side.
