### ISSUE TITLE
Pre container for code blocks is duplicated after editing

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16421]
When you edit a code block message, we duplicate the pre container and nest another inside the one that's already there. Previously this made no visual difference, but now that we've added line numbers, it means there's a second set of line numbers.

We should check whether the pre container is already there before adding it.

**Comment by SimonBrandner** [comment]
This also happens to the buttons, but we can't see that

**Comment by SimonBrandner** [comment]
I am working on a fix
