### ISSUE TITLE
Improve the status of send messages (sending, sent, received, failed)

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#16424]
When sending a message in Element, it’s possible for the sent message to be in several states such as sending, sent, received, failed to send. Today, we have different implementations across web, iOS & Android and we’d like to make them consistent across all platforms.

We present here the new design to expose progress states on Element-Web:
   - When sending or encrypting a message: Display a hollow tick at the bottom right of the message (In case of a multi-line message, the tick is aligned with the last line)
   - **The text color is always black (we remove the light grey color (and other colors) for local echos)**
   - When a message is sent: Display a filled tick
   - When a message has been read: Overlay the read receipt, also ‘clearing’ the tick states. In effect, this means that once a message has been sent & read, it doesn’t need to be decorated any more
![image](https://user-images.githubusercontent.com/8969772/107431304-8b9a3300-6b26-11eb-9f27-61be8cdeab82.png)

   - When a message failed to sent: Display an exclamation mark (on a red background) where the tick lived. (see #16423 to handle the failed messages)
![image](https://user-images.githubusercontent.com/8969772/107431331-981e8b80-6b26-11eb-8d62-64b8e352c224.png)

   - In case of an attachment (image/video/file...), display a progress bar above the composer during the media encryption and its upload.
When this attachment is actually sending display a hollow tick, replaced by a filled tick when this is done:
![image](https://user-images.githubusercontent.com/8969772/107432312-116aae00-6b28-11eb-9c66-b8f0eda2c4bf.png)
Compare to the existing code:
      - Change the way attachments are visually represented
      - Modify uploading visual style and string placements
      - Respect default text style for the uploading states ( Only keep the person’s name. Currently it shows the person’s name + action e.g: Steve is uploading. Ideally this should be removed and only the name should be kept.

**Comment by turt2live** [comment]
Approximate updated design (figma pending):
![image](https://user-images.githubusercontent.com/1190097/108888288-7d3d2400-75c8-11eb-8578-faaf6a80dba9.png)

**Comment by turt2live** [comment]
This portion is done - closing in favour of https://github.com/vector-im/element-web/issues/16423 to cover the remaining half
