### ISSUE TITLE
Video doesn't resume one way after hold

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#16422]
Looks like when we resume a video call from being held, the video only resumes one way. When I tested, it stayed black on the side that un-held.

**Comment by t3chguy** [comment]
I saw this with @lampholder

**Comment by t3chguy** [comment]
https://github.com/matrix-org/element-web-rageshakes/issues/4160 is an instance of this

**Comment by SimonBrandner** [comment]
AFAIK, we fixed this, shout if you ever see this again
