### ISSUE TITLE
VOIP keypad location

### ISSUE THREAD

**Issue by irelativism** [vector-im/element-web#16431]
After question putted by Nad, 
about VOIP recent integration and respective keypad location, and polish made to UI.

The keypad should be in the same place were phonecall is, so given the end-a-call is inside widget. You could use such real-estate of the call button for the keypad.

P.S. I think IOS does a similar thing. Would be a great design and make for a much more smooth and and refined experience. This also should be done, in conjugation with simplification of messagetray buttons. bug report #16333 .

![keypadUX|UI](https://user-images.githubusercontent.com/75645715/107890085-f674b100-6f0e-11eb-8ded-2f9a9dffff34.jpeg)

Cheers, IRELATIVISM.

**Comment by irelativism** [comment]
@jryans could you add the following tags as well ux/ui and design.

**Comment by jryans** [comment]
@irelativism After reading this issue again, I don't think I understand what you are suggesting here... There's currently a keypad button inside the video window I believe... What do you want to change about it?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if you can explain this

**Comment by irelativism** [comment]
Its hard to do so, when you are censored out of the main discision room. There are serious issues in how some element team members lead with contructive criticism and refutations to their positions. So no worries in closing my interest in matrix is diminishing by the day until this important problems get addressed.
