### ISSUE TITLE
Simultaneous calling lead to bug/confusion

### ISSUE THREAD

**Issue by jooooscha** [vector-im/element-web#16440]
### Description

When calling someone who is starting a call back around the same time, neither of the both see that the other one is calling until both hang up and _one_ is starting another call.

### Steps to reproduce

Happens to me on android and electron desktop version.

I would expect that when both are calling at the same time, the call would just be connected, because both users showed intend to call the other person.

### Version information

- **OS**: Arch Linux, Android
- **Version**: 1.7.16, 1.0.14 (Fdroid)

**Comment by SimonBrandner** [comment]
Hmm, glare doesn't seem to be handled when calling EA <-> EW, though I have a feeling EW is not to blame here since this tends to work EW <-> EW

**Comment by SimonBrandner** [comment]
Yeah, I am fairly sure this is an Android issue, so I am going to close this. @jooooscha, could you please file this at https://github.com/vector-im/element-android?
