### ISSUE TITLE
Search is not working in secure rooms

### ISSUE THREAD

**Issue by onutz** [vector-im/element-web#16448]
### Description

In windows app, when searching for strings, no matter short or long, "no results" is always returned. 

### Steps to reproduce
- Write anything in an encrypted room;
- search for what you wrote;
- "No results" is showing

Describe how what happens differs from what you expected.

Log: sent/not sent?    

Element version: 1.7.20
olm version: 3.2.1

Win10 app

For the desktop app:
Win10 Pro, v 20H2

**Comment by jryans** [comment]
@onutz What do you see in User Settings -> Security -> Message Search?

**Comment by onutz** [comment]
![image](https://user-images.githubusercontent.com/556457/108235210-ab4cdf00-7156-11eb-8a83-093ffbb2a37e.png)

**Comment by jryans** [comment]
Hmm, that seems normal... @poljar, what additional info would help work out what's happening here?

**Comment by poljar** [comment]
The stats are fetched out of the SQLite database but the search results are first fetched from the Tantivy index and only then is the SQLite database queried to convert the event ids from the search result into full events.

This sounds either like a desync between the database and the index, or the expected search string indeed isn't part of the index/database. A disable/enable cycle should improve things unless there's a more complicated issue here.

**Comment by onutz** [comment]
I have reset and re-enabled the index, it works properly now! Thank you for your support!

**Comment by onutz** [comment]
I have reset and re-enabled the index, it works properly now! Thank you for your support!
