### ISSUE TITLE
Use the Desktop app to search encrypted messages

### ISSUE THREAD

**Issue by jgarte** [vector-im/element-web#16441]
### Description

I'm running into a bug where I get "Use the Desktop app to search encrypted messages" in certain rooms. I'm using the Desktop app when I get that message.

- **OS**:
$ nixos-version
20.09.2996.002c001ab6f (Nightingale)
```
- **Version**: 
Element version: 1.7.20
olm version: 3.2.1

**Comment by t3chguy** [comment]
unofficial desktop build without seshat

**Comment by austinbutler** [comment]
See https://github.com/NixOS/nixpkgs/issues/87752.

**Comment by beedell-roke** [comment]
> I'm using the Desktop app when I get that message.

@jgarte, why is this filed at the `element-web` repository, then?
