### ISSUE TITLE
Seshat builds incorrectly

### ISSUE THREAD

**Issue by maisiliym** [vector-im/element-web#16452]
[Quote](https://github.com/NixOS/nixpkgs/issues/87752#issuecomment-778564934) (emphasis added)
> It turns out to be much more complicated, because the cargo build of seshat-node-native calls npm install, so we have multiple layers of npm calling yarn calling cargo calling npm. With lots of things being downloaded and executed. *It's a huge shitshow.*

nixpkgs issue for more info: https://github.com/NixOS/nixpkgs/issues/87752

Note: Li doesnt really do github, but matrix is a daring project, so they get a(nother) free tip from him. Expect no more followup from him.

**Comment by jryans** [comment]
I do not really know what to do with this... 😕 It's complicated, sure. We're not aware of a pre-existing process for building all of the native modules in the way we need, and we have something that works.

If someone has a specific plan that might simplify it, please discuss it with us in #element-dev:matrix.org.
