### ISSUE TITLE
Permanent desynchronisation with IRC Bridge

### ISSUE THREAD

**Issue by gcp** [vector-im/element-web#16454]
I extensively use the Freenode IRC bridge for work and private conservations. Connectivity has always been spotty, but invite-only channels are a huge pain as they don't automatically reconnect if the bridge goes down (which seems to happens every few days). As of 3-4 days, I'm dealing with a sort of permanent desync that renders the IRC bridge unusable:

1) To join this invite-only channel, I message Chanserv invite #channel, then tell "Freenode IRC Bridge status" !join channel,
2)  As of 3-4 days, this no longer works, and Chanserv tell me "Channel #channel is not registered."
3) Freenode IRC Bridge tells me, after trying to join "Could not join #channel on 'chat.freenode.net': err_inviteonlychan" (Gee, but Chanserv just claimed it isn't registered!)
4) On another Element session on another PC, I'm shown as being inside the channel, but trying to send any message errors out with: User @gcp:mozilla.org not in room !blablabla:matrix.org (<FrozenEventV3 event_id='$ieA1KjKFoMUPNo8TE0TcHs1deBmj79a_EuFikVNlUg0', type='m.room.member', state_key='@gcp:mozilla.org'>)

**Comment by t3chguy** [comment]
The IRC bridge is not part of Element Web.
It is https://github.com/matrix-org/matrix-appservice-irc

but for the issue you are having reaching out to the support channel for that instance is probably best.

I suggest https://matrix.to/#/#irc:matrix.org

**Comment by gcp** [comment]
@t3chguy is the error in (4) related to the bridge or the client?

**Comment by t3chguy** [comment]
Neither, that error is from Synapse.
Sounds like either your Element either had a stale cache or a Synapse bug meant it missed the room in your `/sync`
