### ISSUE TITLE
Spaces folder hierarchy and design workflow

### ISSUE THREAD

**Issue by irelativism** [vector-im/element-web#16451]
After the brief apresentation of spaces by Matthew Hodgson on FOSDEM. I would like to advise against spaces childs to open inside the left Spaces UX/UI vertical bar. I think it makes for a clunky experience, especially when indentation is used, and for a overall for a very unrefined experience.

Other in app real-state should be used for such purpose. Including the room list tile or if that is to be avoided a dropdown arrow system (similar to room-list, but just with spaces profile images) while keeping the spaces bar "fatness" to a minimum, which is very important for smooth usability.

My suggestion and what I believe would be the most intuitive would be to display the subspaces (general spaces child's) with respective rooms or other spaces child's in the room tile (aka. room list), giving it utilizes a bit more space, so that users can navigate such hierarchy at ease. And at the same time maintaining the spaces vertical bar only for traceability and not actual selection.

#16450 also should be considered for this feature request, given it would englobe the whole dynamic in a simple easy to understand user experience.

**Comment by t3chguy** [comment]
This issue makes no sense. Please fill the template.

**Comment by irelativism** [comment]
> This issue makes no sense. Please fill the template.

has description sugested with WIP??!! was not yet finished. given the referenced issue needed to be finished first. Cheers, nontheless.

**Comment by HansJK** [comment]
Please present a mockup of what you are talking about.

**Comment by SimonBrandner** [comment]
I am not exactly sure what @irelativism is suggesting but might something like merging the space panel and the room list - rooms and spaces would be a part of one tree

**Comment by irelativism** [comment]
this arrogant attitude by the element team never stops to amaze me. One would feel empowered to take this to british court, multiple abusive bans now, without any basis or warning, just because is not confortable to talk about teams pitfalls. You only make people work on alternative protocols to matrix.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19140 as I believe it has a more detailed description and features mockups
