### ISSUE TITLE
user name mention notifications happen when user name is mentioned without any qualifying prefix/suffix

### ISSUE THREAD

**Issue by Be-ing** [vector-im/element-web#16465]
### Description

My Matrix user name is simply `be`, which is a common English word. Element triggers a notification anyone uses my user name, which is almost always not actually trying to send a message to me. This makes notifications from Element basically unusable. User name mentions should only trigger a notification with an appropriate prefix such as `@` or a suffix such as `:`

### Steps to reproduce

- Use a user name that is a common word
- Be annoyed by notifications for irrelevant mentions of your user name

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 84.0.2
- **OS**: Fedora 333
- **URL**: https://webchat.kde.org

**Comment by t3chguy** [comment]
This is a Matrix spec issue, rather than an Element one.

https://matrix.org/docs/spec/client_server/r0.6.1#m-rule-contains-user-name defines it as `[the local part of the user's Matrix ID]` and is implemented in both Clients and Servers

I suggest opening an issue in https://github.com/matrix-org/matrix-doc if you think that should change

**Comment by Be-ing** [comment]
> I suggest opening an issue in https://github.com/matrix-org/matrix-doc if you think that should change

Will do. I don't know why this is different from pretty much every other modern system that uses an `@` prefix.

**Comment by Be-ing** [comment]
I also don't really understand why that's part of the Matrix specification. I think clients should be able to handle notifications however they want.

**Comment by t3chguy** [comment]
Because clients rely on servers for push notifications, so servers apply the same rules

Closing in favour of https://github.com/matrix-org/matrix-doc/issues/3011

**Comment by Be-ing** [comment]
That makes sense
