### ISSUE TITLE
Weblate "few" plurals support

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#16463]
Please add "few" form for plurals to matrix-react-sdk as it is for Android app.
Tanslation strings like **%(count)s people** exist in form _one_ or _other_ only.
In some languages like Czech it sounds silly to use _other_ form for count 2-4.
Thanks.

**Comment by t3chguy** [comment]
Counterpart only supports `one` `other` `zero`
https://www.npmjs.com/package/counterpart

So I suggest opening this request upstream: https://github.com/martinandert/counterpart

**Comment by waclaw66** [comment]
Counterpart issue has been created.
https://github.com/martinandert/counterpart/issues/50

**Comment by waclaw66** [comment]
Not sure, but it seems that other plural forms like **few** or **many** are already supported for certain languages (cz, sk, ru), but not documented.

**Comment by waclaw66** [comment]
Related to https://github.com/vector-im/element-web/issues/14845

**Comment by comradekingu** [comment]
@waclaw66 Weblate is Czech software, so I would imagine it is set up correct out of the box, and just the forms are missing(?)

https://hosted.weblate.org/languages/cs/#information is the setup on Hosted.

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/16463
