### ISSUE TITLE
Email address mistakenly marked as wrong

### ISSUE THREAD

**Issue by Freudentaumel** [vector-im/element-web#16460]
I would like to add my email address matrix@adamger.occumail.net. Unfortunately, it is rejected because it does not appear to be an email address.

However, it is a correct email address and I would like to know how to add it.

With kind regards
Gerhard

**Comment by t3chguy** [comment]
Works fine here in my testing, does not appear as invalid.

**Comment by Freudentaumel** [comment]
Now it works - thank you.
