### ISSUE TITLE
element-desktop no candidate version in bullseye

### ISSUE THREAD

**Issue by elmussol** [vector-im/element-web#16469]
### Description

Trying to install element-desktop from https://packages.riot.im/debian bullseye but on `apt install element-desktop` get `No candidate version found for element-desktop`.

### Steps to reproduce
- `wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`
- Add the following line to `/etc/apt/sources.list`: `deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ bullseye main`
- Run `apt update` with no errors.
- Run `apt install element-desktop` and get `No candidate version found for element-desktop`.

Describe how what happens differs from what you expected.

I expect element-desktop to be installed.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: fully up-to-date Debian Testing/Bullseye.

**Comment by SimonBrandner** [comment]
Weird, I can't reproduce this

**Comment by elmussol** [comment]
Addition info:
```
root@hodder:/etc/apt# apt show element-desktop riot-desktop
Package: riot-desktop
Version: 1.7.0
Priority: optional
Section: oldlibs
Maintainer: packages@element.io
Installed-Size: unknown
Depends: element-desktop
Download-Size: 740 B
APT-Sources: https://packages.riot.im/debian bullseye/main i386 Packages
Description: transitional package
 This is a transitional package. It can safely be removed.

Package: element-desktop
State: not a real package (virtual)
N: Can't select candidate version from package element-desktop as it has no candidate
N: Can't select versions from package 'element-desktop' as it is purely virtual
```

**Comment by elmussol** [comment]
Not reproduceable by Simon. Additional troubleshooting and sharing of configs shed no more light. Just weird.

**Comment by t3chguy** [comment]
Is this a 32 bit system? If so Electron dropped support for 32 bit https://www.electronjs.org/blog/linux-32bit-support

**Comment by SimonBrandner** [comment]
@t3chguy, yes it is

**Comment by t3chguy** [comment]
Ah yes, `i386`

**Comment by elmussol** [comment]
@SimonBrandner @t3chguy Thanks for the clarification. The user will just have to use the web interface.
