### ISSUE TITLE
'Your server isn't responding to some requests' is displayed sometimes when room notification level is changed

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#16472]
When clicking on the bell icon on a room in the sidebar and changing the notification level, very often I get a message in the bottom left corner of the screen saying that "your server isn't responding to some requests". Possibly the first time I adjust notification settings after an app restart?

**Comment by kittykat** [comment]
@dbkr Are you still seeing this issue reproducibly?

**Comment by SimonBrandner** [comment]
I can, it just sometimes flashes in the bottom-left corner
