### ISSUE TITLE
Desktop app UI rendering strangely

### ISSUE THREAD

**Issue by prrathi** [vector-im/element-web#16475]
<img width="826" alt="Screen Shot 2021-02-17 at 17 56 15" src="https://user-images.githubusercontent.com/53785742/108283917-d2e97a80-7149-11eb-94b8-d33bdfb370ec.png">
<img width="1191" alt="Screen Shot 2021-02-17 at 18 15 41" src="https://user-images.githubusercontent.com/53785742/108285186-35437a80-714c-11eb-8775-83c90c830dd5.png">

### Description

The entire Element interface seems to be rendering oddly, with all the normal buttons to other pages like 'Sign in' in the body text and not having any other appearance. When the Sign in is clicked, that page also has problematic UI, with the sign in on the top right faded out. Other problems in the interface can be seen in the screenshots provided.

### Steps to reproduce

- Open any page on the desktop app or Chrome browser

When Element is opened on an incognito window in chrome, its UI appears to be normal, but on normal windows in chrome or the desktop app it doesn't.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Chrome version 88.0.4324.150
- **OS**: macOS
- **URL**: app.element.io 

For the desktop app:

- **OS**: macOS
- **Version**: not sure because don't know how to access with this UI

**Comment by t3chguy** [comment]
I've seen this happen when it conflicted with some browser extensions. Try a clean profile for Chrome. Never seen it in the desktop app though.

**Comment by jryans** [comment]
@prrathi Hmm, that's very strange, especially when you say it goes away in private windows. Please try the steps @t3chguy mentioned above.

**Comment by prrathi** [comment]
Thanks, it was the Dark Mode extension on Chrome.
