### ISSUE TITLE
Device dehydration does not work

### ISSUE THREAD

**Issue by jamescl** [vector-im/element-web#16476]
### Description

Messages sent when offline are showing `** Unable to decrypt: The sender's device has not sent us the keys for this message. **` errors, even though device dehyration is enabled in the config.json with `    "features": {
        "feature_dehydration": true
    },`

### Steps to reproduce

- Bob creates a room with Alice
- Alice logs in and verifies her session with her backup key. We can see the dehydrated device in the device and dehydrated_device table in the synapse database.
- Alice and Bob send each other messages and everything is fine
- Alice logs off (or just closes the incognito window), leaving her with no devices.
- Bob sends Alice a message
-  Alice logs in and verifies her session with her backup key. We can see a new dehydrated device in the device and dehydrated_device table in the synapse database.
- Alice can't see the message Bob sent while she was logged off.
- Alice and Bob send each other messages and everything is fine with these new messages.

In the Chrome Browser console, the following messages are being displayed in Alice's new session
```
Got session backup key from secret storage: caching
Secure Secret Storage ready
Setting dehydration key
downloadKeys: already have all necessary keys
Checking key backup status...
Attempting to dehydrate device
Creating account
Uploading account to server
Finished background key sig upload for {new_device_id}
Finished background key sig upload for {new device_id,public_key}
Backup version 3 still current
Preparing device keys {new_backup_device_id}"
Marking device list outdated for @user:homeserver

...
Done dehydrating
...
```

### Version information
Running synapse 1.27.0 and private element web 1.7.21 on Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by jryans** [comment]
@uhoreg, perhaps one for you to look at?

**Comment by jamescl** [comment]
I've tried out Element Web v1.7.24-rc.1 and this doesn't seem to have fixed the issue I was having, and @uhoreg I think the root cause is different thank your fix, in that Element doesn't seem to think a dehydrated device exists (when it does), and creates a new one.

I'm seeing a "no dehydrated device" found message in the console I didn't see before (not sure if I missed it, or if it wasn't there...), but what I think is happening is:

- Makes a GET request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device 
- Outputs "no dehydrated device" **before the GET request returns**
- Makes a second GET request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device  (after receiving keys from /_matrix/client/r0/keys/query)
- The user enters their recovery key after being prompted to verify this session
- Element makes a PUT request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device to set a new Backup Device
- Uploads keys to the new device via POST to /_matrix/client/r0/keys/upload/ 





**More info /screenshots below**


I can see the "no dehydrated device" message appear while the request is still pending (Can also see the console log appear before the event appears in synapse's homeserver.log)
![image](https://user-images.githubusercontent.com/2550644/112741397-41371d80-8fd1-11eb-8102-66ee582c27c6.png)

Showing of the GET and POST requests 
The two GET requests contain valid data of the initial dehydrated device, with the following data `{"device_id":"DEVICEID","device_data":{"algorithm":"org.matrix.msc2697.v1.olm.libolm_pickle","account":" encryted content "}}`
![image](https://user-images.githubusercontent.com/2550644/112741502-1ef1cf80-8fd2-11eb-8ce0-89976dc680c2.png)

The message in context of other messages if that's useful:
```setLoggedIn: mxid: @user:homeserver deviceId: XXXXXXXXX guest: false hs: https://homeserver/ softLogout: false  freshLogin: true
StorageManager: Checking storage consistency
StorageManager: Local storage supported? true
StorageManager: IndexedDB supported? true
StorageManager: Local storage contains data? true
StorageManager: Crypto initialised? null
StorageManager: Sync store using IndexedDB contains data? false
StorageManager: Crypto store using IndexedDB contains data? false
StorageManager: Storage consistency checks passed
no dehydrated device found
Session persisted for @user:homeserver
Lifecycle: Starting MatrixClient```

**Comment by SimonBrandner** [comment]
@jamescl, please open a new issue
