### ISSUE TITLE
New and larger URL preview is a regression imo

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#16479]
### Description

https://github.com/matrix-org/matrix-react-sdk/pull/5637 is a regression in my opinion. The larger preview wastes screen real estate because fewer messages is visible at the time
Especially in rss/github rooms. But, also in normal chats. The old small preview was large enough to get a feel for what it was about. If I want to see a larger version I'll click the link

New:
![Screen Shot 2021-02-18 at 01 44 48 PM](https://user-images.githubusercontent.com/19155609/108366733-9c1a6f80-71f0-11eb-939e-3a01345b59a5.png)

vs old:
![Screen Shot 2021-02-18 at 01 45 08 PM](https://user-images.githubusercontent.com/19155609/108366753-a0468d00-71f0-11eb-94b4-252903f118a4.png)

### Steps to reproduce

- Post a link in any room where inline URL preview is enabled

Logs being sent: no

### Version information

develop.element.io
Element version: `29fd47d611c2-react-68933c1a3d42-js-371ca009e9e2`

**Comment by jryans** [comment]
I think one detail we should consider here is that URL previews are quite different from image previews. A URL preview for a non-image should properly use a small left-aligned avatar much more like the previous appearance.

If however we know for certain that a URL is previewing an image, perhaps the new layout with wider image is more apprpropriate.

**Comment by callahad** [comment]
Twilight's absolutely right that this takes a problem with link previews and makes it worse (synapse-dev can be borderline unusable even with previews disabled due to bot traffic).

_However_ the smaller _image_ previews are a godsend. Surprisingly significant improvement to my user experience.

**Comment by babolivier** [comment]
While I agree with the feedback regarding URL previews, it also limits the size of image files sent in the timeline, which I like because it makes the room timeline much more readable. So maybe the right fix would be, rather than reverting the change entirely, to revert it only for URL previews (if the URL isn't the one of an image directly)?

**Comment by Twi1ightSparkle** [comment]
I agree thay the smaller image previews are amazing. Maybe that bit can be kept, and the URL inline preview be reverted?

**Comment by SimonBrandner** [comment]
I like the bigger URL previews. But in some cases, they're not ideal. I like what @jryans suggested

> I think one detail we should consider here is that arbitrary non-image URL previews are quite different from image previews. A URL preview for a non-image should probably use a small left-aligned avatar much more like the previous appearance.

**Comment by jryans** [comment]
> @nadonomy, @jryans, please can we **not** ship this until we've got aligned.

Sure, that's why we're collecting feedback in this issue, which is already marked a release blocker.

**Comment by benparsons** [comment]
I'm less concerned about the images (though prefer smaller), but definitely agree that the vertical URL previews make rooms harder to view. Scrolling TWIM right now is quite annoying unfortunately, due to the amount of vertical space.

**Comment by jryans** [comment]
I am working with @nadonomy on this, and we'll have more details here before the RC on Wednesday.

**Comment by nadonomy** [comment]
Thanks everyone for the feedback! After chewing the fat on this we've decided to rollback [the PR](https://github.com/matrix-org/matrix-react-sdk/pull/5637), for several reasons:

1. To address the feedback from this issue and via other channels
2. When reviewing the PR, we didn't quite consider how far reaching the changes would be 
3. @SimonBrandner has a [draft PR](https://github.com/matrix-org/matrix-react-sdk/pull/5666) which treats images and URL previews distinctly, which we believe is the right approach
4. However, to land it, we'll need to consider things like if any character measures or limits are desirable to increase legibility, whether we want to special case any links (e.g. by domain or URL, to do things like display larger thumbnails for videos), the right visual balance for thumbnail sizes, taking into account when we have things like message bubbles, etc

...along with a bunch of other related issues we haven't discovered yet!

So for now, given the timeliness with the PR we're rolling back the changes, closing this issue, and will follow up with the other draft PR to continue to iterate on this.
