### ISSUE TITLE
resizing GUI components per click and drag is flaky

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16482]
### Description
resizing GUI components per click and drag is flaky

### Steps to reproduce

- open the app 
- resize GUI components as shown in the screen cap

The resizing is not stable and frustrating..

Logs being sent: no

Here is a screen cap:

https://user-images.githubusercontent.com/31655082/108463276-5d32fb00-727e-11eb-819d-69973d7fe2a6.mp4

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome
- **OS**: Windows
- **URL**:  app.element.io

**Comment by lampholder** [comment]
Very similar to https://github.com/vector-im/element-web/issues/16473

**Comment by lampholder** [comment]
I think this was fixed along with https://github.com/vector-im/element-web/issues/16473
