### ISSUE TITLE
Windows updater keeps two versions present instead of just one

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16487]
![image](https://user-images.githubusercontent.com/31655082/108467028-db929b80-7284-11eb-9254-43979ef87138.png)

### Description

Describe here the problem that you are experiencing, or the feature you are requesting:

Old Element Electron App/s folders not deleted

### Steps to reproduce

- install the new version by clicking update app when the pop up arrives for example
- open windows settings or check the element folder under local

Describe how what happens differs from what you expected. - 
I expect the old folder to be deleted.

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **Version**: 1.x.y  a few of the last versions

**Comment by jryans** [comment]
@chagai95 Hmm, do you have many such old versions left around, or does it seem more like a one time issue...?

**Comment by chagai95** [comment]
I think I've seen this with two updates already

**Comment by jryans** [comment]
I believe at the moment, the Windows updater does tend to leave one previous version installed (but not accessible via shortcuts or anything). On the next update, the oldest previous version is then removed.

@chagai95 Have you ever observed **more** than 2 versions being present?

**Comment by chagai95** [comment]
Nope, I'll report back if I do

**Comment by benparsons** [comment]
This seems to be the expected (if not desired) behaviour - the Windows electron updater simply works this way? Is there any intention to change that?

**Comment by jryans** [comment]
If there are only every two versions, then yes that's currently the expected behaviour of the updater. I would like mean delving into the details of the Squirrel updater service to change this, which would likely be complex and high risk to change.

**Comment by chagai95** [comment]
This Does not happen anymore on Windows 11 and it's not a big deal so I'm gonna close this, thanks all.
