### ISSUE TITLE
Encrypted by a deleted session red icon

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16486]
![image](https://user-images.githubusercontent.com/31655082/108466688-54452800-7284-11eb-81b1-81810d38dd7e.png)

### Description

Is this going to stay like this? Why is this important? If the session was verified at the time then it shouldn't really be a security risk, or am I missing something? Anyway, in general the red icon is very intimidating for end users, but we can always change that ourselves, just wanted to mention this, perhaps you agree.

### Steps to reproduce
not sure, but I think just have an unverified session in a room

Describe how what happens differs from what you expected:
maybe a less intimidating UI? Like the grey/black  security shield even thought you can also verify the user and make it green with a tick inside

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop? both

For the web app:

all latest versions

For the desktop app:

all latest versions

**Comment by SimonBrandner** [comment]
Duplicate of [#13701](https://github.com/vector-im/element-web/issues/13701)
