### ISSUE TITLE
Pasting into inline message edit field moves focus to composer

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16497]

**Comment by t3chguy** [comment]
I can no longer reproduce this, but think I saw it about a month ago and can't recall anything fixing it - can anyone repro?

**Comment by yannicka** [comment]
I can't reproduce the problem either (neither on desktop nor on browser, version 1.7.29).

**Comment by SimonBrandner** [comment]
Since no one seems to be able to repro this, let's close it. Feel free to shout if this is still a problem for you

**Comment by t3chguy** [comment]
I just hit this again

**Comment by t3chguy** [comment]
Presuming fixed, will re-open if it bites me again
