### ISSUE TITLE
another user's domain containing my name causes extra pings

### ISSUE THREAD

**Issue by namazso** [vector-im/element-web#16496]
### Description

When another user's mxid has a domain that matches my username gets quoted, element fires an incorrect ping

### Steps to reproduce

- your mxid is @john:example.com
- @foo:john.com sends a message
- @bar:john.com quotes the aforementioned message
- you get pinged

I did not expect to get pinged.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.21

**Comment by t3chguy** [comment]
This is a Matrix spec issue rather than an Element one; Closing in favour of https://github.com/matrix-org/matrix-doc/issues/2319
