### ISSUE TITLE
UIFeature.passwordReset doesn't seem to work

### ISSUE THREAD

**Issue by dognodding** [vector-im/element-web#16499]
### Description

I have moved my users to SSO via OIDC. The user accounts previously existed on synapse and I do not want the users to be confused by any remnants of the native synapse account. The config options "UIFeature.registration" (remove registration link from the home page) and "UIFeature.deactivate" (remove the UI option to deactivate the account) both work.

The config option "UIFeature.passwordReset" seems to have no effect. Whether set to "true" or "false", the "Set a new account password..." fields on the Settings -> General page are shown. However, since after moving the users to SSO, local passwords have been disabled in the `password_config` section of synapse's homeserver.yaml, the fields have no effect and generate a HTTP 400 error when the button "Change Password" is clicked.

![Change_Password](https://user-images.githubusercontent.com/38298560/108602349-bcd5f700-73a1-11eb-876b-3e4db14d6a47.png)

With a different homeserver, where users never had local accounts on synapse and only log in via SSO, the "Set a new account password..." fields in Element are not shown.

### Steps to reproduce

- Set up a synapse homeserver and create some users
- Then set up OIDC SSO with an external IdP and add users' accounts
- Change settings in synapse to disable password (i.e. local passwords)
- Set element-web config option "UIFeature.passwordReset" to either "true" or "false"
- The fields to allow password changes under Settings -> General are always shown

Describe how what happens differs from what you expected.

- If "UIFeature.passwordReset" is set to "false", then the fields allowing password changes under Settings -> General should not be shown.

Logs being sent: no - I downloaded the logs but found no mention of UIFeature

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chromium (88.0.4324.182), Firefox (85.0.1)
- **OS**: Ubuntu 20.04.2
- **URL**: Private server, Element Web 1.7.21
- **Version**: Desktop version 1.7.21 (although no UIFeature are changed)

**Comment by t3chguy** [comment]
`UIFeature.passwordReset` as per https://github.com/vector-im/element-web/blob/develop/docs/config.md governs the password *RESET* page. 

![image](https://user-images.githubusercontent.com/2403652/108603587-bb57ff00-73a0-11eb-9170-c4b3be9050a0.png)
![image](https://user-images.githubusercontent.com/2403652/108603590-bb57ff00-73a0-11eb-9d4d-3295ec11f9f0.png)



For disabling Settings > General > Password change capability that is controlled by the Matrix homeserver using the Capabilities API. https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-capabilities `m.change_password`

**Comment by dognodding** [comment]
OK, thanks! Then I just need to find out how to configure that...
