### ISSUE TITLE
no audible or popup notification about invitation to room

### ISSUE THREAD

**Issue by dovf** [vector-im/element-web#1649]
It seems that I'm not getting an audible notification about being invited to a room, even though I have the "When I'm invited to a room" option set to "Highlight & Sound". Audible notifications for normal messages are working fine.
I'm experiencing this issue on the official vector.im/beta instance, both on Firefox/Linux as well as Chrome/Windows.
Thanks!

**Comment by richvdh** [comment]
Yup I'm seeing this too

**Comment by richvdh** [comment]
(This happens because `Notifier.js` registers a listener on `Room.timeline`, but of course the invite isn't added to an existing room, so doesn't trigger the `Room.timeline` event. Guess it needs to add a `Room` listener too.)

**Comment by TheButterZone** [comment]
Same issue with invitations to Freenode private message not notifying. Or should I open a new issue for that? Didn't find one in the search.

**Comment by SimonBrandner** [comment]
Closing as this doesn't seem to be a problem anymore
