### ISSUE TITLE
A user changing their displayname results in "$user joined the room"

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#16506]
I presume Element goes off the cached member state to tell if a membership join event is a newly joined user or a name change. This suggests either some state being lost of a recent regression. I've only started seeing this recently on 1.7.21, so feels like something got broken

**Comment by t3chguy** [comment]
It goes off prevContent on the event, which should be coming from the server, if it is missing then it may cause something like this

**Comment by Half-Shot** [comment]
I wonder if Synapse has recently stopped providing that information. It definitely feels like a new regression.

**Comment by Half-Shot** [comment]
I can confirm that Synapse didn't send any prevEvent information for the event down sync, so this might be broken.

**Comment by Half-Shot** [comment]
Going to close this. I think this is more likely to be the result of my tinkering.
