### ISSUE TITLE
Loading on startup gets stuck on spinner

### ISSUE THREAD

**Issue by mirdaki** [vector-im/element-web#16503]
### Description

If I set Element Desktop to load on startup (using the Gnome Tweaks tool), it usually (though not always) gets up to a spinning loading icon and just stays there. Closing or quitting the app than relaunching does not change the behavior. If I kill all element process than relaunch the app, then it loads normally. If it is not set to load on startup, I have not encountered the issue.

Though I don't have a solid timeline, this has been happening for several months now.

### Steps to reproduce

- Have Element start on Startup

It should finish loading and bring up the full application

Logs being sent: yes

![image](https://user-images.githubusercontent.com/8786151/108633251-1b45b880-7428-11eb-8daf-33f4223e731f.png)

### Version information

- **Platform**: Desktop
- **OS**: Fedora 33 (Gnome 3.38.4 with Wayland)
- **Version**: 1.7.21

**Comment by jryans** [comment]
@mirdaki Hmm, so when it is set to launch on startup, are there multiple copies of the app trying to run at the same time...?

**Comment by mirdaki** [comment]
Not that I can see. There isn't a second window and the number processes look the same regardless of the issue or if it's running normally:
![image](https://user-images.githubusercontent.com/8786151/110416417-8d351900-8048-11eb-9cff-edbe132153b9.png)

**Comment by turt2live** [comment]
Have people been seeing this lately? Just tried on Fedora 36 and it started up just fine multiple times.

**Comment by mirdaki** [comment]
I have not seen this in a while. I'm on Fedora 35 and 36

**Comment by turt2live** [comment]
Considering fixed.
