### ISSUE TITLE
Add option to create a group of Rooms/People

### ISSUE THREAD

**Issue by hiwire03** [vector-im/element-web#16510]
Request to provide a feature to enable the user to create a group of Rooms/People say in folders.

**Comment by SimonBrandner** [comment]
@hiwire03, this is already kind-of possible using communities. They will be replaced by Spaces soon

**Comment by SimonBrandner** [comment]
Take a look at [#15930](https://github.com/vector-im/element-web/issues/15930)

**Comment by expipiplus1** [comment]
Although it's possible to group rooms in spaces, grouping contacts/people/DMs using spaces doesn't seem to be so.

**Comment by SimonBrandner** [comment]
@expipiplus1, Spaces are under heavy development, so if something isn't possible now, it might be in the future. As far as I know, adding people to private spaces is one of the planned things (or it's at least under consideration)

**Comment by expipiplus1** [comment]
Good to know, thanks!
