### ISSUE TITLE
make-icons.sh doesn't make the right icons

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16513]
It's unclear where the icons are coming from if not the script

**Comment by jryans** [comment]
Yes, I think this script should be removed, as it's outdated I believe... @dbkr knows how the icons have been produced most recently I believe...?

**Comment by aceArt-GmbH** [comment]
> Yes, I think this script should be removed, as it's outdated I believe... @dbkr knows how the icons have been produced most recently I believe...?

How are the icons generated currently, if not by make-icons.sh?
This is in regards to https://github.com/vector-im/element-web/issues/12020, where it would be nice if self-hosters could have a simple way to generate all used file types/sizes
