### ISSUE TITLE
reste password emails should not write failure report in web gui

### ISSUE THREAD

**Issue by emollusion** [vector-im/element-web#16522]
Hi!

When I reset password through the web gui I get a written error whenever the email address is not registered, and a success when the email address is registered, this feels like a bit vulnerable since with given time some one can find out a registered email address, or check for an address they have gained control over otherwise.

A failure to find email address for an account should result in a black hole response, and the same response when success.
Something like: A reset validation email has been sent to the registered address, please check your email and if you have received none please contact the HS admin.

**Comment by t3chguy** [comment]
This is not an Element issue as if Element was to hide it that wouldn't mean the Matrix API wasn't giving that result. I suggest opening an issue at https://github.com/matrix-org/matrix-doc
