### ISSUE TITLE
clicking on notifications in Nightly no longer foregrounds the app

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16526]

**Comment by jryans** [comment]
Hmm, I am not able to reproduce this so far with nightly on macOS 10.15.7. Clicking the desktop notification focuses the app and restores with window if needed.

@ara4n, can you check your notification settings in nightly and also the OS level notification settings for the app?

**Comment by ara4n** [comment]
i just spotted that other apps were also failing to foreground on clicking on notifs, so i rebooted, and it fixed

😔
