### ISSUE TITLE
Element Desktop doesn't show error when it can't get secrets from kde wallet

### ISSUE THREAD

**Issue by thibaultmol** [vector-im/element-web#16521]
### Description
I did a reinstall of Manjaro and copied the element folder in .config to my new install. But that obviously doesn't include the secrets which were stored in my kde wallet. The app just says it can't connect to the internet, but the real issue is that it doesn't have any credentials. BUT doesn't alert the user about that

### Steps to reproduce

I assume you'd be able to reproduce it like this:
1) Install Element desktop on linux
2) Make sure it's using the kde wallet
3) Login as usual. then close the app
4) Delete the wallet entries
5) start the app back up

But what happened in my case specifically:
1) Setup element desktop on Manjaro as you normally would, again using kde wallet
2) Backup the Element folder in the home's .config folder
3) Reinstall Manjaro
4) Restore the Element folder in the home's .config folder
5) Start element desktop and notice that it says it can't connect to the internet

It should give the user an error saying that it can't find it's config in the wallet, thus can't connect. Instead of saying that it's not able to connect to the internet.

### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: Manjaro, regular element-desktop package from arch repo
- **Version**: 1.7.20 

EDIT:
Sent debug logs to this issue, but haven't seen them show up yet. Not sure if that's supposed to happen

**Comment by jryans** [comment]
> Sent debug logs to this issue, but haven't seen them show up yet. Not sure if that's supposed to happen

We've received the logs, thanks. They are only visible to Element employees.

**Comment by jryans** [comment]
I believe this is the same issue as https://github.com/vector-im/element-web/issues/16343, so let's track it over there.
