### ISSUE TITLE
Rooms not hidden when selected a Space or Community

### ISSUE THREAD

**Issue by sim6** [vector-im/element-web#16547]
### Description

Some time ago I created version 4 rooms to invite people by email. These rooms are empty and not assigned to any community, but when I select a community they are not hidden.

### Steps to reproduce

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Firefox 78.7.0esr (64-bit)
- **OS**: Debian bullseye/sid
- **URL**: app.element.io

For the desktop app:

- **OS**: Debian bullseye/sid
- **Version**: Element version: 1.7.21 olm version: 3.2.1

**Comment by t3chguy** [comment]
Communities are no longer being developed, Spaces are hopefully not too far away which replace them outright.

**Comment by sim6** [comment]
@t3chguy Do you mean that you won't fix that?

**Comment by SimonBrandner** [comment]
@sim6, this won't get kind of fixed for Communities but it won't be a problem in Spaces since the code is completely new

**Comment by sim6** [comment]
Thanks for the clarification. It is a pity because Communities are in production and Spaces not yet.

**Comment by sim6** [comment]
@SimonBrandner sems that code is not completely new. Same behavior after switch to Spaces beta.

**Comment by t3chguy** [comment]
It sounds like the rooms are being treated as DMs with yourself which would make them show up in spaces & communities.
This is an unrelated but with something populating your `m.direct` event and would be resolved by the Canonical DMs project.

**Comment by t3chguy** [comment]
Closing as issue with user's account data
