### ISSUE TITLE
[Ui/ux] Allow people to hide the large profile picture call window during voice calls.

### ISSUE THREAD

**Issue by imthatsteve** [vector-im/element-web#16542]
This is just a suggestion for a ui change.

### Description

When you call someone on element there is a section of the chat history that gets covered up with a profile picture and the mute/hangup buttons. This is very annoying and its rather pointless since there is already a hangup button at the bottom of the screen so why not just move the mute button down there too and allow people to minimize the large profile picture and reclaim the wasted space. So we can see more than two messages at a time while in a call.

### Version information

- **Platform**: web (in-browser) or desktop?
I'm using the desktop app but this probably applies to the web browser as well.

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?
All of them.

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 
I'm on Linux but again this applies to every platform.

**Comment by SimonBrandner** [comment]
@imthatsteve, VoIP is currently under development and there are going to be some changes to the positions of the buttons (they'll be moved out of the composer). 

I am going to close this in favour of [#16229](https://github.com/vector-im/element-web/issues/16229) but feel free to re-open if you feel like that issue doesn't match what you expect
