### ISSUE TITLE
Automatically scrolled to bottom of thread when sending a message

### ISSUE THREAD

**Issue by nunoperalta** [vector-im/element-web#16548]
### Description

If send a message in a thread, while my scroll isn't at the bottom, I am now automatically pushed to the bottom.

This is the behavior of Whatsapp, Skype and most other chat systems I am aware of, and this is one of the main reasons I was looking at another chat system to chat with my work partners.
We specifically chose Riot/Element with a big bonus being that when we reply to something while we go through all the "unread/unreplied" messages, we aren't being constantly pushed to the bottom of the chat.

### Steps to reproduce

- Scroll up in a conversation thread.
- Type something in the text area and send.
- The expected is to stay where you are, but what happens is that you're now scrolled down.

This is a regression to me, as in previous versions, this did not happen.

### Version information

- **Browser**: Chrome
- **OS**: Windows 10
- **URL**: Private Server, v1.7.21

**Comment by t3chguy** [comment]
This is done by https://github.com/matrix-org/matrix-react-sdk/pull/5565
Maybe it should be a default-on option

**Comment by nunoperalta** [comment]
Thank you.

This "feature" has NEVER made sense to me.

Why would someone EVER want to completely ignore what the other person has to say, or be ignored?

--

We're working together, and we send many messages in a row to each other. We need stability on the scrolls, so that we can continue replying to each bit, without having to constantly scroll up.

This feature is completely non-sense to us.

Whatsapp, Skype, Slack and all others doing this, just makes people more delinquent, promoting "ignoring" to what other people say.
There is already a button at the bottom-right corner to scroll down, if I ever **want** to.

**Comment by SimonBrandner** [comment]
Hmm, I am sorry for the trouble with this. I can make this into a setting...

**Comment by nunoperalta** [comment]
Thank you @SimonBrandner  -- being a Setting would be a great workaround, yes. At least we have the option to stop the behavior.
Thank you for that. 👍

**Comment by nunoperalta** [comment]
Hey guys -- see https://github.com/vector-im/element-web/issues/16833
Thank you!
