### ISSUE TITLE
Cannot search rooms on Linux

### ISSUE THREAD

**Issue by jonasW3F** [vector-im/element-web#16545]
### Description

On Linux, it is not possible to search within rooms. It always tells 0 search results and suggests to "use desktop app to search encrypted messages". 

### Steps to reproduce

search in encrypted rooms with linux app.

### Version information

- **Platform**: Linux

For the desktop app:

- **OS**: Ubuntu, 
- **Version**: Element version: 1.7.21

**Comment by t3chguy** [comment]
Where did you install the package from?
Does the issue persist restarting the app completely?
Could you send logs?

**Comment by jonasW3F** [comment]
Restart won't work, I sent the logs and I believe that I installed it via the commands listed on the homepage of element.,

**Comment by t3chguy** [comment]
`2021-02-26T14:31:30.806Z I EventIndex: Error initializing the event index {"message":"Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: \"Invalid MAC\" } }))"}`

Looks like your EventIndex may have gotten corrupted 
You can delete it for it to be rebuilt from scratch - see https://github.com/vector-im/element-web/issues/14229#issuecomment-745276193

**Comment by jonasW3F** [comment]
I tried that, now it won't tell me to use the desktop version but still it does not yield any search results. I send the logs again after deleting the EventStore.

**Comment by t3chguy** [comment]
Check Settings > Security & Privacy > Message Search - it should show you the indexing progress. Once it is complete (or at least done with the room you want to search) then try it again

**Comment by jonasW3F** [comment]
it worked!
