### ISSUE TITLE
Reorganization of preferences

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16550]
Currently, there is a bunch of stuff in the preferences and I often have problems trying to find what I need. This is my suggestion of how the setting could be reorganized:

+ Room list
  + Show shortcuts to recently viewed rooms above the room list
+ Keyboard 
  + Use Ctrl + F to search
+ Composer
  + Use Ctrl + Enter to send a message
  + Automatically replace plain text Emoji
  + Enable Emoji suggestions while typing
  + Show stickers button
  + Send typing notifications
+ Time
  + Show timestamps in 12 hour format (e.g. 2:30pm)
  + Always show message timestamps
+ Code blocks
  + Enable automatic language detection for syntax highlighting
  + Expand code blocks by default
  + Show line numbers in code blocks
+ Images and videos
  + Autoplay GIFs and videos
  + Enable inline URL previews by default
  + Show previews/thumbnails for images
+ Stuff to hide (no idea how to  name this)
  + Show join/leave messages (invites/kicks/bans unaffected)
  + Show avatar changes
  + Show display name changes
  + Show a placeholder for removed messages
  + Show typing notifications
  + Show read receipts sent by other users
  + Show chat effects (animations when receiving e.g. confetti)
+ Timeline
  + Enable big emoji in chat
  + Jump to the bottom of the timeline when you send a message
  + Show avatars in user and room mentions
+ General
  + Enable Community Filter Panel
  + Prompt before sending invites to potentially invalid matrix IDs

Feel free to suggest any changes!

**Comment by t3chguy** [comment]
> Use Ctrl + Enter to send a message

> Send typing notifications


Feel like `Composer` category items

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/9060
