### ISSUE TITLE
unable to connect to home server on reboot!

### ISSUE THREAD

**Issue by MarvenX97** [vector-im/element-web#16556]
### Description

Hello,

i'm using element on my desktop , my problem is that after i login to my account and reboot my win10 i got the following error "Connectivity to the server lost" then after if i delete the cache and restart  the app it to turns into "unable to connect to home server"

Also another bug i can't search in rooms the error says that i need to use element-desktop while i have element-desktop and used it before to search in my room!

Hint: i think that CCLeaner may be doing some bad stuff  ?
### Steps to reproduce

- Login
- Reboot OS ( this will show the 'Connectivity to the server lost' error )
- Clear Cache ( this will show the 'unable to connect to home server' error )

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.7.21

**Comment by jryans** [comment]
Let's use #element-web / #synapse rooms for support issues with specific deployments like this.
