### ISSUE TITLE
Figma says we're supposed to have a line above the composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16553]
but we don't

**Comment by ara4n** [comment]
i think this is a bug in the figma designs - we deliberately removed the line at the time.

**Comment by turt2live** [comment]
hmm, alright. We noticed this while building a custom theme - maybe we just need to update the figma designs?

**Comment by yannicka** [comment]
Has a final decision been made on this matter?

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17362 as most of the discussions about this happened there
