### ISSUE TITLE
Enchance overall chat UI and expirience

### ISSUE THREAD

**Issue by wuast94** [vector-im/element-web#16561]
**Is your suggestion related to a problem? Please describe.**
no, and yes
**Describe the solution you'd like**
I want a chat expierence that is clear to me, i want to see fast who writes what and replays to what
**Describe alternatives you've considered**
1. Chat Bubbles (makes it visually clear who writes and where a message starts and stops) 
2. Left and Right allignment (makes it clear if its a message from me or other) 
3. Dont expand Reply ( just two or one line is enough, if i want read the full message i click on it and jump to this message)
4. this red highlighting is confusing too i must say but thats by desing if i was quoted, so i understand this

**Additional context**
![image](https://user-images.githubusercontent.com/16965460/109413658-d59c6900-79ae-11eb-9270-c50055266ed3.png)

i mean only looking at this short conversion, who is writing what and reply on what and where and wtf? 

I think we have a lot of potential to get this done better :) 

just as an example a whatsapp screenshot, its sooo much easier to see who was writing was and who reply on wich message
![image](https://user-images.githubusercontent.com/16965460/109413870-eef1e500-79af-11eb-85b8-db2497d2cbe1.png)

And this is no blame or so, i really love the work you make and i honor this :) but as i said, this could be improved so much i think :)

**Comment by SimonBrandner** [comment]
@wuast94, [#4635](https://github.com/vector-im/element-web/issues/4635) is an issue for chat bubbles and the reply rendering should be improved by [#3553](https://github.com/matrix-org/matrix-react-sdk/pull/3553). Do you feel like these issues satisfy your needs?

**Comment by SimonBrandner** [comment]
There is also an issue for highlighting but I can't find it right now

**Comment by wuast94** [comment]
ok i searched for bubbles in issues but dint find them, my fault :) 

and yes they seem to be exactly what i would change :) and as it looks it shouldnt take that long that we will see this upstream right? :)

**Comment by wuast94** [comment]
and feel free to close this as we have an discussion about this :)

**Comment by SimonBrandner** [comment]
> and as it looks it shouldnt take that long that we will see this upstream right?

Once we manage to merge the bubble they are definitely going to stay in [labs](https://github.com/vector-im/element-web/blob/develop/docs/labs.md) for some time until we figure out the details...
