### ISSUE TITLE
Enhance privacy of users 

### ISSUE THREAD

**Issue by githuberyt** [vector-im/element-web#16560]
Telegram channels support hiding users who subscribed in the channel for privacy concerns also they supported anonymous admin feature to hide the admin account of the group for more privacy you should take this into your concern it's very useful features specially for those who live under oppression regimes

**Comment by t3chguy** [comment]
Given the federated nature of Matrix, the best you could do is hide users and just have which servers are in the room.
Equally Matrix has peeking so those users could just peek the room without actually joining it.

In any case, it's an issue for https://github.com/matrix-org/matrix-doc and not here.
