### ISSUE TITLE
Apparent incorrect error message thrown when DMing to offline user

### ISSUE THREAD

**Issue by jqiriazi** [vector-im/element-web#16565]
### Description
I don't know if this is a Matrix issue or an Element issue.

I initiated a new DM with an offline user. I emailed them to confirm their account is active. DM room is not encrypted. When sending the first message a message was thrown saying "User is not online or does not exist. Message not sent." My understanding is, if the DM room is not encrypted, neither a user nor a device needs to be logged in for this to work.

### Steps to reproduce

- user being invited to a room is offline
- user being invited does not have an active session
- invite this user to an unencrypted DM room
- send a message

I expect the message to be sent successfully without that error being thrown. I assume the message will be available and readable by the invitee once coming online.

![image](https://user-images.githubusercontent.com/39391267/109425398-e8a63d80-799c-11eb-9540-c1ff31483cd9.png)

### Version information

Desktop app
- Element version: 1.7.21
- olm version: 3.2.1

OS
- Linux Mint 20.1 Ulyssa

**Comment by t3chguy** [comment]
That is an error from the IRC bridge not from Element.
The user you tried to contact is not online on the IRC side and IRC doesn't allow sending to offline users.
