### ISSUE TITLE
Jitsi integration with matrix username instead of display name

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16577]
### Description

We are getting the username instead of the display name sometimes,
After deleting the caches it went back to the display name for me...

### Steps to reproduce

don't know how to reproduce

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop? probably both, happened to many

In my case:

- **Browser**: Edge latest
- **OS**: Windows
- **URL**: element.aarenet.com Element version: v1.7.13

**Comment by lampholder** [comment]
I have seen this fairly reliably if you open a jitsi widget in a room, then open the room in a new tab - in the new tab you'll have the matrix ID instead of the display name.

**Comment by t3chguy** [comment]
This sounds like a race condition with not reliably having our own display name quite late into app launch
