### ISSUE TITLE
Susan getting UISI from me

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#16576]
### Description

Susan is getting UISI from me.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent   

### Version information

- **Platform**: desktop on MacOS

For the desktop app:

- **OS**: macOS
- **Version**:  1.7.22

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/2996
