### ISSUE TITLE
Greek omega letter renders as rectangle

### ISSUE THREAD

**Issue by alkisg** [vector-im/element-web#16575]
Hi, while visiting https://app.element.io with Ubuntu 20.04 and either firefox 86.0+build3-0ubuntu0.20.04.1 or google-chrome 88.0.4324.182-1, the Greek omega letter (ω) renders as a rectangle, making the UI look horrible.

By pressing F12 developer tools and deleting the Inter font from `<body>`, everything then shows up fine.

Including a screenshot. The problem shows up in words "Ενημέρωση" (Update) and "Δωμάτια" (Rooms) in the screenshot.
Please consider NOT using Inter font as the default.

![omega](https://user-images.githubusercontent.com/88025/109512124-6e64de80-7aac-11eb-93b9-80213574eb44.png)

**Comment by t3chguy** [comment]
You can change font in Settings > Appearance > Advanced
but yes I can confirm that Inter seems to have some issues with that character

**Comment by alkisg** [comment]
Thank you, I'm considering migrating my communities from IRC to Matrix; having a working UI for thousands of Greek users, without having to host a server or tell all of them to customize their fonts, would help in choosing Matrix.

**Comment by jryans** [comment]
Hmm, when looking at examples of Inter (e.g. at https://rsms.me/inter/), it certainly seems to contain a valid glyph for ω... Perhaps it's a bug in the version we're using, and we can upgrade our Inter font files to resolve this...?
