### ISSUE TITLE
Zoom in on image in Electron App

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16586]
**Is your suggestion related to a problem? Please describe.**
Can not Zoom in on image in Electron App and it is a difficult UI to download the image (decrypt then download)

**Describe the solution you'd like**
Zoom in on image in Electron App

**Describe alternatives you've considered**
open in browser button - which decrypts downloads and opens.

**Comment by SimonBrandner** [comment]
Will be fixed by [#5521](https://github.com/matrix-org/matrix-react-sdk/pull/5521)
