### ISSUE TITLE
Read receipts animation misbehaving

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16589]
![Peek 2021-03-03 11-03](https://user-images.githubusercontent.com/5547783/109789146-54441100-7c10-11eb-8898-2e4071f862d1.gif)

(each change in display is triggered by a click (4 clicks total))

I've also seen holes in RR lists, despite being on develop.element.io (so presumably with https://github.com/matrix-org/matrix-react-sdk/pull/5697 merged in):

![Screenshot from 2021-03-03 11-07-22](https://user-images.githubusercontent.com/5547783/109789468-a71dc880-7c10-11eb-8dac-440b73b4c2d1.png)

~Will send logs.~ Done

**Comment by babolivier** [comment]
fwiw I'm now seeing much more holes in RR lists, and clicking on them doesn't fix it anymore (which it did before)

**Comment by turt2live** [comment]
I think this is now manifesting as https://github.com/vector-im/element-web/issues/16646
