### ISSUE TITLE
Call keeps on ringing even though declined on mobile

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16580]
### Description

Call keeps on ringing even though declined on mobile 

### Steps to reproduce

Not sure if it happens every time

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by SimonBrandner** [comment]
@chagai95, have you ever seen this again, could you please share logs?

**Comment by chagai95** [comment]
Probably not happening anymore, I'll open a new ticket if I find something...
