### ISSUE TITLE
Desktop Community Filters missing room/people info

### ISSUE THREAD

**Issue by gummybuns** [vector-im/element-web#16598]
### Description

On the Element for Mac Desktop Application, I am seeing that clicking on a specific community on the left sidebar is failing to properly update the people / rooms properly to reflect what is expected. It is instead showing no rooms or people.

I am not seeing the same behavior when using the web client.

### Steps to reproduce

1. Open Desktop Application.
2. Specify a community
3. Error: The rooms/people are all missing
4. Bonus Bug: Manually choosing a filter by Activity / A-Z pulls in the room/people data

#### Expected (Web Version)
![Kapture 2021-03-03 at 21 29 34](https://user-images.githubusercontent.com/47437711/109901834-ad8b5f00-7c67-11eb-965c-57fbba05f838.gif)

#### Actual (Desktop Version)
![Kapture 2021-03-03 at 21 27 20](https://user-images.githubusercontent.com/47437711/109901810-a5332400-7c67-11eb-9eb4-5f5713934170.gif)

Ideally the Desktop Version replicates the same behavior as the web version 

Describe how what happens differs from what you expected.

### Version information

- **Platform**: desktop
- **OS**: macOS BigSur 11.2.1
- **Version**: 1.7.22

**Comment by SimonBrandner** [comment]
@gummybuns, communities will be soon replaced by Spaces (communities but much better) so I wouldn't worry about this :)

**Comment by SimonBrandner** [comment]
Spaces are now in beta
