### ISSUE TITLE
It is not possible to disable spell-checking on desktop

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16590]
If no spell-checker languages are set, the spell-checker should be disabled but that doesn't seem to be the case. [This line](https://github.com/vector-im/element-desktop/blob/b8adc66898e59ad093528f22626cc7dd9b5d9722/src/electron-main.js#L396) doesn't seem to do anything for me. I remember it working before

**Comment by SimonBrandner** [comment]
Ok, we're on Electron `v11.2.3`, the [docs](https://github.com/electron/electron/blob/v11.2.3/docs/api/session.md) say that there isn't a way to do this, but it seems to be a part of newer Electron versions

**Comment by SimonBrandner** [comment]
On Electron v12.0.0 there is [`setSpellCheckerEnabled(enable)`](https://github.com/electron/electron/blob/v12.0.0/docs/api/session.md#sessetspellcheckerenabledenable) which seems to work

**Comment by jryans** [comment]
Sounds like we can potentially set an empty array to disable on 11.x.
