### ISSUE TITLE
Please add some strikethrough syntax support

### ISSUE THREAD

**Issue by shmerl** [vector-im/element-web#16597]
There is no good way currently to post a strikethrough text. May be adding something like

```
~~foo~~
```
To get ~~foo~~ would be good (it's Github syntax).

**Comment by t3chguy** [comment]
Element uses CommonMark: https://talk.commonmark.org/t/feature-request-strikethrough-text/220
https://github.com/vector-im/element-web/issues/5940 is the issue requesting the switch to Github Markdown.

**Comment by shmerl** [comment]
Should I open a request to switch to Github markdown or there isn't a point and we can just wait until it's added to CommonMark as per that discussion (here is the [original one](https://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820/51), the above one is a dup).

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/5940 which I linked above is the issue requesting to switch to Github markdown.
