### ISSUE TITLE
#python-gsoc:matrix.python-gsoc.org is not accessible at this time.

### ISSUE THREAD

**Issue by ayushksingh28** [vector-im/element-web#16596]
I am not being able to join the python gsoc matrix room. Help me with this issue.
![Capture](https://user-images.githubusercontent.com/79689279/109845822-8d619d00-7c73-11eb-9e7f-a4848882a727.PNG)

**Comment by t3chguy** [comment]
`matrix.python-gsoc.org` is a broken Matrix server as per https://federationtester.matrix.org/#matrix.python-gsoc.org

You may wish to contact them in an alternative manner and let them know.
This issue is unrelated to Element however.
