### ISSUE TITLE
left panel not showing message previews on today's nightly, but option still checked

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#16607]
On restarting into today's nightly, my left panel is no longer showing message previews, but the box still appears checked. The panel also went back to icon-only mode.

**Comment by t3chguy** [comment]
I just updated and mine continued to work fine

**Comment by jryans** [comment]
@dbkr Is this still messed up, or did you workaround it...?

**Comment by SimonBrandner** [comment]
@dbkr, a friendly ping

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
