### ISSUE TITLE
[ubuntu 20.10] Element always writing to disk even in background

### ISSUE THREAD

**Issue by hakkikaancaliskan** [vector-im/element-web#16602]
### Description

Element process always writing to disk (even in background). Total disk write grows up with how much it waits in background.

### Steps to reproduce

Just run element and put it to background or let it start in background with login.
Monitor disk write rate and total disk write.

Describe how what happens differs from what you expected.
It shouldn't write to disk all the time. It never stops. Process should go into sleep mode while in background

Log: sent

(selected process making all the write io) (until i put ss here it growed up to 200mb)
![image](https://user-images.githubusercontent.com/17825767/110000048-edb01780-7d23-11eb-9645-158283ac0ad0.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 20.10
- **Version**: Element version: 1.7.22
                      olm version: 3.2.1

**Comment by SimonBrandner** [comment]
I can reproduce this on Debian 

> Process should go into sleep mode while in background

I think it is necessary to have the process running for notifications.

**Comment by t3chguy** [comment]
Can you compare your findings to other Electron apps like Discord or Slack?

**Comment by hakkikaancaliskan** [comment]
> I _think_ it is necessary to have the process running for notifications.

@SimonBrandner If so, total io is too high for just checking notifications.

Telegram is running for soo long time and here is the io:
![image](https://user-images.githubusercontent.com/17825767/110001985-f99cd900-7d25-11eb-96b9-4bd16b73e15b.png)

**Comment by hakkikaancaliskan** [comment]
And tutanota also running for so long time, here it is:
![image](https://user-images.githubusercontent.com/17825767/110002074-11745d00-7d26-11eb-8582-c318418eeacf.png)

**Comment by hakkikaancaliskan** [comment]
> Can you compare your findings to other Electron apps like Discord or Slack?

I'm not using them, sorry.

**Comment by SimonBrandner** [comment]
> Can you compare your findings to other Electron apps like Discord or Slack?

Discrod seems to have no write at all

**Comment by SimonBrandner** [comment]
It's going up, slowly. I'll wait a bit and compare then

**Comment by SimonBrandner** [comment]
This is what it looks like after I did nothing for a few minutes:
![Screenshot_20210304_183708](https://user-images.githubusercontent.com/25768714/110005391-b5570c00-7d18-11eb-87d9-8d5d07d46e13.png)

**Comment by hakkikaancaliskan** [comment]
I've reinstalled ubuntu to nvme drive from scratch and disk write seems normal to me, maybe this is something with disk?
![image](https://user-images.githubusercontent.com/17825767/110530074-0efd7300-812b-11eb-9e4e-5d7be83e9c72.png)

**Comment by ara4n** [comment]
The obvious things which cause Element Desktop to write lots to disk is:
 * Seshat, the encrypted indexer, goes and spiders all your E2EE rooms and builds a clientside index. This can take ~24h on a large account like mine, so if you measure in that timeframe it'll be busy hammering disk.
 * The sync accumulator goes and persists a copy of your current sync data to disk every few minutes.  On a big account this could be ~100MB.
  
It does this whether the app is in the bg or not.

**Comment by hakkikaancaliskan** [comment]
@ara4n got it thanks! Closing this issue.

(For context, i got 5 rooms(2 of them encrypted))
