### ISSUE TITLE
Untrusted icon is illegible on dark theme on dialogs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16622]
<img width="194" alt="Screenshot 2021-03-08 at 01 01 52" src="https://user-images.githubusercontent.com/1294269/110261936-f154d000-7fa9-11eb-8c2a-360130a0db60.png">

**Comment by niquewoodhouse** [comment]
Does anyone know where you actually see this icon?  The issue says dialogs, but which ones?

![image](https://user-images.githubusercontent.com/1587166/118000228-8aeb8580-b33d-11eb-8482-aa6fcebfc934.png)
