### ISSUE TITLE
Leaving a space doesn't make it disappear from the LLP

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16629]
I've left a space I've created but it's still on my LLP and still shows notification counters etc - refreshing fixed it

**Comment by SimonBrandner** [comment]
Try restarting the client

**Comment by SimonBrandner** [comment]
Closing as I can't reproduce this anymore. Looks like it was fixed by [#5775](https://github.com/matrix-org/matrix-react-sdk/pull/5775)

**Comment by t3chguy** [comment]
Weird, I could still repro it and fixed it in https://github.com/matrix-org/matrix-react-sdk/pull/5789/commits/796bfd851de39878ae8d082a9a3eb72f3d53cd1a :P

**Comment by SimonBrandner** [comment]
You're right, you fixed it by that commit. /me is an idiot and doesn't function very well this week :D
