### ISSUE TITLE
Support MSC1763 configurable retention periods

### ISSUE THREAD

**Issue by nostraboonus** [vector-im/element-web#16625]
### Description

We configured retention on several rooms. After the purge job removed the events on server side, the expired events are still visible on client.

### Steps to reproduce

- configure retention job on Synapse Server
- write message in room
- waiting till retention job removed the message
- message in room still appears in current session
- Closing or reloading tab has no effect on this issue 
- Only *logout* from current session, deletes the messages
- After *login* on element-web or restart of element-desktop the expired messages disappeared

It is expected that expired messages on connected devices will be deleted immediately or always when the tab/client is opened. 

### Version information

Server:
- matrix-synapse: 1.28.0

For the web app:

- **Browser**: Chrome 89.0.4389.82 (64-Bit), Firefox 78.8.0esr (64-Bit)
- **OS**: Debian Buster
- **Version**: 1.7.22

For the desktop app:

- **OS**: Debian Buster
- **Version**: 1.7.22

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-doc/blob/matthew/msc1763/proposals/1763-configurable-retention-periods.md

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/3800
