### ISSUE TITLE
[Spaces] Iterate personal collection space creation flow use case

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16628]
E 1D

**Comment by niquewoodhouse** [comment]
[Design link](https://www.figma.com/file/m7L63aGPW7iHnIYStfdxCe/Spaces?node-id=3487%3A0)

Previous prototype (that kind of explains what we're thinking):
![private-space-existing-rooms-1](https://user-images.githubusercontent.com/1587166/116069560-6cba3000-a683-11eb-928e-1bd6b6e26915.gif)
