### ISSUE TITLE
Encrypted Search not working on Desktop

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16636]
### Description

Not searching encrypted messages from desktop app

### Steps to reproduce

don't know

here is a screen cap:
https://nextcloud.chagai.website/s/LPSHm5scWpsCM4y

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **Version**: 1.7.13

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/14229 https://github.com/vector-im/element-web/issues/15715

Your Seshat db is corrupted

`2021-03-08T15:23:02.669Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseError(SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some(\"file is not a database\")))"}`

Try https://github.com/vector-im/element-web/issues/14229#issuecomment-652980655

**Comment by chagai95** [comment]
I deleted the whole folder in Local and the folder in Roaming then I downloaded the install file and installed it again, still same issue.

**Comment by chagai95** [comment]
sent logs again

**Comment by jryans** [comment]
Unfortunately, the second log says the same thing:

```
2021-03-08T17:19:09.498Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseError(SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some(\"file is not a database\")))"}
```

@chagai95 Do you have some unusual permissions on your user data directory by chance that might limit writing such files...?

**Comment by chagai95** [comment]
```
drwxr-xr-x 1 cfriedlander 1049089   0 Mar  8 16:26  cfriedlander/

```

**Comment by logic** [comment]
FWIW: I tried using Element on Windows 10 for the first time over the last week or two, and promptly ran into this issue. Deleting the EventStore folder kicked seshat indexing off again, and it appears to be storing everything just fine now. I apologize, I don't have logs from prior to removing the EventStore folder, but figured I might as well mention it.

I'll also note that power was lost several times during the setup of this machine, so if seshat indexing was occurring at the time, perhaps it handled that poorly?

(I typically run Element on Linux via flatpak, and have never had this issue there.)

**Comment by domingoso** [comment]
We've just begun trying Element desktop with my team at work and we're all running into this issue. All of us are using Windows 10. Just sent logs from my machine.

**Comment by t3chguy** [comment]
New version should be released today which has a Reset button to fix the corruption, or you can try the workaround linked above.

**Comment by jryans** [comment]
I think this is effectively the same as https://github.com/vector-im/element-web/issues/16568, which already in our queue to investigate in fix. There does seem to be something wrong specifically on Windows.

I think I'll close this one, since the other is queued up already.
