### ISSUE TITLE
Changing the theme to light theme apparently breaks the layout (CSS) see screenshot 

### ISSUE THREAD

**Issue by FlorianJSa** [vector-im/element-web#16639]
### Description

As soon as you change the theme to the light theme, the theme is broken

### Steps to reproduce
- Change the Theme from dark to light 

The Desing is broken 

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**:  Manjaro 
- **Version**: 
Version von Element: 1.7.21
Version von olm: 3.2.1

![Bildschirmfoto vom 2021-03-08 19-08-39](https://user-images.githubusercontent.com/54689374/110364213-c8811900-8043-11eb-9e17-02bccc0f6b9b.png)

**Comment by t3chguy** [comment]
Please fill the issue template.

**Comment by jryans** [comment]
Hmm, does it happen every time...? I've never seen this before...

**Comment by FlorianJSa** [comment]
Hello thanks for your reply, i think you can close the issue it seems to be fixed.

**Comment by SimonBrandner** [comment]
Closing
