### ISSUE TITLE
Cannot open 1:1 video call

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#16633]
Description

Just attempted for the first time to start a 1:1 video call. The call rang but neither user could see the other.

Furthermore, a "Too many requests" message popped up for me.
Steps to reproduce

1.    Use an existing DM with other user.
2.    Click on the camera.
3.    Hear ringing tone.
4.    Accept request for use of video, microphone.
5.    Call appears to start, but I cannot see other user.
6.    A message "Too many requests" pops up in the MD.

Version information

    Platform: web (in-browser)

For the web app:

    Browser: Firefox 86.0 (64-bit)
    OS: Ubuntu
    URL: app.element.io, using matrix.org

**Comment by SimonBrandner** [comment]
Hmm, do we have a repro case here? There are at least two reports of this though I don't remember ever seeing this myself

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
