### ISSUE TITLE
Add a button to start a nightly build on demand

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16637]
for when developers are impatient and can't wait to test their changes in Desktop. Likely rare occurrence, but would be useful to cover "I want to test this on desktop but don't want to burden a person with doing the build". 

Example case: I'd love to test the new message states on all platforms to embed myself in the user experience, but I either have to wait until tomorrow or ask for a one-off build to be started (which feels like too much of an ask given the non-criticalness of the feature).

**Comment by t3chguy** [comment]
We have this now - https://github.com/vector-im/element-desktop/actions/workflows/build_and_deploy.yaml
