### ISSUE TITLE
Some sort of definitive confirmation that the version is correct

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16635]
We report the results of `/version` in rageshakes and in the app, but it would be good to have the version in the JS somewhere where we can report that 'yes, this is definitely v1.x because the code also says so. This would help identify cases where the `/version` file isn't cached, but the rest of the app is loading from cache (HTML, CSS, JS, etc) - if the JS is at least different then there's hope.

**Comment by t3chguy** [comment]
We bake the version in nowadays
