### ISSUE TITLE
Edge: suddenly cannot scroll in timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16643]
not sure what caused this - affects all rooms.

**Comment by jryans** [comment]
@turt2live Has it ever happened again?

**Comment by turt2live** [comment]
Several times. It's a weekly thing.

**Comment by MadLittleMods** [comment]
Maybe related to https://github.com/vector-im/element-web/issues/17593 ?

**Comment by turt2live** [comment]
I think it was a bad Edge version - it hasn't happened since ~May
