### ISSUE TITLE
Read receipts don't come down to the latest message in the room

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16646]
![Peek 2021-03-09 10-48](https://user-images.githubusercontent.com/5547783/110452141-2d308800-80c5-11eb-92c9-db868d89336a.gif)

As you can see, the message is read (send status disappears) but the RR doesn't come down - it only does when I switch rooms (I switched to my DM with @benparsons and back hence why his RR briefly appears at the end). I control both accounts involved in the DM I'm doing tests in so can confirm the message isn't read while switching rooms.

Using develop.element.io with Firefox 85.0, and have sent logs.

**Comment by turt2live** [comment]
@babolivier was the message edited?

**Comment by babolivier** [comment]
No

**Comment by turt2live** [comment]
I need a bunch of other information then, as I cannot reproduce this.

* Who was the sender of the message? (you or someone else?)
* What operating system are you using?
* Do you have reduced motion enabled in your OS or browser?

**Comment by turt2live** [comment]
is that a fork of firefox or regular off-the-shelf firefox?

**Comment by babolivier** [comment]
> is that a fork of firefox or regular off-the-shelf firefox?

Regular off-the-shelf (`pacman -S firefox`) firefox

> also which desktop environment are you using?

Gnome shell

**Comment by turt2live** [comment]
alright, I'm suspecting this has something to do with your OS rather than Element/Firefox

**Comment by babolivier** [comment]
Hmm, any idea how to debug this? It's a pretty standard setup (without much customisation) so I'm a bit surprised to hear that.

**Comment by turt2live** [comment]
Honestly not sure. I can't get an arch VM going to test myself, but all other testing points to it being a problem with your setup specifically :(

If you have another device to test with, I'd try that and see what happens.

**Comment by turt2live** [comment]
@babolivier has this been better on updated versions of develop?

**Comment by babolivier** [comment]
Not as far as I can tell.

**Comment by turt2live** [comment]
ugh, this is going to be not very fun to diagnose

**Comment by shmerl** [comment]
I have the same issue.

Debian Linux, Firefox 87.0.

I wonder how can it be OS related? It should be purely browser driven issue? Is it working OK for Firefox users on Windows let's say?

**Comment by turt2live** [comment]
It's working fine for me in Firefox on Linux and Windows, which is part of the problem.

**Comment by shmerl** [comment]
When looking in console, I see some messages like:

```
Error: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/sync...
```

**Comment by shmerl** [comment]
It seems to be working better with tracking protection turned off. I'll keep monitoring it.

**Comment by turt2live** [comment]
is anyone still seeing this in recent versions of develop?

**Comment by babolivier** [comment]
Yeah I can still see it on develop.element.io

**Comment by turt2live** [comment]
ugh, that's annoying. Any chance of trying other browsers/desktop environments to see if it fixes itself? or trying the desktop app?

**Comment by babolivier** [comment]
Sure, I'll give that a try next week.

**Comment by babolivier** [comment]
I've had a try in Chrome/Chromium (still on Gnome because I've only got this DE set up), I couldn't reproduce this specific issue and could see the animation when a RR goes down (which I don't see on Firefox), but I could also see RRs stacking on top of each other and holes (![image](https://user-images.githubusercontent.com/5547783/112861139-d2cb8b80-90b4-11eb-9758-314cdc37e183.png))

**Comment by babolivier** [comment]
I've just had a try in Firefox after manually disabling tracking protection and it seems to now match what I'm seeing in Chrome.

**Comment by turt2live** [comment]
that's at least progress - so disabling tracking protection (either by using chrome or within firefox) is at least giving you animations? If so, the holes might be a different animation issue or the media repo being slow - if you hover hover a where an avatar would be, do you get a cursor change and tooltip of a user ID? If not, boo. If yes, it's just the media repo at that point.

**Comment by babolivier** [comment]
> so disabling tracking protection (either by using chrome or within firefox) is at least giving you animations?

Yes looks like it.

> if you hover hover a where an avatar would be, do you get a cursor change and tooltip of a user ID?

Nope :/

**Comment by turt2live** [comment]
The next step on this is https://github.com/vector-im/element-web/issues/16554 ftr

**Comment by babolivier** [comment]
Can confirm that https://github.com/matrix-org/matrix-react-sdk/pull/5836 fixes all issues with read receipts from my pov :+1:
