### ISSUE TITLE
View source dialog sometimes runs room ID into event ID

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16653]
![](https://i.imgur.com/LoxMIRi.png)

**Comment by 2580ayush2580** [comment]
I am working on this.

**Comment by 2580ayush2580** [comment]
I think already fixed in this [PR](https://github.com/matrix-org/matrix-react-sdk/pull/5713/)

**Comment by turt2live** [comment]
my test was with a build using that PR, so I'm not sure it is fixed

**Comment by DantrazTrev** [comment]
@2580ayush2580 Are you still working on this ?

**Comment by 2580ayush2580** [comment]
no
