### ISSUE TITLE
Writing custom widgets

### ISSUE THREAD

**Issue by martinchristen** [vector-im/element-web#16654]
I would like to create my own widget. It would be great to have some documentation about the widget api ( https://scalar.vector.im/api/widgets/ ).

So it would be great to have some info on this.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-widget-api
https://github.com/matrix-org/matrix-doc/pulls?q=is%3Apr+is%3Aopen+widget

**Comment by jryans** [comment]
`matrix-doc` seems like the best place to track this.
