### ISSUE TITLE
Audio failure on 1:1 video call when dialing at the same time (glare)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16656]
- Ryan called Tom
- Tom called Ryan
- Ryan answered Tom's call
- Ryan could hear Tom but tom could not hear Ryan

We repeated this twice.

Letting Ryan dial without Tom dialing and Tom answering worked fine.

**Comment by SimonBrandner** [comment]
I am pretty sure we fixed this since, shout if you disagree
