### ISSUE TITLE
New room pills are off-spec

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16660]
Autocompleting a room should result in a plaintext version of the alias in the message `body`, not the room name.

**Comment by turt2live** [comment]
Declaring this a release blocker because it breaks some bots.

**Comment by SimonBrandner** [comment]
I've made a PR to revert this. But I am not exactly happy about it... :( Any reason the spec defines pills like this? It seemed to have been confusing to some users...

**Comment by turt2live** [comment]
They're able to look however visually - it's just the plaintext body which is meant to stay as a room alias. It's largely to support non-rich clients.

**Comment by SimonBrandner** [comment]
Ok, I see, thanks for the explanation! I'll try to figure out a way how to do this later
