### ISSUE TITLE
Create a message-edit menu choice in the context menu

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16663]
The message-edit function is currently invoked with a button to the extreme right of the message.  This is inefficient even if the screen is not opened wide (which makes the needed gesture even less efficient).  Can we put the message-edit function on the context menu?  There is supposedly a way to do this already, but I've not been able to do it.

**Comment by SimonBrandner** [comment]
@Shaping, not sure I understand. Are you talking about a [right-click context menu](https://github.com/vector-im/element-web/issues/16480)?

**Comment by Shaping** [comment]
Yes, place the edit-menu on the context menu.

**Comment by SimonBrandner** [comment]
@Shaping, to clear things up for me: You want to **add** a **right-click context menu** (as described [here](https://github.com/vector-im/element-web/issues/16480)), and this context menu should **include** an **edit button**.

So something like this?

![image](https://user-images.githubusercontent.com/25768714/102108177-e408c900-3e32-11eb-8350-8d512bc1ecce.gif)

**Comment by jryans** [comment]
It feels like the original reporter has disappeared... @Shaping, please see the questions above.

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.
