### ISSUE TITLE
The new uploaded file tiles should be clickable/have a download button

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16668]
![Screenshot_20210311_191857](https://user-images.githubusercontent.com/25768714/110835082-a33c1700-829e-11eb-95a6-d2f5fc60ae46.png)

The new uploaded file tiles are great, but I think they should be clickable or have a download button, and the hyperlink should be removed. The hyperlink feels quite outdated, coming from other apps.

**Comment by nadonomy** [comment]
@gaelledel useful issue for the file download stylisation you're looking at!

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17943
