### ISSUE TITLE
Message demarcation via colored background, as in Telegram

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16661]
Can we have Element clearly delineate individual messages as, say, Telegram, does, without needing to hover over the messages.  The highlight on hover-over is good, but  I find that coloring the message background with a thin gap between each message background very useful when scanning and parsing messages with the eye.

**Comment by jryans** [comment]
I believe you are basically asking for chat bubbles as in https://github.com/vector-im/element-web/issues/4635...? Is that correct?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author. _Feel free_ to reopen or ping me if #4635 isn't what you want.
