### ISSUE TITLE
Make space room-creation ("What projects are you working on?") screen more pleasant

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16674]
#### Is your suggestion related to a problem? Please describe.
When creating a private room, I encounter the "What projects are you working on?" screen, which has 2 rooms prefilled to be created on space finalization, these have to be manually cleared before the space is "finalized".

While an indefinite adding list would be nice too (with a `+` on the bottom of the room name entries, so it can be more than 3), for a user like me, who'd wanna quickly make an empty "folder" of a space to put rooms into, this step's least-resistance could create random empty rooms without noticing it at first, which might be annoying.

#### Describe the solution you'd like
Maybe reduce the prefilled amount of rooms to 1, "General", ~~and then add `x` buttons on the ends of the inputs to quickly clear them, this changes the button to a "skip for now".~~

Edit: It does "skip for now" when you manually clear the rooms, that's good enough.

~~Also make the `Room name` more grey, this makes it more easily identifiable at a glance that those inputs are empty.~~

Edit: Made into a sub-issue: #17243

#### Describe alternatives
- In the `#element-dev` room, when i brought this up, it was said that a "skip" button was explicitly not done because "spaces with 0 rooms provide 0 value", while i disagree with this, i sorta understand this from one perspective, but for my self-management, i'd rather not have any rooms pre-filled, and just allow me to directly "finalize" my private space so i can work on it "personally", without a suggested workflow.
- Another alternative would be to provide a "Add Existing Rooms Instead" button, which opens up rooms to add to the newly created private space, this'd help with users easily setting it up, and would be (in my opinion) a suitable alternative to adding a "skip" button.

**Comment by ShadowJonathan** [comment]
#16627 possibly related

**Comment by ShadowJonathan** [comment]
An alternative would be to provide a "Add Existing Rooms Instead" button, which opens up rooms to add to the newly created private space, this'd help with users easily setting it up, and would be (in my opinion) a suitable alternative to adding a "skip" button.

**Comment by jaywink** [comment]
IMHO it would be nice if a "skip this now" would just be visible without needing to clear any rooms. Especially if one is creating many spaces for an existing community, one doesn't want to add any new rooms but just wants to add the spaces, to be able to add existing rooms.

**Comment by SimonBrandner** [comment]
I think @niquewoodhouse had a mockup that suggested having a completely different screen for private spaces that would instead let you select already existing rooms

**Comment by t3chguy** [comment]
Was this specific to "Just Me" spaces? if so then they now have the add existing rooms as part of their flow

**Comment by t3chguy** [comment]
> Also make the Room name more grey, this makes it more easily identifiable at a glance that those inputs are empty.

That would be an app-wide style change for our `Field` component so unlikely to be tackled as part of an issue about Space creation

**Comment by ShadowJonathan** [comment]
> That would be an app-wide style change for our `Field` component so unlikely to be tackled as part of an issue about Space creation

Should i make an issue for that? Other than that, only my feedback for "finalization" of adding rooms stands.

**Comment by t3chguy** [comment]
Yes, please
