### ISSUE TITLE
Allow scroll-wheel zooming of clicked images

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16676]
A clicked image is zoomed to a larger fixed size but is not usually big/zoomed enough to read if it contains a lot of fine print.  Can we make all clicked images zoomable by default, as in Telegram, so that one need not save down the image, and then open it with a separate image-viewing app to see the details?

**Comment by SimonBrandner** [comment]
@Shaping, this will be fixed by [#5521](https://github.com/matrix-org/matrix-react-sdk/pull/5521)
