### ISSUE TITLE
Hiding Widgets isn't persistent in a room. Widgets are hidden until you go to another room

### ISSUE THREAD

**Issue by rtanglao** [vector-im/element-web#16672]
Filing this issue on behalf of enuan.com, host:enuan

### Description

Clicking  on "Hide Widget" hides the widgets but when you select another room and then go back to the room where you hide the widgets, the widgets are shown again.

### Steps to reproduce

1. Enter  a room let's call it room 1
2. Click on Hide Widgets and the widgets are hidden
3. Enter room 2
4. Go back to room 1

Describe how what happens differs from what you expected.

Expected result is that widgets are still hidden in Room 1

Actual Result is that the widgets are displayed again.

Logs being sent: yes

### Version information

Desktop Element app

For the desktop app:

- **OS**: Windows10
-  Element App 1.7.22

**Comment by toger5** [comment]
Should this be implemented like this? Or is it good that the widgets are visible whenever you open a room to raise awareness that the pinned widgets exist?
In my opinion it is good to store the widget hidden state. Users who have used the button know that the existence of this button means that there are pinned widgets in the room.
