### ISSUE TITLE
Typing notifications are sent when editing a message

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16675]
Currently Element web sends typing notifications when editing a message, which I find quite misleading as I then expect the user who's typing to be sending a new message soon. When I'm having a convo, especially a work-related one, and I see the other user typing, I tend to expect that this user will send a new message in the context of that convo and thus wait for this new message before getting back to my work, since sometimes it can be a "oh but wait" kind of message that directly impacts what I'm working on. It's then quite annoying to realise after a few seconds that the other user was just e.g. fixing a typo in one of their previous message.

**Comment by turt2live** [comment]
fwiw this was added intentionally, though things like https://github.com/matrix-org/matrix-doc/pull/3038 might help improve the messaging of the notification ("TravisR is editing a message", etc)

**Comment by ShadowJonathan** [comment]
Opposite of https://github.com/vector-im/element-web/issues/10188?

**Comment by turt2live** [comment]
Closing in favour of more relevant typing notifications: https://github.com/vector-im/element-web/issues/10188
