### ISSUE TITLE
Remove ':' on mention inserts

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16682]
(This is a request for Element's UX, not only for element-web)

This is related to the general UX of element, which has stemmed from IRC, that i think doesn't apply anymore in a "modern messenger" context.

In any other messager, a mention just becomes a "pill"/`@`, with nothing after it, I think Element should shed this and adopt that design.

I can imagine an extra `:` would cause alienation and frustration among new users, as seeing it suddenly pop up (even in the middle of a sentence) would be a bit off-putting compared to their experiences on other messagers.

So my call is; remove it from Element, or put it behind a feature-flag in settings and make it default "off".

**Comment by aaronraimist** [comment]
https://github.com/vector-im/element-web/issues/15794 seems like a better solution to me. I like the colon when I am directing a message towards someone.

**Comment by ShadowJonathan** [comment]
That issue is focusing on the bug of the colon appearing in the middle of the composer, but I'm asking for it to be removed entirely from Element (or at least as a default), so I respectfully disagree.

**Comment by SimonBrandner** [comment]
Personally, I'd completely remove any character after the pill because I don't think there is a good and easy way to detect where it should be and where it shouldn't be...

**Comment by ara4n** [comment]
the intended behaviour is that colon is suffixed if you tab-complete at the beginning of a message, but not if you tab complete in the middle of a message. this is indeed modelled after xchat and other IRC clients.  I think the colon helper when you're directing a message to someone by mentioning them at the beginning of a sentence is a really nice feature, perosnally - so #15794 is very much a bug, but this is not, imo.

**Comment by ShadowJonathan** [comment]
@ara4n My point is is that this is not consistent with modern messagers, and that Element is already not an IRC equivalent anymore, but is trying to be something else, and so I think this behaviour is inconsistent (and thus, unfriendly) in comparison to modern messengers.

My point *also* is to make this *optional*, right now it is compulsory with no way of turning it off, so please re-open this issue, as I do not see this solved, I'll change the title to "make colon inserts on mention optional".

**Comment by Yajo** [comment]
FWIW nobody on my team used IRC heavily. Everybody used other chat systems. Everybody finds this annoying. I guess it depends on your background... so maybe making it optional would be the best. 🤷🏼‍♂️

**Comment by SimonBrandner** [comment]
I will reopen this as I _believe_ not everything was considered when this was closed, as the above comments have explained.

Though this feature is great for IRC users, many users are coming from different services. This behaviour might be _at least_ a bit surprising to them. I think FTUE should be a big part of the decision here and that is regardless of what service the user is coming from. 

Here is a list of apps that do not do this:
+ Discord
+ Viber
+ What's App
+ Slack
+ Gitter
+ Messanger

_Please correct me if I don't understand something here._

**Comment by DantrazTrev** [comment]
A better redesign for the @ mention pill could really help distinguish it from the Room reference 

![image](https://user-images.githubusercontent.com/43457420/118709476-a291a500-b83a-11eb-8656-de1f41510689.png)

I guess there's an issue already for that. But the only distinguishable point was the trailing : which isn't there when typing mid of the message anymore

Maybe we could have the two combined for the trailing : for the beginning and something different for a mid message like an @ indicator?

**Comment by SimonBrandner** [comment]
@DantrazTrev, this is something for another issue. The `:` wasn't supposed to be there in the middle of the message. If you'd like the room/user/space pills to look differently, please create a new issue

**Comment by DantrazTrev** [comment]
> @DantrazTrev, this is something for another issue. The `:` wasn't supposed to be there in the middle of the message. If you'd like the room/user/space pills to look differently, please create a new issue

Sure will do that. I think it relates a bit to the current issue

**Comment by t3chguy** [comment]
Not really given that whether or not the app pre-inserts a `:` the user could remove it and relying on that for distinction thus is brittle

**Comment by DantrazTrev** [comment]
> Not really given that whether or not the app pre-inserts a `:` the user could remove it and relying on that for distinction thus is brittle

So I guess we need to completely redesign the mention pills.

**Comment by robsonsobral** [comment]
I'm trying to replace the `:`  by `, `, but it's impossible! The mention is removed!

Thank you.
