### ISSUE TITLE
Bring back moving rooms between Rooms and People Section

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16681]
**Is your suggestion related to a problem? Please describe.**
The Telegram and WhatsApp bridge get this wrong all the time.
Also starting an unencrypted chat with someone where the default is encrypted 1:1 chats results in the room being in Rooms instead of People.

**Describe the solution you'd like**
Bring back the Direct Chat button (call it "move to People") that existed for example in version [1.6.5](https://riots.im/1.6.5/) 

![image](https://user-images.githubusercontent.com/31655082/111069764-debd2800-84ce-11eb-9213-d4f2c948b7ab.png)

**Describe alternatives you've considered**
Add it as a lab feature.
Fix these bridges problems and allow creating an unencrypted 1:1 chat. 

**Additional context**
Having to switch between Rooms and People every single time is super annoying

**Comment by SimonBrandner** [comment]
@chagai95, this is missing because eventually [Canonical DMs](https://github.com/vector-im/roadmap/issues/19) should become a thing... Right now you can do `/converttodm` and `/convertoroom`

**Comment by SimonBrandner** [comment]
Should I close this or is there more to this?

**Comment by chagai95** [comment]
thanks for those commands!

**Comment by SimonBrandner** [comment]
No problem!
