### ISSUE TITLE
Reopen Element to save position and size after update.

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16689]
Element should reopen to its original position and size after it updates.  It doesn't currently do that.  It seem to open always by default in the upper left of the screen.    It should be exactly where it was and the same size it was when the Update button was clicked.

**Comment by dbkr** [comment]
This should work. Can you tell us what platform you're on please? It really helps us if you use the issue template.

**Comment by dbkr** [comment]
Closing since there's been no feedback
