### ISSUE TITLE
[element design] Align Emoji Shortcodes with that of github

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16684]
Right now emoji shortcodes/"names" for element android, element web, and element ios differ from eachother, but element web seems to follow a different set of emoji shortcodes than the rest of the internet, such as `:curious:` for :thinking:.

Discord follows [Github's shortcodes](https://emojipedia.org/github/), which is closely similar to [Slack's shortcodes](https://emojipedia.org/slack/), I think it is important and useful to implement Github's shortcodes on element web, but to also do the same on other platforms, in such fashion.

**Comment by t3chguy** [comment]
The emoji shortcodes in Element Web are from https://github.com/milesj/emojibase and we are unlikely to want to curate our own list and update it every few weeks when new emojis/variations are added

**Comment by aaronraimist** [comment]
Related/dup: #13857

**Comment by ShadowJonathan** [comment]
According to the documentation, element web then seems to be using the [Legacy Emojibase set](https://emojibase.dev/emojis?shortcodePresets=emojibase-legacy), and i'm seeing it's possible to just switch to another set, or is that just the documentation?

**Comment by t3chguy** [comment]
Closing as duplicate
