### ISSUE TITLE
Default 'Go To Home' shortcut doesn't work on mac

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#16692]
It's cmd+alt+H which is 'hide other windows'

**Comment by Johennes** [comment]
How about we make it CTRL+H on macOS? CMD+H is already taken for 'hide this window'.

**Comment by Johennes** [comment]
Turns out both of these are bound by macOS as well. 🤦 

I opened #5818 to switch to CTRL+SHIFT+H on macs.
