### ISSUE TITLE
Room-specific appearance (font)

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16690]
Allow Element's appearance to be set for each room.   Specifically, I have a need for a certain monospace font in one room, but don't usually want to read this font when writing less technical prose without people in other rooms.   Currently the chosen font applies to all rooms.

**Comment by turt2live** [comment]
I'm not sure we'd really be able to support this at a product/design level (I wouldn't feel confident in it being approved if brought forward to that team), so closing for now. We might add something like this to a future iteration of custom themes, but unlikely as a dedicated/obvious option within the app itself.
