### ISSUE TITLE
Enforce a configurable jitsi user count limit for widgets, even if there are more people in the room

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#16701]
Is this something that can/should be implemented in Jitsi, rather than via eleweb?

**Comment by t3chguy** [comment]
Given that you can pop out widgets or share them oob this would have to be done on the Jitsi side.

**Comment by turt2live** [comment]
... if we keep popout

**Comment by t3chguy** [comment]
Even if we don't, for Jitsi's without auth this could be easily bypassed and is an equivalent of client-side password validation

**Comment by turt2live** [comment]
imo it's no different of a request than https://github.com/vector-im/element-web/issues/13074 - in fact, both might end up solved at the same time.

**Comment by t3chguy** [comment]
that one *does* have to be done on the Jitsi side though, therefore 

> ... if we keep popout

seems incorrect here

**Comment by turt2live** [comment]
there's a few different tracks to some of these issues. Popout is one of them, Jitsi is another.

**Comment by benparsons** [comment]
It still seems like this is something that should be configured on the Jitsi side, and they already have a config for this. I'll close.

https://community.jitsi.org/t/solved-where-to-add-the-muc-max-occupants-to-limit-participants-in-a-meeting/73968
