### ISSUE TITLE
The UX response on setting room importance (fav, low prio) is sluggish on slow homeservers

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16709]
Whenever I press "favorite" or "low priority" on a room on my homeserver (`jboi.nl`), the UI/UX takes a moment to "respond", there is no acknowledgement of my action in the meantime.

For comparison, on `matrix.org`, these actions are instant, but on other homeservers, this action can take a while, and clog up the user experience.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14302
