### ISSUE TITLE
Recent update to element on element.io broke user status markers in a chat room

### ISSUE THREAD

**Issue by shmerl** [vector-im/element-web#16712]
Until recently, element was showing position of the last read message for various users in the room.

Something broke that, and now user markers (avatars) aren't following the activity unless I refresh the page.

Browser: Firefox 87.0b9.
Element: app.element.io with matrix.org.

**Comment by turt2live** [comment]
@shmerl which operating system are you using?

**Comment by shmerl** [comment]
Linux (Debian testing).

**Comment by turt2live** [comment]
alright, thanks. I think this is a duplicate of https://github.com/vector-im/element-web/issues/16646

**Comment by shmerl** [comment]
Yep, that's it. Thanks for the pointer.
