### ISSUE TITLE
Dragging anything at all over the timeline spawns the "Drop file here to upload" overlay

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/element-web#16728]
### Description

As the title states, dragging anything at all over the timeline triggers the overlay. That includes selected text from the timeline, or any text in general, which also makes pasting text by dragging impossible.

### Steps to reproduce

- Select any text in the timeline
- Drag it such that it is still over the timeline
- Notice that the file upload overlay appears

I'm not sure if there is any way to detect the type of data being dragged over the window, but if there is, the overlay should appear exclusively for files which can be uploaded (releasing the dragged text does not trigger an upload).

Logs being sent: no

### Version information

- **Platform**: Desktop
- **OS**: openSUSE Tumbleweed
- **Version**: 1.7.23 (Flatpak)

**Comment by t3chguy** [comment]
Some browsers tell you the type until the drag drop, I've seen this on Safari for one. Firefox seems to at least though

**Comment by TR-SLimey** [comment]
@t3chguy what about Electron? It should probably allow it also.

So does this mean the issue will be fixed for some browsers/is already fixed on some browsers?

**Comment by t3chguy** [comment]
In electron I couldn't reproduce it happening.

**Comment by TR-SLimey** [comment]
Ah, weird. Could it have anything to do with the fact that I'm using the Flatpak version from flathub?

**Comment by SimonBrandner** [comment]
I can reproduce this on Electron. Maybe OS-specific?

**Comment by TR-SLimey** [comment]
Interesting. I'm on `openSUSE Tumbleweed x86_64 Plasma 5.21/X11` if any of that makes any difference.

**Comment by SimonBrandner** [comment]
Also happens on Windows
