### ISSUE TITLE
[Spaces] Add ability to stick room to "Home" (default) space

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#16724]
**Is your suggestion related to a problem? Please describe.**
I can add needed room to several spaces without problems. But the problem is that when I add the room to any space, it will immediately disappear from the "Home" space (virtual space with orphaned rooms).

But many people want to keep some rooms in "Home" space too, after adding them to other Spaces, and this behavior confuses them!

**Describe the solution you'd like**
Will be good to have the way to force "stick" specific room into "Home" space, when adding it to other Space, or when it is already in Space.

Maybe this can be implemented using the new room tag `m.visible_in_home` (like the `m.favourite` that we already have), or `m.sticky`, `m.default`...?

**Describe alternatives you've considered**
Alternative solution is to create manually the "Home" space, and aggregate all needed rooms into it, but as result we will have two "Home" spaces and will need to add manually all new rooms into custom "Home", that's bad.

**Comment by t3chguy** [comment]
There will be a way to select multiple spaces at once, why not have your own VIP space and select it at the same time as Home if you care for such?

Favourites and DMs will also already be shown in Home always.

**Comment by MurzNN** [comment]
> Favourites will also already be shown in Home always.

Yes, this will be a suitable solution, but not works like described in current version.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/111775184-52cd4680-88a8-11eb-9df7-4958a2c1c5ea.png)

It already does, but seems like there is an updating bug where it needs a refresh to realise
