### ISSUE TITLE
Redacted messages don't show sender

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#16739]
### Description
When a message is redacted, the sender is no longer rendered. Following messages from the same user also don't render the sender, which means they appear as if the user who sent the last message before the redacted message sent all the messages.

I think this is a regression introduced in matrix-org/matrix-react-sdk#5728

### Steps to reproduce

1. Send a message
2. Redact it

![image](https://user-images.githubusercontent.com/4224639/111908383-bbabee80-8a61-11eb-9266-8c3a313f609a.png)

Only the first message was sent by tulir, the redacted message and "test c" were sent by tulir[m].

<details>
<summary>Event sources</summary>

```json
{
  "content": {
    "body": "test a",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1616336561093,
  "sender": "@tulir:maunium.net",
  "type": "m.room.message",
  "unsigned": {
    "age": 345
  },
  "event_id": "$qSfDjp3T2I8buarpmuOgwBXA9J211UcR99TN1UQLpIM",
  "room_id": "!test/v6 🐈️:maunium.net"
}
```
```json
{
  "content": {},
  "origin_server_ts": 1616336563257,
  "sender": "@tulir:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 628,
    "transaction_id": "m1616336562964.14",
    "redacted_because": {
      "content": {
        "reason": "removed message from tulir[m]"
      },
      "origin_server_ts": 1616336574653,
      "redacts": "$nm7K5iXwY76N_ByCxm2VfsPIjNvRZVVCuBqfi08T6EE",
      "sender": "@tulir:matrix.org",
      "type": "m.room.redaction",
      "unsigned": {
        "age": 114,
        "transaction_id": "m1616336574423.15"
      },
      "event_id": "$--yFkLWHEI2hIiOV6fx4RKX_0L7yFA-P9gBuiCxIYUI",
      "room_id": "!test/v6 🐈️:maunium.net"
    }
  },
  "event_id": "$nm7K5iXwY76N_ByCxm2VfsPIjNvRZVVCuBqfi08T6EE",
  "room_id": "!test/v6 🐈️:maunium.net"
}
```
```json
{
  "content": {
    "body": "test c",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1616336577141,
  "sender": "@tulir:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 342,
    "transaction_id": "m1616336576910.16"
  },
  "event_id": "$RlKAKycrubWHiJSVpNSH5Qtv-Y3YxGbKv3BkG1QmvKk",
  "room_id": "!test/v6 🐈️:maunium.net"
}
```

</details>

### Version information

- **Platform**: web
- **URL**: develop.element.io, mau.chat

**Comment by SimonBrandner** [comment]
Not sure about the regression here, should be tested out

**Comment by tulir** [comment]
It works fine on app.element.io, so it's definitely a recent regression. I'm not sure if it was that specific PR, but that PR did mess with redaction rendering, so I guessed it's the most likely
