### ISSUE TITLE
Switch to last viewed room from a space upon switching to that space

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16730]
I often find myself switching between two rooms that are in different spaces (usually a DM and a room). I think it would make sense to redirect to the last viewed room from a space after switching to that space.

Note: I hope this makes sense, my brain is starting to fall asleep...

**Comment by t3chguy** [comment]
This is a thing Nad wrote up somewhere. Great minds think alike

**Comment by t3chguy** [comment]
Nad:
> After pouring more thought into this I think it would be a huge misstep to stray from Discord or Slacks semantics of switching to a space and switching to the last viewed room within that space.
> It's essential to easily context switch between different spaces, and the alternative is opinionated and would alienate anyone coming from other platforms.
> For subspaces, can we follow the same semantics of spaces? As a user my expectation and goal is to view the last room I was within a space. It's less important to sync across devices, but at the least when switching between spaces on the same device I want to retain the same context.

**Comment by MTRNord** [comment]
I agree with this for space Home pages. however for rooms I prefer to not change if the room is in both spaces. But as I didnt test this too in depth yet in actual day to day usage I am not 100% sure if thats good UX or just sounding good

**Comment by ShadowJonathan** [comment]
> However for rooms I prefer to not change if the room is in both spaces.

This could "override" that hard-born discord/slack convention if you suddenly have to chase the room when you step into another space, so maybe make this toggle-able?

**Comment by tanriol** [comment]
It's not nice that I cannot switch to a room in some space without clearing unread count on a (possibly different) room in the same space that happens to be the previous one.
