### ISSUE TITLE
Dial pad button spacing increases with window

### ISSUE THREAD

**Issue by JamesVStone** [vector-im/element-web#16737]
### Description

When using the dial pad in a call the spacing between the buttons increases as the window grows. If enough numbers are entered the Dial Pad window will grow horizontally. The buttons continue to become further apart with no restriction (even when they go over the parent window).

### Steps to reproduce

(only tested on desktop)
- Start a call
- Open Dial Pad
- Dial a number longer than the available space and the window will expand making the buttons further apart.

Describe how what happens differs from what you expected.

I would expect the buttons to remain stationary when the window expands. It might also be better for the text box with the numbers to scroll instead of expanding the Dial Pad.

Logs being sent: no

![2021-03-20T19:54:20,049542906+00:00](https://user-images.githubusercontent.com/33197001/111884331-fb6acb80-89b8-11eb-9f67-6d9311ab8311.png)
![2021-03-20T20:16:40,571628459+00:00](https://user-images.githubusercontent.com/33197001/111884369-366cff00-89b9-11eb-8bb0-fc2a7e98e75e.png)
### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Fedora Silverblue Linux
- **Version**: 1.7.23 (flatpak)

**Comment by anoadragon453** [comment]
I believe this is no longer an issue since #5786.
