### ISSUE TITLE
Youtube Music links preview incorrectly.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#16736]
### Description
Youtube Music links don't preview correctly. Link in screenshot: https://music.youtube.com/watch?v=_ei5tW0oadA&feature=share

### Steps to reproduce

- Paste link
- See issue

Describe how what happens differs from what you expected.
No preview, except for text that says "your browser is outdated"

Logs being sent: yes/no
no, this isn't necessary

![Capture](https://user-images.githubusercontent.com/47131867/111877715-707bd800-899c-11eb-8981-2262744ba4be.PNG)
### Version information

- **Platform**: web (in-browser) or desktop?

- **OS**: Windows
- **Version**: 1.7.23

**Comment by t3chguy** [comment]
URL previews are generated by your Matrix server; 
The issue here is music.youtube.com doesn't support OpenGraph properly https://www.opengraph.xyz/url/https:%2F%2Fmusic.youtube.com%2Fwatch%3Fv=_ei5tW0oadA&feature=share/

**Comment by jryans** [comment]
I recommend refiling this one on the Synapse repo, since there's nothing that can be done on the client for this.
