### ISSUE TITLE
Bad initial sync persists partial state in rooms

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16749]
![image](https://user-images.githubusercontent.com/22740616/112119066-4ead6b80-8bbd-11eb-8de6-fb8618b3df43.png)
(fluffychat's room, as seen from my main account)

![image](https://user-images.githubusercontent.com/22740616/112119174-6b49a380-8bbd-11eb-8dfe-76111a52ca74.png)
(Same room, as seem from an alternate account)

### Description

When a client has had a "bad" initial sync, with the homeserver giving wrong room details, the room does not display properly in the sidebar.

This is per-session and is not a bug on the serverside, this happens once (flake?) and then has the room state persisted this way.

### Version information

- **Platform**: Desktop, Element Flatpak

- **OS**: Linux PopOS 20.10
- **Version**: 1.7.23 (unknown version of when the initial sync happened)

### More information

`/devtools` state as seen from my main account + session:
![image](https://user-images.githubusercontent.com/22740616/112119783-fc207f00-8bbd-11eb-812b-755729f11e54.png)

Same as seen from my alt account:
![image](https://user-images.githubusercontent.com/22740616/112119850-0a6e9b00-8bbe-11eb-9453-05ab564d2433.png)

### Suggested fix.

`/forcestatesync`, or similar, to allow manually fixing broken rooms.

In the long term, maybe add a mechanism which detects this automatically, and/or re-requests state periodically / on reload.

This could affect Spaces, as seen above, per the previous room state being "not there" on the client.

**Comment by t3chguy** [comment]
> When a client has had a "bad" initial sync, with the homeserver giving wrong room details

Sorry how is this not a server issue?

> is not a bug on the serverside

**Comment by ShadowJonathan** [comment]
I have a pretty big account, synapse might miss something, but that means that the client should be able to at least have a fallback mechanism for resilliency

**Comment by t3chguy** [comment]
Where in the spec does it say a server can miss something and it is the client's responsibility to figure that out and work around it?

**Comment by t3chguy** [comment]
> /forcestatesync, or similar, to allow manually fixing broken rooms.

![image](https://user-images.githubusercontent.com/2403652/112133861-080f3f80-8bc4-11eb-94c7-f9746612e4de.png)

**Comment by ShadowJonathan** [comment]
Ah, that seems to have worked.

**Comment by ShadowJonathan** [comment]
Not sure if i should close this issue, though, because i don't think the entire issue is solved, and I think element should at least try to be more resilient than "trust the homeserver to return everything"

**Comment by t3chguy** [comment]
> trust the homeserver to return everything

So should Element also not trust the server to not be a Matrix server and maybe be an XMPP server?
The server is buggy and not conforming to spec due to such.

**Comment by ShadowJonathan** [comment]
Then it's an issue in Synapse, as that is the homeserver I'm using.

**Comment by ShadowJonathan** [comment]
Closing this per above comment, though I think that there should still be redundancies in place that detect this, and attempt a resync.
