### ISSUE TITLE
Styles dissapearing when printing on Google chrome

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#16743]
### Description

When hitting `CMD+P` (Print) it looks as if all the stylesheets get removed and no styles are applied to the page anymore

### Steps to reproduce

- Load app.element.io on Google Chrome
- Make sure to have `use_system_theme: true` in `mx_local_settings` (local storage)
- Hit CMD + P

And then 🔥 🔥 

![Screen Shot 2021-03-22 at 16 25 39](https://user-images.githubusercontent.com/769871/112023852-88359680-8b2b-11eb-9fea-dea58407742e.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: app.element.io

**Comment by t3chguy** [comment]
I cannot reproduce this on macOS Chrome/FF
![image](https://user-images.githubusercontent.com/2403652/112026050-bae08e80-8b2d-11eb-9745-d343a20a96c7.png)

Does it still happen in incognito/private browsing (no extensions)

**Comment by gsouquet** [comment]
It does not happen in incognito mode, however I'm working off a fresh Chrome install that has no extensions installed 🤔

**Comment by gsouquet** [comment]
Closing as I can't reproduce anymore, but it kept on happening yesterday
