### ISSUE TITLE
The custom homeserver field on the login flow doesn't select reliably.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16758]
This is reproducable ~70% of the time for me on Catalina + Chrome.  You click on the custom homeserver field to edit it, and it promptly de-focuses immediately afterwards.  Also, the placeholder text is black when it should surely be greyed (or show a suitable example).

https://user-images.githubusercontent.com/1294269/112188710-217fae00-8bfb-11eb-923c-39798ef5b4ef.mov

**Comment by ara4n** [comment]
(related https://github.com/vector-im/element-web/issues/16297)

**Comment by SimonBrandner** [comment]
I knew it! Duplicate of https://github.com/vector-im/element-web/issues/18031
