### ISSUE TITLE
importing key : "erreur inconnue" (unknown error)

### ISSUE THREAD

**Issue by Marc-marc-marc** [vector-im/element-web#16755]
### Description

using Element Web, I try to import my previously saved key.

### Steps to reproduce

- open https://app.element.io
- connect using my email with matrix
- click on my nickname on the top left
- click on "security and privacy
- click on "import end-to-end encryption keys
- browse, select file, type password, import
- the error message appears

Describe how what happens differs from what you expected.

I was expecting the import of my key or a more explicit error message 

Logs being sent: it fail #16757

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 78.8.0esr (64 bits)
- **OS**: CentOS Linux release 7.9
- **URL**: app.element.io

**Comment by jryans** [comment]
@Marc-marc-marc Since log sending fails, can you check the console for errors just after importing?

**Comment by kittykat** [comment]
@Marc-marc-marc I'm going to close this issue for now as we need more information to action it. Please comment with @kittykat and attach the logs if you're still getting this issue :+1:
