### ISSUE TITLE
Composer forgets reply-to when switching to different chat

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16767]
### Description

When clicking the "reply to" button, putting something in the composer, and then leaving to another chat quickly, the composer forgets the event being replied to.

### Steps to reproduce

1. Click "reply to"
2. Put something in the composer
3. Browse away to a different room
4. Go back to the original room
5. Observe reply-to indicator being gone (and subsequently also not working, even when pressing enter)

### Describe how what happens differs from what you expected.

I expected the reply-to indicator still persisting.

### Version information

- **Platform**: Desktop, Flatpak

For the desktop app:

- **OS**: PopOS 20.10 (Ubuntu 20.10)
- **Version**: 1.7.23

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/16716

**Comment by ShadowJonathan** [comment]
Not sure if this is duplicate, i'll close this if that other issue is updated that this happens even if the composer is empty or not.

**Comment by ShadowJonathan** [comment]
I should note that this occured with a reply to an event far out of timeline view, a pretty "early" event, which might or might not influence behaviour for this

**Comment by nadonomy** [comment]
Closing, given https://github.com/matrix-org/matrix-react-sdk/pull/5796.
