### ISSUE TITLE
Halt message-sending if one message fails to send

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16771]
This is mostly to avoid those "message failed to send" nightmare scenarios, where one specific message being left out of the message chain causes it to be interpreted incorrectly by the recipient(s), but this proposal is also to ensure a more robust delivery of messages.

(User Story: When my Wifi went down, the Element client kept on trying to send some messages out of a series i composed, however, when the wifi came back on, it only sent the last one, which confused my collegue before i showed them the other messages that failed to send.)

Halting when a message fails to send can be annoying, but in combination with #14181 could give better user experience by letting the messages only send in-order, *exactly* as you have submitted them, which gives a better perception of reliability for matrix.

Additionally, when a message fails to send, there should either be a button to "re-send", or "ignore" the error, this allows the user to control this error state, and if a message is particularly problematic (due to a bug), they could or should additionally also be able to report this (via a dedicated "report problem" button?), in any case, message-chaining will not continue until the message has either been successfully re-sent, or been explicitly ignored (to allow the next message(s) to send)

**Comment by ShadowJonathan** [comment]
I recently also found out element does not cancel an 'edit' message transaction if the message that its editing is technically still unsent, creating an event that references a temporary transaction

**Comment by ShadowJonathan** [comment]
Extra info; Telegram and Whatsapp are more robust with message handling (see https://github.com/vector-im/element-ios/issues/4711), and almost never show a "cannot send message" error, except under network conditions which'd force them to send an image or so repeatedly, probably making the user burn up their data cap.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/22885 which has more participants
