### ISSUE TITLE
Emojis not showing on Windows Electron with Windows Emoji pop up

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16778]
### Description

Emojis not showing on Windows Electron with Windows Emoji pop up as opposed to web

### Steps to reproduce

- press windows key and dot on the keyboard to open windows emojis
- select an emoji
- does not show
- after clicking somewhere else it does show.

Logs being sent: no

![image](https://user-images.githubusercontent.com/31655082/112458525-2eb4ae00-8d5d-11eb-8407-236d4c069ca9.png)

https://user-images.githubusercontent.com/31655082/112512387-9dacf980-8d93-11eb-912d-2e524eb7aa62.mp4

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **Version**: 1.x.y

**Comment by t3chguy** [comment]
Looks like the text field isn't selected (no ocaret)

**Comment by chagai95** [comment]
@t3chguy I added a screen cap to show and description, hope it's clear now

**Comment by t3chguy** [comment]
if its working in Web but not in Electron then sounds like a bug there

**Comment by chagai95** [comment]
Can not reproduce anymore, so I guess Electron fixed this? Anyway I'm closing this..
