### ISSUE TITLE
Clarify README for Content-Security-Policy header usage

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16774]
We have a bundled CSP so we don't need to ask users to set one. Typically people will set this on all aspects of Element, which includes the usercontent.html page (which then breaks download links for encrypted media)

**Comment by spantaleev** [comment]
Seems like the README is misleading right now, saying that `add_header Content-Security-Policy "frame-ancestors 'none'";` can be used, while that's not really the case.

In https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1154, we've found out that `frame-ancestors 'self'` works well.

**Comment by opusforlife2** [comment]
Clicking on `View Source` on a downloadable item in Element-Web used to let me copy the URL and paste it in a new tab to be able to download the encrypted media.

Now that HTTPS URL has been replaced by an MXC URL, which the browser cannot parse. I'm forced to request users to send me the HTTPS link each time I wish to download an encrypted media.

Could this be fixed soon, or the HTTPS -> MXC change reverted for now?

**Comment by t3chguy** [comment]
When looking at view source you're looking at the raw data that was sent which is up to the sender. The matrix spec says to use mxc so all clients send it as this. For encrypted media a https download is not possible as the file is still symmetrically encrypted after download. Mxc is a federated protocol and if you read the matrix spec you can see how easy it is to get from an mxc to https url. Just swap out mxc:// for a prefix based on your matrix server url

**Comment by opusforlife2** [comment]
Well, I don't know how, but that method used to work. Another method that used to work was opening uBlock Origin's logger and clicking the download URL from there.

**Comment by t3chguy** [comment]
Neither would work for encrypted attachments due to them having to be decrypted into blob urls which browsers only make valid in the same origin

**Comment by opusforlife2** [comment]
Oh wait, I am so sorry. This happened on a bridged IRC channel. No encryption involved.

But why wouldn't the download button work if that's the case?

**Comment by t3chguy** [comment]
Too many variables to answer. Maybe your browser or a extension prevent programmatic downloads. I suggest asking in the support room rather than a wholly unrelated issue.

**Comment by opusforlife2** [comment]
> Maybe your browser or a extension prevent programmatic downloads

This is likely the case. Sometimes Firefox shows an alert that uBlock Origin has blocked the download from Element Web.

Thanks! Marking as off-topic.

**Comment by t3chguy** [comment]
This got fixed
