### ISSUE TITLE
Ability to allow widgets to verify identity by default for all users

### ISSUE THREAD

**Issue by Ais8Ooz8** [vector-im/element-web#16782]
Every new user is faced with the fact that in every room he is asked to give confirmation before using the jitsi. It would be great to be able to turn off the confirmation prompt

![2021-03-25-182139](https://user-images.githubusercontent.com/66470347/112499746-d8fdf700-8d98-11eb-9c7a-e707378d704e.png)

**Comment by Ais8Ooz8** [comment]
Related: https://github.com/vector-im/element-web/issues/15740  https://github.com/vector-im/element-web/issues/15748

**Comment by turt2live** [comment]
This doesn't sound like the sort of thing we'd want to do because it's a security feature - if a widget can arbitrarily decide to verify a user's identity, it means we're leaking the user's identity to random widgets.

**Comment by Ais8Ooz8** [comment]
This is true, although in our particular self-hosted case it all comes down to the fact that users in our company initially trust us and will simply constantly confirm their permission.

**Comment by turt2live** [comment]
right, but the cost of putting something like that (even if optional) into the main app is that it could be abused by some other self hoster, or misconfigured and end up leaving the company open to auth vulnerabilities. I'd not feel super comfortable about this sort of thing being in the app, at least not until we have a chance to maybe improve on how widgets authenticate.
