### ISSUE TITLE
RoomDirectory->MessagePanel: Uncaught TypeError: can't access property Symbol.iterator, e[n].instances is undefined

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#16789]
![Peek 2021-03-25 20-47](https://user-images.githubusercontent.com/10872136/112534477-677b7400-8dab-11eb-9139-8fab976ccf95.gif)

### Description

I have a new localhost Synapse using the Docker image.
Changes I have made to the config:
 - Added my IRC bridge (which wasn't pumbing yet but the appservice bot was already connected)
 - Enabled registration

### Steps to reproduce

- Have an appservice that's not ready yet. (see Synapse's network responses in the mp4 below)
- Open "Explore rooms"
- Choose "All rooms"

Describe how what happens differs from what you expected.

The dialog closes with a JavaScript error.

```
Uncaught TypeError: can't access property Symbol.iterator, e[n].instances is undefined
    Bl MessagePanel.js:836
    render RoomDirectory.js:391
    React 7
    unstable_runWithPriority scheduler.production.min.js:13
```

Logs being sent: yes

https://user-images.githubusercontent.com/10872136/112535146-3a7b9100-8dac-11eb-9270-a7f4746d6300.mp4

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox Dev 87.0b9
- **OS**: Arch Linux btw.
- **URL**: 1.7.23 stable from the Github tar.gz on localhost via `python -m http.server`

**Comment by t3chguy** [comment]
This is an issue with a spec violation on the server side, `instances` is a required array field.

https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-thirdparty-protocols

**Comment by jaller94** [comment]
My server is `matrixdotorg/synapse:latest` which currently resolves to
https://registry.hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-67a507a29e0406a0e93a9040617380f7310f625e86adb5652ef24cd1ce39db48?context=explore

**Comment by t3chguy** [comment]
I suggest opening a Synapse issue in that case

**Comment by t3chguy** [comment]
Closing in favour of the synapse spec compliance issue
