### ISSUE TITLE
Encoded hashtag in matrix.to URL causes it to open in a new tab instead of in-app

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16795]
https://matrix.to/#/%23matrix:matrix.org

**Comment by Ashray123** [comment]
I would like to work on this issue, please guide me on how to reproduce it? :)

**Comment by turt2live** [comment]
copy/paste that link into a room and click it - it should navigate you to the room, but it doesn't. https://matrix.to/#/#matrix:matrix.org does though.

**Comment by Ashray123** [comment]
@turt2live I think this could also be the reason, please check the answers part of this [one](https://stackoverflow.com/questions/11587744/why-uri-encoded-anchors-cause-404-and-how-to-deal-with-it-in-js).

**Comment by DantrazTrev** [comment]
Hi @Ashray123  , I think it's something to do with the regex pattern `MATRIXTO_URL_PATTERN` in `linkify-matrix.js` that is causing the url to not parse in the `TextualBody.js` in the href .

**Comment by MTRNord** [comment]
Also note that they are not pillified when the pill format gets sent from other clients with urlencoded urls.

**Comment by turt2live** [comment]
@MTRNord that sounds like a different issue
