### ISSUE TITLE
[Spaces] Room and space count in space home wrong

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#16796]
This is a followup from https://github.com/vector-im/element-web/issues/16784

(cc @t3chguy )

![grafik](https://user-images.githubusercontent.com/1374914/112683800-6e20ee80-8e72-11eb-8c5e-b34c462b8d69.png)

### Description

Spaces show the room count of the outer most parent instead of the count of that space + child spaces.

### Steps to reproduce

- Add a root space
- Add 2 child spaces
- Add a room to just one space
- (Also works with having the room deeper nested)

### Describe how what happens differs from what you expected.

It should only count the rooms of the current space + child spaces

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**:  Firefox
- **OS**: Windows
- **URL**: develop.element.io

**Comment by t3chguy** [comment]
Good spot, annoyingly the API doesn't quite function in a useful way here as it goes in both directions from the given node rather than just in the one the client cares about and the client's assumption here is incorrect

**Comment by t3chguy** [comment]
This should be fixed now, it only traverses in one direction
