### ISSUE TITLE
Screenshare call doesn't end if we just cancel at the start

### ISSUE THREAD

**Issue by DantrazTrev** [vector-im/element-web#16800]
### Description

When trying to make a screenshare call and then canceliing just before chooosing the screen , the call is still going and it doesn't alllow us making another call

### Steps to reproduce

-Go to a user or a room
- Place a screenshare call but don't select a screen and cancel it
- An error would appear 
- Now try to make a call to the same person , This error is shown (that you're already in a call with the person)
![image](https://user-images.githubusercontent.com/43457420/112713649-55f5b180-8efc-11eb-9dcb-7095ecc5a506.png)

Also you're not allowed to make a call to someone until you've refreshed

![image](https://user-images.githubusercontent.com/43457420/112713906-a8839d80-8efd-11eb-9c9e-78921b8b804f.png)

Describe how what happens differs from what you expected.

The call shouldn't be placed  or terminated  if the user cancels the screenshare and things should go as normal, allowing us to make calls 
Logs being sent: no

### Version information

- **Platform**: Element Web and desktop app

For the web app:

- **Browser**:  Chromium: 89.0.4389.86 
- **OS**: Ubuntu
- **URL**: develop.element.io

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.7.23

**Comment by SimonBrandner** [comment]
I can reproduce this
