### ISSUE TITLE
Keep the order of the chats, also when filtering and with spaces

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16809]
#### Is your suggestion related to a problem? Please describe.
The jumping around of the chats is very confusing

#### Describe the solution you'd like.
Keep the order of the chats, also when filtering and with spaces

**Comment by t3chguy** [comment]
Please provide an example video of the jumping around you are talking about as a room list reordering bug was recently fixed and without context is impossible to comprehend.

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.
