### ISSUE TITLE
[Spaces] Quick actions should be sticky

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16801]
![Peek 2021-03-05 11-52](https://user-images.githubusercontent.com/25768714/112714106-f89c3900-8ed8-11eb-8435-e72cf0a04c11.gif)

I think it might look great if they were sticky.

**Comment by t3chguy** [comment]
It was intentionally made not sticky as there's no other way to hide them otherwise so scrolling them off is that way

**Comment by SimonBrandner** [comment]
Makes sense, I don't think I like either solution in the end
