### ISSUE TITLE
Empty right margin with read recipts disabled on IRC style layout

### ISSUE THREAD

**Issue by meain** [vector-im/element-web#16803]
![Screenshot 2021-03-27 at 10 36 57 PM](https://user-images.githubusercontent.com/14259816/112728369-f83d8580-8f4c-11eb-8a61-fe905af3ddb4.png)

### Description

The right margin in Element desktop (on macOS) seems to retain the right edge even if read receipts are disabled in the IRC style layout. Related issue: https://github.com/vector-im/element-web/issues/4248 . It seems to work fine in default mode, but does not seem to take effect when using IRC style display. This kinda make it a harder to use when the app is not able to use full width.

### Version information

- **Platform**: Desktop
- **OS**: macOS
- **Version**: Element version: 1.7.23 - olm version: 3.2.1

**Comment by samhh** [comment]
I'm not familiar enough with that code to feel confident in making a PR that doesn't break other things, but locally it looked like changing `.mx_EventTile_msgOption` in the React SDK to have a `max-width` as opposed to a fixed `width` vastly improved matters. In an ideal world that JSX doesn't even get rendered if there's nothing relevant to put there, though.
