### ISSUE TITLE
Message previews not shown at launch

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#16817]
### Description

I have "Show previews of messages" enabled for all sections of the room list, and they normally display as expected. However, sometimes when I open or reload Element, no message previews are displayed until I take some manual action to update the room list UI, such as activating a community filter or toggling message previews off and back on.

### Steps to reproduce

Note that I can't reproduce this reliably myself.

- Enable message previews
- Reload Element
- Toggle a community filter on and off to make them appear

Message previews should be loaded in automatically without having to interact with the room list.

Logs being sent: As soon as I can reproduce it again

### Version information

- **Platform**: web
- **Browser**: Firefox 86.0.1
- **OS**: NixOS 21.05
- **URL**: https://app.element.io/

**Comment by robintown** [comment]
The last time this happened, on 1.7.24, I also noticed that Element had forgotten the width of my room list, and so set it to collapse, and then take up half of the screen when I uncollapsed it with Ctrl+K. So maybe there's a race happening when loading the visual state of the room list.

**Comment by robintown** [comment]
Logs sent

**Comment by jryans** [comment]
Hmm, interesting... I haven't noticed this particular variant yet myself... I do observe them taking a while to appear on startup (because we have to reload cache sync info and replay the messages), but they do eventually appear.

**Comment by robintown** [comment]
Also sent logs with advanced room list debugging enabled

**Comment by robintown** [comment]
I haven't noticed this in a long time, so I'll close this as I suspect it was probably one of the many room list race conditions that got fixed recently
