### ISSUE TITLE
New post-login verification screen is confusing

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16815]
I've had to log in with another browser on my account and the experience was a bit confusing to me for the following reasons:

* it offers me to "Use another login", without defining what a login is (and I couldn't figure it out from the rest of the dialog), so I clicked on the button with only a vague guess at what it might do, which I extrapolated from the context in which this change was made (otherwise I'd probably have been clueless at what it would do)
* on the other session, I then get a "Upgrade encryption" dialog after verifying which doesn't seem to do anything, given keys seem shared and cross-signing seem enabled even if I ignore it (sidenote, I didn't have that dialog on a second attempt, so maybe that's a bug in itself?)

**Comment by babolivier** [comment]
Also the fact that the "Use another login" button is on the left makes me think it's going to cancel something rather than make my attempt progress, and tend to make my brain try to ignore that it's there.

**Comment by jryans** [comment]
>     * on the other session, I then get a "Upgrade encryption" dialog after verifying which doesn't seem to do anything, given keys seem shared and cross-signing seem enabled even if I ignore it (sidenote, I didn't have that dialog on a second attempt, so maybe that's a bug in itself?)

This part seems like a bug, or something separate... that's meant to appear for older accounts, so it's unrelated to the "happy path" flow.

**Comment by dkasak** [comment]
> it offers me to "Use another login", without defining what a login is (and I couldn't figure it out from the rest of the dialog)

I witnessed a (smart but non-programmer) user getting confused by this yesterday. I think the term "login" in this context is awkward and needs to go. "Use another one of your devices" or something along those lines would be much better.

After questioning the user, all of the following were confusing:

1. What is a "login"?
2. The button being on the left.
3. The button trying to be descriptive instead of just saying "Verify" or "Yes" or "OK" and only trying to explain the procedure after the verification has already been started.

**Comment by babolivier** [comment]
> "Use another one of your devices" or something along those lines would be much better.

Yeah, something like device or session would be way less confusing.

> The button being on the left.

Agreed, this has confused me as well, not sure why I've failed to mention it here.

**Comment by dkasak** [comment]
> Yeah, something like device or session would be way less confusing.

> Agreed, this has confused me as well, not sure why I've failed to mention it here.

[You did](https://github.com/vector-im/element-web/issues/16815#issuecomment-809475264)! 😄

**Comment by babolivier** [comment]
> You did! :smile: 

I guess it's still early in the morning :sweat_smile:

**Comment by arromdee** [comment]
I'm trying to sign in on app.element.io and I am not only running into this, I have literally no idea what to do.  I've only ever tried to log in through the web on a computer.  So even knowing that the message really means "another device or session" is useless--I've never tried to use another device with it!  Is this message actually telling me "it is impossible to sign on using just a computer"?

**Comment by duxovni** [comment]
We now say "*Verify with* another login", and the button is solid-green and on the right (the "Verify with Security Key" button will still be further to the right if present, but they're both right-aligned.) We still need to go through and change "login" to "device", and then this should be fixed once that's done.
![20211221_12h53m03s_grim](https://user-images.githubusercontent.com/6477010/146976220-e8924839-768e-4a98-8111-9eef25b39ec7.png)
