### ISSUE TITLE
No dehydrated device is found when one exists on homeserver

### ISSUE THREAD

**Issue by jamescl** [vector-im/element-web#16810]
https://github.com/vector-im/element-web/issues/16476 was marked fixed in Element Web but on login Element still doesn't seem to think a dehydrated device exists (when it does), and creates a new one.

I'm seeing a "no dehydrated device found" message in the console I didn't see before (not sure if I missed it, or if it wasn't there...), but what I think is happening is:

- Element Makes a GET request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device 
- Outputs "no dehydrated device found" **before the GET request returns**
- Makes a second GET request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device  (after receiving keys from /_matrix/client/r0/keys/query)
- The user enters their recovery key after being prompted to verify this session
- Element makes a PUT request to /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device to set a new Backup Device
- Uploads keys to the new device via POST to /_matrix/client/r0/keys/upload/ 

Without downloading any keys from the existing device

**More info /screenshots below**

I can see the "no dehydrated device" message appear while the request is still pending (Can also see the console log appear before the event appears in synapse's homeserver.log)
![image](https://user-images.githubusercontent.com/2550644/112741397-41371d80-8fd1-11eb-8102-66ee582c27c6.png)

Showing of the GET and POST requests 
The two GET requests contain valid data of the initial dehydrated device, with the following data `{"device_id":"DEVICEID","device_data":{"algorithm":"org.matrix.msc2697.v1.olm.libolm_pickle","account":" encryted content "}}`
![image](https://user-images.githubusercontent.com/2550644/112741502-1ef1cf80-8fd2-11eb-8ce0-89976dc680c2.png)

The message in context of other messages if that's useful:
```setLoggedIn: mxid: @user:homeserver deviceId: XXXXXXXXX guest: false hs: https://homeserver/ softLogout: false  freshLogin: true
StorageManager: Checking storage consistency
StorageManager: Local storage supported? true
StorageManager: IndexedDB supported? true
StorageManager: Local storage contains data? true
StorageManager: Crypto initialised? null
StorageManager: Sync store using IndexedDB contains data? false
StorageManager: Crypto store using IndexedDB contains data? false
StorageManager: Storage consistency checks passed
no dehydrated device found
Session persisted for @user:homeserver
Lifecycle: Starting MatrixClient
```

### Version information
Element web 1.7.24rc-1 on Chrome & Firefox for windows

**Comment by jryans** [comment]
@uhoreg Could you take a look at this one?

**Comment by PoolloverNathan** [comment]
What is a dehydrated device?

**Comment by SimonBrandner** [comment]
@PoolloverNathan, please ask in [Matrix HQ](https://matrix.to/#/#matrix:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org)
