### ISSUE TITLE
irc: Fix support for password protected rooms

### ISSUE THREAD

**Issue by robertfoss** [vector-im/element-web#16829]
### Description

There are two somewhat separate issues that I've found
 - There is no (documented?) way of joining password protected irc channels through the `Explore Public Rooms` menu
   * This can be worked around by issuing a `!join #channel password` to `@appservice-irc:matrix.org`
 - However this password is not remember when the room is reconnected to (after an irc server restart for example), so this room will fail to connect and will be removed from the rooms list silently without notifying the user.

### Steps to reproduce

- Manually join password protected irc channel by sending `!join #channel password` to `@appservice-irc:matrix.org`
- Wait for irc server to restart
- After restart is completed only non-password protected irc channels will be listed in your rooms view.

Describe how what happens differs from what you expected.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: matrix.org

For the desktop app:

- **OS**: Ubuntu 20.10
- **Version**: Element version: 1.7.23

**Comment by robintown** [comment]
[matrix-appservice-irc](https://github.com/matrix-org/matrix-appservice-irc/) would be the correct place to file this issue, however the solution is to use the [!storepass command](https://matrix-org.github.io/matrix-appservice-irc/latest/admin_room.html#storepass).

**Comment by robertfoss** [comment]
@robintown Storepass seems to only cover password for an irc server, not for an irc room.

Created this issue: [matrix-appservice-irc/issue/1286](https://github.com/matrix-org/matrix-appservice-irc/issues/1286)
