### ISSUE TITLE
case-sensitivity of username in urls is not respected

### ISSUE THREAD

**Issue by mqus** [vector-im/element-web#16825]
### Description
I tried to post a link to a private service, which included the authentication data (username and password, see screenshot)

![Screenshot_2021-03-30_13-58-59](https://user-images.githubusercontent.com/8398165/112985385-660dcb00-9160-11eb-8984-04d1b945fb92.png)

Sadly, the username in the generated href gets lowercased (notice the leading `u/U`), which causes the server to not accept the login.
As the shown URL still seems right, this is very unexpected.

I tried to research if the username should be case-insensitive but it should not be (see https://tools.ietf.org/html/rfc7617#section-2.1, which refers to https://tools.ietf.org/html/rfc7613#section-3.3, of which section 3.3.2, rule 3 explicitly says:

> Case-Mapping Rule: Uppercase and titlecase characters MUST NOT be
       mapped to their lowercase equivalents; see further discussion in
       Section 3.4.

### Steps to reproduce

- post a URL with user and password data (`User:Pass@` between `http(s)://` and the server domain/ip)
- try to click on posted link

Describe how what happens differs from what you expected.

**Expected:**

The URL gets transmitted to the browser/opened with the unchanged user/password data

**What actually happens:**

The username gets lowercased while everything else stays the same

Logs being sent: no, but can be provided if this really hard to reproduce (i think it isn't)

### Version information

- **Platform**: applicable to both desktop and web

For the web app:

- **Browser**: Firefox 87.0
- **OS**: Arch Linux
- **URL**: private server, 1.7.23

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.23

**Comment by t3chguy** [comment]
Workaround of `<URL>` also seems to work (Commonmark syntax for URLs)

**Comment by t3chguy** [comment]
This is a bug with LinkifyJS, I can reproduce it on their demo page: https://soapbox.github.io/linkifyjs/

**Comment by mqus** [comment]
A new linkifyjs version with a fix was published 2 months ago and the example works in the demo page (now https://linkify.js.org/#demo). Any updates?
