### ISSUE TITLE
Voice messages: the send button doesn't work

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16824]
When recording a voice message, the right hand side of the composer turns into this:
 
![Screenshot from 2021-03-30 14-12-00](https://user-images.githubusercontent.com/5547783/112986567-f13b9080-9161-11eb-9ed1-769581aafeda.png)

My understanding of this UI is that the button on the left is for stopping the recording (and either cancelling it, or listening before sending) and the one on the right is for sending the message right away, but it looks like the one on the left is for stopping and sending the recording right away and the one on the right doesn't do anything, which I find confusing.

**Comment by babolivier** [comment]
Worth noting that it seems to include something in the composer to make the "Send an encrypted message" placeholder disappear, but doesn't clear it out after sending the voice message, so the placeholder is still gone till you hit backspace.

**Comment by turt2live** [comment]
This is because it's not implemented.

**Comment by babolivier** [comment]
Oh huh my bad then!
