### ISSUE TITLE
Pressing the "Reply" button scrolls me down to the very bottom of the chat

### ISSUE THREAD

**Issue by nunoperalta** [vector-im/element-web#16833]
Pressing "Reply":

![image](https://user-images.githubusercontent.com/487079/113198142-78b9fa00-925d-11eb-8016-65d02f2a6fd3.png)

Scrolls me down to the very bottom of the chat.

https://github.com/vector-im/element-web/issues/16548 fixed that actually sending a message was always scrolling me to the bottom (which is very annoying and inconvenient).

Now, it seems that pressing the "Reply" button (to quote a message) does the same.
Please fix this, or respect the setting `scrollToBottomOnMessageSent` added by https://github.com/matrix-org/matrix-react-sdk/pull/5692

### Version information

- **Browser**: Chrome
- **OS**: Windows 10
- **URL**: Private Server, v1.7.23

**Comment by SimonBrandner** [comment]
Hmm, interesting, will look into it

**Comment by nunoperalta** [comment]
Well, actually I'm not fully sure if it happens always.

For that specific reply (with an image), I tried a few times and got down all the time.

On other replies (whether with image or not), I'm not being pushed down.

I'm not sure I understand what's the "pattern", but I can keep looking.
But do you see anything in the code that might be the "suspect"?

**Comment by SimonBrandner** [comment]
I am not able to reproduce this... I am not sure what could be the cause here. Please let me know if you are able to reproduce this with other messages

**Comment by nunoperalta** [comment]
Thank you. Not happening again for now. Closing this, and I'll see if it happens again and I understand why. Have a good day.
