### ISSUE TITLE
'Add rooms to space' dialog doesn't consider upgrades

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16834]
![](https://i.imgur.com/ipPD8uj.png)

**Comment by t3chguy** [comment]
Weird, it uses `getVisibleRooms`

**Comment by t3chguy** [comment]
Cannot repro, made new room, upgraded it, only once in the list:

![image](https://user-images.githubusercontent.com/2403652/114385457-f9df8e00-9b87-11eb-970b-3af257f6d79b.png)

**Comment by turt2live** [comment]
huh, something went badly wrong with those rooms so it's reasonable that they aren't considered an upgrade of each other.
