### ISSUE TITLE
Space panel shouldn't consider Low Priority for notifications dot

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16836]
or possibly any collapsed section?

**Comment by t3chguy** [comment]
Wouldn't it be weird if your favicon had a dot due to Low Prio but the Space panel didn't and you'd have to visit all your spaces to find it manually

**Comment by turt2live** [comment]
I would find it weird if my favicon did in fact have a dot - it doesn't because I've set all my rooms to Mentions Only.

**Comment by t3chguy** [comment]
So by `Low Priority` here do you mean kill off grey dots for the Space Panel or use a Tag to mangle push rules behaviour?

**Comment by turt2live** [comment]
I think I mean I need to think more about what I want out of the spaces which have rooms tagged as low priority: why will I have demoted them to low priority *and* put them into a space...

**Comment by SimonBrandner** [comment]
I've been thinking about this: What I think we should do is simply not show unreads in the space panel. Currently, they make the space panel too cluttered, IMO

**Comment by ShadowJonathan** [comment]
I'm against that, I'd like to see unreads per space, though maybe for non-highlighted unreads, it shouldn't be a number, just a bigger grayer circle.

**Comment by SimonBrandner** [comment]
To be clear: by unreads I mean messages that don't include a mention nor a keyword and are in rooms which are either set to `Mentions only` or to `None`

**Comment by SimonBrandner** [comment]
This is for example what Discord does, afaik

**Comment by SimonBrandner** [comment]
It's also what Element Android does

**Comment by jaywink** [comment]
Definitely agree on this. Currently the notification dot is pretty much useless for me for larger spaces where I've put the rooms I don't plan on reading everything in (but want to be joined for mentions etc) as Low Priority. However, since they have unread messages pretty much all the time, these spaces are just constantly with a notification dot, which means I have no way of telling if I need to click on a space to see if it has interesting unread messages, and end up clicking through them "just in case" periodically, only to most of the time not seeing any (interesting non low priority) rooms with new messages.

**Comment by SimonBrandner** [comment]
@jaywink, to be clear, do you want the space panel to not consider _all_ Unreads (events that don't cause increased notif counts in sync) or only Unreads tagged as Low Priority?

**Comment by jaywink** [comment]
> only Unreads tagged as Low Priority?

This. So say I have a space with lots of rooms. All the rooms with unread messages are tagged "Low Priority". In this case it feels like the space should not tell me it has "unread messages". However if a room has an unread message that is not "Low Priority", then it should tell me the space has unread messages.

**Comment by SimonBrandner** [comment]
An alternative to using the low priority tag would be a per-space setting which also isn't a bad idea, IMO. Now that I think of it, it might actually be a bit better, because it is a bit clearer to the user why the dots are visible/why they are not

**Comment by ShadowJonathan** [comment]
+1 on "tags per spaces", though maybe that should be a separate issue?

**Comment by SimonBrandner** [comment]
Sorry, I wasn't suggesting per-space tags, I was suggesting not considering unreads from low priority rooms in the space panel

**Comment by jaywink** [comment]
> An alternative to using the low priority tag would be a per-space setting which also isn't a bad idea, IMO. Now that I think of it, it might actually be a bit better, because it is a bit clearer to the user why the dots are visible/why they are not

I'm unsure, Element is already very settings/configuration heavy, which is great for techy power users but not so great for a lot of people who come from simpler mainstream apps. Personally it feels like a natural thing to do, "if I set something as 'Low Priority'", it's not important for me to see whether it has new messages". It could be just my workflow, of course, but I feel that adding a new per-space setting would just add to the configuration burden.

What might be worth it would be a new "global preference" that would maybe trigger this behaviour, something like "Exclude Low Priority rooms from unread counters" or something, with (IMHO) a default set to true, but allowing people to return to the old behaviour.

**Comment by SimonBrandner** [comment]
I am unsure about this, while I agree that we have way too many settings/preferences/options, a settings can be better, so that it's clearer to the user what is going on. Perhaps when tagging a room as low priority there could be a tooltip explaining this
