### ISSUE TITLE
Spaces with more than 49 rooms say there are only 49

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16835]
Might be a Synapse thing?

**Comment by t3chguy** [comment]
Yup, the API limits at 50 results (root + 49) currently with no pagination mechanism.

**Comment by anoadragon453** [comment]
Which Synapse API is this out of interest?

**Comment by t3chguy** [comment]
`/rooms/$roomId/spaces`

**Comment by anoadragon453** [comment]
Ah I see. Discussion is ongoing in the relevant MSC: https://github.com/matrix-org/matrix-doc/pull/2946

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18089
