### ISSUE TITLE
Filtering rooms by name in a space should hint that results might be in another space

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16847]
I seem to want to just mash words into the filter box even if I'm in the wrong space. Might be helpful to say '3 other results elsewhere' so as a user I can click on that and see the room(s) I'm looking for?

**Comment by SimonBrandner** [comment]
Related to [#16683](https://github.com/vector-im/element-web/issues/16683)

**Comment by turt2live** [comment]
another option would be to persist the filter across subspace changes so I can go find the room myself

**Comment by t3chguy** [comment]
That was the original behaviour but Nad thought it was jarring

**Comment by ara4n** [comment]
🧐

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16998
