### ISSUE TITLE
Cannot Search Japanese Words in Public Room no Encryption

### ISSUE THREAD

**Issue by harupiyo** [vector-im/element-web#16841]
### Description

Like: https://github.com/vector-im/element-web/issues/16289

### Steps to reproduce

- I wrote "記事へのリンクを張るテストです。"(messege for test) in Public Room.
- I searched "記事へのリンクを張るテストです。" or "リンク" or some words/charactor But no result. 

Logs being sent: no

Screenshots:
![Enter the messege On Public Room No Encryption](https://user-images.githubusercontent.com/92463/113248392-d9961080-92f7-11eb-82e0-aabe5d061edd.png)
![Search by some charactors/words But Not Found](https://user-images.githubusercontent.com/92463/113248419-e74b9600-92f7-11eb-8691-05d70f03e4aa.png)

### Version information
- Using Matrix-Synapse server by Self-hosting(Matrix SDK Version: 0.0.1 on Ubuntu20.04)
- **Platform**: desktop(Windows10home,Element v1.7.24,olm v3.2.1), App(Android9, v1.1.3, olm v3.2.2)

thanks.

**Comment by harupiyo** [comment]
NOTE: Label-i18n

**Comment by aaronraimist** [comment]
This is most likely a Synapse issue rather than something wrong with Element. Search in unencrypted rooms is done by the server.

https://github.com/matrix-org/synapse/issues/901

**Comment by t3chguy** [comment]
Closing as public room search is done server-side and not by Element.

**Comment by harupiyo** [comment]
thanks!
