### ISSUE TITLE
SVG glitches in E2E decoration

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#16843]
<img width="256" alt="Screenshot 2021-04-01 at 11 10 09" src="https://user-images.githubusercontent.com/4626865/123111172-9b127c80-d434-11eb-959f-036252ef30ea.png">

Seems like there's multiple SVGs off by a pixel or so, creating a grey halo around icons.

**Comment by t3chguy** [comment]
@nadonomy would be good to get those screenshots

**Comment by SimonBrandner** [comment]
@nadonomy, is this still a problem, should this be kept open?

**Comment by nadonomy** [comment]
Yep. Just tested, and updated the main issue with a screenshot and more context.

**Comment by t3chguy** [comment]
Ah, its part of my mask based fill leaking out, weird rendering glitch. Probably sub-pixel rendering related
