### ISSUE TITLE
Update Slack integration instructions

### ISSUE THREAD

**Issue by mefuller** [vector-im/element-web#16858]
![Screenshot_20210404_032914](https://user-images.githubusercontent.com/10563357/113496065-3b23ce00-94f6-11eb-9f04-d724fa3d2577.png)

### Description

When adding a Slack bridge, instructions still specify to `/invite @riot_bridge` when this must be `/invite @element_bridge` now

### Steps to reproduce
 - Bridge to Slack on Element
 - Element pops up instructions

Describe how what happens differs from what you expected.
 - Slack doesn't recognize  `/invite @riot_bridge` butdoes work properly with `/invite @element_bridge` 

Logs being sent: yes/no

### Version information

Desktop - Fedora 33 - COPR (https://copr.fedorainfracloud.org/coprs/taw/element/)

**Comment by jaller94** [comment]
This has been fixed internally and will be part of the next release of Scalar.
