### ISSUE TITLE
Issue with search/history/file attachment

### ISSUE THREAD

**Issue by ShingoGear2nd** [vector-im/element-web#16857]
Hi and good morning!
I've got an issue with the web app and desktop app also
The issue is the same
In a chat with a friend (first use of this app honestly), i found that i can't reach any history or search as the program should do

In the attachment you can see that also in desktop app i still got the message "use desktop app to see history"
The person that have chat with me do not have the issue in the same chat, so i suppose is something mine but i really didin't realize what

I use Windows 10, and for web app Google Chrome Versione 89.0.4389.114 (Build ufficiale) (a 64 bit)

Just to be clear, i got the app from **https://element.io/get-started**, so the original site

May i help you in some other way? just have to ask
Thanks for your time, i'll wait for your response
Best regard
Luca

![image](https://user-images.githubusercontent.com/73182123/113482622-c3c34f80-949f-11eb-9246-8003ba90afa5.png)

![image2](https://user-images.githubusercontent.com/73182123/113482650-ebb2b300-949f-11eb-8345-9751dc878f2b.png)

**Comment by SimonBrandner** [comment]
@ShingoGear2nd, did you send logs? If not, please do so

**Comment by SimonBrandner** [comment]
Related: [#16636](https://github.com/vector-im/element-web/issues/16636)

**Comment by ShingoGear2nd** [comment]
sure, done!
Need to send again?

Il giorno dom 4 apr 2021 alle ore 07:52 Šimon Brandner <
***@***.***> ha scritto:

**Comment by ShingoGear2nd** [comment]
I've just seen your answer, Simon...so tnx a lot, it's done!
Now everything is fine, really appreciate it

Tnx a lot and have a nice day!
Best regards
Luca

Il giorno dom 4 apr 2021 alle ore 23:59 Luca Manassero <
***@***.***> ha scritto:

**Comment by t3chguy** [comment]
Closing in favour of #16636 - please try workaround on https://github.com/vector-im/element-web/issues/14229#issuecomment-652980655 or wait until next release which will have a button to do this.
