### ISSUE TITLE
[design] Show encryption lock during E2EE calls

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16855]
To show an "encryption lock" (opposed to a shield, as this only signifies E2EE connectivity) on call dialogs (on web/desktop) or call detail-views (on mobile), so that users are aware these calls are end-to-end encrypted.

I'm not sure if showing a shield here would help, because the shield is already shown in the DM room, but it wouldn't also be possible(?) to verify the other party via it's encryption, unless i'm wrong.

**Comment by joepie91** [comment]
Additional context: people in HQ frequently ask "are calls encrypted?" which implies that the UI does not make it obvious enough.

**Comment by aaronraimist** [comment]
Existing issue for this: https://github.com/vector-im/element-web/issues/12878

**Comment by SimonBrandner** [comment]
@aaronraimist, is there any reason to not close this as a duplicate (I think you have the permissions to do so, right?)?

**Comment by aaronraimist** [comment]
Clicked the wrong button
