### ISSUE TITLE
URL previews for Youtube are useless

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#16853]
### Description

The URL preview for Youtube links are always the same. A sign in message and a warning about cookies. It's never the actual video.

Please compare Youtube:

![Youtube](https://user-images.githubusercontent.com/152227/113410762-7b7b3300-93b4-11eb-9924-64b5eca051df.PNG)

To a random other video service:

![Dumpert](https://user-images.githubusercontent.com/152227/113410795-87ff8b80-93b4-11eb-9752-60de8c47afc9.PNG)

### Steps to reproduce

1. Post a link to a Youtube video.
2. That's it.

Describe how what happens differs from what you expected.

It should preview the actual video, not some useless cookie message or whatever it is.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 1.7.24

**Comment by SimonBrandner** [comment]
Works for me. This looks like a server issue

**Comment by thany** [comment]
Who's server issue then?
Because I'm on matrix.org, and the other person is on a self-hosted server.

**Comment by SimonBrandner** [comment]
My **very limited** understanding was that this is generated by the server, so this would be matrix.org issue but that feels weird

**Comment by ShadowJonathan** [comment]
Related: https://github.com/matrix-org/synapse/issues/9733

**Comment by t3chguy** [comment]
Yup, this is wholly not an Element thing, Element just asks your Matrix homeserver for a URL preview; looks like Youtube has broken their opengraph tags based on some User Agents, Synapse has special support for Twitter which did the same.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/9733 - other media repos do not have this issue (*hint*)
