### ISSUE TITLE
Element desktop should support i18n

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16854]
I don't think we can use `ipc` for this - is there any way to avoid a whole i18n thing in Element desktop?

**Comment by jryans** [comment]
I don't think we need to block the release for this, but yes, it would be good to find a path to translate the text.

**Comment by SimonBrandner** [comment]
Yeah, it was mainly to get this a bit of attention, sorry for abusing the label for that :laughing: I guess most Element non-English users will be able to figure this out but this _should_ be solved. I don't feel exactly great about this...

**Comment by gsouquet** [comment]
There's currently no i18n support in the whole of `element-desktop`. I mentioned this in vector-im/element-desktop#173 but probably should have made that a bit clearer.

All the menu items are also english only unfortunately. Bringing a new internationilisaition system looked a bit out of scope of the original issue but definitely agree that we could implement this

**Comment by SimonBrandner** [comment]
Ah, sorry - missed it in the description. I didn't really realize the menu isn't translated either (I have my system in English). Hmm, I think we probably can't use `ipc` for this (there might have been a chance to make it work with the quit menu but I don't _think_ it could be done globally) - is there any way to avoid a separate i18n support in `element-desktop`?
