### ISSUE TITLE
Design feedback on showing invite reasons

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16869]
Let's use this to track design feedback on https://github.com/matrix-org/matrix-react-sdk/pull/5694 (which I accidentally merged early).

Context from the PR by @robintown:

> Displays the reason for invitation in the invitation dialog, requiring a click to reveal the message. I based it on [this mockup](https://user-images.githubusercontent.com/1922197/88951009-56ff1200-d28d-11ea-905c-1695ce838a80.png), which I assume still needs a design review.
> 
> ![Screenshot_2021-02-26 Element  1  test room](https://user-images.githubusercontent.com/48614497/109355352-167c6c80-784d-11eb-916c-c5355421ed08.png)
> ![Screenshot_2021-02-26 Element  1  test room(1)](https://user-images.githubusercontent.com/48614497/109355366-1b412080-784d-11eb-94e8-50b82d04856d.png)

**Comment by niquewoodhouse** [comment]
Just to check somethings please:

- Is it just co-incidence that the room avatar and the user avatar in the message area are the same? This isn't an invite to a user/DM, but a room?   
- What does an invite to a user/DM look like if reasons are added?  
- How is an invite-reason added to an invite?  Is this web only for Element, or does it/can it exist on Android and iOS too?

**Comment by jryans** [comment]
> * Is it just co-incidence that the room avatar and the user avatar in the message area are the same? This isn't an invite to a user/DM, but a room?

Yes, that's correct, just coincidence from the test data used here. The top avatar under the "do you want join room X" heading is the room avatar.

> * What does an invite to a user/DM look like if reasons are added?

It would look the same as above, but with different header text like we currently have for DM invites (this is unchanged by the invite reasons PR). E.g. the header says "Do you want to chat with %(user)s?" and below the room avatar, it says "<userName/> wants to chat".

At the moment though, there's no way to send an invite reason for a DM in Element Web, since it's currently on exposed as a slash command in the room (see below), which means the room already exists, and for a DM it means you've already invited the one other person most likely. (Other clients might have some UI to send a reason with a DM invite though.)

> * How is an invite-reason added to an invite?  Is this web only for Element, or does it/can it exist on Android and iOS too?

At the moment, in Element Web it's an advanced feature which (I believe) is only exposed via a slash command. E.g. in some room, you can type `/invite @bob:foo.com a really good reason`. Other Matrix clients might have a better UI in place for this.

**Comment by turt2live** [comment]
Please let's also consider the safety side of this, particularly the unsolicited messaging impact.

**Comment by SimonBrandner** [comment]
> Please let's also consider the safety side of this, particularly the unsolicited messaging impact.

I think this is handled quite well with this

![Screenshot_20210406_134232](https://user-images.githubusercontent.com/25768714/113705629-f5295e80-96dd-11eb-9c2a-3641e204a09e.png)

**Comment by turt2live** [comment]
That might need a bit of review: it was not obvious from my 6am glance

**Comment by niquewoodhouse** [comment]
> That might need a bit of review: it was not obvious from my 6am glance

Just to check please @turt2live, is it the UI that's not obvious, or the solution of hiding the message by default that doesn't consider the safety side enough?   Thanks

**Comment by turt2live** [comment]
It currently looks like the invite message is the warning text - the opacity isn't clear enough. A blur or some other component would help

**Comment by niquewoodhouse** [comment]
I took a quick look at this today @jryans 

Some options [here](https://www.figma.com/file/D776QToqQ358H2iyv1TsR2/Web-Show-invite-reasons?node-id=19%3A15) but pulled out a few to put here.  Given the majority of invites wouldn't include a message, I don't personally believe there is a reason to spend much effort on this.

Something that was a bit troubling in the original UI was the use of a 'speech bubble' style box.  I'm not saying speech bubbles aren't good/something Element should have, it just seems like a random place to start sneaking that in and then being inconsistent with how messages look elsewhere.


![03 1](https://user-images.githubusercontent.com/1587166/113897468-cd5ff680-97c2-11eb-9cb0-4b6602a6d143.png)

![04 1](https://user-images.githubusercontent.com/1587166/113897496-d5b83180-97c2-11eb-9fc2-b61d59c9ca67.png)
![01 1](https://user-images.githubusercontent.com/1587166/113897532-dea90300-97c2-11eb-9763-53330971b8c1.png)

![05 1](https://user-images.githubusercontent.com/1587166/113897439-c5a05200-97c2-11eb-8cf0-7700318815d5.png)



In some of them I've assumed we can get things like number of members, if its a private/public room.  I'm not suggesting thats the scope for this, just more things we could do, one day.

**Comment by jryans** [comment]
@niquewoodhouse Thanks for working on these on such short notice! 😅 I should be able to implement one of these, such as the first image with the blurred reason. The last image which reworks the overall layout of the invite acceptance is probably to large a change for the current scope, but seems like a good future direction.

**Comment by t3chguy** [comment]
>  The last image which reworks the overall layout of the invite acceptance is probably to large a change for the current scope

It is near-identical to the Space invite preview so it could be a quick steal

**Comment by jryans** [comment]
> It is near-identical to the Space invite preview so it could be a quick steal

Hmm true, but it would imply entirely changing the general appearance of room invites, which is a much larger scope than intended here. Maybe we want to do that, but let's explore that separately with a bit more breathing room.
