### ISSUE TITLE
Notification when someone with the same/similar name is referenced

### ISSUE THREAD

**Issue by besendorf** [vector-im/element-web#16863]
### Description

I noticed that when someone posts a reply to someone with the same display name as myself Element notifies me as if it was a reply to my post(text in red and a sound notification)

### Steps to reproduce

- have three users (A,B,C) in the same room
- set display name for A to: "user" and display name for B to "User"
- A writes "hello"
- C replys to A's message
- B gets a notification

### Describe how what happens differs from what you expected.

You should only be notified when a reply is sent to your message. You should of course be also notified when your display name is mentioned in the body of a message, but not in the header of the message like the display name of someone else with a similar name.

### Version information

only tested on desktop. Should be the same for web

desktop app:

Element version: 1.7.24

**Comment by ShadowJonathan** [comment]
Isn't this related to reply fallbacks? And these notifications happening due to a "fuzzy search" in those.

**Comment by t3chguy** [comment]
The push rules behaviour is defined in the Matrix Spec and executed by both the Server & Client.

Related https://github.com/vector-im/element-web/issues/8497 https://github.com/vector-im/element-web/issues/9302

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-meta/issues/886
