### ISSUE TITLE
the session list should tell me if they are verified or not so it's easier to find the unverified one to remove them

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#16873]
A usual use case to go to the session list (Settings > Security & Privacy > Wher you're logged in) is if I have an unverified session I want to remove. However remembering the device ID to know which to remove is painful: it'd be easier if the list would tell me which are not verified so I can clear them easily.

**Comment by jryans** [comment]
This is covered by the designs in https://github.com/vector-im/element-web/issues/11221, so we just need to (finally) make space to do them.
