### ISSUE TITLE
Show a federation disabled message instead of "Internal Server Error"

### ISSUE THREAD

**Issue by Zachinquarantine** [vector-im/element-web#16871]
#### Is your suggestion related to a problem? Please describe.
Yes. When your account is on a homeserver with federation disabled, and you try to look at another homeserver's rooms, you will see a message saying "Internal Server Error" instead of something like "Federation Disabled".
#### Describe the solution you'd like.
My suggestion is to replace the "Internal Server Error" message with "Federation Disabled" when federation is disabled, to make it more clear to end users.

#### Describe alternatives you've considered.
N/A

**Comment by t3chguy** [comment]
This is a server issue, if it says Internal Server Error then that is because that is what the server sent us, if it does not tell the client federation is disabled then the client has no way of knowing.

I suggest opening an issue in https://github.com/matrix-org/synapse/
