### ISSUE TITLE
Localization with invite emails?

### ISSUE THREAD

**Issue by dtcg** [vector-im/element-web#16874]
I need to invite people to a room designed for French speakers only. 
Unfortunately, **the standard invite email is written in English by default**, even if the room and admin profile are setup to French. 
Am I missing something? 
Is there a collaborative translation platform connected to Element or any other way to contribute language-wise?
Thx

**Comment by turt2live** [comment]
This would be a duplicate of https://github.com/vector-im/element-web/issues/4509
