### ISSUE TITLE
Account deactivation happens without confirmation

### ISSUE THREAD

**Issue by Animajosser** [vector-im/element-web#16870]
### Description

I am pretty sad, because I lost my account with this issue.

I wanted to look at the section detailing account deactivation, so I clicked it. It was really stupid in hindsight, as I expected a confirmation dialog and wasn't thinking of clicking confirm. However the software decided I agreed and the dialog disappeared as soon as it appeared, without me doing anything, and my account was deactivated. I was left with the settings screen still visible and the background changing to white. When clicking behind the settings screen I could create a new account.

I tried with a dummy account, I still had time to click on a checkbox, this also immediately led to the same result, without any confirmation from my side.

### Steps to reproduce

- create account.
- click on deactivate account in settings.
- don't click on confirm (I couldn't even see the button at all. it went really fast for me)
- account will be gone.

Describe how what happens differs from what you expected.

I expected a confirmation dialog waiting for me to click it. I would click: "NO" and it would be over.

### Version information

webapp in Firefox 87.0 on Linux.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/issues/9754 is the corresponding Synapse issue

**Comment by turt2live** [comment]
I've flagged this as "Spec Compliance" which isn't super accurate but the best we have for "we made a wrong assumption and the spec didn't help us"

**Comment by BrenBarn** [comment]
This is not priority "Major".  This is "Critical".  This is the kind of bug that will turn people away from matrix for the rest of their lives.

**Comment by ShadowJonathan** [comment]
A quick hack to put 1 more modal over that button up-front would work in this case.

**Comment by clokep** [comment]
Synapse v1.37.0 will remove this behavior, see matrix-org/synapse#10184.

**Comment by turt2live** [comment]
Considering fixed for now due to that
