### ISSUE TITLE
User names have same colors in a DM 

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#16881]
### Description

It happens very often that users have same colors in a DM.

![obrazek](https://user-images.githubusercontent.com/15554561/113855357-371ad900-97a0-11eb-86e5-5e2d68728a0a.png)

Users should have always different colors. It's quite difficult to recognize author of each message while browsing history.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 88
- **OS**: Windows 10
- **URL**: private server, Element Web 1.7.24

**Comment by SimonBrandner** [comment]
IIRC, the colours are generated based on usernames and they should be the same in every room. I guess [#5626](https://github.com/matrix-org/matrix-react-sdk/pull/5626) could help this. Do you feel like that is an adequate solution?

**Comment by waclaw66** [comment]
Better then nothing :) As I understood still in development, right?
It would be better to use predefined user name colors in 1:1 DMs. Also chat bubbles would solve it 🙏

> 
> 
> IIRC, the colours are generated based on usernames and they should be the same in every room. I guess [#5626](https://github.com/matrix-org/matrix-react-sdk/pull/5626) could help this. Do you feel like that is an adequate solution?

**Comment by SimonBrandner** [comment]
> Better then nothing :) As I understood still in development, right?

Yeah, waiting for a review

> Also chat bubbles would solve it 

Would it make sense to close this in favour of the [bubbles issue](https://github.com/vector-im/element-web/issues/4635)? Hopefully, we should be able to merge bubbles from SchildiChat at some point.

**Comment by waclaw66** [comment]
> 
> Would it make sense to close this in favour of the [bubbles issue](https://github.com/vector-im/element-web/issues/4635)? Hopefully, we should be able to merge bubbles from SchildiChat at some point.

Sure, https://github.com/matrix-org/matrix-react-sdk/pull/5626 works for me as temporary workaround.

**Comment by SimonBrandner** [comment]
Ok, closing in favour of above mentioned PRs/issues
