### ISSUE TITLE
config.json.gz file prohibits config.json to be respected

### ISSUE THREAD

**Issue by chris-aeviator** [vector-im/element-web#16887]
### Description

When using the docker container, a `config.json.gz` file that is present in `/app/` prohibits my config from `config.json` to be read.

### Steps to reproduce
- Mount a custom config.json file into element-web docker container.
- Access https://my-element.tld/config.json -> default config.json is displayed
- delete `/app/config.json.gz`
- Access https://my-element.tld/config.json -> custom config.json is displayed

Describe how what happens differs from what you expected.

My config.json should be respected at the first place

Logs being sent: yes/no

### Version information
latest

- **Platform**: web 

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: linux
- **URL**: private, latest version

**Comment by jryans** [comment]
What version is "latest version"...? 😅 The special 1.7.24.1 release of the Docker image attempts to fix precisely this.

**Comment by chris-aeviator** [comment]
@jryans thanks for pointing that out. element-web 's docker image, that's tagged latest, is referring to https://hub.docker.com/layers/vectorim/element-web/latest/images/sha256-fbfdf6c82a32884b1266dbd7fc345be1dcd65240f4b230c10113899baf44b7d4?context=explore which not seems to have a version tag

**Comment by jryans** [comment]
@chris-aeviator Ah I see, perhaps the `latest` tag wasn't updated with 1.7.24.1. In any case, it has now been updated for 1.7.25, so I assume this resolves the issue...?

**Comment by t3chguy** [comment]
Closing due to lack of response, please shout if you are still experiencing this issue
