### ISSUE TITLE
Prune unused translations

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16885]
![image](https://user-images.githubusercontent.com/31655082/113970406-181b5600-9837-11eb-8d63-afc955787171.png)

A little bit confusing because 

Start a conversation with someone using their name, username...

is used  but 

, email address or username

is not. So username and email address are in a different order.

**Comment by jryans** [comment]
Yes, there are many such unused translations. We have a script that can be run occasionally, but it requires locking the translation tool to avoid conflicts, so it's only run occasionally. Anyway, it's perhaps good to schedule a fresh run.

**Comment by turt2live** [comment]
(I would recommend running it after spaces lands given the strings are changing there)

**Comment by t3chguy** [comment]
This got done recently and will now be done periodically
