### ISSUE TITLE
Failed addition of rooms to a space don't get retried if rate limited by backend

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#16891]
Synapse aggressively rate limits (https://github.com/matrix-org/synapse/issues/9487) adding rooms to spaces. On my homeserver 10 is the most I can do at once.

In Element v1.7.24.1 it looks like any failures to add rooms to a space do not get retried if the backend returns a 429. There is also no visible error to the user that the addition failed.

Expectation: Element would notify me if rate limited OR automatically retry.

**Comment by t3chguy** [comment]
Estimate: 1D

**Comment by t3chguy** [comment]
![Uploading image.png…]()
