### ISSUE TITLE
Added rooms to a space but some of them are still visible in the orphaned rooms home view

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#16894]
I added rooms to a space. Some of the rooms are still visible in the orphaned rooms "space" (even after cache clear).

I added 46 rooms to a space. I tried to add more but rate limits made some of the additions fail (see #16891 ). Mentioning if this might have caused some of the rooms to still show up in the orphaned home "space".

Synapse v1.31.0 with `spaces` experimental feature enabled.
Element v1.7.24.1.

Will submit rageshake and mention room ID's there.

**Comment by jaywink** [comment]
I think this was due to the rooms being favourites (which I understand is per design?). I'm not seeing this anyway at the moment with 1.7.25. I'll close for now, unless someone else sees the same.

**Comment by t3chguy** [comment]
> which I understand is per design

Yup, Home is defined as a place of high signal-noise, so Favourites + DMs. The only reason we have orphans there is lack of a better place to house them
