### ISSUE TITLE
Forget room not working

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16898]
### Description

nothing happening when pressing forget room
![image](https://user-images.githubusercontent.com/31655082/114220057-ca543a00-996b-11eb-9dcc-78b749b74f44.png)

### Steps to reproduce

not sure

Log: sent    

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? Chrome PWA latest version
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **URL**: app.element.io

**Comment by chagai95** [comment]
a refresh cleared it of course...

**Comment by chagai95** [comment]
Saw this as well and sending different logs to this same ticket hope it does not confuse too much

![Uploading image.png…]()

**Comment by SimonBrandner** [comment]
@chagai95, what version of Element are you using?

**Comment by chagai95** [comment]
1.7.24 latest on app.element.io sorry I forgot to mention that, thought it was obvious but off course it could be that i didn't update...

**Comment by chagai95** [comment]
@jryans I think some stuff is still buggy here...


https://user-images.githubusercontent.com/31655082/123299879-3df0f680-d51a-11eb-9cb7-786c5cc3a10f.mp4

[logs-element-web.zip](https://github.com/vector-im/element-web/files/6710788/logs-element-web.zip)

sent logs, but it might be easier to reproduce, just try forgetting a room refreshing and then forgetting a different room

**Comment by chagai95** [comment]
So this is the ticket which is no open for that:
https://github.com/vector-im/element-web/issues/18473
