### ISSUE TITLE
Inviting a user with email

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16893]
### Description

not sure if this is implemented yet, I believe it was in the past, am I wrong?

### Steps to reproduce

- paste an email address into invite search bar
- press go 
- get this:

![image](https://user-images.githubusercontent.com/31655082/114171325-6b270300-9934-11eb-8dd2-6e5e3957ce13.png)

Describe how what happens differs from what you expected:
I expect the matching userId to this email to be invited (when identity server set up properly)

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **Version**: 1.7.24

**Comment by SimonBrandner** [comment]
Works for me - I can't reproduce this

**Comment by SimonBrandner** [comment]
The problem is probably somewhere in [here](https://github.com/matrix-org/matrix-js-sdk/blob/f1e1daa1949152351862c7cba25d36c80c6a5963/src/base-apis.js#L88). `this.idBaseUrl` seems to be `null`

**Comment by JohannesKleine** [comment]
I can confirm this. Pasting something in the search field gets the @ auto completion. Typing the mail address manually works fine.

**Comment by chagai95** [comment]
@SimonBrandner are you trying to reproduce with matrix.org? I think I didn't have this error there but it still sent an email instead of mapping to the matrix user, is this expected behavior?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/235124349-00938a4f-31fd-4eb0-8669-065d64561862.png)
![image](https://user-images.githubusercontent.com/2403652/235124370-49d8ecd6-d192-49f2-942e-331a99132658.png)

It no longer crashes but the error is crap, making a PR to improve it
