### ISSUE TITLE
"Favorite" changes spellings when you click on it.

### ISSUE THREAD

**Issue by bytesized** [vector-im/element-web#16901]
### Description

The "Favorite" button changes spellings when you click on it.

### Steps to reproduce

- Click on the meatball menu for a channel.
- Observe that the first option reads "Favorite".
- Click the "Favorite" button.
- Click the meatball menu again.
- Observer that the first option has changed spelling and now reads "Favourited". I believe that it should be spelled "Favorited".

![favorite](https://user-images.githubusercontent.com/5944152/114244518-2de76300-997e-11eb-8b54-3bb895c5df0d.PNG)
![favourited](https://user-images.githubusercontent.com/5944152/114244526-3475da80-997e-11eb-80fc-793dccfc7243.PNG)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox Nightly 89.0a1 (2021-04-09) (64-bit)
- **OS**: Windows 10
- **URL**: https://chat.mozilla.org

**Comment by turt2live** [comment]
As mentioned on the PR, this can be fixed at translate.element.io
