### ISSUE TITLE
Enhance contact search for starting PMs

### ISSUE THREAD

**Issue by a-0-dev** [vector-im/element-web#16909]
#### Is your suggestion related to a problem? Please describe.
Finding the contact you want to text in a PM is incredibly hard, especially if the person is on another homeserver

#### Describe the solution you'd like.
Adding all Matrix IDs known to the client (members of rooms the client is in, Matrix IDs referenced in text messages) to the potential search outcomes, thus utilizing the effect that users usually want to start a PM with someone who already has some loose relationship with the user.

**Comment by SimonBrandner** [comment]
![Screenshot_20210410_134335](https://user-images.githubusercontent.com/25768714/114268696-c3c4d180-9a02-11eb-9977-40e306faed76.png)

As far as I know this should already happen, right?

**Comment by a-0-dev** [comment]
My bad, I tested some more and it seems to work in many, but not all, cases... I could not narrow it down to some specific set of accounts where it does not work as expected, I'll close the issue until I find out why this might be

**Comment by t3chguy** [comment]
> I could not narrow it down to some specific set of accounts where it does not work as expected

By default Synapse only lets you search for users you share rooms with/users which are in public rooms (for privacy reasons)
