### ISSUE TITLE
Editing of images does not work

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16903]
I consider this a bug not a feature request. 

One can edit the text of a message.   One cannot, however, edit an image, and replace it with another, but I often need to do this because I messed up the copy or need to update.  Instead I need to create another jag in my message flow with a deleted message annotation I can't hide or delete and repost the updated image to a later spot in the flow where it makes less sense and damages context/coherency.  Please fix this.  Telegram lets you edit/replace an image.  Element should allow this too.

**Comment by SimonBrandner** [comment]
I am sorry, but this qualifies as an Enhancement

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11137
