### ISSUE TITLE
Forwarding of messages

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16905]
This is such a clumsy aspect of Element, I can only conclude that I just haven't learnt the quick way to do it yet.  I need to forward messages from one room to another, a block of them, say 10 messages, some of which are images.  How do I select all of them, with, say, the Shift- and Ctrl-keys, in the usual way when working in any document, and then quickly select a recipient from the ones already listed under people or rooms, without having to type a matrix address designating that recipient?  This is the way Telegram does it, and I just expected it it work in Element. 

Will this behavior be working soon?  If this is not planned, will someone please raise its prioritize.  Thanks.

**Comment by SimonBrandner** [comment]
Related to [#5641](https://github.com/vector-im/element-web/issues/5641) and [#14690](https://github.com/vector-im/element-web/issues/14690)

**Comment by jryans** [comment]
I believe this is summarised by "forwarding is strange", and that is well known and tracked in the existing issues.
