### ISSUE TITLE
Option to hide deleted-message annotations

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16906]
Please give the user the option to hide deleted-message annotations.  This is especially helpful when making notes to self in a private room where debri like this isn't helpful or wanted.

**Comment by SimonBrandner** [comment]
![Screenshot_20210410_132829](https://user-images.githubusercontent.com/25768714/114268294-a55dd680-9a00-11eb-8609-9d0d1c817155.png)

@Shaping, is this what you mean? It is already possible in Setting → Preferences → Timeline

**Comment by SimonBrandner** [comment]
Closing as there doesn't seem to be any response from the author.
