### ISSUE TITLE
Camera not released after call

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16916]
### Description
![image](https://user-images.githubusercontent.com/31655082/114355300-98abc080-9b6f-11eb-9ab8-8c43314e61e4.png)
![image](https://user-images.githubusercontent.com/31655082/114355315-9d707480-9b6f-11eb-90ee-8991e6ea4307.png)

freed after refresh

### Steps to reproduce

unknown

Logs being sent: no
![image](https://user-images.githubusercontent.com/31655082/114355739-2091ca80-9b70-11eb-86c1-b36863eca43a.png)

could not send logs, any idea why the option is not showing?

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? develop branch

**Comment by SimonBrandner** [comment]
Is this Jitsi or the native Matrix calls?

**Comment by t3chguy** [comment]
> could not send logs, any idea why the option is not showing?

> URL: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? develop branch

Whichever Element instance you are using isn't configured with that ability.

**Comment by SimonBrandner** [comment]
> Is this Jitsi or the native Matrix calls?

@chagai95

**Comment by chagai95** [comment]
Sorry, missed this, don't know anymore and I don't have logs...

**Comment by SimonBrandner** [comment]
If we don't have the info, I think we can close this... If you ever encounter this again please open a new issue with logs
