### ISSUE TITLE
Weird email notification behavior on encrypted rooms

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#16910]
![matrix-encrypted-notif](https://user-images.githubusercontent.com/145412/114267156-7d6b7480-99fa-11eb-86d7-3f57ef356b58.png)

Recently, a [public channel](https://app.element.io/#/room/#mwstake-general:matrix.org) I get email notifications for has been switched to encrypted (but still public). The result is weird: the messages just say "an encrypted message", and I seem to get a notification about every new message, even though notifications are configured only for messages mentioning me. I can understand why the server wouldn't be able to see or filter the messages (although it is a public channel so in theory some kind of system account should be able to join and see the messages) but it is still disorienting, and even more so - I imagine - for someone who doesn't know much about the concept of E2EE. At a minimum the notification email should contain some sort of explanation about what's going on.

**Comment by SimonBrandner** [comment]
The whole point of E2EE is that the server can't read the messages. Also, it is pointless to enable encryption in a public room - if someone wants to read the messages they can just join the room. [There should be a dialog to warn you about that](https://github.com/vector-im/element-web/issues/16525)

That being said, I agree - there should probably be some info about this in the email.

**Comment by t3chguy** [comment]
> although it is a public channel so in theory some kind of system account should be able to join and see the messages

At that point your encryption is broken as that server could/would just be logging everything in plaintext in its db/fs

Fundamentally these emails are from the backend rather than Element, so best to seek Synapse support

**Comment by t3chguy** [comment]
If you are still experiencing this bug, please open an issue in https://github.com/matrix-org/synapse/
