### ISSUE TITLE
[Spaces] Spaceless room navigation is inconsistent

### ISSUE THREAD

**Issue by williamkray** [vector-im/element-web#16912]
The current behavior has been seen in the current implementation of Spaces:

- Direct messages do not appear in Spaces unless the DM is with someone who is also a member of that space. There is no way to add a DM to a Space used for personally organizing your rooms.
- Direct messages appear in both a Space and in `Home`. This is inconsistent with how `Home` behaves for normal rooms, which only appear there if they _do not_ belong to a Space.
- There is no way to browse or search _all rooms and DMs_ across all spaces. If you are looking for a room, you must know that it is either not part of a Space, or know exactly which Space(s) it is a member of.

I propose the following UX changes:
1. Make `Home` show all rooms and DMs, similar to the old Communities behavior when no community is selected. This allows for finding rooms and DMs in an aggregated view.
2. Add a new Space view/filter/button like `Home`, but that only shows rooms which are _not_ associated with any Spaces.
3. Include an option in the user's client settings to enable or disable each of the `Home` and `Orphaned` Space views to be flexible for the user's workflow and usecase of Spaces.
4. Ensure that DMs behave similarly to normal rooms in Spaces: users should be able to add a DM to a space just like a normal room without needing to invite the other user to the Space. Additional behavior of automatically including the DM in a Space when both accounts are members of the Space is still logical.

**Comment by t3chguy** [comment]
> There is no way to add a DM to a Space used for personally organizing your rooms.

This is https://github.com/vector-im/element-web/issues/16704

> Direct messages appear in both a Space and in Home. This is inconsistent with how Home behaves for normal rooms, which only appear there if they do not belong to a Space.

Home is designated as being a place of High Signal-Noise, it is by definition where you find all your Favourites & DMs. The only reason "orphaned" rooms are shown there is for lack of a better place.

> There is no way to browse or search all rooms and DMs across all spaces. 

This is https://github.com/vector-im/element-web/issues/16683

> Make Home show all rooms and DMs, similar to the old Communities behavior when no community is selected. This allows for finding rooms and DMs in an aggregated view.

You will be able to shift click as many/few spaces you wish to see together in one view in the future.

**Comment by williamkray** [comment]
awesome. so, does that mean all points covered in this issue are duplicates? happy to close this if it's unnecessary, i just didn't see those other issues when trying to find what i was looking for. alternatively, we can leave this open if there are ideas in the proposed UX that still seem relevant.

**Comment by t3chguy** [comment]
If you think the behaviour of home as described above then re-open, but its behaving as intended currently
