### ISSUE TITLE
Invisible icon in notification area with desktop version on Linux (Flatpak version on Xubuntu)

### ISSUE THREAD

**Issue by gdurif** [vector-im/element-web#16917]
### Description

Using Element-desktop on Linux (Xubuntu/XFCE), especially the Flatpak install from Flathub (https://flathub.org/apps/details/im.riot.Riot), the Element icon in the notification area is invisible despite a dedicated place.

c.f. attached screen shot (3rd spot from the left)

![element_missing_notification_icon](https://user-images.githubusercontent.com/38720408/114360953-23d38900-9b65-11eb-9699-cb6c33480d3a.jpg)

I did try to change the area background color to be sure it was not some color superposition issue.

It can be noted that I can use the Element "invisible" icon as if it was visible, e.g. by clicking on it to Show/Hide Element desktop, or to quit.

### Steps to reproduce

- install from Flathub  (with command `flatpak install flathub im.riot.Riot`)
- run Element-Desktop (e.g. with command `flatpak run im.riot.Riot`)

-> no visible Element icon in the notification area (c.f. attached screenshot)

### Version information

- **Platform**: desktop
- **OS**: Xubuntu 18.04.5 LTS / XFCE 4.12
- **Version**: 1.7.24

**Comment by t3chguy** [comment]
Are you able to reproduce this issue on the official distribution of the Linux build? The flatpak is unofficial and if it has bugs specific to itself they need to be reported to its maintainers.

**Comment by gdurif** [comment]
I tried to build and run Element-desktop from the official repository and there is no problem. The tray icon is visible.
Sorry, I will report this to the maintainer of the flatpak.
