### ISSUE TITLE
Widget background color set by theme

### ISSUE THREAD

**Issue by vranki** [vector-im/element-web#16919]
### Description

Widgets are web pages in iframe. Web pages have white background by default.

Element web's widget viewer uses background color from theme. This causes
many web pages to have black text on dark background with dark themes.

### Steps to reproduce

- Create a widget, for example https://tkstats.r-f.fi/
- Set dark theme
- Observer page being unreadable

### Suggested fix

- Set the background of widget area to white.

### Version information

- **Platform**: all

For the web app:

- **Browser**: Firefox
- **OS**: Windows
- **URL**: app.element.io

**Comment by t3chguy** [comment]
A webpage relying on the browser's background being white is an anti-pattern, given this is not mandated anywhere and is up to each browser. My chrome for example does not have a white background by default.

![image](https://user-images.githubusercontent.com/2403652/114386348-044e5780-9b89-11eb-8e77-bf6e406f3ea4.png)

**Comment by vranki** [comment]
Your chrome seems to also have white foreground color. Maybe this could be solved by changing the foreground color also to theme's foreground, but I still believe that lot of web pages would still be broken if they assume white background and define custom font colors.

WWW is broken and we can't fix it in Element unfortunately. I still think setting white background is the safest workaround.

**Comment by t3chguy** [comment]
> Maybe this could be solved by changing the foreground color also to theme's foreground

That is impossible, a webpage cannot add styling (CSS) rules to cross-origin iframes.
The page you are iframing has a transparent background, so the app is showing through it.

**Comment by vranki** [comment]
Sounds like the only solution or should we call it workaround is defaulting to white background.

**Comment by turt2live** [comment]
Considering most widgets are meant to be developed specifically for client use, I don't think this is a problem. For non-widget pages being embedded as widgets, those pages should not be relying on browser defaults anyways.

I think we'd consider this a bug of the embedded page every time, so closing.
