### ISSUE TITLE
VoIP buttons fade out while you're hovering over them.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16928]
If you're on a 1:1 VoIP call, the buttons fade out even if the mouse is hovering over them after a small period of inactivity.  Rather than buttons disappearing from under the mouse when you might be trying to click on them, we should keep them visible while mouseovered.

**Comment by SimonBrandner** [comment]
Duplicate of your own issue: [#16751](https://github.com/vector-im/element-web/issues/16751)
