### ISSUE TITLE
Can't start a DM with multiple people

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16924]
On today's nightly, hitting "start chat" and entering two users in the resulting dialog failed with "Failed to invite the following users to chat:..."

```
rageshake.js?432e:65 Inviting @foo:bar.com
14:41:28.749 rageshake.js?432e:65 Error: Room not found
    at MultiInviter._inviteToRoom (webpack-internal:///693:121)
    at eval (webpack-internal:///693:154)
    at new Promise (<anonymous>)
    at MultiInviter._doInvite (webpack-internal:///693:147)
    at MultiInviter._inviteMore (webpack-internal:///693:295)
    at MultiInviter.invite (webpack-internal:///693:91)
    at inviteMultipleToRoom (webpack-internal:///692:58)
    at eval (webpack-internal:///695:457)
consoleObj.<computed> @ rageshake.js?432e:65
14:41:28.750 rageshake.js?432e:65 Inviting @baz:bar.com
14:41:28.750 rageshake.js?432e:65 Error: Room not found
    at MultiInviter._inviteToRoom (webpack-internal:///693:121)
    at eval (webpack-internal:///693:154)
    at new Promise (<anonymous>)
    at MultiInviter._doInvite (webpack-internal:///693:147)
    at MultiInviter._inviteMore (webpack-internal:///693:295)
    at eval (webpack-internal:///693:296)
consoleObj.<computed> @ rageshake.js?432e:65
14:41:28.752 rageshake.js?432e:65 Failed to invite users:  Object
14:41:28.763 rageshake.js?432e:65 !ChCjocznfbXyPhBgev:matrix.org is current in RVS but missing from client - clearing sticky room
```

**Comment by ara4n** [comment]
(looks to be a classic case between the dialog creating the room, and actually issuing the invites to it)

**Comment by jryans** [comment]
@ara4n Can you be more specific on how you are choosing users...? I tried to replicate by typing in a name, clicking from the suggestions, typing another name, clicking the suggestion, then pressed Go, and it seemed to work correctly.

**Comment by ara4n** [comment]
https://user-images.githubusercontent.com/1294269/114406078-26eb6b00-9b9f-11eb-8ce7-64f53df77215.mov

**Comment by jryans** [comment]
Hmm, okay, I can reproduce on matrix.org, but not on my local development Synapse... 🤔

**Comment by ara4n** [comment]
almost like it's some kind of race :P

**Comment by jryans** [comment]
Hmm, looks like in the matrix.org case, we're creating the room, and then trying to look up the room before the JS SDK has heard about the new room via sync, and then inviting explodes from there.

I wonder if we removed some step that was previously waiting for the sync response somehow...

**Comment by jryans** [comment]
Looks like this is related to how invites for [multiple person DMs](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/dialogs/InviteDialog.tsx#L657-L675) are handled. If you create a DM with one person, we use the invite param in `createRoom`. If you pick multiple people, we try to create the room and invite separately, which seems to race like we see here.

**Comment by jryans** [comment]
This doesn't seem like a regression to me, but mainly an unfortunate but likely long-lived bug. Let's add to the up next list for Platform to take a look.

**Comment by jryans** [comment]
@turt2live says they have an explanation for the current state, so we may want to await their message before making a change here.

**Comment by jryans** [comment]
Sounds like the story is there was some transitional code in place here expecting canonical DMs to happen sooner than it has... We may want to revert back to previous code and / or change things such that we actually do pack multiple people into the `invite` field when creating the room to avoid the race.
