### ISSUE TITLE
Sending a new event makes the timeline jumpy

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#16920]
https://user-images.githubusercontent.com/5547783/114374909-6ce70580-9b84-11eb-9bbd-ac6d544483a0.mp4

It looks like the message appears when hitting send, then disappears and reappears when its status moves from "sending" to "sent".

(sorry for sending a video rather than a GIF, Peek seems to have a few issues with my ffmpeg version :slightly_frowning_face:)

Observed just now on develop.element.io

**Comment by SimonBrandner** [comment]
Duplicate of [#16914](https://github.com/vector-im/element-web/issues/16914)
