### ISSUE TITLE
Allow user to copy the text of messages without using the edit button

### ISSUE THREAD

**Issue by Shaping** [vector-im/element-web#16937]
Allow user to copy message text by raising a context menu over the message and selecting a message named 'copy text'.  There is already a single item 'copy image' choice in the context menu for images.  The same kind of menu does not exist for texts.

**Comment by t3chguy** [comment]
The copy image button context menu is provided by the Web browser, the webapp cannot modify those buttons.

It could at best be added to the "..." menu to the right of the messages

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/10649
