### ISSUE TITLE
"Already in call" message even though not

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#16932]
### Description

"Already in call" message even though not.

### Steps to reproduce

- sometimes after calling and hanging up
- once after trying to call when the camera was taken by another application (trying video call - not successful - trying audio call - message that a call is already in place)

Logs being sent: no - will try reproducing soon and sending logs

### Version information

- **Platform**: web (in-browser) or desktop? web

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web? develop

**Comment by SimonBrandner** [comment]
Looks like the previous call doesn't actually get terminated - weird

**Comment by chagai95** [comment]
Perhaps a virtual room issue? I could move this issue to the private GitLab repo if so...

**Comment by chagai95** [comment]
Reproduced and it works with a different session and the same user so it seems to be an Element Web bug @dbkr you think it's virtual rooms specific? 
I just sent logs to this ticket

**Comment by SimonBrandner** [comment]
@chagai95, does this still happen?

**Comment by chagai95** [comment]
I believe this was fixed here:
https://github.com/matrix-org/matrix-react-sdk/pull/6194

**Comment by SimonBrandner** [comment]
Ah, great! Closing then, if you ever see this again, ping me and I'll re-open
