### ISSUE TITLE
⌘A on AZERTY keyboards open "Close Element" Popup 

### ISSUE THREAD

**Issue by PommeAuMiel** [vector-im/element-web#16938]
Hi guys !

### Description

Shortcut ⌘A (Select All) on macOS with Element Desktop Version 1.7.25 open a "Close Element" Popup instead of select all text.
It look like this issue is present not only on macOS, i try it on Debian 10, with french AZERTY also.

When i switch to QWERTY keymap, when i physically press ⌘Q (so ⌘A) it done good shortcut "select all".

Shortcut on Element macOS app :
<img width="229" alt="Capture d’écran 2021-04-13 à 19 23 51" src="https://user-images.githubusercontent.com/82466842/114594683-d0108f00-9c8d-11eb-9e61-a813733709ce.png">
<img width="369" alt="Capture d’écran 2021-04-13 à 19 24 40" src="https://user-images.githubusercontent.com/82466842/114594776-edddf400-9c8d-11eb-8ae3-a299c34e3861.png">

### Steps to reproduce
- Switch to non-US QWERTY keyboard or use AZERTY mapping
- Open Element Desktop
- Press ⌘A (or ctrl A on Windows/Linux)

This popup appears 
<img width="312" alt="Capture d’écran 2021-04-13 à 18 42 52" src="https://user-images.githubusercontent.com/82466842/114593459-6ba10000-9c8c-11eb-8852-16fcc03ac7f7.png">

This happen everywhere i click on the Element Window.

### Version information

For the desktop app:
Test on:
- **OS**: macOS, Debian 10
- **Version**: 1.7.25 

Thanks :)

**Comment by flyx** [comment]
The same thing happens when using the [Neo layout](https://neo-layout.org) on macOS and pressing ⌘X which should cut the currently selected text but instead opens this dialog.

Interestingly, the dialog is not shown when physically selecting `Quit Element` in the menu or hitting ⌘Q – in that case, Element simply closes.

**Comment by soymalau** [comment]
Same issue, same element version, win 8.1, AZERTY keyboard, french language on. This is very annoying.

**Comment by Flandre5carlet** [comment]
Same problem on Windows 10; CTRL+A opens up the "Are you sure you want to quit?" popup, however even when selecting "Close Element", it doesn't actually close anything, and selects all afterwards.

**Comment by SimonBrandner** [comment]
I can not repro on Linux (Debian 11 Bullseye, KDE+i3wm)

**Comment by Adrien-Luxey** [comment]
Same issue on Linux Mint, Element Desktop v1.7.25, AZERTY.
**The bug doesn't trigger when I set my keyboard layout to QWERTY.**

**Comment by nicolasgavalda** [comment]
Same issue after updating Element Desktop from 1.7.24 to 1.7.25 on ubuntu 20.04, AZERTY keyboard layout (French variant).

**Comment by Thatoo** [comment]
Same issue with CTRL+A after updating Element Desktop from 1.7.24 to 1.7.25 on Debian 10, AZERTY keyboard layout (French variant).

**Comment by gsouquet** [comment]
Désolé 😅 

Thank you for reporting this issue, I have just opened a PR and this should cater for all keyboard layout.
It will probably land in the Nightly build tomorrow, and be available when Element v1.7.26 goes out

**Comment by Adrien-Luxey** [comment]
Well that was fast, thank you!
