### ISSUE TITLE
Rejecting invites can be improved

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#16931]
Element seems to only show invites as rejected after it received a leave event in /sync. This doesn't always work because the homeserver is not able to reject the invite gracefully sometimes. Synapse has to do some hacks to make up a "fake" leave event just so it can push it in /sync. I suggest Element directly hides the invite after /leave is done.

This will both improve the user experience (rejecting invites is faster) and makes it easier for other homeservers like Conduit to implement it.

**Comment by t3chguy** [comment]
It'll feel broken if the invite then is shown on some clients but not others and the user then has to reject it from each of their devices.

**Comment by ShadowJonathan** [comment]
(Spec-esc) Isn't it easier then to have an "invite status" part of the sync that manages this, where a server could detect and handle invites and rejections on its own, unrelated to showing users the `invite` and `leave` events? This could open up servers to be able to give users "virtual" invites, maybe propagated through SSO, bridges, or other modifications?

**Comment by timokoesters** [comment]
I'm now trying to make conduit send the same state in sync's left as the invite_state, so without the "fake" leave event.

**Comment by timokoesters** [comment]
Nevermind, that doesn't quite work because the events in the invite_state are stripped state events

**Comment by timokoesters** [comment]
`"leave": {!JAONbqNbxqzpSalYmF:fachschaften.org": {}}` is enough to make element hide the invite, that's good enough for me
