### ISSUE TITLE
Sign in with Matrix ID does not work with Mozilla HS

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#16954]
### Description

It's not possible to log into a `mozilla.org` account using the Matrix ID.

### Steps to reproduce

- https://staging.element.io/
- Enter e.g. "@user1234:mozilla.org" into the field "Username"
- Get error: `Invalid homeserver discovery response`

For other SSO-enabled servers element suggests to "Sign in with single sign-on".

If you use the "Sign in to your homeserver" dialog and enter `https://mozilla.modular.im` the SSO-detection works and it's possible to log in.

The [well-known](https://www.mozilla.org/.well-known/matrix/client) delegation seems to be configured correctly.

**Comment by turt2live** [comment]
Mozilla needs to enable appropriate CORS headers on their .well-known. A quick message in https://matrix.to/#/#synchronicity:mozilla.org?via=mozilla.org&via=matrix.org&via=kde.org should be able to get their attention.
