### ISSUE TITLE
Room filtering very slow on nightly.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16952]
To reproduce:
- be in ~750 rooms
- type in something to the room list filter
- wait 20 seconds whilst it churns (it does eventually seem to filter successfully)

**Comment by SimonBrandner** [comment]
Is this a duplicate of [#14750](https://github.com/vector-im/element-web/issues/14750) or is this pointing to regression perhaps?

**Comment by turt2live** [comment]
Almost certainly a duplicate of https://github.com/vector-im/element-web/issues/14750
