### ISSUE TITLE
https://packages.riot.im/ uses old branding

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#16968]
On https://packages.riot.im/:

![image](https://user-images.githubusercontent.com/1389908/114867835-29430480-9ded-11eb-8011-13cf46426c70.png)

Might be good to replace the R logo and the "Why riot?" in the header.

**Comment by jryans** [comment]
I suppose once we get around to changing the domain, let's also update the branding too.

**Comment by t3chguy** [comment]
Domain has been changed

**Comment by t3chguy** [comment]
Closed in favour of https://github.com/vector-im/pkg-repo-configs/issues/2
