### ISSUE TITLE
New Image View feedback

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#16961]
This issue is to gather any feedback regarding the new Image View so that I could make bugfix/improvement PR later

+ [x] Zooming using the scroll wheel is too fast
+ [x] Right-click triggers zoom
+ [x] ~~Clickable area is bigger than it should be~~ (this was caused by the image itself)
+ [ ] Opening pictures from the right panel sometimes fails

**Comment by t3chguy** [comment]
+ [ ] We lost the image metadata e.g size & resolution

😢

**Comment by jryans** [comment]
> [ ] We lost the image metadata e.g size & resolution

@SimonBrandner Maybe make a new issue for anything that remains...? Or reopen this one if you plan to address it before the RC.

**Comment by SimonBrandner** [comment]
@jryans, currently there are two problems:

1. Opening pictures from the right panel sometimes fails - this one seems to have the same cause as [#5692](https://github.com/vector-im/element-web/issues/5692), so I think we can track it there. I'd like to address this before the RC but I am not sure I can. I am missing some  `js-sdk` knowledge and the solution proposed by @t3chguy doesn't seem to work (see [this](https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$oIdvdv1MAGiuG1Rl_kHlAAZqTCc-ocRoYm3OlDy7DjQ?via=matrix.org&via=vector.modular.im&via=chat.weho.st)). I'll try to do more digging
2. We lost the image metadata e.g size & resolution - this was intentionally removed by @niquewoodhouse. I am not sure how necessary it is to revert that change. It would probably be best if @t3chguy made new issue for it, if he wants as it will need the design team to look into it
