### ISSUE TITLE
Integration between matrix-react-sdk and simple typescript react application

### ISSUE THREAD

**Issue by Enderedne** [vector-im/element-web#16966]
Most of todays React frontend developers will go through an application setup using CRA. 

### Using CRA & yarn:

`yarn create react-app example-matrix-react-sdk --template typescript`
`cd example-matrix-react-sdk`
`yarn add matrix-react-sdk`
`yarn start`

In the generated _App.tsx_  add `import * as sdk from "matrix-react-sdk";`

The outcome will be compilation failure. It also seems that typings are not detected + there might be a need for a webpack/babel plugin(s) to successfully run the build procedure.

### Suggestion
Build a simple CRA sample that consumes the matrix-react-sdk. This could serve as a template for applications adopting matrix. Additionally, there are plenty of frameworks samples could be made for like vue, angular, etc.

**Comment by predictron-cloud** [comment]
Is there any chance to get such example? I just want to add matrix chat to my react app, and I've been digging into the element-web webpack, babel, skins etc. configurations for 3 days.

**Comment by YousefED** [comment]
Ran into the same issue. It seems the `package.json` has the following code:

`"typings": "./lib/index.d.ts",`

However, this file is not published to NPM. This seems like a bug instead of just a documentation issue, hope it can be fixed - looking forward to developing on Matrix!

**Comment by dodosan-89** [comment]
Would it be possible to get some simple CRA example how to use the matrix-react-sdk, since this issue hasn't been resolved since this was open and there is no documentation how one is supposed to configure their-own project to make this work?

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk#matrix-react-sdk

> As of Aug 2018, the only skin that exists is [vector-im/element-web](https://github.com/vector-im/element-web/); it and matrix-org/matrix-react-sdk should effectively be considered as a single project (for instance, matrix-react-sdk bugs are currently filed against vector-im/element-web rather than this project).

**Comment by Movsar-Khalakhoev** [comment]
> Would it be possible to get some simple CRA example how to use the matrix-react-sdk, since this issue hasn't been resolved since this was open and there is no documentation how one is supposed to configure their-own project to make this work?
> 
> I'm trying to integrate matrix-react-sdk into an existing project, but for the life of me I can't seem to figure out which of the webpack and babel configurations I need to make this work.

Hi! Have you found a way to add a chat to your app?
