### ISSUE TITLE
Space ordering is indeterministic? 

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16979]
I created a giant space for a bunch of rooms, but when Matthew got roped into joining all the subspaces were in a different order for him. I was relying on the creation order of the subspaces to define where they show up in the space panel

As a feature request: ability to decide the order, if this is NotABug™

**Comment by t3chguy** [comment]
The product spec should probably be modified to say that any newly added/created rooms should be added to the end based on existing rooms orders'

**Comment by t3chguy** [comment]
Right now the MSC says to order rooms without an `order` last but does not specify any deterministic behaviour for such:

> The order key is a string which is used to provide a default ordering of siblings in the room list. (Rooms are sorted based on a lexicographic ordering of the characters in order values; rooms with no order come last. orders which are not strings, or do not consist solely of ascii characters in the range \x20 (space) to \x7F (~), or consist of more than 50 characters, are forbidden and should be ignored if received.)
