### ISSUE TITLE
Verifying sessions: Legion of Problems

### ISSUE THREAD

**Issue by otheus** [vector-im/element-web#16970]
### Description

This bug report started as small, but the more I tried to describe the problem, the more I realized it's not just a single issue. It's a LEGION of issues regarding verifying other sessions. Further, this problem has been described in part by other bugs, but is clearly present in the latest version. 

#### Problem 1:  On unverified session, users are shown other unverified sessions to verify.

Element reports that I have "unverified sessions". What it doesn't bother to mention anywhere is that *this* session is one of those that is unverified. This probably leads to the other problems below, which are confusing because of it.

#### Problem 2:  Element forces logoff after a time and apparently destroys all session data, including server name

Element automatically signs me out of other, (possibly unverified) sessions that haven't been used in a relatively small amount of time.  It is less than 60 days since the last usage, and yet that is too much time. We're not all prebuscent teens in which 60 days is a long time. To test I was using the setup correctly, I restored from a Feb 27th backup (TimeMachine) for the `library/Application Support/Element` directory and restored to the version of Element (from November 2020) that was installed at that time. No matter what, it complains, seemingly removes the entirety of login information, including the private server, forcing me to re-authenticate. Further, the re-authentication requires me to re-enter the hostname of the private server. That is more than a little annoying.

__Update__ : Being logged off might in fact be expected behavior if this session was deleted. I had many unverified sessions from my Mac, and I __assumed__ this was one of them. 

#### Problem 3: Session identifiers not shown on device-to-be-verified
After re-authentication, I am am given the option to either verify my session from another session, or "Skip", or enter a recovery key or passphrase. We'll get to that last part later.  There is NO session identifier here on this screen to assist the user in another device to determine which device needs to be verified. If you have one unverified session, that isn't a problem. But if you have multiple, as I apparently now due, thanks to the forced expiration of others, I am stuck.  My only option is to "Skip", figure out how to get to the session ID from the settings menu. This information should be provided on this initial pop-up screen.  Note: On Android, this *is a not as bad* as the session ID *can be seen* in the background (20% dark). However, Android has other problems. See 6. 

#### Problem 4:  Hard to re-initiate verification step
After _skipping_ the verification step on the the logged in, unverified session, the user wants to verify this session. See Problem 1. There is no clear way of re-initiating the verification step for THIS session. All I can do is verify "other" sessions, one of this is this one (but again, that isn't clear).  Thus, the user is led down a black hole, thinking he can verify a session, which he cannot. That leads to apparently Problem 5..

#### Problem 5: Verification process with text string is FUBAR'd, or WTF Are Security Keys/Phrases?
When attempting to verify other sessions, from either a verified or an unverified session (but again, it's not clear the current session is unverified) the user is prompted through a series of modal dialogue boxes. After being presented with the option to "Verify" another session via text string, the user is then incomprehensibly prompted for a "Security Phrase".  There is no indication of what security phrase this refers to. Nor is there any hint how to generate one from the other sessions. I mean, I still have no clue how to generate a security phrase. There are "session keys", but that wouldn't make sense, would it???

At one point I tried to make a backup of the security keys. I selected this file to upload, but the response was "invalid file". 

So this problem encapsulates (1) a failure to either check or inform the user that the current session is unverified and that verifying other sessions is pointless, and (2) If it isn't really pointless and that a phrase or key, it is completely unclear where such a phrase or key should have been generated, 

Note: When verifying such a session from Android, it simply works.

#### Problem 6. Verification with Android

Using a verified session from a Mac, I verified the session on my Android. On the Mac, it shows that this particular session (identified by the session ID) has been verified. The Element app on the Android does not agree. I have restarted the app several times.  App v 1.1.3. and after updating, App v1.1.5 the same problem. I'm prompted to "Verify the Login" on the verified device, but the verified device thinks it has been verified. 

So I start again. I delete the Android session on the verified device and login on Android anew. I go through the steps again. Ultimately, I am successful, but again there are two issues, 7 and 8.

#### Problem 7. Sessions from Android devices do not have a default name indicating their platform (Android)

Unlike all other devices I have used thus far, (Mac, Win, Chrome), my Android device does not register as having a default device type. Since the Session ID is hidden on the Verify-overview table, one must click on each unverified device to figure out which session ID matches.  

#### Problem 8: When verifying on the verified device, the notice is not obvious.

OK, if I'm looking at two devices -- say an unverified Android and a verified desktop Mac session. I want to verify with the Mac. I click on what looks to be the proper one to verify, and nothing happens. I go back to the Android and click on verify the step. I look back at the Mac, and still nothing has happened. I go back and forth. 

Then out of the corner of my eye, I see this thing counting down. Honestly, it's really subtle for an operation that was initiated by me on that device. 

#### Problem 9: No way to unverify without deleting the session

Accidentally verify a device that shouldn't have been verified? Need to re-verify a device for bug-reporting purposes?  Need to lend a phone out for a little while?  This is certainly an edge case, but I leave it in for completeness' sake. 

### Version information

- **Platform**: web (in-browser) or desktop?
- **OS** : MacOs Desktop
- **Version**: Version 1.7.25 (1.7.25)

- **Platform**: Android
- **OS** : v8
- **Version**: through 1.1.5

**Comment by jryans** [comment]
Thanks for writing up your experience, I agree there are various issues that should be improved. Unfortunately, an issue like this which mixes many problems together is not very useful for tracking: each one might have a different priority, but there's no way to indicate that at the moment. I imagine quite a few also exist as existing issues as well.

I would recommend filing each problem as a separate issue. You may also find the [cross-signing label](https://github.com/vector-im/element-web/labels/A-E2EE-Cross-Signing) points to existing issues that match what you are seeing.

**Comment by otheus** [comment]
> an issue like this which mixes many problems together  ... I would recommend filing each problem as a separate issue 

It is very hard for someone not developing the product to know what "a separate issue" is. I mean, how many of these are bugs, how many are design flaws, how many are platform-specific bugs... etc. I have no idea. If I start documenting each as an independent bug, people will ask "why is this guy reporting 10 different issues that are the same thing" and start marking them as duplicates of each other. It's d* if you do and d* if you dont. So, I leave it to others to separate this ticket into more concretized bug fixes. Thanks for your development efforts

**Comment by jryans** [comment]
> If I start documenting each as an independent bug, people will ask "why is this guy reporting 10 different issues that are the same thing" and start marking them as duplicates of each other. It's d* if you do and d* if you dont. So, I leave it to others to separate this ticket into more concretized bug fixes. Thanks for your development efforts

But that's the system functionally well... if you file 10 separate issues, perhaps 2 are duplicates, and we learn than because you filed them and they are marked as such. The entire community can help and participate. That leaves 8 issues which might all have vastly different priority, but each one can be labelled and tracked appropriately.

**Comment by ShadowJonathan** [comment]
(Please mention this issue in those new issues, it makes them appear in this conversation timeline, and easier to find)
