### ISSUE TITLE
Room in wrong space after being unfavorited

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#16978]
### Description

A room gets wrongly displayed in the home space after being removed from "favourite" 

### Steps to reproduce

- Add a room to your favorites
- Create a new space
- Add your favorite room to the new space
- Go back to home
- Unfavorite the room
- The room is displayed in the rooms sublist

### Expected behaviour

The room should not be displayed in the rooms sublist as when you move away from the home space and get back to it, the rooms fitering is done appropriately 

### Version information

- **Platform**: Element Nightly
- **Build**: Version 2021041501

**Comment by t3chguy** [comment]
Estimate: 0.5D
