### ISSUE TITLE
issue with Polka Dot 

### ISSUE THREAD

**Issue by investwithrob** [vector-im/element-web#16973]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y 
<img width="572" alt="Screen Shot 2021-04-16 at 6 18 03 AM" src="https://user-images.githubusercontent.com/82650360/115010518-838aa680-9e7b-11eb-9277-06ea4e23348c.png">

**Comment by t3chguy** [comment]
Please fill the issue template. The steps you took are quite important as there's a stray "target=" for some reason.

**Comment by t3chguy** [comment]
Closing as missing info, please add more info and we can reopen.
