### ISSUE TITLE
Space index page facepile has a spurious ellipsis

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#16976]
<img width="235" alt="Screenshot 2021-04-16 at 13 13 12" src="https://user-images.githubusercontent.com/1294269/115022633-8c986980-9eb5-11eb-86e5-fa32cb608b78.png">

i appear to have a rogue facial ellipsis

**Comment by t3chguy** [comment]
@niquewoodhouse what was the reason for this again? To suggest clickability or?

**Comment by niquewoodhouse** [comment]
Yes, a `more` to suggest clickability to see everyone who is a member.

**Comment by t3chguy** [comment]
@niquewoodhouse should the `...` maybe be on its own (empty) circle at the end rather than atop someone's face?

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse should the `...` maybe be on its own (empty) circle at the end rather than atop someone's face?

Very happy to give that a go, sounds good.  We just threw these designs together in a bit of a rush, so I don't want to make complicated suggestions - this sounds like it might work nicely.  When this page reaches its final form, maybe it doesn't work so well but it probably would be fine.

I did quickly look this morning at some small ideas, but I think moving the dot made the most sense.  Thanks

![image](https://user-images.githubusercontent.com/1587166/115394807-19576600-a1db-11eb-8f44-0cfe079c8d6e.png)

![image](https://user-images.githubusercontent.com/1587166/115394856-22e0ce00-a1db-11eb-87ea-aaed36350a91.png)


![image](https://user-images.githubusercontent.com/1587166/115395063-5b80a780-a1db-11eb-9abb-437c388edc3d.png)

![image](https://user-images.githubusercontent.com/1587166/115395090-63404c00-a1db-11eb-9eb0-1968b4e1265c.png)

**Comment by t3chguy** [comment]
Estimate: 0.5D
