### ISSUE TITLE
Add prefixes to log messaging

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#16972]
Currently Element logs a bunch of stuff just plain to `console.log`, like this;
![image](https://user-images.githubusercontent.com/22740616/114994322-f3f5ef80-9e9c-11eb-86d1-eb51b1cadda0.png)
This is a bit verbose, and so I think it'd be more helpful if it could be prefixed with the "domains" of those logs like Discord does;
![image](https://user-images.githubusercontent.com/22740616/114994398-053efc00-9e9d-11eb-8bcd-2357068008df.png)

**Comment by gsouquet** [comment]
The `rageshake.js:00` link on the right hand side of those logs is rather useless, however there's a nifty trick that is printed at the very top of the logs that will let you have the correct file and link to the original file/line

```
To fix line numbers in Chrome: Meatball menu → Settings → Ignore list → Add rageshake\.js$
```

Let me know if that fixes your use case or if there is something else you had in mind

**Comment by turt2live** [comment]
somewhere we have a dream of structured logging in Element, but I'm not sure that's tracked in an issue yet.

**Comment by Johennes** [comment]
Assuming this is addressed by Germain's comment
