### ISSUE TITLE
Inform user of issue when trying to send a message starting with a slash

### ISSUE THREAD

**Issue by poldi1405** [vector-im/element-web#16988]
#### Is your suggestion related to a problem? Please describe.
Earlier when trying to send an absolute file path pressing enter or clicking the send button would not do anything. I found out that it had to do with the file path I was trying to send, but unfortunately there was no indication of what was wrong.

#### Describe the solution you'd like.
* detecting that it is not a valid command and just send it (maybe prepend a space if necessary)

or *any* other visual indication of what went wrong

#### Describe alternatives you've considered.
* a little popup saying that "The command /… is not defined"
* detecting that it has multiple `/`s and sending it
* greying out the send button

**Comment by t3chguy** [comment]
That already happens just got broken in the latest release, it'll be fixed in the next release. You can try it on develop.element.io
