### ISSUE TITLE
Do not assume that all users are male [German Translation]

### ISSUE THREAD

**Issue by hrittich** [vector-im/element-web#16987]
### Description

In the appearance settings dialog in the section for setting the font size it reads "Hey du. Du bist der Beste!" in the German version.

![grafik](https://user-images.githubusercontent.com/13047214/115115437-c5f3d680-9f94-11eb-9ac8-98edcf0be52e.png)

Which loosely translates to "Hey you. You are the best." In German, however, you have to choose the article depending on the gender you want to address. In this case, the male article was used, and hence, only male persons are addressed as "being the best". Thus, a more accurate translation would be: "Hey *man*. You are the best." Which is odd for a female person to read.

I would suggest to change the sentence to: "Hey du. Du bist großartig." Which has roughly the same meaning but avoids the article and addresses all people.

### Steps to reproduce

- Set the Language settings of your browser to German and open the settings.

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: tested with Firefox (probably all browsers affected)
- **OS**: Gentoo
- **URL**: 

For the desktop app:

- **OS**: Gentoo
- **Version**:  1.7.22

**Comment by SimonBrandner** [comment]
Element is translated by the community, so you can suggest the translation [here](https://translate.element.io/).

**Comment by libexus** [comment]
@hrittich Thanks for your feedback. If you find any more problems like this, feel free to join us in [#element-translation-de:matrix.org](https://matrix.to/#/#element-translation-de:matrix.org) or just change it directly in Weblate.

**Comment by t3chguy** [comment]
Closing as solution has been proposed
