### ISSUE TITLE
Search all rooms crashes Element Desktop

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#16995]
To reproduce:
1. be me, with a large account (~750 rooms)
2. type a name into the search box
3. click 'All Rooms'
4. The search indicator appears; Element becomes unresponsive and after a minute or two crashes (becomes a white screen, the active jitsi call I was on dies)

**Comment by lampholder** [comment]
Actually, it's worse than that it's dead - my Element Desktop isn't coming back to life even after restarting it :(

**Comment by jryans** [comment]
@lampholder What does your "Message Search" section say in Security settings?

**Comment by jryans** [comment]
Oh, I guess you can't start it at all to check... 😭

**Comment by jryans** [comment]
@lampholder Any chance you recall what you searched for?

**Comment by jryans** [comment]
I can't reproduce this on my own Nightly, so we'll need to work out more details about @lampholder's case to take action here.

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/116065736-38447500-a67f-11eb-962f-b79586f09a64.png)

**Comment by novocaine** [comment]
@lampholder is this still occurring?

**Comment by kittykat** [comment]
@lampholder I'm going to close this issue for now as we can't reproduce and haven't had a follow up - please feel welcome to re-open with more details if you're still seeing it
