### ISSUE TITLE
screen sharing on Element

### ISSUE THREAD

**Issue by jabeshkaglava** [vector-im/element-web#16997]
Its not really an issue but a question, I just didn't know where else to ask. How do I screen share in Element in normal and group calls? Doesn't matter where/which browser, in general what do I need to do in order to share screen (with audio)?
Sorry if this is not something I should be asking here but I've been searching for a long time and I cant find a solution.
Thank you for your time.

**Comment by t3chguy** [comment]
This is an issue tracker, for questions please visit http://matrix.to/#/#element-web:matrix.org
