### ISSUE TITLE
Redaction over a day boundary causes two Todays

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#16991]
![](https://i.imgur.com/mXQEifY.png)

No redactions before the day switched over

**Comment by DantrazTrev** [comment]
Hei , is anyone working on this issue? From what I found, there is a logic error in the `RedactionGroupper` when it uses the  `_wantsDateSeparator` in `MessagePanel.js` ( `react-sdk`)

**Comment by SimonBrandner** [comment]
> is anyone working on this issue?

I don't think so. If you want to try to fix this, please go ahead!
