### ISSUE TITLE
Incorrect / Unusual emoji codes

### ISSUE THREAD

**Issue by ad-si** [vector-im/element-web#17007]
#### Is your suggestion related to a problem? Please describe.

The shortcode for the 😉 emoji is `:coy:` in Element. However, in every other app I've been using so far it has been `:wink:`. Why is it different? Is this a bug?

There are probably other weird shortcodes, which should be checked as well.

#### Describe the solution you'd like.

Use the usual shortcode

**Comment by SimonBrandner** [comment]
Duplicate of [#13857](https://github.com/vector-im/element-web/issues/13857)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/13857

**Comment by t3chguy** [comment]
arg
