### ISSUE TITLE
[Spaces] If the name of a space is long it can get cut off

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17006]
![Screenshot_20210419_200151](https://user-images.githubusercontent.com/25768714/115282122-19f3ec00-a14a-11eb-85d7-64c5c2171bed.png)

**Comment by t3chguy** [comment]
This is expected and the same as long room names, no?

**Comment by SimonBrandner** [comment]
Not really - you can always expand the roomlist but you can't do that for the space panel. Also, the dots are cut off in the middle:

![Screenshot_20210419_201425](https://user-images.githubusercontent.com/25768714/115283580-d8644080-a14b-11eb-8a0b-18bb46cb1b63.png)

**Comment by t3chguy** [comment]
Argh flex boxes are just the worst. The space panel will be user re sizable too, just like the room list panel

**Comment by t3chguy** [comment]
Cannot reproduce the cut off `...` button - what browser do you use?

![image](https://user-images.githubusercontent.com/2403652/115375091-5c0e4380-a1c5-11eb-8c3d-e258a2ccf67a.png)
![image](https://user-images.githubusercontent.com/2403652/115375115-629cbb00-a1c5-11eb-8b5f-13dc76568021.png)

I tried in Desktop app & Firefox above

**Comment by SimonBrandner** [comment]
![Screenshot_20210420_115105](https://user-images.githubusercontent.com/25768714/115376101-b19b1e00-a1ce-11eb-8d03-31932463749c.png)

It's desktop. Looks like it only happens to subspaces
