### ISSUE TITLE
Release signing key has expired

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#17005]
### Description

Trying to verify the latest [release](https://github.com/vector-im/element-web/releases/tag/v1.7.25) prints a notification that the key is expired.

### Steps to reproduce

```
# gpg --keyserver keyserver.ubuntu.com --search-keys releases@riot.im
gpg: data source: http://162.213.33.9:11371
(1)     Riot Releases <releases@riot.im>
          4096 bit RSA key 74692659BDA3D940, created: 2019-04-15
Keys 1-1 of 1 for "releases@riot.im".  Enter number(s), N)ext, or Q)uit > 1
gpg: key 74692659BDA3D940: "Riot Releases <releases@riot.im>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

# gpg --verify element-v1.7.25.tar.gz.asc element-v1.7.25.tar.gz
gpg: Signature made Mon 12 Apr 2021 04:32:08 PM CEST
gpg:                using RSA key 5EA7E0F70461A3BCBEBE4D5EF6151806032026F9
gpg:                issuer "releases@riot.im"
gpg: Good signature from "Riot Releases <releases@riot.im>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: A878 CDF6 6CF4 A9B4 807C  EBE5 7469 2659 BDA3 D940
     Subkey fingerprint: 5EA7 E0F7 0461 A3BC BEBE  4D5E F615 1806 0320 26F9
```

Checking [here](https://keyserver.ubuntu.com/pks/lookup?search=releases%40riot.im&fingerprint=on&op=index) it seems the signing key expired `2021-04-14T23:30:36Z`.

**Comment by SimonBrandner** [comment]
Please see [#16960](https://github.com/vector-im/element-web/issues/16960)

**Comment by hex-m** [comment]
@SimonBrandner The linked issue is about [packages@riot.im](https://keyserver.ubuntu.com/pks/lookup?search=packages%40riot.im&fingerprint=on&op=index) while this issue is about `releases@riot.im` which is used to sign the GitHub releases. It is specified [here](https://github.com/vector-im/element-web/blob/develop/release_config.yaml) in the source.

So I think this is a separate issue.

**Comment by SimonBrandner** [comment]
Ah, sorry, missed that - still I think this should be somehow fixed?

**Comment by hex-m** [comment]
The latest release `1.7.25` is signed with this expired key. Probably it wasn't caught because it only expired two days after the release.

**Comment by jryans** [comment]
I have created a [new keypair](https://keyserver.ubuntu.com/pks/lookup?search=0x712bfbee92dca45252db17d7c7be97efa179b100&fingerprint=on&op=index) as part of this event, as we intend to rebrand these bits from Riot to Element. For now, still using the old email though.

```
pub rsa4096/712bfbee92dca45252db17d7c7be97efa179b100 2021-04-21T13:50:54Z
	 Hash=9bf7bc474b2ca0cc4610fd922b37c3e3

uid Element Releases <releases@riot.im>
sig  sig  c7be97efa179b100 2021-04-21T13:50:54Z ____________________ ____________________ [selfsig]
```

**Comment by jryans** [comment]
We'll update the other key and bot details over in https://github.com/vector-im/element-web/issues/17030.

**Comment by jryans** [comment]
The `element-release-key.*` files at https://packages.riot.im now contain the new key. The previous key has been moved to `element-release-key-2020.*`.

**Comment by richvdh** [comment]
I'm a bit confused about why this needed a new key :-/
