### ISSUE TITLE
Viewing members of a space while in a non-space ends up showing member info details of people in that room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17018]
this makes it difficult to add new admins

**Comment by t3chguy** [comment]
it was done on purpose to aid inviting a space member to your current room

**Comment by ShadowJonathan** [comment]
Maybe a blurb above the role header saying "Role for `<room/space>`"?

**Comment by clokep** [comment]
> this makes it difficult to add new admins

As far as I can tell this makes it impossible to add new admins without modifying the power-levels event directly? Is there a workaround?

**Comment by SimonBrandner** [comment]
> > this makes it difficult to add new admins
> 
> As far as I can tell this makes it impossible to add new admins without modifying the power-levels event directly? Is there a workaround?

You need to view the members from the space home to get the correct member info

**Comment by novocaine** [comment]
My reproduction of this:

1. Right click on a space you are an admin of while another space, which you are not admin of, is selected

<img width="491" alt="Screenshot 2021-09-01 at 15 37 22" src="https://user-images.githubusercontent.com/57377/131691088-672e12dd-53c2-4c39-b9ed-c3af3799bf95.png">

2. Go to members
3. Click on a non-admin of the space in the right panel

What happened:

I can see member details, but without the possibility of setting the person as an admin. I think this is showing the panel for the selected space, not the one I right clicked..?

<img width="341" alt="Screenshot 2021-09-01 at 15 29 49" src="https://user-images.githubusercontent.com/57377/131689809-cf6f9e95-1972-4222-98a2-622a6dcc8e2f.png">

Expected:

To be able to set that member as an admin

<img width="341" alt="Screenshot 2021-09-01 at 15 30 14" src="https://user-images.githubusercontent.com/57377/131690031-f8258b91-3263-4e43-b4db-77c3f7bfc290.png">

**Comment by novocaine** [comment]
I think the desired behaviour is that the member info shouldn't differ depending on whether the Space is selected or not - the context menu behaviour should be as it is when its selected.

@niquewoodhouse can you confirm please?

**Comment by niquewoodhouse** [comment]
@novocaine I agree.  I still think there's something a bit odd about that label at the top, the way it looks and fits into the hierachy, but having that consistently show makes sense to me.

![image](https://user-images.githubusercontent.com/1587166/132008926-2b743540-c537-468d-80b5-44c110a677c1.png)

The only extra thought I had was adding the Space name to the `Role` title so it reads `Role in Space name`, so its hopefully even clearer but that might not be necessary.
