### ISSUE TITLE
`develop.element.io` with Spaces enabled switching rooms and spaces on its own

### ISSUE THREAD

**Issue by tanriol** [vector-im/element-web#17017]
### Description

After a recent `develop.elements.io` update my `develop.element.io` client with Spaces enabled got stuck in an infinite loop switching between rooms and spaces on its own without any additional user input. I've got a number of private spaces for grouping rooms and the loop involves at least one room included in more than one space and both spaces that include it.

The weird switching started before the loop and looked like this:
- I click a different space
- the space opens and some room opens
- space selection goes back to the one I was in
- room changes again
- result: I'm back in the same room where I were unable to go into rooms in the other space

### Environment
`develop.element.io` with Spaces enabled, Firefox Nightly, Linux
The problem started after an update that included https://github.com/matrix-org/matrix-react-sdk/pull/5795, which looks like a likely cause, so cc @SimonBrandner @t3chguy

**Comment by SimonBrandner** [comment]
I'd like to apologize to anyone who has been affected by this. It looks like something I have encountered before but wasn't able to repro then.

@tanriol, could you please try out the live preview [here](https://github.com/matrix-org/matrix-react-sdk/pull/5891) when it's available and confirm that it solves the problem?

I am still having issue trying to find an exact repro case

**Comment by SimonBrandner** [comment]
@tanriol, [here](https://deploy-preview-5891--matrix-react-sdk.netlify.app/) is the live preview. Could you please try? It sometimes takes some time to load so be patient please

**Comment by SimonBrandner** [comment]
To reproduce:

+ Go to home space
+ Click _Manage and Explore_ on another space
+ Try to switch to the home space and it will take you back

**Comment by tanriol** [comment]
I haven't managed to reproduce the problem in the live preview. However, note that the "Manage and Explore" context menu entry on another space is useless with this feature because it causes a space switch and then a room switch to the remembered one.

**Comment by SimonBrandner** [comment]
Yeah, this _is a bug_

**Comment by tanriol** [comment]
Also I'm not sure how to get out to normal state now - "Clear cache and reload" does not seem to kill this remembered room and your fix is in the save path, not load, so it probably won't do that. Looks like I'll need to clear site data completely.

**Comment by SimonBrandner** [comment]
Once again I am really sorry about this. Hit F12 → Go to Storage → Go to local Storage → And delete everything that begins with `mx_last_viewed_rooms_`


![Screenshot_20210420_161839](https://user-images.githubusercontent.com/25768714/115411789-15840d80-a1f4-11eb-92fc-696e6f9c0d4d.png)

**Comment by SimonBrandner** [comment]
If anyone has any further problems with this, please visit [this room](https://matrix.to/#/#spaces:riot.ovh?via=matrix.org&via=dendrite.matrix.org&via=envs.net)
