### ISSUE TITLE
Viewing a member of a space and Exploring Rooms of another space causes wrong member info to be shown

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17019]
The member info is of the previous space, assuming the user you were viewing is not a member of the space you switched to.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/16911

**Comment by niquewoodhouse** [comment]
@turt2live would you mind detailing the steps taken to make this happen please?  

eg 1 - go to space A 2- open members etc

Thanks

**Comment by SimonBrandner** [comment]
This can't happen anymore with the new changes, I believe
