### ISSUE TITLE
Auto-switching to rooms in spaces is disorienting/broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17026]
It's also unreliable if you are viewing a favourite room and you try to navigate to a different space

**Comment by turt2live** [comment]
I can no longer go to my home space because of this.

**Comment by SimonBrandner** [comment]
Is there any chance you are experiencing [#17017](https://github.com/vector-im/element-web/issues/17017)?

**Comment by turt2live** [comment]
Yes, exactly that title. I have Matrix HQ favourited, and it was the last room I had selected in the Home space. Now when I click the Home space it throws me into the Official Test Space (because it has HQ), which then throws me into an Element Company space (which doesn't have HQ). 

It seems this has regressed even further in the last 6 minutes to where I can't even get at the test space: I am always thrown to the Element Company space. 

fwiw, much earlier today I also ran into an infinite loop where it kept throwing me between two spaces and would not break. I had to forcibly log out of that device by deleting the session because the app was unable to respond to the signout button press. Clearing cache did not work.

**Comment by SimonBrandner** [comment]
Ahh, I am sorry for this. I can't really reproduce this behaviour. There is probably some logic in how switching rooms/spaces that cause this to break. Something similar to the previous issue but a bit more complex I assume. You should always be able to delete the data in Local Storage (`mx_last_viewed_rooms_...`). Should I revert/hide behind a setting/something else?

**Comment by turt2live** [comment]
it would be caused by something deep within https://github.com/matrix-org/matrix-react-sdk/pull/5795 - personally, I find the behaviour of that PR highly disorienting even when it's not autoswitching rooms for me. 

It feels like a race condition in the dispatches at least. Some logging around that if/else ladder would show where it is trying to go or do. I think the easiest reproduction case is to have a favourited room that is also in a space, then go to the Home space, visit the favourited room, and switch to some other space. Then, try to return to the Home space.

**Comment by SimonBrandner** [comment]
I will do some debugging in the afternoon (I have school in few minutes). Is there anything I should do in the meantime? (I feel like I've caused a big problem and I am not really sure what I should do)

**Comment by turt2live** [comment]
it's probably fine for now - develop isn't exactly meant to be stable. I've also already brought it up internally, so in theory it should be picked up by someone if needed for a fix sooner.

What you can't see is the two sets of logs I've attached to this: one showing the infinite loop, and one with the broken behaviour described here. Might help investigations for the team members (unfortunately I can't in good conscience upload my logs here for everyone to see).

**Comment by turt2live** [comment]
I think this is actually because there's a second bit of unrelated code which causes the intent to be lost. Somewhere we have a bit of code to auto-select a space based on the room you've clicked on, and that is most likely racing with the code which tries to restore your last room.

**Comment by SimonBrandner** [comment]
> I think the easiest reproduction case is to have a favourited room that is also in a space, then go to the Home space, visit the favourited room, and switch to some other space. Then, try to return to the Home space.

I don't think I can repro this. It goes to the last viewed room in the home space :thinking: Can anyone else?
