### ISSUE TITLE
New lightbox mouse wheel zoom too agressive

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#17037]
### Description

Zooming the image by mouse wheel shows it in maximal/minimal zoom. Single wheel step should do the same thing as (+) and (-) buttons.

### Steps to reproduce

- open the lightbox clicking an image
- scroll mouse wheel one step up
- image is shown in maximal zoom
- scroll mouse wheel one step down
- image is shown in default size

Maximal/minimal zoom is ok when clicking the image by left mouse button, but mouse wheel should behave more fluently.

### Version information

- **Platform**: Element Web 1.7.26-rc.1
- **Browser**: Firefox 89b2
- **OS**: Windows 10
- **URL**: private homeserver

**Comment by SimonBrandner** [comment]
https://user-images.githubusercontent.com/25768714/115703722-c14f6980-a36a-11eb-810e-c88937d54564.mp4

Hmm, weird. Everything works fine for me

**Comment by SimonBrandner** [comment]
I can repro on Chromium :thinking:

**Comment by waclaw66** [comment]
Reproduced on Firefox 90a1 and Chrome 90

> 
> 
> I can repro on Chromium 🤔

**Comment by SimonBrandner** [comment]
@waclaw66, could you please confirm that everything works [here](https://deploy-preview-5904--matrix-react-sdk.netlify.app/)?

**Comment by waclaw66** [comment]
Yes, it works perfectly now! Thanks.

> 
> 
> @waclaw66, could you please confirm that everything works [here](https://deploy-preview-5904--matrix-react-sdk.netlify.app/)?
