### ISSUE TITLE
New lightbox navigation buttons shown over room buttons

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#17036]
### Description

New lightbox navigation buttons are shown over room buttons, they're mixed without background dimmed.

![obrazek](https://user-images.githubusercontent.com/15554561/115659764-5470ab00-a33b-11eb-84de-222262d14397.png)

https://github.com/vector-im/element-web/issues/17014#issuecomment-824553695

### Steps to reproduce

- just click the image

### Version information

- **Platform**: Element Web 1.7.26-rc.1
- **Browser**: Firefox 89b2
- **OS**: Windows 10
- **URL**: private homeserver

**Comment by SimonBrandner** [comment]
I can repro on RC
