### ISSUE TITLE
New image lightbox should zoom to 100% on image click

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#17049]
At the moment, the new image lightbox seems to zoom to an arbitrary 300% when clicking the image, which is somewhat surprising compared to other image views, such as browsers when they display an image file.

I think it would be more natural to match the behaviour of other image viewers:

* For small images that fit in the viewport, display them at 100% by default, and clicking the image is disabled
* For large images that would overflow the viewport, shrink to fit by default, and enable clicking the image to toggle between 100% and shrink to fit

**Comment by SimonBrandner** [comment]
@niquewoodhouse, do you have any thoughts on this? I think I _might_ be able to do something like this but I am not 100% sure (css can be weird :D)

**Comment by SimonBrandner** [comment]
I've created a draft PR. It seems to work great, there is just one thing missing - the max and min zoom is calculated based on the size info from the event but it seems that this data can be missing. I am not really sure what to do in that case
