### ISSUE TITLE
Clicking a room link pointing to a room in another space opens the context switch room instead

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#17047]
### Description

A message in my Home space links to a room in another space. I click it, and see very briefly the room I wanted flickering as selected, but before I can or see anything the context switcher kicks in and selects the room I was in last I visited that space.

Even more confusingly, if I click "Home" again immediately, without selecting the room I actually wanted to go to, the room view changes to the room I wanted to go to, even though it's not even in the Home space.

### Reproduce

(starting situation)
#room1:domain.tld is a room not in any space
#room2:domain.tld is a room in a space A
#room3:domain.tld is the room I recently visited in space A

* #room1 has a message that links to #room2. I click it.
* space A is made visible, but instead of room2, I get room3 in the room view

Expected to see room2.

Bonus confusion: if I click "Home" space before selecting room2, room2 becomes visible but I am now in Home which does not have room2.

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: 2021042201

**Comment by t3chguy** [comment]
This should be fixed in the 2021042301 nightly and develop. Please reopen if it isn't.

**Comment by jaywink** [comment]
Yay! @t3chguy is the "random room chosen on context switching" also fixed (ie not after a link, but possibly related)? I just noticed (new rageshake) that if I navigate to a very not related space, lets call it space B, I also get room2 from space A in my room view sometimes, a lot later after viewing many other rooms :thinking:

**Comment by t3chguy** [comment]
The room chosen on context switch should be the last one you viewed in that space, is the issue you are having on develop or yesterday's nightly?

**Comment by jaywink** [comment]
> The room chosen on context switch should be the last one you viewed in that space, is the issue you are having on develop or yesterday's nightly?

Yesterdays nightly. Cool, I'll reopen once a nightly comes up if I see it again, thanks.
