### ISSUE TITLE
"Low priority" rooms revert to "Rooms" when included in a space

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#17040]
### Description

A room that has been set to "Low priority" in the room list is shown under the standard "Rooms" category when viewed as part of a space.

### Steps to reproduce

* Have a room that you set to low priority
* Enable spaces labs flag
* Join a space that includes that room
* Click on the space

Describe how what happens differs from what you expected.

The room shows up under "Rooms", not "Low priority"

### Version information

- **Platform**: web (in-browser) or desktop? Desktop

For the desktop app:

- **OS**: macOS 11.2.3
- **Version**: Element Nightly version: 2021042201

**Comment by t3chguy** [comment]
What happens when you go on the menu of that room within Rooms?

Is it shown as Low Prio there?
![image](https://user-images.githubusercontent.com/2403652/115707365-98c57080-a366-11eb-9db5-61d9f9a3e6bc.png)

**Comment by clokep** [comment]
Hmmmm, it was not shown as "Low Priority" in that list, although clicking it did move it down there.

Now I'm questioning whether I ever had it as low priority or not. Flipping back and forth between labs and non-labs didn't seem to do anything and I do have *other* rooms that are properly listed as low priority. So maybe I just fat-fingered something at some point. 😢 

I'm going to close this unless I can come up with proper STR.
