### ISSUE TITLE
DMs shouldn't light up spaces

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17044]
![](https://i.imgur.com/9FLNwuV.png)

**Comment by t3chguy** [comment]
favourites & invites also light up related Spaces & Home fwiw

**Comment by turt2live** [comment]
I was honestly not expecting such a hostile reaction to this... The problem is that a DM with someone who is in all the subspaces makes the entire space panel useless: the notification state is completely overridden, which means my only option is to deal with that DM before I can deal with the subspaces. This leads to an unhealthy expectation that DMs are higher priority than the rooms, which further leads to notification burnout and fatigue.

We should not be prioritizing DMs as a workflow.

**Comment by t3chguy** [comment]
The current plan for Beta is to only show DM notification dots on `Home` and never on Spaces.
This may change with feedback after dogfooding.
