### ISSUE TITLE
Logs are filled with !room does not have a create event

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17054]
This seems to be every time a new message comes in - are we calling getVisibleRooms() too often?

**Comment by turt2live** [comment]
the room IDs in my logs are expected to produce this warning, by the way. The problem is that it's a sign of potential inefficiency somewhere in the code.

**Comment by ara4n** [comment]
dup https://github.com/vector-im/element-web/issues/17077 (which has logs)
