### ISSUE TITLE
Option to automatically convert pasted images to avif

### ISSUE THREAD

**Issue by Destroyer** [vector-im/element-web#17053]
#### Is your suggestion related to a problem? Please describe.
Uploading screenshots from desktop often results in png files that are multiple MBs in size

#### Describe the solution you'd like.
Have a setting to optionally convert images to avif before sending

#### Describe alternatives you've considered.
Other formats like older webp are also an option but browsers are already starting to support avif.

**Comment by SimonBrandner** [comment]
@Destroyer, does [#14047](https://github.com/vector-im/element-web/issues/14047) cover your issue?

**Comment by Destroyer** [comment]
It does, closing this issue then.
