### ISSUE TITLE
Desktop app should not tell user to use desktop app to search encrypted messages

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#17051]
Related: #16721 #16636 #14229 #16568

Not #15715

https://github.com/matrix-org/matrix-react-sdk/pull/5806 which was part of the fix for #14229 didn't actually fix the whole issue. In Settings there is now a better error message telling you that something broke which is great but most people are not looking at Settings to see if something went wrong.

Most people are just trying to search for a message and they see the same confusing message that has always been there "Use the Desktop app to search encrypted messages". There is no hint that the problem isn't the app you are using but rather a problem with the message searching feature.

This issue is not about preventing message search from breaking. This issue is about giving a better error message when it does break.

<img width="585" src="https://user-images.githubusercontent.com/5855073/115899156-08e5fc00-a424-11eb-88e0-a54df6b2df10.png">

**Comment by delijati** [comment]
Maybe i'm overlook something, but why do I need the Desktop app at all to search in encrypted messages?

The Desktop app is only a wrapper via Electron:

> Since this package is just the Electron wrapper for Element Web, it doesn't contain any of the Element Web code,

**Comment by t3chguy** [comment]
The Desktop app has an Element Web instance embedded, but it also includes Keytar and Seshat. Seshat is a secure message index, which is what powers encrypted message search. Browsers don't support anything like that and Seshat can't be used in a browser due to lack of encrypted-at-rest indexes/sqlite and threading

**Comment by delijati** [comment]
Yup found this https://github.com/vector-im/element-web/issues/16483#issuecomment-785057003

**Comment by hex-m** [comment]
For others who end up here: You can fix this in `Security & Privacy` -> `Message search` -> `Reset`

> This issue is not about preventing message search from breaking.

But which one is? All linked issues are closed.

**Comment by aaronraimist** [comment]
@hex-m you can create one

**Comment by hex-m** [comment]
I don't have the problem anymore (and don't know how to reproduce it) but if it comes back I'll create an issue with logs.

**Comment by whtshername** [comment]
I had the following error under 

> For others who end up here: You can fix this in `Security & Privacy` -> `Message search` -> `Reset`
> 
> > This issue is not about preventing message search from breaking.
> 
> But which one is? All linked issues are closed.

This fixed the search issue for me. 
The settings showed the following error, maybe this helps to reproduce/fix the issue in general

![image](https://user-images.githubusercontent.com/17835323/123402491-13e61580-d5a8-11eb-8f79-aed468a58bd2.png)
