### ISSUE TITLE
Copy and/or QR-code for room address

### ISSUE THREAD

**Issue by dacoex** [vector-im/element-web#17057]
#### Is your suggestion related to a problem? Please describe.
I wanted to remove / leave some room but keep their address for later.
This I wanted to copy the room address to a external file.
This is currently not possible.

#### Describe the solution you'd like.
A copy to clipboard & QR-code in the field Room Settings → Published Addresses

It should be similar like in the "Share Message" dialogue.

#### Describe alternatives you've considered.
No exsting

#### Additional context
![element - issue - Screenshot_20210424_153620](https://user-images.githubusercontent.com/8660305/115960899-7c126f80-a503-11eb-99ba-0ed0e0aa4033.jpg)
![element - issue - Screenshot_20210424_153729](https://user-images.githubusercontent.com/8660305/115960906-816fba00-a503-11eb-9894-dcd2aa5b9631.jpg)

**Comment by SimonBrandner** [comment]
You can already share a room in the right panel. Is that what you're requesting? 
![Screenshot_20210424_155949](https://user-images.githubusercontent.com/25768714/115961295-1b406280-a516-11eb-9568-3e8b0072b516.png)

**Comment by dacoex** [comment]
@SimonBrandner Thanks for the very swift answer.

I forgot to mention that this issue relates to Element-Desktop
There is no way to file issues specifically for it.

When clicking on the info button, I can only invite others.

**Comment by SimonBrandner** [comment]
> I forgot to mention that this issue relates to Element-Desktop
There is no way to file issues specifically for it.

Issues for Element Desktop should be filed here

> When clicking on the info button, I can only invite others.

I am not sure I understand... There is a little back button maybe you missed that?

![Peek 2021-04-24 16-30](https://user-images.githubusercontent.com/25768714/115962172-68263800-a51a-11eb-9364-1800147df9b3.gif)

**Comment by dacoex** [comment]
> I am not sure I understand... There is a little back button maybe you missed that?
Oh, yes. how embarrassing!

Using a light theme, die is not very visible.
Although I I have no accessibility problems, I imagine others may have also troubles.

I think the actual reason why I overlooked it:
The problems was that the sub-menu status persists across sessions.

Explanation:
* I go to Room Info --> click on "X nos. people"
* close Element Desktop
* reopen
* I go to Room Info
* it shows me the nos of participants in a room and not the Room Info menu.

An improvement would be to always show the top-level entries of the Room Info menu after a re-start of the program.

BTW, thanks for your patience, support & will to assist. Really appreciate it! On a Saturday!

**Comment by SimonBrandner** [comment]
No problem. Let's close this and open a new issue about improving accessibility as this one is already quite flooded
