### ISSUE TITLE
Qr code features similar to wechat

### ISSUE THREAD

**Issue by artiblaster** [vector-im/element-web#17060]
Examples:
1. Being able to add a contact via scanning their QR code on their device (snapchat, instagram seem to do this)
2. Being able to join rooms by scanning a QR code. This wouldn't be too useful in western countries afaik, Yet. But eventually, this could be used in like restaurants, businesses, women's shelters, college clubs to get people to join their rooms
3. Super down the road, it enables possibilities like using QR codes to pay and buy via element. (You can pay for products in vending machines by scanning corresponding QR codes via wechat)
4. In general, having a QR scanner built in or optional as a widget in the element camera function opens up future possibilities. Some phones are adding this to their default camera functions. 

Edit 2: Wechat and these qr features are mostly used in china

**Comment by t3chguy** [comment]
Which of those apps support scanning qr on your laptop or desktop webcam? This repo is about Element Web, for the mobile apps there are different repos.

**Comment by artiblaster** [comment]
Oops, I will take it to another repo. Unless someone thinks laptop qr scanning can somehow pick up XD

**Comment by artiblaster** [comment]
Which repo do i take it too? both android and ios? Or is there a general mobile repo?

**Comment by SimonBrandner** [comment]
Both Android and iOS

**Comment by artiblaster** [comment]
I have a suggestion for an item to add to shop.matrix.org, where do I suggest it?

**Comment by t3chguy** [comment]
Not on the element web repo
