### ISSUE TITLE
Prioritize room aliases to room descriptions in search

### ISSUE THREAD

**Issue by DerMolly** [vector-im/element-web#17065]
### Description

While searching for our room on matrix.org (#hedgedoc:matrix.org) the only search result is our dev room (#hedgedoc-dev:matrix.org), because the string `#hedgedoc:matrix.org` is included in the room description.

![image](https://user-images.githubusercontent.com/3978662/116080469-68990d00-a699-11eb-83c0-1fd203a3c79c.png)

### Steps to reproduce

- click on the compass icon next to search bar in the upper left corner
- enter `#hedgedoc:matrix.org`
- only get a result for #hedgedoc-dev:matrix.org 

Describe how what happens differs from what you expected.

Prioritize room aliases to room descriptions.

### Version information

- **Platform**: desktop and web

For the web app:

- **URL**:  app.element.io

For the desktop app:

- **Version**: nightly

**Comment by DerMolly** [comment]
We just replaced the direct links with aliases from our website for the time being…

**Comment by t3chguy** [comment]
This is filtered & sorted by the server, not by Element. I suggest opening a Synapse issue

**Comment by DerMolly** [comment]
Oh thank you.

> I suggest opening a Synapse issue

Will do

**Comment by DerMolly** [comment]
The issue at the synapse repo https://github.com/matrix-org/synapse/issues/9883
