### ISSUE TITLE
Attempting to add a group of rooms to a space only ends up adding a subset of them

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#17070]
### Description

I attempted to add probably ~30 rooms or so to a space (starts with `!KicHwjOz` in logs) and only 10 were added. I tried again with about 8 or so spaces, and only 2 were added. I'm using the little `# rooms` text to confirm these:

![image](https://user-images.githubusercontent.com/1342360/116118971-cd626080-a6b5-11eb-966a-1eb9ce8c2d23.png)

but I can also see that some rooms I know I tried to add aren't making it in.

### Steps to reproduce

- Try adding a healthy number of rooms to a space
- See that only some rooms were added to the space.

These rooms are not part of any other space (unless you count Home).

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: Nightly 2021042601

**Comment by anoadragon453** [comment]
I'm not sure if this is a case of adding a bunch of rooms and then only a moment later clicking off the Manage Rooms page to look at other rooms, thus cutting the operation short.

**Comment by t3chguy** [comment]
Sounds like synapse rate limited you buy by closing the thing you didn't get shown the error.

**Comment by t3chguy** [comment]
From the screenshot it also looks like you hit https://github.com/vector-im/element-web/issues/16835
where Synapse doesn't offer any pagination mechanism to go beyond the 50 spaces it returns

**Comment by anoadragon453** [comment]
Yep, I think you've hit the nail on the head for both issues. Thanks!
