### ISSUE TITLE
numbers are displayed as a black box

### ISSUE THREAD

**Issue by Graveboda** [vector-im/element-web#17074]
Hallo, 

<!-- ![grafik](https://user-images.githubusercontent.com/83266276/116190280-a3975100-a72a-11eb-9a1f-460acf1a5ef3.png)

I work with W10 Pro
Browser: Firefox newest version
what is the problem when all the numbers in all the old and new news are suddenly shown as a 
are displayed as a black box. The issue is only on my notebook. My tablet works fine.
![blackbox](https://user-images.githubusercontent.com/83266276/116190910-b8c0af80-a72b-11eb-9071-c8c3cb4c8400.JPG)

**Comment by SimonBrandner** [comment]
@Graveboda, please fill in the issue template

**Comment by SimonBrandner** [comment]
I will close this as I can not reproduce this and there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.
