### ISSUE TITLE
Graphical interface & reply icons

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [vector-im/element-web#17076]
Hi there,

So I haven't used Element often even though I want to. This is on PC, Win 7.

One of the major reasons, is I find it very hard to see where one person's comment ends & the other person's comment begins.

I've been online for a very long time & consider myself both a nettie & entrepreneur.

For me, it looks like everything just bleeds together. I am using a f.lux so I have a bit of a blue screen, ut I'm able to see other sites well enough.

Some of the comments have different background colors, but they make no sense to me & they seem to have no rhyme or reason to them.

And lastly, the reply bottom is very far off on the right & it makes it very hard to get to. I prefer them under the text.

I can't tell you how many times I've thought I had the right reply button & I didn't, I ended up grabbing the one from a different line of text /c it seems every single sentence has one instead of the one comment or something.

Is there any way you can fix these things so I can start using Elemenet more & I can feel comfortable enough to invite others?

I'm sure I'll have more suggestions, but that's about it for now.

Thanks

**Comment by SimonBrandner** [comment]
I feel like this issue is a collection of multiple problems. Also, it isn't super easy to know what exactly are you talking about. Could you perhaps include some screenshots and split this into multiple specific issues?

**Comment by ILoveSkilledCoders** [comment]
I'm doing my best to try & articulate here, so bear with me please LOL

https://mega.nz/file/5xUC2DQR#k1zQ5toBMjT3SIYWvnZA8vM1rdcmk6gNbi2cBW9C1fw - this is showing how the reply buttons are often very close together & I end up clicking on the wrong one.

If I start reading left justified, so my vision is on the left. Then I have to look all the way over to the right & mouse-over all over the place trying to find the reply keys & the right one at that.

https://i.imgur.com/t8wk5Oe.png - very busy. Yes there are different colors, but everything is so close together, that it's hard for me to read things quickly & know who's writing what.

https://i.imgur.com/pl1PWu6.png - then if there are replies it's even harder due to greyed out text that confuses me.


Thanks

**Comment by SimonBrandner** [comment]
Okay, so what I gather from this, these are the issues you have (I've included links to issues that I think cover your problem):

+ The message action bar (react, reply, options) buttons are too small and too close together - [#16480](https://github.com/vector-im/element-web/issues/16480)
+ The message action bar is on the right - [#16480](https://github.com/vector-im/element-web/issues/16480)
+ The messages bleed too much together - [#4635](https://github.com/vector-im/element-web/issues/4635)

Is this all? Have I missed something? Let me know if those issues cover your problem or if you have different ideas for a solution. 

Also, the Element UI/UX is fairly similar to Discord/Slack which is kind of a standard. Do you feel the same way about them or is this an only Element thing?

([btw, you can drag an image into the text field on GitHub. They then become a part of the text, which makes it easier for others to read your comment](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests))

**Comment by ILoveSkilledCoders** [comment]
> Okay, so what I gather from this, these are the issues you have (I've included links to issues that I think cover your problem):
> 
> * The message action bar (react, reply, options) buttons are too small and too close together - [#16480](https://github.com/vector-im/element-web/issues/16480)
> * The message action bar is on the right - [#16480](https://github.com/vector-im/element-web/issues/16480)
> * The messages bleed too much together - [#4635](https://github.com/vector-im/element-web/issues/4635)
> 
> Is this all? Have I missed something? Let me know if those issues cover your problem or if you have different ideas for a solution.
> 
> Also, the Element UI/UX is fairly similar to Discord/Slack which is kind of a standard. Do you feel the same way about them or is this an only Element thing?
> 
> ([btw, you can drag an image into the text field on GitHub. They then become a part of the text, which makes it easier for others to read your comment](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests))

Thanks for getting back to me Simon & please don't take offense to anything I say below when I vent as I'm not just talking about Element, but the net in general as I'm a nettie & netrepreneur.

I realized when I restarted my computer that I left this part out of my message.

"I don't know how to design it, all I know is what I do or doing like when I see a design.

If I could design, I'd be offering that to my clients LOL

I can maybe ask around if you want me to.

And I certainly can't stand FB, but it's actually more well laid out than ever before.

I remember when I first started on FB, I could never find anything.

Even MeWe is very hard for me to see clearly & if I have to scroll up to see see what people said before, that's a mess, plus I can never tell who's comment belongs to whom. With fakebook due to their nested look, most of the time I can tell who's responding to whom.

Now nesting isn't great unless you are part of that conversation, but I'm not sure we can have both seeing who's commenting to whom & everyone seeing everyone's comment.

In a forum you can, but not everyone quotes everyone, but most people on forums are smarter than on SM & they do quote.

I was a forum addict at one point years ago. 

Like I said, I also think it's due to your background panels being all grey, then slightly darker, then light, then switching again to an off white. It's just so dull, not inviting & makes things harder to read.

Button colors are generally very important from a GUI standpoint & getting people to click.

I preferred the look of the old fakebook, not the new version they came out with last year, but my eyes have adjusted to the stark white & then the sharp blue.

But the buttons are also sort of 3D so they are easier to find, click on, etc.

And I'll tell you right now, I HATE sites that have no scrollbar or arrow at the top & bottom of the scrollbar.

I use a very old mouse with no wheel & I will literally leave a site when there's no scrollbar & I will bitch to all hell.

I left Minds b/c of that.  I couldn't message, see buttons, do simple things b/c they removed the bar from certain areas of the site. I really don't know why designers have gone this route. 

I've been online for years. Since '94, but f/t since '98. 

While the design of sites back then were not great, at least things were easier to manage & then after about 5 years things got better.

Even now I can't stand scrolling vertical 10 miles down to find things. I feel like I'm falling into the abyss.

And sites now look way uglier than they did before IMO.

Your scrollbars are very thin & you have 2 side by side so I always end up grabbing the wrong one (just so you know.)

So far I've been able to make due with your scrollbars, but it takes up more of my time grabbing the wrong one. And I think you are missing the top or bottom arrow right? I don't have Element open right now.

As for Discord, I'm not in love with Discord either, especially their bugs with their emojis, but their buttons are darker, thicker & when I reach out to grab them, they don't jump as much around.

I don't have time to look at your other threads right now, ut if others are saying the same thing, my suggestion is to find someone who is really good at GUI & design & then to take an hour & come up with some suggestions.

I hope that helps & I appreciate  your attention to this matter.

**Comment by turt2live** [comment]
Thank you for the detailed report and explaining the experience you've had with Element. Unfortunately an issue of this size isn't something we can easily digest into our development and design processes, and it's not entirely clear where the issues stop and start, making breaking them out ourselves even harder.

I can appreciate that Element is not perfect or amazing in every way: a lot of our UI is still developer-driven UI from the early days of the application. We have a full time design team now though, and have been using them for a couple years to improve the overall look, feel, and experience of the app. Some areas, like the timeline, have not received as much attention as other areas and are easily still lacking in modern design.

We are working to improve every area we can, though with a small team we are having to prioritize certain features over others. We tend to improve the usability of part of the app when we make changes in a nearby area (such as when we're implementing a new feature), though time isn't always on our side so we may opt to put improvements on a backburner.

Overall, I think your points are aligned with what our design team considers when redesigning or making improvements to parts of the app: they try to reduce noise, increase productivity, and decrease surprises/frustrations. This includes not being able to grab the smaller scrollbars or everything appearing to be one tangled mess of words.

I'm going to close this as it's not in a digestible state, but I'd like to reassure you that the feedback you've raised is considered when we make changes, though making improvements can be a slow-moving process at the moment.

**Comment by ILoveSkilledCoders** [comment]
Hi there,

So I know you said you weren't going to change anything, but I wanted to show you more.

My website coder & I were talking about sites that have encryption & I told him the only one is yours, but I told him that I have a huge problem with the interface & I went to show him.

He had to run, but he did figure out what most of the issues are.

Here's what I wrote up based on what he saw.


	1. There are issues with nesting replies to comments. If you look at this example, what, he's replying to himself?? https://i.imgur.com/y6scahI.png We couldn't find any example of a reply to someone's reply where this wasn't an issue & so far all I see when someone replies to a comment is that there's no grey text that says "In reply." That only shows up when you reply to someone else's reply.
	2. Then he showed me that there's quotes & I was wondering why are people quoting instead of replying because you can't highlight text & hit quote & have it ONLY quote just that text.

I think the quote option is very confusing. I really don't see the difference.

Anyway, I went to quote someone just to test & look at how the text has no room/padding/space in the text field & around the text. I started complaining about why my text was touching the YT link above it which is when Chris explained why. https://i.imgur.com/vyIW7Z7.png
	3. Then that YT link above for some reason, had an X & I thought if I clicked on that X it would delete my test quote text, but instead, it deleted the entire message.

Turns out it was just the preview that got deleted, but why even offer that option? I thought the entire comment deleted.

Chris likes that option & I get that geeks may like that, but people like me who are on tons of SM sites, that's NEVER an option, so I would have no idea that's what happened, plus it's a fact that people click on images way more than just links. Most of the time people can't even see links clearly if the preview isn't there. 

Having that text there was confusing & another time there was a X & it delete the test text in the text filed, but that was only because I hit reply & not quote.

Consistency is needed in everything otherwise it's confusing.
	4. Now see here, I can't even follow who said what to whom & my website coder can't either. https://i.imgur.com/Avl1rqD.png
	5. So here's another example where everything is confusing & I can't follow anything. https://mega.nz/file/tstihAqQ#YpXDt0nqssXhqr6Prd_Yn3SaNizOp8Y4Yr5Yqsw_dOc

Chris eventually figured it out, but I certainly couldn't, & if a person can't see at a quick glance what is going on, then they won't want to stay on your site & again, that's why I never go on there even though I want to.

The text lighter said was quoted, not replied to which I find very confusing, & then spreadthis asked who said that which was fine, but THEN oneno replied to spreadthis, but it actually says he replied to lighter. And I didn't even get that his reply was the depopulation link.

And then at the end lighter replies & yet this entire time what he originally said never gets pasted along with everything else as the conversation moves forward.
	6. Your handle to size the window is so close to the scrollbar that it constantly pops up & confuses me as to which is the sidebar. I only found out it was a handle to resize when my website coder told me.
	7. I went to your Element Desktop/web room to try & find this conversation & the conversation I had back in May, part of the conversation was greyed out. Why? When I clicked into it it finally removed the greyed out, but why was it there to begin with?
	8. I can never tell where one comment/reply starts, stops, who it's from, etc.

Thanks
