### ISSUE TITLE
Lots of font problems when uBlock extension is used

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#17079]
The issue started today:

[Screenshot from 2021-04-27 13-25-56.pdf](https://github.com/vector-im/element-web/files/6384143/Screenshot.from.2021-04-27.13-25-56.pdf)

Using Firefox 88.0+build2-0ubuntu0.20.04.1.

I do not encounter the same issue with Firefox Nightly.

Lots of error in the Dev console:
```
Analytics error:  TypeError: NetworkError when attempting to fetch resource. KeyboardShortcuts.tsx:280:25
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix-client.matrix.org/_matrix/media/r0/preview_url?url=https%3A%2F%2Fapp.element.io%2Ffonts%2FInter%2FInter-Italic.9528384.woff2&ts=1619522640000. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Failed to get URL preview: M_UNKNOWN: Failed to download content: ["twisted.web.error.SchemeNotSupported: Unsupported scheme: b'data'\n"]
downloadable font: download failed (font-family: "Inter" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://app.element.io/fonts/Inter/Inter-Italic.9528384.woff2
...
```

**Update** The issue seems to vanish if I deactivate uBlock. Did `app.element.io` somehow end up on a uBlock filter?

**Comment by t3chguy** [comment]
`downloadable font: download failed (font-family: "Inter" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://app.element.io/fonts/Inter/Inter-Italic.9528384.woff2` is the only relevant error there, uBlock has some generic catchall rules we might be tripping.

**Comment by Yoric** [comment]
> That file is indeed missing, so it seems like a bad cache.

Where? Should we get in touch with uBlock developers?

**Comment by t3chguy** [comment]
Looks like that issue was due to a bad deploy, not sue to ublock
