### ISSUE TITLE
gpg signature verification fails

### ISSUE THREAD

**Issue by Loader009** [vector-im/element-web#17071]
easy description:
Using gpg --verify element-v1.7.26.tar.gz.asc fails.
Please upload the correct signature and/or update your gpg key.

v1.7.26
```
$ gpg --verify element-v1.7.26.tar.gz.asc
gpg: assuming signed data in 'element-v1.7.26.tar.gz'
gpg: Signature made Mo 26 Apr 2021 18:58:27 CEST
gpg:                using RSA key E95B7699E80B68A9EAD9A19A2BAA9B8552BD9047
gpg:                issuer "releases@riot.im"
gpg: Can't check signature: No public key
```

v1.7.25
```
$ gpg --verify element-v1.7.25.tar.gz.asc
gpg: assuming signed data in 'element-v1.7.25.tar.gz'
gpg: Signature made Mo 12 Apr 2021 16:32:08 CEST
gpg:                using RSA key 5EA7E0F70461A3BCBEBE4D5EF6151806032026F9
gpg:                issuer "releases@riot.im"
gpg: Good signature from "Riot Releases <releases@riot.im>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: A878 CDF6 6CF4 A9B4 807C  EBE5 7469 2659 BDA3 D940
     Subkey fingerprint: 5EA7 E0F7 0461 A3BC BEBE  4D5E F615 1806 0320 26F9
```

**Comment by HarHarLinks** [comment]
I feel like this relates to the pinned issue #17005 (and transitively #17030)

**Comment by Loader009** [comment]
Yes, you're right.
I'm closing this now.
Thank!

**Comment by karthanistyr** [comment]
Not sure #17005 solves it entirely. Can't find a source for the public key id `A2BAA9B8552BD9047` anywhere at the moment (necessary for validating the signature of release 1.7.26). Any one has any luck ?

**Comment by Loader009** [comment]
I used that link:
https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x712bfbee92dca45252db17d7c7be97efa179b100
copied the text (couldn't use curl - and I am not used to gpg, to set up the keyserver) and imported the key.
After that it was successfully verified.
