### ISSUE TITLE
keyboard shortcut wrongly interpreted when using NEO layout

### ISSUE THREAD

**Issue by Marenz** [vector-im/element-web#17087]
### Description

I am using the keyboard layout neo (https://neo-layout.org). When I press CTRL+X to cut a selected text part, element-desktop asks me if I want to quit. Notable here is that the X key is where the Q key would be on a normal QWERTZ/QWERTY layout.
However, if I press CTRL+Q, it actually does exit the application, without asking for any confirmation..

### Steps to reproduce

- write text in in text field
- select text
- press ctrl+x (using the neo-layout!)
- get confirmation dialog whether you want to quit

Expectation: My written text gets cut and placed in the clipboard.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Ubuntu 20.04
- **Version**: Version von Element: 1.7.25; Version von olm: 3.2.1

**Comment by t3chguy** [comment]
Please update to v1.7.26 where this is fixed.
