### ISSUE TITLE
Pinned messages don't update with edits

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17098]
### Description

2021 evolution of #5358, possibly related.

### Steps to reproduce

- encrypted room
- post message, edit message
- pin message
- edit some more

pin view shows the edited message at the time of pinning (including `*` etc), not the subsequent edits.
please also make it pretty and consistent with the regular view, e.g. (edited) and stuff.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021042701-1

**Comment by SimonBrandner** [comment]
![Peek 2021-05-02 20-17](https://user-images.githubusercontent.com/25768714/116823223-9394cc80-ab83-11eb-862a-195c9d42212a.gif)

I can't repro. Am I following the steps correctly? Can you safely repro?

**Comment by HarHarLinks** [comment]
1. the original issue does seem to have disappeared, I'm now on nightly 2021042901-1. the issue may have appeared because the editing happened not immediately like in the tests, but only several pages of chat later so it may have to do with the usual pinning issue of losing pins that are too far back in (unloaded) history. however I think that shouldn't only be supported for completeness, but also this is actually a common occurrence for pins.
1. in your test, you show the need to refresh pins manually. imo the pinned message should automatically update

**Comment by HarHarLinks** [comment]
I found the original message that prompted me to open this issue (actually i think element loaded enough history after a while to make it appear in pins). it has seen 5 edits (it is a list that got ticked off over the course of a day). currently both the message and the pin do **not** show the latest edit(!), however the edit history does.

i have not been able to repro yet.

**Comment by t3chguy** [comment]
Nique reproduced this in our DM

![image](https://user-images.githubusercontent.com/2403652/125306874-7c165480-e327-11eb-97e0-576c6021e6de.png)

**Comment by robintown** [comment]
I've investigated this a bit, and it should at least be solvable for unencrypted rooms via the /relations API, but missing edits in encrypted rooms seems a bit unavoidable given the lack of server-side aggregations. Threads seem to suffer from the same issue in encrypted rooms, FTR.

**Comment by robintown** [comment]
Apparently I misremembered—aggregations work in encrypted rooms too since relations are unencrypted, so this should be a straightforward fix.
