### ISSUE TITLE
message_send_failed dispatch isn't used

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17091]

**Comment by Palid** [comment]
@turt2live can you add some more details about this?

**Comment by turt2live** [comment]
@Palid what details are you after? It's a dispatch action that's not used.

**Comment by Palid** [comment]
@turt2live What are the problems relating to that dispatch action not being used or what using it will solve/enable. I assume it's just a refactoring issue?

**Comment by turt2live** [comment]
It's just dead code we don't need.
