### ISSUE TITLE
"Some of your messages have not been sent" when switching rooms

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17090]
Right after switching to #synapse-dev, I see this:

![image](https://user-images.githubusercontent.com/5547783/116418027-0fb5aa00-a83c-11eb-9391-b69e200bf054.png)

Which doesn't match any event I've sent or tried to send (15:07 is actually the time I switched to this room).

Observed on latest develop.element.io, with Firefox 87.0. ~Will rageshake.~ Done.

**Comment by turt2live** [comment]
the logs say you sent something, but I have a hard time believing that you tried to send something 212ms after switching to the room... @babolivier can you confirm that?

**Comment by babolivier** [comment]
> the logs say you sent something, but I have a hard time believing that you tried to send something 212ms after switching to the room... @babolivier can you confirm that?

Yep.

**Comment by turt2live** [comment]
@babolivier have you seen this lately?

**Comment by babolivier** [comment]
I haven't

**Comment by turt2live** [comment]
I'm going to close this pending someone seeing it in the wild again. If that happens, please open a new issue with as much detail as possible (given we don't have a reproduction case).
