### ISSUE TITLE
Members list incomplete

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17096]
I just rageshaked about this - I'm in a room created by Philip, and he's not listed in the member list.

The room summary pane shows 5 people in the room, but clicking on that to see the 5 people only shows 4.

**Comment by kittykat** [comment]
I just hit the same issue when joining  a room. I could see ~15 members and after I cleared the cache, I could see >260.

**Comment by babolivier** [comment]
I'm observing this issue again (or at least the variant reported in #25646): in a room I've just been joined, the member count shown in the room's summary is 1, but there are several users in it.

https://github.com/vector-im/element-web/assets/5547783/18c90d30-8bc5-48eb-b5b7-9ba1b1c64cc0

I'm on app.element.io (1.11.38), will rageshake.

**Comment by daniellekirkwood** [comment]
I'm hitting this too - the "people" count in the right-panel is 1 but there are 13 people in the room

**Comment by t3chguy** [comment]
```
2023-08-08T16:53:37.051Z D LL: got 34 members from server for room !JfVnErNVIpzxXQjAHA:mozilla.org
2023-08-08T16:53:37.051Z D LL: RoomState about to set 34 OOB members ...
2023-08-08T16:53:37.051Z D LL: RoomState put in finished state ...
2023-08-08T16:53:37.056Z D LL: telling store to write 32 members for room !JfVnErNVIpzxXQjAHA:mozilla.org
...

No errors

**Comment by babolivier** [comment]
Yeah it's also fixed itself for me, even though I haven't closed my browser (or even the Element tab) since first observing it.
