### ISSUE TITLE
Options to further customize colour scheme

### ISSUE THREAD

**Issue by DrWhiteApes** [vector-im/element-web#17108]
The dark chat theme is quite very dark. Perhaps adding a couple more theme options, especially dark themes, would be nice.

Another option could be to customize the theme to ones own liking with RGB.

**Comment by SimonBrandner** [comment]
There are 14 issues under the [`A-Themes-Custom` label](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AA-Themes-Custom). I believe they cover your issue. See [this](https://github.com/aaronraimist/element-themes), if you want to try out some custom themes.
