### ISSUE TITLE
Some characters displaying as HTML character entities in room list preview

### ISSUE THREAD

**Issue by vurpo** [vector-im/element-web#17101]
![image](https://user-images.githubusercontent.com/6452110/116489006-81254500-a89c-11eb-969f-f9eb871a6b39.png)

This only seems to happen when those characters are character entities in the `formatted_body` (not when it's a simple plain message, for example). The content of the event in the screenshot is:

```
{
    "body": "<ServoFire> I know you can set that to happen in Cura when you slice the file with the print order option",
    "format": "org.matrix.custom.html",
    "formatted_body": "&lt;S​ervoFire&gt; I know you can set that to happen in Cura when you slice the file with the print order option",
    "msgtype": "m.text"
}
```

and it renders as expected (using < and > instead of \&lt; and \&gt;) when viewing the event in the room itself.

Element Web develop (c5f533011bc1-react-d203e8f1294a-js-dc64c34ccb82) on Firefox 88.

**Comment by jaiwanth-v** [comment]
I'll work on this

**Comment by HarHarLinks** [comment]
There are a lot of related issues involving broken previews of html-encoded text, including but not limited to pills #16262, text decorations #16330, newline/whitespace #16169, etc. I would expect these all fall back to not interpreting the html correctly.

**Comment by ara4n** [comment]
this is a pretty embarrassing wart.

<img width="355" alt="Screenshot 2021-08-06 at 12 28 50" src="https://user-images.githubusercontent.com/1294269/128504106-502d93ec-9888-4a5b-9416-74eaa8fbc7dc.png">
