### ISSUE TITLE
Can't forward message to a room in another space

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17109]
### Description

Can't forward message to a room in another space

### Steps to reproduce

- contextmenu -> forward msg
- click on space
- click on room
- nothing happens

which is how I would've expected it to work. is there another way, currently?

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021042801-1

**Comment by HarHarLinks** [comment]
Opening in another, stable element without the labs spaces enabled, i.e. spaces appear as regular rooms, I found that the message is shared to that space-room.

**Comment by robintown** [comment]
Related is #14690 as the forwarding UI needs a bit of an overhaul in general
