### ISSUE TITLE
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD

### ISSUE THREAD

**Issue by sha-265** [vector-im/element-web#17113]
### Description

When trying to run `apt update` I get an error for the Element (Riot) apt repository:
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2850B265AC085BD

I downloaded the new public key according to instructions in the element.io website, but the I still get this error. 

What's going on?

**Comment by turt2live** [comment]
Either https://github.com/vector-im/element-web/issues/16960 or https://github.com/vector-im/element-web/issues/17005

**Comment by sha-265** [comment]
@turt2live as I said I downloaded the new public key, but still it's not working.

**Comment by turt2live** [comment]
It appears you're still referencing the old key in your error. As mentioned on the issues, please use the support room for support

**Comment by sha-265** [comment]
@turt2live you banned me from this channel. I have the f*cking new public key, FFS.

**Comment by turt2live** [comment]
yea, we're not going to tolerate abuse either.
