### ISSUE TITLE
Alt+Up doesn't restore pills in composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17115]

**Comment by SimonBrandner** [comment]
![Peek 2021-04-30 09-39](https://user-images.githubusercontent.com/25768714/116663857-f3c71b00-a997-11eb-96e6-853b49c79223.gif)

I can't repro

**Comment by turt2live** [comment]
Try room pills? I was getting a literal "Matrix HQ" when sending instead of a pill

**Comment by SimonBrandner** [comment]
Yeah, I can repro that
