### ISSUE TITLE
Image view could let the user zoom beyond image size

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17114]
blurry images are kinda the user's fault after a point, but it would help for some cases where people send small screenshots

**Comment by SimonBrandner** [comment]
I feel like this at least partially conflicts with [#17049](https://github.com/vector-im/element-web/issues/17049). I think design will need to take a look at this

**Comment by Trendyne** [comment]
This would make the image view feature much more useful. Blurry images could also be dealt with by setting `image-rendering` to `pixelated` or `crisp-edges` when the zoom is over 100%. Some image viewers (I think the default xfce one) do this by default.
