### ISSUE TITLE
keys backup/restore

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#17116]
Hello. How to setup keys backup for all users remotely? Sometimes users lose sessions and messages encrypted in new sessions.
Where is the backup stored? Can I pick up them from sqlite db for recover?

**Comment by SimonBrandner** [comment]
This is an issue tracker. For questions such as this, it is probably the best to ask in [Matrix HQ](https://matrix.to/#/#matrix:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de) or [Element Web/Destkop](https://matrix.to/#/#element-web:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org)
