### ISSUE TITLE
Users declining a voice/video call is too blunt

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17110]
<img width="1904" alt="Screenshot 2021-04-29 at 16 09 19" src="https://user-images.githubusercontent.com/4626865/116576701-b1ee9400-a907-11eb-9987-0a15aa4a78c9.png">

When another user declines a call, we stop users in their tracks with a very blunt and transactional modal. It would be better to find a softer way to inform users their call is declined.

**Comment by SimonBrandner** [comment]
I feel like the call-related messages should look different compared to the other ones. Are there any designs for this?

**Comment by DantrazTrev** [comment]
To make these call-related messages in the caller view itself. Something like this ( a really rough design)
![image](https://user-images.githubusercontent.com/43457420/118219494-365c1d80-b497-11eb-995e-b47208f17ba9.png)

I reckon this could be of use cause
- It'll be distinguishing the caller related messages more specifically decline
- It'll be less interfering to the rest of the window (Considering the caller view is a part of the window and not the whole, I assume
the current design makes sure we can continue using element during a call. Which this design enhances )

However, I think this shouldn't be used for errors before the call is made. Like the Call not sent, media error, or something like that.

**Comment by SimonBrandner** [comment]
The designs feature call tiles, which I feel like could be the first step to solve this:

![Screenshot_20210514_075113](https://user-images.githubusercontent.com/25768714/118227632-29d0c880-b489-11eb-9a6e-c29fefd312e5.png)

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18138
