### ISSUE TITLE
URLs with umlauts are not always recognized

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#17133]
### Description

URLs that contain german umlauts are not recognized correctly.

![Screenshot from 2021-05-03 10-17-03](https://user-images.githubusercontent.com/16013327/116855013-e65c9b80-abf8-11eb-86e0-2f212b5d2336.png)

The URLs all look good on Element-Android.

### Version information

- **Platform**: tested on web (self-hosted instance) and desktop

For the web app:

- **Browser**: Firefox 78.9.0esr
- **OS**: Debian Bullseye
- **Version**: 1.7.25

For the desktop app:

- **OS**: Debian Bullseye
- **Version**: 1.7.24

**Comment by t3chguy** [comment]
Issue with LinkifyJS 

![image](https://user-images.githubusercontent.com/2403652/116855974-371cc600-abf2-11eb-84ed-1f2c6e8ec80e.png)

**Comment by Flexmaen** [comment]
Doesn't even need to be an Umlaut.

For example:
https://upload.wikimedia.org/wikipedia/commons/d/de/Vischer_-_Topographia_Ducatus_Stiriae_-_460_Waldstein_bei_Frohnleiten.jpg
turns into
![element_link](https://user-images.githubusercontent.com/6330276/123765363-f675bc00-d8c5-11eb-8b4b-3115e7dfe2c6.png)

**Comment by t3chguy** [comment]
@Flexmaen that's a totally different issue. https://github.com/vector-im/element-web/issues/4674
