### ISSUE TITLE
Spaces creation wizard calls named spaces 'Empty room'

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#17146]
### Description

The spaces creation wizard refers to your newly created space as 'Empty room', even when you give it a name:

![Screenshot_2021-05-03 Element Test space](https://user-images.githubusercontent.com/48614497/116929136-ff327480-ac2b-11eb-99bc-f5119740b014.png)
![Screenshot_2021-05-03 Element Test space(1)](https://user-images.githubusercontent.com/48614497/116929304-3acd3e80-ac2c-11eb-8512-fb1719820638.png)

This happens with the creation wizards for both public and private spaces.

### Steps to reproduce

- Press 'Create a space'
- Enter a name for the space
- Continue with the wizard
- See mentions of 'Empty room'

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox 88.0
- **OS**: NixOS unstable
- **URL**: https://develop.element.io/
- **Homeserver**: Synapse 1.32.2 with spaces support enabled

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5933/commits/a7642b2b24476c4edb32409c4709a2eeb6ac444c
