### ISSUE TITLE
Elements Desktop does not launch. It stays in a loading state perpetually at startup.

### ISSUE THREAD

**Issue by jerkstorecaller** [vector-im/element-web#17141]
![image](https://user-images.githubusercontent.com/58572326/116892891-57528200-abfe-11eb-8b20-73c85dd2a185.png)

### Description

Elements Desktop does not launch. It stays in a loading state perpetually at startup.

### Steps to reproduce

- (Obviously these steps are specific to the bug I encountered and won't be reproducible on someone else's PC)
- Launch element.exe 
- Wait for it to finish loading. It never will. The busy indicator keeps spinning, but the rest of UI is completely frozen. There's an Element process using up 25% CPU, that process also has its RAM usage increase/decrease by about 30MB repeatedly.
 
After 10 minutes of waiting, I restarted my PC and tried again, no difference.

I will give additional information which may explain what happened:
I installed Element Desktop on my home PC for the 1st time 10 days ago. It's the only Matrix client/session I have. I used it for a whole week without issues, shutting down my computer every day. 3 days ago, I wasn't home, and logged in to app.element.io using my web browser to access my messages (my home PC was shut down at the time). I skipped all the encryption/verification/signing prompts since I only use Matrix for unencrypted IRC bridge chat. I used it without issues on that day. Today I launched Element Desktop on my home PC for the 1st time since that web session, and it fails to launch. These two sessions may be unrelated, I don't know, I'm just trying to provide context that could help developers.

Other info: I just created another web session on the Element website and could use it without issues.

Logs being sent: no
The UI is perpetually frozen so I cannot capture the bug report.

### Version information

For the desktop app:

- **OS**: Windows 10 64-bit 20H2
- **Version**: 1.7.26.0 

Since the UI is frozen, I got the version by right-clicking element.exe and checking the Details tab.

**Comment by JeanPaulLucien** [comment]
UI is webpage. Is it still actual? I'm Windows 7 user and was not similar on my Element versions.

**Comment by t3chguy** [comment]
@jerkstorecaller are you still experiencing this? If so could you send logs from the app console?

**Comment by t3chguy** [comment]
Closing due to lack of requested info
