### ISSUE TITLE
"in reply to" header is missing a space

### ISSUE THREAD

**Issue by Krinkle** [vector-im/element-web#17147]
### Description

The "in reply to" header appears to almost always be missing a space.

![capture](https://user-images.githubusercontent.com/156867/116930562-d32ce880-ac57-11eb-95a2-926938f200f8.png)

It is also very often attributed to `undefined`, but that's its own issue, and might be specific to the room being bridged with a Slack channel.

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce
…

### Version information

- **Platform**: Web, in browser.

For the web app:

- **Browser**: Firefox 84, latest stable.
- **OS**: macOS
- **URL**: <https://wikimediafoundation.element.io/>

**Comment by SimonBrandner** [comment]
This looks very odd to me. I've never seen this with Matrix replies, so this looks like a thing specific to the bridge. This doesn't even look like a Matrix reply. Is there any chance this is completely generated by the bridge? 

(someone please correct me if I am missing something)

**Comment by t3chguy** [comment]
Yup this is definitely a malformed reply fallback, this needs to be reported to the repo of the client/bridge which sent that message, not the rendering client.

**Comment by SimonBrandner** [comment]
I assume we can close this then
