### ISSUE TITLE
[Desktop] Missing username/password log-in option (only SSO available)

### ISSUE THREAD

**Issue by kvithayathil** [vector-im/element-web#17154]
### Description

Missing the ability to sign in to the Desktop app with an existing Matrix.org username/password. I was able to sign in successfully on the web and on mobile.

#### How it appears on desktop:

<img src="https://user-images.githubusercontent.com/1056073/116961133-7e499c00-ac70-11eb-9f56-1ff7b475097d.jpg" alt="Desktop screenshot with missing sign in fields" width="600"/>

#### How it appears on web:

<img src="https://user-images.githubusercontent.com/1056073/116961556-a4bc0700-ac71-11eb-80d6-95fbbf57e41f.png" alt="Web screenshot with username/password fields" width="600"/>

### Steps to reproduce

- Install v1.7.26 on Windows
- Open App
- Try to sign in with an existing Matrix.org username/password

### Version information

- **OS**: Windows
- **Version**: 1.7.26

**Comment by turt2live** [comment]
It appears as though you're using Riot on the desktop, which is a very old version of Element to say the least. The protocol for login changed some time ago, and Riot would not have had that change.

Do you get the same issue when using Element on the desktop? (you may have to update your shortcuts)

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Comment by joyeusenoelle** [comment]
Late to the party, but: I had this issue with Element (not Riot!) 1.7.10 under Pop!_OS (a fork of Ubuntu) 20.10 with X11 and Gnome 3.38.3. For whatever reason - perhaps related to #16880 ? - I was logged out a few days ago, and when I tried to log back in, it only offered me the option to use SSO.

Fortunately, it turns out that updating to Element 1.7.29 fixed the problem. :)
