### ISSUE TITLE
Spaces no longer take up full width of panel

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#17158]
### Description

![Screenshot_2021-05-04 Element Duo](https://user-images.githubusercontent.com/48614497/117001970-fb950100-acb0-11eb-9b2e-e5d24e51a59f.png)

As you can see, the notification dots are no longer aligned due to matrix-org/matrix-react-sdk#5964. Note that despite being on Firefox, I never experienced the visual bug supposedly fixed by that PR.

### Version information

- **Platform**: web
- **Browser**: Firefox 88.0
- **OS**: NixOS unstable
- **URL**: https://develop.element.io/

**Comment by jryans** [comment]
Since this affects a labs feature that is disabled by default, I don't think we'll consider it a release blocker at this time.

**Comment by SimonBrandner** [comment]
> Since this affects a labs feature that is disabled by default, I don't think we'll consider it a release blocker at this time.

I thought the beta is going to be in the next release... But as you have mentioned somewhere it looks like that won't be the case

**Comment by t3chguy** [comment]
Sadly as the FCP has not cleared in time it'll need to be either the release after or an off-cycle
