### ISSUE TITLE
Unable to access private messages

### ISSUE THREAD

**Issue by jojoelle** [vector-im/element-web#17159]
Hi,

I'm writing you because I can no longer use the desktop version of Element - it says my computer is too old (Mac OS X 10.10.5). 
I'm using the web version (on Firefox), but there I cannot read any of my private messages. I can still access to the rooms I'm in. 
I downloaded the app on my phone (Android), but I can't read the private messages there either. If I "verify" the session I can read new messages coming in, but since I need to verify each time I log in, I can't ever read the messages that were sent while I was disconnected. It's also quite inconvenient to have it on my phone because the app is heavy, and I don't have much space on my phone.

It would be great if you could help me, as this is quite unconvenient for my work! Thank you :)

Best,
Joëlle

![Capture d’écran 2021-05-04 à 09 34 07](https://user-images.githubusercontent.com/83652434/117011779-2e90c200-acbc-11eb-98fa-b4614901b7fa.png)

**Comment by t3chguy** [comment]
This is a bug tracker, for support please use https://matrix.to/#/#element-web:matrix.org
