### ISSUE TITLE
font display incorrectly

### ISSUE THREAD

**Issue by zartlike** [vector-im/element-web#17169]
Andriod ver 8.0 
I am not sure this is a bug or something - font display incorrectly when I chatted with others using your web site login -  https://app.element.io
the language used is Burmese, Unicode-complaint font since 2000. Sample for testing - copy and paste from - https://my.wikipedia.org
The other side has home server running on Ubuntu 20.04  displayed correctly.
All red circles display incorrectly in this image below
![Element vector im](https://user-images.githubusercontent.com/79120359/117095546-f9629d80-ada9-11eb-8b69-baba90b3fd62.jpg)

**Comment by robintown** [comment]
A quick search revealed that there are at least a couple different mutually-incompatible character encodings for Burmese script in use today, including Unicode and Zawgyi, and that is maybe what is happening here.

@zartlike Do you know if the font on your phone is a Unicode or Zawgyi font? Are there other sites that exhibit this problem?

**Comment by zartlike** [comment]
Hi robintown,
Only Burmese unicode font from Google - built-in, Noto Sans Myanmar is in the phone.
Can write with that, the other side displaying correctly as both devices has no non-Unicode font- Zawgyi
Thank you

**Comment by zartlike** [comment]
@robintown , I tried today, again through Desktop website instead of App( I haven't install yet on my phone) wrong characters as well as weird ones were displayed. 2 images one from phone and the other from server side for a text - နင်ဂျာ သို့မဟုတ် ရှိနော့ဘိ
![Screenshot_20210506-142529_1](https://user-images.githubusercontent.com/79120359/117242872-7741aa00-ae79-11eb-8a4b-3b16e65e7e36.png)
![home server side](https://user-images.githubusercontent.com/79120359/117242969-a821df00-ae79-11eb-995d-21e748f63018.png)
After installed on my phone App ver 1.1.6 the display is correct ( same text)
![with App](https://user-images.githubusercontent.com/79120359/117246278-b541cc80-ae7f-11eb-9c12-a83b087af69a.png)

I think, your website is configured to force Zawgyi font or some sort when encounter Burmese characters. Probably Zawgyi font requested earlier.
The fact is that Zawgyi font is a illegal, hacked version of Arial font family and having or using it like that of a stolen property. 
Thru with App, it's certain, web site has something to do with it.

**Comment by robintown** [comment]
@zartlike I tried reproducing the problem by testing that exact message on a stock Android device with Opera, but it appears to be rendering correctly for me. Element Web does not use any Burmese-specific fonts such as Zawgyi, and so by all accounts it should be falling back to the Noto Sans font on your device.

Since you have noted that the text displays correctly on Element Android, I would suggest either using that (as is recommended for mobile users) or trying other web browsers. Otherwise, I'm not really sure we can do much here.
