### ISSUE TITLE
Room list is doubly sticking rooms with spaces enabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17163]
Multiple rageshakes.

![image](https://user-images.githubusercontent.com/1190097/117045705-0a89ac80-accd-11eb-86b1-d9fefabbf11d.png)

Appears to happen after searching for rooms in particular.

"Release blocker for spaces", in my opinion.

**Comment by robintown** [comment]
#17125 related

**Comment by SimonBrandner** [comment]
@robintown, open a new issue :)
