### ISSUE TITLE
Space members aren't ordered in an obvious way

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17168]
On my test account the order appears random, but on the account which created the space it seems appropriately ordered as Admins then displayname.

**Comment by t3chguy** [comment]
Strange, it uses the standard MemberList panel for a room, so the ordering should be no different than for a room

**Comment by yannicka** [comment]
I can't reproduce the problem. Do you have an example of an affected space?

**Comment by t3chguy** [comment]
Closing due to not enough information and inability to reproduce
