### ISSUE TITLE
When 1:1 video call is full screen, the dialpad and "three dots" buttons don't work

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#17175]
### Description

When 1:1 video call is full screen, the dialpad and "three dots" buttons don't work

### Steps to reproduce

- start a video call
- go full screen (top right arrows)
- notice the controls work, but the two buttons in the bottom corners don't work

### Version information

Element Nightly version: 2021050501

macos

**Comment by DantrazTrev** [comment]
Can reproduce this one. They do work however are not displayed on the full screen but their positions for the original frame.

Probably has to do something with ` requestFullscreen()` only being called using the `contentRef` in video fullscreen in `CallView.tsx`

```
case 'video_fullscreen': {
                if (!this.contentRef.current) {
                    return;
                }
                if (payload.fullscreen) {
                    requestFullscreen(this.contentRef.current);
```
As `contentRef`  only contains the controls and site buttons for DialPad and hold .

Whereas DialPad and Context Menu are in `dialpadButton` and `contextMenuButton` references.

Could be fixed if we add extra requestfullScreen() calls for the other refs.

Also do we really need DialPad in a video call?

**Comment by SimonBrandner** [comment]
> This might actually be quite hard to solve. It is caused by the way we do context menus. The context menu isn't part of the element that is being full-screened, so the fullscreen view doesn't include the context menu

From https://github.com/vector-im/element-web/issues/18277#issuecomment-888240379

**Comment by anoadragon453** [comment]
`ContextMenu` currently [creates a container](https://github.com/matrix-org/matrix-react-sdk/blob/b8781b75523350c987bd4e8c24535331f2dd3f01/src/components/structures/ContextMenu.tsx#L32-L44) called `mx_ContextualMenu_Container` at the top of the DOM which is used to contain all context menus. This is not contained within the content view that is fullscreened, so they aren't shown in full-screen.

A possible solution may be to allow context menus to be mounted to an arbitrary component on the DOM instead?
