### ISSUE TITLE
New Image Viewer | when full screen Image is always cropped, and can't zoom

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#17184]
For example with the following image, i want to click on it to read the small text

![image](https://user-images.githubusercontent.com/9841565/117309590-d9eb7380-ae82-11eb-9abd-44eb8b4171fb.png)

But when full screen, the image is in Fill screen mode
![image](https://user-images.githubusercontent.com/9841565/117309721-fa1b3280-ae82-11eb-9928-37cde115dba5.png)

So I cannot see the text, it's cropped

Wouldn't it be better if it was in fit to screen mode (no crop)?

**Comment by SimonBrandner** [comment]
This looks _super_ weird. I am not sure I understand what you mean by fullscreen. Do you mean F11? This is how it looks for me: 

![Screenshot_20210506_155729](https://user-images.githubusercontent.com/25768714/117310667-c68cd800-ae83-11eb-879c-30d6bda5c712.png)

**Comment by dbkr** [comment]
Looks like this is probably dependent on the aspect ratio of your element window compared to the aspect ratio of the image: on your test, the wide image fits into the wide element screen area. On my square-ish element, all I get when clicking on the image is it zoomed in on the centre of the image with no option to zoom in, out or pan around. I assume this is what @BillCarsonFr is seeing. For other images I get the zoom controls: its not clear why they're just absent for this image.

**Comment by SimonBrandner** [comment]
It works just fine for me, if I try to make the window more square-ish

![Screenshot_20210506_161909](https://user-images.githubusercontent.com/25768714/117314185-cb06c000-ae86-11eb-8be7-1b00f203d43c.png)

**Comment by SimonBrandner** [comment]
This is probably a long shot but is there any chance that the event's metadata about the image's size is wrong?

**Comment by dbkr** [comment]
Bingo: the image is 1822x700 but the metadata is:
```json
{
      "h": 350,
      "mimetype": "image/png",
      "size": 33739,
      "thumbnail_info": {
        "h": 307,
        "mimetype": "image/png",
        "size": 5470,
        "w": 800
      },
      "thumbnail_url": "mxc://matrix.org/HCStcQpVdSefEGVxhgZZKVGW",
      "w": 911
    }
```

**Comment by dbkr** [comment]
Seems like we may as well just use the actual image dimensions in this case: we have them anyway?

**Comment by SimonBrandner** [comment]
I really didn't expect that to be the case :D Currently, the code tries to calculate how to scale the image based on the event's metadata if it's present. But as far as I can tell, we could just always use `image.naturalWidth/Height`, without any problems

**Comment by SimonBrandner** [comment]
Could one of you please try [#5982](https://github.com/matrix-org/matrix-react-sdk/pull/5982)?

**Comment by SimonBrandner** [comment]
Adding release-blocker as this seems to be a more common issue than I thought, someone correct me if this isn't a release-blocker

**Comment by BillCarsonFr** [comment]
Tested with netlify build and working @SimonBrandner !

**Comment by BillCarsonFr** [comment]
FTR, i have it everytime I do screenshot from macos (Cmd + Ctrl + Shift 4) then paste

**Comment by dbkr** [comment]
Other side of this filed as https://github.com/vector-im/element-web/issues/17186
