### ISSUE TITLE
element-desktop creates /tmp/.org.chromium.Chromium.xxxxxx files when started, which are not deleted upon exit

### ISSUE THREAD

**Issue by PF4Public** [vector-im/element-web#17188]
### Description

Every time I start element-desktop there are `/tmp/.org.chromium.Chromium.xxxxxx` created and not deleted afterwards.

### Steps to reproduce

- Start element-desktop
- Quit element-desktop
- See the contents of a `/tmp` folder

Electron always creates 2 files with ever changing names, but I suppose that they are essentially the same files every start, so I inspected them in a hex editor and to me it looks like electron unpacks keytar and seshat node modules. I also inspected the files generated during the build of element-desktop and only the `gifwrap` resides in `app.asar.unpacked/node_modules/` everything else seems to be packed into `app.asar`. I also compare this to vscode, which keeps all the native modules outside `app.asar`. Could it be, that those modules should also be unpacked? And my suspicion is that if they are not, electron needs to unpack them every time it starts. Therefore I'm filling a bug here as it could be an issue with element-desktop build system. It could also happen to be electron issue. Anyway it would be nice not to generate extra temporary files.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Gentoo Linux
- **Version**: v1.7.26

Related issues I could find, but they didn't help solve this issue: zulip/zulip-desktop#601 electron/electron#16097

**Comment by PF4Public** [comment]
I have rebuilt element-desktop without native modules and no more `/tmp/.org.chromium.Chromium.xxxxxx`. This makes it clear, that it definitely has something to do with how element handles (packs) native modules.

**Comment by kittykat** [comment]
@PF4Public I cannot reproduce this on Arch - my /tmp/.org.chromium.Chromium.xxxxxx do get cleared. I will update this comment later to confirm what triggers the clearing.

FYI, I am using
Electron v14.0.1 / Chromium v93.0.4577.63 / Node v14.17.0
Element version: 1.8.5 / Olm version: 3.2.3

**Comment by PF4Public** [comment]
@kittykat Did you find the trigger?

I've just rebuilt element from develop and the issue still persists.
BTW, I'm using electron-13.5.0

Version von Element: 1.9.0
Version von Olm: 3.2.3

**Comment by kittykat** [comment]
@PF4Public They clear with time for me. The files that were added on Friday when I used Element were still there yesterday and are gone today.

Please try with a newer Electron and I will try with a newer Element, but I suspect this may be a platform or setup issue rather than a bug in Element.

**Comment by PF4Public** [comment]
> @PF4Public They clear with time for me.

> but I suspect this may be a platform or setup issue rather than a bug in Element

If some script on your platform is clearing leftovers of Element (by cleaning /tmp or something like that) it does not automatically fix a bug in Element. Why does vscode with the same version of Electron _not_ leave unpacked modules behind, even though it does use native modules?

Like I've already stated:
>This makes it clear, that it definitely has something to do with how element handles (packages) native modules.

**Comment by PF4Public** [comment]
Just FYI
I've rebuilt element with electron-16:
```cmd
# ps ax | grep element
13968 ?        SLsl   0:18 /usr/lib64/electron-16/electron --enable-crashpad /usr/lib64/element-desktop/app.asar
```

And as expected element still leaves two binaries in /tmp upon exit because those binaries are still packed into app.asar:
```
 * Searching for element-desktop ...
 * Contents of net-im/element-desktop-9999:
/usr
/usr/lib64
/usr/lib64/element-desktop
/usr/lib64/element-desktop/app.asar
/usr/lib64/element-desktop/img
/usr/lib64/element-desktop/img/element.ico
/usr/lib64/element-desktop/img/element.png
/usr/lib64/element-desktop/webapp -> ../../share/element-web
/usr/share
/usr/share/applications
/usr/share/applications/electron-16-element-desktop.desktop

```

**Comment by G2G2G2G** [comment]
![1](https://user-images.githubusercontent.com/50514477/150771832-4acf93c9-1eab-42bf-acd3-31eaaede9a2f.jpg)
![1](https://user-images.githubusercontent.com/50514477/150772010-6c71ef26-f934-4256-80d2-9af6b2334f2e.jpg)
ty electron (I use arch btw)

**Comment by PF4Public** [comment]
Still the same with electron-18

**Comment by G2G2G2G** [comment]
I mounted /tmp to a ramfs and bought another stick of ram just for element

**Comment by PF4Public** [comment]
Enough! I've submitted a PR. 

@G2G2G2G it would be awesome if you could try building that PR and testing whether it solves the issue.

**Comment by G2G2G2G** [comment]
I build this https://aur.archlinux.org/packages/element-desktop-nightly-bin I avoid electron & npm like the plague.
IDK where to add your thing, I see it's just 1 line..
nothing is in the build dir, I think cuz this AUR uses the .deb package

I believe in your pull request though

**Comment by PF4Public** [comment]
> I think cuz this AUR uses the .deb package

Yep, with pre-built packages you have to wait for the next release.

**Comment by G2G2G2G** [comment]
yea been watching it past week, looks great
