### ISSUE TITLE
The timer in the voice message recorder UI is sometimes multi-line

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17185]
![Peek 2021-05-06 16-08](https://user-images.githubusercontent.com/25768714/117312487-5e3ef600-ae85-11eb-80ca-5be9a8ea87fe.gif)

**Comment by turt2live** [comment]
also browser information please.

**Comment by SimonBrandner** [comment]
Ah, sorry I should have though of that... Looks like font scaling issue - increasing the font size to 16 breaks it. Can repro on the latest nightly and FF 78.10.0esr

**Comment by turt2live** [comment]
I had a feeling there would be problems with `width: 42px` 😭

thanks for the confirmation
