### ISSUE TITLE
Tab completing @mentions with many candidates is slow and CPU hungry

### ISSUE THREAD

**Issue by ilmari** [vector-im/element-web#17182]
### Description

Element hogs the CPU for a long time when there are many candidates for an @mention tab completion.

### Steps to reproduce

- Join a room with many people
- Type an @mention with many candiates (e.g. `@m`) and press tab
- Wait …

Element becomes unresponsive and `top` shows Firefox eating several cores' worth of CPU.
The duration of the CPU spike seems to be proportional to the number of users matching the completion,
i.e. a longer prefix respond quicker.

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 78.10.0esr (64-bit)
- **OS**: Debian 10.9 (Buster)
- **URL**: app.element.io

**Comment by t3chguy** [comment]
I believe this is a performance regression due to https://github.com/matrix-org/matrix-react-sdk/pull/5822

**Comment by joepie91** [comment]
Can confirm that this seems to be a fairly recent issue, that did not occur for me before, but does now.
