### ISSUE TITLE
Verification broken with Fluffychat on the other end, confirming to start verification on fluffychat side leads to "Verification cancelled" in element

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#17180]
### Description

Verification is broken in Element when Fluffychat is on the other end, confirming to start verification on fluffychat side leads to "Verification cancelled" in element. This means if all the other sessions run fluffychat, getting an element session verified is effectively impossible.

### Steps to reproduce

1. Have only sessions running with fluffychat. Make sure cross signing and cloud key backup is enabled, and all your fluffychat sessions are signed and have full encryption access.
2. Start a new session by logging into app.element.io. Do not restore key cloud backup.
3. Element prompts you to "Verify" your session. Click that button to initiate it. Make sure fluffychat for one of your trusted sessionsis running.
4. In "Verify this session" dialog in element, click "Use another login."
5. In fluffychat, "New verification request" is prompted, click "OK" to accept.
6. In element, you now get the offer to "Compare unique emoji" while fluffychat shows a waiting dialog. Click "Start" in element's compare emoji dialog.
7. You will now instantly, or after a few seconds, get "Verification cancelled" in element, even though it is obviously not cancelled on fluffychat's side.

Obviously, I would have expected verification to not randomly cancel.

### Version information

- **Platform**: web

- **Browser**: firefox developer edition
- **OS**: linux
- **URL**:  app.element.io

**Comment by luciaemaster** [comment]
I'm having the same problem. I can't get out of looping "Confirm emojis" and then "you canceled confirmation".  I've tried it on the web, in app and desktop version.

**Comment by cosmic-lamanite** [comment]
this problem is still present as of June 2nd, 2022. ive recently decided to switch from Element to Fluffy (seems like its more complete) and i cant verify on Fluffys end.

**Comment by jenkshields** [comment]
I'm still experiencing this problem as described! Element desktop doesn't have the same problem.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18165
