### ISSUE TITLE
Image size detection is wrong on hidpi displays

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17186]
Uploading an image from a Mac with a retina display results in an image message in the room with dimensions half the actualy image dimensions: presumably the browser looking at some size metric of the image after putting it in the dom which is getting adjusted for hidip.

To repro:
 1. Buy a mac
 2. Find any image, drag 'n' drop it into element
 3. Observe that the metadata on the resulting event shows the image dimensions half of what the actual dimensions of the image are

**Comment by dbkr** [comment]
Oh, I lie - it's not any image: it is just screenshots, and it's the hidpi detection code doing the right thing and looking for the tag in the image and adjusting the dimensions accordingly. Seems like this isn't a bug at all then.

**Comment by jryans** [comment]
@dbkr So the dimensions metadata inside the image data that the app receives for macOS screenshots is incorrect?

**Comment by dbkr** [comment]
The data in the actual image for a screenshot of a a hidpi display is the number of pixels in the pixel data of the image and also a tag to say that it's a 2x (or 3x or whatever), so the size it should be displayed at should be adjusted accordingly, eg. if the image has 512x512 actual pixels in it and declares itself to be @2x, you'd display it 256x256 on a non-retina display, chucking 75% of the pixels in the bin, but on an @2x hidpi display you'd map each image pixel to a physical pixel on the display, so it would still be 256x256 "pixel units" big.

Sorry for missing this earlier, hopefully this clears things up a bit!
