### ISSUE TITLE
our default buttons are inconsistent between chrome and ff

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#17197]
31px height on Chrome
![image](https://user-images.githubusercontent.com/2403652/117437951-cd215b00-af28-11eb-814d-ac2f038a96fb.png)

32px height on FF
![image](https://user-images.githubusercontent.com/2403652/117437956-ceeb1e80-af28-11eb-8bfe-8de9cc5ce19b.png)

**Comment by luixxiul** [comment]
The issue seems to have been fixed somehow.

![before](https://user-images.githubusercontent.com/3362943/164719964-77ba6ecf-b0f8-4043-bdcf-86b895486e33.png)

![before1](https://user-images.githubusercontent.com/3362943/164719979-548f0a6c-e156-4194-a247-d3f107195395.png)

**Comment by t3chguy** [comment]
Indeed
