### ISSUE TITLE
gnu+linux phone (hopefully native) new app

### ISSUE THREAD

**Issue by je-vv** [vector-im/element-web#17209]
One of the things I'm missing to be able to start using an gnu+linux phone es a fully reach Matrix app on those phones.  That means not only being a touch focused app, but also its GUI being optimized for phone sizes.  The gnu+linux desktop app is not an option in that regard, and of course an android app isn't either.  There are other apps, but they don't get as feature reach as element.io...

If building such app, hopefully you develop it as a multi platform native one, and my preference would be basing it on Qt, but if not as native, perhaps closer to native, being based on Flutter for example.  Hopefully not at all based on Electron, which is just running on top of chromium.

With such an app, I would not hesitate getting a pinePhone to start with.

**Comment by SimonBrandner** [comment]
> I am afraid this just won't happen. Making a native app would mean having to rewrite _all_ the code in a different language with a different framework which is just a task so immense that I doubt it will happen anytime soon.

> There is already a bunch of native clients, anyway - see [matrix.org clients](https://matrix.org/clients)

Same comment as [here](https://github.com/vector-im/element-web/issues/17208#issuecomment-835701050)

**Comment by turt2live** [comment]
Mobile apps are out of scope for element-web currently. Someone from the Matrix community might be more suited to build an app of this nature.
