### ISSUE TITLE
native desktop or closer to native

### ISSUE THREAD

**Issue by je-vv** [vector-im/element-web#17208]
I'd like you to consider for the desktop app, to make it become a multi platform native desktop app, Qt based as my preference.  If not possible at all, even for future development, then perhaps you might consider getting it closer to native, like make it based on Flutter.  Right now, being based on electron, means just running web content on top of chromium.

**Comment by SimonBrandner** [comment]
I am afraid this just won't happen. Making a native app would mean having to rewrite _all_ the code in a different language with a different framework which is just a task so immense that I doubt it will happen anytime soon.

There is already a bunch of native clients, anyway - see [matrix.org clients](https://matrix.org/clients)

**Comment by turt2live** [comment]
For the foreseeable future we're sticking with Electron, sorry. One of the other clients @SimonBrandner mentioned may be more suitable for your particular use case.
