### ISSUE TITLE
re.jki.counter events with debug events enabled should be summarized

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#17214]
#### Is your suggestion related to a problem? Please describe.
The server_stats room uses this event quite a lot. Each 5m the bot updates it and if the number changed it causes a new state event which is a lot.

<img src="https://user-images.githubusercontent.com/1374914/117573524-b02b8a00-b0d8-11eb-8c62-7ed43d44530d.png" height="700">

#### Describe the solution you'd like.
It should collapse like membership events do as these counter events barely are useful for debugging anyway and therefor could live as second class citizens

#### Describe alternatives you've considered.
Allowing to filter out selective events from your debug view if wanted. But this would be a whole different issue.

**Comment by MTRNord** [comment]
> Something specific to a single hidden event would be unlikely. At best maybe the labs should be extended to summarise all hidden events. e.g `N hidden events` whenever >1

Yeah that would also work to be able to maybe Filter the types of debug Events that you dont want to See.

**Comment by turt2live** [comment]
> Something specific to a single hidden event would be unlikely.

Unless we expand "devtools" beyond the dialog 😇
