### ISSUE TITLE
Shift+Return repeats the last character

### ISSUE THREAD

**Issue by MisterAI** [vector-im/element-web#17215]
### Description

When entering a new line via Shift+Return when composing a message the last character of the current line is automatically added as the first character of the new line (the cursor is placed before the repeated character).

### Steps to reproduce

- Go to "All settings" -> "Preferences" -> Activate "Use Ctrl + Enter to send [...]"
- Start typing a message in any chat (room)
- Hit Shift + Return

Example result:

> Test
> t

Expected result:

> Test
> _empty line_

Log: not sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Linux Mint 18.3
- **Version**:
  - Element version: 1.7.25
  - olm version: 3.2.1

**Comment by SimonBrandner** [comment]
Looks like this happens only on Chromium (and desktop as it uses it)

**Comment by czeidler** [comment]
Can confirm that it works as expected in Firefox but not in Chrome.

Ran it through the debugger and it seems like Chrome adds two carriage returns `\n\n` when at the end of the line and `shift + Enter`. For example, in Chrome:
1) With an oldValue = 'abc' and caret at position 3 the newValue is 'abc\n\n'.
2) With an oldValue = 'abc' and caret at position 2 the newValue is 'ab\nc'.

Is that expected Chrome behavior or is that a bug? Could add a workaround for that if this behavior isn't there for some purpose...

@t3chguy I actually thought about some fuzzy "I don't care" matching but then decided against it. The reason for that was that if the user enters a fuzzy key combo, the user might have done this accidentally. In this case, applying the keybinding would probably be very frustrating (especially when sending the message too early). On the other hand, if the fuzzy key combo was entered on purpose and nothing happens the user simply has to re-enter the correct, exact combo. I argue that the exact matching is less frustrating to the user. Furthermore, it keeps things simple.

**Comment by czeidler** [comment]
The problem actually happens at every end of line. Below is a fix. However, I have a different solution in a pull request.

``` diff
@@ -335,6 +335,20 @@ export default class BasicMessageEditor extends React.Component<IProps, IState>
         this.modifiedFlag = true;
         const sel = document.getSelection();
         const {caret, text} = getCaretOffsetAndText(this.editorRef.current, sel);
+        // On Chrome shift+enter generates a double carriage return sequence '\n\n' when:
+        // 1) the previous char is not a \n
+        // 2) the next char is a \n
+        // Also see #17215.
+        // The model gets confused by this unexpected input produces an incorrect line break.
+        // The following block sanitizes the text before passing it to the model.
+        if (event.inputType === 'insertLineBreak' && text.substr(caret.offset - 1, 2) === '\n\n') {
+            const previousValue = this.props.model.parts.reduce((text, p) => text + p.text, "");
+            if (previousValue.length === text.length - 2) {
+                this.props.model.update(text.slice(0, caret.offset) + text.slice(caret.offset + 1),
+                    event.inputType, caret);
+                return;
+            }
+        }
         this.props.model.update(text, event.inputType, caret);
     };
 ```

**Comment by mcg-matrix** [comment]
> Example result:
> 
> > Test
> > t
> 
> Expected result:
> 
> > Test
> > _empty line_

I can report that this unexpected behaviour still occurs in Element-Desktop installed via Debian package "element-desktop" version 1.9.5 provided by https://packages.riot.im/debian/.

**Comment by mcg-matrix** [comment]
The unexpected behaviour is gone in version 1.10.3 of Element-Desktop. Shift+Enter inserts a linebreak as expected, with or without preference "Use Ctrl + Enter to send a message" turned on.

Thank you!
