### ISSUE TITLE
Unbans do not join the MELS anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17212]

**Comment by t3chguy** [comment]
Cannot repro

![image](https://user-images.githubusercontent.com/2403652/117682148-ae31fb80-b1aa-11eb-9dd8-8fd7ed65e387.png)
![image](https://user-images.githubusercontent.com/2403652/117682167-b12cec00-b1aa-11eb-9a77-619ce02b9f75.png)

**Comment by turt2live** [comment]
Might have been a redaction or something caught between them then
