### ISSUE TITLE
resetting 4S with a recovery key doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17229]
If you hit the 'forgot everything' button when prompted for your 4S passphrase/key, and then ask it to reset everything and set up with a 4S key, then it doesn't actually reset your 4S state.  If you reset and set up with a 4S passphrase it works however.

**Comment by turt2live** [comment]
I'm not sure I tested the key-based path very well, honestly. The use case was to reset with passphrases and the code around it looked like it would work.

**Comment by ShadowJonathan** [comment]
Can't reproduce, when clicking "reset everything", this actually resets everything properly.

**Comment by kittykat** [comment]
I'm going to close this issue for now, please re-open with more details if you feel that there are further improvements to be made.
