### ISSUE TITLE
Jitsi PIP can end up stuck on if you pop it out

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17226]
Repro steps:
 * Go to a room with a Jitsi widget in it
 * Join the widget
 * Click the "pop widget out into its own tab" button
 * Switch room
 * Have a stuck blank PIP Jitsi you can't remove.

<img width="389" alt="Screenshot 2021-05-10 at 12 11 13" src="https://user-images.githubusercontent.com/1294269/117650726-f809ea00-b188-11eb-95dc-1576a0f4c6b2.png">

**Comment by Palid** [comment]
@dbkr didn't your last pull request related to widgets fix it?

**Comment by Palid** [comment]
Still reproducible, can't even rejoin jitsi after opening a new tab with it.

**Comment by Palid** [comment]
@ara4n could you test https://github.com/matrix-org/matrix-react-sdk/pull/6632 if this still can be reproduced? Spent a while with it, but prefer double-checking. 😄
