### ISSUE TITLE
custom fonts persist across logout/login

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17228]
i just logged out of one account which had a custom font set up, and logged in on a different one. was surprised to discover the custom font from the old account persisted...

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22021

**Comment by ara4n** [comment]
No, the bug here is that the custom font is *incorrectly* preserved between different logins - i.e. we're not flushing out custom state correctly between logout & login.  Bug #22021 is about the opposite - preserving theming between logins, where presumably something is overenthusiastically flushing out some theming.

It's possible this has been fixed in the last year, but it needs to be verified.

**Comment by t3chguy** [comment]
ah yes my bad, i can't read
