### ISSUE TITLE
Decide on code style for `import { words }` versus `import {words}`

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17236]
The merge conflicts are getting annoying, as are the diff reviews which change them back and forth.

**Comment by ara4n** [comment]
(i'd vote massively for `import { words }` - it looks ugly and cramped without the whitespace)

**Comment by turt2live** [comment]
We've decided to use spaces between braces for now. Until the linter is updated at all levels, please adjust accordingly.
