### ISSUE TITLE
UI to trigger a self-verification is very opaque

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17230]
If you cancel self-verification at login and then want to do it later, it's very unclear that you have to go to your MemberInfo and then click on a device.  Instead there should be a Verify button as there is for other users

**Comment by kittykat** [comment]
![Screenshot from 2021-12-21 17-23-17](https://user-images.githubusercontent.com/51663/146972511-2ad14a84-9bb6-43a0-9f0e-0c35ea1ea3b3.png)

UI has changed and there are periodic toasts about it as well
