### ISSUE TITLE
Add a way to add an alias to a space

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17244]

**Comment by niquewoodhouse** [comment]
Just to check, is an alias useful for each type of space there currently is?

- Public
- Private
  -  Just me
  - Team 

I think an alias just lets people visit the space via a URL, is that right?  Or does it do more than that?

Thanks

**Comment by t3chguy** [comment]
Yes but for different reasons.

For public spaces an alias is needed to publish it as a public room to your server's room directory
an alias can be used for joining the space/room also

For private rooms/spaces an alias might be useful for giving an identifier to the room which you can use to make Pills in the autocomplete, e.g `#eleme<TAB>`

**Comment by niquewoodhouse** [comment]
> For public spaces an alias is needed to publish it as a public room to your server's room directory
> an alias can be used for joining the space/room also

So, to design this properly, we should consider how spaces appear in 'room directories' as that would be the reason you'd add an alias?

They'd look like 'rooms' by default?  And work like the below?

![image](https://user-images.githubusercontent.com/1587166/117956830-52ce4d80-b311-11eb-9499-d0eb203306d5.png)

- Content would be 
   -  Space avatar; Space name; Space description; Space members.

- Preview would show space preview + Join would open the space

**Comment by ShadowJonathan** [comment]
Imo spaces should not look like normal rooms in the room directory, maybe a label after the name that says "space" will already help that.

**Comment by t3chguy** [comment]
> So, to design this properly, we should consider how spaces appear in 'room directories' as that would be the reason you'd add an alias?

In the longer term yes, but this requires Matrix Spec changes as the publicRooms API isn't space-aware

> They'd look like 'rooms' by default? And work like the below?

Today without those spec changes, yes

**Comment by niquewoodhouse** [comment]
> Imo spaces should not look like normal rooms in the room directory, maybe a label after the name that says "space" will already help that.

Totally agree they shouldn't look the same.  
Just trying to understand what happens by default if we can't do anything in that area, for now.

**Comment by niquewoodhouse** [comment]
> For private rooms/spaces an alias might be useful for giving an identifier to the room which you can use to make Pills in the autocomplete, e.g #eleme<TAB>

At the moment, when I try to make a private room I don't get the option to add an alias.  Whereas I do for public room creation. 

Is this because this action is generally less important if it's a private room?  Is it more important if it's a space, and not a room?

**Comment by t3chguy** [comment]
> Is this because this action is generally less important if it's a private room?

Yes

> Is it more important if it's a space, and not a room?

No

**Comment by ara4n** [comment]
Skimming the comments, i think we're missing the most important use case - aliases let you refer externally to spaces (and rooms) using a human-legible identifier.  So I can say "hey, come join #community:matrix.org" or link to https://matrix.to/#/#community:matrix.org or even matrix:r/community:matrix.org.

Without this, you end up with excruciating things like https://lobste.rs/s/oqsbr4/matrix_space_beta#c_2qxzbq, where the link to the haskell space in question is the utterly impenetrable and geeky and ugly: https://matrix.to/#/!huZmVnclBNrpbrOnpd:matrix.org?via=matrix.org&via=famisoft.pl&via=rauhala.info

**Comment by t3chguy** [comment]
No one disagrees with the need for aliases, but our current alias UI *SUCKS* and needs some real thought.

![image](https://user-images.githubusercontent.com/2403652/118857371-de2a7e80-b8cf-11eb-8552-ea87d1632a57.png)

**Comment by ara4n** [comment]
Totally agreed - but that is orthogonal to us exposing the alias UI (however broken that currently is) for spaces.

In other words, we could expose the current broken UI (it's got beta slapped over it anyway!) and then separately fix the aliases UI for both rooms & spaces.
