### ISSUE TITLE
URLs in topics in space summary page should be clickable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17252]

**Comment by t3chguy** [comment]
They are in my testing, they use the same `<RoomTopic />` component as rooms.

![image](https://user-images.githubusercontent.com/2403652/117946897-9b810900-b307-11eb-8b5a-deb564cca7e7.png)
![image](https://user-images.githubusercontent.com/2403652/117947473-2235e600-b308-11eb-9940-f06a9338f220.png)

--- 

Oh you probably mean in the Explore Rooms
