### ISSUE TITLE
the fact Invites only appear in your Home space means they are super easy to miss

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17251]
I'm dutifully using spaces, and rarely going to my Home space other than when i want a view of the whole world. As a result, i keep missing invites (if i miss the accompanying push)

**Comment by niquewoodhouse** [comment]
> they also appear in the relevant spaces ftr

is that invites to a room?  invites to DM?

**Comment by t3chguy** [comment]
Both, and to sub-spaces

**Comment by kittykat** [comment]
Notifications show in the left spaces panel now:

![Screenshot from 2021-09-21 09-09-26](https://user-images.githubusercontent.com/51663/134135452-84c80642-8b20-4127-81a0-116024d89885.png)
