### ISSUE TITLE
Creating subspaces is very unintuitive

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17256]
You do so by hitting the 'add existing room' button. However, from the user perspective, spaces aren't rooms - they're spaces. So why would i select 'add existing room' when i want to find/add a space?

**Comment by niquewoodhouse** [comment]
We do have some [prototypes](https://www.figma.com/proto/kIbEhWhWmHTpaqKol9ekXZ/HMW-Make-adding-subspaces-feel-easier-to-discover?page-id=0%3A1&node-id=11%3A8599&viewport=195%2C433%2C0.11320754885673523&scaling=min-zoom) exploring this.

**Comment by SimonBrandner** [comment]
I quite dislike number 3 (in expanded space panel) - it will take up unnecessary space and it will be confusing for spaces that don't have any subspaces yet (I am not even sure how exactly would that work). Numbers 1 and 2 feel like they could co-exist together very well.

**Comment by t3chguy** [comment]
The ability to add an existing space as a subspace is important too, for organisational "Just Me" spaces

**Comment by niquewoodhouse** [comment]
@t3chguy would doing these ideas fit within the predicted time?  Mockups are a bit out of date but hopefully explain the rough idea well enough.

**1 Add to context menu**
![image](https://user-images.githubusercontent.com/1587166/126158139-5c147986-4d1e-4204-ba9e-5948a9ea3b43.png)

**2 Add to explore space**

![image](https://user-images.githubusercontent.com/1587166/126158254-198b1391-9303-411e-9967-28d033231412.png)

**4 Add a note to the create space dialog**

This mockup has it as a link but it could just be a footnote bit of text, "you can also add spaces to spaces".

![image](https://user-images.githubusercontent.com/1587166/126158732-8bbef3e4-41d0-46c3-b431-29bacd4f158f.png)

**Comment by t3chguy** [comment]
1/2 are reasonable

Where would the ability to add an existing space as subspace live?

> The ability to add an existing space as a subspace is important too, for organisational "Just Me" spaces


4 could be reasonable but given you have `Home` selected, which space would that be a subspace for?

---

For all of them, what would the subspace creation part look like? Presumably a modified space creation wizard
