### ISSUE TITLE
Possible cause of room list corruption: Receiving an invite and answering it on another device while looking at a space

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17272]

**Comment by ara4n** [comment]
(i think i've seen rampant roomlist corruption without having accepted invites elseplace)

**Comment by jryans** [comment]
@turt2live Is this a duplicate of https://github.com/vector-im/element-web/issues/14508?

**Comment by turt2live** [comment]
No, but the other issue has been hijacked despite my best efforts.
