### ISSUE TITLE
Rapidly clicking the red X in the room directory filter results can cause the directory to duplicate

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17270]
We should probably no-op or not have the button if there's nothing to do

**Comment by Palid** [comment]
@turt2live I can't reproduce this, is this still a problem? If yes, please add better reproduction steps.
We should add some debouncing for it anyways, though. If the problem does not exist anymore then we should only make debouncing for slightly less network requests that aren't necessary.
