### ISSUE TITLE
Settings icon for Labs should be changed for clarity

### ISSUE THREAD

**Issue by WolvenMoonstone** [vector-im/element-web#17274]
### Description

The settings icon for is a flag rather then a beaker.

### Steps to reproduce

open the settings menu 

Describe how what happens differs from what you expected.

The settings menu has a series of icons intended to visually indicate the purpose of a category. The icon for labs in the settings menu is a flag to non-technical users there is no coloration between a flag and experimental features. Other apps use a beaker for this icon.

![LabsFlag](https://user-images.githubusercontent.com/20031750/118035516-85d00b80-b328-11eb-856b-abfe5399f019.png)

**Comment by t3chguy** [comment]
It is now a beaker
