### ISSUE TITLE
Allow top level spaces to be reordered

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#17282]
May need an MSC

Related: https://github.com/vector-im/element-web/issues/16992

**Comment by SimonBrandner** [comment]
Possibly pinning spaces could be allowed

**Comment by ShadowJonathan** [comment]
> This seems to need an MSC

Couldn't this just be account data in the meantime? `im.vector.spaces.ordering`, an array of IDs.

**Comment by t3chguy** [comment]
Sure, but it might be better using existing `m.tag` with some consideration

**Comment by aaronraimist** [comment]
MSC: https://github.com/matrix-org/matrix-doc/pull/3230
