### ISSUE TITLE
The (i) icon on "Spaces are a beta feature" is misleading

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17285]
<img width="273" alt="Screenshot 2021-05-13 at 13 00 48" src="https://user-images.githubusercontent.com/1294269/118123039-91d0d180-b3eb-11eb-84c5-d11d5c2c511b.png">

Everywhere else we use (i) in the app is used to indicate an information tooltip (e.g. the login & registration flows).  But here it has no tooltip. I clicked on it about 4 times hoping to find out more info.

**Comment by t3chguy** [comment]
That's not quite the case

![image](https://user-images.githubusercontent.com/2403652/118123595-68647580-b3ec-11eb-96ef-7f8256bb3bf2.png)

**Comment by ara4n** [comment]
well, it's still a button which when I click it, something happens. rather than decorative. so it reinforces my point :)

**Comment by aaronraimist** [comment]
This icon is gone now
