### ISSUE TITLE
Edits are collapsing to a blank line when the edit happens while looking at the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17290]
on develop, regression in the last 24h

**Comment by ara4n** [comment]
@jryans this is really painful (having just updated to a build which suffers from it) - we can't ship 1.7.28 with it like this.

**Comment by SimonBrandner** [comment]
![Screenshot_20210517_073609](https://user-images.githubusercontent.com/25768714/118437233-8ed32b00-b6e2-11eb-8c9f-57bcbe968959.png)

This is from staging.element.io. As far as I can tell, this was regressed between the 12th and the 13th which is a day or two after the first RC - this is a release blocker, but not for 1.7.28
