### ISSUE TITLE
Account recreation fails after deactivation

### ISSUE THREAD

**Issue by ANF-Studios** [vector-im/element-web#17298]
### Description

Cannot recreate account after deactivation when using GitHub.

### Steps to reproduce

- Deactivate your account only created using GitHub.
- Recreate it with that same GitHub account, only connected to matrix.org.
- Error.

Describe how what happens differs from what you expected.

It should recreate it without any issues at least.

![image](https://user-images.githubusercontent.com/68814933/118215332-52cc6b80-b43f-11eb-814d-ff00425f0038.png)

### Version information

- **Platform**: web, in-browser.

For the web app:

- **Browser**: Chrome 90.0.4430.212 (Official Build) (64-bit)
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: app.element.io

For the desktop app:

- **OS**: Microsoft Windows 
- **Version**: 10.0.19042.630

**Comment by t3chguy** [comment]
That error is from the Matrix server you're connecting to, presumably `matrix.org` - not Element.

**Comment by ANF-Studios** [comment]
Alright thanks, I emailed them my problem and referenced them this issue, I'll be waiting for a reply from them now, please wait till then.

**Comment by aaronraimist** [comment]
Closing since this isn't an Element issue.
