### ISSUE TITLE
Receiving messages in corrupted room list rooms causes proliferation

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17294]

**Comment by jaywink** [comment]
![Selection_999(287)](https://user-images.githubusercontent.com/1174866/118251106-d58d0f00-b4af-11eb-8eb0-30a45d98f6e7.png)

A person I was chatting quickly became three rooms in the room list, after minimizing and maximizing the people section, down to two. Is this the right issue? Attaching rageshake.

**Comment by t3chguy** [comment]
Haven't seen any room list proliferation issues in a while, the one caused by a race within Algorithm is long dead by making the whole thing Sync
