### ISSUE TITLE
Encrypted room history search inconsistent across instances - one instance has indexed more messages than another (but both think they're finished)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17299]
On my mac:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1922197/118265641-5d274d80-b4b1-11eb-9936-6b48d4c95028.png">

On my windows machine:
![image](https://user-images.githubusercontent.com/1922197/118265774-9069dc80-b4b1-11eb-80ad-64107cec36b0.png)

**Comment by foresto** [comment]
I see the same discrepancy between two sessions on the same machine. Also, one instance misses certain messages that the other instance finds in a search.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/14407

**Comment by turt2live** [comment]
I think this is fine as it can mean there's decryption errors or similar. Closing in favour of that whole stream of issues.
