### ISSUE TITLE
Opening the Spaces Feedback modal will close any modals that are currently open

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#17306]
### Description

Say you're in a space and currently editing the settings of the space, like so:

![image](https://user-images.githubusercontent.com/1342360/118341891-ecb41700-b518-11eb-9641-b34f01d79f41.png)

You write a big description and then think "hmm, I really wish I could also add a foobar field to this form". So before you hit Save you hit the "Send feedback" form, write your constructive feedback and hit Send feedback.

You're then taken back to the Manage your Space page, your previous modal and your written up description lost to the wind :cloud: 

### Steps to reproduce

- Open a modal window that involves spaces
- Click the "Feedback" button
- Watch your previous modal be replaced, instead of put below, the Spaces Feedback modal

Ideally it would just spawn on top instead of replacing the current modal.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: develop.element.io (latest commits across repos as of today)

**Comment by t3chguy** [comment]
This was done semi-on-purpose as our stacked modals kinda suck :(

**Comment by anoadragon453** [comment]
Aha OK. I know the spaces feedback button is only temporary, but I assumed fixing this would have some sort of lasting implication. Especially if we decide the implement the same system for future features.

**Comment by t3chguy** [comment]
We can fix this for the settings dialog, but not the add existing to space dialog
