### ISSUE TITLE
[UX anti pattern] "Explore rooms" button inconsistent compared to search bar

### ISSUE THREAD

**Issue by libexus** [vector-im/element-web#17307]
### Description

The "Filter all spaces" search bar filters *all* your spaces (big surprise) and rooms. Therefore I expected the "Explore rooms" button located **directly next to it** to be global too i.e. to open *the server's room list* instead of the Space home.

I've stumbled across this quite often so I really think this should be redesigned in order to clarify the behavior.

### Version information

develop.element.io (e716e484a68d-react-1b8402f39c40-js-91af9a411d3c)

![grafik](https://user-images.githubusercontent.com/67947338/118351413-383be480-b55c-11eb-8cc9-bccd604b9127.png)

**Comment by libexus** [comment]
Sort of related to #17203

**Comment by t3chguy** [comment]
The search is known to be in the wrong location hierarchically, this may not be fixed until post-Beta due to it being quite a large change difficult to maintain as a Beta
