### ISSUE TITLE
Render process crash when scrolling up on Windows 7

### ISSUE THREAD

**Issue by k79e** [vector-im/element-web#17309]
### Description

Screen become white when scroll up
### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Open a room and scroll up for a long time. Then the screen will become white. (In test I used a encrypted room, other rooms not tested)

Just click the scroll bar and move up and don't release then soon it will be whiteboard.
![image](https://user-images.githubusercontent.com/6483602/118353608-afdc3480-b599-11eb-9b6b-32521b3c824f.png)

Logs being sent: yes

### Version information

- **Platform**: web (in-browser) or desktop?
- desktop

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? 
- Win7 x64
- **Version**: 1.x.y 
- 1.7.27

**Comment by thedanbob** [comment]
I just ran into this problem myself in Element Desktop 1.9.9 on Arch Linux. I tried running it from the command line with `element-desktop --enable-logging`, but the only thing that's logged when the crash happens is "Renderer process crashed". Here's a core dump in case it's helpful: https://drive.google.com/file/d/11FSZM2ZIuzIUXMrxOt3WPgOlskBhSxqQ/view?usp=sharing

**Comment by thedanbob** [comment]
This was fixed yesterday in Arch. Apparently it's a problem in electron that affects other apps. Here's the [bug report](https://bugs.archlinux.org/task/73518) and the [fix](https://github.com/archlinux/svntogit-community/commit/24352d68249c9271e7f4451866e46f6e7f68aeaa#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a).

**Comment by novocaine** [comment]
The issue on arch is tracked here: https://github.com/vector-im/element-web/issues/20926

This is an old win7 bug. @k79e has this happened again recently?

**Comment by k79e** [comment]
@novocaine 
There is another bug. I can't even use the program.

**Comment by novocaine** [comment]
Let's discuss over on your other report https://github.com/vector-im/element-web/issues/17333
