### ISSUE TITLE
User Detail Mismatch for spaces

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17300]
### Steps to reproduce
1. Go to room
2. Right-click space -> "members"
3. Select member
4. When you're an admin of the space, observe being unable to affect "role"

### Version information

- **Browser**: Chromium Edge
- **OS**: Windows
- **URL**: staging.element.io "1.7.28-rc.1"

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17018
