### ISSUE TITLE
No information how to continue on desktop ?

### ISSUE THREAD

**Issue by JanzenJohn** [vector-im/element-web#17310]
![error](https://user-images.githubusercontent.com/51709412/118361028-14d36280-b579-11eb-8449-20e17c015d55.png)

### Description

I don't know how to continue after build or what config file to set in.
And the link to element.io reveal new information

### Steps to reproduce

-download the build files for element-desktop
-follow the given steps to build
-run
    yarn run start

Describe how what happens differs from what you expected.

I expected a path to the expected / broken file
and maybe a link to a page listing possible servers

Log: not sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**:  Gentoo
- **Version**: 1.7.27

**Comment by t3chguy** [comment]
Looks like you followed the instructions which say

> # We're explicitly asking for no config, so the packaged Element will have no config.json.

In which case you'd have to provide a local config using https://github.com/vector-im/element-desktop#user-specified-configjson

Or include one in the build using https://github.com/vector-im/element-desktop#config
