### ISSUE TITLE
+🙂 on hover button is too tall/shifts timeline

### ISSUE THREAD

**Issue by lub** [vector-im/element-web#17318]
### Description

When hovering over a message with reactions the 'add reaction' button appears, but it also moves the whole timeline by a couple of pixels.

### Steps to reproduce

- find a message with reactions
- hover over it

I hope this shows the height difference. The orange window border is at the same place on my screen in both screenshots:
![image](https://user-images.githubusercontent.com/1029578/118459579-2b55f700-b6fc-11eb-8b6c-18cf4f76cb0c.png)
![image](https://user-images.githubusercontent.com/1029578/118459605-327d0500-b6fc-11eb-927d-9ab61d38c017.png)

Logs being sent: yes

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Windows
- **URL**: develop.element.io

**Comment by t3chguy** [comment]
This like likely related to your font size change, but sure is annoying

`"baseFontSize":9`

**Comment by SimonBrandner** [comment]
Related: [#17316](https://github.com/vector-im/element-web/issues/17316)
