### ISSUE TITLE
Open Element with Double Click on Tray Icon [Ubuntu]

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-web#17315]
I'd like to open Element by double clicking on the system tray icon. Currently you have to click once, move mouse cursor to show/hide button and click it.
OS: Zorin16, based on Ubuntu 20.04 LTS

**Comment by xekon** [comment]
bah, I missed this one.

I just opened this one: https://github.com/vector-im/element-web/issues/17850

I am suggesting single left displays or hides element. This is the exact behavior of other applications such as Pidgin, or Kdocker which I use to minimize Thunderbird to system tray.

I am running Kubuntu 20.04.2 LTS

**Comment by xekon** [comment]
I just found this: https://github.com/vector-im/element-web/issues/11772

**Comment by xekon** [comment]
This worked for me:

```
sudo touch /opt/Element/libappindicator3.so
sudo touch /opt/Element/libappindicator3.so.1
```

After doing that left click now shows and hides Element.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11772

**Comment by Jieiku** [comment]
This no longer works. its back to not showing/hiding on mouse click of tray icon.
