### ISSUE TITLE
UTD from Matthew

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#17323]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent   

### Version information

- **Platform**: desktop, macOS

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by kittykat** [comment]
I'm going to close this issue for now as there isn't enough information here for us to investigate. Please reopen if there are more details available.
