### ISSUE TITLE
Clicking a pill sends me to home even if not neccessary

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17321]
![Peek 2021-05-17 11-45](https://user-images.githubusercontent.com/25768714/118469148-bb4c6e80-b705-11eb-9563-d72ddebfaab1.gif)

**Comment by t3chguy** [comment]
@SimonBrandner have you experienced this since my TS fixes?

**Comment by SimonBrandner** [comment]
No, and I forgot to close this
