### ISSUE TITLE
Docker "stable" tag

### ISSUE THREAD

**Issue by lanerussell** [vector-im/element-web#17327]
#### Is your suggestion related to a problem? Please describe.
There is currently a `latest` tag for the vectorim/element-web docker container. However, there is not a `stable` tag tracking the latest stable release.

#### Describe the solution you'd like.
If possible, add a `stable` tag and update following each stable release, `1.7.27`, `1.7.28`, etc.

#### Describe alternatives you've considered.
Sysadmin could manually update tag in docker-compose file after each release. I.e. `image: vectorim/element-web:v1.7.28`

**Comment by t3chguy** [comment]
See https://github.com/vector-im/element-web/issues/17325#issuecomment-842349394

The `latest` tag is *stable* - just the versioning script is broken.
