### ISSUE TITLE
Failure to add a room to space

### ISSUE THREAD

**Issue by tuxayo** [vector-im/element-web#17331]
Will send logs to this ticket

### Steps to reproduce

Happened twice, don't know what caused it.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox, which version? dev edition 89.0b12 
- **OS**: EndeavourOS, Arch Linux based
- **URL**:  app.element.io

**Comment by t3chguy** [comment]
This was a `matrix.org` failure

`2021-05-17T15:18:01.604Z E Failed to add rooms to space request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/rooms/!roomId:matrix.org/state/m.space.child/!roomId2:matrix.org`

**Comment by t3chguy** [comment]
Not something element-web can do anything about.
