### ISSUE TITLE
Space room list shows "unnamed room" instead of participants

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17336]
### Description

![image](https://user-images.githubusercontent.com/2803622/118524812-d7b8cd00-b73e-11eb-8814-7555699f7ae9.png)

### Steps to reproduce

I added a couple of family member DMs and groups to a private space. I have not renamed the rooms to keep the autogenerated title of who the other participants are.

Please use the same name in both lists

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021051701-1
- **Homeserver**: synapse 1.34.0 (pypi)

**Comment by SimonBrandner** [comment]
Can reproduce

**Comment by t3chguy** [comment]
This will be an issue where the server doesn't tell us the members of the room so we can't generate a better name for it

**Comment by HarHarLinks** [comment]
I just noticed what cannot be seen in the screenshot: at least some of these DMs are supposed to show the other user's avatar. They do in the room list.

**Comment by t3chguy** [comment]
Same reason: https://github.com/vector-im/element-web/issues/17336#issuecomment-842477570
