### ISSUE TITLE
Implement tombstones for Spaces

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#17339]
#### Is your suggestion related to a problem? Please describe.
If an m.room.tombstone event is made for a Space, latest Element Web does nothing to show that to the user.

#### Describe the solution you'd like.
Display the tombstone to the users same as rooms. Also, clarify what happens if a user tombstones a space to go to a regular room, and vice-versa (should that even be allowed?)

**Comment by t3chguy** [comment]
please fill the issue template.

**Comment by Mikaela** [comment]
This seems kind of like a duplicate of https://github.com/vector-im/element-web/issues/19208 as while this is older, that one follows the issue template and has more discussion within it.

**Comment by t3chguy** [comment]
Closing in favour of #19208 as tombstones are part of the room upgrade process
