### ISSUE TITLE
The index.html is minified and breaks some automation

### ISSUE THREAD

**Issue by fooness** [vector-im/element-web#17330]
The minified `index.html` (all content in one single line) in Element-Web `v1.7.28` (and maybe one or two versions prior) completely breaks (our) Ansible-automated installation and configuration scripts.

Can this please be reverted? Element still offers no proper way of customisation and almost any new elements that are introduced use hardcoded color values instead of existing color variables … it’s simple not possible to properly modify element with just the color variable definitions in `config.json`, and now breaking the proper HTML-structure in `index.html` even makes it close to impossible to automatically change/add contents in that file, like e.g. adding custom css.

Please revert this to non-minified, proper HTML.

**Comment by turt2live** [comment]
@fooness it would be great if this issue was written in a way where we were inclined to interact with it. Confrontational titles, unexplained asks for reverting a change, and assumption that this is intentional all make this undesirable to look at.

**Comment by t3chguy** [comment]
`Please revert this to non-minified, proper HTML.`

pretty sure it is quite proper & valid; https://validator.w3.org/nu/?doc=https%3A%2F%2Fapp.element.io%2F doesn't complain about the formatting of the file.

> Can this please be reverted?

This was not an intentional change, but likely caused by a dependency being upgraded.

> completely breaks (our) Ansible-automated installation and configuration scripts.

Your scripts were brittle then.

> almost any new elements that are introduced use hardcoded color values instead of existing color variables

Please report these specifically because this should not be happening.

> makes it close to impossible to automatically change/add contents in that file, like e.g. adding custom css.

Not impossible at all, you just have to write more resilient scripts that break when handed *VALID* HTML.

**Comment by jryans** [comment]
The content of the `index.html` file is not a supported API surface, so it might change at any time.

This document minification was not done on purpose, but happened as a side effect of upgrading. We would happily accept a PR to fix this, but it is also not a priority for the core team.

**Comment by fooness** [comment]
@turt2live @t3chguy @jryans Pardon if this was a little bit harsh and direct. It’s just rather frustrating that established things in Element are oftentimes changed without detailed upgrade notes and oftentimes introduce some problems for people that want to make use of Element’s customisation features. Sorry for the strong words.

> > Can this please be reverted?
> 
> This was not an intentional change, but likely caused by a dependency being upgraded.

This makes me hope that we might get back the multi-line `index.html` file?

> > completely breaks (our) Ansible-automated installation and configuration scripts.
> 
> Your scripts were brittle then.

> > makes it close to impossible to automatically change/add contents in that file, like e.g. adding custom css.
> 
> Not impossible at all, you just have to write more resilient scripts that don't break when handed _VALID_ HTML.

This is partly true; script that rely on e.g. replacing or adding lines kinda don’t work anymore when there’s no more than one single line in a file to work with.

> This document minification was not done on purpose, but happened as a side effect of upgrading. We would happily accept a PR to fix this, but it is also not a priority for the core team.

We’re super happy to hear so. Is there any research/preparation work I could to for someone else to make the PR?

**Comment by fooness** [comment]
Maybe `Switch back to release version of sanitize-html` via https://github.com/vector-im/element-web/pull/17231 has something to do with this?

**Comment by t3chguy** [comment]
Unlikely. We only call `sanitize-html` at runtime for validating user input.

**Comment by fooness** [comment]
> Unlikely. We only call `sanitize-html` at runtime for validating user input.

Oh, okay sure … sanitizing user input indeed makes way more sense, than sanitizing code from the repo itself. Sorry.

Unfortunately, after looking through the last changelogs and pull request as well as searching for `index.html` in the `element-web` as well as `matrix-react-sdk` repo, I’m still not quite sure where this change could have been introduced.

**Comment by t3chguy** [comment]
Likelu somewhere in https://github.com/vector-im/element-web/commits/develop/yarn.lock

**Comment by fooness** [comment]
> Likelu somewhere in https://github.com/vector-im/element-web/commits/develop/yarn.lock

The changes here look rather cryptic to me; lots of version/hash changes …

It seems that element-web `v1.7.27-rc.1` introduced the problem; that release candidate was released on 2021-05-04 …

So the issue should be somwhere here, right? https://github.com/vector-im/element-web/compare/v1.7.26...v1.7.27-rc.1

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/compare/v1.7.26...v1.7.27-rc.1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L114 looks relevant

**Comment by fooness** [comment]
> [v1.7.26...v1.7.27-rc.1diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L114](https://github.com/vector-im/element-web/compare/v1.7.26...v1.7.27-rc.1diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L114) looks relevant

Unfortunately the link does not work for me.

<img width="1276" alt="Screen Shot 2021-05-17 at 19 54 08" src="https://user-images.githubusercontent.com/11408027/118534564-ae516e80-b749-11eb-9aa1-40380e6a5374.png">

It seems that a package called `html-minifier` was  replaced with `html-minifier-terser` via: https://github.com/vector-im/element-web/commit/708f6a26b1128f7371daff017bc777c2712889bb#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL5671-R5715

<img width="1212" alt="Screen Shot 2021-05-17 at 19 58 20" src="https://user-images.githubusercontent.com/11408027/118535054-451e2b00-b74a-11eb-9956-30449703944d.png">

Could this be the culprit?

**Comment by t3chguy** [comment]
Sure, it could. That's a dependency of a dependency (of a dependency?)
You'd have to check the various dependency changelogs to see

**Comment by fooness** [comment]
I think I might have found the problem.

From the README of `html-webpack-plugin` via: https://github.com/jantimon/html-webpack-plugin/tree/4.x#minification

<img width="889" alt="Screen Shot 2021-05-17 at 20 08 26" src="https://user-images.githubusercontent.com/11408027/118536211-bad6c680-b74b-11eb-9718-c5cc83cd3b6f.png">

So, if I don’t understand this completely wrong … could the following line be changed to `minify: false`, maybe please?

<img width="686" alt="Screen Shot 2021-05-17 at 20 12 50" src="https://user-images.githubusercontent.com/11408027/118536664-4b150b80-b74c-11eb-91de-cb9c4acf0718.png">

https://github.com/vector-im/element-web/blob/develop/webpack.config.js#L389

**Comment by fooness** [comment]
@jryans @t3chguy Might I please ask you to have a look at the pull request in https://github.com/vector-im/element-web/pull/17349? Unfortunately, I’m not sure how to properly run tests and whatever else is needed to verify that everything works as intended, but I don’t think there should be any problems with this change?

**Comment by fooness** [comment]
Fixed in https://github.com/vector-im/element-web/pull/17349 and therefore closed.
