### ISSUE TITLE
Labs spinner can lock up and not animate

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17337]
### Description

![image](https://user-images.githubusercontent.com/2803622/118528796-118bd280-b743-11eb-97e2-832d809fcf78.png)
(imagine this is a gif ;P)

It takes ages (on my poor ~4€/M VPS homeserver?) to load the space overview. Pretty confusing to not see the spinner spinning.

### Steps to reproduce

- run synapse on a really cheap VPS
- join `#community:matrix.org`

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021051701-1
- **Homeserver**: synapse 1.34.0 (pypi)

**Comment by t3chguy** [comment]
That spinner is from Labs, right?

**Comment by HarHarLinks** [comment]
I have labs spinner enabled, yes.

Oh hey, it just started spinning? Was my homeserver that backed up by joining 5 rooms or something?

**Comment by t3chguy** [comment]
The spinning is all done locally, its unrelated to spaces. That spinner is client-side.

**Comment by HarHarLinks** [comment]
gonna repro and then submit logs
