### ISSUE TITLE
nicknames not displayed in search

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17343]
### Description

![image](https://user-images.githubusercontent.com/2803622/118545068-684ed780-b756-11eb-9cb3-567bb51aa0bf.png)

### Steps to reproduce

- search?

render names (and avatars?) as usual

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021051701-1

**Comment by robintown** [comment]
Duplicate of #560
