### ISSUE TITLE
Create an easier bug template for users who report a lot of bugs.

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17355]
#### Is your suggestion related to a problem? Please describe.
I'm always frustrated when I need to go through the template

#### Describe the solution you'd like.
A template for "advanced users"

#### Describe alternatives you've considered.
deleting everything and just free styling

#### Additional context
this will really increase productivity

**Comment by t3chguy** [comment]
It'll require a lot more back and forth a lot of the time when we need to know version etc.
Github supports personal templates, just prefill our template and save it.

![image](https://user-images.githubusercontent.com/2403652/118687104-8d962100-b7fc-11eb-8003-ca238326f875.png)

**Comment by turt2live** [comment]
Sorry, the template is here to ensure we get the detail we need. If the detail is presented in another way (such as by ignoring the template and writing freeform) then we're fine with that too.
