### ISSUE TITLE
Improve starting a DM when no results are returned

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17359]
If no users are found, we could encourage other ways to contact them, like sharing your matrix id/via matrix.to.

**Comment by niquewoodhouse** [comment]
I think this is quite tightly bound to #17365.

What it's like now for reference:
![image](https://user-images.githubusercontent.com/1587166/119683624-b4c3a280-be3b-11eb-8a5d-7a8e5db95397.png)

____

Some options here:

![image](https://user-images.githubusercontent.com/1587166/119683713-c86f0900-be3b-11eb-869f-f91373081d30.png)

![image](https://user-images.githubusercontent.com/1587166/119683762-d3299e00-be3b-11eb-8707-0a862095719e.png)

![image](https://user-images.githubusercontent.com/1587166/119683794-db81d900-be3b-11eb-96f5-42779f1817c3.png)

I think it might be useful to actually include this even if there are results returned.  For example, I might get 5 results for Roger Federer but none of them are my friend, or I'm not sure if they are.  So this might prove useful in that context.

![image](https://user-images.githubusercontent.com/1587166/119684000-0ec46800-be3c-11eb-97ca-3af0a8e02fc2.png)
![image](https://user-images.githubusercontent.com/1587166/119684034-15eb7600-be3c-11eb-842a-3131b06138ac.png)

**Comment by t3chguy** [comment]
This is very feasible, but seems to occupy a lot of vertical space which would mean it'll likely get scrolled off the bottom
