### ISSUE TITLE
Allow mass-joining sub-spaces

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#17352]
#### Is your suggestion related to a problem? Please describe.
Currently, to join sub-spaces, you need to click on the "Join" button for a sub-space, go back to the parent space, scroll down to the next sub-space, click "Join", etc.

#### Describe the solution you'd like.
It would be nice to be able to join all sub-spaces in a space with a single button click, or to select sub-spaces to join and join them all quickly.  Or possibly, the Join button could keep you on the parent space, so that you don't have to navigate back and lose your spot.

**Comment by SimonBrandner** [comment]
Closing in favour of [#17388](https://github.com/vector-im/element-web/issues/17388)
