### ISSUE TITLE
Improve sharing self when creating a DM

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17365]
From recruited user testing— users struggled to understand they could share a link for themselves when creating a DM.

**Comment by niquewoodhouse** [comment]
Based on the idea this is a papercut so small changes

As it currently is for reference

![image](https://user-images.githubusercontent.com/1587166/119694173-e725cd80-be44-11eb-8883-f8e137d32eb4.png)

______

**Stuck to bottom like Discord**

![image](https://user-images.githubusercontent.com/1587166/119694220-f1e06280-be44-11eb-85ab-9d81b86ddbb4.png)

**At top of dialog content as a CTA**

![image](https://user-images.githubusercontent.com/1587166/119694304-06245f80-be45-11eb-90d6-1ddd09b0d93b.png)

**Tabs to keep content changes on this view down**

![image](https://user-images.githubusercontent.com/1587166/119694775-7337f500-be45-11eb-87b6-826240de03ee.png)

![image](https://user-images.githubusercontent.com/1587166/119695233-e3467b00-be45-11eb-9e24-236a9479d41f.png)

**As an extra line of copy in the intro**

![image](https://user-images.githubusercontent.com/1587166/119694829-821ea780-be45-11eb-95d6-0f3b94ea5500.png)

**Comment by t3chguy** [comment]
Any of the options are feasible, the tabbed approach is probably a tad bit more work

**Comment by niquewoodhouse** [comment]
On reflection, think this makes the most sense.

- Puts the matrix link underneath the existing form.  If it goes at the top, I worry it might lead to more people using the link than the form, and there are known papercuts in that experience.
- Solves #17359 by putting something at the end of the list of results that points to the link

@t3chguy I tried using theme colour for the new things, I don't mind if the copy url field has its own pre-existing css for colours etc, we can just use that.

![invite-dialog-01](https://user-images.githubusercontent.com/1587166/119801622-cd809680-bed5-11eb-923e-51fd00696108.gif)
