### ISSUE TITLE
Explore smaller avatars in room list

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17364]
Design hunch: Size of avatars & visual rhythm of room list make it harder to scan and use. Explore visually, looking for simple actionable tweaks.

**Comment by niquewoodhouse** [comment]
@nadonomy I would be interested in hearing the product take on that point

>  Discord has no channel avatars and it seems to work fine

Slack and Microsoft Teams have no channel avatars either.  When the room list was rebuilt last year there was a debate on whether avatars were needed for this, and the conclusion was avatars are a bit of personality and branding to a room.  I just wonder if we still feel that way?  

Quill has a mix, with favourites getting a bigger image and everything else being smaller

![image](https://user-images.githubusercontent.com/1587166/119515284-a3ac6000-bd6d-11eb-8930-556e2bafe2bf.png)

Going to no avatars might mean a cleaner room list but it might also require further changes - eg how `breadcrumbs` appear

**Comment by niquewoodhouse** [comment]
There aren't many quick options as each avatar in the room list needs to be the same size, regardless of whether previews are on or not.

Reducing the avatar to 28px and tweaking some elements is about as far as we can go.  It makes me list shorter but does of course remove some of the breathing space.

<img width="1464" alt="compare-1" src="https://user-images.githubusercontent.com/1587166/119829552-4510ee80-bef3-11eb-9d06-c7af0741f7e6.png">

**Comment by germain-gg** [comment]
These explorations have happened on Figma
