### ISSUE TITLE
Upgrade to Element Home Fails Login

### ISSUE THREAD

**Issue by gtwilliams** [vector-im/element-web#17372]
### Description
I ran Upgrade to Element Home and created gtwilliams subdomain.  Dialog box would not progress after clicking Change Password.  Clicked the big X in upper-right-hand corner and now no way to log in.

You got my money, but won't let me log in.

I can still log into matrix.org as gtwilliams.

### Steps to reproduce
Log in to @gtwilliams:gtwilliams.ems.host

This is refused.  Reset password says no such E-mail address.

E-mail address used for sign-up: gtwilliams@gmail.com

Log: sent/not sent?    Y -- [rageshake.tar.gz](https://github.com/vector-im/element-web/files/6505394/rageshake.tar.gz)

For the web app: Chrome 90.0.4430.212 on Fedora 33, KDE https://app.element.io/

**Comment by turt2live** [comment]
Sorry the upgrade didn't work out for you :( 

The Element Home offering is managed by Element Matrix Services, a department of Element. It would be best to contact them via email at ems-support@element.io so they can figure out what went wrong and keep you updated.

Unfortunately, we won't be able to resolve this issue over github, but the support team should be able to help you out.
