### ISSUE TITLE
Replace ":" by "=" in matrix-react-sdk/src/CallHandler.tsx line #157

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#17377]
Should in `matrix-react-sdk/src/CallHandler.tsx` line https://github.com/matrix-org/matrix-react-sdk/blob/cf384c2a54536abfec81d9f83379ce620b09fb66/src/CallHandler.tsx#L157 the code fragment ...

    private pstnSupportCheckTimer: NodeJS.Timeout; 

be replaced by

    private pstnSupportCheckTimer = NodeJS.Timeout; 

?

**Comment by t3chguy** [comment]
No. `NodeJS.Timeout` is a type

This is typescript describing the type of `pstnSupportCheckTimer`

**Comment by menturion** [comment]
Thanks, didn't know that NodeJS.Timeout is a type. Thought is  an environment var of Node.
