### ISSUE TITLE
Don't require consumers of matrix-react-sdk to use a specific build system

### ISSUE THREAD

**Issue by YousefED** [vector-im/element-web#17380]
I'm trying to get started with https://github.com/matrix-org/matrix-react-sdk, but to be honest hasn't been smooth sailing so far. The library is presented as a "react-based SDK", but it seems difficult to integrate as an SDK into an existing project like regular NPM modules:

Things I'm running into (I'll update this list as we go):
- package.json specifies "typings", but directs to `./lib/index.d.ts` which is not included in NPM.
- In the reference client (`element-web`), imports are directly from the source ("matrix-react-sdk/src/MatrixClientPeg"). Usually, "MatrixClientPeg" should just be exported from "matrix-react-sdk". If we import it this way, it means my client application should build the typescript files, which basically means a library I want to consume (matrix-react-sdk) is enforcing a specific build system on me (e.g.: it now complains `$webapp/i18n/languages.json` can't be resolved because I haven't defined `$webapp` in my webpack config).

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk#matrix-react-sdk

> As of Aug 2018, the only skin that exists is [vector-im/element-web](https://github.com/vector-im/element-web/); it and matrix-org/matrix-react-sdk should effectively be considered as a single project (for instance, matrix-react-sdk bugs are currently filed against vector-im/element-web rather than this project).
