### ISSUE TITLE
don't hide the devtools button for non-admin space users

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17399]
non-admins should be able to use /devtools too

**Comment by t3chguy** [comment]
We don't have anywhere to put it since non-admins don't get space settings due to pointless complexity

**Comment by jonaharagon** [comment]
Just a thought: You could have a devtools button in the global settings, Help & About > Advanced, which closes the settings window and opens devtools. Replace the button in room settings with it too, and then you'll just have one place to access it from any view and you won't run into this again the next time you add a big feature.

**Comment by t3chguy** [comment]
Its in quick settings with dev mode enabled
