### ISSUE TITLE
Add libera.chat to IRC bridges

### ISSUE THREAD

**Issue by Kreyren** [vector-im/element-web#17398]
Add https://libera.chat/ in element to be accessible from this menu
![image](https://user-images.githubusercontent.com/11302521/118846031-981feb80-b8cc-11eb-8efa-b11eab4512bb.png)

**Comment by t3chguy** [comment]
That list comes from the homeserver to which you are connected to - "Your server"
I suggest contacting your server or filing a request in https://github.com/matrix-org/matrix-appservice-irc/issues/208
