### ISSUE TITLE
VoIP events sometimes not making it to CallEventHandler?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17393]
We may have a regression on develop that means voip events are visible in the timeline but somehow don't actually affect the call state machine. Reported failure was one user on develop and another on stable: the user on stable answered the call and develop could see the answer event but the call kept ringing.

Unsure what recent changes could have caused this: the multi-stream stuff doesn't seem like it would cause this, neither does the lazy decryption (answer must have been decrypted if it's visible?)

I also had another call yesterday where I got a regular notification of a call event in a 1:1 room but the call didn't ring.

**Comment by SimonBrandner** [comment]
Will be fixed by [#1698](https://github.com/matrix-org/matrix-js-sdk/pull/1698)

**Comment by SimonBrandner** [comment]
For context view today's messages in #element-dev

**Comment by dbkr** [comment]
I just got similar symptoms to this again after hanging up a call with someone and then them calling back, I could see the call events arriving but it didn't ring.

**Comment by SimonBrandner** [comment]
Yeah, I've also experienced some oddities around this

**Comment by dbkr** [comment]
I think francois just experienced this too and it didn't fix itself until he refreshed cache, rather than just reloading, which seems interesting...

**Comment by gsouquet** [comment]
I have not been able to reproduce this so far. But I am putting this at the top of my to-do list 

If anyone manages to reproduce this consistently I would be keen to understand how

**Comment by dbkr** [comment]
Oh, on the call that I got this bug on, the other person somehow managed to send me 11 invites: I can definitely believe this would break things on the receiver side, although how this could happen with an element-web caller, I don't know - the action handler in CallHandler is synchronous, so it seems like multiple place_call dispatches would have to make it into the queue before the first was processed...

**Comment by dbkr** [comment]
Sorry, I just got this again: rageshake linked

**Comment by dbkr** [comment]
Only repro steps I can think of that might align with the ways I've got this (ie. when people message me and then start a call):
 * Have room X as a DM with someone
 * Switch to some room other than room X
 * Close element & re-open. Element opens in not-room-x
 * Receive message in room X, switch to room X
 * Receive call in room X

The theory would be that you'd see the call invite event but the call would not ring. If you hang up & place another call in that room, it would then ring.

**Comment by dbkr** [comment]
Wait, never mind - apparently I got a hangup for this call before the invite 🙃
