### ISSUE TITLE
element-web runs offsite javascript from vector.im and riot.im

### ISSUE THREAD

**Issue by sneak** [vector-im/element-web#17405]
app = element-web
version = 1.7.28

When using a selfhosted element talking to a sellfhosted server, enabling the Spaces feature establishes connections to `vector.im`, and when trying to view a jitsi video call inline fails with a "JavaScript is disabled.  For this site to work you have to enable JavaScript." error when JS is permitted on the selfhosting domain but denied on others (and it shows it's trying to exec remote javascript from `riot.im` and `vector.im` domains).

What's the point of having both a server app and a client app that can be selfhosted if it has to phone home to the developers to download remote executable code from an untrusted server to work right?

**Comment by t3chguy** [comment]
You can specify your own integrations manager, etc in config.json; https://github.com/vector-im/element-web/blob/develop/docs/config.md

**Comment by sneak** [comment]
<img width="627" alt="Screen Shot 2021-05-19 at 13 45 12" src="https://user-images.githubusercontent.com/408977/118882026-8f1d2300-b8a8-11eb-81f1-668096d6f2f9.png">

<img width="850" alt="Screen Shot 2021-05-19 at 13 44 57" src="https://user-images.githubusercontent.com/408977/118882039-92181380-b8a8-11eb-855f-32beeb988189.png">

<img width="613" alt="Screen Shot 2021-05-19 at 13 44 51" src="https://user-images.githubusercontent.com/408977/118882050-96443100-b8a8-11eb-989e-9b45856e8872.png">

I'm not the server admin, I'm just a user that doesn't want to use Matrix/Vector services.  Is this sort of server configuration the default setting?

**Comment by t3chguy** [comment]
> Is this sort of phone-home-to-central-surveillance server configuration the default setting?

How is accessing the configured services a central-surveilance?

The default config is not feature-less, and its also not magic and those services don't exist in the ether, they have to exist somewhere.

Given that Element doesn't actually come with a config file, only a sample, the onus is on the administrator setting it up to not leave services they do not desire to access in the config; https://github.com/vector-im/element-web/blob/develop/config.sample.json

**Comment by t3chguy** [comment]
> enabling the Spaces feature establishes connections to vector.im

Nope, it doesn't.

Before enabling spaces:

![image](https://user-images.githubusercontent.com/2403652/118882652-5141ee00-b8ec-11eb-85fd-5622f242d5c5.png)

After enabling spaces:

![image](https://user-images.githubusercontent.com/2403652/118882710-60c13700-b8ec-11eb-856d-7f2752c65ffa.png)


And that v1 request is for the Identity Server, which you can turn off in config.json or even as a user:
![image](https://user-images.githubusercontent.com/2403652/118882792-76cef780-b8ec-11eb-9089-9cb4fc5aae53.png)

(see big red button)

**Comment by sneak** [comment]
I'm an end user of this selfhosted (not by me) instance; I don't want to use the vector services or have my data be subjected to your privacy policy. 

It seems that if this is the config that server admins end up with, then this ecosystem probably isn't very privacy-friendly, and I can't yet recommend it to end users who simply want to use a messaging tool without connecting to the developers of that tool.

**Comment by t3chguy** [comment]
> when trying to view a jitsi video call inline fails with a "JavaScript is disabled. For this site to work you have to enable JavaScript." error when JS is permitted on the selfhosting domain but denied on others (and it shows it's trying to exec remote javascript from riot.im and vector.im domains).

The Jitsi you are accessing is hosted at `jitsi.riot.im` - what exactly do you expect here? The javascript being loaded here is loaded inside a sandboxed iframe.

![image](https://user-images.githubusercontent.com/2403652/118883372-142a2b80-b8ed-11eb-9722-4835e32e584b.png)

I cannot reproduce any Javascript being loaded from vector.im when making a Jitsi call - unless you go to `Edit widgets, bridges & bots` which uses the vector.im integrations manager, again in a sandboxed iframe, to provision their bots/bridges/etc

![image](https://user-images.githubusercontent.com/2403652/118883429-21dfb100-b8ed-11eb-9ea9-9e88aca5265a.png)


If you don't want to use the Jitsi provided by Vector then you can make use of `/addwidget` though keep in mind if someone else adds a Jitsi call to the room and you opt to join it then obviously you have to join the Jitsi of whatever domain they chose during the setup of the call otherwise you'd be in your very own call and not the one with your peer.

**Comment by hex-m** [comment]
You can check if your Server defines a custom Jitsi Meet instance to be used by checking the `.well-known` entries. e.g. `https://kif.rocks/.well-known/matrix/client`

```
{
  "m.homeserver": {
    "base_url": "https://matrix.kif.rocks"
  },
  "m.identity_server": {
    "base_url": "https://matrix.kif.rocks"
  },
  "im.vector.riot.jitsi": {
    "preferredDomain": "meet.kif.rocks"
  }
}
```

If there is none defined the Element clients fall back to https://jitsi.riot.im/.

To avoid that you can use Element-Desktop and [change the local config](https://github.com/vector-im/element-desktop#user-specified-configjson) to point to your preferred Jitsi Meet instance.

**Comment by sneak** [comment]
Thanks for the support, sorry for the confusion.  Changing local client configs is beyond the scope of abilities of client users in most cases.  The fact that things will default/fall back automatically to centralized/vector.im services is something that should be fixed or documented more loudly, as the server admin of the instance in question was entirely unaware of these settings and 3p client info leakage until I brought it to their attention.
