### ISSUE TITLE
Mentions ignore homeserver domains

### ISSUE THREAD

**Issue by dpassens** [vector-im/element-web#17404]
### Description

When deciding whether a user has been mentioned, Element only looks at the localpart of the user id, not the domain name.

### Steps to reproduce

- Join a room with somebody with the same local user id but different homeserver.
- Wait until they get mentioned
- You will get a notification and the message will be highlighted like you've been mentioned.

Logs being sent: yes

As you can see, I am receiving mentions for David Prieto (@david:gnome.org), but I am @david:passens.org.

![Screenshot_20210519_223120](https://user-images.githubusercontent.com/48860777/118881383-4dfe3080-b8f3-11eb-8d2c-3968126f669c.png)

### Version information

- Desktop
- Arch Linux
- Element version: 1.7.24
- olm version: 3.2.1

**Comment by t3chguy** [comment]
This is a Matrix spec issue, the push rules are specced there and evaluated by both client & server (for push).

**Comment by dpassens** [comment]
Ah, I found [a spec issue for this](https://github.com/matrix-org/matrix-doc/issues/2319).  Should this issue be closed since it's not element's responsibility or left open until the spec is fixed?

**Comment by t3chguy** [comment]
Better to track it in one place
