### ISSUE TITLE
clicking the facepile of members on a spaces view does nothing if MemberList is already open

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17406]
we should change the label if MemberList is already open to just list the names rather than say 'view members'

**Comment by daniellekirkwood** [comment]
<img width="490" alt="Screenshot 2022-04-12 at 10 44 06" src="https://user-images.githubusercontent.com/89144281/162931582-91eccd39-6778-4656-a7dd-75100b0442f2.png">

I suggest changing the copy in the hover over to say: "XXX members" when the drawer is open (as seen in the screenshot). 
If the drawer is closed the copy reads the same: "View all XXX members"

Whoever picks this up, please comment how complicated this change is.

**Comment by kittykat** [comment]
This is ready to develop, implementing Danielle's suggestion of changing copy when the right panel is open.
