### ISSUE TITLE
Add temporary workaround to synapse UIA auto-advancing on deactivation

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17422]
Otherwise we end up deactivating the user's account all because we queried for flows. https://github.com/matrix-org/synapse/issues/9754

Could be avoided with a 'I understand the risks, continue' button *before* the UIA flow check.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/16870

**Comment by marcelsby** [comment]
I've accidentally deactivated my account because of this auto-advance, have anyway to recover it?

**Comment by turt2live** [comment]
Deactivated accounts are typically unrecoverable due to the information needed to verify the account owner being purged in the process. You can try contacting your homeserver administrator though. For matrix.org, that'd be support@matrix.org

**Comment by marcelsby** [comment]
Thanks, i'll contact them.

**Comment by clokep** [comment]
I think this is a duplicate of #16870, but as I wrote there Synapse v1.37.0 will remove this behavior, see matrix-org/synapse#10184.

**Comment by turt2live** [comment]
closing due to https://github.com/vector-im/element-web/issues/16870#issuecomment-862614884
