### ISSUE TITLE
Answer more common questions in the deactivate dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17421]
People think that the user ID will be released for them to register again, or that the account can be reactivated. The paragraphs of copy might need trimming down.

**Comment by Palid** [comment]
@daniellekirkwood can you have a look on this one?

**Comment by daniellekirkwood** [comment]
Happy to, thanks for the tag @Palid 

@turt2live Do you have a screenshot or steps to reproduce? I'm not quite understanding the ask yet. Thanks!

**Comment by BrenBarn** [comment]
There really needs to be some better terminology for this, since people routinely ask in the Matrix HQ room about how to reactivate their account.  I get that "delete" isn't ideal either because it may make people think the name is "gone" and a new account with that name can be recreated.  But I still think "delete" is preferable to "deactivate" as at least people are more likely to realize that deletion is a permanent action.  Or we could go through a thesaurus or whatever and find some better phrasing.  (Destroy?  Nuke?  Annihilate?  Permafreeze?)

**Comment by turt2live** [comment]
@daniellekirkwood This is the current deactivation dialog (authentication at the bottom may vary):
![image](https://user-images.githubusercontent.com/1190097/148887816-ecfe7977-5fca-4bc9-87c4-aee2b8f4dc86.png)

It's pretty wordy.

The dialog's text is largely focused on the privacy implications, which is good but doesn't really help the end user understand that it's truly impossible (for us) to re-activate the account. We might want to take a look at the word "deactivate" as a whole - though technically accurate, it provides false hope that an account can be re-established.

Conversations with Trust & Safety might be required to keep the legal accuracy of the text without sacrificing the readability.

**Comment by daniellekirkwood** [comment]
Thank you! 

I am adding the labels needed to get this in the right place on our backlog.

**Comment by kittykat** [comment]
Proposed text:

> **Deactivate Your Account**
> 
> Please confirm that you would like to deactivate your account. If you proceed:
> - You will not be able to reactivate your account
> - You will no longer be able to log in
> - No one will be able to reuse your username (MXID)
> - You will leave all rooms and DMs that you are currently in
> - Your friends will not be able to find you with your email or phone number: you will be removed from the identity server
> 
> Your old messages will still be visible to people who received them, just like emails you sent in the past. Would you like to hide your sent messages from people who join rooms in the future?
> - [ ] Hide my messages from new joiners
> 
> To continue, please enter your account password:
> <text entry>

@daniellekirkwood what do you think about making each of those list items a tick box that a user has to tick to show that they understand what will happen? IMO, deactivating an account should be difficult because it's terminal.

**Comment by daniellekirkwood** [comment]
The text is great, I have a couple of minor suggestions to add to it (see below).

As to the check boxes @kittykat, let's leave the scope of this issue to be the text improvement - if we still get feedback that user's aren't reading correctly then we can add them in later. 

<hr />

**Deactivate Your Account**

Confirm that you would like to deactivate your account. If you proceed:
- You will not be able to reactivate your account
- You will no longer be able to log in
- No one will be able to reuse your username, including you (this MXID will remain unavailable)
- You will leave all rooms and DMs that you are in
- Your friends will not be able to find you with your email or phone number; you will be removed from the identity server

Your old messages will still be visible to people who received them, just like emails you sent in the past. Would you like to hide your sent messages from people who join rooms in the future?

- [ ] Hide my messages from new joiners

To continue, please enter your account password:

**Comment by kittykat** [comment]
Minor change:

**Deactivate Your Account**

Confirm that you would like to deactivate your account. If you proceed:

- You will not be able to reactivate your account
- You will no longer be able to log in
- No one will be able to reuse your username (MXID), including you: this username will remain unavailable
- You will leave all rooms and DMs that you are in
- You will be removed from the identity server: your friends will no longer be able to find you with your email or phone number

Your old messages will still be visible to people who received them, just like emails you sent in the past. Would you like to hide your sent messages from people who join rooms in the future?

- [ ]  Hide my messages from new joiners

To continue, please enter your account password:
