### ISSUE TITLE
browser history back does not preserve current space

### ISSUE THREAD

**Issue by ashkitten** [vector-im/element-web#17426]
### Description

i use the browser history to jump back and forth between conversations quickly. with spaces, i often want to view a room in the context of its space. however, any time i use browser history forward or back, it switches to the "all rooms" meta-space.

### Steps to reproduce

- click on a space
- press browser back
- press browser forward

i expect that after using browser forward, i should be looking at the room inside the space. instead, i am looking at it in the "all rooms" meta-space.

### Version information

- **Platform**: web
- **Browser**: firefox 88
- **OS**: nixos
- **URL**: self-hosted element 1.7.28

**Comment by SimonBrandner** [comment]
Could have the same cause as: [#17321](https://github.com/vector-im/element-web/issues/17321)

**Comment by t3chguy** [comment]
This should be fixed given same cause as #17321 - shout if you see this again from next release
