### ISSUE TITLE
any plans to move away from jitsi?

### ISSUE THREAD

**Issue by autoteelar** [vector-im/element-web#17424]
i feel like jitsi is a pretty jank solution, its more for buisness meetings than just hanging out with friends, and i feel like there is much to improve upon with jitsi, i saw the 1:1 calling and i find it works way better than jitsi, idk if its using jitsi or what but jitsi i get very low, usually sub 5 fps screenshare and worse camera quality while 1:1 i get at least 30 at all times, and the camera quality is phenomenal, i was just wondering if this means that later on this will become the standard and replace jitsi with time, and if not if theres any plans to move away from jitsi

**Comment by t3chguy** [comment]
https://matrix.org/blog/2020/12/25/the-matrix-holiday-special-2020#2021

**Comment by robintown** [comment]
https://github.com/matrix-org/matrix-doc/pull/2359 as well

**Comment by SimonBrandner** [comment]
This is the plan and the work has already started/will start soon, therefore I don't think there is a reason to keep this issue open
