### ISSUE TITLE
Keybind to switch Spaces 

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [vector-im/element-web#17420]
I use the alt+up/down keybinds to switch rooms more than I use the mouse to click on rooms. It's just more efficient. A keybind to switch spaces would be nice (I was thinking alt+ctrl+up/down because of prior experience with Discord) and would greatly increase the usability of Spaces on Element.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17128
