### ISSUE TITLE
Sending images from the clipboard

### ISSUE THREAD

**Issue by xRealNeon** [vector-im/element-web#17428]
Can you implement that I can send images from the clipboard.

## How I envision this
I make for example a screenshot and go to the Element web client and do `CTRL + V` and the Image gets uploaded.

**Comment by t3chguy** [comment]
This already happens. Some browsers/OSs don't support copy/paste from your desktop but copying the image 

![image](https://user-images.githubusercontent.com/2403652/119108585-3e2c3c80-ba18-11eb-9137-e656c993f7f9.png)

will work

**Comment by t3chguy** [comment]
> I make for example a screenshot and go to the Element web client and do CTRL + V and the Image gets uploaded.

This is my entire workflow lol, I use the screenshot utility built into Mac or Windows then paste directly into Element Web or Desktop

**Comment by t3chguy** [comment]
If it isn't working for you, please send what http://madebyevan.com/clipboard-test/ shows you when you paste the same thing into it

**Comment by SimonBrandner** [comment]
Related [#16255](https://github.com/vector-im/element-web/issues/16255)

**Comment by xRealNeon** [comment]
## Ok I give some more info:

OS: Ubuntu 20.04.2 LTS
Screenshot utility: Flameshot
Browser: Firefox

## What I do

I pressed `CTRL + V` and used the context menu but both won't work

![Peek 2021-05-21 10-42](https://user-images.githubusercontent.com/20997346/119109261-52c10280-ba21-11eb-9fdd-3ff15e5d7745.gif)

**Comment by xRealNeon** [comment]
> If it isn't working for you, please send what http://madebyevan.com/clipboard-test/ shows you when you paste the same thing into it

It does nothing but for example on Twitter or GitHub it works

**Comment by t3chguy** [comment]
Well given it works for me and seemingly everyone else it would be grand if you actually filled in the issue template with information about your environment so someone might have a chance to reproduce.

**Comment by xRealNeon** [comment]
![2021-05-21_10-50](https://user-images.githubusercontent.com/20997346/119110326-5012dd00-ba22-11eb-91ab-f32d112a8943.png)
![2021-05-21_10-50_1](https://user-images.githubusercontent.com/20997346/119110363-5903ae80-ba22-11eb-9e98-83790b75ee19.png)

**Comment by xRealNeon** [comment]
I got  it I had it disabled on Firefox 🤦
