### ISSUE TITLE
Can't upload an image from clipboard

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#17436]
### Description

I can't paste a screenshot.

### Steps to reproduce

- Get some kind of pixel data on the clipboard
- In a conversation press ctrl+v
- Press the upload button to try and start the upload

Result:
![image](https://user-images.githubusercontent.com/152227/119202937-2b564e00-ba92-11eb-8232-7376c4ca7554.png)

There's not anything else to it, unfortunately.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows 10 21H1
- **Version**: 1.7.28

**Comment by thany** [comment]
Also why PNG? 🤨
There are better image formats these days, including ones that compress losslessly...

**Comment by t3chguy** [comment]
> Also why PNG? 🤨

Ask your browser... That's what it pastes

You can see the raw data at http://madebyevan.com/clipboard-test/

**Comment by thany** [comment]
I'm using the desktop application. No browser.

**Comment by t3chguy** [comment]
The desktop application is Electron which is Chromium.

The logs have server errors in them

```
2021-05-21T22:08:11.830Z E request failed: Unexpected token < in JSON at position 0
ConnectionError: request failed: Unexpected token < in JSON at position 0
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:814466
    at XMLHttpRequest.s.onreadystatechange (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:810686)
```

as well as rate limit errors later on

```
2021-05-21T22:11:03.899Z E Server returned 429 error
Error: Server returned 429 error
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:814984
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:815049
    at Object.callback (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:814203)
    at vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:36602
    at XMLHttpRequest.r.onreadystatechange (vector://vector/webapp/bundles/630944a4d5ff2110b1fc/vendors~init.js:2:36626)
```

**Comment by thany** [comment]
I suppose that first piece of error is useful.

But rate limits? I tried it maybe three times, and it failed even the first time.

**Comment by t3chguy** [comment]
Element isn't the thing rate-limiting you, the 429 is from your Matrix homeserver (matrix.org)

**Comment by t3chguy** [comment]
@thany can you still reproduce this issue?
There was a matrix.org reboot at precisely 2021-05-21T22:08 which would explain all the NOT JSON errors

**Comment by t3chguy** [comment]
Presuming this was a matrix.org outage, an internal issue was raised for matrix.org to return JSON errors during restarts to prevent such cryptic errors.
