### ISSUE TITLE
Spaces feature request created channels kick/ban/invite sync

### ISSUE THREAD

**Issue by sign-out** [vector-im/element-web#17435]
it would be wonderful if in a space if the channels that are only in that space have all of there user lists for invitations, kicks and bans synced.
it would also be cool if it listed all channels that are apart of the space regardless if you are a member of them as long as you have permission to join them.

**Comment by t3chguy** [comment]
This is an anti-goal of Spaces, it does not aim to force a user into all the rooms within a given space

**Comment by t3chguy** [comment]
> it would also be cool if it listed all channels that are apart of the space regardless if you are a member of them as long as you have permission to join them.

You can do this by marking them as Suggested

![image](https://user-images.githubusercontent.com/2403652/120311909-faff8280-c2cf-11eb-898e-9c8a25c7dfce.png)

**Comment by t3chguy** [comment]
> kicks and bans synced.

Is now done by the client when you kick/ban someone from a Space

**Comment by niquewoodhouse** [comment]
@sign-out Can I check if you're satisfied with the way the banner/kicker has the option to ban/kick from specific things or all things they'll allowed to?

**Comment by robintown** [comment]
Closing as this is presumably fixed by the above changes, and we have not gotten further feedback from the reporter
