### ISSUE TITLE
"Remove recent messages" actually removes state events

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#17445]
### Description - Steps to reproduce

https://matrix.to/#/!OluOzqbTJgecdDIuKn:half-shot.uk/$162179252036cmnLU:feline.support?via=half-shot.uk&via=matrix.org&via=tchncs.de

>  The bot has gone out of Sync for me due to Element being a bit over zealous when i ordered a Remove Recent messages due to having to clean out a lot of messages that needed to be redacted due to breaking the rules of the room and the channel on the other side of the bridge. 
> Yes Element Remove Recent messages is EXTEMELY over zealous.
> It can remove s— like Encryption status of a room as far as i am aware. 
> Even tho that is completely not allowed by Spec

**Comment by robintown** [comment]
I wonder whether it's preferable to redact everything *but* non-message events, or to have a predefined list of message event types to redact, given that there could be custom message event types in use that we don't know about
