### ISSUE TITLE
element:// deeplinking stopped working on Chrome macos

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#17446]

**Comment by t3chguy** [comment]
Actually I take it back.
It works from Safari but not from Chrome
Very strange either way

![image](https://user-images.githubusercontent.com/2403652/119275249-db9b9200-bc0b-11eb-84bc-617eb24c2c98.png)

**Comment by simonmichael** [comment]
I'm using Safari, and I always get the choice to download Element or use the web version; it's not opening my installed Element.

**Comment by novocaine** [comment]
Upstream https://github.com/matrix-org/matrix.to/issues/230

**Comment by novocaine** [comment]
The following work okay: 

`open -a Element\ Nightly element://vector/webapp/#/home`
`open -a Element\ Nightly element://vector/webapp/#/user/@jsalter:matrix.org`

However, this doesn't work, and if Element is already open, causes the Element window to stay topmost until you quit it

`open -a Element\ Nightly element://vector/webapp/#/room/#element-dev:matrix.org`
