### ISSUE TITLE
Only have permission to upload images and files from my Downloads directory

### ISSUE THREAD

**Issue by 4of92000** [vector-im/element-web#17441]
### Description

Element on desktop only allows me to upload files from my Downloads directory. I am also experiencing #17436.

### Steps to reproduce

- Open a chat in Element
- Click the "Upload file" paperclip on the right-hand side of the text input

I should have the standard file upload dialog box where I can access and upload any file I have permissions to. Instead, I have a dialog box that only allows me access to `~/Downloads`.

![Screenshot_20210522_102205](https://user-images.githubusercontent.com/5383348/119232140-94ca7100-bb13-11eb-9bce-fa4d4b73c20a.png)

Logs being sent: no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Debian sid; Element installed via Flathub
- **Version**: 1.7.28

**Comment by t3chguy** [comment]
This is specific to the community maintained Flatpak; see https://github.com/flathub/im.riot.Riot/issues/33
