### ISSUE TITLE
youtube embeds dont work

### ISSUE THREAD

**Issue by autoteelar** [vector-im/element-web#17449]
![image](https://user-images.githubusercontent.com/76745649/119315901-52ed1800-bc44-11eb-86ca-45ef4bf60b32.png)

### Description

youtube embeds do not show any info at all about what you are watching, i think it should at least show the title and the picture.

### Steps to reproduce
send a youtube url in the chat

Describe how what happens differs from what you expected.
i expected the thumbnail of the youtube video and title but instead got: Before you continue to YouTube
Sign in a Google company Before you continue to YouTube Google uses cookies and data to: Deliver and maintain services, like tracking outages and protecting against spam, fraud, and abuse Measure audience engagement and site statistics to understand how our services are used

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?
web browser
For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version? firefox
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Linux 
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?
app.element.io

**Comment by t3chguy** [comment]
URL Previews are generated by your Matrix homeserver.
This is an issue which you should raise with your server's support/software.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/3466 would be an alternative which does not rely on the Matrix server

**Comment by autoteelar** [comment]
thats what im doing, @t3chguy, this is matrix.org homeserver

**Comment by t3chguy** [comment]
Element Web/Desktop is not the support for the matrix.org homeserver instance. This repo is for Element Web/Desktop bugs

**Comment by autoteelar** [comment]
care to redirect me to where i should be if this isn't the place? this is an element-web issue, and if not care to explain how is this not a bug?

**Comment by t3chguy** [comment]
This bug is specific to Synapse url previews of youtube. https://github.com/matrix-org/synapse/issues/9733

**Comment by autoteelar** [comment]
Ive tested this in multiple different homeservers just to see and i get the exact same thing, i think theres more to it than just that

**Comment by t3chguy** [comment]
Synapse is the most common homeserver software.
Element just asks your matrix server for a preview - using this API https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-media-r0-preview-url
It doesn't fetch previews directly to not reveal your IP address to third parties, e.g malicious user posts a link to their own webserver in a public room now gets IP addresses of all active users which fetched URL previews.
