### ISSUE TITLE
SSO: Add support for connecting existing accounts to social accounts

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [vector-im/element-web#17448]
#### Is your suggestion related to a problem? Please describe.
I want to sign in to my `matrix.org` account without using an password with either my Twitter, GitHub, GitLab SaaS or Google account, but when I click one of them and authorize, I will need to create a new one again.

#### Describe the solution you'd like.
An setting under the General section for managing connected social accounts.

#### Describe alternatives you've considered.
Possibly show prompt if the email address matches any existing account (looks kinda privacy violation for some, but we might need to show `Enter your password to connect`) or show an `Connect existing account` link underneath the **Continue** button in SSO screen instead.

#### Additional context

While this issue should be in Synapse's issue tracker or probably submit this as an MSC, I would like to submit this issue as an heads up.

**Comment by t3chguy** [comment]
No point tracking this in two places, best to watch it in matrix-doc then once something is done there we can open a spec compliance bug here.
