### ISSUE TITLE
Support for base URL / subfolder reverse proxy

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#17459]
#### Is your suggestion related to a problem? Please describe.
I prefer to host my application reverse proxies on subfolders rather than subdomains (domain.com/element as opposed to element.domain.com).

(I'm hosting this via Docker and have it proxied through Nginx, if that makes a difference.)

#### Describe the solution you'd like.
Many self-hosted applications have the option to specify a base URL that allows the application to build and server pages appropriately when not proxied through a subdomain.

#### Describe alternatives you've considered.
N/A

#### Additional context
N/A

**Comment by t3chguy** [comment]
Hmm, Element should function fine in a subdirectory, before the rebranding it used to run on 

https://riot.im/app
https://riot.im/develop
https://riot.im/staging

just fine

**Comment by es9o** [comment]
I'm admittedly not well-versed in Nginx, but I'm using the usual template for reverse proxies and adding the additional options specified in the README:

location /element {
	
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app element;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
		
	add_header X-Frame-Options SAMEORIGIN;
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";
	add_header Content-Security-Policy "frame-ancestors 'none'";
		
 }

This leads me to a "404 Not Found" error. I use the same template (minus the last four lines recommended in the README) for all of my other services - so I think there must be an Element idiosyncrasy I'm missing.

**Comment by t3chguy** [comment]
I think the only bit you're missing is the trailing slash on `proxy_pass`

-> `        proxy_pass $upstream_proto://$upstream_app:$upstream_port/;`

Which will strip the `/element` path being sent to the upstream

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

**Comment by es9o** [comment]
I did try that - and every other combination of / on the various lines - but no success. Adding the trailing slash where you suggested brings a blank page when navigating to "mydomain.com/element".

**Comment by es9o** [comment]
> I think the only bit you're missing is the trailing slash on `proxy_pass`
> 
> -> ` proxy_pass $upstream_proto://$upstream_app:$upstream_port/;`
> 
> Which will strip the `/element` path being sent to the upstream
> 
> http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

I did try that - and every other combination of / on the various lines - but no success. Adding the trailing slash where you suggested brings a blank page when navigating to "mydomain.com/element".

**Comment by t3chguy** [comment]
You'll want `mydomain.com/element/` (note the trailing slash) otherwise all relative resource accesses will go back to the root of the domain which is wrong. You can do this via a redirect - https://bluegrid.io/edu/how-to-add-a-trailing-slash-on-urls-in-nginx/

An nginx config like the following works for me:

```
    location ~/element(.*)$ {
        set $upstream_app 172.18.0.2;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port$1;

        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Content-Security-Policy "frame-ancestors 'none'";

    }
```

Related https://serverfault.com/questions/792326/nginx-proxy-pass-using-subfolder
