### ISSUE TITLE
Holding and resuming with video results in one way video

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17450]
### Description

Holding and resuming with video results in one way video for the passive side

### Steps to reproduce

- Phone with video
- put call on hold
- resume call
- the passive side sees no video

Log: sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome, version: 90.0.4430.212.
- **OS**: Windows
- **URL**: develop.element.io

**Comment by SimonBrandner** [comment]
This _might_ be on me, though I recall this working last time I tested - I'll look into it

(I'd assign myself but I am on a phone..)

**Comment by SimonBrandner** [comment]
Also, it might be good to know: @chagai95, what browser is the oponent using?

**Comment by SimonBrandner** [comment]
I can repro this if the user being put on hold is on Chromium. Works fine with FF

**Comment by SimonBrandner** [comment]
It looks like this happens on [1.7.26](https://riots.im/1.7.26) (but it happens only for video) and that was before my rewrite. @dbkr, have you seen anything like this while writing the code?

I'll try to find out since when this is a problem

**Comment by SimonBrandner** [comment]
As far as I can tell, this was regressed in [v9.6.0-rc.1](https://github.com/matrix-org/matrix-js-sdk/releases/tag/v9.6.0-rc.1) of the js-sdk ([v1.7.19](https://riots.im/1.7.19) of Element Web)

**Comment by SimonBrandner** [comment]
I am a little suspicious of [#1579](https://github.com/matrix-org/matrix-js-sdk/pull/1579) - I'll do more digging later

**Comment by chagai95** [comment]
Thanks, we were both Chrome, do you need more info?

**Comment by SimonBrandner** [comment]
> Thanks, we were both Chrome, do you need more info?

No, since I have a repro case I don't think I need any more info

**Comment by SimonBrandner** [comment]
> I am a little suspicious of [#1579](https://github.com/matrix-org/matrix-js-sdk/pull/1579) - I'll do more digging later

Bingo! Reverting those changes fixes the issue, though I expect that to cause problems somewhere else...

**Comment by SimonBrandner** [comment]
It looks like [this line](https://github.com/matrix-org/matrix-js-sdk/blob/acb9bc8cc5234326a7583514a8e120a4ac42eedc/src/webrtc/call.ts#L1118) causes the stream to lose the tracks, which is _weird_

**Comment by dbkr** [comment]
I think we should actually just advertise `sendonly` while on hold, which would hopefully eliminate the need for these workarounds.
