### ISSUE TITLE
Toggling video off shows a black screen on the other side - bad UX

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17455]
![image](https://user-images.githubusercontent.com/31655082/119367619-6cc54400-bcb2-11eb-94e5-ada523081689.png)

### Description

Toggling video off shows a black screen on the other side - bad UX

### Steps to reproduce

- Make a video call
- toggle video off

I would expect some avatar or at least any picture but not a black screen which resembles a camera problem.

**Comment by SimonBrandner** [comment]
I'll close this in favour of [#16862](https://github.com/vector-im/element-web/issues/16862) as that issue is looking for a solution to this problem already
