### ISSUE TITLE
Grey notification pill instead of a red one in an encrypted room with highlights

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17452]
I've been highlighted directly in a work room while I wasn't working (i.e. I wasn't online when it happened). This morning, when I loaded up my work account (no new sign in, just opening a browser tab to element web on my already logged in matrix account), I saw a few notifications in this room, with a grey pill, which didn't surprise me since I've set this room to notify on every message. I've gone around catching up on other notifications, but when I looked at this one I noticed the couple of highlights waiting for me in that room.

My understanding is that Element should decrypt messages in encrypted rooms at startup and display a red pill if one of them is defined as a highlight in my push rules, however when I switched to this room it seemed to only decrypt messages then, which sounds like the source of the issue to me?

**Comment by gsouquet** [comment]
The recent work done should decrypt all available messages that are after the last read receipt. Therefore those messages should be decrypted. But there's a caveat to that, vector-im/element-web#17223 was raised quite recently and looks quite similar to the issue you just raised

**Comment by babolivier** [comment]
Ah yeah it does look similar - though I'm surprised a bug that hides your notifications from you is being labeled as minor.

**Comment by gsouquet** [comment]
I believe it is labeled as minor as it occurs only for gappy sync

As the two issues look similar I will close this one and let you continue the conversation there if you want to discuss the priority assigned further
