### ISSUE TITLE
Encryption broken on develop.element.io in browsers without WASM support

### ISSUE THREAD

**Issue by jrick** [vector-im/element-web#17463]
![2021-05-25-093012_656x562_scrot](https://user-images.githubusercontent.com/1420313/119507174-97f47580-bd3c-11eb-82d5-921dc147900d.png)

### Description

The Chromium package on OpenBSD disables wasm support by default (for several reasons I won't go into here).  It is possible to re-enable it, but I would prefer to leave it off.

The latest development version of Element Web no longer works with this setup.  The fallback to loading olm_legacy.js (https://develop.element.io/olm_legacy.js) is 404ing.

### Steps to reproduce

- Use OpenBSD chromium, or any other chromium browser with `--disable-features=WebAssembly,AsmJsToWebAssembly,WebAssemblyStreaming --js-flags=--noexpose-wasm`.
- Open Element Web (currently, Element version: `f78be2631ad6-react-1751b4ba43ea-js-acb9bc8cc523`)

Logs being sent: no

### Version information

- **Platform**: web
- **OS**: any (but only tested OpenBSD)
- **Version**: `f78be2631ad6-react-1751b4ba43ea-js-acb9bc8cc523`

**Comment by brandsimon** [comment]
Normal `app.element.io` does also not work when disabling wasm support on my side.
