### ISSUE TITLE
Message preview in room list isn't always up to date

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17469]
![image](https://user-images.githubusercontent.com/5547783/119631025-cabb6e00-be0f-11eb-9611-7cd2beaf14e2.png)

The latest message in the room starts with "⤵+ Reformatted files using black #344 for matrix-org/sydent", but the preview is using one starting with "📝 Can't upgrade from 1.31 #10052 for matrix-org/synapse", which is two messages older in the timeline.

**Comment by t3chguy** [comment]
I started seeing the same this morning, is it similarly new for you @babolivier?

**Comment by babolivier** [comment]
> I started seeing the same this morning, is it similarly new for you @babolivier?

I've only started noticing it this morning yes.
