### ISSUE TITLE
Reactions are failing to appear on a encrypted room with lots of reactions

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17461]
the individual timeline events are visible (with 'show hidden events' present), but the aggregations are not shown at all. have had this twice; once on today's nightly; one yesterday

**Comment by ara4n** [comment]
Switching back/forth to the room makes them reappear.

**Comment by ara4n** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1294269/119481770-fe809000-bd4a-11eb-9844-315b2e929a17.png">

the second & third messages had tonnes of reactions (which you can see in the timeline), but the aggregations are not shown on them.

**Comment by jryans** [comment]
At first glance, this seems like a rendering issue that only happens when show hidden events is used. If you disable show hidden (normal timeline mode) and re-enter the room, the reactions appear as expected.

**Comment by jryans** [comment]
Ah hmm, actually it may not be specific to hidden events. If the first reaction for an references we don't yet have an event object in memory for, we fail to notify the UI that reactions exist.

I believe this is likely a subtle side-effect of recent decryption changes, as we'll prioritise decrypting the reactions first and so might not have their target.
