### ISSUE TITLE
Element Desktop silently disregards an invalid config.json

### ISSUE THREAD

**Issue by TeknikalDomain** [vector-im/element-web#17476]
After failing to insert a trailing comma (twice now, actually!) I've realized that Element Desktop will fail *silently* if your user-supplied `config.json` is invalid, and disregard it. From the small discussion had in `#element-web:matrix.org`, this seems like a fairly trivial issue to fix.

**Comment by aaronraimist** [comment]
Context: https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$3q5tYvcpzB-55xIZCqCNmWjOnuvRQru33AP9xkaz5AI?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by TeknikalDomain** [comment]
I forgot that was an option or I'd have added it. Oops.
