### ISSUE TITLE
Stuck message at the bottom of the timeline

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17479]
![image](https://user-images.githubusercontent.com/5547783/119794481-da05ee80-bed7-11eb-8d8d-2ba3ab513e65.png)

The message was sent (and the bot I'm talking to responded to it), and I can see it in the right place in the timeline, but a duplicate of it is stuck at the bottom of it.

Switching rooms and back doesn't fix it.

**Comment by t3chguy** [comment]
This is a missing remote echo down sync or a missing transaction id in said remote echo
Duplicate of https://github.com/vector-im/element-web/issues/17471
