### ISSUE TITLE
Outgoing message is corrupted in local cache; perpetually displayed as newest message

### ISSUE THREAD

**Issue by sporksmith** [vector-im/element-web#17471]
### Description

This outgoing message is perpetually displayed as the newest message in this room for me, from my desktop Element client:

![image](https://user-images.githubusercontent.com/179146/119694821-3521dd80-be13-11eb-888a-3d871dbc7568.png)

"View source" gives:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "but on the other side it's not actually much entropy once you know this person thinks \"nerdy books\" are good encryption keys"
  },
  "event_id": "$vzIp4ZPdxzFzmpNIOsAXV7reeAhn0cTDLGahXamggec",
  "user_id": "@sporksmith:matrix.org",
  "sender": "@sporksmith:matrix.org",
  "room_id": "!HRkvwgoHhxxegkVaQY:matrix.org",
  "origin_server_ts": 1621294330488
}
```

This seems to be missing some fields? Maybe notably "age"? For comparison, after a bit I thought maybe the message hadn't gone out, and re-sent the same text. "View source" for that one gives:

```
{
  "content": {
    "body": "but on the other side it's not actually much entropy once you know this person thinks \"nerdy books\" are good encryption keys",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1621297232938,
  "room_id": "!HRkvwgoHhxxegkVaQY:matrix.org",
  "sender": "@sporksmith:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 747163236
  },
  "event_id": "$9Vz-zkzpdXbIBcO5quuhKgsjPMpRVV_3NweNVNlHX1A",
  "user_id": "@sporksmith:matrix.org",
  "age": 747163236
}
```

The original message appears normally from my other clients (e.g. Element on mobile), and according to others did go out the first time and looked normal, so I think it's somehow corrupted in this client's local cache.

### Steps to reproduce

Haven't been able to reproduce

- Send a message (in an IRC bridged room)
- ??
- Observe outgoing message perpetually displayed as newest in the room

Describe how what happens differs from what you expected:

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Ubuntu
- **Version**: 1.7.27

**Comment by t3chguy** [comment]
This is a bug when the server never remote-echoes the event back down /sync - you can Clear Cache & Reload from Settings > Help & About to resolve it

**Comment by sporksmith** [comment]
@t3chguy Yup, that fixed it for me. Thanks!

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17966 due to more technical context
