### ISSUE TITLE
Autocomplete covers most of the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17475]
It uses a two column layout, but much of the second column is empty.

**Comment by SimonBrandner** [comment]
I actually can't repro this :thinking: For me, it always splits the content evenly into the two columns

![Screenshot_20210626_114947](https://user-images.githubusercontent.com/25768714/123509255-9f2cdd00-d674-11eb-9af2-97fa5eee29fe.png)

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18682
