### ISSUE TITLE
How to reset cross-signing from ios?

### ISSUE THREAD

**Issue by ChzenChzen** [vector-im/element-web#17482]
I read some issues where verification process is broken. And the one of suggestions was to reset cross-signing, but I can't find in my client settings in iOS

**Comment by SimonBrandner** [comment]
@ChzenChzen, this looks like a question for [the Element iOS room](https://matrix.to/#/!pMBteVpcoJRdCJxDmn:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org) rather than the element-web repo...
