### ISSUE TITLE
element-desktop shows blank window

### ISSUE THREAD

**Issue by robin-nitrokey** [vector-im/element-web#17485]
### Description

After upgrading element-desktop from 1.7.24 to 1.7.29, the Element window is no longer opened on startup.  If I manually open the window using the Element tray icon, the Element window opens but is empty.

### Steps to reproduce

- Start Element.
- Open the context menu of the tray icon and select “Show / Hide”.

Expected: window opens at startup and shows Element UI

Actual: window only opens after clicking “Show / Hide” and is empty.

Output:

```
$ element-desktop
/home/robin/.config/Element exists: yes
/home/robin/.config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
element-desktop: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
element-desktop: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
element-desktop: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
```

I don’t know whether the libva and intel_memman errors also occurred with previous versions.

### Version information

- **Platform**: desktop
- **OS**: Debian 10
- **Version**: 1.7.29 (installed from the packages.riot.im repository)

**Comment by SimonBrandner** [comment]
Related [#15486](https://github.com/vector-im/element-web/issues/15486)

**Comment by robin-nitrokey** [comment]
Starting `element-desktop` with the `--disable-gpu` option, as discussed in the linked issue, fixes the problem for me.

**Comment by robin-nitrokey** [comment]
This problem no longer occurs for me after updating to version 1.8.1.

**Comment by SimonBrandner** [comment]
Awesome! I am going to close this then, ping me if you ever see this again

**Comment by atuctuc** [comment]
i have still the same problem on ubuntu impish.
with --disable-gpu
element core dumps

element-desktop --disable-gpu
/home/alex/.config/Element exists: no
/home/alex/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
[499925:0915/082432.917851:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
