### ISSUE TITLE
[UX] Pin "Quick actions" in left panel to bottom

### ISSUE THREAD

**Issue by libexus** [vector-im/element-web#17495]
When I'm in a Space with so many rooms that they don't fit into the window, I have to scroll all the way down to access the quick(!) actions buttons.

#### Describe the solution you'd like.
I think the best solution would be to pin the buttons to the button

| sth similar to this | instead of this | 
--- | ---
| ![Artboard-1-1](https://user-images.githubusercontent.com/67947338/120013724-66e89f00-bfe1-11eb-9f89-59282d2da918.png) | ![element_quick_actions](https://user-images.githubusercontent.com/67947338/120015518-b16b1b00-bfe3-11eb-887f-a9bd502cf790.gif) |

**Comment by yannicka** [comment]
The current solution is not ideal, but doesn't the proposed solution take up too much space?

**Comment by HarHarLinks** [comment]
"Explore rooms" button is (currently) pinned at the top, next to the search bar.
"Invite people" is there when you go to the "Explore rooms" menu.

Both are also "pinned" in the right-click menu of the space in the space panel.

**Comment by libexus** [comment]
> The current solution is not ideal, but doesn't the proposed solution take up too much space?

That's true, I didn't think of that.

A space saving alternative I just came up with:

![Artboard-3-small](https://user-images.githubusercontent.com/67947338/120827952-43cb6b80-c55c-11eb-96d7-153861725c39.png) ![Artboard-2-small](https://user-images.githubusercontent.com/67947338/120827920-3d3cf400-c55c-11eb-9e91-198260c2fdb3.png) <br><sup>*Please ignore the ugly black line at the bottom*</sup>

The benefit of this would be that you could add more options like *Space settings*, *Space notification settings*, *New room* etc. later on (Similar to what Discord has at the top of the left panel)

**Comment by t3chguy** [comment]
We got rid of Quick Actions
