### ISSUE TITLE
Key verification pass phrase process is broken 

### ISSUE THREAD

**Issue by WholeCheese** [vector-im/element-web#17497]
Your login “verification” process leaves a lot to be desired.  It refuses to accept the pass phrase that I created, twice, because I had to go through your key verification pass phrase process twice because it refused to log in with my first pass phrase. If you want the average person to use your service you still have a lot of work to do! As it is, this software engineer is about to give it up and stay with Signal.

**Comment by SimonBrandner** [comment]
Please fill in the issue template
