### ISSUE TITLE
Down arrow on editing a message doesn't return to the composer

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17491]
To repro:
 * Type something in the composer
 * Press up: cursor moves to start of message
 * Press up again: Start editing message
 * Press down: Message edit UI flickers but then keeps editing the message

I guess this should probably cancel the editing and go back to the composer?

As I write this, I see @t3chguy has reproed it anyway :)

**Comment by t3chguy** [comment]
Oh yeah, it returns the composer but then instantly back to the edit for me, causing a large flicker

**Comment by SimonBrandner** [comment]
Regressed by [#6001](https://github.com/matrix-org/matrix-react-sdk/pull/6001)
