### ISSUE TITLE
Add a visual indicator when someone is speaking

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#17506]
#### Is your suggestion related to a problem? Please describe.
1. As a speaker, it's nice for me to know exactly what audio is being sent to the other side. Right now I have no way of knowing if they can hear my whispers, typing, or background sound.

2. When diagnosing audio issues, we have no way of visually knowing if the issue is on the senders or receivers side. There isn't an indication other than sound itself that one is speaking.

3. When lots of people are speaking, it can be hard to keep track of who is speaking. 

#### Describe the solution you'd like.
Could a visual indicator be added to the person who is speaking, and to myself, when audio is being sent/received.

For example, when I speak, I expect to see a visual indicator (ie a ring around my avatar) if Element is sending it.
If my friend is speaking, I expect to see a visual indicator (ie a ring around their avatar) if Element is receiving it.

* This will make it so we know exactly when audio is being sent or not.
* It's easy to know if audio issues on from the sending or receiving end. (ie if I see the visual indicator on my friend, but I don't hear him, I can assume the issue is on my side.)

#### Describe alternatives you've considered.
Possible visual indicators:
* Ring around the user's avatar
* If you wanted to be fancy, the thickness of the circle could vary depending on the decibels
* A speaker icon or around the user's avatar

**Comment by robintown** [comment]
To be clear, are you referring to 1-to-1 calls (and not group calls, which are run with Jitsi)?

**Comment by SethFalco** [comment]
I'm referring to 1-to-1 calls.

I'm assuming that confusion came from number 3, which was hypothetical rather than from experience. Sorry if that's not how it works in group settings.

**Comment by robintown** [comment]
Got it. But yeah, number 3 could still be relevant in the future especially if Jitsi is swapped out for a more native Matrix solution

**Comment by SimonBrandner** [comment]
I'll close this in favour of [#16084](https://github.com/vector-im/element-web/issues/16084)
