### ISSUE TITLE
Low-priority section doesn't expand anymore on clicking

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#17505]
### Description

Low-priority section doesn't expand anymore on clicking. It can be opened when going from the last room in "Rooms" via alt-down. It can be closes again but doesn't reopen.

Neither an element or system restart, nor clear cache fixed this.

### Steps to reproduce

- Have some room in low-prio
- close low-prio section
- Try to open it again.

There's nothing in the browser console logs.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: 1.7.29-1 (https://github.com/archlinux/svntogit-community/blob/packages/element.io/trunk/PKGBUILD)

**Comment by Bubu** [comment]
Rageshake sent referencing this issue.

**Comment by SimonBrandner** [comment]
I can't repro this

**Comment by Bubu** [comment]
Mh, it just started working again (while being connected to an external screen? Not sure if related.) I'll see later today if this is still broken when working on the notebook screen.

**Comment by Bubu** [comment]
So, disconnecting the external monitor, it still worked. Restarting element-desktop -> doesn't work anymore.
Reconnecting external screen -> works again.

**Comment by Bubu** [comment]
One additional puzzle piece: This only happens when running with size+1 (ctrl + used once). Problem goes away when returning to normal size (but then everything is too small for my taste)

**Comment by SimonBrandner** [comment]
Yep, I can repro now

**Comment by gsouquet** [comment]
Is that something that both of you are still experiencing? 
The rageshake did not unveil anything useful unfortunately. I have tried multiple browsers trying to follow the given steps without luck so far

**Comment by Bubu** [comment]
This is still happening for me today. My current workaround now is, go to default size, expand section. Go back to size +1

**Comment by Bubu** [comment]
This seems to have regresses in a worse fashion:

Trying to expand the low-prio section now puts a quarter screen whitespace at the bottom of element-desktop:

![image](https://user-images.githubusercontent.com/105185/131651226-d04100e2-d419-4def-81a0-6dd6500471f3.png)

**Comment by gsouquet** [comment]
What version are you currently using? The original issue mentions `1.7.29-1` which is quite outdated now

**Comment by Bubu** [comment]
Currently on 

Element version: 1.7.34
olm version: 3.2.3

**Comment by SimonBrandner** [comment]
Still quite old... The latest is 1.8.1, I think

**Comment by Bubu** [comment]
I updated to 1.8.2 (by manually building an updated archlinux package) and this is now back to the originally reported problem where the low-prio section doesn't expand when using my internal monitor (which has hidpi scaling 2x)

**Comment by germain-gg** [comment]
This seems to have been fixed now.
