### ISSUE TITLE
It's possible to hang up a call before placing it

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17528]
I just got a call from Tom where the hangup event arrived before the invite. His client shows the same order. We should ideally cancel the call if the user presses hangup before we've sent the invite, or failing that at least wait until we've sent the invite to send the hangup.

This might be the same edge case where I managed to place several calls at once by spamming the call button, which I could only repro once (only when browser doesn't have candidates cached maybe?)

**Comment by SimonBrandner** [comment]
@dbkr, did you manage to repro? Have you ever seen this again?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
