### ISSUE TITLE
Emoji picker symbol is not being shown

### ISSUE THREAD

**Issue by Pecadis** [vector-im/element-web#17522]
Hi,

i noticed that the Picker symbol is not being displayed in the browser anymore.
![01](https://user-images.githubusercontent.com/5543829/120304371-05218100-c2d0-11eb-8540-78ba16772b88.png)
The Picker is not visible but clearly the space for it is there

![02](https://user-images.githubusercontent.com/5543829/120304404-0baff880-c2d0-11eb-9c78-d43b624adc73.png)
The Emoji Picker is there and also working when clicking on it

![03](https://user-images.githubusercontent.com/5543829/120304414-0ce12580-c2d0-11eb-8d44-76080280f754.png)
It is certainly not because of Dark-mode.

### Version information

- I have tried the Brave Browser V1.25.68 (May 27, 2021) and Mozilla Firefox 88.0.1 (64-bit).
- Running on Windows 10 
- Element Web is running on version: 1.7.29
- olm version: 3.2.3
- I have also checked the config and compared it with the sample config.

Does anyone face a similar issue? At least i couldn't find it in the issues.

**Comment by t3chguy** [comment]
What instance of Element are you using?

It works fine here

![image](https://user-images.githubusercontent.com/2403652/120305617-e23f9e80-c2c8-11eb-8cfd-86a012bff86b.png)

**Comment by Pecadis** [comment]
It's self hosted. 
which element version are you using?

**Comment by t3chguy** [comment]
I'm using Element Nightly but can also see the same working icon on https://app.element.io

![image](https://user-images.githubusercontent.com/2403652/120307637-1f0c9500-c2cb-11eb-92c6-8e48e2a9045e.png)

**Comment by Pecadis** [comment]
ok, i just deleted the whole /var/www folder and downloaded everything from the latest stable release. now it works -.-
