### ISSUE TITLE
invite does not work when pasting a string instead of typing

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#17523]
### Description

The input field in the invite dialog reacts strange when you paste a string instead of typing.

### Steps to reproduce

- click "Start Chat"
- paste a string from your clipboard into the search field that is not a MXID of an existing user

![Screenshot from 2021-06-01 13-28-27](https://user-images.githubusercontent.com/16013327/120316050-48ceb780-c2dd-11eb-8668-4ca679dec3ba.png)

Type instead of pasting and you can invite the user.

![Screenshot from 2021-06-01 13-27-05](https://user-images.githubusercontent.com/16013327/120316587-e0cca100-c2dd-11eb-901c-cfcedeef7307.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian 11
- **Version**: 1.7.29

**Comment by GaijinSystems** [comment]
This still appears to be an issue with the element desktop version 1.11.22 (running on Debian 11).
I encountered this bug when attempting to paste my matrix.org test account as a DM recipient from my self-hosted server.

Interestingly, when doing the same thing from app.element.io (logged into my matrix.org account), pasting my self-hosted address works just fine.

I understand that this is a minor bug, but it seems that copy/pasting an address would be much more common than typing it out manually.
