### ISSUE TITLE
Can't p2p 1:1 call if turnserver is disabled

### ISSUE THREAD

**Issue by Latrolage** [vector-im/element-web#17535]
Not sure if this is intended or not, but with the 
```
Allow Peer-to-Peer for 1:1 calls (if you enable this, the other party might be able to see your IP address)
```
option enabled, it still requires the server's turnserver to be enabled. I thought that if both parties have this enabled, it would be a p2p e2ee call?

Element version: 1.7.29
olm version: 3.2.3

**Comment by t3chguy** [comment]
Do you have a functioning STUN server, e.g one from your HS or 
![image](https://user-images.githubusercontent.com/2403652/120493548-f5c73400-c3b2-11eb-890b-14cde735c439.png)

Without STUN your client has no way of knowing its external IP address to be able to negotiate a p2p connection.

**Comment by Latrolage** [comment]
Not quite sure if i'm understanding how turn and stun work. I installed and setup coturn on a ubuntu based server. How does stun installation/configuration work?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/blob/develop/docs/turn-howto.md
