### ISSUE TITLE
markdown lists are rendered without the bulletpoints

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17546]
### Description

markdown lists are missing the bulletpoints, same for numbered

![image](https://user-images.githubusercontent.com/2803622/120670715-fdf5a100-c490-11eb-85a7-d22269e8c635.png)

### Steps to reproduce

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "1. test\n2. this ",
    "format": "org.matrix.custom.html",
    "formatted_body": "<ol>\n<li>test</li>\n<li>this</li>\n</ol>\n"
  }
}
```

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021060301-1

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/ebd7cd6212905862912784add85fa936709a8b65#diff-42a8acefe9aa87c2f5bc3a4c03e299b054e7d8d0b9ac4bee58911eb188ff374bR225

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6138

**Comment by HarHarLinks** [comment]
Is the message hover menu thing (react, reply, ...) caused and fixed by the same?
