### ISSUE TITLE
Messages sometimes get sent twice 

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17541]
### Description
Messages sometimes get sent twice

### Steps to reproduce

I have seen this very rarely, but it still happens occasionally.

Logs being sent: yes

### Version information

- **Platform**: web (in-browser-pwa)
- **Browser**: Chrome - the newest version: Version 91.0.4472.77 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: https://element.chagai.website, v1.7.25

**Comment by t3chguy** [comment]
Does the message actually sent twice or does it appear doubled for the sender?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Comment by chagai95** [comment]
Sorry, I was not sure what to answer and then forgot...I think it's the same bug but it might be a different one anyway if it's the same bug I see on a regular basis (every few weeks) then it gets sent twice as well

**Comment by SimonBrandner** [comment]
@chagai95, so you sometimes see that your messages get sent twice? Do other people see the same thing or is it just you who sees this?

**Comment by chagai95** [comment]
I'm pretty sure it's everyone, the next time it happens I'll send logs from the server and take some screenshots

**Comment by SimonBrandner** [comment]
@chagai95, have you seen this again?

**Comment by chagai95** [comment]
Yes but it might be a bridge bug not yet 100% sure maybe 90%

**Comment by SimonBrandner** [comment]
Ah, alright, let's wait a bit then

**Comment by SimonBrandner** [comment]
I am going to close since we don't seem to have a repro case. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
