### ISSUE TITLE
Message action button bar gets cut off (sometimes to the point of being inaccessible)

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#17548]
![Screenshot_20210603_134354](https://user-images.githubusercontent.com/1012976/120689470-2326e700-c472-11eb-8a1d-8321772d7855.png)

### Version information

- **Platform**: web (in-browser) or desktop? Desktop (nightly 2021-06-03)

**Comment by uhoreg** [comment]
This is particularly visible when you mouse-over the second message that someone sends.

**Comment by t3chguy** [comment]
Should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6138

**Comment by SimonBrandner** [comment]
Closing as this should be fixed now. Feel free to shout if this is still a problem
