### ISSUE TITLE
Add ability to remove rooms from spaces from context menu in room list

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#17544]
A suggestion from @JordanHancock-NV after reaching for it as a natural place to want to remove a room from a Space. Relatedly, 'Explore rooms' didn't feel like a good place to reach to manage which rooms are in Spaces. 

cc @niquewoodhouse @t3chguy

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17279
