### ISSUE TITLE
Duplicated rooms

### ISSUE THREAD

**Issue by theCalcaholic** [vector-im/element-web#17554]
### Description

Occasionally, rooms are duplicated in the Element Desktop (and presumably Web) room list.

### Steps to reproduce

not sure yet. It happened a few times. Maybe we can find a pattern, if others have the same issue.

Logs being sent: yes/no

![image](https://user-images.githubusercontent.com/6317548/120802231-7e280f00-c542-11eb-95ab-fe35b89eeadc.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 20.04
- **Version**: 1.7.29

**Comment by SimonBrandner** [comment]
Duplicate of [#14508](https://github.com/vector-im/element-web/issues/14508)

**Comment by theCalcaholic** [comment]
Ah, thank you. Didn't find that :)

**Comment by SimonBrandner** [comment]
No problem :)
