### ISSUE TITLE
No timestamps in replies

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-web#17555]
Timestamps have disappeared from the quoted text in replies. This makes it impossible to jump to the original post (from Matrix HQ room, the timestamp should be under the avatar in the reply):
![2021-06-04_15-33-20](https://user-images.githubusercontent.com/184066/120804206-11664200-c54d-11eb-9ef2-55fd94b4afb6.png)

Reproducible on the current develop. The regression happened in this commit (found through bisect): https://github.com/matrix-org/matrix-react-sdk/commit/171539d42d560bf37abbfdfba86bb0f22986f84e

**Comment by SimonBrandner** [comment]
Closing in favour of [#17560](https://github.com/vector-im/element-web/issues/17560)
