### ISSUE TITLE
Don't reorder room list when prompting user for forwarding room

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#17556]
#### Is your suggestion related to a problem? Please describe.
When going to forward a message, if your room list is ordered by activity, it's very possible to accidentally click the wrong room when the rooms reorder right when you go to click.

#### Describe the solution you'd like.
Don't reorder the room list when the user is being prompted to choose a room to forward to. Instead wait until either they choose a room or cancel the forward.

#### Describe alternatives you've considered.
This doesn't happen with A-Z ordering on the room list but that's not acceptable for those with large room lists.

**Comment by t3chguy** [comment]
The forwarding UX is changing entirely, this isn't relevant for the new style: https://github.com/matrix-org/matrix-react-sdk/pull/5999
