### ISSUE TITLE
DM with generic Icon and Room with the Icon of the user in it

### ISSUE THREAD

**Issue by lascapi** [vector-im/element-web#17559]
### Description

There is a diffence between Element Android and Desktop in the icon for DMs and Rooms.

What I think is good ( like in Element Android ) :
For DMs ( johan is a person ) I can see his/her profil’s picture.

![Screenshot_20210604-203328](https://user-images.githubusercontent.com/6562527/120848865-a1b87d00-c575-11eb-8c40-0e2cefdde0d4.png)

For a room ( Maria is the room’s name) without picture as icon I can to see the first letter

![Screenshot_20210604-202848_1](https://user-images.githubusercontent.com/6562527/120848974-c4e32c80-c575-11eb-9f96-ac55c06193da.png)

### Problem

In element Web/Desktop the behaviour is the opposite. As you can see johan got the first letter and the Maria room got the profil’s picture of johan ( wich is and the only one in the room )

![Element_AztdBsfrES](https://user-images.githubusercontent.com/6562527/120849061-e04e3780-c575-11eb-93e5-91ee8a1b5764.png)

I got it at least for DM rooms version 1

### Version information

- **Platform**:  desktop and web

For the web app: 

- **Browser**:  Firefox 91
- **OS**: Windows 10 
- **URL**: https://app.element.io/ 

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.7.29 
and 
- MacosX
- version ?

**Comment by SimonBrandner** [comment]
Related: [#9929](https://github.com/vector-im/element-web/issues/9929)

**Comment by kittykat** [comment]
Web now shows the avatar for both:
![Screenshot from 2021-09-15 11-04-44](https://user-images.githubusercontent.com/51663/133414191-1098d3cb-f6e7-41c1-ac74-2395133a1dde.png)

**Comment by kittykat** [comment]
@lascapi I think the issue you are seeing is partially related to cache updating. The functional part is summarised in #18747 . If you are happy that 18747 covers your issue, I would like to close this as a duplicate.

**Comment by kittykat** [comment]
I am closing this issue in favour of #18747 for now, Please comment with @kittykat if anyone feels that this should be reopenned
