### ISSUE TITLE
read receipt always flies in from the very top

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17557]
### Description

read marker always flies in from the very top, even if previously it was on the next-to last message

probably related to #17552 in cause and effect

### Steps to reproduce

- have your opposite read the last msg
- send new message
- watch read marker disappear and fly in from the beyond as they read the new message

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021060401-1

**Comment by SimonBrandner** [comment]
I can repro this

**Comment by HarHarLinks** [comment]
just updated, this is still in 2021060402-1

**Comment by robintown** [comment]
@HarHarLinks Are you referring to read receipts (the little circles next to messages) or read markers (the green bar above the first unread message)?

**Comment by HarHarLinks** [comment]
@robintown indeed I mean the little circles with other user's avatars that mark who read up to which point

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17561
