### ISSUE TITLE
Sent marker on the wrong side of the timeline

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17552]
### Description

![image](https://user-images.githubusercontent.com/2803622/120782438-490fc280-c52a-11eb-920a-7997b787004a.png)

### Version information

nightly

**Comment by SimonBrandner** [comment]
This doesn't seem to be a problem on develop. @gsouquet, was this fixed by [#6138](https://github.com/matrix-org/matrix-react-sdk/pull/6138)?

**Comment by jryans** [comment]
> This doesn't seem to be a problem on develop.

Develop was not updating regularly this week from Tuesday (Jun 1) until just recently. Now that it has, I see the issue on develop too, so I'd say it's still an active issue.

**Comment by HarHarLinks** [comment]
let me add that I liked it better on the same side where the read markers are, with any read markers implying that it was sent successfully. only downside is editing, but i'd just put the sent marker on a "new line" within the same message.

**Comment by SimonBrandner** [comment]
@HarHarLinks, this is a bug - it's not intentional

**Comment by jryans** [comment]
It's a regression from one part of https://github.com/matrix-org/matrix-react-sdk/pull/6079 (https://github.com/matrix-org/matrix-react-sdk/pull/6079/commits/f058fd8869dca84b05d70fc1390da262d2e38439). The `msgOption` container needs to be added to the sent status as well.
