### ISSUE TITLE
Inter font paths are absolute

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-web#17575]
Currently, paths to the Inter fonts are relative to the website root. It's not a problem if Element is hosted on its own domain (like https://develop.element.io where these fonts are loaded just fine). But if it's hosted under a custom path like https://example.com/element/ these fonts can't be loaded. All other resources have valid paths, only these fonts are broken. It can be easily fixed with this patch:
```diff
diff --git a/src/vector/index.html b/src/vector/index.html
index 061d249e..7921d37f 100644
--- a/src/vector/index.html
+++ b/src/vector/index.html
@@ -54,7 +54,7 @@
         var tag = htmlWebpackPlugin.tags.headTags[i];
         var path = tag.attributes && tag.attributes.href;
         if (path.indexOf("Inter") !== -1) { %>
-            <link rel="preload" as="font" href="<%= path %>" crossorigin="anonymous"/>
+            <link rel="preload" as="font" href=".<%= path %>" crossorigin="anonymous"/>
         <% }
     } %>
 
```
So that insteal of `<link rel="preload" as="font" href="/fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2" crossorigin="anonymous"/>` it would be `<link rel="preload" as="font" href="./fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2" crossorigin="anonymous"/>`. I'm not completely sure if this solution is good enough but it works for me. Maybe it's better to fix these paths somewhere else.

**Comment by gsouquet** [comment]
As discussed in https://github.com/vector-im/element-web/pull/20040 

> I'm not convinced that this the approach I'd want us to take to fix this particular problem. Dabbling with the [`HtmlWebpackConfig`](https://github.com/jantimon/html-webpack-plugin) sounds a bit more maintanable and will convey the intent a bit better.
It appears that the `path` or `publicPath` option seems to achieve what you're after.
I'd also be curious to understand why this is an issue for this scenario and not for the JavaScript bundles

**Comment by t3chguy** [comment]
This got fixed
