### ISSUE TITLE
Hoverover glitch on selected messages in new timeline code

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17576]
Margins need tweaking on hoverover to compensate for the indenting of the highlight.

https://user-images.githubusercontent.com/1294269/121002005-c6823f80-c783-11eb-90df-d95425178410.mov

**Comment by jryans** [comment]
Hmm, does this still reproduce on develop today? I can't seem to cause it to happen here...

**Comment by SimonBrandner** [comment]
Weird, I can repro on develop.element.io but on Nightly
