### ISSUE TITLE
MELS performance is terrible with lots of membership changes (eg after a netsplit)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17573]
This was reported by the project lead for Fedora (and should be prioritised accordingly as we particularly want big projects like Fedora to be happy)
 https://discussion.fedoraproject.org/t/matrix-irc-bridge-causes-annoying-join-part-spam/29956

"Joining #fedora-devel:matrix.org room causes Firefox hang for 1 minute."

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11963
