### ISSUE TITLE
v1.7.30 breaks timeline scrolling with PageUp and PageDown keys

### ISSUE THREAD

**Issue by dongsibo** [vector-im/element-web#17588]
### Description

As of the v1.7.30 release, scrolling up/down in the timeline with `PageUp` and `PageDown` does not work if the composer is in focus. Scrolling with these keyboard keys will only happen if the timeline is focused (by clicking on it).

### Steps to reproduce

- Update to v1.7.30 when prompted by the web client.
- Navigate to any room.
- Press `PageUp` or `PageDown`.

In previous versions of Element, pressing `PageUp` or `PageDown` while the composer was in focus would scroll the timeline. These keys now have no effect unless the timeline is focused.

Logs being sent: no

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 89.0
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by pdurbin** [comment]
I'm just chiming in to say that the desktop version seems to be affected as well. I'm on Mac.

Thanks for Element. I'm coming over from IRC (weechat) and still getting oriented but overall so far so good!

**Comment by pdurbin** [comment]
I just upgraded to Element 1.7.31 and it's fixed! Thanks! 🎉
