### ISSUE TITLE
Custom theme disables every time I refresh

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#17581]
### Description

Every time I refresh Element (either for an Element update, ctrl+r, or reopen the browser/tab, my custom theme is turned off and the built in light theme is used. In Appearance settings, my custom theme shows as selected. To reapply my theme, I need to select the built in light or dark theme, then my custom theme again.

### Steps to reproduce

- Refresh Element. Not sure how to trigger this bug in the first place

Log: sent    

![Screen Shot 2021-06-07 at 01 28 34 PM](https://user-images.githubusercontent.com/19155609/121016754-6e076e00-c794-11eb-9458-798254bffdf9.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 89.0 (64-bit)
- **OS**: Arch Linux
- **URL**: develop.element.io
Element version: 3254de839413-react-b60feab7d265-js-af16bba1ec96
olm version: 3.2.3

**Comment by robintown** [comment]
@Twi1ightSparkle Another bug that is possibly related was fixed on develop recently, could you check if this still occurs?

**Comment by Twi1ightSparkle** [comment]
Yep, problem appear to be resolved after an Element update today. Thanks
