### ISSUE TITLE
PNG thumbnail creation not working, invalid file header

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#17583]
Related rageshakes

matrix-org/element-web-rageshakes#5506
matrix-org/element-web-rageshakes#5501 

Failing images
* matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/rbIoATJvkNCxPioDiUXbzXxa

![121002261-119c5280-c784-11eb-9aa2-16be834c6603](https://user-images.githubusercontent.com/769871/121029462-82e9fe80-c7a0-11eb-96dd-6dcd331387ab.jpg)

**Comment by t3chguy** [comment]
Looks like people were trying to send a JPG file with `.png` extension and the browser was getting confused and telling us the `image/png` mimetype. Fundamentally same issue as https://github.com/vector-im/element-web/issues/11424 and not one we can really fix.
