### ISSUE TITLE
NotifPanel layout regressions

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17580]
<img width="432" alt="Screenshot 2021-06-07 at 12 03 55" src="https://user-images.githubusercontent.com/1294269/121006146-7a85c980-c788-11eb-8f21-0b5d765e1ac7.png">

**Comment by ara4n** [comment]
n.b. lack of whitespace between Thib & timestamp (and presumably timestamp being in the wrong place entirely)

**Comment by jryans** [comment]
This appears to affect the RC on staging as well, so ideally we'll find a fix today and send it to the release branch as well.

**Comment by jryans** [comment]
Hmm, seems to be related to some part of https://github.com/matrix-org/matrix-react-sdk/commit/d3623217068ca9d2bc8cb170ac1f9f8329b9de3a.

**Comment by jryans** [comment]
> Hmm, seems to be related to some part of [matrix-org/matrix-react-sdk@d362321](https://github.com/matrix-org/matrix-react-sdk/commit/d3623217068ca9d2bc8cb170ac1f9f8329b9de3a) / [matrix-org/matrix-react-sdk#6079](https://github.com/matrix-org/matrix-react-sdk/pull/6079).

Actually, these are only on develop so far, so not entirely sure which was the regressing change at the moment. Anyway, I'll send the fix also to release.
