### ISSUE TITLE
Can not call - Event blocked by other events not yet sent error

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17594]
### Description
Got this error probably after no internet connection.

![image](https://user-images.githubusercontent.com/31655082/121191340-2ce28d00-c86c-11eb-890f-2d031491a36b.png)

### Steps to reproduce

- not sure

Logs being sent: yes
[rageshake.zip](https://github.com/vector-im/element-web/files/6616744/rageshake.zip)

### Version information

- **Platform**: web (in-browser-pwa)
- **Browser**: Chrome
- **OS**: Windows
- **URL**: https://anconnect.aarenet.com, develop build

**Comment by benparsons** [comment]
Customer is reporting that this has occurred more frequently recently and that nothing seems to resolve it (refreshing browser doesn't help)

**Comment by dbkr** [comment]
This is because there are unsent events of some kind in the virtual room which are blocking the invite being sent there, but because you can't see the virtual room, you can't see the unsent events.
