### ISSUE TITLE
Ability to navigate away from rooms

### ISSUE THREAD

**Issue by jonkloske** [vector-im/element-web#17591]
I would like the ability to navigate away from all rooms inside the client.

My workaround used to be to click the communities button, as this would just be a blank non-room page. Now with spaces, there is no way to do this - there's a default "All rooms" space, and any other spaces you've created.

Ideally I'd just like some home page that I can quickly click to where I can still see the user and room list, but not actually be viewing a user or a room in the main panel. Bit like the "home page" on a space. But without an actual space being required.

**Comment by SimonBrandner** [comment]
You can press `Ctrl+Alt+H` to get to a home view. Is that enough for you?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Comment by aaronraimist** [comment]
@SimonBrandner I'm pretty sure there is already an issue for this somewhere that I can't find so you don't have to reopen, but this is a feature I want. I want a button I can quickly click as I walk away from my computer that takes me to `/#/home`. Currently I just click on a empty room I have for that purpose which is a bit annoying to have to keep around.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/123008185-547c3e00-d3b2-11eb-9398-c6bc1e151ec9.png)


There is a keyboard shortcut for it, alternatively you can specify a homeUrl in config.json and then a Home button will be added to the top left menu

**Comment by aaronraimist** [comment]
Yeah, that was Simon's comment above. But I'd prefer a button rather than a keyboard shortcut, and I'd prefer the button to be not inside another menu.

**Comment by jonkloske** [comment]
Well this is awkward. I accidentally filtered replies on this topic, so I never saw any of this. Control-Alt-Home is... awkward, but it works for me. Thanks. I admittedly only spent a few minutes looking into the config.json option but I couldn't find any suitable guides for how to do this. I'm sure if I really poked into it I'd figure it out, but my "5 minutes on google" approach to this problem tends to suggest that's probably not a good general solution for non-technical users.

Apologies again for the delay in replying.
