### ISSUE TITLE
Catalan translations are wrongly ordered in some translations

### ISSUE THREAD

**Issue by tsdgeos** [vector-im/element-web#17597]
For example, in one channel in English it says
"michaelweghorn joined and left 6 times, tsdgeos_ joined and left 2 times"

the catalan text says
" ha entrat i ha sortit 6 vegadesmichaelweghorn, ha entrat i ha sortit 2 vegadestsdgeos_"

I would have translated it as "michaelweghorn ha entrat i ha sortit 6 vegades, tsdgeos_ ha entrat i ha sortit 2 vegades"

### Version information

- **Platform**: web (in-browser) or desktop?
web 

For the web app:

- **Browser**: Firefox 89
- **OS**: Arch Linux
- **URL**: https://webchat.kde.org the config says 
Element version: v1.7.30
olm version: 3.2.3

**Comment by aaronraimist** [comment]
The translations are provided by the community. You can contribute here: https://translate.element.io/

**Comment by tsdgeos** [comment]
No thanks, I'm more than busy everywhere else and i don't find weblate usable at all.

**Comment by tsdgeos** [comment]
FWIW i tried to find out who was the Catalan translator[s] to tag them here but i found no info at all in weblate

**Comment by adriaaah** [comment]
Hello,

https://translate.element.io/translate/element-web/matrix-react-sdk/ca/?checksum=c43e9683c55bc0cc should fix it.
Thanks for reporting it.

`#matrix-cat:matrix.org` (alternatively https://matrix.to/#/#matrix-cat:matrix.org?via=matrix.org&via=musaik.net&via=espailliure.cat) is the room where I raised it, just in case you want to drop by in the future to discuss anything.
