### ISSUE TITLE
Set up docker hub autobuilds elsewhere

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17607]
Docker Hub is removing our ability to build this easily, so we need to find our own builder: https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

Would be good to fix https://github.com/vector-im/element-web/issues/9851 at the same time if we end up with a pipeline

**Comment by turt2live** [comment]
this is important to fix https://github.com/vector-im/element-web/issues/18848

**Comment by ibotty** [comment]
If the approach to use only a Dockerfile is kept, quay.io is an option which will publish automatically to quay.io.  The release script could then easily push the built image to dockerhub.  That works with static executables like `skopeo` that do not demand much setup.

**Comment by ibotty** [comment]
I can also create a pull request with the github actions config if you want to go that route.
