### ISSUE TITLE
Make clicking on the version number in `Settings -> About` copy that version number

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17603]
It's a bit finnicky when I need to select the exact spot when generating a bug report, maybe it'll be a bit of QoL to change it so that when clicking on it, it'll copy it straight into your clipboard.

(Maybe bonus, if the release was based off of staging/develop, maybe also add the commit the version was based on onto the end)

**Comment by SimonBrandner** [comment]
I think a much saner thing, from which everyone would benefit, would be a copy button next to the version in settings.
