### ISSUE TITLE
Voice messages are cut off in the right panel

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17608]
![Screenshot_20210609_185412](https://user-images.githubusercontent.com/25768714/121396881-1a438300-c954-11eb-9288-43ac66e6af92.png)

Also, should we allow pinning them and should they be even shown in the file panel?

**Comment by turt2live** [comment]
I think pinning is okay for now, being a labs feature. It's just another way of sending a message, so can logically be pinned (just as you would a video or image). Maybe for out-of-labs on pinning we can review it.

**Comment by HarHarLinks** [comment]
- pinning: intuitively, I don't see a reason why not
- file panel: if voice messages are treated differently from audio files, it would make sense to separate them. their semantics differ: voice are supposed to be more or less equal to regular messages, the other is an attachment
- i'm not a frequent voice message user. however, in a room that sees frequent voice messages, i imagine it could be beneficial to add some UI to enable exploring of them. text has search, attachments have the file drawer, perhaps voice should have their own drawer. this is also an argument in favour of pinning

**Comment by turt2live** [comment]
consensus from design (internally) is to exclude them from the files panel - have opened a new issue for this: https://github.com/vector-im/element-web/issues/17619

**Comment by turt2live** [comment]
hmm... but we still need a design for what this looks like in the other panels...

**Comment by turt2live** [comment]
ftr we reversed the decision to exclude from the files panel for now. Rough design is a 185px waveform-less component in the right panels.
