### ISSUE TITLE
new forwarding UI papercuts

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17616]
### Description

New forwarding has landed in nightly, yay!

![image](https://user-images.githubusercontent.com/2803622/121543942-99df5980-ca09-11eb-96cf-ce6a96ee5b3f.png)

![image](https://user-images.githubusercontent.com/2803622/121544847-4d484e00-ca0a-11eb-8644-7c04b455c42a.png)

- ~~[defect] weird square at bottom right~~
- [defect] scrollbar touches send buttons which is bad when you want to drag it to scroll lots
- [suggestion] hovering the cursor over the room name says "open link" - imo link is too general and should rather say "go to conversation"
- [thoughts] it uses your global display name for preview, which makes sense if you think about it.
  - your name: at first i thought that was unintentional/bugged, but it is a preview of what your forwarded msg will look like, so makes sense. ideally this will work using a linked list kind of thing similar to replies at some point (which i believed is planned - reasonable protection of secret/leaks, yaddayadda)
  - global display name: element can't know into which context i'm going to forward, so the only choice is global, or the origin room's id. which one relieves the disconnect more?
  - again, both are reasonable choices already. is there an unexplored option that feels more intuitive without first reasoning about it? maybe with future features?

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021061001-1

**Comment by HarHarLinks** [comment]
@SimonBrandner note that this includes 2 defects?

**Comment by SimonBrandner** [comment]
@robintown, you might be interested in this

**Comment by robintown** [comment]
> [defect] weird square at bottom right

For the record this has been fixed in matrix-org/matrix-react-sdk#6276.

**Comment by HarHarLinks** [comment]
- [suggestion] don't send when hitting the send button, but when closing the dialogue/window/panel. add ability to "undo" forwarding. like (i believe) gmail's undo sending for example. the timeline could represent this by leaving the message in unsent state or even more greyed out and either remove it when undone or send it upon close.

reasoning: it's easy to forward messages and potentially leak rooms, between spaces etc. yes you can redact things, but not sending erratically should be better.

**Comment by robintown** [comment]
> [defect] scrollbar touches send buttons which is bad when you want to drag it to scroll lots

Apparently this is browser-specific - on Firefox it's given appropriate space off to the side, whereas in Chrome it's displayed on top of the div. I'm not sure how to get Chrome to push it over without introducing unnecessary padding for other browsers.

**Comment by HarHarLinks** [comment]
I don't like preferring one over the other either, but
- note that electron (which is what I'm on) is also chrome and probably your biggest platform(?) certainly the intended platform since it is the only to offer e.g. encrypted search
- weakest link in the chain etc etc

**Comment by pacien** [comment]
There are some inconsistencies with the new experimental global search box
(opened with CTRL-K) and the search box to find rooms or people to forward to.
The same query can yield different results and ordering in the two search
boxes, which is quite disturbing and has led me to forward things to the wrong
places more than once.

**Comment by HarHarLinks** [comment]
@pacien: please track the issue raised in you comment at #21338
