### ISSUE TITLE
Bold+italics get converted to just italics on edit

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17610]
### Description

When using bold + italic syntax together, it will get converted to just italics on edit.

### Steps to reproduce

`***words***` -> edit -> `_words_`

`_**words**_` -> edit -> `_words_`

### What did you expect?

The original formatting would remain intact with bold and italic text.

**Comment by MadLittleMods** [comment]
I've removed `when not touched` because it does not seem to matter whether you add more to the message or not. The syntax in the edit draft is converted as soon as you press edit on the message.
