### ISSUE TITLE
Forward message does not work

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-web#17628]
The new UI does not work for me on develop on Friday 18:14 CEST.
The message never arrives to the destination room. I sent a rageshake with the forward of an image but it also fails to send text messages.

**Comment by SimonBrandner** [comment]
I can't repro this

**Comment by robintown** [comment]
@manuroe Does the tooltip in the forwarding UI claim the message is still sending, or that it has failed to send?

Also @t3chguy is there any chance I could take a look at the rageshake?

**Comment by t3chguy** [comment]
There's 0 relevant errors in the rageshake

**Comment by robintown** [comment]
It's also possible that @manuroe is expecting the message to be sent just by clicking on the room's name, as with the previous forwarding UX. The "open link" tooltip is apparently not super clear in what it means…

**Comment by robintown** [comment]
@manuroe Can you confirm that you are clicking on the 'Send' button and not the room's name?

**Comment by robintown** [comment]
Closing this as it's quite likely it was just user error - if anyone else is experiencing this and can provide more detail, please open a new issue.
