### ISSUE TITLE
Stuck in dark mode

### ISSUE THREAD

**Issue by WolfIcefang** [vector-im/element-web#17629]
![image](https://user-images.githubusercontent.com/38160450/121724948-39eebe80-caae-11eb-9062-7bc44f94b8aa.png)

### Description

Describe here the problem that you are experiencing, or the feature you are requesting:
I cannot change my theme from dark theme to light theme, and the "use system theme" check box also does nothing. When I hover over the toggle switch in the user menu, the popup says "switch to dark mode" instead of "switch to light mode"
![image](https://user-images.githubusercontent.com/38160450/121725242-9eaa1900-caae-11eb-919e-d4a5091265b0.png)

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points
- I don't normally leave Element running in the background. So, this bug may only occur in a small time frame while the app is still loading.
- Step one: as soon as element opens, click the "switch to dark mode" button from the User menu. (not the All settings menu) I may have clicked the button multiple times in rapid succession by accident, I do not remember. Regardless, if done quickly enough, the theme should not change right away.
- If the bug is triggered, none of the buttons for changing between light and dark mode will work any more.
- 
Describe how what happens differs from what you expected.
- Normally, I expect the buttons that toggle between light and dark mode to... actually change the UI between light and dark. 

Logs being sent: yes
Element username:
@wolficefang:matrix.org

### Version information
- **Platform**: desktop

For the desktop app:
- **OS**: Windows
- **Version**:
- Element version: 1.7.30
- olm version: 3.2.3

Device name	ICEFANG-XPS
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	054657B1-860D-429A-A209-84EB295555BB
Product ID	00325-96113-90233-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points
Edition	Windows 10 Home
Version	20H2
Installed on	‎2020-‎10-‎11
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by t3chguy** [comment]
Fixed on Develop, will be fixed in the next release
