### ISSUE TITLE
There is a weird dot in the reply UI

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17621]
I've also seen it elsewhere
![Screenshot_20210610_204439](https://user-images.githubusercontent.com/25768714/121580253-d1abc880-ca2c-11eb-9195-a214283d362d.png)

**Comment by turt2live** [comment]
this is a floating bullet point from the `<li>`

**Comment by robintown** [comment]
EventTilePreview too: https://github.com/matrix-org/matrix-react-sdk/pull/6000#issuecomment-856319128
