### ISSUE TITLE
both desktop and web element stopped displaying icons signifying no MITM attack in VOIP calls

### ISSUE THREAD

**Issue by sergstesh** [vector-im/element-web#17636]
### Description

In the past performing VOIP calls using various Matrix clients the clients used to display IIRC 5 icons signifying likely absence of Man In The Middle attack. I.e. both parties to the call had to compare the icons and if they were the same, probability of the attack was very low.

For quite a time I do not see such icons. On a side (?) note Nheko Reborn client lost the ability to complete voice calls - apparently trying to negotiate encryption keys for more than a minute.

Anyway, I have two accounts with Matrix, and I have tried to perform VOIP calls using them from different computers. The calls can be established and completed, but, as I wrote, I see no icons.

I carefully examined available setting and see nothing I can change to enable icons.

### Steps to reproduce

Just try a VOIP call.

Describe how what happens differs from what you expected.

No logs yet.

### Version information

- Both web browser and desktop.
- 
For the web app:

- **Browser**: Brave
- **OS**: Linux sergei-dt 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **URL**: app.element.io .
- 
For the desktop app:

- **OS**: Ubuntu
- **Version**: Element version: 1.7.25 , olm version: 3.2.1 .

**Comment by robintown** [comment]
Maybe there was such a feature specific to 1-to-1 VOIP calls a long time ago, but nowadays calls are secured using the same mechanism as encrypted messages. That means that if the user you're calling shows up as "verified" (indicated by a green shield with a checkmark next to their avatar) then the call is secured against MITM attacks. To verify a user, you must open their profile in the right sidebar and click "verify", which will present you with options, one of which is to compare a sequence of 7 emoji. This verification method is probably what you are referring to.

**Comment by dbkr** [comment]
Element has never done this: @robintown is correct: the verification is done via the same mechanism used for other e2e.
