### ISSUE TITLE
There appears to be a nesting of `li`s on develop

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17639]
This looks like a regression caused by one of the recent PRs which made conversions from `li` to `div` and then back? This appears in `EventListSummery`

![Screenshot_20210613_140008](https://user-images.githubusercontent.com/25768714/121806330-aead2e80-cc4f-11eb-942f-df5483d1f8de.png)

**Comment by jryans** [comment]
Aside from being strange markup, does it cause any visual bugs or broken functionality...?

**Comment by SimonBrandner** [comment]
As far as I can tell, no, it doesn't. It's just that the browser isn't very happy about it

**Comment by t3chguy** [comment]
We now put the nested `li`'s in their own `ol.mx_GenericEventListSummary_unstyledList`

![image](https://user-images.githubusercontent.com/2403652/188849013-2bd842d7-d848-44cd-9af9-0ce340de3f0f.png)
