### ISSUE TITLE
Selecting a space that is removed on another device then refreshing Element causes no space to be selected/feeling of infinite loading

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17643]
longest title ever, but it's also the bug description. Created a space on another device, opened it on Element, removed that space on another device, then refreshed Element: infinite load feeling, had to select a space to escape

**Comment by t3chguy** [comment]
Can you still repro this? The area has changed a fair bit

**Comment by t3chguy** [comment]
Presuming no

**Comment by turt2live** [comment]
I didn't get a notification for this :/

Reopening as a reminder to test it.

**Comment by t3chguy** [comment]
@turt2live poke.

**Comment by turt2live** [comment]
Presuming fixed or not important
