### ISSUE TITLE
Displayname overlaps time marker and text in develop.element.io

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#17645]
![image](https://user-images.githubusercontent.com/62639087/121986291-bff85700-cd85-11eb-9b52-2da6a128080d.png)

![matrix](https://user-images.githubusercontent.com/62639087/121988113-4cf0df80-cd89-11eb-9501-213401394f48.png)

### Description

Longer displaynames started going over the time marker and extending to the left of the timeline, hovering over it makes it go over the text in the right. This started happening some time today,

### Steps to reproduce

- Open https://develop.element.io/
- Switch to IRC layout
- Check a long displayname/move the mouse over it

### Version information

Element version: `b96a1551e19f-react-6b4f63df2a70-js-434117c771a6`

**Platform**: Arch Linux, Firefox 89

I think this is the commit that caused the change https://github.com/matrix-org/matrix-react-sdk/commit/91df392a2a79383fa9a8a35cc9e4def6d3d4caab

**Comment by SimonBrandner** [comment]
Probably, regressed by https://github.com/matrix-org/matrix-react-sdk/pull/5880

**Comment by ShadowJonathan** [comment]
This probably happened because `#5880` got onto develop without https://github.com/matrix-org/matrix-js-sdk/pull/1730, so let's wait until that is merged

**Comment by bbhtt** [comment]
> This probably happened because [matrix-org/matrix-react-sdk#5880](https://github.com/matrix-org/matrix-react-sdk/pull/5880) got onto develop without [matrix-org/matrix-js-sdk#1730](https://github.com/matrix-org/matrix-js-sdk/pull/1730), so let's wait until that is merged

Didn't fix it, develop is on `js-9f6ed4fb3381` now.

@https://github.com/SimonBrandner Thanks for the PR.

**Comment by bbhtt** [comment]
Looks like the full mxid (`@displayname:server.tld`) part is overlapping right now when two users of same display name are present in a room.

Reopen this or seperate issue?

**Comment by SimonBrandner** [comment]
> Looks like the full mxid (`@displayname:server.tld`) part is overlapping right now in the same way when two users of same display name are present in a room.
> 
> Reopen this or seperate issue?

Separate issue please, I'll look into it later today
