### ISSUE TITLE
mxid part overlaps time marker and text in develop.element.io while disambiguating

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#17648]
### Description

When two accounts having same displayname are present in a room the mxid part is going over the time marker and extending to the left of the timeline, hovering over it makes it go over the text in the right. 

### Steps to reproduce

- Open https://develop.element.io/
- Switch to IRC layout
- Create similar displaynames and hover over a message.

### Version information

Element version: `b96a1551e19f-react-419baebde912-js-9f6ed4fb3381`

**Platform**: Arch Linux, Firefox 89

Related to, https://github.com/vector-im/element-web/issues/17645 which was fixed.

~Will attach a screenshot.~ Done.

![image](https://user-images.githubusercontent.com/62639087/122020386-41ff7480-cdb4-11eb-81d4-183cc99a8c83.png)

**Comment by t3chguy** [comment]
I disagree on it being a release blocker given that IRC layout is experimental

![image](https://user-images.githubusercontent.com/2403652/122209377-5e76dc00-ce9c-11eb-85a2-d3f384caf239.png)

**Comment by SimonBrandner** [comment]
Yeah, you're right, though it wouldn't be bad to have a fix to merge into release. I'll see what I can do
