### ISSUE TITLE
"Currently joining 1 room" indicator doesn't disappear

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#17656]
### Description

"Currently joining 1 room" indicator doesn't disappear
### Steps to reproduce

Join a room, wait, see that lil spinnter.

### Version information

Element version: e999524e0395-react-520763a045a3-js-9f6ed4fb3381

For the web app:

- **Browser**: FF
- **OS**: macos
- **URL**: develop.element.io

**Comment by benparsons** [comment]
![Screenshot 2021-06-15 at 15 40 50](https://user-images.githubusercontent.com/1197991/122073591-7002aa00-cdf0-11eb-9cb2-75040dd43741.png)

**Comment by benparsons** [comment]
Logs sent

**Comment by robintown** [comment]
Potentially fixed by matrix-org/matrix-react-sdk#6114, which refactors that indicator

**Comment by novocaine** [comment]
@benparsons have you seen this recently?

**Comment by benparsons** [comment]
No I haven't, seems good!
