### ISSUE TITLE
I get "Failed to invite users to chat", but it worked.

### ISSUE THREAD

**Issue by rambip** [vector-im/element-web#17654]
### Description

I host synapse on my server, I enabled federation and everything worked fine (so I'm not sure the issue is related to that)

I get an error when I try to invite a bot from another server.
I created a public room (not encrypted) and invited friends from my server. Everything went fine.

Then I invited a bot (@xkcd:maunium.net) and I got this error:

> Failed to invite the following users to chat: @xkcd:maunium.net

![screenshot](https://user-images.githubusercontent.com/62420525/122061935-41d09a80-cdef-11eb-823c-fd89d5e5a408.jpeg)

But the thing is: the invitation worked !

The bot was in the room and worked well.

I'm admin, but the bug also append with a non-admin user.

Logs being sent: yes/no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chomium-based
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by t3chguy** [comment]
This sounds like a server bug then, where it responds with an error code for an action which actually was successful.

**Comment by t3chguy** [comment]
If you are still experiencing this please open a bug in https://github.com/matrix-org/synapse/
