### ISSUE TITLE
Newlines don't get rendered in messages without HTML formatting

### ISSUE THREAD

**Issue by dzaima** [vector-im/element-web#17658]
### Description

Newlines aren't rendered in multiline messages with just a plain text body, without `"format": "org.matrix.custom.html"` and `"formatted_body"`.

### Steps to reproduce

- Send a message containing two lines with no other formatting, such as:
  ```
  line 1
  line 2
  ```
- Observe that it's rendered as `line 1 line 2`, without the newline.
  But, if there's any formatting, like:
  ```
  line 1
  line _2_
  ```
  then the newline will appear.

The primary issue is that `\n`s in `"body"` aren't respected (meaning that text-only clients cannot send multiline messages).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium 91.0.4472.101
- **OS**: Linux Mint 20.1
- **URL**: Happens on both develop.element.io and app.element.io

https://user-images.githubusercontent.com/5551338/122071849-c1fefc00-cdff-11eb-9299-b1fd1894b2c4.mp4

**Comment by aaronraimist** [comment]
Hmm I cannot reproduce in Firefox on macOS or the desktop app on macOS.

```
{
  "type": "m.room.message",
  "sender": "@aaron:raim.ist",
  "content": {
    "msgtype": "m.text",
    "body": "line 1\nline 2"
  },
```

<img width="162" src="https://user-images.githubusercontent.com/5855073/122127642-1a7ecb00-cdf9-11eb-8ca4-b15fa19d7300.png">

**Comment by dzaima** [comment]
Ugh.. Appears a userstyle was messing with this. Don't know how I didn't think to check that.
