### ISSUE TITLE
Move dial pad button

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17652]
We'd like to move the dial pad button which is currently conditionally shown in the '+' menu in the 'people' section. Designs incoming for the new place, but note that it will have to only show when the HS supports phone number lookup in the same way that it currently conditionally shows the menu.

**Comment by dbkr** [comment]
Assigning to @gaelledel to update when designs are confirmed

**Comment by gaelledel** [comment]
Done, passing to you @anoadragon453 please see design specs here https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=4678%3A2541
