### ISSUE TITLE
IRC error on #gnome-design: err_needreggednick

### ISSUE THREAD

**Issue by Verhoeckx** [vector-im/element-web#17660]
Hello Element,

When I try to join the group GNOME Design I get the following error:
```
You were kicked from GNOME Design by GimpNet IRC
Reason: IRC error on #gnome-design: err_needreggednick
```

What is the reason for this error and what can I do?
I get the this error for the last two days.

It doesn't matter if I use de web application of the mobile application.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-getting-kicked-out-of-a-bridged-room-with-the--err_needreggednick-error

Unrelated to Element, it is an IRC Bridge issue. I suggest #irc:matrix.org for future such queries.
