### ISSUE TITLE
Setting to not show message deleted message and to not show the original message

### ISSUE THREAD

**Issue by ProtoByter** [vector-im/element-web#17664]
#### Is your suggestion related to a problem? Please describe.
I am a moderator/admin on a discord server which is bridged to matrix (via matterbridge), one of the bots we use on this discord server (pluralkit) deletes messages made by certain people and reposts them via a webhook, on the matrix side this looks like this:
![unknown-1~2](https://user-images.githubusercontent.com/20995169/122171215-61aba100-ce77-11eb-99f2-f1f05e9a6046.jpg)
This happens for every single message sent by someone on discord set up with pluralkit, so the messages are effectivley doubled in size compared to people on the discord side without pluralkit or people using matrix natively
We've faced severe resistance to the idea of removing pluralkit. So we can't think of anything we can do to stop this.

#### Describe the solution you'd like.
I thought it'd be useful to have a setting which makes it so that the deleted message message and the original message aren't shown, this would likely be a toggle setting somewhere in the matrix user settings (or possibly as a server setting) which enables this functionality

#### Describe alternatives you've considered.
Removing the bot - Severe resistance
Removing the matrix bridge - Not an option

#### Additional context
No other context needed

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/122174758-e2b86780-ce7a-11eb-9c02-a238c5769d0f.png)

You mean like this existing setting?

**Comment by ProtoByter** [comment]
Sorry for opening this issue, I didn't see that b4
