### ISSUE TITLE
Error leaving room, not in room

### ISSUE THREAD

**Issue by austinbutler** [vector-im/element-web#17662]
### Description

I get an error saying `Error leaving room`, my user is `not in room !AinLFXQRxTuqNpXyXk:matrix.org`. Happens both on Element Desktop on Linux and Element Android. Same as https://github.com/vector-im/element-web/issues/10323 which was closed.

### Steps to reproduce

- Click three dots next to room name on left sidebar
- Click "Leave Room"

Logs being sent: yes

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: NixOS
- **Version**:  1.7.30

**Comment by t3chguy** [comment]
This is a server-side error, hence it happening on both devices

**Comment by Slabity** [comment]
I'm running into this issue too:

![2021-07-09-171035_629x191_scrot](https://user-images.githubusercontent.com/3788421/125136349-aa522500-e0d8-11eb-9fd4-81923c3e244b.png)

I don't even know what this room is or how I joined. It does not have any title and coes up as "alex and 1449 others"

How can I remove this room from my account? Is there any way I can manually manage that information?

**Comment by aaronraimist** [comment]
@Slabity Try clicking the Clear Cache button in the Help & About section of settings

**Comment by t3chguy** [comment]
This is a Synapse issue, it has a case where it can leave the room successfully yet not inform the client down /sync

If you continue to see this, please open an issue in https://github.com/matrix-org/synapse/
