### ISSUE TITLE
Replace Freenode with Libera.chat in channel browser

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#17676]
The Element channel browser ("Explore room" button) has a list of predefined servers, which is currently Matrix, W3C, Snoonet, OFTC, Freenode. With the recent hostile takover and subsequent self-immolation of Freenode, and with pretty much all projects having moved to Libera.chat, it should probably be replaced.

![Element server selector](https://user-images.githubusercontent.com/145412/122353190-1addaa00-cf50-11eb-8552-9c0cb04df143.png)

**Comment by t3chguy** [comment]
W3C, Snoonet, OFTC, Freenode are all given by your server, matrix.org via the https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-thirdparty-protocol-protocol API

You can add libera by using `Add a new server...` and adding `libera.chat` - as for removing Freenode you would need to ask matrix.org's support that or switch servers.
