### ISSUE TITLE
Libera bridge zombie - doesn't work but cannot remove

### ISSUE THREAD

**Issue by thejpster** [vector-im/element-web#17677]
### Description

The channel #rust-retro wishes to bridge to ##rust-retro on Libera. We attempted to set up an integration but it was early days and it did not work. We have the appservice user in our matrix room but messages are not transferred.

If I try to add another IRC integration it says "HTTP 500" and something about being "double bridged". If I try and remove the existing integration, I get a different HTTP 500 error.

### Steps to reproduce

- go to the #rust-retro room in app.element.io
- open the integrations panel
- try to add an IRC bridge to Libera, get a 500 error
- try to remove existing (broken) bridge, get a 500 error

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: have tried Firefox on Android and on Ubuntu
- **OS**: Android and Ubuntu
- **URL**: app.element.io

**Comment by turt2live** [comment]
#irc:matrix.org on Matrix would be best to troubleshoot this.
