### ISSUE TITLE
Info popup on re-request encryption keys link is now misleading

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17670]
This was written pre-cross-signing and talks about if you dismissed the key share request, but we haven't displayed key requests since cross-signing.

**Comment by kittykat** [comment]
@amshakal could you propose new copy for this please?

**Comment by richvdh** [comment]
There is no "re-request encryption keys link" any more (https://github.com/matrix-org/matrix-react-sdk/pull/9544).
