### ISSUE TITLE
UI kit and basic styles Clean up 

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#17685]
Design is currently cleaning up the Element UI components and basic styles such as colours and text styles.
The ultimate goal is to accomplish the same in the code and aim to create consistency and harmony between design and development.
We're starting the cleaning work with basic styles first (colours and text styles)

COLOURS
To start with, I have drastically reduced the colour palette to 25 colours in total. These colours account for both Light and Dark themes and are referenced as Global colours here: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1338%3A17947

I have also created a Web specific colour guide with appropriate variable namings here: https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1521%3A23025

You can see these colours being applied on the web UI here https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/?node-id=1336%3A18405

TEXT STYLES
A list of text styles is defined here 
https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1336%3A17757
It would be ideal to use the variable naming convention proposed in the "font in Figma" column. Again this will ease communication between design and development if the need of text referencing occurs.

Any question let me know :)

**Comment by turt2live** [comment]
Closing as checklists like this are unfortunately not as helpful in modern times. I believe we're also using different places to track this sort of work, so should be covered there.

If needed, please break the issue down into newer, smaller, issues for consideration.
