### ISSUE TITLE
Investigate why artifacts are not uploaded if e2e tests are not successful

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17696]
So looks like artifacts for e2e failures don't upload then
https://github.com/matrix-org/matrix-react-sdk/actions/runs/950540745

https://buildkite.com/matrix-dot-org/matrix-react-sdk/builds/11747#4627aab2-6972-44e9-a302-179a108a798d has all the expected artifacts

**Comment by t3chguy** [comment]
[`958d4df` (#6215)](https://github.com/matrix-org/matrix-react-sdk/pull/6215/commits/958d4df957f065d321c08e04e73428c5020a6455) fixes this
