### ISSUE TITLE
Too easy to accidentally deactivate account.

### ISSUE THREAD

**Issue by adamlsd** [vector-im/element-web#17695]
### Description

If you click on "Deactivate account" and you did not sign up with SSO from an external service, then your account will be automatically deleted without a chance to cancel.

### Steps to reproduce

- Create a new account in the web UI.
- Do not use account integration with any other service (Just use name and password)
- Finish the entire registration process.
- Go to "All Settings"
- Click "Deactivate Account"
- Touch nothing, just wait 15-20 seconds (the minimum time it might take to read and understand the warning message)
- The warning will vanish, you will be marked logged out, the account is now dead.

Describe how what happens differs from what you expected.

The warning should stay on the screen until the user clicks their consent that they wish to destroy the account, or that they wish to keep their account.

My speculation on what is going on (this is just a guess):

There is a "loading..." prompt near the bottom of the warning box.  That may be an attempt to load SSO dialogues for confirmation of the attempt to remove the account.  When this loading fails (as no external service is associated), somehow this triggers the popup dialogue to close in such a way as to make the page think that the user wants to kill the account.

Log: not sent    

I don't think I can send a log, as when the account is destroyed, you can't access anything.  The page eventually reloads and you're at the main login page.

### Version information

- Web browser.

For the web app:

- Firefox (78.10.0esr 64-bit)
- Debian "Bulllseye"
- app.element.io

**Comment by t3chguy** [comment]
See https://github.com/vector-im/element-web/issues/16870#issuecomment-862614884

**Comment by adamlsd** [comment]
@t3chguy Thanks for linking this to the ongoing discussion.

In my local browser this seems to have been resolved since filing this bug a few minutes ago, FYI.
