### ISSUE TITLE
Editing does not instantly update the shown message

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17702]
### Description

edit is only displayed after switching rooms back and forth

![image](https://user-images.githubusercontent.com/2803622/122636913-0cc49080-d0ec-11eb-8d03-ae8a478a4379.png)

![image](https://user-images.githubusercontent.com/2803622/122636921-177f2580-d0ec-11eb-9fbd-2427e537b042.png)

### Steps to reproduce

- post msg
- press arrow up to edit
- edit
- enter
- see it say (edited) and view the edit history. however the edit is only displayed after switching rooms back and forth

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021061901-1

**Comment by HarHarLinks** [comment]
This also applies to edits by other room members.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6196 / https://github.com/matrix-org/matrix-js-sdk/pull/1738

**Comment by turt2live** [comment]
immediate issue fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6196 - leaving open for further investigation.

**Comment by jryans** [comment]
Removing release blocker since the regressing change was reverted.

**Comment by turt2live** [comment]
Closing this issue as it's not actually an issue in current releases, but if we ever do re-launch the problematic feature then it'll become an issue again. I've tracked this awkward state here: https://github.com/vector-im/element-web/issues/18193
