### ISSUE TITLE
when replying, the original message could not be displayed

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17708]
### Description

![image](https://user-images.githubusercontent.com/2803622/122667653-3648ef00-d1b4-11eb-8ef1-79ec405b1407.png)

Even though the message it is trying to reply to is directly above it. Seems to be some kind of race. Can be resolved by switching to another room and back.

perhaps related to #17702 #17703 ?

### Steps to reproduce

- restart element
- open a room with a bunch of replies

Logs being sent: no

### Version information
  
  
  
  - **Platform**: desktop
  
  For the desktop app:
  
  - **OS**: Arch
  - **Version**: aur/element-desktop-nightly-bin 2021061901-1

**Comment by t3chguy** [comment]
This should be fixed on today's Nightly. (2021062001)
