### ISSUE TITLE
Quote button stopped working

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17715]
### Description

Somehow the quote button has stopped working.
![image](https://user-images.githubusercontent.com/2803622/122785686-dd608000-d2b3-11eb-9878-80e4af525aab.png)
Perhaps related to matrix-org/matrix-react-sdk#6196 / matrix-org/matrix-js-sdk#1738.

### Steps to reproduce

- hover msg
- click ...
- click quote
- menu disappears, but nothing happens

message's content should be copied into input field, after a > as to indicate this is a quote

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021062101-1

**Comment by SimonBrandner** [comment]
I have no idea why, but `ComposerInsertPayload` on the following line is the problem: https://github.com/matrix-org/matrix-react-sdk/blob/439e5628f5cceabcae13142e6253ce0c003b9041/src/components/views/context_menus/MessageContextMenu.js#L204 Without that everything works just fine

**Comment by robintown** [comment]
@SimonBrandner Just looks like somebody was trying to use typescript in a javascript file

**Comment by SimonBrandner** [comment]
It looks like I am blind :P

**Comment by t3chguy** [comment]
oh dear, how'd I manage that :D
