### ISSUE TITLE
Modals launching other Modals no longer work

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17716]
<img width="807" alt="Screen Shot 2021-06-21 at 16 36 02" src="https://user-images.githubusercontent.com/769871/122789179-ef8bef80-d2ae-11eb-9e3d-b94719602b93.png">

**Comment by aaronraimist** [comment]
also if you try to reproduce this, the sign out button will stop working until you refresh the page

**Comment by HarHarLinks** [comment]
related or not related, but also happened to me here: https://github.com/vector-im/element-web/issues/17593#issuecomment-859642750

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6185

**Comment by t3chguy** [comment]
So I think we're hitting some race inside the guts of React.
If I add a `setImmediate` on the `ReactDOM.render` call or I set up a breakpoint then it works fine.

```diff
Index: src/Modal.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Modal.tsx	(revision 54c3832b5b9dde5981eb1934f599e7b75eac00e8)
+++ src/Modal.tsx	(date 1624303471241)
@@ -385,7 +385,7 @@
                 </div>
             );
 
-            ReactDOM.render(dialog, ModalManager.getOrCreateContainer());
+            setImmediate(() => ReactDOM.render(dialog, ModalManager.getOrCreateContainer()));
         } else {
             // This is safe to call repeatedly if we happen to do that
             ReactDOM.unmountComponentAtNode(ModalManager.getOrCreateContainer());

```

Not sure what the best way to proceed is here

**Comment by t3chguy** [comment]
Actually the keywords modal was only broken because I attempted to visit send debug logs. So this looks to affect non-priority non-static modals when one closes itself and then opens another in the very same tick.
