### ISSUE TITLE
the composer is very laggy when resizing vertically now, which ends up feeling like a scroll jump

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17735]
as you type multiline messages, the composer expands vertically. except it now does so on a ~100ms lag, which makes it feel like something unrelated to your typing has caused a layout change, which is very disorienting

**Comment by ShadowJonathan** [comment]
According to #18022 it's even worse now, ~5000ms :(

**Comment by davidegirardi** [comment]
Is this still the case? I the expansion of the composer on multiline messages feel synchronous in Nightly and latest stable.

**Comment by t3chguy** [comment]
Think this got fixed with CIDER, was an issue with draft.js
