### ISSUE TITLE
Buttons in toast are massive and overly bold-feeling

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17730]
![](https://i.imgur.com/YuTTT82.png)

It's a bit of a shock to the system when this toast appears - hard to read the text of the buttons, and their size/boldness overwhelms the train of thought a bit.

**Comment by gsouquet** [comment]
This was a request from the design team to deprecate `FormButton` and use the `AccessibleButton` everywhere

* vector-im/element-web#17678
* matrix-org/matrix-react-sdk#6229

Going to remove a couple of tags set above as I don't think this is a regression nor a release blocker, but would definitely be good to hear the product's team opinion to know how we want to move this forward

**Comment by turt2live** [comment]
@gsouquet was the dark theme considered? The light theme version feels fine for the most part, but on the dark theme it's a beacon of distraction

**Comment by gsouquet** [comment]
I believe this is using the same color scheme as the rest of the platform the buttons on the platform

We have not specifically discussed the details in the dark theme as those colors/font-weight are already in use within the dark theme

Probably a good time to ping @vector-im/design / @gaelledel to discuss this further

**Comment by kittykat** [comment]
@turt2live do you still feel that the buttons should be updated? They don't really look out of place to me as they are now:

![Screenshot from 2021-12-22 10-30-19](https://user-images.githubusercontent.com/51663/147078678-5389eedc-0be6-4d09-8586-4dae9c2a7831.png)
