### ISSUE TITLE
Layout shift when hovering a voice message in FilePanel

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17737]
<img width="404" alt="Screen Shot 2021-06-23 at 10 21 32" src="https://user-images.githubusercontent.com/769871/123071832-e749c680-d40c-11eb-8ca2-78f83f39e3cf.png">

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/17608

**Comment by turt2live** [comment]
Counting as a duplicate of that issue due to no designs.
