### ISSUE TITLE
about desktop client safety protection

### ISSUE THREAD

**Issue by 0x00Finch** [vector-im/element-web#17732]
#### Is your suggestion related to a problem? Please describe.
> I felt unsafe when leaving the desktop client without any form of password of pin protection like android version(which has pin and bio auth)

#### Describe the solution you'd like.
> I would like to have some sort of password protecting feature

#### Describe alternatives you've considered.
> None

#### Additional context
> None

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/3777
