### ISSUE TITLE
Dial Pad doesn't look great on the dark theme

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#17736]
### Description

The dial pad is difficult to read when using Element's dark theme.

![image](https://user-images.githubusercontent.com/1342360/123070910-16ac0380-d40c-11eb-866f-3f9664ed6ec6.png)

![image](https://user-images.githubusercontent.com/1342360/123070953-1e6ba800-d40c-11eb-8427-94f5d94f1145.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 89.0.1
- **OS**: Arch Linux
- **URL**: develop.element.io `54da2df8c0f6-react-35b8f79fbd1f-js-1171c33f7af9`

**Comment by dbkr** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/5786 fixes this
