### ISSUE TITLE
`onAction` in TimelinePanel sometimes gets called twice

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17738]

**Comment by t3chguy** [comment]
I cannot repro this on latest nightly

**Comment by SimonBrandner** [comment]
It looks https://github.com/matrix-org/matrix-react-sdk/blob/6d6995e6fb4d01accc47754209f39f082f100031/src/components/structures/TimelinePanel.js#L442 sometimes gets called twice. This is _not_ happening only for `Action.ComposerInsert`

**Comment by SimonBrandner** [comment]
Oh, this is a fun bug! :smile: This only happens when you're also viewing the file panel - another `TimelinePanel`. Both timelines then react to the action and re-dispatch - pill gets inserted twice
