### ISSUE TITLE
sender_claimed_keys not always included in E2E room key export even though required

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#17733]
The spec says it is required https://spec.matrix.org/unstable/client-server-api/#key-export-format 
and it breaks tools like https://github.com/russelldavies/matrix-archive which expect it to exist

https://matrix.to/#/!JiiOHXrIUCtcOJsZCa:matrix.org/$2fsSk0WCGPOUzMOMBJZgyUuA_ZgiQoZHf9o1MbnAudQ?via=matrix.org&via=privacytools.io&via=converser.eu

<img width="240" src="https://user-images.githubusercontent.com/5855073/123015107-4667f680-d38d-11eb-8512-2a3ce20603d0.png">

**Comment by aaronraimist** [comment]
Maybe related to https://github.com/vector-im/element-web/issues/14323

**Comment by turt2live** [comment]
@aaronraimist are you still seeing this? I've just exported from both a test account and production account and everything seems fine with it (not a single entry missing the `sender_claimed_keys`).

**Comment by aaronraimist** [comment]
Appears to be fixed. I made a new export using Element 1.11.8 and every entry has `sender_claimed_keys` now.
