### ISSUE TITLE
Apple silicon: upgrade path from Intel builds

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#17758]
At least initially, we'll be distributing two tracks of builds, Intel and Apple silicon, and updates will serve the same architecture already installed.

We may want to automatically switch those using existing Intel builds on Apple silicon over to the matching native build at upgrade time, if we believe it's safe to do so. Or if we do add Universal builds (https://github.com/vector-im/element-web/issues/17757), that's another possible target as well.

**Comment by turt2live** [comment]
1.8.0 is meant to have this now; please reopen if I'm wrong.
