### ISSUE TITLE
Audio/Video Call Not Terminating on Browser Refresh or Logout

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17754]
Steps to reproduce:

- Place a Audio/Video Call from User A to User B
- User B gets an notification for incoming call do not pick the call.
- Refresh the browser or logout from User A's side.
- User B still getting the incoming call notification.

And even if the call is connected and then User A, refreshes the browser window or logout the widget is deleted from his side but not from the User B's side.

**Comment by SimonBrandner** [comment]
I have my doubts about this being possible: Before we log out we hangup the call but the hangup event probably doesn't get sent. Theoretically, we should be able to wait for the event to get sent before logout. The thing is I have my doubts about us being able to make sure that the hangup event got sent before a refresh. I am not sure we can block the browser. Potentially, we could use something like _Are you sure you want to quit this page, you seem to have unsaved work_.

**Comment by Sr-Preet** [comment]
@SimonBrandner 
Thanks, I'll see if this can resolve my issue.
