### ISSUE TITLE
Apple silicon: Universal builds

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#17757]
We may want to additionally offer Universal builds (combining both macOS architectures into one package). At the moment, the work in https://github.com/vector-im/element-web/issues/16075 only adds separate nightly builds for Apple silicon, matching what happens for Intel at the moment.

See https://github.com/vector-im/element-web/issues/16075 and https://github.com/vector-im/element-desktop/pull/216 for some previous discussions on whether to offer Universal builds.

**Comment by turt2live** [comment]
1.8.0 is meant to have this now; please reopen if I'm wrong.
