### ISSUE TITLE
Prompted to verify against other devices even if there aren't any

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17765]
Signing into an account which doesn't have any other devices logged in will still tell you to verify against another device.

Same bug on iOS: https://github.com/vector-im/element-ios/issues/4474

**Comment by robintown** [comment]
Regression since this was supposedly fixed before: #13289

**Comment by duxovni** [comment]
Fixed in matrix-org/matrix-react-sdk#6811
