### ISSUE TITLE
Implement device trust view in user settings

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17767]
Currently it's only in your own user profile view in the room sidebar & we direct the user there to do things like verify

**Comment by jryans** [comment]
https://github.com/vector-im/element-web/issues/11221 is a related issue for the 2019 device list designs that covered this area and more.

We should definitely add this one or another, as it will greatly improve the feel of the app and resolve a lot of confusion.

**Comment by dbkr** [comment]
Designs for this are in the 'cross signing' figma under 'settings' which I really wish I knew how to get a link to from figma

**Comment by jryans** [comment]
> I really wish I knew how to get a link to from figma

After selecting a nearby frame, on the web, you can just copy the address bar. On desktop, you may need to use top-right Share button -> Copy link.

I believe https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=6%3A364 is pointing near the right place.

**Comment by amshakal** [comment]
I updated the design based on the new design system

https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=7698%3A113101

**Comment by kittykat** [comment]
@amshakal would it be possible to trigger verification from that setting panel for an unverified device? The issue of it being difficult to re-trigger verification came up in our community testing session last week.

**Comment by duxovni** [comment]
I feel like that'd be pretty easy to include alongside the Rename/Sign Out buttons for unverified devices, I'll proceed in that direction pending feedback.

**Comment by amshakal** [comment]
Yeah, I agree, that would be useful. @duxovni we can look at the flow together if you like?
