### ISSUE TITLE
Creating account & then logging out leaves account with no SSSS

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#17764]
* Create account on web
 * Log out without doing anything (or presumably even just not making/joining an encrypted room)
 
You're logged out with no prompt and the account is left with cross-signing set up but no other devices and no SSSS

**Comment by jryans** [comment]
Perhaps it’s already known, but I believe this was originally tied in with the intentional choice to wait for and encrypted room to avoid key prompts during first setup.

**Comment by duxovni** [comment]
Since this is a deliberate choice as jryans said, and we've also now made it simpler to reset cross-signing keys on a new login if there's no SSSS and no other devices (#18536), I'm closing this and opening #20307 for a usability improvement in the case where there aren't even any encrypted chats.
