### ISSUE TITLE
Multiple reports of the IRC layout being broken/regressed

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#17778]

**Comment by joepie91** [comment]
Known issues:
- #17748 (Timestamps display inconsistently and/or are jumpy)
- #17648 (MXID overlaps timestamp when disambiguation is applied)

**Comment by jryans** [comment]
Seems like https://github.com/vector-im/element-web/issues/17748 is not a regression, just an existing defect.

**Comment by SimonBrandner** [comment]
> Seems like #17748 is not a regression, just an existing defect.

Yeah, that is the case

**Comment by bakkot** [comment]
Is there a timeline for getting this fix upstreamed and released to the element.io client? Anything I can do to help?

**Comment by SimonBrandner** [comment]
> Is there a timeline for getting this fix upstreamed and released to the element.io client? Anything I can do to help?

As you can see the issue has been already closed - a fixed version is available at develop.element.io or staging.element.io and will be available on app.element.io in a few days
