### ISSUE TITLE
Space shortcuts don't work on layouts with non-English keys in the places of numbers

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17776]

**Comment by t3chguy** [comment]
Yup, though the keyboard shortcuts dialog does say digits, not "keys where QWERTY has digits"

**Comment by SimonBrandner** [comment]
> Yup, though the keyboard shortcuts dialog does say digits, not "keys where QWERTY has digits"

True, but this is quite a standard thing for apps to do
