### ISSUE TITLE
UI to set layout setting at account level

### ISSUE THREAD

**Issue by phi-gamma** [vector-im/element-web#17773]
### Description

Checking “Enable experimental, compact IRC style layout” in the appearance
settings works. However, when I log out and back on again the setting is
lost and I have to re-check that item.

### Steps to reproduce

1. Check “Settings → Appearance → Show Advanced → Enable experimental, compact
   IRC style layout” to switch to the IRC layout.
2. Sign out, sign back in again.
3. Layout is reverted to the default.

### Version information

Current element web, the version that runs on element.io.

- **Browser**: Firefox, 89.0 (64-bit).
- **OS**: Linux (NixOS, Fedora).
- **URL**: app.element.io

**Comment by t3chguy** [comment]
Yup. The setting is set at a per-device level. This is so you can have a different layout on different sized devices. When you log out you wipe your per-device settings. The setting itself supports being set at the account level but the UI exposed sets at the device level only.

**Comment by phi-gamma** [comment]
Could there be an option to apply this globally? I don’t really think in terms of “devices”
when I use a website. Rather I expect the presentation to be consistent across browsers
and logins.

**Comment by SimonBrandner** [comment]
I think this is one of the things we'll look into when working on the [bubble layout](https://github.com/vector-im/element-web/issues/4635)

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/15985
