### ISSUE TITLE
Offline times are suddenly hyper-precise

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#17786]
![offline](https://user-images.githubusercontent.com/48614497/123453363-7261c280-d5ad-11eb-99c7-ef70b6a9ec4a.png)
Probably related to the [TSification of PresenceLabel](https://github.com/matrix-org/matrix-react-sdk/pull/6251)?

**Comment by SimonBrandner** [comment]
Yeah, I think I now what's the cause of that, will look into it tomorrow
