### ISSUE TITLE
Online status indicator. 

### ISSUE THREAD

**Issue by Monstanner** [vector-im/element-web#17797]
#### Is your suggestion related to a problem? Please describe.

Unfortunately, you don't know if someone is online.

#### Describe the solution you'd like.

You should be able to adjust your online status. You should also have the option of setting in order to be able to select the status. 

For example:

Online
Away
Do not disturb
Invisible (as it is now)
Own status text

This should then be displayed to your contacts. Either as a word or as a colored dot, as is the case with the unread messages dot-indicator for the Spaces.

For example for the dot-indicators:

Online = green
Away = yellow
Do not disturb = red
Invisible (as it is now) = Nothing (but gray for yourself)
Own status text = white

**Comment by t3chguy** [comment]
There is already online/away/offline coloured dot indicators. If you or your friend is using the matrix.org server then they disabled presence but it works on most other servers.

**Comment by dietriro** [comment]
Hi, is there any plan of introducing a feature which allows you to manually set this online status? We have a matrix server at our university but due to data privacy concerns the university has disabled the online indication feature. They can only enable it if it is possible to manually set the status to invisible or something like that. 

It would be great if this would be implemented at some time in the future.

**Comment by cpot** [comment]
> Hi, is there any plan of introducing a feature which allows you to manually set this online status? We have a matrix server at our university but due to data privacy concerns the university has disabled the online indication feature. They can only enable it if it is possible to manually set the status to invisible or something like that.
> 
> It would be great if this would be implemented at some time in the future.

Any news about this feature request ? Why this feature request has been closed ?

**Comment by gschnepp** [comment]
Matrix protocol already has that setting, but there's no representation yet to let the user set his presence state manually in Element or FluffyChat (that's the clients I have here so far). Here is the relevant documentation for the Getter/Setter:

https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3presenceuseridstatus
https://spec.matrix.org/v1.2/client-server-api/#put_matrixclientv3presenceuseridstatus

Looks like an easy job. Just some UI tweaking to allow user to set his state. I'm not able to do this on my own unfortunately.

**Comment by loafbutts** [comment]
Still hoping to see this added in Element. The home server I use has presence enabled but there remains no way to set your status manually. This would be very helpful to have.

**Comment by Randywfl** [comment]
I see hints here and there that Element already includes online status indicators but I cannot find any indication where said indicators are located or how to adjust those status conditions.  Would be great if it was made obvious in the UI itself.

**Comment by MairusuPawa** [comment]
I'll chime in as well as a new user. I'm using a few clients here and there, and it was weird to me that I could set a status message on my phone (using Fluffy) and couldn't remove it when back on my desktop (using Element).

**Comment by AWestermeyer** [comment]
Hi. Any update on this topic ?

**Comment by Randywfl** [comment]
My update is we gave up on Element and moved to "Wire".
