### ISSUE TITLE
FilePanel fails to show all files in (non-E2EE) rooms.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17806]
Either it fails to backpaginate and just sits there, or if it does, it seems you can end up with jumps in its timeline such that files are missing.

**Comment by ara4n** [comment]
<img width="1711" alt="Screenshot 2021-06-28 at 03 20 27" src="https://user-images.githubusercontent.com/1294269/123570400-099e6400-d7c0-11eb-9d99-0f30c7de00a5.png">

^ for example

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17753
