### ISSUE TITLE
Weird white blob in bottom right of new msg fwding UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17805]
<img width="555" alt="Screenshot 2021-06-28 at 02 39 15" src="https://user-images.githubusercontent.com/1294269/123567535-4a937a00-d7ba-11eb-9f5e-a7f45d21b73b.png">

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/123654081-a3e4c300-d825-11eb-8671-7e5b2100686c.png)

Hmm I cannot repro this

**Comment by robintown** [comment]
@t3chguy I believe it's Chrome/Electron only

**Comment by t3chguy** [comment]
Ah yup

**Comment by t3chguy** [comment]
I think its the scrollbar or something, using overscroll auto instead of scroll fixes it
