### ISSUE TITLE
"Start Chat" button isn't scaling correctly on Element Desktop

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#17802]
![image](https://user-images.githubusercontent.com/74838472/123564342-b8ba4b80-d77e-11eb-89a7-3343eeef1a39.png)
*(see right above the Git logo)*

### Description

The background on the `+` button for starting a new chat isn't scaling properly when set to certain sizes.

### Version information

- **Platform**: Desktop
- **OS**: Ubuntu 20.04
- **Version**: 1.7.31

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17068
