### ISSUE TITLE
Roomlist filter filters wrong

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17810]
This is happening pretty regularly, and anecdotally has been happening for a few weeks.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1922197/123617101-d202dc80-d7fe-11eb-9124-f9766dcde12a.png">

**Comment by lampholder** [comment]
Gah:

![image](https://user-images.githubusercontent.com/1922197/123801081-d227d880-d8e1-11eb-9a8b-0cd7a68a6705.png)

**Comment by lampholder** [comment]
Is anyone else seeing this? It's making the app very difficult for me to use :(

**Comment by Yoric** [comment]
I have the same issue.
I have ~50 rooms and the filter doesn't do its work, which makes my life much more complicated than with element-web.

Using version 1.7.31 (1.7.31).

**Comment by eras** [comment]
I have the same issue. It might not be clear from the description, but in addition to finding incorrect matches, _it also fails to find correct ones_.

Sometimes visiting the destination room by other means (e.g. breadcrumbs) solves the search for that particular room.

**Comment by jaywink** [comment]
Yeah was just about to report this. A room I was looking for was not found, I presumed because it has not had activity for a while.

I wrote to it, went to another room and now it comes up first. Initially it didn't come up in the results at all.

**Comment by t3chguy** [comment]
It is possible you have duplicates in your room list at the time this happens? The way the duplicates manifest themselves is by overwriting other entries in the room list, its wholly possibly that the search still treats the duplicates using their original (correct non-duplicated) name, which would explain

> Sometimes it feels that it finds the correct number of matches, but the matches are incorrect.

**Comment by t3chguy** [comment]
This is indeed a manifestation of https://github.com/vector-im/element-web/issues/14508

Room filters are applied on the correct metadata, but the UI shows the wrong room in the tile, and clicking it goes to that wrong place
