### ISSUE TITLE
User mentions in element web appear as normal text.

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17815]
User mentions in element web appear as normal text.
Can anyone please help me regarding this.
![CPT2106281846-864x150](https://user-images.githubusercontent.com/55445693/123642931-7ad22b80-d841-11eb-811c-00c3b63e5df6.gif)

**Comment by SimonBrandner** [comment]
@Sr-Preet, you seem to be using a customized version of Element. Can you repro on app.element.io?

**Comment by Sr-Preet** [comment]
@SimonBrandner 

No simon, this is working fine on the current element.
I'm not able to find the specific code behind this behavior 
Can you help me please

**Comment by SimonBrandner** [comment]
If this isn't an issue with the official version, then I can't, sorry
