### ISSUE TITLE
Unable to invite anyone to rooms (on matrix).

### ISSUE THREAD

**Issue by adamlsd** [vector-im/element-web#17820]
Unable to screenshot.

### Description

When attempting to add people to a room (at least on matrix.org), it gives errors in trying to invite people.

### Steps to reproduce

- Create a new room
- Invite a user
- An error message saying that the operation failed is reported.  No further information.

Expected to successfully invite a user to a room.

Log: sent    

### Version information

- Debian 10, running Matrix
For the desktop app:

- Debian 10
- Element version: 1.7.30 (olm version: 3.2.3)

**Comment by uhoreg** [comment]
Thanks for the report.  There was an issue with the matrix.org server which has now been fixed.
