### ISSUE TITLE
Changing the text on room mention.

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17823]
Hi,
I just wanted to know if I can change the text of room mention pill in message composer without breaking the functionality.
Even though I changed the title on event timeline as you can see, I'm unable to do the same in message composer. The functionality is breaking.

Thanks in advance.
![CPT2106291055-830x98](https://user-images.githubusercontent.com/55445693/123742145-d5fb3100-d8c8-11eb-8119-d5e79a20935b.gif)

**Comment by SimonBrandner** [comment]
Since this isn't a bug report nor a feature request, please ask for help in the [Element Web/Desktop](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org?via=envs.net&via=matrix.org&via=privacytools.io) room

**Comment by t3chguy** [comment]
No, the Matrix spec says that a room mention must be `@room` - this is what the server looks for

An at-room pill is sent as plaintext.

![image](https://user-images.githubusercontent.com/2403652/123754421-c53fc080-d8b2-11eb-96cc-68969ab2ffdc.png)

https://matrix.org/docs/spec/client_server/r0.6.1#m-rule-roomnotif
