### ISSUE TITLE
add `terms_and_conditions_links` to documentation

### ISSUE THREAD

**Issue by hex-m** [vector-im/element-web#17825]
The configuration option `terms_and_conditions_links` is missing from both, the [sample config](https://github.com/vector-im/element-web/blob/develop/config.sample.json) and the [documentation](https://github.com/vector-im/element-web/blob/develop/docs/config.md).

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/blob/develop/docs/config.md#administrative-options
