### ISSUE TITLE
Fix yarn start crashing when renaming a file

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#17827]

**Comment by Palid** [comment]
Will be fixed after we update to webpack 5, but we're waiting for https://github.com/pmmmwh/react-refresh-webpack-plugin to be webpack 5 compliant.

**Comment by t3chguy** [comment]
We no longer use that plugin

**Comment by t3chguy** [comment]
https://github.com/webpack/webpack/issues/9195 indeed fixed in Webpack 5 - closing in favour of https://github.com/vector-im/element-web/issues/24893
