### ISSUE TITLE
Collapse concurrent server ACL changes

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#17829]
#### Is your suggestion related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/1342360/123780781-76525500-d8cb-11eb-880b-bebb34d5b551.png)

After a recent spam wave, a number of room ACLs needed to be changed in rapid succession across a large number of rooms. This will likely be something that happens again in the future. Currently room ACL changes are not collapsed, and the timeline noise is quite disruptive.

#### Describe the solution you'd like.
Collapse ACL changes as we do for membership changes, etc. This could be collapsed based on the user that updated the ACLs, or separate ACL changes from multiple users could be collapsed together. Perhaps simply saying:

`The server ACLs for this room were changed X times.`

#### Describe alternatives you've considered.
This is only really noticeable during a large spam attack, so it's not really high priority. More of a nice-to-have.

However when it does happen it's quite attention-grabbing, and may prompt people to take a look at the banned servers in the ACL - which are often not very nice.

**Comment by SimonBrandner** [comment]
This should be already a thing on develop as of yesterday/today :P

**Comment by t3chguy** [comment]
Already done and merged this morning.

**Comment by anoadragon453** [comment]
Y'all work too fast - thanks :tada:
