### ISSUE TITLE
UISIs after restart

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17828]
This is almost certainly captured elsewhere, but:
- I went into the office for a day and didn't use my eleweb nightly on my desktop
- I came home and used it the next day
- I clicked update to update to the latest version
- It's 20 minutes later and a good chunk of my encrypted rooms are still full of UISIs

I suspect it'll sort itself out, but in the absence of any feedback or progress it feels pretty broken.

**Comment by lampholder** [comment]
After 30 minutes it had indeed sorted itself out.

**Comment by novocaine** [comment]
I don't think this is actionable without a rageshake
