### ISSUE TITLE
Too many extra spaces at the beginning of a room 

### ISSUE THREAD

**Issue by JohnRock0422** [vector-im/element-web#17822]
![extra_space](https://user-images.githubusercontent.com/26728661/123727359-1906d580-d8c4-11eb-8721-6bf93bc5d8bf.png)
![extra_space_1](https://user-images.githubusercontent.com/26728661/123727373-1dcb8980-d8c4-11eb-86d6-4d399dd28a4d.png)

### Description

There are too many extra spaces at the beginning of a room (I can even scroll up to see nearly a blank page).

### Steps to reproduce

- open a new room and don't send any message.

Describe how what happens differs from what you expected.

Logs being sent: no

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome

**Comment by turt2live** [comment]
I believe we would have fixed this by now. If not, please open a new issue with fresh information.
