### ISSUE TITLE
Develop: ReferenceError: can't access lexical declaration 'SpaceStore' before initialization

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#17836]
### Description

develop.element.io crashes with `ReferenceError: can't access lexical declaration 'SpaceStore' before initialization`

### Steps to reproduce

- I have no idea?
- Have spaces and open develop.element.io?

Describe how what happens differs from what you expected.

It should start up

Logs being sent: no (impossible)

![image](https://user-images.githubusercontent.com/1374914/123818296-28ecdc80-d8f9-11eb-9d72-5564626492fb.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 89.0.2
- **OS**: Windows
- **URL**: develop.element.io

**Comment by gsouquet** [comment]
This will now have been fixed on https://develop.element.io/ and the team is working on a long term fix for it. 

Thank you for the heads up!

**Comment by MTRNord** [comment]
> This will now have been fixed on https://develop.element.io/ and the team is working on a long term fix for it. 
> 
> Thank you for the heads up!

Thanks :) can confirm it works. Should I close the issue or should it be open for the long term fix?

**Comment by gsouquet** [comment]
I will open a PR soon that will auto-close this issue 👍
