### ISSUE TITLE
Enter should insert emoji and close autocomplete dialogue, not send the message

### ISSUE THREAD

**Issue by smithfred** [vector-im/element-web#17846]
Duplicate of https://github.com/vector-im/element-web/issues/4721, but I can't reopen that one.

This was supposedly closed by https://github.com/matrix-org/matrix-react-sdk/pull/2968, but I don't know if it actually was, I never saw the described change in behaviour.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/4872
