### ISSUE TITLE
Disable Community Bar for all users by default

### ISSUE THREAD

**Issue by leonfilser** [vector-im/element-web#17849]
#### Is your suggestion related to a problem? Please describe.
Is there a way to disable the community bar on the left by default? I know that users can disable it in settings but i want the default setting to hide the bar for every user unless they manually turn it back on.

#### Describe the solution you'd like.
An option inside the config file that allows to define default values for this (and maybe the other) setting(s).

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/blob/develop/docs/config.md `settingDefaults` `TagPanel.enableTagPanel`
