### ISSUE TITLE
Trying to post defangled URLs in Element somehow broke my message

### ISSUE THREAD

**Issue by alex-mayorga** [vector-im/element-web#17851]
![image](https://user-images.githubusercontent.com/649262/124062805-eb836e80-da20-11eb-905c-7db69a9bc0e5.png)

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Tried to send the following message into https://develop.element.io/#/room/#security:mozilla.org
`This might be mildly interesting for this room. I made a typo and ended up at http://web.whatsap[.]com/ which points to https://streamrecent-bestuberfile[.]best/kzbnt3TSk2ZQBu6uSDDb7_rKW0ny6A8FN4YzOVs5fq8`

Describe how what happens differs from what you expected.

The message was not sent and an error message was displayed:

`Can't load this message (m.room.message)Submit logs`

Log: sent/not sent? Will send, the in app log submission UI states "Before submitting logs, you must create a GitHub issue to describe your problem."   

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**:  Firefox Nightly 91.0a1 (2021-06-30) (64-bit)
- **OS**: Windows
- **URL**: https://develop.element.io/#/room/#security:mozilla.org

**Comment by t3chguy** [comment]
```
2021-07-01T04:08:19.159Z E URL constructor: http://web.whatsap[.]com/ is not a valid URL.
calculateUrlPreview/links<@webpack-internal:///1581:390:23
calculateUrlPreview@webpack-internal:///1581:389:42
_applyFormatting@webpack-internal:///1581:200:10
componentDidMount@webpack-internal:///1581:188:12
Yi@webpack-internal:///95:219:411
dk@webpack-internal:///95:259:160
exports.unstable_runWithPriority@webpack-internal:///100:18:343
gg@webpack-internal:///95:122:325
Uj@webpack-internal:///95:252:281
Lj@webpack-internal:///95:243:373
jg/<@webpack-internal:///95:123:115
exports.unstable_runWithPriority@webpack-internal:///100:18:343
gg@webpack-internal:///95:122:325
jg@webpack-internal:///95:123:63
ig@webpack-internal:///95:122:428
Jg@webpack-internal:///95:237:203
enqueueSetState@webpack-internal:///95:133:213
C.prototype.setState@webpack-internal:///97:12:369
onLoaded@webpack-internal:///887:929:12
```

needs a try-catch

**Comment by t3chguy** [comment]
Fixed on develop
