### ISSUE TITLE
Can't add alias to room

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17857]
When I try to add an alias to a room using element web, I get this error message:

![image](https://user-images.githubusercontent.com/5547783/124157135-bb77b200-da98-11eb-916b-80d05b494151.png)

Looking at the network logs, it looks like Element tries to hit `/_matrix/client/r0/rooms/[roomID]/state/m.room.canonical_alias/` before `/_matrix/client/r0/directory/room/[roomAlias]`. Hitting the latter manually with curl creates the association and allows setting the alias as the main address for the room afterwards.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/124159355-faa30480-da92-11eb-8ac6-79da5d98c649.png)

**Comment by t3chguy** [comment]
Confusing nature of this UX is tracked in https://github.com/vector-im/element-web/issues/13077
