### ISSUE TITLE
Notifications contain reply fallback from `body`

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#17859]
There exists user A and user B
User A and User B are logged into element on different machines

Steps-1) As User B send a reply of previous message to User A
As user A - Observe the notification received

Actual result-Matrix id of the user is displayed in the notification of reply

Expected result-Name of the user should be displayed instead of matrix id

![Screenshot (6)](https://user-images.githubusercontent.com/55445693/124255869-4499f200-db48-11eb-88e2-a75df8e4e488.png)

**Comment by t3chguy** [comment]
> Name of the user should be displayed instead of matrix id

This is unlikely to happen, the Notification is built on the `body` of the Matrix event being received, that body only contains the ID. This section should be stripped, it is a fallback only for legacy clients.

**Comment by Sr-Preet** [comment]
@t3chguy 
Okay, So what can we do to resolve this.
This is happening on the current element-web as well as my custom build.

**Comment by t3chguy** [comment]
Notifier needs to gain something akin to `stripReplyFallback` in HtmlUtils

**Comment by Sr-Preet** [comment]
@t3chguy 
Like bodyToHtml?

**Comment by t3chguy** [comment]
Yeah, might even be able to use that method

**Comment by Sr-Preet** [comment]
@t3chguy 
How about this one?
![Screenshot (34)](https://user-images.githubusercontent.com/55445693/124260256-1d91ef00-db4d-11eb-863b-9e7dd21c8fd3.png)
It's working too.

**Comment by Sr-Preet** [comment]
@t3chguy 
Can you take a look into this too?[#17860 ]

**Comment by t3chguy** [comment]
Open a pull request and it'll have to go through review.

**Comment by Sr-Preet** [comment]
@t3chguy Sure

**Comment by gabrc52** [comment]
This is especially annoying when a reply is long enough to take up the whole notification and you can't see the actual message from the notification

**Comment by gabrc52** [comment]
Thank you! Has this been fixed on mobile as well?
