### ISSUE TITLE
Electron i18n

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17855]
### Description

![image](https://user-images.githubusercontent.com/2803622/124122447-632fb880-da76-11eb-9f3e-a360cd1f7c32.png)

### Steps to reproduce

- Press Alt on Electron

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021070101-1

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/element-desktop/pull/223
