### ISSUE TITLE
You can drag spaces out of the space panel which looks broken

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17868]

**Comment by t3chguy** [comment]
Weirdly this does not happen on FF

**Comment by t3chguy** [comment]
react-beautiful-dnd sets a z-index of 5000 which works in FF but does not work in Chrome, heck even 50000 isn't working

**Comment by t3chguy** [comment]
Okay so whatever I try with z-index seems to be ignored in Chrome and Safari for when dragging.
Going to punt this one for now as its taking more time than I scheduled for such a seemingly simple thing.

**Comment by t3chguy** [comment]
Related to latter half of https://github.com/atlassian/react-beautiful-dnd/issues/370

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/124905390-e5236280-dfdd-11eb-9254-d3073e12762a.png)
![image](https://user-images.githubusercontent.com/2403652/124905425-ece30700-dfdd-11eb-9b42-5a9c87046984.png)

**Comment by SimonBrandner** [comment]
Right now you can't drag the space out of the left panel (space + room-list) which seems ok to me, so I am going to close this
