### ISSUE TITLE
blurhash needs a spinner or something to indicate it's a placeholder

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17878]
greying out the blur might help a bit too. atm it's very much 'uh, why has this person sent me a weird blurred image?!' as initial reaction

**Comment by ara4n** [comment]
could also do an dissolve transition from the blur to the real image to make it pop less, especially if the blur only appears for a few seconds.

**Comment by ShadowJonathan** [comment]
Re: spinner, I think taking inspiration from the way Twitter mobile loads images would be interesting, with displaying a bar alongside the top of the blurry image to indicate progress
