### ISSUE TITLE
Request for IRC Bridge to libera.chat doesn't show up for IRC op

### ISSUE THREAD

**Issue by benks-io** [vector-im/element-web#17876]
#### Description
When setting up a Bridge to libera chat. The selected op IRC user on the other side doesn't get a request to confirm.

#### Steps to reproduce
- Login to element
- Enter the room to be bridged in Element
- Open Room Info
- Add widgets, bridges & bots
- Bridges - IRC
- Select liberachat
- fill in `#roomname`
- select Op User from the dropdown list
- klick Request Integration

#### Describe how what happens differs from what you expected.

Klicking "Request Integration" should show up a message in the Libera.chat Room for the selected op. But it doesn't.
When the room name is entered in the form and the op's a polled, the user "matrixbridge1" logs into the room and immediately logs off again. 

#### Version information

1.7.31

- **Platform**: web (in-browser) or desktop?

- **Browser**: Firefox / Chrome

**Comment by t3chguy** [comment]
This is a support query for https://matrix.to/#/#irc:matrix.org rather than an Element Web issue. The bridge is maintained by Matrix.org - not part of Element Web
