### ISSUE TITLE
Support name aliases for spaces

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#17873]
Space IDs currently consist of the homeserver URL with a random string (i.e. `!KOdBeHhHDQPQNLgioI:hunterwittenborn.com`), but I would like to create a custom, user-friendly ID that I could more easily share (i.e. `!alias:hunterwittenborn.com`).

I can share the link that Element generates and everything, but being able to set a custom alias like I can do in rooms would just be nicer in general.

**Comment by SimonBrandner** [comment]
This is already possible on develop.element.io in space settings
