### ISSUE TITLE
Preserve fragments in link previews

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#17889]
When previewing links, we drop link fragments before sending to the homeserver for preview since they may contain private data and generally aren't meant to be sent to servers. However, the way we currently achieve this cause the fragment to be lost, so when we _display_ the `LinkPreviewWidget`, the fragment is not used, resulting in a different link than expected.

We should keep the fragment around client side and carry it through to the `LinkPreviewWidget`'s display of the link.

**Comment by t3chguy** [comment]
> since they may contain private data and generally aren't meant to be sent to servers. 

That isn't why we do it, we do it because if your message contains the same link with different fragments you end up with N identical looking previews

**Comment by bmarty** [comment]
I've created https://github.com/vector-im/element-android/issues/3640 for Android, but maybe it is not a privacy problem?

Element Android displays only one 1 UrlPreview, for the first link in the message, so we do not have the same problem of multiple identical previews.

But the Fragment part is very important, so removing it when rendering the UrlPreview is a big loss of information.

**Comment by jryans** [comment]
> That isn't why we do it, we do it because if your message contains the same link with different fragments you end up with N identical looking previews

Ah didn't realise it was a recent change... still seems a bit odd privacy wise that we used to send the fragment when normally even the link destination doesn't receive that info...

Privacy aside, if we're continuing to remove the fragment for previewing, we should still keep it around for display, as otherwise we're making it harder to reach the link as sent. People are likely to click the link in the preview vs. the message, since the preview one is a bit larger, so it should preserve all fidelity, e.g. the fragment.

**Comment by t3chguy** [comment]
Right but how do we handle the same link with two different anchors without regressing the aforementioned issue?

**Comment by bmarty** [comment]
Show a preview only for the first link :) as per Element Android. Multiple URL previews take too much space in the timeline IMHO. If the user wants to have a preview for each URL, they just have to send several messages.

**Comment by t3chguy** [comment]
There is another issue about that. But that mandates the ability to expand to all yet

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/5433
