### ISSUE TITLE
Collapsed room list looks/is broken

### ISSUE THREAD

**Issue by cbarrete** [vector-im/element-web#17881]
![image](https://user-images.githubusercontent.com/62146989/124476523-372c7400-dda3-11eb-9943-21e2e040bc01.png)

#### Description

As seen on the screenshot, the room list looks and is broken when collapsed :
- There is a weird bubble over the "start chat" icon which is not even aligned (and isn't present on the "add room" icon)
- The "list options" spawns too high and isn't selectable

#### Steps to reproduce

- Collapse the sidebar, hover over the "start chat" icon

#### Version information

- Element Web 1.7.30 (has been broken for a long time though), self-hosted
- Debian
- Mozilla Firefox 78.10.0esr

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17068
