### ISSUE TITLE
Localization setting is not saved for users.

### ISSUE THREAD

**Issue by Roman-S10** [vector-im/element-web#17882]
#### Steps to reproduce

1. Sign in to the element-web.
2. In the Settings (All settings -> General -> Language and region), select the language (for example Russian).
3. Sign out.
4. Refresh the page.

The Sign in form appears with different language (English).

Sign in to the element-web. UI appears with different language (English).
In the Settings you can see the selected different language (English).

#### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome, Opera.
- **OS**: Windows 10
- **URL**: app.element.io

**Comment by t3chguy** [comment]
The language is per-device, logging out wipes all device preferences for privacy reasons. It defaults to your browser language. You can also set a default in config.json.
