### ISSUE TITLE
Mumble integration (widgets / native)

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17898]
> Maybe a Mumble integration? 👍 I really would like to see something like that^^

_Originally posted by @pottah in https://github.com/vector-im/element-web/issues/3546#issuecomment-478336741_

---

Concurring to the above sentiment, i wanted to split this out into it's own issue that tracks something like this, with something along the lines of either;
- native integration of mumble
- integration of mumble as a VoIP "type"
- widget integration of mumble

**Comment by t3chguy** [comment]
> widget integration of mumble

this is already possible, people have claimed success using Mumble Web as a widget.

**Comment by ShadowJonathan** [comment]
Huh, alright then, i didn't know there was a mumble widget, the only problem i see then is ease-of-use and prominence of using that widget in an easy way (and get it out of the way for the user), but i'll see this issue closed then.
