### ISSUE TITLE
The options button in the image view seems to no longer work

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17892]
There is no error in the console 🤔

**Comment by dbkr** [comment]
argh, this has made it into the release too

**Comment by SimonBrandner** [comment]
Perhaps regressed by https://github.com/matrix-org/matrix-react-sdk/pull/5671?

**Comment by SimonBrandner** [comment]
Yeah, I think I know where the problem is. Will make a PR tomorrow
