### ISSUE TITLE
Element thinks I'm in light mode until I toggle the theme

### ISSUE THREAD

**Issue by Freeplayg** [vector-im/element-web#17894]
#### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

https://user-images.githubusercontent.com/40742947/124647165-9a7ddb00-de63-11eb-8fd6-a85989ab54c2.mp4

#### Steps to reproduce

Enable Dark Mode, logout, then log back in.

Logs being sent: no

#### Version information

- **Platform**: web

For the web app:

- **Browser**:  Firefox 89.0.2
- **OS**: Linux, Pop! OS
- **URL**:  stux.chat v.1.7.31

**Comment by kittykat** [comment]
@Freeplayg is this on develop.element.io or on app.element.io?

**Comment by Freeplayg** [comment]
This was a while ago, but it doesn't seem to happen anymore for me on app.element.io so I'll close the issue.
