### ISSUE TITLE
Showing a room with images in the timeline is very laggy

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17890]
![Peek 2021-07-06 16-21](https://user-images.githubusercontent.com/5547783/124626135-b347ba00-de7e-11eb-9e7d-b99f5422786a.gif)

On develop.element.io with Firefox 89.0.1

**Comment by robintown** [comment]
Probably blurhash related?

**Comment by SimonBrandner** [comment]
> Probably blurhash related?

/me was about to type that :D

**Comment by t3chguy** [comment]
@babolivier can you see if the event source has a blurhash field?

I'd imagine you'd see the blurhash flash in if it was blurhash related

**Comment by babolivier** [comment]
Yeah it does; in some occurrences when the room finally shows I can see a blurhash for a brief moment before the image appears
