### ISSUE TITLE
Can a room be changed to a direct messaging room in the UI?

### ISSUE THREAD

**Issue by ownaginatious** [vector-im/element-web#17899]
#### Description

I recently setup my own Matrix Synapse home server and added some bridge bots for connecting to iMessage and Facebook Messenger. That worked as expected, but when backfilling the data my home server started spitting out 429s (some bots erroneously do not honor 429s and slow down), which I'm guessing caused some requests telling the rooms to get changed into direct messaging rooms to be lost. The API documentation on how this happens is frustratingly vague.

The result is, some of my chats correctly appeared as direct messaging (i.e. under the "People" section), while others are incorrectly under "Rooms".

I was able to fix it by going to the settings of a random room > Advanced > Open Devtools > Send Account Data and sent an event to `m.direct` containing a list of rooms that should be direct messaging for my user. All my clients updated appropriately (i.e. the web browser, Android phone. etc).

So my question is, is there an easier way to do this? Like a toggle I can just set on the room? It's rather tedious to use the event route as it requires sending _every_ room ID that should be direct messaging.

Not including extra information for now as I don't think it's relevant.

**Comment by t3chguy** [comment]
There are /converttoroom and /converttodm commands only.

See https://github.com/vector-im/element-web/issues/16681#issuecomment-798904717

**Comment by ownaginatious** [comment]
Ah, perfect. Thanks for the incredibly fast response!
