### ISSUE TITLE
NanB notifications

### ISSUE THREAD

**Issue by K1D77A** [vector-im/element-web#17904]
![image](https://user-images.githubusercontent.com/10334164/124797392-194d4380-df4a-11eb-80b9-5676223cf693.png)

Hi I am using Element Web and I am getting the preceding as my notification count. I had 13 notifications from one room.

Linux 5.10.28-1 
Devuan

Firefox 78.10.0esr

Thanks.

**Comment by t3chguy** [comment]
I believe this was fixed
