### ISSUE TITLE
thumbnail filesize can be bigger than the original image

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#17906]
For example, https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$RZTZTqR8xROKD6i_cnuPgW-NVmHHiTRIwie2b3poUaI?via=matrix.org&via=vector.modular.im&via=dataport.modular.im has a file size of 17226 for the image, but the file size of the thumbnail is 22985, which seems silly and defeats the purpose of having a thumbnail.  We should detect if the generated thumbnail is bigger than the original image, and if so, we shouldn't upload the thumbnail, and should simply use the original image as the thumbnail instead

**Comment by lub** [comment]
Considering that the thumbnail quality is often also worse than the original image even with similar size, it would imo also make sense to only upload a 'proper' thumbnail after a certain threshold.

For example only upload the thumbnail if it is 10% or 1MB smaller than the original.

Under a certain size it maybe even makes sense to just not generate a thumbnail at all. I mean why have a thumbnail for a 17kb image? I don't know the resolution of the linked example, but a minimum resolution could maybe also be an additional consideration.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/128344596-681e702c-552f-41b7-b21f-11091eaf3538.png)


yeah this is happening all over the place

**Comment by t3chguy** [comment]
Anecdotally I've found that FF generates better thumbnails, for the OP where Chrome did 17226->22985 FF managed 17226->17564 ; but still, larger
