### ISSUE TITLE
TypeError when trying to generate verification QR code

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#17901]
I'm getting `TypeError: can't access dead object` in the console when trying to generate a verification QR code, and the code doesn't display (only a infinite spinner does). Observed on develop.element.io with Firefox 89.0.1. ~Will rageshake~ Done

**Comment by t3chguy** [comment]
Hmm, when researching that error, I can only find docs referencing addons

> The JavaScript exception "can't access dead object" occurs when Firefox disallows add-ons to keep strong references to DOM objects after their parent document has been destroyed to improve in memory usage and to prevent memory leaks.

**Comment by babolivier** [comment]
Oh, right, I'll tinker again with addons disabled

**Comment by babolivier** [comment]
Tried with someone else without even disabling addons and the QR code displayed fine :|

**Comment by Palid** [comment]
@babolivier is this still reproducible? Could've been some temporary memory access problems too.

**Comment by robintown** [comment]
Closing due to this not being reproduced since the original report
