### ISSUE TITLE
Pinned messages are sorted backwards compared to all other lists of messages

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#17903]
The pinned messages panel displays the newest message at the top, and the oldest at the bottom. This is counterintuitive since all other lists of messages (message panel, file panel, notification panel) display messages in the opposite order, though perhaps this was intentional?

**Comment by t3chguy** [comment]
@niquewoodhouse we did this intentionally, can you comment on the rationale?

**Comment by niquewoodhouse** [comment]
Of course, super happy to and will try to be brief :) Also, would love to hear other people's thoughts.  I personally didn't really consider other lists of messages in Element (probably should have but it's just in labs for now), so I completely understand the counterintuitive point.

**In a nutshell, trying to optimize for efficiency.** 

People tend to instinctively read a list, when it's presented to them as a "just so you know" list, from top to bottom.  If the top is the most pertinent thing it lets them read that first.  

As the pinner, if I've just pinned a message, I want people to see that quickly.  If I'm the viewer, seeing that first means I can digest the message quicker.  

If that latest is at the bottom of a list, my brain has to rapidly scan down look for the last avatar/name/entity, just making it harder to get that latest thing and digest the message.   Those small harder things add up over time to a less efficient experience.

People coming from other products/experiences are likely to expect the first thing in a "just so you know" list to be the latest, e.g (just a few examples)

- notifications in twiiter
- pinned messages in Slack, Discord
- files in Slack 
- email
- chats in Whatsapp
- missed calls on a phone
- news articles on a news app

**Comment by robintown** [comment]
Thanks for taking the time to explain, @niquewoodhouse. Those reasons make sense to me, so since this was an intentional design decision I'll go ahead and close this. (I mostly just made this issue in case it was an oversight, and didn't realize that many other applications display this kind of information in the same way)

**Comment by niquewoodhouse** [comment]
@robintown Thank you for raising this issue!  When this leaves labs, it would be good for Element to be consistent with how these lists work, at least to let users understand them quickly, either by making this the same as others or changing others to be like this one.

**Comment by ShadowJonathan** [comment]
fwiw a FIFO-like behaviour for pinned messages aligns with discord, where the latest pinned messages are shown first
