### ISSUE TITLE
ERROR in ./src/vector/init.tsx , Module not found: Error: Can't resolve '../component-index' in '/root/element-web/src/vector'

### ISSUE THREAD

**Issue by Jcicosn** [vector-im/element-web#17913]
#### Description

Trying to set up developer development. I have done the SDK installations. And when I start up I get this error.

Describe how what happens differs from what you expected.

Log: not sent   

![error](https://user-images.githubusercontent.com/53979758/124922831-8fad7c80-e002-11eb-8a14-aaf31e06caa4.png)

#### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome latest version 
- **OS**:Ubuntu server 18.04?
- **URL**: Private element server latest version

**Comment by SimonBrandner** [comment]
@Jcicosn, it would be better to visit the [dev room](https://matrix.to/#/#element-dev:matrix.org) for this kind of a thing

**Comment by Aifolin** [comment]
yarn reskindex
