### ISSUE TITLE
Channels feature request 

### ISSUE THREAD

**Issue by githuberyt** [vector-im/element-web#17915]
We need a way to use for announcements
 which is clean and elegant like telegram channels 

 Telegram Channels

Channels are a tool for broadcasting your public messages to large audiences. They offer a unique opportunity to reach people directly, sending a notification to their phones with each post.

Telegram Channels can have an unlimited amount of subscribers, and only admins have the right to post. Unlike Telegram Groups, channels show the name and photo of the channel next to messages – instead of the person who posted them. 

https://telegram.org/tour/channels

**Comment by t3chguy** [comment]
You can already create rooms which you configure such that only your chosen power (admins etc) can speak in them.

**Comment by githuberyt** [comment]
Yes but rooms is ugly compared to telegram channels there's dozens of accounts events and leave and join messages 
Telegram keeping it simple this way they have a recent actions section on channels which handle channel events and the content on the channels are clean to look or react to it 

I think if element implemented it will get more support among telegram users

**Comment by githuberyt** [comment]
this is a news channel on telegram 

![image](https://user-images.githubusercontent.com/79775707/124936987-301a9580-e031-11eb-9f28-a1c720e94717.png)

matrix room with room state events 

![image](https://user-images.githubusercontent.com/79775707/124937382-8ab3f180-e031-11eb-859b-6c38894a09fa.png)

**Comment by t3chguy** [comment]
In that case

Closing in favour of https://github.com/vector-im/element-web/issues/5186 + https://github.com/vector-im/element-web/issues/16832

**Comment by githuberyt** [comment]
so the suggestion is to introduce a new way for announcements clean for publishing like telegram channels without account events and i know that can be hide from the client side but is not activated by default so using a recent actions section to handle state events would be much better 

![image](https://user-images.githubusercontent.com/79775707/124937725-dc5c7c00-e031-11eb-9220-ded01b3753ad.png)

**Comment by robintown** [comment]
Related: #16902
