### ISSUE TITLE
memberinfo should reset when you change room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17910]
it's very confusing that if you open a memberinfo on someone and then switch room, the memberinfo hangs around - implying that they're in the new room, and giving you buttons like 'kick' and 'ban' which presumably apply to the room you were previously looking at rather than the one which you're now in.

**Comment by t3chguy** [comment]
> which presumably apply to the room you were previously looking at rather than the one which you're now in.

They look to apply to the currently viewed room
