### ISSUE TITLE
Unable to create a public room

### ISSUE THREAD

**Issue by rco3lho** [vector-im/element-web#17922]
<img width="563" alt="Captura de ecrã 2021-07-09, às 15 04 04" src="https://user-images.githubusercontent.com/87192549/125090263-1166de00-e0c7-11eb-8b3b-edbd0758a385.png">
<img width="770" alt="Captura de ecrã 2021-07-09, às 15 04 17" src="https://user-images.githubusercontent.com/87192549/125090291-19268280-e0c7-11eb-8102-c3ec43b5dacd.png">

#### Description

Unable to create a public room where guests without login can participate. Please let me know if I can provide more details.

**Comment by t3chguy** [comment]
That is an error from your server, I suggest checking your server logs.

**Comment by t3chguy** [comment]
Element Web cannot be used for guests to access rooms anyhow: https://github.com/vector-im/element-web/issues/13945#issuecomment-817601302

**Comment by rco3lho** [comment]
The server is chatcloud.net. Thank you guys for helping me out, I'm a mere user and I appriciate your help. I would like to have a room anywhere to add registred users but also guests.

**Comment by t3chguy** [comment]
If you send debug logs from Settings we may be able to see some detail, but unfortunately only `chatcloud.net` would know the full story of why their server wasn't able to create the room.

**Comment by rco3lho** [comment]
@t3chguy really grateful that you there for me. I believe I uploaded the logs

**Comment by t3chguy** [comment]
`2021-07-09T14:04:07.751Z E Failed to create room undefined M_UNKNOWN: Not allowed to create alias`

That server doesn't allow you to create aliases - this is a duplicate of https://github.com/vector-im/element-web/issues/17725 effectively

**Comment by rco3lho** [comment]
<img width="753" alt="Captura de ecrã 2021-07-09, às 15 18 32" src="https://user-images.githubusercontent.com/87192549/125092174-f8f7c300-e0c8-11eb-846a-0c875f6c2a7f.png">
