### ISSUE TITLE
[Feature] Wiping a room (not deleting)

### ISSUE THREAD

**Issue by MartinX3** [vector-im/element-web#17929]
#### Is your suggestion related to a problem? Please describe.
I can't wipe all messages from a room without deleting it.

#### Describe the solution you'd like.
Just clear/wipe/delete/remove all messages in a room.

#### Describe alternatives you've considered.
Using the deletion api and recreate the room maybe.
But all the users need to be readded...

#### Additional context
N/A

**Comment by SimonBrandner** [comment]
This would require spec changes. A better place to file this issue would be: https://github.com/matrix-org/matrix-doc/

**Comment by MartinX3** [comment]
Done https://github.com/matrix-org/matrix-doc/issues/3273 :)
