### ISSUE TITLE
Display name on autocomplete dropdown wraps over the item on the line below

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#17923]
<img width="543" alt="Screen Shot 2021-07-09 at 16 52 35" src="https://user-images.githubusercontent.com/769871/125097362-f51a6f80-e0cd-11eb-8ce7-b07f5ee00cf7.png">

**Comment by dbkr** [comment]
Should probably truncate the display name with an eliipsis at the end, but moving to x-needs-design to confirm.

**Comment by janogarcia** [comment]
@gsouquet What about using the same text truncation logic we defined for the Thread List?

https://github.com/matrix-org/matrix-react-sdk/pull/7549#issuecomment-1015225388

- The display name takes precedence. Display it as an inline block that takes up as much available space as necessary (i.e. do not set a max width for it that is less than 100% its parent container).
- The remaining space is filled by the Matrix User ID, which will be the first to get truncated if the available space becomes limited.

---

**Note**: There's a lot of stuff that we could improve visually for those pills (sizes, spacing, typesetting...), but I'm trying to focus just on this issue's scope.

**Comment by gsouquet** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21393
