### ISSUE TITLE
Fix contrast in new dark mode code block

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17939]
#### Is your suggestion related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/2803622/125176223-182e4780-e1d2-11eb-977c-15d958c778bc.png)
![image](https://user-images.githubusercontent.com/2803622/125176215-08aefe80-e1d2-11eb-8312-d9974273c6df.png)
Congrats on the snazzy looking new code block styling. In the above screenshots it looks pretty good!

Now look at this message:
![image](https://user-images.githubusercontent.com/2803622/125176275-84a94680-e1d2-11eb-9dc4-703338410268.png)
My eyes try to skip the code snippet as it is not only far from the text color but also darker than normal text (less fg-bg contrast) while the background is lighter than normal background (next to no contrast left).

#### Describe the solution you'd like.
Notice how in light mode, the non-coloured text has the same color as regular messages. In dark mode, the same parts in code are kind of faded. I'd like if they matched the normal message text color, or much closer to it, especially inline.

#### Describe alternatives you've considered.
🤔

#### Additional context
Screenshots taken on nightly 2021071001-1

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/125188074-de415d80-e232-11eb-9a24-ea8e1fb0e084.png)
I think this might as well be a T-Defect at this point

**Comment by HarHarLinks** [comment]
If this still happens, I don't consider this closed
![image](https://user-images.githubusercontent.com/2803622/125268786-56c61e00-e308-11eb-81bc-6d1905635546.png)

**Comment by SimonBrandner** [comment]
> If this still happens, I don't consider this resolved
> ![image](https://user-images.githubusercontent.com/2803622/125268786-56c61e00-e308-11eb-81bc-6d1905635546.png)

On it: https://github.com/matrix-org/matrix-react-sdk/pull/6355

**Comment by HarHarLinks** [comment]
this is better as of today's nightly, but now there is a horizontal scrollbar
![image](https://user-images.githubusercontent.com/2803622/126628741-faedf806-3940-4e0b-acd1-e42ccc23b2cb.png)


something something bubbles regression?

**Comment by SimonBrandner** [comment]
Fixed on develop.element.io
