### ISSUE TITLE
disambiguation in IRC layout only partially fixed

### ISSUE THREAD

**Issue by emorrp1** [vector-im/element-web#17930]
![image](https://user-images.githubusercontent.com/71895/125163652-03c45d80-e186-11eb-947a-ef32209d29db.png)

#### Description

#17648 was mostly fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6193 but when the ambiguous user is yourself, the username is now blank until you hover over it, then the mxid overlaps text again.

#### Steps to reproduce

- Switch to IRC layout
- Create similar displaynames and hover over a message.

Expect to see a reasonable representation of the user

### Version information

- **Platform**: desktop ([flatpak](https://flathub.org/apps/details/im.riot.Riot))

For the desktop app:

- **OS**: Debian 10
- **Version**: 1.7.32

**Comment by SimonBrandner** [comment]
This is one of the IRC layout regressions caused by https://github.com/matrix-org/matrix-react-sdk/pull/5880 and by one more PR whose name I don't remember. 

Will try to figure out what to do next with this

**Comment by SimonBrandner** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7652#event-5986701221
