### ISSUE TITLE
Latest native version 1.7.32 unable to build native because it doesn't find rustup

### ISSUE THREAD

**Issue by Polve** [vector-im/element-web#17932]
If I try to compile native binary as usual with "yarn run build:native" I now get this error:
```
$ yarn run hak
$ node scripts/hak/index.js
hak check: matrix-seshat
Can't find rustup
```
This used to work fine until 1.7.30, and I have rustup in my path.
Using ubuntu hirsute

**Comment by t3chguy** [comment]
rustup has been removed on develop and won't be needed for the next version

https://github.com/vector-im/element-desktop/commit/5bbce91e5163f1c697857f2faa66c70abb020b29#diff-9bc19d7502df80c8e478aced30bf985edf35b4f392ba43eef7bcee256623ea60
