### ISSUE TITLE
Fail to build on Node JS v16.4.2

### ISSUE THREAD

**Issue by D4v1dH03** [vector-im/element-web#17941]
#### Description

Error building native modules on Node JS v16.4.2 

#### Steps to reproduce

- Install NodeJS for Windows
-  Try to build following the build instructions
- Fail to build native modules with `yarn build:native`

Describe how what happens differs from what you expected.

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/81270448/125182279-946c5f00-e1c1-11eb-81b0-fb7b3fe627d6.png)

#### Version information

- **Platform**: web (in-browser) or desktop?
Desktop
For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows
- **Version**: 1.x.y 
`master`

**Comment by turt2live** [comment]
Looks like you're missing `tclsh` from your system as a seshat build dependency. 

Visit #element-dev:matrix.org for further support on this.
