### ISSUE TITLE
getting an error when trying to pin

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#17955]
### Description
getting an error when trying to pin
![image](https://user-images.githubusercontent.com/31655082/125282452-b24bd800-e317-11eb-8224-c67e68069edb.png)

```
react-dom.production.min.js:101 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at MessageContextMenu.js:181
    at Object.ze (react-dom.production.min.js:52)
    at Ke (react-dom.production.min.js:52)
    at react-dom.production.min.js:53
    at Tr (react-dom.production.min.js:100)
    at wr (react-dom.production.min.js:101)
    at react-dom.production.min.js:113
    at Me (react-dom.production.min.js:292)
    at react-dom.production.min.js:50
    at Or (react-dom.production.min.js:105)
```

### Steps to reproduce

- not sure

Logs being sent: yes

[logs-0002.log.gz](https://github.com/vector-im/element-web/files/6801070/logs-0002.log.gz)
[logs-0003.log.gz](https://github.com/vector-im/element-web/files/6801071/logs-0003.log.gz)
[logs-0004.log.gz](https://github.com/vector-im/element-web/files/6801072/logs-0004.log.gz)
[logs-0005.log.gz](https://github.com/vector-im/element-web/files/6801073/logs-0005.log.gz)
[logs-0000.log.gz](https://github.com/vector-im/element-web/files/6801074/logs-0000.log.gz)
[logs-0001.log.gz](https://github.com/vector-im/element-web/files/6801075/logs-0001.log.gz)

### Version information

- **Platform**: web (in-browser-pwa)
- **Browser**: Chrome - the newest version: Version 91.0.4472.77 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: internal

**Comment by robintown** [comment]
This looks like the bug that was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6336. @chagai95 can you try develop or nightly and verify whether this resolves your error?

**Comment by t3chguy** [comment]
Assuming fixed on latest develop, you didn't provide a version in your issue (please fill the issue template next time)

Shout if you can repro on latest develop.

**Comment by chagai95** [comment]
I am could not reproduce reliably so I can not test this properly but I can keep a look out, the version is develop branch but I was not on latest...
