### ISSUE TITLE
"Remove recent messages" feature removes avatars/display names

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#17957]
Very similar to https://github.com/vector-im/element-web/issues/17445 but I wanted to keep it a little bit separate (there's talk on that thread of removing _State Events_, but I think all we actually do is remove Avatars/Display Names).

Removing avatars/display names is certainly surprising to users in some case (a customer raised the disappearance of the avatar/display name as a bug). I understand that in some cases it might be desirable when tackling abuse (though in some cases the display name may be _less_ offensive than the mxid.

Similar to the PR in https://github.com/matrix-org/matrix-react-sdk/pull/6114, it would be nice to prompt admin users to ask if they also want avatars/display names to be removed, perhaps leaving them intact by default?

**Comment by robintown** [comment]
Hm, I'm trying to envision this… in what kinds of situations would you want to redact state events in general, but not `m.room.member` data? My hope with https://github.com/matrix-org/matrix-react-sdk/pull/6114 was that one checkbox would be enough granularity.

**Comment by robintown** [comment]
Closing due to lack of info
