### ISSUE TITLE
Ignore emoji shortcode auto completion (enter/space) if it’s one character

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#17958]
This prevents emojis like `:P` or `:D` from getting "corrected"

**Comment by deepbluev7** [comment]
Alternatively, one could just not select any completion by default, so that the user needs to press "up" once or similar to select a completion.

**Comment by t3chguy** [comment]
> For me Element seems to be doing that already

Yes, it is.

The only time a short is completed is when you have the option enabled.

![image](https://user-images.githubusercontent.com/2403652/125303388-ac102880-e324-11eb-99f1-f9946798ca79.png)

@ShadowJonathan this is the whole point of this setting, not sure what your request is
