### ISSUE TITLE
changes in pins are only shown when witnessed live

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#17953]
#### Description

These messages
![image](https://user-images.githubusercontent.com/2803622/125176043-b3beb880-e1d0-11eb-82f4-d0130a5c76e3.png)
only appear in the timeline (even with hidden events on) when the client witnesses the change. The same client loading the same timeline after a restart does not know about them.

#### Steps to reproduce

- pin some stuff
- restart element

Obviously the timeline should be consistent

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021071101-1

**Comment by SimonBrandner** [comment]
I don't think I can repro

**Comment by t3chguy** [comment]
Yeah I can't imagine how this'd happen as it'd be a signal of very major sync/timeline issues given it is just a plain old state event

**Comment by HarHarLinks** [comment]
Yeah I uhh... sorry. *facepalm*
Time moves fast...
