### ISSUE TITLE
Stuck messages in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#17966]
Over the last few weeks i've had ~4 instances where a sent message gets stuck at the bottom of the timeline because we didn't successfully receive an echo down /sync.  I rageshaked; @richvdh took a look with jaeger and says there may be two competing /sync requests which tried to receive the message, and so it may have fallen between the cracks.  As far as I know, eleweb should never be running overlapping sync loops - so it sounds like something is going worryingly wrong here.

**Comment by ara4n** [comment]
this is also https://github.com/matrix-org/synapse/issues/9424#issuecomment-878295236

**Comment by turt2live** [comment]
I'm slightly worried this is a synapse-side threading issue btw. Mjolnir and such are seeing duplicate events down `/sync`, which sounds like some sort of corrupted aggregated state.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17471

**Comment by ara4n** [comment]
I don't think this is a precise dup of the #17471, given @richvdh's investigation with jaeger showed two possible /sync reqs from eleweb which would have caught the event.  Whereas #17471 says...

> This is a bug when the server never remote-echoes the event back down /sync

which is not the case here.

**Comment by richvdh** [comment]
My money is currently on synapse not returning the event in *either* sync request, to be clear.

**Comment by dbkr** [comment]
I just got this again and it's worse now because the new 'sent' tick is just on the latest message, so i you send another message afterwards, the latter one can get through but then the two messages just look like they've been re-ordered, and the 'sent' tick is on the one that actually didn't send at all!

<img width="722" alt="Screenshot 2021-08-19 at 11 08 24" src="https://user-images.githubusercontent.com/986903/130052020-84dc589a-0510-4927-b333-9e5519748b69.png">

**Comment by nrdxp** [comment]
Is anyone aware of how to workaround or resolve this. It's quite annoying :sweat:

**Comment by JokerGermany** [comment]
Have the problem, too and it's really really anoying
https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$aX_HOZknt_1BUOI1WqtHpXQEcLVFahKsISxUEOyz0fc?via=matrix.org&via=libera.chat&via=tchncs.de

**Comment by novocaine** [comment]
@ara4n thinks this is an [E2EE client bug](https://github.com/matrix-org/synapse/issues/9424#issuecomment-942472597) ..

**Comment by Palid** [comment]
This issue also exists in the Android version of the app. @kittykat are you aware of it?

**Comment by Palid** [comment]
If I remember correctly it usually happened whenever I had some backlog to sync and I sent the message and closed the app/changed room focus (either or) before backlog did properly sync, which left me with this hanging message.

**Comment by BillCarsonFr** [comment]
New occurence on web for me https://github.com/matrix-org/element-web-rageshakes/issues/10049
