### ISSUE TITLE
Fail to build native modules on Windows even if all build dependencies are satisfied

### ISSUE THREAD

**Issue by D4v1dH03** [vector-im/element-web#17968]
#### Description

`yarn run build:native` fails with NMAKE fatal error U1077 with all build dependencies satisfied

#### Steps to reproduce

- Run `yarn build:native`
- NMAKE produces fatal error U1077

Describe how what happens differs from what you expected.

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/81270448/125356184-63249800-e355-11eb-8ca1-6168fe21f0a5.png)

#### Version information

- **Platform**: web (in-browser) or **desktop**?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: **Windows**, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment]
The issue tracker is not a support section. Please visit #element-dev:matrix.org for support on the build pipeline.
