### ISSUE TITLE
Explore Rooms window closes unexpectedly if one clears the text search

### ISSUE THREAD

**Issue by maxkratz** [vector-im/element-web#17964]
#### Description

*Explore Rooms* window closes unexpectedly if one clears the text search bar.

#### Steps to reproduce

- Click on *Explore Rooms*.
- Clear the search bar (*Find a room...*) with the red *x*.
- Try to switch the matrix server (just click on the name) -> The *Explore Rooms* window closes.

(Please refer to the attached screenshots.)

#### Describe how what happens differs from what you expected.

I'd expect the popup window to not close, i.e., the clearing of the search bar should not affect the whole window.

Logs being sent: No

![Screenshot_2021-07-12_20-49-34](https://user-images.githubusercontent.com/20956405/125340750-23f54780-e353-11eb-9aef-b2c9b07f4ee8.png)
![Screenshot_2021-07-12_20-49-54](https://user-images.githubusercontent.com/20956405/125340756-25267480-e353-11eb-84df-62a098ad8049.png)
![Screenshot_2021-07-12_20-50-17](https://user-images.githubusercontent.com/20956405/125340765-26f03800-e353-11eb-910d-e87f7b634b24.png)

#### Version information

- **Platform**: Web **and** desktop app

For the web app:

- **Browser**: Chromium Version 91.0.4472.114
- **OS**: Linux Mint 20.1 x86_64
- **URL**: https://app.element.io

For the desktop app:

- **OS**: Linux Mint 20.1 x86_64
- **Version**: Element version: 1.7.32, olm version: 3.2.3

**Comment by t3chguy** [comment]
Fixed on develop
