### ISSUE TITLE
Link invitation to rooms/spaces does not work correctly

### ISSUE THREAD

**Issue by AntonDashevsky** [vector-im/element-web#17974]
![image](https://user-images.githubusercontent.com/5083772/125422923-1bfec5a9-b4aa-467a-8f60-b03d493f012f.png)
![image](https://user-images.githubusercontent.com/5083772/125455054-45a2faab-ca03-4bf2-a741-2d77e3d3d984.png)

#### Description

Can't enter the room \ space by permalink. The page opens, but the spinner spins endlessly. The problem is identical on the local machine and dev / prod servers. There are no errors in the logs

#### Steps to reproduce

- User # 1 invites user # 2 to room \ space by permalink
- User # 2 opens the link and watches the spinner without additional information on ui

Platform: web
Release: 1.7.32

What could we have missed to make invitations work correctly?

**Comment by kittykat** [comment]
When I try to join a space using [this link](https://matrix.to/#/#element-translators:matrix.org):
![Screenshot from 2021-08-24 10-44-30](https://user-images.githubusercontent.com/51663/130596994-c140b455-acd2-4569-aa7d-ffe69794af92.png)


- If I am in Beta, then the room I was looking at last opens and I am not added to the space
- If I have Beta off, I see this:
  ![Screenshot from 2021-08-24 10-44-59](https://user-images.githubusercontent.com/51663/130596984-7746cb9c-fa79-42ff-b706-5b251f1cafb9.png)
  And when I switch Beta on, I get taken to the last room that I had open and do not join the space

**Comment by novocaine** [comment]
> When I try to join a space using [this link](https://matrix.to/#/#element-translators:matrix.org):
> ![Screenshot from 2021-08-24 10-44-30](https://user-images.githubusercontent.com/51663/130596994-c140b455-acd2-4569-aa7d-ffe69794af92.png)
> 
> * If I am in Beta, then the room I was looking at last opens and I am not added to the space
> 
>  join-space.mp4 
> * If I have Beta off, I see this:
>   ![Screenshot from 2021-08-24 10-44-59](https://user-images.githubusercontent.com/51663/130596984-7746cb9c-fa79-42ff-b706-5b251f1cafb9.png)
>   And when I switch Beta on, I get taken to the last room that I had open and do not join the space
> 
> Clearing cache did not fix the issue. The same link worked when I opened it from inside Element rather than an external page.

@kittykat - how did you generate that matrix.to link?

**Comment by kittykat** [comment]
@novocaine Find a room in the left panel, then click on the hamburger menu and select "Copy Room Link":

![Screenshot from 2021-09-01 18-01-10](https://user-images.githubusercontent.com/51663/131713154-cd2b9f83-dbe3-4def-84e5-b1868b179ecf.png)

**Comment by novocaine** [comment]
> @novocaine Find a room in the left panel, then click on the hamburger menu and select "Copy Room Link":
> 
> ![Screenshot from 2021-09-01 18-01-10](https://user-images.githubusercontent.com/51663/131713154-cd2b9f83-dbe3-4def-84e5-b1868b179ecf.png)

Hrm, but in your comment you noted it's for a space?

**Comment by kittykat** [comment]
Ah, for spaces it's left panel -> right click on space -> Invite People

![Screenshot from 2021-09-01 20-24-27](https://user-images.githubusercontent.com/51663/131731966-fa366fc5-a8dd-4571-9cc9-3af795006058.png)

**Comment by novocaine** [comment]
that generates a link in a different format - does that produce the same behaviour?
