### ISSUE TITLE
Video Call doesn't hang up when camera is not available

### ISSUE THREAD

**Issue by b0ngi** [vector-im/element-web#17975]
#### Description

When receiving a video call on a PC without webcam the call ends on the receiving side with "Unable to access webcam / microphone" (throwing an "Uncaught (in promise) DOMException") and continues on the calling side. 

#### Steps to reproduce

- create DM with user who has no webcam
- start video call
- Receiver: Accept call
- Receiver: Error message is displayed
- Caller: Video call is still active an ringing

I would expect the video call at least to stop on both sides (calling and receiving). Ideally, the call would start without video feed if no webcam is found.
  

Logs being sent: yes

![tempsnip](https://user-images.githubusercontent.com/87361719/125424197-7d65be96-03ae-48ca-acf3-d064d4ea3355.png)

#### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 91.0.4472.124, Firefox 89.0.2
- **OS**: Window, Android, Arch Linux, Ubuntu
- **URL**: connect.assigndmb.com (private server), Element version 1.7.32

**Comment by SimonBrandner** [comment]
This is debatable since you might want to give other devices a chance to answer the call/give the user a chance to connect their microphone instead of hanging up the call

**Comment by b0ngi** [comment]
Yes, I fully agree.

I think either both sides should terminate the call or both sides should engage in the call.
Right now if someone calls me I cannot even call back with a voice call immediately, since a call is currently placed 😅.

I would really appreciate if you are able to fix this issue. I'm currently trying to find my way through the matrix-react-sdk but I'm not really familiar with react and typescript.

Thanks

**Comment by SimonBrandner** [comment]
With trying to follow what I wrote in https://github.com/vector-im/element-web/issues/17975#issuecomment-878953700 would it make sense to you to let the call keep ringing if Element fails to access the camera/mic...?

**Comment by b0ngi** [comment]
Yes, that seems like a good solution. Then the receiver would have the change to plugin the device or decline the call which would also end the call on the callers side.

**Comment by SimonBrandner** [comment]
Partially related to https://github.com/vector-im/element-web/issues/12646

**Comment by SimonBrandner** [comment]
> I would still want the ability to connect a camera before accepting the call. If I've disconnected my camera and all I have to do is plug it in and then accept the call, it feels odd to force me to accept the call first. Equally, if we don't yet have call upgrades, then at least offering people the option to connect a camera and accept as a voice call seems to give them more choices.

You have that already, it's just that if you try to accept the call hangs up (though you can still answer elsewhere). I wasn't arguing for removing that. I am just saying if you try to answer a call without a camera it makes sense to make it a voice call from your side

**Comment by SimonBrandner** [comment]
> Ah sorry, I see what you mean - I misunderstood the point at which the error message is displayed.
Yes, I agree that the simplest approach in that case is that if they click accept without a camera attached it simply becomes a voice call from their side.

No worries and great! I am quite busy atm but hopefully, I should have time to do this over the weekend, should I or do you want to discuss this further with other designers before I start working on it?
