### ISSUE TITLE
Invites don't light up the home space

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#17988]
I received a DM invite and it did initially light up the home space but after I read it, home wasn't highlighted anymore but the invite still has the red badge. This feels quite inconsistent. I think the home space should stay highlighted until I act on that invite the same way the invite does

**Comment by SimonBrandner** [comment]
Alright, there is a chance that the home spaces wasn't highlighted since the person was is a part of the Matrix Community space

**Comment by ShadowJonathan** [comment]
Personally I'd say that I would appreciate it if invites don't constantly remind me, as I possibly would want to wait before accepting. But that's a personal preference, I think if invites are to be handled similarly to message notifications, it'd need a bit wider existing support for it (in the form of "muting" and "unmuting" particular invites, and such)

**Comment by SimonBrandner** [comment]
I am not able to repro this, closing
