### ISSUE TITLE
Spaces panel expand and collapse interaction

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#17993]
We've seen in research that the expand/collapse interaction for the spaces panel is annoying and hard to use for most people.

We also know from research that subspaces might not live in this area or that we even require an expandable panel, so we should be reluctant to spend much effort on this interaction.

Adding some quick gif ideas:
1
![expand-interaction-01](https://user-images.githubusercontent.com/1587166/125774717-71331a3f-a61c-45f6-b288-18ca1b574822.gif)

2
![expand-interaction-02](https://user-images.githubusercontent.com/1587166/125779695-7b0ba220-949b-4b25-a851-8c743511d233.gif)

3
![expand-interaction-03](https://user-images.githubusercontent.com/1587166/125774728-b3c8a97a-0879-4d8a-87c0-6e70db498f6c.gif)

4
![expand-interaction-04](https://user-images.githubusercontent.com/1587166/125777448-3175086d-4c14-4a94-bd3f-8264d6282f1a.gif)

**Comment by ShadowJonathan** [comment]
Related: https://github.com/vector-im/element-web/issues/17604

**Comment by t3chguy** [comment]
@niquewoodhouse what is the task wanted from the web team based on this issue?

**Comment by t3chguy** [comment]
If we want any animation we will first need to implement a resizer for the space panel otherwise the width is automatic and thus not animatable

**Comment by t3chguy** [comment]
@niquewoodhouse / @nadonomy where does this slot into our new Milestones sheet?

**Comment by ShadowJonathan** [comment]
@niquewoodhouse i just saw the updated GIFs, a personal favourite would be 4 with a less "thick-lined" collapse icon. But i quite like the ideas set forth for now.

**Comment by nadonomy** [comment]
@niquewoodhouse thanks for exploring!

On 1:

- Love love love the smooth motion between the states
- I don't have much affordance from the small button stylised as a circle. Is the design more intuitive if we use a larger, square, button which pops out over the right of the space panel? 
- The interaction overall looks like it might have legs

On 2:

- Building on my middle point on 1, this is more what I was thinking! Idea: Try stylising as the same size and radius as the explore rooms button, placing it to the right of the space panel (obscuring space name etc), using the same background as the space panel.
- I like the idea of the space panel rounding as it helps develop the hierarchy of the space panel being a background, and the other panels layered on top. Does a softer radius feel more visually cohesive?

On 3:

- I like the discoverability of hamburger
- I'm unsure how I feel about printing the Element logotype. I think it's good to build more equity, but on the pure subjective spark joy level a part of me wonders if it's a bit tacky? It reminds me of when you get crappy stickers on new physical products. Need to think more on this, totally not resolute on my opinion. 
- Really love the icon changing on hover to hint at interaction. The specific iconography reminds me of a trident, or type setting, though. Wondering how else we could stylise.

On 4:

- The alpha transition feels really primitve compared to how polished the other motion comps do (you did this to yourself!)
- Logomark only feels like a way more tasteful way to re-enforce brand equity.
- Find the icon stroke too heavy (colour, weight), I wonder if this might feel better overall with iconography closer to 3?

Overall, some really nice direction(s)!

**Comment by niquewoodhouse** [comment]
@nadonomy thanks for reviewing, following your notes I iterated the different options:

1:
- Amended button design to be more like others

https://user-images.githubusercontent.com/1587166/130578635-2bde38e4-4502-4cc0-9617-15dfcdd513ba.mp4


2:
- Amended button design
- Softer radius on expanded panel

https://user-images.githubusercontent.com/1587166/130578656-c81c3243-4a23-4826-acce-c7a655c0b40a.mp4


4: 
- Amended alpha transition
- Amend icon 


https://user-images.githubusercontent.com/1587166/130579519-7dd1dde8-85d6-4d81-b41c-c60223862342.mp4

**Comment by t3chguy** [comment]
Proposals 3&4 are incompatible with IA1.1
