### ISSUE TITLE
Feature flags can be costly when read zillions of times

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#18004]
Some feature flags (such as the one for Spaces) are checked in hot code paths, such as `isRoomVisible`. Every time we check a feature flag, we read it from `localStorage`. 😱 

We should probably cache those feature flags in memory instead.

**Comment by robintown** [comment]
I don't know the full reasons why toggling the spaces beta requires the client to restart, but perhaps putting settings watchers on `feature_spaces` would have the added benefit of allowing you to toggle it without a restart?

**Comment by t3chguy** [comment]
> I don't know the full reasons why toggling the spaces beta requires the client to restart, but perhaps putting settings watchers on `feature_spaces` would have the added benefit of allowing you to toggle it without a restart?

The space store isn't running with the flag off so it'll have missed many events and it's easier maintaining the assumption that it'll be given all events it needs and not miss any.

Also so the groups store isn't holding onto things
And you'd have to listen to not only feature_spaces but also the settings for communities, custom tags and communities V2 as all those get disabled when you enable spaces

**Comment by turt2live** [comment]
also the RoomListStore and friends need to be told to recalculate the world, which can be expensive. By the time that you've updated all the stores, the client will have locked up enough where a restart/refresh is *less* disruptive.

**Comment by t3chguy** [comment]
But for the Spaces beta specifically we can lean into that and read it once and know it won't change in this lifetime - I will do so

**Comment by robintown** [comment]
Ah, then nevermind

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8366
