### ISSUE TITLE
Widgets can't be added in rooms

### ISSUE THREAD

**Issue by Roman-S10** [vector-im/element-web#18000]
![grafana](https://user-images.githubusercontent.com/17530517/125671472-e7ee8e45-185e-4012-bf57-f071057e50d1.png)
### Steps to reproduce:

1. In room "Room info".
2. Add widget (for example Grafana) by clicking "Add widgets, bridges & bots" on right panel.
3. Add Grafana URL and Title in Grafana widget settings, click "Save" button.
4. On right panelin from Widgets list choose on Grafana widget.

Result: "Sorry, this content is not embeddable in Matrix X-Frame-Options: DENY".

### Version information

- Platform: web (in-browser)

- Browser: Chrome, Opera.

- OS: Windows 10

- URL: app.element.io

**Comment by t3chguy** [comment]
`X-Frame-Options: DENY` is the header your resource is sending.
This forbids Web Browsers from embedding it, you must fix this on the Grafana instance you're using.

**Comment by Roman-S10** [comment]
How can I fix this on the Grafana instance? From Grafana widget I can get link only (f.e. https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=1626335492080&to=1626339092080&viewPanel=7)

**Comment by t3chguy** [comment]
play.grafana.org don't allow their instance to be iframed.

They have the embed feature disabled

https://grafana.com/docs/grafana/latest/sharing/share-panel/#embed-panel
![image](https://user-images.githubusercontent.com/2403652/125790267-57fd6ed1-3265-4182-b457-bdf44301e98d.png)

**Comment by Roman-S10** [comment]
Does it mean that Grafana widget completely useless for element-web?

**Comment by t3chguy** [comment]
Only if you're using play.grafana.com or another Grafana instance with embedding disabled.

**Comment by turt2live** [comment]
Closing as we will not be able to fix this.
