### ISSUE TITLE
Mention automatic composer focus in keyboard shortcuts screen

### ISSUE THREAD

**Issue by c7hm4r** [vector-im/element-web#18016]
#### Is your suggestion related to a problem? Please describe.
I never knew that inserting any (unhandled) letter key when the composer is unfocussed would focus the composer. [That](https://github.com/vector-im/element-web/issues/5775#issuecomment-613354924) is where I learned it.

#### Describe the solution you'd like.
In the keyboard shortcuts screen (`Ctrl` + `/`) please inform about that behavior.

#### Describe alternatives you've considered.
… I was about to create an unnecessary issue to suggest a shortcut for focussing the composer.

**Comment by gsouquet** [comment]
I don't think that the behaviour you're describing is a keyboard shortcut.
It will simply auto focus the composer as you start typing a message. I don't really believe that this is something that needs to be documented there. 

For that reason I will be closing this issue
