### ISSUE TITLE
Sticker placeholders not centered anymore

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18014]
#### Description

![image](https://user-images.githubusercontent.com/2803622/125917281-f1b4846b-8072-4fe7-b530-70ea669d15a6.png)
I believe those were once centered as to give a better hint how much of a place they're holding. perhaps the area should be highlighted anyway.

#### Steps to reproduce

- circumstances in which stickers load extremely slowly

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch
- **Version**: aur/element-desktop-nightly-bin 2021071501-1

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/128643849-ac937922-a113-4fde-a43f-161d81fe7101.png)

@SimonBrandner please re-open?

Element Nightly version: 2021080801
Olm version: 3.2.3

**Comment by SimonBrandner** [comment]
@HarHarLinks, you should be able to do that yourself :)

**Comment by HarHarLinks** [comment]
This appears to be back to the way I originally reported (top left).

btw i looked this up:

> you should be able to do that yourself :)

- you can re-open your own issues if you closed them yourself
- you cannot close or re-open issues opened by someone else
- you cannot re-open your own issues if a repo collaborator closed them
