### ISSUE TITLE
Allow space admins to lock the order of rooms in the sidebar

### ISSUE THREAD

**Issue by ducheng0** [vector-im/element-web#18012]
#### Is your suggestion related to a problem? Please describe.
Onboarding new users to a Space is difficult when the rooms are ordered by either A-Z or Activity, and they want to see suggested rooms first, such as rules or the main chat room.

#### Describe the solution you'd like.
Allow the admins of a space to lock the order of the rooms in the sidebar and explore page, so that for example, the About, Rules, and General chats can be forced to the top, similar to how they are organized on Discord.

#### Describe alternatives you've considered.
Allowing users to change the room list, but having it set as a "Suggested" order by default to help with onboarding of newbies.

**Comment by h4x3rotab** [comment]
Maybe dup of #18012

**Comment by SimonBrandner** [comment]
> Maybe dup of #18012

That is this issue

**Comment by h4x3rotab** [comment]
> > Maybe dup of #18012
> 
> That is this issue

fixed :D

**Comment by SimonBrandner** [comment]
Ok, yes, seems like a dupe, thanks!
