### ISSUE TITLE
When I  has a message send failed ,I will can't send success again

### ISSUE THREAD

**Issue by Modificator** [vector-im/element-web#18015]
#### Description

When I  has a message send failed ,I will can't send new message success again
if `Delete All` or `Retry All` can be fix it
![image](https://user-images.githubusercontent.com/3425930/125919598-974cd8fe-771f-4c29-9549-0be034a34a19.png)

#### Steps to reproduce

1. disable all network
1. send some message to any room
1. wait show send failed
1. restore network
1. send message to same room

#### Version information

- **Platform**:  desktop
- **OS**: macOS
- **Version**: 1.7.32

**Comment by robintown** [comment]
I think this behavior might be intentional, to prevent messages from being sent out of order

**Comment by t3chguy** [comment]
it is, at least as far as the code is concerned
