### ISSUE TITLE
indicate replied-to messages are clickable in new reply UI

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18027]
#### Is your suggestion related to a problem? Please describe.
matrix-org/matrix-react-sdk#3553 has landed in the nightly. Looks real nice.
It is however missing some indication that the replied-to message is clickable. Would be nice, at least on hover.

Yes the cursor changes to 👆️ but it is not clear what that means since nothing clickable is highlighted.

#### Describe the solution you'd like.
Background color offset

**Comment by ShadowJonathan** [comment]
FWIW discord brightens the selected "clickable text" a bit when you hover over it.

**Comment by SimonBrandner** [comment]
I am not sure if we can easily achieve this. The reason this works for Discord is that their replies are grayish by default. So they can set the color to `#fff` on hover. But our replies are that by default, so I don't really know how to make them brighter. Ideas are welcome :)

**Comment by SimonBrandner** [comment]
@niquewoodhouse, do you have any thoughts on this? (thanks for the previous reply designs, btw)

**Comment by HarHarLinks** [comment]
High(or low)light the background instead? Seems to be the obvious choice, since you can click the area and not just the text

**Comment by ShadowJonathan** [comment]
Yeah making the background light up a little while you hover the cursor over it seems like the obvious choice.

**Comment by SimonBrandner** [comment]
The trouble here is that you have nested hover effects which looks a little odd to be honest:

https://user-images.githubusercontent.com/25768714/126060106-59b7fb27-34d7-48af-a5fe-6f8e511f66b2.mp4

**Comment by ShadowJonathan** [comment]
I personally like it, I think this is fine.

**Comment by HarHarLinks** [comment]
I see Šimon's argument, but it feels hard to judge without trying it in a natural environment. I will say that it is now obvious you are clicking the original message to jump to it.

In any case if this was to be done properly, the highlighted area should include the colored bar on the left, not extend all the way to the right(?) and have nice rounded corners.
