### ISSUE TITLE
Breadcrumbs that lead to other spaces require 2 clicks to work

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18032]
as of https://github.com/matrix-org/matrix-react-sdk/pull/6391 (I assume)

**Comment by robintown** [comment]
Same thing happens if you try to go to a room in a different space via the message forward dialog

**Comment by SimonBrandner** [comment]
The same thing causes pills to break. Console shows

![Screenshot_20210717_153200](https://user-images.githubusercontent.com/25768714/126038699-ab43058d-fff3-4093-9b2b-ecb3aa2b6030.png)

**Comment by t3chguy** [comment]
What do pills have to do with that error? Pills shouldn't be interacting with the room list store

**Comment by SimonBrandner** [comment]
Well, neither should the forward dialog. The fact is that room-switching seems to be partially broken and when it breaks that is the error we get. So I assumed it's related to that change but it of course can be unrelated :man_shrugging:
