### ISSUE TITLE
Can’t find private chats and messages 

### ISSUE THREAD

**Issue by ginahicks** [vector-im/element-web#18033]
#### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

#### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

#### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by SimonBrandner** [comment]
@ginahicks, please fill in the issue template

**Comment by ginahicks** [comment]
U will have to excuse me I am clueless with all this, my husband who had this profile did all this unfortunately he passed away 2 months ago suddenly he was only 46. However I wanted all his info messages ECT. Bc I miss him n would like to look over everything he had.

**Comment by SimonBrandner** [comment]
In that case, I think it would be best to visit [the Element Web/Desktop room](https://matrix.to/#/#element-web:matrix.org)
