### ISSUE TITLE
Message context menu is a mental load

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18034]
I can't really explain why or how, but every time it opens I have to carefully read what the options are to make sure I pick the right one. Did the options change order or something?

**Comment by ShadowJonathan** [comment]
Maybe it's the increased (icon) padding?

**Comment by dbkr** [comment]
The spacing probably doesn't help. The icons are also in two distinct groups of visual weights (share & report are very heavy vs the others).

**Comment by dbkr** [comment]
Also the 'remove' gets its own section in red below but 'report' doesn't, which is surely equally, if not more, consequential.

**Comment by ShadowJonathan** [comment]
The "remove" button was put into its own section because it would be "destructive", as to basically say "hold up, think about this for a moment longer". Though the constant red every time that menu is opened (as travis is a mod almost everywhere) probably wouldnt help)

**Comment by HarHarLinks** [comment]
I agree, also it seems counter-intuitive, the mental load increased when the icons where added.

**Comment by SimonBrandner** [comment]
Do we all still feel the same way? Personally, I feel like I've gotten used to it and it works just fine for me now

**Comment by robintown** [comment]
Closing due to lack of reports beyond the week that this was changed
