### ISSUE TITLE
Confirmation mail receiving fails on OpenSMTP server

### ISSUE THREAD

**Issue by Rot127** [vector-im/element-web#18039]
#### Description

If the mailserver runs OpenSMTP the confirmation mail on sign up will not arrive.
Logs:
```
smtpd[92414]: 58f6e84f60c642db smtp connected address=69.169.224.7 host=b224-7.smtp-out.eu-central-1.amazonses.com
smtpd[92414]: 58f6e84f60c642db smtp disconnected reason="io-error: handshake failed: error:140260C1:SSL routines:ACCEPT_SR_CLNT_HELLO:no shared cipher"
smtpd[92414]: 58f6e850befa63c6 smtp connected address=69.169.224.7 host=b224-7.smtp-out.eu-central-1.amazonses.com
smtpd[92414]: 58f6e850befa63c6 smtp failed-command command="MAIL FROM:<0107017ab4212363-25147239-3601-4882-8a6d-4de9ce00760f-000000@ses.notifs.matrix.org>" result="530 5.5.1 Invalid command: Must issue a STARTTLS command first"
```

#### Steps to reproduce

- Sign up for account.
- Enter mail address of mail server with OpenSMTP running.

#### Version information

- **Platform**: web (in-browser) / server?

For the web app:

- **OS**: Mailserver runs OpenBSD 6.9 (fully updated and patched) + TLS certs from let's encrypt
- **URL**: https://app.element.io

**Comment by t3chguy** [comment]
Element Web isn't the thing sending the email, matrix.org is using their Synapse. I suggest opening an issue in https://github.com/matrix-org/synapse/

**Comment by Rot127** [comment]
Ok. Thanks for the help.

**Comment by Rot127** [comment]
Just for reference, there seems to be a related issue:
https://github.com/matrix-org/synapse/issues/6211

synapse seems to use <TLSv1.2

**Comment by t3chguy** [comment]
Well presumably it'd be the SMTP server that the Synapse uses to send its outbound mail, doubt it does that directly
