### ISSUE TITLE
Every time I login it asks me to verify.

### ISSUE THREAD

**Issue by freemo** [vector-im/element-web#18045]
I am running my own element instance here: https://element.qoto.org Other than this one problem it does seem to be working.

Everytime I login it asks me to verify. I have no other logins anywhere else so I use the security key option every time, which does work for that session. However when i log out then back in I am forced to reverify every time.

**Comment by freemo** [comment]
Not sure if this is related to the above (if not ill open a new ticket once I make some headway on this)...

In addition if i try to add a email to my account (A second one as I added one through the admin interface), this time the normal way through element, it tells me I need to verify it. I get the verification email from my server and when I click to verify it says it is successfully verified. However when I go back to my account the new email is not listed.

**Comment by t3chguy** [comment]
> However when i log out then back in I am forced to reverify every time.

This is expected, logging out discards anything and everything from that device so when you log back in there's no way of knowing it is the same device

> I get the verification email from my server and when I click to verify it says it is successfully verified. However when I go back to my account the new email is not listed.

Your other issue is totally unrelated, but is due to there being a Continue button in the Element Settings where you start the procedure that you must click to finish the task.

**Comment by freemo** [comment]
@t3chguy thanks so much, i will confirm the second one now. if it pans out ill close the ticket.

**Comment by freemo** [comment]
@t3chguy that did the trick, thanks and sorry for bothering you with this noise.
