### ISSUE TITLE
Unable to upgrade encryption "Not setting dehydration key: no SSSS key found"

### ISSUE THREAD

**Issue by danielrocher** [vector-im/element-web#18046]
#### Description

Impossible to upgrade encryption.

#### Steps to reproduce

When I click on the "Upgrade" button, nothing happens.
![](https://i.ibb.co/s5NDrHk/Capture-d-cran-2021-07-18-14-14-08.png)

In the JavaScript console, the presence of the message: "**Not setting dehydration key: no SSSS key found**"
![](https://i.ibb.co/cb7bNWk/Capture-d-cran-2021-07-18-14-14-37.png)

#### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox 90.0 (64 bits)
- **OS**: Ubuntu 20.04
- **URL**: https://app.element.io 
- *Version de Element* : 1.7.32
- *version de olm* : 3.2.3

**Comment by t3chguy** [comment]
Please fill the issue template, version/env are important for bug reports.

**Comment by danielrocher** [comment]
updated. Tkanks

**Comment by t3chguy** [comment]
This should be fixed in the next release which is due to be released in the coming days (1.7.33)

**Comment by SimonBrandner** [comment]
Closing since this should be fixed in the next release, @danielrocher, shout if it isn't
