### ISSUE TITLE
Desktop notifications emoticons are sometimes displayed incorrectly

### ISSUE THREAD

**Issue by keevan** [vector-im/element-web#18051]
![bugreport-matrixnotification](https://user-images.githubusercontent.com/9924643/126085009-a390dc8d-4a6f-455f-b735-4ee29466b4dd.png)

#### Description

When receiving a message whilst not focused on the desktop application, sometimes emoticons appear flipped / incorrect. This has happened on :thumbsup / :thumbsdown, and the :pleased / :ecstatic face and more emojis.

#### Steps to reproduce

- Start a chat with someone
- Defocus the window (focus on something else like the browser)
- Have them send a message with an emoji to you, e.g. "Hello 🙂"

I expect the same emojis to appear in the notifications, that appear in the desktop app.

Logs being sent: no

#### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 20.04.2 LTS

- **Element version**: 1.7.25
- **olm version**: 3.2.1

**Comment by t3chguy** [comment]
We're just using the Notifications API provided by the underlying browser, kinda seems like either it is faulty or the system font is

**Comment by daniellekirkwood** [comment]
It this still happening? If it's using the browser itself and we're not able to fix it -- we should close this issue

**Comment by keevan** [comment]
I haven't noticed it since upgrading to Ubuntu 22 so might be something else. Happy to close for now
