### ISSUE TITLE
Render room id as link

### ISSUE THREAD

**Issue by sumpfralle** [vector-im/element-web#18056]
#### Is your suggestion related to a problem? Please describe.

When mentioning a room ID (e.g. `!lTcmPpFGNyulwYyLCH:example.org`) in a message, I would like to see a link to the room.
Instead the local part is rendered as text, while the domain part is rendered as an http-based URL.

#### Describe the solution you'd like.

I would like to be able to reference a room ID, which is actionable for the receiver (i.e. rendering a link leading to the room).
This would allow room IDs to be just as usable as room aliases (starting with `#` instead of `!`).

#### Describe alternatives you've considered.

I could assign an alias to the room. But I see no reason to squat the alias namespace of the domain (besides the "refer to the room" issue described above).

Thank you!

**Comment by robintown** [comment]
I think there have been discussions of this kind of thing in the past, where it was argued that room IDs are never really something the end user should have to deal with. The intended way to reference rooms without aliases is to share a matrix.to link, but also, for being able to autocomplete rooms without aliases as nicer-looking room pills, there is https://github.com/vector-im/element-web/issues/17996.

**Comment by sumpfralle** [comment]
I was happy with just copying the full room id into the text. Only the rendering was missing, thus causing confusion at the receiver side.

And yes, I could understand, if this rendering just should not be there, since room ids are not supposed to be communicated to other people within text (instead of using invites and so on). But I would like it :)

**Comment by sumpfralle** [comment]
Duplicate of #5150
