### ISSUE TITLE
[bubble messages] Move right-hand messages and avatars closer to the "read receipt gutter"

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18073]
(Breakout of https://github.com/matrix-org/matrix-react-sdk/pull/6291#pullrequestreview-707090023)

#### Is your suggestion related to a problem? Please describe.
When chatting with bubble messages on, I notice there's a large gap between the read receipts of my messages and the "alignment" of my message itself.

The avatar hangs on the side of the message, but the "gutter" seems to stop on the right side of that avatar.

#### Describe the solution you'd like.
Make sure that the avatar can "hang" over the gutter, like so;

Current;

![](https://user-images.githubusercontent.com/22740616/125758306-4cbebe71-f73a-45f2-9ef9-a051c41fd0c6.png)

Suggested;

![](https://user-images.githubusercontent.com/22740616/125758455-6aab4d04-368e-4784-baa3-4e4359541791.png)

**Comment by amshakal** [comment]
I beleive the issue with bringing them this close together is that it creates situations where there might be an overlap between the read recipt, the avatar and the time stamp. 

Another problem with implementing this is that we want to fix the alignment between the avatar and the bubble as mentioned in [here](https://github.com/vector-im/element-web/issues/18083), and on doing so, there will definitely be an overlap.

**Comment by gsouquet** [comment]
At this stage it seems like the gutter space was added on purpose to cater for some specific scenarios in the timeline.
It seems unlikely that we will change it at this stage, therefore will close this issue

Maybe future design decisions will lead us to revisit this
