### ISSUE TITLE
Small collection of UI nits

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18076]
- [ ] in-reply-to's look out-of-place
  ![image](https://user-images.githubusercontent.com/22740616/125757132-10ac6a36-2d4a-4aa4-9283-d25573ee781f.png)
  (https://github.com/matrix-org/matrix-react-sdk/pull/6396 should be noted here)  

---

- [ ] Single emoji padding is a bit off on the bottom
  ![image](https://user-images.githubusercontent.com/22740616/125757493-80f9e220-2eaf-4b78-b8e8-3ad85f3f8553.png)
  (In general, i think removing a message bubble around emojis entirely could be an alternative, see https://github.com/SchildiChat/schildichat-desktop/issues/37)

---
  
- [x] Long URL preview text overflows out of the message
  ![image](https://user-images.githubusercontent.com/22740616/125757823-54675002-aea9-4395-9275-ba021a77e4f8.png)

**Comment by robintown** [comment]
Closing this since the first 2 issues are now fixed
