### ISSUE TITLE
[bubble messages] If a message is too short, message action buttons can get "in the way"

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18074]
![](https://user-images.githubusercontent.com/22740616/125757024-efb259e8-b5dd-4798-9cab-11dd98a9c4e4.png)

#### Description

When a message is too short, above message action buttons gets in the way of being able to click something else.

**Comment by gsouquet** [comment]
The hit area of the message action bar is quite wide on purpose
However this does not fit message bubble as well. Need to discuss this further with product folks as this impacts quite a few message types

**Comment by ShadowJonathan** [comment]
Note that https://github.com/vector-im/element-web/issues/18075 is also related to this, then, in that vein

**Comment by amshakal** [comment]
@gsouquet and I spoke about moving the action buttons to the right of the bubble, to reduce the overlap. Attaching a screenshot to illustrate the solution
<img width="632" alt="Screenshot 2021-07-21 at 14 55 09" src="https://user-images.githubusercontent.com/85162587/126500596-9e4d6484-7a14-4045-b930-9bfb05c179f6.png">
