### ISSUE TITLE
[bubble messages] Show stickers without "bubble wrapping"

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18080]
Similar to the second point in https://github.com/vector-im/element-web/issues/18076, which mentions https://github.com/SchildiChat/schildichat-desktop/issues/37, I think it's a good idea to show stickers without a bubble message background.

Other messengers like telegram and whatsapp do the same.

Telegram;

![image](https://user-images.githubusercontent.com/22740616/126312022-7854414d-2d17-44af-a716-ee9e44edbdda.png)

**Comment by amshakal** [comment]
We tried this approach initially, it works great if it's the second or third message sent by the same user, but if it's the first message sent, it created an awakward relationship between the avatar, the username and the sticker. 

To simplify that, we added bubbles to emojis and strickers as well.

**Comment by ShadowJonathan** [comment]
I'll close this issue then on that note, thanks for responding!
