### ISSUE TITLE
M11.3 Switch to Spaces by default

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#18088]
* Load Spaces by default instead of Communities
* Temporarily support Communities in Settings
    * Add a toggle to Preferences
    * If linked to a community (prefixed with +) show a relevant tooltip ‘Enable Communities in Preferences’
    * If trying to load a community (e.g. by slash command) show a new full screen view (leveraging the space preview?) with
        * Preview metadata on the community
        * Micro copy on how to enable Communities in Settings
* In future, sunset support for Communities

**Comment by nadonomy** [comment]
@novocaine this is in the Design Review column but has been approved (https://github.com/matrix-org/matrix-react-sdk/pull/6594).

I assume we're waiting until we're ready to exit beta to merge this? Pls can you move the card to wherever you think is best in the board?
