### ISSUE TITLE
[bubble messages] Subjective insights

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18083]
Some improvements I figured on bubble messages. (Note: all of these are subjective)

---

## Avatar icon placement

(From https://github.com/matrix-org/matrix-react-sdk/pull/6291#issuecomment-877352054)

Currently the avatar shows itself to be "just about" touching the top right side of the message, while previously it was offset entirely away from the message, i had some notes on it;

> Some alternatives I think would look better could be;
> - Align the top of the avatar with the top of the message group vertically.
> - Do the same design as the “left side”, and have the user avatar be on the top right corner of the message group
> - Flip that last one on its head, and put it on the *bottom* right corner of the message group (on the last message)
>   - This would lend itself to a design language that others are “beaming down” the messages, while you are “beaming up”, so to speak

---

## Background colours

The current colour of messages, in dark-mode, is `#394049`. In my opinion this is way too bright compared to the almost-black background, as it creates too much contrast inbetween the messages and that background.

My suggestion would be to change it to `#2e3135`, but I saw some dark emojis (such as a black cat) not look well in that.

The colour when hovering over messages (which is currently yellow) turned out to be way too distracting and intrusive to the experience, I don't know a good alternative (even though I suggested `#292a2d`), but here i'd like to suggest to take after Discord, which only minimally changes the message background when hovering over it;

![image](https://user-images.githubusercontent.com/22740616/126311211-a7784199-c176-4ec8-bb3f-ebbfe07e0dd6.png)

---

## Composer alignment

The composer feels "disaligned" with the message timeline now, I feel it is best described with the following images;

<details>
<summary>Images</summary>

![image](https://user-images.githubusercontent.com/22740616/126312543-11789ae2-38ee-4b84-b80a-0f567f8e6727.png)

(White & blue: Left side of messages. Green & Sea green: avatars. Also note the avatar sizes are off)

Previous;

![image](https://user-images.githubusercontent.com/22740616/126312841-56e39458-f8b8-4fea-aab3-bcce370a70d7.png)

</details>

---

## State messages alignment

Currently, state messages are aligned to the middle of the screen.

This is hard to see in a conversation, but just like #18072, it could be moved closer to the left of the screen, as telegram does in adaptive layout mode;

<details>
<summary>Wide images</summary>

![image](https://user-images.githubusercontent.com/22740616/126313436-02c197f7-f02a-4d75-84d0-92a3520ee439.png)

Compared to element;

![image](https://user-images.githubusercontent.com/22740616/126313495-7f5cdda5-da35-48f0-813e-44ae830922f0.png)

</details>

---

## Deleted messages markup

Currently, in my opinion, deleted message indicators look a bit out of place;

![image](https://user-images.githubusercontent.com/22740616/126313995-880bc2ef-46da-4ed9-807d-91e85e3879c6.png)

Compare this to whatsapp, where messages only get stylised differently with an icon placed in front of it, but keep their "bubble wrapping";

![ima_ad988cf](https://user-images.githubusercontent.com/22740616/126314151-4ccfaa0c-fe35-4058-853d-f8a9fa3fd525.jpeg)

---

## Bubble rounded corner "continuity" of short messages

The following image shows that *very* short messages after eachother can look weird with the discontinuity of rounded corners on one side, and the "bubble"-ness of the message on another;

![image](https://user-images.githubusercontent.com/22740616/126314628-36019fcd-49ae-4d02-bf06-8065d4c550c3.png)

Note that this problem does not occur in slightly longer messages;

![image](https://user-images.githubusercontent.com/22740616/126314668-83da35d3-d97e-466f-ad18-e368a9fc8bd0.png)

It should also be noted how telegram handle this, with their messages being slightly more verbose in comparison;

![image](https://user-images.githubusercontent.com/22740616/126314770-03a49964-1479-4536-9481-44e73dddeaa5.png)

The problem isn't big, but I think the design should be able to scale to this size, so I noted it here.

**Comment by robintown** [comment]
+1 for deleted messages looking weird, in particular it can result in sort of a snowfall effect of your own avatar on the right hand side

![Screenshot 2021-07-20 at 22-01-58 Element kaise](https://user-images.githubusercontent.com/48614497/126419036-c023f0c1-3d8c-4453-8e9a-8922f14a65e4.png)

**Comment by amshakal** [comment]
Let me go one by one:

1. Avatar icon placement: I think we plan on fixing this. The idea is to have the same design as the “left side”, and have the user avatar be on the top right corner of the message group. The problem right now was around timestamp. The way to resolve that would be to add extra padding on the right, as we have on the left to accomodate for the timestamp.

2. Background colours: We need to reword the colours for both dark and light themese based on the current design system. Will continue the conversation [here #18085 (light)](https://github.com/vector-im/element-web/issues/18085) and [here  #18081 (dark)](https://github.com/vector-im/element-web/issues/18081)

3. Composer Alignment: Along with composer alignment, I think we need to also align the header with the rest of the messages. 

4. State message alignment: Talking about this issue [here #18126](https://github.com/vector-im/element-web/issues/18126)

5. Deleted messages: Definitely aware of this issue @gsouquet is already working on it to align it with the username. 

6.  Bubble rounded corner "continuity": @gsouquet is already working on it

Thanks! 
☺️

**Comment by ShadowJonathan** [comment]
Thank you for the insightful comment! As I see most concerns are addressed or delegated here, I'll close this pre-emptively, to keep it out of the way.
