### ISSUE TITLE
no start menu or desktop icon when install on windows

### ISSUE THREAD

**Issue by tinsel-grumble** [vector-im/element-web#18087]
#### Description

install on windows does not make a desktop or start menu icon so no way to start element desktop. have to keep reinstall everytime to use

#### Steps to reproduce

- download win installer
- run installer
- see no icons
- keep running installer to connect to element

i expect icons to be able to use program. search in start doesnt even find it install, even if running

i also try to delete eveyrthing element from %appdata% and reinstall. did not work.

Logs being sent: yes/no

#### Version information

- **Platform**: desktop

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows
- **Version**: Element version: 1.7.33
olm version: 3.2.3

**Comment by loucurapt** [comment]
I confirm.

After installation on Windows, there was no shortcut on the start menu or on the desktop.
The installer did create an "Element" folder in my start menu, but empty.

For others who may find this issue, Element is installed to `C:\Users\YouUser\AppData\Local\element-desktop` (AppData is a hidden folder).

**Comment by tinsel-grumble** [comment]
`element-desktop` folder also has all version separate too which is odd. maybe contribute to issue as wrong target or is missing for link in start menu so add fail. i confirm start menu folder empty @loucurapt
