### ISSUE TITLE
M11.11 Communities to Spaces migrator

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#18092]
* To aid users with legacy Communities, we should support migrating them to Spaces.
* To start, we can implement a migrator on Web only
* We should make Spaces don’t support and won’t migrate
  * Flair
  * Rich descriptions
* How we should migrate:
  * Name
  * Avatar
  * New address if public
  * Rooms
  * Invite users to new space
  * Prepend message about migration to group description
  * Hide Communities which you are joined to a space from (Android/iOS)
* We should only let people migrate Communities they’re an admin of
* Once complete, we should heavily suggest to users to sunset their community manually
  * Considering specific interactions to
    * e.g. Update the name/description with links to the specific Space
    * E.g. Copy paste a pre-written message of ‘This community is turning into this Space -> Link’

**Comment by ShadowJonathan** [comment]
FWIW @turt2live has made a "space bot" at `@spacebot:t2bot.io`

**Comment by t3chguy** [comment]
Yup, we know, but we will definitely not be relying on a bot given not all servers federate
It uses a different SDK so isn't portable
