### ISSUE TITLE
Integrate unred notification section from android app to web/desktop

### ISSUE THREAD

**Issue by Kreyren** [vector-im/element-web#18101]
#### Rationale
I keep missing notifications, bcs element just shows a white dot on the space and then expects me to go on an adventure to find more white dots which is annoying af while it works great on android using the labs feature to show list of unread notifications.

#### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: NixOS 21.11 (Porcupine)
- **Version**: 1.7.31
- **olm version:** 3.2.3

**Comment by t3chguy** [comment]
Do you mean https://github.com/vector-im/element-web/issues/16009
or do you mean for messages, then the bell icon in the top right of the app?

**Comment by Kreyren** [comment]
OP updated

> Do you mean #16009 @t3chguy 

Seems irelevant to me

> or do you mean for messages, then the bell icon in the top right of the app? @t3chguy 

The bell icon in the top right of the android app.

**Comment by Kreyren** [comment]
FWIW i wasn't able to find any duplicates in this repo

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/126340236-423c7d9f-d10c-4a9f-9599-9f5cc8905fc7.png)

The web app also has a bell icon for your notifications, not sure what you're asking for

**Comment by Kreyren** [comment]
i am hugging blind! thanks
