### ISSUE TITLE
random disconnect on desktop client and settings wiped

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#18103]
#### Description

random element desktop will put `[Offline]` in the title bar and say connectivity lost. no other internet is lost anywhere. closing and open element desktop does not fix. only fix is to sign out and back in. this looses settings though every time

this happen most times after update from notification in client too. will immediately be offline and have to sign out and back in

for me offline happens at least once per week unless update available. settings always wiped when sign out

#### Steps to reproduce

intermittent hard to reproduce but

- sign in
- stay signed in for awhile and it may happen

OR

- click update notification and will be offline when done
- -sign out/back to fix 

should not random lose connection and go "offline". settings should stay when logging out and back in if same user

Logs being sent: will need to get when happens

#### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**: Windows
- **Version**: Element version: 1.7.33
olm version: 3.2.3

**Comment by SimonBrandner** [comment]
Element shows this warning when your homeserver is inaccessible, what homeserver are you using?

**Comment by ErKaf** [comment]
> Element shows this warning when your homeserver is inaccessible, what homeserver are you using?

Hey, I have the same problem as OP. I use matrix.org, which is accessible because it still works on my phone and my laptop. But my Desktop client still says "Offline" and like OP said, it's only fixable by logging out and logging back in. 

(But I'm on Kubuntu and not on Windows, like OP)

**Comment by tinsel-grumble** [comment]
matrix.org official server

**Comment by ErKaf** [comment]
> matrix.org official server

I stopped using the Spaces Beta and now everything works great again, so the problem must be anywhere with the Beta since the last update. So you could also stop using it for the time till you get a real fix.

**Comment by tinsel-grumble** [comment]
im not using beta anything i know of

**Comment by dbkr** [comment]
If you could submit debug logs for this issue we may be able to see what's going wrong.

**Comment by tinsel-grumble** [comment]
@dbkr will try to remember for next time it happen to me. is random

**Comment by AKlemm88** [comment]
Hello, I have a similar issue. My client looses the config after windows reboot. Then I have to sign out and sign in again. After next reboot ... same issue.

Where can I find the logs for it? Anyone found a solution for this?

Thank you
Alex

**Comment by tinsel-grumble** [comment]
> 
> 
> Hello, I have a similar issue. My client looses the config after windows reboot. Then I have to sign out and sign in again. After next reboot ... same issue.
> 
> Where can I find the logs for it? Anyone found a solution for this?
> 
> Thank you Alex

@AKlemm88  no solution here. even normal sign out wipe prefs, not just when it go offline

**Comment by AKlemm88** [comment]
I found the logs. It seems there is a problem by opening the local stored DB. If I recognized it well, the client is trying to log in to the server, getting a Key and is opening the local DB for encryption Informations. But the client don't get the key for opening the local stores DB. I can not find the cause of the issue.

Maybe we can find the solution together. Did anyone have any other idea?

Thanks
Alex

**Comment by AKlemm88** [comment]
Are there any new informations top the Problem?

**Comment by tinsel-grumble** [comment]
ping for update from element team @SimonBrandner

**Comment by SimonBrandner** [comment]
> ping for update from element team @SimonBrandner

1. I am not a part of the Element team, I am just an outside contributor
2. Pining members of the team won't make things faster, there are some 4 900 open issues and all of these need to get attention, you just need to be a little patient

**Comment by turt2live** [comment]
This issue does not appear to be in an actionable state. If this is still happening, please open a new issue with the requested information.
