### ISSUE TITLE
Room list default avatars get weirdly cropped

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#18100]
swapping inline-block for block on .mx_BaseAvatar seems to fix this one edge

![image](https://user-images.githubusercontent.com/2403652/126336511-48e19aa6-9cc3-4614-83c7-fb009c9a5b03.png)

**Comment by nadonomy** [comment]
If useful:

<img width="496" alt="Screenshot 2021-07-22 at 11 29 24" src="https://user-images.githubusercontent.com/4626865/126628631-71022170-18dc-4df0-9082-789f95bbc5fd.png">
<img width="315" alt="Screenshot 2021-07-22 at 11 32 35" src="https://user-images.githubusercontent.com/4626865/126628668-5f2e56fb-7aee-4ab5-bd38-cceb955775b2.png">
