### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by PierreP94** [vector-im/element-web#18104]
![Capture d’écran du 2021-07-20 11-25-34](https://user-images.githubusercontent.com/72252766/126340810-5802c1dc-4c73-4d17-a321-5b7c46047834.png)

#### Description

Impossible to connect to Docker vectorim/element-web on Synology NAS because of SSL Error

#### Steps to reproduce

- Install the container.
- Start it
- Impossible to connect

Describe how what happens differs from what you expected.

Logs being sent: yes/no

#### Version information

Last version

- **Platform**: web (in-browser) or desktop?

Browser Chrome / firefox (last versions)
OS Ubuntu

I have tried to check the package with Wireshark without success, as I don't really know what is necessary to be checked.

**Comment by t3chguy** [comment]
The docker doesn't do SSL termination https://github.com/vector-im/element-web/blob/develop/Dockerfile
Just standard nginx:alpine

You probably either want to connect using `http://` (no s) or your TLS termination is faulty.

**Comment by PierreP94** [comment]
Ok thanks.
Can be solved with reverse proxy
