### ISSUE TITLE
[nit] SSO buttons are "uncomfortable"

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18114]
![image](https://user-images.githubusercontent.com/22740616/126355951-d09b7165-24fc-49ce-915b-0877c73f53f2.png)

#### Is your suggestion related to a problem? Please describe.
1. ~~When hovering over SSO options, the name popup is hovering directly next to my cursor, and is covering part of that button. I perceive this as "uncomfortably close". This popup happens within less of a second as well, which strengthens that feeling.~~
  Dup of https://github.com/vector-im/element-web/issues/11486

2. When hovering over the buttons, I don't get any intrinsic feedback other than the popup, I think adding a slight greying of the background of the button as a "hover" effect would help somewhat.

Here's a mockup of some improvement I thought about;

![image](https://user-images.githubusercontent.com/22740616/126357434-d3cd8859-6961-4f51-8bc6-5aa62dc20e68.png)

Adding a slight grey with the following insertion;

```css
.mx_SSOButtons .mx_SSOButton:hover {
    background-color: #F5F5F5;
}
```

(I wasn't able to change the label's behaviour, as that one is dictated by Aria, which I have no idea how to change)

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/11486 is the issue re 1
