### ISSUE TITLE
How can I remove all messages from a group at once?

### ISSUE THREAD

**Issue by useruser73** [vector-im/element-web#18119]
Hi, How can I remove all messages from a group at once? Any event for this? Bot? Program? Something?

**Comment by ShadowJonathan** [comment]
Why would you want this? It is rather performance-intensive compared to alternatives you might want, such as message history settings, or removing/upgrading a room entirely.

**Comment by robintown** [comment]
This is not currently possible - there is an open spec issue for it at https://github.com/matrix-org/matrix-doc/issues/3273. Also, this issue tracker is not for support/Q&A, please visit [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) for that instead.
