### ISSUE TITLE
New layout switcher layout problems

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18120]
<img width="635" alt="Screenshot 2021-07-21 at 00 37 12" src="https://user-images.githubusercontent.com/1294269/126408368-c250221e-4f78-427b-9fb2-7efde0bcaee5.png">

surely these should be equal width columns?

**Comment by ara4n** [comment]
also, tapping on the thumbnail should switch the radiobutton over rather than literally having to click the button or label.

**Comment by ara4n** [comment]
also, having selected message bubbles, the preview layout for picking font size is borked:

<img width="649" alt="Screenshot 2021-07-21 at 00 38 24" src="https://user-images.githubusercontent.com/1294269/126408436-4d6019d0-cf95-487d-9c6b-928b48832309.png">

**Comment by robintown** [comment]
> also, having selected message bubbles, the preview layout for picking font size is borked:
> 
> <img alt="Screenshot 2021-07-21 at 00 38 24" width="649" src="https://user-images.githubusercontent.com/1294269/126408436-4d6019d0-cf95-487d-9c6b-928b48832309.png">

Tracked at https://github.com/vector-im/element-web/issues/18084
