### ISSUE TITLE
Membership events feel claustrophobic in message bubble layout

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18126]
![Screenshot 2021-07-20 at 22-54-59 Element #element-dev matrix org](https://user-images.githubusercontent.com/48614497/126423388-7d0466e7-40aa-4ba0-bc78-179ca446981d.png)

Currently they interrupt the visual rhythm that bubbles otherwise have, even just a tiny bit of vertical padding would help.

**Comment by amshakal** [comment]
Yeah i agree. There are two differnt things we can do:

1. Increase padding between events and bubbles and between two different events/evevnts and dates etc. I suggest 20px
2. Align them to the right as they are today

**Comment by ShadowJonathan** [comment]
I'd like to suggest a third:
- group state events together (as they're accustomed to group together, and have little padding between each other), but add that 20px padding only between those state event groups, and any bubble message

How's that sound?
