### ISSUE TITLE
Right padding on reply bubbles is  missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18121]
<img width="585" alt="Screenshot 2021-07-21 at 00 39 20" src="https://user-images.githubusercontent.com/1294269/126408503-98ba3580-d16f-4c7f-9abc-1875aaa316dd.png">

**Comment by ara4n** [comment]
also, is that really the right colourscheme on dark? the grey feels way too light.

**Comment by ShadowJonathan** [comment]
> also, is that really the right colour scheme theme on dark? the grey feels way too light.

FWIW I also noted that [here](https://github.com/vector-im/element-web/issues/18083), under "background colours"
