### ISSUE TITLE
Reply padding is broken on bubbles

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18122]
<img width="561" alt="Screenshot 2021-07-21 at 00 40 59" src="https://user-images.githubusercontent.com/1294269/126408612-42bc26b4-a69d-48f6-b684-d64fa7ff4755.png">

https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$wIL2F8v4Bsvca9UZ_2mANliU9PdFAgZn40p6ncOF8ac?via=matrix.org&via=libera.chat

**Comment by robintown** [comment]
Related: https://github.com/vector-im/element-web/issues/18099
