### ISSUE TITLE
Can't dismiss the "New login. Was this you?" toast

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#18133]
While testing whether https://github.com/matrix-org/matrix-react-sdk/pull/6423 fixed my image display issue (https://github.com/vector-im/element-web/issues/18115), I logged in on the netlify deploy. The "New login. Was this you?" toast appeared, and I just ignored it till I verified my new session. Now I'm trying to click "Later" and it doesn't do anything.

[removed GIF because it showed my home IP address, I'm attaching it to the rageshake]

Observed now on develop.element.io

**Comment by babolivier** [comment]
Note that clicking "Check your devices" shows my security and privacy settings but doesn't dismiss the toast.

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17667
