### ISSUE TITLE
UI and behaviour issues on 1:1 calls

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-web#18138]
- [ ] The colour of the buttons on OFF mode is wrong
- [ ] The dial pad should not be shown for regular users
- [ ] On hover, the controls disappear very quickly, can the transition be set to disappear less quickly? (see competitors)
- [ ] If I'm on a video call, the video icon should be shown in the widget title area and the icon should not be red. can this be corrected on both Light and Dark themes? https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=2904%3A48322
- [ ] We need a Missed call state call tile using the right iconography here: https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=2871%3A55146
- [ ] On missed calls, the UI shows that the call Failed see below. Please update to "Missed call" on the call tile instead (no need of a modal) 
<img width="1440" alt="Screenshot 2021-07-21 at 10 11 04" src="https://user-images.githubusercontent.com/76945183/126463570-1a255bab-23d8-4448-a407-6a9457e2b7fa.png">

- [ ] The connecting states aren't implemented as per design specs https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=3472%3A78780

**Comment by SimonBrandner** [comment]
I've split out the missed call stuff/call event tile stuff into https://github.com/vector-im/element-web/issues/18216

**Comment by SimonBrandner** [comment]
I've split out connecting states into https://github.com/vector-im/element-web/issues/18220

**Comment by SimonBrandner** [comment]
I've split out the Call View issues into https://github.com/vector-im/element-web/issues/18221

**Comment by SimonBrandner** [comment]
Everything here is now split out into issues based on the area of the necessary changes, therefore I am going to close this
