### ISSUE TITLE
Element not showing up on Start Menu but installed on Windows 11

### ISSUE THREAD

**Issue by jeiannueva** [vector-im/element-web#18130]
#### Description

Upon installation of Element. The user won't be able to open it as it's not searchable or even on the start menu of Windows 11  (Running Beta software)

#### Steps to reproduce

1. Install Windows 11
2. Install Element for Desktop

Describe how what happens differs from what you expected.

Logs being sent: yes

Element should be searchable, and on the start menu. All other apps are not experiencing this only element-desktop.

#### Version information

Element version: 1.7.32
olm version: 3.2.3
- **Platform**: web (in-browser) or desktop?  DESKTOP

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 11
- **Version**: 1.x.y? 22000

**Comment by jeiannueva** [comment]
If you are here for the alternative fix. Run the element-setup app and then pin it to the taskbar.
If you also know how to access the installation folder, you can create a shortcut there too!

**Comment by turt2live** [comment]
Sorry, Windows 11 is under technical preview at the moment and not a supported platform. If it's still an issue at or near release time for Windows 11, please report it so we can take a look. For now, it's just too early.
