### ISSUE TITLE
Hidden events do not play nicely with message bubbles

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18132]
They are all center aligned which makes it hard to read when they are expanded
On top of that the expand button sometimes flickers making it hard to reach

**Comment by jryans** [comment]
The expand button actually seems impossible to reach on my side in bubble mode, as its currently covered by the action bar:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/279572/126449217-a7c20b3d-3e1a-40d6-9ac8-4ee4b1768f39.png">
