### ISSUE TITLE
Notifications label in room list is confusing

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18139]
<img width="813" alt="Screenshot 2021-07-21 at 11 16 42" src="https://user-images.githubusercontent.com/4626865/126473212-29cca2db-e05b-484d-a187-fb9065f7ba54.png">

Left: Production. Right: Develop.

The tweak on develop relabelling 'Use default' to 'Global' is confusing in practise. In context, 'Global' seems like a type of notification and causes me to pause and think.

@gaelledel what could we do to tweak? Is there something we could do where we use a more predictable term in the context menu on the room list, and add some micro copy to Settings to aid?

**Comment by gaelledel** [comment]
Default doesn't work either as these are really more based on user's own decisions. So as an alternative I suggest:

In the contextual menu: Custom/Customised, Personalised, or Selective

In the core settings: Custom notifications, Personalised notifications, Selective notifications

**Comment by gaelledel** [comment]
I have a preference for the word Custom if you'd ask me. Let me know so I can let the devs know

**Comment by nadonomy** [comment]
@gaelledel I don't think _Custom_ is appropriate as this is the default selection for everyone.

> Default doesn't work either as these are really more based on user's own decisions.

This is the out of the box, starting, choice though so isn't based on any user's own decisions. _If_ users do delve into Settings to tweak they can carry that cognitive load forward, but for this interaction we should optimise for it to make sense for new users and all users whose goal is to override their account settings for a specific room.

What else could we do?

**Comment by t3chguy** [comment]
In the long term, with the FTUE Notifications project this'll improve to have very similar interactions between Settings > Notifications and the Room notifications override context menu but with push rules that's prohibitively complex and flakey to do

**Comment by nadonomy** [comment]
@dbkr btw would be good to tag/flag this as a release blocker ahead of Tuesdays RC (not sure of the best way/which board to do that in?).

It'll be trivial to implement once we have clarity on the right copy, but would be a shame for this to slip to production as is.

**Comment by gaelledel** [comment]
Have told development to revert back to original terminology

**Comment by t3chguy** [comment]
@nadonomy that is just a label in GH

**Comment by nadonomy** [comment]
> @nadonomy that is just a label in GH ^

Wasn't sure if the label is actively being looked at per release cycle. Assuming from @turt2live self-assigning everything is in hand!

**Comment by turt2live** [comment]
yup, it got raised oob and is part of a sponsored project. Should be up for review soon.
