### ISSUE TITLE
Replies should be more consistent across layouts

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18145]
![Screenshot_20210721_151651](https://user-images.githubusercontent.com/25768714/126494861-09c6809d-e7a0-42b3-b92a-212cc36ef4bf.png)
![Screenshot_20210721_151719](https://user-images.githubusercontent.com/25768714/126494907-fce395e0-086c-43ba-958d-636453e7209c.png)

They look to different, IMO

**Comment by t3chguy** [comment]
Hmm, how are you meant to know who you're replying to in that first screenshot? Is it in the gutter?

**Comment by SimonBrandner** [comment]
> Hmm, how are you meant to know who you're replying to in that first screenshot?

No idea :man_shrugging:

**Comment by SimonBrandner** [comment]
The replies not looking similar could be a problem for when a person might want to use multiple layouts at the same time when it is possible. Having two completely different reply looks would feel weird, IMO
