### ISSUE TITLE
Call event tiles look broken on the bubble layout

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18144]
![Screenshot_20210721_151511](https://user-images.githubusercontent.com/25768714/126494635-d631e878-479c-4667-8afc-92f52551d8f2.png)

They should be wider

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/126495856-52f8abc9-24ed-4701-84f0-dcef45851be6.png)

This bit is just nightmare fuel

**Comment by SimonBrandner** [comment]
> ![image](https://user-images.githubusercontent.com/2403652/126495856-52f8abc9-24ed-4701-84f0-dcef45851be6.png)
> 
> This bit is just nightmare fuel

Users with hidden events disabled are very happy people atm :D Though that's a different issue
