### ISSUE TITLE
Rooms where all messages have expired, are shown as unread

### ISSUE THREAD

**Issue by SamiLehtinen** [vector-im/element-web#18141]
#### Description

Rooms where all messages have expired on server side via m.room.retention and therefore are unavailable from the server, are always and continuously shown as unread in Element Web and Linux Desktop. 

#### Steps to reproduce

- Create a room
- Set short expiration like 1 second using m.room.retention event
- Post something
- Wait for the message to expire
- Clear local cache (or login with new session which doesn't have the message cached)
- Now the room is shown as unread
- When something is posted to the room, and "seen" by the clients then it's marked as read, until this happens again.
 
I guess the logic is bad, it checks if the last event in room is seen, but what if the no last event isn't available? Why it then defaults to unread? If I try to jump to the last read message on desktop client, I'll just gives me an error: "Failed to load timeline position". 

#### Version information

- **Platform**: Web & Linux Desktop

For the web app:

- **Browser**: Firefox
- **OS**: Windows & Ubuntu
- **URL**: 1.7.30 (private server)

For the desktop app:

- **OS**: Ubuntu
- **Version**: 1.7.32

**Comment by 4nd3r** [comment]
duplicate #14976
