### ISSUE TITLE
Option to change notifications preference from inside a room

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18156]
#### Is your suggestion related to a problem? Please describe.
The problem is you need to go to the room list and search for the room but you actually usually want to mute a room when getting a message from that room after a long time...

#### Describe the solution you'd like.
a possibility in the room settings to change the notification preference (e.g. mute room)

I can add screenshots if it helps

**Comment by SimonBrandner** [comment]
So you would want there to be a button in the notif saying "Mute"?

**Comment by chagai95** [comment]
Well that would be optimal but I think that's irrelevant for now since there are no buttons on web - would be a ticket for Android, what I'd like is on the right side bar or as an extra icon on the top next to the calling buttons for example.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/13960
