### ISSUE TITLE
massive slowdowns on sending e2ee messages in last few days

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18155]
something has regressed in the last few days which means it now regularly takes multiple minutes to send an e2ee message in a room with ~500 devices present on element desktop.

**Comment by dbkr** [comment]
Just tested and, although this does seem a lot slower than it needs to be, it's not demonstrably worse between 1.7.33 and today's nightly (on the room I was testing, 32 seconds for app and 27s for nightly). Looks like maybe it's spending its time doing indexeddb txns.

**Comment by novocaine** [comment]
@ara4n is this still happening?

**Comment by kittykat** [comment]
I'm going to close this issue for now as we can't reproduce it. Please reopen if it's still happening!
