### ISSUE TITLE
Larger images in timeline are being cut off on the right

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#18163]
#### Description

Ever since upgrading to Element 1.7.33, larger images in the timeline are cut off on the right side, and the "download" link is no longer visible. In order to view the whole image, I have to click the image now.

#### Steps to reproduce

- Upload a large image (particularly a wide one) to the message timeline

In the previous version of Element, images would shrink to fit the message bubble, so it was always fully shown.

Here's how it looks in 1.7.33:
![image](https://user-images.githubusercontent.com/41203525/126571249-752a4583-10d8-4c20-ba55-aca41feccc70.png)

And here's what it looks like in 1.7.32:
![image](https://user-images.githubusercontent.com/41203525/126571864-6c96d73d-655b-4a53-ada5-1b55635f3729.png)

This might be related to #18162 

Tested on Element Web 1.7.33-53-g5ec0ca91-dirty

**Comment by robintown** [comment]
The download link being gone is intentional, as it has moved to the message action bar: https://github.com/matrix-org/matrix-react-sdk/pull/6386

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/6386 didn't make it into the release, so it's extra cut off

**Comment by robintown** [comment]
Well, it sounds to me like @BurnyBoi is actually running develop and not the release, given that the commit sha in the report is from today

**Comment by turt2live** [comment]
ah, that would do it.

**Comment by robintown** [comment]
Appears to be fixed as of https://github.com/matrix-org/matrix-react-sdk/pull/6448
