### ISSUE TITLE
Make bubbles look cleaner by putting reactions inside

### ISSUE THREAD

**Issue by frandavid100** [vector-im/element-web#18169]
I think that message bubbles would look cleaner if each message's reactions appeared inside the bubble. Here's a comparison of how they look now vs how they would look:

![image](https://user-images.githubusercontent.com/694794/126602576-66ce3a41-0609-40d9-ba25-94c61e631c1e.png)

**Comment by ShadowJonathan** [comment]
I'd actually like the former and current approach, the latter introduces much empty space for singular emojis, while the former actually feels proper in how it "attaches" the reaction to the message, imo.

**Comment by amshakal** [comment]
Hey! Yeah including the reactions inside the bubbles will just make the design a bit bulky and will give the illusion of having a bubble within a bubble. 😅
