### ISSUE TITLE
"your settings" in the search initialisation fail message must be styled as a link

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#18164]
![image](https://user-images.githubusercontent.com/14617699/126571507-c5e65e8e-e905-477b-8443-f07a5e63bec6.png)

"your settings" must be styled as a link. Right now it's highlighten only on mouse over.
That link should open the user setting, jump to the "Security & Privacy" tab and scroll down to the "Message search" section

element-desktop 1.7.33 debian sid

**Comment by ttheshreeyasingh** [comment]
@gsouquet @t3chguy  Can I be assigned this issue?

**Comment by SimonBrandner** [comment]
> @gsouquet @t3chguy Can I be assigned this issue?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by 532910** [comment]
I dunno how to reproduce and this issue is not about the error itself. It's about link style.
