### ISSUE TITLE
Messages have right padding missing

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18174]
![Screenshot_20210722_105635](https://user-images.githubusercontent.com/25768714/126613843-340620c7-9188-4bd7-a895-1693edcb409d.png)
![Screenshot_20210722_105818](https://user-images.githubusercontent.com/25768714/126613953-fdf6c03d-0d4e-47f7-8b01-e41b9192c5a1.png)

**Comment by gsouquet** [comment]
Duplicate of #18121
This is presumably the same underlying issue
