### ISSUE TITLE
1.7.33 crashes on Apple Silicon

### ISSUE THREAD

**Issue by monochromec** [vector-im/element-web#18173]
#### Description

Randomly crashes on an M1 (both native ARM64 and emulated X86 versions).

Crash report for ARM64: https://gist.github.com/monochromec/1b5b5872e360d4d86cd2959a9f4e9ed6

#### Steps to reproduce
- Start Element on OSX 11.4
- Element randomly locks up and exits with a SIGABRT
- Suspect foul play in the memory management of the V8 engine (cf. stack trace)
- Only happens in 1.7.33, previous version works fine

Logs being sent: yes (cf. above)

#### Version information

- **Platform**: web (in-browser) or desktop?
- Desktop

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- OSX 11.4
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- Cf. above
- **Version**: 1.7.33 

More than happy to provide more info - just let me know.

**Comment by ShadowJonathan** [comment]
(Isn't this the release that toyed with Electron 13?)

**Comment by t3chguy** [comment]
No, that one is still on electron 12 https://github.com/vector-im/element-desktop/blob/release-v1.7.33/package.json#L85

**Comment by dbkr** [comment]
Nightly is now on Electron 13 and has a new version of one of the native modules, so would be worth trying that and seeing if you get the same bug.

**Comment by monochromec** [comment]
Different crash in different framework used by V8. Details at https://gist.github.com/monochromec/7a4d2cb770534cab5d61b5a1750324b1 .
Please let me know if more info is needed.

**Comment by dbkr** [comment]
Ah, `v8::internal::FatalProcessOutOfMemory` is fairly incriminating. I'm guessing some change has pushed it over the heap limit on your account.

**Comment by monochromec** [comment]
The issue disappeared after upgrading to OSX 11.5 today. Not sure if this demands further RCA. I'll close this for the time being, happy to file a similar issue should this reoccur.
