### ISSUE TITLE
Remove excessive padding after url previews

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18178]
#### Is your suggestion related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/2803622/126623850-6599a4c8-4e2e-4901-bc01-b847d13bec25.png)

![image](https://user-images.githubusercontent.com/2803622/126623788-b59518c7-d157-4468-9681-26a509a4defe.png)

#### Describe the solution you'd like.
Same as normal msgs

#### Describe alternatives you've considered.
no

#### Additional context
nightly 20210722

**Comment by t3chguy** [comment]
looks like a regression from the bubble messages work
