### ISSUE TITLE
profile picture problem

### ISSUE THREAD

**Issue by ilovepoopingmypee** [vector-im/element-web#18177]
#### Description

Only with element, and only in a specific room, profile pictures do not show for half the users
I have tried clearing cache and it did not help
Other clients work just fine

#### Steps to reproduce

join #public:midov.pl
try to see profile pictures

Logs being sent: yes/no

#### Version information

- **Platform**: desktop

- **OS**: Artix Linux
- **Version**: 1.7.33

**Comment by t3chguy** [comment]
Would be good to get an example of which user's avatar does not show up.

![image](https://user-images.githubusercontent.com/2403652/126622522-007392d3-a870-4981-9f0c-402c367e55e6.png)

**Comment by t3chguy** [comment]
Once I joined the room the users claimed they lured me there to ask me other support queries, assuming this was a lure and not a genuine issue.
