### ISSUE TITLE
Spaces: new private space shows different UI when first using and later

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18181]
#### Description

Spaces UI did not behave consistently for me as a first time user. The first private space I created showed me a different UI than the second one. It is possible that I may have clicked away from the space before the home screen was loaded. As a new user, I was not expecting the landing page to change until I took an action (the "Who are you working with?" view is only visible on a newly created space and is not accessible again, as far as I can see, after navigating away from the space regardless of whether it was actioned or not).

#### Steps to reproduce

1. Enable Spaces in the Labs tab of the settings dialog
2. Add a new private space 
3. Add a name and "Create"

[Goes straight to the space home view]

4. "Clear cache and reload" in the Help & About (…because of an unrelated issue, this step may not be relevant. I also did not try creating a new space until a while later.)
5. Create another new private space

This time the view shows:
![Screenshot from 2021-07-22 12-44-48](https://user-images.githubusercontent.com/51663/126637524-c80c92c6-75a3-4309-983c-f91a60c931f1.png)

I expect consistent behaviour every time I add a new space.

The first behaviour also left me feeling confused (as a first time user) about how to create a private space to organise rooms.

Logs being sent: yes
[log-0.txt](https://github.com/vector-im/element-web/files/6862153/log-0.txt)

#### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium Version 91.0.4472.164 (Official Build) 
- **OS**: Arch Linux (64-bit)
- **URL**: app.element.io

**Comment by t3chguy** [comment]
> [Goes straight to the space home view]

I cannot reproduce this, it is not intended. The setup wizard is optional as you have found beyond the point of setting avatar/name/topic but I have never seen it autoskip.

**Comment by kittykat** [comment]
I can't reproduce it as well now, and it didn't help that I wasn't aware that I was supposed to see a wizard on the first run experience!
