### ISSUE TITLE
Replies to messages using m.notice appear as m.not-notice

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18183]
![](https://i.imgur.com/YbkasUD.png)

Should be grey compared to the reply.

**Comment by HarHarLinks** [comment]
Works for me, desktop nightly 20210723
![image](https://user-images.githubusercontent.com/2803622/126784026-84649d4e-26c3-47d6-8129-7b92253154cc.png)

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @SimonBrandner to let me know that it’s ready to be reopened.
