### ISSUE TITLE
Show image metadata in timeline (& lightbox)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18197]
#### Is your suggestion related to a problem? Please describe.
With matrix-org/matrix-react-sdk#6386 (and perhaps more?), the download button which used to be a green linkified text "description" under an ~~image~~file in the timeline is gone. With it is gone the file name and size.

While I like the clean look, I also like to see file names and sizes. This could even be an opportunity to show more than before.

#### Describe the solution you'd like.
I would like that feature back in a way. Perhaps there is a way to make it fit better than adding back a caption:
With the reply redesign, replies to images "quote" the image like this:
![image](https://user-images.githubusercontent.com/2803622/126768833-91ff8585-e7d6-4dfd-9421-79fd395089f3.png)
I notice that even when sending an extremely wide (4k px) image like the following, there is still screen space ~~left~~ right:
![image](https://user-images.githubusercontent.com/2803622/126768930-17d2fc11-3606-4a40-af1b-893a1d1c1a2e.png)
In fact that seems to be a somewhat arbitrary limit (w=800px) for thumbnail size that just works out this way on my 1080p screen.
Perhaps that space could be repurposed somewhat similar to the reply view.

Similarly in the lightbox there is currently _no_ metadata visible at all, even though I believe we had it prior to the lightbox (full size/screen image viewer) upgrade with fancy zooming rotating etc. There is plenty of space in the top bar. #17014

The info I would like:
- file name
- file size
- image/video dimension
- audio/video duration

I would be content if in the timeline, these would only be shown if there is space left to repurpose for them "anyway", i.e. most situation. Fewer (less height to fit the list), or no (image fills full width) is acceptable, since they can be explicitly viewed in the lightbox.

#### Describe alternatives you've considered.
This info could also be shown on hover: darken an image and put the text on top (ensure enough contrast). Kind of the reverse of the GIF indicator.
Audio will probably be always tiny enough to show it on the side.

This could also be an optional "power user" toggle in appearance.

#### Additional context
#17014

**Comment by HarHarLinks** [comment]
Regarding my alternative idea, this is what the new app.cinny.in does:

![image](https://user-images.githubusercontent.com/2803622/127492604-2dfaec6f-086b-47cd-8003-8b33b222f567.png)
These are nicer than current stable element, but not the direction current develop is going.

Mockup with develop as baseline:
![Element Mockup](https://user-images.githubusercontent.com/2803622/127496382-4ac1d596-a371-4f30-9bcc-6607b76caecd.png)

**Comment by ara4n** [comment]
The fact we can no longer see what filename a given image/video has (or how massive a download it will be if i click it) is a huge step backwards.
