### ISSUE TITLE
Rich embed of matrix.to a message

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18190]
#### Is your suggestion related to a problem? Please describe.
I happens regularly for me that someone is confused about what message is being discussed, because they missed it or similar.
We can currently permalink to a message by "sharing" it via the context menu to get a matrix.to link. Clicking that link stays within riot and, if the room/message is accessible to the client, will navigate to it.

This is fine but it could be nicer.

#### Describe the solution you'd like.
I would like a way to render such matrix.to links to messages similarly to a reply. You could think of my UI vision like a custom embedded reply. This is somewhat analogous to matrix.to user/room<del>/community</del> which are element's code for (try-to-make-)pill-here (is that even spec'd? something should get spec'd for that).

There should be a nice UI button that places the "embed code" in the composer for me, similar to the quote (and some extent reply) button. Perhaps the same action should add a `relates_to` field, which could be the same as the rich forwarding if that ever happens.
The UI for recipients should fall back to "this message is not accessible, because..." and probably the raw URL.

#### Describe alternatives you've considered.
no

#### Additional context
Related to rich forwarding?

**Comment by SimonBrandner** [comment]
> Related to rich forwarding?

Yes, this is basically that, therefore I am closing in favour of https://github.com/vector-im/element-web/issues/4747. Shout if you disagree
