### ISSUE TITLE
Check "Building From Source" workflow

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18196]
From reports in dev rooms, I suspect the steps in our "Building From Source" section in the readme no longer work and lead to an error about react-sdk's component-index being missing (ie. the one where you just clone element-web and run yarn dist as opposed to the 3 separate linked checkouts).

We should run through this and see if it works or not (aside from any questions on whether checking out *just* the element-web repo and building that is a sensible or valuable thing to do...)

**Comment by luixxiul** [comment]
For me the latest yarn did not work due to an error (the second step on the documentation); installing Yarn 1.x instead worked.

**Comment by t3chguy** [comment]
It works, we specifically link to https://classic.yarnpkg.com/en/docs/install
