### ISSUE TITLE
New-style reply design is harder to grok

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#18194]
As a gut reaction, the new replies are a lot harder for me to follow what's going on and pick them out.

Before | After
--- | ---
![](https://user-images.githubusercontent.com/558581/126718305-91560d77-0160-454d-a7cd-9968fba24344.png) | ![](https://user-images.githubusercontent.com/558581/126718314-f4e9f83d-1bbe-47b7-9424-8adf2a9ee1e2.png)

Full-size:

Before | After
--- | ---
![](https://user-images.githubusercontent.com/558581/126733668-d0d50b21-6043-41fd-a414-0e4f1abd0c99.png) | ![](https://user-images.githubusercontent.com/558581/126733678-4ed4533b-d1ab-4f92-b1d4-3657ed4bd0bd.png)

It looks like this was updated in https://github.com/matrix-org/matrix-react-sdk/pull/3553 and has finally made it to https://develop.element.io where I noticed it.

Reading through the PR, [@nadonomy's comment](https://github.com/matrix-org/matrix-react-sdk/pull/3553#issuecomment-543666473) about "The avatars in replies were useful, so would prefer to keep them" made me realize that this might be the big missing piece for me. Although the discussion for keeping them was leaned towards making it like small pill style and the big left spacing would still be gone 🤷 

In terms of spacing and colors, it's probably more something to get used to. Although previously the bottom margin on the quote made it easier to distinguish the actual message from the quote.

This issue seems like it may be more personal feedback than an actionable issue. Feel free to close 🙇

**Comment by robintown** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/6396 is the PR to bring back the avatars (while still keeping replies compact, of course)

**Comment by MadLittleMods** [comment]
Thanks @robintown 🙂 I feel like there is still something to it that feels off. It's blending too well with the current spacing or rhythm.

**Comment by SimonBrandner** [comment]
Hmm, I would suggest we wait for https://github.com/matrix-org/matrix-react-sdk/pull/6396 to get merged and iterate from there onward

**Comment by robintown** [comment]
Hmm, could giving replies the same lightened color as blockquotes be a solution?

![Screenshot 2021-07-23 at 11-15-43 Element #element-dev matrix org](https://user-images.githubusercontent.com/48614497/126803456-36335db8-95b9-40e2-aa66-411199df8ff7.png)

**Comment by SimonBrandner** [comment]
That looks great to me! Also we could then add a hover effect

**Comment by robintown** [comment]
Maybe add it to the PR then :D
