### ISSUE TITLE
Inconsistent widths on scores/blocks

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18199]
<img width="112" alt="Screenshot 2021-07-23 at 12 23 58" src="https://user-images.githubusercontent.com/4626865/126775305-5ceee98f-faf5-481b-a8a6-acab3ce723d5.png">

With https://github.com/matrix-org/matrix-react-sdk/pull/6441 we reduced the visual weight of quotes. However, there are other UI elements (quotes, nested replies) which use the older/thicker lines.

Can we find/replace all of these related styles?

**Comment by t3chguy** [comment]
yeah looks like user input blockquotes aren't styled right
