### ISSUE TITLE
Truncated reply previews are useless with fallback-reply-quotes (common android)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18205]
#### Description

(the fallback is bad and should be removed, or this might never go away. but that is a spec issue.)

![image](https://user-images.githubusercontent.com/2803622/126788994-d5fa044d-99c7-4737-a54c-2a26f26802b8.png)
This is a common occurrence with android handling things wrong when editing a reply. It leads to the above.

If it isn't fixed ~~on android~~ in the spec (as it hasn't in years!) desktop needs to work with it.

#### Steps to reproduce

- reply
- edit that reply an android
- reply to that again

The preview previews the "grandparent" message instead of the parent.

message from the screenshot: https://matrix.to/#/!LPqOcoJQuGkweiTedq:riot.ovh/$7657d0RYb-MMzrUee5joUupurozJAMW2OaUEbwAxlcQ?via=matrix.org&via=fairydust.space&via=envs.net

Logs being sent: no

#### Version information

- desktop
- arch
- nightly 20210723 and any element android app version

**Comment by t3chguy** [comment]
> If it isn't fixed on android in the spec (as it hasn't in years!)

Got the spec issue to hand?


This is unequivocally not a receiving side issue, its also difficult to solve on the receiving side without false negatives given the variety of ways a sending client could send something mangled is greater than one.

**Comment by t3chguy** [comment]
The way android mangles it is by nesting the mx-reply tag last I checked - which is explicitly against the spec - see my earlier investigation into this here https://github.com/vector-im/element-web/issues/14081#issuecomment-645990934

**Comment by t3chguy** [comment]
```json
{
  "content": {
    "body": "* I had an idea to make clicking on a space that's already selected pull up the index. I think that would make it feel a lot less hidden",
    "m.new_content": {
      "body": "> <@matthew:matrix.org> feels unintuitive and hidden relative to having some kind of first-class \"show me the space!\" button\n\nI had an idea to make clicking on a space that's already selected pull up the index. I think that would make it feel a lot less hidden",
      "format": "org.matrix.custom.html",
      "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!LPqOcoJQuGkweiTedq:riot.ovh/$P38uSMMXnol2IkPzNlox7wDaNB7etJa5GJ1ePvZ94yY?via=townsendandsmith.ml&via=matrix.org&via=fairydust.space\">In reply to</a> <a href=\"https://matrix.to/#/@matthew:matrix.org\">Matthew</a><br />feels unintuitive and hidden relative to having some kind of first-class \"show me the space!\" button</blockquote></mx-reply>I had an idea to make clicking on a space that's already selected pull up the index. I think that would make it feel a lot less hidden",
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$Q1jRZMdZvPPpsXiTBwZKjXXnMpOGvkoEH9XY79kivio",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1626953749627,
  "room_id": "!LPqOcoJQuGkweiTedq:riot.ovh",
  "sender": "@robintown:townsendandsmith.ml",
  "type": "m.room.message",
  "unsigned": {
    "age": 94212296
  },
  "event_id": "$JxtN9XhFpeXZQu9BAzPeOmOqIcK7HLVXylpcjNEBvqo",
  "user_id": "@robintown:townsendandsmith.ml",
  "age": 94212296
}
```

The bug happening here is that `<mx-reply>` should not be present in edits.

See spec document https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md

> What happens when we edit a reply?
> We just send an m.replace which refers to the m.reference target; nothing special is needed. i.e. you cannot change who the event is replying to.
> The edited reply should ditch the fallback representation of the reply itself however from m.new_content (specifically the <mx-reply> tag in the HTML, and the chevron prefixed text in the plaintext which we don't know whether to parse as we don't know whether this is a reply or not), as we can assume that any client which can handle edits can also display replies natively.

**Comment by HarHarLinks** [comment]
I faintly remember discussing the removal of reply fallbacks with you a while back.

I understand and agree, thanks for the analysis. I am raising this issue with android... again.

**Comment by t3chguy** [comment]
Removing the fallbacks altogether will be great, not sure where that is on the spec core team's agenda. They are currently going through finalising all the aggregations MSCs so maybe they can look into that afterwards
