### ISSUE TITLE
Native Apple Silicon app?

### ISSUE THREAD

**Issue by danielktdoranie** [vector-im/element-web#18215]
#### Is your suggestion related to a problem? Please describe.
I am frustrated there is no native Apple Silicon app.

#### Describe the solution you'd like.
I'd appreciate a native Apple Silicon app so I don't have to use Rosetta 2 (which will soon be discontinued by Apple)

See above
#### Describe alternatives you've considered.
Running on Rosetta 2 now but Apple will soon discontinue that, it's only meant as a stop-gap measure. 
#### Additional context
Maybe a arm64 release for Raspberry Pi too?

**Comment by t3chguy** [comment]
https://packages.riot.im/desktop/install/macos/arm64/

**Comment by t3chguy** [comment]
> Maybe a arm64 release for Raspberry Pi too?



https://github.com/vector-im/element-web/issues/17942
