### ISSUE TITLE
Avatar not lined up with join message

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18218]
![](https://i.imgur.com/ZSgtRH4.png) Modern theme, Nightly.

**Comment by gsouquet** [comment]
@turt2live are you still experiencing this?
I've tried reproducing on different browsers without luck so far

**Comment by turt2live** [comment]
@gsouquet I'm getting this in Nightly, Windows 10 (latest as of writing). Appears to only be an issue for people without avatars set.

**Comment by gsouquet** [comment]
It appears that this has been fixed on develop.element.io.
Will close and please let me know if you do experience this again
