### ISSUE TITLE
Random Text in Composer

### ISSUE THREAD

**Issue by Skaalgard** [vector-im/element-web#18210]
#### Description

I'm having an issue where sometimes random text is input into the composer (the "send message" input box) as if I had typed it there. Sometimes it's text I've copied and sometimes it isn't. It does not seem to follow a pattern on this. Today I was browsing a message board and when I returned to Element, the entire post had been "typed" into the input box.

#### Steps to reproduce

I can't seem to reliably reproduce this issue, but:

1. Browse web while having Element open, maybe highlight some text.
2. Return to Element, especially to a room that was not open previously.
3. See text from Web in the composer.

Obviously the expected behavior is for this not to occur.

Logs being sent: yes

#### Version information

- **Platform**: Desktop
- **OS**: Linux Mint 20 x86_64 Xfce
- **Version**: 1.7.25 (olm version 3.2.1)

**Comment by ShadowJonathan** [comment]
Can you give some examples of the kind of text that got copied in there?

**Comment by Skaalgard** [comment]
I had this page open in my web browser: https://midnight.pub/posts/605

And the following text was copied into the composer: 

"Over the years, I've left behind a trail of abandoned blogs. From geocities to wordpress, I start with high hopes only to slowly lose interest or motivation after a few posts. I still have wild fancies of consistently writing about things I like or find interesting, but I'm sure this will be no different (on a long enough time scale, the survival rate for everyone drops to zero). Starting projects I will never finish is a recurring problem for me. A project I can easily complete is too trivial and boring to work on, but a project that is interesting and exciting is too large and daunting to ever finish.

I've read a lot about writing. As an avid reader, I always thought I should try my hand at the craft. So many authors say something along the lines of "I can't not write. I have to get these ideas out of my head and onto the page." That's an attitude I can only envy. For me, putting words on the page is more like pulling teeth. I don't enjoy the act of writing, but I want the satisfaction of having written. But I keep coming back to writing. I do believe it is good for me to put my thoughts into words and share them with others. Even if I am just shouting into the void, the act of writing seems beneficial.

This is a lot of whining for a first post, and I hesitate to even upload it. But, maybe writing one post will give me some momentum to write more. Maybe this time will be different and the habit will stick. "

**Comment by Skaalgard** [comment]
Sometimes it'll just be a message from another Matrix room. Say, for example, someone says "Hey, how's it going?" and sometimes I'll go into another room and "Hey, how's it going?" will be in the composer.

**Comment by robintown** [comment]
Are you perhaps middle-clicking on the composer by accident? That tends to be the most popular way of accidentally pasting things

**Comment by SimonBrandner** [comment]
Or pressing both the left and right button which emulates middle button click in some cases

**Comment by Skaalgard** [comment]
I didn't realize the middle mouse button would past things. This seems an odd choice. It is probable I was accidentally middle-clicking.

**Comment by robintown** [comment]
Ah, well that is a feature of your browser/OS, so there isn't much that Element can do about it. I'm going to close this as it was likely just that that was happening, but if you see this happening for some other reason feel free to reopen

**Comment by Skaalgard** [comment]
No, this was the issue, closing is appropriate. Thanks for your help - I was completely unware of this issue in Linux.
