### ISSUE TITLE
Force desktop view on mobile

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18213]
#### Is your suggestion related to a problem? Please describe.
it's impossible to read messages otherwise with the mobile view and it'll be nice to not have to install an app just to preview a group

#### Describe the solution you'd like.
Force desktop mode after the user chooses to continue on mobile

#### Describe alternatives you've considered.
fix the margin on the right of the messages for mobile...

#### Additional context
I tried googling: https://stackoverflow.com/questions/31334481/how-to-force-desktop-view-on-mobile-devices-bootstrap

**Comment by t3chguy** [comment]
Due to the support policy marking mobile devices as Experimental this is unlikely to get any attention outside of the community like it did with https://github.com/vector-im/element-web/pull/13818 which added the existing viewport attribute

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/9814
