### ISSUE TITLE
Display name showing wrong

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18222]
![Screenshot from 2021-07-25 12-10-34](https://user-images.githubusercontent.com/31655082/126895532-c19c7d61-3a33-4b92-8a93-c8c138e21c2f.png)

![Screenshot from 2021-07-25 12-11-19](https://user-images.githubusercontent.com/31655082/126895541-57ad8786-a3db-4f5e-bd04-61dbf3703499.png)

#### Description

The same user is shown in one chat with a different display name as in a different chat

#### Steps to reproduce

- Not sure, might be related to tg bridge

Logs being sent: yes

#### Version information

- **Platform**: web (in-browser) or desktop?

on different web instances all the same.

**Comment by t3chguy** [comment]
Display names are per-room, so it sounds like that room's state is missing that user's display name.

**Comment by chagai95** [comment]
Interesting, how can I get more info on that?

**Comment by t3chguy** [comment]
/devtools -> Explore Room State -> m.room.member -> @telegram_783139841:chagai.website

It looks like either the bridge or your server didn't propagate the display name change to this room.

**Comment by chagai95** [comment]
ok thanks, I'll just change it manually, love these dev tools!

**Comment by t3chguy** [comment]
You cannot update another user's displayname, as per the spec anything with a state key of an MXID is reserved to that user. You would need to either have the bridge re-set the displayname or masquarade as the bridge using its access token and perform the update that way.

Closing as not a client issue.
