### ISSUE TITLE
Voice messages uploading errors should be contextual

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18226]
If sending a voice message fails, we expose this in a fairly brutal full screen modal. We should use contextual feedback instead. Can we use the message send fail/retry interactions where:

1. Messages instantly appear in the timeline in all cases
2. Errors in the room list are easily discoverable
3. We have nice interactions above the composer to send/cancel/send all, etc

**Comment by nadonomy** [comment]
@turt2live I'm reluctant to add the release blocker label on this depending on effort for 2&3. What are your thoughts?

**Comment by nadonomy** [comment]
@turt2live @gaelledel I'm tentatively marking this as release blocker, pending effort.

**Comment by gaelledel** [comment]
@turt2live Can you let me know of the types of errors that can occur and if you need support for copy writing for these?

**Comment by turt2live** [comment]
I've opened https://github.com/vector-im/element-web/issues/18246 to track the future work where we want this feature (I imagine it's desirable outside of voice messages too), but as mentioned internally it's a bit complex at the moment and not necessarily worth the development time at the moment. 

Changing to needs-design to work out improved copy/approach.
