### ISSUE TITLE
Voice messages layout issues

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18225]
When using voice messages, you can observe:

1. The voice message UI building frame by frame
2. The overall composer layout (e.g. user avatar) pixel jiggling when sending messages

We should obscure the first, and the second shouldn't happen.

**Comment by turt2live** [comment]
@nadonomy are you able to screencap what you're seeing for both of these? (and include browser+OS information please)

**Comment by turt2live** [comment]
ah, I guess for popping in it's the state where the first time load can be a bit slow (half the stuff shows up)

**Comment by turt2live** [comment]
though I'm not able to reproduce this :(

**Comment by nadonomy** [comment]
Specifically it's these loading in frame by frame:

![image](https://user-images.githubusercontent.com/4626865/127987297-6dd3b5a1-6af3-4a09-9ea5-6c9bcca883f9.png)
![image](https://user-images.githubusercontent.com/4626865/127987323-fbddd296-721f-44a3-ad37-caea498f43b9.png)
![image](https://user-images.githubusercontent.com/4626865/127987327-17d2667a-05ce-4a36-91e4-591f6b820378.png)

Happens most times I use voice messages (Chrome, macOS), irrespective of first load.
