### ISSUE TITLE
"Show notification badges for People in Spaces" setting not respected

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#18229]
#### Description

When a friend sends me a message in our DM, which produces a notification, the notification badges on all spaces which we share increments as well. This is despite the setting for this being turned off on my side:

#### Steps to reproduce

I don't really know how to reproduce this somewhere else, but what I'm observing on my side is:

1. Have the "Show notification badges for People in Spaces" setting in Settings > Labs > Spaces turned off.
2. Have my friend message me, producing a notification.
3. All spaces where we are both members get their notification badges incremented.

Logs being sent: yes

#### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.33

**Comment by t3chguy** [comment]
This setting is about to be nuked out of orbit, so hopefully any bugs along with it :D
