### ISSUE TITLE
Blurhash shown for images in the browser cache

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18243]

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/17879

**Comment by Palid** [comment]
Images were properly cached for unencrypted messages, but weren't really in a cache for encrypted messages. 
While fixing this problem I found out that there's some regression with sizing blurhash/placeholders and fell into a rabbit hole. Both will be fixed by my PR.

**Comment by Palid** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17862
Turns out we can't cache the images that are encrypted, but we are already caching non-encrypted images via browser means.
The proper solution is to make better user experience for loading encrypted images.
