### ISSUE TITLE
Blurhash preview ~twice the size of the image

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18240]
When the image loads, the timeline jumps

**Comment by Palid** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18254 ?

**Comment by eras** [comment]
The issue can be seen by switching to Matrix HQ to this message: https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$_RhglMp7cK4AlNpMi5XLD4QCqm3AdoShRYgzL-a7ac0?via=matrix.org&via=cybre.space&via=libera.chat

It seems to be visible (very, very shortly) when you switch to the room. I guess it shouldn't do the blurhash display at all in that case..

**Comment by t3chguy** [comment]
@Palid didn't you fix this issue?

**Comment by SimonBrandner** [comment]
> @Palid didn't you fix this issue?

Yeah, I can't see it on nightly

**Comment by Palid** [comment]
@t3chguy It escaped my closing, it's fixed. Thanks for catching!
