### ISSUE TITLE
CORS Errors when trying to talk to homeserver on Element Desktop

### ISSUE THREAD

**Issue by darnir** [vector-im/element-web#18248]
#### Description

On Element Desktop, I cannot communicate with my homeserver https://talk.go7box.xyz. It consistently complains about connection errors. However, from the same machine, I can use Element Web, nheko, fractal, Wget and curl to login and communicate with the homeserver without any troubles. Element Desktop is the only client that is unable to talk to the homeserver.

#### Steps to reproduce

- Start Element Desktop
- Change Homeserver to "talk.go7box.xyz"
- Try to Login

This should log the user in successfully. However, it throws an error instead: 
`There was a problem communicating with the homeserver, please try again later.`

I don't have such an issue on my Element Android that is running on the same network. So I tried using nheko, fractal and Matrix Shell Suite. All of them could successfully login and send messages. Some on #element-web:matrix.org asked me to try with Element Web. So I ran Element Web on Firefox and even from there, I could log in successfully. Only on Element Desktop do I have this issue.

Next, in order to debug, I took a look at the network activity. The only difference I could see was that Element Web sends a:
`origin: app.element.io` header whereas Element Desktop sends a `origin: vector://vector` header. On Element Desktop I also see a lot of errors in the console complaining that the CORS request had been rejected. I copied the failing POST request as cURL  and ran it on the command line. That also succeeded without any issues. I received back a 200 response with a access_token in the JSON.

So, literally only Element Desktop is unable to communicate with the server. The exact same HTTP request when sent via Curl works just fine.

Logs being sent: Can't

#### Version information

- **Homeserver**: Synapse 1.38.1

- **Platform**: Desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.7.33

**Comment by darnir** [comment]
I have found some more information about this issue. It looks like Element Desktop closes the network connection when initiating a `GET /sync`  request a little too early. 

I run synapse behind a nginx reverse proxy, and I can see hundreds of requests coming from Element Desktop all of which have a "499" error code. Which is an nginx extension for when the client closes the connection before the backend server can respond.

Can someone please look into this issue? It is extremely annoying. I don't know if this is a synapse or a Element problem, but not being able to use Element Desktop is very frustrating.

**Comment by darnir** [comment]
The reason seems to be that over a IPv6 connection, Element Desktop sends a request with a timeout of 0. See the following excerpt from the network tools in Electron:

Query String for a `GET /sync` request:
```
filter=8&timeout=0&since=s2437449_117861614_20428_7024048_372597_164_98153_19352788_6
```

The query string on the same request path when I disable IPv6 on my PC and force a IPv4 connection:
```
filter=8&timeout=30000&since=s2445621_118304660_12309_7055234_372735_164_98203_19383293_6
```

As one can see, the timeout is now "30000" which is enough for the server to complete processing a `/sync` request. But with a timeout of 0, the request always times out and Element is unable to talk to my homeserver

**Comment by t3chguy** [comment]
> But with a timeout of 0, the request always times out and Element is unable to talk to my homeserver

The spec says `timeout=0` means

> By default, this is 0, so the server will return immediately even if the response is empty.

So it really shouldn't time out, as it doesn't have to block/wait for anything.

**Comment by darnir** [comment]
So does that imply this is a bug in Synapse?

**Comment by SimonBrandner** [comment]
@darnir and @besendorf, did this work before for you?

**Comment by SimonBrandner** [comment]
[Image of logs when trying to login](https://user-images.githubusercontent.com/26350155/131347096-b5e8eabf-3258-4ada-8b41-c23d0be55d3e.png)

**Comment by besendorf** [comment]
> 
> 
> @darnir and @besendorf, did this work before for you?

Yes it worked before without any problems. At one point I had to log out in Element Desktop because the UI froze. After that it I couldn't log in anymore. See #18836 for reference.

**Comment by novocaine** [comment]
If its a CORS issue .. you should be able to open the network tab in the console (Ctrl+Shift+I) and look at the erroring requests to `client` and `versions` when you set the homeserver url and see in more detail why the request is failing

**Comment by besendorf** [comment]
> If its a CORS issue .. you should be able to open the network tab in the console (Ctrl+Shift+I) and look at the erroring requests to `client` and `versions` when you set the homeserver url and see in more detail why the request is failing

I just wanted to try this and then suddenly I could log in without any problems. Im not sure why though

**Comment by SimonBrandner** [comment]
@darnir, can you still see this?

**Comment by darnir** [comment]
I'm going to upgrade synapse tonight and try it again. I should get back to you within 24 hours with something.

**Comment by novocaine** [comment]
Downgrading to O-Low as I believe this this rare and likely somehow setup specific, as we can't reproduce.

**Comment by darnir** [comment]
I am still seeing this. 

I've attached an image of the console.
![image](https://user-images.githubusercontent.com/1660085/131739338-58f64a1a-307b-46df-9baf-e9538bc25f13.png)


Some queries go through, but others end up dropping. As a result, my Element Desktop keeps switching between connected and not-connected states

**Comment by t3chguy** [comment]
Looks like timeouts, but only the Network tab would tell you for certain. In Timeouts the CORS/ACAO header also will not be sent.

**Comment by novocaine** [comment]
those `ERR_NETWORK_CHANGED` errors seem like a client connectivity issue .. 

https://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome also notes the problem seems to happen on linux with ipv6..

**Comment by novocaine** [comment]
@darnir did you end up getting to the bottom of this?

**Comment by darnir** [comment]
The issue seems to have disappeared entirely on its own. I haven't changed anything, but I don't see it anymore. So I'm going to close this issue. Thanks everyone that tried to help. If something shows up again, I'll re-open here
