### ISSUE TITLE
Don't ping me when a message mentioning me is replied to

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18256]
#### Is your suggestion related to a problem? Please describe.
Why ping me again?

#### Describe the solution you'd like.
Don't

#### Describe alternatives you've considered.
Global toggle for it

#### Additional context
#9070

**Comment by t3chguy** [comment]
Push Rules are calculated by clients & servers as per the spec 

This is https://github.com/matrix-org/matrix-doc/issues/2736

**Comment by ShadowJonathan** [comment]
@t3chguy id argue this is a valid issue, as this is related to reply fallbacks, in which then contains the username of the original user being replied to, etc.

**Comment by t3chguy** [comment]
Yes, perfectly valid, but it requires a spec change to resolve. Given that Element can't change it without being in breach of the spec.
