### ISSUE TITLE
Space home room tree seems to have regressed

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18250]
![Screenshot_20210727_084523](https://user-images.githubusercontent.com/25768714/127108391-a0eee05f-a89d-405f-9890-ac2fc4073f85.png)

**Comment by t3chguy** [comment]
Hmm, I cannot reproduce this on latest develop - is that space public so I could test it?

![image](https://user-images.githubusercontent.com/2403652/127150192-41015c51-d8fd-464f-9006-09768d230d53.png)

**Comment by SimonBrandner** [comment]
This doesn't happen always, I seem to be able to repro on develop with FF:

![Screenshot_20210727_140357](https://user-images.githubusercontent.com/25768714/127150438-ce32f2ff-d3e4-46c3-abbd-673e001f190d.png)

**Comment by t3chguy** [comment]
/me is using FF - will try that space
