### ISSUE TITLE
Images never loading after waking up laptop

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18252]
The last couple of days I've opened my laptop and there's been an image in the room element was open in that has arrived overnight, but it's just a blurhash and never loads. Switch rooms and back to the same room again makes it load.

**Comment by SimonBrandner** [comment]
Perhaps https://github.com/vector-im/element-web/issues/18243 ?

**Comment by novocaine** [comment]
@dbkr have you seen this lately?

**Comment by kittykat** [comment]
I'm going to close this issue for now as we can't reproduce it. Please reopen if it's still happening!

**Comment by Palid** [comment]
@kittykat this one's probably related to missing error handling and retires logic for images.
