### ISSUE TITLE
1px gap in edit UI

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18269]
#### Description

![image](https://user-images.githubusercontent.com/2803622/127171495-e0110921-552b-444c-9e37-025d64f21658.png)

Whatever is behind here shines through. Even worse, an image will shine through the green border of the input field.

#### Steps to reproduce

- edit

Logs being sent: yes/no

#### Version information

- desktop
- arch
- nightly 210727

**Comment by kittykat** [comment]
@HarHarLinks are you still seeing this?

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/149002333-fc0857c3-56ab-4311-b0f7-7ddea1d994c1.png)
freshly taken on https://matrix.to/#/#element-community-testing:matrix.org

**Comment by turt2live** [comment]
I'm not seeing this. If you are still seeing it, please open a new issue with fresh/new information.
