### ISSUE TITLE
PIP for portrait video calls is positioned off the screen

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18261]
It then slowly creeps back onto the page when you start to interact with it

**Comment by Palid** [comment]
Related: https://github.com/matrix-org/matrix-react-sdk/pull/6475

**Comment by SimonBrandner** [comment]
This is on me, we shouldn't animate when the windows size changes

**Comment by Palid** [comment]
@SimonBrandner pretty sure it's the same (or at least very similar) problem I have in the linked PR, wanna help with figuring this out? 😄

**Comment by SimonBrandner** [comment]
Already working on it :P

**Comment by ara4n** [comment]
for the sake of posterity, this bug looked like this:

<img width="506" alt="Screenshot 2021-07-27 at 13 47 49" src="https://user-images.githubusercontent.com/1294269/127220385-cb741f41-3175-431c-b33a-919da03a8a8a.png">
