### ISSUE TITLE
Links in replies are only clickable with a middle button click

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#18265]
Clicking a link with the left mouse click only makes Element jump in the timeline (a few messages later than the message being replied to):

![Peek 2021-07-27 14-44](https://user-images.githubusercontent.com/5547783/127164879-00ceab6c-79ee-4ad6-a42e-d8dc6ba5d4dd.gif)

Clicking with the middle mouse button (scroll wheel) works.

Observed on develop.element.io with Firefox 90.0.1

**Comment by t3chguy** [comment]
Please fill the issue template, the version you are running is critical here.

**Comment by babolivier** [comment]
As I said, I'm running what's currently on develop.element.io, so `1d54312c9f1f-react-f7d0419cee2c-js-e6d40f0c1732`.

I know that https://github.com/matrix-org/matrix-react-sdk/pull/6474 is applied on that version because middle mouse click wouldn't be working otherwise (it would just open the message in another tab, not the link)

**Comment by t3chguy** [comment]
You said

> Observed on develop.element.io with Firefox 90.0.1

but didn't say what time you loaded thus what version you are running 

thanks for responding with your version

**Comment by t3chguy** [comment]
@gsouquet this is running your code but seemingly not working

**Comment by babolivier** [comment]
> but didn't say what time you loaded thus what version you are running

Sorry, I was filling in this a bit quickly between other things and was a bit quick to reply as well. Sorry if my tone came out a bit aggressive.
