### ISSUE TITLE
can't copy links from replies any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18273]
i keep right-clicking on links in replies and copying to clipboard. except it copies the permalink to the reply, not the link i was trying to copy. surely links should take click priority over the permalink.

**Comment by dbkr** [comment]
I think this should also be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6487

**Comment by robintown** [comment]
Can confirm it's fixed, I'll assume @ara4n was filing against the RC or a nightly build unless he says otherwise
