### ISSUE TITLE
Create new room dialog disappears unintentionally

### ISSUE THREAD

**Issue by libexus** [vector-im/element-web#18275]
#### Description

When creating a new room and choosing the room type "Public Room" the dialog suddenly closes but then appears inside "Explore rooms"

#### Steps to reproduce

Edit: This happens only if you have no Space selected

- click on "create new room" from your room list
- try to change the room type to "Public Room"
- the dialog closes
- now open "Explore rooms"
- the dialog appears there (but you still can't create a public room)

#### Version information

develop.element.io on Firefox 90/Linux
Element version: `1d54312c9f1f-react-9707797d4576-js-a69d9a9f20b6`
olm version: `3.2.3`

**Comment by SimonBrandner** [comment]
I can repro the dialog crashing

**Comment by SimonBrandner** [comment]
![Screenshot_20210728_082859](https://user-images.githubusercontent.com/25768714/127274621-f173d5fe-69d9-4786-8c32-cb6bfa81088f.png)

Looks like a regression caused by spaces
