### ISSUE TITLE
Clicking on a pill in a reply opens the matrix.to link

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18283]
I would expect clicking on a user mention in a reply to just open their profile in the right panel, but instead it does that *and also* opens the underlying matrix.to link for the quoted event.

**Comment by gsouquet** [comment]
Could you elaborate a bit more on your setup?
Using Firefox, Chrome or Desktop I have not encountered that yet

**Comment by SimonBrandner** [comment]
I can repro on nightly
