### ISSUE TITLE
Registration explodes on grecaptcha

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#18284]
![image](https://user-images.githubusercontent.com/2403652/127462891-8b7945aa-2cd4-4e27-9a4d-72f790f170cb.png)

**Comment by dbkr** [comment]
same as https://github.com/vector-im/element-web/issues/12468 maybe?

**Comment by t3chguy** [comment]
`2020-02-21T19:03:53.025Z E undefined is not an object (evaluating 'this.props.stageParams.policies')`

that one looks to be policies rather than captcha
