### ISSUE TITLE
[UI] some bugs recent Commits

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#18280]
My small issue list for the Devs :) 

### Version / Branches
**Element-Web:** develop
**JS:** develop
**React:** develop

#### Settings
**Font-Size:** 17px

### Avatar cutted 
![image](https://user-images.githubusercontent.com/1436958/127355161-0e63b65c-9b2c-41fa-80cd-d30846b0d975.png)
### First letter hidden by Avatar sometimes like this 
![image](https://user-images.githubusercontent.com/1436958/127355430-18811ee6-15ea-4c8d-ba56-e7cd1b5b25d6.png)

### strange align left Events (is this normal???)
![image](https://user-images.githubusercontent.com/1436958/127355913-829e4283-aa73-459d-bba0-efae6a89ff6f.png)

### Bubble hover yellow ????
![image](https://user-images.githubusercontent.com/1436958/127355584-cca02b34-6d2a-413d-83ba-5b81b8c1b873.png)

**THX for this awesome Client!!!!** 💯 👍🏻 :)

**Comment by robintown** [comment]
@DoM1niC Are you sure you're running the latest version of develop? Most of those look like exactly like the regressions that were fixed last week (except for the final issue, which is a duplicate of https://github.com/vector-im/element-web/issues/18081)

**Comment by DoM1niC** [comment]
> @DoM1niC Are you sure you're running the latest version of develop? Most of those look like exactly like the regressions that were fixed last week (except for the final issue, which is a duplicate of #18081)

Ohhh ok? yes I see my Web seems ok now ... I'm on Desktop Client with my Fork so some seems not be cleared on the Cache side but you are agree the Bugs are not exist in the Webbrowser.... but THX for Feedback 👍🏻
