### ISSUE TITLE
`strictNullChecks` in tsconfig.json

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18286]
A ticket to gather the pull requests that are definitely failing right now.

https://github.com/vector-im/element-web/pull/18285
https://github.com/matrix-org/matrix-react-sdk/pull/6506
https://github.com/matrix-org/matrix-js-sdk/pull/1817

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21967

(closing in favor)
