### ISSUE TITLE
Message bubbles have no indication of sending state

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18298]
I can't believe I didn't notice this before, but it seems that message bubbles don't show the usual circle-with-checkmark sending state indicator. Is this intentional?

**Comment by daniellekirkwood** [comment]
![Screenshot 2021-12-07 at 12 24 46](https://user-images.githubusercontent.com/89144281/145028590-cf0816fd-8237-4dc6-946b-6eab449e8365.png)
![Screenshot 2021-12-07 at 12 24 18](https://user-images.githubusercontent.com/89144281/145028597-3a8ef4c8-dcab-44e0-b1ef-f838a44d7f6e.png)
![Screenshot 2021-12-07 at 12 23 30](https://user-images.githubusercontent.com/89144281/145028599-5d823f39-439f-4625-94f3-1afd6b806e3a.png)

**Comment by daniellekirkwood** [comment]
Needs designs/input from @amshakal 👍

**Comment by amshakal** [comment]
Mockup with send state. It has a 16px padding on the right

![98](https://user-images.githubusercontent.com/85162587/146594203-2744ae09-0ab8-42fc-b41c-0fd25235352e.png)
