### ISSUE TITLE
Timestamp overlaps membership event on hover in bubble layout

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18294]
![timestamp](https://user-images.githubusercontent.com/48614497/127515342-d802649d-7dd9-4952-bde3-47e247818a10.png)

**Comment by waclaw66** [comment]
Same problem here...
![obrazek](https://user-images.githubusercontent.com/15554561/129698442-bcf98c55-0131-4ff3-893b-46e3ab3adf26.png)

**Comment by kittykat** [comment]
Added to backlog for web app team because it's visually impactful

**Comment by robintown** [comment]
It's supposed to be on the left.

**Comment by janogarcia** [comment]
I've just checked the Message Bubbles mockups and those should be aligned to the left. Similar (put probably a sightly different gap) to what we're doing in production currently.

@amshakal Could you please confirm? 👍

![events](https://user-images.githubusercontent.com/60790/132021629-2c451548-384c-4a04-9492-a440a515a557.png)
![deleted](https://user-images.githubusercontent.com/60790/132021639-3dae5304-a0f0-4f0e-b4d7-d494e87843af.png)
