### ISSUE TITLE
1.7.33 crashes on Apple silicon

### ISSUE THREAD

**Issue by monochromec** [vector-im/element-web#18292]
Cf. https://github.com/vector-im/element-web/issues/18173 for the details. This surfaced after the recent upgrade to OSX 11.5.1 again.

https://gist.github.com/monochromec/706975e5a9fad8399be8c29b8799ab0c contains the crash dump. Interestingly, the time it seems to be a memory management issue on the ARM-native V8 indicated by the SIGABRT. 

Please let me know if more details are needed.

**Comment by aaronraimist** [comment]
I cannot reproduce on an M1 Mac with macOS 11.5.1 so this may be something specific to your configuration or account. Tested 1.7.33 (X86) and the latest nightly (ARM).

**Comment by monochromec** [comment]
Issue disappeared after downgrading to 1.4.7(#20210722123858) from the OSX App Store.

**Comment by aaronraimist** [comment]
Huh? 1.4.7 is the iOS version. The Desktop version is not in the App Store.

**Comment by monochromec** [comment]
Just search for Element in the App Store. Although it's the iOS version you can install and run this on OSX too. The look and feel is somewhat different but it has the advantage that it doesn't crash randomly due to a memory management issue.
