### ISSUE TITLE
Line breaks removed when message is one large markdown quote

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18299]
Sending:

```
> test
>
> test
```

results in a single line:
<img width="98" alt="Screenshot 2021-07-30 at 10 11 45" src="https://user-images.githubusercontent.com/986903/127630653-a63d6c68-9559-45ab-ad85-4a294bd8e5c4.png">

whereas obviously it should be one markdown quote with linebreaks in it

```
> test
>
> test

hi folks
```

...works as expected.

Probably very closely related to https://github.com/vector-im/element-web/issues/15320

**Comment by AgentOak** [comment]
Is this not a straightforward duplicate of #8786?

**Comment by SimonBrandner** [comment]
> Is this not a straightforward duplicate of #8786?

Yep, seems to be the case, thanks!
