### ISSUE TITLE
Showing avatar changes even though the setting is off in the preferences

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18308]
### Description
avatar changes are showing even though the setting is off in the preferences, I think this might be causing an even more annoying problem - marking these chats as unread messages and putting them on the top of the list.

https://user-images.githubusercontent.com/31655082/127734023-0b3fc0c9-2492-4fb5-89a5-86f782d889a8.mp4

### Steps to reproduce

- I think with double-puppeted bridged WhatsApp groups this happens

Logs being sent: yes

### Version information

- **Platform**: web (in-browser-pwa)
- **Browser**: Chrome - the newest version: Version 91.0.4472.77 (Official Build) (64-bit)
- **OS**: Windows
- **URL**: https://element.chagai.website, v1.7.33

**Comment by t3chguy** [comment]
Did you switch rooms away and back after changing the setting? I think it has an issue where already rendered rooms won't notice you changed the preference

**Comment by chagai95** [comment]
I'll have to check, will do soon

**Comment by kittykat** [comment]
@chagai95 Are you still seeing this issue?

**Comment by chagai95** [comment]
Still have to check..

**Comment by kittykat** [comment]
@chagai95 I will close this issue for now, please respond with @kittykat if you're still seeing it so that I can reopen it if needed :+1:
