### ISSUE TITLE
Avatar can overlap EventListSummary expand button in bubble layout

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18319]
![Screenshot 2021-08-01 at 12-02-22 Element kaise](https://user-images.githubusercontent.com/48614497/127777600-7ec3af6e-0107-46dc-a2b5-b6d8b5483f5a.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/146357094-43e9b4aa-f7de-4937-afcf-3be9717f90f4.png)

It no longer overlaps quite the same, but could in longer languages.
