### ISSUE TITLE
Self-joins appearing as '@travis:t2l.io joined the room' rather than 'TravisR joined the room' (and avatars in profile changes are wrong/missing)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18321]
The profile information is in the state event

**Comment by SimonBrandner** [comment]
I've also seen them not having an a avatar

**Comment by jryans** [comment]
Yes, avatars / profile info for state events seem to be frequently missing in the last few weeks... I swear there was a separate bug for that already... 😅

**Comment by ara4n** [comment]
This looks to be consistently broken.  Comparing app.element.io with nightly, i see:

app:
<img width="479" alt="Screenshot 2021-08-09 at 14 27 17" src="https://user-images.githubusercontent.com/1294269/128713839-8376b0a9-394b-4c26-ac6f-758e7ab9f5de.png">
develop:
<img width="559" alt="Screenshot 2021-08-09 at 14 27 06" src="https://user-images.githubusercontent.com/1294269/128713835-486c912c-04b2-4ff0-91ef-fe22a35a2b7e.png">

and

app:
<img width="381" alt="Screenshot 2021-08-09 at 14 27 21" src="https://user-images.githubusercontent.com/1294269/128713867-80a569e2-adc9-4a00-b849-f16b226ae5d6.png">
develop:
<img width="396" alt="Screenshot 2021-08-09 at 14 27 28" src="https://user-images.githubusercontent.com/1294269/128713862-e6503132-238e-4ac4-91ec-9899148eb6a9.png">

**Comment by dbkr** [comment]
Chronologically it looks like this most likely regressed with https://github.com/matrix-org/matrix-react-sdk/pull/6349/files but I don't yet see how

**Comment by dbkr** [comment]
Node, regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1765
