### ISSUE TITLE
Fails to import E2E room keys from RiotX (Trailer line not found)

### ISSUE THREAD

**Issue by JustinTArthur** [vector-im/element-web#18328]
#### Description

I'm trying to finally get rid of RiotX as it keeps indicating it has been deprecated in favor of Element. As I'm using a 3rd party homeserver, I'd prefer to use an out of band method of transmitting my E2E room keys, so I tried to use the import and export features of RiotX and Element Desktop. Element Desktop seems to have issues with the keys file though.

A similar issue was filed against the riot-android project (vector-im/riot-android#3479), but it was closed by @bmarty despite the problem still occurring.

#### Steps to reproduce
- With RiotX for Android, _Export E2E room keys_
- On Element Desktop, _Import E2E room keys_ using the file produced in the first step.

Instead of importing the room keys, the dialog indicates an error has occurred. Further details can be found in the DevTools log, which gives the following stacktrace:

```
    Error importing e2e keys: Error: Trailer line not found
        at MegolmExportEncryption.js:306
        at Object.l (MegolmExportEncryption.js:51)
        at ImportE2eKeysDialog.js:85
```

Attempts to import E2E room keys from Element Android on the same Android phone work without error.
Logs being sent: no

![image](https://user-images.githubusercontent.com/577312/127817970-5f563b50-e75e-42a4-8528-e04070983dc4.png)
![image](https://user-images.githubusercontent.com/577312/127818029-25f1a38c-9a91-4a9f-96c3-87e541cc4f2f.png)

#### Version information
Element version:
- **Platform**: desktop
- **OS**: macOS
- **Version**: 1.7.33 with olm 3.2.3

**Comment by lifetheater57** [comment]
@JustinTArthur Did you find a workaround?

**Comment by t3chguy** [comment]
Sounds like the format from RiotX is invalid. The input must look like

```
-----BEGIN MEGOLM SESSION DATA-----
...
-----END MEGOLM SESSION DATA-----
```

The error states that the END line is missing. I suggest opening an issue with whichever client generated that output.
