### ISSUE TITLE
Clicking on whitespace areas in replies takes you to matrix.to

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18327]
This happens if you click anywhere that's inside the reply tile `a` tag, but is not inside any of the `a` tag's children. This occurs on both modern and bubble layouts, though the hitbox is different for each since they lay out reply tiles slightly differently.

**Comment by ShadowJonathan** [comment]
This is expected behaviour, and there's been quite a bit of back-and-forth already with replies like this, please look at the other closed issues which introduced this, and explain why this is an issue instead.

**Comment by SimonBrandner** [comment]
> This is expected behaviour, and there's been quite a bit of back-and-forth already with replies like this, please look at the other closed issues which introduced this, and explain why this is an issue instead.

This is _not_ expected behaviour, you should not be sent to matrix.to when clicking a reply

**Comment by ShadowJonathan** [comment]
Oh, my apologies, I understood. Yes, that sounds like regressed behaviour.

@robintown Is this on web?

**Comment by robintown** [comment]
@ShadowJonathan Yep, on web

**Comment by ShadowJonathan** [comment]
Might be just a case of the `<a>` handler not being registered for replies as well (next to time stamps), should be easy to fix.

**Comment by SimonBrandner** [comment]
@robintown, do you still see this? I don't think I can repro

**Comment by robintown** [comment]
@SimonBrandner This still reproduces easily for me, by clicking inside the ReplyTile `a` but outside its children.

**Comment by SimonBrandner** [comment]
Ah, sorry, I can repro too

**Comment by SimonBrandner** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6487
