### ISSUE TITLE
"Verify session" request when there is only one session running

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18330]
#### Description

I have a test account that I've been using in a private browser session to validate issues. When I log in, I am asked to verify the session using another login. A dialog pops us waiting for me to do the verification and just sits there.

Assuming I understand correctly how sessions/session tracking works, the app should do a check to confirm if more than one session is running and if there is only one session, then should throw an error message instead.

On a random sample of ~1200 users, this issue could affect ~40% of them.

#### Steps to reproduce

- Use an account in a private browsing session
- End the session
- Sign into this account again

The second session asks me to verify it against another session. As I've only ever used private browsing, I don't have any other session running. This means that I cannot decrypt my messages from previous sessions.

This issue could affect anyone with only one session if they lose that session (e.g. caused by any other sessoin loss bug) so could be higher risk for people who are using Matrix for work and may not have a backup session running on another device.

Logs being sent: no

#### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: all
- **OS**: all
- **URL**: all

**Comment by SimonBrandner** [comment]
Closing per above
