### ISSUE TITLE
Tooling for cherry-picking fixes from develop to a release branch

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18332]
Currently it is a little bit painful to post fixes to a branched release.

It is typically necessary to create PRs both against the RC branch and the develop branch. Each requires separate approval.

We should consider how we might make this workflow faster. Although we may often require 2 separate PRs - as we need to run CI against both, and potentially separately review merge conflict resolutions etc - but perhaps some tooling for cloning PRs from one branch to another would be useful.

**Comment by t3chguy** [comment]
IMO it should be the other way around, an easy way to cherry-pick from develop to RC, we normally do the develop PR and then if that passes then the RC PR which would maintain the existing typical order of operations

**Comment by novocaine** [comment]
> IMO it should be the other way around, an easy way to cherry-pick from develop to RC, we normally do the develop PR and then if that passes then the RC PR which would maintain the existing typical order of operations

Amended the wording.

**Comment by t3chguy** [comment]
This happened with the `backport staging` label
