### ISSUE TITLE
client side url previews for e2ee

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18341]
#### Is your suggestion related to a problem? Please describe.
- People like rich URL previews.
- Server-generated URL previews break e2ee

#### Describe the solution you'd like.
client-side URL previews (at least for encrypted rooms)

#### Describe alternatives you've considered.
#10853

#### Additional context
https://github.com/vector-im/element-web/issues/16852#issuecomment-826981068

**Comment by t3chguy** [comment]
+ People don't like leaking their IP address
+ Browsers have to respect CORS so a lot of places won't allow url preview generation cross-site

**Comment by t3chguy** [comment]
Anyway, duplicate of https://github.com/vector-im/element-web/issues/2953
