### ISSUE TITLE
Debian repository reporting 1.7.35 available for update

### ISSUE THREAD

**Issue by E-werd** [vector-im/element-web#18345]
![Screenshot from 2021-08-02 17-11-56](https://user-images.githubusercontent.com/1765057/127924456-f65f99d8-c1fb-4c5c-8f5c-c31a5e767c7b.png)

#### Description

Debian repository is reporting element-desktop 1.7.35 to be available instead of 1.7.34 that was released today.

#### Version information

- element-desktop, Pop!_OS 21.04
- Upgrading from 1.7.33

**Comment by Dravere** [comment]
Can confirm. My distro tried to get it via here: https://packages.riot.im/debian/dists/default/main/binary-amd64/Packages

Clearly states the latest version is 1.7.35

**Comment by shirishag75** [comment]
Same here and then it isn't able to do anything about it. I even removed all and tried it all over again from  - 

https://element.io/get-started

```
$ sudo aptitude install element-desktop -y
The following packages will be upgraded: 
  element-desktop 
1 packages upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
Need to get 79.3 MB of archives. After unpacking 0 B will be used.
Err https://packages.riot.im/debian default/main amd64 element-desktop amd64 v1.7.35
  404  Not Found [IP: 104.26.4.138 443]
0% [Working]E: Failed to fetch https://packages.riot.im/debian/pool/main/e/element-desktop/element-desktop_v1.7.35_amd64.deb: 404  Not Found [IP: 104.26.4.138 443]
E: Unable to fetch some packages; try '-o APT::Get::Fix-Missing=true' to continue with missing packages
```
Also shouldn't the instructions change, it has been quite sometime now. Maybe have a new keyring with the name element,  and the same with the package archive. 

From https://element.io/get-started

```
sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list
```

**Comment by Asara** [comment]
From here: `https://packages.riot.im/debian/dists/bullseye/Release`
```Package: element-desktop
License: Apache-2.0
Vendor: support@element.io
Architecture: amd64
Maintainer: support@element.io
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, 
libsecret-1-0, libsqlcipher0
Recommends: libappindicator3-1
Replaces: riot-desktop (<< 1.7.0), riot-web (<< 1.7.0)
Breaks: riot-desktop (<< 1.7.0), riot-web (<< 1.7.0)
Homepage: https://element.io/
Priority: extra
Section: net
Filename: pool/main/e/element-desktop/element-desktop_v1.7.35_amd64.deb
Size: 79296900
SHA256: 3662eaf264bfbc6764ad1083d6dbe9d45987c69256f344a437248687711e623f
SHA1: 6239b0884a392f62faa55cf8f980ec166f702e9f
MD5sum: bdb82182d37411a3600b48c00cc3a263
Description: 
  A feature-rich client for Matrix.org
Version: v1.7.35
```

**Comment by DC7IA** [comment]
Noticed that, too. Really annoying as it breaks updates for the whole system except when the repo is disabled. Hopefully this gets resolved soon-ish. :/

**Comment by dbkr** [comment]
Sorry about this - I thought I fixed this this morning but now the rogue 1.7.35 has appeared again somehow.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
When Repo gonna fix though???

**Comment by dbkr** [comment]
Should be fixed now - thanks for the patience.
