### ISSUE TITLE
Docker image is creeping in size at a somewhat alarming rate

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18344]
About 500kb every release on average

**Comment by t3chguy** [comment]
This no longer seems to be happening

![image](https://user-images.githubusercontent.com/2403652/169897208-ba900574-4cb7-4088-86df-da422a97a4d9.png)
![image](https://user-images.githubusercontent.com/2403652/169897249-1bf8c4ad-c5ed-4676-abe3-457f61fb9a33.png)
![image](https://user-images.githubusercontent.com/2403652/169897276-8d0627ed-bdd7-40b5-8299-a0ea095d3a15.png)

Seems to scale with the app growing new features
