### ISSUE TITLE
Group panel says NaNB for notification counts again

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18343]

**Comment by t3chguy** [comment]
Groups/Communities are in maintenance mode and bugs will not be fixed given that replacing them with Spaces is just around the corner!

**Comment by turt2live** [comment]
@t3chguy we should probably fix this one unless there's a de-labs PR out. It's been around the corner for months.

**Comment by pferreir** [comment]
I guess I have the same issue? Is there a workaround?

![image](https://user-images.githubusercontent.com/2699/133752942-86592db5-f631-414c-8ea8-8a39483f6847.png)

**Comment by t3chguy** [comment]
Spaces is out of Labs in the next Release, Communities will be dropped in a future release. It is no longer maintained.
