### ISSUE TITLE
element-desktop freeze when open room with big ogg-files

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#18350]
Steps to reproduce:

1. send to room big ogg-files (20-40 mb) - count>10
2. open this room in element-desktop
3. see animations, which try download all "voices"
4. wait ~1 minutes
5. see white screen >5 minutes

In my situation - I have room with my bots, which was convert youtube links to ogg-voice and send this sound files to this room. I was listen this files at offline.
But today, when I select this room in element-desktop - I see this bug. I think this is because element-desktop try show preview for all this ogg-files. 

OS: ubuntu 20.04
version: element-desktop 1.7.33

**Comment by turt2live** [comment]
This is fixed in 1.7.34
