### ISSUE TITLE
Rooms sublist can get stuck 'scrolled off the top'

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18366]
The only workaround is to collapse and reexpand the sublist

**Comment by ara4n** [comment]
This is a recent regression from within the last week or so.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/1294269/128046862-574507d3-65db-4f51-9ebc-291d6ce30294.png">

**Comment by novocaine** [comment]
@turt2live speculates this might be message bubble related:

> it feels related to message bubbles, awkwardly. There was a point where the default avatars were cut off a bit, leading to unexpected room list jumps. Might be a consequence of that fix

**Comment by ara4n** [comment]
<img width="356" alt="Screenshot 2021-08-03 at 17 05 31" src="https://user-images.githubusercontent.com/1294269/128049115-be283566-9a25-4a58-ab45-c4c01403153b.png">

**Comment by ara4n** [comment]
^ is the correct layout, having kicked it.

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
