### ISSUE TITLE
looks like we normalise the voice msg waveform amplitude on Web but not iOS

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18364]
if you record a near-silent message on iOS, it gets sent with a nice small waveform. But then on Web the same waveform is maaaaaaaaaassive because something has incorrectly normalised it.

**Comment by ara4n** [comment]
iOS:
![image](https://user-images.githubusercontent.com/1294269/128044295-09ad5b6a-30a1-4fe7-a678-564992a4b5be.png)

Web:
<img width="381" alt="Screenshot 2021-08-03 at 16 36 16" src="https://user-images.githubusercontent.com/1294269/128044212-7bd96043-e7f7-4f8b-b8f1-c348197e1f59.png">

**Comment by turt2live** [comment]
we should just take out the rescaling
