### ISSUE TITLE
Top of reaction picker can fall off the top of the screen

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18377]
#### Description

With messages a certain distance from the top, the top of the reaction picker can be off the top of the screen. Looks like the reaction picker is taller than it's expecting it to be?

<img width="477" alt="Screenshot 2021-08-04 at 10 52 53" src="https://user-images.githubusercontent.com/986903/128161701-cc2b685f-88d9-4502-a409-348c7c5dd057.png">

#### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

desktop nightly

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/17527

**Comment by robintown** [comment]
(To repro, your window has to be vertically short)
