### ISSUE TITLE
searching encrypted messages on the desktop app seems to not work anymore

### ISSUE THREAD

**Issue by autoteelar** [vector-im/element-web#18373]
i cant seem to search anymore it provides 0 results in encrypted chats, i searched for an existing issue but couldnt find one so if one already exists my bad couldnt find it.

it also says Use the Desktop app to search encrypted messages, even though im already using the desktop app

**Comment by robintown** [comment]
What platform are you on, and how are you installing Element Desktop?

**Comment by SimonBrandner** [comment]
If you go to Settings -> Security & Privacy -> Message Search, you can see if there are any errors there

**Comment by autoteelar** [comment]
ill check thanks, i am using void so i installed it through XBPS package manager,  element-desktop-1.7.30_1 is the latest version as of writing this message 

alrighty i checked it and got this,
Message search
Message search initialization failed

Advanced
Error opening the database: DatabaseUnlockError("Invalid passphrase")

maybe im doing something wrong or just missing something? i never got promted to enter my passphrase before but i do know it

**Comment by autoteelar** [comment]
theres a red reset button, maybe i could try pressing that? says i most likely do not want to reset event store but maybe its a good idea since it isnt working for me currently?

**Comment by aaronraimist** [comment]
Yes you should reset it.

The actual latest version is 1.7.33 which should contain the fix for the confusing error message telling you to use the desktop app when you are already on the desktop app.

**Comment by autoteelar** [comment]
ah ill try downloading that version, it doesnt seem to be in the void repos so ill just get it here ^^ i did reset it and it seemed fine and said it was working, but after a while it reoccurred, i will try on the later up to date version

**Comment by dbkr** [comment]
going to assume this worked since we haven't heard anything for a while

**Comment by autoteelar** [comment]
yea sorry i dont really use git often ^^ it seemed to have worked ^^ sometimes i have to do it again and wait and its a little buggy but its working kind of
