### ISSUE TITLE
"Explore public room" doesn't load (TypeError: e.instances is undefined)

### ISSUE THREAD

**Issue by alvinhochun** [vector-im/element-web#18378]
#### Description
When trying to list public rooms, the "Explore rooms" overlay doesn't load. Error "Uncaught (in promise) TypeError: e.instances is undefined" is reported on the console.

#### Steps to reproduce

- Press the "+" sign next to "Rooms"
- Press "Explore public rooms"
- Check dev tools console

The "Explore Rooms" overlay stays loading indefinitely and an error is logged on the console.

Log: not sent

![圖片](https://user-images.githubusercontent.com/2397650/128178087-69a28a63-4e94-4990-bf21-29584754ee4e.png)

#### Version information

- **Platform**: web
- **Browser**: Firefox 91 (beta channel)
- **OS**: Windows 10
- **URL**: both develop.element.io and webchat.kde.org

**Comment by t3chguy** [comment]
Your server's response is illegal based on the matrix spec which says `instances` is a required field

This is a Synapse issue https://github.com/matrix-org/synapse/issues/9694

**Comment by alvinhochun** [comment]
Okay, so what can I do now since this is happening with the kde.org homeserver?

**Comment by t3chguy** [comment]
Normally I'd suggest to get in touch with the KDE team responsible, so they can open a support ticket with EMS. But I have raised this internally with EMS now.

**Comment by Half-Shot** [comment]
We're on the case.

**Comment by Half-Shot** [comment]
This will be fixed in Synapse v1.41.0
