### ISSUE TITLE
Replying to a message make links in original messages unclickable

### ISSUE THREAD

**Issue by moritzdietz** [vector-im/element-web#18374]
#### Description

With the new release of Element, messages containing a link which are being replied to have the problem that the links aren't clickable anymore.

Depending on the intent of the change in the new reply code, this might be a regression.
Here is a video demo:

https://user-images.githubusercontent.com/7935536/128070325-d163cadd-650c-409f-b913-0d5f2f2f29be.mov

#### Steps to reproduce

- Send a message in a room containing a link
- Reply to this message with a new message
- Try clicking the link from the original message you have replied to
- This won't work anymore

Describe how what happens differs from what you expected.

Logs being sent: yes/no

#### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.7.34 (1.7.34)

**Comment by moritzdietz** [comment]
Maybe this needs to be moved to the sdk repo, but I'm not sure.

**Comment by SimonBrandner** [comment]
Fixed on develop.element.io, will be in the next release
