### ISSUE TITLE
Error: Attempt to postMessage on disconnected port while calling?

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18379]
![Screenshot_20210804_142513](https://user-images.githubusercontent.com/25768714/128180614-55272eef-8508-4086-a680-d446e5fb04a9.png)

Browser: Firefox
Element version: develop.element.io

**Comment by SimonBrandner** [comment]
This happens while I am in a call which is super weird and I can't see a single reason why

**Comment by gsouquet** [comment]
Thank you for your report. It would be good to have a bit more information regarding the impact of that issue so that we can assign it a proper priority. Could you edit your issue to include replies to all sections in the template.

**Comment by SimonBrandner** [comment]
Ok, it seems that this is somehow specific to my FF? Let's close this since it doesn't seem to have much to do with our code
