### ISSUE TITLE
Pop out menu in PIP is in a random location

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18382]
#### Description

Assuming that the ellipsis menu is there for fancy future features, I would expect the menu that pops to to not be somewhere random.

#### Steps to reproduce

- Start a call
- Navigate to another room [call minimises to a "PIP" window]
- Click the … button in the "PIP" window

When the "PIP" window is top right or bottom right, I get this:

![Screenshot from 2021-08-04 15-24-14](https://user-images.githubusercontent.com/51663/128198604-1ecf4db4-07e0-45e1-8cfb-671d4087389c.png) ![Screenshot from 2021-08-04 14-53-52](https://user-images.githubusercontent.com/51663/128198607-96efead1-9e3c-4d4c-8bea-3c3760c25166.png)

When it is top left or bottom left, the … button doesn't do anything at all

Logs being sent: no

#### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium Version 92.0.4515.107 (Official Build)
- **OS**: Arch Linux (64-bit)
- **URL**: develop.element.io

#### Acceptance criteria for fix

- [ ] Menu overlay behaves in a consistent way

CC: @afranke

**Comment by afranke** [comment]
Can confirm on Firefox 90.0.2, Fedora 34, develop.element.io.

Looks fine on app.element.io (where the button still have a slightly different layout).

**Comment by SimonBrandner** [comment]
Perhaps regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6496

**Comment by SimonBrandner** [comment]
> Perhaps regressed by [matrix-org/matrix-react-sdk#6496](https://github.com/matrix-org/matrix-react-sdk/pull/6496)

Yeah, looks fine when the context menu isn't mounted as a child

**Comment by anoadragon453** [comment]
Indeed - thanks for reporting! I've put up a PR to fix this at https://github.com/matrix-org/matrix-react-sdk/pull/6552.
