### ISSUE TITLE
Custom notification sound file upload visible in room settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18392]
It's supposed to be managed by the buttons

**Comment by daniellekirkwood** [comment]
<img width="671" alt="Screenshot 2023-08-15 at 17 20 28" src="https://github.com/vector-im/element-web/assets/89144281/ecc0b439-f8f1-49d5-b44d-2b671823522d">

This is as designed. Give or take some Compound tweaks. 

@turt2live I don't follow your ask but I think it's covered as you can control the sound of a room using the buttons. I'll close this but re-open if you have more details to add and my understanding is not correct.

**Comment by t3chguy** [comment]
Pretty sure this is an old regression actually
