### ISSUE TITLE
Jumping to red-highlighted text is broken

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18397]
The jump goes way too low and sometimes just doesn't show you the context, it also doesn't hold the scroll position properly.

Update: It seems that it no longer jumps too low, but that the scroll position is now broken - it first jump to the top of the page, then back to where it should be and if you try scrolling it does the same thing again. That's not really a good experience.

Video proof: 

https://user-images.githubusercontent.com/3636685/128262050-2e8f326f-4a7e-46b7-9eb6-b99744d83bbf.mp4

Client: https://app.element.io
System: MacOS Big Sur 11.4 (20F71)
Browser: Firefox 90.0.2 (64-bit)

**Comment by MaxSchwalbe** [comment]
It seems something else goes strange with highlighted messages: I get mentions in red with desktop client only, can't be been with android client. And sometimes, the mention batch is just highlighted red (or rather brown in dark mode), and sometimes, the font is red as well. Is that a bug or a feature I do not understand? ^^

**Comment by robintown** [comment]
The jump after scrolling away was solved, the remaining bit is https://github.com/vector-im/element-web/issues/21585
