### ISSUE TITLE
Consider putting the pinned messages button under room info

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18402]
The row of buttons in the top right is slowly growing a bit overwhelming. Since pinned messages open up in the right panel and seem to fall semantically under "Room Info", could the button just be placed there alongside members and files?

**Comment by t3chguy** [comment]
You'd miss the red dot which tells you that you have unread pinned messages then though

**Comment by robintown** [comment]
Yeah, this doesn't make sense to me anymore.
