### ISSUE TITLE
Use new issue forms instead of templates for bugs

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18419]
GitHub have introduced forms for issue creation. We should use them because they're more structured. This is what our issue creation forms could look like.

On the new issue page:
![Screenshot from 2021-08-06 08-56-37](https://user-images.githubusercontent.com/51663/128477679-267ce84d-b5a8-48bd-ab25-48f568c64f8a.png)

For browser version:
![Screenshot from 2021-08-06 08-57-54](https://user-images.githubusercontent.com/51663/128477674-e8b81096-6fe9-42a1-8d82-337d9ab61f6f.png)

For desktop version:
![Screenshot from 2021-08-06 09-24-39](https://user-images.githubusercontent.com/51663/128480871-2bbe9062-93e4-4aa8-8c82-8f0169e9c4f3.png)

See #18420

**Comment by t3chguy** [comment]
For desktop, where they installed it from is also vital. Given that our Ubuntu/Debian repos are first party, but if someone is using say the third party Flatpak, they may encounter different bugs due to that packaging.

**Comment by kittykat** [comment]
Makes sense, updated (see screenshot above)
