### ISSUE TITLE
Voice messages: "stop recording" layout shift

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18416]
From Nad at https://github.com/matrix-org/matrix-react-sdk/pull/6530#issuecomment-891673615 :

It's a shame that when stopping recording the entire layout re-shuffles and your eye has to re-read the layout to know what happens:

<img width="379" alt="Screenshot 2021-08-03 at 09 50 18" src="https://user-images.githubusercontent.com/4626865/127988507-b2b3ba27-01d7-4edd-bae4-b41b21ec52b6.png">
<img width="432" alt="Screenshot 2021-08-03 at 09 50 13" src="https://user-images.githubusercontent.com/4626865/127988513-23dbb6bb-d02e-440f-afb5-4e5006fb811b.png">

Is there a simple way to re-arrange the interactions to avoid this?

**Comment by gaelledel** [comment]
@turt2live To solve the issue we could try to place the STOP button on the left of the player instead
so it'd be from the left to the right: Delete, Stop, Player, Send button. Let's review together when you're ready
