### ISSUE TITLE
FilePanel doesn't paginate any more in E2EE rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18415]
It shows however many files that are already loaded in the timeline, but shows an infinispinner at the top rather than pulling in additional older files

**Comment by kittykat** [comment]
Not convinced I can reproduce in Element version: 1.7.34, olm version: 3.2.3. If I scroll right as far back as I can (to 2017, I'm not sure if there are any older files), I don't get the infinispinner even though most of the files in the history aren't loaded in the timeline. I do get a blank area though:
![Screenshot from 2021-08-11 14-00-17](https://user-images.githubusercontent.com/51663/129034634-206d7660-d755-4c61-ad56-c78f166b1b79.png)

I can also get an empty FilePanel if I scroll up and down too fast, might be related? :
![Screenshot from 2021-08-11 14-01-52](https://user-images.githubusercontent.com/51663/129034820-af014802-418f-4edb-9cc6-603d52f9edb0.png)

@gsouquet can you reproduce?

**Comment by ara4n** [comment]
It's definitely inconsistent to reproduce, but i swear i can.  Right now repro is made hard by (in element nightly desktop) it taking about 10s to paginate each chunk of filepanel contents. Obviously it should be instant given it can query the local sqlcipher db.  In fact, it looks to be completely stuck now, tight-looping on:

```
rageshake.js?432e:65 TypeError: Cannot read property 'eventIdToTimeline' of undefined
    at eval (webpack-internal:///240:715)
    at Array.forEach (<anonymous>)
    at EventIndex.populateFileTimeline (webpack-internal:///240:714)
    at async paginationMethod (webpack-internal:///240:767)
    at async Promise.all (://vector/webapp/index 0)
    at async ScrollPanel.eval [as checkFillState] (webpack-internal:///1210:206)
```

will rageshake.

<img width="377" alt="Screenshot 2021-08-12 at 22 18 20" src="https://user-images.githubusercontent.com/1294269/129271367-11a472bd-ad45-4011-9111-9443ec61c3e8.png">

**Comment by SimonBrandner** [comment]
This is caused by the fact that we're accessing `_timline` on https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndex.ts#L863. This doesn't exist anymore and it is private now
