### ISSUE TITLE
Image thumbnail placeholders don't show in compact IRC mode

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#18411]
In the compact IRC view, placeholders for thumbnails are no longer shown.  If an image is posted, an empty message appears - and with no way to open or download the original image either.

**Comment by Biep** [comment]
Hmm - I can't edit the title.  I meant "Image thumbnail **placeholders**".

**Comment by gsouquet** [comment]
@Biep thank you for raising this issue.

Could you maybe give a little more information regarding your setup (browser, OS, ...) and maybe send a little clip showcasing the issue you're facing?

I have not been able to reproduce the issue on my setup so far and further info would definitely help with the investigation

**Comment by t3chguy** [comment]
IRC mode is still experimental, not Critical

**Comment by Biep** [comment]
I have Ubuntu 20.04, with Element Desktop 1.7.34 from the standard repo.
Dark theme; font size set to 13.
Compact 'Modern' lay-out (greyed out but selected); compact IRC lay-out.
Automatically play GIFs and videos is off; Show thumbnails is off.

This used to show a placeholder with an eye symbol (clickable to show the thumbnail), and a download link underneath.  Now neither shows.

Here is what I see now in a room where @xkcd:maunium.net posts.
![image](https://user-images.githubusercontent.com/12461597/128594724-8c4dbe96-f9e1-4b3d-b42b-238f37d08d73.png)

**Comment by Biep** [comment]
I switched IRC mode off, but that only made it worse:
![image](https://user-images.githubusercontent.com/12461597/128630443-5d683768-ff42-48e6-9a73-d242c2015a32.png)
So **this** - not the experimental mode - would be critical, I suppose.

**Comment by Biep** [comment]
(I see it is both S-Major and S-Minor now..)

**Comment by gsouquet** [comment]
Interesting, I have not heard about this issue, nor am I able to reproduce it.
For my ease of mind, could you have a look at your settings and confirm that "Show preview/thumbnails for images" is switched on?
You'll find that setting under "Settings > Preferences > Images, GIFs and videos"

**Comment by Biep** [comment]
I don't want to view thumbnails by default (which would cost too much data).  I just want the placeholder there, zo that when I am on a WiFi connection I can click on the placeholder to see the preview.
![image](https://user-images.githubusercontent.com/12461597/128699586-dfa98ecc-5982-46cb-9317-2bc515e84ab4.png)
See the example from #Strips:matrix.org - the partial image at the top is one that appeared when I clicked on the placeholder.  For the latest images there is no placeholder to click on, so I cannot make the preview visible.

**Comment by Biep** [comment]
I don't want to view thumbnails by default (which would cost too much data).  I just want the placeholder there, zo that when I am on a WiFi connection I can click on the placeholder to see the preview.
![image](https://user-images.githubusercontent.com/12461597/128699586-dfa98ecc-5982-46cb-9317-2bc515e84ab4.png)
See the example from #Strips:matrix.org - the partial image at the top is one that appeared when I clicked on the placeholder.  For the latest images there is no placeholder to click on, so I cannot make the preview visible.

Oh - wrote this, but then forgot to click the "Comment" button, so it was never posted.  Sorry!
(And by the way - would a rageshake help?

**Comment by Biep** [comment]
..and now it shows twice, so it was posted after all..

**Comment by Biep** [comment]
I unchecked both compact lay-outs (Modern and IRC), and got the following, which may give you some info:
![image](https://user-images.githubusercontent.com/12461597/129493288-b899d08f-154a-4b66-85c8-3082a8450e34.png)
As you see, the time stamp of the first message (the image, I presume) is there, though almost hidden behind the time stamp of the second message (the "caption").
I certainly hope this helps, because it is quite annoying not being able to see any images at all..

**Comment by Biep** [comment]
I am on 1.8.0 now, and the problem is gone - the placeholders are back.
Thanks for wittingly or unwittingly repairing the bug!
