### ISSUE TITLE
Dragging PiP from the avatar goes back to room on drop

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#18421]
#### Steps to reproduce

- Start a video call in your 1-1 room with Alice
- Switch to any other room from the sidebar. Video call is overlaid (PiP) in one of the corners.
- Move your mouse over Alice’s avatar in the header of the PiP.
- Click and start dragging the PiP.
- Wait for it to catch up to your mouse position. Drop the PiP (release mouse button).

Expected: the PiP behaves like it would if I had dragged from any other draggable part of it
Actual result: Element switches to Alice’s room, as if I had clicked on the avatar or the top right icon.

#### Version information

- **Platform**: web
- **Browser**: Firefox 90.0.2
- **OS**: Fedora 34
- **URL**: develop.element.io

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/15920

**Comment by SimonBrandner** [comment]
@gaelledel, do you have any thoughts on how clicking/dragging different parts of the PiP should behave? Also, in connection with https://github.com/vector-im/element-web/issues/15920

**Comment by gsouquet** [comment]
After testing on both Chrome and Firefox I could see a UI defect on Firefox, however I have not been able to reproduce following the provided steps

Could you try again and maybe share a little film-strip of the problem you're experiencing? 

<table>
<tr>
	<td>Firefox
	<td>Chrome
<tr>
	<td>
<img width="430" alt="Screen Shot 2021-08-06 at 12 19 43" src="https://user-images.githubusercontent.com/769871/128497036-cce76635-d902-4b23-ac63-75aa7ccc6568.png">

	<td>
<img width="396" alt="Screen Shot 2021-08-06 at 12 19 54" src="https://user-images.githubusercontent.com/769871/128497055-02b8f244-13c9-43a1-a84d-dab8930ea9d7.png">

</table>

**Comment by SimonBrandner** [comment]
I can repro on FF: 

https://user-images.githubusercontent.com/25768714/128499302-c3baf7e2-05ea-4220-80ac-dd6313acb9a7.mp4

**Comment by jryans** [comment]
I don't think this one needs Design, seems fairly straight forward to me.
