### ISSUE TITLE
Space room directory header text out of sync with list content

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18427]
### Steps to reproduce

1. Go to space settings
2. Add a subspace
3. Remove the created subspace

### What happened?

The subspace has been correctly removed, the list below is empty but the list header text is not matching the reality anymore

<img width="947" alt="Screen Shot 2021-08-06 at 15 17 29" src="https://user-images.githubusercontent.com/769871/128516459-38438033-ecb5-48b1-a6a6-0fe86aaa7d77.png">

### What did you expect?

Moving away from the space settings and coming back displays the correct caption '0 rooms'

### Operating system

macOs

### Application version

Nightly

### How did you install the app?

Homebrew

**Comment by t3chguy** [comment]
That heading might be going away as its not going to be possible with the way the pagination will work
