### ISSUE TITLE
Skinning doesn't work if trying to actually use the react-sdk in the skin

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18430]
Overriding a component with uses another component from the react-sdk causes errors relating to components not being registered due to the import order. The workaround is to use `sdk.getComponent()` inline (and `require()` for the obscure cases), but this is obviously not great. 

We should see if the SDK load order can be improved, possibly opening up the ability to extend react-sdk components rather than override them wholesale.

**Comment by t3chguy** [comment]
This got fixed
