### ISSUE TITLE
Explore public rooms loads forever

### ISSUE THREAD

**Issue by skepticalwaves** [vector-im/element-web#18432]
### Steps to reproduce

1. Where are you starting? What can you see?
2. 
Open explore public rooms.

![image](https://user-images.githubusercontent.com/66973897/128529914-24e7a509-7c9f-4f86-bebc-7d5e7016f2ed.png)

2. What do you click?
Explore public rooms

3. More steps…

### What happened?

Loads forever

### What did you expect?

To be able to browse public rooms

### Operating system

Ubuntu

### Browser information

Brave Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)

### URL for webapp

Private, element version v1.7.34 via official docker

**Comment by t3chguy** [comment]
Check your logs. There is likely an error from your server sending an illegal response. A future Synapse release will resolve that illegal response.

**Comment by t3chguy** [comment]
Browser console

**Comment by skepticalwaves** [comment]
![image](https://user-images.githubusercontent.com/66973897/128530822-a4adb0d4-0638-4512-b061-dd18db5655e4.png)

**Comment by t3chguy** [comment]
Yup, your server is missing the requires `instances` field - https://github.com/matrix-org/synapse/issues/9694

**Comment by skepticalwaves** [comment]
Is there an element bugfix that will make it a little more forgiving of this?

**Comment by t3chguy** [comment]
Nope, the closest would be an error state in this instance, but missing fields which are required in the spec yield undefined/error behaviour.
