### ISSUE TITLE
Hovering over a mention pill in a message hides the timestamp

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18447]
but the hover state for the tile is otherwise maintained.

**Comment by psrpinto** [comment]
![Screen Recording 2021-09-02 at 17 21 06](https://user-images.githubusercontent.com/550401/131881173-e1f6464c-38f2-40e9-8df1-881c8ec2df02.gif)

**Comment by SimonBrandner** [comment]
I don't think I can repro.. Could you please provide a bit more info on how to repro this?

**Comment by turt2live** [comment]
The gif shows the timestamp going away with the hover.

**Comment by SimonBrandner** [comment]
It doesn't for me

**Comment by SimonBrandner** [comment]
https://user-images.githubusercontent.com/25768714/132092386-396d7507-47c5-4afb-892f-ae2b50751f09.mp4

**Comment by turt2live** [comment]
Looks like you have "always show timestamps" on, so it wouldn't do that :)

**Comment by SimonBrandner** [comment]
Ah, that's it! Thanks

**Comment by yaya-usman** [comment]
@gsouquet @turt2live it seems this issue has been fixed, because i couldn't reproduce the issue even when "always show timestamps" is off or on
