### ISSUE TITLE
Upon joining a room in bubble layout, all display names are hidden

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18448]
# Steps to reproduce

* Activate bubble layout
* Join a room that has more than 2 members, #networking:nixos.org](https://matrix.to/#/#networking:nixos.org)
  
# What happened?

This is the lack of display names that I saw upon joining [

![Screenshot 2021-08-07 at 21-36-51 Element NixOS Networking](https://user-images.githubusercontent.com/48614497/128618033-da3144cf-12eb-40e4-9617-61553113a115.png)

# What did you expect?

To see the Sender's name

# More context

Switching back and forth between rooms solved the problem.

# Operating system

All

# Browser information

All

# URL for webapp

app.element.io

**Comment by t3chguy** [comment]
Uploading Screen Recording 2021-12-17 at 14.42.59.mov…

Cannot reproduce this.
