### ISSUE TITLE
Disable matrix.to links based on "permalinkPrefix" config.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#18459]
It is a relatively common ask for people running dedicated instances of Element connected to unfederated instances to disable the links to matrix.to.

We already allow admins to _change_ the matrix.to provider via the "permalinkPrefix" option in `config.json`. Would it be possible/appopriate to suppress the UX entirely using the same/a similar option?

It appears in two places:

Room details, right hand panel:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/1922197/128719748-b3ecf449-345e-4259-9915-2029c67cf555.png">

Invite dialog:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1922197/128719811-d3c09d72-8443-4edc-9294-137db2c3b19b.png">

**Comment by turt2live** [comment]
This is being considered in other places, I believe. Currently it's not technically feasible with the hundreds of code sites, but may be possible if determined enough to make it happen.
