### ISSUE TITLE
Phantom call notifications(?)

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18454]
### Steps to reproduce

Nor reliably reproducebale

### What happened?

We're getting reports of users being in a 1:1 call, hanging up, and then 10 minutes later the other party claims they had another incoming call from them.

### What did you expect?

No phantom calls

**Comment by dbkr** [comment]
Another report suggests this is happening whenever element ios is opened after a call, showing each user that the other is calling them, so it's possible this could actually be am element-ios bug.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/4607
