### ISSUE TITLE
Stopping the camera whilst screensharing does not turn the webcam LED off on my mac

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18456]
### Steps to reproduce

1. Start a VoIP call with camera on
2. Start screensharing
3. Stop camera

### What happened?

Camera has stopped, but the "green" LED that indicate that the webcam is active is still on

### What did you expect?

I would expect that LED to switch off and the camera to stop recording

### Operating system

macOs

### Browser information

Chromium Version 92.0.4515.131

### URL for webapp

app.element.io / Element Desktop

**Comment by SimonBrandner** [comment]
AFAICT, this has nothing to do with screen-sharing. This is a general regression

**Comment by SimonBrandner** [comment]
Oh no, this isn't a regression, this is a general Chromium issue

**Comment by SimonBrandner** [comment]
This is an upstream issue, see https://bugs.chromium.org/p/chromium/issues/detail?id=642785

**Comment by gsouquet** [comment]
After discussing with Simon, it turns out this is a compatibility issue where disabled stream keep the LED turned on.
Other vendors can potentially remove the video track altogether but this was decided otherwise in Matrix as part of the MSC process, view matrix-org/matrix-doc#3291

Closing as this is already tracked on Chromium's issue board bugs.chromium.org/p/chromium/issues/detail?id=642785
