### ISSUE TITLE
User should never see the UI as if they are in a deleted space after it has been deleted

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18455]
### Steps to reproduce

1. Log in to your account on two devices (one web)
2. Create a space and open it in the webapp
3. Leave the space from the other device
4. Close the webapp
5. Open the same webapp

### What happened?

The view is showing me the deleted space with empty people/room lists

![Screenshot from 2021-08-09 10-11-16](https://user-images.githubusercontent.com/51663/128699400-fc0cc27f-76ae-4da4-8e4b-89c7059d86df.png)

### What did you expect?

The view on my webapp to open in the home space

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131

### URL for webapp

app.element.io

**Comment by t3chguy** [comment]
> Delete the space from the other device

Not sure what you mean by this, deletion of rooms is not really possible in Matrix by a user, only by server admins

**Comment by kittykat** [comment]
> Not sure what you mean by this, deletion of rooms is not really possible in Matrix by a user, only by server admins

Updated instructions, you have to be an admin for the space

**Comment by t3chguy** [comment]
> Updated instructions, you have to be an admin for the space

I still just see

> Delete the space from the other device

![image](https://user-images.githubusercontent.com/2403652/128707215-5620a69c-0b9d-4a51-8a65-42bd29ae532a.png)

**Comment by kittykat** [comment]
Right, leave the space, not delete it

**Comment by t3chguy** [comment]
This is likely not specific to spaces then, and is behaviour we inherit from rooms.
