### ISSUE TITLE
Use GitHub actions layered build output to run the e2e tests

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18453]
#### Is your suggestion related to a problem? Please describe.

CI builds element-web for both Netlify and again when running the end-to-end tests

#### Describe the solution you'd like.

Piggy back off matrix-org/matrix-react-sdk#6575 output to run the e2e tests rather than rebuilding element-web from scratch to shave off precious minutes in our CI

#### Describe alternatives you've considered.

N/A

#### Additional context

N/A

**Comment by t3chguy** [comment]
This happened with Cypress
