### ISSUE TITLE
Message search result not able to match characters in the middle of the sentence. 

### ISSUE THREAD

**Issue by Narakuku** [vector-im/element-web#18457]
### Steps to reproduce

1. Click the Search bar in any room.
2. Searching for any keywords in the middle of the sentence of the chat history.

### What happened?

The search result does not show any result if the keyword is in the middle of the sentence.

<img width="465" alt="22" src="https://user-images.githubusercontent.com/74468372/128712799-d16d151f-d42a-4c97-bdd6-61ad9ba04591.png">
<img width="424" alt="11" src="https://user-images.githubusercontent.com/74468372/128712810-194609e8-6828-4cdb-8b73-01982948b225.png">

### What did you expect?

Able to search any keywords of the chat history.

### Operating system

Any

### Browser information

Chromium Version 92.0.4515.131

### URL for webapp

app.element.io

**Comment by t3chguy** [comment]
The search is performed by your matrix server

**Comment by gsouquet** [comment]
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously - see #14018. I'm going to close this issue now so we can focus on #14018. Please watch, vote or comment there if there is any additional information you can provide.
