### ISSUE TITLE
Element Web unconditionally accesses `threepids`

### ISSUE THREAD

**Issue by ahmedcharles** [vector-im/element-web#18469]
### Steps to reproduce

Have a homeserver return `{}` from `GET /_matrix/client/r0/account/3pid`.

### What happened?

Element unconditionally accesses `threepids` in the response. This results in notification settings being inaccessible.

### What did you expect?

It shouldn't fail when `threepids` isn't in the response.

### Operating system

Debian

### Browser information

Firefox 78.12.0esr (64-bit)

### URL for webapp

app.element.io

**Comment by turt2live** [comment]
I think this is a spec issue where a field is unintentionally marked optional.
