### ISSUE TITLE
Creating new room in a Space doesn't show up under Rooms

### ISSUE THREAD

**Issue by oxr463** [vector-im/element-web#18465]
### Steps to reproduce

1. Where are you starting? What can you see?

![image](https://user-images.githubusercontent.com/43783393/128746177-4206bf59-22fd-4271-8e9e-e777c009189c.png)

2. What do you click?

> Create new room

### What happened?

Instead of the new room showing up in my space under Rooms, I could only see it under All rooms -> Rooms:

![image](https://user-images.githubusercontent.com/43783393/128746466-088faa36-3e95-48f5-90cd-42a881fecf96.png)

The two "Technical" rooms under Historical were the rooms I had problems creating.

### What did you expect?

I expected the room to show up under Rooms in my space, but it never did.

As a workaround, I went into the Element Android App on my phone and created a room in my space. Then I refreshed the Web App and I could see it properly.

### Operating system

Pop!_OS 21.04

### Browser information

Firefox 90.0

### URL for webapp

https://app.element.io

**Comment by t3chguy** [comment]
Can reproduce, regression from https://github.com/matrix-org/matrix-react-sdk/commit/eb9f4c609a22c8493c9021d20958ccdf4286529c#diff-89268874351e08a327e47b0a7e1d4e916e1ad8dc4be8b4a3f1ef67f3f83a5bc9R124
