### ISSUE TITLE
Actually implement paginated /sync to speed up initial sync

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1846]
Erik implemented most (all?) of paginated /sync serverside. It needs to be hooked up clientside once we have decided precise updated ux for 1:1s

**Comment by ara4n** [comment]
need to decide whether lazy loading members is sufficient, or if we also could benefit from lazy loading in rooms too.

**Comment by richvdh** [comment]
(Synapse PR was https://github.com/matrix-org/synapse/pull/893)

**Comment by ara4n** [comment]
erik's original paginated /sync work has been succeeded by sync v3 (https://github.com/matrix-org/sync-v3); will open a new bug to get that implemented once it's ready. currently being proven with H instead of EW.
