### ISSUE TITLE
Integration permission page shows "[object Object]"

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#18467]
### Steps to reproduce

1. Add an Etherpad
2. Revoke your permissions
3. Go onto the sidepanel page that allows you to grant permissions to the integration.

### What happened?

![Screenshot_2021-08-09_22-11-34](https://user-images.githubusercontent.com/10872136/128785606-bd667a9f-930a-47fc-809a-0b1abc95c57b.png)

### What did you expect?

It shouldn't show "[object Object]".

### Operating system

Manjaro Linux

### Browser information

Firefox Developer 91

### URL for webapp

staging.element.io (Element version: 1.7.34)

**Comment by t3chguy** [comment]
Fixed on develop.
