### ISSUE TITLE
Fix nightly/develop to use React production build again

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18477]
### Steps to reproduce

Go on develop.element.io or launch Element Nightly

### What happened ?

It is using a React development version

### What did you expect ?

We should use React production version

### Extra context 

vector-im/element-web#16969

**Comment by Palid** [comment]
We should run nightly builds with something like `NODE_ENV='nightly'` and then in `webpack.config.js` verify if it's `production`, `development` or `nightly` and set the `mode` and the variables properly.

**Comment by t3chguy** [comment]
`nightly` would be a poor name given that it goes onto develop.element.io many times an hour

**Comment by Palid** [comment]
Why not just building it with `production` build then? Sourcemaps should be more than enough for errors tracking in this case.

**Comment by gsouquet** [comment]
That has been fixed
