### ISSUE TITLE
Read receipts fly from the sky

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18480]
### Steps to reproduce

It looks like if you rapidly switch between rooms of images of different loading types (blurhash/spinner) it may happen, but I couldn't figure out a proper 100% reproduction yet.  It may also be related to the multiple calls.
Attaching a video. Action happens around 8th second+.

https://user-images.githubusercontent.com/3636685/128901633-c14c4982-a835-4ae4-b3d4-d5e44cc6625e.mp4

### What happened?

Icon was spriting bottom from the top of the page (look at the right side of the timeline view) like it just missed the olympics.

### What did you expect?

That the last-seen message icon is not sprinting down but is kept at the bottom from the beginning. 

### Operating system

MacOS Big Sur 11.4

### Browser information

Google Chrome Version 92.0.4515.131 (Official Build) (x86_64)

### URL for webapp

https://app.element.io/

**Comment by gsouquet** [comment]
Looks like #17561 regressed

**Comment by Palid** [comment]
Seems that the regression is related to delayed loading of Call events.

**Comment by SimonBrandner** [comment]
I can repro though I am not able to tell what exactly is causing the animation

**Comment by MadLittleMods** [comment]
Does this still occur? Can we close?

**Comment by SimonBrandner** [comment]
I don't think so? Haven't see in it in a while - closing; shout if you ever see this again
