### ISSUE TITLE
new DMs you initiate appear in breadcrumbs with an initial of 'E', no matter who they're with

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18485]
i assume E stands for Empty Room. it should use the profile of the user you're DMing instead, obviously

**Comment by gsouquet** [comment]
I tried reproducing this issue on develop.element.io and was not able to
Not quite sure what to do next. Any chance you could share a little more information regarding this?

**Comment by ara4n** [comment]
hm, agreed. i guess it's possible i'm getting it mixed up with https://github.com/vector-im/element-web/issues/16400, but i'm pretty sure that 3 times in a row i saw the new DM being added to breadcrumbs but with an E.  In trying to repro it just now i captured #16400 instead.

**Comment by t3chguy** [comment]
It could also be related to the js-sdk bug with sentinel members/event contexts which caused the name/avatar to lag behind and might've bled through to room avatar/name calculation

**Comment by ara4n** [comment]
if that was fixed in today's build, that might explain why i can't repro now.

**Comment by t3chguy** [comment]
Merged 2 days ago https://github.com/matrix-org/matrix-js-sdk/pull/1837 so potentially not

**Comment by ara4n** [comment]
right, i was on today's nightly, so i bet this is what was causing this.

**Comment by ara4n** [comment]
no, it's still happening. however, turns out this is a duplicate of https://github.com/vector-im/element-web/issues/17480
