### ISSUE TITLE
cmd-zero takes you to the Home space rather than resets zoom

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18481]
cmd-zero is the standard browser shortcut to reset your browser zoom to 100%. overriding it to take you to the Home space is questionable. perhaps we can special-case Home to be another shortcut and keep cmd-zero for zoom-reset

**Comment by t3chguy** [comment]
Cmd Fn Right Arrow (Cmd Home on a macbook) seems rather involved but better than clashing on Cmd-0
