### ISSUE TITLE
Refactor deprecated UNSAFE_* React lifecycle methods

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18482]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles

As of this day, there are 26 components using those legacy lifecycle methods

<img width="707" alt="Screen Shot 2021-08-11 at 09 28 48" src="https://user-images.githubusercontent.com/769871/128987950-11750ca0-3039-4d6b-bd20-6d1e452309f2.png">

**Comment by t3chguy** [comment]
Today we have 23 usages over 18 files
