### ISSUE TITLE
I think this is a UISI on a redacted event

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#18487]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1922197/129035078-53722f84-3cb8-48a0-8590-024d9966d4fe.png)

### What happened?

I went to an encrypted room and saw what looked like a UISI on an encrypted event maybe? This _might_ be an artefact of my having _Show hidden events in timeline_ enabled in labs.

### What did you expect?

I expected it to look less weird.

### Application version

Element Nightly version: 0.0.1-nightly.2021081001 Olm version: 3.2.3

**Comment by turt2live** [comment]
This looks to be with "show hidden events" enabled, which is effectively a feature to have this behaviour.
