### ISSUE TITLE
FilePanel scrollback is empty

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18491]
### Steps to reproduce

1. Open the FilePanel in a room with a long history of files. 
2. Move the scroll thumb up and down fast.

![Screenshot from 2021-08-11 14-01-52](https://user-images.githubusercontent.com/51663/129043901-c918130c-4e9b-4478-a2fb-7c06bd16874f.png)

### What happened?

Eventually the image previews stop loading. Scrolling away from there caused the images to start loading again.

### What did you expect?

Image previews are fast to show after the initial loading

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

**Comment by Palid** [comment]
@kittykat I can't figure out how to reproduce this, could've been that it's fixed already? Spent like 30minutes uploading lots of cute cats photos and scrolling like a madman, but haven't seen noticed this problem.

**Comment by SimonBrandner** [comment]
I think we fixed this

**Comment by SimonBrandner** [comment]
See https://github.com/matrix-org/matrix-react-sdk/pull/6630

**Comment by Palid** [comment]
Alright, closing with Fixed-By-Simon. 😄

**Comment by SimonBrandner** [comment]
(hopefully) :p
