### ISSUE TITLE
you can't right-click to copy the download link of a non-e2ee attachment any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18498]
We used to be able to right-click on the download link of attachments or files in order to grab their URL in non-E2EE rooms.  Now there's no way to do so, as both the tile and the download link are a JS action rather than a literal `<a href="">`.  Therefore I can't deeplink to the media repo any more.

**Comment by t3chguy** [comment]
Given the media APIs will be gaining authentication this isn't something that could be considered a feature anyway
