### ISSUE TITLE
Add a better newbie-friendly instruction for changing branches in readme

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18507]
Currently the instructions in element-web for developers are expecting a bit of javascript tooling knowledge, it'd be much better if we could make it so that the instructions could be helpful even for newbies. Maybe create a new paragraph intended for more entry-level developers?

**Comment by Johennes** [comment]
Closing since there hasn't been any follow-up since 2021 and it's slightly unclear to me what would require changing
