### ISSUE TITLE
Autostart on elementary OS leads to infinite loading

### ISSUE THREAD

**Issue by Y0hy0h** [vector-im/element-web#18502]
### Steps to reproduce

1. On elementary OS install Element using Flatpak.
2. Start Element and login. (Everything works fine so far.)
3. Add Element to the apps to autostart.
4. Restart.
5. Watch Element automatically start, but only show the loading spinner. The "Log out" link at the bottom is missing.
6. Use `htop` to kill all Element processes.
7. Start Element normally.
8. Remove Element form autostart list.
9. Restart.
10. Start Element manually. It works normally.

### What happened?

Having Element autostart on elementary OS leads to it loading infinitely.

### What did you expect?

Element should load normally, even when autostarting.

### Operating system

elementary OS

### Application version

Element version: 1.7.34, olm version: 3.2.3

### How did you install the app?

Via the elementary OS AppCenter, which uses Flatpak in the background (https://flathub.org/apps/details/im.riot.Riot)

**Comment by Y0hy0h** [comment]
I just tried activating the "Start automatically after system login" inside Element. After a restart nothing happens automatically. But now when I manually start it, I get the same infinite loading (without "Log out"). Even after killing all Element processes and starting it again do I get that infinite loading.

**Comment by t3chguy** [comment]
This is likely an issue with the third party flatpak package

**Comment by Y0hy0h** [comment]
Thanks for the pointer. I've opened the same issue there, so I'm closing this one.
