### ISSUE TITLE
Red shield icon next to my friends messages even though all of our sessions are verified.

### ISSUE THREAD

**Issue by GitHubRaien** [vector-im/element-web#18505]
I even turned on the feature which disabled communication with any of us if one of us are unverified, and we can still see each others messages, though the has an unencrypted icon next to her messages. (I'm sorry if this is something that has already been posted, I didn't look too much)
![image](https://user-images.githubusercontent.com/88808525/129122550-ecd00c11-c493-4bb3-8b42-dcc32dc3e7a0.png)
![image](https://user-images.githubusercontent.com/88808525/129122586-f6293412-84d1-45f5-9095-b0789ca9beaf.png)
![image](https://user-images.githubusercontent.com/88808525/129122610-0ac7eda5-bc0f-41c3-a56d-92e00d8bd01e.png)

**Comment by SimonBrandner** [comment]
@GitHubRaien, if you hover over the red encryption badge it should say something, what does it say?

**Comment by GitHubRaien** [comment]
@SimonBrandner Obviously it says "unverified"

**Comment by SimonBrandner** [comment]
Ah, so just to check even if you disable _Never send encrypted messages to unverified sessions from this session_, you get the unverified badge on messages, even new ones?

**Comment by GitHubRaien** [comment]
@SimonBrander Yes, that is exactly the case.

**Comment by GitHubRaien** [comment]
@SimonBrandner Also, could that red badge signify anything BUT "unverified"?

**Comment by SimonBrandner** [comment]
> @SimonBrandner Also, could that red badge signify anything BUT "unverified"?

There could be _Encrypted by a deleted session_ and possible other stuff, I am not sure

**Comment by dbkr** [comment]
Debug logs could be useful here

**Comment by ManDay** [comment]
Please compare #17187 . I confirmed the behaviour there, not to repeat it here.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17187
