### ISSUE TITLE
js-sdk RC missing type definitions for `lib/`

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18503]
It was in previous RCs and releases. Probably a missed `yarn build:types` before release.

**Comment by turt2live** [comment]
`S-Critical` because it says "prevents work" in the label description, which is affecting a customer.

**Comment by dbkr** [comment]
tsc doesn't seem to be creating `lib/index.d.ts` any more...

**Comment by dbkr** [comment]
Regressed in https://github.com/matrix-org/matrix-js-sdk/pull/1829
