### ISSUE TITLE
Option+Backspace does not delete words in message box

### ISSUE THREAD

**Issue by callahad** [vector-im/element-web#18508]
### Steps to reproduce

1. Begin typing a message in a room (or edit an existing message)
2. Press Option+Backspace

### What happened?

One character was deleted

### What did you expect?

On macOS, Option + Backspace should delete whole words, not individual characters. This is a recent regression in Element Web.

Other textboxes in the app work as expected (e.g., text in the "Filter all spaces" box properly responds to Option+Backspace, so we've somehow broken the default widget behaviour in our message entry boxes.)

### Operating system

macOS 11.5

### Browser information

Firefox 92 (Beta)

### URL for webapp

develop.element.io

**Comment by t3chguy** [comment]
Can you share which version of develop you are using? It should be fixed in latest.

**Comment by callahad** [comment]
Element version: fac01903e730-react-09ffad96ff1e-js-696b3ef1ce15
Olm version: 3.2.3

**Comment by callahad** [comment]
Confirming fixed after manually checking for updates (thought reloading would do that automatically, #TIL)
