### ISSUE TITLE
Emoji reaction picker jittery when scrolling to the very bottom

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18514]
### Steps to reproduce

1. open picker to react with emoji
2. search, e.g. `de` to find :de: 
3. scroll to the bottom

### What happened?

menu jitters, scrolling up and down by ~2px constantly. the bottom row is thus not clickable.

### What did you expect?

stay at bottom

### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18272
