### ISSUE TITLE
Breadcrumbs should show when spaces are managed ("Manage & Explore Rooms")

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18518]
#### What would you like to do?

I find that I'm confused and disorientated when I go to look at my breadcrumbs after something has taken over the timeline view of my client. I expect that the Space would show up in the first room slot, causing me to visually scan the remaining ones for the room avatar I'm looking for before finally ending up realizing that the space didn't take the first slot. I'd like to do less of that.

#### Why would you like to it?

Per above, to reduce confusion.

#### How would you like to achieve it?

Ensuring that the space appears in breadcrumbs when managing it (not when clicking them on the left) would be appreciated so I can jump around a bit easier.

**Comment by t3chguy** [comment]
This is now done
