### ISSUE TITLE
Ctrl+Backspace/Delete doesn't delete whole words anymore

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18513]
### Steps to reproduce

1. compose msg
2. want to delete a word
3. hit ctrl+backspace or ctrl+del

### What happened?

delete single char

### What did you expect?

delete whole word

### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by t3chguy** [comment]
Already fixed on develop.
