### ISSUE TITLE
It's super unclear that 'explore rooms' will show you the space dir rather than room dir when in a space

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18528]
![image](https://user-images.githubusercontent.com/1294269/129365107-4b231683-36f5-451a-8bd6-38e9027bc539.png)

I had never thought to click on the button on the RHS here to display the space index - i assumed it would always show me the server's room directory.

 * Can we change the tooltip to 'Explore space' or 'Explore Element Corp.' rather than 'Explore rooms', which sounds like it's talking about the old roomdir?
 * Is there a better icon which makes it clearer that we're talking about spaces here?

Precisely the same goes for the bottom at the bottom of the roomlist:

<img width="352" alt="Screenshot 2021-08-13 at 14 35 39" src="https://user-images.githubusercontent.com/1294269/129365287-f2bb3136-7065-43e2-b7c2-616f43bba785.png">

If these apply to the current space, should it be "Invite to Element Corp." and "Explore Element Corp."?

**Comment by ShadowJonathan** [comment]
+1 to "explore space", else it'd become a word salad in the tooltip

> Is there a better icon which makes it clearer that we're talking about spaces here?

Maybe a rocket? :D

Though, why not keep the current `#` icon, and remove the looking glass?

Alternatives such as having a looking glass wouldn't work well because the button is right next to the search field, then it could be confused as a "search" button. In general I don't know good iconology for "spaces", we really should design one of our own for element, to designate Spaces with.

**Comment by niquewoodhouse** [comment]
> Can we change the tooltip to 'Explore space'

That sounds really good to me.  

> Is there a better icon which makes it clearer that we're talking about spaces here?

I think Spaces is a pretty abstract concept so its hard to identify an icon that is easily understood.  It can be done though, 
I noticed [Cinny](https://cinny.in/) on their homepage has an icon for Spaces:

![image](https://user-images.githubusercontent.com/1587166/129598960-98395ec5-f413-419b-8e39-65e2c0f7fb84.png)

Once you work out what it means, it makes it easier to recognize what's a Space, I guess.  But if we relied on this hypothetical icon in some way and it was left on its own (no label), it would add to the cognitive load for everyone at first (_what is that?  oh...a Space...ok_). 

Even if there is was an obvious icon that says 'Spaces', showing a Space icon here might confuse people - am I searching Spaces here or looking at rooms within a Space?  

> Though, why not keep the current # icon, and remove the looking glass?
> 
> Alternatives such as having a looking glass wouldn't work well because the button is right next to the search field, then it could be confused as a "search" button. 

I think the thing is, it _is_ for many people a search button of sorts.  We've seen in tests people reach for a magnifying glass when they're looking for something and the people exploring a space are looking for something.  

I do think there's a really strong insight in your suggestions - in that it's a bit confusing to have a search (to filter your room list) and then _another_ search next to it but I think the answer is a global spotlight search that includes what you're in and what what you're not in, which keeps on coming up.

**Comment by niquewoodhouse** [comment]
Took a quick look at this, just exploring some of the ideas good and bad.

**Change tooltip (good small change):**

https://user-images.githubusercontent.com/1587166/130446331-b608083c-d7d9-453a-949d-61607a694394.mp4

_____

The next few are just rough mockups of rough ideas, not necessarily designs we'd follow.

Remove explore button and combine it with the search (not so good - you end up with results in 2 places):

https://user-images.githubusercontent.com/1587166/130446379-a7e65d86-fd94-4e4e-8cd8-50c3eaea5963.mp4

https://user-images.githubusercontent.com/1587166/130446409-b52e4652-0885-4984-a4ec-b8485e889a70.mp4

Wider redesign of Element web UI to make one global search that sits above room list of a Space:

https://user-images.githubusercontent.com/1587166/130483367-481258d2-3a1a-4423-840d-6811c2357133.mp4

**Comment by ShadowJonathan** [comment]
I gotta say 03 *looks* to be promising, but it is incredibly awkward to have the searchbar just "shoot off" into the middle of the chat window, sorta "breaking" the barrier between the room list and the chat list.

It might help if the small greyish "user bar" at the top of the room list (with the drop-down icon) starts stretching all across the window too, it'd at least signal that this is intended, and/or "hiding" the chat window for now.

Though certainly i think a sudden stretch-across of the searchbar if i click on it would be a bit frightening, more as like you're poking an animal and it just lengthens 3 meters across the floor in under a second.

---

04 looks like a "Web UI", but i also gotta say it's discarding a lot of space by occupying a top bar.

---

Can't a discord/slack-style "pop up searcher" be used for this?
