### ISSUE TITLE
Action to remove from the Needs info column

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18523]
Currently, a human needs to do this, it seems

**Comment by kittykat** [comment]
@SimonBrandner Are you talking about one of the project boards?

**Comment by SimonBrandner** [comment]
> @SimonBrandner Are you talking about one of the project boards?

Yes, the [issue triage one](https://github.com/vector-im/element-web/projects/27)

**Comment by kittykat** [comment]
Work on that board is still in progress, there's a host of automation that still needs to hapen
