### ISSUE TITLE
Give feedback button on space home doesn't work

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18524]
### Steps to reproduce

![Screenshot_20210813_135154](https://user-images.githubusercontent.com/25768714/129353136-831131b4-0785-46cb-b156-218ac85fd637.png)

### What happened?

![Screenshot_20210813_135214](https://user-images.githubusercontent.com/25768714/129353185-72bb90e8-df37-4576-a5ad-8e7e010d04db.png)

### What did you expect?

I expected it to work

### Application version

Element Nightly version: 2021081202 Olm version: 3.2.3

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6594/commits/013ccd46ad7a28af7b18358f195aefd3aff0d4ca
