### ISSUE TITLE
VoIP glare is broken.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18538]
### Steps to reproduce

I called Tom at the same time that he was calling me.  It displayed me as calling him still, and vice versa.

<img width="1032" alt="Screenshot 2021-08-13 at 17 08 59" src="https://user-images.githubusercontent.com/1294269/129388348-62ba8e6d-703a-497f-aba0-df3fe0220c57.png">

### What happened?

Call glare didn't work; see above.

### What did you expect?

One of the outbound calls should have turned into an inbound call but it didn't.

### Application version

nightly

**Comment by SimonBrandner** [comment]
So far it seems that the peer connection goes missing for the side doing the replacing. That leads me to think that this has the same cause as https://github.com/matrix-org/matrix-js-sdk/pull/1834. I am not exactly sure where this regressed but https://github.com/matrix-org/matrix-js-sdk/pull/1821 is a candidate though I don't really see how could that happen

**Comment by SimonBrandner** [comment]
I am getting there... :D

**Comment by dbkr** [comment]
I reverted the fix in https://github.com/matrix-org/matrix-js-sdk/pull/1857 because it caused a lot of voip breakage (https://github.com/matrix-org/matrix-js-sdk/pull/1857) so re-opening this
