### ISSUE TITLE
Fullblown search UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1854]
The current search UI is placeholder that vdh & I made up.  The intention instead is to have a proper spotlight-style search UI in the MiddlePanel that produces different types of results and lets you search different types of data.  There are some proposals from ribot for this.  This is the HL tracker for implementing them.

**Comment by ara4n** [comment]
the idea is to put the search results as an entry in the LeftPanel for ease of subsequent reference.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16409
