### ISSUE TITLE
Prompt to send a voice message if a VoIP call doesn't pick up

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18544]
#### What would you like to do?

Prompt to send a voice message if a VoIP call times out when ringing, as a cute nod to voicemail (and visual voicemail) of years gone by.

#### Why would you like to it?

If the user has got rigged up for a VoIP call, tries to call someone, and they don't answer, they're in a perfect position to leave a voice message to summarise why they were trying to call - which might be a bit more personable and emotive than just sending an IM.  We could give them the option to do so.  It's also a cheeky reference to the good old PSTN, and to remind people that Matrix is attempting to replace the PSTN.

#### How would you like to achieve it?

Perhaps the call tile could prompt to send a voice message if the call times out?

**Comment by ShadowJonathan** [comment]
2c: Does the call window (upon no response) require explicit dismissal? Maybe then this can be as simple as adding a "leave voicemail" button on that same window?

If not, maybe it could instead be added onto the timeline tile (visible for about 10 minutes or so)

**Comment by HammyHavoc** [comment]
That's sick.

**Comment by bryandesrosiers** [comment]
All on board with this idea

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-meta/discussions/638
