### ISSUE TITLE
Mac: Preferences (Settings) doesn't close in the usual way

### ISSUE THREAD

**Issue by Behodar** [vector-im/element-web#18548]
### Steps to reproduce

1. From Element's application menu, choose Preferences.
2. Attempt to close the resulting "Settings" window by using its Close button or by pressing Cmd-W.

### What happened?

The Close button is in the wrong place and has the wrong icon. It should be a red circle in the top-left of the window, and instead it's a grey cross in the top-right.

Pressing Cmd-W doesn't close Settings, but rather the entire Element window.

### What did you expect?

I expected to have a red Close button in the top-left corner. I expected Cmd-W to close Settings.

Side note: "Settings" should be "Preferences" to match other Mac apps. It's correct in the menu bar but not in the app itself.

### Operating system

macOS 11.4

### Application version

Element 1.7.34

### How did you install the app?

From https://element.io/get-started

**Comment by SimonBrandner** [comment]
Element's settings aren't a separate window. They are a part of the main window. For what you're suggesting to work, we would need to make quite a few changes. And these changes would only affect desktop users, so it doesn't seem to be worth it. This is also the same behaviour that many other apps such as Discord have.
