### ISSUE TITLE
Create Space from community says my address is already in use!

### ISSUE THREAD

**Issue by onkq** [vector-im/element-web#18542]
### Steps to reproduce

1. Open develop.element.io
2. Settings -> Prefs
3. Communities -> Show my communities -> Create Space
4. See the address already taken

![d](https://user-images.githubusercontent.com/84337276/129446673-ac63dc8a-2897-462b-9b45-1b8c1c314bd3.png)

### What happened?

The address is automatically filled for you with your previous community address, but is showed as unavailable/taken. Which doesn't make sense since I am still the proud owner of the address!

### What did you expect?

Let me keep my address name because I am simply converting it. It shouldn't be possible to steal since it's not even out yet to the public and still in development.

### Operating system

Linux

### Browser information

Firefox 90.0.2

### URL for webapp

develop.element.io

**Comment by t3chguy** [comment]
Spaces are rooms and as such use room addresses. Your community may well be +aqw:matrix.org but #aqw:matrix.org is already taken.

**Comment by onkq** [comment]
Oh okay. Guess there is nothing else I can do
