### ISSUE TITLE
Silence button for inbound ringing calls is ugly and not obviously a silence button

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18557]
### Steps to reproduce

You receive an inbound call.  You see this toast:

<img width="319" alt="Screenshot 2021-08-15 at 22 21 35" src="https://user-images.githubusercontent.com/1294269/129493308-a766ab7d-d65f-4a7c-a05d-ead07b163c36.png">

### What happened?

You wonder why there's loudspeaker icon squeezed into the toast without any padding.  You assume that it's informational somehow saying "oi, this toast comes with a noise".

You hover over it, discover that it's a silence call button.

### What did you expect?

I expected the icon to more clearly show that it's a button, rather than informational state, and to be laid out properly in the toast with padding.

### Application version

today's develop

**Comment by SimonBrandner** [comment]
The padding issue will be solved by https://github.com/matrix-org/matrix-react-sdk/pull/6617 though I am not sure how to make the button feel more like a button. IMO, it's fine the way it is. @gaelledel, do you have any thoughts on this?

**Comment by gaelledel** [comment]
Making this a button like the traditional ones wouldn't be appropriate in this context as the action should be secondary. Adding padding is however fundamental.

**Comment by gaelledel** [comment]
Why are we showing the Matrix ID next to the name?

**Comment by SimonBrandner** [comment]
> Why are we showing the Matrix ID next to the name?

This looks like disambiguation happening - two users called Matthew in the room?

**Comment by SimonBrandner** [comment]
> > Why are we showing the Matrix ID next to the name?
> 
> This looks like disambiguation happening - two users called Matthew in the room?

Yeah, I think this is Matthew's test DM with himself from another homeserver
