### ISSUE TITLE
Call duration while on call

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18566]
#### What would you like to do?
See call duration while on call
#### Why would you like to it?
It exists on Android
#### How would you like to achieve it?
Same as on Android

**Comment by chagai95** [comment]
Thanks Dave and Simon

**Comment by SimonBrandner** [comment]
FYI, we also probably plan to add a timer to the call header though I deferred that since there are going to be changes for https://github.com/matrix-org/matrix-react-sdk/pull/6547 which would conflict with this
