### ISSUE TITLE
"Call again" button text overflows on narrow screens

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#18565]
### Steps to reproduce

1. Try to call someone and have them decline. A card appears in the timeline with a "Call again” button.
2. Have the window be a narrow width (on my 1050px wide monitor, or when I half-tile on my 1680px wide one → 840px)

### What happened?

The button looks like this:

![image](https://user-images.githubusercontent.com/117241/129550146-1e93be2c-8b40-4a25-9894-5efd0fd36930.png)

### What did you expect?

The button (background) should be resized to fit its text content.

### Operating system

Fedora 34

### Browser information

Firefox 90.0.2

### URL for webapp

app.element.io

**Comment by SimonBrandner** [comment]
Partially fixed on develop.element.io and the rest will come in https://github.com/matrix-org/matrix-react-sdk/pull/6618

**Comment by afranke** [comment]
develop indeed looks better. The card takes only about half the width of the timeline though, not sure that’s expected.

![image](https://user-images.githubusercontent.com/117241/129559828-55c889f0-d2d4-482a-aa31-9671f59765e2.png)

**Comment by SimonBrandner** [comment]
> develop indeed looks better. The card takes only about half the width of the timeline though, not sure that’s expected.
> 
> ![image](https://user-images.githubusercontent.com/117241/129559828-55c889f0-d2d4-482a-aa31-9671f59765e2.png)

Yes, if the card collapses if there isn't enough of space

**Comment by kittykat** [comment]
I'm on up-to-date develop.element.io

![Screenshot from 2021-08-16 12-57-06](https://user-images.githubusercontent.com/51663/129560272-11abadf2-6b20-4a2f-b2d7-b6e07009e03e.png)

**Comment by kittykat** [comment]
I am using half my screen rather than a full screen, I don't feel like that's an unreasonable thing to do - I often do that for other websites (e.g. GitHub, Etherpad, Google Docs/Sheets). The monitor is 1920 wide, so the window is 960 px wide.

![Screenshot from 2021-08-16 14-04-09](https://user-images.githubusercontent.com/51663/129568783-468634c1-c1e2-4e16-880f-f3d1d6148f0d.png)

**Comment by SimonBrandner** [comment]
> I am using half my screen rather than a full screen, I don't feel like that's an unreasonable thing to do - I often do that for other websites (e.g. GitHub, Etherpad, Google Docs/Sheets). The monitor is 1920 wide, so the window is 960 px wide.

Definitely agreed, https://github.com/matrix-org/matrix-react-sdk/pull/6618 should fix this. In the first picture, it looked like you had the window smaller than that though

**Comment by kittykat** [comment]
In the first one, there's space for the button to be double the height so it matches the "call declined" text for height
