### ISSUE TITLE
No notification for calls

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18567]
### Steps to reproduce

Sorry for the terrible voice quality, it's still pretty clear what I'm doing though...

https://user-images.githubusercontent.com/31655082/129552889-36f5b675-b71c-4ff6-8cf1-5d2ea78f57e1.mp4

1. Receiving an incoming call

### What happened?

No notification.

### What did you expect?

A notification.

### Operating system

Windows

### Browser information

Chrome Version 92.0.4515.131 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

**Comment by SimonBrandner** [comment]
Sorry about this... This is my screw up that go into release and it should be fixed in the next one
