### ISSUE TITLE
Release script source tarball signature races with Github

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18577]
### Steps to reproduce

Intermittent on releasing

### What happened?

Occasionally when running the release script, the step of downloading the source tarball from github, checking it against what's on disk and signing the result, fails because github isn't ready yet and returns a 404 for the source tarball for that release.

### What did you expect?

Perhaps it should retry on a 404, or possibly we could just sign what's on disk and upload that, and accept that if github change some subtle detail of the source tarballs, our sigs will be wrong until someone notices.

**Comment by Johennes** [comment]
@t3chguy would it make sense to include this in the [Saner Releases](https://github.com/vector-im/element-web/issues/23538) epic?

**Comment by t3chguy** [comment]
Saner Releases will eradicate the release script so it'll supplant this issue

**Comment by Johennes** [comment]
Even better! In that case I don't think we have to keep this one open as we're already committed to saner releases.
