### ISSUE TITLE
emoji auto-completion is accepted when hitting space bar

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18571]
### Steps to reproduce

settings:
![image](https://user-images.githubusercontent.com/2803622/129586869-358ea663-a9b6-40c1-8da7-788bba4bdcbd.png)
- auto replace off
- "suggestions" on to enable github-codes like :thinking_face: :thinking: 

1. type `:)`
2. auto-completion pops up with `:slightly_smiling_face:` (what a description, really)
3. ignore popup since i prefer plain and continue typing (i.e. hit space bar)

### What happened?

emoji gets accepted anyway

### What did you expect?

The previous behaviour was to not accept on space bar.
Perhaps the problem is the same change that changed the emoji codes, perhaps not.

For better typing flow, space should dismiss suggestions additionally to escape since escape if far away and continuing to type (literally ignoring) would otherwise accept things unintentionally. things like enter (and at most tab, which I'd expect to navigate the suggestions instead) should accept.

### Operating system

arch

### Application version

Element Nightly version: 2021081601 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by robintown** [comment]
I can't reproduce this (are you certain that auto replace is off?)

**Comment by HarHarLinks** [comment]
yes the settings are as in the screenshot.

however it stopped doing that now after I toggled the suggestions (2nd) off and on to see if i can still use the :codes: with it off.

no idea what happened here...
