### ISSUE TITLE
We've lost the tooltip on hover for stickers

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18574]

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/129598766-ea726dcc-7e0f-49e8-9624-a93b530c25ef.png)
?

Element Nightly version: 2021081601
Olm version: 3.2.3

**Comment by turt2live** [comment]
closing as invalid: there's badly behaving clients in the wild.

**Comment by ShadowJonathan** [comment]
@HarHarLinks (apt sticker btw :D)
