### ISSUE TITLE
voice call doesn't work

### ISSUE THREAD

**Issue by wizzyxx** [vector-im/element-web#18578]
### What happened?

If i call a person, that person can't hear me but i can hear that person and if the other person calls back, i cant hear that person but that person can hear me.

When i get the call i can't hear the ringing also if i call other person that person can't hear the ringing either.

### What did you expect?

voice should work for both side

### Operating system

Windows 10

### Browser information

Chromium: 92.0.4515.131

### URL for webapp

app,element,io

Element version: 1.8.0
Olm version: 3.2.3

**Comment by dbkr** [comment]
I think there are at least 3 issues here that I can repro:
 1. No audio from caller to callee
 2. Ringing sound seems to be silenced by default (no ringing to start with, silencing the call the un-silencing it starts it ringing)
 3. No notifications for calls unless you're in the room at the time

**Comment by dbkr** [comment]
I've reverted the code that caused this so you can use https://develop.element.io/ as a workaround for now.

**Comment by wizzyxx** [comment]
working fine on https://develop.element.io
