### ISSUE TITLE
Element Web may report running a newer version than it actually is

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18572]
### Steps to reproduce

1. Load Element Web
2. Deploy a new version of the app to https://app.element.io
3. Open a new browser tab and load the web inspector.
4. Load Element Web again, without refreshing - directly visit the URL.
5. Go to settings and check the version of the app. Note that it is for the newly deployed version.
6. Check the `Last-Modified` header returned for https://app.element.io. Note that it will be the date of the previous release - this is because you're running the previous release. 
7. Note also that you are not running the latest release by checking for absent features

### What happened?

Here's a screenshot showing the problem. I am running Element 1.7.x but the about box shows Element 1.8.0.

<img width="1651" alt="Screenshot 2021-08-16 at 16 50 40" src="https://user-images.githubusercontent.com/57377/129593373-5803efb1-3e25-4ec8-a19b-d2da922404ac.png">

Note that version shows 1.8.0, but `Last-Modified` is 2nd august (from the previous 1.7x release). 

And also note that in 1.8.0, we changed how versions are displayed to this, so I'm definitely not running 1.8.0

<img width="230" alt="Screenshot 2021-08-16 at 17 05 21" src="https://user-images.githubusercontent.com/57377/129594187-bc1ab2db-f598-4b2c-bfe9-0d6bed7cda35.png">

And .. the bundle hash referred to from the stale HTML is for the previous version

<img width="488" alt="Screenshot 2021-08-16 at 16 51 15" src="https://user-images.githubusercontent.com/57377/129594240-8e124a7b-e3ee-4b9b-a9e7-16f96e7a08fe.png">

Whereas the bundle hash should be this:

<img width="462" alt="Screenshot 2021-08-16 at 16 51 53" src="https://user-images.githubusercontent.com/57377/129594290-2b5462a3-1d8e-4395-bda0-aced5591d680.png">

### What did you expect?

The version reported should match the actual version I'm running

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

**Comment by novocaine** [comment]
This has the same root cause as https://github.com/vector-im/element-web/issues/9422 - we don't set a `cache-control` header on `/`, so we run stale copies of the app bundle, but we determine the current version by fetching a static file from the server which we cache bust

**Comment by turt2live** [comment]
I thought we had an issue for this already, but naturally the keywords including "version" make it impossible to find. The suggestion on that unknown issue is to bundle the version into the app rather than use a separate file (aside from update checking). This is particularly useful for rageshake reporting where if someone says they're on 1.8 and in fact they're on 0.17 we can end up diagnosing a non-issue.

**Comment by novocaine** [comment]
Agreed, that sounds much better.

**Comment by t3chguy** [comment]
This got fixed, we now bake in the current version using webpack
