### ISSUE TITLE
Waveform object in voice message contained only nulls

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#18587]
### Steps to reproduce

- Record a voice message in Element Web

### What happened?

The MSC in https://github.com/matrix-org/matrix-doc/pull/3246 appears to only allow integer numbers in the `waveform` array, but some events sent by element-web include nulls.

### What did you expect?

An array containing numbers. Otherwise, the event is incompatible with the spec.

### Operating system

Linux

### Application version

1.8.1

### How did you install the app?

Internal Testing Server

**Comment by Half-Shot** [comment]
This also causes Element Android to fail to render the event at all, although other Element Web instances seemed to be able to render and play the event (amazingly, with a proper waveform).

**Comment by SimonBrandner** [comment]
I don't think I am able to repro

**Comment by SimonBrandner** [comment]
NVM, I can repro on FF

**Comment by SimonBrandner** [comment]
I also don't see any waveform when recording

**Comment by novocaine** [comment]
Is this from an electron build? Is it from a nightly or official release?

**Comment by SimonBrandner** [comment]
For me, this is on develop.element.io on FF

**Comment by novocaine** [comment]
> For me, this is on develop.element.io on FF

cool, the reason I ask is that this has been filed with the desktop (electron) template, but the note refers to Element Web

**Comment by novocaine** [comment]
FWIW, I also can't replicate on electron, so would be quite interested in whether @Half-Shot sees this on FF

**Comment by Half-Shot** [comment]
Sorry, I probably filed it on the wrong one. I'm filing as someone who received an invalid event rather than the sender.

**Comment by dbkr** [comment]
Re-opened due to https://github.com/vector-im/element-web/issues/18939

**Comment by turt2live** [comment]
@dbkr this needs updated reproduction steps, browser information, etc as the issue is believed fixed and is unreproducable.

**Comment by bmarty** [comment]
I think all that is needed to know to repro the issue is there: https://github.com/vector-im/element-web/issues/18939

I still reproduce the issue today, not all the time though
