### ISSUE TITLE
website download links not clickable

### ISSUE THREAD

**Issue by Tcll** [vector-im/element-web#18580]
clicking the download links here doesn't work:
![image](https://user-images.githubusercontent.com/773959/129640323-7a31328e-32de-46c4-9e84-6c6fce1470d9.png)

this may have something to do with the malware that's blocked:
![image](https://user-images.githubusercontent.com/773959/129640482-58a109a0-4ecc-4c12-8fa0-1c54dd48ad13.png)
unfortunately uMatrix doesn't give any details on what's for what that's being blocked, or I'd post that too

hopefully you can get the download links working non-maliciously :)

**Comment by kittykat** [comment]
You should see this pop-up when you click the Linux link:

![Screenshot from 2021-08-17 08-33-29](https://user-images.githubusercontent.com/51663/129683551-7d2a6a28-4177-449a-87d0-c28e0f4f28ac.png)

**Comment by SimonBrandner** [comment]
This should probably be filed at https://github.com/vector-im/element.io

**Comment by dbkr** [comment]
Moved to https://github.com/vector-im/element.io/issues/26

**Comment by Tcll** [comment]
> You should see this pop-up when you click the Linux link:
> 
> ![Screenshot from 2021-08-17 08-33-29](https://user-images.githubusercontent.com/51663/129683551-7d2a6a28-4177-449a-87d0-c28e0f4f28ac.png)

oh wait, there's no appimage download anyways?
that's a shame
I was hoping to update to the latest appimage so I could search encrypted rooms again

I guess I'll get the appimage unofficially then
at least you guys are fixing the website malware issue ;)
