### ISSUE TITLE
Microphone muted in 1on1 calls

### ISSUE THREAD

**Issue by lukasIO** [vector-im/element-web#18583]
### Steps to reproduce

1. Open direct message room
2. Start video call

### What happened?

After the latest update, in our tests, the person who initiated the call cannot be heard by the other participant. 
Nevertheless the other person can still be heard by the person who did not initiate the call. Video worked without any problems in both directions.
This also happens calling from the iOS App to element desktop.

### What did you expect?

I expected that the both participants can hear each other.

### Operating system

Windows, macOS, iOS

### Application version

Version von Element: 1.8.0 Olm version: 3.2.3

### How did you install the app?

In-App Update

**Comment by SimonBrandner** [comment]
Sorry for the trouble! This is a known issue and an off-cycle release has been started, it should be ready in a few hours. For now, you can use develop.element.io where a fix has already been deployed
