### ISSUE TITLE
Voice messages contain a `waveform` key in `org.matrix.msc1767.audio`, which is not specced

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#18586]
I found this while trying to report another bug, but since I don't have a spec to follow it's difficult to tell what the format of waveform is meant to be. 

[MSC1767](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1767/proposals/1767-extensible-events.md)

**Comment by Half-Shot** [comment]
Ah, it appears to be https://github.com/matrix-org/matrix-doc/pull/3246. Since that MSC doesn't include a prefix, I guess this is fine.

**Comment by turt2live** [comment]
Ftr, lack of prefix in an MSC does not mean someone can use it without a prefix. In this case, the property is under an all-new prefixed key and thus doesn't need overspecification.
