### ISSUE TITLE
VoiP call shows always as connecting, sometimes shows unknown state after ending

### ISSUE THREAD

**Issue by swedneck** [vector-im/element-web#18585]
### Steps to reproduce

Opening an issue to link logs as requested by šimon brandner.

### What happened?

Calls show as infinitely connecting, upon ending call it sometimes says the call is in an unknown state.

### What did you expect?

the call just working

### Operating system

Fedora 34

### Browser information

firefox 87

### URL for webapp

app.element.io, develop.element.io

**Comment by dbkr** [comment]
Somehow the call here has only got host candidates on both sides, even though one is develop on matrix.org (I just tested and the turn server is working for me)

**Comment by dbkr** [comment]
There's another bug we've seen where firefox fails to resolve the address of the turn server and ends up trying to connect to 0.0.0.0. Are you able to get the logs from `about:webrtc` to confirm if it's this bug or not? If so, you should see something like `Write error for IP4:0.0.0.0:3478/TCP - 10`.

**Comment by swedneck** [comment]
unfortunately it seems that visting that url utterly swallows my RAM and forces me to restart the browser.

**Comment by ara4n** [comment]
if you try it on a fresh browser session immediately after a single 1:1 call in Element then about:webrtc shouldn't melt FF.

**Comment by SimonBrandner** [comment]
@swedneck, were you able to get logs from `about:webrtc`?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
