### ISSUE TITLE
Unable to verify iOS app from macOS app

### ISSUE THREAD

**Issue by JoeStrout** [vector-im/element-web#18595]
I am unable to verify my iOS app from the macOS app.
The result is that on my iOS device, half the messages in a conversation are encrypted and unreadable.
When I jump through the verification hoops, it all seems to go great, until it asks if the same icon (a green shield with checkmark) appears on both devices.
It does, so I click Yes.
And then it tells me (on both devices) that I cancelled the verification.
<img width="710" alt="Screen Shot 2021-08-17 at 8 32 53 AM" src="https://user-images.githubusercontent.com/263365/129756806-251203ed-1c74-46eb-a710-04f4770aae04.png">

**Comment by dbkr** [comment]
This was resolved in #element-web:matrix.org (although we still don't know how it got into this state).
