### ISSUE TITLE
Beta-dot breaking subpixel antialiasing font rendering

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18600]
Due to some issues with layers and LCD text rendering (see https://bugs.chromium.org/p/chromium/issues/detail?id=1016062) it seems that animating Beta dot (`.mx_BetaDot`), `res/css/views/beta/_BetaCard.scss` breaks the fonts rendering in the entire application on Windows as long as it animates.

I haven't figured out any solution other than just getting rid of this animation on Windows entirely.
Contributions welcome, as this is a quite annoying pickle.

**Comment by Palid** [comment]
Beta dot should be removed in this or next RC anyways, so we can get rid of this issue.

**Comment by t3chguy** [comment]
> Beta dot should be removed in this or next RC anyways

This is not the case, https://github.com/matrix-org/matrix-react-sdk/pull/6594 makes use of it for the grand Spaces release.

**Comment by Palid** [comment]
Fortunately the beta-dot doesn't break timeline rendering after all the optimisations now.
