### ISSUE TITLE
Screen Sharing in Calls

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#18602]
#### What would you like to do?
Please add screen sharing to calls.
#### Why would you like to it?
Because I would like to be able to share my screen with people.
#### How would you like to achieve it?
Capture the screen and share it to the other call participant

### Have you considered any alternatives?

The only alternative is not using matrix

**Comment by robintown** [comment]
Screen sharing is now a thing as of version 1.8.0: https://github.com/matrix-org/matrix-react-sdk/pull/5992

If however your Element is up to date and it still doesn't seem to be working, definitely report bugs like that back here.
