### ISSUE TITLE
Broken screen sharing on Linux Wayland

### ISSUE THREAD

**Issue by vchernin** [vector-im/element-web#18607]
### Steps to reproduce

1. Try to screen share on Linux Wayland with the new 1:1 calling feature.

### What happened?

Sharing the full screen or most apps will not work. You might in some cases be able to share other xwayland Chromium based apps, but that's a guess at best. This issue is not about group calls with embedded Jitsi, that is broken in all Element desktop builds due to https://github.com/vector-im/element-web/issues/4880.

### What did you expect?

Chromium and Electron apps like Element currently require passing `--enable-features=WebRTCPipeWireCapturer` at runtime to enable PipeWire screen sharing on Wayland. This isn't something most users will know exists, so screen sharing will simply be assumed to be broken with Element on Wayland.

Element should enable this flag at build time so .DEB and Flatpak users can screen share. [Jitsi meet electron did so here](https://github.com/jitsi/jitsi-meet-electron/pull/584) (not the Jitsi embedded in Element, just a seperate Electron Jitsi package).

As far as I've seen, this flag does not cause regressions for X11 users. The expererience with it on Wayland can sometimes have issues, but I think mostly working screen sharing on Wayland by default is better than hardly anything at all.

One issue I noticed is Element seems to have [a similar problem as Jitsi Meet Electron](https://github.com/jitsi/jitsi-meet-electron/issues/608), where the preview image is broken even though the share button works.

[As discussed extensively here](https://github.com/flathub/org.chromium.Chromium/issues/121), when on Wayland, devices with dedicated gpus (notably AMD) might experience segfaults when using experimental (not fully enabled by default in any distro I know of) DMA-BUF PipeWire screencasting.  Since DMA-BUF screencasting will not be fully enabled by default until issues discussed there are fixed, I don't see this as blocking for Element.

### Operating system

Linux

### Application version

Element version: 1.8.1 Olm version: 3.2.3

### How did you install the app?

Flatpak, will affect DEB as well.

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
@vchernin, I've submitted https://github.com/vector-im/element-desktop/pull/256. I don't have a Wayland setup, so I can't really test this. In case you were able to try out the PR yourself and test it, it would be great. But don't worry about it if you don't know how to compile Element desktop/don't have time for it

**Comment by vchernin** [comment]
@SimonBrandner wow thanks for doing this so quickly! I do think your fix should work given it's the same as Jitsi's.

I tried using [recent work in Flatpak to build from source](https://github.com/flathub/im.riot.Riot/pull/205), but that wasn't as trivial I was hoping for. And I tried reading over the build instructions, but that might take me some time to figure it out...

If anyone who is more familar with Electron can build this and try it out on Wayland please do. And then this should be mergeable :)

**Comment by dbkr** [comment]
Re-opening since it's untested - let's close this once we know it works.

**Comment by SimonBrandner** [comment]
> I've merged the PR so this will be in tomorrow's nightly if you could give it a test. Follow instructions on [element.io/get-started](https://element.io/get-started) but instead of `https://packages.riot.im/debian/`, use `https://packages.riot.im/nightly/` or just grab a deb from there for a one-off non-updating build).

You should also be able to do `sudo apt install element-desktop-nightly` (if on Debian)

**Comment by vchernin** [comment]
So I tested the current [nightly build](https://packages.riot.im/debian/pool/main/e/element-nightly/) (to confirm what happens before the flag was added). But in a Ubuntu 21.04 VM I can't start video calls due to no camera access, I'm sure it's possible to pass it through somehow but that seems overkill. Is there a trick to override this error? 
![image](https://user-images.githubusercontent.com/38842733/129951336-fa2ecdbb-ccf8-4885-89ef-5f18e11ddf2d.png)

Otherwise I'll just try in a live usb on real hardware.

**Comment by SimonBrandner** [comment]
Not without tempering with the code, live USB is probably the easiest way

**Comment by SimonBrandner** [comment]
But you should be able to screen-share in voice calls if both sides support it

**Comment by vchernin** [comment]
> Not without tempering with the code, live USB is probably the easiest way

Thanks, will do.

> But you should be able to screen-share in voice calls if both sides support it

Yeah, I'll just use my phone with latest stable Element as that already worked when I tried with stable Flatpak.

**Comment by vchernin** [comment]
@SimonBrandner I've just tested build element-nightly-2021081901_amd64 and it works exactly as hoped! This issue can be closed.

Further info:
I had to install Debian on a spare laptop, couldn't find a live DEB-based distros with a live Wayland environment. 

The UX isn't perfect (as mentioned above) but it's much better than nothing. I'll open a follow up issue for improving that.

Thanks again!

**Comment by mYnDstrEAm** [comment]
Is screensharing supposed to work with this flag on Debian with Wayland? It didn't work but I can't try again right now and couldn't find another issue (please point me to the newer one if there is one).
