### ISSUE TITLE
While writing a message, I would like to expand the area in fullscreen.

### ISSUE THREAD

**Issue by nu111** [vector-im/element-web#18610]
#### What would you like to do?
Sometimes I need to write a not-so-short message. I would like to expand the "textarea" of the message I am writing in fullscreen.

#### Why would you like to it?
Because it's hard to write a long, structured text in the current available area.

#### How would you like to achieve it?
I think that a new icon would be enough
![Current text writing area](https://i.imgur.com/Wlnax41.png)

### Have you considered any alternatives?

I usually write the message in a text-editor and then pasted in Element. But it's not a fluid experience.

**Comment by SimonBrandner** [comment]
Thank you for your report.

It seems you're not the only one to have come across this issue, as a similar issue been reported previously - see https://github.com/vector-im/element-web/issues/5882. I'm going to close this issue now so we can focus on https://github.com/vector-im/element-web/issues/5882. Please watch, vote or comment on #??? if there is any additional information you can provide.
