### ISSUE TITLE
Broken stickers

### ISSUE THREAD

**Issue by K1D77A** [vector-im/element-web#18626]
### Steps to reproduce

I have two stickers with the same MXC but different widths and heights sent in the m.sticker event, the latest element update has broken the displaying of the sticker. 
![image](https://user-images.githubusercontent.com/10334164/129923345-f6337cfb-3c55-4f0d-9cc1-7fa2f02aa00a.png)

Important to note that it isn't broken on element mobile.

### What happened?

Here is the m.sticker event for the larger sticker.
```json
{ api : 'fromWidget', action : 'm.sticker', widgetId : 'stickerpicker', requestId : 'sticker-ready-3838248048', data : { content : { body : 'blepe-chungus', info : { w : 128, h : 119, mimetype : 'image/png', thumbnail_url : 'mxc://scyldings.com/wlKZJwdBQoCUVzkkwZCqViCN' }, url : 'mxc://scyldings.com/dDLbLtfPuKsZKxLBzcfdeIWI' } }, widgetData : { content : { body : 'blepe-chungus', info : { w : 128, h : 119, mimetype : 'image/png', thumbnail_url : 'mxc://scyldings.com/wlKZJwdBQoCUVzkkwZCqViCN' }, url : 'mxc://scyldings.com/dDLbLtfPuKsZKxLBzcfdeIWI' } } };
```
And the smaller one.
```json
{ api : 'fromWidget', action : 'm.sticker', widgetId : 'stickerpicker', requestId : 'sticker-ready-3838248048', data : { content : { body : 'blepe-chungus', info : { w : 64, h : 60, mimetype : 'image/png', thumbnail_url : 'mxc://scyldings.com/wlKZJwdBQoCUVzkkwZCqViCN' }, url : 'mxc://scyldings.com/dDLbLtfPuKsZKxLBzcfdeIWI' } }, widgetData : { content : { body : 'blepe-chungus', info : { w : 64, h : 60, mimetype : 'image/png', thumbnail_url : 'mxc://scyldings.com/wlKZJwdBQoCUVzkkwZCqViCN' }, url : 'mxc://scyldings.com/dDLbLtfPuKsZKxLBzcfdeIWI' } } };
```

### What did you expect?

The smaller sticker should simply be a smaller version of the larger. 

### Operating system

Linux

### Browser information

FF 78.12.0esr

### URL for webapp

https://app.element.io

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment]
The image URLs are the same in your two stickers which means the metadata is lying on one of them, so this is related to https://github.com/vector-im/element-web/issues/18616 in that our handling of incorrect image metadata has changed.

**Comment by t3chguy** [comment]
Cannot reproduce anymore

![image](https://github.com/vector-im/element-web/assets/2403652/35afc5d3-142e-491d-bf7b-382ec4fcafcc)
