### ISSUE TITLE
Weird avatars behavior on matrix server restart

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18622]
Whenever matrix.org server is restarted I see that on a lot of channels my client is trying to re-fetch either person's or room's avatar and fails miserably, which ends up on having `.` instead of the avatar, not even the colored circle with the letter inside of it. Client: https://app.element.io, Firefox 91.0.1 (64-bit), MacOS 11.5.2 (20G95)

**Comment by t3chguy** [comment]
This is an effective dup of https://github.com/vector-im/element-web/issues/23117
