### ISSUE TITLE
Clicking a permalink doesn't expand Membership Event List Summary

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18638]
Which makes it literally impossible to figure out where a permalink to a deleted event, membership event, etc goes

**Comment by ara4n** [comment]
What info is needed here? The bug looks clear to me: MELS (membership event list summary) blocks wre not expanded if a permalink links to an event within the block. So it looks like the permalink is broken.

**Comment by SimonBrandner** [comment]
Ah, sorry didn't get it first, thanks for the explanation! 

(I also should have asked...)

**Comment by Palid** [comment]
@turt2live Could you add the easiest possible way to reproduce this? We should definitely have a clear reproduction steps for each issue, even if it's simple.

**Comment by turt2live** [comment]
Steps to reproduce:
1. In a MELS, get a permalink to one of the events
2. Go to another room and use that permalink (such as from a message event or the `/goto` command)
3. Note that your timeline is dumped in the middle of the room without context

Expected behaviour:
The MELS should expand to reveal the permalink highlight.

This used to work, so is a regression.

**Comment by aaronraimist** [comment]
@turt2live This seems to have been fixed at some point. Works for me in 1.11.15

**Comment by turt2live** [comment]
I can believe that - closing until proven otherwise.
