### ISSUE TITLE
Favourites created in Spaces show up in Home

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18634]
### Steps to reproduce

1. Pin some rooms in a space as favourites
2. Select the "Home" space
3. See the rooms still visible as favourites

### What happened?

The rooms are still visible in the favourites panel.

### What did you expect?

Home contains rooms that aren't in a space, so I'd expect to not see favourites that are in a space.

I *would* expect this behaviour if I had "Show all rooms in Home" enabled, but I don't.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
This is intentional design, afaik. Home should be your place with high priority stuff -> _all_ favourites are there

**Comment by novocaine** [comment]
> This is intentional design, afaik. Home should be your place with high priority stuff -> _all_ favourites are there

Indeed it's intentional - but design agrees that this is indeed confusing

**Comment by t3chguy** [comment]
Spec `m.tag` `m.favourite` has no concept of Spaces

**Comment by novocaine** [comment]
One possible way to fix this is to change the UI so that it's more obvious that favourites aren't part of the Spaces heirarchy - at the moment, it seems like they are, because they sit in a panel with other objects that are (channels and people). 

So removing X-Spec-Changes as it ain't necessarily so, whilst noting that it *would* require a spec change if we actually *did* want to make favourites per-space.

**Comment by daniellekirkwood** [comment]
As this is working "as expected" I'm going to change this from an Enhancement to a Defect. 

I'll also be tagging with an IA tag so we can take a look at similar feedback and how we want to address the confusion of Favourites by Space/Global items in the layout.

**Comment by TuringTux** [comment]
I personally would really like to have per-space favorites, they would help me quite a bit to get my stuff sorted.

However, I understand that there is probably quite some work attached, so I definitely don't expect anything, just wanted to chime in with my two cents. 

Thank you for your development work, I really like Element a lot :)

**Comment by frandavid100** [comment]
This is amazing. Just a request: would it be possible to make these draggable, like other spaces are?

**Comment by t3chguy** [comment]
It'd be difficult because the spec for ordering only considers real spaces, and most clients won't have identical meta-spaces

https://github.com/matrix-org/matrix-doc/pull/3230 is the relevant MSC

**Comment by SimonBrandner** [comment]
I guess we could do some localStorage magic :thinking:
