### ISSUE TITLE
more compact 'Modern' layout stopped working

### ISSUE THREAD

**Issue by f0x52** [vector-im/element-web#18637]
### Steps to reproduce

Settings > Appearance > Show advanced
check and uncheck "Use a more compact ‘Modern’ layout", has no impact

### What happened?

nothing

### What did you expect?

to switch to the more condensed layout like before

### Operating system

Windows 10

### Browser information

Firefox Developer 92.0b4 (64-bit)

### URL for webapp

develop.element.io (latest)

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment]
This is working for me on nightly but not develop so looks like this regressed today, although I can't see any obvious candidates. Added release blocker so we don't ship this regression.

**Comment by Palid** [comment]
Another one related to the background blur. Taking.

**Comment by Palid** [comment]
Fixed kin https://github.com/vector-im/element-web/issues/18637
