### ISSUE TITLE
Temporary network failure may prevent E2EE keys from being shared

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18639]
### Steps to reproduce

1. During an operation that involves sending keys with another user, Alice experiences a network failure
2. Bob doesn't receive Alice's keys, and they might not be sent again for an undetermined amount of time

### What happened?

Bob will see messages like ** Unable to decrypt: The sender's device has not sent us the keys for this message. ** when trying to read Alice's messages, until such time as Alice's keys are sent again

### What did you expect?

The keys should be resent shortly after connectivity resumes.

### Operating system

Any

### Browser information

Any

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
Filing this issue to represent the likely user impact of https://github.com/matrix-org/matrix-js-sdk/issues/1866 in Element Web

**Comment by dkasak** [comment]
This one should now be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2549.
