### ISSUE TITLE
App layout/right panel interaction broken on medium-small screens

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18632]
### Steps to reproduce

View a room:

<img width="1008" alt="Screenshot 2021-08-19 at 10 43 28" src="https://user-images.githubusercontent.com/4626865/130047339-1c00dc28-6a84-4b52-875e-160862f82bc9.png">

Click on 'room info' button: 

<img width="1008" alt="Screenshot 2021-08-19 at 10 43 31" src="https://user-images.githubusercontent.com/4626865/130047353-475458c7-dab7-470d-b645-89a374770b8b.png">

### What happened?

1. Right panel is off canvas/screen.
2. Room header layout is borked, icons off canvas/screen.

### What did you expect?

Things to not go off screen.

### Operating system

macOS

### Browser information

Chrome, latest.

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by nadonomy** [comment]
Note, once you hit this at a medium-ish sized resolution it then breaks on larger ones too in weird and wonderful ways:

<img width="1283" alt="Screenshot 2021-08-19 at 10 57 26" src="https://user-images.githubusercontent.com/4626865/130049179-d75b9d56-199f-40ab-98e5-b68be2df845c.png">

Resizing the room list panel horizontally pushes the rest of the app out. The overall layout of the app feels fundamentally broken.

**Comment by dbkr** [comment]
Is this spaces specific or is this a regression that blocks release of the whole app?

**Comment by SimonBrandner** [comment]
My wild guess would be to blame https://github.com/matrix-org/matrix-react-sdk/pull/6262, so release blocker of the whole app.

**Comment by jryans** [comment]
Another version of this seems to be if you have a code block in the room, it will push the header icons off screen:

![image](https://user-images.githubusercontent.com/279572/130212961-70caeaa3-520a-4f55-a7a6-bb6dd86fe523.png)

**Comment by SimonBrandner** [comment]
Another way to repro is to fill the composer with a letter:

![Screenshot_20210820_124927](https://user-images.githubusercontent.com/25768714/130222555-73399332-259f-4bf3-bb3c-e851dd92bdde.png)
