### ISSUE TITLE
Display m.room.retention settings

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#18630]
### Steps to reproduce

1. Open a direct chat between two accounts (preferably both yours for easier reproducing)
2. Send messages from both
3. Send a state event from devtools `m.retention.policy` with whatever values you want.
4. Bonus: change the retention time.

### What happened?

The other account sees nothing to imply that messages are going to disappear after a specified time. The only visible change is the direct chat jumping on top of direct chats without any visible reason why.

### What did you expect?

I expected to see a warning that "disappearing messages" are enabled in the room and especially warning if they get disabled. Currently they are implemented on server-side with no warning making [gaslighting](https://en.wikipedia.org/wiki/Gaslighting) or other abuse possible especially towards less technical users.

See also #2497 for a complete implementation?

### Operating system

Fedora 34

### Browser information

Microsoft Edge 93.0.961.18

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by Mikaela** [comment]
To clarify, this issue also affects Element iOS and Element Android, not only Element Web.

Additionally I commented to https://github.com/vector-im/element-web/issues/2497#issuecomment-901371589 on what kind of a solution I would like to see.

**Comment by karolyi** [comment]
Mind you, room message retention handling is disabled per default:

https://github.com/matrix-org/synapse/blob/b5fef6054a3d5763a031440ad4c56fc97b12d2aa/synapse/config/server.py#L1201-L1205

**Comment by Mikaela** [comment]
However a lot of homeservers enable it for performance reasons while I think they generally use a year or so as global maximum policy.

On the issue in general I would like to add that clients have options to show redactions and some like FluffyChat even show message removals by default as opposed to room retention just resulting the messages being gone without a trace.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16625
