### ISSUE TITLE
"Enable encryption in settings" should not be shown to users that are unable to modify room encryption

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#18646]
### Steps to reproduce

1. Join an invite-only room where you don't have permission to modify encryption settings.
2. Be shown the following warning:

![image](https://user-images.githubusercontent.com/1342360/130156702-9819eaa8-8a7a-46d4-bf4e-456f3e23db15.png)

3. Click "Enable encryption in settings"
4. Find that the setting cannot be modified, as one does not have permission to do so.

### What happened?

I became confoozed.

### What did you expect?

The "Enable encryption in settings" link should not be shown if the user does not have permission to modify room settings.

Additionally, the text is a bit odd, as this occurred in a room with 4 other users; so this isn't really a private message. It's just an invite-only room.

### Operating system

Arch Linux

### Application version

Element Desktop 1.7.34

### How did you install the app?

Arch Linux User Repository

### Have you submitted a rageshake?

No

**Comment by Mint-6263** [comment]
Ok:kissing_heart:
