### ISSUE TITLE
Space panel shifts when vertically resizing window

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18640]
### Steps to reproduce

Resize the window vertically

### What happened?

https://user-images.githubusercontent.com/48614497/130107857-efd95904-7af8-4a4c-b824-05236c5fd8c8.mp4

### What did you expect?

The space panel should remain a fixed width while resizing the window

### Operating system

NixOS unstable

### Browser information

Firefox 91.0

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
This one's probably related to backdrop, I'll take it.
