### ISSUE TITLE
All rooms don't show all rooms except I explicitly check "Show all rooms"...?

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#18654]
### Your use case

Don't know whether this is just a translation issue or a wording issue in general or a functional thing, but in the German version, if I hover over the top-left "Home" button (house icon), I get a tooltip "Alle Räume" (All rooms). If I left-click it I only see 1 room. If I right-click it, I see a context menu where I can select "Show all rooms". If I check that, I now really see all rooms. *Scratches head*...?

**Comment by ShadowJonathan** [comment]
Probably an outdated translation?

**Comment by SimonBrandner** [comment]
> Probably an outdated translation?

Yeah, sound like that, though it appears to be correct in Weblate, let's wait for another release and see then

![Screenshot_20210820_130311](https://user-images.githubusercontent.com/25768714/130224121-c98a5825-1b28-4f55-8ddd-c4b5140d603b.png)

**Comment by k0tyk** [comment]
Reproducing this on https://develop.element.io/ with Element version: 211f48002759-react-cd04799cb496-js-bae883a89198 using an account `@k0tyk:matrix.org` that doesn't have any spaces but is present in multiple rooms:

![Peek 2021-12-22 17-06](https://user-images.githubusercontent.com/96536343/147113860-7a94b3fe-a8de-45ba-be58-848c0dab4506.gif)

Relevant fragment of the `#element-web:matrix.org` discussion:

Sascha: "What exactly is the purpose of the "all rooms" toggle above the room list in element web? :/"

t3chguy: "changes the behaviour of the Home space between All rooms & Home. only really does anything if you're in Spaces"

Суспільне Надбання: "Probably supposed to be that way, but toggling it makes all my rooms disappear from Home until I refresh the page. Toggling it multiple times, that is 😄 Just once seems to do nothing indeed. Same room-disappearing behavior when signing out and back in again"

t3chguy: "please file a bug report"

**Comment by robintown** [comment]
@k0tyk That appears to be a different bug, please file a separate issue if you are still experiencing it.

@rgpublic Are you still experiencing this?

**Comment by k0tyk** [comment]
> That appears to be a different bug

No... My screencast showed how to reproduce the English
version of the string the topic starter saw, and when
it appeared, and what other things glitched when it was
visible. Without that context, the issue looks like an
outdated translation, which it is not.

Please unflag it because the flag effectively hides it
from all the readers not signed into the proprietary
service all the time. The off-topic flag is meant for
disruptive content, not good-faith attempts to help
debug and discuss.

**Comment by rgpublic** [comment]
@robintown I think this is solved. The tooltip now correctly depends on whether "Show all rooms" is checked or not. If it's not checked then the tooltip just says "Startseite" (German for "homepage"). Only when "Show all rooms" is checked then the tooltip says "All rooms". Makes sense now, I guess.
