### ISSUE TITLE
Unverified session UI implies that it can successfully request encryption keys

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18652]
### Steps to reproduce

1. Log into a new session
2. "Verify this login" -> "Skip"
3. "Are you sure?" -> "Skip"
4. View an encrypted room with a backlog

### What happened?

![Screenshot from 2021-08-20 10-24-06](https://user-images.githubusercontent.com/51663/130212015-d2943e47-7e2a-4e18-88d6-69fa071a3dfd.png)

### What did you expect?

This session will not be able to successfully request encryption keys until it is verified so the error message should not let me re-request keys. The error message should tell me to verify my session first.

> :shield: ** Unable to decrypt: you have not verified this session.**
> [Verify this session](link to popup) using one of your other sessions to request encryption keys.

Or

> :shield: ** Unable to decrypt: the sender's device has not sent us the keys for this message.**
> [Verify this session](link to popup) using one of your other sessions to request encryption keys.

Complicated because they need to verify against the correct session. Maybe we can assume that all their other sessions are verified against each other? Then we could check if this session is not verified against any other session before showing the above error. The bug could still persist for people who has ended up with two sets of sessions which are not verified against each other.

S-Major because clicking the "re-request encryption keys" fails silently so user is unaware that there is a problem and not able to try a workaround.
O-Frequent because it happens every time a new session is started and verification is skipped (based on other tickets and chat, verification is confusing to many new users).

### Acceptance criteria
- [ ] Error message for an unverified session communicating that session must be verified before a successful key request is possible.

### Out of scope
Verified session failing to request keys because it is not verified against the needed sessions - may need new issue but might not be resolvable.

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

Related: https://github.com/vector-im/element-web/issues/18881

**Comment by richvdh** [comment]
We no longer have these "re-request encryption keys" buttons, so this is resolved.
