### ISSUE TITLE
Encourage users to provide 3PID so their friends can find them

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18658]
### Your use case

Element doesn't strongly encourage users to provide 3PID on sign-up, and so many users don't supply it.

One of the strengths of Matrix and Element is that you don't need to provide a 3PID to use it, which is ideal if you are concerned about privacy and don't want to be identified. If, on the other hand, you're less concerned about being tied to another identity, and more interested in being discoverable by friends also on the network, it probably would suit you better to provide a 3PID.

This has a particularly strong effect on new users, who will be more likely to continue using Matrix and Element if they can immediately find some friends to talk to on it.

Element Web should make a more eloquent, nuanced case to new users that providing 3PID is a good idea, so that their friends can find them more easily. Supplying 3PID should remain clearly optional, but the benefits of providing it should be clearer and friction of supplying it should be minimised.

### Have you considered any alternatives?

1. We could suggest people provide their real name to be more discoverable (a la Facebook, LinkedIn), but that doesn't work as well for matching and it raises more privacy concerns.

2. We could rely on people advertising their Matrix IDs in other places, like people do their Twitter handle, but it could be a while before that catches on

### Additional context

This is the current Element Web signup screen

<img width="438" alt="Screenshot 2021-08-20 at 12 47 18" src="https://user-images.githubusercontent.com/57377/130229850-5f1d8ff3-8b86-4d3a-9766-e3e06d89d7d9.png">

Suggestions:

1. Make email the first field in the form, remaining clearly optional
2. Improve the copy to make a stronger case for supplying an email address, and make it clear we don't use email addresses for marketing purposes, share it with others etc
3. Auto-generate an overridable matrix username based on the email address so that people don't have to fill in three things

We could potentially also consider easily-dismissable-forever prompts in app suggesting people enter 3PID if they've been using the app for a little while and trust us. For example, it might not be a great idea to ask for a phone number on signup, but people might be quite okay with it after using the app for a little while and wishing more of their friends could find them on matrix.

**Comment by kittykat** [comment]
Note that email is currently a compulsory field for the matrix.org homeserver

**Comment by novocaine** [comment]
> Note that email is currently a compulsory field for the matrix.org homeserver

I didn't realise! Thanks, adapting the ticket then
