### ISSUE TITLE
Do not show toggle/editable text field in room settings for things users aren't allowed to change 

### ISSUE THREAD

**Issue by peter-czy** [vector-im/element-web#18656]
### Your use case

In rooms where I don't have permission to change certain room settings, I still see a toggle (although grey).

///
![2021-08-20_12-18](https://user-images.githubusercontent.com/81222469/130219972-ed2c3b2c-cda8-42a9-8ba0-da1baf200b15.png)
///
+
///
![2021-08-20_12-18_2](https://user-images.githubusercontent.com/81222469/130219993-b3d8cd73-20a8-4231-9b37-610edaf4b473.png)
///
Also a multiple selector option (which I cannot use)

///
![2021-08-20_12-19](https://user-images.githubusercontent.com/81222469/130220001-6ded04d4-05e0-4be6-9c02-fe098a6b5bfa.png)
///
+
///
![2021-08-20_12-19_1](https://user-images.githubusercontent.com/81222469/130220073-2c0ccd3e-19e7-41aa-8230-f6f585558ccc.png)
///
Also, room name and description should not be displayed in an editable text box.
///
![2021-08-20_12-18_1](https://user-images.githubusercontent.com/81222469/130220427-150289e3-f562-48dc-95ca-82571841e948.png)
///

--> Overall, room settings need some design changes to make everything look simpler.

**Comment by SimonBrandner** [comment]
This is very much intentional, without this there would be no way for you to know the room's settings. While you might be able to figure out some stuff from different places, the settings are a way to view all the settings at once

**Comment by dbkr** [comment]
This would be a design change so whilst it might be something we'd consider, it isn't something we'd track in the issue tracker.
