### ISSUE TITLE
Unable to manage rooms in any spaces where I am admin

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#18667]
### Steps to reproduce

I don't know how to trigger this in the first place, it just randomly started happening earlier today

### What happened?

I did a bunch of reordering of my spaces today when switching from my own Element spaces to the official ones. But at some point, I completely lost the ability to manage rooms in any spaces where I am admin. The Add and Remove buttons are highlighting etc when expected (for example, Remove does light up when selecting a room), but they are no longer clickable. The mouse pointer also doesn't change when hovering over the buttons This persists over Clearing cache and browser reload. It applies to all my sessions on develop, but seems to work on the stable desktop app.

### What did you expect?

Working buttons

### Operating system

macOS Big Sur 11.4 (20F71) and Arch Linux

### Browser information

Firefox 91.0.1 (64 bit) and Firefox 90.0.2 (64-bit)

### URL for webapp

https://develop.element.io/

### Have you submitted a rageshake?

Yes

**Comment by Twi1ightSparkle** [comment]
Also applies to the "Mark as (not) suggests" button btw

**Comment by Twi1ightSparkle** [comment]
Also works with a brand new session on app.element.io

**Comment by Twi1ightSparkle** [comment]
And now 6 hours after it stopped working it has randomly started working again on develop... :confused:

**Comment by Palid** [comment]
@Twi1ightSparkle it could've been due to my mistake, the backdrop filter PR made a ton of layouting regressions. if it won't be reproducable anymore let me know and we can close it!

**Comment by Twi1ightSparkle** [comment]
I'm currently unable to reproduce this. I'll close it for now and reopen if I manage to trigger it again later.
