### ISSUE TITLE
Wide images push messages view to be wider then the window

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18662]
### Steps to reproduce

1. Resize element to be reasonably narrow (mine is 1001px)
2. Send a wide image into a room, eg. https://matrix-client.matrix.org/_matrix/media/r0/download/maunium.net/OGoPiFhgdixoDgvUSHWAHijx

### What happened?

Image is smashed right up against the right hand side of the window, pushing the read receipt gutter and the '...' button of the hover toolbox off the right hand side.

Before:
<img width="678" alt="Screenshot 2021-08-20 at 15 18 40" src="https://user-images.githubusercontent.com/986903/130247645-0aff6232-e548-4ab4-96fe-15f5acafb4d2.png">

After:
<img width="712" alt="Screenshot 2021-08-20 at 15 18 23" src="https://user-images.githubusercontent.com/986903/130247601-fd951b1e-4434-4652-9fd5-dd9b23c9f979.png">

### What did you expect?

The 'before' screenshot

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment]
This is even worse with wide code blocks which push the content even wider: the only way to view the rest of the message below the code block is to expand the window:

<img width="714" alt="Screenshot 2021-08-20 at 15 51 30" src="https://user-images.githubusercontent.com/986903/130252218-b4758dc1-cbba-40fb-894b-1f1c67635acd.png">

**Comment by Palid** [comment]
@dbkr https://github.com/matrix-org/matrix-react-sdk/pull/6652 does this fix it?

**Comment by dbkr** [comment]
ah, it does.
