### ISSUE TITLE
Getting a weird background experience in room list with my profile avatar

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#18660]
### Steps to reproduce

1. Upload my profile pic for example https://chagai.website/me.jpg

### What happened?

Getting a weird background experience in room list with my profile avatar

![image](https://user-images.githubusercontent.com/31655082/130245120-6ad7d8ae-30d4-4422-9120-0b866a022658.png)

### What did you expect?

A nice experience

### Operating system

Windows

### Browser information

Chrome Version 92.0.4515.131 (Official Build) (64-bit)

### URL for webapp

merged develop branch to a private frok yesterday

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
@gsouquet I think it should be slightly better now, but I'm not 100% sure this is entirely mitigated.

**Comment by chagai95** [comment]
I can check, we used some css to remove it 🙈

**Comment by kittykat** [comment]
@chagai95 I'm going to close this issue as we haven't heard back and it should be fixed by now. If you are still experiencing problems, please drop one of us a message to reopen it.
