### ISSUE TITLE
Threads Prototype

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18663]
Figma: https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads
Exploration Document: https://docs.google.com/document/d/18oYXibEWM6Vl7RW55zkmxJL9BVnF9IG0BJE9T1vewUI/edit

**Comment by ShadowJonathan** [comment]
@novocaine both documents are non-publicly-readable, i understand internal processes, but i think it'd be transparent to somehow make these publicly readable.

**Comment by novocaine** [comment]
> @novocaine both documents are non-publicly-readable, i understand internal processes, but i think it'd be transparent if these are world-readable.

Hi @ShadowJonathan - sorry, we won't be making these internal designs public until they're in a sufficiently mature state for opening up the wider conversation.

This ticket was actually created in error - I'm experimenting with zenhub epics for grouping work and didn't expect that this would result in a public ticket.

**Comment by ShadowJonathan** [comment]
Understandable, sorry for the extra workload then
