### ISSUE TITLE
After you upgrade a room to become a private space, you need to reopen settings in the new room

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18677]
### Steps to reproduce

1. Go to room settings -> Security and Privacy
2. Change access to Space members and confirm the dialog

### What happened?

The room seems to upgrade in the background, the dialog closes, then .. nothing happens. You're just dropped back to this

<img width="605" alt="Screenshot 2021-08-20 at 19 05 40" src="https://user-images.githubusercontent.com/57377/130275982-aad755fc-2938-488e-ae9d-e8b7c1a8e543.png">

If you close settings then open them for the upgraded room, the radio button still isn't selected, but the upgrade prompt is gone:

<img width="611" alt="Screenshot 2021-08-20 at 19 08 37" src="https://user-images.githubusercontent.com/57377/130276006-11e59bff-fc97-464b-8ab1-7026e8f0e129.png">

Then if you then click the radio button you can select which spaces can access the room, confirm, and the radio button selects as you'd expect.

### What did you expect?

I shouldn't have to reopen settings to set up the room's space members config.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

https://app.element.io

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
@niquewoodhouse can you suggest what the flow should be instead please?

**Comment by niquewoodhouse** [comment]
Some suggested iterations to improve the flow.  

**Be redirected in the background to the new room with the same settings screen open.**

In terms of this exact flow, this would be probably the most helpful change for a user.  We can possibly safely assume their intention is to mark this room as `Space members`, as this upgrade button is closely associated with that option.  

Example (I'm sure it wouldn't work exactly like this, just trying to illustrate the idea)

https://user-images.githubusercontent.com/1587166/131986936-5bff0bac-ba1e-4bcb-9478-332519733c75.mp4



I did quickly consider some alternatives (listed below) but dismissed them for a few reasons.

_________

**When a room is upgraded, show in the content a link to the new room and the new room's settings.**

Could be easily missed.  Unclear how to decide the rules for when/where it shows.  Would require a lot of interaction and effort from the user.  

**When you upgrade the room, have a confirmation screen that lets users be directed to the new room's settings screen.**

Increases the number of interactions for the user, there's a chance people wouldn't go to the settings of the room, unless you made that the primary CTA.


https://user-images.githubusercontent.com/1587166/131996607-fa0ea463-c760-48db-9190-a3c7ce900597.mp4
