### ISSUE TITLE
Getting an invite link for a space shouldn't open a browser

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18674]
I mostly just want the link to drop into chat without inviting a specific person. The spaces are all set up with `restricted` join rules so the expectation is a bit different from an invite only or public space

**Comment by MadLittleMods** [comment]
What does a current space invite link look like?

Is there a way we can make these `matrix.to` or `matrix` protocol/schema URLs? For example, I'd prefer to open in browser but should be whatever preference/app handler is set.

**Comment by turt2live** [comment]
It's currently a matrix.to link: 
![image](https://user-images.githubusercontent.com/1190097/130525963-afdaaa60-c02a-420e-be6a-8bd6fa715f6e.png)

I would expect this to copy to my clipboard though instead of opening a new tab (particularly when clicking from the desktop app)

**Comment by MadLittleMods** [comment]
👌 Ahh I see, perfect screenshot!

This flow seems to be fine for a browser user as I can just copy from the address bar but 👍 on being able to copy URL directly.

**Comment by t3chguy** [comment]
This matches the behaviour of the room invite dialog, IMO should be consistent over both

**Comment by SimonBrandner** [comment]
> This matches the behaviour of the room invite dialog, IMO should be consistent over both

Agreed, though I would prefer the behaviour proposed here for rooms too

**Comment by daniellekirkwood** [comment]
As the behaviour is "as expected" and matches that of the Room invite/share, I'm going to mark this issue as Enhancement.

**Comment by t3chguy** [comment]
We now show a copy prompt for Spaces

![image](https://user-images.githubusercontent.com/2403652/146194770-2599da6f-a8fe-481d-a583-4d3da5f38e22.png)
