### ISSUE TITLE
Explore rooms layout is wrong

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18678]
### Steps to reproduce

Go to the explore rooms page of any space

### What happened?

![flex](https://user-images.githubusercontent.com/48614497/130278973-73dfe770-ca5f-45f6-b0c8-9e8c21a1b791.png)

![flex2](https://user-images.githubusercontent.com/48614497/130279252-4412583c-d769-486a-89a7-357eb6ea48f2.png)

In the second image, the content is stuck in place and does not scroll

### What did you expect?

The explore rooms page should fit to the size of the container and not be centered

### Operating system

NixOS unstable

### Browser information

Firefox 91.0

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
@robintown can I get an invite to this space for @paliddev:matrix.org ? Will be much easier to debug.

**Comment by robintown** [comment]
@Palid It's the Bridges subspace of #community:matrix.org, but the issue occurs for me on all spaces, regardless of size or publicity

**Comment by Palid** [comment]
@robintown should be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6654
