### ISSUE TITLE
Autocomplete covers too much of the timeline

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18682]
### Steps to reproduce

Trigger autocomplete by typing `:` `@` or `#` in the composer

### What happened?

The autocomplete overlay covers half of the entire timeline, making it very difficult to reference earlier messages

![Screenshot 2021-08-21 at 12-52-18 Element Test room](https://user-images.githubusercontent.com/48614497/130329274-74ed2331-428d-4b75-9dc7-77f4cf19f63e.png)

### What did you expect?

The autocomplete overlay should be significantly shorter and/or narrower, to avoid covering as much of the timeline

### Operating system

NixOS unstable

### Browser information

Firefox 91.0

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
It's `50vh`, so `25vh`?

**Comment by robintown** [comment]
Sounds good to me

**Comment by SimonBrandner** [comment]
`25vh` seemed too small, what do you think of `35vh`?

![Screenshot_20210821_190115](https://user-images.githubusercontent.com/25768714/130329475-977e404e-d52e-46b0-bfa4-22bea69753d4.png)

**Comment by robintown** [comment]
Also looks fine I suppose
