### ISSUE TITLE
Edit a message to no content should delete the message

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#18684]
#### What would you like to do?
I want to delete a message by editing its contents to be empty.

#### Why would you like to it?
It can be easier to delete a message by editing the message and removing all content.

For example, to delete the previous message would just be:
* `UP` (edit previous message)
* `CTRL` + `A` (select all)
* `CTRL` + `X` / `BACKSPACE` / `DELETE` (remove the content)
* `ENTER` (prompt for deletion reason)

#### How would you like to achieve it?
On the client-side, editing a message to have empty contents should instead leave the edit view and prompt to delete the message instead.

### Have you considered any alternatives?

N/A

### Additional context

The following applications have this behavior already:
* Discord
* Slack
* Rocket.Chat

**Comment by SimonBrandner** [comment]
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously - see https://github.com/vector-im/element-web/issues/11024. I'm going to close this issue now so we can focus on #???. Please watch, vote or comment on https://github.com/vector-im/element-web/issues/11024 if there is any additional information you can provide.
