### ISSUE TITLE
HEIC images don't render on Windows even when codec pack is installed

### ISSUE THREAD

**Issue by ajkessel** [vector-im/element-web#18699]
### Steps to reproduce

HEIC images show up on iOS Element but not Windows Element. On Windows, I just see a blank space where the image should be.

Windows does not ship with HEIC support natively but it can be installed for $0.99 from https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7 or for free per instructions here https://www.reddit.com/r/Windows10/comments/j58y6f/no_longer_free_windows_10_hevc_video_extensions/gggdy2z?utm_source=share&utm_medium=web2x&context=3

After installed HEIC support, at least some other Windows app (such as the native Photos client) display HEIC images, but Element Desktop still does not.

Can Element leverage this codec to render these images once it is installed in Windows?

### What happened?

HEIC images don't appear

### What did you expect?

HEIC images should appear

### Operating system

Windows 10

### Application version

Element version: 1.8.1 Olm version: 3.2.3 

### Have you submitted a rageshake?

No

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/9143 and https://github.com/vector-im/element-web/issues/18519 which were both closed because it's more of a browser support problem: https://caniuse.com/heif
