### ISSUE TITLE
Provide a URL to force a logout

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#18693]
#### What would you like to do?

Have a single URL path to be able to logout of the web client.

#### Why would you like to it?

A user has an SSO portal (ie, a place where they can manually logout their SSO). If they logout there, they would like to be able to logout Element too.

#### How would you like to achieve it?

A single endpoint to force a logout.

### Have you considered any alternatives?

*Not* logging element out. This might be better in case the user has no devices to encrypt to.

**Comment by t3chguy** [comment]
Could be abused by users being misled into clicking a link and possibly losing megolm session keys

**Comment by benparsons** [comment]
Closing this as it's a bad idea.
