### ISSUE TITLE
Can't have forward slash (/) under Settings → Notifications → Mention and keywords

### ISSUE THREAD

**Issue by SethFalco** [vector-im/element-web#18707]
### Steps to reproduce

1. Navigate to Settings → Notifications → Mention and keywords
2. In the Keyword field, input any text containing a forward slash. (`/`)
3. Select Add

### What happened?

A modal appears with the following text.

> **Error saving notification preferences**
> 
> An error occurred whilst saving your notification preferences.

And the content of the Notifications setting changes to.

> **Notifications**
> 
> There was an error loading your notification settings.

![Peek 2021-08-24 10-27](https://user-images.githubusercontent.com/22801583/130583746-0fa6614c-514c-4149-90e4-0509af558828.gif)

---

I can just flip to another page, then return to Notifications settings to access the page again. (The keyword does not get added.)

### What did you expect?

I would expect the keyword to get added as it would for any other keyword.

If for whatever reason, not that I can think of one, a `/` cannot be used in a keyword for a logical/technical reason, then I would expect the field to have validation explicitly warning the user. (Or handle it gracefully one way or another.)

### Operating system

Ubuntu 20.04

### Application version

Element version: 1.8.1 Olm version: 3.2.3

### How did you install the app?

apt: `element-desktop/unknown,now 1.8.1 amd64 [installed]`

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
It seems that `/` is rejected by backend, we need to add some front-end validation for that too.

**Comment by Palid** [comment]
It also shouldn't just show `There was an error loading your notification settings` after showing modal that something has failed.

**Comment by Palid** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/18778

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18839
