### ISSUE TITLE
🐱‍🐉treated as "cat dragon" by font rendering

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18704]
### Steps to reproduce

1. Receive a message with 🐱‍🐉 in it
2. See this:
![image](https://user-images.githubusercontent.com/1190097/130530285-3475f95f-a6eb-43ad-b97f-e8fe75e8bed7.png)
3. Despair

### What happened?

see above

### What did you expect?

not the above

### Operating system

Windows 10

### Application version

Nightly (2021-08-23)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

No

**Comment by turt2live** [comment]
I have since been referred to https://emojipedia.org/dino-cat/ which makes this possibly invalid as an issue.

**Comment by MadLittleMods** [comment]
For reference, I was the person using the "dino cat" emoji as an example of weird Windows emoji

https://emojipedia.org/dino-cat/ says "This emoji is included in Windows 10 as a proprietary ZWJ Sequence which is not supported by other vendors." and I'd be in favor of not supporting it.
