### ISSUE TITLE
🧘‍♂️ emoji not recognized

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18703]
### Steps to reproduce

1. Received a message with 🧘‍♂️ in it
2. Copy/pasted it into the emoji picker to see what it was
3. No results (insert despair)

### What happened?

despair at unknown emoji

### What did you expect?

the emoji to be recognized

### Operating system

Windows 10

### Application version

Nightly (2021-08-23)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Indeed you can only search for the ungendered one 
<img width="148" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/56106885-7e65-43ce-9e3e-384323919252">
(right-most)
