### ISSUE TITLE
File uploads from Sailtrix are invisible

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#18702]
### Steps to reproduce

1. Send an image from Sailtrix
2. Look at Element Web
3. See "Tätä viestiä ei voi ladata (m.room.message)Lähetä lokit"

### What happened?

I see a message "Tätä viestiä ei voi ladata (m.room.message)Lähetä lokit", "This message cannot be loaded (m.room.message) Send logs.

### What did you expect?

I expected to see the screenshot.

### Operating system

Fedora 34

### Browser information

Edge 93.0.961.27

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

Yes, after opening the issue first.

**Comment by Mikaela** [comment]
@tulir said:

> looks like a recent-ish regression
> the problem is that sailtrix doesn't send the info object, but that object isn't required by the spec
> so the bug is in element web and matterbridge

**Comment by tulir** [comment]
![image](https://user-images.githubusercontent.com/4224639/130525573-bd34075f-0755-45b6-9757-700adbd47903.png)
