### ISSUE TITLE
¡Algo ha fallado!

### ISSUE THREAD

**Issue by Jorget778** [vector-im/element-web#18701]
¡Algo ha fallado!
Por favor, crea un nuevo nodo en GitHub para que podamos investigar este error.

Si has enviado un error a GitHub, estos registros pueden ayudar a localizar el problema. Contienen información de uso de la aplicación, incluido el nombre de usuario, IDs o alias de las salas o grupos visitados y los nombres de otros usuarios. No contienen mensajes.

**Comment by turt2live** [comment]
Please use the issue template.
