### ISSUE TITLE
Slightly different blurred-background behavior on develop compared to prod

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18708]
Compare below avatar on production (https://app.element.io/) and current develop (https://develop.element.io) with different  aspect ratios.
![rainbow_vertical](https://user-images.githubusercontent.com/3636685/130583831-c194a50e-4265-470e-a8d3-9f7e74246d36.png)

Prod:
<img width="549" alt="CleanShot 2021-08-24 at 10 49 28@2x" src="https://user-images.githubusercontent.com/3636685/130587155-0223cfe6-b766-4e03-908b-5a5a759d28cb.png">
Develop: 
<img width="549" alt="CleanShot 2021-08-24 at 10 49 42@2x" src="https://user-images.githubusercontent.com/3636685/130587191-86e7f6e2-f19c-4a49-b946-a0338c29eef7.png">

Prod:
<img width="528" alt="CleanShot 2021-08-24 at 10 50 23@2x" src="https://user-images.githubusercontent.com/3636685/130587250-f13caad4-be86-4410-89be-a9111ed11ecc.png">
Develop:
<img width="532" alt="CleanShot 2021-08-24 at 10 50 29@2x" src="https://user-images.githubusercontent.com/3636685/130587274-95717bc1-714b-4b46-b32f-adbad91ecdd9.png">

**Comment by Palid** [comment]
@janogarcia is this acceptable, or should we try to normalize it even more? I think this is fine.

**Comment by janogarcia** [comment]
@Palid Just checked it with my avatar and it seems the develop version is throwing a more discernible — potentially distracting — image, see below.

I’d suggest being a bit more aggressive with the blur intensity. This is the value I came up with after comparing the rendering for the current production and develop versions.

```
:root {
    --lp-background-blur: 40px;
}
```

---

**Develop**

![develop](https://user-images.githubusercontent.com/60790/130829886-b1c458fc-3f8d-4959-847a-775ec7187f02.png)

**Production**

![production](https://user-images.githubusercontent.com/60790/130829932-faa98bdc-0007-447a-833d-9c871398c098.png)
