### ISSUE TITLE
Room list is cut off and misaligned

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18723]
### Steps to reproduce

Look at the room list

### What happened?

![Screenshot 2021-08-24 at 09-34-02 Element #element-dev matrix org](https://user-images.githubusercontent.com/48614497/130626205-c8e95d38-a921-419c-b3de-d1ff90e70326.png)

### What did you expect?

The room list should not be cut off and misaligned

### Operating system

NixOS unstable

### Browser information

Firefox 91.0

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Works fine without message previews

**Comment by SimonBrandner** [comment]
> Works fine without message previews

I take that back, enabling them just makes it worse

**Comment by Palid** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6669
