### ISSUE TITLE
Resize handle is shifted when I start resizing

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18725]
### Steps to reproduce

Resize the room-list

### What happened?

https://user-images.githubusercontent.com/25768714/130627488-c5e66d6f-aaf6-472d-96d2-8d28e1049227.mp4

### What did you expect?

It to behave normally

### Operating system

Linux

### Browser information

FF

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by robintown** [comment]
I can't reproduce, is that on latest develop with https://github.com/matrix-org/matrix-react-sdk/pull/6664?

**Comment by SimonBrandner** [comment]
Ok, it's gone now, weird - I loaded a develop a few seconds ago
