### ISSUE TITLE
GH action to move an issue to priority bugs is broken

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18727]
![Screenshot_20210824_154602](https://user-images.githubusercontent.com/25768714/130628247-582635ed-cb2c-488a-917b-3b635b9b4b7d.png)

**Comment by novocaine** [comment]
I think `T-Defect` should be reserved for user-facing defects ..

**Comment by novocaine** [comment]
(I think this is because we renamed the column)

**Comment by novocaine** [comment]
Should be fixed by https://github.com/vector-im/element-web/pull/18758
