### ISSUE TITLE
Add the ability to see online people

### ISSUE THREAD

**Issue by Ivaniku** [vector-im/element-web#18735]
I'm currently using element as my main chatting app for some time and I couldn't help but notice something very annoying.

You can't see when someone in your direct messages is online. It's impossible.

That's why I would love to see online statuses in element, since as far as I know matrix already exposes when someone is online and is in itself a very useful feature.

**Comment by SimonBrandner** [comment]
This already is a feature of Element but it's quite heavy on server performance, so some servers like matrix.org disable it. What homeserver are you using?

**Comment by Ivaniku** [comment]
> This already is a feature of Element but it's quite heavy on server performance, so some servers like matrix.org disable it. What homeserver are you using?

Oh I was using matrix.org, is there any way to enable it?

**Comment by SimonBrandner** [comment]
> > This already is a feature of Element but it's quite heavy on server performance, so some servers like matrix.org disable it. What homeserver are you using?
> 
> Oh I was using matrix.org, is there any way to enable it?

No, matrix.org has it disabled, if you want to have it enabled you need to use a homeserver that has it enabled. 

I would recommend asking around about using other homeservers and what benefits might that provide but I am going close this as this isn't an Element issue
