### ISSUE TITLE
Room-list blur causes poor performance of the app on desktop

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18730]
On today's Nightly, the app feels quite laggy with the blur on, when I disable the room-list blur the performance of the app gets much better. It doesn't feel the same way on develop with FF nor with Chromium. I have a feeling that before today's Nightly the performance of the app wasn't impacted by the blur

**Comment by SimonBrandner** [comment]
I can repro the same behaviour on my laptop. Both devices are Linux (Debian Bookworm)

**Comment by SimonBrandner** [comment]
I don't seem to be able to repro on Windows

**Comment by Palid** [comment]
@SimonBrandner just not to scare anyone: As you said on a chat, this does not reproduce on develop.

**Comment by SimonBrandner** [comment]
Will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6644
