### ISSUE TITLE
After disinviting user from Space they still appear in the People section

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#18737]
### Steps to reproduce

1. Right click on a space and click Invite Members
2. Invite someone
3. Disinvite them from memberinfo

### What happened?

A DM with them appears in the People section of the room list when viewing that space

After refreshing the tab it corrects itself

### What did you expect?

They should not appear in the Space since they are not members of the space

### URL for webapp

v1.8.1

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
From what you have experienced, would that member still be able to accept the invite or is it more a state issue on the client side?
That would change the severity of this issue quite drastically in my opinion

**Comment by aaronraimist** [comment]
I think it’s a very minor client side visual glitch.

**Comment by t3chguy** [comment]
I can reproduce this on both the inviting and disinviting edges
