### ISSUE TITLE
Bug when server responds with empty threepids

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#18731]
### Steps to reproduce

Use a server that responds with an empty json to the /account/3pid endpoint

Then try to open the notification settings

I think the bug is here: https://github.com/matrix-org/matrix-react-sdk/blob/485655966115dd13d249b795d31c3bbb620a3020/src/components/views/settings/Notifications.tsx#L483

threepids is not set when the json response is empty. Also see https://github.com/matrix-org/matrix-react-sdk/blob/485655966115dd13d249b795d31c3bbb620a3020/src/components/views/settings/Notifications.tsx#L134

### What happened?

Notification screen doesn't load

### What did you expect?

Notification screen opens

### Operating system

-

### Browser information

-

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Under what circumstances a server would return an empty response?

Just to confirm, are we talking about a completely empty body response or `{}` ?

**Comment by timokoesters** [comment]
I'm talking about {} in case there are no threepids
