### ISSUE TITLE
Citation ignores newlines

### ISSUE THREAD

**Issue by wknds** [vector-im/element-web#18740]
### Steps to reproduce

1. Copy paste a text block with newlines
2. Select all and click on citation button
![Bildschirmfoto_2021-08-25_14-55-46](https://user-images.githubusercontent.com/25268078/130795389-8db9752d-4893-4c3c-a1d7-7b4388ce61f8.png)
Brackets should be inserted now:
![Bildschirmfoto_2021-08-25_14-56-12](https://user-images.githubusercontent.com/25268078/130795567-3a03efa4-e80d-41bb-9525-b2f1d462b23c.png)
3. Send message

### What happened?

Newlines are ignored on the sent message resp. not displayed correctly.

![Bildschirmfoto_2021-08-25_14-56-31](https://user-images.githubusercontent.com/25268078/130795718-cebd0408-11dd-4944-8628-3d42eced4e5b.png)

### What did you expect?

Newlines should be respected on the displayed citation.

### Operating system

Linux, Android

### Application version

Desktop: 1.8.1 Olm version: 3.2.3 / Android: 1.2.0 Olm version: 3.2.4

### How did you install the app?

Riot repository / Fdroid

### Have you submitted a rageshake?

No

**Comment by yannicka** [comment]
This is a duplication of #18299. The information should be gathered in one ticket.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/18299
