### ISSUE TITLE
Opting in to Spaces beta via invites isn't smooth

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18744]
### Steps to reproduce

1. Don't be opted into the beta
2. Receive an invite to a Space
3. Click on the link
4. Opt in to the Spaces beta to accept the link
5. Wait for your web client to refresh
6. Observe there is no space in the space panel

### What happened?

App relaunches without joining the space or offering a clear way to quickly join.

### What did you expect?

Either to have a super obvious way to join the space (e.g. persist the URL path so the space preview is front and center post refresh, with a big fat join button) or to just simply join the Space and be looking at it.

This path may be redundant when Spaces are enabled by default, but we should discuss.

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
If this will be resolved by Spaces leaving beta, I don't think we need to take action at this point.
