### ISSUE TITLE
Don't default to user avatar for two member rooms

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18747]
### Your use case

I realise this issue is broader than Spaces. Filing this to specifically discuss within the context of Spaces and see if we can organise any quick wins in the coming weeks.

After creating a Space, it's expected to create rooms and invite people to them. While a room has 2 people, we use the other users avatar as the room avatar. In Spaces, this is incredibly unexpected and confusing.

Can we action a quick win to not do this when viewing Spaces, or more generally in Element?

### Additional context

<img width="222" alt="Screenshot 2021-08-25 at 10 11 56" src="https://user-images.githubusercontent.com/4626865/130805874-c7706fea-1cc1-410e-b3b3-ca27cf091df9.png">

Screenshot of a bunch of rooms unexpectedly inheriting @daniellekirkwood's avatar.

**Comment by andybalaam** [comment]
I think this might have already been fixed in https://github.com/matrix-org/matrix-react-sdk/commit/79daf615e4d8f99602c2c616baebf8d359a3e39e

**Comment by andybalaam** [comment]
@nadonomy are you able to re-test?

**Comment by novocaine** [comment]
@andybalaam That commit is from February at the start of the Spaces project, so I doubt that has fixed it..?

**Comment by andybalaam** [comment]
> @andybalaam That commit is from February at the start of the Spaces project, so I doubt that has fixed it..?

Hmm ... weird though because it contains a line of code that definitely appears to be intended to fix this when the room is in a space.

**Comment by SimonBrandner** [comment]
> > @andybalaam That commit is from February at the start of the Spaces project, so I doubt that has fixed it..?
> 
> Hmm ... weird though because it contains a line of code that definitely appears to be intended to fix this when the room is in a space.

Spaces are just rooms with special state events. That line is changing the behaviour in the case the room is a space _not_ when the room is in a space

**Comment by andybalaam** [comment]
> That line is changing the behaviour in the case the room _is_ a space _not_ when the room is in a space

Ah I see! Thank you.
