### ISSUE TITLE
Forgot Password non-obviously requires confirmation via email link, and then clicking a button in the tab

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18752]
### Steps to reproduce

Request a password reset via forgot password

<img width="708" alt="Screenshot 2021-08-25 at 14 39 40" src="https://user-images.githubusercontent.com/57377/130806539-ad570796-9922-4154-a82d-06af533f6fed.png">

Receive the email, open its link and click to confirm that you are you.

![reset-email](https://user-images.githubusercontent.com/57377/130807024-dc073480-43d1-40d8-9e6d-c72037f1a28f.jpeg)

The text displayed is `Your email has now been validated, please return to your client to reset your password. You may now close this window`.

Try to login with the new password - it doesn't work

### What happened?

It didn't work because I still need to click one more thing in the forgot password tab after doing the email thing

<img width="747" alt="Screenshot 2021-08-25 at 15 17 58" src="https://user-images.githubusercontent.com/57377/130807602-a8a0a8e8-22cd-421d-ad61-9efe4a763d93.png">

### What did you expect?

That my password would have been reset after clicking the link from the email, and not have to click anything else.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
Changing to an enhancement as this is how its currently designed..

**Comment by nadonomy** [comment]
@daniellekirkwood to consider as a part of upcoming forgot password travels.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23131
