### ISSUE TITLE
Not clear you're filtering across all spaces when filtering

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18753]
### Your use case

<img width="136" alt="Screenshot 2021-08-25 at 10 17 32" src="https://user-images.githubusercontent.com/4626865/130807732-a6f75e0c-48b8-4b03-8ffb-1036a5e5c67d.png">

While filtering for a Space, it's easy to mis-read that you're filtering with that Space only while we display the space name at the top of the room list.

We should try find quick wins to improve (remove or modify the space name while filtering?)

We should also be cognizant breadcrumbs break up the info architecture, although not sure we'll have a quick/immediate solution to this.

**Comment by SimonBrandner** [comment]
Related https://github.com/vector-im/element-web/issues/4658

**Comment by t3chguy** [comment]
> We should try find quick wins to improve (remove or modify the space name while filtering?)

We remove the space name nowadays

![image](https://user-images.githubusercontent.com/2403652/146026004-8f65891b-730d-422e-a61a-76e9f293d99d.png)

> We should also be cognizant breadcrumbs break up the info architecture, although not sure we'll have a quick/immediate solution to this.

This is also no longer an issue as much, especially with the Labs

**Comment by t3chguy** [comment]
Chatted with Nad oob and he deems this no longer an issue
