### ISSUE TITLE
Space home doesn't render correctly when panel is collapsed

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18754]
### Steps to reproduce

<img width="659" alt="Screenshot 2021-08-25 at 10 00 51" src="https://user-images.githubusercontent.com/4626865/130808335-22dd5b4d-712d-44c8-9b8b-634c8b5b0590.png">

1. View a Space home/summary screen on a small screen.
2. Observe broken layouts.

Note: The screenshot shows an extremely small viewport, but it's easy enough to break the layout on a 13" laptop with a reasonably sized window. 

### What happened?

The above.

### What did you expect?

Any of:

1. More generally in the app, receiving some kind of full screen info/warning when hitting low screen size breakpoints we don't formally support. This content should link to the mobile apps, taking inspiration from the mobile install guide screen.
2. Better responsive styling.
3. (Suggestion from @daniellekirkwood) Auto hide contextual panels (e.g. right panel) when resizing.

### URL for webapp

develop.element.io & desktop app (production)

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
Related: https://github.com/vector-im/element-web/issues/12203

**Comment by t3chguy** [comment]
I can't quite reproduce the same level of breakage
![image](https://user-images.githubusercontent.com/2403652/133252998-8588ae8f-392f-4067-82cd-0785e342e641.png)

But also note that at this size the app is unusable anyhow.

![image](https://user-images.githubusercontent.com/2403652/133253026-4f87759c-8b4d-4e8d-a5d1-311ef9e3d71c.png)

**Comment by SimonBrandner** [comment]
I think this was one of the room list background blur image regressions that might have been fixed

**Comment by novocaine** [comment]
Can't reproduce original breakage so considering this fixed
