### ISSUE TITLE
Can't create a room in a Space which isn't suggested

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18760]
### Your use case

Every room I create in a Space is automatically set as a suggested room.

I can't figure out how to create one which isn't. Might be a bug or PEBKAC.

If we're defaulting to 'Suggested' for all we should make this extremely explicit. Otherwise I might create a room with confidential info in the name or topic which would be seen by all members of a Space.

**Comment by t3chguy** [comment]
Yup, this is a defect, the intent was only for the initial rooms to be suggested, thereafter it being an opt-in toggle
