### ISSUE TITLE
Private spaces don't prompt to set an address

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18765]
### Your use case

We don't prompt users to set an address for private Spaces when creating them. The inconsistency with public spaces may be unexpected.

We should:

1. Get clarity on why. Is it because we're waiting on knocking? Is it because we're assuming users don't want to set addresses for private spaces?
2. Gather more insight from users.

**Comment by t3chguy** [comment]
It matches the behaviour on Private Room creation

**Comment by kittykat** [comment]
I feel like we decided that this wasn't an issue during the testing as we don't want private spaces/rooms to squat nice URLs so closing - please reopen if I am mis-remembering.
