### ISSUE TITLE
Input box (in space creation) uses monospaced font

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18766]
### Steps to reproduce

<img width="373" alt="Screenshot 2021-08-25 at 10 21 06" src="https://user-images.githubusercontent.com/4626865/130821763-f1522bff-73e9-4862-9782-950b2b14b51f.png">

Multi-line input when inputing description in a private space isn't using the right font. Is this specific to this input/screen? Is it an issue which affects all multi-line inputs?

### What happened?

See above.

### What did you expect?

See above.

### Operating system

macOS

### How did you install the app?

Production app/latest.

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
![Screenshot_20210825_180950](https://user-images.githubusercontent.com/25768714/130826251-4fdf5d98-4aa5-4a90-b82a-5faf6505c78b.png)

I don't seem to be able to reproduce

**Comment by novocaine** [comment]
I can't repro either

@nadonomy maybe you should have filled out *Application Version* .. ;)

**Comment by nadonomy** [comment]
> @nadonomy maybe you should have filled out _Application Version_ .. ;)

@daniellekirkwood can you confirm what app version this is happening for you in?

**Comment by t3chguy** [comment]
This is fixed by https://github.com/matrix-org/matrix-react-sdk/commit/f7818e01692229db352b1eaabbe147e19b5cadff#diff-8f68d8b124b4b690fd6653ef49401a58a0adad725415db7ffc6248384e2c4515R41
in future, an app version is critical for bug reports.
