### ISSUE TITLE
Private Spaces don't do several expected things

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18769]
### Steps to reproduce

This is true on develop.element.io connecting to matrix.org right now. It may not be true once we merge enabling Spaces by default. To review & discuss internally to potentially break out into multiple issues:

1. New rooms created in private spaces do not use v8, and need to be manually upgraded. This breaks user experience everywhere.
2. If you do need to upgrade rooms in a space, it's painful to do room by room. Should we add/consider bulk upgrades? E.g. In a space, on best effort of all rooms you admin?

### What happened?

See above.

### What did you expect?

See above.

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
> New rooms created in private spaces do not use v8, and need to be manually upgraded. This breaks user experience everywhere.

https://github.com/vector-im/element-web/issues/18722

**Comment by novocaine** [comment]
@nadonomy we think #1 is fixed by #18722 - I think #2 is an enhancement not a defect so maybe should be filed separately

**Comment by nadonomy** [comment]
@novocaine Sgtm. Filed https://github.com/vector-im/element-web/issues/18861.
