### ISSUE TITLE
New suggested rooms don't appear in room list

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18761]
### Steps to reproduce

1. View a Space.
2. Add a room to the Space, as a suggested room ([related](https://github.com/vector-im/element-web/issues/18760)).
3. Observe the room appear in Explore/Space Home after refreshing it.
4. Observe the room not appearing in the 'Suggested list' in the room list

### What happened?

The above.

### What did you expect?

Ideally, the room to instantly appear in the 'Suggested' section, the same way Invites instantly appear. Otherwise, at the least for the new room to refresh on _some_ action, e.g. when refreshing the view of the Space when switching Spaces.

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Given that you can only add rooms you are already in, and the suggested section only shows rooms which are not yet in, this is presumably from the PoV of others?
