### ISSUE TITLE
Guest option in private spaces is alarming

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#18776]
### Your use case

<img width="1107" alt="Screenshot 2021-08-25 at 17 03 52" src="https://user-images.githubusercontent.com/4626865/130825494-db764834-40d9-4dff-9d79-4ab4afc8bc3f.png">

1. Create a private space.
2. Go to space settings.
3. Observe that guest access is enabled in Settings.

This is scary and alarming.

### Suggested quick fix

Default this to 'off' when creating a private space.

**Comment by robintown** [comment]
Related: https://github.com/vector-im/element-web/issues/17366, https://github.com/vector-im/element-web/issues/9121
