### ISSUE TITLE
"and 108 others" in add rooms to space wizard step not aligned

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18784]
### Steps to reproduce

1. Create a new private space for Just Me
2. Filter onto something reasonable to scroll down on (in my case, `t2bot.io` which reveals about 200 Discord rooms)
3. Scroll down to the end of the section to where "and 108 others" would be

### What happened?

![image](https://user-images.githubusercontent.com/1190097/130861575-e95b09ab-2f73-4bdc-90ad-6841121402b5.png)

### What did you expect?

not that

### Operating system

Windows 10

### Application version

Nightly (2021-08-25)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
This was added by someone presumably without design input, it should probably get some.
