### ISSUE TITLE
Unknown rooms in restricted join rules lead to empty section in UI

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18780]
### Steps to reproduce

1. Have an admin change the join rules to restricted based on membership in an unknown room to you
2. Look at the room settings

### What happened?

![image](https://user-images.githubusercontent.com/1190097/130833434-8b06a6a4-43d3-4057-9a52-617bf5c8c94a.png)

### What did you expect?

The "Spaces with access" section should say "Unknown room" or a room ID or something to indicate that there's a room there, but that the user's client doesn't have enough context to decorate it.

This is what it is supposed to look like:
![image](https://user-images.githubusercontent.com/1190097/130833751-eeaffc60-af73-40e1-aa03-c8043ef003a7.png)

### Operating system

Windows 10

### Application version

Nightly (2021-08-24)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Whoops, i18n issue with missing a `|one` - annoying that `|other` doesn't fill in for that case...
