### ISSUE TITLE
"New in spaces beta" toast+dialog unclear and feels broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18781]
### Steps to reproduce

Unknown.

### What happened?

I refreshed Nightly and got a toast which looks like a changelog:
![image](https://user-images.githubusercontent.com/1190097/130838129-caf61ca5-e97e-484e-81ec-700dc4083431.png)

Upon clicking 'Learn More' I got a dialog which doesn't tell me a whole lot:
![image](https://user-images.githubusercontent.com/1190097/130838199-7be8d35a-52e9-4754-a5b3-80be908e427d.png)

The pink section also has clickable headers but clicking them doesn't do anything. 

### What did you expect?

On the toast, the "Skip" button should probably be "Ignore" or something. "Skip" feels wrong.

On the dialog: it feels like there's supposed to be more information but I'm not sure what. Animated images would be a huge help as right now the dialog feels lacking.

### Operating system

Windows 10

### Application version

Nightly (2021-08-25)

### How did you install the app?

The Internet

### Have you submitted a rageshake?

No

**Comment by niquewoodhouse** [comment]
@turt2live would you mind confirming please if the dialog image had icons or was just the text headers:

![image](https://user-images.githubusercontent.com/1587166/132478089-7b1477f0-d45b-435f-8acd-500c7f9c2654.png)

**Comment by t3chguy** [comment]
Indeed the styling is missing, something has regressed.

**Comment by niquewoodhouse** [comment]
> On the dialog: it feels like there's supposed to be more information but I'm not sure what. Animated images would be a huge help as right now the dialog feels lacking.

In principle just to say I totally agree on animated images, there just wasn't time to do that, and given this will hopefully disappear when Spaces beta ends, doesn't feel like a good use of time but I'd always prefer to do something that animates to explain without the need to read a thing.
