### ISSUE TITLE
Call ends after stop sharing screen

### ISSUE THREAD

**Issue by wizzyxx** [vector-im/element-web#18799]
### Steps to reproduce

1. Started 1:1 audio call
2. both started sharing screen

### What happened?

The person who started sharing screen first if that person stop sharing screen the call ends for that person but the other person stays on call.

### What did you expect?

Call should not end after stop sharing screen.

### Operating system

Windows 10

### Browser information

Chromium: 92.0.4515.159

### URL for webapp

app.element.io

Element version: 1.8.1
Olm version: 3.2.3

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/answers to the given questions/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
