### ISSUE TITLE
Blurhash canvas left in the DOM after image loaded

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18791]
### Steps to reproduce

1. open a room that has an image with a blurhash
2. wait for the image to be loaded
3. inspect the DOM

### What happened?

The blurhash canvas still exists

### What did you expect?

It should be removed from the DOM, otherwise this creates a lot of unnecessery elements

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
I cannot reproduce this, I had two blurhashed images in a room, tested both sending and loading and 0 stale canvases were left around.

The only canvas that is present there for me is the Chat Effects canvas `.mx_RoomView > canvas`
During loading I can certainly see additional canvases flash up but then they get destroyed.

**Comment by gsouquet** [comment]
Me neither, this must have been fixed by another commit?
Thanks for checking this out
