### ISSUE TITLE
Move timestamps into message bubbles

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#18805]
### Your use case

Timestamps should be moved inside message bubbles to be more consistent with the design.
It looks much better especially in DM, showing all timestamps out of bubbles is too distruptive.

Element:
![obrazek](https://user-images.githubusercontent.com/15554561/131080901-1ac67648-cb55-4101-94aa-d736386c57d2.png)

SchildiChat:
![obrazek](https://user-images.githubusercontent.com/15554561/131080948-8c63f02d-7aba-46ed-bd6a-3bb179d9d978.png)

**Comment by ShadowJonathan** [comment]
FWIW Telegram has this as well;

![image](https://user-images.githubusercontent.com/22740616/131263515-1548c6c4-f974-4f20-9308-1b87c32d5bb1.png)

Same with Whatsapp.

**Comment by psrpinto** [comment]
I agree with moving the timestamp to the message bubble, but I think it should be displayed on top of the bubble, e.g. next to the message sender's name. Displaying the timestamp on the bottom of the bubble will result in its position changing according to the bubble's height. I think having the timestamp on a consistent position makes it easier to track. This is also how Slack does it.

<img width="231" alt="Screenshot 2021-08-31 at 12 56 41" src="https://user-images.githubusercontent.com/550401/131498626-557a97d1-d7cd-4553-bb1a-076d9ef03afa.png">

**Comment by ShadowJonathan** [comment]
> I agree with moving the timestamp to the message bubble, but I think it should be displayed on top of the bubble, e.g. next to the message sender's name.

That breaks apart as soon as you want to have a second message underneath, and then there's no timestamp for that message.

Discord solves this by chunking messages in 7-minute intervals, injecting a "header" (even though its from the same user) if it goes beyond that 7-minute chunk.

**Comment by psrpinto** [comment]
I see, good point, I didn't consider that.

> Discord solves this by chunking messages in 7-minute intervals

Slack does a similar thing, I believe, and in addition, shows timestamps of messages on hover:

<img width="190" alt="Screenshot 2021-08-31 at 14 36 50" src="https://user-images.githubusercontent.com/550401/131512392-011f156b-f150-44e2-a80a-ce2a146f00f3.png">

Related: #12536

**Comment by amshakal** [comment]
Here is a mockup of timestamp inside the bubble 

<img width="1440" alt="99" src="https://user-images.githubusercontent.com/85162587/146592520-c93546aa-a466-44da-9485-06401f818ff2.png">

**Comment by ShadowJonathan** [comment]
Looks good, I would recommend adding a little bit more margins around the time stamps, to let them not "sit next" to the text like that.
