### ISSUE TITLE
System Volume / Audio level low until Element is quiet

### ISSUE THREAD

**Issue by michaelgaultjr** [vector-im/element-web#18803]
### Steps to reproduce

1. Enter a voice call, and the volume of all system applications lowers.
2. Exit the call, and the volume stays low.
3. "Quit" Element, and the volume of all system applications return to normal.

### What happened?

When entering a voice call, the volume of all other applications gets lowered, after exiting the call, the volume for the other applications stays low until the Element Desktop app is fully exited.

### What did you expect?

When entering the voice call, the volume of all the other applications gets lowered, after exiting the call, the volume returns to normal.

### Operating system

Windows 10

### Application version

Element version: 1.8.1, Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Have you submitted a rageshake?

No

**Comment by lukasIO** [comment]
FWIW I'm experiencing the same problem (Win10).

**Comment by SimonBrandner** [comment]
@michaelgaultjr, why have you closed the issue? Is it gone?

**Comment by michaelgaultjr** [comment]
> @michaelgaultjr, why have you closed the issue? Is it gone?

I personally haven't noticed it happening recently, and there hasn't really any other information on it so I thought I should close it, I can reopen it if should stay open until officially resolved

**Comment by SimonBrandner** [comment]
> I personally haven't noticed it happening recently, and there hasn't really any other information on it so I thought I should close

Ah, I see, it was just a little confusing to see the issue closed out of nowhere :sweat_smile: Let us know if you ever see it again
