### ISSUE TITLE
Element doesn't show `m.image` events for which a thumbnail could not be generated

### ISSUE THREAD

**Issue by tadzik** [vector-im/element-web#18813]
### Steps to reproduce

1. Send an XCF file as an `m.image`
2. Synapse fails to generate a thumbnail for it
3. The event will not be displayed at all, not even as a fallback

![fail](https://user-images.githubusercontent.com/86378/131132146-7b0ed619-84cb-43a3-bef7-eb9f09492b1e.png)

### What happened?

Element is not ready for a situation when an image exists, but the thumbnail doesn't for any reason

### What did you expect?

A soft-scaled image, or at least an `m.file` equivalent UI element.

### Operating system

Pop OS

### Browser information

Firefox version 90

### URL for webapp

Element 1.8.2-rc.2

### Homeserver

Self hosted one running Synapse ab82fd6ed117d65b330648727dd262b88c94215c, not on the public internet

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Looks very similar to #18819 ?

**Comment by Palid** [comment]
Similar to #18819 (we don't handle errors) and closing in favor of https://github.com/vector-im/element-web/issues/18880
