### ISSUE TITLE
Blurhash never loaded

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18819]
### Steps to reproduce

I opened an E2EE room; it had a blurhash thumbnail of a screenshot; the screenshot never loaded; i sat staring for minutes at a beautifully pulsating blurhash. 

### What happened?

The E2EE thumbnail didn't load

### What did you expect?

The E2EE thumbnail should have loaded rapidly.

### Operating system

macOS

### Application version

nightly

### Have you submitted a rageshake?

Yes

**Comment by Palid** [comment]
@ara4n I couldn't really reproduce it, but it seems that for some reason the image didn't load, and we're not handling it anyhow. We probably need to figure out how to handle it and add some additional logging there.
@janogarcia do we have any image-error designs?

**Comment by novocaine** [comment]
@Palid can you please rename the issue if you intend to pivot it to showing an error message

**Comment by Palid** [comment]
A new one should probably be created instead of this one. Will do.

**Comment by Palid** [comment]
Closing in favor of  #18880
