### ISSUE TITLE
Can't reference images uploaded in encrypted rooms in markdown

### ISSUE THREAD

**Issue by Spunkie** [vector-im/element-web#18817]
### Steps to reproduce

1. Start in an encrypted room and uploaded an image.
2. Grab the uploaded image matrix link, should look like `mxc://matrix.org/iZnsILDtTYjGzywTrOTuTcRv`
3. Reference the image in markdown with the following format `![](mxc://matrix.org/bwCUSPBbtcpwbBhBOJeERzDK)` in a message

### What happened?

1. A blank message with no rendered image

### What did you expect?

1. Anyone with access/decryption keys to the referenced image should still see the images rendered in the markdown, inside or outside of the originally uploaded room.

Possible quality of life improvement: Show everyone else without access a placeholder image that gives some kinda hint about their lack of access.

### Operating system

Manjaro Linux

### Application version

Element Version: 1.7.3.4, olm Version: 3.2.3

### How did you install the app?

pacman, element-desktop, official manjaro repo

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Someone correct me please, but I don't think the matrix image link is enough for the SDK to know whether a user has the decryption key to see that media. 
You need the event ID for that

Tagging @dbkr as he is probably a bit more well versed in that area of the codebase than I am

**Comment by t3chguy** [comment]
Yeah, you need the MXC as well as the keys to decrypt it given it is an MXC pointing at an encrypted blob.

**Comment by dbkr** [comment]
Yeah, in theory the client could look to see if it already has a message that references the mxc url, then use the key / hash from that message to decrypt it but this would be a dice roll on whether the message was recent enough that the client has seen it. I think this is is 'working as expected'. This sounds like something that would need explicit support to work in e2e rooms so best bet might be to open a feature request for what you're actually trying to do.
