### ISSUE TITLE
`CallEventGrouper` should use dispatcher to answer/reject calls

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18825]
Not doing this renders https://github.com/matrix-org/matrix-react-sdk/pull/6691 useless when accepting be clicking on a call tile

**Comment by novocaine** [comment]
Hi @SimonBrandner - can you please fill in more details explaining the user impact of this defect, and how reproduce it? I'm not sure many people are going to grok this other than you ;)
