### ISSUE TITLE
Message bubbles lose rounded corners on message edit

### ISSUE THREAD

**Issue by D-T-666** [vector-im/element-web#18826]
### Steps to reproduce

1. in a regular chat room
2. someone sends a message
3. then they edit their message

### What happened?

the bubble of the last message loses the round corner (bottom left) if it gets edited

### What did you expect?

I'd expect the bubble to have the corner still rounded

### Operating system

Manjaro

### Application version

Element Nightly version: 2021082601 Olm version: 3.2.3

### How did you install the app?

yay -S element-desktop-nightly-bin

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Thank you for your report.

It seems you're not the only one to have come across this bug, as it's been reported previously - see https://github.com/vector-im/element-web/issues/18124. I'm going to close this issue now so we can focus on https://github.com/vector-im/element-web/issues/18124. Please watch, vote or comment on https://github.com/vector-im/element-web/issues/18124 if there is any additional information you can provide.
