### ISSUE TITLE
Use a duplicate template that doesn't require a lot of copy-pasting and searching

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18827]
The current template requires you to find three different pieces of text and replace all of them which can take time and be a bit annoying therefore I would suggest something like:

> Thank you for your report.
>
> It seems you're not the only one to have come across this bug, as it's been reported previously - see #???. I'm going to close this issue now so we can focus on that issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

**Comment by gsouquet** [comment]
Tagging @kittykat as she's owning the new triage process and she will probably be the one that can action this piece of feedback the best

**Comment by kittykat** [comment]
Fixed in https://github.com/vector-im/element-meta/wiki/Comment-templates/_compare/2e0646aaa4d81c7814cd28f9cf633082ad7b1231

**Comment by SimonBrandner** [comment]
> Fixed in [vector-im/element-meta/wiki/Comment-templates/_compare/2e0646aaa4d81c7814cd28f9cf633082ad7b1231](https://github.com/vector-im/element-meta/wiki/Comment-templates/_compare/2e0646aaa4d81c7814cd28f9cf633082ad7b1231)

Thank you! :heart:
