### ISSUE TITLE
Split "Autoplay GIFs and videos" into separate settings

### ISSUE THREAD

**Issue by Spunkie** [vector-im/element-web#18830]
### What would you like to do?

This setting should be split into two separate options.
1. Autoplay videos -- Which defaults to off
2. Autoplay GIFs -- which defaults to on  

### Why would you like to do it?

Every time I write this section out it feels like I'm getting on some kind of soap box. So I'll try and keep it short and simple.

GIFs are not videos and should not be conflated as such. The only reason GIFs are even relevant today is because the internet has traditionally treated them as images, not videos. 

While autoplaying videos outside of streaming/video sites has generally been regarded as a cancer on the internet. Autoplaying GIFs on the other hand has been the norm for many decades.
___
As for the defaults, I've seen more less technically minded friends than I would like to admit that upload or a receive an animated GIF that does not autoplay and they just assume it's bugged/broken and move on.

**Comment by Spunkie** [comment]
Also, I'm specifically mentioning GIFs here but the same "Autoplay GIFs" settings should apply to any other "animated image" formats. Such as an animated webp or apng file. 

Found some relevant open issues digging through the backlog #12967 #5771

**Comment by SimonBrandner** [comment]
https://github.com/vector-im/element-web/issues/5771 seems like a duplicate?

**Comment by Spunkie** [comment]
@SimonBrandner Ya sorry, I didn't see it when I created this issue it was on the last page of open issues. 😅 Still, I think this deserves a fresh look.

**Comment by SimonBrandner** [comment]
> @SimonBrandner Ya sorry, I didn't see #5771 when I created this issue it was on the last page of open issues. sweat_smile Still, I think this deserves a fresh look.

It's not really about giving it a fresh look, it's just that the team has other priorities atm, I am going to close this in favour of https://github.com/vector-im/element-web/issues/5771 and a `Help wanted` label there to indicate that if a member of the community wants to take this up, they can

**Comment by Spunkie** [comment]
I understand, and I'm happy to discuss this suggestion in #5771 going forward. :+1: 
___
> It's not really about giving it a fresh look, it's just that the team has other priorities atm.

I will say though, I find the reasoning given to be disingenuous.

A 3+ year old issue which was outright dismissed with no actual discussion of the proposals merits and is(was) completely out of sync with the modern format and triage tags does not equal a legitimately prioritized/backlogged issue. It's not sitting on some roadmap or bouncing around in the back of a developers brain somewhere. 

It is has been(was) for all intents and purposes unprioritized, dismissed, and forgotten. So, it is 100% about "giving it a fresh look" I believe.
