### ISSUE TITLE
Home does not show existing rooms from spaces

### ISSUE THREAD

**Issue by freaktechnik** [vector-im/element-web#18832]
### Steps to reproduce

1. Reset element web client cache
2. After cache is cleared, select home "space"
3. Join a new room that is in an existing space

### What happened?

Rooms that are in a space that the account had already joined at time of the cache clear and that have no tags are not shown in the home space. Only rooms that are joined afterward show up. Rooms that have a tag (like favorites or low priority) are fine, as are rooms marked as DMs (since they usually have the people tag, presumably).

### What did you expect?

All rooms are shown in the home "space"

### Operating system

elementary OS

### Application version

humanoids beCloud version: 1.8.1 Olm version: 3.2.3 (via Firefox Nightly 93.0a1)

### How did you install the app?

Nextcloud app

### Homeserver

humanoids.be

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
![Screenshot_20210830_082138](https://user-images.githubusercontent.com/25768714/131294378-ef50b4c2-9b40-4090-bcd1-93d7ae56c8c0.png)

You don't seem to have `Show all rooms` enabled... Could you please check with that enabled?

**Comment by freaktechnik** [comment]
A bit weird that rooms that are joined later still show up even with that disabled (which it seems to be by default).

**Comment by SimonBrandner** [comment]
Yeah that is a bug
