### ISSUE TITLE
Connection lost while downloaded file is opened from element

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18835]
### Steps to reproduce

1. download file from element, e.g. a pdf
2. click open in the download complete dialogue
3. pdf viewer opens with the file
4. keep pdf viewer open but switch back to element

### What happened?

element process seems blocked in the background(?) and says connection lost.

connection restores when closing the pdf viewer.

### What did you expect?

element remains usable

### Operating system

arch

### Application version

Element Nightly version: 2021083001 Olm version: 3.2.3

### How did you install the app?

aur/element-desktop-nightly-bin

### Homeserver

private

### Have you submitted a rageshake?

Yes

**Comment by HarHarLinks** [comment]
kinda related #18266

**Comment by HarHarLinks** [comment]
Oh sorry, in fact this is a dupe of #18268

Yes it repros everytime on arch, swaywm, element-desktop-nightly-bin, a pdf file, evince

**Comment by SimonBrandner** [comment]
Ok, let's close this then
