### ISSUE TITLE
Element does not request media permission more than once

### ISSUE THREAD

**Issue by follower** [vector-im/element-web#18831]
### Steps to reproduce

1. Where are you starting? What can you see?

   "Voice & Video" settings tab of "Settings" dialog.

2. What do you click?

   Click "Request media permissions" button.

   Deny access to Camera & Microphone (because there appears no way to give permission for just microphone, not camera) in Firefox popup.

   Get expected "No media permissions"/"You may need to manually permit Element to access your microphone/webcam" dialog from Element.

3. Click the "Site Information" button in the left part of the URL bar.

   Click the "x"/remove icon next to the "Use the microphone" permission.

4. Click "Request media permissions" button again.

### What happened?

The "No media permissions"/"You may need to manually permit Element to access your microphone/webcam" dialog from Element is displayed again without a prompt from the browser about giving permission for just the audio device.

### What did you expect?

Same behaviour as Jitsi Meet, which prompts for mic access again.

(I attempted to locate the applicable area of code in their code base but there's too many layers of abstraction to identify quickly: https://github.com/jitsi/jitsi-meet/search?q=getusermedia :D )

### Possibly related issues

 * https://github.com/vector-im/element-web/issues/5552
 * https://github.com/vector-im/element-web/issues/458

### Possibly related code

 * https://github.com/matrix-org/matrix-react-sdk/pull/3146/files#diff-a8e3039da792c3b4ec5459ad089c2e3420b61e819793294cee181c454fd78fd3R82

 * From a brief look it seems the applicable logic might be here, where it looks like the `refreshMediaDevices()` call is never made if an error exists--which it will when the button is pressed for the second time: https://github.com/matrix-org/matrix-react-sdk/blob/770de8f6b520d250e0ebf8d540ebe6b23ffd3301/src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx#L86-L115

   Perhaps the refresh needs to be called on the subsequent button push before  the call  to `navigator.mediaDevices.getUserMedia()`.

### Operating system

Elementary Linux 5.1

### Browser information

Firefox 84.0.2 (64-bit) for Ubuntu canonical 1.0

### URL for webapp

https://app.element.io/

### Homeserver

private

### Have you submitted a rageshake?

No

**Comment by follower** [comment]
Console shows this error message:

```
Failed to list userMedia devices 
MediaStreamError
​
constraint: ""
​
message: "The request is not allowed by the user agent or the platform in the current context."
​
name: "NotAllowedError"
​
stack: ""

```

**Comment by SimonBrandner** [comment]
I don't think I can repro. Could you please try with a newer version of FF perhaps?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.

**Comment by CRCinAU** [comment]
So, interestingly we see this using the web interface via Chrome on a brand new install of Matrix / Element.

@SimonBrandner Can we do anything to assist with troubleshooting? It seems to work in Firefox, but not Chrome.

Even if I go and manually allow Mic / Camera in Chrome for the site, I still get:
![image](https://user-images.githubusercontent.com/3992884/180137067-8b4f2325-6264-42e8-a553-0e414c67d58a.png)

In Settings, I get:
![image](https://user-images.githubusercontent.com/3992884/180137133-527a91e1-53d7-4113-9690-9b178e3240ba.png)
