### ISSUE TITLE
Created DM doesn't show up under spaces where the target is a member of

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18840]
### Steps to reproduce

1. Have a space with someone else as a member
2. DM that person

### What happened?

the DM doesn't show up under the space. Might be a subset of https://github.com/vector-im/element-web/issues/18837

### What did you expect?

for the DM to show up under the space

### Operating system

Windows 10

### Application version

Nightly (2021-08-30)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Have you submitted a rageshake?

No

**Comment by robintown** [comment]
Likely duplicate of https://github.com/vector-im/element-web/issues/17291

**Comment by SimonBrandner** [comment]
Yeah, I am fairly certain it is that
