### ISSUE TITLE
Missing history after joining a room until I clear the cache

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#18842]
### Steps to reproduce

1. Join a room ([UI kit](https://matrix.to/#/!VUpWDSYFjyziRqOqDU:matrix.org?via=matrix.org&via=envs.net))
2. See no history before join
3. Clear cache
4. View the room
5. See history correctly

### What happened?

The history was missing

### What did you expect?

See the history 

### Operating system

Debian Bookworm

### Application version

Element Nightly version: 2021083001 Olm version: 3.2.3

### How did you install the app?

Debian repo

### Homeserver

envs.net

### Have you submitted a rageshake?

Yes

**Comment by t3chguy** [comment]
Is the room encrypted?

**Comment by SimonBrandner** [comment]
Nope

**Comment by SimonBrandner** [comment]
I don't seem to be able to repro :/

**Comment by SimonBrandner** [comment]
Restarting didn't help here

**Comment by SimonBrandner** [comment]
Given I can't repro, I am going to close this until I have more info
