### ISSUE TITLE
https://chat.mozilla.org/ is using a development build of React

### ISSUE THREAD

**Issue by mstange** [vector-im/element-web#18847]
### Steps to reproduce

1. Install the React devtools extension for your browser.
2. Go to https://chat.mozilla.org/

### What happened?

The React icon lights up in red. The panel says "This page is using a development build of React."

### What did you expect?

The React icon should light up in black/blue and indicate a production build.

This gives better performance.

### Browser information

Firefox Nightly

### URL for webapp

chat.mozilla.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Thank you for the heads up

This issue has already been fixed vector-im/element-web#18651 and released as part of Element 1.8.2 (which has been released today).
I can see that chat.mozilla.org is running 1.8.1

Will close this ticket, but feel free to comment on it and I will re-open if upgrading Element did not fix the issue

**Comment by mstange** [comment]
I can confirm that this is fixed now.
