### ISSUE TITLE
Room upgrade flow during "Space members" doesn't link the new room to the previous parent spaces if you are not an admin of the space

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#18858]
### Steps to reproduce

Room Settings -> Security & Privacy

Set the room access to "Space members" for a room that requires upgrading (will show an Upgrade required).

Don't be an admin of at least one of the parent spaces.

Go through with the upgrade as usual.

### What happened?

The new room is created, but it silently won't be added to an old room's parent space if you're not an admin of it. 

It's also not possible to link the room manually - the previous parent space doesn't show up in search.

<img width="528" alt="Screenshot 2021-09-01 at 09 57 45" src="https://user-images.githubusercontent.com/57377/131654109-b322ab27-0d5c-4663-abdd-7b8c18dc4fb9.png">

### What did you expect?

Either

* To be warned about the behaviour before the operation so I could get someone who is an admin of the space to perform the upgrade instead
* Or less desirably, to be warned during the operation that re-linking had failed

Also interested in whether there's some way to avoid the problem entirely.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Given that users on other servers may have had the room in personal "Just Me" Spaces there really isn't much that can be done here, as no one server or user can update (or even know about) all spaces containing that room. This may require spec changes to work around to make the Hierarchy API resolve tombstones to the latest version of a room or similar.

**Comment by novocaine** [comment]
There might not be a good general solution for the federated case, but at the very least, for the non-federated case, we should be able to do better in terms of detecting the problem and warning the user about it.

**Comment by t3chguy** [comment]
Sure, for the Spaces the user is in we can warn. But even for non-federated case where someone else has that room in a Just Me Space we can't really inform the admin upgrading as that'd be a privacy leak.

**Comment by novocaine** [comment]
From out-of-band discussion:

* Tell the user if we weren't able to successfully link the any of the known parents during the operation (better than silent fail?)
* Warn the user before they start if we weren't able to find any parents with local perms suggesting the re-linking would succeed

**Comment by t3chguy** [comment]
> we could tell the user if we weren't able to successfully link the any of the known parents during the operation (better than silent fail?)
> we could warn them before they start if we weren't able to find any parents with local perms suggesting the re-linking would succeed

^ from @novocaine 

needs some design input on how to present this to the user

**Comment by niquewoodhouse** [comment]
I think I understand the issue.  My preferred flow would be:

- User trieds to upgrade room
- Spinner spins
- _If_ doesn't link new room to previous rooms parent space, you're informed in a dialog which tells you which Spaces, the consequences, and asks if you want to proceed anyway.
- _If_ the above doesn't happen, directed to new room settings (already done)

Dialog:

![image](https://user-images.githubusercontent.com/1587166/132725227-655ab216-242f-4d6f-985c-a0bdfa98953f.png)

I feel like because the upgrade will, in this instance[1], damage the room and the Spaces it's in, and the person upgrading is trying to improve the room, explicitly warning them is best.


[1] If I understand the issue correctly

**Comment by t3chguy** [comment]
> you're informed in a dialog which tells you which Spaces, the consequences, and asks if you want to proceed anyway.

This won't remove the room from those spaces, it'll just not be able to update the link so the older room version will still be linked from those spaces, users joining via that link will join the older version and have a prompt to join the newer version from there.

We also have no way of knowing all spaces which contain this room, only the spaces which you are in (and don't have permission to update the link in)

**Comment by novocaine** [comment]
yeah, we need to just be careful about the copy says, as what we can actually know for certain is very limited: 

* we will know if we weren't able to successfully link *any* of the known parents during the operation (suggesting something wasn't right)
* before they start, we can tell if we weren't able to find any parents that we have admin on

**Comment by niquewoodhouse** [comment]
> we will know if we weren't able to successfully link any of the known parents during the operation (suggesting something wasn't right)
> before they start, we can tell if we weren't able to find any parents that we have admin on

These feel like two different messages.  

1. Suggesting something wasn't right - we couldn't link to _any_ parents

<img width="636" alt="Screenshot 2021-09-14 at 09 56 17" src="https://user-images.githubusercontent.com/1587166/133227680-c1ec3889-daa7-4e3b-bc82-ea59d8792867.png">

2. We couldn't find any parents 'that we have admin on'

![image](https://user-images.githubusercontent.com/1587166/133227958-dd92b4d5-9e70-44cf-b209-da73c5fe6403.png)

**Comment by t3chguy** [comment]
> Suggesting something wasn't right - we couldn't link to any parents

We'd know ahead of time if we 

1) know of any parents containing this room
2) are admin in any of those

but we will never know about all parents and thus also never be admin in all parents.
The Try again CTA on this modal makes no sense as nothing would be any different, you still wouldn't be.

> We couldn't find any parents 'that we have admin on'

This modal seems to do the trick, maybe we could list the spaces for clarity

**Comment by niquewoodhouse** [comment]
> This modal seems to do the trick, maybe we could list the spaces for clarity

Adding a list sounds helpful but we could do it later.

Copy from dialog: 

This room is in some spaces you’re not an admin of.  In those spaces, the old room will still be shown, but people will be prompted to join the new one.
