### ISSUE TITLE
Riot robot did not reverts deps to "develop" after release

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18854]
### Steps to reproduce

1. Pull `develop`
2. Check `package.json`
3. Look for `matrix-react-sdk`, `matrix-js-sdk`, ... 

### What happened?

It's pointing to a specific version

### What did you expect?

It should target the GitHub `develop` branch

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment]
Gah, bitten by our release process again (the merge failed because I `yarn upgrade`d on develop branches which makes the yarn.lock conflict) so it bailed out and I ran one part but not the other part which is somewhere else 🙄
