### ISSUE TITLE
Low-priority section doesn't expand anymore on clicking

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-web#18859]
_Originally posted by @Bubu in https://github.com/vector-im/element-web/issues/17505#issuecomment-910124238_

This seems to have regresses in a worse fashion:
Trying to expand the low-prio section now puts a quarter screen whitespace at the bottom of element-desktop:

![image](https://user-images.githubusercontent.com/105185/131651226-d04100e2-d419-4def-81a0-6dd6500471f3.png)

Element version: 1.7.34
olm version: 3.2.3

**Comment by gsouquet** [comment]
Closing this issue, and reopening #17505
