### ISSUE TITLE
Labs feature_custom_tags: UI broken as of v1.8.2

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#18856]
UI elements to activate custom tags are not accessible (broke in v1.8.2):

![2021-09-01 10_55_43-D-PHYS Element _ notes](https://user-images.githubusercontent.com/6731714/131642992-29f60193-2d47-4de9-924f-2e90f17d0504.png)

It should look like this:

![2021-09-01 10_56_08-D-PHYS Element _ notes](https://user-images.githubusercontent.com/6731714/131643252-b4d0a6f0-161d-4e6f-a0ff-8ccdf1bf6ea2.png)

Workaround: disable room list background image (open console, enter `mxSettingsStore.setValue("RoomList.backgroundImage", null, "account", "DIE");`).

Reset to default value: `mxSettingsStore.setValue("RoomList.backgroundImage", null, "account", null);`

**Comment by turt2live** [comment]
Custom tags are replaced by spaces, and removed formally in https://github.com/matrix-org/matrix-react-sdk/pull/8027
