### ISSUE TITLE
Unify room directory and explore space UIs

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#18851]
#### What would you like to do?

Replace the current room directory UI with a specialized version of the explore space UI.

#### Why would you like to do it?

There is a large overlap in functionality between the room directory and explore space page. Unifying them would bring many benefits, including:

- Simplifying the experience by giving users a single interface to find rooms
- Making it easier to publish rooms to the directory by exposing the same "Add" and "Remove" button seen in spaces
- If desired, increasing the visibility of the room directory for first time users by making it the home page
- Making it simple to show spaces in the room directory, once that becomes a thing

#### How would you like to achieve it?

Something like this:

![Screenshot 2021-08-31 at 18-53-22 Element matrix org](https://user-images.githubusercontent.com/48614497/131585947-a4f85015-08b7-483e-8975-c0b54cc8339b.png)

One functionality that the current room directory UI provides that we'd have to put elsewhere is the ability to join rooms by their alias. I think this would be a great opportunity to put it somewhere less hidden, such as in the room list + button:

![Screenshot 2021-08-31 at 19-03-10 Element Discord bridge](https://user-images.githubusercontent.com/48614497/131586754-4e51db6a-b228-45a0-9005-b8630805db3e.png)

One thing I don't know quite where to place though is the server switcher dropdown. I suppose the homeserver name could serve as the dropdown, though it would be a bit large.

**Comment by gsouquet** [comment]
Removing the `A-Spaces` label as the issue only mentions spaces but is not related to them

**Comment by bkil** [comment]
Somewhat related to #21288 (as in possibly involving a restructuring of the explore rooms UI)

**Comment by robintown** [comment]
https://github.com/vector-im/element-web/issues/22846 seems like an overall saner solution
