### ISSUE TITLE
Auth components use hard-coded dark colour for main text, even for dark & custom dark themes

### ISSUE THREAD

**Issue by AndrewFerr** [vector-im/element-web#18865]
### Steps to reproduce

1. Set the default theme to one that uses dark background colours & light foreground colours.
2. Log in & set up E2EE.
3. Log in from another browser / container, which should prompt to "Verify this login".

### What happened?

The background of the "Verify this login" dialog is dark, and the text for "Verify this login" & buttons are light, but **the text element for the main message of "Verify your identity to access encrypted messages..." is dark**, and thus illegible.

Inspecting that text element shows that its class of `mx_CompleteSecurityBody` has its `color` hard-coded to `#232f32`.

Meanwhile, other elements in the box use a `color` of `var(--timeline-text-color)` or `var(--timeline-background-color)`, which explains why they are legible.

### What did you expect?

The main text in auth dialogs should be set to `var(--timeline-text-color)` (or one of the `authpage-*-color` values mentioned in `res/css/views/auth/_AuthBody.scss`) to inherit its colour from the active theme.

This can be done manually by editing `/bundles/*/theme-*.css` with the desired colour for the `mx_CompleteSecurityBody` class.

### URL for webapp

Self-hosted server with Element v1.8.2

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Looking at the source code it appears that this colours are not hardcoded but using Sass variables

https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/auth/_CompleteSecurityBody.scss#L20-L21

It would appear to me that the colours set in the themes are clashing here. We would welcome a pull request for this change if you're up for trying it out

**Comment by AndrewFerr** [comment]
> It would appear to me that the colours set in the themes are clashing here. We would welcome a pull request for this change if you're up for trying it out

Yes, I'm willing to give this a try--it might be a few days before I can get to it, though.
