### ISSUE TITLE
Changing the Caller Sound

### ISSUE THREAD

**Issue by byZeroOfficial** [vector-im/element-web#18863]
#### What would you like to do?
Change the Call-Sound of everything and specific Rooms

#### Why would you like to do it?
1. Because the Call-Sound is annoying me
2. I don't like it

#### How would you like to achieve it?
Add a way to change it. In Android, you could use the system picker. On Desktop you can use custom files (mp3, wav, flac)

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/5891
