### ISSUE TITLE
User settings inaccessible

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18876]
### Steps to reproduce

1. Press the down arrow next to your username
2. "All settings"

This also happens with "Security & privacy", and from "Notification settings" -> "General"/"Security & privacy"

### What happened?

Drop down menu closes and nothing else

### What did you expect?

Settings overlay

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Regressed by matrix-org/matrix-react-sdk#6619

**Comment by kittykat** [comment]
@gsouquet I still can't access "All settings" from the left menu or "General" from the settings overlay.

I can now access "Security & privacy"

I've reloaded develop.element.io with the latest updates in the last few minutes and cleared the cache.
