### ISSUE TITLE
Emoji suggestions while typing: not working anymore in 1.8.x

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#18879]
Composer settings:
- Automatically replace plain text Emoji: On
- Enable Emoji suggestions while typing: On

In Element (Web/Desktop) v1.7.x, typing a `:` shows emoji suggestions immediately:

![2021-09-03 12_06_02-Window](https://user-images.githubusercontent.com/6731714/131989179-6fbb02dc-9540-46fb-835d-938c157eceb1.png)

Typing `:D`:

![2021-09-03 12_02_29-Window](https://user-images.githubusercontent.com/6731714/131989233-5de76c59-6e34-48c2-a321-385b61f7ac79.png)

Typing `:D` + TAB:

![2021-09-03 12_02_56-Window](https://user-images.githubusercontent.com/6731714/131989307-b2e66758-4202-40bd-a550-264d254f5388.png)

In Element (Web/Desktop) version v1.8.x this does not seem to work anymore>

Typing `:` shows nothing, typing `:` + TAB shows nothing.
Typing `:D` + TAB shows:

![2021-09-03 12_01_54-D-PHYS Element _ Test Lab C-33_a](https://user-images.githubusercontent.com/6731714/131989565-a7535852-2edc-49e3-aab7-d8a5d40bf4b9.png)

**Comment by t3chguy** [comment]
This was an intentional change to only show suggestions when you enter 2 characters after `:`. With the setting you have enabled you can simply do `:D<space>`

**Comment by SimonBrandner** [comment]
Related https://github.com/vector-im/element-web/issues/18833

**Comment by gsouquet** [comment]
Thank you for taking the time to report this

Will close this issue as this was an intentional change.
I would recommend you posting your thoughts in #18833 so that we can reach a consensus and iterate on that feature
