### ISSUE TITLE
editing message to make it empty makes Element unhappy

### ISSUE THREAD

**Issue by jimblandy** [vector-im/element-web#18873]
### Steps to reproduce

Send two messages. Use up-arrow to edit the most recent one, and delete all its text. Hit Save.

### What happened?

The "save" didn't do anything, and now Element says "Can't load this message (m.room.message)"

### What did you expect?

The message to become empty or perhaps deleted entirely

### Operating system

Fedora

### Browser information

Firefox

### URL for webapp

https://chat.mozilla.org/#/room/#naga:matrix.org

### Homeserver

mozilla.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
I partly experience the same thing as you minus the "Can't load this message (m.room.message)"

If I use the up arrow, delete all the text in the input, the save button is not doing anything, it should probably be either disabled, or delete the message.

Could you explain a bit more what is happening after you try to hit "save" and it not working? At what point does the state changes to the "Can't load this message" error?

**Comment by jimblandy** [comment]
Oh, I was worried about the Save button not doing anything, so I hit "reload" on the page.

**Comment by dbkr** [comment]
It looks like we prevent hitting 'save' if the edited message is empty but the editor performs the edit in situations other thna just pressing the save button: eg. I can repro this by switching to a different room after deleting the message content (at which point presumably the editor commits the edit...)

**Comment by dbkr** [comment]
I suspect there may be three bugs here:
 * Editor's prevention mechanism for editing messages to empty misses some cases
 * Element crashes when rendering those messages
 * and should we be submitting an edit when switching rooms if the editor is still open? Feels like cancelling would be a more sensible behaviour?

**Comment by novocaine** [comment]
Maybe splitting hairs, but downgrading to S-Major as I don't *think* you can really be prevented from doing work or lose data over an empty message. Upgrading to O-Intermediate, though.

**Comment by janogarcia** [comment]
This has been discusses internally already. 👍

My two recommended approaches to handle this scenario would be to either disable the _Save_ button if the the message is empty and thus preventing empty messages from ending up in the timeline, or better yet show the deletion confirmation modal and then proceed to deleted the message, which should follow more closely the user's intent and be also more meaningful to others rather than an empty message.
