### ISSUE TITLE
Better error UX for unsent messages

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#18885]
### Your use case

Currently the UX for unsent/undelivered message is slightly lackluster. We could definitely figure something out to improve it, so it's easier to understand for non-power users.

Current UX: 
![129390084-26d699fd-8996-4e90-b206-9d2c7f294021](https://user-images.githubusercontent.com/3636685/131997991-1a874526-05ee-4db1-9d44-2d8905245691.png)

Follow up from: https://github.com/vector-im/element-web/issues/14181

**Comment by novocaine** [comment]
Can someone articulate why it is lacklustre?

**Comment by Palid** [comment]
@novocaine It definitely isn't S-Major, I think I just re-labeled it without thinking much about it. 
We should probably additionally animate it, or make it so it's much more visible than just a red icon in the corner.

**Comment by kittykat** [comment]
There are now 4 red icons so I'm going to close this issue. If you feel that further improvements can be made, please re-open with a list.

![Screenshot from 2021-10-06 09-39-08](https://user-images.githubusercontent.com/51663/136200608-daba4e68-677d-4730-b96d-66a9a6977ca9.png)
