### ISSUE TITLE
Sync stops running when you run out of disk space, silently.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#18895]
### Steps to reproduce

1. Run out of/low on disk space

### What happened?

1. The web environment will close the Indexedb database as normal. `Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`
- The client also stops syncing
- The client does NOT show an error, meaning that you won't know the sync has stopped. The only reason I know is that my logs are full of errors and my other clients continued to work.

Additionally, this sucks:
![image](https://user-images.githubusercontent.com/2072976/132022490-0ef00568-73d7-4289-8216-878c27ac1e9a.png)

### What did you expect?

- An error when the client approaches or hits a disk space limit, at least giving you an action to recover

### Operating system

Ubuntu 20.04

### Application version

Element Nightly version: 1.8.1 Olm version: 3.2.3

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
It appears you're not the only one facing issues when the browsers faces disk pressure, see vector-im/element-web#18258

An attempt at fixing it has been done as part of vector-im/element-web#18875

**Comment by novocaine** [comment]
Related: https://github.com/vector-im/element-web/issues/18423

**Comment by novocaine** [comment]
Closing in favour of tracking these in https://github.com/vector-im/element-web/issues/18423
