### ISSUE TITLE
Failed message notification not visible when viewing another space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#18891]
### Steps to reproduce

1. Send message while the network is dropping out
2. Navigate to a different space
-> Message fails to send
-> User is not notified of failure while under the assumption that it has sent
-> Message is not sent automatically when network becomes available again

### What happened?

The failure notification takes a while to appear, giving the user a sense that the message sent before the network dropped out and the notification is not visible from another space. So if the user navigates away from the space, then they may not find out about the failed message until a long time later.

### What did you expect?

Something like this:
![Screenshot from 2021-09-03 12-07-39](https://user-images.githubusercontent.com/51663/132008296-425cc5d3-25ce-4f78-988d-cd3d53894f44.png)

There is prior art for overlaying notifications on avatars:
![Screenshot from 2021-09-03 14-07-40](https://user-images.githubusercontent.com/51663/132010211-165c19c9-1e11-4033-9e40-e6dfe61c6223.png)

### URL for webapp

develop.element.io

### Development checklist
 - [x] Tagged as T-Defect, and with correct A-*, S-* and O-* labels
 - [x] Can be reproduced from steps (see above)
 - [ ] Developer has acquired all needed info from issue author and issue is not labelled with X-Needs-Info
 - [ ] Design team has signed off on the feature: final design has been approved by the Element design team and attached to this issue: <link to design>
 - [ ] Acceptance criteria (in scope) have been clearly defined:
   - [ ] Failure warning is visible for recent conversations when viewing another space
 - [ ] Out of scope:
   - [ ] …

**Comment by novocaine** [comment]
Note that we do (eventually) show a badge next to the room

<img width="288" alt="Screenshot 2021-09-06 at 12 10 24" src="https://user-images.githubusercontent.com/57377/132208618-80da784d-068a-4a10-93e3-6568ffabf098.png">

But there is no badge on the space showing it has unsent messages

<img width="68" alt="Screenshot 2021-09-06 at 12 11 46" src="https://user-images.githubusercontent.com/57377/132208679-c04bc9c2-9cb5-4c61-89d5-c6624af88bed.png">

**Comment by niquewoodhouse** [comment]
I don't know the sizing of the `!` or the notification dots, so sizing of things should be ignored...but used the same logic as the room error and notification badges in Element:

- Tapping the dot on a Space takes you to the relevant room (as in Spaces panel)
- The `!` is considered more important than the general notification dots (as in room list).


https://user-images.githubusercontent.com/1587166/132670423-9be895d9-172e-4f36-8949-abf56fcd502a.mp4
[Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/Exit-beta-Spaces?node-id=190%3A76612)

**Comment by t3chguy** [comment]
So one minor issue I have with this from a data hierarchy PoV is that it seems weird that we aggregate `!` to a count on the room sublist but then back to a `!` on the space panel - definitely doable just feels strange

![image](https://user-images.githubusercontent.com/2403652/132682047-cea4c892-88c1-4e33-8531-d26b132c8c30.png)
