### ISSUE TITLE
Hyperlinks in preview being cut

### ISSUE THREAD

**Issue by DennisHeine** [vector-im/element-web#18904]
### Steps to reproduce

Send a message to Element that contains a Youtube link with a hyperlink in the description of the video.

### What did you expect?
the link in the preview being either clickable, or completely removed
### What happened?
the hyperlink gets cut. It is in the format http.//www.somecoolhyp... (the rest of the link gets replaced with dots),
thus leading to a 404 page.

### Operating system

Linux

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by aaronraimist** [comment]
I am assuming you are talking about the URL preview that appears directly below the message but there are several other things that could be considered previews (such as the message preview that appears in the room list or desktop notifications) so a screenshot and a YouTube link that reproduces this issue would be helpful.

I cannot reproduce this. I sent a message with a link to https://www.youtube.com/watch?v=TZcF4s-swis and the link to GitHub.com in the URL preview is clickable.

<img width="650" src="https://user-images.githubusercontent.com/5855073/132103368-e6591be3-2f1f-48d7-be31-109dc18513fc.png">

**Comment by DennisHeine** [comment]
![image](https://user-images.githubusercontent.com/18600621/132131721-67ef2608-79f5-4431-9a97-899ae1052063.png)
the link has to exceed the display limit, but still be visible. so that the rest of it gets replaced with three dots.

**Comment by DennisHeine** [comment]
![image](https://user-images.githubusercontent.com/18600621/132131756-ee84d851-2898-4179-8ae0-ac9a5382f2c2.png)
to reproduce, the preview has to be cut at a position  in the link.

http://www.domain.com/page
is cut down to
http://www.domai... 
or something like that

**Comment by aaronraimist** [comment]
This is a Synapse issue then because Synapse does not return the full URL

```
{
  "og:site_name": "YouTube",
  "og:url": "https://www.youtube.com/watch?v=0hzLjBx4E6M",
  "og:title": "Can Linux do this? What every Engineer must know about FOSS Productivity!",
  "og:image": "mxc://raim.ist/2021-09-05_lTKSZPEoIiUBlSLt",
  "og:image:width": 480,
  "og:image:height": 360,
  "og:description": "In this presentation, I will demonstrate a setup I use to be more productive with FOSS.All scripts are available at : https://github.com/magnacore/Productivi...",
  "og:type": "video.other",
  "og:video:url": "https://www.youtube.com/embed/0hzLjBx4E6M",
  "og:video:secure_url": "https://www.youtube.com/embed/0hzLjBx4E6M",
  "og:video:type": "text/html",
  "og:video:width": "1280",
  "og:video:height": "720",
  "og:image:type": "image/jpeg",
  "matrix:image:size": 37151
}
```

**Comment by DennisHeine** [comment]
all right, thank you.
