### ISSUE TITLE
Scrolling impossible when there are unread messages out of screen

### ISSUE THREAD

**Issue by COLAMAroro** [vector-im/element-web#18903]
### Steps to reproduce

When there are more messages new (and unread) messages that the window can show, it become impossible to scroll up.

Closing [the small rewind overlay](https://i.imgur.com/w3B94J4.png) fixes the issue

1. Open two accounts in the same room
2. In one account, send enough (or long enough) messages that the unread messages scroll off the top of the viewport on the other client
3. Switch to other client and try to scroll up

### What did you expect?
The ability to scroll back up to the first unread message

### What happened?
The inability to scroll back up to the first unread message

### Operating system

Windows 10 Pro 21H1 (Build 19043.1165)

### Application version

Element 1.8.3, Olm 3.2.3

### How did you install the app?

Upgraded from "Riot"

### Homeserver

lovelyrad.io

### Have you submitted a rageshake?

Yes

**Comment by dbkr** [comment]
Updated description with actual repro steps.

For me, it depends on scroll velocity - if I scroll very slowly I can see the timeline move up by a tiny amount and then immediately move back down again. If I scroll faster, it scrolls up. Presumably depending on how you scrolling is set up, this may or may not happen.

How frequent this is will depend on how frequent that kind of scrolling setup is - I'm not sure, so have gone with intermediate. Initially went with Minor given there is a workaround, but it could be very non-obvious what the workaround is, and not being able to scroll up is pretty bad.
