### ISSUE TITLE
Non-admin private spaces users can invite others to the space. Only spaces admins should be able to invite.

### ISSUE THREAD

**Issue by dessalines** [vector-im/element-web#18909]
### Steps to reproduce

There should either be a way to restrict the inviting of other people to mods or admins of that private space, or it should be that way by default. Seems odd that random new members to a private space can invite anyone they want, and get access to the entire space.

### What happened?

Only admins should be able to invite others to private spaces.

### Operating system

Arch Linux

### Browser information

FF 91.0.2 (64-bit)

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
As part of fixing https://github.com/vector-im/element-web/issues/18908 we will be exposing the permissions settings for Spaces such that you can configure it as you see fit.
