### ISSUE TITLE
There is no way to unban a user from a private space

### ISSUE THREAD

**Issue by dessalines** [vector-im/element-web#18908]
### Steps to reproduce

1. Create a private space.
2. Invite a user.
3. They join some rooms.
4. Ban them.
5. Try to unban them from the space, and there's nothing in the space settings to do this.

### What did you expect?

A list of banned users in the space settings.

### What happened?

Nothing there.

### Operating system

Arch Linux

### Browser information

FF 91.0.2 (64-bit)

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
@vector-im/design should we just copy the one from Room Settings? Should we also add permissions management?

**Comment by janogarcia** [comment]
I think @niquewoodhouse probably knows this best. 👍

**Comment by niquewoodhouse** [comment]
> @vector-im/design should we just copy the one from Room Settings? Should we also add permissions management?

I think that would be the simplest fix, yes, and I guess it makes sense if Spaces and rooms have the same kind of options here. I do find the layout and ux of that page a bit challenging.

![image](https://user-images.githubusercontent.com/1587166/132729635-3fc61ee1-ba52-41eb-82ee-f5eef7f92fb6.png)

It might be better in the long term for spaces (and maybe rooms too) to seperate out the members issues like Discord, with bans, members and invites seperate (and we'd have roles/permissions as another).

![image](https://user-images.githubusercontent.com/1587166/132727818-2c3c1d03-e3b1-4188-a57f-0189e8e36855.png)
