### ISSUE TITLE
"Joining room ..." when attempting to join #matrix:matrix.org

### ISSUE THREAD

**Issue by HammyHavoc** [vector-im/element-web#18906]
### Steps to reproduce

1. I can either directly attempt to join #matrix:matrix.org via the desktop client, or https://matrix.to/#/#matrix:matrix.org, but the result will be the same

### What did you expect?

To join the room. Works fine via the web interface on app.element.io, but obviously a showstopper with the desktop app.

### What happened?

![image](https://user-images.githubusercontent.com/503951/132103432-390893fe-79da-498e-bb11-ecd2a687656e.png)

![image](https://user-images.githubusercontent.com/503951/132103436-4ba640cb-3ade-41cd-9ceb-3bacbd63270f.png)

After letting it fail and attempt to join again, I get a 'Failed to join room', 'Failed to fetch alias' error when attempting it again.

### Operating system

Windows 10

### Application version

Element version: 1.8.2 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.splitanatom.com

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
@HammyHavoc, could you please send logs, it might lead to more info about this

**Comment by robintown** [comment]
This is more likely an issue with your Synapse being slow and timing out than anything, as HQ is a notoriously difficult room to join. See https://github.com/matrix-org/synapse/issues/4755

**Comment by HammyHavoc** [comment]
I would say so, yes. Is it possible to increase the number of seconds before hitting a timeout?

**Comment by Palid** [comment]
We could probably figure out some better UX for that from the client side though.

**Comment by robintown** [comment]
That would be https://github.com/vector-im/element-web/issues/15627 I think

**Comment by novocaine** [comment]
Closing as this is a HS perf issue; UX suggestions / timeout can be followed up in https://github.com/vector-im/element-web/issues/15627
