### ISSUE TITLE
Access to chats in Historical rooms

### ISSUE THREAD

**Issue by MadHatterInTown** [vector-im/element-web#18913]
### Steps to reproduce

1. Me and my friend left the 1:1 chat room as he was kicked out of element in his browser and he lost his encryption keys and I had to invite him to chat in a new room.
2. I also left the room since I opened a new chat room with him and the original chat moved under historical. 
3. I am currently unable to view the chats in historical as it says no server is found. 
4. Also in my 3 active sessions only one session seems to have this room under historical, while the other 2 does not have this room listed despite me not selecting forget room.

### What happened?

Also as there is no provision to archive the old chats. Is there a way to restore the chats in the historical chat room?

### Operating system

Windows

### Browser information

Google Chrome

### Have you submitted a rageshake?

No

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/12153 https://github.com/vector-im/element-web/issues/16731 https://github.com/vector-im/element-web/issues/7850 https://github.com/vector-im/element-web/issues/14038

**Comment by MadHatterInTown** [comment]
Is there a way to contact the admin of the server to gain access to the historical room. Or at the very least obtain an archived copy of the chat logs.

**Comment by dbkr** [comment]
I think this is the same as https://github.com/vector-im/element-web/issues/12153
