### ISSUE TITLE
Element loses connection to the server when exiting

### ISSUE THREAD

**Issue by laribA** [vector-im/element-web#18917]
### Steps to reproduce

How to reproduce:
1. Install Element/Open Element)
2. Log in 
(I'm using Matrix.org, I'm not sure about other servers)
3. Exit Element somehow
(Everything works fine until this point)
    1. You can do this on desktop by either quitting the app from the system tray or letting the computer go to sleep
    2. You can do this on web by just restarting the browser
4. Re-open Element
5. Issue will occur ("Connectivity to the server has been lost. Sent messages will be stored until your connection has returned.")

How to fix:
1. Sign out and back in
    1. Sign out
    2. Select "I don't want my encrypted messages" (I don't know if this is needed, but this is what I did every time)
    3. Edit homeserver
    4. Select "Other homeserver"
    5. Manually type in "matrix.org"
    6. Sign in
2. Reinstall Element (Desktop only)
   1. I used BCUninstaller every time

### What did you expect?
I would be able to use Element as normal. Connection to the homeserver would not break.

### What happened?
Connection to the homeserver broke, and will not fix on restart.

### Operating system
Windows 10 Build 19043.1165
Microsoft Edge v93.0.961.38 (Official build) (64-bit)

### Application version

Element v1.8.2, Olm v3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Have you submitted a rageshake?

No, I am unable to download logs with /rageshake due to this error: "Failed to send logs: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/user/%40tlariba%3Amatrix.org/account_data/m.cross_signing.master ..."

**Comment by dbkr** [comment]
I'm really not sure what could possibly cause this but the fact that, despite downloading element from the homepage, you have to select 'other homeserver' and type matrix.org to sign back in is very strange - why is this? What was it showing as the default?

**Comment by laribA** [comment]
> I'm really not sure what could possibly cause this but the fact that, despite downloading element from the homepage, you have to select 'other homeserver' and type matrix.org to sign back in is very strange - why is this? What was it showing as the default?

The weird thing is, it was showing "matrix.org"-it just refused to connect until I typed it in manually. I'll upload a video showing what I mean.

**Comment by laribA** [comment]
What the hell? The issue just fixed by itself! Sorry to waste your time, closing the issue.
