### ISSUE TITLE
Spaces' 'Explore rooms' page paginates and searches frustratingly slowly

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-web#18927]
### Steps to reproduce

1. Open a space
2. Click 'Explore rooms'
3. It takes a while to load
4. Scroll down. It takes a while to load even more. This isn't helped by the fact that it seems to be chunked to only a handful of rooms at once (or maybe this is due to the subspaces in the Element space)
5. Type in a search term
6. Wait for a while

This is exacerbated by trying to join multiple rooms as you have to keep returning to the explore rooms page, which then takes another while to load each chunk. Perhaps we could add some caching or make the 'Join' button not dump you in that room immediately?

### What did you expect?

It should feel snappy, or at least should be snappy after a while initially.

### What happened?

It was very slow for every single interaction.

### Operating system

Linux

### Browser information

Firefox 90.0.2

### URL for webapp

https://develop.element.io

### Homeserver

librepush.net

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17550 and https://github.com/vector-im/element-web/issues/17388 as alleviations to the API being slow, for actual performance improvements I suggest opening a Synapse issue

**Comment by reivilibre** [comment]
https://github.com/matrix-org/synapse/issues/10523 related
