### ISSUE TITLE
goto command joins room

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#18925]
### Steps to reproduce

1. Type in composer /goto <address of room you're not already a member of> & press enter

### What did you expect?
Probably to land on a screen giving me the room's name & avatar, or at least a page saying, 'do you want to join this room?'

### What happened?
You're joined to the room straight away. /goto is an alias of join, so it does the same thing, but their names imply different things.

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/10128
