### ISSUE TITLE
Icon to clear room list filter is hidden

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#18922]
![Peek 2021-09-06 10-47](https://user-images.githubusercontent.com/5547783/132197818-f06a2638-8a67-42d6-85b1-eb339a1b571f.gif)

```
Element version: 9b7070b8e6a8-react-e7cfa4816e4d-js-324f9e58ea34
Olm version: 3.2.3
```

This is current develop.element.io as of writing this issue. A refresh of the tab doesn't fix it.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/132202222-4cea6fcc-a65d-4976-bde2-41cd998d8c1a.png)

Looks like the resource maybe failed to load for you

**Comment by babolivier** [comment]
Hmm, looks like it's showing up now. :shrug:
