### ISSUE TITLE
More robust search function

### ISSUE THREAD

**Issue by Latrolage** [vector-im/element-web#18928]
#### What would you like to do?
Add things like searching for messages from a user. Maybe even regular expression or just globing. Showing links to a particular website.

And the ability to combine the above in 1 search.
#### Why would you like to do it?
So that searching messages can be more powerful

### Have you considered any alternatives?

The ability to search messages after searching once. (searching through the searched messages) but that would probably look dumb in the UI

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/element-web/issues/4752
