### ISSUE TITLE
"Use another login" is a misleading string

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#18932]
In the context of verifying a session, a button offers to "Use another login". What is actually meant is being logged in from another device, but the string by itself is ambiguous as it could more easily be interpreted to mean using another account. That leads to bad translations, e.g. for a while French indeed meant "Use another identifier" (Weblate tells it has since been fixed, someone must have been annoyed by the UI which didn’t make any sense).

The current French is "Utiliser une autre session" and I suggest the original string be changed to "Use another session".

**Comment by ShadowJonathan** [comment]
dup of https://github.com/vector-im/element-web/issues/16815

**Comment by afranke** [comment]
They are related but I disagree that this is a duplicate. The other issue expects a redesign, which will probably take time if it happens at all. It does mention the string but it is not the focus and can be overlooked.

This one is a concrete suggestion for a simple fix that could be implemented in a matter of minutes.
