### ISSUE TITLE
active speaker UI is too noisy

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#18935]
it's not useful to tell me when i'm speaking on a 1:1 call. it might vaguely be useful to show the remote speaker flashing, but even that's debatable. the feature is obviously most useful for multiway calls.  even then, the green border should fade in/out or something rather than aggressively flicker on and off as folks speak

**Comment by afranke** [comment]
> it's not useful to tell me when i'm speaking on a 1:1 call

Doesn’t it help with “I’m talking but nothing goes out because I’m muted” situations?

**Comment by SimonBrandner** [comment]
We have removed this now...
