### ISSUE TITLE
Pasting an image from Firefox triggers upload of two pictures

### ISSUE THREAD

**Issue by Wendell250** [vector-im/element-web#18952]
### Steps to reproduce

1. Copy any image from Firefox
2. Paste it (Ctrl+V) into Element Desktop
3. Upload dialogue wants to upload 2 images instead of 1

![png_1](https://user-images.githubusercontent.com/90041836/132595552-425e7eb1-6691-45ae-9112-f11c84affeed.png)
![png_2](https://user-images.githubusercontent.com/90041836/132595557-c2b3c7a7-261e-4c25-b0d9-04bca7d500ab.png)
![jpg_1](https://user-images.githubusercontent.com/90041836/132595612-c85f8c9a-f299-4c8e-95ad-d81be040d425.png)
![jpg_2](https://user-images.githubusercontent.com/90041836/132595615-15448ba4-7930-4f95-95ad-3a17c615088a.png)
![gif_1](https://user-images.githubusercontent.com/90041836/132595849-e0316b2b-6887-4b6b-93a0-ae7669de3d5e.png)
![gif_2](https://user-images.githubusercontent.com/90041836/132595853-e23d1d6a-5356-4da9-a587-2fddde63d99d.png)

### What happened?

I don't remember exact day when this issue crept in, but I'd say it's been a month.

Copying an image from Firefox (RMB -> 'Copy Image') to Element Desktop (Ctrl+V) begins an upload of two images.
They are the same images, except they have different sizes (and extensions).

This happens with all common file types: .png, .jpg, .gif

Examples (seen above, with upload order):

- PNG
1: image.png (835 kb)
2: RiotX-1.png (709 kb)

- JPG
1: image.**png** (8.52 **mb**)
2: 20170216_apollo-11-liftoff.**jpg** (344 **kb**)

- GIF
1: image.**png** (69 **kb**) [static]
2: Rotating_globe.**gif** (13 **mb**) [animated]

Both images upload _successfully_.
Cancelling the first upload will also cancel the second.
Also if I alter contents of the clipboard (Ctrl+C anything) before clicking 'upload' on the second image the upload of said image will fail.

The issue persists in [Troubleshoot mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode).

Chrome does *not* have this issue.
Pasting GIFs turns them into static PNGs though.

**Firefox version: 92.0**

Images from examples:
https://element.io/blog/content/images/2020/07/RiotX-1.png
https://planetary.s3.amazonaws.com/assets/images/spacecraft/2017/20170216_apollo-11-liftoff.jpg
https://upload.wikimedia.org/wikipedia/commons/6/6b/Rotating_globe.gif

### Operating system

Windows 8.1

### Application version

Element version: 1.8.2, Olm version: 3.2.3

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Can you paste into http://madebyevan.com/clipboard-test/ and share the results

> Pasting GIFs turns them into static PNGs though.

This'll be your browsers doing, Element does no conversion here, try pasting the GIF into the above clipboard tester

**Comment by Wendell250** [comment]
Did I have to paste it into the same browser (Firefox) or Chrome?
Because they provide different outputs.
Did both just in case.

So for the main Firefox issue:
* **FF-to-FF (PNG)**
![clipboard_png_ff-to-ff](https://user-images.githubusercontent.com/90041836/132768095-ebff2bcc-ff06-493c-b646-5322cc750405.png)
***
* **FF-to-Chrome (PNG)**
![clipboard_png_ff-to-chrome](https://user-images.githubusercontent.com/90041836/132768170-5dc84fe9-214b-4f2d-b4ce-45bf1b786eac.png)
***
And for the semi-related Chrome issue ("Pasting GIFs turns them into static PNGs though"):
* **Chrome-to-Chrome (GIF)**
![clipboard_gif_chrome-to-chrome](https://user-images.githubusercontent.com/90041836/132768330-eccb0847-865b-4154-84b9-0c2958fefb03.png)

**Comment by Destroyer** [comment]
Assuming this is because Chromium 91.0.4472 being used(at least in Element: 1.9.5, Olm: 3.2.3) which has the same issue

https://user-images.githubusercontent.com/289988/143128082-a64ba6ba-b4fa-444a-bcf7-1c83f43eb3aa.mp4

**Comment by bengaywins** [comment]
It appears this _might_ have been fixed? I can't reproduce anymore.

**Comment by Wendell250** [comment]
Just tested on 1.10.1 (desktop) & FF 97.0, and indeed it appears to be fixed.
Didn't even notice when it happened.

> The paste buffer still shows two, but Element isn't pasting two anymore.

The preview properly shows only one image for all filetypes.

**Comment by Wendell250** [comment]
This was fixed a while ago.
Forgot to close it.
