### ISSUE TITLE
Trigger keyword notification only for exact match

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#18959]
### Steps to reproduce

1. Change your display name to "gg"
2. Join a room, and have someone send a message containing "https://discord.gg"

### What did you expect?

To receive the message and for my notification settings to be respected

### What happened?

Receiving this message triggered a "mention" notification because my display name "gg" has been set as a "keyword".
The domain TLD "gg" triggered a match 

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
This is a spec issue as we are just following the Push Rules spec

> These configure behaviour for (unencrypted) messages that match certain patterns. Content rules take one parameter: pattern, that gives the glob pattern to match against. This is treated in the same way as pattern for event_match.

Globs don't support word boundary placeholders or similar

**Comment by gsouquet** [comment]
Closing as it seems to be working as expected
