### ISSUE TITLE
Kick / Ban from a Space has no Impact on child rooms/spaces 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#18969]
### Your use case

Currently kicking or banning a user from a space / room has no impact on child rooms. Meaning that a user Banned from a space will still be to participate in any space rooms he joined.

#### What would you like to do?

The `moderation` aspect of space as not yet been spec'ed, and is out of scope for the initial release.
Nevertheless, we should at least display a message to a user trying to ban from a space to explain that this functionnality is still beta.

#### Why would you like to do it?

It is probable that a lot of space admin would expect that banning from a space would cascade to child rooms.
But it's a quite complexe problem, as space are so versatile.

#### How would you like to achieve it?

Minimum: Add a 'warning' when you try to ban/kick from space, e.g
> Kick/Ban is still in space is still experimental, you might want to manually ban from the contained rooms if needed.

Better: Add Warning + A dialog where you can cherry pick a list of child room that the user must be banned/kick from (if you have enough power level)

**Comment by niquewoodhouse** [comment]
https://user-images.githubusercontent.com/1587166/133083716-3fba9204-4d57-44cd-bb57-a33939d9adbb.mp4

or if we can only change text

![image](https://user-images.githubusercontent.com/1587166/133084909-159c28ba-c4ad-4012-83ab-700dab3e79c3.png)


I think @daniellekirkwood volunteered to look at the copy

**Comment by t3chguy** [comment]
This approach looks sane, but we are losing some of the current ban functionality

![image](https://user-images.githubusercontent.com/2403652/133285813-0eea8bd9-d40c-461c-8241-61c6a666992f.png)

We also might need to consider the unban edge, given a ban can cascade, an unban might want to as well, there in the list we might only show the rooms they are already banned in (and you have permission to unban them)

**Comment by niquewoodhouse** [comment]
Thanks for the info @t3chguy.  Tried to combine them like so.

**Ban**

<img src="https://user-images.githubusercontent.com/1587166/133643266-02820768-cba5-4bb2-b514-3099004d26b5.png" width="380">

If you’re not an admin of a room or space in Space name, they’ll still be able to access it after you ban them.

**Unban**

<img src="https://user-images.githubusercontent.com/1587166/133643947-13d3bd23-00bb-4461-8032-79e4f92b950b.png" width="380">

If you’re not an admin of a room or space in Space name, they won’t be unbanned from it.
