### ISSUE TITLE
Added a user preference to allow the use of the old method for autocompleting usernames

### ISSUE THREAD

**Issue by gnomelibre** [vector-im/element-web#18963]
### Your use case

For me, the new method for autocompleting user names is catastrophic (much slower and requires the use of different keys). One can even say that it is no longer possible to autocomplete a name, unless you type enough letters to be sure you are autocompleting the right person. Otherwise, it stupidly autocompletes the first name in the list, which will almost never be the right person.

So it would be really nice to have a user preference to choose the old method, where you can simply use the tab key several times to cycle quickly through the list of users until you select the right one. This method was used until this recent change (it's also the one used by IRC clients for several decades).

**Comment by dbkr** [comment]
dup of https://github.com/vector-im/element-web/issues/18973
