### ISSUE TITLE
Cannot cancel message editing easily when viewing list of files

### ISSUE THREAD

**Issue by JohanWinther** [vector-im/element-web#18964]
### Steps to reproduce

1. Open a room that contains: 
   - a message that you have sent
   - at least one sent media file
1. Open the "Room info" sidebar
1. Open "Show files"
1. Open the edit menu on a message you have sent
1. Press cancel

### What did you expect?
That the edit box would disappear.
### What happened?
The edit box disappeared for 0.1 seconds and then opens again.
You can however spam the cancel button and it will eventually cancel.

### Operating system

Ubuntu

### Application version

Element version: 1.8.2 Olm version: 3.2.3

### How did you install the app?

From https://element.io/get-started

### Homeserver

carboncloud.ems.host

### Have you submitted a rageshake?

Yes

**Comment by dbkr** [comment]
What a strange bug. Thanks for the great repro steps - have reproed this on both develop and app.
