### ISSUE TITLE
Room Data/Account Data toggle in editor makes no sense, "send" button should be green

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18967]
![image](https://user-images.githubusercontent.com/22740616/132695417-77ec11f7-64dc-4983-83f7-4adb8ac4c3f1.png)

I find myself instinctively clicking it after being done, because it's a pretty bright button.

Clicking it doesn't even do anything, it just wiggles back and forth.

**Comment by t3chguy** [comment]
Mostly covered by https://github.com/vector-im/element-web/issues/9583

**Comment by ShadowJonathan** [comment]
Yeup, i'll merge this with that
