### ISSUE TITLE
'Scroll to most recent messages' button never goes away (and sending a message scrolls up suddenly)

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-web#18961]
### Steps to reproduce

1. Go to one of most rooms (I thought it was all rooms, but actually one of them I've tried is not affected)
2. Scroll to the bottom
3. The 'Scroll to most recent messages' (downward arrow in a circle, at the bottom-right) never goes away

When I send a message, I also get scrolled up a chunk.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/38398653/132668855-e42c92ff-0c9a-47ec-a6b7-64a8a35d8034.png">

This bug appeared yesterday.

### What did you expect?

The button should disappear when I reach the bottom, so that I can see read receipts without awkwardly having to scroll a small fraction to be able to see them.

### What happened?

The button lingers, and sending or deleting a message suddenly scrolls up.

https://user-images.githubusercontent.com/38398653/132669598-b7ef5e82-6e4f-41e7-953f-047e1901e76a.mp4

### Operating system

Linux Kubuntu 21.04

### Browser information

Firefox 91.0.2

### URL for webapp

https://develop.element.io

### Homeserver

librepush.net

### Have you submitted a rageshake?

Yes

**Comment by dbkr** [comment]
This could be caused by https://github.com/matrix-org/matrix-react-sdk/pull/6751

**Comment by dbkr** [comment]
Going to say this is a release blocker because this probably isn't a regression we want to ship.
