### ISSUE TITLE
Allow viewing space as a chat timeline from devtools

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#18965]
### Your use case

This'd be locked behind a lab toggle and/or only be available through in-app devtools.

### Additional context

Sorta-related to https://github.com/ajbura/cinny/issues/52#issuecomment-915578561, it'd be nice if Element offers some way to view a space room as a normal chatroom, to allow developer debugging.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/5327
