### ISSUE TITLE
Emoji selection/picker should favor emojis which are used more often

### ISSUE THREAD

**Issue by barathrm** [vector-im/element-web#18978]
### Steps to reproduce

In a message input field when I start writing `:sweat`, the first-selected emoji is 😓. Before, it was 😅.

### What did you expect?

When I write `:sweat` I expected Element to present me with a fuzzy-search result over the names and descriptions of the emojis **sorted by most often used**.

### What happened?

The 😓 emoji is always presented first so I can't simply press enter to auto-fill it in.

Me and me and others I know have gotten quite used to using 😅 in chat. However, now the ordering has changed and it's become a hassle to quickly select that emoji. IIRC Even earlier, that emoji was reachable via `:embarrassed` but that stopped working.

I'd suggest ordering emoji by how often they've been used locally.

### Operating system

Debian Stable

### Application version

Element version: 1.8.2 Olm version: 3.2.3

### How did you install the app?

https://packages.riot.im/debian

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by Peque** [comment]
Cross-referencing https://github.com/vector-im/element-web/issues/19044.
