### ISSUE TITLE
Room list is suddenly full of identically-named rooms

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#18970]
### Steps to reproduce

none

### What happened?

![image](https://user-images.githubusercontent.com/1389908/132697467-a2975d30-c5c9-4c64-ab1c-2361056fcf46.png)

I think maybe they are different rooms, but the room list has decided to give them the same title?

### Operating system

Ubuntu

### Application version

2021071401

### How did you install the app?

nightly debian

### Homeserver

sw1v.org

### Have you submitted a rageshake?

No

**Comment by richvdh** [comment]
> Have you submitted a rageshake?

I have now.

**Comment by ShadowJonathan** [comment]
I feel this is the old duplicate room bug creeping back in :thinking:

**Comment by t3chguy** [comment]
2021071401 is old enough to still have this bug.

**Comment by t3chguy** [comment]
Closing as the impacted version is nearly two months old; please update.
