### ISSUE TITLE
Stuck unread notifications in Spaces

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#18975]
### Steps to reproduce

1. Reproduce https://github.com/vector-im/element-web/issues/4947 but on a Space rather than conversational room

### What did you expect?
For me to be able to at least clear the stuck notification, or not receive it in the first place.

### What happened?

![image](https://user-images.githubusercontent.com/1190097/132725780-1847475b-a1fc-47c0-b931-54782d648000.png)

There are no rooms under PS that are unread. It appears as though one of the subspaces or the space itself is "unread" for some reason.

### Operating system

Windows 10

### Application version

Nightly (2021-09-09)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
I may require some debugging from you here, inspecting the notification state, it does not seem to include the sub-spaces.

Inspecting `mxSpaceStore.getNotificationState(SPACE_ROOM_ID).states`

Maybe `Object.values(mxSpaceStore.getNotificationState(SPACE_ROOM_ID).states).filter(s => s.color > 0).map(s => s.room)` to filter to the rooms which have an unread within the space

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/135143594-76897fa3-af91-458e-ba86-eba96cb148fb.png)

Checked the room IDs with `/goto`, landed on the space exploration pages.
