### ISSUE TITLE
Messages "emotes" timestamp hidden

### ISSUE THREAD

**Issue by JordanConnor** [vector-im/element-web#18983]
### Steps to reproduce

/me

### What happened?

Messages "emotes" (where the name is not displayed), have their timestamp hidden behind the avatar, I would expect it to be below or hidden(?)

### Operating system

MacOS

### Application version

Element version: 1.8.2 Olm version: 3.2.3

### How did you install the app?

/get-started

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2284
