### ISSUE TITLE
Github Issue template and rageshake form are at odds

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#18985]
### Steps to reproduce

Attempt to create an issue (https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Defect&template=bug-desktop.yml)

### What happened?

The form says "Have you submitted a rageshake?"

The answer is, "no, of course I haven't, because the `/rageshake` form says, in big bold letters: 

> *Before* submitting logs, you *must* create a GitHub issue to describe your problem.

![image](https://user-images.githubusercontent.com/1389908/132869001-cd6722d9-f6fa-44d9-8173-26ab4e61efea.png)

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
This isn't a developer-experience ticket - this affects real users trying to file bugs

**Comment by kittykat** [comment]
Ideally we want users to
1. Trigger the rageshake as that takes a snapshot of the logs
2. File the issue on GitHub
3. Submit the rageshake

>  Will you submit a rageshake?
    Did you know that you know that you can send a /rageshake command from the web application to submit logs for this issue? Trigger the defect, then type /rageshake into the message entry area followed by a description of the problem and send the command. This will let you submit anonymous logs to the developers.
        - 'Yes'
        - 'No'

We can approach this as a question or an instruction. If a user has to select a response, they are more likely to action it as it's more engaging, but it can also be irritating. I'm not satisfied with the wording above as we want the title to be more proactive

**Comment by uhoreg** [comment]
We should probably avoid using the term "rageshake", or at least explain what it means.  Obviously, we need to refer to the command name as `/rageshake`, but we should use a more meaningful name.  I think that it some places, we call it "debug logs".

**Comment by kittykat** [comment]
@uhoreg the description does explain that it's a way to submit logs. I feel that having a "rageshake" as a title is more engaging and encourages people to read the description
