### ISSUE TITLE
timeline autoscroll is unreliable

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#18984]
### Steps to reproduce

I recently updated to a recent nightly

### What happened?

 Now the timeline sometimes randomly jumps up the screen so I can no longer see the bottom message.

### Operating system

Ubuntu

### Application version

Element Nightly version: 2021090901 Olm version: 3.2.3

### How did you install the app?

nightly debian

### Homeserver

sw1v.org

### Have you submitted a rageshake?

No

**Comment by richvdh** [comment]
This is really, really annoying.

I sent @palid a video demonstrating the issue - not sure if he's had a chance to look at it yet.

The thing that I notice about when it happens is that the `(v)` "scroll to bottom of timeline" button won't go away - either when I click on it, or manually scroll up and down. So presumably the timeline panel doesn't think it is at the bottom of its scroll range, so doesn't need to stick to the bottom when new messages arrive.

**Comment by richvdh** [comment]
The problem seems to come and go arbitrarily. I can't figure out what triggers it for a given room. Once it happens, it seems to persist until more events arrive, at which point it may or may not be possible to clear the `(v)` button.

**Comment by MadLittleMods** [comment]
@richvdh @Palid Can you share the video here? 

Possibly related to https://github.com/vector-im/element-web/issues/18522

**Comment by richvdh** [comment]
the video is of an internal room, so no sorry, I can't share it here.

**Comment by Palid** [comment]
Haven't looked at it yet, been on a sick leave the last week. Will have a look on Monday.

**Comment by richvdh** [comment]
@MadLittleMods the video is attached to the rageshake at https://github.com/matrix-org/element-web-rageshakes/issues/6322

**Comment by richvdh** [comment]
when this happens:

```
sn = this.getScrollNode(); sn.scrollHeight - (sn.scrollTop + sn.clientHeight)
-1.0677490234375
```

Compare: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/ScrollPanel.tsx#L281.

Can we increase the limit on that line? Or remove the `Math.abs` (surely if the value is negative we must be at the bottom)?
