### ISSUE TITLE
Element ignores "features" settings declared in config.json

### ISSUE THREAD

**Issue by asakura42** [vector-im/element-web#18995]
### Steps to reproduce

1. Where are you starting? What can you see?

I edited `config.json` and added these lines:

```json
"showLabsSettings": true,
"features": {
    "feature_spaces": true,
    "feature_new_spinner": true,
    "feature_pinning": true,
    "feature_thread": true
  },
.....
```

Labs showed but no new spinner, pinning or threading appeared.

### What did you expect?

Adding new features fron config.json

### What happened?

No new features, no pinning, no threading

### Operating system

ArchLinux

### Application version

Element version: 1.7.34 olm version: 3.2.3

### How did you install the app?

Repo

### Have you submitted a rageshake?

No

**Comment by aaronraimist** [comment]
If you set showLabsSettings back to false does it go away?

**Comment by asakura42** [comment]
@aaronraimist 
No.

**Comment by aaronraimist** [comment]
Then it sounds like you are probably editing a config.json file that Element isn't looking at either because it is in the wrong location or maybe has the wrong permissions or something.

Make sure you are putting it at this path https://github.com/vector-im/element-desktop#user-specified-configjson

**Comment by asakura42** [comment]
No, @aaronraimist, for example `"settingDefaults": { ... }` works okay. My config locates as described in `$HOME/.config/Element/config.json`. Also it properly reads `"showLabsSettings"` (enables and disables Labs as expected).

Also with `"showLabsSettings": true` and, for example `"feature_pinning": false` button near `Message Pinning` becomes isabled, grey and unclickable.
If `"showLabsSettings": true` and `"feature_pinning": true` then button near `Message Pinning` becomes isabled, grey and unclickable too.

**Comment by asakura42** [comment]
My full config.json is:

```json
{
"showLabsSettings": true,
"features": {
    "feature_spaces": true,
    "feature_new_spinner": true,
    "feature_pinning": true,
    "feature_thread": true
  },
"settingDefaults": {
    "showJoinLeaves": false,
    "hideJoinLeaves": true,
    "showTwelveHourTimestamps": false,
    "showRedactions": false,
    "hideRedactions": true,
    "showAvatarChanges": false,
    "hideAvatarChanges": true,
    "showDisplaynameChanges": false,
    "hideDisplaynameChanges": true,
    "autoplayGifsAndVideos": false,
    "TextualBody.enableBigEmoji": false,
    "TextualBody.disableBigEmoji": true,
    "expandCodeByDefault": true,
    "scrollToBottomOnMessageSent": true,
    "MessageComposerInput.showStickersButton": false,
    "MessageComposerInput.autoReplaceEmoji": false,
    "MessageComposerInput.suggestEmoji": false,
    "MessageComposerInput.dontSuggestEmoji": true,
    "promptBeforeInviteUnknownUsers": true,
    "showChatEffects": false
          }
}

```

I activated spaces from GUI before, maybe it broke smth.

**Comment by Mikaela** [comment]
I don't know if this is related, but my config.json uses `"enable"` where you use `true` e.g.

```json
  "features": {
    "feature_pinning": "enable",
    "feature_custom_tags": "enable",
    "feature_state_counters": "labs",
  },
```

* * * * *

I am curious where do you find the name "feature_spaces" and "feature_thread" as they don't seem to be documented within the labs.md?

**Comment by asakura42** [comment]
@Mikaela 

>feature_spaces
https://github.com/vector-im/element-web/pull/16538

>feature_thread
https://github.com/vector-im/element-web/pull/18872

**Comment by G2G2G2G** [comment]
It does work, certain features do not work like "feature_pinning" for example on windows stable build... (not testing on my linux build since it's dev)

"feature_custom_themes" should work on everything, you can easily verify by enabling it and looking in your appearance and seeing the input box, also it's force checked in the labs menu. "showLabsSettings": true / false also works, but labs tab is always viewable since spaces is always there and always viewable (I assume it should be like that but not sure)

"feature_pinning" doesn't work on stable releases currently (not sure if it should or shouldn't, but it doesn't)

**Comment by t3chguy** [comment]
@asakura42 are you still experiencing this? https://github.com/vector-im/element-web/blob/develop/docs/config.md#labs-flags

We make use of config.json to enable labs by default on develop.element.io quite often 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2403652/170706450-971f10b7-5491-4070-9b15-d00a67e55a87.png">

**Comment by weeman1337** [comment]
I am closing this issue because there has been no response in the last two weeks. If you keep experiencing this defect @asakura42 , please add a comment with @weeman1337 to let me know that it should be reopened.
