### ISSUE TITLE
Managing space users actually manages current room users

### ISSUE THREAD

**Issue by Fidgetcetera** [vector-im/element-web#18994]
### Steps to reproduce

1. In a room inside a space, open the context menu for that space, and click "members"
2. Click on a member of the space who is also inside the room you're looking at.
3. Subtly, this is actually a member page for them relevant to the *current room* being viewed. Kick, ban, mute, etc buttons function in the currently selected room.

### What did you expect?
I expected the spaces member list to lead to the member info page for the space, not the room.
### What happened?
I accidentally kicked a user from a room instead of a space because I thought I was managing their presence in the space.

### Operating system

Xubuntu 21.04

### Application version

Element version: 1.8.2, Olm version: 3.2.3

### How did you install the app?

Deb package from apt source as detailed on https://element.io/get-started 

### Homeserver

nora.codes

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Thank you for taking the time to tell us about your issue.

I am going to close this issue as it has been resolved in a more recent development version of Element and should be available to you soon.
