### ISSUE TITLE
Emojis cut off on top in Brave Browser

### ISSUE THREAD

**Issue by valynor** [vector-im/element-web#19009]
### Steps to reproduce

Many (but not all) of the "big emojis" are missing a few lines at the top in the timeline:

![emoji](https://user-images.githubusercontent.com/23384233/133085649-7f33c5ad-39fd-4f78-aeb2-7a7a4482b2d3.png)

This seems to be a problem with the Brave Browser as it does NOT happen in element-web in Chrome or FireFox on the same system. 

### Operating system

Linux Mint 19.3, element-web 1.8.4

### Browser information

Brave Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Possibly related https://github.com/vector-im/element-web/issues/16588

**Comment by valynor** [comment]
Update: the issue was gone like a week ago (sorry I can't be more precise) but it's now back with Brave Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit) and element-web 1.9.0

**Comment by robintown** [comment]
Brave Browser is not currently one of our [supported environments](https://github.com/vector-im/element-web#supported-environments), so I'm closing this. If you can reproduce in a supported browser, feel free to re-open.
