### ISSUE TITLE
Build desktop error

### ISSUE THREAD

**Issue by SergeyDjam** [vector-im/element-web#19002]
### Steps to reproduce

1. download 1.8.2 sources
2. unpack
3. yarn
yarn run build:native

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### What happened?
neon info generating native/index.node
hak build: keytar
Running yarn with env {
  npm_config_init_license: 'MIT',
  npm_package_devDependencies_chokidar: '^3.5.2',
  LC_ALL: 'C',
  npm_package_dependencies_electron_window_state: '^5.0.3',
  LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:*.sh=01;32:*.csh=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.iso=01;31:*.jpg=01;35:*.jpeg=01;35:*.JPG=01;35:*.JPEG=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.ico=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.divx=01;35:*.xvid=01;35:*.3gp=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.gem=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*.mp2=00;36:*.mod=00;36:*.xm=00;36:*.s3m=00;36:*.it=00;36:*.wma=00;36:*~=47;30:*.bak=47;30:*.swp=47;30:*.bck=47;30:*.bk=47;30:*.old=47;30:*.tmp=47;30:*.save=47;30:*.rpmsave=47;30:*.rpmnew=47;30:',
  npm_package_devDependencies_matrix_web_i18n: 'github:matrix-org/matrix-web-i18n',
  npm_package_build_protocols_0_schemes_0: 'element',
  npm_package_build_linux_maintainer: 'support@element.io',
  npm_package_build_mac_darkModeSupport: 'true',
  npm_package_scripts_lint_js_fix: 'eslint --fix src scripts hak',
  npm_execpath: '/usr/lib/node_modules/npm/node_modules/yarn/bin/yarn.js',
  _: '/tmp/yarn--1631519714102-0.8610427052997534/node',
  LANG: 'C',
  npm_config_bin_links: 'true',
  HISTCONTROL: 'ignoredups',
  LESS: '-R',
  HOSTNAME: 'df02982ed16e',
  OLDPWD: '/home/builder/rpmbuild/BUILD',
  npm_package_scripts_i18n: 'matrix-gen-i18n',
  npm_package_devDependencies__types_counterpart: '^0.18.1',
  npm_package_scripts_diff_i18n: 'cp src/i18n/strings/en_EN.json src/i18n/strings/en_EN_orig.json && matrix-gen-i18n && matrix-compare-i18n-files src/i18n/strings/en_EN_orig.json src/i18n/strings/en_EN.json',
  npm_package_build_linux_category: 'Network;InstantMessaging;Chat',
  npm_package_scripts_docker_build_native: 'scripts/in-docker.sh yarn run hak',
  npm_package_scripts_build_native: 'yarn run hak',
  npm_package_repository_url: 'https://github.com/vector-im/element-desktop',
  npm_package_build_directories_output: 'dist',
  npm_package_scripts_docker_install: 'scripts/in-docker.sh yarn install',
  npm_package_devDependencies_eslint: '7.18.0',
  npm_package_build_appId: 'im.riot.app',
  npm_package_scripts_start: 'yarn run build:ts && yarn run build:res && electron .',
  npm_package_build_afterSign: 'scripts/electron_afterSign',
  npm_config_version_git_message: 'v%s',
  npm_package_devDependencies_eslint_config_google: '^0.14.0',
  RPM_BUILD_DIR: '/home/builder/rpmbuild/BUILD',
  npm_config_user_agent: 'yarn/1.22.5 npm/? node/v14.17.6 linux x64',
  npm_package_devDependencies_tar: '^6.1.2',
  npm_config_init_version: '1.0.0',
  npm_package_scripts_build_ts: 'tsc',
  npm_config_registry: 'https://registry.yarnpkg.com',
  npm_package_devDependencies__types_minimist: '^1.2.1',
  npm_package_main: 'lib/electron-main.js',
  npm_package_productName: 'Element',
  npm_config_strict_ssl: 'true',
  npm_package_devDependencies_electron: '^13.1.9',
  npm_package_license: 'Apache-2.0',
  npm_package_build_win_target_target: 'squirrel',
  npm_lifecycle_event: 'hak',
  YARN_WRAP_OUTPUT: 'false',
  npm_package_build_linux_target: 'deb',
  npm_package_description: 'A feature-rich client for Matrix.org',
  PWD: '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2',
  INPUTRC: '/etc/inputrc',
  npm_package_scripts_build_64: 'yarn run build:ts && yarn run build:res && electron-builder --x64',
  HOME: '/home/builder',
  TMP: '/tmp',
  npm_package_scripts_docker_setup: 'docker build -t element-desktop-dockerbuild dockerbuild',
  npm_package_devDependencies_electron_builder: '22.11.4',
  npm_package_build_linux_desktop_StartupWMClass: 'element',
  npm_package_dependencies_electron_store: '^6.0.1',
  npm_package_build_mac_category: 'public.app-category.social-networking',
  npm_config_argv: '{"remain":[],"cooked":["run","build:native"],"original":["run","build:native"]}',
  RPM_BUILD_ROOT: '/home/builder/rpmbuild/BUILDROOT/element-1.8.2-1-rosa2016.1.x86_64-buildroot',
  npm_package_scripts_build: 'yarn run build:ts && yarn run build:res && electron-builder',
  npm_package_devDependencies_electron_notarize: '^1.0.0',
  npm_package_build_files_1_to: 'node_modules',
  npm_config_version_git_sign: '',
  npm_package_scripts_build_res: 'node scripts/copy-res.js',
  npm_package_scripts_mkdirs: 'mkdirp packages deploys',
  npm_package_scripts_lint_types: 'tsc --noEmit',
  npm_package_devDependencies_fs_extra: '^8.1.0',
  npm_package_devDependencies__typescript_eslint_parser: '^4.17.0',
  npm_package_scripts_hak: 'node scripts/hak/index.js',
  npm_config_version_tag_prefix: 'v',
  npm_package_devDependencies_typescript: '^4.1.3',
  TMPDIR: '/tmp',
  npm_package_dependencies_minimist: '^1.2.3',
  npm_package_devDependencies__typescript_eslint_eslint_plugin: '^4.17.0',
  SYSTEMD_PAGER: '/usr/bin/less -FR',
  npm_package_devDependencies_electron_devtools_installer: '^3.1.1',
  npm_config_wrap_output: '',
  npm_config_ignore_scripts: '',
  npm_package_scripts_build_32: 'yarn run build:ts && yarn run build:res && electron-builder --ia32',
  npm_package_build_extraResources_0_from: 'res/img',
  npm_package_devDependencies_rimraf: '^3.0.2',
  npm_package_devDependencies_needle: '^2.5.0',
  npm_package_devDependencies_node_pre_gyp: '^0.15.0',
  npm_package_devDependencies_pacote: '^11.3.5',
  npm_package_build_extraResources_1: 'webapp.asar',
  npm_lifecycle_script: 'node scripts/hak/index.js',
  MDV_MENU_STYLE: 'mandriva',
  LESSKEY: '/etc/.less',
  npm_package_dependencies_request: '^2.88.2',
  INIT_CWD: '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2',
  TERM: 'xterm',
  npm_package_hakDependencies_keytar: '^5.6.0',
  npm_package_scripts_fetch: 'yarn run mkdirs && node scripts/fetch-package.js',
  npm_package_hakDependencies_matrix_seshat: '^2.3.0',
  npm_package_devDependencies_allchange: '^1.0.0',
  npm_package_scripts_lint_js: 'eslint --max-warnings 0 src scripts hak',
  npm_package_scripts_clean: 'rimraf webapp.asar dist packages deploys lib',
  RPM_PACKAGE_NAME: 'element',
  npm_package_scripts_asar_webapp: 'asar p webapp webapp.asar',
  PYTHONSTARTUP: '/etc/pythonrc.py',
  npm_package_devDependencies_asar: '^2.0.1',
  npm_package_build_afterPack: 'scripts/electron_afterPack',
  PYTHONDONTWRITEBYTECODE: '1',
  SHLVL: '4',
  G_FILENAME_ENCODING: '@locale',
  npm_node_execpath: '/opt/nodejs/14.17.6/bin/node',
  npm_package_build_electronVersion: '13.1.9',
  npm_package_scripts_debrepo: 'scripts/mkrepo.sh',
  npm_package_devDependencies_glob: '^7.1.6',
  npm_package_author_name: 'Element',
  npm_package_repository_type: 'git',
  npm_package_version: '1.8.2',
  npm_package_dependencies_png_to_ico: '^2.1.1',
  LESSCHARSET: 'UTF-8',
  npm_package_scripts_build_universal: 'yarn run build:ts && yarn run build:res && electron-builder --universal',
  npm_package_dependencies_auto_launch: '^5.0.5',
  npm_package_dependencies_counterpart: '^0.18.6',
  npm_package_build_win_sign: 'scripts/electron_winSign',
  npm_config_version_git_tag: 'true',
  npm_package_devDependencies_find_npm_prefix: '^1.0.2',
  npm_package_build_extraResources_0_to: 'img',
  npm_package_devDependencies__types_auto_launch: '^5.0.1',
  npm_package_scripts_prunei18n: 'matrix-prune-i18n',
  PATH: '/tmp/yarn--1631519714102-0.8610427052997534:/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/.bin:/home/builder/.config/yarn/link/node_modules/.bin:/opt/nodejs/14.17.6/libexec/lib/node_modules/npm/bin/node-gyp-bin:/opt/nodejs/14.17.6/lib/node_modules/npm/bin/node-gyp-bin:/opt/nodejs/14.17.6/bin/node_modules/npm/bin/node-gyp-bin:/tmp/yarn--1631519713898-0.02555421891662002:/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/.bin:/home/builder/.config/yarn/link/node_modules/.bin:/home/builder/.yarn/bin:/opt/nodejs/14.17.6/libexec/lib/node_modules/npm/bin/node-gyp-bin:/opt/nodejs/14.17.6/lib/node_modules/npm/bin/node-gyp-bin:/opt/nodejs/14.17.6/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  npm_package_scripts_docker_build: 'scripts/in-docker.sh yarn run build',
  npm_package_devDependencies_electron_builder_squirrel_windows: '22.11.4',
  npm_package_devDependencies_mkdirp: '^1.0.3',
  npm_config_save_prefix: '^',
  META_CLASS: 'desktop',
  npm_config_ignore_optional: '',
  RPM_OPT_FLAGS: '-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC',
  NODE: '/opt/nodejs/14.17.6/bin/node',
  npm_package_build_files_2: 'lib/**',
  npm_package_scripts_lint: 'yarn lint:types && yarn lint:js',
  npm_package_build_files_0: 'package.json',
  npm_package_devDependencies_eslint_plugin_matrix_org: 'github:matrix-org/eslint-plugin-matrix-org#2306b3d4da4eba908b256014b979f1d3d43d2945',
  npm_package_readmeFilename: 'README.md',
  npm_package_scripts_build_native_universal: 'yarn run hak --target x86_64-apple-darwin fetchandbuild && yarn run hak --target aarch64-apple-darwin fetchandbuild && yarn run hak --target x86_64-apple-darwin --target aarch64-apple-darwin copyandlink',
  npm_package_build_protocols_0_name: 'element',
  npm_package_name: 'element-desktop',
  npm_config_version_commit_hooks: 'true',
  LESSOPEN: '|/usr/bin/lesspipe.sh %s',
  npm_package_build_files_1_from: '.hak/hakModules',
  npm_config_arch: 'x64',
  npm_config_target_arch: 'x64',
  npm_config_disturl: 'https://atom.io/download/electron',
  npm_config_runtime: 'electron',
  npm_config_target: '13.1.9',
  npm_config_build_from_source: true,
  npm_config_devdir: '/home/builder/.electron-gyp'
}
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.17.6 | linux | x64
gyp info find Python using Python version 3.5.9 found at "/usr/bin/python3"
gyp http GET https://atom.io/download/electron/v13.1.9/node-v13.1.9-headers.tar.gz
gyp http 200 https://atom.io/download/electron/v13.1.9/node-v13.1.9-headers.tar.gz
gyp http GET https://atom.io/download/electron/v13.1.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v13.1.9/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/builder/.electron-gyp/13.1.9/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/builder/.electron-gyp/13.1.9',
gyp info spawn args   '-Dnode_gyp_dir=/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/builder/.electron-gyp/13.1.9/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/build'
  CXX(target) Release/obj.target/keytar/src/async.o
  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: Leaving directory '/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build/build'
gyp info ok 
hak copy: matrix-seshat
Removing native from /home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/hakModules/matrix-seshat
Copying files from /home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/matrix-seshat/x86_64-unknown-linux-gnu/build to /home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/hakModules/matrix-seshat
        native/index.node
hak copy: keytar
Copying files from /home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/keytar/x86_64-unknown-linux-gnu/build to /home/builder/rpmbuild/BUILD/element-desktop-1.8.2/.hak/hakModules/keytar
        build/Release/keytar.node
hak link: matrix-seshat
success Registered "matrix-seshat".
info You can now run `yarn link "matrix-seshat"` in the projects where you want to use this package and it will be used instead.
success Using linked package for "matrix-seshat".
hak link: keytar
success Registered "keytar".
info You can now run `yarn link "keytar"` in the projects where you want to use this package and it will be used instead.
success Using linked package for "keytar".
Done in 192.84s.
+ node_modules/.bin/electron-builder -l --x64 --dir
  • electron-builder  version=22.11.4 os=5.10.50-generic-1rosa-x86_64
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=13.1.9 appOutDir=dist/linux-unpacked
  ⨯ Application entry file "lib/electron-main.js" in the "/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "lib/electron-main.js" in the "/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:31:11)
    at LinuxPackager.checkFileInPackage (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/platformPackager.ts:489:7)
    at LinuxPackager.sanityCheckPackage (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/platformPackager.ts:537:5)
    at LinuxPackager.doPack (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/platformPackager.ts:298:5)
    at LinuxPackager.pack (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/node_modules/builder-util/src/promise.ts:12:14)
error: Bad exit status from /var/tmp/rpm-tmp.29691 (%build)

>  ⨯ Application entry file "lib/electron-main.js" in the "/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "lib/electron-main.js" in the "/home/builder/rpmbuild/BUILD/element-desktop-1.8.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
  

### Operating system

ROSA Linux Fresh R11.1

### Application version

1.8.2

### How did you install the app?

---

### Homeserver

---

### Have you submitted a rageshake?

No

**Comment by dbkr** [comment]
Looks like you didn't run `yarn run build`?

**Comment by kittykat** [comment]
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please respond to David's question and add a comment with @kittykat to let me know that it’s ready to be reopened.
