### ISSUE TITLE
Can't open emoji picker

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19012]
### Steps to reproduce

Link to recording (too big for github): https://www.dropbox.com/s/dz1bi83xsgf1g0g/CleanShot%202021-09-13%20at%2016.37.41.mp4?dl=0

Couldn't figure out if there are any additional steps required to reproduce it.

### What happened?

Can't open emoji picker on neither element-desktop nightly nor on development environment (develop.element.io works though).

### Operating system

MacOS 11.5.2 (20G95)

### Browser information

Element Desktop Nightly (13.09.2021),  Version 93.0.4577.63 (Official Build) (x86_64)

### Environment

Element Desktop Nightly (13.09.2021)

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
Probably relevant? https://github.com/vector-im/element-web/issues/18997

**Comment by novocaine** [comment]
earlier rageshake looks related

https://github.com/matrix-org/element-web-rageshakes/issues/6272
