### ISSUE TITLE
Performance drops to ~ 5 FPS with the addition of room list background blur

### ISSUE THREAD

**Issue by Midar** [vector-im/element-web#19013]
### Steps to reproduce

Just open Element Web in Firefox 92 on Linux

### What did you expect?
Everything is responsive, like before. Typing is instant, scrolling has 120 FPS.

### What happened?
Everything is slow and laggy, typing takes a long while for letters to appear, scrolling happens with 5 FPS or less.

### Operating system

Fedora 34

### Browser information

Firefox 92

### URL for webapp

localhost

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
I am 92.0 too on Linux (Debian Bookworm) and stuff seems fine here :/ 

CC @Palid

**Comment by Palid** [comment]
@Midar want to help me debug this problem directly? Hit me up at @palid:matrix.org and we'll try to figure out how to reproduce it. Already spent a while with @SimonBrandner trying to figure this out and it may be very setup-specific.

**Comment by Palid** [comment]
Okay, I just verified this in a VM and it seems that for some reason unknown to me so far Fedora's Firefox is generally extremely sluggish and the background drop only adds to the slowness. This was without proper hardware acceleration so far though, so my experience may be different in a while (I'll edit this message).

**Comment by Palid** [comment]
After trying to optimise it for a little bit it seems that whatever we do, unless we render already blurred properly background as the actual background for `.mx_LeftPanel_wrapper`, which isn't that easy as the canvas filters act widely different than css equivalents, the only sane way seems to add some kind of a switch to turn it off. Every single css solution that allows us to use the `blur` filter ends up lagging as heck on Fedora, but working nicely even on Safari.

**Comment by Midar** [comment]
Interesting - my experience with Firefox on Fedora has been in general that it can sometimes feel quite sluggish - I had no idea that this was Fedora related. I wonder if rather than fixing it in Element, it would make more sense to report it on the RH Bugzilla?

**Comment by Midar** [comment]
I searched around a little and found that there were some reports with Firefox on Fedora in general being sluggish. It turns out that setting `gfx.webrender.all` and `gfx.webrender.enabled` to `true` in `about:config` fixes it. So maybe setting those to `false` on other systems helps with reproducing this bug.

**Comment by Palid** [comment]
I tried it on a VM and it didn't really looked like it works, even though I found some blog post saying that webrender.all should be turned on by default.
I don't think that's the proper solution though, as Firefox on Fedora will still have those problems. Maybe it would be actually useful to write the bug you suggested with reproduction steps from here?

**Comment by kittykat** [comment]
Closing in favour of enhancement request #19019
