### ISSUE TITLE
Add flag to disable blurred avatar backdrop in the left panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19019]
#### What would you like to do?
Disable the blurred avatar backdrop

#### Why would you like to do it?
See #19013 - it causes performance issues in Firefox on Fedora

#### How would you like to achieve it?
Add a setting

**Comment by t3chguy** [comment]
We never had such a flag so it isn't a regression

**Comment by SimonBrandner** [comment]
> We never had such a flag so it isn't a regression, it causes contrast issues so is an a11y issue though

If we were to actually do this, we might as well allow setting a custom image

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14665
