### ISSUE TITLE
Disabling auto update in Windows Desktop 

### ISSUE THREAD

**Issue by phmassa** [vector-im/element-web#19027]
### Your use case

On Windows, with option --no-update , it seem doesn't work

can you add an option Pref/General : disable auto-update ?

**Comment by t3chguy** [comment]
You can disable auto-updater via config.json, or you must pass `--no-update` to the right executable, inside the versioned folder in AppData.

**Comment by phmassa** [comment]
how on config.json ?

**Comment by t3chguy** [comment]
`"update_base_url": null` in config.json

**Comment by kittykat** [comment]
Closing as this is already doable.

@phmassa if you need further help with this, please ask in [the Element Web/Desktop](https://matrix.to/#/#element-web:matrix.org) channel.
