### ISSUE TITLE
Joining a room in a space still shows up in home even though show all rooms is disabled

### ISSUE THREAD

**Issue by freaktechnik** [vector-im/element-web#19025]
### Steps to reproduce

1. Make sure "Show all rooms" is disabled for home
2. Find a room you're not in in a space
3. Join said room
4. Go back to home

### What did you expect?

The newly joined room should not show up in home, since it's in a space.

### What happened?

The newly joined room shows up in home. Turning "show all rooms" on and off again makes it disappear.

### Operating system

elementary OS

### Browser information

Firefox Nightly 94.0a1

### URL for webapp

humanoids beCloud version: 1.8.4 Olm version: 3.2.3

### Homeserver

im.humanoids.be

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Two things are going wrong here, it is being added to the home space wrongly but also it should auto-switch you to the relevant space.

**Comment by freaktechnik** [comment]
I was already in the relevant space - joined via the space room list, so I might be missing a step there if we're going very detailed.

**Comment by t3chguy** [comment]
Fair enough, the auto-switch if you joined a room via a link/pill/join command didn't work anyway and is closely related to the expected experience so bundled it into the same fix
