### ISSUE TITLE
"Give feedback" link for spaces in "Explore rooms" doesn't work

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19029]
### Steps to reproduce

1. Go to "Explore rooms"
2. See this top-right: 
![Screenshot from 2021-09-14 11-51-27](https://user-images.githubusercontent.com/51663/133244943-76552e17-f3b0-4b5f-9671-36a0de7f10e0.png)

3. Try clicking "Give feedback"

### What did you expect?
Something to happen

### What happened?
Nothing

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18524
