### ISSUE TITLE
Room title is wrong in Explore rooms view for new space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19023]
### Steps to reproduce

1. Press the + icon in the left spaces panel
2. Select ""Private"" option from the dialog
5. Create space
6. "Me and my teammates"
7. [not sure if relevant] Invited one user by email and one by username
10. "Continue"
11. Create the space without adding a third room

### What did you expect?
The Explore rooms view has "Empty room" as the room name.

### What happened?
![Screenshot from 2021-09-14 10-38-12](https://user-images.githubusercontent.com/51663/133234626-9f048a48-14ab-4705-8a95-d537c92b7ea3.png)

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
I tried reproducing this and instead got

![image](https://user-images.githubusercontent.com/2403652/133252499-71fde8a8-631a-40a9-9a48-d7cbbd74601c.png)

we might need to add an artificial delay somewhere

**Comment by t3chguy** [comment]
looks like any permutation of empty/correct is possible :(

![image](https://user-images.githubusercontent.com/2403652/133266619-4dc2f9a4-0858-431b-b406-7907170af195.png)
