### ISSUE TITLE
Styled Dropdown component can't be collapsed by its chevron

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19030]
### Steps to reproduce

1. Right click on a space in the left panel -> "Add space"
2. Open permission drop down

### What did you expect?
Be able to click on the downward facing caret (▼) to close the drop down

### What happened?
Nothing

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
This is not specific to spaces, applies to all usages of that Dropdown component, e.g Country and Language dropdowns
