### ISSUE TITLE
VoiceRecording.ts uses noiseSuppression preventing TypeScript upgrade

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19048]
src/audio/VoiceRecording.ts uses noiseSuppression attribute which was removed (https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029).

Review whether to stop using this or add it to our types.

**Comment by t3chguy** [comment]
4.5 brought it back https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1143
