### ISSUE TITLE
Usage of window.MSStream preventing typescript upgrade

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19046]
We use window.MSStream in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/toasts/MobileGuideToast.ts#L33 which has been removed by typescript: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029

There's no documentation of why we use this, so we need to either find something else if this isn't appropriate any more, or add it to our types.

**Comment by UwUnyaa** [comment]
It could be possible to use an interface that extends window and defines the type of this value to keep the check in place if necessary.

I don't think that's the case though, as IE isn't in the supported list, and neither is Windows Phone.

**Comment by t3chguy** [comment]
I added this to the Window interface as part of the upgrade. https://github.com/matrix-org/matrix-react-sdk/blob/7033f8696ae2a82a1fe23eefff6e3bf33ecc4e95/src/@types/global.d.ts#L71

> I don't think that's the case though, as IE isn't in the supported list, and neither is Windows Phone.

Yes, but this is used in the MobileGuideToast & permalink handling for mobile_guide - so has to work on more browsers.
