### ISSUE TITLE
When private messaging (PMing) the text started moving all over the place

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [vector-im/element-web#19045]
### Steps to reproduce

1. I was typing text and pressing enter to send the text in a one-on-one conversation with someone.

### What happened?

1. I was PMing with someone for about 30-45 minutes 
2. I heard the ding, but then there was no message
3. I asked him if he just sent me a message & after I clicked enter, his message showed up.
4. Then after that, every time I typed, one sentence I had already written kept attaching itself to my last PM.
5. Even at one point it showed up as a stand alone PM & of course I never typed it.
6. I have screenshots, but I prefer not to show them here in public as it was a private conversation.
7. I sent him the SS & he didn't see that, so it's only seen on my end I guess.
8. And the reason I couldn't see his message before was b/c it must have been above that message that keeps doing its own thing.

### Operating system

Win 7

### Application version

I just updated & there is no about area in help.

### How did you install the app?

I really don't remember, it was over a year ago. I assume from your site.

### Homeserver

I think it's matrix.org. I still don't understand all of that

### Have you submitted a rageshake?

No

**Comment by Palid** [comment]
@ILoveSkilledCoders The next time it appears please get a video of how it behaves (you can censor all the things we don't need) and add a `/rageshake`. It'll really help us!
To me it seems that maybe you had a patchy internet and/or tried to send a message while the matrix server was restarting, but for some reason the client didn't catch that. I'm guessing here though, as I don't have enough data.

**Comment by turt2live** [comment]
Closing due to lack of information. If you're still seeing this, please open a new issue with the requested information.
