### ISSUE TITLE
publish container image on registry without draconian rate limits

### ISSUE THREAD

**Issue by ibotty** [vector-im/element-web#19041]
#### What would you like to do?

I would like to run the element-web container image.  Unfortunately it is not possible because the docker registry rate limits my IP.

#### How would you like to achieve it?

I'd like to get the image from another registry.  The github-registry is fine as is quay.io.  Both have a fair-use policy.

**Comment by gsouquet** [comment]
I would probably suggest to raise this in a Matrix room, like https://matrix.to/#/#element-web:matrix.org

You can alternatively find the instructions on how to run Element with Docker in the README, https://github.com/vector-im/element-web#running-from-docker

Will close this, as this is probably not the right forum to discuss this

**Comment by ibotty** [comment]
Sorry, I don't see why that's the wrong forum.  It's not a support request.  It's about publishing the container image that is part of that repo.  Maybe you misunderstood what I was trying to say.  I know how to run Element with docker.  I want to do so without running into rate limits from dockerhub.

**Comment by gsouquet** [comment]
At this stage I do not think that Element is considering to publish the docker image in other docker container registry.

I might be worth you reach out to DockerHub to understand why such restrictive rate limits are in place for you as I do not believe other users are experiencing this

**Comment by ibotty** [comment]
I run into it regularly.  I think you might misunderstand the docker rate limits.  We are not singled out.  All IPs get the same rate limits.  When operating a cluster behind a NAT all cluster pulls count against the rate limit, so one runs into it easily.  We are not alone in that regard.  Please reconsider.
