### ISSUE TITLE
Slack bridge to a channel in someone else's workspace

### ISSUE THREAD

**Issue by hughallied** [vector-im/element-web#19054]
### Steps to reproduce

1. Where are you starting? What can you see? - A partner organisation wishes to collaborate with us and has created a shared (open) slack channel, inviting the relevant people from our team into it.  I invited the Element Bridge app in.  I know the bridge functionality is working because it is already operational to other shared slack channels, both channels owned by our slack workspace, and channels owned by others' slack workspaces.
2. What do you click? I go to the Home space, then click on the explore rooms compass icon.   I then search for the bridged room (both full name and fragments of the title).  The room does not appear.

#### What did you expect?

I expected to be able to see the slack channel as a bridged room in the list of available rooms to join, as has happened when bridging to other slack channels.

#### What happened?

I couldn't find the room.

### Operating system

Windows 10 Home, 21H1

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

From the Element site

### Homeserver

allied-partners.element.io

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Thank you for raising that issue. It does appear to be related to the Slack bridge rather than with Element itself.
May I direct you to https://github.com/matrix-org/matrix-appservice-slack/issues ?

I'll be closing this issue here, and the bridge team should be able to come back to you regarding that
