### ISSUE TITLE
Unpin & upgrade typescript & react

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19053]
https://github.com/matrix-org/matrix-react-sdk/pull/6813 pins typescript / react packages. This is a reminder for us to un-pin them & upgrade them once we fix these bugs so we can:

https://github.com/vector-im/element-web/issues/19046
https://github.com/vector-im/element-web/issues/19047
https://github.com/vector-im/element-web/issues/19048
https://github.com/vector-im/element-web/issues/19049
https://github.com/vector-im/element-web/issues/19051

**Comment by dbkr** [comment]
Also need to remove the entry in `resolutions` for `@types/react` added in https://github.com/matrix-org/matrix-react-sdk/pull/6814

**Comment by dbkr** [comment]
Likewise pinning in element-web: https://github.com/vector-im/element-web/pull/19056

**Comment by t3chguy** [comment]
The great unpinning already happened
