### ISSUE TITLE
"Help space members find private rooms" dialog makes no sense

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19067]
### Steps to reproduce

1. Got a toast today about helping members find rooms in spaces, possibly while testing spaces.
2. 
![Screenshot from 2021-09-16 08-02-26](https://user-images.githubusercontent.com/51663/133571397-55a72f5d-64e4-404d-8c4a-795c602345f3.png)

### What happened?

The dialog doesn't actually get to the point of what it wants me to do in the settings. I can help with wording if someone can explain the intent to me.

S-Major because I don't actually know what it wants me to do; O-Occasional is questionable, I'm not sure what triggers the dialog, but I'm guessing any space admin may be affected by this.

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
This is as designed so will need more design input.

**Comment by niquewoodhouse** [comment]
> I'm not sure what triggers the dialog, but I'm guessing any space admin may be affected by this.

It was a toast like this:

![image](https://user-images.githubusercontent.com/1587166/135251749-f304d0a7-aece-403c-80e2-93dc0d0aabf9.png)

I'm guessing this is no longer here, as the beta referred to in the toast has now concluded, so therefore the dialog no longer appears/can be triggered to appear?

**Comment by t3chguy** [comment]
@niquewoodhouse nope, it appears to have slipped in with that exact copy into the launch

**Comment by niquewoodhouse** [comment]
Ok, I'm not sure if we need to make an effort to promote this feature anymore, as we're now out of beta and the benefits of this feature will already exist for all spaces started from now.
