### ISSUE TITLE
Generated translations don't work with strings like "Collapse quote | ⇧+click"

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19068]
It seems that the `yarn i18n` script in `matrix-react-sdk` is stripping the part of `Collapse quote | ⇧+click` after `Collapse quote`, which leaves it as `Collapse quote ` in the end. We should probably handle this in the generator script properly, or add a new, better way to handle showing hotkey hints. 
Related https://github.com/matrix-org/matrix-react-sdk/pull/6701

**Comment by gsouquet** [comment]
This looks like it has been fixed. `Collapse quotes │ ⇧+click` is a string that exists in all the i18n files
