### ISSUE TITLE
Joining Subspace shows UI about rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19064]
### Steps to reproduce

1. Go to Explore rooms in a space with a subspace
2. Click the "Join" button

### What did you expect?
Next dialog/page showing "Joining space"

### What happened?
Goes to an intermediate page with "Joining room"/spinner and then to the "Explore rooms" page for the subspace

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/17388 would likely supercede this but making a fix to pass the fact it is a space and thus change the copy to `Joining space ...`
