### ISSUE TITLE
Automatically replace plain text emoji duplicates last character

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#19073]
### Steps to reproduce

1. Enable "Automatically replace plain text Emoji"
2. Click into the composter
3. Type `:-D<space>`

### What did you expect?

I expected my composer to be `😀<space>`

### What happened?

My composer is `😀D<space>`

### Operating system

macOS

### Application version

Element Nightly version: 2021091601 Olm version: 3.2.3

### How did you install the app?

I don't remember

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by clokep** [comment]
This *might* be a regression from matrix-react-sdk#6784 as that shows typing `:D` replacing properly (which I've confirmed *does* work), it's just when you add a nose (`:-D`) that things break.

**Comment by clokep** [comment]
Thanks for the quick fix! 🎉

**Comment by SimonBrandner** [comment]
> Thanks for the quick fix! tada

No problem!
