### ISSUE TITLE
Square artifacts on notification badges etc

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19072]
### Steps to reproduce

I have evidence of this happening in the room list, but I believe it has happened in other areas, perhaps the seen-by marker or similar. Only happens sometimes and for unknown reason.

### What happened?
![image](https://user-images.githubusercontent.com/2803622/133649842-491ffa04-46fc-4236-8a35-34a3760bc6bd.png)

### Operating system

Windows, Arch Linux

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

element.io

### Have you submitted a rageshake?

No

**Comment by HarHarLinks** [comment]
Also happening when typing a reply on stable, Windows 10. Artifacts updated and moved with every character typed.

**Comment by turt2live** [comment]
This appears to be a system issue (driver, graphics card dying, etc) and not something we'll be able to fix. If you're still seeing this, and can link it back to Element specifically, please open a new issue with fresh information.
