### ISSUE TITLE
Change matrix-web-i18n's gen-i18n script to instead be a babel plugin, so it runs automatically 

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19076]
Currently you have to manually run `yarn i18n` from the `matrix-react-sdk` repository to properly update translations. We should change the `node_modules/matrix-web-i18n/scripts/gen-i18n.js` to be a proper babel plugin instead, so that we don't really need to manually run it and it'll run while transpiling the codebase on dev step anyways.

**Comment by t3chguy** [comment]
This won't really work, as Weblate isn't smart enough to run a script to generate the base translations file (English)
