### ISSUE TITLE
Backspace can't erase Name "bubble" after completion on firefox 78

### ISSUE THREAD

**Issue by airblag** [vector-im/element-web#19077]
Since a few updates (at least 1.8.2), when using Element-web in Firefox ESR, once a name is changed into the reference "bubble", you cannot delete it with backspace.

In chromium (and in the desktop client), it works as expected.

# How to reproduce

- run element-web in firefox (tested with 78 from debian).
- In a room type the begining of a participant name and Tab to complete the name.
- try to erase it with from the composer with backspace. It doesn't get erased

# Workaround

- User has to select the "bubble" with Shift + <- + <- to be able to erase it from the composer.

**Comment by SimonBrandner** [comment]
@airblag, could you please test out the live preview on https://github.com/matrix-org/matrix-react-sdk/pull/6832?

**Comment by ilmari** [comment]
> could you please test out the live preview on [matrix-org/matrix-react-sdk#6832](https://github.com/matrix-org/matrix-react-sdk/pull/6832)?

@SimonBrandner I can confirm that deleting a mention pill works fine there with Firefox 78 ESR, both with backspace and delete, while it does not work on {app,staging}.element.io.

**Comment by SimonBrandner** [comment]
@ilmari, we had to revert the fix since it broke a bunch of other things...

**Comment by robintown** [comment]
Firefox ESR has moved on from 78 to 91, which doesn't have this issue
