### ISSUE TITLE
Submitting feedback on Spaces is not working

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-web#19078]
### Steps to reproduce

1. Go to the management space for a space
2. Click the top right "give feedback" button

or:

1. Click the button to create a new space
2. At the bottom of the create-space modal, click "give feedback"

then:

3. Nothing appear to happen, but the following is posted in the console, but nothing else appear to happen
![Screen Shot 2021-09-17 at 10 39 01 AM](https://user-images.githubusercontent.com/19155609/133761887-a0933c4c-1675-42d5-8258-6c8f53980201.png)

### What did you expect?

Spaces feedback modal

### What happened?

Nothing

### Operating system

Arch Linux

### Browser information

Firefox 92.0 (64-bit) and Chromium 93.0.4577.63

### URL for webapp

app.element.io

### Homeserver

Reproducible using multiple homeservers

### Have you submitted a rageshake?

Yes

**Comment by t3chguy** [comment]
Already fixed on develop.

**Comment by lassepe** [comment]
Still broken for spaces that are migrated communities though.
