### ISSUE TITLE
"Mark as read" not working in CoAP mode

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#19088]
### Steps to reproduce

Click the big X button.

### What happened?

Message not marked as read, whereas it should have been.

### Operating system

Ubuntu 21.04, but irrelevant for reproducing this bug

### Application version

1.8.5

### How did you install the app?

Ubuntu APT repository

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by turt2live** [comment]
This is a feature.

**Comment by erkinalp** [comment]
Why is that?
