### ISSUE TITLE
Ctrl+Backspace is broken

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#19089]
### Steps to reproduce

1. Type a word in the composer
2. Try to delete it with Ctrl+Backspace

### What happened?

Only a single character was deleted

### What did you expect?

The entire word should be deleted

Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6832

### Operating system

NixOS unstable

### Browser information

Firefox 92.0

### URL for webapp

develop.element.io

### Homeserver

townsendandsmith.ml

### Have you submitted a rageshake?

No

**Comment by HarHarLinks** [comment]
Same for Ctrl+Del which from looking at the PR code doesn't seem fixed. @SimonBrandner?

Element Nightly version: 2021092001
Olm version: 3.2.3

**Comment by SimonBrandner** [comment]
> Same for Ctrl+Del which from looking at the PR code doesn't seem fixed. @SimonBrandner?

No, the PR should fix that
