### ISSUE TITLE
If you join a room and then join a space that contains a room you have already joined, it will disappear from your home 'space'.

### ISSUE THREAD

**Issue by zarp-dev** [vector-im/element-web#19087]
### Steps to reproduce

To reproduce this, you will need two Element Web sessions.
1. Using first session, join any room. You will see this room in your Home 'space'.
2. Using second session, create a space. Add the room you joined in the first session to the space.
3. Using first session, join the space that you created in second session. The room you joined in step 1 will disappear from your Home 'space'.

### What did you expect?
I wanted the room that I entered before entering the space to remain in my Home 'space'.
### What happened?
It disappeared from my Home 'space'.

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
This is the expected behaviour

**Comment by zarp-dev** [comment]
Related #17347

**Comment by HarHarLinks** [comment]
> This is the expected behaviour

... depending on this spaces-setting
![image](https://user-images.githubusercontent.com/2803622/133987030-85775b87-abe4-4544-b5ac-3faf97030b03.png)

**Comment by zarp-dev** [comment]
This is very strange behavior. Let's imagine I have a lot of spaces, I don't want to see rooms from these spaces in my Home tab. Let's imagine that I entered the Element Web / Desktop room, I want it to be in my Home tab. Then I join a space that contains this room. The room disappears from my Home tab, I want it to stay there. I think the solution should be to add the "Pin to Home" option for rooms and spaces. If a user tries to join a space that has a room or a space that the user is already in, issue a warning: 
"_Example space contains the room (s) (or space (s)) you are already in. If you join to the Example space, the room (s) (or space (s)) will disappear from your Home tab. Do you want to pin the  room (s) (or space (s)) to the Home tab?_ "
Below should list the rooms or spaces that will disappear as a result of the user joining the Example space, there should be a checkbox next to each room or space. At the very bottom there should be buttons "Cancel" and "Pin".
"Pin to Home" option will also be useful if a user wants to add any room from the space he has already joined to the Home tab.

**Comment by SimonBrandner** [comment]
> "Pin to Home" option for rooms and spaces

You can add the room to your favourites and it will appear in your home

**Comment by zarp-dev** [comment]
What if I don't want to add the room to my favourites. I just want it to be in the Home tab.

**Comment by daniellekirkwood** [comment]
As this is currently working as designed, I'm going to go ahead and mark this issue as an Enhancement. 

Thanks for your feedback, we'll look into "Pin" and other solutions for this!

**Comment by kittykat** [comment]
This sounds like a perfect use case for a private space: you want to be able to pick and chose which rooms appear in your "home" space.

With the latest IA changes, you can hide the automatically populated spaces that you don't want to see:
![Screenshot from 2021-12-17 11-53-09](https://user-images.githubusercontent.com/51663/146541109-f116a291-cb66-4f83-82bf-b38d0d7a3594.png)

And can create your own private space where you can have only the rooms that you want. @zarp-dev does this satisfy what you would like to do?

**Comment by kittykat** [comment]
I'm going to close this issue for now as there is a solution which may be able to satisfy the criteria. Please comment with @kittykat and further details if you feel that there are more improvements to be made so that I can reopen the issue for you.
