### ISSUE TITLE
Incorrect reports of "Some of your messages have not been sent"

### ISSUE THREAD

**Issue by bjherbison** [vector-im/element-web#19099]
This morning I have a report of "Some of your messages have not been sent" which wasn't displayed yesterday evening. The message at the bottom of my scroll is identical to a message I sent yesterday afternoon that was obviously sent as someone responded to the message.

https://chat.mozilla.org/#/room/#general:mozilla.org
https://matrix.to/#/!gTeEstkMlPUdxvIdCE:mozilla.org/$3VhWHAtCNFBfUJDe4QWnfT4EgeUDS8gS7Ii8oo9xCJA?via=mozilla.org&via=matrix.org&via=privacytools.io

**Comment by gsouquet** [comment]
Thank you for your report. We need some more information from you before our developers can look at it. 
Could you please share a rageshake and give a little more information regarding your setup?

**Comment by bjherbison** [comment]
The setup is a Ubuntu laptop using Firefox no XFCE. I saw the message on two different laptops using different versions of Firefox. The message is coming from the web site.

I didn't realize Ubuntu/XFCE responded to rageshake. I shook my laptop -- what do I do to get the information to you.

**Comment by SimonBrandner** [comment]
You can type `/rageshake <link to an issue>` to submit logs

**Comment by bjherbison** [comment]
Thank you. I wish yesterday's comment had been phrased that way.
I don't expect a /rageshake now would be useful as I cleared the annoying red mark yesterday. I see the red mark about weekly so I bookmarked this issue so I can submit logs when I see it. (This was the first time I had easy evidence others had seem the "unsent" message.)

**Comment by bjherbison** [comment]
> Thank you for your report. We need some more information from you before our developers can look at it.
> Could you please share a rageshake and give a little more information regarding your setup?

gsouquet: Please try to remember that not all users are experts in the product and avoid using linguistic shortcuts.You shouldn't expect that a ransom element user even knows the phrase rageshake.

**Comment by novocaine** [comment]
Without further info, I think we can assume this is most likely a case of https://github.com/vector-im/element-web/issues/18403 - closing as duplicate
