### ISSUE TITLE
[Desktop] Add ability to hide window on startup

### ISSUE THREAD

**Issue by hwittenborn** [vector-im/element-web#19092]
### Your use case

It would be nice to be able to have Element desktop automatically hide on startup, so I could have Element both start up automatically and then just stay out of my way by default.

**Comment by SimonBrandner** [comment]
Isn't this the default behaviour with `Start automatically after system login` and `Show tray icon and minimize window to it on close` enabled?

**Comment by hwittenborn** [comment]
It doesn't appear to be doing so, no.

Here's the relevant system information if it helps:

Element version: 1.8.2
Olm version: 3.2.3
Platform: Linux

**Comment by hwittenborn** [comment]
Looks like in addition to the security fix I received from the update, the issue got fixed right along with it.

I don't really need a toggle then as long as it stays like that by default. Thanks regardless!

**Comment by hwittenborn** [comment]
Nevermind, the issue came back after powering on my computer this morning.

Here's the current version information:

Element version: 1.8.5
Olm version: 3.2.3

**Comment by gsouquet** [comment]
@hwittenborn Could you confirm whether you're still experiencing this issue or not?

**Comment by hwittenborn** [comment]
Sorry for the delay; My client currently isn't up to date, so I'll have to check after I get a chance to do that.

**Comment by hwittenborn** [comment]
Sorry for the delay again, but I got my client up to date now, but the issue is still persisting.

I forgot I made [this issue](https://github.com/vector-im/element-web/issues/17033) a bit back, but maybe it's related?

**Comment by hwittenborn** [comment]
I started using a new machine a few days ago, and the issue appears to have since disappeared. The new machine also has quite higher specs, and I'm leaning towards that the slowness on my other machine was showing the issue for one reason or the other.

**Comment by SimonBrandner** [comment]
Since you're not experiencing this anymore, I am going to close this. If you or anyone ever sees this again, please let us know

**Comment by jwaciewski** [comment]
> Found the easiest way to do it for the flatpak version is to add `--hidden` to the `Exec` command: ![image](https://user-images.githubusercontent.com/40805353/162764886-4724e57b-14bf-454a-ab12-f32152a44e09.png) keep in mind that editing this startup file requires root privileges.

Why would you need root privileges to edit a file in autostart home directory?

**Comment by ManeraKai** [comment]
I'm not sure why I said that before. Maybe because that file was a shortcut to another root file in the system.

**Comment by chamdim** [comment]
The --hidden flag also works on kde while configuring the autostart for this app. No root privileges here. App downloading from Arch extra repo.
