### ISSUE TITLE
Clicking Create Space causes a thin gap between space panel and room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19093]
### Steps to reproduce

1. Click create space
2. Observe gap

### What did you expect?
For there to be no gap created. The gap is not present when the dialog is closed.

### What happened?
![image](https://user-images.githubusercontent.com/1190097/133915874-1ded1041-f97d-419f-a405-b4d173d6149e.png)

### Operating system

Windows 10

### Browser information

Edge Version 93.0.961.47 (Official build) (64-bit)

### URL for webapp

local build of develop.element.io

### Homeserver

localhost (Synapse 1.43.0rc2)

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
that gap is actually just an issue with the placement of the shade
