### ISSUE TITLE
Screen sharing doesn't work - [Arch Linux] 

### ISSUE THREAD

**Issue by stnert** [vector-im/element-web#19094]
### Steps to reproduce

1 - The share full screen button or just the application is inactive. 
2 - The share full screen button or the application not working, and the share button is also inactive. 
3 - Follow the printscreen in attach 

### What happened?

I expected the button to work for screen sharing or applications. 

### Operating system

Arch Linux

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

AUR -> community/element-desktop 1.8.5-1

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
So the real issue here from my testing seems to be that you can only do screen-sharing once and if you do it again it breaks and you have to restart Element to make it work again?

**Comment by SimonBrandner** [comment]
There is something super-weird going on here
