### ISSUE TITLE
Get admin warning for leaving space I'm not an admin in

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19102]
### Steps to reproduce

1. I am not as admin in the Matrix Community space.
2. Try to leave the space the space:
 
 ![Screenshot from 2021-09-20 14-43-14](https://user-images.githubusercontent.com/51663/134012654-d9c3e3fa-8355-4044-b188-3f034aa18dad.png)

#### What did you expect?
No admin warming

#### What happened?
See admin warning for leaving space:
![Screenshot from 2021-09-20 14-39-06](https://user-images.githubusercontent.com/51663/134012796-5123677a-f918-4d0a-a762-e0b7ad43ca9c.png)

Not seeing it on develop.element.io and only seeing it in the Matrix Community space (not in other spaces).

### URL for webapp

https://61488d29a3ea2dbe370c6b6d--matrix-react-sdk.netlify.app/

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Might be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6824

**Comment by t3chguy** [comment]
If you're only seeing this on a specific netlify build and not on develop then it sounds like a bug with that build?

**Comment by kittykat** [comment]
Cannot reproduce it either any more (was also seeing on a local build at the time).
