### ISSUE TITLE
Element Desktop crashed upon attempting to accept an incoming 1:1 call

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#19104]
### Steps to reproduce

1. Have an incoming 1:1 call.
2. Click pickup from the cell in the timeline.
3. Element desktop closes.

### What did you expect?

The call to start.

### What happened?

Element desktop closed.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021091901; Olm version: 3.2.3

### How did you install the app?

The AUR

### Have you submitted a rageshake?

Yes

**Comment by gsouquet** [comment]
I was not able to unveil any useful information from the rageshake report unfortunately
Looking at the recent changelog, I can only see vector-im/element-desktop#256 that could possibly impact you in this case.

We currently do not have a way to rageshake the IPC logs unfortunately, will open an issue for it

**Comment by SimonBrandner** [comment]
@anoadragon453, are you using Wayland?

**Comment by anoadragon453** [comment]
@SimonBrandner I am not, but I am using Pipewire. It's also worth mentioning that Element desktop did not crash after starting it up again, changing my media sources and sinks in Element's settings and then making a call to the same participant.

**Comment by novocaine** [comment]
If we don't have any other process-level logs or a core dump, we can't take action, so will close for now - we can reopen if we received subsequent reports.
