### ISSUE TITLE
Backspace to delete an emoji creates broken Unicode

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#19103]
### Steps to reproduce

1. In the composer, add an emoji character (via the automatic plaintext to emoji, or by using the emoji picker).
2. Press backspace (you might need to do this more than once).

### What did you expect?

The emoji disappears.

### What happened?

A broken Unicode character (�) appears.

### Operating system

macOS

### Application version

Element Nightly version: 2021092001 Olm version: 3.2.3

### How did you install the app?

I don't remember

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6832
