### ISSUE TITLE
Resizers don't let go on develop

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#19119]

**Comment by SimonBrandner** [comment]
![Screenshot_20210921_210726](https://user-images.githubusercontent.com/25768714/134232555-1dd8d8a6-806b-4d82-a877-0d0c235e320c.png)

This might have something to do with one of my TS conversions, will have a look tomorrow

**Comment by Sleuth56** [comment]
For anyone that needs a work around. You can open an other client and unpin the widget. That fixes it for now.

**Comment by artfb** [comment]
I think it is related to this library https://yarnpkg.com/package/re-resizable and `mouseup` event not firing in Chrome
(latest Brave and Safari work well).

Check:
http://bokuweb.github.io/re-resizable/?path=/story/aspect--default
https://github.com/bokuweb/re-resizable/blob/d681a3b2a5b52d642cdc5f92be6899064b9bdf12/src/index.tsx#L467

Changing mouse events to pointer events eg `mouseup` -> `pointerup` fixes the issue.

**Comment by SimonBrandner** [comment]
> I think it is related to this library [yarnpkg.com/package/re-resizable](https://yarnpkg.com/package/re-resizable) and `mouseup` event not firing in Chrome (latest Brave and Safari work well).
> 
> Check: http://bokuweb.github.io/re-resizable/?path=/story/aspect--default [bokuweb/re-resizable@`d681a3b`/src/index.tsx#L467](https://github.com/bokuweb/re-resizable/blob/d681a3b2a5b52d642cdc5f92be6899064b9bdf12/src/index.tsx#L467)
> 
> Changing mouse events to pointer events eg `mouseup` -> `pointerup` fixes the issue.

The issue was caused by something else and has already been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6850
