### ISSUE TITLE
Use light theme in all HTML chat exports

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19117]
#### What would you like to do?

Once the new [export chat feature](https://github.com/matrix-org/matrix-react-sdk/pull/6081) merges, I would like it to apply the light theme in all cases, even if I'm using the dark theme in Element.

#### Why would you like to do it?

To have more confidence in printing, aid familiarity when sharing history with users not using dark themes.

### Have you considered any alternatives?

I did consider whether this should be an option. Decided against as the export options are already complex, and it seems needless to add more complexity for something we can just be more resolute on.

**Comment by gsouquet** [comment]
I believe using the [`media`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-media) attribute on the [`<link/>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) tag we could honour the user's system theme using `prefers-color-scheme`.

And we would still be able to force the light theme using `media="print"` if a user wants to print a chat history.

Do you believe this could meet all the criterias to have your request fixed?
