### ISSUE TITLE
WEB/DESKTOP Login Request Timeout

### ISSUE THREAD

**Issue by Sr-Preet** [vector-im/element-web#19121]
Whenever I'm trying to login via WEB or DESKTOP application the request timeout after exactly one minute
But when I login with mobile app it's working fine then.
I'm not getting this issue with everyone, but just once in a while it pops up.
Can anybody please help me with this?

**Comment by gsouquet** [comment]
Thank you for your report. We need some more information from you before our developers can look at it. Please edit your issue to include replies to all sections.

Please comment to let us know when you've had a chance to add more details to the issue.

**Comment by Sr-Preet** [comment]
> Thank you for your report. We need some more information from you before our developers can look at it. Please edit your issue to include replies to all sections.
> 
> Please comment to let us know when you've had a chance to add more details to the issue.

Thanks @gsouquet for replying
The thing is that I'm not able to replicate this issue. But It is happening with a couple of users.
In the network tab I'm getting CORS issue, which shouldn't even be there.
On top of that, It's not getting recorder in the synapse logs also.
Am I missing something here?

**Comment by gsouquet** [comment]
Following the template given on https://github.com/vector-im/element-web/issues/new/choose will help the developers to look into this issue and assist you the best they can.

A CORS issue likely indicates an issue with the homeserver but it is difficult to say without more information at hand

**Comment by Sr-Preet** [comment]
Yeah I think I opened an blank issue.
Thanks for helping. I'll dig into the logs to see if i can find something.
