### ISSUE TITLE
Fix room notifications count for threaded events

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19126]
For the first iteration, read receipts and read markers will not be supported for Threads.
At the moment when a new event is received, this will increment the notification count.

However, upon viewing the "thread view" read receipts are disabled, therefore the notification count is never disabled.

Splitting events across different timeline sets breaks the contract that all events are in chronological order. Meaning that the way read receipts work is not entirely correct anymore

Design: figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1246%3A231502 

## Requirements

- [x] When receiving a new threaded event the notification count should increase by 1
- [x] When mentioned in a thread the notification pill color should turn to red
- [x] When opening a room only the events in visible timelines should be decremented from the room's notification count
- [x] Upon opening a thread, if it contains any unread messages, decrement the room notification count
- [ ] if notification count is only related to one thread, open the thread view when switching to that room
- [ ] if notification count is related to 2+ threads, open the room and the threads list
- [ ] if notification count is related to main timeline only, keep the same behaviour as pre-thread

**Comment by daniellekirkwood** [comment]
We discussed this today and landed here: 
- We will implement notifications in a way that includes numbers (and colours) in the notification badges
- Users may have a notification on each platform they have Threads on, this is a temporary compromise we are willing to make (it's better to have a notification twice, than miss something completely)
- The goal is to implement this in such a way that very little work is needed on Client side once Server supports read receipts

@gsouquet did I capture this correctly?

**Comment by daniellekirkwood** [comment]
[Notification documentation and notes](https://docs.google.com/document/d/1V5G1WbvBwvqt3t0XCMfIt39Eu-veoN-4Ca7Z5VGE_A8/edit?usp=sharing)
