### ISSUE TITLE
Error Code: Bad_session when creating account with Sign in with Google and account already exists

### ISSUE THREAD

**Issue by hanthor** [vector-im/element-web#19137]
### Steps to reproduce

1. Clicked Create account at staging.element.io
2. Click Sign in with Google
3. Sign in with a person gmail account with 2FA turned off
4. Get the following error on the next screen

### What did you expect?
A prompt to create a new Matrix account

### What happened?
![image](https://user-images.githubusercontent.com/5840441/134378454-18252016-5fb3-4764-8295-9ca07606d12d.png)
at URL https://matrix-client.matrix.org/_synapse/client/new_user_consent#

### Operating system

Windows

### Browser information

Chrome 94.0.4606.54

### URL for webapp

staging.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
I can't reproduce.

I think your issue is somehow account specific - have you already created an account with that SSO provider?

**Comment by hanthor** [comment]
Looks like I already had an account tied to the google account. So I got an error when I tried to make a new account with the same google account. Would be nice if there was some indication instead of giving a mysterious error

**Comment by kittykat** [comment]
I managed to reproduce this:
1. Go to the web app
2. Register
3. Google account
4. Create a new account with a new gmail address
5. Go through the creation process until you've entered your DoB and then go to the next screen (terms of service/privacy or something like that)
6. Open a new tab and to go the webapp (same URL as before is fine)
7. Register -> Google account
8. Type in your new account email address
 -> See notification that account doesn't exist
9. Go back to first tab and finish registration
 -> On registration completion, see that error message

**Comment by novocaine** [comment]
The error message is rendered by Synapse, so we need to create an issue for that there.

**Comment by Nexus2k** [comment]
I believe you can prevent this error by setting `allow_existing_users: true` in the synapse config https://matrix-org.github.io/synapse/latest/sample_config.yaml -> search for allow_existing_users.

**Comment by t3chguy** [comment]
If you are still experiencing this bug, please open an issue in https://github.com/matrix-org/synapse/
