### ISSUE TITLE
Difficult to find how to leave a space

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#19144]
### Steps to reproduce

I wanted to leave a space, here called "Space". I clicked the "Explore Space" interaction as I remembered it brings up the generic space description and room list. Expected to see a "Leave" button. The button with three dots doesn't seem to bring up a menu as my next expectation.

After some searching, I managed to leave the space by right clicking it in the sidebar and choosing "Leave space".

Note, I'm only a member of the space with no special power, which probably explains not seeing any space settings either. This is also slightly confusing, since rooms have a settings panel visible always, even without power levels - you're just not able to change things. Now I can't even find the space internal room ID

![Selection_999(566)](https://user-images.githubusercontent.com/1174866/134469565-5fce9ce2-7ac7-4a15-8e93-d39d6200ed0a.png)

### What did you expect?

To find a leave space button.

### What happened?

Didn't see a leave space button.

### Operating system

Ubuntu 20.04

### Application version

Element Nightly version: 2021092201 Olm version: 3.2.3

### How did you install the app?

Official debs.

### Homeserver

federator.dev

### Have you submitted a rageshake?

No

**Comment by kittykat** [comment]
Leaving a space works in the same way as leaving a room (from the left menu or settings), so re-tagging this as an enhancement as it would be a different interaction which needs design

**Comment by jaywink** [comment]
I agree however one cannot access settings of a space unless one has power in the space. Possibly settings should always be visible read-only like for rooms?

**Comment by nadonomy** [comment]
Closing as this has changed to be more visible with the latest IA changes (https://github.com/vector-im/element-web/issues/19527).

@jaywink if this is still not discoverable enough for you please re-open with amended screenshots. Thx!

**Comment by MadLittleMods** [comment]
I had the same feedback as @jaywink after the IA changes mentioned above -> https://github.com/vector-im/element-web/issues/21715
