### ISSUE TITLE
Users complain that they do not receive an e-mail after a message is received but not read after 10 minutes

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#19148]
I have a request from a customer:

> Every time the user logs off the option for notifications “Enable email notification” automatically turns off.
> This option is not saved when the user selects this option.

**Comment by gsouquet** [comment]
Thank you for opening this issue, could I ask you to fill in the defect template?
It's a bit unclear to me how to reproduce this issue and what that user is expecting

**Comment by Palid** [comment]
@benparsons 
Could you please fill in the details acoording to the defect template? We can't figure out what needs to be done here.

**Comment by benparsons** [comment]
Let's close for now, I don't recall the source of this.
