### ISSUE TITLE
[Important] Built-in matrix and slack integration no longer work

### ISSUE THREAD

**Issue by itsnotsaved** [vector-im/element-web#19159]
### Steps to reproduce

**About the issue**

Recently, I tried to integrate Matrix with Slack using Element (Matrix) built-in integration but when going to configure auth set up on Slack then page doesn't work.

[Matrix] Go to one room on my matrix space
https://matrix.to/#/#wplk:matrix.org

[Matrix] Go to room info and add "widgets, bridges and bots" (screen1)
https://i.ibb.co/3kRV796/screen1.png

[Matrix] pick slack and add bridge (screen 2, 3)
https://i.ibb.co/QC6gYV7/screen2.png
https://i.ibb.co/tmtLfJN/screen3.png

[Matrix] add slack (screen 4, 5)
https://i.ibb.co/yh78PTP/screen4.png
https://i.ibb.co/GVFNGbX/screen5.png
https://wplk.slack.com/

[Slack] allow permissions (screen 6)
https://i.ibb.co/5TxbCVV/screen6.png

[Slack] this page isn't working (screen 7)
https://i.ibb.co/rpLtwNP/screen7.png

**Slack support response**
![image](https://user-images.githubusercontent.com/73447325/134669182-11dbc462-65e0-46a8-ba0b-25e9f111c50f.png)

**Discussion on EMS room**
![image](https://user-images.githubusercontent.com/73447325/134669438-20d2147a-4054-48b5-bf0a-6cb5e9ddf305.png)
![image](https://user-images.githubusercontent.com/73447325/134669486-149e841e-6148-4a5e-82f2-c78d23ba3379.png)

### What did you expect?
Work

### What happened?
No longer work

### Operating system

Ubuntu 21.04

### Browser information

Chromium

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
I believe this should be open in the bridge repo (which would https://github.com/matrix-org/matrix-appservice-slack probably) since this isn't an issue with Element but the bridge

**Comment by itsnotsaved** [comment]
https://github.com/matrix-org/matrix-appservice-slack/issues/617
