### ISSUE TITLE
Event missing from timeline

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#19156]
### Steps to reproduce

This seems rather odd, and I can't entirely rule out a server-side bug, but I think the symptoms mean it has to be client-side:

In our "Backend Internal" room, we have a calendar bot which sends a message to the room at 10:00, with @mentions for most of the room (including myself).

This morning, when the event arrived, I was looking at a different room. I saw "Backend Internal" was red, so switched to it, but the relevant event is missing from the timeline.

The event is visible on another device on the same account.

### What did you expect?

Event should be visible in the timeline

### What happened?

A missing event

### Operating system

Ubuntu

### Application version

Element Nightly version: 2021092301 Olm version: 3.2.3

### How did you install the app?

nightly debian

### Homeserver

sw1v.org

### Have you submitted a rageshake?

No

**Comment by richvdh** [comment]
the event is not present in `window.mxMatrixClientPeg.get().store.getRoom(...).timeline`, for the record.

**Comment by t3chguy** [comment]
> but I think the symptoms mean it has to be client-side:

Possibly the /sync response contained the highlight count increase but not the event

The room in question is non-e2ee so the client blindly trusts the counts provided by the server.

**Comment by turt2live** [comment]
@richvdh has this happened since?

**Comment by turt2live** [comment]
closing in favour of https://github.com/vector-im/element-web/issues/21112 for now. If we determine it's a different issue, we can reopen or establish a new ticket.
