### ISSUE TITLE
Something went wrong after adding a custom widget using the `/addwidget` command

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#19152]
### Steps to reproduce

1. Add any website URL in the /addwidget command
2. Pin the newly created widget

### What did you expect?
The custom widget loads

### What happened?
Something went wrong

For a bit of context, yesterday I tried adding play.fancade.com as a custom widget using the `/addwidget` command, pinned the widget, something went wrong, eventually was able to remove it on Element Android

...and now today I tried adding a meet.jit.si meeting URL as a custom widget in the same way, then once again, something went wrong

Keep in mind that I was using the nightly version

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021092201 Olm version: 3.2.3

### How did you install the app?

AUR

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment]
@Linerly, could you please try with a newer nightly? We might have fixed this issue already

**Comment by Linerly** [comment]
The widget loads with the webpage and stuff, although the game itself failed to load (it shows the “Unable to load Fancade” message)

…even if I go to another room with some pinned widgets, they load just fine

**Comment by SimonBrandner** [comment]
So the previous issue with `Something went wrong` is now resolved and there is a new issue? Could you please create a new issue with the URL of the widget and logs then?

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19172
