### ISSUE TITLE
"You have unverified logins" toast "Review" response is broken

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19158]
### Steps to reproduce

1. "You have unverified logins", click "Review"

#### What did you expect?
"Security & privacy" view in settings dialog 

That dialog also has a "verify them in your user profile" link which also takes me to the same blank screen

#### What happened?
URL changed to https://develop.element.io/#/user/@<me>:matrix.org and I got a blank screen

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by novocaine** [comment]
Similar, but not identical to https://github.com/vector-im/element-web/issues/17667

**Comment by dbkr** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6787
