### ISSUE TITLE
Cannot add alias to a room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19151]
### Steps to reproduce

1. Go to the room settings try to add a room alias, see this error
  ![Screenshot from 2021-09-23 23-17-36](https://user-images.githubusercontent.com/51663/134596174-f160173a-33ec-4cd5-839e-96f2600d5505.png)

2. Look at the settings now and see the alias is showing in the UI:
  ![Screenshot from 2021-09-23 23-18-48](https://user-images.githubusercontent.com/51663/134596234-fb0edc81-bb0e-431b-a88f-39f6574b5cdd.png)

3. Look at the settings in another tab and see no alias
  ![Screenshot from 2021-09-23 23-19-12](https://user-images.githubusercontent.com/51663/134596288-df1c17cb-82af-49c2-81c7-c9e31d95f5c9.png)
 

### What happened?

I expected to be able to add an alias
If the alias isn't added, I expect to not see it in the settings dialog after the failure.

### Operating system

Arch Linux

### Browser information

Chromium Version 92.0.4515.131 (Official Build)

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
Would you be able to try again and share the network call that failed?
It would help to pinpoint the cause of this issue and to detect whether the issue lies with Element or Synapse

**Comment by kittykat** [comment]
@gsouquet sorry, didn't see your message earlier. Might be good practice to @ a person if they need to action an issue?


https://user-images.githubusercontent.com/51663/147076320-f11f5f19-9774-4a35-9947-394229b63d5d.mp4

**Comment by kittykat** [comment]
This is actually a duplicate of #13077
