### ISSUE TITLE
Visual regression in "Spaces with access" on a space's visibility settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19164]
### Steps to reproduce

1. Create a subspace
2. Set it up to have visibility to match the parent space
3. Open settings for the subspace

### What happened?

![image](https://user-images.githubusercontent.com/1190097/134705405-5a2d8547-0c95-4dff-839f-4a0e3482b1ed.png)

### Operating system

Windows 10

### Application version

Nightly (2021-09-23)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Have you submitted a rageshake?

No

**Comment by turt2live** [comment]
Release blocker to determine if this affects staging. If yes, would need fixing.

**Comment by t3chguy** [comment]
Hmm, I cannot reproduce this on develop:

![image](https://user-images.githubusercontent.com/2403652/135084430-8acf1f26-de36-4299-8590-1534d0b7e981.png)

**Comment by turt2live** [comment]
@t3chguy that looks like a room, not a space. 

I can still reproduce this on develop using the same BizOps space.
