### ISSUE TITLE
"Sort by" options in roomlist list options doesn't respond reliably to clicks in Firefox and Chromium

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#19160]
### Steps to reproduce

1. Go to a room sublist header (any one) and click on the ellipsis
2. Try and switch between the Sort by radio options (Activity, A-Z)
3. Observe that it sometimes takes a number of clicks to force a change (clicking on either the radio itself or the label)

This does not occur in Element Desktop, but occurs on Element Web at least as far back as https://riots.im/1.7.21

### What did you expect?
A single click to work

### What happened?
I had to click lots of times

### Operating system

Windows

### Browser information

Firefox Nightly 93.0a1 (2021-09-01) (64-bit) and Chromium 93.0a1 (2021-09-01) (64-bit)

### URL for webapp

https://develop.element.io, https://riots.im/1.7.21

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/commit/9289c0c90fc6877aa6ea751a1ac3c92b16611ef9#diff-56c717b6ca043fbdc54936f15ed13e15915ae8a544768e90c0aea91db197613bR405
