### ISSUE TITLE
Emoji suggestions not popping up when encased with parentheses

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19175]
### Steps to reproduce

1. Type `()`
2. Have your cursor inbetween the parentheses `(|)`
3. Type any emoji `(:eyes|)`
4. Observe no emoji being suggested

### What did you expect?

An emoji suggestion screen to pop up after the first `:`

### What happened?

No emoji suggestion screen

### Operating system

Linux

### Application version

Element version: 1.8.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Have you submitted a rageshake?

No

**Comment by ShadowJonathan** [comment]
Here is a video showcasing the effect;

https://user-images.githubusercontent.com/22740616/134802731-3496b146-edbf-437b-9a97-d7e7b7bf85a2.mp4

**Comment by SimonBrandner** [comment]
Not just `(` but after any character, which makes sense, imo. It matches Discord

**Comment by ShadowJonathan** [comment]
In that case i'm inclined to close "as-intended".
