### ISSUE TITLE
"Unable to load Fancade" issue

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#19171]
So the previous issue with `Something went wrong` is now resolved and there is a new issue? Could you please create a new issue with the URL of the widget and logs then?

_Originally posted by @SimonBrandner in https://github.com/vector-im/element-web/issues/19152#issuecomment-927241063_

**Comment by SimonBrandner** [comment]
@Linerly, could you please fill in the issue template?

**Comment by Linerly** [comment]
Oh, wait

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19172
