### ISSUE TITLE
Room stays in invite room list after joining

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#19184]
### Steps to reproduce

0. (Possibly related) Someone upgrades a room that you are in
1. Be invited to that room, and join the room
2. The room is now joined and you can talk in it
3. However, the room is still in the invite list.

### What did you expect?

The room would be in my "Rooms" list section

### What happened?

The room is still in my invites list

### Operating system

Ubuntu 20.04

### Application version

1.8.5

### How did you install the app?

apt

### Homeserver

half-shot.uk

### Have you submitted a rageshake?

Yes

**Comment by Half-Shot** [comment]
This fixes itself after clicking around on a Space, so corrects itself when the room list gets recalculated.

**Comment by t3chguy** [comment]
I hit the same bug in https://github.com/matrix-org/element-web-rageshakes/issues/9490
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7635 - do shout if you see it again
