### ISSUE TITLE
Un/mute button not working in 1:1 video call

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19182]
### Steps to reproduce

1. Video call
2. Click mute microphone button

### What did you expect?
- button changes to indicate muted status
- press button again to unmute

### What happened?
- button does not change to indicate muted
- however I am still muted
- pressing it again does nothing
- had to restart the call to work around

Meanwhile "muting" and un"muting" video worked as expected.

### Operating system

arch, wayland (sway), pipewire
Element running in ozone (i.e. wayland native), not xwayland

### Application version

Element Nightly version: 2021092401 Olm version: 3.2.3

### How did you install the app?

aur/nightly-bin

### Homeserver

private

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
Should be fixed in the next nightly, sorry for the troulbe
