### ISSUE TITLE
Room settings shows invite level as `Moderator` when the invite level isn't set.

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#19187]
### Steps to reproduce

1. Create a new room.
2. Use the dev tools to *remove* the `invite` level from the power levels event.
3. Open Room Settings > Roles & Privileges and look at `invite` level

### What did you expect?

The invite level to say `Default`

### What happened?

The invite level says `Moderator`. This is incorrect, and normal users can invite.

### URL for webapp

develop.element.io

### Homeserver

jki.re

### Have you submitted a rageshake?

No

**Comment by erikjohnston** [comment]
This appears to also effect android https://github.com/vector-im/element-android/issues/4089

**Comment by t3chguy** [comment]
> The level required to invite a user. Defaults to 50 if unspecified.

https://matrix.org/docs/spec/client_server/r0.6.1#m-room-power-levels

**Comment by bmarty** [comment]
Yes, also in the power_level state event, "state_default" is set to `50` (by default).

**Comment by erikjohnston** [comment]
> > The level required to invite a user. Defaults to 50 if unspecified.
> 
> https://matrix.org/docs/spec/client_server/r0.6.1#m-room-power-levels

Oh, blast, I forgot that this is a spec bug: https://github.com/matrix-org/matrix-doc/issues/3281



> Yes, also in the power_level state event, "state_default" is set to `50` (by default).

For historical reasons we don't apply `state_default` to membership events (we don't do it for joins for example).

**Comment by bmarty** [comment]
> For historical reasons we don't apply state_default to membership events (we don't do it for joins for example).

So you use the value of `events_default` for membership events (i.e. `m.room.member` events)? Or just `0` if "invite" is not specified

**Comment by erikjohnston** [comment]
> > For historical reasons we don't apply state_default to membership events (we don't do it for joins for example).
> 
> So you use the value of `events_default` for membership events (i.e. `m.room.member` events)? Or just `0` if "invite" is not specified

Membership events basically use a custom set of authorization rules, only relying on the `ban`, `kick` and `invite` levels. The base set of authorization rules are at https://spec.matrix.org/unstable/rooms/v1/#authorization-rules (though they've been updated in subsequent room versions)

**Comment by bmarty** [comment]
Ok. Actually after a check in the code, the Android SDK does not use `events_default` but a hard-coded value when "invite" is not specified.

The places to update this are:
- https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/PowerLevelsContent.kt#L114
- https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/PowerLevelsContent.kt#L37

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/commit/1afecc474fd3a85248bf3a833b008d7b2c46d959
