### ISSUE TITLE
Chrome 52's video tag layout appears to truncate the thumbnail

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1918]
The word 'WOW' has been lopped off the example below:

<img width="560" alt="screen shot 2016-08-02 at 18 27 00" src="https://cloud.githubusercontent.com/assets/1294269/17338301/d99131f8-58de-11e6-8056-ffbd037a24a4.png">

**Comment by MadLittleMods** [comment]
Here is what the latest Chrome `<video>` styles look like. Their controls still cover the video and disappear after timeout but it's a little more transparent. Feels like we should close this one though unless we want to add our own player styles.

https://user-images.githubusercontent.com/558581/132075970-82786cb6-9a1a-4f81-840b-ff4042ef1689.mp4
