### ISSUE TITLE
if a tombstone event has no body, the UI doesn't give a fwd link to the new room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19207]
If you manually send an `m.room.tombstone` event in order to route a room from one place to another, then if you don't specify a `body` field in the event contents to give a reason for the tombstoning, then the forward link is missing from the composer view.  It should look like this:

<img width="1092" alt="Screenshot 2021-10-04 at 11 59 07" src="https://user-images.githubusercontent.com/1294269/135840059-2272cbf3-a101-4ac6-99e7-77073c418672.png">

but instead it looks like:

<img width="1092" alt="Screenshot 2021-10-04 at 11 59 07" src="https://user-images.githubusercontent.com/1294269/135840165-f641df97-b7b5-48d2-97b2-4bb920599b51.png">

As a result, rooms which have been upgraded by a script or by someone manually sending a tombstone event which lack a `body` result in dead-end rooms with no way to discover the new room, which is a pretty horrific failure mode.  The same happens if you redact a tombstone event, which is arguably a more common way to trigger it. You can work around it by sending a new tombstone event with a `body` field, but it'd be much better if EW didn't bug out in the first place.

**Comment by Palid** [comment]
@ara4n related? https://github.com/vector-im/element-web/issues/19113

**Comment by kittykat** [comment]
@ara4n how likely is the tombstone event to not have a body? It would be helpful for triage if you could include more information in the issue description :+1:

**Comment by t3chguy** [comment]
This is actually based on `replacement_room` being in content, not `body`. This is obvious as without this field you cannot know where to link to.

![image](https://user-images.githubusercontent.com/2403652/216956447-50f4a6e1-e076-4474-a885-5f2b35acaf7e.png)
![image](https://user-images.githubusercontent.com/2403652/216956462-58b06c11-a296-4479-9031-9988c9af1a9c.png)
