### ISSUE TITLE
Change image pasting format from PNG to JPEG (of AVIF) to save disk space

### ISSUE THREAD

**Issue by fockr** [vector-im/element-web#19200]
#### What would you like to do?
I would like Element to not use PNG format when pasting images from the clipboard.

#### Why would you like to do it?
The PNG format takes way to much disk space and reduces the transfer speed. Better alternatives exist while preserving the image quality.

#### How would you like to achieve it?
You could change the default encoder to JPEG or the even more efficient AVIF format.

### Have you considered any alternatives?

My current solution to this is saving a file manually as JPEG and uploading it to a room. As to animated GIFs, the AVIF format gives me usually a 10-20 fold decrease of file size.

**Comment by t3chguy** [comment]
The format is set by your browser, not by Element.
Try pasting into http://madebyevan.com/clipboard-test/

![image](https://user-images.githubusercontent.com/2403652/135091119-52d7dbd0-e332-4581-958c-e6bc2c0eeac6.png)

https://github.com/vector-im/element-web/issues/4144 is the issue about upload time compression/reencoding
