### ISSUE TITLE
Converting a community to a space fails when containing many users

### ISSUE THREAD

**Issue by markvoortman** [vector-im/element-web#19216]
### Steps to reproduce

1. Whenever I try to convert a community to a space it fails when it contains many (~75) users.
2. Go to Settings > Preferences > Show my Communities > Create Space.
3. It then fails to complete that action, for a screen shot see the "what happened" section.
4. I also tried the desktop app (in addition to the web app) but that didn't make a difference.

Note: it did work for communities with only a few or no users.

### What did you expect?

I expected the community to be converted to a space.

### What happened?

It failed and asked me to retry (which also didn't work).
On the web console this error was visible:

<img width="807" alt="Screen Shot 2021-09-28 at 7 22 38 PM" src="https://user-images.githubusercontent.com/5963034/135178931-ec4ffa71-10cd-4d5a-acc3-7e93b188d9e1.png">

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
I don't think the spec defines a limit on how many users you can invite at once, so this is a pesky Synapse implementation detail which the client has no way of getting at.

**Comment by novocaine** [comment]
Can we increase it for matrix.org, which is where I think this bug is filed for?

**Comment by t3chguy** [comment]
We could also do the invites one-by-one like we have to for room upgrades, but this would make the operation much much slower

**Comment by novocaine** [comment]
My view would be that if its a one time operation, it can be slow as long as we signal progress to the user. And doing it that way would be more robust on homeservers we can't re-config.

**Comment by t3chguy** [comment]
Need design on how to signal progress to the user as part of this interaction then

**Comment by markvoortman** [comment]
Thanks for all the prompt responses!

> Can we increase it for matrix.org, which is where I think this bug is filed for?

That is correct, and would solve my immediate problem.

> We could also do the invites one-by-one like we have to for room upgrades, but this would make the operation much much slower

I would be perfectly fine with waiting, as it's only a one-time operation, but a heads up to the user would be nice indeed.
I'm not familiar with the relevant code, but would it be an option to divide the work into reasonably sized batches?

**Comment by t3chguy** [comment]
> but would it be an option to divide the work into reasonably sized batches?

Nope you can only batch invite at room creation time, any invites thereafter have to be singular. We also have no way of querying the server for its limit so can't even make use of that first larger batch.

**Comment by niquewoodhouse** [comment]
> Need design on how to signal progress to the user as part of this interaction then

We have this as part of the add existing rooms dialog.

Can the same progress/error states be used?  

<img src="https://user-images.githubusercontent.com/1587166/135440711-8bdf5324-aa0f-4768-b559-abff254b1e08.png" width="400">

<img src="https://user-images.githubusercontent.com/1587166/135440725-fab7d398-3567-4cd9-8cb1-3d4a000df342.png" width="400">

**Comment by JoshStrobl** [comment]
Running into this as well except I don't even have 20 people in my Matrix (via matrix.org) community. Why is the rate limit so low?

**Comment by t3chguy** [comment]
> Why is the rate limit so low?

That's a question for the matrix.org Ops team rather than an Element Web issue tracker but my best guess is to prevent someone mass spam inviting people to rooms.
