### ISSUE TITLE
Rooms cannot be restricted (allow access) to spaces they are not part of

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#19213]
### Steps to reproduce

1. Create a private room (not in a space)
2. Upgrade it to version 9
3. Try to restrict it to a space in **Room Settings** > **Security & Privacy** > **Access** > **Space members**

### What did you expect?

Allow to restrict rooms to all spaces my client knows about.

### What happened?

The UI does not show any spaces to restrict to:

![image](https://user-images.githubusercontent.com/6731714/135159419-a2334cd9-dbbb-422b-84fb-1fddc20cdfe1.png)

Similarly if the room is part of a space, it cannot be restricted to another space that it is not part of.

### Workaround

Use `/devtools` to manually edit `m.room.join_rules`, which then shows the space with access in room settings:

![image](https://user-images.githubusercontent.com/6731714/135160769-03702188-13ee-43fc-9704-f31320f77938.png)

**Edit which spaces can access here.** still does not show the space restriction:

![image](https://user-images.githubusercontent.com/6731714/135159419-a2334cd9-dbbb-422b-84fb-1fddc20cdfe1.png)

### Operating system

Windows

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

phys.ethz.ch

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
This was done intentionally to make that list as minimal as possible, given that allowing joins from users in space X if the room isn't in space X then how would users even discover that room

**Comment by rda0** [comment]
> This was done intentionally to make that list as minimal as possible, given that allowing joins from users in space X if the room isn't in space X then how would users even discover that room

It could be discovered in space Y or any other way (room aliases/ids, matrix.to links).

I thought so that it was done intentionally and I think it probably makes sense for the majority of space usage cases. What about a check box `Show all spaces`, that is by default off?

**Comment by niquewoodhouse** [comment]
> I thought so that it was done intentionally and I think it probably makes sense for the majority of space usage cases.

just to check, please, @rda0 what's the use case that you have here?  Thanks so much

**Comment by rda0** [comment]
> 
> 
> > I thought so that it was done intentionally and I think it probably makes sense for the majority of space usage cases.
> 
> just to check, please, @rda0 what's the use case that you have here? Thanks so much

@niquewoodhouse I am a server admin in a university. Our simplified organizational structure looks like `uni > n departments > n institutes > n research groups`. Typically a research group wants a private space and private rooms in them to communicate. Most of our rooms are private, most of our rooms would like to be restricted. People sometimes would like to have an option to create rooms that are accessible by uni/department members only. Our university is very federated (both physically and organizational). Our Matrix users are federated over multiple servers on uni and department level. We have a relatively high fluctuation of memberships in those organizational structures.

In an ideal world and if the following features are ready (out of beta) or implemented:

- subspaces (space trees)
- subspaces in compact view: #17472
- pinning of top level spaces #17347

building a huge tree of spaces reflecting our structure would make this issue go away, since you can restrict rooms in Element to parent spaces. Although I have doubts that it will ever be possible to organizationally manage such a spaces construct.

I think just restricting a room to space X without having all the subspace organizational complexity is much simpler for the end user. Of course we can instruct our users to use the `/devtools`. But regular people (not developers or Matrix admins) do not like to use `/devtools` or to type json.

As a Matrix admin I would like to have more features in my client rather than less. I would like to be able to use all features of the Matrix protocol using the clients UI.

**Comment by luxaritas** [comment]
I'd also like to jump in with a use case: I'm on a project where some of our code is open source, but not all of it. My desired hierarchy is like:
```
My Company
- Core Team
- Development
  - Public Project
  - Private Project
```

The "private project" room should only be available to members of the core team, but I don't want to have to add it as a subspace of core team as it should be considered a high-level space under my company, as it is accessible to public members of the company as well.
