### ISSUE TITLE
Updating room topic breaks room avatar preview in settings

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19226]
### Steps to reproduce

1. Go to the settings for a room where you are admin
2. Update room topic
3. Click "Save"

### What did you expect?
Room avatar to still show correctly in the setting dialog

### What happened?
![Screenshot from 2021-09-29 17-26-37](https://user-images.githubusercontent.com/51663/135310056-e0d716f0-666b-4328-8a25-1f026849dea3.png)

### URL for webapp

develop.element.io

### Have you submitted a rageshake?

No

**Comment by jaller94** [comment]
This is now on staging.element.io
