### ISSUE TITLE
Action bar safe zone blocks interactions with message bubble content

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#19227]
### Steps to reproduce

1. Enable the message bubble layout
2. Receive a 1 line text message with a link, spoiler, or "edited" button at the end (or even just an image)
3. Try to interact with the contents of the message

### What happened?

https://user-images.githubusercontent.com/48614497/135329873-cb696ebe-9471-46f7-a052-0acfd1f36a3f.mp4

Within a certain zone near the top-right corner of the bubble, it is impossible to interact with the link/spoiler/image, because the invisible "safe hover zone" for the message action bar blocks it.

### What did you expect?

I should be able to click on links as long as they aren't visually obscured by something.

### Operating system

NixOS unstable

### Browser information

Firefox 92.0

### URL for webapp

develop.element.io

### Homeserver

townsendandsmith.ml

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Looks like MAB got moved up sufficiently for this to no longer be an issue.


https://user-images.githubusercontent.com/2403652/146563325-6a08f3df-9b9a-40cd-8f0f-6c188cb2bd61.mov

@amshakal @daniellekirkwood do you agree this is no longer an issue?

**Comment by t3chguy** [comment]
Nvm, it is still an issue for left-column messages which have a different vertical offset for the MAB.

![image](https://user-images.githubusercontent.com/2403652/146563580-ef16774e-2927-477f-8ed0-662918c48831.png)

@amshakal what positioning should the MAB have in bubble layout? presumably the same regardless of left or right column

**Comment by daniellekirkwood** [comment]
What is MAB?

**Comment by t3chguy** [comment]
MAB = Message Action Bar
![image](https://user-images.githubusercontent.com/2403652/146568357-fd74cc38-9afb-47c9-8de6-20c7bdb4e157.png)

**Comment by amshakal** [comment]
Here is a mockup of MAB

![Screenshot 2021-12-17 at 17 00 38](https://user-images.githubusercontent.com/85162587/146592743-c8b52551-2039-4cb8-a93e-e1c71651d4c4.png)
