### ISSUE TITLE
Call time increasing quicker than realtime

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#19221]
### Steps to reproduce

I don't have much in the way of reproduction steps, only that I noticed this while on a 50+ min call with @babolivier last week. I only noticed it happening about halfway through.

### What happened?

The little counter for the current time the call has been going on for was originally counting 1 second per second.

Then it started going up 2 seconds for every 1 second.

Then up 3 seconds for every 1 second.

When the call finished, the frozen time in the call tile was accurate.

![image](https://user-images.githubusercontent.com/1342360/135254606-95fe6fc8-50d4-4f6e-8f9e-ca260aeea566.png)

My only suggestion would probably be to look at the code and see if it's possible for the timer to increase quicker than normal.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021092301 (or earlier) Olm version: 3.2.3

### How did you install the app?

The AUR

### Have you submitted a rageshake?

No

**Comment by SimonBrandner** [comment]
I think we can just blame relativity here 😄 

Will investigate
