### ISSUE TITLE
Selecting a room from room list search should not jump to a space

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#19223]
### Steps to reproduce

1. Enable "Show all rooms in Home" in Preferences
2. From the Home space, search for some room joined to a space, such as "Matrix HQ"
3. Click on the "Matrix HQ" room tile

### What did you expect?

I expect to remain in the Home space, since that is where I started.

### What happened?

My view changed to the "Matrix Community" space, I assume since HQ is part of that.

### Operating system

macOS

### Browser information

Firefox 94

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by jryans** [comment]
AFAICT, this is a regression in the last week or so, as it was working the way I expected for most of the Spaces beta period on develop.

**Comment by t3chguy** [comment]
Weirdly I cannot reproduce this.

https://user-images.githubusercontent.com/2403652/135278713-8b103dde-e589-40dc-996d-3a9654d54b06.mov

**Comment by jryans** [comment]
Hmm, that's quite puzzling... here's a recording from my side:

https://user-images.githubusercontent.com/279572/135279565-0542466f-d83e-49be-bec3-9b75f4bc11e8.mov

**Comment by jryans** [comment]
Hmm, curious, it seems like `SpaceStore` does not believe it is in "all rooms in Home" mode, even though the setting is enabled... 🤔

**Comment by jryans** [comment]
`mxSettingsStore.getValue("Spaces.allRoomsInHome")` says `true`

**Comment by t3chguy** [comment]
So is `mxSpaceStore.allRoomsInHome` `false` then?

**Comment by jryans** [comment]
> So is `mxSpaceStore.allRoomsInHome` `false` then?

Yes, indeed, it gives `false`. 🤔

**Comment by t3chguy** [comment]
oh.
I know what it is, and it is indeed a recent regression from me adding a null-guard to the dispatch handler, so it misses the setting being read

**Comment by t3chguy** [comment]
Thanks for the debugging @jryans

**Comment by jryans** [comment]
Verified fixed on develop, thanks! 😄
