### ISSUE TITLE
Searching in Spaces summary should call the pagination api if no results are yet found

### ISSUE THREAD

**Issue by emorrp1** [vector-im/element-web#19235]
### Steps to reproduce

1. [#gaming-space:matrix.org](https://matrix.to/#/#gaming-space:matrix.org)
2. Search names and descriptions: "arcadia"
3. Clear search box
4. Press "End" keyboard shortcut, wait for the throbber to disappear
5. Search names and descriptions: "arcadia"

### What did you expect?
The identical searches in steps 2 and 5 should find the same result:
![image](https://user-images.githubusercontent.com/71895/135460441-10732efd-b4a7-4ff6-b256-1e99eaa764e2.png)

### What happened?
The search succeeds only after all the rooms have been loaded via pagination, Step 2 incorrectly displays:
> No results found
> You may want to try a different search or check for typos.

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

flatpak https://flathub.org/apps/details/im.riot.Riot

### Homeserver

freedombox.emorrp1.name

### Have you submitted a rageshake?

No

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6876
