### ISSUE TITLE
Change design for "Sign out" and "Deactivate account" in mobile application

### ISSUE THREAD

**Issue by neer17** [vector-im/element-web#19237]
#### What would you like to do?
Remove the "Sign out" and "Deactivate account" labels and put those two buttons with an appropriate background, probably red.

#### Why would you like to do it?
Opened the setting for the first time and it did seem very confusing. It feels confusing because all the other categories have multiple options whereas these two have only one option and the labels and the text of the buttons are the same.  

#### How would you like to achieve it?
Remove the labels and make both the buttons take the entire width of the screen with a red background color in a stack fashion.

**Comment by SimonBrandner** [comment]
I am quite confused... Are you talking about the https://github.com/vector-im/element-android/ or the https://github.com/vector-im/element-ios app?

**Comment by neer17** [comment]
The android app. Adding the image for reference.
![Settings panel in android](https://user-images.githubusercontent.com/33282852/135489361-d0572936-9099-426e-b5e6-27b949d3e0e2.jpeg)

**Comment by SimonBrandner** [comment]
Then please file this at vector-im/element-android

Closing as this belongs somewhere else
