### ISSUE TITLE
Improve CSS of "Message search initialisation failed..." error

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19245]
#### What would you like to do?
https://github.com/matrix-org/matrix-react-sdk/blob/b86d646fa7e17fef83bc19367481f1e28d699525/src/components/views/elements/DesktopBuildsNotice.tsx#L41
added in matrix-org/matrix-react-sdk#6230

looks like:
![image](https://user-images.githubusercontent.com/2803622/135603745-09def815-3cb6-4d4e-803e-ef6987d0e39d.png)

compared to:
![image](https://user-images.githubusercontent.com/2803622/135603786-a3058cb5-4b0f-4493-a7ca-7205db57b342.png)

**Comment by gsouquet** [comment]
Thank you for filing this issue,
Could you confirm that you're experiencing that on Web?

From where I stand we want to display "Use the Element desktop..." message on web. However the other message is still desirable when used from desktop.

This other ticket #18164 is relevant for this work too and would benefit from being tackled at the same time

**Comment by HarHarLinks** [comment]
> Could you confirm that you're experiencing that on Web?

No, this is an issue for desktop, since the error is (should be...) exclusive to desktop, as you say yourself:

> From where I stand we want to display "Use the Element desktop..." message on web. However the other message is still desirable when used from desktop.

Correct. To clarify: I suggest to add similar CSS that centers and pads the error message in the first screenshot on desktop similar to how the message in the second screenshot is on web. Maybe an icon or red coloring etc to indicate it is an error as well.

> This other ticket #18164 is relevant for this work too and would benefit from being tackled at the same time

Sure, that ticket has a very good suggestion, and you can see in it's screenshot another example of missing styling (padding). Both are probably very easy to fix with 2 lines of CSS.

**Comment by ttheshreeyasingh** [comment]
@gsouquet  Can I be assigned this issue? I'm an outreachy applicant.

**Comment by SimonBrandner** [comment]
> @gsouquet Can I be assigned this issue? I'm an outreachy applicant.

A PR already seems to be associated with the issue, sorry
