### ISSUE TITLE
Use Sentry release management for better call stacks

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19243]
### Your use case

https://docs.sentry.io/product/cli/releases/

This would let us upload source maps to Sentry and enhance the stack traces readibility

**Comment by Palid** [comment]
Seems that using https://docs.sentry.io/platforms/javascript/sourcemaps/ would be the easiest way though.

**Comment by gsouquet** [comment]
Things like the `sentry-webpack-plugin` that you mention can be helpful indeed. I don't see that as exclusive from using the release management

However there are many other Sentry features we would miss on by only relying only on source maps, like commit integrations, deployment management, ...

**Comment by gsouquet** [comment]
Fixed as @novocaine brought sourcemaps to Sentry!
