### ISSUE TITLE
element-desktop >= 1.8.4 hanging on tiling window manager

### ISSUE THREAD

**Issue by paboum** [vector-im/element-web#19240]
### Steps to reproduce

1. Run the application normally, converse in a room
2. Switch to another application
3. Receive a message in the room
4. Switch back to element-desktop

### What did you expect?
Reading the new message.

### What happened?
The application hangs. I can see a notification in the tray but not the app window.

The console keeps repeating:
`(element-desktop:3113): libnotify-WARNING **: 20:39:47.843: Failed to connect to proxy`

### Operating system

Gentoo Linux with xmonad

### Application version

1.8.4 from portage or 1.9.0 built from source

### How did you install the app?

see above

### Have you submitted a rageshake?

No

**Comment by paboum** [comment]
Seems related: https://github.com/signalapp/Signal-Desktop/issues/4653

I disabled notifications in Element and it seems to have helped. Not that they ever worked anyway. =x11-libs/libnotify-0.7.9-r1 stable from portage.

**Comment by thulle** [comment]
Similarly, I got around this issue by installing a notification daemon.

**Comment by josteink** [comment]
Using swaywm, I've experienced this issue too on some of my machines... I was never sure what was different about the different environments, but disabling desktop notifications seems to have fixed it for now.

Will have to look into a notification-daemon in the long run, I guess ;)

**Comment by paboum** [comment]
Does not longer occur for me on `1.11.15`.
