### ISSUE TITLE
Editing a markdown message removes all horizontal lines

### ISSUE THREAD

**Issue by puenka** [vector-im/element-web#19248]
### Steps to reproduce

1. Write a markdown message with a horizontal line to a recipient like:
```
# Hello!
- - -
This is a message from me to you!
- - -
```
2. Click on `Edit` to modify the message. 

### What did you expect?
I expected to see the original markdown source of the message.
### What happened?
The lines containing horizontal lines disappeared. In the example above, the edit text field shows
```
# Hello!
This is a message from me to you!
```

### Operating system

Ubuntu 20.04

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by aaronraimist** [comment]
@SimonBrandner I doubt this is an upstream issue. The fix should be something similar to https://github.com/matrix-org/matrix-react-sdk/pull/3030/files.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7543
