### ISSUE TITLE
"Verify them in your User Profile" opens empty page

### ISSUE THREAD

**Issue by blizzard4591** [vector-im/element-web#19253]
### Steps to reproduce

1. Open settings, look at "Where you're logged in".
2. Click on the link reading "Verify them in your User Profile" to e.g. grant a new session opened on another device.
3. You land on an empty page, not showing anything.

### What did you expect?
I expected to see a list of sessions and be able to mark them as trusted/share keys with that sessions.

### What happened?
The Settings dialog disappears, showing the main app with the entire right side blank.
Restarts, Re-Login and retries did not help.

I then logged into Element-Web, used a recovery key to add the web session as trusted and encountered the same issue there (page also empty).

### Operating system

Windows 10

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

janaberger.de

### Have you submitted a rageshake?

Yes

**Comment by blizzard4591** [comment]
I can still reproduce the issue, I made a screenshot of what it looks like _after_ clicking the "Verify them in your User Profile" link
![element-broken](https://user-images.githubusercontent.com/130480/136568405-3aeab726-8dd8-40f2-9284-394cc98d3dad.jpg)
:
As you can see, the entire right side is plain empty. There is no panel, at least nothing I can see.

**Comment by novocaine** [comment]
Chromium tends to show CORS errors when the underlying issue is something else - are there are other lines in the line preceding or following the CORS error?

**Comment by novocaine** [comment]
@yellowchris In that case, you might be able see the browser issuing a failed OPTIONS request in the network tab of dev tools leading to the CORS error - are you able to share those? Maybe we can examine the headers.

Also, can I ask what home server you are using and which version?
