### ISSUE TITLE
Unable to change roles or upgrade room version despite being admin

### ISSUE THREAD

**Issue by N1N74** [vector-im/element-web#19257]
##### Where are you starting? What can you see?
I have a room create since before spaces feature which was added to space since it released in beta while it is in version 5 . I am the admin of the room (and space) and have highest power level in both the room and space settings, yet am unable to mute or upgrade room. I've been possibly locked out of more actions that I haven't tested. Below are the errors I am getting, last one for upgrading room:

![image](https://user-images.githubusercontent.com/39383296/135722147-0e1ad2cb-9b0c-42a3-96be-9490e8c43cec.png)

![image](https://user-images.githubusercontent.com/39383296/135722160-fd793246-1535-4504-8a6f-4bb9cea71a61.png)

![image](https://user-images.githubusercontent.com/39383296/135722174-370511a8-72de-4610-9030-c3d8e774c5d8.png)

The room, space and all its participants are located on matrix.org using which I have already upgraded other room verion 5s to 9s.

##### What do you click?
Mute user, change power level, "/upgraderoom 9", and the same settings in room settings. I have also tried setting user power level lower in space than in the room to see if the room lets me change power levels and nope. I have also tried removing room from space to make same changes and again, nope.

##### More steps…
I'll have uploaded debug log once this issue goes up that may be of help.

### What did you expect?
To be able to upgrade room level since it exists on matrix.org and I have admin power in both room and corresponding space. To be able to mute or change power levels of users.
### What happened?
Got non specific error messages.

### Operating system

Windows

### Application version

Element version: 1.9.0, Olm version: 3.2.3 and also Element version: 4efa0b215fa4-react-9f26c1ca57e6-js-a7a08fd760e6, Olm version: 3.2.3

### How did you install the app?

app updated from a previous install from element.io and web version of develop.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

Yes

**Comment by t3chguy** [comment]
Needs someone to get the logs from matrix.org to see what's on the other side of the Internal Server Errors

**Comment by t3chguy** [comment]
The room state is corrupted and Synapse is unhappy about power level updates. Upgrading the room version would fix this.
