### ISSUE TITLE
Design Systems: Color normalization

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#19254]
This is a list of components that use colours that are not defined in the [Compound Figma file](https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound). As of the time of writing the list, many components are missing from it. Things that are checked off have been updated to use the same colours as in the designs or there is a PR to do so

+ [ ] Settings 
	+ [ ] Appearence settings
	+ [ ] Help settings
	+ [ ] Security room settings
	+ [ ] Security user settings
+ [ ] Upload bar - appears when uploading a file
+ [ ] User menu - the thing with your username above the room-list (and the context menu which appears when you click it)
+ [ ] Create room dialog
+ [ ] Create space dialog
+ [ ] Room settings dialog bridges - room settings `Bridges` tab, has to be enabled in labs
+ [ ] Widget capabilities dialog - ?
+ [ ] Network dropdown - the context menu in the `Explore rooms` dialog that allows you to select a server
+ [ ] Info tooltip
+ [ ] Redacted messages
+ [ ] Jump to bottom button
+ [ ] Room sublist menu button
+ [ ] Layout swither
+ [ ] Radio button
+ [x] Dialpad
+ [ ] Top unread message bar - ?

**Comment by Palid** [comment]
@janogarcia @daniellekirkwood just as a heads up :)

**Comment by nadonomy** [comment]
Thanks for the effort on this so far. Very excited for our design system led world!

**Comment by turt2live** [comment]
@SimonBrandner is this still on your radar?

**Comment by SimonBrandner** [comment]
Yep, though it's stuck on design input (see https://github.com/matrix-org/matrix-react-sdk/pull/7283)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/25547
