### ISSUE TITLE
Sticker picker is broken (again)

### ISSUE THREAD

**Issue by gnomelibre** [vector-im/element-web#19258]
### Steps to reproduce

I click on the sticker picker icon and it doesn't show anything

![stickers-element_web-1 9 0](https://user-images.githubusercontent.com/11492626/135723728-e3c2c41c-ee58-4f71-be06-a3e71af61cd6.png)

If I reload the page (sometimes necessary to do it several times), the stickers eventually come back.

I did see that a similar problem had occurred in the past (see bug #15842), but unfortunately it is broken again.

### What happened?
The sticker picker doesn't show anything. I'm not the only one concerned, since all the members of my private room have the same problem.

### Operating system

Fedora 34

### Browser information

Firefox 92.0.1

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gnomelibre** [comment]
I forgot to mention it, but it's not a temporary problem, since it's been bothering me for several weeks.

**Comment by gsouquet** [comment]
Before we can investigate further, would you be able to share a rageshake (By typing `/rageshake` in the message composer right after you experience the issue) so that we can investigate the error messages logged in your developer console

**Comment by t3chguy** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/2403652/159480307-f504c9b7-23ad-4cb3-a42f-f5d1eb8df9ec.png)

**Comment by gnomelibre** [comment]
You can close it, it started working again a few weeks after this bug report 🙂
