### ISSUE TITLE
Element-desktop fails with Let's Encrypt root CA

### ISSUE THREAD

**Issue by eravion** [vector-im/element-web#19261]
### Steps to reproduce

Use Element-desktop 1.9.0 that uses Electron 13.5.0 and try to establish a connection with a homeserver that has a Let's Encrypt certificate

### Operating system

MacOS, IOS

### Application version

1.9.0

### How did you install the app?

.

### Homeserver

matrix.ravion.org

### Have you submitted a rageshake?

No

**Comment by schelmo** [comment]
there is a patch release for electron:
https://github.com/electron/electron/pull/31213

**Comment by gsouquet** [comment]
Would you be able to share some logs or more information regarding the connection failure?
It will be difficult to investigate further with the current amount of information

**Comment by eravion** [comment]
> there is a patch release for electron:
> https://github.com/electron/electron/releases/tag/v13.5.1
> [electron/electron#31213](https://github.com/electron/electron/pull/31213)

it look to be this issue.
This patch is/will be added on element apps ?

**Comment by eravion** [comment]
> Would you be able to share some logs or more information regarding the connection failure?
> It will be difficult to investigate further with the current amount of information

In french the message is : 
l'URL du serveur d'accueil ne semble pas être un serveur d'accueil Matrix valide.
more or less in English : this URL is not a valid Matrix server 
Or something like that.

Nothing on server logs.

**Comment by gsouquet** [comment]
Right, when trying to load: 

- matrix.ravion.org
- matrix.ravion.org/_synapse/admin/v1/server_version
- ravion.org/.well-known/matrix/client
- matrix.ravion.org/.well-known/matrix/client

None of those URLs answer. It appears to be an issue with your Synapse setup rather than an element-web issue.
Will close this issue as there are not much else we can do an our side

**Comment by eravion** [comment]
The site was down, sorry for that.
Now it is up.
BTW I have the same issue on element to connect to.

**Comment by gsouquet** [comment]
Same problem arises, none of the URLs that I have tested above work.
I would recommend you go through the install steps again and verify your server side setup

Bonne chance :)

**Comment by schelmo** [comment]
hi @gsouquet 
there is definitly a problem with the X3 switch from letsencrypt.
i have currently no access to the windows computer where it happened with element 1.9 to provide some logs
but it was an SSL error (-1 error code iirc)
removing the last block from the new certificate (like mentioned [here](https://community.letsencrypt.org/t/issues-with-electron-and-expired-root/160991/14)), fixed the problem for me.
in the linked pull request above from electron, and with the 13.5.1 release, the bug should be fixed.
here is also the correspending electron issues: https://github.com/electron/electron/issues/31212

**Comment by eravion** [comment]
Hello,
I have the same issue on IOS Apps Version 1.6.1.
May I ask you to confirm ?

**Comment by gsouquet** [comment]
I will handle the regression on the element-desktop side. However could you open another issue on the iOS bug tracker, https://github.com/vector-im/element-ios
