### ISSUE TITLE
libva error: init failed

### ISSUE THREAD

**Issue by 0xBYTESHIFT** [vector-im/element-web#19262]
### Steps to reproduce

1. Install element-desktop following the instructions from the official site using apt repo
2. Run element-desktop from terminal
3. Get error "libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed"

### What did you expect?
Proper run

### What happened?
Element-desktop runs, but all I can see is the window filled with white

### Operating system

Ubuntu 21.10, gnome 40.4.0, X11

### Application version

Element 1.9.0

### How did you install the app?

https://packages.riot.im/debian/ default main

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by gsouquet** [comment]
It looks like vector-im/element-web#19169 is a duplicate and has quite a few leads on how to mitigate your issue before the next release.
Let me know whether this solved your issue or not

**Comment by novocaine** [comment]
Hrm actually, this looks like an issue with libva. There are many other threads about this error such as https://github.com/intel/libva/issues/375

I don't think we can help - this is a config issue with your system.

**Comment by 0xBYTESHIFT** [comment]
suggested fix from [here](https://github.com/vector-im/element-web/issues/19169#issuecomment-929364555) helped, I installed element-nightly and it works just fine

**Comment by novocaine** [comment]
Interesting! Thanks for letting us know.
