### ISSUE TITLE
URL parts get interpreted as Markdown and break linkification

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#19269]
### Steps to reproduce

In any room, send a URL that contains something looking like markdown. E.g. `https://twitter.com/__apf__/status/1444829700480593920`

### What happened?

It should look like a regular link, https://twitter.com/__apf__/status/1444829700480593920

Instead it will break at the `__apf__` part, which becomes `<strong>apf</strong>` and only https://twitter.com/ becomes a link.

### Have you submitted a rageshake?

No

**Comment by Samir-Rashid** [comment]
Duplicate of #4674

**Comment by afranke** [comment]
Indeed, thanks.
