### ISSUE TITLE
Pagination on space summery API broken

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#19276]
### Steps to reproduce

1. Opened the explore rooms view for a space with a bunch of rooms (e.g. Matrix Community)

### What did you expect?

To scroll down and see more rooms loaded

### What happened?

The little wheel kept spinning and spinning

### Operating system

Debian Bookworm

### Application version

Element Nightly version: 2021100301 Olm version: 3.2.3

### How did you install the app?

Debian repo

### Homeserver

matrix.envs.net

### Have you submitted a rageshake?

Yes

**Comment by SimonBrandner** [comment]
Can repro on staging.element.io

**Comment by HarHarLinks** [comment]
can also repro on arch aur/nightly-bin and develop.element.io in chromium
