### ISSUE TITLE
bad user experience with quitting desktop app

### ISSUE THREAD

**Issue by mcandre** [vector-im/element-web#19286]
### Steps to reproduce

1. Launch Element desktop app.
2. Press Ctrl+Q to quit.

#### What did you expect?

Ctrl+Q should directly quit.

#### What happened instead?

* An annoying confirmation prompt appears.
* Confirming the prompt does nothing. The app remains running.

My personal preference is to ditch termination confirmation prompts. I've always found these to be unnecessary blocks of code to maintain.

If we absolutely must keep a confirmation prompt, then I want an option to skip the prompt. And I would want this option to persist across my Element user account onto all my devices. So that I don't have to manually reapply this setting when using a different device.

### Operating system

Windows

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

https://element.io/

### Will you send logs?

No

**Comment by t3chguy** [comment]
You can disable the prompt in Settings.

**Comment by gsouquet** [comment]
Closing as there is already a way to disable that prompt when quitting Element desktop

**Comment by MartinDelille** [comment]
I can't find the setting to disable this prompt in the latest version (1.10.10) on Macos

**Comment by t3chguy** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/2403652/164425482-a6fc0afb-c5ba-471d-b9cc-8e76d4f471d1.png">

**Comment by MartinDelille** [comment]
Ok I missed that sorry!
