### ISSUE TITLE
Emoji reactions are broken in multiple ways

### ISSUE THREAD

**Issue by graue70** [vector-im/element-web#19295]
### Steps to reproduce

I wrote multiple messages in a room. Five people (including me) reacted to them with three different emojis. The outcome looks like this in element-desktop:

![element-emoji-reactions](https://user-images.githubusercontent.com/23035329/136059679-d00a304f-4e21-404f-a2e3-cc808e2d6f39.png)

#### What did you expect?

1. I expect all emojis of the same kind (e.g. `thumbs up`) to be combined into one group for every message.
2. I expect at most one occurrence of one kind of emoji (e.g. `thumbs up`) for one person and one message.
3. I expect to be able to remove my own reaction by clicking on it.

#### What happened instead?

1. On the first visible message `Fr, 29.10.` (among others), there are three `thumbs up` emojis in one group and then two `thumbs up` emojis in another group.
2. On the first visible message `Fr, 29.10.` (among others), there are two `thumbs up` emojis from the same person. (You can't see this in the screenshot.) One of them is part of the first group of three `thumbs up` emojis. The other is part of the second of group of `thumbs up` emojis.
3. If I click on the `thumbs down` emoji on the last message `Sa, 27.11`, nothing happens.

#### Further information

Looking at the original event source for the first message `Fr, 29.10.`, part of it looks like this (note that the `thumbs up` emojis are not combined):

```
"unsigned": {
    "age": 432219634,
    "m.relations": {
      "m.annotation": {
        "chunk": [
          {
            "type": "m.reaction",
            "key": "👍",
            "count": 3
          },
          {
            "type": "m.reaction",
            "key": "👍️",
            "count": 2
          },
          {
            "type": "m.reaction",
            "key": "👎️",
            "count": 1
          }
        ]
      }
    }
  },
```

For the last message `Sa, 27.11.`, it looks like this (note that my `thumbs down` emoji isn't there):

```
"unsigned": {
    "age": 432175238,
    "m.relations": {
      "m.annotation": {
        "chunk": [
          {
            "type": "m.reaction",
            "key": "👍️",
            "count": 3
          },
          {
            "type": "m.reaction",
            "key": "👎",
            "count": 2
          }
        ]
      }
    }
  },
```

### Operating system

Ubuntu 18.04.6

### Application version

Element version: 1.8.4 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
So the two thumbs up above are actually different, even though with most fonts they render identically.
The former is `\ud83d\udc4d` whereas the latter is `\ud83d\udc4d\ufe0f` - as per the relevant MSC https://github.com/uhoreg/matrix-doc/blob/aggregations-reactions/proposals/2677-reactions.md - the trailing `\ufe0f` should be sent for emoji reactions.

> When sending emoji reactions, the `key` field should include the colourful variation-16 when applicable.

So whichever client/bot/script/whatever sent the one without `\ufe0f` should be updated to send better formed emoji.

**Comment by graue70** [comment]
Doing further research with your information, I suspect that this is related to https://github.com/vector-im/element-web/issues/13586, https://github.com/vector-im/element-web/issues/13926 and, more precise (since the weird reactions were made on mobile clients), is caused by https://github.com/vector-im/element-ios/issues/3315 and https://github.com/vector-im/element-android/issues/1452.

Those two issues would explain my problems 1 and 2.

That leaves problem 3 unexplained, namely, one of my desktop clients showing reactions of mine that aren't really there and that I can't remove.
