### ISSUE TITLE
Release notes contain duplicate references to fixed issues

### ISSUE THREAD

**Issue by graue70** [vector-im/element-web#19293]
### Your use case

Many of the release notes at https://github.com/vector-im/element-web/releases contain references to fixed issues. They all look like this:

```
Fixes #19030 and #19030.
Fixes #18787 and #18787.
Fixes #18186 and #18186.
Fixes #18984 and #18984.
```

It seems there is a problem in the CI/CD pipeline.

**Comment by aaronraimist** [comment]
Seems to have been fixed by https://github.com/matrix-org/allchange/pull/29
