### ISSUE TITLE
Emoji autocomplete sorting is not temporally consistent after full shortcode match

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#19302]
Emoji autocomplete sorting is not temporally consistent after full match.

## Steps to reproduce

 1. Type out one of the problem emoji listed below except for the last colon `:grinning`
 1. Notice how the autocomplete is sorted as expected
 1. Type the final ending colon `:grinning:`
 1. Notice the first result is no longer the direct match and instead shows some other emoji with similar names

I haven't nailed down the exactly why it occurs but it's something about emoji which have aliases or other emoji names which are shorter/higher priority and sort higher.

`:+1:` | `:grinning:` | `:heart:` 
--- | --- | --- 
![](https://user-images.githubusercontent.com/558581/136102186-47e11b3f-d010-4b46-b51a-da70a7cd8db3.png) | ![](https://user-images.githubusercontent.com/558581/136102273-ed16df4d-85f0-45c3-b0ef-8677190e8df7.png) | ![](https://user-images.githubusercontent.com/558581/136102222-83d97903-ead3-46f7-9c7a-2584a6ccdb88.png)

`:o:` | `:hand:` | `:man:` (`:man:_beard:` broken syntax tracked by https://github.com/vector-im/element-web/issues/19304)
--- | --- | ---
![](https://user-images.githubusercontent.com/558581/136102153-9f220b1c-1281-4821-a1ba-c1ff26b104dd.png) | ![chrome_2021-10-05_16-07-32](https://user-images.githubusercontent.com/558581/136102874-b7bdfeab-5d1b-4917-bb68-dd9328cc53f1.png) | ![](https://user-images.githubusercontent.com/558581/136103785-f69fa8f5-df84-4a87-81ce-bef952961bea.png)

![](https://user-images.githubusercontent.com/558581/136105497-034a1125-1730-4e1a-92f0-7f9af5fff110.gif)

## Expected

The emoji autocomplete sort is the same before and after typing the final ending colon `:`. And shows the direct match as the first result.

## Other notes

The mismatch does not happen with `:sweat:`, `:monkey:`, `:boat:`, `:mailbox:`, `:cop:`, `:bow:`, `:kiss:`, `:golf:` which seem like similar viable candidates but the sorting does change after you add the final end colon `:`.

Given you have to select the emoji in the emoji autocomplete, https://github.com/vector-im/element-web/issues/7256, this bug makes it even harder to convert the emoji shortcode to Unicode emoji.

---

 - emoji syntax

**Comment by ShadowJonathan** [comment]
I think that another of my issues is either referencing or has this be a dup of it, but I think that issue was already closed on triage.

**Comment by HarHarLinks** [comment]
this is really annoying

https://user-images.githubusercontent.com/2803622/144526126-fa180eca-4056-4c79-977f-3cb37b98d165.mp4

the demonstrated case has been worsened since now the popup selector thingy only appears after typing the second (third if counting the colon) character, so it's impossible to work around to get the correct one.

**Comment by commonlawfeature** [comment]
I put together a PR that I believe resolves this issue. Would appreciate any thoughts or feedback or validation that people's issues are resolved by that PR.
