### ISSUE TITLE
Log in after registering shouldn't be necessary

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#19305]
Log in after registering shouldn't be necessary.

## What happened?

Going through the registration flow, after I enter my details to create a new account and click the validation link from my email, I am greeted with a "You can now close this window or log in to your new account." message. It seems like we could easily just sign in the user without the extra login step. This is just an extra layer of friction for users to finally get into Element and chat on Matrix.

![](https://user-images.githubusercontent.com/558581/136110300-bcb44be0-5b0e-456d-8de6-7aba61fa7e47.png)

## Expected

I am automatically signed in after clicking the validation link from my email.

If there is some constraint where we can only do this in the same Element web instance from where the registration started, we can use a similar solution to what I proposed in https://github.com/vector-im/element-web/issues/16899. This doesn't seem like it's necessary though.

## Other notes

This was originally part of my [initial user experience doc](https://docs.google.com/document/d/1PkUlVyZFM1stDdXbrJXuHPnQ-1S1Dh5KiDaGlYhiTAU/edit#heading=h.qwqn9eaw4dq4) where I tracked pain and friction points from first using Element.

And also mentioned at https://matrix.to/#/!habtTMRwfSmIsKRFni:lant.uk/$iNNwCX-RTHkJGzd7PJ9fZ8vU8zGOj7GzoK7M8JOLBxc?via=matrix.org&via=vector.modular.im&via=bpulse.org (cc @BillCarsonFr)

> BTW why do i have to login a second time after registering on web? It's kind of unusual
> All in all you have to type the password 3 times 

## Relevant code

 - [`src/components/structures/auth/Registration.tsx#L597`](https://github.com/matrix-org/matrix-react-sdk/blob/b5e3ba28d91b20d832ef4443462ff82fead07c47/src/components/structures/auth/Registration.tsx#L597)

---

 - sign in after registering

**Comment by eleensmathew** [comment]
Can I work on this? Since I am new can you please guide me?

**Comment by MadLittleMods** [comment]
@eleensmathew This probably isn't a very good first issue but if you're interested in contributing to Element in general, you can checkout the other issues labels `good first issue`, https://github.com/vector-im/element-web/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by gsouquet** [comment]
This is apparently a regression, and was intended to automatically log the user in when possible. 

View [matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$rZMYuTXH86_3vkTh3Au-QG-UWC0CcELIInCg9I9ioFw?via=matrix.org&via=element.io&via=mozilla.org](https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$rZMYuTXH86_3vkTh3Au-QG-UWC0CcELIInCg9I9ioFw?via=matrix.org&via=element.io&via=mozilla.org) for extra context
