### ISSUE TITLE
Validate that the phone number verification field is filled before allowing user to submit

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19316]
### Steps to reproduce

1. Go to settings
2. Under Phone numbers, enter a valid phone number and press "Add"
   -> Can press Continue without entering a Verification code

### Expected result
The Verification code text entry has content before the button is clickable so when the field is empty, the button should be greyed out.

Since the verification code is generated by the identity server, we can't validate the input any further than that there's something in the field.

![Screenshot from 2021-10-07 10-16-25](https://user-images.githubusercontent.com/51663/136356362-3b5f6a57-0299-4020-a1b6-378700d44f97.png)

**Comment by VFermat** [comment]
@kittykat 
Developing a solution for this issue! Is that ok?
