### ISSUE TITLE
Thread sidebar loses draft when a message is received

### ISSUE THREAD

**Issue by shader** [vector-im/element-web#19311]
### Steps to reproduce

1. Enable threading feature in develop.element.io
2. Create a thread with at least one other participant
2. Start typing a message, but don't send it
3. Have another account send a message to the thread while there is a draft message in the thread input box

#### What did you expect?

The draft message and cursor position should be unaffected

#### What happened instead?

The draft message is deleted/cleared, and the cursor is focused on the thread sidebar even if it was in the main room input box at the time.

### Operating system

Windows 11

### Browser information

Firefox 92.0

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
I have tested the steps mentioned in the issue and can not reproduce it.
This has most probably been fixed as part of ongoing development effort around threads

If you still experience it let us know, but in the mean time I will close this ticket
