### ISSUE TITLE
Restricted rooms option gets a bit confused about itself when restricted to not-a-space

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19324]
### Steps to reproduce

1. Create a room
2. Make another room
3. Set the restricted join rules in the second room to allow members from the first
4. Open room settings on the second room

#### What did you expect?

The UI to use generic terminology, or show which room(s) are allowed into the new room.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/136460727-93ff72fd-03f0-44d8-851c-ebc7125bc997.png)

The UI here feels like it's saying the room is public to "anyone in a space", which could theoretically be anyone. This is false: the room is accessible to those who were a member of the upgraded room, which is not a space.

### Will you send logs?

No

**Comment by t3chguy** [comment]
We specifically opted to default to `space` here, but yeah generic terminology would probably be better

**Comment by turt2live** [comment]
"Currently a space has access" is probably okay, but the other sentence is a bit too far on the misleading side I think.
