### ISSUE TITLE
Element desktop app doesnt show me all trusted connections of my other devices

### ISSUE THREAD

**Issue by castenaso** [vector-im/element-web#19328]
### Steps to reproduce

I cant see all my trusted connections on security of element app, under manjaro arm on a raspi pi4 and on a tablet with ubuntu, it doesnt show any trusted connection, page is blank, hence on an android device i can see everything.

### Outcome

I installed, on a pinephone with mobian, matrix-mirage, and after i logged in, i seen this behaviour on my main devices (raspi and tablet). I dont know if two things are related

### Operating system

manjaro arm kde, ubuntu 20.04 x86-64

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by castenaso** [comment]
i dont know how send logs, i tryed twice from element app, but here i dont see logs showed

**Comment by castenaso** [comment]
i click with left click on my name, on top left of application. I choose Privacy and Security, and if i click on Verify on your user profile, i have a blank screen

here a screenshot
![2021-10-09_10-12](https://user-images.githubusercontent.com/91591060/136650175-d3bdaeb8-889a-4a7d-87a5-477fbd35ce58.png)

**Comment by SimonBrandner** [comment]
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/19253

Please shout if I am missing something
