### ISSUE TITLE
Room list scroll jumps are back

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#19322]
### Steps to reproduce

Scroll through the room list, and watch it jump every time the sticky header changes

> ### Steps to reproduce
> This bug depends on your viewport height compared to one of your room list sub-sections.
> 
> 1. Start with a big viewport, and have a room subsection expanded where all of it fits on screen
> 2. Resize to shrink your viewport so that it's just big enough to show the whole room subsection. Then shrink a bit more so that the headings overlap when you scroll down
> 3. Scroll to the bottom of the room list
> 4. Notice the jitter
> 
> I have reproduced this with Chrome on Windows and the Element desktop app on macOS but seems like it would happen in any environment.
> 
> I have also reproduced this with several different room sub-sections and also when switched to a space.
>
> *-- https://github.com/vector-im/element-web/issues/18440*

#### What did you expect?

The scrolling should be smooth and continuous

#### What happened instead?

https://user-images.githubusercontent.com/48614497/136436474-096302cd-f4e5-40b8-80ba-89952835f138.mp4

Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6915

### Operating system

NixOS unstable

### Browser information

Firefox 92.0.1

### URL for webapp

develop.element.io

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
I'm able to reproduce on the latest `develop.element.io`

![](https://user-images.githubusercontent.com/558581/155563178-3fdd2ca6-950c-4488-a27f-9fc895968343.gif)

Same reproduction steps as my original issue:

> ### Steps to reproduce
> This bug depends on your viewport height compared to one of your room list sub-sections.
> 
> 1. Start with a big viewport, and have a room subsection expanded where all of it fits on screen
> 2. Resize to shrink your viewport so that it's just big enough to show the whole room subsection. Then shrink a bit more so that the headings overlap when you scroll down
> 3. Scroll to the bottom of the room list
> 4. Notice the jitter
> 
> I have reproduced this with Chrome on Windows and the Element desktop app on macOS but seems like it would happen in any environment.
> 
> I have also reproduced this with several different room sub-sections and also when switched to a space.
>
> *-- https://github.com/vector-im/element-web/issues/18440*



Past issues:

 - https://github.com/vector-im/element-web/issues/18440
 - https://github.com/vector-im/element-web/issues/19555
 - https://github.com/vector-im/element-web/issues/19848
 - https://github.com/vector-im/element-web/issues/20441
