### ISSUE TITLE
password reset security hints i18n

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19335]
### Steps to reproduce

1. go to develop.element.io which automatically is in my local language
2. click forgot pw
3. enter new pw
4. a bubble with hints to improve pw security pops up

#### What did you expect?
i18n

#### What happened instead?
popups are in english when the rest of element isn't

### Operating system

linux

### Browser information

Vivaldi 4.3.2439.41 (Official Build) snapshot (64-bit) Revision 4b7f03922d16ea1d46dc97082edcfc0a5820acaa OS Linux JavaScript V8 9.4.146.18 User Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.72 Safari/537.36

### URL for webapp

develop.element.io

### Homeserver

private

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
![Screenshot_20211010_080227](https://user-images.githubusercontent.com/25768714/136684543-492ed8d3-fa2c-40ad-9928-d11b9d36f845.png)

Mine works just fine... What leads you to think that there is an issue with Element and not just the translation?
