### ISSUE TITLE
Start chat icon not correctly aligned

### ISSUE THREAD

**Issue by root-io** [vector-im/element-web#19340]
### Steps to reproduce

<img width="141" alt="Screen Shot 2021-10-10 at 14 28 22" src="https://user-images.githubusercontent.com/6101308/136695678-d09177a4-9eb2-4f87-9825-0b341db24a69.png">

#### What did you expect?

The " + " icon to be correctly aligned

#### What happened instead?

The " + " icon is out of the grey bubble

### Operating system

macOS

### Application version

Element version 1.9.0

### How did you install the app?

Homebrew + auto update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Thank you for taking the time to tell us about your issue.

I am going to close this issue as it has been resolved on the develop version of Element and will fixed in the next version of Element and should be available to you soon.

**Comment by root-io** [comment]
@SimonBrandner Awesome thanks ;)
