### ISSUE TITLE
When deleting a session there's no "are you sure?"

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19360]
### Your use case

Raised in a community testing session [October 5, 2021]

"When I delete a session that's currently logged in, I don't get a big scary warning that I'm about to log myself out"

Would suggest an "Are you sure" modal, or some more info when the user is taking this action. 

👀  @kittykat

**Comment by t3chguy** [comment]
This will be a server issue, Element depends on Synapse flagging the action via UIA, but Synapse has had a change where if you recently logged in/performed UIA then any more actions in a short period of time will not require to go via UIA. There's no API to ask the server what auth is needed without attempting the action, so its a Server/Spec issue.
