### ISSUE TITLE
RightPanel behaviour is unnavigable when you view space membership, pinned messages, or anything else that hijacks it

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19365]
### Steps to reproduce

1. Have RightPanel open for something like room members
2. Right-click on a space and view space membership

#### What did you expect?

I'm surprised that the membership list for my current room has been replaced with a membership list for a space, given it looks almost the same as the room membership list, but now refers to completely different context (a space rather than a room).  I'd have expected the MiddlePanel to also change to the space management view, tbh.

Moreover, I expect to be able to navigate back to the room membership list, but there's no back button and i can't.  I hit the close button and then have to reopen the RightPanel again to get back to where i was.

### Operating system

macOS

### Application version

Nightly

### Will you send logs?

No

**Comment by kittykat** [comment]
I'm going to close this issue now as the right panel is on per-room/space now so navigating away from a room and back to the room will show you the last state of the panel for that room on return.
