### ISSUE TITLE
FilePanel no longer paginates.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19387]
### Steps to reproduce

Open the FilePanel in a room with lots of images.  See that it only shows one page's worth of thumbnails, and if you scroll up it doesn't backpaginate at all any more.

### Outcome

The ability to backpaginate on the FilePanel.

### Operating system

macOS

### Application version

Nightly

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I don't think I can repro

**Comment by SimonBrandner** [comment]
Logs could be quite useful here

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
