### ISSUE TITLE
My room list isn't loading

### ISSUE THREAD

**Issue by graingert** [vector-im/element-web#19380]
### Steps to reproduce

screenshots here:
https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$iSBqUDtnLvo2LqQQkxh6bMQuJCye8W3HhZnrjRgstX0?via=matrix.org&via=privacytools.io&via=mozilla.org

![room list not loading](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/QwuiHJDnOzRZqwZGcKFqDkcl)

### Operating system

Ubuntu 20.04.3 LTS

### Browser information

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0

### URL for webapp

https://app.element.io/#/room/#element-web:matrix.org

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
> ah thanks I didn't spot it

No worries!
