### ISSUE TITLE
Unable to add stickers

### ISSUE THREAD

**Issue by gondhijagapathi** [vector-im/element-web#19382]
### Steps to reproduce

1. click on show stickers
2. click on add some now
3. try to add any sticker

#### What did you expect?
Sticker pack gets added
#### What happened instead?
got an error in the web console, no error in UI

scalar-384bfbefc6406a22e76a.bundle.js:1 Unhandled rejection Error: Missing room_id in request    at https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:93370    at l (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:86094)    at T._settlePromiseFromHandler (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:59604)    at T._settlePromise (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:60404)    at T._settlePromise0 (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:61103)    at T._settlePromises (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:62430)From previous event:    at T.j [as _captureStackTrace] (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:30887)    at T._then (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:55190)    at T.then (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:1:53576)    at a.value (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:63:140460)    at a.value (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:63:139814)    at a.value (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:63:139590)    at Object.o (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:46493)    at s (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:44694)    at Object.executeDispatchesInOrder (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:45423)    at p (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:12996)    at d (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:13122)    at Array.forEach (<anonymous>)    at e.exports (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:37:18164)    at Object.processEventQueue (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:14514)    at https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:69:114561    at Object.handleTopLevel [as _handleTopLevel] (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:69:114583)    at d (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:77:32559)    at c.perform (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:23:20596)    at Object.batchedUpdates (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:77:32041)    at Object.batchedUpdates (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:18:35126)    at dispatchEvent (https://scalar.vector.im/scalar-384bfbefc6406a22e76a.bundle.js:77:33343)

### Operating system

macos

### Browser information

chrome 94.0.4606.81

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by acheng-floyd** [comment]
@bink thank you very much. When i compiled element-web using your "fix  branch" of matrix-react-sdk , the "Missing room_id" problem got fixed! Now i can use the sticker picker with matrix-dimension!
![image-20211228184955552](https://raw.githubusercontent.com/acheng-floyd/markdown_pic/master/img/202112281850874.png)
