### ISSUE TITLE
Migrate Room.ts `threads` to be a proper EventTImelineSet instead

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19384]
Currently `Room` model has a `threads` property that is a Set, which isn't ideal for our usecase. We already have a semi-proper implementation of the EventTimelineSet used in a `ThreadList.tsx` component and we'd want to move it to the `Room` model, so that we can properly reuse the same timeline we have already.
Ideally, we'd want to use the `Filter` class so that our threads timeline would be added automatically on room initialization, but that requires proper backend implementation first.

See comment from PR: https://github.com/matrix-org/matrix-react-sdk/pull/6904#discussion_r727272715

**Comment by gsouquet** [comment]
Closing this as we'll keep both an `EventTimelinetSet` AND a `Map` of threads as they both provide value differently
