### ISSUE TITLE
New threads are not properly shown in the Main Timeline (room)

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19395]
### Steps to reproduce

1. Login with two different accounts and join the same room (Alice and Bob)
2. Write a message from any of those account (Bob)
3. Create a thread with the same account (Bob)
4. Expect that on the second account (Alice) you will have the message with a thread

#### What did you expect?
A threaded message, as the Bob account created

#### What happened instead?
The thread was not created

Problems analysis:
1. EventTile.tsx is not properly listening for thread events updated, see: https://github.com/matrix-org/matrix-react-sdk/pull/6929 (this pull request on itself does not fix the problem, as model is broken)
2. `matrix-js-sdk/src/models/thread.ts:77` - the `root` is always overriden when getting a new thread with the first reply event, instead of the actual thread's root.
3. The proper root event (which in this case would be `event.replyEventId`, `matrix-js-sdk/src/models/thread.ts:77`) has not been added to the Thread's timeline, which means that `event.rootEvent` never exists and threads can't render

### Will you send logs?

No

**Comment by gsouquet** [comment]
To test again after matrix-org/matrix-react-sdk#6949 lands

**Comment by gsouquet** [comment]
Fixed as part of matrix-org/matrix-react-sdk#6952
