### ISSUE TITLE
Implement Empty List design for Threads List in Right Panel

### ISSUE THREAD

**Issue by Palid** [vector-im/element-web#19396]
Threads List currently doesn't have any special rendering for when it's empty, we need to implement that.

Follow-up to https://github.com/vector-im/element-web/issues/18957

**Design**

- [Empty state — No threads in room](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2067%3A255125)
- [Empty state — Threads in room but not participating yet](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2067%3A254213)
- [Thread panel empty state details](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2076%3A256634)

---

**Snapshot**

![thread-panel-empty-states](https://user-images.githubusercontent.com/60790/141161363-3920741f-7136-400a-912e-6558c6159f6a.png)

**Comment by gsouquet** [comment]
@janogarcia any updates regarding this task?

**Comment by janogarcia** [comment]
@gsouquet Updated the issue description with the relevant links to Figma. 👍
