### ISSUE TITLE
Disable flushing encrypted store on element desktop

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19392]
I just got a notification that all of my encrypted session data is gone after reaching some low disk space on my system (I was messing around with swap files), I'm majorly concerned why Element Desktop allows it's embedded browser to do this.

Please disable database flushing on low disk space on Element Desktop.

I think that at least until dehydrated devices are available, all avenues to preserve encryption quorum should be upheld. If I only had element open on my desktop, I would've just lost all of my encryption history.

**Comment by dbkr** [comment]
dup of https://github.com/vector-im/element-web/issues/4014
