### ISSUE TITLE
Element fails to send messages in encrypted rooms

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#19406]
![image](https://user-images.githubusercontent.com/5547783/137477425-32247270-8919-4a5f-ae28-fcda1f6376cd.png)

No sign of failing request (or outgoing request at all) in the devtools.
Unencrypted rooms seem to work fine.
Refreshing doesn't fix the issue.

Have sent logs: https://github.com/matrix-org/element-web-rageshakes/issues/6597

Element version: ef470a120730-react-af55ac7b8c9d-js-fc800821f938
Olm version: 3.2.3

**Comment by foss-** [comment]
Seems to work again now. Is there any status page to check when such glitches occur?

**Comment by DMRobertson** [comment]
> Seems to work again now. Is there any status page to check when such glitches occur?

https://status.matrix.org/ , but note that's only for the matrix.org homeserver, and not the others in federation.

**Comment by novocaine** [comment]
@babolivier has this happened to you recently?

**Comment by babolivier** [comment]
Nope. Let's close it for now.
