### ISSUE TITLE
Fix branch matching on CI

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19405]
This project is split across 4 layers (`element-desktop`, `element-web`, `matrix-react-sdk`, `matrix-js-sdk`). Sometimes changes are dependant on each other, meaning that a pull request on the React layer might require an update on the JS SDK. In order to not delay things artificially and wait for stuff to land on `develop`, branch matching has been introduced.

This process is driven by `scripts/fetchdep.sh`

If I open a PR on `element-web` with a base branch called `my-branch-1`.

- The CI should check whether there's a branch called `my-branch-1` on the React layer, if not fall back to using `develop`
- The CI should check whether there's a branch called `my-branch-1` on the JS SDK layer, if not fall back to using `develop`

Cases to take into consideration
- [ ] Works when CI runs on BuildKite
- [ ] Works when CI runs on GitHub Actions
- [ ] Works when the base branch is on a fork

**Comment by SimonBrandner** [comment]
What makes you think this is broken? It worked fine for me the last time

**Comment by SimonBrandner** [comment]
@gsouquet, is this still relevant since it seems to work with GHA and we're looking to get rid of BuildKite, afaik?
