### ISSUE TITLE
A reply to one of my messages appears as a highlight, but another doesn't

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#19408]
![image](https://user-images.githubusercontent.com/5547783/137504673-375106b0-4913-41d3-94b7-9ce429548ced.png)

Element version: ef470a120730-react-f8c516d927ec-js-bbc547fd7f8c
Olm version: 3.2.3

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
