### ISSUE TITLE
jack alsa outputs hanging

### ISSUE THREAD

**Issue by atuctuc** [vector-im/element-web#19439]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Outcome

i experience a problem with the jack alsa audio driver on ubuntu 21.10

the sound works with voip calls, the only problem is, that the alsa-jack-rawjack output-devices in qjackctl don't get removed after calls, 

when i stop element-desktop-nightly, the jack driver blocks audio for 1 minute, until element has stoped.

### Operating system

ubuntu

### Application version

Element Nightly version: 2021101801 Olm version: 3.2.3

### How did you install the app?

https://packages.riot.im/debian/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Would you be able to rageshake as well as sharing the main process logs.
This will be difficult to pinpoint with no more information

**Comment by SimonBrandner** [comment]
@atuctuc, did you rageshake?

**Comment by turt2live** [comment]
Closing due to lack of information. If this is still happening to you, please open a new issue with the requested information.
