### ISSUE TITLE
Message HTML export produces a ~1MB CSS file

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#19441]
### Steps to reproduce

When exporting 1MB of messages from a room through the 'Export chat' button in the sidebar, the resulting export ends up being 40KB of message history, 180KB of images and 884KB of CSS.

```
> ls
css  js  messages.html  room.png  users
> du -hd 1 *
884K	css
4.0K	js
40K	    messages.html
4.0K	room.png
180K	users
```

#### What did you expect?

More messages, less CSS.

#### What happened instead?

I only noticed this when trying to debug #19436, going into the CSS file and being met with a very large file, one that dwarfs the others in my chat export.

Going out on a limb, I'm guessing this may be because the chat export feature simply takes the resulting CSS bundle from Element and simply exports that? I suppose that works and is low maintenance, but is does mean the export format will change occasionally and not deliberately.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021100901, Olm version: 3.2.3

### How did you install the app?

The AUR

### Will you send logs?

No

**Comment by t3chguy** [comment]
```
t3chguy@Michaels-MacBook-Pro ~/D/Element - Chat Export - 08-12-2021 at 16-42-45> du -hd 1 *
 28K	css
4.0K	js
 12K	messages.html
 12K	users

t3chguy@Michaels-MacBook-Pro ~/D/Element - Chat Export - 08-12-2021 at 16-44-12> du -hd 1 *
 28K	css
4.0K	js
 48K	messages.html
4.0K	room.png
 28K	users
```

The above are exported from Firefox
The following is exported from Element Nightly (chromium)

WOW

```
t3chguy@Michaels-MacBook-Pro ~/D/Element Nightly - Chat Export - 08-12-2021 at 16-45-45> du -hd 1 *
1.0M	css
4.0K	js
 48K	messages.html
 12K	room.png
 48K	users
```

**Comment by t3chguy** [comment]
Going to try a naive approach to strip unused classes and minify the CSS to see how smol we can make it

**Comment by t3chguy** [comment]
Naive approach attempt 1 output a stylesheet of 68KB without compression but it seems to over-strip some classes and thus lose some styling.

![image](https://user-images.githubusercontent.com/2403652/145256368-1502de73-7c5f-4f71-9fb0-a6839cf3a066.png)

**Comment by t3chguy** [comment]
Getting a bit closer but still broken

![image](https://user-images.githubusercontent.com/2403652/145259240-2f491a58-1dee-419a-bfe0-93c05bb3002e.png)
![image](https://user-images.githubusercontent.com/2403652/145259263-a59a4b3b-e03e-4b31-9c22-6d0ea4b68294.png)

**Comment by t3chguy** [comment]
Alright, with a functional export we are up to 74KB unminified/uncompressed
![image](https://user-images.githubusercontent.com/2403652/145260155-9a9319fe-cd54-4aec-aa01-dca0d51a2c28.png)

![image](https://user-images.githubusercontent.com/2403652/145260190-c4c0c8e4-dfe7-46bd-98f9-4fce17b1767f.png)
