### ISSUE TITLE
Cannot quit app stuck in infinispinner state

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19444]
### Steps to reproduce

1. Have app stuck in infinispinner state (e.g. #19443)
2. Close app
3. Start app again
4. See app still stuck in infinispinner state

#### What did you expect?
To be able to try logging in again

#### What happened instead?
App still stuck in infispinner state (I killed it from a terminal but most users wouldn't know how to do that).

### Will you send logs?

No

**Comment by t3chguy** [comment]
Logs would be helpful here

**Comment by turt2live** [comment]
Closing due to lack of information. If this is still happening, please reopen the issue with new information or open a new issue altogether.
