### ISSUE TITLE
Sign in stuck on infinispinner

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19443]
### Steps to reproduce

I don't know if these steps will trigger the issues, but I haven't logged into the desktop app in a long time. This is also happening right after an update (app wasn't running during update).

1. In a web session, delete the desktop session (Settings -> Security & Privacy -> Where you’re logged in)
2. Open desktop app
2. See the "you've been logged out, delete old session data" dialogs and confirm all of them.
2. Sign in

#### What did you expect?
Be logged in

#### What happened instead?
Infinispinner on sign in page

From the web app for the desktop session stuck in the infinispinner state:
![Screenshot from 2021-10-19 10-56-56](https://user-images.githubusercontent.com/51663/137888187-7f620189-afab-4d56-a0c5-b1e5df9836cf.png)

Killing the app and starting again let me sign in successfully

### Operating system

Arch Linux

### Application version

element-desktop-1.9.2-2, electron-15.2.0-1

### How did you install the app?

Distro package

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
Can you please rageshake next time this happens?

**Comment by turt2live** [comment]
@kittykat have you seen this recently?

**Comment by kittykat** [comment]
I'm going to close this issue as I haven't experienced it recently
