### ISSUE TITLE
Hide quick actions

### ISSUE THREAD

**Issue by rgpublic** [vector-im/element-web#19454]
### Your use case

In the sidebar of my community there are two ugly huge useless buttons at the bottom of the sidebar:

![image](https://user-images.githubusercontent.com/17726950/137955761-4279e693-11bf-4038-be9e-7b83e1c588cc.png)

I could swear they have only been there recently, but I might be wrong. Anyway, it would be really nice in terms of having a clean UI if there was an option to disable them :-)

**Comment by t3chguy** [comment]
We got rid of Quick Actions
