### ISSUE TITLE
Bulk invite button can go negative if receiving and accepting invites after the dialog was opened

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19466]
### Steps to reproduce

1. Receive 2 invites
2. Open the Security & Privacy tab of settings but don't click the buttons to accept the invites. Note the button says 2 invites.
3. Receive a third invite. Note that the button doesn't change its number.
4. Click accept all 2 invites
5. Wait for it to accept all 3 invites
6. Button now should say -1 invites are pending.

#### What did you expect?

For the button to disappear and not come back with -1.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/138298223-f8c5b9b6-c20b-4eb7-a473-aa49fa9e74d6.png)

### Operating system

Windows 10

### Browser information

Chrome

### URL for webapp

internal - app.element.io equiv

### Homeserver

internal

### Will you send logs?

No

**Comment by renancleyson-dev** [comment]
I would like to work on this issue

**Comment by turt2live** [comment]
Yay! Check out our contributing guidelines and open a PR.

I believe the fix will be in the matrix-react-sdk, but visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org) on Matrix if you run into issues.
