### ISSUE TITLE
Ellipses functionality missing in quite a few places which can completly break the UI

### ISSUE THREAD

**Issue by Whodiduexpect** [vector-im/element-web#19463]
### Steps to reproduce

1. Click "Start Chat" or "Invite to Room" to make the account selection panel show up
2. Have an account in the "Recently Direct Messaged" or "Suggestions" section with a really long name

#### What did you expect?
I expected the name to get truncated with an ellipses, like it does in most other places.

#### What happened instead?
The entire name is displayed, adding a bottom scroll bar as well as completely breaking the alignment, with the profile picture on top, the name and mxid directly below it instead of to the side and in the case of recently direct messaged the time where the user was last messaged way over to the bottom and the right colliding with the next user in the list.

### Will you send logs?

No

**Comment by Whodiduexpect** [comment]
I've noticed the lack of ellipses bug in the following additional places:
- The mention helper user select
![image](https://user-images.githubusercontent.com/53096512/144364048-051bf87d-d1e1-491d-b28d-6942bfd5108d.png)
- Typing notifications (does not mess up the UI, but is ugly and wastes tons of spaces)
- Hovering on reactions and similar, the display name is displayed in full and will go off screen hiding everyone else

**Comment by SimonBrandner** [comment]
I've assigned you to the issue, if you need any help, be sure to visit https://matrix.to/#/#element-dev:matrix.org
