### ISSUE TITLE
I get "unsupported browser" using latest chrome and firefox

### ISSUE THREAD

**Issue by Polve** [vector-im/element-web#19464]
### Steps to reproduce

I download the latest web version and configure my web site to serve it.

I'm using latest chrome (94 at the time of writing) or firefox (93 at the time of writing).

I get the warning "unsupported browser" and I need to press the button to ignore risks and continue.

#### What did you expect?

The element app should start normally without warnings.

#### What happened instead?

A scary message will send away most of users.

### Operating system

linux

### Browser information

Version 94.0.4606.81 (Official Build) (64-bit)

### URL for webapp

1.9.2

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is because browsers disable crypto on http:// sites, you'll need to set up ssl and use https

**Comment by Polve** [comment]
WTH I didn't know that. Thanks for pointing me this
