### ISSUE TITLE
Element desktop fails to build on Apple M1 Macbook Air

### ISSUE THREAD

**Issue by D4v1dH03** [vector-im/element-web#19486]
### Steps to reproduce

1. I am strictly following the build steps on `element-desktop` README file
2. Run `yarn install` - succeeded
3. Run `yarn run build:native --target aarch64-apple-darwin` - Failed.
4. Shows error, build failed with error code 1, cannot continue

#### What did you expect?
I expect the build of native modules will finish successfully
#### What happened instead?
When running the command `yarn run build:native --target aarch64-apple-darwin` it shows the following error 
```
checking build system type... Invalid configuration `arm64-apple-darwin21.1.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21.1.0 failed
1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Operating system

macOS

### Application version

element-dekstop master branch at commit 0af82db

### How did you install the app?

Manually building

### Homeserver

(Not applicable)

### Will you send logs?

No

**Comment by aaronraimist** [comment]
Hmm it works for me. Are you running your terminal in Rosetta?

**Comment by dbkr** [comment]
Now I have a machine I can try this with, I've tried and it works fine for me (although there's a different bug when using node 17: https://github.com/nodejs/node-gyp/issues/2534) - does it work for you now?

**Comment by D4v1dH03** [comment]
OK I will try again when I have time and if it works this issue will be closed.

**Comment by D4v1dH03** [comment]
Unfortunately it still says the very same message as in description. I am now on the latest master at commit `9746517`

**Comment by dbkr** [comment]
Would you be able to upload the whole log? If there is anything there, chance are its buried somewhere in the pages above.

**Comment by D4v1dH03** [comment]
> Would you be able to upload the whole log? If there is anything there, chance are its buried somewhere in the pages above.

I cannot even build it how am I even supposed to upload the log?

:(

**Comment by dbkr** [comment]
The console log from the terminal you're typing in when you're trying to build element (ie. wherever your snippets above came from).

**Comment by D4v1dH03** [comment]
```
 % yarn install
yarn install v1.22.17
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.13s.
% yarn run build:native --target aarch64-apple-darwin
yarn run v1.22.17
warning ../../package.json: No license field
$ yarn run hak --target aarch64-apple-darwin
warning ../../package.json: No license field
$ node scripts/hak/index.js --target aarch64-apple-darwin
hak check: matrix-seshat
hak check: keytar
hak fetch: matrix-seshat
hak fetch: keytar
hak fetchDeps: matrix-seshat
hak fetchDeps: keytar
hak build: matrix-seshat
checking build system type... Invalid configuration `arm64-apple-darwin21.1.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21.1.0 failed
1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by D4v1dH03** [comment]
@dbkr  Found the problem! It is the homebrew `coreutils` that is the culprit! especially the `uname` in that version of `coreutils`
I removed it and then Element built normally
