### ISSUE TITLE
Size videos the same way we size images

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#19498]
#### What would you like to do?

Have videos be sized the same way images are in https://github.com/matrix-org/matrix-react-sdk/pull/7017

#### Why would you like to do it?

To be consistent

### Have you considered any alternatives?

+ Add a separate setting for videos
+ Always make videos the size of smaller images
+ Leave them the way they are

### Additional context

https://github.com/matrix-org/matrix-react-sdk/pull/7017#issuecomment-950389136

**Comment by gaelledel** [comment]
Approved by design in https://github.com/matrix-org/matrix-react-sdk/pull/7017#issuecomment-950389136
