### ISSUE TITLE
Keyboard shortcuts window should fill screen rather than scrolling vertically

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19493]
#### Current state

![image](https://user-images.githubusercontent.com/2803622/138598425-0f8e2540-ae10-4e81-9f89-8ba0bf6569b6.png)

As you see there is about 2/3 of unused space but still the shortcuts list scrolls vertically rather than expand

**Comment by t3chguy** [comment]
This has now been done, by @SimonBrandner
