### ISSUE TITLE
i18n de: "Copy" secret button overflow

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#19511]
### Steps to reproduce

1. Login to any account
2. Switch to German
3. Open the settings "Sicherheit & Datenschutz"
4. Under "Verschlüsselung" click "Zurücksetzen"
5. Click "Fortfahren"
6. The generated secret dialog should open

#### What did you expect?

"In Zwischenablage kopieren" fits into button

#### What happened instead?

"In Zwischenablage kopieren" doesn't fit into button

![Peek 2021-10-25 23-08](https://user-images.githubusercontent.com/6216686/138771165-89ed8a64-420e-4c5f-b40f-6c8f3360f10e.gif)

### Possible solutions

a) increase the button sizes
b) change "In Zwischenablage kopieren" to "Kopieren" (as in other languages)

While most translations are "copy" in German it is "copy to clipboard". This is more precise but requires more space.

![image](https://user-images.githubusercontent.com/6216686/138771643-0065da1a-6134-4b30-b489-9ac04a424490.png)

I can fix it depending on feedback about a) or b).

### Operating system

Ubuntu 20.04.3 LTS

### Browser information

Chromium Version 95.0.4638.54 (Official Build) snap (64-bit)

### URL for webapp

develop

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
My feedback as German native is to definitely do option b) independent of resizing the Button.
My mom can understand "copy" rather than "copy to clipboard" which will confuse her by mentioning clipboard unnecessarily while she doesn't know what it is.

**Comment by aaronraimist** [comment]
@HarHarLinks the translations are all community provided so you are welcome to edit them on https://translate.element.io/ if you would like to
