### ISSUE TITLE
IA1.2: Discovery: Room header menus

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19527]
<img width="429" alt="Screenshot 2021-11-11 at 17 29 44" src="https://user-images.githubusercontent.com/4626865/141342562-4b4c0c48-c68c-470b-8d0b-a8cf1d89d213.png">

The intent of these changes is to provide a consistent way within the room view to access most useful actions. Later, we'll also consider unifying this context menu with the overflow interaction in the room list.

- Part of a larger project to [improve our IA](https://github.com/vector-im/element-meta/issues/56).
- [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=642%3A119525)
- Merging to develop to test there, rapidly iterate for production.

## Tasks
- [x] Update room list context menu in room header to match latest designs.
- [ ] Vary context menu depending on if you're viewing a DM or a room.

**Comment by niquewoodhouse** [comment]
@nadonomy @t3chguy If we're building to learn/experiment I think we should do the following things:

1 - Don't change menus on the room list
2 - Don't change the right panel or the `i` that opens it
3 - Add a bumper context menu to the room header that includes all the room options.  Use pre-existing things (eg right panel) to show things when selected (eg Widgets in below):


https://user-images.githubusercontent.com/1587166/139841337-306ec32d-c1c5-4c55-942a-672bee167190.mp4

I know this might be a bit strange to use but I think this would minimize the amount of work we need to do just to get the idea of the mega menu for testing.

**Comment by t3chguy** [comment]
>  Vary context menu depending on if you're viewing a DM or a room.

this got missed, reopening until it is resolved

**Comment by niquewoodhouse** [comment]
> > Vary context menu depending on if you're viewing a DM or a room.
> 
> this got missed, reopening until it is resolved

New design for DM:
- From header menu: Remove invite, copy link, people
- From room list options list: Remove copy link, invite 


<img width="1440" alt="Menu for DM@2x" src="https://user-images.githubusercontent.com/1587166/145066421-64efc18b-fae6-44bb-9968-166614a4e5d7.png">


Notes:  

We believe a copy link option on a DM could lead to people wondering about the security of their DMs; we don't think people are likely in a DM to want to manage room members; we don't believe people are likely to want to invite people to existing DMs, but rather start new conversations when appropriate.
