### ISSUE TITLE
element-macOS has high CPU usages

### ISSUE THREAD

**Issue by jimmychu0807** [vector-im/element-web#19549]
### Steps to reproduce

I think there are 10 - 20 rooms I don't have the encryption keys to decrypt the messages. And then I realized element is keep using 15% - 25% of my mac CPU.

#### What did you expect?

I expect the app should mostly be quiet and not constantly using up CPU resources.

### Operating system

macOS

### Application version

Element Version 1.9.3

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.parity.io

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Sorry that you are experiencing high CPU usage.
After a quick look at the logs you sent, I can not see anything that would link the fact that rooms are missing encryption keys with that high CPU usage.

Could you maybe share a bit more details on how that manifest? Is this linked to a specific action or does it happen when you are idle?

And if possible, would you be able to share some performance profiles taken using browser devtools so that we can understand better what the root of this issue could be

**Comment by jimmychu0807** [comment]
I record the CPU usage in [a video here](https://screencast-o-matic.com/watch/crXf1PVlk2x). It seems the calls from `rageshake.ts` are never ending. This is running with element macOS App.

I also run Element in the webapp form. Surprisingly it has totally different performance profile, and the `rageshake.ts` calls end after some time. The following is the dev profile screen from the webapp.

![Screenshot 2021-11-04 at 14 55 43](https://user-images.githubusercontent.com/898091/140270806-42d0ad94-b55e-4f77-b13a-eee0e9fa2bc4.png)

**Comment by gsouquet** [comment]
From the video you shared I don't really see anything out of the ordinary

Upon startup, Element might have some crypto sessions and key exchange to perform to ensure that all messages can be sent and received securely
This will depend and how large your account is, whether you've joined large federated rooms like Matrix HQ, or many other factors.

There are exploratory work performed to improve initial sync (aka sync v3) and it should help to mitigate the issue you're experiencing

**Comment by jimmychu0807** [comment]
I see. Just that the webapp is much more usable to me than the native macOS app, and I am happy to stick with the webapp for now.

I will close this now. Feel free to reopen if you think there is followup action needed.

**Comment by brevilo** [comment]
I've also been seeing significant idle CPU load for months now, across various Element and macOS versions. Element usually consumes between 25 - 45% CPU (+ 3% for the helpers) with 30% on average when idling in the background. I would expect less than 5% ideally.

Environment:
- MacBookPro14,3 (2,8 GHz Quad-Core Intel Core i7)
- macOS 12.5
- Element 1.11.0
- Synapse 1.63.1 (private)
- Joined two local rooms (two and four users respectively, one federated in 2nd room)
- Joined two people (DMs, one federated)

Can we reopen this issue and have another look?

**Comment by sam0x17** [comment]
I am also seeing extreme idle CPU usage on macos. Please re-open issue.

**Comment by m-cat** [comment]
Seeing this too. Seems to be related to encryption/decryption. Occurred as soon as I joined some DMs after which there was a big lag before messages appeared. Had to switch to web app.
