### ISSUE TITLE
Reaction images do not show up properly when they use a custom URL as image source

### ISSUE THREAD

**Issue by nikp123** [vector-im/element-web#19559]
### Steps to reproduce

1. Log into a matrix account that access to a Discord bridge bot (aka. custom reaction emojis)
2. Open channel with said reaction images
3. The reaction image does not load

#### What did you expect?
The images loading fine just like in FluffyChat.
![image](https://user-images.githubusercontent.com/4696350/139600992-fdda1185-c281-4bf2-ac33-65ecbd0ae6f3.png)

#### What happened instead?
The MXC url got shown instead
![image](https://user-images.githubusercontent.com/4696350/139599595-1ea5f104-5cda-45c7-9f5b-1cba01502e33.png)

### Operating system

Arch Linux x86_64

### Application version

Element version 1.9.3 from FlatHub Stable (flatpak)

### How did you install the app?

Flatpak

### Homeserver

https://matrix.ex-booking.cpm

### Will you send logs?

Yes

**Comment by nikp123** [comment]
This issue affects not only my Arch system, but also my web browser or any mobile client. I reproduced this issue on iOS 14.7.1, Firefox (Linux and Windows) and Android 10.

**Comment by turt2live** [comment]
This is not a feature of the spec, sorry.
