### ISSUE TITLE
Switching back to Home space with home view open shouldn't open last conversation

### ISSUE THREAD

**Issue by ndarilek** [vector-im/element-web#19554]
To reproduce:

1. From the Home space, open the home view with ctrl-alt-h.
2. Switch to another space.
3. Use ctrl-1 to switch back to the home space.

For me, this opens the last conversation I had active in this space (or rather, in the default area where non-space rooms are.) I'd expect it to return to the home screen.

I haven't tested this, but it seems like it might put me in a situation where messages I'm not ready to read are marked as read, assuming I don't switch out of the conversation quickly enough to not reset the marker.

I'm not sure if this is true for switching to spaces with no open conversation as well, but in general I'd expect switching to a space with no conversation open to remember that state when I switch back.

Thanks!

**Comment by t3chguy** [comment]
This context switching behaviour is as designed, in theory though it shouldn't mark as read until you actually do an action in that room, though not sure how that plays with accessibility technologies

**Comment by SimonBrandner** [comment]
> This context switching behaviour is as designed, in theory though it shouldn't mark as read until you actually do an action in that room, though not sure how that plays with accessibility technologies

I think it would actually make sense to show the home page in the home space and make it act as a room from the perspective of context switching, it feels way more natural than the current behaviour

**Comment by ndarilek** [comment]
Agreed. Admittedly I haven't tested whether or not my read position is 
changed, but I generally like to leave my desktop client on the home 
tab, since at minimum it can get a bit spammy to switch into a room and 
have ARIA content start reading as it arrives. Switching to the Home 
screen/tab seems to clearly signal my intent not to suddenly appear in a 
room, so it's surprising that my intent is overridden in this very 
specific area but not in others.


Thanks.
