### ISSUE TITLE
Unable to decrypt: TimeoutError: Transaction timed out due to inactivity.

### ISSUE THREAD

**Issue by kroeckx** [vector-im/element-web#19563]
### Steps to reproduce

After switching back to X, messages send in the mean time that are encrypted seem to show up as:
```
** Unable to decrypt: TimeoutError: Transaction timed out due to inactivity. **
```

### Outcome

```
** Unable to decrypt: TimeoutError: Transaction timed out due to inactivity. **
```

### Operating system

Debian

### Application version

1.9.3

### How did you install the app?

https://packages.riot.im/debian/

### Will you send logs?

No

**Comment by kroeckx** [comment]
I only see this in a chat with a person, not in an encrypted room.

Restarting element-desktop fixes the problem.

**Comment by gsouquet** [comment]
@kroeckx would you be able to share logs and link them with this issue? This will help the crypto team to investigate why this happens

Either using the `/rageshake` command in chat, or "User Menu > Feedback > debug logs"

**Comment by kroeckx** [comment]
I've send a rageshake.

To reproduce it, I switch to the console, someone sends a message,
after a while I switch to X again.

I assume the other person has some other issue.

**Comment by kroeckx** [comment]
I'm not seeing the issue anymore with 1.9.4 so far.

**Comment by kroeckx** [comment]
I'm seeing it again with 1.9.5
