### ISSUE TITLE
Question/labs.md: what is the config.json flag for always showing hidden events on the timeline?

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#19562]
https://github.com/vector-im/element-web/blob/develop/docs/labs.md doesn't tell what is "Always show hidden events on the timeline" which I would like to enable to mitigate https://github.com/vector-im/element-web/issues/4385 a bit more.

How can the mapping between labs settings and config.json be found in general, is there any other mechanism than the labs.md file?

Could GitHub Discussions be enabled for questions and answers?

**Comment by t3chguy** [comment]
The issue tracker isn't a support forum

https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/settings/Settings.tsx shows all the possible keys for `settingDefaults` - for further queries I suggest visiting the Element Web room on Matrix

> Could GitHub Discussions be enabled for questions and answers?

This was dismissed in the past due to not wanting a third location for information to live

**Comment by Mikaela** [comment]
> The issue tracker isn't a support forum

Thus the request for an actual support forum in form of GitHub discussions :)

> https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/settings/Settings.tsx shows all the possible keys for settingDefaults - for further queries I suggest visiting the Element Web room on Matrix

Thank you, I will try that and possibly come ask on Matrix again. My issue with Matrix is that queries there often go unanswered and overlooked and thus I suggested another forum place, as I don't think instant messenger is necessarily the best place for support, even with instant messenger.

> This was dismissed in the past due to not wanting a third location for information to live

I hope you will reconsider it in the future.
