### ISSUE TITLE
Make files drag and drop file in a room work with threads

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19578]
If a file is dropped over the thread view, upload the file in the thread, otherwise upload it in the room.

Adding @janogarcia to the discussion as we might want to have some visuals to indicate in what context a file will be uploaded

**Comment by daniellekirkwood** [comment]
Removing the Blocked status as we have discussed this issue. This is a nice-to-have for the MVP and so has been put into the [Threads:Post Launch](https://github.com/vector-im/element-meta/issues/61) Epic. 

As we get closer to launching Threads MVP, we will reconsider this decision.

**Comment by HarHarLinks** [comment]
At the same time, this could (imo, should) also add the ability to reply with a file upload

**Comment by t3chguy** [comment]
Replies (non thread) with files is not possible due to the spec's requirement of a fallback which is not possible when sending files.

**Comment by HarHarLinks** [comment]
aren't threads (supposed to?) fall back to replies? what's the difference then?
getting rid of reply fallbacks is a whole other issue

**Comment by HarHarLinks** [comment]
Sorry, what I mean is: in current element with the labs flag I can write into a thread, but turning the labs flag off it will appear as a regular reply. I had assumed that for this same reason you can only post such events into a thread which you can post as a reply.

**Comment by t3chguy** [comment]
> but turning the labs flag off it will appear as a regular reply.

Yup, but if you use an old (pre-Threads) Element that wouldn't happen.
This is just the Element receiver treating threads with the Replies code with the labs flag off

**Comment by HarHarLinks** [comment]
Then with threads merged into spec, clients will be expected to implement them, no fallback? If that is the case, I don't see a reason to not require proper replies and remove reply fallbacks at the same time. Anyway, this is getting off-topic.

Files-as-reply for all.
