### ISSUE TITLE
Release automation: More reliable release script

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19570]
Convert the current bash release script to something (probably typescript) that is less error prone, including:

 * Don't race with github on whether the source tarball is available when we try to download it to compare & sign
 * Fix the fact that we make edits to package.json / yarn.lock then try to merge back to develop / master and inevitably conflict if dependencies have been upgraded on develop.

Should be possible to run in an automated fashion with some confidence that it won't go off the rails.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23538
