### ISSUE TITLE
Unnecessary vertical top padding in thread view

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19580]
### Steps to reproduce

Create a new thread

### Outcome

There's excessive vertical padding at the top of the thread view, causing an unnecessary vertical scroll bar to appear

<img width="428" alt="Screenshot 2021-11-02 at 09 13 38" src="https://user-images.githubusercontent.com/57377/139818686-f2ded083-0045-4383-a283-551e82ce5d13.png">

* scroll up to nothing *

<img width="426" alt="Screenshot 2021-11-02 at 09 13 42" src="https://user-images.githubusercontent.com/57377/139818697-7db55e15-8f8f-4263-ad7a-10d4517e2d3b.png">

### Operating system

os X

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
@t3chguy are you aware of why the timeline adds overscroll? i'm not sure i understand the reasoning behind that
