### ISSUE TITLE
Pasting images into Element Desktop under Wayland does not work 

### ISSUE THREAD

**Issue by Cadair** [vector-im/element-web#19582]
### Steps to reproduce

1. Start element desktop nightly in wayland mode: `element-desktop-nightly --enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Attempt to paste an image into the composer
3. Nothing happens

#### What did you expect?

Image upload dialogue with preview

#### What happened instead?

Nothing

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021110101 Olm version: 3.2.3

### How did you install the app?

`element-desktop-nightly-bin` AUR package

### Will you send logs?

No

**Comment by gsouquet** [comment]
Would you be able to share logs with us so that we can investigate what has gone wrong?

**Comment by Cadair** [comment]
I have sent some logs, don't know if it's getting far enough to hit them or if it's a platform issue or what.

**Comment by novocaine** [comment]
I can see `Failed to get URL preview: M_UNKNOWN: Got error 429` in the logs

**Comment by Cadair** [comment]
It looks like that was being hit on room load and not on pasting the image.

**Comment by Cadair** [comment]
I am not seeing anything happen in the console when I paste.

**Comment by novocaine** [comment]
What is the format of the image? Did you drag/drop or use a keyboard shortcut?

**Comment by Cadair** [comment]
It's a png, my normal workflow is take a screenshot and paste it in using ctrl-v.

Drag and drop also doesn't seem to work with a png, but does with a jpeg. I shall experiment with paste and jpgs.

**Comment by Cadair** [comment]
Oh I take that back, drag and drop does seem to work with a png, but didn't the first time I tried :thinking:

**Comment by Cadair** [comment]
Well, this seems odd.

I can reproduce it with both jpg and png images, and also I seem to be able to reproduce it in Firefox. However, other apps like Nheko work fine and accept a paste.

**Comment by novocaine** [comment]
I'm suspicious this is Wayland flakiness based on similar issues floating around, possibly electron specific

https://forum.manjaro.org/t/copy-paste-problem-works-every-other-time/36957
https://askubuntu.com/questions/1341172/ubuntu-21-04-wayland-copy-paste-intermittently-fails

**Comment by Cadair** [comment]
I never have an issue with this when using Nheko, that works every time, also don't have any general copy/paste issues under wayland (sway).

**Comment by novocaine** [comment]
There are some related notes on EW not working well in other ways with Wayland due to not being on Electron 14 in https://github.com/vector-im/element-web/issues/18943

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-desktop/pull/299 updates to Electron 16 so may very well fix this

**Comment by t3chguy** [comment]
We're on Electron 17 now, and about to upgrade to Electron 18, with not having any update in quite some time to this issue will presume it is fixed due to Electron updates. Do shout if you still see it.
