### ISSUE TITLE
Better error messages where actions fail due to restricted federation

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#19598]
#### What would you like to do?
I'd like to know that my invite failed due to restricted federation.

#### Why would you like to do it?
Because the existing message "You do not have permission to invite people to this room" is not helpful or appropriate.

**Comment by t3chguy** [comment]
The client has no way of knowing that the federation is restricted

**Comment by richvdh** [comment]
> The client has no way of knowing that the federation is restricted

this is a thing that can be fixed, of course!

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/10673
