### ISSUE TITLE
Squash pull requests on merge to make better commit list in develop

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#19591]
#### What would you like to do?
I want to suggest doing squash of pull requests on merge action, to join all PR commits to one with message text from PR title.

#### Why would you like to do it?
This will make commit list in develop branch looks much better, without bunch of "typo fix"-like  commits, and easier to find reasons for concrete changes.

#### How would you like to achieve it?
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by turt2live** [comment]
This should have been done a couple weeks ago.
