### ISSUE TITLE
Message vanishes from timeline

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19603]
### Steps to reproduce

1. In a group chat, reply to a message (in a thread - this may not be a thread-related bug, but I have only been able to trigger it 3 times when I was the first person to reply to a thread)
2. Some time later (maybe 1-3 hours later), the thread view only shows my name
3. Some time later, my reply is no longer shown anywhere, as if it doesn't exist

Also, I cannot send messages from step 2 onwards:

![Screenshot from 2021-11-03 12-36-40](https://user-images.githubusercontent.com/51663/140087759-0b2b47a2-8b5d-462f-bd1b-7cef50a59017.png)

Germain says there are some Sentry logs for this

#### What did you expect?
Message is sent and stays visible.

#### What happened instead?
My message dissapeared and I cannot send messages to that room any more (I can still send messages to other rooms). Note that I can see the message just fine on Android.

### URL for webapp

develop.element.io

### Application version

Element version: cb0f9022f943-react-2a20d9a7df19-js-50332c4999f0 Olm version: 3.2.3 (I first saw the issue one week ago)

### Will you send logs?

Yes

**Comment by augusto-herrmann** [comment]
I'm not sure this is the same problem, probably yes.

We have a channel that is bridged with Discord. When someone edits a message on Discord, the message body disappears from Element web, but the person's name is still visible there. If I click "options", "view source", I can still see the message in the json.

The same edited messages do appear just fine on Element for Android.

Here is the [link to an example](https://matrix.to/#/!eZALqDcQGxYxBmwPAh:matrix.org/$Gwy1KWjPOAE0HX_gLbC4QWJBrg43J5rgaAEKKPjEDAU?via=matrix.org&via=t2bot.io) in a public channel.

**Comment by gsouquet** [comment]
Removing the threads label as it seems to be an issue with redactions rather than threads.
The event that vanished for @kittykat is also a redaction.

**Comment by augusto-herrmann** [comment]
I thought the problem had gone away after the merge of matrix-org/matrix-js-sdk#2011, but recently there has been an update in Element Web and the bug is back again.

[This message](https://matrix.to/#/!eZALqDcQGxYxBmwPAh:matrix.org/$IyUvn50cvr4MzIQFOGBpSxvrI5VI4FQdFlAKCRSlV8U?via=matrix.org&via=t2bot.io) has been edited by the [discord bridge bot](https://github.com/t2bot/matrix-appservice-discord) and is invisible in the Element Web UI. One can still read it by selecting "view source", though.

**Comment by kittykat** [comment]
I had this issue once last week.

**Comment by kittykat** [comment]
I'm going to close this for now as I cannot reproduce it at the moment
