### ISSUE TITLE
Room alias address isn't checked for validity before being shown as added

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19609]
### Steps to reproduce

1. Go to room settings (in the left panel, ⋯ -> Settings)
2. Under Room Addresses -> Published Addresses, add and address that looks like "#someaddress"
3. Add
4. Get pop-up with "Error updating main address"
5. Close dialog
6. See bad alias shown in the list
7. Under "main address" dropdown, see the bad alias listed
8. Select the bad alias under "main address" to get another error dialog

#### What did you expect?
Basic validation check when tabbing out of the field (like on login with password or email) and for the alias to not be shown if it fails to be added.

#### What happened instead?
There is no validation before I click "Add" and the alias shows as added after I get the error dialog. The bad alias is also listed under "main address" as well, and throws another error dialog if I try to select it there

![Screenshot from 2021-11-04 09-00-25](https://user-images.githubusercontent.com/51663/140286442-17462720-724e-4a45-a785-d3c949fa712c.png)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kittykat** [comment]
[Tested Netlify build](https://618bc5fbc9092820af4e14ce--matrix-react-sdk.netlify.app/). Can confirm that bad alias is now no longer added.

For me to consider this issue resolved, I would like the text entry to show an error message of this style on a malformed address:
![Screenshot from 2021-11-12 17-21-37](https://user-images.githubusercontent.com/51663/141508544-4f3f423a-7d32-41d1-8a52-73a70561d42e.png)

**Comment by Palid** [comment]
@kittykat can you have a look on the newest build? I could add some better error handling, but I think taking over matrix-org/matrix-react-sdk#6180 makes more sense

**Comment by kittykat** [comment]
It should check that there is *something* before the `:`, otherwise looks great!

![Screenshot from 2021-11-30 20-53-33](https://user-images.githubusercontent.com/51663/144126508-7e5188a9-6db0-4e1e-ae1e-390e11a9f3cb.png)

**Comment by kittykat** [comment]
@t3chguy I just realised that the UI is super confusing. I think published address shouldn't be a text entry at all, but maybe a drop down? The only valid options as far as I can see (and I may be wrong on this) are local addresses which have been added in the section below.

**Comment by t3chguy** [comment]
@kittykat It has to be a text entry field as there's absolutely no way to enumerate all addresses from all possible servers in the world pointing at this room. Local addresses are just a subset of addresses.

Local addresses are on your server, lets say matrix.org. Imagine you're the only admin in the room but someone adds an `#foobar:element.io` address, if you want to publish it, it won't be a *local* address and as such will not show there.

**Comment by t3chguy** [comment]
The UX being confusing is also entirely out of scope of this issue, its tracked in https://github.com/vector-im/element-web/issues/13077
