### ISSUE TITLE
Thread I participated in disappeared entirely, both from the Threads panel and the timeline

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#19607]
### Steps to reproduce

Unfortunately I don't know how to reproduce.

### Outcome

I participated in a thread in a room today. The room in question was encrypted, if it matters.

After some hours, I decided to check up on it, but I could no longer find the thread in the Threads panel nor any of the messages from that thread in the timeline.

Could be related to #19587.

### Operating system

Arch Linux

### Application version

Element version: 1.9.3 Olm version: 3.2.3

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
@dkasak could you confirm whether you're still experiencing this or not? 
I believe matrix-org/matrix-js-sdk#2011 should have mitigated the problem fairly well

**Comment by dkasak** [comment]
When I tried it yesterday on develop.element.io, it didn't work, but it changed: I could now see the thread but my messages were still missing.

I now repeated the test and it works as expected -- I see both the thread and my messages within.
