### ISSUE TITLE
MemberAvatar in thread summary is not correctly sized

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19623]
<img width="581" alt="Screen Shot 2021-11-04 at 12 21 41" src="https://user-images.githubusercontent.com/769871/140312631-23cfa368-4f4d-46dc-ab53-8a7c45f0ff1b.png">

Looks like it happens only for default avatars which do not use a default profile picture

**Comment by kittykat** [comment]
Also broken from my side:
![Screenshot from 2021-11-04 14-14-35](https://user-images.githubusercontent.com/51663/140332831-de6da320-02e0-4960-8483-478c69ebb404.png)
