### ISSUE TITLE
Notification panel no longer shows E2EE messages

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#19627]
### Steps to reproduce

1. Get pinged in an E2ee room
2. Open notification panel
3. Don't see the message

#### What did you expect?

I expect to see the message that pinged me

#### What happened instead?

I don't see the message.

I know this *used* to work, because of #3715.  But it seems to have broken at some point.

### Operating system

Linux (Debian)

### Application version

Element desktop nightly (2021-11-01)

### How did you install the app?

apt repository

### Homeserver

uhoreg.ca

### Will you send logs?

No

**Comment by t3chguy** [comment]
According to this it never did:

https://github.com/vector-im/element-web/issues/6874

Closing in favour of that
