### ISSUE TITLE
Replies in the parent of thread are missing padding

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#19629]
### Steps to reproduce

1. Send a message
2. Reply to the message
3. Start a thread from the reply

#### What did you expect?

The thread root message (the reply from step 2) should have all its components left-aligned in a similar way to how they are in the main timeline.

#### What happened instead?

The parent message in the thread root is hanging out to the left, unaligned from the rest of the thread.

<img src="https://user-images.githubusercontent.com/279572/140364761-96464911-e9aa-45d0-8824-6127e3ce7e33.png" width="400">

### Operating system

macOS

### Browser information

Firefox 96

### URL for webapp

develop.element.io

### Application version

Element version: ef87da52f4aa-react-9c8e1d32e205-js-195498e9dbf7 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Firefox only issue

**Comment by jryans** [comment]
@gsouquet Hmm, unfortunately this issue still occurs on 8e279116ae34-react-1de9630e44c6-js-ad8a93dde8b4, which I believe includes https://github.com/matrix-org/matrix-react-sdk/pull/7100. Should the issue be reopened?

**Comment by gsouquet** [comment]
My bad, I misread the issue and did not actually correct the right thing.
Thank you for the heads up 🤦

**Comment by jryans** [comment]
> Firefox only issue

Also seems to occur in Chrome as well here, so I think it's likely all browsers.
