### ISSUE TITLE
Poll dialog makes bad suggestions for question/topic

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19631]
### Steps to reproduce

1. Enable polls in labs in settings
2. Start a poll
3. Click on "Question or topic"

#### What did you expect?
No suggestions as this is the first time I'm using polls

#### What happened instead?
Weird suggestions:

![Screenshot from 2021-11-04 16-16-59](https://user-images.githubusercontent.com/51663/140377886-9d177434-4540-4c69-b803-adab461eb71e.png)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by mnaturel** [comment]
Hi @kittykat, can you still reproduce this issue with the current version? If so, could you detail the web browser you are using?

**Comment by kittykat** [comment]
Fixed now!
