### ISSUE TITLE
Vector can get stuck in a state thinking it has an inbound call ringing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1963]
Just had a disaster where my Windows PC sat stuck playing a ringtone, but with no popup saying where the new call was.  Apparently it was also sending `m.call.hangup` to other inbound calls.

**Comment by ara4n** [comment]
this is now no longer quite so disasterous now #1964 is worked around

**Comment by ara4n** [comment]
related to #3572

**Comment by SimonBrandner** [comment]
This seems to be no longer relevant
