### ISSUE TITLE
Implement Thread Summary changes

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#19646]
**Changelog**

- Added: Show the latest commenter name.
- Changed: Defined the behavior for the Tread Summary width. Minimum, fluid range, and maximum.

**Source**

→ [Figma](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1939%3A254160)

**Snapshot**

![thread-summary](https://user-images.githubusercontent.com/60790/140566039-b2973103-60a5-4d2a-b2f9-5d0edc159599.png)

**Comment by gsouquet** [comment]
@janogarcia I can see that you've added the display name of the user next to the avatar.
How do you foresee us dealing with disambuiguiated names?

When two display names are homoglyphs the matrix ID usually gets displayed too to avoid usurpation

<img width="308" alt="Screen Shot 2021-11-08 at 08 48 37" src="https://user-images.githubusercontent.com/769871/140711476-544f8afa-5344-46ae-9910-df14f1c2ac74.png">

**Comment by janogarcia** [comment]
@gsouquet The changes detailed in the [issue description](https://github.com/vector-im/element-web/issues/19646#issue-1046167203) haven't landed yet, it seems the issue was closed before actually merging/implementing those changes.

**Comment by janogarcia** [comment]
@gsouquet Just a quick note that Ryan has already implemented the [behavior for narrow timeline containers](https://github.com/matrix-org/matrix-react-sdk/pull/7838), so you don't need to care about that part. 👍

![Threads – Figma](https://user-images.githubusercontent.com/60790/155320811-74cff80d-f131-4771-8a27-a29c09f4819b.png)

**Comment by t3chguy** [comment]
@janogarcia outstanding questions at https://github.com/vector-im/element-web/issues/19646#issuecomment-962932942

**Comment by janogarcia** [comment]
@t3chguy It's actually one of the frame on the above screenshot, the one titled `Thread summary — Disambiguated Matrix User ID`. 

→ [Figma](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1939%3A254160)
