### ISSUE TITLE
Changes of edited enencrypted messages cannot be shown

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#19651]
### Steps to reproduce

1. Send an unencrypted message to encrypted room (e.g. via curl)
2. Edit that message (e.g. in Element Web)
3. Click to `(edited)` to show edits

#### What did you expect?
List of changes. That works well for encrypted messages. It works properly on Element Android even for unencrypted messages.

#### What happened instead?
![obrazek](https://user-images.githubusercontent.com/15554561/140646641-365ab540-adb1-41a2-b831-264c1ecb8cf0.png)

### Operating system

Windows 10

### Browser information

Firefox 95b3

### URL for webapp

own

### Application version

Element version: 1.9.4-rc.1 Olm version: 3.2.3

### Homeserver

own

### Will you send logs?

Yes

**Comment by aaronraimist** [comment]
You say redact but I think you mean edit.

**Comment by waclaw66** [comment]
You're, redaction means removal in Matrix terminilogy.
> 
> You say redact but I think you mean edit.
