### ISSUE TITLE
Bubbles: Context menu button of deleted message hidden behind avatar

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#19652]
### Steps to reproduce

1. Delete own message.
2. Point mouse cursor to message placeholder.
3. See partially hidden button.

#### What did you expect?
Button shall be located next to avatar same as for normal messages.
#### What happened instead?
![obrazek](https://user-images.githubusercontent.com/15554561/140648163-6f4609d7-b40c-4909-83f8-21006495edb7.png)

### Operating system

Windows 10

### Browser information

Firefox 95b3

### URL for webapp

own

### Application version

Element version: 1.9.4-rc.1 Olm version: 3.2.3

### Homeserver

own

### Will you send logs?

No

**Comment by t3chguy** [comment]
the hover effect is wrong here too
