### ISSUE TITLE
The zip file from Room Export should have a root folder

### ISSUE THREAD

**Issue by Sleuth56** [vector-im/element-web#19653]
#### What would you like to do?

When a room is exported the zip file should have a root folder that all the other folders are in. Currently it makes a huge mess of whatever folder it's extracted in.

#### How would you like to achieve it?

Create a folder in the root of the zip with the name of the room as the folder's name. Then put all the data inside that folder.

**Comment by aaronraimist** [comment]
I can't reproduce this. For me the ZIP file unzips to be a single folder.

**Comment by Sleuth56** [comment]
Certain decompression programs automatically create a root folder. But some don't. The unzip command on linux doesn't. As well as KDE's dolphin.
