### ISSUE TITLE
Role value does not update when switching user viewed

### ISSUE THREAD

**Issue by benthetechguy** [vector-im/element-web#19666]
### Steps to reproduce

1. Go into a room.
2. Click on a user and see their role.
3. Click on another user and see that the role didn't change, even if it's not accurate for that user.
4. Close that menu and click on that second user again, and see that the role is accurate.

https://user-images.githubusercontent.com/29379327/140853719-1f0bd0e8-4ca4-46ce-bc7e-dba9dac17ad9.mp4

#### What did you expect?
I expect the role box to be updated to properly reflect the role of the user I'm viewing.

#### What happened instead?
The value in the role box didn't change from the first one viewed.

### Operating system

Arch Linux, Windows 10

### Application version

Element version: 1.9.3, Olm version: 3.2.3

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/, https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe

### Homeserver

fairydust.space

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I can reproduce
