### ISSUE TITLE
'Copied!' tooltip doesn't go away

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19663]
### Steps to reproduce

1. Find (or post) a code block
2. Click the 'copy' button

#### What did you expect?
Code block copied to clipboard, tooltip appears briefly then goes away

#### What happened instead?
'Copied!' tooltip stays on screen

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This feels like a duplicate but I can't find it

**Comment by aaronraimist** [comment]
I can't reproduce this either.

My issue was closed as a dup of this but was slightly different. For me, the tooltip works correctly on code blocks.

The only issue I can reproduce is with the tooltip when copying the version number in the Help & About section of settings. The "Copy" overlaps the "Copied!" tooltip. The tooltips correctly disappear when the mouse moves.

<img width="286" src="https://user-images.githubusercontent.com/5855073/145864803-44ffa03c-c043-488b-88fc-128487d22ecc.png">

**Comment by t3chguy** [comment]
Closing due to unable to reproduce
