### ISSUE TITLE
When rotating camera is showing more of me than I think (From what I see in the small pip of myself)

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#19671]
### Steps to reproduce

1. Calling between mobile - web
2. rotating to horizontal.

#### What did you expect?
To see all of what my camera is recording.

#### What happened instead?
I can only see a bit of what the others see.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

private

### Application version

Develop branch

### Homeserver

private server

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Is this in 1:1 or in group calls (Jitsi)?

**Comment by chagai95** [comment]
This is reproducible, 1:1 calls so I didn't think I needed to add too much information, tested on WhatsApp and they don't seem to have that issue 🙈

**Comment by SimonBrandner** [comment]
> I can only see a bit of what the others see.

Ok, I am a little confused by what you mean by this, do you mean the video is cut off on the sides or...? Perhaps an image would help

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.

**Comment by chagai95** [comment]
@SimonBrandner I made a video, maybe it's easier to see this in the video:

**Comment by chagai95** [comment]
This is kind of a big privacy issue so I think it'll be good to investigate...

**Comment by SimonBrandner** [comment]
Ah, ok, thanks for making a video! Could you please file that at https://github.com/vector-im/element-android? It's Android that is sending a video but cropping it locally, so it isn't fully shown on the phone

**Comment by chagai95** [comment]
Yep, thanks for answering, 

https://github.com/vector-im/element-android/issues/4570
