### ISSUE TITLE
Citation doesn't work

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#19689]
This seems a regression.  Choosing *citation* (the top option in the ... menu for messages) does nothing any more.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19659 - fixed on develop

**Comment by Biep** [comment]
Element Desktop 1.9.4; olm 3.2.3

**Comment by SimonBrandner** [comment]
The changed didn't get into release

**Comment by SimonBrandner** [comment]
Ah, okay the release is already out... Will ask if we should make a release to fix this but I don't think so. I am going to close this as it is fixed on develop

**Comment by Christsnatcher** [comment]
I'm having exactly the same issue, and consider fixing it quite important, as the "Reply" feature can in no way be considered a proper "substitute" for the disfunctional "Quote".

I'm using the latest Element web build in Google Chrome v95.0.4638.69 (Official Build) (64-bit).
