### ISSUE TITLE
Normalize shortcut formatting for quote expansion control

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#19685]
The shortcut in the tooltip of the quote expansion control should use the same formatting used across the app.

❌ **Incorrect shortcut formatting: Quote expansion control**

![Element](https://user-images.githubusercontent.com/60790/141113226-9df5e569-49a3-41e0-b6e1-a24e3509c043.png)

✅ **Correct shortcut formatting example: Bold formatting in composer**

![Element](https://user-images.githubusercontent.com/60790/141113251-85efcc42-1d1c-45c1-bfa1-00d4c0dc6bcf.png)

**Comment by Sinharitik589** [comment]
@janogarcia can you explain how to get the option as I am unable to find it .It may be a silly quest to ask but I am new to the community.

**Comment by SimonBrandner** [comment]
@Sinharitik589, like this:

https://user-images.githubusercontent.com/25768714/156913478-9fb33fb4-f11b-431e-84f5-65b957a279af.mp4

**Comment by Sinharitik589** [comment]
Can i work on this issue ?

**Comment by SimonBrandner** [comment]
Yes, sure! I've assigned you, if you need any help/have any questions, be sure to visit https://matrix.to/#/#element-dev:matrix.org!
