### ISSUE TITLE
Improve using Threads across multiple rooms & DMs

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19686]
#### What would you like to do?

(Request from [this issue/comment](https://github.com/vector-im/element-web/issues/19660#issuecomment-963968642) to break out into a separate issue.) 

Often when participating in a thread, to compose a reply I'll need to use other rooms. When I view another room, often in the middle of composing a message, my threads panel becomes utterly useless:

<img width="593" alt="Screenshot 2021-11-10 at 12 40 07" src="https://user-images.githubusercontent.com/4626865/141114723-1aa5ecea-6a7f-46f2-b14b-1a26d0399a05.png">

From lived experience in Slack, I just expect the thread I'm viewing to persist. This works well for me as I've deliberately clicked on a thread to mentally switch into it 'modally', and therefore I'm happy to deliberately close it too.

### Persistent panels per room
I would be able to achieve the same goal if Element just remembered which panels I have open per room, dismissing or showing the last known panel when switching. I'd be able to click to different rooms and DMs to see what I want, and easily return to the room to finish composing my reply.

It would be more work for me, but at least the app wouldn't be re-laying out unexpectedly and I'd learn how to 'multi-task' across rooms with individual states pretty quickly.

### Pinning
Suggestions of 'pinning' or 'picture in picture' interactions were discussed. I think these are interesting but dangerous:

- **Low discoverability:** Users wouldn't expect to do this or reach for it. I'm not confident it's an advantage.
- **High friction:** It's labour intensive to need to continually click to view -> participate -> pin -> finish -> unpin.
- **Info Architecture:** The thread would need to be outside of the room to avoid mis-communicating it's 'pinned' for everyone.
- **Tenure:** These interactions work well for longer lived goals (watching a video, DMing). I wonder if pinning multiple threads simultaneously (inspired by Messenger overlays over Facebook?) could vastly promote the utility of threads. My spidey sense is tingling on usability, but could be worth exploring.

Separately, I'd also be happier if the empty threads state wasn't so jarring in the first place.

### Additional context

@janogarcia @daniellekirkwood @gsouquet would be interested in your initial thoughts on the above!

**Comment by daniellekirkwood** [comment]
This will not be included in P0 but I wouldn't interested in exploring it for future releases.

**Comment by gsouquet** [comment]
Technically nothing prevents us from doing what you suggest.
I'd be interested in exploring that a bit more for sure.

The back arrow behaviour from the thread view would probably need to be reworked as it goes back to the thread list of the current room, but it does appear that some thoughts need to happen regarding the right panel navigation holistically anyway
