### ISSUE TITLE
Threads P0 smoke testing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19690]
Run an initial testing session to check that we're on the right track.

#### What we need going into the session
- [x] List of completed and partially completed tasks based on [must haves](https://github.com/vector-im/element-meta/issues/3) for P0
- [x] Pick a time when most of the team can attend (Product, Design and lead developer for the platform must attend)

#### During the session
- Lay out standard paths to follow to achieve tasks (test cases with steps)
- Run through some exploratory test cases (tasks to achieve without steps)
- Collect defects and enhancements which are found, and  make sure to collect accurate reproductions steps with screenshots and screen recordings as needed

#### Outputs from the session
- [x] Product processes and files found issues
- [x] Design reviews any designs to update for findings from session
- [x] Acceptance criteria on issues updated as needed (by design, product or development)

**Comment by daniellekirkwood** [comment]
@kittykat It looks like, as we've run the session and finished our debrief, we can close this issue?
We don't need for the issues found to be closed, just triaged?

**Comment by kittykat** [comment]
Indeed, we can close this 👍
