### ISSUE TITLE
IA1: Build for production

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19707]
Issue to track building [Phase I IA experiments](https://github.com/vector-im/element-meta/issues/56) in chorus. To be expanded with:

- Detailed deliverables based on our [conclusions from testing](https://github.com/vector-im/element-web/issues/19706)
- Hi-fidelity Figma comps to be used as acceptance criteria, to aid testing
__
- [x] https://github.com/vector-im/element-web/issues/20619
- [x] https://github.com/vector-im/element-web/issues/20623

**Comment by kittykat** [comment]
Build phase is complete
