### ISSUE TITLE
Formatting issue in thread panel for long messages

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19710]
When looking at the Thread list panel the root message for bigger messages doesn't look right. See screenshot

![Screenshot 2021-11-11 at 15 02 02](https://user-images.githubusercontent.com/89144281/141341893-f028ca59-5266-49eb-880a-12a6f0b89565.png)

**Comment by gsouquet** [comment]
@janogarcia I vaguely remember that you said you wanted to cap this to 2 lines only?
Could you remind me what the acceptance criteria are for this task?

**Comment by janogarcia** [comment]
@gsouquet The root message text snippet should be formatted as follows:

- Remove any HTML/Markdown formatting.
- Limit its length by setting a hard line clamp of 2 lines and then truncating it, appending an ellipsis `…`, if it exceeds the available space.

A rather similar approach to how the [preview/preheader text](https://duckduckgo.com/?q=email+preview+text&t=h_&iax=images&ia=images) is rendered in email clients.
