### ISSUE TITLE
room conversation exports should name the file after the room being exported

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19724]

**Comment by Sinharitik589** [comment]
It means if the name of room is **hello** the exported chat should be called **hello.txt** or **hello.zip** in case of html or **hello.json**  in case of json? @ara4n

**Comment by Sinharitik589** [comment]
> > It means if the name of room is **hello** the exported chat should be called **hello.txt** or **hello.zip** in case of html or **hello.json**  in case of json? @ara4n  @SimonBrandner  @RiotRobot
> 
> Yes, something like that though some other stuff should probably be included like it is now

can you elaborate please

**Comment by SimonBrandner** [comment]
Currently, the export file can be titled like this `Element - Chat Export - 3-4-2022 at 4-23-12 PM`, it should be instead titled something like this `Element - Here Comes The Name of The Room - Chat Export - 3-4-2022 at 4-23-12 PM`

**Comment by Jumeb** [comment]
hello @andybalaam, I would love to work on this issue as my first outreachy contribution. Please could you assign it to me.

**Comment by Sinharitik589** [comment]
> hello @andybalaam, I would love to work on this issue as my first outreachy contribution. Please could you assign it to me.

Hey ! ,I have an ongoing PR against this issue you may look into other issues.

**Comment by andybalaam** [comment]
@Sinharitik589 are you still working on this? If not I will unassign it.
