### ISSUE TITLE
Join a room by "Internal room ID"

### ISSUE THREAD

**Issue by nim65s** [vector-im/element-web#19722]
#### What would you like to do?

I would like to be able to join a room from its Internal room ID, eg. `!ehXvUhWNASUkSLvAGP:matrix.org`

#### Why would you like to do it?

Because if someone ask me to join a room and provide this ID, I would like to enter in that room.

#### How would you like to achieve it?

From the main interface to join a room: the "Find a room..." text input in the "Explore rooms" menu.

### Have you considered any alternatives?

1. open https://matrix.to, enter !ehXvUhWNASUkSLvAGP:matrix.org, and click on the link
2. type `/join !ehXvUhWNASUkSLvAGP:matrix.org`

Both work, but this doesn't feel very user friendly for a newcomer

**Comment by t3chguy** [comment]
A room ID is not routable, so cannot be used reliably for joining. https://github.com/vector-im/element-web/issues/2925 being the reference issue on that

So a Room ID on its own isn't enough over federation, you also need a list of `via=`s - a Room ID on its own only works when your server is already joined to the room.

**Comment by nim65s** [comment]
Thanks, I had no idea it wasn't routable. 

Looking at https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-join-roomidoralias, I guess this is about the case where all users from the initial homeserver left the room, or where that homeserver itself is no longer available, right ?

Maybe at the GUI level, we could just try to find the room anyway, from the homserver in the link, and see if we find anything ?

I mean when a user see that `No results for "!ehXvUhWNASUkSLvAGP:matrix.org"`, while he is logged into the matrix.org homeserver, and somebody else from that same server just said to him that this room exists, this is a pretty bad experience.

**Comment by t3chguy** [comment]
Nope, the server at the end of the room ID is never used. Only the local server and the ones specified in the ?via= are used. That would be a spec/synapse thing

**Comment by nim65s** [comment]
Ok, this explains why `/join !ehXvUhWNASUkSLvAGP:matrix.org` works from my matrix.org account and not from my accounts on other homeservers. I thought this was a bug between element web & element desktop, and was going to open another issue for that ^^"

**Comment by nim65s** [comment]
Hum… May I ask why this issue is closed ? 

Do you want me to open another one with `!ehXvUhWNASUkSLvAGP:matrix.org?via=matrix.org` as example instead ?

I find it hard to understand that inside the same application, the command line works while the GUI doesn't :/
