### ISSUE TITLE
/rainbow broken in threads

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19721]
### Steps to reproduce

1. Go in a thread
2. Type "/rainbow it's a double rainbow all the way"

(Happens with /shrug, /tableflip, ...)

#### What did you expect?

For the message to appear in the thread

#### What happened instead?

The message appears in the main timeline

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
@gsouquet  the spacing on backslash commands is also broken... 

![Screenshot 2021-11-11 at 15 18 20](https://user-images.githubusercontent.com/89144281/141455839-3e6091ff-1b42-4444-a5ce-b32893734612.png)
