### ISSUE TITLE
Review list of commands to display in the Thread's composer

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19725]
There are items in the /command list that are only applicable to the room and so it does not make sense to have them appear in the Thread.

[Here is a list of commands and the proposal for which to remove from the Threads composer](https://docs.google.com/spreadsheets/d/16BTyouFCqqBYhA1rnDPOvRb7wlJACcmeqaq0td8Mehc/edit?usp=sharing)

**Comment by daniellekirkwood** [comment]
There are items in the command list that are only applicable to the room and so it does not make sense to have them appear in the Thread. 

- [ ] @daniellekirkwood  to create list of commands for and not-for Threads panel

**Comment by daniellekirkwood** [comment]
Assigning to other folks for feedback on the proposal 👍

**Comment by daniellekirkwood** [comment]
The list is now finalised and ready to be implemented, removing the Assignee's to reflect that.

**Comment by daniellekirkwood** [comment]
@gsouquet 

We're discussing the [Android version of this issue](https://github.com/vector-im/element-android/issues/4474)
We needed to provide content for an error if the user tries to use a command that we have removed from the list, is the same thing relevant on web? Do we show an error message if the user tries an invalid command?
