### ISSUE TITLE
[Design] Make metaspaces easier on the eyes with dark mode

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19736]
#### What would you like to do?

Currently, in dark mode, the metaspaces look like this;

![image](https://user-images.githubusercontent.com/22740616/141518962-8910425a-a0dd-4899-8019-84d0fa53209f.png)

I suggest inverting these colours to make them less bright.

**Comment by t3chguy** [comment]
This got done as part of IA1.1

![image](https://user-images.githubusercontent.com/2403652/144575866-0b7ebf68-1f6b-44ce-ab18-a26f462cf009.png)
