### ISSUE TITLE
Use the stable hierarchy endpoint from MSC2946

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#19738]
[MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) has completed FCP and Synapse is implementing the stable endpoint (see matrix-org/synapse#11329). It would be nice for Element Web to implement the following so that the unstable endpoints can be deprecated:

* Start using the stable `/_matrix/client/v1/rooms/{roomID}/hierarchy` endpoint.
* Ensure that the `room_id` is not accessed via the list of `children_state` (this is nested under the room information and should be unnecesary).

This should most likely be implemented to attempt using the stable endpoint before falling back to the unstable endpoint. Please let me know if you have any questions.

**Comment by clokep** [comment]
Thank you! 👍

**Comment by t3chguy** [comment]
Unfortunately older Synapse versions return a bad 404 for this API so we cannot sanely fallback.

```
docker run -it --rm --mount type=volume,src=synapse-data,dst=/data -e SYNAPSE_SERVER_NAME=localhost -e SYNAPSE_REPORT_STATS=no -p 8008:8008 matrixdotorg/synapse:v1.47.1
#
t3chguy@Michaels-MacBook-Pro ~ [7]> curl "http://localhost:8008/_matrix/client/v1/rooms/!iMZEhwCvbfeAYUxAjZ%3At2l.io/hierarchy?suggested_only=false&limit=20" -vvv
*   Trying 127.0.0.1:8008...
* Connected to localhost (127.0.0.1) port 8008 (#0)
> GET /_matrix/client/v1/rooms/!iMZEhwCvbfeAYUxAjZ%3At2l.io/hierarchy?suggested_only=false&limit=20 HTTP/1.1
> Host: localhost:8008
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: Synapse/1.47.1
< Date: Fri, 17 Dec 2021 14:12:38 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 167
< 

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>
* Connection #0 to host localhost left intact
```

This is missing an ACAO header and the `errcode=M_UNRECOGNIZED` JSON error expected.

Due to this the `/v1/` API hit is going to rolled back until Synapses with support for this API have been sufficiently rolled out to prevent this issue from becoming widespread.

**Comment by richvdh** [comment]
for reference, https://github.com/matrix-org/synapse/issues/11600 has been fixed, which should prevent this mess in future, but given that any Synapse that has https://github.com/matrix-org/synapse/issues/11600 will also support `/_matrix/client/v1/rooms/{roomID}/hierarchy`, it doesn't help much in this particular instance.
