### ISSUE TITLE
backup key setup dialogue css broken with i18n

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19739]
### Steps to reproduce

1. use german element
2. set up security key by ignoring it after login but then trying to verify a user

### Outcome

![image](https://user-images.githubusercontent.com/2803622/141598124-feda8795-64d5-4086-b9a0-fa395a3d68c8.png)

1. i18n?!
2. buttons

### Operating system

arch

### Browser information

Vivaldi	4.4.2473.3 (Official Build) snapshot (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Version von Element: 8e58d31db35f-react-365950e36670-js-ad8a93dde8b4 Version von Olm: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/141598236-547227b1-45ef-4570-8f1f-13e43dff89b7.png)

**Comment by aaronraimist** [comment]
Initial post is a duplicate of https://github.com/vector-im/element-web/issues/19511

I'm not sure what the second screenshot is showing, just that some things aren't translated?

**Comment by HarHarLinks** [comment]
Screenshots show parts that aren't translated, both related to verification, hence
> 1. i18n?

**Comment by SimonBrandner** [comment]
Though that probably just means the strings haven't been translated yet... I am going to close this as a duplicate then. If there is another issue with the missing translation that I am missing, please open a new issue for that specifically

**Comment by HarHarLinks** [comment]
This is the existing translation of for the first screenshot
https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=3c0cb3fa4b544103&sort_by=-priority,position

it is either not merged or otherwise buggy.
If there is no other issue with the missing/broken translation, as you say there isn't, why do you close this issue instead of renaming/labeling to "German i18n broken"? The info is already here, why repost it?

**Comment by aaronraimist** [comment]
@HarHarLinks that string was translated 10 days ago and the last time the translations were merged was 12 days ago. It just missed the cut off for 1.9.4 but should be in the next version of Element.
