### ISSUE TITLE
Element contacts Posthog before user has agreed

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#19745]
### Steps to reproduce

1. Sign in to Element Nightly desktop app

#### What did you expect?
Element shouldn't attempt to connect to telemetry until it has been enabled by the user

#### What happened instead
POST request to https://posthog.hss.element.io/decide/?ip=X&_=XXXXXXXXXX is sent before user has made a decision on this dialog: 

<img width="311" src="https://user-images.githubusercontent.com/5855073/141660701-61be1c42-a8f8-42a7-93c9-9f98d03fc1b1.png">

### Operating system

macOS

### Application version

Element Nightly version: 2021111301

### Will you send logs?

No

**Comment by aaronraimist** [comment]
Actually even when you log out it is still contacting Posthog while on the login screen

**Comment by novocaine** [comment]
Needs further investigation, but this appears to be due to the [posthog SDK testing which feature flags are enabled](https://posthog.com/docs/api/post-only-endpoints#decide). It's undesirable, but it's not recording telemetry events.

**Comment by aaronraimist** [comment]
Appears to be just `/decide`
