### ISSUE TITLE
emoji verification button have different height

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19740]
### Steps to reproduce

1. verify somebody by emoji

### Outcome

![image](https://user-images.githubusercontent.com/2803622/141598212-115085d1-e42e-4d79-88b0-1fafbc54d8b3.png)

the same is ok in a german element window: the buttons are below each other instead of next to each other.

maybe matrix-org/matrix-react-sdk#6943 but idk why there are 2 different places for emoji verification to happen anyway.

### Operating system

arch

### Application version

Element Nightly version: 2021111201 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by MohamedSaman** [comment]
<a href="https://emojis.com/emoji/verified-checkmark-eqG6RNJH8G" target="_blank">Emoji by emojis.com</a>
