### ISSUE TITLE
Home space right click "show all rooms" slow to react

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19749]
### Steps to reproduce

1. right click on home space
2. click "show all rooms"

![image](https://user-images.githubusercontent.com/2803622/141679591-38b935a2-5693-4e83-bccf-00f74e7420dd.png)

#### What did you expect?
UI updates instantly showing the setting has been toggled and the room list updates asap

#### What happened instead?
Felt like nothing at first, I have now tried 2 dozen times and it still takes a second.

### Operating system

arch

### Application version

Element Nightly version: 2021111401 Olm version: 3.2.3

### How did you install the app?

aur

### Homeserver

private

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
How many rooms do you have approximately?

**Comment by HarHarLinks** [comment]
~100 including DMs

**Comment by ShadowJonathan** [comment]
> then there should still be instant feedback in the toggle and with a loading spinner

(This could apply to the majority of other element context menus, fwiw)
