### ISSUE TITLE
Failed to change power level in certain channels

### ISSUE THREAD

**Issue by dom96** [vector-im/element-web#19751]
### Steps to reproduce

1. https://app.element.io/#/room/#nim-lang:matrix.org
2. Trying to give a member moderator privileges, done via searching for their nick, clicking their account then using the dropdown.

#### What did you expect?

User gets mod privs

#### What happened instead?

![image](https://user-images.githubusercontent.com/246651/141689702-f41455f0-c729-40ad-9991-cc477d299145.png)

This works in other channels. For some reason in this channel specifically it fails :/

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

app.element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is a server error

`2021-11-14T16:29:58.766Z E Failed to change power level M_BAD_JSON: "@freenode_yglukhov[i]:matrix.org": '0' is not of type 'integer'`

**Comment by Yardanico** [comment]
Is there any workaround or fix for this issue? It's quite troublesome for us as we currently only have one active admin in this channel, and they don't always have time to remove spam. Maybe it's possible to promote admins some other way?

**Comment by PMunch** [comment]
Is the Nim channel the only one affected? Judging by that error it seems like all channels should have the same error..

**Comment by Yardanico** [comment]
@PMunch I doubt all channels have the same exact user joined :)

**Comment by PMunch** [comment]
Oh that's what it meant? To be honest that error message doesn't make much sense, it first shows their username, then complains that '0' is not an integer

**Comment by dom96** [comment]
Just tried again and still can't change power levels in that channel. Anything else that I can do to help repro? I'm not sure this is related to that specific username.

**Comment by t3chguy** [comment]
So that room has a broken power levels event

```
{
  "content": {
    "ban": 50,
    "events": {
      "im.vector.modular.widgets": 50,
      "m.room.avatar": 100,
      "m.room.canonical_alias": 100,
      "m.room.encryption": 100,
      "m.room.history_visibility": 100,
      "m.room.name": 100,
      "m.room.power_levels": 100,
      "m.room.server_acl": 50,
      "m.room.tombstone": 100,
      "m.room.topic": 100
    },
    "events_default": 0,
    "invite": 0,
    "kick": 50,
    "redact": 100,
    "state_default": 100,
    "users": {
      "@appservice-irc:matrix.org": 100,
      "@dom96:matrix.org": 100,
      "@freenode_yglukhov[i]:matrix.org": "0",
      "@uran:matrix.org": 100
    },
    "users_default": 0
  },
  "event_id": "$162405382075982TABhT:matrix.org",
  "origin_server_ts": 1624053820674,
  "room_id": "!EtGqjSRNQoJCbpCJSF:matrix.org",
  "sender": "@dom96:matrix.org",
  "state_key": "",
  "type": "m.room.power_levels",
  "unsigned": {
    "replaces_state": "$162405381975981bMSPl:matrix.org",
    "age": 18455146100
  },
  "user_id": "@dom96:matrix.org",
  "age": 18455146100,
  "replaces_state": "$162405381975981bMSPl:matrix.org"
}
```

`"@freenode_yglukhov[i]:matrix.org": "0",` should be `0` not `"0"`

Given that Synapse is happy to return these, it should also be happy to accept them. I'd suggest this be raised on the Synapse repo

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/12538
