### ISSUE TITLE
#exercism_support:gitter.im# is not accessible at this time.

### ISSUE THREAD

**Issue by akwala** [vector-im/element-web#19753]
### Steps to reproduce

1. In browser: https://gitter.im/exercism/support
2. Click "Chat in Matrix" button at the bottom.
3. This brought me to https://matrix.to/#/#exercism_support:gitter.im#/#exercism_support:gitter.im. 
![Screenshot_20211114_152550](https://user-images.githubusercontent.com/1786/141697901-490a1183-223e-437c-9a7e-e17599adb20d.png)

4. Since I've already installed Element in Linux (Kubuntu 20.04.3), I launched Element and tried to join _#exercism_support:gitter.im#_ (copied the room identifier from the web page above).

#### What did you expect?
Expected to join #exercism_support:gitter.im# in Element.
#### What happened instead?
Error message
![Screenshot_20211114_152909](https://user-images.githubusercontent.com/1786/141697868-b149cbb3-24c2-4241-b1ad-5e7146b620e1.png)

### Operating system

Kubuntu 20.04.3

### Application version

Element version: 1.9.4 Olm version: 3.2.3

### How did you install the app?

Followed instructions at https://element.io/get-started#linux

### Homeserver

matrix,org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The # at the end is invalid, your link shouldn't contain that.

**Comment by akwala** [comment]
> The # at the end is invalid, your link shouldn't contain that. This looks like a gitter bug in generating faulty m.to urls

Thanks. Omitting the trailing '#' from the address fixed it.
