### ISSUE TITLE
Speed up autocomplete matching.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/element-web#1976]
@eternaleye says http://blog.notdot.net/2010/07/Damn-Cool-Algorithms-Levenshtein-Automata might help

**Comment by aviraldg** [comment]
Reminder to self: use https://github.com/universal-automata/liblevenshtein-coffeescript

**Comment by gsouquet** [comment]
Significant improvement have been made on that area and as of today there are no specific performance issue regarding autocomplete.

Given the very broad nature of the issue it would be difficult to know when the target has been reached. If you feel like there are still unadressed problems with automplete I would suggest reopening a new issue with a more tangible target or commenting below what you believe should be addressed
