### ISSUE TITLE
Show which thread is unread (unread marker)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19774]
#### What would you like to do?
highlight somehow which thread is unread

#### Why would you like to do it?
the room has a notification count but there's no message. because it's in a thread. but which one?

#### How would you like to achieve it?
notification badge?

**Comment by daniellekirkwood** [comment]
Thanks for creating this issue! We intend to add badges to the Thread Panel and are currently working on this. 

For now, I'll leave this issue open but once https://github.com/vector-im/element-web/issues/19126 is complete, this issue will also be closed.

**Comment by gsouquet** [comment]
Closing as that's a duplicate of #19126.
