### ISSUE TITLE
Client crash on opening Room (Firefox)

### ISSUE THREAD

**Issue by mpeter50** [vector-im/element-web#19777]
### Steps to reproduce

1. An other room was opened, which was in a nested space.
2. I opened an other space
3. Then opened a room in that space

#### What did you expect?
I expected the room to be opened.

#### What happened instead?
Without delay, the "Something went wrong!" dialog opened.

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Crash in `prefersReducedMotion`

**Comment by SimonBrandner** [comment]
@mpeter50, do you have threads enabled?

**Comment by mpeter50** [comment]
If that is a labs feature, I don't think so. I don't remember enabling it, but I'm unable to check it because the labs menu is missing from the settings

![image](https://user-images.githubusercontent.com/83356418/142633161-fabdb3e3-82bb-4741-a31d-b93e2e7c4c24.png)

**Comment by SimonBrandner** [comment]
Ah, okay, then it seems unrelated to an issue I though it was related to

**Comment by mpeter50** [comment]
Also, a few more details.

Forgot to mention, but after a browser restart I'm again able to log in to my account without using a tab container.
An other one, is that I'm also having an issue where I get logged out every time I restart my browser. For this one I had an open issue, but closed it because I thought the problem has gone away.

**Comment by novocaine** [comment]
Looking at the rageshake, the error is `can't access dead object` at [this line](https://github.com/matrix-org/matrix-react-sdk/blob/78b1f6c0b13efd57031a329a1ac62baba948dad3/src/settings/controllers/ReducedMotionController.ts#L43).

That error is associated with Firefox add-ons - see [here](https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/). 

@mpeter50 - do you have any add-ons installed?

**Comment by mpeter50** [comment]
Yes, I have some.
Reading the Mozilla Blog post you linked, does that mean that Element tried to use something that was deleted by an addon?

They also say that the error message should contain the `chrome://` uri of the addon that caused this, so I checked the rageshake zip that I downloaded, and.. maybe I misunderstand something, but did you not receive the message I included with the error report? In the one where you also ask to include the link of the opened Github issue. ASkibg because in issue.txt the first line is `text = User did not supply any additional text.`
I wasn't able to find the addon's uri there, though, probably I would have needed to check it in the dev tools console when that happened.

For the record, I don't have Selenium IDE, but I have quite a few addons that modify the page:

**Comment by novocaine** [comment]
> Yes, I have some. Reading the Mozilla Blog post you linked, does that mean that Element tried to use something that was deleted by an addon?

The theory is that Element is accessing an object that was somehow left in an invalid state by an add-on. 
 
> They also say that the error message should contain the `chrome://` uri of the addon that caused this, 

I think this is only the case if you are the add-on developer, developing your add-on code.

> so I checked the rageshake zip that I downloaded, and.. maybe I misunderstand something, but did you not receive the message I included with the error report? In the one where you also ask to include the link of the opened Github issue. ASkibg because in issue.txt the first line is `text = User did not supply any additional text.` I wasn't able to find the addon's uri there, though, probably I would have needed to check it in the dev tools console when that happened.

We received the message yes.. the logs give the exact line in our code where the crash occurred, but not any further detail on what add-on might be causing it. 

> 
> For the record, I don't have Selenium IDE, but I have quite a few addons that modify the page:

Well, my suggestion would be to disable the addons and try again; if it stops happening, you can pinpoint the problematic one by selectively re-enabling them.

**Comment by mpeter50** [comment]
Actually the problem went away by restarting the browser, and I haven't experienced it earlier nor since my report.
At this point it seems to me that this is a browser glitch, if you think so too feel free to close the issue.

**Comment by novocaine** [comment]
Okay!
