### ISSUE TITLE
Set permission level required to add/create a room to/in a space

### ISSUE THREAD

**Issue by wm75** [vector-im/element-web#19789]
#### What would you like to do?

For a invite-only space I would like to control who among the space members is able to create new rooms inside that space or can add existing rooms to it, but I couldn't find an option to control this permission.
From a quick experiment it seems that by default this requires at least Moderator level, but I would like to be able to change and customize this like other permissions.

#### Why would you like to do it?
Would like to give space members the opportunity to customize the space for themselves without having to be Moderators or Admins.

#### How would you like to achieve it?
Well, the question is: is this something that is just missing from Element's UI, but could be achieved via the API, or is it something missing at the matrix level?

**Comment by t3chguy** [comment]
This is already there in the RC.

![image](https://user-images.githubusercontent.com/2403652/142241809-34815d31-d07d-440e-8f43-6f192821089a.png)

**Comment by wm75** [comment]
Awesome, thanks for the superfast response :rocket:
