### ISSUE TITLE
Wrong command in `matrix-react-sdk` documentation.

### ISSUE THREAD

**Issue by ankur12-1610** [vector-im/element-web#19785]
#### What would you like to do?

Currently, in [`matrix-react-sdk`](https://github.com/matrix-org/matrix-react-sdk) the command to link yarn is given by: 
`yarn link matrix-js-sdk`.

Here is the image of the same:
![matrix](https://user-images.githubusercontent.com/76884959/142190949-9a92abf1-c93d-44c6-aa97-fc0148e2018e.png)

#### Why would you like to do it?

The correct one should be `yarn link matrix-react-sdk`.

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by SimonBrandner** [comment]
No, I don't it should. You're linking the js-sdk to the react-sdk, therefore this seems correct

**Comment by ankur12-1610** [comment]
> No, I don't think it should. You're linking the js-sdk to the react-sdk, therefore this seems correct

I followed the commands but I came across this error:
![terminal](https://user-images.githubusercontent.com/76884959/142193902-47fb689c-0919-489e-a1a8-f14a7532488e.png)

But when I ran `yarn link matrix-react-sdk` it worked :sweat_smile:

![t2](https://user-images.githubusercontent.com/76884959/142194278-f2e72b34-d0a8-4d06-9660-ca99973ddf45.png)

**Comment by SimonBrandner** [comment]
It seems you haven't installed the js-sdk. I think we should move this to #element-dev:matrix.org...

**Comment by ankur12-1610** [comment]
> It seems you haven't installed the js-sdk. I think we should move this to #element-dev:matrix.org...

So what should I do?

**Comment by SimonBrandner** [comment]
Closing as we fixed the issue in #element-dev:matrix.org

**Comment by ankur12-1610** [comment]
> Closing as we fixed the issue in #element-dev:matrix.org

Yeah, sure!
Thanks for the help :)

**Comment by SimonBrandner** [comment]
> > Closing as we fixed the issue in #element-dev:matrix.org
> 
> Yeah, sure! Thanks for the help :)

np!
