### ISSUE TITLE
Not able to switch video-camera / audio mic / audio speaker.

### ISSUE THREAD

**Issue by nvkrishna77** [vector-im/element-web#19782]
#### What would you like to do?
To be able to switch camera / mic / speaker during a call.

Another way is to automatically change the mic/speaker when the system default mic/speaker changes - a common occurrence when blue-tooth headset gets out of charge.

#### Why would you like to do it?
When we have multiple monitors / speakers / mics it is many times useful to change them.

### Have you considered any alternatives?

o- I see that we can stop the call, change the camera/mic/speaker and restart the call. But that is not convenient.

**Comment by SimonBrandner** [comment]
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate o https://github.com/vector-im/element-web/issues/15595
