### ISSUE TITLE
New DMs have blank room avatars, rather than an avatar with the user you're talking with

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#19786]
### Steps to reproduce

1. Start a DM with a user
2. Notice that the room avatar is a standard "letter" avatar, and *not* the avatar of the user you're talking to. Even after they've joined

#### What did you expect?

The room to have the avatar of the user

#### What happened instead?

The room had a blank avatar

### Operating system

Ubuntu

### Browser information

Chrome Version 95.0.4638.69 (Official Build) (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f212e410-react-3583d99ef26d-js-af523522def0 Olm version: 3.2.3

### Homeserver

jki.re

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I don't think I can repro. Could you please try clearing the cache?

**Comment by xanderio** [comment]
Clearing the cache and reloading fixed this issue for me.

**Comment by shmerl** [comment]
I cleared the cache, but it didn't fix the issue for me. Some of the DM rooms are still missing avatars.

**Comment by sjamaan** [comment]
This also happened for me, after updating to a newer Element version (1.9.4) only one (already open) DM had its avatar reset to just the letter. This avatar had already been loaded before, that's the weird thing. And in the message history I can see the avatar changes. I'm not sure how to clear the cache, but opening the dev tools and pressing Ctrl-R and Ctrl-Shift-R didn't fix the issue.

**Comment by manuke42** [comment]
I have the same problem on Element Desktop and now also on Schildichat (1.9.5-sc2), which did not have this problem before the latest update.

**Comment by SimonBrandner** [comment]
Could you all please try to clear your cache (`Settings` -> `Help about` -> `Clear cache and reload`)? This sounds like a sync bug that should be fixed by that. Does that work for you?

@shmerl, interesting. Could you please try running `/converttoroom` and then `/converttodm`? Maybe Element is just confused. Am I assuming correctly that these DMs have only 2 members?

**Comment by shmerl** [comment]
I tried, it didn't work. But I also have Firefox containers enabled, I need to check how to clean cache for them.

**Comment by shmerl** [comment]
Looks like cookies and cache with containers are somewhat messy: https://github.com/mozilla/multi-account-containers/issues/303

**Comment by shmerl** [comment]
OK, what I did now, I cleared not just cache but sites data in Firefox too. That fixed the issue.

**Comment by sjamaan** [comment]
Clearing cache worked for me

**Comment by SimonBrandner** [comment]
I have opened [a new issue](https://github.com/vector-im/element-web/issues/20064) which hopefully summarizes and simplifies this one

Closing in favour of https://github.com/vector-im/element-web/issues/20064
