### ISSUE TITLE
Thread messages wiggle

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19799]
### Steps to reproduce

1. write in a thread
2. hover messages

#### What did you expect?
no wiggle

#### What happened instead?
wiggle, as seen in #19630 except for all messages including own, verified and unverified others.

### Operating system

arch

### Application version

Element Nightly version: 2021111801 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
confirming: develop.element.io is still wiggly right now

**Comment by gsouquet** [comment]
Just tested, and this has been fixed (most probably as part of matrix-org/matrix-react-sdk#7209)
