### ISSUE TITLE
Switches for Labs flags aren't aligned with labels

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19798]
### Steps to reproduce

Settings -> Labs

#### What did you expect?
Strings and switches are aligned

#### What happened instead?
Switches are lower than the labels

![threads](https://user-images.githubusercontent.com/51663/142405939-8827bf2c-389d-455b-8603-b46b44a1e2c1.png)

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f212e410-react-e549438e2af0-js-af523522def0 ; Olm version: 3.2.3

### Will you send logs?

No

**Comment by jryans** [comment]
We may also want some kind of hover style on the entire row, so you can clearly tell which label and switch are connected as you move around.

**Comment by SimonBrandner** [comment]
> We may also want some kind of hover style on the entire row, so you can clearly tell which label and switch are connected as you move around.

I think it might be better to change the order - have the switch before the text

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by ankur12-1610** [comment]
> > We may also want some kind of hover style on the entire row, so you can clearly tell which label and switch are connected as you move around.
> 
> I think it might be better to change the order - have the switch before the text

Does it means, switches will be on left side and text on right?

**Comment by SimonBrandner** [comment]
> > > We may also want some kind of hover style on the entire row, so you can clearly tell which label and switch are connected as you move around.
> > 
> > 
> > I think it might be better to change the order - have the switch before the text
> 
> Does it means, switches will be on left side and text on right?

Depends on what the design team decides, it was just a suggestion

**Comment by ankur12-1610** [comment]
> > > > We may also want some kind of hover style on the entire row, so you can clearly tell which label and switch are connected as you move around.
> > > 
> > > 
> > > I think it might be better to change the order - have the switch before the text
> > 
> > 
> > Does it means, switches will be on left side and text on right?
> 
> Depends on what the design team decides, it was just a suggestion

I'm facing an issue, I did find a scss file associated with it - `matrix-react-sdk/res/css/views/dialogs/_SpaceSettingsDialog.scss`.

Doubts- 
- Should I create a different class for it or should change it in the existing one?
-  The above mentioned file is correct or not? :sweat_smile:

**Comment by t3chguy** [comment]
`matrix-react-sdk/res/css/views/dialogs/_SpaceSettingsDialog.scss` is the wrong file. The Space Settings Dialog has 0 labs flags inside it. The file you want is called `_LabsUserSettingsTab.scss`.
