### ISSUE TITLE
Switching to the threaded tab in a room caused a "Something went wrong"

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#19797]
### Steps to reproduce

1. Open a (encrypted room)
2. Click the threads tab
3. Crash!

#### What did you expect?

That I could see my threads

#### What happened instead?

That I see a crash

### Operating system

Ubuntu 20.04

### Application version

Element Nightly version: 1.9.3
Olm version: 3.2.3

### Homeserver

half-shot.uk

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Maybe a duplicate of https://github.com/vector-im/element-web/issues/19777?

**Comment by Half-Shot** [comment]
Only thing to add is that the client was fine until I opened the thread view. I can actually say that updating to 1.9.4 made this hard to repro, but I've not tested all rooms yet

**Comment by gsouquet** [comment]
@Half-Shot Can you confirm whether you still experience the issue or not? I believe this has now been fixed

**Comment by gsouquet** [comment]
Going to close this as I believe this has been fixed. Feel free to re-open the issue if you still experience this somehow
