### ISSUE TITLE
When a message is deleted, the message action buttons get shifted to under the avatar for the message

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19801]
### Steps to reproduce

Delete message, look at timeline

#### What did you expect?
The buttons are still in the correct place

#### What happened instead?
Button is hidden by avatar and difficult to click

![Screenshot from 2021-11-11 15-42-45](https://user-images.githubusercontent.com/51663/142425398-9077ae05-57d7-424c-95d6-132b744a8d6d.png)

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f21-react-e549438e2af0-js-af523522def0 ; Olm version: 3.2.3

### Will you send logs?

No

**Comment by waclaw66** [comment]
Duplicate to https://github.com/vector-im/element-web/issues/19652
