### ISSUE TITLE
Filtering for my issues in threads is broken

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19809]
### Steps to reproduce

1. Go to Thread side panel (view all threads)
2. Change filter top-right to view only your threads

#### What did you expect?
To see all threads I'm participating in

#### What happened instead?
I can only see threads which I started

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f212e410-react-256c468c15a3-js-af523522def0 Olm version: 3.2.3

### Will you send logs?

No

**Comment by gsouquet** [comment]
Should a reaction be counted as a participating in a thread?

**Comment by clokep** [comment]
See matrix-org/synapse#11399

**Comment by janogarcia** [comment]
@gsouquet As discussed in the [duplicate issue](https://github.com/vector-im/element-web/issues/19846) (now closed), the following interactions should be considered high signal and thus be part of the matching criteria for the "My threads" filter:

- Starting a thread
- Replying to a thread

Ideally we'd also consider mentions, but as you already pointed out that's not going to work at all for encrypted rooms, so we have dropped that requirement.

As for reactions, we consider those low signal/engagement, so those should be excluded. A proper follow/unfollow mechanism, planned for a future release, would allow users to selectively follow threads even if they haven't actively participated in them. 

/cc @daniellekirkwood
