### ISSUE TITLE
Attachments in threads are not aligned same as messages

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19808]
### Steps to reproduce

1. In a thread, attach a file

#### What did you expect?
All content is aligned the same

#### What happened instead?

![Screenshot from 2021-11-18 17-24-16](https://user-images.githubusercontent.com/51663/142474374-2a1bfb03-2448-4a89-80ff-78dabcd53146.png)

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f21-react-e549438e2af0-js-af523522def0 ; Olm version: 3.2.3

### Will you send logs?

No

**Comment by gsouquet** [comment]
Just tested, and this has been fixed (most probably as part of matrix-org/matrix-react-sdk#7209)
