### ISSUE TITLE
Read receipts show room members twice

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19811]
### Steps to reproduce

1. In a new room, invited people by email, then some of them joined, then I posted a message.
2. When other room members saw the message, I saw two copies of read receipts for both of the other two people in the room

#### What did you expect?
Can see the RR only once per user

#### What happened instead?
Can see two RR for each user
![Screenshot from 2021-11-18 20-15-26](https://user-images.githubusercontent.com/51663/142490865-c0c5d0b7-cfa8-44ee-a1e3-a0c24e209e25.png)

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f21-react-256c468c15a3-js-af523522def0 Olm version: 3.2.3

### Will you send logs?

No

**Comment by turt2live** [comment]
Logs for this issue would be great if possible, as that is a very worrying symptom.

**Comment by t3chguy** [comment]
Closing due to lack of logs and other reports, please shout if you see it again
