### ISSUE TITLE
matrix.to deeplinks don't open the Element Desktop app

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#19819]
### Steps to reproduce

Copy a link to a room through the right click context menu

Open the link in your browser

#### What did you expect?

For the link to open in Element Desktop

#### What happened instead?

It opens in the browser

### Operating system

OS X

### Application version

NIghtly

### How did you install the app?

Element Nightly version: 2021111701 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
There's an upstream issue for this in matrix.to - https://github.com/matrix-org/matrix.to/issues/230#issuecomment-974485710

But given this affects Element Web specifically, I think the EW team should take care of it, so logging it here

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17446
