### ISSUE TITLE
"Go to newest" button doesn't work

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19813]
### Steps to reproduce

1. Click a link to a message in element-web
2. See room and message load, with message highlighted
3. Press the "go to newest" button

#### What did you expect?
To jump to the most recent messages in the timeline

#### What happened instead?
Nothing. If I scroll up and down the page a bit, then the button starts working again

### Browser information

Chromium 95.0.4638.69 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2e8f212e410-react-28d7a51bb9d7-js-763e25e0319c Olm version: 3.2.3

### Will you send logs?

No

**Comment by ShadowJonathan** [comment]
This is also sometimes the case when clicking message links twice, see #20097 for notes about timelines still being "loaded"

**Comment by aaronraimist** [comment]
Regressed in https://github.com/matrix-org/matrix-react-sdk/pull/7003
