### ISSUE TITLE
Stickers don't go into threads

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19825]
### Steps to reproduce

1. start thread
2. try sending sticker

#### What did you expect?
threaded sticker

#### What happened instead?
timeline sticker

### Operating system

arch

### Application version

Element Nightly version: 2021112001 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by gsouquet** [comment]
Blocked by https://github.com/matrix-org/matrix-react-sdk/pull/7157 which allows to send a `threadId` for sticker events
