### ISSUE TITLE
Image thumbnail is huge when images are tall

### ISSUE THREAD

**Issue by zkat** [vector-im/element-web#19827]
### Steps to reproduce

1. upload a screenshot from a phone into a channel
2. look at the image on Element Desktop

#### What did you expect?

A reasonable size.

#### What happened instead?

First image is from a vertically-large image. The second image below that is what I would expect the size to be like based on by settings.

<img width="1502" alt="Screen Shot 2021-11-20 at 12 38 19" src="https://user-images.githubusercontent.com/17535/142740313-7580f610-360d-46e1-a9da-ec79a17ef1ec.png">

### Operating system

macOS

### Application version

Nightly as of 2021-11-20

### How did you install the app?

downloaded from site

### Homeserver

zkat.tech

### Will you send logs?

No

**Comment by ShadowJonathan** [comment]
I have the same issue on `Element version: b2e8f212e410-react-7f6f98443865-js-b2d83c1f80b5
Olm version: 3.2.3` FWIW

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19788#issue-1056328942

**Comment by zkat** [comment]
closing the duplicate, then :)
