### ISSUE TITLE
Pasting into threads composer autoselects the main composer

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19826]
### Steps to reproduce

1. copy some text
2. open thread
3. paste into thread composer

#### What did you expect?
text pasted in thread composer, cursor is in thread composer

#### What happened instead?
text pasted in thread composer, cursor is in main composer

### Operating system

arch

### Application version

Element Nightly version: 2021112001 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
seems like there are more thread autofocus issues to iron out #19821

**Comment by SimonBrandner** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7167
