### ISSUE TITLE
WEBPs with transparency are not thumbnailed as transparent

### ISSUE THREAD

**Issue by hiddeninthesand** [vector-im/element-web#19838]
### Steps to reproduce

1. Acquire a WEBP with a transparent background.
2. Upload to a room.
3. Get a black background instead of a transparent one.

#### What did you expect?

A transparent background, such as what happens to PNGs with transparent backgrounds.

#### What happened instead?

A non-transparent background.

### Operating system

Ubuntu

### Application version

Element version: 1.9.4 Olm version: 3.2.3

### How did you install the app?

Ubuntu Repo

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Is the room you uploaded to encrypted or not? If not then the thumbnailing would be done by your server

**Comment by hiddeninthesand** [comment]
> Is the room you uploaded to encrypted or not? If not then the thumbnailing would be done by your server

It isn't encrypted, and after further checking it does seem to work in an encrypted chat. Should I bring this up with the home server hosts instead?

**Comment by t3chguy** [comment]
Yup!

**Comment by t3chguy** [comment]
Closing as synapse/server bug
