### ISSUE TITLE
Feasibility of Upgrading Cryptography? 

### ISSUE THREAD

**Issue by Librechain** [vector-im/element-web#19835]
### Your use case

Was tempted to add this in as an 'issue', but recently the NSA deprecated 256-bit strength cryptography (secp256k1 specifically; I think the NIST SP reference still recommends ed25519). 

In either case, was wondering about the feasibility of upgrading to ed448. otrv4 has a similar scheme to megolm, and the increase in overhead is negligible. Minus ed448, there are no additions to any of the libraries that I can think of at this point. 

### Not Demanding the Change 

If I can implement it on my end personally, I'm happy to do so. Just wondering if there are any caveats or things I should look out for first. 

Thank you in advance for taking time to answer this. 

### Have you considered any alternatives?

Only alternative would be using XMPP; I already have that integration in tow - but for other things.

**Comment by SimonBrandner** [comment]
I believe this should be filed at https://github.com/matrix-org/matrix-doc/

**Comment by t3chguy** [comment]
Agreed

**Comment by Librechain** [comment]
Will do guys @t3chguy @Simon; thank you.
