### ISSUE TITLE
When a space is upgraded, there is no indication shown to user

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#19841]
### Steps to reproduce

1. Have at least two accounts joined to a space
2. Workaround https://github.com/vector-im/element-web/issues/19208 by enabling developer mode and seeing room timeline to issue `/upgraderoom` or just send the tombstone event by hand.
3. Until cache is cleared and reloaded, there are two spaces visible, one upgraded.
4. Look at the space from account that didn't upgrade it. There is no hint that it has been upgraded or path to follow.

#### What did you expect?

I expected there to be a upgrade flow for members of the space like there is for rooms.

#### What happened instead?

There is no hint at all that upgrade has happened.

* ![Welcome to deprecated space](https://user-images.githubusercontent.com/831184/142831422-8e748d1a-376b-4bef-babd-729888c736a2.png)

Unless I developer mode see room timeline which looks like the expected room upgrade flow.

### Operating system

Microsoft Windows [Version 10.0.19043.1348]

### Application version

Element-versio: 1.9.4 Olm-versio: 3.2.3

### How did you install the app?

I am unsure whether I used winget or element.io

### Homeserver

matrix.org

### Will you send logs?

No

(Edit: I removed a revision from edit history due to accidentally including content from dual screen where the other was Slack.)

**Comment by t3chguy** [comment]
Space upgrades are not supported - https://github.com/vector-im/element-web/issues/19208

**Comment by heyakyra** [comment]
> 2\. Workaround https://github.com/vector-im/element-web/issues/19208 by enabling developer mode and seeing room timeline to issue /upgraderoom or just send the tombstone event by hand.

How does one do each of those? Is there a shortcut to open devtools from a space or does that also require using the browser inspector?

**Comment by Mikaela** [comment]
> > 2. Workaround #19208 by enabling developer mode and seeing room timeline to issue /upgraderoom or just send the tombstone event by hand.
> 
> How does one do each of those? Is there a shortcut to open devtools from a space or does that also require using the browser inspector?

Send a message `/devtools` to any room using Element Web and it opens a settings window where you can enable developer mode. With it enabled right click your desired Space and there you can type `/upgraderoom 10`

I don't have the manual tombstone format at hand anywhere so I would suggest seeing an upgraded room and from `/devtools` looking up the tombstone event.
