### ISSUE TITLE
Threads List: Filter

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#19846]
Let's discuss the Threads List Filter: All Threads & My Threads and whether it's manageable for the MVP launch of Threads. 

**Logic**
We believe the following to be true:
- High signal indicators; Start a thread, Respond to a thread, Mentioned in a thread.
- Low signal indicators; Emoji reactions

and therefore High Signal indicators should be included in the definition of "My Threads"

**Comment by gsouquet** [comment]
I don't think we'll easily be able to include threads you've been mentioned in. The server will never know about those events in encrypted rooms. And that mean clients should have the entire history of all threads in a room decrypted to build an accurate list

**Comment by daniellekirkwood** [comment]
Good to know! Thanks @gsouquet 

@janogarcia I'm going to remove the request to include "Mentions" as this is not possible. Users will be able to see Threads they are mentioned in by using the notification badges (as they do today). 

Do we have any other updates for this issue?

**Comment by daniellekirkwood** [comment]
This is a duplicate of: https://github.com/vector-im/element-web/issues/19809 and so will be closed
