### ISSUE TITLE
Suggestion: Have a "file a bug" button which goes to an issue form with prefilled variables

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19844]
#### What would you like to do?

Add a "File a bug on github" button to Element, and/or to rageshakes, to easily file bugs.

#### Why would you like to do it?

This would lower the threshold for filing bugs.

#### How would you like to achieve it?

Github has issue forms now, but one small thing that i just discovered is that you can prefill variables.

Compare the following URL to the following issue template;

```
https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Defect&template=bug-desktop.yml&version=Element%20version:%201.9.4%20Olm%20version:%203.2.3
```

https://raw.githubusercontent.com/vector-im/element-web/develop/.github/ISSUE_TEMPLATE/bug-desktop.yml

This pre-fills the "version" part of the report, leaving the user only to note down reproducability steps.

The local app could collect all version and install information on its own, such as OS (if possible), Version, Device, etc.

Note: For cross-version compatibility, it may be best for element.io to set up a bounce service, where the client just gives variables, and the service redirects to the latest bug-issue template, so this doesn't have to be hardcoded in the client.

Note 2: This would only work for github users, which would have to log in, it might not be very useful for every other user.

### Additional context

Clone of https://github.com/vector-im/element-ios/issues/5176

**Comment by turt2live** [comment]
This information is included in the subsequent rageshake/log submission, so I don't think we're terribly concerned about it. As mentioned on other issues, we also don't want to add too many bells to the UI as it can mean the feedback is impacted: freeform and minimal distractions produce the best bug reports.
