### ISSUE TITLE
Analytics events for Threads

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#19840]
We want to gather some information about product usage in regards to Threads in PostHog

We need to come up with a list of product questions we want to answer that I will then convert to events sent to PostHog.

### Questions to answer
**Discussed November 23, 2021**
* User has responded to a Thread 
  * Find answer to these questions with that event: Started a Thread, Added a reaction edited or redacted to a Thread, How many responses in one Thread, How many Threads in a room.
* How many users are opening the Thread list view (where from and with how many notifications)
* How many users are choosing to start a Thread (but may not complete Thread creation)
* How many users are using the Filter

**Comment by daniellekirkwood** [comment]
Have a draft document that we'll discuss tomorrow: https://docs.google.com/document/d/1hR7lyj54gdSZGi03zvhfezUAwxavcRRQWf9cgPqk6kI/edit?usp=sharing

**Comment by gsouquet** [comment]
Superseeded by https://github.com/vector-im/element-meta/issues/59
