### ISSUE TITLE
device_keys values must be a list of strings

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#19842]
### Steps to reproduce

Hello. We have old RiotIM client for x32 PCs. After last upgrade we got an error "device_keys values must be a list of strings" during send of message. Can we have temporary workaroud, may be some options in client or server, while we'll migrating to x64 PCs?

### Application version

1.5.15.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please put this as a comment on the 32 bit windows issue https://github.com/vector-im/element-web/issues/13175

**Comment by fidoman** [comment]
workaround for synapse 1.71 
fix it in place, so after server upgrade users can connect with riot and upgrade to element without service disruption
(as fresh element client refuse to work with old server you must first upgrade server)

```
/opt/venvs/matrix-synapse/lib/python3.10/site-packages/synapse/rest/client

--- keys.py-orig        2023-11-15 23:30:51.746311535 +0000
+++ keys.py     2023-11-15 20:40:33.766275710 +0000
@@ -171,6 +171,9 @@
         def is_list_of_strings(values: Any) -> bool:
             return isinstance(values, list) and all(isinstance(v, str) for v in values)

+        for k, v in device_keys.items():
+          if v=={}: device_keys[k]=[]
+
         if any(not is_list_of_strings(keys) for keys in device_keys.values()):
             raise InvalidAPICallError(
                 "'device_keys' values must be a list of strings:%s BODY:%s"%(repr(device_keys), repr(body)),

```
