### ISSUE TITLE
FilePanel no longer shows timestamps, so you can't permalink them or follow them in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19849]
Actually, you can permalink based on clicking the name of the user who sent the msg, but not being able to see the timestamp when it was sent is still problematic.

**Comment by SimonBrandner** [comment]
![Screenshot_20211123_075733](https://user-images.githubusercontent.com/25768714/142982207-1ab85b5f-8b35-4652-9935-80119c4b53e1.png)

I don't think I can repro

**Comment by turt2live** [comment]
Closing as presumed fixed.
