### ISSUE TITLE
Add vertical spacing between buttons when they go over multiple lines

### ISSUE THREAD

**Issue by Glandos** [vector-im/element-web#19853]
### Steps to reproduce

1. Switch to a language with long text like French
2. Open the preferences dialog, go to "Security and Privacy"
3. Scroll down to the encryption section

#### What did you expect?
![image](https://user-images.githubusercontent.com/297578/142927067-e7214a1a-5730-4c91-8ce6-8a7911f3d5ad.png)

#### What happened instead?
![image](https://user-images.githubusercontent.com/297578/142926981-6831b855-a43b-4c73-8345-dc5687b14a22.png)

Since buttons have long content, the line is broken, but the top and bottom margins are set on the parent element.
They should be set on each button instead.

This is true in this panel, but also within the dialog to verify your session with the security passphrase:
![image](https://user-images.githubusercontent.com/297578/142927545-7de44d99-ff4e-4178-bf4b-5093ac6f373a.png)

I suspect there are more.

### Operating system

Debian/unstable

### Browser information

Firefox 94.0

### Application version

Element develop 9746517ef734eec94c31a07d73c7c1bc7d30e932

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by twigleingrid** [comment]
Hey hey! I would like to do that!
I would add a `display: inline-flex` on the parent element of the buttons and then use the `gap` property for the spacing.
