### ISSUE TITLE
Home View should show spaces that rooms belong to

### ISSUE THREAD

**Issue by lilyball** [vector-im/element-web#19851]
#### What would you like to do?
When I'm in the Home View and looking at rooms (either those favorited, or with the "Show all rooms in Home" setting set) it should show me what spaces the rooms belong to.

If a room is in multiple spaces I belong to, I'm not sure what it should show (but showing any of the spaces is better than none). For Favorited rooms, ideally it would show the space I was looking at when I favorited the room, though I'm guessing that information is not saved. It could also use the order of spaces in the sidebar, or any other criteria, as long as it's deterministic. Perhaps it could even let me choose the space to display for a room (persisting this choice somewhere accessible to my other devices if possible).

#### Why would you like to do it?
My Home View right now has two favorited rooms both called "General". It's confusing. Thankfully they have separate icons.

#### How would you like to achieve it?
Show a smaller greyed-out subtitle on each room telling me the space it belongs to, if it comes from a space that I belong to.

**Comment by kittykat** [comment]
@lilyball could you check if https://github.com/vector-im/element-web/issues/19349 covers your usecase sufficiently? If it does, we can close this as a duplicate (and you are welcome to comment on the other issue)

**Comment by lilyball** [comment]
@kittykat That issue talks about filtering. Filtering the sidebar uses the same UI as the unfiltered sidebar, so if any such fix to the UI while filtering also applies without a filter then it would fix my issue. I'll go ahead and close this and comment there just to be sure it's covered.
