### ISSUE TITLE
If your computer doesn't send video, any VC you try to start terminates after a few seconds

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#1985]
If your computer doesn't send video, any voice/video conference (VC) you try to start terminates after a few seconds.

**Comment by t3chguy** [comment]
@SimonBrandner this is fixed now, right?

**Comment by SimonBrandner** [comment]
Yeah, this in general doesn't seem to be relevant anymore. If you don't have a camera, it should give an error dialog
