### ISSUE TITLE
Pressing keys without input focused adds weird focus ring to message instead of typing

### ISSUE THREAD

**Issue by lilyball** [vector-im/element-web#19852]
### Steps to reproduce

1. I'm in a room. I can see the sidebar and the room chat.
2. I click on a message to remove focus from the input.
3. I press any letter on my keyboard

#### What did you expect?
I expected it to type that letter into the input, like both Slack and Discord do.

#### What happened instead?
It put a focus ring around the message. Other than that, it did nothing at all with the key I pressed. Nothing I press at this point seems to actually do anything with the message. I also don't see any way with just the keyboard to move focus to the input field beyond pressing Tab enough times to get focus all the way there (past every other focusable element on the page).

Clicking on the page removes the focus ring, but pressing a key again just focuses the new message I clicked.

Pressing Space seems to both add the focus ring and scroll down by a page.

### Operating system

macOS

### Application version

Version 1.9.5

### Will you send logs?

Yes

**Comment by lilyball** [comment]
I've tried sending logs three times now. Do the logs not actually get attached to the GitHub issue? If so, this is non-obvious (I'd at least have expected some indication added to the issue to signal that logs were submitted).

**Comment by t3chguy** [comment]
They do but given that the logs are private only people with access to them can see them.

![image](https://user-images.githubusercontent.com/2403652/142924893-805ef0c6-c58a-42eb-8d96-e80cf27d2482.png)

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7167
