### ISSUE TITLE
Syntax Check Stopped Working

### ISSUE THREAD

**Issue by JordanHancock-NV** [vector-im/element-web#19861]
### Steps to reproduce

A couple of upgrades ago the automatic spell checking stopped working as eleweb.

It took me a while to notice, probably just thinking my spelling had all of a sudden become perfect :D

I checked in the settings if syntax highlighting was on and it is (I didn't need to toggle it)
![image](https://user-images.githubusercontent.com/62945565/143000661-45da3587-9125-4812-80ee-41f16d7a2f79.png)

Not sure what else I can provide to help?

#### What did you expect?
Syntax (spell) check to continue to work after upgrades

#### What happened instead?
Even though I think the right toggle is on there is no syntax highlighting for incorrectly spelt words

### Operating system

Windows 10

### Browser information

Version 96.0.4664.45 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/room/!KjInLFdSMaYaIyUWvb:matrix.org

### Application version

Versions: Element version: 1.9.5 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> A couple of upgrades ago the automatic spell checking stopped working as eleweb.

Spell checking or Syntax highlighting? They are very different things

Given you're using Element in a Web Browser, the Spell checking is handled entirely by your browser

**Comment by JordanHancock-NV** [comment]
Oh my, thanks for the 101 lesson!  Issue resolved.
