### ISSUE TITLE
Chat effects don't trigger by sending emoji

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19867]
### Steps to reproduce

1. chat effects are on
2. send an effect emoji like 🎉 ❄️ 👾 🌧️ ⛈️ 🌦️

#### What did you expect?
trigger effect on sending

#### What happened instead?
no effect

#### more info
- sending the respective command works
- receiving the same emoji works
- receiving a message generated from the respective command works

this probably regressed somewhere between Element version: 1.9.5 Olm version: 3.2.3 and my nightly, as it works on a 1.9.5 Windows 10 with whom I am chatting

### Operating system

arch

### Application version

Element Nightly version: 2021112301 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot reproduce

https://user-images.githubusercontent.com/2403652/143217989-e88d55e3-cf49-4294-b869-55e673248e26.mov

**Comment by HarHarLinks** [comment]
Works again in Element Nightly version: 2021112401
Olm version: 3.2.3
