### ISSUE TITLE
Display name randomly changed to my full name

### ISSUE THREAD

**Issue by malcolmbastien** [vector-im/element-web#19879]
### Steps to reproduce

1. I just have Element desktop app open and running in the background. I'm not interacting with the application at all

#### What did you expect?
Nothing.

#### What happened instead?
My display name randomly automatically changed from "Malcolm" to "Malcolm Bastien" which is my correct full name. This was unprompted and the change was made in every room I was in.

It happened to me:
![image](https://user-images.githubusercontent.com/62178/143250456-d73a5720-0ee4-4983-a2d2-a96e2eaff61f.png)

And one other user:
![image](https://user-images.githubusercontent.com/62178/143250534-326675ac-83ed-408b-957e-0392735b0ba1.png)

It doesn't appear that my full name is saved anywhere within the Element app, but clearly it must have found it somehow. My full name is "Name" as found at https://ems.element.io/user/account so maybe it was pulling from there.

Matrix ID is @malcolm:one.ems.host in case you need more info.

### Operating system

Windows

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Homeserver

one.ems.host

### Will you send logs?

No

**Comment by kittykat** [comment]
This is an upstream issue in EMS, lets leave this issue to track public-facing progress

(Internal issue is matrix-org/matrix-hosted/issues/4564)

**Comment by Half-Shot** [comment]
Hi @malcolmbastien, we've identified the cause and this shouldn't happen again! The name was being pulled from whatever displayname you chose during the setup wizard at the beginning, but from now on it shouldn't attempt to change it.
