### ISSUE TITLE
clicking permalinks to rooms which you're not in yet infinispinners after hitting join

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#19880]

**Comment by novocaine** [comment]
This seems important - can you please refile this according to https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Defect&template=bug-web.yml or at least add screenshots, version information etc

**Comment by robintown** [comment]
Closing, as this needs to be refiled with more info in order to have a chance of reproducing/diagnosing
