### ISSUE TITLE
Unable to delete / remove / redact messages

### ISSUE THREAD

**Issue by callahad** [vector-im/element-web#19882]
### Steps to reproduce

1. Send a message
2. Open the message's '...' menu then click "Remove..."
3. Click "Remove" in the modal

#### What did you expect?

The message gets removed

#### What happened instead?

Nothing. No HTTP request is issued, and the following message appears in the browser console:

> sendEvent of type m.room.redaction in !MiGyLAaeUPeNZgUtiW:matrix.org with txnId [object Object
> (rageshake.ts:65:27)

### Operating system

macOS

### Browser information

Firefox 95

### URL for webapp

develop.element.io

### Application version

Element version: 194aeac19e2d-react-a0e8c29d85f0-js-ddd6a05198ca, Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
`txnId [object Object` this smells like the threads js-sdk changes - @gsouquet did the api signature changes land?

**Comment by gsouquet** [comment]
Yes it has, let me look into that now
