### ISSUE TITLE
Explore Rooms / Explore Space button behaves inconsistently

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19892]
### Steps to reproduce

 1. Select the home / all rooms space
 2. Click 'Explore rooms'
 3. [Modal appears]
 4. Select a space
 5. Click the same button (explore [space])
 6. The room view changes (or if you're already on the space home, nothing happens)

### Outcome

It's a bit disorientating that the same button, with the same icon, in the same position, behaves differently depending on context. I got confused for a second thinking the button wasn't doing anything because I was already on the space home and no dialog was appearing.

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I've recently seen @niquewoodhouse's mockup somewhere which nicely places the room directory into the room view space, I really liked that

**Comment by t3chguy** [comment]
> with the same icon

This is a regression from the metaspaces work

https://github.com/matrix-org/matrix-react-sdk/pull/7052 is exploring this issue
