### ISSUE TITLE
Roles & Permissions section does not appear with custom permission

### ISSUE THREAD

**Issue by BramvdnHeuvel** [vector-im/element-web#19899]
### Steps to reproduce

1. Create a new Matrix room on Element version 1.9.5;
2. Go to Settings > Advanced > Open Devtools > Explore Room State > m.room.power_levels;
3. Click on `Edit`;
4. Add `com.example.whatever` to the `events` key with permission level 100;
5. Press Send. The permissions should now look like something like the following: 
![afbeelding](https://user-images.githubusercontent.com/43719024/143501460-4b18865f-c77f-43a6-b098-c0256f7686ec.png)
6. Exit the **Developer Tools** menu, but keep the **Room Settings** menu open;
7. Click on **Roles & Permissions**;

## What did you expect?
Element should now display the **Roles & Permissions** section of the room.
![afbeelding](https://user-images.githubusercontent.com/43719024/143501431-aee7807f-abaf-4a5f-96f4-3251bbf61887.png)

Similarly, it shows a similar view on Element Android.
![afbeelding](https://user-images.githubusercontent.com/43719024/143501521-a856e8af-99ed-4319-90c6-d32c818673d5.png)

## What happened instead?
The **Roles & Permissions** section closes unexpectedly. The console also shows an error.
![afbeelding](https://user-images.githubusercontent.com/43719024/143501718-c559bfa1-566e-42a5-a4e6-9706541a5c7f.png)

This happens with Element on Firefox and on Element Desktop. Element Android remains unchanged. I could not test this issue on Element iOS or on other browsers.

### Operating system

Windows desktop, Firefox

### Application version

Element version: 1.9.5, Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

noordstar.me

### Will you send logs?

No

**Comment by tulir** [comment]
Duplicate of #19812

**Comment by BramvdnHeuvel** [comment]
Good catch! 🔥 I'm closing the issue.
