### ISSUE TITLE
Ellipsis on long spaces name make the space panel size jump

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#19891]

**Comment by novocaine** [comment]
https://user-images.githubusercontent.com/57377/143403864-68788eb5-3ce5-48b4-aef9-bd6360507c2e.mov

**Comment by t3chguy** [comment]
I cannot reproduce this.
Version, environment, browser etc would be helpful

https://user-images.githubusercontent.com/2403652/143439190-f24c638e-cc38-46dd-887d-3f454a190de6.mov

**Comment by bwindels** [comment]
Seeing this on element desktop 1.9.5, Fedora 35 with Gnome 41.1 on wayland.

**Comment by t3chguy** [comment]
Likely Chromium specific, will investigate once again

**Comment by t3chguy** [comment]
Hmm, I'm unable to reproduce in Chrome too. Would be good to get version info from the original reporter.
@bwindels are you able to repro on Nightly/Develop at all?

**Comment by AmandineLP** [comment]
Element Nightly version: 2021112501
Olm version: 3.2.3

cf https://github.com/matrix-org/element-web-rageshakes/issues/6917

**Comment by jaller94** [comment]
Mozilla Firefox 95.0b8
https://staging.element.io
Element version: 1.9.5

![Peek 2021-11-29 15-32](https://user-images.githubusercontent.com/10872136/143886636-379697ba-8baf-439a-b9d0-6e8a78cc2da2.gif)

**Comment by jaller94** [comment]
These steps to reproduce assume the English (UK) locale. The panel width depends on the labels "All rooms" and "Create a space".

## Steps to reproduce:
1. Have no long space names or sub-spaces which push the panel width to its maximum width.
2. Create a space called "Create a spa" or longer.
3. Hover over the space in the panel.

## Known conditions:
- Have at least one space name that's as long as the "Create a space" button.
- Have no space name which is so long that it needs to be truncated by the CSS ellipses.

### Right length to reproduce
![Peek 2021-11-29 16-07](https://user-images.githubusercontent.com/10872136/143892648-246caded-2dab-4559-a6ae-b0e17b8f7872.gif)

### No name is as long as "Create a space" (minimum panel width)
![Peek 2021-11-29 16-08_2](https://user-images.githubusercontent.com/10872136/143892730-0a44d413-9b16-4880-a22b-1bacc7dec93f.gif)

### One name is too long to reproduce (maximum panel width)
![Peek 2021-11-29 16-08](https://user-images.githubusercontent.com/10872136/143892685-f3b100e7-d672-4203-adcf-9c9bb0692f74.gif)

**Comment by dkasak** [comment]
The space names don't have to be long for this to happen. I think in this case the requisite condition is that the hovered space is a parent space and that its section is expanded. When collapsed, it stops happening. This is on Element Desktop 1.9.9.

https://user-images.githubusercontent.com/463342/152530102-82b94d93-4693-4e3b-82a3-118533fe74b8.mp4

**Comment by jaller94** [comment]
For me it's the other way around where the width flickers with all parent spaces collapsed.

![Peek 2022-02-07 20-31](https://user-images.githubusercontent.com/10872136/152858570-a518495a-21c6-4d26-9a51-2e44f6ea3b60.gif)

**Comment by justjanne** [comment]
## Investigation

The list has a maximum width equivalent to the width of the largest element, or a given fixed maximum. If the longest element is an actual space (not the users own profile item, nor the settings or "create new space" item) the issue can occur.

The issue occurs because at that point the width of the entire panel is determined by the width of this longest space name. When hovering, the ellipsis menu appears, increasing the width of this space item, in turn increasing the width of the entire panel.
