### ISSUE TITLE
CallHandler.tsx: Uncaught TypeError: can't access property "callId", this.calls.get(...) is undefined

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#19902]
### Steps to reproduce

1. Log in to develop.element.io
2. (There may be additional steps specific to my account. e.g. having a hung up call in your recent history)

#### What did you expect?
"Signing In..." works

#### What happened instead?
The client gets stuck at "Signing In..." and shows this error in the JavaScript console.

```
Uncaught TypeError: can't access property "callId", this.calls.get(...) is undefined
    CallHandler CallHandler.tsx:902
    _invokeCallback Dispatcher.js:198
    dispatch Dispatcher.js:174
    setTimeout handler*dispatch dispatcher.ts:51
    MatrixChat MatrixChat.tsx:604
    _invokeCallback Dispatcher.js:198
    dispatch Dispatcher.js:174
    setTimeout handler*dispatch dispatcher.ts:51
    onLogoutClick MatrixChat.tsx:1872
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
CallHandler.tsx:902:54
```

https://github.com/matrix-org/matrix-react-sdk/blob/37828ab0842560712f8fb884f4e25cef9f5a1fa0/src/CallHandler.tsx#L912

### Operating system

Manjaro Linux

### Browser information

Firefox 95.0b8

### URL for webapp

develop.element.io

### Application version

2021-11-26

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
The method in which the error occured used to look like this:

```ts
this.stopRingingIfPossible(this.calls.get(payload.room_id).callId);

for (const call of this.calls.values()) {
	call.hangup(CallErrorCode.UserHangup, false);
}

```

Now it looks like this:

```ts
for (const call of this.calls.values()) {
	this.stopRingingIfPossible(call.callId);
	call.hangup(CallErrorCode.UserHangup, false);
}
```

As far as I can tell, the error shouldn't occur with the new code, so I am going to close this. Shout if you ever see this again!
