### ISSUE TITLE
Red shield in forwarding preview

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19913]
### Steps to reproduce

1. forward a message (from a fully verified e2ee room?)

#### What did you expect?
no red shields

#### What happened instead?
red shield in the preview

### Operating system

arch

### Application version

Element Nightly version: 2021112501 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by ankur12-1610** [comment]
@HarHarLinks I'm unable to reproduce the issue:sweat_smile:.
Kindly elaborate more properly.

**Comment by SimonBrandner** [comment]
> @HarHarLinks I'm unable to reproduce the issuesweat_smile. Kindly elaborate more properly.

Try forwarding a message from an encrypted room, it should happen then

**Comment by HarHarLinks** [comment]
yes, the required condition seems to be that the room is encrypted.
![image](https://user-images.githubusercontent.com/2803622/147238860-cf299d9d-e1d9-4301-9739-39a67720219c.png)

**Comment by ankur12-1610** [comment]
> yes, the required condition seems to be that the room is encrypted. ![image](https://user-images.githubusercontent.com/2803622/147238860-cf299d9d-e1d9-4301-9739-39a67720219c.png)

Ah! got it:+1:

**Comment by ankur12-1610** [comment]
I found some files related to the `e2eIcon` and found this [file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/dialogs/_ForwardDialog.scss#:~:text=.mx_EventTile_e2eIcon_unencrypted%20%7B,%7D) the most relatable one, I tried using `visibility: hidden` but it didn't work. Need some help :sweat_smile:

**Comment by SimonBrandner** [comment]
> I found some files related to the `e2eIcon` and found this [file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/dialogs/_ForwardDialog.scss?rgh-link-date=2021-12-24T07%3A33%3A33Z#:~:text=.mx_EventTile_e2eIcon_unencrypted%20%7B,%7D) the most relatable one, I tried using `visibility: hidden` but it didn't work. Need some help sweat_smile

The easiest solution might be finding the CSS class of the icon and then in the SCSS file of the forwarding dialog set its display property to `none`

**Comment by ankur12-1610** [comment]
> > I found some files related to the `e2eIcon` and found this [file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/dialogs/_ForwardDialog.scss?rgh-link-date=2021-12-24T07%3A33%3A33Z#:~:text=.mx_EventTile_e2eIcon_unencrypted%20%7B,%7D) the most relatable one, I tried using `visibility: hidden` but it didn't work. Need some help sweat_smile
> 
> The easiest solution might be finding the CSS class of the icon and then in the SCSS file of the forwarding dialog set its display property to `none`

I did the same, but the css class of the icon already has its display property to `none`. Can you please visit the file attached in the above comment:')

**Comment by SimonBrandner** [comment]
> > > I found some files related to the `e2eIcon` and found this [file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/dialogs/_ForwardDialog.scss?rgh-link-date=2021-12-24T07%3A41%3A58Z#:~:text=.mx_EventTile_e2eIcon_unencrypted%20%7B,%7D) the most relatable one, I tried using `visibility: hidden` but it didn't work. Need some help sweat_smile
> > 
> > 
> > The easiest solution might be finding the CSS class of the icon and then in the SCSS file of the forwarding dialog set its display property to `none`
> 
> I did the same, but the css class of the icon already has its display property to `none`. Can you please visit the file attached in the above comment:')

Argh, perhaps try `display: none !important;`

**Comment by ankur12-1610** [comment]
> > > > I found some files related to the `e2eIcon` and found this [file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/dialogs/_ForwardDialog.scss?rgh-link-date=2021-12-24T07%3A41%3A58Z#:~:text=.mx_EventTile_e2eIcon_unencrypted%20%7B,%7D) the most relatable one, I tried using `visibility: hidden` but it didn't work. Need some help sweat_smile
> > > 
> > > 
> > > The easiest solution might be finding the CSS class of the icon and then in the SCSS file of the forwarding dialog set its display property to `none`
> > 
> > 
> > I did the same, but the css class of the icon already has its display property to `none`. Can you please visit the file attached in the above comment:')
> 
> Argh, perhaps try `display: none !important;`

I got the CSS class, turns out it was `.mx_EventTile_e2eIcon_warning`. So I set it's display property to `none`.

I've raised a PR([#7447](https://github.com/matrix-org/matrix-react-sdk/pull/7447)), kindly review :)
