### ISSUE TITLE
Build from source crashing on Mac (M1)

### ISSUE THREAD

**Issue by jthoma** [vector-im/element-web#19925]
### Steps to reproduce

Build instructions went smooth and the .dmg was created. It could be installed, but on starting it crashes.

### Outcome

Not sure if it is due to the build:native building and linking for x86_64 under darwin. My mac PowerBook is having M1 arm64e chipset. 

### Operating system

macOS

### Will you send logs?

No

**Comment by novocaine** [comment]
The production build doesn't crash on M1, so something has gone wrong with packaging on your machine.

To debug, you can try running the binary from gdb and inspecting the stack trace to see where its dying.

**Comment by jthoma** [comment]
Sure will do, meanwhile when I tried "yarn start" there was an error on the console, but the UI started up.
`Keytar unexpected error: Error: dlopen(/Users/jijumathew/Projects/element-desktop/.hak/hakModules/keytar/build/Release/keytar.node, 0x0001): tried: '/Users/jijumathew/Projects/element-desktop/.hak/hakModules/keytar/build/Release/keytar.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/keytar.node' (no such file), '/usr/lib/keytar.node' (no such file)`

**Comment by novocaine** [comment]
aha, that looks similar to https://github.com/atom/node-keytar/issues/406#issuecomment-901794103

**Comment by jthoma** [comment]
Yes, it is, though I read somewhere that "yarn run build:native" will detect the platform and build accordingly; but it seems that the automatic behaviour is just detecting the "darwin" and assuming the chipset to be x86_64. Someone, please guide me how to hint the same to try compiling for arm64e for the native modules it could be better off..

**Comment by novocaine** [comment]
@dbkr might be best placed to answer that, although I think this might be more a conversation for [#element-dev](https://matrix.to/#/#element-dev:matrix.org)

**Comment by dbkr** [comment]
Yes, it should auto detect: I've just confirmed by starting from fresh and running, `yarn run build:native`, and I get an arm64 binary:

```
file .hak/hakModules/matrix-seshat/native/index.node
.hak/hakModules/matrix-seshat/native/index.node: Mach-O 64-bit dynamically linked shared library arm64
```

You can force the architecture as per the readme file, but I think we'd need to see exactly what you're running and what logs you're getting to be any more help.

**Comment by jryans** [comment]
I suspect we may need to know details like which Xcode version you have installed, etc.

Do you perhaps have some non-Apple toolchain on your path as the default complier or linker? That is likely to confuse things.

**Comment by jthoma** [comment]
@jryans :) just started using mac 2 weeks back, and even xcode was installed from the apple store - no idea about checking these things. 

xcodebuild -version

Xcode 13.1
Build version 13A1030d

**Comment by jthoma** [comment]
Thanks guyz, it was my ignorance. Somehow package.json was from an old release, once updated and followed the documented process the arm64 binary is built
