### ISSUE TITLE
Unable to load or view rooms initially created under a Space

### ISSUE THREAD

**Issue by ElDifinitivo** [vector-im/element-web#19920]
### Steps to reproduce

I've spun a dendrite HS on a VPS to test/compare with my synapse homeserver (ems.element.io). This might also be linked to dendrite unable to properly load Space room lists, but I only see this issue on desktop (desktop app and browser) but not on element for android.

Creating rooms from my synapse user and invite my dendrite user works fine, no issues there. If the room moved to be part of a Space, no worry. My dendrite user doesn't need to be part of the Space, and the room being invite only, space members only, etc. makes no difference. The issue arises when a room created initially as part of a Space (click on the Space -> Explore rooms -> Add). I create the room and invite my dendrite user, who is able to join without issue. The bug crops up when the dendrite user tries to view the room.

### Outcome

When the dendrite user tries to view the room, the room flashes for a split second before the "Something went wrong!" screen shows up. It can still view room settings and modify (given the correct permissions), it just can't see or access the chat.

Encryption being on/off doesn't change anything, and neither does if a local address is set or now. I've tested this on the Flatpak install v1.9.5 (dendrite user) with the Void repo install v1.8.4 (synapse user), as well as through the browser (app.element.io) with my dendrite user to cross-check to see if this was a Flatpak issue. I've also tried to replicate this on Android installed through F-Droid v1.3.7 and I can view the rooms without a crash.

### Operating system

Linux 5.13.19_1 (Void)

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

Private dendrite homeserver (docker)

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is the Room Upgrade warning bar exploding

`2021-11-27T23:57:36.706Z W URGENT upgrade required on !<roomID>`
