### ISSUE TITLE
Clicking quoted message takes me to the wrong message

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19934]
### Steps to reproduce

 1. Go to this mesaage: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$ZcLS-LbobQjkzNGGRzlrbc1i7AT9kR6CbbFxX_eRr3Y?via=matrix.org&via=vector.modular.im&via=chat.weho.st in #element-dev:matrix.org
 2. Click on the quoted message to view that message
 3. Timeline scrolls to a different message from Germain: $B3ubGk45GppP3SE0J5alH5Y4uam6uZomLoXzsj52UOw

#### What did you expect?
To see Germain's message starting, "Hello peeps"

#### What happened instead?
Saw some other message from Germain starting "Hey folks"

### Operating system

macOS

### Application version

2021112901

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment]
@dbkr I can't reproduce this, are you still seeing it? (Or is anyone else?)

**Comment by dbkr** [comment]
Yep, I can still reliably repro this

**Comment by SimonBrandner** [comment]
For me, it highlights the correct message but it's not fully in the view

**Comment by dbkr** [comment]
That may be it, and it may just be the my client's window is small enough that it's not visible. Mine also scroll-jumps as soon as I start scrolling after clicking the link, which makes it even more disorientating.

**Comment by justjanne** [comment]
If I jump to a message that has never previously been viewed with that client, it loads perfectly and is centered in the view.

If I jump to a message close to the messages I’ve loaded previously, it also is centered perfectly in the view.

If I jump to a message that’s far away in the history, but to which I’ve jumped before, it loads, but the view scrolls just past the message so the actual message I wanted to jump to is hidden just below the top bar.
