### ISSUE TITLE
UserMenu spinner is broken

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#19932]
### Steps to reproduce

1. Join a room
2. Look at the UserMenu spinner

#### What did you expect?

The spinner should be vertically centered and should show a tooltip on hover

#### What happened instead?

The spinner was out of alignment and hovering over it does not display any tooltips

### Operating system

NixOS unstable

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 10e121a5143f-react-9fefeefc8c8c-js-b33b01df0f32 Olm version: 3.2.3

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by t3chguy** [comment]
This spinner is moved and re-implemented as part of IA1.1
