### ISSUE TITLE
"New login. Was this you?" message does not disappear

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#19930]
### Steps to reproduce

1. Logged in and verified on one device.
2. Log in on a new device.
3. Follow the steps to verify successfully.
4. The first device now says "New login. Was this you?"
5. Click "Check your devices", which launches the Settings dialog.

#### What did you expect?

I expected the "New login.  Was this you?" prompt to disappear.

#### What happened instead?

"New login.  Was this you?" is still displayed.

I tried clicking "Later" and it did not disappear.

When I click "Later" I see this in the console:

```
Dismissing unverified sessions: LBYEJFXLBG rageshake.ts:65:27
Old unverified sessions: rageshake.ts:65:27
New unverified sessions: rageshake.ts:65:27
```

Later in the console I see this:

```
Error getting device cross-signing info TypeError: device is null
    deviceToObject CrossSigning.ts:592
    checkDeviceTrust CrossSigning.ts:569
    isDeviceVerified DevicesPanel.tsx:122
    render DevicesPanel.tsx:304
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    loadDevices DevicesPanel.tsx:74
rageshake.ts:65:27
    fnName rageshake.ts:65
    instrumentConsole instrument.js:111
    isDeviceVerified DevicesPanel.tsx:129
    render DevicesPanel.tsx:304
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    loadDevices DevicesPanel.tsx:74
```

### Operating system

Ubuntu 21.10

### Browser information

Firefox 94.0 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: 10e121a5143f-react-6d3865bdd542-js-b33b01df0f32
Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Other stuff in the logs:

```
Error: Promised response from onMessage listener went out of scope 3 common.js:4:491
```

**Comment by SimonBrandner** [comment]
Perhaps a duplicate of https://github.com/vector-im/element-web/issues/17667?

**Comment by andybalaam** [comment]
Well spotted @SimonBrandner

**Comment by andybalaam** [comment]
Duplicate of #17667
