### ISSUE TITLE
Voice-chat not connecting

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-web#19943]
### Steps to reproduce

Hi,
me and my friend are hosting or own matrix-synapse server and we are using element as the client.

At first everything worked correctly. After some updates things changed. Now we cant Make calls beside using the jitsi widget. But everything else works.

!!! The calls works if i the call is coming from the same local network. !!!

What have changed in this time form it worked to its broken?
Our dns got a new static ip address. we updated matrix-synapse from 1.25 to 1.47.1.

I cleaned the log so only the test connection from test and test2 user is visible. We made the test call between 20:05:59 and 20:06:04.
I noticed an interesting error -> DNS Lookup searches for matrix.archgang and not matrix.archgang.xyz but i checked all the configs and it seems that i configured the domain everywhere correctly.
Our config and log files are down below, i hope you can give us some tipps.

[homeserver.yaml](https://pastebin.com/GHDCTDtd)
[Apache VHost Config](https://pastebin.com/N4vtKWCq)
[homeserver.log](https://pastebin.com/C7DhATY1)

EDIT: I also did a full clean install but it did the same issue.
### Outcome

Voice-chat connects.

### Operating system

Linux, Windows

### Homeserver

matrix.archgang.xyz

### Will you send logs?

Yes

**Comment by robintown** [comment]
It appears from your config that you haven't set up a TURN server, which is necessary for calls to work across NATs. See https://matrix-org.github.io/synapse/latest/turn-howto.html for details on how to configure one.
