### ISSUE TITLE
Crash when switching spaces

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#19942]
### Steps to reproduce

Unsure, but it happened when I switched spaces to Matrix Community

#### What did you expect?

To switch spaces

#### What happened instead?

Full page 'Something went wrong!' message

### Operating system

NixOS unstable

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 090fc808bbc9-react-82ae39435c3e-js-b33b01df0f32
Olm version: 3.2.3

### Homeserver

townsendandsmith.ml

### Will you send logs?

Yes

**Comment by eternaleye** [comment]
I've also encountered this, and submitted a log.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7228
