### ISSUE TITLE
Quick actions bottom padding too small

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19956]
### Steps to reproduce

scroll to the bottom of a space room list

### Outcome

![image](https://user-images.githubusercontent.com/2803622/144038822-3460baf0-420e-48e2-9625-e1f13ec5b618.png)
the bottom padding/margin is smaller than the other 3 sides

### Operating system

arch

### Application version

Element Nightly version: 2021113002 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
Quick actions are going away with IA1.1
