### ISSUE TITLE
Crash after pressing Ctrl-K

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#19952]
### Steps to reproduce

1. In a DM
2. Press Ctrl-k to search for a room
3. Start typing name of room

#### What did you expect?

Usually, I get search results for the room I am looking for

#### What happened instead?

This time, I got "Something went wrong!" and a page asking me to log a bug.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 94.0 (64-bit)

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7228
