### ISSUE TITLE
Crash when switching rooms

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19951]
### Steps to reproduce

1. (Filter for a room).
2. Click on a room.
3. Crash, sometimes.

My rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/6971

Others: https://github.com/matrix-org/element-web-rageshakes/issues/6970 https://github.com/matrix-org/element-web-rageshakes/issues/6968

### Operating system

macOS

### Browser information

Chrome, latest

### URL for webapp

develop.element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7228
