### ISSUE TITLE
Quick settings theme dropdown can go out of bounds

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19963]
### Steps to reproduce
Install some custom themes

#### What did you expect?
see everything

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/144088551-8bf26607-e271-4a26-8745-f8c1d9dd4794.png)

### Operating system

arch + sway + ozone

### Application version

Element Nightly version: 2021113002 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
> Fixed by #19963

19963 is this issue, not a PR

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7764 then :P
