### ISSUE TITLE
emoji verification descriptions are ellipses

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#19977]
### Your use case

descriptions can be ellipses which isn't great. there is plenty space.

![image](https://user-images.githubusercontent.com/2803622/144143224-0b15c342-8fe6-4e31-82b2-802ac40c01b4.png)

happens at least in the popup, not sure about right panel.
A-E2EE-SAS-Verification
A-E2EE-Cross-Signing

**Comment by dbkr** [comment]
I'd probably say minor for this one, effectively the workaround is to guess it from the text you can see + the image.

**Comment by HarHarLinks** [comment]
in case it's not clear: this should be made to work flexible enough for any emoji description i18n

**Comment by bmarty** [comment]
I have encountered the issue today, I agree this is not great, and this should be fixed.

**Comment by t3chguy** [comment]
This was done specifically by design

**Comment by bmarty** [comment]
We suck

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/12974
