### ISSUE TITLE
Imgur & Tenor "Gifs"  don't embed on Element Web

### ISSUE THREAD

**Issue by nathanielcwm** [vector-im/element-web#19970]
### Steps to reproduce

1. Send or receive a link to an Imgur or Tenor "GIF" in chat
2. Observe that the embed just asks you to open a separate tab to open Imgur or Tenor instead of showing you the video.
![image](https://user-images.githubusercontent.com/22572406/144101220-9f3a34b4-37e7-495c-b4bf-c8929ef00dc1.png)
![image](https://user-images.githubusercontent.com/22572406/144101511-5fd4935c-542f-4a26-9469-f76a6eeafd6a.png)

#### What did you expect?
Video to be embedded into chat
#### What happened instead?
All that is embedded is some text asking for you to open imgur/tenor in a separate tab.

### Operating system

Windows

### Browser information

Firefox 94.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The url previews are generated by the server, not the client

**Comment by nathanielcwm** [comment]
Static imgur galleries also do not embed.
![image](https://user-images.githubusercontent.com/22572406/144101692-23205ec5-8453-4090-88ae-9466b7ac8739.png)

But i.imgur.com links do embed
![image](https://user-images.githubusercontent.com/22572406/144102038-4b5ac290-59e5-4fab-9941-fed7b0711de0.png)

**Comment by t3chguy** [comment]
If you want this to be looked into I suggest creating a https://github.com/matrix-org/synapse/ issue instead, Synapse devs don't tend to look at this issue tracker.

**Comment by nathanielcwm** [comment]
> The url previews are generated by the server, not the client

Ah so should I close this issue?

**Comment by nathanielcwm** [comment]
> If you want this to be looked into I suggest creating a https://github.com/matrix-org/synapse/ issue instead, Synapse devs don't tend to look at this issue tracker.

Looks like there are already some related issues there.

**Comment by SimonBrandner** [comment]
> > The url previews are generated by the server, not the client
> 
> Ah so should I close this issue?

Yes, I am going to close it as it seems to be a server issue
