### ISSUE TITLE
Signin from Guest Crashes

### ISSUE THREAD

**Issue by Sleuth56** [vector-im/element-web#19972]
### Steps to reproduce

1. Login
2. Enter a room
3. Copy the URL
4. Logout
5. Paste the URL
6. Refresh
6. Click on the user then the sign-in button
7. Element should crash

#### What did you expect?
To be brought back to the sign in screen.

#### What happened instead?
Element crashes

### Operating system

Manjaro Linux

### Browser information

Firefox Latest and Brave Latest

### URL for webapp

https://develop.element.io

### Application version

Element version: ae048025e4fc-react-c09e0efdb9fb-js-87b920698f4c Olm version: 3.2.3

### Homeserver

chat.mountainview.theworkpc.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
(label based on glance at rageshake)
