### ISSUE TITLE
Pressing on a forward/backwards button on the mouse makes element take a "detour" through the home metaspace

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19974]
### Steps to reproduce

1. Go to room A in space A
2. Go to room B in space B
3. Press "backwards" on mouse
4. Observe "detour" through Home

#### What did you expect?

For element to just directly go to the last room in the last space

#### What happened instead?

For element to take a small delay loading Home, then immidiately switching to that last room

### Operating system

PopOS Linux, 21.04

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

No

**Comment by t3chguy** [comment]
I was planning on looking into this tomorrow prior to this issue landing :D

**Comment by t3chguy** [comment]
It even happens on rooms in the same space, the trigger looks to be going to a room with a canonical alias (this may be confirmation bias though)
