### ISSUE TITLE
Timeline's scrollbar is not reserved space, causing read receipts and such to jump left

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19979]
The scrollbar on the timeline should always be reserved space to prevent jarring jumps in content. Appeared on develop. Easiest to reproduce in encrypted rooms which require backfill

**Comment by SimonBrandner** [comment]
I don't think I can repro, could you please provide a video of this?

**Comment by turt2live** [comment]
Video is difficult because of my account's sensitivity, but I can reproduce it when clicking into HQ every time.

**Comment by gsouquet** [comment]
Regressed by https://github.com/vector-im/element-web/issues/19580

**Comment by kittykat** [comment]
@turt2live can you verify if this was fixed with the closing of the above bug?

**Comment by turt2live** [comment]
Which fix, sorry? I still see this in today's nightly.

**Comment by turt2live** [comment]
Presuming fixed.
