### ISSUE TITLE
Pressing Super button causes some U.I. element to be given a thick, gold border.

### ISSUE THREAD

**Issue by Penguin-Guru** [vector-im/element-web#19975]
### Steps to reproduce

1. Where are you starting? What can you see?
In the main view, looking at a room conversation and the rooms and spaces sidebars on the left.
2. What do you click?
I press the Super (A.K.A. Windows, Command) button on my keyboard.
3. More steps…
None.

#### What did you expect?
Nothing to happen in the application.
#### What happened instead?
A thick, gold border appears around one of a few elements in Element. Elements I've seen subject to this are the spaces column, the sub-space column, and (rarely) individual rooms in the listing. It's only ever one at a time. The border disappears when I click on something else in the application. It also disappears when I focus a different window, but then it returns when I focus Element again. This is very annoying because I use Super for a lot of common keyboard shortcuts. Convention on all platforms (I know of) has long considered this a system utility button, not to be used by applications.

### Operating system

Linux.

### Application version

Element version: 1.9.2, Olm version: 3.2.3

### How did you install the app?

Native package manager.

### Homeserver

matrix.org

### Will you send logs?

Only if you really want them.

**Comment by t3chguy** [comment]
This is chromium showing you the focus outline, a key visual accessibility feature.

**Comment by Penguin-Guru** [comment]
Can it be disabled or changed to appear with a different shortcut? I use Chromium as my normal web browser and it does not do this when I press the Super button.

**Comment by SimonBrandner** [comment]
@Penguin-Guru, would you be ok with closing this issue in favour of https://github.com/vector-im/element-web/issues/19889?

**Comment by Penguin-Guru** [comment]
@SimonBrandner Yes, that probably makes sense. I think the Super button is especially important to fix but it is basically the same issue. Sorry I couldn't find that one before opening this. I did try.

**Comment by SimonBrandner** [comment]
> @SimonBrandner Yes, that probably makes sense. I think the Super button is especially important to fix but it is basically the same issue. Sorry I couldn't find that one before opening this. I did try.

No worries, be sure to copy your thoughts onto the other issue!
