### ISSUE TITLE
You can set a very long status message now

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#19988]
### Steps to reproduce

1. Set a very long status, you can notice that there isn't any limit on how many characters you can use in a status unlike the old one which has a limit on how many characters you can use in a status

#### What did you expect?
It limits to a few characters (I didn't know how much though in the old one)

#### What happened instead?
You can set a very, very, very long status, which I have to zoom out to be able to see the whole status:
![how long can this status get](https://user-images.githubusercontent.com/47475676/144244489-9d5d7d19-0bd9-477d-92bd-c9994b83f060.png)
<details>
<summary>The status message</summary>
how long can this status get? huh? what? how long is it? why is it longer than last time? this is okay though - sadjkhhajskfhjasfhjsdfhjsdahjlfjhsadfhjlsadjkfhajyweuirhfsdjczykisaugwejksgrheywaeujgaszhrywatesgdfs ajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj fuewg hwrefwherf uiht wer h h h h  hh fhfhfhhddddddddddddddddddddddddddddfewff wef      asf asdf asd f    qwetf da sdgs rwtef as     5eyr gsfdd gj tej rtng d uku 67i uyrjth    gdsh sb s dfb sdfb sdf bs dh dsgdf g dsg sdg sdfg dg d gds fgfd
</details>

### Operating system

Arch Linux

### Application version

Element Nightly version: 2021120101 Olm version: 3.2.3

### How did you install the app?

AUR

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
