### ISSUE TITLE
translation doesnt work for some placeholder (example: email)

### ISSUE THREAD

**Issue by rezaei92** [vector-im/element-web#19989]
### Steps to reproduce

In some form translated placeholder doesnt shown correctly.
for example in email input translated placeholder shown as "missing translation: et|Kinnita"
In forgot password page "confirm" does not display correctly when I selected other lang and print error (missing translation) while translated word is exist in json translation file in matrix-react-sdk.
I tested that for several languages  and results were same.

![image](https://user-images.githubusercontent.com/93854988/144240103-dfa3e60c-0699-4f88-8bb4-af7a04a2169a.png)

#### What did you expect?
I want to see the correct translation of that word
#### What happened instead?
for example in email input translated placeholder shown as "missing translation: et|Kinnita"

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue of double-translation
