### ISSUE TITLE
Unexpected order of "Next room" navigation when "Show rooms with unread messages first" is checked

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#19983]
### Steps to reproduce

1. Several rooms have unread messages
2. Choose "List Options" next to Rooms, and choose "Sort by: activity" and "Show rooms with unread messages first"
3. Click within the room somewhere so Ctrl-DownArrow works to navigate.
3. Use Ctrl-DownArrow on the keyboard to navigate through the rooms.

#### What did you expect?

I expected to step through the rooms one by one until I have seen all rooms with unread messages.

#### What happened instead?

I only see half of the rooms as I navigate downwards.  It seems like Element re-sorts the rooms based on their unread status **before** it chooses the next room to move to.

![element-room-nav](https://user-images.githubusercontent.com/76812/144208436-70ed819e-d5c5-4879-bd0b-4be3c87572fc.gif)

I expected to see Pinephone, Python, Matrix HQ, Ubuntu as I pressed Ctrl-DownArrow, but I actually saw Pinephone, Matrix HQ, Raspberry PI, and the list shuffled around under me.

For comparison, Slack with similar settings navigates through the rooms in the order they are displayed, and the order does not change as I move.

![slack-room-nav](https://user-images.githubusercontent.com/76812/144211724-efce727d-ebbb-41d2-b146-ddadc6e99e56.gif)

### Operating system

Ubuntu MATE 21.10

### Browser information

Firefox 94.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: f496d6d5bf31-react-cbb34d8ac7b3-js-87b920698f4c Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andybalaam** [comment]
Related, or even dup? #15663

**Comment by SimonBrandner** [comment]
> It seems like Element re-sorts the rooms based on their unread status

Yep, I think so
