### ISSUE TITLE
When clicking 3-dots button on uploaded video, the menu appears far to the left, disconnected from the 3-dots

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/element-web#19980]
### Steps to reproduce

1. Upload video to matrix room (room has e2ee active)
2. Click 3-dots button
3. The menu with the "Download" option appears far to the left of the 3-dots button, and is partially hidden by the left-hand panel
4. Click and drag the left-hand panel's resize handle to reveal the menu with the "Download" option
![3-dots-disconnected](https://user-images.githubusercontent.com/29561518/144161630-05cb62d6-5c24-460a-a348-21b74cb22f16.png)

#### What did you expect?

I expected the menu to appear connected to the 3-dots button

#### What happened instead?

The menu appeared disconnected, and was actually not easy to find, since it was partially hidden by the left-hand pane

### Operating system

Linux Mint 20.2

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Will you send logs?

No

**Comment by t3chguy** [comment]
Interesting, this is a native browser component (Chromium) - seems like an Electron/Chromium bug

**Comment by t3chguy** [comment]
Can reproduce on macos, will try again after updating electron - related https://github.com/vector-im/element-web/issues/20378

**Comment by dbkr** [comment]
re-opening because we downgraded electron again
