### ISSUE TITLE
Element Web shows blank message for polls if Labs feature disabled (or if on Stable, where it doesn't exist)

### ISSUE THREAD

**Issue by eternaleye** [vector-im/element-web#19981]
### Steps to reproduce

1. Where are you starting? What can you see?

On Element/Web stable (or on Develop with the polls feature disabled)

2. What do you click?

A room a poll has been started in

#### What did you expect?

Either not seeing the poll start message at all, or some kind of UI indicating an unrecognized message type.

#### What happened instead?

A message that looks like a perfectly ordinary textual message, but with no text at all.

In Develop, with the feature disabled:
![image](https://user-images.githubusercontent.com/99404/144201541-97484733-6158-4785-9a61-36509b1f9ed7.png)

(the stable case was reported to me by a friend, at which point I repro'd in Develop)

### Operating system

Exherbo Linux

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 090fc808bbc9-react-5c895bf3f68d-js-db9936e07c39 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment]
Polls have been released, and can no longer be disabled.
