### ISSUE TITLE
Add emoji picker in the user custom status message section

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#19982]
### Your use case

![Element](https://user-images.githubusercontent.com/47475676/144199186-2f2ad8af-a699-41d4-b082-71ac80fc52c1.png)

![discord](https://user-images.githubusercontent.com/47475676/144203624-3e66a3fa-687c-4a79-989f-852c2168b2b7.png)
Here's Discord for example

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
