### ISSUE TITLE
Breadcrumbs no longer stay scrolled to the left when rapidly switching rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19993]
It diverges further and further the more rooms you click. This is problematic for folks trying to catch up on their european colleagues' posts 😇

**Comment by kittykat** [comment]
@turt2live were you on production or develop? With IA on or off?

**Comment by turt2live** [comment]
This was nightly at the time, without the labs flag (it hadn't landed yet)

**Comment by gsouquet** [comment]
This looks outdated as the designs have changed and breadcrumbs are not in a dropdown menu
