### ISSUE TITLE
Thread fallback replies should be off the most recent message rather than the root

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19997]
When someone is talking in a thread they are almost certainly referencing the most recent message rather than the root, which leads to a lot of confusion for those without threads enabled/supported.

**Comment by gsouquet** [comment]
The event source has a relation pointing to the thread root. The client could potentially do some magic to figure out what is the last reply of that thread and use that as a quote reply instead, but that could lead to the quote reply displayed not being the same across all clients and users viewing that timeline

**Comment by turt2live** [comment]
hmm, looks like the internal follow-on conversation didn't make it here. Due to the added complexity of the fallback handling, and the fact that it's not actually in the event and is rather a client-specific rendering, I'd recommend just removing the feature entirely. 

I believe I've commented this on the MSC at some point.

**Comment by kittykat** [comment]
My concern with removing the replies for threaded messages is that the messages will appear completely out of context, which would lead to user frustration… (this has already been the case for me on app.element.io in the early days of threads)

**Comment by turt2live** [comment]
it's even more frustrating to have context that's wrong :(

**Comment by gsouquet** [comment]
This has now been implemented on EW
