### ISSUE TITLE
User can keep trying to join an empty DM room which is not joinable

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#19992]
### Steps to reproduce

1. User1 starts a DM with user2
2. User1 leaves DM before user2 joins
3. User2 tries to accept the invite (in the  "Do you want to chat with user1?" room view, using "Start chatting")
4. "Failed to join room" -> OK
5. Return to "Do you want to chat with user1?" room view

#### What did you expect?
If I will never be able to join the DM, I don't want to keep getting the option

#### What happened instead?
I can keep trying to join the chat.

### Operating system

Arch Linux

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 1.9.6-rc.2 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
it should be possible to "reject" this invite after getting a sane error message. Making the invite go away after the inviter leaves is a spec issue.

**Comment by turt2live** [comment]
this was re-tested and it appears the error message is clear enough to communicate intent.

If it's ever unclear, a new issue can be opened for tracking.

**Comment by kittykat** [comment]
![Screenshot from 2022-05-18 21-55-51](https://user-images.githubusercontent.com/51663/169156079-3b773fde-d1fa-4638-8b3e-1cbc05a34397.png)
