### ISSUE TITLE
Messages in threads you are not involved in shouldn't notify

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#19996]
in desktop notifications

**Comment by HarHarLinks** [comment]
what if I'm "involved" by passively following (reading) a thread, and want to keep up?

**Comment by t3chguy** [comment]
> what if I'm "involved" by passively following (reading) a thread, and want to keep updated?

Then maybe even the act of opening the thread should be considered as you being involved. Having an RR in the thread could be used to track it maybe.

**Comment by HarHarLinks** [comment]
also interesting could be a checkbox to (un)subscribe to a thread, not unlike here on github
![image](https://user-images.githubusercontent.com/2803622/144421127-17ed0aa4-891c-4b91-80c9-2d09ddd935b8.png)

**Comment by janogarcia** [comment]
@HarHarLinks Selectively following and unfollowing threads, without requiring you to actively participate on a thread, was considered early in the design process, but won't make the cut for the first release. /cc @daniellekirkwood 

As for @t3chguy remark's on notifications, that's correct, you should only get notifications for those threads that you either are the author of the root message or have replied to it (first reply or any subsequent reply).

![Threads – Figma](https://user-images.githubusercontent.com/60790/144470494-f8f94247-8b7e-4faf-9493-e4141057d278.png)

---

I'm removing the X-Needs-Design and X-Needs-Product labels.

**Comment by HarHarLinks** [comment]
So reacting to a thread message doesn't count to "follow" it either? :/

**Comment by janogarcia** [comment]
@HarHarLinks We'll consider that interaction as low engagement. A future, proper follow mechanism will give more fine grained control over thread follows.

> As for reactions, we consider those low signal/engagement, so those should be excluded. A proper follow/unfollow mechanism, planned for a future release, would allow users to selectively follow threads even if they haven't actively participated in them.

https://github.com/vector-im/element-web/issues/19809

**Comment by gsouquet** [comment]
Blocked by https://github.com/matrix-org/synapse/issues/11399

**Comment by gsouquet** [comment]
To test against https://github.com/matrix-org/synapse/pull/11577

**Comment by daniellekirkwood** [comment]
Thread messages should follow the room notification levels. We have an Element document outlining the exit beta milestone behaviour for notifications [(here)](https://docs.google.com/document/d/1DYyDsf24OlrME3h-Hg-H2GvCrKkqZJrQwIbNWjqxB2A/edit?usp=sharing)

Therefore I'm closing this issue

**Comment by bhearsum** [comment]
Is it going to be possible to unfollow (or explicitly follow) threads? Currently it seems like this is not possible, although this issue suggests otherwise (unless the document above that I can't access says something different).

Currently, I get notified on every thread in every channel I'm in which seems....less than ideal.
