### ISSUE TITLE
Discovery section got stuck in submitted state when adding phone number as well

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20003]
### Steps to reproduce

1. In Settings -> General,
1. Add phone number
2. Scroll to Discovery section
3. Tick box and Accept

#### What did you expect?
Discovery is enabled and dialog is updated

#### What happened instead?
Discovery section got stuck in submitted state

![VvJgcOf](https://user-images.githubusercontent.com/51663/144320383-2cf0f698-b4b2-48dc-a887-e6d1569818ec.png)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by novocaine** [comment]
Can you reproduce this and record logs please?

**Comment by turt2live** [comment]
This is trivially reproduced:

1. Create a new account
2. Open the user settings
3. Click the checkbox noted in the issue description
4. Click continue
5. Wait forever
6. Nothing happens

To skip step 1 on a dev account, clear the accepted terms account data.
