### ISSUE TITLE
Add Markdown support in custom status messages

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20006]
#### What would you like to do?
Adding Markdown support in custom status messages

#### Why would you like to do it?
I want to be able to use Markdown (or HTML) in status messages, like strikethrough, hyperlinks, …

#### How would you like to achieve it?
Interpret status messages as Markdown

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
