### ISSUE TITLE
(1 more message) displayed at the end of bot response but no more message

### ISSUE THREAD

**Issue by mystiquewolf** [vector-im/element-web#20009]
### Steps to reproduce

1. Chatting with the bot named "phrick" in #archlinux:libera.chat
2. Executing/sending command `plugin help Anonymous`
3. Receiving a little long paragraph which ends abruptly with (1 more message) - but there is no message after that message.

#### What did you expect?
To be able to see that (1 more message)
#### What happened instead?
Only text (1 more message) shows but no more messages after that

### Operating system

Arch Linux

### Browser information

Firefox 94.0.2

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is unrelated to Element Web, either the bot or the bridge is at fault, the `1 more message` bit is part of the sent text.

```
"body": "webdevguru_test31:  This plugin allows users to act through the bot anonymously. The 'do' command has the bot perform an anonymous action in a given channel, and the 'say' command allows other people to speak through the bot. Since this can be fairly well abused, you might want to set supybot.plugins.Anonymous.requireCapability so only users with that capability can use this plugin. For extra security, you can require that the user be  (1 more message)",
```

![image](https://user-images.githubusercontent.com/2403652/144415258-2decb609-05b0-4847-87d7-2794c8d31a1f.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/144415600-de977970-603a-4b65-bdf3-615bcbbd1a98.png)

Have confirmed the but is with the bot, happens directly over IRC too.
