### ISSUE TITLE
Turn on/invent a lint rule for member visibility (public/private)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20019]
This is part of our TS style guide and code is ending up without it being specified

**Comment by turt2live** [comment]
fwiw, the policy is also to make it optional on the react function overrides, but a linter is not going to be able to distinguish that. I don't feel it's a bad thing to fully specify `public componentDidMount()`, personally.

**Comment by SimonBrandner** [comment]
> fwiw, the policy is also to make it optional on the react function overrides, but a linter is not going to be able to distinguish that. I don't feel it's a bad thing to fully specify `public componentDidMount()`, personally.

Yeah, I don't really see why not do this, it will certainly feel more consistent if _all_ methods have member visibility set

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23673
