### ISSUE TITLE
Message bubbles stopped working on develop.element.io

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20014]
### Steps to reproduce

1. Enable "New layout switcher (with message bubbles)" in Settings -> Labs

#### What did you expect?
Message bubbles continuing to work how they used to

#### What happened instead?
All messages are on the left and not in message bubbles

![Screenshot from 2021-12-02 15-39-50](https://user-images.githubusercontent.com/51663/144454120-2d4711de-6fa5-4556-9725-8a5ccb6fc9b4.png)

### Operating system

Arch Linux

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 0e69caee7c6a-react-f40291d408cc-js-b716cde9b558 Olm version: 3.2.3 (broke in an earlier version)

### Homeserver

n/a

### Will you send logs?

No

**Comment by t3chguy** [comment]
Does it work if you change rooms?

**Comment by kittykat** [comment]
> Does it work if you change rooms?

No, I haven't been able to do anything to get them back (tried switching on and off, etc). I haven't tried clearing cache, but I can reproduce the issue in Firefox 94.0.2 with a fresh login.

**Comment by robintown** [comment]
Are you sure you've selected message bubbles in appearance settings?

**Comment by kittykat** [comment]
I'm going to close this issue as they've reappeared now after an update/restart
