### ISSUE TITLE
Missing translation: es (login web)

### ISSUE THREAD

**Issue by JulianGR** [vector-im/element-web#20010]
### Your use case

I've encountered a "missing translation" message in the placeholder of the login and restore password forms. It's not really a bug and not that critical: i'm just reporting it just for the dev team to know.

The first image is for the "restore password" form (thus in spanish, _elegir nueva contraseña_). It should be "**Confirmar contraseña**" (_confirm password_ in english) where it says "missing translation: es | Confirmar"
[https://i.imgur.com/hlhQ8D0.png](https://i.imgur.com/hlhQ8D0.png)

The second image is for the "login" form. It should be "**Correo electrónico**" (_email_ in english) where it says "missing translation: es | Correo electrónico"
[https://i.imgur.com/O15ZHWL.png](https://i.imgur.com/O15ZHWL.png)

**Comment by t3chguy** [comment]
Already fixed on develop

**Comment by t3chguy** [comment]
Actually only the first one was fixed, the email field not.
