### ISSUE TITLE
Add a workflow to triage Labs issues better

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20016]
Add a job that is triggered when an issue [is labelled](https://github.com/vector-im/element-web/blob/develop/.github/workflows/triage-move-labelled.yml).

Check if it contains any labels for features behind labs flags (like A-Polls or A-Threads).

If it does, then add an Z-Labs label to that issue.

**Comment by ankur12-1610** [comment]
@kittykat I'm really curious and interested to work on this label-action issue. But I'm not sure how do I approach the problem and apply the logic to the `triage-move-labelled.yml`. Can you please assist :sweat_smile: ?

**Comment by kittykat** [comment]
You would need to write a new job which will live inside the triage-move-labelled.yml.

You can find [GitHub's documentation for actions](https://docs.github.com/en/actions) here and the best way to do it is probably to use the [graphql API](https://docs.github.com/en/graphql). If you are not familiar with the tools, then there is quite a lot to learn!

You should create a practice repository to try out the workflow and be confident in how it works before you submit a PR :+1:

**Comment by ankur12-1610** [comment]
> You would need to write a new job which will live inside the triage-move-labelled.yml.
> 
> You can find [GitHub's documentation for actions](https://docs.github.com/en/actions) here and the best way to do it is probably to use the [graphql API](https://docs.github.com/en/graphql). If you are not familiar with the tools, then there is quite a lot to learn!
> 
> You should create a practice repository to try out the workflow and be confident in how it works before you submit a PR +1

Thanks a lot :), I'll look into it.

**Comment by kittykat** [comment]
@ankur12-1610 how are you getting along with this?

**Comment by ankur12-1610** [comment]
> @ankur12-1610 how are you getting along with this?

Yeah I'm working on it, currently taking a look into graph API. 

I have a doubt there are so many labels starting with A, should I include all of them?

**Comment by kittykat** [comment]
@ankur12-1610 only the ones which are behind the labs flag. (You can have a look at Settings -> Labs on develop.element.io or Nightly.). Otherwise, I will get a list for you shortly.

**Comment by kittykat** [comment]
@ankur12-1610 
```
A-Maths
A-Message-Pinning
A-Threads
A-Polls
A-Location-Sharing
A-Message-Bubbles
Z-Maximised-Widgets
Z-IA
A-Themes-Custom
A-E2EE-Dehydration
A-Tags
```

**Comment by ankur12-1610** [comment]
> @ankur12-1610 
> ```
> A-Maths
> A-Message-Pinning
> A-Threads
> A-Polls
> A-Location-Sharing
> A-Message-Bubbles
> Z-Maximised-Widgets
> Z-IA
> A-Themes-Custom
> A-E2EE-Dehydration
> A-Tags
> ```

Thanks a lot @kittykat 😁, sorry for the delayed reply😅.

**Comment by ankur12-1610** [comment]
@kittykat I've raised the PR for this issue, kindly verify :)

**Comment by kittykat** [comment]
Thank you for submitting the PR, I've merged it now and verified that it works :tada:  If you are interested, I could point you at other workflow issues which we have in our backlog?

**Comment by ankur12-1610** [comment]
> Thank you for submitting the PR, I've merged it now and verified that it works :tada:  If you are interested, I could point you at other workflow issues which we have in our backlog?

Yeah sure, it really good of you :)
