### ISSUE TITLE
Slack Bridges can't be added in develop.element.io

### ISSUE THREAD

**Issue by markrosenbaum** [vector-im/element-web#20013]
### Steps to reproduce

1. Where are you starting? What can you see?
When trying to add a slack bridge on develop.element.io It throws an error.
2. What do you click?
When adding a slack bridge it fails when I try to link to a channel.
3. More steps…

#### What did you expect?
It just to link the slack channel.
#### What happened instead?
It throws the error "Failed to make link: Cannot read property 'users' of undefined"

### Operating system

ChromeOS

### Browser information

Chtome

### URL for webapp

develop.element.io

### Application version

Not Sure

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Half-Shot** [comment]
This was https://github.com/vector-im/element-web/issues/19845, which I believe is fixed in develop?

**Comment by t3chguy** [comment]
> > Application version
> Not Sure

Please specify the application version from Settings > Help & About

**Comment by markrosenbaum** [comment]
Yep, sorry.  When retrying on an updated version it works.  Thanks for the help.
