### ISSUE TITLE
Order of events after a federation outage is confusing

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20024]
![image](https://user-images.githubusercontent.com/31655082/144564835-90636d5a-6056-4230-8407-876757a6754c.png)

### Steps to reproduce

1. The server was down for a few hours.

#### What did you expect?
Eventual consistency
#### What happened instead?
The timeline showing on one server is not the same as the other server.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

https://app.element.io, chat.chagai.website

### Application version

Element version: 1.9.5 Olm version: 3.2.3, Element Chagai version: v1.8.5 Olm version: 3.2.3

### Homeserver

matrix.org, chagai.website

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The timeline content & order is provided by the server. During server outages, old messages may come down /sync as new ones and the client has no way to tell them apart.

**Comment by chagai95** [comment]
So if I understood correctly it's a server issue, closing it here

**Comment by chagai95** [comment]
> Unsure if there's enough information or not for the clients to mark them reliably and consistently — would need a client dev's perspective on whether we ought to think about a clearer way to tell clients about this case (which would need protocol changes/specification work).

**Comment by MadLittleMods** [comment]
Related to:

 - https://github.com/vector-im/element-web/issues/3153
 - https://github.com/vector-im/element-web/issues/1173

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/1456
