### ISSUE TITLE
User DM notification badge shows up under "rooms" in an unrelated space

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20022]
### Steps to reproduce

(Unknown, will send rageshake instead)

#### What did you expect?

User DM notification badges to stay under "home".

#### What happened instead?

![image](https://user-images.githubusercontent.com/22740616/144494990-26c136d2-55b5-457e-aae7-43953a2c344e.png)
![image](https://user-images.githubusercontent.com/22740616/144495007-addf0cf8-6232-433e-9701-08f117058e4a.png)

### Operating system

PopOS Linux, 21.04

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
Are you still experiencing this issue?

**Comment by ShadowJonathan** [comment]
Just tested, seems like i do not have this problem anymore.
