### ISSUE TITLE
develop.element.io not updating after clicking update

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#20033]
### Steps to reproduce

1. Log into develop.element.io
2. Use it for a bit and wait for new stuff to land and/or for element to check for new changes
3. Click the update button

#### What did you expect?

After the tab reloads the Element Web version is using the latest commits from the element-web, matrix-js-sdk and matrix-react-sdk repos.

#### What happened instead?

The version string shows that it's stuck at old commits (my current version is `f496d6d5bf31-react-4a6d46b76adc-js-87b920698f4c`) and changes introduced by new changes are missing.

After discussing this in internal rooms, it looks like this is caused by requests to anything under `https://develop.element.io/` getting responded to with a `cache-control: max-age=691200` header, whereas that header should be `cache-control: no-cache` to prevent any caching.

Not sending logs because that's not an issue with the app itself but with the web server(s) involved in delivering it.

### Operating system

Arch Linux

### Browser information

Firefox 93.0

### URL for webapp

develop.element.io

### Application version

f496d6d5bf31-react-4a6d46b76adc-js-87b920698f4c

### Homeserver

element.io

### Will you send logs?

No

**Comment by novocaine** [comment]
There may have been a misunderstanding about the headers.

```
 curl -v https://develop.element.io > /dev/null

..

< HTTP/2 200
< date: Sun, 05 Dec 2021 22:25:15 GMT
< content-type: text/html
< last-modified: Fri, 03 Dec 2021 14:15:48 GMT
< vary: Accept-Encoding
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-frame-options: sameorigin
< cache-control: no-cache
```

This is correct. Do you get a different result?

Note that the resources - .css and .js files - have `max-age` set, which is by design; their paths contain a bundle ID which changes with the un-cached root page. The key thing to inspect is the request to `https://develop.element.io` and whether that's being fetched from disk, or whether its coming over the network.

**Comment by babolivier** [comment]
Looks like I get the right headers with curl:

```
[10:07:27] babolivier@Noah:~$  curlie https://develop.element.io > /dev/null
HTTP/2 200 
date: Mon, 06 Dec 2021 10:08:08 GMT
content-type: text/html
last-modified: Mon, 06 Dec 2021 10:02:53 GMT
vary: Accept-Encoding
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: sameorigin
cache-control: no-cache
permissions-policy: interest-cohort=()
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=mYODatz7oXOu4xeg8mdmbi0zT2KuYvkEY4j3Z9vcjfPs9Bg5OrefCW65gdV6R9ZpPh2j%2FHTVVIQ1s%2B2VegoXsrz64lDhrkBa2gJagFyFUlouTjQqT8fGg3muSdtnfpC1sHVUPMnrWZ4z7fms1jAN3Q%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6b94b616ea1271ae-LHR
```

However, for some reason Firefox seems to disagree:

![image](https://user-images.githubusercontent.com/5547783/144827689-c3c6fadd-e5fb-4fba-9286-7b3288a5ae92.png)

**Comment by novocaine** [comment]
that's .. really bizarre.

can you try right clicking on the network request and copying as curl and running that?

I guess the obvious difference its its http2 from firefox .. I wonder if Cloudflare is up to something

![Screenshot 2021-12-06 at 21 28 23](https://user-images.githubusercontent.com/57377/144830410-2e68109d-1000-4549-8f1a-a78fc21939a0.png)

**Comment by babolivier** [comment]
Indeed, that's returning a different header:

```
[10:10:15] babolivier@Noah:~$ curlie 'https://develop.element.io/?#/room/#matrix-internal:matrix.org' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-GB,en;q=0.8,fr-FR;q=0.5,en-US;q=0.3' --compressed -H 'DNT: 1' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: same-origin' -H 'Connection: keep-alive' -H 'Cookie: [REDACTED]' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' > /dev/null
HTTP/2 200 
date: Mon, 06 Dec 2021 10:34:25 GMT
content-type: text/html
last-modified: Mon, 06 Dec 2021 10:28:52 GMT
vary: Accept-Encoding
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: sameorigin
cache-control: max-age=691200
permissions-policy: interest-cohort=()
cf-cache-status: MISS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=IQaRKvjvbiQyAS%2Bwe6sS%2FyhYPLHyk4eOrsPcEUQmI8zKAPYYO4cYVth1UzSzIJ7%2FyqCkB7HVqoIhaLWzeiCgSMYhOJezld65B02ZgGsrd5SaOFakEZ%2FMNWbiXr61V0P0%2BBNeqNhUuXvYCkwYdgMUFw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6b94dc9329be71c9-LHR
content-encoding: br
```

I've redacted the cookies in case they contain sensitive secrets, but removing them from the curl doesn't change the `cache-control` header in the response.

I'll try to tweak the line to see what makes that value change.

**Comment by babolivier** [comment]
Right, it looks like in some cases the browser tries to request `https://develop.element.io/#/...` and other times `https://develop.element.io/?#/...` (notice the question mark). The `cache-control` header has the wrong value in the latter case but not the former.

**Comment by novocaine** [comment]
aha! okay, great find - I think we'll have to adjust the rule in Apache slightly then.

**Comment by babolivier** [comment]
fwiw it looks like the root issue here is that something at some point caused Element to update the current URL of the tab with a question mark, which just stuck around. Looks like I managed to fix things by removing the `?` from the URL in the address bar.

**Comment by t3chguy** [comment]
This also applies to staging.element.io - https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$cHj7WJ38ET2sEaEZaplNHM_Wj68GEzvlxwubV0qMEqM?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by ilmari** [comment]
I don't have a question mark in my staging.element.io URL, but when I hit update just now, a lot of the responses were cached, including the initial request. The request headers according to the Firefox network inspector were:

```
GET /#/room/#element-web:matrix.org HTTP/2
Host: staging.element.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-GB,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Upgrade-Insecure-Requests: 1
Connection: keep-alive
If-Modified-Since: Wed, 01 Dec 2021 11:53:16 GMT
Cache-Control: max-age=0
TE: Trailers
```
and the response had:

```
HTTP/2 304 Not Modified
date: Mon, 06 Dec 2021 11:03:06 GMT
etag: "1bc4-5d21451bbe300"
cache-control: no-cache
permissions-policy: interest-cohort=()
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=bpWrnSkW7pn69LyU9O0m9a532paj2CqTNh9Wcd8%2BGBRQNOSkIrKgNWRb6N1lMtIb1hjcgdUQNgnZbDPLZwuLctds%2F0ogp1hiYCRXG99nZLwdwQTt0ZSbLmJ0SmedSOGLwrrfJPCZwstOy2k62pl6CA%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6b95069bc8b17747-LHR
X-Firefox-Spdy: h2
```

**Comment by ilmari** [comment]
Doing a force-reload (`Ctrl-Shift-R`) resulted in this request:

```
GET /#/room/#element-web:matrix.org HTTP/2
Host: staging.element.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-GB,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
```
And this response:
```
HTTP/2 200 OK
date: Mon, 06 Dec 2021 11:11:54 GMT
content-type: text/html
last-modified: Wed, 01 Dec 2021 11:53:16 GMT
vary: Accept-Encoding
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: sameorigin
cache-control: no-cache
permissions-policy: interest-cohort=()
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=uRoMbm5CM9Am6ujwB00%2FtlEJyyntAbj5FVGIEouXAYz3cBIM9QaFITJ1IGg1mmj%2FhBEtfFdoLsB8hSmsLk61i0IiXPvxKDtIpB7NikmJcsE08UOYc1%2F0Bk6kGIqArbxCvRYXL1WRoE5RbQCQXq4t8w%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6b95137bdf957777-LHR
content-encoding: br
X-Firefox-Spdy: h2
```

**Comment by ilmari** [comment]
Clicking "Check for update" in the "Help & About" dialog says an updated version is available even after the force-reload, and even though the version in the response matches what is showing in the about dialog (1.9.6-rc.2)

The request headers were:
```
GET /version?cachebuster=1638789283641 HTTP/2
Host: staging.element.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: */*
Accept-Language: en-GB,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
TE: Trailers
```
and response was:
```
HTTP/2 200 OK
date: Mon, 06 Dec 2021 11:14:44 GMT
content-type: text/html
last-modified: Wed, 01 Dec 2021 11:53:16 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: sameorigin
permissions-policy: interest-cohort=()
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5Hp1edU7Q%2BKsMk62MNcLR6d1TVtIlN7kKzphMpC3RWVFKYDEmV%2BFFBmYuco0gUMk269dlbkraizp7hrMT4MFZvvn3UBEkBW7DOZlF0%2BZdtEYGPiIvRIC1Gks68%2B%2BCqM9bY294VytqeFTZtCvTmiMXw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6b95179eccb07777-LHR
content-encoding: br
X-Firefox-Spdy: h2

1.9.6-rc.2
```

**Comment by novocaine** [comment]
> I don't have a question mark in my staging.element.io URL, but when I hit update just now, a lot of the responses were cached, including the initial request. The request headers according to the Firefox network inspector were:
> 
> ```
> GET /#/room/#element-web:matrix.org HTTP/2
> Host: staging.element.io
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Accept-Language: en-GB,en-US;q=0.7,en;q=0.3
> Accept-Encoding: gzip, deflate, br
> DNT: 1
> Upgrade-Insecure-Requests: 1
> Connection: keep-alive
> If-Modified-Since: Wed, 01 Dec 2021 11:53:16 GMT
> Cache-Control: max-age=0
> TE: Trailers
> ```
> 
> and the response had:
> 
> ```
> HTTP/2 304 Not Modified
> date: Mon, 06 Dec 2021 11:03:06 GMT
> etag: "1bc4-5d21451bbe300"
> cache-control: no-cache
> permissions-policy: interest-cohort=()
> cf-cache-status: DYNAMIC
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=bpWrnSkW7pn69LyU9O0m9a532paj2CqTNh9Wcd8%2BGBRQNOSkIrKgNWRb6N1lMtIb1hjcgdUQNgnZbDPLZwuLctds%2F0ogp1hiYCRXG99nZLwdwQTt0ZSbLmJ0SmedSOGLwrrfJPCZwstOy2k62pl6CA%3D%3D"}],"group":"cf-nel","max_age":604800}
> nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> server: cloudflare
> cf-ray: 6b95069bc8b17747-LHR
> X-Firefox-Spdy: h2
> ```

This looks like the correct behaviour at least in terms of how the requests are behaving `cache-control: no-cache` is set; your browser is revalidating its cached copy and receiving a 304 indicating no change has occurred.

**Comment by novocaine** [comment]
> Clicking "Check for update" in the "Help & About" dialog says an updated version is available even after the force-reload, and even though the version in the response matches what is showing in the about dialog (1.9.6-rc.2)
> 
> The request headers were:
> 
> ```
> GET /version?cachebuster=1638789283641 HTTP/2
> Host: staging.element.io
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
> Accept: */*
> Accept-Language: en-GB,en-US;q=0.7,en;q=0.3
> Accept-Encoding: gzip, deflate, br
> DNT: 1
> Connection: keep-alive
> TE: Trailers
> ```
> 
> and response was:
> 
> ```
> HTTP/2 200 OK
> date: Mon, 06 Dec 2021 11:14:44 GMT
> content-type: text/html
> last-modified: Wed, 01 Dec 2021 11:53:16 GMT
> x-xss-protection: 1; mode=block
> x-content-type-options: nosniff
> strict-transport-security: max-age=31536000; includeSubDomains; preload
> x-frame-options: sameorigin
> permissions-policy: interest-cohort=()
> cf-cache-status: DYNAMIC
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5Hp1edU7Q%2BKsMk62MNcLR6d1TVtIlN7kKzphMpC3RWVFKYDEmV%2BFFBmYuco0gUMk269dlbkraizp7hrMT4MFZvvn3UBEkBW7DOZlF0%2BZdtEYGPiIvRIC1Gks68%2B%2BCqM9bY294VytqeFTZtCvTmiMXw%3D%3D"}],"group":"cf-nel","max_age":604800}
> nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> server: cloudflare
> cf-ray: 6b95179eccb07777-LHR
> content-encoding: br
> X-Firefox-Spdy: h2
> 
> 1.9.6-rc.2
> ```

Indeed, I can repro this on staging - I think this is a regression caused by https://github.com/vector-im/element-web/pull/19857

**Comment by michaelkaye** [comment]
I think there's some overrides of the apache config (which is correct) in the cloudflare config, which is manifesting itself with develop.element.io/ and develop.element.io/? acting differently, despite the apache config treating them the same.

**Comment by michaelkaye** [comment]
staging.element.io doesn't have the same cloudflare config, and I believe is working properly.

The 304 Not Modified in @ilmari 's examples are happening because the request is checking the server using the data in the `if-modified-since` header. So the request is revalidated, but the data is not retransmitted.

If the file had changed you'd be getting a 200 with new content instead of the 304 not modified - it'll always check with the server.
