### ISSUE TITLE
Did not get a notification when someone reacted to my thread response

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20036]
### Steps to reproduce

1. User1 responds in a thread
2. User2 reacts to threaded post in 1
3. User1 does not see a notification on Web (notification shown as usual on Android)

#### What did you expect?
A notification

#### What happened instead?
No notification

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 1a403a37f93b-react-961fec90812a-js-ba1b1cc6fa86 Olm version: 3.2.3

### Will you send logs?

No

**Comment by t3chguy** [comment]
Depends on your push rule but it wouldn't pivot on whether it's a reaction to your message in any case (default no for all reactions)

**Comment by gsouquet** [comment]
@kittykat would you be able to retest this? After the changes I have made around notifications and the unread counter I believe you should get accurate notifications and bings.

I am not able to reproduce this one as we speak

**Comment by kittykat** [comment]
During re-testing with Germain, I found that a reply to a thread in an encrypted room did not cause an audio notification, nor a system notification. A reply to a thread in an unencrypted room did cause an audio notification, but did not cause a system notification.
