### ISSUE TITLE
Problem if too large server desynchronization.

### ISSUE THREAD

**Issue by epannekoucke** [vector-im/element-web#20034]
### Steps to reproduce

It seems that we have a problem with Synapse when the server that hosts it has suffered a too big desynchronization in terms of the time and date of the machine. (ex: year 2250)

This problem causes enormous slowness.

#### What did you expect?
It shouldn't cause such high latency.

### Operating system

server hosted on CentOS 7

### Browser information

*

### URL for webapp

Version 1.7.29

### Homeserver

ceo-vision.com

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This should be filed at https://github.com/matrix-org/synapse, could you please file it there?
