### ISSUE TITLE
hangup button on PIP video call has illegible tooltip

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20038]
as it's so narrow each character linewraps...

**Comment by ara4n** [comment]
<img width="331" alt="Screenshot 2022-01-04 at 11 57 27" src="https://user-images.githubusercontent.com/1294269/148055684-d6bde844-9875-4798-8452-0edf827650a3.png">

this is really ugly - especially for video, where the tooltip becomes one character wide.

**Comment by gsouquet** [comment]
It looks like this issue has been resolved, I can not reproducing it anymore.

@ara4n could you confirm that's been resolved on your side too? if not, a couple of extra details regarding your setup would be appreciated to help us reproduce this problem

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
