### ISSUE TITLE
Indonesian translation isn't available to choose

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20030]
The Indonesian translation is 100% done (https://translate.element.io/projects/element-web/matrix-react-sdk/id/), but there's no option to use the Indonesian translation in the settings

**Comment by t3chguy** [comment]
You can open a pull request similar to https://github.com/vector-im/element-web/pull/20029 to get it enabled for the subsequent release cycle

**Comment by Linerly** [comment]
https://github.com/vector-im/element-web/pull/20032
