### ISSUE TITLE
"Some of your messages have not been sent" reported when the message has been sent

### ISSUE THREAD

**Issue by bjherbison** [vector-im/element-web#20042]
### Steps to reproduce

1. Make a comment.
2. Close the tab.
3. Come back later and visit the site.

#### What did you expect?

Nothing unusual.

#### What happened instead?

There was a message:
Some of your messages have not been sent
You can select all or individual messages to retry or delete

Looking back in the history the message had been sent and responded to. I visited the room from another account through a different homeserver and the message and reply were in the room history.
![Screenshot 2021-12-04 at 13-55-09 Element  4  Mozilla General](https://user-images.githubusercontent.com/4101902/144721319-f306eb6f-dbd5-43f0-a3b9-a9cbb58e7d31.png)
![Screenshot 2021-12-04 at 13-56-50 Element  4  Mozilla General](https://user-images.githubusercontent.com/4101902/144721339-31edf8d8-dd8b-428f-9b9a-d63ad6051833.png)

### Operating system

Ubuntu

### Browser information

Firefox Nightly 96

### URL for webapp

https://chat.mozilla.org/#/room/#general:mozilla.org

### Application version

Element version: v1.9.5 Olm version: 3.2.3

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Is it possible that you have sent a reaction and that didn't get sent?

**Comment by bjherbison** [comment]
Looking back at the thread I see nothing I would have reacted to (related to the exchange marked "unsent" or anything else in the area). I use reactions in specific situations but I'm not one to make lots of spontaneous reactions.

Is it possible I closed the window before my browser received confirmation that my message had been sent?

**Comment by SimonBrandner** [comment]
> Is it possible I closed the window before my browser received confirmation that my message had been sent?

Yeah, I think so

**Comment by Pfiver** [comment]
I have the same issue. In a private Room (2person direct messages). I have tried leaving and re-joining the room. Even deleted all cookies and "website data" in the browser and restored the PKs from my other device.

On the other device (Android phone app), in the same account, everything works. On the other end (on an Android tablet app), everything works. I can even send messages from the tablet to the browser and make a call. But the browser refuses to send to that room. It sends to other rooms. But not this one. No matter how often I leave and re-join by invite.I would love to keep the room history, that's why haven't given up yet and just created a new conversation room.

**Comment by Pfiver** [comment]
Works again for me after today's update.

Element version: 1.9.8
Olm version: 3.2.8

To who ever it may concern: Thanks a lot for fixing it! :-)

**Comment by SimonBrandner** [comment]
@bjherbison, is this fixed for you as well?

**Comment by bjherbison** [comment]
I don't know how to tell if it is fixed. I haven't seen it recently, but it was never common.

As I mentioned [above](https://github.com/vector-im/element-web/issues/20042#issuecomment-986202865), I wonder if this is caused when I make a message and close the window soon after so notification is received by the browser that the message was sent. Was that situation checked and fixed if necessary?

**Comment by bjherbison** [comment]
(Note to self: When commenting on an issue, don't ask a question you can answer yourself.)
I just edited a message on https://chat.mozilla.org/#/room/#testing:mozilla.org , pressed Save, and closed the tab. When I returned to the site the edit had successfully been made but I have the message "Some of your messages have not been sent".

**Comment by Pfiver** [comment]
After actually reading the description ("Steps to reproduce") in the description carefully, I actually think that the issue I had observed was mostly related to this one. Sorry for the noise!

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21615 pending more information.

**Comment by antokhio** [comment]
just fell this with:
```
Error leaving room
MatrixError: [403] Event $4HcXU57lgPrTYH1V-Fp6GLKRenQeqkIftIcSX5Jq7AY has duplicate auth_events for ('m.room.member', '@#####:matrix.org'): $QAJqPN1WZWNSpc2tMuRNMANmT9dFpVkNrb_UKa-09vE and $TEtue0dOaiPMBR0Trg8kPsXeIOCC4MK92K-hvQ40EQ8 (https://matrix-client.matrix.org/_matrix/client/v3/rooms/!TBQqTlhFuOgIVtjUbt%3Amatrix.org/leave)
```

**Comment by t3chguy** [comment]
@antokhio that sounds like https://github.com/element-hq/synapse/issues/18606
