### ISSUE TITLE
New ctrl-k label makes click target for filter box too small in some cases

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#20041]
### Your use case

On develop.element.io, the new ctrl-K label takes up quite a bit of space on the room filter box and is not clickable. I use the most narrow room list configuration on a vertical monitor, and now the click target for the filter box is so tiny that it's hard to hit now:

![image](https://user-images.githubusercontent.com/41203525/144712560-85d98242-f5e0-4e36-90a3-403b045dcb19.png)

Some ideas to remedy this are either make the ctrl-k hint also clickable to focus on the filter box, get rid of it after the user does ctrl-k at least once, or hide it entirely once the room list is resized down to a certain amount.

**Comment by BurnyBoi** [comment]
CORRECTION: Just checked again and clicking the label does actually work now, so this issue is only cosmetic. My mistake.

**Comment by turt2live** [comment]
Considering the workaround suitable for this (it's clickable/click-through-able). Whether the room list should be allowed to be that narrow is a whole other discussion, but best placed in a new issue for consideration.
