### ISSUE TITLE
Always show all rooms from "People" group in "People" virtual Space

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#20048]
#### What would you like to do?
Always show all rooms from "People" group in "People" virtual Space without collapsing.

#### Why would you like to do it?
At now we have a separate virtual Space "People", that shows only rooms from "People" group, as it shown in "All rooms" mode.

But the problem is that in "All rooms" mode the "People" group in most cases is collapsed to show only several first items, to see next "Rooms" group too.

And the problem is that in the separate virtual Space "People" we see this "People" group collapsed too, so not all items but only few first items and "Show 777 more" link, and a lot of free vertical space after it.

#### How would you like to achieve it?
To solve this problem will be good to show all rooms, when user switches to "People" virtual Space, and maybe even without single "People" section at the top.

And same rule will be good for "Favorites" virtual space too.

**Comment by MurzNN** [comment]
Thanks for quick implementing! But seems it broke something, cuz now I see empty "People" group in sidebar:
![image](https://user-images.githubusercontent.com/336662/144849375-7187c5b3-8ca3-43ea-b467-420fbdb6f304.png)

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/144850251-b9458b4b-e1f5-4776-8c6e-7407478c8c43.png)

Cannot reproduce.

**Comment by Alvarus** [comment]
> Thanks for quick implementing! But seems it broke something, cuz now I see always empty "People" group in sidebar without ability to expand or collapse it: ![image](https://user-images.githubusercontent.com/336662/144849375-7187c5b3-8ca3-43ea-b467-420fbdb6f304.png)

I have the same effect on current develop.element.io web version. Both People and Favorites metaspaces show empty lists, but Other rooms show Fevorites and Rooms.

![Favorites](https://user-images.githubusercontent.com/3265956/144995735-d055db2d-f793-4f9f-922b-83880e5c2637.png)
![People](https://user-images.githubusercontent.com/3265956/144995754-8b7f1796-9879-47e0-978b-3f83561aff47.png)
![OtherRooms](https://user-images.githubusercontent.com/3265956/144995758-f16996d5-6590-4426-8b97-9b925622c04e.png)

**Comment by t3chguy** [comment]
Commenting on a closed issue won't get triaged.
