### ISSUE TITLE
Notification become not working

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#20050]
### Steps to reproduce

Some users report then element notification become not working around task bar

### Outcome

User want to return popup notification pop-up window

### Operating system

Windows 10 x64

### Application version

Element version: 1.9.5 Olm version: 3.2.3

### Will you send logs?

No

**Comment by gsouquet** [comment]
Could you please provide more information regarding the broken feature and steps to reproduce the problem?

I'm slightly unsure what is not working as expected after reading your report nor do I know what you'd consider a reasonable outcome

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/144811561-9586f87f-8880-403b-8c49-7b9b5265fda7.png)

**Comment by dm-msk** [comment]
The pop-up window not appear when message was received

**Comment by gsouquet** [comment]
But this appear to be working for you?
Could you maybe try to get those users to gather more information about their setup? There are a lot of OS level or Element settings that can determine whether those notifications are shown or not.

A rageshake from those users could also help unveil problems in the code

**Comment by dm-msk** [comment]
I've sent a log via user client. After approved session in security tab, the pop-up windows appear.

**Comment by dm-msk** [comment]
Same issue from another user. Log have been sent. Session is approved.

**Comment by dm-msk** [comment]
Maybe it it possible after every update icon hide from taskbar.
https://support.microsoft.com/en-us/windows/customize-the-taskbar-notification-area-e159e8d2-9ac5-b2bd-61c5-bb63c1d437c3

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/145007900-90ab5d7e-895e-4398-9285-71a03c6e0ead.png)

**Comment by dm-msk** [comment]
"Get notifications from apps and other senders" helped me

**Comment by gsouquet** [comment]
The issue that you are describing looks like it is an OS level setting that is not really related to Element. 
Can you confirm that after ticking this box things start to behave the way you expect them to?

**Comment by dm-msk** [comment]
All seems good. Thank you
