### ISSUE TITLE
Can't clear unread status for a room

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#20052]
### Steps to reproduce

Viewing the contents of a room isn't clearing its unread status; the room's name remains in bold. 

#### What did you expect?

When I click on the room in the left panel, for its title to be unbolded and marked as read.

#### What happened instead?

It stayed bold.

This might be linked to having a a thread in that room. I don't really want to post a screenshot of the content here; DM me for details.

### Operating system

OS X

### Application version

Element Nightly version: 2021120601 Olm version: 3.2.3

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
I've had the same, found that I have to open all threads to clear the notifications in those too
