### ISSUE TITLE
labs panel doesn't seem to work

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#20053]
### Steps to reproduce

1. Open settings panel
2. Click "Labs"

#### What did you expect?

labs settings panel

#### What happened instead?

settings dialog disappears

https://user-images.githubusercontent.com/1389908/144835896-a0364e89-4ab9-445c-9a11-16f04b5f462f.mp4

### Operating system

ubuntu 20.04

### Application version

Element Nightly version: 2021120601 Olm version: 3.2.3

### How did you install the app?

nightly debian

### Homeserver

sw1v.org

### Will you send logs?

Yes

**Comment by richvdh** [comment]
```
Uncaught TypeError: Cannot read property 'push' of undefined
    at LabsUserSettingsTab.render (LabsUserSettingsTab.tsx:104)
```

where line 104 looks like

```js
            groups.get(LabGroup.Analytics).push(
```

**Comment by SimonBrandner** [comment]
@t3chguy, am I assuming correctly this was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7290?

**Comment by t3chguy** [comment]
Yup
