### ISSUE TITLE
Missing "send attachment" label in narrow composer dropdown

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-web#20067]
### Steps to reproduce

1. Reduce the width of the app until the icons at the right hand side of the composer switch to show the 'meatballs menu'.
2. Click on the meatballs menu icon

![Screenshot 2021-12-06 at 14 54 26](https://user-images.githubusercontent.com/87766619/144868055-efec5f38-d5db-4915-98bc-723fc8b6811d.png)

#### What did you expect?
1. All icons that are in the composer should appear in this menu
2. Either all icons should not have text descriptions, or all icons should have text descriptions - for consistency

#### What happened instead?
1. The attachments icon does not have text next to it, unlike the other two
2. Voice messages is missing 
3. Polls is also missing, if this is enabled in labs

### Operating system

MacOS

### Application version

Element Nightly Version 2021120601

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Voice messages is missing

This is https://github.com/vector-im/element-web/issues/19361

The other two issues are fixed by the related PR. This only affected Polls Labs users.
