### ISSUE TITLE
Trying to share location results in "Something went wrong!"

### ISSUE THREAD

**Issue by witchent** [vector-im/element-web#20066]
### Steps to reproduce

1. I activate location sharing from labs, enter a room and click on the location icon next to the composer.
2. The chat vanishes and instead I am greeted by a "Something went wrong!" screen.
3. This happens even when I create a new room without encryption and try the same there.

This might have something to do with my addons or using arkenfox/user.js. I will try to find out if this is true as soon as I got the time, but I wanted to create this anyway in case someone already knows the answer.

#### What did you expect?
Being able to share my location.

#### What happened instead?
I got a "Something went wrong!" screen.

### Operating system

Arch Linux

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 60788da1a36d-react-9bcb82d6dcb9-js-15d05cd92f44

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2021-12-06T14:52:32.300Z E this.geolocate is undefined
componentWillUnmount@https://develop.element.io/bundles/fb839a8854287e443239/init.js:158700:5
bj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53067:493
cj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53073:296
bj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53068:38
cj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53073:296
dk@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53099:470
exports.unstable_runWithPriority@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53207:343
gg@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52965:325
Uj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53095:281
Lj@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53086:373
jg/<@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52966:115
exports.unstable_runWithPriority@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53207:343
gg@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52965:325
jg@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52966:63
ig@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52965:428
Hb@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:53135:101
gd@https://develop.element.io/bundles/fb839a8854287e443239/vendors~init.js:52916:354
```

**Comment by t3chguy** [comment]
`2021-12-06T14:52:32.300Z E Failed to initialize WebGL` yeah so this does seem to be something likely caused by your addons/extensions

**Comment by witchent** [comment]
Yes, my bad, should have had a closer look.

For anyone in the future having the same problem: arkenfox/user.js disables WebGl. Enabling it (with a user override) makes it work.

Sorry for the troubling and thanks for helping me pinpoint this.

**Comment by t3chguy** [comment]
Still going to do some improvements so it shows an error rather than crashing everything

**Comment by ara4n** [comment]
thanks!
