### ISSUE TITLE
Resize-handles in left panel disappear

### ISSUE THREAD

**Issue by williamkray** [vector-im/element-web#20076]
### Steps to reproduce

1. Run docker container v1.9.6
2. Use resize handle to shrink a section (e.g. people)
3. Resize handle disappears

before:
![Screenshot_20211206152146](https://user-images.githubusercontent.com/8409433/144938720-f99500e7-4270-4e96-b41d-a1f663006a58.png)

after:
![Screenshot_20211206152403](https://user-images.githubusercontent.com/8409433/144938728-78126b6f-dd08-4d68-9371-c1b785b6f569.png)

I can't seem to get them back.

#### What did you expect?
Resize handle still exists

#### What happened instead?
it ceases to exist

### Operating system

arch linux

### Browser information

firefox 94.0.1 (64-bit)

### URL for webapp

app.mssj.me

### Application version

v1.9.6

### Homeserver

synapse.mssj.me

### Will you send logs?

Yes

**Comment by williamkray** [comment]
played with it a bit... seems like if i shrink a section just the right amount it will pop up with "show 5 more" or whatever, and the handle will still be visible... but if i shrink it not exactly the right amount, the handle will disappear under another element or something

**Comment by gsouquet** [comment]
I have dabbled a bit with the reproduction steps and haven't been able to reproduce it so far. There has been a bit of work in that area lately. Would you be able to test this on develop.element.io that has all the latest and greatest to confirm whether this is still happening for you or not?

**Comment by williamkray** [comment]
i have just confirmed it still happens on develop.element.io, and have recorded a video. you can watch the handle slide under another element several times, and because in the last instance i _do not_ release the mouse button in an "ideal" area, i am unable to recall the handle again after that:

https://user-images.githubusercontent.com/8409433/145048135-574d91c9-a3fa-4477-9da5-e42c712c3ad3.mp4

**Comment by t3chguy** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/pull/7191
