### ISSUE TITLE
Editing nested list changes formatting

### ISSUE THREAD

**Issue by renancleyson-dev** [vector-im/element-web#20073]
### Steps to reproduce

1. Send a message with a markdown nested list and some text before or after it
![WhatsApp Image 2021-12-06 at 15 35 01](https://user-images.githubusercontent.com/43624243/144902741-5278a976-c7b5-4199-b389-2fb628e545a1.jpeg)
2. Edit the message, just add or remove something on some list item
3. The formatting changes, there's more space between the items
![WhatsApp Image 2021-12-06 at 15 35 38](https://user-images.githubusercontent.com/43624243/144902861-c1539f4c-2dff-4310-a12d-b121b3df6021.jpeg)
4. Edit again
5. The formatting changes, the additional space is removed
![WhatsApp Image 2021-12-06 at 15 36 07](https://user-images.githubusercontent.com/43624243/144902928-f8761833-c550-4075-b670-899eaf117b9b.jpeg)
6. If you repeat the 2-5 steps, you will see that the formatting alternates between adding and removing space

#### What did you expect?
Editing list items don't add any space or change the formatting.
#### What happened instead?
Editing list items alternate the formatting between adding and removing space.

### Operating system

Ubuntu

### Browser information

Chrome Version 96.0.4664.45 (64-bit)

### URL for webapp

app.element.io

### Application version

element version: 1.9.6 olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Inspecting the DOM shows that the first list item text gets wrapped in a paragraph element.

There has been a list of PRs recently that could have regressed this (https://github.com/matrix-org/matrix-react-sdk/pull/7200, https://github.com/matrix-org/matrix-react-sdk/pull/7257, https://github.com/matrix-org/matrix-react-sdk/pull/7279)

<img width="400" alt="Screen Shot 2021-12-07 at 08 14 44" src="https://user-images.githubusercontent.com/769871/144984069-e9a3673f-6eed-4c47-8157-55884b5fd60c.png">
