### ISSUE TITLE
Favourites and People meta spaces have no content

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20070]
### Steps to reproduce

1. Enable Favourites and People meta spaces
2. Open the meta space
3. See no content under Favourites and People (see rooms under "Low priority")

#### What did you expect?
Meta spaces show the correct content

#### What happened instead?
No content in the People and Favourites sections:
![Screenshot from 2021-12-06 15-54-32](https://user-images.githubusercontent.com/51663/144878391-917beee9-dad0-4fec-9ab6-a409fa5556ce.png)

### Operating system

Arch Linux (64-bit)

### Browser information

Chromium 96.0.4664.45 (Official Build)

### URL for webapp

develop.element.io

### Application version

Element version: 60788da1a36d-react-2e5a6fc738c6-js-b7247fcedc4d Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ShadowJonathan** [comment]
Rageshake sent in https://github.com/vector-im/element-web/issues/20080

**Comment by t3chguy** [comment]
I can reproduce on my personal account

**Comment by t3chguy** [comment]
This is not reproducible in FF but is in Chromium

**Comment by ShadowJonathan** [comment]
I'm still getting this problem.

Element version: de9f427364e9-react-2b52e17a8065-js-72bc13eb395e
Olm version: 3.2.3

Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

**Comment by t3chguy** [comment]
HAH, the fix for another bug regressed this one.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7303

Annoyingly these are Chrome/FF differences, fixing one for Chrome breaks the other for FF

**Comment by t3chguy** [comment]
Actually, now it is worse (but more consistent) as it is broken in both Chrome & FF

**Comment by ShadowJonathan** [comment]
I think that people metaspaces shouldn't rely on the category drop downs, but show the rooms directly in those sidebars, cuz with categories it looks weird, maybe that could be the permanent fix for this.

**Comment by t3chguy** [comment]
But low priority and favourites still applies within the people metaspaces, so not having a header for the other list would be weird.
