### ISSUE TITLE
Docker image not picking up the correct runtime `VERSION` variable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20074]
![](https://t2l.io/_matrix/media/r0/download/matrix.org/GcIHDtGKvLRjvlFPxEQbByiF)

**Comment by turt2live** [comment]
note that this has the effect of causing eternal upgrade notifications - the docker image writes `/version` correctly, but clearly doesn't set `VERSION`, so spawns a loop of no-op updates.

**Comment by jaller94** [comment]
Also, the `/version` that gets written to Docker and is used for update checking uses the Git Tag, not `$VERSION`.

https://github.com/vector-im/element-web/blob/b3c5bb899bed14f3dbb6355960a98db42e04be47/scripts/docker-write-version.sh#L5

https://github.com/vector-im/element-web/blob/b3c5bb899bed14f3dbb6355960a98db42e04be47/scripts/docker-write-version.sh#L7

https://github.com/vector-im/element-web/blob/b3c5bb899bed14f3dbb6355960a98db42e04be47/scripts/docker-write-version.sh#L22

**Comment by novocaine** [comment]
> * [ ]  Also, the `/version` that gets written to Docker and is used for update checking uses the Git Tag, not `$VERSION`.

great spot, indeed this is not consistent with https://github.com/vector-im/element-web/blob/develop/scripts/package.sh#L24

**Comment by novocaine** [comment]
https://github.com/vector-im/element-web/pull/20077 fixes this in a way that restores the previous behaviour, $VERSION will go back to being automatically derived from git

**Comment by davidmehren** [comment]
Are you going to push a fixed 1.9.6 image to Docker Hub?
I rolled back to 1.9.5 yesterday, as users complained about the upgrade-loop.

**Comment by stoically** [comment]
Just leaving the keyword `!!UNSET!!` as text here so it's easier to find.

**Comment by davidmehren** [comment]
The updated image seems to have been pushed. I had to manually run `docker pull docker.io/vectorim/element-web:v1.9.6`, to get the new image.
