### ISSUE TITLE
Video thumbnails have become *massive*

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20072]
### Steps to reproduce

1. Where are you starting? What can you see?

Gil sent a screencap video, probably from Android.  I viewed it with 'large thumbnails' (i.e. the old behaviour before tiny thumbnails were added) configured.

#### What did you expect?

With 'large thumbnails' enabled, the video thumbnail and embedded video tag should be resized to fit within an 800x600px bounding box.

#### What happened instead?

Instead, the vertical bounding doesn't seem to have applied at all, resulting in a 800px wide but 1280px(?) high massive video thumbnail which is so big you can't view the whole video at a time.

<img width="998" alt="Screenshot 2021-12-06 at 16 15 27" src="https://user-images.githubusercontent.com/1294269/144881970-7c776ce1-e5af-4369-ba7e-b4f85935b398.png">

### Operating system

macOS 12.0.1 on M1

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment]
This continues to be a real mess:

<img width="1009" alt="Screenshot 2022-01-25 at 14 10 23" src="https://user-images.githubusercontent.com/1294269/150992451-2731e1dd-5ec1-4ac2-b44f-c6c2bf744f9d.png">

**Comment by robintown** [comment]
This is actually [not a regression](https://github.com/matrix-org/matrix-react-sdk/pull/6172)
