### ISSUE TITLE
SVGs break timeline layout

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20088]
### Steps to reproduce

1. (With message bubbles enabled) attach an SVG
2. Post a message

#### What did you expect?
See attached file in timeline

#### What happened instead?
The second message covers up the SVG attachment

![Screenshot from 2021-12-07 15-40-43](https://user-images.githubusercontent.com/51663/145064485-eda97371-569c-44d5-8675-80a1770c5890.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-38e5e94ee410-js-2206b80e65aa Olm version: 3.2.3

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
there are some more svg issues, e.g. #18526

one issue seems to be that in contrast to pixel based images, element/electron/chromium doesn't seem to have a proper sense of scale for vector images.

**Comment by justjanne** [comment]
I’ve created a few test files for this, with intrinsic sizes of 200×200, 2×2, and 0×0. I can reliably reproduce the issue with these files.

* [black circle](https://user-images.githubusercontent.com/3933349/162929734-d79c9777-fe01-4970-8201-b8f79fe08dee.svg)
* [black circle (sizeless)](https://user-images.githubusercontent.com/3933349/162929740-088c385a-46dc-456f-8a5f-3d6c26241eb6.svg)
* [black circle (tiny)](https://user-images.githubusercontent.com/3933349/162929741-3aedabba-ef59-4bbf-82dc-eef194caf67d.svg)
* [white circle](https://user-images.githubusercontent.com/3933349/162929768-4bd865e8-cf04-4eeb-ac6f-514324e2b954.svg)
* [white circle (sizeless)](https://user-images.githubusercontent.com/3933349/162929773-c7b05488-acc0-4567-912a-e560524653ad.svg)
* [white circle (tiny)](https://user-images.githubusercontent.com/3933349/162929779-e4990494-0244-4952-9de0-fd72e3483314.svg)

**Comment by justjanne** [comment]
It’s not just tiny SVGs, nor is it just with message bubbles. From my testing, all tiny images cause this, in all layouts:

* ![2×2 PNG in bubbles layout](https://user-images.githubusercontent.com/3933349/163380173-3977757f-e61a-48f7-93c9-159d553f8542.png)
* ![2×2 SVG in bubbles layout](https://user-images.githubusercontent.com/3933349/163380197-727568b3-9d84-414a-83f7-1040c0deecba.png)
* ![2×2 PNG in modern layout](https://user-images.githubusercontent.com/3933349/163380206-100dd1fa-087b-4bc7-aa7b-be859350a529.png)
* ![2×2 SVG in modern layout](https://user-images.githubusercontent.com/3933349/163380225-5cb74887-69a5-42c7-aae2-7cb66976e9e5.png)
