### ISSUE TITLE
Mapbox failed to initialise WebGL

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20086]
### Steps to reproduce

1. Enable location sharing in Labs
2. Click the location icon in the composer

#### What did you expect?
Pops up a popup where to select the location

#### What happened instead?
Something went wrong

### Operating system

Arch Linux

### Application version

Versi Element Nightly: 2021120701 Versi Olm: 3.2.3

### How did you install the app?

AUR

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
WebGL is failing

**Comment by t3chguy** [comment]
This was fixed for Element Desktop
