### ISSUE TITLE
Markdown expressible by underscores or asterisks after Links stopped working

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#20091]
### Steps to reproduce

1. Try sending this message: `Found another wikidata gem: According to https://www.wikidata.org/wiki/Q59209813 Fractal is a _FORK_ of Matrix... as well as being based on it. :D It uses the https://www.wikidata.org/wiki/Property:P144 property which describes forks :D not usage` (Using the original message as I am not sure what causes it. It may be markdown in the middle of 2 links but it may be something else as well?)

#### What did you expect?

`_FORK_` should get italic in the message

#### What happened instead?

`_FORK_` did not change and the underscores show up in the timeline

### Operating system

Windows 11

### Browser information

Firefox 94.0.2 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: b0abbfacd48b-react-97ee25126fb7-js-2206b80e65aa Version von Olm: 3.2.3

### Homeserver

nordgedanken.dev

### Will you send logs?

No

**Comment by MTRNord** [comment]
@tulir mentioned to me that this may be a regression of https://github.com/matrix-org/matrix-react-sdk/pull/7200

**Comment by tulir** [comment]
Simpler example that reproduces the issue: `https://example.com _foo_ bar`

Also, `https://example.com *test* _foo_` does something very weird

![image](https://user-images.githubusercontent.com/4224639/145126706-525b717a-46f1-4011-8254-9da96e294803.png)

**Comment by gsouquet** [comment]
Probably regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7200

**Comment by ShadowJonathan** [comment]
Same with room IDs;

https://github.com/vector-im/element-web/issues/20565#issuecomment-1013693995
