### ISSUE TITLE
Avatar preview doesn't update when re-uploading an image with the same name

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20098]
### Steps to reproduce

1. Create a PNG with a transparent background
2. Start creating a new space and upload PNG for the space image
3. Realise that you accidentally have a transparent background and generate a new PNG with the same name in the same location, overwriting the original PNG
4. Click on the image preview in the space creation dialog to upload new PNG and select it
5. See the preview not update

Can also be reproduced in user settings with the user avatar and room settings with the room avatar.

#### What did you expect?
Preview updates every time a new image is uploaded.

#### What happened instead?
Preview is not updated if the filename is the same. The correct image is uploaded if I proceed with space creation.

### Browser information

Chromium 96.0.4664.45

### URL for webapp

chat.fosdem.org
develop.element.io

### Application version

FOSDEM 2021 version: 1.9.6, Olm version: 3.2.3
Element version: b0abbfacd48b-react-697b5d28b3bf-js-72bc13eb395e, Olm version: 3.2.3

**Comment by t3chguy** [comment]
@kittykat is this specific to spaces? I'd imagine the same happens for user avatar & room avatar given the code is the same

**Comment by kittykat** [comment]
Verified that it's the same problem in user settings and room settings
