### ISSUE TITLE
Presence indicator in room header is not aligned with cutout

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20090]
### Steps to reproduce

1. Open a DM
2. Look at the other participant's presence indicator in the room header

### Outcome

![Screenshot 2021-12-07 at 15-50-17 Element kaneru](https://user-images.githubusercontent.com/48614497/145104152-2c7bdfdf-91e7-4aa4-94fd-7b5213bda2cd.png)

#### What did you expect?

The presence indicator should be aligned with the cutout.

#### What happened instead?

The presence indicator is too far up and to the left.

### Operating system

NixOS unstable

### Browser information

Firefox 94.0.2

### URL for webapp

develop.element.io

### Application version

Element version: b0abbfacd48b-react-97ee25126fb7-js-2206b80e65aa Olm version: 3.2.3

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an annoying one, DecoratedRoomAvatar takes a size param, but in reality can't be sized so naively because the cutout svg only fits for 32px sizing. Maybe we can size using a scale transformation instead.
