### ISSUE TITLE
accessibility issues

### ISSUE THREAD

**Issue by albertotirla** [vector-im/element-web#20099]
### Steps to reproduce

1. Where are you starting? What can you see?

most of it happens throughout the entirity of element, so app.element.io

2. What do you click?

I enter a room in most instances, however the bugs appear also in the rooms and spaces pannel

3. More steps…

just turn on a screen reader and enjoy

#### What did you expect?

I expect everything to work according to how screen readers should navigate an accessible website

#### What happened instead?

* with every assistive technology I tryed, the list of messages is only accessible if we use browse mode, virtual cursor for jaws users, etc.
Problem with this way of navigating is that the interface makes the carret move around eratically, sometimes preventing the user from reading the message when navigating very fast around the UI.
Possible solution, wrap the message in a listview item(`<li>...</li>`) that spawns the message options upon right-click or opening the context menu on the item
* ~~when I go to the spaces treeview and press on add a space, the button changes to cancel but there is no indication as to what to do next to actually complete the action.
If the information is at the bottom of the page, consider displaying a popup dialog containing all required controlls, with the usual close dialog buttons and sensitivity to the esc key as you're doing with other dialogs in some parts of the interface.
Alternatively, consider updating the aria live region with the fact that more info is at the bottom of the page or some other brief instruction of what to do, though the first option would be prefered.~~
* when a user sends a message, the assistive technology is made to repeate the same announcement for three or more times, causes might be improper use of the aria live regions. A possible fix would be to clear the content of such regions every about 200 ms.
* depending how many messages I scroll through, the actual focus of the web page might move. In that case, depending on the kind of UI component it's focused on, it begins to read it multiple times. Cause for this might be that the aria region is updated each time focus moves to a message. Solution, don't update the aria region unless it's necesary, a.k.a new messages, joined a room, left the room, private messages, replyes, etc.

### Operating system

windows and ubuntu

### Browser information

firefox(latest)

### URL for webapp

app.element.io

### Application version

Element version: 1.9.6 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9747

**Comment by fcnjd** [comment]
Thank you for creating this issue, because I also find all the mentioned points important for screenreader users. It would be great if Element could become a web-app that is accessible to everyone who wants to use it, without annoying pitholes in it.

**Comment by fcnjd** [comment]
Hello,
now more than a year has passed since this issue got reported, so I'd like to ask if there are any updates on this topic yet? For me personally, especially the first mentioned problem, that the messages can only be navigated using browse mode, is the biggest obstacle in using Element regularly with my screenreader, since it makes it rather difficult to navigate large chat history lists. I'd be looking forward to see improvements to this in the future!

**Comment by t3chguy** [comment]
Meta issues like this aren't super helpful, the issues are already tracked in issues like https://github.com/vector-im/element-web/issues/19665
