### ISSUE TITLE
Right click on a resizer opens context menu and triggers resizer

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#20105]
### Your use case

![Peek 2021-12-08 14-49](https://user-images.githubusercontent.com/10872136/145219781-528542e9-0c81-452b-a46f-caa0939d9e8d.gif)

#### What would you like to do?
When right clicking on a resizer, it shouldn't trigger both the context menu and the resizer.

#### Why would you like to do it?
In most cases I wanted just the context menu and was confused when the resizer started following my cursor.

#### How would you like to achieve it?
Alternatives:
1. Don't start the resizer's behaviour on any click but a main click. This is what I expect in a webapp.
2. Prevent the context menu from opening. This is what the XFCE window manager does for native window borders.

The button that was clicked can be tested with [`event.button`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button).

### Have you considered any alternatives?

Maybe the React Re-Resizer does this properly already?. Looks like we want(ed) to migrate to this. #15083

### Left sidebar is affected too
![Peek 2021-12-08 14-48](https://user-images.githubusercontent.com/10872136/145219753-b0e22e1c-6012-48ef-ae3e-b9b02b5b2250.gif)

### Right sidebar is affected too
![Peek 2021-12-08 14-49_2](https://user-images.githubusercontent.com/10872136/145220563-a252c7ec-254b-4fcf-8725-0d6dba731549.gif)

**Comment by SimonBrandner** [comment]
I don't think I can repro to this extent but the resizer probably shouldn't react to right-click

**Comment by yaya-usman** [comment]
@SimonBrandner @jaller94 i couldn't reproduce this issue, don't you think it should be closed?

**Comment by SimonBrandner** [comment]
> @SimonBrandner @jaller94 i couldn't reproduce this issue, don't you think it should be closed?

The resizer still reacts to right-click for me on Chrome (100.0.4896.60), so no, I wouldn't consider it completely fixed

**Comment by jaller94** [comment]
Looks like the fix https://github.com/matrix-org/matrix-react-sdk/pull/10546 got merged but the issue didn't get closed.

Just as a surprising side note (this is not the behaviour I expected): On XFCE/Linux, you can resize windows with both the primary and secondary mouse button. Only the tertiary (middle) muse button doesn't trigger the resizing.
