### ISSUE TITLE
Threaded message preview in timeline isn't updated

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20101]
### Steps to reproduce

1. Receive a new message notification
2. Open thread panel
3. See new message come in the thread panel
4. Timeline preview isn't updated with the latest message

#### What did you expect?
Timeline and right panel show the same most recent message

#### What happened instead?
Timeline shows the latest message in the thread as an older message

### Will you send logs?

No

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19615
