### ISSUE TITLE
Can't complete the "Encryption upgrade available" process

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#20119]
### Steps to reproduce

I have a problem on my matrix.org account with "Encryption upgrade available" toast - it appears on every login, when I click "Upgrade", it asks my security phrase. 

If I fill my security phrase right - modal dialog simply disappears (toast stays in place) and that's all. And I can repeat that situation multiple times, on this device with this or new session, and on new clear devices too...

When I fill my security phrase wrongly, it shows me the "Unable to access secret storage. Please verify that you entered the correct Security Phrase." warning, so the problem is not in the wrong security phrase.

#### What did you expect?
I expect to do some upgrade of my encryption to some better grade ;)

#### What happened instead?
Nothing happened.

### Operating system

Ubuntu

### Browser information

Firefox 94

### URL for webapp

develop.element.io

### Application version

Element version: 0a5adedbc12f-react-68ac5785770d-js-4e9fe8f53fd2 Olm version: 3.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MurzNN** [comment]
Here is console.log output:
```
Cross-signing private keys not found locally, but they are available in secret storage, reading storage and caching locally rageshake.ts:65:27
downloadKeys: already have all necessary keys rageshake.ts:65:27
Got cross-signing update event for user @Murz:matrix.org but no new cross-signing information found! rageshake.ts:65:27
Cross-signing ready rageshake.ts:65:27
Bootstrapping Secure Secret Storage rageshake.ts:65:27
Object { keyBackupInfo: undefined, setupNewKeyBackup: undefined, setupNewSecretStorage: undefined, storageExists: true, oldKeyInfo: {…} }
rageshake.ts:65:27
Secret storage exists rageshake.ts:65:27
Starting load of AsyncWrapper for modal rageshake.ts:65:27
Got session backup key from secret storage: caching rageshake.ts:65:27
Secure Secret Storage ready rageshake.ts:65:27
Not setting dehydration key: feature disabled rageshake.ts:65:27
```

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/22893 which has pictures 🤩
