### ISSUE TITLE
In version 1.9.6 the same problem

### ISSUE THREAD

**Issue by korneydanote2** [vector-im/element-web#20115]
In version 1.9.6 the same problem

1.9.6 - There is no button to view the list of participants
![tmp ifJTbNSPHP](https://user-images.githubusercontent.com/94513169/145356055-76d3d69e-dc41-4ad2-ad64-b5479e260783.png)

1.9.3 - The button is in place
![tmp nHi3xjv996](https://user-images.githubusercontent.com/94513169/145356250-e428ecc1-db0b-439d-9ede-350ff4bbd965.png)

@t3chguy Can you check, please?

_Originally posted by @korneydanote2 in https://github.com/vector-im/element-web/issues/19781#issuecomment-989600537_

**Comment by SimonBrandner** [comment]
I have re-opened https://github.com/vector-im/element-web/issues/19781
