### ISSUE TITLE
Update broke timeline/threads panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20111]
### Steps to reproduce

1. Have thread panel open
2. Draft a reply in the timeline to a message in room 1
2. Update to latest version
3. Submit reply in the timeline
4. Navigate to another room
5. Come back to room 1
6. See draft reply and quoted message in the timeline from 3
7. See draft reply and quoted message in the thread panel

#### What did you expect?
Once I sent the reply in step 4, to not see the draft again

#### What happened instead?
The draft reply is persistent in the timeline and thread panel

![Screenshot from 2021-12-09 10-13-44](https://user-images.githubusercontent.com/51663/145378260-7e5e8d2f-19de-473d-af61-bf8bbaee62d8.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: de9f427364e9-react-4712ae49b2ae-js-95e7a76ba966 Olm version: 3.2.3

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
So far cannot reproduce, same as @kittykat. 
Keeping this open as this bug appearance might be sporadic

**Comment by kittykat** [comment]
@gsouquet I think we can close this, I've not seen it recently (but also threads panel was broken for much of this time)

**Comment by gsouquet** [comment]
Fixed as part of https://github.com/vector-im/element-web/issues/20408
