### ISSUE TITLE
Room menu: same actions should have the same wording

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-web#20133]
|Top timeline menu|Menu from room list|
|-|-|
|<img width="473" alt="image" src="https://user-images.githubusercontent.com/3940906/145580670-42dee74d-ac51-47f5-a356-15329fc0da07.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/3940906/145580728-50cc441b-b889-434b-93b9-8cb243a8edfb.png">|

See the diff for invite/room link/leave

**Comment by niquewoodhouse** [comment]
**Copy suggestion:**

- Leave room = Leave (is used for both DMs and rooms)
- Copy Room Link = Copy room link (this option is only visible for rooms)
- Invite people = Invite (shorter for translations)
