### ISSUE TITLE
Sign out leads to "Something went wrong!" page.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#20136]
### Steps to reproduce

Be logged in to a server previously in that browser (matrix.org and a test server have both exhibited this). Close the window.

Come back by visiting app.element.io ; get taken to the home screen for the previously logged in user correctly.

Head into the menu and click log out. Don't otherwise interact with the app.

#### What did you expect?

Not to be asked to report a bug. maybe a "logged out" message, or the intial page again.

#### What happened instead?

"Something went wrong!" message.

Note on firefox I appear to be unable to send debug logging. On firefox this occurred when using a private browsing session.

### Operating system

Linux ubuntu

### Browser information

Firefox and Chrome

### URL for webapp

app.element.io

### Application version

1.9.6

### Homeserver

matrix.org and test server

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed on develop
