### ISSUE TITLE
ScalarMessaging action:invite doesn't successfully no-op if the user is already present in the room

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#20134]
Leading to integration managers failing to handle bridge requests. Additionally, the error thrown by `client.invite` should be checked to see if the HS reports the user as invited, rather than just exploding.

**Comment by t3chguy** [comment]
```
{"errcode":"M_FORBIDDEN","error":"@NickServ:libera.chat is already in the room."}
```

> Additionally, the error thrown by client.invite should be checked to see if the HS reports the user as invited, rather than just exploding.

`M_FORBIDDEN` is not specific enough to rely on for this, and parsing `error` would be tied to Synapse

**Comment by Half-Shot** [comment]
We really need a M_CONFLICT or similar
