### ISSUE TITLE
Can't view message edit history

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20137]
### Steps to reproduce

1. edit
2. click (edited)

#### What did you expect?
diff
#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/145598747-a8f9c3ab-016d-4637-84c6-b1ce19ca4867.png)

### Operating system

arch

### Application version

Element Nightly version: 2021121001 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
Without logs this cannot be investigated.

**Comment by HarHarLinks** [comment]
submitted rageshake

**Comment by t3chguy** [comment]
Thanks!
