### ISSUE TITLE
editing an escaped formatted message does not retain escaped characters

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20140]
### Steps to reproduce

1. send message prefixed with `/shrug`
2. edit message

#### What did you expect?
similar to `/rainbow`, put the original command in the composer. most importantly reproduce the original behaviour.
also, escape stuff properly when editing.

#### What happened instead?
content is placed into composer literally, `\` is interpreted as escape and gets lost

### Operating system

arch

### Application version

Element Nightly version: 2021121001 Olm version: 3.2.3

### How did you install the app?

aur

### Will you send logs?

No

**Comment by dbkr** [comment]
It's tempting to say that features like this should either have decent test coverage or be canned

**Comment by HarHarLinks** [comment]
I think the actual issue here is that editing + escaping markdown characters is not working/implemented

1. type an exscaped message
![image](https://user-images.githubusercontent.com/2803622/145826886-3bca66a8-0ee2-4d62-8b13-73a234c560cd.png)
2. result
![image](https://user-images.githubusercontent.com/2803622/145826920-1cfcad6b-5cc6-4acd-a67f-4978d5fa3565.png)
3. press edit, change nothing. notice the escape `\` are gone
![image](https://user-images.githubusercontent.com/2803622/145826939-4799bc87-5449-43eb-b814-f6131665ee19.png)
4. enter to save (despite the save button being deactiveated!!), result:
![image](https://user-images.githubusercontent.com/2803622/145826977-9bbd0d51-5cd4-435e-8069-5b8b70e23d5a.png)

**Comment by HarHarLinks** [comment]
however the special case of the `/shrug` command in relation to `/rainbow` as described in the OP, while fixed by proper escaping when editing, remains to be improved upon
