### ISSUE TITLE
Bad contrast in the typing text avatar

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#20144]
![typing](https://user-images.githubusercontent.com/47475676/145677667-1e14c705-87c5-412e-b209-0a6da2cc1701.png)

It's kinda unreadable on dark mode because of how thin the text is (and how the color is quite similar to the background)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
My opinion is that the colour is more problematic than the width of the text.

**Comment by Linerly** [comment]
Yep, that too as well
