### ISSUE TITLE
Pinned/Threaded polls do not show followups like votes

### ISSUE THREAD

**Issue by witchent** [vector-im/element-web#20152]
### Steps to reproduce

1. Create a poll
2. Vote for it
3. Pin the event
4. The votes are not accounted for the poll in the pinned panel

#### What did you expect?
Have votes for polls be shown in the pin panel

#### What happened instead?
Votes have not been accounted for

### Operating system

Arch Linux

### Browser information

Firefox 95

### URL for webapp

develop.element.io

### Application version

0744c86ac9b3-react-3b3776222b06-js-c0fbed914e45

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
Changed my mind on the prio, but going with minor since it has a workaround but frequent as it these seem like a likely combination (labs aside, but Z-labs encapsulates that).

**Comment by witchent** [comment]
Just out of interest, what is the workaround? Just go to the message in the timeline instead of looking at the pinned message?

**Comment by gsouquet** [comment]
Removing the threadd label as the issue is fixed there.
Also editing the original bug description

**Comment by HarHarLinks** [comment]
related? #20282

**Comment by gsouquet** [comment]
The underlying issue is the same but the resolution is slightly different
