### ISSUE TITLE
*:* does strange things in element.

### ISSUE THREAD

**Issue by Sleuth56** [vector-im/element-web#20170]
### Steps to reproduce

1. Send a message with `*:*` in it. Example `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * *:* -a`
2. Look at the message you sent. It will look like `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * : -a`
3. Attempt to edit that message `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * _:_ -a`
4. Notice that something is very wrong here. 
  * My original message had `*:*`
  * Looking at the message I sent I get ':' 
  * Editing the message I see `_:_`

Note, the message is actually sent correctly the first time even though element displays it wrong. Tested with an opsdroid bot that logged the message. 

If you save the edited version without changing anything it will send `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * _:_ -a`

#### What did you expect?
Element to send `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * *:* -a` without changing anything.

#### What happened instead?
Element send the message correctly but stores and displays it incorrectly.
* In Element text: `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * : -a`
* Edited text: `!announcement -n NAME-m <H1>HTML!</H1> -t *, 13 * * _:_ -a`

### Operating system

Manjaro

### Application version

Element Nightly version: 2021100501 Olm version: 3.2.3

### How did you install the app?

AUR

### Homeserver

NA

### Will you send logs?

Will if needed.

**Comment by Sleuth56** [comment]
This has something to do with the markdown parser. Markdown uses asterisk symbols to bold a word. However it's usually two asterisks on each side not one. And to my knowledge there isn't anything in markdown that uses one on each side. I don't think it's parsing this as a bullet list.

**Comment by t3chguy** [comment]
https://commonmark.org/help/ single `*` is italics.

**Comment by Sleuth56** [comment]
Your right. I thought it was only _ that did italics. Guess I have to change my format then.

**Comment by dbkr** [comment]
Yep, I think this is working as expected since it's translating the italics to underscore notation which is equivalent. `/plain <message>` would be a workaround
