### ISSUE TITLE
Spaces icon has weird outline in left left panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20186]
### Steps to reproduce

1. Click on a space so that space avatar is outlined with a black outline.

### Outcome

Odd pale outline between space avatar and emphasis outline:
![Screenshot from 2021-12-14 13-22-25](https://user-images.githubusercontent.com/51663/146014463-935fa567-35ac-4f85-ad9f-f9d36f83a678.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 705366ab8c7a-react-60286f617087-js-aeec4aa4a809 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
there's meant to be a 1px gap between the icon and the selected border, is that what you're referring to @kittykat?

**Comment by kittykat** [comment]
> there's meant to be a 1px gap between the icon and the selected border, is that what you're referring to @kittykat?

Yes, that's it

**Comment by niquewoodhouse** [comment]
Closing this issue because it's intentional and not a bug, thanks
