### ISSUE TITLE
If message editing is aborted, timeline jumps to newest

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20182]
### Steps to reproduce

1. Scroll up the timeline to an older message
2. Edit the message
3. Press Esc

#### What did you expect?
View to remain at the message which I started editing

#### What happened instead?
Timeline jumped to newest message

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: a90cbe9476e5-react-d00809b8b902-js-aeec4aa4a809 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
TBH, I don't think this is a regression

**Comment by t3chguy** [comment]
This is only on Esc, not on clicking Cancel
