### ISSUE TITLE
Scan this unique code - barcode not generated

### ISSUE THREAD

**Issue by stevepdp** [vector-im/element-web#20188]
### Steps to reproduce

I'm looking to verify my new Android session using Firefox.

1. On the phone, click "Verify this login".
2. On the browser, accept the invitation to verify.
3. On the phone, prepare the camera to scan the code.
4. On the desktop, code never generates and spins indefinitely.
5. Give up then verify using emoji instead.

Tested against staging on both devices.

#### What did you expect?

I expected to see an image of a barcode to scan.

#### What happened instead?

The spinner kept spinning and no image rendered.

### Operating system

Ubuntu 21.10

### Browser information

95.0 (64-bit) snap

### URL for webapp

https://staging.element.io

### Application version

Element version: 1.9.8-rc.1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stevepdp** [comment]
Unfortunately I've lost the /rageshake moment for this one.

See this screenshot also:  
![2021-12-14_17-56](https://user-images.githubusercontent.com/1271004/146055916-4232bcc6-a0ab-4e02-8a4d-434ccee6f74f.png)

**Comment by stevepdp** [comment]
Hi @t3chguy.

I have now performed a /rageshake. Hopefully the logs contain useful information. This event however occurred a while back so the information may be lost. Apologies.

With regards to sharing the browser console. I'm aware that Firefox generates it's own noise. I only share these things because I know that they sometimes contain something like a request error, which is what I assumed this to be.

Note that my Firefox installation in this case is fresh via Snap and doesn't have any extensions installed.

**Comment by kittykat** [comment]
I got a rageshake as well for the same issue, and I had this in the console log (I was testing on develop):

![Screenshot from 2021-12-14 19-08-10](https://user-images.githubusercontent.com/51663/146063926-d8397e32-642d-4133-853c-536460ae0142.png)

**Comment by t3chguy** [comment]
Upstream issue https://github.com/soldair/node-qrcode/issues/289
