### ISSUE TITLE
Room preamble doesn't include a date header

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20194]
So you have no way of telling what day a conversation started on, short of tooltipping over a timestamp which is an undiscoverable poweruser move

**Comment by dbkr** [comment]
I have 'today' at the top after starting a new room?
<img width="837" alt="Screenshot 2021-12-17 at 11 14 08" src="https://user-images.githubusercontent.com/986903/146536580-f3b17598-a20b-4fb3-8154-ecaa50302c33.png">

**Comment by robintown** [comment]
Closing due to lack of info
