### ISSUE TITLE
Export room stuck on "M_FORBIDDEN: Host not in room."

### ISSUE THREAD

**Issue by TheFrenchGhosty** [vector-im/element-web#20190]
### Steps to reproduce

1. Run an export on an old room (in my case the [Invidious](https://invidious.io/) room [#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org) )
2. Choose JSON and 4MB
3. Run an export, until it get stuck, looks at the console: 403

#### What did you expect?

Skips the 403, or just don't 403

#### What happened instead?
![this](https://user-images.githubusercontent.com/47571719/146059979-9df3e412-f85c-4a02-94d6-83387cf2911b.png)

Then stops.

If I restart the export again, it give a 403 instantly, however if I clear the cache of the client, it works, until this error happens again.

Note:

It's an old V1 room (from early 2019), we want to export it so that we can upgrade it while keeping a backup of the messages.

We did an HTML export with attachment an hour before without issue.

it's maybe a Synapse issue.

### Operating system

Debian

### Application version

1.9.7

### How did you install the app?

Official Element repository

### Homeserver

My own

### Will you send logs?

No

**Comment by t3chguy** [comment]
The 403 error is definitely a Synapse issue, you should be able to paginate the entire history unless you left & forgot the room.
The exporter should handle this better with a user-facing error however

**Comment by TheFrenchGhosty** [comment]
@t3chguy The thing is that the exports worked without issue with HTML... and I just tried again, and it failed again on the same event (event 62953). It definitely looks like a Synapse issue, can you transfer the issue or do I have to open a new one?

**Comment by TheFrenchGhosty** [comment]
And I just updated Synapse to 1.49.0, and now it 403 instantly, even after clearing Element's cache.

Something is really wrong.

**Comment by t3chguy** [comment]
It is not possible to transfer issues between organisations (vector-im vs matrix-org)

**Comment by TheFrenchGhosty** [comment]
@t3chguy Ah right, I didn't think of that.
