### ISSUE TITLE
Default notification noise physically harms myself and others & there's no way to change it.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20198]
#### What would you like to do?
At least have an option to change it, but the ideal option would be a different, better noise that doesn't cause physical pain, as it's a point of friction for many new users I invite to use the app.
#### Why would you like to do it?
Because it causes physical pain and harms myself and others.
#### How would you like to achieve it?
Changing the file to one which is less physically damaging.

### Have you considered any alternatives?

I would use another app if any apps were as issue rich as element. This issue forces me to just have notifications off at all times, which is not ideal.

**Comment by dbkr** [comment]
dup of https://github.com/vector-im/element-web/issues/5891
