### ISSUE TITLE
Crash on accessing security settings

### ISSUE THREAD

**Issue by gleachkr** [vector-im/element-web#20209]
### Steps to reproduce

1. Where are you starting? What can you see?

Broswer tab becomes unresponsive and needs to be killed

1. What do you click?

The issue seems to occur intermittently while looking at the security and privacy. It sometimes occurs after several seconds.

#### What did you expect?

Smooth sailing.

#### What happened instead?

Rough sailing. The console seems to be registering thousands of instances of the final "cannot read properties of null" in this sequence:

```
rageshake.ts:65 Starting load of AsyncWrapper for modal
rageshake.ts:65 Checking key backup status...
rageshake.ts:65 Ignoring signature from unknown key XXXXXXXXXXXXXXXX
rageshake.ts:65 Ignoring signature from unknown key XXXXXXXXXXXXXXXX
rageshake.ts:65 Backup version 1 still current
rageshake.ts:65 Error getting device cross-signing info TypeError: Cannot read properties of null (reading 'algorithms')
    at CrossSigning.ts:592
    at h.checkDeviceTrust (CrossSigning.ts:569)
    at r.isDeviceVerified (DevicesPanel.tsx:122)
    at render (DevicesPanel.tsx:304)
    at Ga (react-dom.production.min.js:187)
    at Ba (react-dom.production.min.js:186)
    at Gs (react-dom.production.min.js:269)
    at wc (react-dom.production.min.js:250)
    at Ec (react-dom.production.min.js:250)
    at yc (react-dom.production.min.js:250)
e.<computed> @ rageshake.ts:65
isDeviceVerified @ DevicesPanel.tsx:129
render @ DevicesPanel.tsx:304
Ga @ react-dom.production.min.js:187
Ba @ react-dom.production.min.js:186
Gs @ react-dom.production.min.js:269
wc @ react-dom.production.min.js:250
Ec @ react-dom.production.min.js:250
yc @ react-dom.production.min.js:250
hc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Hi @ react-dom.production.min.js:123
qi @ react-dom.production.min.js:122
sc @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonymous) @ DevicesPanel.tsx:74
```

### Operating system

Arch Linux

### Browser information

Chromium 96.0.4664.93

### URL for webapp

app.element.io

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
@gleachkr please submit a rageshake (send `/rageshake` from the console and link to this issue). I'm on the same setup as you and cannot reproduce the issue.

**Comment by gleachkr** [comment]
I'm not certain I can do that. I take it that you mean to send the `/rageshake` from the message input area? Once I trigger the issue, the browser tab becomes unresponsive and I can't navigate to the message input area. I could `/rageshake` *before* triggering the problem - would that help?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/146520137-a7f08e93-5f66-4912-90a1-8c34edf987b8.png)

![image](https://user-images.githubusercontent.com/2403652/146520182-aa87e55f-fa25-40d2-8a27-409f31307577.png)


Avatar -> Feedback -> debug logs

**Comment by t3chguy** [comment]
> I could /rageshake before triggering the problem - would that help?

No but rageshakes include logs from the past few sessions too, so hit the issue, refresh, then send logs please

**Comment by gleachkr** [comment]
Hey, so FWIW, here's some additional info.

1.  It kinda looks like the call to `getStoredDevice` [here](https://github.com/matrix-org/matrix-react-sdk/blob/8a0398b632dff1a5f6cfd4bf95d78854aeadc60e/src/components/views/settings/DevicesPanel.tsx#L120) is returning something that is breaking the call to `checkDeviceTrust` [here](https://github.com/matrix-org/matrix-react-sdk/blob/8a0398b632dff1a5f6cfd4bf95d78854aeadc60e/src/components/views/settings/DevicesPanel.tsx#L121). From the error, it looks like it might be returning null, but I haven't found a place where it could be doing that. There is a code path that returns undefined, not sure if this might somehow be converted to null during compilation.

2. I used my access token from element to hit the `_matrix/client/v3/devices/` endpoint, since that seemed somehow implicated in this bug. As it turns out, I have about 84M of registered devices, which I think is the result of using early versions of `matrix-weechat`. Most of these have no associated `display name`, and a few have nothing but a `device_id`. I think the time it takes to download this accounts for the delay before the crash occurs.

Should I try to delete the huge number of bad devices with a script or something?

**Comment by gleachkr** [comment]
I went ahead and deleted the approximately 600K bogus devices by using the `delete_devices` endpoint manually. Now everything seems to be fine, so I think I can confirm that the odd behavior has something to do with this. I'm not sure if there might still be an issue with handling devices that are represented by only a `device_id`, or of this issue was caused by the sheer number of devices.

**Comment by MadLittleMods** [comment]
Running into this now and it's reproducible every time in my current session: https://github.com/matrix-org/element-web-rageshakes/issues/16515 - The error specifically occurs when the devices load in on the **Security & Privacy** settings

Might be related to https://github.com/vector-im/element-web/issues/23636 since the error occurs when I open the **Security & Privacy** settings from the **Review** button on that toast.

**Comment by turt2live** [comment]
This is blowing up from https://github.com/matrix-org/matrix-js-sdk/blob/9f2f08dfd3de5cb28b5427ffdb3280573929abea/src/crypto/CrossSigning.ts#L568 (inside function call, where we access `device.algorithms`).

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/commit/a03438f2af0cf28bbed1b7abb11f6453ef8d3785
