### ISSUE TITLE
Spaces and Communities

### ISSUE THREAD

**Issue by Roman-S10** [vector-im/element-web#20201]
Regarding new features. Is it right that in the future electron will migrate from Community to Spaces?
Is the Community the feature that completely replace Spaces? Or will be awalible bouth features Community and  Spaces?

**Comment by kittykat** [comment]
Hi, please ask for support in [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org). This issue tracker is for tracking defects, enhancements and planned work.

Yes, it is intended for Spaces to replace Communities in the long term.
