### ISSUE TITLE
Security & Privacy dialog doesn't update after signing out of old sessons

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20203]
### Steps to reproduce

Prerequisites: signing in with a server account (not social login), must have multiple sessions logged in and must wait for password to time out so that it would need to be re-entered

1. Settings -> Security & Privacy
2. Select sessions under "Verified devices"
3. Sign out *n* selected devices
4. Type in password
  -> Spinner spins for about 5 minutes
5. Password dialog closes and same sessions can be seen as step 1

#### What did you expect?
Signed out sessions are removed from dialog

#### What happened instead?
Signed out sessions are visible until I navigate to a different tab and back

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 23b21c940c68-react-53081f52fb35-js-e4d3124e72ed Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by sahilsaini110** [comment]
@kittykat i would love to do this. may u assign this to me

**Comment by kittykat** [comment]
@sahilsaini110 Sure thing! Please keep in mind that this issue is time sensitive as it is a regression and should ideally be fixed in the next ~2 weeks.

**Comment by sahilsaini110** [comment]
@kittykat this is my first open-source contribution may you plz guide me a little.

**Comment by kittykat** [comment]
You can find instructions on how to build the app [here](https://github.com/vector-im/element-web#building-from-source) and more documentation [here](https://github.com/vector-im/element-web/tree/develop/docs).

When your PR is ready (well tested locally and you are confident that it is working reliably), then you should submit a PR and it will be reviewed by developers. When you submit a PR, it will go through some checks and your PR description will be updated with a netlify link which you should use to re-test your PR.

You can also submit a draft PR and mark it ready when you're done with the changes.

You can ask for more help in [#element-web:matrix.org](https://develop.element.io/#/room/#element-web:matrix.org), which is a public room. Most of our developers are on holiday for the next 1-2 weeks so replies may be slow. As with most F/LOSS projects, the expectation is that you always give things a try following documentation before you ask for help :+1:

**Comment by sahilsaini110** [comment]
> You can find instructions on how to build the app [here](https://github.com/vector-im/element-web#building-from-source) and more documentation [here](https://github.com/vector-im/element-web/tree/develop/docs).
> 
> When your PR is ready (well tested locally and you are confident that it is working reliably), then you should submit a PR and it will be reviewed by developers. When you submit a PR, it will go through some checks and your PR description will be updated with a netlify link which you should use to re-test your PR.
> 
> You can also submit a draft PR and mark it ready when you're done with the changes.
> 
> You can ask for more help in [#element-web:matrix.org](https://develop.element.io/#/room/#element-web:matrix.org), which is a public room. Most of our developers are on holiday for the next 1-2 weeks so replies may be slow. As with most F/LOSS projects, the expectation is that you always give things a try following documentation before you ask for help 👍

thanks

**Comment by sahilsaini110** [comment]
![Screenshot from 2021-12-24 11-40-01](https://user-images.githubusercontent.com/76941329/147323513-c67f7b19-4cf0-432e-be3b-32f70fa39887.png)
![Screenshot from 2021-12-24 11-39-58](https://user-images.githubusercontent.com/76941329/147323533-d0622b85-ac80-4d92-aaa3-6c6b2c8e3352.png)
![Screenshot from 2021-12-24 11-39-50](https://user-images.githubusercontent.com/76941329/147323540-9c8cab4f-040e-47ef-a410-2f7eb7ae6e9f.png)

@kittykat here i am unable to find the issue may u plz confirm i am going right.

**Comment by sahilsaini110** [comment]
![Screenshot from 2021-12-24 11-39-50](https://user-images.githubusercontent.com/76941329/147324026-721d96c1-6450-48c8-ac22-0d0cbdc14081.png)
![Screenshot from 2021-12-24 11-39-58](https://user-images.githubusercontent.com/76941329/147324029-e23bf17e-afa0-4010-850e-b1bbd144052e.png)
![Screenshot from 2021-12-24 11-40-01](https://user-images.githubusercontent.com/76941329/147324030-dc1048e7-7458-4f1e-8fe0-b9c2c428b5b3.png)

@kittykat  i am unable to find the bug still may u plz  tell me whats wrong in this

**Comment by kittykat** [comment]
@sahilsaini110 you need to be signed into other devices and you need to sign out of them to trigger it. You won't see the right UI with only one device

**Comment by sahilsaini110** [comment]
> @sahilsaini110 you need to be signed into other devices and you need to sign out of them to trigger it. You won't see the right UI with only one device

ok i try it

**Comment by sahilsaini110** [comment]
https://user-images.githubusercontent.com/76941329/147389032-ab5795a6-80cf-4daf-933d-ee42a035a11c.mp4

@kittykat  may you plz check this there is no such issue.

**Comment by kittykat** [comment]
@sahilsaini110 It looks like it's been fixed! Sorry the PR didn't get linked back to the issue.
