### ISSUE TITLE
matrix-react-sdk build fails on master branch with "Cannot find type definition file for 'request'"

### ISSUE THREAD

**Issue by tom-auger** [vector-im/element-web#20205]
### Steps to reproduce

```sh
$ git clone master https://github.com/matrix-org/matrix-react-sdk.git
$ cd matrix-react-sdk
$ yarn install && yarn build
```

#### What did you expect?
The build succeeds.

#### What happened instead?

The build errors out with: 
![image](https://user-images.githubusercontent.com/31711089/146177955-f9e8ecd5-0904-4342-b3af-38f5df848cec.png)

It builds fine on the develop branch. I was able to get it building on master by adding `@types/request` as a dev dependency: `yarn add @types/request --dev`. 

I also noticed that `release.sh` never builds matrix-react-sdk as there is no `dist` script for this package so this issue may never have been hit in CI.

### Operating system

Windows, Linux

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Request is long gone
