### ISSUE TITLE
Cannot log into matrix server from private browsing mode in Chromium

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20218]
### Steps to reproduce

1. https://develop.element.io/#/login in private browsing mode (this bug is browser specific for me)
2. Log in using valid matrix.org credentials

#### What did you expect?
Can log in

#### What happened instead?

Cannot log in:
![Screenshot from 2021-12-16 08-36-29](https://user-images.githubusercontent.com/51663/146338731-5d3b0aea-705b-4afd-a57c-49562e7a0fe4.png)

on staging.element.io, I also got:
![Screenshot from 2021-12-16 08-55-34](https://user-images.githubusercontent.com/51663/146339765-48760219-c196-4955-b588-1e4db0b130ae.png)

I also got this in my device list:
![Screenshot from 2021-12-16 08-59-15](https://user-images.githubusercontent.com/51663/146340473-41fa70c6-ba9a-4e5c-9b9e-4d0928444f6e.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io, staging.element.io

### Application version

Element version: 23b21c940c68-react-b952fef1950b-js-72643026a3f8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The log isn't showing any error. That 404 is expected. Probably a temporal issue with matrix.org like a restart.

**Comment by kittykat** [comment]
@t3chguy I've removed the unhelpful screenshot, but I also got another error when I tried again on staging.element.io (screenshot added)

**Comment by novocaine** [comment]
I think the underlying error is net::ERR_FAILED 524 which seems to be a generic networking failure

**Comment by t3chguy** [comment]
This is a matrix.org issue, not an Element one. The 524 is from Cloudflare.

**Comment by t3chguy** [comment]
> I also got this in my device list

Looks like the login is succeeding but taking sufficiently long on matrix.org that Cloudflare hits the timeout
The Matrix API has no mechanism for dealing with this situation, no way to idempotently re-submit the login to get the same access token back.
