### ISSUE TITLE
element-web missing woff2 font resources

### ISSUE THREAD

**Issue by Jieiku** [vector-im/element-web#20216]
### Steps to reproduce

1. Install latest element-web
2. use firefox and press ctrl+shift+e for developer console
3. press ctrl+f5 in browser
4. notice the warnings for all the css?

#### What did you expect?
That the missing woff2 fonts would be there, or that they would be removed from the css referencing them.

#### What happened instead?
its trying to load these missing woff2 files:

```
21:47:15.531 The resource at “https://app.element.io/fonts/Inter/Inter-BoldItalic.2129bd0.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. app.element.io
21:47:15.531 The resource at “https://app.element.io/fonts/Inter/Inter-Bold.fc28dff.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. app.element.io
21:47:15.531 The resource at “https://app.element.io/fonts/Inter/Inter-SemiBoldItalic.10a60d8.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. app.element.io
21:47:15.532 The resource at “https://app.element.io/fonts/Inter/Inter-MediumItalic.8154ac2.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. app.element.io
21:47:15.533 The resource at “https://app.element.io/fonts/Inter/Inter-Medium.027d14e.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. app.element.io
```

### Operating system

Ubuntu 20.04.3

### Browser information

Firefox 95.0 (64-bit)

### URL for webapp

https://app.element.io

### Application version

https://element.io | Stable: v1.9.7 | Release status: v1.9.8 in RC

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The error you posted doesn't say they're missing, its just the browser whining that we told it to preload the font but then it wasn't used straight away. Because there was no Bold/BoldItalic etc text on your screen yet.

**Comment by Jieiku** [comment]
very clear explanation, thank you for taking the time to tell me. (sorry for the issue report)
