### ISSUE TITLE
Calling turns on video without participant consent.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20212]
### Steps to reproduce

1. In a group chat, start or join a jitsi call (even when clicking the "voice call" button).
2. Your camera is now on, without consent or warning, and visible to anyone connecting to your call.

#### What did you expect?
I expected that there would at least be a warning if it were to turn on, and if anything, hitting "voice call" wouldn't have turned on my camera.
#### What happened instead?
My camera was immediately turned on.

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by novocaine** [comment]
This is critical if it's happening after pressing voice call.

**Comment by AverytheFurry** [comment]
Just realized i didnt mention this was through "jitsi" calling (which is default for group chats), but i believe ive had the same behavior with native calls too.

**Comment by AverytheFurry** [comment]
> Just realized i didnt mention this was through "jitsi" calling (which is default for group chats), but i believe ive had the same behavior with native calls too.
> 
> I'm surprised this hasn't been reported, as this is the behavior for everyone I've heard of when using jitsi, I always warn people that it happens.

Alright I did some testing and I suppose it doesn't happen nearly as often as I have remembered (it did happen once out of ~10 tries), although I believe that answering the call (not initiating it) almost always turns your camera on.. However, in another room, calling started with a completely different prompt which showed settings to enable/disable video and audio devices before entering the call. Not sure why there's so much inconsistency here. Sorry if it's confusing!

**Comment by AverytheFurry** [comment]
![image](https://user-images.githubusercontent.com/47131867/146355928-9e30c2ad-ec9e-4b16-b16f-5b22df49ca81.png)

**Comment by novocaine** [comment]
> However, in another room, calling started with a completely different prompt which showed settings to enable/disable video and audio devices before entering the call. 

This is the case in newer versions of Jitsi. AFAICT, the Jitsi instance can be set in Element config or by the homeserver; if neither are set, it falls back to https://jitsi.riot.im/ which is using an older Jitsi version without that feature.

**Comment by novocaine** [comment]
It makes some sense that particular Jitsi instances would be remembering your prior config based on cookies. I've created a PR that turns off the camera for voice calls; we were not passing the param to the Jitsi SDK for some reason.

**Comment by AverytheFurry** [comment]
> It makes some sense that particular Jitsi instances would be remembering your prior config based on cookies. I've created a PR that turns off the camera for voice calls; we were not passing the param to the Jitsi SDK for some reason.

If other jitsi instances could just ignore this sdk parameter (since it seems youre saying the camera is not disabled or enabled by element), that would pose another issue, right? Couldnt someone just make a modified jitsi widget which silently records your video?

**Comment by novocaine** [comment]
> If other jitsi instances could just ignore this sdk parameter (since it seems youre saying the camera is not disabled or enabled by element), that would pose another issue, right? Couldnt someone just make a modified (malicious) jitsi widget which silently records your video?

The Jitsi widget code is part of your local copy of Element, which where I've just fixed the bug. Other people can't make you run arbitrary widget code.
