### ISSUE TITLE
Element-web 1.9.8-rc.1  Verify Identity with picture is broken

### ISSUE THREAD

**Issue by Jieiku** [vector-im/element-web#20217]
### Steps to reproduce

1. try to verify your identity using the picture code scan is broken in 1.9.8

#### What did you expect?
expect to see the picture to scan with my phone

#### What happened instead?
instead it just spins and spins

![2021-12-15_23-56](https://user-images.githubusercontent.com/106644/146333265-37d2fde7-28fa-45ea-9363-69792263a132.png)

![2021-12-15_23-54](https://user-images.githubusercontent.com/106644/146333270-5adc9705-fd19-4d46-81f6-53f0cb5fcb79.png)

### Operating system

Ubuntu 20.04.3

### Browser information

Firefox 95.0 (64-bit)

### URL for webapp

https://app.element.io

### Application version

https://element.io | Stable: v1.9.7 | Release status: v1.9.8 in RC

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed on develop and RC branch. Will be fine for release.
