### ISSUE TITLE
Element-Desktop 1.9.7  Windows/Linux login on homeserver not possible

### ISSUE THREAD

**Issue by pprugger** [vector-im/element-web#20227]
### Steps to reproduce

Download and install Element-Desktop 1.9.7 for Windows
Start Element-Desktop
Click on edit to change the homeserver
Type in your homeserver: https://homeserver-url
Element-Desktop keeps to persist to say it is not e valid homeserver.

Element works on the Webclient, Linux, Android and IOS with this homeserver.
Only the Windows version fails to function.

In my debbuging i found that:
If you just type in the homeserver url the client tries to query .well-known/matrix/client
With the https:// prepended the client does not even query the homeserver
Just says: "Homeserver URL does not seem to be a valid Matrix Homeserver".

#### What did you expect?
Login to my own homeserver
#### What happened instead?
Just says: "Homeserver URL does not seem to be a valid Matrix Homeserver".

### Operating system

Windows 10

### Application version

Element-Desktop 1.9.7

### How did you install the app?

https://element.io/get-started#download

### Homeserver

https://prometheus.umask.eu

### Will you send logs?

No

**Comment by kittykat** [comment]
@pprugger can you please check if there are any errors in the console (you should be able to open it with Ctrl+i, then go to the Console tab)

**Comment by pprugger** [comment]
![image](https://user-images.githubusercontent.com/25439591/146438591-ed3991ac-3727-4e36-85e7-920ab7c2925d.png)

Here a screenshot of the errors!

**Comment by pprugger** [comment]
Additional info:
After many more tests i can confirm, this also occurs on the linux client.
I retestet the 1.9.6 client and this one works.
So it seems this has been introduced in 1.9.7.

**Comment by t3chguy** [comment]
CORS is entirely outside the hands of Element, it is a handshake between the browser (Chromium) and your Web Server.

If you check the Network tab and try again it'll give you more details about the error.

**Comment by pprugger** [comment]
Hey @t3chguy !
I am talking about Element-Desktop here.
I just wrote what i observed.
The 1.9.6 desktop client just works.
No CORS errors, login works, sync works.

In 1.9.7 everything is dead.

**Comment by t3chguy** [comment]
Element Desktop uses Electron which is built on Chromium, hence me saying that.
Again, check the network tab for more details.

**Comment by pprugger** [comment]
I dont know what that should tell me more than the errors i already have posted.
It shows the same CORS error.

**Comment by t3chguy** [comment]
If you click on the request it'll show you response headers, which you can use to figure out why it was flagged as CORS, e.g missing ACAO header.

**Comment by pprugger** [comment]
As i already stated, i tried setting and changing the ACAO header with no luck.
This though doesn't explain the server_name error.
I guess this are two different things that both came with 1.9.7.

Attempted prometheus.umask.eu as a server_name but it failed Error: Homeserver URL does not appear to be a valid Matrix homeserver
    at g (languageHandler.tsx:56)
    at Function.buildValidatedConfigFromDiscovery (AutoDiscoveryUtils.tsx:242)
    at deriveData (ServerPickerDialog.tsx:95)
    at async r.validate (Validation.tsx:95)
    at async _.validate (Field.tsx:200)

**Comment by t3chguy** [comment]
Again, only the info in the Network tab would be helpful as the Javascript Console only contains app logs but with CORS the browser obscures the underlying cause for security reasons.

**Comment by pprugger** [comment]
![image](https://user-images.githubusercontent.com/25439591/146911180-0798b218-c9d1-4eda-89e9-0abf0b7b365d.png)

![image](https://user-images.githubusercontent.com/25439591/146911231-1bfa5290-958d-4cb0-bb5f-f198a8f7e890.png)

![image](https://user-images.githubusercontent.com/25439591/146911709-a3aa9814-124b-49e7-9f4c-631e90fe9aab.png)

**Comment by pprugger** [comment]
Well @t3chguy
I did some other tests.

As it seems it works if just a simple URL is used like example.com
BUT: Subdomains don't work
Try it yourself:
tchncs.de works
matrix.allmende.io doesn't work

Problem still persists in 1.9.8

**Comment by Melchiorro** [comment]
Hello! Exactly the same error on 1.10.* with my homeserver

Linux, android, macos and most windows clients works as before without any problems. Some windows desktop clients lost connection with the server after updating to version 1.10.0. After logging out of the account, it is impossible to log back in - the address of the home server is not accepted. The console shows the following errors
![Безымянный](https://user-images.githubusercontent.com/62253680/152363224-d1746fef-2bdc-4501-a22b-40fcf49a3bd5.png)
![Безымянный2](https://user-images.githubusercontent.com/62253680/152364845-da3c6961-ebf7-478e-95ac-4ff184316ba7.png)
![Безымянный3](https://user-images.githubusercontent.com/62253680/152365083-84b81dfe-1b7d-46c7-99c7-1d8b709ade14.png)

At the same time, in the web version, the same devices connect to the server successfully. There are no errors when running desktop 1.9 too. Update to 1.10.1 not didn't help.

OS: Windows 10.

How else can i help you find the problem?

**Comment by Melchiorro** [comment]
Okay, we were able to solve this problem. On computers where this problem arose, an alternative dns from Google was registered. For some reason, version 1.10 lost the server until you removed dns from the connection options, but at the same time, 1.9 worked flawlessly on the same device and with dns too.

**Comment by Torxed** [comment]
> CORS is entirely outside the hands of Element, it is a handshake between the browser (Chromium) and your Web Server.

I don't fully agree with this. As the Origin header is all sorts of special when it comes to element/synapse.
For anyone ending up here.. and running nginx as a reverse proxy:

```
        if ($http_origin = 'https://your.frontend.lan') {
                add_header Access-Control-Allow-Origin "https://your.frontend.lan";
        }
        if ($http_origin = 'https://your.backend.lan') {
                add_header Access-Control-Allow-Origin "https://your.backend.lan";
        }
        if ($http_origin = 'vector://vector') {
                add_header Access-Control-Allow-Origin "vector://vector";
        }
```

I don't like adding `vector://vector` here, but these are the things that have to go in there to avoid the issues above.

**Comment by t3chguy** [comment]
@Torxed the Matrix spec recommends `*` https://spec.matrix.org/v1.2/client-server-api/#web-browser-clients - given Matrix is an open protocol and other web clients exist, e.g Hydrogen

**Comment by t3chguy** [comment]
> but that would allow any site to access content on a client running under another domain?

No, it merely tells what origins a web browser should allow to make web requests to your API service. It does not control cross-tab or cross-origin access of any data or client state, merely the HTTP request passing or failing.

**Comment by turt2live** [comment]
From the history it appears as though all cases are configuration errors and not something we can fix ourselves. If you see this, please visit [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) on Matrix for troubleshooting.
