### ISSUE TITLE
"The following users may not exist" even though I "recently direct messaged" them

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20224]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/2803622/146408284-f29af1eb-ebe6-4d0d-8fa9-572d5f2a9bc7.png)
![image](https://user-images.githubusercontent.com/2803622/146408406-8cf1c935-d3bb-4458-9f9d-28e7acb7ec86.png)

#### What did you expect?
This `@_webhook` user is the matrix-appservice-webhooks. It is probably the bridge's shortcoming that it seems like it doesn't exist.

I am surprised that this user still "may not exist" even though I have a DM with them which they have joined. That should be enough evidence that they do exist.

### Operating system

arcch

### Application version

Element Nightly version: 2021121401 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
Just because you recently messaged them doesn't mean they haven't since been deactivated though?

**Comment by HarHarLinks** [comment]
Wouldn't they have left our DM then?

**Comment by t3chguy** [comment]
> Wouldn't they have left our DM then?

That's a Synapse-specific non-default behaviour. It isn't documented in the Matrix spec, so not necessarily.

**Comment by HarHarLinks** [comment]
Then I guess we have to live with it.

**Comment by t3chguy** [comment]
> Then I guess we have to live with it.

Or complain to Synapse and/or the application service
