### ISSUE TITLE
Room list for space doesn't load

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#20221]
### Steps to reproduce

Last nightly (just updated to confirm) seems to have regressed in space room list:
* clicking "+" next to space name in the second side bar launches global room directory popup (pretty sure it used to load space rooms?)
* clicking "Explore rooms" in the leftmost sidebar on the space loads the space but the spinner is infinite

#### What did you expect?

Expected to see room list.

#### What happened instead?

Wrong room list / Infinity spinner.

The console seems to be suggesting missing CORS headers :thinking: 

### Operating system

Ubuntu

### Application version

Element Nightly version: 2021121601 Olm version: 3.2.8

### Homeserver

federator.dev

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2021-12-16T12:25:41.635Z E request failed: CORS request rejected: https://federator.modular.im/_matrix/client/v1/rooms/!<roomID>%3Amatrix.org/hierarchy?suggested_only=true&max_depth=1&limit=20
ConnectionError: request failed: CORS request rejected: https://federator.modular.im/_matrix/client/v1/rooms/!<roomID>%3Amatrix.org/hierarchy?suggested_only=true&max_depth=1&limit=20
    at vector://vector/webapp/bundles/67514d2768cd59d6d61f/init.js:36546:15
    at Object.callback (vector://vector/webapp/bundles/67514d2768cd59d6d61f/init.js:36479:9)
    at on_response (vector://vector/webapp/bundles/67514d2768cd59d6d61f/vendors~init.js:202194:22)
    at XMLHttpRequest.on_state_change (vector://vector/webapp/bundles/67514d2768cd59d6d61f/vendors~init.js:202170:7)
    at XMLHttpRequest.<anonymous> (vector://vector/webapp/bundles/67514d2768cd59d6d61f/vendors~init.js:160881:41)
    at XMLHttpRequest.sentryWrapped (vector://vector/webapp/bundles/67514d2768cd59d6d61f/vendors~init.js:25806:23)
```

This is an issue with your server and/or configuration

Normally an error should come up here, will keep this issue open for that.

**Comment by jaywink** [comment]
Looks like the backend error is 404.

> 404 "GET /_matrix/client/v1/rooms/!roomid%3Amatrix.org/hierarchy?suggested_only=true&max_depth=1&limit=20

Did I maybe enable some labs flag that changed the way these are fetched or is nightly not compatible with Synapse v1.47.1? :thinking: I can't see any relevant nightly flags that I would have enabled related to spaces or room list.

**Comment by t3chguy** [comment]
The issue is the lack of ACAO + errcode=M_UNRECOGNISED on the 404.

```
< HTTP/2 404 
< date: Fri, 17 Dec 2021 14:00:30 GMT
< content-type: text/html; charset=utf-8
< content-length: 167
< strict-transport-security: max-age=15724800; includeSubDomains
< 

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>
```

**Comment by thawn** [comment]
I just encoundered the same issue on both the web and desktop clients: 

When I go to the "Space Home" page, I see a message "Failed to load list of rooms" and an infinitely running spinner.

What is a bit weird is, that the error message and spinner appear immediately without any delay.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/1308449/160141282-9c518633-f27b-4473-9a77-49f02290f8b9.png)

In the browser console, I see "CORS request rejected" errors.

And this message: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://synapse.matrix.tu-dresden.de](https://synapse.matrix.tu-dresden.de/_matrix/client/v1/rooms/!SQgtRQObuVxiqYqMqo%3Atu-dresden.de/hierarchy?suggested_only=false&limit=20)

Is this a misconfiguration on the client or the server side?

**Comment by t3chguy** [comment]
@thawn likely neither, likely a timeout due to your server not having enough resources, but due to how CORS works there's no way for the app to differentiate different kinds of errors (e.g timeouts)

**Comment by thawn** [comment]
@t3chguy thanks for your quick reply (and sorry for my slow answer 😉 )
But if it is a timeout, why is it appearing reproducibly every time? Also, the error message appears immediately, without any delay, I would expect that it should take some time if it was a timeout.

**Comment by t3chguy** [comment]
Only the Synapse server logs would have your answers unfortunately.

**Comment by thawn** [comment]
@t3chguy o.k. thanks. I will report the issue to the people who have access to that log. In case I get some enlightening information from them, I will report back here.

**Comment by penieldev** [comment]
> I just encoundered the same issue on both the web and desktop clients:
> 
> When I go to the "Space Home" page, I see a message "Failed to load list of rooms" and an infinitely running spinner.
> 
> What is a bit weird is, that the error message and spinner appear immediately without any delay.
> 
> Here is a screenshot:
> 
> ![image](https://user-images.githubusercontent.com/1308449/160141282-9c518633-f27b-4473-9a77-49f02290f8b9.png)
> 
> In the browser console, I see "CORS request rejected" errors.
> 
> And this message: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://synapse.matrix.tu-dresden.de](https://synapse.matrix.tu-dresden.de/_matrix/client/v1/rooms/!SQgtRQObuVxiqYqMqo%3Atu-dresden.de/hierarchy?suggested_only=false&limit=20)
> 
> Is this a misconfiguration on the client or the server side?

I have the same issue as well. The rooms are displayed fine on the sidebar, but not on the space homepage.

**Comment by t3chguy** [comment]
@penieldev I suggest checking the logs to see the underlying server error.
