### ISSUE TITLE
Keyword notification didn't highlight Home messages in red

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20229]
### Steps to reproduce

1. Home -> have "show all rooms" enabled
2. Received a ping via a keywork in #TIL

#### What did you expect?
Home and Element spaces both to have red badges

#### What happened instead?
Element space got a red badge, but Home stayed grey

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 23b21c940c68-react-d009cebb0745-js-3eaed304466a Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/2403652/146525949-e8652b75-baec-4009-b762-5c67c9d5a3f0.png)

![image](https://user-images.githubusercontent.com/2403652/146525920-b117697a-cc69-48b8-b90f-7c3c5d503249.png)

**Comment by t3chguy** [comment]
Can reproduce
