### ISSUE TITLE
'Person changed their profile picture' uses the old avatar rather than the new one

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20233]
This seems like a somewhat recent change.

**Comment by TheReshma** [comment]
I think this one is solved because I didn't encounter this in the recent versions..

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/161110001-202c7142-a34d-40da-9c2d-c933788b4b9b.png)

indeed - looks fixed.
