### ISSUE TITLE
uploading .mov screencaps don't get thumbnails or m.video events

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2023]

**Comment by pixlwave** [comment]
Just a small bump to say that support for .mov files would be lovely 🙃

**Comment by t3chguy** [comment]
Whether or not it is supported is up to your web browser.
Mov is a container format, your browser has to both support mov and whatever codecs you are using inside it.

**Comment by pixlwave** [comment]
Is this the same for the desktop client with Electron not having .mov support?

**Comment by t3chguy** [comment]
Yup, electron is based on chromium

**Comment by ara4n** [comment]
i finally snapped and fixed it in https://github.com/matrix-org/matrix-react-sdk/pull/8108. Closing as dup of https://github.com/vector-im/element-web/issues/21505

**Comment by t3chguy** [comment]
Arguably 21505 should have been closed as a dup of this much older, voted and properly triaged issue.
