### ISSUE TITLE
Display copyable version string in the feedback menu

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20231]
#### What would you like to do?
click on feedback, see this UI:
![image](https://user-images.githubusercontent.com/2803622/146438179-83ecc20b-6261-451f-aa81-da380a5c440b.png)

#### Why would you like to do it?
submit feedback. currently have to go to settings -> about and then also feedback to submit rageshake.
with this change, go only to feedback.

**Comment by kittykat** [comment]
Rageshake and feedback form automatically include version numbers as part of the logs :+1: You don't need to paste the version info into the feedback/rageshake form. For filing new bugs, we have [this issue](https://github.com/vector-im/element-web/issues/19844)

Does this resolve the issue for you?

**Comment by HarHarLinks** [comment]
> Rageshake and feedback form automatically include version numbers as part of the logs :+1:

this is great, but opaque. as a naive user I still think I need to fill in the version field of the github issue template, and I'm sure devs are going to complain if I don't even though I answered "going to submit logs" with yes. it slows down triage (e.g. issue is invalid as my bug from stable was fixed on develop). thus it would be nice if it was easier to get to.

#19844 seems like a great idea. however, if you open github first to see and remember "I need to fill in the version!" it's already too late, so I don't think it totally replaces this idea?

do you consider adding this copyable version string field to the feedback tab harmful? because it overloads the UI?

**Comment by t3chguy** [comment]
> do you consider adding this copyable version string field to the feedback tab harmful? because it overloads the UI?

Personally, yes, adding too many things to the UI may discourage users from leaving feedback due to information overload

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22104 given the version string isn't all that critical
