### ISSUE TITLE
Update strings to mention space rather than room or be ambiguous when it's not possible to be certain

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20243]
### Steps to reproduce

As an example:
1. Receive link to space (specifically [the one in this internal message](https://matrix.to/#/!kxwQeJPhRigXSZrHqf:matrix.org/$BgpDhzeAOtyVY1bZ2fQBUjLo0pLDvbfUdiW5QlTna54?via=matrix.org&via=element.io&via=vector.modular.im))
2. Click link
3. See two strings about joining a room when in reality I'm joining a space.

#### What did you expect?
Spaces and rooms have different strings, or where it's not possible to know what's on the other end, then be ambiguous

#### What happened instead?
Join space reuses join room strings

![Screenshot from 2022-02-03 16-52-51](https://user-images.githubusercontent.com/51663/152389908-7da1de0a-1679-4386-88db-c78ad8ad84ec.png)

![Screenshot from 2022-02-03 16-52-33](https://user-images.githubusercontent.com/51663/152389919-6bf0d42e-3ddf-425f-a182-2cdd5f9be537.png)

#### Other examples

As a space owner, I get mention of room when trying to re-invite a user to a space:
![Screenshot from 2021-12-17 13-49-10](https://user-images.githubusercontent.com/51663/146554201-2b9500fc-d96d-41bb-accf-b70520789555.png)

S-Major because current strings are actively misleading

### URL for webapp

develop.element.io

### Application version

Element version: 9e1f393-react-fb494a5098e6-js-36906e2ddb6d Olm version: 3.2.8

**Comment by t3chguy** [comment]
If the room is not peekable (federation, history visibility != world readable) then we don't know that its a space prior to joining it

**Comment by kittykat** [comment]
As a space owner, I get mention of room when trying to re-invite a user to a space:
![Screenshot from 2021-12-17 13-49-10](https://user-images.githubusercontent.com/51663/146554201-2b9500fc-d96d-41bb-accf-b70520789555.png)

**Comment by t3chguy** [comment]
@kittykat is that related to this issue about "join strings"?

**Comment by t3chguy** [comment]
For the `Some invites couldn't be sent` we can differentiate between room & space no problem

but for all of the pre-join/invite failed to join states, we need ambiguous language

**Comment by kittykat** [comment]
What about for the "Failed to join room":
> Failed to join
> You have not been invited

For "This room can't be previewed":
> There's no preview, would you like to join?
> Join the discussion

For "Some invites couldn't be sent", red line to:
> User is already in the space

(It feels redundant to repeat the MXID twice over two lines there)

**Comment by t3chguy** [comment]
> (It feels redundant to repeat the MXID twice over two lines there)

This has its own issue but I cannot find it atm

**Comment by t3chguy** [comment]
Need ambiguous copy for 

> Sorry, your homeserver is too old to participate in this room. Please contact your homeserver administrator.

> The person who invited you already left the room.

> The person who invited you already left the room, or their server is offline.

**Comment by t3chguy** [comment]
> What about for the "Failed to join room":

This is a string from Synapse

It emits a similar one too

> You do not belong to any of the required rooms/spaces to join this room.

We get an errcode of `M_FORBIDDEN` for both, so if you can think of an ambiguous message mixing "You have not been invited" and "You do not belong to any of the required rooms/spaces to join [this room/space]" then we can i18n it and replace the Synapse string in the UI

**Comment by kittykat** [comment]
> Sorry, your homeserver is too old to participate in this room. Please contact your homeserver administrator.

`Sorry, your homeserver is too old to participate here. Please contact your homeserver administrator.`

> The person who invited you already left the room.

`The person who invited you has already left.`

> The person who invited you already left the room, or their server is offline.

`The person who invited you has already left, or their server is offline.`

> This room does not exist.

`This room or Space does not exist.`

> This room is not accessible at this time.

`This room or Space is not accessible right now.`

> Try again later, or ask a room admin to check if you have access.

`Try again later, or ask a room or Space admin to check if you have access.`

> %(errcode)s was returned while trying to access the room.

`%(errcode)s was returned while trying to access the room or Space.`

> Join the discussion

Where does this one appear?

> You were removed from this room by %(memberName)s

`You were removed from here by %(memberName)s`

> You were banned from this room by %(memberName)s

`You were banned from here by %(memberName)s`

> Something went wrong with your invite to this room.

`Something went wrong with your invite.`

Is the context enough here to not mention room/Space?

> An error (%(errcode)s) was returned while trying to validate your " +
> "invite. You could try to pass this information on to a room admin.

When is this error seen? Is it useful to pass on this information to a room/space admin?

> You can still join it because this is a public room.

`You can still join because the is a public place.`

**Comment by t3chguy** [comment]
> This room does not exist.

> This room or Space is not accessible right now.

> Try again later, or ask a room or Space admin to check if you have access.

> %(errcode)s was returned while trying to access the room or Space.

What's with the inconsistent capitalisation here?

> Join the discussion

When previewing (peeking) into a room, on the CTA (primary) join button in the preview bar

> You were removed from here by %(memberName)s

> You were banned from here by %(memberName)s

IMO it reads better without `from here`

> Is the context enough here to not mention room/Space?

Well the client has no way of knowing if its a room or a space, so presumably neither would the user.

> When is this error seen? Is it useful to pass on this information to a room/space admin?

Yeah, they'd need to re-issue the 3pid invite

> You can still join because the is a public place.

We never use the term `place` elsewhere

**Comment by kittykat** [comment]
> > This room does not exist.
> 
> > This room or Space is not accessible right now.
> 
> > Try again later, or ask a room or Space admin to check if you have access.
> 
> > %(errcode)s was returned while trying to access the room or Space.
> 
> What's with the inconsistent capitalisation between `room` and `Space` here?

Lets go with "space". When spaces was released, it was considered a proper noun so was capitalised. We went with lower case on Android and iOS now.

> > Join the discussion
> 
> When previewing (peeking) into a room, on the CTA (primary) join button in the preview bar

I think we can keep this one as it doesn't mention room specifically and technically spaces have discussions in them (in the rooms).

> > You were removed from here by %(memberName)s
> 
> > You were banned from here by %(memberName)s
> 
> IMO it reads better without `from here`

Agreed, lets go with:
"You were removed by %(memberName)s"
"You were banned by %(memberName)s"

> > Is the context enough here to not mention room/Space?
> 
> Well the client has no way of knowing if its a room or a space, so presumably neither would the user.

Ok, lets keep it as "Something went wrong with your invite." then

> > When is this error seen? Is it useful to pass on this information to a room/space admin?
> 
> Yeah, they'd need to re-issue the 3pid invite

What about:
"An error (%(errcode)s) was returned while trying to validate your " +
"invite. You could try to pass this information on to the person who invited you."

> > You can still join because the is a public place.
> 
> We never use the term `place` elsewhere

Would just `You can still join here.` work?
