### ISSUE TITLE
Bubbles: Launching (Web)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20244]
### To launch the first round of Bubbles we need: 

**For the customer**
- [x] Runtime config.json <del>or Build flag</del>

**For users**
- [x] Setting in Appearance for Message Bubbles (no Labs flag)
**We need to remove Appearance picker and Message Bubbles from Labs, but leave IRC mode in Labs.**
- [x] Update Labs flag switch
- [x] Update copy of the Labs flag

---
## Discussion only, no deliverables

- [x] Are Bubbles for DMs only? Users would like to configure by DM or Room, or both. This brings complications we're choosing not to hanlde in V1 including: If Bubbles **off** for some Rooms, which Appearance Setting to use in place of Bubbles?
- [x] Can Bubbles be configurable by Space? No, this is complicated and not indicated as useful by the survey
- [x] Should Bubbles be set once across platform? No, discussed as a team that Bubbles should be a by Platform choice for now

**Comment by Stebalien** [comment]
(I hope this is the right place to give this feedback)

> Are Bubbles for DMs only?

Please keep it _possible_ to enable bubbles for all rooms. For me, at least, it really helps with following the conversation.

**Comment by amshakal** [comment]
Noted :)

**Comment by daniellekirkwood** [comment]
@t3chguy as Bubbles is in the RC, do you think we can close this?

**Comment by daniellekirkwood** [comment]
Confirmed in DMs
