### ISSUE TITLE
Remove List Options for Suggested Rooms

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20252]
#### What would you like to do?
![image](https://user-images.githubusercontent.com/2803622/146581982-b1aee1a4-f54c-4698-a54b-03d482c4cc33.png)

![image](https://user-images.githubusercontent.com/2803622/146581938-51113df4-03cd-4b11-adad-1fe62e908399.png)

These are useless:
- don't have the info to sort or show unread/previews without joining
- but upon joining, it's removed from suggestions

**Comment by t3chguy** [comment]
Only the appearance section should be removed to match `Invites`

**Comment by t3chguy** [comment]
Changed my mind, don't particularly want to wire it through the RoomListStore/Algorithm to wire up sorting
