### ISSUE TITLE
Video calling triggers camera usage indicator, even when camera is turned off.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20258]
### Steps to reproduce

1. Start a video call (native, not jitsi, although the behavior may be the same on jitsi, I haven't tested it)
2. Turn your camera off in the call, while remaining in the call
3. Observe the light on the camera still being on until you end the call

#### What did you expect?
Expected the camera to be turned off, but it appears it is still in use, even when the video is turned off.
#### What happened instead?
The camera is being activated.

### Operating system

Windows

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
@AverytheFurry, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seems to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)

**Comment by AverytheFurry** [comment]
> @AverytheFurry, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seems to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)

I'm using the electron app, but i can try it at home later

**Comment by SimonBrandner** [comment]
> > @AverytheFurry, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seems to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)
> 
> I'm using the electron app, but i can try it at home later

Try in Chrome/Chromium, should behave the same

**Comment by AverytheFurry** [comment]
> > > @AverytheFurry, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seems to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)
> > 
> > 
> > I'm using the electron app, but i can try it at home later
> 
> Try in Chrome/Chromium, should behave the same

I will do this the next time I find someone to video call as a test on an alt account. Don't know when that will be.

**Comment by SimonBrandner** [comment]
> > > > @AverytheFurry, can you please try [this](https://jyasskin.github.io/sandbox/camera-pause/) out - click `Replace stream` and then click `Disable stream` and see what happens. From my testing, this looks like a Chrome bug which already seems to have been filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)
> > > 
> > > 
> > > I'm using the electron app, but i can try it at home later
> > 
> > 
> > Try in Chrome/Chromium, should behave the same
> 
> I will do this the next time I find someone to video call as a test on an alt account. Don't know when that will be.

You don't need a second person for the test that I have suggested

**Comment by AverytheFurry** [comment]
> 

Disable stream doesn't do anything, but stop stream does.

**Comment by SimonBrandner** [comment]
> > 
> 
> Disable stream doesn't do anything, but stop stream does.

Yeah, then this is a Chrome issue... We can't do anything about that, sorry. I suggest you follow [this Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=642785).

I am going to close this as it is not an Element Web/Desktop bug
