### ISSUE TITLE
Localized missed call tile not responsive

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#20254]
### Steps to reproduce

The "Call back" button on missed call is misplaced if localized text which is longer than the original. The background rectangle should adjust its size to the right side of the button.
![image](https://user-images.githubusercontent.com/26059643/146606756-b79f3758-78fc-48a8-ab20-dc8a320c3b33.png)

### Outcome

It looks ugly.

### Operating system

Linux

### Browser information

any

### URL for webapp

app.element.io

### Application version

1.9.7

### Homeserver

grin.hu

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
@gaelledel, do you have any thoughts on how to handle this?
