### ISSUE TITLE
"Show all rooms in Home" option inactive even though I selected it

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20250]
### Steps to reproduce

1. Return to Element from some other task, and already am in the Home space.
2. I notice that fewer than normal rooms are visible.  E.g. there is no Favourites section at all, and other rooms are missing
3. Go to Preferences and unselect "Show all rooms in Home"
4. Select "Show all rooms in Home"
5. Notice my rooms are all visible, and Favourites has appeared

#### What did you expect?

"Show all rooms in Home" should remain active.

#### What happened instead?

"Show all rooms in Home" seemed to stop having an effect.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 95.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 9e1f39322479-react-670d7824ec43-js-36906e2ddb6d Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment]
Mine keeps switching off every time I refresh at the moment.
