### ISSUE TITLE
Sharing screen applications don't show if they are minimized. (ex. sharing a game)

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20269]
### Steps to reproduce

1. Open a game in exclusive fullscreen
2. Alt+tab (which minimizes the game)
3. Try to share the game through the "application" dialogue
4. The game does not appear unless you set it to windowed mode.

#### What did you expect?
I expected the game to still show as a streamable option.
#### What happened instead?
The game was not streamable. From my experience, sharing the application tends to lead to fewer performance issues.

### Operating system

Windows

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I am pretty sure there is nothing we can do here due to this being completely handled by Electron itself... Do you know any other Electron apps (Discord, Slack...) that do this?

**Comment by AverytheFurry** [comment]
> I am pretty sure there is nothing we can do here due to this being completely handled by Electron itself... Do you know any other Electron apps (Discord, Slack...) that do this?

Yes, discord lets you screenshare games even if they are minimized at the point of starting the stream, as its impossible to use discord at the same time as keeping the game un-minimized.

**Comment by t3chguy** [comment]
> The game does not appear unless you set it to windowed mode.

This might not be related to it being minimized but maybe due to how full screen games are rendered, much more directly and might skip the layer which Chromium hooks into for application window screen sharing (the clue is in the name, application *window*)

**Comment by AverytheFurry** [comment]
> > The game does not appear unless you set it to windowed mode.
> 
> This might not be related to it being minimized but maybe due to how full screen games are rendered, much more directly and might skip the layer which Chromium hooks into for application window screen sharing (the clue is in the name, application _window_)

I believe you can toggle the window to windowed mode, start the screenshare, and then put it back in fullscreen mode, and it (usually) continues sharing, although I remember having some issues with alt tabbing after all that breaking the screen sharing.

**Comment by SimonBrandner** [comment]
@AverytheFurry, could you please try the web version of Element, so that we know if this is indeed caused by Chromium?

**Comment by AverytheFurry** [comment]
> @AverytheFurry, could you please try the web version of Element, so that we know if this is indeed caused by Chromium?

Yes, ill give it a try the next time i have a chance.

**Comment by turt2live** [comment]
Unfortunately there's nothing we can control here - it's a feature of the browser/electron to determine which applications, if any, can be screenshared.
