### ISSUE TITLE
Clicking on a reply (containing a codeblock?) breaks timeline so you can't jump-to-bottom any more.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20264]
### Steps to reproduce

* Viewing a timeline with some replies containing codeblock
* Click on the codeblock; jump in theory to the reply location

### Outcome

* Sometimes it jumps to the wrong place entirely
* Sometimes it then scrolljumps immediately after
* Sometimes the jump to bottom button does nothing

Easy to reproduce.

Have included screencap on the rageshake.

### Operating system

macOS 12.0.1 on M1

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
I can repro without code blocks involved, just any reply jump, presumably even all permalink jumps

**Comment by aaronraimist** [comment]
Jump to bottom being broken is https://github.com/vector-im/element-web/issues/19813
