### ISSUE TITLE
[Develop Branch] Visual changes feedback

### ISSUE THREAD

**Issue by licentiapoetica** [vector-im/element-web#20261]
#### What would you like to do?
I would like to advise to not change how the breadcrumbs, or otherwise refered to as Room list shortcuts be hidden behind a extra hover to access them, this totally ruins the usability of this feature, if this is thought as a permanent change, please make it optional so users like me don't have to sacrifice on usability when it comes to ui.
#### Why would you like to do it?
Because I don't like it at all.
#### How would you like to achieve it?
By stating it here as feedback.

**Comment by gsouquet** [comment]
Closing as this experiment will be discontinued and we will keep the breadcrumbs as they were working
