### ISSUE TITLE
easy way to migrate to another user

### ISSUE THREAD

**Issue by rubo77** [vector-im/element-web#20267]
#### What would you like to do?
I want to invite my new user name into all my rooms. And in second step I want to leave or rooms with my old user.

#### Why would you like to do it?
Migrate to another user on another homeserver.

#### How would you like to achieve it?
Provide the functionality where I can select all rooms and invite the new user into those rooms with one click.

Then I would switch to my new user.

Can you use a I would need a button to accept or invitations with one click.

Then we need button for my old user to leave all rooms with one click

**Comment by HarHarLinks** [comment]
does this help? https://ems.element.io/tools/matrix-migration

**Comment by rubo77** [comment]
cool, this site should be linked in Element somewhere

**Comment by gsouquet** [comment]
It looks like this feature already exist, for that reason I will close this issue.
Feel free to comment if you feel like that does not solve your issue
