### ISSUE TITLE
Rotate Left tooltip is shown when opening lightbox

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20268]
### Steps to reproduce

click an image, in timeline or profile or room info etc to open in lightbox

#### What did you expect?
![image](https://user-images.githubusercontent.com/2803622/146694552-12f2b271-3820-4ade-9bab-14267b021fc9.png)

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/146694546-231633db-1ace-4795-86b3-1a2b2594634e.png)

### Operating system

arch (ozone)

### Application version

Element Nightly version: 2021121901 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20210
