### ISSUE TITLE
HTML exporting broken on develop.element.io

### ISSUE THREAD

**Issue by notramo** [vector-im/element-web#20276]
### Steps to reproduce

HTML exported conversations are not styled. Seems like an error to load CSS.

It works on app.element.io v1.9.7

### Operating system

doesn't matter

### Browser information

Firefox (both for app and viewing)

### URL for webapp

develop.element.io

### Application version

Element verzió: 9e1f39322479-react-9289c0c90fc6-js-dd0ca91aa94e

### Homeserver

grin.hu

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7415

**Comment by ara4n** [comment]
This seems to have regressed again; my export's style.css is only 7KB and has hardly anything in it.

```
JSON.parse(window.localStorage.mx_local_settings).theme
'dark'
JSON.parse(window.localStorage.mx_local_settings).use_system_theme
false
```

fwiw.

**Comment by t3chguy** [comment]
The export is always in light theme, so your selected theme should bear no effect

**Comment by ara4n** [comment]
ok, can i share debugging that'd be useful?

**Comment by t3chguy** [comment]
Just tried to repro on Chrome on macOS on develop and it worked fine, yielding a ~70KB CSS file. (Dark mode enabled, use System theme disabled, same as yours) - this issue is about develop by title, but can repro on Nightly
