### ISSUE TITLE
Icon to expand spaces sidebar is invisible

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#20279]
### Steps to reproduce

1. Update to 1.9.8
2. Try to expand spaces sidebar

#### What did you expect?

The button is visible

#### What happened instead?

The button is invisible when in the collapsed state
<img width="169" src="https://user-images.githubusercontent.com/5855073/146807696-2b4f804c-9d23-4f35-a7d9-5471df19d5b3.png">

When expanded the button is visible when not hovering. When you hover over it though the button becomes invisible.
<img width="159" src="https://user-images.githubusercontent.com/5855073/146807773-bb9509f3-4c4e-4716-bee4-ae95073dfff9.png">

### Operating system

macOS

### Browser information

Firefox

### Application version

1.9.8

### Will you send logs?

No

**Comment by yozhic** [comment]
![invisible_icon](https://user-images.githubusercontent.com/13917732/146930843-84b02991-ce4e-4be1-9849-4f0e8daee319.gif)
