### ISSUE TITLE
Quoted text is incorrectly collapsed

### ISSUE THREAD

**Issue by grahamc** [vector-im/element-web#20277]
### Steps to reproduce

From a chat with a person or a room, send a message of quoted text:

```markdown
> foo
> 
> bar
```

Observe the message arrives as `foobar`.

Then click Edit on the message and see you actually ended up sending:

```markdown
> 
foobar
```

#### What did you expect?

I expected my quoted text to render the included paragraph breaks. ie when I send:

```
> foo
> 
> bar
```

I expect the message to render like this:

> foo
>
> bar

#### What happened instead?

The message renders like this, and the actual text of what I sent is changed, potentially making it mean something different:

> foobar

### Operating system

NixOS

### Application version

Element version: 1.9.4 Olm version: 3.2.3

### How did you install the app?

Nix

### Homeserver

nixos.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Element version: 1.9.4 Olm version: 3.2.3

Please update, I believe this is fixed.

**Comment by grahamc** [comment]
Yep you're right, thanks! Sorry about that I thought I'd updated first.
