### ISSUE TITLE
Cannot invite people in a different homeserver to a Space

### ISSUE THREAD

**Issue by igutekunst** [vector-im/element-web#20280]
### Steps to reproduce

0. Setup matrix-synpase using https://github.com/spantaleev/matrix-docker-ansible-deploy.
1. Create a new Space/Community
2. Attempt to invite a user with an account on a different homeserver 

#### Some additional comments

This very well could be a matrix-synapse bug and not an Element bug. However, I have not dug into the logs on the homeserver enough to find out for sure. The folks in the Synaps Admins room didn't know how to solve it, though we didn't try too hard. 

#### Expected

The invite is sent successfully 

#### Actual

A message box opens and says:

Failed to invite user to the room. You do not have permission to invite people to this room. 

The Space is set to private. The advanced tab says room version: 6.

### Operating system

Windows, Linux and Mac OS

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

I can discuss in private if this is relevant. It is my personal homeserver. 

### Will you send logs?

No

**Comment by aaronraimist** [comment]
Most likely this is a misconfiguration of your server or of the space. Does your server pass the federation tester? Can you invite users on other homeservers to rooms? Does the Advanced section of the Space settings say "This room is not accessible by remote Matrix servers"?

**Comment by t3chguy** [comment]
Closing due to no info from the author. As specified, likely a misconfiguration as Spaces are fundamentally just rooms.
