### ISSUE TITLE
Windows Desktop Icon

### ISSUE THREAD

**Issue by mgrant0** [vector-im/element-web#20297]
### Steps to reproduce

1. Where are you starting? What can you see?

When Element updates, it always recreates the icon on my Windows desktop.  

2. What do you click?

Click the update button when a new update arrives.

3. More steps…

#### What did you expect?

On initial install, Element should ask if it should create a desktop icon.  If the user chooses no, then no desktop icon should ever be created.  Frankly I don't understand desktop icons for programs, if ever program had an icon on the desktop, the desktop would be an unusable mess!  But some people like specific things on the desktop.  Element should respect the user's choice of wether to create/recreate the icon.

#### What happened instead?

I expected it not to create / recreate the icon ever time it updated.

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://element.io/personal

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9210

**Comment by mgrant0** [comment]
ok thanks, i will close this then.  I didn't find that other bug because I was searching for 'icon'
