### ISSUE TITLE
Missing translation in 1.9.8 develop branch 

### ISSUE THREAD

**Issue by ottersarecool** [vector-im/element-web#20295]
### Steps to reproduce

1. Pulled latest develop and master branch
2. compiled using yarn start:js before dist
3. see this: 
![2021-12-21_07-48](https://user-images.githubusercontent.com/51519051/146884665-c836dbac-1d42-47bf-96cd-922170513670.png)

#### What did you expect?
no missing translation

#### What happened instead?
apparently some translation is missing

### Operating system

Arch btw

### Browser information

Firefox 95

### Application version

1.9.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Missing translation in 1.9.8 develop branch 

So is it 1.9.8 or `develop` - they are very different things.

![image](https://user-images.githubusercontent.com/2403652/146933414-f5796462-bbd9-415b-84e1-ec0fad1e4dc5.png)

On develop it looks fine to me.

**Comment by ottersarecool** [comment]
> > Missing translation in 1.9.8 develop branch
> 
> So is it 1.9.8 or `develop` - they are very different things.
> 
> ![image](https://user-images.githubusercontent.com/2403652/146933414-f5796462-bbd9-415b-84e1-ec0fad1e4dc5.png)
> 
> On develop it looks fine to me.

I figured out it happens when I have labs settings enabled for dnd and custom status, no idea why though. I pulled develop and master to check.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/147001121-b23d7670-6b2b-46ec-a83e-a36257dbb805.png)

Still fine here.

**Comment by ottersarecool** [comment]
> ![image](https://user-images.githubusercontent.com/2403652/147001121-b23d7670-6b2b-46ec-a83e-a36257dbb805.png)
> 
> Still fine here.

very weird, I just repulled and recompiled but still no luck at all!
![2021-12-21_22-46](https://user-images.githubusercontent.com/51519051/147001740-b2a4a783-7fad-4a78-99c5-64da8e041d48.png)
![2021-12-21_22-46_1](https://user-images.githubusercontent.com/51519051/147001743-0e2f2d76-c0b5-4c9d-a118-87bdf5fdb178.png)

**Comment by t3chguy** [comment]
Please provide a set of reproduction steps, your description mixes develop and master which is very confusing.

**Comment by ottersarecool** [comment]
> Please provide a set of reproduction steps (each command), your description mixes develop and master which is very confusing.

sorry if this is confusing to you but I literally just try to follow the readme when building it myself and there are some translations missing

**Comment by t3chguy** [comment]
If you are mixing a release branch with a development branch then this is entirely unsupported, all layers must be on develop or all layers must be on master.

**Comment by ottersarecool** [comment]
> If you are mixing a release branch with a development branch then this is entirely unsupported, all layers must be on develop or all layers must be on master.

you were right this somehow messed my dev env up, thank you!
fresh pull of the whole repo did the trick
