### ISSUE TITLE
Timeline jumps around randomly when using message bubbles

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20302]
### Steps to reproduce

1. Enable Message Bubbles in Labs
2. In a room, scroll to older messages or click a pinned link to an older message

#### What did you expect?
To see older messages

#### What happened instead?
Timeline starts jumping around

https://user-images.githubusercontent.com/51663/146961326-bfeefcea-b86e-41a1-857f-79127a860b77.mp4

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 211f48002759-react-a239c456e37e-js-2aae2362e3a8 Olm version: 3.2.8 and newer

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Seems to only happen with bubbles

**Comment by kittykat** [comment]
Agreed, I stopped seeing it when I switched away from message bubbles and it came back when I switched back just now. Description updated to reflect this

**Comment by t3chguy** [comment]
This looks to be related to blurhashes which don't render in bubble layout wrongly so cause jumps

**Comment by t3chguy** [comment]
So fixing the blurhash issue doesn't appear to fix the bulk of the jumping :((

**Comment by t3chguy** [comment]
The bulk of this issue seems to be some weird uncontrollable jump around the backpagination trigger which causes you to get stuck weirdly.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/4a9173a7f1568ae55d26954a047d45c95840e8a6
