### ISSUE TITLE
Suggested rooms are still in the room list but not labeled as such

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20304]
### Steps to reproduce

any space with suggested rooms, e.g. element space
![image](https://user-images.githubusercontent.com/2803622/146966586-5d85531e-aa2a-4ce8-aeb1-0d4218add497.png)

#### What did you expect?
labeled or no suggestions
#### What happened instead?
confusion

### Operating system

arch

### Application version

Element Nightly version: 2021122001 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
Looks like a broken sticky header

**Comment by HarHarLinks** [comment]
It happens in the element space, but not the matrix space:
![image](https://user-images.githubusercontent.com/2803622/147092744-cd22349b-a998-4bc7-9f9d-f0a2c1bdbc37.png)

**Comment by t3chguy** [comment]
I cannot reproduce

![image](https://user-images.githubusercontent.com/2403652/147226547-645f9ed0-c497-4d5c-9f6f-e3eaed100b57.png)

![image](https://user-images.githubusercontent.com/2403652/147226551-85e55204-7e31-4d6d-957c-cb74c7f013bd.png)

**Comment by HarHarLinks** [comment]
Indeed it seems to have disappeared in today's nightly!
