### ISSUE TITLE
Can't  Login , stay in Syncing

### ISSUE THREAD

**Issue by xiezhiqi** [vector-im/element-web#20318]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/4393881/147061574-ec8e0022-a0d6-44cb-9e4f-49497549cb23.png)
![image](https://user-images.githubusercontent.com/4393881/147062871-5b925d74-9ff6-4d29-be36-3f2aa0be8819.png)

### Outcome

Homeserver have port but get " _matrix/client/versions" not have port

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your server is misconfigured, in homeserver.yaml your base_url is set wrong so the server is saying:

> Here's your access token, now log into `https://$$$$$.com` with it (missing the port)

**Comment by xiezhiqi** [comment]
Android client can be used normally

**Comment by xiezhiqi** [comment]
> Your server is misconfigured, in homeserver.yaml your base_url is set wrong so the server is saying:
> 
> > Here's your access token, now log into `https://$$$$$.com` with it (missing the port)

But ，Android client can be used normally

**Comment by t3chguy** [comment]
I believe android has a bug where it doesn't follow the login flow from the spec properly.

**Comment by robintown** [comment]
Closing, as this is a case of homeserver misconfiguration
