### ISSUE TITLE
Overflow read recipts look 'boxy' until expanded.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20310]
### Steps to reproduce

1. Look at a large number of 'clumped' read receipts, observe "boxyness"
2. Ungroup them, observe them looking normal.

#### What did you expect?
I expected them to appear as circles.
#### What happened instead?
They seem to be boxy for some reason.
![Capture](https://user-images.githubusercontent.com/47131867/146986450-1cc9cf09-199e-4f32-a3b6-9d5e34b1f940.PNG)
![Capture2](https://user-images.githubusercontent.com/47131867/146986454-7dafb9c7-ca82-4122-a4b8-9d17a54e2c2e.PNG)

### Operating system

Windows

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by shryasss** [comment]
I'd love to contribute on this, but I'm a newbie and will need help, can you share any resources to get started?

**Comment by SimonBrandner** [comment]
> I'd love to contribute on this, but I'm a newbie and will need help, can you share any resources to get started?

I believe [this file](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/ReadReceiptMarker.tsx) should be a good starting point

**Comment by SimonBrandner** [comment]
If you have any more questions be sure to visit https://matrix.to/#/#element-dev:matrix.org. Will assign you as you have expressed the want to work on this, let us know if you need something or don't have time to work on this anymore

**Comment by ttheshreeyasingh** [comment]
@shryasss Hi, are you still working on this issue? If not, can I be assigned the issue as well?

**Comment by Pattygeek** [comment]
@SimonBrandner I will like to be assigned this issue.

**Comment by SimonBrandner** [comment]
> @shryasss Hi, are you still working on this issue? If not, can I be assigned the issue as well?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by yaya-usman** [comment]
@ttheshreeyasingh are you still working on this, I want to link a draft PR to this incase you're not working on it anymore

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8389
