### ISSUE TITLE
Code block numbering doesn't account for wrapping

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#20316]
![image](https://user-images.githubusercontent.com/2403652/147014421-9313b619-03cc-4312-a386-9cb89141fb7b.png)
![image](https://user-images.githubusercontent.com/2403652/147014428-ca7fbd2b-166b-4e33-995e-05f200976fae.png)

**Comment by hex-m** [comment]
The problem started with `1.9.8`. Older versions did not wrap lines in code blocks.

My intuition says that lines in code blocks (`pre`-elements) should not be wrapped and that's also how it is rendered on GitHub, GitLab and Stack Exchange. 

I assume it was a conscious decision, but imho the cleanest way to solve this issue would be not to wrap lines in code blocks.

**Comment by t3chguy** [comment]
The intent was to only wrap in inline code blocks, good spot.
