### ISSUE TITLE
MsgBubbles: Media Layout

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20326]
### Your use case

To ensure alignment across platforms the we need to ensure the following for Web: 

Images, Files, Audio, & Video (and other Media) messages are sent outside of a bubble. 
Images, Files, Audio, & Video (and other Media) messages are seen on the right by the sender and left when receiving.
Images, Files, Audio, & Video (and other Media) messages are green on the right, and grey on the left (to be confirmed)

Verified for:
- [x] Images
- [x] Files
- [x] Audio
- [x] Video 
 

Also needs checking:
- [ ] Verifications
- [ ] Room intro

**Comment by t3chguy** [comment]
> Images, Files, Audio, & Video (and other Media) messages are green on the right, and grey on the left (to be confirmed)

How would this work if they're outside of a bubble?

**Comment by t3chguy** [comment]
> Images, Files, Audio, & Video (and other Media) messages are sent outside of a bubble.
> Images, Files, Audio, & Video (and other Media) messages are seen on the right by the sender and left when receiving.

Pretty sure these are already the case so really unsure about what there is to be done given I've been assigned.

**Comment by daniellekirkwood** [comment]
<img width="403" alt="Screenshot 2021-12-22 at 15 56 09" src="https://user-images.githubusercontent.com/89144281/147120045-a88774f7-2db1-4b1e-8119-cd3487646645.png">

This is a screenshot where I am a sender for all of the above types of media (image, file, audio, video).

Should we change the colour grey to green in this instance? Or should it be grey? (same possibly applies to calls)

**Comment by t3chguy** [comment]
and probably verifications and room intro summaries

**Comment by daniellekirkwood** [comment]
> > Images, Files, Audio, & Video (and other Media) messages are green on the right, and grey on the left (to be confirmed)
> 
> How would this work if they're outside of a bubble?

We know that they're outside of a bubble but as they're wrapped with rounded edges, users may not know that. Depending on the response from Amsha we can probably close this issue without input from you @t3chguy -

**Comment by daniellekirkwood** [comment]
> and probably verifications and room intro summaries

ooh, good point. Let's add those to the issue

**Comment by amshakal** [comment]
Voice messages and files are the only ones that need a to be green when being sent as it's in a 'bubble' already. The rest does not have a bounding box and will stay as it is.

**Comment by t3chguy** [comment]
@amshakal should the middle-aligned verifications get appropriate colour too?

![image](https://user-images.githubusercontent.com/2403652/148047583-753aefdd-f64d-4190-bb00-2ee465de3208.png)

**Comment by daniellekirkwood** [comment]
These items were raised in the Testing session today.

All Media types mention in this issue have their own "Bubble" styling and therefore do not need any further action from the Bubbles team. 

👀 @t3chguy & @amshakal 

I will start to update our language throughout the Bubbles project so that when talking about media messages it's component style is a pill (rather than a bubble). Does that work for you both?
