### ISSUE TITLE
MsgBubbles: Location

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20323]
Location sharing should not appear in a Bubble. Locations should look like Images. 

![imagebubbles](https://user-images.githubusercontent.com/89144281/147108435-9cd19ead-6f81-41be-8287-7fef3cd83c98.png)

**Comment by daniellekirkwood** [comment]
I think Location should act the same as Image WRT Bubbles...

**Comment by daniellekirkwood** [comment]
@gaelledel for your reference :)

**Comment by amshakal** [comment]
+1

**Comment by amshakal** [comment]
Here is an example:
<img width="351" alt="Screenshot 2021-12-23 at 17 35 13" src="https://user-images.githubusercontent.com/85162587/147238079-440f6a51-c33a-4174-b436-ec724b2af7a8.png">

**Comment by t3chguy** [comment]
@amshakal where's the timestamp on there?

**Comment by amshakal** [comment]
<img width="362" alt="Screenshot 2021-12-23 at 17 48 24" src="https://user-images.githubusercontent.com/85162587/147239586-a4b6c0e1-ecd7-4861-8a07-eeaf5ea3a1ec.png">
Here is the timestamp :D It's following the same principles as other messages. The grey colour of the timestamp is the same as that of other messages.
