### ISSUE TITLE
MsgBubbles: Smoke Testing (Web)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20327]
### Your use case

Run an initial testing session to check that we're on the right track.

#### What we need going into the session
- [x] List of completed and partially completed tasks based on Customer Requirements
- [x] Pick a time when most of the team can attend (Product, Design and lead developer for the platform must attend)

#### During the session
- Lay out standard paths to follow to achieve tasks (test cases with steps)
- Run through some exploratory test cases (tasks to achieve without steps)
- Collect defects and enhancements which are found, and  make sure to collect accurate reproductions steps with screenshots and screen recordings as needed
- Compare against designs

#### Outputs from the session
- [x] Product processes and files found issues
- [ ] Design reviews any designs to update for findings from session
- [ ] Acceptance criteria on issues updated as needed (by design, product or development)

**Comment by daniellekirkwood** [comment]
Planned for January 12, 2022

**Comment by daniellekirkwood** [comment]
Document tracking next steps
https://docs.google.com/document/d/1RBQEkCcFoDkR1gBM8T4P_yhFbWR0E-be9u3VNj3_Dxc/edit?usp=sharing

**Comment by t3chguy** [comment]
No access to doc

**Comment by daniellekirkwood** [comment]
Web passed with a success rate of 73%
(_80% is the minimum_)

The remaining 27%
Web: What's 27%?**

Bugs excluded and raised in GH, see [Project Board](https://github.com/orgs/vector-im/projects/26/views/4)

| Test case             | Solution                                                     |
| --------------------- | ------------------------------------------------------------ |
| Read receipts         | ✅ Discussed with design<br />No Eng action needed. <br />Change the test case for Round 2 |
| Left-aligned timeline | ⏱ Discuss with design<br />GH to be raised if needed, else change test case for Round 2 |
| Video calls           | ✅ Discussed with design<br />No Eng action needed. <br />Change the test case for Round 2 |
| Code blocks           | ✅ Discussed with design<br />No Eng action needed. <br />Change the test case for Round 2 |
| Thread summary        | ✅ Discussed with design<br />No Eng action needed. <br />Change the test case for Round 2 |
| URL previews          | ⏱ Discuss with design<br />GH to be raised if needed, else change test case for Round 2 |
| File sharing          | ✅ Discussed with design<br />No Eng action needed. <br />Change the test case for Round 2 |
| Stickers              | https://github.com/vector-im/element-web/issues/20523        |
| Thread panel messages | https://github.com/vector-im/element-web/issues/20522<br />Change the test case for Round 2 |

**Comment by daniellekirkwood** [comment]
Closing this issue as round one was completed and all action items have been dealt with
