### ISSUE TITLE
Space name is weirdly inserted into "Preferences" view

### ISSUE THREAD

**Issue by artevaeckt** [vector-im/element-web#20331]
### Steps to reproduce

1. Create a space with a long name (should be more than 19 chars)
2. Navigate to that space
3. Click the space name to open the drop down menu
4. Click "Preferences"

#### What did you expect?
There should either no space name visible or it should not be hidden behind other elements.
#### What happened instead?
The space name is partly hidden behind other elements (see image below).

![image](https://user-images.githubusercontent.com/39308834/147136099-c528299a-1a0f-4900-b662-5cada5691edd.png)

### Operating system

Ubuntu 21.10

### Application version

Element Nightly version: 2021122001 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
from the modals semantic headers work

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by ankur12-1610** [comment]
> from the modals semantic headers work

Agh! I'm able to solve this problem by assigning a background color to the `TabView`, white in light mode and black in dark mode. Although I'm not sure if it is the right way to do so:sweat_smile:?

**Comment by ankur12-1610** [comment]
I've raised a PR kindly review:sweat_smile:.

**Comment by t3chguy** [comment]
Design:
![image](https://user-images.githubusercontent.com/2403652/148196576-05745f58-0c09-4acf-94aa-f57f14c225cf.png)
