### ISSUE TITLE
Custom themes are broken

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20336]
### Steps to reproduce

1. Use a custom theme, for example:
```
"custom_themes": [
                {
                    "name": "Aarenet",
                    "is_dark": false,
                    "fonts": {
                        "faces": [
                            {
                                "font-family": "Inter",
                                "src": [{"url": "/fonts/Inter.ttf", "format": "ttf"}]
                            }
                        ],
                        "general": "Arial, sans",
                        "monospace": "'Courier New'"
                    },
                    "colors": {
                        "accent-color": "#2985ff",
                        "secondary-content": "#2e475d",
                        "primary-color": "#2985ff",
                        "warning-color": "#ff3f54",
                        "sidebar-color": "#8ea3b1",
                        "roomlist-background-color": "#f0f5f8",
                        "roomlist-text-color": "#2e475d",
                        "roomlist-text-secondary-color": "#2e475d",
                        "roomlist-highlights-color": "#ffffff",
                        "roomlist-separator-color": "#ffffff",
                        "timeline-background-color": "#ffffff",
                        "timeline-text-color": "#2e475d",
                        "timeline-text-secondary-color": "#2e475d",
                        "timeline-highlights-color": "#f0f5f8",
                        "username-colors": ["#ff3f54","#ff3f54","#000000","#2985ff","#000000","#2985ff","#000000","#2985ff"],
                        "avatar-background-colors": ["#ff3f54","#2985ff","#000000"]
                    }
                }
            ]
```

2. check the colors.

Here is a video showing this:
https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/Edfsgn8ZTT5Clnf7WnctiCsBSOUlDpawlTD-4f1bfnoF_w?e=tJAmd9

#### What did you expect?
Themes to not be broken.
Maybe an update on https://github.com/vector-im/element-web/blob/develop/docs/theming.md or a mention in the changelogs?

#### What happened instead?
Themes are broken.
Maybe it's this? :
https://github.com/matrix-org/matrix-react-sdk/pull/7271

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

localhost

### Application version

Element version: 1.9.8 built with the version tags

### Homeserver

private server

### Will you send logs?

No

**Comment by t3chguy** [comment]
That looks more like the theme itself is broken based on the colours it chooses not offering enough contrast based on other parameters?

**Comment by chagai95** [comment]
That is definitely an issue but the color should not be green, that's my main point here.

**Comment by t3chguy** [comment]
> but the color should not be green

You might need to be more specific as to which colour out of hundreds in a nearly two minute video.

**Comment by chagai95** [comment]
Sorry, I mean the $accent-color which is green on Element and should be blue according to my example config, #2985ff

**Comment by SimonBrandner** [comment]
> Sorry, I mean the $accent-color which is green on Element and should be blue according to my example config, #2985ff

Ah, change it to just `$accent`, I've been doing a lot of CSS cleanup to allow for better theming and make writing new code easier and the change from `$accent-color` to `$accent` was a part of that

**Comment by chagai95** [comment]
Thanks, that's the missing link, I'm really sorry for being so bad at communicating, I rewatched the video and I see how difficult it was to actually understand what my problem was, thanks for understanding me anyway!

**Comment by SimonBrandner** [comment]
> Thanks, that's the missing link, I'm really sorry for being so bad at communicating, I rewatched the video and I see how difficult it was to actually understand what my problem was, thanks for understanding me anyway!

np! Feel free to visit https://matrix.to/#/#element-themes:raim.ist people in there tend to know what's going on with custom themes/may be able to help

Closing as I am assuming this is fixed now, let me know if something is still causing issues
