### ISSUE TITLE
Collapsed view of new LeftPanel needs design

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2033]

**Comment by ara4n** [comment]
particularly how to handle the sticky headers

**Comment by aperezdc** [comment]
Also, when there's activity in a room, it shows with its name in bold when the left sidebar is expanded, but when the sidebar is collapsed rooms with activity are not marked in any distinguishable way. Mentions do make a badge with the number of notifications appear, though. One way could be to add an “empty badge” (without a number) to indicate rooms with activity but no mentions.

**Comment by alex-mayorga** [comment]
![riot](https://cloud.githubusercontent.com/assets/649262/21526278/97c8e71a-cce8-11e6-8c84-482e4b62d85a.PNG)

FWIW, the current sad state of affairs...

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
