### ISSUE TITLE
flickering white rectangles

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20346]
### Steps to reproduce

I can't nail this down 100% but it happens now and again, seems worthy of an issue. Here is what happened this time:

1. receive a couple images (m.image) with text descriptions (m.text) in between from element iOS in a e2ee group of 4 participants. sender and receiver are xsigned, but not all participants are.
2. scroll around to view all the images, hovering the mouse over the timeline
3. also move the mouse around the timeline a bit from image event to image event

#### What happened instead?
White squares (maybe rectangles, happened to screenshot a square?) flicker over the timeline but also outside like on the room info etc as the mouse hover events occur on the timeline. Haven't seen them on the room list. White square sizes are all similar if not the same.
![image](https://user-images.githubusercontent.com/2803622/147349340-bf85899d-9107-4f18-bffe-1474d3c662d3.png)

Switch the room or whatever and it doesn't happen again, so it seems to be something unstabled when receiving these while viewing the room.

### Operating system

arch + sway + ozone

### Application version

Element Nightly version: 2021122301 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
#20341 could be related

**Comment by gsouquet** [comment]
I have not been able to reproduce this yet.
My gut feeling tells me this has to do with Electron, have you encountered this issue when using a web based Element?

**Comment by HarHarLinks** [comment]
No, but then again I use desktop all day everyday and develop.element.io at most once a week to debug something that requires another account.

**Comment by gsouquet** [comment]
Would you be able to share the screenshot you're mentioning in the original message?
That would maybe help to give me a lead to investigate this further

**Comment by HarHarLinks** [comment]
it appears I uploaded a screenshot of something else ("text message in between", weird) when I opened this issue, I will update when it happens again.

**Comment by kittykat** [comment]
I can't reproduce it on Arch / GNOME / Wayland in the 2022010701-1 nightly aur package
