### ISSUE TITLE
Can't join tab-completed room names.

### ISSUE THREAD

**Issue by emilio** [vector-im/element-web#20343]
### Steps to reproduce

1. Try to switch rooms by using `/join #room-name` from the current chat.
2. Autocomplete the room name using the tab key. So, if I want to join the `#developers` room, I type `/join #d<tab>`
3. Press enter.

#### What did you expect?

Joining the room.

#### What happened instead?

```
Command error
Usage: /join <room-address>
```

I think this used to work at some point in the past.

![Screenshot from 2021-12-23 22-46-29](https://user-images.githubusercontent.com/51663/147297389-19b71137-7d36-46e2-881d-25d65dbb4e76.png)

### Operating system

All

### Browser information

All

### URL for webapp

chat.mozilla.org

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

mozilla.org

### Will you send logs?

No

**Comment by emilio** [comment]
(Happy to send logs if needed, I just thought that they shouldn't be needed since it is trivial to reproduce)

**Comment by emilio** [comment]
I'm happy to try fixing it btw (vacations are going to be a bit boring due to covid anyways :/). Any pointer to the relevant code would be appreciated, but otherwise I'll try to look into this after Christmas :)

**Comment by t3chguy** [comment]
Matrix react sdk
SlashCommands.tsx

Though also keep in mind that you can only tab complete rooms you're already in so it's a little moot for this to function

**Comment by emilio** [comment]
Well, `/join` not only joins, it also also switches to that room. I use it to not have to use the mouse to switch to another room I'm already in.

**Comment by t3chguy** [comment]
Why not use the dedicated quick switch shortcut

Ctrl/Cmd + K
Type your query
Hit enter

**Comment by emilio** [comment]
I didn't know that shortcut :-)
