### ISSUE TITLE
Make sure that location sharing is compatible with with Neochat and Fluffychat in both directions

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-web#20344]
### Your use case

First a disclaimer: Soru has not used element-web's location yet, but this issue is to prevent something like the voice message fiasco from happening again. Currently NeoChat and FluffyChat both implement location sharing via the standard `m.location` event. So basically, to remain compatible, the element clients should also render the location sharing properly if the extensible parts are absent, and make sure that the fallback to the extensible stuff is present properly, so that locations shared in element are displayable in other clients and vice-versa.

**Comment by Sorunome** [comment]
Tulir just said

> element web's location support does support m.location, I tested it with the telegram bridge soon after it appeared

**Comment by Sorunome** [comment]
and then travis

> I'm a bit more concerned about the mobile apps tbh

**Comment by tulir** [comment]
Mobile app issues might find the right people more effectively if posted to the mobile app repos

**Comment by andybalaam** [comment]
I will check this and update this issue.

**Comment by andybalaam** [comment]
I will try sending locations from/to the following an update this issue:

- [ ] Fluffychat Android -> Element Web
- [ ] Fluffychat Android -> Element Android
- [ ] Element Web -> Fluffychat Android
- [ ] Element Android -> Fluffychat Android
- [ ] NeoChat (linux, snap) -> Element Web
- [ ] NeoChat (linux, snap) -> Element Android
- [ ] Element Web -> NeoChat (linux, snap)
- [ ] Element Android -> NeoChat (linux, snap)

If others are able to follow up with other combinations, please do.

**Comment by andybalaam** [comment]
Element Web -> NeoChat displays locations as text, which is similar to what you see when you share FluffyChat -> NeoChat, so I am assuming this is ok.

**Comment by stefanceriu** [comment]
- [x] Fluffychat iOS -> Element Web
- [x] Fluffychat iOS -> Element iOS
- [x] Element Web -> Fluffychat iOS
- [x] Element iOS -> Fluffychat iOS
