### ISSUE TITLE
Document the new theming attributes (please 🙈)

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20342]
### Steps to reproduce

Use a custom theme.

### Outcome

I understand now it's not [broken](https://github.com/vector-im/element-web/issues/20336) just not documented anywhere (besides in the code 😉) :

```
$accent: var(--accent, $accent);
$alert: var(--alert, $alert);
$links: var(--links, $links);
$primary-content: var(--primary-content, $primary-content);
$secondary-content: var(--secondary-content, $secondary-content);
$tertiary-content: var(--tertiary-content, $tertiary-content);
$quaternary-content: var(--quaternary-content, $quaternary-content);
$quinary-content: var(--quinary-content, $quinary-content);
$system: var(--system, $system);
$background: var(--background, $background);
$panels: rgba($system, 0.9);
$panel-base: var(--panel-base, $tertiary-content); // This color is not intended for use in the app
$panel-selected: rgba($panel-base, 0.3);
$panel-hover: rgba($panel-base, 0.1);
$panel-actions: rgba($panel-base, 0.2);
$space-nav: rgba($panel-base, 0.1);
```
Here is a video showing how this merge affected our fork:
https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/Edfsgn8ZTT5Clnf7WnctiCsBSOUlDpawlTD-4f1bfnoF_w?e=tc8mAZ

Could you describe these variables somewhere?

accent-color became accent
I think quinary-content is also new and was used at least for hovering over a room name and the dial pad background and I think the background of the filter box when clicking on it and maybe the line between the filter and the room sections, I used timeline-highlights-color, roomlist-background-color for that color before, so I just changed that to also use the same color they did.

If this is out of scope for the Element public repo I would appreciate you saying this and I'll report this issue on Jira/GitLab/#element-themes:raim.ist or where ever else you think is good? Every time there is a change with this, it would be very important for us to know and not have to just discover this by accident...

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

private server

### Application version

 1.9.8

### Homeserver

private

### Will you send logs?

No

**Comment by gsouquet** [comment]
Removing the "Help Wanted" attribute as we currently do not have a clear solution for this problem.
It definitely needs to be solved but I'm not confident one can jump straight in this issue. If you're interested in working on this, you should probably first raise that in the Element dev matrix room

**Comment by Johennes** [comment]
Closing since theming will change with Compound, so we shouldn't invest here anymore
