### ISSUE TITLE
Ability to morph rooms into sub spaces

### ISSUE THREAD

**Issue by Flam3z** [vector-im/element-web#20351]
### Use case
As communities tend to grow especially back when only rooms were a thing I highly suggest a feature where the owners or staff have the ability to change said room into a sub space for better organization.

### Additional context
I found an [issue](https://github.com/vector-im/element-web/issues/16992) that maybe similar to mine and if so i'll gladly let it be marked as a duplicate

**Comment by t3chguy** [comment]
Rooms cannot be made into spaces, that property is immutable in the way the spec defined it.

**Comment by HarHarLinks** [comment]
I'm sure that's technically impossible, but this could be implemented by creating a new space, add the existing room, possibly rename and upgrade it ("visible to space members"), invite everyone in the room to the space. Question is, is it worth creating a simple workflow in the app for this rare case, or should users (admins) just do it by hand (it's only a couple steps!)?

**Comment by kittykat** [comment]
I'm going to close this issue as per above points, but I think #17264 and #20296 is probably of interest to you as it would make sharing spaces with other people easier.
