### ISSUE TITLE
quoting does not work when searching

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20353]
### Steps to reproduce

1. search
2. click quote
3. exit search since composer isn't shown in search (why?!)

#### What did you expect?
quote
#### What happened instead?
no quote in composer

### Operating system

arch

### Application version

Element Nightly version: 2021122301 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by kittykat** [comment]
Can confirm on develop
