### ISSUE TITLE
Add Option for Custom Css / Themes 

### ISSUE THREAD

**Issue by salemgod69** [vector-im/element-web#20352]
#### What would you like to do?
Add an Option where you can add a theme link or on pc etc version a file

#### Why would you like to do it?
To improve the user experience and the look and feel of element

#### How would you like to achieve it?
Add an Option where you can add a theme link or on pc etc version a file

### Additional context

e.g. where this is done would be in Better Discord with the Themes and Custom CSS

**Comment by HarHarLinks** [comment]
This exists (in Labs), see https://github.com/aaronraimist/element-themes

**Comment by SimonBrandner** [comment]
Closing as this feature already exists (even though it is still in development)

**Comment by HarHarLinks** [comment]
> even though it is still in development

i.e. probably a dupe, but I didn't look for it

**Comment by SimonBrandner** [comment]
> > even though it is still in development
> 
> i.e. probably a dupe, but I didn't look for it

Basically this: https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AA-Themes-Custom
