### ISSUE TITLE
custom footer elements?

### ISSUE THREAD

**Issue by Skyfay** [vector-im/element-web#20364]
I use the docker server and would like to know where the information for the footer area of ​​the login page is?

I can't find it in the index.html file.

Unfortunately, my knowledge is at the end of it.

I see the information in developer mode in the browser but cannot assign it.

would be very nice if someone could help me :)

**Comment by aaronraimist** [comment]
See `authFooterLinks` in https://github.com/vector-im/element-web/blob/30cb0ae96dcdee178b33b4fda60a3ad063d4904e/docs/config.md
