### ISSUE TITLE
Recent room bar is confusing on first viewing

### ISSUE THREAD

**Issue by LynHyper** [vector-im/element-web#20366]
#### What would you like to do?

The new recent room bar (not the `develop.element.io` version) behaves very strangely at the moment, especially when you're not scrolled all the way to the left.

If you're located in the middle of the scroll, you'll just stay in the same position, but, you'll observe the scroll instantly jump right by one room and smoothly scroll left to where it just was.

If you're located at the right-most position in the scroll, and the last room (most-right icon) moves somewhere else, the bar overscrolls and hides the icon that was just left of the right-most icon; it appears to scroll two icons left.

The room icons themselves also suddenly disappear when changing location, this makes the animations appear even more jarring when first seen by the user.

#### Why would you like to do it?

Currently, the sudden jump right and smooth scroll left makes it look like the bar is stuck in a loop like it's a bug; it doesn't look intentional on first glance. This animation should only happen when the bar is all the way to the left as other scroll positions behave very strangely with the animation.

There should also be a smooth animation for the icons disappearing or moving instead of having them instantly disappear when changing location.

#### How would you like to achieve it?

I would disable the scroll animation, going instantly right then smoothly left, for when the user is anywhere except the left-most scroll position. Maybe adding different animations for the middle and right-most scroll positions.

### Additional context

I hope this doesn't come across as harsh, I do like the addition of the recent room bar and think it should definitely stay in the UI, hopefully this feedback is helpful to the Element team.

**Comment by toger5** [comment]
The recent rooms are being redesigned atm. I am not sure if you are talking about the "new" new design or the current design? Since you are referring right/left scrolling, I think you are talking about the "old" new design.

If you want to test the new design and see, if that solves you concerns (this issue):
 - go to develop.element.io
 - go to settings
 - activate `Use new room breadcrumbs` in the labs section.
 click this button:
![image](https://user-images.githubusercontent.com/16718859/147570061-a7515613-7261-4750-9ba0-3a50ecbfba90.png)

**Comment by LynHyper** [comment]
You are correct, I was using the "old" new design.

I've tested the version at``develop.element.io` with the Lab setting enabled and it's definitely an improvement, however, the fact that the button replaces the room search button doesn't seem ideal; it's not very intuitive how you should search the public room list without the button there.

**Comment by LynHyper** [comment]
I think I'll close this issue, the original feedback was for the "old" new design so it won't be relevant for the `develop.element.io` version that exists. I'll create a separate issue for the new design when it's ready. Thanks for your help!
