### ISSUE TITLE
Grey text in Preferences in wrong location

### ISSUE THREAD

**Issue by LynHyper** [vector-im/element-web#20365]
### Steps to reproduce

1. Navigate to Settings, Preferences
2. Look at the grey text right of "Show all rooms in Home" and "Display Communities instead of Spaces"
3. See the grey text is to the right of the normal text instead of under it

#### What did you expect?

Grey text should be underneath the normal text like it is in other menus

#### What happened instead?

Grey text is placed to the right of the normal text with no gap between them

### Operating system

Arch Linux

### Application version

Element version: 1.9.8, Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by toger5** [comment]
Thanks for spotting the visual bug and opening the issue!
