### ISSUE TITLE
new post indicator too late

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#20363]
### Steps to reproduce

I go to the Favorites in Edge
I see the Favorite for Element
Sometimes there is an indicator that there is new post

### Outcome

I expect the indicator to appear before I read the new post
The indicator appears after I read the new post

### Operating system

Windows 10

### Browser information

Edge Versie 96.0.1054.62 (Officiële build) (64-bits)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by aaronraimist** [comment]
Can you take a screenshot of the indicator? I'm assuming you are talking about the badge that appears next to the favicon? If you don't have any tab for Element open already there probably isn't any way for that badge to update.

**Comment by ctjacobs2** [comment]
![New posts](https://user-images.githubusercontent.com/96727905/147573964-0cb18d31-2e4b-42fd-9eb2-3c95a36d0670.PNG)
![no new posts](https://user-images.githubusercontent.com/96727905/147573977-47a1a0b1-9f4b-4862-84f5-66f3463a44c6.PNG)

**Comment by t3chguy** [comment]
> If you don't have any tab for Element open already there probably isn't any way for that badge to update.

Yeah this sounds like precisely this. Element can't update the Favicon that your browser stores for its favourites when it isn't open.

**Comment by ctjacobs2** [comment]
@t3chguy just repeats a suggestion already made by @aaronraimist and the re-ads the X-Needs-Info label.
I already gave the info @aaronraimist asked.

**Comment by t3chguy** [comment]
You never answered if the tab is open/running or not.

**Comment by ctjacobs2** [comment]
You never asked that. But evidently the tab is open when I read the new posts. So if a closed tab is the problem then the new post favicon would not appear after I read the new posts. It would appear never!

**Comment by t3chguy** [comment]
Element Web does not run when it isn't in an open tab, what favicon your browser persists is entirely up to it.

**Comment by jryans** [comment]
This seems difficult to act on since the user is now gone and we can't ask any further questions, so seems best to close.
