### ISSUE TITLE
Editing a comment increases notification count even if comment is unread.

### ISSUE THREAD

**Issue by Caspy7** [vector-im/element-web#20377]
I'm going on the assumption that when my name is mentioned in a comment, edited comments are intended to increase the notification count.

I came back from being offline and Element said I had two unread notifications in a channel. When I went to read them it turns out it was just one comment that had been edited. 

Other users may not understand this is what's happening and the count is still misleading for those that do. Can we negate the notification count addition for comments that are edited but unread? That is, if I've not yet read a message there's no need to +1 the count on edit.

edit: I'm on Windows 10, Firefox Nightly 97.0a1 (2021-12-29) (64-bit), Element version: 1.9.8 Olm version: 3.2.8 (chat.mozilla.org)

**Comment by kittykat** [comment]
@Caspy7 thank you for filing the issue, can you please update your description to include which platform you are using, which version of the app and details of your browser.

It would be great if you could use the correct bug template next time as it helps us triage the issue more effectively and implement a fix faster :+1:

**Comment by Caspy7** [comment]
I was linked here and clicked New Issue and don't recall seeing a template.

I've updated the initial description.

**Comment by kittykat** [comment]
Thank you for updating with more details :+1:  If you use the "New issue" button top-right of here, you should see [this page](https://github.com/vector-im/element-web/issues/new/choose) where the first two options are templates for bugs in desktop and web apps

**Comment by SimonBrandner** [comment]
I can repro, this is due to there being no sane way to know whether the event is an edit or not. In encrypted rooms we only see event type as `m.room.encrypted` until the message is decrypted, that is where we run into the same issues as with https://github.com/vector-im/element-web/issues/7941. In non-encrypted rooms/once the event is decrypted we'd have to check the event content to figure out if it is an edit, I don't think push rules mechanisms are really prepared for this

**Comment by HarHarLinks** [comment]
I can repro too. It can really be confusing: why is there only 1 new message, am I missing messages in threads or another place?

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22234
