### ISSUE TITLE
"Failed to save your profile" when updating the display name

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-web#20375]
On my main account, using Firefox 95 on MacOS Monterey 

Every time I change my display name from the settings, I get a dialog after a few seconds:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/3940906/147736361-967f0289-3ef5-4f8f-b2c6-1ba6bb5585f3.png">

Note that the display name is actually updated correctly and all my rooms get the membership event.

**Comment by t3chguy** [comment]
This is a Synapse issue, it times out the request even though it continues to work on it in the background.

**Comment by bmarty** [comment]
Thanks. You are right, I also have a timeout when changing my display name (successfully) using Element Android.
I transfer the issue to Synapse.
