### ISSUE TITLE
Left panel space menu opens create dialogs when rooms or spaces are added

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20373]
### Steps to reproduce

1. Right click on a space
2. Under "Add", select room or space

![Screenshot from 2021-12-29 11-55-27](https://user-images.githubusercontent.com/51663/147659786-b15ff99e-1a57-4c71-931e-b1be627b5447.png)

#### What did you expect?
I can add existing rooms

#### What happened instead?
Create dialogs open

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20222
