### ISSUE TITLE
Timestamps on membership events are mispositioned

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20379]
### Steps to reproduce

1. Enable message bubble layout
2. Hover over any membership event

### Outcome

![Screenshot 2021-12-31 at 10-38-06 Element #element-dev matrix org](https://user-images.githubusercontent.com/48614497/147830864-9d5adb11-72d1-4e55-abdb-4b11319b237e.png)

#### What did you expect?

The timestamp should be aligned with the membership event and have some space between it and the edge of the timeline.

#### What happened instead?

The timestamp is at the very edge of the timeline.

### Operating system

NixOS unstable

### Browser information

Firefox 95.0

### URL for webapp

develop.element.io

### Application version

Element version: 211f48002759-react-e759a8532172-js-f30be8787934 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by amshakal** [comment]
Thanks for pointing this out. For this, we can stick to the same aignment of these components like we have on modern layout. Screenshot for ref:
<img width="859" alt="Screenshot 2022-01-13 at 5 16 37 pm" src="https://user-images.githubusercontent.com/85162587/149324791-3022c405-8c8c-4641-b3ad-c7926ad5a762.png">
