### ISSUE TITLE
Searches rooms should ignore leading or trailing spaces

### ISSUE THREAD

**Issue by QEDeD** [vector-im/element-web#20388]
### Steps to reproduce

1. Try to search for a known room, e.g. #serpentos:matrix.org
 
![image](https://user-images.githubusercontent.com/16562457/147881428-3b5fff5b-d9b8-43b2-a260-7ab63d8a65ac.png)

2. Add a space at the beginning or end of the room's ID - now you don't get any results
![image](https://user-images.githubusercontent.com/16562457/147881415-4e9b6609-8640-40da-8298-f56f51f09177.png)

#### What did you expect?
The search field should ignore/remove leading and/or trailing spaces 

#### What happened instead?
Adding a space ruins the search 

### Operating system

PopOS

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by uhoreg** [comment]
This seems like a good candidate for the "good first issue" label.

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7431

**Comment by QEDeD** [comment]
Thanks for the fix @twigleingrid

**Comment by twigleingrid** [comment]
Oh, great! Happy that I pre-caught it!
