### ISSUE TITLE
I can’t fix home server address, cannot delete.

### ISSUE THREAD

**Issue by gabrix73** [vector-im/element-web#20389]
### Steps to reproduce

I entered the homeserver address in the appropriate box, wrong format (without mentioning the https protocol) ok, but now I can not delete and write properly. The wrong address remains there and I can’t fix it, here’s the screenshot. I used several browsers and several different machines but the problem persists.
The error is not possible to identify in any log.
Element-web and matrix-synapse-py3 are installed on the same VPS.
Element-web is at this url: https://element.virebent.art, also check you

![Screenshot from 2022-01-03 13-21-13](https://user-images.githubusercontent.com/24553253/147929974-7fafc0e7-f718-43ef-8d88-975067a50015.png)
![Screenshot from 2022-01-03 13-22-20](https://user-images.githubusercontent.com/24553253/147929976-d4cb312e-375a-4804-bc3c-675633886dec.png)

### Outcome

Being able to correct with the address in the right format

### Operating system

Kali Linux

### Application version

element-v1.9.8.tar.gz

### How did you install the app?

https://github.com/vector-im/element-web/releases/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Could you check your developer console to see whether any error is reported there?
Could help to figure out what the problem is

**Comment by t3chguy** [comment]
I can't even get to that stage

![image](https://user-images.githubusercontent.com/2403652/148225888-7669ea5f-31af-4a14-a65d-09f259cf9031.png)

**Comment by gabrix73** [comment]
> Could you check your developer console to see whether any error is reported there? Could help to figure out what the problem is

Yes and it is in brakets:
`<span class="mx_ServerPicker_server">matrix.virebent.art</span>`

**Comment by gabrix73** [comment]
i think i understood what the problem is. I'm new to matrix-synapse.

**Comment by t3chguy** [comment]
https://element.virebent.art/#/login looks fine now
