### ISSUE TITLE
Pasted images don't show up

### ISSUE THREAD

**Issue by lnicola** [vector-im/element-web#20391]
### Steps to reproduce

1. Paste an image (might also happen with uploaded ones)
2. Notice the missing preview
3. Notice how you can't open it (clicking the pill downloads the image)

### Outcome

![image](https://user-images.githubusercontent.com/308347/147946488-66a8c2be-d0be-4afd-9da7-95d26286dce5.png)

### Operating system

Linux

### Browser information

Firefox 97 Nightly

### URL for webapp

self-hosted 1.9.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Can you send logs please, this happens when your browser can't process the image locally to generate a thumbnail.

**Comment by lnicola** [comment]
Uploaded some logs.

**Comment by t3chguy** [comment]
You're using an unstable Firefox version which enables a partially-implemented experimental API which makes things explode. This will be fixed in subsequent versions but for now you can disable offscreencanvas api in flags
