### ISSUE TITLE
Optimize the UI for password manager (KeepassXC)

### ISSUE THREAD

**Issue by Kreyren** [vector-im/element-web#20390]
I am unable to fill in the **Secret Key** after login from KeepAssXC using one-click on GNU IceCat (theoretically any firefox-based browser).

Doesn't work (In matrix):
![2022-01-02_11-29](https://user-images.githubusercontent.com/11302521/147942695-d3b8218a-a715-4f6e-bfb5-0aa5590befea.png)

Works (In Discord):
![2022-01-03_15-32](https://user-images.githubusercontent.com/11302521/147942677-49b1cc68-74c0-4e38-82d4-e5b5d9ffb63e.png)

I assume that the current UI in element is making it difficult for keepassxc to find the field so i created this here

### Steps to reproduce
0. Get KeepAssXC on desktop
0.1. Create a password database with your credentials for matrix account
0.2. Install any Firefox-based browser, install the `KeeAssXC-Browser` extension on it and link the extension to your desktop database.
1. Try to log-in through element-web on matrix through one-click and expect to need to use Copypasting from the app

### Expected
Log-in to matrix using KeepAssXC by using one-click per field.

#### Element-web is keep changing the identifier
The element-web seems to be changing the `mx_field_NUM` everything i press `Go Back` on the login screen.

#### Login process on discord
1. Fill ID and PW
2. Fill TOPT
3. Fill `SDC_PASSWORD` which is defined in additional attributes in keepassxc

Note: PW and SDC_PASSWORD are **NOT** same

#### Usage of SimpleDiscordCrypt on Discord
I am using SimpleDiscordCrypt on Discord that provides the E2EE and requires password after TOPT

#### Discussion with KeepassXC Developers
https://matrix.to/#/!EcUZQSzumzSBRdQSRU:vi.fi/$KTMn21Pfh2ZZgetS2Sv6Ci6G95iL9-UWhJCVqrB5ny8?via=matrix.org&via=libera.chat&via=mozilla.org

### Metadata

**OS:** GNU Guix (b7078d5d49d72cb5e5356d698b99540612b4d6c4)
**Arch:** x86_64
**Web Browser:** GNU IceCat (91.4.0-guix0-preview1)
**KeepAssXC Version:** 2.6.6 (9c108b9) / Qt 5.15.2
**KeepAssXC-Browser version:** 1.7.11

---

CC KeepassXC maintainers: @varjolintu @shemeshg @droidmonkey

**Comment by SimonBrandner** [comment]
@Kreyren, does https://github.com/matrix-org/matrix-react-sdk/pull/7489 solve your issue?
