### ISSUE TITLE
Add state reset detection

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#20394]
#### Why would you like to do it?
Due to decentralised nature of Matrix, the room state is somewhat append only but nothing except initial creation is considered final.
#### How would you like to achieve it?
Servers such as Synapse try to handle this by soft-failure. It turns out some of this soft-failure logic can be applied in the client side also, not in order to fail the events, but in order to detect state resets that arose in the room due to oncoming federation events.
#### Additional context
This detection does not have to be 100 percent reliable, I would be more than happy if it detected the most obvious ones and some non-obvious ones.

**Comment by gsouquet** [comment]
I'm not sure I grasp what you're suggesting.
Could you maybe give some steps to end up in the state you're offering to enhance?

**Comment by erkinalp** [comment]
The types of state resets I am referring to is things like events disappearing away from the room state without redaction. To detect such state resets, a client would need to do a full state fetch (currently doable by initial sync or federation fetch using client credentials) of the room, compare the recently received state to what it currently stores in its cache, and throw a warning if an event disappears or authorisation status of an event changes with no corresponding authorising event change, when compared to what it previously stores. This would obviously be expensive, hence this feature should be disabled by default when implemented.

**Comment by turt2live** [comment]
This is not a thing we can practically do at a client level. We should just fix state resets.

**Comment by erkinalp** [comment]
September 2025 matrix.org failure has shown why this has always been necessary.
