### ISSUE TITLE
Missing session data in the app

### ISSUE THREAD

**Issue by nahuelwexd** [vector-im/element-web#20396]
### Steps to reproduce

I really have no idea how to reproduce it, it's been happening to me in a somewhat random way, but it always requires that:

1. open the app
2. The screen keeps loading eternally
3. Close the app
4. Open the app again
5. The app displays a "Missing session data" dialog.

#### What did you expect?
The app starts correctly

#### What happened instead?
The app shows a "Missing session data" dialog and I have to log in again.

### Operating system

Fedora 35.20211226.0 (Silverblue)

### Application version

1.9.8

### How did you install the app?

From Flathub

### Homeserver

matrix.org

### Will you send logs?

No, it doesn't allow me, I get "no connected database".

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18625

**Comment by leanneeliatra** [comment]
I am having this same issue and can't use element as a result.
