### ISSUE TITLE
Message action bar can block interaction with sender info

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20404]
### Steps to reproduce

1. Enable message bubble layout
2. Receive any short message
3. Attempt to click on the avatar or display name of the sender

### Outcome

![safe zone](https://user-images.githubusercontent.com/48614497/148118837-5ff7c91c-b06c-4a59-b462-c4414bb983f4.png)

#### What did you expect?

To be able to click on the avatar and display name.

#### What happened instead?

The message action bar obscures the display name, preventing me from using click-to-mention, and the "interaction safe zone" for the bar, which extends further to the left, blocks interactions with the avatar, preventing me from opening their user info.

### Operating system

NixOS unstable

### Browser information

Firefox 95.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 211f48002759-react-00feb248778a-js-f30be8787934 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
I think these are related: https://github.com/vector-im/element-web/issues/20403

**Comment by daniellekirkwood** [comment]
We're going to push the MAB to be right-aligned with a left-margin.
![20404](https://user-images.githubusercontent.com/89144281/149933382-805215cb-9f39-420d-a5c0-44f46963f151.png)
