### ISSUE TITLE
Narrow images cause message action bar to overflow timeline

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20403]
### Steps to reproduce

1. Enable message bubble layout
2. Receive any tall, narrow image
3. Hover over the image

### Outcome

![mab](https://user-images.githubusercontent.com/48614497/148118110-b8c4f1a1-c8dd-4dff-ab06-087b2668fa50.png)

#### What did you expect?

To be able to see and interact with the entire message action bar.

#### What happened instead?

The message action bar overflows the timeline off to the left, causing some options to not be visible.

### Operating system

NixOS unstable

### Browser information

Firefox 95.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 211f48002759-react-00feb248778a-js-f30be8787934 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
Hey @t3chguy - What's the question that we'd like Design to answer here? 

Regardless the width of the image, the hover over menu should always be actionable. I think we need to know whether the action bar show up over-top of the left Room list, or if we move it to the right to stay in the Timeline - would you agree?

**Comment by t3chguy** [comment]
> I think we need to know whether the action bar show up over-top of the left Room list, or if we move it to the right to stay in the Timeline - would you agree?

Precisely

**Comment by amshakal** [comment]
Hi, for images exceeding the action bar width, we should stick to the current solution but for images narrower than the action bar we should move it to the right and below the username/ID. Here is an example:
<img width="533" alt="Screenshot 2022-01-12 at 4 22 56 pm" src="https://user-images.githubusercontent.com/85162587/149126974-f785d988-8005-4375-8179-7cc4a6830bb4.png">

**Comment by t3chguy** [comment]
@amshakal the above confuses me slightly

Current MAB positioning is slightly above to not overlap the event/image/text too much:

![image](https://user-images.githubusercontent.com/2403652/149362752-5f29da36-c8db-4c0b-80af-2403e9c153bc.png)

If I apply the vertical changes it looks very strange

![image](https://user-images.githubusercontent.com/2403652/149362799-f0ef86f9-b489-469b-827d-d5d720d100f9.png)
![image](https://user-images.githubusercontent.com/2403652/149362826-da5b5909-8b76-4050-bd2d-912ce1a84ca5.png)

Also this issue not only affects the MAB but also timestamps on very narrow images, so may need more design input on that aspect too.

![image](https://user-images.githubusercontent.com/2403652/149362910-e3981a03-57c6-4f26-aa20-f96589899013.png)

**Comment by daniellekirkwood** [comment]
> @amshakal the above confuses me slightly
> 
> Current MAB positioning is slightly above to not overlap the event/image/text too much:
> 
> ![image](https://user-images.githubusercontent.com/2403652/149362752-5f29da36-c8db-4c0b-80af-2403e9c153bc.png)
> 
> If I apply the vertical changes it looks very strange

As the MAB is only visible on Hover I think it's okay to obscure the image/content a little. It allows the user to interact with the clicks on the message (MAB, Avatar, Username) and if they want to see the content, they can mouse over elsewhere and back. It's not perfect, but let's go with it for V1 and re-raise if needed in V2.

**Comment by t3chguy** [comment]
> Also this issue not only affects the MAB but also timestamps on very narrow images, so may need more design input on that aspect too.

Still needs input on this regard

**Comment by daniellekirkwood** [comment]
After discussing this issue and the technical limitations we have there are a few options: 
- Do not fix for the first launch
- Spend (too much) time trying to get this to work as desired, or
- Move the MAB to be always left-aligned

@amshakal I do not think that moving the MAB to be left-aligned is an option we want to pursue right now, can you confirm?

**Comment by t3chguy** [comment]
> Move the MAB to be always left-aligned

(for left-column, messages sent by the other user, can be restricted to media events too)

**Comment by daniellekirkwood** [comment]
Scratch that, we're going to right-align the MAB with a left margin
![20403](https://user-images.githubusercontent.com/89144281/149933438-3c7c0562-aac5-4494-b0e6-3bd9653cb0c5.png)


this does not solve the timestamp issue - let's not try and solve timestamp issues in this GH. We'll raise a new one just for timestamps across bubbles
