### ISSUE TITLE
Crash on sending a threaded message

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20407]
### Steps to reproduce

1. Start a new thread
2. Send message

### Outcome

Message sent and a crash (rageshake attached)

### Browser information

Version 96.0.4664.110 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 211f48002759-react-00feb248778a-js-f30be8787934 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by toger5** [comment]
rageshake:
[rageshake.zip](https://github.com/vector-im/element-web/files/7815230/rageshake.zip)
