### ISSUE TITLE
Add ability to view homeserver type and version in Element interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#20416]
#### What would you like to do?
We need an easy way to check the type (Synapse, Dendrite, etc) and version of currently connected homeserver in Element interface. Also list of supported API versions and features will be good to see too.

#### Why would you like to do it?
When reporting bugs or talking about some issues, very often type and version of homeserver are important. And to check them, now user must gather the information manually via technical urls like `/_matrix/client/versions` and `/_matrix/federation/v1/version`? That's not good!

#### How would you like to achieve it?
Add more information about homeserver into "Help & About" page in Settings, near to homeserver url. I guess Element already read this information for technical needs, so we just need to show it to user.

**Comment by t3chguy** [comment]
There is no Client API for getting this information. The client should not be accessing /federation/ APIs.

**Comment by turt2live** [comment]
I don't believe this information will be useful to the average user, and developers should be more than able of figuring it out. For rageshakes and bug reporting there's https://github.com/vector-im/element-web/issues/11070 which I think this functionality would be most useful in.

**Comment by t3chguy** [comment]
and for the record its already in /devtools -> Server Info
