### ISSUE TITLE
Avatar in composer flickers while typing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20421]
### Steps to reproduce

1. Go to the composer in a chat
2. @ someone
3. Start typing

#### What did you expect?
Avatar does not flicker

#### What happened instead?
Avatar flickers at every keystroke

https://user-images.githubusercontent.com/51663/148399408-65610fbb-9844-4767-b5b2-119304b93eae.mp4

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Yesterday's version at 10:34

### Will you send logs?

No

**Comment by t3chguy** [comment]
@kittykat can you reproduce this on app? Last I checked this was an artifact of React's development mode being less efficient at reconciling.

**Comment by t3chguy** [comment]
Yup do reopen if you spot on app though please
