### ISSUE TITLE
Warn user about search index issues when searching

### ISSUE THREAD

**Issue by Popkornium18** [vector-im/element-web#20427]
### Your use case

Currently there is no indication that something is wrong with the search index when using the search function. It just doesn't return any result.

This happened to me and a quick look in the settings revealed that the search index database could not be decrypted due to a wrong password. (Resetting fixed the issue)

I think it would be great if element would warn the user about problems like that when using the search function.

**Comment by aaronraimist** [comment]
What version of Element are you using and how did you install it? There is an error displayed below the search field for me (though it is poorly styled, which is https://github.com/vector-im/element-web/issues/19245).

<img width="963" src="https://user-images.githubusercontent.com/5855073/148673352-cc05e9bc-75d3-40b9-ad62-1a932f0565ed.png">
<img width="522" src="https://user-images.githubusercontent.com/5855073/148673368-a3ccf210-4816-4467-8160-6d1b189cb2d9.png">

**Comment by Popkornium18** [comment]
I am using 1.9.8 from the official Arch Linux repositories. Maybe I missed that message. Is there a way to intentionally break the database, so I can check again?

**Comment by aaronraimist** [comment]
The database is inside the `EventStore` folder located here https://github.com/vector-im/element-desktop#user-specified-configjson

You can move `events.db` somewhere else and create a text file or some other invalid file called `events.db`.

**Comment by Popkornium18** [comment]
There is an error message. My bad.

**Comment by alisafa1371** [comment]
> The database is inside the `EventStore` folder located here https://github.com/vector-im/element-desktop#user-specified-configjson
> 
> You can move `events.db` somewhere else and create a text file or some other invalid file called `events.db`.

why there is no EventStore folder in the link you sent ? how can I find this folder ? thanks
