### ISSUE TITLE
Getting 'missing translation: en-us|counterpart|pluralize' on Jan 6th, 2022 nightly

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20426]
Noticed during upload:

![](https://i.imgur.com/a7ctRQB.png)

**Comment by gsouquet** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/9422

**Comment by MTRNord** [comment]
This is still happening on develop with https://github.com/matrix-org/matrix-react-sdk/pull/7476 deployed.

**Comment by kerryarchibald** [comment]
Reopening, this can still occur when translations exist for *some* pluralizations, but not the pluralization being called.

**Comment by t3chguy** [comment]
@kerryarchibald whats the context to this getting re-opened? is it not fixed in the end?

**Comment by kerryarchibald** [comment]
@t3chguy My fix introduced another regression - all pluralized strings are defaulted to english. (Comment here: https://github.com/matrix-org/matrix-react-sdk/pull/7480#issuecomment-1007775904)

**Comment by t3chguy** [comment]
Ah right, would have been saner to open a new issue as the title of this issue no longer seems to match the actual bug at hand

**Comment by kerryarchibald** [comment]
Closing, non English pluralized strings issue here: https://github.com/vector-im/element-web/issues/20455
