### ISSUE TITLE
"Unable to decrypt: The sender's device has not sent us the keys for this message."

### ISSUE THREAD

**Issue by claell** [vector-im/element-web#20434]
### Steps to reproduce

1. Use element before
2. Use encrypted messages
3. Register a new device (element web in my case)

#### What did you expect?
Messages should display normally
#### What happened instead?
I get the error in the title. Clicking "retrieve keys from other sessions" doesn't work, either.

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by claell** [comment]
Other important information:
Screenshot:
![grafik](https://user-images.githubusercontent.com/6171135/148547891-ef94f2ca-f9d2-4356-bac5-2f968537dad2.png)

Also, I just set up fluffychat on the same device and did not experience this problem there (the same chats can be decrypted there). So I am rather sure this is a bug of element.

Umbrella issue for those problems: #2996 
Unfortunately, I am not experienced enough (and currently also don't have the time) to say whether this issue is a duplicate of one of the issues listed there.

**Comment by claell** [comment]
Not sure, possibly https://github.com/matrix-org/matrix-js-sdk/issues/1866 is the cause for this?

**Comment by claell** [comment]
Hm, out of curiosity, I just signed in on develop.element.io. Then I verified that device from app.element.io (at least I think so, I also needed to type in the security phrase). But then on develop.element.io, I was notified that the app.element.io session still needs verification (which is weird). After I verified app.element.io from develop.element.io, I now could also read the chats there that were previously unable to decrypt. Not sure what caused this (for example, I am rather sure that I have verified app.element.io before, but maybe there went something wrong during that process).

**Comment by claell** [comment]
And now I think that I get the error again for the two most recent messages on develop.element.io (which I think decrypted fine some minutes before). At least the option to request the keys from another session does seem to work for them.

**Comment by claell** [comment]
For another room, it first showed the error for a short time and then displayed most of the messages correctly. However, the error stayed there for some messages. There I had to manually request the keys from another session.

**Comment by kittykat** [comment]
@claell can you please submit rageshakes (logs) from app.element.io, develop.element.io and the device that you originally tried to verify app.element.io against?

**Comment by claell** [comment]
@kittykat Thanks, just sent them for app.element.io and develop.element.io. I am not sure which device I originally (tried?) to verify app.element.io against. Possibly my mobile phone or I used the security phrase without a second device. Unfortunately, I didn't find the log sending option on Android and also `/rageshake` was not recognized there (although the functionality should be there according to https://github.com/vector-im/element-android/issues/33 or am I wrong?).

**Comment by kittykat** [comment]
You can enable rageshakes in the advanced settings and then literally shake your phone to trigger it:

![Screenshot_20220107-174028.png](https://user-images.githubusercontent.com/51663/148584480-94c42b90-f514-416b-b7ad-bf9d569ebad5.png)

**Comment by claell** [comment]
Lol, it is a bit weird that only this option works and both other options (menu or command) are not available for sending stuff. I guess I'll create an issue for that.

**Comment by claell** [comment]
BTW: I didn't have to enable it, it was already enabled for me. Just didn't shake my phone before, as I wasn't familiar with the concept of rageshake before.

**Comment by claell** [comment]
Logs for Android device are also sent out now. I mentioned the number of this issue in the description.

**Comment by claell** [comment]
Followup issue for rageshake on mobile: https://github.com/vector-im/element-android/issues/4881

**Comment by waclaw66** [comment]
Probably the same as https://github.com/vector-im/element-web/issues/19748. Try to use keyphrase instead of verifying device. If it helps, it's definitely the same bug.

**Comment by claell** [comment]
Might be true. However, the behavior is strange. At first, clicking the button to retrieve the keys from another device did nothing. Later, on develop.element.io, it works (but sometimes does not decrypt all messages in a chat). Possibly I am also experiencing more than one bug, which then makes it harder to determine which one it is.

**Comment by mark-todd** [comment]
The above comment is slightly unrelated, but nonetheless here are the docs:
https://element.io/enterprise/end-to-end-encryption

**Comment by richvdh** [comment]
this seems to have gone stale. closing in favour of https://github.com/vector-im/element-meta/issues/245.
