### ISSUE TITLE
Multi-Bridged Rooms possible? (group chats with users on different networks)

### ISSUE THREAD

**Issue by ArneNostitz** [vector-im/element-web#20439]
Hi and sorry if this is answered somewhere else - I couldn't find it ... 

Since the whatsapp privacy talk last year lots of my friends changed to different networks. sadly its really all over the place. now i was wondering if its possible to create a room and connect people on different networks. say, one on signal and the other one on telegram together into one room. so that it creates a virtual group on those networks ... 
 When i think about it - it makes no sense ... because the other user needs to be somehow created on that network ... maybe it could be created as a "quote" ... 
what do you think - is that an option, that is already possible? or something to think about? thanks in advance and happy new years

**Comment by aaronraimist** [comment]
Yes you can bridge a room to multiple networks. The folks in `#bridging:matrix.org` or in the room for the specific bridge you want to use can help you with this.
