### ISSUE TITLE
Ship maximised widgets and remove feature flag

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#20432]
Maximised widgets has now been reviewed by Design and Product, and has been approved for release.

We should remove the feature flag so it's available for everyone:

- [x] Remove the [setting](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/settings/Settings.ts)
- [x] Remove all `getValue` lines that test for the feature
- [x] Remove the feature from the [labs documentation](https://github.com/vector-im/element-web/blob/develop/docs/labs.md)
- [x] #20485

**Comment by kittykat** [comment]
I've added a fourth point about housekeeping in the repo :+1:

**Comment by toger5** [comment]
> Update issue automation to not add Z-Labs to A-Widgets and remove Z-Labs from any outstanding issues at the point of release
I hope I got this right: https://github.com/vector-im/element-web/pull/20483

**Comment by jryans** [comment]
All done! 🥳
