### ISSUE TITLE
ignore users from settings

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20444]
#### What would you like to do?
1. go to settings -> privacy -> ignored users
2. enter mxid (with suggestions by recently seen when typing)
3. user is ignored

#### Why would you like to do it?
`/ignore mxid` is hard to use: https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$RaOo4oQQBkIluBoSiGbdXOam-5CjOfLRlBwtT4ehAFs?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by aaronraimist** [comment]
One way to fix this would be to bring `feature_mjolnir`/MSC2313 out of labs since it already has this feature.

<img width="893" src="https://user-images.githubusercontent.com/5855073/148673167-a9a2e1e7-7238-42e8-b438-58ee5f8ebb3f.png">

**Comment by gsouquet** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/11373
