### ISSUE TITLE
Flatpak not starting after login

### ISSUE THREAD

**Issue by PhieF** [vector-im/element-web#20448]
### Steps to reproduce

1. Install Element Desktop flatpak from flathub
3. Login to your matrix account
4. Enable Start automatically after login
5. Restart computer and login

#### What did you expect?

I expect Element desktop to be started, minimized in my system tray

#### What happened instead?

Element isn't started

### Operating system

Ubuntu 21.10

### Application version

1.9.8

### How did you install the app?

from flathub https://flathub.org/apps/details/im.riot.Riot

### Will you send logs?

No

**Comment by aaronraimist** [comment]
That appears to be a known issue with the Flatpak package https://github.com/flathub/im.riot.Riot/issues/231#issuecomment-962591981 and Electron https://github.com/electron/electron/issues/32388

**Comment by SimonBrandner** [comment]
I think we can close this then
