### ISSUE TITLE
Updating to latest nightly disconnected me

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20451]
### Steps to reproduce

1. Update to the latest nightly

#### What did you expect?

For the app to restart as usual

#### What happened instead?

App restarts and a pink "Unable to connect to homerserver" appears for 5 seconds
I get redirected to the login screen

### Operating system

macOS

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Interesting, console would have likely been helpful here, the app should only be wiping the slate clean if the server or user ask it to

**Comment by novocaine** [comment]
Marking this as s-major as getting logged out once, whilst inconvenient, I don't think causes data loss / prevents work

**Comment by aaronraimist** [comment]
It can cause data loss if key backup is not enabled

**Comment by gsouquet** [comment]
Closing as I can't reproduce nor was I able to capture log at the time. 
Will re-open if I see this issue again
