### ISSUE TITLE
HTML export broken

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#20453]
### Steps to reproduce

- Try to export chat history to HTML

### Outcome

![chat export issue](https://user-images.githubusercontent.com/57274151/148747201-bf631800-e3f8-46b7-a489-e474236d7dbd.png)

Export fails to finish 

Regression maybe caused by https://github.com/matrix-org/matrix-react-sdk/pull/7415/commits/44e607de4a6354822605856bf12c1b7a68a66fed?

### URL for webapp

https://riot.im/app

### Application version

Element version: 1.9.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
What browser is this happening in?

The issue template is there for a reason

**Comment by c-cal** [comment]
Tested with FF 95.0.1 & Chromium 97 (ubuntu)

it doesn't seem to be related to the browser

with chromium:

![image](https://user-images.githubusercontent.com/57274151/148751642-530cdfa3-fcf2-4a10-9062-a29cd6be3b99.png)
