### ISSUE TITLE
expose m.reaction power level to room PL settings by default

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20450]
#### What would you like to do?
manage my announcement room to only allow mods to post messages but anyone to send reactions, like Element Web Announcements and Synapse Announcements.

to do that, I need to set message PL > default, reaction PL <= default and redaction PL <= default

#### How would you like to achieve it?

add m.reaction to room settings -> permissions

### Have you considered any alternatives?

it might be useful to have some presets like "announcement room, users can only react" which sets message = mod, reaction = redact = default

### Additional context

#15446 is closely related

**Comment by saibotk** [comment]
While #7492 added a settings switch, this still leads to weird UX, where Users can send reactions but are not allowed to remove them.

**Comment by HarHarLinks** [comment]
You are correct, #7492 misses the fact that `m.room.redaction` must be exposed alongside it (so you can redact your own messages, which can only be reactions since that's the only you're allowed to send).
@t3chguy please re-open.

I have split off my other suggestion of even more proper UX to #20492 to be addressed independently.
