### ISSUE TITLE
Missing message in 1-1 room, but room has unread notification number

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#20456]
### Steps to reproduce

1. I'm in a 1-1 room bridged from Telegram where the last event in the room is an `m.sticker` sent from the other user.
2. Clicking on the room, scrolling around etc. does not mark the room as read. There's still a (1) notification on the room.
3. Enabling showing hidden events in timeline does not reveal any more events, or help mark the room as read.

### Outcome

![image](https://user-images.githubusercontent.com/1342360/148756645-a8b83a99-0f5d-4ff0-9e73-92b969de5d45.png)

#### What did you expect?

The room to no longer have an unread notification after I had read the latest messages in it.

#### What happened instead?

There's still a (1) on the room in the room list.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022010901, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Can't repro, does clearing cache help?

**Comment by anoadragon453** [comment]
Unfortunately, the user sent another message while I was clearing the cache :(

**Comment by anoadragon453** [comment]
@SimonBrandner see the latest edit on my comment.

**Comment by SimonBrandner** [comment]
Hmm, interesting, so there was a message but it didn't appear, is possible this is a Synapse bug? :thinking:

**Comment by SimonBrandner** [comment]
/me is a little confused, did you see a message preview for the invisible message in the room-list or did you just see the notification badge (possibly, the notif count from sync could have been correct but the event itself was missing)?

**Comment by anoadragon453** [comment]
Just the notification badge. I believe the original message preview was just referring to the `m.sticker` event. If you look at the two screenshots, the message preview is different.

> possibly, the notif count from sync could have been correct but the event itself was missing

That's plausible, and would indeed point to a Synapse bug. Not sure if we're able to figure that out from the client logs though...

**Comment by anoadragon453** [comment]
Closing this as I don't think it's actionable at this point. I'll return with a new issue and homeserver logs if it happens again.
