### ISSUE TITLE
Support Mumble-URL

### ISSUE THREAD

**Issue by natrius** [vector-im/element-web#20468]
https://wiki.mumble.info/wiki/Mumble_URL

The whole scheme is 

`mumble://[username[:password]@]<address>[:port]/[channelpath]?version=<serverversion>[&title=<servername>][&url=<serverurl>]`

and it would be nice if it would be recognized in Element itself.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/15018
