### ISSUE TITLE
PR board automation doesn't action review request from team

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20469]
### Steps to reproduce

1. Assign PR to the design team

### Outcome

This is an example where the the assignment to the team didn't trigger the PR being added to the board: https://github.com/vector-im/element-web/runs/4661109128?check_suite_focus=true

This is an example where the assignment to a team *member* did trigger the PR to be added: https://github.com/vector-im/element-web/runs/4661103876?check_suite_focus=true

**Comment by andybalaam** [comment]
Potential f*x is #20474

**Comment by andybalaam** [comment]
Another try: #20477

**Comment by andybalaam** [comment]
... and ... #20480

**Comment by andybalaam** [comment]
Fixed by #20480
