### ISSUE TITLE
Threads: Analytics

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20486]
This issue tracks the work needed on web to ensure analytics events are available to measure the success of Threads. 

The primary issue is here: https://github.com/vector-im/element-meta/issues/59

The primary issue has all information and decision tracking.

---

MVP:

- [x] [How many users have started a Thread](https://posthog.hss.element.io/dashboard/98)
- [x] [How many users have responded to a Thread](https://posthog.hss.element.io/dashboard/98)
- [x] [How often has the Threads panel been opened and where was it opened from?](https://posthog.hss.element.io/dashboard/98) (Top right icon, Thread view > back)
- [x] [How often has the Thread view been opened and where was it opened from?](https://posthog.hss.element.io/dashboard/98) (Threads panel > select, Thread summary from timeline)
- [x] [How often is the Filter used in the Thread panel](https://posthog.hss.element.io/dashboard/98)

**Comment by t3chguy** [comment]
> Thread Panel's view could be either the Thread list, or the Thread timeline.

Alright, the terms are poorly defined, in the code `ThreadPanel` is the list of threads, `ThreadView` is a single thread. In Metrics `Thread Panel` refers to both.

**Comment by daniellekirkwood** [comment]
Got it. Happy to change up the request... 

How about:
- See how many users are viewing the `ThreadPanel` and the access point that got them there: Icon top right, Thread summary> Back
- See how many users are viewing the `ThreadView` and the access point that got them there: Icon top right > Select, Thread Summary

**Comment by daniellekirkwood** [comment]
Yes, good catch
