### ISSUE TITLE
whole timeline appears in threads panel as if every message was a thread root

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20494]
### Steps to reproduce

not sure, I started a thread (as seen in picture), then clicked "back" to get to threads overview panel. it was gray for some seconds (loading?) then see below.

#### What did you expect?
only threads

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/148995512-bb6bf9e7-0140-41be-89eb-9a67113a092c.png)

### Operating system

arch

### Application version

Element Nightly version: 2022011101 Olm version: 3.2.8

### How did you install the app?

aur/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed on develop with compatible homeservers.
