### ISSUE TITLE
Codeblocks inaccurately representing line numbers

### ISSUE THREAD

**Issue by TheEvilSkeleton** [vector-im/element-web#20498]
### Steps to reproduce

Whenever I post a codeblock, lines get wrapped and line numbers are inaccurately represented

1. Open a room
2. Type \`\`\`PASTE LONG SINGLE LINE CODE / TERMINAL OUTPUT HERE\`\`\`
3. Send the message

#### What did you expect?
1. I expect codeblocks to _not_ be wrapped.
1. I expect the codeblock to say exactly the line number, as shown here:
![image](https://user-images.githubusercontent.com/50847364/148999534-a9a6ab0b-d8cd-4d6a-af1c-5ae21f97fb6e.png)
Here's a bigger preview:
![image](https://user-images.githubusercontent.com/50847364/148999656-323a6303-604e-44fa-8498-7ead0503d6ff.png)

*Screenshot taken with Element on my __**1440p**__ monitor*

#### What happened instead?
It creates a newline (and wraps code) and says that they're two lines instead of one:
![image](https://user-images.githubusercontent.com/50847364/148999369-32334974-66a2-4119-9704-3260c3856b6d.png)

Here's a bigger preview:
![image](https://user-images.githubusercontent.com/50847364/148999429-cbf06280-4371-4393-9286-d71af46d5f8f.png)

*Screenshot taken with Element on my **1080p** monitor*

If possible, can we please bring back unwrapped codeblocks? It's so much harder to read now while they're wrapped.

### Operating system

Fedora Silverblue 35

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

Flathub https://flathub.org/apps/details/im.riot.Riot

### Homeserver

fedora.im

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed already on develop
