### ISSUE TITLE
simple widget embedding a website does not update linked resources (e.g. css)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20496]
### Steps to reproduce

1. add widget of my site
2. update its css
3. widget refreshes html but not css

#### What did you expect?
refresh css too

#### Suggestions
add a button to refresh the widget and clear its cache

### Operating system

arch

### Application version

Element Nightly version: 2022011101 Olm version: 3.2.8

### How did you install the app?

aur/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by t3chguy** [comment]
I don't believe a webapp can control the cache invalidation of an iframe. We could cachebust the outermost page but if your cache controls headers on the css are set such that it is cached aggressively that would do nothing.

**Comment by gsouquet** [comment]
Definitely agree with what was said above.
I believe there's no way to control what gets cached on invalidated. This is the browser's job.

However your HTML document can include some directives to hint browsers at how they should cache the subresources.

Will close this issue, but feel free to comment if you feel like there are things Element could do to improve the current situation
