### ISSUE TITLE
Downgrade an admin

### ISSUE THREAD

**Issue by samelamin** [vector-im/element-web#20495]
#### What would you like to do?
Admins cannot be downgraded from the UI
#### Why would you like to do it?
To better manage rooms
#### How would you like to achieve it?
Using the UI, the same way I upgraded a moderator to Admin

### Additional context

I am trying to fix the bridge between our element room and telegram and mistakenly set the bots to Admin

I cant change their permissions back to moderator

![image](https://user-images.githubusercontent.com/4311963/148997087-31245f01-5007-4dda-9b07-32a2fb47a175.png)

**Comment by t3chguy** [comment]
Matrix does not allow you to control users with the same power level as you, so you would need to be >Admin to do this.

**Comment by samelamin** [comment]
> Matrix does not allow you to control users with the same power level as you, so you would need to be >Admin to do this. When you set a user to admin you are warned about this.
> 
> ![image](https://user-images.githubusercontent.com/2403652/148997735-c3b11b50-e12a-401a-a7b1-8f8aa9fb39d1.png)

Sorry for my mistake, I was most likely warned and missed it

I did create the group though, doesn't that mean I _should_ have higher permissions than Admin. Or is Admin the highest?

**Comment by t3chguy** [comment]
Depends on your server, most set the creator to just Admin.

**Comment by samelamin** [comment]
I see. So there's nothing I can do but delete the room and start over?

**Comment by t3chguy** [comment]
Or have those bots drop their own power level

**Comment by samelamin** [comment]
Ok thanks for your help mate! 

This is sheer idiocy from me! 🤦‍♂️
