### ISSUE TITLE
Info button in the top-right can get de-synced

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#20509]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/149154041-1e6f9077-c641-4628-b817-8171c832b9e2.png)

Note that the info button is highlighted, but the right sidebar is not visible.

This is reproducible by:

1. Closing the right sidebar in a room.
2. Navigating to another room.
3. Opening the right sidebar if it isn't already.
3. Returning to the previous room.
4. Notice that the info icon remains highlighted, even though the right sidebar is not currently shown.

#### What did you expect?

The status of the highlight to be consistent with whether the sidebar is shown.

#### What happened instead?

Chaos! As shown by the screenshot above.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022011101, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Will you send logs?

No

**Comment by anoadragon453** [comment]
It actually looks like it's not *always* reproducible with the above step, and that it can affect other top-right buttons as well:

![image](https://user-images.githubusercontent.com/1342360/149158203-d0c8e429-9466-4c2c-9463-09786eadc63c.png)

**Comment by toger5** [comment]
I tried with multiple rooms and panels but I cannot reproduce the issue.
But I have ran into this during development. I cannot recall what exactly was done when. Can you try with your account on develop.element.io?

**Comment by toger5** [comment]
This got fixed recently by @jryans (THANKS ! )
https://github.com/matrix-org/matrix-react-sdk/pull/7506
