### ISSUE TITLE
Message bubbles timeline looks oddly narrow on a 1920px display

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20504]
### Steps to reproduce

1. Switch from Modern layout to Message Bubbles in the settings

#### What did you expect?
![Screenshot from 2022-01-12 10-47-05](https://user-images.githubusercontent.com/51663/149126164-a77640a8-cf2c-4686-b011-672650224eaf.png)

#### What happened instead?
![Screenshot from 2022-01-12 10-44-41](https://user-images.githubusercontent.com/51663/149126053-5f942c1f-361c-452f-8eee-5d1786f9348a.png)

### Operating system

Arch Linux

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: ef9335697e05-react-b8355883313e-js-6fc586598a98 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an intentional centering with max-width of 1200px to make bubbles saner on wide screens, see https://github.com/vector-im/element-web/issues/18072

**Comment by G2G2G2G** [comment]
Please add a toggle checkbox to enable/disable these margins

**Comment by daniellekirkwood** [comment]
Thanks for the feedback on this - for our initial launch we're choosing to stick with what we have. Once this feature is out of labs and used by more folks we'll revisit this decision. 

In the meantime, I'll close this issue. Thank you!
