### ISSUE TITLE
If you c+p a 3PID invite URL into an existing vector window's URL bar, nothing happens

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2050]
Presumably the URL parsing stuff ignores it

**Comment by ara4n** [comment]
The story here was:
 * Click on 3PID link in Outlook
 * Vector opens in IE. Everything breaks.
 * Copy-paste URL from IE to Chrome.  No invite shown.
 * Copy-paste 3PID url from Outlook to Chrome.  Nothing happens.
 * Close chrome tab, paste 3PID url into new empty tab.  Everything works.

Ugh.

**Comment by MidhunSureshR** [comment]
I'm closing this issue since it's really old and I'm not sure if it's even reproducible now. Please feel free to re-open with up to date information :+1:
