### ISSUE TITLE
[Spaces] Add Mark as read to spaces context menu in the spaces panel

### ISSUE THREAD

**Issue by licentiapoetica** [vector-im/element-web#20502]
#### What would you like to do?
Marking all channels with unread messages as read via shortcut so I don't have to click manually on all of them

#### Why would you like to do it?
Lazy

#### How would you like to achieve it?
by gods grace

### Have you considered any alternatives?

Clicking every room by hand

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/8541
