### ISSUE TITLE
Room was added to space instead of inviting the user to the room

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20516]
### Steps to reproduce

happened to me once like this:
1. Created a private space - choose just for me.
2. invite people to this space
3. one person invited landed in the list of rooms as well as in the list of people in the space

#### What did you expect?
They should only be in the list of people in the space
#### What happened instead?
one of the people was also added as a DM roo.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

element.chagai.website

### Application version

Element Chagai version: v1.9.5 Olm version: 3.2.3

### Homeserver

Https://mx.chagai.website

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Spaces list your existing DMs with members of that space in the room list, is this what is confusing you? Screenshots may help explain your predicament.

**Comment by chagai95** [comment]
Sorry I forgot the screenshot, but yes that would explain it, Thanks!

![image](https://user-images.githubusercontent.com/31655082/149192253-313dc7e5-f201-4ebe-9fb1-7b9b4b5bc083.png)
