### ISSUE TITLE
FLAC file extension renamed to .mp3 when uploaded using Element

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#20520]
### Steps to reproduce

1. Upload particular FLAC files using Element (only happens with certain ones)
2. Attempt to play file in Element once uploaded and review file extension

(I can provide one of the FLAC files in question if needed. Wasn't sure if I could post it publicly here since it's copyrighted music)

![image](https://user-images.githubusercontent.com/41203525/149209492-b653b038-ed7a-4bae-8230-6f18aed4a9bf.png)

![image](https://user-images.githubusercontent.com/41203525/149209587-1eb5b933-087d-4237-ac2d-5a19e1cfbf74.png)

![image](https://user-images.githubusercontent.com/41203525/149209660-579f18f3-2150-4da4-b311-a2c7b9e5fcfa.png)

![image](https://user-images.githubusercontent.com/41203525/149210891-1baaa6e5-ca6b-4112-ac7c-bdc4ab904037.png)

#### What did you expect?
The file should retain its .flac file extension and play in Element

#### What happened instead?
File extension is changed to .mp3 and is unable to play in Element (probably because the browser is attempting to process it as an mp3 and failing). If I press Download and play in mpv, I can play it and see that the file extension is now .mp3 but the data is FLAC.

### Operating system

Arch Linux

### Browser information

Firefox 93.0

### URL for webapp

self-hosted initially, but was able to reproduce on develop.element.io

### Application version

Mine: Element version: 1.9.0-8-gcf5cbb1f-dirty Olm version: 3.2.3
develop.element.io at the time of testing this: Element version: ef9335697e05-react-3a18fd8f716b-js-4acb98c4963d Olm version: 3.2.8

### Homeserver

private instance initially, but was able to reproduce on other homeservers including matrix.org

### Will you send logs?

No. Tested with multiple instances including public ones and was able to reproduce.

**Comment by HarHarLinks** [comment]
related https://github.com/matrix-org/matrix-doc/issues/1938

**Comment by gsouquet** [comment]
Can not reproduce that in macOs Electron or Firefox.

**Comment by kittykat** [comment]
@BurnyBoi could you please reach out to me and share the file? You can reach me at @kittykat:matrix.org

**Comment by G2G2G2G** [comment]
Does it do that with a flac that has no mjpeg embedded? (Reason I ask is mjpeg doesn't seem to be supported by anything for the metadata there)

**Comment by gsouquet** [comment]
> that's when I noticed I think it's actually the BROWSER that is doing it somehow:

Could you reproduce the error locally and send a rageshake, I'd be interested to see what's the actual error is.
Looking at the code, it appears that the displayed error message is somehow misleading, this issue can happen in the media processing failed which is likely what's going on here.

I don't know what the support for media is on Qutebrowser

**Comment by BurnyBoi** [comment]
> Does it do that with a flac that has no mjpeg embedded? (Reason I ask is mjpeg doesn't seem to be supported by anything for the metadata there)

I used a tag editor to remove the embedded image on the same file and uploaded again, and I am seeing it embeds and plays in Firefox after doing that. It seems having the image embedded in the FLAC is part of the cause then?


> Could you reproduce the error locally and send a rageshake, 

I believe that should be submitted now, but I see no indication here so idk if that's something that is checked behind the scenes. I went to the test room, waited for the file to show "Error Downloading Audio", then did Submit Debug Logs.

**Comment by G2G2G2G** [comment]
Now add in a .png thumbnail instead of that mjpeg and see if it does it with a .png (which is actually the supported thumbnail embedded image)... if it does do it then it's a problem, if not.. I'd say not a problem since mjpeg isn't technically supposed to be embedded in metadata as far as I read.

**Comment by BurnyBoi** [comment]
> Now add in a .png thumbnail instead of that mjpeg and see if it does it with a .png (which is actually the supported thumbnail embedded image)... if it does do it then it's a problem, if not.. I'd say not a problem since mjpeg isn't technically supposed to be embedded in metadata as far as I read.

Just tested this, and you're right. A FLAC with an embedded png instead also plays fine in Element Web on Firefox.

**Comment by G2G2G2G** [comment]
Yea so whoever made the file didn't respect the "specification" and just embedded whatever they wanted.. ffmpeg etc let you do this, (like 10bit H.264, 4k H.264?, etc which is extremely popular yet not part of spec)
I assume browsers are just ignoring it but firefox is trying to do something with it and instead fails (rather than just ignoring it), firefox generally follows spec much closer than chromium does.. for better or for worse.

This is a browser (bug? / feature?) not to do with element-web though
