### ISSUE TITLE
Romanian phone numbers not supported

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-web#20524]
### Steps to reproduce

1. Go to your account (matrix.org/vector.im) settings / general / phone numbers 
2. Select Romania from the list
3. Insert a valid number e.g. `741 000 000`
4. Receive `country not supported error`

#### What did you expect?
For the phone number to be added and to receive a confirmation SMS as per https://www.openmarket.com/docs/Content/globalcoverage/country/romania.htm

I also tried this with my own personal phone number (which can receive SMSs without problems) with the same results.

#### What happened instead?
`Errror` - `Phone numbers in this country are not currently supported (Status 400)`

![Screenshot 2022-01-13 at 11 06 47](https://user-images.githubusercontent.com/637564/149300171-40f97ebd-8c99-4ee8-82a9-70a128f1dbe3.png)

### Operating system

macOS

### Browser information

Chrome Version 97.0.4692.71

### URL for webapp

app.element.io

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an error from your homeserver rather than Element Web

**Comment by kittykat** [comment]
babolivier had a quick look at this issue. It looks like [this list](https://github.com/matrix-org/matrix-ansible-private/blob/main/roles/sydent/templates/sydent.conf.j2#L95-L96) needs to be compared to [the countries covered by the provider](https://www.openmarket.com/docs/Content/globalmaps.htm) and updated

**Comment by stefanceriu** [comment]
Oh nice, thank you for that! I guess I'll raise a PR and see what happens 👍

**Comment by t3chguy** [comment]
Cannot reproduce this anymore

> A text message has been sent to +40749XXXXXX. Please enter the verification code it contains.

**Comment by stefanceriu** [comment]
Oh, completely forgot to comment on this. Yes, the validation now works and I was able to setup my Romanian phone number. Thank you everybody 👍
