### ISSUE TITLE
MsgBubbles: Stickers

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20523]
### Your use case

As part of the Message Bubbles project, Stickers should **not** into Bubbles.

**Comment by t3chguy** [comment]
One thing to consider is stickers are not unlike images with a transparent border (and a tooltip) so putting them in a bubble that may be inconsistent with sticker-like images which are sent as an m.image instead of m.sticker.
Related https://github.com/vector-im/element-web/issues/20535

**Comment by amshakal** [comment]
Hi, okay based on the issue above and to remove complications. Let's move stickers outside the bubble. On doing some research on other platforms I see floating timestamp for stickers is quite common and perhaps a better tradeoff than having a gradient. The only place where it might not look good is if stick is the first message sent by a user. I am attaching below designs for the those scenarios. Aplogies for going back and forth on this issue. Thanks!


When sticker is the first message
<img width="730" alt="Screenshot 2022-01-17 at 8 48 27 pm" src="https://user-images.githubusercontent.com/85162587/149796237-b779916d-2ad4-4d74-9caf-1db042b7e59d.png">
<img width="636" alt="Screenshot 2022-01-17 at 8 48 55 pm" src="https://user-images.githubusercontent.com/85162587/149796246-c45cd565-8924-4b9c-b44c-af5764bb0eba.png">

When sticker is a message in between
<img width="736" alt="Screenshot 2022-01-17 at 8 48 23 pm" src="https://user-images.githubusercontent.com/85162587/149796202-454e0ae7-5cc0-423f-9966-de298545c620.png">
<img width="608" alt="Screenshot 2022-01-17 at 8 48 47 pm" src="https://user-images.githubusercontent.com/85162587/149796213-09de3dce-abb2-418e-85fd-83c9d09093e5.png">

When sticker is the last message
<img width="651" alt="Screenshot 2022-01-17 at 8 43 29 pm" src="https://user-images.githubusercontent.com/85162587/149796107-43f834c4-0d32-49dd-b45c-46a5623dc48b.png">
<img width="633" alt="Screenshot 2022-01-17 at 8 49 02 pm" src="https://user-images.githubusercontent.com/85162587/149796142-704ce3db-20be-4359-b0f2-079cc377bf12.png">

Link to figma: https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=2099%3A44213

**Comment by daniellekirkwood** [comment]
Updated content of issue based on above
