### ISSUE TITLE
Incorrect messages order with bubbles

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#20536]
### Steps to reproduce

1. Enable bubbles
2. Talk to someone and send a message after theirs
3. They edit their message
4. Their original message is now displayed below yours

#### What did you expect?

I expected the timeline order to stay the same as before edits

#### What happened instead?

The timeline took the edit time into account to display the message

### Operating system

macOS

### Application version

Element Nightly version: 2022011301
Olm version: 3.2.8

### How did you install the app?

https://element.io

### Homeserver

ergaster.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
https://user-images.githubusercontent.com/2403652/149369158-53a40544-dc34-495f-8821-16a75b0d6edc.mov

Cannot reproduce this

**Comment by t3chguy** [comment]
This turned out to be a pending message glued to the bottom until the server confirmed the order of events via /sync causing some confusion to a user watching slightly too closely
