### ISSUE TITLE
Threads panel shows messages from two rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20530]
### Steps to reproduce

1. Read a thread in one room
2. Switch rooms to another room with threads
3. See a mix of threads from both rooms

#### What did you expect?
Either threads for one room being persistent in the right panel or seeing only threads from the rooms I'm currently viewing rather than a mix of both.

#### What happened instead?
In my example, the latest thread is the one from the wrong room and the other ones are from this room:
![Screenshot from 2022-01-13 13-37-47](https://user-images.githubusercontent.com/51663/149342173-181eeafd-8854-4d2f-b760-b7e06a18a04a.png)

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 315f95e3909b-react-25cd1a8a43d0-js-4acb98c4963d Olm version: 3.2.8

**Comment by gsouquet** [comment]
Have not been able to reproduce that one so far.
Tested on homeservers with and without thread capabilities. 

Are you still able to reproduce? It appears that yesterday's Nightly build had a few odditties attached to it
