### ISSUE TITLE
Linear gradient on images with transparencies in message bubble layout looks bad

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#20535]
![image](https://user-images.githubusercontent.com/2403652/149366689-e2960561-8d72-42ca-a617-14d33bc78237.png)

Spun out from https://github.com/vector-im/element-web/issues/20403#issuecomment-1012280273

Without the gradient though the timestamp would not be visible whatsoever

![image](https://user-images.githubusercontent.com/2403652/149366796-a8527a08-c10c-4acd-b489-4c7db7f488b7.png)

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/20523

**Comment by t3chguy** [comment]
This no longer applies to stickers but still will apply to images with transparency

**Comment by daniellekirkwood** [comment]
Great issue to raise. Let's live with what we have for now and see how it goes. 

I'm marking this issue as a V2 Enhancement so we can revisit in a few weeks

**Comment by robintown** [comment]
The gradient has been removed
