### ISSUE TITLE
doing pw reset with an email added by synapse admin asks you to verify the email but goes through anyway

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20543]
### Steps to reproduce

1. add 3PID email address to an account via synapse-admin, i.e. it is added without confirming it
2. do a pw reset
3. after entering new pw, it asks whether you have verified your email address unnecessarily
4. you can ignore and continue, but it sounds weird

#### What did you expect?
not have that popup

### Operating system

arch

### Browser information

Chrome/96.0.4664.113

### URL for webapp

staging.element.io

### Application version

idk didn't log in and it doesn't say on the login screen

### Homeserver

custom

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
the element issue here is that it seems to receive info from server about verifying the address, which doesn't make sense if you're already resetting.

it seems to me that there also is an issue either with synapse or with synapse-admin that addresses added by admins (i.e. without regular verification flow) are not marked as "verified", and the server tells the client that when resetting. could you open issues with the respective projects or point me to the relevant one?

**Comment by t3chguy** [comment]
The server is free to request anything it wishes via UIA flows so this sounds like a backend issue rather than an Element one. Element can't assume/filter the requested UIA flows based on the exact path the user is taking as the spec allows any UIA flow to be used on any UIA-enabled API.

**Comment by t3chguy** [comment]
If you are still experiencing this bug, please open an issue in https://github.com/matrix-org/synapse/
