### ISSUE TITLE
Thread replies get posted to the main timeline

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20541]
### Steps to reproduce

Post a reply to an existing thread using the thread message composer.

#### What did you expect?

The reply to get added to the thread.

#### What happened instead?

It got posted to the main timeline but it wasn't added to the thread.

### Operating system

macOS 12.1

### Browser information

Chrome 96.0.4664.110

### URL for webapp

develop.element.io

### Application version

Element version: 85f6c3b21f80-react-61a0be7d46c8-js-016e24472a0b Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by toger5** [comment]
This regeshake was also caused by the same error i think:
https://github.com/matrix-org/element-web-rageshakes/issues/8126

**Comment by janogarcia** [comment]
@toger5 Updating to the latest develop seems to fix the described issues. Can you please check on your side?

```
Element version: 85f6c3b21f80-react-47c112b12e5d-js-129fb7f10f12
Olm version: 3.2.8
```

@gsouquet Consider closing this issue. 👍

**Comment by toger5** [comment]
It also works for me. I hope its fine that I closed it.
