### ISSUE TITLE
Starting a thread makes the main timeline go blank

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20554]
### Steps to reproduce

It's happening randomly, so it's hard to reproduce.

Just start a new thread by clicking on the "Reply in thread" action on a message in the main timeline.

#### What did you expect?

Start typing a reply in the thread composer without any side effects to the main timeline.

#### What happened instead?

The main timeline went blank.

I'm attaching a screenshot, but I'm not submitting logs yet, as it's hard to trigger the bug.

![Blank timeline](https://user-images.githubusercontent.com/60790/149515551-a7059d0d-3d52-4fe2-ae70-1672295ae699.png)

### Operating system

macOS 12.1

### Browser information

Chrome 96.0.4664.110

### URL for webapp

develop.element.io

### Application version

Element version: 85f6c3b21f80-react-50de35cd1a88-js-16ca09eed811 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
@janogarcia I have not encountered this issue since you raised it.
Have you stumbled upon it recently?

**Comment by janogarcia** [comment]
@gsouquet I think I haven't after updating to the immediately following develop version.

**Comment by gsouquet** [comment]
Closing this as there has been no spotting of this particular problem in the past handful of days.
We will always be able to reopen it if it happens again
