### ISSUE TITLE
Broken search in encrypted room

### ISSUE THREAD

**Issue by domestomas** [vector-im/element-web#20564]
### Steps to reproduce

In a 1-1 encrypted room, search omits some results. I can not find any pattern in which messages can not be searched. Both users on matrix.org.

### Operating system

Linux Mint

### Application version

 Element 1.9.8 Olm 3.2.8

### How did you install the app?

official repository

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by G2G2G2G** [comment]
https://github.com/vector-im/element-web/issues/19001

**Comment by SimonBrandner** [comment]
@domestomas, could you please check Settings -> Security & Privacy -> Message Search? Are there any errors there?

**Comment by domestomas** [comment]
Hi, there are no errors there.

**Comment by turt2live** [comment]
without an error this sounds effectively like https://github.com/vector-im/element-web/issues/21535 where we are using a different search algorithm and that's causing a tripup for the user.

Closing as a duplicate of https://github.com/vector-im/element-web/issues/21535
