### ISSUE TITLE
Element does not interpret markdown after first encountering a room pill

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20565]
### Steps to reproduce

Trying to send the following message;

![image](https://user-images.githubusercontent.com/22740616/149580409-2229b18a-134b-404b-85ad-5c149e0db561.png)

Results in the following message;

![image](https://user-images.githubusercontent.com/22740616/149580438-36a52e8f-a8ae-4e4a-ad81-044f65576c72.png)

<details>
<summary>Source</summary>

```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "#matrix-spec:matrix.org a *thing*",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/#matrix-spec:matrix.org\">#matrix-spec:matrix.org</a> a _thing_"
  }
}
```

</details>

#### What did you expect?

Markdown to get interpreted correctly

#### What happened instead?

Markdown somehow got interpreted from HTML back to Markdown

### Operating system

PopOS Linux, 21.04

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

No

**Comment by UwUnyaa** [comment]
I just managed to reproduce this with element web (running as element desktop) 1.9.8-1 on Arch.

**Comment by UwUnyaa** [comment]
Looking through code, I found a reference to this issue: https://github.com/vector-im/element-web/issues/16660

**Comment by SimonBrandner** [comment]
I don't think I can repro on develop.element.io

**Comment by ShadowJonathan** [comment]
I can reproduce it still on nightly:

https://user-images.githubusercontent.com/22740616/149622439-fdfef060-f9a4-45ae-9ef7-11b6d431a7f0.mp4

**Comment by UwUnyaa** [comment]
@SimonBrandner the ability to complete rooms in a given room is flaky, so for some reason this cannot be reproduced in every room, and doesn't seem to work at all in DMs.

**Comment by robintown** [comment]
Probably a duplicate of https://github.com/vector-im/element-web/issues/20091, since pills are actually links.

**Comment by ShadowJonathan** [comment]
Indeed

Duplicate of #20091

**Comment by UwUnyaa** [comment]
This would make sense, as mentions of users are considered to be pills, but don't cause the problem. It suggests that the problem is caused by something else entirely.
