### ISSUE TITLE
Call tiles don't have timestamps in the bubble layout

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#20562]

**Comment by amshakal** [comment]
Link to figma: https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=1696%3A39346

While it's not the most elegant solution it is consistent, predictable and what is probably expected in the scenario that the timestamp should be visible at all times for calls.

**Comment by t3chguy** [comment]
They seem to have timestamps now, just in a very wrong place.

![image](https://user-images.githubusercontent.com/2403652/149813830-6b9827a0-1424-4c04-9f8d-4ad2c343b578.png)


@amshakal would be good to keep the timestamp location consistent between these middle-timeline-pill-things, could you show me where the timestamp should be for the verification request pills?

**Comment by amshakal** [comment]
I have created a page with events like these that are in the center on the timeline. Please let me know if you need designs for any other such instance, I'll add it to this specific frame. I have edited the design from the above proposal to align it to the right corner in the center of the box so it can work with other instances as well, such as verification request, with least amount of disruption to what we have currently.

<img width="710" alt="Screenshot 2022-01-17 at 11 35 19 pm" src="https://user-images.githubusercontent.com/85162587/149819240-098949cd-4243-4370-a6c3-16a05f7187ae.png">


Figma link: https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=2115%3A46891

**Comment by SimonBrandner** [comment]
Hmm, the more I think about this, I feel like it would be better to have the timestamp outside of the message on the left, similarly to leave/joins... This is both from the technical and design perspective as it feels a little weird to have two things that show time (call time + timestamp) in the bubble

**Comment by t3chguy** [comment]
@amshakal thoughts on the above?

**Comment by daniellekirkwood** [comment]
It's great feedback but leaving the timestamp on the left feels disjointed. Let's go with the design as is and re-evaluate this decision after our first launch of bubbles. 

Thanks!
