### ISSUE TITLE
Widgets should span across the whole room width when using bubble layout

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#20560]
The bubble layout makes the timeline more narrow but also by accident makes the call view more narrow which looks very odd and wrong

![2022-01-14_18-05](https://user-images.githubusercontent.com/25768714/149555706-b56f4d59-2a62-475c-b5f8-19401248d181.png)

**Comment by gsouquet** [comment]
Could you attach a screenshot of the issue as well please?

**Comment by SimonBrandner** [comment]
> Could you attach a screenshot of the issue as well please?

Done
