### ISSUE TITLE
When dowloading a steam game, video quality gets terrible and latency is insane (doesn't happen on other calling apps)

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20569]
### Steps to reproduce

1. Start a video call
2. Start a game download on steam
3. Observe video quality going very low, along with latency being extremely high, even for audio. Turning off the video does not fix this latency.

#### What did you expect?
Almost nothing to happen, perhapse a slight degradation in video quality (I have good internet)
#### What happened instead?
The video got very blurry and there was extreme latency

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Does this happen in the browser, I am a little worried we can't do much here

**Comment by AverytheFurry** [comment]
> Does this happen in the browser, I am a little worried we can't do much here

Unsure, I can try reproducing it sometime when I have free time and another person to waste (and if I remember) lol
I almost never use the web app

**Comment by turt2live** [comment]
There's nothing we can do about bandwidth constraints here. Video going blurring when contested is a feature rather than a bug by conference call apps.
