### ISSUE TITLE
Unable to screenshare to mobile device

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20573]
### Steps to reproduce

1. Call someone who is using a mobile device.
2. The screen share button does not exist, like it does when calling someone on a desktop device.

#### What did you expect?
I expected the ability to share my screen to be present.
#### What happened instead?
The ability to share my screen was not present.

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by robintown** [comment]
Specifically which client is the mobile user using?

**Comment by SimonBrandner** [comment]
I am assuming you're making a voice call, if that is the case, this is a duplicate of https://github.com/vector-im/element-android/issues/3734. Element Android doesn't support receiving nor sending multiple streams, so this isn't possible.

Duplicate of https://github.com/vector-im/element-android/issues/3734

**Comment by AverytheFurry** [comment]
> I am assuming you're making a voice call, if that is the case, this is a duplicate of [vector-im/element-android#3734](https://github.com/vector-im/element-android/issues/3734). Element Android doesn't support receiving nor sending multiple streams, so this isn't possible.
> 
> Duplicate of [vector-im/element-android#3734](https://github.com/vector-im/element-android/issues/3734)

Apps like discord and telegram do support this, to my knowledge

**Comment by SimonBrandner** [comment]
Yes, I am aware, I am by no means saying this is technically impossible. But for Android to be able to do this they need to support https://github.com/matrix-org/matrix-doc/pull/3077 which they don't yet and therefore [the linked issue](https://github.com/vector-im/element-android/issues/3734) exists

**Comment by ratnik2** [comment]
Could this issue be re-opened since MSC3077 has been merged? I'm assuming nothing is stopping Element X iOS/Android from screen sharing.

Telegram & Discord have this feature and if implemented on Element, I could finally convince my friends to switch to Element X.

**Comment by t3chguy** [comment]
@ratnik2 this is the element-web repo, it has nothing to do with Element X iOS/Android, so re-opening this wouldn't help anything.

**Comment by ratnik2** [comment]
@t3chguy Should I write this feature request in element-call or another repo? I couldn't find this issue on any other repo presently.
