### ISSUE TITLE
Whenever someone else hangs up in a voice call, my client usually does not register the call as completed.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20571]
### Steps to reproduce

1. Call someone/have someone call you
2. Have them hang up
3. The call does not end, however they have left the call and are not transmitting audio/video

#### What did you expect?
I expected the call to end, instead of being in a call with myself
#### What happened instead?
The call did not end

This happens about 50% of the time when I'm not the one who ends the call.

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
What device is the other person using? Could you please send logs? Is there any more info you can provide? 

This doesn't not happen for me

**Comment by turt2live** [comment]
Closing due to lack of information. If this is still happening for you, please open a new issue with the information requested.
