### ISSUE TITLE
"remove from room" and "ban" are inconsistently phrased

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20578]
### Your use case

![image](https://user-images.githubusercontent.com/2803622/149632519-40c216a5-6173-455d-bdc1-0e5d97a9c80f.png)

both should say "from room", in fact all of these should clarify whether they apply to the scope of the room or globally, and only yourself or everyone for things like mute. E.g. globally muting a user for everyone else, otherwise known as a shadowban.

It may also make sense to split this list up between room admin settings and server admin.

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by ankur12-1610** [comment]
I'm finding a difficulty in reproducing this issue, kindly help:sweat_smile:

**Comment by HarHarLinks** [comment]
Element Nightly version: 2022011801
Olm version: 3.2.8

**Comment by EECvision** [comment]
Hi,  I am an outreachy applicant. I noticed that this issue was worked on but unable to be merged. Can I still improve it?

**Comment by ttheshreeyasingh** [comment]
@ankur12-1610 Hi, are you still working on this issue? If not, can I please be assigned the issue?

**Comment by EECvision** [comment]
> @ankur12-1610 Hi, are you still working on this issue? If not, can I please be assigned the issue?

yes, I am still working on it.

**Comment by HarHarLinks** [comment]
I think this PR has landed in Element Nightly version: 2022041501, as the "Admin tools" in rooms reflect this change.

However in spaces this happens:
![image](https://user-images.githubusercontent.com/2803622/163559946-f3e94cb0-ac4b-4a03-84c7-0523fe3473c7.png)

Thus @turt2live please re-open.

**Comment by EECvision** [comment]
> I think this PR has landed in Element Nightly version: 2022041501, as the "Admin tools" in rooms reflect this change.
> 
> However in spaces this happens: ![image](https://user-images.githubusercontent.com/2803622/163559946-f3e94cb0-ac4b-4a03-84c7-0523fe3473c7.png)
> 
> Thus @turt2live please re-open and @EECvision you might want to address this.

Okay, I will.
