### ISSUE TITLE
When calling, dragging the video call element down (to enlarge it) causes it to push horizontally under the room/user info element.

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20570]
### Steps to reproduce

1. Start a video call
2. Drag down on the video element
3. Observe

#### What did you expect?
I expected the video call panel to not get shoved behind the room/user info panel
#### What happened instead?
it got shoved behind the room/user info panel
![Capture](https://user-images.githubusercontent.com/47131867/149616635-8a90f6a2-d8a2-4e63-b43e-01fa63aff405.PNG)

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
How big is your screen? Does this happen always? Could you perhaps record a video?

I cannot reproduce

**Comment by AverytheFurry** [comment]
> How big is your screen? Does this happen always? Could you perhaps record a video?
> 
> I cannot reproduce

I was going to record a video, but didn't want to expose the pfp of the person I was calling. I didn't end up taking a video and it's the next day now :p - this does not happen all the time, so I believe there could be something situational at play.

**Comment by SimonBrandner** [comment]
I've been messing around with this for a few minutes now and still can't repro :/

**Comment by AverytheFurry** [comment]
> I've been messing around with this for a few minutes now and still can't repro :/

gotcha, sorry for all the issue spam, just lliterally had all these things happen to me in the same day and I was like "better to just report ig"

**Comment by AverytheFurry** [comment]
> I've been messing around with this for a few minutes now and still can't repro :/

actually, it could have something to do with my resolution changing from 1920x1080 to 1280x720 sometimes (when I play games I change my resolution)

**Comment by SimonBrandner** [comment]
> > I've been messing around with this for a few minutes now and still can't repro :/
> 
> actually, it could have something to do with my resolution changing from 1920x1080 to 1280x720 sometimes (when I play games I change my resolution)

That sounds plausible, I've seen something like this happen a few times when showing developer tools. Quite possibly this is a browser/Electron issue rather than an Element one. 

Could you please check this is the case?

**Comment by turt2live** [comment]
Closing as a presumed environmental issue. If this is still happening for you, please open a new issue with new information.
