### ISSUE TITLE
Wrong membership state showing in client

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20575]
### Steps to reproduce

Not sure if this always happens
1. I invited another account I have
2. I joined with that account (auto-accept-module)
3. The people section still shows invited.

https://user-images.githubusercontent.com/31655082/149625958-a50cd3ec-3408-4c38-b6db-638c4eb4dbf1.mp4

4. After reacting to a message the GUI updated.

#### What did you expect?
the membership state to be correct.
#### What happened instead?
It was not.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The timeline of the client on the left isn't showing the `X joined` event either, so this looks like it never came down /sync and I'm led to believe its a Synapse /sync bug

**Comment by t3chguy** [comment]
Closing as a server issue
