### ISSUE TITLE
Add keyboard shortcuts for previous and next in image lightbox view

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20587]
#### What would you like to do?
Navigate between files in a room using right and left keyboard buttons so I don't need to close and open the lightbox view

#### Why would you like to do it?
To navigate faster between images and navigate using the keyboard

#### How would you like to achieve it?
Keyboard shortcuts: left arrow to go to previous, right arrow to go to next.

### Additional context

This issue is ready for development. See also [issue about adding buttons to the lightbox](https://github.com/vector-im/element-web/issues/337).

**Comment by t3chguy** [comment]
This issue is covered under the one you linked

> Should also be able to use left & right arrows

**Comment by kittykat** [comment]
Going to close this one in favour of the original after discussion
