### ISSUE TITLE
Search for multiple words in an encrypted room fails

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#20586]
### Steps to reproduce

Go to an encrypted room

Search for "foo bar". 

#### What did you expect?

To search successfully

#### What happened instead?

A Popup with `Index error: An invalid argument was passed: 'Query is invalid. SyntaxError'`

### Operating system

OS X

### Application version

Element Nightly version: 2022011601 Olm version: 3.2.8

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
Regression from https://github.com/matrix-org/seshat/pull/104

**Comment by t3chguy** [comment]
The fix seems to be effective on Nightly, @novocaine are we good to close this?

**Comment by dbkr** [comment]
Also working for me, so I'm going to say this is fixed.
