### ISSUE TITLE
Weird video calling visual bug

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#20580]
### Steps to reproduce

1. Start a video call
2. Screenshare
3. ????

#### What did you expect?
Definitely anything but this
#### What happened instead?
![image](https://user-images.githubusercontent.com/47131867/149657360-d513f0f5-f2dd-4a86-8ea1-da5a982388f8.png)

### Operating system

Windows 10

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

**Comment by dbkr** [comment]
Are you able to add any more detail on how to reproduce this? Was the person on the other end of the call on a particular device? The shape of the video box makes me think perhaps a mobile device?

**Comment by AverytheFurry** [comment]
> Are you able to add any more detail on how to reproduce this? Was the person on the other end of the call on a particular device? The shape of the video box makes me think perhaps a mobile device?

Yeah, they were on a mobile device but i dont believe their camera was on

**Comment by SimonBrandner** [comment]
> > Are you able to add any more detail on how to reproduce this? Was the person on the other end of the call on a particular device? The shape of the video box makes me think perhaps a mobile device?
> 
> Yeah, they were on a mobile device but i dont believe their camera was on

Ah, that would explain it, Android doesn't support https://github.com/vector-im/element-android/issues/3790 which causes this bug

Closing in favour of https://github.com/vector-im/element-android/issues/3790
