### ISSUE TITLE
Double focus when scrolling and mouseovering on spotlight

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20597]
### Steps to reproduce

1. enable spotlight in labs
2. hit cmd-k
3. type something common (e.g. matrix)
4. scroll with cursor keys, going beyond 1 page
5. then mouseover too

#### What did you expect?

single focused row

#### What happened instead?

stale focus on rows:

<img width="690" alt="Screenshot 2022-01-17 at 22 50 16" src="https://user-images.githubusercontent.com/1294269/149845165-f4f908c5-64bc-4bd3-bdd3-3de6d2d7c3ed.png">

### Operating system

macOS 12.1 on M1

### Application version

Nightly

### Will you send logs?

No

**Comment by t3chguy** [comment]
This matches the expectation from the WAI ARIA practices examples

![image](https://user-images.githubusercontent.com/2403652/149903774-dccc7919-0eda-49c8-b4bd-b5e67b769223.png)

https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html

but I guess the `Enter` shortcut being shown on the mouse-hovered one is indeed incorrect and needs fixing.
