### ISSUE TITLE
Read receipts are disappearing

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20592]
It seems like they are getting caught on hidden events (reactions, thread responses, etc) and not bubbling up to the latest visible message like they're supposed to

**Comment by novocaine** [comment]
@turt2live any chance of narrowing down the reproduction criteria? I can't see it happening ..

**Comment by turt2live** [comment]
It started happening 3 days ago, but unfortunately haven't really narrowed it down. Will keep an eye out.

**Comment by kittykat** [comment]
@turt2live on production or develop/Nightly? Need to know for regression tracking. Would be great if you could use the templates :+1:

**Comment by turt2live** [comment]
I haven't been able to track down when or why this started happening, so just going to close. 

It seems resolved for now.
