### ISSUE TITLE
Reset highlighted result to top result when backspacing through search

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20612]
### **Problem**

As noted in some web feedback captured as part of https://github.com/vector-im/element-web/issues/19706 when typing for something, people might type a word, get to 0 results and then use backspace to try a different search.  They then struggle to use their keyboard to go to their preferred result. This is because:

- When they got 0 results: the browse public rooms became highlighted
- When they backspaced and entered an amended search term, public rooms was still highlighted <sup>1</sup>.  

### **Task**

- [x] Experiment with making backspace reset the highlight to be the first result

Notes 

<sup>1</sup> This might be part of the reason for https://github.com/vector-im/element-web/issues/20184

**Comment by t3chguy** [comment]
This would break the expectations as defined by WAI-ARIA and worsen accessibility I believe. I will dig up the relevant gospel on Monday
