### ISSUE TITLE
Instrument metrics for web for the IA project

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20613]
We want to know if the IA changes are successful. For this we need to learn more about how users currently use element and whether the IA changes are improving or not making worse their workflows.

Details of what needs to be instrumented are [in this internal spreadsheet](https://docs.google.com/spreadsheets/d/1ggIEyF2gYWjbCUiycPO2WwiK31gv_Cl7ShmdHP1JC1I/edit#gid=0).

## Search
- [x] [Funnel for open search > visit room > open search again](https://posthog.hss.element.io/dashboard/79) (within time constraint)
- [x] [Time and frequency to go from open search to click result](https://posthog.hss.element.io/dashboard/79)
- [x] [Frequency of open search and close without clicking result](https://posthog.hss.element.io/dashboard/79)
- [x] [Frequency of no search results returned (this needs more investigation before we know how we want to track this)](https://posthog.hss.element.io/dashboard/79)

## Room header menu
We should be able to use screen/previous screen features in PostHog to know where users are accessing things from, if there are multiple ways to access them.
- [x] [How are favourites being added (which path leads to a room being favourited) ](https://posthog.hss.element.io/dashboard/79)
- [x] [How Notifications settings for a room are being accessed](https://posthog.hss.element.io/dashboard/79)
- [x] [Path to room member list is being accessed](https://posthog.hss.element.io/dashboard/79)
- [x] [Path to invite to room (which menu is the link accessed from? are users using the "invite" button in member list?)](https://posthog.hss.element.io/dashboard/79)
- [x] [Path to users are leaving rooms](https://posthog.hss.element.io/dashboard/79)
- [x] [Path to room settings are being accessed](https://posthog.hss.element.io/dashboard/79)

## Rooms
- [x] [Path for users to join a room](https://posthog.hss.element.io/dashboard/79)
- [x] [Point of entry to create room dialog](https://posthog.hss.element.io/dashboard/79)
- [x] [How many favourited rooms does a user have (split between new and experienced users)](https://posthog.hss.element.io/cohorts)

## Metaspaces and quick settings
We can use user properties rather for users preferences, and then should be able to visualise from there.
- [x] Number of (experienced) users with metaspaces changed from default
- [x] [Which metaspaces are being used](https://posthog.hss.element.io/cohorts)
- [x] [How many users have Home set to "show all rooms"](https://posthog.hss.element.io/cohorts)
- [x] [Path to enabling/disabling metaspace settings](https://posthog.hss.element.io/dashboard/79)
- [x] [Path to theme change (available in User Menu, Quick Settings, User Settings)](https://posthog.hss.element.io/dashboard/79)

## Space header
Should add a user property for how many spaces the user is in
- [x] [Add a user property for how many spaces the user is in - to split users into cohorts](https://posthog.hss.element.io/cohorts)
- [ ] Source of invite to space
- [x] [Number of times explore space is accessed and how](https://posthog.hss.element.io/dashboard/79)
- [x] [Number of times a space is clicked in the left panel and "explore for that space is accessed within 3 seconds](https://posthog.hss.element.io/insights?events=%5B%7B%22id%22%3A%22Interaction%22%2C%22math%22%3Anull%2C%22name%22%3A%22Interaction%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22name%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22SpacePanelSwitchSpace%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22Interaction%22%2C%22math%22%3Anull%2C%22name%22%3A%22Interaction%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22name%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%5B%22SpacePanelSelectedSpace%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%5D&layout=vertical&display=FunnelViz&insight=FUNNELS&interval=day&date_from=-90d&funnel_viz_type=time_to_convert)

## Breadcrumbs
- [x] [Source of room open](https://posthog.hss.element.io/dashboard/79)

## Descoped
- [ ] Length of session for room accessed via breadcrumb (we want to compare old breadcrumbs against new ones)

**Comment by gsouquet** [comment]
@kittykat what kind of support do you believe is required here? From what I gather this should be ready to work on? 
Unless there were some technical limitations to tracking the remaining unchecked list items

**Comment by kittykat** [comment]
@gsouquet this was probably requiring support from ops as we needed a posthog upgrade to be able to do time-based tracking. This has now happened.

I've descoped the breadcrumb tracking item, but space invites haven't been marked as implemented.

**Comment by kittykat** [comment]
I believe this issue is now done
