### ISSUE TITLE
Please avoid git+https dependencies

### ISSUE THREAD

**Issue by PF4Public** [vector-im/element-web#20628]
Please avoid git+https dependencies. This creates difficulties with the packaging.
For example:
https://github.com/vector-im/element-web/blob/aed3467fdf890e48ae5f0fc288918df4b73c10f2/yarn.lock#L8040-L8042

This could be achieved for example if using  `"matrix-analytics-events": "matrix-org/matrix-analytics-events#1eab4356548c97722a183912fda1ceabbe8cc7c1",` here:
https://github.com/matrix-org/matrix-react-sdk/blob/0b83dfcd63e238974afe3d8f3c7d08f09fe6ddef/package.json#L88
```json
"matrix-analytics-events": "https://github.com/matrix-org/matrix-analytics-events.git#1eab4356548c97722a183912fda1ceabbe8cc7c1",
```

Alternatively release `matrix-analytics-events` as a node module, so that it could be easily referenced by yarn.

**Comment by dbkr** [comment]
Can you go into more detail on the packaging issues this causes (or provide a link?)

**Comment by PF4Public** [comment]
@dbkr If the dependency is specified such as 
```json
"matrix-analytics-events": "matrix-org/matrix-analytics-events#1eab4356548c97722a183912fda1ceabbe8cc7c1",
```
Yarn resolves this into a plain URL, something along the lines of https://codeload.github..blabla../tar.gz/1eab4356548c97722a183912fda1ceabbe8cc7c1, which is a plain tarball, which could be supplied with other dependencies in yarn cache , making yarn use this cache instead of downloading every package.

**Comment by dbkr** [comment]
Ah, of course - makes sense, and indeed this is how we specify our other deps from GH repos too, so good to be consistent.
