### ISSUE TITLE
Invite dialog margins are visually inconsistent

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20631]
### Steps to reproduce

Open an invite dialog

### Outcome

![Screenshot 2022-01-18 at 23-09-02 Element general](https://user-images.githubusercontent.com/48614497/150062571-1bd1efc2-fde0-49b1-b9a4-971a99f6d843.png)

#### What did you expect?

The dialog should have a uniform margin on all 4 sides, matching the visual style of all other dialogs in the application.

#### What happened instead?

The dialog seems as if all 4 sides have a different margin, which looks unusual. Additionally, there seem to be two different margin widths in use on the right side. (The 'invite' button and 'X hours ago' labels are indented further than other elements.)

### Operating system

NixOS unstable

### Browser information

Firefox 96.0

### URL for webapp

develop.element.io

### Application version

Element version: 840867bc0212-react-a00d359422a6-js-652b3a9208f0 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by luixxiul** [comment]
Which margin are you talking about?

![after](https://user-images.githubusercontent.com/3362943/158556142-c29d6422-3082-41dc-b75d-7b68e905168d.png)

The top (above `Invite ...`) and the left (left of `Recently ...` and `Suggetions`)?

**Comment by robintown** [comment]
Yes, that's correct

**Comment by robintown** [comment]
See https://github.com/matrix-org/matrix-react-sdk/pull/6111#issuecomment-850258228 for the layout that was being discussed by the designers

**Comment by andybalaam** [comment]
Hmm, seems like I should have passed the PR to the designers after all, sorry about that.

**Comment by luixxiul** [comment]
@niquewoodhouse how much padding on the top above the heading is preferred? I checked https://github.com/matrix-org/matrix-react-sdk/pull/6111#issuecomment-850258228 but I cannot really find the instruction about that.

**Comment by luixxiul** [comment]
> Hmm, seems like I should have passed the PR to the designers after all, sorry about that.

That's what I missed, you should not be sorry...

**Comment by luixxiul** [comment]
By setting the same padding on the top and on the left:

![margin](https://user-images.githubusercontent.com/3362943/158664016-0fb9ac2a-567c-4482-95cd-a77014867602.png)

Is this fine?

**Comment by robintown** [comment]
It would probably be better to simply remove the extra left and right padding on the dialog's contents, so that it just uses the standard 24px padding on all sides.

**Comment by robintown** [comment]
(as in this image from that PR I linked to:)

![padding](https://user-images.githubusercontent.com/1587166/119956446-05044700-bf99-11eb-95c2-4478d0abacad.png)

**Comment by luixxiul** [comment]
I have not been so sure about it due to `// the design wants some padding on the left` on https://github.com/luixxiul/matrix-react-sdk/blob/7cea71085e4ba4bf5eed8427cece76b607c3a753/res/css/views/dialogs/_InviteDialog.scss#L276. Is it no longer valid?

**Comment by robintown** [comment]
Right, that's why this will need input from the design team. If they approve of the changes, it won't be valid anymore.
