### ISSUE TITLE
Editing a thread reply makes the thread panel go blank

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20633]
### Steps to reproduce

In a thread, try editing one of your replies and save changes.

#### What did you expect?

The edits to be saved and the inline editor to be automatically dismissed.

#### What happened instead?

The thread panel went blank.

### Operating system

macOS 12.1

### Browser information

Chrome 96.0.4664.110

### URL for webapp

develop.element.io

### Application version

Element version: 85f6c3b21f80-react-18c82d57ae0a-js-16ca09eed811 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment]
Can reproduce on Element version: 840867bc0212-react-41b9e4aa4f6f-js-a50a627300df, Olm version: 3.2.8 with Chromium
