### ISSUE TITLE
Three-party DM display one mxid in search results

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20634]
### Steps to reproduce

Create a three party DM
Enable the new search modal
Search for it

#### What did you expect?

The mxid should not be displayed for the first result as it's confusing. There are 3 people in that room

#### What happened instead?

<img width="605" alt="Screen Shot 2022-01-19 at 09 17 33" src="https://user-images.githubusercontent.com/769871/150100944-02692eda-98f8-4ca8-b57a-ce9cc51b59d1.png">

### Will you send logs?

No

**Comment by t3chguy** [comment]
a three-party DM isn't technically valid, its a DM with one of those users and just has a bystander inside it. Immutable DMs MSC will clear this up.

**Comment by t3chguy** [comment]
> The mxid should not be displayed for the first result as it's confusing. There are 3 people in that room

I disagree, if the 3rd user was the Github bot, I'd still want it to be treated exactly like any other DM

**Comment by gsouquet** [comment]
> Immutable DMs MSC will clear this up.

Not quite sure I understand how this will solve this problem? It is rather confusing to display one mxid here, when the message will not be sent to that user only.

**Comment by t3chguy** [comment]
Immutable DMs will restructure DMs altogether, distincting important users (people) from bots, right now DMs always assume 1:1 + unimportant users (bots) hence only one MXID being shown.

**Comment by gsouquet** [comment]
But we give users the ability to mark any type of rooms as a DM using `/converttodm`.
We can't really run under the assumption that a DM will be 1:1 only as there are multiple cases where this won't be the cases

**Comment by t3chguy** [comment]
Slash Commands are for power users

> We can't really run under the assumption that a DM will be 1:1 only as there are multiple cases where this won't be the cases

That's simply how broken the DM support is currently, in a 3 person DM between A, B, C

A may see it as a DM with B
B may see it as a DM with C
C may see it as a non-DM

It's all very brittle.

**Comment by kittykat** [comment]
We decided to not display MXIDs for 3+ party DMs but to improve the searching so that the result returns if any member in the DM matches the search term
