### ISSUE TITLE
add keyboard shortcut to toggle Show hidden events in timeline

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20646]
#### What would you like to do?
toggle the labs setting Show hidden events in timeline by keyboard combination

#### Why would you like to do it?
Show hidden events in timeline is at the very bottom of a 3 deep menu (main menu, settings, labs, scroll to bottom). Switching back and forth is quite the hassle

#### How would you like to achieve it?
add a keyboard shortcut like <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd>

### Have you considered any alternatives?

add it to quick settings if developer mode is on or so

**Comment by UwUnyaa** [comment]
Do you need to enable some sort of developer mode in order to be able to view the labs tab in settings? I cannot find it, even in element running in dev mode.

**Comment by UwUnyaa** [comment]
I just found that it's an option in `settings.json`. I assume this means this shortcut should be only present if that option is enabled.

**Comment by HarHarLinks** [comment]
> I cannot find it, even in element running in dev mode.

perhaps it should get moved out of labs into dev mode anyway? it's not an experimental element feature, but a dev feature(?)

**Comment by UwUnyaa** [comment]
It's only available if you enable labs. Because of that, the amount of changes is slightly larger. I almost have an initial patch ready, I just ran into some tooling issues, preventing me from creating clean diffs.

**Comment by dbkr** [comment]
Yeah, develop.element.io and the nightly desktop build have that option on and so have labs available. And yep, it's one of the advanced / developer settings that's got mixed up under labs, so shouldn't really be there. Thanks for looking at this!

**Comment by t3chguy** [comment]
Merged
