### ISSUE TITLE
Threads: No Thread summary shown in timeline

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#20649]
### Your use case

During Testing we found some messages were not showing the Thread Summary on the timeline.

If the Thread panel was open the Thread showed correctly in the Thread list, the summary just didn't render on the timeline...

**Comment by gsouquet** [comment]
Can not reproduce this one anymore.
@daniellekirkwood could you give it another go and let me know whether that's something you experienced too or not?
