### ISSUE TITLE
Using Tab on spotlight without typing looks weird

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#20645]
### Steps to reproduce

1. Open spotlight search
2. Use Tab to navigate through the Recently Viewed room list without typing a search term

#### What did you expect?

Tab should highlight each room as it tabs through them

#### What happened instead?

The selected room is only indicated by having both the room name and the "this room is public" labels display near the selection, overlapping one another.

![pic-selected-220119-1236-31](https://user-images.githubusercontent.com/41203525/150184249-749f24b9-7cef-47c6-81ab-219d6251c902.png)

It looks like there is some highlighting effect on "MyTest", but it doesn't move with Tab. Matrix HQ is selected and Enter opens Matrix HQ.

### Operating system

Arch Linux

### Browser information

Firefox 95

### URL for webapp

develop.element.io

### Application version

Element version: 840867bc0212-react-ec6bb8806822-js-a50a627300df Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
related #20339
