### ISSUE TITLE
Localization: Missing argument for phone number

### ISSUE THREAD

**Issue by libexus** [vector-im/element-web#20652]
The string [`Unable to find Matrix ID for phone number`](https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=f2afa74cab6c3fce) needs an argument for inserting the phone number because in German it does not fit at the end.

**Comment by libexus** [comment]
umm something went wrong with the feedback form, I'll edit it

**Comment by dbkr** [comment]
The phone number isn't actually appended to this string: it's just presented as-is (I think it's assumed the user can see what number they dialled as it's in the dialler).

**Comment by libexus** [comment]
@dbkr So do you think I could translate it into German so that it says somewhat like "This phone number has no Matrix-ID associated"?

**Comment by duxovni** [comment]
@libexus it looks like you've already submitted a better German translation? (Thank you!) I'm closing this, please let us know if this isn't actually resolved.
