### ISSUE TITLE
New threads created go to the end of the thread list (Thread list ordering)

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20654]
### Steps to reproduce

1. Visit a room with threads.
2. Open the thread panel to browse the current thread list.
3. Start a new thread.

#### What did you expect?

The new thread to be added to the topmost position of the thread list.

#### What happened instead?

It seems to go like this. When you first visit a room and are just browsing it, the order for threads is correct, but as soon as you create a new thread it gets added to the last position in the stack, instead of the topmost.

### URL for webapp

develop.element.io

### Application version

Element version: c40dbf158019-react-f59ea6d7adf5-js-230e3b4acee3 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by janogarcia** [comment]
**Top** - Correct order

![top](https://user-images.githubusercontent.com/60790/150386717-46b7a20c-c7fc-4013-b036-2836586b9bc6.png)

**Bottom** - New thread (posted @ 17:25) showing on the bottom of the list.

![bottom](https://user-images.githubusercontent.com/60790/150386733-d4b24ea4-39dc-45ef-b2c3-ecc3b2b0ab07.png)

**Comment by gsouquet** [comment]
As discussed internally last week, this behaviour is quite tedious to implement for clients when dealing with a paginated API.

This is currently blocked on https://github.com/vector-im/element-meta/issues/152 and the ordering will be based on the root thread rather than the last reply to a thread until we have a new sorting filter available server-side

**Comment by gsouquet** [comment]
Web now orders thread by the last reply time. In the future we will want this sorting to be done by the server, but for now we can consider this issue resolved
