### ISSUE TITLE
Cannot scroll to the beginning of an encrypted room

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#20658]
### Steps to reproduce

1. Try to scroll up using Home key
2. In the certain point scrolling ends and beginning of an encrypted room cannot be reached

#### What did you expect?
Scrolling to the beginning.

#### What happened instead?
Loading of history stopped. It works flawlessly on Element Android.
Cache has been flushed.

### Operating system

Windows 10

### Browser information

Firefox 97b5, Chrome 97.0.4692.71

### URL for webapp

own

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### Homeserver

own

### Will you send logs?

Yes

**Comment by waclaw66** [comment]
Possibly related to #18325

**Comment by t3chguy** [comment]
> In the certain point scrolling ends and beginning of an encrypted room cannot be reached

This sounds like you don't have the E2EE keys all that way back and thus the history is hidden from you by Element Web to avoid showing you a load of undecryptable errors.

Related https://github.com/vector-im/element-web/issues/19230
Caused by https://github.com/matrix-org/matrix-react-sdk/pull/3881

**Comment by waclaw66** [comment]
> This sounds like you don't have the E2EE keys all that way back and thus the history is hidden from you by Element Web to avoid showing you a load of undecryptable errors.

That's not that case, as I mentioned, it works fine on Element Android.

**Comment by t3chguy** [comment]
Element Android doesn't have the equivelant of https://github.com/matrix-org/matrix-react-sdk/pull/3881

**Comment by t3chguy** [comment]
If there is a single undecryptable message from before your join then the remainder of history will not be shown to hide UISIs

**Comment by waclaw66** [comment]
I can see all properly decrypted messages on Element Android (even in a newly created session) since the beginning od the room. I have to, I have created that room and posted the first message.
This has nothing to do with matrix-org/matrix-react-sdk#3881.
Seems like #18325.
While scrolling back there is shown a blank space (almost the whole screen height) before some decrypted message and scrolling get stucked. When I try to scroll to the future and back again, the blank space dissapers.
There is no message like _You can't see earlier messages_ or _** Unable to decrypt: The sender's device has not sent us the keys for this message. **_ that indicate E2EE key problems.

**Comment by t3chguy** [comment]
> Seems like #18325.

In that case are you happy to close this issue?

**Comment by waclaw66** [comment]
No problem, I found similarity with #18325 later on. Therefore this one seems like a dup.
