### ISSUE TITLE
Map in location sharing doesn't draw

### ISSUE THREAD

**Issue by lnicola** [vector-im/element-web#20655]
### Steps to reproduce

1. Enable location sharing in Labs
2. Click the share location button
3. If prompted by the browser give location access to the page

#### What did you expect?
A map.

#### What happened instead?
No map and a warning:

![image](https://user-images.githubusercontent.com/308347/150392763-41017cf5-5a9b-4892-8675-8185db8a2fae.png)

    WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

### Operating system

Linux

### Browser information

Firefox 98.0a1 (2022-01-19)

### URL for webapp

self-hosted 1.9.9

### Will you send logs?

No

**Comment by t3chguy** [comment]
Do you have the API Key in config.json?

https://github.com/vector-im/element-web/blob/develop/docs/config.md `36` `map_style_url`

**Comment by lnicola** [comment]
Thanks. I checked the sample config, but this key isn't there yet, of course. It might be worth printing a console message if the URL is empty.

**Comment by t3chguy** [comment]
It'd be better if the button was not available if there was no API Key - @andybalaam

**Comment by lnicola** [comment]
The problem with that is you won't know what to do if it's not working. At lease there should be a tooltip or error message.

**Comment by t3chguy** [comment]
But its not an error that an end-user can do anything about, its one for the (tiny) subset of users which are the operator of that Element instance

**Comment by t3chguy** [comment]
We do the same for rageshakes ftr, if there's no submit logs url in the config.json the button just vanishes

**Comment by andybalaam** [comment]
There is definitely intended to be a console log message about this.  I will check that first, then think about the other questions.

**Comment by andybalaam** [comment]
OK, I found the bug meaning that no error message is shown.  It will be fixed in https://github.com/matrix-org/matrix-react-sdk/pull/7623 .  As for not showing the button if the config is missing - we can handle this as a separate feature, but it's a little tricky because it affects all maps, not just sharing your own location, and it's really a problem that should be fixed by your server or client admin, rather than the user, so maybe a browser console message is the right way to handle it?

**Comment by t3chguy** [comment]
> and it's really a problem that should be fixed by your server or client admin, rather than the user, so maybe a browser console message is the right way to handle it?

Your client admin doesn't tend to ever see the end user's console though, so a missing button would be a bit more clear as something a user might complain about

**Comment by lnicola** [comment]
A missing button doesn't say anything. Maybe the feature isn't there (how could the user complain if they don't even know it's missing?). Maybe the feature is disabled. Maybe it's enabled but configured incorrectly. Maybe it's not working on some browser.

An error message can clear this up: "you tried to do X, it didn't work because Y".

**Comment by andybalaam** [comment]
I am inclined to agree with @lnicola .  I will feed this in to the design process - thank you.
