### ISSUE TITLE
Poll not working on desktop, at all

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#20659]
### Steps to reproduce

1. On mobile, enable polls through the Labs section in settings
2. On mobile still, create a poll
3. Now on desktop, open the same room

#### What did you expect?
The poll I just created.
But also, an option to be able to see them, if this feature must be behind a setting for some reason.

#### What happened instead?
No poll. Not even a placeholder of any kind. Silent failure. I would call this a form of data loss, even if data hasn't technically been lost, but just hidden away.
And no option to enable them.

### Operating system

Windows 10 21H2

### Application version

Element version: 1.9.9, Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
So you haven't enabled polls in labs on desktop?

**Comment by thany** [comment]
There is no Labs at all

**Comment by SimonBrandner** [comment]
> @SimonBrandner
> 
> > So you haven't enabled polls in labs on desktop?
> 
> There is no Labs at all, like I stated...

Labs have to be enabled through a config file on desktop. See https://github.com/vector-im/element-desktop/#config and https://github.com/vector-im/element-web/blob/develop/docs/labs.md. If you run into trouble be sure to visit https://matrix.to/#/#element-web:matrix.org

**Comment by thany** [comment]
Okay. But this doesn't solve the issue. The issue is also that a poll, without them enabled, shows *absolutely nothing*.

This will make people not having them enabled for *any* reason whatsoever, miss content that has been confirmed sent. This is not right. I would expect to see the sourcecode for a poll.

An on a more universal note: there shouldn't *ever* be a discrepancy on what content can show where. Every piece of content should be visible on every device, on every client, with any setting. Whether that content shows as intended, is secondary, but it should not be possible to completely miss out.

**Comment by thany** [comment]
@t3chguy That sounds like an explanation of why the problem exists. This means it still needs a solution, and it seems like it absolutely *can* have a solution.

**Comment by t3chguy** [comment]
You're asking for a solution in the wrong place, Element is doing the everything it can based on the msc.

**Comment by thany** [comment]
Like I said, content should just display - whatever that content is. Why can't Element just do that?

**Comment by t3chguy** [comment]
The msc should instruct senders to fill the body field, to match all previous fallbacks. How can a client which predates support otherwise show anything?

**Comment by thany** [comment]
I don't know, show source code, show something like "unknown message, expadable into its source code"

Just *nothing* is not okay. Anything would be fine, realy. Anything at all, just not nothing.

**Comment by t3chguy** [comment]
If you want to see unhandled events then you enable show hidden events, but then things will get very noisy for you.

**Comment by thany** [comment]
I don't know. But it's not just me. If someone sends something, it has to reach the recipients. It should never silently fail!

**Comment by t3chguy** [comment]
I agree, and there is a defined mechanism for this, events use the `body` field, this MSC is taking a very different approach which doesn't have backwards compatibility for clients without support of the future tech called Extensible Events which it itself is still an MSC. Showing all unhandled events to all users would be messy, I'd comment on the MSC that for clients without Extensible Events support (all clients atm) the lack of a fallback is jarring and lossy.

**Comment by thany** [comment]
I wouldn't say the solution is to show every unhandled event. Just the ones that would have displayed any sort of content. Surely, a poll contains some kind of content. Display that. Graceful degradation and all that.

I don't know what other events might make it "noisy" as you say, but the fact of the matter remains that one client sends real genuine earnest pieces of content that are effectly silently trashed by another. To a user, this is unacceptable.

**Comment by t3chguy** [comment]
> Just the ones that would have displayed any sort of content. Surely, a poll contains some kind of content. Display that. Graceful degradation and all that.

How can a client know which random event types it has never seen before are displaying any sort of content, and which fields to use for that content if it has never seen that event type before. The new event type should use the fallback mechanism to give older clients a chance.

**Comment by thany** [comment]
Maybe unknown events with content need to send fallback content.

Clients able to interpret the special type of event: display the special type of content in a special way, like a poll, and ignore fallback content.
Clients that don't know this type of event: display it as if it were a plaintext message - display the fallback content.

Kind of like how html + plaintext e-mail works.

**Comment by t3chguy** [comment]
Precisely, that's the intent. But this msc did not specify any fallback so the body of the event is empty. This body field is what other events use for their plaintext representation and clients unaware of such events may use as a fallback. For polls no such field exists because of the msc. I will not be going around in circles again, see the msc.

**Comment by thany** [comment]
> I will not be going around in circles again, see the msc.

Me neither. This is a form of data loss, which needs a fix. Whatever tat fix is, I don't really care. As a user, I also don't really care how the underlying system works, in the same way that I don't care how my washing machine works - I just need it to work. As a user, I don't want to miss content sent by others, and I don't want others to miss my content. That's all there is to it.

**Comment by t3chguy** [comment]
That content you can't see is in a format your client has no way of comprehending due to a weird choice during the MSC process. Its like someone sending you a letter in a foreign language, until you learn that language you cannot comprehend it.

**Comment by thany** [comment]
At least that letter arrives. It's much better than the postal service (or indeed my letterbox) deciding that an unreadable letter needs to be discarded, without my permission or consent.

**Comment by t3chguy** [comment]
How user-friendly do you think rendering

```
{
  "type": "m.poll.start",
  "sender": "@alice:example.org",
  "content": {
    "m.poll.start": {
      "question": {
        "m.text": "What should we order for the party?"
      },
      "kind": "m.poll.disclosed",
      "max_selections": 1,
      "answers": [
        { "id": "pizza", "m.text": "Pizza 🍕" },
        { "id": "poutine", "m.text": "Poutine 🍟" },
        { "id": "italian", "m.text": "Italian 🍝" },
        { "id": "wings", "m.text": "Wings 🔥" }
      ]
    },
    "m.message": [
      {
        "mimetype": "text/plain",
        "body": "What should we order for the party?\n1. Pizza 🍕\n2. Poutine 🍟\n3. Italian 🍝\n4. Wings 🔥"
      },
      {
        "mimetype": "text/html",
        "body": "<b>What should we order for the party?</b><ol><li>1. Pizza 🍕</li><li>2. Poutine 🍟</li><li>3. Italian 🍝</li><li>4. Wings 🔥</li></ol>"
      }
    ]
  },
  // other fields that aren't relevant here
}
```

Would be?
The MSC purposefully omitted a `body` field at the top level which would have been a sane fallback for the event to be readable by older clients, not sure why.

**Comment by thany** [comment]
It's better than nothing. Not delivering a message is *always* worse than delivering *anything at all* in its stead.
