### ISSUE TITLE
Clicking on the thread contextual actions in the thread list will open the thread

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20653]
### Steps to reproduce

Just click on the "View in room" or "Copy link to thread" button when hovering a thread in the thread list.

#### What did you expect?

**When clicking the "View in room" button**

The main timeline to scroll as necessary to display the root message in context, which is now highlighted. 

**When clicking the "Copy link to thread" button**

Copy the thread URL to the clipboard.

#### What happened instead?

**When clicking the "View in room" button**

Apart from scrolling the timeline and highlighting the message, it will also open the thread in the thread panel (which actually shouldn't happen). 

This won't happen of immediately repeating the action (i.e. when the message is already selected/highlighted in the main timeline as a result of having used "View in room" right before).

**When clicking the "Copy link to thread" button**

Apart from copying the URL, it will also open the thread in the thread panel.

This will happen every time the button is used.

### URL for webapp

develop.element.io

### Application version

Element version: c40dbf158019-react-f59ea6d7adf5-js-230e3b4acee3 Olm version: 3.2.8

### Will you send logs?

No

**Comment by novocaine** [comment]
This is still happening for "copy link" but not "view in room"
