### ISSUE TITLE
Favourites keep showing up in the people metaspace

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20664]
### Steps to reproduce

This happens at random, I see it maybe once or twice a day and at least for the last three days

1. Enable metaspaces in labs
2. Go to People

#### What did you expect?
To see only people

#### What happened instead?
Favourites and people show up

![Screenshot from 2022-01-19 14-53-50](https://user-images.githubusercontent.com/51663/150497975-3ccac324-14a2-4595-9df1-8d68783da86c.png)

### Browser information

Chromium 96.0.4664.110 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: c40dbf158019-react-2e6f616e91f6-js-230e3b4acee3 Olm version: 3.2.8 and earlier versions

### Will you send logs?

No

**Comment by gileluard** [comment]
Didn't reproduced with my version (may be a regression): 
Element version: 68f582601315-react-cf0141467e74-js-230e3b4acee3 Olm version: 3.2.8
