### ISSUE TITLE
Pills require two keypresses to move past

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20678]
### Steps to reproduce

Potentially platform specific.

1. Type a pill into the composer.
2. Press Home to place the cursor before the pill.
3. Press Right.

#### What did you expect?

The cursor should move to the right side of the pill.

#### What happened instead?

The cursor remained on the left. To move it past the pill, you have to press Right twice.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0

### URL for webapp

develop.element.io

### Application version

Element version: 06fa4f4440a4-react-010cbadc8ecf-js-230e3b4acee3 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This only happens if the pill is at the start of the composer

**Comment by robintown** [comment]
This happens because caret nodes, which are inserted before and after pills in some situations, contain a zero width space that the caret has to move past. To fix this, there would have to be some way to make the caret skip over the zero width space.
