### ISSUE TITLE
Logging in with JWT token gives error after trying to save keys for e2e encryption

### ISSUE THREAD

**Issue by Rakiah** [vector-im/element-web#20673]
### Your use case

Hello everyone, this is more of a question but could not found any categories to put it, sorry

#### What would you like to do?

I've tried to modify Element application to support JWT login using the `loginToken` query parameter, so far so good I get logged in correctly and it kind of "generate" an account in Synapse if it doesn't exist already, however once I try to setup e2e keys, I get an error when saving passphrase as follow:

![image](https://user-images.githubusercontent.com/16012885/150574774-cfef67e9-dd47-4fab-a1c4-f4890a3551fb.png)

and I get in the console the following failed request:
![image](https://user-images.githubusercontent.com/16012885/150575147-501b8656-2426-4f26-b79b-9c58da7e03a9.png)

with the following body:
![image](https://user-images.githubusercontent.com/16012885/150575185-a67706f5-9ca5-4667-8a76-cd257023ef5a.png)

the code i've edited is quite slim and only apply to the `Lifecycle.ts` file in `matrix-react-sdk` as follow:

line 188 before my changes:
```
const homeserver = localStorage.getItem(SSO_HOMESERVER_URL_KEY);
```
line 188 after my changes:
```
const homeserver = "https://matrix.dev.obvious.tech";
```

line 204 before my changes:
```
        "m.login.token", {
```
line 204 after my changes:
```
        "org.matrix.login.jwt", {
```

for a wider picture here is the snippet changed:

```
 const homeserver = "https://matrix.dev.obvious.tech";
    const identityServer = localStorage.getItem(SSO_ID_SERVER_URL_KEY);
    if (!homeserver) {
        logger.warn("Cannot log in with token: can't determine HS URL to use");
        Modal.createTrackedDialog("SSO", "Unknown HS", ErrorDialog, {
            title: _t("We couldn't log you in"),
            description: _t("We asked the browser to remember which homeserver you use to let you sign in, " +
                "but unfortunately your browser has forgotten it. Go to the sign in page and try again."),
            button: _t("Try again"),
        });
        return Promise.resolve(false);
    }

    return sendLoginRequest(
        homeserver,
        identityServer,
        "org.matrix.login.jwt", {
            token: queryParams.loginToken as string,
            initial_device_display_name: defaultDeviceDisplayName,
        },
    ).then(function(creds) {
        logger.log("Logged in with token");
        return clearStorage().then(async () => {
            await persistCredentials(creds);
            // remember that we just logged in
            sessionStorage.setItem("mx_fresh_login", String(true));
            return true;
        });
    }).catch((err) => {
```

#### Why would you like to do it?

Because my service already provide JWT tokens

### Have you considered any alternatives?

I'm trying first to see if I miss anything obvious before considering any alternatives as this flow would be very simple to integrate in my application and quite straight forward

**Comment by gsouquet** [comment]
This is not really an issue with Element Web but rather a support request.
I will close this issue and recommend you raise this on the [element-dev room](https://matrix.to/#/#element-dev:matrix.org) where people might be abe to assist you and find ideas on how to approach this

**Comment by Rakiah** [comment]
Isn't it an issue that logging in with JWT (which is, as stated by the documentation, supported) does not allow you to save end to end encryptions keys afterwards ?
@gsouquet

**Comment by linthertoss** [comment]
@Rakiah How's the issue going?
I am also having this issue.
If you have resolved it, so please suggest any solutions.
Thanks!
