### ISSUE TITLE
Shift+click to remove public room often opens two dialogs

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#20681]
### Steps to reproduce

**Do not take into account the intermediate error message in the video**

https://user-images.githubusercontent.com/57274151/150638210-53e99eb7-bf23-4d63-a119-2f502181395d.mp4

#### What did you expect?

Open only one "Remove from directory" dialog.

#### What happened instead?

Two MouseDown events are captured randomly, which causes "Remove from directory" dialog to be opened twice.

### Operating system

Ubuntu

### Browser information

Chromium 97 & FF 96

### URL for webapp

https://riot.im/app

### Application version

Element version: 1.9.9

### Will you send logs?

No

**Comment by gsouquet** [comment]
I have just tested this and there are many things wrong about those modals. 
None of them should be displayed in the first place. The keyboard shortcut should not react at all. The JS-SDK is aware of user membership and power levels

**Comment by t3chguy** [comment]
> The JS-SDK is aware of user membership and power levels

This is a hidden feature intended for server admins, so that a server admin can remove an alias from a room after they have left it (given it may not be possible to join it due to 0 people in the room)
