### ISSUE TITLE
Move "Developer mode" and related out of labs

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20683]
### Your use case

reference: https://github.com/vector-im/element-web/issues/20646#issuecomment-1017627680

#### What would you like to do?
Move "Developer mode" out of labs onto it's own settings category, similar element android's advanced settings. When developer mode is enabled, other options grouped under it should become available.

Dev mode (or "advanced settings" to stay in sync with android?) would become a new tab in the settings.

The obvious child option currently would be "Show hidden events in timeline" which should also get moved out of labs assuming it is stable.

In the future, experimental dev settings could be under labs, which required both labs and dev mode to be enabled.

#### Why would you like to do it?
While I would consider it an advanced feature for enthusiasts, it isn't only for developers working on element, but simply with element on something else. You might be using element to debug a bot/appservice sending replies, or set up something like hookshot or populus that use custom events.

Is Developer mode unstable in that sense?

**Comment by t3chguy** [comment]
Done

**Comment by HarHarLinks** [comment]
For anyone searching like I did: they are now in the `/devtools` modal
