### ISSUE TITLE
[sdk] Turn on `no-explicit-any`

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20692]
Related; https://github.com/matrix-org/matrix-js-sdk/issues/2115

https://github.com/matrix-org/matrix-react-sdk/blob/010cbadc8ecf9f15ade94d87950734c873ca6095/.eslintrc.js#L81-L82;

```js
            // We disable this while we're transitioning
            "@typescript-eslint/no-explicit-any": "off",
```

**Comment by gsouquet** [comment]
I'm going to close this issue and keep matrix-org/matrix-js-sdk#2115 as the canonical source.
