### ISSUE TITLE
[sdk] Have react-sdk pass TSconfig `strict: true` 

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20693]
Related: https://github.com/matrix-org/matrix-js-sdk/issues/2116

Sub-issues;
- [ ] `strictNullChecks`: TBD
- [ ] `strictFunctionTypes`: TBD
- [ ] `noImplicitAny`: TBD
- [ ] ... (more from https://www.typescriptlang.org/tsconfig#strict)

Related: https://github.com/vector-im/element-web/issues/20692

**Comment by gsouquet** [comment]
I'm probably going to close this issue and keep matrix-org/matrix-js-sdk#2116 as the canonical source.
This is to avoid content getting out of sync. Even though the issue has been open very recently I can see that their content already differ

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21967 & https://github.com/vector-im/element-web/issues/21968
