### ISSUE TITLE
App never launched.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20698]
### Steps to reproduce

1. Laptop kernel panicked and rebooted
2. On reboot, macOS tried to relaunch all apps

### Outcome

3. Element Nightly sat there spinning for about ~10 minutes on the fullscreen spinner and never completed.

### Operating system

macOS 12.1 on M1

### Application version

nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@ara4n have you seen this since?

**Comment by turt2live** [comment]
Closing as presumed fixed or non-recurring. If this is untrue, please open a new issue with fresh information and reproduction steps.
