### ISSUE TITLE
VoIP Voice Activity

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#20690]
### Your use case

Have my voice only transmit above a certain noise gate/voice level/detection.

Discord has this feature alongside push-to-talk, it would be nice if Element implemented this as well.

**Comment by HarHarLinks** [comment]
In my experience with teamspeak, this mode works best if you (can) disable all kinds of automatic volume adjustments, since otherwise if you don't say anything for a bit, it will adjust volume thinking the background noise is you talking. Idk how (well) discord handles this.

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/1673
