### ISSUE TITLE
Explore Space ID in the settings in the same way as for rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20704]
#### What would you like to do?
I want to find the room ID for a space that I am a member of (not admin)

#### Why would you like to do it?
So I can manage the space more effectively

#### How would you like to achieve it?
By being able to look it up in the settings or devtools, same as for any other room

### Have you considered any alternatives?

Look it up from inside one of the child rooms using devtools

### Additional context

This would be useful to me as someone who is managing a space via a bot rather than my own account.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/17399

**Comment by gsouquet** [comment]
Closing this issue to make #17399 the one place to discuss this matter
