### ISSUE TITLE
Joining a space took over 4 minutes.

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#20717]
### Steps to reproduce

1. Where are you starting? What can you see?

I received a space invitation to join the Fosdem testing space. 

2. What do you click?

I clicked Accept on the space invite.

#### What did you expect?

To be joined to the space in 10-20 seconds.

#### What happened instead?

After 4 minutes of waiting, I gave up, clicked over to another space/room and then took a 30 minute call. When I came back from the call, I found that I had been joined to the space.

### Operating system

Fedora Linux 35

### Browser information

Brave (Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit))

### URL for webapp

Private Server. 

### Application version

Element version: 869b271f72f9-react-869b271f72f9-js-869b271f72f9 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Performance suggests its something client-side, but Element can't do anything about a Synapse API being super slow.

**Comment by hex-m** [comment]
It seems like the client aborts trying to join when you bring a different room to the foreground. That counts as a client bug imo.

To gracefully deal with slow server actions, I'd expect the client to tell me that it seems to take a while - let me go on doing stuff - and ping me when it's ready.

**Comment by t3chguy** [comment]
> It seems like the client aborts trying to join when you bring a different room to the foreground. 

It is impossible to abort a `/join` - there is nothing in the Matrix spec which allows for this.

**Comment by t3chguy** [comment]
> I could press "Reject" or "Accept" again.

The client has no way of knowing which joins are still ongoing, which the server has given up with etc because the server timed out so the pipeline for the error/success to come down is severed.

**Comment by t3chguy** [comment]
If you are still experiencing this, please open an issue in https://github.com/matrix-org/synapse/
