### ISSUE TITLE
Space before link in list is deleted when a message is edited

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20718]
### Steps to reproduce

1. Send this message: `* this is a space [before a link](link)`
2. Edit this message, see `* this is a space[before a link](link)` in the composer

#### What did you expect?
`* this is a space [before a link](link) - edited`

#### What happened instead?
`* this is a space[before a link](link) - edited`

### URL for webapp

develop.element.io

### Application version

Element version: 03e776d9c4cc-react-9d9b77d5e1c5-js-fab7b7f26ae5 Olm version: 3.2.8

### Will you send logs?

No

**Comment by gsouquet** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7453
