### ISSUE TITLE
Narrow polls overlap timestamp in message bubble layout

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#20712]
![image](https://user-images.githubusercontent.com/2403652/150796041-dcd11ce0-3cfd-4df2-95fd-8cc6c305e302.png)

**Comment by daniellekirkwood** [comment]
@t3chguy do you have what you need to move forwards with this issue?

**Comment by t3chguy** [comment]
Nope

**Comment by daniellekirkwood** [comment]
Hi @gaelledel as the designer on Polls can you provide the figma link for this use case please? Thank you

**Comment by gaelledel** [comment]
I don't have specific designs for polls in bubbles as this goes beyond this feature design but I can provide some guidance based on the current implementation.
It would be good to mimic the visual style of the state of Polls in a default layout view when bubble is activated like below with the timestamp being placed under the avatar
<img width="1440" alt="Screenshot 2022-01-27 at 11 19 22" src="https://user-images.githubusercontent.com/76945183/151349319-70fbb26e-1041-4628-88a1-48a23472dacd.png">

Currently the size of the options are too small
<img width="1440" alt="Screenshot 2022-01-27 at 11 18 42" src="https://user-images.githubusercontent.com/76945183/151349315-3f920dbb-9d57-4f57-b170-db8d491079e3.png">

Happy for @amshakal to make further calls on how she would like to handle this case scenario

**Comment by daniellekirkwood** [comment]
Thanks, @gaelledel 

Sorry, I don't think I communicated this particularly well. 

Polls will stay as you've designed. We will not be placing Polls inside of Bubbles. The issue we're running into is when a poll is too "thin" the timestamp overlaps with the other content. I would understand that this is a use case faced by the whole polls project, not just the bubbles+polls project.

Where should the timestamp for a poll go when the poll is not wide enough to support the timestamp and the content underneath the poll?

**Comment by t3chguy** [comment]
@daniellekirkwood it looks like @gaelledel is suggesting that polls should not shrink down to the minimum size to fit their Questions & Answers, in Modern layout they take up a lot of width regardless the content. This would fix the overlap issue between timestamp & the polls text

**Comment by gaelledel** [comment]
Yes to @t3chguy comment. The options should only shrink when minimizing the view port. A constraint should be put in place so it does not minimise to create the overlap mentioned above.

**Comment by t3chguy** [comment]
We can probably grow the poll to the max width of a bubbles column (70%) to match long text bubbles

**Comment by daniellekirkwood** [comment]
Sounds good, so long as y'all are aligned on that approach 👍
