### ISSUE TITLE
Crash when viewing pinned messages after pinning a threaded encrypted image

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20714]
### Steps to reproduce

Unsure as I'm unable to reproduce, but this is roughly what happened:

1. In an encrypted room, upload an image to a thread
2. Pin the image
3. Open the pinned messages panel

#### What did you expect?

To see the pinned message.

#### What happened instead?

"Something went wrong!"

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 03e776d9c4cc-react-6806c2cdca98-js-fab7b7f26ae5 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
I have not been able to reproduce this issue either. Have asked a couple of more people to test this out

**Comment by gsouquet** [comment]
@robintown Can you confirm whether this still happens to you or not?
Have not been able to reproduce not have heard of anyone else encountering this?

**Comment by robintown** [comment]
I still haven't succeeded at reproducing it in a different room, but opening the pinned messages panel in that room still triggers the crash.

**Comment by t3chguy** [comment]
This is a MemberAvatar (from LocationBodyContent) being rendered with a null member exploding, will fix this.
