### ISSUE TITLE
In-app link navigation broke on Element Nightly and develop

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#20715]
### Steps to reproduce

1. Someone sends a matrix.to link in a room
2. Click the link
3. The browser opens, instead of Element following the link

#### What did you expect?

I would expect Element to follow the matrix.to link

#### What happened instead?

The browser opens

### Operating system

macOS

### Application version

Element Nightly version: 2022012401

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

ergaster.org

### Will you send logs?

Yes

**Comment by jryans** [comment]
@thibaultamartin Could you provide more detail on the specific link you tried? On my first attempt, I was navigated inside Element, so it may come down to the precise link type.

Feel free to message me privately if needed.

**Comment by turt2live** [comment]
For me this broke with a pill (from a bot, but rendered as a pill). See https://github.com/vector-im/element-web/issues/20719

**Comment by jryans** [comment]
I can try to take a look tomorrow morning if no one picks this up before.

**Comment by thibaultamartin** [comment]
> @thibaultamartin Could you provide more detail on the specific link you tried? On my first attempt, I was navigated inside Element, so it may come down to the precise link type.

It seems to be links to a message. For TWIM, my bot gives me a link to the messages people sent to report news. A typical link will be https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$yR7i-3aGQ_Ztbhj5wJAx_Gq6NBml8PX9gbIijD43UgU

I just tested: links to a room (e.g. https://matrix.to/#/#sliding-sync:matrix.org) do work correctly

**Comment by jryans** [comment]
I'll see what I can do here.
