### ISSUE TITLE
People right panel broken on Nightly and develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20716]
### Steps to reproduce

1. On develop.element.io or in today's Nightly, go to a space where you haven't had the people panel open recently and navigate Explore Space -> click on members to open right panel

#### What did you expect?
See list of space members

#### What happened instead?
For spaces where I didn't already have the panel open, I see a blank panel that doesn't load. For spaces where I recently had the panel open, I see list of People.

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io (also on Nightly)

### Application version

Element version: 03e776d9c4cc-react-26e1570dd6b0-js-fab7b7f26ae5 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/7609 claimed to fix this

**Comment by SimonBrandner** [comment]
> [matrix-org/matrix-react-sdk#7609](https://github.com/matrix-org/matrix-react-sdk/pull/7609) claimed to fix this

Hmm, I could have sworn it did, but now I am seeing empty panels everywhere...

**Comment by jryans** [comment]
> Hmm, I could have sworn it did, but now I am seeing empty panels everywhere...

I also recently merged https://github.com/matrix-org/matrix-react-sdk/pull/7575, which may have changed some of the right panel semantics.

**Comment by jryans** [comment]
I'll try to sort out what's happened here.
