### ISSUE TITLE
Vertical gradient on images extends over E2EE shields

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20713]
### Steps to reproduce

1. Enable bubble layout
2. Create an unencrypted room
3. Upload an image
4. Enable encryption

### Outcome

![Screenshot 2022-01-24 at 09-06-24 Element testing](https://user-images.githubusercontent.com/48614497/150797885-8c9e8500-5e3b-46f9-8347-ef492eb81c96.png)

#### What did you expect?

The gradient should only cover the image.

#### What happened instead?

The gradient extends to the left of the image to cover the E2EE shield as well.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 03e776d9c4cc-react-6806c2cdca98-js-fab7b7f26ae5 Olm version: 3.2.8

### Homeserver

townsendandsmith.ml

### Will you send logs?

No

**Comment by t3chguy** [comment]
@amshakal does the Figma design account for these e2ee icons?

**Comment by nadonomy** [comment]
@t3chguy @daniellekirkwood if it helps move along while @amshakal is away— I think it's just an execution oversight, very confident the original intention matches the suggestion & comment here for the gradient to visually mask the image only.

**Comment by t3chguy** [comment]
> the gradient to visually mask the image only.

Right, this is clear

But the work to right it is non-trivial, so if the e2e icon was going to move anyway (e.g overlaid like the timestamp is) that'd save the non-trivial work

**Comment by robintown** [comment]
The gradient has been removed
