### ISSUE TITLE
Where do I find the security code?

### ISSUE THREAD

**Issue by Adithr123** [vector-im/element-web#20727]
### Steps to reproduce

I cant find the security code to verify between accounts.

### Outcome

NA

### Operating system

Linux

### Browser information

Chrome Os

### URL for webapp

develop.element.io/

### Application version

Element version: c778aa82441c-react-6ac3a925130e-js-033693283dca Olm version: 3.2.8

### Homeserver

matxix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
Please ask questions in the support rooms, not on the issue tracker. #element-web:matrix.org on Matrix should be able to help.
