### ISSUE TITLE
matrix.to and matrix.org no longer linkified when just the bare domain

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20720]
example.org is linkified, but a literal matrix.org is not

**Comment by gsouquet** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7453

**Comment by turt2live** [comment]
possibly related to https://github.com/vector-im/element-web/issues/20715

**Comment by jryans** [comment]
I'll take a look. It seems regressed by the same PR (https://github.com/matrix-org/matrix-react-sdk/pull/7453), but it's a fairly distinct cause from https://github.com/vector-im/element-web/issues/20715.

**Comment by jryans** [comment]
In the end, we needed to patch linkifyjs to understand that domains can start with schemes. For the moment we're on a fork for this and other reasons. I have filed an [upstream issue](https://github.com/Hypercontext/linkifyjs/issues/374) as well.
