### ISSUE TITLE
Add `feature_thread` to `labs.md`

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#20728]
Was supposedly going to happen a while back but still hasn't https://github.com/vector-im/element-web/pull/18872#pullrequestreview-745689188

cc @gsouquet

**Comment by eleensmathew** [comment]
Hi can I work on this. Since I am a newbie please guide through resolving the issue.

**Comment by eleensmathew** [comment]
Hi i created a pull request https://github.com/vector-im/element-web/pull/20761. Please review and tell me if any changes are to be made.

**Comment by eleensmathew** [comment]
Hi i created a pull request #20761
<https://github.com/vector-im/element-web/pull/20761>. Please review and
tell me if any changes are to be made.

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/element-web/pull/21303
