### ISSUE TITLE
Element Web / Desktop stores messages unencrypted in IndexedDB

### ISSUE THREAD

**Issue by DatanoiseTV** [vector-im/element-web#20729]
Recently, I found out that Element Web doesn't store the history encrypted. On MacOS this results in complete chat history being stored in ˜/Library/Application Support/Element/IndexedDB/vector_vector_0.indexeddb.blob, which is a huge privacy problem.

I think it would contribute greatly to user's privacy when the indexed DB would be protected with a passphrase, for which the  user gets a prompt after first login and sets a cookie that expires in a set amount of time.

Another approach would be to allow the user to choose not to store history to disk / to store it only in an in-memory database.

**Comment by gsouquet** [comment]
Element does store encrypted room events in their encrypted form.
If you are aware of any security or privacy implications would you be able to email security@matrix.org as a public forum is probably not the right place for this type of issues.
