### ISSUE TITLE
Registration: Network failure will show "Someone already has that username."

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#20725]
### Steps to reproduce

1. https://app.element.io/#/register
2. Disable your WiFi/network to simulate going offline.
3. Type in a user name.

#### What did you expect?
An error message about being offline or that the app was otherwise unable to check if the username is unavailable.

#### What happened instead?
The network request `GET https://fosdem-attendees.ems.host/_matrix/client/r0/register/available?username=jaller94` had failed.

Element told me that the username is taken. As a non-experienced user I would assume this is the truth an pick a different username. This is frustrating, if it was just a short network issue.

![Screenshot_2022-01-24_22-06-25](https://user-images.githubusercontent.com/10872136/150865683-f5878ae0-97d0-4c44-9011-7dab18764bbb.png)

### Operating system

Manjaro Linux

### Browser information

Firefox Developer 97

### URL for webapp

https://chat.fosdem.org

### Application version

Element 1.9.9

### Homeserver

attendees.fosdem.org

### Will you send logs?

No

**Comment by Vinayaka2k** [comment]
Hello, tried reproducing this in chrome, Windows OS. The` username is taken `error seems to appear with/without network failure

**Comment by dbkr** [comment]
If someone's looking to pick this up as a good first issue, this would be the registration code of react-sdk calling a matrix-js-sdk method to then call this REST API, and obviously the js-sdk API should distinguish failures from the username not being available.

**Comment by t3chguy** [comment]
err I already did this :'(

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7621
