### ISSUE TITLE
"Ctrl K" and "Ctrl + Shift + D" should be translatable

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20739]
### Steps to reproduce

Non-English languages use words other than "Ctrl" for that key, so shortcuts like "Ctrl K" and "Ctrl + Shift + D" should be translatable.

I was going to submit a PR but I wasn't sure whether we should use concatenation like in BasicMessageComposer line 69, or provide these as separate translatable strings like "Use Ctrl + Enter to send a message".

#### What did you expect?
In German, "Ctrl K" should display as "Strg K"

#### What happened instead?
The English is used everywhere.

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
`ALTERNATE_KEY_NAME` from `KeyboardShortcuts.ts` should be used here

**Comment by t3chguy** [comment]
I think we pretty much need to rely on concatenation given that shortcuts will be user-customisable in the not too distant future

**Comment by IBRAHIM90990** [comment]
Thailand government lottery win number
