### ISSUE TITLE
SSO user can't terminate/logout existing sessions

### ISSUE THREAD

**Issue by Nexus2k** [vector-im/element-web#20733]
### Steps to reproduce

1. User logs in using Google SSO (openidp)
2. User tries to logout existing/old session
3. Element asks for Password which SSO users don't have

#### What did you expect?
Sessions can be logged out by SSO users w/o query for password.

#### What happened instead?
User was asked for password instead.

### Operating system

macOS

### Browser information

Element native client

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Your server is misconfigured, the server can ask for SSO for logging out existing/old sessions.

**Comment by helkaluin** [comment]
Apologies for necro-ing, but is there documentation for the proper configuration for this? I've followed the docs in adding an OIDC provider, and I can successfully login with it, but on the "remove other sessions" dialogue it just asks for a password (which doesn't exist).

**Comment by t3chguy** [comment]
> Apologies for necro-ing, but is there documentation for the proper configuration for this? I've followed the docs in adding an OIDC provider, and I can successfully login with it, but on the "remove other sessions" dialogue it just asks for a password (which doesn't exist).

In your case your Matrix server is asking for the password, you need that end to be correct. I suggest seeking help from the software responsible for that. https://spec.matrix.org/v1.8/client-server-api/#user-interactive-authentication-api is the mechanism using which the server (wrongly) asks for a password in your case

**Comment by helkaluin** [comment]
Thanks for the swift reply. Your link and a bit a Googling on related terms led me to try disabling password_config in my Synapse, which resulted in Synapse asking for SSO during logging out other sessions.
