### ISSUE TITLE
Element Desktop freezes when typing ™ symbol

### ISSUE THREAD

**Issue by davidmehren** [vector-im/element-web#20746]
### Steps to reproduce

1. Try to enter a ™ symbol in the composer (on my keyboard layout, this works using AltGr + Shift + 8)

#### What did you expect?
A ™ symbol appears in the message composer

#### What happened instead?
Element Desktop freezes, the window goes white after a bit and Element has to be closed and restarted manually

### Operating system

Fedora

### Application version

Element Nightly 2022012501, Olm 3.2.8

### How did you install the app?

AUR package `element-desktop-nightly-bin`

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
I can reproduce, this may be a 🔥
