### ISSUE TITLE
Jitsi call sometimes started instead of 1:1 in room with 2 members

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#20753]
### Steps to reproduce

Unknown

#### What did you expect?
1:1 call started

#### What happened instead?
Jitsi call started

Looks like this is because the `summaryInvitedMemberCount` is getting stuck at 1 and then not updating once a user joins. We debugged and observed the state to have two room members, both of whom were joined, but since `getInvitedMemberCount()` uses `summaryInvitedMemberCount`, it was adding 1 from this value and thinking that there were three users in the room (when there had only ever been two).

@kittykat found this in community testing

### Will you send logs?

No

**Comment by dbkr** [comment]
I think this maybe a blocker too as I think this might be what a few people are experiencing which would suggest it could be quite common, and it's super confusing.

**Comment by kittykat** [comment]
Could this be fixed alongside the new user joins room during ongoing 1:1 call and then starts a second Jitsi call on join? Ping me tomorrow and I'll find the issue

**Comment by dbkr** [comment]
I think the cause of this was trying to fix that bug actually

**Comment by dbkr** [comment]
One way to repro this is to have A start a DM with B, have B join, then refresh the page on A. A's client will now have two room members, both with state join, summaryJoinedCount will be 2 but summaryInvitedCount will be 1.
