### ISSUE TITLE
Remove mentions of communities from `Keyboard` settings tab

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#20755]
![2022-01-25_19-54](https://user-images.githubusercontent.com/25768714/151040616-dfcf2bcb-52fa-4343-9b92-dadde1a8372d.png)

The name should be just `...recently visited room`

**Comment by t3chguy** [comment]
Also applies to spaces though

**Comment by aj-ya** [comment]
Hey! @t3chguy I would like to work on this issue.

**Comment by SimonBrandner** [comment]
> Also applies to spaces though

As far as I understand the shortcut, it will take you to the preview/next room, not the previous/next space necessarily. Having the word `space` just confuses me...

**Comment by SimonBrandner** [comment]
> Hey! @t3chguy I would like to work on this issue.

Will assign you when we're sure what the string should be, I thought I knew, but now I am a little confused

**Comment by t3chguy** [comment]
I'd argue it should pivot based on whether you have spaces/communities enabled and say `Previous/Next recently visited room or space` in the former case.

**Comment by SimonBrandner** [comment]
> I'd argue it should pivot based on whether you have spaces/communities enabled and say `Previous/Next recently visited room or space` in the former case.

Sorry, I was trying to say that since the shortcut switches to the next/previous room no matter the space, the mention of spaces in the keybinding name confuses me. When I first read the shortcut name I wasn't very sure what it would do - would it switch between rooms, spaces or somehow both. I feel like if spaces weren't mentioned in the shortcut name it wouldn't be confusing

Maybe this is just me?

**Comment by t3chguy** [comment]
If you click on Space home/Explore space then it'll also navigate back/forward to that too @SimonBrandner

**Comment by SimonBrandner** [comment]
> If you click on Space home/Explore space then it'll also navigate back/forward to that too @SimonBrandner

Oh, right! :facepalm: I am wondering if we should use `space home` or something like that in the title to convey this better?

**Comment by aj-ya** [comment]
Hey! I was getting ready to work on this issue and if I'm not wrong, the string(s) should be changed to  `... recently visited room/space` right?
Also, the only files that need modifications are the ones changed in Issue: https://github.com/vector-im/element-web/pull/20595

**Comment by t3chguy** [comment]
Never touch the language files manually, just run the `i18n` script and it'll do everything for you.

**Comment by aj-ya** [comment]
Oh! Thanks for the heads up! So, I just have to edit just the 2 files then.
Edit: I changed those files and then ran the Perl script(`check_i18.pl`) and it just printed out the fraction of the strings translated, etc. but there were no changes in the files. How do I proceed further?

**Comment by SimonBrandner** [comment]
You should run `yarn i18n`

**Comment by luixxiul** [comment]
With [https://github.com/matrix-org/matrix-react-sdk/pull/7850](https://github.com/matrix-org/matrix-react-sdk/pull/7850/files#diff-454f7f431b8bcf5cfe7cdb0a66bc6f123dcf9617f67d7dce3b3d99bbb1fdad64R265-R266) handling of desktop-only shortcuts has been moved to the react-sdk.
