### ISSUE TITLE
Space panel scroll gradient only appears after scrolling

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20756]
### Steps to reproduce

1. Be in lots of spaces
2. Open the app
3. Note lack of gradient
4. Scroll
5. Note gradient appears
6. Scroll all the way to the top (similar to app start)
7. Note gradient is still present

#### What did you expect?

The gradient should be consistently shown.

This gradient:
![image](https://user-images.githubusercontent.com/1190097/151060321-c5ee9b02-db77-4168-a9e5-fa6e5f306373.png)

### Operating system

Windows 10

### Application version

Nightly (2022-01-25)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Are you seeing this on the breadcrumbs horizontal bar also?

**Comment by t3chguy** [comment]
Does not need design, the class is not being applied at first render and only onScroll
