### ISSUE TITLE
Spotlight search leaking [object Object] as mxid

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20763]
### Steps to reproduce

<img width="229" alt="Screenshot 2022-01-26 at 10 28 15" src="https://user-images.githubusercontent.com/1294269/151147035-d139701d-5c78-4f6d-96bc-969ffc4b5b6e.png">

### Outcome

Should show Cadair's mxid, not [object Object]

### Operating system

macOS 12.1 on M1

### Application version

nightly

### Will you send logs?

No

**Comment by t3chguy** [comment]
Does your `m.direct` `account_data` for that room say its with `[object Object]`?

**Comment by ara4n** [comment]
looks like it:

```
    "[object Object]": [
      "!aOrSMNhiKHkqulIqPGE:matrix.org",
      "!AnGSOXgCNPrAUPAZmbF:matrix.org",
      "!gAsekSJKgZIJIdedogo:westwork.org",
      "!QqzDoUYgMtOmYDYBMkV:matrix.org",
      "!RQTZZdlORjTpEZJZrFi:matrix.org"
    ],
```

(roomIDs anonymised)

**Comment by t3chguy** [comment]
Indeed, so this is https://github.com/vector-im/element-web/issues/7485

**Comment by robintown** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/7485
