### ISSUE TITLE
Hanging up a PiP'd jitsi call causes crash

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#20766]
### Steps to reproduce

1. In a room add a jitsi widget and join the conference
2. Navigate to a different room
3. Click the hangup button on the PiPed jitsi

#### What happened instead?

<img width="837" alt="Screenshot 2022-01-26 at 12 37 13" src="https://user-images.githubusercontent.com/3055605/151156713-538f352b-6de8-4495-be64-b73d298ba52a.png">

### URL for webapp

develop

### Application version

Element version: c6c1238cefc4-react-f7a3027e501a-js-8434f29c54ae Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Applies to 1:1 calls too
