### ISSUE TITLE
Unable to switch audio input while in a call

### ISSUE THREAD

**Issue by omame** [vector-im/element-web#20771]
### Steps to reproduce

1. Start a call having more than one microphone connected to the computer (built-in microphone counts as one).
2. Open the preferences and go to "voice & video".
3. Switch another input source.

#### What did you expect?
The call switches to using the selected audio input.

#### What happened instead?
The call is still using the audio input that was selected when the call started.

### Operating system

MacOS Monterey 12.1

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### How did you install the app?

Homebrew

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by omame** [comment]
Rageshake [here](https://github.com/matrix-org/element-web-rageshakes/issues/9832).

**Comment by omame** [comment]
I swear I looked for it and couldn't find it.

Thanks for the pointer! See you there.

**Comment by SimonBrandner** [comment]
> I swear I looked for it and couldn't find it.
> 
> Thanks for the pointer! See you there.

No problem!
