### ISSUE TITLE
"Sort by" option does not update after selecting a option when section is hidden

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#20776]
### Steps to reproduce

1. Fold a room section using the arrow.
2. Try changing the Sort by option

Here is a video showing this.
https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/ES79Nqlf36RIpD2OHviODWEB6cfKIVpAfb0YHgNjRsJh_g?e=CFbYXK

#### What did you expect?
UI to update
#### What happened instead?
did not.

### Operating system

Windows

### Browser information

Version 93.0.4577.63 (Official Build) (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.9.9 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
I have not been able to reproduce.
Can you confirm that the issue happens on app.element.io? The dialpad next to the filter input suggests you're running a fork?

**Comment by chagai95** [comment]
Sorry, the video is from a fork but I thought I could reproduce on app.element.io maybe I was experiencing this other issue which confused me:
https://github.com/vector-im/element-web/issues/19160

Anyway I think this issue was fixed already, our fork is based on 1.9.8 so we'll just update that.
