### ISSUE TITLE
Link to room without alias don't work between develop and Nightly

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20783]
### Steps to reproduce

1. Send `[Room](roomid)` link like `[Testing](!CMjQWAjoxImKwLBMzX:matrix.org)`
2. Send `[Room](#/room/!CMjQWAjoxImKwLBMzX:matrix.org)`

#### What did you expect?
Room is pillified and openable in both cases

#### What happened instead?
I can open the second link from develop, but Michael can't open it in Nightly

Source:
`"formatted_body": "<a href=\"#/room/!CMjQWAjoxImKwLBMzX:matrix.org\">Room</a>"`

### Browser information

Chromium 96.0.4664.45 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cfa97212f73e-react-074fec359b9f-js-7d2a5afa6dc9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by jryans** [comment]
Hmm, we've certainly changed a few things here lately... generally though, I wouldn't expect the second format there to work consistently, as it's effectively an Element Web specific URL format. Best to use an absolute link for sharing. Room header menu -> Copy room link is one way to get that.

Of course, we should have a way to autocomplete rooms without aliases, but that's a separate issue... 😄
