### ISSUE TITLE
Shrinking the composer when we have a voice recording shows an empty "more options" menu

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#20784]
### Steps to reproduce

1. Start recording a void message
2. Shrink the window to be narrow, so the composer goes into "narrow mode"
3. Notice that a "..." menu has appeared, with no options in it

![rec-2022-01-27_15 32 08](https://user-images.githubusercontent.com/76812/151390822-34b69939-3a59-4811-a52b-9f36e3cff21d.gif)

#### What did you expect?
I expected no menu to appear, since when we have a voice message, the compose has no buttons

#### What happened instead?
A menu appeared, but with no options in it
![image](https://user-images.githubusercontent.com/76812/151391540-142025de-82e1-4f25-8387-082c3330f44b.png)

### Application version

Element version: cfa97212f73e-react-074fec359b9f-js-7d2a5afa6dc9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7658

**Comment by andybalaam** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7658
