### ISSUE TITLE
ACL changes appear to be causing notifications in rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20788]
They shouldn't, much like membership events don't

**Comment by kittykat** [comment]
Experienced on:
Element version: cfa97212f73e-react-efa1667d7e9d-js-67d362fdd93d
Olm version: 3.2.8
Chromium 96.0.4664.110 (Official Build) Arch Linux (64-bit) on GNOME with Wayland

**Comment by ShadowJonathan** [comment]
Personally, I'd like for these notifications to (optionally) stay, as I think they're notification-worthy for administrators, at the very least.

**Comment by gsouquet** [comment]
@daniellekirkwood would be good to define what we're aiming for here

**Comment by SimonBrandner** [comment]
This is super annoying - does anyone mind raising it to `S-Major`

**Comment by turt2live** [comment]
@gsouquet which part of this is not actionable?

**Comment by turt2live** [comment]
@SimonBrandner workarounds do exist, though are obtuse and annoying to implement - I don't think it qualifies for Major.

**Comment by gsouquet** [comment]
@turt2live hmm I believe it's unclear whether we want that to be handled on Element or whether this would require some spec changes to make sure this does not notify ever

**Comment by turt2live** [comment]
"yes" :p 

We have code in Element which should help here, but also we probably want to spec a push rule.
