### ISSUE TITLE
After sending a custom sticker in a room, can't send any sticker after looking at another room.

### ISSUE THREAD

**Issue by JuliaVonKreutzer** [vector-im/element-web#20797]
### Steps to reproduce

1. Use Element Nightly Desktop and Maunium sticker picker (https://github.com/maunium/stickerpicker)
2. Send a custom sticker in any room
3. Click on another room
4. Try to send a sticker but clicking on it does nothing

#### What did you expect?
I expected to send a sticker by clicking on it
#### What happened instead?
Clicking on a sticker did nothing.

### Operating system

Windows 10

### Application version

Version de Element Nightly : 0.0.1-nightly.2022012801 Version de Olm : 3.2.8

### How did you install the app?

https://packages.riot.im/nightly/install/win32/x64/

### Homeserver

Synapse 1.50.1

### Will you send logs?

Yes

**Comment by tulir** [comment]
Happens with the scalar sticker picker on develop.element.io too (d731a2561933-react-afe6021c9a06-js-51f3fac87be4)
