### ISSUE TITLE
Scrolling in jump to date month/year pickers instantly teleports you

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20799]
### Steps to reproduce

1. Enable jump to date
2. Click on a date header
3. Click on the date picker
4. Click on the month/year picker
5. Scroll through the month/year lists

### Outcome

https://user-images.githubusercontent.com/48614497/151577445-de0dd015-db90-45b7-a063-36f00922a4d8.mp4

#### What did you expect?

To be able to scroll through the list and select a year.

#### What happened instead?

I was instantly teleported to 2021.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: cfa97212f73e-react-0c10385dd2e9-js-164320136391 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
This is specific to Firefox where it fires `change` events when the year/month controls are touched 😖, https://codepen.io/MadLittleMods/pen/WNXaqOK

With Chrome, it fires `input` events as the controls in the datepicker are touched and only fires a `change` when a selection is actually made in the datepicker.

Relevant code: [`src/components/views/messages/JumpToDatePicker.tsx#L42-L59`](https://github.com/matrix-org/matrix-react-sdk/blob/b02d5ecb97e475342f79383b18269ea93bd62620/src/components/views/messages/JumpToDatePicker.tsx#L42-L59)

**Comment by robintown** [comment]
A solution to this could be to wait until the user actually presses the 'Go' button before jumping.

**Comment by MadLittleMods** [comment]
@robintown We can simplify 👍

It was cool having the pick and go option but it doesn't work everywhere 😭
