### ISSUE TITLE
Jump to date calendar picker isn't visible when near the bottom of the screen

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20798]
### Steps to reproduce

1. Enable jump to date
2. Scroll back through a room until there is a date header at the very bottom of the timeline
3. Click on the date header
4. Click on the date field

### Outcome

![jump](https://user-images.githubusercontent.com/48614497/151575242-e2584628-c5d5-423e-967b-8c12ffc8e4c6.png)

#### What did you expect?

To be able to see and interact with the date picker

#### What happened instead?

The calendar is not visible

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: cfa97212f73e-react-0c10385dd2e9-js-164320136391 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
😢 It's a native `<input type="date">`. The browser should be smart about putting the dialog above when there is not enough room below.

Seems to work as expected in Chrome and Firefox on macOS and Windows 10 so it looks specific to Linux.


. | Chrome | Firefox
--- | --- | ---
macOS | <img width="1016" alt="" src="https://user-images.githubusercontent.com/558581/156080584-04239e3e-6f18-4729-a4d4-4152b6e6a8ab.png"> | <img width="797" alt="" src="https://user-images.githubusercontent.com/558581/156080591-e5c91a2f-4778-4e51-9943-923a5bb88d76.png">
Windows | ![](https://user-images.githubusercontent.com/558581/156083607-70a24fb5-da0c-4225-924f-560fc4388650.png) | ![](https://user-images.githubusercontent.com/558581/156083604-34ddf78e-2235-4aba-bf25-5ab1a6b23581.png)

**Comment by robintown** [comment]
Oh, so it's a Firefox bug then, fun

**Comment by robintown** [comment]
This seems to have been fixed upstream now
