### ISSUE TITLE
Jump to date picker lets you try to jump into the future

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20800]
### Steps to reproduce

1. Enable jump to date
2. Click on a date header
3. Select a future date

#### What did you expect?

Time travel :D

Or at least until there are plans to support time travel, the buttons for future dates in the calendar picker should be disabled.

#### What happened instead?

"Error: Unable to find event at that date."

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: cfa97212f73e-react-0c10385dd2e9-js-164320136391 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
We can set the [`max` property on the `<input type="date">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#max).

Relevant code: [`src/components/views/messages/JumpToDatePicker.tsx#L81-L93`](https://github.com/matrix-org/matrix-react-sdk/blob/b02d5ecb97e475342f79383b18269ea93bd62620/src/components/views/messages/JumpToDatePicker.tsx#L81-L93)

**Comment by SpookyDooky** [comment]
I would like to fix this issue.

**Comment by SimonBrandner** [comment]
I've assigned you to the issue, if you need any help/have any questions, be sure to visit https://matrix.to/#/#element-dev:matrix.org!

**Comment by Aman-Godara** [comment]
@robintown if it is possible can you please paste a small gif or something to use this **jump to date** feature. I am new to **element** platform, I went through some old issues/PR when this feature was added and thought that there is some command to access this feature. So I opened my element account on browser and typed **/jumptodate** command in the chat but this command wasn't available there. I tried the same on _develop.element.io_ but to no luck.

![image](https://user-images.githubusercontent.com/34789087/158010266-2753e138-9042-45b8-a2f3-823137f92894.png)

Can you show me where to find this jump to date feature? Thanks.

**Comment by robintown** [comment]
@Aman-Godara You need to use a homeserver that supports [MSC3030](https://github.com/matrix-org/matrix-spec-proposals/pull/3030), and then you should see an option in Labs labeled "Jump to date", which you must enable. After that, you can use the feature by clicking on the dropdown arrows that appear next to dates in the timeline, like so:

https://user-images.githubusercontent.com/48614497/151577445-de0dd015-db90-45b7-a063-36f00922a4d8.mp4

**Comment by robintown** [comment]
(to enable MSC3030 support on synapse, add something like the following to your config)

```
experimental_features:
  - msc3030_enabled: true
```

**Comment by ttheshreeyasingh** [comment]
Hi, can I be assigned this issue?

**Comment by Aman-Godara** [comment]
Who so ever works on this please read this comment for more info: https://github.com/matrix-org/matrix-react-sdk/pull/8013#discussion_r869862599
