### ISSUE TITLE
Element overwrites custom status_msg

### ISSUE THREAD

**Issue by deepbluev7** [vector-im/element-web#20809]
### Steps to reproduce

1. Set a custom status message in a different client (i.e. Nheko) or using curl
2. Open Element
3. Do something else for a while

#### What did you expect?

Element marks me as unavailable, but my status_msg is kept.

#### What happened instead?

Your status_msg will be unset by a call to ` /_matrix/client/v3/presence/{userId}/status`. Element doesn't seem to store the old status_msg and it doesn't provide it when setting the status, effectively deleting the old status_msg. And even worse, if you are active in a different client, Element will still unset the status_msg, even though you are still online!

### Operating system

Gentoo

### Browser information

Firefox, Chrome, etc. It doesn't matter

### URL for webapp

riot.neko.dev

### Application version

1.9.8 (and others, this has been an issue for 2 years)

### Homeserver

neko.dev, nheko.im

### Will you send logs?

No

**Comment by andybalaam** [comment]
We've had to revert the fix for this pending a Synapse update: https://github.com/matrix-org/matrix-react-sdk/pull/11365
