### ISSUE TITLE
Ignored user still triggers the channels unread indicator

### ISSUE THREAD

**Issue by steinex** [vector-im/element-web#20802]
### Steps to reproduce

1. Ignore user in a channel
2. Change channel
3. Channel gets bold in the sidebar like when a new message arrived
4. Switch back to channel and it has the same state as before (in reality the ignored user typed a message which is hidden)

#### What did you expect?
Channel should not get bold in the sidebar when the only action was by an ignored user.

#### What happened instead?
Channel got bold although the action was by an ignored user.

### Operating system

Linux

### Application version

1.9.9

### How did you install the app?

Flatpak

### Homeserver

Conduit -next (20006c91)

### Will you send logs?

No

**Comment by t3chguy** [comment]
Synapse should be filtering out everything from ignored users down /sync - so I'm thinking this is a bug where Synapse increments the notif counters regardless (yet doesn't send the event down /sync)

**Comment by t3chguy** [comment]
I cannot reproduce this anymore, but if you see this again I suggest opening an issue in https://github.com/matrix-org/synapse/
