### ISSUE TITLE
session rot after more than a half year of inactivity

### ISSUE THREAD

**Issue by neputevshina** [vector-im/element-web#20811]
### Steps to reproduce

1. don't login from a browser for more than half a year
2. see the message about rotten session

#### What did you expect?
i log in normally, prove another session, log out and forget that i have a windows installation on my pc

#### What happened instead?
i can't log in

### Operating system

windows 10

### Browser information

firefox 84.0

### URL for webapp

app.element.io

### Application version

latest?

### Will you send logs?

Yes

**Comment by dbkr** [comment]
From the debug logs, this session had been logged out on the server, eg. the device had been removed in settings / security & privacy, although there are also some indexeddb errors. So were you seeing an error message that prevented you from logging in again? I'm not sure I really understand what happened here.

**Comment by neputevshina** [comment]
hm, maybe it's me who accidentally logged out somehow. nvm, i checked my lastpass and found my recovery key. sorry for me being dumb.
