### ISSUE TITLE
Element Desktop window turns white after scrolling up in chat history

### ISSUE THREAD

**Issue by ginkel** [vector-im/element-web#20813]
### Steps to reproduce

1. Open an arbitrary DM chat session
2. Use the mouse wheel to scroll through the history
3. The Element Desktop window freezes for a moment and then turns white:

![image](https://user-images.githubusercontent.com/174129/151788032-a8e38e21-5487-4e0f-828d-9198f8f99fa5.png)

4. When the Dev Tools window is open during the crash, the following message is displayed:

![image](https://user-images.githubusercontent.com/174129/151787024-b03e8509-8c57-44cf-843c-bd7d0f082e4a.png)

No errors are displayed on the console. Running Element Desktop under `gdb` does not yield any core dump when the crash happens.

The error still occurs after starting from scratch with an empty config dir. The error also happens when (forward-)scrolling through the settings.

#### What did you expect?
I can scroll back in the chat's history.

#### What happened instead?
Element Desktop turns white.

### Operating system

Arch Linux w/ X.org and KDE Plasma

### Application version

1.9.9

### How did you install the app?

Arch package element-desktop

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is likely specific to the community maintained Arch package as there haven't been reports on the `deb`

**Comment by ginkel** [comment]
Seems this is cause by Electron: https://bugs.archlinux.org/task/73518

Updating right now. Will report back whether this is fixed.

**Comment by ginkel** [comment]
Updating `electron13` to the version w/o `-fstack-clash-protection` actually solved the problem. Sorry for the noise...
