### ISSUE TITLE
Toggle button doesn't switch the themes when light mode is the default mode. 

### ISSUE THREAD

**Issue by ankur12-1610** [vector-im/element-web#20816]
### Steps to reproduce

- Sign out with setting light mode
- Sign in and then switch the toggle button to dark mode.
-  Try to do it again, it won't switch.

#### What did you expect?
The toggle button should switch themes.
#### What happened instead?
The toggle button doesn't switch between the themes.

https://user-images.githubusercontent.com/76884959/151804496-d3673a4a-81e4-4a0b-b209-1d4e37559ce8.mp4

### Operating system

Linux

### Browser information

Chromium Version 97.0.4692.99 (Official Build) (64-bit)

### URL for webapp

localhost:8080

### Application version

Olm version: 3.2.8

### Will you send logs?

No

**Comment by dbkr** [comment]
Sounds like a dup of https://github.com/vector-im/element-web/issues/19514

**Comment by ankur12-1610** [comment]
Oh! :sweat_smile:, np :)
