### ISSUE TITLE
Error sending event to widget: Unknown or unsupported action: send_event

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#20815]
### Steps to reproduce

1. We use a spanner :wrench: widget to avoid working on the same system at once.
2. It sets a state event and posts a message every time someone takes or drops a spanner.

#### What did you expect?
No error

#### What happened instead?
A console error whenever I take or drop the spanner.

![Screenshot_2022-01-31_13-50-57](https://user-images.githubusercontent.com/10872136/151797553-33eba53a-d594-443f-ad5a-f00d3b9a6ddd.png)

### Operating system

Manjaro Linux

### Browser information

Firefox Developer 97

### URL for webapp

staging.element.io

### Application version

Element version: 1.9.10-rc.2, Olm version: 3.2.8

### Homeserver

vector.modular.im

### Will you send logs?

No

**Comment by jryans** [comment]
@jaller94 Can you share the source of the widget?

**Comment by jaller94** [comment]
The widget is: https://github.com/Half-Shot/matrix-spanner-widget

**Comment by jryans** [comment]
@jaller94 This appears to be an artefact of the current `matrix-widget-api` contract as [hinted](https://github.com/matrix-org/matrix-widget-api#usage-for-widgets) in the docs: it currently expects you to call `ev.preventDefault()` and send a reply for any event you process.

Personally, I find this to be a somewhat surprising API expectation, as it leads to extra error messages like this, even though the widget has actually processed the data anyway. I filed https://github.com/matrix-org/matrix-widget-api/issues/53 to discuss possibly changing that contract for the general case.

To resolve this for the spanner widget, either you can wait to see the outcome of that general API contract change, or the spanner widget could be altered to follow the current contract.

Either way, the changes wouldn't happen in Element Web directly, so I'll close this issue.
