### ISSUE TITLE
Spotlight should show unread & badge state

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20821]
#### What would you like to do?

The fact spotlight doesn't show unread/badge state is a regression over the old filter behaviour, and makes it hard to pick the right room.  I often have 4 similarly named rooms (Eng Mgt, Eng Managers, Core Eng Mgt or whatever) and the main way to identify which one i really want to read is going to be which one has the red badge (or the highest unread count etc).

#### Why would you like to do it?

To avoid spotlight, which is amazing in all other ways, be a regression over the old cmd-K filtering.

#### How would you like to achieve it?

Whang the unread/notif badge on the end  of each result (with a dot for unread rooms without a badge count)

**Comment by t3chguy** [comment]
Needs design, we can't reuse the narrow room list badge placement as the avatars in spotlight are too small

One random functional proposal:

![image](https://user-images.githubusercontent.com/2403652/152005392-6bc525ab-3bb1-4924-aad1-355d830efdd3.png)
