### ISSUE TITLE
Master password to block the messenger

### ISSUE THREAD

**Issue by AAndyProgram** [vector-im/element-web#20828]
### Your use case

Is it possible to add a lock button or key combination to lock the messenger and the lock timer (for example, to lock messenger in an hour if I do nothing)? It would be great if users could block the messenger and it could still work to get notifications etc. In addition, this feature provides a higher level of security for your chats. If I leave my workplace and forget to close the messenger, I can be sure that no one will open it. Also, no one can be able to read chats without a master password, if only the messenger is launched.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/3777
