### ISSUE TITLE
Shavian unicode text displays as emoji text (larger font) 

### ISSUE THREAD

**Issue by trosel** [vector-im/element-web#20824]
### Steps to reproduce

I wondered why [Shavian letters](https://en.wikipedia.org/wiki/Shavian_alphabet) are larger than Latin letters as seen below:

![image](https://user-images.githubusercontent.com/1299322/151879966-4e852114-87df-4aca-90e0-94480b717622.png)

**Note**: I am not complaining about the fact that the Shavian letters are larger, because I prefer them to be larger! But that should be fixed on the font level. The problem here is that each Shavian unicode character is being detected as an Emoji!

![image](https://user-images.githubusercontent.com/1299322/151879891-6e306b63-8ba6-434c-8c13-d623a04608b8.png)

The code that detects emojis seems to include the Shavian unicode block in it's detection: https://en.wikipedia.org/wiki/Shavian_(Unicode_block)

I have searched this repository for `mx_Emoji` and could not find anything. Maybe this is not the correct repository?

#### What did you expect?
Shavian text would be rendered as text

#### What happened instead?
Shavian text is rendered as emojis

### Operating system

Windows

### Browser information

Brave version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.10.0 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by trosel** [comment]
Update: I believe this is the code in the react sdk that is throwing a false positive for shavian characters: https://github.com/matrix-org/matrix-react-sdk/blob/fad65f958286ef312732ff23b03faa16d8dd2437/src/HtmlUtils.tsx#L93

**Comment by robintown** [comment]
Yep, it seems we need to use the slower but more rigorous emoji regex after all

**Comment by robintown** [comment]
(also, neat alphabet! :slightly_smiling_face:)
