### ISSUE TITLE
Broken group and 1on1 notifications

### ISSUE THREAD

**Issue by WGH-** [vector-im/element-web#2083]
So, somehow notifications (sound ones, favicon change, etc.) in my web Vector broke.

If I remember correctly, it happened after I disabled group chat notifications in my Android Vector client.

After that, I could no longer receive notifications in web Vector as well. 

My notification settings started to look like this:
![test](https://cloud.githubusercontent.com/assets/1099351/18232704/c0fde04c-72e6-11e6-9d88-20774668927a.png)

After fiddling with these settings (turning them on/off, etc.), that weird entry is gone. Somehow,  notifications in rooms like #matrix returned, but not in 1-vs-1 chats.

**Comment by WGH-** [comment]
As it turned out, per-room notification for my 1vs1 was set to "Highlight only". I don't remember setting it that way. I'll try to reproduce it, though.

**Comment by ara4n** [comment]
@WGH- what client did you set it to 'highlight only' on?

**Comment by WGH-** [comment]
I think I never did. I might have done it accidentally somehow.

**Comment by kittykat** [comment]
@WGH- It's been a while since this issue was filed and the app has changed significantly, do you still experience this issue?

**Comment by WGH-** [comment]
On December 27, 2021 7:24:56 PM GMT+03:00, Kat Gerasimova ***@***.***> wrote:
***@***.*** It's been a while since this issue was filed and the app has changed significantly, do you still experience this issue?
>

I don't recall any notification problems recently, so I think this issue is either no longer relevant, or it has been bogus all along.

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
