### ISSUE TITLE
Publishing alias requires it both be taken and not, becoming impossible

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#20833]
### Steps to reproduce

1. attempt to publish an alternate room alias

#### What did you expect?

Alternate alias should submit as-entered

#### What happened instead?

According to the synapse logs, Element is attempting to query for the alias with an extra "#" on the front, causing an error that leaves it unable to publish the alias.

![pic-selected-220201-0615-43](https://user-images.githubusercontent.com/41203525/151958856-94f1384c-e7d1-40d2-bdde-e786e11513d8.png)

![pic-selected-220201-0612-38](https://user-images.githubusercontent.com/41203525/151958886-d74fbdb5-f91a-48b6-9bdd-388a146e491e.png)

Synapse (1.50.2) log:
```
Feb 01 06:11:56 synapse[184312]: 2022-02-01 06:11:56,220 - root - 262 - WARNING - GET-236997 - Error retrieving alias
Feb 01 06:11:56 synapse[184312]: 2022-02-01 06:11:56,220 - synapse.http.server - 95 - INFO - GET-236997 - <XForwardedForRequest at 0x7fdb20704400 method='GET' uri='/_matrix/client/r0/directory/room/%23%23testingalias456%3Amatrix.org' clientproto='HTTP/1.0' site='8008'> SynapseError: 404 - Room alias ##testingalias456:matrix.org not found
Feb 01 06:11:56 synapse[184312]: 2022-02-01 06:11:56,224 - synapse.http.matrixfederationclient - 607 - INFO - GET-236998 - {GET-O-256879} [matrix.org] Got response headers: 404 Not Found

```

Attempting to exclude the "#" at the front doesn't work:
![pic-selected-220201-0612-54](https://user-images.githubusercontent.com/41203525/151959168-bd35d80b-957e-49fd-8a34-5e2c65a4a162.png)

### Operating system

Arch Linux

### Browser information

Firefox 96

### URL for webapp

develop.element.io

### Application version

Element version: d731a2561933-react-afe6021c9a06-js-51f3fac87be4 Olm version: 3.2.8

### Homeserver

private instance, but was able to replicate client-side error with matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The field has a `#` prefix on it - the `#` should not be entered

The red border you show in your issue when removing that is likely because that address doesn't yet point at your room, which is managed in the `Local Addresses` section below. You can only publish an address which already exists.

I think this issue is fundamentally https://github.com/vector-im/element-web/issues/13077

**Comment by BurnyBoi** [comment]
> The red border you show in your issue when removing that is likely because that address doesn't yet point at your room, 


That's not correct @t3chguy. The alias 100% was pointing to the room, and the Add button doesn't work when the # is excluded. This is preventing me from adding the alias entirely. This is a regression in Element. I know this was working correctly before.

**Comment by BurnyBoi** [comment]
@t3chguy I just tested this on 1.10.1 and the same behavior is still happening. excluding the "#" shows as red and clicking Add does nothing, and including the "#" produces the same error with the extra "#" at the front in the logs.

**Comment by t3chguy** [comment]
What error is the field saying? Keep it focused to see the error. You should *NOT* be including a `#` in that field given its already in the field's prefix

**Comment by BurnyBoi** [comment]
The UI error when I don't include the "#" is "This address had invalid server or is already in use." That being said, I logged in using develop.element.io rather than my own build and I was able to add the alias without the "#" as expected.

I'm currently building the develop branch of element-web from git. Does that currently include the fix mentioned in the latest release?

**Comment by t3chguy** [comment]
> Element version: 1.10.1-9-g0041ad723-dirty

Can you try on app.element.io instead?

**Comment by BurnyBoi** [comment]
It worked there as well. I just looked inside my node_modules and it looks like `yarn` still provided me 3.39.0 rather than 3.39.1, even on a fresh pull and run of `yarn`. That explains why I still don't have it. I guess I could either try to force it to pull the newer one or just wait until I get it naturally.
