### ISSUE TITLE
Default filename for 'save image as' is always image.png

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20838]
### Steps to reproduce

1. post a link to a gif such as https://media3.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif?cid=790b7611b5238203d4dfc621261917cf4acab0e609612f97&rid=giphy.gif&ct=g
2. wait for image preview
3. click on image to view gif in lightbox
4. right click and save

#### What did you expect?
defaults to `something.gif`

#### What happened instead?
defaults to `image.png`

### Operating system

arch

### Application version

Element Nightly version: 2022020101 Olm version: 3.2.8

### How did you install the app?

aur/element-desktop-nightly-bin

### Homeserver

synapse 1.51

### Will you send logs?

No

**Comment by dbkr** [comment]
I can't repro this - I get a gif file named, in this case, `2022-02-01_GPLorpFvLlahmacq.gif`. The source of the displayed image is synapse's download URL, ie. the original un-thumbnailed GIF, via the media repo.

**Comment by HarHarLinks** [comment]
> I can't repro this - I get a gif file named, in this case, `2022-02-01_GPLorpFvLlahmacq.gif`. The source of the displayed image is synapse's download URL, ie. the original un-thumbnailed GIF, via the media repo.

Have you tried the above link? I suspect it might be something about the URI not ending in `.gif`?

**Comment by dbkr** [comment]
Yep, that was with the link you provided

**Comment by HarHarLinks** [comment]
Choosing "copy link address" instead of "save image" yields this URL: `https://matrix.example.org/_matrix/media/r0/download/example.org/2022-02-01_iBnlzJewWOBknlCt` without `.gif` :thinking: 
When I download it anyway it is a proper gif... apart from the filename.
```
$ file /tmp/image.png
/tmp/image.png: GIF image data, version 89a, 350 x 263
```

Opening the same URL in my chromium-based browser and downloading it there does suggest the file name incl `.gif` ending as you said.

**Comment by dbkr** [comment]
Aha, so this is actually completely specific to the desktop app and is because we prompt for the filename before fetching the file (apart from obviously that the browser would already have fetched it to display it). In fact it just literally defaults to 'image.png'.
