### ISSUE TITLE
[Fosdem Instance] Jitsi widget isnt movable if switching rooms. Making reactions and replies impossible

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#20840]
At https://chat.fosdem.org the jitsi widget after switching rooms gets minimized to the lower right and therefore overlaps the action buttons.

![image](https://user-images.githubusercontent.com/1374914/152012858-8815738c-c4f8-4839-96bc-0755cc6b213d.png)

**Comment by kittykat** [comment]
@jaywink this is specifically in the chat.fosdem.org instance, medium priority compared to your other tasks

**Comment by jaywink** [comment]
So chat.fosdem.org was on 1.9.9 while this bug was logged, it's now on 1.10.1 - can you re-verify @MTRNord ? Dragging it around works for me at least.

**Comment by MTRNord** [comment]
@jaywink dragging works now :) Closing it as it is fixed.
