### ISSUE TITLE
Threads from another room appear in thread panel

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20850]
### Steps to reproduce

not sure in particular, just use some threads in some rooms

#### What did you expect?
![image](https://user-images.githubusercontent.com/2803622/152056409-e0861fee-d80e-4eda-81b0-ab6f7321d9bb.png)

#### What happened instead?
seeing threads from other rooms as well

### Operating system

arch

### Application version

Element Nightly version: 2022020101 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by gsouquet** [comment]
I've not really been able to reproduce that one.
The threads displayed in that list always seem to be scoped to the correct room for me. Regardless of whether I hit a homeserver that has the new sets of APIs or not.

Are there any more steps that lead you to encounter this issue?

**Comment by HarHarLinks** [comment]
I just opened a random DM, opened the threads panel. There are 5 Threads:

1. is actually from this room
2. is from another room (group, e2ee) that also includes the DM participant
3. is from this room
4. is from another DM (e2ee) that does not include the DM participant
5. is from https://matrix.to/#/#element-community-testing:matrix.org where I just demonstrated another threads bug

**Comment by thegcat** [comment]
(technically I'm on Element Desktop 1.10.1 on macOS 12, but my understanding is it's the same code at this point)

I also see a thread from room B when looking at the thread panel of room A, although the panel is set to "all thread for the current room".

The thread panel in room A shows 4 threads, the 3rd from top being from room B. The panel is also missing older threads from room A, though I'm not sure wether this is intended or not. I also just went to room B to check what the threads panel is showing there, and it showed the thread view (not the thread list) for the thread that is erroneously shown in the thread list from room A.

I just cache-busted said Element Desktop a few days ago (might be yesterday?), so this should be a problem that is reproducible on a "fresh" client? Seeing I had the panel with the erroneous thread open in room B, maybe the steps would be "open room B", "open a single thread view in room B", "switch to room A", "open thread list in room A"?
