### ISSUE TITLE
Make thread unread marker more obvious (in dark mode)

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20853]
#### What would you like to do?
With a mundane non-ping message you get a grey indicator dot on the threads button at the top right as well as on the relevant thread(s).

![image](https://user-images.githubusercontent.com/2803622/152060506-5beeb3f8-749e-4fb2-b192-891c0749b371.png)
![image](https://user-images.githubusercontent.com/2803622/152060037-f33efe31-8614-4932-abdd-8b208af9999f.png)
![image](https://user-images.githubusercontent.com/2803622/152060476-dca847c1-6d9a-47bd-8c6f-7b40e2b96797.png)

#### Why would you like to do it?
It's not obvious enough in dark mode. It does not even match the default *white* indicator in the space panel.

The Threads overview list suffers in particular because it is quite noisy in general: there are times and display names and avatars and reply counts. And then a small grey dot hidden beside one.

#### How would you like to achieve it?
More contrast, more size, possibly highlight the whole thread in a different way instead.

room list/space panel number: 
![image](https://user-images.githubusercontent.com/2803622/152060552-f38710fa-4d0a-435f-981c-ceb8d384af3d.png)

room list/space panel dot:
![image](https://user-images.githubusercontent.com/2803622/152060584-8bb43235-4ea9-40be-a2c0-ade1ad04c158.png)

I just had my friend help me repro this to take screenshots, and fully expecting to get the indicator I couldn't find the thread!
The indication should be on the left side where there is enough space (below avatar, see above), and we are used to read and look from left to right. This can even be so big as to fit a number.

### Additional context

#20852

**Comment by janogarcia** [comment]
Closing as this has been fixed in a recent PR.

**Comment by janogarcia** [comment]
<img width="1188" alt="Small dot (8px) on high contrast icon" src="https://user-images.githubusercontent.com/60790/162440073-46779998-d0f8-4cdb-87fa-62fad8b05a92.png">
