### ISSUE TITLE
Element pillifies @room even when in code block

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20851]
### Steps to reproduce

1. send <code>\`@room\`</code>

#### What did you expect?
`@room`

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/152057676-94180802-c693-4cea-a0dc-396feec56a79.png)

### Operating system

arch

### Application version

Element Nightly version: 2022020101 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9613
