### ISSUE TITLE
Invite link has two copy buttons

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20855]
### Steps to reproduce

1. Go to "Start a chat"
2. Hover over the copy button next to the invite link

### Outcome

![copy](https://user-images.githubusercontent.com/48614497/152069520-34997e72-e600-4fdd-ac95-e9587da6a9fc.png)

#### What did you expect?

There should only be a single copy button.

#### What happened instead?

A second copy button appears on hover.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 0041ad7230a6-react-bb03298e6dad-js-9c242a9ce6d9 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
There is a new component called `CopyableText` that should probably be used here
