### ISSUE TITLE
E2E unexpectedly disabled on direct message room, sloppy warnings

### ISSUE THREAD

**Issue by capocasa** [vector-im/element-web#20865]
### Steps to reproduce

1. Where are you starting? What can you see?

Chatted happily for a while in an direct message room with a friend. I used that room on browser and on my android phone. All sessoins cross-verified.

Suddenly, I started getting warnings about unencrypted outgoing messages in the browser, but not incoming ones. I got no warnings at all on the phone.

This raised in my mind the following security-related questions:

- Why did E2E for that room get disabled?
- Why can E2E be disabled for a private room at all?
- Why did I receive no warnings for incoming messages in the browser?
- Why did I receive no warnings at all in the android app?
- Why were the warnings sent after the fact- why did I not receive warning *before* sending a message that I was *about* to send an unencrypted message?

2. What do you click?

I performed normal messaging with my friend

3. More steps…

I checked the room information on the phone and it was marked unencrypted- I don't know why, my friend did not disable it.

More information in this investigatory reddit thread: https://www.reddit.com/r/elementchat/comments/sff90g/messages_selectively_marked_unencrypted_in_secure/

#### What did you expect?

I expected E2E to always be enabled in a private room on Element.

If E2E were to be disabled by technical error, I would expect a safeguard to warn me about this *before* I send messages, not *after*. I would further expect a safeguard for all clients (android phone too, not just web, didn't test ios or win/lin/osx desktop but expect it to work there too), not just in the web version. But I would mostly expect such an error to not happen.

Shortly, I would expect Element not to potentially land me in prison.

#### What happened instead?

Supposedly E2E encrypted messages messages were leaked to server in plain text without warning. They were harmless by chance, but this incident does not inspire confident in Element that it can keep a secret. I am very happy I am not in Minsk or Myanmar right now, or conspiring to whistleblow on powerful people in the United States.

Element could potentially send me to prison by insufficient safeguards against leaking messages, as well as an unknown presumed bug that disabled E2E for a room.

### Operating system

Linux

### Browser information

Firefox

### URL for webapp

app.element.io

### Application version

Latest

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by capocasa** [comment]
UPDATE

- Only messages sent with my android phone are marked as unencrypted in the browser.
- Only the phone shows the direct message room to be unencrypted in room options
- Messages sent with the browser are marked encrypted in the browser
- In the browser, the room is marked encrypted in room options.

**Comment by dbkr** [comment]
This sounds like android getting confused about the state of the room, which is being tracked in https://github.com/vector-im/element-android/issues/5068

**Comment by capocasa** [comment]
Thanks for triaging!!!

Hang on not so quick with the closing though, the broken room state is not all I reported.

I also reported that should a bug like this happen, there should be a safeguard against sending out unencrypted messages so easily- ensuring E2E would appear to me to be overly fragile for something so critical.

**Comment by t3chguy** [comment]
Web and desktop (which is what this repo is about) have such a safeguard, if a room was ever encrypted they will not allow unencrypted messages being sent from them

**Comment by dkasak** [comment]
> Why did I receive no warnings for incoming messages in the browser?

Were the incoming messages actually unencrypted?

**Comment by capocasa** [comment]
@dkasak Were the incoming messages actually unencrypted?

Good point, it is possible that the incoming messages were encrypted, while the outgoing messages were unencrypted.

Is there a way to confirm this in an additional way rather than using the icon?

**Comment by capocasa** [comment]
> Web and desktop (which is what this repo is about) have such a safeguard, if a room was ever encrypted they will not allow unencrypted messages being sent from them.

That is quite reassuring.

I would like to report to the right place that having such a safeguard must be required from all clients, as even a single weak link drags the security of the entire app ecosystem down. Might someone kindly point me to the right place to make such a report that is about coordinating between all clients?

**Comment by t3chguy** [comment]
> I would like to report to the right place that having such a safeguard must be required from all clients, as even a single weak link drags the security of the entire app ecosystem down. Might someone kindly point me to the right place to make such a report that is about coordinating between all clients?

I suggest https://github.com/matrix-org/matrix-doc/ so that its added as a must in the spec

**Comment by capocasa** [comment]
@t3chguy Sounds perfect, will d

**Comment by dkasak** [comment]
Complementing spec changes, there is also https://github.com/vector-im/element-meta/issues/69 where we are doing gap analysis for handling of misconfigured encryption across all Element clients. I just added [a note](https://github.com/vector-im/element-meta/issues/69#issuecomment-1027986571) to also handle the case of disappearing state and redacted events.

**Comment by dkasak** [comment]
> Good point, it is possible that the incoming messages were encrypted, while the outgoing messages were unencrypted.
>
> Is there a way to confirm this in an additional way rather than using the icon?

@capocasa: On Element Android you can long-press the message. If it is encrypted, it should have both `View Source` and `View Decrypted Source`. Clicking on `View Source` should reveal a `ciphertext` field inside the `content` dictionary. If it is like described, the message is encrypted. On Element Web/Desktop you can access the same thing from the `...` context menu of a message, then clicking on `View Source`.

**Comment by capocasa** [comment]
Thank you, @dkasak @t3chguy @dbkr for your efforts- I feel really passionate about element because it's so open and flexible and useful in so many different ways.

I use it to talk with my 80 year old dad who lives too far away to visit him often. He uses a computer, but not a smartphone. Thanks to element he can see his grandkids on video calls and pictures, he can reach out to me anytime he likes, and we can have real conversations without self-censorship- no "don't talk about this on the phone" or weird "coincidental" relevant ads. All in his comfortable environment. I can safely say I'm just so much more connected with him since I set him up with element.

So I wanted to let you know that you guys are on the right track and really making a difference by working on something that's as open and flexible as element is. Thank you!!!

**Comment by capocasa** [comment]
> @capocasa: `View Source`.

Confirm that the messages marked unencrypted were unencrypted, and the messages not marked unencrypted were not unencrypted. So there is no encrypted-marking display bug.
