### ISSUE TITLE
Multiple issues after client restart

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#20862]
### Steps to reproduce

1. Reload app from one of the develop builds on 02/02 to develop as of now (10:00 03/02)

Multiple reports of this have come in now, some reloading from yesterday's nightly build and some reloading develop. I saw it when restarting nightly this morning.

Clear cache & reload fixes it (which technically is a workaround, which would make this 'minor', but I'm going to apply common sense here and make it critical)

### Outcome

 * Many rooms have lost their names (shown as 'empty room')
 * Often directed to old versions of rooms first, and then have to click through manually to their newest version
 * Room list is missing message previews until I switch to the room
 * Receiving notifications for strange rooms that don't usually notify me

### Will you send logs?

No

**Comment by jryans** [comment]
I believe [this list of commits](https://github.com/matrix-org/matrix-react-sdk/compare/82f3888cee298118d60a490a3e1e50e19939fd5b...fce19d763a4dba73f71f8d5a344922f975ee292f) has all the new things I applied this morning when the issues started, though I am not 100% certain.

**Comment by dbkr** [comment]
Thanks. I got the bug with the nightly build which finished at 8:47: before any of the 3 commits today, so that rules out those three.

**Comment by jryans** [comment]
...though after scanning those changes, I can't see how they could trigger anything like these issue... 😰

**Comment by jryans** [comment]
Given the areas affected, I would have expected JS SDK changes, but I do not recall seeing any in the changelog before updating...

**Comment by jryans** [comment]
Using `/devtools` to try viewing room state makes it clear that state events seem to just be... missing from the room model.

**Comment by jryans** [comment]
I do notice that the IndexedDB store worker appears to startup twice, which doesn’t seem to happen on app.

**Comment by jryans** [comment]
The `sync` data in IndexedDB for the affected session is extremely minimal: it only seems to have some read receipts... perhaps 2 copies of the store logic are racing?

**Comment by jryans** [comment]
I'm only noticing duplicate runs of the store worker in my main Firefox session, though some are affected on the desktop build as well.

**Comment by jryans** [comment]
...and now the worker only starts up once. 😵

**Comment by jryans** [comment]
Well, I've run out of theories to investigate, so I suppose I'll clear cache now.

**Comment by turt2live** [comment]
Fwiw, I haven't yet checked nightly or web, but mobile (android) is suddenly using default naming on a handful of rooms and also lost their avatar. This might be a server issue.

**Comment by t3chguy** [comment]
`processThreadEvents` can throw if there's no connection/any server failure and will explode the `syncFromCache` method causing the `Error processing cached sync` log line

**Comment by t3chguy** [comment]
I'm also not sure how I feel about restoring a cached sync needing to hit any Matrix APIs at all

**Comment by dbkr** [comment]
ah, I found it making calls to /members to get room members for encrypted rooms, but those were all caught sensibly. Threads might do it though...

and yeah, shudder at things making API calls wile processing a cached sync :/

**Comment by dbkr** [comment]
Right, successfully reproed by:
 1. sending an event
 2. sending 50 messages in that room to push that event out of the cached sync window
 3. making a thread from the first event
 4. waiting long enough for the client to save a cached sync response
 5. blocking the `/event/` API in chrome dev tools
 6. reloading

It's https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/room.ts#L1375 which makes an API call but doesn't catch errors
