### ISSUE TITLE
Formatting bar doesn't work in GNOME Web (Epiphany)

### ISSUE THREAD

**Issue by smithfred** [vector-im/element-web#20868]
### Steps to reproduce

1. Type text in the message box and select.
2. Click any formatting button on the formatting bar.

#### What did you expect?

Formatting is applied.

#### What happened instead?

Text is deselected and cursor moves to the beginning of the line, without any formatting applied.

#### Additional info

* No error messages logged in browser console.
* GNOME Web is WebKit based; 40.3 uses WebKitGTK 2.34.1.

### Operating system

Linux

### Browser information

GNOME Web (Epiphany) 40.3

### URL for webapp

app.element.io

### Application version

Element 1.10.1, Olm 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
That is not a supported environment as per https://github.com/vector-im/element-web#supported-environments

**Comment by t3chguy** [comment]
Can confirm it affects Safari

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/2ee732b84d348652b2942f346dbf51b76ba474b8
