### ISSUE TITLE
Public space shared link redirect to matrix.to instead of internal matrix server

### ISSUE THREAD

**Issue by n4rkip0d** [vector-im/element-web#20860]
### Steps to reproduce

1. Where are you starting? What can you see?

I create a public space and want to share it with all the organization

2. What do you click?

Invite people, Link

3. More steps…

Paste the link redirect to matrix.to with space addresse

#### What did you expect?

Redirect to my internal matrix server

#### What happened instead?
It use matrix.to and try to redirect but can not find as we do not open port
![image](https://user-images.githubusercontent.com/68989865/152134326-26497fcc-6ec9-46c8-bedf-1430c7f3d96a.png)

Is it possible to change the default link ?

### Operating system

Windows 10

### Browser information

Google Chrome 97.0.4692.99

### URL for webapp

Element 1.9.8

### Application version

version: 1.9.8 Olm version: 3.2.8

### Homeserver

Synapse 1.49.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
You should configure your Element to not issue matrix.to links

https://github.com/vector-im/element-web/blob/develop/docs/config.md `permalinkPrefix`

**Comment by n4rkip0d** [comment]
Thank you, it works like a charm !

I should have think about this before creating the ticket as I already use some custom features of Element.
