### ISSUE TITLE
[FOSDEM instance] The key dialog crashes element-web if ignored

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#20878]
![image](https://user-images.githubusercontent.com/1374914/152205509-ef836e0b-c7e8-4f14-a8d0-ef67503ebec1.png)

On Fosdem instance https://chat.fosdem.org the dialog cant be ignore -> Crash to login, on accepting the dialog overlaps, on relogin it goes into key recovery mode.

**Comment by MTRNord** [comment]
Rageshake was send

**Comment by MTRNord** [comment]
This pops up on a new account when accepting widget permissions.

**Comment by dbkr** [comment]
I'm struggling to understand what's happening here. What's a "crash to login"? What overlaps what? If you could use the template and fill in exact repro steps, that would really help.

**Comment by MTRNord** [comment]
> I'm struggling to understand what's happening here. What's a "crash to login"? What overlaps what? If you could use the template and fill in exact repro steps, that would really help.

Sorry I try to explain it in more detail:

1. I had a fresh fosdem account
2. I then joined a speakers room
3. I got the usual "please accept these widget permissions" dialog
While this came up the "You will lose your keys" dialog came up prompting me to either setup key backup or saying that I dont want the keys

From here I played both scenarios:

4a. I said "I dont want my keys"

Element-web brought me back to the login screen without warning and I had to log in again

While logging in, I got a dialog telling me the keys are corrupted,

5a. I ignored it.
6a. I tried to accept the widget permissions again and land at step 3.

Then I tried the other button to setup the key backup.

4b. The keybackup setup opens behind the "You will lose your keys" dialog.
5b. Closing the "You will lose your keys" dialog caused another "crash" to the login screen and I had to log in again
6b. I tried key backup again and then tried to close that one and same result.

After another page reload, I eventually was able to accept the widget and bypass the keys ones.

Also note that I think in the meantime a newer version was deployed, and I am not sure if this was fixed due to the update or not.

**Comment by turt2live** [comment]
I'm not seeing any code path other than a log out here. Widgets can't issue that, and it requires the user to click on the sign out button.

It's possible a browser extension or app on the OS was interfering with clicks somehow, however as far as I can tell from the logs and code at the time it looks like somehow the logout button was clicked, hence warning, hence "crash" to login after dismissing the dialog.
