### ISSUE TITLE
sso_redirect_options are not applicated

### ISSUE THREAD

**Issue by ThomasAppDev** [vector-im/element-web#20876]
### Steps to reproduce

We have a basic Element-Web Installation with authentication over openID. Everything works, accept we cannot redirect directly to the sso login. Settings done in config.json:
"sso_redirect_options": {
        "immediate": true,
        "on_welcome_page": true
    },

#### What did you expect?
If I surf to any website of Element-web I will be redirect to the login of our SSO provider.

#### What happened instead?
I got the usual Element Web-Websites (Welcome-Page and SSO Login Page).

### Application version

1.7.15

### Will you send logs?

No

**Comment by robintown** [comment]
Version 1.7.15 is over a year old, does the issue still occur in recent versions?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/commit/bc32f05fcbfb2f6c2219d3ad840ef20ca1749177 is only a handful of months old so definitely won't work in a 14 month old release.
