### ISSUE TITLE
"My threads" does not display any threads

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#20877]
### Steps to reproduce

Be in a room in which I've replied to threads. Go to the threads list and and show: my threads

#### What did you expect?

To see threads I've participated in

#### What happened instead?

<img width="513" alt="Screenshot 2022-02-02 at 17 10 56" src="https://user-images.githubusercontent.com/57377/152202797-045971a9-dcfc-4f19-8608-289ad06a89d2.png">

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Element version: 6bc7036dc824-react-75b03ca101a3-js-cf0ccaf93d32 Olm version: 3.2.8

### Homeserver

threads-dev.lab.element.dev

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
also #20850
