### ISSUE TITLE
Opening room list category locks the UI

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20884]
### Steps to reproduce

1.  Opening a collapsed tag in the room list

#### What did you expect?

For this to feel seemless	

#### What happened instead?

Some folks, especially on Web (Electron seems to be less severely affected) experience very low refresh rate

#### Debugging info

<img width="929" alt="Screen Shot 2022-02-03 at 09 00 54" src="https://user-images.githubusercontent.com/769871/152312123-fa01a776-d827-44de-b898-98f495e5bc41.png">

<img width="438" alt="Screen Shot 2022-02-03 at 09 01 48" src="https://user-images.githubusercontent.com/769871/152312119-07a0ff3c-85de-4d4a-abfb-a20e2d222b3f.png">

It can trace that back to `Tooltip.tsx#updatePosition` that seems to trigger a relayout way more often that it should
Can share the Chrome performance recording privately

### Operating system

all

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Element Nightly version: 2022020201

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
@gsouquet How is this feeling for you now that https://github.com/matrix-org/matrix-react-sdk/pull/7939 is merged (on `develop`)? That PR optimizes the Tooltips which were causing the `updatePosition` calls in the performance profile from the issue description here.

**Comment by robintown** [comment]
Assuming that the above PR has indeed fixed this due to lack of response
