### ISSUE TITLE
Add necessary advertising for search experiment beta 

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20886]
We want to show the experiment in labs as a beta option in the same way we previously did for spaces.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1587166/152314598-a2cebae5-ddb0-4a2b-a70e-d50d8e721f0e.png">

**Comment by matthijskooijman** [comment]
Maybe this is the wrong place to ask, but is this "search beta" currently the *only* thing that should be displayed under Labs? I was looking to enable threading and some other things documented at https://github.com/vector-im/element-web/blob/develop/docs/labs.md, but I only get the search beta advertising shown in the screenshot above, without a way to access an other lab features?

**Comment by t3chguy** [comment]
> but is this "search beta" currently the only thing that should be displayed under Labs?

Depends on if your config.json has showLabsSettings on or off. https://github.com/vector-im/element-web/blob/develop/docs/config.md

**Comment by matthijskooijman** [comment]
I was talking about the default instance, which has them disabled indeed: https://app.element.io/config.json, the dev build does have them enabled: https://develop.element.io/config.json and shown in the UI.

Thanks for solving my confusion!
