### ISSUE TITLE
Can't create polls

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20882]
### Steps to reproduce

1. Click on the 'More options' button in the composer
2. Select 'Poll'

#### What did you expect?

The create poll dialog should appear.

#### What happened instead?

Nothing, except an error in the console.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 6bc7036dc824-react-f0446a23d5dc-js-6bf8142ff631 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Nothing, except an error in the console.

I'm not seeing this error in your logs
