### ISSUE TITLE
Element should leave us the choice of collapsing composer buttons or not, or which buttons should be collapsed or not.

### ISSUE THREAD

**Issue by JuliaVonKreutzer** [vector-im/element-web#20887]
#### What would you like to do?
Since this PR (https://github.com/matrix-org/matrix-react-sdk/pull/7678), Element nightly/develop collapses buttons. I would like to be able to choose if I want them to collapse or not, or to be able to choose which buttons collapse. I guess the easiest is that we could have the choice of having buttons collapse or not, since I'm fine with the current Element button display.

#### Why would you like to do it?
The sticker button is collapsed behind a menu on Element Nightly/Develop, which is very annoying to most of my friends and me, because we are ***huge*** custom stickers users. It's basically the only button I ever use on Desktop/Web. And I feel like (custom) stickers can be a huge appeal to some users, mainly from gaming/anime community. 

#### How would you like to achieve it?
We could have the option in the settings.

### Additional context

I use Element Night/Develop desktop and Element stable on daily basis.

**Comment by HarHarLinks** [comment]
Full customizability of which options are directly accessible or hidden in the `...` menu would be great. I don't need the :paperclip: that often and you can drag & drop files anyway. I need the emoji so-so as `: ` shortcodes are convenient... if you know the name. I use stickers frequently, and some people might use voice messages.

**Comment by salixor** [comment]
In Preferences > Composer, there is an option to "Show stickers button", which is a weird in-between considering the new behavior of collapsing buttons even on wide layouts. Why would we only be able to hide one button and not the others ?

It feels like we should be able to show / hide buttons we don't care about (which increases the amount of options as the number of buttons increases).

Or this option should be replaced, to enable / disable collapsing on wide layouts (the number of options stays the same).

**Comment by gaelledel** [comment]
Hi thanks all for your comments! We were waiting to hear more feedback from you guys before acting. We will take this into consideration for iterating.

**Comment by JuliaVonKreutzer** [comment]
It looks good to me. Thanks for the work!

**Comment by Destroyer** [comment]
as i commented in https://github.com/matrix-org/matrix-react-sdk/pull/7678

> is it possible to pin a button somehow? there's no point for me in using emoji picker but sticker picker hidden behind dots is quite annoying


I would add - why is this such a big deal? why hiding these options at all? If you wanna make sure the text gets enough space, they could get hidden once you start typing, but if it's a plain empty box - show all the options without me having to do an extra click for no reason 
thank you

**Comment by gaelledel** [comment]
FYI: We are monitoring user feedback on this issue and will be re assessing this only if we gain more significant data on the subject. User feedback gathered so far suggests this is low impact for the majority of users using Element.

**Comment by Destroyer** [comment]
maybe because people gave up on this stuff long time ago... they think they can't change anything anyways, why bother

also care to explain how clicking twice is better than clicking once?

**Comment by sinistergamer3333** [comment]
> FYI: We are monitoring user feedback on this issue and will be re assessing this only if we gain more significant data on the subject. User feedback gathered so far suggests this is low impact for the majority of users using Element.

FYI: This is literally the worst update I've ever seen pushed to Element. Every single person in my private group agrees, but they thought the devs would surely revert such a silly decision and therefore didn't came to come out and comment.

**Comment by andybalaam** [comment]
Thank you for creating this issue, and for giving your feedback on this change. It's really difficult to balance feedback from different people on something like this. Often, we are listening to specific irritations from current users, and trying to balance them against our goals, which often affect future users, who don't yet have a voice.

The design team wanted a simpler look, which they hope will help people who are new to the app to become familiar with it, and they are standing by that decision.

Meanwhile, we need to avoid adding too many configuration options to Element - there are already far too many, so we don't want to make this into a config option.

So we're going to stick with this change, and not make the complexity problem even worse by adding a config option.

One personal thought: would a keyboard shortcut to open the stickers box help?

**Comment by JuliaVonKreutzer** [comment]
Hello, 

A keyboard shortcut would be great yeah !

Although, as pointed out by @salixor : 

> In Preferences > Composer, there is an option to "Show stickers button", which is a weird in-between considering the new behavior of collapsing buttons even on wide layouts. Why would we only be able to hide one button and not the others ?

Why not just replace that ?

**Comment by Destroyer** [comment]
> would a keyboard shortcut to open the stickers box help

it's better but not by much, since you have to take your hands off keyboard to add a sticker, you still have to reach for a mouse


>    In Preferences > Composer, there is an option to "Show stickers button", which is a weird in-between considering the new behavior of collapsing buttons even on wide layouts. Why would we only be able to hide one button and not the others ?

that'd be better


> The design team wanted a simpler look

if i wanted a simpler look i'd look for MS teams, signal or telegram depending on my needs, those apps are much more bare bones
The reason I chose element is because I think offering people choice is a good thing. I also hope this design decision doesn't ruin the app in long term and things like date picker to go to a particular part of chat history, more advanced search (so you can search particular person or date range) or file picker that you can actually filter are things that I hope will be improved and not declined for "simplicity reasons"
That'd be sad

**Comment by andybalaam** [comment]
> A keyboard shortcut would be great yeah !

https://github.com/matrix-org/matrix-react-sdk/pull/7985 will help a little then, at least for some people.

**Comment by HarHarLinks** [comment]
> we need to avoid adding too many configuration options to Element - there are already far too many

but there is place for this? https://github.com/matrix-org/matrix-react-sdk/pull/6711

yeah sorry, not buying it.

**Comment by andybalaam** [comment]
The latest code allows you to press Ctrl+; to open/close the Stickers box. This will be included in the release towards the end of March. I hope it eases the pain for some of the people commenting here.

**Comment by ledangtrung** [comment]
> as i commented in [matrix-org/matrix-react-sdk#7678](https://github.com/matrix-org/matrix-react-sdk/pull/7678)
> 
> > is it possible to pin a button somehow? there's no point for me in using emoji picker but sticker picker hidden behind dots is quite annoying
> 
> I would add - why is this such a big deal? why hiding these options at all? **If you wanna make sure the text gets enough space, they could get hidden once you start typing, but if it's a plain empty box - show all the options without me having to do an extra click for no reason thank you**

This is a higly valid point. I always hate that I have to do many many clicks just to send a picture.

**Comment by eTomte** [comment]
Add me to the list of people who thinks that it's annoying to have these items collapsed behind a menu when they could be visible.  I use voice messages every day, I have plenty of screen real estate and I'd love to have a user configurable option to display all of the items I can choose from. :)
