### ISSUE TITLE
Extra space (gap) above messages

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#20896]
### Steps to reproduce

1. Open or create a thread
1. Send many long replies that will wrap over multiple lines
1. Notice the gap above the first message

It looks like the extra space is caused by `<ol class="mx_RoomView_MessageList" aria-live="polite" style="height: 2000px;">`

![chrome_2022-02-03_12-09-41](https://user-images.githubusercontent.com/558581/152403018-eb308e11-3983-4464-9fef-260e77c69ed4.png)

#### What did you expect?

No extra random space as replies come in (space grows as more replies come in)

#### What happened instead?

Extra space (gap) above first message)

### Operating system

Windows 10

### Application version

Element version: 64242a004eb7-react-78e78292cb62-js-b07457726bf5 Olm version: 3.2.8

### How did you install the app?

https://develop.element.io/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
That gap is part of the pagination mechanism in ScrollPanel, removing it makes very bad things happen (never ending backpagination), making it smaller should be sane though, but it was made 400px seemingly quite intentionally https://github.com/matrix-org/matrix-react-sdk/commit/86c13b97ce1bcff69470a8f70bf0f86b8b4b000f

**Comment by t3chguy** [comment]
The list is effectively split into pages of that size and rounded up

**Comment by t3chguy** [comment]
Not specific to thread panel nor to multi line messages

**Comment by t3chguy** [comment]
The comment around this is

> // _updateHeight makes the height a ceiled multiple of this so we
// don't have to update the height too often. It also allows the user
// to scroll past the pagination spinner a bit so they don't feel blocked so
// much while the content loads.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8392
