### ISSUE TITLE
No way to get Space internal room ID without being admin (as settings is not visible)

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#20890]
### Steps to reproduce

I want to get the internal room ID of a space. Without access to the space settings, it's not possible.

#### What did you expect?

To see room ID for any space I'm member of from the UI.

#### What happened instead?

I cannot.

### Application version

Element Nightly version: 2022020301 Olm version: 3.2.8

### How did you install the app?

Ubuntu, official repo

### Will you send logs?

No

**Comment by t3chguy** [comment]
Tracked in https://github.com/vector-im/element-web/issues/17399
