### ISSUE TITLE
dkasak getting UISIs from users on element.io and vector.modular.im

### ISSUE THREAD

**Issue by deniseal** [vector-im/element-web#20899]
### Steps to reproduce

Nothing to reproduce on my side, just submitting logs

#### What did you expect?

For Denis to be able to read our messages.

#### What happened instead?

UISI

### Operating system

macOS

### Application version

1.10.1

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by dkasak** [comment]
Seems to have been a transitory connectivity issue from EMS towards my homeserver. Resolved on its own.
