### ISSUE TITLE
New composer "more options" dialogue invisibly extends farther right

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20898]
### Steps to reproduce

1. press Mod4 (Windows key)

#### What did you expect?
nothing

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/152408502-0e20a6b1-991b-4707-bc3c-c7c8a0b1fc17.png)

### Operating system

arch

### Application version

Element Nightly version: 2022020301 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
> the wrong expectation

maybe, but the template asked what I personally expect. Apart from personally not needing it or having learned how to use it, I would expect it on <kbd>Alt</kbd> which makes the other keyboard navigable shortcuts pop up instead of what seems to be the <kbd>Mod4</kbd> which to my knowledge is usually the OS/wm shortcut key. Element as an app (potentially within another app, the browser) is the polar opposite of that expectation. But again that may be some standardized accessibility thing I'm unaware of.

**Comment by t3chguy** [comment]
So the issue you want is https://github.com/vector-im/element-web/issues/19889 - treating this issue as the button being too wide.

**Comment by HarHarLinks** [comment]
> So the issue you want is https://github.com/vector-im/element-web/issues/19889

not really, but thanks for the pointer

> treating this issue as the button being too wide.

my original intention was the highlight being too wide, now that i know it's the actual button that is my intention. i'll try to improve making my intention unmistakable in future reports.

**Comment by t3chguy** [comment]
Thanks!
