### ISSUE TITLE
Layout shift on expanded space sidebar hover

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#20906]
### Steps to reproduce

https://user-images.githubusercontent.com/769871/152504020-39b4adc5-dc36-4501-92ba-28ff0c5ca645.mov

#### What did you expect?

No layout shift

### Operating system

macOs

### URL for webapp

Element Nightly

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19891
