### ISSUE TITLE
Failure to enable encrypted message indexing

### ISSUE THREAD

**Issue by Kitanit** [vector-im/element-web#20907]
### Steps to reproduce

When I install element on my PC cleanly and try to index encrypted messages an error (screenshot), when I press reset, it just loads endlessly until it times out

![image](https://user-images.githubusercontent.com/65107731/152505489-2a36101c-7b36-4f1d-b258-efa5eeb1f30e.png)
![image](https://user-images.githubusercontent.com/65107731/152505708-54a47cb8-cbf7-494e-aa0b-1a9396289e76.png)

### Outcome

It used to work but on a different server, I can send you the full server settings if you need
![image](https://user-images.githubusercontent.com/65107731/152506482-93c5f46b-443c-44e8-922e-d6ec284a2a0b.png)

### Operating system

Linux Mine

### Application version

версия Element: 1.10.1 Версия Olm: 3.2.8

### How did you install the app?

https://element.io/get-started and apt

### Homeserver

Synapse docker 1.51.0

### Will you send logs?

Yes

**Comment by dbkr** [comment]
dup of https://github.com/vector-im/element-web/issues/19358
