### ISSUE TITLE
Leaving a room while one of its widgets has set `setAlwaysOnScreen(true)` makes the widget linger invisibly

### ISSUE THREAD

**Issue by squahtx** [vector-im/element-web#20901]
### Steps to reproduce

Reproducible with the FOSDEM 2022 talk widgets.

1. Join a FOSDEM 2022 talk room, eg. `#talk-13559:fosdem.org`
2. Join the Jitsi call in the widget. This calls `widgetApi.setAlwaysOnScreen(true)`.
3. Switch to another room. The Jitsi widget now appears in a small picture-in-picture overlay.
4. Leave the talk room. The picture-in-picture overlay disappears, but the Jitsi call in the widget is still running.
5. Visiting the room under the Historical section shows the Jitsi widget still running.

#### What did you expect?
Either the picture-in-picture overlay should remain after leaving the room, or the widget should be destroyed.

#### What happened instead?
The widget remained running in the background.

### Operating system

Windows

### Browser information

Chrome 98.0.4758.82

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-29cf22a5212c-js-b07457726bf5 Olm version: 3.2.8

### Homeserver

N/A

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Either the picture-in-picture overlay should remain after leaving the room, or the widget should be destroyed.

@vector-im/product which of these is preferable?

**Comment by jakewb-b** [comment]
I would say the widget should be destroyed if you've left the room.

**Comment by t3chguy** [comment]
@jakewb-b what about if you're looking at the room when you leave it, you'd probably also want to leave the call?

**Comment by jakewb-b** [comment]
@t3chguy - yes, that's what I'd expect
