### ISSUE TITLE
Composer buttons are visible even if you don't have send permissions

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#20903]
### Steps to reproduce

1. Open a room where you have no permission to send messages
2. Look at the composer

#### What did you expect?

The composer buttons should not be visible.

#### What happened instead?

The composer buttons, such as emoji, attachments, voice messages, etc. are visible despite not being able to use them for anything. Attempting to use them leads to a variety of error states.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-29cf22a5212c-js-b07457726bf5 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

No

**Comment by gsouquet** [comment]
@robintown is this a regression or are you suggesting to introduce this new behaviour.
I can not remember how this was supposed to work

**Comment by SimonBrandner** [comment]
I am pretty sure this is a regression since the recent composer rework
