### ISSUE TITLE
Implement improved rendering for threads in the main timeline

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#20908]
**Changelog**

Root messages should form a standalone group with their respective thread summaries.

This way, we establish a clear relationship between the thread summary and the root message it belongs to. Failure to do it results in an ambiguous relationship that only gets worse when message bubbles are enabled.

**Source**

→ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3085%3A306074

**Snapshot**

![Threads – Figma](https://user-images.githubusercontent.com/60790/165067196-553f77b2-e93e-450c-97e4-e75242418488.png)

**Comment by janogarcia** [comment]
I've updated the issue description and mockup for better clarity on what the expected rendering should be.

@novocaine This issue is currently assigned to Germain. I guess we should either unassign or reassign it. @robintown took the lead on implementing the current behavior, which is already quite close to the expected one.

**Comment by t3chguy** [comment]
@janogarcia I am failing to see the difference between the Figma and existing implementation

![image](https://user-images.githubusercontent.com/2403652/165079148-8b9dcd34-1957-4a24-a947-f8ca76e593bd.png)

Could you please point out what you need changing?

Thanks

**Comment by janogarcia** [comment]
@t3chguy Sure, in the example below the threads (`third` root messages in the group) shouldn't be grouped with the messages `first` and `second`. That is, make sure the threads are always rendered in standalone groups. Does that make sense?

![Element  1  | 🧪 Playground Non-encrypted](https://user-images.githubusercontent.com/60790/165111863-2a9e188b-4926-4667-902f-330c556ef3d1.png)

**Comment by t3chguy** [comment]
Oh so don't form a continuation on both sides of the thread preview tile, got it.

Though the Figma does not happen to show that ftr

**Comment by janogarcia** [comment]
If the first message were a regular message, it would be rendered the same. I should have made that more explicit in the Figma mockup.

![Threads – Figma](https://user-images.githubusercontent.com/60790/165157259-9a799a0a-84f3-426a-a219-8308ea6b8f13.png)
