### ISSUE TITLE
PIP window closes when you switch to another room

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-web#20913]
### Steps to reproduce

(unfortunately doesn't reproduce reliably, however when the underlying problem seems active, it works all the time )

A new day, opening chat.fosdem.org: no problems;
After closing the tab with an active chat.fosdem.org session (verified) after a few minutes and reopening it:
1. Switch to "Home" selection on the left and then click "Home" to see the fosdem overview page
2. Open FOSDEM 2022 Space on the left
3. Open the "Test Track 1" by clicking the already joined room in the list on the left
4. make sure the "Livestream" widget is pinned
5. Open the stream in PIP mode by using the in-widget controls
6. Click on "Matrix Stand" room

#### What did you expect?

PIP window stays visible

#### What happened instead?

PIP window vanishes

### Operating system

Windows 10 Pro 19044.1469

### Browser information

Edge Version 97.0.1072.76 (Official build) (64-bit)

### URL for webapp

https://chat.fosdem.org/

### Application version

FOSDEM 2022 version: 1.10.1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes -> https://github.com/matrix-org/element-web-rageshakes/issues/10382

**Comment by aWeinzierl** [comment]
I could "end" the bug (for now) by unpinning the widget, opening it in the sidebar and then enable PIP.

**Comment by jryans** [comment]
> 5\. Open the stream in PIP mode by using the in-widget controls

Hmm, what does this step mean? I am attempting from develop.element.io, which could be slightly different, but I can't find any in-widget controls for PIP...?

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/279572/152804692-7d83275b-8bde-486b-8f6e-736bc36adf04.png">

**Comment by t3chguy** [comment]
I guess some browsers have a right click option on videos to break out into PIP

![image](https://user-images.githubusercontent.com/2403652/152805898-0af98f26-c280-4d1a-bba6-c785db56565a.png)

Which Element won't be able to detect and then will unmount the iframe when switching rooms.

**Comment by jryans** [comment]
Ah right, if @aWeinzierl means browser-specific features like that (as opposed to similar widget capabilities to persist the widget across rooms), then it's "expected" at the moment.

I do see though that [some browsers](http://developer.mozilla.org/en-US/docs/Web/API/PictureInPictureEvent) will actually emit events when these "browser PIP" features are used... but it's not yet available in all browsers Element Web supports.

**Comment by aWeinzierl** [comment]
> > 5. Open the stream in PIP mode by using the in-widget controls
> 
> Hmm, what does this step mean? I am attempting from develop.element.io, which could be slightly different, but I can't find any in-widget controls for PIP...?
> 
> <img alt="image" width="1013" src="https://user-images.githubusercontent.com/279572/152804692-7d83275b-8bde-486b-8f6e-736bc36adf04.png">

When I hover over the widget, I see:
![image](https://user-images.githubusercontent.com/20560137/152813082-5d5fdf0d-d25b-4a5a-9890-027dbb629f48.png)
The context menu offers speed settings as well as PIP:
![image](https://user-images.githubusercontent.com/20560137/152813262-e516a0bc-1501-4c8c-9564-5c0bbe557cc6.png)

This is true for the web app as well as for the Desktop app.


> as opposed to similar widget capabilities to persist the widget across rooms

How?

**Comment by t3chguy** [comment]
> There is currently no user-level feature to force a widget to stay on screen. Perhaps there should be, but that seems like a separate enhancement issue.



https://github.com/vector-im/element-web/issues/20933

**Comment by jryans** [comment]
Given that this widget seems to be operating as expected within the constraints of widgets, and there's also a separate issue for a user-level toggle, I think it's best to close this issue.

**Comment by t3chguy** [comment]
It'd be good if the FOSDEM/conf widget listened for the video element's PIP event and translated it into a Widget PIP caps event tbh
