### ISSUE TITLE
Bubble layout breaks layout of shared location

### ISSUE THREAD

**Issue by aWeinzierl** [vector-im/element-web#20916]
### Steps to reproduce

1. Send a location using Element Android (the first version with location sharing in the Play Store)
2. View the sent message in Element

#### What did you expect?
properly formatted message, maybe(!) even with a bubble around it

#### What happened instead?
timestamp and text overlapping
![image](https://user-images.githubusercontent.com/20560137/152563626-071f185d-7f3c-44a8-8c2f-79a8b5b0d1ef.png)

### Operating system

Windows 10 Pro 19044.1469

### Application version

Versión de Element: 1.10.1 Versión de Olm: 3.2.8

### How did you install the app?

https://element.io/get-started#download

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7705
