### ISSUE TITLE
Some dialogs are cut off on the bottom edge

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#20911]
The invite link should have a border all round.

Testing on https://61fd1afc94f814006310661b--matrix-react-sdk.netlify.app/ from https://github.com/matrix-org/matrix-react-sdk/pull/7718

Browser: Chromium 98.0.4758.80 (Official Build) Arch Linux (64-bit)

![Screenshot from 2022-02-04 13-12-01](https://user-images.githubusercontent.com/51663/152535263-9b7cc322-d6c5-44eb-a88e-b3c324ddc131.png)

**Comment by wiksien** [comment]
I will fix this issue.

**Comment by wiksien** [comment]
I had problems setting up develop branch on my local PC using Docker (I made a new issue about it: #20936). Obviously, I can't fix an issue without having the web app, so if someone wants to fix this issue themselves, go for it. For now I will wait untill said issue gets resolved.

**Comment by SimonBrandner** [comment]
@wiksien, be sure to visit https://matrix.to/#/#element-dev:matrix.org if you need help setting up a dev env!

**Comment by archijaiswal** [comment]
Hi, I'm new to opensource . Could you assign this task to me and assist me to fix this issue? Thanks.

**Comment by SimonBrandner** [comment]
> Hi, I'm new to opensource . Could you assign this task to me and assist me to fix this issue? Thanks.

I've assigned you, be sure to visit https://matrix.to/#/#element-dev:matrix.org, if you need help/directions!

**Comment by kittykat** [comment]
> This issue requires fixing file from [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk) repo. I should probably submit a PR there.

Yes, please submit the PR there and link it to this issue

**Comment by HarHarLinks** [comment]
devtools are cut off, too:
![image](https://user-images.githubusercontent.com/2803622/161378639-cdb14cd9-7d4f-4d17-bb3d-c5b4e790693f.png)

Element Nightly version: 2022040201
Olm version: 3.2.8

**Comment by kittykat** [comment]
> devtools are cut off, too

Can you file a separate issue for that please? This one will be closed soon either with a fix or when the dialog is removed (any day now)

**Comment by HarHarLinks** [comment]
@kittykat: your issue is titled very generally which led me to believe this issue encompasses modal dialogues in general rather than just this single dialogue.

**Comment by justjanne** [comment]
This issue and the issues merged into it describe overall two separate sub-issues:

1. Dialog content doesn’t properly shrink if the dialog shrinks causing double scrollbars
2. InviteDialog and DevToolsDialog use fixed heights for some elements.

Regarding 1., we’ll handle this issue at a later point in time, as it requires changing many more dialogs one by one.

Regarding 2., the issue with this is that these fixed height definitions (e.g., `height: calc(100% - 36px)`) assume certain values for margin, padding, and height of other elements in or around the dialog content. These values have changed recently, which caused the dialog content to be cut off.

My proposed fix for 2. replaces the *internal* fixed height definitions of the two dialogs which are still using these definitions with flex-based height definitions. This avoids us having to change them in the future if surrounding elements should change again.

**Comment by kittykat** [comment]
As per DM, lets go with fix 2 :+1:
