### ISSUE TITLE
Widgets are not stored in right panel history

### ISSUE THREAD

**Issue by toger5** [vector-im/element-web#20929]
### Steps to reproduce
In fosdem:
 - opening the schedule on the right panel
 - switch room
 - go back to the room.
 - see the room info panel instead of thewidget
This also does not works (and the issue can be tested) with any other widget.

**Comment by HarHarLinks** [comment]
on the other room, widgets that ask to stay open
![image](https://user-images.githubusercontent.com/2803622/152645461-e9d08e80-2996-48a3-8c5d-7fe0a343ba71.png)
in the sidebar, actually keep audio open in background when in sidebar contrary to if pinned

(nightly 20220205)
