### ISSUE TITLE
`MatrixCapabilities.RequiresClient` is in the wrong enum

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#20920]
It should be in `ElementWidgetCapabilities` instead, as an element thing without MSC. Alternatively, an MSC, still moving it, and adding the MSC's version to `MatrixCapabilities` would be good 😇

**Comment by rkouwenhoven** [comment]
I would like to fix this issue

**Comment by SimonBrandner** [comment]
> I would like to fix this issue

If you need any help, be sure to visit https://matrix.to/#/#element-dev:matrix.org

**Comment by rkouwenhoven** [comment]
If I remove RequiresClient from MatrixCapabilities, other codebases that use this field need to be changed. Should I add a deprecated tag instead? Or should I also change the other codebases?

**Comment by SimonBrandner** [comment]
> If I remove RequiresClient from MatrixCapabilities, other codebases that use this field need to be changed. Should I add a deprecated tag instead? Or should I also change the other codebases?

Yep, would make sense probably
