### ISSUE TITLE
Reply to a specific sender won't send in encrypted rooms

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#20928]
### Steps to reproduce

1. Go to the FOSDEM internal room
2. Try to reply to a message from @turt2live 

#### What did you expect?

Reply sends

#### What happened instead?

Reply can't be sent:

![image](https://user-images.githubusercontent.com/5547783/152634617-e3ed0179-d268-4d39-9b81-a7f7143325c7.png)

There's also an error in the console.

### Operating system

Arch Linux

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 64242a004eb7-react-7f3f18604417-js-2d23330b74da, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by babolivier** [comment]
Also for some reason I can't even mention Travis:

![image](https://user-images.githubusercontent.com/5547783/152634634-760fb330-e424-4453-aa96-41678b6f6463.png)

Or share a message of his:

![image](https://user-images.githubusercontent.com/5547783/152634644-fbd336f7-a9a6-44aa-addc-3c2b575f5daa.png)

**Comment by t3chguy** [comment]
Looking at the rageshake, the errant code has since been rewritten so regarding this fixed unless told otherwise
