### ISSUE TITLE
"Add existing room" opens "Create a room" modal

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#20924]
### Steps to reproduce

1. Create a private Space
2. Open the Space
3. Expand the left room list on the left (this is important, the collapsed version works fine)
4. Click on the Plus button next to your Space's name
5. Click on "Add existing room"

![Screenshot 2022-02-04 at 19-50-34 Element #matrix-backstage-devroom fosdem org](https://user-images.githubusercontent.com/10872136/152586629-a1f70bfb-2f41-451f-a88d-967d78e42471.png)

#### What did you expect?
A modal opens letting me pick one or many rooms that I'm joined to.

#### What happened instead?
The modal for creating a room opened.

![Peek 2022-02-04 19-49](https://user-images.githubusercontent.com/10872136/152586813-073615ab-8e62-4bbf-b4f7-a1896eacedce.gif)

### Browser information

Firefox Developer 97

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
Please fix issue title?

**Comment by jaller94** [comment]
You had commented on this related issue: https://github.com/vector-im/element-web/issues/20222#issuecomment-995972314

A few other issues have "Add existing room" in their titles, however, I couldn't find a direct duplicate.
