### ISSUE TITLE
Custom branch won't build from Docker.

### ISSUE THREAD

**Issue by wiksien** [vector-im/element-web#20936]
### Steps to reproduce

1. I do steps exactly as described in `README.md` section titled `Running from Docker` up to git checkout command.
2. I write `git checkout develop`.
3. I write modified docker build command so it works on my operating system: `docker build -t element-web:local-test --build-arg USE_CUSTOM_SDKS=true --build-arg REACT_SDK_REPO="https://github.com/matrix-org/matrix-react-sdk.git" --build-arg REACT_SDK_BRANCH="develop" --build-arg JS_SDK_REPO="https://github.com/matrix-org/matrix-js-sdk.git" --build-arg JS_SDK_BRANCH="develop" .`
    ```
    docker build -t element-web:local-test \
        --build-arg USE_CUSTOM_SDKS=true \
        --build-arg REACT_SDK_REPO="https://github.com/matrix-org/matrix-react-sdk.git" \
        --build-arg REACT_SDK_BRANCH="develop" \
        --build-arg JS_SDK_REPO="https://github.com/matrix-org/matrix-js-sdk.git" \
        --build-arg JS_SDK_BRANCH="develop" \
        .
    ```
4. Everything runs fine until error message appears:
![obraz](https://user-images.githubusercontent.com/88692323/152661330-1fcece33-0933-4737-9b08-f2242ad49db3.png)

#### What did you expect?

I expected that the command completes building the web app.

#### What happened instead?

Midway through and error message appeared.

### Operating system

Windows 10 Pro N

### URL for webapp

v1.10.1

### Application version

v1.10.1

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
Based on some Googling -> https://stackoverflow.com/q/14219092/796832: It looks like you're problem has to do with a line-ending problem, `\r\n` vs `\n`.

I'm guessing that when you cloned the repo, `git` messed with your line endings. You probably want to follow https://stackoverflow.com/a/13154031/796832 to get LF `\n` line endings.

**Comment by t3chguy** [comment]
Closing due to it being a git config issue
