### ISSUE TITLE
Thread summary is visually cut off when using maximized widget

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20941]
### Steps to reproduce

thread with maximized widget

### Outcome

![image](https://user-images.githubusercontent.com/2803622/152682011-61fec841-043c-4d3f-8cb7-b4279eaf7526.png)

### Operating system

arch

### Application version

Element Nightly version: 2022020601 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by gsouquet** [comment]
@janogarcia iirc correctly we enforce a `min-width` for the thread summary. 
What should happen in this scenario? We can go below the minimum recommended width and add an ellipsis? Does that sound like a fair thing to do here?

**Comment by HarHarLinks** [comment]
I can confirm this happens everytime the timeline is narrow enough, maximized widgets are just the most common use case since nobody is going to use element like this:
![image](https://user-images.githubusercontent.com/2803622/152820299-a7a53237-d6ad-4180-9a6e-ce6d37b6ebf9.png)

**Comment by jryans** [comment]
Seems straightforward enough, I've offered to pick this up from @gsouquet.

**Comment by janogarcia** [comment]
Heads up that I've updated the design to remove the label for the reply count when the timeline is rendered in a narrow container (below 400px).

![Threads – Figma](https://user-images.githubusercontent.com/60790/154546193-9eeea3d8-17ae-4c43-b61f-33e1c2cffcae.png)
