### ISSUE TITLE
The copy button to copy your DM invite link shows up twice (Browser)

### ISSUE THREAD

**Issue by AstroOrbis** [vector-im/element-web#20945]
### Steps to reproduce

1. Click the "Add" button (looks like a Plus)
<img width="384" alt="Screen Shot 2022-02-06 at 09 01 03" src="https://user-images.githubusercontent.com/65419194/152684466-ec000f97-717b-4849-934a-ba7740c1484d.png">
 2. Click the "Start New Chat" button
<img width="179" alt="Screen Shot 2022-02-06 at 09 01 33" src="https://user-images.githubusercontent.com/65419194/152684492-3edd2be8-1d3c-42a6-b701-b14a611ac0ec.png">
3. Hover over the copy button for your invite link
<img width="734" alt="Screen Shot 2022-02-06 at 09 03 48" src="https://user-images.githubusercontent.com/65419194/152684595-a98c9aef-9cf8-4a37-aedc-fee220a0f294.png">
4. A fully functional new copy button appears to the let
<img width="735" alt="Screen Shot 2022-02-06 at 09 03 58" src="https://user-images.githubusercontent.com/65419194/152684601-5bdaf61e-a218-4a26-9538-2e7315668195.png">

### Outcome

A second copy button appears.

This issue is also present on the desktop app, so I will be creating a duplicate issue in that category.

### Operating system

MacOS

### Browser information

Latest Opera GX

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Thank you for taking the time to tell us about your issue.

I am going to close this issue as it has been resolved on develop.element.io and should be available to you soon.
