### ISSUE TITLE
"Block this user" should also block quotations

### ISSUE THREAD

**Issue by dertuxmalwieder** [vector-im/element-web#20951]
#### What would you like to do?

When I block a user so I can't see his messages anymore, I would also love to not see anyone quoting this user anymore.

#### Why would you like to do it?

"Block" should mean "block", not "partially block".

#### How would you like to achieve it?

Element should work like Twitter here: "Block" = "also block any quotations".

### Have you considered any alternatives?

Well, not visiting certain rooms anymore, I guess.

**Comment by SimonBrandner** [comment]
Do you mean quotes or replies to their messages?

**Comment by dertuxmalwieder** [comment]
I mean quotes.

**Comment by HarHarLinks** [comment]
Quotes in reply fallbacks are an interesting point here (and more importantly in clients that don't implement rich replies)

**Comment by t3chguy** [comment]
> or a protocol enhancement?

Well all blocking is done by the server currently

**Comment by turt2live** [comment]
I don't believe this is feasibly possible, even from a spec perspective, so closing as impossible, sorry. From a spec perspective we wouldn't really be comfortable adding the metadata to the message at the moment, though if someone were to be convincing enough in an MSC then it can be reconsidered.

Further, where we put the metadata itself would be unknown given quotes are deliberately not a spec feature nor are they verifiably accurate in the first place.
