### ISSUE TITLE
Redacted invite and join events disappear from the timeline

### ISSUE THREAD

**Issue by heftig** [vector-im/element-web#20959]
### Steps to reproduce

1. Invite another user to a room
2. Redact the invitation from the timeline

#### What did you expect?

The invitation is withdrawn.

#### What happened instead?

The invitation disappeared completely from the timeline but the user stayed invited. They merely lost their nick and avatar.

### Operating system

Arch Linux

### Browser information

Firefox 98.0a1

### URL for webapp

app.element.io

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

archlinux.org, Synapse 1.51.0

### Will you send logs?

No

**Comment by heftig** [comment]
It seems you actually need kick permissions to withdraw invitations, but the current effect of hiding the invitation from the timeline is still inappropriate. The event should stay visible, even if nick and avatar are gone.

**Comment by heftig** [comment]
The same happens when join events get redacted, which I just saw happening with Mjolnir. They just disappear from the timeline.

I don't think this used to happen, so it's a regression. Perhaps from when the bubble layout was implemented?

**Comment by t3chguy** [comment]
> Perhaps from when the bubble layout was implemented?

The bubble layout didn't change which events got rendered, only added layout specific attributes to them
