### ISSUE TITLE
Pressing Reply causes a Thread to be started instead, if you've already opened the Threads panel

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#20963]
### Steps to reproduce

1. Click "Reply in thread" on a message: the Right panel opens
2. Close the right panel
3. Click "Reply" on the same message
4. The new reply will be part of a new Thread, not an old-style Reply

#### What did you expect?

Old-style Reply

#### What happened instead?

New-style Thread Reply

### Operating system

mac

### Will you send logs?

No

**Comment by t3chguy** [comment]
I cannot reproduce this anymore, @benparsons have you seen this recently?

**Comment by benparsons** [comment]
I cannot reproduce.

But, when I tested I get a different error - "Something went wrong" appears in Right Panel when trying to leave the Threads screen. Logs attached.

**Comment by t3chguy** [comment]
Please open a new issue regarding that, has very different symptoms and causes

**Comment by t3chguy** [comment]
(I'll repoint your rageshake when you open the new issue)
