### ISSUE TITLE
Joining a virgin or temporarily desynched room mess up event display order

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#20961]
### Steps to reproduce

1. Join a newly created foreign server room where your HS had no joins so far

### Outcome

_I have tried to search for this bug, since it is known and experienced for years now, but I wasn't pretty successful, and there were multiple "posisbly related" bugs, far in the past. I kindly ask your help to find its duplicate, or related, if you know it without searching, or know the proper keywords. Thanks!_

#### What did you expect?
All events are visible and they are in chronological order.

#### What happened instead?
Some events appear in random places, days, possibly weeks earlier. If the room has no enough history to contain days or weeks, the events became "ghost": canot be seen by scrolling but became temporarily visible when referenced by replying.
They may be reordered on browser reload or cache clear.

The same effect may happen when some servers are delayed/desynched, and the user joins the room, or sometimes even when being in the room. Some events (possibly the ones which were backfilled on the server after Element synched its state?) aren't visible but not lost, just they are possibly inserted in the past, hours or days or even weeks ago, and could be found by scrollnig up. Often they can't be easily found, and finding them requires someone who see them normally to reply to them, thus reference the event, which can be clicked and found by the other party.

I would guess this is a result of the difference between LocalStorage state and server state, and somehow the later arriving(?) events aren't fitting anywhere and gets inserted at seemingly random places.

Cache clear probably resolves the issue, but I do not want to clear it just yet, since I have the effect on #offtopic:matrix.org right now, if anyone wanted to ask for any state variables.

### Application version

version: 1.10.1 Olm version: 3.2.8

### Will you send logs?

No

**Comment by turt2live** [comment]
This will be a server issue and not something we can easily fix. We're simply showing the events in the order the server gives them to us.
