### ISSUE TITLE
Mouse pointer starts flashing between hand and arrow in a tight loop

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#20960]
### Steps to reproduce

1. Chatting in a room.
2. Needs a click, either on a line with no hotspot or one of the icons at the end, usually "edit" (often I accidentally click on the line, not by purpose)
3. About 1 in 20 the bug happens

#### What happens

__Browser__: Chromium (Version 97.0.4692.71 (Official Build) built on Debian bookworm/sid, running on Debian bookworm/sid (64-bit)

__Version__: version: 1.10.1; Olm version: 3.2.8

The mouse cursor starts flashing between Hand and normal Arrow, about 20 changes per second, or probably the maximum rate the desktop environment can actually display. 
The browser UI is halted since the loop is so tight 100% CPU (used by that specific browser thread, not the whole machine) is used up. 
Clicking on a tab does nothing, but the click is travelling at snail speed and it is possible that it gets processed in a few minutes, and the browser changes tabls. In this case sometimes the flashing ends, and from then it's good again. Sometimes it stays unresponsive and have to be killed.

### Operating system

Debian/sid Linux 

### Browser information

Chromium (Version 97.0.4692.71 (Official Build) built on Debian bookworm/sid, running on Debian bookworm/sid (64-bit)

### URL for webapp

https://riot.grin.hu/

### Application version

version: 1.10.1; Olm version: 3.2.8

### Homeserver

synapse  1.51.0-1

### Will you send logs?

No

**Comment by gsouquet** [comment]
Would you be able to take a performance recording of your browser when that does happen? 
That would greatly help to understand what pegs the CPU

**Comment by grinapo** [comment]
Not really. It become so unresponsive that don't answer to SIGINT / CTRL-C either. I will try to start a task manager in the background and pull it up when it happens, but I doubt it would succeed and even then it would probably show that javascript hogs 100% CPU. Chromium logs nothing to the (xterm) console.

Also, this is new, I haven't seen that in the before-last version.

**Comment by grinapo** [comment]
I caught two now, with not much success.

One was with open console: nothing was logged. Browser had to be killed.

An other one was with open task manager. Element tab used ~80% cpu, and browser core used ~60%, but the browser (including all windows of it) was compoletely unresponsive (cursor shape change tight loop), so the task manager wasn't updating the figures either.
However when I focused another window (xorg was working fine, though with raised cpu usage) after a while the tab just started working. It seems when I deprived it of its cursor the constant changes were either stopped or happened faster, without using resources, and task manager started to respond, raised browser core to ~90% cpu, and after a few tens of seconds everything went back to normal, tab cpu usage back to 2-3%.

**Comment by grinapo** [comment]
It is getting more frequent now, about once a day. 
When it happens on clicking reply the effect with the cursor is the same, but also the reply icon starts flashing between pushed and normal in high frequency.
About every fifth occurence it can be self-healed by removing focus for a few seconds.

**Comment by grinapo** [comment]
Since this was observed right now on another webpage (namely gmail interface) I believe this must be a Chromium bug, and element can't be blamed (only for triggering it, but it's really unreproducible reliably). I am closing this, you can't help it it seems.

**Comment by grinapo** [comment]
Just putting here [the cromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1301067) as well for the record.

**Comment by grinapo** [comment]
FYI:
>  The fix will rollout in Chrome 101.  Unfortunately we can't backport the fix to 99 or 100 since it's too large and risky.  However, you can install the Chrome dev channel alongside the stable channel if you need the fix sooner.  The fix will reach the dev channel in about a week.

**Comment by mibmo** [comment]
I'm still having this issue as of 2022-06-29 and on `element-desktop` too.

**Comment by t3chguy** [comment]
@mibmo the fix isn't in a release yet. It will be in 1.11.0
