### ISSUE TITLE
Allow fully ignoring unread messages in room or space

### ISSUE THREAD

**Issue by IeuanK** [vector-im/element-web#20975]
#### What would you like to do?

I would like to not be made aware of new messages unless mentioned, including hiding the unread message orb

#### Why would you like to do it?

I have a few bridges that cause constant orbs to appear, which destroys my 'inbox zero' feel

#### How would you like to achieve it?

Preference for each space or room to hide unread notifications, but still let mentions and keywords through

**Comment by SimonBrandner** [comment]
This is mostly a duplicate of https://github.com/vector-im/element-web/issues/16836, would you agree with closing this issue in favor of https://github.com/vector-im/element-web/issues/16836?

**Comment by IeuanK** [comment]
I agree that that would satisfy my request, thanks for linking, will close this one :)
