### ISSUE TITLE
SearchBar search crashes when All Rooms is selected

### ISSUE THREAD

**Issue by ohporter** [vector-im/element-web#20979]
### Steps to reproduce

1. Where are you starting? What can you see?

Room selected with timeline visible.

2. What do you click?

Click on magnifying glass in upper right to open the SearchBar. Then clicked on "All Rooms".

3. More steps…

Typed "test" and pressed <Enter>

#### What did you expect?

Search results to be shown.

#### What happened instead?

Crash with "Something went wrong!"

Note that running the same search with "This Room" selected is successful. Also, an admin user on the same server can search "All Rooms" without the crash. This occurs with a default power user only.

### Operating system

Debian Linux

### Browser information

Version 96.0.4664.45 (Official Build) (64-bit)

### URL for webapp

Element version: 1.10.1 Olm version: 3.2.8

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

Synapse 1.51.0

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
@ohporter Thank you for reporting this issue.
It appears that a recent code change has probably fixed this issue. To confirm that would you be able to test this on develop.element.io as I have personally not been able to reproduce this

**Comment by t3chguy** [comment]
I believe this to even be fixed on the latest release, 1.10.4

**Comment by kittykat** [comment]
I am going to close this issue for now as it appears to have been resolved and we have not had further reports. Please reply with @kittykat if you are still experiencing it and I will reopen it for you.
