### ISSUE TITLE
Store font size in im.vector.web.settings

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-web#20983]
#### What would you like to do?
When setting a font size in the Appearance section of Settings, I would love for this to be saved so that if I log in elsewhere, I don't need to set it again.

#### Why would you like to do it?
Whenever I log in to Element Web I always drag the font size slider down to 14. Was just thinking that it would be nice for this to be remembered as I've been logging in to test accounts more regularly recently.

#### How would you like to achieve it?
My first thought would be to store the setting in the `im.vector.web.settings` account data event, but there may be better solutions here.

### Have you considered any alternatives?

A different default font size might be an alternative, but everyone has their own preferences so seems unlikely to be a productive activity.

**Comment by t3chguy** [comment]
> When setting a font size in the Appearance section of Settings, I would love for this to be saved so that if I log in elsewhere, I don't need to set it again.

Different devices have different resolutions and screen densities, so different px font sizes will be needed for different devices. Forcing a user to have one font size between all devices is not a good idea for accessibility.

**Comment by pixlwave** [comment]
> Different devices have different resolutions and screen densities, so different px font sizes will be needed for different devices. Forcing a user to have one font size between all devices is not a good idea for accessibility.

That’s a very valid point I hadn’t considered given my narrow range of devices. Will close 👍
