### ISSUE TITLE
Modifying widgets uses MXID instead of Display Name

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#20986]
### Steps to reproduce

1. Add a widget
2. Remove a widget

#### What did you expect?
Use display name, same as when inviting, modifying room settings, ...

#### What happened instead?
> Widget added/removed by `@mxid:server.tld`

### Operating system

arch

### Application version

Element Nightly version: 2022020801 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/70a44a8cd61692173c2f311a577cc89c22914ca5/src/TextForEvent.tsx#L636

Should look more like `const senderName = event.sender?.name || event.getSender();`

**Comment by HarHarLinks** [comment]
https://github.com/vector-im/element-meta/discussions/149
