### ISSUE TITLE
Location share map doesn't reload after regaining connectivity

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20993]
### Steps to reproduce

1. Joe sent me a location share
2. My client received it, but i didn't yet look at it
3. My client then lost connectivity
4. I then tried to view it - "Failed to load map", and no avatar on the pic, which is fine
5. I then got connectivity back again
6. Avatar loads
7. Map does not

#### What did you expect?

Map should get nudged to reload when connectivity reestablishes.

#### What happened instead?

I had to switch back & forth between rooms before the map would load

### Operating system

macOS

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Closed by https://github.com/matrix-org/matrix-react-sdk/pull/8848
