### ISSUE TITLE
Display name and avatar disappearing after sending a second message

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#20999]
### Steps to reproduce

1. Send a message in a DM, and see my account's display name and profile picture
2. Send another message -> my profile picture and display name are no longer there!

Example one:
![image](https://user-images.githubusercontent.com/1342360/153189617-cbcb4347-f533-4284-ab15-3fcabda34865.png)

Example two:
![image](https://user-images.githubusercontent.com/1342360/153189798-6342a002-d3cb-4a16-ba92-791039274803.png)

I also seem to have completely disappeared from the members list:

![image](https://user-images.githubusercontent.com/1342360/153190999-c5b78e3f-4799-4cb4-ae06-b84d58833712.png)

#### What did you expect?

To see my display name and profile picture consistently.

#### What happened instead?

It's a gone!

Hunch: could this perhaps be related to any recent "change profile information for older messages" work?

Also possibly related: https://github.com/vector-im/element-web/issues/20981

Very possibly related (stale memberlist): https://github.com/vector-im/element-web/issues/20962

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022020701, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Seems very likely to be the same cause as https://github.com/vector-im/element-web/issues/20981 - nightly no 2 from today (2022021102) has the fix, so please let us know if you see it again with this version.

**Comment by dbkr** [comment]
No more reports of this since the revert (https://github.com/matrix-org/matrix-js-sdk/pull/2171) so I'm going to say that this is fixed
