### ISSUE TITLE
Terminating voip calls trigger audio notif

### ISSUE THREAD

**Issue by kegsay** [vector-im/element-web#2100]
By Matthew: Apparently if you have audio notifs turned on in a 1:1, the act of the remote party terminating a call triggers a notif

**Comment by t3chguy** [comment]
Should this not be on https://github.com/vector-im/riot-ios?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
