### ISSUE TITLE
Notifications right panel: Something went wrong!

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#21004]
### Steps to reproduce

1. Not sure, this just appeared.

### Outcome

> Something went wrong!
> Please [create a new issue](https://github.com/vector-im/element-web/issues/new/choose) on GitHub so that we can investigate this bug.

### Operating system

mac

### Browser information

chrome

### URL for webapp

develop.element.io

### Application version

762fc53c6150-react-254dbeeccb26-js-41bf8c2d5f4a

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Does not affect the RC
