### ISSUE TITLE
'Add existing room' button opens up dialogue to Create a new room

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-web#21001]
### Steps to reproduce

1. Open a Space in Element
2. Click [+] next to the space title and get a menu.
3. Click 'Add existing room'

<img width="212" alt="image" src="https://user-images.githubusercontent.com/38398653/153192940-11eef0e9-5172-4d08-8e26-64717bdb2aba.png">

#### What did you expect?

Dialogue to add existing room

#### What happened instead?

Dialogue to create new room

<img width="369" alt="image" src="https://user-images.githubusercontent.com/38398653/153192990-a39d14b4-5d2f-400a-8919-b574588b7f87.png">

### Operating system

Linux

### Browser information

Firefox

### URL for webapp

https://develop.element.io

### Application version

Element version: 64242a004eb7-react-7f3f18604417-js-2d23330b74da Olm version: 3.2.8

### Homeserver

librepush.net

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please use a newer develop. 5 days old for develop is centuries. Fixed since
