### ISSUE TITLE
Delay noisy notifications when popup/desktop notifications are turned on

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-web#21019]
### Your use case

Noisy notifications can be annoying when they repeat many times.

**Suggestion:**
If popup/desktop notifications are turned on, Element should give users 5 seconds to switch to Element to read/reply to the message before it triggers a noisy notification.

**Comment by HarHarLinks** [comment]
on the other hand it would be weird to get a noisy notification without visual indication of its origin, don't you agree?

**Comment by SPiRiT369** [comment]
It's not weird at all. A user might choose to have noisy notifications only and disable popup notifications (for privacy reasons or just personal preference). In this case, the noisy notification should work as is.

In my case, I have both desktop notifications and noisy ones and I feel there is too much noise. There is additional noise for the popup message that the browser sends.

I'm not sure exactly if/how other apps do that, but when I use Telegram Desktop, the app is not so noisy. I think that if it beeps for new message, it won't make another one for few seconds after that. Maybe that's a better way to define it?

**Comment by SPiRiT369** [comment]
Although I think this can be very useful, I understand that this feature might not be useful for most users, and some might see it un-needed. There are other more important suggestions and bugs to handle, so I close it.
