### ISSUE TITLE
Read and send receipts get cut off with bubble layout 

### ISSUE THREAD

**Issue by noantiq** [vector-im/element-web#21011]
### Steps to reproduce

1. Select bubble layout in settings
2. open any room
3. look at the read receipts

#### What did you expect?
To see complete circles
#### What happened instead?
The circles are cut off on the right side, see screenshot.

![image](https://user-images.githubusercontent.com/39308834/153249008-984464ac-ae38-41d4-b536-f450d9faeaa1.png)

### Operating system

Ubuntu

### Application version

Element Nightly version: 2022020901 Olm version: 3.2.8

### How did you install the app?

Element Debian repo

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot repro in firefox

![image](https://user-images.githubusercontent.com/2403652/153370658-7768544e-28f9-4add-a29a-c2dca07bd418.png)

Cannot repro in chrome

![image](https://user-images.githubusercontent.com/2403652/153370821-842d7fd4-4682-44ca-b937-398b3a7a522d.png)

**Comment by noantiq** [comment]
Could not reproduce in Web as well but it persists on nightly for me. Did you try to reproduce it on desktop too?

**Comment by t3chguy** [comment]
Cannot repro on Desktop (11th Feb Nightly) either

<img width="133" alt="image" src="https://user-images.githubusercontent.com/2403652/153575419-0e84b31c-396a-4749-a4d0-432b3b5c1f2d.png">

**Comment by turt2live** [comment]
Is this specific to the meta read receipts (send/sending) rather than actual read receipts?

**Comment by noantiq** [comment]
@turt2live No, it is not, I just wanted to keep my picture out of the original screenshot. For clarification here is another screenshot:
![image](https://user-images.githubusercontent.com/39308834/154722620-dd8b64d3-90eb-499c-8a46-4d3623f4b8eb.png)

What I did notice was that it might be OS specific since it seems like that cut-off has the same width as Gnome's scrolling indicator, see:
![image](https://user-images.githubusercontent.com/39308834/154723456-b84f5b68-abb0-4684-9c33-2082f8dce20d.png)

**Comment by luixxiul** [comment]
Which desktop environment do you use? It might be specific to GNOME.

I run XFCE on Debian and cannot be reproduced.

**Comment by noantiq** [comment]
Yes, that’s what I figured too, I use GNOME.

**Comment by waclaw66** [comment]
![obrazek](https://user-images.githubusercontent.com/15554561/158172357-f5eaa7c8-4b6b-485f-ad17-19d1c69b53ce.png)

**Comment by robintown** [comment]
@noantiq Are you still seeing this with the new read receipt designs on 1.10.12?

**Comment by noantiq** [comment]
@robintown looks good now :+1:
