### ISSUE TITLE
Threads does not switch to new/other thread

### ISSUE THREAD

**Issue by tmissoni** [vector-im/element-web#21010]
### Steps to reproduce

Ff the thread panel is open on a thread, clicking on the timeline on another thread or

Uploading Screen Recording 2022-02-09 at 17.05.34.mov…

 reply in a thread does not switch to the new/other thread. You must go back to the thread list and then, clicking new/other thread works properly

#### What did you expect?
Clicking on another thread or answer in a thread button should bring me automatically in the selected/new thread
#### What happened instead?
the thread displayed in the thread pane remains the same

### Operating system

OSX

### Application version

Element Nightly version: 2022020901 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
I cannot reproduce this - @tmissoni can you upload the screen recording you attempted to? Thanks

https://user-images.githubusercontent.com/2403652/154671177-160cb234-787c-4328-8a37-593579c9b48f.mov

**Comment by t3chguy** [comment]
Closing as no longer an issue, shout if you see it again.
