### ISSUE TITLE
Leaving a space doesn't correctly cascade

### ISSUE THREAD

**Issue by razzeee** [vector-im/element-web#21012]
### Steps to reproduce

1. I attended fosdem and had a bunch of rooms with their inbetween rooms, so that everything was neatly in the space
2. I right clicked the space and clicked `Leave space`
3. Selected `Leave all rooms` and hit the red button

#### What did you expect?
I expected it to cascade through all levels of rooms and correctly remove the space.

#### What happened instead?
My sidebar basically exploded and I now have ~20 new spaces

![image](https://user-images.githubusercontent.com/5943908/153250989-e66ae5d0-cf68-4213-82b6-670874f1a4ba.png)

### Operating system

Manjaro Linux

### Application version

Element version: 1.9.6 Olm version: 3.2.3

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This was a bug specific to subspaces, which are still in Beta as per their label
