### ISSUE TITLE
Can't forward image from a thread

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21015]
### Steps to reproduce

1. go to https://matrix.to/#/!AZozoWghOYSIAfaZjJ:matrix.org/$jf9BUsdwpskZIMklDOMzqE6P1CdzXfZWoig3-nuht38?via=matrix.org&via=privacytools.io&via=tchncs.de
2. the source is structured like this, not sure if that's a proper thread event or not, so pasting here:
```json
{
  "content": {
    "body": "image.png",
    "info": {
      "h": 707,
      "mimetype": "image/png",
      "size": 518253,
      "thumbnail_info": {
        "h": 600,
        "mimetype": "image/png",
        "size": 458227,
        "w": 466
      },
      "thumbnail_url": "mxc://xxx",
      "w": 550,
      "xyz.amorgan.blurhash": "T4RfIGO@=s#m*J00EfB:%2QmH?w^"
    },
    "m.relates_to": {
      "event_id": "$yyy",
      "m.in_reply_to": {
        "event_id": "$zzz"
      },
      "rel_type": "io.element.thread"
    },
    "msgtype": "m.image",
    "url": "mxc://XXX"
  },
  "origin_server_ts": 1644415812501,
  "sender": "@aaa",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$bbb",
  "room_id": "!AZozoWghOYSIAfaZjJ:matrix.org"
}
```
3. click to forward the image

#### What did you expect?
forward the simple image

#### What happened instead?
1. it's preview is formatted like a reply (not even like a thread), when it should forward a simple message
2. it fails to send
![image](https://user-images.githubusercontent.com/2803622/153256528-e5d9ce32-2708-4604-a0f3-1f5166f5b555.png)

### Operating system

arch

### Application version

Element Nightly version: 2022020901 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.51

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
I can't replicate the "reply" with forwarding but I do encounter an error when trying to forward a message in a thread to another room. 

I think this falls into the fast follow epic along with things like "voice messages" so I'll remove the Needs-Product label and update the issue to reflect that. 

If you have any other questions, tag me :)
