### ISSUE TITLE
Read-receipts shifting backwards in the timeline

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#21016]
### Steps to reproduce

A few times now, I've observed a user's read receipt animating back up the timeline(!) to the previous message after the user in question sends a message of their own:

Case 1:
![image](https://user-images.githubusercontent.com/1342360/153260585-8898eaca-4dfe-4a14-85a9-bf31ced74c8e.png)

Case 2:
![image](https://user-images.githubusercontent.com/1342360/153260616-6f100442-bfd6-414f-95f1-8259041db978.png)

Note the read receipt markers on the right. In both instances, Erik's read receipt should at least be at his latest message.

* User A sends a message (message 1)
* User A's read receipt is set to message 1 
* User B sends a message (message 2)
* User B's read receipt is set to message 2
* User A's read receipt is set to message 2 after they read it
* User B's read receipt _incorrectly_ animates back up to message 1. It should not have moved.

#### What did you expect?

Read receipts not to ever go backwards

#### What happened instead?

Read receipts walk backwards up the timeline. This is weird.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022020802, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
This seems like something that should have been fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2160 though if my math is right, your version of Element should have that fix :/

**Comment by ektefa** [comment]
I saw this today too

**Comment by anoadragon453** [comment]
@ektefa what is your Element version (Settings -> Help & About -> Versions) and operating system? That may help us track down when this regression was introduced.
