### ISSUE TITLE
Submit debug logs stuck at "Collecting app version information..."

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#21023]
### Steps to reproduce

1. Tried to submit debug logs for https://github.com/vector-im/element-web/issues/21021
2. It wedged on "Collecting app version information..." with no useful feedback as to what had happened.
3. Clicking 'Cancel' or 'Send logs' doesn't do anything, so I'm stuck

My laptop does have a functioning internet connection.

#### What did you expect?
Rageshake to send

#### What happened instead?
Rageshake didn't send, Element wedged forever

### Operating system

macOS Monterey

### Application version

Element Nightly version: 2022020901 Olm version: 3.2.8

### How did you install the app?

Website

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by t3chguy** [comment]
Anything useful in your console?

**Comment by lampholder** [comment]
I'll inspect the console next time it happens - it's happened a few times

**Comment by turt2live** [comment]
Closing while we await new information. I'm certain this will be a variant of https://github.com/vector-im/element-web/issues/13290
