### ISSUE TITLE
Inconsistent UI when creating rooms in space I don't have permission to do so

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#21020]
### Steps to reproduce

I do not have permission to add rooms or create rooms in the given space.

When using the `+` by the list of rooms, i see greyed out UI for creating a room in the space:
![add-denys](https://user-images.githubusercontent.com/1917473/153387450-c4476d18-a68d-4f8a-85fb-9bef9b4cdc51.png)
When using the `+` by the space, i do not see greyed out UI:
![add-allows](https://user-images.githubusercontent.com/1917473/153387454-3c811f52-acdb-4d4f-b561-ff3182e0ec64.png)

Additionally, if i do click "add room to space", it takes me to "Create a room" not "add a room":
![Screenshot from 2022-02-10 10-24-54](https://user-images.githubusercontent.com/1917473/153387875-3825ce34-c6c2-4ee6-9769-ad586dbd4d70.png)
And then when i complete the operation, i get the generic "it broke":
![failure](https://user-images.githubusercontent.com/1917473/153387921-13b977a1-4b30-4e76-a6e1-340a800800be.png)

I think this second part might be related to #20222 "add room turning into create room" - but the lack of permission checks which got me into that UI at all is the core of this issue.

#### What did you expect?
Consistent greyed out UI

#### What happened instead?
Only one of the two routes greyed out the option, and the other route took me to an error.

### Operating system

Linux ubuntu

### Application version

Element version: 1.10.1 Olm version: 3.2.8

### Homeserver

ems

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Additionally, if i do click "add room to space", it takes me to "Create a room" not "add a room":

is a bug and already fixed on develop

**Comment by t3chguy** [comment]
> Only one of the two routes greyed out the option, and the other route took me to an error.

This is also fixed on develop already
