### ISSUE TITLE
Message Bubbles: Remove visible hover state

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-web#21029]
### Your use case

When you select message bubble layout and hover over bubbles, the background area becomes grey. 
![grafik](https://user-images.githubusercontent.com/24477557/153448331-9ac75184-3506-4282-8cd1-c9b30c3b3c1b.png)

As none of the big messaging app competitors do this - why does element? I personally don't like it.

**Comment by daniellekirkwood** [comment]
Thanks for the feedback! It's really interesting that you feel this way about the cell highlight. 

Our reasons for keeping the highlight on the cell, with and without bubbles, is to improve readability and ensure that different UI items remain related. When a 'cell' or 'row' is highlighted the action bar also appears, indicating to our new - or less experienced users - that further actions are available. 

I'm going to go ahead and close this issue as the team is not looking to update this behaviour for now. However, if you would like to continue this discussion you're welcome to [open a discussion here](https://github.com/vector-im/element-meta/discussions/categories/ideas) and tag your suggestions as an Idea for future development :D 

Thanks again!

cc @amshakal & @pixlwave
