### ISSUE TITLE
Context menu to view individual reaction events from the reaction bubble

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#21027]
### Your use case

I would like to look at individual reaction events without enabling "view hidden events".
When this is implemented, the context menu that is accessed from the reaction bubble would show the reaction key, the display name and the time stamp of the reaction; and individual menu items would show the event source view when clicked on them.

**Comment by SimonBrandner** [comment]
I am going to close this in favour of https://github.com/vector-im/element-web/issues/9723 as that issue at least partially covers your request. With dev tools enabled, the modal could show a view source button as you've requested
