### ISSUE TITLE
Redaction wrongly shown as continuation of previous sender

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#21030]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/2403652/153453235-db7866c3-5144-4d89-a362-4b394d915405.png">

This `Message deleted` was a message from Matthew, deleted by Matthew

**Comment by SimonBrandner** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/21055

**Comment by SimonBrandner** [comment]
Steps to repro:

1. Send a message as User A
2. Send a message as User B
3. Send a second message as User B
4. Redact B's first message
5. Note how it looks like A sent it.
6.

**Comment by t3chguy** [comment]
I do not believe this is a release blocker for 1.10.2 but only for releases thereafter, the MELS/ELS/GELS changeset was after the RC https://github.com/matrix-org/matrix-react-sdk/commit/714136d4f77cb2e7e2c7c2c81dd9e4aedc14f6ea
