### ISSUE TITLE
Support strikethrough text by wrapping in double tildes

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#21045]
As a committed power user, I've built up muscle memory to use double tildes (see [GitHub flavoured markdown](https://github.github.com/gfm/#strikethrough-extension-)) for strikethroughs.

I know I can wrap text in `<del> ... </del>` or use the formatting GUI, but neither cut it.

**Comment by SimonBrandner** [comment]
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/10444
