### ISSUE TITLE
Thread preview showing wrong avatar and no message preview

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#21044]
### Steps to reproduce

1. Open room
2. Look at thread

#### What did you expect?

Thread preview is consistent with what is shown as the last message when viewing the thread.

#### What happened instead?

No message is shown and the avatar is not the one of the person who last posted in the thread.

Thread tab:
![Screenshot from 2022-02-11 09-53-53](https://user-images.githubusercontent.com/5547783/153571403-3e38827a-32e2-462d-9783-fd49afd4fd44.png)

Room timeline:
![Screenshot from 2022-02-11 09-53-40](https://user-images.githubusercontent.com/5547783/153571407-b1363e0e-c814-4541-a862-d2b9e130354a.png)

Note that I have blurred the actual messages for privacy but I haven't done any edit to the thread preview (there wasn't any message to blur).

I was wondering if it can be something like the last person to post in the thread redacted their message, but there's only one redaction I can see in the timeline and it's not coming from the person whose avatar is shown in the preview.

### Operating system

Arch Linux

### Browser information

Firefox 96.0.2

### URL for webapp

develop.element.io

### Application version

Element version: d4a019b27a40-react-c3bb8cf3ef75-js-d97c514b8da0, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
@babolivier Can not reproduce this one either. Is it something that you can still experience on your end?

**Comment by babolivier** [comment]
Yep, saw it just now:

![image](https://user-images.githubusercontent.com/5547783/154998633-4d85f2cf-d554-4cc8-8dd7-483f2c1db176.png)

**Comment by babolivier** [comment]
Just saw that again today:

![image](https://user-images.githubusercontent.com/5547783/157028446-e831f932-cd9e-462e-9b0d-146fb5a184e5.png)

**Comment by t3chguy** [comment]
@babolivier have you seen this since? Yesterday I landed a change in how the summaries are handled and it fixed a bunch of "stale" summary issues

**Comment by novocaine** [comment]
No recent reports so closing
