### ISSUE TITLE
Auto update option

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#21041]
### Your use case

I want to update all users who not accept updates.
But I cannot do it because element crash when I run ElementSetup.exe on running element. It wiil be fine to have an option to allow automatic updates in registry on in the config.json file

**Comment by gsouquet** [comment]
Would you be able to share some debug logs of Element crashing for us to have a bit more context regarding what is going on?

> I want to update all users who not accept updates.

Could you elaborate on that? It seems odd to me that we would provide an option that would go against the user preferences

**Comment by dm-msk** [comment]
I cannot reproduce the issue. Next attempts to run Element Setup.exe on the running program does not through the error. I want to have newer version to all users in my environment through group policy.

**Comment by dbkr** [comment]
Sounds like this is no longer an issue if you can no longer reproduce it?
