### ISSUE TITLE
The icon for the "invite to space" menu item is cropped

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#21047]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/153585768-23ce1a8a-d4b8-4541-bda6-b6308d756763.png)

The icon for the "Invite to Space" menu item appears to be cropped.

1. Click the `+` button next to the People menu in the room list while looking at a space.
2. See the "Invite to Space menu item"

#### What did you expect?

The icon not to look cropped.

#### What happened instead?

:scissors: 

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022020802, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin/

### Will you send logs?

No

**Comment by t3chguy** [comment]
It is also the wrong icon
