### ISSUE TITLE
Upgrade to Node.js 17

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21043]
[Node.js 17 announcement post](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382)

# Known issues

- [ ] `ERR_OSSL_EVP_UNSUPPORTED` => [Node.js upgrade to OpenSSL 3.0](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382#5f07), temporary workaround use `--openssl-legacy-provider` as a CLI option 
- [ ] `node-gyp` build issues as described in https://github.com/vector-im/element-web/issues/20075

**Comment by squid-f** [comment]
Hi. 
Do pay attention the workaround doesn't work with all nodejs version and the issue happens with 16.14 as well, without this workaround possible.
https://github.com/webpack/webpack/issues/14532
and nodejs 18 doesn't exhibit the issue.

**Comment by t3chguy** [comment]
Why would we switch to 17 rather than using LTS releases?

17 isn't even a Current release anymore

**Comment by gsouquet** [comment]
Makes sense, we should instead use LTS versions
