### ISSUE TITLE
Cannot remove reactions in read-only rooms

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-web#21057]
### Steps to reproduce

* Change room permissions so that only Moderators can write in the room.
* Allow users to add reactions by choosing "Default" in the "Send reactions" permissions option.
* Add a reaction to some message.
* Delete the reaction.

#### What did you expect?
Since users have permission to add reactions, they should also be able to remove them.

#### What happened instead?
Reactions are not removed. Instead, the user gets a message:  "Some of your messages have not been sent".

### Operating system

Linux

### Application version

Element 1.10.1, Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
> has another permission "Send m.room.redaction events"

The UI will show all "unknown" power level settings from the m.room.power_levels event to allow the user to change them, even if they can't set them to begin with.
