### ISSUE TITLE
Hidden event grouping puts wrong avatar to name.

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#21050]
### Steps to reproduce

Have multiple reactions sent by different people (I think)

#### What did you expect?
Name and avatar match

#### What happened instead?
![image](https://user-images.githubusercontent.com/1374914/153651993-d85d3e38-cfcb-41bb-9711-455867e167d2.png)

### Operating system

Windows 11

### Browser information

Firefox 96.0.3 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: d4a019b27a40-react-87ca70edb144-js-47c5c4645e41 Version von Olm: 3.2.8

### Homeserver

nordgedanken.dev

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7739
