### ISSUE TITLE
Add Keyboard shortcut to go back to the last viewed room

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21062]
#### What would you like to do?
1. receive message in a room
2. switch there by clicking the notification etc
3. done with that
4. switch back to the last room

#### How would you like to achieve it?
in windows I can press Alt+Tab to go to the last focused windows, in my browser I can press Ctrl+Tab to switch to the last viewed tab, etc.

obviously the mentioned combos can't be used. Shift+Tab is used for keyboard navigation.

arrow keys are also heavily used. maybe an F-key?

**Comment by t3chguy** [comment]
Already there. Cmd + [ or ctrl + left arrow

**Comment by SimonBrandner** [comment]
> Already there. Cmd + [ or ctrl + left arrow

Beat me to it :D

**Comment by HarHarLinks** [comment]
> Already there. Cmd + [ or ctrl + left arrow

neither are working for me.

windows 10
Element version: 1.10.1
Olm version: 3.2.8

**Comment by HarHarLinks** [comment]
according to keyboard settings it is Alt+ left arrow
