### ISSUE TITLE
"Copied!" notification in various dialog needs more padding

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21069]
### Steps to reproduce

For example,
1. In a room, pick a message and go to ⋯ -> Share
2. Click on the copy icon

Also present in other areas such as copying version info in "Help & About"

#### What did you expect?
"Copied!" message to have padding

#### What happened instead?
![Screenshot from 2022-02-14 12-50-31](https://user-images.githubusercontent.com/51663/153867791-92db131f-8c95-430a-8f46-a0cf7395d1f2.png)

### Browser information

Chromium 98.0.4758.80 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: fa64d65e6e53-react-1c3507bc117a-js-cfad8d361454 Olm version: 3.2.8

**Comment by t3chguy** [comment]
IMO the `Copy` tooltip should just change to `Copied!`, identical styling etc
