### ISSUE TITLE
Allow user to make a new Space in the mobile application

### ISSUE THREAD

**Issue by JeremyShore** [vector-im/element-web#21063]
#### What would you like to do?

I would like to be able to make a new Space (like Home, not just a new chat or new room) in the mobile application. 

#### Why would you like to do it?

This would enhance usability of the app, for I do not always have a computer on hand to make new spaces

#### How would you like to achieve it?

If there is a "+" button on the menu of Spaces, like how there is on the browser, then that would be the most intuitive way to make a new Space.

### Have you considered any alternatives?

Although I could use a Room to make multiple chats, this is would not be practical for a large organized community with sub-groups, for there would be no smaller tier for making small groups in a Room. 

### Additional context

I would make sure that all chat features on the browser (or whatever is best developed features-wise) are working on the mobile app before deploying more features like voice chat or video call (which would be great additions down the road).

**Comment by robintown** [comment]
This is the issue tracker for Element Web, not the mobile apps. Element Android already supports creating spaces, while support for creating spaces on iOS is coming soon.
