### ISSUE TITLE
Threaded messages don't have text event fallback in the event body

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21074]
Under MSC3676 they *should* but are not required to. It'd be best to be a good role model for the ecosystem though

**Comment by t3chguy** [comment]
@turt2live if I'm reading it correctly, it says *should not*

> Thread events using replies as a fallback representation for threads **should not** include a textual reply fallback at all (and so avoid threaded messages triggering notifications). The same would apply for any other usage which uses replies as a fallback.
