### ISSUE TITLE
The abillity to search for messages in all rooms on android

### ISSUE THREAD

**Issue by ufkhf** [vector-im/element-web#21071]
I would the ability to search for messages in all rooms on android. On desktop and on the web app its possible, but i cant find the feature on android.

![image](https://user-images.githubusercontent.com/84050866/153903697-83672a0e-37f5-4a31-9042-222695bc36ca.png)

**Comment by robintown** [comment]
This is the issue tracker for Element Web, not Android (→ https://github.com/vector-im/element-android/issues)
