### ISSUE TITLE
Move e2e test suite over to Cypress

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#21083]
We now have an example e2e test in cypress, lets move all the puppeteer tests over and kill them

**Comment by t3chguy** [comment]
- [x] [Threads tests](https://github.com/matrix-org/matrix-react-sdk/pull/8501)
- [x] [Enterprise Erin tests](https://github.com/matrix-org/matrix-react-sdk/pull/8569)
- [ ] Stickers tests
- [ ] Update cachebuster tests
- [ ] Spaces tests
- [ ] Toasts tests
- [ ] User view tests
- [ ] Room Directory tests
- [ ] E2E Encryption tests
- [ ] Lazy Loading tests

**Comment by weeman1337** [comment]
„E2E Encryption tests → @weeman1337‘ done
