### ISSUE TITLE
Set default values for "Show placeholder for removed messages "and "Show join/leave messages" in config file

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-web#21086]
### Your use case

Users can decide whether they want to see deleted messages, joins and leaves, or disable it.

#### What would you like to do?
I want to be able to change the defaults so that users will not see deleted messages and/or joins and leaves by default.

#### Why would you like to do it?
I want to provide minimal interface to users. I can disable widgets, shareQr and other settings with the config file but not these.

#### How would you like to achieve it?
By having settings such as: 
`"settingDefaults": {
  "showRemovedMessages": false,
  "showJoinsAndLeaves": false
}`

Users that would like to enable it can still do that in Settings -> Preferences.

**Comment by t3chguy** [comment]
It is already possible, try `hideRedactions` or `showRedactions` and `showJoinLeaves` / `hideJoinLeaves` (I don't recall whether the normal or inverted work in config.) https://github.com/matrix-org/matrix-react-sdk/blob/b5e7d12f76ce3f03fd137eae78bf1dfefa252462/src/settings/Settings.tsx#L422-L456

**Comment by SPiRiT369** [comment]
@t3chguy thanks. I missed that in the documentation. But unfortunately I've just tried that and it doesn't seem to work. Also tried it globally (outisde of settingDefaults).

![image](https://user-images.githubusercontent.com/63514368/154047408-397d572f-241b-4285-8e44-03e5b3a4cc12.png)

**Comment by SPiRiT369** [comment]
@t3chguy you were right! 👍 The inverted settings do work! Many thanks for your help. Should I close this issue myself?

![image](https://user-images.githubusercontent.com/63514368/154049461-6ed78f84-bce2-4587-b08d-9bb2b7208853.png)
