### ISSUE TITLE
Add existing space not showing any spaces

### ISSUE THREAD

**Issue by c-cal** [vector-im/element-web#21087]
### Steps to reproduce

- already be a member of spaces and rooms
- create a private space for "Just me"

#### What did you expect?

Show existing spaces in the Spaces section

#### What happened instead?

![image](https://user-images.githubusercontent.com/57274151/153959801-5899233e-9ef8-4d12-be86-0ac9d8b3e0b5.png)

### Operating system

Ubuntu

### Browser information

FF96

### URL for webapp

https://develop.element.io

### Application version

Element version: f14450fdd2d8-react-cfa6e266cda9-js-2bb14698a505

### Will you send logs?

No

**Comment by t3chguy** [comment]
That gap should be filled with the https://github.com/matrix-org/matrix-react-sdk/blob/f6565bfbc806434dafd18a3469ecf82b074488c6/src/components/views/dialogs/AddExistingToSpaceDialog.tsx#L462
