### ISSUE TITLE
Couldn't change account password due to not knowing the password

### ISSUE THREAD

**Issue by zanculmarktum** [vector-im/element-web#21081]
So, I was signing up the matrix via GitHub, unfortunately the GitHub method didn't ask me for a matrix password.

Now, that I'm about to change my account password through element-web it's not possible since I don't know the current password.

![shot](https://user-images.githubusercontent.com/16958511/153924253-2c9b3f7d-5f38-4359-9967-d4a7cc651d92.png)

**Comment by t3chguy** [comment]
This is a bug with Synapse - https://github.com/matrix-org/synapse/issues/11944
