### ISSUE TITLE
New Search: Add button to go back to the search window from Explore Rooms

### ISSUE THREAD

**Issue by onkq** [vector-im/element-web#21103]
#### What would you like to do?
Go back to previous window from Explore Rooms.
#### Why would you like to do it?
If I missclick. Or wanna go back to search instead of closing the window and then reopening search again. It's annoying when u don't have a back button.
#### How would you like to achieve it?
Create a back button on the other side of the X button.

### Have you considered any alternatives?

No need to

### Additional context

![Peek 2022-02-16 17-10](https://user-images.githubusercontent.com/84337276/154307303-55027fae-d8ef-43e8-9556-d0902723ef9e.gif)

**Comment by niquewoodhouse** [comment]
Just adding this as a quick non-comprehensive design thought:

What if public searching was part of the beta dialog?

https://user-images.githubusercontent.com/1587166/154984547-4868a72f-22db-4779-8ae4-fc8c5ae9fef8.mov

Would be interested in some your input @t3chguy - eg effort/feasibility anything you think I'm being blind to? Thanks

**Comment by t3chguy** [comment]
@niquewoodhouse should be achievable, effort estimated in the low single digit days

**Comment by bkil** [comment]
Somewhat related: #21288

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21354
