### ISSUE TITLE
Messages referencing old threads don't update badge count

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#21100]
### Steps to reproduce

Moving this out to its own issue: discovered whilst debugging https://github.com/vector-im/element-web/issues/20859

 1. Have clients A and B who share a room (room 1) with nobody else. Have another room on A too (room 2)
 1. Send enough messages from B into room 1 to overflow the initial sync amount (30 ought to do it)
 1. Switch to room 2 to client A
 1. Clear cache & reload on A
 1. Send a threaded reply from B to the earliest of the ~30 messages you sent
 1. Observe that A makes the notification sound but no badge appears.

#### What did you expect?
Notification bubble on client A

#### What happened instead?
No notification bubble

### Will you send logs?

No

**Comment by t3chguy** [comment]
This will have been an issue with degraded mode which we are not considering for long term support.

**Comment by gsouquet** [comment]
Given that we're planning to rework notifications and want it to be driven by the server, this probably falls out of scope of what clients are responsible for.
