### ISSUE TITLE
Poll votes increment the message counter in room list

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#21115]
#### What would you like to do?

I turned on noisy notifications in a few low traffic rooms, for which I want to be pinged whenever there's a new message.
If someone posts a poll there and that room is not my active one (i.e. I'm looking at another room), the messages counter in the room list is incremented each time someone votes.

This is unsettling, because when I switch back to this room, I don't see any new message. I would find it more intuitive if votes were excluded from the new messages counter.

#### Why would you like to do it?

I want to keep low traffic rooms with noisy notifications on so I don't miss anything important

### Additional context

Element and Olm version:

```
Element Nightly version: 2022021701
Olm version: 3.2.8
```

**Comment by kittykat** [comment]
To throw my 2c in: as a poll creator, I want to monitor votes, so it would be handy to have notifications as the owner

But I also don't want to be notified about votes on other people's polls

**Comment by robintown** [comment]
Related to https://github.com/vector-im/element-web/issues/7941

**Comment by turt2live** [comment]
Related https://github.com/vector-im/element-web/issues/12063

**Comment by turt2live** [comment]
This requires spec changes as it's controlled by a push rule, for better or worse. This would require https://github.com/matrix-org/matrix-spec/issues/1065 or similar.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22234
