### ISSUE TITLE
Deleted poll does not show "Message deleted" message

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21125]
### Steps to reproduce
1. Create a poll
2. Remove it

#### What did you expect?
I expected to see "Message deleted" or similar.

#### What happened instead?
The poll disappears and there is no message.

![2022-02-19 23-00-54](https://user-images.githubusercontent.com/76812/154950279-6fe68650-c53e-4a4d-a907-d647c76757d8.gif)

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
The reporter will upload a video when they have time.

**Comment by xncz8h** [comment]
I tried to replicate this bug, however for me it works fine. Replicated it on element-web and element-desktop on windows and Chrome.

**Comment by xncz8h** [comment]
Hey there, I've been playing around with this a bit and it seems like the problem is only happening in unencrypted rooms. However, it does behave correctly in encrypted rooms.

**Comment by t3chguy** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/blob/d50dae52082a09d9b640a8ab6935e7314fcd1e14/src/components/views/rooms/EventTile.tsx#L1664-L1673 not considering polls
