### ISSUE TITLE
UI freezes for multiple seconds

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21127]
### Steps to reproduce

Haven't managed to consistently reproduce the issue.
Also experienced by @novocaine and @turt2live today

#### What did you expect?

A smooth 60fps rendering

#### What happened instead?

UI is frozen for multiple seconds

### Will you send logs?

No

**Comment by andybalaam** [comment]
I just saw my UI freeze and I had to refresh to get back to a usable system.
Ubuntu 21.10
Firefox 64.0
https://develop.element.io
It happened when I entered the Dendrite room.

**Comment by andybalaam** [comment]
This just happened to me again.  I'll keep the tab around in case I can debug or something.

**Comment by andybalaam** [comment]
I opened a new tab on develop.element.io and it immediately froze too, which might be a helpful data point?

**Comment by dbkr** [comment]
I can still repro this with the new nightly build It looks like might be a few more places that need throttling, although the profile on nightly isn't letting me click through to the source so I can't easily see where:

<img width="1137" alt="Screenshot 2022-02-22 at 18 11 46" src="https://user-images.githubusercontent.com/986903/155193377-076f4031-18cd-48b7-a07e-78ef8cd8598a.png">

**Comment by andybalaam** [comment]
I got this again just now on develop.element.io. Trying to rageshake.

**Comment by andybalaam** [comment]
Managed to capture a profile of another freeze:
[freeze-opening-room.json.gz](https://github.com/vector-im/element-web/files/8124844/freeze-opening-room.json.gz)

**Comment by andybalaam** [comment]
Another profile - I think this one is better:
[profile-freeze-3mins.json.gz](https://github.com/vector-im/element-web/files/8124885/profile-freeze-3mins.json.gz)

My UI froze for 3 minutes, and the profiler was started before it happened.

**Comment by andybalaam** [comment]
![image](https://user-images.githubusercontent.com/76812/155335481-29b2bb1f-1974-4a06-ba66-4779ca04e70a.png)

**Comment by andybalaam** [comment]
![image](https://user-images.githubusercontent.com/76812/155335727-bb206d91-4b41-4604-a815-61f9e5892027.png)

**Comment by andybalaam** [comment]
![image](https://user-images.githubusercontent.com/76812/155335866-a7919297-9ff3-4ee1-8470-1faeedcf3bb2.png)

**Comment by HarHarLinks** [comment]
I think I hit this on desktop. Submitted a rageshake with this issue as target.

**Comment by dbkr** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7816 which turned on the event handler which was just sitting there doing nothing before because the listener was on the wrong object.

**Comment by dbkr** [comment]
...and reopening. It's better, but still pauses for somewhere between 6s and 2 mins due to `updateHighestPlUser`. I can do the same throttling to this but the onMember for permalinks still takes a bit of time which could be a 10 second pause. Feels like we need a better solution, eg. using the new batch event.
