### ISSUE TITLE
Hovering over a pill avatar shows two tooltips

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21135]
### Steps to reproduce

1. Mention someone
2. Hover over the pill's avatar

### Outcome

![tooltips](https://user-images.githubusercontent.com/48614497/154856051-1d0ea593-fc93-4d78-822b-5d62605d1996.png)

#### What did you expect?

There should be only one tooltip.

#### What happened instead?

There are two different tooltips showing me the same information.

### Operating system

NixOS unstable

### Browser information

Firefox 96.0.3

### URL for webapp

develop.element.io

### Application version

Element version: a01684e126e6-react-fc9a2213715a-js-7a7318b636b7 Olm version: 3.2.8

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
One is an Element tooltip, the other is from your browser

We can probably inhibit mouse events on the avatar there
