### ISSUE TITLE
New room takes too long to be created

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21143]
### Steps to reproduce

1. In the left panel, click + next to the People section
2. In the "Direct Messages" dialog, add two users to start a three way DM
3. "Go" to start the DM

See creation of room `!RKRzVogjnVpVWYLVSZ:matrix.org` in the rageshake

#### What did you expect?
I can send a message to the new room quickly

#### What happened instead?
The "Joining room" spinner stuck around for about 30 seconds before I could access the new room

### Browser information

Chromium 98.0.4758.80 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: a01684e126e6-react-e2827b40825c-js-a89c1990d6f2 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@kittykat would https://github.com/vector-im/element-web/issues/14736 be a solution to this for you? If not then its really a Synapse performance issue

**Comment by kittykat** [comment]
@t3chguy yes, it does. I would be happy if I'm not blocking on the UI to get my messages sent before moving on

**Comment by t3chguy** [comment]
Closing in favour of #14736 as a proposed solution
