### ISSUE TITLE
Message redacted placeholder is indented for the first message

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21149]
1. Send 2 messages
2. Redact both messages
3. The first placeholder will be indented too far

**Comment by t3chguy** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/2403652/155041403-afabf885-1fb7-4ded-80ce-65e5defb7234.png">

**Comment by t3chguy** [comment]
Regressed by 2160fd81c2b879e8e24830298d5eca37d45e7eee
