### ISSUE TITLE
Searching for a specific word with a french accent in a specific room brings up the message "Something went wrong"

### ISSUE THREAD

**Issue by mdxe** [vector-im/element-web#21150]
### Steps to reproduce

1. Click search button in a specific room
2. search for French word with acute accent
3. error message appears...

#### What did you expect?

search results

#### What happened instead?

Something went wrong!
Please [create a new issue](https://github.com/vector-im/element-web/issues/new/choose) on GitHub so that we can investigate this bug.

### Operating system

Arch Linux

### Application version

Element version: 1.10.4 Olm version: 3.2.8

### How did you install the app?

pacman

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by mdxe** [comment]
Note: The same search in a different room doesn't trigger the bug.

**Comment by SimonBrandner** [comment]
Is the room encrypted?

**Comment by mdxe** [comment]
yes

**Comment by mdxe** [comment]
yes it is encrypted

**Comment by t3chguy** [comment]
This happens when the search result's context includes a call event, PR incoming

**Comment by t3chguy** [comment]
(lets not ship another release with this bug please)
