### ISSUE TITLE
New invite did not add a badge to the space sidebar

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21157]
### Steps to reproduce

1. Receive a new room/DM invite

#### What did you expect?

To receive a bing and the space sidebar to display a badge

#### What happened instead?

Received a bing, the notification counter of the dock increased by one, but the space badges did not appear

<img width="496" alt="Screen Shot 2022-02-22 at 11 22 41" src="https://user-images.githubusercontent.com/769871/155123265-30699170-633b-46eb-bb93-6d2d7a3f8b37.png">

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/20381
