### ISSUE TITLE
New search prioritises IDs over names

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#21156]
### Steps to reproduce

1. Be joined to the "matrix.org website" room and have DMs with several matrix.org users
2. Search for "matrix.org" in the new search UI

#### What did you expect?

Since there's a match on a room's name, show that room first.

#### What happened instead?

I can only see DMs I have with people on matrix.org:

![image](https://user-images.githubusercontent.com/5547783/155115095-85c88cbd-3abe-457a-a5a0-66046082f905.png)

I feel like it would be more natural to at least prioritise matches on users' display names or rooms' names to matches on the technical ID that non-technical users aren't really supposed to care about.

### Operating system

Arch Linux

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: a01684e126e6-react-e2827b40825c-js-a89c1990d6f2, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
It doesn't prioritise anything, there is no sorting at all.

Closing in favour of https://github.com/vector-im/element-web/issues/20635
