### ISSUE TITLE
Cannot run Element as another user

### ISSUE THREAD

**Issue by Scorpion2185** [vector-im/element-web#21167]
### Steps to reproduce

When I try to run Element as another user with `pkexec` I can't:
```
pkexec --user <user> env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY flatpak run im.riot.Riot
[2 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[2 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus

```

### Outcome

I expected to don't have problems.
But something is wrong.

### Operating system

Debian 11

### Application version

Version 1.9.4

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Can you reproduce this with a first party package from https://element.io/get-started - curious as to whether its an issue specific to the community-maintained flatpak package

**Comment by Scorpion2185** [comment]
I installed `element-desktop_1.10.4_amd64.deb` and it works.
