### ISSUE TITLE
Ticking a checkbox causes another checkbox to change its state

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21163]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I've opened Sidebar settings.
2. What do you click?
 -I start clicking metaspace checkboxes one by one.
3. More steps…
 -After a while, clicking on one checkbox seems to change the state of another checkbox.
 -The faster I click on different checkboxes, the more I can observe this strange behaviour

https://user-images.githubusercontent.com/18530109/155171330-0810ee8e-6199-43f3-9496-6f63ec9e1b24.mp4

#### What did you expect?
Clicking a checkbox causes its state to change.
Clicking on one checkbox doesn't affect the other.

#### What happened instead?
Clicking on one checkbox causes the other to change.

Initially observed on Desktop Nightly but also reproducible on Element Desktop, as well as develop.element.io.

### Operating system

Windows 10 Home

### Application version

Element Nightly version: 0.0.1-nightly.2022022001 Olm version: 3.2.8

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Race condition with settings local echo
