### ISSUE TITLE
Glitch in the Thread Panel - message repeated multiple times 

### ISSUE THREAD

**Issue by tmissoni** [vector-im/element-web#21164]
### Steps to reproduce

I wrote a message on the VOIP room and then I clicked the thread button to follow up with another message as a thread. Right pane opens automatically and shows multiple time the first thread message.
Changing room and coming back to the thread, solved the issue.
<img width="1044" alt="Screenshot 2022-02-22 at 17 31 07" src="https://user-images.githubusercontent.com/63042679/155181132-c73ce20f-51a9-41fd-be95-aadbecbd459d.png">

I tried to reproduce the issue on the Thread room and it looks like it is reproducible.

<img width="1036" alt="Screenshot 2022-02-22 at 18 01 31" src="https://user-images.githubusercontent.com/63042679/155181353-fcb2578f-f3ff-4335-af30-a6229a157ff5.png">

### Operating system

macOS

### Application version

Element Nightly version: 2022020901 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

---

 - copy
 - multiple
 - local echo

**Comment by gsouquet** [comment]
@tmissoni Are you still experiencing this issue? I tried to reproduce it this morning and could not get the app in this state

**Comment by tmissoni** [comment]
@gsouquet Yes, still there
<img width="828" alt="Screenshot 2022-03-08 at 15 31 18" src="https://user-images.githubusercontent.com/63042679/157258616-2c12132f-63b7-4498-9fc5-bf0b3e515de9.png">

**Comment by gsouquet** [comment]
Steps to reproduce from @tmissoni 

> so, I enter e message in the timeline and right after I want to post a reply as a thread. So I click on the thread button and when the thread panel opens I get those repetition of the initial message
this does not happen if you already have the thread panel open

**Comment by novocaine** [comment]
This is from an ancient version of Element (2022-02-09). Can you please upgrade to latest and try again @tmissoni ? And be advised using old nightlies is a very bad idea..

Element Nightly version: 2022020901 Olm version: 3.2.8

**Comment by novocaine** [comment]
[this repro](https://github.com/vector-im/element-web/issues/21164#issuecomment-1061840096) is from 2022030801 so guess that's not the issue

**Comment by gsouquet** [comment]
After talking with @tmissoni he was not able to reproduce this issue anymore.
Feel free to re-open it if we spot it in the wild again
