### ISSUE TITLE
Can't browse rooms of a space

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21170]
Server says invalid parameter, which is correct because it's `undefined` but present in the query string

**Comment by gsouquet** [comment]
@turt2live could you fill in the issue template, it's missing key information to be able to reproduce the issue here

**Comment by turt2live** [comment]
The steps are pretty minimal, so was hoping it'd be covered by the title:

1. Explore rooms of a space
2. Note error

**Comment by SimonBrandner** [comment]
Happens on develop.element.io
