### ISSUE TITLE
Threads: Upload file via composer in Thread panel doesn't upload file

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21175]
### Steps to reproduce

1. Where are you starting? What can you see?
Open thread panel > click 3 dots in composer > select upload file > choose file > nothing happens (more options is visible)

#### What did you expect?
file uploads

#### What happened instead?
nothing happens (more options is visible)

### Application version

Develop on Chrome and Safari

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
@janogarcia also tested

**Comment by janogarcia** [comment]
Yeah, tested it on develop `Element version: 3810b7e3297d-react-5e76d988ca53-js-2128f67dc344
Olm version: 3.2.8`, on macOS Safari and Chrome.

**Comment by gsouquet** [comment]
Might be related to https://github.com/matrix-org/matrix-react-sdk/pull/7860

**Comment by t3chguy** [comment]
Also affects the narrow main timeline composer
