### ISSUE TITLE
Client without closed poll support can see other's votes after voting before ending the poll

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21176]
### Steps to reproduce

1. with nightly 20220223 send a closed poll
2. answer yourself
3. with stable 1.10.4 answer the poll

#### What did you expect?
stable can't see other's answers since the poll is closed

#### What happened instead?
can see answers as if it was an open poll

### Operating system

arch

### Application version

Element Nightly version: 2022022301 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.52.0

### Will you send logs?

No

**Comment by andybalaam** [comment]
I think there is no fix for this other than to upgrade the client. Polls being "closed" is a client feature, similar to votes being hidden before you vote.

**Comment by andybalaam** [comment]
Good point - would you be prepared to make an issue explaining this?
