### ISSUE TITLE
UI locks up when answering a VoIP call

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21181]
### Steps to reproduce

1. Answer a VoIP call 

#### What did you expect?

To chat with the person calling me

#### What happened instead?

UI locked up for more than 1 minute

<img width="1069" alt="Screen Shot 2022-02-23 at 14 45 27" src="https://user-images.githubusercontent.com/769871/155349762-22762c4d-a15f-46c3-aa78-3d3b8fcc299e.png">
<img width="390" alt="Screen Shot 2022-02-23 at 14 46 11" src="https://user-images.githubusercontent.com/769871/155349821-7bc24803-d3f1-4a2b-8790-998f8c2bead9.png">

### Will you send logs?

No

**Comment by dbkr** [comment]
I can only repo this very sporadically :/

**Comment by HarHarLinks** [comment]
I've had my UI freeze for a couple seconds during a voice call on Thu 2022-02-17 if that might help bisecting

**Comment by dbkr** [comment]
I'm going to assume this is inexplicably fixed now...

**Comment by novocaine** [comment]
reopening as @neilisfragile still reporting this

**Comment by novocaine** [comment]
not sure if https://github.com/vector-im/element-web/issues/21181 is related

**Comment by dbkr** [comment]
@gsouquet are you still able to repro this?

**Comment by HarHarLinks** [comment]
possibly also #21278

**Comment by neilisfragile** [comment]
I can reproduce this consistently, would it be helpful to produce some up to date rage shakes?

One thing that seems significant is that when I initiate a call there is a pop up that tells me that I am already in a call with this person.

**Comment by dbkr** [comment]
That does seem like it could be relevant, yeah - I'm not certain that rageshakes will be helpful but could certainly be worth a try.
