### ISSUE TITLE
Changing the formatting of a word when editing a message jumps the cursor to the end of the text

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#21183]
### Steps to reproduce

1. edit a message containing multiple words
2. highlight a word somewhere in the middle
3. click _i_ to italicise it
4. observe: your cursor is now at the end of the text input field

#### What did you expect?
I expected the cursor not to be _anywhere_, like the main composer when you use the UX to change the formatting of a word

#### What happened instead?
The cursor jumped to the end of the text input field

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022022201 Olm version: 3.2.8

### How did you install the app?

website

### Homeserver

lant.uk

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot reproduce on Element Nightly or develop on FF

https://user-images.githubusercontent.com/2403652/155556828-5e4ddbb3-d79a-42bf-a245-8ef3934ccadf.mov

**Comment by turt2live** [comment]
also tried on Windows, can't reproduce.

**Comment by lampholder** [comment]
Agreed, I can't reproduce it now either.
