### ISSUE TITLE
How long are Etherpads kept?

### ISSUE THREAD

**Issue by colans** [vector-im/element-web#21186]
How long do Etherpads stick around, the ones that are created in in the app via a widget?  Do they expire after a period of time of inactivity?

We've been using https://pad.riseup.net/, but would like to switch to doing it in here if we can figure out the rules.  The rules over there are:

* https://pad.riseup.net/p/1234-tmp => deleted after 1 day of inactivity
* https://pad.riseup.net/p/1234 => deleted after 60 days of inactivity
* https://pad.riseup.net/p/1234-keep => deleted after 365 days of inactivity

How does it work here given that it's not possible to set the URLs?

I asked in [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org), but didn't get a response.

**Comment by gsouquet** [comment]
This issue tracker is not really for support requests, [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) could help, you can alternatively head to [#ems:matrix.org](https://matrix.to/#/#ems:matrix.org) where folks might be able to answer your question
