### ISSUE TITLE
Invites succeed but spinner doesn't go away

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21192]
### Steps to reproduce

1. Invite someone to a room
2. See it succeed in the room in the background, but the invite dialog doesn't close and the spinner spins

This is seemingly happening to all my invites now

#### What did you expect?

The dialog to disappear once they were invited

#### What happened instead?

The spinner spins

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Element Nightly version: 2022022301 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Wasn't able to reproduce but the dialog took ~2mn to close
A lot of `encryptMessages` call happening in the background

**Comment by t3chguy** [comment]
Yeah so right now the dialog blocks on sharing e2ee keys for the entire accessible history, perhaps it should be done int he background but then we need a way to surface/swallow errors

**Comment by t3chguy** [comment]
Well it scales with size of history of room and number of unique device permutations ever in the room, so some rooms will be much slower than others. The perf of each individual keyshare may or may not have changed but could even be a server perf manifestation

**Comment by t3chguy** [comment]
That sounds like it's busy sharing keys if the logs are still going

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7655
