### ISSUE TITLE
Various state event alignment regressions in right panel timeline

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#21212]
### Steps to reproduce

1. Start a new room so the "created and configured" grouped line is accessible for testing
2. Send a few ungrouped state events, such as adding widgets
3. Maximise a widget so that the right panel timeline is displayed

#### What did you expect?

State event summaries should be aligned with the rest of timeline and use reasonable padding, as they have in previous versions.

#### What happened instead?

Release branch screenshot:

<img src="https://user-images.githubusercontent.com/279572/155738063-ecee0df6-9b64-4709-bc52-e9e43a2ac0e2.png" width="50%">

* "Created and configured" grouped line fails to override padding because of class name change in https://github.com/matrix-org/matrix-react-sdk/pull/7739
* Ungrouped widget events fail to override padding because `!important` was used in https://github.com/matrix-org/matrix-react-sdk/pull/7891

Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7739
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7891

### Operating system

macOS

### Browser information

Firefox 99

### URL for webapp

Local server

### Application version

React SDK branch release-v3.41.0 (43d3f6c00493e13ca984fa68b25c1e1273f58540)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
Does this affect current staging? Looks like one issue does but one doesn't?

**Comment by jryans** [comment]
@dbkr Well, it "doesn't" affect staging, but that's only because it requires the last commit on the release branch which hasn't been deployed to staging. The release branch **is** affected.

**Comment by jryans** [comment]
Both regressing PRs are new in this release I believe:

* https://github.com/matrix-org/matrix-react-sdk/commit/714136d4f77cb2e7e2c7c2c81dd9e4aedc14f6ea
* https://github.com/matrix-org/matrix-react-sdk/commit/43d3f6c00493e13ca984fa68b25c1e1273f58540
