### ISSUE TITLE
Can't enable threads

### ISSUE THREAD

**Issue by stonewalljones** [vector-im/element-web#21237]
### Steps to reproduce

I'm unable to find how to enable threads in Element Desktop on windows. 

I've looked through all of the settings and I'm unable to find a place to enable threads. 

It is specially not show to me in the Labs tab of settings like on mobile.

### Outcome

No way to enable Threads

### Operating system

Windows 10 21H2

### Application version

Element version: 1.10.5 Olm version: 3.2.8

### How did you install the app?

Choco

### Homeserver

Synpase 1.53.0+buster1 non-public

### Will you send logs?

no

**Comment by reynoldsme** [comment]
@stonewalljones The majority of labs features are hidden by default and you need to create or edit a config file to show them in the Element labs settings.

I don't know if installing via choco will change your default config location, but have a look at https://github.com/vector-im/element-desktop#user-specified-configjson 
You need to create a file called `config.json` in the correct location and add the following contents.

```
{
"showLabsSettings": true
}
```

**Comment by stonewalljones** [comment]
That was it than you.

**Comment by robintown** [comment]
Closing as resolved, then
