### ISSUE TITLE
Render local Seshat View when selecting an E2E Search Result

### ISSUE THREAD

**Issue by dylangerdaly** [vector-im/element-web#21230]
#### What would you like to do?
View the seshat search index in a nice UI/UX
#### Why would you like to do it?
Currently it's possible to search encrypted rooms via Seshat, however if you click on a result it'll request the actual message, I'd prefer if I was dropped into a local seshat view.

#### How would you like to achieve it?
Instead of jumping to the event, render a localized view of the Seshat Search Index.

**Comment by dbkr** [comment]
I'm afraid I don't understand what this is asking for at all. What is a "local Seshat View"?

**Comment by dylangerdaly** [comment]
That's fair enough, do you know if there's an internal way to view just the raw Seshat index? Outside of sqlchipher?

-------- Original Message --------

**Comment by t3chguy** [comment]
No, you're better off asking https://matrix.to/#/!VYQqtuzngcvIzsyyOV:matrix.org?via=matrix.org&via=t2l.io&via=t2bot.io as linked in Seshat's README.

**Comment by bwindels** [comment]
Thanks for report. I'll be closing this, as this doesn't seem to be a feature we want in Element.
