### ISSUE TITLE
Various rooms seem to repeat chains of state events and read receipts

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#21245]
### Steps to reproduce

1. Look at some rooms, perhaps scroll up a bit (I am not quite sure what it takes)

#### What did you expect?

State events and read receipts should only appear in one place in the timeline. Event level "..." menus should open when clicked.

#### What happened instead?

As seen below, some state events seem to repeat in a loop, as well as read receipts down the side. Also, the "..." menu on the state events does not want to open.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/279572/156151985-50ad1f52-13cb-4d94-aa6e-c3619c6247ba.png">

### Operating system

macOS

### Browser information

Firefox 99

### URL for webapp

develop.element.io

### Application version

Element version: de9e65de2b18-react-36adba101caf-js-54e815085f4d, Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Possibly a Synapse/matrix.org issue.

**Comment by robintown** [comment]
Could be related to https://github.com/matrix-org/matrix-react-sdk/pull/7915 ?

**Comment by t3chguy** [comment]
Unlikely as that only governs what `key` to cache-bust React using, it should never be possible for that to result in multiple renders

**Comment by jryans** [comment]
I haven't seen at all after this morning, so perhaps something server-side indeed.
