### ISSUE TITLE
Waking up a session didn't work.

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#21247]
### Steps to reproduce

On Firefox 97.0 (64-bits) on Ubuntu 20.04, I opened https://app.element.io in a new tab.  That was supposed to open my running session, but instead I got an error message with the request to create an issue, and send the log to it.
I'll click the button offered for that as soon as I have created this issue, and know its number.

### Outcome

That was supposed to open my running session, but instead I got an error message with the request to create an issue, and send the log to it.

### Operating system

Ubuntu 20.04

### Browser information

Firefox 97.0 (64-bits)

### URL for webapp

https://app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is fixed in the next release
