### ISSUE TITLE
Translation files appear to be requested twice on app startup

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21254]
Unclear where the calls are happening, but presumably it's not a good thing if we ask twice. Found during development of https://github.com/matrix-org/matrix-react-sdk/pull/7886 (uninvestigated).

**Comment by t3chguy** [comment]
This seems to have been fixed

![image](https://user-images.githubusercontent.com/2403652/176667528-52672d51-1a91-4021-b9ce-8dda6132bcd1.png)
