### ISSUE TITLE
Animated GIF avatar causes annoying left panel background

### ISSUE THREAD

**Issue by JeremyMahieu** [vector-im/element-web#21250]
### Steps to reproduce

Have an animated gif avatar. Pick any.
![thumb-1920-92879](https://user-images.githubusercontent.com/23409814/156190469-94ef8405-c208-4db0-a955-65d3c4055d7b.gif)

#### What did you expect?
Didn't expect he left panel background to have something to do with the avatar

#### What happened instead?
The left panel background is a heavily blurred piece of the avatar, so animated gif avatars cause an annoying UI.

https://user-images.githubusercontent.com/23409814/156190422-d1d39198-f025-4815-991a-20a073d0060d.mp4

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14665
