### ISSUE TITLE
Can no longer force non-https schemes in custom server picker

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21253]
for localhost dev this is important. Should be able to change the server on the login page to `http://localhost:port` without issue. Workaround is to use a local element with config.json

**Comment by t3chguy** [comment]
Works fine for me, cannot reproduce

<img width="739" alt="image" src="https://user-images.githubusercontent.com/2403652/156209822-f2c4b471-572b-4235-8bd1-d1933cdf7d3a.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/2403652/156209846-e6599023-8005-45df-9d94-1158e764c921.png">

**Comment by turt2live** [comment]
I can reproduce this on develop.element.io but not app.element.io

for context, @t3chguy's test is a webpack-dev-server

**Comment by clokep** [comment]
> I can reproduce this on develop.element.io but not app.element.io

Correct, app.element.io and staging.element.io work fine. Only develop.element.io is broken.

**Comment by t3chguy** [comment]
Due to **INSANE** fragility, https://github.com/matrix-org/matrix-react-sdk/pull/7816 caused the browser-request module to get subbed out for node's `request` module which has ever so slightly different behaviour, causing this bug and also https://github.com/vector-im/element-web/issues/21170

**Comment by clokep** [comment]
I can confirm this is working again. Thank you for the quick fix @t3chguy!

**Comment by fariszr** [comment]
![image](https://user-images.githubusercontent.com/35614734/157535130-c605771e-542b-4429-abad-ff9f819021c0.png)
this still doesn't work on app.element.io

**Comment by turt2live** [comment]
The fix is due to go out on Monday - we close issues ahead of the formal release.
