### ISSUE TITLE
Margins on room header encryption tooltips are inexplicably large

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#21270]
### Your use case

See:

<img width="315" alt="Screenshot 2022-03-02 at 13 37 43" src="https://user-images.githubusercontent.com/4626865/156372356-a18fc5e8-083e-4972-8157-2079ed97e8f9.png">

Should be consistent with other tooltips:

<img width="398" alt="Screenshot 2022-03-02 at 13 38 04" src="https://user-images.githubusercontent.com/4626865/156372449-86e121a1-3c3c-4ec5-aeb8-7c562bd2edb1.png">

@niquewoodhouse did this come up when making adjustments to the room header layouts in IA?

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse did this come up when making adjustments to the room header layouts in IA?

Didn't come up, we were just adding a chevron next to the name and a menu that appears.  Nothing further has been looked at yet

**Comment by xncz8h** [comment]
I would like to work on this issue

**Comment by dbkr** [comment]
I think this seems well scoped enough that it doesn't need input from design before someone could write a PR for it.
