### ISSUE TITLE
DM Invite did not change the badge count & color on space sidebar

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21276]
### Steps to reproduce

1. Disable "show all rooms" on your home space
2. Have a space in common with the user that is going to invite you
3. Receive an invite from said user 

#### What did you expect?

For the badge counter to increase by one, and for the badge color to turn red and to get binged

#### What happened instead?

I got binged, but because I was viewing another space that I do not share with that user, I did not see their invite until I viewed the home space

### Will you send logs?

No

**Comment by t3chguy** [comment]
Badge counts for DMs are specifically omitted from spaces, regardless of whether they are invites or not, as you often share multiple spaces with a given party and having lots of unread badges was noisy.

**Comment by t3chguy** [comment]
> I got binged, but because I was viewing another space that I do not share with that user, I did not see their invite until I viewed the home space

Did you not see the invite badge on Home/People either?

**Comment by gsouquet** [comment]
Yeah the home space showed 1 unread grey notification (from an existing room). The People space remained badge-less

**Comment by turt2live** [comment]
I have the same issue, but did not have a badge on the Home space. The DM invite was completely silent until I accidentally ran across it.

**Comment by t3chguy** [comment]
So this is currently working "as intended" because Home shows invites regardless of any preferences.
Right now the rule is to only show DM notifications in the Space Panel on the Home or People metaspaces, never on the actual Spaces given that a user (and thus that DM) may be in multiple real spaces, and it can get really messy

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20381
