### ISSUE TITLE
Freeze when switching room during call

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21278]
### Steps to reproduce

1. Have a 1:1 native e2ee call
2. switch to another room whether it's in the space or not

#### What did you expect?
no freeze

#### What happened instead?
1-3 seconds freeze

This happened to me for the first time on 2022-02-17.

### Operating system

arch

### Application version

Element Nightly version: 2022030201 Olm version: 3.2.8

### How did you install the app?

aur nightly

### Homeserver

1.52

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Given very similar symptoms to https://github.com/vector-im/element-web/issues/21181, let's close this issue in favour of the other one
