### ISSUE TITLE
Increase visible characters in room names in "Recently viewed" in the new search

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21285]
User research and feedback indicate that people want to see more of the room name in the Recently viewed breadcrumbs in the new search experience. [Straw poll](https://matrix.to/#/!CMjQWAjoxImKwLBMzX:matrix.org/$qWtmApw7y0DwYVVqKad1tncG1EHxiu-i6EJZJrGUsB0?via=matrix.org&via=element.io&via=one.ems.host) during user research indicates that most users would like to see 9-10 characters

## Acceptance criteria

- [x] Prototype:
  - Show 9 characters of the Room/DM name followed by ellipsis. E.g. `Matrix Co…` instead of `Matri…`
  - Increase avatar size as needed (@niquewoodhouse )
- [ ] Design product to review build and sign off

**Comment by niquewoodhouse** [comment]
Here's a [Figma](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=105%3A16479):

- [ ] Character limit in recently viewed increased to 8 characters*
- [ ] Avatars in results increased to 24px

* I realise the most popular suggestion was 9-10 characters in the straw poll but it was a very small sample size of, likely, a particular persona so I'm a little reluctant to just proceed directly with that suggestion fully as it will impact people we've not heard from (eg - the more characters, the less recently viewed rooms you'll see and this might impact the effectiveness of the area).  So I'd suggest starting with less than 9.

**Comment by t3chguy** [comment]
@kittykat this isn't a character limit, this is just making the components larger

Characters in non-monospaced fonts are variable width, e.g

lllllllllllllllllllllllllllllll 31 chars
WWWWWWWW 8 chars

yet take up very similar amount of width.

I think throwing around the term "character limit" is causing undue confusion

**Comment by kittykat** [comment]
@niquewoodhouse could you please suggest pixel width rather than character number for the room names?

**Comment by niquewoodhouse** [comment]
@t3chguy I'd like to try this please:

Max width is 58px. 
<img width="154" alt="image" src="https://user-images.githubusercontent.com/1587166/157630677-98d1e30b-2397-497f-9406-c9b098e8a670.png">

The 57 height is a bit random, it's coming from the line height of the text component in Figma, I'm not especially bothered if that changes as we're in beta.

[Figma link](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=105%3A16479)
