### ISSUE TITLE
SVGs are broken in Element Desktop

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#21293]
![image](https://user-images.githubusercontent.com/2403652/156586808-99f5d4bd-50b8-4a94-8a0a-7b360f6eecff.png)
![image](https://user-images.githubusercontent.com/2403652/156586825-6a84fa6b-8fe6-4cf7-b5a0-d000889a414b.png)
![image](https://user-images.githubusercontent.com/2403652/156586840-24e56fb6-9ae7-4907-b481-ccd35d819043.png)

**Comment by t3chguy** [comment]
Not fixed 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/2403652/156744329-ea46c257-c985-4110-a55a-cf39b490116e.png">

**Comment by kerryarchibald** [comment]
Looks good in Element Nightly version: 2022030402
css:
<img width="192" alt="Screenshot 2022-03-04 at 18 01 32" src="https://user-images.githubusercontent.com/3055605/156807011-97499470-7ee2-4242-9432-3c1d8e2231a5.png">
react component:
<img width="229" alt="Screenshot 2022-03-04 at 18 01 28" src="https://user-images.githubusercontent.com/3055605/156807016-ec8f3ffc-939c-4ed7-87a7-9c2743ed684b.png">
inline require
<img width="195" alt="Screenshot 2022-03-04 at 18 01 20" src="https://user-images.githubusercontent.com/3055605/156807020-dbc3b042-72dd-48d2-bdc6-25adb7fdbc6f.png">
