### ISSUE TITLE
Webpack shouldn't compile if there's TypeScript errors

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21298]
As a build step, it doesn't make sense that the project 'builds' when it'll fail typechecking

**Comment by ankur12-1610** [comment]
Can I work on this issue, it is an interesting one :')

**Comment by ankur12-1610** [comment]
@turt2live there's one question that arrived in my mind: there are already typescript errors in the codebase but the webpack still compiles, and to solve this issue first of all we need to solve all the typescript errors. Am I right?

**Comment by t3chguy** [comment]
@ankur12-1610 looks like you need to clean your yarn cache and reinstall to fix the dependency. `yarn clean && yarn install --foce`

**Comment by ankur12-1610** [comment]
> yarn clean && yarn install --force

@t3chguy I tried but I get the same type check errors :cry: 

Also, I tried several typecheck configs, for this I referred to; https://www.typescriptlang.org/tsconfig#:~:text=%22compilerOptions%22-,Type%20Checking,useUnknownInCatchVariables,-Modules but didn't work.

@turt2live @t3chguy can you please help?

**Comment by turt2live** [comment]
Diagnosing your issue would be best in the #element-dev:matrix.org room.

**Comment by ankur12-1610** [comment]
> Diagnosing your issue would be best in the #element-dev:matrix.org room.

Sure, I'll start this discussion over there.

**Comment by t3chguy** [comment]
Closing as this is intentional in babel-typescript
