### ISSUE TITLE
Crashing -  dendrite sending a null conditions like in spec

### ISSUE THREAD

**Issue by genofire** [vector-im/element-web#21305]
### Steps to reproduce

1. logout on other devices (android app)
2. reset all site settings for element-wen
3. login again
4. .... crash during, maybe auth/recovery

#### What did you expect?
Let's recovery with another device and sync all chats.

### Operating system

nixos

### Browser information

Firefox

### URL for webapp

https://element.sum7.eu

### Homeserver

dendrite main commit f75169c35

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

I'm not seeing your logs.

**Comment by t3chguy** [comment]
Got them, thanks

**Comment by genofire** [comment]
Bugreporter of element.io does not work - it put that under:

https://github.com/matrix-org/element-web-rageshakes/issues/11279

Or somewhere else, here is it again (just log, tar is not allowed here):

[log-0.log](https://github.com/vector-im/element-web/files/8184115/log-0.log)

**Comment by t3chguy** [comment]
> Bugreporter of element.io does not work - it put that under:

It does work, it goes to a private repo on purpose.

**Comment by t3chguy** [comment]
The crash you are having is related to Dendrite sending a `null` conditions, the spec doesn't say it is required so the client is wrong to assert its presence

**Comment by t3chguy** [comment]
@genofire will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7973
