### ISSUE TITLE
In Composer, choosing a person's name with TAB inserts the word "false"

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21307]
### Steps to reproduce

1. In the composer
2. Type something at the beginning (otherwise this doesn't work) and press space.
3. Type the beginning of someone's name
4. Press TAB on the keyboard
5. Press Enter to select the person

#### What did you expect?
I expected the person's name to appear in a "pill".

#### What happened instead?
The pill did appear, but also the word `false` appeared after my cursor.

![rec-2022-03-04_10 12 01](https://user-images.githubusercontent.com/76812/156744588-f8751d16-e57f-45e0-bf0d-20c4f222cd9a.gif)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 96.0 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: 3f2ad33b2b22-react-86329012f37e-js-9e4f109e80ae Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/6711
