### ISSUE TITLE
Reuse translation strings

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21308]
### Steps to reproduce

These strings should be set to reuse the common part, in order to reduce translators' work and the high chance of translation inconsistency.

- https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx#L253-L258
- https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/elements/ErrorBoundary.tsx#L95-L100
- https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/dialogs/BugReportDialog.tsx#L206-L209

They share these strings `Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited, which UI elements you last interacted with, and the usernames of other users. They do not contain messages.`, two of which have `If you've submitted a bug via GitHub, debug logs can help us track down the problem. `

### Outcome

The long sentences have a high chance of translation inconsistency. They should be based on a common translation if any.

### URL for webapp

develop branch

### Application version

localhost

### Will you send logs?

No

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx#L253-L258 and https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/elements/ErrorBoundary.tsx#L95-L100 already use a single translation.

https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/dialogs/BugReportDialog.tsx#L206-L209 does not, one issue with splitting translations into sentences is not all languages have whitespace between sentences so really need to be translated whole and not piecemeal

**Comment by luixxiul** [comment]
> one issue with splitting translations into sentences is not all languages have whitespace between sentences

The existing solution is to include the whitespace into the original strings and let the translator on Weblate decide how to handle them. They can delete it to suppress the warning.

Please see https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/dialogs/BugReportDialog.tsx#L115 for example.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/86329012f37e88ef052c84c6e59639738d7a81b0/src/components/views/dialogs/BugReportDialog.tsx#L115 is a poor example, this is bad i18n, the error should be part of the string as an interpolation due to some languages preferring different subject orders.

**Comment by luixxiul** [comment]
Sorry, I could not actually understand the reason why subject orders might matter here... The existing strings consist of two different separate sentences, and I thought they could be safely separated, unless there could be a chance that the order of those sentences would be changed.

**Comment by t3chguy** [comment]
We now handle the reuse piece on the Localazy side and actually split out strings further via translation keys
