### ISSUE TITLE
Cadila-messages were coming through as " waiting for massages"

### ISSUE THREAD

**Issue by Snehalrathod85** [vector-im/element-web#21304]
Cadila-messages were coming through as " waiting for massages"

how can this issue solve?

**Comment by dbkr** [comment]
I'm not sure what this is talking about unfortunately. Could you please use the issue templates? They should help in making a bug report that has the necessary information.

**Comment by andybalaam** [comment]
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @andybalaam to let me know that it’s ready to be reopened.
