### ISSUE TITLE
do not change users avatar and nickname automatically

### ISSUE THREAD

**Issue by jiangshanghan** [vector-im/element-web#21301]
#### What would you like to do?

when users change the account avatar or dispaly name, do not automatically change their "roomnick" and "room avatar".

#### Why would you like to do it?

this is helpful especially when you added in a lot of chat rooms.

**Comment by t3chguy** [comment]
This is a Spec/Synapse issue, Element just calls one API and the server does it all.

See https://github.com/vector-im/element-web/issues/11293
