### ISSUE TITLE
When you discard a voice message that you are recording, the "message composer" area does not reset

### ISSUE THREAD

**Issue by nu111** [vector-im/element-web#21318]
### Steps to reproduce

1. start a voice message
2. discard it
3. now you can't write a message unless you completely reload the app

#### What did you expect?
The "message composer" area should reset

#### What happened instead?
The "message composer" stay freezed as if it's ready to send a voice message

### Application version

1.10.6

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Thank you for taking the time to tell us about your issue.

I am going to close this issue as it has been resolved on develop.element.io and should be available to you soon.
