### ISSUE TITLE
Notification panel is filled with errors

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21319]
### Steps to reproduce

Open the notification panel

#### What did you expect?

To see my notifications.

#### What happened instead?

![Screenshot 2022-03-04 at 10-32-56 Element Test room](https://user-images.githubusercontent.com/48614497/156792534-d6c9643c-b85c-4889-b7b1-1e2c9337b691.png)

### Operating system

NixOS unstable

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 8ec86eb7d566-react-3099a75a5db8-js-70efed1a5881 Olm version: 3.2.8

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Could you send logs here please, I can't repro

![image](https://user-images.githubusercontent.com/2403652/156794816-8cbf6184-7333-4efe-8074-8249f1677db6.png)

**Comment by robintown** [comment]
Sure, sent

**Comment by robintown** [comment]
(It's another instance of `TypeError: member is null`)

**Comment by dbkr** [comment]
SenderProfile.tsx:117

**Comment by novocaine** [comment]
@robintown - Just a note that although it might be frequent for you, if its not occurring for everyone else (I think it isn't?) we wouldn't usually mark the issue as frequent
