### ISSUE TITLE
Autocomplete in composer appends `false` after pill

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21316]
### Steps to reproduce

1. Go to a room and type `/invite @ali`
2. Presse [tab] to autocomplete the user you want to invite

#### What did you expect?

For the composer text to be `/invite @alice:matrix.org`

#### What happened instead?

<img width="237" alt="Screen Shot 2022-03-04 at 13 57 16" src="https://user-images.githubusercontent.com/769871/156776192-d64eff5e-73d9-4eac-a9d8-690fdbec164a.png">

The caret is positioned right between the pill and `false`

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21307
