### ISSUE TITLE
Element Desktop request the pac file continually

### ISSUE THREAD

**Issue by yingziwu** [vector-im/element-web#21323]
### Steps to reproduce

Environment: 
- DE: Plasma 5.24.2

1. Open proxy setting and set proxy setting to  `Use proxy auto configuration URL` .

![image](https://user-images.githubusercontent.com/22741471/156872776-f155e026-664d-4fec-8462-30d5ce990103.png)

2. Start Element Desktop.
3. View the access log of nginx.

![image](https://user-images.githubusercontent.com/22741471/156872863-5b14cfc9-036a-4f47-ad52-1f18abd84733.png)

The element desktop request pac file continually.

#### What did you expect?

The element desktop request pac file only once.

#### What happened instead?

The element desktop request pac file continually.

### Operating system

Arch Linux x86_64 

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

https://neo.bgme.me

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
That sounds like something your OS or Electron would do.
Element is not directly fetching those proxy configuration files
