### ISSUE TITLE
Description on SpaceRoomView.tsx

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21325]
### Steps to reproduce

1. Create a space inside a space (BETA)

#### What did you expect?

According to https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/SpaceRoomView.tsx#L901, the description should be separated in two lines.

![after](https://user-images.githubusercontent.com/3362943/156896965-25a4750a-22d2-41d7-9cd3-5d6e01b03f56.png)

#### What happened instead?

![before](https://user-images.githubusercontent.com/3362943/156896967-99c10286-a56d-4a44-b2ab-36ce54d7a9fb.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
I would like to ask the design team to see if the proposed change would be a proper one.

**Comment by t3chguy** [comment]
GIven I wrote the `\n` I'd say yes this matched Figma at the time, feel free to make a PR to fix this!
