### ISSUE TITLE
Custom user status messages form reloads page on submit

### ISSUE THREAD

**Issue by mitaka8** [vector-im/element-web#21328]
### Steps to reproduce

1. Enable the "Custom user status" feature in "Labs"
2. Click on your profile picture in the top left corner.
3. Type out a message in the "Set a new status" field.
4. Press the Return / Enter button on the keyboard.
![image](https://user-images.githubusercontent.com/61919426/156927154-84ebeb16-310f-49d2-8cb5-d04ef2cd128c.png)

#### What did you expect?
I expected the same action to fire as would have happened if I press the "Set status" button.
#### What happened instead?
Page reloaded and my status was not saved

### Operating system

Microsoft Windows 10 LTSC

### Browser information

Firefox 97

### Application version

Element version: 8e480c72d386-react-8e480c72d386-js-8e480c72d386

### Homeserver

Synapse 1.52.0

### Will you send logs?

No

**Comment by gsouquet** [comment]
Sure, i'll assign you to the issue

**Comment by turt2live** [comment]
I'm going to close this now that the feature has been removed from the app.
