### ISSUE TITLE
Plain text chat export fails for rooms with redacted polls

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#21337]
### Steps to reproduce

1. Create an unencrypted room
2. Create a poll
3. Remove it
4. Export chat from the right panel, select plain text type

#### What happened instead?
Error in the console, hanging export process
<img width="783" alt="Screenshot 2022-03-07 at 10 25 15" src="https://user-images.githubusercontent.com/3055605/157004426-bc19d538-c8f3-454a-aad8-7993785f2cef.png">

### Will you send logs?

No

**Comment by rkouwenhoven** [comment]
I would like to fix this issue
