### ISSUE TITLE
Buttons and text layout on Security Key dialog

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21330]
### Steps to reproduce

1. Select `Connect this session to Key Backup` from the setting
2. Make the window size small enough to get buttons and the text collapsed on the dialog

#### What did you expect?

There should be margin space between the buttons and the text. Also the text should be aligned to left.

![after1](https://user-images.githubusercontent.com/3362943/156931737-86d83c53-056c-4761-b7e6-92f500bba10e.png)![after](https://user-images.githubusercontent.com/3362943/156931732-56ccbf84-8d65-4fee-b246-456c1782d211.png)

#### What happened instead?

There is not margin space. The text is aligned to right, separating the text from the warning icon.

![before1](https://user-images.githubusercontent.com/3362943/156931746-5ce72c2e-b053-4428-bf99-4b2c95e1adda.png)![before](https://user-images.githubusercontent.com/3362943/156931739-842e586b-33fa-416e-ac97-02f8d25f653f.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by andybalaam** [comment]
Yep, it looks like this

![rec-2022-03-08_16 10 23](https://user-images.githubusercontent.com/76812/157277940-237be921-c036-4097-804d-27ffbcdc5aaf.gif)
