### ISSUE TITLE
Pending messages appear in the threads list

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21344]
### Steps to reproduce

1. Open the threads list
2. Send a message in the main timeline

#### What did you expect?

The message should not appear in the threads list since it is not a part of any threads.

#### What happened instead?

The message briefly appeared at the bottom of the threads list. (regression of https://github.com/vector-im/element-web/issues/21146)

### Operating system

NixOS unstable

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 31702e9a26a1-react-9379be0189b8-js-2ce1e7e6ef11 Olm version: 3.2.8

### Homeserver

Synapse 1.54.0rc1

### Will you send logs?

No

**Comment by gsouquet** [comment]
https://user-images.githubusercontent.com/769871/157270697-9c3d5faf-d423-4cdd-b83c-bf388ccd1eab.mov

I have not been able to reproduce this issue on my matrix.org account, however could find a problem when using the thread dev server that has all the MSC3440 APIs enabled

The video above is on my matrix.org account
