### ISSUE TITLE
Inform labs threads users that their old threads have moved to the main timeline

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21349]
When we update the client to consider `m.thread` as the threads prefix in https://github.com/vector-im/element-web/issues/21215, the user will see their old threads move into the main timeline.

We need to inform users that have labs enabled in threads that this has occurred.

**Comment by janogarcia** [comment]
@novocaine I'm attaching the mockups and reassigning it to @gsouquet.

**Source**
[Threads — Labs phasing out notice](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3908%3A317002)

**Comment by gsouquet** [comment]
@janogarcia in regards to the messaging, during the beta period, threads will show up on the "Labs" tab of settings.
So the use of "labs" in the wording of the modal could be confusing. Do you reckon we would be better off changing that to "experimental" instead?

**Comment by janogarcia** [comment]
@gsouquet Thanks for pointing that out, Germain. So it's kind of moving from Labs Alpha/Experimental to Labs Beta, right? Let's iterate on Figma.
