### ISSUE TITLE
Closing element-desktop on linux does not stop the processes.

### ISSUE THREAD

**Issue by mmance** [vector-im/element-web#21345]
### Steps to reproduce

I have element-desktop installed via apt repo:

mmance@gameplay1:~$ dpkg -l element-desktop
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-=================================
ii  element-desktop 1.10.6       amd64 

When I close the program, there are still multiple processes running and they never close:

mmance@gameplay1:~$ pgrep element-desktop
1553074
1553077
1553078
1553080
1553109
1553115
1553121
1553144

### Outcome

I expected when you close element-desktop that the processes for the program close as well.

### Operating system

Debian GNU/Linux 11 (bullseye)

### Application version

1.10.6

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

Synapse - This is not Server related.

### Will you send logs?

No

**Comment by t3chguy** [comment]
Do you have the tray icon enabled in Settings > Preferences > `Show tray icon and minimise window to it on close`?

**Comment by mmance** [comment]
Yes, that was it. it was not showing in my tray.  Thank you so much.
