### ISSUE TITLE
dim UI and show spinner while a dialogue to select file for uploading is show

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21342]
#### What would you like to do?
element should dim the UI when opening a popup window the same as with any modal.

#### Why would you like to do it?
when i click upload a file, it might take my disk some seconds to spin up, hence the dialogue will also show up only after that time.
in the meantime element itself displays no intention of my clicking on the paperclip had any effect at all.
i might click a couple more times and end up with a lot of file selection windows after the disk is ready.

#### How would you like to achieve it?
dim ui, show spinner. after selecting a file an closing the dialogue, hide spinner and undo dimming.

**Comment by t3chguy** [comment]
I don't think browsers tell us when the dialog is closed

The events we have access to are `change` and `input` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file - which don't fire if the dialog is merely closed without a selection being made

**Comment by gsouquet** [comment]
Unfortunately there are not a lot we can do in this scenario as t3chguy mentioned.
Will close this issue as it won't be actionable
