### ISSUE TITLE
Element message search - filter by properties

### ISSUE THREAD

**Issue by throwabird** [vector-im/element-web#21366]
#### What would you like to do?
I would like to be able to filter the search results by certain properties similar to how discord does it.
For reference here are discords properties:
`from:` `user`
`mentions:` `user`
`has:` `link` `embed` `file` `video` `image` `sound` `sticker`
`before:` `date`
`during:` `date`
`after:` `date`
`in:` `channel`

The last property could also replace the 2 separate tabs "This Room" and "All Rooms" which are currently in the element search or make the button add the filter in the search bar. 

#### Why would you like to do it?
There are several cases where this can come in handy - to name a few:
* Searching for a particular image `has:file` or `has:video` or even `has:link`
* Filtering search results by people `from:@user:matrix.tld`
* Looking at results further back `before:date`

#### How would you like to achieve it?
The current Element application (desktop) already offers a search feature which stores the chats locally. The search query would need to be improved with such filters and possibly store more (meta)data to archive the aforementioned features.

**Comment by SimonBrandner** [comment]
Related https://github.com/matrix-org/matrix-spec/issues/759

**Comment by throwabird** [comment]
I've just realized this is a duplicate of #4752.
Related #21121
