### ISSUE TITLE
'Empty Room (was %user)' is not translated

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21369]
I believe this string comes from the js-sdk, so might need to use `td()` and such to get it properly fixed

**Comment by yuktea** [comment]
I would like to work on this @turt2live 🙂

**Comment by Aman-Godara** [comment]
May I ask what is `td()`? Not here to steel the thunder, just familiarizing myself with the issue.
There's a [room.ts](https://github.com/Aman-Godara/matrix-js-sdk/blob/17f3920ddd13248e956e848e00389d374fba83fe/src/models/room.ts#L2448) file which I believe is part of the context of the issue.

**Comment by aaronraimist** [comment]
@Aman-Godara see https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md#translating-strings-vs-marking-strings-for-translation

**Comment by Aman-Godara** [comment]
Where should one import **_td** function from? I couldn't find **_td** function in **matrix-js-sdk**?

**Comment by turt2live** [comment]
Similar to verification, we'd bring the strings from the js-sdk into the react-sdk for translation coverage. We might also need a flag to detect empty rooms so we can translate appropriately

**Comment by turt2live** [comment]
Another option is we move the naming into the react-sdk instead, though this might be more complicated and break some of the layering expectations.

In general though, if someone has a fix for it then go ahead and open a PR - we'll review them all against each other :)

**Comment by Aman-Godara** [comment]
> Similar to verification, we'd bring the strings from the js-sdk into the react-sdk for translation coverage. We might also need a flag to detect empty rooms so we can translate appropriately

you mean not to call **_td** function in **matrix-js-sdk** and pass the string as it is (i.e. without **_td** on it) to **matrix-react-sdk**, where that **_td** function will be added to this string and passed to **element-web**, where **_t** will be called on this string?

**Comment by turt2live** [comment]
We'd still use _td, but wouldn't want to translate named rooms so would skip them.

**Comment by Aman-Godara** [comment]
what about **_td** function should I create one in **matrix-js-sdk**, as it doesn't exist as of now?
Also, can you point to the relevant "verification" file, so that I have a look at it and get a better idea?

**Comment by turt2live** [comment]
It shouldn't be created in the js-sdk - we'd just use it at the top of a related file in the react-sdk. I'm not sure exactly where we have it, but searching for instances of `_td()` should work, I think.

**Comment by Aman-Godara** [comment]
Sorry I think I misunderstood your last few comments.

I have raised a draft PR where I have made small some changes in matrix-js-sdk repo as per what I have understood. Please have a brief look first to understand me better. I have divided my understanding into 3 parts:

1). **matrix-js-sdk**: I added "%()" at several places in matrix-js-sdk repo of this draft PR.

2). **matrix-react-sdk**: Method **getDefaultRoomName** of matrix-js-sdk, as I believe, will be called in matrix-react-sdk repo where **_td()** function will be applied on the string (returned by **getDefaultRoomName** method) to indicate that this string needs translation.

**_td** method is already available in matrix-react-sdk repo in languageHandler.tsx file.

3). **element-web**: This **_td**ed string will reach element-web repo, where **_t()** will be applied on it to get it translated from english to whichever language a user has selected.

Problems I am facing:
I couldn't find **getDefaultRoomName** in matrix-react-sdk repo.

I am a new contributor to element-web. I might be wrong with my assumptions made above, please correct me wherever you find necessary. Also, please let me know wherever I got it right.

**Comment by turt2live** [comment]
We'd be looking at something more similar to this: https://github.com/matrix-org/matrix-react-sdk/blob/a4fda7e25df91819090fab0e9fb9d34ae1d71f60/src/components/views/verification/VerificationShowSas.tsx#L168

In the react-sdk we `_td()` all the strings from the js-sdk, then when it gets used we `_t()` it (elsewhere). 

It might be easier to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org) on Matrix so opinions and thoughts from the wider team can be captured more easily :)

**Comment by t3chguy** [comment]
This is not a trivial fix
