### ISSUE TITLE
Unable to search messages: Error opening the database: DatabaseUnlockError("Invalid passphrase")

### ISSUE THREAD

**Issue by sneaker-net** [vector-im/element-web#21375]
### Steps to reproduce

Preferences > Security & Privacy > Message search > Enable

<img width="562" alt="Enable message search" src="https://user-images.githubusercontent.com/73359050/157654386-d6c6a041-b697-4083-8204-8cdef8bae8c4.png">

### Outcome

<img width="550" alt="Screenshot 2022-03-09 at 11 39 39" src="https://user-images.githubusercontent.com/73359050/157654378-2ed032da-4f00-4a48-84b6-f2be4fdf7546.png">
ps…

### Operating system

macOS Monterey 12.2.1 (Chip: Apple M1)

### Application version

Element version: 1.10.6 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#download

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19358
