### ISSUE TITLE
/rainbow breaks compound emojis

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21371]
### Steps to reproduce

Send `/rainbow 🐻‍❄️`

#### What did you expect?

![Screenshot 2022-03-09 at 23-03-22 Element Test room](https://user-images.githubusercontent.com/48614497/157586246-ba6109ad-8b88-4606-9982-93a0166e0f80.png)

#### What happened instead?

![broken](https://user-images.githubusercontent.com/48614497/157586348-73fb6a32-a45b-433d-8741-d51bc39ae1c1.png)

### Operating system

NixOS unstable

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 2d3757c37f20-react-7b71a9fb6543-js-35a375e3d290 Olm version: 3.2.8

### Homeserver

Synapse 1.54.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9794#issuecomment-494607106

**Comment by EECvision** [comment]
Hi @andybalaam @t3chguy @gsouquet, I am an outreachy applicant. I am interested in solving this issue. Can you assign it to me? Thank you

**Comment by andybalaam** [comment]
@EECvision I assigned it to you. Make sure you un-assign it if you stop working on it.

**Comment by EECvision** [comment]
Alright, thank you.
