### ISSUE TITLE
Refactor _KeyBackupFailedDialog.scss

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21387]
### Steps to reproduce

[`res/css/views/dialogs/security/_KeyBackupFailedDialog.scss`](https://github.com/matrix-org/matrix-react-sdk/blob/48cd83b9d5ad4643f98c98988018a1d3e38e1380/res/css/views/dialogs/security/_KeyBackupFailedDialog.scss) can be refactored to keep styling consistent.

The dialog is not often displayed, but because of it there might be a high chance that inconsistency will be overlooked.

#### What did you expect?

Styling should be strict enough to avoid using `!important` in the future.

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by gsouquet** [comment]
As mentioned in the PR, I'm not entirely sure why this needs to be changed. I'd be inclined to keep it as is

**Comment by luixxiul** [comment]
Replied here: https://github.com/matrix-org/matrix-react-sdk/pull/8029#issuecomment-1065071525

**Comment by luixxiul** [comment]
ya it will never happen
