### ISSUE TITLE
Set min-height to event when formatted HTML is empty to avoid overlapping timestamps

### ISSUE THREAD

**Issue by SamiLehtinen** [vector-im/element-web#21381]
### Steps to reproduce

Received message with custom html:
```
{
  "room_id": "!redacted:envs.net",
  "type": "m.room.message",
  "content": {
    "body": "<div style=\"padding-top: 56.25%; position: relative;\"> <iframe src=\"redacted\" allowfullscreen frameborder=\"0\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\" ></iframe> </div>",
    "format": "org.matrix.custom.html",
    "msgtype": "m.text",
    "formatted_body": "<!-- raw HTML omitted -->"
  }
}
```

### Outcome

Timestamps overlap, because the content collapses for some reason.
![image](https://user-images.githubusercontent.com/4014176/157709940-4646465c-b127-4a7a-ae03-8f520fd1b8c1.png)
The mosaic part is user image and name, works as usual. There are three over lapping timestamps, but you can have more or less, by sending content like above.

### Operating system

Ubuntu

### Application version

1.10.6

### Homeserver

doesn't affect afaik

### Will you send logs?

No

**Comment by gsouquet** [comment]
Reading through the spec, I can see 

> Clients should limit the HTML they render to avoid Cross-Site Scripting, HTML injection, and similar attacks. The strongly suggested set of HTML tags to permit, denying the use and rendering of anything else, is: font, del, h1, h2, h3, h4, h5, h6, blockquote, p, a, ul, ol, sup, sub, li, b, i, u, strong, em, strike, code, hr, br, div, table, thead, tbody, tr, th, td, caption, pre, span, img, details, summary.

I suspect Element would strip out the iframe of the rendered HTML. 
We should probably set a `min-height` to avoid the overlapping timestamps

**Comment by goelesha** [comment]
@andybalaam May I work on this issue.

**Comment by andybalaam** [comment]
@goelesha sure, I assigned it to you. Make sure you un-assign it if you change your mind.

**Comment by goelesha** [comment]
> @goelesha sure, I assigned it to you. Make sure you un-assign it if you change your mind.

Noted. Thanks

**Comment by andybalaam** [comment]
@goelesha I suggest you ask any questions you have here, and then anyone who knows the answer can add it. Or, for more general questions, I suggest you ask in the Matrix room #element-dev:matrix.org

**Comment by goelesha** [comment]
> @goelesha I suggest you ask any questions you have here, and then anyone who knows the answer can add it. Or, for more general questions, I suggest you ask in the Matrix room #element-dev:matrix.org

Noted
