### ISSUE TITLE
"Some of your messages have not been sent" when replying to a threaded message that uses io.element.thread rel type

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21394]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I start a thread within a public room with a client which uses io.element.thread prefix (e.g. iOS)
 -I switch to a client which uses m.thread (develop.element.io) and I see the message in my timeline, as expected
2. What do you click?
 -Using develop.element.io, I try to make a threaded reply to this message

![image](https://user-images.githubusercontent.com/18530109/157893317-2830d134-1cae-4335-be1d-061290cbff80.png)

#### What did you expect?
Not reconciliating the two threads is fine but the user should at least be able to send the message.

#### What happened instead?
The message could not be sent at all.

### Operating system

Windows 10 Home 21H1

### Browser information

Firefox 98.0 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: f149f9a9ad68-react-1eb67047c90d-js-9fc8048c307f Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2022-03-11T14:51:42.279Z I sendEvent of type m.room.message in !VBDnsRtbNNtchetwWf:matrix.org with txnId m1647010302279.1
2022-03-11T14:51:42.428Z E Error sending event MatrixError@https://develop.element.io/bundles/16963f9153af95a415d9/init.js:54808:5
parseErrorResponse@https://develop.element.io/bundles/16963f9153af95a415d9/init.js:54747:13
requestCallback/<@https://develop.element.io/bundles/16963f9153af95a415d9/init.js:54697:17
doRequest/req<@https://develop.element.io/bundles/16963f9153af95a415d9/init.js:54621:18
on_end@https://develop.element.io/bundles/16963f9153af95a415d9/vendors~init.js:209427:13
on_state_change@https://develop.element.io/bundles/16963f9153af95a415d9/vendors~init.js:209377:7
instrumentXHR/</</</<@https://develop.element.io/bundles/16963f9153af95a415d9/vendors~init.js:191566:41

**Comment by t3chguy** [comment]
This is an error from the server
