### ISSUE TITLE
mx_EventTile_readAvatarRemainder is hidden by an avatar on Bubble layout

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21392]
### Steps to reproduce

1. Run XFCE desktop environment if possible
1. Change the message layout to Bubble layout
1. Go to a popular room like the official matrix room
2. Send a message
3. Check the read count next to your avatar. Look for `.mx_EventTile_readAvatarRemainder`

#### What did you expect?

The counter should not be hidden. 

#### What happened instead?

The counter (`2+`) is hidden by the avatar. If the count is more than 10, only the first digit is displayed. See the image below:

![mx_EventTile_readAvatarRemainder](https://user-images.githubusercontent.com/3362943/157882345-4fc7617c-642d-47e0-a3c4-6393581524b6.png)

The position of the counter should not be defined with a fixed number, `right: calc(1.5rem + 14px)` of `.mx_EventTile_readAvatarRemainder` because (1) the actual width depends on a font installed on the computer, and (2) the counter will be hidden again if you get more than three digits such as `100+`.

### Operating system

Debian, XFCE

### Application version

Element version 1.10.6

### Will you send logs?

No

**Comment by t3chguy** [comment]
Does this still happen with the new grouped read receipts?

**Comment by luixxiul** [comment]
No, I have not seen it happening for a while.
