### ISSUE TITLE
Poll votes different on pin message sidebar and on main room timeline

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21408]
### Steps to reproduce

1. Pin a poll
2. Have people vote and then come back to the room later

### Outcome

<img width="1138" alt="Screen Shot 2022-03-14 at 09 37 54" src="https://user-images.githubusercontent.com/769871/158145984-aad0e9d6-1f2f-4361-b450-a7fd5ea181a2.png">

### Application version

Element Nightly version: 2022031001
Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment]
What version is this on? This is supposed to be fixed.

**Comment by gsouquet** [comment]
@robintown I've updated the original bug report with the version information

**Comment by robintown** [comment]
Looks like this is a duplicate of https://github.com/vector-im/element-web/issues/21382, then
