### ISSUE TITLE
Element  on windows crash on start a screencast

### ISSUE THREAD

**Issue by Serizao** [vector-im/element-web#21404]
### Steps to reproduce

To reproduce this issue juste start a video conversation with an other et try to screencast from windows computer with non browser of element software

this is the detail of the crash 
![image](https://user-images.githubusercontent.com/11671895/158074667-4be979a5-bde5-4d2e-9fa5-926e8e9f7bab.png)

#### What did you expect?

bug fix ^^

### Operating system

Windows 11

### Application version

element 1.10.6

### How did you install the app?

official installer

### Homeserver

personnal homeserver

### Will you send logs?

Yes

**Comment by dbkr** [comment]
What problem, if any, are you experiencing? The message in the console is for diagnostics and is normal since it's been interrupted by another play (see the line below).

**Comment by uhoreg** [comment]
Closing this issue since we haven't received any more information about it.
