### ISSUE TITLE
Hardware acceleration future

### ISSUE THREAD

**Issue by SapphyThyHybrid** [vector-im/element-web#21405]
#### What would you like to do?
I would like the option to enable or disable Hardware Acceleration 
#### Why would you like to do it?
I would like to do it because I would like the option to continue my troubleshooting. The element client I been told uses electron, like discord, funnily enough I had the same issue in discord, but it was resolved by disabling the hardware acceleration future under advance settings for discord, sadly this future is not in  the element client. As for the issue that prompted me to do this, talk to someone about and which led me here, is well. blurry text. If I continue to move my mouse over the letters, everything is fine, but after a few seconds it becomes partly blurry or fully blurry
screenshots will be added.
![image](https://user-images.githubusercontent.com/101528021/158079886-59273603-8e17-484c-91e6-6552de286f4b.png)
![image](https://user-images.githubusercontent.com/101528021/158079893-908136be-e69c-42cd-9dd4-1bf431e1385b.png)

#### How would you like to achieve it?
I am unsure how I would like to achieve it, I am sadly not a programmer nor know most of the difficulties that come with being one

### Additional context

I looked through the settings to find what might be it, but I can only assume its hardware acceleration causing it. I am also new to Element and Matrix in general, so I have talked to a friend whom knows more about it than I and it eventually led to them telling me to make this request/ report

**Comment by MRAAGH** [comment]
According to https://github.com/electron/electron/issues/8708 this is a bug in Electron and can indeed be fixed by disabling hardware acceleration.

**Comment by MRAAGH** [comment]
Note: similar issue, but does not seem to be related: https://github.com/vector-im/element-web/issues/15594

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/element-web/issues/13648
