### ISSUE TITLE
Room counter is acting up with threads server support

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21413]
### Steps to reproduce

https://user-images.githubusercontent.com/769871/158166457-bdc00fdb-1b90-4e8e-900d-0ba732a478e0.mov

#### What did you expect?

Not that

#### What happened instead?

See the video

### Will you send logs?

No

**Comment by gsouquet** [comment]
I have just been able to reproduce this. It only happens in encrypted rooms where we listen to the event decryption and try to adjust the highlight read badge if you've been mentioned or one of your keywords was in the event content.

This logic should only be applied to incoming messages and not older ones

**Comment by t3chguy** [comment]
Blocking on threads notifications msc work

**Comment by novocaine** [comment]
Related: https://github.com/vector-im/element-web/issues/21823
