### ISSUE TITLE
Room intermittently reporting "you can't see earlier messages"

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21434]
### Steps to reproduce

1. Switch to a certain room which I have been in for months. The room contains threads, which may or may not be relevant

#### What did you expect?

To see the room's contents

#### What happened instead?

I get this

<img width="379" alt="Screenshot 2022-03-16 at 11 47 55" src="https://user-images.githubusercontent.com/57377/158583697-df5ab47b-8923-4c99-aadb-02885caf2a05.png">

Typing text into the room clears

### Operating system

OS X

### Application version

Element Nightly version: 2022031601 Olm version: 3.2.8

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by JokerGermany** [comment]
I got this in a room #datenschutz:matrix.org after clearing the cache.
It fixed itself.

**Comment by novocaine** [comment]
not seeing this lately, assuming its related to threads and has been fixed
