### ISSUE TITLE
Code formatting button does not escape backticks

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21437]
### Steps to reproduce

1. Type "hello \` world" in the composer
2. Select all
3. Press the code formatting button

#### What did you expect?

For the backtick to be escaped by using more backticks for the fence, like this: \`\`hello \` world\`\`

#### What happened instead?

The composer contains this text: \`hello \` world\`

Since the inner backtick is not escaped, sending the message results in:
`hello` world\`
which was not the intent

### Operating system

NixOS unstable

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

Element version: adad5e16c274-react-e677901eaf70-js-157635476bc0 Olm version: 3.2.8

### Homeserver

Synapse 1.54.0

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@robintown how do i locate the composer? can you kindly drop a screenshot of the steps in reproducing the issue

**Comment by yaya-usman** [comment]
@t3chguy  @robintown , can you assign the issue to me?

**Comment by robintown** [comment]
@yaya-usman It's the input box at the bottom of the screen, and the code formatting button is this one:

![Screenshot 2022-03-28 at 08-17-25 Element Test room](https://user-images.githubusercontent.com/48614497/160396137-0b32edea-5e23-4024-94af-cf0b3fc6181f.png)

**Comment by yaya-usman** [comment]
> @yaya-usman It's the input box at the bottom of the screen, and the code formatting button is this one:
> 
> ![Screenshot 2022-03-28 at 08-17-25 Element Test room](https://user-images.githubusercontent.com/48614497/160396137-0b32edea-5e23-4024-94af-cf0b3fc6181f.png)

Yea figured it out, thanks. I am working on it
