### ISSUE TITLE
Adding a reaction to a message in a thread sometimes increases the notification count / marks the room as unread

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21433]
### Steps to reproduce

1. Open a thread
2. Add a reaction to someone else's existing message 
3. See the room unread count increase (often to > 1) even though there's no new messages

#### What did you expect?

For the unread count/marker to not change

#### What happened instead?

The unread counter changes unpredictably, or the room gets marked as unread.

The outcome isn't consistent and it doesn't happen on all threads. I suspect its related to https://github.com/vector-im/element-web/issues/21414

### Operating system

OS X

### Application version

Element Nightly version: 2022031601 Olm version: 3.2.8

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
reproable example from the threads p0 room. there's two rockets on Aris' message and I see 7 in the badge (already wrong, but whatever)

<img width="290" alt="Screenshot 2022-03-16 at 11 03 01" src="https://user-images.githubusercontent.com/57377/158575972-28813f4b-500d-4c55-afb7-9f982e6b75fa.png">

<img width="316" alt="Screenshot 2022-03-16 at 11 03 06" src="https://user-images.githubusercontent.com/57377/158576105-75f04a6b-f796-4f49-b8f4-8bbe7a4dfca0.png">

click the rocket. rocket count -> 1, room count increments by 2

<img width="309" alt="Screenshot 2022-03-16 at 11 03 11" src="https://user-images.githubusercontent.com/57377/158576159-95761f0c-14f4-47dc-8b2e-2c78b2b32c4f.png">

click the rocket again. rocket count -> 2, room count increments by another 2

<img width="317" alt="Screenshot 2022-03-16 at 11 03 16" src="https://user-images.githubusercontent.com/57377/158576189-c9500bd2-7820-48ef-a805-f03415a71c59.png">

**Comment by t3chguy** [comment]
Blocking on threads notifications msc work
