### ISSUE TITLE
Can't login using Google Account

### ISSUE THREAD

**Issue by phpPhil** [vector-im/element-web#21431]
### Steps to reproduce

This is both element-web and element-desktop on Debian Linux. For simplicity, these steps are for element-web:

1. Open website on https://element.io/get-started#linux 
2. Click "Launch Element Web"
3. Click "Sign In"
4. Click Google icon ("Continue with Google")
5. Click an account (I have 2 accounts).

#### What did you expect?

I get logged in with selected account.

#### What happened instead?

I'm on a page that indicates I'm creating a matrix account:
"Your account is nearly ready. Check your details before creating an account on matrix.org"

(When entering a username and clicking "Continue" I receive: Account already exists.)

Note: I'm using the same matrix/google account successfully on the element app on my Android phone.

### Operating system

Ubuntu 20.04

### Browser information

Google Chrome 96.0.4664.110

### URL for webapp

https://element.io

### Application version

1.10.7

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
Did you log in in the same way on Android (ie. with google & by selecting the same account)? It seems like the server doesn't have an account associated with your google login.

**Comment by robertlong** [comment]
I've tested this on my system, I've created a new Matrix account with a google account and tried to sign in with it. Everything worked as expected.

If you have more reproduction steps and can still reproduce this bug let us know. Closing this for now.
