### ISSUE TITLE
Edited message is incorrectly displayed within a thread

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21447]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I'm in a room with some existing threads
2. What do you click?
 -I edit the root message of a thread
3. More steps…
 -I open that thread and view the root message

#### What did you expect?
The edited version of the root message to be displayed within that thread
#### What happened instead?
The original version is displayed instead

### Operating system

Windows 10 Home 21H1

### Browser information

Firefox 98.0.1 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: 071a5410b88e-react-176e49e31259-js-905a884f72e8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by clokep** [comment]
Does this always happen or only in encrypted rooms?

**Comment by frakic** [comment]
> Does this always happen or only in encrypted rooms?

It seems to only happen in encrypted rooms

**Comment by t3chguy** [comment]
This is not specific to root events due to https://github.com/matrix-org/matrix-spec-proposals/pull/2676/files#r827240084
