### ISSUE TITLE
Message action bar is hidden behind avatar on narrow screens

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21446]
### Steps to reproduce

<img width="200" alt="Screen Shot 2022-03-17 at 09 55 06" src="https://user-images.githubusercontent.com/769871/158784227-28b8f8aa-0bec-4351-92b7-db8bb30883d0.png">

#### What did you expect?

Not that...

#### What happened instead?

Check screenshot

### Will you send logs?

No

**Comment by azizChebbi** [comment]
@gsouquet can you please explain the steps to produce the bug more specifically, so I can easily work on it.

**Comment by gsouquet** [comment]
Make your window very narrow so that when you hover over the event the message action bar will overlap with the sender's avatar

**Comment by agrani29** [comment]
Hii @gsouquet, can you please assign this issue to me, I want to work on it. I am an Outreachy applicant.
