### ISSUE TITLE
Thread I created in a room isn't showing up in the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21456]
### Steps to reproduce

1. Open a room
2. Send a message
3. Reply to that message using Threads
4. Root message disappears

#### What did you expect?

For a message to remain in the timeline

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/158840533-f93c025d-258a-4a31-880f-fae110c726c3.png)

### Operating system

Windows 10

### Application version

Nightly (2021-03-17)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This whole area of code has been rewritten, presuming this got fixed - do shout if it recurs!
