### ISSUE TITLE
Thread summary is not displayed for root messages in search results

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21450]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I'm in a public room with some threads
2. What do you click?
 -I click the Search icon and type in the content of some root message
3. More steps…
 -The message is found but underneath, instead of showing the thread summary, it just says "From a thread"

![image](https://user-images.githubusercontent.com/18530109/158798291-864fa455-f44d-4d3e-86f1-d0dd7c6928e5.png)

#### What did you expect?
To see the thread summary underneath the root message in search results
#### What happened instead?
It just says "From a thread"

### Operating system

Windows 10 Home 21H1

### Browser information

Firefox 98.0.1 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: 071a5410b88e-react-176e49e31259-js-905a884f72e8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Requires spec https://github.com/matrix-org/matrix-spec-proposals/pull/3666

**Comment by t3chguy** [comment]
> The message is found but underneath, instead of showing the thread summary, it just says "From a thread"

This is no longer the case, we will show the thread summary if we know it locally already, else nothing (because we don't know that its a thread root)

**Comment by t3chguy** [comment]
matrix.org now supports MSC3666 - EW needs a tiny bit of support
