### ISSUE TITLE
Room list not adhering to "Sort by A-Z" setting

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21454]
### Steps to reproduce

1. have a space with some favorites
2. set favorites section to sort by A-Z
3. wait for some notifications in the favorites
4. open the rooms

#### What did you expect?
order is fixed always 100% alphabetical

#### What happened instead?
favorites shuffle around when there are unreads

### Operating system

arch

### Application version

Element Nightly version: 2022031601 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.54

### Will you send logs?

No

**Comment by turt2live** [comment]
I can't seem to reproduce this. Is `[x] Show rooms with unread messages first` checked?

Working:
![image](https://user-images.githubusercontent.com/1190097/158893552-cbd599a3-f78d-4692-9e68-a0c90e9587df.png)

Settings used:
![image](https://user-images.githubusercontent.com/1190097/158893539-8588b941-1d31-40a8-bc6c-e8210f14457b.png)

**Comment by HarHarLinks** [comment]
I might have been a bit stupid in this case
