### ISSUE TITLE
Viewing 2 of the 3 threads in a specific room causes an unread dot on the room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21458]
### Steps to reproduce

Just in case it's relevant:
1. Be on a version of Synapse without stable threads support
2. Be on a version of Element with stable threads support (and threads enabled)
3. Have 3 threads in the room, using stable identifiers
4. Upgrade Synapse
5. Refresh Element

Then for the issue:
1. View the threads one by one, noting the unread dot between them

#### What did you expect?

For the room to stay marked as read, as I had the room read.

#### What happened instead?

The unread dot appears.
![image](https://user-images.githubusercontent.com/1190097/158892154-d7cdc3b0-cb04-45ec-b610-4cbc4a922622.png)

Some potentially relevant information:
* The room is set to "Mentions Only", so there might be an unread count I'm not seeing
* The thread which "fixes" the issue is the thread with my event as the root event
* The thread which "fixes" the issue is the middle thread in the panel
* The thread with my event as a root event was not started by me

### Operating system

Windows 10

### Application version

Nightly (2021-03-17)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21114
