### ISSUE TITLE
WebGL disabled displays wrong error

### ISSUE THREAD

**Issue by witchent** [vector-im/element-web#21451]
### Steps to reproduce

1. Disable WebGL (in firefox: about:config -> webgl.disabled = true)
2. Enter a timeline with a shared location (or try to share any location)

#### What did you expect?
An error pointing me towards disabled WebGL in my own browser.

#### What happened instead?
"Unable to load map: This homeserver is not configured correctly to display maps, or the configured map server may be unreachable."
This points me towards my homeserver being misconfigured, so I might try to ask the admins who in turn have no idea why it is not working.

### Browser information

Firefox 98

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Prakashh21** [comment]
Hey @witchent @RiotRobot @gsouquet @t3chguy  I was able to reproduce this. can you assign me this issue , I want to want to work on this as part of my outreachy internship. thanks!!
![photo_2022-03-28_23-00-18](https://user-images.githubusercontent.com/90280586/160454302-2561a5d7-dd38-477e-b2ef-2bac8b66b276.jpg)

**Comment by NSV1991** [comment]
What is the expected error message to show here?

**Comment by t3chguy** [comment]
> An error pointing me towards disabled WebGL in my own browser.

**Comment by rashmitpankhania** [comment]
Assuming if we just change the error message, wanted to ask if we will have to change the existing translation of that message in all languages we are supporting as part of i18n?
sry a newbie, lemme know if i off track or thinking too much

**Comment by t3chguy** [comment]
The message that is there is valid but for a different error, we have to add a new error for if WebGL is disabled.

**Comment by witchent** [comment]
It is indeed fixed, so closing this
