### ISSUE TITLE
Link URL overlay covers up part of the composer

### ISSUE THREAD

**Issue by inducer** [vector-im/element-web#21457]
### Steps to reproduce

1. Enter multi-line text in the composer
2. Hover over a link

#### What did you expect?

Composer remains unobscured.

#### What happened instead?

Firefox's link URL overlay covers up the composer:

![grafik](https://user-images.githubusercontent.com/352067/158852180-e03f1df4-95a6-4130-8be1-74920ac0f671.png)

If the composer were spaced away from the bottom of the window (e.g. like Slack does this), this would not be an issue.

### Operating system

Linux Debian

### Browser information

Firefox 98.0

### URL for webapp

1.10.7

### Homeserver

Synapse 1.54

### Will you send logs?

No

**Comment by robintown** [comment]
Somewhat related: https://github.com/vector-im/element-web/issues/17362

**Comment by gsouquet** [comment]
We'll use https://github.com/vector-im/element-web/issues/17362 as a canonical source of information. I'd invite you to post your screenshot and insights to this problem there.

**Comment by robintown** [comment]
Reopening since https://github.com/vector-im/element-web/issues/17362 has been closed without resolving this

**Comment by robintown** [comment]
Well, nevermind, it does seem that there's enough padding now to keep the bottom text line of the composer visible at all times

![link](https://user-images.githubusercontent.com/48614497/172526534-3d6651f8-baa2-4940-b087-f75e96f0967e.png)
