### ISSUE TITLE
Brand option not used in some strings

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21452]
### Steps to reproduce

It looks like there are some cases left where the brand name `Element` should be replaced with a brand const.

#### What did you expect?

The brand name should be configured with sdkconfig. 

#### What happened instead?

There are some cases left where the brand name `Element` are hardcoded.

### Application version

develop branch

### Will you send logs?

No

**Comment by Sinharitik589** [comment]
Can i work on this?

**Comment by luixxiul** [comment]
Since I have worked on this for `matrix-react-sdk`, would you mind checking for `element-web`?
