### ISSUE TITLE
The Spaces bar cannot be scrolled anymore

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#21467]
### Steps to reproduce

1. Join so many Spaces the Spaces bar becomes scrollable
2. Try to scroll the Spaces (leftmost) bar

#### What did you expect?

To be able to scroll

#### What happened instead?

I can't scroll

### Operating system

macOS

### Application version

2022031701

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

Synapse 1.54.0 (ergaster.org)

### Will you send logs?

Yes

**Comment by turt2live** [comment]
This is a regression in develop - works fine on staging.

**Comment by turt2live** [comment]
err, except develop is about to be staging -- oops.
