### ISSUE TITLE
Creating a new space does not select it by default

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21460]
### Steps to reproduce

1. Visit a space (to get off 'Home')
2. Use the `+` in the left panel to create a space
3. *follow instructions on screen*
4. Note that the space just created was not automatically selected in the left panel

#### What did you expect?

For the space to be selected automatically.

#### What happened instead?

I was getting the "Just me or for your teammates" prompt while a different space was selected in the panel.

### Operating system

Windows 10

### Browser information

Edge

### URL for webapp

local build of develop.element.io

### Will you send logs?

No

**Comment by Sinharitik589** [comment]
Can i take this issue ?

**Comment by turt2live** [comment]
Sure! It might be a bit of a challenge, but let us know in #element-dev:matrix.org if you run into issues.
