### ISSUE TITLE
Read indicators can intersect with last message in message bubble layout

### ISSUE THREAD

**Issue by alyaeanyx** [vector-im/element-web#21469]
### Steps to reproduce

1. Activate message bubble layout
2. Join a room with more than ~6 people in it
3. Write a message
4. Wait until all participants have read your message
5. Click on the read indicators to expand them

#### What did you expect?
The read indicators should not intersect with the bubble of the last message, instead appearing entirely below it
#### What happened instead?
The read indicators overlap with the last message.
![Screenshot from 2022-03-18 11-54-25](https://user-images.githubusercontent.com/74795488/158990968-7fcb35cc-c7b6-4155-87ca-123122e9266e.png)

### Operating system

NixOS unstable

### Application version

Element version: 1.10.4, Olm version: 3.2.8

### How did you install the app?

From the nixpkgs-unstable repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Hi @agrani29 just a comment saying you are working on it is fine - please go ahead.

**Comment by robintown** [comment]
This is fixed as of https://github.com/matrix-org/matrix-react-sdk/pull/8389
