### ISSUE TITLE
Long names are displayed inconsistently in thread summary

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21472]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I change my display name to something long
2. What do you click?
 -I reply to a thread
3. More steps…
 -I reply to another thread with longer text

![Screenshot](https://user-images.githubusercontent.com/18530109/159001941-dd999680-a221-402a-a3ab-8146e1fb6f4f.png)

#### What did you expect?
I expected my name to be displayed consistently across all thread summaries.
#### What happened instead?
My display name is sometimes wrapped within the summary and sometimes only a part of my name is displayed.

### Operating system

Windows 10 Home 21H1

### Browser information

Firefox 98.0.1 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: 071a5410b88e-react-cdcf6d0fd182-js-779afbcb3992 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
if you decide to use multiple ("up to 2") lines at all, then there should be less spacing between lines and instead more to the outside
![image](https://user-images.githubusercontent.com/2803622/159915600-1fa0d9b5-8321-4e6c-bb9b-40194856d679.png)

**Comment by janogarcia** [comment]
@t3chguy After further testing, turns out [the alternate approach](https://github.com/vector-im/element-web/issues/21502#issuecomment-1082059043) I shared works best for variable length content.

```
.mx_ThreadInfo_sender {
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}

// Add this extra declaration

.mx_ThreadInfo_content {
    flex: 1;
}
```
