### ISSUE TITLE
Support Emoji 14.0

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21479]
#### What would you like to do?

Support [Emoji 14.0](https://emojipedia.org/emoji-14.0/).

#### Why would you like to do it?

So that people can use the latest and greatest emoji.

#### How would you like to achieve it?

By updating our Twemoji and Emojibase sources. ([here's](https://github.com/matrix-org/matrix-react-sdk/pull/6347) how it was done last time.)

**Comment by SimonBrandner** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/7286 is also waiting for this, [I suppose a Twemoji release is on its way](https://github.com/twitter/twemoji/commit/cb4fb472e7dc2a83c30391a67d8e5f6574306584) :tada:

**Comment by robintown** [comment]
There's a 14.0.0 tag in the repo already, it just isn't im GitHub Release form for some reason

**Comment by SimonBrandner** [comment]
> There's a 14.0.0 tag in the repo already, it just isn't in GitHub Release form for some reason

Ah, great, seems to be on NPM too, will give it a look (not sure when yet though)

**Comment by robintown** [comment]
yep, will ping Michael about this on monday

**Comment by ara4n** [comment]
for whatever reason twemoji releases often lag behind their tags; in the past i generated them based on the tags without problems (although michael has taken over the font-wrangling reins these days).

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7286
