### ISSUE TITLE
Add copy buttons to event source modal

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21482]
#### What would you like to do?
Copy event source with 1 click

#### Why would you like to do it?
devtools stuff

#### How would you like to achieve it?
add the usual copy button in the place of the red markers:
![image](https://user-images.githubusercontent.com/2803622/159134283-95ce4064-402a-4b4c-b2f2-b82fe70ae9d4.png)
- [ ] copy event id
- [ ] copy room id
- [x] copy decrypted source if available
- [x] copy raw source

**Comment by gsouquet** [comment]
That should be a good very useful first issue to work on for someone who wants to contribute to Element

**Comment by mketer1** [comment]
Hi! I'm new to open source contribution. I'm not too familiar with typescript but would love to take a shot at this issue. If it's still open, I would love to be assigned this task. I may need some guidance/assistance if possible. Please let me know!

**Comment by SimonBrandner** [comment]
If you need any help/have any questions be sure to visit https://matrix.to/#/#element-dev:matrix.org!

**Comment by Prakashh21** [comment]
hey @gsouquet @SimonBrandner @mketer1  can I work on this , I really feel like can do this , I'm an outreachy applicant Thankyou !!

**Comment by andybalaam** [comment]
@mketer1 are you working on this?

**Comment by mketer1** [comment]
Hi! I'm still working on this. Apologies for delayed responses, I've been focusing on class recently but should be free to work on it soon :)

**Comment by sakshi-0206** [comment]
Hey @gsouquet  @andybalaam ! 
I am an Outreachy applicant and would like to work on this issue. Can you please assign this to me as well?

**Comment by andybalaam** [comment]
@sakshi-0206 since @mketer1 is working on this, it does not seem a good idea for you to work on it too. I suggest looking for other issues. Ask if you have questions.

**Comment by olivialivia** [comment]
Hi! Found this issue the other day and as I've not seen much recent activity on it, I fixed it

**Comment by HarHarLinks** [comment]
@t3chguy since #8278 only fixes this issue partly, do you want to reopen (and perhaps rename) or open another one?

**Comment by olivialivia** [comment]
Hi @t3chguy, I'm working on the copy button and before I commit anything I was wondering if you'd prefer it to look like:

![copy](https://user-images.githubusercontent.com/94136530/162977284-903a00fc-2067-4fd8-980d-c51de9e2b0aa.png)
- this using `<AccessibleButton>` + some CSS to style it

OR

![image](https://user-images.githubusercontent.com/94136530/162977320-b887e27b-2106-4b9c-8a40-4b052f13476b.png)
- more like this using `<CopyableText>`

**Comment by t3chguy** [comment]
Definitely avoid adding more height like in your latter proposal please

**Comment by t3chguy** [comment]
> Another nit: in above mockup the buttons are also accessible while the item is collapsed. Idk if that would actually save someone the click to expand but nice to have if you do.

I don't think this is great tbh, blind copying would never come in handy to me personally

**Comment by HarHarLinks** [comment]
> blind copying

Unless current behaviour changes, the main use would be copying encrypted body without looking at it. But yeah not too likely you need that.

> Also if you don't put the comments on the relevant PR< they're likely to get missed

I decided to comment here because that PR is already merged and this is still open, should I really go back to that?
