### ISSUE TITLE
Unread badge shown on a room with threads, despite me having read all the threads elsewhere.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21481]
### Steps to reproduce

1. Participate in a room with a bunch of threads on Element iOS, and get notified in the various subthreads
2. Launch Element Web
3. Go to that room
4. See there's a big red badge shown on the room in the roomlist & breadcrumbs (in my instance: red badge with 7 in it)
5. Look confused, as none of the threads in the threadlist have badges, and you've read them all... and you're also caught up on the room itself.
6. Switch away from the room
7. Switch back again
8. See the red badge disappear
9. Worry that the app feels flakey

#### What did you expect?

If i've read msgs in threads on a different device, i'd expect the badge not to appear on EW.

#### What happened instead?

EW showed stale badge state.

### Operating system

macOS

### Browser information

Nightly

### URL for webapp

Nightly

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
Related: https://github.com/vector-im/element-web/issues/21481

**Comment by thawn** [comment]
The same happened to me. This always happens, if the thread that received a new message is already open.

Switching to a different thread and switching back causes the unread notification to disappear.

It seems that updating the read status of messages in threads only gets updated once the thread is opened, not while the thread is open.

**Comment by gsouquet** [comment]
This will be fixed once we land https://github.com/vector-im/element-meta/issues/196 and https://github.com/vector-im/element-web/issues/22981
