### ISSUE TITLE
Long display name not hidden on context menu

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21486]
### Steps to reproduce

1. Change your display name to the max length 256 chars (eg. `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor a`)
2. Click your avatar to display user menu

#### What did you expect?

The part of the display name over the width of the menu should be hidden.

![after](https://user-images.githubusercontent.com/3362943/159156197-63893084-1ce8-4ad3-9636-6f7ae5de2adb.png)

#### What happened instead?

It is not hidden and makes the width of the menu very wide.

![before](https://user-images.githubusercontent.com/3362943/159156204-41df242b-e794-4a11-a0f1-8529c5c48761.png)

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
There is a related issue: https://github.com/vector-im/element-web/issues/19463

**Comment by gsouquet** [comment]
I would recommend waiting on guidance from the design folks on how to handle text-wrapping/ellipsis/... in the app as it has only been solved ad'hoc and there would be great value in standardising our approach

**Comment by luixxiul** [comment]
I thought it had been instructed with `// Automatically grow all subelements to fit the container`. I will remove it instead for now if it's been outdated already, so that another person would not try to submit the same PR..

**Comment by luixxiul** [comment]
It looks like the same type of issue occurs on the space panel when the space name is long.
