### ISSUE TITLE
Cannot submit `/me` command with only an emoji and user pill

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#21497]
### Steps to reproduce

Try to submit a `/me` command with only an emoji and username pill;
![image](https://user-images.githubusercontent.com/22740616/159291405-487ca0ed-105f-49ec-af73-a814ac94338a.png)

#### What did you expect?

The `/me` command to succeed.

#### What happened instead?

It did not react at all to my enter key, it just stayed in the composer

### Operating system

PopOS 21.10

### Application version

Element version: 1.10.7 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

jboi.nl

### Will you send logs?

Yes

**Comment by robintown** [comment]
Regressed by matrix-org/matrix-react-sdk#7377

**Comment by robintown** [comment]
Other part regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7513
