### ISSUE TITLE
ThreadPanel cuts off timestamp with highlight hoverover

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21495]
### Steps to reproduce

Messages with double-digit hours in the timestamp have the first digit hidden by the green hoverover in the ThreadPanel

<img width="417" alt="Screenshot 2022-03-21 at 14 12 23" src="https://user-images.githubusercontent.com/1294269/159279551-a247d58a-b4bf-4d1e-b75e-3df537d24cfa.png">

^ this should say 11:33, not 1:33

#### What did you expect?

No truncation

#### What happened instead?

Truncation!

### Operating system

macOS 12.3 on M1

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Closing as it will be tackled as part of https://github.com/vector-im/element-web/issues/21084
