### ISSUE TITLE
VoIP call only works once per session when (D)TLS is used by the TURN Server

### ISSUE THREAD

**Issue by v411e** [vector-im/element-web#21490]
### Steps to reproduce

1. Activate (D)TLS on the TURN Server and update the homeserver config as described [here](https://github.com/matrix-org/synapse/blob/develop/docs/turn-howto.md) (use wildcard certificate for domain issued by Starfield Technologies)
2. Restart clients to get new TURN URL
3. Start a 1:1 call
4. Call works
5. End call
6. Start another 1:1 call
7. **Call does not connect / black screen**
8. End failed call
9. Restart Element Desktop
10. Start a 1:1 call
11. **Call works**

### Important notes
- The problem only occurs on federation calls. Calls between accounts on the same homeserver are working with enabled TLS

#### Overview
| TLS enabled on TURN server | Client          | Federated call | Fresh element start              | Working |
|----------------------------|-----------------|----------------|----------------------------------|---------|
| Yes                        | Element iOS     | Yes            | -                                | ✔️       |
| No                         | Element iOS     | Yes            | -                                | ✔️       |
| Yes                        | Element Desktop | Yes            | Yes (first call in session)      | ✔️       |
| Yes                        | Element Desktop | Yes            | No (e.g. second call in session) | ❌       |
| No                         | Element Desktop | Yes            | -                                | ✔️       |
| Yes                        | Element iOS     | No             | -                                | ✔️       |
| No                         | Element iOS     | No             | -                                | ✔️       |
| Yes                        | Element Desktop | No             | Yes (first call in session)      | ✔️       |
| Yes                        | Element Desktop | No             | No (e.g. second call in session) | ✔️       |
| No                         | Element Desktop | No             | -                                | ✔️       |

#### What did you expect?
We expected the second call to work like the first one did. 

#### What happened instead?
The second (and following) calls of one Element Session (aka no restart of Element) do not connect, when TLS is activated on the TURN Server. Interestingly a restart of Element fixes the problem, but only for the first call of that session.

### Operating system

Windows

### Application version

1.10.7 and earlier

### How did you install the app?

From element.io downloads section

### Homeserver

non-public Synapse 1.51.0

### Will you send logs?

No

**Comment by gsouquet** [comment]
Could you share logs for us to investigate this issue further?

**Comment by v411e** [comment]
I added an overview of the tests we did to track down the bug. Which logs would help you? A rageshake or server logs?

**Comment by uhoreg** [comment]
> I added an overview of the tests we did to track down the bug. Which logs would help you? A rageshake or server logs?

I think @gsouquet was asking for a rageshake

**Comment by kittykat** [comment]
@v411e Hi, are you still experiencing the issue? If you are, can you please submit a rageshake and include a link to this issue?

**Comment by v411e** [comment]
We have deactivated DTLS for now and the issue did not occur again. I would close this issue for now. Thanks a lot for your support!
