### ISSUE TITLE
Design of call decline and accept buttons not consistent

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21493]
### Steps to reproduce

1. Let other people call you on video (or create another account and call yourself with it)

#### What did you expect?

The button design should be consistent.

#### What happened instead?

![after3](https://user-images.githubusercontent.com/3362943/159225174-33bd7ab8-6aaf-49a2-ae9a-54aabca51747.png)

- Button height is not aligned
- font-weight are different
- border-radius are different

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
The issue is caused with the default border. Fix is ready.

![after](https://user-images.githubusercontent.com/3362943/159251426-8e9028df-2f3d-467f-8568-795a9af0e20f.png)

**Comment by luixxiul** [comment]
Should `Decline` have the same font-weight as `Call back` here?

**Comment by SimonBrandner** [comment]
> Should `Decline` have the same font-weight as `Call back` here?

Both should be `600` say the design specs 

<hr>

How did you manage to get both `Decline` and `Call back` displayed? Doesn't seem to be a state that we should have

**Comment by luixxiul** [comment]
Basically I just modified the code temporarily to display them both type of buttons. I haven't noticed those texts, which are unnatural as you mentioned :sweat_smile: 

Would you please pointing out where the design spec is available?

**Comment by SimonBrandner** [comment]
> Basically I just modified the code temporarily to display the both types of buttons. I haven't noticed those texts, which are unnatural as you mentioned sweat_smile

Ah, I see :D

> Would you please letting me know where the design spec is available?

They're "semi-private" - I would suggest joining https://matrix.to/#/#element-dev:matrix.org and asking for access there
