### ISSUE TITLE
"Encryption not enabled" in Element web

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#21494]
### Steps to reproduce

First, when I opened Element Web this morning, I couldn't decrypt any message from after last Friday afternoon (I've sent a rageshake for that: https://github.com/matrix-org/element-web-rageshakes/issues/11600). I hit the "Re-request encryption keys" a few times and it helped a bit.

Then, because of an unrelated issue, I rebooted my computer.

#### What did you expect?

When I load Element, my messages (or at least the ones I managed to decrypt) are readable.

#### What happened instead?

Element says "Encryption not enabled" on each encrypted message.

![image](https://user-images.githubusercontent.com/5547783/159256611-009f3754-9dfc-411f-a875-1fa8f8a37b51.png)

_Worth noting that I'm reproducing this consistently on develop.element.io, but app.element.io works fine. On app.element.io I seem to be able to read every encrypted message, even some that I still couldn't decrypt before the reboot._

### Operating system

Arch Linux

### Browser information

Firefox 97.0.1

### URL for webapp

develop.element.io

### Application version

`Element version: 1384783a77ca-react-22712d3091ce-js-75674d961a1, olm version: <not-enabled>`

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by babolivier** [comment]
Just happened to me __again__ on app.element.io (which is now unusable for me as well). Rageshaking.

**Comment by babolivier** [comment]
In both cases my laptop froze and I had to reboot it, and that's olm starts crashing. And it looks like restoring from key backup is failing as well.

**Comment by richvdh** [comment]
Presumably this was a transient problem. Given we never got to the bottom of it, it's unlikely we will now. Closing.
