### ISSUE TITLE
It's really hard to spot where unread messages in threads are coming from

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21496]
### Steps to reproduce

1. Participate in a room where there are two active threads
2. Have one thread open in the threadpanel
3. Someone starts sending messages in the other thread
4. The room badge gets a red 5 or similar
5. But there are no new visible messages in the room, nor on the current thread you're looking at.

#### What did you expect?

Additional visual indicators that you need to look at the ThreadPanel to figure out which thread is active.

#### What happened instead?

I don't think there was either grey or red dot on the ThreadPanel button in the TopRightMenu to tell me i was missing msgs in other threads.  Moreover, given I was already looking at the ThreadPanel, i kinda assumed the panel itself would tell me somehow - e.g. by putting a red-5 badge on the back button of the Thread to encourage me to go back to the ThreadPanel.

Also, weirdly, at some point the red-5 became grey while i was hunting for the missing message (while scrollbacking in the main timeline), which was even more confusing.

### Operating system

macOS 12.3 on M1

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
Part of this problem is bugs and notifications not reliably working as they should, part of it might be design.
