### ISSUE TITLE
Shared Secret with SSO

### ISSUE THREAD

**Issue by shreyasajj** [vector-im/element-web#21503]
### Your use case

Is there a way to allow Shared Secret with SSO without element asking for a password. I have tried to create a shared secret with sso so that my bridges can still auth with my bridge. However, element still thinks I have a password and prompts me for a password everywhere I go that doesn't exist. (example: disabling, and keys)

While it could be solve by using https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-telegram.md#method-1-automatically-by-enabling-shared-secret-auth method 2. I would perfer having method 1 for the `it's easier to accomplish, works for all your users automatically, and has less of a chance of breaking in the future.`

Thank you in advance

### Additional context

This might be a synapse bug, not sure how element verifies there is a password or not

https://github.com/matrix-org/synapse/issues/9605

**Comment by t3chguy** [comment]
> This might be a synapse bug, not sure how element verifies there is a password or not

The server tells it via the `m.change_password` and UIA flows. Not a client issue. https://spec.matrix.org/v1.2/client-server-api/#password-based
