### ISSUE TITLE
Quicktime Video uploads don't get thumbnailed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21505]
### Steps to reproduce

1. Take a screencapture on macOS (e.g. as a .mov)
2. Upload it
3. No thumbnail

#### What did you expect?

If we can thumbnail images via canvas, i'd expect us to be able to render the first frame of the video to a canvas too to thumbnail it.

#### What happened instead?

No thumbnail.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Rather than drawing the image to a canvas I believe we can now use [`createImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap) which avoids the interaction with a DOM element, and is generally faster
