### ISSUE TITLE
per-room RightPanel should not remember Notifications card, as it's global

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21529]
### Steps to reproduce

1. Be in a room
2. Display the notifications panel to check for missed notifs in general
3. Move to a different room
4. Go back again
5. Feel confused by the rightpanel showing notifications, given notifications are global, not per-room.

#### What did you expect?

Don't restore the notificationpanel when you view a room (similar to https://github.com/vector-im/element-web/issues/21487, but for unexpectedly getting dumped in the notifpanel)

### Will you send logs?

No

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/element-web/issues/5383

For contributors: scoping this issue to exactly what's described in the title is best, as otherwise the scope gets complex. Talk to us in #element-dev:matrix.org for questions :)

**Comment by israelsgalaxy** [comment]
Hey @ara4n :), 
Could you assign this issue to me? (Outreachy applicant)

**Comment by arpit-maurya** [comment]
@SimonBrandner @turt2live Please can you elaborate me how to reproduce this bug.

**Comment by SimonBrandner** [comment]
> @SimonBrandner @turt2live Please can you elaborate me how to reproduce this bug.

If you open the notif panel in a room and then switch to another one, the notif panel doesn't stay open. It should stay open regardless of the room

**Comment by SimonBrandner** [comment]
> Don't restore the notificationpanel when you view

In room A open the notif panel, switch to room B, switch back to room A, see the notif panel open again (which it shouldn't be)

**Comment by yaya-usman** [comment]
@SimonBrandner interesting, i should probably give it  a try, you can assign me the issue if @arpit-maurya doesn't work on it or you can assign us both if it's possible

**Comment by ShivraniAJ** [comment]
Hi, I am Shivrani, I am selected as outreachy initial applicant, Please can you assign this issue to me?

**Comment by SimonBrandner** [comment]
> Hi, I am Shivrani, I am selected as outreachy initial applicant, Please can you assign this issue to me?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by ShivraniAJ** [comment]
> > Hi, I am Shivrani; I am selected as outreachy initial applicant, Please can you assign this issue to me?
> 
> I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

Yaa, sure I will go through the link. Thank You

**Comment by andybalaam** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/8273 may be still under development. I have asked there.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/5383
