### ISSUE TITLE
Jitsi participants in voice rooms sometimes don't return an avatar

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21521]
As seen in this screenshot, in the room list:

![the bug](https://user-images.githubusercontent.com/48614497/159062202-a7f8d8b2-ff39-4576-b398-cc3b526864f9.png)

**Comment by robintown** [comment]
No longer relevant in the current designs

**Comment by Nourio** [comment]
Was there a reason for removing the avatars? It followed the design philosophy of Discord, and it's nice to be able to see who's in the room before joining the call.

**Comment by robintown** [comment]
@Nourio It was removed because we wanted to avoid adding complexity to the room list. We're still considering showing that information somewhere else, so the avatars may yet return in some form.
