### ISSUE TITLE
Notifications panel is inconsistent with red mark in room list

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#21530]
### Your use case

When a message is sent with my displayname pilled, eleweb marks the room red, and the message is listed in the right alerts panel.

When a non-pilled message message which contains my displayname string is sent, the room is read but the message does not appear in the alerts panel.

### Have you considered any alternatives?

It just needs to be consistent either way.

**Comment by t3chguy** [comment]
@benparsons is the message in an encrypted room?

**Comment by benparsons** [comment]
> @benparsons is the message in an encrypted room?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/6874
