### ISSUE TITLE
Turn on component debug logs while using app

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#21532]
#### What would you like to do?

In order to better debug a timeline problem when it occurs in the wild (https://github.com/vector-im/element-web/issues/21531), I want to enable [`DEBUG_SCROLL` in the `ScrollPanel.tsx`](https://github.com/matrix-org/matrix-react-sdk/blob/9ba1c97770d75d1d43f161d4acf68d6a9851ec02/src/components/structures/ScrollPanel.tsx#L28) and [`TimelinePanel.tsx`](https://github.com/matrix-org/matrix-react-sdk/blob/9ba1c97770d75d1d43f161d4acf68d6a9851ec02/src/components/structures/TimelinePanel.tsx#L67-L71) to see what's going on. But this isn't really possible when I'm using and reproducing problems with `develop.element.io` in production because the variable constant is already hard-coded in the build. I want a way to toggle this after the fact while using the app (whether that be in the browser devtools console or Labs).

This debug log pattern is also used in various components so it would be good to extend our solution to all of the places we want conditional/toggle-able debug logs.

#### Why would you like to do it?

Get better debug logs to understand what/why went wrong.

##### 1. Using `debug`

One possible solution is to use the [`debug`](https://www.npmjs.com/package/debug) package where you can selectively enable which debug logs you want to filter and see in the console by regex. We use [`debug` on Gitter](https://gitlab.com/gitterHQ/webapp/-/blob/develop/docs/developer-faq.md#frontend) and it's very nice to work with to get just the logs from the pieces you're interested in.

ex.

 - To show everything: `window.localStorage.debug = '*';`
 - To show just logs from the scroll panel: `window.localStorage.debug = 'app:scroll-panel:*';`
 - To show logs from multiple components: `window.localStorage.debug = 'app:scroll-panel:*,app:device-listener:*';`
 - To disable and stop showing debug logs: `window.localStorage.debug = '';`

This could even be a string field in the developer settings if we want to prompt people to give us more detailed logs for their next reproduction.

##### 2. Extending `logger` in `matrix-js-sdk`

We can write some more custom pieces of [`logger`](https://github.com/matrix-org/matrix-js-sdk/blob/d0b964837f2820940bd93e718a2450b5f528bffc/src/logger.ts) to accomplish something similar. One problem is that we currently have the default log level set to `debug` so all of the existing `logger.debug(...)` already show up in the logs. We want these more in depth logs to not show by default and be able to be toggled on.

Also of interest, [`matrix-appservice-bridge` -> `src/components/logging.ts`](https://github.com/matrix-org/matrix-appservice-bridge/blob/2b8a6078fea4426cbabae59b7055578e08e54185/src/components/logging.ts) which has namespaced labeled loggers

[`matrix-bot-sdk` -> `src/logging/LogService.ts`](https://github.com/turt2live/matrix-bot-sdk/blob/c95c493dae7b2d25abe7f18d59f0299715f088e8/src/logging/LogService.ts) has the concept of [`mutedModules`](https://github.com/turt2live/matrix-bot-sdk/blob/c95c493dae7b2d25abe7f18d59f0299715f088e8/src/logging/LogService.ts#L94-L99) to filter out logs.

### Have you considered any alternatives?

Lots of ways to accomplish!

### Additional context

Useful for situations like https://github.com/vector-im/element-web/issues/21432#issuecomment-1069039187

Related issues:

 - https://github.com/vector-im/element-web/issues/19539
 - https://github.com/vector-im/element-web/issues/16972

**Comment by Johennes** [comment]
Assuming it's already possible to do this on local builds, I'd say that is sufficient. I don't believe we really need the ability to do it on _any_ deployed build.
