### ISSUE TITLE
Threaded message appears in main timeline until a new event came in

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#21533]
### Steps to reproduce

1. Go to a room
2. Send a threaded message
3. Edit the threaded message
4. Notice the duplicated thread message in the main timeline
5. After a new event came in, the threaded message disappeared from the main timeline

In the image, both of the messages from me (MadLittleMods) are the same message with the same `event_id` when `Viewing source` on them.

![](https://user-images.githubusercontent.com/558581/159715587-5571f6a2-8cfe-4d6d-bcf2-6f0237cb2573.png)

#### What did you expect?

No thread messages in the main timeline. Made me second guess whether the message was double sent.

#### What happened instead?

The threaded message appeared duplicated in the main timeline

Rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/11633

### Operating system

Windows 10

### Browser information

Chrome Version 99.0.4844.74

### URL for webapp

develop.element.io

### Application version

Element version: e638abf7c253-react-9ba1c97770d7-js-d0b964837f28 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

Rageshake logs: https://github.com/matrix-org/element-web-rageshakes/issues/11633

A similar reproduction: https://github.com/matrix-org/element-web-rageshakes/issues/11637

**Comment by t3chguy** [comment]
Fixed by [matrix-org/matrix-js-sdk@`3892df8` (#2256)](https://github.com/matrix-org/matrix-js-sdk/pull/2256/commits/3892df8f1a9f2aa39b9c720127a547f0952453a7)
