### ISSUE TITLE
Maximised widgets prevent people from joining a room when peeking into the room

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#21542]
### Steps to reproduce

1. Create a room
2. Add a widget (e.g. YT video), maximise it, set layout for everyone
3. Make the room public, enable guest access, make history readable by everyone, and join at least a matrix.org user in the room
4. Send a matrix.to link to the room to someone else

#### What did you expect?

I expect the person to be told they're seeing a preview, and asked if they want to join the room to participate in the conversation.

#### What happened instead?

The person sees the maximised widget, and they are told in the right panel (timeline) they are not allowed to participate in the conversation. They don't know they are only previewing the room, and they have no way to join the room.

### Operating system

macOS 12.2.1 (Monterey)

### Application version

Element Nightly version: 2022032301

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

ergaster.org on Synapse 1.55.0, openforumeurope.org on Synapse 1.54.0, matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
>  and they have no way to join the room.

Element Web/Desktop don't allow guests to join rooms anyway, they're forced to register.

**Comment by thibaultamartin** [comment]
When sharing a matrix.to link to a someone who already has a registered account, their Element only shows the preview. So registered people cannot join the room from Element.

Here is a screenshot taken from Element Desktop, with someone logged in with a matrix.org account and who tried to join a room with maximised widgets.

![Screenshot 2022-03-23 at 16 07 47](https://user-images.githubusercontent.com/1688309/159886352-954c7383-ded6-4162-8914-dd3aafa65358.png)

They can't post messages in the room, but they don't know they are only previewing the room and have not way to join

**Comment by t3chguy** [comment]
Updated the title to better explain how guests fit into this.

**Comment by jryans** [comment]
Planning to take a look at this next week.
