### ISSUE TITLE
Missing divider between space type and member count

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#21549]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I've received an invitation to a space
2. What do you click?
 -I open the invitation
3. More steps…
 -There's no divider between the space type (private/public) and member count

#### What did you expect?
This is what it looks like on Web:
![image](https://user-images.githubusercontent.com/18530109/159925191-45124963-03cf-468b-881d-e0ffb7a28173.png)

#### What happened instead?
This is Desktop Nightly:
![image](https://user-images.githubusercontent.com/18530109/159925323-c7a691fc-859d-4746-a68d-bf9ce02a81a2.png)

### Operating system

Windows 10 Home 21H1

### Application version

Element Nightly version: 0.0.1-nightly.2022032401 Olm version: 3.2.8

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by luixxiul** [comment]
It should be fixed with https://github.com/matrix-org/matrix-react-sdk/pull/8142.

**Comment by t3chguy** [comment]
Nightly is too old to have this fix.
