### ISSUE TITLE
Screenshare settings

### ISSUE THREAD

**Issue by Doomsdayrs** [vector-im/element-web#21558]
##### Change the quality of the screenshare.
IE:
140p
240p
360p
480p
720p
1080p
...
4k
Automatic

##### Change the FPS of the screenshare
15fps
24fps
30fps
60fps
...
Source
Automatic

#### Why would you like to do it?

By doing so, I can ensure my stream maintains lag free. 

#### How would you like to achieve it?

When screen sharing, provide a button to change the screen share quality.

### Additional context

Sometimes my friends say "the video is lagging" and we have to swap to Discord because I can change the stream quality there

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/19008, https://github.com/vector-im/element-web/issues/16657

**Comment by gsouquet** [comment]
Closing as duplicate of https://github.com/vector-im/element-web/issues/19008
