### ISSUE TITLE
Can't reply to messages while searching

### ISSUE THREAD

**Issue by KamilBaczkowski** [vector-im/element-web#21550]
### Steps to reproduce

1. Go to a room
2. Click the search button
3. Try using the reply button

#### What did you expect?
I expected that I would be able to reply to a message while the search bar is active.

#### What happened instead?
The message input was focused, and that's all

### Operating system

Manjaro Linux

### Application version

Element version: 1.10.7 Olm version: 3.2.8

### How did you install the app?

OS repos

### Homeserver

Synapse 1.47.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is fixed on develop
