### ISSUE TITLE
Labs beta card overflow on a small window

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21554]
### Steps to reproduce

1. Open Settings
2. Open `Labs`

#### What did you expect?

The beta card should be wrapped like below.

https://user-images.githubusercontent.com/3362943/159982965-c35dda3c-f268-4b5f-8c1e-925b33b50f8d.mp4

#### What happened instead?

The GIF image on the right side is only partly displayed.

![before](https://user-images.githubusercontent.com/3362943/159983007-10ea06e0-9666-4232-8670-9556a1d99d17.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
Before pushing a commit, I would like to know if it is fine to proceed with that design. If it should stay as it is, I'll close this issue.

**Comment by t3chguy** [comment]
It looks sane to me!

**Comment by luixxiul** [comment]
What concerns me here is that the heights of cards area might be too large when there are more than a couple of tests, like three tests. To decrease the height of each card a little bit, for example I could try to align feedback and leave beta buttons horizontally when the animation image is wrapped, taking the length of their strings which depend on translation into consideration.

**Comment by luixxiul** [comment]
This should look better. The feedback button is placed above and right of the other button.

![after1](https://user-images.githubusercontent.com/3362943/160141252-f8fb9f41-4565-4ad5-b23e-640d1bf146fd.png)
![after2](https://user-images.githubusercontent.com/3362943/160141272-d45f9be0-5bb4-48a7-8bc2-743e72bd4790.png)
