### ISSUE TITLE
The "View source" button has disappeared

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21563]
### Steps to reproduce

Open the context menu of any event

#### What did you expect?

To see the "View source" option

#### What happened instead?

It's not there:

![Screenshot 2022-03-25 at 11-52-50 Element 1 Michael (t3chguy)](https://user-images.githubusercontent.com/48614497/160155619-48fedb96-ada1-4b4e-88a9-a7bd0b398dba.png)

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 6ae7d60f4ae1-react-50fd24581cd5-js-e90f12ee321a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment]
Apparently this is hidden behind developer mode now, but I can't find how to enable developer mode anymore :confused:

**Comment by robintown** [comment]
The option is in /devtools

**Comment by bkil** [comment]
Thanks, I was looking for that as well. Could you perhaps somehow document this on the interface, so people would not need to go through GitHub to find out about the solution?
