### ISSUE TITLE
Video showed up as a static image and audio player

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21569]
### Steps to reproduce

1. Receive a video in a chat
2. Wait for the server to download it
3. If autoplay is enabled, it'll play as a frozen frame with an audio player instead of the video controls

#### What did you expect?

I expected the video to not load or to have the correct playback.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/160254661-3438b89c-fd3e-4250-820d-22b71087dd09.png)

I recognize the control bar as one for audio, and it appeared to have the poster image stuck underneath it. While waiting for the video to load, one can see the rough skeleton of what the controls should be:
![image](https://user-images.githubusercontent.com/1190097/160254690-d77c9c71-2173-4206-8f0c-7fbaca1f7361.png)

----

The video itself is listed as `.mov`, so might be a compatibility issue? Unsure of the inner container format.

### Operating system

Windows 10

### Application version

Nightly (2021-03-26)

### How did you install the app?

The Internet

### Homeserver

t2l.io (using an alternative media repo)

### Will you send logs?

No

**Comment by turt2live** [comment]
The video plays fine in external players, when downloaded.

**Comment by t3chguy** [comment]
@turt2live can you confirm the event is `m.video` and also the DOM contains a `<video />` element for playback?

**Comment by turt2live** [comment]
yes, it is an `m.video` and has `<video />`

**Comment by turt2live** [comment]
err, it was working just fine before? I don't have any reason to believe this is a browser issue.

**Comment by t3chguy** [comment]
Beforehand mov files were all sent as `m.file` by EW/ED

**Comment by t3chguy** [comment]
Is the file encrypted?

**Comment by turt2live** [comment]
no, it is not.

**Comment by t3chguy** [comment]
Then nothing was changed here on the receiving side to my knowledge, can you test using an older version to confirm or forward me the problematic footage to see if I can reproduce? mov files work fine for me on Desktop

**Comment by t3chguy** [comment]
Tested the issue with 1.10.0 on Chrome and encountered the same thing, given we're just passing the file verbatim to Chrome, it seems like an upstream bug.

**Comment by turt2live** [comment]
closing as unactionable then - thanks for testing.

**Comment by t3chguy** [comment]
This bug is specific to Chrome's lack of full support for MOV, iOS seems to send MOVs muxed in something other than mp4

**Comment by t3chguy** [comment]
FTR Safari can play that same file back happily

![image](https://user-images.githubusercontent.com/2403652/160439103-9932e369-049e-458c-a686-cbfa559fdacd.png)

and Firefox gives up sanely

![image](https://user-images.githubusercontent.com/2403652/160439139-5dd3292a-eeec-4efd-9ca2-2a445e2ec206.png)
