### ISSUE TITLE
Press arrow-up to edit most recently sent message stopped working

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#21560]
### Steps to reproduce

1. Send any message
2. Press up on the keyboard

#### What did you expect?

The most recently sent message should go into edit mode.

#### What happened instead?

Nothing.

### Operating system

Windows 10

### Application version

Element version: 1.10.7 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of your own issue https://github.com/vector-im/element-web/issues/19908

**Comment by thany** [comment]
But it was fixed...
