### ISSUE TITLE
Devtools button is missing from room settings

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#21577]
### Steps to reproduce

1. Open a room
2. Go to the room settings
3. See the lack of a devtools button to open the devtools.

### What did you expect?

A devtools button in the room settings

#### What happened instead?

It's not there

### Operating system

Arch Linux / Wayland w/ Sway

### Browser information

Firefox 98

### URL for webapp

develop.element.io

### Application version

develop

### Homeserver

half-shot.uk

### Will you send logs?

No

**Comment by t3chguy** [comment]
That button was removed, it is now available via /devtools or with Developer Mode enabled also in the room header context menu and the quick settings menu

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2403652/160400727-19efae04-c63e-4824-a393-0058d422b2f5.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/2403652/160400747-a6c9bcb3-c4b1-4524-b60c-8f77b02210d5.png">
