### ISSUE TITLE
Assign user to specific space

### ISSUE THREAD

**Issue by mmahmoudian** [vector-im/element-web#21573]
I tried to see if someone else have reported this but didn't find anything even close ([Example](https://github.com/vector-im/element-web/issues?q=assign+to+space+)). If I missed it and this is a duplicate, I apologize. 

-------

#### What would you like to do?

It would be nice to be able to assign a specific chat to a Space.

#### Why would you like to do it?

I have been recently approach by someone regarding a FLOSS project I'm a dev team member of, so this private chat very much belongs to the Space of that FLOSS project, but now instead it sits in the middle of the list of other private chats.

As far as I understand, Spaces is a concept that although it can be used to bundle multiple rooms from admin's perspective, but it is also (confusingly) also used to de-clutter the chat list and be more organized for each user. This impression of mine comes from the fact that when I create a private chat to a user from a specific Space, that private chat appears also in that Space (which is very convenient although slightly confusing).

#### How would you like to achieve it?

It would be nice if a room can be assigned to a specific Space either via the settings of that room, and/or by drag-n-drop to the icon of the specific Space. 

### Have you considered any alternatives?

I have no better or alternative idea

**Comment by t3chguy** [comment]
> It would be nice if a room can be assigned to a specific Space either via the settings of that room, and/or by drag-n-drop to the icon of the specific Space.

You can add existing rooms to a space - see https://github.com/vector-im/element-web/issues/20222

**Comment by mmahmoudian** [comment]
@t3chguy  No you cannot. You can only add "room"s and not private chat with people. I don't know what the lingo is, but I just tried and the list only and only shows the rooms with more than 1 users. What I'm asking is those chats that are categorized under "people"

**Comment by mmahmoudian** [comment]
Also it is super confusing because I don't want to add this private chat to that Space so that everyone on earth can see, I want it to be added so that I can see it more organized. This is because everyone is using a nickname and it is impossible to keep track of who was this person I chatted with in few weeks.

**Comment by t3chguy** [comment]
If the space is private then you can also add DMs.

> Also it is super confusing because I don't want to add this private chat to that Space so that everyone on earth can see, I want it to be added so that I can see it more organized.

Given DMs are private-rooms, they'll only be visible in the space to those already in the room (i.e the participants of the DM) and the rest of users would only see the room ID but never in the UI as the UI will hide rooms you don't have permission to know details of.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/2403652/160356940-17630964-d0b2-4d03-8403-795659caccd3.png">

**Comment by mmahmoudian** [comment]
@t3chguy What am I doing wrong?


https://user-images.githubusercontent.com/390889/160367837-f7439ec1-05eb-44b0-bd7a-6141ab2a68a3.mp4

**Comment by t3chguy** [comment]
Is your space private?

> If the space is private then you can also add DMs.

**Comment by mmahmoudian** [comment]
> Is your space private?

No the Space is not private.

> If the space is private then you can also add DMs.

Then I guess my feature request hold and should not be closed because it has nothing to do with #20222 ?

**Comment by t3chguy** [comment]
I suggest adding it to https://github.com/vector-im/element-web/issues/17260 or maybe opening an element-meta issue given it isn't web-specific.
