### ISSUE TITLE
In threads, disambiguated names are blue

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21570]
### Steps to reproduce

1. Have multiple users with similar display names in a room
2. Start a thread as one of those users

### Outcome

![Screenshot 2022-03-26 at 17-23-43 Element 2 Test room](https://user-images.githubusercontent.com/48614497/160257654-610b3994-5b4e-427b-a1f7-d7cf9c23cdb7.png)

#### What did you expect?

The disambiguated part of the display name should have the same gray color that it does in the main timeline.

#### What happened instead?

It's blue.

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 14f46a8ca994-react-6c69f3e3b63e-js-e90f12ee321a Olm version: 3.2.8

### Homeserver

Synapse 1.55.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I've seen this once before but can't repro it now

![2022-03-27_10-04](https://user-images.githubusercontent.com/25768714/160272641-7d5831f3-0524-4cb0-a934-1dbf893dd916.png)

**Comment by robintown** [comment]
Maybe requires bubble layout?

**Comment by SimonBrandner** [comment]
> Maybe requires bubble layout?

Ah, yep!
