### ISSUE TITLE
Events RSVP management 

### ISSUE THREAD

**Issue by wvhulle** [vector-im/element-web#21571]
#### What would you like to do?

Next to the option of adding polls, it would be nice to have an option to share events with a location and ask for RSVPs.

#### Why would you like to do it?

To make Element a better competitor to Facebook.

#### How would you like to achieve it?

Adding an extra option in the message attachment dialog.

### Have you considered any alternatives?

Yes making an event externally and then sharing the link, but this relies on an external service.

**Comment by SimonBrandner** [comment]
You might also want to consider filing an issue at https://github.com/matrix-org/matrix-spec

**Comment by hex-m** [comment]
The issue in the spec-repo is https://github.com/matrix-org/matrix-spec/issues/1006

There is also https://github.com/vector-im/element-web/issues/3195 so I think this can be closed.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/3195
