### ISSUE TITLE
Can't run `yarn run fetch --noverify --cfgdir ""` on Windows

### ISSUE THREAD

**Issue by elibroftw** [vector-im/element-web#21586]
### Steps to reproduce

Powershell:
`yarn run fetch --noverify --cfgdir ""` after `yarn`

#### What did you expect?

It to work

#### What happened instead?
```
$ yarn run mkdirs && node scripts/fetch-package.js --noverify -d=
$ mkdirp packages deploys
No config directory set
Specify a config directory with --cfgdir or -d
To build with no config (and no auto-update), pass the empty string (-d '')
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\maste\Documents\GitHub\element-desktop>
```

### Operating system

Windows

### Application version

latest

### Will you send logs?

No

**Comment by gsouquet** [comment]
This sounds like you might need to escape the quotes for them to be passed to the command that gets executed

```
$ yarn run mkdirs && node scripts/fetch-package.js --noverify -d=
```

`-d` receives nothing. This bug tracker is probably not the right forum for this kind of issues, https://matrix.to/#/#element-web:matrix.org might be more appropriate

**Comment by elibroftw** [comment]
> This sounds like you might need to escape the quotes for them to be passed to the command that gets executed
> 
> ```
> $ yarn run mkdirs && node scripts/fetch-package.js --noverify -d=
> ```
> 
> `-d` receives nothing. This bug tracker is probably not the right forum for this kind of issues, https://matrix.to/#/#element-web:matrix.org might be more appropriate 

You're Readme does not tell me to escape quotes or anything. A bug with documentation **IS** relevant. This is a documentation issue not a user problem. So this is relevant place.

**Comment by t3chguy** [comment]
The readme assumes a typical shell such as sh, zsh, bash, etc. Powershell is non-standard.

**Comment by elibroftw** [comment]
It is standard. If you open vscode without changing the default terminal you get powershell.

I'll consider this a bug with powershell though so whatever.

However why does such a simple action require command line arguments. Config file? For what?

**Comment by t3chguy** [comment]
Standard is not the same as default.

Powershell behaves very differently to CMD even on the very same Windows box. And both of those function very different to *nix shells etc.

> However why does such a simple action require command line arguments. Config file? For what?

For the desktop app you are building, Element doesn't function without a config file which tells it parameters like what server to connect to, where to get its updates etc.

**Comment by elibroftw** [comment]
If the build and docs are made in the perspective of someone forking and not contributing back, then shouldn't it also include how to use config.js?
