### ISSUE TITLE
Threads: Rooms set to mentions only don't bump in "unreadness" with replies to a thread

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21583]
### Steps to reproduce

1. Have threads enabled
2. Engage with threads
3. Engage with other rooms, while others continue to engage with threads
4. Note the room not surfacing as unread

#### What did you expect?

The unread dot on the room when any reply to any thread is made. There also seems to be a bug where the last activity timestamp for the room is not being updated properly, which may be related, so the room list isn't surfacing the room as "more active than previously", so can be lost in the sea of rooms.

#### What happened instead?

The room's unread status was unchanged. Cause of "mentions only" determined from internal chat.

### Operating system

Windows 10

### Application version

Nightly (2021-03-27)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by novocaine** [comment]
I am seeing this today in Threads P0
