### ISSUE TITLE
Image replies look weird in bubble layout

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21581]
### Steps to reproduce

1. Enable bubble layout
2. Reply to something with an image

#### What did you expect?

The gradient should not encompass the entire reply body, and I guess the image should be right-aligned since the whole bubble is right-aligned? Or the top right corner of the image should be rounded.

#### What happened instead?

![Screenshot 2022-03-28 at 11-28-28 Element Test room](https://user-images.githubusercontent.com/48614497/160433144-7e5a1c8a-2651-4339-92ec-783a6c349a68.png)

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 14f46a8ca994-react-8baf06c3fff6-js-bdc3da1fac3c Olm version: 3.2.8

### Homeserver

Synapse 1.55.0

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@robintown how do you enable bubble layout?

**Comment by goelesha** [comment]
@robintown Myself Esha Goel. I am an Outreachy Applicant. I was able to reproduce the issue. Can you pls assign it to me?

**Comment by SimonBrandner** [comment]
> @robintown Myself Esha Goel. I am an Outreachy Applicant. I was able to reproduce the issue. Can you pls assign it to me?

Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by robintown** [comment]
Also, this issue needs input from the design team before it can be actionable.

**Comment by yaya-usman** [comment]
> @robintown how do you enable bubble layout?

Ok i figured it out, but it seems to be working on my browser, check the image below

![bubble](https://user-images.githubusercontent.com/38439166/162582291-e86fe4ff-f6b8-45d0-81d3-31ad70d64a3c.PNG)

**Comment by yaya-usman** [comment]
> Also, this issue needs input from the design team before it can be actionable.

ohh ok

**Comment by goelesha** [comment]
> > @robintown Myself Esha Goel. I am an Outreachy Applicant. I was able to reproduce the issue. Can you pls assign it to me?
> 
> Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).
> 
> If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

Thanks for your response. I will look for some other issues to work on.

**Comment by robintown** [comment]
The gradient has been removed, so let's track the remaining issues at https://github.com/vector-im/element-web/issues/23409
