### ISSUE TITLE
Rooms vanished from left panel and didn't show up in search results

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21592]
### Steps to reproduce

1. Notice at some point that a DM isn't showing in the left panel (`!mziByPnfpgOyIrrOIZ:matrix.org` and it had unread messages in it at the time)
2. Try to search for it (using start of MXID/user alias) and see no results
3. Observe that the DM is visible in the Android app
4. Send message to the room there
5. See DM appear in element-web with the "empty room" label in the left panel
6. DM metadata (avatar and room name) load

I also updated develop after I noticed the issue and that did not help with the problem.

#### What did you expect?
Can always see DMs in left panel and search results

#### What happened instead?
DM vanished from left panel and didn't come up in search result

### Browser information

Chromium 98.0.4758.102 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 5eecc768a389-react-2adc972eeca0-js-26cbe02a7f2e Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Clear client cache in Settings > Help & About - some requests failed likely whilst starting your client due to either network or HS issues.

**Comment by gsouquet** [comment]
There's also something odd with that room, logs are saying

```
2022-03-29T16:42:35.632Z W [getType] Room !mziByPnfpgOyIrrOIZ:matrix.org does not have an m.room.create event
```

**Comment by t3chguy** [comment]
Yeah the app would have thrown during sync-accumulator restoration due to not being able to fetch something

```
2022-03-29T16:49:11.608Z E Error processing cached sync M_NOT_FOUND: Could not find event undefined
    at parseErrorResponse (https://develop.element.io/bundles/5dcbc963c293a6a063da/init.js:56451:13)
    at https://develop.element.io/bundles/5dcbc963c293a6a063da/init.js:56401:17
    at Object.callback (https://develop.element.io/bundles/5dcbc963c293a6a063da/init.js:56325:9)
    at on_end (https://develop.element.io/bundles/5dcbc963c293a6a063da/vendors~init.js:209406:13)
    at XMLHttpRequest.on_state_change (https://develop.element.io/bundles/5dcbc963c293a6a063da/vendors~init.js:209356:7)
    at XMLHttpRequest.<anonymous> (https://develop.element.io/bundles/5dcbc963c293a6a063da/vendors~init.js:191552:41)

**Comment by kittykat** [comment]
I'm seeing this with other rooms today (not DMs) - haven't cleared cache yet, so probably same cause as yesterday.

**Comment by t3chguy** [comment]
Yes, this applies to rooms across the board, any rooms processed after the error was thrown will have gotten corrupted.

**Comment by kittykat** [comment]
I cleared cache and reloaded, and I'm still having the same issue with the web app team room and `!mziByPnfpgOyIrrOIZ:matrix.org`

While it was reloading, I got this error:
![Screenshot from 2022-03-30 10-18-56](https://user-images.githubusercontent.com/51663/160797732-76867c2a-b809-4422-ac24-6cc86419cd6c.png)

And when the reload finished, I saw a preview of the room that I'm a member of instead of the timeline

**Comment by jakewb-b** [comment]
I've had this issue yesterday and today - Nightly has been almost unusable:

- Rooms, including very recent DMs, not visible in the list or findable in search
- Rooms showing as 'empty room' despite having users in, and then switching to 'X and Y others' instead of the room name
- Unable to send messages in certain DMs

Clearing cache didn't fix it. Disabling threads in labs does appear to have resolved all of the above issues.

**Comment by ara4n** [comment]
I just had it this morning after upgrading; completely exploded.

**Comment by ara4n** [comment]
(this is very similar to https://github.com/vector-im/element-web/issues/20862 - please can we fix it so that if it fails again in future it fails hard, rather than leaving the app in such a horrible state?)

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/2264 has potential to fix this, if you're running this code and still see it then please shout and I will add some defensive logging

**Comment by gsouquet** [comment]
It looks like https://github.com/matrix-org/matrix-js-sdk/pull/2264 has fixed the issue, no one seems to be able to reproduce the issue anymore

**Comment by kittykat** [comment]
I haven't had the issue again, so going to close

**Comment by c7hm4r** [comment]
For me, this issue appears when I do not have increased `client_max_body_size` in my nginx configuration for Synapse. A workaround for me was to clear the Element cache each time after my browser cache was cleared. The solution is to increase the `client_max_body_size` (to `100M` for me) and do a simple page refresh.
