### ISSUE TITLE
Enable email notifications doesn't survive user logout

### ISSUE THREAD

**Issue by jrybar-fl** [vector-im/element-web#21598]
### Steps to reproduce

1. User log in on element.{matrix_domain}
2. Click on user avatar on top of the left panel
3. Choose Notifications
4. Enable email notifications for {email}
5. Close Settings window
6. Log out
7. Sign in again
8. Verify device with Security Key
9. Repeat Steps 2 and 3

#### What did you expect?

Once 'Enable email notifications for {e-mail}' has been enabled, it should persist and survive session logout.

#### What happened instead?

After logout 'Enable email notifications for {e-mail}' is disabled for unknown reason.

### Operating system

MacOS 12.3

### Browser information

Iridium 2020.11 (Official Build) (64-bit)

### URL for webapp

1.10.6

### Application version

Element version: 1.10.6, Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is https://github.com/matrix-org/synapse/issues/3696
