### ISSUE TITLE
A reply to a reply to a thread root appears in the thread, but it should not

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21599]
### Steps to reproduce

1. In a room, write a message A
2. Create a thead based on A
3. Reply to A in the main timeline **EDIT: you must do this from a non-threads-capable Element Web**. Note that this reply appears correctly in the main timeline
4. Reply to the reply

#### What did you expect?
The reply to the reply should appear in the main timeline.

#### What happened instead?
Instead, it appears in the thread.

![image](https://user-images.githubusercontent.com/76812/160806670-1f06ad0b-cd0d-4170-8dbf-b731785d729b.png)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 98.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 5eecc768a389-react-4d14128d94c8-js-26cbe02a7f2e Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Note that this reply appears correctly in the main timeline

For me this does not happen which feels even more broken

**Comment by t3chguy** [comment]
Okay, got a fix for the above issue and can now reproduce, your repro steps do not work if the reply to A is sent by a threads-capable EW

**Comment by andybalaam** [comment]
> Okay, got a fix for the above issue and can now reproduce, your repro steps do not work if the reply to A is sent by a threads-capable EW

aiee

**Comment by andybalaam** [comment]
Want me to test your fix @t3chguy ?

**Comment by andybalaam** [comment]
Ah, I see the fix was merged. I've re-tested the same conversation, and it's fixed!

**Comment by andybalaam** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8195
