### ISSUE TITLE
Linking to a thread reply from a different room fails to load timeline position

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#21596]
### Steps to reproduce

1. Johannes sent a link to a thread reply to me in our DM. The thread in question is in a private encrypted room that I am in, have already loaded timeline for.
2. Following the link causes
<img width="799" alt="Screenshot 2022-03-30 at 10 45 23" src="https://user-images.githubusercontent.com/3055605/160790782-79b658e8-1ee5-4186-9b11-667c3b2d9406.png">

### Application version

Element Nightly version: 2022032401
Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This was likely fixed since, you're on an old nightly, please retry on latest develop/nightly and if it recurs then reopen.
