### ISSUE TITLE
Stuck message in a thread

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21608]
### Steps to reproduce

1. Send a bunch of messages in a thread
2. Receive stuck message (unclear on exact reproduction steps)

#### What did you expect?

Messages to be in the order they were sent.

#### What happened instead?

One of my messages was stuck at the bottom of the send panel. When I send other messages, they briefly show up *below* that stuck message before moving *above* said message.

Likely, the client missed an echo.

### Operating system

Windows 10

### Application version

Nightly (2021-03-29)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
After restarting the client I see my event in the thread correctly as a replay attack, and an "unsent message" for the exact same thing. I suppose it got stuck during sending, then?

**Comment by t3chguy** [comment]
Closing in favour of the more generic https://github.com/vector-im/element-web/issues/17966
