### ISSUE TITLE
Display two buttons of device verifications on the center of the modal window

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21604]
### Steps to reproduce

1. Logout and login from another device (or login on a private mode browser)

#### What did you expect?

From the perspective of UX, I think these buttons should be placed on the center (horizontal) of the dialog, because they are its main content, not an additive one like Cancel / Done buttons.

![after1](https://user-images.githubusercontent.com/3362943/160859752-056a8cd2-71fd-47cd-90ff-3ae2154922f8.png)
![after2](https://user-images.githubusercontent.com/3362943/160859772-c1d964a4-ef7f-4a01-b0f7-70c10d7b24de.png)

I would even add icons (device and key icons) before those labels to highlight their functions.

#### What happened instead?

![before](https://user-images.githubusercontent.com/3362943/160859785-96c9f62b-774e-4323-89c2-a4c24ba999ac.png)

Considering there is not preference over each other, it is not really clear why these buttons are aligned to the right side.

### Application version

develop branch

### Will you send logs?

No

**Comment by Pranjalie** [comment]
@kerryarchibald @luixxiul I would like to work on this issue.

**Comment by luixxiul** [comment]
I no longer want to work on this

**Comment by luixxiul** [comment]
And closing as this proposal is not sensible. Please create one if you guys want to work on that area.
