### ISSUE TITLE
Non-Google Capcha

### ISSUE THREAD

**Issue by V1TA5** [vector-im/element-web#21602]
### Your use case

Hi,

Why is it, that a messageing software that tries to be an alternative to big tech Solutions like Whatsapp offers Google Capacha as solution for preventing bots on signin/up?

#### What would you like to do?
I would like to have self hosted alternatives to google recapcha.

#### Why would you like to do it?
Giving users back control over their data is what motivates people to switch to Matrix.
Adding a google service back into a web client is contra productive. 

#### How would you like to achieve it?
Find some other Capacha or other solution to verify that the is user a human.

### Have you considered any alternatives?

Iam aware e-mail verification exists. It only provides proof that a user account has a reachable email address not that it belongs to a human.

### Additional context

I had to disable registration on my server because i refuse to enable Google reCapacha and/or e-mail verification.

I do think E-Mail verification isn't relevant anymore because of the easy to get a (temp) email now days and it doesn't protect you from spam accounts. 

I would love if i could run a secure matrix & element setup without 3rd party services.

Thank you for producing my go to chat client.

**Comment by t3chguy** [comment]
The captcha used is the one that the Matrix homeserver you connect to demands, right now most servers use Google Recaptcha but nothing prevents them using UIA fallback to serve different ones.

Closing in favour of https://github.com/matrix-org/matrix-spec/issues/295
