### ISSUE TITLE
Changing of theme from Dark mode to Light mode does not respond

### ISSUE THREAD

**Issue by EECvision** [vector-im/element-web#21611]
### Steps to reproduce

https://user-images.githubusercontent.com/63562663/160947985-fabcfc38-b74b-4c4d-a879-24cc92a03210.mp4

#### What did you expect?
Change from Dark mode to Light mode
#### What happened instead?
Dark mode persisted.

### Operating system

Windows

### Browser information

Version 99.0.4844.84 (Official Build) (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21610 - generally, only one issue is necessary for problems that occur on both Web and Desktop.

**Comment by EECvision** [comment]
Okay, thank you for letting me know.
