### ISSUE TITLE
Thread includes messages from main timeline

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21613]
### Steps to reproduce

1. Chatting in a room
2. One participant started a thread based on one of the messages
3. More chatting

#### What did you expect?
Only messages sent to the thread should be included in the thread.

#### What happened instead?
Messages from before the thread were included:

![image](https://user-images.githubusercontent.com/76812/161001448-dadd4766-2695-4f89-872c-762f9f012284.png)

The thread started with Travis' "slight bump" message, but messages from before that are visible in the thread.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 98.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: f029b68ad4b1-react-d09205122d14-js-4360ae7ff817 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Stebalien** [comment]
I ran into this issue once, but it disappeared after I restarted Element. In case it's relevant, the thread started with a reply to a message in another thread.

I.e.:

1. Message A:
    1. Threaded: Message B
    2. Threaded: Message C
2. Message D, reply to C.
    1. Message E

**Comment by novocaine** [comment]
I believe this hasn't been seen for a while so assume fixed

**Comment by t3chguy** [comment]
Saw this just now

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2403652/165084265-a709109b-b91e-4ad3-9da7-456047cbde5f.png">

**Comment by t3chguy** [comment]
I had this happen again during development, and it made React devtools very unhappy. From what I could tell, the main timeline things are actually glitched/duplicated by React itself, they don't exist in the shadow DOM under the right panel

**Comment by MadLittleMods** [comment]
Reproduced this again but I think I was able to capture the necessary debugging info that was asked for previously, https://github.com/matrix-org/element-web-rageshakes/issues/12986

The logs include [`TimelinePanel` debugging snapshot info](https://github.com/matrix-org/matrix-react-sdk/pull/8502) and have [`ScrollPanel` `DEBUG_SCROLL` and `TimelinePanel` `DEBUG` enabled](https://github.com/matrix-org/matrix-react-sdk/pull/8513).

The random extra messages show in the React devtools and the `keys` look sane.

**Comment by t3chguy** [comment]
Alright so the issue is that the Threads EventTimelineSet somehow grows a second timeline which it shouldn't
