### ISSUE TITLE
Thread summaries not being updated correctly

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21628]
### Steps to reproduce

Post a message on a thread.

#### What did you expect?

The thread summary in the room timeline to be updated with my avatar and display name.

#### What happened instead?

The thread summary is not showing my avatar and is showing my matrix user id instead of the display name. Clicking on the thread summary will make the thread summary to render the correct contents.

### Operating system

macOS

### Browser information

Chrome 99.0.4844.74

### URL for webapp

develop.element.io

### Application version

Element version: 5077157282d1-react-f4c25e06cdbc-js-d6f1c6cfdc5a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Hmm, so this will be a regression from https://github.com/matrix-org/matrix-react-sdk/pull/8204

**Comment by gsouquet** [comment]
This issue has not been seen in the recent past! If this happens again, we'll investigate
