### ISSUE TITLE
Round number of join messages

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#21637]
#### What would you like to do?

Currently in https://matrix.to/#/#lobby:ipfs.io, there seems to of been a DoS attack where 2378 members suddenly joined at once, this causes Element to lag as it tries to count the number displayed for "user and 2378 others joined", this lag doesn't disappear when the count has finished. It'd be nice to be able to reduce this lag.

#### Why would you like to do it?

Having Element lag from a large number of joining members isn't great, the whole UI becomes sluggish even after the counting has finished, being able to reduce this lag would be nice.

#### How would you like to achieve it?

There's two possible solutions to this (though they're not mutually exclusive):
- Batch the members joined count so it increases by increments of 50 (or some other large number) for each new update to the count.
- Round the members joined count to the nearest hundreth when the count surpasses 1000.

### Additional context

There's probably a better way that the devs know to reduce the amount of lag, the fact that the lag continues even after the count has finished might imply the counting logic isn't actually the problem, I mainly created this issue as a real-world example of a DoS event and how Element/Matrix currently handles it.

Additionally, I noticed that clicking the "unread messages" button in the top-left will scroll the chat just before the large number of joined members, but, the count prevents you from scrolling down any more recent messages until the count has finished. This is probably worth a separate issue.

**Comment by t3chguy** [comment]
The issue isn't the counting, its that it has to hold all of those events in memory in the timeline at once, because of how Matrix timelines work.

**Comment by Winterhuman** [comment]
So there's not much that can be optimised to reduce this substantially? Also, what about the joined-message count stopping the scrolling, is it possible to make those messages be fetched asynchonously from actual chat messages or is that a major spec change or not worth it?

**Comment by t3chguy** [comment]
They're all in a single Matrix Room Timeline (DAG) and if you fetch them separately (using two filters and two sync/messages streams) then as a client you no longer know at what point a user changed their profile/joined/left and thus cannot know what profile to render for messages in that area

**Comment by t3chguy** [comment]
I think its valid as a problem to have, but not the suggested solution

**Comment by Winterhuman** [comment]
Alright then, I'll close this and create a performance issue instead, thanks!

**Comment by Winterhuman** [comment]
I've created a new issue, this one is specifically about after the join events have all been counted since that seems possible to tackle at least partially: https://github.com/vector-im/element-web/issues/21638
