### ISSUE TITLE
Convert selected text to MD link when pasting a URL

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#21634]
#### What would you like to do?

When pasting a URL _while having text selected_ the selection should turn into a MD link with the previously selected text being the title.

To illustrate, starting from:

![Screenshot 2022-04-01 at 08 53 44](https://user-images.githubusercontent.com/1137962/161211207-fdb10226-a934-4801-9f13-cdfeb07bf60c.png)

and pasting `https://matrix.org` should end up with:

![Screenshot 2022-04-01 at 08 54 05](https://user-images.githubusercontent.com/1137962/161211214-95a20b38-74f7-4996-9311-7de9afe49b3f.png)

#### Why would you like to do it?

This is a common idiom supported in at least some text composition apps (for instance, logseq) and saves time in having to write the MD link manually.

#### How would you like to achieve it?
Check if the pasted text is a URL. If so, perform the string replacement to construct a MD link.

**Comment by Sinharitik589** [comment]
Can i take this issue?

**Comment by SimonBrandner** [comment]
> Can i take this issue?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!
