### ISSUE TITLE
Found a typo error in the element-web doc.

### ISSUE THREAD

**Issue by EECvision** [vector-im/element-web#21635]
### Steps to reproduce

Go to matrix-react-sdk\README.md file Ln 60, Col 55

#### What did you expect?
![issue4](https://user-images.githubusercontent.com/63562663/161230170-3fa9d6cd-f600-493c-b22a-906e03f1dd11.PNG)

#### What happened instead?
![issue4-b](https://user-images.githubusercontent.com/63562663/161230360-fb02c9e6-f9d0-4247-88c1-0d9552c57c39.PNG)

### Operating system

Windows

### Will you send logs?

No

**Comment by EECvision** [comment]
Hi, I am outreachy applicant, I want to fix this issue. Can you assign it to me? Thanks

**Comment by gsouquet** [comment]
Go ahead and fix it, thank you for the heads up

**Comment by EECvision** [comment]
Thank you.

**Comment by t3chguy** [comment]
This got fixed
