### ISSUE TITLE
Spike scoring system for sorting search results

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21641]
This is the development issue for spiking a scoring system for search results in the new search experience (opt into the Beta in Settings -> Labs).

### Prior art to consider
- Chrome site engagement
  - https://www.chromium.org/developers/design-documents/site-engagement/
  - In chrome: chrome://site-engagement/

### Development tasks
TBD

**Comment by gsouquet** [comment]
This has actually been built to a certain level as part of getting the search out of beta, see https://github.com/matrix-org/matrix-react-sdk/pull/8707/files#diff-2d52b31ab57cfe24e2244fe53723a3582ef718c987d3432b1203a0656c2fd7e1
(cc @justjanne)
