### ISSUE TITLE
Jitsi widget can be removed from video rooms in other clients

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#21647]
### Steps to reproduce

1. Create a Voice Room 
2. Use your 2nd Client e.g. Element Android
3. Join Hangup in Room (Slide Hangup not from Jitsi UI)

### Outcome

Jitsi Conf is gone forever and make Room unusable 

### Operating system

All

### Browser information

N/A

### URL for webapp

messenger.3dns.eu

### Application version

Develop

### Homeserver

1.56.0rc1

### Will you send logs?

No

**Comment by robintown** [comment]
> Join Hangup in Room (Slide Hangup not from Jitsi UI)

I'm not sure what this is referring to. Could you maybe provide a screenshot of what you're doing?

**Comment by DoM1niC** [comment]
> > Join Hangup in Room (Slide Hangup not from Jitsi UI)
> 
> I'm not sure what this is referring to. Could you maybe provide a screenshot of what you're doing?

the Voice Room is show as a Video Call and a Slide to Hangup appearing I just 4 Fun Slide it and the Widget was dismiss.
