### ISSUE TITLE
New "send a sticker" shortcut conflicts with GNOME emoji picker shortcut

### ISSUE THREAD

**Issue by smithfred** [vector-im/element-web#21645]
### Steps to reproduce

1. On a GTK-based web browser on GNOME (e.g. GNOME Web), press <kbd>Ctrl</kbd>+<kbd>;</kbd>.

#### What did you expect?

GNOME/GTK emoji picker appears.

#### What happened instead?

Element's "Send a sticker" is triggered.

#### Additional info

Shortcut is mentioned online here: https://gitlab.gnome.org/GNOME/gnome-user-docs/-/issues/108 (couldn't find any better official online mention of this unfortunately, but it's been around for several versions of GNOME/GTK).

This is quite likely to affect other browsers on GNOME in future too (e.g. Firefox) as they adopt the shortcut, since it's a standard GNOME shortcut (didn't test on e.g. Chrome/Chromium).

### Operating system

Linux/GNOME

### Browser information

GNOME Web

### URL for webapp

app.element.io

### Application version

Element 1.10.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15076 - it'll never be possible to avoid clashing shortcuts with all DE's/OS'es/Browsers
