### ISSUE TITLE
Voice & Video room freezes after playing with widget settings

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21643]
### Steps to reproduce

1. create e2ee voice & video room
2. open right panel
3. try out what happens when you click widget maximize, unpin etc (to figure out what is the difference from a pinned widget)

#### What did you expect?
no crash

#### What happened instead?
app hang. element now thinks i'm not in the room. it also won't join (stuck joining with spinner).

### Operating system

arch

### Application version

Element Nightly version: 2022040101 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.55.2

### Will you send logs?

Yes

**Comment by robintown** [comment]
Widget settings are hidden in video rooms on develop
