### ISSUE TITLE
Emoji does not align well with text on chats

### ISSUE THREAD

**Issue by yaya-usman** [vector-im/element-web#21655]
### Steps to reproduce

1. Enter a text on the composer followed by an emoji.

#### What did you expect?

![issue2](https://user-images.githubusercontent.com/38439166/161422335-99d1ccb2-052d-4eeb-bbeb-8504a2538ac8.PNG)

#### What happened instead?
![issue1](https://user-images.githubusercontent.com/38439166/161422267-e4d12cea-7f5a-4a7b-8ff2-95b88b9cce55.PNG)

### Operating system

windows 10

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@andybalaam  @t3chguy  I will be submitting my PR soon

**Comment by robintown** [comment]
As you mentioned in the PR, this issue occurs on Brave Browser, which is not currently one of our [supported environments](https://github.com/vector-im/element-web#supported-environments). If you can reproduce this in a supported browser, feel free to re-open.
