### ISSUE TITLE
URL Previews enabled 'accidentally?' in encrypted room

### ISSUE THREAD

**Issue by AverytheFurry** [vector-im/element-web#21659]
### Steps to reproduce

idk how reproducible this is, but this is all I remember doing
1. Create a new encrypted & private room on the matrix.org homeserver
2. Paste a link which can preview
3. See preview
4. Close element
5. Open element
6. No preview?

#### What did you expect?
I expected there to be no preview in an encrypted room. I assume that this is a bug because it was later re-disabled after reopening the website. 
#### What happened instead?
I literally opened up my mostly unused matrix.org account, only to test this, as I thought "wait, matrix.org has url previews, isn't that a privacy concern if used in encrypted rooms?" This is why I have a before and after screenshot, because I sent it to my friend to ask it about the situation (and then closed the browser), and it told me that this was likely not intended behavior.

Before:
![image](https://user-images.githubusercontent.com/47131867/161460920-9caf9bbe-6a81-4621-82c2-52f99d294c05.png)
After:
![image](https://user-images.githubusercontent.com/47131867/161460899-a612c7a6-92d0-4bd9-9715-926ae43f36f8.png)

Keep in mind, I didn't change any room settings after creation. I also am using librewolf and had to enable canvas data and persistent storage during the initial login to my account, idk how that would cause any issues, but it might give some info? idk.

### Operating system

Windows 10

### Browser information

Librewolf Version 98.0-1

### URL for webapp

app.element.io

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by goelesha** [comment]
@AverytheFurry Can you pls elaborate more. I tried the same steps which you mentioned in the description but after sending a link to my private room I didn't see any preview. I have attached a screenshot for your reference.
<img width="584" alt="Screenshot 2022-04-04 at 1 38 43 PM" src="https://user-images.githubusercontent.com/54431564/161501601-dfefe9de-e2da-467c-945c-5ed52a552e95.png">

**Comment by kittykat** [comment]
I can recreate when creating room on

```
Element version: b1a60b25b4c8-react-13a51654e782-js-71b7521f4223
Olm version: 3.2.8
```

and viewing on

```
Element version: 1.10.8
Olm version: 3.2.8
```
