### ISSUE TITLE
Link in README.md of matrix-org / matrix-react-sdk for CSS of matrix-react-sdk is not redirecting to any page.

### ISSUE THREAD

**Issue by ShivraniAJ** [vector-im/element-web#21654]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
I was going through https://github.com/matrix-org/matrix-react-sdk/blob/develop/README.md then I clicked https://github.com/vector-im/element-web/tree/master/src/skins/vector/css/matrix-react-sdk it was showing page not found.

#### What happened instead?
I was expecting for CSS folder of matrix-react-sdk  to open but instead it was showing page not found.
![Screenshot (32)](https://user-images.githubusercontent.com/86149243/161420540-985b3367-692f-420a-808a-50c535f3d3cf.png)

### Operating system

Windows

### Will you send logs?

No

**Comment by ShivraniAJ** [comment]
I was looking for the css of  matrix-react-sdk which I found at https://github.com/matrix-org/matrix-react-sdk/tree/develop/res/css, Do you wish to redirect that link to this CSS folder instead ? Can you please guide me, I would like to fix this issue.

**Comment by ShivraniAJ** [comment]
Can you please guide and assign this issue to me? I would like to fix this issue.

**Comment by gsouquet** [comment]
> I was looking for the css of matrix-react-sdk which I found at [https://github.com/matrix-org/matrix-react-sdk/tree/develop/res/css](https://github.com/matrix-org/matrix-react-sdk/tree/develop/res/css?rgh-link-date=2022-04-03T09%3A20%3A10Z), Do you wish to redirect that link to this CSS folder instead ? Can you please guide me, I would like to fix this issue.

Looks like you have a good grasp on where things are 👍
Nice one spotting this
