### ISSUE TITLE
Unable to leave or join the room "#offtopic:grapheneos.org"

### ISSUE THREAD

**Issue by jahway603** [vector-im/element-web#21657]
### Steps to reproduce

1. I have been in the room #offtopic:grapheneos.org for a while now.
1. I discovered this issue by right clicking on the room and choosing the "Low Priority" option. I get the error message "Error leaving room Not a known room".
1. I then try to leave the room (with the intention of re-joining it). I get the error message "Error leaving room Not a known room".
1. I then try to join #offtopic:grapheneos.org to see if that works. I get the following error message, which brought me here to file this issue:

```
#offtopic:grapheneos.org is not accessible at this time.
Try again later, or ask a room admin to check if you have access.

M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose).
```

#### What did you expect?

I expect that the room is accessible. I should be able to leave and join the room.

#### What happened instead?

It's not clear if the room exists or not. I'm unable to "leave" the room. I'm unable to "join" the room.

### Operating system

Arch Linux

### Application version

Element version: 1.10.8, Olm version: 3.2.8

### How did you install the app?

Arch package via pacman

### Homeserver

meowchat.xyz, Synapse {"server_version":"1.55.2","python_version":"3.9.2"}

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
M_UNKNOWN: Failed to fetch alias
    at S (vector://vector/webapp/bundles/d56013f0044a307bef18/vendors~init.js:2:806154)
    at vector://vector/webapp/bundles/d56013f0044a307bef18/vendors~init.js:2:805557
    at Object.callback (vector://vector/webapp/bundles/d56013f0044a307bef18/vendors~init.js:2:805120)
    at vector://vector/webapp/bundles/d56013f0044a307bef18/vendors~init.js:2:11207
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/d56013f0044a307bef18/vendors~init.js:2:11231)
```

This is an issue with your server, possibly around federation or caching.

**Comment by jahway603** [comment]
@t3chguy do you have any helpful suggestions to help me troubleshoot what is going wrong here?

**Comment by t3chguy** [comment]
Nope, I suggest getting the server logs and asking the Synapse team
