### ISSUE TITLE
Placeholder on the sign-in page inputs does not hide when typing.

### ISSUE THREAD

**Issue by EECvision** [vector-im/element-web#21660]
### Steps to reproduce

1. Go to the sign-in page of app.element.io

2. Start typing in the inputs

#### What did you expect?
I expect the placeholder to hide when I start typing
![issue6](https://user-images.githubusercontent.com/63562663/161497039-96917d18-462d-4ac4-a4ab-bfff4f29188e.PNG)

#### What happened instead?
text is written over the placeholder
![issue5](https://user-images.githubusercontent.com/63562663/161497273-735043c9-0b05-40bf-8348-b50ecb3555c2.PNG)

### Operating system

Windows

### URL for webapp

Version 100.0.4896.60 (Official Build) (64-bit)

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Will you send logs?

No

**Comment by EECvision** [comment]
Hi, I am an outreachy applicant. I can work on this issue, can you assign it to me? Thank you

**Comment by gsouquet** [comment]
I can not reproduce this issue
Does this happen in incognito too? It looks like you are using some sort of password manager?

**Comment by EECvision** [comment]
> I can not reproduce this issue Does this happen in incognito too? It looks like you are using some sort of password manager?

You are right, this does not happen in incognito. I understand that my password manager may have been the cause. Thank you for looking into it.
