### ISSUE TITLE
Thread view lacks a loading state

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21668]
### Steps to reproduce

Click on an existing thread either from the main timeline (thread summary, or "Reply in thread" contextual action) or the thread list.

#### What did you expect?

The thread view container to show a loading indicator if the loading isn't close to instant.

#### What happened instead?

An empty thread view container is shown with no feedback on loading activity, which felt sluggish/broken.

### URL for webapp

develop.element.io

### Application version

Element version: b79133c6947b-react-371ccd78580f-js-b8321290f823 Olm version: 3.2.8

### Will you send logs?

No

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21335
