### ISSUE TITLE
Clicking on user names in the thread view will cause jumps in the timeline

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21672]
### Steps to reproduce

When viewing a thread, click on a user name.

#### What did you expect?

Same behavior as in the main timeline (i.e., adds a user pill in the composer, without introducing any unexpected jump in the timeline position).

#### What happened instead?

- When clicking on the root message's author name it will jump to that message position in the main timeline.
- When clicking on a non-root message author name it will center the position of the message in the thread timeline (needs to be tested on a long thread)

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

develop.element.io

### Application version

Element version: b79133c6947b-react-371ccd78580f-js-b8321290f823 Olm version: 3.2.8

### Will you send logs?

No

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8149/
