### ISSUE TITLE
Downloading files fails due to Content Security Policy

### ISSUE THREAD

**Issue by johannes-krude** [vector-im/element-web#21677]
### Steps to reproduce

I configured the `Content-Security-Policy` in nginx for element-web as described in https://github.com/vector-im/element-web/#configuration-best-practices.

### Outcome

Our element-web users can no longer download files. The download spinner keeps rotating and the following error message appears in the firefox log.

![screenshot_2022-04-05_09:04:49](https://user-images.githubusercontent.com/28594647/161702845-0aa4b69a-d00e-44e0-8dbe-d3ed16952339.png)

```
SecurityError: The operation is insecure. [2bf984cf-d2df-4425-a509-7db97539560d:1](blob:https://riot.comsys.rwth-aachen.de/2bf984cf-d2df-4425-a509-7db97539560d)
Content Security Policy: The page’s settings blocked the loading of a resource at https://riot.comsys.rwth-aachen.de/ (“frame-ancestors”).
XML Parsing Error: undefined entity
Location: jar:file:///snap/firefox/1154/usr/lib/firefox/browser/omni.ja!/chrome/browser/content/browser/certerror/aboutNetError.xhtml
Line Number 24, Column 12:
```

Similar to https://github.com/vector-im/element-web/issues/21095 I tried changing the `Content-Security-Policy` to `frame-ancestors 'self` and this resulted in successful file downloads.

### Operating system

Ubuntu Linux

### Browser information

Firefox 98.0.2

### URL for webapp

https://riot.comsys.rwth-aachen.de

### Application version

Element version: 1.10.8 Olm version: 3.2.8

### Homeserver

Synapse 1.55.0

### Will you send logs?

Yes

**Comment by johannes-krude** [comment]
Doing a rageshake results in `Failed to send logs: No connected database`.

**Comment by t3chguy** [comment]
We updated the docs to say `frame-ancestors` `self`
