### ISSUE TITLE
Out-of-order messages

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#21678]
### Steps to reproduce

1. In a room with some threads (threads enabled in labs)
2. Some messages sent, including a thread. The last reply in the thread was yesterday.

#### What did you expect?
Messages from today to be below messages from yesterday

#### What happened instead?
Yesterday's message was below today's

![image](https://user-images.githubusercontent.com/76812/161708995-ecb8edf7-cdaf-43fd-9bcf-9a025567c698.png)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 98.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: b79133c6947b-react-371ccd78580f-js-b8321290f823 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kittykat** [comment]
I've occasionally seen this, but not producibly

**Comment by dbkr** [comment]
If the messages couldn't get from one homeserver to another until a later day, this is considered a feature: the alternative being that the new message appear in the 'correct' place, somewhere back in the timeline. It's a bit concerning that the message didn't come through until later.

**Comment by andybalaam** [comment]
I'm 95% sure this was client side, not server side.  After refreshing my browser tab it was fixed.
