### ISSUE TITLE
Broken gradient effect when hovering the thread summary

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21670]
### Steps to reproduce

Hover over a thread summary in the main timeline.

### Outcome

The gradient effect underneath the caret icon is not rendered correctly.

<img src="https://user-images.githubusercontent.com/60790/161609064-6f5fffd4-ecde-4749-aeba-76d56f6ffd15.png" width="279">

### Operating system

macOS Monterey

### Browser information

Safari 15.3 (17612.4.9.1.8)

### URL for webapp

develop.element.io

### Application version

Element version: b79133c6947b-react-371ccd78580f-js-b8321290f823 Olm version: 3.2.8

### Will you send logs?

No

**Comment by soumyag123** [comment]
@janogarcia can you please assign me this issue?

**Comment by gsouquet** [comment]
@soumyag123 this issue is not really up for grabs as threads is a project under active development

**Comment by kittykat** [comment]
@soumyag123 you may want to have a look at some of the [issues labelled with "Help Wanted"](https://github.com/vector-im/element-web/labels/Help%20Wanted). Some of those are also marked as "good first issue", which means they're more suitable for newcomers to the project.

**Comment by janogarcia** [comment]
@t3chguy It can be fixed for Safari 15.3 and below by changing the declaration for the background gradient.

Apparently, there's a bug that is triggered when transitioning from a colored stop to a purely transparent one, just as we're currently doing:

`linear-gradient(270deg, #F4F6FA 52.6%, transparent 100%)`

To fix it change the hex colors to HSLa or RGBa:

`linear-gradient(270deg, hsla(220, 37%, 97% , 1) 50%, hsla(220, 37%, 97% , 0) 100%)`
`linear-gradient(270deg, rgba(244, 246, 250, 1) 50%, rgba(244, 246, 250, 0) 100%)`

**Comment by t3chguy** [comment]
@janogarcia had to use `rgba(255, 255, 255, 0)` otherwise it'd require introducing a new variable - $system-transparent which serves no purpose other than to work around a bug in Safari 15.3 - from a quick stackoverflow search this should still work 

Is the move from 52.6% to 50% intentional?

**Comment by janogarcia** [comment]
@t3chguy I'd recommend, if possible, using Sass `change-color()` function as a way of returning the expected color for this type of gradients in a systematic way that still doesn't require defining a new variable (rather than fading it to a different hue).

`background: change-color($color, $alpha: 0);`

As for the updated percentage value, I sort of rounded it / cleaned it up, as the 52.6% value came directly from Figma, where it's hard to have precisely positioned gradients without plugins. It was meant to be 50% in practice.

**Comment by t3chguy** [comment]
@janogarcia 

1. We don't use SASS but instead postCSS
2. We have to do this operation at runtime due to how custom (JSON) themes work using css variables `--system`

**Comment by janogarcia** [comment]
I'll need to learn more about our CSS and runtime theming setup.

**Comment by janogarcia** [comment]
I guess the hardcoded white transparent value you proposed using in the PR won't work with custom theming either.
