### ISSUE TITLE
Advanced audio settings for Jitsi

### ISSUE THREAD

**Issue by DashieTM** [vector-im/element-web#21687]
#### What would you like to do?
The current implementation of video rooms is easy to use, but removes a lot of settings and features that one could normally adjust.
A good example is the video sharing feature that was very welcome with the regular jitsi.

My proposal here is to create a new settings tab (likely inside element settings) that should offer the the following settings: 
    - enable/disable **noise suppression** (sometimes it doesn't exactly do what it is supposed to) _(not implemented in jitsi)_
    - enable/disable **automatic volume gain** (often amplifies noise and often unwanted in general) _(not implemented in jitsi)_
    - adjustable **voice activation** (more reliable than noise suppression alone) _(not implemented in jitsi)_
    - more settings like these:
![image](https://user-images.githubusercontent.com/72016555/161787504-5eb479e8-a9ff-41d8-baeb-549aab047edd.png)
    - **screen share fps options** (default on jitsi is 5 fps, that is pretty much unusable)
![image](https://user-images.githubusercontent.com/72016555/161786512-4451dfcf-6025-4012-8b6a-2bc784c78025.png)

A list of features that are implemented in jitsi but not in the current voice rooms:
  - video sharing
![image](https://user-images.githubusercontent.com/72016555/161786992-0cba0293-027e-4c5c-9129-821e47d35812.png)
  - reactions
![image](https://user-images.githubusercontent.com/72016555/161787130-9977d56f-b226-4474-8c4d-69f7a758b152.png)
  - moderation 
  - changing backgrounds
  - all of these
![image](https://user-images.githubusercontent.com/72016555/161790719-0705bdf5-514a-4d32-baa6-a8c2449ef261.png)

#### Why would you like to do it?
While simple calls can already be done just fine, it would drastically improve the experience of these rooms to something similar to discord. 
Many of these defaults sadly do often not work as they are intended to.
I regularly talk to someone who currently has a baby, so as you can expect the baby will be quite vocal while we talk. (no worries that persons partner does care for the baby during that time)
What usually happens is that the volume gain tries to amplify the babys voice which is rather unwelcome. And the missing voice activation ensures I always hear everything.

Obviously this is not the only case where these features are quite nice. Any noise that doesn't get suppressed by the filter will be quite annoying at some point.

For the rest of the features: It just makes sense to achieve parity as one would otherwise just use the jitsi widget instead.

#### How would you like to achieve it?
- The noise suppression and automatic volume gain are booleans in jitsi that could be set to true or false in a setting inside the voice room or rather inside the regular settings of element.
- voice activation is a bit more tricky as jitsi does not seem to have anything implemented, I tried to find a solution for the standalone jitsi-meet but due to my limited experience with web development I couldn't finish something that worked.
- The rest are implementations of the voice rooms that would need to be adjusted to fit the rest of the jitsi features.

### Additional context

I absolutely understand that video rooms are in development right now, which is why I am making this request now instead of later. 
If any of these are already implemented in another version or if this was already requested then I humbly apologize.

**In any case a big thanks to the element/matrix team for an awesome messaging client and voice/video chat application!**

**Comment by DashieTM** [comment]
I did some more digging, apparently you can set these flags in a browser or even inside a link to get it done: 
![image](https://user-images.githubusercontent.com/72016555/161853430-a9e6ab0a-7868-487f-a18f-9fe5b9cccfef.png)
perhaps like this: https://jitsi.riot.im/FJfDIRKXoziupWDXPvmatrixorg8bnv8zlihlu#config.disableHPF=true&config.diableNS=true&config.disableAGC=true

these options are also found in lib-jitsi-meet and jitsi-meet itself, I assume lib-jitsi-meet is more important here: 
![image](https://user-images.githubusercontent.com/72016555/161853645-fcb87827-710d-4474-a1ec-2334556a106e.png)

**Comment by dbkr** [comment]
I think this is just referring to jitsi calls in rooms rather than the feature that we've been calling, "Video Rooms", right? Either way, this is a meta-bug of lots different things, so would be better at least split out into, "Expose these jitsi settings" or similar. Bear in mind though that jitsi is not in our long-term plan, so these probably won't get attention.

**Comment by DashieTM** [comment]
Yes, it's about these settings. I have made a few buttons for the base settings of jitsi, however, something like voice activation will be more tricky. In this case I will not delve into that issue and instead divert my attention towards the proper system you are working on, I assume it's the element-call?

**Comment by robintown** [comment]
@DashieTM I've repurposed this issue to track *only* the advanced audio settings aspect of this, which is not strictly related to video rooms. If you'd still like to request that more Jitsi features be exposed in video rooms, please open another issue.

**Comment by DashieTM** [comment]
@robintown perfectly fine, I should have probably opened 2 issues at the beginning, the important part to me and a lot of other users trying to ditch discord is likely the audio setting anyways.

**Comment by DashieTM** [comment]
Closing as element call is soon to replace jitsi either way, ((should have done this a while ago.))
