### ISSUE TITLE
Element recent 1.10.x versions unusable due to UI lockup bug

### ISSUE THREAD

**Issue by geckolinux** [vector-im/element-web#21684]
### Steps to reproduce

Hi, I've been using the Element desktop app on openSUSE Tumbleweed for years. Since about a month or two ago, Element has become unusable on my system because of a new bug where the interface locks up. It usually happens a few minutes after starting the app and switching between different 1:1 direct chats with my contacts. Upon switching, it goes into some kind of loop as if trying to refresh/repaint the chat contents, and there is a high-frequency jitter / shaking / flashing effect on the chat input box, previous chat contents, and the scroll bar, making the UI completely lockup. I have to use the process manager to kill all the `element-desktop` processes. I'm using the matrix.org homeserver. My main computer has hybrid/discreet graphics, but I don't use the Nvidia graphics nor do I install the proprietary drivers, so it's basically just a standard Intel UHD Graphics 630 system.

This bug is currently happening to me on the Flatpak version of Element-Desktop (tried v1.10.8 and v1.10.7 and v1.10.6), but it was also happening in that same version range with the element-desktop packages from the openSUSE Tumbleweed repo and also from the [taw00](https://github.com/taw00/element-rpm) Element RPM repo.

I rolled back to this version in the Flatpak repo, which definitely does not have this bug:
Element version: 1.10.3
Olm version: 3.2.8

Possibly related: #8075 and #18899

### Will you send logs?

Depends on the level of sanitization.

**Comment by robintown** [comment]
@geckolinux Does https://github.com/vector-im/element-web/issues/21147 look like the issue you're experiencing, or is it different?

**Comment by geckolinux** [comment]
Hi @robintown thanks a lot for the fast triage. Yes, that does indeed look like what I'm seeing. Sorry I didn't find that one, I tried searching but it's hard to find the right words to describe this bug. Close this as a dupe?
