### ISSUE TITLE
Opening a Jitsi widget leaves you with a stuck PIP

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21681]
### Steps to reproduce

1. Open a Jitsi widget in a room (n.b. not a video call button)
2. Join and exit the jitsi
3. Every room you subsequently look at has a Jitsi PIP open, which you then can't get rid of

#### What did you expect?

PIP should only apply to Video calls, not random widgets that happen to be in a room.

### Application version

nightly

### Will you send logs?

No

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21648, assuming your Nightly is a few days stale
