### ISSUE TITLE
Changing power levels from 'Admin' to '100' results in a warning

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21682]
### Steps to reproduce

1. Create a new room
2. In that room, open your own user info
3. Change your role from 'Admin' to 'Custom level (100)'
![Screenshot 2022-04-05 at 09-07-47 Element File transfers](https://user-images.githubusercontent.com/48614497/161760687-a0d1c220-af9f-481f-b977-932d34a23c29.png)
5. Click in the input box, and then click out of it

#### What did you expect?

Nothing to happen, since 'Admin' is the same role as 'Custom level (100)'.

#### What happened instead?

A warning pops up:

![Screenshot 2022-04-05 at 09-07-33 Element File transfers](https://user-images.githubusercontent.com/48614497/161760890-e81c9a2c-1a08-49a8-8312-2a0da5aec3bc.png)

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.2

### URL for webapp

develop.element.io

### Application version

Element version: b79133c6947b-react-4f6b9394260b-js-b8321290f823 Olm version: 3.2.8

### Homeserver

Synapse 1.55.0

### Will you send logs?

No

**Comment by Jumeb** [comment]
@robintown I would love to work on this issue
Can you please assign it to me.

**Comment by robintown** [comment]
Sure! You're assigned now.

**Comment by Jumeb** [comment]
> Sure! You're assigned now.

I could not replicate your same exact problem, but I found out the following

1. If I try to demote my self to a moderator or default, I am being warned and I take cancel
2. But the value moderator or default remain, then when I try to get my Role back as Admin I am being warned.

I don't know if I solve my problem it will solve yours, so I am just going to solve the problem I have.

**Comment by robintown** [comment]
@Jumeb Please reference this video to reproduce the issue:

https://user-images.githubusercontent.com/48614497/161807037-9d55a718-7ebf-4708-bd3c-7b2614dc5c8d.mp4

**Comment by Jumeb** [comment]
> @Jumeb Please reference this video to reproduce the issue:
> 
>  resize.mp4

Thanks, I can reproduce the error
