### ISSUE TITLE
Element Web calls don't work if /thirdparty/user/im.vector.protocol.sip_virtual is not implemented

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#21680]
### Steps to reproduce

1. Connect to Conduit homeserver
2. Start a voice call
3. See this request fail in devtools:
`GET https://matrix.redacted.com/_matrix/client/r0/thirdparty/user/im.vector.protocol.sip_virtual?native_mxid=@testuser2:REDACTED.com`

From web to android and android to web. (both users on the same conduit server)
If web calls android, CORS error (because /thirdparty is not implemented). Nothing happens UI wise.
If android call web, on android I hear the ring, on the web I see "Missed call" automatically, android keeps ringing until I hang up

**Comment by vi** [comment]
Is there a workaround available?
I.e. some easy modification of Element Web or a backend server that allows the call to proceed?
