### ISSUE TITLE
Edit fallbacks are leaking into the timeline on Nightly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21694]
### Steps to reproduce

1. Launch the app
2. Look at the timeline for messages which arrive in the incremental sync
3. Note that edits are not shown correctly; the fallbacks are showing rather than being aggregated correctly - instead the edit is shown as an emote after the edited message?
4. This may require hidden events to be enabled (but even if so, the edit should be hidden, surely, not leaking into the timeline)

<img width="249" alt="Screenshot 2022-04-06 at 10 59 07" src="https://user-images.githubusercontent.com/1294269/161950374-7be98cab-b2ff-4cc1-a9e9-3acf2ce1fb03.png">

#### What did you expect?

Edits to be displayed correctly

#### What happened instead?

Edits leak into the timeline now (if show hidden events is enabled?)

### Operating system

macOS

### Application version

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Half-Shot** [comment]
Confirmed that this only happens with hidden events turned on.

**Comment by ara4n** [comment]
this basically makes "show hidden events" unusable, thanks to the extreme noise of the edits.

please can we un-regress it? i depend on "show hidden events" this when demoing Matrix.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7962
