### ISSUE TITLE
Bridged WhatsApp messages not marked as read in WhatsApp

### ISSUE THREAD

**Issue by kalikiana** [vector-im/element-web#21698]
### Steps to reproduce

1. I'm looking at Element, responding, reading etc
2. I'm checking my phone to find all of the same messages unread
3. I'm also seeing unreads for my own messages

Not sure if I should've filed this against https://github.com/mautrix/whatsapp but I have no idea about the configuration on One and wether this would be an upstream issue or not.

I also tried changing both **Read Marker lifetime** settings and leaving the message open longer but nothing changed.

#### What did you expect?

I expect read status to be mirrored, like with WhatsApp web, or with the Telegram brdige.

#### What happened instead?
WhatsApp seems unaware of any changes in read status.

### Browser information

Chrome 100

### URL for webapp

https://one.element.io/

### Will you send logs?

No

**Comment by kalikiana** [comment]
Maybe mautrix/whatsapp/issues/450 is related?

**Comment by t3chguy** [comment]
Yeah this issue should be either reported to EMS/ Element One's support or the bridge. Element Web has no whatsapp specific code.
