### ISSUE TITLE
Inconsistent grammer in device sign out modal

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#21699]
### Outcome

This modal appeared while trying to sign out **a single device** from my user settings.

![image](https://user-images.githubusercontent.com/1342360/162008086-0288f840-bd40-4b23-94f5-40590fd8084f.png)

The title talks of multiple devices, whereas the content implies there is only one device. The content is correct, though in either case both the title and content should match the number of devices they're talking about.

Also, if we're in the area, having both the title and content text be nearly the same seems redundant. It might be nicer to have the title as "Are you sure?". But that's a separate matter :)

### Steps to reproduce

1. Navigate to Settings -> Security & Privacy
2. Check the box next to one of your devices
3. Click the red "Sign out 1 selected device" button.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022040101, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by EECvision** [comment]
Hi @anoadragon453, I am an outreachy applicant. Please can you assign me this issue. Thank you.

**Comment by anoadragon453** [comment]
@EECvision I don't have the authority to do that, but I (and hopefully others) can see that you've submitted [a PR](https://github.com/matrix-org/matrix-react-sdk/pull/8253) to fix this. Thank you for doing that!

**Comment by EECvision** [comment]
Okay, thank you.

**Comment by SimonBrandner** [comment]
> Please can you assign me this issue

Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)
