### ISSUE TITLE
Element search should understand matrix.to links

### ISSUE THREAD

**Issue by axelsimon** [vector-im/element-web#21695]
#### What would you like to do?
People are likely to copy-paste a matrix.to URL and think that's the identifier of the room they want to join, and then use the search function (<kbd>ctrl</kbd>+<kbd>K</kbd>) to find it.

Search should be smart enough to recognise a matrix.to link (such as https://matrix.to/#/#webrtc:matrix.org) and strip everything before the room ID to help the user find what they are looking.

#### Why would you like to do it?
Reduces prior knowledge needed to use the matrix ecosystem.

#### How would you like to achieve it?
Enhance search on Element web (and Android and iOS).

### Have you considered any alternatives?

Improve matrix.to to reliably detect any running Element instance. Currently, it has no way of knowing that myrandomriot.example.com running in a random tab is actually an instance of Element that could be used to join the target of the matrix.to link.

Webmails are capable of registering with Firefox's applications, maybe Element instances could do the same, for a `matrixto` content type.

**Comment by bolu-tife** [comment]
Hello, I would like to work on this.

**Comment by SimonBrandner** [comment]
> Hello, I would like to work on this.

Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by bolu-tife** [comment]
Thank you. I have drafted a pull request for this issue.

**Comment by HarHarLinks** [comment]
> strip everything before the room ID

just a clarification, identifiers such as `#element-dev:matrix.org` that start with a `#` are aliases, while room IDs are random looking strings with a `!` prefix and, depending on the room version(?) a server name postfix.

**Comment by JeanPaulLucien** [comment]
I support this feature, because something strange are going with memory in these places.

**Comment by weeman1337** [comment]
Currently pasting a matrix.to link shows this message

> Failed to find the following users
> 
> The following users might not exist or are invalid, and cannot be invited:
> https://matrix.to/#/@bob:example.com
