### ISSUE TITLE
Multiple effects can play at the same time

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21701]
### Steps to reproduce

1. Send `/confetti`
2. While the confetti effect is playing, also send `/spaceinvaders`

#### What did you expect?

When the space invaders effect starts playing, the confetti effect should be stopped.

#### What happened instead?

Both effects play at the same time, resulting in flickering:

https://user-images.githubusercontent.com/48614497/162023607-79497747-9e70-4dc4-9636-20ddb4b50dc1.mp4

### Operating system

NixOS unstable

### Browser information

Firefox 98.0.2

### URL for webapp

develop.element.io

### Application version

Element version: ecf1c41f7c09-react-6bf7fef92bc5-js-3322b47b6d17 Olm version: 3.2.8

### Homeserver

Synapse 1.56.0

### Will you send logs?

No

**Comment by EECvision** [comment]
Hi @robintown, I am outreachy applicant. Please, can you assign me this issue

**Comment by robintown** [comment]
You're assigned now 👍

**Comment by EECvision** [comment]
> You're assigned now 👍

Thank you

**Comment by HarHarLinks** [comment]
> should be stopped

:frowning_face:

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/16015
