### ISSUE TITLE
Threads don't respect "order by unread first" ordering in room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21700]
### Steps to reproduce

1. Be in a room with threads
2. Have that room set to Mentions Only
3. Order your room list by "unread first"
4. Look at a different room
5. People continue to engage with a thread
6. Room doesn't move to top of room list

#### What did you expect?

The room to follow the regular ordering of the importance algorithm.

#### What happened instead?

The room was unread, but not in a useful place in my room list.

Likely regression following https://github.com/matrix-org/matrix-react-sdk/pull/8202

### Operating system

Windows 10

### Application version

Nightly (2021-04-06)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by turt2live** [comment]
upgraded to S-Major because "disabling threads" is not satisfactory as a workaround.

**Comment by t3chguy** [comment]
Confirming with product how thread responses will affect the room list

**Comment by turt2live** [comment]
This is just a bug? There was a message in the room and the room was not marked as unread in the room list. The message was not a thread response.

**Comment by t3chguy** [comment]
@turt2live which was it? Marked or not marked as unread...

> The room was unread, but not in a useful place in my room list.

vs

> There was a message in the room and the room was not marked as unread in the room list.

**Comment by t3chguy** [comment]
@turt2live https://github.com/vector-im/element-web/issues/21416 ?

**Comment by turt2live** [comment]
that sounds like it, yea. 

apologies for the noise 😅

**Comment by gsouquet** [comment]
Should a message in a thread be characterised as new activity in a room and bump the room up the list?

The `RecentAlgorithm` currently only inspect the last timestamp from the room timeline and orders based on that. However, all rooms with an unread counter are automatically bump to the top of the list.
We are in a weird situation where if a room is in position 5 in the list, receives a thread reply, it will be moved in position 1, and as soon as that message will be viewed and the room blurred, it will be moved back to position 5.

I would like to suggest to make the `RecentAlgorithm` look for the latest timestamp across all known timelines in a room

**Comment by daniellekirkwood** [comment]
The counter in the room list should increment with thread timeline and main timeline messages. As the room list counter is increasing, and we do not distinguish between main timeline or thread timeline in the count, it would be confusing for users if the room list did not reflect this new and increasing activity in the room list order. Therefore, we want for the room list activity to change for both main timeline and thread timeline messages when either of those things are incrementing the count in the room list view.
