### ISSUE TITLE
Images uploaded with uppercase file extension are not uploaded as images

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#21709]
### Steps to reproduce

1. Where are you starting? What can you see?
Upload a jpg file with *:JPG as Name

This is the same picture.
One is .JPG
the other is .jpg

![grafik](https://user-images.githubusercontent.com/30293477/162224350-35eb6f7f-0b52-4444-bf4c-6504eeaa7f34.png)

#### What did you expect?
See the picture
#### What happened instead?
It's only an attachment

### Operating system

Windows, Ubuntu Mate 20.04

### Application version

Version von Element: 1.10.8 Version von Olm: 3.2.8

### How did you install the app?

Downloaded exe from element.io / package source of element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
I can't reproduce this, although I was trying on macOS rather than windows or Ubuntu. Could you also specify how you're uploading? There are several ways and they may not all follow identical code paths.

**Comment by JokerGermany** [comment]
Sorry my bad, the Problem was not a uppercase Problem, the PRoblem is that it was an 0kb File which was uploaded.
(I Think the camera disconnected and element didn't recognize something went wrong)
The issue can be closed, but a uploadcheck would be nice
