### ISSUE TITLE
Reporting messages is broken

### ISSUE THREAD

**Issue by pandafy** [vector-im/element-web#21713]
### Steps to reproduce

On `develop.element.io`, when I tried to report messages the reporting failed. 

#### What did you expect?
Message being reported successfully. 

#### What happened instead?

```
Cannot read properties of undefined (reading 'getRoomId')
```

![Screenshot from 2022-04-08 00-39-26](https://user-images.githubusercontent.com/32094433/162279894-739278b5-d8de-4192-aaaf-aa363685932a.png)

### Operating system

Ubuntu 20.04

### Browser information

Chromium Version 100.0.4896.60 (Official Build) snap (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cec31d0e714e-react-233278546bda-js-dde4285cdf5f Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

 - https://github.com/matrix-org/element-web-rageshakes/issues/11903
 - https://github.com/matrix-org/element-web-rageshakes/issues/11893

**Comment by turt2live** [comment]
This does not block the release - affects develop-only code

**Comment by BuiHuynhNam** [comment]
Hi, when i updated v1.10.9 latest version from **git pull upstream master**, It failed to start

![Screen Shot 2022-04-14 at 10 54 30 AM](https://user-images.githubusercontent.com/44636715/163310651-a2158e1d-d0e0-44b8-a754-0ac8004f896a.png)

**Comment by turt2live** [comment]
@BuiHuynhNam it looks like you're running into a different error than what is described here. Please visit [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) on Matrix for support.

**Comment by BuiHuynhNam** [comment]
> it looks like you're running into a different error than what is described here. Please visit [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) on Matrix for support.

Thank you
