### ISSUE TITLE
Hidden events cause room to be marked as unread

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#21725]
### Steps to reproduce

0. Use latest develop version
1. Enable showing hidden events in timeline
2. Receive a hidden event (e.g. a reaction)

#### What did you expect?

Room is not marked as unread.

app.element.io works as expected (with hidden events enabled manually), so it seems like a recent regression.

#### What happened instead?

Room is marked as unread and bumped to the top of the list.

### Operating system

Ubuntu 21.10

### Browser information

Firefox 100.0b3

### URL for webapp

develop.element.io, mau.chat

### Application version

Element version: cec31d0e714e-react-9f8c208516cc-js-f963feab0f5d

### Homeserver

Synapse 1.56

### Will you send logs?

No

**Comment by t3chguy** [comment]
Possibly fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8379 - testing

**Comment by tulir** [comment]
Can confirm it's not happening anymore :tada:, thanks!
