### ISSUE TITLE
Keep developer guides for projects updated

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21728]
#### What would you like to do?

I would like to have the latest developer guides for the projects under `matrix-org` such as `matrix-react-sdk` which reflect the latest internal discussion. For example, I would like to have a style guide on usage of spacing variables in https://github.com/matrix-org/matrix-react-sdk#developer-guide with the graphic on https://github.com/matrix-org/matrix-react-sdk/pull/7456

#### Why would you like to do it?

I think that unlike Element, a software of vector-im, SDKs for Matrix should provide the latest, up-to-date documentation which reflects the latest internal discussion, because I think that publishing a guideline and keeping it updated helps outside developers to work on Matrix without being worried about the possibility that their works could be based on an obsolete spec, etc. Personally I feel it is not fair to tell a developer that his/her work is not based on the latest spec, even if it is not available to him/her.

#### How would you like to achieve it?

I would like to ask the developer team of Matrix to keep the developer guides of projects under `matrix-org` updated, for example, by requiring a PR to include documentation update at the same time if the change is related to the spec change or an internal discussion.

### Have you considered any alternatives?

One of the other alternatives could make private internal rooms public (whether guests are allowed to send a message or not) to let them follow the discussion and spec change.

**Comment by luixxiul** [comment]
Please transfer this issue if there is another proper place, thanks.

**Comment by luixxiul** [comment]
Thank you very much for listing the links.

I've been specifically expecting the guide on styling with CSS other than one on https://github.com/matrix-org/matrix-react-sdk#developer-guide (which only explains how to name elements), especially design specifications and guidelines about implementation, such as about usage of variables, font weight (what to be styled with a bold font), font color (which color to be used for a link; red or green), font size, spacing, overflow (how to handle text overflow), and other bunch of stuff for UI design and its implementation.

**Comment by t3chguy** [comment]
Such doesn't exist yet, and will likely not exist coherently until the Design team finishes Compound (UI kit) and we can start applying it to the codebase. Right now there isn't much consistency.

**Comment by andybalaam** [comment]
No specific action for this issue at the moment, since we're not clear what the guidelines will be.
