### ISSUE TITLE
Opening a permalink to a message in a thread then entering a different room complains about a missing message

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#21742]
### Steps to reproduce

1. Enter Room A. Room A contains no threads. Room A contains a permalink to a message in a thread of Room B.  
![Room A with the mouse hovering over the permalink to the message in Room B](https://user-images.githubusercontent.com/3933349/162784122-f7714771-477d-4ebd-90de-161ceb10c221.png)
3. Click on the link. Room B opens. The thread panel of Room B opens and scrolls to the message.  
![Room B with the thread open](https://user-images.githubusercontent.com/3933349/162784178-059934cb-a958-4f42-bab6-518ea2161e62.png)
5. Switch back to Room A  
![Room B with the mouse hovering over the button to switch back to Room A](https://user-images.githubusercontent.com/3933349/162784217-9852eba0-8a99-400b-90f7-79aab4ce73e6.png)

#### What did you expect?

Either the thread panel closes or the thread panel shows an empty UI.

#### What happened instead?

Element Web shows a dialog containing the following message:

Failed to load timeline position: Tried to load a specific point in this room's timeline, but was unable to find it.

![Dialog with the aforementioned error message](https://user-images.githubusercontent.com/3933349/162784384-33491cc7-1e55-4492-82bc-d44477313752.png)
 
 (This does not happen every time, but almost every second time)

### Operating system

Ubuntu 21.10 (impish)

### Browser information

Firefox 98.0.2 (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cec31d0e714e-react-f648140d0c72-js-286500e335e4 Olm version: 3.2.8

### Homeserver

chat.element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
I had this happen and it was an unexpected Synapse error claiming an event I myself sent (and existed in my DB) did not exist.

![image](https://user-images.githubusercontent.com/2403652/166655839-89e6a63e-e65d-44be-87f8-a520e69bd59a.png)

![image](https://user-images.githubusercontent.com/2403652/166655859-e1a0482f-247d-458d-a1c0-8dc52aa13971.png)

**Comment by HarHarLinks** [comment]
i'm submitting a rageshake, i did the following:
1. create a permalink to a thread message in room A (public, no e2ee)
2. send the link in room B (e2ee, link previews enabled)
3. click the link

At this point one of several things can happen:
- the thread panel in room B opens (but is empty)
- navigate to room A but thread panel does not open
- navigate to room A and thread panel opens

In the last case, then returning to room B will have its thread panel open as well, and display the error "could not jump to the requested point in the timeline" (wording similar).
Unless I close the thread panel, this issue remains.

**Comment by gsouquet** [comment]
Was fixed as part of https://github.com/matrix-org/matrix-react-sdk/pull/9356 
Can not reproduce anymore
