### ISSUE TITLE
Threads: Response to Thread showing as latest message for All Threads in the Thread list.

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21747]
### Steps to reproduce

I sent a thread message in one thread "Thanks, I'm happy to translate" and when I go to the Thread list the entire thread list shows my message in one thread as the most recent response in all the threads...

<img width="416" alt="Screenshot 2022-04-12 at 10 27 58" src="https://user-images.githubusercontent.com/89144281/162928602-55d4e310-227b-4619-a46f-58e904d06736.png">

#### What did you expect?
To see the actual message thats the latest in the thread itself
#### What happened instead?
Saw my message as latest for all threads in the thread list (does not appear when you click in)

### Operating system

Mac Monterey

### Application version

Element Nightly version: 2022040901
Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please update your nightly, this has already been fixed.
