### ISSUE TITLE
Replying to search results in threads is broken

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#21750]
### Steps to reproduce

1. Search for a threads response
2. Click Reply on one of the results

#### What did you expect?

Thread to open with the selected event ready for a reply

#### What happened instead?

The search closed, thread did not open, and the reply prompt was over the main timeline

### Operating system

N/A

### Browser information

N/A

### URL for webapp

N/A

### Application version

1.10.9

### Homeserver

N/A

### Will you send logs?

No

**Comment by novocaine** [comment]
@t3chguy can you indicate what you need from design please?

**Comment by t3chguy** [comment]
The behaviour of the UX.

Clicking Reply in the Search view closes the search view and makes things happen in that same view
But what if the result you're seeing is actually from within a thread, we can't show it in the main timeline so what do we do? 

1. Close the main search view, open your result in the thread panel
2. Just open your result in the thread panel without closing your search view

**Comment by gsouquet** [comment]
This is now working, closing as fixed. Do not know what pull request fixed it.
