### ISSUE TITLE
Implement improved spacing for the thread list and timeline.

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21759]
**Changelog**

- Changed root message avatar size to 32px (the previous value of 36px was a design bug 🙃🐛).
- Changed the unread dots size to 8px and adjusted their spacing, bringing them closer to the timestamp and leaving more breathing room for the hover state.
- Updated the inner padding for the thread panel and around the avatar for better visual balance and to better fit 12-hour timestamps.
- Updated padding values for hover states for better visual balance.

Please refer to the annotations/redlines for the expected spacing.

**Design**

→ [Figma — Redlines](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=4447%3A490693)
→ [Figma — Mockups](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A182996)

**Snapshot**

![Threads - Updated spacing](https://user-images.githubusercontent.com/60790/163165158-3865ffed-53f0-4c30-a315-5975b5f3a751.png)

**Comment by luixxiul** [comment]
Working on the thread list:

Without the scroll bar ↓
![list1](https://user-images.githubusercontent.com/3362943/163555887-279a90ea-b226-45a5-a845-f598d05e02c9.png)

With the scroll bar ↓
![list2](https://user-images.githubusercontent.com/3362943/163555923-972e48da-3115-4929-b954-523032e2bda7.png)
