### ISSUE TITLE
feature_thread: false in config.json doesn't hide the reply in thread icon

### ISSUE THREAD

**Issue by tgurr** [vector-im/element-web#21753]
### Steps to reproduce

1. Main chat(room) view
2. Hover a message
3. Observe the available reply options
4. Notice "Reply in thread" icon is still shown, despite the feature being disabled in config.json
![feature_thread_false](https://user-images.githubusercontent.com/414984/162962614-fe155724-8f97-442a-80a9-667ed09da204.png)

Relevant config.json part:
```
[...]
    "show_labs_settings": false,
    "features": {
        "feature_spotlight": false,
        "feature_thread": false
    },
[...]
```

Labs is correctly not shown/accessible from settings:
![feature_thread_false_02](https://user-images.githubusercontent.com/414984/162962823-9bf8240e-bea8-482c-9f30-cab05509c12c.png)

#### What did you expect?
"Reply in thread" icon is **not** shown when the feature is disabled in config.json
#### What happened instead?
"Reply in thread" icon is shown, despite the feature being disabled in config.json

### Operating system

Linux

### Browser information

Chrome 100.0.4896.88

### URL for webapp

element hosted in an restricted environment

### Application version

Element: 1.10.9, Olm: 3.2.8

### Homeserver

Synapse 1.56.0

### Will you send logs?

No

**Comment by dbkr** [comment]
I believe this is intentional and is the feature in its transition phase from labs to stable - someone should be able to confirm

**Comment by t3chguy** [comment]
I think given the config dictates that the Beta cannot be enabled, the prompts to enable it should not be present.
