### ISSUE TITLE
Taking up too much space

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#21758]
### Steps to reproduce

1. Start Element
2. Observe the space being wasted

#### What did you expect?

A sidebar that doesn't take more space than it needs.

#### What happened instead?

This nonsense happened:
![image](https://user-images.githubusercontent.com/152227/163020780-8b15fd64-a416-4508-8788-c527d78c16d0.png)

Also why duplicate the settings cog? It doesn't need to be always visible in the sidebar. It's not *that* important.

### Operating system

Windows 10 21H2

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by thany** [comment]
I would recommend merging the two sidebars again. It never needed this split, there is absolutely no advantage to wasting an entire additional vertical bar for this.

**Comment by thany** [comment]
And suddenly now this happened:

![image](https://user-images.githubusercontent.com/152227/163021758-8f0b4d17-4fb9-4ceb-9efe-0d7257c86533.png)

This "home" appeared. Why is it so brightly bordered? Why is it there? Clicking it doesn't even do anything.

**Comment by thany** [comment]
Actually,

```css
.mx_LeftPanel_wrapper {
  flex-direction: columns;
}
.mx_LeftPanel_wrapper--user {
  flex-grow: 1;
}
```

Now how do I make this permanent? Do you accept a PR?

**Comment by robintown** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18898

**Comment by thany** [comment]
It is not a duplicate.

That one asks to DISBALE it, I'm asking to MERGE it.

Please stop closing my issues willy-nilly. It's really annoying. Especially when I'm facing an already annoying issue.

**Comment by thany** [comment]
Btw, result of my CSS change before it was so rudely interrupted:

![image](https://user-images.githubusercontent.com/152227/163025830-4237d43e-4029-451d-ac81-b9ba7e731e6c.png)

What's better, this or disabling it? Forcing those spaces in a separate sidebar is nonsense either way.

**Comment by robintown** [comment]
I've marked this as a duplicate, because merging the two bars together would be a prerequisite for disabling the spaces bar, as the user menu currently lives exclusively in that bar, so design would almost certainly need to consider them together.

My assumption that this should be resolved by disabling the spaces bar is because it appears that you aren't in any spaces. Unless you're asking for a way to both be in spaces, and at the same time not have the spaces bar take up horizontal real estate?

**Comment by emiliogon** [comment]
@robintown Any time this has been reported over the last year, the issue has been hastily closed as a duplicate of issue #18898.  Except, that issue does not exist.  So, is this feature no longer going to be restored?  Has it fallen through the cracks?  The design is trivial, as should be the implementation.

Along with other users, I've been waiting for this feature to be restored.  I literally never use Spaces, it was shoved into the app without much thought for UX, and I'd much rather have those pixels for chat.  I don't think this is a new feature request, as I remember being able to hide that superfluous sidebar.

**Comment by 2510** [comment]
+1 request for more compact UI. Please reopen and reconsider this issue.

**Comment by BurnyBoi** [comment]
> +1 request for more compact UI. Please reopen and reconsider this issue.

#18898 (and my account) are back :tada:

**Comment by thany** [comment]
It's become WORSE since the last update. WTF
