### ISSUE TITLE
Broke threads sidebar view

### ISSUE THREAD

**Issue by paulvt** [vector-im/element-web#21762]
### Steps to reproduce

1. I opened two Elements on different accounts, and started a test thread in a DM room between the two accounts
2. Writing messages back and forth in de sidebar worked
3. Then I clicked the "<" button next to Thread in the sidebar header to get to the main sidebar view

#### What did you expect?
I expected to go back to the main sidebar view.

#### What happened instead?
I got the "Something went wrong" screen. And now in every room that I click on the "Threads" button in the top right, I get the "Something went wrong" screen and I can never view that room anymore.
This is probably because it remembers the sidebar state per room?

### Operating system

Debian Linux 11 (bookworm)

### Browser information

Firefox 99.0

### URL for webapp

Element Web 1.0.9

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### Homeserver

Synapse 1.54.0

### Will you send logs?

Yes

**Comment by robintown** [comment]
This is fixed on develop and only happens on outdated homeservers.

**Comment by paulvt** [comment]
Thanks for the quick response! I could indeed not reproduce it on develop.
My Synapse is blocked by the database changes, I had not time. I will put more effort in it then 🙂.
