### ISSUE TITLE
Add Smart App Banner to prompt users to download the native iOS app

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#21763]
#### What would you like to do?

Add [Smart App Banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners) to prompt users to download the native iOS app from the App Store.

<img src="https://user-images.githubusercontent.com/558581/163048464-a9018434-f54c-4158-8721-89725ec57feb.png" width="376">

#### Why would you like to do it?

Element Web on mobile is [unusable](https://github.com/vector-im/element-web/issues/14962) and marked as experimental.

#### How would you like to achieve it?

See the *Implement a Smart App Banner on Your Website* section on https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners

### Additional context

Full context for improving the first time user experience for iOS users: https://github.com/matrix-org/matrix.to/issues/263

**Comment by t3chguy** [comment]
I wonder if the smart banner can work dynamically, because we can't hardcode it into index.html as the iOS app being pointed to may be the wrong one depending on the deployment - and given Element is all static files, would need to be injected after reading config.json

**Comment by t3chguy** [comment]
https://stackoverflow.com/questions/31289530/load-ios-smart-app-banner-through-javascript claims it doesn't work if injected async, but is rather old so may no longer be the case

**Comment by niquewoodhouse** [comment]
[Figma](https://www.figma.com/file/TL0eVJTMMbG1Pahpa0poBO/%5BMatrix.to%5D-Add-smart-banner?node-id=2%3A402) example of smart app banners.

**Comment by t3chguy** [comment]
As per my comments above, the smart app banner for iOS may not be possible due to the async nature of our purely client-side SPA config mechanisms (config.json is read by the client, not injected by the server) - but does need more testing by someone with an iOS device.

**Comment by gsouquet** [comment]
@t3chguy I can see that we added code for a smart banner as part of https://github.com/vector-im/element-web/pull/22224 in `/mobile_guide`
I believe we can not inject dynamic app id indeed.

Considering marking this issue as complete and folks who fork the app can change the app id.

**Comment by t3chguy** [comment]
@gsouquet that PR didn't add any such thing 😇

**Comment by t3chguy** [comment]
I think another issue is that some iOS browsers (cough iPadOS) lie and claim to be a desktop browser, so the app banner won't be shown as the user won't be taken to the mobile_guide

**Comment by t3chguy** [comment]
> the following meta tag was added

Yes, after being removed from a few lines lower, by the auto-formatter

**Comment by gsouquet** [comment]
![IMG_8785A0432EDD-1](https://user-images.githubusercontent.com/769871/202426890-1a32a243-131a-4f9c-b6a7-c8c064bb2ac5.jpeg)

Closing as this feature already exists on Element Web.
