### ISSUE TITLE
Thread return button error

### ISSUE THREAD

**Issue by ploafmaster** [vector-im/element-web#21760]
### Steps to reproduce

I was in a room with a thread - I clicked the thread to open and typed a message. Then I clicked the `<` button in the top left of the thread panel and got the "something went wrong" screen. It will not go away even after clearing cache and reloading, or after quitting the desktop client and restarting. I already submitted debug logs to this effect.

### Outcome

I don't know what to expect - the button I clicked was not the `X` button to close.

### Operating system

macOS 12.3.1

### Application version

Element version 1.10.9

### How did you install the app?

This was an auto update from within the app, which was installed via DMG file from the 

### Homeserver

matrix.joshmock.com

### Will you send logs?

Yes

**Comment by dbkr** [comment]
We don't seem to have got for this yet

**Comment by t3chguy** [comment]
This is fixed on develop and only happens on outdated homeservers.
