### ISSUE TITLE
Show URL when hovering link in Element Desktop

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#21769]
#### What would you like to do?

When hovering a link in a message, it would be helpful if the target URL would be shown somewhere.

![Screenshot 2022-04-13 at 09 50 50](https://user-images.githubusercontent.com/1137962/163127479-231fc456-b8c3-4b80-a3b9-472a98770622.png)

In Element Web, the browser itself usually solves this problem, e.g. by showing the URL somewhere in the bottom of the window. However, in Element Desktop the URL only shows when I right click the link.

![Screenshot 2022-04-13 at 09 50 58](https://user-images.githubusercontent.com/1137962/163127491-0c75d677-377b-48ee-86b4-c1802bff1928.png)

#### Why would you like to do it?

I want to know where a link is taking me before clicking it (e.g. to prevent phishing).

Right-clicking is not very intuitive, possibly also not accessible.

#### How would you like to achieve it?

Display a tooltip with the target URL when hovering a link in Element Desktop.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/6532
