### ISSUE TITLE
Make Developer Tools accessible through GUI

### ISSUE THREAD

**Issue by Xiretza** [vector-im/element-web#21773]
#### What would you like to do?

Currently, the "Developer Tools" modal seems to only be accessible by sending the "/devtools" command to a room. It should also be accessible through a more discoverable graphical menu.

#### Why would you like to do it?

I don't know any concrete design policies for Element, but personally I find the current state quite surprising - with a primarily graphical application such as Element, I expect all functionality to be accessible through some menu or another and to not have to resort to a command line interface.

#### How would you like to achieve it?

The ideal place for it would probably be in the "Advanced" tab of the Room Settings dialog (entered either 1. by clicking the three dots on or right clicking a room/space -> Settings, 2. by clicking the room name on the top of the room window -> Settings, or 3. via "Room Info" sidebar -> Room settings). Currently, this tab only contains the room ID and room version.

**Comment by robintown** [comment]
It is accessible through the GUI as described in https://github.com/vector-im/element-web/issues/21771#issuecomment-1097996672, though I agree that the setting to enable developer mode in the first place could stand to be accessible somewhere in the non-developer GUI

**Comment by Xiretza** [comment]
Agreed - while it is accessible through the GUI when developer mode is active, the only way to enable developer mode is through the exact menu in question. Making it possible to enable developer mode through the main Settings menu would also solve this catch-22, but the main Settings menu doesn't (currently) have an "Advanced" tab that this setting would obviously fit into.

**Comment by t3chguy** [comment]
> Making it possible to enable developer mode through the main Settings menu would also solve this catch-22, but the main Settings menu doesn't (currently) have an "Advanced" tab that this setting would obviously fit into.

So this used to be possible but requires show_labs_settings to be enabled in the config.json so it was actually restrictive to you needing a development build/config.

**Comment by MadLittleMods** [comment]
Adding it back to **Room settings** -> **Advanced** when developer mode is enabled would be nice 👍

> It is accessible through the GUI as described in https://github.com/vector-im/element-web/issues/21771#issuecomment-1097996672, though I agree that the setting to enable developer mode in the first place could stand to be accessible somewhere in the non-developer GUI

I completely missed the quick settings menu at bottom of the space bar and thought it was only toggle-able via `/devtools` which sucks when you're trying to compose a message with some copy-pasted event ID's.

**Comment by robintown** [comment]
It isn't a room-level setting though, it's device level, so it would probably belong somewhere in user settings

**Comment by t3chguy** [comment]
@MadLittleMods 

> Adding it back to Room settings -> Advanced when developer mode is enabled would be nice 👍

It is also in the room menu

<img width="279" alt="image" src="https://user-images.githubusercontent.com/2403652/165046053-e0633f66-892e-4b28-a2d1-92fe3d9f5264.png">

**Comment by fnwbr** [comment]
Thanks for all the hints you people gave.
At the same time I agree that it would be nice to make this even more accessible.

Adding the "Enable developer mode" toggle to the "All settings" > "Labs" > "Developer" section would be quite nice.

**Comment by MadLittleMods** [comment]
> Adding it back to **Room settings** -> **Advanced** when developer mode is enabled would be nice 👍

To add another reason why opening from the room list -> **Settings** -> **Advanced** would be nice is if you want to check your notification debug status without opening up the room.

**Comment by weeman1337** [comment]
I am currently working on https://github.com/matrix-org/matrix-react-sdk/pull/10634 . I think all suggestions from here are good additions:

- Option to enable developer mode in settings
- Open dev tools from room settings
- If dev mode is enabled a menu item in the room list

**Comment by daniellekirkwood** [comment]
Hey there! 

We've made the decision to leave the Developer Tools toggle inside of the /devtools command. Once developer tools has been activated, you're now able to access the developer tools for a room using the room context menu and the room header menu. 

We do not want to reveal the Developer Tools toggle at a higher level (in General Settings) at this stage. 

Thanks for your feedback. I'll be closing this issue but if you have other ideas, comments, or user problems feel free to raise them.

**Comment by MadLittleMods** [comment]
The last comment makes it seem like nothing more is happening from what we currently have in the UI. But reading closely, this does actually include an improvment:

> Once developer tools has been activated, you're now able to access the developer tools for a room using the room context menu

Which is being addressed by https://github.com/matrix-org/matrix-react-sdk/pull/10635

![](https://user-images.githubusercontent.com/6216686/232704516-de1820f8-8eca-4394-9253-b3b6cd09f81c.png)

This solves my use case of being able to open notification debug and reference other rooms without opening the room 👍
