### ISSUE TITLE
Pressing the back button on a thread makes the room unusable

### ISSUE THREAD

**Issue by seancolsen** [vector-im/element-web#21772]
### Steps to reproduce

1. Enable beta threads feature.
2. Open a thread.
3. Click the "<" button.
4. Expect the thread to close.
5. Observe the room to display an error "Something went wrong!"

![Peek 2022-04-13 08-19](https://user-images.githubusercontent.com/42411/163178485-e7e3a330-1764-45df-bb4e-948556084031.gif)

### Work around

If I sign out and back in, then I can access the room again

### Operating system

Ubuntu Linux

### Application version

1.10.9

### How did you install the app?

Ubuntu repository

### Homeserver

http://matrix.mathesar.org

### Will you send logs?

No

**Comment by robintown** [comment]
This is fixed on develop and only happens on outdated homeservers, though we will be releasing a hotfix for this soon.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/21762
