### ISSUE TITLE
Font Size preview doesn't change on changing the message layout

### ISSUE THREAD

**Issue by goelesha** [vector-im/element-web#21782]
### Steps to reproduce

1. Where are you starting? What can you see?
Open appearance in the setting on the element web in the browser. When I change the message layout the font size preview doesn't get changed. Instead, it changes on refreshing the page.

#### What did you expect?
If initially I have IRC message layout set in the appearance settings and now I change it to a modern message layout, then on changing the message layout the font size preview message doesn't get changed on the click instead it gets changed after refreshing.
Initially when layout is set to IRC it looks like this-
<img width="842" alt="Screenshot 2022-04-13 at 11 25 58 PM" src="https://user-images.githubusercontent.com/54431564/163241473-f4b5791b-2b2a-4224-b25e-0e3146a07429.png">
Now as soon as I change the message layout by clicking on modern, I expect the font size preview message to get changed on the click. So I expect this after clicking on Modern now.
<img width="786" alt="Screenshot 2022-04-13 at 11 26 20 PM" src="https://user-images.githubusercontent.com/54431564/163241754-07f12546-29a8-4181-87b5-f5b6506fa19d.png">

#### What happened instead?
On changing the message layout by clicking on Modern, the font size preview message doesn't get changed at the same time. The changes occur after refreshing the page. Something like this occurs-
<img width="808" alt="Screenshot 2022-04-13 at 11 26 07 PM" src="https://user-images.githubusercontent.com/54431564/163241973-88a5972e-39a4-45e9-bd39-688ba23d38a5.png">

### Operating system

macOS

### Browser information

Chrome

### Will you send logs?

No

**Comment by bolu-tife** [comment]
Hello, 
Please I would like to work on this. However, I'm not able to reproduce this error.

**Comment by goelesha** [comment]
> Hello, Please I would like to work on this. However, I'm not able to reproduce this error.

Actually I am Outreachy applicant and I have opened the issue and already working on it.

**Comment by bolu-tife** [comment]
Alright, thanks.
