### ISSUE TITLE
Deleted text shouldn't have share capability

### ISSUE THREAD

**Issue by yaya-usman** [vector-im/element-web#21785]
#### What would you like to do?
I realized if a message is deleted, it stays in the chat space as deleted, also it can be shared as shown in the image below:

![Capture2](https://user-images.githubusercontent.com/38439166/163274983-0efa3359-66b2-44fe-b782-7bec7761c2c9.PNG)

I'll suggest after a chat is deleted each user should be able to delete it entirely from their chat space, `delete/remove` should replace the `share` option as shown in the image above.

#### Why would you like to do it?

For cleaner chat space and better user experience

#### How would you like to achieve it?
Needs inputs from the team, probably i can start working on it based on their guidance and suggestion.

**Comment by Sinharitik589** [comment]
I want to work on this issue .Please assign me.

**Comment by yaya-usman** [comment]
@Sinharitik589 ,sorry i am also an outreachy applicant, so i'll be working on the fix, that's why i opened the issue. @t3chguy can you assign it to me, i'll be dropping a draft PR to this soon

**Comment by turt2live** [comment]
I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.

**Comment by yaya-usman** [comment]
> I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.

Exactly, i was about to say same thing, it needs redesigning. Thanks for your input.

**Comment by asaayushisingh** [comment]
Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You! 

> I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.

Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!

**Comment by yaya-usman** [comment]
> Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> 
> > I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.
> 
> Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!

You don't have to be assigned. You can drop a draft PR. Also as stated up there by @turt2live ,it needs inputs from the design team in order to proceed. But i guess you can still go ahead and drop your PR

**Comment by asaayushisingh** [comment]
> > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> > 
> > > I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.
> > 
> > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> 
> You don't have to be assigned. You can drop a draft PR. Also as stated up there by @turt2live ,it needs inputs from the design team in order to proceed. But i guess you can still go ahead and drop your PR 


Hey! @yaya-usman Sure! I will raise the PR for this issue. Thank you!

**Comment by asaayushisingh** [comment]
> > > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> > > > I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.
> > > 
> > > 
> > > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> > 
> > 
> > You don't have to be assigned. You can drop a draft PR. Also as stated up there by @turt2live ,it needs inputs from the design team in order to proceed. But i guess you can still go ahead and drop your PR

> Hey! @yaya-usman Sure! I will raise the PR for this issue. Thank you!
Hey! @yaya-usman  I could not able to create a new branch to raise the PR.

**Comment by yaya-usman** [comment]
> > > > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> > > > > I feel this is a feature rather than a bug, as all events (even redacted ones) should be sharable. Let's get a product opinion on this.
> > > > 
> > > > 
> > > > Hey! @turt2live I have already solved this issue. Kindly assign me this issue so that i can raise the PR. Thank You!
> > > 
> > > 
> > > You don't have to be assigned. You can drop a draft PR. Also as stated up there by @turt2live ,it needs inputs from the design team in order to proceed. But i guess you can still go ahead and drop your PR
> 
> > Hey! @yaya-usman Sure! I will raise the PR for this issue. Thank you!
> > Hey! @yaya-usman  I could not able to create a new branch to raise the PR.

What's the error it's giving when you try creating a branch? , Also are you sure you have forked this repo to your account?

**Comment by turt2live** [comment]
(please stop using quote reply - there's no threading needed here)

If you're having issues with branching, please use the [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org) room on Matrix.

**Comment by kittykat** [comment]
Hi, thank you for filing this issue. There are use cases for linking to deleted messages, such as when the message contained abusive content and needs to be referred to for moderation purposes.

For this reason, I am going to close this issue on behalf of the product team as won't fix.

If you would still like to contribute to Element, I would recommend checking out existing issues with the "[good first issue](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" label. These should generally contain product and design decisions, which will make it easier to contribute to those issues.
