### ISSUE TITLE
After opting for using 'Threads' beta, the conversations are showing blank for the respective room

### ISSUE THREAD

**Issue by ajinkya-xebrium** [vector-im/element-web#21787]
### Steps to reproduce

1. Click 'Threads' icon in any room and it shows following message wiping out all messages - 
**********************
Something went wrong!
Please [create a new issue](https://github.com/vector-im/element-web/issues/new/choose) on GitHub so that we can investigate this bug.

If you've submitted a bug via GitHub, debug logs can help us track down the problem. Debug logs contain application usage data including your username, the IDs or aliases of the rooms you have visited, which UI elements you last interacted with, and the usernames of other users. They do not contain messages.

**********************
**There is no way to  bail out from the 'Threads' beta.** 

### Outcome

Existing messages should not have wiped out. 

### Operating system

macOS

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Will you send logs?

Yes

**Comment by robintown** [comment]
See https://github.com/vector-im/element-web/issues/21762
