### ISSUE TITLE
Horizontal alignment for media and reaction containers in threads is off

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21780]
### Steps to reproduce

In a thread, react to a text reply, or upload some media (image, GIF, video, or sticker) after a text message.

#### What did you expect?

The left edge of text messages, their reactions, and media to be aligned to the same vertical line.

#### What happened instead?

The left edge of containers for reactions and media (image, GIF, video, or sticker) are not aligned to the same vertical line of text messages.

![Threads – Figma](https://user-images.githubusercontent.com/60790/163216782-9f1ca677-03f4-479f-abb2-330e2098a033.png)

### Browser information

Element version: 03ab1237ed77-react-fe4683df1043-js-9aab9178360b Olm version: 3.2.8

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@janogarcia i'm interested in this issue, can i get assigned. I'll drop a draft PR soon

**Comment by yaya-usman** [comment]
@janogarcia it seems to be aligned properly for me here.

![1](https://user-images.githubusercontent.com/38439166/163262945-8781c6c6-d071-4d4e-931e-2cc0339d5497.PNG)

**Comment by yaya-usman** [comment]
@janogarcia it seems to be aligned properly for me here.

![1](https://user-images.githubusercontent.com/38439166/163262945-8781c6c6-d071-4d4e-931e-2cc0339d5497.PNG)
