### ISSUE TITLE
"Something went wrong!" after clickling on the icon to close the new thread view

### ISSUE THREAD

**Issue by hagenest** [vector-im/element-web#21795]
### Steps to reproduce

1. Trying out the (great btw) new thread function
2. Click on the icon to close the thread view
3. "Something went wrong!" page appears instead
4. **Clearing the cache and reloading doesn't make the room accesible again**. Other rooms are still working though.

#### What did you expect?

That the thread view closes but the rest of the conversation stays accessible

#### What happened instead?

<img width="494" alt="Screenshot 2022-04-14 at 13 41 06" src="https://user-images.githubusercontent.com/53492173/163384242-c7ae2412-198d-40ef-ba97-87b68c02b176.png">

### Operating system

macOS 12.3

### Application version

Version 1.10.9

### How did you install the app?

homebrew

### Homeserver

Synapse 1.41.1

### Will you send logs?

Yes

**Comment by robintown** [comment]
See https://github.com/vector-im/element-web/issues/21762, you should be using a more recent version of Synapse, but we will be releasing a hotfix for this soon.
