### ISSUE TITLE
Sometimes the threads unread indicator shows, but I don't seem to have unread threads

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21798]
### Steps to reproduce

1. Be reading a threads
2. Notice that the thread unread indicator is showing
3. Go back to the thread list, but there is no thread with an unread marker

#### What did you expect?

Not this

#### What happened instead?

The unread marker is basically stuck and I can't clear it

<img width="527" alt="Screenshot 2022-04-14 at 14 04 32" src="https://user-images.githubusercontent.com/57377/163397127-c1a3d576-e012-4828-81ae-592703015d61.png">

### Operating system

OS X

### Application version

Element Nightly version: 2022041301 Olm version: 3.2.8

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
This is happening again in the "Delight Team" room. Restarting Element Desktop fixed the issue.

**Comment by t3chguy** [comment]
@novocaine could this be https://github.com/vector-im/element-web/issues/21927 ?

**Comment by t3chguy** [comment]
> Restarting Element Desktop fixed the issue.

Restarting if you have read up the main timeline will reset per-thread notifications until we have the MSCs & server support in place

**Comment by novocaine** [comment]
> #21927

yes, it's possible that the thread with unreads is missing from the list.
