### ISSUE TITLE
Abnormal use of CPU when idle

### ISSUE THREAD

**Issue by JasonMahdjoub** [vector-im/element-web#21793]
### Steps to reproduce

Hi,
My system is Ubuntu 21.04, Linux 5.17.3, Gnome Shell 40, Wayland, Element version 1.10.9

When I let the element-desktop window opened, element use one CPU core at around 10% of usage. If I close the Element window, but without closing it which remains available into the system icons, than the CPU slow down around 0% of usage.
I have tried it into another computer with the same configuration, but with an older version of element-desktop (probably 1.10.8), and the problem does not occur. Then, I have updated Element to version 1.10.9, and the problem restarted to appear.
I have also tried Element-desktop into Windows, and the problem is the same.

#### What did you expect?
0% of CPU usage
#### What happened instead?
10% of CPU usage

### Operating system

Ubuntu 21.04, Windows 11

### Application version

1.10.9

### How did you install the app?

https://element.io/get-started

### Homeserver

1.56

### Will you send logs?

No

**Comment by dbkr** [comment]
Debug logs may tell us what's going on, so if anyone experiencing this problem is willing to submit some that may help to diagnose this. Otherwise we'll have to wait until it happens to somehow who's able to get a javascript profile.

**Comment by goodboy** [comment]
I already reported this [in the desktop room](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$nDpZ3gmLanrkbl_6ka5DKEtqb1_Fs_wNMfn9W888BjA?via=matrix.org&via=privacytools.io&via=mozilla.org) but the issue for me appears to be the `electron17` child proc with the `--type=renderer`:

`ps h` gives the following cmd line for that child:

```
/usr/lib/electron17/electron --type=renderer --enable-crashpad --enable-crash-reporter=c199195c-d538-41e5-a910-3cec1cdc045d,no_channel --user-data-dir=/home/goodboy/.config/Riot --standard-schemes=vector --enable-sandbox --secure-schemes=vector --bypasscsp-schemes --cors-schemes --fetch-schemes=vector --service-worker-schemes --streaming-schemes --app-path=/usr/lib/element/app.asar --lang=en-US --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=77979922590 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,11337240959077112874,7156202190314880840,131072 --enable-features=WebRTCPipeWireCapturer --disable-features=HardwareMediaKeyHandling,MediaSessionService,PlzServiceWorker,SpareRendererForSitePerProcess
```

This is on an arch install fwiw and `strace`-ing the proc shows spinning between `futex`, `mprotect`, `getrandom` and `madvise` 🤷🏼 

In my case this is burning **a whole core** out of the 4 i have..

**Comment by dbkr** [comment]
Unfortunately not much in the log, and the renderer process is just the process that electron runs the app code in, so that's unsurprising. However, it looks like the little animated blue dots on the reply button might have something to do with this, and I suspect they may be animating even when the toolbar isn't visible.

**Comment by dbkr** [comment]
An illustrative gif:
![invisible blue dot animating](https://user-images.githubusercontent.com/986903/163432174-9bc615c8-1f8f-43e2-a45c-6e4f8035cf4b.gif)

**Comment by dbkr** [comment]
Oh, one more thing: if this is the case then a workaround would be to enable the threads beta which will stop the little blue dot from appearing. This probably explains why none of us are seeing this (we all turned threads on).

**Comment by hsiktas** [comment]
Confirmed! Turning on the Threads beta hides that blue dot, and the CPU usage goes down.

**Comment by catscratchedme** [comment]
I've also enabled threads beta, and my scrolling still seems laggy on Element desktop, especially when initially scrolling up in the timeline.

**Comment by turt2live** [comment]
so without too much effort, managed to reproduce this (~200 messages in the timeline)

![image](https://user-images.githubusercontent.com/1190097/163628956-18c6a1fe-6578-40c3-b47f-5751ce9b3886.png)

Top is with animation, bottom is without (not reloaded between profiles - just disabled CSS rules for animation).

The fact that the CPU graph is nearly flat in the top graph confirms the problem, at least.

**Comment by turt2live** [comment]
purple confirmed to be styles as well:

![image](https://user-images.githubusercontent.com/1190097/163629261-bf6dea1d-2937-485c-85fa-2084470428d3.png)
