### ISSUE TITLE
Started a thread and the app crashed

### ISSUE THREAD

**Issue by saharhage** [vector-im/element-web#21791]
### Steps to reproduce

1- Updated my app to the beta version
2- Started a thread in a room (of 1 other person) (to a message that the other party sent)
3- Sent 3 messages in the popup thread on the right
4- Clicked on the arrow button to close the thread popup => app crashed on this specific conversation
-> Cannot access the room

<img width="1070" alt="Screen Shot 2022-04-14 at 12 22 20 PM" src="https://user-images.githubusercontent.com/67438003/163355497-28b93841-2b2a-4079-8818-fe902e7a8277.png">

#### What did you expect?
The thread popup to be closed

#### What happened instead?
App Crash

### Operating system

macOs

### Application version

Beta version - Version 1.10.9 

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
See https://github.com/vector-im/element-web/issues/21762
