### ISSUE TITLE
"Invites" show up in breadcrumb

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21794]
### Steps to reproduce

1. Receive an invite
2. View the invite and reject it

#### What did you expect?

For the breadcrumbs to remain unchanged. Especially if I have rejected the invite that is a strong signal that I am not interested in this and would not want to see it again

#### What happened instead?

It shows up in the breadcrumb

### Will you send logs?

No

**Comment by Sinharitik589** [comment]
Can you assign it to me?

**Comment by robintown** [comment]
@Sinharitik589 Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by Sinharitik589** [comment]
@robintown kindly look into the PR , and assign the issue to me,
..
