### ISSUE TITLE
Sometimes the thread list shows out of order

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21799]
### Steps to reproduce

1. Be in the threads list of a room with a lot of threads
2. Scroll right up to the top and then down to the bottom again
3. Notice threads appear out of order

#### What did you expect?

Thread order should be consistent

#### What happened instead?

The last thread shown at the bottom of the list was from 6 days ago

### Operating system

OS X

### Application version

Element Nightly version: 2022041301 Olm version: 3.2.8

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Going to block this until we have a paginated mechanism for loading the threads list, as hunting & fixing this bug will be a lot of work which will be thrown away at that point
