### ISSUE TITLE
Thread preview and number not correctly displayed inside the thread panel on the first load

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#21807]
### Steps to reproduce

1. Create a test room
2. Send `1` as a message
3. Send until `5`
4. Reply in thread to each message fast (send different messages on each thread)
5. Open the thread list on the right panel

#### What did you expect?

- The number of message for each thread should be `1`
- The message preview for each thread should be different

#### What happened instead?

- The number of the message in each thread is not displayed as `1`
- The message previews of the threads is of the last reply for the fifth message

Please see inside the rectangle on the picture.

![before1](https://user-images.githubusercontent.com/3362943/163467321-e4a303da-091d-4a97-ab8a-fafd2b81789f.png)

If you reload the page, you should get the expected list as below:

![before](https://user-images.githubusercontent.com/3362943/163468255-ddabd648-aae8-42ed-be60-c376aa549337.png)

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by novocaine** [comment]
Can you please indicate what homeserver you are using?

**Comment by luixxiul** [comment]
I'm using a homeserver at matrix.org.

**Comment by luixxiul** [comment]
@novocaine Please let me know if you need some kind of log, tests, etc. I would be able to help to get some insight on this issue.
