### ISSUE TITLE
Sending a reaction causes "This event could not be displayed" to appear in the timeline

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#21811]
### Steps to reproduce

1. Open a room
2. Send a reaction to a message
3. See the reaction appear
4. See "This event could not be displayed" appear in the timeline

#### What did you expect?

The absence of "This event could not be displayed"

#### What happened instead?

The appearance of "This event could not be displayed"

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by yaya-usman** [comment]
@Half-Shot can you drop a snapshot of the problem... I tried reproducing, it's not giving the error you stated

**Comment by robintown** [comment]
@Half-Shot Do you have 'Show hidden events' enabled? A regression with that was fixed just an hour ago.

**Comment by Half-Shot** [comment]
> @Half-Shot Do you have 'Show hidden events' enabled? A regression with that was fixed just an hour ago.

Yes, if so I'll close.
