### ISSUE TITLE
Registration captcha is missing in Firefox private browsing

### ISSUE THREAD

**Issue by progval** [vector-im/element-web#21818]
### Steps to reproduce

The captcha when registering to matrix.org on https://app.element.io/ isn't shown when using Firefox private browsing; and there is no fallback to tell users what is wrong, so they are stuck.

#### What did you expect?

Either find a way to show a captcha that isn't blocked, or show an error message to tell users what to do

#### What happened instead?

Just a message asking to prove the user is not a bot

### Operating system

Debian 11

### Browser information

Firefox 91.8.0esr

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/2403652/163983278-66a69e4b-69dd-43db-9f2c-21ef3b58bc14.png)
![image](https://user-images.githubusercontent.com/2403652/163983320-1ae9be16-2585-45f9-8137-d2bd8c964fa9.png)
![image](https://user-images.githubusercontent.com/2403652/163983338-839c04a0-6b2a-4ec5-ae3f-ef125e22be94.png)

**Comment by progval** [comment]
FWIW, I see in the debugger Element repeatedly sends requests to https://matrix-client.matrix.org/_matrix/client/r0/register with this body:

```
{"username":"rijrjgoiejjgioj","password":"redacted","initial_device_display_name":"app.element.io (Firefox, Linux)","auth":{"session":"RmIDDLiWWWslEKkRLBKZHVku"},"inhibit_login":true}
```

And gets 401 as an answer, with this body:

```
{"session":"RmIDDLiWWWslEKkRLBKZHVku","flows":[{"stages":["m.login.recaptcha","m.login.terms","m.login.email.identity"]}],"params":{"m.login.recaptcha":{"public_key":"6LcgI54UAAAAABGdGmruw6DdOocFpYVdjYBRe4zb"},"m.login.terms":{"policies":{"privacy_policy":{"version":"1.0","en":{"name":"Terms and Conditions","url":"https://matrix-client.matrix.org/_matrix/consent?v=1.0"}}}}},"completed":[]}
```

**Comment by t3chguy** [comment]
This is polling the completion of the UIA stage

**Comment by progval** [comment]
I figured it out: you need to set `urlclassifier.trackingTable` to `test-track-simple,base-track-digest256,content-track-digest256`

I don't recall changing this value nor using an extension that may have changed it.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/164404948-2b595777-b048-455c-b41a-fc6fef920338.png)

^ is the default I see in a stock Firefox install

**Comment by t3chguy** [comment]
Closing due to this being due to custom Firefox settings
