### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by Gage20710** [vector-im/element-web#21817]
### Steps to reproduce

1. Where are you starting? What can you see? Room, Voice Chat
3. What do you click? Volume Slider
4. More steps…

#### What did you expect?
Volume to stay the same when user disconnects when adjusting volume slider
#### What happened instead?
Volume went back to 100% after user disconnects and reconnects

### Operating system

Windows

### Application version

Element version 1.10.10 Olm version 3.2.8

### How did you install the app?

https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment]
It's not entirely clear what volume slider you're referring to. Could you perhaps provide a screenshot?

If it's the volume of another participant in Jitsi, that's not something Element really has control over.

**Comment by Akanksha2403** [comment]
can u please assign this issue to me?

**Comment by robintown** [comment]
@Akanksha2403 Sorry, but we're currently awaiting more info from the reporter.

**Comment by Gage20710** [comment]
Sorry for late response, I didnt see this email until now.

The user volume slider in a conference call included in the screenshot
[image: element bug report ss.png]
[image: image.png]

But as you said this is a jitsi problem, so you guys might not be able to
do anything about it.

Thank You.

**Comment by robintown** [comment]
Right, this is a limitation of Jitsi Meet in that case, and so should be filed on their issue tracker instead.

**Comment by Gage20710** [comment]
Could you assist me in getting in contact with jitsi to report a bug?

**Comment by robintown** [comment]
Their issue tracker is here: https://github.com/jitsi/jitsi-meet/issues
