### ISSUE TITLE
Address to private room is visible to network logs due to URL

### ISSUE THREAD

**Issue by Currrupted** [vector-im/element-web#21814]
### Steps to reproduce

1. Create a private, encrypted room
2. enter the room
3. see the room address in the URL you are currently visiting

![image](https://user-images.githubusercontent.com/13292623/163624366-46530fc0-596d-49a3-bd44-c261d69abe63.png)

#### What did you expect?

The browser should not include the room URL in the address bar, as this information may be visible to the network access point, ISP or surveillance.

The address/URL of the room and the one actually accessed should **not** be the same.

#### What happened instead?

The room/group you are currently using will be specified as such in the address bar of the browser. So if I visit the room „Movie night” with the address gge8fjikölslkf:matrix.org, my ISP will see that I visit this specific room.

### Operating system

Kubuntu 21.10

### Browser information

Firefox

### Will you send logs?

No

**Comment by t3chguy** [comment]
With HTTPS only the domain is visible to intermediatry nodes in the network (like your router and ISP). Everything else is encrypted. Furthermore anything after a # in a url isn't sent to the server

See https://en.m.wikipedia.org/wiki/URI_fragment

> Clients are not supposed to send URI fragments to servers when they retrieve a document, and without help from a local application (see below) fragments do not participate in HTTP redirections.

**Comment by t3chguy** [comment]
Closing as a non issue, feel free to check the network requests in your browser devtools and network logs for yourself.

Room ids will be sent to servers ultimately via the Matrix API, given the client must ask for the room for information about that room but that's entirely unrelated to it being in the url or not.

**Comment by Currrupted** [comment]
Oh okay, got it! Thanks for the clarification, this is a relief
