### ISSUE TITLE
Reloading the registration page should warn about data loss

### ISSUE THREAD

**Issue by progval** [vector-im/element-web#21819]
### Steps to reproduce

1. Open https://app.element.io/ while not authenticated
2. Click "Create an account"
3. Fill the first form, click "Register" (the captcha page shows up)
4. Refresh the page

There are many reasons to refresh the page at that point, like an issue with the captcha (eg. users who block Javascript by default may need to reload the page after whitlisting recaptcha)

#### What did you expect?

Back to the registration form, with empty fields

#### What happened instead?

Should either be the original form with fields filled, or the captcha page

### Operating system

Debian 11

### Browser information

Firefox 91.8.0esr

### Will you send logs?

No

**Comment by t3chguy** [comment]
I think the app should warn you on refresh that it'll lose your progress, storing the state like passwords isn't great, this app never stores passwords and it shouldn't start now.

**Comment by progval** [comment]
Firefox normally takes care of repopulating fields on page reload.

But here it doesn't for some reason, probably because the form is dynamically created or someting

**Comment by t3chguy** [comment]
> probably because the form is dynamically created or something

Well yes, it is an SPA written in React, no way around that.

**Comment by yaya-usman** [comment]
@t3chguy hi, I am interested in this issue but need some clarifications before linking my PR, do I need to customize the message as "you will lose your data" in the modal displaying the warning or rather leave it for the browser agent and as far as I know if I am not wrong, it's kinda not possible to customize the message.

**Comment by t3chguy** [comment]
> it's kinda not possible to customize the message.

I believe you are right, it should be sufficient though
