### ISSUE TITLE
Webcam Indicator light is on even after stopping the camera

### ISSUE THREAD

**Issue by wizzyxx** [vector-im/element-web#21837]
### Steps to reproduce

1. Bob started a video call with Alice
2. Alice answers the call
3. Bob stops the video
4. Alice cannot see Bob
5. The indicator light of Bobs webcam is still on

#### What did you expect?

I expected the webcam indicator light will turn off after stopping the camera.

#### What happened instead?

The webcam indicator light is on after stopping the camera.

### Operating system

Windows 10 Pro

### Browser information

Chromium: 100.0.4896.127

### URL for webapp

app.element.io

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This is not an Element bug, this is a chromium bug, see https://bugs.chromium.org/p/chromium/issues/detail?id=642785 - I'll close this issue as there isn't much we can do here
