### ISSUE TITLE
SSO login doesn't work for custom profile

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#21841]
### Steps to reproduce

1. Run `flatpak run im.riot.Riot --profile pikaviestin`
2. Set homeserver URL as `https://pikaviestin.fi/`
3. Select `Continue with authentik`
4. Web browser opens.
5. Login
6. Select "Continue"
7. Another Element opens without the specified profile (it keeps loading forever, but I presume it's the default profile for another account)

#### What did you expect?

I expected Element to be logged in.

#### What happened instead?

I got a different Element instance with a different profile.

### Operating system

Fedora release 36 (Thirty Six)

### Application version

1.10.10 ?

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot (Element doesn't provide Fedora packaging and "blessed" repository is discontinued https://github.com/vector-im/element-web/issues/3781#issuecomment-1054068455)

### Homeserver

pikaviestin.fi on Synapse 1.51.0

### Will you send logs?

No

**Comment by Mikaela** [comment]
This appears to be a regression, https://github.com/vector-im/element-web/issues/12932 is the same, but previously fixed and I presume a new issue is required two years later.

I cannot send logs as they require being logged in.

**Comment by t3chguy** [comment]
Can you test this bug using the official releases? its possible it is specific to the community-maintained Flathub.

**Comment by Mikaela** [comment]
How can I install an official release on Fedora 36?

**Comment by t3chguy** [comment]
There isn't one, official releases are listed at https://element.io/get-started - but if the issue is confirmed to be specific with the flathub then the issue needs to be opened elsewhere so the right people see it.

**Comment by Mikaela** [comment]
I don't have an officially supported release available, but I opened https://github.com/flathub/im.riot.Riot/issues/268 in case they are able to reproduce or figure out which side this issue is on. Meanwhile I am asking if anyone is using an officially supported operating system and could test this.

**Comment by t3chguy** [comment]
Can confirm it works as expected on Ubuntu 20.04 with the official deb.

For the record the way this works is

1. Element (ProfileX) appends to file sso-sessions.json in the Default Profile's data directory a $key->/path/to/ProfileX
2. Element (ProfileX) opens browser with callback to element://<...>?element-desktop-ssoid=$key
3. Browser opens the callback
4. Element sees the ssoid in the URL passed to it for handling and looks up the profile to use in the JSON map.
