### ISSUE TITLE
Have window decorations for GNOME (Update Electron version to 18.0.4)

### ISSUE THREAD

**Issue by VarLad** [vector-im/element-web#21842]
#### What would you like to do?
Be able to use Element app natively on Wayland. 

#### Why would you like to do it?
XWayland still doesn't work properly on NVIDIA GPUs on Wayland. Wayland can be enforced on current version too, but its missing window decorations on the current version in the GNOME DE. That got fixed in Electron 17.x.y releases, and Wayland support is in a good shape in 18.x.y releases. 

#### How would you like to achieve it?
Update the version of Electron Element Web uses to 18.0.4

**Comment by t3chguy** [comment]
> That got fixed in Electron 17.x.y releases

We already use 17.x.y

https://github.com/vector-im/element-desktop/blob/develop/package.json#L64

**Comment by VarLad** [comment]
@t3chguy 
Currently, when I launch Element with `flatpak run im.riot.Riot --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland`

I get,
```
/home/username/.var/app/im.riot.Riot/config/Element exists: yes
/home/username/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0419/134142.918527:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0419/134142.918630:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
[50:0419/134143.017741:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is
[50:0419/134143.021422:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/app/bin/element: line 10:     3 Segmentation fault      (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

I also read an issue here https://github.com/containers/podman-desktop/issues/97

**Comment by BirdInFire** [comment]
> flatpak run im.riot.Riot --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland

you can fix this problem in gnome with WaylandWindowDecorations feature so 

flatpak run im.riot.Riot --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WaylandWindowDecorations --ozone-platform=wayland

**Comment by VarLad** [comment]
@BirdInFire Thanks! That works
But still, the window decoration is somewhat buggy

**Comment by BirdInFire** [comment]
> @BirdInFire Thanks! That works But still, the window decoration is somewhat buggy As in, maximizing window doesn't work properly now

yes i know but it's a quite "recent" fix for gnome from electron (time to fix it properly i think)

**Comment by VarLad** [comment]
I guess this is the problem https://github.com/electron/electron/issues/33161
(Just posting here for reference)

**Comment by VarLad** [comment]
I'll close this issue for now. 
I'll reopen it with the appropriate version needed when it gets resolved upstream. (probably 19.x.y then)
