### ISSUE TITLE
Do not disturb should update my status

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21844]
#### What would you like to do?

When turning "Do not disturb" on, my status should be updated to let others know i'm currently not available

#### Why would you like to do it?

This is quite a common feature with dnd functionality

#### How would you like to achieve it?

n/a

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.

**Comment by autoteelar** [comment]
i thought this feature was very cool, why the removal? (both custom status's and do not disturb)

will they come back?
