### ISSUE TITLE
Mention highlight and cursor hover highlight has different corner radius

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21845]
### Steps to reproduce

hover on a message that pings you

### Outcome

https://user-images.githubusercontent.com/2803622/164002956-6f5ccae5-f77f-47e8-b56c-0990273f9225.mp4

### Operating system

arch

### Application version

Element Nightly version: 2022041901 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.56

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
selected messages (e.g. search, link, ...) use the smaller radius as well.

**Comment by yaya-usman** [comment]
Linking my PR to this now

**Comment by yaya-usman** [comment]
@HarHarLinks which app do you use in recording your screen to be this clear, i tried to record after the fix so i can include it in the PR description but it was blurry when i converted to gif. so i couldn't show it.

**Comment by HarHarLinks** [comment]
I used the command `wf-recorder -g "$(slurp)" -f /tmp/gif.mp4`, but I think that is specific to wayland desktops

**Comment by yaya-usman** [comment]
ohh ok thanks
