### ISSUE TITLE
Registration email is sent before the user accepts EULA (consent)

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-web#21850]
### Steps to reproduce

My server requires email to register, as well as accepting the eula (consent).

After the user provides username, password and email address, the server sends him a token via email, but then asks him to accept the eula/consent.

In my opinion this is a weird behavior. The regisration email+token should only be sent to the user after he accepted the eula/consent and not before that.

### Outcome

For more reasonable and standard behavior.
Also consent document might include privacy information (e.g. "how we use your data") so the users should know that BEFORE they choose to provide their email address.

### Will you send logs?

No

**Comment by t3chguy** [comment]
The order is dictated by the server via the UIA mechanism. As per the spec, this is ordered.
