### ISSUE TITLE
Creating polls does not scale well for small windows

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#21855]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/2403652/164203803-5f91ebba-5cc8-499e-879d-8d482e0054c0.png)

#### What did you expect?
A responsive modal

#### What happened instead?
Overlapping buttons and horizontal overscroll

### Application version

1.10.10

### Will you send logs?

No

**Comment by ankur12-1610** [comment]
I'll work on it :)

**Comment by ankur12-1610** [comment]
![poll_shadow](https://user-images.githubusercontent.com/76884959/165240272-6aa572ad-5d43-40b0-8c17-43a0f8ce947f.png)

Is the shadow for the footer an intentional one?

**Comment by robintown** [comment]
It is, yes

**Comment by ankur12-1610** [comment]
> It is, yes

Thanks, I thought there was an bug in it 😅
