### ISSUE TITLE
I cannot see past encrypted messages

### ISSUE THREAD

**Issue by mrlogick** [vector-im/element-web#21868]
I did a video to explain the problem:
[[video](https://odysee.com/@mrlogick:8/matrix_org_bug:7?r=BmfALtvHo7ztiwsWGLpK7Ph2TbURuiU6)]

- User `A` logs in
- User `A` creates an encrypted room, writes something, and invites user `B`
- User `A` logs out
- User `B` logs in
- User `B` joins the room, but he cannot see past messages

I tried logging out and coming back with both users, but I cannot see past encrypted messages.

I think the problem is due to the fact that I tried everything within the same web browser. If I try with two computers (one for each user), **with both browsers online at the same time, encrypted messages do appear**.

I re-tried with my own private server (with synapse), instead of matrix.org, and even with several matrix clients, but the problem still remains.

**Comment by t3chguy** [comment]
Your issue is here

> User A creates an encrypted room, writes something, and invites user B

If `B` doesn't have devices online at this time, then you can't send them the decryption keys for the history.
This is due to Megolm featuring PFS (Perfect Forward Secrecy)

**Comment by mrlogick** [comment]
_I apologize for my poor understanding of cryptography._

In the "room settings" it is said:
`Who can read history?`
`[*] Members only (since the point in time of selecting this option)`

Also, when I'm inviting the new user Element is saying:
`Invited people will be able to read old messages.` (4:39 minutes of my video)

What's the point of Matrix if clients need to stay online? It should be enough that servers are online.

Is it possible to solve this?
If I already started a project, and new friends want to join my project, I need to let them see the whole history.

**Comment by t3chguy** [comment]
> What's the point of Matrix if clients need to stay online?

Not online, just logged in.

When you log in you create a cryptographic keypair to which you receive encryption keys

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/2286 + https://github.com/vector-im/element-web/issues/18458
