### ISSUE TITLE
Pills for users only appear after editing the message

### ISSUE THREAD

**Issue by johannes-krude** [vector-im/element-web#21867]
### Steps to reproduce

1. I send a message containing an mxid, e.g., `Maybe @abc:example.com can help you.`
2. The message appears in the timeline, but the mxid is not replaced by a pill.
3. I edit the message, but leave the mxid unchanged. E.g., `Maybe 
@abc:example.com can help you!`
4. The timeline now shows a pill instead of the mxid
5. I switch to another room and then back to the room, the pill disapears again.
6. Any further edits to the message do not result in again showing the pill.

#### What did you expect?

The mxid is always replaced by i pill.

#### What happened instead?

The mxid is only replaced by a pill after editing the message and disapears again upon switching rooms or doing further edits to the message.

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

deb https://packages.riot.im/debian/ default main

### Homeserver

Synapse 1.57.0

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
reopened by https://github.com/matrix-org/matrix-react-sdk/pull/10370
