### ISSUE TITLE
OAuth login should be linked to the original account, if there is an existing account

### ISSUE THREAD

**Issue by bluedasher13** [vector-im/element-web#21863]
#### What would you like to do?
I have registered an account with Email (name@domain.com) and a password
However, when I tried to log in with a Google account that has the same Email, I was requested to **Create a New Account** instead of linking this OAuth to the original account.

#### Why would you like to do it?
It looks like a weird strategy.
I don't need to create a new account, I just need multiple ways that could all log in to the same account.

#### How would you like to achieve it?
Most websites take one of two methods below:
1. We could choose to link or unlink 3-rd accounts (Google / Apple ID / GitHub...) in my control panel anytime.
2. While we log in with a trustable OAuth platform that has an Email address (such as Google), the system should log in to the existing account associated with this email. (looks like link it automatically)

**Comment by t3chguy** [comment]
This is all done by the server, so I suggest opening an issue in Synapse

https://github.com/matrix-org/synapse/
