### ISSUE TITLE
Now RightPanel notifs and files have landed, the design may need some tweaking

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2187]
Specifically, it feels that FilePanel is quite hard to interpret, and the left margin in NotifPanel caused by the avatars may be too wide.  We also need more space for long timestamps, and need to decide whether to duplicate room headings or not

**Comment by kittykat** [comment]
That review has come to pass, Nad and Jano are satisfied that this is resolved. For current design issues, see #18492
