### ISSUE TITLE
Margin between deleted messages in Bubble Layout

### ISSUE THREAD

**Issue by TheReshma** [vector-im/element-web#21878]
### Steps to reproduce

1. Go to app.element.io
2. Be sure that the chats are in Bubble Layout
3. in a 1-1 room, delete a few messages
4. This happens 
Message bubbles are perfectly sandwiched on one another which should be avoided.
![image](https://user-images.githubusercontent.com/70228821/164695779-d924f470-2c2a-486a-b1a9-3cb550d66c53.png)

#### What did you expect?
Sufficient space between message bubbles 

#### What happened instead?
![image](https://user-images.githubusercontent.com/70228821/164695779-d924f470-2c2a-486a-b1a9-3cb550d66c53.png)

### Operating system

Windows 10

### Browser information

Edge

### URL for webapp

app.element.io

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### Homeserver

Matrix

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed on develop
