### ISSUE TITLE
Room crashes and can't be view after selecting "thread" view

### ISSUE THREAD

**Issue by johnjaylward** [vector-im/element-web#21871]
### Steps to reproduce

1. upgraded server to 1.55.2
2. Element Desktop -> join thread beta
3. In a room, select the "Thread" option to show threads

#### What did you expect?

Thread view for the room would show

#### What happened instead?

room crashed hard and can not recover view:
![image](https://user-images.githubusercontent.com/383703/164511351-a0a9bab0-d9a9-4bb4-b290-e75b04f30ddf.png)

### Operating system

Server - freebsd, Desktop - Linux

### Application version

Element version: 1.10.9 Olm version: 3.2.8

### How did you install the app?

gentoo system package. `emerge net-im/element-desktop-bin`

### Homeserver

Synapse 1.55.2

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please upgrade to 1.10.10 where the issue is fixed.

**Comment by johnjaylward** [comment]
thanks. confirmed the upgrade worked.
