### ISSUE TITLE
Read receipts on state events in bubble layout are misaligned

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21899]
### Steps to reproduce

1. Enable bubble layout
2. View a room with a state event directly after a normal message, where both have a read receipt on them

#### What did you expect?

The read receipts should be horizontally aligned

#### What happened instead?

The read receipts on the state event are slightly further left than those on the message:

![Screenshot 2022-04-23 at 12-51-41 Element 1 Element Web_Desktop](https://user-images.githubusercontent.com/48614497/164916155-2627f3e8-d0cb-4540-86ed-f6750b3722c9.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0

### URL for webapp

develop.element.io

### Application version

Element version: 691b8d5c38ee-react-0c7a4dfcacea-js-1bb82108b742 Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
(Does not block 1.10.11 but rather the release after)
