### ISSUE TITLE
Clicking on the read receipt of a user who was never in the room causes a soft crash

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21896]
### Steps to reproduce

1. Use an appservice such as mx-puppet-discord that sends a separate read receipt for the bridge bot in DMs, even though the bridge bot is not part of the DM
2. Click on said read receipt

#### What did you expect?

To open the read receipt info menu

#### What happened instead?

A soft crash ("Can't load this message (m.room.message)") with the following error in the console:

```
TypeError: roomMember is null
    ReadReceiptPerson ReadReceiptGroup.tsx:190
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
rageshake.ts:72:27
```

### Operating system

NixOS unstable

### Browser information

Firefox 99.0

### URL for webapp

develop.element.io

### Application version

Element version: 691b8d5c38ee-react-0c7a4dfcacea-js-1bb82108b742 Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

Yes

**Comment by justjanne** [comment]
`IReadReceiptProps` is defined as

```typescript
export interface IReadReceiptProps {
    userId: string;
    roomMember: RoomMember;
    ts: number;
}
```

The `roomMember` property is set in [MessagePanel.tsx:854](https://github.com/matrix-org/matrix-react-sdk/blob/a3a7c60dd7731bb4a253c918984ca7fa0a9ddb7a/src/components/structures/MessagePanel.tsx#L851) from a call to `room.getMember`, which can return null.

It looks like the type should instead have roomMember be nullable.
