### ISSUE TITLE
Style of read receipt info menu is inconsistent with the 'recently viewed' menu

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21898]
### Steps to reproduce

1. Look at a read receipt info menu
2. Look at the 'recently viewed' menu

#### What did you expect?

A consistent visual language between similar UI elements

#### What happened instead?

![rv](https://user-images.githubusercontent.com/48614497/164915502-df7e02aa-fd26-4afa-8bb5-291870e7dda7.png) ![rr](https://user-images.githubusercontent.com/48614497/164915585-f614d5b7-4a2d-4143-98ea-f708d318d3b2.png)

These two menus are structurally identical, yet look different in a number of ways:
- The hover/focus color is different
- The scrollbar is in a different place
- The header is a different size
- The font size of list items is different
- The border and shadow is different

### Operating system

NixOS unstable

### Browser information

Firefox 99.0

### URL for webapp

develop.element.io

### Application version

Element version: 691b8d5c38ee-react-0c7a4dfcacea-js-1bb82108b742 Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by luixxiul** [comment]
Here's a rough implementation of the read receipt menu based on the style rules of the recently viewed menu:

https://user-images.githubusercontent.com/3362943/164946244-7fac2019-08e1-4ec3-899d-585f279245a2.mp4

The font size can also be identical like below, but it might look too large (especially the header).

https://user-images.githubusercontent.com/3362943/164946250-81f2779b-70c4-4b83-b594-4b184ea30e22.mp4

The guidance on the size and spacing would be appreciated.

**Comment by niquewoodhouse** [comment]
> These two menus are structurally identical, yet look different in a number of ways:

First off, I really really like the underlying goal of this issue - striving for a visually consistent product.  

However, the recently viewed menu is a labs feature (I think) - it's not a given it will ever become a part of the actual default experience - so I'd be reluctant to use its styling as precise direction for things that everyone will see by default.    Let me know if I'm incorrectly assuming what a labs feature is.  Also, while the UI is inconsistent between places across the product, I think it's best for users to make something consistent with what's near/around it.


> * The border and shadow is different
> * The hover/focus color is different

The styling for the read receipts comes from other floating click to open elements on the timeline.  Like the more options list: 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/1587166/165111696-0b837dd8-001a-4837-a7a8-771ac224d159.png">

> The header is a different size
> The font size of list items is different

I do agree this is something that could be improved a bit in general but to be more like the sizes around it, not necessarily the same as the larger header in recently viewed.

**Comment by robintown** [comment]
The breadcrumbs experiment is slated for removal, so this doesn't matter anymore
