### ISSUE TITLE
If the server emits 500s, you can end up spuriously telling the user that their room needs to be upgraded

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21891]
### Steps to reproduce

1. Get a 5xx from the server
2. View a room around the same time
3. Get a super ugly spurious room upgrade warning (https://github.com/vector-im/element-web/issues/15298)

<img width="1322" alt="Screenshot 2020-09-27 at 21 47 54" src="https://user-images.githubusercontent.com/1294269/94375427-738fbd00-010b-11eb-9fc7-c7bae9984706.png">

#### What did you expect?

Errors should be retried, and shouldn't be misreported to the user.

#### What happened instead?

Error misinterpreted as the room needing an upgrade.

### Operating system

macos

### Application version

nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/vector-im/element-web/issues/20166 https://github.com/vector-im/element-web/issues/16068

**Comment by ara4n** [comment]
closing as dup of #20166 - thanks
