### ISSUE TITLE
New RR layout unnecessarily wastes horizontal screen estate

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21890]
### Steps to reproduce

1. Observe the new RR layout when you have a lot of RRs on a message - looks cute!
2. But then realise there's a huge right-hand margin on the message bodies which is presumably left over from the old layout, wasting horizontal screen real estate.

<img width="564" alt="Screenshot 2022-04-22 at 21 03 54" src="https://user-images.githubusercontent.com/1294269/164786259-b4eda8be-dd13-4ada-8295-9163302f0ac3.png">

#### What did you expect?

New RR layout to give more horizontal real estate

#### What happened instead?

It doesn't.

### Application version

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by justjanne** [comment]
> some need to align them with sent/sending iconography

From a technical perspective: sent/sending icons use the same CSS classes as read receipts, so they are aligned and positioned identically.

**Comment by t3chguy** [comment]
The timeline reserves a right margin to avoid overlapping with the read receipts, since read receipts are much narrower now, the reserved column can be shrunk down to fit

**Comment by kittykat** [comment]
@niquewoodhouse did you get a follow up from the rest of the design team on this issue? Maybe we could shrink that column down for now to resolve this issue?

**Comment by niquewoodhouse** [comment]
@kittykat No one had much detail on this area, I have tried to look at this in my but I'm not sure I have a clear design proposal and I'm not sure if the waste of screen estate is overall a negative

- The margin helps align things on the right so the ui isn't as messy
- The margin does separate the receipts from the messages which I understand might be deemed a problem for some but it also gives the message more focus, and makes the receipts clearly a less important element, which feels true.

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/1587166/169313140-df46bb8b-483f-472f-be91-bfb0e273e3db.png">

I think to move this forwards, I might need to pair with an engineer to make a netlify to test with all the various things (bubbles, IRC, different screen sizes).

**Comment by gsouquet** [comment]
I don't think the idea is to change the right gutter at all, but more to do with the space between the event tile and the read receipts. I've opened a PR that I believe brings the spacing between the read receipt UI and event tile to what it was before the redesign. 

Used a 8px spacing between the two elements
