### ISSUE TITLE
Improper button padding in Developer Tools dialog box.

### ISSUE THREAD

**Issue by ankur12-1610** [vector-im/element-web#21908]
### Steps to reproduce

Open the `Developer Tools` dialog box via Room Options.

#### What did you expect?
Proper UI.
#### What happened instead?
![button-padding-dev-tools](https://user-images.githubusercontent.com/76884959/165044892-82fffbe0-c88f-4c29-8ada-4ce0cca1564a.png)

### Operating system

Ubuntu 21.10

### Browser information

Chromium Version 100.0.4896.75

### URL for webapp

develop.element.io

### Application version

Olm version: 3.2.8

### Will you send logs?

No

**Comment by ankur12-1610** [comment]
I'll work on this.

**Comment by t3chguy** [comment]
If you're referring to the footer, that is already fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8400

**Comment by t3chguy** [comment]
Yes, that PR fixes that.
