### ISSUE TITLE
Support disabling spellchecking

### ISSUE THREAD

**Issue by nidico** [vector-im/element-web#21901]
### Steps to reproduce

1. I am trying to disable the spell checker for whatever reason. (e.g. I hate chell speckers and don't need them!!)
2. I am entering the settings and hope to find a setting for that purpose.

#### What did you expect?

I expected to easily find out how I can disable the spell checker.

#### What happened instead?

Unfortunately there's no search within the settings (see #9592), so I'm spending 2 minutes clicking through the different categories, don't find it and spend an hour to [write comments in the issue about the missing search](https://github.com/vector-im/element-web/issues/9592#issuecomment-1107761251).

Then, I look for a bug report about the missing "disable spell checker" option, find out that *it does exist*, spend even more time to write [another bug comment](https://github.com/vector-im/element-web/issues/13543#issuecomment-1107797939) because I think being able to disable it entirely would be better for various reasons and finally end up here, writing yet another bug report.

#### What to do about it?

This bug report is about documenting the way the current implementation works to the end user, as long as a proper kill switch doesn't exist.

I would suggest the following simple fix: Add a hint on top of the dictionary chooser which states "In order to disable the spell checker entirely, you have to remove all languages from the list below."

### Application version

Element 1.10.0

### How did you install the app?

Debian package from riot.im repo

### Will you send logs?

No

**Comment by t3chguy** [comment]
The workaround you listed only works on Windows & Linux, macOS languages cannot be set due to it being controlled in System Settings
