### ISSUE TITLE
Bring back the waveform on voice messages.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#21904]
#### What would you like to do?

https://github.com/matrix-org/matrix-react-sdk/pull/8079 removed the ability to view waveforms in the timeline for voice messages, in favour of being able to scrub them.  As a result, they look naked and crap and i thought my demo had broken when I was trying to show them off the other day.

#### Why would you like to do it?

Given we have waveforms on VMs, it's nuts not to show them.

#### How would you like to achieve it?

Extend the scrubbable view of VMs to also display the waveform in the bg (perhaps semi-greyed out, to help with a11y)

**Comment by jellykells** [comment]
maybe an improved design could take inspiration from SoundCloud where the waveform shows the progress of a track, and also allows scrubbing by clicking inside the waveform. idk if it would be considered less accessible to do it this way
