### ISSUE TITLE
Element using 35% CPU idling

### ISSUE THREAD

**Issue by NeilW** [vector-im/element-web#21909]
### Steps to reproduce

Running element on an Ubuntu Linux VM logging into matrix.org

Use show/hide on tray icon to toggle the main display on and off.

#### What did you expect?

CPU usage to be minimal on idle

#### What happened instead?

35% CPU load (1 core) when display is not hidden, but not being used. CPU load disappears when display is hidden. 

### Operating system

Ubuntu Linux 20.04

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

Automatic update from Element Apt repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This has been fixed since and will be released in 1.10.11
