### ISSUE TITLE
Display strikethrough formatting from other clients

### ISSUE THREAD

**Issue by MRAAGH** [vector-im/element-web#21905]
### Steps to reproduce

1. Send this message using the client Mirage or Moment: `~~message~~`   (event formatted body is `<p><s>message</s></p>`)
2. Look at the message in Element

#### What did you expect?
I expected Element to display:
~~message~~

#### What happened instead?
Element displays:
message

### Operating system

Arch LInux

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

pacman -S element-desktop

### Homeserver

Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment]
The spec suggests use of the `<del>` tag instead of `<s>`

https://spec.matrix.org/v1.2/client-server-api/#mroommessage-msgtypes

> Clients should limit the HTML they render to avoid Cross-Site Scripting, HTML injection, and similar attacks. The strongly suggested set of HTML tags to permit, denying the use and rendering of anything else, is: font, del, h1, h2, h3, h4, h5, h6, blockquote, p, a, ul, ol, sup, sub, li, b, i, u, strong, em, strike, code, hr, br, div, table, thead, tbody, tr, th, td, caption, pre, span, img, details, summary.

**Comment by MRAAGH** [comment]
Reported for Moment: https://gitlab.com/mx-moment/moment/-/issues/133
