### ISSUE TITLE
Slash commands mess up editing replies

### ISSUE THREAD

**Issue by twouters** [vector-im/element-web#21928]
### Steps to reproduce

1. send a message to a room
2. trigger a reply to the message
3. type /shrug command in message composer
4. send message
5. edit the reply

#### What did you expect?

I expected that slash commands behave like regular replies, so the original message should be visible in the editing dialog, but not editable.

#### What happened instead?

The original message is included as a literal quoted message when editing the reply

### Operating system

Arch Linux

### Browser information

any browser version / element desktop app

### URL for webapp

development.element.io

### Application version

1.10.10, 2ffb3a11808c-react-ba624c8ef281-js-3649cf46d343

### Homeserver

synapse 1.51.0

### Will you send logs?

No

**Comment by twouters** [comment]
sidenote: I just tested this in the threads view and the new implementation seems to behave correctly. Only messes up stuff when rightclicking a message in the room view and clicking reply.

**Comment by t3chguy** [comment]
This is due to the edit parser choking on non-html replies
