### ISSUE TITLE
Unread indicators not showing anymore in thread list

### ISSUE THREAD

**Issue by janogarcia** [vector-im/element-web#21927]
### Steps to reproduce

1. Get a reply or a mention on a thread you're participating in.
2. Open the thread list.

#### What did you expect?

The unread indicator showing in the thread list, beside the timestamp of the updated thread.

#### What happened instead?

The thread summary gets updated with the latest reply but there's no unread indicator beside the timestamp.

### Operating system

macOS

### Browser information

Chrome 100.0.4896.127

### URL for webapp

develop.element.io

### Application version

Element version: 2ffb3a11808c-react-f85e178fc18b-js-ac08e5241079 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Blocked on https://github.com/vector-im/element-meta/issues/196

**Comment by t3chguy** [comment]
Actually, we can fix the semi-working implementation we already had, and improve when we have the proper MSC support
