### ISSUE TITLE
High CPU usage when the app window not minimized

### ISSUE THREAD

**Issue by robertvanya** [vector-im/element-web#21924]
### Steps to reproduce

Open the windows: the CPU load is around 10%.
Minimize the window to the taskba, the CPU usage will drop. The same effect when opened in the browser, from the web. The same on Windows and Linux, Edge and Firefox.

### Outcome

Overheats my tablet (passive cooling) and discharges the battery fast.
Runs the CPU fans at high noise on a desktop.

### Operating system

Windows, Ubuntu

### Application version

1.10.10

### How did you install the app?

from element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Will be fixed in 1.10.11 - for now if you enable the Threads beta it will go away
