### ISSUE TITLE
Use monospace font for room, message IDs in View Source modal

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21937]
#### What would you like to do?
To maximize readability, room and message IDs in the view event source dialogue should use the monospace font.

It could look like this, though my vertical alignment is off:

![image](https://user-images.githubusercontent.com/2803622/165354628-ebb638a5-befc-4b67-9ac1-9d1b19f504aa.png)

#### How would you like to achieve it?
Here is the part in the code:
https://github.com/matrix-org/matrix-react-sdk/blob/e718242912e2d063a66abc05c2fcab53db18569c/src/components/structures/ViewSource.tsx#L170-L179

1. put labels and IDs in their own element classes
2. apply monospace font to IDs
3. ensure the labels have the same width for alignment (they do coincidentally with that font, but probably still should)

### Additional context

Would it make sense to do this for MXIDs as well? With the Inter font, capital i and lower case L are indistinguishable. This could combat impersonation attempts.

**Comment by ritikBhandari** [comment]
Hi, 
Can I take up this issue? I'd like to work on it.

**Comment by HarHarLinks** [comment]
Thank you @paragpoddar for working on this :)

Personally, I wish the labels were still aligned (as mentioned in OP). @t3chguy is that something you'd consider?

![image](https://user-images.githubusercontent.com/2803622/215549264-231faf96-9b05-4d0b-9b6d-b13693b8fe29.png)
