### ISSUE TITLE
Timeline jumps when switching rooms to timelines with potential URL previews

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21933]
### Steps to reproduce

1. Disable URL previews server-side, but not in the client
2. Visit a room with lots of links (in my case, EMS Ops)
3. Note the timeline jump

#### What did you expect?

For the timeline not to jump immediately upon opening the room.

#### What happened instead?

The timeline jumped. It appears to be a gap roughly the height of the typing notification container, and goes away after the URL previews error out.

This appears to be a regression: we didn't previously reserve the space while the preview was loading, instead opting to pop-in the previews.

### Operating system

Windows 10

### Application version

0.0.1-nightly.2022042601

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a symptom of https://github.com/vector-im/element-web/issues/21930
