### ISSUE TITLE
New read receipts: Show the +1th receipt, hide the +2th

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21935]
#### What would you like to do?

Showing that "one more person" read my message is a bit annoying when I can't see their avatar - I have to guess who it might be, or click to interact. This is particularly annoying now that the number of visible read receipts is fewer.

When 2 or more receipts would be hidden though, use the +N button to show that. For +1 though, just show the fourth avatar.

#### Why would you like to do it?

See above.

#### How would you like to achieve it?

See above.

**Comment by HarHarLinks** [comment]
"+1th", "+:tooth: "

:stuck_out_tongue_winking_eye:
