### ISSUE TITLE
Delight: The Home screen AKA The Onboarding Checklist

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21947]
## The problem

- Users land in Element and don’t know where to begin
- We believe that users who add content quickly (and stop millhousin) are more likely to be successful in Element
- There’s a lot of paths that users might take in order to invest in Element, add and consume content in the app
- This also might be a great place to start educating users on the USP of Element, showing our value and feature set to their best use (at each stage of their user journey)
- The items listed below may change, or change priority, based on the user’s [use case selection](https://github.com/vector-im/element-web/issues/21949)

**The solution should**

- Encourage users to commit to Element as their Matrix solution
- Increase D1 retention (get them coming back tomorrow)
- Help users stop "millhousin"
- Be welcoming and contain personality (this is their first screen!)
- Be easy to find; When the user first logs in it should be the first thing they see and they should be able to get back to it (especially while they’re still in their first session) 
- Educate; There’s a lot to learn - Howe can we educate users subtly so that the product makes more sense faster

**Today we include**

- Start a DM
- Create Room
- Join Room
- Personalise profile

Depending on the chosen design and method, we could decide if we need all of these options or if a combination of these and others makes more sense. 

**Other options to consider including**

- Set up Notifications
- Set up Secure backups
- Invite friends or Share on Socials that you joined Element (so people message you)
- Set up discoverability and identity server so others can search for you
- Join a space
- Download the app 
- _Anything else?_

**Analytics on the current screen (May 5, 2022)**
https://posthog.hss.element.io/dashboard/479

### Hypothesis 
We believe that by having one hero action where the user gets a reward and immediate feedback, followed by a series of investment tasks we kick start the first "retention loop" and therefore increase D1. This also will allow us to give users a tailored experience of element, based on what we know about them. 

As this is a hypothesis, we've taken the ideal state and broken it into chunks that can be delivered over time: 
<img width="1425" alt="Screenshot 2022-06-09 at 15 08 41" src="https://user-images.githubusercontent.com/89144281/172857207-3ec075be-87ea-4a9d-a0c2-9fbef422c05d.png">

### Delivery 1: https://github.com/vector-im/element-web/issues/22463 
Focus on:
* Asking the use case question
* Getting baseline metrics for the one hero action
* Understand if the checklist "works"
* Provide a way back to the 'Welcome Home' screen

**Comment by daniellekirkwood** [comment]
Join a space

**Comment by daniellekirkwood** [comment]
Continued access?

**Comment by t3chguy** [comment]
> Join a space

Depends on https://github.com/vector-im/element-web/issues/17264

**Comment by daniellekirkwood** [comment]
Discoverability and identity servers

**Comment by daniellekirkwood** [comment]
App downloads

**Comment by t3chguy** [comment]
Do you mean the Home page? The welcome screen is

![image](https://user-images.githubusercontent.com/2403652/166841956-c00ab2b8-9340-467c-b0ae-922fb6a1bf31.png)

**Comment by daniellekirkwood** [comment]
We may also want to consider this: https://github.com/vector-im/element-web/issues/21949

**Comment by niquewoodhouse** [comment]
@gsouquet just exploring some ideas, was wondering if you could comment please on this idea - I'm interested in feasibility/effort to do something like this.  

https://user-images.githubusercontent.com/1587166/168568760-5ce9d94f-c9f2-4745-9f30-ca7a1a308ab2.mov

So put a big search looking thing on the page that opens up the beta search.  Is that simple to do, or would that be complicated?  Once it's out of beta, does this become a simpler idea to do?

Thanks

**Comment by ShadowJonathan** [comment]
Impression: I don't know what "CTA" means, from a glance at that screen, so it might be worth discovering if that term is friendly and understandable or not.

**Comment by t3chguy** [comment]
CTA=Call To Action

**Comment by gsouquet** [comment]
@ShadowJonathan this are early drafts/research. This is purely placeholder content

**Comment by gsouquet** [comment]
@niquewoodhouse 

This is definitely achievable. A prerequisite for this flow to work would be to have the new search experience out of beta (which is what we're currently working on).
The new screen 

When discussing with @justjanne she mentioned the welcome screen could also be turned into a check-list. The "next steps" could be turned into a list that would incentivise users to do some actions that will make them more likely to continue using Element (and overall Matrix) as a messaging platform

**Comment by justjanne** [comment]
> The "next steps" could be turned into a list that would incentivise users to do some actions that will make them more likely to continue using Element (and overall Matrix) as a messaging platform

It’d also be a nice place to show the analytics opt-in as one of these steps, as a way to get users to engage with it intentionally (see https://github.com/vector-im/element-meta/issues/238)

**Comment by niquewoodhouse** [comment]
> When discussing with @justjanne she mentioned the welcome screen could also be turned into a check-list. The "next steps" could be turned into a list that would incentivise users to do some actions that will make them more likely to continue using Element (and overall Matrix) as a messaging platform

One of the other ideas we've been looking at is a checklist kind of like that:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1587166/168583861-d9a41ffc-94e4-463a-ac90-81e7f51b7ae7.png">

**Comment by daniellekirkwood** [comment]
We've committed all we intend to for now on this issue so I'll close it.
