### ISSUE TITLE
Different info in Settings vs Message search modal

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#21942]
### Steps to reproduce

1. Open Security and Privacy settings
2. Note the summary of Message search status (N rooms)
3. Click Manage
4. Note the detailed Message search status (X out of Y rooms)

#### What did you expect?
Summary and detailed don't diverge.

#### What happened instead?

![image](https://user-images.githubusercontent.com/2803622/165408824-df908562-81a7-4e8b-8acc-84500cadbca9.png)
![image](https://user-images.githubusercontent.com/2803622/165408833-702b82c3-a6d2-4a4d-a7bd-5a98934fc274.png)

The shown N != X. If that is intended then it should be explained somehow.

### Operating system

arch

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### How did you install the app?

element-desktop from arch repos

### Homeserver

1.57.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17299

**Comment by HarHarLinks** [comment]
Issue https://github.com/vector-im/element-web/issues/17299 is about multiple clients/sessions
My issue is about different info within a single client/session's settings

Your call if it's still a dupe

**Comment by t3chguy** [comment]
Sorry my bad, Duplicate of https://github.com/vector-im/element-web/issues/16246
