### ISSUE TITLE
Messages do not sent  or receive , if sent it took 30 minutes

### ISSUE THREAD

**Issue by RajrupDasid** [vector-im/element-web#21943]
### Steps to reproduce

1. Too slow for Firefox browser
2. when enable encryption in rooms and even in general messages
3. Too much slow application and I am seriously been pissed with it's performance 
4. I don't know it's for Firefox only or not but no messages are sent or receiving , which is rather unfortunate
5. even if messages sent or receive it's too slow like taking 30 + minutes to sent 
6. I am on a 100 mbps optic fiber connection and other platforms are working fine not this 

### Operating system

Linux 

### Browser information

Firefox normal edition - version 99.0.1

### URL for webapp

https://app.elements.io

### Application version

Element version 1.10.11 olm version 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andybalaam** [comment]
@RajrupDasid I use Firefox on Linux and don't see this kind of poor performance, so there must be some kind of bug being triggered on your setup.

If you were willing to send logs by typing /rageshake and linking the logs report to this issue it would help us to debug the problem.

**Comment by RajrupDasid** [comment]
[issue.txt](https://github.com/vector-im/element-web/files/8588172/issue.txt)
[log-0.log](https://github.com/vector-im/element-web/files/8588174/log-0.log)

The information it maybe helpful for you to understand things

**Comment by t3chguy** [comment]
Can you try Settings > Help & About > Clear cache and reload
From the logs it looks like lots of data is missing from the IndexedDB in your browser, this should rebuild that data

**Comment by RajrupDasid** [comment]
@andybalaam @t3chguy  one thing i want to tell you the problems i've mentioned here I am facing it only in Firefox not in Microsoft Edge

**Comment by t3chguy** [comment]
The browser cache stores images and other such resources, the application cache stores your sync state which includes rooms the app knows about. Clearing browser cache basically does nothing here

**Comment by RajrupDasid** [comment]
I cleared application cache but nothing worked  @t3chguy 
also slow down issue I am facing in Microsoft edge also
Messages aren't sending even after clearing cache
why? 
and when you're going to fix those issues?

**Comment by RajrupDasid** [comment]
@andybalaam @t3chguy please a least do something for messages are not sending 
and please make it little bit fast

**Comment by t3chguy** [comment]
Fixing your issue requires reproducing it, and unfortunately you are the only reporter thus far. Also you should note that Edge is not a supported browser https://github.com/vector-im/element-web#supported-environments

**Comment by RajrupDasid** [comment]
@t3chguy I've a lotta fingerprint defender , ad blocker and Decentraleyes installed  on both of my browsers 
so can this be a reason?
but how it's can be because it's opensource system , it does not show ads , it does not has any local injection
or fingerprinting or any such then what went wrong then?

**Comment by t3chguy** [comment]
Some privacy or adblock extensions have heuristics which trip false positive when using multiple apps which access the same service (e.g matrix.org) because they assume it is a tracker or ad server. Not understanding that it might be a service provider for multiple clients.

Try reproduce the issue in a fresh browser profile with 0 extensions.

**Comment by RajrupDasid** [comment]
is this the case for u block origin too?
I am using that adblocker
okay but on edge it's not affecting but sometime  it's slowing down
firefox might have some cryptography issue
well I am trying

**Comment by t3chguy** [comment]
Yes ublock origin has caused issues in the past, search it in this repo's issue tracker

**Comment by RajrupDasid** [comment]
> Yes ublock origin has caused issues in the past, search it in this repo's issue tracker

On a bare browser chromium it's still the same as it's on other browser with Adblocker @t3chguy 
well I am using vodafone's network to accessing the platform 
can this be a problem?
what do you say?do I charge them? what do I even say them?
