### ISSUE TITLE
We've lost the ability to quickly hover over a read receipt to see who it was

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21940]
### Steps to reproduce

1. Send a message
2. Have 2 people read it
3. Wonder "who is that avatar?" and hover over it
4. Get told 2 people saw the message
5. Be disappointed that the tooltip doesn't reveal a user ID/name.

#### What did you expect?

To be able to quickly find out who a specific avatar is for cases when an unrecognized (or not familiar) avatar is shown as having read the message. Most common in the first 2-3 read receipts.

#### What happened instead?

I'm now told that N people saw my message. I'd rather know who it was than how many.

### Operating system

Windows 10

### Application version

0.0.1-nightly.2022042601

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
@niquewoodhouse & @justjanne 👀

**Comment by justjanne** [comment]
Currently, our design specs the tooltip to show exactly that – “Seen by n people”. Previously, the avatars had their own, individual tooltips. I expect that we don’t want to show two tooltips again (#21897), so we’ll need some design on whether we want to replace that "Seen by n people" tooltip, add a second tooltip, or reject this issue.

**Comment by niquewoodhouse** [comment]
To improve the experience for this specific case we could use the tooltip to include names.  There's precedence for this in the product, for example tooltip on Space members facepile:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1587166/165745281-6e3a6126-3ce8-4bbc-9abb-559135f9d8bf.png">

So the tooltip goes from saying `Seen by 2 people` to `Seen by 2 people Name and Name` with the same styling as the above example.  @justjanne I'm not 100% sure of the logic for the way that space members tooltip shows names but hopefully its a good fit for our needs.  

My only concerns are taking up a lot of screen with a giant tooltip when being able to read the timeline is so important to the product experience.  So maybe  when our read receipts gets to the count where it needs to say `+1` next to the facepile, its a good point to stop showing names and say Seen by 9 people. `John, John, John and more.`. Would probably need to try this out in practice to get confident about the right cut off.

<img width="166" alt="image" src="https://user-images.githubusercontent.com/1587166/165747288-a30ef45b-ee82-4546-a25d-42e7737bf565.png">

**Comment by justjanne** [comment]
How should we handle cases where the names are not as short as e.g., “John” but more like “Janne Mareike Koschinski (UTC+2) [away]”, and we’ve got four of them?

**Comment by niquewoodhouse** [comment]
> How should we handle cases where the names are not as short as e.g., “John” but more like “Janne Mareike Koschinski (UTC+2) [away]”, and we’ve got four of them?

Good question, what options do you feel we have easily available?  We obviously don't want a super long tooltip or the most over engineered tooltip in the world so I'd like to get your input on what's easiest to do.

**Example ideas:**
- We could ellipsis names so the example would be "Janne M..., John and more"
- We could have linebreaks in the tooltip after XX characters, but that might lead to snapping people's names in half, which would suck
- We could have line breaks after each name

**Comment by justjanne** [comment]
One option would be removing everything at the end of a user’s name that is framed in (), [], {} or <> and instead adding “…”.
All the other ideas you mentioned are also obviously possible, but I don’t know how we usually do this.

**Comment by jellykells** [comment]
The new design discussed here doesn't seem to actually solve the issue, which is that you can no longer tell which member a read receipt avatar belongs to by hovering over it.
A truncated list of display names that appears regardless of which read receipt you hover over isn't very helpful in that case.

**Comment by t3chguy** [comment]
Well given only 3/4 avatars are shown, those same names could be there in that same order and then it would solve the issue, no? @jellykells

**Comment by niquewoodhouse** [comment]
@justjanne I'm not sure if we have any precedent for doing this.  

I think with this kind of thing it needs to be tried in practice to have confidence in the solution.  I'm not sure we should start with truncating names, lets just try showing the display names as they are and see how it works.  

Seen by 2 people
Name, Name

Seen by 3 people
Name, Name, Name

Seen by 4 people
Name, Name, Name, Name

Seen by 14 people
Name, Name and more
