### ISSUE TITLE
Add new user's new username to the Registration flow 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21944]
### Your use case

Can we add a screen/copy somewhere in the flow that confirms the user's username so that they are able to log in once the account is created successfully? 

[Figma link](https://www.figma.com/file/ZDVvKC8odsa5Jeml9gCuLd/Web%3A-New-User's-Journey?node-id=52%3A16)

| From |
|--|
|<img width="676" alt="Screenshot 2022-04-26 at 21 41 00" src="https://user-images.githubusercontent.com/89144281/165442064-da86617a-b70a-4ef7-a38b-05a04f3bf14b.png">|
| To | 
|![image](https://user-images.githubusercontent.com/89144281/167027704-14ce5aac-3bec-43a6-a6a4-af3f8b1331d3.png)|

**Comment by t3chguy** [comment]
@daniellekirkwood I think this would be better served by https://github.com/vector-im/element-web/issues/19305

**Comment by kittykat** [comment]
We could do both: keep a reminder going of the user's username and log in automatically when they click the link in the email

**Comment by daniellekirkwood** [comment]
Great point, @kittykat 

Let me change this issue to address the problem, rather than provide a solution and that should help.

**Comment by daniellekirkwood** [comment]
Hey 
@niquewoodhouse It might be good to include the user's MXID somewhere in the flow here so that they've seen it. On mobile we use a "celebratory screen" but the screenshot above might be enough for now? WDYT?

@gsouquet the other issue here: https://github.com/vector-im/element-web/issues/19305 is very similar, what do you think the estimate for 19305 is?

Both: We should decide how/if we want to merge these issues, or if we sequence them. Let me know your thoughts!

**Comment by gsouquet** [comment]
We should aim to achieve both issues. However #19305 seems to require a bit more effort

Let's sequence them as this appears to be a low hanging fruit and spend a bit more time to see whether we can get the server to issue an access token whne registration is succesful. It might require us to create an MSC to change the response frm the registration and the email confirmation endpoints

**Comment by niquewoodhouse** [comment]
> Hey @niquewoodhouse It might be good to include the user's MXID somewhere in the flow here so that they've seen it. On mobile we use a "celebratory screen" but the screenshot above might be enough for now? WDYT?

Just curious - why is seeing their MXID helpful at this time?  Maybe it came up in mobile testing?  Im assuming a bit but I'm guessing most people won't really read much here and the MXiD is not helpful to them in this early stage of their experience, especially as its not useful for logging in?  Web defaults to user name as the login (which might not be right anyway) and not MXID.

Here are some ideas around the issue:
____
**Web celebratory screen with MXiD**
- Content mostly copied from mobile flow
<img width="1440" alt="_option1b@2x" src="https://user-images.githubusercontent.com/1587166/166969942-167d7242-3b6c-4ca7-a5d7-d5b8c0248710.png">

____
**Web confirmation screen with username**
- Less fun, just says username
<img width="1440" alt="_option1a@2x" src="https://user-images.githubusercontent.com/1587166/166971329-b2916274-3d89-4b70-9391-b03dde0ff6ac.png">

____
I can see from the comments above we might do #19305 later on but just to mention some ideas for that: 

**Auto-login route option 1**
- The current home/welcome screen shows username, so could log in and go straight to that
https://user-images.githubusercontent.com/1587166/166972887-691fa2ea-f69f-4f24-8389-6c4d172012bd.mov

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-web/issues/19305 would be wonderful to implement so let's get that scheduled. 

For the meantime, both of your suggestions are great @niquewoodhouse. @gsouquet is there much of a time difference? I think we'd prefer the celebration one? 

To answer your question Nique, you're 💯 right that users don't need to know their whole MXID at this stage because web defaults to username (where mobile doesn't) but we also found in Mobile that folks don't ever really see their MXID as a whole cause it's "hidden" under a click. So if they've signed up and want to share it, they may not know what it is... Happy to move the MXID to another screen or part of the flow but I think it's worth testing putting it in somewhere... WDYT?

**Comment by niquewoodhouse** [comment]
Sounds good, was just really curious, thanks for explaining

**Comment by gsouquet** [comment]
We already have some bits to have confetti particles in the product. We could try and re-arrange that to slot them on the confirmation screen.
I'd recommend we timebox this and see what we manage to generate there

**Comment by gsouquet** [comment]
After some further discussion, this is actually a regression and should not be a thing (view https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$rZMYuTXH86_3vkTh3Au-QG-UWC0CcELIInCg9I9ioFw?via=matrix.org&via=element.io&via=mozilla.org) 

Closing in favour of https://github.com/vector-im/element-web/issues/19305
