### ISSUE TITLE
Read Receipts jump back up to top of the screen before traveling down

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#21953]
### Steps to reproduce

Find a room where someone has their read receipt already on screen, and observe them read the latest message.

#### What did you expect?

Read receipt should travel from their previously-last read message to the bottom

#### What happened instead?
The read receipt zips back up to the top of the screen, then travels all the way down to the message. This looks so odd. Not sure when this regressed but I don't remember Element doing this until I updated.

### Operating system

Arch Linux

### Browser information

Firefox 99

### URL for webapp

self-hosted instance

### Application version

Element version: 1.10.11-11-g7c326f49d-dirty Olm version: 3.2.8

### Homeserver

private instance

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed on develop
