### ISSUE TITLE
A thread does not load on the right if there is another one previously opened. You first have to close the previous thread and then open the new one to read its messages.

### ISSUE THREAD

**Issue by alexmehandzhiyska** [vector-im/element-web#21956]
### Steps to reproduce

1. Open a chat with a friend.
2. Click on a thread to read the messages.
3. Click on another thread to read its messages.

#### What did you expect?
To see the second thread opened on the right.
#### What happened instead?
I still see the first thread as if I haven't clicked on the second one.

### Operating system

macOS

### Application version

Element version 1.10.11

### How did you install the app?

https://element.io/get-started

### Will you send logs?

No

**Comment by andybalaam** [comment]
@alexmehandzhiyska I tried this myself just now and it seemed to work. Please could you re-test it, and if it happens again, please could send logs to help us figure out what is causing the problem? Thanks.

**Comment by t3chguy** [comment]
This is fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8448
