### ISSUE TITLE
Room upgrade stopped inviting former members

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#21957]
### Steps to reproduce

1. Upgraded a room to allow the members of a Space to join. (room version 5 to 9)

#### What did you expect?
All former members get an invite to the new room.

#### What happened instead?
- Only 2 out of 79 people when the modal closed itself.
- The new room's permission were set to "Invite" instead of the expected "Space members"

### Operating system

Manjaro Linux

### Browser information

Mozilla Firefox 99.0b8

### URL for webapp

staging.element.io

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### Homeserver

vector.modular.im

### Will you send logs?

Yes

**Comment by turt2live** [comment]
This is almost certainly because of a rate limit. Closing in favour of spec-generalized solution: https://github.com/matrix-org/matrix-spec/issues/455
