### ISSUE TITLE
Confusing French translation when cancelling upgrade to Element Home

### ISSUE THREAD

**Issue by progval** [vector-im/element-web#21964]
### Steps to reproduce

1. Set your browser to French
2. Click the top left button
3. Click "Mettre à jour vers Element..."
4. Click the top right cross

#### What did you expect?

Should show two with different labels

#### What happened instead?

Shows two buttons labeled "Annuler" ("Cancel")

![Screenshot 2022-04-28 at 08-20-02 Element valtest](https://user-images.githubusercontent.com/406946/165690932-672b859b-c535-40a9-8e8d-e770b6a0de04.png)

### Operating system

Debian 11

### Browser information

Firefox 91.8.0esr

### URL for webapp

https://app.element.io/

### Application version

Element 1.10.11

### Will you send logs?

No

**Comment by t3chguy** [comment]
Translations are all maintained by the community - see https://github.com/vector-im/element-web/blob/develop/docs/translating.md#step-0-join-element-translationsmatrixorg
