### ISSUE TITLE
Login on a new account unable to verify device

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21977]
### Steps to reproduce

1. Create a new account
2. Log in
3. Go to a new browser and login that same account

#### What happened instead?

I have the `Unable to verify this device` E2E dialog asking me to proceed with a "reset".

#### What did you expect?

To be logged in
I have 0 DMs in my new account, and have not setup anything related to encryption. That step should be skipped entirely 

### Will you send logs?

No

**Comment by duxovni** [comment]
On further inspection, it looks like the broken version of Element is attempting to upload its device signatures to the homeserver before it's finished uploading its device signing keys, which leads to the upload getting rejected, so those signatures are missing when the device keys are queried later. I'll continue investigating why that's happening.

**Comment by duxovni** [comment]
Tracked it down to [matrix-org/matrix-react-sdk#8457](https://github.com/matrix-org/matrix-react-sdk/pull/8457/files#diff-b0f859210061ffa5b0e690d01bf0f2103022719dd6c19bd39b7deb4679123246); there's some typing confusion going on, and in the contexts that matter here, `makeRequest` really is an async function and does need to be awaited. I'll put together a PR.
