### ISSUE TITLE
Quoting from the markdown bar breaks formatting

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2197]
I copy pasted a bunch of text including paragraphs and line breaks, selected it all, clicked on the 'quote' button and all my formatting was lost, putting everything as a single line text

**Comment by lukebarnard1** [comment]
It seems that the default behaviour when quoting in draft-js is to quote every "block". So bullets will become individual blockquotes instead of there being one big blockquote encapsulating all. Inline formatting appears to survive however.

**Comment by DJCrashdummy** [comment]
i guess this is related:
i observed that quoting messages with numbering just works until the numbering because the numbers (including its text) is ignored. :frowning_face:

*no idea if it is the same for bullets. - i will report if i fall across such case (and still remember).*

**Comment by yannicka** [comment]
From my side, the composer does not break the formatting, it is the formatted message that is badly formatted.

Original message:

```
a

b
```

I select all and I click on the "Quote" button:

```
> a
> 
> b
```

I send the message.

The message is displayed as:

```
> ab
```

And if I edit the message, the content is:

```
> 
ab
```

The source of the message sent:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "> a\n>\n> b",
    "format": "org.matrix.custom.html",
    "formatted_body": "<blockquote>\nab\n</blockquote>\n"
  }
}
```

The `body` is correct while the `formatted_body` is incorrect.

**Comment by t3chguy** [comment]
@MazeChaZer would you consider this fixed now then?

**Comment by kittykat** [comment]
I'm going to close this for now as it appears to be fixed. Please file a new issue with details if you feel that there are further improvements to be made :+1:
