### ISSUE TITLE
-6 Replies in thread

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#21979]
### Steps to reproduce

Started a conversation in a room normally.
Didn't appear to do anything specia - possibly another user replied to and deleted a message in another thread.

Ended up seeing this:

![Screenshot from 2022-04-28 16-31-20](https://user-images.githubusercontent.com/1917473/165789724-3f011ea0-5308-4709-b245-51214f66c8aa.png)

#### What did you expect?

I don't think this should have been a thread

#### What happened instead?

It was a -6 message thread :)

### Operating system

Ubuntu

### Application version

 Version: 1.10.10

### Homeserver

EMS

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed in 1.10.11 or develop
