### ISSUE TITLE
Element for Windows re-creates the desktop shortcut every time it is updated

### ISSUE THREAD

**Issue by emchristiansen** [vector-im/element-web#21989]
### Steps to reproduce

1. Install Element for Windows
2. Delete the desktop shortcut because you like having a clean desktop
3. Consent to an Element update
4. See that the desktop shortcut has reappeared

### Outcome

Element should remember or figure out that I don't want a desktop shortcut, and stop creating them.

I'll send logs if you need them

### Operating system

Windows

### Will you send logs?

No

**Comment by t3chguy** [comment]
Fixed on develop. Will be in the next release.
