### ISSUE TITLE
Delight: Add password requirements to the create account screen

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21986]
### Your use case

Password creation is hard - especially as we don't share the requirements anywhere when creating an account. The more frustrated a user is the harder it will be for them to remember the password they settled on (and therefore logging in later will be tough)

Is there a way we can add the password requirements on this screen (in a tool tip or otherwise)

<img width="544" alt="Screenshot 2022-04-28 at 13 48 19" src="https://user-images.githubusercontent.com/89144281/165843275-31713618-d386-4194-bd42-4d98a7858f60.png">

**Comment by t3chguy** [comment]
We use https://github.com/dropbox/zxcvbn which doesn't set discrete requirements, just gives passwords a score

**Comment by daniellekirkwood** [comment]
Ok, so we won't be able to add password requirements?

Maybe there are alternative ways to ease this step with copy...?

**Comment by t3chguy** [comment]
The requirements aren't as simple as needs X, Y, Z. Your password can meet the required score being just numbers for example. We can give tips on how to improve a password but not a checklist.

You can try it out at https://lowe.github.io/tryzxcvbn/ - we require a score of 3 or 4.

![image](https://user-images.githubusercontent.com/2403652/166108252-307c73eb-7c17-4c5b-a5e7-294ab87e207b.png)

**Comment by robintown** [comment]
zxcvbn supposedly returns suggestions like "Try adding another word or two", perhaps those could be exposed in the UI to nudge the user toward a good password?

**Comment by t3chguy** [comment]
We do already

![image](https://user-images.githubusercontent.com/2403652/167218698-06e12aef-0048-4f1b-80b0-a49906c03f0e.png)
![image](https://user-images.githubusercontent.com/2403652/167218711-ecf15d80-a08a-460f-a353-456f60caca4c.png)
![image](https://user-images.githubusercontent.com/2403652/167218714-3a5d330b-3d42-47e1-812b-e9ed2f0a3aa9.png)

**Comment by robintown** [comment]
Oh, didn't realize that that's what "This password is similar to another commonly used password" already was

**Comment by daniellekirkwood** [comment]
Thanks, team! 

Looks like this is the best solution we can provide at this stage. 

Appreciate the feedback :)
