### ISSUE TITLE
Delight: 2 spinners on start new DM

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#21988]
### Your use case

Can we remove one of the spinners here?

<img width="376" alt="Screenshot 2022-04-28 at 14 31 28" src="https://user-images.githubusercontent.com/89144281/165849235-26805f07-2dfe-4140-b0db-c80cdd5cf792.png">

**Comment by niquewoodhouse** [comment]
@weeman1337 I think removing the one next to the "Go" button would be best, because the user is sent to the DM, is that right?  When we're directing users to a page its probably best to block them doing something else, so we don't interrupt another flow for them.

**Comment by weeman1337** [comment]
@niquewoodhouse thanks for your feedback.

I am currently working on „create DM on first message“ (#14736). It will change the create-DM-flow and should solve this one as well.

**Comment by weeman1337** [comment]
Solved by the new DM flow
