### ISSUE TITLE
Messages in thread view have their first line indented

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#21997]
### Steps to reproduce

1. Use modern layout
2. View a thread

#### What did you expect?

Uniform indentation

#### What happened instead?

![Screenshot 2022-04-29 at 13-03-51 Element 1 Threads Internal](https://user-images.githubusercontent.com/48614497/165990566-462c81b6-9d29-4504-8c9f-c322a624371c.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: b5336c9a4d51-react-36fd9cb0d4a7-js-2ebf33544f2a Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by luixxiul** [comment]
Introduced with https://github.com/matrix-org/matrix-react-sdk/pull/8442/files#diff-bd83194d78de871bc4ad1c4e8d43102c4368481bbb90705152d3d17fea813919R892.
