### ISSUE TITLE
Call glare breaks catastrophically

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2199]
Overlapping inbound & outbound calls end up with uncancellable calls which ring forever

**Comment by superdump** [comment]
Perhaps https://github.com/matrix-org/matrix-js-sdk/pull/381 improved things. If people can reproduce then they're welcome to test to see if this is still an issue.

**Comment by ara4n** [comment]
this is a disaster still; both callers end up stuck in a totally weird state.

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
