### ISSUE TITLE
Threading modes: always, never, auto. (Zulip/Twist-style threading)

### ISSUE THREAD

**Issue by heyakyra** [vector-im/element-web#21990]
#### What would you like to do?

Rooms / Communities should be able to set a mode which enforces threading for each discussion (Zulip/Twist style), never (IRC), or auto (slack/discord/teams style). 

#### Why would you like to do it?

Threads are now in beta, but currently discussion can be mixed between threads and unthreaded messages, which can be chaotic for discussion as topics fork off. 

This was discussed on the original Threading ticket

> The threads development is great!
> 
> However, one concern is that it doesn't seem to be possible to make a room "thread only". If one looks across the marketplace of chatt apps (open source and closed source) there are basically two thread models available:
> 
>     1. Slack-style threads; all rooms contains messages, but the message may contain sub-messages (threads)
>     2. Zulip / Twist style threads; all rooms contain only threads/topics, and within each thread/topic there are messages
> 
> […]
> 
> In the design discussion on threads, many people have requested it (and those comments have many upvotes):
> 
>     * [Threaded Messaging element-web#2349 (comment)](https://github.com/vector-im/element-web/issues/2349#issuecomment-411738639)
> 
>     * [Threaded Messaging element-web#2349 (comment)](https://github.com/vector-im/element-web/issues/2349#issuecomment-321921360)
> 
>     * [Threaded Messaging element-web#2349 (comment)](https://github.com/vector-im/element-web/issues/2349#issuecomment-452908762)

Via: https://github.com/vector-im/roadmap/issues/8#issuecomment-1084648871

#### How would you like to achieve it?

In always-threaded mode, it should still be possible to "fork" a new thread from an existing one, which would start a new topic in the channel starting with the message in the existing thread.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21465 + https://github.com/vector-im/element-web/issues/20428
