### ISSUE TITLE
'Jump to bottom' button is always displayed on non-overflowing timelines

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22003]
### Steps to reproduce

Create a room

#### What did you expect?

Since I'm scrolled to the bottom of the timeline, the 'jump to bottom' button should not be displayed.

#### What happened instead?

![Screenshot 2022-04-30 at 11-31-48 Element Empty room](https://user-images.githubusercontent.com/48614497/166112102-412b4bb3-1a62-418d-9d77-7ca8344f7119.png)

### Operating system

NixOS unstable

### Browser information

Firefox 99.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 850a250cea91-react-36fd9cb0d4a7-js-2ebf33544f2a Olm version: 3.2.8

### Homeserver

Synapse 1.57.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
From what I gather something changed about the way that the `messsagePanel` ref is set in `TimelinePanel.tsx`, so `isAtEndOfLiveTimeline()` returns undefined when called from `componentDidUpdate()` in `RoomView.tsx` which causes the button to be visible

**Comment by SimonBrandner** [comment]
Or possible `onMessageListScroll()` used to be called once more when everything was fully loaded but it is not called now

**Comment by SimonBrandner** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8392 though I don't think I know how exactly
