### ISSUE TITLE
Lag and high cpu usage 200% on UI interaction

### ISSUE THREAD

**Issue by emanuele-f** [vector-im/element-web#22000]
### Steps to reproduce

Interaction with the element UI is quite laggy and cpu usage goes crazy (peaks at 200% while scrolling messages in a group).

This may be related to https://github.com/vector-im/element-web/issues/21932 .

Here is a performance profile generated while scrolling the messages view in a group:
[Profile-20220429T231217.json.zip](https://github.com/vector-im/element-web/files/8594782/Profile-20220429T231217.json.zip)

#### What did you expect?

The cpu usage should not be so high for a simple ui scroll operation

### Operating system

Archlinux

### Application version

Element version 1.10.11, Element version 1.10.11

### How did you install the app?

from the archlinux repo

### Will you send logs?

No

**Comment by t3chguy** [comment]
Considering fixed as per linked issue
