### ISSUE TITLE
Delight: Add event

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22001]
### Your use case

<img width="465" alt="Screenshot 2022-04-29 at 14 25 51" src="https://user-images.githubusercontent.com/89144281/166071281-0886f740-401a-4446-b205-93f02305a018.png">

This event shows us users who have completed this screen:

<img width="629" alt="Screenshot 2022-04-29 at 14 26 27" src="https://user-images.githubusercontent.com/89144281/166071331-430e34ad-9d13-4c41-8221-440d5201fd7b.png">

Can we have an event that measures the **start** of this? As this event is just the end?

I'd like to see the success of the screen so we can see how many people saw this screen and how many completed successfully. Is this something we can do?

**Comment by daniellekirkwood** [comment]
@gsouquet & @BillCarsonFr 
Any reason we shouldn't add this event?

**Comment by daniellekirkwood** [comment]
https://posthog.hss.element.io/insights/za4O8V5K

**Comment by gsouquet** [comment]
We should be able to add this, 👍  can't think of a reason why not

**Comment by germain-gg** [comment]
Unfortunately the delight team is not more. Closing as not doing
