### ISSUE TITLE
Searching channels for literal strings like "C++20" produces non-useful results

### ISSUE THREAD

**Issue by sliedes** [vector-im/element-web#22010]
### Steps to reproduce

1. Search a channel with lots of history for strings like "C++20" or "C++20 modules". Try all of the following:

- C++20
- "C++20"
- C\+\+20

#### What did you expect?

I expected to find messages mentioning C++20 or C++20 modules, essentially containing the literal string "c++20" or "C++20".

#### What happened instead?

I got a ton of unrelated hits; the logic seems to be something like:

- it matches all messages with words starting with c and that contain "20"
- of those, it highlights fully all words that start with c, only the letter c in the middle of other words, and all instances of "20".

![image](https://user-images.githubusercontent.com/2307997/166215815-ef1f3698-3ef0-49ff-92ed-82cb05bc367a.png)

### Operating system

Arch Linux

### Browser information

Firefox 99.0.1 (64-bit)

### URL for webapp

https://chat.hacklab.fi

### Application version

Hacklab.fi Element version: 1.10.11 Olm version: 3.2.8

### Homeserver

hacklab.fi

### Will you send logs?

No

**Comment by t3chguy** [comment]
@sliedes is the room those results are from Encrypted or not?

**Comment by sliedes** [comment]
> @sliedes is the room those results are from Encrypted or not?

I believe not, but I don't understand Matrix well enough (i.e. I'm barely familiar with it) to be sure. Here's what I could find about the room:

- Room settings->General in Element says its "Main address" is "#please:matrix.org", though that seems grayed out.
- Google search also finds it at https://gitter.im/please-build/Lobby
- In "Security & Privacy", the "Encrypted" toggle seems to be unset, Access is "public" and "Who can read history?" is set to "Members only (since the point in time of selecting this option)".

**Comment by t3chguy** [comment]
If the room is not encrypted then the search is done server-side, could you please open this issue in https://github.com/matrix-org/synapse/
