### ISSUE TITLE
Polls can be edited via right-click menu (even after someone voted)

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#22018]
### Steps to reproduce

Started poll cannot be edited from context menu of the message...
![obrazek](https://user-images.githubusercontent.com/15554561/166238096-f22b1f26-c2aa-4330-a049-f5a2767b8d43.png)
![obrazek](https://user-images.githubusercontent.com/15554561/166237991-407e7f29-9be9-4e57-9ce7-3d292d3f94ff.png)

Nevertheless it can be edited from right click context menu
|||
| ------------- | ------------- |
| ![obrazek](https://user-images.githubusercontent.com/15554561/166238261-9403197c-4c63-45c6-be45-8974ce8c54f5.png)| ![obrazek](https://user-images.githubusercontent.com/15554561/166238335-1244bc1d-7ec0-4544-9ca3-e19077f0f1bb.png)|

#### What did you expect?
Consistency

#### What happened instead?
Inconsistency

### Operating system

Windows 10

### Browser information

Firefox 100b9

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### Homeserver

own

### Will you send logs?

No

**Comment by andybalaam** [comment]
Did you try editing a poll after votes have been cast? I believe the current implementation in Element changes the poll ID, meaning that the previously-cast votes become invalid. So, while this is an annoying bug, I don't think that it is a "security" bug.

Of course, nothing stops someone from crafting a custom event to edit the poll and keep its ID the same, and polls are explicitly not intended for secure voting.

**Comment by waclaw66** [comment]
I haven't said that is a security bug, but just inconsistency between edit button (edit is disabled) and menu item (edit is enabled). Tested in the current version, still persists.
