### ISSUE TITLE
Element: in frame-src CSP

### ISSUE THREAD

**Issue by korneyda** [vector-im/element-web#22025]
#### What would you like to do?
Please, add element: in index.html in frame-src

<meta http-equiv="Content-Security-Policy" content="
        default-src 'none';
        style-src 'self' 'unsafe-inline';
        script-src 'self' 'unsafe-eval' https://www.recaptcha.net https://www.gstatic.com;
        img-src * blob: data:;
        connect-src *;
        font-src 'self' data:;
        media-src * blob: data:;
        child-src * blob: data:;
        worker-src 'self' blob:;
        frame-src * blob: data:;
        form-action 'self';
        manifest-src 'self';
    ">

#### Why would you like to do it?
This will allow to open urls responsible for users and rooms from widgets to the Element for opening
#### How would you like to achieve it?
Add element: to frame-src in CSP

**Comment by t3chguy** [comment]
> This will allow to open urls responsible for users and rooms from widgets to the Element for opening

You can already do this using the Widget API - see https://github.com/matrix-org/matrix-spec-proposals/pull/2931

**Comment by korneyda** [comment]
@t3chguy 
It is true that mxwidgets.MatrixCapabilities.MSC2931Navigate unstable?

Using
widgetApi.requestCapability(mxwidgets.MatrixCapabilities.MSC2931Navigate);
widgetApi.navigateTo(url).then(function(r)

?

**Comment by t3chguy** [comment]
That'd be a question for whatever widgetApi library/driver you're using. Element fundamentally only sees/cares about the postMessage API hit as defined in the spec link above

**Comment by korneyda** [comment]
Thank you
