### ISSUE TITLE
Add CI check for ensuring i18n files are not improperly modified

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22020]
ie: if someone doesn't use `yarn i18n` and modifies the strings directly in all language files, fail the check. May be worth an extension to the existing i18n similarity check

**Comment by t3chguy** [comment]
Example fail https://github.com/vector-im/element-desktop/runs/6269964712?check_suite_focus=true

**Comment by t3chguy** [comment]
Done by https://github.com/vector-im/element-web/pull/21939 + https://github.com/vector-im/element-desktop/pull/351 + https://github.com/matrix-org/matrix-react-sdk/pull/8472
