### ISSUE TITLE
history visibility warnings shouldn't fire on e2e rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2202]

**Comment by ara4n** [comment]
i.e. when inviting into a room etc we shouldn't show 'history will be visible' warnings which are untrue.

**Comment by uhoreg** [comment]
see also https://github.com/vector-im/riot-web/issues/2286

**Comment by kittykat** [comment]
Closing this issue as I don't think we have those warnings any more, please reopen if anyone has come across them recently.
