### ISSUE TITLE
Reply to a message with a voice message

### ISSUE THREAD

**Issue by Hugueprime** [vector-im/element-web#22031]
### Steps to reproduce

1. Select an audio or any other type of message and click reply.
2. Click voice message and record an audio.
3. Send the audio.

#### What did you expect?
I expected the response audio to be linked to the previously selected audio.

#### What happened instead?
The response audio is sent without responding to the selected audio, keeping the previous audio in response mode in the text box area.

### Operating system

Windows

### Application version

Version de Element : 1.10.11 Version de Olm : 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

custom

### Will you send logs?

No

**Comment by Hugueprime** [comment]
Thank you for your work on this !

**Comment by SimonBrandner** [comment]
> Thank you for your work on this !

np! :)
