### ISSUE TITLE
Menu items in composer More options menu are not highlighted on hover

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22046]
### Steps to reproduce

1. Open any chat
2. Click the three dots next to the message composer
3. Hover the items

#### What did you expect?

- Icon should change its colour to keep in sync with the other buttons next to the three dots
- Background should indicate the hovered item like it is working for other menus:

![message_menu](https://user-images.githubusercontent.com/6216686/166667133-355a5796-9eaa-4222-bb63-25085dcfe2ee.gif)

#### What happened instead?

- Icons are highlighted
- Background is not

![composer_menu](https://user-images.githubusercontent.com/6216686/166667018-3e955e87-e7c2-4c0e-92bd-d270576c4de3.gif)

### URL for webapp

https://develop.element.io/

### Will you send logs?

No

**Comment by gaelledel** [comment]
<img width="454" alt="Screenshot 2022-05-05 at 11 14 08" src="https://user-images.githubusercontent.com/76945183/166894543-8bbb0008-95c1-4c28-a1d6-ab33169f1f70.png">
@weeman1337 Let's keep the model above for the composer so all you'd need to do is to remove the green state on the icons and simply add the hover overlay
