### ISSUE TITLE
Report Content gets an "request failed: CORS request rejected"

### ISSUE THREAD

**Issue by cremesk** [vector-im/element-web#22045]
### Steps to reproduce

(same issue with Desktop app and the browser client https://element.envs.net)

If i like to send an Report of an event i get this error:
![image](https://user-images.githubusercontent.com/7526990/166638652-aa1bc2b8-afb8-4274-b41a-36fcc79323fc.png)

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.envs.net/_matrix/client/r0/rooms/x/report/x. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, *’)`

my nginx configuration is very basic and available here:
https://git.envs.net/envs/matrix-conf/src/branch/master/etc/nginx/sites-available/matrix.envs.net.conf

The problem seems to be something newer. I know that the Report function worked a while ago with the same settings.

### Outcome

.

### Operating system

Ubuntu

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#linux-details

### Homeserver

envs.net / Synapse 1.58.0

**Comment by t3chguy** [comment]
`*, *` is not a valid value for the Access-Control-Allow-Origin 

Probably related to your `always` on the add_header

Either way, a server misconfiguration, when ACAO/CORS trips, the app has no way to access the API.

**Comment by cremesk** [comment]
i found the problem..
i use the mjolnir report function (https://github.com/matrix-org/mjolnir#enabling-readable-abuse-reports)

if i comment out the cors header here it works fine:
https://git.envs.net/envs/matrix-conf/src/branch/master/etc/nginx/include.d/mjolnir-report.conf#L4
