### ISSUE TITLE
[Dendrite Server] Going into Threads locks up room 

### ISSUE THREAD

**Issue by madprogramer** [vector-im/element-web#22056]
### Steps to reproduce

1. Connect to Element, from a Dendrite homeserver.
2. Join any room.
3. Attempt to enter threads from the top bar.
4. Element should now crash.
5. No matter how many times you reload, it will try to open the threads tab again and keep failing.

Temporary Solution:
Logging in from `https://app.element.io/` seems to bypass the UI cache, defaulting to the room itself and not the thread-view.

#### What did you expect?
A warning message

#### What happened instead?
Deadlock in trying to access inaccessible threads.

### Operating system

macOS

### Browser information

Chromium: 100.0.4896.127 (Official version) (x86_64)

### URL for webapp

Element Web (1.10.9)

### Application version

Element version: 1.10.9

### Homeserver

madpro.world (Dendrite)

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed in 1.10.11 - please update
