### ISSUE TITLE
Devtools window's bottom is cut off

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22051]
### Steps to reproduce

use devtools

### Outcome

![image](https://user-images.githubusercontent.com/2803622/161378656-1ecee554-b113-4fa5-9049-ff87d5e43699.png)

see also #20911

### Operating system

arch

### Application version

Element Nightly version: 2022040201 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.57.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
This has been fixed since. You're on a very old Nightly.

**Comment by HarHarLinks** [comment]
You're correct, I just migrated this comment to a new issue upon request without checking if it was fixed. Sorry for the overhead caused.
