### ISSUE TITLE
Remove the blue dot on the Spaces panel

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22061]
See discussion below but we would like to: 
- Remove the blue dot from the Add Space icon as we think this will be less distracting for new users and simplify the first session.

Previous issue content. 
> Delay the blue dot on the Spaces panel to the second time that a user logs in. 
> Right now the blue dot draws the user's attention but it's not the most important thing for them to do in their first session. 
> We think delaying the dot will improve the user's experience

**Comment by daniellekirkwood** [comment]
@niquewoodhouse Do you agree with this issue, is there an alternative time that you think the blue dot would work better?

**Comment by t3chguy** [comment]
There's unfortunately no way for the client to differentiate between log-in and registration due to how SSO works, we could track on the server the second time they log in with a supported client (EW) if that'd help

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse Do you agree with this issue, is there an alternative time that you think the blue dot would work better?

I agree we should delay it, but not sure if second log in is right (just my opinion).  

I actually vote for just getting rid of it completely.  It was there to really say "hey, new thing here".   I don't know if that's still worth telling people. I wonder if it is necessary to promote the feature still?  Does it just distract people from other goals they might have?

**Comment by daniellekirkwood** [comment]
Whatever you recommend @niquewoodhouse but I think the first session is not the right place... :) 

Thanks for the feedback, @t3chguy ! Good to know

**Comment by niquewoodhouse** [comment]
> Whatever you recommend @niquewoodhouse but I think the first session is not the right place... :)
 
Cool, I totally agree.  My recommendation is we just remove it, it has served its purpose.

**Comment by daniellekirkwood** [comment]
Updating the issue core to reflect this decision
