### ISSUE TITLE
Pinned poll has different vote count than the one in the timeline/history

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22078]
### Steps to reproduce

1. Start a poll in a reasonably high traffic room
2. Pin the poll
3. Wait N days, where N > 1
4. Open the pins to see the poll. Note the vote count increase as it fetches data from the server.
5. Click 'view message' to jump to the poll
6. Note that the poll has a different count and doesn't increase.

#### What did you expect?

That the poll have the same vote count regardless of the panel it's shown in.

#### What happened instead?

Presumably when I jumped to the poll in the timeline it changed which timeline segment it was looking at, so it missed most of the votes because they were in a different timeline segment.

### Operating system

Windows 10

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by turt2live** [comment]
Worse: when I click "reply" on that poll, I get a third count of "no votes cast" in the preview :|

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/166860694-4f505885-6040-4e7e-8a31-cac5354d2ce1.png)

**Comment by kerryarchibald** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9877
