### ISSUE TITLE
Delight: Default to dark mode?

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22075]

**Comment by t3chguy** [comment]
Don't we already default to match system theme?

**Comment by turt2live** [comment]
it's somewhat more rare that folks don't have their OS set to dark mode, but want applications as dark mode by default.

**Comment by daniellekirkwood** [comment]
I wonder if we can pull data on who has dark mode on right now and if there's a correlation to the use case

**Comment by t3chguy** [comment]
@daniellekirkwood it is stored on-device only atm, and we don't have it hooked up to Posthog yet
