### ISSUE TITLE
my friend created a thread which is misbehaving

### ISSUE THREAD

**Issue by rrix** [vector-im/element-web#22087]
### Steps to reproduce

- my friend made a thread in response to a message in a e2e 1:1 room last night
- on android element the thread only shows the first message with my text included as the typical "in reply to", but he sent 6 messages
- i "gave feedback" in the android app about an hour ago
- on their phone, it shows all the messages outside the thread UI (maybe they just don't have the feature turned on there)
- opening the threads UI on element-web crashes the chat. I will upload 

#### What did you expect?

to see a thread with 6 messages

#### What happened instead?

element-web doesn't load the room any more saying "Something went wrong!", and android doesn't show the thread messages besides the first

### Operating system

NixOS

### How did you install the app?

github.com/nixos/nixpkgs

### Homeserver

Element version: 1.10.9 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by robintown** [comment]
The crash in Element Web has been fixed, please update to a more recent version (and consider using a more up to date homeserver for proper threads support). Element Android issues should be filed at https://github.com/vector-im/element-android/issues/.
