### ISSUE TITLE
bugged out html 5

### ISSUE THREAD

**Issue by solomoncyj** [vector-im/element-web#22083]
### Steps to reproduce

1. Where are you starting? What can you see?
>home screen
3. What do you click?
quick settings > theme > dark
5. More steps…

#### What did you expect?
nothing to happen

#### What happened instead?
![image](https://user-images.githubusercontent.com/74647769/166901988-072d9af8-c001-41e0-850c-f195b561e32f.png)

### Operating system

windows

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

installer

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Can you restart the app (right click in tray, Quit) and send logs please.

**Comment by solomoncyj** [comment]
done

**Comment by solomoncyj** [comment]
Any Updates

**Comment by t3chguy** [comment]
Nothing comes up in the logs, please open the javascript console using Ctrl + Shift + I and screenshot that over

No one else seemingly has reproduced this issue

**Comment by solomoncyj** [comment]
Does nodejs make thiss happen?

**Comment by solomoncyj** [comment]
https://user-images.githubusercontent.com/74647769/178031205-8efa616a-3d86-42c0-874b-7231f6c638fc.mp4

some more updates

**Comment by solomoncyj** [comment]
@t3chguy

**Comment by solomoncyj** [comment]
Hello?

**Comment by t3chguy** [comment]
@solomoncyj no one has yet managed to reproduce it, so we have no way to figure out what is causing it to behave as it does for you.

**Comment by solomoncyj** [comment]
What node is do you use? Maybe because of version differences

**Comment by solomoncyj** [comment]
.

**Comment by t3chguy** [comment]
@solomoncyj Yes? You said the issue was related to your local copy being corrupted, shouldn't you close this issue then?
