### ISSUE TITLE
Reactions go off screen when using message bubbles

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#22093]
### Steps to reproduce

1. Where are you starting? What can you see?
I have message bubbles turned
2. What do you click?
I' spam reactions to a message
3. More steps…
I resize the client to a small width

#### What did you expect?
I expected reactions to wrap to the timeline width
#### What happened instead?
1. At some point the Show all button became two rows high and it added an unnecessary row to all my reactions:
![image](https://user-images.githubusercontent.com/18530109/167134463-6e2855af-90af-4456-8fc0-ce2f8497c6c4.png)

2. After making the width even smaller, reactions started to go off screen:
![image](https://user-images.githubusercontent.com/18530109/167134722-ee9a6117-c70e-4aeb-88dd-16e1341f2ea6.png)

### Operating system

Windows 11 Home 21H2

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by luixxiul** [comment]
I've tried, and found that the issue was to figure out how to make the reactions of the left column (on others posts) and the right column (on your posts) wrapped symmetrically, including the position of addReactionButton and `Show All` link button.

**Comment by yaya-usman** [comment]
@frakic i am interested in this issue, but i will like to know what would you expect it to do when the size is smaller, wrap around?

**Comment by yaya-usman** [comment]
@frakic i am interested in the issue, i want to be clear of what is needed to be done first, you want it as the image below right?

**Before**
![Capture2](https://user-images.githubusercontent.com/38439166/167411305-f4e82d94-9f60-4daa-978e-22aba1321400.PNG)

**After**
![Capture1](https://user-images.githubusercontent.com/38439166/167411372-54f67bb6-e589-41d6-a123-ca7191484743.PNG)
