### ISSUE TITLE
Remove some under-used/burdensome labs flags

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22099]
**All of these flags need a discussion - do not remove them without talking to someone first, please.**

* [x] Do not disturb
* [x] Custom status messages
* [x] Widget screenshots
* [x] Current avatar and name in history (non-historical profiles) - **needs plan**
* [ ] Mjolnir
* [x] Multiple integration managers
* [ ] New room breadcrumbs (Delight)

**Comment by turt2live** [comment]
first round here: https://github.com/matrix-org/matrix-react-sdk/pull/8521

**Comment by turt2live** [comment]
widget screenshots are not technically removed, just better placed: https://github.com/matrix-org/matrix-react-sdk/pull/8522

**Comment by aaronraimist** [comment]
No not Mjolnir 😭

**Comment by turt2live** [comment]
It's just not a practical labs flag to keep around, unfortunately. I'm hoping to implement its effects through the spec rather than keep it as an awkward element-web-only labs flag. 

Though, the full plan needs to be figured out. We'd for sure be keeping the timeline representation of the state events.

**Comment by Mikaela** [comment]
I am also missing DND and would miss Mjolnir.

Is there any Spec issue to be followed on soft ignores which still allow seeing the ignored message through clicking it?

Prior art: WeeChat IRC client has /filter e.g. https://www.aminda.eu/blog/english/2015/05/31/weechat-filter.html

**Comment by turt2live** [comment]
I'm actually going to close this as a plan has been made for the ones this issue was intended to cover. Other labs flags not personally maintained/written by me should get their own respective issues.

**Comment by aaronraimist** [comment]
@Mikaela spec issue is https://github.com/matrix-org/matrix-spec/issues/414
