### ISSUE TITLE
Re-inviting to a rejected invite isn't syncing

### ISSUE THREAD

**Issue by hifi** [vector-im/element-web#22106]
### Steps to reproduce

1. Have a (possibly private) room #R and user A who can invite to it
2. A: invite B to #R
3. B: reject invite to #R (from Element web)
4. A: re-invite B to #R

#### What did you expect?
New invite is shown in Element web that can be used to join.

Hydgrogen works correctly as an example.

#### What happened instead?
Nothing (visually).

If I `/join` the room id by hand or through a clickable link the room is joined _but_ the room state is completely wrong until clear cache & refresh. This may be due to a rejected room being moved to "historical" rooms and the state not being refreshed when joining back.

### Operating system

Linux

### Browser information

Firefox 91.8.0esr

### URL for webapp

https://develop.element.io

### Application version

Element version: a94323fc368e-react-c86040b77a48-js-da69ca215b9c Olm version: 3.2.8

### Homeserver

Synapse 1.5x

### Will you send logs?

Yes

**Comment by turt2live** [comment]
This looks like an annoying bug in the room list:

`!CWPHJgjUpaifgZrhMC:localhost is reportedly new but is already known - assuming TagChange instead`

so it's not jumping from Archive -> Invited for some reason.

**Comment by turt2live** [comment]
looks like this is actually more sinister: the js-sdk isn't even emitting anything for the room. It's an easy fix, but testing it will be interesting.
