### ISSUE TITLE
Pasting links creates blank markdown url syntax

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#22117]
### Steps to reproduce

1. Have nothing selected 
2. Paste a link in the input box

#### What did you expect?

Just to paste that link

#### What happened instead?

Instead it creates `[](<link to be pasted>)`

Possibly a regression from https://github.com/matrix-org/matrix-react-sdk/commit/dfc7224fc7c7d05bc86ff28e0992763829f35681? To my understanding it should convert to markdown when text is selected, not when directly pasting the link.

Video:

https://user-images.githubusercontent.com/62639087/167366713-5c1f89b8-a6e2-4e4d-bc05-e9cec3e156cd.mp4

### Operating system

Arch LInux

### Browser information

Firefox 100

### URL for webapp

https://develop.element.io/

### Application version

Element version: 31b43542cdc6-react-aa8e3dbfb45a-js-da69ca215b9c Olm version: 3.2.8

### Will you send logs?

No

**Comment by nadonomy** [comment]
Very vocal +1 to this issue. The experience is unexpected & frustrating, and completely unusable for those who don't know MD syntax.
