### ISSUE TITLE
Tooltip persists after closing modal

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22121]
### Steps to reproduce

1. click on "(edited)"
2. click anywhere

### Outcome

https://user-images.githubusercontent.com/2803622/167433346-a20065f5-c3a4-402d-b62b-2ad3a3803d80.mp4

### Operating system

arch

### Application version

Element Nightly version: 2022050901 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.58.1

### Will you send logs?

No

**Comment by robintown** [comment]
Applies to many tooltips across the app, such as those on beta pills
