### ISSUE TITLE
Square bracket escaped in edit composer

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#22127]
### Steps to reproduce

https://user-images.githubusercontent.com/769871/167585773-cb2f9d52-a4d6-49e8-8393-2b634a6a6477.mov

### Outcome

not that

### Will you send logs?

No

**Comment by yaya-usman** [comment]
I think this is due to markdown being enabled, it exhibit the behavior for text containing `\` as well it tries to escape it. Linking a PR which supposedly solves this but not sure if its the right solution. I will need some guidance.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22456
