### ISSUE TITLE
Calendar icon in jump to date field is not theme-aware

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22124]
### Steps to reproduce

1. Enable jump to date labs flag (requires compatible homeserver)
2. Enable dark theme
3. Try to jump to a date from the date separator

#### What did you expect?

A theme-aware icon.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/167470742-9d12efa9-76a0-4de5-a615-b36a530e847d.png)

If you look closely, it's on the right side of the field. This usually means we're using an `img` tag rather than a mask, which would be aware of the theme.

### Will you send logs?

No

**Comment by robintown** [comment]
That icon is put there by your browser, not Element. In Firefox you get an 'x' button:

![Screenshot 2022-05-09 at 14-19-59 Element 1 Test room](https://user-images.githubusercontent.com/48614497/167472495-f7f2f1c8-c884-4a8a-be7b-552399bd4123.png)

**Comment by robintown** [comment]
https://stackoverflow.com/questions/62162645/change-color-of-chromes-calendar-icon-in-html-date-input

**Comment by turt2live** [comment]
Oh my. Well, this is electron :D
