### ISSUE TITLE
Accepting an already-open search result should move the cursor for typing a message

### ISSUE THREAD

**Issue by Isodome** [vector-im/element-web#22130]
### Steps to reproduce

1. Open Element Web, open any room
2. Hit Ctrl+K and search for the room that's already open
3. Hit enter to switch the UI to that room (that's already open)

#### What did you expect?
After hitting Enter I expected the cursor to move to the chat's text box so I can start authoring a message. That's what happens if you switch to another room using the ctrl+k method.

#### What happened instead?
The search bar stays highlighted so any further text appears in the search bar, not the chat window.

### Operating system

Debian

### Browser information

Chrome 101.0.4951.54

### URL for webapp

https://one.element.io

### Application version

 1.10.11

### Homeserver

https://one.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is fixed by the new search experience beta

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/2403652/167626507-35669c82-c49a-4689-8e0a-0382fa310126.png">
