### ISSUE TITLE
Can't switch back to bright theme (design)

### ISSUE THREAD

**Issue by srn271** [vector-im/element-web#22140]
### Steps to reproduce

1. Switch to dark theme
2. Switch back to bright theme

#### What did you expect?
The app appears again in bright theme.

#### What happened instead?
The app remains in dark theme, but the option is changed to bright theme.
Doesn't matter if via quick settings or normal settings menu.

![image](https://user-images.githubusercontent.com/11979498/167796326-b2f801eb-0a30-4845-bcc4-6cd8878abe47.png)

### Operating system

Windows

### Application version

Element: 1.10.12 Olm: 3.2.8

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Duplicate https://github.com/vector-im/element-web/issues/19514
