### ISSUE TITLE
"View source" sometimes doesn't open the dialog

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22143]
### Steps to reproduce

1. Post a message
2. Delete it
3. Click on ⋯ -> View source

#### What did you expect?
Could view source for deleted message. Changing layout didn't fix the issue

#### What happened instead?
Couldn't open "View source" dialog:

https://user-images.githubusercontent.com/51663/167817299-88b5e237-aa6b-4da3-9142-8118b29868fe.mp4

![Screenshot from 2022-05-11 10-31-56](https://user-images.githubusercontent.com/51663/167818148-20abf82a-9d6c-4156-bb54-b45b2058028d.png)

Major -> don't know of any workarounds
Uncommon -> can't reproduce reliably

### Browser information

Chromium 100.0.4896.127 (Official Build) Arch Linux (64-bit)

### URL for webapp

app.element.io & develop.element.io

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed on develop
