### ISSUE TITLE
Desktop notifications for messages in a thread don't show the sender

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#22152]
### Steps to reproduce

In a room where I have noisy notifications, if someone sends a message to a room as a thread reply, the desktop notif includes the body, but *doesn't* include the sender/author.

Example message: https://matrix.to/#/!qNkemcgdvkDSHWNhDg:lant.uk/$yllnXTmLyOVGFR4_L_z9F72ooNAByH4WAjbKw_EUR8g?via=lant.uk&via=matrix.org&via=element.io

#### What did you expect?

Desktop notif should be the same as every other message

#### What happened instead?

Notif is missing the sender

### Operating system

macOS 

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

from element.io

### Homeserver

Synapse 1.58

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Cannot reproduce

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/2403652/167897694-df37f1d1-0ec4-465b-bc19-874008133871.png">

**Comment by gsouquet** [comment]
<img width="374" alt="Screenshot 2022-11-15 at 10 38 50" src="https://user-images.githubusercontent.com/769871/201898915-31c0b197-4e5d-4d2d-944a-e27d16eb2dea.png">

I believe this has been addressed
