### ISSUE TITLE
"Don't send read receipts" lab no longer clears notification badge on the room

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#22154]
### Steps to reproduce

1. Receive a notification while on the room
2. Despite hovering the mouse over the window while it is focused and sending a message in the room, the notification badge on the room list no longer clears
3. I move to another room, select it again, and it still doesn't clear
4. I go to Labs, disable "Don't send read receipts" lab, then go to the room again, and the badge clears
5. Re-enable the lab
6. Repeat process and the problem happens again

#### What did you expect?
Notification badge should clear either when you're currently in the room and the Element window is focused, OR you're not in the room and then go to select it 

#### What happened instead?
Badge never clears when "Don't send read receipts" lab is on:
![image](https://user-images.githubusercontent.com/41203525/167917177-c1739ee7-90a4-43ad-aae6-ef627937cdd0.png)

Note: This only started happening when upgrading from 1.10.11 to 1.10.12

### Operating system

Arch Linux

### Browser information

Firefox 100

### URL for webapp

Internal instance

### Application version

Element version: 1.10.12-16-g479d4bf64-dirty Olm version: 3.2.8

### Homeserver

Private instance

### Will you send logs?

No

**Comment by robintown** [comment]
What version of Synapse are you running? The MSC has changed, so you'll need to run at least Synapse 1.59.0rc1 to get the latest server-side support.

**Comment by SimonBrandner** [comment]
> What version of Synapse are you running? The MSC has changed, so you'll need to run at least Synapse 1.59.0rc1 to get the latest server-side support.

Yep, the MSC has changed a lot:

https://github.com/matrix-org/synapse/pull/12168
https://github.com/matrix-org/matrix-js-sdk/pull/2221
https://github.com/matrix-org/matrix-react-sdk/pull/7993

Once all of your software is up to date, it should work again

**Comment by BurnyBoi** [comment]
Oh, I am out of date then for sure. I'm currently on the arch repo version though and it's been flagged out of date for a while with no progress since 1.57.0

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/pull/12168 is not even released yet, closing as running incompatible software for the labs option chosen
