### ISSUE TITLE
Sometimes confetti falls from the top when an unrelated reaction is made to a thread

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22150]
### Steps to reproduce

I'm not sure what the initial trigger is, but it could be a :tada: in the timeline or in the first thread message

1. React to a thread with anything other than :tada:  (e.g. react with :grinning: )

#### What did you expect?
No confetti

#### What happened instead?
Confetti rains down from the sky

### Browser information

Chromium 100.0.4896.127 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 479d4bf64d97-react-e2a612b07083-js-923ff4b282b7 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/24811
