### ISSUE TITLE
Allow for multiple social-sign-on for a single account

### ISSUE THREAD

**Issue by deanveloper** [vector-im/element-web#22158]
#### What would you like to do?

I would like to link both my google and github accounts to my matrix user.

#### Why would you like to do it?

So that I can use either one.

#### How would you like to achieve it?

In the settings, there should be an option to add social sign-on options to an already-existing account.

### Have you considered any alternatives?

There isn't a clear alternative to this, other than being forced to only use one account. I use my Github account for now, but would like to transition to using my Google account since the 2FA for Google is quite a bit simpler than Github.

### Additional context

With https://github.com/matrix-org/synapse/pull/9110, it looks like this should be possible from a protocol standpoint. But I am not entirely sure.

**Comment by t3chguy** [comment]
SSO is entirely done by the server

Closing in favour of https://github.com/matrix-org/synapse/issues/9441
