### ISSUE TITLE
can't build on Slackware GNU/Linux: builds for Debian!

### ISSUE THREAD

**Issue by dchmelik** [vector-im/element-web#22169]
### Steps to reproduce

yarn install
yarn run fetch --importkey
yarn run fetch --cfgdir ""
yarn run build

#### What did you expect?
SlackBuild a txz.

#### What happened instead?
d@cosmos:~/math/src/network/chat/element-desktop-1.10.12$ yarn install
yarn run fetch --importkey
yarn run fetch --cfgdir ""
yarn run build
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.11: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.7: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-plugin-matrix-org@0.4.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.5.1".
warning " > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
yarn run v1.22.10
$ yarn run mkdirs && node scripts/fetch-package.js --importkey
$ mkdirp packages deploys
Key imported!
yarn run v1.22.10
$ yarn run mkdirs && node scripts/fetch-package.js --cfgdir ''
$ mkdirp packages deploys
Downloading https://github.com/vector-im/element-web/releases/download/v1.10.12/element-v1.10.12.tar.gz...
Downloading https://github.com/vector-im/element-web/releases/download/v1.10.12/element-v1.10.12.tar.gz.asc...
packages/element-v1.10.12.tar.gz downloaded and verified
Skipping config file
Pack deploys/element-v1.10.12 -> webapp.asar
Done!
yarn run v1.22.10
$ yarn run build:ts && yarn run build:res && electron-builder
$ tsc
$ node scripts/copy-res.js
  • electron-builder  version=22.11.4 os=5.17.6
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=17.4.0 appOutDir=dist/linux-unpacked
  • building        target=deb arch=x64 file=dist/element-desktop_1.10.12_amd64.deb

### Operating system

Slackware64 15.1-current

### Application version

element-desktop-1.10.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
You can pass whatever build parameters you want to electron-builder - https://www.electron.build/configuration/linux https://www.electron.build/cli you probably want `-l tar.xz` or similar

**Comment by dchmelik** [comment]
A Slackware package isn't just a .tar.xz.  README says element-desktop builds for any OS... not even for the longest-lasting GNU/Linux...

**Comment by t3chguy** [comment]
Where does it say it builds for any OS?
And building for an OS does not mean it'll package it in the very specific way that OS wants it. You can use `-l --dir` and have a build compatible with your OS, then use your OS tooling to package it in its native way if not inherently supported by electron-builder

Inherently build != package

**Comment by dchmelik** [comment]
Linux is a kernel typically used with GNU OS (or sometimes Android.)

**Comment by t3chguy** [comment]
Well some tools simplify what they refer to as OS, including electron-builder, breaking it down to macOS, Windows and Linux. 

If you expect native support for slackware style packaging I suggest opening an issue in https://github.com/electron-userland/electron-builder

> builds for Debian!

No, it builds for Linux (whatever flavour of Linux you are running) - by default packages for Debian (even if that isn't your chosen flavour), which you can tweak using the command line args linked previously, though as above Slackware is not a supported packaging medium. Closing as issue is upstream, if you wish to re-word the README such that it makes more sense to you, a pull request will be considered.
