### ISSUE TITLE
"Something went wrong" 

### ISSUE THREAD

**Issue by DMRobertson** [vector-im/element-web#22166]
### Steps to reproduce

I'm not sure what happened. I navigated to "Element (New Vector) Internal" and saw this:

![Screenshot from 2022-05-12 20-21-37](https://user-images.githubusercontent.com/8614563/168152342-3358eed7-5196-4a3f-90e8-7ca5f6472c42.png)

I've been joined to that room for ages (browsed it earlier today without any problems).

Debug logs to follow.

#### What did you expect?

See the room timeline.

#### What happened instead?

Saw the error screen.

### Operating system

Linux, Fedora 35

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

Flatpak from https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org, Synapse 1.59.0rc1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This has been fixed in 1.10.12 - please update.
