### ISSUE TITLE
Mismatched room ID (unable to decrypt errors)

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#22171]
### Steps to reproduce

1. Start my day, open Element, click on a room

#### What did you expect?
To see all messages

#### What happened instead?
Several rooms show Unable to decrypt errors. This one says "mismatched room id":
![image](https://user-images.githubusercontent.com/76812/168241534-7b997d8e-b7c1-471e-8e22-c06575bd7b13.png)

(These are probably unrelated, but happened at the same time:
![image](https://user-images.githubusercontent.com/76812/168241870-ee3eadcc-cd08-4017-961d-4419ce408b3b.png)
Note that some of these messages were sent by me, on my phone.
)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 99.0

### URL for webapp

https://develop.element.io

### Application version

Element version: 479d4bf64d97-react-d87cfae0c97f-js-4721aa1d241a Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by babolivier** [comment]
The first error (which I've seen before and looks like it only happens in threads) is on a message from me, I've rageshaken from the device that sent it here: https://github.com/matrix-org/element-web-rageshakes/issues/12915

**Comment by t3chguy** [comment]
Please track all general UISI/UTDs in https://github.com/vector-im/element-web/issues/2996

**Comment by michaelkaye** [comment]
FTR, This error is a unique one as far as I've seen `** Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !XXX:matrix.org, was undefined) **"` rather than the standard key missing errors, but it is probably related to other reports - eg #22094

**Comment by babolivier** [comment]
> Please track all general UISI/UTDs in #2996

The first one is not a general one though: `Mismatched room_id for inbound group session (expected ![...], was undefined)`

Plus it seems to only happen in threads.

**Comment by andybalaam** [comment]
Re-opening because I don't think this is general.

**Comment by t3chguy** [comment]
In that case this is a duplicate of https://github.com/vector-im/element-web/issues/22094 - no?

**Comment by andybalaam** [comment]
Duplicate of #22094
