### ISSUE TITLE
Emoji is clipped at the top in the composer

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#22170]
### Steps to reproduce

<img width="289" alt="Screen Shot 2022-05-13 at 10 12 05" src="https://user-images.githubusercontent.com/769871/168240568-1386b0fc-8593-4306-bead-c543f82d7b06.png">

#### What did you expect?

For the emoji not to be clipped

#### What happened instead?

See the screenshot

### Operating system

macOs

### Browser information

Element Desktop 

### Application version

Nightly from 13th of May

### Will you send logs?

No

**Comment by robintown** [comment]
What browser and OS is this?

**Comment by gsouquet** [comment]
@robintown updated the original ticket
