### ISSUE TITLE
Redacted message line heights are different from messages, and have timestamps not vertically centered

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22181]
### Steps to reproduce

1. Send a single-line message
2. Note resulting dimensions of elements
3. Redact it
4. Note difference in dimensions

#### What did you expect?

Uniform styling and behaviour between redacted and unredacted messages, at least for the single-line case.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/168316465-a57bf1e0-4ac7-4c6a-8514-66e43e04bb75.png)

The redacted message's timestamp is up against the avatar rather than being vertically centered, and the height of the message body is different by about 5-10px.

### Operating system

Windows 10

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I am not sure if this is related but these also look weird:

![2022-05-13_17-35](https://user-images.githubusercontent.com/25768714/168317876-bab8157d-2783-4a66-a3b7-ca7d1dbd0605.png)
