### ISSUE TITLE
Own avatar in threads is flush with the right side of the panel

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22188]
### Steps to reproduce

1. Enable bubble layout
2. Send a message in a thread

#### What did you expect?

My avatar should have some amount of padding between it and the right side of the panel

#### What happened instead?

It's uncomfortably close to the edge:

![Screenshot 2022-05-13 at 14-32-13 Element 1 #element-dev matrix org](https://user-images.githubusercontent.com/48614497/168345832-6379505a-2fb8-4ac5-91d6-afd5c07af839.png)

### Operating system

NixOS unstable

### Browser information

Firefox 100.0

### URL for webapp

develop.element.io

### Application version

Element version: f2c8e89053ee-react-1fc80091091a-js-72013341dbb2 Olm version: 3.2.8

### Homeserver

Synapse 1.58.0

### Will you send logs?

No

**Comment by luixxiul** [comment]
I believe the this is essentially same as https://github.com/vector-im/element-web/issues/22084 as the space between the avatar and the right border is secured with `overflow-y: scroll` on https://github.com/matrix-org/matrix-react-sdk/blob/b54c7d8fafe3aee87189b6b72863c42c1ec7debe/res/css/views/right_panel/_ThreadPanel.scss#L112.

FWIW the border width change can globally (=outside of Firefox as well) be observed on xfce, mate, and Gnome, so I guess specifying the width with pixel might be required to fix the issue.

**Comment by robintown** [comment]
Ah, you're right, this is reproducible with Firefox 100 on app.element.io as well. I don't think we should rely on scrollbars taking up space to create padding.

**Comment by gsouquet** [comment]
Looks like this has been fixed!

<img width="233" alt="Screenshot 2022-11-15 at 10 34 43" src="https://user-images.githubusercontent.com/769871/201898014-c8877864-3c38-40b9-bec2-0f9e9c9ec9aa.png">
