### ISSUE TITLE
Flag emojis for England, Scotland, and Wales get turned into black flags

### ISSUE THREAD

**Issue by duxovni** [vector-im/element-web#22196]
### Steps to reproduce

1. Start composing a message
2. Open the emoji picker
3. Go to the very end of the flags section, where 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁳󠁣󠁴󠁿 🏴󠁧󠁢󠁷󠁬󠁳󠁿 are
4. Click one of those emojis

Alternatively:
1. Start composing a message
2. Paste in a 🏴󠁧󠁢󠁥󠁮󠁧󠁿, 🏴󠁧󠁢󠁳󠁣󠁴󠁿, or 🏴󠁧󠁢󠁷󠁬󠁳󠁿 emoji from the clipboard

#### What did you expect?
The emoji are displayed properly in the message composer and in the timeline.

#### What happened instead?
All three of these emoji appear as black flags in the message composer and in the timeline after sending.

It still takes 7 backspace keystrokes to delete them in the composer, which suggests that all of the unicode codepoints are still present, but for some reason only the initial U+1F3F4 Black Flag is displayed, and the remaining codepoints are hidden rather than being combined into the flag properly. The emoji also display properly in "View Source".

I've reproduced this behavior on
- develop.element.io in Firefox
- Element Desktop 1.10.11 on NixOS Unstable
- Element Desktop 1.10.12 on Arch Linux

My guess is this is an unrelated issue from #16884:
- This is reproducible across platforms and between browser/desktop, while the trans flag is only broken in Arch Linux's Element Desktop package
- The 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁳󠁣󠁴󠁿 🏴󠁧󠁢󠁷󠁬󠁳󠁿 emojis display properly in the emoji picker and in View Source, whereas the trans flag in Arch Desktop is broken into its constituent glyphs everywhere.
- As mentioned, these emoji take 7 backspace keystrokes to delete because the joiner characters aren't being combined properly. The broken trans flag still only takes one keystroke to delete, which suggests it's more an issue around fonts/display.

### Will you send logs?

No

**Comment by simpleAndrew** [comment]
Hey there!

Any plans to get this fixed somehow? :)

**Comment by Half-Shot** [comment]
I suspect this is due to us splitting emoji's in messages into mx_emoji span tags, and doing a very poor job of complex emoji. https://github.com/matrix-org/matrix-react-sdk/blob/7d0c68aa2922ba6e2d0134ab0999698323bb1f27/src/HtmlUtils.tsx#LL54C1-L57C74 seems to find emoji by regex, and in practice it seems to break things like 🏴󠁧󠁢󠁷󠁬󠁳󠁿. Room previews and the emoji picker actually do render this fine, so the flag isn't *broken* entirely, it's just the way we process it.

**Comment by t3chguy** [comment]
We can probably use lodash's `split` which has proper grapheme splitting

**Comment by Johennes** [comment]
Looks like we are already doing that (https://github.com/matrix-org/matrix-react-sdk/blob/7d0c68aa2922ba6e2d0134ab0999698323bb1f27/src/HtmlUtils.tsx#L474) but lodash itself can't properly handle that emoji.

```
for (const char of split("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "")) {
    console.log(`char: ${char}`)
    console.log(`codepoint: ${char.codePointAt(0).toString(16)}`);
}

...

char: 🏴 
codepoint: 1f3f4 
char: 󠁧 
codepoint: e0067 
char: 󠁢 
codepoint: e0062 
char: 󠁷 
codepoint: e0077 
char: 󠁬 
codepoint: e006c 
char: 󠁳 
codepoint: e0073 
char: 󠁿 
codepoint: e007f
```

Those are all the the code points in `"🏴󠁧󠁢󠁷󠁬󠁳󠁿"`, just not split correctly.

**Comment by justjanne** [comment]
Lodash just defers to the JS engine's own String#split method. This in turn has two ways of splitting, into surrogate pairs (bad) or into codepoints (which causes this specific issue).

**Comment by t3chguy** [comment]
See

<img width="1090" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/43bffb65-3b9d-47b1-b5c8-2763891ed995">

**Comment by justjanne** [comment]
Not really, String.split handles compound emoji just fine if you use /(?:)/u as separator. lodash only uses its own unicodeToArray in rare cases.

**Comment by t3chguy** [comment]
> in rare cases.

Like our case, given we don't pass `/(?:)/u` as the separator. We fall into the https://github.com/lodash/lodash/blob/master/split.js#L35-L37 `unicodeToArray` bracket in this emoji handling

**Comment by Johennes** [comment]
Looks like https://github.com/beaugunderson/emoji-aware can split 🏴󠁧󠁢󠁷󠁬󠁳󠁿 properly.

![Screenshot 2023-05-24 at 11 51 08](https://github.com/vector-im/element-web/assets/1137962/a5a7ed18-6e48-45f3-8031-b28ae352a767)

Ironically, their README claims that lodash itself should also do this.

> Note: Lodash's toArray (as of 4.0.0) and split (as of 4.9.0) functions now correctly split strings that contain emoji; so if that's all you need to do then [Lodash](https://lodash.com/) is a great fit.

**Comment by t3chguy** [comment]
@justjanne we do document the call sites saying that we're relying on lodash's grapheme handling

**Comment by t3chguy** [comment]
Went for `grapheme-splitter` instead as its already a transitive dependency 

<img width="746" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/62e9f490-b555-4779-b43d-1b19d3b59d3d">

```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "grapheme-splitter"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "grapheme-splitter@1.0.4"
info Reasons this module exists
   - "@typescript-eslint#eslint-plugin" depends on it
   - Hoisted from "@typescript-eslint#eslint-plugin#grapheme-splitter"
   - Hoisted from "eslint#grapheme-splitter"
info Disk size without dependencies: "252KB"
info Disk size with unique dependencies: "252KB"
info Disk size with transitive dependencies: "252KB"
info Number of shared dependencies: 0
✨  Done in 0.44s.

```

**Comment by Johennes** [comment]
Ah, great! 👍

**Comment by isaacschepp** [comment]
This is still happening on the server nickname field.
