### ISSUE TITLE
Disabling markdown causes formatted_body to be sent without any HTML

### ISSUE THREAD

**Issue by dreaddr** [vector-im/element-web#22198]
### Steps to reproduce

1. Disable markdown using the composer toggle on Element Web
2. Send a non markdown message to a room (For example, * This *)
3. Receive the message and check back on a mobile client (For example, Element Android)

4. Result is that they are not interpreted the same. 

#### What did you expect?

For it to work as the same as appending the /plain command to the start of the message in which the message is not interpreted as MD

#### What happened instead?

Disabling Automatic Markdown (as of version 1.10.12) in web client only disables it for other web client users and not for mobile client users. This is confusing as * This * will be treated as _This_  in the receivers' side mobile client even though it is specifically disabled on the composer of the senders' Web Client.

### Operating system

All

### Browser information

Chromium Version 100

### URL for webapp

app.element.io

### Application version

Element Web 1.10.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Disabling Automatic Markdown (as of version 1.10.12) in web client only disables it for other web client users and not for mobile client users. This is confusing as * This * will be treated as This in the receivers' side mobile client even though it is specifically disabled on the composer of the senders' Web Client.

Matrix clients should only be parsing markdown at sending, so this doesn't make much sense.

> Result is that they are not interpreted the same.

Can you show examples of this? Ideally screenshots as well as the `View Source` content of the event

Thanks

**Comment by dreaddr** [comment]
> Matrix clients should only be parsing markdown at sending, so this doesn't make much sense.

Which is exactly why this issue was made, it does not make sense. 

> Can you show examples of this? Ideally screenshots as well as the `View Source` content of the event

Sure, I've attached them below for your reference @t3chguy 

https://imgur.com/a/HtMNu0n

**Comment by t3chguy** [comment]
And how does the rendering vary between the clients with that event?

**Comment by t3chguy** [comment]
This looks like a bug with the Element Android client, there is nothing in that event which should be parsed as markdown.

**Comment by dreaddr** [comment]
> And how does the rendering vary between the clients with that event?

Can't see?

**Comment by t3chguy** [comment]
> Can't see?

Sorry I completely tunnel-visioned on the first screenshot

**Comment by dreaddr** [comment]
> This looks like a bug with the Element Android client, there is nothing in that event which should be parsed as markdown. I suggest opening an issue in https://github.com/vector-im/element-android
> 
> I will leave this issue open to track sending pointless formatted_body even though it contains no HTML.

Alright

**Comment by t3chguy** [comment]
(S-Tolerable because if Element Android wasn't wrongly parsing the formatted_body then this wouldn't have a visual impact)

**Comment by t3chguy** [comment]
@dreaddr appreciate you promptly providing additional info & screenshots, very helpful

**Comment by turt2live** [comment]
this also affects how web handles Big Emoji: https://github.com/vector-im/element-web/issues/22351

**Comment by dreaddr** [comment]
Fixed, update to latest versions to get rid of this issue https://github.com/vector-im/element-android/issues/6054
