### ISSUE TITLE
Cursor style is 'text' when hovering over clickable topic

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#22203]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/168427607-73198728-82b5-4905-a76e-36a75de9027a.png)

Related to https://github.com/matrix-org/matrix-react-sdk/pull/8517.

When hovering over a topic, I'm informed that I can click it to open the new topic dialog via a tooltip. However, my mouse pointer is in the 'text' [style](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#values), rather than the 'pointer' style.

#### What did you expect?

I would expect my cursor to change to the 'pointer' style when hovering over something that will open a dialog:

![image](https://user-images.githubusercontent.com/1342360/168427730-cd7a0abe-0762-4c57-a921-a545caeff63d.png)

#### What happened instead?

The smallest amount of UX pain ever experienced.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022051401, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/?K=element-desktop-nightly-bin

### Will you send logs?

No

**Comment by robintown** [comment]
The designs in https://github.com/vector-im/element-web/issues/9623 have this, so I'll put 'good first issue' on here since this seems to be a no-brainer
