### ISSUE TITLE
Element truncates all numbers except the last two on beginning of a message

### ISSUE THREAD

**Issue by Brice187** [vector-im/element-web#22216]
### Steps to reproduce

Start chat message with any number between 3 and 9 digits ending with a dot.

The visible message only contains the last two digits and the dot. If you try to edit the last message, the correct number is shown.

#### What did you expect?
`12.`-> `12.`
`123.`-> `123.`
`12345678.` -> `12345678.`
`1234567899.` -> `1234567899.`

#### What happened instead?
`12.`-> `12.`
`123.`-> `23.`
`12345678.` -> `78.`
`1234567899.` -> `1234567899.`

### Operating system

Linux Mint uma

### Application version

Element: 1.10.11,  Olm: 3.2.8

### How did you install the app?

apt

### Homeserver

local (synapse:v1.54.0)

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14621
