### ISSUE TITLE
Update highlight.js usage in-code

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22233]
from the console:

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

**Comment by SAGARGAUD01** [comment]
Hello,
 I have fixed this issue dear admin.

**Comment by dbkr** [comment]
The above PR will fix this issue once merged: we don't need any more PRs for it.

**Comment by Amit-Morade** [comment]
Is this issue still open?

**Comment by weeman1337** [comment]
> Is this issue still open?

Yes. But there already is also a pull request for it https://github.com/matrix-org/matrix-react-sdk/pull/9989

**Comment by BamaCharanChhandogi** [comment]
hey i take up this issue.

**Comment by weeman1337** [comment]
> hey i take up this issue.

This issue has already been solved.
