### ISSUE TITLE
Invite dialog to a group chat can sometimes include duplicate user records

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22232]
### Steps to reproduce

Unclear. See screenshot.

#### What did you expect?

1 of each user

#### What happened instead?

2 of one user (the searched one).

![image](https://user-images.githubusercontent.com/1190097/168693280-3995f4a9-8e64-460c-bc48-09350de2c82a.png)

### Will you send logs?

No

**Comment by robintown** [comment]
Next time you see this, it would be good to know whether the results are duplicated by Synapse or the client

**Comment by turt2live** [comment]
I believe one was from Synapse and the other from the client, from memory.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11028
