### ISSUE TITLE
Room ID are not linkified

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#22238]
### Steps to reproduce

1. Send a message containing a room ID `!roomId:homeserver.tld`

#### What did you expect?

For the room ID to be linkified and clickable

#### What happened instead?

<img width="602" alt="Screen Shot 2022-05-17 at 08 42 01" src="https://user-images.githubusercontent.com/769871/168757152-2d08b540-ed44-4852-86d7-5b8084c86345.png">

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/5150
