### ISSUE TITLE
Edit UI in threads and narrow right panel looks broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22231]
### Steps to reproduce

1. Send message
2. Send another message to form a thread
3. Start editing a message in that thread

#### What did you expect?

A sensible-looking edit UI. Not entirely sure tbh.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/168688045-534e32ce-ca61-4ebb-b301-93845e86408d.png)

### Operating system

Windows 10

### Browser information

Edge

### URL for webapp

local build of develop.element.io

### Will you send logs?

No

**Comment by luixxiul** [comment]
This is also reproduced on the main timeline with the room info panel opened.

![Untitled](https://user-images.githubusercontent.com/3362943/168782717-eb6a7b07-96b0-4f18-bc91-fa37d89d1b50.png)

The padding of the buttons with fixed pixel value should be replaced with something responsive.
