### ISSUE TITLE
Dialog to select which space to allow room acces for doesn't contain my spaces

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#22237]
### Steps to reproduce

I wanted to set room access to members of a space I am in. I upgraded the room from v6 to v9, as instructed by the room access settings, and after the upgrade, select the option "space members".

#### What did you expect?

The spaces I am in to appear in the dialog

#### What happened instead?

![image](https://user-images.githubusercontent.com/274386/168754332-7abe4543-8f82-4981-ad28-7087672149c0.png)

### Operating system

Linux 

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The dialog shows the spaces you are in which contain the given room, given it makes no sense to set the room to be joinable for members of a space which doesn't contain the room, this is as designed.
