### ISSUE TITLE
Word submatch should not trigger loud notification

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#22257]
### Steps to reproduce

1. My display name is set as `Germain`
2. I received the following in a room I am a member of

<img width="534" alt="Screen Shot 2022-05-18 at 08 19 25" src="https://user-images.githubusercontent.com/769871/168980639-27acb5a9-bfc6-4e4e-ace4-d8ddfbe99e4e.png">

#### What did you expect?

To get a normal level notification as this is not a perfect match of my display name

#### What happened instead?

Got a loud/highlight notification

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a spec issue

Related https://github.com/matrix-org/matrix-spec/issues/16 https://github.com/matrix-org/matrix-spec/issues/680 https://github.com/matrix-org/matrix-spec/issues/353
