### ISSUE TITLE
Migrate to the Fetch API

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#22265]
#### What would you like to do?

We currently use [browser-request](https://www.npmjs.com/package/browser-request) for XHR requests. We should use instead [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) which has been available natively for many years.

#### Why would you like to do it?

1. We won't be depending on an unmaintained library
2. We think this will allow us to upload files without loading them into memory, as [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects can be passed as a Blob in the [`body` option of a `Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) rather than having to load blob data into a buffer as is currently done
3. We could use the [`priority` option](https://developer.mozilla.org/en-US/docs/Web/API/Request/priority) to make some requests more important than others

#### How would you like to achieve it?

With great boldness and courage

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-js-sdk/issues/801
