### ISSUE TITLE
Fonts are blurred and difficult to read

### ISSUE THREAD

**Issue by blueglyph** [vector-im/element-web#22267]
### Steps to reproduce

Launch the application

### Outcome

As soon as the application is launched, any text is blurred. This does not depend on the theme.

### Operating system

Windows 10 Home, 64-bit

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by novocaine** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/15594
