### ISSUE TITLE
UI support for forbidden redactions of reactions 

### ISSUE THREAD

**Issue by v411e** [vector-im/element-web#22262]
#### What would you like to do?
We have a room where m.room.redaction is set to 100. Standard users may therefore not redact their own messages and reactions. 
The message part is implemented well - the button for deleting a message is not shown. But the reaction part is not implemented.
Just clicking a second time on a reaction sent by me gives me this error:
![image](https://user-images.githubusercontent.com/8049779/169019475-0d682e12-5c04-496f-8850-8185f4e992ce.png)

#### Why would you like to do it?
Because it is possible in matrix spec.

#### How would you like to achieve it?
Just make the reactions on a message not clickable when the user does not have the right to redact them. Maybe show a small hint, that this is not possible due to missing permissions.

### Have you considered any alternatives?

Leaving it as it is now. This would cause user confusion.

**Comment by v411e** [comment]
Thank you! :)

**Comment by SimonBrandner** [comment]
> Thank you! :)

No problem : )
