### ISSUE TITLE
Thread summary shows non-existing messages

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#22274]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I have threads turned on
2. What do you click?
 -I click the "Reply in thread" icon on someone else's message (i.e. start a thread)
3. More steps…
 -Thread summary immediately shows 1 reply, even though I haven't sent anything yet
 -If i send my reply, thread summary shows 2 replies

![image](https://user-images.githubusercontent.com/18530109/169143384-7d2c720e-b4a2-4d07-9f17-b316f8cdf739.png)

 

#### What did you expect?
I expected the thread summary to appear only after I've sent the first message and also to show correct number of replies.
#### What happened instead?
Thread summary with 1 reply appears before the first threaded message is sent and shows 2 replies when there is 1.

### Operating system

Windows 11 Home 21H2

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment]
Fixed on develop by https://github.com/matrix-org/matrix-js-sdk/pull/2369
