### ISSUE TITLE
Right-click context menu doesn't appear on images

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#22278]
### Steps to reproduce

1. Where are you starting? What can you see?
 -There's a message containing an image
2. What do you click?
 -I right-click on that message tile (not the image itself)
3. More steps…
 -Default browser right-click context menu appears

![image](https://user-images.githubusercontent.com/18530109/169278774-5d92e57c-702c-4eac-8391-3a27366ff087.png)

#### What did you expect?
When clicking on an image itself, I'd expect the browser context menu to appear as I might want to copy/inspect the image etc. However, when I click on the image tile (the surrounding container) I'd expect the custom context menu to appear, offering me the same options as if I've clicked on the three dots on the right.
#### What happened instead?
Default browser context menu appeared.

### Operating system

Windows 11 Home 21H2

### Browser information

Firefox 100.0 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: d36dcd276602-react-82169ab92354-js-2dccefb33a9d Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This is a manifestation of https://github.com/vector-im/element-web/issues/22282 therefore I am going to close this issue and follow up with design there
