### ISSUE TITLE
Background color on hover cannot be trigged on chat panel and thread panel in bubble message layout

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22273]
### Steps to reproduce

1. Enable bubble message layout
2. Enable the right panel (chat panel or thread panel)
3. Send a massage
4. Hover over the message

#### What did you expect?

The background color should be enabled.

![after1](https://user-images.githubusercontent.com/3362943/169131655-c690b299-774a-4082-8855-9ad1e3bd8715.png)

#### What happened instead?

The background color is not enabled.

![before1](https://user-images.githubusercontent.com/3362943/169131732-b7645e92-f4f8-47f2-a6a0-11e6c547061b.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

e87bda9f37f2c4a57b3e115162bd1e94f66c6453

### Will you send logs?

No

**Comment by novocaine** [comment]
@amshakal can you validate whether this looks correct?

**Comment by luixxiul** [comment]
Please note that the background color was temporarily changed in order to set a clear contrast.
