### ISSUE TITLE
Right-clicking on message toolbar triggers both menus

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#22279]
### Steps to reproduce

1. Where are you starting? What can you see?
 -I have right-click context menu turned on in Labs
2. What do you click?
 -I hover a message and right-click on Options
3. More steps…
 -Both the right-click context menu and Options menu appear

![image](https://user-images.githubusercontent.com/18530109/169279385-98d5bdc5-79f6-496a-a545-1aabecaa7f44.png)

Same thing happens with reactions

#### What did you expect?
Personally, I'd expect nothing to happen here. We might need some community/design feedback on this.
#### What happened instead?
Multiple menus appear.

### Operating system

Windows 11 Home 21H2

### Browser information

Firefox 100.0 (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Element version: d36dcd276602-react-82169ab92354-js-2dccefb33a9d Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
@SimonBrandner Still happening in the Netlify build:

![Screenshot from 2022-08-17 12-07-02](https://user-images.githubusercontent.com/51663/185104467-907b79a8-d9d6-440d-a143-bc0a06a8db92.png)
