### ISSUE TITLE
A thought about screenshot testing

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22288]
Screenshot testing is expensive to maintain because it costs real money to store a reasonable number of screenshots. Currently the approach is to re-run the CI roughly on every commit which leads to a ton of builds: ~70 PRs per week with 5-20 commits each is approximately 840 builds on average. If we then consider we want 4 browsers at 2 resolutions each tested, that's potentially 6720 screenshots *a week*, dangerously close to our 25k screenshots *per month* limit.

For the average case we'd be at 93% of our quota, but we can't assume average is normal. Looking at the worst case, we'd be at 179% of our quota. Obviously, that's not going to work out.

To try and avoid throwing too much money at the problem we could implement a slightly weird workflow that solves a couple problems: instead of running the percy screenshot tests on *every* commit, we wait until the PR has been code review approved. Once approved, a GHA comment could be left on the PR to the effect of:
> Congrats on your PR approval! To fully test that this is production-ready, please update to incorporate the latest changes from develop or have a team member stop by to say `!percy go` - this will run our screenshot tests to verify nothing has unexpectedly changed.

As the comment implies, the CI will monitor for merge commits or the `!percy go` command and then run the screenshot tests *once*. We don't run it on every commit after this point to ensure we don't over-use the quota (and honestly there's a good chance that code changes after merge will need to be re-reviewed anyways).

This ends up solving two problems:
1. We don't get anywhere near our screenshot quota
2. PRs are encouraged to update to the latest develop *before* merge, reducing risk of changes breaking things

However, it also introduces a new downside:
1. Developers won't know if they broke the screenshot tests without running them locally (can they even run them locally?).
    * A potential fix is we allow the `!percy go` command or possibly a manual GHA for team members and trusted contributors to use throughout the PR process. 

An alternative would be to only run a single browser and single resolution on PRs and a weekly/nightly job to more widely test everything, however failures would be delayed (potentially to the point where the blamed author has lost context) and we'd still be quite close to the quota by building 1 screenshot per commit.

----

This issue serves as a discussion for this workflow.

**Comment by turt2live** [comment]
I've been informed that the math here is flawed: it's more or less based on snapshots (where the number of snapshots will go up over time) multiplied by 4 browsers of 2 screenshots each, or roughly 40 screenshots per commit (~33k screenshots per week)

**Comment by t3chguy** [comment]
> An alternative would be to only run a single browser

Browser selection is project-wide

![image](https://user-images.githubusercontent.com/2403652/169423854-75a07f6d-f546-437b-9bff-9c4393f7ac72.png)
