### ISSUE TITLE
Temporarily mute a channel with an active discussion for X minutes or hours

### ISSUE THREAD

**Issue by raphj** [vector-im/element-web#22289]
#### What would you like to do?

I would like to be able to temporary mute a channel for a few minutes. 

#### Why would you like to do it?

I usually want to see all the notification messages from all the channels I'm in. The traffic is quite low overall. However, it happens that some channel has an ongoing active discussion that I'm not particularly interested in and that produces a lot of notifications. It'd be nice to temporarily ignore this channel until the ongoing discussion settles down to avoid missing focus on my current task or missing more important notifications.

#### How would you like to achieve it?

Clicking on a menu item "Disable notification for some time", with sub items like "10 minutes", "30 minutes", "1 hour", "2 hours" in the contextual menu of a channel.

### Have you considered any alternatives?

I considered manually disabling notifications for the channel and thinking of re-enabling them when later, but I risk forgetting to re-enable them.

**Comment by t3chguy** [comment]
I think this would need to be a https://github.com/matrix-org/matrix-spec issue otherwise if you turn off your client during the `X minutes or hours` period then the time will never lapse and notifications will continue to not arrive.

**Comment by raphj** [comment]
I don't think so, the "disable for X minute" would actually do "disable, and renable after time T", so would be fine. I really see it as a purely client-side feature. The notification I'm talking about it the Web Notification that is shown by the OS, I still want the messages to go through. Though I'm not familiar with the Matrix protocol and I don't know how those notification settings are handled, including how they are shared between clients.

**Comment by t3chguy** [comment]
Notifications are handled by both clients & servers, via the push rules APIs. If your client disables then goes offline (Element runs entirely on your device) then the push rule will remain disabled until the client comes back online.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/1075 
& https://github.com/matrix-org/matrix-spec-proposals/pull/3767

**Comment by piegamesde** [comment]
Note: https://github.com/matrix-org/matrix-spec-proposals/pull/3767 does not address this issue: https://github.com/matrix-org/matrix-spec-proposals/pull/3767#discussion_r1239745213
