### ISSUE TITLE
No error message when getting disconnected from Jitsi

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22284]
### Steps to reproduce

1. Be in a video room with someone else
2. Find myself in the lobby without any errors or explanations

#### What did you expect?
I stay in the call until I leave

#### What happened instead?
Got kicked out of the call somehow

### Browser information

Chromium 101.0.4951.64 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: b2d057b-react-efc36acf9334-js-81d884f899eb Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by robintown** [comment]
This happens whenever Jitsi encounters a fatal error, such as losing internet connection
