### ISSUE TITLE
`Can't load this message (m.room.message)` on switching rooms

### ISSUE THREAD

**Issue by DMRobertson** [vector-im/element-web#22281]
### Steps to reproduce

I navigated from one room to another. (Internal to Element-the-organisation.)

#### What did you expect?

Messages timeline to load without an error.

#### What happened instead?
I saw some of the room's timeline, but at the bottom:

![image](https://user-images.githubusercontent.com/8614563/169301330-4f018c6b-6c9a-450c-b05c-846214a4ac1a.png)

This persisted even as newer messages arrived.

### Operating system

Fedora 36

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
I saw one of these today as well.

**Comment by t3chguy** [comment]
`2022-05-19T13:09:14.830Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)` doesn't look like it, but the logs don't really contain anything helpful

**Comment by turt2live** [comment]
this is also concerning:
```
2022-05-19T13:09:23.373Z W Event type not supported: type:m.room.encrypted isState:false
```

The `removeChild` could be a false-positive, but is also not fun to see in the logs. 

Did it eventually fix itself eventually? From the logs it looks like the keys might have been missing at the time, so the event could have gone through the render pipeline as an unexpected event type.

**Comment by DMRobertson** [comment]
> Did it eventually fix itself eventually?

I think so. I scrolled back in that room and didn't see the error message. Double checking just now I can't see it either.

**Comment by turt2live** [comment]
I'm even more inclined to blame this on a temporary decryption fail then. Unclear what would have caused that specifically.

**Comment by turt2live** [comment]
Presuming fixed or otherwise not an issue. If this happens again, please open a new issue with new information.
