### ISSUE TITLE
Analytics: CreatedRoom 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22299]
#### What would you like to do?
Add the CreatedRoom event on Web analytics

#### Why would you like to do it?
So that we can see how many users create a room and whether they're DMs or Rooms

#### How would you like to achieve it?
Add CreatedRoom like here: https://matrix-org.github.io/matrix-analytics-events/

**Comment by daniellekirkwood** [comment]
I thought we already had this but when I look at the event in PostHog its blank.

**Comment by t3chguy** [comment]
Web has `ViewRoom` + trigger=Created and isDM exists just the same, CreatedRoom seems a bit superfluous?

**Comment by daniellekirkwood** [comment]
It seems weird to be handled differently across platforms - why would we not have it? (Especially for people checking the events list, expecting it to be there...)

**Comment by t3chguy** [comment]
Because `CreatedRoom` is already falling out of sync with the parameters that ViewRoom + trigger=Created can afford you, e.g `viaKeyboard`, `isSpace`, `activeSpace`

**Comment by daniellekirkwood** [comment]
Then shouldn't we make that the case with Android and remove the CreatedRoom trigger altogether?

**Comment by daniellekirkwood** [comment]
i misspoke - the CreatedRoom event. 

We should either have the CreatedRoom event on all platforms or we should use ViewRoom with trigger == Create on all platforms.

**Comment by daniellekirkwood** [comment]
Removing @justjanne  until we get an answer to this from the Analytics team

**Comment by germain-gg** [comment]
Delight team is no more... closing as not doing.
