### ISSUE TITLE
"Show All" link button on ReactionsRow should be styled properly

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22300]
### Steps to reproduce

1. Send a message
2. Add reactions to display `Show All` link button

#### What did you expect?

The link button should be styled as implemented on https://github.com/matrix-org/matrix-react-sdk/pull/6027

#### What happened instead?

The default link declarations are applied to the link button.

![before](https://user-images.githubusercontent.com/3362943/169588856-836ffdcd-a780-4bf0-86c0-5f91d07ffac2.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I think I actually prefer the green one, @vector-im/design, what do you think off this?

**Comment by luixxiul** [comment]
It can be easily realized by removing this line: https://github.com/matrix-org/matrix-react-sdk/pull/8658/files#diff-9b841ae6013a222403aff59b3ae7d1c76c11a381b24a749607bfeff22dc07c8dR65.

The main issue here is that current implementation does not respect declarations of `.mx_ReactionsRow_showAll` block and all of them except the margin declaration are not effective.

**Comment by SimonBrandner** [comment]
> It could be easily realized by removing this line: [matrix-org/matrix-react-sdk#8658 (files)](https://github.com/matrix-org/matrix-react-sdk/pull/8658/files#diff-9b841ae6013a222403aff59b3ae7d1c76c11a381b24a749607bfeff22dc07c8dR65).
> 
> The main issue here is that current implementation does not respect declarations of `.mx_ReactionsRow_showAll` block and all of them except the margin declaration are not effective.

Could we split this into two things - the color and the rest?

**Comment by luixxiul** [comment]
Since #8658 does not change the current color value, it is possible to do so by moving the color declaration for link color directly under `mx_ReactionsRow_showAll`, though I am sure it is not a great way as it has the color property overridden on purpose :sweat_smile:
