### ISSUE TITLE
 CORS request rejected: https://xxx_matrix/client/r0/search

### ISSUE THREAD

**Issue by starsareintherose** [vector-im/element-web#22317]
### Steps to reproduce

1. Where are you starting? What can you see? login the element self host web
2. What do you click? search message history

#### What did you expect?
can search information
#### What happened instead?
When search
```
request failed: CORS request rejected: https://xxx_matrix/client/r0/search
````

### Operating system

Arch Linux

### Browser information

Chromium 101.0.4951.64

### URL for webapp

1.10.12

### Application version

1.10.12

### Homeserver

Dendrite 0.8.5

### Will you send logs?

No

**Comment by t3chguy** [comment]
This will be your server hitting a timeout, I suggest increasing the timeout limits on your Synapse and/or reverse proxy.

**Comment by t3chguy** [comment]
For future support queries I suggest https://matrix.to/#/#element-web:matrix.org - you should also look at the network inspector of your browser to see the underlying error, sometimes helps figure out how your server is going wrong.
