### ISSUE TITLE
PiP 1:1 microphone and camera buttons lose their symbol

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22316]
### Steps to reproduce

1. be in a 1:1 video call
2. switch to another room
3. call goes PiP

#### What did you expect?
![image](https://user-images.githubusercontent.com/2803622/169878554-74f724ed-409c-4d16-b57d-0a578ba68b42.png)

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/169878480-f5d28547-0c82-4e3e-93a1-cf35de909725.png)

### Operating system

arch

### Application version

Element Nightly version: 2022052102 Olm version: 3.2.8

### How did you install the app?

aur

### Homeserver

1.59.1

### Will you send logs?

No

**Comment by dbkr** [comment]
I can repro this reliably so I'm going to bump it to frequent
