### ISSUE TITLE
Problem with in-app search

### ISSUE THREAD

**Issue by NataliaShpakVictory** [vector-im/element-web#22320]
### Steps to reproduce

I click "Allow" message search and the wheel spins endlessly. After that, nothing happens.
I've restarted the app and logout, but to no avail.
Sometimes in the desktop app I see "Use the desktop app to search".

### Outcome

I hope the problem is solved.

### Operating system

Windows 

### Application version

Версия Element: 1.10.12 Версия Olm: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

https://chat.syneforge.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
No you do not need to remake the issue, just send logs again please.

**Comment by NataliaShpakVictory** [comment]
I need instructions on how to do this

**Comment by t3chguy** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/2403652/169983689-3dcf67fe-cef6-45c3-941c-ead87d9954a7.png">

**Comment by NataliaShpakVictory** [comment]
sorry, not sure if i can provide this information

**Comment by turt2live** [comment]
Closing this issue for now. If you continue to experience this, please open a new issue and submit logs using the instructions above.
