### ISSUE TITLE
Text cursor skipping a line when removing a line of text

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#22335]
### Steps to reproduce

Apologies for the issue name, but this is something that's best explained by video:

https://user-images.githubusercontent.com/1342360/170228358-e98200c2-1627-48bd-9c0a-3d923274bce2.mp4

The steps to reproduce are:

- Write some text into the message composer window.
- Use Shift-Enter at the beginning of the text to add an extra two newlines.
- Move your cursor up two lines and enter a character or two.
- Use the backspace key to delete those characters you've just entered.
- After deleting the last character, you'd expect the cursor to move back to where that character initially was.
- Instead, the cursor jumps down a line.

### Outcome

The text cursor jumps around in certain cases. This can be especially confusing for accessibility.

Potentially related, although that issue was determined to only occur in Firefox: https://github.com/vector-im/element-web/issues/17969

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022051801, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by anoadragon453** [comment]
This is still reproducible on Element Web 1.11.30.

**Comment by Johennes** [comment]
The root issue appears to be that we compute the wrong line in [`findNodeInLineForPart`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/editor/caret.ts#L123). It ends up with line index 1 when it should be 0. I believe this is because in this edge case the very first part is a newline itself and so we increment over it in the loop even though this is our destination.

I'm not seeing the line jump anymore with this patch but haven't yet tested this deeper.

```
diff --git a/src/editor/caret.ts b/src/editor/caret.ts
index 61c6a85640..67daca84ea 100644
--- a/src/editor/caret.ts
+++ b/src/editor/caret.ts
@@ -129,7 +129,7 @@ function findNodeInLineForPart(parts: Part[], partIndex: number): { lineIndex: n
     // to find newline parts
     for (let i = 0; i <= partIndex; ++i) {
         const part = parts[i];
-        if (part.type === Type.Newline) {
+        if (part.type === Type.Newline && i < partIndex) {
             lineIndex += 1;
             nodeIndex = -1;
             prevPart = undefined;
```
