### ISSUE TITLE
Element Web using unstable endpoint for local aliases

### ISSUE THREAD

**Issue by neilalexander** [vector-im/element-web#22337]
### Steps to reproduce

Open the "Settings" page for a room when connected to a Dendrite server and no local aliases are displayed, even if they exist.

Seems to be the cause of matrix-org/dendrite#2486.

#### What did you expect?

We should use the specced `/_matrix/client/v3/rooms/{roomID}/aliases` endpoint and not gate on unstable features.

#### What happened instead?

Element Web seems to be using unstable `/_matrix/client/unstable/org.matrix.msc2432/rooms/{roomID}/aliases` to look up local aliases for a room. Additionally, it seems to only look up local aliases for the room if `org.matrix.msc2432` appears in the `unstable_features`.

### Operating system

All

### Browser information

All

### URL for webapp

app.element.io

### Application version

1.10.13

### Homeserver

dendrite.matrix.org

### Will you send logs?

No

**Comment by spaetz** [comment]
For the record, I was using Element Web v1.10.12 trying this with no lab features enabled.
