### ISSUE TITLE
Move Current Avatar labs flag to prefrences

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-web#22336]
#### What would you like to do?
Move the labs flag `Show current avatar and name for users in message history` to preferences.

#### Why would you like to do it?
Product has decided it's important enough to keep this as a preference for the user but there is not enough data/research at this point to determine if the default behaviour should change.

#### How would you like to achieve it?
1. Make changes to move the labs flag to `Settings -> Preferences -> Timeline`
2. Add additional tests or other required finishing items we normally apply as a part of de-labs-ing process.

**Comment by turt2live** [comment]
Product has already signed off on this elsewhere.
