### ISSUE TITLE
BROKEN app after clicking the Pop-up to UPDATE app. "Connectivity to the server has been lost."

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-web#22330]
### Steps to reproduce

1. Where are you starting? What can you see?
Connectivity to the server has been lost. 
Started right after clicked pop-up to UPDATE app.
Currently it says:
Element version: 1.10.13
Olm version: 3.2.8

3. What do you click?
Messages Fail to send with red circle with exclamation mark, and message displayed in red:
"Connectivity to the server has been lost."

#### What did you expect?
To have it work as it did before the update, preferably BETTER because I clicked on UPDATE because already it was buggy in some ways, like I click on voice or video call in a DM direct-message 2 person chat and nothing would happen. Seems like it may have been that only one participant was Admin and only admin could initiate, but no helpful errors were given, just nothing happened on clicking voice call or video.
#### What happened instead?
But before update at least messaging was working fine. After clicking update, nothing works.

### Operating system

Windows 10

### Will you send logs?

Yes

**Comment by jittygitty** [comment]
I discovered the issue, it seems like the "background update" employed by Element Desktop does not play well with Software Firewalls and so upon re-installation it did not initiate re-quest to re-authorize network access.

**Comment by t3chguy** [comment]
> it did not initiate re-quest to re-authorize network access

Software doesn't "request" network access, it just makes a request and firewalls can choose to allow, block, or ask. In your case it seems like the firewall defaulted to block.

Related https://github.com/vector-im/element-web/issues/14788

**Comment by dbkr** [comment]
I think the related bug covers everything here, so I'm going to close this one in favour of https://github.com/vector-im/element-web/issues/14788.
