### ISSUE TITLE
Sometimes the linkifier doesn't kick in for valid emails

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22344]
### Steps to reproduce

1. Spam a bunch of emails
2. Note that some of them didn't autolink

#### What did you expect?

For the email addresses to be consistently linked

#### What happened instead?
![image](https://user-images.githubusercontent.com/1190097/170304384-727fc295-4d34-4184-9fcb-ec3ae186b1ef.png)

### Operating system

Windows 10

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Looks like updating Linkify fixed this

<img width="313" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/e7d8aa48-1a54-4532-b51a-8b609ce432e1">

The last 2 are the expected failure cases
