### ISSUE TITLE
Add an option to pin messages

### ISSUE THREAD

**Issue by alexmehandzhiyska** [vector-im/element-web#22340]
#### What would you like to do?
I would like to have the option to pin messages/threads.

#### Why would you like to do it?
Because it provides the users with the opportunity to pin the most important messages in a chat, as well as some threads that they frequently use.

#### How would you like to achieve it?
With a "Pin message/thread" option when I hover over a message/thread.

**Comment by t3chguy** [comment]
Already available in Labs

<img width="297" alt="image" src="https://user-images.githubusercontent.com/2403652/170266584-6c39371c-f585-4ecb-b10f-fd21acd44475.png">

You can try it at develop.element.io

**Comment by samantarya** [comment]
Can this feature be moved to the stable version now?

**Comment by t3chguy** [comment]
@samantarya it is blocked on mobile support.
