### ISSUE TITLE
Window size is not remembered correctly

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#22347]
### Steps to reproduce

1. Start Element
2. Exit Element
3. Start Element

#### What did you expect?
Upon starting Element, window size is set to exactly how it was when I exited.

#### What happened instead?
Window size is set to exactly half the width, and half the height, compared to how it was before I exited.

### Operating system

Windows 10 21H2

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20940 - your own issue
