### ISSUE TITLE
BigEmoji doesn't work when Markdown is disabled on the sender's side

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22351]
### Steps to reproduce

1. Disable markdown
2. Send an emoji
3. Note that it's not a big emoji

#### What did you expect?

The emoji should be a large one.

#### What happened instead?

It appears as though when markdown is disabled the message gets sent as text+HTML, despite there being no HTML component, which is probably causing the big emoji parser to not run (if it was sending just text then it'd probably work).

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of the underlying cause https://github.com/vector-im/element-web/issues/22198
