### ISSUE TITLE
Unable to connect to homeserver, retrying... - Lost access to homeserver on mobile, web, and desktop apps after logout

### ISSUE THREAD

**Issue by johndball** [vector-im/element-web#22357]
### Steps to reproduce

1. This behavior has started recently after a user logs out of a client on a self-run homeserver. This issue is on the Element Windows desktop app 1.10.13 and app.element.io on the web.
2. I logged out and am unable to log back in. On my mobile device, I am prompted with a "verify session" prompt, but the client never loads on desktop or web.
3. I opened developer view on the web and I can see "Number of consecutive failed sync requests: 36" and other issues related to syncing. 
4. UPDATE - After posting this I tried clearing cache on my mobile Element and second desktop. I've now lost access to my homserver on mobile as well. iOS 15.x. I've effectively lost all front-end/user access to both homeservers now and can no longer interact with any users on either server at this point. 

This behavior mimics the issue on https://github.com/vector-im/element-web/issues/12694 but I did not want to revive a 2 year old thread.
![Capture2](https://user-images.githubusercontent.com/4836923/170383092-748985de-8ce8-4101-a56b-59741126b785.PNG)
![Capture](https://user-images.githubusercontent.com/4836923/170383096-e24a58fc-6610-4f8d-84fa-f78285277618.PNG)

#### What did you expect?
A log out and log back in should work after successful authentication.

#### What happened instead?
Client just spins and no login occurs.

### Operating system

Windows 

### Application version

1. 10.13

### How did you install the app?

https://element.io/get-started#download

### Homeserver

Self-hosted, both on Ubuntu 20.04 LTS, Apache2, Matrix 1.59.1

### Will you send logs?

Yes

**Comment by johndball** [comment]
After trying multiple "things", I ended up rolling back to Matrix Synapse 1.57.0 from 1.59.1 and my clients (web, mobile, desktop) instantly signed in.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/12820

> I can see in developer tools that there is a never ending /sync job. This is the issue I opened in Element
