### ISSUE TITLE
escape close the wrong panel

### ISSUE THREAD

**Issue by Hugueprime** [vector-im/element-web#22354]
### Steps to reproduce

1. Click a message to reply
2. Open emoji panel and select one or multiple emoji(s)
3. Press escape

#### What did you expect?
The emoji panel to close

#### What happened instead?
The message went back to a normal message without the reply

### Operating system

Windows

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

custom

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/22191
