### ISSUE TITLE
Support specifying which Electron app to render

### ISSUE THREAD

**Issue by Torxed** [vector-im/element-web#22362]
### Steps to reproduce

Install and run the desktop client.

### Outcome

CORS is a PITA with the desktop app, and most of the guides will tell you to set `*` for `Access-Control-Allow-Origin` to get around the symptoms that people experience which is not at all what I would recommend.

And I don't agree with arguments such as https://github.com/vector-im/element-web/issues/20227#issuecomment-996723651 because it is partially Elements causing these issues through documentation and odd requests to the server.

The fact that I cannot force which servers to talk to in the electron desktop client is an issue. I don't like other domains, and the whole point of riot/element/vector is that it's supposed to be self-hosted and that you should be able to own all aspects of the communication. So why is it communicating with *(rhetorical question, I understand why but this should not be happening):
 * matrix.org
 * matrix-client.matrix.org
 * vector.im

Along side this, the desktop client sends a bogus `vector://vector` origin to the chosen server, which is only supposed to be a local schema to override loading of external URL's and not something that is really a URL that I'd want to accept on the server side.

So either make it clear that the desktop app is not self-hosted only or make it so that it doesn't request these external domains until you attempt to login, in which case the user has chosen to supply a domain to login against.
And at the very least, make the `Origin` reflect correctly which host is actually being retrieved.

*Sidenote: this statement of changing name to Element should probably be done across the board, when things are called riot or vector or element is a tad bit confusing.. Not really something I care about but it is confusing at times.*

### Operating system

flatpak

### Application version

latest

### How did you install the app?

flatpak install im.riot.Riot

### Homeserver

any

### Will you send logs?

No

**Comment by t3chguy** [comment]
> because it is partially Elements causing these issues through documentation and odd requests to the server.

Care to elaborate?

> The fact that I cannot force which servers to talk to in the electron desktop client is an issue. I don't like other domains, and the whole point of riot/element/vector is that it's supposed to be self-hosted and that you should be able to own all aspects of the communication. 

Yes you can, via [config.json](https://github.com/vector-im/element-web/blob/develop/docs/config.md) you can replace all of those domains. 

> So why is it communicating with *(rhetorical question, I understand why but this should not be happening):
> matrix.org
matrix-client.matrix.org
vector.im

This is https://github.com/vector-im/element-web/issues/11154 / https://github.com/vector-im/element-web/issues/11655

> So either make it clear that the desktop app is not self-hosted only or make it so that it doesn't request these external domains until you attempt to login, in which case the user has chosen to supply a domain to login against.

I am struggling to see how this relates to the issue title `Support specifying which Electron app to render` but if the above summary is your issue then it sounds like https://github.com/vector-im/element-web/issues/11655

The title verbatim sounds more like https://github.com/vector-im/element-web/issues/8299#issuecomment-520517475 though
