### ISSUE TITLE
Blockquotes should only be rendered with messages that begin with `>{space}`

### ISSUE THREAD

**Issue by sudoforge** [vector-im/element-web#22368]
### Steps to reproduce

1. Be in a direct message room with another user
2. Ensure that Markdown rendering is enabled
3. Type a message beginning with the oldschool facepalm ascii emoji: `>_< this is just a test`
4. See that Element Web renders a blockquote with the contents `_< this is just a test`

#### What did you expect?

I expected the message to be rendered as plaintext, without a blockquote:

```
>_< so much for blocked time on my calendar
```

#### What happened instead?

The message was rendered with a blockquote.
![20220526T135328308](https://user-images.githubusercontent.com/3893293/170579879-f0c91197-2bb8-4d16-bc66-b97a44410e89.png)

### Operating system

Arch Linux

### Browser information

Qutebrowser v2.5.0 (QTWebEngine 5.15.9, based on Chromium 87.0.4280.149)

### URL for webapp

app.element.io

### Application version

Element version: 1.10.13, Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a property of Commonmark

![image](https://user-images.githubusercontent.com/2403652/170580489-393878d1-8a14-44bc-b380-8e551a34dea6.png)

We will not be rolling our own custom Markdown dialect

Closing in favour of https://github.com/vector-im/element-meta/issues/330 as the general markdown bug

**Comment by sudoforge** [comment]
Got it, thanks for the clarification.
