### ISSUE TITLE
Space doesn't show new messages

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22364]
### Steps to reproduce

1. Receive new message
2. Look at the space
3. See new message markers only in people and home, but not in the space.

#### What did you expect?
The space has new message markers

#### What happened instead?
![Screenshot from 2022-05-26 17-06-04](https://user-images.githubusercontent.com/51663/170532218-0332c319-4e5a-4cd3-a1e5-4ebfc3483114.png)

### URL for webapp

staging.element.io

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is by design, a DM will be visible in many spaces, and it causing all your spaces to light up is anxiety-inducing. Product decided to only show DM notification badges on Home/People.
https://github.com/matrix-org/matrix-react-sdk/pull/5968 was the change for this
