### ISSUE TITLE
Configuration auth_header_logo_url (branding) not working

### ISSUE THREAD

**Issue by penguin86** [vector-im/element-web#22370]
### Steps to reproduce

To reproduce:
- install Element 1.10.12 unzipping the archive in /var/www/html (Apache2 webserver)
- copy config.json.example to config.json
- create a theme folder and add some SVG images
- edit the config.json file adding this section:
```
"branding": {
      "welcome_background_url": "theme/background.svg",
      "auth_header_logo_url": "theme/logo.svg"
   }
```
- go to the login page with browser (I'm using Firefox 100)

While the background is shown correctly, the logo isn't replaced (the default Element logo is shown). In the developer tool's network tab there are no failed requests for the logo. The only request for logo.svg is done at `/welcome/images/logo.svg`.

Maybe useful infos:
- The `https://....../config.json?cachebuster=1653633709541` request returns the correct logo image path.
- Replacing the relative urls with absolute ones (`https://.......logo.svg`) in the config doesn't solve the problem
- The images are available from the web browser at the expected url

PS: Thank you very much for this gorgeous client!!!

#### What did you expect?
The logo on login page to be replaced with the one set in the config file.
#### What happened instead?
The logo remained the default one.

### Operating system

Debian 11

### Browser information

Firefox 100

### URL for webapp

Element 1.10.12

### Application version

Element 1.10.12

### Homeserver

synapse (matrix-synapse-py3 1.59.1+bullseye1)

### Will you send logs?

No

**Comment by t3chguy** [comment]
So the reason for this is that Welcome is an external HTML page (`/welcome.html`) which is loaded in.

![image](https://user-images.githubusercontent.com/2403652/170649599-154ab03f-4ba3-4114-a4b6-11e7db60d859.png)

You can replace the entire welcome.html with your own choice of page using `embedded_pages.welcome_url` in config.json

**Comment by penguin86** [comment]
Ooooh, I see... Thank you Michael, I didn't expect the welcome page to be enabled by default, altought I must say it was well-documented. Sorry to have bothered you, and thank you a lot for the support!

Just to leave a trace to someone that may need it in the future: if you don't want to implement a custom welcome page but want to continue using the default login page, just add another section in the config file:
```
    "embedded_pages": {
        "login_for_welcome": true
    }
```
This disables the default welcome page: this way the defalt login page is shown, with the correct logo.
