### ISSUE TITLE
Unable to invite EMS user to a chat

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22375]
### Steps to reproduce

Clicked [+] in EW, copy and paste the MXID (that's an EMS account) to the dialog box, click Go

This issue:
![Screenshot 2022-05-26 at 09 06 21](https://user-images.githubusercontent.com/89144281/170713210-1b8efdd6-1b0b-40d0-8b31-a755f1211f38.png)

The user was able to invite me to a chat.

#### What did you expect?
To invite the user to a chat
#### What happened instead?
Not able to

### Operating system

MacOS

### Browser information

Safari

### URL for webapp

app.element.io

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/17269

**Comment by turt2live** [comment]
Without logs it's hard to confirm if this is a client or server issue. If people see this, please send logs against this issue for investigation.

**Comment by Half-Shot** [comment]
This is likely because one.ems.host limits profile access to users you share a room with (and since this requires authentication, it doesn't work over federation). If you've got an issue for this already, I'd close this and link to that.

**Comment by Half-Shot** [comment]
In fact, that's what @t3chguy did. I'm going to close this.
