### ISSUE TITLE
not possible to verify Android Version

### ISSUE THREAD

**Issue by sl5net** [vector-im/element-web#22387]
### Steps to reproduce

1. for weeks i enabled a other Beta-Feature at Linux Client Element. works very well
2. then i enabled this other Beta-Feature at Android Client Element. not works. it waits for server antword for days, and it still wait at the moment.
3. i disabled the beta at linux desktiop (no effect)
4. i reinstalled the andoid version  (no effect) it still waits for sever response
5. and at same time it tries verification (Desktop as for QR-Code or Emoji Verification) but Android is in deadLock. to problems at same times seems to be not possible to solve for it. so i stack with to problems. and i cant use Android Element not any more

BTW the german cumunity also now it. i long time user in this room:  #german:matrix.org

### Outcome

verification the android element version

its blocked (dedlock) because android could not handle this two problems as same time (see  description  above)

### Operating system

Ubuntu and Andoid

### Application version

Element newest Version at both devices
Desktop Version:
Element version: 1.10.13
Olm version: 3.2.8

### How did you install the app?

the Andoid is from Google Play Store

### Homeserver

tchncs.de

### Will you send logs?

Yes

**Comment by uhoreg** [comment]
Transferring to element-android

**Comment by uhoreg** [comment]
Or not.  GitHub doesn't seem to let me.  I'm closing this issue.  Please open a new issue at https://github.com/vector-im/element-android since it affects the Android version rather than the web/desktop version.

**Comment by t3chguy** [comment]
@sl5net see https://github.com/vector-im/element-web/issues/22387#issuecomment-1141293761
