### ISSUE TITLE
"Share your screen" dialog in video room stays stuck on loading animation for sources (Linux, Manjaro XFCE)

### ISSUE THREAD

**Issue by AlexFolland** [vector-im/element-web#22381]
### Steps to reproduce

1. Create or enter a video room.
    - To do this, you will first need labs flag `feature_video_rooms` to be `true` and be running Element version 1.10.9 or later.  For reference, this issue was encountered on Element 1.10.13
2. Join the video call with the join button.
3. Hover over the video panel until the control GUI appears.
4. Click the button which has tooltip "Start / Stop sharing your screen"
5. Navigate back and forth between the "Your entire screen" and "Application window" tabs, waiting at least 10 seconds on each tab.

#### Expected behavior:

- After fewer than 10 seconds of waiting, a list of screens is expected to be visible and interactive on the "Your entire screen" tab of the "Share your screen" dialog.
- After fewer than 10 seconds of waiting, a list of application windows is expected to be visible and interactive on the "Application window" tab of the "Share your screen" dialog.

#### Observed behavior:

- After more than 10 seconds of waiting, the loading animation continues playing, with no list of screens visible or interactive on the "Your entire screen" tab of the "Share your screen" dialog.
- After more than 10 seconds of waiting, the loading animation continues playing, with no list of application windows visible or interactive on the "Application window" tab of the "Share your screen" dialog.

#### Additional information:

- Running the Jitsi Widget in Chromium on the same system and sharing screen from there immediately populates the lists of screens and application windows when starting a screen-share.
- GPU: Nvidia GeForce GTX 1080 Ti
- Nvidia driver version: 515.43.04
- Display server: Xorg
- Xorg screens: 1
- Xorg server version number: 11.0
- Xorg server vendor version: 1.21.1.3

### Operating system

Manjaro XFCE, unstable branch, latest updates applied as of 2022-05-27

### Application version

1.10.13

### How did you install the app?

`community/element-desktop` package from Manjaro unstable branch

### Homeserver

matrix.org

### Will you send logs?

Yes; here: [logs.zip](https://github.com/vector-im/element-web/files/8790643/logs.zip) (PPMd compression format; used 7-Zip)

**Comment by AlexFolland** [comment]
[logs.zip](https://github.com/vector-im/element-web/files/8790643/logs.zip)

This file is compressed with PPMd in a zip container, since that was the only decent compression algorithm that github would accept for these logs I could find in my brief search.  Github does not accept xz yet, somehow.

**Comment by SimonBrandner** [comment]
It seems you're not the only one to have come across this bug, as it's been reported previously. I'm going to close this issue now so we can focus on the older issue. Please watch, vote or comment on that issue if there is any additional information you can provide.

Duplicate of https://github.com/vector-im/element-web/issues/4880

**Comment by AlexFolland** [comment]
This isn't exactly the same, and it's specific to the new video rooms.  I say this because if I add a Jitsi widget to a normal room then use the "Popout widget" button, that lets me bring the widget to a web browser which does populate the screen-sharing lists correctly.  This makes it so that I can have a call with someone starting from Element and share my screen.  The issue preventing this workaround for the new video rooms is that there's no "Popout widget" button in the new video rooms interface.  Therefore, I propose this issue be unmarked duplicate and reopened.

**Comment by t3chguy** [comment]
The plan for video rooms is to move them to Element Call as soon as it is ready so that will remedy this. Video rooms are still under active development as per the labs flag description.

**Comment by SimonBrandner** [comment]
> This isn't exactly the same, and it's specific to the new video rooms. I say this because if I add a Jitsi widget to a normal room then use the "Popout widget" button, that lets me bring the widget to a web browser which does populate the screen-sharing lists correctly. This makes it so that I can have a call with someone starting from Element and share my screen. The issue preventing this workaround for the new video rooms is that there's no "Popout widget" button in the new video rooms interface. Therefore, I propose this issue be unmarked duplicate and reopened.

If you pop the widget out, you avoid the issue as it is created by Electron - the technology that Element uses. As mentioned above - we'll move to Element Call in the future where this will no longer a be problem

**Comment by AlexFolland** [comment]
> The plan for video rooms is to move them to Element Call as soon as it is ready so that will remedy this.

Okay.  Thanks.

> Video rooms are still under active development as per the labs flag description.

That is exactly why I reported this issue, as I expect issues are expected to be reported for features which are exposed for testing.  I understand the rationale for closing it though.

---

By the way, I'm very happy that voice rooms are being added to Element, but I'm not sure about where to read about the intended design.  For example, I really hope the voice/video room joining behavior changes eventually to leave the most recent non-voice/video room selected and just add the user to an indented visible list of users inside the voice/video room, and have them join with audio only without confirmation.  This would match Discord's intuitive voice channel joining behavior.  I don't know where I could research whether that's planned, and whether I should open an issue ticket here proposing that design change, if it's not planned.  Is there a central public place where specific approved and planned feature design specifications like this are documented?

**Comment by AlexFolland** [comment]
I've tested this in Manjaro KDE Plasma Wayland now with the latest version of Element Nightly using Element Call.  It still doesn't work properly.  It shows a list of screens and windows to share, but when one is chosen, that menu closes and reopens after about a second, seemingly in an infinite loop.  It can be cancelled by quickly cancelling in that delay before reopening, but it doesn't allow screen-sharing.

**Comment by Destinyg133** [comment]
> I've tested this in Manjaro KDE Plasma Wayland now with the latest version of Element Nightly using Element Call. It still doesn't work properly. It shows a list of screens and windows to share, but when one is chosen, that menu closes and reopens after about a second, seemingly in an infinite loop. It can be cancelled by quickly cancelling in that delay before reopening, but it doesn't allow screen-sharing.

For wayland and electron you need to add flags
https://wiki.archlinux.org/title/Wayland#Electron

**Comment by AlexFolland** [comment]
> > I've tested this in Manjaro KDE Plasma Wayland now with the latest version of Element Nightly using Element Call. It still doesn't work properly. It shows a list of screens and windows to share, but when one is chosen, that menu closes and reopens after about a second, seemingly in an infinite loop. It can be cancelled by quickly cancelling in that delay before reopening, but it doesn't allow screen-sharing.
> 
> For wayland and electron you need to add flags https://wiki.archlinux.org/title/Wayland#Electron

OK, I tested screen sharing after running the program with this command line:

```
ELECTRON_OZONE_PLATFORM_HINT=wayland element-desktop-nightly --ozone-platform-hint=wayland --enable-features=WaylandWindowDecorations --enable-features=WebRTCPipeWireCapturer
```

The behavior I observed was identical to my previous test.

**Comment by BujuArena** [comment]
I've tested this again now and it almost works now.  I can see a tiny thumbnail of my screen share, but it's so small that I can't see what it's showing.  When I click the expand button, even on the screen share itself, the Element window fills the screen but leaves the screen share tiny, so I can't see it except for some dots.  For example, normal readable text just looks like a series of dots because the thumbnail is something around 230x126 in size compared to the display I'm sharing being 2560x1440.  So, looks like this just needs to be able to pop out the screen share so I can use my window manager to set it to full screen.
