### ISSUE TITLE
No membership changes visible in log after OP on IRC set the room to 'voice only'

### ISSUE THREAD

**Issue by erciccione** [vector-im/element-web#22388]
### Steps to reproduce

1. Be administrator in a room with IRC bridge (room v6)
2. An OP from IRC set the room as 'voice only'
3. See on element mobile the stream of membership changes for the users in the room (from 1 to default)

#### What did you expect?

Membership changes for all users in the room visible in the room log (compacted or verbose as in mobile)

#### What happened instead?

Nothing. No messages at all about membership changes. Note that manual membership changes for single users appear in the log as expected.

### Operating system

Fedora 34

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

Flatpak

### Homeserver

synapse 1.59.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Are you able to share the `View Source` from the missing events (via Mobile)

**Comment by erciccione** [comment]
I got a screenshot from another element user. I just checked my log from mobile and i still don't see the missing events.

**Comment by t3chguy** [comment]
Sounds like a server issue then, given it spans multiple clients

**Comment by erciccione** [comment]
Right. I have my own server. Anything i should look for?

**Comment by t3chguy** [comment]
You'd best ask Synapse support rather than an Element Web/Desktop tracker.

**Comment by erciccione** [comment]
Thanks @t3chguy. I asked on synapse's matrix room. If i don't get an answer there i'll open an issue in the repo.

**Comment by squahtx** [comment]
As @erciccione points out, there is a UX issue here:

> This is a problem. If i'm an administrator of a bridged room, i want to see changes coming from IRC that impact my matrix room. I'm in a situation when i'm not aware of the status of my own room and the fact that people (from both matrix and IRC) have no possibility to post in the room, unless i log in to IRC to manually check its status.
>
> Admins should be told somehow that users cannot post in the room. Right now, from one moment to another, users find themselves unable to post without knowing. That's bad user experience and creates a number of problems.
