### ISSUE TITLE
Removing the colon appended to user mentions

### ISSUE THREAD

**Issue by r00ster91** [vector-im/element-web#22383]
### Your use case

I would like to remove the colon appended when autocompleting a user mention at the start of a message:
![image](https://user-images.githubusercontent.com/35064754/170824877-78db762d-0d98-4a2a-b6f3-fd6f128c51d9.png)
This colon is only appended if the cursor is at position 0. I don't think it adds any special value and I think it's just an unnecessary extra for no reason.
A mention simply works by writing the name and then using the autocompletion to make the client make it into
`<a href='https://matrix.to/#/matrix_id'>username</a>`. The colon is not part of it at all.
The client only highlights the actual part of the mention (`<a>x</a>`) and ignores the colon. The colon does not add clarity as to what the mention is. It's only noise. I frankly don't see the value of it.
In a way, it also predefines a style of speaking. If someone wishes to put a colon after their mentions, they can do so by themself.

Removing the colon also doesn't really threaten compatibility:
![image](https://user-images.githubusercontent.com/35064754/170825562-8580b759-6802-4f82-b713-4aa18bea7bc8.png)

The specification does not specify the colon either. It is entirely the client's decision: https://spec.matrix.org/v1.2/client-server-api/#user-and-room-mentions

Overall my argument is that the colon just does not seem very useful. If however there is a good reason for it, please let me know.

**Comment by t3chguy** [comment]
It is a preference

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2403652/170831280-907f2957-cb30-4ead-b265-3279cde7b730.png">


You can disable it yourself

**Comment by t3chguy** [comment]
FTR Element Android inserts the colon too, so if your issue is actually to get rid of this feature altogether then I'd suggest an https://github.com/vector-im/element-meta issue
