### ISSUE TITLE
Thread created without any threaded message

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#22389]
### Steps to reproduce

1. Send a message

Someone also responded in a thread to a reply I sent after the wrongly threaded message, not sure if that's what caused Element to get confused.

#### What did you expect?

No thread created

#### What happened instead?

Thread created:

![2022-05-30_10-01](https://user-images.githubusercontent.com/5547783/170957417-bbaa007c-6bfe-45a6-99b9-29a169d5f24c.png)

The preview is generated from my message

In the thread tab:

![2022-05-30_10-01_1](https://user-images.githubusercontent.com/5547783/170957413-4acee514-b61a-436f-9d03-8c46c3ffaa35.png)

### Operating system

Arch Linux

### Browser information

100.0

### URL for webapp

develop.element.io

### Application version

Element version: 70a247446e29-react-15c2fb6b71b1-js-a4a50a4a5c36, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by uhoreg** [comment]
> Someone also responded in a thread to a reply I sent after the wrongly threaded message, not sure if that's what caused Element to get confused.

I don't understand this.  Can you explain more?

**Comment by babolivier** [comment]
> I don't understand this. Can you explain more?

1. I send message 1
2. I send message 2, which is a reply to a message sent before message 1
3. Someone sends a message in a thread created by message 2

I'm not at all familiar with the thread code so I don't know if that's a red herring or not, but the bug happened around the same time 3 happened.

**Comment by uhoreg** [comment]
Thanks

**Comment by gsouquet** [comment]
I believe this would have been fixed with the refactor that occurred in https://github.com/matrix-org/matrix-react-sdk/pull/9356
