### ISSUE TITLE
Add ability to change display name and profile picture in general setting without changing per-room ones that has been set by /myroomnick and /myroomavatar

### ISSUE THREAD

**Issue by whatbh** [vector-im/element-web#22386]
#### What would you like to do?
I want to keep the custom display name and profile picture I set in some rooms (using `/myroomnick` and `/myroomavatar`) unchanged when I change the those in general setting.
#### Why would you like to do it?
There are legitimate reasons I want different display name and profile picture in some rooms, changing those in general setting will discard per-room customization and and having to reiterate the routine for every room I have set a custom display name and profile picture. This is tedious and laborious. 
#### How would you like to achieve it?
I suggest having a check box to allow keeping display name and profile picture in rooms that are not identical to general setting's display name and profile picture. When the check box is checked, changing general setting's display name and profile picture will only change those in rooms that use identical ones, and leave rooms that use custom ones unchanged.

**Comment by t3chguy** [comment]
Element hits a single API to change your profile, Synapse chooses to apply that to all rooms even those which have a per-room override.

As in it works on Synapse, but there is nothing in the Matrix Spec to mandate it working the way it does.

You could open a Synapse bug but they'll likely not do anything until the spec is clearer https://github.com/matrix-org/matrix-doc/issues/545
