### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by r00ster91** [vector-im/element-web#22402]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/35064754/171164442-2381c747-6be9-4cc2-9aa9-70c02db69d83.png)

### Outcome

A space is missing after the bold "rooms." text.

### Will you send logs?

No

**Comment by rakshitgondwal** [comment]
Hey, is this issue still open ? @kerryarchibald @r00ster91

**Comment by SimonBrandner** [comment]
> Hey, is this issue still open ? @kerryarchibald @r00ster91

Yep :)
