### ISSUE TITLE
Self-hosted : Created Video Room - cannot start the conference, it is asking for unknown credentials

### ISSUE THREAD

**Issue by HeneryH** [vector-im/element-web#22405]
### Steps to reproduce

1. Where are you starting? What can you see?

>I have a self-hosted Matrix/Jiti system created via the ansible playbook.  Basic messaging works fine.  Using the Jitsi widet works fine.  Video calls work fine.
> 
> I am just starting to try the Video Room as it might be a good fit for my usecase.  The room is created and I am presented a black background with the video/audo enable buttons and the preview looks good.  There is a "connect now" button under the preview.
>  

2. What do you click?

> 
> When I click "connect now" it sits for a moment then fails with no error message at all and goes back to the prior screen.
> 
> When I do the same for the mobile app, it tells me the Host has not yet started the conference.  It gives me the option of waiting or telling the app that I am the host.  When I select the I am Host button it gives me a credential screen with user@domain/pw fields.  I am not sure what credential this is?  I never gave an email when I created my accounts on my self-hosted system.  Note the format it is asking for looks like an email address format.

5. More steps…

#### What did you expect?
Maybe the host authenticates with the matrix credentials ie #me:mydomain

#### What happened instead?
It asks for some user@domain/pw credentials that I am not sure which system it is looking up in.

### Operating system

Ubuntu 20.04 installed Matrix via ansible playbook

### Browser information

Current Firefox and Chrome behave the same.

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### Homeserver

Homeserver is https://matrix.flynnhome.org Identity server is https://vector.im

### Will you send logs?

Yes

**Comment by HeneryH** [comment]
Screen shots from Element App on iPhone and Web Browser
iPhone App
[https://i.imgur.com/RlSYINP.png](url)
[https://i.imgur.com/M74NNGv.png](url)

Browser image
[https://i.imgur.com/RMX2QAU.jpg](url)

**Comment by HeneryH** [comment]
> @HeneryH did you enable one of the Jitsi auth modes in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md#optional-configure-jitsi-authentication-and-guests-mode ?

I'll check now.  I don't think I did.

**Comment by t3chguy** [comment]
@HeneryH video rooms don't support the experimental prosody auth, so you'd either need to turn it off for Jitsi to work or wait until the eventual switch to Element Call.

**Comment by HeneryH** [comment]
@t3chguy  No problem for me to turn it off.  I just created them as a matter of flow through the help docs.

I'll confirm it works here in moment.

**Comment by HeneryH** [comment]
Interesting that that the pages look very different between Chrome and Firefox.  In Firefox the video room is completely a black background with the video panel centered in it.  In Chrome it looks like like a regular room with the jitsi widget on it.

I think I will go back to just using a regular room with the Jitsi widget on it.

Thank you for your help.
