### ISSUE TITLE
I am being asked for passphrase unexpectedly and can't exit the dialog loop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22416]
### Steps to reproduce

1. Use Element web for a while, then close tab
2. Open a new tab, see the Security Key dialog pop up:

  ![Screenshot from 2022-06-01 16-00-13](https://user-images.githubusercontent.com/51663/171436353-c03367ca-7b36-4f2f-9062-49cdbbd0d34d.png)

  -> I don't think I should be presented with this dialog right now?

3. Click "Go Back" because that seems to be the non-destructive exit path, see the cancel dialog:

  ![Screenshot from 2022-06-01 16-00-39element](https://user-images.githubusercontent.com/51663/171436595-e1950bd6-6d75-45bf-a100-e90096473b3c.png)

4. Click "Cancel" to confirm that I want to exit the flow as I can see decrypted messages in the background.
5. Get returned to the previous dialog

#### What did you expect?
Continue using the app without having to think about encryption

#### What happened instead?
I got stuck in a loop. Clicking outside the two dialogs keeps in going round in a loop. Pressing X doesn't close the dialog. Continue is greyed out but looks clickable when I hover over it.

I can't get to the composer or settings to get the app version or do a rageshake.

### Browser information

Chromium 101.0.4951.64 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by uhoreg** [comment]
For reference, you can send a rageshake by opening the JavaScript console and entering `mxSendRageshake("rageshake for #22416")`

**Comment by uhoreg** [comment]
Since several other people are reporting this, I'm upgrading it from O-Uncommon to O-Occasional.
