### ISSUE TITLE
Empty room with error Something went wrong! appeared

### ISSUE THREAD

**Issue by Paragoumba** [vector-im/element-web#22418]
### Steps to reproduce

I'm not sure how to reproduce, the room appeared out of nowhere. I use the mautrix-whatsapp bridge which might (or might not) have triggered the error.

#### What did you expect?
No empty room should appear

#### What happened instead?
An empty room showing an error appeared

### Operating system

Arch Linux

### Browser information

Firefox 102.0b2

### URL for webapp

Private server

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### Homeserver

Dendrite 0.8.7

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is the inviter missing in the invite stripped state

**Comment by Paragoumba** [comment]
I cleared the cache and reloaded and the room still appears. I have no idea how to investigate this further. What can I do?

**Comment by t3chguy** [comment]
This is an issue specific to using a Dendrite server
