### ISSUE TITLE
Replying to a poll with a thread breaks it

### ISSUE THREAD

**Issue by mtausig** [vector-im/element-web#22413]
### Steps to reproduce

1. A user creates a poll in a room
2. Another user who is part of the threads beta replies to it with a thread
3. Room members vote on the thread

#### What did you expect?

The poll should work as usual. Every user and especially the poll creator should see the votes as they come in.

#### What happened instead?

The result is that anybody (including the person having created the poll) can only see their own vote but not the final tally.

Everyone in the room not being part of the threads-beta can see all the votes cast.

Selecting *Clear Cache and Reload* fixes the problem locally.

### Operating system

Windows 10

### Application version

Element version: 1.10.13,  Olm version: 3.2.8

### Homeserver

local server, Synapse 1.60.0

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
No longer reproduces, covered by e2e test here: https://github.com/matrix-org/matrix-react-sdk/pull/9073
