### ISSUE TITLE
Pressing up to edit latest message stopped working (again)

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#22421]
### Steps to reproduce

1. In a chat view
2. Send a message
3. Press the up-key to edit that message

Please note: this is **not 100% reprodicble** and I don't know what causes this problem to occur. So please refrain from resolving/closing this issue on that basis.

This is a followup from #19908 which was resolved. It's possible the root cause is different, even though the effect appears to be the same.

#### What did you expect?
The most recently sent message goes into edit mode

#### What happened instead?
Either a (much) earliest sent message goes into edit mode, or nothing happens at all.

### Operating system

Windows 10 21H2

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I cannot reproduce

**Comment by thany** [comment]
That's to be expected. It's completely and utterly unclear to me what triggers this problem. I have the same application on the same account in the same room on a different pc, and there it works fine. On the pc I'm on right now, it selects the incorrect message or doesn't select a message at all.

So I can't even reproduce it, unless I happen to be on a pc where I can.

So, I'm sorry to say, but "cannot reproduce" is the correct answer, and getting it reproduced is what this bug is partly about. Getting to the bottom of why this might happen.

This is why I asked before, and I'll ask again, what are EXACTLY the steps and circumstances of the application in order to select a message to edit? Those steps might reveal why it won't work correctly.

**Comment by t3chguy** [comment]
> This is why I asked before, and I'll ask again, what are EXACTLY the steps and circumstances of the application in order to select a message to edit? Those steps might reveal why it won't work correctly.

https://github.com/matrix-org/matrix-react-sdk/blob/8036985204cf7defd20f815f527e4e84cd52c7c9/src/components/views/rooms/SendMessageComposer.tsx#L213-L233
https://github.com/matrix-org/matrix-react-sdk/blob/21d0aaf52422a4bb51d7e8e221956e2248894d29/src/utils/EventUtils.ts#L104-L135

**Comment by thany** [comment]
Okay, so please explain the reason for closing this issue? It is NOT fixed.

**Comment by t3chguy** [comment]
@thany are you saying you can still reproduce it on develop?
