### ISSUE TITLE
Can't upload attachments from Element Desktop but works from Android to same room 

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-web#22429]
### Steps to reproduce

1. Where are you starting? What can you see?
Tried to upload attachment but get error:
Upload Error
This file is **too large** to upload. The file size limit is 0 B but this file is SIZEofFileHere KB.

The room version is 6. Nothing happens in Dendrite server when clicking to send attachment so it seems
error is in Element Desktop client itself, since dev console simply says:
"Starting load of AsyncWrapper for modal" 
And nothing happens except that error about file is too large.

Yet I can upload larger files from Android app to the same room just fine.

#### What did you expect?
File/photo to be uploaded.
#### What happened instead?
Error popup that is actually a wrong error it seems, file is not too large at all and Android app works fine.

### Operating system

Windows 10

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started 

### Homeserver

Dendrite 0.8.5 or above

### Will you send logs?

No

**Comment by turt2live** [comment]
Dendrite needs to support the media config endpoint. Please open an issue there.
