### ISSUE TITLE
High Element and pulseaudio CPU usage after leaving video conference

### ISSUE THREAD

**Issue by ProactiveServices** [vector-im/element-web#22420]
### Steps to reproduce

An ongoing video conference, that I left, seems to be causing me high CPU and pulseaudio CPU usage of about 50% of my available CPU cycles.

#### What did you expect?
CPU usage to drop to idle once I left.

#### What happened instead?
CPU usage remains high.

### Operating system

Ubuntu 20.04.4, pulseaudio 13.99.1

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

apt via https://packages.riot.im/debian

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Was this a Jitsi conference, do you happen to see a bunch of Chrome/Chromium tracks in Pulseaudio?

**Comment by ProactiveServices** [comment]
It was a Jitsi conference. I did notice a dozen or so Chromium entries in the volume setting flyout in that context as well as during a 1-to-1 voice call.

**Comment by SimonBrandner** [comment]
> It was a Jitsi conference. I did notice a dozen or so Chromium entries in the volume setting flyout in that context as well as during a 1-to-1 voice call.

To clarify: you see high Pulseaudio CPU usage when in a Jitsi call but a low number of tracks?

**Comment by ProactiveServices** [comment]
My initial report was regarding high Element and Pulseaudio CPU usage observed after I left the Jitsi call and for perhaps 10-15 minutes, until I exited and reloaded Matrix.

On another occasion, whilst in a 1-to-2 voice call, I observed a lot of Chromium tracks present in the system's volume flyout, which may suggest many concurrent tracks. I'll collect further information and follow-up.

**Comment by SimonBrandner** [comment]
> My initial report was regarding high Element and Pulseaudio CPU usage observed after I left the Jitsi call and for perhaps 10-15 minutes, until I exited and reloaded Matrix.

Do you know if there were a lot of tracks in Pulseaudio in _this case_?

> On another occasion, whilst in a 1-to-2 voice call, I observed a lot of Chromium tracks present in the system's volume flyout, which may suggest many concurrent tracks. 

This is https://github.com/vector-im/element-web/issues/19294

> I'll collect further information and follow-up.

:+1:

**Comment by ProactiveServices** [comment]
Seeing both high CPU and pulseaudio tracks in this case; https://github.com/vector-im/element-web/issues/19294 is precisely what I'm seeing, both with 1-to-1 voice calls and Jitsi video conferences, apologies for the dupe.
