### ISSUE TITLE
Plaintext labs options not present on Windows

### ISSUE THREAD

**Issue by rom4nik** [vector-im/element-web#22432]
### Steps to reproduce

1. Open Settings
2. Go to Labs
3. Scroll down
4. Plaintext options (i.e. video rooms) which appear on Arch Linux build are missing on Windows build (confirmed by 2 of my users)

#### What did you expect?

![image](https://user-images.githubusercontent.com/46846000/171828788-ac4188a6-a181-43a6-bf2c-eab81ea67acd.png)

#### What happened instead?

![image](https://user-images.githubusercontent.com/46846000/171828669-d09f8b73-df9f-4db4-bc24-7e748946e330.png)

### Operating system

Windows

### Application version

Element version: 1.10.13 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

Synapse 1.60.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
They need to be enabled in config.json https://github.com/vector-im/element-web/blob/develop/docs/config.md#labs-flags - Element Nightly has them pre-enabled

**Comment by rom4nik** [comment]
Oh, I didn't realize that was the case, sorry. Can I set a config.json server-wide that all desktop Elements will use by default, or is it possible only for self-hosted web Element?

**Comment by t3chguy** [comment]
Element Desktop doesn't have a server, connects directly to your Matrix server, so the config is per-instance (per install)

https://github.com/vector-im/element-desktop/#user-specified-configjson

**Comment by rom4nik** [comment]
I was hoping Synapse could somehow suggest a config to Element clients. It's just a bit confusing, given that i.e. Android client doesn't need any special configuration to show those experimental settings in labs.
Thanks for help anyway.

**Comment by paboum** [comment]
Why is it hidden by default? A warning should suffice, especially if beta features are reviewed before releasing. Conversely, a hint how to enable this should be made in GUI, especially if it's easily available in element-android.
Took me some time to find this ticket and understand what's happening. Especially confusing was noticing the difference between "room developer options" which in Polish locale is once called "opcje deweloperskie", then it's "opcje programistyczne", and then in labs we have the three main items visible by default and the others are not even captioned in my pure web client (had the flag enabled in config.json already) so I don't know what I'm missing.
Clearly, @rom4nik understands what I mean here.
