### ISSUE TITLE
Decorated room avatar for offline status on light theme makes eclipse

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22443]
### Steps to reproduce

1. Set the theme to `Light`
1. Create a test user
2. Add the user as a friend on your main account
3. Log out from the test user account

#### What did you expect?

The icon should have the clear contrast.

#### What happened instead?

It looks to have the same color as its background and makes the avatar icon like an eclipse.

![before](https://user-images.githubusercontent.com/3362943/172038390-146feacd-db87-43e1-bd2d-60638bc1ea7d.png)

### Operating system

Debian

### Application version

Element version: 1.10.13, Olm version: 3.2.8

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Could it possibly be intentional?

**Comment by luixxiul** [comment]
I am not sure about it because on the dark theme the contrast is very obvious.

![before](https://user-images.githubusercontent.com/3362943/172059139-fa8a9f12-a403-48f5-99b2-a724f91e65c6.png)

**Comment by luixxiul** [comment]
apparently compound should fix this.
