### ISSUE TITLE
Composer looks awkward in the right panel

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22459]
### Steps to reproduce

Open a thread, maximize a widget, or open the chat panel in a video room

#### What did you expect?

Not entirely sure

#### What happened instead?

The reply preview spills over the sides, and the composer is surrounded by two different borders that are right on top of one another:

![Screenshot 2022-06-07 at 09-21-22 Element Robin's video room 1](https://user-images.githubusercontent.com/48614497/172390646-d9e6d195-b6a9-4a9e-8156-daf107fa2b94.png)

### Operating system

NixOS unstable

### Browser information

Firefox 100.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 1f3826f3cee6-react-5da187d520f8-js-cb5b2e14703e Olm version: 3.2.8

### Homeserver

Synapse 1.60.0

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer

**Comment by HarHarLinks** [comment]
In my opinion (more) clearly visible in dark mode:
![](https://user-images.githubusercontent.com/2803622/173629332-9620693b-3572-400f-9416-88346123c32f.png)
