### ISSUE TITLE
Avatar not updated in mac app-not visisble in left pane...

### ISSUE THREAD

**Issue by peters77** [vector-im/element-web#22454]
### Steps to reproduce

A friend (alex) added an avatar to his profile. 
The avatar shows if I select the user info. The avatar is visible in the chat, but the picture is not updated in the room list and on the left top where I see the last accessed rooms. 
All is working fine in the iOS app. 
MacApp element:
<img width="1305" alt="Bildschirmfoto 2022-06-06 um 10 00 24" src="https://user-images.githubusercontent.com/8840918/172154040-b086f54a-fc11-489c-9844-6461b913e6d2.png">

iOS App element:
![image1](https://user-images.githubusercontent.com/8840918/172154087-ca705cf8-96b3-4ae0-8d0a-47e84e37606e.png)

#### What did you expect?
The avatars (pictures) should be visible in the room list on the left and last actioned rooms on the top left of the element app
#### What happened instead?
Picture didn't get updated, see the the first letter of the the name instead. 

### Operating system

macOS Big Sur and Monterey

### Application version

Version 1.10.13 (1.10.13)

### How did you install the app?

Appstore

### Homeserver

homeserver, synapse v1.60.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Try go into Settings > Help & About > Clear cache and reload

**Comment by SimonBrandner** [comment]
Closing as the problem seems to be gone
