### ISSUE TITLE
Unpin should be removed from the widget kebab menu

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22466]
### Steps to reproduce

1. Add a custom widget to a room
2. Look at the actions in the widget title and the kebab menu

#### What did you expect?

- No „Unpin“ item

#### What happened instead?

- Menu contains an „Unpin“ item

![image](https://user-images.githubusercontent.com/6216686/172427191-6b436e78-1367-4cfe-ad6d-16174bd38d35.png)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 100.0.2 (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Element version: b44df4bcc311-react-3a20cb17038b-js-2982bd79f610 Olm version: 3.2.8

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
According to https://github.com/vector-im/element-web/issues/20506#issuecomment-1023305830 the option in the kebab menu should simply have been removed, but it appears that did not in fact happen.

**Comment by weeman1337** [comment]
Thanks for linking the comment @HarHarLinks
