### ISSUE TITLE
New composer flickers between room changes

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22462]
### Steps to reproduce

1. Be in a room
2. Click a different room
3. Composer flickers

#### What did you expect?

Not a distracting flicker every time I change a room :P

#### What happened instead?

The border flickers, almost certainly because it's going from focus -> no focus (due to room list click) -> focus (from room change). 

### Operating system

Windows 10

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer

**Comment by t3chguy** [comment]
No more flicker probably due to losing most of its styling
