### ISSUE TITLE
It's possible to get "caught" scrolled up by the new composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22464]
### Steps to reproduce

1. Exist?? (I think receiving typing notifications causes it?)
2. Type a message
3. Notice that while you haven't sent anything you're "scrolled up" (new messages appear under the composer with a "jump to bottom" button)

#### What did you expect?

Not a regression

#### What happened instead?

See above. Somewhere we have a variable or two which deals with composer height - that variable might need adjusting to magically fix this.

### Operating system

Windows 10

### Will you send logs?

No

**Comment by turt2live** [comment]
`S-Major` because shipping with this will cause us to lose users. Workaround of scrolling down/clicking the button manually works, however the user is more likely to leave the app before accepting that as a "workaround".

**Comment by gsouquet** [comment]
Managed to reproduce the issue consistently.
You get scrolled up by 1px if you type a message, do not send it, and completely erase the content that is in the composer 


https://user-images.githubusercontent.com/769871/172592417-560a5209-137d-43a1-9944-36239e076d2a.mov

**Comment by turt2live** [comment]
thanks for the quick fix on this <3
