### ISSUE TITLE
Previewing a room adds it to the 'historical' section of the roomlist

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#22473]
### Steps to reproduce

1. Search for #archlinux:archlinux.org.
2. Preview the room.
3. See the Archlinux room show up in **Historical** upon fully loading everytime.
4. Find another room such as #grapheneos:grapheneos.org, #CalyxOS:matrix.org, etc (most rooms are not like #archlinux:archlinux.org).
5. Preview the room.
6. See that none of the rooms show up in **Historical**.
7. Close and open Element (full restart) and see all rooms suddenly show up in **Historical** as expected (or not, previewed rooms ending up in **Historical** doesn't feel correct in my opinion).

#### What did you expect?

All previously previewed rooms either do (or don't) show up in **Historical** immediately upon fully loading.

#### What happened instead?

Some select rooms (doesn't seem to be based on Homeserver) will end up in **Historical** upon loading, but most other rooms don't and require restarting Element to show up.

**Additional**: Sometimes they'll also get stuck and require a restart to be removed (related to https://github.com/vector-im/element-web/issues/18473), as well as leave notifications behind even after leaving, but, I think that's unrelated.

### Operating system

Arch Linux

### Application version

Element version: 1.11.3
Olm version: 3.2.12

(Originally spotted in: Element version: 1.10.13, Olm version: 3.2.8)

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by robintown** [comment]
This is a regression of https://github.com/vector-im/element-web/issues/10861
