### ISSUE TITLE
Notification dot/number on pinned desktop app

### ISSUE THREAD

**Issue by ArtexJay** [vector-im/element-web#22475]
#### What would you like to do?
Add notification dot/marker/number on Element icon if it's open or pinned on the taskbar.
![image](https://user-images.githubusercontent.com/32932497/172505354-dca2c4d1-f075-4b80-a596-5934d6381e7e.png)

#### Why would you like to do it?
It would be easier to notice/see it compared to when it's in the system tray.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14033

**Comment by ArtexJay** [comment]
> Duplicate of #14033

thanks, didn't see/find it when i searched for it myself.
