### ISSUE TITLE
New right click context menu should offer a download option

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#22479]
#### What would you like to do?

Download sent or received media

#### Why would you like to do it?

With the browser's native context menu there's an option to download a sent/received videos by right clicking on it and clicking Save As. This opens the FileChooser dialogue and initiates the download.

The new context menu seems to replace this with the app's own context menu, so now there's no way to download a sent video by right clicking on it in the chat timeline.

#### How would you like to achieve it?

Add a "Download" option in the context menu.

### Have you considered any alternatives?

Disabling the new context menu in Labs and using the native context menu.

### Additional context

None.

**Comment by weeman1337** [comment]
Hi @bbhtt ! Thank you for opening this issue.

I can see a download option in the „direct actions“ of a message:

![image](https://user-images.githubusercontent.com/6216686/172549612-cb7441a0-2eb6-4c0e-89c3-25eb7b67ee67.png)

If that is not what you are looking for can you please update your issue description with the settings you are using? I will then try to reproduce the issue. An example may be adding additional steps „enable right click context menu in labs“ etc. .

**Comment by bbhtt** [comment]
Ahh, thank you. I missed that.

I was expecting to see it here like the native context menu
![image](https://user-images.githubusercontent.com/62639087/172551065-a65e5356-3c31-4986-8fc7-6ec4521b4c00.png)

Closing.
