### ISSUE TITLE
Shield in composer in encrypted rooms where you don't have permission to post is in the wrong place

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22484]
### Steps to reproduce

View an encrypted room where you don't have permission to send messages

#### What did you expect?

The encryption shield should be on the right side of the composer

#### What happened instead?

It's squished up against the notice:

![Screenshot 2022-06-08 at 09-12-40 Element 3 Element Company Announcements](https://user-images.githubusercontent.com/48614497/172625090-5bb255af-2bdb-4d3e-9c81-af4712789e99.png)

### Operating system

NixOS unstable

### Browser information

Firefox 100.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 569838978918-react-f568a76dc644-js-b20063f8a8ef Olm version: 3.2.8

### Homeserver

Synapse 1.60.0

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
