### ISSUE TITLE
In High Contrast, the search box's scroll buttons are not readable

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#22481]
### Steps to reproduce

1. Set "Use high contrast" in Settings -> Appearance
2. Enable "The new search" in labs
3. In a room, press Ctrl-K to launch the search box

#### What did you expect?
Something like the normal light theme:
![image](https://user-images.githubusercontent.com/76812/172606173-814fa0cc-ac96-4ac2-acb9-4cca3558320d.png)
(This is really nice, by the way)

#### What happened instead?
Buttons are not visible/readable

![image](https://user-images.githubusercontent.com/76812/172606045-400d50ce-ef44-4f2d-8d02-ba2bd279f445.png)

### Operating system

Ubuntu 21.10

### Browser information

Firefox 100.0

### URL for webapp

https://develop.element.io

### Application version

Element version: af609e35a3cc-react-36f2f3e2cef0-js-11cc2aca9dc1 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by luixxiul** [comment]
This happens because both of `$tertiary-content` and `$quinary-content` refer `$secondary-content` on `_light-high-contrast.scss`.

**Comment by andybalaam** [comment]
Very similar problem in composer: 
![image](https://user-images.githubusercontent.com/76812/172847722-cfb900e1-2acd-434f-b6d2-d2350cf2e6ea.png)

If anyone wanted to fix both at once..

**Comment by luixxiul** [comment]
I guess this requires a professional insight on a11y. It should be at least decided which color to be implemented instead.

**Comment by andybalaam** [comment]
> I guess this requires a professional insight on a11y. It should be at least decided which color to be implemented instead.

I think it's pretty straightforward - we can follow the same pattern as https://github.com/vector-im/element-web/issues/19931

**Comment by luixxiul** [comment]
Yes right... I did not know that the issue has been experienced already, sorry for the noise!

**Comment by andybalaam** [comment]
@luixxiul No problem, thank you!

**Comment by andybalaam** [comment]
Thank you! :tada:
