### ISSUE TITLE
Room history not visible after one month on unencrypted rooms

### ISSUE THREAD

**Issue by s0p4LiN** [vector-im/element-web#22488]
### Steps to reproduce

1. Where are you starting? What can you see?

A manager just informs me that all employees can not see history over 1 month even in unencrypted rooms.
Is there a limit on the web version of Element ?

3. What do you click?

scroll up to see previous messages

5. More steps…

#### What did you expect?

See history

#### What happened instead?

![image](https://user-images.githubusercontent.com/68989865/172652096-cb327660-ec83-41f1-8fbe-3818dc575416.png)
Depending the user, the history is visible one month ago or 2 month etc, it change when I'm on the web version or the desktop version

How come on unencrypted rooms the history not visible ?

### Operating system

Windows 

### Browser information

Latest

### URL for webapp

https://chat.company.lan

### Application version

Element version: 1.10.12 Olm version: 3.2.8

### Will you send logs?

No

**Comment by s0p4LiN** [comment]
I double check on private messages and on room I created on december 2021

PM with user, can not see message before yesterday
![image](https://user-images.githubusercontent.com/68989865/172785393-6a50f7af-ff77-42fd-b694-c44801162ca3.png)

This room was created in december 2021, and has a lot of messages history, but I can not see it before 16th May 2022

![image](https://user-images.githubusercontent.com/68989865/172785872-dfc858ac-e2ee-4783-8e0f-511eae3a5157.png)

The settings are the same than yours
![image](https://user-images.githubusercontent.com/68989865/172786038-8f624e22-1bfc-4272-a0fd-e32933ef6c1e.png)


I search about the "You can't see earlier messages" but on this github, it is about encrypted room, which we do not have in the company, we use only unencrypted rooms, and we do not use Element Desktop App but the Embedded Web version as chrome app.

**Comment by aaronraimist** [comment]
The "You can't see earlier messages" is not only for encrypted rooms. It can be triggered based on several different conditions https://github.com/matrix-org/matrix-react-sdk/pull/5887/files#diff-69240a2e8f6142e6794b3dd6890d203515b151dca861ff0cebb4316360d4704fR31-R38

Is it possible your server has enabled the experimental message retention feature in Synapse? https://github.com/matrix-org/synapse/blob/master/docs/message_retention_policies.md

**Comment by s0p4LiN** [comment]
Thanks for the tips .... it was the message retention, a bad understanding on my side of the features.
I thought it was for the logs retention of the messages

![image](https://user-images.githubusercontent.com/68989865/173018031-bf7e71ae-4500-4643-b5c6-2f410b0434be.png)
