### ISSUE TITLE
Long displayName can overflow from the reply preview on the new message composer 

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22495]
### Steps to reproduce

1. Create a test user whose display name is long
2. Send something from the user
3. Reply to the message from the main account

#### What did you expect?

The display name should not overflow.

![after](https://user-images.githubusercontent.com/3362943/172781835-acc40051-1425-454e-9744-c16818380081.png)

#### What happened instead?

It overflows.

![before](https://user-images.githubusercontent.com/3362943/172781886-6926b49f-afc3-46fd-9227-b9f1846a0d83.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
