### ISSUE TITLE
emoji cut off on the new message composer

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22508]
### Steps to reproduce

1. Add an emoji

#### What did you expect?

It should be fully visible

#### What happened instead?

It is cut off

![Untitled](https://user-images.githubusercontent.com/3362943/172997728-33af5a82-fe63-4edc-8d14-eb0e1e8da687.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
