### ISSUE TITLE
Composer overflow on long input

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22507]
### Steps to reproduce

1. Input `aaa...`

#### What did you expect?

the new composer should not overflow.

#### What happened instead?

It overflows.

![Untitled](https://user-images.githubusercontent.com/3362943/172997316-16e16e25-eab4-4901-bb63-5e35762b6842.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
On the right panel:

![Untitled](https://user-images.githubusercontent.com/3362943/173027441-90b34ad1-5b1a-4275-abe0-25b9822302cc.png)

**Comment by justjanne** [comment]
The following change seems to resolve the issue for me locally:

```diff
diff --git a/res/css/views/rooms/_MessageComposer.scss b/res/css/views/rooms/_MessageComposer.scss
index 5c34f78a8b..8e091b9431 100644
--- a/res/css/views/rooms/_MessageComposer.scss
+++ b/res/css/views/rooms/_MessageComposer.scss
@@ -37,6 +37,7 @@ limitations under the License.
     }
 
     .mx_MessageComposer_row {
+        overflow: hidden;
         grid-area: composer;
     }
 

```
