### ISSUE TITLE
Empty send button on the new message composer

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22506]
### Steps to reproduce

1. Open a room
2. Move the mouse cursor to the edge of the message composer

#### What did you expect?

There should not be a send button.

#### What happened instead?

There is a clickable empty send button.

![Untitled](https://user-images.githubusercontent.com/3362943/172996611-10d2ae32-f043-4c72-859e-25a477118a10.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
The bug is reproduced on the right panel as well.

**Comment by turt2live** [comment]
blocked on the future of the composer
