### ISSUE TITLE
When composing a very long, unwrappable message, the composer overflows

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#22514]
### Steps to reproduce

1. Write a very long, unwrappable message, e.g. 2000 times the character "w"

#### What did you expect?

The composer forces the message to be wrapped anyway

#### What happened instead?

The composer overflows out of its boundaries, through the right panel and into nirvana.

### Operating system

Ubuntu Budgie 22.04 (jammy)

### Application version

Element Nightly version: 2022061001 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

chat.element.io

### Will you send logs?

No

**Comment by luixxiul** [comment]
Same as https://github.com/vector-im/element-web/issues/22507 ?

**Comment by justjanne** [comment]
The following change seems to fix the issue for me locally:

```diff
diff --git a/res/css/views/rooms/_MessageComposer.scss b/res/css/views/rooms/_MessageComposer.scss
index 5c34f78a8b..8e091b9431 100644
--- a/res/css/views/rooms/_MessageComposer.scss
+++ b/res/css/views/rooms/_MessageComposer.scss
@@ -37,6 +37,7 @@ limitations under the License.
     }
 
     .mx_MessageComposer_row {
+        overflow: hidden;
         grid-area: composer;
     }

```

**Comment by justjanne** [comment]
> Same as #22507 ?

You’re right, it’s a duplicate! Sorry I didn’t check earlier

**Comment by luixxiul** [comment]
No problem! Rather thank you for creating the issue to confirm the bug.
