### ISSUE TITLE
OSX app stays in dock after closure

### ISSUE THREAD

**Issue by monochromec** [vector-im/element-web#22519]
### Steps to reproduce

1. Open Element for Desktop app
2. Close it (CMD-q or via the app menu)
3. Observe the icon staying in the dock (until you explicitly remove it from the dock)

#### What did you expect?

Icon disappearing from the dock

#### What happened instead?

Icon staid in the dock

### Operating system

OSX 12.4

### Application version

1.10.14

### How did you install the app?

https://element.io/get-started#download

### Homeserver

Private synapse instance

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This sounds like normal behaviour? I just Cmd+Q'd WhatsApp and Preview and they both stayed in my dock even though unpinned.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/2403652/173073560-2743cf94-a910-4c5a-aa27-ec83ef1ed490.png">

Looks like the latest 3 unpinned will always stick around

https://osxdaily.com/2018/10/22/hide-show-recent-apps-mac-dock/

**Comment by robintown** [comment]
This is intentional macOS behavior, as per above

**Comment by monochromec** [comment]
The wonders of OSX.... :-)

Thanks for the clarification!
