### ISSUE TITLE
The placeholder on the new composer lacks ellipsis effect

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22511]
### Steps to reproduce

1. Reduce the width of the window

#### What did you expect?

The ellipsis effect should be enabled on the placeholder.

#### What happened instead?

It is hidden abruptly.

![Untitled](https://user-images.githubusercontent.com/3362943/173028294-0d122563-33d6-44f7-a9fa-bd3492ff6009.png)

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
