### ISSUE TITLE
Add "clear/clean cache" feature which is in Android Element Client

### ISSUE THREAD

**Issue by jahway603** [vector-im/element-web#22529]
#### What would you like to do?
Clear & clean the cache in the Element Desktop client as is available in the Android Element Client.

#### Why would you like to do it?
Currently there are "stuck rooms" which disappear when I clear & clean the cache on the Android Element Client, but this functionality does not exist in the Element Desktop Client.

#### How would you like to achieve it?
However I can

### Have you considered any alternatives?

No because this feature exists in the Android Element Client already which resolved the "stuck rooms" issue on that platform.

**Comment by DoM1niC** [comment]
> ### Your use case
> #### What would you like to do?
> 
> Clear & clean the cache in the Element Desktop client as is available in the Android Element Client.
> #### Why would you like to do it?
> 
> Currently there are "stuck rooms" which disappear when I clear & clean the cache on the Android Element Client, but this functionality does not exist in the Element Desktop Client.
> #### How would you like to achieve it?
> 
> However I can
> ### Have you considered any alternatives?
> 
> No because this feature exists in the Android Element Client already which resolved the "stuck rooms" issue on that platform.
> ### Additional context
> 
> _No response_

Under Support / Help you can clean Cache and force a new init sync 

### like this
![grafik](https://user-images.githubusercontent.com/1436958/173139475-d592c605-e811-401f-908f-edb163df43c1.png)

**Comment by t3chguy** [comment]
As above, it is already available in Setting > Help & About
