### ISSUE TITLE
New line is inserted on the new message composer with IME enabled by inputting backspace key or deleting draft

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22526]
### Steps to reproduce

1. Enable IME such as `fcitx-mozc`
2. Enable Japanese
3. Set a focus to the new message composer
4. Input <kbd>Backspace</kdd>
5. Input `あ` with <kbd>a</kbd>

#### What did you expect?

New line should not be inserted.

#### What happened instead?

New line is inserted temporarily until pushing <kbd>Enter</kbd> to decide the conversion candidate.

https://user-images.githubusercontent.com/3362943/173106785-4a91633a-29c1-41ad-97bf-1c5c3523ddb4.mp4

This is a regression which has not happened before, and harms the UX of CJK (Chinese, Japanese, Korean) language users.

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by luixxiul** [comment]
Actually this is reproduced constantly by deleting a draft and writing a new sentence like this:

https://user-images.githubusercontent.com/3362943/173108508-daca981f-62ad-453e-a121-5afa5234efcc.mp4

**Comment by turt2live** [comment]
if this isn't determined to be caused by the new composer (which I'm fairly sure is just aesthetic), then it's not a release blocker.

**Comment by luixxiul** [comment]
This is reproduced already on app.element.io, so yes, I think this is not a blocker.

**Comment by luixxiul** [comment]
The issue is no longer reproduced. Closing as stale.
