### ISSUE TITLE
Some options disappear.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#22538]
### Steps to reproduce

n/a

#### What did you expect?
n/a

#### What happened instead?
After updating to 1.10.14, some settings in "Settings -> Preferences" disappeared.

Before (1.10.13):
![{EBA5A353-B9D6-81AC-14D4-9580A43A664C}](https://user-images.githubusercontent.com/48104960/173173051-60d4047f-73d7-4c09-910c-3cda0a0f29b6.png)

After (1.10.14):
![{BD48C004-652B-C90B-24AF-36193CE4665F}](https://user-images.githubusercontent.com/48104960/173173059-b9027f03-9057-472d-881b-8153640e2ef0.png)

### Operating system

x64 Windows 10 21H2 (Enterprise LTSC)

### Application version

Element 1.10.14

### How did you install the app?

From https://packages.element.io/desktop/update/win32/x64/

### Homeserver

Synapse 1.60.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
@YamatoRyou Could you please send logs

@turt2live not sure if this is a Release Blocker given a single report and already from a released version and not Nightly

**Comment by YamatoRyou** [comment]
> @YamatoRyou Could you please send logs
> 
> @turt2live not sure if this is a Release Blocker given a single report and already from a released version and not Nightly

[rageshake.zip](https://github.com/vector-im/element-web/files/8883978/rageshake.zip)
Password: ```CBB2DF5FB758EE72003375D0496BCEFF```

**Comment by t3chguy** [comment]
Regressed by https://github.com/vector-im/element-web/pull/22295
Fixes by https://github.com/vector-im/element-web/pull/22491

We will consider an off-cycle release with these fixes
