### ISSUE TITLE
Upload progress bar and the new message composer not aligned

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22534]
### Steps to reproduce

1. Open a room
2. Upload a file

#### What did you expect?

The message composer and the upload bar should be aligned.

#### What happened instead?

They are not aligned.

![before1](https://user-images.githubusercontent.com/3362943/173172038-6d3e826a-4e9f-435c-817f-1a0641883a1e.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer

**Comment by luixxiul** [comment]
It looks like the same kind of issue is reproduced with connection lost bar.

![Untitled](https://user-images.githubusercontent.com/3362943/173566518-f58e7dd8-81f9-4240-8394-574a38f27ee5.png)
