### ISSUE TITLE
Stickers picker's context menu covering message composer

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22535]
### Steps to reproduce

1. Open a room
2. Open the sticker picker

#### What did you expect?

Gap should exist between the sticker picker's context menu and the composer area.

#### What happened instead?

The sticker picker's context menu covers the composer area.

![before1](https://user-images.githubusercontent.com/3362943/173172175-e12a728b-edaa-457c-beb3-799ef86c11f7.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
blocked on the future of the composer
