### ISSUE TITLE
slash autocomplete menu hides the new message composer

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22537]
### Steps to reproduce

1. Open a room
2. Input slash

#### What did you expect?

The composer should not be hidden.

#### What happened instead?

Its upper area is hidden.

![before1](https://user-images.githubusercontent.com/3362943/173172696-56383671-26d2-4d52-b7b0-d5c0105b1350.png)

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
I think this might be a feature

**Comment by turt2live** [comment]
blocked on the future of the composer
