### ISSUE TITLE
EW hides history from before your join as soon as it encounters something undecryptable, even if you have decryptable things before it

### ISSUE THREAD

**Issue by leona-ya** [vector-im/element-web#22544]
### Steps to reproduce

1. Create a new room with the old user
2. Send message with the old user on Element Web
3. Send message with the old user on Element Android
4. Invite new user to long existing room on Element Web (all messages are available there)
5. Accept invitation
6. Encryption keys aren't transferred

#### What did you expect?
All message keys are transferred to the new account and the messages are visible over there.

#### What happened instead?
Messges aren't available

Old account:
![screenshot-2022-06-11_23-06-1654981598](https://user-images.githubusercontent.com/11006031/173204983-e6c8a77c-0a52-401e-b717-5082e1f5995d.jpg)

New account:
![screenshot-2022-06-11_23-06-1654981582](https://user-images.githubusercontent.com/11006031/173204992-bd9c7a5e-eeb4-4716-9c3d-683d6b417e3e.jpg)

However, it works in a new room with a few messages sent right before the invitation by the same client.

### Operating system

NixOS

### Application version

1.10.13 (Web+Desktop)

### Homeserver

synapse 1.60.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This will be an Android bug with not supporting shared history megolm sessions.
The sending client has to mark the megolm session as sharable for the inviting client to share them over.

Tracked in https://github.com/vector-im/element-android/issues/4153

The other part of this is EW hides history from before your join as soon as it encounters something undecryptable, even if you have decryptable things before it

**Comment by ara4n** [comment]
dup of https://github.com/vector-im/element-web/issues/22671
