### ISSUE TITLE
Opening PreferencesTab twice causes uncaught error

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22545]
### Steps to reproduce

1. Open the settings
1. Click `Preferences`
2. Close the settings by using the X
3. Reopen the settings
4. Click `Preferences`

#### What did you expect?

Preferences should be displayed.

#### What happened instead?

The settings window is closed with `Uncaught Error: Level platform is not prioritized`.

### Operating system

Debian

### Browser information

Firefox ESR 99

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
IMHO this is a release blocker.
