### ISSUE TITLE
New composer can expand off the right edge of the display

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22540]
### Steps to reproduce

1. Open a room
2. Copy paste the string `1111111111111111111111111` a lot (or similar)
3. Composer goes off screen

#### What did you expect?

The composer should word wrap.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/173177114-dbda5513-544c-4891-86b4-4e196412b9cc.png)

note that the composer continues *through* the right panel.

### Operating system

Windows 10

### Will you send logs?

No

**Comment by luixxiul** [comment]
Same as https://github.com/vector-im/element-web/issues/22507 ?

**Comment by turt2live** [comment]
yes, just missing triage labels. Have added.
