### ISSUE TITLE
How to migrate from riot.im to element-desktop ?

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#22557]
### Steps to reproduce

I am on element-desktop 1.10.14 - 
```

$ apt-cache policy element-desktop
element-desktop:
  Installed: 1.10.14
  Candidate: 1.10.14
  Version table:
 *** 1.10.14 500
        500 https://packages.riot.im/debian default/main amd64 Packages
        100 /var/lib/dpkg/status
```

Now whenever I start element-desktop session I get the following - 
```

$ element-desktop
/home/shirish/.config/Element exists: no
/home/shirish/.config/Riot exists: yes
Using legacy user data path: /home/shirish/.config/Riot
```

### Outcome

What I was expecting is either here or on element-desktop site, there would be some sort of migration guide but that seems to be missing :(

While looking at ~/.config/Riot$ found the following - 

```
~/.config/Riot$ ls
 000013.log        CURRENT                              'Local Storage'                Preferences
 blob_storage      databases                             LOCK                          QuotaManager
 Cache             Dictionaries                          LOG                           QuotaManager-journal
'Code Cache'       electron-config.json                  LOG.old                      'Session Storage'
 Cookies           EventStore                            MANIFEST-000012               sso-sessions.json
 Cookies-journal   GPUCache                             'Network Persistent State'     TransportSecurity
 Crashpad          IndexedDB                            'Origin Bound Certs'           webrtc_event_logs
'Crash Reports'    in_progress_download_metadata_store  'Origin Bound Certs-journal'   window-state.json
```
Now I could do the easy change of just rename the directory from - 

~/.config/Riot$  ~/.config/Element$ 

Or is there any more to it? 

Also for this message - 
`
Using legacy user data path: /home/shirish/.config/Riot`

Would that change things a bit ???

### Operating system

Debian Testing

### How did you install the app?

Added         500 https://packages.riot.im/debian default/main amd64 Packages to my pack

### Will you send logs?

Yes

**Comment by shirishag75** [comment]
I did look up https://element.io/previously-riot but that's about what I could find about the change :(

**Comment by t3chguy** [comment]
You can rename it or just ignore it given the migration isn't going away

**Comment by shirishag75** [comment]
> You can rename it or just ignore it given the migration isn't going away

I didn't get what you mean by that. Could you be more specific in what you mean?

**Comment by shirishag75** [comment]
> > I didn't get what you mean by that. Could you be more specific in what you mean?
> 
> ```
> /home/shirish/.config/Element exists: no
> /home/shirish/.config/Riot exists: yes
> ```
> 
> You can either rename the directory from Riot to Element whilst the app is quit or just ignore this bit of log output. It uses either folder in an identical manner.

Aha, now I get it - 

```
$ element-desktop
/home/shirish/.config/Element exists: yes
/home/shirish/.config/Riot exists: no

I am going to close this issue as this one is solved, at least this part. 
```
