### ISSUE TITLE
Homeservers are barely distinguishable from bridges

### ISSUE THREAD

**Issue by frakic** [vector-im/element-web#22552]
### Steps to reproduce

1. Where are you starting? What can you see?
I've opened the new search modal.
2. What do you click?
I turn on the Public rooms filter
3. More steps…
I open the homeserver dropdown:
![image](https://user-images.githubusercontent.com/18530109/173350246-26555360-e6b4-4778-955c-c963073234f3.png)

#### What did you expect?
Right now, it's easier to tell what's going on in the Explore rooms modal:
![image](https://user-images.githubusercontent.com/18530109/173351117-b81532f0-7d75-420c-9b5b-9a2bc7438252.png)

#### What happened instead?
With the new design, my (and other community members') first attempt was to click on the homeserver name, only to find out it's not actually clickable.

### Operating system

Windows 11 Home 21H2

### Browser information

Firefox 101.0.1 (64-bit)

### URL for webapp

https://pr8707--matrix-react-sdk.netlify.app

### Application version

Element version: 2c0965c240c8-react-054a7488cbb9-js-aaf508e30941 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by niquewoodhouse** [comment]
it looks a bit like the margins aren't quite the same as originally intended in [figma](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=248%3A21210)

<img width="656" alt="image" src="https://user-images.githubusercontent.com/1587166/173633552-a1092f86-96bd-4b5b-9b99-6d75aef972b0.png">
