### ISSUE TITLE
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#22558]
### Steps to reproduce

Starting element-desktop -

Saw the following on the console - 

```
$ element-desktop
/home/shirish/.config/Element exists: no
/home/shirish/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
[1208960:0614/004141.153734:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[1208926:0614/004141.326165:ERROR:browser_main_loop.cc(267)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:87:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:100:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:99:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
 }
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
```
I have no clue from where it got en-gb as my locale, and even if it is, dunno why it was unable to find this :(

### Outcome

The above should not have come.

### Operating system

Debian Testing

### Application version

element-desktop 1.10.14

### How did you install the app?

https://packages.riot.im/debian default/main amd64 Packages

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Does this affect the client's operation at all? We don't have translations for en_GB, so this is an expected error.

**Comment by turt2live** [comment]
I would assume so, yes. It looks like you're on Debian Testing, so it could be pretty much anything that is causing the window to crash.

**Comment by shirishag75** [comment]
> I would assume so, yes. It looks like you're on Debian Testing, so it could be pretty much anything that is causing the window to crash.

True, but this is the only client that behaves like this. 

What I want to know which version of gtk it runs, I have 2, 3 as well 4.1 running on this system.

**Comment by turt2live** [comment]
I would suggest debugging this in the [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) room on Matrix, tbh. If it ends up being a true Element bug then happy to have an issue opened to fix it, but at the moment this really appears environmental. 

If the same issue happens on a stable Debian installation for instance then we might be able to investigate further ourselves.
