### ISSUE TITLE
"Error decrypting image" bubble should be styled

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22567]
### Steps to reproduce

1. Enable bubble layout
1. Send an image file to a room
2. Reload Element offline

#### What did you expect?

The error message should be styled properly.

#### What happened instead?

It is displayed as below.

![Untitled](https://user-images.githubusercontent.com/3362943/173580203-d04f80db-89a5-46f2-abe0-bf9ec47ff75e.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by turt2live** [comment]
is this with message bubbles?

**Comment by luixxiul** [comment]
Yes, they are. I am not sure how they are displayed on modern layout as the issue is no longer reproduced on my side.

**Comment by luixxiul** [comment]
I haven't seen the error for a while. Closing for now.
