### ISSUE TITLE
When creating a public space, server receives `visibility: private`

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#22578]
### Steps to reproduce

1. Create a public space
2. See the request to the server says `visibility: private`

#### What did you expect?

`visibility: public`

#### What happened instead?

![2022-06-14_20-26](https://user-images.githubusercontent.com/25768714/173662176-7962edb8-7d04-4faa-a723-0b66a554e196.png)

### Operating system

Not relevant

### Browser information

Not relevant

### URL for webapp

develop.element.io

### Application version

Element version: 6c375748576f-react-3c5c2bef6dba-js-eb8491c91bbc; Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is intentional due to the public rooms api not supporting spaces properly, should be capabilities gated at minimum

**Comment by t3chguy** [comment]
No it was a choice at the implementation time, same reason we don't expose the publish toggle switch
