### ISSUE TITLE
Bogus `updated` parameter in URL

### ISSUE THREAD

**Issue by xvitaly** [vector-im/element-web#22570]
### Steps to reproduce

1. Update to 1.10.15 from any previous.
2. Open `https://chat.example.org/` and it will always redirect to `https://chat.example.org/?updated=1.10.15`.

#### What did you expect?

It should not redirect to `$url/?updated=1.10.15`.

#### What happened instead?

Automatic redirect to `$url/?updated=1.10.15`. Removing `?updated=1.10.15` doesn't helps. It will add it again.

### Operating system

Fedora Linux

### Browser information

Mozilla Firefox 101.0.1

### URL for webapp

Version 1.10.15 from releases

### Application version

Element Web version: 1.10.15 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an active workaround for a Firefox bug.
https://github.com/vector-im/element-web/issues/9422
https://bugzilla.mozilla.org/show_bug.cgi?id=706970
