### ISSUE TITLE
Screensharing in video room crashes browser

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22573]
### Steps to reproduce

1. Join a video room, screenshare
2. Stop screensharing

#### What did you expect?
Browser doesn't crash

#### What happened instead?
Browser crashes on stopping screen sharing

### Browser information

Chromium 102.0.5005.61 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Yesterday's develop

**Comment by robintown** [comment]
@kittykat I can't reproduce this, if you still can, could you please send logs?

**Comment by robintown** [comment]
Closing due to lack of info
