### ISSUE TITLE
Video room in PIP mode shows me instead of the other person

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22574]
### Steps to reproduce

1. Join a call in a video room with one other person
2. Navigate to another room and look at the PIP

#### What did you expect?
I see the other person in the PIP view

#### What happened instead?
PIP shows my video stream

### Browser information

Chromium 102.0.5005.61 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
We should probably switch Jitsi from tile mode back to active speaker mode whenever it becomes a PiP
