### ISSUE TITLE
NVDA reads voice message clock as "Midnight" when it's 00:00

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22582]
Despite the `role=timer` added by https://github.com/matrix-org/matrix-react-sdk/pull/8843

It's unclear why NVDA might be doing this, or even if it's a problem.

**Comment by sameer-kumar-jain** [comment]
This is still an issue in 2023. Any update on this or any workaround?

**Comment by turt2live** [comment]
It appears to be NVDA-specific, unfortunately. If folks have ideas on how to fix it, please do share :D

**Comment by t3chguy** [comment]
Related https://stackoverflow.com/questions/48758106/how-do-i-indicate-to-a-screen-reader-that-a-time-is-hours-and-minutes-not-minut
