### ISSUE TITLE
Inserting emoji leaves a grey shape in the new composer

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22595]
### Steps to reproduce

https://user-images.githubusercontent.com/2803622/174064284-a0d27c59-616b-4678-a88e-c4c1611005cb.mp4

#### What happened instead?
grey shape (looks like a broken empty tooltip?) stuck in composer

### Operating system

arch

### Application version

Element Nightly version: 2022061501 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
That looks like a scrollbar and will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8840
