### ISSUE TITLE
Room retention parameter stopped working

### ISSUE THREAD

**Issue by FlanOfHarmony** [vector-im/element-web#22599]
### Steps to reproduce

Hopefully this is the right place to post my issue. I'm a simple user registered on the public servers of matrix.org, using Element as client (same for all the persons I talk to). 

In several rooms I'm in, I created room retention parameters with dev tools about ~a year ago. It seemed to work, after doing the tampering, messages older than the period I defined could not be loaded only cached ones remained. About 1-2 weeks ago, I was extremely disappointed to see that it was now possible to see all previouses messages, all the way back to at least ~6 months ago. I didn't go all the way back to the start because it's too much time consuming, but I guess that means no message has ever been deleted.

I know that room retention "isn't part of the Matrix specification yet", but I expected it to be implemented on matrix.org. By the way I saw that there has been [some developments](https://github.com/vector-im/element-web/issues/3800#issuecomment-1138270779)  room retention parameters. But if clients did not care about room retention before this, and messages never got deleted, why did it seem to work the way it was supposed to? I don't understand. 

When I do 'Open DevTools' -> 'Explore Room State' -> 'm.room.retention', my settings are still here:
```
"content": {
    "enabled": true,
    "expire_on_clients": true,
    "max_allowed_lifetime": 31104000000,
    "max_lifetime": 604800000,
    "min_allowed_lifetime": 0,
    "min_lifetime": 0
  },
  ...
  ```
  As can be seen, I even sent the event again with `"expire_on_clients": true,` just in case, cleared the cache: no effect.

#### What did you expect?
Messages older than specified duration getting deleted.
#### What happened instead?
Messages appeared to be deleted thanks to room retention parameters until 1-2 weeks when I was very unplesantly surprised to see they all came back. 

### Operating system

Fedora 36

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### How did you install the app?

From the now defunct element fedora taw copr build

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
I think this will be a Synapse issue of some kind. I have to admit though, I am surprised that we're using stable nemspaces for this feature given it's not even in the spec yet.

An issue at https://github.com/matrix-org/synapse would be appreciated.
