### ISSUE TITLE
Invited user joined the room before it was created.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#22596]
### Steps to reproduce

1. Created a private encrypted room
2. Invited a bunch of users to it
3. Sent about a page of scrollback
4. Closed laptop
5. Invited user joined the room and sent a message
6. Open laptop later
7. Discover join & message is shown in timeline *before* the creation of the room.

#### What did you expect?

Chronological timeline

#### What happened instead?

Causality nightmare

### Operating system

macOS 12

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment]
I'm struggling to understand this. I think a screenshot would be invaluable.

Given the lack of any updates in the last 12 months, it seems pretty unusual. I'm going to close it for now.
