### ISSUE TITLE
Not reverting back to light mode

### ISSUE THREAD

**Issue by thanasistrisp** [vector-im/element-web#22609]
### Steps to reproduce

When windows go back from dark mode to light mode (either manually or with third party app, e.g. auto dark mode app) it remains in dark mode and I need to exit the app and reopen it manually, while all other apps are reverting correctly. The inverse procedure (from light mode to dark mode) works correctly.

#### What did you expect?
To revert from dark mode to light mode correctly 
#### What happened instead?
It stays in dark mode

### Operating system

Windows 11

### Application version

Element Nightly: 0.0.1-nightly.2022061501

### How did you install the app?

From https://element.io/get-started#nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by florianduros** [comment]
After investigation, I notice this behavior:

In case of light theme previously selected:
- Element web is display => `theme-light.css` is loaded => light theme is applied
- I switch to dark => `theme-dark.css` is loaded => dark theme is applied
- I switch to light => `theme-light.css` is loaded => the dark theme is still effective and prevails on the light one
- I switch to dark => no loading of `theme-dark.css` => dark theme is applied
- I switch to light => `theme-light.css` is loaded => dark theme is still effective 

In case of dark theme previously selected:
- Element web is display => `theme-dark.css` is loaded => dark theme is applied
- I switch to light => `theme-light.css` is loaded => light theme is applied
- I switch to dark => `theme-dark.css` is loaded => dark theme is applied
- I switch to light => no loading of `theme-light.css` => light theme is applied
- I switch to dark => `theme-dark.css` is loaded => dark theme is applied

**Comment by florianduros** [comment]
The fix just landed on  the `react-sdk` `develop` branch.

**Comment by florianduros** [comment]
Yes, the fix will be available for the desktop app and the next nightly version is tomorrow at 8am UK time.
