### ISSUE TITLE
Waveform overflows from audio player

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22604]
### Steps to reproduce

1. Enable IRC layout and open the thread to reduce the width of the UI
2. Upload an audio file

#### What did you expect?

The waveform should not overflow.

![after](https://user-images.githubusercontent.com/3362943/174319899-02b38998-04ec-4c12-8c89-2f0776cefb67.png)

#### What happened instead?

It overflows. 

![before](https://user-images.githubusercontent.com/3362943/174319862-c01a7ccf-1d79-4593-a588-e120062ca3df.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by DoM1niC** [comment]
![grafik](https://user-images.githubusercontent.com/1436958/174325907-3b511885-419c-4a1b-93ad-35ade4b02108.png)
the Font-Size will do similar the same like your Issue

**Comment by luixxiul** [comment]
@DoM1niC Leider hier gibt es mir nix mehr zu tun weil das Design des Spielern von offiziellen Mitgliedern festgestellt und entwickelt werden soll.

**Comment by weeman1337** [comment]
> Leider hier gibt es mir nix mehr zu tun weil das Design des Spielern von offiziellen Mitgliedern festgestellt und entwickelt werden soll.

Translating: Nothing else to do here because these parts of the app should go through the design process.

@DoM1niC if you encounter any other issue can you please open an issue for that?

**Comment by DoM1niC** [comment]
In my case I merged his PR in my own Fork and all is fine 🙌🏻

**Comment by luixxiul** [comment]
@DoM1niC ah I understood what you have wanted to say :-D
