### ISSUE TITLE
room-switching performance has dropped again.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2261]
(worth noting that Firefox is empirically an order of magnitude worse than Chrome here -- @richvdh)

**Comment by ara4n** [comment]
This was partially due to little green men calculations, combined with how easy it is to expand out the various sublists these days.  Something else is going wrong though - we shouldn't be rerendering the whole RoomList in the first place when changing room given we're just changing a highlight...

**Comment by richvdh** [comment]
ftr, we've always rerendered the roomlist on room switch (or at least, we did when I last looked at performance about 6 months ago). I hacked up a build which didn't have a roomlist at all and it didn't feel materially quicker, so I didn't bother trying to optimise it further.

**Comment by turt2live** [comment]
This is largely resolved with the new room list, I think. If it's not then a new issue with fresh reports would be appreciated.
