### ISSUE TITLE
Video rooms beta pill is shown on space invites

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22619]
### Steps to reproduce

Receive an invite to a space

#### What did you expect?

No beta pill, since spaces are not in beta

#### What happened instead?

There is a beta pill with the tooltip "Video rooms are a beta feature".

![Screenshot 2022-06-19 at 10-01-38 Element 1 My space](https://user-images.githubusercontent.com/48614497/174485147-a08a2968-903a-4a92-924a-1ab11b880550.png)

### Operating system

NixOS unstable

### Browser information

Firefox 101.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 7a131fc50f09-react-cfbe1cb06669-js-fc946ab0fa15 Olm version: 3.2.8

### Homeserver

Synapse 1.61.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8872; CC @luixxiul
