### ISSUE TITLE
Beta pill on video room invites is in the wrong place

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22620]
### Steps to reproduce

Receive an invite to a video room from someone with a short name

#### What did you expect?

The beta pill should be in the top right corner

#### What happened instead?

It's directly to the right of the inviter's name

![Screenshot 2022-06-19 at 10-02-20 Element 2 Robin's video room 2](https://user-images.githubusercontent.com/48614497/174485118-a5f28b94-0191-43e1-8598-fa1215bc0512.png)

### Operating system

NixOS unstable

### Browser information

Firefox 101.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 7a131fc50f09-react-cfbe1cb06669-js-fc946ab0fa15 Olm version: 3.2.8

### Homeserver

Synapse 1.61.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8872; CC @luixxiul
