### ISSUE TITLE
Remove Keyboard Shortcuts button from Help & About -> FAQ

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22625]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/2803622/174626477-0e292ff2-9f07-4652-a11e-2cf72a1c154a.png)

oversight when kb got its own settings tab.

### Outcome

n/a

### Application version

Element Nightly version: 2022061501 Olm version: 3.2.8

### Will you send logs?

No

**Comment by gefgu** [comment]
I would like to work on this issue :)
