### ISSUE TITLE
"Reject" button on room preview card needs clickable area indication

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22623]
### Steps to reproduce

1. Be invited to Space (or create a test user to invite)

#### What did you expect?

`Reject` button needs some kind of indication about clickable area (with border around it for example).

#### What happened instead?

It is not clear where is clickable around the label itself.

![before](https://user-images.githubusercontent.com/3362943/174524232-88f4505e-7862-4e62-96c5-8e29e2dc24ff.png)

![before1](https://user-images.githubusercontent.com/3362943/174524254-73ac0f27-6e41-4135-be01-d082c8409436.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### Will you send logs?

No

**Comment by nawarajshah** [comment]
i would like to work on this issue, assign it to me
and can you tell me what border color you would like in the reject button?

**Comment by SAGARGAUD01** [comment]
Hello I want to work on this, can you please give me hint about what is the keyword that can be search in codebase to get that exact code template where I need to perform changes.
