### ISSUE TITLE
ability to list all your verified e2e keys in one place so you can curate them better

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2263]

**Comment by Fidgetcetera** [comment]
Noting that this would be great, and that the "security and privacy" settings menu's list of session IDs would be a great place to be able to click a "show session key to share" type of button.

**Comment by kittykat** [comment]
@ara4n do you mean keys from verifying other users?

**Comment by turt2live** [comment]
Closing as it's unclear what this is asking for specifically. If this is still an issue, please add more detail and reopen or open a new issue.
