### ISSUE TITLE
Hyphen should not affect how IDs on view source dialog should be wrapped

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22636]
### Steps to reproduce

1. Open a room
3. View source of a message

#### What did you expect?

Hyphen should not affect how IDs on view source dialog should be wrapped.

![after (copy 1)](https://user-images.githubusercontent.com/3362943/175240039-458d30e9-7a53-4e38-a7ea-343901daad11.png)|

#### What happened instead?

The event ID is not properly wrapped due to a hyphen in it.

![before (copy 1)](https://user-images.githubusercontent.com/3362943/175240070-6c5989e3-4f39-4470-8e20-8be43ace7eb1.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
Related #21937
