### ISSUE TITLE
Reactions are misaligned in IRC layout

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#22644]
### Steps to reproduce

1. Switch to IRC Layout
2. Add a reaction to a message
3. It's misaligned:

![image](https://user-images.githubusercontent.com/62639087/175575409-0a19a937-7ec4-4c1b-8c56-77edf3f34262.png)

In modern layout, it is aligned with the start of the message:

![image](https://user-images.githubusercontent.com/62639087/175575602-bf121013-f751-410d-a88b-203806b2a225.png)

#### What did you expect?

The reaction to be aligned similar to modern layout.

#### What happened instead?

Weird space

### Operating system

Arch Linux

### Browser information

Firefox 103

### URL for webapp

https://develop.element.io

### Application version

Element version: 659f41482b05-react-663bca559f7c-js-58227307974a Olm version: 3.2.8

### Will you send logs?

No

**Comment by bbhtt** [comment]
Probably from https://github.com/matrix-org/matrix-react-sdk/pull/8813

**Comment by luixxiul** [comment]
This should be fixed with https://github.com/matrix-org/matrix-react-sdk/pull/8858
