### ISSUE TITLE
Clicking on a room pill opens matrix.to in a new tab

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#22653]
### Steps to reproduce

1. Click on a room pill, like the one in this message:

![image](https://user-images.githubusercontent.com/5547783/175908214-49989754-c37f-4d8d-897b-623933a85dd4.png)

#### What did you expect?

Element switches to the room linked in the pill (in this case a room I'm already in)

#### What happened instead?

Element opened a new tab on matrix.to

### Operating system

Arch Linux

### Browser information

Firefox 101.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 9eda502a9bce-react-e7a8dbd04cc0-js-9b7628c10313, olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
release blocker because this is a regression that shouldn't happen
