### ISSUE TITLE
Invite dialog changes height as suggestions change

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22659]
### Steps to reproduce

1. Open an invite dialog
2. Type someone's name in

#### What did you expect?

The dialog should remain a constant height.

#### What happened instead?

The dialog changes height distractingly as the suggestions list gets shorter/longer.

### Operating system

NixOS unstable

### Browser information

Firefox 101.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 9eda502a9bce-react-a9a97d1be38c-js-9b7628c10313 Olm version: 3.2.8

### Homeserver

Synapse 1.61.0

### Will you send logs?

No

**Comment by weeman1337** [comment]
Caused by this commit https://github.com/matrix-org/matrix-react-sdk/commit/a74b9a70836b97b5a05a18c8e7ed2d7dcd9d8b7e#diff-b725c545a7edd5a6aef3688ab33206236523ece3500ddc32e1a827f5b5735442
