### ISSUE TITLE
Spinner shown when expanding Historical sublist has disappeared

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2265]

**Comment by wmwragg** [comment]
This still works for me on /develop, I have noticed that it occasionally doesn't show, but no more than it used to, perhaps 1 in 10.

**Comment by lukebarnard1** [comment]
This is probably because opening the sub list doesn't trigger a scroll to the bottom (which would reveal a hidden spinner).

**Comment by t3chguy** [comment]
We got rid of this - closing in favour of https://github.com/vector-im/element-web/issues/14038
