### ISSUE TITLE
Incomplete sentence on inaccessible room preview message

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22661]
### Steps to reproduce

1. Disable network connection
2. Open a room outside of your homeserver

#### What did you expect?

The message on the preview message should be complete.

#### What happened instead?

It is not clear what `was returned while trying to access the room or space`.

![before](https://user-images.githubusercontent.com/3362943/175988338-bca9903a-a30d-4dcb-b958-440300058d16.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

localhost

### Application version

develop branch

### Will you send logs?

No

**Comment by t3chguy** [comment]
There should be an error code before it but it is empty

**Comment by luixxiul** [comment]
I haven't seen this for a while. Closing for now.
