### ISSUE TITLE
Font color of MessageTimestamp different between main timeline and right panel (TimelineCard, ThreadView, ThreadPanel)

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22699]
### Steps to reproduce

1. Compare timestamp font color on the main timeline and the right panel

#### What did you expect?

The color should be consistent.

#### What happened instead?

The font color of the timestamp on right panel (ThreadsList, ThreadView, *and* TimelineCard) has been specified on [this line](https://github.com/matrix-org/matrix-react-sdk/commit/544957bdad5b0207e0ca747e6cea1b476fd73d39#diff-f6d1464858812e6ea15c65a49935a089650e5e7adc0a380eeabfce5da896aa67R192) based on https://github.com/vector-im/element-web/issues/19669.

|Main timeline|Right panel|
|------------------|---------------|
|![before2](https://user-images.githubusercontent.com/3362943/176690474-8af6b0b2-193b-4502-839f-c4e336a843d2.png)|![before1](https://user-images.githubusercontent.com/3362943/176690448-bfa8bae5-a969-449f-81ff-fce0238fad5a.png)|
|↑ Inherited from the default value|↑ Specified on on [this line](https://github.com/matrix-org/matrix-react-sdk/commit/544957bdad5b0207e0ca747e6cea1b476fd73d39#diff-f6d1464858812e6ea15c65a49935a089650e5e7adc0a380eeabfce5da896aa67R192)|

Probably should the default color be replaced?

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by turt2live** [comment]
Let's converge on the colour from the main timeline.

**Comment by luixxiul** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/10016 seems to have fixed the issue. There should be a percy test about possible color change due to cascading. going to work on it..
