### ISSUE TITLE
HTML Rendering in Space description threw fatal error

### ISSUE THREAD

**Issue by williamkray** [vector-im/element-web#22691]
### Steps to reproduce

Discovered as part of the User Experience Testing session started 06/29/2022

1. use develop.element.io
2. enable HTML rendering in room topics lab feature
3. create Space, put the following in the description of the space at creation time:
```
[link me](https://element.io) takes you to https://element.io
🪦
<del>_this is italic_ & **this is bold**</del> blah blah blah H<sub>2</sub>0 is <sup>water</sup>

`this is _a code_ **block** <sub>hello</sub><sup>there</sup>`

```
hello
    there
```

>this is a quote
>it is multiple lines

this is no longer a quote

- this is a list
- more things

<a href="https://google.com">this shouldn't also be a link</a>
```
4. space will be created, but description will not render markdown as HTML
5. edit space description by adding a single space to beginning of the description

#### What did you expect?
Description would be updated and render HTML properly (this is current behavior for room topics)

#### What happened instead?
Element threw an error and prompted me to send debug logs, but first I had to create this github issue.

### Operating system

Arch Linux

### Browser information

Firefox 101.0

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by williamkray** [comment]
clearing the app cache and reloading renders the topic as expected.

**Comment by t3chguy** [comment]
This got fixed by switching to `linkify-react`
