### ISSUE TITLE
Connectivity to the server has been lost.

### ISSUE THREAD

**Issue by wildcard-f8** [vector-im/element-web#22707]
### Steps to reproduce

1. Open app
2. See an error message: Connectivity to the server has been lost. Sent messages will be stored until your connection has returned.
3. ?

#### What did you expect?
I expect to be able to communicate with my team.

#### What happened instead?
We're forced to use another communication service.

### Operating system

Manjaro linux

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

Majaro official repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Thanks for the debug logs. Looks like your homeserver was unavailable for a bit, so this isn't an element bug. If it continues to be a problem you could contact your homeserver admin.
