### ISSUE TITLE
'Start chat' from MemberInfo opens rooms with declined invites; should re-invite instead.

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2272]
I invited someone to chat via the member info. They declined. I started a chat from start chat button, invited the same user, our 1:1 opened, but as if i had opened the room from the directory: last thing happening there was the other guy decliningthe invite, the new invite wasn't triggered. I then invited via the invite button from the room and it worked. I guess start chat should propose me to open the existing one or create a new one, and until it is implemented it should probably at least trigger a reinvite. Expected behaviour can be discussed depending on the status of implementation

**Comment by weeman1337** [comment]
Tested via the invite dialog and the a room member list:
Element Web creates a new DM if the invited user rejects the invite.
