### ISSUE TITLE
Can't use a custom font

### ISSUE THREAD

**Issue by avfigueredo** [vector-im/element-web#22724]
### Steps to reproduce

I'm trying to install a custom font, but for some reason, the app isn't loading my font.

My config.json

`
"fonts": {
          "faces": [
            {
              "font-family": "Open Sans",
              "src": [{"url": "/fonts/Open_Sans.ttf", "format": "ttf"}]
            }
          ],
          "general": "Open Sans, regular",
          "monospace": "Open Sans, regular"
        },
`

I've moved the font files to inside the container. 

<img width="965" alt="Screen Shot 2022-07-04 at 10 06 46" src="https://user-images.githubusercontent.com/8737136/177122332-b3a41dd4-2a73-4c96-891b-87750474d791.png">

<img width="1204" alt="Screen Shot 2022-07-04 at 10 06 58" src="https://user-images.githubusercontent.com/8737136/177122349-da821514-22bd-4ef8-9a3f-f07758237b3c.png">

But the app is still loading the default font. 

<img width="761" alt="Screen Shot 2022-07-04 at 09 32 18" src="https://user-images.githubusercontent.com/8737136/177122527-06747a31-c1b1-44b6-b972-06266c293adf.png">

#### What did you expect?

Use custom font.

#### What happened instead?

The custom font wasn't loaded, instead, the app continue to load the default font. 

### Operating system

Ubuntu 20

### Browser information

Safari, Brave, Chrome

### URL for webapp

It's a private server, running the latest version

### Application version

Version Element: ba38b73a1550-react-ba38b73a1550-js-ba38b73a1550 Version Olm: 3.2.8

### Homeserver

Synapse 

### Will you send logs?

No

**Comment by bwindels** [comment]
If you put the `fonts` section as a root entry in your config file, this isn't going to work. You have to define a custom theme, wherein you can put a fonts section, see https://github.com/vector-im/element-web/blob/develop/docs/theming.md#custom-themes

Could you provide your full config (with redacted values if needed) if this isn't the case?

**Comment by avfigueredo** [comment]
> If you put the `fonts` section as a root entry in your config file, this isn't going to work. You have to define a custom theme, wherein you can put a fonts section, see https://github.com/vector-im/element-web/blob/develop/docs/theming.md#custom-themes
> 
> Could you provide your full config (with redacted values if needed) if this isn't the case?

@bwindels Thanks, I've followed this tutorial, and here is my config.json. I've created a Dockerfile to move the font files to inside the container.  The colours are applied correctly, just the font doesn't  work. 

`{
  "default_server_config": {
    "m.homeserver": {
      "base_url": "http://myserver.com",
      "server_name": "myserver.com"
    },
    "m.identity_server": {
      "base_url": "https://vector.im"
    }
  },
  "disable_custom_urls": true,
  "disable_guests": false,
  "disable_login_language_selector": false,
  "disable_3pid_login": false,
  "brand": "App",
  "integrations_ui_url": "https://scalar.vector.im/",
  "integrations_rest_url": "https://scalar.vector.im/api",
  "integrations_widgets_urls": [
    "https://scalar.vector.im/_matrix/integrations/v1",
    "https://scalar.vector.im/api",
    "https://scalar-staging.vector.im/_matrix/integrations/v1",
    "https://scalar-staging.vector.im/api",
    "https://scalar-staging.riot.im/scalar/api"
  ],
  "bug_report_endpoint_url": "https://element.io/bugreports/submit",
  "uisi_autorageshake_app": "element-auto-uisi",
  "default_country_code": "DE",
  "show_labs_settings": false,
  "features": {},
  "default_federate": true,
  "default_theme": "custom-app",
  "room_directory": {
    "servers": [
      "matrix.org"
    ]
  },
  "piwik": {
    "url": "https://piwik.riot.im/",
    "whitelisted_hs_urls": [
      "https://matrix.org"
    ],
    "whitelisted_is_urls": [
      "https://vector.im",
      "https://matrix.org"
    ],
    "siteId": 1
  },
  "enable_presence_by_hs_url": {
    "https://matrix.org": false,
    "https://matrix-client.matrix.org": false
  },
  "setting_defaults": {
    "breadcrumbs": true,
    "UIFeature.deactivate": false,
    "UIFeature.registration": false,
    "UIFeature.passwordReset": false,
    "showCallButtonsInComposer": false,
    "language": "de",
    "custom_themes": [
      {
        "name": "app",
        "is_dark": false,
        "fonts": {
          "faces": [
            {
              "font-family": "Open Sans",
              "src": [{"url": "/fonts/Open_Sans.ttf", "format": "ttf"}]
            }
          ],
          "general": "Open Sans, regular",
          "monospace": "Open Sans, regular"
        },
        "colors": {
          "accent-color": "#DD91A3",
          "warning-color": "#FAC826",
          "sidebar-color": "#DFE3E6",
          "roomlist-background-color": "#F5F7FA",
          "roomlist-text-color": "#EA4692",
          "roomlist-text-secondary-color": "#ab0050",
          "roomlist-highlights-color": "#ffffff",
          "roomlist-separator-color": "#e3e8f0",
          "timeline-background-color": "#ffffff",
          "timeline-text-color": "#2e2f32",
          "timeline-text-secondary-color": "#61708b",
          "timeline-highlights-color": "#F5F7FA",
          "username-colors": ["#A0A0C0"],
          "avatar-background-colors": ["#dd91a3"]
        }
      }
    ]
  },
  "jitsi": {
    "preferred_domain": "meet.element.io"
  },
  "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
`

**Comment by avfigueredo** [comment]
@t3chguy There aren't errors in the console. I was looking here, and the files aren't loaded on the page. When I try to access the files via browser, they don't open/exist. But, for example, the default font can be opened. 

<img width="1437" alt="Screen Shot 2022-07-04 at 14 21 13" src="https://user-images.githubusercontent.com/8737136/177166010-d08b1ba1-d43c-40dc-8601-e3f377b0788b.png">

<img width="804" alt="Screen Shot 2022-07-04 at 14 21 32" src="https://user-images.githubusercontent.com/8737136/177166042-ca17d483-b4b2-4369-be06-caf9e7ced7dc.png">

<img width="649" alt="Screen Shot 2022-07-04 at 14 23 19" src="https://user-images.githubusercontent.com/8737136/177166070-15d54fb1-1680-4359-958d-1ac16c4c76b3.png">

<img width="1440" alt="Screen Shot 2022-07-04 at 14 28 43" src="https://user-images.githubusercontent.com/8737136/177166089-d2a817bc-ebeb-4277-86f2-1d110b3449f7.png">

<img width="1440" alt="Screen Shot 2022-07-04 at 14 34 27" src="https://user-images.githubusercontent.com/8737136/177166136-a219b977-5d8c-42bc-805f-6bed0da49381.png">

<img width="1195" alt="Screen Shot 2022-07-04 at 14 31 22" src="https://user-images.githubusercontent.com/8737136/177166155-3798c959-d304-4789-aa61-059b6cb7fc64.png">

**Comment by t3chguy** [comment]
The directory permissions are wrong.

![image](https://user-images.githubusercontent.com/2403652/177167790-19ace791-2f19-4cb5-a632-930bdb7199ec.png)

That directory can only be read and opened by root (+rx)

**Comment by avfigueredo** [comment]
Hello guys, any idea about why this is happening?

**Comment by Johennes** [comment]
@avfigueredo are you still facing this problem?

**Comment by daniellekirkwood** [comment]
No response, closing for now. Re-open if needed
