### ISSUE TITLE
Tweak 'Create video room' modal to make e2e clearer

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#22737]
### Your use case

<img width="623" alt="Screenshot 2022-07-05 at 14 37 28" src="https://user-images.githubusercontent.com/4626865/177340960-44515241-5d7f-4131-b839-ad37241ce6e0.png">

In the modal above, encryption is enabled in the Matrix room but not in the embedded Jitsi widget. Given that Video Rooms are centred on the video mechanic, I think we should tweak the copy to something like:

> You can't disable this later. The room will be end-to-end encrypted but the embedded call is not.

Wdyt @robintown @gaelledel? Is there anywhere else while participating in an encrypted video room we might want to add more UX copy?

**Comment by gaelledel** [comment]
All good for me unless @robintown you think anything might be missing from Nad's copy tweak?

**Comment by robintown** [comment]
Looks good to me as well
