### ISSUE TITLE
"Ctrl-K" is displayed instead of the room search icon when the room list is minimized

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#22739]
### Steps to reproduce

* Shrink the room list panel.
* Look at the room search field.

#### What did you expect?

To see a :mag_right: icon.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1342360/177358255-39d5ec5b-5567-4152-a64a-264bd2e9dbb5.png)

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022070501, Olm version: 3.2.8

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by voice06** [comment]
Seeing it on Linux Mint as well, installed from the Element repo, https://packages.riot.im/debian/
Element version: 1.11.0
Olm version: 3.2.8

![image](https://user-images.githubusercontent.com/4512200/177370442-67183444-cc3c-46a2-951c-76a6b2635a59.png)
![image](https://user-images.githubusercontent.com/4512200/177370463-cc7e8324-5426-4df7-b491-4dbeac0ab8c8.png)
