### ISSUE TITLE
mouse hover over room icons leads to mouse blinking, unresponsiveness, high CPU

### ISSUE THREAD

**Issue by gerbrent** [vector-im/element-web#22742]
### Steps to reproduce

mouse hover over room icons leads to mouse blinking, unresponsiveness, high CPU

## Steps to reproduce
* application window is in "half screen" mode, i.e. the compressed room names to icons only, etc.
* hover mouse over rooms icons: works as expected to present "alt text" of room name
* resize application window
* hover mouse over rooms icons, esp the corner of the icon near the room scroll bar
* mouse pointer flickers between standard pointer and hand-pointing states endlessly
* application becomes unresponsive, high CPU usage, must force kill application.

![Peek 2022-07-05 22-39](https://user-images.githubusercontent.com/7018928/177475098-a70d37f8-d25c-43a4-89ff-94e572b783fb.gif)

CPU usage *after* mouse hover bug encountered:
![Peek 2022-07-05 22-45](https://user-images.githubusercontent.com/7018928/177475103-df3e4e6d-ae9e-4441-9df7-a07d70990b56.gif)
**note:** htop/cpu usage screenshot taken *after* unresponsive UI, not during above mouse exploration process.

## Additional System Info:
OS: Fedora Linux 36 (KDE Plasma) x86_64 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.24.5 
WM: KWin 

## bug logs
* [element-bug.log](https://github.com/vector-im/element-web/files/9051975/element-bug.log)
   * these error messages appear via terminal output at launch-time, *before* the above described mouse hover bug, thus may not be related. However have been included here if helpful. Recorded via command `flatpak -vv run im.riot.Riot &> element-bug.log`
   
* in-app bug reporting
   * could not initiate in-app debug logs reporting *after* above bug, since application becomes unresponsive. Therefore, this in-app debug logs report is recorded *before* the above bug occurs.

#### What did you expect?
* hover mouse over rooms icons: works as expected to present "alt text" of room name

#### What happened instead?
* mouse pointer flickers between standard pointer and hand-pointing states endlessly
* application becomes unresponsive, high CPU usage, must force kill application.

### Operating system

Fedora Linux 36 (KDE Plasma) x86_64

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

flatpak via flathub

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@gerbrent this was fixed in 1.11.0
