### ISSUE TITLE
Sync labs right click message context menu options with current context menu

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22745]
### Steps to reproduce

1. enable right click menu in labs
2. right click

![image](https://user-images.githubusercontent.com/2803622/177495988-2b425e23-a8e1-4f53-a012-14878e7682e5.png)

#### What did you expect?
same options in right click and hover context menus
#### What happened instead?
labs right click has copy link but no thread, while hover context menu has thread but no copy link

### Operating system

arch

### Application version

Element Nightly version: 2022070501 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
We will want to add a thread button to the context menu but not a copy button to the options since copy is a thing that would be typically done using right-click

@vector-im/design, would you agree?

**Comment by HarHarLinks** [comment]
> since copy is a thing that would be typically done using right-click

I don't really follow the reasoning. I don't see why someone that prefers to use the hover menu (assuming it's sticking around) over right clicking (e.g. touch pad user) should not have the ability to copy.

That said, the copy option is just a short cut to selecting "Share" and clicking copy in the share modal in the first place, which I don't entirely understand either.

**Comment by SimonBrandner** [comment]
The copy link button is probably does something other than you think: it only shows up if you're clicking either the timestamp (in which case it copies a link to the message) or if you click a hyperlink inside the message (in which case it copies the link)

**Comment by HarHarLinks** [comment]
> if you're clicking either the timestamp

this appears to be the case in Element version: 1.11.0 for windows 10, but with the nightly on linux i got it by clicking anywhere inside the message body as well (see above screenshot though admittedly it's a bit cropped). this is the same as selecting share for a selected message and then copying the matrix.to url with the checkbox "Link to selected message" enabled.

**Comment by SimonBrandner** [comment]
![2022-07-07_09-27](https://user-images.githubusercontent.com/25768714/177716635-a6b15e94-c8ad-44d8-a789-96f20e15649a.png)

I cannot reproduce that; is there any chance you're clicking a reply (those are technically links)?

**Comment by HarHarLinks** [comment]
I've updated to 220707, it now works as you describe.
