### ISSUE TITLE
WebP avatar breaks

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#22753]
### Steps to reproduce

1. Go to All Settings - General
2. Change profile picture
3. Select any WebP image you have previously stored
4. Press the Save button

[Here's one](https://github.com/vector-im/element-web/files/9056636/313c7luie6f61.zip) for your convenience (zipped, because Github doesn't understand modern formats either) but any other will do.

#### What did you expect?
Profile picture is set to uploaded picture

#### What happened instead?
Profile picture looks good at first, but after pressing the Save button, it becomes a "broken image".
Closing All Settings makes the profile picture revert to the default (user initials).

### Operating system

Windows 10 21H2

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
Sounds like it could be an issue of synapse understanding webp?
I don't think webp are properly supported by the matrix ecosystem/in general. I've heard reports of webm not working on iOS, likely webp is the same.

**Comment by thany** [comment]
> I don't think webp are properly supported by the matrix ecosystem/in general. I've heard reports of webm not working on iOS, likely webp is the same.

Then why is the settings panel allowing me to select one?

I'm not saying disallow WebP, mind you. It just illustrates a lack of communication between UI design, and technical implementation, doesn't it.

**Comment by HarHarLinks** [comment]
Yes, your argument is totally valid. It boils down to the issue that there is no clear definition of what media types a client and server must support to properly comply to the matrix protocol. This issue to my knowledge is tracked at https://github.com/matrix-org/matrix-spec/issues/453. There appears to possibly additionally be miscommunication between Element and Synapse which is tracked at https://github.com/vector-im/element-web/issues/3563, however in the end I think it boils down to the aforementioned missing definition in the spec.

There is no base for Element to decide whether it should dis/allow you selecting this webp, .
Hence currently everything operates on the base of "I support this format, so I'm assuming everyone else does, too", which leads to the common-ish webm problem I described.

**Comment by t3chguy** [comment]
> Seems pretty simple to me.

Except it is different for each Matrix server, depending on their HS/Media implementation

**Comment by thany** [comment]
Why is the server involved at all? The way I see it, avater is a plain uploaded file, that happens to be an image. The client just displays it. I don't see why the server has to care what type of image it is. All it needs to care about is, that it's not exceeding some arbitrary file size limit, which is unlikely for an avatar.
