### ISSUE TITLE
Textual events not correctly positioned in modern layout

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22759]
### Steps to reproduce

1. Be sure modern layout is active
2. Add a custom widget to a room
3. Look at the timeline

#### What did you expect?

„Widget added…“ correctly aligned

#### What happened instead?

„Widget added…“ not correctly aligned

![image](https://user-images.githubusercontent.com/6216686/177721563-eecb5d5e-f0e1-477b-9cab-8f39e38632b2.png)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 102.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: 688dbc6cbab6-react-58b81f604adb-js-685cab38b9b9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/5349f301da19b72dbc275d003fd25bc2dd985769

**Comment by luixxiul** [comment]
Should be fixed with https://github.com/matrix-org/matrix-react-sdk/pull/8994
