### ISSUE TITLE
URL tooltips disable URL preview

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22764]
### Steps to reproduce

Since https://github.com/vector-im/element-web/issues/6532 links with custom text do now show the target URL in a tooltip when hovering the mouse over them. However such links now don't produce URL previews anymore.

#### What did you expect?
(option to) get URL previews in the TL
#### What happened instead?
no URL previews

### Operating system

arch

### Application version

Element Nightly version: 2022070701 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by Johennes** [comment]
Hm, it looks like the rendering of `LinkWithTooltip` hasn't finished by the time `calculateUrlPreview` is called so the span is empty when we search for anchors. 🤔

**Comment by Johennes** [comment]
So what I _could_ do to fix it is add a callback invoking `calculateUrlPreview` to the props of `LinkWithTooltip` and call it in `componentDidMount` / `componentDidUpdate`.

Not sure if that's a great solution though. @t3chguy WDYT?

**Comment by t3chguy** [comment]
@Johennes can we not just swap the calls of `tooltipifyLinks` and `calculateUrlPreview` so that we scrape the URLs out before tooltipification which is racey?

**Comment by Johennes** [comment]
Aaaand that's why I knew it'd be good to ask for your input. 😅

I'll send a PR.
