### ISSUE TITLE
Some spaces and rooms disappeared from UI after upgrading element-develop

### ISSUE THREAD

**Issue by mnaturel** [vector-im/element-web#22761]
### Steps to reproduce

I was using the element-develop web environment in Firefox. 
On the 6th July 2022, there was a invitation to upgrade Element Web.
I clicked on it to upgrade.

#### What did you expect?
The upgrade should have happened correctly.

#### What happened instead?
After upgrade, it seems my data was kind of corrupted. Some of my spaces (3/5) and rooms disappeared from the UI.

To fix this what I did is signin+verification in another browser (Safari) then signout from Firefox and signin+verification again in Firefox. And all went back to normal.

### Operating system

MacOS Monterey

### Browser information

Firefox 102.0 (64 bits)

### URL for webapp

develop.element.io

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@mnaturel are you still experiencing this with 1.11.4?

**Comment by t3chguy** [comment]
Closing as presumed fixed, do shout if you see it recur - thanks!
