### ISSUE TITLE
Docker containers should be cleaned up after exiting cypress

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22762]
### Steps to reproduce

1. Open a shell
2. Run some tests, e.g. `./node_modules/.bin/cypress run --headed --no-exit --spec ./cypress/integration/12-spotlight/spotlight.spec.ts `
3. Wait that a test spins up a synapse container
4. Close the test window
5. Stop Cypress by `Ctrl + C`

#### What did you expect?

Docker container stopped and removed

#### What happened instead?

Docker container still hanging around

### Operating system

Ubuntu 22.04 LTS

### Will you send logs?

No

**Comment by weeman1337** [comment]
Doesn't look that easy to do something on exiting a Node process.

**Comment by turt2live** [comment]
we do try and clean up the containers within the test execution, but interrupting that execution means the container survives. Could be fixed with `--rm` if we could enable it :(
