### ISSUE TITLE
Unsent messages notification pointing to nowhere

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22763]
### Steps to reproduce

1. Just using Element Desktop
2. At some point a „Some messages didn't send. Click for info" appeared
3. Clicking it doesn't do anything

#### What did you expect?

- It should not be there
- It should lead to the unsent message

#### What happened instead?

- The „notification“ hangs around

![image](https://user-images.githubusercontent.com/6216686/177729962-adc94534-be5b-4c8a-bcbb-98f878929523.png)

### Operating system

Ubuntu 22.04 LTS

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

deb

### Will you send logs?

Yes

**Comment by aaronraimist** [comment]
This could be the same as https://github.com/vector-im/element-web/issues/9692.

I experienced this bug this a few times recently and when I investigated today's occurrence it seemed to be a reaction that had failed to send.

**Comment by weeman1337** [comment]
Cannot reproduce any more
