### ISSUE TITLE
Remove community linkification from composer/timeline

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22770]
#### What would you like to do?
![image](https://user-images.githubusercontent.com/2803622/177813984-4e8807e0-de2a-473d-92e6-d5fd9a2211da.png)

`+11:30` gets turned into a community link by the TL renderer to https://matrix.to/#/+11:30 where
- `+` qualifies it as community
- `11` is the community id
- `:` is the server separator token
- `30` is the server, albeit no FQDN

#### Why would you like to do it?

since communities have been removed, this should go, too.

additionally, this shouldn't be turned into a community link in the first place due to missing whitespace around it.

**Comment by turt2live** [comment]
this is a feature to inform users that communities are dead and they should move to spaces. Once design/product are comfortable with moving ahead on removing this linkification, we can do that.

**Comment by kittykat** [comment]
I think we can go ahead and do that now as communities have been deprecated for a while
