### ISSUE TITLE
'Upgrade to Element Home' popup appears off screen

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22778]
### Steps to reproduce

1. Click „Upgrade to Element Home“ in the user menu

#### What did you expect?

Seeing the popup

#### What happened instead?

The popup goes off screen

![upgrade](https://user-images.githubusercontent.com/6216686/177933191-22f42155-8667-41b3-851f-218b4380ff43.gif)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 102.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: a4f9e7adad81-react-bd8949872df1-js-685cab38b9b9 Olm version: 3.2.8

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed in v1.11.0 by https://github.com/matrix-org/matrix-react-sdk/commit/a85799b87c374fe8dd61ed8dcb4c6e02d8a32a26
