### ISSUE TITLE
Scalar or Bots should politely refuse to participate in E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2277]

**Comment by lampholder** [comment]
As per #4066 the current behaviour provides a very confusing user experience.

**Comment by Half-Shot** [comment]
Also, if a room is encrypted after it has been plumbed/a bot has been added then I'd like for Riot to warn the user that it will break bots.

**Comment by turt2live** [comment]
closing in favour of backlinked internal issue.
