### ISSUE TITLE
Unable join a room I've been invited to

### ISSUE THREAD

**Issue by omame** [vector-im/element-web#22784]
### Steps to reproduce

1. Accept the invitation
2. New room opens and starts loading

#### What did you expect?
Room finishes loading and I join

#### What happened instead?
Room never stops loading

### Operating system

MacOS, Android (Element and Fluffychat apps)

### Browser information

Chromium version 103.0.5060.114

### URL for webapp

app.element.io

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by omame** [comment]
Here's a fun turn of events.

It turns out that I did indeed join the room (currently chatting on it) but the history never loads. This, according to @timokoesters, is due to lack of support in conduit. Thing is, my client shouldn't forever attempt to retrieve it but show an error instead.

**Comment by timokoesters** [comment]
@t3chguy In this case, Element was talking to a normal Synapse, that fulfills all requirements, but that Synapse was federating with a Conduit.

I think an appropriate solution would be for Element to stop requesting history if it still errors after multiple tries. Maybe additionally Synapse should do exponential backoff on /backfill.

**Comment by omame** [comment]
If anything, throwing an error to the user rather than spinning forever would be an UX improvement.

**Comment by t3chguy** [comment]
@omame the issue says "Unable to join" - but @timokoesters is talking about history backfill. Which happened? Were you able to join or not?

**Comment by omame** [comment]
[I did](https://github.com/vector-im/element-web/issues/22784#issuecomment-1179496982).

**Comment by omame** [comment]
I think we can close this. It happened 2 months ago today and I never experienced the issue again ever since. This because I never joined another room federated with Conduit.

So the problem, as @timokoesters pointed out, it's in the way Element and Conduit talk to each other.

As for my problem, I consider it to be expected behaviour based on the above. Thus, I'm closing this but feel free to reference it in a more generic issue to address the problem.

**Comment by t3chguy** [comment]
> it's in the way Element and Conduit talk to each other.

Element wasn't talking to Conduit, the federation happens between servers.
