### ISSUE TITLE
The green left stroke on the event tile being edited is hidden with the message editor on IRC layout

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22785]
### Steps to reproduce

1. Enable IRC layout
2. Open a room
3. Send a message
4. Edit the message

#### What did you expect?

The green left stroke should not be hidden by the message editor. The editor should also have 3px padding, the default value of the editor.

![after](https://user-images.githubusercontent.com/3362943/178095974-339de6dd-32ca-49cb-9dcf-8b442d3e9114.png)

#### What happened instead?

It is hidden 1px (4px: the width of the stroke - 3px: the inline padding of the editor) by the editor.

![before](https://user-images.githubusercontent.com/3362943/178095983-24958520-8b9e-46ed-9361-23d250b148dd.png)

### Operating system

Debian

### Browser information

Firefox ESR 91

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by robertlong** [comment]
This issue also appears in Element desktop when IRC layout is used.
