### ISSUE TITLE
Search highlighting seems not really consistent

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22787]
### Steps to reproduce

1. Open a popular room such as Matrix HQ
2. Search for a popular word such as `Element`

#### What did you expect?

Every `Element` should be highlighted.

#### What happened instead?

Some are highlighted, others are not. It looks not really consistent.

![Untitled](https://user-images.githubusercontent.com/3362943/178102198-f2ffb43f-5ecf-4097-873f-68950c5f5178.png)

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This is pretty odd - it seems that `SafeEventTile` sometimes has the `highlights` prop `undefined` though I think `SearchResultTile` is always passing it correctly

**Comment by t3chguy** [comment]
Looks like plaintext messages (ones without `formatted_body`) don't get highlights

**Comment by t3chguy** [comment]
This pretty much has to be regression otherwise it'd have barely ever worked pre-replies, as those force a lot more messages to be formatted
