### ISSUE TITLE
Clicking on a room category arrow when category is stuck at the bottom should collapse the category

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2278]
When the room list is scrolled up with my favourite expanded, the People category is stuck at the bottom. If the category is meant to be expended, clicking on the arrow should collapse it while clicking somewhere else on the title will make it visible.

**Comment by ara4n** [comment]
Agreed. Having arrows toggle collapse state would be nice.

**Comment by turt2live** [comment]
We've specifically avoided this behaviour in the new room list
