### ISSUE TITLE
Video thumbnail not displaying in encrypted rooms.

### ISSUE THREAD

**Issue by coxde** [vector-im/element-web#22791]
### Steps to reproduce

1. Turn off "Autoplay GIFs and videos" option
2. Open an encrypted room including videos.

#### What did you expect?
A thumbnail inside the player frame.

#### What happened instead?
The player frame is shown, but with black background. It can play if I click play button.

**Note**: only happened in an encrypted room.

### Operating system

Linux

### Browser information

Firefox 102, Chromium 103

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

Homeserver with Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment]
@coxde what client sent the video? Older versions of Element Web/Desktop sometimes sent invalid things for portrait videos.

**Comment by t3chguy** [comment]
Likely an issue with the bridge then, if videos from Element clients work as expected.

**Comment by turt2live** [comment]
Closing as a presumed upstream issue. If this is untrue, please open a new issue with fresh reproduction steps for our QA team to review.
