### ISSUE TITLE
"Check for update" button doesn't appear to work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22795]
### Steps to reproduce

1. Have a pending Desktop app update
2. Dismiss the toast
3. Go to settings -> Help
4. Click "Check for Update" to get the toast/"update now" button, but instead it keeps spinning at "Checking for update"

#### What did you expect?

The update to be checked and applied, so I can update.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/178197570-61d1d5d5-8a5a-41f6-a4b6-4c4dc45bbcf2.png)

with that spinner going on forever and ever

### Operating system

Windows 10

### Application version

Nightly 2022070901

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
flagged as a release blocker until investigation proves otherwise

**Comment by t3chguy** [comment]
Caused by https://github.com/vector-im/element-desktop/pull/386
