### ISSUE TITLE
Room appears to be part of a space on my client, but it doesn't appear for other people

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#22798]
### Steps to reproduce

(Not sure how to repro, this is reporting a split brain that has happened)

My client thinks a room (A) is joined to a space (B). However, other users in the space can't see the room. If I open the devtools for the space, there is **no** `m.space.child` for A. 

The UI for the room thinks it's in the space. I can't add the room to the space in my client because it believes it's already there.

#### What did you expect?

Everyone can see that the room is part of a space.

#### What happened instead?

My client thinks the room is part of a space, but other users do not.

### Operating system

Arch Linux / Wayland w/ Sway

### Browser information

Firefox 102

### URL for webapp

develop.element.io

### Homeserver

Element version: a4f9e7adad81-react-8c67984f50f9-js-1fbfdaf22131 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@Half-Shot this sounds like https://github.com/vector-im/element-web/issues/17293

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/19209
