### ISSUE TITLE
Update documentation about cypress

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#22799]
### Steps to reproduce

1. Open https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#cypress-in-element-web and read
2. `cd ~/element-web`
3. `yarn start`
4. Open a new terminal
1. `cd ~/matrix-react-sdk`
1. `yarn run test:cypress`

#### What did you expect?

- Cypress tests run
- The manual which reflects the latest status

#### What happened instead?

`Can't run because no spec files were found.`

https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#how-the-tests-work says:

> Everything Cypress-related lives in the cypress/ subdirectory of react-sdk as is typical for Cypress tests. Likewise, tests live in cypress/integration.

But there is no `integration` folder inside https://github.com/matrix-org/matrix-react-sdk/tree/develop/cypress.

### Operating system

Debian

### Will you send logs?

No

**Comment by t3chguy** [comment]
Can you confirm what version of Cypress you had installed?

**Comment by luixxiul** [comment]
Installed the latest version and it look like it works.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/9039 updates the doc
