### ISSUE TITLE
User shows as unverified, even though all their sessions are

### ISSUE THREAD

**Issue by jblachly** [vector-im/element-web#22826]
### Steps to reproduce

Signed into the same account (user1; on private conduit 0.4 homeserver) with element-web (app.element.io) and element-iOS; and then to a second account (user2; on public mozilla.org) once using a different element-web instance (chat.mozilla.org).

Next, I had user1 and user2 verify one another with emojis using the two element-web instances in the browser.

Afterward, for user1 on element-ios ONLY, and for user2 in element-web (via chat.mozilla.org), both users show as mutually validated. Green shield for E2EE rooms correctly appears. User1 in **element-web** does not see user2 as verified (even though it shows user2's session as verified);  see details below.

#### What did you expect?

I expected user1 (via element-web) to see user2 as validated.

#### What happened instead?

User1, via element-iOS _does_ show user2 as validated.
However, User1 (via element-web) does NOT show user2 as validated, even though user2's only session does show as validated. Also, user2 appears as "offline" to user1 which may be a function of the homeserver(?). Importantly, although element-ios also shows user2 as offline, they still show with green shield and are marked verified.

**Figure 1:** User 1's view of User 2 in element-web; note gray shield.
![Screen Shot 2022-07-12 at 5 03 20 PM](https://user-images.githubusercontent.com/5987153/178595554-5eae7a51-44cd-4bc2-b658-eb3aa1d1a0f6.png)

**Figure 2:** User 1's view of User 2 in element-web after clicking "1 session" to expand
![Screen Shot 2022-07-12 at 5 05 11 PM](https://user-images.githubusercontent.com/5987153/178595513-dddeb960-fb85-4755-8016-7875aee6c4cf.png)

**Figure 3:** User 1's view of User 2 in element-ios
![IMG_CCA6AFECF864-1](https://user-images.githubusercontent.com/5987153/178595446-fc9e682b-a0b5-432d-b6c3-52d57ffa6b38.jpeg)
 

### Operating system

macOS

### Browser information

Firefox (102.0.1)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.11.0 Olm version: 3.2.8

### Homeserver

conduit 0.4

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Did the verification happen in the room timeline or in a bunch of popups? This looks like you verified the user's devices (legacy) rather than their cross-signing keys (maybe they don't have any) hence you trust the devices but not the user, and you won't have implicit trust on any of their new (self-verified) devices.

**Comment by jblachly** [comment]
> Did the verification happen in the room timeline or in a bunch of popups? This looks like you verified the user's devices (legacy) rather than their cross-signing keys (maybe they don't have any) hence you trust the devices but not the user, and you won't have implicit trust on any of their new (self-verified) devices.

Popups. I have a hard time understanding your comment because it is clearly different behavior between element web and element iOS.

**Comment by t3chguy** [comment]
Closing due to this being a server support issue, compounded by an Element iOS bug
