### ISSUE TITLE
Phone number country code defaults to 🇬🇧 `United Kingdom (+44)` which isn't accurate for every other country

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#22825]
#### What would you like to do?

Default phone number country code to the country I'm in. **Settings** -> **General** -> **Phone numbers**

#### Why would you like to do it?

Currently, the phone number country code defaults to 🇬🇧 `United Kingdom (+44)`. It stands out in the settings as someone who lives in the US:

![](https://user-images.githubusercontent.com/558581/178586557-10dcebca-87d7-4149-a1d6-4e568a3954d6.png)

The picker already has the `United States (+1)` as the second option by default:

![](https://user-images.githubusercontent.com/558581/178586600-428fc4cc-3ef9-4547-86ba-68e85bdcf763.png)

#### How would you like to achieve it?

Instead of pulling from location or based off of IP, maybe we can infer a bit from `window.navigator.language` since it's `en-US` for me in the US. Obviously not applicable for all situations since people can change their language to whatever but it's an easy heuristic for the majority in the US.

**Comment by t3chguy** [comment]
Language codes don't map 1:1 to a country. E.g en_GB (default) can be mapped to many dialing country codes in the dropdown.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/2403652/178691068-2dd79c80-178a-495c-b1a8-a8f73d7c0ee5.png">

Similar goes for French, Spanish, and other more widely spoken languages.

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/10627 as much as the granularity of language codes allows
