### ISSUE TITLE
main view doesn't fit my (not so small) screen anymore

### ISSUE THREAD

**Issue by zeenix** [vector-im/element-web#22833]
### Steps to reproduce

Ever since the global panel has appeared on the left, my channel view doesn't fit in on my screen and I've to scroll horizontally to read the full message and reach for buttons on the messages (reply, reaction, etc). I resized the channel list/selection vertical panel to minimum but it didn't help. My display resolution is 3840x2160.

![Screenshot from 2022-07-13 12-40-02](https://user-images.githubusercontent.com/2027/178715139-a1513348-e1e9-4285-b6cd-ec84df05fcc0.png)

#### What did you expect?

To not have to scroll horizontally to see the full message and reach the buttons.

#### What happened instead?

I had to scroll horizontally.

### Operating system

Linux

### Browser information

Firefox 101 x86_64

### URL for webapp

https://gnome.element.io/

### Application version

GNOME version: 1.11.0 Olm version: 3.2.8

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Can you reproduce this in a clean browser profile with default settings and no extensions?

**Comment by zeenix** [comment]
> Can you reproduce this in a clean browser profile with default settings and no extensions?

I don't know if there is an easy way to save settings, reset to default and then reload old settings. :thinking:

**Comment by SimonBrandner** [comment]
> I don't know if there is an easy way to save settings, reset to default and then reload old settings. thinking

Perhaps you could try an anonymous window though I am not sure to what extent that helps here

**Comment by zeenix** [comment]
> Perhaps you could try an anonymous window though I am not sure to what extent that helps here

I did that and then I can't reproduce the issue.

It's possible that this somehow is triggered by my me switching back and forth between my big monitor and laptop screen (that has much smaller resolution).

**Comment by zeenix** [comment]
oh and seem launching a new FF window and opening gnome.element.io there also helps. perhaps one of the tabs is somehow messing things up. :shrug:

**Comment by turt2live** [comment]
Closing as a presumed environmental/browser issue. If this is untrue, please open a new issue with fresh reproduction steps for our QA team to review.

**Comment by zeenix** [comment]
> Closing as a presumed environmental/browser issue.

What changed in all these months that gave you that impression? I provided all the information you asked for and happy to provide more info. Everything remains the same for me and it's super annoying.

> If this is untrue, please open a new issue with fresh reproduction steps for our QA team to review.

Why make me go through the effort of repeating the whole thing? Please re-open the issue and assign the tags or move it as you see fit cause it's still reproducible and it's the exact same bug with the same environment.
