### ISSUE TITLE
Composer doesn't refocus when "Unknown Command" dialog is quit

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22832]
### Steps to reproduce

1. In a room, send an invalid command from the composer. e.g. `/>`
2. See the "Unknown Command" dialog appear
3. Press `Esc` on the keyboard to quit the dialog

#### What did you expect?
Dialog closes and composer is re-focused

#### What happened instead?
Dialog closes and composer lost focus

### URL for webapp

develop.element.io

### Application version

Element version: fc1db94c8030-react-6fb834200387-js-7a18991342cb Olm version: 3.2.8

### Will you send logs?

No

**Comment by Ashu999** [comment]
Hi, I'll be working on this issue
