### ISSUE TITLE
Drop in rooms similar to discord, but saving bandwidth

### ISSUE THREAD

**Issue by mcmurphy8097234789** [vector-im/element-web#22835]
#### What would you like to do?
I would be able to drop into 'rooms' similar to discord. 

#### Why would you like to do it?
It is convenient, it is less intrusive than calling other people directly, and in my experience the lack of this feature has been the obstacle to my social network from using element

#### How would you like to achieve it?
Ideally, 'drop in' functionalities would be similar to Discord. However, it is possible that element does not have the bandwidth for people to be sitting in a room while being idle.

If this is the case, I propose 2 measures. First, when joining a room, the single user is allowed to show up graphically in the GUI as 
being 'in the room' and this user is put in a voice call connection queue; however, the backend would not actually transmit/initiate a connection until more than one user was in the room.
Second, an AFK measure; if a person doesn't seem to be transmitting audio for a length of time (say 10 minutes) they are removed from the call. 

### Have you considered any alternatives?

See last answer

### Additional context

None required

**Comment by t3chguy** [comment]
Have you tried the Video rooms beta? These are rooms which you can create which users can leave and join as they wish.

![Uploading image.png…]()

**Comment by mcmurphy8097234789** [comment]
> Have you tried the Video rooms beta? These are rooms which you can create which users can leave and join as they wish.
> 
> <img alt="image" width="1064" src="https://user-images.githubusercontent.com/2403652/178740431-2c690857-e57b-4336-b80f-43767013ea6e.png">

Well now I feel like an idiot; I didn't know this was a beta. This is basically what I am suggesting, yes.
I do like the features; they even have screen sharing in this beta. Looking forward to seeing the kinks ironed out

**Comment by SimonBrandner** [comment]
As it seems this issue is resolved, I am going to close it. If you encounter any issue with video rooms, feel free to fill out a bug request :)
