### ISSUE TITLE
Collapsed state events are misaligned in IRC layout

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#22868]
### Steps to reproduce

1. Find a number of collapsed state events like join/leave messages 
2. See that they are misaligned in the timeline when collapsed

Collapsed:

![image](https://user-images.githubusercontent.com/62639087/179350399-aa1fdd83-3829-4abe-92c4-cca63a94a12a.png)

Uncollapsed:

![image](https://user-images.githubusercontent.com/62639087/179350410-2ed6829f-585b-4387-b535-232cbd4b61e5.png)

![image](https://user-images.githubusercontent.com/62639087/179352632-b3ed6098-94b3-4c5f-839b-6d9e5fcdc132.png)

#### What did you expect?

To be aligned similarly to the uncollapsed layout ie. more to the center of the timeline

#### What happened instead?

Aligned to the left edge of the timeline

### Operating system

Arch Linux

### Browser information

Firefox Nightly 

### URL for webapp

https://develop.element.io

### Application version

Element version: 787d4c41351e-react-161a333a5165-js-32bb4b1fc464 Olm version: 3.2.8

### Will you send logs?

No

**Comment by bbhtt** [comment]
I haven't checked but I think this is from https://github.com/matrix-org/matrix-react-sdk/pull/8994. If the idea was to align all these events to the left, then I guess the issue is that the uncollapsed events aren't.

**Comment by luixxiul** [comment]
It should be fixed with https://github.com/matrix-org/matrix-react-sdk/pull/9063. Regressed with the recent change from *.scss to *.pcss.

**Comment by bbhtt** [comment]
> Regressed with the recent change from *.scss to *.pcss, because of [this line](https://github.com/matrix-org/matrix-react-sdk/pull/9013/files#diff-5d3e25eb1d22dd7a96e0e87ea9c1298dc7dbce8eb965d30b2d1ebc1436bfec3fR492). Not because of [matrix-org/matrix-react-sdk#8994](https://github.com/matrix-org/matrix-react-sdk/pull/8994)

Indeed, it's that commit, thank you.

>  It should be fixed with [matrix-org/matrix-react-sdk#9063](https://github.com/matrix-org/matrix-react-sdk/pull/9063).

Looks like it is fixed (I'm on 787d4c41351e-react-b90ea87d11e9-js-32bb4b1fc464
Olm version: 3.2.8 now) like you said so I'm closing this issue. 

Thanks!
