### ISSUE TITLE
scalar.vector.im returns 403 for widgets in chrome

### ISSUE THREAD

**Issue by roughnecks** [vector-im/element-web#22865]
### Steps to reproduce

1. I'm adding widgets in a room, be it a TradingView or Sticker widget
2. When I pin the TradingView widget in the room or open the stickers panel (to add one in chat) I only get a white window
3. If I open chrome's developer mode I can see 403 error code returned for scalar.vector.im

#### What did you expect?

I'm expecting to see the actual widget loading up

#### What happened instead?

Only got a white, never-loading window

https://gist.githubusercontent.com/roughnecks/d938f7bab7b1bd79bcf888860de62d85/raw/d8a2dab6515483bab854086acfce2e7865ea6655/2022-07-15_18-08-00.txt

### Operating system

Windows 10 Pro x64

### Browser information

Chrome Version 103.0.5060.114 (Official Build) (64 bit)

### URL for webapp

https://app.element.io/#/home - https://element.woodpeckersnest.space/#/home

### Application version

Element version: 1.11.0 Olm version: 3.2.8 (on my HS)

### Homeserver

matrix.org | woodpeckersnest.space with Synapse 1.62.0

### Will you send logs?

No

**Comment by roughnecks** [comment]
Okay, after a lot of troubleshooting I think it's working fine now. I had to allow third-party cookies which were blocked in the Element Web app.

**Comment by ledlamp** [comment]
OMG thx. Enabling third party cookies made it work. But chrome will turn it back off in 90 days! How come it works with matrix.org but not my server??? There must be something missing...
