### ISSUE TITLE
Cannot delete unverified devices when using SSO

### ISSUE THREAD

**Issue by nhh** [vector-im/element-web#22867]
### Steps to reproduce

1. Go to settings > Security
<img width="1043" alt="Bildschirmfoto 2022-07-16 um 09 17 09" src="https://user-images.githubusercontent.com/13472382/179344679-09d20709-0327-4edf-b6a3-a70dd722e3fc.png">
2. Click delete unverified devices
<img width="397" alt="Bildschirmfoto 2022-07-16 um 09 18 37" src="https://user-images.githubusercontent.com/13472382/179344695-ed59049b-2131-4614-87d1-0fbb7ba55172.png">
3. You are being prompted with an Password field
<img width="730" alt="Bildschirmfoto 2022-07-16 um 09 21 13" src="https://user-images.githubusercontent.com/13472382/179344791-ab9fe8fc-85b3-439d-9545-363929325ff3.png">

#### What did you expect?
When using SSO I expect that there is no password field to be prompted with.
#### What happened instead?
A password field wants my password, which I dont have. (SSO)

### Operating system

macOS

### Application version

Version von Element: 1.11.0 Version von Olm: 3.2.8

### How did you install the app?

Dont remember

### Homeserver

https://matrix.mointech.de

### Will you send logs?

No

**Comment by t3chguy** [comment]
@nhh your server must be misconfigured and not asking for the relevant flow to your account. I suggest chatting to in the Synapse room asking for help. The relevant APIs are UIA - https://spec.matrix.org/v1.3/client-server-api/#user-interactive-authentication-api - where the server tells the client what flow (password or SSO etc) it wants, and here the server is asking for a password.

**Comment by nhh** [comment]
@t3chguy Hi, thank you for your response.

Are you sure that this must be a misconfiguration?

For context I've changed the auth from local to sso with existing accounts. So the users have had a password.

I've configured everything according to the official docs.

Is that relevant?

**Comment by t3chguy** [comment]
Its up to Synapse to send the flows which are specific for that user, if your user doesn't have a password then Synapse shouldn't be asking for one like it is here.
