### ISSUE TITLE
Allow hiding "Home" on sidebar when "People" and "Other Rooms" are enabled.

### ISSUE THREAD

**Issue by aflyingpumpkin** [vector-im/element-web#22870]
### Your use case

On the Sidebar I am currently able to show "People" and "Other Rooms" in order to help avoid clutter. Though I am unable to hide the "Home" section once these two are enabled. When these two sections are enabled, they cover all information that would normally be displayed inside of "Home" but in a more organized format, so having "Home" be displays just takes up screen real estate. And more importantly (for my workflow) the Ctrl+1 keybind. I would like for the ability to hide "Home" when "People" and "Other Rooms" are displayed.

### Have you considered any alternatives?

Giving users the ability to completely disable "Home" no matter what other items they have in their sidebar would also be a valid way to address this issue and avoid clutter for users who do not actively user Home. Another way to avoid this problem is to allow users to move Home to be at the bottom of their key binds / space list.

**Comment by SimonBrandner** [comment]
Duplicate https://github.com/vector-im/element-web/issues/20948
