### ISSUE TITLE
Links in replies are clickable but text isn't selectable

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#22877]
### Steps to reproduce

Hyperlinks in quoted replies are clickable but the text isn't selectable, causing the rage-inducing interaction of trying several times to select the latter half of link (ie. the bit I wanted), failing, then clicking to to the the original reply where I'd be able to select the text and instead clicking on the link.

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
duplicate of #18202
related to #21299
