### ISSUE TITLE
Email validation for new account logs me out of my account

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22881]
### Steps to reproduce

1. Be logged into Element with an account
2. In the same browser, click on a validation link for a new Matrix account
3. Be logged out of your old account and logged into the new one

#### What did you expect?
If I am already logged in, I would expect to not be logged out as that could cause me to lose my keys

#### What happened instead?
I was logged out and temporarily lost access to my historical messages

### Browser information

Chromium 101.0.4951.64 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by gsouquet** [comment]
@kittykat this is marked as a regression, is that how this used to work?

This issue would benefit from being open on Synapse as this is the piece of the stack that issues those emails and the access token when clicking the link
Will close the ticket here as I am not able to move the issue cross organisations

**Comment by turt2live** [comment]
This appears to have regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8654 - we have the code [here](https://github.com/matrix-org/matrix-react-sdk/blob/43773e134a42de27d3c02841bb288daea5b966a6/src/components/structures/auth/Registration.tsx#L357) to prevent the overwrite, but the PR seems to bypass this.

Keeping as a release blocker, but not necessarily for the current RC->release cycle. This is something which needs to be fixed soon, I think, given it's been an issue for a couple months and release blockers are the current way of making that happen (unless there's a different process?)

**Comment by turt2live** [comment]
also ftr, this is broken on app too (having re-tested myself).

**Comment by turt2live** [comment]
@t3chguy yes, but not necessarily for this release:

> Keeping as a release blocker, but not necessarily for the current RC->release cycle. This is something which needs to be fixed soon, I think, given it's been an issue for a couple months and release blockers are the current way of making that happen (unless there's a different process?)
