### ISSUE TITLE
Web ↔ Web emoji verification match confirm ends up with „Verification cancelled“

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#22908]
### Steps to reproduce

1. Have to web sessions
2. Start emoji verification
3. Confirm matching emojis

#### What did you expect?

Verification done

#### What happened instead?

Verification failing with „Verification cancelled“

![Peek 2022-07-21 12-13](https://user-images.githubusercontent.com/6216686/180190196-fe3925d8-6c41-4d1c-baf8-c4c7a70b2038.gif)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 102.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: a6a1e1fffd81-react-9edd49818c4a-js-32f55de38388 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Works before https://github.com/matrix-org/matrix-js-sdk/pull/2320

**Comment by uhoreg** [comment]
> Olm version: 3.2.8

It should work again with https://github.com/vector-im/element-web/pull/22906  Can you give it another try?

**Comment by SalsaGal** [comment]
This issue has happened again. I'm on Arch Linux and I'm trying to verify my IOS client.
