### ISSUE TITLE
Create cypress test for email verification flow

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#22910]
We should create a cypress test for the email verification flow. We should test the happy case, but also ensure previously fixed issues don’t return:

- https://github.com/vector-im/element-web/issues/22881

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/22297

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22297
