### ISSUE TITLE
The Welcome Home Screen: Dedicated Download Apps Dialog

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#22921]
*Part of Epic https://github.com/vector-im/element-web/issues/22463*

As part of the new user onboarding flow, we want to provide a better experience for the "download apps" action. This should be accomplished with a new, dedicated dialog for downloading apps.

**Comment by daniellekirkwood** [comment]
We deprioritised this from the MVP so that we could get the checklist into the 26th July RC. We will update with this functionality for the next release.
