### ISSUE TITLE
Reduce volume of ringtones (someone calling, call ended...)

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#22936]
#### What would you like to do?
Reduce the volume of the ringtones - they are a lot lot louder than the voices in calls (or anything in relation on my computer for that matter)
#### Why would you like to do it?
It's too loud
#### How would you like to achieve it?
Reduce the volume - either programmatically or of the ringtone files itself

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/5891

**Comment by JMoVS** [comment]
please reopen - I am fine with the selection - my issue is with the incredible volume of these. Letting users change the ringtone won't solve the volume issue either - it would just mean a different ringtone at very loud volumes

**Comment by t3chguy** [comment]
@JMoVS then its https://github.com/vector-im/element-web/issues/4192

**Comment by JMoVS** [comment]
Thanks - 4 years open. I saw a commit that aimed to reduce the volume by changing the ogg file - if I were to generate a pull request to lower the ringing volume sound files, could that be accepted?
