### ISSUE TITLE
Something went wrong error when attempting to join a room in a space

### ISSUE THREAD

**Issue by MURBASLMS** [vector-im/element-web#22956]
### Steps to reproduce

Was invited to a space, joined ok
list of rooms in there, clicked join
something went wrong message appeared
clear cache and reload worked

### Outcome

when clicking join a room in a space would expect to just join.

### Operating system

OSX 10.15.7

### Application version

1.11.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22752
