### ISSUE TITLE
Glitch when right clicking the text bar on Element Desktop

### ISSUE THREAD

**Issue by Rayserzor** [vector-im/element-web#22954]
### Steps to reproduce

After I update my Element from 1.9.9 to 1.11.1 I have some glitches when I right-click the text bar to have options like "paste, select all, etc..."

![glitch error](https://user-images.githubusercontent.com/34875783/181583011-5acd04a9-7307-4eae-b8ac-f6ef479ec054.png)

### Outcome

I expected to work just fine like the previous version (1.9.9) but instead in the new version 1.11.1 I have this annoying glitch.

### Operating system

Linux Mint Cinnamon 20.3

### Application version

Element Desktop Linux Flatpak 1.11.1  Olm 3.2.8

### How did you install the app?

Flatpak command line

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22439 which is likely the same underlying cause within Electron/Chromium
