### ISSUE TITLE
Always issues with detecting users people in chat room, they're either invisible or says offline

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-web#22955]
### Steps to reproduce

1. Where are you starting? What can you see?
Under settings info on a room, under "People" why do I just about never see all the people that are in that room, and those that I do see, some of them say "offline" when they are not offline.
In fact even inside from the Element Desktop itself with the user that I'm chatting with and sending messages, it still says user is "offline". 

Is this a problem with DENDRITE server or can these issues be CLIENT related as well?
I have these kind of issues on just about all clients it seems, Element Desktop or Android etc.
(It also affects both encrypted and UN-encrypted rooms as well.)

Perhaps it would be good to have a feature whereby an Admin can promote another user to ADMIN etc by typing in the username if its not visible or if its listed offline etc. Since as it is I couldn't promote a user's privileges since I couldn't select user since wasn't visible in the android client that had Admin, and in the Element Desktop it says user is offline.

#### What did you expect?
I expect all users to be shown under list of people in channel etc.
#### What happened instead?
Not seeing other users at all though they are in channel and sending messages.
And from that sender's own element desktop, oddly they're shown as "offline".

### Operating system

Windows 10

### Application version

Element version: 1.11.1 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started

### Homeserver

Dendrite Latest git pull yesterday

### Will you send logs?

No

**Comment by aaronraimist** [comment]
> Is this a problem with DENDRITE server

Yes. https://github.com/matrix-org/dendrite/blob/main/README.md says

> In particular, presence and push notifications are entirely missing from Dendrite.

Presence is the feature you are looking for.
