### ISSUE TITLE
HTML tags are being displayed in links for desktop app

### ISSUE THREAD

**Issue by jeremiah-k** [vector-im/element-web#22953]
### Steps to reproduce

1. Where are you starting? What can you see?
We have an RSS bot in a room and <strong> & </strong> HTML tags are displayed in the title in the Element desktop app, but displays normally in the web app. I believe this just started happening in the latest version 1.11.1. I don't know if the problem is specific to the RSS bot or just these tags, etc.

![Screenshot from 2022-07-28 10-33-10](https://user-images.githubusercontent.com/17190268/181579429-323969cf-4a77-4ac7-b37c-fdce23964d6d.png)
Element Desktop v1.11.1

![Screenshot from 2022-07-28 10-33-25](https://user-images.githubusercontent.com/17190268/181579477-58350d03-a07e-4e90-bc64-2943256721a4.png)
Element Web v1.11.1

#### What did you expect?
The link to the webpage to display correctly without showing the HTML tags.
#### What happened instead?
HTML tags were visible.

### Operating system

Linux Mint 20.3

### Application version

1.11.1 Desktop

### How did you install the app?

Debian/Ubuntu package

### Will you send logs?

No

**Comment by t3chguy** [comment]
@chainslunatic the change landed yesterday, the RC was cut last Tuesday. So you won't see this until the next release. https://github.com/vector-im/element-web/releases/tag/v1.11.2-rc.1
