### ISSUE TITLE
Port VideoChannelUtils to MSC3401

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22957]
As a preparatory task for integrating Element Call into Element Web, the utilities from the VideoChannelUtils file need to be ported to work with [MSC3401](https://github.com/matrix-org/matrix-spec-proposals/pull/3401), in addition to the proprietary `io.element.video` events that we use today for video rooms. I would suggest putting the MSC3401 versions of these utilities in a file called GroupCallUtils.

Since Element Call is already doing some of the work for us, not all of the utilities need to have MSC3401 versions. The only ones that will be used within the react-sdk, are:

- `getVideoChannel` (should probably be named `getGroupCall`, and return the active `m.call` event)
- `useConnectedMembers` (needs to take the `m.call` event as an input in order to find the associated `m.call.member` events)
- `removeOurDevice`
- `fixStuckDevices`

These should all be accompanied by unit tests.

Since these functions will need to inspect `m.call` and `m.call.member` events, but the types for them are sitting in the unmerged robertlong/group-call branch of the js-sdk, it's okay if those type declarations get duplicated in the react-sdk. Once we finish merging the group call branch back into mainline, we can remove those redundancies, but we just need something to build off of for the moment.

**Comment by weeman1337** [comment]
Hi @robintown I wonder how `fixStuckDevices` is supposed to work. According [to the spec](https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/group-voip/proposals/3401-group-voip.md) there is no last seen per device any more. Instead there is an `m.expires_ts` for the entire `m.call.member` state.

**Comment by robintown** [comment]
You should still be able to call `await client.getDevices();` and then look for the `last_seen_ts` on each, right? That shouldn't've changed with MSC3401.

**Comment by robintown** [comment]
Both the `io.element.video.member` events and the `m.call.member` events have a single `expires_ts` value in their content, so the logic should be practically the same
