### ISSUE TITLE
Room sidebar reports 98 people, People list only shows 33 total

### ISSUE THREAD

**Issue by Winterhuman** [vector-im/element-web#22965]
### Steps to reproduce

1. Go to https://matrix.to/#/#freenet-locutus:matrix.org.
2. Open room sidebar to see details.
3. See `People: 98`.
4. Open **People** list, but only see 33 people total.

#### What did you expect?

Because I don't know if "98" is the actual number of people in the room or not, here's the expectations depending on what's happening:

- If the number (98) isn't the actual number of people, it should report the number of people actually in the **People** list instead.
- If the number (98) is the actual number of people, the people list, when expanded, should say something like "65 people couldn't be found..." similar to how "and N others..." is shown.

Alternatively, this issue might not be practical to fix; the people list and the number of people might always be significantly different for small rooms.

#### What happened instead?

The number of people reported in the room's sidebar is much higher than the actual list of people accessible.

Of note is that the Locutus room seems to be unique, other similarly sized rooms (usually smaller) don't have this issue. This might be because the room has a larger variety of homeservers involved than a typical Matrix room?

### Operating system

Arch Linux

### Application version

Element version: 1.11.1, Olm version: 3.2.8

### How did you install the app?

FlatHub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
![2022-07-30_10-21](https://user-images.githubusercontent.com/25768714/181894843-db70e00f-670c-4486-ba9c-119b97293680.png)

You can expand this list by clicking this button

**Comment by Winterhuman** [comment]
Yes, that's why I said it shows 33 total; clicking "and N others..." only reveals 3 more people for me

**Comment by Winterhuman** [comment]
Here's some images to clarify what I'm seeing:
![SidebarNumber](https://user-images.githubusercontent.com/86165318/181909880-43cdb999-a412-4bb0-9789-3fc42ec4e249.png)

And when I go to the people list and scroll to the end of the list of the initial 30 people:

![PeopleListNumber](https://user-images.githubusercontent.com/86165318/181909884-a7c5f425-cda0-4ffa-a3c1-a2dd69b9de8e.png)

**Comment by SimonBrandner** [comment]
Ah, I see sorry!

**Comment by Winterhuman** [comment]
Closing as duplicate of https://github.com/vector-im/element-web/issues/17096.
