### ISSUE TITLE
new session shown as not trusted, despite doing the verification dance

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#22962]
### Steps to reproduce

1. start a new eleweb session
2. verify it from another device (QR code scan)
3. new session still shows as not trusted

#### What did you expect?

Device should be shown as verified

#### What happened instead?

I, and others, see my new session as unverified

![image](https://user-images.githubusercontent.com/1389908/181737770-78f0a5b5-9446-44c9-b7d2-5a9d88f20cfa.png)

![image](https://user-images.githubusercontent.com/1389908/181737828-5e9118f2-6361-4bff-a0ed-3580853ca2eb.png)

### Operating system

Ubuntu 22.04

### Application version

Element Nightly version: 2022071901 Olm version: 3.2.8

### How did you install the app?

nightly debian

### Homeserver

synapse 1.61.0

### Will you send logs?

Yes

**Comment by richvdh** [comment]
possibly again related to lack of gnome-keyring?

**Comment by richvdh** [comment]
I tried to do the verification again with an emoji comparison, but no improvement.

**Comment by richvdh** [comment]
Is this maybe the same as #21919?

**Comment by richvdh** [comment]
btw it is 100% reproducible for me - no matter how many times I do the verification dance it doesn't help.

**Comment by richvdh** [comment]
oh, or possibly #22904 is a closer match

**Comment by MichaelErjemenko** [comment]
I observe the same behaviour for two accounts, but cannot reproduce it for one of my own accounts.

1. New device_b login (Chrome)
2. old and verified device_a (Android Element-App) verifies device_b
3. device_b can decrypt all messages
4. device_b is shown as unverified like already descirbed in the issue desciption

**Comment by richvdh** [comment]
well, this seems to have fixed itself somewhere along the line.
