### ISSUE TITLE
Element suddenly started sending malformed Authorization headers

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#22960]
### Steps to reproduce

? I just opened Element-desktop this morning

### Outcome

Looking at the devtools, I see this header on all requests:

```
Authorization: Bearer [object Object]
```

Obviously, they are 401ed.

### Operating system

Ubuntu 22.04

### Application version

element-nightly 2022071901

### How did you install the app?

nightly debian

### Homeserver

synapse 1.61.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
`2022-07-29T08:32:50.604Z E Expected a pickle key, but none provided.  Encryption may not work.`

@richvdh is your Keyring having issues?

**Comment by richvdh** [comment]
oh, heh. I uninstalled gnome-keyring in a fit of pique. So yes, I guess that's it. The silent failure is a bit unpleasant though.

**Comment by t3chguy** [comment]
Indeed, but your session might now be hosed as it is pickled against a key stored in your keyring

**Comment by richvdh** [comment]
I've now logged out and logged back in, so hopefully I should be ok?

**Comment by t3chguy** [comment]
Symptomatically this is https://github.com/vector-im/element-web/issues/17845

Duplicate of https://github.com/vector-im/element-web/issues/17845

**Comment by t3chguy** [comment]
> I've now logged out and logged back in, so hopefully I should be ok?

Yup, no more pickling will happen so things are stored in plaintext on disk
