### ISSUE TITLE
Date separators are way bigger than they should be with jump to date enabled

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22969]
### Steps to reproduce

1. Enable the jump to date feature in labs
2. Look at any date separator (big black text)

#### What did you expect?

<img width="672" alt="" src="https://user-images.githubusercontent.com/558581/150060664-79627573-f4fd-497c-b726-dc3485854bd0.png">

#### What happened instead?

![Screenshot 2022-08-01 at 14-12-42 Element Video rooms](https://user-images.githubusercontent.com/48614497/182215014-76de45e0-63d2-43aa-a30d-54fb0137ebe6.png)

### Operating system

NixOS unstable

### Browser information

Firefox 102.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 070f4735cd06-react-f10e3abb6e64-js-4a4241806e3d Olm version: 3.2.12

### Homeserver

Synapse 1.63.1

### Will you send logs?

No

**Comment by alwaysahad** [comment]
please assign me  this issue

**Comment by robintown** [comment]
Hi @alwaysahad, we have a policy of not assigning issues to new external contributors without first seeing at least a draft PR that looks promising. However, you're still very much welcome to work on this. If you have any questions, feel free to ask us in [#element-dev](https://matrix.to/#/#element-dev:matrix.org).

**Comment by spiritanand** [comment]
@robintown could you please give more details of the error before I get started?

**Comment by robintown** [comment]
Hi @spiritanand, due to https://github.com/vector-im/element-web/issues/24362 blocking this feature from being enabled in the client, I would actually not recommend this as a good first issue at this time.
