### ISSUE TITLE
Using the word specific

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#22974]
### Your use case

I am not a native english speaker and stumbled accross this in translate.element.io , but it looks like specific is used as replacement for rooms and spaces.
I don't think this is very user friendly.
https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=c6041d79ab1bed4c
https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=37cfab5560f782a5
https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=8da399750814b3c3

### Have you considered any alternatives?

perhaps "rooms and spaces"
(It's translated this way in the german translation)

**Comment by SimonBrandner** [comment]
Yep:

+ `Remove them from everything I'm able to`
+ `Remove them from specific things I'm able to`
+ `They'll still be able to access whatever you're not an admin of.`

![image](https://user-images.githubusercontent.com/25768714/182538695-08bce445-894a-4472-ba45-3d49699dcc31.png)

Is this enough context for you?

**Comment by JokerGermany** [comment]
Yes thanks

**Comment by SimonBrandner** [comment]
> Yes thanks

np!

**Comment by JokerGermany** [comment]
But i think that a greyed out selection box, even if you didn't already have chosen the second selection, would be good and would better explain the "specific".

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22986
