### ISSUE TITLE
string "Remove them from everything I'm able to" is unspecific

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#22975]
#### What would you like to do?
I wanted to translate this string

#### Why would you like to do it?
I stumbled over the german translation and looked into translate.element.io
https://translate.element.io/translate/element-web/matrix-react-sdk/de/?checksum=723f0f1595745ba6

When i saw the german message the first time i was very confused, i already changed a little bit in the translation perhaps this will fix it a little bit, but perhaps it's better to add rooms and spaces instead of everything...

**Comment by SimonBrandner** [comment]
This is one of the strings shown in the dialog that is shown when you try to kick someone from a room:

+ `Remove them from everything I'm able to`
+ `Remove them from specific things I'm able to`
+ `They'll still be able to access whatever you're not an admin of.`

![image](https://user-images.githubusercontent.com/25768714/182538695-08bce445-894a-4472-ba45-3d49699dcc31.png)

Is this enough context for you?

**Comment by JokerGermany** [comment]
The problem is, that i don't know if this is user friendly. Do you think EVERY Matrix user knows what you mean with "everything"?
This expects knowledge, which i didn't like.
Perhaps it would good if you could e.g. insert a mouseover event for everything or a the whole line with a Tooltip which explains everything.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22986
