### ISSUE TITLE
Configuration option to set a default message layout i.e. IRC, Modern or Bubbles

### ISSUE THREAD

**Issue by vishu1034** [vector-im/element-web#22973]
#### What would you like to do?
Developers should have the option in configs to set the default message layout i.e. IRC, Modern or Bubbles. Currently the users have to change it explicitly.

#### Why would you like to do it?
Most of the users are more familiar with bubbles layout and this option should be there to set it as a default layout.

#### How would you like to achieve it?
We should be able to define the message layout in the config file of the project.

**Comment by t3chguy** [comment]
It is already possible. https://github.com/vector-im/element-web/blob/develop/docs/config.md#default-settings + https://github.com/matrix-org/matrix-react-sdk/blob/1e4c336fed4d7f76a03b6275bcc09d4d1533d9b5/src/settings/Settings.tsx#L879-L882
