### ISSUE TITLE
Messages not marked as seen, but are in other client

### ISSUE THREAD

**Issue by puddyput** [vector-im/element-web#22972]
### Steps to reproduce

I have set up a bot that sends notifications to a channel.
For testing it sent messages to a "testing" room, now since everything works the messages are sent to "notifications" room.

In each channel the last message by the bot is not marked as seen for my account in Element web.
Both messages include my account handle, in case that matters.
In the Android element client, both messages are marked as seen.
In the web client both messages are marked as new and the unread indicator in the favicon displays 2 unread messages.

Version von Element: 1.11.1
Version von Olm: 3.2.8

### Outcome

I click on one of the rooms to see the message and expect it to be marked as seen and the seen indicator to display no unread messages.

Sometimes it works and the message is marked as read, but this lasts only until I restart the browser. Then both messages are unread again.
There is no way I can mark the message in "testing" as  seen.
 I've tried clearing the cache and the problem is persisting for one week now.

### Operating system

Fedora Linux

### Browser information

Brave / Version 1.41.96 Chromium: 103.0.5060.114 (Offizieller Build) (64-Bit)

### URL for webapp

https://app.element.io/

### Application version

Version von Element: 1.11.1 Version von Olm: 3.2.8

### Homeserver

matrix.phcn.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
To make sure I follow:

+ User/Bot A sends a message to a room
+ User B reads that message on Element Android
+ User B opens Element Web and sees the room as not being read and having pending notifications

Is that correct?

**Comment by puddyput** [comment]
Thank you for looking at this.
There are two rooms involved, "R1" and "R2"
There are two users involved "A" and "B" (B being the bot)
B sends a message each to R1 and R2
A reads both messages in Element Web. 
-> In Web R1 gets marked as seen, no pending notifications
-> In Web R2 does NOT get marked as seen, notification still pending.
-> After cleaning cache&refreshing or browser restart both R1 and R2 show up as unread again in Web
A reads both messages in Element Android
-> both rooms are marked as seen, no pending notification in Element Android
-> Element Web has not changed because of actions in Element Android for R1 and R2.

Interactions with other rooms or chats are synched as expected, e.g. if messages are marked as read in Android in other rooms by other users they are marked as read in Web as well. To me it feels like the issue is between user A and B.

I've seen this issue:
https://github.com/vector-im/element-web/issues/22789
and it made me realize the message from B does @mention user A. I'll see if I can test it without an @A

But: disabling notification does not resolve my issue and it persists for over a week now, so I think it may be related but different.

**Comment by SimonBrandner** [comment]
> User B sends message containing "@A" to R1.
User A sees R1 as having one unread message.
User A opens R1 to see the message, but the message stays "unread" and the room has pending notifications.

I am unable to reproduce the last thing here - the notification clears
