### ISSUE TITLE
Changes is not detect after edit

### ISSUE THREAD

**Issue by WebSofter** [vector-im/element-web#22983]
### Steps to reproduce

I installed the dev version from the link https://github.com/vector-im/element-web#setting-up-a-dev-environment (Setting up a dev environment). Everything started successfully. Next, I try to change the React code from matrix-react-sdk, but nothing happens even after reloading. What am I doing wrong?

### Operating system

Ubuntu Linux VPS

### Browser information

Chrome 104.0.5112.81

### URL for webapp

localhost:8080

### Application version

v1.11.2

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by WebSofter** [comment]
> Support questions for development environments are best asked in the [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org) room on Matrix.
> 
> We'll also need a bit more information once you're there: which files are you trying to change, and what is the console output?

Hi, turt2live. Any changes. For example i changed Welcome page
![image](https://user-images.githubusercontent.com/5724414/182652404-84bbd9d1-2406-40b6-9ad2-5164537c413e.png)
but it is not detect in browser
![image](https://user-images.githubusercontent.com/5724414/182652645-137baa4e-038d-4506-a58b-c0efa12a1b9e.png)

**Comment by t3chguy** [comment]
As per the above, please seek support in the support room, not in the *issue* tracker. It looks like your layers may not be correctly `yarn link`'d or your environment might be missing filesystem watch hooks, does restarting `yarn start` make your change apply?

**Comment by t3chguy** [comment]
Also, did you refresh the browser? We don't run live/hot-reload.

**Comment by WebSofter** [comment]
> does restarting `yarn start` make your change apply?
No, changes don't make a reload. Even manual changes don't take effect.

**Comment by WebSofter** [comment]
> It looks like your layers may not be correctly `yarn link`'d or your environment might be missing filesystem watch hooks

Thanks, that was the problem. Re-added links and it worked 😊
