### ISSUE TITLE
Code tags in a link render with `<code>...</code>` in plaintext

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#22997]
### Steps to reproduce

1. Write a message with the following content:
    ```
    I really like [`this library`](https://library.com).
    ```
2. This gets correctly converted to the following HTML:
    ```
    I really like <a href=\"https://library.com\"><code>this library</code></a>.
    ```
3. See that Element Web renders the above HTML as the following:

    ![image](https://user-images.githubusercontent.com/1342360/182890730-8811370d-76ed-4807-a3d4-a31fc36f1c58.png)

4. When it should have done something like the following instead (link inside a inline code block):

    ![image](https://user-images.githubusercontent.com/1342360/182890838-55f9e22d-4463-464a-8a6c-0dddef86a237.png)

### Outcome

The HTML renders correctly on Element Web version fc6c859976b3-react-a866005bea85-js-d867affc40fb. It renders *incorrectly* on Element Desktop nightly version 2022080201.

@turt2live alluded that this may be related to the "Tooltips when hovering over URLs which don't match their link text" feature, which has been recently disabled(?).

### Operating system

Arch Linux

### Application version

Element Desktop nightly version 2022080201

### How did you install the app?

https://aur.archlinux.org/packages/element-desktop-nightly-bin

### Will you send logs?

No

**Comment by t3chguy** [comment]
Update your Nightly please
