### ISSUE TITLE
The composer has gained padding

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#22992]
### Steps to reproduce

1. Look at the composer

#### What did you expect?

This much padding:

![Screenshot 2022-08-04 at 08-49-44 Element Offline Test room](https://user-images.githubusercontent.com/48614497/182854815-4423e7b8-91dc-412b-af66-c9a731e12386.png)

#### What happened instead?

More padding:

![Screenshot 2022-08-04 at 09-08-13 Element 7 Test room](https://user-images.githubusercontent.com/48614497/182854805-76d706ab-7708-4a12-ad81-f78e508f19c7.png)

### Operating system

NixOS unstable

### Browser information

Firefox 102.0.1

### URL for webapp

develop.element.io

### Application version

Element version: fc6c859976b3-react-a866005bea85-js-d867affc40fb Olm version: 3.2.12

### Homeserver

Synapse 1.63.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Yup, I even accidentally approved it in Percy :L

https://percy.io/dfde73bd/matrix-react-sdk/builds/20253973/changed/1136548332?browser=edge&browser_ids=18%2C22%2C23%2C25&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1920&widths=1024%2C1920

**Comment by weeman1337** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/pull/8612/files#diff-b2786578c92d4cf87798cdc64d2a7a878d17e4324a8aec2fa6c9d4839a612c32R38
