### ISSUE TITLE
`spaces` > `should allow user to create private space` is flaky 

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#23005]
https://dashboard.cypress.io/projects/ppvnzg/runs/3109/test-results/cf23f41c-c494-41e8-8699-7602decddbae

**Comment by t3chguy** [comment]
The test is written poorly, doesn't leverage the Retry behaviour well.

`> 132 |         cy.get(".mx_RoomTile").contains("Random").should("exist");`
Should be more akin to `cy.get(".mx_RoomList").contains(".mx_RoomTile", "Random").should("exist");`
