### ISSUE TITLE
Inconsistent thread delete behaviour

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23004]
### Steps to reproduce

1. Create a thread
2. Delete all messages
3. Create another thread
4. Delete all messages

#### What did you expect?

Consistent behaviour: Either both gone or both with deleted reply

#### What happened instead?

One showing as „deleted“, the other gone

![inconsistent_thread](https://user-images.githubusercontent.com/6216686/183043496-fb880d80-4d12-46d7-ab63-d52092270b93.gif)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 103.0.1

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 3e3f279469ad-react-e864dbfacf01-js-3907d1c28f87 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by gsouquet** [comment]
We have fixed that as part of https://github.com/matrix-org/matrix-react-sdk/pull/9356
