### ISSUE TITLE
Connection to server is lost after login

### ISSUE THREAD

**Issue by k79e** [vector-im/element-web#23019]
### Steps to reproduce

1. start program with proxy `--proxy-server=http://xxxx`
2. After login it always says something like "connection to the server is already been lost". 

### Outcome

Can't use program

### Operating system

Win7 x64

### Application version

1.11.2

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This seems like the proxy is unable to be used, make sure it is a proxy that Chromium supports and the param is in a supported format.

**Comment by k79e** [comment]
After sign out & sign in and obverse for days, it's normal now.
I'll let you know when it unstable again.

**Comment by k79e** [comment]
Happened again.

**Comment by t3chguy** [comment]
Your version is quite out of date, I suggest re-reporting after updating. Also seems like you're on Windows 7 which we no longer support - https://github.com/vector-im/element-desktop/issues/808
