### ISSUE TITLE
Room with Disappearing messages shows notification - no message available

### ISSUE THREAD

**Issue by moan0s** [vector-im/element-web#23011]
### Steps to reproduce

1.   Use an account on a Synapse server that makes use of retention (purges messages)
2. Create a new room
3. Send an m.retention event with a small retention time (here one hour)
```
{
  "type": "m.room.retention",
  "sender": "@xy:example.com",
  "content": {
    "max_lifetime": 3600000
  },
  "state_key": "",
  "origin_server_ts": 1641353041750,
  "unsigned": {
    "age": 17572771043
  },
  "event_id": "$7wf6WmAsADF56w3gPx-TSzeikYbeA-7kro77rT7nE",
  "room_id": "!ABCDEyfgmxxaqWTULn:example.com"
}
```
4. Send some messages
5. Log out and log in after messages have been purged (depends on server configuration).

#### What did you expect?

The room looks as if there never was a message and no notification.

#### What happened instead?

You can see the room where you activated disappearing messages and see a notification (the small white dot). But the room itself is empty as all messages have been purged and there is no way to mark this room as read.
![image](https://user-images.githubusercontent.com/25753802/183037858-e9af3b0f-b3bb-4ec3-a10a-fbd8662e9887.png)

### Operating system

Endeavour OS

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### How did you install the app?

Endeavour OS community repo

### Homeserver

https://synapse.hyteck.de

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Retention is not currently supported client-side.

See https://github.com/vector-im/element-web/issues/3800
