### ISSUE TITLE
Powerlevels are shown as a blank timeline item

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23013]
### Steps to reproduce

1. Create a new private room
2. Expand the 'configuring room' steps
3. Note there's a blank timeline entry, which if you view source turns out to be the join rules:

<img width="569" alt="Screenshot 2022-08-05 at 15 24 21" src="https://user-images.githubusercontent.com/1294269/183097836-52461075-a50b-45e5-af35-add08d4aca47.png">

#### What did you expect?

no mystery blank timeline entries.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
I can only reproduce this if "show hidden events" is turned on. It's technically a feature, though we should be showing the event type at least.

**Comment by t3chguy** [comment]
The join rules event is right below it

`Matthew made the room invite only.`

the invisible event is power levels
