### ISSUE TITLE
"Lazy Loading" > "should handle lazy loading properly even when offline" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23015]
![Screenshot 2022-08-05 at 12-19-38 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/183119489-fd72a479-9ba1-4423-ac2f-b321d998265e.png)
![cypress-screenshot](https://user-images.githubusercontent.com/48614497/183119601-f63d0e95-6806-49c3-a9c0-19af7d08e188.png)

**Comment by t3chguy** [comment]
Do you have a link to the test run? This was fixed recently.

**Comment by robintown** [comment]
Unfortunately no, so I'll presume this is fixed for the moment
