### ISSUE TITLE
Voice messages break when two composers are shown (main + thread)

### ISSUE THREAD

**Issue by grimhilt** [vector-im/element-web#23023]
### Steps to reproduce

1. Start recording a vm either in a thread's composer or in the main composer.
2. Stop this recording.

#### What did you expect?
I would expect to have a vm standing in a thread or in the main chat, waiting to be send, with only one "send button" setup to send this vm.

#### What happened instead?
Even with the other composer empty, both "send button" are active with the note "send a voice message". If I click the send button with the empty composer, I have an error in the console.

### Operating system

Windows

### Browser information

firefox 103.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### Homeserver

custom

### Will you send logs?

No

**Comment by grimhilt** [comment]
I would like to work on this. (I don't expect to be assign).

**Comment by gsouquet** [comment]
@grimhilt How are you getting on with this task?

**Comment by grimhilt** [comment]
Sorry @gsouquet, I didn't see your message, this pr should close this issue
