### ISSUE TITLE
Preserve position in the timeline when closing and reopening Element

### ISSUE THREAD

**Issue by k79e** [vector-im/element-web#23020]
### Steps to reproduce

View a group chat.
Scroll up many pages.
Exit the program.

Start again then the position is lost.

#### What did you expect?
Position should be not lost.
#### What happened instead?
But it losts.

### Operating system

win7 x64

### Application version

1.11.2

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
/duplicate https://github.com/vector-im/element-web/issues/17308
