### ISSUE TITLE
Config parameter: "show_labs_settings" or "showLabsSettings"

### ISSUE THREAD

**Issue by Fail-Unsafe** [vector-im/element-web#23022]
### Steps to reproduce

1. Trying to create a config.json for Element Web
2. Using [config.json](https://github.com/vector-im/element-web/blob/develop/docs/config.md) as an example
3. but at https://app.element.io/config.json the parameter is called "showLabsSettings"

Which one is the right one? I guess it's show_labs_settings.

#### What did you expect?
Hide the Labs settings in Element Web

#### What happened instead?
No matter which parameter I choose, the Labs settings are still there even after a browser refresh.

### Operating system

Ubuntu

### Browser information

Firefox 102

### URL for webapp

own private deployment

### Application version

Element Version 1.10.15

### Homeserver

Synapse 1.63.1

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
> No matter which parameter I choose, the Labs settings are still there even after a browser refresh.

Do you mean the betas are there (the big tiles like threads and video rooms) or the options below? You can't disable betas

> Which one is the right one? I guess it's show_labs_settings.

Both `show_labs_settings` and `showLabsSettings` are correct though `show_labs_settings` is/might be depracted

**Comment by Fail-Unsafe** [comment]
> Do you mean the betas are there (the big tiles like threads and video rooms) or the options below? You can't disable betas

Yes, exactly. I thought I could remove the menu item altogether.

**Comment by SimonBrandner** [comment]
> > Do you mean the betas are there (the big tiles like threads and video rooms) or the options below? You can't disable betas
> 
> Yes, exactly. I thought I could remove the menu item altogether.

That is not possible, sorry. I would recommend opening a new issue for that specifically if you want it to be added

**Comment by dklimpel** [comment]
Which one is deprecated `show_labs_settings` or `showLabsSettings`
The last change was from `showLabsSettings` to `show_labs_settings`
- #21429

**Comment by t3chguy** [comment]
camelCase is deprecated, snake_case is documented: https://github.com/vector-im/element-web/blob/develop/docs/config.md
