### ISSUE TITLE
Jitsi video conference/call: No video (webcam) nor screen share possible in element-desktop

### ISSUE THREAD

**Issue by maxkratz** [vector-im/element-web#23028]
### Steps to reproduce

1. Create a room with more than 2 people in element-desktop.
2. Click the video button at the top to start a Jitsi conference.
3. Try to use the webcam or try to start a screen share.
4. The other people within the call can not see my webcam and I'm unable to choose a window for screen sharing (because the loading wheel spins forever).

![Unbenannt](https://user-images.githubusercontent.com/20956405/183421429-309cf62a-c1aa-4548-b706-03e0324f7351.PNG)

#### What did you expect?

- I did expect to share my video from my webcam.
- I did expect to share my screen and/or choose a window to share in the Jitsi widget.

#### What happened instead?

- I can start my webcam (video) stream but the other people can not see it.
- I cannot choose a window or a display to share with the others.
- **Interestingly, both features do work with element-web.**

I've tested it with element-desktop on Windows 10 and element-desktop on Linux Mint 20.3. The version for the web browser (element-web) is not affected, AFAIK. I also tested this on two different home servers both running the currently latest stable version of the Synapse.

**Moreover, I'm sure that both features (video share of the webcam feed and screen sharing) worked in a previous version of element-desktop.**

### Operating system

Windows 10, Linux Mint 20.3

### Application version

Element version: 1.11.2; Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#download

### Homeserver

{"server":{"name":"Synapse","version":"1.64.0"}}

### Will you send logs?

No

**Comment by t3chguy** [comment]
Lack of screen sharing is #4880 - can you show screenshots of the webcam not working?

**Comment by maxkratz** [comment]
> Lack of screen sharing is #4880 - can you show screenshots of the webcam not working?

On my side, it looks like the webcam video feed is working but all other participants only see my initials. This also occurs vice-versa.

Unfortunately, we were unable to reproduce it right now (the webcam video stream did work like a charm) -.-

**Comment by duxovni** [comment]
FWIW, Jitsi does sometimes disable some people's camera feeds when your connection is flaky; did you see an icon like ![Jitsi's "connection inactive" icon](https://raw.githubusercontent.com/jitsi/jitsi-meet/master/react/features/base/icons/svg/ninja.svg) or a poor connection icon when your webcam feed wasn't working?

**Comment by maxkratz** [comment]
> FWIW, Jitsi does sometimes disable some people's camera feeds when your connection is flaky; did you see an icon like ![Jitsi's "connection inactive" icon](https://raw.githubusercontent.com/jitsi/jitsi-meet/master/react/features/base/icons/svg/ninja.svg) or a poor connection icon when your webcam feed wasn't working?

Oh, interesting thought. I can't remember it, but if it occurs again, I will post a reply here. Thank you!

**Comment by t3chguy** [comment]
Closing until reproduced, using #4880 as the issue for desktop sharing
