### ISSUE TITLE
Default Ubuntu install is just white

### ISSUE THREAD

**Issue by niccokunzmann** [vector-im/element-web#23031]
### Steps to reproduce

1. I went into the software repository program. 
    ![](https://user-images.githubusercontent.com/564768/183508108-36ef92d9-871b-43e2-ae95-5cf54237c5a8.png)
2. I clicked on install
3. There was no "OPEN" button next to the bin
4. When I stated it manually, it just opened an icon in the task bar
5. When I opened it through the icon, it was blank - just white

#### What did you expect?

I expect to open it and show something.

### Operating system

Ubuntu 22

### Application version

1.10.12

### How did you install the app?

Software program built into Xubuntu 22

### Will you send logs?

No

**Comment by 3nprob** [comment]
Related: #18168 #22690 #22477 #21541

**Comment by niccokunzmann** [comment]
Could be a duplicate - I just opened it.
I installed it from https://element.io/get-started#linux-details and it works.

**Comment by MadLittleMods** [comment]
Thanks for all of the links @3nprob!

Looks closely related to https://github.com/vector-im/element-web/issues/22477 which is also recent ⏩

@niccokunzmann There are some debugging steps in https://github.com/vector-im/element-web/issues/22477#issuecomment-1149535148 if you can still reproduce and post your results there.
