### ISSUE TITLE
Element desktop app lost its border / decorations

### ISSUE THREAD

**Issue by thomaseizinger** [vector-im/element-web#23033]
### Steps to reproduce

1. Open the Element desktop app.
2. Observe no decorations (i.e. no close and minimize buttons, etc)

#### What did you expect?

A window that has decorations and looks consistent with other windows in Gnome.

#### What happened instead?

A borderless window.

### Operating system

Manjaro Linux with Gnome DE

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### How did you install the app?

Manjaro community repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment]
@thomaseizinger

 - Is the page still interactive like normal?
 - Can you provide a screenshot?
 - Is this consistently reproducible now every time you open the app?
 - When did this start happening? Did it coincide with an Element update or system update?

**Comment by thomaseizinger** [comment]
This seems to have been an issue with the dependencies installed through my package manager. A wash of updates came in today, including one for electron19 which fixed the issue.
