### ISSUE TITLE
@room has two room icons in pill

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23036]
### Steps to reproduce

1. Send a message
2. Edit the message and include @room in the edited message

#### What did you expect?
Normal working pill

#### What happened instead?
There are two room avatars in the pill

![Screenshot from 2022-08-09 11-56-27](https://user-images.githubusercontent.com/51663/183632445-b27db9ef-6a5b-44ce-98b7-515e58c3b33d.png)

### Operating system

Arch Linux

### Browser information

Chromium 104.0.5112.79

### URL for webapp

develop.element.io

### Application version

Element version: 0ed179d94c9f-react-7eaed1a3f870-js-6316a6ae4462 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
No evidence this is a regression, this code is old
