### ISSUE TITLE
Error joining Room within a Space

### ISSUE THREAD

**Issue by ProactiveServices** [vector-im/element-web#23044]
### Steps to reproduce

1. Clicked on to the Libre Gaming Space
2. Clicked to join the "Games" Room

#### What did you expect?
To join the Room

#### What happened instead?
Element threw the "Something went wrong!" page, asking to submit an issue.

### Operating system

Ubuntu 20.04.4

### Application version

Element 1.11.2

### How did you install the app?

https://packages.riot.im/debian apt repo

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ProactiveServices** [comment]
After clicking the "Clear cache and reload" button in the error window, it appears that the join succeeded.

**Comment by ProactiveServices** [comment]
This seems to be reproducible; from the Opensource_gaming Space I clicked to join the General Room and encountered the error. Before clicking the "Clear cache and reload" I checked on my Android mobile and saw that I had been joined.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22752
