### ISSUE TITLE
Can't start DM with a sticker if room doesn't exist yet

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23047]
### Steps to reproduce

For an account without sticker packs,

1. Following the new DM flow, start a new DM (room isn't created yet)
2. Try to send a sticker
3. Go through process to get sticker packs, get "Sorry, but you do not have permission to add widgets in this room" error message

#### What did you expect?
Can add a sticker pack or can't attempt to send a sticker if I have no packs added

#### What happened instead?
"Sorry, but you do not have permission to add widgets in this room"

### Browser information

Chromium 104.0.5112.79 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 9c36adc4dfe8-react-3b64a7999c79-js-e29e0d15a571 Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
Marking as Major due to the confusing error and non-obvious workaround of first sending a different type of message

**Comment by weeman1337** [comment]
What are we going to do about this? Disable stickers for the first message? Because once you have the sticker picker you can reach the integration manager. And it doesn't make sense for local rooms.

Alternatively we can make at least the sticker integration work for local rooms. But I don't know if this is possible (with reasonable effort).

**Comment by kittykat** [comment]
I would advise disabling stickers as a first message for now, wdyt @giomfo ?

**Comment by giomfo** [comment]
> I would advise disabling stickers as a first message for now, wdyt @giomfo ?

yes this sounds the right plan for now

**Comment by weeman1337** [comment]
@gaelledel gave her okay in behalf of design to hide the sticker button for local rooms
