### ISSUE TITLE
Subspaces aren't indented

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23049]
### Steps to reproduce

1. Expand the space panel
2. Click the 'expand' arrow next to a top-level space to reveal its subspaces

#### What did you expect?

The subspaces should be indented further than the top-level space

#### What happened instead?

They have matching indentation

![Screenshot 2022-08-10 at 08-42-38 Element 1 tooling](https://user-images.githubusercontent.com/48614497/183904420-b6802050-5823-42ad-87ec-b740f6bbf32b.png)

This was probably regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9157

### Operating system

NixOS unstable

### Browser information

Firefox 102.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 9c36adc4dfe8-react-3d0982e9a603-js-8f13df2dd986 Olm version: 3.2.12

### Homeserver

Synapse 1.63.1

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9157
