### ISSUE TITLE
Element keeps crashing when I click "I am the host" in Jitsi widget

### ISSUE THREAD

**Issue by Sojjjik** [vector-im/element-web#23042]
### Steps to reproduce

We have self-hosted Jitsi server. This server is specified in .well-known/matrix/client. So, when I create a video-chat with phone, element uses our self hosted link. On jitsi server we have enabled auth. When you create a video-chat you recieve a message like "we need to wait a host". You can press "I am the host". You just press this button, enter password and that's it. It used to work.  Now, when you press "I am the host" element stops working

1. Create a video conference in element from Android phone. Self hosted jitsi with enabled auth.
2. Enter to this conference.
3. Press "I am the host"
4. Element stops working

**_When I press "I am the host" from PC, everything works fine._**

#### What did you expect?
Enter to video conference as a host
#### What happened instead?
Element stops working

### Operating system

Android

### Application version

Element - 1.4.31, OLM - 3.2.12

### How did you install the app?

Google Play

### Homeserver

Self-hosted server. server_version	"1.64.0"

### Will you send logs?

No

**Comment by t3chguy** [comment]
> When I press "I am the host" from PC, everything works fine.

Sounds like your issue is not with element-web (this repo) but with https://github.com/vector-im/element-android
