### ISSUE TITLE
Disable some notification targets from the list

### ISSUE THREAD

**Issue by ylecollen** [vector-im/element-web#2304]
Peter Vágner reported it.

It makes sense : it would be nice to be able to manage the notified target even if it is only allowed from the web client.

I don't create this issue on Android or IOS project because i assume it will require some server APIs updates.

**Comment by ara4n** [comment]
@ylecollen / @pvagner - I'm not understanding what the suggestion here is...

**Comment by ldexterldesign** [comment]
FYI IMO this issue should be closed in favour of https://github.com/vector-im/riot-web/issues/3438

Regards

**Comment by andy5995** [comment]
I'm not sure #3438 is a duplicate. Right now I have 2 separate target notification emails listed in my settings and would like to remove one of them. But the option isn't present.

Seems more related to #5496

**Comment by kittykat** [comment]
I'm going to close this issue for now as the UI has changed and it should now be possible to do what the original issue was asking for. If needed, please open a new issue with more details for further improvements.
