### ISSUE TITLE
Tombstone command/UI

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#23054]
#### What would you like to do?

Tombstone a room using a command rather than having to send a custom state event in devtools. 

#### Why would you like to do it?

Doing it in devtools and/or making an external script is annoying.

#### How would you like to achieve it?

A dialog box on the UI for this would be ideal, but even a `/tombstone !replacement_room_id Reason` command would be better than nothing.

### Have you considered any alternatives?

devtools

**Comment by olmari** [comment]
You do have /upgraderoom which is mainly what actually utilizes tombstoning in the process. Usually tombstone alone is not what is wanted, while doable.

**Comment by turt2live** [comment]
The spec really doesn't want people to be tombstoning rooms without upgrades, so I don't think this is a feature we can support at this time.
