### ISSUE TITLE
Disabling historical rooms

### ISSUE THREAD

**Issue by iambeingtracked** [vector-im/element-web#23056]
#### What would you like to do?
I would like to disable historical rooms.
#### Why would you like to do it?
Because I don't need that functionality and it kind of annoys me.
#### How would you like to achieve it?
Remove the Historical rooms list by triggering an option in the settings.

### Have you considered any alternatives?

Hiding it with some kind of an extension

### Additional context

I first thought that it was a server side thing (see https://github.com/matrix-org/synapse/issues/13401), but it isn't

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/14038

**Comment by nadonomy** [comment]
Thanks for submitting! I'm closing this in favour of #14038 as it's unlikely we'd add an explicit setting for this.

The reach/impact isn't clear and in the linked issue there's more involved discussion & thoughts on how we could solve this more elegantly and holistically for more users.
