### ISSUE TITLE
Eleweb incorrectly reports "The sender has disabled encrypting to unverified devices"

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#23065]
### Steps to reproduce

1. Have an unverified device
2. Receive an E2E message from a use who does *not* have "Never send encrypted messages to unverified sessions from this session" enabled
3. Observe error

#### What did you expect?

Message received as normal

#### What happened instead?

"** Unable to decrypt: The sender has disabled encrypting to unverified devices. **"

![image](https://user-images.githubusercontent.com/1389908/184341450-797339e2-02d4-4194-84ae-61d8f29c06fb.png)

(@neilisfragile swears he does not have "Never send encrypted messages to unverified sessions from this session" enabled)

### Operating system

Ubuntu 22.04

### Application version

Element Nightly version: 2022080901 Olm version: 3.2.12

### How did you install the app?

nightly debian

### Homeserver

Synapse 1.61.0

### Will you send logs?

Yes

**Comment by richvdh** [comment]
(the reason my device is unverified is https://github.com/vector-im/element-web/issues/22962)

**Comment by t3chguy** [comment]
@neilisfragile it is worth pointing out that the option is available both at an account and a room level, worth checking both just in case

**Comment by neilisfragile** [comment]
<img width="791" alt="Screenshot 2022-08-12 at 13 16 07" src="https://user-images.githubusercontent.com/451032/184352131-a955b2e0-b1cf-4569-b275-d408587a6955.png">

**Comment by neilisfragile** [comment]
@t3chguy Best I can tell both global and room settings are set to ignore that a session is unverified. 

I've submitted logs.

**Comment by t3chguy** [comment]
@neilisfragile please update your nightly, you're four days out of date and running a reverted change which caused this issue on partial-verificated peers - https://github.com/matrix-org/matrix-js-sdk/pull/2571
