### ISSUE TITLE
mx_ReadReceiptGroup shows avatar placeholder of a user that does not exist

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#23062]
### Steps to reproduce

I'm seeing this read receipt:
![image](https://user-images.githubusercontent.com/2803622/184247994-c9ad25d5-bdde-4045-b065-dd6cc4173448.png)

 1. ✅ The left one uses the correct avatar of a user in the room. (appears in "seen by" tooltip text)
 2. ❌ The center one uses a placeholder avatar with an `S` on purple background. There is no user in this room that uses a displayname starting with `S`. Further, the only other user without an avatar image set is shown with a green placeholder and the letter `Z`.
    - Now as read receipts have updated that appears confirmed:
    ![](https://user-images.githubusercontent.com/2803622/184249070-d04579bd-e4d4-4186-a13e-11166f725410.png)
 3. ✅ The right one is the correct placeholder for a user with displayname set to `♠` and no avatar image set on their account. (appears in "seen by" tooltip text)

---

Assuming that for some reason avatars and displaynames were not loaded in time to display the receipt correctly, there is one user that uses an mxid starting in lower case `s`, however as per dev tools, it is definitely an upper case S: `<span class="mx_BaseAvatar_initial" aria-hidden="true" style="font-size: 9.1px; width: 14px; line-height: 14px;">S</span>`.

The only remaining option is the aforementioned user with the `♠` displayname: their color is purple and their (legacy) mxid begins in upper case `S`.

#### What did you expect?
show proper receipts

#### What happened instead?
maybe duplicated read receipt + potentially causing rendering bug?

### Operating system

arch

### Application version

Element Nightly version: 2022081002 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment]
>  there is one user that uses an mxid starting in lower case s, however as per dev tools, it is definitely an upper case S

The placeholder avatars will [always be uppercase](https://github.com/matrix-org/matrix-react-sdk/blob/4a5ed2f89916d8dca106ef1717ac39707296febe/src/Avatar.ts#L132) regardless of the MXID casing.

---

When an avatar fails to load, we [fallback to the next one](https://github.com/matrix-org/matrix-react-sdk/blob/4a5ed2f89916d8dca106ef1717ac39707296febe/src/components/views/avatars/BaseAvatar.tsx#L79-L81) if available (like thumbnail and full size) and when we run out, it uses the placeholder avatar.

Did the user with the lower-case `s` MXID read the message? It sounds like we had to fallback to placeholder avatar for some reason.

Check your devtools network tab to see the failed avatar image requests.

**Comment by HarHarLinks** [comment]
> Did the user with the lower-case `s` MXID read the message?

They did (they are currently the only one to not have their read marker moved on), but...

> When an avatar fails to load, we [fallback to the next one](https://github.com/matrix-org/matrix-react-sdk/blob/4a5ed2f89916d8dca106ef1717ac39707296febe/src/components/views/avatars/BaseAvatar.tsx#L79-L81) if available (like thumbnail and full size) and when we run out, it uses the placeholder avatar.

...if I understand correctly, it should fall back to the next user? Why didn't it then fall back to one of the +5 (see screenshot in OP) minus `Z` options?

Now regardless, why does the avatar fail at all, when other thumbnail sizes of it have loaded correctly, e.g. in this dialogue? Let me mention that this user is local to my hs, so there really shouldn't be much of an issue loading any image?
![image](https://user-images.githubusercontent.com/2803622/184352267-2a39d9b2-74d2-436c-9cb7-370b38517cbf.png)
Why would their upper-cased mxid be used over their displayname? Is it because they use some (admittedly strange) unicode in their displayname? Why would that not display on the fallback avatar?

**Comment by MadLittleMods** [comment]
> ...if I understand correctly, it should fall back to the next user? Why didn't it then fall back to one of the +5 (see screenshot in OP) minus Z options?

It doesn't fallback to the next user. It just fallsback to another image alternative given which in some cases for example we try the thumbnail size first and if that fails, try to use the full size, and if that fails, use the placeholder fallback.

> Now regardless, why does the avatar fail at all, when other thumbnail sizes of it have loaded correctly, e.g. in this dialogue? Let me mention that this user is local to my hs, so there really shouldn't be much of an issue loading any image?

A request can fail intermittently. It could have failed when the read reciept was created but then later was successful when you opened the "seen by".

> Why would their upper-cased mxid be used over their displayname? Is it because they use some (admittedly strange) unicode in their displayname? Why would that not display on the fallback avatar?

You can see the [logic linked](https://github.com/matrix-org/matrix-react-sdk/blob/4a5ed2f89916d8dca106ef1717ac39707296febe/src/Avatar.ts#L132). Given we didn't have their avatar, it's possible we didn't have their profile at all so we didn't have their displayname.

Given we can't see the actual MXID's and displaynames, it's very hard to reason about exactly what happened.

In any case, a user that has a `s` in their MXID read the message and we used the placeholder avatar. It could have failed in an unlimited amount of ways and Element coped with what it had available so I'm going to close this issue.
