### ISSUE TITLE
Online indicator

### ISSUE THREAD

**Issue by Gitogitos** [vector-im/element-web#23073]
### Your use case

I wanna ask it would be possible to add some sort of beacon that people which we have on the list are currently online? Really miss this function. It would be useful. Cause now when I write message I don’t know when will get reply. Or maybe even implement the some form of status like online, busy, offline.

**Comment by SimonBrandner** [comment]
On what homeserver are you? You can find it in `Help & About` > `Advanced`

**Comment by t3chguy** [comment]
<img width="52" alt="image" src="https://user-images.githubusercontent.com/2403652/184597834-092dcc8b-d4a3-45f3-9be6-bf6f90af2e49.png">

This already exists but requires your server to not have disabled it.
