### ISSUE TITLE
Not able to login using my homeserver on Element desktop apps (macOS)

### ISSUE THREAD

**Issue by jalemann** [vector-im/element-web#23070]
### Steps to reproduce

1. Where are you starting? What can you see?
Starting at the welcome screen of the element app.

2. What do you click?
'Sign In' > Edit homeserver > Select 'Other homeserver' > type `matrix.alemann.dev` or `https://matrix.alemann.dev` > 'Continue'

3. Error 'Homeserver URL does not appear to be a valid Matrix homeserver' is shown.

4. View > Toggle Developer Tools brings up the developer tools console which shows the following errors:
4.1 `Access to XMLHttpRequest at 'https://matrix.alemann.dev/_matrix/client/versions' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
4.2 `Invalid /versions response`
4.3 `Error processing homeserver config: {state: 'FAIL_ERROR', error: 'Homeserver URL does not appear to be a valid Matrix homeserver', base_url: 'https://matrix.alemann.dev'}`
4.4 `Attempted matrix.alemann.dev as a server_name but it failed Error: Homeserver URL does not appear to be a valid Matrix homeserver
    at y (languageHandler.tsx:61:19)
    at h.buildValidatedConfigFromDiscovery (AutoDiscoveryUtils.tsx:229:27)
    at y.deriveData (ServerPickerDialog.tsx:93:61)
    at async y.validate (Validation.tsx:95:44)
    at async _.validate (Field.tsx:215:24)`
4.5 `GET https://matrix.alemann.dev/_matrix/client/versions net::ERR_FAILED 301`

5. I am having this error on the element app for around 2 weeks, the element nighlty app worked for me for like the last week but now it also shows the error (using the given version).
6. Other clients (including Element Web, Element iOS, Nheko macOS) work for me.
7. `curl https://matrix.alemann.dev/_matrix/client/versions` returns `{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0.6.1","v1.1","v1.2"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666.mutual_rooms":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false,"org.matrix.msc3026.busy_presence":false,"org.matrix.msc2285":false,"org.matrix.msc3827":false,"org.matrix.msc2716":false,"org.matrix.msc3030":false,"org.matrix.msc3440.stable":true,"fi.mau.msc2815":false}`
8. I don't know anything about CORS which was mentioned in the developer console error but `curl -I https://matrix.alemann.dev/_matrix/client/versions` shows 
```
HTTP/2 200  
server: nginx 
date: Sun, 14 Aug 2022 09:31:56 GMT
content-type: application/json
cache-control: no-cache, no-store, must-revalidate
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
access-control-allow-headers: X-Requested-With, Content-Type, Authorization, Date
permissions-policy: interest-cohort=()
strict-transport-security: max-age=31536000; includeSubDomains
x-xss-protection: 1; mode=block
``` where the `'Access-Control-Allow-Origin' header` mentioned in the error seems to be present.

### Outcome

#### What did you expect?
I expected to be able to login as usual on the Element desktop apps.

#### What happened instead?
Element wouldn't let me choose my homeserver and shows that it doesn't appear to be a valid homeserver URL.

While I don't have much knowledge about server hosting yet and it might be the case that I just messed something up on my side, I wanted to still address this issue as other clients work just fine and I couldn't find any misconfigurations using the shown error messages.

I was not able to send logs as typing `/rageshake` in the developer console after the error returned `Uncaught SyntaxError: Invalid regular expression: missing /`. Please let me know if I did it wrong or if I can send other logs.

### Operating system

macOS

### Application version

Element Version 1.11.2, Element Nightly Version 2022081301

### How did you install the app?

https://element.io/get-started

### Homeserver

alemann.dev (Synapse 1.64.0)

### Will you send logs?

No

**Comment by jalemann** [comment]
Just updated to Synapse 1.65.0 and the issue persists

**Comment by jalemann** [comment]
Okay so the issue was something with Elements Cache. I had Cloudflare as a proxy some time ago and Element still had a cached route to cloudflare instead of my actual server.

Solution:
1. Quit Element
2. Delete Elements directory in Application Support (~/Library/Application Support/Element)
3. Restart Element and try again

**Comment by t3chguy** [comment]
The underlying Chromium within Electron will be respecting whatever Cache TTL was previously sent out by Cloudflare, its possible that it had a silly TTL which was causing this issue.

**Comment by jalemann** [comment]
I see. TTL was set to Auto at Cloudflares dashboard but still it's weird because the max TTL seems to be 1 day whereas this issue persisted for almost two weeks.
