### ISSUE TITLE
Weird leave DM historical room / search behaviour

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23074]
### Steps to reproduce

1. Start a DM with someone
2. Leave the room

#### What did you expect?

- Room is gone. Or in historical section.
- If in historical rooms it should be consistent between reloads.

#### What happened instead?

- After leaving the room it shows up in historical section
- Reload
- It shows up as empty room
- Reload
- It is gone

The points above apply to the search as well.

![historical](https://user-images.githubusercontent.com/6216686/184590776-75b1fce6-3f7a-43da-8b4f-4a1c130db7d8.gif)

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element version: 39eee10c576f-react-8db7766a4012-js-3f6f5b69c7a1 Olm version: 3.2.12

### How did you install the app?

https://develop.element.io/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> If in historical rooms it should be consistent between reloads.

This is intentional due to performance overhead, the historical section is due to be extracted into an archived rooms section - https://github.com/vector-im/element-web/issues/14038
