### ISSUE TITLE
Link tooltip gets stuck if app loses focus

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#23086]
### Steps to reproduce

1. Find / make a message with a link that that triggers the tooltip
2. Click the link. Link opens in separate browser.
3. Move mouse, tooltip disappears.
4. Focus the element app again
5. Tooltip reappears and stays there until you click something.

#### What did you expect?
Tooltip to disappear as soon as the app loses focus, probably

#### What happened instead?
See repro steps

### Operating system

macOS

### Application version

Nightly version: 2022081601

### Will you send logs?

No

**Comment by t3chguy** [comment]
The link tooltips are going away - https://github.com/vector-im/element-web/issues/22875#issuecomment-1225511170
