### ISSUE TITLE
Element spams profile and device list get requests every 2 seconds

### ISSUE THREAD

**Issue by tulir** [vector-im/element-web#23085]
### Steps to reproduce

1. Open the app

#### What did you expect?

Element doesn't spam requests (except maybe sync)

#### What happened instead?

Element calls `GET /_matrix/client/r0/profile/%40tulir%3Amatrix.org` and `GET /_matrix/client/r0/devices` every 2 seconds

![image](https://user-images.githubusercontent.com/4224639/184889695-458c0808-27d2-4acf-ad74-37b5e9e9aa0e.png)

The source seems to be `useUserOnboardingContext` https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/hooks/useUserOnboardingContext.ts

### Operating system

Ubuntu

### Browser information

Firefox 104

### URL for webapp

develop.element.io

### Application version

Element version: 39eee10c576f-react-9bf77963ee5e-js-3f6f5b69c7a1 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by justjanne** [comment]
This is kind of an expected tradeoff, we want to be able to update quickly if a user has completed an onboarding task, even if that was done on a different device.
