### ISSUE TITLE
Logging into the web client with access token instead of password.

### ISSUE THREAD

**Issue by vishu1034** [vector-im/element-web#23091]
#### What would you like to do?
I was just wondering if it is possible to pass an access token instead of password to login which we can  securely get from the synapse admin endpoint "/_synapse/admin/v1/users/<user_id>/login"

#### Why would you like to do it?
I have made some endpoints which implements a kind of otp authentication. So the user just needs to enter his/her username and after verifying the otp, i am generating an access token for that user with the synapse login endpoint.

Now I want to be able to send this access_token to the client and my web client can somehow autofill this and  directly login the user. So now there is no password involved in the login process.

**Comment by t3chguy** [comment]
Not via the UI, you can use `mxLoginWithAccessToken(hsUrl, accessToken)` in the console, or fork the app and add a way to do it yourself. Access token login doesn't pass the deviceId, doing so would make it very easy to brick your encryption. This is not a feature that users can use safely.

I suggest you look into the SSO mechanisms in Matrix instead, those can easily be wired up to OTP via the likes of Keycloak and auth0

**Comment by genofire** [comment]
Does not work, it creates an broken e2e state:
```
Unable to initialise e2e Error: Cannot enable encryption on MatrixClient with unknown deviceId: ensure deviceId is passed in createClient().
```

**Comment by genofire** [comment]
Is there something equal on element-android ?

**Comment by t3chguy** [comment]
@genofire this isn't a support forum. I suggest asking the relevant Matrix room for that project.
