### ISSUE TITLE
Reading message in open thread not picked up

### ISSUE THREAD

**Issue by mtausig** [vector-im/element-web#23098]
### Steps to reproduce

1. Activate the *Threads* beta
2. Open a room
3. Reply to a message with a thread
4. Leave the thread open an move the window to the background
5. Somebody replies to the thread
6. The room name is set in bold, indicating an unread message
7. Return to the Element Window
8. Click anywhere in the window (room. thread panel, message field)
9. The room name still indicates an unread message
10. Close the thread panel
11. Reopen the same thread panel
12. The room name is not bold anymore, indicating the reply in the thread is considered to be read

#### What did you expect?

If I activate the Element window with an open thread, if should take that as the message being read. That would be the same behaviour that Element shows without threads.

Steps 9-11 should not be there

#### What happened instead?

I had to perform the useless steps 10 and 11 in order to convince Element that I have read the response

### Operating system

Windows 10

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### Homeserver

Synapse

### Will you send logs?

No

**Comment by uhoreg** [comment]
I think this is a dup of https://github.com/vector-im/element-web/issues/21798 or https://github.com/vector-im/element-web/issues/21114

**Comment by mtausig** [comment]
I disagree, that this is a duplicate of the issues mentioned. Those two describe problems with notifications that should not be there at all or that can't be removed, while my problem describes real notifications whose "read" status can only be changed in an unexpected way.
