### ISSUE TITLE
multi party "pre-DM" screen incorrect subheader

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23094]
### Steps to reproduce

1. Create a DM with Bob and Alice
2. Land on the "pre-DM" screen

### Outcome

```diff
Header: Bob and Alice 
-Caption: Send you first message to invite Bob to chat
+Caption: Send you first message to invite Bob and Alice to chat 
```

### Will you send logs?

No

**Comment by gsouquet** [comment]
@kittykat i'm not sure that qualifies as a regression. It's a bug that happens only in the pre-DM screen and that did not exist beforehand.

**Comment by kittykat** [comment]
I feel that it is a regression because the old flow had correct strings, and the new flow introduced one that was wrong
