### ISSUE TITLE
No feedback when waiting for the server on a /delete_devices request with SSO

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#23096]
### Steps to reproduce

1. Select devices to delete
2. Click on the "Sign out X selected devices" button
3. Auth via UIA (SSO in my case)
4. Click the button to confirm you want to sign out devices

#### What did you expect?

A spinner or some kind of indicator to show Element has sent the request and is waiting for the response.

#### What happened instead?

Nothing, until the server responded (15s later) at which point the modal closed. It was fairly confusing because I thought I was hitting a bug and my device deletion request wasn't going through whereas it actually did but the server just took a while to respond.

### Operating system

Arch Linux

### Browser information

Firefox 103.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 39eee10c576f-react-9bf77963ee5e-js-3f6f5b69c7a1, olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
@babolivier is that using the new session manager or the old one?

<img width="716" alt="image" src="https://user-images.githubusercontent.com/2403652/185095345-3cd44af6-dc18-4eb9-bf67-3e1f20b9aa1e.png">

If the old one then can you see whether it occurs the same with the new one?

**Comment by babolivier** [comment]
> is that using the new session manager or the old one?

It's using the old one, TIL that the new one is available in labs.

I'm happy to try with the new one but when using it I can't seem to be able to do any operation on another session only to see the list of existing sessions (if you're talking about the "Sessions" tab in the settings that appears when I turn on the labs flag).

**Comment by t3chguy** [comment]
@kerryarchibald could this issue be taken into account for the impl of the new session manager?

**Comment by kerryarchibald** [comment]
https://user-images.githubusercontent.com/3055605/185109605-d50f1896-d2a2-45fb-bd70-d23d3f9bcfcf.mov

I don't follow exactly what step the spinner is missing, both the modal and the sessions list show a spinner here ^

**Comment by anoadragon453** [comment]
I also ran into this today with the new session manager after waiting for a particularly long-running `/_matrix/client/r0/delete_devices` request. Specifically I'm waiting on this screen:

![image](https://user-images.githubusercontent.com/1342360/211514895-1ddb05af-184f-46a3-85a7-388faf751622.png)

I think it'd be nice for the "Sign out devices" button to turn into a spinner while the request is carried out.

**Comment by t3chguy** [comment]
This is not fixed in the Beta Session manager
