### ISSUE TITLE
Unable to establish audio/video connection

### ISSUE THREAD

**Issue by Lalilalulalam** [vector-im/element-web#23092]
### Steps to reproduce

1. Initiate connection within private room;
2. _Connecting_ hangs indefinitely

#### What did you expect?
Connection to go through

#### What happened instead?
Hangs at connecting after accepting a call

### Operating system

Windows, Linux, Android

### Application version

1.11.3

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Could you please send logs, without them there isn't much we can do here...

**Comment by Lalilalulalam** [comment]
I just did, hope you're able to access them.

**Comment by SimonBrandner** [comment]
Is this a 1:1 call or a group call,

**Comment by Lalilalulalam** [comment]
This is 1:1 call issue, however haven't checked group yet, since I use it less frequently.

**Comment by SimonBrandner** [comment]
Would the other side be willing to share their logs?

**Comment by Lalilalulalam** [comment]
The other side was using Element for Android, but sure. We can arrange that.

**Comment by Lalilalulalam** [comment]
I have just sent logs from Android device; in the description i have put link to this issue.

**Comment by Lalilalulalam** [comment]
Problem disappeared after recent update.
