### ISSUE TITLE
"Cryptography" > "setting up secure key backup should work" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23101]
https://dashboard.cypress.io/projects/ppvnzg/runs/3472/test-results/a62d558f-2e76-409d-bfa5-d516fbba61f1

![Screenshot 2022-08-17 at 10-31-55 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/185161637-eb63fb44-de0b-42aa-801f-e9a1dc1111aa.png)

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
