### ISSUE TITLE
HTML code added to output rendering when editing a MarkDown list containing a domain name

### ISSUE THREAD

**Issue by mtausig** [vector-im/element-web#23104]
### Steps to reproduce

1. Create a Markdown list in a message
2. One of the items contains a dot, so that it is interpreted as a Link to some domain
3. Edit the list and append an item
4. The item containing the domain name (which has not been edited) is now displayed with some unexpected HTML code (`<span><div tabindex="-1" class="mx_TextWithTooltip_target">foo.eu</div></span>`), which is also not shown in the source code of the message
 
This is what the original message looked like:

![image](https://user-images.githubusercontent.com/1511226/185339107-518ce52b-cdac-4b64-9d30-c558e3df877c.png)

This is how the message looks like after an item has been appended:

![image](https://user-images.githubusercontent.com/1511226/185339155-5412bf5c-1942-4db4-b542-ac76c40e308e.png)

This is what the source of the message looks like, when I click on `Edit`:

![image](https://user-images.githubusercontent.com/1511226/185339692-301af4b1-a99a-4bbe-bcf8-c04e6ba94ae6.png)

This issue is obviously related to #10725

#### What did you expect?

The list item should remain unchanged or at least rendered as typed

#### What happened instead?

HTML code is shown in the output rendering

### Operating system

Windows

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### Homeserver

Synapse homeserver

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please update to 1.11.3
