### ISSUE TITLE
[Spaces] Something wrong happens when I join a room listed in a sub-space without joining the sub-space before

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#23114]
### Steps to reproduce

I reproduced it several time 

- explore the rooms of a joined space
- decide to join a room listed under a sub-space whereas the sub-space is not joined yet
- the room is joined, but Element desktop prompts the user something wrong happened and suggests reporting a bug

### Outcome

the joined room should be displayed

### Will you send logs?

No

**Comment by giomfo** [comment]
Version 1.11.3

**Comment by t3chguy** [comment]
This should be fixed on develop. If you see it on develop or 1.11.4 then please send logs, cannot chase a crash without logs

**Comment by giomfo** [comment]
(I didn't send logs because it was easy to reproduce, I will send logs next time 😉 )
