### ISSUE TITLE
Cannot edit state events with event type <empty string>

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#23115]
### Steps to reproduce

1. Open a chat and type `/devtools` into the composer. Press Enter.
2. Click on "Explore room state" and "Send custom state event"
3. Type in some random content, but don't give fill in the "Event Type" field.
4. Click "Send".
5. Go back to the "Explore room state" view that lists all state event types.

### Outcome

![Screenshot_2022-08-19_15-46-39](https://user-images.githubusercontent.com/10872136/185646709-b7237a54-9f7b-4d88-ab71-93992e1cd5a3.png)

#### What did you expect?
(I was surprised that an empty string is a valid state event type.)

There's a new button labelled "<empty string>", similar to how it exists for empty state keys.
Clicking on the button behaves the same as clicking the buttons of other event types.

#### What happened instead?

The button doesn't have the correct height, has no label and nothing happens when clicking it.

### Operating system

irrelephant

### Browser information

Mozilla Firefox 104.0b9

### URL for webapp

private and develop.element.io

### Application version

Element version: 1.10.12 and a302dba006f5-react-488babaf6575-js-3ae974e23e41

### Homeserver

Synapse from May 2022

### Will you send logs?

No

**Comment by turt2live** [comment]
An empty string is exceedingly silly, but valid, as an event type ftr. Given this affects development tooling I'm not (personally) concerned over it existing as a bug.
