### ISSUE TITLE
Some messages in room cannot be decrypted

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#23124]
### Steps to reproduce

1. Invite a second identity of yourself to a room with some other people
2. Accept invitation
3. Observe the ongoing conversation

#### What did you expect?
I would expect the second identity to be a full participant of the ongoing conversation from the moment of joining, while not being able to see the history before.

#### What happened instead?
The second identity sees some conversation, but then some stuff remains encrypted. There doesn't seem to be a pattern in this.

![image](https://user-images.githubusercontent.com/640121/185796993-37f06c57-954f-4264-ad23-538ee1244b2d.png)

### Operating system

Windows 11

### Application version

Element version: 1.11.2, Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Homeserver

https://element.ems.host

### Will you send logs?

Yes

**Comment by ara4n** [comment]
the rageshake here should also include some nasty indexeddb failures which may have contributed here

**Comment by linuxmail** [comment]
Hello,

we have the same issue, that some of our users and me included have sometimes problems with encrypted messages. The only (fastes) way to get them decrypted is to use a 2nd device and open the same room .. after clicking a bit around .. the messages gets readable.

* me
  - Fedora 36
  - 1.11.4
* User
  - Windows 11
  - 1.11.5

It does not happen always .. but round about once in a week.

cu denny

**Comment by richvdh** [comment]
I think we've only got rageshakes from one side here, so can't do much with this.
