### ISSUE TITLE
File upload progress bar no longer works

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23121]
### Steps to reproduce

1. Upload an image to an e2ee room on a slow connection
2. Observe that there is no upload progress on the bar any more - it remains at 0% until the transfer completes.

#### What did you expect?

Progress bar that doesn't lie

#### What happened instead?

Blank progress bar

### Operating system

macOS

### Application version

Nightly

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by YamatoRyou** [comment]
This problem can also be reproduced by uploading files in non-encrypted rooms.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/1e4c336fed4d7f76a03b6275bcc09d4d1533d9b5

**Comment by t3chguy** [comment]
All progress bars other than the onboarding one were regressed
