### ISSUE TITLE
Device list showing random device names 

### ISSUE THREAD

**Issue by simaddis** [vector-im/element-web#23130]
### Steps to reproduce

1. login Alice to Element Web (using SSO - SAML Azure AD)
2. Login Alice to Element iOS (using SSO - SAML Azure AD)
3. Show "Where you're signed in" device list on Element Web.
4. Mobile device shows up with unrecognisable device name (e.g. "FUBMQYXZSW") under "Devices without encryption support".
5. Same happens when Alice logs into admin console. 

#### What did you expect?
Expected to see the mobile device listed as "iPhone" in the device list.
#### What happened instead?
Device listed was FUBMQYXZSW.

### Operating system

Windows 10 client

### Browser information

Chrome Version 104.0.5112.81 (Official Build) (64-bit)

### URL for webapp

Element Web version: 1.11.2 Olm version: 3.2.12

### Application version

Element Web version: 1.11.2 Olm version: 3.2.12

### Homeserver

Synapse (installer version 2022-08-02)

### Will you send logs?

No

**Comment by t3chguy** [comment]
iOS has a bug that it doesn't upload the device name when a password isn't involved.
https://github.com/matrix-org/matrix-ios-sdk/blob/27ab1ca41a97a0832be9169b8b9438f7e0fd210d/MatrixSDK/MXRestClient.m#L996-L1012
