### ISSUE TITLE
Start DM by inviting again an email create a new DM

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#23139]
#### Steps to reproduce
1. Start a new DM by selecting an e-mail and sending a message -> a new DM is created unencrypted and a third party invite is sent - OK
2. Other user does not react to the invite, yet - They did create their mx account, or they did not enable discovery of their account via their email address
3. Start again a new DM by selecting the same email -> Element-web suggests sending your first message - NOK this will create a new DM instead of keep using the existing one

#### What would you like to do?
The existing DM should be opened when I press Go on the Start DM dialog (after having selected the same email)

#### Why would you like to do it?
To prevent multiple DM for the same contact

#### How would you like to achieve it?
Check whether a DM is already created for the email in the `m.direct` event (Account Data)

**Comment by weeman1337** [comment]
Related to #23138
