### ISSUE TITLE
Start DM for e-mail invited person creates a new DM

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23138]
### Steps to reproduce

1. Invite someone by e-mail
2. Other person completes the invite process
3. A DM exists, both joined
4. Click on + next to „people“ and select the user or click „message“ in room member list

#### What did you expect?

The created DM room will be displayed

#### What happened instead?

A new DM is started

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 104.0

### Application version

Version von Element: 1.11.3 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by giomfo** [comment]
FYI this has been fixed in Element-Android by this [PR](https://github.com/vector-im/element-android/pull/3743)
