### ISSUE TITLE
Direct Message: Manage encrypted DM in case of invite by email

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#23133]
#### [Context](https://github.com/vector-im/element-meta/issues/372) sum up 
Currently this is possible to start a new DM by filling an email address.

The resulting DM is an unencrypted room (even if the encryption should be enabled by default according to the HS well-known configuration) because there is no way to encrypt message in this room until an actual matrix account has joined the DM:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/8969772/171010276-7f8a8be1-af2a-462d-aa27-46c14569c834.png">

The purpose is to let the end user start sending messages before the invited contact creates theirs account and joins, but there is some concerns:
- we run the risk to let people using an unencrypted DM without being aware of that
- matrix.org allows us to create unencrypted DM, but some HS may force the encryption in the created DM. The user experience would not be good then

#### What would you like to do?
After discussing with Design team, we converged to the following solution:

- [ ] When the HS promotes the encryption (via the well-known endpoint), the DM will be created by enabling the encryption. The chat composer will be disabled until a matrix account is created by using the invited email
- [ ] In order to be able to name correctly the resulting room, only one email address will be allowed at once. The created DM will be added to the m.direct dictionary by using the email as key. The Element clients will then able to add this DM in the right people section and name it with the full email address

Here are the suggested design:
<img width="1080" alt="Screenshot 2022-08-22 at 18 54 42" src="https://user-images.githubusercontent.com/8969772/185977090-9aebdcba-4c00-42bc-81fb-c05257373a67.png">

Figma: https://www.figma.com/file/OvsSONqAyabcUDYp8tnEs6/Start-a-DM?node-id=1373%3A49380

### Additional context

We plan to work on a PR for this in the following weeks

**Comment by t3chguy** [comment]
> The created DM will be added to the m.direct dictionary by using the email as key. 

Is there an MSC to allow this? The spec says the keys are MXIDs

https://spec.matrix.org/v1.3/client-server-api/#mdirect

**Comment by weeman1337** [comment]
At least on web, e-mail-addresses are listed in `m.direct`. We are probably not spec-compliant there.

**Comment by turt2live** [comment]
That is indeed a bug/spec violation. Previously reported as https://github.com/vector-im/element-web/issues/7484 but closed due to lack of traffic/known causes.

**Comment by t3chguy** [comment]
@weeman1337 was web the only client you ever used on the account? `m.direct` is obviously shared across all your devices ever

**Comment by weeman1337** [comment]
Checked on Android. Same behaviour there.

**Comment by giomfo** [comment]
We agree to write an MSC for supporting email addresses in m.direct event. This would at least clarify what is implemented in the current Element clients.

We should replace the email address with a mxid once known, like we did in Element-Android [here](https://github.com/vector-im/element-android/pull/3743/files#diff-a634a9bb2324cf1f4f0c13c99cde41d138be16a41864f209f6c4f7dd7bad47c5R57-R63)

**Comment by t3chguy** [comment]
Small reminder that `m.direct` is on its way out with canonical DMs
