### ISSUE TITLE
Jumping playback time in voice messages causes view to scroll

### ISSUE THREAD

**Issue by GithubUser96** [vector-im/element-web#23132]
### Steps to reproduce

1. Where are you starting? What can you see?

When a voice message is being played and time is skipped using the progress bar, the view scrolls/jumps up.

3. What do you click?

Voice message progress bar.

#### What did you expect?

For the voice message to skip to the desired moment.

#### What happened instead?

A misalignment of the view in the window occurred.

### Operating system

Windows

### Application version

1.10.10

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by dbkr** [comment]
I can't reproduce this bug with the repro steps given. A video might help?

**Comment by kittykat** [comment]
@GithubUser96 Are you still experiencing the issue? Can you help us by providing a video?

**Comment by robintown** [comment]
I can't reproduce this either. @GithubUser96 If you have any new info, we can reopen this.
