### ISSUE TITLE
Problem opening a video room session when jitsi requires login data.

### ISSUE THREAD

**Issue by silkker** [vector-im/element-web#23149]
### Steps to reproduce

1. Setup jitsi using LDAP authentication (https://github.com/jitsi/jitsi-meet/wiki/LDAP-Authentication)
2. Setup element to use this jitsi instance.
3. Create a video room
4. Try joining the jitsi session

### Outcome

You won't be able to join because it does not prompt you for the authentication data.
When another person joins via Element-IOS (not tested on android) it prompts for authentication data and the second person will be able to join.

### Operating system

Windows

### Browser information

Chrome: 104.0.5112.101

### Application version

v1.11.3

### Homeserver

Synapse

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is not something Video Rooms will support, Jitsi will be replaced by Element Call which will be authenticated.
