### ISSUE TITLE
UISI in a Room

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#23144]
### Steps to reproduce

1. Where are you starting? What can you see?
I'm in a room with a user called A and I can't see their messages due to UISI issues.
3. What do you click?

I tried clicking request encryption keys and this did not help.

#### What did you expect?

To be able to read A's messages.

#### What happened instead?

UISI Errors

### Operating system

Fedora Linux 36

### Browser information

Microsoft Edge Version 104.0.1293.54 (Official build) (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 6cc71e1f13ba-react-a973543bf8a8-js-1df329df7c97 Olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by richvdh** [comment]
Afraid I don't think we're going to get anything useful here after all this time :(.
