### ISSUE TITLE
Error uploading voice message: ConnectionError: request failed: JSON.parse: unexpected character at line 2 column 1 of the JSON data

### ISSUE THREAD

**Issue by ralfi** [vector-im/element-web#23143]
### Steps to reproduce

Try to send a voice messages on a room with admin privileges on my self hosted synapse 1.65 matrix server with element web interface on latest element v1.11.3

#### What did you expect?
send voise-messages to the room

#### What happened instead?
Error in the browser console
Error uploading voice message: ConnectionError: request failed: JSON.parse: unexpected character at line 2 column 1 of the JSON data

### Operating system

Windows

### Browser information

FF 101.0.1 32 Bit

### URL for webapp

my own homeserver

### Application version

element 1.11.3

### Homeserver

matrix synapse 1.65

### Will you send logs?

No

**Comment by t3chguy** [comment]
Sounds like your homeserver returned a non-JSON payload error, maybe a Cloudflare error page or similar.

**Comment by ralfi** [comment]
Do not use this but i have my own adguard based privacy dns server. Mmmmh, thanks, i will be look deeper ...

**Comment by ralfi** [comment]
No for browser setting, now look at the synapse / element logs ...

**Comment by ralfi** [comment]
Not really there, also no tcp rst packages with wireshark

**Comment by ralfi** [comment]
Not element related, seems to be in conjunction with detailled worker config as in matrix-docker-ansible-deploy recommended. Without workers everything with voise message upload is fine.
