### ISSUE TITLE
"Lazy Loading" > "should handle lazy loading properly even when offline" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23154]
https://dashboard.cypress.io/projects/ppvnzg/runs/3630/test-results/6bc2aec2-75d9-438a-bebe-e358de9eba78

![Screenshot 2022-08-25 at 19-50-45 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/186788350-10e30742-8dc9-4bec-a6a5-929e7412196c.png)

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
