### ISSUE TITLE
Enable copying link to a particular chat entry

### ISSUE THREAD

**Issue by tnabtaf** [vector-im/element-web#23156]
#### What would you like to do?

Be able to include links to specific chat entries in elsewhere on the web.  For example, in my emails, or on a web page.  Clicking on the link would take me to that chat entry.

#### Why would you like to do it?

I often want to refer to a particular chat post, from outside of Element.

#### How would you like to achieve it?

1. Click on the ellipsis to the right of particular chat post.
2. In the pull down, select "Copy link" or "Link to".
3. Paste the link wherever I need it.

![Screen Shot 2022-08-25 at 16 48 39](https://user-images.githubusercontent.com/1622414/186788372-973c0ad5-f3f7-4b30-a725-cfc0b9ea05ec.png)

### Have you considered any alternatives?

There are two workarounds, but both are painful and most people won't bother:

Option 1: Search

1. Search for the specific post you want to link to.  Use the web interface for this.
2. Right click on the post in the search results and copy the link.

Option 2: Compose from source

1. Click on the ellipsis of the post you want to get a link to.
2. Select "View Source"
3. Cut and paste the event ID and Room ID into this template
    https://app.element.io/#/room/<ROOM_ID>/<EVENT_ID>

### Additional context

Linkability is a key feature for chat.  Sometimes chats contain exchanges or announcements that are worth pointing to.

Linking to individual posts is already supported.  All we need is a way to easily get the link.

**Comment by t3chguy** [comment]
Or just use the `Share` button in your screenshot?

<img width="774" alt="image" src="https://user-images.githubusercontent.com/2403652/186846407-0f7073e9-8224-4775-9e71-e9298e82ccd8.png">

From there you can copy, if you want a shortcut you can right click copy link on the timestamp on the message

<img width="216" alt="image" src="https://user-images.githubusercontent.com/2403652/186846459-d0bb1940-bbdd-4574-a1bc-2e8f499271a1.png">

**Comment by SimonBrandner** [comment]
FWIW, you can do this by right-clicking the timestamp

**Comment by tnabtaf** [comment]
@t3chguy and @SimonBrandner GAAHHH!  I apologize.  I swear I looked at at that.  But apparently I did not. 

Thank you for already having this feature, and for being nice to people who clearly weren't paying attention.
