### ISSUE TITLE
Problem with message display whitespace/international domain, possibly script injection?

### ISSUE THREAD

**Issue by phpwutz** [vector-im/element-web#23159]
### Steps to reproduce

Write someone a message containing an IDN (international domain name)
for example:

`test köll.net. ` (note the trailing whitespace!)

Shouldnt need anything else

#### What did you expect?

I expect the message to just show up like that in my client and my conversation partners client.

It does seem to show up correctly when i edit and save again without the trailing whitespace, then hit "edit" and "cancel" again. that's not a feasable workaround though xD

#### What happened instead?

This shows up in the chat history:

`test [<span><div tabindex="-1" class="mx_TextWithTooltip_target">köll.net</div></span>](http://xn--kll-sna.net/).`

![image](https://user-images.githubusercontent.com/133333/187033671-aa5ade80-3cb0-43bd-beaa-aa4eaeb46d4a.png)

Note that the HTML shows up in the chat history, i didn't do any "show source" or the likes

### Operating system

Arch

### Application version

Element version: 1.11.2 Olm version: 3.2.12

### How did you install the app?

arch user repository

### Homeserver

docker.io/matrixdotorg/synapse:v1.63.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please update to 1.11.3 this was a bug with the url tool tips getting escaped

**Comment by phpwutz** [comment]
i would love to upgrade, but the arch package still points to 1.11

https://archlinux.org/packages/community/x86_64/element-desktop/

**Comment by t3chguy** [comment]
The arch package is community-maintained, you'd need to seek support from its maintainer(s).
