### ISSUE TITLE
`M_INVALID_USERNAME` on `/register/available` comes back as "We are unable to check if this username is taken"

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23161]
### Steps to reproduce

1. Try to register `_alice` on Synapse
2. Get `{"errcode":"M_INVALID_USERNAME","error":"User ID may not begin with _"}`
3. See UI reported as: 
![image](https://user-images.githubusercontent.com/1190097/187051766-ba17203c-0e9c-4eed-ad98-462542874d14.png)

#### What did you expect?

The error message to be clearer that the ID is invalid

#### What happened instead?

see above

### Will you send logs?

No

**Comment by turt2live** [comment]
(why does this need design?)

**Comment by t3chguy** [comment]
This seems to be an issue with Synapse not matching the Spec's grammar https://spec.matrix.org/v1.3/appendices/#user-identifiers

**Comment by turt2live** [comment]
> This seems to be an issue with Synapse not matching the Spec's grammar https://spec.matrix.org/v1.3/appendices/#user-identifiers
> 

The spec also says that basically anything is acceptable as a user ID. There's also a mention elsewhere that appservices should start with an underscore, and I believe that's what synapse is protecting against.

Also, why does this need design?
