### ISSUE TITLE
Unable to decrypt

### ISSUE THREAD

**Issue by tadzik** [vector-im/element-web#23166]
### Steps to reproduce

1. I'm getting "Unable to decrypt" errors in a room where I used to have a normal conversation with the sender

#### What did you expect?

I expected messages to be decrypted

### Operating system

Debian Linux

### Browser information

Firefox 103.0

### URL for webapp

chat.element.io

### Application version

Element version: 1.11.3 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by vfxninjaeditor** [comment]
As of today I have also noticed this. Not sure if it's related to yours but file uploads older than about a month (images/video) won't decrypt for me or anyone else I know using the platform.

**Comment by tadzik** [comment]
Got it in a DM with the same sender too, so I sent a rageshake for that, also for this issue.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2996
