### ISSUE TITLE
Searching not working

### ISSUE THREAD

**Issue by dm-msk** [vector-im/element-web#23164]
### Steps to reproduce

Searching not working.
Error opening the database: IndexError(IOError(IOError { path: None, err: Custom { kind: Other, error: "Invalid MAC" } }))

### Operating system

Windows 10 x64

### Application version

Element version: 1.11.3 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/19001
