### ISSUE TITLE
Unable to set up secret storage

### ISSUE THREAD

**Issue by RoninAngle1** [vector-im/element-web#23167]
### Steps to reproduce

First I should say that I ran matrix synapse on my local server , there is no valid domain, SSL/TLS
Every thing is fine but when a user wants to register or sign in with web base app (V1.11.2) , user wants to generate or import a key file , there is this error (Unable to set up secret storage)

path: all settings --> security & privacy --> Encryption --> Icon "Setup" --> generate new key --> Download / Copy --> asks user password to verify the user --> Error "Unable to set up secret storage" . Tested in Chrome, Firefox, .etc

This Problem is only on web base app, the desktop apps are OK.

#### What did you expect?
I expected to say every thing fine or any thing like this , exept Unable to set up secret storage
#### What happened instead?
It just says Unable to set up secret storage with two icons, Try again & cancel

my home server conf
```
erver_name: "matrix.geek.local"
pid_file: "/var/run/matrix-synapse.pid"
enable_registration: true
session_lifetime: 24h
registration_shared_secret: XXXX
#enable_registration_without_verification: true
public_baseurl: http://matrix.geek.local/
web_client_location: http://element.geek.local/
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']
    resources:
      - names: [client, federation]
        compress: true

database:
  name: sqlite3
  args:
    database: /var/lib/matrix-synapse/homeserver.db

macaroon_secret_key: "XXXX"
form_secret: "XXXX"
log_config: "/etc/matrix-synapse/log.yaml"
report_stats: true
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
trusted_key_servers:
        - server_name: "http://localhost:8090"

registrations_require_3pid:
  - email
enable_3pid_lookup: true
registration_requires_token: false
allowed_local_3pids:
  - medium: email
    pattern: '^[^@]+@example\.local$'

email:
  smtp_host: mail.example.local
  smtp_port: 25
  force_tls: false
  require_transport_security: false
  enable_tls: false
  notif_from: "Your Friendly %(app)s homeserver <element-noreply@pep.co.ir>"
  app_name: pep_matrix
  enable_notifs: true
  notif_for_new_users: true
  client_base_url: "http://element.geek.local"
  validation_token_lifetime: 15m
  invite_client_location: http://element.geek.local

  subjects:
    ...

password_config:
   enabled: true
   localdb_enabled: false
   policy:
      enabled: true
      ...

modules:
 - module: "ldap_auth_provider.LdapAuthProviderModule"
   config:
     enabled: true
     ...
password_providers:
  - module: "rest_auth_provider.RestAuthProvider"
    config:
      endpoint: "http://localhost:8090"
```
my ma1sd conf
```
matrix:
  domain: 'matrix.geek.local'
  v1: false 
  v2: true   
key:
  path: '/var/lib/ma1sd/keys'

storage:
  provider:
    sqlite:
      database: '/etc/ma1sd/ma1sd.db'

synapseSql:
  enabled: true
  connection: '/var/lib/matrix-synapse/homeserver.db'

threepid:
  medium:
    email:
      domain:
          whitelist:
            - '*@example.local'
      identity:
        from: 'test@example.local'
      connectors:
        smtp:
          host: 'mail.example.local'
          tls: 0
          port: 25

ldap:
  enabled: true
  lookup: true # hash lookup
  activeDirectory: true
  mode: "search"
  defaultDomain: 'example.local'
  connection:
    host: 'XXXX'
    port: 389
    bindDn: 'test@example.local'
    bindPassword: 'XXXX'
    baseDNs:
      - 'OU=test,DC=example,DC=local'
  attribute:
    mail: "email"
    name: "DisplayName"

dns:
  overwrite:
    homeserver:
      client:
        - name: 'matrix.geek.local'
          value: 'http://localhost:8008'

config:
  policy:
    registration:
      username:
        enforceLowercase: false

logging:
  root: info    
  app: info       
  requests: false
```

![Screenshot from 2022-08-30 14-52-25](https://user-images.githubusercontent.com/106800360/187413709-77a8c5a9-1c25-486c-b53d-184e7c4f03e3.png)
![Screenshot from 2022-08-30 14-52-42](https://user-images.githubusercontent.com/106800360/187413743-cd482d9c-914b-4efb-b820-fbb9f8fd6df0.png)
![Screenshot from 2022-08-30 14-52-58](https://user-images.githubusercontent.com/106800360/187413779-9820ca4c-7e99-4861-be62-57807c068436.png)
![Screenshot from 2022-08-30 14-53-13](https://user-images.githubusercontent.com/106800360/187413810-a3b1a6d5-8aaa-4efd-a03e-934f033147c4.png)
![Screenshot from 2022-08-30 14-53-27](https://user-images.githubusercontent.com/106800360/187413840-960c9dfd-0521-492f-b6b5-88d2d2803689.png)
![Screenshot from 2022-08-30 14-53-36](https://user-images.githubusercontent.com/106800360/187413874-754d91ed-83d2-4a60-85a3-67d32fd9ed25.png)
![image](https://user-images.githubusercontent.com/106800360/187415854-96926792-46fd-4097-8e7e-153645b0c2d8.png)
![image (1)](https://user-images.githubusercontent.com/106800360/187415879-34223c57-b1c7-4f86-bd05-c08fc5280ed5.png)
log file:
[rageshake(2).zip](https://github.com/vector-im/element-web/files/9452095/rageshake.2.zip)

### Operating system

Ubuntu 20.04, Ubuntu 18.04, Windows 10

### Browser information

Version 103.0.5060.134 (Official Build) (64-bit), Firefox 104.0 (64-bit)

### URL for webapp

(http://element.geek.local) Local --> Unable to be published on internet

### Application version

V1.11.2

### Homeserver

(http://matrix.geek.local) Local --> Unable to be published on internet

### Will you send logs?

No

**Comment by t3chguy** [comment]
> (http://element.geek.local/) Local --> Unable to be published on internet

The `http://` here is the issue: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure - without this your browser disabled cryptography features. You will either need to use `https://` or `localhost` or modify your browser to include `element.geek.local` in a whitelist if it supports this.

**Comment by RoninAngle1** [comment]
Thanks a lot , I understand it now. many thanks to you
