### ISSUE TITLE
No connectivity

### ISSUE THREAD

**Issue by robgrune** [vector-im/element-web#23179]
### Steps to reproduce

Linux gnome 42 system, X11. 
Prior, installed element flatpack.
Problem occurred today, 01sept22, after receiving notice to update.
Updated.
Could no longer invoke element.
Uninstalled element flatpack.
Installed latest release of element from website.
Element can now be invoked.
PROBLEM: Element can no longer connect to server.
Message; connectivity to server has been lost.
QUESTION: how to re-establish connection to server?
QUESTION: where to find the logs? 

#### What did you expect?
after re-install, expected the app to work properly

#### What happened instead?
Cannot connect to server.

### Operating system

Pop!_OS

### Application version

1.11.4

### How did you install the app?

https://element.io/get-started#downloads

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The flatpak is community maintained, I suggest seeking support from https://github.com/flathub/im.riot.Riot

**Comment by robgrune** [comment]
pls read again. flatpack UNINSTALLED.  thank you.

**Comment by robintown** [comment]
You can view the logs by opening Developer Tools with Ctrl+Shift+I, or by going to Feedback > Report a bug > Debug logs > Download logs

**Comment by robgrune** [comment]
many thanks for reply.

rageshake.tar is uploaded.

ctrl+shift+I brings up a console.
seemingly the relevant log data shows in this console as follows...

rageshake.ts:73 Getting push rules failed M_MISSING_TOKEN: Invalid Authorization header.
    at T (vector://vector/webapp/bundles/5502a285e4431c24dbcf/vendors~init.js:2:861860)
    at vector://vector/webapp/bundles/5502a285e4431c24dbcf/vendors~init.js:2:861263
    at Object.callback (vector://vector/webapp/bundles/5502a285e4431c24dbcf/vendors~init.js:2:860826)
    at vector://vector/webapp/bundles/5502a285e4431c24dbcf/vendors~init.js:2:13243
    at i.onreadystatechange (vector://vector/webapp/bundles/5502a285e4431c24dbcf/vendors~init.js:2:13267)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:50
i @ sync.ts:576
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
await in i (async)
i @ sync.ts:582
XMLHttpRequest.send (async)
(anonymous) @ index.js:218
t @ index.js:179
(anonymous) @ browser-index.js:34
doRequest @ http-api.ts:854
requestOtherUrl @ http-api.ts:729
request @ http-api.ts:681
pokeKeepAlive @ sync.ts:1452
rageshake.ts:73 Waiting for saved sync before retrying push rules...
rageshake.ts:73 MatrixClient sync state => ERROR

**Comment by robintown** [comment]
Could you try logging out and logging back in?

**Comment by robgrune** [comment]
well, I tried 1st time to login/out to no avail.
2nd time,,,, I re-established all keys, then login/out/in. this required a
real-time connect with the phone.
bingo. can now login via desktop.

thank you for your suggestion.

**Comment by robintown** [comment]
Okay, I think we can safely close this then. If you experience any further issues feel free to ask in [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org).
