### ISSUE TITLE
Can see old room history even though setting is "Members only (since they joined)"

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23180]
### Steps to reproduce

1. Invited a user to #public-room-testing:matrix.org (public, unencrypted room with "Members only (since they joined)" settings)
2. User joined
3. User can see some very old messages, but not newer ones

#### What did you expect?
User can see new messages only since they joined

#### What happened instead?
User can see really old messages, but not newer ones

What I can see on the left, what new user can see on the right
![Screenshot from 2022-09-01 10-01-09](https://user-images.githubusercontent.com/51663/187876360-84257c55-8bb0-4e5e-85b3-7ef4f9ff65d8.png)

### URL for webapp

I'm on develop.element.io; new user is on staging.element.io

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Can see old room history even though setting is "Members only (since they joined)"

The setting is not retroactive

But also the history access control is done by the server, this would need an issue with whatever server implementation you are using @kittykat

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/187889173-b8de8ace-92d7-4f39-a3d3-7155bb26d8a7.png)

You change the history visibility after sending messages with a different one, so history at different points in time will differ, hence you being able to see the older history but not more recent history. As per the warning when making this change:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/2403652/187889294-0945c439-1e00-42d8-b681-a159f337d374.png">


Closing as it is behaving as per the spec, if you think this is behaving with a fault you'd need to open a server bug as the server handles this ACL. If you think this behaviour is confusing then a spec bug
