### ISSUE TITLE
Scrollbar collides with checkboxes on "Add Existing Rooms/Spaces" dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23189]
### Steps to reproduce

1. Manage a space
2. Click "Add existing room"
3. Have lots of rooms or otherwise resize the viewport to cause a scrollbar
4. Attempt to click on the right side of the checkbox

#### What did you expect?

To be able to click the checkboxes

#### What happened instead?

The scrollbar is in the way:
![image](https://user-images.githubusercontent.com/1190097/188019945-517ba506-94c7-4824-9481-3151d3b4155a.png)

(Left edge was clicked to get around it)

### Operating system

Windows 10

### Will you send logs?

No

**Comment by rksingh2001** [comment]
@robintown @turt2live Can I take up this issue?

**Comment by rksingh2001** [comment]
@robintown It seems like the CSS is being handled in matrix-react-sdk, so should i make a PR there or should I try to do this in element-web only?

**Comment by robintown** [comment]
Yes, the majority of Element Web's code is actually in matrix-react-sdk, so you should open your PR there.

**Comment by rksingh2001** [comment]
@robintown I have made the PR: https://github.com/matrix-org/matrix-react-sdk/pull/9312

**Comment by snehilchhabria** [comment]
I see this issue is still relevant, I can work on this right away.
