### ISSUE TITLE
QR codes for app download doesn't look nice in the dark theme

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-web#23199]
### Steps to reproduce

1. Start out using Element Web
2. Use the dark theme
3. Click on “Download app”, and see the QR codes

#### What did you expect?
The QR codes should be inverted, or have a padding around it to make it look nice, though I can scan it with my phone

#### What happened instead?
![Screenshot_20220903_215415](https://user-images.githubusercontent.com/47475676/188276113-abaa2361-159a-44c3-9ebb-2aab433871d8.png)

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
> though technically it is still scannable

QR Codes require a quiet zone around them: https://www.2dtg.com/node/121
