### ISSUE TITLE
Cannot sign-in neither sing-up

### ISSUE THREAD

**Issue by Thestroyer** [vector-im/element-web#23205]
### Steps to reproduce

1. Where are you starting? What can you see?
I just "Launch Element Web" from https://element.io/get-started and click "Sign-In" / "Create Account" in incognito tab and then i get the "Something went wrong" tab 
![image](https://user-images.githubusercontent.com/95849588/188384380-ee9b7e8a-e243-4fa4-8316-d0191c9156ee.png)
2. What do you click?
As I said.
3. More steps…
No further steps, I just can't sign-in neither create an account. It happens in non-incognito tab also.

#### What did you expect?
I expected to create an account.

### Operating system

Arch Linux

### Browser information

Version 104.0.5112.79 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9235

**Comment by Thestroyer** [comment]
> Fixed by [matrix-org/matrix-react-sdk#9235](https://github.com/matrix-org/matrix-react-sdk/pull/9235)

Well, not for me.

**Comment by t3chguy** [comment]
@Thestroyer are you running that change? It hasn't made it into a release yet.

**Comment by Thestroyer** [comment]
Ah okay sorry I didn't think.
