### ISSUE TITLE
As of the last few weeks, every time ED is launched, a somewhat stable subset of old rooms are incorrectly shown as unread.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23209]
### Steps to reproduce

1. Restart Element Desktop
2. Observe ancient rooms start to pop up in one's room lists marked as unread (grey dot)
3. Open room, and see there have been no messages since the last time you checked.

The timings roughly coincide with the arrival of private read receipts. (I have them turned off, though, and the rooms in question don't have messages sent from me while i had private RRs enabled).

The rooms in question have no invisible events keeping them alive, nor do they have any threaded messages.

#### What did you expect?

Unread state shouldn't lie

#### What happened instead?

It lied

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by erikjohnston** [comment]
In the matrix.org DB:

* There is a stable private read receipt pointing at the latest event
* There is an unstable private read receipt pointing at an older event
* The notification counts are 0.

**Comment by ara4n** [comment]
This sounds like EW needs to ignore the unstable receipt events?

**Comment by SimonBrandner** [comment]
> This sounds like EW needs to ignore the unstable receipt events?

This should be done now, let's see what happens

**Comment by t3chguy** [comment]
Closing as presumed fixed until proven otherwise

**Comment by mr-karan** [comment]
I am hitting into this as well.
