### ISSUE TITLE
E2E key imports

### ISSUE THREAD

**Issue by gsnedders** [vector-im/element-web#23213]
### Steps to reproduce

1. Login, again.
2. Get asked to verify the session.
3. As a security key, upload file beginning with `-----BEGIN MEGOLM SESSION DATA-----`

#### What did you expect?
I expected to import the E2E key

#### What happened instead?
"Wrong file type"

### Operating system

macOS

### Browser information

Safari 16

### URL for webapp

chat.mozilla.org

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### Homeserver

chat.mozilla.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
That isn't your security key, that's your Megolm keys. Your security/recovery key guards your secure backup, Megolm keys are encryption keys which are used to encrypt individual/groups of messages.

Megolm keys are exported & imported here:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/2403652/188575126-a5aeb014-1530-4953-9cf8-f42845c8c52a.png">

The security/recovery key isn't ever stored by the app, you are asked to copy or download it when you set up your secure backup.

**Comment by gsnedders** [comment]
I realise you've closed this now, but could we detect other keys (like Megolm keys) and give a more useful error message than "wrong file type"? Like, "hey, these are E2E room keys, not your security key"?

**Comment by t3chguy** [comment]
I suggest creating that suggestion on https://github.com/vector-im/element-meta - where cross-platform suggestions live
