### ISSUE TITLE
Rooms marked unread without new text

### ISSUE THREAD

**Issue by fuzzy76** [vector-im/element-web#2321]
From time to time (on average, once a day among 20 rooms), Vector marks some of my rooms unread without any new text in the channel. It seems to be mostly rooms that are bridged to IRC channels, but I'm not 100% sure.

If you need any steps by me to help narrow it down, let me know.

**Comment by ara4n** [comment]
I've seen this too, and haven't worked out the reproduction steps either.

**Comment by ara4n** [comment]
possibly related to #3257 and #2427

**Comment by fuzzy76** [comment]
This is still happening on a daily basis. :-/

**Comment by aaronraimist** [comment]
One of the things that causes it to happen is people adding aliases to a room

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/12063
