### ISSUE TITLE
"Add existing room to Space" dialog not showing a room that I'm in and is not in the space already

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#23217]
### Steps to reproduce

1. The "Dendrite" (non-dev) room was upgraded. As such, the old room (`!yomrOFwgFXzmeMAbzX:matrix.org`) was stuck under the "Servers" space (in Element's internal Space). The new room (`!RcWPWcZrMeBxOGaalX:matrix.org`) was not part of the Space.
2. I removed the old room from the Space using Element's Space Room Management UI.
3. I then clicked Add -> Add existing room and searched for "Dendrite", but neither the new or old room appeared in the list, even though my user account is in both, and I can see the new room if I search for it in the room sidebar.

I've failed to reproduce this with a test space and rooms. As such, I have included debug logs.

#### What did you expect?

The new (and not old) Dendrite room to appear in the list of rooms I could add to the "Servers" space.

#### What happened instead?

My query returned zero search results.

![image](https://user-images.githubusercontent.com/1342360/188605109-159a7e1c-7eed-4929-b66e-f1adcb0e3c68.png)

### Operating system

Arch Linux

### Application version

Element version: 2022090501, Olm version: 3.2.12

### How did you install the app?

The AUR

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Turns out the removal failed due to https://github.com/vector-im/element-web/issues/21002 - thus the room is being hidden as it is already in the space in one of its variants
