### ISSUE TITLE
Mentions are not discoverable

### ISSUE THREAD

**Issue by 3nprob** [vector-im/element-web#23212]
### Steps to reproduce

1. Be logged in to large unencrypted room
2. Receive mention in said room while AFK.
3. Open Element Messenger Desktop. Room is marked :exclamation: as expected. 
4. Click room. View is scrolled to bottom, showing last unread message.
5. Click up-arrow in top-right corner of scrollback. Scrolls past the mention, to first unread message

#### What did you expect?

There exists an obvious way in the UI to navigate to recent and unread mentions.

#### What happened instead?

Have to manually scroll for ~10 minutes to locate message with a mention that yielded the last notification (which are not always discoverable from searching the user handle, which means search is not a solution)

#21876 (feature request to add a keyboard shortcut for navigating unread mentions and DMs) is related but different - this issue is just about being able to *somehow* view the events that triggered pending unread notifications and UI urgency indicators.

### Will you send logs?

No

**Comment by t3chguy** [comment]
> There exists an obvious way in the UI to navigate to recent and unread mentions.

Have you tried the bell icon top right?

**Comment by 3nprob** [comment]
I'm a doofus.
