### ISSUE TITLE
Sort shorter/exact emoji matches before longer incomplete matches

### ISSUE THREAD

**Issue by grimhilt** [vector-im/element-web#23210]
#### What would you like to do?
1. Get only the frequently used emojis that have the same beginning as the input string
2. Create a sort inside the list of selected frequently used emojis based on shortcode length

#### Why would you like to do it?
1. Considering `:heart_eyes:` in my frequently used emojis list, typing `:eyes` will get me `:heart_eyes:` and then `:eyes:`
2. Considering having `:heartpulse:` and `:heart:` (in this order), typing `:heart` will get me `:heartpulse:` and then `:heart:`

Both of these outcomes are illogical to me.

**Comment by MadLittleMods** [comment]
I don't think this pertains just to the frequently used section of the emoji picker. `:heart_eyes:` sorts before `:eyes:` in the normal `Smileys & People` section as well.

![](https://user-images.githubusercontent.com/558581/188737325-34cddbd5-2605-4820-b7b1-a35f1116d067.png)

---

Having exact matches sort above fuzzy matches makes sense though 👍

Same problem as https://github.com/vector-im/element-web/issues/15609 for the MXID autocomplete

**Comment by grimhilt** [comment]
I took some time to work on this, and i noticed there isn't any sort done in the EmojiPicker.
Is this really expected ?
