### ISSUE TITLE
NotifPanel should show displaynames

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23214]
### Your use case

<img width="418" alt="Screenshot 2022-09-06 at 10 16 20" src="https://user-images.githubusercontent.com/1294269/188597080-7546c52f-8861-4fae-b234-703add2c3516.png">

should show Kegan rather than `@kegan:matrix.org`

**Comment by ara4n** [comment]
see also https://github.com/vector-im/element-web/issues/2776

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22985
