### ISSUE TITLE
Option to toggle the spaces feature

### ISSUE THREAD

**Issue by vishu1034** [vector-im/element-web#23230]
#### What would you like to do?
I would like to enable/disable the spaces feature in the element web client. We don't need this feature and would like to remove it.

#### Why would you like to do it?
We don't need the spaces feature and would like to remove it.

#### How would you like to achieve it?
It would be great if there could be a toggle to just disable/enable spaces.

**Comment by weeman1337** [comment]
Thanks @vishu1034 for opening this issue.

It seems like this is a duplicate of #18898 and probably #22765. You can vote on the other issue :+1: to follow it.

**Comment by weeman1337** [comment]
Duplicate of #18898
