### ISSUE TITLE
The text on the 'Delete all' and 'Retry all' buttons is selectable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23232]
### Steps to reproduce

<img width="261" alt="Screenshot 2022-09-07 at 12 01 20" src="https://user-images.githubusercontent.com/1294269/188862767-df57b0d0-2589-449a-9e7a-13008aa004ba.png">

if you try to click on this and miss slightly, you end up selecting the text - needs less pointer events.

#### What did you expect?

buttons are buttons, not text.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment]
(this might have been exacerbated by the button also not working at all due to a bug on the SS branch)

**Comment by AnshumanPadiya** [comment]
@ara4n Hey, I would like to work on this issue, could you please tell me exactly how to reproduce the above scenario, I am asking this as I am just starting to use element.

**Comment by KartikSingh023** [comment]
@ara4n Hey, I would like to work on this issue, could you please tell me exactly how to reproduce the above scenario, I am asking this as I am just starting to use element.

**Comment by Tashneet-30** [comment]
Hey, Just started with Element .
I would really like to contribute to this issue. Could you please assign me the same  and  also help me understand the code base and how can I reproduce this matter.?

**Comment by nawarajshah** [comment]
can you tell me where I can get this button? because the step to reproduce is not clear to me.

**Comment by itsmeajay1699** [comment]
@ara4n  can u please tell where are the buttons present its hard to find
