### ISSUE TITLE
Invites don't decorate spaces with a dot/badge

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#23248]
### Steps to reproduce

Pre-condition: My `People` "space" did not have any decoration (neither an unread dot nor a badge count) before I started because I read all my conversations.

1. I receive an invite to a DM.
2. My `People` "space" in the space list still doesn't have any decorations.

#### What did you expect?

The invite should decorate the relates spaces in the space list (in this case the `People` "space") since it's a new unhandled/unobserved event.

#### What happened instead?

The `People` "space" remained without any decoration.

### Operating system

Arch Linux

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### How did you install the app?

Arch Linux repository

### Homeserver

termina.org.uk

### Will you send logs?

No

**Comment by t3chguy** [comment]
It was indeed the intent at the time of implementing the feature

**Comment by daniellekirkwood** [comment]
Cool.

 @gaelledel , this might be worth thinking about :)
