### ISSUE TITLE
As an admin I cannot change power settings of another user

### ISSUE THREAD

**Issue by schaefi** [vector-im/element-web#23245]
### Steps to reproduce

I'm the admin of the kiwi room here: https://app.element.io/#/room/#kiwi:matrix.org and wanted to give other users moderation power. I did it as follows:

```
/op  @user 50
```

and received a very strange message from a bot

```
Server Error
"@_discord_bot:t2bot.io": '0' is not of type 'integer'
```

next I deleted all users t2bot.io from the room as they are "dead" users anyway because that t2bot is non functional anyway. Once I did that I repeated the /op command and still receive the same strange error from the server.

Next I double checked if there is any bot:t2bot registration in my room and got

```
Kicking @_discord_bot:t2bot.io, response: {"errcode":"M_FORBIDDEN","error":"The target user is not in the room"}
```
which was expected and looks correct to me.

I'm running out of ideas and kindly ask for help

Thanks much

#### What did you expect?

```/op @some_user 50``` works

#### What happened instead?

see the initial report and message

### Operating system

Linux

### Browser information

google-chrome-stable-105.0.5195.102-1.x86_64

### URL for webapp

https://app.element.io/#/room/#kiwi:matrix.org

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The room is corrupted and has non-integer power levels. They are against the spec and Synapse began rejecting them. They need to be fixed manually using the API or a room upgrade.
