### ISSUE TITLE
Pre-DM screen does not persist message on room change

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23240]
#### What would you like to do?

For the Pre-DM screen to persist my message

#### Why would you like to do it?

I've many time started writing a message to in a new DM, realised that i needed to switch rooms to copy a link, tried to go back, and lost my original message

#### How would you like to achieve it?

Parity with the normal room behaviour. Locally persist it in the appropriate storage layer

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23196
