### ISSUE TITLE
"Timeline" > "message displaying" > "should click top left of view source event toggle" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23255]
https://dashboard.cypress.io/projects/ppvnzg/runs/3896/test-results/7038f46c-4bbb-447b-a8b9-d78746478d34

![Screenshot 2022-09-11 at 19-43-19 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/189553952-83ba3844-8082-4c2a-8612-717b31fbf6ed.png)

**Comment by weeman1337** [comment]
Looking at the screenshots it looks like the „show hidden events“ setting has not been applied.

I did run the test a couple of times locally. It always passed.
→ fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9287
