### ISSUE TITLE
Cypress login routine is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23256]
https://dashboard.cypress.io/projects/ppvnzg/runs/3897/test-results/79de8a76-8972-489a-9cfc-68258f8e0386

![Screenshot 2022-09-11 at 20-01-36 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/189554687-c8a80cba-61a4-44d2-9cf2-e2e30805556e.png)

**Comment by t3chguy** [comment]
This isn't specific to this test, can happen to any of them, Element just white-screens.

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
