### ISSUE TITLE
Username registered while already taken

### ISSUE THREAD

**Issue by doshmeister** [vector-im/element-web#23251]
### Steps to reproduce

Having a problem with username changing.

Chose the username "jayming" and registered account, but after email confirmation it said username is taken. Since I have used my email to register, i cannot make a new account without using a throw-away email, which I don't want to do.

### Outcome

I expected that I would be able to simply delete the account, however since I cannot login due to duplicate username, I cannot.

### Operating system

Windows 11

### How did you install the app?

element.io/get-started

### Homeserver

matrix.org (where it would have been)

### Will you send logs?

No

**Comment by t3chguy** [comment]
I suggest contacting support@matrix.org
Element Web isn't able to delete accounts or anything of the sort
