### ISSUE TITLE
Unable to Verify Users (happened after I tried Thunderbird Chat Integration)

### ISSUE THREAD

**Issue by russmcg** [vector-im/element-web#23258]
### Steps to reproduce

1. To preface I have all my keys backed up. All my accounts verified. etc. 
2. element was working flawlessly until this weekend when I tried to sign in Thunderbird chat using the same credentials. 
3. Was able to login to thunderbird chat with my matrix credentials, but it wasn't grabbing my messages properly. I clicked verify for a few users, and had no success. Figured it was a problem with the integration so I removed it from my account by logging out on a trusted Admin device. 
4. Because it wasn't working I logged out and revoked the thunderbird chat session. 
5. Now none of my messages are decrypting, and on the other side (users I'm messaging) my messages show up as not able to decrypt. 
6. When I try to verify the user and go through the verification steps it doesn't allow us to complete the steps. So something isn't talking back and forth now. 
Not sure what is going on but it is really really annoying, and I feel like it shouldn't be happening all because I tried to sign into an integration. 
Please help. 

### Outcome

Verification isn't working so I am unable to talk with users who I was previously talking to prior to trying to login and verify the Thunderbird Chat integration. 

### Operating system

Android, Linux, Etc. happens on all devices

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Logs do not appear to be submitted for this issue - if you're still seeing this, please resubmit them using this issue URL in the report dialog.

**Comment by russmcg** [comment]
How to I send logs?

**Comment by turt2live** [comment]
Apparently I missed a reply to this, sorry.

Settings -> Help -> Submit Debug Logs -> Use this issue URL.

**Comment by t3chguy** [comment]
Closing due to lack of info (logs) having been sent

**Comment by renyuneyun** [comment]
I'm having a similar issue -- also unable to verify my session. In my case, after entering the session-verification page on my Element client, nothing appears to happen on *Thunderbird* end.

After starting thunderbird from terminal, I get the following after clicking the "verify" button ('this is me") on Element:

```
prpl-matrix.matrix: error while handling verification event
"ascii" is not a function
```

So, this looks like a thunderbird issue, at least for my case. Unfortunately I don't find a way to report this to them, as thunderbird reporting guidance is really blocking newcomers...
