### ISSUE TITLE
'Something went wrong' on joining a room.

### ISSUE THREAD

**Issue by UnchartedSystems** [vector-im/element-web#23263]
### Steps to reproduce

1. I am looking at the rooms inside of the Helix community (general, random) 
3. I click the green 'Join' button to the right of the general room
5. I immediately get a generic 'Something Went Wrong' message.

### Outcome

I expected to join the room, instead I got a generic error message

### Operating system

Pop Os (Linux)

### Application version

1.11.4-1

### How did you install the app?

Through my native package manager (sudo apt install element-desktop)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Duplicate https://github.com/vector-im/element-web/issues/22752
