### ISSUE TITLE
"$foo made no change" membership events are useless, ugly and confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23274]
### Steps to reproduce

1. Send a membership event which goes join->join (e.g. Dendrite getting confused)
2. In the timeline, you see:

<img width="266" alt="Screenshot 2022-09-14 at 07 38 42" src="https://user-images.githubusercontent.com/1294269/190078318-4223d342-51ee-4439-a884-5633fb13e69c.png">

3. This is great for debugging, but useless for everyone else. It should only be shown if you have invisible events turned on in the timeline via devtools.

#### What did you expect?

A human-focused timeline

#### What happened instead?

A developer-focused timeline

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

Nightly

### Application version

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> It should only be shown if you have invisible events turned on in the timeline via devtools.

This is already the case.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2403652/190096513-14f49bfb-18db-436e-907d-b399843c560c.png">
