### ISSUE TITLE
Third-party invites sent via federation lead to broken room state

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2328]
`@alice:alice.com` invites Bob via email to an invite-only room; Bob joins as `@bob:bob.com`. The invite is not signed by alice.com and is considered invalid; Alice never sees any events from Bob.

**Comment by ara4n** [comment]
assigning to erik as this is server woes.

**Comment by kittykat** [comment]
@richvdh I'm going to close this for now as we haven't experienced this issue when testing. If you can still reproduce it, please reopen!

**Comment by richvdh** [comment]
Yeah I don't know what this was about. Bob's `m.room.member` with `"membership":"invite"` doesn't need to be signed by Alice's server: rather it contains a `third_party_invite` property which validates it.

the 3pid invite flow has many problems, but this doesn't seem to be one of them.
