### ISSUE TITLE
"Widget PIP" > "should be closed on leave" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23286]
https://dashboard.cypress.io/projects/ppvnzg/runs/4003/test-results/d352eee3-0fb4-45f4-8e5a-254191ebc519

![Screenshot 2022-09-15 at 09-06-09 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/190411303-a1e39b3e-9dc9-45a5-9069-e4cd99c720d1.png)

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
