### ISSUE TITLE
Electron error on npm install new instance FREEBSD

### ISSUE THREAD

**Issue by JEAholding** [vector-im/element-web#23297]
### Steps to reproduce

1. Where are you starting? What can you see?
Brand new element installation on FREEBSD 13.1 

#### What did you expect?

I expected complete installation got the package.json from source and NPM install after configuring the matrix-synapse

#### What happened instead?

LOG of NPM....

```
6048 verbose cwd /usr/local/www/element
6049 verbose FreeBSD 13.1-RELEASE-p2
6050 verbose node v16.16.0
6051 verbose npm  v8.19.1
6052 error code 1
6053 error path /usr/local/www/element/node_modules/electron
6054 error command failed
6055 error command sh -c node install.js
6056 error HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v20.1.4/electron-v20.1.4-freebsd-x64.zip
6056 error     at EventEmitter.<anonymous> (/usr/local/www/element/node_modules/got/source/as-stream.js:35:24)
6056 error     at EventEmitter.emit (node:events:527:28)
6056 error     at module.exports (/usr/local/www/element/node_modules/got/source/get-response.js:22:10)
6056 error     at ClientRequest.handleResponse (/usr/local/www/element/node_modules/got/source/request-as-event-emitter.js:15
5:5)
6056 error     at Object.onceWrapper (node:events:642:26)
6056 error     at ClientRequest.emit (node:events:539:35)
6056 error     at ClientRequest.origin.emit (/usr/local/www/element/node_modules/@szmarczak/http-timer/source/index.js:37:11)
6056 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
6056 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
6056 error     at TLSSocket.socketOnData (node:_http_client:494:22)
6057 verbose exit 1
6058 timing npm Completed in 167151ms
6059 verbose unfinished npm timer reify 1663326247936
6060 verbose unfinished npm timer reify:build 1663326385192
6061 verbose unfinished npm timer build 1663326385202
6062 verbose unfinished npm timer build:deps 1663326385204
6063 verbose unfinished npm timer build:run:postinstall 1663326386279
6064 verbose unfinished npm timer build:run:postinstall:node_modules/electron 1663326386476
6065 verbose code 1
6066 error A complete log of this run can be found in:
6066 error     /root/.npm/_logs/2022-09-16T11_04_07_638Z-debug-0.log
```

##### FRONT GUI functions and is latest
THE APP/Desktop functions normal (TO MY light usage).
I looked at the electron release AND they do not have a freebsd source only darwin source path.... Have not look at issue further BUT I am assuming might be a routing/naming issue with electron OR element-web not sure. 

### Operating system

FREEBSD 13.1

### Browser information

NA

### URL for webapp

NA

### Application version

_LATEST_

### Homeserver

Latest based on freebsd PORT

### Will you send logs?

No , attached

**Comment by t3chguy** [comment]
Electron doesn't release for FreeBSD, so it is unsupported natively.
You could probably make it work using https://github.com/tagattie/FreeBSD-Electron but if electron-builder doesn't support it then you'll probably need to jump through some hoops to get it to work.

https://www.electron.build/configuration/linux.html seems to support `freebsd` so you may need to just modify the config to build for that.

**Comment by turt2live** [comment]
Closing as a presumed environmental issue. If this is untrue, please open a new issue with fresh reproduction steps for our team to review.
