### ISSUE TITLE
"Timeline" > "message displaying" > "should set inline start padding to a hidden event line" is still flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23296]
https://dashboard.cypress.io/projects/ppvnzg/runs/4080/test-results/8612d9f9-1c4c-437a-bee9-59be3e7f2d90

![Screenshot 2022-09-16 at 10-49-30 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/190667432-19b9febd-8a44-4f4e-a3ce-fd51132fbdef.png)

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
