### ISSUE TITLE
`sliding-sync/sliding-sync.ts` → „should clear the reply to field when swapping rooms“ fails

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23293]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/6216686/190629709-699c1571-728a-44f0-b8f0-e9141019d84f.png)

example https://dashboard.cypress.io/projects/ppvnzg/runs/4067/test-results/9e5090ea-5676-4ca1-bea1-efef606baf98

**Comment by t3chguy** [comment]
This is unrelated to sliding sync, this is the app not loading (or white screening)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23256

**Comment by weeman1337** [comment]
Oh yes, I have to take a closer look to the report next time :+1:

**Comment by richvdh** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/13362/test-results/d7d37ecc-fcc8-45a0-8b8d-ad036635e688

**Comment by richvdh** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/14407/test-results/ea8e6eea-5918-47f8-b17c-289200179773

**Comment by t3chguy** [comment]
Test was skipped/removed
