### ISSUE TITLE
`integration-manager/kick.spec.ts` → „should no-op if the target was banned “ fails

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23292]
### Steps to reproduce

Error `Timed out retrying after 10000ms: Expected to find content: 'Bob joined the room' but never did.`

Messages are collapsed

![image](https://user-images.githubusercontent.com/6216686/190612388-82f6cff4-cd11-46b6-aa07-817413a05891.png)

Example https://dashboard.cypress.io/projects/ppvnzg/runs/4058/test-results/ca3edb03-8648-44cc-9409-7c93edaae285

**Comment by turt2live** [comment]
I haven't been able to get a stable environment going to fix this, but also it's not super flaky at the moment - returning to backlog.

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
