### ISSUE TITLE
Cypress: Your Element is misconfigured flake

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23294]
### Steps to reproduce

Example https://dashboard.cypress.io/projects/ppvnzg/runs/4072/test-results/96ab4e37-931b-45d9-b1b6-c5988afee57f

![image](https://user-images.githubusercontent.com/6216686/190645929-d5d480df-6956-42a5-a9c7-4c013d4ac1b1.png)

This is different from the „blank screen“ issue:

![image](https://user-images.githubusercontent.com/6216686/190646027-386910d4-7c8a-4b3e-a242-15bf75595fa7.png)

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
