### ISSUE TITLE
Cancelling the Element Home dialog yields two cancel buttons

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#23306]
### Steps to reproduce

1. In the home page, I click on my avatar
2. I click on "Upgrade to Element Home"
3. I click on the arrow at the top right
4. I have a modal with two cancel buttons

<img width="786" alt="Screenshot 2022-09-19 at 15 06 10" src="https://user-images.githubusercontent.com/2621378/191024075-3a1cb47c-38a4-46dc-a4cd-cedf19df029c.png">

#### What did you expect?

I expect to have on cancel button

#### What happened instead?

I have two  cancel buttons

### Operating system

macOS

### Browser information

Chrome 105.0.5195.125 (Official Build) (arm64)

### URL for webapp

https://app.element.io/

### Application version

Version de Element : 1.11.5 Version de Olm : 3.2.12

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Here is the English dialog:

![image](https://user-images.githubusercontent.com/6216686/191181216-5eb924b9-4fa9-4536-923f-1b9cf0b85716.png)

Also updated the title, so that other can find it more easily.

**Comment by turt2live** [comment]
it's a little annoying we don't have a way to make dark patterns like this prioritized :(
