### ISSUE TITLE
Minor issue: Participants shown muted, when not.

### ISSUE THREAD

**Issue by Arkoprovo1996** [vector-im/element-web#23305]
### Steps to reproduce

Having a video-call with few people. In our case it was 4.

#### What did you expect?

Everyone be shown muted when they're muted, and, unmuted when they're speaking.

#### What happened instead?

Some of the participants were shown muted but were speaking. Like the audiometers, speech detection border, everything was working fine. Just the muted mic icon was continuously being displayed for them.

### Operating system

Manjaro Linux (Xorg + Pipewire) & Windows: It was okay. Artix Linux (Wayland + Pipewire) & Ubuntu 18.04: Were shown muted.

### Browser information

Firefox 103.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.5 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Have you seen this more than once? I am afraid we won't be able to debug this very well since the issues seems to be with Jitsi

**Comment by turt2live** [comment]
Closing due to lack of response. If you're still seeing this, please open a new issue with fresh reproduction steps for our QA team to review.
