### ISSUE TITLE
Avatar is blank in Element Call video rooms

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#23301]
### Steps to reproduce

1. Set a Avatar
2. Join a Element Call with Element Web

### Outcome

![grafik](https://user-images.githubusercontent.com/1436958/190805818-43503540-0bd4-4117-abfd-6cb007ab8baa.png)

### Operating system

Any

### Browser information

Desktop

### URL for webapp

messenger.3dns.eu

### Will you send logs?

No

**Comment by robintown** [comment]
This happens because the EC widget has no idea what the homeserver URL is, and so it spits out `/_matrix/media/r0/thumbnail/example.org/xyz` as the image src, with no protocol or domain. We need to thread that information through EC into the js-sdk.

**Comment by t3chguy** [comment]
> Can the home server domains be reliably obtained by the user id's? 

Yes, using the well-known lookup as specced https://spec.matrix.org/v1.4/client-server-api/#server-discovery

**BUT** I would advise against this as it'd leak your public IP address to servers other than your own.

**Comment by robintown** [comment]
@toger5 You shouldn't need to know anything more than the user's own homeserver URL, since the media endpoint will automatically pull files in over federation if it's not yet on your own server
