### ISSUE TITLE
Verifying "status exceeded for this country (status 429)   - when trying to verify profile

### ISSUE THREAD

**Issue by cbitsco** [vector-im/element-web#23308]
### Steps to reproduce

Step 5 Setup your Profile
add Phone number, Enter my mobile, press "Add"
![image](https://user-images.githubusercontent.com/15198890/191043741-aa9f83c5-4460-4b2a-9d69-1300f8e854de.png)

…

### Operating system

Windows 11 64bit Dev beta

### Application version

Element version: 1.11.5 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue with matrix.org - not element-web
