### ISSUE TITLE
Export Chat doesn't show images

### ISSUE THREAD

**Issue by ruben1PvP** [vector-im/element-web#23309]
### Steps to reproduce

1. Click on "Export Chat" 
2. Select the "HTML" and the "Include attachments" option
3. Open the html in a browser
4. You will see the chat perfectly fine except for the images, as you will only see white squares.

Tried on Mozilla Firefox 104.0.2 and Google Chrome 105.0.5195.127

#### What did you expect?
Everything about the chat is visible, including images
#### What happened instead?
Instead of the actual images, you only see the square where the images should have been.

### Operating system

Windows 10

### Application version

Element version 1.11.5

### How did you install the app?

element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Already fixed on develop.
