### ISSUE TITLE
Error decrypting image

### ISSUE THREAD

**Issue by vladh** [vector-im/element-web#23310]
### Steps to reproduce

1. Send an image to a chat

#### What did you expect?

I expected the image to appear.

#### What happened instead?

Instead of the image, all parties (including myself) see "Error decrypting image".

This problem previously did not happen, and it randomly started happening a few days ago.

I would love to debug this problem in more detail but it's not clear to me how to see any actually helpful logs.

### Operating system

Arch Linux

### Application version

Element 1.11.4

### How did you install the app?

Arch repos

### Homeserver

Synapse 1.53.0-1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2022-09-19T18:40:52.993Z W Unable to decrypt attachment:  Failed to fetch
TypeError: Failed to fetch
```

I suggest checking your server logs for why it failed to fetch

**Comment by vladh** [comment]
Is there a way to check these client-side logs you just looked at as an end-user?

**Comment by t3chguy** [comment]
Yes, on the page you sent them from there is a `Download logs` button

**Comment by vladh** [comment]
The issue was a misconfiguration of my webserver, thank you. My suggestion would be to make the logs a bit more visible to the end-user, so that those running the instances can more readily know what's wrong.
