### ISSUE TITLE
vector-web plays notification sounds even with "Enable audible notifications in web client" unchecked

### ISSUE THREAD

**Issue by aliencq** [vector-im/element-web#2332]
![selection_130](https://cloud.githubusercontent.com/assets/7108174/18756853/fa5dd1dc-80e0-11e6-82f4-71b9ec41a4a7.png)

**Comment by gdvine** [comment]
Seeing this bug in macOS desktop v1.7.7.

"Noisy" settings still chime even with box unchecked.

**Comment by t3chguy** [comment]
Closing as presumed fixed
