### ISSUE TITLE
EC video room PIP resizing and positioning

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23337]
### Steps to reproduce

Start an EC video room and PIP it by switching to a different room.  Then, lament that you can't move the PIP to arbitrary coordinates on the page (it insists on snapping to the corner, which is just annoying - i want to move it to wherever i have dead space on the window), and you can't resize it to make it a bit larger so you can see people better.

#### What did you expect?

No snap and resizable PIP

#### What happened instead?

Snap to corner and fixed size PIP

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20056
