### ISSUE TITLE
Invite button in EC video rooms doesn't work

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23335]
**Steps to reproduce:**

1. Join an Element Call video room or a group call
2. Inside the widget, open the 'more options' menu and use the 'invite' button to get a link to the call
3. Share the link with someone

**What did you expect?**

Either it shouldn't be possible to get the link, or the link should work.

**What happened instead?**

Since call.ems.host has federation disabled, and since some calls happen in private rooms, guests will not be able to use the link to access the call.

**Comment by turt2live** [comment]
What does "doesn't work" mean?
