### ISSUE TITLE
Clicking a Matrix ID in the timeline takes the user to the home screen

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#23342]
### Steps to reproduce

1. Click a Matrix ID in the timeline

#### What did you expect?

The user profile sidebar to appear.

#### What happened instead?

The user profile sidebar appeared, but with a broken back button, and unexpectedly being redirected to the Home screen.

[Screencast from 09-22-2022 05:44:49 PM.webm](https://user-images.githubusercontent.com/1342360/191805513-256aacfa-62dd-4e0a-afa5-fdc7ef7ad5e3.webm)

In the video I click the back button twice, causing it to disappear (clicking it once does nothing).

### Operating system

Arch Linux

### Application version

Element version: 2022090801 Olm version: 3.2.12

### How did you install the app?

The AUR

### Will you send logs?

Yes

**Comment by uhoreg** [comment]
It seems to work as expected if the MXID is a pill, but not if it is plain text

**Comment by SimonBrandner** [comment]
This sorta makes sense to me since pill is always a member of the room but a matrix.to link does not have to be

**Comment by uhoreg** [comment]
This issue also occurs when the MXID belongs to a user in the room.

**Comment by t3chguy** [comment]
This now takes me to matrix.to in the same tab :/

**Comment by t3chguy** [comment]
This works fine on https://riots.im/1.11.35/ but not on develop. This seems to be related to @Johennes updating linkifyjs :/

**Comment by t3chguy** [comment]
Looks like it is due to [4.1.1](https://github.com/Hypercontext/linkifyjs/blob/main/CHANGELOG.md#v411)

> Ensure function options get called with unformatted href

**Comment by Johennes** [comment]
Thanks for fixing this @t3chguy!
