### ISSUE TITLE
Thesis - admin bot in DM

### ISSUE THREAD

**Issue by jlfrance** [vector-im/element-web#23347]
### Steps to reproduce

1. When I create a DM chat, it adds adminbot to the room 

![Screenshot 2022-09-23 at 5 37 06 PM](https://user-images.githubusercontent.com/31907495/191999109-7a377c3d-9074-4986-b8ff-0a94b0c15548.png)
![Screenshot 2022-09-23 at 5 38 12 PM](https://user-images.githubusercontent.com/31907495/191999187-29ce1009-642c-473c-8055-b433e0ee6fd2.png)

Internal Room ID !FeHOExeeoNJNucIohZ:thesis.co

#### What did you expect?
I do not expect adminbot to be added to a DM 

#### What happened instead?
Every DM I create, adminbot is added to the room and the room name is "adminbot and 2 others"

### Operating system

macOS

### Application version

Element version: 1.11.5 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#download

### Homeserver

chat.thesis.co

### Will you send logs?

Yes

**Comment by Half-Shot** [comment]
@t3chguy Sorry, this is a EMS customer request. The admin bot joining the room is expected, the problem is the name shouldn't contain "adminbot" (e.g. https://github.com/vector-im/element-web/issues/22894). I've already verified that the state event is set in

```json
        {
            "content": {
                "service_members": [
                    [
                        "@adminbot:thesis.co",
                        "@auditbot:thesis.co"
                    ]
                ]
            },
            "origin_server_ts": 1663191054699,
            "room_id": "!FANMJlbrDcRxcQycUv:thesis.co",
            "sender": "@adminbot:thesis.co",
            "state_key": "",
            "type": "io.element.functional_members",
            "unsigned": {
                "age": 747271222
            },
            "event_id": "$R3Lvu-EzGwVGV9HH35Qm_tA7TpqMNQW3wOmKYPLmw5Y",
            "user_id": "@adminbot:thesis.co",
            "age": 747271222
        },

```

**Comment by t3chguy** [comment]
This is a js-sdk issue, `calculateRoomName` doesn't get called when a new `io.element.functional_members` event is received.

**Comment by Shadowfiend** [comment]
Hey folks, I want to clarify that it is *not* expected that adminbot join these DMs, as it is explicitly configured not to. The issue is not in a client or client SDK, it is in the bot itself (not sure that this is the right place for the bug report in that context, however—happy to redirect accordingly). See below for config. 

![Adminbot config](https://user-images.githubusercontent.com/8245/194547212-cce34dde-8850-4ea9-ab14-597ce6c448d0.png)

**Comment by t3chguy** [comment]
@Half-Shot ^^ th
