### ISSUE TITLE
[Start DM] Look for an actual account in case of email address

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#23353]
### Your use case

When I open the contact picker to start a new DM, and type an email address, Element-Web doesn't check whether an actual account is discoverable for this email, whereas I configured an identity server in my profile.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/8969772/192235010-6fc2639a-1ea0-4ad0-8a9b-16482dc5fa96.png">

Element-Android triggers a lookup request to replace this email address with a potential actual account

There is multiple advantages to discover user on email here:
- the end user has the confirmation their contact has a matrix account
- we worked on a new flow to create DM only on the first message https://github.com/vector-im/element-web/issues/14736, select a matrix id is more powerful than an email in this case
- prevent the application from creating a new DM whereas one is already created for this user

### Additional context

The same enhancement is requested for Element-iOS: https://github.com/vector-im/element-ios/issues/6497

**Comment by t3chguy** [comment]
Hmm this seems to have regressed https://github.com/vector-im/element-web/issues/2933

**Comment by weeman1337** [comment]
Giving this a major severity, because you end up in having multiple DMs with the same person.
