### ISSUE TITLE
 Ubuntu apt gives 404 error for repo URL

### ISSUE THREAD

**Issue by aethralis** [vector-im/element-web#23364]
### Steps to reproduce

The issue is similar to [18349](https://github.com/vector-im/element-web/issues/18349), but this time it tries to download element-desktop_1.11.6-test

The whole error message is as follows:

```
Err:1 https://packages.riot.im/debian default/main amd64 element-desktop amd64 1.11.6-test.1
404  Not Found [IP: 172.67.70.226 443]
E: Failed to fetch https://packages.riot.im/debian/pool/main/e/element-desktop/element-desktop_1.11.6-test.1_amd64.deb  404  Not Found [IP: 172.67.70.226 443]
```

### Outcome

I expected the upgrade to go smoothly.

### Operating system

Ubuntu 22.04

### Application version

1.11.5

### Homeserver

https://packages.riot.im/debian repo

### Will you send logs?

No

**Comment by t3chguy** [comment]
Thanks for reporting, this has now been fixed! Machinery test gone wrong
