### ISSUE TITLE
Joined rooms are missing from updating to v1.11.7

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#23368]
### Steps to reproduce
We've upgraded from Element Web 1.11.5 to Element Web 1.11.7 on EMS staging (not live yet).
We've skipped 1.11.6 which was released yesterday.

### Outcome
On some accounts rooms are missing after the upgrade.

#### What did you expect?
All rooms are in the room list.

### Operating system

Manjaro Linux

### Browser information

Firefox 105

### Application version

Element version: 1.11.7 Olm version: 3.2.12

### Homeserver

EMS staging

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Yup, a workaround is to log out and back in. We're about to ship 1.11.8 which fixes this, for anyone affected you can either log out and back in, or wait for 1.11.8 (due in the next 1-2 hours) and then Settings > Help & About > Clear cache and reload

**Comment by t3chguy** [comment]
Version 1.11.8 which addresses this issue has shipped on app.element.io, staging.element.io, releases and Element Desktop. Please update and clear cache and reload in Settings > Help & About
