### ISSUE TITLE
The lazy loading dialog is making repeat appearances

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23377]
### Steps to reproduce

According to [a user's report](https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$ExxhrDmkPJR4pHH9zXZcP19cIirCjhw8E03nj4KdXuM?via=matrix.org&via=privacytools.io&via=mozilla.org):

1. Update to the latest develop.element.io
2. Get the lazy loading dialog
3. Press the OK button
4. Element reloads
5. goto 2

This is also reproducible by running any of our Cypress tests.

#### What did you expect?

The lazy loading dialog should not appear

#### What happened instead?

![cypress-screenshot(1)](https://user-images.githubusercontent.com/48614497/193181914-130d13dd-8739-46c2-abc5-ad1cec51e957.png)

Since the dialog appears repeatedly on each reload, this effectively blocks all interaction with the app.

### Operating system

NixOS unstable

### Browser information

Chromium 105.0.5195.125

### URL for webapp

The develop branch

### Application version

Element version: 8e841be39310-react-7a33818bd7ec-js-f398e3564d14 Olm version: 3.2.12

### Will you send logs?

No

**Comment by robintown** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/2713 likely related

**Comment by robintown** [comment]
Tentative fix:

```diff
diff --git a/src/store/indexeddb-local-backend.ts b/src/store/indexeddb-local-backend.ts
index 0ab50db35..21166f575 100644
--- a/src/store/indexeddb-local-backend.ts
+++ b/src/store/indexeddb-local-backend.ts
@@ -167,6 +167,10 @@ export class LocalIndexedDBStoreBackend implements IIndexedDBBackend {
             logger.log(
                 `LocalIndexedDBStoreBackend.connect: upgrading from ${oldVersion}`,
             );
+            if (oldVersion < 1) {
+                // The database did not previously exist
+                this._isNewlyCreated = true;
+            }
             DB_MIGRATIONS.forEach((migration, index) => {
                 if (oldVersion <= index) migration(db);
             });
```

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2713
