### ISSUE TITLE
Incorrect cursor theme & size on Wayland 

### ISSUE THREAD

**Issue by johns2s** [vector-im/element-web#23371]
### Steps to reproduce

Using the latest version of Element from Flathub, Fedora 36 or 37, and GNOME Shell 42 or 43, start Element using Wayland as the backend (`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`). Observe incorrect cursor theme. Enable fractional scaling, restart Element, and observe both incorrect cursor theme and incorrect cursor size.

### Outcome

This appears to be a relatively new regression. The last version that doesn't experience this is Element version: 1.11.4 Olm version: 3.2.12, commit `10bc554f8f5b2b2185eda3b6a03886643acf13ba3cd3a408b8ab96ab742f9f59` on Flathub. Starting from the next release (though same version number), at commit `21ca5fd133f102bbef56dfe78b16969219bad3eded4a6b70d583be8bd5d08acc`, the cursor behaves strangely when using Wayland.
* The cursor theme is incorrect regardless of whether fractional scaling is on
* With fractional scaling set to 125%, the cursor is tiny except for when it is in a hovering state, at which point it becomes enormous.

Theme issue, without scaling:
[Screencast from 2022-09-28 20-12-51 (trimmed).webm](https://user-images.githubusercontent.com/33157607/192911073-89c23025-ab24-4088-9aa1-9492145d87c8.webm)

Size issue, with scaling:
[Screencast from 2022-09-28 19-30-45.webm](https://user-images.githubusercontent.com/33157607/192911123-fc3a49fa-27aa-449f-9954-58a024a4d6b9.webm)

I initially assumed this was an Electron issue, but both the affected and unaffected versions of Element use Electron 20.0.3.

### Operating system

Fedora 36 and 37

### Application version

Element version: 1.11.4 Olm version: 3.2.12 through latest release

### How did you install the app?

Flathub

### Will you send logs?

No

**Comment by weeman1337** [comment]
@johns2s thank you for reporting this issue. Can you test if the previous version still doesn't have this issue? So we can be sure that no other package or system update caused the problem.

**Comment by johns2s** [comment]
> @johns2s thank you for reporting this issue. Can you test if the previous version still doesn't have this issue? So we can be sure that no other package or system update caused the problem.

It does, before reporting I tried a bunch of different versions until I found where it stopped working.

**Comment by johns2s** [comment]
After some more digging, I found this was a problem in recent releases of FluffyChat, which uses Flutter, as well. It turns out this issue is a regression introduced in version 22.08 of the Freedesktop Platform used on Flathub releases of Element. I'll close this here and file an issue on the flathub release's Github to update the runtime.
