### ISSUE TITLE
Fix flaky sliding-sync.ts end to end tests

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23373]
I have noticed multiple PRs where sliding-sync.ts has been flaky

https://github.com/matrix-org/matrix-react-sdk/pull/9328 for instance (see commit [5491089](https://github.com/matrix-org/matrix-react-sdk/pull/9328/commits/54910891f61aeeebf57625ea1d6ee7650b18f737))

**Comment by t3chguy** [comment]
This flake is unrelated to sliding sync (app failed to load)

![image](https://user-images.githubusercontent.com/2403652/193215443-14c7ff9b-f596-4b34-9070-680b828650d1.png)

Duplicate of https://github.com/vector-im/element-web/issues/23256
