### ISSUE TITLE
Incompatible browser warning page doesn't scroll on tiny browser windows

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23376]
### Steps to reproduce

1. Have an incompatible browser (access webpack over the network on http)
2. Try to open Element
3. "Incompatible browser" warning (expected)
4. Can't scroll down to accept button

In my case, I created the incompatible browser by having a Windows VM on my dev machine with my dev machine running webpack. Accessing Element over the network by hitting my dev machine's private IP forces the browser to use http (not https) and because it's not `localhost` it drops things like subtlecrypto, which we require to run.

I had each window in a corner of a 1024x768 screen to reproduce this.

![image](https://user-images.githubusercontent.com/1190097/193133282-71924e35-68c4-42aa-a17b-7ed840951a8f.png)

(after clicking through - just demonstrating layout)

#### What did you expect?

To be able to scroll. The fact that the window is unusably small shouldn't prevent the scroll wheel from working.

#### What happened instead?

No scroll :(

### Operating system

Windows 10 & 11

### Browser information

Edge, Chrome, and Firefox on both

### URL for webapp

localhost / private IP

### Application version

develop

### Homeserver

localhost

### Will you send logs?

No

**Comment by justjanne** [comment]
Screenshot of the issue itself:

![Screenshot from 2022-10-04 14-07-09](https://user-images.githubusercontent.com/3933349/193815314-2791debc-bc34-416f-9bbc-fbf6f4b953c4.png)
