### ISSUE TITLE
Invalid implementation of MSC3890

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#23384]
> While no local_notification_settings event exists for the current device, or a local_notification_settings event exists where is_silenced is falsy, events should be processed as normal and trigger system notifications and sounds where necessary.

Says to treat no event or no `is_silenced` as if it were false, we default to true: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/utils/notifications.ts#L54

~The wrong unstable prefix is used also `org.matrix.msc3890.local_notification_settings` vs https://github.com/matrix-org/matrix-spec-proposals/blob/60695654956019c51f88f0f88ca02280ef00bc13/proposals/3890-remote-local-notification-toggle.md#unstable-prefix~

**Comment by gsouquet** [comment]
The rendered link in the MSC does not point to the latest commit. The implementation is correct
