### ISSUE TITLE
Screensharing in Element Call-powered calls doesn't work on Desktop

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#23382]
### Steps to reproduce

1. Start a Element Call in your Desktop app

### Outcome
`Enabling screensharing error DOMException: Permission denied`

![grafik](https://user-images.githubusercontent.com/1436958/193269395-3b27e34d-d75f-43f0-a4f9-4f7e079ad143.png)

### Operating system

Windows

### Browser information

Electron Client

### URL for webapp

https://voip.messenger.3dns.eu/

### Will you send logs?

Yes

**Comment by Thatoo** [comment]
Same issue on GNU/Linux/Debian.

**Comment by DoM1niC** [comment]
Fully fixed by https://github.com/vector-im/element-call/pull/652 for Desktop App
