### ISSUE TITLE
Room Notification settings: Clicking on "settings" link also selects the option

### ISSUE THREAD

**Issue by jaller94** [vector-im/element-web#23391]
### Steps to reproduce

1. Open any room's settings.
2. Go to the tab "Notifications"
3. Click on a "settings" link of an option that is not currently selected.

![Screenshot 2022-10-02 at 18-19-13 Element P2P Matrix](https://user-images.githubusercontent.com/10872136/193464965-9f909981-1686-4376-b82a-58ebf4269df1.png)

#### What did you expect?
1. The global notification settings open.

#### What happened instead?
1. The option is selected.
2. Additionally, the global notification settings open.

### Browser information

Firefox 105.0b4

### URL for webapp

app.element.io

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by SoldierCorp** [comment]
Hi @jaller94 !

I believe it's working as expected. The option is being selected and the global settings gets open. Although the selected option it's not visible until you re-open the room settings.

https://user-images.githubusercontent.com/1775881/193954550-ad6d4146-7e74-45ae-a3d5-3ed0f546c7fa.mov

**Comment by jaller94** [comment]
As a user I don't expect a link to trigger a second action.
The link is a component inside the label. Other applications like Firefox, Chromium and VS Code don't toggle checkboxes when you click on links like "Learn more" inside a label.

**Comment by SoldierCorp** [comment]
@jaller94 You know what, I read the expected behaviours in the opposite way. Now I know this is wrong and it's supposed to only open Global Notifications without selecting the option.

I would like to work on this one, could you please assign it to me?

**Comment by BhuvaneshPatil** [comment]
@jaller94 , can we close this issue as it's resolved in the mentioned PR
