### ISSUE TITLE
Misaligned reply preview in thread composer

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23396]
### Steps to reproduce

1. Open a thread and hit reply

#### What did you expect?

The reply preview should be aligned with the cursor

#### What happened instead?

<img width="578" alt="Screen Shot 2022-10-03 at 13 08 03" src="https://user-images.githubusercontent.com/769871/193573304-0f78ae32-03cd-4b5d-98e0-f5f426acc1bb.png">

### Will you send logs?

No

**Comment by SoldierCorp** [comment]
Hi @gsouquet !

Is this the expected design change? I moved the `Replying` box to the left.
![image](https://user-images.githubusercontent.com/1775881/193953117-ab4764bd-636b-4778-9f9e-3d57c05b3e70.png)

Or this one? I moved the `message box` a little bit to the right.
![image](https://user-images.githubusercontent.com/1775881/193955055-edfb2a3e-3c31-4351-bd33-96c13194b787.png)

**Comment by gsouquet** [comment]
The former seems more adequate! Thank you
