### ISSUE TITLE
Cannot start a dm with a user if `limit_profile_requests_to_users_who_share_rooms` is true in the synapse config

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#23403]
### Steps to reproduce

1. Set `limit_profile_requests_to_users_who_share_rooms: true` in synapse
2. Create a new user
3. Try to invite the user

#### What did you expect?

Possibly telling me there was an error but allowing me to ignore this

#### What happened instead?

There is no way of inviting the user to a new DM as the server returns a 403 "Profile is not available" error

### Operating system

Windows

### Browser information

Firefox 105.0 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 8e841be39310-react-a49603b9b84a-js-91171afddd6d Version von Olm: 3.2.12

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/17269
