### ISSUE TITLE
Invalid homeserver-url check

### ISSUE THREAD

**Issue by Jan-NiklasB** [vector-im/element-web#23419]
### Steps to reproduce

1. Setup matrixdotorg/synapse docker
2. setup apache reverse proxy to redirct 443, 8448, 80 to docker container
------------------------ Done about a year ago, was working as suspected until now---------------------------

3. Try to connect to server via element app (Linux repo) and Web UI

#### What did you expect?
Successful login on server

#### What happened instead?
"Homeserver-URL doesn't seems to be a valid matrix-homeserver"

In Logfile the request looks like this:

``2022-10-04 17:42:46,653 - synapse.access.http.8008 - 459 - INFO - GET-601 - 123.123.123.123 - 8008 - {None} Processed request: 0.000sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 265B 200 "GET /_matrix/client/versions HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.8 Chrome/104.0.5112.102 Electron/20.1.1 Safari/537.36" [0 dbevts]
``

federationtester.matrix.org gives the following output:

```{
  "WellKnownResult": {
    "m.server": "matrix.mydomain.org:443",
    "CacheExpiresAt": 0
  },
  "DNSResult": {
    "SRVSkipped": true,
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": null,
    "Hosts": {
      "matrix.ydomain.org": {
        "CName": "matrix.mydomain.org.",
        "Addrs": [
          "X.X.X.X"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "X.X.X.X:443"
    ]
  },
  "ConnectionReports": {
    "X.X.X.X:443": {
      "Certificates": [
        {
          "SubjectCommonName": "matrix.mydomain.org",
          "IssuerCommonName": "R3",
          "SHA256Fingerprint": "XXXXXXXX",
          "DNSNames": [
            "matrix.mydomain.org"
          ]
        },
        {
          "SubjectCommonName": "R3",
          "IssuerCommonName": "ISRG Root X1",
          "SHA256Fingerprint": "Z63RFmsCCuYbj1/JaBPATCqliZYHloZVcqPH5zdhPf0",
          "DNSNames": null
        },
        {
          "SubjectCommonName": "ISRG Root X1",
          "IssuerCommonName": "DST Root CA X3",
          "SHA256Fingerprint": "bZn7Jl6xxbN0R2X8vGSPPNjhv/r9xML5m51Hz3/xwk8",
          "DNSNames": null
        }
      ],
      "Cipher": {
        "Version": "TLS 1.3",
        "CipherSuite": "TLS_AES_256_GCM_SHA384"
      },
      "Checks": {
        "AllChecksOK": true,
        "MatchingServerName": true,
        "FutureValidUntilTS": true,
        "HasEd25519Key": true,
        "AllEd25519ChecksOK": true,
        "Ed25519Checks": {
          "ed25519:a_Uxdc": {
            "ValidEd25519": true,
            "MatchingSignature": true
          }
        },
        "ValidCertificates": true
      },
      "Errors": [],
      "Ed25519VerifyKeys": {
        "ed25519:a_Uxdc": "XXXXXXX"
      },
      "Info": {},
      "Keys": {
        "old_verify_keys": {},
        "server_name": "matrix.mydomain.org",
        "signatures": {
          "matrix.mydomain.org": {
            "ed25519:a_Uxdc": "XXXXXXXXXXX"
          }
        },
        "valid_until_ts": 1664989368408,
        "verify_keys": {
          "ed25519:a_Uxdc": {
            "key": "XXXXXXXXX"
          }
        }
      }
    }
  },
  "ConnectionErrors": {},
  "Version": {
    "name": "Synapse",
    "version": "1.68.0"
  },
  "FederationOK": true
}
```

(Connection via element app on android still works without problems)

### Operating system

Linux Mint Cinnamon 20.1

### Application version

element-desktop 1.11.8

### How did you install the app?

via repo as described on setup page

### Homeserver

Synapse docker image 1.68.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Sounds like a CORS issue. Needs logs. I suggest reading https://spec.matrix.org/v1.4/client-server-api/#web-browser-clients

**Comment by t3chguy** [comment]
Then please provide logs from the Chromium console.

**Comment by Jan-NiklasB** [comment]
How can I get them from the desktop-app?

**Comment by Jan-NiklasB** [comment]
Never mind... had some CORS setting wich worked till now, but seems like the made problems now...
After commenting out it works now
Sorry for wasting your time
