### ISSUE TITLE
Room incorrectly shown as having unread messages

### ISSUE THREAD

**Issue by dkozel** [vector-im/element-web#23416]
### Steps to reproduce

I've noticed several times over the past week that Spaces would be shown with the black circle marker indicating that a room in them has unread messages. Opening the space, the room listing would show a room name in bold with the circle marker. However upon opening the room and scrolling around the unread messages marker would remain despite there being no unread messages.

After some time reading other rooms, switching back and forth, and reloading the Element Web browser tab the room status would change to correctly show no unread messages.

I will submit logs the next time this occurs.

#### What did you expect?
Opening a room with the unread messages marker would either show the button to scroll to the oldest unread message or would just show recent unread messages. The Space and Room names in the left hand lists would revert to unbolded and the circle marker would go away.

#### What happened instead?
The Space and Room names were still shown with the circle indicator and the Room name was bolded.

### Operating system

Windows 11, Ubuntu 20.04

### Browser information

Firefox 105.0.1

### URL for webapp

https://chat.gnuradio.org

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### Homeserver

gnuradio.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
@dkozel do you have the threads beta enabled?

**Comment by dkozel** [comment]
Yes, I just checked and it's enabled by default.

**Comment by t3chguy** [comment]
Threads is not enabled by default unless your instance chooses for it to be:

![image](https://user-images.githubusercontent.com/2403652/193896731-68732ade-aa39-4f95-a301-11edc369610a.png)

This is a known issue with threads: https://github.com/vector-im/element-web/issues/21114
