### ISSUE TITLE
ability to remove invites from the ui without explicitly rejecting them (i.e. ignore invites)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2341]

**Comment by ara4n** [comment]
This would provide a viable solution to many of the stuck invites, which are caused by the server not letting you reject an invite if it can't relay it to the originating server (e.g. if that server is now down).  Whereas saying "hey, i just want to delete this invite from the list" would be adequate.  Would solve:
 * https://github.com/vector-im/riot-web/issues/3580
 * https://github.com/vector-im/riot-web/issues/3743
 * https://github.com/vector-im/riot-web/issues/4225
 * https://github.com/vector-im/riot-web/issues/4374
and probably most other stuff in https://github.com/vector-im/riot-web/labels/stuck-invite

**Comment by rubo77** [comment]
Possible workarounds: https://gist.github.com/turt2live/7bf1e589664298d786dfa6aeccda294a

Which is the safest for not to get stuck with a "room does not exist" error

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19118
