### ISSUE TITLE
Cannot close element in a window manager (without a DE?)

### ISSUE THREAD

**Issue by ffaf1** [vector-im/element-web#23428]
### Steps to reproduce

1. install a system without a Desktop Environment (in this case, `xorg` +` xmonad`)
2. launch `element` *from the terminal*
3. close the window via your window manager (e.g. press e.g. ⌂+c)
5. the window is not gone but check the termina: you can see the program has not finished running

#### What did you expect?

Program terminates.

#### What happened instead?

Window is gone, but program still running.

### Operating system

Debian 11.5

### Application version

Element version: 1.10.15 Olm version: 3.2.8

### How did you install the app?

appimage (Element-v1.10.15.glibc2.31.AppImage)

### Homeserver

tchncs.de

### Will you send logs?

No

**Comment by t3chguy** [comment]
The default behaviour is to minimize to tray, you can turn this off in Settings > Preferences.
