### ISSUE TITLE
Cypress parallelzation falls over due to "environment mismatch" sometimes

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23423]
See https://github.com/matrix-org/matrix-react-sdk/actions/runs/3185062590/attempts/1 for the 2/3 failed environments.

**Comment by t3chguy** [comment]
https://github.com/cypress-io/github-action/issues/602

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
