### ISSUE TITLE
Volume control doesn't work on E2E notifications

### ISSUE THREAD

**Issue by aviraldg** [vector-im/element-web#2342]
Erik says so. Manifests as notifications showing up for e2e rooms even if they're turned off from settings

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/6745

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/2256

**Comment by jryans** [comment]
I added separate volume controls for encrypted messages in https://github.com/matrix-org/matrix-react-sdk/pull/2346. Maybe that's enough to mark this as fixed then?

**Comment by ara4n** [comment]
hm, that doesn't affect it ignoring the specified muteness/noisiness on the room, though, does it?

**Comment by jryans** [comment]
Here's what I get when using the "Encrypted messages in group chats" global control in Settings combined with the per-room volume control for an E2E room:

  | Global: Off | Global: On | Global: Noisy
--- | --- | --- | ---
**Room: Mute** | 🤫 | 🤫 | 🤫
**Room: All Messages** | 🤫 | ✉️ | 🔔
**Room: Noisy** | 🔔 | 🔔 | 🔔

🤫 = nothing happens
✉️ = silent notification
🔔 = noisy notification

**Comment by jryans** [comment]
@ara4n Does the table above match the desired state here? If so, then it seems fixed.

**Comment by kittykat** [comment]
I'm going to close this issue for now as the issue seems to be resolved, please file a new one if any further changes are needed.
