### ISSUE TITLE
chats keep appearing as unread/unseen; sending read receipts is disabled and cannot be enabled

### ISSUE THREAD

**Issue by Flupp** [vector-im/element-web#23424]
### Steps to reproduce

When I activate a chat that is marked as having unread messages, the marker disappears as expected. However, after restarting Element, the unread marker reappears although there are no new messages.

I noticed that the “Send read receipts” option is disabled for me and I cannot enable it:
![Screenshot_20221005_114005](https://user-images.githubusercontent.com/364471/194032549-2de7d61f-83d7-4640-9ed8-a308f373d6fe.png)
Considering https://github.com/vector-im/element-web/issues/2527#issuecomment-754238668, this might be related. For other users of the same server, the option appears as enabled (and cannot be disabled). Those users do not experience any issues related to unread message status.

I tried Thunderbird as an alternative client and it seems that it persistently marks messages as read as expected. Those messages then also appear as read in Element.

#### What did you expect?

Messages marked as read keep being marked as read.

#### What happened instead?

After restarting Element, messages that were marked as read before appear as unread again.

### Operating system

Arch Linux

### Application version

Element version: 1.11.8, Olm version: 3.2.12

### How did you install the app?

`pacman -S element-desktop`

### Homeserver

Synapse

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Ok, this is very interesting... What is the address of your homeserver (e.g. matrix.org)?

**Comment by Flupp** [comment]
Unfortunately it’s a server run within a company and for employees only. What particular information do you need?

**Comment by SimonBrandner** [comment]
I am interested in the server version and the features supported by the server - i.e the response to `{homeserver_url}/_matrix/client/versions` (e.g. `https://matrix.org/_matrix/client/versions`)

This will help determine if the feature is supported by the server and by that help us determine what's going wrong in the client. I already have one guess but I would like to confirm it

**Comment by Flupp** [comment]
Here we go: `curl https://…/_matrix/client/versions | jq | xclip`
```json
{
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0",
    "r0.6.0",
    "r0.6.1"
  ],
  "unstable_features": {
    "org.matrix.label_based_filtering": true,
    "org.matrix.e2e_cross_signing": true,
    "org.matrix.msc2432": true,
    "uk.half-shot.msc2666": true,
    "io.element.e2ee_forced.public": false,
    "io.element.e2ee_forced.private": false,
    "io.element.e2ee_forced.trusted_private": false,
    "org.matrix.msc3026.busy_presence": false,
    "org.matrix.msc2285": false
  }
}
```

**Comment by SimonBrandner** [comment]
Ok, so there are two things that are happening:

- Your homeserver is outdated: it seems it did support disabling read receipts (since you were able to disable them) but does not now; it should be updated since with the current stable Synapse release disabling read receipts is supported by default and does not require it being enabled manually in the server config
- Element Web isn't allowing you to change the setting since your homeserver does not support the feature

I would recommend suggesting a homeserver update to your admins and following https://github.com/vector-im/element-web/issues/23433 (a new issue I created to track my second point)
