### ISSUE TITLE
"Threads" > "should be usable for a conversation" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23438]
https://dashboard.cypress.io/projects/ppvnzg/runs/4627/test-results/e8ea65bc-11ad-4811-ac03-70f123ceeb1c

![Screenshot 2022-10-06 at 21-16-53 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/194446028-0a227157-5115-4acd-bf35-ab634e16ae64.png)

**Comment by gsouquet** [comment]
I believe this has been adressed by @t3chguy and is not flaky as it used to be
