### ISSUE TITLE
Element Installed via Flatpak Won't Search Encrypted Rooms

### ISSUE THREAD

**Issue by NoraCodes** [vector-im/element-web#23437]
### Steps to reproduce

1. I open Element, installed via Flatpak, on Fedora.
2. I open an encrypted room.
3. I click the circled-magnifying-glass icon in the top right hand corner.

#### What did you expect?

I expected to see a search bar and get messages as results when searching.

#### What happened instead?

Instead I see a search bar which doesn't give me results and the message "Use the [Desktop app](https://element.io/get-started) to search encrypted messages".

### Operating system

Fedora Linux

### Application version

"Element im.riot.Riot 1.11.8"

### How did you install the app?

Flatpak im.riot.Riot

### Homeserver

nora.codes. Synapse 1.66.0 Python3 on Ubuntu

### Will you send logs?

No

**Comment by NoraCodes** [comment]
I'll add that this is especially frustrating because there is no Fedora package for Element. I'd be happy to install it through another mechanism but that doesn't appear possible.

**Comment by t3chguy** [comment]
Please file issues specific to the flatpak with the community repo - https://github.com/flathub/im.riot.Riot/
