### ISSUE TITLE
Dead code analysis CI can continue with failure

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23430]
> Error: error Command "ts-prune" not found.

https://github.com/matrix-org/matrix-react-sdk/actions/runs/3191351498/jobs/5207555467

**Comment by t3chguy** [comment]
Looks like yarn/npm had issues installing deps https://github.com/matrix-org/matrix-react-sdk/actions/runs/3191351498/jobs/5207555467#step:4:262 - though that step really should've errored.

**Comment by turt2live** [comment]
updated title to match
