### ISSUE TITLE
Allow grouping contacts in folders

### ISSUE THREAD

**Issue by vdefives** [vector-im/element-web#23444]
#### What would you like to do?
Hello,

I would like to be able to group my contacts in Element, in different folders.

I would like to do so because, today, the only way to display my contacts is in a full list.

#### Why would you like to do it?
I would like to be able to create folders such as "Friends" "Family", "Work" in which I could place my contacts and find them more easily.

#### How would you like to achieve it?
I guess one way to achieve it would be to add it as an option when you click on the "..." near "people".
Here it could display "create new folder" and then we would be able to drag and drop people in those folders

### Additional context

Thank you for your work on this marvelous tool and I hope you will take interest in this feature request :)

**Comment by t3chguy** [comment]
You can do this already

<img width="182" alt="image" src="https://user-images.githubusercontent.com/2403652/194580355-63d6602f-c733-4f4c-9d4f-0e91b5bfd54d.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/2403652/194580390-39460cf0-57c2-481c-b1d4-15d6a999456e.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/2403652/194580421-9dd1bb66-5ce6-46ca-8857-cd276c3a03de.png">

Then choose `Just Me` and add all the rooms you wish to group into it
