### ISSUE TITLE
Forward dialog has no video controls when forwarding videos

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23459]
### Steps to reproduce

1. Send a video into a room
2. Menu -> Forward
3. Try to pause the thing as it plays in the dialog

#### What did you expect?

For the video to not be playing or to be pausable.

#### What happened instead?

It was playing and could not be paused. I think it might have been playing because of autoplay gifs & videos being enabled on my account? Either way, would expect it to *not* autoplay in this case or at least be something which can be paused.

### Operating system

Windows 10

### Application version

Nightly (2022-10-11)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is due to the `pointer-events: none;` - we should probably inhibit auto-play instead of reverting that
