### ISSUE TITLE
Updating to 1.11.9 broke notifications

### ISSUE THREAD

**Issue by valynor** [vector-im/element-web#23456]
### Steps to reproduce

Just updated element-web to 1.11.9, immediately noticed desktop notifications and sounds not working anymore. 
Did several clear cache & reloads, no change.

Went to settings and  I switched OFF notifs for this device + desktop notifs for this session and turned them ON again. 
Only now they work (again). 

### Outcome

see above

### Operating system

macOS 12.6

### Browser information

Brave Version 1.44.108 Chromium: 106.0.5249.103 (Official Build) (arm64)

### URL for webapp

https://app.element.io/

### Application version

1.11.9

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Originally filed as part of https://github.com/vector-im/element-web/issues/23384

> https://github.com/vector-im/element-web/issues/23384
