### ISSUE TITLE
support mouseless operation

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2346]
specifically clearing RM on keyboard as well as on mouse activity

**Comment by Palid** [comment]
Need to figure out what still needs proper keyboard support.

**Comment by hex-m** [comment]
Most of the discussion seems to happen in https://github.com/vector-im/element-web/issues/3232.

**Comment by kittykat** [comment]
Closing as I appear to be able to trigger RM clearing with keyboard, please reopen with more details if there is still an outstanding issue.
