### ISSUE TITLE
"request failed: CORS request rejected" when attempting to send an e-mail

### ISSUE THREAD

**Issue by psychofaktory** [vector-im/element-web#23461]
### Steps to reproduce

When doing operations that require emailing, I always get the message "request failed: CORS request rejected:"

When trying to register a new Matrix account I get the message "request failed: CORS request rejected: https://<matrixdomain.tld>/_matrix/client/r0/register/email/requestToken".

When trying to add an email address to an existing profile I get the message "request failed: CORS request rejected: https://<matrixdomain.tld>//_matrix/client/r0/account/3pid/email/requestToken"

The environmental conditions are as follows:
- Docker Element Web: vectorim/element-web:latest
- Docker Matrix Server: matrixdotorg/synapse
- Docker Identitiy server: ma1uta/ma1sd
- Reverse-Proxy: nginx on OPNsense 22.7.5
- Mail-Server: Power Mail-In-A-Box v56.5

The email parameters stored in homeserver.yaml and ma1sd.yaml are correct and work in other applications.

Attached are:

- the configuration file of synapse (homeserver.yaml)
- the configuration file of ma1sd (ma1sd.yaml)
- the configuration file of element-web (config.json)
- the nginx configuration generated by OPNsense (nginx.conf)

[configfiles.zip](https://github.com/vector-im/element-web/files/9759111/configfiles.zip)

#### What did you expect?
The e-mail is sent without errors

#### What happened instead?
Instead, the described error message appears

### Browser information

tested from Firefox-ESR 102.3.0 and Microsoft Edge 106.0.1370.34

### Application version

Element version 1.11.8; olm version 3.2.12

### Homeserver

Synapse 1.68.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
You would need to look into your logs to uncover the underlying error under the CORS, be it missing ACAO headers or a timeout. Sending in-app logs won't help given that the browser obfuscates CORS errors, you would need to look at your browser's network tab and reproduce the issue.
