### ISSUE TITLE
Crash when sharing screen

### ISSUE THREAD

**Issue by Grant12311** [vector-im/element-web#23463]
### Steps to reproduce

1. Start a voice call
2. Share you screen
3. Element crashes

#### What did you expect?
That Element would share my screen
#### What happened instead?
Element crashed

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Grant12311** [comment]
It might be worth noting that I'm running Wayland.

**Comment by t3chguy** [comment]
Please report issues for the community flatpak to their repo - https://github.com/flathub/im.riot.Riot/ - if you encounter this issue on the official packages then please let us know and we can reopen.
