### ISSUE TITLE
Crashing when in background

### ISSUE THREAD

**Issue by Grant12311** [vector-im/element-web#23462]
### Steps to reproduce

1. Open Element
2. Close Element but leave it open in the system tray
3. Wait as little as a minute or so for it to silently crash and vanish from the system tray

#### What did you expect?
For Element to remain open in the background
#### What happened instead?
It silently crashed

### Operating system

Ubuntu 22.04

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please report issues specific to the flatpak in https://github.com/flathub/im.riot.Riot/ - if you can reproduce on the official releases then please let us know and we can reopen.

**Comment by Grant12311** [comment]
@t3chguy Ah sorry, I didn't realize the flatpak version was community maintained and not quite official. It does actually appear that switching to the deb package fixed both this and my other opened issue.
