### ISSUE TITLE
Local rooms have wrong default avatar colour until the room is created properly

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23476]
### Steps to reproduce

1. Find someone you haven't messaged yet who also doesn't have an avatar set
2. Click "Message" to start a local room with them
3. Note the avatar colour.
4. Actually send a message to create the room.
5. Note the avatar colour.

#### What did you expect?

Consistency.

#### What happened instead?

Before creation:
![image](https://user-images.githubusercontent.com/1190097/195530949-a5c095a8-8821-4207-9036-98edb76ffc72.png)

After creation:
![image](https://user-images.githubusercontent.com/1190097/195530974-30ca8e3a-0ea2-4d2f-81af-6875c0c4adb3.png)

Purple is the correct colour for this user.

### Operating system

Windows 10

### Application version

Nightly (2022-10-12)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
For 1-1 rooms this is solvable
For 1-N DM rooms this isn't, as there the colour is based on the room ID which is unknown until the room is created

**Comment by turt2live** [comment]
Multiparty DMs changing avatar colour is probably fine, but for single user DMs it's a bit surprising.
