### ISSUE TITLE
Thread should disappear if someone starts a thread and then redacts their message

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#23483]
### Steps to reproduce

User 1:
1. Send a message in a room (not in a thread)

User 2:
1. Reply to User 1's message using a thread
1. Redact the message you just sent

#### What did you expect?
The thread should disappear because there are no messages in the thread

#### What happened instead?
The thread remains visible.

This makes it look like the original message is replying to itself since it is the only message visible in the thread.
<img width="1369" src="https://user-images.githubusercontent.com/5855073/195662311-0a972c03-32b7-445e-b146-869f2a645372.png">

### Application version

1.11.10

### Will you send logs?

No

**Comment by t3chguy** [comment]
This used to work, this is a regression

**Comment by aaronraimist** [comment]
After clearing cache it does go away

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23004
