### ISSUE TITLE
`login/login.spec.ts` „Login → logout → should go to login page on logout“ failing

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23486]
Sample run https://dashboard.cypress.io/projects/ppvnzg/runs/5010/test-results/ac8da009-4f8d-4ec1-97db-57e5e008ffe2

Looks like the „Updating Element“ dialog is in the way.

Message

```
Timed out retrying after 10050ms: cy.click() failed because this element:

<div title="User menu" aria-label="User menu" aria-haspopup="true" aria-expanded="false" role="button" tabindex="0" class="mx_AccessibleButton">...</div>

is being covered by another element:

<div class="mx_Dialog_background"></div>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
```

Screenshot

![image](https://user-images.githubusercontent.com/6216686/195724093-e032493c-b187-4351-b9d7-6b85aefb9b68.png)

**Comment by duxovni** [comment]
(My understanding of the triage process is that Defect is for bugs in the app, and bugs in tests are Task; happy to be corrected if that's not how we want to classify things)
