### ISSUE TITLE
Message input field eats Ctrl-Shift-P (open private window) in Firefox

### ISSUE THREAD

**Issue by ilmari** [vector-im/element-web#23495]
### Steps to reproduce

1. Have the message input field focused
2. Press `Ctrl`+`Shift`+`P`

#### What did you expect?

A new private browsing window to open, seeing as `Ctrl`+`Shift`+`P` is not listed as an Element shortcut in the `Ctrl`+`/` popup.

#### What happened instead?

Nothing

### Operating system

Debian Linux 11 (Bullseye)

### Browser information

Firefox 102.3.0esr

### URL for webapp

app.element.io

### Application version

Element version: 1.11.10 Olm version: 3.2.12, 

### Homeserver

Synapse 1.66.0

### Will you send logs?

No

**Comment by robertlong** [comment]
Currently on macOS and I can't repro here. Needs testing on Windows and Linux.

**Comment by MadLittleMods** [comment]
I can't reproduce on Windows with Firefox 105.0.3. It brings up a private browsing window as expected.

Also can't reproduce in Chrome on Windows (not that the shortcut means the same thing anyways). Opens the print dialog and with devtools open, opens the command pallet in devtools.

**Comment by robintown** [comment]
I can't reproduce this on NixOS on Firefox 105.0.1 either. @ilmari Are you aware of any other variables such as browser extensions that could be interfering with the shortcut?

**Comment by ilmari** [comment]
It turns out the culprit is `/org/gnome/desktop/interface/gtk-key-theme = 'Emacs'`, which makes `Ctrl`+`P` go to the previous line, and `Ctrl`+`Shift`+`P` select text while moving. I just hadn't noticed because there was no text in the box when I tried previously.
It also affects other text entry boxes, like this one I'm typing into now, so not an Element issue. Sorry for the noise.
