### ISSUE TITLE
No verification request popup (dialog) on web when requesting verification from Android app

### ISSUE THREAD

**Issue by amitkma** [vector-im/element-web#23492]
### Steps to reproduce

1. Login with your account on [chat.element.io](https://chat.element.io)
2. Now login into Element Android app.
3. There is popup shown on Element web, dismiss that one by clicking on 'Later'
4. Now, start a verification from the Android app.
5. There is no further request popup in Element web, although there is a verification request received in console.

#### What did you expect?

There should be a verification popup in Element web.

#### What happened instead?

There is no verification popup.

### Operating system

macOS 12.6

### Browser information

Google Chrome Version 105.0.5195.125 \(Official Build\) \(arm64\)

### URL for webapp

chat.element.io

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

No

**Comment by amitkma** [comment]
FYI @BillCarsonFr 

I found this happens once you dismiss the popup for the first time as soon as you login on new device.

**Comment by richvdh** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/21021, though the symptoms seem different.

Given this only seems to have been reported once, over a year ago, I'm inclined to imagine it has now been fixed. If anyone has repro steps, please reopen, along with clear description of the steps and **rageshake logs**
