### ISSUE TITLE
Cypress flake: Failed to execute transaction on IDBDatabase - closing

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23496]
https://dashboard.cypress.io/projects/ppvnzg/runs/5106/test-results/0c1c3e8d-0b5e-4476-8be8-153689521039

![Screenshot 2022-10-14 at 13-05-28 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/195902880-6e77d69d-3ce0-4293-9361-c41dce854ba3.png)

**Comment by robintown** [comment]
https://dashboard.cypress.io/projects/ppvnzg/runs/5108/test-results/58586f93-fbeb-4807-81c4-7ef7cb88fa75 shows *even more* ways that it can flake :neutral_face:

**Comment by t3chguy** [comment]
This flake isn't specific to this test

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
