### ISSUE TITLE
`integration-manager/kick.spec.ts` → „Integration Manager: Kick > should kick the target“ flaky

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23516]
Looks like that events are collapsed.

Sample run

https://dashboard.cypress.io/projects/ppvnzg/runs/5254/test-results/f9fe2af6-f816-4400-b2a6-a59dba78571d

Message

```
Timed out retrying after 10000ms: Expected to find content: 'Alice removed Bob: Goodbye' within the selector: '.mx_EventTile_line' but never did.

// Check for the event message (or lack thereof)
  90 |     cy.contains(".mx_EventTile_line", `${USER_DISPLAY_NAME} removed ${BOT_DISPLAY_NAME}: ${KICK_REASON}`)
> 91 |         .should(shouldExist ? "exist" : "not.exist");
     |          ^
  92 | }
  93 | 
  94 | describe("Integration Manager: Kick", () => {
```

Screenshot

![image](https://user-images.githubusercontent.com/6216686/196402265-e2ecbc1a-68c3-4b18-b084-a49f222a61e7.png)

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/23292

**Comment by t3chguy** [comment]
https://dashboard.cypress.io/projects/ppvnzg/runs/5831/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github

**Comment by turt2live** [comment]
I haven't been able to get a stable environment going to fix this, but also it's not super flaky at the moment - returning to backlog.

**Comment by turt2live** [comment]
we don't believe this test is flaky enough to have the issue open - if people encounter this flaky test, please open a new issue or reopen this one.
