### ISSUE TITLE
Importance ordering of the room list is broken

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23554]
To set up the conditions for this:
1. Have 3+ rooms in Favourites
2. Have 3+ rooms untagged (under "rooms")
3. Have "Show rooms with unread messages first" and "Sort by activity" enabled for both sublists
4. In each section, have 3 rooms that are unread

To reproduce from those conditions:
1. Select the middle room of your Rooms
2. Select any room in your favourites
3. Note that the middle room from Rooms did not move to the bottom like it should have

Also reproduced by opening Ctrl+K dialog and switching to a room in that space.

**This does not appear to be an issue on staging, however I have not tested extensively.**

**Comment by turt2live** [comment]
release blocker for develop->RC, not active cycle at this very moment.

**Comment by turt2live** [comment]
also appears to be affecting notifications in several rooms, and I'm starting to be able to reproduce it without switching between tags (indicating higher order corruption).

**Comment by turt2live** [comment]
I haven't been able to reproduce this locally, and restarting Nightly appears to have resolved the issue (at least for now). Logs do not show any particular red flags either.

Testing on Synapse 1.68 vs 1.69 also did not reveal anything wrong, and the only flag differences would be disabled anyways:
![image](https://user-images.githubusercontent.com/1190097/196794835-565e5b99-c3f1-4e44-89d9-6f8155e1f30a.png)

Bisecting locally also did not reveal any particular issues. This might have just been random corruption on my side?

**Comment by turt2live** [comment]
and of course Nightly is broken again :(

**Comment by kegsay** [comment]
Possibly related: https://github.com/matrix-org/matrix-react-sdk/pull/9438 as it means we send notification snapshots less frequently now.
