### ISSUE TITLE
title bar and timeline default avatar after room creation don't match

### ISSUE THREAD

**Issue by lub** [vector-im/element-web#23551]
### Steps to reproduce

1. Create a new room
2. Wait until it finished loading

#### What did you expect?
That the default avatars in the title bar and timeline match, like they do after switching away from the room and opening it again:
![image](https://user-images.githubusercontent.com/1029578/196708578-c275b51c-eb5d-42d4-9a7a-ea30254647b2.png)

#### What happened instead?
They don't match:
![image](https://user-images.githubusercontent.com/1029578/196708477-5bb4d763-6159-4db4-b956-5da252ce0e44.png)

### Operating system

Windows

### Browser information

Firefox 105.0.3

### URL for webapp

app.element.io

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### Homeserver

imninja.net

### Will you send logs?

Yes

**Comment by lub** [comment]
Not sure if these two could be related:
https://github.com/vector-im/element-web/issues/22590
https://github.com/vector-im/element-web/issues/23476

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22590
