### ISSUE TITLE
Re-request encryption keys prompt remains after message is decrypted

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#23550]
### Steps to reproduce

1. Receive a message where there is a delay receiving the encryptions keys, so an error is displayed
2. Wait, and see the message get decrypted
3. Note that the "Re-request encryption keys" text is still there.

![image](https://user-images.githubusercontent.com/76812/196666920-94b04e69-bcc2-460f-8df1-aab3d813dee4.png)

#### What did you expect?

I expected this prompt to disappear because the message was decrypted, and it is now just confusing.

#### What happened instead?

It stayed around.

### Operating system

Ubuntu 22.04

### Browser information

Firefox 105.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 921deab6ad14-react-e0ab0ac5c999-js-17e16b9b1a4d Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by buffless-matt** [comment]
I'm experiencing the same thing, but with a mixture of horizontal (as shown in Andy's screenshot) and vertical text:

![image](https://user-images.githubusercontent.com/96466754/196820770-2441e5e2-8b17-4114-8cdd-5ec3be372614.png)

## Operating system

Ubuntu 20.04

## Application version

Element desktop version: 1.11.10

**Comment by andybalaam** [comment]
I am seeing this regularly now. I have several instances in a single room.

**Comment by andybalaam** [comment]
@uhoreg I bumped this up to O-Frequent - please change it if you disagree.

**Comment by BillCarsonFr** [comment]
Step to reprocude

1) Send a message
2) Edit it once
3) Edit it again

4) Do a clear cache (initial sync)

=> Now you have the problem

**Comment by BillCarsonFr** [comment]
Before & after initial sync event:

## Before (from timeline view source)
```
{
  "type": "m.room.encrypted",
  "sender": "@alice:localhost:8480",
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "sender_key": "hGKn1DTWmQF6fkJY4uUUrlLBubyt9DHyQkbLSeuE+xU",
    "ciphertext": "AwgAEqAB+c+86+ViMDxn17VY+9W3mJPEEOwsvCgtN/kglMLAuvcak8ldhU+lNb6PqT1/foNfRpBlMb7/GbQEJ1NkbDGKyj+9N6nl/o4J28hSOavTJZcuRq74BA3Lb4mi5ntJs7l5cKxhBj/sTUSzMcxpM9NsxtZNL5sI/emObWbD2+nfCg2jytlKZqM+Cesj2pgDrSu9Vqb8+VbX5OTrDr4KzlVOPpA2rGU3ufbBj8M8uUNlUbzRWChhNEQ2rnjKDPnrzQO8wTYVt7uq+kr9SZzwb5xWNyOcXFH0c1Ec6npPbvdb3jf50AjQTV5GBg",
    "session_id": "KQrjVvG9p7kLCThUTWRIxk66Znr9isRjSTxwLOc99c0",
    "device_id": "QCBCOIBBFJ"
  },
  "origin_server_ts": 1666343360659,
  "unsigned": {
    "age": 74,
    "transaction_id": "m1666343360614.4"
  },
  "event_id": "$b51iVve9PasAMiwPAS697t2AtcKjcpeqfRZhbo28dmU",
  "room_id": "!tWvKYbGyhxZIROGqGa:localhost:8480"
}
```

## After (from the sync request)

```
{
  "type": "m.room.encrypted",
  "sender": "@alice:localhost:8480",
  "content": {},
  "origin_server_ts": 1666343360659,
  "unsigned": {
    "age": 31245,
    "transaction_id": "m1666343360614.4",
    "m.relations": {
      "m.replace": {
        "event_id": "$k9aKiHCMFZ-yxvfxfIwEIT5o4kR3ul5CdEVUV9LcJ0w",
        "origin_server_ts": 1666343381454,
        "sender": "@alice:localhost:8480"
      }
    }
  },
  "event_id": "$b51iVve9PasAMiwPAS697t2AtcKjcpeqfRZhbo28dmU"
}

**Comment by BillCarsonFr** [comment]
Root cause https://github.com/matrix-org/synapse/issues/14252
