### ISSUE TITLE
Brandnew installation on Ubuntu 20.04 with NGINX and received can not reach homeserver

### ISSUE THREAD

**Issue by GentleRV** [vector-im/element-web#23557]
### Steps to reproduce

1. After installing synapse and tested with the federation tester (with good results) the installation with NGINX is performed
2. Downloaded the web package version V1.11.10 
3. Created the element directory under /var/www/html
4. Copied all the files in the /var/www/html/element directory
5. Copied the config.sample.json to config.json and adjusted the homeserver variable to my need
6. Created the NGINX configuration file with this contents:
server {
    listen 80;
	listen [::]:80;
    server_name homeserver;
    return 301 https://$host:446$request_uri;
}

server {
    listen 446 ssl;
    listen [::]:446 ssl;
    server_name homeserver;

    # For the federation port
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;

    ssl_certificate /etc/letsencrypt/live/homeserver/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/homeserver/privkey.pem; # managed by Certbot
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE
    	
    root /var/www/html/element;
    index index.html;

    location ~ ^(/_matrix|/_synapse/client) {
        # note: do not add a path (even a single /) after the port in `proxy_pass`,
        # otherwise nginx will canonicalise the URI and cause signature verification
        # errors.
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
		add_header X-Frame-Options SAMEORIGIN;
		add_header X-Content-Type-Options nosniff;
		add_header X-XSS-Protection "1; mode=block";
		add_header Content-Security-Policy "frame-ancestors 'none'";

    # Nginx by default only allows file uploads up to 1M in size
    # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
    client_max_body_size 50M;
	}
    location / {
        try_files $uri $uri/ =404;
    }
}
7. Restarted NGINX
8. After testing with federation everything looks fine
9. Entering the URL in firefox give me the login screen, click the login button produced the error:
10. There was a problem communicating with the homeserver, please try again later.
11. For now I give up

#### What did you expect?
A good working server who can be used to chat and amuse people

#### What happened instead?
Got frustrated after many hours to get things working

### Operating system

Ubuntu 20.04-5 LTS

### Browser information

Firefox version 105

### URL for webapp

from github

### Application version

version 1.11.10

### Homeserver

own hosted server

### Will you send logs?

No

**Comment by dbkr** [comment]
This isn't the right place to get help setting up your instances - try one of the matrix rooms, although also - port 446 seems wrong?

**Comment by GentleRV** [comment]
Port 446 is not wrong as my NGINX version 1.18 is reporting port in use when use 443.
For this I want to update NGING to version 1.22 in the hope the port issue is solved
My feeling now is: why should I report issues and hope to get help instead of short answers thet I need to find other places to hget helpe and you just closed the issue.
I still have the problem and put a lot of work generating the needed documentation to GET HELP

**Comment by GentleRV** [comment]
reaching problems where solved with reinstalling NGINX and the use of port 443 who started to work.
I used this script:
wget https://raw.githubusercontent.com/angristan/nginx-autoinstall/master/nginx-autoinstall.sh
chmod +x nginx-autoinstall.sh
./nginx-autoinstall.sh
