### ISSUE TITLE
Joining a room caused error

### ISSUE THREAD

**Issue by anka-213** [vector-im/element-web#23561]
### Steps to reproduce

1. Search for a room in an organization (or whatever they're called)
2. Click on the join button

#### What did you expect?
Joining the room
#### What happened instead?
I got a "Something went wrong!" message

### Operating system

macOS

### Application version

1.11.10

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22752
