### ISSUE TITLE
Unable to verify device

### ISSUE THREAD

**Issue by dwagener** [vector-im/element-web#23578]
### Steps to reproduce

1. On login, get the popup "You have unverified logins"
2. Click "Review"
3. Click "Verify“ for „This Device"
4. Click "Verify with Security Key"
5. Click "Upload"
6. Select key
7. Click "Continue"

#### What did you expect?

Successful verification

#### What happened instead?

I found myself back at the "Verify this session"-screen from step 4.

Log gives me "Error: Key type master from getCrossSigningKey callback did not match"

Except for the log I see the same on the WebApp and the Element AndroidApp Errors with "Failed to import keys"

### Operating system

Linux

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### How did you install the app?

gentoo portage, package net-im/element-desktop-bin

### Homeserver

synapse 1.69.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please update to `1.11.10` and attempt to reproduce.

**Comment by dwagener** [comment]
Reproducible with:
Element version: 1.11.10
Olm version: 3.2.12

According logs have been uploaded

**Comment by dwagener** [comment]
On Mon, 2022-10-24 at 03:32 -0700, Michael Telatynski wrote:
> Please update to `1.11.10` and attempt to reproduce.
> 

Done. No Change.

Same with 1.11.13: No change.

**Comment by dwagener** [comment]
Also present in 1.11.14

**Comment by dwagener** [comment]
Issue persists with
> Element version: 1.11.15
> Olm version: 3.2.12

**Comment by dwagener** [comment]
On Mon, 2022-10-24 at 03:32 -0700, Michael Telatynski wrote:
> Please update to `1.11.10` and attempt to reproduce.
> 

Issue persists with 1.11.20

-- 
kernel concepts GmbH		Daniel Wagener
Hauptstraße 16			***@***.***
D-57074 Siegen			Tel: +49 271 771091 18
http://www.kernelconcepts.de/ 	Fax: +49 271 338857 29
Geschäftsführer: Ole Reinhardt
HR Siegen, HR B 9613

**Comment by kylrth** [comment]
I am also seeing this, when asked for the security passphrase or security key when cross-signing another device. 1.11.24

**Comment by dwagener** [comment]
Still present in 

Element version: 1.11.29
Olm version: 3.2.12

FWIW, I was able to pull some Log output:

> [2300445:0419/082440.774910:INFO:CONSOLE(107135)] "[object Object]", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082440.774935:INFO:CONSOLE(107135)] "Cross-signing private keys not found locally, but they are available in secret storage, reading storage and caching locally", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082440.774954:INFO:CONSOLE(107135)] "downloadKeys: already have all necessary keys", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082440.775851:INFO:CONSOLE(107135)] "Got new master public key ***", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082440.775873:INFO:CONSOLE(107135)] "Attempting to retrieve cross-signing master private key", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082440.776784:INFO:CONSOLE(107135)] "Starting load of AsyncWrapper for modal", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082443.246566:INFO:CONSOLE(107135)] "Error: Key type master from getCrossSigningKey callback did not match", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082443.246590:INFO:CONSOLE(107135)] "Error: Key type master from getCrossSigningKey callback did not match", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)
> [2300445:0419/082445.277123:INFO:CONSOLE(107135)] "Bootstrapping cross-signing", source: vector://vector/webapp/bundles/a5e4405ebc0b066c121a/init.js (107135)

I also did some digging and found #13542 and  #22893, which bear at least some resemblance.



This issue (or the underlying cause which I cannot identify beyond „element has some issue with my keys“) keeps me from having any verified session and accessing old messages from past sessions. It also prevents all other sessions from being properly cross signed.
After now half a year I will reset that account to regain a verified session and calm down the contacts which are complaining they could not trust me anymore.
So I will not be able to reproduce and verify this with new releases anymore.
