### ISSUE TITLE
Top menu item in context menus are highlighted

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#23582]
### Steps to reproduce

This seems to be a regression in a recent version of Element Web.

[Screencast from 10-24-2022 04:48:32 PM.webm](https://user-images.githubusercontent.com/1342360/197570911-a172765a-e405-4393-b3f5-489307f244d5.webm)

1. Right click a message or room
2. The top-most entry in the context menu's items will be pre-highlighted
3. It shouldn't be as I'm not hovering over it

Also occurs in the menu that appears when clicking your user avatar:
![image](https://user-images.githubusercontent.com/1342360/197570689-539c289c-9a24-4e74-9428-af1e82bc434d.png)

#### What did you expect?

For no items to be highlighted if my mouse isn't over the context menu.

#### What happened instead?

The top entry is always highlighted until I use tab to switch to another entry.

### Operating system

Arch Linux

### Application version

Element version: 2022102401, Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
That'll be because the accessibility roving tab-index will be selecting it probably

**Comment by kerryarchibald** [comment]
Regressed (?) by https://github.com/matrix-org/matrix-react-sdk/pull/9386/files#diff-b00e15cbc8a0e560ba2e326b52e604dd9ceb1bf7114370e591611ea023997243

**Comment by kerryarchibald** [comment]
Possible it should use outline focus styling rather than extending the hover style
<img width="205" alt="Screenshot 2022-10-24 at 18 43 50" src="https://user-images.githubusercontent.com/3055605/197581707-b0ffb22d-896b-4d14-b68e-6e8eb086f2d5.png">

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/197583179-516d846d-4d84-48fa-bf98-d1e5acb7058d.png)

Before the change ^
