### ISSUE TITLE
Bad UTDs (corrupted channel) from me->johannes

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#23581]
### Steps to reproduce

I sent Johannes a bunch of msgs on Sat in 1:1; he couldn't them on Mon due to corrupted olm channel. Keyshare reqs didn't seem to fix it.

### Outcome

E2EE that works.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org -> element.io

### Will you send logs?

Yes

**Comment by poljar** [comment]
The logs show megolm decryption failures with a description that the Olm channel was corrupted.

Sadly there isn't any mention of the room key in the sender logs, no way to check if the room key was sent out.

There are no Olm decryption failures in the recipient logs. So no way to see when the room key should have been received or why the Olm message failed decryption. The recipient does have a suspiciously large amount of Olm sessions with the problematic device `Nhu0+B3JJNHr3abToRm0rYjXne20De67kH1RaNZBEAM`.

The later log lines show that communication over Olm healed itself.

Sadly nothing to go by here to further investigate.
