### ISSUE TITLE
Element Desktop crashes on start

### ISSUE THREAD

**Issue by picsel2** [vector-im/element-web#23587]
### Steps to reproduce

1. Start Element

#### What did you expect?

The app to start properly.

#### What happened instead?

The app crashes immediately.

### Operating system

Fedora 36

### Application version

flatpak reports 1.11.10

### How did you install the app?

Flathub

### Homeserver

matrix.grabel.de

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report this to the maintainers of the community flatpak package: https://github.com/flathub/im.riot.Riot/
