### ISSUE TITLE
Received "[403] Auth events could not be found", server forbidden from federating?

### ISSUE THREAD

**Issue by jivanpal** [vector-im/element-web#23594]
### Steps to reproduce

1. Attempt to join `#users:ansible.com`.
2. Wait for a while whilst my homeserver attempts to join the room.

#### What did you expect?

The room join should complete normally.

#### What happened instead?

I eventually receive the following error message:

> MatrixError: [403] Auth events could not be found (https://matrix.opaline.uk/_matrix/client/r0/join/%23users%3Aansible.com?server_name=ansible.com)

I'm not sure whether I should have filed this here or against Synapse, but I have also checked my homeserver's logs, which indicate that it is receiving 403 responses from many, if not all,  other homeservers, all of this form (but of course, with various peers):

> ```
> synpse.http.matrixfederationclient - 629 - INFO - federation_transaction_transmission_loop-6488491 - {PUT-O-5076145} [matrix.am] Got response headers: 403 Forbidden
> synapse.federation.sender.transaction_manager - 171 - INFO - federation_transaction_transmission_loop-6488491 - TX [matrix.am] {1666055548064} got 403 response
> synapse.federation.sender.per_destination_queue - 360 - WARNING - federation_transaction_transmission_loop-6488491 - TX [matrix.am] Received 403 response to transaction: 403: Forbidden
> ```

### Operating system

macOS 10.15.7

### Application version

Element Desktop 1.11.11

### How did you install the app?

Homebrew (`brew`), which installs from <https://packages.riot.im/desktop/install/macos/Element.dmg>

### Homeserver

opaline.uk (my own homeserver), running Synapse 1.69.0

### Will you send logs?

Yes

**Comment by jivanpal** [comment]
(Logs submitted via app, referencing this issue URL)

**Comment by t3chguy** [comment]
This is an issue with Synapse, please open an issue in https://github.com/matrix-org/synapse
