### ISSUE TITLE
Icons next to new WYSIWYG composer misaligned

### ISSUE THREAD

**Issue by moritzdietz** [vector-im/element-web#23593]
#### What would you like to do?
Fix the alignment of the icons in the new WYSIWYG composer to be centered.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/7935536/197861993-e31b955c-57a6-4e54-99af-57cd773fe766.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/7935536/197862097-3e51fb98-d32e-47c9-9974-5a739641fb9d.png">

#### Why would you like to do it?
Because they are not centered and it would look better when they are centered.

#### How would you like to achieve it?
N/A

**Comment by weeman1337** [comment]
Also misaligned with the voice recorder

![image](https://user-images.githubusercontent.com/6216686/198062574-ca5b0cd3-1499-4654-b247-f6d088aee0ba.png)

**Comment by florianduros** [comment]
In the last PR https://github.com/matrix-org/matrix-react-sdk/pull/9533 we worked on the design of the rich text composer. *Normally*, all icons should be aligned correctly.
