### ISSUE TITLE
Upload Failed "The file 'filename.png' failed to upload.

### ISSUE THREAD

**Issue by johndball** [vector-im/element-web#23605]
### Steps to reproduce

1. In any room under Element version 1.11.11 Windows x64, .png and .jpg files fail to upload _if using the in-place upgrade to version 1.11.11_ (see 3f). Uploads were working without issue prior to the update to 1.11.11. 
2. Open a room - click the paperclip button - attach a .png or .jpg file - click upload. Received error message.
3. Uploads work from mobile, not from Desktop 1.11.11. 
3b - restarted server - failed message persists
3c- restarted desktop (myself and a half dozen users) - failed message persists
3d - logged out of Desktop app and logged back in - failed message persists
3e - cleared cache - failed message persists
3f - reinstalled Element (no uninstall) from https://element.io/get-started#download Windows x64 and uploads work one time. In place overwrite of the existing install and no error message. A second upload triggers the error message again. A reinstall of Element allows for another upload one time then errors out again.

![Capture](https://user-images.githubusercontent.com/4836923/198015813-592ddcdc-8545-4b0d-ad04-06d4dbc73be3.PNG)

#### What did you expect?
-Expectations - uploads to work post upgrade

#### What happened instead?
-Outcomes - uploads failed to work when upgrading using the in-app upgrade to version 1.11.11

### Operating system

Windows 10 21H2 x64

### Application version

1.11.11

### How did you install the app?

Auto upgrade notification. Reinstalled using https://element.io/get-started#download

### Homeserver

Synapse 1.69.0

### Will you send logs?

No

**Comment by turt2live** [comment]
I'm not able to reproduce this - are you able to submit logs from Settings -> Help -> Submit Debug Logs please?

**Comment by johndball** [comment]
> I'm not able to reproduce this - are you able to submit logs from Settings -> Help -> Submit Debug Logs please?

I can't have usernames, IDs, and aliases of rooms submitted and that is one of the warnings for debug logs. If I can get the logs and purge that information, I'd be happy to share. 
FYI - Element updated to 1.11.12 and same error. 


![Capture](https://user-images.githubusercontent.com/4836923/198098456-a59b3b45-fb76-4783-89c1-855d8f5c7dd9.PNG)

**Comment by t3chguy** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/2403652/198099816-5d0ed2de-6362-4631-ac31-4fe4259419a4.png">

@johndball try the Download logs button.

**Comment by t3chguy** [comment]
@johndball unfortunately we don't go through logs by hand submitted like this, we only go through logs submitted through the rageshake server which get parsed & indexed. I suggest you go through them yourself to share the pertinent entries.

**Comment by johndball** [comment]
> @johndball unfortunately we don't go through logs by hand submitted like this, we only go through logs submitted through the rageshake server which get parsed & indexed. I suggest you go through them yourself to share the pertinent entries.

Okay, sorry, a little confused here. The issue is that I can't submit them without redactions, which I did following the comment above about downloading the logs and redacting the information. But now I can't submit the redacted logs? 

So... how can I submit them with redactions? Or is that just not an option at this point?

**Comment by t3chguy** [comment]
@johndball instead of redacting the whole thing, just find the pertinent error, redact if needed, and share that here in the issue, not in a zip.

**Comment by johndball** [comment]
> @johndball instead of redacting the whole thing, just find the pertinent error, redact if needed, and share that here in the issue, not in a zip.

Tried to upload again, got the error, immediately dumped. These are the entries immediately preceding the dump of the logs which I did as soon as the error displayed.

```
	Line 2184: 2022-10-26T18:33:02.541Z I Starting load of AsyncWrapper for modal
	Line 2185: 2022-10-26T18:33:02.555Z I Returning cached capabilities
	Line 2186: 2022-10-26T18:33:02.707Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2190: 2022-10-26T18:33:03.064Z W Unable to reach identity server at https://vector.im to check for 3PIDs bindings in Settings
	Line 2191: 2022-10-26T18:33:03.064Z W MatrixError: [500] Internal Server Error (https://vector.im/_matrix/identity/v2/account/register)
	Line 2199: 2022-10-26T18:33:03.192Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2203: 2022-10-26T18:33:03.218Z W Unable to reach identity server at https://vector.im to check for terms in Settings
	Line 2204: 2022-10-26T18:33:03.218Z W MatrixError: [500] Internal Server Error (https://vector.im/_matrix/identity/v2/account/register)
	Line 2211: 2022-10-26T18:33:03.707Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2215: 2022-10-26T18:33:04.188Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2219: 2022-10-26T18:33:04.688Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2223: 2022-10-26T18:33:05.137Z I Starting load of AsyncWrapper for modal
	Line 2224: 2022-10-26T18:33:05.144Z I TimelinePanel(Room): Debugging info for !zWcCmRMzDTsSblGMzc:coms.[redacted].com
	Line 2232: 2022-10-26T18:33:05.204Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2236: 2022-10-26T18:33:05.692Z E MatrixError: [404] Could not find event $WlGSaKlo79cUDji173OgLY3zSbQW3YENrlzO6hx5xDI (https://coms.[redacted].com/_matrix/client/r0/rooms/!zWcCmRMzDTsSblGMzc%3Acoms.[redacted].com/read_markers)
	Line 2240: 2022-10-26T18:33:06.131Z I Sending bug report.
```

**Comment by johndball** [comment]
I was able to figure this out by accident while hunting down a federation issue via Cloudflare. Looks like Cloudflare OWASP is knocking down the uploads. 

```
host: matrixserver.domain.com
path: /_matrix/media/r0/upload

Rule ID: OWASP Block (981176)
Rule message: Inbound Anomaly Score Exceeded
Rule group: OWASP Inbound Blocking

960901 · Invalid character in request | OWASP Protocol Violations | Log
960024 · Meta-Character Anomaly Detection Alert - Repetative Non-Word Characters | OWASP Generic Attacks | Log
959151 · PHP Injection Attack | OWASP Generic Attacks | Log
981231 · SQL Comment Sequence Detected | OWASP SQL Injection Attacks | Log
981318 · SQL Injection Attack: Common Injection Testing Detected | OWASP SQL Injection Attacks | Log
981319 · SQL Injection Attack: SQL Operator Detected | OWASP SQL Injection Attacks | Log
981244 · Detects basic SQL authentication bypass attempts 1/3 | OWASP SQL Injection Attacks | Log
981257 · Detects MySQL comment-/space-obfuscated injections and backtick termination | OWASP SQL Injection Attacks | Log
981245 · Detects basic SQL authentication bypass attempts 2/3 | OWASP SQL Injection Attacks | Log
981240 · Detects MySQL comments, conditions and ch(a)r injections | OWASP SQL Injection Attacks | Log
981242 · Detects classic SQL injection probings 1/2 | OWASP SQL Injection Attacks | Log
981243 · Detects classic SQL injection probings 2/2 | OWASP SQL Injection Attacks | Log
973300 · Possible XSS Attack Detected - HTML Tag Handler | OWASP XSS Attacks | Log
973335 · IE XSS Filters - Attack Detected | OWASP XSS Attacks | Log
973334 · IE XSS Filters - Attack Detected | OWASP XSS Attacks | Log
973333 · IE XSS Filters - Attack Detected | OWASP XSS Attacks | Log
973344 · IE XSS Filters - Attack Detected | OWASP XSS Attacks | Log
```

Cloudflare WAF bypass rules do not work. Had to create a page rule to bypass Cloudflare WAF using the following host:
`matrixserver.domain.com/_matrix/media/r*/upload`
