### ISSUE TITLE
Registration where server needs email validation results in 2 sessions being created

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23601]
### Steps to reproduce

1. Register a new account
2. See "Welcome" screen on landing

#### What did you expect?
I need to click the "Download apps" button before "Download Element" is marked as done

#### What happened instead?
See "Download Element" ticked as a done action

### Browser information

Chromium 106.0.5249.119 in private browsing mode

### URL for webapp

develop.element.io

### Application version

Element version: 2f49467152ac-react-b7ff56a7264f-js-9f2f08dfd3de Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/01a3150d447be995215265d67f6063d552814dd7

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8654
