### ISSUE TITLE
Formatting indicator does not work if selecting all text by mouse

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23614]
### Steps to reproduce

1. Enable new composer
2. Write some text
3. Select all by mouse
4. Press bold
5. Click somewhere in the bold text

#### What did you expect?

Bold indicator active

#### What happened instead?

Indicator inactive

![composer2](https://user-images.githubusercontent.com/6216686/198070099-7e5d1358-8589-419f-8d04-ca4210cb6db0.gif)

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 106.0.1 (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Element version: 12bde9a51421-react-7692533e18f1-js-dddc0aeccb32 Olm version: 3.2.12

### Will you send logs?

No

**Comment by andybalaam** [comment]
I'm pretty sure this is caused by the backwards-selection bug, so should be fixed when element-web picks up the next matrix-rich-text-editor release (0.5.0).

**Comment by florianduros** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/9573
