### ISSUE TITLE
Labs: emoji picker doesn't work with WYSIWYG editor

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23612]
### Steps to reproduce

1. Enable "Try out the rich text editor (plain text mode coming soon)" in labs
2. Refresh to apply changes
3. Click on the emoji picker and then on an emoji

#### What did you expect?
Emoji is inserted

#### What happened instead?
Nothing happens

### Browser information

Chromium 106.0.5249.119 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 3366ed1-react-51e69427f3d6-js-9f2f08dfd3de Olm version: 3.2.12

### Will you send logs?

No

**Comment by florianduros** [comment]
Ongoing implementation:
* Rich text mode: https://github.com/matrix-org/matrix-react-sdk/pull/9661 
* Plain text mode: https://github.com/matrix-org/matrix-react-sdk/pull/9727

**Comment by florianduros** [comment]
Emoji picker should work on both mode now.
