### ISSUE TITLE
Labs: Ctrl+Backspace & Ctrl+Del doesn't work in the WYSIWYG composer

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23616]
### Steps to reproduce

1. Enable "Try out the rich text editor (plain text mode coming soon)" in labs
2. Refresh to apply changes
3. Type some text in
4. Press Ctrl+Del or Ctrl+Backspace

#### What did you expect?
Correct word is deleted

#### What happened instead?
Correct word is hidden and when I start typing again, it reappears. Note behaviour is slightly different depending on whether there is one or more words in the composer at the time.

### Browser information

Chromium 106.0.5249.119 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 3366ed1-react-51e69427f3d6-js-9f2f08dfd3de Olm version: 3.2.12

### Will you send logs?

No

**Comment by alunturner** [comment]
Implemented in https://github.com/matrix-org/matrix-rich-text-editor/pull/383
