### ISSUE TITLE
"Leave space" should always be the bottom action in the space menu

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23627]
#### What would you like to do?
Have red/destructive actions at the bottom of the menu

#### Why would you like to do it?
Because they should be the least used

#### How would you like to achieve it?
By swapping "See room timeline" and "Leave space" in the menu

### Additional context

![Screenshot from 2022-10-27 12-11-48](https://user-images.githubusercontent.com/51663/198269841-97d2b81c-3c43-4627-8afc-75ddbbefa011.png)

**Comment by KartikBudania** [comment]
@kittykat @justjanne Please assign this issue to me.

**Comment by justjanne** [comment]
> @kittykat @justjanne Please assign this issue to me.

We generally do not assign issues anymore. Feel free to write a PR for it even without being assigned to it.

**Comment by KartikBudania** [comment]
> We generally do not assign issues anymore. Feel free to write a PR for it even without being assigned to it.

@justjanne please help me identify the file/code responsible for the issue, I'll see what I can do.

**Comment by KartikBudania** [comment]
@kittykat would you please help me identify the file/code responsible for the issue?

**Comment by kittykat** [comment]
> @kittykat would you please help me identify the file/code responsible for the issue?

Please be patient. It's the weekend so our developers may take until Monday to follow up :)

I'm not familiar with the code, but you can try searching the code for the string and work your way back from that until you find that menu. Your IDE should provide you with appropriate tools to do that or you can use `[git grep](https://git-scm.com/book/en/v2/Git-Tools-Searching)`

**Comment by KartikBudania** [comment]
@kittykat thanks for your guidance :)

**Comment by t3chguy** [comment]
@KartikBudania search in https://github.com/matrix-org/matrix-react-sdk

**Comment by florianduros** [comment]
Merged in develop in the react-sdk
