### ISSUE TITLE
Fixed width font no longer used in ```code``` syntax

### ISSUE THREAD

**Issue by inputvalidation** [vector-im/element-web#23624]
### Steps to reproduce

1. Where are you starting? What can you see?

I write a message like this:

```
<code>
```

... and it is no longer displaying the content with a fixed width font.

<img width="670" alt="Screenshot 2022-10-27 at 06 58 59" src="https://user-images.githubusercontent.com/26655367/198196162-002b18ad-d2a5-4bc6-96de-69523ec397fc.png">

#### What did you expect?

A fixed width font to be used.

#### What happened instead?

Times New Roman (or similar) was used.

### Operating system

macOS

### Application version

1.11.10

### How did you install the app?

Was updated automatically.

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please send logs

**Comment by inputvalidation** [comment]
For security reasons I can't share these, this is what I also indicated when submitting the issue ("Will you send logs?").

**Comment by t3chguy** [comment]
Without logs we cannot investigate further. I suggest looking at the logs yourself and figuring it out or sharing relevant errors.
