### ISSUE TITLE
Can't restore previous session

### ISSUE THREAD

**Issue by k79e** [vector-im/element-web#23634]
### Steps to reproduce

1. It suddenly shows, randomly happens when you start the program.

#### What did you expect?
It should not happen
### Operating system

win7 x64

### Application version
1.11.12
_No response_

### Will you send logs?
yes

When sending log it says: "fetch failed: Failed to fetch" (no, this is caused proxy network problem. Now it sent.)

**Comment by weeman1337** [comment]
Probably caused by fetch migration.
See linked duplicates for other logs.

**Comment by t3chguy** [comment]
Caused by https://github.com/matrix-org/matrix-js-sdk/pull/2739

**Comment by t3chguy** [comment]
We will be getting out a hotfix release in the coming hours which resolves this issue, fixed in v1.11.13
