### ISSUE TITLE
WISIWIG editor cannot be used to enter a bulleted list 

### ISSUE THREAD

**Issue by test4matrix** [vector-im/element-web#23631]
### Steps to reproduce

1. Where are you starting? What can you see? I want to enter a message with a bulleted list included
2. What do you click? when I try to enter a newline (with shift Carriage-Return) the input line is closed, if the Editor is active - this is possible, if the editor is not active. Then however a <div> character is inserted, thus no list is produced either. I add a screenshot, documenting my input of - test, with the WISIWIG editor enabled and disabled.
3. More steps…
![WISIWIGTestBulletedList](https://user-images.githubusercontent.com/116800745/198298363-f8e60b6b-c0de-4bc0-8966-61ce2f186782.png)

#### What did you expect?
The enabled WISIWIG editor should not evaluate shift Carriage-Return as Carriage-Return
the disabled WISIWIG editor should display a shift Carriage-Return as Carriage-Return and not as <div>
### Operating system

macOS 12.6 (21G115)

### Browser information

Safari 16.0 (17614.1.25.9.10, 17614)

### URL for webapp

https://develop.element.io

### Application version

Version von Element: 5da11ae43654-react-0173e211294c-js-b44787192db1 Version von Olm: 3.2.12

### Homeserver

synod.im

### Will you send logs?

Yes

**Comment by test4matrix** [comment]
I tried to use the \rageshake command out of the WISIWIG Editor and I am not shure, if this worked as intended

**Comment by kittykat** [comment]
The rich text editor doesn't support sending slash commands such as `/rageshake` yet!

**Comment by florianduros** [comment]
Bulleted list are now available https://github.com/matrix-org/matrix-react-sdk/pull/9871
