### ISSUE TITLE
Root event missing meta data in thread

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23648]
### Steps to reproduce

1. Look at a thread root inside that thread

Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9356 & https://github.com/matrix-org/matrix-js-sdk/pull/2735

#### What did you expect?

To have the metadata set to see the display name instead 

#### What happened instead?

See the mxid instead

### Will you send logs?

No

**Comment by t3chguy** [comment]
@gsouquet is this a release blocker given how hard we are promoting threads?

**Comment by gsouquet** [comment]
I don't think it is given it's in labs... but I'm also going to make sure it's fixed before the RC tomorrow.
