### ISSUE TITLE
Error launching 

### ISSUE THREAD

**Issue by flufferyxd** [vector-im/element-web#23640]
### Steps to reproduce

launch element client
error 

#### What did you expect?
complete login, keys load 
### Operating system

Fedora Linux 36

### Application version

unknown/cant access

### How did you install the app?

flathub

### Homeserver

matrix.catgirl.cloud

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Thanks for reporting the issue @flufferyxd . This looks like a duplicate of #23634. Closing in favour of the other issue. If you want to get notifications about the progress please subscribe to the other issue.

**Comment by weeman1337** [comment]
duplicate of https://github.com/vector-im/element-web/issues/23634
