### ISSUE TITLE
Changing custom notification sound fails and causes room notification settings window to be inaccessible

### ISSUE THREAD

**Issue by Nitrox1de** [vector-im/element-web#23641]
### Steps to reproduce

1. Open the room options menu from the ellipses icon
2. Click "Settings"
3. Under "General", "Security & Privacy", and "Roles & Permissions", click "Notifications"
4. Select a custom notification sound and upload
5. It will fail to set the default notification sound
6. Attempting to access the 'Notifications' tab again will instantly close the entire room settings menu

#### What did you expect?
I expected to be able to set my notification sound, and change it if it fails to set

#### What happened instead?
The menu instantly closes on an attempt to revisit the notifications tab if it failed to upload. This occurs even after a complete removal of the program and all associated preference and program/app data, as well as clearing the cache mid session. Also occurs on a different session, on a different device, on a different network, running Windows 10, on a different account.

### Operating system

Windows 10

### Application version

Element version 1.11.12, Olm version 3.2.12

### How did you install the app?

From https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please send logs so the crash reason can be seen

**Comment by eTomte** [comment]
I can confirm that this also happens on the Linux Desktop version of Element as well.

**Comment by JohnDepon** [comment]
Also occurs on the Web Client v1.11.13 on Firefox/Chrome/Edge.  
I've submitted debug logs via the web version of element.

**Comment by eTomte** [comment]
Thanks for fixing this. :)
