### ISSUE TITLE
Deploy to IPFS

### ISSUE THREAD

**Issue by planetoryd** [vector-im/element-web#23650]
#### What would you like to do?

It's not a lot of work. It enhances security.

#### Why would you like to do it?

Deploying to IPFS eliminates trust on element-web hosters and CDNs, especially when using a local IPFS daemon since all the data are content-addressed, ie. verified. Using a IPFS gateway doesn't offer verification.

When deployed to IPNS, element-web can be accessed without DNS, with continual automatic updates.

Element-desktop requires package managers, and is more bloated than element-web. Web clients generally have less access to OS, hence more security. It is easier to control web clients. eg. Setting proxy for element-desktop is troublesome, and less reliable than setting a proxy for browsers. (let's not use OS-level proxying for convenience)

**Comment by aaronraimist** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18921
