### ISSUE TITLE
Confirming mail on password reset does not work

### ISSUE THREAD

**Issue by dabo248** [vector-im/element-web#23652]
### Steps to reproduce

1. Where are you starting? What can you see?

Starting here: https://app.element.io/#/forgot_password

2. What do you click?

Adding a mail and a new password and continuing to the next screen, where I have to confirm my mail. After clicking the link in the mail, I see the following: "Your email has now been validated, please return to your client to reset your password. You may now close this window."
 
3. More steps…

Getting back to the web app, I click on "I have confirmed my mail address" (translated, as I got it in german) and I see an error, stating I have not confirmed my mail address:

"Error

Email address verification failed: Please make sure you have clicked the link in the email" (translated)

It's not possible to reset the password with Element Web.

#### What did you expect?

Password reset

#### What happened instead?

Error stating I have not confirmed my mail, although I have

### Operating system

macOS Ventura 13.0

### Browser information

Safari v16.1, Chrome v107.0.5304.87

### URL for webapp

https://app.element.io/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for reporting @dabo248 . This is a duplicate issue. Closing in favour of the other one.
