### ISSUE TITLE
Can't set up encryption or cross-signing when initiating session with CAS

### ISSUE THREAD

**Issue by retiolus** [vector-im/element-web#23656]
### Steps to reproduce

I can't set up encryption or cross-signing when initiating my session with CAS.

### Outcome

My account on the Synapse server is created with LDAP, I initiate the session on Schildichat with this account using CAS, I am asked for a password to activate these two options but it does not seem to be the same password as the LDAP user, what to do?

### Will you send logs?

No

**Comment by t3chguy** [comment]
These prompts are requested by your Synapse server via the UIA mechanism, I suggest you seek support from them on how to fix this. https://spec.matrix.org/v1.4/client-server-api/#user-interactive-authentication-api
