### ISSUE TITLE
"Something went wrong" when joining space

### ISSUE THREAD

**Issue by nh2** [vector-im/element-web#23670]
### Steps to reproduce

1. From my matrix.org account on element-web with version from today, try to join the `#teams:nixos.org` room/space.
2. Get shown `Something went wrong! Please create a new issue on GitHub`

For reference, I:

* had already joined in the "parent" `NixOS` public space `#community:nixos.org` (which contains the room I want to join, `#teams:nixos.org`), and also
* had already joined `#security-discuss:nixos.org` (which is _contained in_ the room I want to join,  `#community:nixos.org`)

Just in case the fact that I tried to join a room in the "middle" of the space containment hierarchy is relevant to the issue.

#### What did you expect?

No popup asking me to report a bug on Github.

#### What happened instead?

A popup asking me to report a bug on Github:

![image](https://user-images.githubusercontent.com/399535/199229780-bdc0005e-5955-4bf3-a246-e84ac959feaa.png)

### Operating system

Ubuntu Linux 22.04

### Browser information

Firefox 106

### URL for webapp

app.element.iop

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by nh2** [comment]
I performed `Submit debug logs` as shown in the popup.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22752
