### ISSUE TITLE
Failed to load timeline position when clicking "go to unread" up arrow

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#23697]
### Steps to reproduce

1. Open a room with unread messages
2. Click on the up arrow to jump to the first unread message

#### What did you expect?
Jumping to the message.

#### What happened instead?
Got this:
```
Failed to load timeline position
Tried to load a specific point in this room's timeline, but was unable to find it.
```

### Operating system

Arch Linux

### Application version

1.11.10-1

### How did you install the app?

Package manager

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hi!

First of all thank you for your report. 

I don't reproduce the issue. The bug is happening every time in your case ?

**Comment by davidegirardi** [comment]
Hi, no it does not. It happened a couple of other times and I think it's connected to Element believing there are unread messages when there actually are not.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20927

**Comment by Elliria** [comment]
The same thing happens to me on the gitter.im homeserver.

**Comment by GigiDee** [comment]
I am currently getting this issue just trying to comment in the thread of a message - is anyone else repetitively getting this issue? 

Also, the search function no longer works? Any idea as to why?
