### ISSUE TITLE
MSC3401 calls have notifications should respect `Mentions Only`

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23691]
### Steps to reproduce

1. Set a room to Mentions Only
2. Have another user start an MSC3401 call
3. Hear noise & get desktop notification
4. Note lack of badge in room

#### What did you expect?

For "Mentions Only" to be fully respected - there should not be a notification.

#### What happened instead?

A notification, but only half of one.

### Operating system

Windows 10 & 11

### Application version

Nightly

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
From what I gather here, to make this work the `PushProcessor` would need to check the room push rules, which I belive it doesn't do atm

**Comment by turt2live** [comment]
that should already be the case though? Are the call notifications going through without push rules?

**Comment by SimonBrandner** [comment]
The call notifications are done using push rules and yet it seems to ignore setting a room to `Mentions Only`... Can't see any code to handle this - am I blind?

**Comment by turt2live** [comment]
I haven't looked, but usually this sort of behaviour is caused by something going outside the push rules process (either because the js-sdk does a bad job of merging missing rules, or because the code literally doesn't use push rules)
