### ISSUE TITLE
Notifications panel is always empty on `develop.element.io`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#23695]
### Steps to reproduce

1. Open the notification panel (accessed via the bell icon in the top-right)
2. Notice how the notification panel doesn't have any notifications listed

> You're all caught up
> 
> You have no visible notifications.

This is only broken on `develop.element.io`

`app.element.io` (working ✅) | `develop.element.io` (not working ❌)
--- | ---
![](https://user-images.githubusercontent.com/558581/199847421-883b9d39-12ef-4278-9940-5269a74f79cb.png) | ![](https://user-images.githubusercontent.com/558581/199847434-1115ee3c-c988-4799-9991-f00db5d6e7b9.png)

#### What did you expect?

Notifications to be shown

#### What happened instead?

Just shows an empty placeholder view

When opening the panel, the following is logged to the console,

```
can't initialise scroll state because messagePanel didn't load
```

### Operating system

Windows 10

### Browser information

Chrome Version 107.0.5304.88

### URL for webapp

develop.element.io

### Application version

Element version: e21eb2505c3a-react-a347525781e1-js-4a33e584b01d Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes, see https://github.com/matrix-org/element-web-rageshakes/issues/16781

**Comment by weeman1337** [comment]
Could this be related to threads?

**Comment by t3chguy** [comment]
staging.element.io needs testing as this could be a release blocker

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/2835
