### ISSUE TITLE
Error when setting my avatar for one room only

### ISSUE THREAD

**Issue by CrackFoxo** [vector-im/element-web#23705]
### Steps to reproduce

1. Where are you starting? What can you see?

    Happens in any room.

2. What do you click?

     Used the command /myroomavatar  
Picked an image file 

     Got taken to the upload files screen and then clicked "Upload" 

     A few seconds passed and the server error message appears.  

#### What did you expect?

My avatar for that room to change into the image being uploaded

#### What happened instead?

This server error appears and after it is a link to the room I think

MatrixError: [500] Internal server error 

### Operating system

Windows 10 Pro

### Application version

Element version: 1.11.13 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed on develop & staging
