### ISSUE TITLE
Reply to picture is not working at all

### ISSUE THREAD

**Issue by notimportant1** [vector-im/element-web#23706]
### Steps to reproduce

Is impossible to reply to the picture! It will not show the picture but a text like “shush53.jpg” is so crucially important to see to which picture we are replying. Please please fix this! I look forward to hear back from you. 

I look forward to hearing back from you,

Roman 

### Outcome

Is impossible to reply to the picture! It will not show the picture but a text like “shush53.jpg” is so crucially important to see to which picture we are replying. Please please fix this! I look forward to hear back from you. 

My email address is 3140146489@protonmail.com

I look forward to hearing back from you,

Roman

### Operating system

iOS Apple 

### Application version

1.9.9 olm 3.2.12

### How did you install the app?

iOS app store

### Homeserver

Any

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Hi @notimportant1 . Looks like you reported the issue in the wrong tracker. This is the one for element web.

Moving your issue to iOS

**Comment by weeman1337** [comment]
Unfortunately I am unable to move it. @notimportant1 can you please re-open your issue here? https://github.com/vector-im/element-ios/issues
