### ISSUE TITLE
Pop out jitsi call does not work when openidtoken-jwt is enabled

### ISSUE THREAD

**Issue by krombel** [vector-im/element-web#23700]
### Steps to reproduce

1. enable openidtoken-jwt authentication for jitsi
2. add jitsi widget to room
3. click "Pop out"
4. "Joining" Window (jitsi.html) opens

#### What did you expect?
I can join conference

#### What happened instead?
When clicking on "Join Conference" it says "Failed to load Jitsi widget"

### Operating system

-

### Browser information

-

### Application version

1.11.13

### Homeserver

synapse 1.70.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a known issue, though I thought we disabled the pop-out button when auth was used

**Comment by krombel** [comment]
It is not disabled

**Comment by krombel** [comment]
Wouldn't it be possible to append an openId token to that popout url (leaving the other arguments as is)
I would try a PR for that if wanted

**Comment by t3chguy** [comment]
It'd be possible but it is unlikely to be desirable, a link is easily wrongly shared, breaking the security model

**Comment by dhenneke** [comment]
I think this issue can be closed since it was solved by https://github.com/vector-im/element-web/pull/24294. The solution there was to just hide the button since it can't work in this situation.
