### ISSUE TITLE
MXIDs with forward slashes not recognised

### ISSUE THREAD

**Issue by 0x1a8510f2** [vector-im/element-web#23708]
Related: https://github.com/matrix-org/matrix.to/issues/288

### Steps to reproduce

1. Send an MXID without a slash in chat
2. Notice that it automatically gets linkified with the correct matrix.to link
3. Send an MXID with forward slash in chat
4. Notice that it does not get linkified correctly

#### What did you expect?

Per [the spec](https://spec.matrix.org/v1.4/appendices/#user-identifiers), the MXID should be recognised.

#### What happened instead?

![image](https://user-images.githubusercontent.com/83190128/200072639-22b3e04d-ef07-4149-b6a1-968aa6388536.png)

### Operating system

(not relevant)

### Browser information

(not relevant)

### URL for webapp

(not relevant)

### Application version

1.11.12

### Homeserver

(not relevant)

### Will you send logs?

No

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/6381

**Comment by 0x1a8510f2** [comment]
Going through the comments on the linked issue, it looks like there are a few related issues actually, mostily from 5 years back:

#6381
#4867
#5135

Not sure if I should close this as duplicate then?

In either case, any chances this could get some priority? It's impossible to work around if you have a nickname with a slash in it and seems to have been around for a while.

**Comment by t3chguy** [comment]
@Johennes one interesting tidbit, they get handled differently.

<img width="293" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/e403771b-bdd5-4a28-84fd-3c6f43ade6c5">

Only the latter gets a URL preview

**Comment by Johennes** [comment]
Oh interesting. None of them should get one, right?

**Comment by t3chguy** [comment]
Indeed

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/df202e62-8a17-4c60-9a43-d65deb585e88)

**Comment by Johennes** [comment]
Ohh, nice find! And thanks for fixing it. 👍
