### ISSUE TITLE
Add other social media logins to Element apps

### ISSUE THREAD

**Issue by mackiexx** [vector-im/element-web#23719]
#### What would you like to do?

It will be great if the social media logins mentioned in OpenID like twitter and twitch will be added to the mobile apps logins. 

#### Why would you like to do it?

Since Element is not responsive on mobile view, having this logins is essential cause some people might want to add these OpenIDs but cannot since it is not on mobile apps. I will like to add twitter and twitch but i can't since it is not on mobile apps and user wont be able to login with it on mobile apps after logging in with it on Desktop

#### How would you like to achieve it?
The OpenIDs is already available on the website and it will be great if it can be supported too on mobile apps.

**Comment by t3chguy** [comment]
Element supports whatever the connected Server says it supports, I suggest reaching out to the server you are using to add support for more auth providers.
