### ISSUE TITLE
RTL writing and font

### ISSUE THREAD

**Issue by mahmoodn** [vector-im/element-web#23725]
### Your use case

Additional support for non-English languages, specially Farsi, which is a right-to-left language and also more standard fonts for better representation.

**Comment by t3chguy** [comment]
> and also more standard fonts for better representation.

You can choose whichever font you like most in Settings > Appearance > Advanced

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/14520

**Comment by t3chguy** [comment]
This repo is called element-web, you might want to try one called element-android for issues with the Android app.
