### ISSUE TITLE
Scrolling in the main timeline while keeping a thread with a mention open increases the notification count

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23721]
### Steps to reproduce

1. Clear all your notifications in a room
1. Open a thread in that room where you were previously mentioned and notified
2. Scroll backwards through the main timeline of the room

#### What did you expect?

The notification count should stay at zero

#### What happened instead?

The room gets a red badge, and the notification count for the room seems to increase by 1 for every new event loaded into the main timeline

### Operating system

NixOS unstable

### Browser information

Firefox 106.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 65b8bc196a89-react-36a574a14fa7-js-6c543382e665 Olm version: 3.2.12

### Homeserver

Synapse 1.70.1

### Will you send logs?

No

**Comment by gsouquet** [comment]
I have been unable to reproduce with the steps you gave, there must be other forces at play that I have not figured out yet, but I have a PR up that could make this a tiny bit better, https://github.com/matrix-org/matrix-js-sdk/pull/2862

Would you be able to check the Netlify build at some point?

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2862
