### ISSUE TITLE
When scrolling thread list up, scroll gets reset to the bottom at random 

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23727]
### Steps to reproduce

1. scroll backwards in a very long list of threads

#### What did you expect?

natural scrolling backwards

#### What happened instead?

you sometimes get jumped at the very bottom of the list, seemingly at random

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
Here are more details from the [duplicate](https://github.com/vector-im/element-web/issues/23787) I created.

Reproduction steps:

1. Have a room where you haven't opened the threads list panel in a while
1. Open the threads list panel
1. Try to scroll around while it's catching up and fetching thread summaries
1. Notice how you keep being forced back to the bottom of the list each time something updates (like a thread summary)


The video is a bit cut-off as I didn't have the recording wide enough before I started recording but demonstrates the problem perfectly. The scroll keeps getting reset to the bottom.

https://user-images.githubusercontent.com/558581/202582910-0b959141-25a0-40b5-b4a7-ed9ec4b6d52d.mp4
