### ISSUE TITLE
Missing avatars in pills

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#23733]
### Steps to reproduce

1. Mention someone in a pill
2. Observe the lack of avatar

#### What did you expect?

The user's avatar is in the pill

#### What happened instead?

The place where the user's avatar should be is empty (filled with white):

![image](https://user-images.githubusercontent.com/5547783/200636596-17acfd14-e097-4d7b-bb31-dd5fbc45df73.png)

When inspecting the element with devtools, it looks like the source of the `img` tag for the avatar is empty:

![image](https://user-images.githubusercontent.com/5547783/200636815-8ea683d2-14fa-4363-87ba-13e1155b26d4.png)

### Operating system

Arch Linux

### Browser information

Firefox 106.0.3

### URL for webapp

develop.element.io

### Application version

Element version: 65b8bc196a89-react-3f3005a3ca4d-js-bd4589fcc45b, olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by babolivier** [comment]
Note that this is happening for every single pill (apart from reply headers) over two instances of Element (each connected to a different homeserver).

**Comment by t3chguy** [comment]
member=Object object looks super suspicious

**Comment by robintown** [comment]
Avatars are also missing from the members panel in spaces:

![Screenshot 2022-11-08 at 22-40-29 Element 11 NixOS](https://user-images.githubusercontent.com/48614497/200732781-209702e9-3139-495f-837b-48cad33da84f.png)

**Comment by babolivier** [comment]
> Avatars are also missing from the members panel in spaces:

Can confirm I'm seeing this as well

**Comment by gsouquet** [comment]
This does not seem as easy to reproduce as it seems.
I've tried many different combinations of homeservers or browsers without luck. 

I suspect this might be down to an OS difference, but have not manage to spot the issue yet
