### ISSUE TITLE
Bad PGP signature in v1.11.14-src.tar.gz.asc for element-desktop v1.11.14.tar.gz

### ISSUE THREAD

**Issue by hardfalcon** [vector-im/element-web#23734]
### Steps to reproduce

Download the source tarball for element-desktop 1.11.14 and it's PGP signature from Github:
https://github.com/vector-im/element-desktop/pulls

### Outcome

The released file `element-desktop-1.11.14.tar.gz.asc` that is supposed to contain the PGP signature for the released source tarball `element-desktop-1.11.14.tar.gz` appears to contain a bad PGP signature:
```
$ gpg --verify element-desktop-1.11.14.tar.gz.asc
gpg: assuming signed data in 'element-desktop-1.11.14.tar.gz'
gpg: Signature made 2022-11-08T17:22:41 CET
gpg:                using RSA key E95B7699E80B68A9EAD9A19A2BAA9B8552BD9047
gpg:                issuer "releases@riot.im"
gpg: BAD signature from "Element Releases <releases@riot.im>" [unknown]
```

The ASC file containing the signature for `element-web-1.11.14.tar.gz` looks fine though:
```
$ gpg --verify element-web-1.11.14.tar.gz.asc 
gpg: assuming signed data in 'element-web-1.11.14.tar.gz'
gpg: Signature made 2022-11-08T16:11:20 CET
gpg:                using RSA key E95B7699E80B68A9EAD9A19A2BAA9B8552BD9047
gpg:                issuer "releases@riot.im"
gpg: Good signature from "Element Releases <releases@riot.im>" [unknown]
gpg:                 aka "Element Web Releases <web-releases@element.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 712B FBEE 92DC A452 52DB  17D7 C7BE 97EF A179 B100
     Subkey fingerprint: E95B 7699 E80B 68A9 EAD9  A19A 2BAA 9B85 52BD 9047
```

The reason why this doesn't work seems clear: After the PGP signature file was uploaded on 2022-11-08T16:22:43Z, the `v1.11.14` tag was modified at 2022-11-08T17:34:40Z, so the PGP signature simply cannot be valid unless somebody has invented time travel. Looking at my RSS reader, this was likely caused by a copy-paste error when initially creating the `v1.11.14` tag at 2022-11-08T16:09:21Z.

### Operating system

Archlinux x86_64, gnupg 2.2.40-1

### Application version

element-desktop 1.11.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
@hardfalcon please try again now https://github.com/vector-im/element-desktop/releases/download/v1.11.14/v1.11.14-src.tar.gz.asc

**Comment by hardfalcon** [comment]
Thanks a lot for the swift response, the signature works fine now. :)
