### ISSUE TITLE
Read receipts don't trickle down correctly

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#23746]
### Steps to reproduce

1. Display a room with some activity in it
2. Observe the read receipts on new messages

#### What did you expect?

Read receipts correctly trickle down to the last message that someone has read.

#### What happened instead?

Some read receipts don't move when they should. In the screenshot below:

![image](https://user-images.githubusercontent.com/5547783/201070413-7658196e-cbe9-421f-bd1b-9815a5c4d4fe.png)

my cursor is on top of Half-Shot's avatar. You can somewhat see Michael W's past the top right corner of the tooltip, which hasn't trickled down from the previous message, even though Element Web apparently realises it should have moved (since the tooltip shows their name next to Half-Shot's).

I'm seeing this happen across most (all?) rooms.

### Operating system

Arch Linux

### Browser information

Firefox 106.0.3

### URL for webapp

develop.element.io

### Application version

Element version: 65b8bc196a89-react-3f3005a3ca4d-js-bd4589fcc45b, olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by robintown** [comment]
Likely cause:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
MemberAvatar@webpack-internal:///971:51:9
NodeAnimator@webpack-internal:///2013:37:5
ReadReceiptMarker@webpack-internal:///2012:38:5
```
