### ISSUE TITLE
Got „Unable to decrypt: decryption key withheld“ for some messages

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23745]
### Steps to reproduce

1. Existing encrypted room
2. Other user sends some messages

#### What did you expect?

Could read all messages

#### What happened instead?

- Got „Unable to decrypt: decryption key withheld“
- After new login they appear as „Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX “
- Sender can read all messages

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 107.0

### URL for webapp

https://develop.element.io/

### Application version

Element version: 65b8bc196a89-react-3f3005a3ca4d-js-bd4589fcc45b Olm version: 3.2.12

### Homeserver

ccc-ffm.de / Synapse 1.70.1

### Will you send logs?

Yes

**Comment by grisu48** [comment]
Same issue, here, `docker.io/matrixdotorg/synapse:latest` with Firefox 106.0.2 on openSUSE Tumbleweed.

**Comment by DavidB137** [comment]
I can also confirm the issue. This strange behaviour makes overall user experience *a lot* worse, because to "normal" people who just want to text, Element doesn't look like a reliable solution.

- server: selfhosted latest Synapse
- client 1 and 2 are on some combination of Element web, Android and desktop app

**Comment by weeman1337** [comment]
Looks like frequency increased cross platform in the last days https://github.com/vector-im/element-android/issues/7403#issuecomment-1297888369

**Comment by moritzdietz** [comment]
Yes, me too! I have noticed this this morning with iPhone, Android as well es Element Desktop on macOS.
Thought it was a spontaneous error on our end, but seems more broad after seeing this issue here.

**Comment by quicquid** [comment]
The receiver encountered the issue for the android app as well. When I started up the desktop app (on a different device) the message could be decrypted by the receiver.

**Comment by robertmx** [comment]
Possible workaround in the related (identical?) issue #7403.
https://github.com/vector-im/element-android/issues/7403#issuecomment-1312193215

**Comment by moritzdietz** [comment]
Just rageshaked from within develop.element.io and added linked it to this issue. Maybe there's something in there which helps.

**Comment by quicquid** [comment]
I tried /discardsession as mentioned in issue #7403 on the device sending the message and it did the trick.

**Comment by richvdh** [comment]
@weeman1337 I have looked at your rageshake, and it looks like the events were sent before you joined the room, which I think explains why you can't decrypt them?

On the other rageshakes that you have linked to this issue: do you have any particular reason to believe they have the same cause?

**Comment by weeman1337** [comment]
@richvdh I did post all messages in an existing room.

**Comment by richvdh** [comment]
> @richvdh I did post all messages in an existing room.

I'm afraid I'm not following you at all.

Your initial rageshake (https://github.com/matrix-org/element-web-rageshakes/issues/16971) the problem, afaict, is with messages sent by `@l:lesosoftware.com`, before you joined the room.

If there are particular events that you are having trouble with, please can you tell me which they are, and exactly what you are seeing?

**Comment by weeman1337** [comment]
It happened just inside a chat. Both sides joined the room before. We already sent messages to each other before. This happens sometimes right in the middle of some chat.

![image](https://user-images.githubusercontent.com/6216686/202466693-474f3754-99c9-4574-b9d3-bd26b7b723c4.png)

Event Id from the screenshot: `$4Nr8sFKwGwoMpXa4E2sWS0cp4AP0Bc7C48_Dzca213U`

**Comment by richvdh** [comment]
> This happens sometimes right in the middle of some chat.

Please don't assume that every time you can't decrypt a message, it's the same problem!

I can look at `$4Nr8sFKwGwoMpXa4E2sWS0cp4AP0Bc7C48_Dzca213U` more closely.

**Comment by richvdh** [comment]
@weeman1337 well, `$4Nr8sFKwGwoMpXa4E2sWS0cp4AP0Bc7C48_Dzca213U` really looks to have been sent before `@l:lesosoftware.com`'s client got the memo about you having joined the room. Without access to their server's database, it's hard to be exactly certain, but I think this is an inevitable artifact of a distributed system: even if your server thinks you have joined the room at a given time, it's not the case that everyone in the room will see the same thing.

Thanks for the report though!

**Comment by richvdh** [comment]
Wait, I'm confused (again). 

> Got „Unable to decrypt: decryption key withheld“
> After new login they appear as „Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX “

Is the rageshake I'm looking at (https://github.com/matrix-org/element-web-rageshakes/issues/16971) from the old login or the new one? Presumably the old one? What about the screenshot above? When was the screenshot taken? Do we have a rageshake from about the right time?

The reason I ask is that I just spent half an hour looking for "decryption key withheld" errors in https://github.com/matrix-org/element-web-rageshakes/issues/16971 and failing to find any :(

**Comment by weeman1337** [comment]
> @weeman1337 well, $4Nr8sFKwGwoMpXa4E2sWS0cp4AP0Bc7C48_Dzca213U really looks to have been sent before @l:lesosoftware.com's client got the memo about you having joined the room. Without access to their server's database, it's hard to be exactly certain, but I think this is an inevitable artifact of a distributed system: even if your server thinks you have joined the room at a given time, it's not the case that everyone in the room will see the same thing.

But as you can see in the screenshot above it happened in an ongoing chat. One message can be read and the next one not. :man_shrugging: 

---

> Is the rageshake I'm looking at (https://github.com/matrix-org/element-web-rageshakes/issues/16971) from the old login or the new one?

Should be from the old login.

---

> but I think this is an inevitable artifact of a distributed system: even if your server thinks you have joined the room at a given time, it's not the case that everyone in the room will see the same thing.

The other user of the [most recent rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/17118) is on the same server:

![image](https://user-images.githubusercontent.com/6216686/202733325-95c1455b-00b9-43e0-bd46-cd1c3c6c357b.png)

**Comment by weeman1337** [comment]
@richvdh in general: Should I open separate issues when an „Unable to decrypt: decryption key withheld“ appears? I just learned from you that they can have many different causes.

**Comment by richvdh** [comment]
This seems to be due to https://github.com/vector-im/element-web/issues/23803. Closing in favour of that.

**Comment by Martin0100110101001000** [comment]
Exactly the same issue here, using Windows desktop and android phones.  And Starlink internet.

**Comment by jonnyrobbie** [comment]
> This seems to be due to #23803. Closing in favour of that.

I'm not sure I understand. #23803 makes it seem like it's only a nomenclature/wording issue? When a chat (that one relies on for real world people communication) fundamentally breaks, a user doesn't really cares if "keys witheld" is not the most appropriate message. A user cares that he completely lost a method of communication. I'm completely behind @DavidB137 frustration that this makes element/matrix like a unrealiable and undependable tool.

> I really can't see that from the screenshot, sorry. A bunch of information is pixellated: I have no idea what the other messages are, when they arrived, who sent them, how they got there, etc. But most importantly, I have no idea how it correlates to your original report or the rageshake you sent.

He was just counterpointing you that the messages stopped being recieved in the middle of the session, which *is* visible from the screenshot.

---

Here's my entry if it helps you more with diagnosing the issue:

Decrypted event source:
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: decryption key withheld **"
  }
}
```

Original event source:
```
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
   ...
  },
  "event_id": "$1672913572466835HxZbP:matrix.org",
  "origin_server_ts": 1672913572551,
  "room_id": "!UJVHFqSAHanxWQMbhW:matrix.org",
  "sender": "@xstem116:matrix.org",
  "type": "m.room.encrypted",
  "unsigned": {
    "age": 365175193
  },
  "user_id": "@xstem116:matrix.org",
  "age": 365175193
}
```

**Comment by shinji257** [comment]
It seems to be related but not the same issue. The one thing I'll note is channels and chats by this seem to have the messages but are hidden from view. If you export the affected chat the result has messages that could be decrypted even if they were not visible in Element.
