### ISSUE TITLE
URL in formatted message gets mangled due to markdown

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23743]
### Steps to reproduce

1. Post a message
2. Reply to it with this link `https://wiki.fsfe.org/Activities/Android/UpcyclingWorkshops#A24._November_2022_-_Chaos_Computer_Club_Frankfurt.2C_Frankfurt.2C_Deutschland`

#### What did you expect?

Exactly this link in reply message

#### What happened instead?

Got `https://wiki.fsfe.org/Activities/Android/UpcyclingWorkshops#A24._November_-_Chaos_Computer_Club_Frankfurt.2C_Frankfurt.2C_Deutschland`

„2022“ is gone

![2022](https://user-images.githubusercontent.com/6216686/201047462-17214624-3999-48b3-bfe0-47b84413417b.gif)

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 107.0

### URL for webapp

https://develop.element.io/

### Application version

Element version: 65b8bc196a89-react-3f3005a3ca4d-js-bd4589fcc45b
Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Are we sure this is a regression? Has anyone tried against an older version in riots.im?

**Comment by t3chguy** [comment]
Reproduced on 1.11.10

**Comment by t3chguy** [comment]
This is in all "rich" messages, so either in replies due to the fallback or any message with markdown markup
