### ISSUE TITLE
Polls show different results depending on what part of the timeline you've loaded

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23756]
### Steps to reproduce

1. Start a poll in an active room
2. Get a bunch of responses, interspersed with messages
3. Wait until there are enough messages to put the first poll responses fully out of your client's view of the timeline
4. Reply to the poll
5. Reload Element

#### What did you expect?

Polls should always show consistent and accurate results.

#### What happened instead?

Depending on where I scroll in the timeline, the poll results change significantly. For example if I reload Element and then view the reply to the poll, the reply preview only counts the more recent responses. If I scroll all the way back to the original posting of the poll, I see all of the responses counted (I think). If I copy the link to the poll, close Element, and then launch Element using this link, I get yet another result counting only the earlier responses.

### Operating system

NixOS unstable

### Browser information

Firefox 106.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 8f8a9e1e49f5-react-e8d4fbb8ff2b-js-67f343d6f0a2 Olm version: 3.2.12

### Homeserver

Synapse 1.71.0

### Will you send logs?

No

**Comment by turt2live** [comment]
This will be because we don't call `/relations`

**Comment by kerryarchibald** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9877
(Polls now use /relations API to fetch all votes)
