### ISSUE TITLE
It might be good to truncate the notifications in the notif panel

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2375]
As a reminder when designing it

**Comment by ara4n** [comment]
as in limit the number of lines we show of the message?

**Comment by AmandineLP** [comment]
yes

**Comment by ara4n** [comment]
personally I quite like the fact that it doesn't... in general the culture of matrix rooms encourages people not to send enormous messages, and when they do it's often not clear how to truncate them (unless we did it cosmetically with CSS).  @AmandineLP do you still think we need this?

**Comment by MadLittleMods** [comment]
Closing as there hasn't been any follow-up
