### ISSUE TITLE
iOS App crashed - Voice Messages

### ISSUE THREAD

**Issue by DCDevilschild** [vector-im/element-web#23757]
### Steps to reproduce

1. Record a voice message on Element iOS App
2. Play this voice message on Element iOS App
3. The app crashed and closed

#### What did you expect?

The app should continue to run

#### What happened instead?

The app ist crashed and closed.

### Operating system

Apple iOS

### Application version

iOS Element App 1.9.10

### How did you install the app?

Apple App Store

### Homeserver

Matrix EMS Homeserver / Synapse 1.71.0 / Python 3.19.15

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please open the issue in https://github.com/vector-im/element-ios/
