### ISSUE TITLE
Lags and slowdown/freezes in some rooms

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [vector-im/element-web#23763]
### Steps to reproduce

I just open the room https://matrix.to/#/#yggru:matrix.org (I was already there) It loads two messages and then it hangs and slows down.

It affected selectively and does not appear in all rooms.

#### What did you expect?
All messages are loaded quickly and without freezing.

#### What happened instead?
Everything is terribly slow, it's impossible to use.

### Operating system

Windows

### Browser information

Firefox 107.0b5 (64 bit)

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by 0x4E69676874466F78** [comment]
I can't send a full log because it keeps slowing down so much that it practically hangs.

**Comment by gsouquet** [comment]
@0x4E69676874466F78 thank you for opening this issue. We've received your rageshakes even though the UI might not be showing the feedback it usually shows.
Would it be possible for you to capture a performance profile? This could help pinpoint where the issue is

**Comment by 0x4E69676874466F78** [comment]
@gsouquet With what profiling settings?
Also at the moment it is not slowing down, but the messages are not loading.
![изображение](https://user-images.githubusercontent.com/4449851/201729187-4db249b9-fb52-4eac-9525-38af57d29f45.png)

**Comment by 0x4E69676874466F78** [comment]
It happened again and I capture the "Web Developer" profile. I sent it through the rageshake, please check it.

**Comment by turt2live** [comment]
I believe this is due to an operational issue on the matrix.org homeserver and not a new cause of performance degredation in the app. 

There are cases where the app is slow in this respect, however they are tracked by other issues already.
