### ISSUE TITLE
Threads panel immediately re-opens

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#23764]
### Steps to reproduce

1. In a room with several threads, with the thread panel open
2. Click the X in the top right of the thread panel

#### What did you expect?

The thread panel should disappear.

#### What happened instead?

The thread panel disappears and then immediately re-appears:

![reappearing-thread mp4](https://user-images.githubusercontent.com/76812/201640981-c89191e1-6ac4-4ca7-a187-c41a8a73f1c5.gif)

[Note: I have tried with both with and without Rich Text Editor enabled in labs.]

### Operating system

Ubuntu 22.04

### Browser information

Firefox 106.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 8f8a9e1e49f5-react-18c03daa865d-js-ba6a001d677f Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Me and @andybalaam did investigate this a bit more together this morning as he could reproduce it!

All the `RightPanelStore` code seems to be doing what it needs to do. However, Andy managed to get in a state where https://github.com/matrix-org/matrix-react-sdk/blob/6c556cb88c73902f6345fddc24c3f6d2834d1680/src/components/structures/RoomView.tsx#L621 is executed when closed... 

We lost track of the problem after that

**Comment by andybalaam** [comment]
Yes, not every time I get a notification, but it does seem like this is caused by desktop notifications

**Comment by andybalaam** [comment]
I am getting this again today, again triggered by clicking a desktop notification.

**Comment by andybalaam** [comment]
This is happening again for me this morning :-(

I'll rageshake.

**Comment by andybalaam** [comment]
I haven't seen this for a while, so I think it's done.
