### ISSUE TITLE
Element account code

### ISSUE THREAD

**Issue by zkeller01** [vector-im/element-web#23768]
### Steps to reproduce

1. Where are you starting? I sign in What can you see? it shows me a screen saying messages may have been lost and i need to sign in and out again to get codes but when i sign out and log back in it says the same thing
2. What do you click? I have no clue because it told me my messages couldnt be decrypted and i closed the tab opened it again and now it wont let me in
3. More steps…

#### What did you expect?
it told me that i needed to recover codes from another device but i dont have that device at this moment 
#### What happened instead?
i cant get back in to message people

### Operating system

google

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
Are you able to provide a screenshot for what you're seeing?
