### ISSUE TITLE
"localStorage.clear()" too invasive in Lifecycle.ts

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#23772]
### Your use case

Clearing all localStorage items within function `clearStorage` (in `Lifecycle.ts`, see here https://github.com/matrix-org/matrix-react-sdk/blob/c10339ad682880dee68231d23643867bedc0a0d5/src/Lifecycle.ts#L886) is too invasive as it wipes data from other apps running under the same origin.

To avoid this `window.localStorage.clear()` could be replaced by a method like shown below, using the localStorage prefix of Matrix (`mx`):

```
        // Clear Matrix-specific localStorage items only
        for (let i = window.localStorage.length - 1; i >= 0; i--) {
            const key = window.localStorage.key(i);
            if (key.startsWith("mx")) {
                window.localStorage.removeItem(key);
            }
        }
```

**Comment by turt2live** [comment]
This is considered a feature - Element Web expects to be the only thing on the domain.
