### ISSUE TITLE
Video room is stuck in 'grey' state after leaving it

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#23781]
### Steps to reproduce

Leave Element-call video room

### Outcome

The call is stuck in a "grey" state

<img width="838" alt="1" src="https://user-images.githubusercontent.com/1137962/202423844-925eb5c7-afa8-4baf-b9e4-651c073cffbb.png">
<img width="395" alt="2" src="https://user-images.githubusercontent.com/1137962/202423853-90b7a0b5-1b5c-4391-9848-f2fd00db515c.png">

See https://github.com/matrix-org/element-web-rageshakes/issues/17193

### Operating system

macOS

### Application version

nightly

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by robintown** [comment]
Unfortunately the linked rageshake doesn't show the offending error, since the issue occurred inside the Element Call iframe. If this happens again, please look manually for any errors inside the developer tools console.

**Comment by robintown** [comment]
Yep, Ctrl+Shift+I

**Comment by robintown** [comment]
This needs retesting on the latest Nightly now that https://github.com/vector-im/element-desktop/pull/458 might have fixed it

**Comment by robintown** [comment]
Retested, fixed by https://github.com/vector-im/element-desktop/pull/458
