### ISSUE TITLE
Web: Missing session data

### ISSUE THREAD

**Issue by maximeborges** [vector-im/element-web#23790]
### Steps to reproduce

1. Where are you starting? What can you see?
Open the Web element app.

2. What do you click?
Nothing

#### What did you expect?
The main application view with my channels on the left and the space for messages on the right.

#### What happened instead?
![image](https://user-images.githubusercontent.com/159235/202700905-ed3024d3-bcc4-424f-bdae-8047ba5c70a1.png)

### Operating system

Windows 10

### Browser information

Chrome 107.0.5304.107

### URL for webapp

https://app.element.io/

### Homeserver

posttenebraslab.ch  on Synapse 1.68.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Please send logs.

**Comment by maximeborges** [comment]
I'm not sure where I should send the logs, I downloaded them but then closed everything and started from a clean session. When doing the /rageshake command I guess it would only send the new logs

**Comment by t3chguy** [comment]
Closing due to lack of requested info
