### ISSUE TITLE
Clicking on a link/preview to an event does nothing

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#23794]
### Steps to reproduce

1. Open a room where a reply has been sent
2. Click on the preview of the message that was replied to

Note that I've also observed this behaviour with matrix.to links to specific events.

#### What did you expect?

The timeline jumps to the event.

#### What happened instead?

Nothing. The event ID gets added to the tab's URL, but the timeline stays where it is.

https://user-images.githubusercontent.com/5547783/202741968-9a48cd8c-0d19-4401-86da-0af4ee96493b.mp4

### Operating system

Arch Linux

### Browser information

Firefox 106.0.3

### URL for webapp

develop.element.io

### Application version

Element version: 6bdc8daa3683-react-cd46c8969923-js-c0f7df8c3bc9, olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by robintown** [comment]
I can reproduce this. It doesn't seem to just be caused by the usual amount of jumpy timeline brokenness, so I think this is a regression.

**Comment by t3chguy** [comment]
Likely caused by https://github.com/matrix-org/matrix-react-sdk/commit/590b845f3f4bfa076c758bfa137cc75816b70023

**Comment by robintown** [comment]
Confirmed that this does not affect the RC.

**Comment by babolivier** [comment]
Note that this bug also affects search results, in that clicking on a search result in the room's timeline doesn't do anything (closing the search UI with the red "X" next to the search bar does switch to the the result that was last clicked on though).
