### ISSUE TITLE
Something went wrong, but i can't submit the debug log

### ISSUE THREAD

**Issue by hoowwshii** [vector-im/element-web#23805]
### Steps to reproduce

I don't click anything

### Outcome

![image](https://user-images.githubusercontent.com/68774737/202942874-e92f8c35-ce74-4c64-875c-e1b59bce9f54.png)

#### What did you expect?
Submit the debug log 

#### What happened instead?
its not working, i clicked the button, nothing happened

### Operating system

Windows 10

### Browser information

Firefox v107

### URL for webapp

app.element.io

### Application version

Element version: 1.11.14 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Without logs we cannot do anything. Please get logs out of the web browser's console.
