### ISSUE TITLE
Screen share not working in 1:1 call (native call)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#23808]
### Steps to reproduce

1. Have a 1:1 with Alfie
2. Try and share a window
3. No effect
4. Try and share whole screen
5. No effect
6. Alfie tries to share a window
7. No effect
8. Alfie tries to share whole screen
9. Get a weird black rectangle

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2022111801 Olm version: 3.2.12

### How did you install the app?

Internet

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by MrAnno** [comment]
I can reproduce the same with v1.11.15.

```
Call *** set screensharing enabled? true
rageshake.ts:73 Not using desktop capturer source
rageshake.ts:73 Getting screensharing stream using getDisplayMedia() screen:0:0
rageshake.ts:73 Call *** Failed to get screen-sharing stream: DOMException: Permission denied
```

**Comment by CodeAndWeb** [comment]
Same issue on macOS 13.

**Comment by Nougat-User** [comment]
Same problem on Win10 21H2 :'(

**Comment by Grant12311** [comment]
I can reproduce the same problem on Ubuntu 22.04 running with Wayland. When I click the button that normally opens the native prompt to select something to share, nothing happens.

**Comment by Grant12311** [comment]
It is my understanding that the web version is unaffected. Someone I was talking to was able to share her screen from the web version to me running natively. But I couldn't share to her. She was running Windows 10 or 11. Limited sample size for web but it's something.

**Comment by Grant12311** [comment]
I am also on 1.11.15 installed from the official Linux instructions. This issue did not happen until recently so it's probably a recent update.
