### ISSUE TITLE
Element shows "Decryption key withheld" when it wasn't

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#23803]
When Element Android (and other clients based on matrix-android-sdk2) gets an `m.room_key_request` for a key that it doesn't have, it sends an `m.room_key.withheld` message with a code of `m.unavailable` (see [implementation](https://github.com/vector-im/element-android/blob/75de805417ffea6cd2b1647e098d1d32f8e3f17b/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/IncomingKeyRequestManager.kt#L403)).

Having received the `m.unavailable` response, Element-web shows "Decryption key withheld", which is misleading at best.

**Comment by robertmx** [comment]
Well #23745 was S-Major, as were some of the related bug reports. If the the chat suddenly stops working completely it probably should not be considered a minor inconvenience. I mean the core functionality breaks irrevocably without user interaction and does not recover without "expert" technical assistance.

Therefore I think it is appropriate to upgrade to S-major.

**Comment by richvdh** [comment]
> Therefore I think it is appropriate to upgrade to S-major.

It's just a misleading error message; this issue does not cause "the chat suddenly stops working completely". You may be thinking of some of the other crypto bugs, tracked at https://github.com/vector-im/element-meta/issues/245.
