### ISSUE TITLE
Verification fails to start (intermittently) when there is no existing DM with the target user

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#23819]
### Steps to reproduce

1. Share a room, but not a DM with target user
2. Open target user's details and click "verify"

#### What did you expect?

Verification process starts correctly

#### What happened instead?

1. Target user receives invite to DM, but there are no messages in the room:
![image](https://user-images.githubusercontent.com/1389908/203543251-1cc7f469-5c51-4592-b7cc-89a2c77e6689.png)

2. Originating user sees an error in the DM:
![image](https://user-images.githubusercontent.com/1389908/203543344-6ce3059e-fb4a-4301-aec5-371108230bd6.png)

Clicking "resend" resumes the verification process.

### Operating system

Linux

### Browser information

Firefox

### URL for webapp

https://vdhtest.riot.sw1v.org/

### Application version

element v1.11.15

### Will you send logs?

Yes

**Comment by richvdh** [comment]
From the console (this does *not* appear in the rageshake for some reason; possibly because it's "uncaught in promise"):

```
12:04:35.378
Uncaught (in promise) Error: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.
    encryptEvent index.ts:2817
    encryptEventIfNeeded client.ts:4107
    encryptAndSendEvent client.ts:4003
    promise callback*encryptAndSendEvent client.ts:4002
    sendCompleteEvent client.ts:3988
    sendEvent client.ts:3914
    sendCompleted InRoomChannel.ts:33
    send InRoomChannel.ts:259
    sendRequest VerificationRequest.ts:456
    requestVerificationWithChannel index.ts:2318
    requestVerificationDM index.ts:2293
    requestVerificationDM client.ts:2031
    _ EncryptionPanel.tsx:115
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 11
    ne init.tsx:144
    68 index.ts:229
    68 index.ts:240
```

**Comment by richvdh** [comment]
related: https://github.com/vector-im/element-web/issues/18463

**Comment by richvdh** [comment]
PR was reverted by https://github.com/matrix-org/matrix-js-sdk/pull/2913

**Comment by t3chguy** [comment]
Fix caused develop to break, so got reverted
