### ISSUE TITLE
Add push-to-talk functionality like Discord

### ISSUE THREAD

**Issue by aliiririran** [vector-im/element-web#23829]
### Your use case

There is a push-to-talk option in Discord that, when enabled for calls, Whenever you release your hand from the button, the input sound stops, which is very suitable for gaming!

#Sorry that my writing is not normal, I wrote with a **translator**!(:!

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/5993 + https://github.com/vector-im/element-web/issues/15284
