### ISSUE TITLE
Unable to login after not accepting the new security string

### ISSUE THREAD

**Issue by DMRobertson** [vector-im/element-web#23820]
### Steps to reproduce

(Manually transferred from https://github.com/matrix-org/synapse/issues/14532 on behalf of @GentleRV)

After updating matrix to version 1.72+focal+1 after login I get the question for a security key
I did a full reset to create the key and copied it
Continue the login I needed to enter this key again and get wrong key.

### Outcome

After the latest update today I encounter problems with setting up the security key

First I have no idea WHY a securtity key is needed, the user has his/her password which is enough

### Homeserver

Two homeservers connected with HAPROXY to get one acces IPaddress, running Synapse

### Will you send logs?

No

**Comment by DMRobertson** [comment]
@GentleRV please can you let the Element Web team know

- which OS are you using,
- which version of Element are you using,
- how did you install Element,

and any other information they need to diagnose your problem.

**Comment by uhoreg** [comment]
> First I have no idea WHY a securtity key is needed, the user has his/her password which is enough

The security key is to protect the information needed for end-to-end encryption.  The server sees the user's password when they log in, but the point of end-to-end encryption is to prevent the server from being able to access it, so another key is needed.

**Comment by turt2live** [comment]
Closing due to lack of information. If this is still happening, please open a new issue with fresh reproduction steps.
