### ISSUE TITLE
Sent message lost after reload

### ISSUE THREAD

**Issue by arecvlohe** [vector-im/element-web#23839]
### Steps to reproduce

1. If I try to send a message in any channel, I'll see the check mark next to the message, but when I reload the browser there will be an error that the message was not sent

#### What did you expect?

The message to be sent. On reload of the browser I can see the message I sent.

#### What happened instead?

The message is not sent. On reload of the browser there is an error saying the message was not sent

### Operating system

macOS 11.6.8

### Browser information

Firefox 107.0 (64-bit)

### URL for webapp

https://app.element.io

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by arecvlohe** [comment]
Just sent a message around 2:38pm (14:38) CDT.  The event id from source is:

`"event_id": "$laPDoNJuyWVRxJPVVXJTSFwtcopzkfmopCvMNnNoKrv"`

Running the snippet of code above does give back some information to help with debugging.

```
{
  "mx_pending_events_!dBfQZxCoGVmSTujfiv:matrix.org": "[{\"type\":\"m.room.message\",\"content\":{\"org.matrix.msc1767.text\":\"https://keyoxide.org/865AB70C915CEC62F7DE8B4086B2353C52B80DCB\",\"body\":\"https://keyoxide.org/865AB70C915CEC62F7DE8B4086B2353C52B80DCB\",\"msgtype\":\"m.text\"},\"event_id\":\"$laPDoNJuyWVRxJPVVXJTSFwtcopzkfmopCvMNnNoKrv\",\"user_id\":\"@adamrecvlohe:matrix.org\",\"sender\":\"@adamrecvlohe:matrix.org\",\"room_id\":\"!dBfQZxCoGVmSTujfiv:matrix.org\",\"origin_server_ts\":1672256281748,\"txn_id\":\"m1672256281748.0\"}]"
}
```

Screen capture of the message:

<img width="1013" alt="Screen Shot 2022-12-28 at 2 43 37 PM" src="https://user-images.githubusercontent.com/9747933/209864363-f02b0d9d-e99c-4d53-a9fd-a47fdc4eb0e9.png">

Let me know if there is anything else I should do!

**Comment by MadLittleMods** [comment]
Thanks for the reproduction details @arecvlohe! It would also be good to send debug logs again in case we can spot any error on why the transaction didn't match up and clear the pending event.

For reference, I won't be looking into this and was just trying to collect enough information for Element Web developers to spot the root cause.

**Comment by arecvlohe** [comment]
I sent in some more debug logs to help with the diagnosis. If you need anything else let me know.

**Comment by arecvlohe** [comment]
I gave up on this. Just created a new account
