### ISSUE TITLE
"Export chat" feature doesn't respect 24-hours time format (forces AM / PM output) in plaintext mode

### ISSUE THREAD

**Issue by nekohayo** [vector-im/element-web#23838]
### Steps to reproduce

1. Click the room name at the top of the UI
2. "Export chat", choose plaintext format

#### What did you expect?

Output like this:

```
2022-11-15, 09:44:48 - bob left the room
2022-11-16, 22:59:22 - <jeff> alice: if you will need me to emergency smoke-test something with your branch this month?
2022-11-18, 08:28:16 - <alice> jeff: thanks, I've been testing with my xml from stable and finding a billion bugs.
```

#### What happened instead?

Hard-to-read (or to process) output like this:

```
2022-11-15, 9:44:48 a.m. - bob left the room
2022-11-16, 10:59:22 p.m. - jeff: alice: if you will need me to emergency smoke-test something with your branch this month?
2022-11-18, 8:28:16 a.m. - alice: jeff: thanks, I've been testing with my xml from stable and finding a billion bugs.
```

---

P.s.: the `<speaker username>` format that is part of my expected output style is explained in issue #23837

### Operating system

Fedora 37

### Browser information

Firefox 107

### URL for webapp

app.element.io

### Application version

Element version: 1.11.15, Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by jaydeep-radadiya** [comment]
Hello @uhoreg, @nekohayo 

Can I take up this issue?

**Comment by nekohayo** [comment]
Open source does not require permission for you to send patches / merge requests.

**Comment by uhoreg** [comment]
Some times it is a good idea to check before working on an issue, for example to see if someone else is already working on it, or if there are certain considerations that are relevant (e.g. design).  In this case, it looks pretty straightforward, and I don't think there are any complications.  But see also https://github.com/matrix-org/matrix-react-sdk/pull/9724 (which attempts to solve this, but forces 24-hour time, and hasn't had any response from the contributor).

**Comment by Priyam3955** [comment]
Hello @nekohayo , @uhoreg Can I take up this issue?

**Comment by nawarajshah** [comment]
i have made changes, and waiting for PR to be reviewed

**Comment by rashmitpankhania** [comment]
isnt the datetime format depends on user's locale
is the expectation from this issue to stick on one format i.e 2022-11-18, 08:28:16 ??

**Comment by t3chguy** [comment]
@rashmitpankhania check out Settings > Preferences > Displaying time

<img width="996" alt="image" src="https://user-images.githubusercontent.com/2403652/233005702-6bf0cdae-4429-4262-aacd-6aca5c3a7db5.png">
