### ISSUE TITLE
"People" metaspace shows favourite rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23849]
### Steps to reproduce

1. Click on "People" metaspace 

#### What did you expect?
See only people listed in the left panel

#### What happened instead?
See rooms under "Favourites" listed in the left panel

![Screenshot from 2022-11-28 09-56-04](https://user-images.githubusercontent.com/51663/204248792-e37e68cf-e377-416e-95f0-ecf72f460505.png)

### Browser information

Chromium 107.0.5304.121 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: cbf5c43ae79d-react-569a36493378-js-b318a77ecef1 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
fwiw, I'm unable to reproduce on https://develop.element.io/

The relevant code around that meta space is around `MetaSpace.People`,  specifically [`src/stores/spaces/SpaceStore.ts#L382-L410`](https://github.com/matrix-org/matrix-react-sdk/blob/ad090ac4cd28f0c51b410c1646317db02c71501f/src/stores/spaces/SpaceStore.ts#L382-L410)

**Comment by kittykat** [comment]
Haven't seen again since, so closing for now.
