### ISSUE TITLE
"Integration Manager: Kick" > "should kick the target" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23858]
https://cloud.cypress.io/projects/ppvnzg/runs/6365/test-results/2212d6c2-bfcb-417a-b0e8-18f356a03787

![Screenshot 2022-11-29 at 08-17-57 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/204539287-4e5cff97-7b93-4304-9663-f2ab5810e1f7.png)

**Comment by t3chguy** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/6391/test-results/731f3314-4f6d-49b9-819a-959b801d9632

**Comment by richvdh** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/7247/test-results/3daa9bd2-df2a-461e-9121-1dd080b5f720

**Comment by weeman1337** [comment]
Still flaky. Even worse with only one runner. Cypress tests take quite a while.
