### ISSUE TITLE
Message fails to send

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23862]
### Steps to reproduce

1. Type out a test message and hit send

#### What did you expect?
Message is sent

#### What happened instead?
Within 1 minute:

![Screenshot from 2022-11-29 14-15-00](https://user-images.githubusercontent.com/51663/204552409-b2066d1a-31d5-4988-a769-e729a4cef5f7.png)

![Screenshot from 2022-11-29 14-12-34](https://user-images.githubusercontent.com/51663/204552326-a73a2227-41e6-407a-af18-469447a25a04.png)

### Browser information

Chromium 107.0.5304.121 (Official Build) Arch Linux (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
matrix.org is having issues, the errors are on point.
