### ISSUE TITLE
Thread read receipts are pushed off screen in bubble leayout

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#23867]
### Steps to reproduce

1. Enable threads
2. Enable bubble layout
3. Open a thread
4. Resize the thread panel

#### What did you expect?

Everything should stay on the screen

#### What happened instead?

Read receipts are pushed off screen

![read](https://user-images.githubusercontent.com/6216686/204596339-92fe3d91-d647-45dc-9eab-2e70c58201f6.gif)

Related
- https://github.com/vector-im/element-web/issues/23569
- https://github.com/vector-im/element-web/issues/23576

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element Nightly version: 2022112801 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Will you send logs?

No

**Comment by gsouquet** [comment]
Merging into https://github.com/vector-im/element-web/issues/23569
