### ISSUE TITLE
File attachment does not works if path contains NON-ASCII symbols

### ISSUE THREAD

**Issue by shams00** [vector-im/element-web#23860]
### Steps to reproduce

> 1. Where are you starting? What can you see?

I'm in the chat with single user.

> What do you click?

I do:
- click "attach" button
- select file, for example "/shams/temp/тест\ тест/Предложение\ по\ изменению.drawio"
- click "open"

#### What did you expect?

I expect file to be sent.

#### What happened instead?

I see:
![Screenshot_20221129_163302](https://user-images.githubusercontent.com/1482093/204542383-6956b363-9fc0-4364-a9b9-34d52e293c67.png)

File is not sent.

### Operating system

Manjaro Linux 

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

From official repository of Manjaro Linux

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is likely specific to the Manjaro package which isn't 1st party, I suggest reaching out there

**Comment by shams00** [comment]
I can't try deb package, but I have tried the flatpak one. The version from flatpack was Element version: 1.11.15
Olm version: 3.2.12. The behavior is the same. "0B" in upload dialog and "Upload failed" after pressing "Upload" for files having non-ascii symbols in path.

After installing flatpak version I additionally ran these commands:
# flatpak override im.riot.Riot --filesystem=host --user
# sudo flatpak override im.riot.Riot --filesystem=host

**Comment by shams00** [comment]
Running Element with command `env LC_ALL=C.UTF-8 /usr/bin/element-desktop %u` have fixed the issue.

**Comment by t3chguy** [comment]
@shams00 are you able to open an issue with the Manjaro package to suggest they do that upstream?

**Comment by shams00** [comment]
> @shams00 are you able to open an issue with the Manjaro package to suggest they do that upstream?

This is my first report to Manjaro/Arch but it seems to work: https://bugs.archlinux.org/task/76871

**Comment by blockisec** [comment]
getting this on element debian official repo package when attachment name contains chars like "ä", "ö" or "ü".
