### ISSUE TITLE
[Rich text editor] Pasting picture from the clipboard didn't work

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#23870]
### Steps to reproduce

I activated the Rich Text Editor from the Labs.

When I try to paste a picture from the clipboard, nothing get inserted.

#### What did you expect?
The Picture get pasted
(Like with the "old" Editor)
#### What happened instead?
nothing

### Operating system

Ubuntu Mate 22.04

### Application version

Version von Element: 1.11.15 Version von Olm: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by alunturner** [comment]
Fixed as of PRs:

- [rich text mode implementation](https://github.com/matrix-org/matrix-react-sdk/pull/11049)
- [plain text mode implementation ](https://github.com/matrix-org/matrix-react-sdk/pull/11056)
