### ISSUE TITLE
Messages/images upload failed

### ISSUE THREAD

**Issue by hoowwshii** [vector-im/element-web#23886]
### Steps to reproduce

 1. I am just sending messages/uploading photos, but often it fails. It takes 3-4 times before I can send my message/photo
    ![](https://user-images.githubusercontent.com/68774737/205195814-d8bb04c7-067b-490e-8764-77dbc0ba5cb1.png)
 1. And the worst part is that when I click resend at my message, a single line/word can be split up into many parts. For example, I originally typed `bener` and it was split up to:
    ```
    be
    ne
    r
    ```
    ![](https://user-images.githubusercontent.com/68774737/205198929-1b9e6af9-5f8e-4b77-acb1-20085976173f.png)

#### What did you expect?

The message should send correctly as expected

### Operating system

Windows 10

### Browser information

Firefox v107.0.1

### URL for webapp

app.element.io

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The log is full of networking errors, either you or matrix.org were having issues.

```
2022-12-02T02:11:20.960Z E Failed to get URL preview: ConnectionError: fetch failed: NetworkError when attempting to fetch resource.
2022-12-02T02:11:20.961Z E Failed to get URL preview: ConnectionError: fetch failed: NetworkError when attempting to fetch resource.
2022-12-02T02:11:21.024Z I checkForPreJoinUISI: did not find pre-join UISI
2022-12-02T02:11:21.092Z E Failed to get URL preview: ConnectionError: fetch failed: NetworkError when attempting to fetch resource.
2022-12-02T02:12:20.730Z E /sync error %s fetch failed: NetworkError when attempting to fetch resource.
s@https://app.element.io/bundles/a6ee55915aa181396f61/vendors~init.js:2:1212234
requestOtherUrl@https://app.element.io/bundles/a6ee55915aa181396f61/vendors~init.js:2:3569966
```

**Comment by hoowwshii** [comment]
> 

idk man, i tried on two different network, i even thought it was my isp, i tried with vpn, same result tho. if that so, i think the problem might be matrix.org. thank you for figuring this out.

**Comment by aliasaadi1714-coder** [comment]
Element account problem on both web and app versions 
Messages are sent but photos are not sent along with sending voice messages 
Only confirms access via recovery code from one device
For other devices, a message is displayed stating that the data has been verified, but it still considers the devices unknown
Previous messages are encrypted and cannot be seen unless the device is verified and granted access
What can be done about this problem?
