### ISSUE TITLE
Receiving a mention in an encrypted "Mentions Only" room does not highlight the room red

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23885]
### Steps to reproduce

1. Be in a room with 3+ people in it (including yourself)
2. Set the room's notification level to "Mentions Only"
3. Enable encryption
4. Get pinged while the room isn't active

#### What did you expect?

For the room to be highlighted red and decorated accordingly.

#### What happened instead?

I got the notification sound, but the message appeared in the room list as "bold" (dot, no count). It should have been red with a count.

### Operating system

Windows 10

### Application version

Nightly (2022-12-01)

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
confirmed to *not* affect the current staging.element.io deployment

**Comment by t3chguy** [comment]
Release blocker for for 1.11.17
