### ISSUE TITLE
Rich Text: main room composer steals focus from thread composer

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#23888]
### Steps to reproduce

0. Rich Text Editor labs flag enabled
1. In a room with a thread in the right-hand panel
2. Type a message and press Enter to send
3. Notice where the cursor goes

#### What did you expect?

I expected the cursor to stay in the thread composer

#### What happened instead?

The cursor jumped to the main room composer

### Operating system

Ubuntu 22.04

### Browser information

Firefox 106.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 003fc7cdf41b-react-1f703b8898c6-js-3870e3395d0c Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by florianduros** [comment]
Duplicate of #23755
