### ISSUE TITLE
Unable to demote myself in a space.

### ISSUE THREAD

**Issue by viasux** [vector-im/element-web#23882]
### Steps to reproduce

1. Give an alt account administrator in your space
2. Try to demote alt account (from the alt account)
3. The dialogue is greyed out

#### What did you expect?
I expected to be able to demote myself.
#### What happened instead?
I could not demote myself.

### Operating system

Windows

### Browser information

Librewolf 107.0-1

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Homeserver

the-apothecary.club

### Will you send logs?

No

My alt account I'm trying to demote is the @averythefurry:matrix.org one.
![image](https://user-images.githubusercontent.com/47131867/204997228-31c7eca0-df74-4bbb-90bf-d0da624949a6.png)

**Comment by t3chguy** [comment]
You can via the right panel member list

**Comment by viasux** [comment]
> You can via the right panel member list

I can't think of a reason this should be limited to only that instance of showing modifiable user power levels. Why not add it to the larger, more prominent screen that you can already modify some users' power levels on?

**Comment by t3chguy** [comment]
It was a bug. It has been fixed. Will be released in 1.11.17.
