### ISSUE TITLE
WYSIWYG editor doesn't support autocomplete or slash commands

### ISSUE THREAD

**Issue by paboum** [vector-im/element-web#23880]
### Steps to reproduce

1. Add `"show_labs_settings": true` to `config.json` (either web or Desktop)
2. Enable "Try out the rich text editor (plain text mode coming soon)"
3. Type `/dev` in any room.

#### What did you expect?
A list of commands available to pop up, with `/devtools` as the prime example.

#### What happened instead?
Nothing.

I believe it's easy enough to reproduce so you don't need logs. Otherwise, just tell me.

### Application version

element web 1.11.15

### Will you send logs?

No

**Comment by andybalaam** [comment]
This is expected - the feature is still under development and slash commands have not yet been implemented.

**Comment by t3chguy** [comment]
@andybalaam this issue is an Enhancement request

**Comment by andybalaam** [comment]
Fine to leave it but it might be more valuable in the https://github.com/matrix-org/matrix-rich-text-editor/ project?

**Comment by t3chguy** [comment]
They'd just keep getting re-opened here as users won't know to search in a different project

https://github.com/vector-im/element-web/issues?q=is%3Aopen+label%3AA-Rich-Text-Editor+sort%3Aupdated-desc has multiple issues of the same style

+ Lack of bullet lists
+ Lack of emoji picker
+ Lack of editing via arrows
+ Pasting files

So we should either keep or move them all

**Comment by andybalaam** [comment]
Cool well if leaving them avoids people constantly re-creating them I guess we leave them, and we'll have to try to make sure to close them when the relevant issue in the other is closed.

**Comment by paboum** [comment]
> users won't know to search in a different project
This could be mitigated by providing an architecture overview displayed somewhere near "New Isssue" button or a bot automatically moving the issues based on keywords. I've been using the product for some months, using github for a few years now and still cannot get a good grasp of which goes where.

**Comment by t3chguy** [comment]
Automatically moving issues is all well and good but that just creates duplicates that someone has to manually clean up.

**Comment by Thatoo** [comment]
So this issue is also a reminder to add the ability  to ping users with "@someone" to this new Rich text editor.

**Comment by paboum** [comment]
Since it's tracked elsewhere, I agree to close this ticket.
