### ISSUE TITLE
Screen Sharing doesn't work after the update to 1.11.15

### ISSUE THREAD

**Issue by notshriram** [vector-im/element-web#23896]
### Steps to reproduce

1. Where are you starting? What can you see?
When I do a 1 on 1 voice call with anyone and I try to share my screen. Once the call is connected, I can see the available screens to share but when I select a screen and click the share button, the modal disappears but it doesn't start sharing anything

2. What do you click?
I click the screen I want to share, in the modal and then I click the share button

#### What did you expect?
I expected the screen to start sharing like it did before the update to 1.11.15. I don't remember what version I was using previously.

#### What happened instead?
The screen share modal just disappears without starting the share
![image](https://user-images.githubusercontent.com/49370927/205421931-41612839-206e-4d65-b67c-ad09a9bf4556.png)

### Operating system

macOS, Ubuntu

### Application version

Element Version 1.11.15 (1.11.15), olm 3.2.12

### How did you install the app?

homebrew on macOS

### Homeserver

Synapse https://github.com/spantaleev/matrix-docker-ansible-deploy

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
This is fixed in the next version which is coming soon!

**Comment by MadLittleMods** [comment]
@SimonBrandner Can you share a link for the PR fix and canonical issue that I assume was tracking it before?
