### ISSUE TITLE
Some Japanese characters are printed oddly

### ISSUE THREAD

**Issue by tsawada** [vector-im/element-web#23899]
### Steps to reproduce

1. send a text that contains "の" (a Japanese character)

#### What did you expect?
The glyph of "の" is displayed as the same style as other Japanese characters.

![good](https://user-images.githubusercontent.com/1198544/205488434-6f14610b-c69b-4a27-a65a-b067d3a31b9d.png)

#### What happened instead?
The glyph of "の" look different from other Japanese characters.
If I try to simulate this in English: ţexţ looks like ţhis.

![bad](https://user-images.githubusercontent.com/1198544/205488399-0196e072-8112-4f1b-8ff8-d5c11624f1e9.png)

I figured out that this glyph is coming from STIXGeneral font, which somehow contains a glyph for "の" but not for other characters (there could be more). I'm not sure if STIX intentionally included "の".

### Operating system

macOS

### Browser information

Google Chrome, latest

### URL for webapp

app.element.io

### Application version

Element version: 1.11.15 Olm version: 3.2.12

### Will you send logs?

No

**Comment by tsawada** [comment]
I am no expert in the topic but my understanding is that [STIXGeneral is deprecated](https://github.com/stipub/stixfonts/blob/f120869ef6853e187514917dc8c2b99adfded140/FONTLOG.txt#L1212), and should be replaced with STIX Two or other fonts.
On my browser, Element seems to refer STIXGeneral in [theme-dark.css](https://app.element.io/bundles/a6ee55915aa181396f61/theme-dark.css) (similar for the light theme as well) but I can't find relevant location in the source tree.

**Comment by robintown** [comment]
This would be because Japanese characters are supposed to fall back to `sans-serif`, but [STIXGeneral is prioritized over `sans-serif`](https://github.com/matrix-org/matrix-react-sdk/blob/8e719d57a2ca09787f415b9eabb937ffe857f4c0/res/themes/light/css/_light.pcss#L17). I would expect the order to be the other way around.

**Comment by robintown** [comment]
This is apparently still an issue on some font stack + browser combinations. We probably need to remove STIXGeneral from the font list entirely, since it's doing exactly this: https://github.com/matrix-org/matrix-react-sdk/pull/8687#issuecomment-1137296914
