### ISSUE TITLE
Add Element Call to HS `well-known`

### ISSUE THREAD

**Issue by korneyda** [vector-im/element-web#23905]
#### What would you like to do?
Please add the option to specify your setting for Element Call, similar to jitsi

https://github.com/vector-im/element-web/blob/develop/docs/jitsi.md
```
/.well-known/matrix/client
{
  "im.vector.riot.jitsi": {
    "preferredDomain": "your.jitsi.example.org"
  }
}
```
#### Why would you like to do it?

For centralized management

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/blob/develop/docs/config.md#voip--jitsi-calls `element_call` currently only configurable in config.json

**Comment by korneyda** [comment]
_in config.json_
This makes it impossible to use centralized management for all users of my matrix server, unlike jitsi in /.well-known/matrix/client

**Comment by korneyda** [comment]
In my opinion, it is necessary to do this, because there is no way to specify in config.json this parameter for each user.

**Comment by robintown** [comment]
As @dbkr has explained, this is undesirable from a security perspective. We are however very much open to https://github.com/vector-im/element-web/issues/23908.

**Comment by raphaelbadawi** [comment]
Excuse me but it seems we can actually make the Call URL discoverable for Element X (using .well-known/element/element.json). **So this really doesn't make any sense we can't do it for Element Legacy**. Our users using X end up in rooms hosted in our Call instance, but users using Legacy desktop app end up on the SaaS instance, which doesn't make any sense.
