### ISSUE TITLE
Invite error: unknow server error

### ISSUE THREAD

**Issue by Himbeersternchen** [vector-im/element-web#23918]
### Steps to reproduce

I was trying to invite people into a chat room. But error was occured with 'unknown server error'. I use the matrix homeserver, so do the people whom i have invited. It does not have problem if i invite people into chatroom with the element app on my phone (ios).

### Outcome

I expect that I can invite people in to chatroom. And this worked today morning.

### Operating system

ubuntu 18.04

### Browser information

chrome, firefox

### Application version

Version von Element: 1.11.3 Version von Olm: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
You need to send logs from within the app. Settings > Help & About > Submit debug logs.

**Comment by Himbeersternchen** [comment]
> You need to send logs from within the app. Settings > Help & About > Submit debug logs.

Hi t3chguy, thanks for your help. I have received a update on web and updated it. And now it works again! :)
