### ISSUE TITLE
Read Receipt of the user is not set to the message this user sent

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-web#23915]
### Steps to reproduce

1. UserA: Send some messages to the thread
2. UserB: read this messages. Result - RR(Read Receipt) is moved to the last message
3. UserB: send message to the same thread

### Outcome

Expected result: UserA sees RR of UserB over message UserB just send (the last message in a thread)
Actual result: UserA sees RR of UserB over the last message of UserA (as before UserB sent his message)

### Operating system

macOS

### Application version

Version 1.11.15 (1.11.15)

### How did you install the app?

from element website

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is fixed on develop, and will be in today's release
