### ISSUE TITLE
Add thread messages to message preview in room list and prepend with the thread icon

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#23920]
### Your use case

Add threads messages to the message previews in the room list, prepend the thread message with the thread icon (similar to the screenshot below)

<img width="366" alt="Screenshot 2022-12-15 at 10 37 27" src="https://user-images.githubusercontent.com/89144281/207837923-d7fe9504-1bf6-4c67-b0d1-ce4d30108a83.png">

**Comment by weeman1337** [comment]
@daniellekirkwood @janogarcia a per design the preview should only display message from „My Threads“. I've currently implemented the thread message preview (without design yet) and it may be confusing:

![image](https://user-images.githubusercontent.com/6216686/231719675-dba65da8-cb7d-4e80-9582-a9085e36aa81.png)

![image](https://user-images.githubusercontent.com/6216686/231720324-5f604222-0a7b-4ced-829c-308fa3c15778.png)

- You get a notification count of 1 (1) from a message in a thread where you don't participate
- The message preview shows the last message from a thread where you participate

To me it feels like a bug not to see the message causing the unread notification in the room list.

**Comment by daniellekirkwood** [comment]
thanks @weeman1337 - I agree.

while we're still in the state that al threads messages send you a notification, I think we should show all thread messages in the room list

Jano is on vacation so let's go with all messages in the room list for now and update this when we get to updating threads only sending notifications on "your messages"
