### ISSUE TITLE
Replying to root message in thread causes right panel to go blank

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23934]
### Steps to reproduce

1. Go to #publicencryptedroom:matrix.org and post a message
2. Click the thread button in the main timeline
3. In the right panel, click the reply button

#### What did you expect?
Can reply to message

#### What happened instead?
Root message vanishes from right panel and it looks empty. If I try to start a thread from that message now, the room message never shows in the right panel.

![Screenshot from 2022-12-07 16-03-55](https://user-images.githubusercontent.com/51663/206229458-b76696a4-1066-4ae8-9293-60dec04aef18.png)

[Screencast from 2022-12-07 16-09-45.webm](https://user-images.githubusercontent.com/51663/206230922-c4e48f6c-e891-48cf-b83a-d91d42a3cc44.webm)

### Browser information

Chromium 108.0.5359.94 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: c473cb6-react-c3809d3afa7d-js-8d018f9c2d33 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by justjanne** [comment]
Fixed  by https://github.com/matrix-org/matrix-js-sdk/pull/2965
