### ISSUE TITLE
Certain rooms in room directory cannot be joined.

### ISSUE THREAD

**Issue by daedric7** [vector-im/element-web#23937]
### Steps to reproduce

1. Click top search bar
2. Select Rooms
3. Change current server to Libera.chat
4. Type "Mastodon" and wait for the result
5. Click Join

#### What did you expect?

The usual joining (even if slow and with errors) of the room.

#### What happened instead?

Instant error: 

Failed to join

MatrixError: [404] Can't join remote room because no servers that are in the room have been provided. (https://aguiarvieira.pt/_matrix/client/r0/join/!QVGzddUWpPdvanbeBp%3Alibera.chat)

### Operating system

Ubuntu running on a Oracle Free Arm.

### Application version

versão do Element: 1.11.16 Olm version: 3.2.12

### How did you install the app?

Oficial element webpage

### Homeserver

aguiarvieira.pt

### Will you send logs?

Yes

**Comment by daedric7** [comment]
result of docker compose logs right after attempting to join the room:

```
matrix-postgres  | 2022-12-07 22:29:43.759 UTC [36] ERROR:  could not serialize access due to concurrent update
matrix-postgres  | 2022-12-07 22:29:43.759 UTC [36] STATEMENT:  INSERT INTO account_data (user_id, account_data_type, stream_id, content) VALUES ('@daedric:aguiarvieira.pt', 'im.vector.web.settings', 10141, '{"MessageComposerInput.insertTrailingColon":true,"deviceClientInformationOptIn":true,"SpotlightSearch.recentSearches":["!QVGzddUWpPdvanbeBp:libera.chat","!dfclKzOduGNuyuRPZU:libera.chat","!DQJVniaSzEOMrvVSsB:aguiarvieira.pt","!uXvvbgIhuFMCGAIeRR:maunium.net","!rhzvpsUPIYocutzXMf:midov.pl","!CJLYyMYkwPyraCvrRu:midov.pl","!UeTeyNedDrjNKNBMNq:anontier.nl","!EDOCKtRwqSlfrROnqI:libera.chat","!SzcRUxcpYurpoctOzk:matrix.org","!ibrWVedlXMAAFnhIub:matrix.org"],"breadcrumbs":true,"room_directory_servers":["midov.pl","maunium.net"],"Images.size":"large","Spaces.allRoomsInHome":true,"autoplayGifs":true,"autoplayVideo":true,"MessageComposerInput.autoReplaceEmoji":true,"enableSyntaxHighlightLanguageDetection":true,"Spaces.enabledMetaSpaces":{"home-space":true,"people-space":true,"favourites-space":true,"orphans-space":true}}') ON CONFLICT (user_id, account_data_type)  DO UPDATE SET stream_id=EXCLUDED.stream_id, content=EXCLUDED.content
matrix-synapse   | 2022-12-07 22:29:43,760 - synapse.storage.txn - 717 - WARNING - PUT-219506 - [TXN OPERROR] {add_user_account_data-125b14} could not serialize access due to concurrent update
matrix-synapse   |  0/5
```

**Comment by richvdh** [comment]
I was able to repeat this. E-W sent a /join request: `POST https://matrix.sw1v.org/_matrix/client/r0/join/!QVGzddUWpPdvanbeBp%3Alibera.chat` with a body of `{}`. Note the absence of server name in the request.

Synapse logs:

```
2022-12-07 22:12:49,013 - synapse.http.server - 108 - INFO - POST-1331 - <XForwardedForRequest at 0x7f9161d57898 method='POST' uri='/_matrix/client/r0/join/!QVGzddUWpPdvanbeBp%3Alibera.chat' clientproto='HTTP/1.0' site='8008'> SynapseError: 404 - Can't join remote room because no servers that are in the room have been provided.
2022-12-07 22:12:49,019 - synapse.access.http.8008 - 481 - INFO - POST-1331 - 2001:8b0:ba7a:e98f:4ddd:69b1:9dd:7564 - 8008 - {@richvdh:sw1v.org} Processed request: 0.007sec/0.006sec (0.006sec, 0.000sec) (0.001sec/0.003sec/4) 116B 404 "POST /_matrix/client/r0/join/!QVGzddUWpPdvanbeBp%3Alibera.chat HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element-Nightly/2022112501 Chrome/106.0.5249.181 Electron/21.3.0 Safari/537.36" [0 dbevts]
```

**Comment by richvdh** [comment]
(I suspect this is not limited to `libera.chat`)

**Comment by richvdh** [comment]
Good question I guess, though I'm pretty sure the intention of the federation `/publicRooms` API is that servers should not return rooms they have left.

I've raised https://github.com/matrix-org/matrix-spec/issues/1375 to track the clarification anyway.

**Comment by t3chguy** [comment]
Blocked on spec clarification

**Comment by 0xb1b1** [comment]
Can reproduce. Error details below:

Error message box
```
MatrixError: [404] Can't join remote room because no servers that are in the room have been provided. (https://synapse.seizure.icu/_matrix/client/r0/join/!JlytvgrOTrGPXOfjrK%3Atechlore.net)
```

Room: Techlore - Main (!JlytvgrOTrGPXOfjrK:techlore.net) (found on matrix.org homeserver)

**Comment by 0xb1b1** [comment]
Can reproduce. Error details below:

Error message box
```
MatrixError: [404] Can't join remote room because no servers that are in the room have been provided. (https://[redacted]/_matrix/client/r0/join/!JlytvgrOTrGPXOfjrK%3Atechlore.net)
```

Room: Techlore - Main (!JlytvgrOTrGPXOfjrK:techlore.net) (found on matrix.org homeserver)

Deployment details:
Platform: Docker / GNU/Linux NixOS 22.05
Version: matrixdotorg/synapse:v1.75.0 + postgres:alpine3.15
Proxy: Traefik

*Some* rooms are not "joinable", others (for example, #spitetech:matrix.org) are working fine.

**Comment by JeanPaulLucien** [comment]
I tried to add server `libera.chat`. About 30s was "Can't find this server or...".
Element Desktop 1.11.22; Homeserver: matrix.org

**Comment by JeanPaulLucien** [comment]
I tried to reproduce. I found this room. Joined. **Not confirm.**
Element Desktop 1.11.22; Homeserver: matrix.org.

**Comment by JeanPaulLucien** [comment]
> Room: Techlore - Main (!JlytvgrOTrGPXOfjrK:techlore.net) (found on matrix.org homeserver)

I tried to add this server to my server list. I suppose this server does not exitst. So, it's correct 404.

**Comment by Happyfeet01** [comment]
Can reproduce:

`MatrixError: [404] Can't join remote room because no servers that are in the room have been provided. (https://matrix.fulda.social/_matrix/client/r0/join/!PukFFdIcHgtaaHZflT%3Adevture.com)`

Room Name: Docker + Ansible = Matrix

System: Docker / Debian 11
Synapse 1.76.0
Proxy: Nginx

**Comment by JeanPaulLucien** [comment]
Meanwhile Matrix's Synapse side has started to suspect something: https://github.com/matrix-org/synapse/issues/15115

**Comment by t3chguy** [comment]
Given this is biting more people, moving ahead with a fix which assumes https://github.com/matrix-org/matrix-spec/issues/1375 will result in a spec clarification stating that servers must not return rooms they cannot facilitate a join to
