### ISSUE TITLE
Account backup not triggered after login

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23931]
### Steps to reproduce

1. Login to your account
2. Verify your session
3. ... none of your messages are decrypted

#### What did you expect?

For all of my messages to be decrypted

#### What happened instead?

I need to manually go and click restore from backup on my account settings, and enter my security key, even though I have just cross-signed and have already implicitely entered my security key.

### Operating system

*No response*

### Browser information

*No response*

### URL for webapp

*No response*

### Application version

*No response*

### Homeserver

*No response*

### Will you send logs?

No

**Comment by richvdh** [comment]
I wasn't able to reproduce this. Possible it was just slow (https://github.com/vector-im/element-meta/issues/757), but in the absence of logs or more recent reports, I'm going to close it for now.
