### ISSUE TITLE
Triage CI broken for Delight and Product/Design

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23938]
Examples:
* https://github.com/vector-im/element-web/actions/runs/3643764337
* https://github.com/vector-im/element-web/actions/runs/3643764336
* https://github.com/vector-im/element-web/actions/runs/3643748369
* https://github.com/vector-im/element-web/actions/runs/3643748370
* https://github.com/vector-im/element-web/actions/runs/3643738563
* https://github.com/vector-im/element-web/actions/runs/3643738548
* https://github.com/vector-im/element-web/actions/runs/3643738535
* https://github.com/vector-im/element-web/actions/runs/3643703797

**Comment by kittykat** [comment]
GitHub has updated project board IDs so they need to be reflected in the automation scripts

**Comment by gsouquet** [comment]
Fixed by https://github.com/vector-im/element-web/pull/23943
