### ISSUE TITLE
Threaded message reply doesn't appear in right panel but does in timeline

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23932]
### Steps to reproduce

1. See a threaded message in the main timeline
2. Click on it to open right panel
3. See new message arrive in the main timeline but not in the right panel

#### What did you expect?
Right panel and timeline update at the same time

#### What happened instead?
Timeline is updating but right panel is not

In the inspector:
![Screenshot from 2022-12-07 15-14-17](https://user-images.githubusercontent.com/51663/206218749-cca88b61-254e-439d-8073-20cab03bb174.png)

### Browser information

Chromium 108.0.5359.94 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: c473cb6e773f-react-c3809d3afa7d-js-8d018f9c2d33 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by justjanne** [comment]
This issue is likely fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2951, but I couldn't reproduce it reliably. If you could, please try to reproduce it again

**Comment by kittykat** [comment]
Seems to be resolved now
