### ISSUE TITLE
Linux: drag and drop of files doesn't work.

### ISSUE THREAD

**Issue by et-the-extra-terrestrial** [vector-im/element-web#23945]
### Steps to reproduce

1. Where are you starting? What can you see?

When i try to drag and drop a file from my folders into a chat room, a broken thumbnail appears and it says the file is 0 kb.
![Capture d’écran du 2022-12-08 09-55-15](https://user-images.githubusercontent.com/108896421/206478768-f5e7add3-f29b-4312-943f-cf8e6d61eef1.png)

#### What did you expect?

That the file will join itself properly

#### What happened instead?

Impossible to send files from drag and drop

### Operating system

Linux Mint

### Application version

1.11.16

### How did you install the app?

Software center

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
![2022-12-08_19-03](https://user-images.githubusercontent.com/25768714/206530401-aae92e0d-81ec-4a39-b1b4-e7c1e239813d.png)

It works fine for me on Debian Bookworm

**Comment by itsrachelfish** [comment]
@SimonBrandner I installed Element using Flatpak on this system. I never had this problem on other computers when I installed element using a .deb file. Perhaps Flatpak is the root cause of the issue here?

It's also worth noting that I'm not using Wayland. When I tried to run element in Wayland mode it segfaulted.

```

flatpak run im.riot.Riot --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland
/home/rachel/.var/app/im.riot.Riot/config/Element exists: yes
/home/rachel/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:1208/104353.840796:ERROR:wayland_connection.cc(218)] Failed to connect to Wayland display: No such file or directory (2)
[3:1208/104353.840827:ERROR:ozone_platform_wayland.cc(220)] Failed to initialize Wayland platform
[3:1208/104353.840832:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
/app/bin/element: line 10:     3 Segmentation fault      (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

**Comment by SimonBrandner** [comment]
> Perhaps Flatpak is the root cause of the issue here?

Sounds possible, @et-the-extra-terrestrial, are you also using the Flatpak version?

**Comment by itsrachelfish** [comment]
Here's a screen recording of the issue. You can see that both individual files and groups of files don't work for me


https://user-images.githubusercontent.com/1670549/206538769-e32a24a7-5b61-4f34-9aa2-49f1d7ffaf5f.mp4

**Comment by SimonBrandner** [comment]
Since this seems to be a Flatpak issue, I would recommend opening an issue at https://github.com/flathub/im.riot.Riot since the Flatpak version isn't officially supported. If you discover this happens with non-Flatpak versions too, let us know!
