### ISSUE TITLE
Kat's new session on develop missing so many decryption keys

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23940]
### Steps to reproduce

1. Log out of develop
2. Log back in
3. Verify session against app.element.io
4. See Android, iOS and app.element.io continuing to ask to verify the develop session
5. See develop session marked as verified in settings
6. Keys to old messeges are slow to arrive, even after 24h most are missing

#### What did you expect?
The app is usable

#### What happened instead?
The app is not usable because I can't read most of my old messages

### Browser information

Chromium 108.0.5359.94 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: c473cb6e773f-react-c3809d3afa7d-js-8d018f9c2d33 Olm version: 3.2.12 and yesterday's

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by uhoreg** [comment]
From the rageshakes, it looks like your new device for some reason isn't recognizing your cross-signing key, so it cannot check the signature on your backup.  What does it show in your "Security & Privacy" settings, under the "Cross-signing" section?

If you log in a new session, does the same thing happen?

**Comment by kittykat** [comment]
@uhoreg :

![Screenshot from 2022-12-13 11-06-42](https://user-images.githubusercontent.com/51663/207301817-256a8886-5c32-457c-b9ab-31ba4d95f875.png)

**Comment by kittykat** [comment]
I've tried a new session in a private browsing window, but I've gotten most of the keys relatively quickly on that one. Rageshake is above, just in case.

**Comment by uhoreg** [comment]
Your new session looks fine.  Was your screenshot in https://github.com/vector-im/element-web/issues/23940#issuecomment-1348203101 from your session that wasn't getting the decryption keys?

**Comment by kittykat** [comment]
@uhoreg Yes, screenshot was from the original problem session that wasn't getting keys. I've still got that session running if you need anything else from me.

**Comment by uhoreg** [comment]
Kat, can you do another rageshake from that device?  Your screenshot doesn't match what I would have expected based on your previous rageshakes, and I'm wondering if something changed in the client, or something else strange is going on.

**Comment by richvdh** [comment]
@kittykat is this still a problem for you? I'm not sure we're going to be able to do much with it now that so much time has gone by.

**Comment by kittykat** [comment]
Not with this specific session and I didn't have a problem with other new sessions
