### ISSUE TITLE
An error when trying to add a phone number to the profile

### ISSUE THREAD

**Issue by Stvad** [vector-im/element-web#23941]
### Steps to reproduce

Go to general settings and try to add number (I'm adding a US number in case it's relevant)

#### What did you expect?

Number is added to the profile (or confirmation message is sent to me /etc)

#### What happened instead?

I get the following error:
> MatrixError: [500] Internal Server Error (https://matrix-client.matrix.org/_matrix/client/r0/account/3pid/msisdn/requestToken) (Status 500)

<img width="755" alt="image" src="https://user-images.githubusercontent.com/81347/206434211-74eec548-f75c-4140-bd7d-106929532284.png">

---
I also get 500 error when trying to add the phone via Android app (though it does not provide details)

### Operating system

macOS

### Application version

Element version: 1.11.16 Olm version: 3.2.12

### How did you install the app?

brew

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by aaronraimist** [comment]
Matrix.org/vector.im disabled phone number verification so that is expected.

Here is the issue for showing a better error message: https://github.com/vector-im/element-meta/issues/766
