### ISSUE TITLE
The thread reply count from the thread panel and the main room panel disagree

### ISSUE THREAD

**Issue by Yoric** [vector-im/element-web#23952]
### Steps to reproduce

During the past few days, I've noticed several times discrepancies between the thread panel and the main room panel.

In the screenshot below, the main room panel shows that there are 4 thread responses (which is correct), so there should be a total of 5 messages in the thread. The thread panel only shows 3 messages, i.e. two responses.

![Screenshot from 2022-12-09 15-37-22](https://user-images.githubusercontent.com/10190/206728307-04bb1c08-3f42-4861-bf4a-19850e00c029.png)

This is the source code of an event that wasn't displayed:

```jsonc
{
    "body": "> bla, bla, ba\n bla bla bla",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!CaXWQYnxLNfVirQPgQ:localhost:9999/$yUXRcUo4JwreG3fZZk8DGmrDzQV8_awfh_VZ6Kc1v_0\">In reply to</a> <a href=\"https://matrix.to/#/@witness:localhost:9999\">Bla bla bla</a><br>Bla bla bla</blockquote></mx-reply><ol>\n<li>Bla bla bla</li>\n</ol>\n",
    "m.relates_to": {
        "event_id": "$GmTpG-0ZHzJXMlLkMIo-Vzdydi_jYvekXmRTHOuz1-Q",// Confirmed, this is the root event of the thread.
        "is_falling_back": true,
        "m.in_reply_to": {
            "event_id": "$yUXRcUo4JwreG3fZZk8DGmrDzQV8_awfh_VZ6Kc1v_0"
        },
        "rel_type": "m.thread"
    },
    "msgtype": "m.notice",
    "org.matrix.msc1767.html": "Bla bla bla",
    "org.matrix.msc1767.text": "Bla bla bla"
}
```

### Outcome

I should have the same view on both panels.

### Application version

Element version: 1.11.16 Olm version: 3.2.12

### How did you install the app?

Ubuntu

### Homeserver

Synapse 1.75

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/23942

**Comment by justjanne** [comment]
I've been able to reliably reproduce this issue if messages were sent while element was running but disconnected, e.g., when running in background and the device was suspended or disconnected from WiFi.
