### ISSUE TITLE
Add speaking indications in voice calls

### ISSUE THREAD

**Issue by RealFascinated** [vector-im/element-web#23959]
#### What would you like to do?
Add speaking indications in voice calls

#### Why would you like to do it?
Having this feature would be useful to know when people are speaking

#### How would you like to achieve it?
When a user is speaking it will show a outline in on their profile picture in the voice chat window
Would be similar to Discords implementation of it

**Comment by SimonBrandner** [comment]
We previously had this but the design team deemed it to be too noisy (see https://github.com/vector-im/element-web/issues/19513), the Element Call integration should have this again in group calls

I am going to close this as the design team seems to be against this but if you wish to follow up on this I can tag them here for further discussion

**Comment by RealFascinated** [comment]
I quite like knowing when people are talking (dm or group calls). It would be nice to at least have a toggle for it since I find it very useful. It would be nice if you did bring it up again with the team. Thanks :)

**Comment by SimonBrandner** [comment]
The design team atm doesn't feel like the benefits outway the cons (the feature being quite distracting 1:1 calls), so we are not going to add this. In group calls we definitely are going to have this, you can already check out call.element.io

**Comment by RealFascinated** [comment]
I've had it multiple times that I am talking to myself as I don't know that my microphone isn't working. My friends are always having this issue all the time always. This feature would solve this issue.

**Comment by SimonBrandner** [comment]
I feel like this could be accomplished better by https://github.com/vector-im/element-web/issues/12647 for example or perhaps by adding some sort of audio indicator to the lobby view: what do you think about that?
