### ISSUE TITLE
Little oversight in russian localization

### ISSUE THREAD

**Issue by esdf-34** [vector-im/element-web#23961]
### Steps to reproduce

1. Changed language to russian
2. Went into an empty room
3. Hovered over video call and voice call

#### What did you expect?
"Здесь некому звонить"

#### What happened instead?
"There's no one here to call"

![1](https://user-images.githubusercontent.com/120260986/206913296-cd0be726-c348-43a1-83f2-8b849c34a985.png)

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Element is entirely translated by the community. If you want to help with the translations, you can do it at https://translate.element.io/. I would also recommend joining https://matrix.to/#/#element-translations:matrix.org
