### ISSUE TITLE
Thread list panel is missing recent thread that I participated in

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#23971]
### Steps to reproduce

1. Participate in a thread that someone else started on your own message
1. Come back a day later and try to see if there was any replies by opening the thread list panel in that room
1. Notice that the thread list is missing your thread you know exists
1. Thread still appears and is accessible from the main timeline

#### What did you expect?

All threads in room are listed in the thread list view (especially ones clearly visible in the main timeline)

#### What happened instead?

Thread missing from thread list view

Uncensored screenshot in [rageshake issue](https://github.com/matrix-org/element-web-rageshakes/issues/18315). But you can see that the thread is from 2022-12-08 while the most recent threads in the list are from September/November?
![](https://user-images.githubusercontent.com/558581/207160283-abf10b5d-8c43-4df8-895b-ab22851f5f83.png)

### Operating system

Windows 10

### Browser information

Chrome Version 108.0.5359.99

### URL for webapp

https://develop.element.io/

### Application version

Element version: 60d05f03a556-react-d835721ae1dd-js-4c5f416b329f Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes, https://github.com/matrix-org/element-web-rageshakes/issues/18315

**Comment by justjanne** [comment]
Could you try reproducing it again? When you reported the issue, you weren't using the latest threads changes from yesterday yet, those should have fixed the issue.

**Comment by thibaultamartin** [comment]
I've hit this issue too, on Element Nightly version: 2022121301. This occurred after switching from "All threads" to "My threads" and back
