### ISSUE TITLE
Changing thread filter to "My threads" make select disappear

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#23974]
### Steps to reproduce

1. Open the thread list
2. Select "My Threads" in the thread filter type

#### What did you expect?

To keep on seeing the select input

#### What happened instead?

It has dissapeared

### Will you send logs?

No

**Comment by robintown** [comment]
@gsouquet I'm not sure what this is referring to. Given it's marked as a good first issue, could you add more details?

**Comment by robintown** [comment]
See https://github.com/vector-im/element-web/issues/24040 which has more details
