### ISSUE TITLE
Hard crash: Error: Setting 'feature_thread' does not appear to be a setting.

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#23982]
### Steps to reproduce

1. Open develop.element.io

#### What did you expect?

Working app

#### What happened instead?

![image](https://user-images.githubusercontent.com/1374914/207379638-0c7978cd-7dd2-4d01-84c5-8d63a6141702.png)

### Operating system

Fedora Silverblue 37

### Browser information

Firefox 107.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Unknown

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9748

**Comment by MTRNord** [comment]
Thanks :) that was quick :D
