### ISSUE TITLE
option to unset active room and go to blank timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2398]
apparently TG has this

**Comment by Mikaela** [comment]
Screenshot of Telegram desktop from Searx image search. [Source](http://www.kdeblog.com/telegram-desktop-otro-cliente-de-telegram-para-linux.html)

![](http://www.kdeblog.com/wp-content/uploads/2014/08/telegam-desktop_02.png)

**Comment by Mikaela** [comment]
I wonder if this/ESC should go to room directory as that appears to be the default view when you login to Riot or if that screen should be this screen.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16691
