### ISSUE TITLE
SettingsStore value "feature_thread" unknown

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#23983]
### Steps to reproduce

Replace 

`if (!SettingsStore.getValue("feature_thread")) {`
here https://github.com/matrix-org/matrix-react-sdk/blob/2d2755d14542dd68b8318a88dda568a794ac5c81/src/Unread.ts#L69

by 

`if (!SettingsStore.getValue("feature_threadstable")) {`

### Outcome

Crash

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9748

**Comment by menturion** [comment]
The `BetaPill` should be removed as well here https://github.com/matrix-org/matrix-react-sdk/blob/2d2755d14542dd68b8318a88dda568a794ac5c81/src/components/structures/ThreadPanel.tsx#L276
