### ISSUE TITLE
Cannot see public room https://app.element.io/#/room/#sasjs:4gl.io

### ISSUE THREAD

**Issue by Catrins** [vector-im/element-web#23992]
### Steps to reproduce

1. Chrome Browser with URL after registration via GitHub or email
2. I get the following message(see picture)
![image](https://user-images.githubusercontent.com/28100886/207578353-3463171a-bdfc-4ced-9c2f-d01ab7170400.png)
3. I clicked rooms to find the public room
4. I cannot find the room

A collegue tried to connect and he is successfull at my computer and with Chrome browser. 
I can send messages to him, but I cannot send messages to a person in UK. It takes a long time, the system tries to create a room, but no success.

#### What happened instead?
Cannot see or find the public room. No conversation is possible to people, woh are not in this company.

### Operating system

Windows

### Browser information

Chromium 107.0.5304.107 

### URL for webapp

https://app.element.io/#/room/#sasjs:4gl.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Could you share logs? aka, a rageshake, you can do so by typing `/rageshake` in the message field and link it to this GitHub issue so that we can investigate the problem

**Comment by kittykat** [comment]
Hi @Catrins, thank you for taking the time to report the issue. Unfortunately we cannot investigate it unless you submit a rageshake shortly after you experience the problem and link the rageshake to this issue.

I'm going to close this issue for now, but if you do get a chance to attach the rageshake, please comment with `@kittykat` and I will reopen the issue for you :+1:
