### ISSUE TITLE
Stuck notifications: DM stuck as unread

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#23991]
### Steps to reproduce

1. Refresh the Element Web page

#### What did you expect?

My encrypted DM, which has no unread messages in it, is not marked as unread.

#### What happened instead?

This DM is marked as unread.

### Operating system

Ubuntu 22.04

### Browser information

Firefox 106.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: c4806b9c4fc7-react-aeb9f4373fff-js-b2a10e6db323 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
I added the room ID to the attached rageshake

**Comment by andybalaam** [comment]
This is happening to me in an encrypted DM.

**Comment by MadLittleMods** [comment]
I have had this one encrypted DM pop-up as unread every time I refresh Element since December. Consistent every-time I refresh so I can easily grab more debugging info if you provide snippets to run. There hasn't been new activity in the room.

Rageshake logs: https://github.com/matrix-org/element-web-rageshakes/issues/19036

https://user-images.githubusercontent.com/558581/211664116-2a45d6a9-2cd3-4df9-b70d-51073556c2b0.mp4

**Comment by andybalaam** [comment]
This is still happening to me. I am upgrading the frequency to O-Frequent.

**Comment by kittykat** [comment]
I'm seeing this all the time with a specific DM

**Comment by gsouquet** [comment]
Two PRs have landed yesterday to help with this issue. https://github.com/matrix-org/matrix-react-sdk/pull/9763 and https://github.com/matrix-org/matrix-js-sdk/pull/3031 .
Does this still happens in today's nightly if you do a "clear cache & reload"?

Let me know, and I'll investigate further if this does still occur.
@kittykat @andybalaam @MadLittleMods

**Comment by andybalaam** [comment]
On develop.element.io I just did "clear cache & reload" and I still have a notification for the same DM (but no new message).

**Comment by kittykat** [comment]
It was working ok yesterday, same DM is marked unread today again

**Comment by gsouquet** [comment]
@andybalaam 's issue seem to be related to a synapse problem, we have filed https://github.com/vector-im/element-web/issues/23685

@kittykat 's bug was different and appears to be a client-side confusion of "cache receipts", I'm investigating this and should be able to come up with a solution

`getEventReadUpTo` and `getReadReceiptForUserId` seem to conflict, and return a reference to a different event. Making `hasUserReadEvent` determine that the wrong is unread and generated a "bold" notification
