### ISSUE TITLE
Mention through '@' doesn't show list automatically

### ISSUE THREAD

**Issue by br3eze** [vector-im/element-web#24018]
### Steps to reproduce

Just try to put '@' into the edit box to mention somebody.

### Outcome

It popups variants only if You type first letter of a nickname. 

### Operating system

Arch Linux

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

pacman repos

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This was chosen intentionally

**Comment by br3eze** [comment]
@t3chguy But in the mobile version it shows variants. Really helps sometimes to make a fast answer.

**Comment by t3chguy** [comment]
Sure, it is up to design to pick which to go forward with and the other platforms should follow. It is unlikely a setting will be allowed for this, Design is averse to adding settings unless required.

**Comment by daniellekirkwood** [comment]
Created a discussion for this issue: https://github.com/vector-im/element-meta/discussions/1032

I'll close this for now as it's likely we'll choose to go with the implementation that currently exists on Web. However, thanks for bringing this to our attention - once we've got a plan to move forwards new issues will be created to address the work needed.
