### ISSUE TITLE
Part of Room Tile goes behind the show more button area

### ISSUE THREAD

**Issue by vishu1034** [vector-im/element-web#24037]
### Steps to reproduce

I have three entries in my favorites and the last tile is going behind the show more button area, I have attached the screenshot.
<img width="351" alt="Screenshot 2022-12-16 at 9 32 52 AM" src="https://user-images.githubusercontent.com/97598956/208042473-ee846b03-7745-4ac0-ae75-d9a63ac07ae9.png">

#### What did you expect?
Room tiles should be fully visible

#### What happened instead?
Part of Last room tile is hiding behind the show more button area.

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is done intentionally, as the user can resize each sublist to the exact size they wish it to be without it snapping in increments of room tiles.

**Comment by vishu1034** [comment]
> This is done intentionally, as the user can resize each sublist to the exact size they wish it to be without it snapping in increments of room tiles.

But you see I have only three entries in the favorites list and half of the last tile is hidden. Doesn't look good. Any way to show the complete tiles.

**Comment by vishu1034** [comment]
> 

And with only three entries, show more button is not visible so looks broken.

**Comment by vishu1034** [comment]
> Yes, as I said you can resize it to whatever size you like. Drag the resize handle.
> 
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/2403652/208069961-f67ba4cb-5526-44fe-a2d1-b5d5ad4c3b2e.png">

ohk. Got it. Thanks for clearing that up.
