### ISSUE TITLE
app.element.io claims to be "wrongly configured"

### ISSUE THREAD

**Issue by probonopd** [vector-im/element-web#24048]
### Steps to reproduce

1. Where are you starting? What can you see?  https://element.io/get-started
2. What do you click? Click "Open Element web" button
3. More steps…The error message immediately appears

#### What did you expect?

Works

#### What happened instead?

![image](https://user-images.githubusercontent.com/2480569/208323099-89e61582-48cd-4528-95ac-b28c2e10db84.png)

### Operating system

FreeBSD

### Browser information

Falkon. User agent: "Mozilla/5.0 (X11; FreeBSD amd64; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/22.08.1 Chrome/83.0.4103.122 Safari/537.36"

### URL for webapp

app.element.io

### Application version

Whatever app.element.io uses as of today

### Homeserver

Whatever app.element.io uses

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hi @probonopd can you have a look at the Browser's error console if you open this page? If there are any errors, can you post them as comments here?

**Comment by t3chguy** [comment]
Falkon is not a supported environment - https://github.com/vector-im/element-web#supported-environments

**Comment by probonopd** [comment]
Falkon is essentially just Qt WebEngine, which is essentially just the guts of Google Chrome.

Here is the console output. What jumps at me is a 404. Maybe that has to do with it?

![image](https://user-images.githubusercontent.com/2480569/208529397-567cb85e-35f5-4806-a41b-ac33a56b952b.png)

**Comment by probonopd** [comment]
Is https://app.element.io/config.app.element.io.json supposed to be working?

**Comment by t3chguy** [comment]
No, that config is optional. The app isn't loading for you as your browser lacks support for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry - as per the supported environments policy, your browser is unsupported
