### ISSUE TITLE
Welcome text overflows the box (German version)

### ISSUE THREAD

**Issue by DzenOwl** [vector-im/element-web#24044]
### Steps to reproduce

After first authorization one of the welcome messages overflows the container
1. Go to the welcome page
2. Choose "German" as the language
3. Authorize new account
4. There's the bug

#### What did you expect?
Expected that text in the element will fit

#### What happened instead?
It doesn't
![image](https://user-images.githubusercontent.com/58021505/208265042-1dad5501-b622-4cdd-8652-703904e8d056.png)

### Operating system

Windows 10

### Browser information

Microsoft Edge 108.0.1462.54

### URL for webapp

app.element.io

### Application version

Element version: 1.11.16, Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Thanks for reporting the issue @DzenOwl . One addition to the reproduction steps: You can see this screen if not logging in and setting the path to `#/home`.

**Comment by t3chguy** [comment]
@vector-im/design what should happen here? Should the last button grow itself?

**Comment by t3chguy** [comment]
We do not support soft hyphens to my knowledge and Weblate has no simple way to enter them - https://github.com/WeblateOrg/weblate/issues/3006

**Comment by weeman1337** [comment]
Soft hyphens can be entered in translations:

![image](https://user-images.githubusercontent.com/6216686/214297826-31fd1e3d-6ecf-46f7-a834-9fc3ce48435c.png) 

→ done
