### ISSUE TITLE
Selecting "Show: My threads" makes button disappear

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24040]
### Steps to reproduce

1. Have a DM with another user
2. The other user starts a thread on _their own_ message
3. I select "My threads"
4. The "Show: ..." button disappears and the other users' thread is still visible

![Screenshot 2022-12-16 at 14 10 07](https://user-images.githubusercontent.com/1137962/208105935-b36dca19-bf5d-4241-84da-42c36ce379d7.png)

![Screenshot 2022-12-16 at 14 12 35](https://user-images.githubusercontent.com/1137962/208105979-cda5058b-7923-4e2f-aaf4-df4e3fc109b7.png)

#### What did you expect?

The button shouldn't go hidden. Also since I'm not in any thread myself, I suspect the list should be empty?

#### What happened instead?

The opposite.

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io

### Will you send logs?

No

**Comment by kwliang1** [comment]
I'd like to give this a shot, please.

**Comment by gsouquet** [comment]
Go for it! Feel free to drop by https://matrix.to/#/#element-dev:matrix.org if you have any questions!
