### ISSUE TITLE
`m.direct` account data is modified when starting typing and clearing composer within a DM

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24059]
### Steps to reproduce

1. With user A create a DM with user B
2. Let user B join
3. Type a message with user B
4. Open network tab
5. Notice `m.direct` hit

#### What did you expect?

No account data changes related to DMs when interacting with the composer.

#### What happened instead?

Lots of network requests. It's unclear if this is further caused by DMs being "corrupted" by the RoomListStore: `!room:localhost was found in DMs but the room is not in the store`

Only happens for invited user B

### Operating system

Windows 10

### Browser information

Edge

### URL for webapp

local build of staging.element.io

### Application version

Staging

### Homeserver

localhost, 1.73.0

### Will you send logs?

Yes

**Comment by turt2live** [comment]
copy/pasting for further context:

so the call to set `m.direct` is coming from `RoomView`'s `updateRoomMembers` function, which is seemingly being triggered by a room state update in the js-sdk. That room state update is happening because the typing notification for ourselves is coming down `/sync`, which appears to have an empty timeline and state array for the room, which is enough to trigger the js-sdk's `setStateEvents` function within `RoomState` (specifically, called from [here](https://github.com/matrix-org/matrix-js-sdk/blob/b83c3728486a4d3c7f9d660c4cd0f678e73746c7/src/sync.ts#L1727)). At the end of `setStateEvents`, we trigger a room state update, even if we didn't change anything.

I'm not seeing any obvious recent changes which would cause this sort of behaviour, so a possible theory is it's Synapse returning (legal) JSON with extra, empty, fields (thus triggering our code to set state from an empty array). That said, it would be a very weird bug to show up only now and not ages ago.

**Comment by weeman1337** [comment]
Can reproduce - updated steps in description

**Comment by weeman1337** [comment]
Last version not showing this behaviour is 1.10.6

**Comment by weeman1337** [comment]
Found the change introducing this behaviour https://github.com/matrix-org/matrix-react-sdk/commit/c257bc3f7a3bf8db92c621ea1473d50706464be1#diff-13590ebbbcd62256ff3ead94de2e6be41867b82ad9e0470c4b63ff63c1f5f78bR287

**Comment by turt2live** [comment]
I'm a bit worried that a more recent change has made this worse, as a 10 month-old bug would have manifested sooner. 

ftr, this issue appears to cause DM status to be *lost* on rooms, as it calculates the wrong DM state.

**Comment by weeman1337** [comment]
> ftr, this issue appears to cause DM status to be lost on rooms, as it calculates the wrong DM state.

Isn't this another issue? Like sending the wrong `m.direct` content?
