### ISSUE TITLE
History not received by invited account

### ISSUE THREAD

**Issue by dbankmann** [vector-im/element-web#24056]
### Steps to reproduce

1. Create new private space with some rooms
2. Change history setting of rooms to 'Anyone' or 'Members only (since the point in time of selecting this option)
3. Write a few messages
4. Invite a second user to those rooms

#### What did you expect?
History should be visible, meaning the messages of step 3.
#### What happened instead?
Either the messages are not shown at all or the message 

> You can't see earlier messages
> Encrypted messages before this point are unavailable.
appears

### Operating system

Arch linux

### Application version

Element version: 1.11.10 Olm version: 3.2.12

### How did you install the app?

arch package

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hey @dbankmann thank you for reporting this issue. Unfortunately I am unable to reproduce it.

- You reported the issue using an older version of Element. Can you test with the latest version please?
- Did you invite the user to the space or to the rooms?

**Comment by dbankmann** [comment]
Hi @weeman1337,

I invited the user to the rooms specifically. 
Indeed, I was using latest arch package which is suprinsingly outdated. With the `element-desktop-git` package from aur using version `1.11.16.r32.ga7124c935e` I've not been able to reproduce the issue either.
