### ISSUE TITLE
Timeline blank / white when viewing a room if threads enabled and thread root is UTD

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24054]
### Steps to reproduce

1. Have threads enabled
2. Create an encrypted room
3. Send a message
4. Invite other, unverified account
5. Let the other join
6. Go to settings and check „never send encrypted messages to unverified users“
7. Start a thread in the room
8. With other user: view another room, go back to test room

#### What did you expect?

Can see the timeline

#### What happened instead?

Cannot see the timeline. White / blank space only

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element Nightly version: 2022121801 Olm version: 3.2.12

### How did you install the app?

official deb

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Maybe related https://github.com/vector-im/element-web/issues/23598

This issue targets an existing room, that was visible before

**Comment by weeman1337** [comment]
Room works with threads disabled

**Comment by gsouquet** [comment]
I don't think I've encountered this issue and I unfortunately do not end up in the same stage as you when joining the room you've listed.

The rageshake logs do not highlight anything useful in this context

**Comment by weeman1337** [comment]
Don't know if this helps: The thread event now shows as UTD. After someone reacted to it I can see the room again with threads enabled.

![image](https://user-images.githubusercontent.com/6216686/208471279-127a751a-8157-4248-8e85-444881a48556.png)

**Comment by weeman1337** [comment]
Updated the issue. Can now reproduce. Looks like UTD thread roots are causing the issue.

**Comment by gsouquet** [comment]
I don't think this issue is occuring in staging.element.io. Could someone confirm this too

**Comment by weeman1337** [comment]
It does

![image](https://user-images.githubusercontent.com/6216686/208655987-305496c3-97fc-41ce-bdff-dd20119afb37.png)
