### ISSUE TITLE
Thread back button should restore my old position in the thread list instead of going to the bottom

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#24062]
#### What would you like to do?

1. Browse threads.
2. Pick a thread and click on it.
3. Decide it's not the thread you wanted, so press the back button to go back to the thread list.

You're now on the bottom of the thread list. Instead, it would be better if the old position was retained.

#### Why would you like to do it?

It's less disorienting to retain the old position and is much more efficient when you're traversing multiple threads (for example, if you're viewing each one in order to find a particular one).

#### How would you like to achieve it?

The back button should lead to the old position in the thread list rather than the bottom.

**Comment by clokep** [comment]
Note that this is particularly bad when you've scrolled back a few pages in the thread list as you then have to wait again for each page to load.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/21735 which seems to be where the responsible individuals for threads are tracking this (please migrate your 👍 over there)
