### ISSUE TITLE
New room directory does not show spaces

### ISSUE THREAD

**Issue by dali99** [vector-im/element-web#24064]
### Steps to reproduce

The old room directory looked like this on our server:
![2022-12-13-162332_731x616_scrot](https://user-images.githubusercontent.com/990767/208687867-3c739d55-ea1f-46f2-bca6-2ed40d86a9e5.png)

With different organization's spaces in our room directory

Now it only shows the two rooms which are not spaces:

![2022-12-20-152418_696x581_scrot](https://user-images.githubusercontent.com/990767/208689385-73c64a2c-0e82-46e9-bfd9-603a95ecad25.png)

#### What did you expect?

I expect rooms in the room directory to show up in the room directory regardless of what room types they are

#### What happened instead?

Only chat rooms are displayed

### Application version

element-web 1.11.16

### Will you send logs?

No

**Comment by t3chguy** [comment]
Do you have the labs flag enabled? The previous dialog didn't support it either and it was also not possible to graphically add spaces to the room directory, it just asked for all rooms. The new only asks for non-space rooms unless you have the labs flag enabled

<img width="720" alt="image" src="https://user-images.githubusercontent.com/2403652/208692588-c87425e6-abbd-4977-b580-62d923ad1aca.png">

**Comment by dali99** [comment]
I do not have the labs flag enabled, so that explains it

It was possible to add spaces to the room directory using other clients (cinny, synapse-admin) and it worked well in element as well.

I'll be enabling this lab option by default on our element deployment, thanks
