### ISSUE TITLE
Netlify workflow refers to workflow file that doesn't exist

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#24071]
https://github.com/matrix-org/matrix-react-sdk/blob/develop/.github/workflows/netlify.yaml#L38 refers to element-build-and-test.yaml but that file was deleted just over a week after that reference was added (https://github.com/matrix-org/matrix-react-sdk/pull/8677).

I guess it still works fine though...

**Comment by dbkr** [comment]
Oh, it doesn't matter because `run_id` is specified. The docs allude to not specifying options together although not specifically `workflow`. Either way, we probably just want to delete `workflow`.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/9649 fixed the same thing in cypress.yaml - just a case of deleting the line
