### ISSUE TITLE
"Jump to date" doesn't work.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#24079]
### Steps to reproduce
1. Make sure the Synapse configuration file `homeserver.yaml` has MSC 3030 enabled:
```
experimental_features:
   msc3030_enabled: true
```
2. Since Element Desktop (version: 1.11.16 / 1.11.17) cannot manually enable "Jump to date", ~~you need to roll back to an older version and enable "Jump to date" in this version~~ ("Jump to date" may be related to the iteration of the Synapse version, which may be the version before 1.73);
3. Update Element Desktop to the latest version and start it;
4. Enter a room with a longer timeline (for jumping), and locate a certain timeline;
5. Click the date, try to jump up according to the prompt.
![{A98B8333-08C8-FE69-AD44-8A075123C9F6}](https://user-images.githubusercontent.com/48104960/209109580-7c71a552-8ae8-43ce-b99a-e6c1ffe79b73.png)

#### What did you expect?
I can jump to near the specified date according to my needs.

#### What happened instead?
If the jump fails, an error as shown in the figure is returned:
![{9CD7751E-4849-FB3A-2D30-BCCB361F178B}](https://user-images.githubusercontent.com/48104960/208937813-a43e2bde-c45b-46bf-b834-02bb9cef888d.png)

At this time, the developer tool displays the information as shown in the figure:
![{EA4B5B82-3BF2-D8F7-5770-2206A170CD44}](https://user-images.githubusercontent.com/48104960/209108878-a99d2b69-67ad-4a46-bc6e-05d150789f99.png)

**Also I found that this feature has disappeared from "Labs". This makes it impossible to enable this feature in another development version (Element Web, version number: a7124c935ece-react-910aa0b81395-js-6d58a54039fc). What happend?**

### Operating system

x64 Windows 7

### Application version

Element Desktop 1.11.17

### How did you install the app?

https://packages.element.io/desktop/update/win32/x64

### Homeserver

Synapse 1.74.0

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for reporting the issue @YamatoRyou 

Can you please provide reproduction steps for you issue?

**Comment by YamatoRyou** [comment]
> Thanks for reporting the issue @YamatoRyou
> 
> Can you please provide reproduction steps for you issue?

Has been updated.

**Comment by t3chguy** [comment]
Yeah this is simply Synapse dropping development support, the work to move to the stable endpoint is https://github.com/matrix-org/matrix-js-sdk/pull/2915

**Comment by YamatoRyou** [comment]
> Yeah this is simply Synapse dropping development support, the work to move to the stable endpoint is [matrix-org/matrix-js-sdk#2915](https://github.com/matrix-org/matrix-js-sdk/pull/2915)

Will Element follow up on this change so users can continue to use the feature?

**Comment by t3chguy** [comment]
It is awaiting iteration from its author.
