### ISSUE TITLE
Be able to display 2 PIP widgets: one for a call, another for a voice broadcast

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#24076]
### Your use case

A live voice broadcast recorder is paused when the user accepts an incoming call.
We should be able to display the PIP of this VB when the user navigates to other rooms whereas there is already a PIP widget for the call

[Design](https://www.figma.com/file/5zlCPsSOJELBzIiQdHC2LV/Voice-Broadcasting?node-id=58%3A13919&t=o76SoVhm3U1Y4UzJ-4)
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/8969772/208924378-6979ae4b-4f2f-421d-ab0c-f268f3c5ec21.png">

**Comment by robintown** [comment]
Just for visibility, it's not entirely related, but the VoIP team also has PiP changes of its own in progress: https://github.com/matrix-org/matrix-react-sdk/pull/9800
