### ISSUE TITLE
"Sign in instead" on forgot password page doesn't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24087]
### Steps to reproduce

1. Go to login page
2. Forget your password, click link to fix
3. Remember your password, click "Sign in instead"

#### What did you expect?

The login page.

#### What happened instead?

The first time I ended up getting a page refresh (due to an empty query string being added), and subsequent times the component flickers but doesn't change. Presumably this is a form button not being intercepted, so the page changes before our code can do anything with it.

### Operating system

Windows 10

### Browser information

Edge

### Will you send logs?

No

**Comment by weeman1337** [comment]
Can reproduce. And this was me. Will take care of a fix.

**Comment by richvdh** [comment]
> And this was me

Can you link to the PR that introduced this?
