### ISSUE TITLE
The website does not adapt to mobile form-factors.

### ISSUE THREAD

**Issue by rokejulianlockhart** [vector-im/element-web#24082]
### Steps to reproduce

Login.

#### What did you expect?
The website should adapt to the form-factor of my display.

#### What happened instead?
![Screenshot_20221221-175123](https://user-images.githubusercontent.com/42837531/208971550-1d4c6b52-defd-4120-9b47-512eeb2ede31.png)
![Screenshot_20221221-153811](https://user-images.githubusercontent.com/42837531/208967264-e5a74941-5c72-44a6-9645-0a870151557f.png)

### Operating system

Android 13; CalyxOS 4.4.0; build TQ1A.221205.011.22404000

### Browser information

https://play.google.com/store/apps/details?id=org.mozilla.fenix 110.0a1 (Build #2015922795), d07de1e02+ AC: 110.0.20221221024602, 35a3cae7a7 GV: 110.0a1-20221220093956 AS: 96.1.3 2022-12-21T05:08:50.670314

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Thanks for reporting the issue @rokejulianlockhart . Unfortunately mobile browsers are currently not supported, see [here](https://github.com/vector-im/element-web#supported-environments). You can use the mobile apps on you phone.

**Comment by rokejulianlockhart** [comment]
Don't you think that that's rather ridiculous in this day and age?—That a new website, of all things, would not be able to adapt to different form-factors? It operates perfectly otherwise.

**Comment by t3chguy** [comment]
@rokejulianlockhart contributions are welcome, we do not have the time to invest in working in all various layouts on top of maintaining two dedicated mobile apps.

**Comment by rokejulianlockhart** [comment]
@t3chguy, why? You'll cut off any user of a mobile Linux device with that attitude, and any whose device is old. I realize that it is more to maintain – I'm a developer too, and having to duplicate work is awfully bothersome, but what I request is rather standard practise.

**Comment by andybalaam** [comment]
@rokejulianlockhart this is just not something we are investing effort into at the moment. There are a lot of open issues on this repo (any help much appreciated!) and we think fixing bugs is more important than supporting new platforms. There are lots of Matrix clients that work well on mobile, including web-based ones like [Hydrogen](https://github.com/vector-im/hydrogen-web/).
