### ISSUE TITLE
Desktop search doesn't work

### ISSUE THREAD

**Issue by yozhic** [vector-im/element-web#24098]
### Steps to reproduce

1. I start the Element Desktop App.
2. Open the room. Start searching for the word in the messages.

#### What did you expect?

The program searches for the word.

#### What happened instead?

The program is not searching. I immediately see the message "No result". And I see the message "Use the Desktop app". But I already use the Desktop app!

![2022-12-23_14-28-22](https://user-images.githubusercontent.com/13917732/209338075-c28645db-77e2-4da1-a173-747cc6b3f61c.jpg)

### Operating system

macOS 10.14.6 Mojave

### Application version

Element version 1.11.17

### How did you install the app?

From https://packages.riot.im/desktop/install/macos/Element.dmg

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
It does not work on Mojave, it requires some native module features only present from Catalina onwards I believe. Given Mojave is out of service it is not a supported platform - https://github.com/vector-im/element-web#supported-environments
