### ISSUE TITLE
Element Nightly crashing on startup.

### ISSUE THREAD

**Issue by kspalaiologos** [vector-im/element-web#24094]
### Steps to reproduce

1. Start element with gdb attached (`gdb -q /opt/Element-Nightly/element-desktop-nightly`).
2. Wait for the screen which shows a spinning progress indicator.

### Outcome

Element Nightly crashes.

```
Thread 5 "ThreadPoolForeg" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7ffff27866c0 (LWP 6783)]
0x000055555abe1554 in ?? ()
(gdb) bt
#0  0x000055555abe1554 in  ()
#1  0x0000001600290000 in  ()
#2  0x0000201801a01c00 in  ()
#3  0x000055555f0031c0 in  ()
#4  0x000000000000a000 in  ()
#5  0x00007ffff27845b0 in  ()
```

This happens on a somewhat random basis.

### Operating system

Debian Linux

### Application version

Element Nightly version: 2022122101 Olm version: 3.2.12

### How did you install the app?

Debian Sid repositories.

### Homeserver

Up to date Synapse.

### Will you send logs?

No

**Comment by weeman1337** [comment]
Can confirm this issue

Output from console when crashing

```
Fetching translation json for locale: en
Resetting the UI components after locale change
[9599:1223/083836.054435:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Trace/breakpoint trap (core dumped)
```

**Comment by weeman1337** [comment]
@kspalaiologos can this be the same as https://github.com/vector-im/element-web/issues/23311 ?

**Comment by kspalaiologos** [comment]
I doubt this, since my crash happens directly a few seconds after startup,
not minutes.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/23311#issuecomment-1254217941 reports it being a few seconds too
