### ISSUE TITLE
Wrong quote level chosen when replying to a quoted quote

### ISSUE THREAD

**Issue by yoasif** [vector-im/element-web#24095]
### Steps to reproduce

1. Someone posted a quote with > (I think) and appended to that quote with their own comment
2. I then clicked the reply button on that comment
3. I typed my reply and sent

#### What did you expect?

I expect that in my reply, the text that I am responding to ends with the text that the poster appended to their quoted text. 

#### What happened instead?

The displayed comment I posted showed the wrong part quoted - it shows as if I was responding to the quote that the initial commenter was commenting on, not their own comment.

### Operating system

Linux

### Browser information

Firefox Nightly

### URL for webapp

https://chat.mozilla.org

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by yoasif** [comment]
Screenshot of the issue:

![image](https://user-images.githubusercontent.com/152493/209229513-d3afe6e3-774b-4f73-8d55-e95601f6243d.png)

My message source:

{
  "content": {
    "body": "> <@dannycolin:mozilla.org> > Mozilla is on life support, and ironically for them, it’s Google they have to thank. With something like 75% of Mozilla’s funding coming from them.\n> \n> Ofc their \"supporters\" are too busy ranting on reddit and switching to Brave that is [surprise] a Chrome based browser 😆\n\nlol i dont know about them being supporters ",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!jsaezpvBlGBUzugEtp:mozilla.org/$3GTomd5tWBKUkYQ7oEMl6AMs0oigvA-aEX7s4V4itxY?via=mozilla.org&via=matrix.org&via=kde.org\">In reply to</a> <a href=\"https://matrix.to/#/@dannycolin:mozilla.org\">@dannycolin:mozilla.org</a><br><blockquote>\n<p>Mozilla is on life support, and ironically for them, it’s Google they have to thank. With something like 75% of Mozilla’s funding coming from them.</p>\n</blockquote>\n<p>Ofc their \"supporters\" are too busy ranting on reddit and switching to Brave that is [surprise] a Chrome based browser 😆</p>\n</blockquote></mx-reply>lol i dont know about them being supporters",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$3GTomd5tWBKUkYQ7oEMl6AMs0oigvA-aEX7s4V4itxY"
      }
    },
    "msgtype": "m.text",
    "org.matrix.msc1767.message": [
      {
        "body": "> <@dannycolin:mozilla.org> > Mozilla is on life support, and ironically for them, it’s Google they have to thank. With something like 75% of Mozilla’s funding coming from them.\n> \n> Ofc their \"supporters\" are too busy ranting on reddit and switching to Brave that is [surprise] a Chrome based browser 😆\n\nlol i dont know about them being supporters ",
        "mimetype": "text/plain"
      },
      {
        "body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!jsaezpvBlGBUzugEtp:mozilla.org/$3GTomd5tWBKUkYQ7oEMl6AMs0oigvA-aEX7s4V4itxY?via=mozilla.org&via=matrix.org&via=kde.org\">In reply to</a> <a href=\"https://matrix.to/#/@dannycolin:mozilla.org\">@dannycolin:mozilla.org</a><br><blockquote>\n<p>Mozilla is on life support, and ironically for them, it’s Google they have to thank. With something like 75% of Mozilla’s funding coming from them.</p>\n</blockquote>\n<p>Ofc their \"supporters\" are too busy ranting on reddit and switching to Brave that is [surprise] a Chrome based browser 😆</p>\n</blockquote></mx-reply>lol i dont know about them being supporters",
        "mimetype": "text/html"
      }
    ]
  },
  "origin_server_ts": 1671743185459,
  "sender": "@yoasif:mozilla.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 121,
    "transaction_id": "m1671743185355.0"
  },
  "event_id": "$XEN3kAWxD5iPyl5q1SEq1JOoJmEmVLx_1bkBSip4dc4",
  "room_id": "!jsaezpvBlGBUzugEtp:mozilla.org"
}

**Comment by weeman1337** [comment]
Thanks for reporting the issue @yoasif .

 This looks correctly to me. If someone writes a message with quoting something by prefixing it with `>` it counts as a normal message.
