### ISSUE TITLE
Unable to decrypt: The sender's device has not sent us the keys for this message

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#24109]
### Steps to reproduce

1. Where are you starting? What can you see?

Almost never had any decryption issue in 3 years that my family is using Matrix and Element but for the last three month, it has happened way to often to make it usable. We have to launch the /discardsession all the time.

We constantly face the annoying "Unable to decrypt: The sender's device has not sent us the keys for this message" message.

#### What did you expect?
Be able to read messages of our friend and family.
#### What happened instead?
"Unable to decrypt: The sender's device has not sent us the keys for this message"

### Operating system

Debian but same issue with Element Android

### Application version

1.11.17

### How did you install the app?

From the website element.io for the desktop version and from f-droid fro the Android version.

### Homeserver

1.71

### Will you send logs?

Yes

**Comment by Thatoo** [comment]
I have sent three rageshake

**Comment by weeman1337** [comment]
Hi @Thatoo thanks for reporting the issue. If possible, can you send rageshakes from both sides (sender and receiver) next time?

**Comment by richvdh** [comment]
Unfortunately I don't think we can do very much here without rageshakes from the sender side.
