### ISSUE TITLE
room not accessible

### ISSUE THREAD

**Issue by OptimusGREEN** [vector-im/element-web#24102]
### Steps to reproduce

Trying to add the following room

[#facebook:maunium.net](https://matrix.to/#/#facebook:maunium.net)

### Outcome

got this error

#facebook:maunium.net is not accessible at this time.
Try again later, or ask a room or space admin to check if you have access.

was returned while trying to access the room or space. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose).

### Operating system

MacOS

### Application version

Element v1.11.17

### How did you install the app?

element website, cant remember was ages ago

### Homeserver

matrix.optimusgreen.com

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Hi @OptimusGREEN :wave: thanks for reporting the issue. You selected to send logs. Can you do this if possible directly after the error occurred?

**Comment by OptimusGREEN** [comment]
Hi,

Where should i find the logs on a mac?

when trying to join via element web i get this...

`MatrixError: [404] Can't join remote room because no servers that are in the room have been provided. (https://matrix.optimusgreen.com/_matrix/client/r0/join/!JiBnIosqbMwu%3Amaunium.net)`

**Comment by weeman1337** [comment]
You can send logs via „All Settings“ →„Help and About“ → „Submit Debug Logs“

**Comment by turt2live** [comment]
What were the steps leading up to the error? We'll need to know how exactly you got to the join screen so we can fix the issue.

**Comment by OptimusGREEN** [comment]
Hi, I've closed this as I have binned matrix for the time being. Thanks
