### ISSUE TITLE
Unify voice message bitrate

### ISSUE THREAD

**Issue by Bleuzen** [vector-im/element-web#24103]
### Your use case

The opus bitrate of voice messages is different when comparing mobile to desktop client.

The mobile client uses a higher bitrate (35 kbps in my test, probably abr targetting ~ 32 kbps)
while the desktop client uses a lower bitrate (23 in my test, probably abr targetting ~ 24 kbps).

#### What would you like to do?

Increase the voice message bitrate of the desktop client (currently ~ 24 kbps) to match the one of the mobile client (~ 32 kbps).

#### Why would you like to do it?

1.) The current encoding settings are inconsistent (in a way it doesn't make sense)
2.) The current audio quality of voice messages is bad. This is more apparent on the desktop client since people more likely have better mics on their desktop setup compared to the tiny mics of their phones. Together with the fact that the desktop client uses this low bitrate, it just sounds bad. Increasing the bitrate should improve the audio quality.

#### How would you like to achieve it?

Increase the bitrate of the desktop client to match the one of the mobile client (~ 24 -> ~ 32 kbps).

32 kbps for opus voice messages is usually a good compromise for "okay" audio quality while keeping the file size small, so it is a good default value to use for both client types in my opinion.

### Have you considered any alternatives?

Short term: no, I think just using ~ 32 kbps in all clients should do just fine.

Long term: just an idea, perhaps implement a setting to select the voice message bitrate. Not sure if this is overkill, should probably be discussed in another issue if there is enough interest.

**Comment by turt2live** [comment]
As per the MSC (https://github.com/matrix-org/matrix-spec-proposals/pull/3245), the mobile clients should be *lowering* their bitrate instead.
