### ISSUE TITLE
Unable to query secret storage status and Unable to set up keys errors. 

### ISSUE THREAD

**Issue by digitaldarragh** [vector-im/element-web#24116]
### Steps to reproduce

Error1: "Unable to set up keys"
Error2: "Unable to query secret storage status"

Error one is encountered during first login. 
Error 2 is encountered when I try to validate a device. 

I installed this yesterday on a dedicated server. It's my first time with Element and matrix-synapse. So it's possible that I got something wrong during setup or configuration. 

[ElementLogs.zip](https://github.com/vector-im/element-web/files/10315381/ElementLogs.zip)

Logs attached. 

### Outcome

Expected: Device keys should be created.

Happening: It appears to me that this is not happening or Element isn't acknowleding that it is happening. I don't know enough about this software to make a determination either way. 

### Operating system

Ubuntu

### Browser information

Edge

### URL for webapp

v1.11.17

### Application version

1.11.17

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Hi @digitaldarragh thanks for reporting the issue. Does your Synapse provide any useful logs?

**Comment by digitaldarragh** [comment]
I have investigated this at length today. 
I see a similarly reported issue here: https://github.com/typokign/matrix-chart/issues/24

Extract from the log. With some of the left text removed to make it a little easier to read: 
INFO - GET-15147 - 123.123.123.123 - 8008 - {None} Processed request: 0.000sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 167B 404 "GET /_matrix/client/v3/room_keys/version HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54" [0 dbevts]

I understand that this is likely to be as a result of nginx inserting it's own 404 page. However, I have now confirmed that this isn't the cause.  My vhost config is pasted below for confirmation of this. 

`server {
        listen 443 ssl;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_certificate /etc/letsencrypt/live/example.org/cert.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;
         server_name matrix.example.org;
         location /_matrix 
         {
                proxy_pass         http://localhost:8008;
                proxy_intercept_errors off;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect     off;
                proxy_set_header   Host             $host;
                client_max_body_size 50M;
                proxy_http_version 1.1;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
} 

server {
    listen 8448 ssl;
    server_name matrix.example.org;

    ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem;

    location / {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
`

Do you have any ideas what could be causing this?

**Comment by digitaldarragh** [comment]
Please note that this was an issue on my side. After fixing the referse proxying issue described in my previous post, nginx was continuing to cache.
