### ISSUE TITLE
setting individual room avatar not working

### ISSUE THREAD

**Issue by vincentthequeer06** [vector-im/element-web#24120]
### Steps to reproduce

1. Login to element web app
2. go to a random room
3. send an image in said room
4. right click on the image and select copy image adress
5. run the command /myroomavatar and paste the url
6. It will say [user] changed their profile picture
7. click on your user profile in that room and your profile picture will be like one of the defaults with the letter on it

#### What did you expect?
I wanted my profile picture in a room to be changed

#### What happened instead?
My profile picture disappeared and only had a letter in it like one of the default pfps

### Operating system

Chrome OS

### URL for webapp

app.element.io

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### Homeserver

Homeserver is https://matrix-client.matrix.org Identity server is https://vector.im

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
> right click on the image and select copy image adress

This will get you the regular URL, not the MXC URL which you need for `/myroomavatar`. To get the MXC URL you need to click `View Source` in the message context menu and look for `"content"` -> `"file"` -> `"url"`
