### ISSUE TITLE
Element repeatedly crashing and now refuses to start

### ISSUE THREAD

**Issue by cxr6548** [vector-im/element-web#24123]
### Steps to reproduce

1. Where are you starting? What can you see?
Starting the element flatpak doesn't really work out very well. My iOS element also used to crash frequently. Nobody else on my homeserver is having startup issues.

#### What did you expect?
I expect to open element and start chatting

#### What happened instead?
I got a neat screen saying I'd have to clear cache to continue or I had the option of submitting debug logs.

### Operating system

Fedora Linux

### Application version

1.11.17

### How did you install the app?

flathub

### Homeserver

Synapse 1.72.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report this to the maintainers of your community maintained package - https://github.com/flathub/im.riot.Riot/
