### ISSUE TITLE
Lock icon in the 'create a space' window is clearly larger than it used to be

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#24128]
### Steps to reproduce

1. Press 'create a space'

#### What did you expect?

Something like this:

![](https://user-images.githubusercontent.com/2403652/116373837-a450e580-a805-11eb-8bca-5b515f36d478.png)

#### What happened instead?

The lock has gotten bigger:

![Screenshot 2023-01-01 at 01-08-57 Element llg](https://user-images.githubusercontent.com/48614497/210162485-3217f498-c470-4368-bf6c-a29f120c8d96.png)

Presumably since I had to write https://github.com/matrix-org/matrix-react-sdk/pull/9638 as well, the lock SVG got enlarged at the source at some point.

### Operating system

NixOS unstable

### Browser information

Firefox 108.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 85e2f063ac81-react-3ce064731b6d-js-ce776b99895d Olm version: 3.2.12

### Homeserver

Synapse 1.72.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed in 1.11.16

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9581
@weeman1337 could you please resolve this
