### ISSUE TITLE
Typing after Ctrl-Backspace restores deleted text

### ISSUE THREAD

**Issue by al-jshen** [vector-im/element-web#24121]
### Steps to reproduce

https://user-images.githubusercontent.com/22137276/210021706-a61039d0-c7c7-4280-9dcc-3955b35496f7.mov

Steps to reproduce:
1. Type in some text. 
2. Delete the entire message with Ctrl+Backspace.
3. Type in some new text. 

The text that was deleted in (2) reappears after the cursor in (3). 

#### What did you expect?

Old text is deleted and does not reappear after the cursor when inserting new text. 

#### What happened instead?

Old text is deleted, but reappears after the cursor when inserting new text. 

### Operating system

macOS Ventura 13.0.1

### Application version

Element Nightly version: 2022122901 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Homeserver

Synapse v1.74.0

### Will you send logs?

No

**Comment by kennylflim** [comment]
How to Ctrl -Backspace with my Android keyboard

**Comment by t3chguy** [comment]
@kennylflim this repo is for Element Web & Desktop, Android is not a supported environment as per the top of the README

**Comment by alunturner** [comment]
This issue was resolved by work in commit 04e38abc87034a53382f0e1ef665054a4971d083, which can be found from tag 0.10.0 onwards
