### ISSUE TITLE
Icon no longer appears in Panel Notification Area

### ISSUE THREAD

**Issue by FizzyTea** [vector-im/element-web#24129]
### Steps to reproduce

1. Open Element-Desktop

#### What did you expect?

I expect the application icon to appear in the notification area of the panel upon opening. When I have unread messages I expect to see this indicated over the icon

#### What happened instead?

The notification area icon does not appear.

### Operating system

Ubuntu 20.04  with XFCE

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

App is installed from apt following instructions on element site

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for reporting the issue @FizzyTea . This looks like a duplicate of https://github.com/vector-im/element-web/issues/23993 . You can follow the other issue for updates.

**Comment by weeman1337** [comment]
duplicate of https://github.com/vector-im/element-web/issues/23993
