### ISSUE TITLE
Bring back search room like in 1.07

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24135]
**Is your feature request related to a problem? Please describe.**
In 1.07 I can use Search field like filter of my rooms. So, I typed "element" and have seen all my rooms about Element

**Comment by SimonBrandner** [comment]
Sorry, I am not sure I understand - do you miss the room-list search and dislike the New Search Experience (the spotlight like search you get by pressing Ctrl+K)?

**Comment by JeanPaulLucien** [comment]
Yes, I don't like new search field. In 1.07 Element Desktop I clicked on search field, typed keyword and see all my rooms with this keyword. Now search spend my time. 

I don't use Web. This is app issue.

**Comment by SimonBrandner** [comment]
Given most users are happy with the new search experience, it is unlikely to change

<hr>

The source code for the web app and the desktop is the same for the most part, so we open all issues here for simplicity, see https://github.com/vector-im/element-desktop/issues/471

**Comment by t3chguy** [comment]
This will not be coming back, but improvement suggestions to the Spotlight search are welcome.
