### ISSUE TITLE
formatted_body HTML table width, height and border are not rendered correctly

### ISSUE THREAD

**Issue by wmwsagara** [vector-im/element-web#24136]
### Steps to reproduce

1. Send a message to a room with formatted_body as per https://spec.matrix.org/v1.5/client-server-api/#mtext

```"formatted_body": "<table width=\"100%\" border=\"0\"> <tr> <td width=\"96\" height=\"96\"> <img src=mxc://matrix.ourdomain.com/POQTHofYepkTdqdFZtnpiKfG width=\"96\" height=\"96\"> </td> <td> <p>TestPub</p> </td> <td> <p>3 members</p> </td> </tr> </table> <div> <p>The horse (Equus ferus caballus) is a domesticated, one-toed, hoofed mammal. It belongs to the taxonomic family Equidae and is one of two extant subspecies of Equus ferus. The horse has evolved over the past 45 to 55 million years from a small multi-toed creature, Eohippus, into the large, single-toed animal of today.</p> <a href=https://en.wikipedia.org/wiki/Horse target=\"_blank\" rel=\"noopener\"> <img src=mxc://matrix.ourdomain.com/pdrQPNdleszFlWAdFiAWYvvY width=\"100%\"> </a> </div>"```

#### What did you expect?
The table without border as same width as the main image (horses).

#### What happened instead?
The main image (horses) is displayed to full width. But the table is smaller with border.

![Screenshot from 2023-01-02 20-22-45](https://user-images.githubusercontent.com/94213268/210231654-b34f2918-69d5-4be1-95d2-d499b44e2a49.png)

### Operating system

Ubuntu

### Browser information

Firefox 108.0

### Application version

Element version: 1.11.17

### Homeserver

matrix-synapse-1.72.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
https://spec.matrix.org/v1.5/client-server-api/#mroommessage-msgtypes doesn't permit `width` `height` or `border` on `table` elements

I suggest opening a spec issue if you disagree with the allow list
