### ISSUE TITLE
Rooms are not being marked as unread when new messages are received (with threads enabled)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24132]
### Steps to reproduce

Unclear on reliable steps.

1. Have a room set to "mentions only"
2. Be looking at a different room
3. Room receives new messages
4. Room moves up in the room list, but does not receive an unread badge

#### What did you expect?

The room to be marked as unread.

#### What happened instead?

See reproduction steps.

### Operating system

Windows 10

### Application version

0.0.1-nightly.2022123001

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
upgrading to major (critical app functionality) and release blocker given I've just caught it doing it again - no useful logs, unfortunately.

**Comment by gsouquet** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23907
