### ISSUE TITLE
Joining a specific room fails with a CORS error

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#24149]
### Steps to reproduce

Trying to join `#miraheze:libera.chat` (via ctrl-K -> type name -> click "Public rooms" -> select libera.chat as server -> click "Join") fails with a nondescript error dialog ("Failed to join / There was an error joining.") and a JS console message `Failed to join room: fetch failed: Failed to fetch` and a CORS error:
> Access to fetch at 'https://matrix-client.matrix.org/_matrix/client/r0/join/%23miraheze%3Alibera.chat' from origin 'https://app.element.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Joining other libera.chat rooms works fine.

### Operating system

Ubuntu 22.04

### Browser information

Google Chrome Version 108.0.5359.124 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
The request to `https://matrix-client.matrix.org/_matrix/client/r0/join/#miraheze:libera.chat` returns an HTTP 502 (Bad Gateway).
The issue lies within the homeserver. I would contact the homeserver admin or open a ticket in https://github.com/matrix-org/synapse/
