### ISSUE TITLE
Attempting to "View source" on a redacted event results in an error

### ISSUE THREAD

**Issue by yakumi9x** [vector-im/element-web#24165]
### Steps to reproduce

1. Send a message in an encrypted room
2. Redact (delete) the message
3. Right-click the redacted message and click "View source"

#### What did you expect?
The "View Source" dialog should show up.

#### What happened instead?
Nothing happens, and the DevTools console spits out "TypeError: e is undefined".

### Application version

Element version: 1.11.17, Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please send logs.
