### ISSUE TITLE
Failed to join. There was an error joining

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24162]
### Steps to reproduce

1. Try to join to room. 

Rooms to reproduce:
#stardust:matrix.org
#the:matrix.org
#te:matrix.org

#### What did you expect?
Joined to the room

#### What happened instead?
Failed to join

### Operating system

Windows 7

### Application version

1.11.17

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for reporting the issue @JeanPaulLucien Can you be a bit more specific? What do you mean by „Failed to join“? What is the exact error you see. Can you send logs just after this happened (via Settings → Help & About → Send debug logs)?

**Comment by JeanPaulLucien** [comment]
@weeman1337 
"Failed to join" means text in Element client.

**Comment by JeanPaulLucien** [comment]
Another one room to reptoduce: #mas:matrix.org

**Comment by turt2live** [comment]
Like https://github.com/vector-im/element-web/issues/24102 , we will need to know how exactly you're getting to the join screen in order to diagnose this issue.
