### ISSUE TITLE
Problem with SSL unable to use the chat app - https://matrix-client.matrix.org/

### ISSUE THREAD

**Issue by AngeloParana** [vector-im/element-web#24176]
### Steps to reproduce

Unable to send message due to expired home server 
https://matrix-client.matrix.org/

![image](https://user-images.githubusercontent.com/116395561/210932362-566357fc-fb1e-47da-aac6-4814310d7031.png)

### Operating system

All versions

### Application version

Latest Version

### How did you install the app?

From the website

### Homeserver

https://matrix-client.matrix.org/

### Will you send logs?

No

**Comment by turt2live** [comment]
Thanks for reporting this issue. This will be related to an ongoing incident at matrix.org - please follow https://github.com/matrix-org/matrix.org/issues/1601 for updates.
