### ISSUE TITLE
Remotely install of Element desktop version

### ISSUE THREAD

**Issue by keno61** [vector-im/element-web#24170]
Hello all together,

firstly happy new year! 

I want to install the element desktop version on the clients in our compony. I work with a software distrubution to install the software remotely. I use Powershell to realize my work. When i try to install Element via the local powershell terminal it works fine, without any problem. I used the Cmdlet `Start-process -Filepath ***` for this. 

If i try this via my software distrubution nothing happens. In the task manager i can see some processes about element but it does not install the software. I dont get an install path noteven a desktop shortcut. 

Do you guys know what can cause the problem?

Thank you for your answers.

**Comment by gsouquet** [comment]
Thank you for using Element,
All questions should be directed to https://matrix.to/#/#element-web:matrix.org and dev coordinations happens in https://matrix.to/#/#element-dev:matrix.org
