### ISSUE TITLE
SSL Certificate invalid. Browser element AND element desktop affected. Images failed to download, then avatars disappeared.

### ISSUE THREAD

**Issue by unknown-user-9246102101** [vector-im/element-web#24174]
### Steps to reproduce

1. Where are you starting? What can you see?

<img width="649" alt="Screenshot_20230105_090700" src="https://user-images.githubusercontent.com/35440139/210921962-40f7c7b8-5990-4890-88b5-24be2a8fb145.png">

3. What do you click?
Clicked on "homeserver's ssl certificate is trusted"

4. More steps…
<img width="758" alt="Screenshot_20230105_090446" src="https://user-images.githubusercontent.com/35440139/210922070-fd911ccb-ec6a-4603-a542-8a5248d76d2e.png">

This is for web. I shut down my desktop client first but it had images failing to load as a symptom.

#### What did you expect?
A working SSL certificate

#### What happened instead?
Cloudflare says it's invalid, I would paste the actual cert but MITM prevents that. That's ok though.

### Operating system

Windows 11

### Browser information

Chrome Version 108.0.5359.125 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/login

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by austinbutler** [comment]
Same issue. Matrix.org seems effectively totally down due to this.

Probably this isn't the right place to report the issue since it's not an issue with Element, but I don't know of any better place either.

Matrix status is green: https://status.matrix.org
No chatter on Twitter: https://twitter.com/matrixdotorg

So :shrug:

**Comment by turt2live** [comment]
Thanks for reporting this issue - the operations team was notified shortly after the incident began and is currently working on remediation. 

Closing this issue in favour of the matrix.org repo: https://github.com/matrix-org/matrix.org/issues/1601
