### ISSUE TITLE
Adding Seshat for search in E2E encrypted rooms

### ISSUE THREAD

**Issue by tschreier** [vector-im/element-web#24178]
I would like to install SQLCipher on Windows but I can't find a hint anywhere on how to do it.
Without SQLCipher <yarn add matrix-seshat>  the compilation aborts with an error:

note: Non-UTF-8 output: LINK : fatal error LNK1181: Input file \"sqlcipher.lib\" cannot be opened.\r\n
error: could not compile `seshat-node` due to previous error
neon ERR! cargo build failed

#### Why would you like to do it?
I would like to build the element-desktop client with some modification
 
#### How would you like to achieve it?
https://github.com/vector-im/element-desktop/blob/develop/docs/native-node-modules.md
![image](https://user-images.githubusercontent.com/1712585/210956489-88dd9483-3a84-400e-b417-3123821af97f.png)

**Comment by gsouquet** [comment]
I would suggest discussing this in https://matrix.to/#/#element-dev:matrix.org.
Parts of that documentation hint that it is possible to install SQLCipher on Windows
