### ISSUE TITLE
Message cannot be decrypted, unable to decrypt attachment or message, Decryption issues, Unable to decrypt

### ISSUE THREAD

**Issue by jittygitty** [vector-im/element-web#24172]
### Steps to reproduce

I had posted this issue in Element Desktop about Decryption issues:
https://github.com/vector-im/element-desktop/issues/500
But it was closed with reference that we should instead open such issues inside Element Web even if we're using desktop (since its same codebase I think).
(see https://github.com/vector-im/element-desktop/issues/471 )

As a "follow-up" to the issue I initially posted at:
https://github.com/vector-im/element-desktop/issues/500

Today I just had another Decryption issue, but this time in a channel with 3 people who were all registered/signed in on matrix.org and who were all using matrix.org server and not any custom homesever/dendrite etc. When I try to click a recent Text File Attachment upload, the .txt says its 163B , when i click on attachment link, i get a popup saying Error, Error decrypting attachment.

Element Desktop version is: 
Element version: 1.10.10
Olm version: 3.2.8

#### What did you expect?
I would expect no decryption errors.

#### What happened instead?
I got decryption errors.

Ctrl-Shift-I  on Element Dekstop shows;
Uncaught (in promise) TypeError: Failed to fetch
    at a.downloadSource (://vector/webapp/bundles/......./vendors~init.js:2:384282)
......
rageshake.ts:72 Unable to decrypt attachment:  TypeError: Failed to fetch
    at a.downloadSource (://vector/webapp/bundles/.../vendors~init.js...)
    at s.getFn ....
    at s.get value [as value] .....
    at i.decryptFile ...
    at ....    at Object.ze .....
    at Ye ...  at wr ...
e.<computed> @ rageshake.ts:72
rageshake.ts:72 Starting load of AsyncWrapper for modal

(It's difficult to correlate the console errors since I'm not familiar with it and don't see easy way to correlate specific error to its chat comment/post/attachment/etc)

Personally, I think that some of these errors could at least be easier to live with if we even had the OPTION to CACHE ALL LOCALLY as soon as it's received, because scrolling up through chat I notice now even Images that previously had worked, now have some small red triangle with exclamation mark, saying "Error decrypting image".

Currently if a server has any problems, you're locked out of your chat history. Now I realize this is a moot point for Element "WEB", but it isn't for Element "DESKTOP" or other client "apps". So for desktop app or other client apps, it would be nice to have option to LOCALLY SAVE all content. (Not sure if someone requested the feature already...)

Otherwise, yea, without such features, it's even more important that there be less of all these decryption issues.

### Operating system

Windows 10

### Application version

Element version: 1.10.10 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by turt2live** [comment]
I believe this issue will be related to the ongoing matrix.org outage - please track https://github.com/matrix-org/matrix.org/issues/1601 for updates.

**Comment by richvdh** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/28060
