### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by FreeBornAngel** [vector-im/element-web#24173]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

1. Page won't load.
![image](https://user-images.githubusercontent.com/18445737/210919702-354d5ee0-778c-4f7b-b9d6-a76bf6b61b11.png)

### Operating system

linux

### Browser information

brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/room/#hivediscord:matrix.org

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Thanks for reporting this issue - please see https://github.com/vector-im/element-web/issues/24174#issuecomment-1373125062

**Comment by turt2live** [comment]
for backlinks: https://github.com/matrix-org/matrix.org/issues/1601

**Comment by FreeBornAngel** [comment]
And,....it's back.
