### ISSUE TITLE
my element isn't working anymore

### ISSUE THREAD

**Issue by Yadiel9p** [vector-im/element-web#24177]
### Steps to reproduce

i can't get my element to work and I'm looking for help here because i can't get in my element it keeps saying this in the screenshot below and i don't understand why it won't let me do anything 
![Screenshot (601)](https://user-images.githubusercontent.com/122074136/210931940-adb5a0da-e148-48fb-ac27-b60b00e95f1d.png)

### Outcome

 What did you expect?

to have my element working back to normal

What happened instead? 

element isn't working for me

### Operating system

Windows 

### Application version

Element version: 1.11.17 Olm version: 3.2.12

### How did you install the app?

https://element.io/download

### Homeserver

idk my home server 

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Thanks for reporting this issue. This will be related to an ongoing incident at matrix.org - please follow https://github.com/matrix-org/matrix.org/issues/1601 for updates.
