### ISSUE TITLE
Domains containing Unicode codepoints not fully recognized even if protocol is included

### ISSUE THREAD

**Issue by pludi** [vector-im/element-web#24180]
### Steps to reproduce

In any chat include a URL containing Unicode codepoints outside alphabets. This was noticed with the URL [http://↑↑↓↓←→←→ba.tk/](http://↑↑↓↓←→←→ba.tk/)

#### What did you expect?
URL getting rendered as [http://↑↑↓↓←→←→ba.tk/](http://↑↑↓↓←→←→ba.tk/)
#### What happened instead?
URL getting rendered as http://↑↑↓↓←→←→[ba.tk/](http://ba.tk/)

Example:

![image](https://user-images.githubusercontent.com/2112148/211036465-8d044345-89d5-48f5-9e56-94b3e6c6f4bb.png)

### Operating system

Ubuntu, Mint

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by pludi** [comment]
Possibly related to #5808 that needs to be fixed upstream in [Hypercontext/linkifyjs](https://github.com/Hypercontext/linkifyjs)

**Comment by t3chguy** [comment]
Indeed
![image](https://user-images.githubusercontent.com/2403652/211787653-92d196ef-5cb2-4f9d-95a5-eeba931d0dec.png)

**Comment by pludi** [comment]
Opened upstream ticket as Hypercontext/linkifyjs#427

**Comment by pludi** [comment]
Marked as fixed in version 4.1.1 upstream.

**Comment by t3chguy** [comment]
Blocked on https://github.com/vector-im/element-web/issues/24589 then

**Comment by Johennes** [comment]
We jumped to 4.1.1 with https://github.com/matrix-org/matrix-react-sdk/pull/11132 and this seems fixed on nightly now.

<img width="376" alt="Screenshot 2023-07-11 at 18 56 53" src="https://github.com/vector-im/element-web/assets/1137962/28047e5a-bf49-4ec9-876b-e1c202687e48">
