### ISSUE TITLE
Element on fedora crashes after a few seconds

### ISSUE THREAD

**Issue by cbro-cert** [vector-im/element-web#24185]
### Steps to reproduce

1. Where are you starting? What can you see?
I use element mostly on Fedora and sometimes Manjaro. 
Server is https://matrix.cert.ccc.de, other users are unaffected, also my installations on  Mac and Android. 
A few seconds after starting the app it crashes giving the error message "Oops ... we´re sorry. It looks like Element crashed, please contact the developers "

3. What do you click?
sometimes reading messages, sometimes nothing, it even crashes right after fresh installation. 

5. More steps…
I tried restarting the  app and the OS, new installation, emptying cache via Element, new installation after deleting config an cache manually. Nothing hat a lasting effect. 
It seems though, after deleting cace/reinstallation the crashes take a little longer to appear. 
 
[issue.txt](https://github.com/vector-im/element-web/files/10362953/issue.txt)
[log-0.log](https://github.com/vector-im/element-web/files/10362954/log-0.log)
[Uploading log-1.log…]()
/rageshake 

#### What did you expect?
to work properly like before

#### What happened instead?
app quits after a few seconds

/rageshake

--- Running report_uReport ---
Fehler: No segments found in coredump './coredump'
(»report_uReport« abgebrochen durch 1)

### Operating system

Fedora, Manjaro 

### Application version

Version von Element: 1.11.17 Version von Olm: 3.2.12

### How did you install the app?

via "Software" App / Flatpak

### Homeserver

https://matrix.cert.ccc.de

### Will you send logs?

Yes

**Comment by dhaneshsabane** [comment]
I'm facing the same issue on my Fedora install.

Software Information:

OS: Fedora 37 Workstation
Element version: 1.11.17
Installed via: Flatpak

I tried to run the app via the terminal using `flatpak run im.riot.Riot` and I saw the following output:

```
➜ flatpak run im.riot.Riot                                                                                   
/home/dhanesh/.var/app/im.riot.Riot/config/Element exists: yes
/home/dhanesh/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 12:50:42.931: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:50:42.932: Failed to load module "pk-gtk-module"
Gtk-Message: 12:50:42.932: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:50:42.932: Failed to load module "pk-gtk-module"
[3:0108/125042.947528:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0108/125042.947570:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
[45:0108/125049.534319:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[45:0108/125049.545742:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[45:0108/125057.244565:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

A quick search on the internet pointed me to a Bug in Electron - https://github.com/electron/electron/issues/32760

Maybe this is related?

**Comment by e00E** [comment]
I have probably the same issue. It started happening maybe a week ago. Using the element-desktop package on Arch.

I run element-desktop from the shell. The last two lines, that appear immediately before the crash are
```
ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
element-desktop terminated by signal SIGSEGV (Address boundary error)
```
The last line is printed by my shell, not element-desktop.

**Comment by turt2live** [comment]
Please report this to the flatpak maintainers: https://github.com/flathub/im.riot.Riot

**Comment by e00E** [comment]
This issue should not be closed. As I have described in my post experience a similar issue without flatpack.

**Comment by turt2live** [comment]
@NebulaOnion it appears as though your log segment is missing details, but it sounds like https://github.com/vector-im/element-web/issues/23311
@e00E your issue is https://github.com/vector-im/element-web/issues/23311

**Comment by razerrazer** [comment]
I have the same issue on Fedora 37, please let me know if i can provide anything that can help to solve this issue.

**Comment by MartenBE** [comment]
I have this issue for months now on both my desktop and laptop running Fedora ...
