### ISSUE TITLE
New decryption overlay should change layout when window is half-screen sized

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24183]
### Steps to reproduce

1. On a reasonably average external monitor, lay out your browser window so it takes up half the screen (right or left)
2. Open a threaded message

#### What did you expect?
The message looks good

#### What happened instead?
The message is laid out badly:
![Screenshot from 2023-01-06 17-02-01](https://user-images.githubusercontent.com/51663/211061421-99239ac9-8472-44a7-8d8d-7a3f63fafcc5.png)

### Browser information

Chromium 108.0.5359.124 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 5b730f4-react-ff34fc71d9e1-js-bba4a35665b9 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MdNomanUddin** [comment]
hey i want to contribute to this issue how can i start and where is the location of this issue

**Comment by SarthakKl** [comment]
Hi @kittykat, I want to work on this issue. Can you please give me a pointer on where to start?

**Comment by Spartan09** [comment]
@kittykat Where is the decryption overlay?

**Comment by ABHIXIT2** [comment]
@kittykat  So to be clear here the issue is that the layout of the messages doesn't look normal or looks bad when oppend in a smaller window(whith thread open)??
