### ISSUE TITLE
Element - BUG or Design Issue - Automatically Logs me out If my PC Crashes

### ISSUE THREAD

**Issue by AppTester7** [vector-im/element-web#24184]
### Steps to reproduce

Element always logs me out if my PC crashes
After reboot element shows me its log-in screen (Despite the "Start automatically after system login" option in settings > Preferences

This is extremely problematic for Encrypted Messages, as by design, if you choose to logout of your account you will lose ALL keys for the current
session, which will prevent you from being able to decrypt other peoples messages

The matrix.org evelpoment team or the devs of the elment app cannot give any guarantees as to weather a PC might crash or not
(it could crash even due to hardware related issues such as the processor heat sink not being effective at one point)

#### What did you expect?
I expect to have element automatically log me into my account

#### What happened instead?
I was met with the normal login screen

Upon logging in - i had some encrypted messages in a room i could no longer decrypt

### Operating system

Linux

### Application version

1.11.17

### How did you install the app?

https://element.io/download

### Will you send logs?

Yes

**Comment by AppTester7** [comment]
I was not able to get error logs
Element displayed "Failed to send log: No connected database" either when i attempted to send them or when i went to download them :(

**Comment by turt2live** [comment]
The error you're getting when trying to send logs appears to also explain why the app is logging you out: it's not able to store anything for some reason, which is leading to data being wiped when you restart.

I would suggest visiting [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) to diagnose the issue and report bugs discovered in that process, as it's a bit difficult to provide support here.
