### ISSUE TITLE
Message cannot be decrypted by room participants

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#24181]
### Steps to reproduce

1. I send a message in a room or DM
2. The other user complains that they cannot decrypt
3. I can decrypt their message though

#### What did you expect?
The other user to be able to read my message

#### What happened instead?
The other user not being able to read my message

### Operating system

Windows 11

### How did you install the app?

Element

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by kongo09** [comment]
Unfortunately, log collecting is also broken as it spins forever:

![image](https://user-images.githubusercontent.com/640121/211060440-1b51f695-6478-45f5-94e5-506bbef355ee.png)

**Comment by lectrode** [comment]
I've got the same issue, but on the other side of the transaction (cannot decrypt messages sent to me) for the past ~17 hours. Uploaded logs to this issue. If it'd be better to create a separate issue, please let me know and  I'll do that.

**Comment by hplewis** [comment]
I have a similar issue where they can see my messages, but I can't see theirs (decryption key withheld). Having the other person logout and back in resolved it. This issue was entirely scoped to their 1 device in that 1 room (1-1 DM). Other rooms and others of their devices worked fine.

**Comment by turt2live** [comment]
This particular instance was related to an operational issue on matrix.org - closing as a known cause.

**Comment by weeman1337** [comment]
Should we create an issue for „decryption doesn't work, if home server is under load“? Even there is a technical reason for this: Try to explain to someone that the message arrives but the keys do not.
