### ISSUE TITLE
Quick Search instantly closes (Conduit)

### ISSUE THREAD

**Issue by timokoesters** [vector-im/element-web#24195]
### Steps to reproduce

1. Log in to conduit server (Feel free to DM me for an account)
2. Open the Ctrl-K search menu
3. Type anything

### Outcome

- Search instantly closes
Element logs:
`Uncaught (in promise) M_UNRECOGNIZED: MatrixError: [404] M_UNRECOGNIZED: Unrecognized request ([https://conduit.koesters.xyz/_matrix/client/unstable/org.mat…s2kw3c5%3Aconduit.rs/hierarchy?suggested_only=false&limit=50](https://conduit.koesters.xyz/_matrix/client/unstable/org.matrix.msc2946/rooms/!MtBkOeeMGE6s2kw3c5%3Aconduit.rs/hierarchy?suggested_only=false&limit=50))`
`TypeError: lt is undefined`

The network debugger shows that element first tried the v1 /hierarchy, then unstable /hierarchy (both of which currently fail on conduit with a 404 M_UNRECOGNIZED)

### Will you send logs?

No

**Comment by turt2live** [comment]
The endpoint was added in Matrix 1.2, meaning under the [js-sdk's support policy](https://github.com/matrix-org/matrix-js-sdk#matrix-javascript-sdk), we should be supporting it as of writing.

However, a spec release is right around the corner by a matter of weeks: I'm not sure the team will have a chance to add safe fallback code before then, or if the fallback code would be there long enough. Relatedly though, this issue highlights the importance of https://github.com/vector-im/element-web/issues/22346 - we shouldn't be connecting to homeservers which lack endpoints we need.

**Comment by timokoesters** [comment]
Thanks for the quick response. I didn't know about that issue yet and agree with your conclusion and I will close this issue
