### ISSUE TITLE
Replies to polls do not include formatted body

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#24197]
### Steps to reproduce

1. create a poll
2. reply to the poll in EW
3. observe no `<mx-reply>` formatted body in the reply message

### Outcome

Web should explicitly handle poll start events replies to match other platforms:

Eg reply to poll from iOS
```
  "content": {
    "body": "> <@user:matrix.org> %poll question%\n\n%reply content%",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!CVJnkRSzTJbFTaNblu%3Amatrix.org/%24aEFuRjG8nOYdyKl_62cj2_lVN9IqaTPyvRxvQgdVdNM\">In reply to</a> <a href=\"https://matrix.to/#/@user:matrix.org\">@user:matrix.org</a><br>%poll question%</blockquote></mx-reply>%reply content%",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$xxxx"
      }
    },
  },
```

### Will you send logs?

No

**Comment by turt2live** [comment]
worth noting that the presence of reply fallback was somewhat recently diminished to a SHOULD in the spec (ie: not including the fallback is entirely valid): https://spec.matrix.org/v1.5/client-server-api/#fallbacks-for-rich-replies
