### ISSUE TITLE
Broadcast notifications show [object Object] or the wrong state if setting „All messages“

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#24193]
### Steps to reproduce

1. Force the notifications of a room to be "All Messages"
2. Start a Voice Broadcast from another user of the room
3. Pause/Resume the VB
4. Observe the notifications

#### What did you expect?

- „Someone started a voice broadcast“
- „Someone paused a voice broadcast“
- etc.

To be honest I didn't expect notifications for state events. But if the web client forces notifications on all events because of the settings "All Messages", we have to handle these notifications.

#### What happened instead?

For a started event: „Someone ended a voice broadcast“
For other events: „[object Object]“

I observed notification with unexpected content
<img width="383" alt="image" src="https://user-images.githubusercontent.com/8969772/211383691-5cb1c0e1-39a5-4785-99f9-9539ba763907.png">

### Will you send logs?

No

**Comment by turt2live** [comment]
is this https://github.com/vector-im/element-web/issues/24192 ?

**Comment by weeman1337** [comment]
One is „mute everything except start events“ - the other is „show a useful message“. This morning I would say we can merge these. I will take care of the issues.

**Comment by weeman1337** [comment]
We found that if „Notify all“ is enabled we get broken notifications (this issue). There should be a notification about a started broadcast for default notification settings (other issue).

I will clarify in the descriptions.
