### ISSUE TITLE
Timeline bounces when switching rooms

### ISSUE THREAD

**Issue by leonerd** [vector-im/element-web#2419]
When I click a room name in the LHS bar to switch the display, almost immediately the timeline view switches and displays the correct content from the new room, but then bounces up to some part of earlier history, before jumping back down to the correct time again. The whole thing seems to take about a second.

It's largely cosmetic so not a huge problem but I wonder if it's wasting CPU somewhere doing something unnecessary, because it did get the right place initially, only to go wrong then right again.

(Browser: Firefox 45.3.0)

**Comment by leonerd** [comment]
Also happens on Firefox 49.0

**Comment by neutralinsomniac** [comment]
Another data point: oftentimes after switching rooms the scrolling will jump up for me, but not re-set itself to the bottom, leaving me hanging in the middle of the room history. What's worse is that the "scroll to bottom" button doesn't get shown in this scenario either until I scroll manually to trigger it.

**Comment by SimonBrandner** [comment]
@leonerd, is this still a problem?

**Comment by jryans** [comment]
Let's assume probably not. Please reopen or file a new issue if this still happens.
