### ISSUE TITLE
M_UNKNOWN for a room that exists

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24200]
### Steps to reproduce

1. Within develop.element.io, looking at the room listedn in the error message below.
2. Saw an update was available and clicked Update Now

#### What did you expect?

To return to the room I was looking at.

#### What happened instead?

I received this message:

```
#element-web-internal:matrix.org is not accessible at this time.

Try again later, or ask a room or space admin to check if you have access.

M_UNKNOWN was returned while trying to access the room or space. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose).
```

### Operating system

Ubuntu 22.04

### Browser information

Firefox 108.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 5b730f4b07b1-react-b1c32995c679-js-e2ce379b56b9 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Soon afterwards I received `Connectivity to the server has been lost.` banner (at the same time as this comment)

**Comment by andybalaam** [comment]
When I refresh the page I get the same error, but when I switch to the room with Ctrl-K, it appears.

**Comment by argentatus-larus** [comment]
Same problem on app.element.io

**Comment by andybalaam** [comment]
Getting this in console:

```
Getting filter failed M_UNKNOWN: MatrixError: [429] Server is unavailable (https://matrix-client.matrix.org/_matrix/client/r0/user/%40andybalaam%3Amatrix.org/filter)
```

**Comment by andybalaam** [comment]
So I'm being rate-limited.

**Comment by argentatus-larus** [comment]
Same (RVS failed to get room id for alias: ...

I'm not sure what is RVS

**Comment by andybalaam** [comment]
I saw an issue that was causing lots of requests, but I can't find it. If this is an example of that issue, I remember that it was actually fixed, but any users hit by it need to wait for the queue of requests to drain and then it will start working again.

If/when I find the issue number I'll double-check this and then mark this as a duplicate if that seems right.

Meanwhile, matrix.org might be struggling a bit, maybe because of this problem.

**Comment by andybalaam** [comment]
It seems to be healthier for me now. @argentatus-larus ?

**Comment by richvdh** [comment]
sorry, this was a partial utage on matrix.org, between 10:30 and 11:10 or so, UTC.

**Comment by argentatus-larus** [comment]
Same, all good, thank you!

**Comment by richvdh** [comment]
> I saw an issue that was causing lots of requests

you may be thinking of https://github.com/vector-im/element-web/issues/24167?

**Comment by weeman1337** [comment]
> you may be thinking of https://github.com/vector-im/element-web/issues/24167?

At least for me, it didn't trigger a rate limiting on m.org. Do the rate limit checks depend on the endpoints?

**Comment by richvdh** [comment]
> At least for me, it [#24167] didn't trigger a rate limiting on m.org. Do the rate limit checks depend on the endpoints?

Yes, but I don't think #24167 is related here, and nor are per-user rate limits.

**Comment by andybalaam** [comment]
> you may be thinking of #24167? I don't think that's related here.

Yes I was, thank you.

**Comment by andybalaam** [comment]
OK, so this was down to a partial outage on matrix.org, closing.
