### ISSUE TITLE
[Rich text editor] can't ping a user

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-web#24217]
#### What would you like to do?
Start writting @someo and that it suggests @someone and we can select the user and ping the user.
#### Why would you like to do it?
To be able to ping a user in a room or averybody with @room as we can do it when the Rich text editor is not enabled

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23880

**Comment by Thatoo** [comment]
Good. Sorry, I thought commands starting with / and ping starting with @ was two different things, that's why I opened a new issue but if it is the same then good.
