### ISSUE TITLE
App fails to load in a Firefox private browsing window

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24216]
### Steps to reproduce

1. Open a firefox private browsing window
2. Go to https://staging.element.io

#### What did you expect?

a working app

#### What happened instead?

Infinnispinner

### Browser information

Firefox

### URL for webapp

https://staging.element.io

### Will you send logs?

No

**Comment by richvdh** [comment]
From the console logs:

```
16:15:57.588 unable to delete IndexedDBCryptoStore: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. [rageshake.ts:64:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
16:15:57.588 Failed to remove IndexedDB instance matrix-js-sdk::matrix-sdk-crypto: [object Event] [rageshake.ts:64:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
16:15:57.588 Uncaught (in promise) Error: Error clearing storage: [object Event]
```

**Comment by richvdh** [comment]
Introduced by https://github.com/matrix-org/matrix-js-sdk/pull/2969

**Comment by ashughes1** [comment]
Does not look like this is 100% fixed, filed issue 24234.
