### ISSUE TITLE
Poll replies overflow when not enough space (e.g. open side panel)

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24227]
### Steps to reproduce

1. Start a poll
2. Reply to it
3. Open a side panel or narrow the window

#### What did you expect?

Layout same for polls and the reply

#### What happened instead?

Poll reply overflows. Happens with all layouts (IRC, modern, bubble)

![image](https://user-images.githubusercontent.com/6216686/212329355-b2c84302-b4b3-413b-89b6-045545dd533e.png)

![image](https://user-images.githubusercontent.com/6216686/212329434-55e1825a-f58a-45dc-81e9-b73df9706a32.png)

Non-bubble layout

![image](https://user-images.githubusercontent.com/6216686/212329758-d64dd8f8-7732-46ae-9ab6-f4532925c5ba.png)

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 109.0 (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Element version: 4aa3b0b6370a-react-b9e987876b5e-js-789aec732adb Olm version: 3.2.12

### Will you send logs?

No

**Comment by weeman1337** [comment]
Similar issue has been reported in the past https://github.com/vector-im/element-web/issues/22005

**Comment by Johennes** [comment]
This looks somewhat awful so we should pick this up in the ongoing polls work under the non-critical bugs milestone. 
@mnaturel could you make a ticket for it?

CC @kerryarchibald also as it looks like you fixed a similar issue [before](https://github.com/matrix-org/matrix-react-sdk/pull/8459).

**Comment by mnaturel** [comment]
> This looks somewhat awful so we should pick this up in the ongoing polls work under the non-critical bugs milestone. @mnaturel could you make a ticket for it?
> 
> CC @kerryarchibald also as it looks like you fixed a similar issue [before](https://github.com/matrix-org/matrix-react-sdk/pull/8459).

Sure, done!
