### ISSUE TITLE
Forgot password : other element-web session is not logged out

### ISSUE THREAD

**Issue by estellecomment** [vector-im/element-web#24228]
### Steps to reproduce

 - sign in in Chrome in session 1
 - sign in in Firefox in session 2, same account.
 - In session 2, go to Forgot password. Complete the flow, and select "disconnect other sessions" when prompted. The password is reset.

#### What did you expect?

session 1 is logged out.

#### What happened instead?

session 1 is not logged out. 
Reloading page : still not logged out. 
Session 1 can still send messages, which are received by recipient.

### Operating system

macOS

### Browser information

Firefox 108.0.2 (session 2) and Chrome 108.0.5359.124 (session 1)

### URL for webapp

app.element.io

### Application version

1.11.17

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@estellecomment you write Homeserver matrix.org but your rageshake shows a different server. What Matrix server version is that Homeserver running?

**Comment by estellecomment** [comment]
Ah ! Wrong log ! I tried both matrix.org and Tchap's server, and sent you the wrong one. (got the same issue on both)
Sent new ones from rageshake, from both sessions. You can ignore the first one.

**Comment by weeman1337** [comment]
Regressed by new password reset flow
