### ISSUE TITLE
hide password change option if user logged in with cas/ldap/etc

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#2423]

**Comment by richvdh** [comment]
Also "deactivate account" ?

**Comment by muppeth** [comment]
it looks like users can change password which then results in two passwords they can authenticate with both.
I dont think its cosmetics it;s rather serious issue.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/3379

**Comment by felinira** [comment]
This could actually be seen as a security issue: If the LDAP password is weak and the password is changed to a stronger password in synapse the old password still works and most users will not notice.

**Comment by t3chguy** [comment]
IMO this should be signalled by the HS using the `m.change_password` capability.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/11944
