### ISSUE TITLE
Big ping to 146.112.x.x

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24244]
### Steps to reproduce

1. Use Element Desktop
2. Monitor connections to see IP 146.112.41.2
3. Check ping

#### What did you expect?
Low ping.
#### What happened instead?
Ping 400-5000 ms.

### Operating system

Windows 7

### Application version

1.11.17

### Will you send logs?

No

**Comment by t3chguy** [comment]
146.112.41.2 is Cisco OpenDNS doh.opendns.com - are they your DNS provider by chance?

**Comment by JeanPaulLucien** [comment]
@t3chguy 
No. Element connects to it.

**Comment by JeanPaulLucien** [comment]
Yeah, I suppose it's complex issue of Element and Matrix servers. Ping is too big. Unfortunatelly, I have captured a moment and did not see this IP more.

**Comment by JeanPaulLucien** [comment]
> Windows 7 is no longer a supported environment - https://github.com/vector-im/element-web#supported-environments
There is nothing to do for me.
