### ISSUE TITLE
Error page even after clearing cache in one browser

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#24245]
### Steps to reproduce

1. Open https://develop.element.io in qutebrowser on one specific computer.
2. "Something went wrong" error page.
3. Click "Clear cache and reload"
4. "Something went wrong error page"
5. Clear site data from developer tools.
6. Log back into my account on https://matrix.thebeckmeyers.xyz
7. "Something went wrong error page"

#### What did you expect?
To be able to use Element from the browser on this computer (everything works fine on other computers)
#### What happened instead?
"Something went wrong error page"

### Operating system

Void Linux

### Browser information

qutebrowser v2.5.2; Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144; Qt: 5.15.7 (compiled 5.15.5)

### URL for webapp

develop.element.io

### Homeserver

matrix.thebeckmeyers.xyz (synapse 1.75.0)

### Will you send logs?

Yes

**Comment by DrZingo** [comment]
Same thing here, with almost the same setup. I can also confirm that it worked yesterday on this exact computer/setup.

**Steps:**
app.element.io
cleared cache with button on page - same issue.
cleared cache, cookies etc from developer tools - still the same.

**Browser info:**
qutebrowser v2.5.2 
QtWebEngine 5.15.3
Qt: 5.15.6

**Operating system:**
Alpine 3.17

**Comment by qvatch** [comment]
getting this in windows 10 now

Steps:
already logged in to app.element.io
Click to upgrade
"Something went wrong" error page.
cleared cache with button on page - same issue.

Element version: 1.11.18, Olm version: 3.2.12 [these are the numbers shown in settings>help/about on the window that is showing the error page]

Browser info:
Firefox 89.0.1

OS:
Windows 10 Pro, v2004, build 19041.508, feature 120.2212.31.0

**Comment by uhoreg** [comment]
There is a known issue with the latest version and certain browsers.  The team is working on a fix.

From the Element announcements room:

> NOTE NOTE NOTE: this release has a known problem in browsers supporting older web standards. We are working on a fix now.

**Comment by uhoreg** [comment]
This should be fixed in the latest release (1.11.19).  Can you try again?

**Comment by andybalaam** [comment]
Huge apologies from all of the team for letting this issue slip through.

Fixed in v1.11.19

**Comment by non-Jedi** [comment]
Can confirm that this is fixed on develop.element.io. Apologies for not reporting this issue sooner; I've been having it for several days. Might have avoided it making its way into a release if I had taken the time to do so.
