### ISSUE TITLE
On-the-fly formatting via hotkeys

### ISSUE THREAD

**Issue by vertigo220** [vector-im/element-web#24257]
#### What would you like to do?
Toggle formatting _as I type_ via hotkeys, like you can do here on Github, as opposed to having to type something, then select it, then press the hotkey

#### Why would you like to do it?
To make composing messages faster and easier by allowing for a more fluid and natural typing experience

#### How would you like to achieve it?
By making the hotkeys for formatting work like they do here, so pressing them _while typing_ inserts the appropriate markdown elements without having to first select the text. Also, ideally, improve on how it works here by having it add the markdown when pressed the first time and move to the end of it when pressed the second time. IOW, whereas in Github if you press ctrl+i and type a word, you get two underscores when pressing it, then you type the word, then you have to either arrow past the second underscore or hit the end key. It would be ideal if you could just press ctrl+i again, and instead of it just removing the underscores/italics, if it would automatically move to the right of the next underscore.

**Comment by dbkr** [comment]
This is already the case in the rich text editor in labs

**Comment by vertigo220** [comment]
Does it work in the method I described or like it does here on Github? And how can I access it? I don't see anything about the editor in labs, just video rooms, threaded messages, and new session manager.

**Comment by t3chguy** [comment]
@vertigo220 labs is available via Element Nightly & develop.element.io - otherwise the list is only showing Betas

**Comment by vertigo220** [comment]
Is there a special repo or place to discuss issues with the nightly/labs? I find the implementation of this feature to be done very poorly and would like to share my thoughts. Specifically, it's different from every other implementation of such a feature I've ever used, going all the way back to the original Word/WordPad and similar writer software, where instead of pressing the shortcut/hotkey _before_ typing the word, you press it _during or after_ typing it, which is very counter-intuitive. And even then, it still doesn't shift the cursor past the markdown characters, e.g. the _ when italicizing something.
