### ISSUE TITLE
Highlighting / Pinning chat comments

### ISSUE THREAD

**Issue by vertigo220** [vector-im/element-web#24256]
#### What would you like to do?
Pin something from chat to make it always visible or highlight it to make it easier to find later

#### Why would you like to do it?
To increase visibility and make sure things don't get lost/forgotten and help with keeping track

#### How would you like to achieve it?
Just like you can react/reply/edit comments, you should also be able to pin and highlight them. Pinning seems to be already a work in progress, though it's unclear exactly. Highlighting doesn't appear to be previously requested or worked on, and it should be easier to add, as it would probably just be another formatting option. Only it would be nice to also have highlighted lines show in the scrollbar like search terms do in Chrome to make them easier to find later.

**Comment by dbkr** [comment]
I'm not quite sure what the difference between pinning and highlighting is here, but this sounds like the pinned messages functionality which is labs.

**Comment by vertigo220** [comment]
Pinning, I'm guessing, sticks a copy of the message to the top and/or sidebar. Highlighting simply highlights the message in place. As I said in the OP, it's just another type of formatting. Highlighting is a very different thing from pinning, and this issue shouldn't be closed.
