### ISSUE TITLE
Rich text editor reverses line order in code blocks

### ISSUE THREAD

**Issue by domestomas** [vector-im/element-web#24251]
### Steps to reproduce

1. Enable rich text editor in labs
2.  Select "show formating"
3. Paste message consiting of more lines, e.g. 

one
two 
three
four
five

4. select the message and click "code block"
5. send the message

#### What did you expect?
one
two 
three
four
five

#### What happened instead?
one
five
four
three
two

### Operating system

Linux mint 21.1

### Application version

Element 1.11.17

### How did you install the app?

from the repository

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by alunturner** [comment]
Hello, thanks for the report.

This issue has been fixed as part of a large bit of work prior to our most recent release and has been tested and passed using the above test case.
