### ISSUE TITLE
Flatpak installation crashes after few seconds

### ISSUE THREAD

**Issue by ahangarha** [vector-im/element-web#24250]
### Steps to reproduce

1. I install element (im.riot.riot) from flathub on my Ubuntu 22.10
2. I log in without an issue and verify the session
3. Now onwards, the app crashes without any particular pattern observed

#### What did you expect?
The app to work normally

#### What happened instead?
This is the terminal log when I run the app from terminal:
```
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 15:46:25.875: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:46:25.876: Failed to load module "canberra-gtk-module"
[3:0118/154625.895675:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0118/154625.895733:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Fetching translation json for locale: en_EN
Changing application language to en-us,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
[44:0118/154627.665584:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!



[53:0118/154638.621840:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

### Operating system

Ubuntu 22.10

### Application version

1.11.17

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ahangarha** [comment]
This might be relevant in some way: I am doing this from Iran. Ensure this might be because of either some internet filtering from the Iranian government (though I can use the app without any issue on my phone and even in those few seconds after launching the app, I can see my messages) or because of some filtering from the servers against Iranian IPs. Even in such cases, we shouldn't experience crashes.

Again, this is just a side note which might be helpful for debugging.

**Comment by t3chguy** [comment]
The flatpak is community maintained, please file issues at https://github.com/flathub/im.riot.Riot/

**Comment by ahangarha** [comment]
I have opened [an issue](https://github.com/flathub/im.riot.Riot/issues/322) on the mentioned repo above. I think it is worth looking at [this comment](https://github.com/NicolasConstant/sengi/issues/222#issuecomment-1401215486).
