### ISSUE TITLE
Enable or add option for inverse of "Use Ctrl + Enter to send a message" so it will add a newline

### ISSUE THREAD

**Issue by vertigo220** [vector-im/element-web#24258]
#### What would you like to do?
I prefer to hit enter to send a message, but I also like to have the ability to add a new line (carriage return / line feed). There's an option to use ctrl+enter to send messages, which then allows you to create a new line with enter, but with that disabled, the inverse isn't true, i.e. you can't use ctrl+enter to add a new line.

#### Why would you like to do it?
See above

#### How would you like to achieve it?
Add another option that's active if this option is disabled, allowing the user to use ctrl+enter for a new line, or just do it automatically, since it's unlikely it would be an issue for anyone.

**Comment by t3chguy** [comment]
Shift enter is newline
