### ISSUE TITLE
Open another device to load encrypted messages...

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24267]
### Steps to reproduce

1. You need try to visit encrypted rooms.

#### What did you expect?
???
#### What happened instead?
I see "Unable to decrypt message" instead message. I can't see text before and other info was instead them. But now I see also 

> Open another device to load encrypted messages
> This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.

And no way to close that. It's visible all time and it does not confirm keys.

### Operating system

Windows 7

### Application version

1.11.17

### Will you send logs?

No

**Comment by JeanPaulLucien** [comment]
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: The sender has disabled encrypting to unverified devices. **"
  }
}
```

**Comment by dbkr** [comment]
We'll need logs from both yourself and the sender to investigate this.

**Comment by t3chguy** [comment]
> The sender has disabled encrypting to unverified devices

This signals that the sender of the message has chosen to only encrypt to verified devices.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2403652/213680651-fedb612d-08c0-490f-aa90-59ab15bd21c9.png">

You should ask them to turn it off or for them to verify you

**Comment by JeanPaulLucien** [comment]
General issues it's 

> Open another device to load encrypted messages
> This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.

all time. No way to close that.

**Comment by JeanPaulLucien** [comment]
General issues it's 

> Open another device to load encrypted messages
> This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.

all time. No way to close that.

**Comment by JeanPaulLucien** [comment]
Element is not support

**Comment by BotoX** [comment]
Give me an option to close this crap, even better a setting to permanently hide it.
I don't care about other people purposefully breaking their chat, show this warning to them instead.
The box is taking up valuable screen space and there is NO WAY TO CLOSE IT AAAAA

**Comment by viendocraz** [comment]
I am also experiencing this on Window x64 Desktop using v1.11.23, only other users are Android F-Droid flavour (installed recently) Android 11/Android 12, All using one room and homeserver self-hosted running Synapse. 

One of the Android devices also has messages of the type "Unable to decrypt: The sender's device has not sent us the keys for this message" which we cannot seem to get rid of. 

Have tried logging out and logging in again using the security phrase. Also have tried import the keys again on the Windows x64 Desktop version. The problem still persists and the UI continues to display the message with no option to dismiss. There is the option to "View your devices list" but seemingly not much you can do there. 

In the console log on the Desktop version, I see a 404 error trying to reach "https://matrix.domain.com/_matrix/client/v3/room_keys/keys/<RANDOM STRING>matrix.domain.com/<RANDOM STRING>?version=2" which seems like a weird URL but not sure if this is related. Also a few instances of "Error decrypting event".

Not sure what other info would be useful or how to obtain it for anyone looking into this.

**Comment by viendocraz** [comment]
I would add that if you scroll past the "Unable to decrypt message" errors, then the "Open another device to load encrypted messages" is no longer visible.

**Comment by olymk2** [comment]
It's not clear what needs to be "resend request seems to do nothing" view verified devices shows all devices as verified ie they ave a tick checking on another device does not seem to change any thing either so kind of stuck with the message, be nice if it could at least tell me which devices it thinks are unverified. mine or senders ? 

I will uncheck the verify for now I guess based on the suggestion above but the usability here need improvement as a technical person I am not sure how to proceed for any one un technical they would have even less idea and probably go to other services if they can not fix it.

**Comment by t3chguy** [comment]
> I see the issue is marked as closed, but we're facing the same problem so wasn't sure if this should be a new issue. This started for us after upgrading to 1.81.0 and still exists in 1.82.0. 

Those version numbers don't match this application @johndball, we're currently only up to 1.11.30.

**Comment by hieronymousch** [comment]
I have the same issues, running a Yunohost Synapse server, version 1.83. Only get this issue with a single iOS device. I already upgraded the room, cleared cache, removed sessions, ... still getting this error on both Element Web & Element Android.

**Comment by NeonMinnen** [comment]
Same issue. Seems to be happening with one of my iOS clients as well.

**Comment by kenwuuu** [comment]
sent debug logs using this github issue's url

**Comment by dnisbetjones** [comment]
I can also report that this issue happens specifically with sending images and seemingly only to and from iOS users.

**Comment by bhauer** [comment]
I've subscribed to this issue because I'm seeing the same problem on my Matrix instance, running Element-web 1.11.29 and Synapse 1.81.0. Specifically: *periodic* instances of messages from iOS clients that cannot be decrypted by others using Element-web, which causes the "Open another device to load encrypted messages" dialog to appear. That dialog ultimately does nothing when the user selects "Resend key requests." From my perspective, it seems clear every client has the keys it needs, but messages aren't being sent correctly.

As @johndball said, perhaps this should be a new issue since this one has been closed. But for whatever it's worth, this is the most significant defect I've seen in Matrix since adopting it years ago, so I hope it sees some attention.

**Comment by bhauer** [comment]
I am now seeing this issue propagating into multiple channels and affecting multiple users. It seems to be getting worse. I suspect the more general "Unable to decrypt" issue (#25221) may be more applicable to me now. While I am seeing the permanent "Open another device to load encrypted messages" alert box that cannot be dismissed, I think the underlying issue is simply a problem with encryption stemming from iOS clients, and perhaps iOS clients sending photos.

**Comment by jsimmonsworks24** [comment]
Agree with bhauer. I keep having to reinstall the application on 2 iOS devices. Encryption usually breaks on the device, after sending a picture through element.

**Comment by sanjayws** [comment]
One of the many reasons my team just can't take Elements + Matrix anymore. It's just too clunky.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I have been experiencing this problem for a few releases as well. I think it might have happened around the time the [iOS Element software started using a different _crypto_](https://github.com/vector-im/element-ios/releases/tag/v1.10.10).

I can open the same conversation in iOS and see the message, but when I view it on the desktop, it is unable to decrypt.
