### ISSUE TITLE
"Unable to decrypt: Error: leading sigil is incorrect or missing" in 1.11.19

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-web#24260]
### Steps to reproduce

1. Update to 1.11.19.
2. All encrypted rooms show just these errors...
![obrazek](https://user-images.githubusercontent.com/15554561/213370460-9a570bac-7e20-46d8-ba7e-ce493e15a517.png)

#### What did you expect?
See encrypted messages.

#### What happened instead?
Element Web cannot decrypt any message.
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: Error: leading sigil is incorrect or missing **"
  }
}
```

### Operating system

Windows 10

### Browser information

Firefox 109.0

### URL for webapp

self hosted

### Application version

Element version: 1.11.19 Olm version: <not-enabled>

### Homeserver

self hosted Synapse 1.76.0

### Will you send logs?

Yes

**Comment by waclaw66** [comment]
Logs cannot be sent...
![obrazek](https://user-images.githubusercontent.com/15554561/213370669-796f421a-a139-4e89-83ac-614cac14a25d.png)

**Comment by richvdh** [comment]
Hi @waclaw66, thanks for the report.

I notice you're self-hosting the webapp. Do you have a customised `config.json`? Please could you share it if so.

**Comment by waclaw66** [comment]
Hi @richvdh, there shouldn't be anything harmfull. I've tried to cut it as much as possible, but no success.

```json
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.bolesiny.net",
            "server_name": "bolesiny.net"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "Element",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "default_country_code": "CZ",
    "show_labs_settings": true,
    "default_federate": true,
    "default_theme": "light",
    "room_directory": {
        "servers": [
            "matrix.org",
            "bolesiny.net"
        ]
    },
    "piwik": {
        "url": "https://matomo.bolesiny.net/",
        "whitelistedHSUrls": ["https://matrix.org"],
        "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
        "siteId": 2
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": true,
        "https://matrix-client.matrix.org": true
    },
    "setting_defaults": {
        "breadcrumbs": true
    },
    "jitsi": {
        "preferred_domain": "meet.element.io"
    },
    "element_call": {
        "url": "https://call.element.io",
        "participant_limit": 8,
        "brand": "Element Call"
    },
    "branding": {
        "welcomeBackgroundUrl": "https://matrix.bolesiny.net/forrest.jpg"
    },
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
```

**Comment by richvdh** [comment]
Thanks. Have you previously experimented with the `feature_rust_crypto` setting?

**Comment by waclaw66** [comment]
@richvdh yes, I have. I have had enabled it for a while.

**Comment by t3chguy** [comment]
@waclaw66 you'll likely need to log out and back in then to clear it

**Comment by t3chguy** [comment]
<img width="712" alt="Screenshot 2023-01-19 at 17 08 34" src="https://user-images.githubusercontent.com/2403652/213512726-fe32a8fe-e41f-496b-80a6-a547ad55fff5.png">

**Comment by waclaw66** [comment]
Yes, I enabled it there, but the it stayed enabled in Eleement Web even when I set it to false in config.json.

**Comment by t3chguy** [comment]
Yes, it is intentionally sticky, it isn't interchangeable, it doesn't store things in the same formats or places.
