### ISSUE TITLE
"Composer" > "WYSIWYG" > "sends a message when you click send or press Enter" is flaky

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#24269]
https://cloud.cypress.io/projects/ppvnzg/runs/8462/test-results/51558f28-d140-4a83-9723-78f1b2ca4779

![Screenshot 2023-01-19 at 21-44-22 matrix-react-sdk](https://user-images.githubusercontent.com/48614497/213606919-a6d35520-a189-4842-9ffa-7f9e82beade4.png)

**Comment by florianduros** [comment]
Huch again, I though I had fixed it 😡

**Comment by robintown** [comment]
Thanks, then let's consider this fixed until proven otherwise
