### ISSUE TITLE
CPU loading is higher now

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24278]
### Steps to reproduce

1. Use Element Desktop
2. Monitor processes and CPU usage on Element and svchost.exe

#### What did you expect?
Same like in 1.11.17 and 1.11.18
#### What happened instead?
CPU usage is higher

### Operating system

Windows 7

### Application version

1.11.20

### How did you install the app?

In-app update

### Will you send logs?

No

**Comment by t3chguy** [comment]
Windows 7 isn't a supported environment, if users on supported environments see the same place comment and we can re-open https://github.com/vector-im/element-web#supported-environments

**Comment by ZenKyma** [comment]
I can confirm the same higher CPU load (up to 30% at times) on my linux OS (Solus Budgie 4.3). Became aware of it when my laptop fan went full speed and immediately stopped when killing the element process.
