### ISSUE TITLE
after a redact, one can get unread badges for their own messages

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2427]
How I saw it: Matthew redacted one or several messages in our 1:1, then everytime I was sending a message I had an unread badge in the LHS panel for my own message. there was no read marker for Matthew (as he hadn't come back to the room since I started talking after his redact

**Comment by Kegsay** [comment]
I got this yesterday in a 1:1 but it was an unread badge for the redacted event. It seems to be reproducible in 1:1 rooms by:
 - Read up to the latest message
 - B sends message which will be redacted
 - A reads it(?)
 - B redacts the message.
 - Badge count now incorrect.

Viewing the room does reset the count though, this isn't a persistent stuck notification.

**Comment by aaronraimist** [comment]
Does this still exist?

**Comment by turt2live** [comment]
I'm assuming it does not still exist.
