### ISSUE TITLE
Previous Element version still consumes memory

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24279]
### Steps to reproduce

I suppose these steps to reproduce:
1. Use not latest version.
2. Get notification about new version and press "Update"
3. Wait when new version will be installed and Element restarted.

Part of https://github.com/vector-im/element-web/issues/24236
#### What did you expect?
Previous version does not consume memory
#### What happened instead?
Previous version still consume about 39 MB of memory.
![Element Desktop 1 11 20 - 1 11 19 in memory](https://user-images.githubusercontent.com/24779886/213777104-11f14a2e-e5f6-4207-9c61-ae778a397088.jpg)

### Operating system

Windows 7

### Application version

1.11.20

### How did you install the app?

In-app update

### Will you send logs?

No

**Comment by JeanPaulLucien** [comment]
https://github.com/vector-im/element-web/issues/24236

**Comment by JeanPaulLucien** [comment]
![Element Desktop 1 11 20 - 1 11 19 in memory - 02](https://user-images.githubusercontent.com/24779886/213780273-be279898-eb08-4859-bdd4-d8a72046b4e9.jpg)
It's really exists on my PC.

**Comment by t3chguy** [comment]
Sorry Windows 7 is no longer a supported environment - https://github.com/vector-im/element-web#supported-environments
