### ISSUE TITLE
Superfetch (svchost.exe) consumes much memory

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24280]
### Steps to reproduce

0. Use previous version (1.11.19 was) and update it using in-app UI.
1. Just start Element Desktop.
2. Go to monitor how much svchost.exe uses memory.

#### What did you expect?
Less than 200 MBs
#### What happened instead?
Svchost.exe consumes 220-250 MBs.

### Operating system

Windows 7

### Application version

1.11.20

### How did you install the app?

In-app update

### Will you send logs?

No

**Comment by t3chguy** [comment]
Svchost is not part of Element, it is part of Windows. Not sure what it has to do with Superfetch either? https://en.wikipedia.org/wiki/Svchost.exe

**Comment by t3chguy** [comment]
> Windows 7

This is not a supported environment as of two years ago.

https://github.com/vector-im/element-web#supported-environments
