### ISSUE TITLE
"Your browser can't run Element" after most recent update

### ISSUE THREAD

**Issue by EvocativeOlash** [vector-im/element-web#24284]
### Steps to reproduce

1. Opens straight to "Unsupported browser
Your browser can't run Element
Element uses advanced browser features which aren't supported by your current browser.

Please install [Chrome](https://www.google.com/chrome), [Firefox](https://firefox.com/), or [Safari](https://apple.com/safari) for the best experience.

You can continue using your current browser, but some or all features may not work and the look and feel of the application may be incorrect.

I understand the risks and wish to continue
Use Element on mobile
iOS (iPhone or iPad)"

2. The "I understand the risks and wish to continue" button is unresponsive.
3. Attempt to reinstall using web installer just brings up this window again.
"
![image](https://user-images.githubusercontent.com/38131177/213882410-a656047b-95c9-4454-8858-01f1acc014c5.png)

#### What did you expect?

Update

#### What happened instead?

Start to nonfunctional state

### Operating system

Windows 11

### Application version

1.11.20.0

### How did you install the app?

https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe

### Will you send logs?

Yes

**Comment by EvocativeOlash** [comment]
Ok figured out the user data in roaming was corrupted, deleted that for reinstall.

**Comment by weeman1337** [comment]
> Ok figured out the user data in roaming was corrupted, deleted that for reinstall.

Did this solve your issue?

**Comment by EvocativeOlash** [comment]
Yes but I lost access to encrypted chat log from the past.
