### ISSUE TITLE
links in topic tooltip aren't clickable

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2428]
if you have a room with a long topic, you can read the whole thing by hovering over it for a tooltip. It would be nice to do this ourselves rather than using `title` so that we can linkify links in the topic.

**Comment by ara4n** [comment]
We have a PR for this already (https://github.com/vector-im/vector-web/pull/2287) but it's a bit hacky.

**Comment by aaronraimist** [comment]
https://github.com/vector-im/riot-web/issues/1836 seems like a better solution to me

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/9623
