### ISSUE TITLE
UISI: requested by Matthew

### ISSUE THREAD

**Issue by Arkaniad** [vector-im/element-web#24299]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Operating system

macOS Monterey 12.5.1

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### How did you install the app?

from Homebrew `element` package

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing as https://github.com/vector-im/element-x-ios-rageshakes/issues/28 looks to have attributed it to EX bugs
