### ISSUE TITLE
@room not working

### ISSUE THREAD

**Issue by kaspot** [vector-im/element-web#24293]
### Steps to reproduce

the @room thing is not working on Mac desktop client and web, as well as on iphone ... 

#### What did you expect?
that all in the room would be notified ;-)
#### What happened instead?
it is just written in a text but without the real function behind it

### Operating system

MacOS 12.1, Mac iOS, iPhone 12 Pro, Chrome

### Application version

Version 1.11.20 (1.11.20)

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thank you for reporting the issue @kaspot . Sending an `@room` notification requires the „Notify everyone“ permission. Can you check, if you have the permission in your test room?

![image](https://user-images.githubusercontent.com/6216686/214233515-a0a96721-65b7-4766-a028-8b3b5fdb9a58.png)

**Comment by t3chguy** [comment]
Closing due to lack of requested info
