### ISSUE TITLE
Save users into contacts with custom information

### ISSUE THREAD

**Issue by GithubUser96** [vector-im/element-web#24302]
#### What would you like to do?
I'd like to save users in Element as contacts, provided I can rename them, so they show up in the chat list with custom names or at least make it so that one can change the room name without it affecting the other person.
#### Why would you like to do it?
Would improve the usability of the app greatly. When many chats are present under nicknames, it gets hard to distinguish the chats from one another.
#### How would you like to achieve it?
Add contacts section to the app. Make room metadata only viewable for one person.

### Have you considered any alternatives?

Yes, there are currently none.

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/341

**Comment by flo1o1** [comment]
apparently this is rather a duplicate of element-hq/element-meta#726

**Comment by flo1o1** [comment]
Further related links:

https://github.com/matrix-org/matrix-spec/issues/188
https://github.com/matrix-org/matrix-spec-proposals/pull/3015
