### ISSUE TITLE
One to one calls are broken since 1.11.18 (1.11.17 is ok)

### ISSUE THREAD

**Issue by steinex** [vector-im/element-web#24306]
### Steps to reproduce

Since Element 1.11.18 one to one video calls are broken. They get signalled and ring but either there is no video or the window with the call does not open at all. Element 1.11.17 is ok.

#### What did you expect?

When calling someone or get called the video widget should pop up and I should be able to have a call normally.

#### What happened instead?

Either the video widget does not pop up at all or there is only black video.

### Operating system

Void Linux

### Browser information

Firefox 109.0

### URL for webapp

self-hosted 1.11.18 and above

### Application version

1.11.18 and above

### Homeserver

Synapse 1.75.0

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Cannot repro :/

**Comment by SimonBrandner** [comment]
Could you please share your logs, they could help us diagnose the issue

**Comment by steinex** [comment]
I can share logs tommorow. How do I do that though? I have no `/rageshake` command.

**Comment by andybalaam** [comment]
Removed the regression label since we're not sure whether this is a regression or not at this point.

**Comment by steinex** [comment]
I uploaded logs now. As noted, the call is ringing but I only see a black window of my peer. Audio is working, though. Downgraded to 1.11.17, cleared cache and it suddenly works again.

**Comment by steinex** [comment]
Another thing to note: My peer is having video/audio correctly and he's using exactly the same Element instance. I'm not sure what could be the issue on my side though since Element 1.11.17 works just fine.

**Comment by SimonBrandner** [comment]
We'd have to manually add unused transceivers to do this, I guess it could be useful for calls in general though it'd be some effort

Also, this would require quite a bit of UI work

**Comment by SimonBrandner** [comment]
You're right, sorry :rofl:

**Comment by SimonBrandner** [comment]
Is it possible you're seeing https://github.com/vector-im/element-web/issues/20584 ?

**Comment by steinex** [comment]
This looks like my issue, yes. However, when I downgrade to 1.11.17 the problem is gone and the issue you linked seems much older.

**Comment by SimonBrandner** [comment]
Right, interesting, interesting... :thinking:

**Comment by steinex** [comment]
I just uploaded another rageshake with a call active on 1.11.17 where the problem does not appear. Maybe you are able to spot a difference from the defect vs. non-defect rageshake?

**Comment by steinex** [comment]
This turned out to be a TURN issue on my side most probably. Can not reproduce anymore. I'm closing this.
