### ISSUE TITLE
Error getting the event index passphrase out of the secret store

### ISSUE THREAD

**Issue by i-a-m-a-k** [vector-im/element-web#24300]
### Steps to reproduce

1. Open element-desktop
2. Wait for a few seconds

### Outcome

_Expected behaviour_: I should be able to use the program normally
_What happens_: Program crashes after few seconds

Since the program crashes before I can execute `/rageshake` I have attached the log I took by executing `element-desktop > log.txt` in the terminal.

```
/home/<user>/.config/Element exists: yes
/home/<user>/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: The name org.freedesktop.secrets was not provided by any .service files]
```

I have `keepassxc` installed which provides the `org.freedesktop.secrets` service.

### Operating system

Arch Linux

### Application version

1.11.20-1

### How did you install the app?

pacman

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hey :wave: @i-a-m-a-k @odiferousmint Please report issues for the Arch / Void packages to their repos

- https://bugs.archlinux.org/?project=5&string=element-desktop
- https://github.com/void-linux/void-packages

 If you encounter this issue on the official packages then please let us know and we can reopen.

**Comment by felixx9** [comment]
same #24521

**Comment by CicadaCinema** [comment]
I have the same issue on the Flatpak for a fresh install of Fedora Linux 37.

**Comment by chimere2** [comment]
I have the same issue with the Flatpak package on Fedora 37 and Fedora 36, but it is working with Fedora 35.

**Comment by t3chguy** [comment]
@hunter2k01 @CicadaCinema @chimere2 please report issues with the flatpak to https://github.com/flathub/im.riot.Riot/

**Comment by iam-TJ** [comment]
Experienced this today after a package upgrade: `element-desktop:amd64 (1.11.26, 1.11.30)`  and tried starting it many times:
```
...
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: The name is not activatable]
Trace/breakpoint trap 
```
And then, to try to aid diagnostics, I started it via `gdb` debugging session and it started correctly! I then quit it and tried it without `gdb` and it works!
```
$ apt-cache policy element-desktop
element-desktop:
  Installed: 1.11.30
  Candidate: 1.11.30
  Version table:
 *** 1.11.30 500
        500 https://packages.element.io/debian default/main amd64 Packages
        100 /var/lib/dpkg/status
```
with Debian 11 Bullseye amd64.

**Comment by srmfx** [comment]
Not working on archlinux anymore, i tried both schildichat-desktop-bin and schildichat-desktop-git, got the same error on both after a pacman -Syu, everything else seems to be workig fairly 'OK', so it's definitively an issue on schildi's end.
``` 
(electron:33841): Gtk-WARNING **: 17:16:51.938: Failed to parse /home/spamtla/.config/gtk-3.0/settings.ini: Key file does not have group “Settings”
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: The name is not activatable]

```

**Comment by cgalo5758** [comment]
Same issue on Fedora Linux 39.

```
Error getting the event index passphrase out of the secret store [Error: org.freedesktop.DBus.Error.ServiceUnknown]
/app/bin/element: line 16:     3 Illegal instruction     (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

Element opens, but then it crashes as soon as I input key strokes.

**Comment by blockisec** [comment]
I receive same error after latest upgrade on debian

**Comment by t3chguy** [comment]
> What is meant by this? Why is the scope limited to specific Linux distributions' packages?

Because issues with keytar (the module responsible for the "secret store") is very finnicky to package

**Comment by pm4rcin** [comment]
The same has happened for me after flatpak update. I use keepassxc as provider. It was working fine before but after update it stopped communicating and asking keepass for the key. Here's some logs:
```bash
Error getting the event index passphrase out of the secret store TypeError: keytar.setPassword is not a function
    at getOrCreatePassphrase (file:///app/Element/resources/app.asar/lib/seshat.js:42:30)
    at async IpcMainImpl.<anonymous> (file:///app/Element/resources/app.asar/lib/seshat.js:90:36)
```

**Comment by Sazu-bit** [comment]
I get the same log, I don't understand why it worked last month, but this month... since element updated, issues.
