### ISSUE TITLE
Cannot view room from space home after upgrading

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24329]
### Steps to reproduce

I upgraded the Element web app team room which was in the WAT space. After the room upgrade, I can see both the old and new room in the `m.space.child` state event. On the space home page, the room sows up (a single time) but clicking the "view" button or trying to delete it does nothing.

#### What did you expect?

The buttons to work as they did before and to take me to the _new_ room.

#### What happened instead?

Nothing.

### Operating system

macOS

### Application version

Element Desktop nightly

### Will you send logs?

No

**Comment by weeman1337** [comment]
`O-Occasional` spaces are quite common. `S-Major` because I cannot join or view a room, that I can see in the space list.

**Comment by Johennes** [comment]
Console error on web:

```
Uncaught TypeError: room is undefined
    showRoom SpaceHierarchy.tsx:365
    onViewRoomClick SpaceHierarchy.tsx:807
    onViewRoomClick SpaceHierarchy.tsx:480
    onPreviewClick SpaceHierarchy.tsx:120
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 15
    loadApp init.tsx:150
    start index.ts:228
    async* index.ts:239
    <anonymous> bundle.js:1444
    __webpack_require__ bundle.js:838
    fn bundle.js:130
    <anonymous> bundle.js:1068
    __webpack_require__ bundle.js:838
    <anonymous> bundle.js:1055
    <anonymous> bundle.js:1058
2 SpaceHierarchy.tsx:365:8
```

**Comment by Johennes** [comment]
Looks like [`/_matrix/client/v1/rooms/{roomId}/hierarchy`](https://spec.matrix.org/latest/client-server-api/#get_matrixclientv1roomsroomidhierarchy) doesn't return the new room. That in turn is likely because the new room seems to be missing the `via` parameter in 

**Old room**

```
{
  "content": {
    "suggested": false,
    "via": [
      "matrix.org",
      "element.io",
      "riot.ovh"
    ]
  },
  "origin_server_ts": 1674562905343,
  "sender": "@johannesm:element.io",
  "state_key": "...",
  "type": "m.space.child",
  "unsigned": {
    "age": 241155595
  },
  "event_id": "...",
  "room_id": "..."
}
```

**New room**

```
{
  "content": {},
  "origin_server_ts": 1674662312761,
  "sender": "@johannesm:element.io",
  "state_key": "...",
  "type": "m.space.child",
  "unsigned": {
    "age": 141748160
  },
  "event_id": "...",
  "room_id": "..."
}
```

`via` is [required](https://spec.matrix.org/latest/client-server-api/#mspacechild) and:

> When not present or invalid, the child room is not considered to be part of the space.

**Comment by Johennes** [comment]
And finally `toLocalRoom` converts the old room in the hierarchy returned by the server to the latest room in the room upgrade history:

```
const toLocalRoom = (cli: MatrixClient, room: IHierarchyRoom): IHierarchyRoom => {
    const history = cli.getRoomUpgradeHistory(room.room_id, true);
    const cliRoom = history[history.length - 1];
    if (cliRoom) {
        return {
            ...room,
            room_id: cliRoom.roomId,
```

So that explains why the room with the _new_ ID is used in the room list.

**Comment by Johennes** [comment]
So I think there are two bugs here:

1. When upgrading the room, the new one was added into the old one's space but no `via` parameter was set, technically making it _not_ part of the space.
2. When resolving the latest room version, we don't verify whether the corresponding room is actually in the space or not.

**Comment by Johennes** [comment]
> So I think there are two bugs here:
> 
>     1. When upgrading the room, the new one was added into the old one's space but no `via` parameter was set, technically making it _not_ part of the space.
> 
>     2. When resolving the latest room version, we don't verify whether the corresponding room is actually in the space or not.

2 was fixed with https://github.com/matrix-org/matrix-react-sdk/pull/10010

**Comment by Johennes** [comment]
I've tested this again locally for another room and I'm not able to reproduce issue 1 anymore. The `via` parameter is correctly set. Unsure what went wrong the last time. Closing this for now.
