### ISSUE TITLE
Gitter sunsetting: ensure hidden highlights code respects MSC3946

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24324]
Adapt the code inside RoomView to call `findPredecessor` instead of manually extracting room predecessor from the create event.

Pass through the MSC3946 feature flag to `findPredecessor` to ensure it has the correct behaviour.

**Comment by andybalaam** [comment]
Chatting to Eric this morning, https://github.com/vector-im/element-web/issues/24325 seems more urgent.

Meanwhile, testing `RoomView` is proving very annoying, so putting this on hold and picking up 24325

**Comment by andybalaam** [comment]
I looked at this briefly and found testing RoomView tricky. Feel free to give me a ping if you'd like to talk it through.

**Comment by andybalaam** [comment]
This change only affects whether you see "hidden highlights": notifications from an old room. This does not seem important enough to block Gitter sunsetting.
