### ISSUE TITLE
Screensharing crashes Element

### ISSUE THREAD

**Issue by Lalilalulalam** [vector-im/element-web#24321]
### Steps to reproduce

During videocall there is an option to start screensharing. Once clicked, pop-up windows appears, clicking "share entire screen" results in instant crash.

#### What did you expect?
Start sharing.
#### What happened instead?
Application crash.

### Operating system

Fedora Workstation 37

### Application version

1.11.20

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Lalilalulalam** [comment]
[element_crash.log](https://github.com/vector-im/element-web/files/10502708/element_crash.log)
![Zrzut ekranu z 2023-01-25 20-09-58](https://user-images.githubusercontent.com/94278457/214660977-27e8d022-7619-4d77-8ae0-7b001d3c097a.png)

**Comment by SimonBrandner** [comment]
The Flatpak version is not officially supported, I would suggest opening an issue at https://github.com/flathub/im.riot.Riot
