### ISSUE TITLE
Subscribing to many rooms in a space leads to crashes

### ISSUE THREAD

**Issue by BastianZim** [vector-im/element-web#24330]
### Steps to reproduce

1. Visit space
2. Subscribe to many rooms
3. Process fails

#### What did you expect?
Succeeds and subcribes
#### What happened instead?
Crashes but subscribes to some

### Operating system

macOS

### Browser information

Safari Version 16.2 (18614.3.7.1.5)

### URL for webapp

https://app.element.io

### Will you send logs?

Yes

**Comment by justjanne** [comment]
Likely duplicate of https://github.com/vector-im/element-web/issues/22752

**Comment by SimonBrandner** [comment]
Closing as duplicate of https://github.com/vector-im/element-web/issues/22752
