### ISSUE TITLE
Notification for thread root and message for thread reply

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24336]
### Steps to reproduce

1. Create a thread
2. Clear all notifications
3. Send a message from another user to the thread

#### What did you expect?

A notification for the new message

#### What happened instead?

Two notifications: One for the thread root, another for the message

![image](https://user-images.githubusercontent.com/6216686/214787128-c91774f3-accc-4cc8-88a6-c8e63655fcab.png)

### Operating system

Ubuntu 22.04 LTS

### Application version

Element Nightly version: 2023012501 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

element.ems.host

### Will you send logs?

No

**Comment by weeman1337** [comment]
Cannot reproduce any more →close

**Comment by t3chguy** [comment]
I'm still seeing this
