### ISSUE TITLE
When starting a thread I see the root message twice

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24335]
### Steps to reproduce

1. Send a message
2. Directly click „reply in thread“

#### What did you expect?

Thread root message once

#### What happened instead?

Thread root message twice

![image](https://user-images.githubusercontent.com/6216686/214785836-84f0e644-a20a-4427-90bc-fa2378bbbd5c.png)

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 109

### URL for webapp

https://develop.element.io/

### Application version

Element version: bd26775dcb2c-react-222f8a919dd9-js-ef51ee28fda9 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Hmm I have not been able to reproduce this issue at all.
Is that something you still encounter? I don't think I've seen it

**Comment by weeman1337** [comment]
I will open it if it occurs again. Maybe it is more likely to happen on a slow connection / server with load :man_shrugging:
