### ISSUE TITLE
Element Desktop App keeps activating the dedicated GPU on Legion 5 Pro 2021

### ISSUE THREAD

**Issue by martinderm** [vector-im/element-web#24345]
### Steps to reproduce

1) Open App
2) App uses dGPU
3) kill all processes using the dGPU (by [LegionToolkit](https://github.com/BartoszCichecki/LenovoLegionToolkit)) 
4) element sub-process restarts and uses dGPU again

<img width="452" alt="image" src="https://user-images.githubusercontent.com/6137077/214947224-5c0455e1-482a-489b-a57a-8f683a3fa342.png">

#### What did you expect?
Element desktop app should use the integrated GPU

#### What happened instead?
Element desktop app uses discrete GPU

### Operating system

Windows 11 22623.1180 (KB5022363)

### Application version

Version von Element: 1.11.21-rc.1 Version von Olm: 3.2.12

### How did you install the app?

Official Website /Auto-Update

### Homeserver

no

### Will you send logs?

No

**Comment by t3chguy** [comment]
You can disable GPU acceleration in Settings > Preferences > `Enable hardware acceleration (restart %(appName)s to take effect)`
