### ISSUE TITLE
Clearing Cache deletes Session Data and Login

### ISSUE THREAD

**Issue by TheTinyProwler** [vector-im/element-web#24356]
### Steps to reproduce

1. Where are you starting? 
I am using Element web in the Ferdium Multimessenger.  During use teh caqche infinitely grows. I have to clear it from time, usually i do this when its size surpasses 2 GB. From the beginning, by clearing the cache i wipe out the login and the session data, so i have to login and restore the session data.
2. What can you see? 
I get a popup which tells me about what happened and advises me to logout, then login and restore the session. This all works well but to have to go through the process is annoying. 
3. What do you click?
Due i want to use Element, i follow the instructions...
- I would like to send the protocol data but i dont know where to find them.

### Operating system

Linux Mint 19.3

### Browser information

Multimessenger Ferdium 

### URL for webapp

matrix.org?

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hi @TheTinyProwler :wave:  Thanks for reporting the issue.

> I am using Element web in the Ferdium Multimessenger. During use teh caqche infinitely grows. I have to clear it from time, usually i do this when its size surpasses 2 GB. From the beginning, by clearing the cache i wipe out the login and the session data, so i have to login and restore the session data.

How do you clear the cache? From Ferdium or Element Web settings? Can you send a screenshot of this option?

**Comment by TheTinyProwler** [comment]
![issue-report-screenshot](https://user-images.githubusercontent.com/39658925/215516307-72f3574e-078b-42ab-96a6-8523acedd4e2.png)

I am using the option within the ferdium settings, it's located in the "advanced" options, see
screenshot.

**Comment by t3chguy** [comment]
What Ferdium calls "Cache" likely includes IndexedDB and/or Local Storage then.
Anyhow, an unsupported environment as per https://github.com/vector-im/element-web#supported-environments

I suggest reaching out to their support for help
