### ISSUE TITLE
Activate markdown when hotkey is pressed *before* starting to type word

### ISSUE THREAD

**Issue by vertigo220** [vector-im/element-web#24358]
#### What would you like to do?
I created issue #24257 which was misunderstood and prematurely closed, so I'm opening this one and clarifying. Currently, the hotkeys for activating formatting like bold and italics only work once you've started typing a word, which is contrary to how it works everywhere else (document editors like Word, here in GitHub, etc) and leads to being more difficult to use as well as my (and possibly others) thinking the hotkeys don't work on-the-fly while typing. It's standard to be able to press a hotkey, ctrl+i for example, _before_ starting to type a word and have it activate the corresponding formatting, whether rich-text or markdown. This is how it works in the RTE in labs, and how it works here, but not how it works in markdown in Element. For that, you have to start typing the word _then_ press the hotkey, and that's the problem I was trying to request a fix to in the other issue.

#### Why would you like to do it?
So it works like literally every other text editor I've ever used, thereby not causing confusion, thinking it doesn't work, and making it easier to use, instead of having to change how I type just for this one app.

#### How would you like to achieve it?
By making it insert the markdown elements for formatting text (e.g. __ for italics, **** for bold) whenever the hotkeys are pressed, not just when the cursor is on a word, but also when on a blank space, so they can be activated _before_ typing a word. Also, if activated _after_ typing a word, maybe it should automatically shift the cursor to the right of the markdown elements, so the user doesn't have to arrow over, though this could be problematic if activated mid-word, though that seems unlikely.

**Comment by dbkr** [comment]
Hi - I closed your other bug because the intention is to switch to the rich text editor once it's finished. You've confirmed above that the rich text editor works as you expect. We'd be unlikely to consider changes to the legacy text editor at this point since it will be removed soon.

Do you still want to keep this bug open to track changing the behaviour of the legacy editor?

**Comment by vertigo220** [comment]
No, that's not necessary. I didn't realize it was replacing markdown, and thought the two were going to coexist with the user selecting one or the other. Thanks for the clarification, closing this issue.
