### ISSUE TITLE
Remove Threads from Beta and Labs

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24365]
### Your use case

Threads is no longer in Beta we should remove the references to it being in Beta and also remove the flag in Labs. 

(For those users who have turned off the labs flag, do we have to manage that or does it not matter?) 

We also need to remove the pop up saying "threads no longer experimental".

**Comment by daniellekirkwood** [comment]
@gsouquet & @justjanne I've been cheeky and gone ahead and assigned this to you ;) 
Let's chat in Element.

**Comment by gsouquet** [comment]
Will be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9878

**Comment by luixxiul** [comment]
Not sure whether it is fine to ask this here, but is it expected for Threads to be disabled when you click `Leave the beta` button on Element Web? This happens on Element 1.11.23 for me, not tested on a fresh profile.

**Comment by gsouquet** [comment]
Currently yes, once this PR lands you won't have the button nor a way to disable them.

**Comment by simonmichael** [comment]
I had recently disabled threads on both desktop and IOS and life was so much better. Sorry threads UX designers, but this feature wasn't worth the added complexity and difficulty in my usage. Please make them an option.

**Comment by axiopaladin** [comment]
Strongly encourage returning a toggle for this feature. I would very much like to turn them off, just as I did in the android client. Threads are terrible UX in my opinion.

**Comment by athompso** [comment]
I agree - I participate in a few private rooms where having threads turned on 100% guarantees I won't see messages.  Please make this a toggle - either globally, or even better, per room.  The only indication of new messages is a really subtle green dot up in the corner of the UI _when I'm in the room_,   A green dot that NEVER GOES AWAY so it has become utterly useless as an indicator.

**Comment by sheldonelectric** [comment]
Please offer an option to disable threads. My correspondant had to verbally tell me (!!!!) in which thread he had answered, because the message wouldn't show up where I expected (=in the bottom of the chat)
