### ISSUE TITLE
changing to dark mode gets error

### ISSUE THREAD

**Issue by alisafa1371** [vector-im/element-web#24364]
### Steps to reproduce

In schildi element-web  I decided to change the theme color from setting appearance . when I click on dark mode I get the below error on console:
```
theme.ts?6c0f:247 Uncaught (in promise) Error: Unknown theme dark
    at setTheme (theme.ts?6c0f:247:15)
    at ThemeWatcher.recheck (ThemeWatcher.ts?0fa8:94:21)
    at eval (ThemeWatcher.ts?0fa8:78:14)
    at localizedCallback (SettingsStore.ts?2f21:188:13)
    at WatchManager.notifyUpdate (WatchManager.ts?5392:72:13)
    at DeviceSettingsHandler.setValue (DeviceSettingsHandler.ts?1081:127:27)
    at SettingsStore.setValue (SettingsStore.ts?2f21:486:23)
    at eval (ThemeChoicePanel.tsx?7516:122:23)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:3994:1)

```
in **element-web folder** in **src/vector/index.html** there are some code that I think is responsible for providing styles for different theme .here is the code:
```
    <% for (var i=0; i < htmlWebpackPlugin.files.css.length; i++) {
        var file = htmlWebpackPlugin.files.css[i];
        var match = file.match(/^bundles\/.*?\/theme-(.*)\.css$/);
        if (match) {
            var title = match[1].charAt(0).toUpperCase() + match[1].slice(1);
        %>
           <link rel="stylesheet" disabled="disabled" data-mx-theme="<%= title %>" title="<%= title %>" href="<%= file %>">
        <% } else { %>
           <link rel="stylesheet" href="<%= file %>">
        <% }
    } %>

    <% for (var i=0; i < htmlWebpackPlugin.tags.headTags.length; i++) {
        var tag = htmlWebpackPlugin.tags.headTags[i];
        var path = tag.attributes && tag.attributes.href;
        if (path.includes("/Inter/")) { %>
            <link rel="preload" as="font" href=".<%= path %>" crossorigin="anonymous"/>
        <% }
    } %>
````
these code is supposed to  make style tag for all available themes like light,dark,dark-custom,legacy-dark and etc. ``` <style data-mx-theme="theme-name"></style> ``` 
my problem is that when my app renders I just have ```<style data-mx-theme="light"></style>``` and there are no other styles so when I try to change the theme I got the first error that I mentioned above.
How can I have all style tags ( data-mx-theme) for all themes ?

#### What did you expect?
Changing to dark mode
#### What happened instead?
Getting error that there is no theme dark

### Operating system

Windows

### Browser information

Chrome

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please send logs

**Comment by t3chguy** [comment]
> Application version

What application version?

**Comment by t3chguy** [comment]
> In schildi element-web

Please open issues specific to forks to their own projects

https://github.com/SchildiChat/schildichat-desktop
