### ISSUE TITLE
Sudden crashing on Arch Linux desktop

### ISSUE THREAD

**Issue by edwargix** [vector-im/element-web#24360]
### Steps to reproduce

1. start element from a terminal (kitty+zsh in my case) by running `element-desktop`.  I did this this just so I can capture the logs, but the problem also happens when using a launcher like dmenu
2. wait for a bit (usually 10 minutes)
3. CPU usage spikes from element
4. app crashes, displaying the 'core dumped' error below

```sh
[~]$ element-desktop 
/home/edwargix/.config/Element exists: yes
/home/edwargix/.config/Riot exists: no
[5293:0128/135819.049280:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[5293:0128/135819.049361:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Error getting the event index passphrase out of the secret store [Error: The name org.freedesktop.secrets was not provided by any .service files]
[5324:0128/135821.233092:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[5324:0128/135821.249789:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[5324:0128/135821.266147:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[5330:0128/140410.435240:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
zsh: trace trap (core dumped)  element-desktop
[~]$
```

#### What did you expect?

no crashing

#### What happened instead?

crashed

I am using [Sway](https://swaywm.org) [version 1.8](https://github.com/archlinux/svntogit-community/blob/31023f46a66d3b66aaf67b8a9e66e3e4097b22d9/trunk/PKGBUILD), but a few friends are also experiencing this issue on i3 and Xfce.  The problem seems to have started occurring within the last month or two.

In case it's relevant: I am a member of many e2ee rooms, and have my element configured to enable message search for encrypted messages.

### Operating system

Arch Linux

### Application version

Element version 1.11.20, olm version 3.2.12

### How did you install the app?

element-desktop package for arch: https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

Synapse 1.75.0 (using docker.io/matrixdotorg/synapse:latest)

### Will you send logs?

Yes

**Comment by edwargix** [comment]
might be the same issue: https://github.com/vector-im/element-web/issues/24319

**Comment by edwargix** [comment]
https://bugs.archlinux.org/task/77258

**Comment by florianduros** [comment]
Hi, thanks for the issue report!

Are you running on wayland ?

Seems to be related to #23202

**Comment by t3chguy** [comment]
Closing in favour of https://bugs.archlinux.org/task/77258 as this is a community maintained package and issue does not occur on first party packages
