### ISSUE TITLE
latest stable macOS version 1.11.21 or 1.11.20?

### ISSUE THREAD

**Issue by suschizu** [vector-im/element-web#24363]
**Describe the bug**
the website download (https://packages.riot.im/desktop/install/macos/Element.dmg) contains version 1.11.21-rc.1

the GitHub project marks 1.11.21-rc.1 as Pre-release 

**Expected behavior**
which one in the latest stable version?

**Scree
<img width="268" alt="Screenshot 2023-01-29 at 18 47 57" src="https://user-images.githubusercontent.com/16004333/215345647-e3272e45-db6a-4a5c-b97d-125abbfa0b60.png">
nshots**

**Desktop (please complete the following information):**
 - OS: 12.6
 - Browser: chrome + safari

**Comment by weeman1337** [comment]
It is 1.11.20. [There was an issue with the release last week](https://matrix.to/#/!bijaLdadorKgNGtHdA:matrix.org/$jtoXSPkruRuZXlrwRVaA8knRJBwHSGk5NqxRvueQTVE?via=matrix.org&via=element.io&via=envs.net).

**Comment by weeman1337** [comment]
> It is 1.11.20. [There was an issue with the release last week](https://matrix.to/#/!bijaLdadorKgNGtHdA:matrix.org/$jtoXSPkruRuZXlrwRVaA8knRJBwHSGk5NqxRvueQTVE?via=matrix.org&via=element.io&via=envs.net).
