### ISSUE TITLE
Read receipts have regressed visually

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#24375]
### Steps to reproduce

1. View any high-traffic room
2. Look at the read receipts

#### What did you expect?

Read receipts should be in groups of 3, stacked on top of each other from left to right, and there should be no gaps in the layout.

#### What happened instead?

Visually broken read receipts appearing in unevenly spaced groups of 4:

![Screenshot 2023-01-30 at 12-55-39 Element 1 Element Web Announcements](https://user-images.githubusercontent.com/48614497/215556027-f70d59d9-d067-4f68-a169-871373ed77f2.png)
![Screenshot 2023-01-30 at 12-54-00 Element 1 Element Web_Desktop](https://user-images.githubusercontent.com/48614497/215556033-9447ebe5-f8db-4e98-bcb0-ec2c54e58066.png)
![Screenshot 2023-01-30 at 12-52-54 Element 1 #webrtc matrix org](https://user-images.githubusercontent.com/48614497/215556035-f56f01a9-c03b-4218-a7b5-4b9704267e10.png)

Read receipts stacked in an unusual order:

![Screenshot 2023-01-30 at 12-56-39 Element 1 Element Web Announcements](https://user-images.githubusercontent.com/48614497/215556328-7e32ef82-1683-4ddf-a8c7-8524af01326d.png)

### Operating system

NixOS unstable

### Browser information

Firefox 108.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 50f2b532e907-react-e9d723269f2e-js-4f918f684e9d Olm version: 3.2.12

### Homeserver

Synapse 1.75.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Believed to be regressed by https://github.com/matrix-org/matrix-react-sdk/commit/a8aa4de4b4c14a6a995071aab3f2f871b3ff2388
