### ISSUE TITLE
Unable to decrypt messages or fetch keys to decrypt them

### ISSUE THREAD

**Issue by wayovermyhead** [vector-im/element-web#24378]
### Steps to reproduce

 1. Looking over messages in the Bisq General room, I can see an apparent struggle to decrypt messages going on.
 1. My MacBook Pro started struggling to decrypt in an encrypted room and despite signing in and out of Element, I continue to receive the following error message:
    > Some messages could not be decrypted
    >
    > Unfortunately, there are no other verified devices to request decryption keys from. Signing in and verifying other devices may help avoid this situation in the future.
 1. I left the room and tried to reenter and was urged to open an issue here due to an error.

#### What happened instead?

Decryption error messages keep reappearing.  Struggle to decrypt iMessages.  Final error message recited above. 

Messages in room prior to January 24 no longer appear.

### Operating system

Mac OS 10.15.7

### Application version

Version 1.11.21-rc.1 (1.11.21-rc.1)

### How did you install the app?

App Store, probably.  I downloaded last summer and had no issues until now

### Homeserver

Matrix

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hello!

Can you send the logs with `/rageshake` when you have the issue ? Thanks

**Comment by t3chguy** [comment]
Closing due to lack of requested info
