### ISSUE TITLE
Room list cuts off the last room

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#24370]
### Steps to reproduce

1. Fully expand a section of the room list to its maximum height
2. Scroll to the bottom

#### What did you expect?

To see all of my rooms

#### What happened instead?

In some spaces, the last room in the list is cut off:

![Screenshot 2023-01-30 at 10-26-13 Element 2 Test room](https://user-images.githubusercontent.com/48614497/215519718-61eea28c-bee7-4861-a9e5-d0e2a7bf2108.png)
![Screenshot 2023-01-30 at 10-25-52 Element 2 Discord bridge](https://user-images.githubusercontent.com/48614497/215519719-c54df12d-5a3c-43f4-b628-5462141eeb5f.png)
![Screenshot 2023-01-30 at 10-25-12 Element 2 general](https://user-images.githubusercontent.com/48614497/215519721-db2004e4-6a29-4edd-bf6f-5bb51eb88cda.png)

### Operating system

NixOS unstable

### Browser information

Firefox 108.0.2

### URL for webapp

develop.element.io

### Application version

Element version: 50f2b532e907-react-4c1e4f5127bd-js-4f918f684e9d Olm version: 3.2.12

### Homeserver

Synapse 1.75.0

### Will you send logs?

No

**Comment by weeman1337** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/a8aa4de4b4c14a6a995071aab3f2f871b3ff2388

**Comment by t3chguy** [comment]
I bet the spacing got bumped
