### ISSUE TITLE
Avatar overlays own message in threads panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24374]
### Steps to reproduce

1. Reply in a thread
2. Open thread panel in the all threads view

Note this works fine if someone else has sent the last reply in the thread

#### What did you expect?

I can see my message next to my avatar, not under it.

#### What happened instead?

My avatar overlays my own message:

![Screenshot from 2023-01-30 17-28-51](https://user-images.githubusercontent.com/51663/215550671-c819341f-561f-421d-9fcc-305f6081bb64.png)

### Browser information

Chromium 109.0.5414.74 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 50f2b532e907-react-5095bc0427a1-js-4f918f684e9d Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9990
