### ISSUE TITLE
GYU: Implement MSC3952 in matrix-js-sdk

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24376]
Picking up from https://github.com/matrix-org/matrix-js-sdk/pull/3092

**Comment by clokep** [comment]
[MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) depends on a few MSCs which we need to implement:

* [MSC3758](https://github.com/matrix-org/matrix-spec-proposals/pull/3758)
