### ISSUE TITLE
Border around selected spaces icon not uniform on develop

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-web#24382]
### Steps to reproduce

1. Create a new empty space called "Test"
2. Select the space
3. Note the border around the icon in the left-side panel

### Outcome

The border should appear fairly uniform around the icon, but on develop it is somewhat elongated. This does not appear to happen on already existing spaces, only when I create a new one does it do this.

# develop.element.io
![Screenshot from 2023-01-31 07-21-05](https://user-images.githubusercontent.com/766595/215805507-b32e6763-211c-4c89-892b-d6ee7e25b976.png)

# chat.element.io
![Screenshot from 2023-01-31 07-37-45](https://user-images.githubusercontent.com/766595/215805769-04b20c57-d2a4-42fa-86a7-79b4d170fecd.png)

### Operating system

Fedora Silverblue 37

### Browser information

Firefox 106.0.1

### URL for webapp

develop.element.io

### Application version

Element version:
`4c19d2bd0237-react-0d1fce37b22c-js-1c26dc02339c`

Olm version: 3.2.12

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9990
