### ISSUE TITLE
Space avatars in left panel are broken on develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24381]
### Steps to reproduce

1. Look at the left panel, where the space avatars are

#### What did you expect?
Nice, high contrast avatar fallbacks for spaces in the left panel

#### What happened instead?
Low contrast avatar fallback for spaces in the left panel

![Screenshot from 2023-01-31 15-21-56](https://user-images.githubusercontent.com/51663/215802422-e7c027bb-1c6c-43a8-985d-598bfe41bc82.png)

Also the outline border is broken for Anthony but not me

### Browser information

Chromium 109.0.5414.74 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 50f2b532e907-react-269d1622b946-js-4f918f684e9d Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please refresh, fixed an hour ago.
