### ISSUE TITLE
The RSS bot should either not truncate its posts, or the number of characters should be increased.

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-web#24386]
#### What would you like to do?
I am using the RSS bot with a Mastodon account. However, even though a mastodon post is usually about 500 characters, the RSS bot always truncates these when posting to a room. I would like the RSS bot to either (1) not truncate posts at all, (2) increase the number of characters before truncating, or (3) give the user the option to choose how many characters should be posted.
#### Why would you like to do it?
I really like the RSS bot. Unfortunately, it is pretty much useless in it present configuration when used with a mastodon rss feed.

#### How would you like to achieve it?
Just don't truncate! Or increase the word count to something like 500 characters.

**Comment by t3chguy** [comment]
The RSS bot isn't part of Element Web, I suggest opening an issue in https://github.com/matrix-org/go-neb/
