### ISSUE TITLE
Network Change Detection

### ISSUE THREAD

**Issue by rvalle** [vector-im/element-web#24383]
### Steps to reproduce

1. Start using Element connected via Wifi (i.e. disable mobile connectivity)
2. Test Element is functional (i.e. you receive messages)
3. Change network from wifi to mobile
3a. Turn Wifi off
3b. Turn Mobile connectiviy on 
4. Get someone to message you on Element
5. Messages are not received
6. You are not warned of failing connectivity.

#### What did you expect?
Element should detect network connectivity changes and reconnect via whatever network is functional. 
#### What happened instead?
I left home, and I missed important element notifications. Kept looking at the app waiting for them... but nothing.

### Operating system

Android

### Application version

1.5.20 

### How did you install the app?

Google Play

### Homeserver

Synapse home server

### Will you send logs?

No

**Comment by t3chguy** [comment]
This repo is called Element Web - try [Element Android](https://github.com/vector-im/element-android)
