### ISSUE TITLE
Extend devtools to extract relevant info to debug stuck notifications

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24393]

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/24388

**Comment by Johennes** [comment]
You just bet me to it! 😅

![Screenshot 2023-02-01 at 10 07 54](https://user-images.githubusercontent.com/1137962/215999447-ee7be355-753d-421d-84c8-56bec8d56937.png)
