### ISSUE TITLE
Edited message with reply only renders reply

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-web#24405]
### Steps to reproduce

Send a message like this one

```json
{
  "content": {
    "body": "* if you want to try a fresh language, id recommend go for interesting, quick, and performant backends over rust (you can see a well architected example go backend at the oss repo for classes.wtf)",
    "format": "org.matrix.custom.html",
    "formatted_body": "* if you want to try a fresh language, id recommend go for interesting, quick, and performant backends over rust (you can see a well architected example go backend at the oss repo for classes.wtf)",
    "m.new_content": {
      "body": "if you want to try a fresh language, id recommend go for interesting, quick, and performant backends over rust (you can see a well architected example go backend at the oss repo for classes.wtf)",
      "format": "org.matrix.custom.html",
      "formatted_body": "if you want to try a fresh language, id recommend go for interesting, quick, and performant backends over rust (you can see a well architected example go backend at the oss repo for classes.wtf)",
      "msgtype": "m.text"
    },
    "m.relates_to": {
      "event_id": "$96LNHzRmq2Gr1iYXk6Da8SfWQ9RKkISfWmF9CWltMts",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1675307398144,
  "sender": "@_discord_[REDACTED]:t2bot.io",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$K5bOd4i4lnOtJehZy0httRJNApkSFJZY6XAfgVMaBYE",
  "room_id": "!HjzDdJoIoiKebmgpWq:uplink.mit.edu"
}
```

This was generated by a Discord bridge bot.

#### What did you expect?

Message is rendered properly i.e. nheko:

![image](https://user-images.githubusercontent.com/24363938/216224522-4266d125-78e7-4d2c-81dc-3fe977607a7b.png)

#### What happened instead?

Only the quoted message is rendered:

![image](https://user-images.githubusercontent.com/24363938/216224627-5aebc581-4f46-4ac8-8de3-027154ce32b6.png)

The actual message contents aren't rendered

### Operating system

Linux

### Browser information

Firefox 109.0

### URL for webapp

Element 1.11.22

### Application version

Element 1.11.22, Olm 3.2.12

### Homeserver

matrix-synapse-py3 1.75.0+jammy1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your repro steps are insufficient, without seeing the original event we don't know the full relation. Your screenshot shows the message to be a reply but the event content does not.

**Comment by t3chguy** [comment]
Closing due to lack of requested info
