### ISSUE TITLE
Failed to load timeline position

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24410]
### Steps to reproduce

1. Member of room A
2. Somebody sends you a link to a message in room A via DM
3. Click the link

#### What did you expect?

Go to the message

#### What happened instead?

„Failed to load timeline position“

The room is displayed anyway.

### Operating system

Ubuntu 22.04.1 LTS

### Application version

Element Nightly version: 2023020101 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Looks like the event link you clicked on was invalid, the event ID began with `~!` not `$`

`!mVljGSzipLMokQkgTL:matrix.org/~!mVljGSzipLMokQkgTL:matrix.org:m1675334670869.229`
