### ISSUE TITLE
The user search does not work.

### ISSUE THREAD

**Issue by BlackSazha** [vector-im/element-web#24422]
### Your use case

Hi all!
English is not my native language, sorry for the mistakes.
I have a problem, the user search does not work.
Although the API works great!
That is, there are search results, but they are not displayed in the search, if you look at the requests, they are there. If the user makes changes to the profile, the search will return a result.
Are there solutions?
![2023-02-02_11-28-20](https://user-images.githubusercontent.com/35872063/216500752-139ddedd-55a5-49c0-a7f1-927860099418.png)
![2023-02-02_11-31-31](https://user-images.githubusercontent.com/35872063/216500759-08148eb4-993e-480d-bf4e-c1abb50226f5.png)
![2023-02-02_11-32-39](https://user-images.githubusercontent.com/35872063/216500764-63942741-d078-4a73-aa84-3fff5cc9862a.png)

**Comment by korneyda** [comment]
It's hard to write from prison (ot Naval’nogo) ))

**Comment by abhijain2003** [comment]
can I work on this

**Comment by SimonBrandner** [comment]
> can I work on this

Yeah, sure go ahead!

**Comment by abhijain2003** [comment]
I have started thanks

**Comment by abhijain2003** [comment]
![Screenshot 2023-02-08 232330](https://user-images.githubusercontent.com/91718608/217611541-3b466138-0c21-4d63-b9b4-1bcee9161523.png)


I just created my account in element web, and when I search for user profile, even I tried search my own profile. it shows data to me on screen.

kindly @BlackSazha  would you please describe your issue more
it would helpful

**Comment by t3chguy** [comment]
Change was reverted due to introducing a regression
