### ISSUE TITLE
Make it easier to see who is in a call

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24447]
### Your use case

There needs to be a better way to see who specifically are in a voice call from just looking at it, and not only the amount of people that are in the voice call like it currently is.

(From a [rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/19948))

**Comment by dbkr** [comment]
I'm not sure I understand what this means?

**Comment by andybalaam** [comment]
Me neither. Happy to just close if it's not adding any value.

**Comment by SimonBrandner** [comment]
Yeah, let's close this

**Comment by AndyClausen** [comment]
@andybalaam I think this is related to seeing who is currently in a video room without having to join it. This functionality is in Commet, and is the only thing missing for me and my friends to make Element a viable Discord alternative.

Any chance this can be reopened? For a fellow Andy?

**Comment by andybalaam** [comment]
@AndyClausen re-opening this won't help here. Please could you open a new issue that explains as clearly as possible what you want to do and what is not working for you. Screenshots would likely be helpful.

btw I'm not on the Element Web team so it wouldn't be me working on this :-)
