### ISSUE TITLE
Joining rooms in a space causes errors. Joining a subspace of rooms does not work.

### ISSUE THREAD

**Issue by SpecialBomb** [vector-im/element-web#24452]
### Steps to reproduce

1. Join a space in Element.
2. Go to the space's home.
3. Join a room.

#### What did you expect?
I expected to join the room as normal.
#### What happened instead?
I join the room, but the space home page is replaced with the bug report screen. I can simply click on another room on the left bar to make it go away. It does not require a full restart to use Element again.

### Operating system

Void Linux

### Application version

Element version: 1.11.20, Olm version: 3.2.12

### How did you install the app?

I installed it from the Void Linux package repository.

### Homeserver

I am registered on the-apothecary.club public homeserver.

### Will you send logs?

Yes

**Comment by SpecialBomb** [comment]
I found another strange behavior as well, if I try to join a subspace, it simply fails to join me to all of the associated rooms of the subspace. Joining rooms individually actually adds me to the room.

**Comment by t3chguy** [comment]
Fixed in 1.11.23
Joining a subspace isn't expected to join all rooms therein, auto join hasn't yet been decided.
