### ISSUE TITLE
Element crashed when trying to join a room

### ISSUE THREAD

**Issue by vranki** [vector-im/element-web#24451]
### Steps to reproduce

1. Was looking at a room list for a space, and searched for certain room
2. Clicked on "Join" button on said room
3. 

#### What did you expect?
Joining the room
#### What happened instead?
Element crashed and prompted to submit debug information

### Operating system

Ubuntu 

### Application version

1.11.22

### How did you install the app?

Debian packages

### Homeserver

hacklab.fi

### Will you send logs?

Yes

**Comment by vranki** [comment]
Sent the logs. Btw I was joined to the room after this.

**Comment by t3chguy** [comment]
Fixed on develop, will be fixed in 1.11.23
