### ISSUE TITLE
Gitter sunsetting: Can't go back to previous room version if I've never been there

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24453]
### Steps to reproduce

1. Visit a room that has a predecessor (defined in the create event, or, if you like, defined via MSC2946 if you've enabled the labs flag).
2. Scroll to the top
3. Look for the "This room is a continuation of another conversation." tile

#### What did you expect?

The tile to appear, and to be able to (attempt to) go back to the predecessor room.

#### What happened instead?

No tile appeared, and this error message appeared in the console:

```
Failed to find predecessor room with id !etcetc:gitter.im
```

### Operating system

Ubuntu 22.04

### Browser information

Firefox 109.0.1

### URL for webapp

https://develop.element.io

### Application version

Element version: 27f1d999a043-react-5ac014ff294d-js-8a3d7d5671e5 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andybalaam** [comment]
Workaround: if you post a normal message linking to the predecessor, then after the user has clicked that link, they will see the tile as normal.

**Comment by MadLittleMods** [comment]
> No tile appeared, and this error message appeared in the console:
> 
> ```
> Failed to find predecessor room with id !etcetc:gitter.im
> ```

Alongside fixing the problem here for the tile to show, we should update our tiles to show an error more clearly whenever a tile fails to appear. Showing some error feedback is much better than silently failing and having the user go on a goose chase to find out why it's not there or just assume they've done something wrong.

**Comment by andybalaam** [comment]
The fix for this is https://github.com/vector-im/element-web/issues/24611

**Comment by andybalaam** [comment]
The latest version of https://github.com/matrix-org/matrix-spec-proposals/pull/3946 includes a via_servers property that helps us find a predecessor room if the user has never opened it before.

Adapt the room predecessor code to use store and this property where it helps.

**Comment by t3chguy** [comment]
@andybalaam your comment above says this is fixed by https://github.com/vector-im/element-web/issues/24611 ? Should this be closed?

**Comment by andybalaam** [comment]
@t3chguy no, #24611 was closed in favour of this one. I'll update my comment.

**Comment by andybalaam** [comment]
> > No tile appeared, and this error message appeared in the console:
> > ```
> > Failed to find predecessor room with id !etcetc:gitter.im
> > ```
> 
> Alongside fixing the problem here for the tile to show, we should update our tiles to show an error more clearly whenever a tile fails to appear. Showing some error feedback is much better than silently failing and having the user go on a goose chase to find out why it's not there or just assume they've done something wrong.

For this tile, I've addressed this issue in https://github.com/matrix-org/matrix-react-sdk/pull/10483 .

**Comment by andybalaam** [comment]
@MadLittleMods when https://github.com/matrix-org/matrix-react-sdk/pull/10483 is merged, this should work for Gitter, BUT only when you have sent new predecessor events that contain `via_servers` properties.

**Comment by MadLittleMods** [comment]
Thanks for the fix and heads-up @andybalaam! I'm tracking re-sending the MSC3946 predecessor events with `via_servers` for all of the Gitter rooms in https://gitlab.com/gitterHQ/gitter.im/-/issues/10

**Comment by andybalaam** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/10483
