### ISSUE TITLE
Application not shown in application list

### ISSUE THREAD

**Issue by Cyb10101** [vector-im/element-web#24467]
**Describe the bug**
Element application not shown in application list. Only found by searching.

**To Reproduce**
Tested in Ubuntu 22.04. Scroll though Application list, Application should be missing.

**Expected behavior**
Application should be found in list.

**Desktop:**
 - OS: Ubuntu 22.04
 - Version: 1.11.22

**Additional context**
This should be done very easily by adding a `TryExec` line on `/usr/share/applications/element-desktop.desktop`:

```text
[Desktop Entry]
Exec=/opt/Element/element-desktop %U
TryExec=/opt/Element/element-desktop
```

I just couldn't find anywhere where this file is created. :-)

**Comment by weeman1337** [comment]
What desktop environment are you using @Cyb10101 ?

**Comment by JeanPaulLucien** [comment]
I confirm. Same in Windows.

**Comment by t3chguy** [comment]
@JeanPaulLucien that issue seems on your end.

![image](https://user-images.githubusercontent.com/2403652/218073369-867ee5bd-bc64-4bac-8d85-7e3571107e27.png)

**Comment by JeanPaulLucien** [comment]
> that issue seems on your end.

I installed by Riot installer, then it updated, then Installer 1.10... then in-app updates. I suppose it did not create the links and forgot about this. So, old users without links in Start menu.

**Comment by JeanPaulLucien** [comment]
> that issue seems on your end.

I found. :rofl: Sorry.

**Comment by t3chguy** [comment]
Yeah TryExec is only needed if the first executable listed in `Exec` isn't the target, e.g. for an AppImage being ran by AppRun. But we run our executable directly so it shouldn't be necessary.
