### ISSUE TITLE
Thread reply missing from thread in the mix of sending my own thread reply

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24466]
### Steps to reproduce

1. Someone else threads off their own message and sends some thread replies
1. In the mix of them sending more thread replies, you send a thread reply of your own
1. Notice a missing thread reply from the other person. Probably some race condition between your message being sent and the other thread replies.

(details in rageshake issue https://github.com/matrix-org/element-web-rageshakes/issues/19979)

Also [discussed in an internal room](https://matrix.to/#/!tCaHWuHHvOHjWyqapP:matrix.org/$jAvMiDVqXD6YAV5uP3pPhtsXRkm2PvYkThy3LpVP_go?via=matrix.org&via=element.io&via=vector.modular.im).

#### What did you expect?

All thread replies visible especially since it seems like it reached my client.

#### What happened instead?

There is a missing thread reply from the other person.

I did see an unread message indicator in the room preview. This phenomena is very hard to notice since I only caught the missing message from a notification on my other computer.

### Operating system

Windows 10

### Browser information

Chrome Version 109.0.5414.120

### URL for webapp

develop.element.io

### Application version

Element version: 27f1d999a043-react-39fe72e53ad6-js-8a3d7d5671e5 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes, https://github.com/matrix-org/element-web-rageshakes/issues/19979

**Comment by Johennes** [comment]
@MadLittleMods how often have you experienced this since filing the issue?

**Comment by MadLittleMods** [comment]
@Johennes I think 3 times. It seems pretty easy to reproduce in a situation as described above. Was pretty common with two of us going back and forth in a thread (answering someone's Gitter questions).

**Comment by Johennes** [comment]
I think I've run into another occurrence of this. Details in https://github.com/matrix-org/element-web-rageshakes/issues/22198.

**Comment by daniellekirkwood** [comment]
I think we've had several more reports of this (i've had a few people in my DMs this past week) 

@Johennes does that mean there's a new, different issue, or this one is getting worse (and needs to be changed from occasional)?

**Comment by Johennes** [comment]
It's hard to say since we don't know the actual root cause. It might as well be something new or just the old issue increased in frequency by a tangential change.

**Comment by Johennes** [comment]
We chatted this through in the WAT weekly today and we'll not escalate fixing this. We have other urgent work that is aligned with company-wide strategy this week and are generally not confident in making changes around the threads model without the refactoring and test suite mentioned in https://github.com/vector-im/element-web/issues/24392. So this is, sadly, gated behind that work unless somebody would like to step in.
