### ISSUE TITLE
Please provide a way to disable update notifications.

### ISSUE THREAD

**Issue by Mugane** [vector-im/element-web#24471]
### Steps to reproduce

It keeps telling me in a popup "Update Element" that "New version of Element is available".
I will argue separately that you release too many, non-critical updates that do not **need** to be applied. But even if this were not the case, updates are provisioned through a required package manager (chocolatey) and there will always be a delay between actual updates and availability of updates. Telling the end user that they need to update is completely useless in this case, since we are already using the latest update that is available to us. Therefore, please provide a way to permanently disable these incessant notifications to do something that we literally cannot do. 

#### What did you expect?
To be able to permanently disable update notifications.

#### What happened instead?
Micromanaging of my desktop with non-actionable, annoying notifications.

### Operating system

Windows

### Application version

NA

### How did you install the app?

Chocolatey

### Homeserver

NA

### Will you send logs?

No

**Comment by t3chguy** [comment]
Disable updates in config.json - `"update_base_url": null` - https://github.com/vector-im/element-desktop/#user-specified-configjson

Chocolatey is a community maintained development, they should include that in their config.json. We don't support a user pref for it as disabling updates means missing security updates.

**Comment by Mugane** [comment]
You are not the only software in the universe, literally thousands of other programs and systems exist and every user has different requirements. It is not your call to determine what update/install method customers of your product are using. Expecting that it is even remotely possible that users would modify their entire existing software provisioning method in order to accommodate your bug fixes or suffer a literally useless incessant non-actionable notice is absurdly egotistical.

**Comment by Mugane** [comment]
Please re-open and address the issue. There is zero downside to giving users the ability to turn off update notices like literally every other application in the universe.
