### ISSUE TITLE
You were removed from <room-title> by appservice

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24482]
### Steps to reproduce

1. Find room `#mastodon` on `libera.chat`
2. Join to room, using button "Join"
3. 

#### What did you expect?
Join to room
#### What happened instead?
Issue title + Reason: IRC connection failure.

### Operating system

Windows

### Application version

1.11.22

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The IRC bridge is not part of Element, I suggest seeking support in the support room #irc:matrix.org
