### ISSUE TITLE
Client sends requests with any word as server-domain value in "Add server" popup

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24485]
### Steps to reproduce

1. Use Element Desktop;
2. Open console.
3. Open Explore.
4. Add server
5. Type anything as server's domain.

For me these rooms:
```
!JsbthXjlaqosxISjgl:gitter.im
#irc:matrix.org
```

#### What did you expect?

Add server popup tries to check connection to domain-like keyword (example.com), no to any word.

#### What happened instead?

Matrix accepts just any word as server's domain and sends requests. In fact it returns errors.
```
Access to fetch at 'https://matrix-client.matrix.org/_matrix/client/r0/publicRooms?server=gi&limit=1' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. -- vector://vector/webapp/#/room/...
Failed to load resource: net::ERR_FAILED -- https://matrix-client.matrix.org/_matrix/client/r0/publicRooms?server=...&limit=...
```

### Operating system

Windows

### Application version

1.11.22

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This CORS is likely a timeout, and if it isn't then it is a server misconfiguration, I suggest seeking help from the server admin. Nothing a client can do re CORS errors.
