### ISSUE TITLE
Add a screen to notify that the secure backup is configured successfully

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#24487]
#### What would you like to do?
When secure storage is getting configured, there is no success panel

#### Why would you like to do it?
to let the user know that everything is ok

#### How would you like to achieve it?
By adding a dialog at the end of the process to confirm that the secure backup is correctly configured
(Currently this information is visible only in the application settings)

**Comment by americanrefugee** [comment]
What about this @giomfo?

![Secure Backup - Success message](https://user-images.githubusercontent.com/112560169/218484481-bd7831ad-1cf6-45d5-83ea-4cce1ff21891.png)

[Link to Figma file](https://www.figma.com/file/ja1Hf2UguAaD7ne1sYforo/DINUM-Feedback---Feb-2023?node-id=0%3A1)

**Comment by giomfo** [comment]
@americanrefugee yes, I approved this suggested design
We will work on its implementation
