### ISSUE TITLE
Video duplication when switching rooms

### ISSUE THREAD

**Issue by ThatOneCalculator** [vector-im/element-web#24498]
### Steps to reproduce

1. Play a video in a room
2. Quickly switch to another room
3. Quickly switch back
4. Repeat until your ears die

#### What did you expect?

Videos are unloaded when leaving a room

#### What happened instead?

This:

(Please play with audio on, but soft)

https://user-images.githubusercontent.com/44733677/218288354-7d51c90e-49c9-47ab-aa43-b664a5896f41.mp4

### Operating system

Arch Linux

### Browser information

Mozilla Firefox 109.0.1

### URL for webapp

element.fedibird.com

### Application version

Fedibird Matrix / Element version: 1.11.22 Olm version: 3.2.12

### Homeserver

matrix.fedibird.com

### Will you send logs?

Yes, I already downloaded my rageshake.tar and can upload if needed.

### The original video

https://user-images.githubusercontent.com/44733677/218288457-1af686d1-ecb7-4016-b9ad-3550a21412e5.mp4

**Comment by t3chguy** [comment]
Cannot reproduce, mine stops playing when I switch rooms away

https://github.com/vector-im/element-web/assets/2403652/9c88f087-4b4c-439c-af1f-95d79704a9f4

**Comment by ThatOneCalculator** [comment]
It still does it for me. You have to switch pretty fast.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/assets/2403652/78fece79-ba3a-4f01-ae02-32cd5a0b2b27

Switching pretty fast, also using element.fedibird.com - no difference

Likely a bug of your Firefox, I suggest trying a different browser or on a different system.

**Comment by t3chguy** [comment]
@ThatOneCalculator were you able to try it in a different browser?
