### ISSUE TITLE
Joining a room in a space: "Something went wrong"

### ISSUE THREAD

**Issue by timbl** [vector-im/element-web#24495]
### Steps to reproduce

1. Where are you starting? What can you see?

Log on as  different user timblbot:matrix.org created   a space  (solidprojectspace:matrix.org) 

2. Log on as timbl:matric.org 
3. Go to the space solidprojecspace:matrix.org
4. See the list of rooms, some with "View" buttons, some with "Join" buttons

5. What do you click?

"Join" (the r"solid" room in the list)

7. More steps…

#### What did you expect?

To move to a a display of the room n a oned state

#### What happened instead?
<img width="983" alt="Screenshot 2023-02-11 at 14 36 40" src="https://user-images.githubusercontent.com/1254848/218263781-4642787a-b3be-45a0-895b-ac98e522f371.png">

### Operating system

Mac OS 13.1

### Application version

Element Version 1.11.22 (1.11.22)

### How did you install the app?

I forget 

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by timbl** [comment]
Logs sent

**Comment by t3chguy** [comment]
Thank you @timbl - this was fixed last week and will be in this week's release
