### ISSUE TITLE
Mismatched default avatar colours

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2449]
It's rather unintuitive that the colour of the room avatar doesn't match the user's avatar:

<img width="442" alt="screen shot 2016-10-11 at 14 50 01" src="https://cloud.githubusercontent.com/assets/1294269/19272839/1078f61e-8fc2-11e6-8e16-b3e94e9deda4.png">

**Comment by rubo77** [comment]
can this be fixed easily?

maybe use an md5 hash on the comlete username and always create the colour from that?

**Comment by t3chguy** [comment]
This should also include matching the colour with the username colour in timeline

**Comment by waclaw66** [comment]
Another related problem is that avatar is not correcly depictured within browser notifications. There is shown only the solid color fill. I would suggest to use pre-rendered png avatar as another services do. That would solve both problems.

**Comment by waclaw66** [comment]
@t3chguy Do you have better solution?

**Comment by t3chguy** [comment]
I'm simply not a fan of the default avatars apps normally use, a colour and initial is much better for instant recognition than a random silhouette

**Comment by waclaw66** [comment]
I'm not talking about random siluete, I'm in favour of current appearance too. But html representation as img and span doesn't work for notifications as I mentioned. In case of pre-rendered png (color+initial) you don't need to care about platforms (web, notification, android...).

**Comment by t3chguy** [comment]
So you want to pre-render every possible colour+letter permutation? Given that Displaynames are unicode that is a very large set of images.

**Comment by t3chguy** [comment]
Plus given that users are in control of the font their Element uses, the pre-rendered images would not be able to make use of system fonts and be fixed at just one font.

**Comment by waclaw66** [comment]
I just want to fix web notifications, that's it. If the way how other services (like Google) do that (pre-rendered png) is not feasible, then please propose better solution.

**Comment by t3chguy** [comment]
Well services like google are centralised and not end-to-end-encrypted, and don't allow you to change the font. They can just have a single copy of all pre-rendered avatars. Here you would need each Element instance to host a copy of those 100,000 * Number of Colours PNG files and you still have issues. 

This is completely off-topic for this issue. This issue is about the default avatar colour generated for rooms being based on a hash of the Room ID but the one for Users is on the User ID so for DMs with a default avatar those can drift apart.

**Comment by waclaw66** [comment]
No, that's not what I say. Yes, notification image bug is offtopic. But my suggestion would fix it too. You don't need to have thousands pre-rendered images. You just pre-render the default avatar for each user on homeserver (when user is created or name changed) and save it in the same way as normal avatar picture, that's it. This is a common technique for default avatars.

**Comment by t3chguy** [comment]
Sure, you could do that. But the avatar colours are themable by the client. Like right now you could load up an Element theme and have different default avatar colours: https://github.com/aaronraimist/element-themes - this is important for branding and accessibility (colour-blindness and whatnot)

**Comment by t3chguy** [comment]
Nothing to stop a Matrix homeserver doing this auto-generation, but it'd need to be specced with some way to signal to the client that their avatar is a generated one otherwise their client would continuously show a Remove button next to their avatar. Your proposal should probably go on the matrix-doc repo.

**Comment by waclaw66** [comment]
I wasn't aware of local default avatar theming (same theme for default avatars from another homeservers). This is the only obstacle for my solution. Remove button is not a problem, you can add column "custom_avatar" to the db and show/hide remove button according that. I think it's time to stop the discussion, thanks for explanation. I will create new issue regarding notification image bug.

**Comment by t3chguy** [comment]
> Remove button is not a problem, you can add column "custom_avatar" to the db and show/hide remove button according that.

I'm talking about using the existing spec, there's either an avatar or there isn't one, if the server is generating a default then there always would be one so there would need to be a spec extension, not merely client/server work.
