### ISSUE TITLE
When connecting a new device, device verification does not start automatically

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#24490]
### Your use case

When a new session is detected the following dialog is displayed:
<img width="1143" alt="Screenshot 2023-02-10 at 18 56 37" src="https://user-images.githubusercontent.com/8969772/218162477-9de28580-7205-427f-9115-623619e4e9f4.png">

#### What would you like to do?
Start the verify device process automatically instead of navigating to the devices list in the application settings.
When the dialog appears, the first click should kick-off the process.

Note: Don't mix up with the incoming verification dialog:
<img width="768" alt="Screenshot 2023-02-10 at 18 50 26" src="https://user-images.githubusercontent.com/8969772/218162304-e6de2c5a-5822-4083-8167-84b6465774d1.png">

**Comment by americanrefugee** [comment]
I *think* this is what you're asking for @giomfo ...

New log in:

![New log in](https://user-images.githubusercontent.com/112560169/218506191-b6fcbd63-e888-4c5c-8d2d-f3997657bf29.png)

[Figma file](https://www.figma.com/file/ja1Hf2UguAaD7ne1sYforo/DINUM-Feedback---Feb-2023?node-id=4%3A7863&t=tkIt0sNrL6tEUirB-4)

Verification requested:

![Verification requested](https://user-images.githubusercontent.com/112560169/218506397-e13407bc-cecc-4ade-9faa-32ecbbaedf91.png)

[Figma file](https://www.figma.com/file/ja1Hf2UguAaD7ne1sYforo/DINUM-Feedback---Feb-2023?node-id=15%3A8311&t=tkIt0sNrL6tEUirB-4)

**Comment by americanrefugee** [comment]
@giomfo I also wanted to add some clarifications...

- For New Log In: Clicking "No" will take the user to the Settings page showing them a list of their devices, where they can sign out from the unrecognized device. In this case, we should also recommend that they change their password.
- For Verification Requested: This prompt is independent of the one for New Log In, in case that wasn't clear. The user would only see this if they initiated verification from their new device.

**Comment by pmaier1** [comment]
Just to make sure there's no misunderstanding: 
- The "new login" dialog is currently not meant to initiate the device verification. It's rather a security feature to notify users about new logins on their account. That's why it guides you to the device manager to review your connected devices. It could be extended to guide you to device verification if the user hits "Yes, it was me" in https://github.com/vector-im/element-web/issues/24490#issuecomment-1428182188.
- Usually the device verification process is started from the new device. Therefore I'm not sure which problem we're solving if we additionally allow starting it from the "new login" dialog. 

What's the actual user story here?

**Comment by pmaier1** [comment]
> we think that we should not start the verification on "Yes, it was me" click.

Agree :+1: 

> Eventually we may add a new dialog on this click to explain why they should verify this new session, and suggest this verification (not sure we want to add this now)

Please take into account that the verification dialog will automatically appear once a user starts the verification on a new device. I'm wondering what it is that you will change here after all. Is it just the button labels then?

**Comment by giomfo** [comment]
> I'm wondering what it is that you will change here after all. Is it just the button labels then?

Yes, and the layout of the dialog

**Comment by weeman1337** [comment]
Button labels are up to date. The new layout is still missing.
