### ISSUE TITLE
Element Desktop possible can break the IRP

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24491]
### Steps to reproduce

I suspect that Element Desktop may be used to break IRP in Windows. In result we got memory leak. Oh, maybe not only Element Desktop, but any Electron and Chromium apps.
```
Tag  Type     Allocs            Frees            Diff       Bytes

Irp  Nonp   22840036 ( 137)  17748425 ( 100)  5091611  1548179024
fwLP Nonp    3986606 (   2)   3970876 (   2)    15730    27433120
ArL2 Nonp    1121978 (   4)   1121905 (   4)       73    15036192
Io   Nonp  305992814 ( 927) 305881011 ( 928)   111803     9247888
```

#### What did you expect?
IRP works well, no memory leak
#### What happened instead?
IRP is broken, memory leak

### Operating system

Windows

### Application version

1.11.22

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by alunturner** [comment]
Hello @JeanPaulLucien. Would you be able to confirm whether you think this is specific to Element desktop or if you think that this is an Electron/Chromium issue? Thanks!

**Comment by t3chguy** [comment]
Closing due to lack of requested info
