### ISSUE TITLE
Cannot access any rooms

### ISSUE THREAD

**Issue by priyankacitrus** [vector-im/element-web#24502]
### Steps to reproduce

#cactus:cactus.chat is not accessible at this time.

Try again later, or ask a room or space admin to check if you have access.

was returned while trying to access the room or space. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose).

### Outcome

How to handle this situation?

### Operating system

Windows

### Homeserver

https://synapse.matrix.infra.medigy.com

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Looks like your federation isn't functional. https://federationtester.matrix.org/#synapse.matrix.infra.medigy.com unlike that of cactus.chat https://federationtester.matrix.org/#cactus.chat

`Get "https://162.243.60.189:8448/_matrix/key/v2/server": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
