### ISSUE TITLE
#comments_veedougherty_cactus-comments:veeroom:matrix.org is not accessible at this time.

### ISSUE THREAD

**Issue by vdougherty** [vector-im/element-web#24503]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

1. Attempting to set this up (cactus-comment) as my comment section in Hugo... I keep getting this error on my localhost "Error: M_INVALID_PARAM Room alias invalid" 
2. I get this error when logging into my Element account " #comments_veedougherty_cactus-comments:veeroom:matrix.org is not accessible at this time.

Try again later, or ask a room or space admin to check if you have access.

M_INVALID_PARAM was returned while trying to access the room or space. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose)."

in my chat.hmtl for Hugo this  what my setup looks like:

initComments({
  node: document.getElementById("comment-section"),
  defaultHomeserverUrl: "https://matrix.cactus.chat:8448",
  serverName: "cactus.chat ",
  siteName: "veedougherty",
  commentSectionId: "{{ index .Params 0 }}"
})

Honestly, I a complete newbie to git pages, hugo, and enabling chat any help would be appreciated.

#### What did you expect?

For the chat to work ...

#### What happened instead?

Chat displays with  error above it ""Error: M_INVALID_PARAM Room alias invalid"  in red"

### Operating system

Linux Mint

### Browser information

Firefox

### URL for webapp

loclhost has the error

### Homeserver

https://vdougherty.github.io/

### Will you send logs?

No

**Comment by t3chguy** [comment]
`#comments_veedougherty_cactus-comments:veeroom:matrix.org` is not a valid address, you cannot have multiple `:` unless the last one is a ports separator. `veeroom:matrix.org` is not a valid server name.
