### ISSUE TITLE
When viewing a room unauthenticated as a guest, it doesn't have any feature toggles enabled (like threads)

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24513]
### Steps to reproduce

1. In an fresh incognito tab, visit https://develop.element.io/#/room/#gitter_gitter:gitter.im
1. Notice that you can see messages in the room
1. But threads are just using fallback replies and other feature toggles you expect to be defaulted to on are not working
   - For `app.gitter.im`, this also means dynamic room predecessors which aren't visible.

---

Product-wise, this was [discussed internally](https://matrix.to/#/!HRPxYTDNTrjHtQknUy:matrix.org/$M58v87B_xHieSF6L8Egy7HTngWlioGA_n0TjDIO0mQ0?via=matrix.org&via=element.io&via=one.ems.host) (no conclusion yet).

#### What did you expect?

Default feature toggles apply to guest accounts so you can preview a room unauthenticated as expected.

#### What happened instead?

Missing a bunch of features that should be turned on

### Operating system

Windows 10

### Browser information

Chrome Version 110.0.5481.78

### URL for webapp

https://develop.element.io/

### Application version

Element version: 2b779e5e4ab6-react-fa036a508037-js-abc9c9dcb02f Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is intentional according to the comment above the implementation at least https://github.com/matrix-org/matrix-react-sdk/blob/030b7e90bf8ba09648f539dd378c0909f8773f86/src/settings/handlers/DeviceSettingsHandler.ts#L120-L123

**Comment by daniellekirkwood** [comment]
"Feature toggles" should only apply to Labs flags. 

Are there non-Labs features that you feel should be defaulted to on and are not today?

**Comment by MadLittleMods** [comment]
> So, for example, in [app.gitter.com's config file](https://app.gitter.im/config.json) I can see `"feature_dynamic_room_predecessors": true`
> 
> I would definitely expect a guest user to see that feature turned on if they connected to that client.
> 
> Is this what you mean @MadLittleMods ?

👍 Yes. You can default some labs feature toggles to enabled for an Element instance so everyone experiences them by default. Everyone should include guests.

**Comment by andybalaam** [comment]
I am discussing this with @daniellekirkwood

**Comment by daniellekirkwood** [comment]
What's stopping us from moving those things out of Labs?

**Comment by MadLittleMods** [comment]
> What's stopping us from moving those things out of Labs?

@daniellekirkwood To me, this is mostly separate concern as there are always going to be features that haven't made it stable yet.

This also prevents us from ever testing these features as a guest before they roll out to stable.

For example, we had this situation with threads when it was enabled by default (technically considered out of labs but still behind the same feature toggle) for all users while we tested the waters and left room for us to turn back if anything catastrophic came up. The thing holding us back was confidence, bandwidth, and time.

If we're talking Gitter specifics:

For dynamic room predecessors, this is still a new feature where the implementation is still settling in, probably needs a few more tweaks to be fully ready, and [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946) still needs to be discussed, merged, and put into a spec version. Gitter is ok with this risk (risk profile/tolerance) since the feature is necessary to even make content accessible.
 
For LaTeX math, this probably mostly a case of no direct responsible individual moving it forward (it's been a feature toggle for years). [MSC2191](https://github.com/matrix-org/matrix-spec-proposals/pull/2191) is still open but supporting the syntax is pretty harmless because it's just readable text for any other client which is fine to fallback with.

**Comment by daniellekirkwood** [comment]
I'm not 100% sold on this however, it feels like a simple thing to do and I believe it will benefit the users that you're concerned about here... We didn't reach conclusion internally which means no-one has strong thoughts on the PM team.

Path forwards: Let's do it. Element Web should respect the Server's (HTML) flags settings if it's choosing to override things. 

We should loop back round and discuss the Guest use case in more detail in the future but as that's not on the roadmap for 2023, let's go ahead and unblock y'all here :)

**Comment by MadLittleMods** [comment]
Thanks for looking into the details, weighing everything, and biasing to action @daniellekirkwood!

Thanks for the fixing this up @andybalaam! -> https://github.com/matrix-org/matrix-react-sdk/pull/10651
