### ISSUE TITLE
GYU – Quick settings: Change the copy / labels on the options

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24522]
Designs: https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=9040-138522&t=tDtJy79BQirt5h81-0

|How it looks today|How it looks in the new designs|
|-|-|
|![Screenshot 2023-03-20 at 12 54 07](https://user-images.githubusercontent.com/1137962/226331810-5914e515-cef3-45bf-8de9-01a194d85197.png)|![Screenshot 2023-03-20 at 12 53 46](https://user-images.githubusercontent.com/1137962/226331751-66bf035d-37bd-4327-9493-7cb48ce343d3.png)|

**Acceptance criteria**

* The copy for the four options in the tool-tip notification menu is update to
  * Match default settings
  * All messages
  * Mentions & keywords
  * Mute room
* The `... (Default)` suffix is not part of this issue and tracked in https://github.com/vector-im/element-web/issues/24523

**Comment by MadLittleMods** [comment]
@Johennes What does "GYU" stand for? There is no disambiguation on any of these issues

**Comment by Johennes** [comment]
The story & epic are linked if you click through on the tracked by header.

![Screenshot 2023-02-16 at 07 57 03](https://user-images.githubusercontent.com/1137962/219290923-ec6a62fc-824e-4628-bf7e-43761ba0f65f.png)

I agree that "GYU" is not a great acronym but there's a bit of a balance to be struck here due to the way we organize our work. It's not possible to see parent issues on cards in a GH board but if we spell out the full epic name in each issue's title, the board gets very cumbersome to parse.

**Comment by MadLittleMods** [comment]
> but if we spell out the full epic name in each issue's title, the board gets very cumbersome to parse.

That's fine. I'm just suggesting adding it to the issue description and the `Z-GetYourUpdates` label

**Comment by t3chguy** [comment]
@Johennes this isn't isn't ready, it lacks any detail whatsoever
