### ISSUE TITLE
gitter.im: all these dead "rooms" on the left

### ISSUE THREAD

**Issue by virtuald** [vector-im/element-web#24520]
### Steps to reproduce

1. Look at the left. All my old conversations are there. But none of them are usable.
2. A bunch of new rooms that are sorta duplicates of the old conversations are there

#### What happened instead?

It's nice that the old conversations are there, but they have a "This room has been replaced and is no longer active." message... which I guess is fine, but can't you just put them all in their own "archived" or similar category so I don't have to see them anymore?

Additionally, you autocreated new rooms for each one of the conversations... but some of these people I haven't said anything to in years. It's weird. Maybe if users haven't talked in N days then don't auto-create it, this new interface just has a lot of clutter.

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
@virtuald have these duplicates resolved now (after a reload)? Initially, we had the following problem which was mentioned in the blog before we fixed it up:

> Update: We’ve noticed an issue with one-to-one rooms that show up duplicated in the room list (because both the "live" and historical rooms are showing) but this will be patched up throughout the day today. You can track [this issue](https://gitlab.com/gitterHQ/webapp/-/issues/2873).

These two sections from the blog post are also relevant:

> We didn’t make the distinction whether to create the historical room based on if any messages would be sent in it.
>
> *-- https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/#where-is-my-message-history*

> #### Why do I see a bunch of random rooms that I didn’t see in the old Gitter app?
>
> You probably had these rooms hidden in Gitter but this isn’t a distinction made on Matrix so you will have to decide what you want to do with them. Feel free to leave any room you don’t want to be in or with Element, you can mark them as low priority to put them at the bottom of your room list.
>
> *-- https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/#why-do-i-see-a-bunch-of-random-rooms-that-i-didn%E2%80%99t-see-in-the-old-gitter-app*
