### ISSUE TITLE
Room ordering broken when switching spaces

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24527]
### Steps to reproduce

1. Click between spaces
2. DMs are wrong (old ones shown, not recent ones)
3. Switch back and forth
4. DMs are fine

#### What did you expect?

A stable room list

#### What happened instead?

See above. Started happening with today's nightly.

### Operating system

Windows 10

### Application version

Nightly (2022-02-14)

### How did you install the app?

The Internet

### Will you send logs?

Yes

**Comment by turt2live** [comment]
also applies to non-DM rooms, sometimes

**Comment by turt2live** [comment]
workaround to fix appears to be to click on a room in the sublist, then click out of that sublist

**Comment by tulir** [comment]
All rooms seem to be consistently incorrectly ordered whenever switching spaces for me. Re-orders after switching rooms (and breaks again after switching spaces)

**Comment by turt2live** [comment]
yea, I'm getting this reliably on all sublists now. Sometimes a room list order update (new message, etc) fixes it, but clicking & clicking off the sublist has been the most reliable so far.
