### ISSUE TITLE
Element desktop crash when maximizing

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [vector-im/element-web#24536]
### Steps to reproduce

1. Where are you starting? What can you see?
At any point where the Element window is on screen
2. What do you click?
The maximize button/keybind

#### What did you expect?
The Element window to be maximized 
#### What happened instead?
The Element app crahses with SIGSEGV
Backtrace is all `{addr} in ??()`

### Operating system

Arch Linux, KDE Plasma 5.26.5, Wayland (using native wayland)

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### How did you install the app?

The Arch Linux community repository.

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please report issues specific to community packages to their maintainers
