### ISSUE TITLE
Asterisk appears in Element app title

### ISSUE THREAD

**Issue by globalistas** [vector-im/element-web#24533]
### Steps to reproduce

Start the Element desktop app.

#### What did you expect?

To not see an asterisk in the app title.

#### What happened instead?

![image](https://user-images.githubusercontent.com/64347618/218981125-77ab3670-e806-499e-891f-94e4148acca9.png)

### Operating system

Windows

### Application version

Element version: 1.11.23 Olm version: 3.2.12

### How did you install the app?

I'm not sure, it was a long time ago.

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a feature, it is an unread marker (akin to the number that shows up in the same place which denotes notifications)
