### ISSUE TITLE
Notifications will not go away once the messages are read

### ISSUE THREAD

**Issue by Elliria** [vector-im/element-web#24532]
### Steps to reproduce

1. I'm starting in the home screen on [https://app.gitter.im/#/room/#gitter:matrix.org](https://app.gitter.im/#/room/#gitter:matrix.org).
2. I click the notification bell, which has a red dot on it.
3. I see a bunch of notifications dating all the way back to September of 2021.
4. Note that I was a Gitter user and got switched over to Matrix yesterday. These notifications were there when I arrived.
5. Despite reading through the messages in the notifications, the notifications are still there.
6. I posted about this in `matrix.org/gitter` and got some help from @madlittlemods
7. He suggested that I should go into Settings --> Notifications and click the red "Mark all as read" button.
8. I did that and the notifications are still there.
9. I went back in there to try it again and the red button is gone.
10. 

#### What did you expect?
I expected the notifications to go away as I read the messages.
#### What happened instead?
They stayed there.

### Operating system

Kubuntu 22.04 LTS Jammy Jellyfish

### Browser information

Firefox 110.0 (64-bit)

### URL for webapp

https://app.gitter.im/#/room/#gitter:matrix.org

### Application version

Gitter version: 1.11.23-rc.1 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Elliria** [comment]
![StuckNotifications](https://user-images.githubusercontent.com/25792925/218907781-9c5e24e6-280d-4673-8025-51bd9cbac54f.png)

**Comment by Elliria** [comment]
![NoMoreRedButton](https://user-images.githubusercontent.com/25792925/218908143-973d0dce-ea1d-4346-aadd-3e1c8b8f6ae2.png)

**Comment by t3chguy** [comment]
> I went back in there to try it again and the red button is gone.


The notifications panel is intentionally not cleared so you can scroll back to your old highlights as a means of searching

**Comment by Elliria** [comment]
So, how do you tell the difference between them and any new ones? Also, please consider making an optional toggle for those of us who would like to hide them unless they're needed for some reason.

**Comment by Elliria** [comment]
I'm not using an API. I'm using the web interface for Matrix and the little bell icon just always gives me the same list of notifications that you see above even though new messages have come in. I don't understand its purpose and why it doesn't change. It's making it pretty much impossible to find new messages and the ones that I'm finding are out of sheer luck at this point.

**Comment by t3chguy** [comment]
@Elliria the issue you labelled notifications don't go away one read - this is intentional, the panel is not meant to lose history. If you're missing new notifications in the panel that is a very different issue. Could it be https://github.com/vector-im/element-web/issues/6874 ?

**Comment by Elliria** [comment]
I don't think so. It's exactly as described above and I'd be surprised to find out this is intended behavior. I'm attaching a screenshot I took of how my notifications look today. Note that when you look at this image and compare it with the one I posted 5 days ago, they're identical. That can't be right...

**Comment by Elliria** [comment]
Note that I included the part of my (admittedly very hot pink) system tray that has the clock in it in the screenshot to show I took it today:

![2023-02-20-still-the-same](https://user-images.githubusercontent.com/25792925/220135083-a28a902e-8334-40f9-bbb2-0decd79af3f3.png)

**Comment by Elliria** [comment]
Also, I have my browser set to clear cache and cookies every time it closes, so it's not a local issue.

**Comment by t3chguy** [comment]
@Elliria this list is entirely populated by the server so client cache has 0 effect on it. Are the missing notifications in encrypted rooms?

**Comment by Elliria** [comment]
No idea. These are the rooms I'm in, and I've had new messages in some or all of them since 5 days ago, so it stands to reason that there would have been notifications:

![MyRooms](https://user-images.githubusercontent.com/25792925/220163988-bc0926a4-fdcc-40bc-90c9-adcd2b9f683f.png)

They're all public rooms. I also included **System Alerts** in the screenshot in case that's encrypted and/or counted as a room.

**Comment by t3chguy** [comment]
Sounds like your server, gitter.im, isn't correctly filling the Notifications panel for you

https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3notifications

**Comment by Elliria** [comment]
Is there something I need to do to fix it or is the fix going to be at your end?

**Comment by Elliria** [comment]
Also, will this be worked on even if it's been closed as completed or would it need to be reopened?

**Comment by t3chguy** [comment]
@Elliria the issue is with your server, gitter.im. Not the client. The client just asks the server for a list of events and renders it verbatim. A closed issue will not be worked on but I suggest reporting this to gitter.im

**Comment by MadLittleMods** [comment]
While I understand this panel is populated with whatever `/notifications` returns, this feels like it may be an Element problem where it doesn't properly gather notifications once it's shown the empty state. I've created a new issue to track this problem separately: https://github.com/vector-im/element-web/issues/24614

I also reproduced this (from the @EricGitterTester perspective). Some of these mentions were even made while staring at the blank panel.

![](https://user-images.githubusercontent.com/558581/220721325-0c4dc7cf-c084-4e0c-a11e-91133a201a53.png)


And after a refresh, the mentions appeared.

![](https://user-images.githubusercontent.com/558581/220721408-03e45d53-20e2-4d77-af4e-02fd662c8a90.png)

**Comment by Elliria** [comment]
That's not the case for me. In my case, all the old mentions are there when I log in. A refresh empties my notifications panel and another refresh puts the old mentions back. No new mentions ever show up.

**Comment by Elliria** [comment]
This also shouldn't just be about mentions, should it? Shouldn't notifications also let me know about any new posts even if I'm not mentioned in them?

**Comment by MadLittleMods** [comment]
There appears to be multiple problems going on here and we're now tracking them in:

 - https://github.com/vector-im/element-web/issues/24616
 - https://github.com/vector-im/element-web/issues/24614
