### ISSUE TITLE
I don't see the same rooms and username in the desktop and web ( github login )

### ISSUE THREAD

**Issue by shral** [vector-im/element-web#24540]
### Steps to reproduce

1. Log in to element web through the GitHub account, see everything like in gitter
2. Try the same thing in the desktop app ( Linux debian 11 ) or Android app ( Android version 12 )

#### What did you expect?

The rooms and usernames are to be the same on all 3 platforms

#### What happened instead?

In Desktop and Android, I see only one room and the username is different (on the desktop looks like this: `@myusername:matrix.org` in the web looks like this `@name-somerandomnumbers:gitter.im` )

### Application version

Element version: 1.11.22 Olm version: 3.2.12

### How did you install the app?

from android play/webpage ( as trying to open gitter was redirected )

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
You are logged into different accounts. @myusername:matrix.org is an account on matrix.org - @name-somerandomnumbers:gitter.im looks like an account or guest on gitter.im. To see the same rooms log into the same account on all your devices.

**Comment by shral** [comment]
Thank you @t3chguy if I put gitter.im in all platforms I get all the rooms now. It is though strange and should not be that the user needs to edit the string ( at least one dropdown should be available ) for the homse server. A normal user that was 2 days ago using only gitter should't have two different accounts that were randomly choosen in differnt platforms.

**Comment by t3chguy** [comment]
Anyone can host their own server, Element doesn't want to have to curate a list of "approved" servers so it is just the default server (from your config.json) + a text box.
