### ISSUE TITLE
Room with thread message not shown at top of list when „Show rooms with unread messages first“ is checked

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24547]
### Steps to reproduce

1. Check „Show rooms with unread messages first“ in your room list
2. Let someone send a message to a thread
3. Room has notification count (1)

#### What did you expect?

Room at top of the list

#### What happened instead?

Room not at top of the list

### Browser information

Firefox 110.0

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: dfe2a21b5860-react-a3a2a0f9141d-js-89df43a975d5 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by weeman1337** [comment]
Upgraded to `O-Frequent` since threads are out of beta and used in many places.

**Comment by t3chguy** [comment]
@Johennes could it be https://github.com/vector-im/element-web/issues/16127 (currently selected room being in the wrong place)

**Comment by t3chguy** [comment]
Closing as presumed fixed
