### ISSUE TITLE
When sorting invites by activity, newest are now at the bottom which isn't helpful when you stack them up because ignoring invites still doesn't exist....

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24546]
### Steps to reproduce

See rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/20150

When sorting invites by activity, newest are now at the bottom which isn't helpful when you stack them up because ignoring invites still doesn't exist....

### Application version

2023021601

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Potentially related to https://github.com/vector-im/element-web/issues/24527

**Comment by t3chguy** [comment]
Fixed on develop
