### ISSUE TITLE
Remove Sexual Content from the Room Directory (NSFW)

### ISSUE THREAD

**Issue by mindraj** [vector-im/element-web#24555]
### Your use case

Matrix.org homeserver seems to not have its own issue tracker and my message in Matrix HQ has been ignored so I will report here as that's what the Element app suggests. I ask you to remove sexual content from the public room search as there is a high probability of users discovering such content unintentionally and the content that does get discovered is just a pure PR disaster waiting to happen.
 
For example I wouldn't want an Asian person to feel objectified the moment they join matrix:
![Screenshot from 2023-02-08 05-34-28](https://user-images.githubusercontent.com/106462852/219522680-8cfe9195-ce11-4288-9d10-432e42f17d07.png)

Or a minor to discover sex related rooms the moment they search "cartoon":
![image](https://user-images.githubusercontent.com/106462852/219523072-dc3b7630-4a82-4d30-932c-fbbb3c9e62d8.png)

Those innocent search queries returning a slew of fetishistic content is utterly inappropriate for a network that strives to be inclusive for all kinds of people. Therefore I propose to ban NSFW content from the public room search on Matrix.org homeserver.

### Have you considered any alternatives?

Offer a toggle that is off by default if it is technically possible

**Comment by t3chguy** [comment]
Support for the matrix.org server is support@matrix.org
The best element could do is add a client side NSFW word filter like the mobile apps have

**Comment by andybalaam** [comment]
I pinged @daniellekirkwood to talk about where we can prioritise matching our mobile clients on this.

cc @jimmackenzie

**Comment by andybalaam** [comment]
After a quick chat with @daniellekirkwood we agreed we will treat this as a defect since it really needs addressing.

I gave it critical severity because for some people this will absolutely prevent them from using the app.

**Comment by daniellekirkwood** [comment]
This is pretty serious, thank you for bringing it to our attention. We'll treat this as a defect and look into building the solution as quickly as possible. 

@t3chguy's solution here feels like the right approach, especially in order to handle this ASAP, so let's move forwards with that. 

![IMG_2517](https://user-images.githubusercontent.com/89144281/219617601-90acda74-1b86-4161-9325-db9782f20850.jpg)

On iOS the toggle looks like this - let's go ahead with the logic that you have to enable this flag in order to see "NSFW" rooms and it's off by default. It should live in Settings but I'm not sure which sub-category so I'll leave that to @gaelledel :)

**Comment by gaelledel** [comment]
Design specs https://www.figma.com/file/GdakBDNSqVzATZ7uGy2jOI/Settings?node-id=226%3A3466&t=2TDiRIgkh58FZjzo-4

**Comment by daniellekirkwood** [comment]
Thanks, @gaelledel 

Quick note, this issue is now in "Ready" not "Done"

**Comment by andybalaam** [comment]
Design looks good, thanks @gaelledel

**Comment by MadLittleMods** [comment]
Related issue https://github.com/matrix-org/matrix-public-archive/issues/89 tracking this for the Matrix Public Archive

**Comment by andybalaam** [comment]
Apologies: the release notes for element-web v1.11.24-rc.2 incorrectly say that the fix for this is included. It is not: it will be included in v1.11.25

**Comment by t3chguy** [comment]
@kerryarchibald is this closed by your PR?

**Comment by syldrathecat** [comment]
I just updated to Element Web v1.11.24 and this NSFW filter **does** seem to be present and enabled by default, with no warning or instructions on how to disable it.

**Comment by t3chguy** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/2403652/223065105-67dfd5e9-060e-4b35-9d58-9b01848b19c7.png">

@syldrathecat Settings > Preferences

**Comment by jcrben** [comment]
I just sent in an email to support@matrix.org for a few more fyi, they're likely to keep creeping in
