### ISSUE TITLE
Potential typo and documentation inaccuracy (feature_thread vs feature_threadenabled)

### ISSUE THREAD

**Issue by spantaleev** [vector-im/element-web#24552]
### Your use case

`docs/betas.md` and `docs/labs.md` mention some `feature_thread` feature.

Grepping through the `element-web` and `matrix-react-sdk` source code, I **cannot find a `feature_thread` feature there**, only `feature_threadenabled`. I believe the documentation should be changed to address this typo.

Moreover, threads are out of beta now, aren't they? Looking at `matrix-react-sdk`'s `src/settings/Settings.tsx`, it seems like `feature_threadenabled` defaults to `true` already, so maybe Threaded Messaging shouldn't be mentioned on `docs/betas.md` at all. Given that it's shown in the **Labs** tab, I suppose it's OK to keep it in `docs/labs.md`.

I could also submit a PR if someone confirms my suspicions and plan of action.

**Comment by t3chguy** [comment]
Yeah this was missed when we went default-on, removing it from labs entirely is on the horizon so the docs might as well be updated for that
