### ISSUE TITLE
Scrolling backwards through history is quite slow

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#24550]
### Steps to reproduce

Scrolling backwards through a direct message history is quite slow (especially compared to Slack). I see messages show up one by one (is each one a separate network request?) and high CPU usage.

#### What did you expect?

Scrolling backwards through history should be faster

### Operating system

macOS

### Application version

Version 1.11.23 (1.11.23)

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by dbkr** [comment]
No logs have appeared as yet

**Comment by jrmuizel** [comment]
Can you remind me how to do that?

**Comment by t3chguy** [comment]
@jrmuizel it was in the form you said Yes to

![image](https://user-images.githubusercontent.com/2403652/220079884-f61d565c-b2fe-40e3-acce-d20a932161af.png)

**Comment by jrmuizel** [comment]
I've sent the logs now.

**Comment by MadLittleMods** [comment]
The `/messages` endpoint is known to be slow on Synapse (the server), https://github.com/matrix-org/synapse/issues/13356

There have been some great improvements in the last year but there is still a ways to go to make it actually fast.

---

I doubt the logs will show anything useful here and I suggest closing in favor of the upstream Synapse issue and all of the [performance issues in Element](https://github.com/vector-im/element-web/labels/A-Performance)
