### ISSUE TITLE
Poll not visible

### ISSUE THREAD

**Issue by jon-ryan** [vector-im/element-web#24568]
### Steps to reproduce

1. Create a poll in a group from some device
2. Open the group chat in the desktop app

#### What did you expect?
I can see the poll, participate and view the votes.

#### What happened instead?
I don't see the poll message

### Operating system

Arch Linux

### Application version

Element Version: 1.11.23; Olm: 3.2.12

### How did you install the app?

Flatpak

### Homeserver

non-public homeserver, matrixdotorg/synapse

### Will you send logs?

No

**Comment by jon-ryan** [comment]
![no-poll-visible](https://user-images.githubusercontent.com/37742289/219696623-7908980a-3fa4-41ce-8c46-2941382bcc9c.png)

**Comment by MadLittleMods** [comment]
@jon-ryan Are you sure that the poll was actually sent out? It might be hard to tell because the message send status isn't shown for polls (tracked by https://github.com/vector-im/element-web/issues/20566)

Does the poll have an event ID? Is it visible from any other device?

**Comment by jon-ryan** [comment]
@MadLittleMods yes, the poll was sent out. It is visible on iOS and Android and users can participate. 
One user in this group is using the Windows desktop client and he also can't see the poll.

The poll has an event id which begins with $jI74LNVY8-z2YrJZKu09g_HU-.....

**Comment by kerryarchibald** [comment]
Tested this by creating a poll on Element iOS 1.10.2 and viewing it with EW desktop 1.11.2, could not recreate the issue. 
What client is being used to create the poll?
Can you share the event source for the poll? (On a client where you can see the poll, open the `...` message context menu and 'view source')
<img width="656" alt="Screenshot 2023-02-20 at 11 07 03" src="https://user-images.githubusercontent.com/3055605/219977977-3cf2332f-bcd8-40c5-8340-d10dbabf11a1.png">

**Comment by jon-ryan** [comment]
I created the poll in the desktop application. On that client I can see it. Other desktop clients can't see it.

```
{
  "room_id": "!yPNuyUUpKbwfVYZrku:[my-homeserver]",
  "type": "org.matrix.msc3381.poll.start",
  "content": {
    "org.matrix.msc3381.poll.start": {
      "question": {
        "org.matrix.msc1767.text": "Datum nächstes Treffen",
        "body": "Datum nächstes Treffen",
        "msgtype": "m.text"
      },
      "kind": "org.matrix.msc3381.poll.disclosed",
      "max_selections": 1,
      "answers": [
        {
          "id": "xm8MI1vatmgIXiLM",
          "org.matrix.msc1767.text": "25.02."
        },
        {
          "id": "k7LPBFhWIBjlNXwT",
          "org.matrix.msc1767.text": "18.03"
        }
      ]
    },
    "org.matrix.msc1767.text": "Datum nächstes Treffen\n1. 25.02.\n2. 18.03"
  }
}
```

**Comment by weeman1337** [comment]
I am able to reproduce it by following these steps:

- Start a poll
- Login in with a new device
- Do not verify this device
- Go to the room, see the encrypted poll message
- Verify your device

Expected: Poll now visible
What actually happens: Poll not visible, empty message
