### ISSUE TITLE
Join Public room fails to parse url

### ISSUE THREAD

**Issue by mrx23dot** [vector-im/element-web#24566]
### Steps to reproduce

 1. Press join public room on main page
 1. Enter: https://matrix.to/#/!JiiOHXrIUCtcOJsZCa:matrix.org?via=matrix.org&via=maunium.net&via=t2l.io

![2023-02-17 15_01_05-SchildiChat ](https://user-images.githubusercontent.com/4163396/219689756-3ce0685e-0888-49b4-affc-234b0a721e25.png)

#### What did you expect?

Joining to public room using this standard URL

#### What happened instead?

It doesn't recognise URL, offers to create room ..

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment]
Closing in favor of these issues:

 - https://github.com/vector-im/element-web/issues/21695
 - https://github.com/vector-im/element-web/issues/16066
