### ISSUE TITLE
Show all Labs feature toggles when developer mode is active

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24571]
#### Problem

Currently, the **Settings** -> **Labs** section is only shown when `"showLabsSettings": true,` is configured in the Element `config.json` which not every Element instance has activated. The Labs section is also shown for any active "Betas" but only shows the betas and not the feature toggles unless the `showLabsSettings` setting is also `true`.

Feature flags can still be toggled manually via the devtools console if you know the JavaScript magic necessary to make it happen. But this is cumbersome to lookup, figure out which toggle you want, and use every time.

If I've toggled `/devtools` -> `Developer mode`, then that should give enough indication that I want and am capable enough to handle the dangers of the Labs feature toggles.

#### How would you like to achieve it?

When developer mode is enabled, always show Labs feature toggles

### Additional context

This idea already has some buy-in and [discussion in an internal room](https://matrix.to/#/!HRPxYTDNTrjHtQknUy:matrix.org/$Mpvm4dq8VE6IWPBpJgBpWi7wJpGWSW7HFb-RI0-cQFw?via=matrix.org&via=element.io&via=one.ems.host)

#### Dev notes

```
SettingsStore.getValue("developerMode")

SdkConfig.get("show_labs_settings")
```

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/8498
