### ISSUE TITLE
Ending a poll duplicates it in the timeline

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24579]
### Steps to reproduce

1. Start a poll
2. End it

#### What did you expect?

Ended poll once in the timeline

![image](https://user-images.githubusercontent.com/6216686/220041712-0392dce1-dea2-4df3-bcf1-89cbcec8cc62.png)

#### What happened instead?

Ended poll twice in the timeline

### Browser information

Firefox 110.0

### URL for webapp

https://develop.element.io/

### Application version

Element version: c463a5015988-react-d3771f8a9fb1-js-89df43a975d5 Olm version: 3.2.12

### Will you send logs?

No

**Comment by Johennes** [comment]
@kerryarchibald I think we're missing the "... ended a poll" line to make it more clear what happened here.

![Screenshot 2023-02-20 at 10 42 39](https://user-images.githubusercontent.com/1137962/220069629-4fb8d9c6-2e79-4718-bd4f-132b7d7d9169.png)
