### ISSUE TITLE
Threads are always unread on page load

### ISSUE THREAD

**Issue by Fabian42** [vector-im/element-web#24578]
Someone replied to one of my messages (sent in a regular chat) in a thread. Since then, I get a notification for that message and the chat appears as unread every time I open the website.

### Browser information

Firefox 110.0

### URL for webapp

matrix.germanzero.de

### Application version

Element version: 1.11.22 Olm version: 3.2.12

### Homeserver

politikergespraeche.germanzero.org

### Will you send logs?

Yes

**Comment by Fabian42** [comment]
Am I supposed to see the log here? What do I insert into the text box? I tried ID and link.

**Comment by gsouquet** [comment]
@Fabian42 The logs have correctly been linked to this issue, thank you!

Would you be able to go in one of the room that has those unread messages and type `/devtools` in the message composer. You should then see a "notifications debug" tool. Could you click on it and add the output onto this issue?

**Comment by Fabian42** [comment]
There is no "notification debug" option there:
![image](https://user-images.githubusercontent.com/10481506/220089425-047b4582-59fd-4b87-a012-806515cf58d8.png)

**Comment by t3chguy** [comment]
@Fabian42 update to 1.11.23

**Comment by Fabian42** [comment]
Well, it's a website, I'm not updating anything. Do you mean that the group owner needs to do something?

**Comment by t3chguy** [comment]
Whoever runs https://matrix.politikergespraeche.germanzero.org needs to update to 1.11.23. For now you can use an up to date instance to provide the necessary info. Such as app.element.io.

**Comment by t3chguy** [comment]
This got fixed
