### ISSUE TITLE
Telegram rooms getting deleted and recreated, room ID changes all the time

### ISSUE THREAD

**Issue by evakdev** [vector-im/element-web#24576]
### Steps to reproduce

Where are you starting? What can you see?

List of rooms. rooms connected to telegram keep getting recreated at least once per day. The old room goes to the "historical rooms" section, with a message saying "You were removed from [room-name] by Telegram Bridge (one.ems.host)".
A new room gets created and syncs messages and permissions. Sometimes this process produces unnecessary notifications. 
The new room's id is completely different from the old, and any alias I had set for it is now gone.
This only happens to rooms where the Telegram bridge is present. and only some of them. I’ve checked the perms on both “healthy” (not getting recreated everyday) and problematic rooms in telegram, and haven’t been able to find any specific situation that would make these rooms unique. It seems to be completely random. Sometimes problematic rooms suddenly become healthy, and sometimes a room that was okay becomes faulty.

#### What did you expect?

I expected the room ID to be a unique, identifiable source of information about a room, something I can bookmark. and that the room alias would stay the same.

#### What happened instead?
The room ID keeps changing for no clear reason, My aliases are removed, and I get unnecessary notifications for old messages while they are syncing.

### Operating system

Linux Mint

### Browser information

Chrome Version 109.0.5414.119

### URL for webapp

one.element.io

### Application version

Element version: 1.11.23 Olm version: 3.2.12

### Homeserver

one.ems.host

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Not sure this issue has to do with Element Web
Looks like you've already opened a ticket on the bridge project https://github.com/vector-im/mautrix-telegram/issues/57 lo
