### ISSUE TITLE
Fix element-desktop eslint config (to fix renovate PR)

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24581]
We updated our eslint setup and it caused this failure: https://github.com/vector-im/element-desktop/pull/529

To fix it, we need to update our config. See https://github.com/vector-im/element-desktop/pull/546

Should fix this one too: https://github.com/matrix-org/matrix-react-sdk/pull/10103 (if not, make a new issue)

**Comment by weeman1337** [comment]
@andybalaam I've considered the renovate issues as `A-DeveloperExperience` and gave them the `S-Minor`/`O-Uncommon` labels. If you don't agree feel free to adjust them.

**Comment by andybalaam** [comment]
Thank you @weeman1337 sorry for the spam. We will treat them with priority because they might prevent bringing in security updates, but in terms of triage your assessment looks totally reasonable.

**Comment by andybalaam** [comment]
I created https://github.com/vector-im/element-desktop/pull/547 which is an empty change to test whether I see the same error there.

**Comment by andybalaam** [comment]
After lots of work, https://github.com/vector-im/element-desktop/pull/546 is merged. Now checking up on https://github.com/vector-im/element-desktop/pull/529
