### ISSUE TITLE
Flaky location.spec.ts e2e test

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#24596]
https://cloud.cypress.io/projects/ppvnzg/runs/9742/test-results/81d7a0f3-9e2d-46df-aa63-02a4df25ab2d

Flake happened as part of https://github.com/matrix-org/matrix-react-sdk/pull/10191

**Comment by t3chguy** [comment]
Assigning to @kerryarchibald based on git blame

**Comment by kerryarchibald** [comment]
Last failure was 5 days ago.
The selector that Germain's PR was failing on [changed here](https://github.com/matrix-org/matrix-react-sdk/pull/10181/files) but the cypress selector was updated in the same commit.
