### ISSUE TITLE
Element tries to request avatars from non-exist servers.

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24618]
### Steps to reproduce

_Excuse me, it will be finished a bit later._

To reproduce you need an invite to the room on non-existed server.
Click to show invites.

Note: server does not exist.

#### What did you expect?
No request to non-exist server.
#### What happened instead?
`GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/...?width=32&height=32&method=crop`
Request an avatar from non-existed server, drops 404 error.

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by aaronraimist** [comment]
What would you suggest Element do instead? Element has no way to know if an avatar or server exists without making the request.

Also, what server are you suggesting no longer exists? The URL you provided shows Element is making a request to your homeserver, matrix.org, for the avatar of another matrix.org user. matrix.org certainly exists.

**Comment by weeman1337** [comment]
@JeanPaulLucien thank you for creating the issue.

How does Element behave when requesting from an unknown server? Is there any error message or does it use the fallback avatar in your case?

**Comment by weeman1337** [comment]
Thank you for creating the issue @JeanPaulLucien . Element falls back to the letter avatar in the case it cannot load an avatar. I think this is not going to be changed. Closing this issue.

**Comment by JeanPaulLucien** [comment]
@weeman1337 I discovered more. I was wrong other reason.
