### ISSUE TITLE
Notifications for threads contain the text of the message that the thread was started from

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#24620]
### Steps to reproduce

1. Start a thread
2. Get replies to the thread

#### What did you expect?
Notifications that contain the text of the reply

#### What happened instead?
Notifications contain the text of the message that the thread was started from instead of the text of the replies.

### Operating system

macOS 10.15

### Application version

Version 1.11.23 (1.11.23)

### Homeserver

mozilla.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
@jrmuizel thank you for reporting the issue. This is not related to threads and applies to all replies.

**Comment by t3chguy** [comment]
@weeman1337 threads don't contain a fallback like replies:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/2403652/220862711-4f8f59e5-011e-4bea-8383-e96fc6aba6c6.png">

Could this be https://github.com/vector-im/element-web/issues/24336?

**Comment by weeman1337** [comment]
> Could this be https://github.com/vector-im/element-web/issues/24336?

Closed the other issue, because I cannot reproduce it any more.

**Comment by weeman1337** [comment]
I think the issue mentioned here is to repeat the text of the original message. With limited space available in notifications it looks like that you are getting notified about the original message

![image](https://user-images.githubusercontent.com/6216686/220866635-44a728f4-bb15-4c9a-8e3b-d5e3d5118447.png)

**Comment by weeman1337** [comment]
Maybe this should change to „someone replied to“ or „someone $reply message“ :man_shrugging:

**Comment by t3chguy** [comment]
@weeman1337 that's a reply though, not a thread response

https://github.com/vector-im/element-web/issues/17859 is the isssue tracking what you demonstrate in your screenshot

**Comment by t3chguy** [comment]
@jrmuizel can you clarify was it a reply or a thread response? A screenshot would be helpful.

**Comment by jrmuizel** [comment]
A thread response

**Comment by jrmuizel** [comment]
This is marked as needing info. Is there still info that's needed?

**Comment by 8227846265** [comment]
This bug is RIDICULOUS and SUPER ANNOYING.

You send one message. Element will then barrage you with 5 duplicate notification even though no one replied. 

If you sent 5 messages. You get 15+ Duplicate Notification Message!!!

(╯°□°)╯︵ ┻━┻ 

I sent a rage shake for this. Hopefully someone can see it and help on the necessary info to reproduce this issue.

**Comment by 8227846265** [comment]
The only possible band-aid solution I can find to avoid the notifications is to update the `Room Settings` > `Notification` like this.
![image](https://user-images.githubusercontent.com/66582769/226805017-3c3694ed-89c1-40ff-a4b1-46c19ff2f13d.png)

**Comment by 8227846265** [comment]
(╯°□°)╯︵ ┻━┻ 

There's no day to properly message on an encrypted room without this bug being triggered.

**Comment by xi-pinmping** [comment]
I seem to be getting this mostly with direct messages to me in a group.

**Comment by t3chguy** [comment]
I cannot reproduce this anymore, @jrmuizel please shout if you are still seeing it on 1.11.36
