### ISSUE TITLE
Read messages reappear as "new" after restarting the app.

### ISSUE THREAD

**Issue by Anagastes** [vector-im/element-web#24629]
### Steps to reproduce

I have no idea how to force it. It suddenly shows up sporadically on the desktop clients.

It is using Arch Linux and the official package from there

### Outcome

That read messages also keep the status.

### Operating system

Arch Linux

### Application version

Version von webgo: 1.11.23 Version von Olm: 3.2.12

### How did you install the app?

https://archlinux.org/packages/community/x86_64/element-desktop/

### Homeserver

Own Synapse on Debian 11, v1.77

### Will you send logs?

Yes

**Comment by florianduros** [comment]
Hi ! 

Is the unread bug is happening in rooms where threads are used ?

**Comment by Anagastes** [comment]
The Threats are not used there, but yes, I hadn't thought of that. Thanks.

The behavior seems indeed nevertheless related to the [#24392](https://github.com/vector-im/element-web/issues/24392).

**Comment by jeffrson** [comment]
BTW, when I click on "Jump to first unread message" a message box appears:
**Failed to load timeline position**
Tried to load a specific point in this room's timeline, but was unable to find it.

**Comment by t3chguy** [comment]
@jeffrson please use issue search. https://github.com/vector-im/element-web/issues/20927

**Comment by jeffrson** [comment]
Okay, sorry, I thought  it might be related.

**Comment by davidmehren** [comment]
I can reproduce this with two different accounts, with Element Desktop Stable on Windows and Element Nightly both on Windows and Linux. I submitted two rageshakes, maybe they contain something useful.

**Comment by Anagastes** [comment]
Still present with Server v1.79 and 

Element-Desktop 
Version from webgo: 1.11.25
Version from Olm: 3.2.12

**Comment by Anagastes** [comment]
Still present with Server v1.79 and

Element-Desktop
Version from webgo: 1.11.26
Version from Olm: 3.2.12

I have sent log data again.

**Comment by Standard8** [comment]
I very frequently get this on the desktop client on startup but not always. A few rooms in particular seem to be stuck in this bad state.

Today, when I started it said I had 11 notifications from a one-to-one conversation (this was something I'd not seen before) but when I visited it, there was nothing since 9 days ago.

Clearing the cache & reloading doesn't help. In fact I just cleared the cache & reloaded, followed by restarting the app and 10 rooms are now showing as unread - and they haven't had any activity in that time.

Note that I use Element on both desktop & mobile, so that may or may not be related. I've submitted a couple of sets of logs.

**Comment by Anagastes** [comment]
> 

Yes, the error is still present with me. 

Unfortunately, I don't know of any trackers. I only know that the error was listed here... but for reasons unknown to me is now in the archive -.-

https://github.com/vector-im/element-web/projects/27#card-88213606

**Comment by JeanPaulLucien** [comment]
In my opinion this bug has appeared after 1.11.23.

**Comment by weeman1337** [comment]
- We should send a `/receipt` for the `main` thread when viewing the main timeline.
- How should we handle if we got both, `main` and unthreaded receipts?
- What unthreaded receipt should we send when viewing a room? Currently it sends a receipt for some previous thread.

![image](https://user-images.githubusercontent.com/6216686/234015445-f01e7e83-0dee-482a-b238-f811998cc5a2.png)

**Comment by weeman1337** [comment]
> What unthreaded receipt should we send when viewing a room? Currently it sends a receipt for some previous thread.

→ https://github.com/vector-im/element-web/issues/25196

**Comment by clokep** [comment]
> We should send a `/receipt` for the `main` „thread“ when viewing the main timeline?

Yes, the main timeline is "just" another thread.

> How should we proceed if we got both, `main` and unthreaded receipts?

The unthreaded receipt applies to an unthreaded view of the room (so essentially across all threads). For each thread you need to compare the unthreaded receipt and the receipt for that thread and use the one which is "later".

> What unthreaded receipt should we send when viewing a room?

Element Web is a threaded client and should never send an unthreaded receipt (unless you want to mark a room as fully read, in which case an unthreaded receipt on the latest event in the room, regardless of thread, should be sent).

**Comment by weeman1337** [comment]
We should store receipts for the `main` thread separately [here](https://github.com/matrix-org/matrix-js-sdk/blob/c2afc357b923f3d6a234a39f73541465d8dd7dda/src/sync-accumulator.ts#L459). It should be persisted then as well. When reading the persisted data it should automagically be restored [here](https://github.com/matrix-org/matrix-js-sdk/blob/c2afc357b923f3d6a234a39f73541465d8dd7dda/src/sync-accumulator.ts#L600-L607).

**Comment by andybalaam** [comment]
/me is desperate to factor out the receipt part from `accumulateJoinState` and write some unit tests

**Comment by Anagastes** [comment]
@andybalaam 

Is it known when the fix will be released? I can't find #24629 and #24392 in the release notes yet.

Sorry to follow up, it's just regrettably extremely annoying in general operation.

**Comment by andybalaam** [comment]
Hi @Anagastes, I'm sorry it's still happening! It's still happening to me too and annoying me too.

The last fix that might still be trickling towards you is https://github.com/matrix-org/matrix-js-sdk/pull/3427 . That should be in v1.11.34.

If that one doesn't prevent your problem, please log a new bug.

If you want to find out early, please try https://develop.element.io or the Nightly builds.

Thanks for your patience. We've fixed lots of issues in this area, but every time we turn over another rock we find 10 more, so it's frustratingly slow to show results.

**Comment by Anagastes** [comment]
> Hi @Anagastes, I'm sorry it's still happening! It's still happening to me too and annoying me too.
> 
> The last fix that might still be trickling towards you is [matrix-org/matrix-js-sdk#3427](https://github.com/matrix-org/matrix-js-sdk/pull/3427) . That should be in v1.11.34.
> 
> If that one doesn't prevent your problem, please log a new bug.
> 
> If you want to find out early, please try https://develop.element.io or the Nightly builds.
> 
> Thanks for your patience. We've fixed lots of issues in this area, but every time we turn over another rock we find 10 more, so it's frustratingly slow to show results.

Sorry to breathe life back into this issue, but even with the stable 1.11.34 it is not fixed for me.
