### ISSUE TITLE
Admin request in room where you are common user

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24631]
### Steps to reproduce

1. Visit any room where you are a common user.
2. Open user list in room.
3. Open console.
4. View user information.
5. Element tries GET https://matrix-client.matrix.org/_synapse/admin/v1/users//admin 403

#### What did you expect?
Element works like for a common user
#### What happened instead?
Element tries to work like for admin

```
fetch.ts:62          
GET https://matrix-client.matrix.org/_synapse/admin/v1/users/ /admin 403
fetch @ fetch.ts:62
requestOtherUrl @ fetch.ts:264
request @ fetch.ts:205
authedRequest @ fetch.ts:156
isSynapseAdministrator @ client.ts:6927
(anonymous) @ UserInfo.tsx:964
Bl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Ml @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
L @ scheduler.production.min.js:16
E.port1.onmessage @ scheduler.production.min.js:12
```

### Operating system

Windows

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is checking if you are a Server Admin (Synapse specific feature) - unrelated to room power levels.
