### ISSUE TITLE
Element doesn't display double line breaks in quotes

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#24644]
### Steps to reproduce

1. Write a message containing a quote with double line breaks
2. Send the message
3. The message displayed doesn't display double line breaks

#### What did you expect?

I expect Element do display the double line breaks in the quotes.

#### What happened instead?

<img width="1030" alt="Screenshot 2023-02-24 at 13 31 09" src="https://user-images.githubusercontent.com/1688309/221189282-33d8ac5a-b343-4db2-b6ae-18f582b5dd6d.png">

<img width="1030" alt="Screenshot 2023-02-24 at 13 31 14" src="https://user-images.githubusercontent.com/1688309/221189346-8f70dc02-d201-40e6-9c9f-0fae70d62b50.png">

Source event content is:

```json
"content": {
    "msgtype": "m.text",
    "body": "This is a message with double line breaks.\n\nAnother line\n\n> What about quotes now?\n> \n> Do we skip the double line breaks?",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>This is a message with double line breaks.</p>\n<p>Another line</p>\n<blockquote>\n<p>What about quotes now?</p>\n<p>Do we skip the double line breaks?</p>\n</blockquote>\n"
  },
```

### Operating system

macOS

### Application version

Element Nightly version: 2023022401 Olm version: 3.2.12

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

Synapse 1.77.0

### Will you send logs?

No

**Comment by JeanPaulLucien** [comment]
I like this.

**Comment by JeanPaulLucien** [comment]
![image](https://user-images.githubusercontent.com/24779886/221192558-a049d824-c938-473b-93c9-5e6d62b3b0e2.png)
![image](https://user-images.githubusercontent.com/24779886/221192652-5efdbecc-603d-413d-ac97-64312086c174.png)

**Comment by Johennes** [comment]
Can't reproduce on current ED nightly.

![Screenshot 2023-06-25 at 16 22 45](https://github.com/vector-im/element-web/assets/1137962/3c14914f-35f7-4539-87f5-3c0aa78a48c5)
![Screenshot 2023-06-25 at 16 22 51](https://github.com/vector-im/element-web/assets/1137962/9d49c8da-4fe4-4b07-9ac2-3175f81bb997)

Assuming fixed. Please reopen if you still experience this.
