### ISSUE TITLE
Very high CPU loading after leaving of a room

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24643]
The Help Vampire is here again.
It's the temp situation. About less than one minute. 
**About the room:** But I has left a totally empty room (about 7 messages, 1 link with preview, 5 users in the room and about 20-30 events (join, left, change nick and etc.). 
Other programs that uses CPU was not launched at this time. I did not know what will be with performance. I don't have an idea where I can get 75% or more percents, only encoding audio and video consumes 50%.
I have not seen nothing special in Element's console. Nor errors, nor warnings.

### Steps to reproduce

CPU: Intel Core I5 240M 2.5 GHz (2 cores, 4 threads).

1. Click "..." in the Room list.
2. Click "Leave room".
3. Confirm, leave room.
4. Monitor CPU usage.

#### What happened instead?
Above 75% of CPU usage,

### Operating system

Windows

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Please send logs and/or a profile

**Comment by t3chguy** [comment]
Closing due to lack of requested info
