### ISSUE TITLE
CPU usage and memory jumps

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24648]
### Steps to reproduce

Seems Element has built-in miner. It's joke, but likely.

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
To get to the bottom of memory usage a memory profile would be needed

**Comment by JeanPaulLucien** [comment]
I tried to capture a screen with CPU usage, but when I open Task Manager it bring back to 0-10%. My cooling system says about CPU usage.

**Comment by t3chguy** [comment]
that doesn't help at all

**Comment by JeanPaulLucien** [comment]
@t3chguy but logs? Did you received?

**Comment by t3chguy** [comment]
For memory issues we'd need a profile as I stated in https://github.com/vector-im/element-web/issues/24648#issuecomment-1443826715

https://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art038

**Comment by JeanPaulLucien** [comment]
I really do nothing special. I even do nothing in Element. Just switch between browser, Task manager and Element. I see in Task manager 1200 MB, then I write a comment here, return to Task Manager, Element used 1 400 MB after 2 seconds drops to 1 200 MB.

**Comment by JeanPaulLucien** [comment]
> To get to the bottom of memory usage a memory profile would be needed

Is it possible task when 3 GB of RAM is free? While 4% and OS ready to kill that.

**Comment by JeanPaulLucien** [comment]
Create snapshot is task not for my hardware. 
![image](https://user-images.githubusercontent.com/24779886/221234123-99e60204-c810-4e0e-8258-a65fb8f4f456.png)

**Comment by t3chguy** [comment]
@JeanPaulLucien Windows 7 is not a supported environment https://github.com/vector-im/element-web#supported-environments - Electron explicitly dropped support for it - https://www.electronjs.org/blog/electron-23-0

> Additionally, support for Windows 7/8/8.1 has been dropped.
