### ISSUE TITLE
Custom sticker picker became blank after updating Nightly build

### ISSUE THREAD

**Issue by cqjjjzr** [vector-im/element-web#24664]
### Steps to reproduce

Use a custom sticker picker from https://github.com/maunium/stickerpicker without any integrations manager. Click Ctrl+; to open the sticker picker.

#### What did you expect?

The custom sticker picker opens, as is in the browser and in the previous Nightly version.

(expected)

![image](https://user-images.githubusercontent.com/6622592/221335143-ce42dcca-9368-4b9a-83dd-a21d2897bc87.png)

#### What happened instead?

The sticker picker pane is blank, with an empty `mx_persistedElement_stickerPicker` div.

![image](https://user-images.githubusercontent.com/6622592/221335090-7fd1e108-50b5-4a4b-bc28-372ff8b30e15.png)
![image](https://user-images.githubusercontent.com/6622592/221335232-e31e2525-721d-4604-a61d-de3a0e3f28fb.png)

### Operating system

Windows 10 Build 19045 Simp. Chinese

### Application version

Element Nighgly

### How did you install the app?

https://element.io/download

### Homeserver

Dendrite 0.11.1+cc59879

### Will you send logs?

Yes

**Comment by cqjjjzr** [comment]
OK I figured out from the console logs. It is required to add `creatorUserId` to the 'content' object for the sticker picker widget in the `m.widgets` object, like this:

```json
{
  "content": {
    "stickerpicker": {
      "content": {
        "type": "m.stickerpicker",
        "url": "<url of the sticker picker>",
        "name": "Stickerpicker",
        "creatorUserId": "<my username>",
        "data": {}
      },
      "sender": "<my username>",
      "state_key": "stickerpicker",
      "type": "m.widget",
      "id": "stickerpicker"
    }
  },
  "type": "m.widgets"
}
```

Don't know why it's working on the web version though

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-widget-api doesn't allow widgets to not have a `creatorUserId` - and https://github.com/maunium/stickerpicker/wiki/Enabling-the-widget instructs you to set one also. This appears to be an invalid usage of a custom sticker picker.

**Comment by cqjjjzr** [comment]
The wiki was edited by me. The previous version doesn't have the `creatorUserId` entry. Maybe it's a doc issue.

**Comment by t3chguy** [comment]
Interesting, thanks for updating. The spec lacks detail around `m.stickerpicker` but https://github.com/matrix-org/matrix-widget-api is the canonical implementation so if that demands `creatorUserId` then it ought to be provided.
