### ISSUE TITLE
Memory leak in room where "Unable to decrypt message"

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24669]
### Steps to reproduce

1. Go to any room where you see "Unable to decrypt message", you should see also popup about your devices https://github.com/vector-im/element-web/issues/24067 
2. Messages with "Unable to decrypt message" should be visible. Scroll to place it in the middle of the screen.
3. Just stay your PC alone with Element Desktop to destroy your hardware.

#### What happened instead?
High CPU usage, memory leak

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
@JeanPaulLucien Windows 7 is not a supported environment https://github.com/vector-im/element-web#supported-environments - Electron explicitly dropped support for it - https://www.electronjs.org/blog/electron-23-0

> Additionally, support for Windows 7/8/8.1 has been dropped.
