### ISSUE TITLE
Jitsi widget fails to get access for media devices (microphone, webcam)

### ISSUE THREAD

**Issue by VannaKarenina** [vector-im/element-web#24662]
### Steps to reproduce

1. Start group call
2. Join in conference
3. Check error

#### What did you expect?
Jitsi widget will get access to microphone and webcam
#### What happened instead?
Throw error like 'You need to enable access to microphone and camera'

### Operating system

Windows 10/11

### Application version

Element Desktop 1.11.23

### How did you install the app?

https://element.io/get-started

### Homeserver

Synapse 1.77.0

### Will you send logs?

Yes

**Comment by VannaKarenina** [comment]
After some tests, this thing exist only in self builded client

**Comment by t3chguy** [comment]
@VannaKarenina are you signing the client? It might be that without signing Windows won't let you access media devices. You can check by right clicking the executable and going into the `Digital Signatures` tab

**Comment by VannaKarenina** [comment]
> @VannaKarenina are you signing the client? It might be that without signing Windows won't let you access media devices. You can check by right clicking the executable and going into the `Digital Signatures` tab
Oh, I completely forgot about the fact that the signature affects. Are there instructions on how to sign without bothering ?

**Comment by t3chguy** [comment]
@VannaKarenina https://www.electron.build/code-signing

**Comment by t3chguy** [comment]
@VannaKarenina if you can reproduce after code signing please shout back here

**Comment by t3chguy** [comment]
Probably, but that'll likely require you to manually trust that certificate on each machine you install it on

**Comment by VannaKarenina** [comment]
> Probably, but that'll likely require you to manually trust that certificate on each machine you install it on

Tried to sign by self signed and still same issues, but Digital Signatures showing sign :(

**Comment by t3chguy** [comment]
@VannaKarenina that's unrelated - https://github.com/vector-im/element-web/issues/4880 - its an issue of Jitsi not supporting Electron when sandbox + security hardening is enabled.

**Comment by VannaKarenina** [comment]
> @VannaKarenina that's unrelated - https://github.com/vector-im/element-web/issues/4880 - its an issue of Jitsi not supporting Electron when sandbox + security hardening is enabled.

Oh, is any estimated time for fix from their side?
And one more question, element cal in groups using external server or we can self host him ?

**Comment by t3chguy** [comment]
None. They have been very non-receptive around fixes coming from us in the past. We are focusing on Element Call replacing Jitsi ASAP.

**Comment by VannaKarenina** [comment]
> None. They have been very non-receptive around fixes coming from us in the past. We are focusing on Element Call replacing Jitsi ASAP. You can self-host element-call but right now it is peer-to-peer anyway, the (lack of) SFU mode is what is keeping it in Beta, but that too will be self-hostable. https://github.com/vector-im/element-call/

So I understand correctly that your servers are not involved in element call group calls right now ?

**Comment by t3chguy** [comment]
TURN/STUN may be involved if your networks do not allow for peer-to-peer (CGNAT etc)

**Comment by VannaKarenina** [comment]
> TURN/STUN may be involved if your networks do not allow for peer-to-peer (CGNAT etc) but it is fully end to end encrypted via DTLS

Any instructuons to configure turn for element call ?

**Comment by t3chguy** [comment]
I suggest asking the relevant project

**Comment by VannaKarenina** [comment]
> I suggest asking the relevant project

Okay, thx for help
