### ISSUE TITLE
`Cannot connect to integration manager`

### ISSUE THREAD

**Issue by HammyHavoc** [vector-im/element-web#24661]
### Steps to reproduce

1. Click `Add widgets, bridges & bots`

#### What did you expect?
To be able to manage integrations.
#### What happened instead?
`Cannot connect to integration manager`
`The integration manager is offline or it cannot reach your homeserver.`

### Operating system

Windows

### Application version

Element version: 1.11.23 Olm version: 3.2.12

### How did you install the app?

Element website

### Homeserver

https://hub.docker.com/layers/avhost/docker-matrix/latest/images/sha256-a341dee867911642e90bf1923a1709aadc38e2c05b0a2bc0e3ab38d978b16fac?context=explore

### Will you send logs?

No

**Comment by HammyHavoc** [comment]
FWIW, https://scalar.vector.im gives me a 403 error.

**Comment by t3chguy** [comment]
Does your server federate?

https://federationtester.matrix.org/

**Comment by HammyHavoc** [comment]
> Does your server federate?
> 
> https://federationtester.matrix.org/

Interestingly, no: https://federationtester.matrix.org/#matrix.splitanatom.com

The port is open, the SRV is set in the DNS, the `homeserver.yaml` looks right, and everything else seems to work. No doubt I'm missing something obvious and it'll be a case of the "9 at night after a long week". :- )

**Comment by t3chguy** [comment]
The integration manager needs functional federation to be able to authenticate you, I suggest you seek help with synapse federation
