### ISSUE TITLE
Replying to tall images causes 1.5 spinners

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24666]
### Steps to reproduce

1. Send a tall image (phone screenshot)
2. Reply to that message
3. Have a slow media server (takes forever to download)
4. Note the spinners

#### What did you expect?

A single spinner

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/221364410-da4dbfdb-af09-4da3-bb05-e36bc56e3996.png)

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023022401 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by luixxiul** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/21784 ?
