### ISSUE TITLE
Using touch to switch in the community sidebar or between room entries next to it won't switch the conversation view until minutes later

### ISSUE THREAD

**Issue by ell1e** [vector-im/element-web#24675]
### Steps to reproduce

1. Use a slow device like the PinePhone (Allwinner variant, not the Pro variant)
2. Use touch to navigate and switch rooms or community spaces. The sidebars will already take some seconds to react sometimes, but not too long. Scrolling and such remains operational outside of brief hiccups so it's not the entire page or browser being stuck.
3. The actual room view (where the messages are that people write, the message history) won't actually adjust to what you picked until multiple minutes later. If you switched multiple times then it will also go through all the switches throughout multiple minutes instead of just the latest pick.

In overall, it just feels like something is happening and delaying things by an extraordinarily long amount of time that shouldn't be.  Since it used to be less bad, this seems to be a regression.

#### What did you expect?
Expected level of delay on this slow device (various seconds of reaction time or occasional complete freezes for a second or so are expected)

#### What happened instead?
Switching the actual message history lags multiple minutes behind

### Operating system

postmarketOS 22.12 which is based on Alpine Linux, running on ARM64 device

### URL for webapp

https://app.element.io

### Application version

Mozilla Firefox 102.8.0esr as shipped by Alpine Linux

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
That is not a [supported environment](https://github.com/vector-im/element-web#supported-environments)

**Comment by ell1e** [comment]
Can you elaborate why not? It's a Linux desktop environment accessing your web app, so it fits:

> Desktop OSes means macOS, Windows, and Linux versions for desktop devices that are actively supported by the OS vendor and receive security updates

**Comment by t3chguy** [comment]
> for desktop devices

> PinePhone

**Comment by ell1e** [comment]
The PinePhone is regarding the software-side a desktop device.

Also,
> Definition: Issues only affecting unsupported environments are closed

It should affect all slow Linux devices, not just the PinePhone which just happens the one I am testing with.

**Comment by t3chguy** [comment]
We don't really prioritise touch support, nor small screens. If you can reproduce with a device that fits the criteria then we can reopen

**Comment by ell1e** [comment]
Do you really need me to reattach a large screen and mouse to it just to reproduce that it's well, slow?
Because I can, the PinePhone supports that (it's just an ARM64 desktop computer in a phone form factor). But it doesn't seem to be a useful thing for me to be doing.

**Comment by t3chguy** [comment]
If it isn't specific to touch then it sounds like https://github.com/vector-im/element-web/issues/14574 or https://github.com/vector-im/element-web/issues/4997 but even worse due to the slow device

**Comment by ell1e** [comment]
Looks like a duplicate of #4997 to me, especially since I'm also in a lot of rooms (surely a 100). My apologies for the duplicate filing
