### ISSUE TITLE
Memory leak and high CPU usage when I use the Explore

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24672]
### Steps to reproduce

1. Open Explore;
2. Type "electron" to search
3. Monitor usage and check logs
4. Slowly scroll down to find the place where Element Desktop starts to destroy your hardware.

#### What did you expect?
Search does not ask hundreds MBs of RAM, Explore does not make jumps of RAM usage.
#### What happened instead?
High hardware usage, memory consuming... In my case it's jump from 700-800 to  1500-1600 MBs.

### Operating system

Windows 7

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
@JeanPaulLucien Windows 7 is not a supported environment https://github.com/vector-im/element-web#supported-environments - Electron explicitly dropped support for it - https://www.electronjs.org/blog/electron-23-0

> Additionally, support for Windows 7/8/8.1 has been dropped.
