### ISSUE TITLE
First message sent in lazily created DM is unencrypted

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#24683]
### Steps to reproduce

 - opened matrix.to link for user
 - continue with Element, opening element://...
 - clicked Message in the right panel
 - typed :wave: and pressed enter
 - Element started creating the room
 - when the room got created, my :wave: message had a red shield saying it was unencrypted. When checking the source, it was indeed:
 ```json
{
  "content": {
    "body": "👋",
    "msgtype": "m.text",
    "org.matrix.msc1767.text": "👋"
  },
  "origin_server_ts": 1677508841417,
  "sender": "@bwindels:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 7214,
    "transaction_id": "m1677508841305.417"
  },
  "event_id": "$hL0WCpYLAN12KZXHcJZcmCOBoAXhDd04m_2c7G34ZeE",
  "room_id": "!UAZFKFsUzwaxJvImIy:matrix.org"
}
```
 - subsequent messages sent in the room _were_ encrypted. The room has a `m.room.encryption` state event:
```json
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2"
  },
  "origin_server_ts": 1677508835641,
  "sender": "@bwindels:matrix.org",
  "state_key": "",
  "type": "m.room.encryption",
  "unsigned": {
    "age": 9681
  },
  "event_id": "$Eomv8hP6Pty-0ElTipql1bKA9z_F7jPX58Era27aWN4",
  "room_id": "!UAZFKFsUzwaxJvImIy:matrix.org"
} 
```

#### What did you expect?

The first message to be encrypted

#### What happened instead?

It wasn't

### Operating system

Fedora 36

### Application version

Element version: 1.11.8 Olm version: 3.2.12

### How did you install the app?

flatpak

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Element version: 1.11.8

This version is 6 months old, please update
