### ISSUE TITLE
Invalid inline style comments are allowed

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24686]
### Steps to reproduce

1. Add a CSS rule as a comment with double slash `//` like `//a { color: pink; }` to any *.pcss file, such as `_ReplyTile.pcss` which has double-slash comments
2. Run `yarn run style:lint`

#### What did you expect?

It should return errors (See: https://github.com/matrix-org/matrix-react-sdk/pull/9099).

#### What happened instead?

It does not return an error.

### Will you send logs?

No

**Comment by weeman1337** [comment]
Unfortunately [the built-in rule](https://stylelint.io/user-guide/rules/no-invalid-double-slash-comments) allows `//` for scss like files.

We could create a rule based on the built-in one that checks all file types.

**Comment by luixxiul** [comment]
There's not a plan to do something for this. closing
