### ISSUE TITLE
the procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by KOYK** [vector-im/element-web#24693]
### Steps to reproduce

Describe the bug
the procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll

After new update I get this error.

downloading and installing from the setup file wont resolve the issue, since after I get prompted to update and the update is done, the same error will show

Desktop (please complete the following information):

OS: win7

### Outcome

downloading and installing from the setup file wont resolve the issue, since after I get prompted to update and the update is done, the same error will show

### Will you send logs?

No

**Comment by t3chguy** [comment]
Windows 7 is not in our support policy due to it not being supported by Microsoft. Chrome & Electron also dropped support for it. https://github.com/vector-im/element-web#supported-environments

**Comment by JeanPaulLucien** [comment]
@KOYK download and install 1.11.23.

**Comment by JeanPaulLucien** [comment]
Has broken clients for Windows 7 users. Nice job.

**Comment by t3chguy** [comment]
Reminder to those still on Windows 7 and 8.1, it has reached end of life.

# It is no longer a viable platform for a secure messenger.

https://www.microsoft.com/en-gb/windows/end-of-support?r=1
https://vivaldi.com/blog/pulling-the-plug-on-expired-operating-systems/
https://releases.electronjs.org/release/v23.0.0

https://github.com/vector-im/element-web#supported-environments

You can download old versions at https://packages.element.io but no support will be offered for users on unsupported operating systems.
