### ISSUE TITLE
Room with only 2 other users named "Erik and 2 others"

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24692]
### Steps to reproduce

I have a room with two other users (who we shall name, for the sake of example, Erik and Lisa) and myself.

#### What did you expect?

Room title is "Erik and Lisa"

#### What happened instead?

![image](https://user-images.githubusercontent.com/1389908/221856565-72460d23-f592-489f-93a0-1adc4cd7a963.png)

### Application version

Element Nightly version: 2023022001 Olm version: 3.2.12

### How did you install the app?

nightly debian

### Homeserver

Synapse 1.77ish

### Will you send logs?

Yes

**Comment by Johennes** [comment]
I cannot reproduce this. When I go over + button > start new chat, select two users A and B and then write the first message, I'm dropped into a room without an `m.room.name` event that is titled "A and B" in Element Web.

Assuming this is fixed. Please reopen if you still experience this.

**Comment by richvdh** [comment]
for sure, at some point in the last 4 months I have restarted the application and it has fixed itself ;)
