### ISSUE TITLE
Flaky Percy test: URL Preview

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24690]
### Steps to reproduce

This Percy test: https://percy.io/dfde73bd/matrix-react-sdk/builds/25491316/changed/1421018150?browser=edge&browser_ids=18%2C33%2C34%2C35&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=400&widths=400%2C800%2C1024%2C1920

Failed because the timestamp changed.

Presumably it will fail again next time it runs, if it doesn't control the time, or ignore it.

![image](https://user-images.githubusercontent.com/76812/221825180-0ab8e123-42b2-4039-b2b4-bdd0911d8611.png)

**Comment by andybalaam** [comment]
@t3chguy you did some work to prevent times changing in Percy. Can you point me to what you did so I can check this one out?

**Comment by t3chguy** [comment]
@andybalaam https://github.com/matrix-org/matrix-react-sdk/blob/95223c87feca23559269c16844826e0bcf4ab2a8/cypress/e2e/timeline/timeline.spec.ts#L339-L343 https://github.com/matrix-org/matrix-react-sdk/pull/10239

**Comment by t3chguy** [comment]
The fix landed after your problematic Percy run..


![image](https://user-images.githubusercontent.com/2403652/221826094-16dca8d5-edf4-41f8-9466-cfeba62a2761.png)
