### ISSUE TITLE
Room pill should always try to resolve room name and avatar

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24705]
### Your use case

Part of https://github.com/vector-im/element-meta/issues/1030

#### What would you like to do?

Currently room pills to  look like this if a user didn't join the room yet:

![image](https://user-images.githubusercontent.com/6216686/222102188-eb4d7f50-a84e-4278-b647-974cb69738d3.png)

Matrix.to for instance does display the room name and avatar:

![image](https://user-images.githubusercontent.com/6216686/222102517-40ae53eb-4495-4f3a-a059-d0ca98168676.png)

#### Why would you like to do it?

Consistent user experience: Same room name and avatar before and after joining the room.

#### How would you like to achieve it?

Try to query room data when adding the pill.

**Comment by t3chguy** [comment]
> Matrix.to for instance does display the room name and avatar:

It grabs huge pages of `/publicRooms` API until it finds the right room, this isn't exactly a great thing to copy :P

**Comment by giomfo** [comment]
@weeman1337 FYI when the room/space details are not available, we will display the following pill:
<img width="103" alt="image" src="https://user-images.githubusercontent.com/8969772/224039360-44cbb923-4a0e-4721-b4c7-1635ede1823d.png">

**Comment by giomfo** [comment]
We changed our mind, we won't retrieve room details by default. We will use the local data
