### ISSUE TITLE
Can't run app-1.11.24 app on Windows 8.1

### ISSUE THREAD

**Issue by Gitogitos** [vector-im/element-web#24712]
### Steps to reproduce

Don’t know what happened but after self update the Element not start any more. The previous version which I have still in directory – app-1.11.23 works fine but the new one app-1.11.24 no.
Is Element drop support for Win 8.1??? because I still use it and I haven’t seen any notice about it.

#### What happened instead?

App not running at all, after log out, restart whole pc no making any diffrence. When I click on Element icon there is no reaction, Idon’t see any process with Element.exe in taskbar. 

### Operating system

Windows 8.1 x64

### Application version

1.11.24

### How did you install the app?

Self update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
See pinned issue https://github.com/vector-im/element-web/issues/24693

**Comment by durablenapkin** [comment]
It would be nice if auto-update could possibly be disabled for 1.11.23 instances on Windows 7/8/8.1 server-side (detect OS, if Windows 7/8/8.1 then don't auto-update)

**Comment by t3chguy** [comment]
The update server is a Cloudflare R2 bucket, it is a static file host and cannot detect OS. Squirrel.Windows also doesn't support not downloading updates based on conditions.
