### ISSUE TITLE
GetPackageFamilyName could not be located in KERNEL32.dll

### ISSUE THREAD

**Issue by rlebeau** [vector-im/element-web#24713]
### Steps to reproduce

When I started up the Element desktop app this morning, it fails to run, displaying this popup error:

> The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll.

`GetPackageFamilyName` was introduced in Windows 8, but I am running on Windows 7.

The app was working perfectly fine yesterday.  I had originally installed **v1.11.22.0**, but apparently somehow **v1.11.24.0** got installed.  I DID NOT install v1.11.24.0 myself, did it auto-update itself?

I have now reinstalled v1.11.22.0 and it runs fine.

#### What did you expect?

I expected it to run.

#### What happened instead?

It failed to run.

### Operating system

Windows 7 Home Premium

### Application version

Element version: 1.11.24

### How did you install the app?

https://element.io/download

### Homeserver

matrix.org, gitter.im

### Will you send logs?

No

**Comment by t3chguy** [comment]
See pinned issue https://github.com/vector-im/element-web/issues/24693

Also in release notes https://github.com/vector-im/element-desktop/releases/tag/v1.11.24

**Comment by durablenapkin** [comment]
If anyone wants to get it working again:

1) Edit C:\Windows\System32\drivers\etc\hosts and add `127.0.0.1 packages.element.io`
1) Uninstall Element
2) Download https://packages.element.io/desktop/install/win32/x64/Element%20Setup%201.11.23.exe (Windows x64 build,or 32 bit build - https://packages.element.io/desktop/install/win32/ia32/Element%20Setup%201.11.23.exe)
3) Install (shouldn't be any need to re-log in/authenticate)
4) Confirm autoupdate is disabled by going to Settings => Help & About => Click on Check for update and confirm an error message is shown

**Comment by t3chguy** [comment]
@durablenapkin or do it the officially supported way by creating a config.json file and adding `"update_base_url": null` to it.

**Comment by durablenapkin** [comment]
Thanks! That's good to know, it might be good to mention that (and v1.11.23 as the last working build for Windows 7/8/8.1) in #24693

**Comment by t3chguy** [comment]
@durablenapkin we don't want to promote staying on an old version which won't receive security updates. Just noting possibility to disable updates here in a better way than editing the hosts file.

**Comment by JeanPaulLucien** [comment]
> config.json file and adding `"update_base_url": null` to it

Does not work, Where should I place this file in Windows 7?

**Comment by t3chguy** [comment]
@JeanPaulLucien https://github.com/vector-im/element-desktop/#user-specified-configjson

**Comment by rlebeau** [comment]
> > config.json file and adding `"update_base_url": null` to it
> 
> Does not work, Where should I place this file in Windows 7?

Worked fine for me.  It is placed in the `%APPDATA%\Element` folder.

**Comment by DeMoN100** [comment]
> > > config.json file and adding `"update_base_url": null` to it
> > 
> > 
> > Does not work, Where should I place this file in Windows 7?
> 
> Worked fine for me. It is placed in the `%APPDATA%\Element` folder.

This did not work for me either I placed the config.json in %appdata%/local/element-desktop folder.
I also tried the host edit & that did not work either.

**Comment by Seceroth** [comment]
I would reply in the pinned issue, but it's locked.
It wouldn't have been hard to detect the OS and not update to a version that wouldn't run on it, instead of straight up breaking it.

**Comment by DeMoN100** [comment]
I've even attempted to completely uninstall & download an older version but this issue keeps coming up with no solution.

**Comment by t3chguy** [comment]
> I would reply in the pinned issue, but it's locked.
> It wouldn't have been hard to detect the OS and not update to a version that wouldn't run on it, instead of straight up breaking it.

That means knowing ahead of time which version breaks it and baking that in months/years ahead otherwise people on really old versions would get updated. Squirrel.windows in electron doesn't support conditional updates in any meaningful way where you can set rules based on metadata on the server.

**Comment by t3chguy** [comment]
> I've had no trouble using the `config.json` solution.  I've been running Element 1.11.23 for 2 months now and it runs just fine on Windows 7, no forced updates.
> 
> ![config](https://user-images.githubusercontent.com/15006977/236894555-b681c7b4-af21-49b2-8804-52dd6b3ffad4.png)
> 

Worth noting that version has published security vulnerabilities.

**Comment by DeMoN100** [comment]
Just tried again with the .json config on the newest setup.exe & now it seemed to work idk why I didn't do anything different I just get a popup an error that theres an invalid line on the config on line 17. But there is no line 17 it's just exactly how you have it in the screenshot. I can click the popup error away & it works fine now.

**Comment by rlebeau** [comment]
> Worth noting that version [1.11.23] has published security vulnerabilities.

Perhaps, but upgrading past Windows 7 simply isn't an option for me right now.
