### ISSUE TITLE
Apple cannot check it for malcious software !!!

### ISSUE THREAD

**Issue by AnassDriate** [vector-im/element-web#24728]
### Steps to reproduce

Install Element 1.11.23   /    1.11.24 

### Outcome

We are not able to use Element FOSS 1.11.23 and 1.11.24

### Operating system

MacOS

### Application version

1.11.24

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
When did you try 1.11.24? We fixed it two days ago.

**Comment by AnassDriate** [comment]
I just re-installed it right now and it works as expected
Thank you 
Ticket can be closed
