### ISSUE TITLE
SelfBuilded element app failing media devices in element call

### ISSUE THREAD

**Issue by VannaKarenina** [vector-im/element-web#24727]
### Steps to reproduce

1. Start elemt call in room
2. Join in
3. See errors in console:
`Uncaught (in promise) DOMException: Could not start audio source`
`Failed to get stream for device default DOMException: Could not start video source`

#### What did you expect?
Normal media device work in call
#### What happened instead?
Media devices not load

### Operating system

windows 10

### Application version

element 1.11.24

### How did you install the app?

self builded (https://github.com/vector-im/element-desktop)

### Homeserver

synapse latest

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This looks to be the same as https://github.com/vector-im/element-web/issues/24662 except for Element Call? Did you OV/EV sign the app?

**Comment by VannaKarenina** [comment]
> This looks to be the same as https://github.com/vector-im/element-web/issues/24662 except for Element Call? Did you OV/EV sign the app? 

Yes, but any way. 

When I join in call I see that app connect to mic and cam. We can see this in confindential manager I think if there was a signature problem the application would not have been able to access them at all

**Comment by VannaKarenina** [comment]
Could it be a problem in the way I signed the application? Because the machine fully trusts the certificate with which I signed it
