### ISSUE TITLE
Desktop: Add a profile chooser like Firefox

### ISSUE THREAD

**Issue by trytomakeyouprivate** [vector-im/element-web#24735]
### What would you like to do?
Element allows multiple users by adding the `--profile <name>` to the end. I would like to run this command without a name, to trigger a small menu showing the installed users, allowing to add or erase them. Firefox does exactly that. Elements multiuser functionality is mostly unknown, because there is no GUI integration.

### Why would you like to do it?
Multiple Users are a good way to have secure seperate identities for groups, as the protocol is decentralized, so little trust should be applied regarding metadata.

### How would you like to achieve it?
- allowing `<command to run app> --profile` to open a profile chooser
- A button in GUI under account settings "log in with another account"
- The button switching to "open account manager" when there are 2+ accounts.

### Have you considered any alternatives?

opening through terminal after finding the method online somewhere

**Comment by t3chguy** [comment]
`--profile` is a workaround for https://github.com/vector-im/element-web/issues/2320 - closing in favour of that
