### ISSUE TITLE
Cannot login after starting my holiday

### ISSUE THREAD

**Issue by thany** [vector-im/element-web#24745]
### Steps to reproduce

1. Go on a holiday
2. Start Element
3. It immediately falls into "Connectivity to the server has been lost"

I'm not actually sure if going on an actual holiday is strictly required. I'm just telling what I'm seeing that's happening.

#### What did you expect?
I can connect with my account perfectly fine.

#### What happened instead?
Observations so far, other than (2) from above:

* All Settings -> Help & About is not reachable. Click it just closes the settings screen.
* Trying to change my display name, it says `MatrixError: [401] Invalid Authorization header. (https://matrix-client.matrix.org/_matrix/client/r0/profile/[...]/displayname)`
* There seems to be no (obvious) way to disconnect an account and set it up again, just to see if the app has somehow "forgotten" my authentication or something.
* Element on my Android phone remains working perfectly fine, although on a 4G network.

### Operating system

Windows 10 22H2

### Application version

Latest, I hope. I don't know (see first observation).

### Will you send logs?

No

**Comment by thany** [comment]
Note: not sending logs because I cannot get to the Help & About screen.

**Comment by dbkr** [comment]
Dup of https://github.com/vector-im/element-web/issues/23063 I think

**Comment by thany** [comment]
If you're closing this issue as not planned, please tell me the solution at least.

**Comment by aaronraimist** [comment]
> If you're closing this issue as not planned, please tell me the solution at least.

@thany Your issue was not closed because it was solved. The issue was closed because it is a duplicate of another existing issue: #23063. There is more information about why the bug might be happening here: https://github.com/vector-im/element-web/issues/23063#issuecomment-1212563748. They need logs to figure out exactly what is happening.

**Comment by thany** [comment]
Can't send logs when I can't reach the help&about screen.

**Comment by aaronraimist** [comment]
You can open the browser console and manually copy things out of it.

**Comment by thany** [comment]
It's not a browser. I'm using the Windows desktop app.

**Comment by t3chguy** [comment]
@thany the Desktop app is built using Electron which uses Chromium, so it is a browser.

**Comment by thany** [comment]
Either way, I still don't know what you expect me to do. How do I open the console, and what do you want me to copy out of it?
