### ISSUE TITLE
Space settings dialog has a browser tooltip *everywhere*

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24740]
### Steps to reproduce

1. Open space settings
2. Move your mouse over the dialog
3. Wait a couple seconds for the browser tooltip to appear

#### What did you expect?

No tooltip

#### What happened instead?

A tooltip.

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023030301 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/pull/6151
