### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by haspelstfs** [vector-im/element-web#24748]
### Steps to reproduce

1. I am trying to search in my rooms.
2. Using Element on MacOS
3. Error message : "Initialisierung der Suche fehlgeschlagen, für weitere Informationen öffne deine Einstellungen"
4. There is nothing visible to me in the settings, how to resolve this issue...

#### What did you expect?
Getting search results
#### What happened instead?
Error

### Operating system

MacOS

### Application version

Version von Element: 1.11.24, Version von Olm: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Please send logs with this issue linked

**Comment by haspelstfs** [comment]
I kind of found the solution. The re-indexing option was not visible to me. I had to reset my security key, then I could reset my search indexing and now it works.
You may close the ticket.
Logs are in the attachement.
[rageshake.zip](https://github.com/vector-im/element-web/files/10896242/rageshake.zip)

Thanks for the fast reply...
