### ISSUE TITLE
Mouse middle button click pastes from primary clipboard instead of secondary

### ISSUE THREAD

**Issue by liZe** [vector-im/element-web#24758]
### Steps to reproduce

1. Select some text and copy it with Ctrl+C
2. Select some other text (and don’t copy it)
3. Middle-click on Element’s message composer

#### What did you expect?

I expected to get the second text pasted, as on any other app on Linux.

#### What happened instead?

I get the first text pasted.

The message composer seems to be a `contenteditable` tag. My browser usually pastes the correct data for middle-click on `contenteditable` elements, so there must be some JS magic doing the wrong paste.

### Operating system

Linux

### Browser information

Epiphany

### URL for webapp

app.gitter.im

### Application version

Gitter version 1.11.24, Olm version 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Epiphany

This is not a [supported environment](https://github.com/vector-im/element-web#supported-environments)

**Comment by liZe** [comment]
> This is not a [supported environment](https://github.com/vector-im/element-web#supported-environments)

Oh, OK.
