### ISSUE TITLE
PNG uploads as a file attachment rather than image on develop

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24761]
### Steps to reproduce

1. In a room, attach a PNG

#### What did you expect?
See image preview

#### What happened instead?
See file:

![Screenshot from 2023-03-07 13-38-40](https://user-images.githubusercontent.com/51663/223438857-4c86c302-95bf-4748-84bf-218e8e88ddab.png)

### Browser information

Chromium 110.0.5481.177 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 5ae88eb30b0c-react-32aa18ff2e0e-js-b4cdc5a92397 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
@kittykat please send logs, this happens when your browser's canvas can't generate a thumbnail typically

**Comment by kittykat** [comment]
```
Room ID: !UlIlSOXSmCVQUaTbFh:matrix.org
Message ID: $tYcrlMrJW6kiz8djEGuvcsJZTybepoFzZkjbss_cZZ0
```

**Comment by t3chguy** [comment]
```
2023-03-07T13:54:24.431Z E Invalid .png file header
Error: Invalid .png file header
    at extractChunks (https://develop.element.io/bundles/b4fa679a5cbd84250cf6/vendors~init.js:178640:31)
    at https://develop.element.io/bundles/b4fa679a5cbd84250cf6/init.js:63467:50
    at async Promise.all (index 0)
    at async loadImageElement (https://develop.element.io/bundles/b4fa679a5cbd84250cf6/init.js:63477:19)
    at async infoForImageFile (https://develop.element.io/bundles/b4fa679a5cbd84250cf6/init.js:63511:24)
    at async ContentMessages_ContentMessages.sendContentToRoom (https://develop.element.io/bundles/b4fa679a5cbd84250cf6/init.js:63825:29)
```

@kittykat would you be able to share the problem file (internally on the rageshake)

**Comment by kittykat** [comment]
@t3chguy done!

**Comment by t3chguy** [comment]
The file is called `.png` but it actually is a JPEG file

```
t3chguy@Michael-t3chguy-MBP ~/Desktop> file 223445092-3dab0ff7-8527-4861-929f-7e8dc5fc53dc.png 
223445092-3dab0ff7-8527-4861-929f-7e8dc5fc53dc.png: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1080x2400, components 3

**Comment by kittykat** [comment]
🤔 Wonder what my phone is doing…

Should JPEGs not be previewed? Is it assuming file type based on extension? If it is, can we get it to check file type instead?

**Comment by t3chguy** [comment]
JPEG should be, but for PNGs we need to check if it is hidpi by parsing it, so if we get given a faulty PNG we have to assume the file is broken not just mis-named

> Is it assuming file type based on extension?

It is asking the browser but some browsers do indeed naively assume by file extension (sometimes being completely wrong for container formats like mkv which can be audio-only or video)

**Comment by t3chguy** [comment]
@kittykat https://github.com/matrix-org/matrix-react-sdk/pull/10308 should allow the PNG parsing to fail, but this file is likely to be problematic either way as we'll be sending it with a mime type of `image/png` (as the browser tells us) and other devices (native/mobile) may look at that, pick the specific renderer and fail to render it entirely. Not sure what Synapse's thumbnailer will do either, that could fail also.
