### ISSUE TITLE
Unable to access microphone.  Call failed because microphone could not be accessed.

### ISSUE THREAD

**Issue by proclos** [vector-im/element-web#24770]
### Steps to reproduce

Try any One2One Audio or Video Call.
(Exchanging text messages and uploading content works.)

#### What did you expect?
Audio or video call with other participant

#### What happened instead?
Error message in popup:  Unable to access microphone. Call failed because microphone could not be accessed. Check that a microphone is plugged in and set up correctly.

Mircrophone works with any other application. Error seems to be related to a certificate issue, since this in console log:
[5078:0308/133527.194681:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

### Operating system

MacOS Ventura 13.2.1 (22D68)

### Application version

1.11.24

### How did you install the app?

https://packages.riot.im/desktop/install/macos/Element.dmg

### Homeserver

Synapse 1.78.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please reinstall 1.11.24 from the link you provided, the initial release had a notarisation failure but has been re-uploaded

**Comment by proclos** [comment]
Thank you for your feedback!

Reinstalled as suggested, but still no success.
There is one additional error message on console log.

[5583:0308/140324.492000:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

Error returned: <dictionary: 0x1ed7d0c40> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x1ed7d0dd8> { length = 18, contents = "Connection invalid" }
}

**Comment by t3chguy** [comment]
The AIA certificate error looks to be coming from Chromium, as if it is refusing to connect to a self-signed/unsigned server. 

According to the logs you sent your TURN server configured in your Synapse is invalid

`SyntaxError: Failed to construct 'RTCPeerConnection': 'turns:turn.choose-open.cloud:443??transport=tcp' is not a valid stun or turn URL.` the double question mark seems amiss.
