### ISSUE TITLE
Key request dialog covers the timeline and makes it unusable 

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24780]
### Steps to reproduce

1. Open an encrypted room where you do not have the key to decrypt messages
2. Open a thread panel
3. Scroll the main timeline
4. Find the messages which cannot be decrypted

#### What did you expect?

The panel should be small and not cover the timeline.

#### What happened instead?

It covers the timeline and makes it unusable until you close the thread panel or open another room.

https://user-images.githubusercontent.com/3362943/224031411-90546656-96be-4c65-a36f-b66e1f3e77d0.mp4

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

localhost

### Will you send logs?

No

**Comment by luixxiul** [comment]
The issue is related to the dialog's flexbox design. The buttons should be wrapped not to make the message so tall.

**Comment by MadLittleMods** [comment]
@luixxiul I don't think this is related to having your language switched to Japanese (I can imagine it happening in English). I've modified the description to remove that detail from the reproduction steps.
