### ISSUE TITLE
Arm64 Native Build For Windows

### ISSUE THREAD

**Issue by huangyinhaow** [vector-im/element-web#24799]
Windows computers with Arm SOC have a long battery life and now more and more people, especially teachers and students, are using these kind of computers and wnr is exactly what they need.
Thanks!

**Comment by t3chguy** [comment]
Duplicate of #17942

**Comment by huangyinhaow** [comment]
#17942 is about Linux, not windows.

**Comment by t3chguy** [comment]
How do you figure? The issue title literally says windows & linux

**Comment by huangyinhaow** [comment]
> How do you figure? The issue title literally says windows & linux

Yes, it has "windows & linux" in its title, but we don't get any useful replies on "Windows" below.

**Comment by huangyinhaow** [comment]
Sorry, I thought #17942 was closed because it hasn't been updated in a long time.

**Comment by jglathe** [comment]
What is this. No ARM64 for Windows? Quite unbelievable.
