### ISSUE TITLE
Can't add phone number

### ISSUE THREAD

**Issue by TechnoMom** [vector-im/element-web#24796]
### Steps to reproduce

1. Where are you starting? What can you see? From Settings > General > Phone Numbers
2. What do you click? Selected the correct country code, entered my phone number, and hit the Add button.
3. More steps… I got a message saying that an SMS message had been sent to my phone, then this error: MatrixError: [500] Internal Server Error (https://matrix-client.matrix.org/_matrix/client/r0/account/3pid/msisdn/requestToken) (Status 500)
![500 error](https://user-images.githubusercontent.com/17887141/224440894-c6633943-ca27-4417-ae96-43f7a059e199.png)

#### What did you expect?
I expected to get a text message (I didn't) and to enter a code from it into the app in order to add my phone number
#### What happened instead?
The 500 error noted above

### Operating system

macOS

### Application version

1.1.24

### How did you install the app?

From https://element.io/download

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue with matrix.org not element web, I believe they disabled the ability to add phone numbers and this isn't something the matrix spec supports
