### ISSUE TITLE
Clicking a user pill navigates away from the room

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#24797]
### Steps to reproduce

1. Find a message containing a user pill
2. Click said user pill

#### What did you expect?

The right panel should open with the user's profile, while staying where you are in the room.

#### What happened instead?

The right panel opens with the user's profile, and the room timeline is replaced with the app's home screen. Once this has happened, closing the right panel can cause you to switch spaces and other fun navigational glitches.

### Operating system

NixOS unstable

### Browser information

Firefox 110.0.1

### URL for webapp

develop.element.io

### Application version

Element version: c85eb81ed00a-react-127a3b667cd1-js-913cd257f497 Olm version: 3.2.12

### Homeserver

Synapse 1.77.0

### Will you send logs?

No

**Comment by robintown** [comment]
This issue is **not present** in the 1.11.25 RC

**Comment by weeman1337** [comment]
Caused by https://github.com/matrix-org/matrix-react-sdk/commit/ad26925bb6628260cfe0fcf90ec0a8cba381f4a4 . That was a day after the RC. Phew :wink:
