### ISSUE TITLE
Regression around emoji replies to emoji

### ISSUE THREAD

**Issue by AndrewRyanChama** [vector-im/element-web#24798]
### Steps to reproduce

Send an emoji reply to a big emoji

### Outcome

According to what is in #13333 the emojis should remain large, but this fix no longer works
<img width="434" alt="Screenshot 2023-03-10 at 10 35 06 PM" src="https://user-images.githubusercontent.com/89478935/224469285-04546b06-5a82-4077-9bd3-e3e74eb0bb66.png">

### Will you send logs?

No

**Comment by lapaz17** [comment]
@t3chguy could you assign me?

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/7592
