### ISSUE TITLE
identity server https://vector.im somehow forgotten my email and whole account after successful registration

### ISSUE THREAD

**Issue by cypa** [vector-im/element-web#2479]
I've registered via android client, then go to desktop to open confirmation email msg and click the link in it, then I had login successfully via web client in my desktop browser ... a few days later I've made first attempt to login via android client, which was insufficient

a few weeks later, I've registered again with same email address successfully, it was today actually 

I've always leave default home/identity server settings for registration

**Comment by ara4n** [comment]
if you can PM me (@ matthew:matrix.org) the email address i can try to see what's gone wrong.

**Comment by kittykat** [comment]
Closing as it's an old issue without steps to reproduce. If it still happens, please reply with @kittykat in your message and I will reopen it for you.
