### ISSUE TITLE
Gibberish instead of login screen

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#24800]
### Steps to reproduce

1. Element complains that its session was lost and suggests to relog
2. click log out
3. gibberish

#### What happened instead?
![image](https://user-images.githubusercontent.com/2803622/224490536-4f2348b8-a421-44c3-a968-f036e299579a.png)

### Operating system

arch, sway 1.8.1

### Application version

Element Nightly version: 2023031101 Olm version: 3.2.12

### How did you install the app?

aur

### Homeserver

synapse 1.77

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report issues with community maintained packages to their maintainers, the arch package isn't one of ours
