### ISSUE TITLE
Possible data leak

### ISSUE THREAD

**Issue by p3tr0v** [vector-im/element-web#24806]
### Steps to reproduce

1. Open terminal and go to `/home/[user]/.config/Element/Local Storage/leveldb`
2. Type `strings` command on log files.
3. You will see traces of talks.

#### What did you expect?
I expect Element clear any possible log with info that could be extracted by someone and break the privacy/security/anonimous

### Operating system

Parrot OS 5.2

### Application version

1.11.24

### Will you send logs?

No

**Comment by t3chguy** [comment]
> I expect Element clear any possible log

This isn't a log. This is the Chromium's LocalStorage. It uses leveldb which uses a technique called journalling to prevent data loss on power loss. https://github.com/google/leveldb/blob/main/doc/impl.md#log-files

LocalStorage gets wiped when you log out, until then it is used to store settings and such.
