### ISSUE TITLE
"Rust Cryptography Implementation" labs flag has disappeared

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24813]
with react-sdk v3.67.0:

![image](https://user-images.githubusercontent.com/1389908/224803654-82d03ca0-b897-4366-859c-7fe426848a6e.png)

On current develop:

![image](https://user-images.githubusercontent.com/1389908/224805277-607df437-e9bb-4cdb-89c4-7b9a369875d2.png)

**Comment by richvdh** [comment]
This seems to have been introduced by https://github.com/matrix-org/matrix-react-sdk/pull/10276; specifically https://github.com/matrix-org/matrix-react-sdk/pull/10276/files#diff-a36208da63333eaa9839c9cd23c857f00d222bac4b242a9a69de8698a366a525R59 which filters out any "disabled" settings.

I'm prepared to believe I was holding it wrong (though https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/settings/controllers/SettingController.ts#L71 is less than forthcoming on what exactly "disabled" is meant to mean), but is there any other easy way to achieve a setting which is `disabled` in the HTML attribute sense?

**Comment by t3chguy** [comment]
@richvdh my bad, disabled for Labs definitely makes more sense as shown as disabled with a helpful hint, will take this on

**Comment by richvdh** [comment]
thanks!
