### ISSUE TITLE
Hide "create account" registration links when registration is disabled (`UIFeature.registration: false`)

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24814]
*Spawning from a user report rageshake, https://github.com/matrix-org/element-web-rageshakes/issues/20495*

### Steps to reproduce

 1. Enable guest access on Element/Synapse
 1. Configure Element to [disable registration `UIFeature.registration: false`](https://github.com/vector-im/element-web/blob/934eb22d3a838a4925cc222c1a87d956d0b03620/docs/config.md#ui-features)
 1. Visit a room as a guest

First possibility:

 1. Open the user menu
 1. Click the `Create an account` link (this link should not be visible)
 1. Notice you're at a blank page  `/#/register`

![](https://user-images.githubusercontent.com/558581/224875732-c2bb532b-f716-4e1a-8f55-d735c0f7ff1f.png)

Second possibility

 1. Open the user menu -> **Settings** - > **Create account**

![](https://user-images.githubusercontent.com/558581/224876874-9e4b0686-4668-4132-be2a-401072eb68ee.png)

#### What did you expect?

The create account buttons/link should not be visible when registration is disabled.

#### What happened instead?

The create account actions are visible and link to a blank registration page when registration is disabled.

### Operating system

Windows 10

### Browser information

Chrome Version 110.0.5481.180

### URL for webapp

app.gitter.im

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### Homeserver

gitter.im

### Will you send logs?

No

**Comment by t3chguy** [comment]
@MadLittleMods I'd argue gitter shouldn't be using this UIF, especially once this is fixed. As then there'll only be `Sign in` buttons and people might think that if they don't already have an account then they can't acquire one. Take https://chat.mozilla.org/#/room/!ZhDoFXlMzzCuqKMZoO:mozilla.org for example, registration isn't  disabled and *just works*

**Comment by MadLittleMods** [comment]
@t3chguy Thanks for fixing up these spots in https://github.com/matrix-org/matrix-react-sdk/pull/10371!

We only had sign-in buttons on Gitter before. Perhaps some spots in Element would benefit from the same "Sign-in to start talking" language instead of "Use your account to sign-in" which is a bit more awkward.

Gitter reference:

Gitter `/login` and sign-in modal | Gitter not logged in room/chat view | Gitter homepage
--- | --- | ---
![Gitter /login](https://user-images.githubusercontent.com/558581/225091889-94670d41-7da9-4a44-bbae-cccdd1c83cc0.png) ![Gitter sign-in modal on /login](https://user-images.githubusercontent.com/558581/225091023-19ec7ae1-8b32-4fad-b65f-e6d8c2fbbc7f.png) | ![Gitter not logged in room/chat view](https://user-images.githubusercontent.com/558581/225092957-fb43f056-c1a9-4daf-a47a-c71057b60375.png) | ![Gitter homepage](https://user-images.githubusercontent.com/558581/225091989-a601fa0e-1c03-416b-9f25-227133b62f11.png)
