### ISSUE TITLE
anything that looks like an mxid is now unexpectedly pillified, complete with broken avatar

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#24817]
### Steps to reproduce

1. Type `@foo:bar.com` verbatim in a message (no tab complete or anything)
2. Observe that it gets transformed into a weird ugly pill with a blank avatar:

<img width="208" alt="Screenshot 2023-03-14 at 10 04 38" src="https://user-images.githubusercontent.com/1294269/224966572-454cff36-1997-4993-b8ee-05df7b479963.png">

#### What did you expect?

mxids shouldn't be pillified without tab-complete.

#### What happened instead?

anything that looks like an mxid gets unexpectedly and brokenly pillified.

### Operating system

macOS

### Application version

nightly

### How did you install the app?

nightly

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
We are going to roll this back before the release.
