### ISSUE TITLE
Adding a phone number fails

### ISSUE THREAD

**Issue by CorruptComputer** [vector-im/element-web#24815]
### Steps to reproduce

1. Add a US phone number
2. Adding the phone number will fail

![image](https://user-images.githubusercontent.com/5573038/224897367-6c67d6ef-656f-4c3e-bb54-85abf913ed5d.png)

#### What did you expect?
I should be able to add a phone number to my account.

#### What happened instead?
I cannot add a phone number to my account.

### Operating system

Fedora Linux 37

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### How did you install the app?

https://flathub.org/apps/details/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
matrix.org neutered the ability to add an MSISDN
