### ISSUE TITLE
`allowedTags` React warning making it hard to debug

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24823]
### Steps to reproduce

1. Open the console

#### What did you expect?

Fewer spammy warnings

#### What happened instead?

```
⚠️ Your `allowedTags` option includes, `style`, which is inherently
vulnerable to XSS attacks. Please remove it from `allowedTags`.
Or, to disable this warning, add the `allowVulnerableTags` option
and ensure you are accounting for this risk.
```
x1000000

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023031401 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by JeanPaulLucien** [comment]
What is reason for this warning? I see too.

**Comment by Koakuma-spec** [comment]
I have this issue on Element Desktop for Arch Linux (1.11.25/3.2.12) but not on Windows (Element version: 1.11.30
Olm version: 3.2.14)

Is this warning something that I should be worried about?
