### ISSUE TITLE
Widget menu not visible if a user has no permissions to edit widgets

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24826]
### Steps to reproduce

1. Create a room as user A,
2. Invite user B
1. Add a jitsi widget to a room
3. As user B click the three dots in the widget title

#### What did you expect?

The menu should show up with the options available (for instance „revoke permissions“).

#### What happened instead?

The menu does not show up.

![widget](https://user-images.githubusercontent.com/6216686/225274642-68c61363-9d2f-4aeb-bc3e-2df8683974b9.gif)

### Operating system

Ubuntu 22.04.2 LTS

### Browser information

Chromium Version 110.0.5481.177 (Official Build) (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 4a18ab6d1b9a-react-0c38bd7bebf9-js-7faba5c2f0bb Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/2403652/225278233-c3a1a0f5-40c3-4185-afd5-3f175a3437fe.png">

Works fine for me on latest Nightly

**Comment by t3chguy** [comment]
Can't reproduce on Develop either

![image](https://user-images.githubusercontent.com/2403652/225279447-5fdfc587-47ea-4913-a5bf-e04e15b1cfb6.png)

**Comment by weeman1337** [comment]
@t3chguy thanks for testing this. I found the actual problem and updated the title and description accordingly.

**Comment by t3chguy** [comment]
@weeman1337 do you mean **not** visible?

**Comment by weeman1337** [comment]
Two options: Menu not visible or menu trigger visible :man_shrugging: 
I've updated the issue again.

**Comment by t3chguy** [comment]
The trigger isn't exclusive for admins, the `Revoke permissions` option lives there
