### ISSUE TITLE
Warning about inviting unknown users is not shown when creating a room via "Start chat"

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#24830]
### Steps to reproduce

1. Click the + "Start chat" button next to the header of the People section of the room list.
2. Attempt to start a chat with a user that you know does not exist (and alternatively, on a homeserver you know does exist).
3. Click "Go"
4. You are let through to the next stage without any warnings.
5. Send a message to create the room.

If you chose a non-existent localpart on a real matrix homeserver domain, then that non-existent user will have an invite (which the homeserver received). If a user is ever created under that localpart, then they will find that invite waiting for them when they log in for the first time.

If you chose a non-existent homeserver domain, then you will end up in a broken room.

### What did you expect?

The following errors appear when attempting to invite a non-existent user through the "Invite" dialog in an existing Matrix room.

When attempting to invite a non-existent localpart on an existing homeserver:

![image](https://user-images.githubusercontent.com/1342360/225382856-5bcf3aed-5eee-4739-aac6-28b57ad78122.png)

When attempting to invite any user on a non-existent homeserver:

![image](https://user-images.githubusercontent.com/1342360/225382769-7de48e29-043f-4075-aacd-a672895c931d.png)

### What happened instead?

For a non-existent user on an existing homeserver, no warning is presented on clicking Go here:

![Screenshot_20230315_165033](https://user-images.githubusercontent.com/1342360/225382284-af0f4564-052b-431c-bdbf-85a5612e5720.png)

When attempting to contact a user on a non-existent homeserver, you end up with a broken room. Clicking retry does nothing:

![image](https://user-images.githubusercontent.com/1342360/225383940-03336908-1c37-4e15-94eb-c6a49a415773.png)

To actually leave these rooms, user have to search for "Empty room" in their list of rooms and select it. This will take them to the same room, but with a composer that is usable. They can then leave the room from there.

### Operating system

NixOS

### Application version

Element version: 1.11.24 Olm version: 3.2.12

### How did you install the app?

nixpkgs package repository

### Will you send logs?

No

**Comment by t3chguy** [comment]
This looks like the create-dm-on-first-message flow caused a regression

**Comment by weeman1337** [comment]
Not sure if this is really a regression. Recording from pre-start-dm-on-first-message version:

![dm](https://user-images.githubusercontent.com/6216686/225536229-dea05cab-76ed-4179-af10-a2de6cb718ee.gif)

**Comment by weeman1337** [comment]
I do net get the error on sending message, otherwise behaves the same as pre-create-dm-on-first-message.

![dm2](https://user-images.githubusercontent.com/6216686/225536850-3235b0af-d829-4afd-aab4-2dce39256598.gif)

**Comment by weeman1337** [comment]
@anoadragon453 can you send logs right after „Some of your messages have not been sent“ happened?

**Comment by anoadragon453** [comment]
@weeman1337 to encounter the broken room, you need to attempt to invite a user from a homeserver that will not respond to an invite over federation. In your example you're using matrix.org, which will.

**Comment by anoadragon453** [comment]
In the case of the homeserver that does exist (your first gif), I expect to still receive a warning that the user does not exist (a /profile lookup for them failed). We have such a warning when inviting a user to an existing room:

![](https://user-images.githubusercontent.com/1342360/225382856-5bcf3aed-5eee-4739-aac6-28b57ad78122.png)

**Comment by giomfo** [comment]
We should consider to implement client side this [MSC3720: Account status endpoint](https://github.com/matrix-org/matrix-spec-proposals/blob/babolivier/user_status/proposals/3720-account-status.md). This would ease the handling of these use cases

**Comment by anoadragon453** [comment]
@giomfo It may have been an intentional design decision for [`GET /_matrix/client/v3/profile/{userId}`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3profileuserid) to return a 404 if you don't share a room with that user, as it allows users to hide the fact that they exist from certain other users. In this world, having a warning like the one above about the user *might* not existing is the best we can do.

MSC3720 as written today would compromise that privacy benefit (though we can have a discussion in spec land about whether we'd want to do that to improve functionality/allow users to explicitly choose their preference).

Today, the warning should exist in all cases where you attempt to invite a user to a chat, and currently it does not for the Start Chat flow.

**Comment by weeman1337** [comment]
I've created a new issue for the homeserver does not exist case: https://github.com/vector-im/element-web/issues/24991
