### ISSUE TITLE
Build failed with: TypeError: Cannot read property 'pipeline' of undefined

### ISSUE THREAD

**Issue by root-add** [vector-im/element-web#24845]
### Steps to reproduce

Hello,

1. Install software listed in https://github.com/vector-im/element-desktop/blob/develop/docs/windows-requirements.md
2. Install latest yarn https://classic.yarnpkg.com/latest.msi
3. Download and extract any of
https://github.com/vector-im/element-desktop/archive/refs/tags/v1.11.25.zip
https://github.com/vector-im/element-desktop/archive/refs/tags/v1.11.23.zip
4. Goto to extracted dir
    cd v1.11.25\element-desktop-1.11.25
5. yarn install
6. yarn run fetch --noverify --cfgdir ""

### Outcome

I expect build will be successful, but in fails with:

> cd C:\Users\Administrator\Downloads\v1.11.25\element-desktop-1.11.25
> yarn install
yarn install v1.22.19
[1/4] Resolving packages...
warning Resolution field "@types/node@16.18.12" is incompatible with requested version "@types/node@^17.0.36"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "@babel/eslint-parser@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "@babel/eslint-plugin@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "eslint-plugin-deprecate@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "eslint-plugin-jest@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "eslint-plugin-jsx-a11y@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "eslint-plugin-react@*".
warning " > eslint-plugin-matrix-org@1.0.0" has unmet peer dependency "eslint-plugin-react-hooks@*".
warning " > eslint-plugin-matrix-org@1.0.0" has incorrect peer dependency "prettier@2.8.0".
[4/4] Building fresh packages...
Done in 403.58s.

> call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.25
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

> yarn run fetch --noverify --cfgdir ""
yarn run v1.22.19
$ yarn run mkdirs && ts-node scripts/fetch-package.ts --noverify --cfgdir element.io.my
$ mkdirp packages deploys
Downloading https://github.com/vector-im/element-web/releases/download/v1.11.25/element-v1.11.25.tar.gz...
TypeError: Cannot read property 'pipeline' of undefined
    at downloadToFile (C:\Users\Administrator\Downloads\v1.11.25\element-desktop-1.11.25\scripts\fetch-package.ts:26:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (C:\Users\Administrator\Downloads\v1.11.25\element-desktop-1.11.25\scripts\fetch-package.ts:160:17)
Failed to download https://github.com/vector-im/element-web/releases/download/v1.11.25/element-v1.11.25.tar.gz TypeError: Cannot read property 'pipeline' of undefined
    at downloadToFile (C:\Users\Administrator\Downloads\v1.11.25\element-desktop-1.11.25\scripts\fetch-package.ts:26:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (C:\Users\Administrator\Downloads\v1.11.25\element-desktop-1.11.25\scripts\fetch-package.ts:160:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Operating system

Windows 2016 fresh installed

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-desktop/blob/develop/docs/windows-requirements.md is outdated, we don't support Node 14 anymore - we tend to use v16/18. You can take our github actions workflows as a functional example.

Your node version seems to lack `stream` promises support - https://nodejs.org/api/stream.html#streams-promises-api was added in v15

**Comment by root-add** [comment]
Thank you.
Node 18 did the trick:

> yarn run fetch --noverify --cfgdir ""
Done in 20.44s.

**Comment by root-add** [comment]
Closed.
