### ISSUE TITLE
Updating the display name starts own key download a ~100x

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24840]
### Steps to reproduce

1. Go to profile settings
2. Open developer console
3. Wait until the console is quiet
4. Enter a new display name
5. Save
6. Look at the console

#### What did you expect?

Not ~100 key downloads of own keys

#### What happened instead?

~100 key downloads of own keys

### Operating system

Ubuntu 22.04.2 LTS

### Browser information

Firefox 111.0 (64-bit)

### URL for webapp

https://develop.element.io/

### Application version

Element version: 77e7bad4f157-react-2344eaab1c53-js-7f2a4c256852 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is a Synapse issue - https://github.com/matrix-org/synapse/issues/9392
