### ISSUE TITLE
Messages remain pinned to bottom of room even after manual deletion from database

### ISSUE THREAD

**Issue by mcgovernl** [vector-im/element-web#24849]
### Steps to reproduce

Not sure how to reproduce this. Unsure why it happened in the first place.

### Outcome

I'm new to element/matrix and I am trying to find out how to properly remove these bugged messages.

![element_screenshot](https://user-images.githubusercontent.com/35819265/225680900-43b32532-0b30-4f67-923a-c033430d0a9d.png)

These two messages continue to stay at the bottom of this room no matter what I seem to do. I tried deleting them in the chat in an effort to get rid of them but realized that doesn't remove them from the chat completely. I even went into the synapse homeserver db and deleted the event to non avail. When I send new messages these two still appear below them and act as if they are pinned to the bottom of the room. 

Is there any way to remove these messages manually. Can I wipe them from local storage? Is that a potential fix?
Thanks in advance

### Operating system

Arch Linux:  5.10.161-1-MANJARO

### Browser information

Desktop App

### URL for webapp

Desktop

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### Homeserver

Synapse v1.79.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Clear cache in Settings > Help & About - this is a Synapse bug

1. messages stuck to bottom = missing remote echo down /sync
2. removing from DB not being reflected in clients is similar, Synapse doesn't inform clients via /sync
