### ISSUE TITLE
Element Call Video Call fails

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#24858]
### Steps to reproduce

1. Enable group calls via element call labs flags
2. Click video call button, pick element call
3. Click join
4. Call UI appears but times out and fails after a few seconds

This is with ED nightly 2023031701

### Application version

ED nightly 2023031701

### Will you send logs?

No

**Comment by robintown** [comment]
Element Web appears to be denying all read_events requests from the widget with "Cannot read state events of this type"

**Comment by Maximexe** [comment]
I also am having this issue - I can no longer connect to Element video call rooms. It just times out at "connecting" and then refuses to connect and the join button re-appears.

**Comment by IceDBorn** [comment]
I'm having this issue too

**Comment by Maximexe** [comment]
It looks like this issue was closed but I still cannot connect to the calls even after updating - any word on resolution? This is my primary communication method.

**Comment by robintown** [comment]
@Maximexe Please open a new issue and send logs, as it's probable that your issue has a cause unrelated to the reporter's here.

**Comment by Maximexe** [comment]
@robintown how would I collect or send logs with this issue?

**Comment by robintown** [comment]
You can do that by clicking on your avatar in the top right corner, then selecting 'Feedback' > 'submit debug logs'
