### ISSUE TITLE
Toggling Message Search on and off multiple times crashes Element Desktop

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-web#24853]
### Steps to reproduce

1. Go to Settings -> Security & Privacy
2. Disable or Enable Message Search
3. Keep doing this multiple times until Element crashes

#### What did you expect?

Element shouldn't crash when toggling Message Search

#### What happened instead?

It crashes.

Terminal:

```
$ element-desktop
/home/debian/.config/Element exists: yes
/home/debian/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Trace/breakpoint trap
```

Systemd log:

```
kernel: traps: element-desktop[18324] trap int3 ip:56160e134d3f sp:7fff19585fe0 error:0 in element-desktop[56160a8af000+785e000]
```

### Operating system

Debian bookworm

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### How did you install the app?

https://element.io/download#linux-details

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by konomikitten** [comment]
This might also be breaking the session data, see #23123 for more details.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/23311
