### ISSUE TITLE
[Desktop] Add ability to hide window on startup

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-web#24851]
### Your use case

It would be nice to be able to have Element desktop automatically hide on startup, so I could have Element both start up automatically and then just stay out of my way by default. In element desktop there have no option to startup as minimized. So, If I add the app in startup folder in windows it always open window when it startup at login.

**Comment by t3chguy** [comment]
We do instruct it to hide on startup using AutoLaunch `isHidden` - https://www.npmjs.com/package/auto-launch#api

**Comment by AnisTaluqdar** [comment]
> @AnisTaluqdar What OS are you using?
> 
> @t3chguy mentions that this should already be working so I assume we expect to be working for macOS, Windows, and some main stream Linux distributions.

Windows 11, How to use for ishidden command in windows 11? I know it how to use in linux.

**Comment by t3chguy** [comment]
@AnisTaluqdar when using the Settings > Preference > Start automatically after system login
 option we specify it to auto-launch which passes `--hidden` as a command line argument.

**Comment by t3chguy** [comment]
> As I am putting menially in windows 11 startup folder so it startup after system login with open window.

Add `--hidden` to your shortcut then

Closing in favour of https://github.com/vector-im/element-web/issues/16437

See `--help` for other command line arguments.
