### ISSUE TITLE
VoIP buttons can vanish entirely after a network failure

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2486]

**Comment by AmandineLP** [comment]
I was trying to call while in unstable connection state (my iphone tried to take over and do tethering, then trying to connect to a wifi and failing etc).

**Comment by richvdh** [comment]
sounds a bit like React got upset. Don't suppose you have any console logs? Think it's going to be hard to do much with this.

**Comment by ara4n** [comment]
I got this earlier too. I lost connection whilst on a voip call (my wifi stack crashed; well done Apple); the call failed; on network coming back, the buttons then mysteriously vanished (although I could accept an inbound call).  Should be easy to reproduce.  I have no logs for it though :/

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
