### ISSUE TITLE
Room (with only myself) content gone

### ISSUE THREAD

**Issue by eyallior** [vector-im/element-web#24865]
### Steps to reproduce

1. I have a room only with myself, I use it to journal for many months.
2. Today I tried to access it from Web app and from Linux app, the room has no content besides this message:
Waiting for users to join Element
Once invited users have joined Element, you will be able to chat and the room will be end-to-end encrypted
@eyallior:matrix.org revoked the invitation for Someone to join the room.

The room was still accessible from my android app.

I could still access room settings, as I am the admin.

Then I changed to public but still nothing changed.

I then changed to space members and had to press "upgrade" - and since then, the room content is gone also from my android app.

This is really bad.

#### What did you expect?
Not losing my content

#### What happened instead?
My content is gone. Luckily I have a recent backup. But I can't trust this app anymore.

### Operating system

Linux, Android

### Browser information

Firefox

### Will you send logs?

Yes

**Comment by eyallior** [comment]
After the upgrade - there's this message:
This room is a continuation of another conversation.
[Click here to see older messages.]

On the android app I can click this link and see old messages, but on the Linux-Firefox web version and on the Linux Element app - not.

**Comment by MadLittleMods** [comment]
@robintown Why `A-3PIDS` here? Typo?

From the follow-up comment, it seems like a problem where a room had a bunch of content, was upgraded, and the new room doesn't point back at the old room to continue reading.

**Comment by t3chguy** [comment]
> URL for webapp
No response

> Application version
No response

@eyallior please don't omit this info, it makes it nigh impossible to chase issues down

**Comment by robintown** [comment]
@MadLittleMods It was a little bit of a hunch, I remembered reviewing some changes to how 3PID users are calculated recently, and I interpreted the follow-up comment as meaning that the 3PID message was still present after the upgrade.

**Comment by t3chguy** [comment]
Closing due to lack of response
