### ISSUE TITLE
Element crash on KDE

### ISSUE THREAD

**Issue by Error504TimeOut** [vector-im/element-web#24867]
### Steps to reproduce

1. Start Element on Arch Linux on KDE (Version 5.27.3, X11) (both the flatpak and non flatpak version have this Problem)
2. Just wait.

[View Log](https://github.com/vector-im/element-web/files/11011704/log.txt)

#### What did you expect?
No crash. I used XFCE for a long time and I did not have this Problem.
#### What happened instead?
It crashes after a seemingly random amount of time. It does not matter if you interact with the application.

### Operating system

Arch Linux (KDE, X11)

### Application version

Version Element: 1.11.25, Version Olm: 3.2.12

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report issues with the community flatpak to its maintainers

**Comment by t3chguy** [comment]
The arch package is also community maintained

**Comment by t3chguy** [comment]
https://github.com/flathub/im.riot.Riot/
