### ISSUE TITLE
Weird CSS on Safari web browser

### ISSUE THREAD

**Issue by voltaire7** [vector-im/element-web#24869]
### Steps to reproduce

Open app.element.io on Safari while connected.

#### What did you expect?
I expected it to be like in Chrome:
<img width="1840" alt="Screenshot 2023-03-19 at 16 49 52" src="https://user-images.githubusercontent.com/83353052/226208138-5e364359-f86d-4e02-9dc5-eff81fc9a0c6.png">

#### What happened instead?
But the 'People' section in the side bar is not displayed properly:
<img width="1840" alt="Screenshot 2023-03-19 at 16 49 56" src="https://user-images.githubusercontent.com/83353052/226208149-eed90d17-bf52-46e1-bb11-5be18fe6130c.png">

### Operating system

macOS

### Browser information

Safari Version 16.3 (18614.4.6.1.6)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### Will you send logs?

No

**Comment by alunturner** [comment]
Hello, thanks for raising an issue.

I've been trying to reproduce it this morning but I'm unable to get anything resembling the images you've attached. 

Please could you confirm if this is consistent (or was a one off/infrequent occurrence)? If you can reproduce it consistently, any extra detail on the steps to reproduce would be helpful.

**Comment by voltaire7** [comment]
I don't know what to tell you... I'm going to app.element.io and I look at the interface and it's just displays incorrectly. Here's a screen recording to prove it:
https://user-images.githubusercontent.com/83353052/226488811-c81f3f6c-d735-40fd-8c8c-571ae1724a18.mov

**Comment by alunturner** [comment]
Thanks very much, the video was very helpful - didn't spot that the whole menu section appears to be there, just shifted too far to the left. I still can't reproduce this locally despite being on MacOS and Safari 16.3. 

The only thing I can think of is if you'd be able to grab a screenshot of the CSS that is applied to the element that is behaving badly (when it is shifted over to the left) we might be able to figure out what's going on then.
