### ISSUE TITLE
Trying to join rooms in KDE Community fails

### ISSUE THREAD

**Issue by warpKaiba** [vector-im/element-web#24868]
### Steps to reproduce

1. Where are you starting? What can you see?

I tried to join the KDE room in the KDE Community space and it failed and gave a "failed to join room" message. I then tried to join the Plasma room and it gave a full "Something went wrong!" dialog that asked me to make this issue. I will submit the debug logs.

*I submitted the debug logs through Element, but I'm not sure if it worked.
*The message on trying to join the room is "Failed to join There was an error joining."

2. What do you click?
Join room on the general KDE room

#### What did you expect?
Join the room

#### What happened instead?
Failed to join the room

### Operating system

Manjaro linux

### Application version

Element version: 1.11.20 Olm version: 3.2.12

### How did you install the app?

manjaro pacman

### Homeserver

nibbana.jp

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please update 1.11.20 is out of date
