### ISSUE TITLE
[ Bug ] Upgraded Encrypted Room. Admin and Members unable to join upgraded room.

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#24871]
### Steps to reproduce

1. Where are you starting? What can you see?
- An encrypted room in a space.
- A fellow admin assigned to the room upgraded the room. And this button now appears:
![image](https://user-images.githubusercontent.com/66582769/226229900-a453dcaf-09a6-4b7d-8ee1-3db5fd0ec11e.png)
- When I click, `The conversation continues here. I get this error message`
![image](https://user-images.githubusercontent.com/66582769/226229982-126220ae-1024-4436-93ad-4f70a34bba72.png)

Note
- I'm the creator of the Space and I created the Room as well. However, I cannot join the room anymore.
- I don't think my fellow admin manually remove me on the room since I didn't get any prompt that got kicked out of the room, and also I still have access to the previous version room's conversation. Also, I'm the only admin of the Space, so I should have complete access to all the rooms. No moderator or other privileged user in the Space role and permission setting as well.

#### What did you expect?
I'm able to join the upgraded room after clicking `The conversation continues here.`

#### What happened instead?
I'm unable to join the upgraded room after clicking `The conversation continues here.`

Note:
I don't think it's possible to generate /rageshake since the room is upgraded and the previous version of the room's message box is not available anymore.

### Operating system

Windows 11

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
The person who upgraded the room had the option to invite you as part of the upgrade. 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/2403652/226845766-e7ac06bd-4098-4076-837c-f45c12b81623.png">

As for being able to join without an invite, that needs to be enabled in Settings.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/2403652/226845869-8a17c554-e219-4e8d-b955-2267112adc50.png">

> I'm the creator of the Space and I created the Room as well.

Matrix has no special permissions for "Creator"

> Also, I'm the only admin of the Space, so I should have complete access to all the rooms.

Matrix Spaces don't have a concept of synced/cascaded access controls or power levels, so being an admin in the Space gives you no special control over its rooms other than being able to control which rooms are shown in the space.

**Comment by 8227846265** [comment]
The person who upgraded the room had the option to invite you as part of the upgrade.
- Why is there even a `Automatically invite members from this room to the new one` on the option? If the admin upgrades a room with members on it. The membership should be inherited without question. If they plan to not to invite the members on the upgraded room. They can kick the members before the upgrade.
- Additionally, this UX invites **do-or-die** setup wherein if the private room has let say 100+ or even more members, and they mistakenly disabled the automatic invite option during upgrade prompt. The admin has to reinvite ALL OF THEM manually by clicking and finding the members in the Space User List. The hardship of reinvitation scales to the number of users of the Space since there's no smart way to efficiently select members to a private room.

Unless of course, the admin make the room public to Space.

Matrix Spaces don't have a concept of synced/cascaded access controls or power levels, so being an admin in the Space gives you no special control over its rooms other than being able to control which rooms are shown in the space.
- I'm the only one allowed to create Room on the Space, since there's no Moderator and no Admin aside from me. Why can a room admin-only upgrade a room inside the Space I created, isn't that essentially overriding the Space Admin ownership of the room created and the ability to create a room (by virtue of upgrade function)?

**Comment by t3chguy** [comment]
I suggest https://github.com/vector-im/element-meta/ for larger Element/Matrix discussions, this repo is about element-web/desktop only. Your queries aren't specific even to Element but to Matrix clients & servers as a whole.
