### ISSUE TITLE
Flaky percy test Room Directory - filtered no results

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24879]
E.g. https://percy.io/dfde73bd/matrix-react-sdk/builds/26058610/changed/1452588982?browser=edge&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1024&widths=516%2C1024%2C1920

This test failed because a spinner was visible in the top right corner:

![image](https://user-images.githubusercontent.com/76812/226553301-b952e639-7647-4190-9733-11d9d1e28b93.png)

**Comment by daniellekirkwood** [comment]
@andybalaam  and I discussed this and it's done.
