### ISSUE TITLE
Creating a subspace doesn't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#24882]
### Steps to reproduce

1. Right click an existing space in the space panel
2. Add a space
3. Enter details
4. Click add

#### What did you expect?

For a space to be created or error shown to me.

#### What happened instead?

Literally nothing.

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023032101 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/8cb8cd4eb1b06832ebc0930d50cebae8fde6b604
