### ISSUE TITLE
Unable to remove contact information

### ISSUE THREAD

**Issue by Curious-r** [vector-im/element-web#24884]
### Steps to reproduce

1. Settings --> General --> Email Addresses --> Remove 

#### What did you expect?
The email is deleted.
#### What happened instead?
Pop-up prompts:
```
Unable to remove contact information
fetch failed: Failed to fetch
```

### Operating system

Windows 11

### Browser information

Microsoft Edge 111.0.1661.44

### URL for webapp

app.element.io

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### Homeserver

curious.host

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The logs do not show the underlying error, please reach out to `curious.host` to ask for the error, it is likely a misconfiguration on their end.
