### ISSUE TITLE
Stickerpicker is broken

### ISSUE THREAD

**Issue by AndrewRyanChama** [vector-im/element-web#24887]
### Steps to reproduce

1. Open the stickerpicker
2. It's blank

#### What did you expect?
Stickerpicker shows up 

#### What happened instead?
blank box
<img width="1043" alt="Screenshot 2023-03-21 at 6 08 39 PM" src="https://user-images.githubusercontent.com/89478935/226775893-4b68d942-b9f8-488a-8909-c18b0626c67b.png">

I tried to 

### Will you send logs?

Yes

**Comment by AndrewRyanChama** [comment]
I tried removing and re-adding with the official thing

Error is: Uncaught Error: creatorUserId is required

**Comment by meson800** [comment]
My homeserver uses a custom stickerpicker and had the same problem. We do the lazy thing and have people manually edit their `m.widgets` account information. Adding in a `creatorUserId` keyvalue pair in two places makes the stickerpicker work again. Only adding it in one place gives the same error.

Example:
```
{
  "type": "m.widgets",
  "content": {
    "stickerpicker": {
      "content": {
        "type": "m.stickerpicker",
        "url": "https://homeserver/stickers/",
        "creatorUserId": "@me:homeserver",
        "name": "Stickerpack"
      },
      "sender": "@me:homeserver",
      "creatorUserId": "@me:homeserver",
      "state_key": "stickerpicker",
      "type": "m.widget",
      "id": "stickerpicker"
    }
  }
}
```
