### ISSUE TITLE
`Modal.createDialog(...)` throws strict TypeScript errors

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24899]
*Spawning from https://github.com/matrix-org/matrix-react-sdk/pull/10405#discussion_r1142916977,*

Our `Modal.createDialog(...)` usage throws strict TypeScript errors when you start touching parts of that code.

ex.
```js
Modal.createDialog(ErrorDialog, {
    title: _t("Upload Failed"),
    description: desc,
});
```

```
Argument of type 'typeof ErrorDialog' is not assignable to parameter of type 'ComponentType'.
```

Another example:
```
Argument of type 'typeof BugReportDialog' is not assignable to parameter of type 'ComponentType'.
```

### Potential solutions

We probably need to fix the Type definitions in [`Modal.createDialog(...)`](https://github.com/matrix-org/matrix-react-sdk/blob/ed88e0cdcee5b85e15dec10bf2c80749ef5d83ef/src/Modal.tsx#L126-L133) to more accurately portray what we're doing. I'm not sure what those changes would look like.

**Comment by t3chguy** [comment]
Targeted by https://github.com/matrix-org/matrix-react-sdk/pull/10387
