### ISSUE TITLE
Fix flaky Percy test due to seek bar on audio player

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24897]
### Steps to reproduce

1. Check audio player's seek bar of [this result](https://percy.io/dfde73bd/matrix-react-sdk/builds/26097295/changed/1454569038?browser=chrome&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=original&width=1920&widths=1024%2C1920) for `File tiles on FilePanel`.

#### What did you expect?

The seek bar should be reset to zero.

#### What happened instead?

It does not reset to zero, while the counter shows `00:00`.

Here is a cropped screenshot of the test. The indicator is rendered on a different position on the seek bar.

![Screenshot from 2023-03-23 04-16-21](https://user-images.githubusercontent.com/3362943/227013014-da6401aa-f776-48bb-9c4f-203462db5e23.png)

### Will you send logs?

No

**Comment by richvdh** [comment]
As I understand it, the root cause of this is https://github.com/vector-im/element-web/issues/24898
