### ISSUE TITLE
Investigate potential memory leak

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24892]
We have reports from Matthew and Travis that their Element Desktops crash when left open for more than a few hours.

We also have reports that our tests are using large amounts of memory.

These may be related, or they may not, but the first at least implies we have a memory problem, probably a memory leak.

Investigate it and fix what you find.

See also https://github.com/vector-im/element-web/issues/22690

**Comment by daniellekirkwood** [comment]
@andybalaam we turned this into an issue, can you add the details and labels needed :) Thanks!

**Comment by t3chguy** [comment]
This looks like https://github.com/vector-im/element-web/issues/21336 or https://github.com/vector-im/element-web/issues/21541

**Comment by NeonMinnen** [comment]
Would love to see this investigated more. RAM usage is absolutely ridiculously high.

**Comment by andybalaam** [comment]
Closing in favour of #21541, which I have moved to Next @dan
