### ISSUE TITLE
Clicking any room, space, person results in "Something went wrong!" popup

### ISSUE THREAD

**Issue by kkatz151** [vector-im/element-web#24909]
### Steps to reproduce

1. Start web browser, firefox, brave, etc
2. login and enter key for a previously working account
3. after viewing https://app.element.io/#/room/..  click on any room, space, or person

note:  settings page can also be viewed and eddited.  it is only opening he said above.

### Operating system

linux

### Browser information

Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/room/

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by kkatz151** [comment]
i cant get to messsage area.  but i can send what is in F12 console.log.  it is saved, but i have a new question.  is there anything in there security wise i need to be concerned with?
i can paste a snipit maybe:
rageshake.ts:73 Switching to room id !y.....JId:conduit.rs at event undefined
rageshake.ts:73 RVS update: !ytAj.....Id:conduit.rs null loading? false joining? false initial? true shouldPeek? true
rageshake.ts:73 newscreen room/#_discord_4496......33760:conduit.rs
rageshake.ts:73 TypeError: t.forEach is not a function
    at DMRoomMap.ts:201:21

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/blob/master/src/utils/DMRoomMap.ts#L201

Looks like your `m.direct` event is invalid.

Could you run `/devtools` > Explore account data > m.direct and possibly share the content, feel free to redact the Matrix IDs

**Comment by kkatz151** [comment]
sure,  but where do i type /devtools

**Comment by t3chguy** [comment]
In any room that you are in, in the box you type messages into

**Comment by t3chguy** [comment]
Well that's problematic

**Comment by t3chguy** [comment]
@kkatz151 can you open your browser console and enter `JSON.stringify(mxMatrixClientPeg.matrixClient.getAccountData("m.direct").getContent(), null, 4)` and paste that in here (again feel free to redact the identifiers)

**Comment by andybalaam** [comment]
Potentially related rageshakes?

https://github.com/matrix-org/element-web-rageshakes/issues/20784
https://github.com/matrix-org/element-web-rageshakes/issues/20785

**Comment by kkatz151** [comment]
Yes I see the  above @andybalaam 
here is paste @t3chguy 

'{\n    "type": "m.direct",\n    "content": {\n        "@wa...irt:matrix.org": [\n            "!Kg...HKW:matrix.org"\n        ],\n        "@cor...ren:tedomum.net": [\n            "!GoC...lO:matrix.org"\n        ],\n        "@al...rx:matrix.org": [\n            "!PeAfb...Dqj:matrix.org"\n        ],\n        "@kal...ot:matrix.org": [\n            "!Po...ncum:matrix.org"\n        ],\n        "@x..b:matrix.org": [\n            "!Rmc...iQ:matrix.org"\n        ],\n        "@gi..a:g..dra.xyz": [\n            "!QvE...RAB:matrix.org"\n        ],\n        "@ay...a:matrix.org": [\n            "!VOoRn...cMf:matrix.org"\n        ],\n        "@mi..e:matrix.org": [\n            "!bk...MtP:matrix.org"\n        ],\n        "@f...6:matrix.org": [\n            "!wwnk...ITj:matrix.org"\n        ],\n        "@mo...11:matrix.org": [\n            "!kDy...BM:matrix.org"\n        ],\n        "@ka...olf:matrix.org": [\n            "!zI...lDvp:matrix.org"\n        ]\n    }\n}'

**Comment by t3chguy** [comment]
Looks like somewhere the `m.direct` content is getting set to the whole event which is worrying

**Comment by kkatz151** [comment]
![Screenshot from 2023-03-23 06-26-29](https://user-images.githubusercontent.com/64765505/227222936-c8398ab0-27e6-48d9-b91a-daffdde38b32.png)
![Screenshot from 2023-03-23 06-26-40](https://user-images.githubusercontent.com/64765505/227223000-1ac9667a-1e22-4837-afdc-34de04dd3573.png)

**Comment by weeman1337** [comment]
@kkatz151 thank you for providing more information.

I still have more questions:
- Is the console output the result of exactly this command: `JSON.stringify(mxMatrixClientPeg.matrixClient.getAccountData("m.direct").getContent(), null, 4)` ? I don't care about the … here but more about the structure.
- Did you update your account data manually? For instance via the API or dev tools?
- Do you use other Matrix clients with your account?

**Comment by kkatz151** [comment]
@weeman1337 
{
    "type": "m.direct",
    "content": {
        "@w.org": [
            "!K.org"
        ],
        "@c.net": [
            "!G.org"
        ],
        "@a.org": [
            "!P.org"
        ],
        "@k.org": [
            "!P.org"
        ],
        "@x.org": [
            "!R.org"
        ],
        "@g.xyz": [
            "!Q.org"
        ],
        "@a.org": [
            "!VO.org"
        ],
        "@m.org": [
            "!b.org"
        ],
        "@f.org": [
            "!w.org"
        ],
        "@m.org": [
            "!k.org"
        ],
        "@k.org": [
            "!z.org"
        ]
    }
}


and yes i WAS, using "Syphon" on android phone.
no i dont recall ever editing my account manually

**Comment by kkatz151** [comment]
@weeman1337  Yes, all fixed.  ty ty.  had trouble with a bit of your instructions on where to place the single quotes, but got it figured.  checked all the rooms, and people and i think its ok, I think some people disappeared.  but its at least workable now

**Comment by weeman1337** [comment]
Then lets close this one by https://github.com/matrix-org/matrix-react-sdk/pull/10436

**Comment by kkatz151** [comment]
agreed  ty all
