### ISSUE TITLE
Refactoring for Quick settings button

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24912]
#### What would you like to do?
Change code for Quick settings button
#### Why would you like to do it?
Less code
#### How would you like to achieve it?
Edit html, css and scripts.

### Additional context

Do you like this view? It with less code.
Yeah, I did not write to get 1-to-1 view I can.
![image](https://user-images.githubusercontent.com/24779886/227365773-d68b0780-73f1-42bf-85d2-1bfad486d420.png)

**Comment by gsouquet** [comment]
Refactors for less code and the same functionality without sacrificing readibility sounds great.

Unfortunately the screenshot above does not look satisfactory. I will close this issue, feel free to work on refactors that bring tangible improvements to the codebase. 
Change in the look and feel can be accepted if they favour a better user experience
