### ISSUE TITLE
Element Desktop shows unread messages after each start

### ISSUE THREAD

**Issue by AlBundy33** [vector-im/element-web#24915]
### Steps to reproduce

Since some days Element shows always the same messages after start.
![image](https://user-images.githubusercontent.com/6294586/227453274-3dbe3d2b-2d37-4894-9b23-dfaa525d27b8.png)

After I read them the notifications are gone as usual but will be shown again on the next start.

I've already tried:
- login and logout
- clear the cache
none of them helped

This is only an issue on the windows app - I don't have this issue on my android devices.

### Operating system

Windows

### Application version

Version von Element: 1.11.25 Version von Olm: 3.2.12

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/24392
