### ISSUE TITLE
Element web flatpak desktop app crashes after a few seconds

### ISSUE THREAD

**Issue by stingray-11** [vector-im/element-web#24926]
### Steps to reproduce

The issue is simply that I open the element desktop app, do nothing, it runs for maybe 10-15 seconds, then crashes.  During that very brief window I can send a quick message (it works normally).  

I did a quick debug and it's exiting with SIGILL (illegal instruction).  I have not dug farther than that.  I am a C++ developer and can collect more details if anyone has suggestions.  I didn't report this for a while as I thought it was an obvious enough issue to be fixed but it must not be a widespread problem.  

This has been happening on my Manjaro system (AMD CPU) for a few months, BOTH the manjaro-packaged and Flatpak versions.  I have another system running EndeavourOS (Intel CPU) which was fine for a while but also started exhibiting this last week.  That system is running the Flatpak.  Both systems are running GNOME.  I have also tried deleting all .config data, sign in/out several times, etc.  

#### What happened instead?

Expect no crash.  Instead it crashes.  

### Operating system

Manjaro, EndeavourOS

### Application version

Element 1.1.25, olm 3.2.12 (Manjaro flatpak)
System electron version is v22.0.3

### How did you install the app?

pacman, Flatpak

### Homeserver

Synapse 1.79.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report crashes with community packages to their maintainers - e.g. https://github.com/flathub/im.riot.Riot/
