### ISSUE TITLE
A11y: Settings headings are not marked up in HTML

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24922]
In all submenu items in the web Settings screen, the headings are not marked up in HTML which makes it difficult for screen readers to navigate 

Example of this issue are highlighted in red:
<img width="525" alt="Screenshot 2023-03-24 at 11 48 38" src="https://user-images.githubusercontent.com/89144281/227513450-b3fcf8af-29ef-4107-a02e-8c09c1c7ede6.png">

**Comment by MadLittleMods** [comment]
What about these A11y issues requires https://github.com/vector-im/element-web/labels/X-Needs-Design? Are the screens/flows changing beyond making the existing content accessible?

**Comment by MadLittleMods** [comment]
@daniellekirkwood Feels like this can be addressed without any design input.

If we want to fix it in the current Element, just update to use some semantic heading elements.

If we want to make sure headings in the Compound design system are accessible, just use semantic heading elements.

**Comment by luixxiul** [comment]
@kerryarchibald I would like to ask you if the issues you referenced to this is to address https://github.com/vector-im/element-web/issues/25227 as well.
