### ISSUE TITLE
A11y: The Quick Settings aria-label is not read by screen readers, leaving the button useless...

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24920]
<img width="159" alt="Screenshot 2023-03-24 at 11 36 28" src="https://user-images.githubusercontent.com/89144281/227511208-3cbe4851-1baa-441e-b442-63b1baf17b2b.png">

The graphic control element shown has an aria-label attribute with a meaningful
alternative text. However, the screen reader does not output anything, which means
that screen reader users do not experience the functionality of the control element.

**Comment by t3chguy** [comment]
Needs more info, what OS, Browser, Screen reader and what navigation mode

![image](https://user-images.githubusercontent.com/2403652/227511879-f88b349d-a4be-4041-9fdf-65cec4c2f8e9.png)

The accessibility tree shows it just fine

**Comment by daniellekirkwood** [comment]
Ok, if this is all we have to do to give an item a label (and that screenshot is it) then I'm happy we close this out :)

**Comment by t3chguy** [comment]
https://user-images.githubusercontent.com/2403652/228554825-260ccb84-db6f-4cad-9540-906f8a78555d.mov

@daniellekirkwood looks to work fine for me, not sure what else can be done, VoiceOver reads it just fine, Firefox shows it just fine in the Accessibility Tree.

**Comment by Morhonda** [comment]
Hi @t3chguy and @daniellekirkwood,

could you please let me know in which version of Element this is fixed in? thanks.

Best wishes,

Moritz

**Comment by daniellekirkwood** [comment]
Thanks for checking!
