### ISSUE TITLE
A11y: Colour contrast

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24933]
There's several examples of the colour contrast in our product not being met. 

@daniellekirkwood Will share screens but this is a holding issue for the design systems team.

**Comment by t3chguy** [comment]
There are a multitude of existing a11y contrast issues that overlap with this one - https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+contrast+label%3AA11y

**Comment by daniellekirkwood** [comment]
Yeah, I will set some time aside this week and gather all the colour feedback here and mark it as an epic. It's then likely we'll move it from this repo to the Design repo

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/14731
https://github.com/vector-im/element-web/issues/14738

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-web/issues/25547 covers the colour pass we'll do. 

This issue will be closed when Danielle has reviewed the open issues related to colour contrast and closed them (if needed) based on the work completed as part of the issue #25547

**Comment by germain-gg** [comment]
@daniellekirkwood I believe we've done some great strides with regards to colour contrast! The colour pass is a best effort, so there are probably a couple of places where contrast might still dip under, but we're fixing those regressions as we find them

**Comment by daniellekirkwood** [comment]
Ok. Thanks, @germain-gg. As we're then tracking those items elsewhere and in different tickets I'll consider this complete and close it out! :D
