### ISSUE TITLE
Percy tests do not capture movement of `collapse` link button on GELS

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24949]
### Steps to reproduce

This might be an upstream issue, but it seems that Percy tests do not capture movement of `collapse` link button on GELS (generic event list summary), introduced with https://github.com/matrix-org/matrix-react-sdk/pull/10211.

Here are the Percy results which seem to have the issue (please check it by toggling `original` and `new`):

- [Expanded GELS and with placeholder of deleted message](https://percy.io/dfde73bd/matrix-react-sdk/builds/26151082/changed/1457474596?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1920&widths=1024%2C1920)
- [Expanded GELS and with emote and placeholder of deleted message](https://percy.io/dfde73bd/matrix-react-sdk/builds/26151082/changed/1457474594?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1920&widths=1024%2C1920)
- [Expanded GELS and messages on IRC layout](https://percy.io/dfde73bd/matrix-react-sdk/builds/26151082/changed/1457474593?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1920&widths=1024%2C1920)
- [Event line with inline start margin on IRC layout](https://percy.io/dfde73bd/matrix-react-sdk/builds/26151082/changed/1457474591?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920)

Those snapshots are built on this PR: https://github.com/matrix-org/matrix-react-sdk/pull/10189

#### What did you expect?

The horizontal row where `collapse` link button exists should be highlighted, as its movement (by https://github.com/matrix-org/matrix-react-sdk/pull/10211) is exactly what caused the snapshot changes.

#### What happened instead?

Percy did not highlight the row. It highlights other parts instead, which I think is quite confusing to those who did not work on the change.

### Will you send logs?

No

**Comment by andybalaam** [comment]
I agree the highlighting is unfortunate, but this is definitely a Percy issue, not Element Web, so closing.
