### ISSUE TITLE
better feedback when we can't share keys with a device

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2494]
If we can't start an Olm session with a device (eg, because we couldn't claim a one-time key), then we write an error to the console and carry on regardless. We should probably offer the user some options (carry on, try again, etc.)

**Comment by poljar** [comment]
While this is talking about showing an error on the sending side, we instead implemented showing more helpful errors on the receiving side via [m.room_key.withheld](https://spec.matrix.org/unstable/client-server-api/#reporting-that-decryption-keys-are-withheld) messages. 

This might have been what we wanted all along, if not, please reopen.
