### ISSUE TITLE
Guest rooms are not displayed over a federation

### ISSUE THREAD

**Issue by EntityinArray** [vector-im/element-web#24955]
### Steps to reproduce

1. Open a guest room from my home server, chat history will be visible, no registration needed
https://chat.isekai.su/#/room/!UNphPwtLKfeEyCgJqZ:isekai.su

2. Open a guest room from app.element.io, it will force you to register
https://app.element.io/#/room/!UNphPwtLKfeEyCgJqZ:isekai.su

#### What did you expect?
Ability to read chat history (and send messages as a guest, but that's a different [issue](https://github.com/vector-im/element-meta/issues/340))

#### What happened instead?
Client forces registration upon you for no reason

### Operating system

Arch Linux

### Browser information

Google Chrome Version 111.0.5563.64 (Official Build) unknown (64-bit)

### URL for webapp

chat.isekai.su

### Application version

element-v1.11.25

### Homeserver

Synapse 1.79.0-1 on isekai.su

### Will you send logs?

No
Sorry, I couldn't get the logs because I'm a guest and can't send ```/rageshake```. Tell me if there is another way to obtain logs

**Comment by t3chguy** [comment]
This is peeking not working over federation, a spec issue rather than an element one. https://github.com/matrix-org/matrix-spec-proposals/pull/2444
