### ISSUE TITLE
Create account link on login page incorrectly appends register to URL

### ISSUE THREAD

**Issue by ThoreKr** [vector-im/element-web#24953]
### Steps to reproduce

1. A synapse server with a single oidc_provider configured as only identity provider.
2. The `.well-known` options for `m.authentication` also point to the same identity provider.
3. Instead of "Continue with <IdP Name> click on "Create account" below.
4. A redirect to the following URL happens: `https://[...]/_matrix/client/r0/login/sso/redirect/register?redirectUrl=https%3A%2F%2Fc[...]%2F`

#### What did you expect?

A redirect to `https://[...]/_matrix/client/r0/login/sso/redirect?redirectUrl=https%3A%2F%2Fc[...]%2F`
note the missing register in the path.

#### What happened instead?
Synapse interprets the register as the idp id and fails at this point: https://github.com/matrix-org/synapse/blob/ce00e57a2acc7c06d0e3bf4c9880dc830c6938ef/synapse/handlers/sso.py#L319

returning 
```
{"errcode":"M_NOT_FOUND","error":"Unknown identity provider"}
```

### Operating system

Any

### Browser information

Any

### URL for webapp

develop.element.io (just as a test if it can be reproduced there)

### Application version

Custom deployed: version: 1.11.25 Olm version: 3.2.12

### Homeserver

Synapse 1.79.0.

### Will you send logs?

No

**Comment by felix-two-tone** [comment]
Having this same issue. We use a OIDC with Keycloak and get the same incorrect redirect.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/8681

**Comment by t3chguy** [comment]
Affects all HSes with an id-less idp (legacy)
