### ISSUE TITLE
Flaky Percy test - `TopUnreadMessagesBar`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24957]
### Steps to reproduce

1. Check this snapshot [`EventTiles on IRC layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26177517/changed/1458253491?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1024&widths=133%2C151%2C267%2C303%2C600%2C1024%2C1920) which was created with https://github.com/matrix-org/matrix-react-sdk/pull/10441

#### What did you expect?

The `TopUnreadMessagesBar` should not be rendered.

#### What happened instead?

It is rendered.

![1](https://user-images.githubusercontent.com/3362943/227789197-db6ff631-d04b-4b58-9411-c9cf6b242d46.png)

### Will you send logs?

No

**Comment by andybalaam** [comment]
I haven't seen this for a while, so assuming it's fixed. Please re-open if not.

**Comment by luixxiul** [comment]
Maybe because it has been hidden by https://github.com/matrix-org/matrix-react-sdk/pull/10453 ...?

**Comment by andybalaam** [comment]
Ah, yes - probably.
