### ISSUE TITLE
Add instruction to run Percy on forked repositories

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24950]
#### What would you like to do?

I would like to have instruction to run Percy on forked repositories, including about what to install, how to set it up, etc.

#### Why would you like to do it?

I wanted to understand how to set up Percy (with my account there) for my own forked repository so that I could test the change there first to ensure that it should not introduce a flaky test to the main repository.

I tried once without whether knowing running it on a local repository would be even possible, but without an introduction I could not proceed more than linking my GitHub repository on my Percy preference (local PR against `develop` branch just skipped Percy test).

**Comment by Johennes** [comment]
Closing this as not planned for the moment. I don't believe we want to support running it on forks and we're reconsidering the value of Percy in general with https://github.com/vector-im/wat-internal/issues/56.
