### ISSUE TITLE
Add information about `@media only percy` to `docs/cypress.md`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24952]
#### What would you like to do?

On `docs/cypress.md` I would like to know about how the media query `@media only percy` works and when it should be used.

It is sure that the media query clearly suggest that it can be used for elements that can change randomly on each test run such as avatar color (`_BaseAvatar.pcss`) in order to avoid flaky test results, but documentation would help here.

#### Why would you like to do it?

I was not sure that several elements change its value like color randomly and it would cause flaky tests. 

#### How would you like to achieve it?

Edit `docs/cypress.md`.

**Comment by gsouquet** [comment]
I think you pretty much captured the essence of why this exists. 

This conversation happened a few days ago in the element-dev public room, here's a link to that conversation so it can be transcribed to a more solid and long term documentation, https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$S0jU3NIFAjLdhEqsFTrW3Jli9jz7zKjkJct5_HBSP5Y?via=matrix.org&via=element.io&via=envs.net

**Comment by t3chguy** [comment]
The canonical documentation for how is https://docs.percy.io/docs/percy-specific-css#percy-css-media-query
