### ISSUE TITLE
A11y: It's not possible to use the keyboard to navigate

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24962]
WCAG Success Criterion: "All functionality of the content is operable through a keyboard
interface without requiring specific timing for individual keystrokes, unless the underlying function requires input that is dependent on the path of the user's movement and not just the endpoints."

The room list, the extra menu on the composer, the emoji selector, settings... for example 

<img width="342" alt="Screenshot 2023-03-27 at 09 18 38" src="https://user-images.githubusercontent.com/89144281/227882897-4f599a38-1df8-43dc-8758-d36bf057812d.png">

**Comment by daniellekirkwood** [comment]
Ooh, cool video. 

The other examples I have are: 
- The emoji picker
- The overflow menu on the composer
- and this (image)

<img width="492" alt="Screenshot 2023-03-27 at 16 44 13" src="https://user-images.githubusercontent.com/89144281/227992869-432db49e-81cc-499f-ad4c-7dd43e064c6c.png">

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/10473 fixes the font slider
