### ISSUE TITLE
UI for setting e2e session rotation frequency

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2496]

**Comment by richvdh** [comment]
blocked by #2495

**Comment by kittykat** [comment]
@richvdh Can you please confirm if this is still an issue?

**Comment by richvdh** [comment]
well, it's still an issue in that there is no UI for controlling how frequently the megolm session should be rotated, either at the room level or at the individual level.

However, I'm not at all convinced that is actually a desirable feature for most users. I think it's probably safe to close this.
