### ISSUE TITLE
A11y: The Creating a room error messages are not linked to the input box in a way that allows screen-readers to see where the error is 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24963]
<img width="510" alt="Screenshot 2023-03-27 at 09 22 57" src="https://user-images.githubusercontent.com/89144281/227883976-78a0f67d-5530-41a0-876a-fbdc1f8b95e6.png">

If no name for creating a room is entered in the input field, an error message appears (example marked in red), which is not linked to the input field. Screen reader users therefore do not find out where they can correct the incorrect input.

This problem exists with other input fields on the checked page

Please ask @daniellekirkwood about timesheeting

**Comment by t3chguy** [comment]
We give it a role of `alert` so screen readers should read it immediately.

> The alert role is used to communicate an important and usually time-sensitive message to the user. When this role is added to an element, the browser will send out an accessible alert event to assistive technology products which can then notify the user.

https://user-images.githubusercontent.com/2403652/229728660-d1d10103-93f0-459c-b38e-7c569efe561d.mov

@daniellekirkwood works fine for me

**Comment by daniellekirkwood** [comment]
We have the same thing for all the input boxes on this screen?

**Comment by t3chguy** [comment]
That's just how our field validation works, its not specific to this screen

**Comment by daniellekirkwood** [comment]
Notes from call: 
* Alert doesn't connect the error message to the field - its just read immediately when it happens
* ARIA polite will wait until the user is done typing and then call out the error message
* It's odd to show an error message when I tab into the field
* And we need to have it connected: ARIA describe by.

**Comment by t3chguy** [comment]
> Alert doesn't connect the error message to the field - its just read immediately when it happens

> And we need to have it connected: ARIA describe by.

Will get this done

> ARIA polite will wait until the user is done typing and then call out the error message

But it doesn't use polite, it uses assertive - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

> Setting role="alert" is equivalent to setting [aria-live="assertive"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) and [aria-atomic="true"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-atomic).

> It's odd to show an error message when I tab into the field

Not sure I follow what you mean by this @daniellekirkwood

**Comment by t3chguy** [comment]
@daniellekirkwood that sounds like a different issue than

> A11y: The Creating a room error messages are not linked to the input box in a way that allows screen-readers to see where the error is

Could you open a new issue for that?
