### ISSUE TITLE
A11y: Checkboxes in the Appearance menu are not assigned a role

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24964]
The checkboxes marked red in the "Appearance" submenu in the "Settings" menu
have not been assigned a role. Screen reader users therefore do not find out what
type of control element it is.

Suggested solution: Assign the attribute role="checkbox" to the checkboxes. 
This problem applies to all checkboxes on the checked page.
<img width="276" alt="Screenshot 2023-03-27 at 09 24 53" src="https://user-images.githubusercontent.com/89144281/227884539-4333cf13-bcea-4c98-a8bc-f3534984a533.png">

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/227887284-be30b0d7-df97-4ae6-a480-94dfa1b442ba.png)

It uses an actual input checkbox, so should not need an explicit role as it uses the semantic element

**Comment by daniellekirkwood** [comment]
Cool, let's close it then
