### ISSUE TITLE
"Jump to date" is forcibly disabled in "Labs".

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#24976]
### Steps to reproduce

n/a

#### What did you expect?
n/a

#### What happened instead?
I updated Synapse to 1.80.0 a while ago.
After updating to 1.11.26 (both web and desktop), I found that "jump to date" is not available. This feature is disabled in "labs" and cannot be manually enabled.
![{A7406C30-7C80-AF9F-C711-DFA243581EE7}](https://user-images.githubusercontent.com/48104960/228371221-26e91bd5-476f-4473-bfba-c0681bd4d1d7.png)

**Strangely, in a specific version (1.11.23), and Synapse version 1.80.0, this feature is still available.**

P.S.: 1.11.23 doesn't have "Jump to Date" option in "Labs", but it can be enabled manually by adding a key `"feature_jump_to_date":true` in DevTools.

In the case where I found the above problem, Synapse's configuration file `homeserver.yaml` already has the following content:
```
experimental_features:
   msc3030_enabled: true
```

`GET /_matrix/client/versions`
```
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0","r0 .6.1","v1.1","v1.2","v1.3","v1.4","v1.5"],"unstable_features":{"org.matrix.label_based_filtering":true, "org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666.mutual_rooms":true,"io.element.e2ee_forced.public":false,"io.element .e2ee_forced.private": false,"io.element.e2ee_forced.trusted_private":false,"org.matrix.msc3026.busy_presence":false,"org.matrix.msc2285.stable":true,"org.matrix.msc3827 .stable":true,"org.matrix.msc2716":false,"org.matrix.msc3440.stable":true,"org.matrix.msc3771":true,"org.matrix.msc3773":false,"fi .mau.msc2815":false,"fi.mau.msc2659":false,"org.matrix.msc3882":true,"org.matrix.msc3881":true,"org.matrix.msc3874":false,"org .matrix.msc3886":true,"org.matrix.msc3912":false,"org.matrix.msc3952_intentional_mentions":false}}
```

**Since I'm just a user, please let me know if I missed something.**

### Operating system

x64 Windows 10

### Browser information

Chromium 102.0.5005.167

### URL for webapp

9ec10a274ec5-react-f5115e047e14-js-c8503b312036

### Application version

Element Desktop 1.11.26

### Homeserver

Synapse 1.80.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Your `GET /_matrix/client/versions` response lacks `msc3030` - I suggest asking Synapse support.
