### ISSUE TITLE
Window is resized when clicking notifications

### ISSUE THREAD

**Issue by ibahnasy** [vector-im/element-web#24971]
### Steps to reproduce

1. Element desktop window is opened in the background as maximized.
2. A new message is received and display a gnome-shell notification.
3. Click on the notification.

#### What did you expect?
It should show the Element desktop windows is it was before it get minimized to sent to the background.

#### What happened instead?
It show the app windows not maximized as it was.

### Operating system

Ubuntu 22.10

### Application version

Element version: 1.11.25 Olm version: 3.2.12

### How did you install the app?

APT repository

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/3292
