### ISSUE TITLE
Win64 version can't even do initial launch properly?!

### ISSUE THREAD

**Issue by MrPeteH** [vector-im/element-web#24980]
### Steps to reproduce

1. Where are you starting? What can you see?
* I used element.io/get-started to download and install the Win64 desktop app
* On first launch, I get an error: Failed to start // Your Element is misconfigured // Unexpected error resolving homeserver configuration [Go to element.io](https://element.io/)
* That's pretty discouraging to say the least
* See below for attempts made to work around. At this point, I'm stuck.

2. What do you click?
(Nothing to click other than the offer to return to the main website. That's kind of... silly?)

3. More steps…

#### What did you expect?
An app that launches and gives me... something
#### What happened instead?
Dead app.

#### Workarounds attempted etc
* I searched for other reports...
  * Some suspect people are installing a browser-based version. NO
  * Some think it might be related to browser. I closed browser. Same exact result.
* I ran wireshark to see if I could learn anything. Nothing obvious. In fact I don't see anything (obviously) related to element or matrix.

Of course, I'm a noob to this software and network. 

### Operating system

Win10, current

### Application version

N/A - can't use app

### How did you install the app?

https://element.io/get-started

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
That error comes up if it can't reach the configured homeserver, by default that is matrix.org - do you have any net filters or proxies in place?

**Comment by MrPeteH** [comment]
BLEAH. I'll do my best to make this a helpful report, given the circumstances:
* No net filters or proxies
* Thanks for the Chromium // ctrl-shift-i !!!
   * I could see the error in the console. Nice.
   * Unfortunately, I failed to copy;/paste it here before taking one more step
   * What I remember: a null reference. I suspect the lack of any config info is the problem
   * I DID capture the wireshark packet trace. Probably useless...

NOTE that up until now, I've opened and closed the app several times, checked in my (SysInternals) Process Explorer and saw that there are no Elements-related processes when closed... and the symptoms have been very consistent.

* I then did a ctrl-R refresh
* Hiccup hiccup... and the app is working! SO... let's try to replicate.

REPLICATION ATTEMPT 1
* Closed app, did standard uninstall. Deleted all from %APPDATA%/Element. Reinstalled. Works fine.
* HOWEVER, on attempting to close (without touching the app. Just open and close.) The spinny window remained, and five processes remained although no other UI visible. Killed all visible processes. The spinner remained until I closed it from the bar??! **( I wonder what that UI spinner process is ;) )**

REPLICATION ATTEMPT 2
* Probably because the close didn't work... **the app does NOT show up as an uninstallable app!** 
* Let's clean up more completely.
  * Deleted %APPDATA%/Element
  * Deleted %APPDATA%/Local/Element
  * Searched registry, found nothing useful
  * Found nothing in AutoRuns
  * (I'm probably missing something...)
  * (Will reboot to ensure a clean environment. TIme to wrap up this comment.)

**Comment by t3chguy** [comment]
> I've opened and closed the app several times

By default X closes the app to tray, right click Quit actually closes it.

If merely Ctrl + R (Refresh) fixed it that implies the app was launched without internet connectivity (causing an unable to reach homeserver error)

> Found nothing in AutoRuns

We don't autolaunch unless you opt into it

If it happens again please do shout.

**Comment by MrPeteH** [comment]
1) There was no right-click-quit option
2) "If merely Ctrl + R (Refresh) fixed it that implies the app was launched without internet connectivity (causing an unable to reach homeserver error)"

* That would be a bit strange, since the computer's been running for quite some time. All other apps worked fine on the internet.
* SO: how can an app be "launched without internet connectivity" and then seconds later, it HAS internet connectivity?

**Comment by MrPeteH** [comment]
It wasn't functioning. ctrl-shift-i worked. But right click didn't do anything. 
Of course now it is all quite happy.

I get it... unrepeatable symptoms are more than a little difficult to debug. when i get a few more round tuits, I'll see if I can replicate cleanly...

(TMI: My worst case was on the first digital phone system long ago... we had a bug that hit (literally) about 2 per million calls. I was astounded that a room full of operators noticed. Then again, at 4 seconds per call and 2 dozen operators, it was happening ~daily LOL)

**Comment by wioxjk** [comment]
Same problem here. I have not been able to get it to work on three separate Windows installations. 
I completely reinstalled Windows today for other reasons, and the first application I tried to install was element - and it does not work.
How can I convince my family to continue to use element if they are constantly put up with this?

**Comment by MrPeteH** [comment]
@wioxjk -- 
Please open the app and then do the following, carefully: (DO THIS BEFORE FURTHER ATTEMPTS TO 'FIX' as this is not easy to reproduce!)
- press ctrl-shift-i -- this should open a dev/diagnostic console. BE PATIENT, it could take several seconds!
- Click on the "Console" tab at the top (on mine it's the second tab)
- That should bring up a log with a lot of information
- right click in the log area, choose "save as" and save the log as a file somewhere you can get it (probably desktop)
- should be save to share the log here. it may well explain what's going on
