### ISSUE TITLE
Stop to break a formatting for SDK styles in builds and generate 6.

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24997]
### Your use case

Your builds of Element Web with destroyed formatting for CSS. You need to stop that. You generate 6 style files about 800 KBs. That you deletes spaces and line-breaks from style does not help you. You try to save KBs when Element consumes hundreds MBs of RAM and have memory leaks inside.

**Comment by gsouquet** [comment]
The build system also yields a sourcemap to be able to debug and view the code unminified. I largely agree with you regarding the size of the CSS files and efforts are put in that direction with vector-im/compound, however not a single issue will solve this issue.

I will close this issue as "not planned", but would be more than happy to re-open it if there are actionable improvements suggested with some reasoning

**Comment by t3chguy** [comment]
Minification is an industry standard technique.

**Comment by JeanPaulLucien** [comment]
> Minification is an industry standard technique.

W3C did not say that.

**Comment by t3chguy** [comment]
https://developers.google.com/speed/docs/insights/MinifyResources
https://web.dev/optimizing-content-efficiency-optimize-encoding-and-transfer/#minification-preprocessing--context-specific-optimizations
