### ISSUE TITLE
Messages not loading

### ISSUE THREAD

**Issue by AlexandraGhi** [vector-im/element-web#25000]
### Steps to reproduce

1. Where are you starting? What can you see?
I send messages in rooms or DM but they do not load and i can't read others messages (only on my phone)
The following message is appearing : Open another device to load encrypted messages
This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.
3. What do you click?
-
5. More steps…
-

#### What did you expect?
My messages to be sent and read others messages

#### What happened instead?
"Open another device to load encrypted messages
This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up."

### Operating system

Windows 

### Application version

Element version: 1.11.26 Olm version: 3.2.12

### How did you install the app?

From the website

### Homeserver

Element server

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
Looks similar to https://github.com/vector-im/element-web/issues/20434 . I think we can probably close this one and keep that one open.
