### ISSUE TITLE
invalid lockfile in desktop release

### ISSUE THREAD

**Issue by selfisekai** [vector-im/element-web#25008]
### Steps to reproduce

run `yarn install --frozen-lockfile`

#### What did you expect?
successful install

#### What happened instead?
```
>>> element-desktop: Fetch element-desktop dependencies
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/node@16.18.12" is incompatible with requested version "@types/node@^17.0.36"
warning asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
warning electron-builder@24.0.0: signing bug when using entitlements
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

### Operating system

Alpine Linux edge

### Application version

1.11.27

### How did you install the app?

source code from https://github.com/vector-im/element-desktop/archive/refs/tags/v1.11.27.tar.gz

### Homeserver

n/a

### Will you send logs?

No

**Comment by andybalaam** [comment]
Hopefully fixed by https://github.com/vector-im/element-desktop/commit/266fc707b0d843d1b5f8e310da88a312e40e9ee9 - running builds now

**Comment by andybalaam** [comment]
Confirmed that I can successfully run `yarn install --frozen-lockfile` in the unzipped tarball from https://github.com/vector-im/element-desktop/archive/refs/tags/v1.11.28.tar.gz so I think this is fixed. Please re-open if not.

**Comment by selfisekai** [comment]
confirmed, works correctly. I think it's worth to also add tests for this or make sure that `yarn.lock` is also committed in the release commit

**Comment by andybalaam** [comment]
> confirmed, works correctly. I think it's worth to also add tests for this or make sure that `yarn.lock` is also committed in the release commit

Absolutely, we plan to check this as part of the release process, so it can never happen again.
