### ISSUE TITLE
Timestamps are wrong in Firefox 78 ESR

### ISSUE THREAD

**Issue by TurtleWilly** [vector-im/element-web#25006]
### Steps to reproduce

The message timestamps (aka the time shown in the small bubbles in front of any messages) in the rooms seem to be shown in UTC only since upgrading to the latest version of element-web to 1.11.26 for the security/CVS reasons. I was using a somewhat older version before which didn't show this problem.

This problem only seems to happen when using _Firefox_ 78 ESR. Using an older _Ungoogled Chrome_ 87.0.4280.141 timestamps are correct, so the problem seems to be specific/ limited to Firefox.

#### What did you expect?

Timestamps of the messages are shown in my local browser timezone (for me it's Central European Summertime currently, so UTC+2h)

#### What happened instead?

Timestamps are 2 hours off, and seem to be shown in UTC.

### Operating system

Mac OS X

### Browser information

Firefox 78.15.0esr (latest update possible for the machine. Cannot be updated further. 😢)

### URL for webapp

localhost hosted via Apache 2.x

### Application version

Element version: 1.11.26, Olm version: 3.2.12

### Homeserver

Synapse, version unknown (I'm only a user on the server).

### Will you send logs?

No

**Comment by t3chguy** [comment]
Can you try to reproduce in a fresh firefox profile? Do you have resist fingerprinting on? This feature specifically overrides timezones with UTC

**Comment by TurtleWilly** [comment]
@t3chguy "Resist fingerprinting" is the cause. 😧 I recently enabled that. Seemed to cause problems with the default avatars too (but canvas stuff can be whitelisted for specific sites). Thanks for quick and correct hint and sorry for the bug report noise.👍
