### ISSUE TITLE
People search returns non-existent users

### ISSUE THREAD

**Issue by Wodann** [vector-im/element-web#25027]
### Steps to reproduce

1. In the sidebar, next to the `people` drop-down, click the `+` symbol 
2. Start typing a username: `@nonexistentuser101:matri`

#### What did you expect?
The people search should only propose existing accounts

#### What happened instead?
Non-existent accounts are recommended and you're allowed to start a direct chat with it.

![image](https://user-images.githubusercontent.com/6917585/229651713-821cef92-70cf-49bd-9610-4cc67183318b.png)

### Operating system

Windows

### How did you install the app?

Element version: 1.11.28 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Due to privacy settings on certain homeservers you are unable to tell whether a user exists, if you think this should be changed I suggest an issue in https://github.com/matrix-org/matrix-spec
