### ISSUE TITLE
Permalink creation with custom base URL is wrong

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25039]
### Steps to reproduce

1. Set a custom URL in `permalink_prefix` in `config.json`, e.g. `https://example.com`
2. Complete a room in message composer
3. Look at the message

Should also be checked in other places where a permalink is generated.

#### What did you expect?

Permalink with pill

#### What happened instead?

Room alias is displayed. Link is wrong including `/room`. Means the parser does not recognise the room

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Link is wrong including /room.

This is right, the docs say pointing at an Element Web deployment, not a matrix.to one, see config.md

> permalink_prefix: An optional URL pointing to an Element Web deployment. For example, https://app.element.io. This will change all permalinks (via the "Share" menus) to point at the Element Web deployment rather than matrix.to.

**Comment by weeman1337** [comment]
This is than as invalid as https://github.com/vector-im/element-web/issues/25038

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/23960
