### ISSUE TITLE
Apply Cypress Testing Library to the existing E2E tests

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25033]
https://github.com/matrix-org/matrix-react-sdk/pull/10446 implemented [Cypress Testing Library](https://testing-library.com/docs/cypress-testing-library/intro/) to align Jest tests and Cypress tests in terms of using Test Library (https://github.com/vector-im/element-web/issues/24906#issue-1637460194), and I think Cypress Testing Library should be applied to not only a new test but also the existing tests.

- Here is the list of commands provided by the library: https://github.com/testing-library/cypress-testing-library/blob/next/cypress/integration/find.spec.js

Here is a list of the current Cypress E2E tests.

- `analytics-toast.ts` [10718](https://github.com/matrix-org/matrix-react-sdk/pull/10718)
- [x] `audio-player.spec.ts`: [10537](https://github.com/matrix-org/matrix-react-sdk/pull/10537)
- [x] `composer.spec.ts`: [10511](https://github.com/matrix-org/matrix-react-sdk/pull/10511) [10538](https://github.com/matrix-org/matrix-react-sdk/pull/10538)
- [x] `consent.spec.ts`: [10514](https://github.com/matrix-org/matrix-react-sdk/pull/10514)
- [x] `create-room.spec.ts` [10542](https://github.com/matrix-org/matrix-react-sdk/pull/10542)
- [x] `crypto.spec.ts`: [10512](https://github.com/matrix-org/matrix-react-sdk/pull/10512)
- [x] `decryption-failure.spec.ts`: [10513](https://github.com/matrix-org/matrix-react-sdk/pull/10513) [10541](https://github.com/matrix-org/matrix-react-sdk/pull/10541)
- [x] `device-management.spec.ts` [10585](https://github.com/matrix-org/matrix-react-sdk/pull/10585)
- [x] `editing.spec.ts` [10543](https://github.com/matrix-org/matrix-react-sdk/pull/10543)
- [x] `events.spec.ts` [10590](https://github.com/matrix-org/matrix-react-sdk/pull/10590)
- [x] `file-panel.spec.ts` [10574](https://github.com/matrix-org/matrix-react-sdk/pull/10574)
- [x] `get-openid-token.spec.ts` [10586](https://github.com/matrix-org/matrix-react-sdk/pull/10586)
- `hidden-rr-migration.spec.ts`
- [x] `kick.spec.ts` [10587](https://github.com/matrix-org/matrix-react-sdk/pull/10587)
- `layout.spec.ts`
- [x] `lazy-loading.spec.ts` [10591](https://github.com/matrix-org/matrix-react-sdk/pull/10591)
- [x] `location.spec.ts` [10612](https://github.com/matrix-org/matrix-react-sdk/pull/10612)
- [x] `login.spec.ts` [10597](https://github.com/matrix-org/matrix-react-sdk/pull/10597)
- [x] `one-to-one-chat.spec.ts` [10572](https://github.com/matrix-org/matrix-react-sdk/pull/10572)
- `permalinks.spec.ts`
- [x] `pills-click-in-app.spec.ts` [10582](https://github.com/matrix-org/matrix-react-sdk/pull/10582)
- [x] `pollHistory.spec.ts` [10611](https://github.com/matrix-org/matrix-react-sdk/pull/10611)
- [x] `polls.spec.ts` [10609](https://github.com/matrix-org/matrix-react-sdk/pull/10609)
- [x] `read_events.spec.ts` [10719](https://github.com/matrix-org/matrix-react-sdk/pull/10719)
- [x] `register.spec.ts` [10566](https://github.com/matrix-org/matrix-react-sdk/pull/10566)
- [x] `right-panel.spec.ts` [10539](https://github.com/matrix-org/matrix-react-sdk/pull/10539)
- [x] `room-directory.spec.ts` [10596](https://github.com/matrix-org/matrix-react-sdk/pull/10596)
- [x] `room.spec.ts` [10608](https://github.com/matrix-org/matrix-react-sdk/pull/10608)
- [x] `send_event.spec.ts` [10613](https://github.com/matrix-org/matrix-react-sdk/pull/10613)
- [x] `sliding-sync.ts` [10618](https://github.com/matrix-org/matrix-react-sdk/pull/10618)
- [x] `spaces.spec.ts` [10620](https://github.com/matrix-org/matrix-react-sdk/pull/10620)
- [x] `spotlight.spec.ts ` [10621](https://github.com/matrix-org/matrix-react-sdk/pull/10621)
- [x] `stickers.spec.ts` [10622](https://github.com/matrix-org/matrix-react-sdk/pull/10622)
- [x] `threads.spec.ts` [10680](https://github.com/matrix-org/matrix-react-sdk/pull/10680)
- [ ] `timeline.spec.ts` [10540](https://github.com/matrix-org/matrix-react-sdk/pull/10540) (partial) [10721](https://github.com/matrix-org/matrix-react-sdk/pull/10721)
- `update.spec.ts`
- [x] `user-menu.spec.ts` [10578](https://github.com/matrix-org/matrix-react-sdk/pull/10578)
- [x] `user-onboarding-new.ts` [10728](https://github.com/matrix-org/matrix-react-sdk/pull/10728)
- [x] `user-onboarding-old.ts` [10728](https://github.com/matrix-org/matrix-react-sdk/pull/10728)
- [x] `user-view.spec.ts` [10577](https://github.com/matrix-org/matrix-react-sdk/pull/10577)
- `widget-pip-close.spec.ts`
- [x] Files inside `support/` directory [10619](https://github.com/matrix-org/matrix-react-sdk/pull/10619)

Please note that some of them do not require Cypress Testing Library, as they do not emulate interactions by users.

**Comment by weeman1337** [comment]
@luixxiul Thanks for writing the list about what to migrate. I would suggest that you pause your work on this issue for a few days until a decision on convenience functions has been made.

**Comment by luixxiul** [comment]
I understood. Fortunately it looks fairly easy to replace the lines of the existing PRs with regex in any case :-)

**Comment by luixxiul** [comment]
Note: anchor link has the `link` role, so `cy.findByRole("link", { name: "…" }).click()` should find the link and click it.
