### ISSUE TITLE
Thread view not showing latest response

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#25035]
### Steps to reproduce

1. respond to long thread from another client
2. open web/desktop client
3. see your own response to a thread in the timeline
4. click it
5. confusion

#### What did you expect?

To see my response at the bottom, where other clients show it

#### What happened instead?

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/2403652/230020524-9d3be6e8-0450-4cda-b20b-f564f96ae0d6.png">

### Application version

2023033101

### Will you send logs?

No

**Comment by andybalaam** [comment]
Message is missing, so labelling as Major, but if it turns up again soon, maybe it's Minor?

**Comment by t3chguy** [comment]
Still isn't there hours later

**Comment by weeman1337** [comment]
Upgrade to occasional because Guillaume found it and I did this morning.

**Comment by heftig** [comment]
I believe I also encountered this: I responded to a thread two times. I noticed my earlier response was missing, and after reloading Element my second response had vanished as well.

**Comment by leonardehrenfried** [comment]
I can confirm that I'm also seeing this. So far it seems to only affect my own messages in the very latest thread in a room.

**Comment by t3chguy** [comment]
@leonardehrenfried saying "me too" only helps if you include the version you're on or send logs

**Comment by leonardehrenfried** [comment]
Sorry, that was a bit stupid of me @t3chguy. I've submitted logs now and the thread in question is https://matrix.to/#/!oXNNoHKzbaSOlFzLEt:gitter.im/$c--M-1av-j4KhMpEYvT5yLIMZDWOdA9b_pfor-8R7UA?via=gitter.im&via=matrix.org&via=mafiasi.de

**Comment by t3chguy** [comment]
@leonardehrenfried perfect thanks, I believe this issue may be fixed on develop which you can try on develop.element.io or it'll be in the release on the 8th of August

**Comment by leonardehrenfried** [comment]
Thanks. I did take a look and develop indeed solves this problem!

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3618
