### ISSUE TITLE
Permalink parsing for custom permalink base URL does not work

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25038]
### Steps to reproduce

1. Set `permalink_prefix` to some custom URL like for instance `https://example.com`
2. Post a permalink into a room (e.g. `https://example.com/#/@fritz:example.com`
3. Look at the message in the room

#### What did you expect?

Permalink pill

#### What happened instead?

Only plain permalink visible

### Will you send logs?

No

**Comment by t3chguy** [comment]
`permalink_prefix` is for Element Web style URLs, not matrix.to ones. `https://example.com/#/@fritz:example.com` is not a valid EW URL fragment

Also you are expecting it to do something it isn't designed to, see config.md, it doesn't say anything about changing parsing

> permalink_prefix: An optional URL pointing to an Element Web deployment. For example, https://app.element.io. This will change all permalinks (via the "Share" menus) to point at the Element Web deployment rather than matrix.to.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/23960
