### ISSUE TITLE
Confirm Percy snapshots for `audio-player.spec.ts`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25055]
https://github.com/matrix-org/matrix-react-sdk/pull/10441 has added E2E tests of the audio player (`audio-player.spec.ts`). The test includes Percy snapshots to check a visual regression of `mx_EventTile_last` on which the player is rendered, but since the repository has run out of the quota, the PR was integrated without checking whether Percy would take snapshots as expected. We should check it once the quota is restored later this month.

ref: https://github.com/vector-im/element-web/issues/24747 and https://github.com/vector-im/element-web/issues/22542

**Comment by weeman1337** [comment]
You can have a look at a recent build: https://percy.io/dfde73bd/matrix-react-sdk/builds/26747313

Looks like seek bars are not there for any of them (searched for „audio“).

I would still close this issue. The purpose of Percy snapshots is to be aware of the changes. That can also mean the current state may probably not the correct one.

**Comment by luixxiul** [comment]
> Looks like seek bars are not there for any of them

The seek bars have been hidden intentionally due to https://github.com/vector-im/element-web/issues/24898 ([here](https://github.com/matrix-org/matrix-react-sdk/blob/1efa82917a0cf581db5bb30f202e7c3efde92f00/cypress/e2e/audio-player/audio-player.spec.ts#L28) is a comment on the test). 

The intention of the issue was to add a reminder to check the snapshot, since the PR has been merged without confirming whether snapshots of the `mx_EventTile_last` were properly captured. [This link](https://percy.io/dfde73bd/matrix-react-sdk/builds/26747313/search?searchParam=audio%20player) lists them, and it seems they are captured as expected :+1:
