### ISSUE TITLE
logged out after running out of diskpace

### ISSUE THREAD

**Issue by Wieter** [vector-im/element-web#25052]
### Steps to reproduce

ran out of disk space, the app logged out and a popup requesting to submit log data.
for submitting log data, this report had to be opened.

### Outcome

N/A

### Operating system

MacOS

### Will you send logs?

Yes

**Comment by Wieter** [comment]
Failed to send logs: No connected database

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/18423
