### ISSUE TITLE
Escape doesn't exit Notifications window after selecting a radio button

### ISSUE THREAD

**Issue by kenwuuu** [vector-im/element-web#25051]
### Steps to reproduce

1. Open Notifications settings
2. Change a radio button, I selected Noisy for "Messages containing keywords"
3. Press escape

#### What did you expect?
Close settings

#### What happened instead?
Settings remained open. No change

### Operating system
Mac

### Application version
Element version: 1.11.28 Olm version: 3.2.12

### How did you install the app?
https://element.io/download

### Homeserver
matrix.org

### Will you send logs?
Sent. Attached this issue URL in it

**Comment by t3chguy** [comment]
Blocking this on the GYU project which changes this settings tab quite significantly. The issue here is after changing the radio options they all get disabled as it persists your change and this sends your focus away from where it was

**Comment by t3chguy** [comment]
This is fixed by @justjanne's GYU Notification labs
