### ISSUE TITLE
Login screen broken when using more than one SSO provider

### ISSUE THREAD

**Issue by jacotec** [vector-im/element-web#25056]
### Steps to reproduce

1. Have two SSO providers configured in Matrix Synapse
2. Open Element-Web, click on "Login"
3. The two SSO buttons are malformed and without any text

![image](https://user-images.githubusercontent.com/3321655/230383697-08da3b42-d890-484f-a2c9-2aa3f9952207.png)

This is how it looks correct with only one provider configured:

![image](https://user-images.githubusercontent.com/3321655/230384046-0ed0fa05-7bb3-4fbd-ae47-c1b2ac75f069.png)

#### What did you expect?

Having two SSO buttons with their name in, one below the other

#### What happened instead?

Two empty buttons without text side by side

### Operating system

N/A

### Browser information

All browsers

### URL for webapp

1.11.28

### Application version

Version von Messenger: 1.11.28 Version von Olm: 3.2.12

### Homeserver

Synapse 1.80.0

### Will you send logs?

No

**Comment by jacotec** [comment]
Any advice for a quick patch (if possible) is apprecited as I need to implement a second SSO provider.

**Comment by t3chguy** [comment]
I suggest looking at the data the server sends, https://spec.matrix.org/v1.6/client-server-api/#client-login-via-sso - you should be including an `icon` as per the spec

**Comment by jacotec** [comment]
@t3chguy Thanks, but that leaves me a bit helpless. At which point do I need to add this icon or brand?

In Keycloak? In the synapse config?

**Comment by t3chguy** [comment]
Element is a Matrix client, so it only talks to your Matrix server, I suggest seeking help from Synapse if that is the server software which you are using. 

```json
 ~  curl https://matrix.org/_matrix/client/r0/login --silent | jq .                                                                               1272ms  Thu  6 Apr 14:04:33 2023
{
  "flows": [
    {
      "type": "m.login.sso",
      "identity_providers": [
        {
          "id": "oidc-github",
          "name": "GitHub",
          "icon": "mxc://matrix.org/sVesTtrFDTpXRbYfpahuJsKP",
          "brand": "github"
        },
        {
          "id": "oidc-google",
          "name": "Google",
          "icon": "mxc://matrix.org/ZlnaaZNPxtUuQemvgQzlOlkz",
          "brand": "google"
        },
        {
          "id": "oidc-gitlab",
          "name": "GitLab",
          "icon": "mxc://matrix.org/MCVOEmFgVieKFshPxmnejWOq",
          "brand": "gitlab"
        },
        {
          "id": "oidc-facebook",
          "name": "Facebook",
          "icon": "mxc://matrix.org/nsyeLIgzxazZmJadflMAsAWG",
          "brand": "facebook"
        },
        {
          "id": "oidc-apple",
          "name": "Apple",
          "icon": "mxc://matrix.org/QQKNSOdLiMHtJhzeAObmkFiU",
          "brand": "apple"
        }
      ]
    },
    {
      "type": "m.login.token"
    },
    {
      "type": "m.login.password"
    },
    {
      "type": "m.login.application_service"
    }
  ]
}
```

This is what matrix.org's login flows look like, I suggest sharing yours

**Comment by jacotec** [comment]
Ah, I understand. With more than one provider, It uses buttons with Icons instead of the text. And the icons must be provided from the server.

That helps, thank you @t3chguy !

**Comment by t3chguy** [comment]
Yeah the given name is only used in tooltip for >1 provider

![image](https://user-images.githubusercontent.com/2403652/230395687-160cd995-78df-456e-9d0e-6bdb2bae0bfd.png)
