### ISSUE TITLE
Joining from public room list sends two join requests

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25054]
### Steps to reproduce

1. Click on the + next to the room list
2. Choose „Explore public rooms“
3. Search for a room that can be joined directly (with a „Join“ button)
4. Open the browser network tab
5. Filter by „join“
6. Click „Join“

#### What did you expect?

One join request

#### What happened instead?

Two join requests

### Operating system

Ubuntu 22.04.2 LTS

### Browser information

Firefox 112.0

### URL for webapp

https://app.element.io/

### Application version

Version von Element: 1.11.27 Version von Olm: 3.2.12

### Will you send logs?

No

PSB-304

**Comment by t3chguy** [comment]
Is this not just CORS pre-flight? Are they both POST requests or is there a HEAD?

**Comment by weeman1337** [comment]
> Is this not just CORS pre-flight? Are they both POST requests or is there a HEAD?

Both POST requests:

![image](https://user-images.githubusercontent.com/6216686/230325316-46ecf95f-8fa4-49e9-8247-6922691772bc.png)
