### ISSUE TITLE
cannot add direct messages to a space

### ISSUE THREAD

**Issue by rcurtin** [vector-im/element-web#25064]
I think this is exactly the same as the solved issue #16704, so I think there has been a regression.

I use a personal Matrix server with Element installed via the wonderful [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) project.

I have many bridges to other services (WhatsApp, Slack, Facebook Messenger, etc.) and I like to organize individual chats including direct messages into spaces, otherwise there are just too many to keep track of.

Up until maybe a month ago I was able to easily add direct messages to a space from the space home view ("Add existing rooms"); however, now, I can't add direct messages by searching or even pasting the internal room ID; the dialog reports "No results".

Please let me know if there is a workaround or something I can do locally to fix the problem---without this functionality it makes it very hard for me to organize/separate my chats.  Thanks!

**Comment by t3chguy** [comment]
@rcurtin you can only add them to private/invite only spaces, check your space settings

**Comment by rcurtin** [comment]
Thank you!  I did not realize that was the issue.  Sorry for the noise.
