### ISSUE TITLE
Can't receive verification code for a second phone number

### ISSUE THREAD

**Issue by imrehg** [vector-im/element-web#25062]
### Steps to reproduce

1. Started in the main view.
2. Clicked my profile picture > All Settings > General > Phone numbers
3. Filled in a phone number
4. Clicked "Add"

I already have one phone number verified, wanted to do a second one. (Happy to share the country codes for either if that is likely affecting things).

#### What did you expect?

Receiving a verification code and verifying my phone number

#### What happened instead?

The fields for entering a verification code appeared for a split second, and then resulted in the following upstream server 500 error report:

<img width="743" alt="Screenshot 2023-04-07 at 13 41 25" src="https://user-images.githubusercontent.com/38863/230549292-dd876d03-f196-49a8-9608-802a99e9bb76.png">

### Operating system

macOS

### Browser information

Firefox 111.0.1 (64-bit)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.27 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
matrix.org disabled MSISDN support.
