### ISSUE TITLE
Remove the "Reaction previews" Labs flags

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25083]
We have 2 labs flags for message previews. They appear to be stable, so let's take them out of Labs!

<img width="736" alt="Screenshot 2023-04-11 at 19 54 36" src="https://user-images.githubusercontent.com/89144281/231261535-bbac130c-be1d-4689-b7ca-d6d21fd19353.png">

Users do not need to be able to toggle these, we should show it for everyone
We should update the copy so it's clear what's an emoji message event and whats a reaction event (see comments)

We need to: 
- [x] Understand why they're in Labs
- [x] Check with other teams if there's a reason for them to stay in Labs
- [x] Understand with the design team where these settings should live (if anywhere, see [here](https://docs.google.com/document/d/1ryZjVuYBSfsu4e6fqYHIC9hJhY-aEWukcWMig1ewRA4/edit#) )
- [ ] Do the task...

**Comment by daniellekirkwood** [comment]
@amshakal @VolkerJunginger 

As per your document discussing what shows up in a message preview and what doesn't... Should these toggles exist for users, or when we remove them from Labs should we default them to on for everyone in both cases? (If we do move the toggle, where should we move it to?)

Secondly, right now we don't show the difference between an emoji in the timeline and a reaction in the timeline. How are y'all showing that on Element X?

**Comment by daniellekirkwood** [comment]
@VolkerJunginger : I think the scope of this issue is to either show reactions or not show reactions, regardless of whether the reaction was on the last message in the room or not. 

We do want to update the preview text to show: 
* You reacted [emoji] to [message] 
* [user] reacted [emoji] to [message]

@weeman1337 is it straightforward to add "[message]" to the preview where [message] is the content of the message the user reacted to? Or do we need to shorten it to "you reacted with [emoji]" & "[user] reacted with [emoji]" ? 

Also, @VolkerJunginger & @amshakal I assume that we do **not** want to show the toggle and that if the user sees previews they always see reactions in this way?

**Comment by VolkerJunginger** [comment]
We should not have a setting to change the preview behaviour.

**Comment by daniellekirkwood** [comment]
Awesome. 

If we want to open a new ticket to only show reactions on the most recent event in the room, feel free to open that as a new issue here. I think y'all have delayed work on reactions though so that might not be necessary. 

@weeman1337 We're good to go! I will update the main content of the issue to reflect the decisions made in comments but ping me any questions :D Thank you!

**Comment by daniellekirkwood** [comment]
lol i didn't read the comments here and it looks like @t3chguy already actioned this... !
