### ISSUE TITLE
Images no longer reserve their space in the timeline correctly

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25082]
### Steps to reproduce

1. Receive an image message
2. Note that the tile is small while loading
3. Timeline jumps when image loads

#### What did you expect?

The blurhash and skeleton loading animation from past releases, and for the space to be reserved in the timeline.

#### What happened instead?

![image](https://user-images.githubusercontent.com/1190097/231231120-e8e91087-588f-4434-909a-bcf40aba6780.png)

^during load

![image](https://user-images.githubusercontent.com/1190097/231231225-d4f5e430-0852-4b66-8493-2d44c6617a9d.png)

^after load

The event does have dimension information in it:

```
{
  "type": "m.room.message",
  "content": {
    "body": "image.png",
    "info": {
      "size": 98660,
      "mimetype": "image/png",
      "w": 1085,
      "h": 764,
      "xyz.amorgan.blurhash": "REDACTED"
    },
    "msgtype": "m.image",
    "file": {
      "v": "v2",
      "key": { REDACTED },
      "iv": "REDACTED",
      "hashes": {
        "sha256": "REDACTED"
      },
      "url": "mxc://REDACTED"
    }
  }
}
```

I believe this started happening after the security release.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023041101 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Regressed by cefd94859c40f7ea85f09fd8e2c856aa5724e151
