### ISSUE TITLE
Read receipts fall from the sky when they were pointing at the last message and a reaction is sent

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25081]
### Steps to reproduce

1. Create a room with at least 1 other participant.
2. Send a message.
3. Read that message from the participant's side.
4. While watching the sending client, send a reaction to that message from the participant.
5. Note that the read receipt flies down from the sky rather than simply not moving.

#### What did you expect?

Stable behaviour on read receipts. This didn't happen before.

#### What happened instead?

See above. It's a bit distracting. This has been happening for a couple weeks now (I think since the security release).

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023041101 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by weeman1337** [comment]
> (I think since the security release).

Also happening with a pre security release version.
