### ISSUE TITLE
Early signs of room list corruption

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25099]
### Steps to reproduce

1. Open console
2. Be worried

### Outcome

```
Room list index corruption: 0 (i:30) is greater than undefined (i:undefined) - category indices are likely desynced from reality
Room list index corruption: 0 (i:29) is greater than undefined (i:undefined) - category indices are likely desynced from reality
```

This appears to be happening when switching rooms. Seeing this warning logged is a *very* scary red flag that the room list is unstable or about to become incredibly broken. Hopefully though, it's benign and the surrounding code can be fixed to not cause the warning.

Unsure when it started.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023041201 Olm version: 3.2.12

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by steelman** [comment]
I can see this too on app.element.io.
```
Room list index corruption: 0 (i:0) is greater than undefined (i:undefined) - category indices are likely desynced from reality
```

**Comment by weeman1337** [comment]
I think this is caused by https://github.com/matrix-org/matrix-react-sdk/commit/9aef1874db09f0eb0eefca83d42e98b6afac7f40#diff-58fb34f963968c49c6e28c428d27861c6e078a05b7a86afe4ba9a814145617beR296

Maybe we should assume `undefined` as `0` there.
