### ISSUE TITLE
Encrypted DMs being created with users without encrypted devices

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#25098]
### Steps to reproduce

1. Create a DM with a user sporting no encrypted devices. An easy way to do this is to spin up an IRC client on libera.chat, and talk to yourself (@<nick>:libera.chat.)
2. Notice that the room is encrypted.
3. Obviously, messages do not work.

#### What did you expect?

If a invitee to a DM has no encrypted devices, the room should be created unencrypted.

#### What happened instead?

The room is created encrypted.

### Operating system

Arch Linux

### Browser information

Firefox 110

### URL for webapp

half-shot.uk

### Application version

Element version: 1.11.26 Olm version: 3.2.12

### Homeserver

half-shot.uk

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Element version: 1.11.26 Olm version: 3.2.12

Please update, there have been changes to this code since. You're 3 versions out of date.

**Comment by Half-Shot** [comment]
You got me, I was unable to prove this in the latest develop version :)
