### ISSUE TITLE
Joining rooms as a guest stuck in infinite loading.

### ISSUE THREAD

**Issue by EntityinArray** [vector-im/element-web#25100]
### Steps to reproduce

1. Visit https://isekai.su/#/rooms/!fZXXYsNtKPQekoCGPU%3Aisekai.su (guest accessible room)
2. Element web infinite loading incident

#### What did you expect?
Joining a room
#### What happened instead?
Infinite loading

Sorry, i'm unable to give you logs because app won't show the UI

### Operating system

Arch Linux

### Browser information

Google Chrome Version 111.0.5563.110 (Official Build) unknown (64-bit)

### URL for webapp

chat.isekai.su

### Application version

Element Version: 1.11.25 Olm Version: 3.2.12

### Homeserver

isekai.su, synapse

### Will you send logs?

No

**Comment by t3chguy** [comment]
Your link is invalid, it should be https://chat.isekai.su/#/room/!fZXXYsNtKPQekoCGPU%3Aisekai.su - room not rooms
