### ISSUE TITLE
Element Desktop, Connectivity to the server has been lost.

### ISSUE THREAD

**Issue by Hydroponic-Gardener** [vector-im/element-web#25102]
### Steps to reproduce
Running the app results in "Lost connection"

The desktop app has been non-functioning for whole day, but the web and mobile app works.
![image](https://user-images.githubusercontent.com/130553435/231553885-3004f3a2-825a-4635-90a1-147438be2e65.png)
Specs^
Using the latest version of Element Desktop/Web.

Help & About exits out of settings, security & privacy has "Unable to load" on many options, Notifications is errored out.

### Outcome

Connection to the server

App loads, connection not working.

### Operating system

Arch Linux

### Application version

1.11.26-1

### How did you install the app?

pacman

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Please report issues with community maintained packages to their own support tracker, also you're 3 versions out of date
