### ISSUE TITLE
Element crashes while building search index

### ISSUE THREAD

**Issue by pipoprods** [vector-im/element-web#25114]
### Steps to reproduce

From "Security & Privacy", click "Enable" under "Message Search".

Wait a few seconds, the app crashes. Restart it, it will crash again…

Disable "Message Search", no more crash.

#### What did you expect?

Message search to work.

#### What happened instead?

Message search doesn't work.

### Operating system

Debian

### Application version

Version de Element : 1.11.28 Version de Olm : 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

Synapse 1.81.0

### Will you send logs?

No

**Comment by uhoreg** [comment]
I believe this is the same as https://github.com/vector-im/element-web/issues/25010 and is being worked on

**Comment by pipoprods** [comment]
This comment suggests current bug should be reopened: https://github.com/vector-im/element-web/issues/25010#issuecomment-1512790127

**Comment by andybalaam** [comment]
> This comment suggests current bug should be reopened: [#25010 (comment)](https://github.com/vector-im/element-web/issues/25010#issuecomment-1512790127)

Sorry, my fault. I re-opened #25010
