### ISSUE TITLE
Explore rooms/Room directory does not contain spaces

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-web#25124]
### Steps to reproduce

1. Make a space

2. Publish it into the room directory (right click the space > settings > visibility > publish this room...)

3. Click on "Explore rooms"

![image](https://user-images.githubusercontent.com/24363938/232420956-8b7a348a-12ea-4949-b6f7-f709c7e58510.png)

4. Attempt to search for a Space

#### What did you expect?

After step 3, our space should appear. After step 4, our space should apear.

#### What happened instead?

Space does not show up

```
{"filter":{"generic_search_term":"","room_types":[null]}}
```

Element explicitly requests rooms without a room type, which excludes spaces. If Element instead requested spaces too, the homeserver would return them:

```
{"filter":{"generic_search_term":"","room_types":[null,"m.space"]}}
```

### Operating system

Linux

### Browser information

Firefox 112.0

### Application version

Element 1.11.24

### Homeserver

Synapse 1.77.0+jammy1

### Will you send logs?

No

**Comment by t3chguy** [comment]
The feature is in Labs.


<img width="975" alt="image" src="https://user-images.githubusercontent.com/2403652/232423425-dd91e9b0-6865-4e1d-87d3-c23a765d5c16.png">

**Comment by gabrc52** [comment]
Thank you for the fast response!
