### ISSUE TITLE
Flakey cypress test

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25128]
`should send location and reply to the location on ThreadView` in `threads/threads.spec.ts` regularly fails with:

```
Expected to find element: [data-test-id="share-location-option-Pin"], but never found it.
```

**Comment by kerryarchibald** [comment]
Where is the failure happening? Do you need to pull develop? This test id was changed yesterday by https://github.com/matrix-org/matrix-react-sdk/commit/8a4a584ba0b749b0e01b66d9ee85b2dbe67e72bd

**Comment by richvdh** [comment]
Oh, that might be it, thanks kerry.
