### ISSUE TITLE
Massive memory leak, very low volume room

### ISSUE THREAD

**Issue by the-moog** [vector-im/element-web#25120]
### Steps to reproduce

Element desktop on VM

1. Where: In a room, 1-2 msgs per day
2. Clicked: No interaction other than 1-2 msgs
3. Steps:  Let time pass

#### What did you expect?
Should just work as it does on a windows PC

#### What happened instead?
After 3-4 days 12G memory used. Eventually crashes PC due to available VM memory being used up.

Done a restart and discovered developer mode, which has a JS heap monitor, will run that for a few days.

### Operating system

Debian 11

### Application version

Element version: 1.11.26 Olm version: 3.2.12

### How did you install the app?

Don't recall - ages ago.

### Homeserver

Private Synapse

### Will you send logs?

No

**Comment by the-moog** [comment]
I noticed something very odd, perhaps this is related.   Looking at `top` with lots of detail turned on.  Element has many processes each with many threads - fine, makes sense.   What does not make sense is each process has requested 1TB virtual memory and each thread 32G.   Other processes and apps are in mB, the only one even close is Firefox at 1.2G.  Surely this can't be normal?


**Screen cap from top**  I can't get the table to format, but take a look at the bold text 1Tb!!
Would this not cause a temporary allocation to never be freed and reclaimed, instead paged?

<table align="left" border="1" cellpadding="0" cellspacing="0" style="width: 100%; font-size: 8px; border-collapse: collapse; margin: 0px auto; border: 1px solid rgb(154, 153, 150);">
<tr><th>    PID</th><th>    PPID</th><th>     TIME+</th>   <th>%CPU</th><th>  %MEM</th> <th>S</th> <th style="min-width:300px;">COMMAND</th>                                                        <th>VIRT</th><th> SWAP</th><th>    RES</th><th>   CODE</th><th>    DATA</th><th>    SHR</th>    <th>OOMa</th> <th>OOMs</th><th>   USED</th><th>   RSan</th>   <th>RSfd</th>   <th>RSlk</th>   <th>RSsh</th></tr> 
<tr><td>   1313</td><td>     731</td><td>   0:00.00</td>   <td>0.0</td><td>   0.0</td><td> S</td> <td>+    `- /usr/libexec/dconf-service                              </td><td> 152.3m<td>   0.0m</td><td>   5.1m</td><td>   0.0m</td><td>   16.8m</td><td>   4.6m</td>    <td> 0</td>  <td>666</td><td>   5.1m</td><td>   0.5m</td><td>   4.6m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>  15291</td><td>     731</td><td>   0:08.78</td>   <td>2.6</td><td>   0.4</td><td> S</td> <td>+    `- /usr/libexec/gnome-terminal-server                      </td><td> 464.6m<td>   0.0m</td><td>  45.1m</td><td>   0.2m</td><td>   51.1m</td><td>  33.8m</td>    <td> 0</td>  <td>668</td><td>  45.1m</td><td>  11.3m</td><td>  33.8m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    944</td><td>       1</td><td>   0:00.05</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td> `- /usr/libexec/udisks2/udisksd                                </td><td> 384.5m<td>   0.0m</td><td>  11.8m</td><td>   0.2m</td><td>   42.0m</td><td>   9.9m</td>    <td> 0</td>  <td>666</td><td>  11.8m</td><td>   1.9m</td><td>   9.9m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    945</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/udisks2/udisksd                            </td><td> 384.5m<td>   0.0m</td><td>  11.8m</td><td>   0.2m</td><td>   42.0m</td><td>   9.9m</td>    <td> 0</td>  <td>666</td><td>  11.8m</td><td>   1.9m</td><td>   9.9m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    947</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/udisks2/udisksd                            </td><td> 384.5m<td>   0.0m</td><td>  11.8m</td><td>   0.2m</td><td>   42.0m</td><td>   9.9m</td>    <td> 0</td>  <td>666</td><td>  11.8m</td><td>   1.9m</td><td>   9.9m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    950</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/udisks2/udisksd                            </td><td> 384.5m<td>   0.0m</td><td>  11.8m</td><td>   0.2m</td><td>   42.0m</td><td>   9.9m</td>    <td> 0</td>  <td>666</td><td>  11.8m</td><td>   1.9m</td><td>   9.9m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    958</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/udisks2/udisksd                            </td><td> 384.5m<td>   0.0m</td><td>  11.8m</td><td>   0.2m</td><td>   42.0m</td><td>   9.9m</td>    <td> 0</td>  <td>666</td><td>  11.8m</td><td>   1.9m</td><td>   9.9m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    983</td><td>       1</td><td>   0:00.03</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td> `- /usr/libexec/upowerd                                        </td><td> 233.0m<td>   0.0m</td><td>   8.1m</td><td>   0.1m</td><td>   25.2m</td><td>   7.2m</td>    <td> 0</td>  <td>666</td><td>   8.1m</td><td>   0.9m</td><td>   7.2m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    985</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/upowerd                                    </td><td> 233.0m<td>   0.0m</td><td>   8.1m</td><td>   0.1m</td><td>   25.2m</td><td>   7.2m</td>    <td> 0</td>  <td>666</td><td>   8.1m</td><td>   0.9m</td><td>   7.2m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>    986</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>     `- /usr/libexec/upowerd                                    </td><td> 233.0m<td>   0.0m</td><td>   8.1m</td><td>   0.1m</td><td>   25.2m</td><td>   7.2m</td>    <td> 0</td>  <td>666</td><td>   8.1m</td><td>   0.9m</td><td>   7.2m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>   1112</td><td>       1</td><td>   1:25.75</td>   <td>0.0</td><td>   1.4</td><td> S</td> <td> `- /opt/Element/element-desktop --hidden                       </td><td><b>1122.0g</b><td>   0.0m</td><td> 157.4m</td><td> 120.4m</td><td>  290.6m</td><td> 119.8m</td>    <td> 0</td>  <td>674</td><td> 157.4m</td><td>  37.7m</td><td> 117.9m</td><td>   0.0m</td><td>   1.9m</td> </tr>
<tr><td>   1240</td><td>       1</td><td>   0:00.00</td>   <td>0.0</td><td>   1.4</td><td> S</td> <td>     `- /opt/Element/element-desktop --hidden                   </td><td><b>1122.0g</b><td>   0.0m</td><td> 157.4m</td><td> 120.4m</td><td>  290.6m</td><td> 119.8m</td>    <td> 0</td>  <td>674</td><td> 157.4m</td><td>  37.7m</td><td> 117.9m</td><td>   0.0m</td><td>   1.9m</td> </tr>
<tr><td>   1242</td><td>    1112</td><td>   0:00.03</td>   <td>0.0</td><td>   0.4</td><td> S</td> <td>     `- /opt/Element/element-desktop --type=zygote --no-zygote+ </td><td><b>  32.2g</b><td>   0.0m</td><td>  49.4m</td><td> 120.4m</td><td>    4.8m</td><td>  41.0m</td>    <td> 0</td>  <td>668</td><td>  49.4m</td><td>   8.4m</td><td>  41.0m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>   1478</td><td>    1242</td><td>   0:02.76</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>         `- /opt/Element/element-desktop --type=gpu-process --+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1500</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1501</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1502</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1503</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1504</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1505</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1506</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1507</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1508</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1509</td><td>    1242</td><td>   0:00.00</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1510</td><td>    1242</td><td>   0:00.09</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1511</td><td>    1242</td><td>   0:08.19</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1513</td><td>    1242</td><td>   0:53.37</td>   <td>0.0</td><td>   0.8</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=gpu-proces+ </td><td><b>  32.5g</b><td>   0.0m</td><td>  96.1m</td><td> 120.4m</td><td>  147.5m</td><td>  72.3m</td>    <td> <b>3</b></td>  <td><b>804</b></td><td>  96.1m</td><td>  23.7m</td><td>  61.7m</td><td>   0.0m</td><td>  10.6m</td> </tr>
<tr><td>   1243</td><td>    1112</td><td>   0:00.03</td>   <td>0.0</td><td>   0.4</td><td> S</td> <td>     `- /opt/Element/element-desktop --type=zygote              </td><td><b>  32.2g</b><td>   0.0m</td><td>  49.1m</td><td> 120.4m</td><td>    4.8m</td><td>  40.8m</td>    <td> 0</td>  <td>668</td><td>  49.1m</td><td>   8.3m</td><td>  40.8m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>   1245</td><td>    1243</td><td>   0:00.00</td>   <td>0.0</td><td>   0.1</td><td> S</td> <td>         `- /opt/Element/element-desktop --type=zygote          </td><td><b>  32.2g</b><td>   0.0m</td><td>  12.4m</td><td> 120.4m</td><td>    4.8m</td><td>   4.0m</td>    <td> 0</td>  <td>666</td><td>  12.4m</td><td>   8.4m</td><td>   4.0m</td><td>   0.0m</td><td>   0.0m</td> </tr>
<tr><td>   1371</td><td>    1245</td><td>   5:06.75</td>   <td>0.7</td><td>   2.4</td><td> S</td> <td>             `- /opt/Element/element-desktop --type=renderer -+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1376</td><td>    1245</td><td>   0:00.00</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1377</td><td>    1245</td><td>   0:14.52</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1378</td><td>    1245</td><td>   0:14.84</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1381</td><td>    1245</td><td>   0:00.00</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1514</td><td>    1245</td><td>   0:19.96</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1515</td><td>    1245</td><td>   0:00.00</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1516</td><td>    1245</td><td>   0:01.84</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1517</td><td>    1245</td><td>   0:01.90</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1518</td><td>    1245</td><td>   0:01.79</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1519</td><td>    1245</td><td>   0:01.84</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1520</td><td>    1245</td><td>   0:00.00</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
<tr><td>   1528</td><td>    1245</td><td>   0:00.01</td>   <td>0.0</td><td>   2.4</td><td> S</td> <td>                 `- /opt/Element/element-desktop --type=render+ </td><td><b>1131.9g</b><td>   0.0m</td><td> 276.9m</td><td> 120.4m</td><td>  459.3m</td><td> 101.4m</td>    <td> <b>5</b></td>  <td><b>880</b></td><td> 276.9m</td><td> 175.5m</td><td>  97.4m</td><td>   0.0m</td><td>   4.0m</td> </tr>
</span>
</table>

**Comment by luixxiul** [comment]
This issue seems to be tracked here: https://github.com/vector-im/element-web/issues/21541

**Comment by the-moog** [comment]
In my case the PC never sleeps. So I am not sure it's the same issue.
It does turn off it's screen and lock it but the desktop never closes.  
I found the JS Heap debug in the developer menu so I am running it with that on for a few days.
