### ISSUE TITLE
Please publish packages for Debian bookworm on packages.element.io/debian

### ISSUE THREAD

**Issue by behrmann** [vector-im/element-web#25134]
#### What would you like to do?

Currently https://packages.element.io/debian/dists/index.html lists the current stable and older Debian releases as well as Debian unstable. The next stable Debian release, bookworm, is soon to release and during testing the release I noticed that `element-desktop` was not available. 

#### Why would you like to do it?

Because I like using element. :)

#### How would you like to achieve it?

Haven't looked at your build setup, but it should probably be little more than adding `bookworm` to your build matrix.

### Have you considered any alternatives?

The package for sid (Debian unstable) can be installed, but it will require explicitly opting into `-t sid`, which will be an extra step for automated installations or image builders and bookworm will be released in a few months and will probably (hopefully) receive packages then anyway, so this can be started now, since bookworm is already frozen and package versions won't change anymore.

**Comment by t3chguy** [comment]
Read the instructions - https://element.io/download#linux

`default` is used by all distros. The other names are only there for historical reasons when we had distro-specific namespacing. This was pointless as the package doesn't vary between distros. We build only once.

**Comment by behrmann** [comment]
Thanks for the hinted, tested it and it works flawlessly.
