### ISSUE TITLE
Typing notification is broken

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25165]
### Steps to reproduce

Look at a 1to1 DM where the other person is typing

### Outcome

![Screenshot from 2023-04-20 11-57-18](https://user-images.githubusercontent.com/51663/233346528-c0f2fe6d-d5b7-441d-ab39-98e35e42b603.png)

### URL for webapp

develop.element.io

### Application version

Element version: 66c86a639726-react-6b211dd602ff-js-cb180b4195a4 Olm version: 3.2.12

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Likely regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10666
