### ISSUE TITLE
Create a CSS file dedicated for managing `z-index` values

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25162]
#### What would you like to do?

Creating a CSS file dedicated for managing `z-index` properties.

#### Why would you like to do it?

Because the values affects the UI overall and managing those values on a single file should help us to see the hierarchy.

#### How would you like to achieve it?

Create `_zIndex.pcss`, set custom properties on the file, and apply them to each z-index declaration.

### Have you considered any alternatives?

Managing them on `_common.pcss` is alternative, though it makes the `:root` style block large as duplicate selector is not permitted.

**Comment by weeman1337** [comment]
@luixxiul to clarify this: Do you mean a file that holds all z-index values as variables (similarly [to the font sizes](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/_font-sizes.pcss) for instance)?

**Comment by luixxiul** [comment]
Yes, exactly!

**Comment by luixxiul** [comment]
I am wondering if this one will be deprecated by Compound stuff. I would like to ask someone to clarify, so that someone who works on this would not waste his/her time.
