### ISSUE TITLE
Plus button to add a space has border when clicked

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25172]
### Steps to reproduce

1. Open https://develop.element.io on Firefox
2. Click plus button to add a space on the left panel
3. Check `.mx_SpacePanel .mx_SpaceButton.mx_SpaceButton_new .mx_SpaceButton_icon::before`

#### What did you expect?

The border around the button should not appear.

#### What happened instead?

The border around the button appears.

https://user-images.githubusercontent.com/3362943/233580792-c10e3015-36f5-4c2e-8e37-5582f49c5fb1.mp4

Since the class does not have a declaration related to the border and the border disappears by disabling `background-color`, this issue should be related to the background declaration. This issue might be specific to Firefox.

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is a firefox bug - https://github.com/vector-im/element-web/issues/19296 - https://bugzilla.mozilla.org/show_bug.cgi?id=1671784
