### ISSUE TITLE
Autocomplete not showing up reliably

### ISSUE THREAD

**Issue by ZaquMan** [vector-im/element-web#25170]
### Steps to reproduce

1. Click text field and type @ symbol
2. Begin typing user's username

![image](https://user-images.githubusercontent.com/43051103/233506676-118e280b-8776-4c60-b97d-21ad5634b422.png)

#### What did you expect?
The list of usernames to reduce to the point of only listing the user who's username was entered after the @ symbol.

#### What happened instead?
The list of usernames became blank, as if there were no matching users.

### Operating system

Windows 10

### Application version

Element version: 1.11.29 Olm version: 3.2.12

### How did you install the app?

Originally, https://packages.riot.im/desktop/install/win32/x64/Element%20Setup.exe but updates through the app.

### Homeserver

https://chat.serverplus.com (Synapse 1.79.0)

### Will you send logs?

Yes

**Comment by alunturner** [comment]
Hello @ZaquMan , thank you for opening an issue.

Please can you confirm that if, in the above example, you had entered the text `@sam` there was still nothing shown by the autocomplete? I would expect that to match the "Samuel Lee" user at least. Do you have more information as to which users are present in the rooms and what their names are?

In the screenshot shown, you have entered `@sami`. The current behaviour, which I believe is the expected behaviour, is that that would not match against "Samuel...", so unless there are users in that room containing the string "sami" in their name, I would expect no matches there.

Perhaps a good step forward would be if you could grab a screen recording of the effect of slowly entering "@sami", with small pauses between the letters to show what the autocomplete does.

**Comment by ZaquMan** [comment]
Sorry for the lack of detail.  The user that was supposed to show up was sami.soomro:serverplus.com, not samuel.lee:serverplus.com.  This is an intermittent issue, so it may be difficult to get that recording for you.  However as this is affecting multiple users in our organization, I'll ask them to try and catch recordings of it happening.

As for users in the room, there are 29 members of that room:
<html>
<body>
	<table>
		<tbody>
			<tr>
				<td>&nbsp;@alvin.diolola:serverplus.com</td>
				<td>&nbsp;@kyle.fitzgerald:serverplus.com</td>
				<td>&nbsp;@michael.turner:serverplus.com</td>
				<td>&nbsp;@sami.soomro:serverplus.com</td>
			</tr>
			<tr>
				<td>@arslan.james:serverplus.com&nbsp;</td>
				<td>&nbsp;@layne:serverplus.com</td>
				<td>&nbsp;@monsin.delosreyes:serverplus.com</td>
				<td>&nbsp;@samuel.lee:serverplus.com</td>
			</tr>
			<tr>
				<td>@christopher.jenkins:serverplus.com&nbsp;</td>
				<td>&nbsp;@leanna.esguerra:serverplus.com</td>
				<td>&nbsp;@neo:serverplus.com</td>
				<td>&nbsp;@scha:serverplus.com</td>
			</tr>
			<tr>
				<td>&nbsp;@danny.guajardo:serverplus.com</td>
				<td>&nbsp;@markjason.landicho:serverplus.com</td>
				<td>&nbsp;@nephi.andersen:serverplus.com</td>
				<td>&nbsp;@tyler.williams:serverplus.com</td>
			</tr>
			<tr>
				<td>&nbsp;@eli.goodman:serverplus.com</td>
				<td>&nbsp;@marktan:serverplus.com</td>
				<td>&nbsp;@nick.diolola:serverplus.com</td>
				<td>&nbsp;@zachary.barnett:serverplus.com</td>
			</tr>
			<tr>
				<td>&nbsp;@elmer.ferrer:serverplus.com</td>
				<td>&nbsp;@mary.parks:serverplus.com</td>
				<td>&nbsp;@niquolette.jones:serverplus.com</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td>&nbsp;@eric.greenwell:serverplus.com</td>
				<td>&nbsp;@maryjane.gayo:serverplus.com</td>
				<td>&nbsp;@patricia.hall:serverplus.com</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td>&nbsp;@kara.karnes:serverplus.com</td>
				<td>&nbsp;@michael.rizzuto:serverplus.com</td>
				<td>&nbsp;@robert.folker:serverplus.com</td>
				<td>&nbsp;</td>
			</tr>
		</tbody>
	</table>
</body>
</html>

**Comment by alunturner** [comment]
No need to apologise - anything that helps with investigation is appreciated, I've been using this component a lot recently due to some related work but can't say I've seen this behaviour.

Perhaps the request for a video isn't really possible in that case - I didn't understand initially that it's an intermittent issue

**Comment by t3chguy** [comment]
I've had similar issues but with the emoji autocomplete, where `:facep` sometimes just doesn't pop up the completer, emptying it and re-typing fixes it. Seems racy. Definitely a regression, no clue when.

**Comment by ZaquMan** [comment]
We're having issues with the emojis as well.  It might be related, or it might not be, so I was thinking of them as separate issues.

As for when, it seems to have been in the past couple weeks, as the first person to report it to me mentioned before they were unable to reliably click a user's name to mention them.  After that was fixed, the issues with autocompleting usernames and emojis began.

**Comment by scottwallacesh** [comment]
I'm seeing the same issue with `@room`, any username or emoji/emoticon.

As mentioned, clearing it and re-typing it sees it working again.

**Comment by alunturner** [comment]
I've found some steps to reproduce for this (there may be others). Would appreciate if you could try these steps @ZaquMan to see if it reproduces this way for you too. This was testing on develop on 28 Apr:

STR:

- enter some text to open the autocomplete (could be mention or emoji, doesn't matter)
- pick something from the autocomplete
- send the message
- now try to open **the same** autocomplete by entering text
- autocomplete will not open

Interestingly it seems that sending a purely text message followed by trying to open the emoji picker also blocks that autocomplete opening (but this isn't the case for user mentions). See second video. Not in both videos, to get it to work I press backspace until the placeholder appears (as noted as a workaround in the comments above).

Video of following STR:

https://user-images.githubusercontent.com/56027671/235110116-34fb791e-1de2-480c-bf9f-d9023df53028.mov


Video of specific emoji behaviour:

https://user-images.githubusercontent.com/56027671/235110153-2c9539b7-5cae-418e-8f07-b1ea8543aabd.mov

**Comment by t3chguy** [comment]
@alunturner I can reproduce using those steps, thanks

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/e4dfb21e56de9d469ff4b73387316034f8aa3721
