### ISSUE TITLE
Notification for my own message in a thread that took forever to encrypt

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#25178]
### Steps to reproduce

1. Reply to a thread in an encrypted room
1. Make an edit before the message sends
1. Go to another room because it's taking forever to encrypt and will send eventually
1. See a notification for the thread root

#### What did you expect?

I sent the message so I don't care about new activity in the thread about it (no notification)

#### What happened instead?

I see a notification for the thread root indicating activity happened in that thread (https://github.com/vector-im/element-web/issues/24620)

### Operating system

Windows 10

### Browser information

Chrome Version 112.0.5615.122

### URL for webapp

develop.element.io

### Application version

Element version: 66c86a639726-react-2da52372d49c-js-743ba5f050ea Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
We don't use toasts for message notifications, do you mean HTML5 Desktop notifications? Toasts are the things we have top left, desktop notifications tend to be on the right but it depends on your OS/WM/NM

**Comment by MadLittleMods** [comment]
@t3chguy I've updated it to just say "notification" ⏩

I wasn't referring to some specific toast implementation in our app.

**Comment by t3chguy** [comment]
I believe this to be fixed now, please shout if you can reproduce on >1.11.36
