### ISSUE TITLE
Structural attributes are removed from HTML tables

### ISSUE THREAD

**Issue by AndrewKvalheim** [vector-im/element-web#25179]
### Steps to reproduce

Send a message containing an HTML table that uses `colspan` and `rowspan`:

```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "…",
    "format": "org.matrix.custom.html",
    "formatted_body": "<table><thead><tr><th colspan=\"2\">A</th><th>B</th></tr><tr><th>C</th><th>D</th><th>E</th></tr></thead><tbody><tr><td>F</td><td>G</td><td rowspan=\"2\">H</td></tr><tr><td>I</td><td>J</td></tr></tbody></table>"
  }
}
```

#### What did you expect?

The structure of the table is preserved:

> <table>
>   <thead>
>     <tr><th colspan="2">A</th><th>B</th></tr>
>     <tr><th>C</th><th>D</th><th>E</th></tr>
>   </thead>
>   <tbody>
>     <tr><td>F</td><td>G</td><td rowspan="2">H</td></tr>
>     <tr><td>I</td><td>J</td></tr>
>   </tbody>
> </table>

#### What happened instead?

The `colspan` and `rowspan` attributes are [removed](https://github.com/matrix-org/matrix-react-sdk/blob/v3.70.0/src/HtmlUtils.tsx#L301):

> <table>
>   <thead>
>     <tr><th>A</th><th>B</th></tr>
>     <tr><th>C</th><th>D</th><th>E</th></tr>
>   </thead>
>   <tbody>
>     <tr><td>F</td><td>G</td><td>H</td></tr>
>     <tr><td>I</td><td>J</td></tr>
>   </tbody>
> </table>

### Operating system

NixOS 22.11

### Browser information

Firefox 112

### URL for webapp

app.element.io

### Application version

Element version: 1.11.29, Olm version: 3.2.12

### Homeserver

Synapse 1.80.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is as per the Matrix spec - I suggest opening an issue in https://github.com/matrix-org/matrix-spec - https://spec.matrix.org/v1.6/client-server-api/#mroommessage-msgtypes does not list colspan or rowspan as permitted.
