### ISSUE TITLE
PostHog ingestion warning due to repeated identification of already identified user

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25187]
We're currently seeing around 2-3k daily [ingestion warnings](https://posthog.element.io/data-management/ingestion-warnings) on PostHog.

> Refused to merge already identified person `foo-bar-foo` into `bla-bla-bla` via an `$identify` or `$create_alias` call

Judging from the [docs,](https://posthog.com/docs/data/data-management#creating-definitions) these stem from attempting to call `identify` on an already identified user.

Browsing through the user list,  many of them appear to be from Element Web so we should start the investigation here. The code already mentions a possible race condition but this isn't necessarily the root problem.

```
// Couldn't retrieve an analytics ID from user settings, so create one and set it on the server.
// Note there's a race condition here - if two devices do these steps at the same time, last write
// wins, and the first writer will send tracking with an ID that doesn't match the one on the server
// until the next time account data is refreshed and this function is called (most likely on next
// page load). This will happen pretty infrequently, so we can tolerate the possibility.
```

**Comment by Johennes** [comment]
@t3chguy could I ask you to take a look into this?

**Comment by laurencegill** [comment]
@Johennes we're still seeing these alerts FTR

https://posthog.element.io/data-management/ingestion-warnings

**Comment by t3chguy** [comment]
This looks like ios

![image](https://github.com/vector-im/element-web/assets/2403652/bf9e7586-b328-4081-a312-a0447d2a4506)

https://posthog.element.io/person/fc7fa6a7-ccc1-4cfc-9973-03d0fffd463d#activeTab=featureFlags
