### ISSUE TITLE
Way to Join/View a room without closing the "Explore public rooms" window.

### ISSUE THREAD

**Issue by HubKing** [vector-im/element-web#25188]
### Your use case

Currently, if I open "Explore public rooms" and I click a room in the list, the list gets closed. If I want to visit the next room in that list, I have to open the list again (and search with the same keyword again, if it was a search result list). This is very inconvenient.

There should be one of these options

1. Join/view a room without closing the list window
2. Select multiple rooms in the list and join/view them all.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/21288
Related https://github.com/vector-im/element-web/issues/5111

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/12269
