### ISSUE TITLE
Unthreaded read receipts are sent after reading the main timeline

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25196]
### Steps to reproduce

1. Open network logging
1. Create a room
2. Invite someone else
3. Let them send a message
7. Look at the room's main timeline

#### What did you expect?

It should send a receipt for the `main` thread after reading the main timeline

see [Threaded read receipts](https://spec.matrix.org/v1.5/client-server-api/#threaded-read-receipts) in the spec

#### What happened instead?

`/read_markers` sent when viewing the main timeline (creates unthreaded receipts)

![image](https://user-images.githubusercontent.com/6216686/234505404-2ff665f7-eec4-4e83-951f-a677c90c5c42.png)

### Application version

Element Nightly version: 2023042301 Olm version: 3.2.12

### Will you send logs?

No

**Comment by clokep** [comment]
> If everything (= all threads and main timeline) is read after reading the thread it should additionally send an unthreaded receipt

This doesn't seem necessary. I think we want to only send unthreaded receipts when we use the "Mark as read" button.

**Comment by t3chguy** [comment]
Also `m.fully_read` != read receipts, the read marker is the green horizontal line which follows different rules as to when it moves.

**Comment by weeman1337** [comment]
Thank you for your comments @t3chguy and @clokep . I've updated the issue description to be more specific. Let us focus on the `main` timeline receipt here.
