### ISSUE TITLE
Room is missing avatar in directory

### ISSUE THREAD

**Issue by jeangb** [vector-im/element-web#2519]
Related to https://github.com/vector-im/vector-android/issues/579
![room with no photo](https://cloud.githubusercontent.com/assets/22364949/19769172/a313e7e6-9c5a-11e6-9efe-f2cf129268d5.jpg)
I can't find this room anymore in the room directory, but it still exists as I can go into since I joined it weeks before.

Reproduced on v0.8.3.

**Comment by aaronraimist** [comment]
Is this still an issue?

**Comment by yannicka** [comment]
Two years later, is it still an issue?

**Comment by turt2live** [comment]
I'm assuming not.
