### ISSUE TITLE
„Mark as read“ button does not send the correct receipt for the last event in a thread

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25207]
:information_source: There is another bug about the button itself https://github.com/vector-im/element-web/issues/24229 This bug here is specifically related to sending the correct receipt.

### Steps to reproduce

1. Create a room
2. Start a thread
3. Let someone send a message to the main timeline
4. Read everything, so that the room is marked as read
5. View another room
6. Let someone send a message to the thread
7. Use „Mark as read“ from the room context menu

#### What did you expect?

Unthreaded read receipt sent for the last message in the thread.

The button should always send a receipt for the last message in the room. Either from the main timeline or a thread timeline.

#### What happened instead?

Unthreaded read receipt sent for the last message in the main timeline.

### URL for webapp

https://develop.element.io/

### Application version

Element version: e558661a7784-react-b32482bc4aa5-js-73dbd709d801 Olm version: 3.2.14

### Will you send logs?

No

**Comment by clokep** [comment]
> Unthreaded read receipt sent for the last message in the main timeline.

I think this should be "for the last message in the *room*", not the main timeline specifically. (If the goal is to mark the entire room, including all threads, as read.)

**Comment by weeman1337** [comment]
> > Unthreaded read receipt sent for the last message in the main timeline.
> 
> I think this should be "for the last message in the _room_", not the main timeline specifically. (If the goal is to mark the entire room, including all threads, as read.)

I've double checked. „Unthreaded read receipt sent for the last message in the main timeline.“ is the answer to „What happened instead?“ from the issue description. The correct behaviour is the answer to „What did you expect?“ is „Unthreaded read receipt sent for the last message in the thread.“.

Anyway I've slightly updated the description to mention that it should mark the entire room as read.
