### ISSUE TITLE
Iphone element does not update when modifications are done in a message originally worked on desktop element

### ISSUE THREAD

**Issue by NATALIE69NKM** [vector-im/element-web#25205]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Will you send logs?

No

**Comment by robintown** [comment]
Hi @NATALIE69NKM, please fill out the issue template to describe what bug you're experiencing.

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-ios is the repo for Element iOS
