### ISSUE TITLE
:rofl: alias

### ISSUE THREAD

**Issue by 42Willow** [vector-im/element-web#25211]
### Your use case

Currently you have to type `:rolling_on_the_floor_laughing:` which is kind of tedious...

Adding another alias such as `:rofl:` would be useful.

**Comment by t3chguy** [comment]
They come from https://github.com/milesj/emojibase - I suggest opening a request there

**Comment by 42Willow** [comment]
@t3chguy 

https://github.com/milesj/emojibase/issues/156

> They come from https://github.com/milesj/emojibase - I suggest opening a request there

Are you sure it's emojibase? Or is it `iamcal`?

**Comment by t3chguy** [comment]
Both. We use milesj/emojibase's iamcal.json
