### ISSUE TITLE
regression in being able to resend stuck messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2523]
i don't have full repro steps, but i am fairly sure that sending messages has got less reliable when on bad connections.  for instance, when the server stops responding for a few minutes after an IO explosion, i have reports of people getting stuck with loads of unsent messages, but no way of triggering a resend

**Comment by ara4n** [comment]
I just had this after today's IO meltdowns.  Messages were stacking up despite the server otherwise being back, but no UI to resend them; they were stuck in grey.  Logs attached.
[bug-2523.txt](https://github.com/vector-im/riot-web/files/694394/bug-2523.txt)

**Comment by ara4n** [comment]
...and just had this again after DC1 firewall meltdown.

**Comment by ara4n** [comment]
Just had this again.  Errors are:

```
bundle.js:20633 Persisting sync data up to  s118136230_177531992_510334_18178459_186038_63906_600364_394212
2017-03-23 16:08:57.418 bundle.js:49086 Uncaught Error: ETIMEDOUT
    at too_late (bundle.js:71681)
2017-03-23 16:09:03.870 bundle.js:63328 Uncaught Error: updatePendingEventStatus called on an event which is not a local echo.
    at Room.updatePendingEvent (bundle.js:63328)
    at _updatePendingEventStatus (bundle.js:54126)
    at MatrixScheduler._procFn (bundle.js:53297)
    at _processQueue (bundle.js:70190)
    at bundle.js:70212
```

**Comment by ara4n** [comment]
it looks like a single request which gets stuck and fails with some error may wedge all subsequent ones.

**Comment by kittykat** [comment]
I'm going to close this issue for now as I was testing this a few weeks ago and re-sending messages worked fine (was testing for notifications, which are also fixed now). If it is still an issue for anyone, please reopen.
