### ISSUE TITLE
Space search returns no results

### ISSUE THREAD

**Issue by 0xdevalias** [vector-im/element-web#25239]
### Steps to reproduce

- With spaces enabled, click on a space on the left hand sidebar to view the 'space overview' screen
  - ![image](https://user-images.githubusercontent.com/753891/235389048-bb74e8e5-e327-43c9-8112-0a949f57046b.png)
- On the 'space overview' screen, find the 'Rooms and spaces' title, and notice that there is nothing listed underneath it, even though we can see in the 'middle panel' on the left that there are rooms within this space
- Hover over the 'Remove' button and notice the tooltip that says 'Select a room below first'
  - ![image](https://user-images.githubusercontent.com/753891/235389147-ac05e335-ea0a-45c9-aedd-92d8cd7e9226.png)
- Notice that there are no rooms listed 'below', and thus no ability to select them to be able to remove them.
- In the 'space overview' search bar, type a search query that won't match anything, and notice that it shows 'No results found' in the 'Results' section
  - ![image](https://user-images.githubusercontent.com/753891/235389310-5a4ea6d2-104c-4778-b71b-6e163774e763.png)
- In the 'space overview' search bar, type a search query that should match something (eg. the letter `e`), and notice that it shows nothing under the 'Results' section (but notice that it isn't showing 'No results found', implying that we should actually see results being listed here)
  - ![image](https://user-images.githubusercontent.com/753891/235389377-cd0bce76-5de8-4f03-acbe-8f17a143e619.png)

#### What did you expect?

I would see a list of rooms in the space, and be able to select them, to then be able to remove them.

#### What happened instead?

There were no rooms listed, and thus I wasn't able to remove them from the space.

### Operating system

macOS

### Browser information

Version 112.0.5615.49 (Official Build) (x86_64)

### URL for webapp

https://app.schildi.chat/

### Application version

SchildiChat version: 1.11.30-sc.2, Olm version: 3.2.12

### Homeserver

beeper.com

### Will you send logs?

No

**Comment by 0xdevalias** [comment]
Note that this also appears to be an issue in the [Beeper](https://www.beeper.com/) desktop app (bug reported to them as `DES-10667`, but I suspect the issue is with upstream `element-web` given I can replicate it on a non-Beeper client):

```
Beeper
olm version: Olm version: 3.2.8
beeper-web commit hash: ba7fce556d46c6a12a04f891a6a8ba0c0521398e
beeper-desktop version: 3.52.29
```

**Comment by gsouquet** [comment]
Thank you for raising this issue.
Would you be able to link a rageshake (Type `/rageshake` in any room) with this issue right after reproducing this bug?
This will help pinpoint the source of the problem.

**Comment by t3chguy** [comment]
I suggest reaching out to Beeper support, given the screenshot showing an empty list without any filter that implies their `/hierarchy` API is returning no results. Please shout if you reproduce on a more conventional server with a stock Element (not Schildi)

**Comment by 0xdevalias** [comment]
@gsouquet @t3chguy Fair enough, thanks for trying. I've pinged Beeper support again and asked for further clarity:

> RE: DES-10667, the upstream bug report I opened with element-web directed me back to Beeper Support: https://github.com/vector-im/element-web/issues/25239#issuecomment-1535933563
> 
> Can you confirm whether this is broken because your `/hierarchy` endpoint is not returning data as it should?

**Comment by 0xdevalias** [comment]
This was feedback from support, so I guess that explains why it's seemingly not reproducible for others, as it seems to be related to Beeper's implementation of the homeserver/similar:

> Re: DES-10667: the `/hierarchy` endpoint has not been implemented yet because we don't use it within our own clients and it only affects third party clients (hence you're not getting data)
> 
>  - Rishi
