### ISSUE TITLE
Incorrect username highlighting when mxid finishes with a dot

### ISSUE THREAD

**Issue by 33Spot** [vector-im/element-web#25246]
### Steps to reproduce

1. in any room or private message i write down and post username link like this for example: @username.:matrix.org

#### What did you expect?
link should work for whole username like it is working for other usernames without dot
#### What happened instead?
link is not working like it would normally. it is working only for the matrix.org part.

![Screenshot 2023-05-02 at 09 01 46](https://user-images.githubusercontent.com/769871/235612035-3c3eb6dd-5002-498f-a389-069ab3c7f132.png)

### Operating system

Linux

### Browser information

chromium; ferdium

### URL for webapp

app.element.io

### Application version

Element: 1.11.30 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by gsouquet** [comment]
According to the spec, this is a valid mxid, https://spec.matrix.org/v1.6/appendices/#common-namespaced-identifier-grammar

The regular expression must be missing this scenario.

**Comment by 33Spot** [comment]
it works ok on android as i see. i believe it may work on desktop app too. but on web app its like i posted
