### ISSUE TITLE
Microphone auth (ALL VERSION)

### ISSUE THREAD

**Issue by metasystem** [vector-im/element-web#25243]
### Steps to reproduce

No popup auth for webcam/microphone.
On:
- W11 (app)
- Gentoo 6.1.19-rt (firefox)
- Gentoo       "       (electron app).

### Outcome

The app is worst after every update...
jitsi implementation don't work for many, many reasons... I already make bug reports, but the problems disappears on some support and appears on another...
Notification don't work for many supports or sometimes, never arrived...
I think I will remove element for some years because it's unusable...

### Operating system

Linux & Windows

### Browser information

Firefox 112.0.2 (64 bits)

### URL for webapp

https://app.element.io

### Application version

1.11.29 on linux...

### Will you send logs?

No

**Comment by gsouquet** [comment]
@metasystem could you please give clear reproduction steps regarding this issue? At what point do you usually receive a prompt to access the microphone data, ...

In the current state of this issue we will not be able to investigate further.
