### ISSUE TITLE
Edit `code_style.md` to discourage using mixins

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25240]
### Steps to reproduce

1. Create a PR which uses `@mixin`
2. Wait for a review
3. Wait for the change to be effectively rejected by an Element employer based on "our goal": https://github.com/matrix-org/matrix-react-sdk/pull/10743
4. Be annoyed as "our goal" is explained nowhere ("what the hell is 'our goal'?")
5. Be distrustful of the team due to the information gap

#### What did you expect?

- The policy should have been explicitly published, especially if the policy is used to request a change
- I expected "our goal" was *our* goal and not something of the internal team members

#### What happened instead?

- The internal policy has not been reflected to the documentation, which discourages people who do not belong to the internal private rooms from contributing
- The PR was effectively rejected by not sharing unspoken internal "our" goal, which is to make stuff in vanilla CSS.

That goal should be universally applied. Therefore, `@mixin` should be universally deprecated.

### Will you send logs?

No

**Comment by luixxiul** [comment]
Personally I think I have experienced this kind of gaps a lot of times since https://github.com/vector-im/element-web/issues/21728, and I believe (without factual evidence) that's one of the reasons why this project could not gain the third party developers who constantly contribute.

Especially it seems Design and Product teams are either reluctant or unwilling to publish the latest information in a timely manner.

**Comment by andybalaam** [comment]
@luixxiul thank you for raising this issue, and I'm sorry that this has been frustrating.

Yes, we should document items like this, and we are grateful to you for pointing them out. But, I don't think it's realistic to expect everything to be caught and documented before it trips a contributor up. I'm afraid this will happen from time to time, and the only way I can suggest to make it less likely is to chat about changes we are thinking about in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org). I am encouraging the Element employees to chat in that room, and I encourage you to do the same. It's always best to talk things through before spending a lot of time on them.

**Comment by luixxiul** [comment]
Thanks for your reply. I do not expect everything should / could be documented either. The point is how to reduce the frequency of such annoying experiences. I am sure that you also would feel annoyed when unwritten rules are applied (by a government for example) against your actions, as if those rules had been shared. That's essentially what happened.

I agree with you that sharing communication should be one of the ways to reduce the change of such experiences, including documentation (which obviously should be based on the open discourse, dialog). It is really appreciated that you recommend using https://matrix.to/#/#element-dev:matrix.org to employees, since it is pretty obvious that it has not been a preferred communication channel among them. I'd like to expect much more communication related to development will happen there, so that everyone could follow the context freely, the power hierarchy based on the information gap is removed, and transparency is maintained.

**Comment by andybalaam** [comment]
Absolutely. We are doing our best, but we need to improve, and your feedback is helping. Thank you!

**Comment by luixxiul** [comment]
I'm pretty confident this won't be fixed, so closing
