### ISSUE TITLE
`X-Needs-Percy` label does not seem to run on the merge queue

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25252]
### Steps to reproduce

1. Create a PR on https://github.com/matrix-org/matrix-react-sdk (such as https://github.com/matrix-org/matrix-react-sdk/pull/10744)
2. Add `X-Needs-Percy` label to the PR
3. Add the PR to the merge queue

#### What did you expect?

Percy should run for the PR, according to the documentation: https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/cypress.md#screenshot-testing-with-percy:

> If your pull request makes visual changes, you are encouraged to request Percy to run by adding the label X-Needs-Percy to the PR, these will only run in the merge queue to save snapshots. 

#### What happened instead?

It seems it did not run: https://github.com/matrix-org/matrix-react-sdk/pull/10744#event-9143888691

### Will you send logs?

No

**Comment by richvdh** [comment]
I think [this line](https://github.com/matrix-org/matrix-react-sdk/blob/develop/.github/workflows/cypress.yaml#L68) should be `github.event.workflow_run.event == 'merge_group'`. `merge_queue` is not listed at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows.

**Comment by t3chguy** [comment]
@richvdh that seems sane, I made that mistake many times, my brain seems to refuse to accept that github didn't name them the same damn thing
