### ISSUE TITLE
Element desktop app  installed on windows server with error and not working

### ISSUE THREAD

**Issue by EToLLa** [vector-im/element-web#25262]
### Steps to reproduce

1. Where are you starting? What can you see?
Download app from site and try to install it.
3. What do you click?
Trying to install dowloaded file
5. More steps…

#### What did you expect?
Expecting to start element app
#### What happened instead?
app crash with error Procedure entry point DiscardVirtualMemory not found in DLL C:\users\...\appdata\local\element-desktop\app-1.11.30\element.exe

### Operating system

Windows Server 2012 R2

### Application version

1.11.29, 1.11.30

### How did you install the app?

https://element.io/download

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
This OS support has been deprecated by electron, https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
Making Element Desktop not compatible with your current setup unfortunately
