### ISSUE TITLE
Ended Polls are Clipping Out of Bounds

### ISSUE THREAD

**Issue by Error504TimeOut** [vector-im/element-web#25263]
### Steps to reproduce

1. Chosse the Message Bubbles Design
2. Create a Poll
3. End the Poll
4. Decrease the width of the Window

https://user-images.githubusercontent.com/126692020/235709686-90f63b64-c4cb-4b67-ad98-bc40147e4028.mp4

#### What did you expect?
The Answer Bars/Blocks should be scaling down with the Message Bubble, they only do so to a certain width
#### What happened instead?
The Bars/Blocks scale down to a certain level then stop and therefore will clip out of bounds

### Operating system

Windows (also occurs in Browser)

### Application version

Element version: 1.11.30 Olm version: 3.2.14

### How did you install the app?

https://element.io/download

### Homeserver

Synapse 1.82.0

### Will you send logs?

No

**Comment by Error504TimeOut** [comment]
I forgot to say, that this doesn't happen if the poll is running (at least when it's a closed poll). You can see that a little bit at the top of the video.

**Comment by daniellekirkwood** [comment]
<img width="563" alt="Screenshot 2023-11-10 at 16 08 55" src="https://github.com/vector-im/element-web/assets/89144281/dd14a115-e335-472c-ae60-5d9f78a48e33">

ran into this again today when closing a poll with bubbles on
