### ISSUE TITLE
Stabilize support for MSC3952: intentional mentions

### ISSUE THREAD

**Issue by clokep** [vector-im/element-web#25267]
### Your use case

MSC3952 has been accepted, we should stabilize support for it by using the stable identifiers:

* `org.matrix.msc3952.mentions` -> `m.mentions`
* `.org.matrix.msc3952.is_user_mention` -> `.m.rule.is_user_mention`
* `.org.matrix.msc3952.is_room_mention` -> `.m.rule.is_room_mention`

And we should de-labs it after testing.

### Have you considered any alternatives?

N/A

### Additional context

See #25266 for a known bug in the implementation.

**Comment by clokep** [comment]
Also see matrix-org/synapse#15487 for stabilizing this in Synapse.

**Comment by kerryarchibald** [comment]
Changes are drafted, will open for review following [synapse changes](https://github.com/matrix-org/synapse/pull/15520) and/or the EW user testing sessions.

**Comment by clokep** [comment]
@kerryarchibald I had a thought: should we update the buttons in the notification settings to disable the new push rules (in addition to the old)? Eg if you disable mentions it should probably toggle both versions?

Maybe this would be done with the settings UI rework though.

**Comment by kerryarchibald** [comment]
@clokep good thought! We should have that in place for the testing session. I'll make a ticket and coordinate with Janne

**Comment by Johennes** [comment]
Looks like the Synapse PR was merged. Is this ready to progress now?

**Comment by clokep** [comment]
It should be fine to, I think the element web code won't be used unless v1.7 is enabled in the server anyway? Not 100% sure how it is implemented.

**Comment by clokep** [comment]
@kerryarchibald Shall we close this or is it pending #25434?
