### ISSUE TITLE
A browser in another session has deleted the encryption keys used in the Element Desktop for Linux

### ISSUE THREAD

**Issue by eikmaster** [vector-im/element-web#25275]
### Steps to reproduce

1. Where are you starting? What can you see?
I see encrypted messages in the room, offered in another session from view for decryption

2. What do you click?
this situation does not stop with time

3. More steps…
I'll try to log out completely and use my keys locally, and not check with a confirmed session ...

### Operating system

Manjaro Linux

### Application version

Версия Element: 1.11.26 Версия Olm: 3.2.12

### How did you install the app?

Install Element Desktop from pacman manager 

### Homeserver

im.iosoc.ru

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
@eikmaster Could you clarify the reproduction steps? In its current state I unfortunately can't follow clearly how to face the same issue as you.

**Comment by t3chguy** [comment]
Closing due to lack of response
