### ISSUE TITLE
"show image", clicking on it does not work in all rooms

### ISSUE THREAD

**Issue by wsmwk** [vector-im/element-web#25271]
### Steps to reproduce

I see "show image", but clicking on it does not work in all rooms.

I am verified on all devices afaict.

### Operating system

macOS 13

### Application version

Version 1.11.30 (1.11.30)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by wsmwk** [comment]
logs sent

**Comment by andybalaam** [comment]
To reproduce, set "Show previews/thumbnails for images" in Preferences to false:

![image](https://user-images.githubusercontent.com/76812/235927737-e565763a-0997-468a-9628-fb1b7ff2f0ea.png)

**Comment by andybalaam** [comment]
I can reproduce this.

**Comment by wsmwk** [comment]
> To reproduce, set "Show previews/thumbnails for images" in Preferences to false:

Thanks @andybalaam, that helps.

**Comment by kerryarchibald** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10571
https://github.com/matrix-org/matrix-react-sdk/blob/7f7daa13b99a98e7afe5f7601f584a7aa0ac65b8/src/components/views/messages/MImageBody.tsx#L527
