### ISSUE TITLE
develop.element.io deployment seems to be missing files

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25273]
### Steps to reproduce

1. Under "security & privacy" settings, attempt to set up secure backup

#### What did you expect?

45 Setup flow

#### What happened instead?

error dialog. Observe from console that https://develop.element.io/bundles/f36f1bfa3532e92317bb/8.js is returning a 404 (despite other parts of that bundle such as  https://develop.element.io/bundles/f36f1bfa3532e92317bb/init.js being ok)

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This looks like missing redirects

https://element-web-develop.element.io/bundles/f36f1bfa3532e92317bb/init.js
https://element-web-develop.element.io/bundles/f36f1bfa3532e92317bb/8.js

both exist and should be redirected to

https://element-web-develop.element.io/_redirects

![image](https://user-images.githubusercontent.com/2403652/236416032-8c792d6e-8120-43ba-b49b-50cfcb986beb.png)

Seems like none of the redirects are working. I think we exceeded the limit of redirects and it made CFP sad

**Comment by t3chguy** [comment]
Looks like only the first 100 splats are respected, guess CFP treat them as Dynamic redirects and thus count towards the 100 limit - https://developers.cloudflare.com/pages/platform/redirects/#surpass-_redirects-limits
