### ISSUE TITLE
Space/Room nick setting through UI element

### ISSUE THREAD

**Issue by frillfish** [vector-im/element-web#25281]
#### What would you like to do?
Implement UI for setting space and room nicks rather than slash commands being the only option.
#### Why would you like to do it?
This was something I noticed as a pain point when starting to use Element. Nickname setting/general personal customization per space/room is a pretty basic function that many people will want to do up front when joining new spaces, but it's unfortunately buried in a long list of slash commands.
#### How would you like to achieve it?
Add a more visible UI element for customizing room nick, space nick, other similar elements if relevant. 

### Have you considered any alternatives?

Could also function well as a toggleable popup when joining new spaces (especially if you can set nick prior to properly joining a space/room so you join with your intended name, without it being shown in the chatlog, but that's a separate issue).

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/499
