### ISSUE TITLE
Timeline SearchBar overflows the narrow timeline with `BaseCard`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25291]
### Steps to reproduce

1. Open a room
2. Display a room info card or a thread
3. Enable Timeline SearchBar

#### What did you expect?

The input area, the buttons to search and cancel should be displayed.

![2](https://user-images.githubusercontent.com/3362943/236612807-60a7ded0-6958-47e5-81b2-6644d55c8173.png)

#### What happened instead?

The buttons are overlapped by the `BaseCard`. They are displayed by selecting with <kbd>tab</kbd> key.

![Screenshot from 2023-05-06 17-29-31](https://user-images.githubusercontent.com/3362943/236612904-313a5c19-548b-411b-a1b8-3b680e93c81a.png)

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by richvdh** [comment]
This only happens when the window is narrow
