### ISSUE TITLE
Image embeds/preview setting behaves VERY strangely

### ISSUE THREAD

**Issue by Draco18s** [vector-im/element-web#25296]
### Steps to reproduce

1. Start in a blank channel and set settings to default and make sure to clear cache and refresh
2. Turn "Show previews/thumbnails for images" off
3. Have someone send a sticker or image
4. Observe behavior (a)
5. Turn the setting back on
6. Observe behavior (b)
7. Have someone send a sticker or image
8. Observe behavior (c)
9. Ctrl-F5
10. Observe behavior (d)
11. Ctrl-F5 again
12. Observe behavior (e)
13. Turn the setting off and perform steps 4 through 12 again.
14. Observe behavior (f)

https://user-images.githubusercontent.com/1750680/236653511-abebfbe4-3745-4bf1-9ed7-fb5a6c096d9d.mp4

### Outcome

Behaviors:
(a) Image shows as a square with a "click to show" clicking does not show
(b) Images do not immediately show up
(c) New image does show up
(d) *Some* images show up
(e) All images how up
(f) Behaviors (a) through (e) but inversed: images do not immediately hide, new images are, click-to-show still doesn't work, and it takes 2 cache-free refreshes to make all images match new setting.

### Operating system

Windows

### Browser information

Chrome Version 112.0.5615.139 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.30 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Dav-Edward** [comment]
Confirmed I'm having the same issue in Firefox 112.0.2 (64-bit)

**Comment by Draco18s** [comment]
For comparison, here's how images look when not in-line in Discord (note how little vertical space they take up)
![image](https://user-images.githubusercontent.com/1750680/236653836-053950d3-421e-445b-8d99-05c6467d351d.png)

**Comment by kerryarchibald** [comment]
Duplicate https://github.com/matrix-org/matrix-react-sdk/pull/10781
