### ISSUE TITLE
A pill in a thread didn't link to the right room

### ISSUE THREAD

**Issue by thibaultamartin** [vector-im/element-web#25290]
### Steps to reproduce

I sent a pill to a room (#foobar:zor.tld) in a thread, and clicking on the pill didn't bring me to said room but refreshed current room

#### What did you expect?

I expected being able to go to the room I linked to

#### What happened instead?

The pill displayed the right info but eleweb didn't allow me to go there by clicking on the pill.

### Operating system

macOS

### Application version

Element Nightly version: 2023050201
Olm version: 3.2.14

### How did you install the app?

https://element.io/get-started#nightly

### Homeserver

Synapse 1.82

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
Unfortunately the rageshake did not shed any lights on a potential exception causing this bug

**Comment by weeman1337** [comment]
@thibaultamartin unfortunately I cannot reproduce it. I've tested sending room links to threads: works . Also the permalink in the thread from your rageshake works :neutral_face: 

Does that happen every time you send a room link to a thread?
The next time this happens, we can do a live debug to find the problem.

**Comment by t3chguy** [comment]
Closing due to lack of response
