### ISSUE TITLE
element desktop : device disconnect second authentication does not work 

### ISSUE THREAD

**Issue by eon2207** [vector-im/element-web#25300]
### Steps to reproduce

1. In main screen, Quick settings icon at the bottom left
2. In window newly opened, All settings
3. In settings window, select "Security & privacy" tab
4. Select one unverified devices
5. "Sign out 1 selected device" button
6. In "Authentication" new window, select "Start authentication"
7. Opens new tab in Firefox, JSON error (errcode | "M_UNKNOWN" -- | -- error | "Unknown auth stage type")
8. Can not go further
9. When closing "Authentication" window, having no message

### Outcome

A window allowing me to enter my password was expected, and the device should have been disconnected.

Instead, nothing happened.

### Operating system

GNU Linux : Debian 11

### Application version

Element version: 1.11.30 Olm version: 3.2.14

### How did you install the app?

https://packages.element.io/debian/ default main

### Homeserver

matrix.domainepublic.net

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your server is using a custom stage `com.devture.shared_secret_auth` which Element Web/Desktop do not support so it tries to delegate to the fallback auth API which your server doesn't support for this custom stage either. I suggest contacting your server admins for advice, they likely need you to use a custom client.
