### ISSUE TITLE
"Show rooms with unread messages first" should not be on by default for new users

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#25304]
"Show rooms with unread messages first" should not be on by default for new users (it is today) - the behaviour of how it works and interacts with M&K will stay the same for now but is being discussed.

**Comment by kerryarchibald** [comment]
@daniellekirkwood I can't figure out what M&K is here

**Comment by weeman1337** [comment]
@kerryarchibald I also can't figure out what M&K is here :upside_down_face:

**Comment by weeman1337** [comment]
Got it: M&K = Mentions & Keywords

**Comment by daniellekirkwood** [comment]
Sorry! "Mentions and Keywords" - my fault
