### ISSUE TITLE
Flaky Cypress test - `should handle long room address and long room name` on right-panel.spec.ts

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25317]
### Steps to reproduce

1. Check https://cloud.cypress.io/projects/ppvnzg/runs/5dc8530c-98db-4a4a-aa4d-ab0c7dff8336/test-results/901b191b-dac6-4260-93d0-2de44d76ab7b

#### What did you expect?

The test should run consistently.

#### What happened instead?

It sometimes fails due to the error below:

````
The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of null (reading 'isValid')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.

https://on.cypress.io/uncaught-exception-from-application
````

### Will you send logs?

No

**Comment by luixxiul** [comment]
Should checking its existence before clicking fix the issue, like `cy.findByRole("button", { name: "Room info" }).should("exist").click();`?

**Comment by richvdh** [comment]
Introduced by matrix-org/matrix-react-sdk#10811, presumably?

**Comment by luixxiul** [comment]
Since that PR added that test, I guess it should be so
