### ISSUE TITLE
Emoji list becomes jumbled after searching

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25323]
### Steps to reproduce

1. Open the emoji picker
2. Enter a search term
3. Clear the search field

#### What did you expect?

The emoji picker should return back to its original state:

![Screenshot 2023-05-09 at 12-23-00 Element 17 Test room](https://github.com/vector-im/element-web/assets/48614497/aac9439e-df6f-490e-b4d7-f020f2fa408a)

#### What happened instead?

Emoji are now displayed out of their original order:

![Screenshot 2023-05-09 at 12-23-14 Element 17 Test room](https://github.com/vector-im/element-web/assets/48614497/3f8471fa-8f46-4ea6-b743-802106a43574)

### Operating system

NixOS unstable

### Browser information

Firefox 112.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 1fb03c82fe30-react-1cfe126e1445-js-ee2b0204aa4e Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/0546a11fd99b18fb2be8cfdd308260ef15deefb2
