### ISSUE TITLE
Percy does not take snapshots of `Font size slider` properly

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25333]
### Steps to reproduce

1. Check https://percy.io/dfde73bd/matrix-react-sdk/builds/27304995/changed/1519329818?browser=firefox&browser_ids=36%2C38%2C39&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=486&widths=486%2C1024%2C1920
2. Check https://github.com/matrix-org/matrix-react-sdk/blob/82e32035fdf95ae03e5092c6147be0892c05edab/cypress/e2e/settings/appearance-user-settings-tab.spec.ts#L118 and https://github.com/matrix-org/matrix-react-sdk/blob/82e32035fdf95ae03e5092c6147be0892c05edab/cypress/e2e/settings/appearance-user-settings-tab.spec.ts#L131

#### What did you expect?

Percy should take snapshots of `mx_FontScalingPanel_fontSlider` in the same way in which it is rendered on the actual UI

#### What happened instead?

Percy did neither respect the `align-items` value nor `background` value of `mx_FontScalingPanel_fontSlider`.

### Will you send logs?

No

**Comment by andybalaam** [comment]
This is not something we can fix. Please could you log a bug against Percy and/or look for a different thing to screenshot to check the appearance of this item?

**Comment by luixxiul** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/10858 intends to change what to `get` and take snapshots against. With that PR, snapshots of the area which includes the slider will be started to be taken.
