### ISSUE TITLE
Flaky Jest test - `SendWysiwygComposer-test.tsx`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25348]
### Steps to reproduce

1. Check https://github.com/matrix-org/matrix-react-sdk/actions/runs/4955472391/jobs/8864904887?pr=10877
2. Run `SendWysiwygComposer-test.tsx` locally

#### What did you expect?

The test should pass on GitHub Action.

#### What happened instead?

The test passed locally but not on GitHub Action.

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/commit/4e5687c454377d4fab092a5fdd0f8dd9a835348f ?
