### ISSUE TITLE
Low memory key eviction (suggested by app)

### ISSUE THREAD

**Issue by mcint** [vector-im/element-web#25341]
### Steps to reproduce

1. Run the app
2. Use too much memory on the host
3. Restore low memory

#### What did you expect?
Keys still present?
#### What happened instead?
Keys evicted from memory, requiring manual re-authentication of device

### Operating system

macOS

### Application version

1.11.31

### How did you install the app?

brew, at 1.8.5, auto updates since

### Homeserver

synapse

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Restore low memory

What do you mean by this?

**Comment by t3chguy** [comment]
Closing due to lack of info
