### ISSUE TITLE
Manual approval of Percy build should be reflected to the base build

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25346]
### Steps to reproduce

- Create and merge PRs with the label `X-Needs-Percy` in a day, before a new based build is created based on `develop` and replaces the existing base build
 
Also:
- Compare [this build (2407)](https://percy.io/dfde73bd/matrix-react-sdk/builds/27329067/changed/1520653194?browser=firefox&browser_ids=36%2C38%2C39&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1920&widths=264%2C486%2C1024%2C1920) and [its next build (2408)](https://percy.io/dfde73bd/matrix-react-sdk/builds/27331687/changed/1520839291?browser=firefox&browser_ids=36%2C38%2C39&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1920&widths=264%2C592%2C1024%2C1920)

#### What did you expect?

Build 2408 should have 2407 as the base build, whose changes have been already approved.

#### What happened instead?

Build 2408 does not have its base build.

Therefore, you would manually have to compare the builds in order to check (1) whether there is a difference between those two builds and (2) whether there is a difference between the latest build and the actual base build (to see whether new changes introduced by 2407 would be regressed by 2408).

### Will you send logs?

No

**Comment by andybalaam** [comment]
I think we need to open a ticket with Percy to try and figure out what is going on here. I don't think it helps much to have this issue open, so closing for now. I'm not going to have time to follow this up, but if someone else wants to read the Percy docs and/or talk to Percy about how to fix this, that would be great!
