### ISSUE TITLE
Flaky Cypress test matrix-react-sdk/cypress/e2e/crypto/complete-security.spec.ts

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25368]
Example failure: https://cloud.cypress.io/projects/ppvnzg/runs/13899/test-results/531287dc-d4d8-4247-8627-56db578ac779

"should go straight to the welcome screen if we have no signed device" failed with:

```
Timed out retrying after 10000ms: Unable to find an accessible element with the role "button" and name "Edit"

Here are the accessible roles:

  document:

  Name "":
  <body
    style="height: 100%; margin: 0;"
  />

  progressbar:

  Name "Loading…":
  <div
    aria-label="Loading…"
    class="mx_Spinner_icon"
    data-testid="spinner"
    role="progressbar"
    style="width: 32px; height: 32px;"
  />
```

**Comment by richvdh** [comment]
That might help, but I think the root problem is that it is making requests to the actual live `matrix.org` deployment:

![image](https://github.com/vector-im/element-web/assets/1389908/853ea1ec-7397-4b6c-971d-248c2f0dd4e7)

This is clearly not something a cypress test should be doing.

I suspect it's not unique to this test.

I can take a look.

**Comment by andybalaam** [comment]
Oh, wow! Thank you.

**Comment by richvdh** [comment]
Hopefully this is now fixed by https://github.com/matrix-org/matrix-react-sdk/pull/10908. If it happens again, reopen and I can take another look.
