### ISSUE TITLE
Element no longer shows unread badges in collapsed room list

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#25372]
### Steps to reproduce

1. Collapse the room list into icons only by dragging the separator between room list and timeline all the way to the left
2. Wait for a room to get a new message

#### What did you expect?

Small white circle as unread indicator

#### What happened instead?

Room is reordered to top (according to my settings) but no unread indicator.

### Operating system

arch linux

### Application version

88c539534914c5aee65f2f12262579b3dbd45c09, olm version 3.2.14

### How did you install the app?

element-web-git AUR package

### Homeserver

Synapse 1.76.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/265b5332-54e8-425c-9506-5ee7bcb4f5fc)
![image](https://github.com/vector-im/element-web/assets/2403652/042aa58c-01e6-4238-acef-456cc07f1184)

Cannot reproduce

**Comment by alunturner** [comment]
Not sure if this helps at all as a datapoint, but I can see this behaviour in the current nightly desktop build (as of 17 May, can't reproduce on web though).
![Menubar_and_Element_Nightly__3____aluntest0](https://github.com/vector-im/element-web/assets/56027671/a2f9419a-aadf-4ebc-bb1f-8ba220479e4e)

![Menubar_and_Element_Nightly__3____aluntest0](https://github.com/vector-im/element-web/assets/56027671/5fd17bee-1afe-4910-834f-7545bf96a5a7)

**Comment by MonkeyBars3k** [comment]
Confirmed here as well on macOS Catalina.

**Comment by MonkeyBars3k** [comment]
@andybalaam Not sure why S-Minor and O-Occasional labels were added. This bug is neither intermittent, nor is there a proper workaround.

**Comment by MonkeyBars3k** [comment]
> @MonkeyBars3k I couldn't reproduce at all so how is if it isn't intermittent then it is a X-Cannot-Reproduce, which would you prefer?

Cannot reproduce is more accurate. Perhaps it has been fixed since the release build.

**Comment by Johennes** [comment]
@jplatte do you still see this on nightly?

**Comment by jplatte** [comment]
I've had a closer look. The root cause seems to be the `--MatrixChat_useCompactLayout_group-padding-top` variable not being defined. If I disable the `inset-block-start` CSS rule that references it, the badges show up again.

![Screenshot_2023-05-30_161919](https://github.com/vector-im/element-web/assets/951129/3400e3fa-fa6b-4c43-88b4-15ee9f0be93e)

**Comment by t3chguy** [comment]
Can confirm this is specific to `Use a more compact 'Modern' layout`

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9033

**Comment by Johennes** [comment]
@luixxiul are you available to try and fix this?

**Comment by t3chguy** [comment]
@Johennes there's already a linked PR which fixes this..?

**Comment by luixxiul** [comment]
@Johennes No problem at all. I will revisit the area to see whether it can be improved to avoid such a regression from happening again.

It should be possible, because the room list notification badge has nothing to do with `EventTile`! I will also try to create a E2E test.

**Comment by MonkeyBars3k** [comment]
Great job y'all!

**Comment by t3chguy** [comment]
@jplatte see release schedule in the topic of `#element-web:matrix.org`
