### ISSUE TITLE
Flaky Cypress test - `right panel behaves correctly`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25374]
### Steps to reproduce

1. Check recent test results, such as [this](https://cloud.cypress.io/projects/ppvnzg/runs/14028/overview/d21fc053-9dcc-4cf2-b58f-3ac898638ec3?roarHideRunsWithDiffGroupsAndTags=1) and [this](https://cloud.cypress.io/projects/ppvnzg/runs/14020/overview/25329d55-4ac0-4dca-9662-ecf774cc918d?roarHideRunsWithDiffGroupsAndTags=1)

#### What did you expect?

The test should successfully run on Cypress Cloud.

#### What happened instead?

The test failed on Cypress Cloud.

````
The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'getId')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the uncaught:exception event.

https://on.cypress.io/uncaught-exception-from-application

at TimelinePanel_TimelinePanel.sendReadReceipt (http://localhost:8080/bundles/efe1ac7cf3e920c1732a/element-web-app.js:41687:36) at TimelinePanel_TimelinePanel.sendReadReceipts (http://localhost:8080/bundles/efe1ac7cf3e920c1732a/element-web-app.js:41258:25) at TimelinePanel_TimelinePanel.updateReadReceiptOnUserActivity (http://localhost:8080/bundles/efe1ac7cf3e920c1732a/element-web-app.js:41609:18)
````

The test successfully runs on local Cypress.

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/commit/4e5687c454377d4fab092a5fdd0f8dd9a835348f ?

**Comment by luixxiul** [comment]
@weeman1337 could I ask you to check it if you have some time? https://github.com/matrix-org/matrix-react-sdk/pull/10864
