### ISSUE TITLE
Text inserted at incorrect position

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-web#25379]
### Steps to reproduce

1. Enable the rich text editor in labs
2. Create a bullet point containing a link
3. Create a new line and type something
4. Start a new line and create a bullet point containing some text
5. Within this new bullet point, change the cursor position
6. Backspace or type some text

[Screencast from 16-05-23 09:33:51.webm](https://github.com/vector-im/element-web/assets/4940864/863d4230-fb3e-41a2-9a92-3981e552ad38)

#### What did you expect?
Text is edited at the cursor position

#### What happened instead?
Text is edited one or two characters before the cursor position

### Operating system

Ubuntu

### Application version

Element Nightly version: 2023051401 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by alunturner** [comment]
There's something quite spectacularly wrong with the message html here. Following the steps above but only to the point where we have a link with a bullet point and some following text:
<img width="694" alt="Element_Nightly__3____aluntest0" src="https://github.com/vector-im/element-web/assets/56027671/60287827-6e46-4fa7-ae93-89e15035dc48">

Then send the message and inspect the body content:
<img width="727" alt="Element_Nightly__3____aluntest0" src="https://github.com/vector-im/element-web/assets/56027671/8ed3d5ba-2ba4-4098-9ab6-2718053c4c7c">

For some reason we have an empty `<a>` tag appended at the end of the last paragraph.

**Comment by jonnyandrew** [comment]
Ok, it sounds like we should move this issue over to the rich text editor project

**Comment by alunturner** [comment]
Manually transferred to https://github.com/matrix-org/matrix-rich-text-editor/issues/681

**Comment by jonnyandrew** [comment]
Reopening but note this is dependent on
- matrix-org/matrix-rich-text-editor#681
