### ISSUE TITLE
"Manually verify by text" does nothing

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#25375]
### Steps to reproduce

1. Click on your avatar in the timeline of some room which will open your profile on the right side of the screen
2. In the Security section you should be able to click on your Hydrogen session
3. Click "Manually Verify by Text"
4. Make sure the `Session ID` and `Session key` match what is shown in the Hydrogen settings
5. Click the green **Verify session** button which 
6. Notice that nothing seemed to happen except that the dialog was dismissed. The session still shows as unverified and going through the process over again has no effect.

1 | 2 | 3 | 4
--- | --- | --- | ---
![](https://user-images.githubusercontent.com/558581/172390388-915d7c20-3be5-43d0-b552-8443dd0cb74d.png) | ![](https://user-images.githubusercontent.com/558581/172389964-e170ce23-d5a4-4498-af01-454d431f1ba5.png) | ![](https://user-images.githubusercontent.com/558581/172389986-2ff02324-47bc-40b8-82de-d9e5cd1f0f41.png) | ![](https://user-images.githubusercontent.com/558581/172389993-f5c36c4f-5888-44fb-958d-28498bc68443.png)

(it's only possible to verify by text via the steps above because it's not in the session manager, see https://github.com/vector-im/element-web/issues/20273)

#### What did you expect?

My session would be become verified after I manually verified it. This used to work just fine.

It did work as expected when I tried from another Element Desktop session.

#### What happened instead?

No change and my sessions are still unverified. I don't even see a network request going out.

### Operating system

Manjaro Linux 22.1.1 (Arch-based)

### Browser information

Version 113.0.5672.92 

### URL for webapp

https://develop.element.io/

### Application version

Element version: 88c539534914-react-38c13509fd21-js-43160094019a Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by luixxiul** [comment]
I think I noticed the same issue when I tried to verify a session of Hydrogen.

**Comment by dt-zero** [comment]
For anybody wondering, a temporary workaround can be to start a local instance of an older element-web version, e.g. `sudo docker run --rm -p 80:80 vectorim/element-web:v1.11.13` and verify through that. I didn't bisect but I imagine this regressed at some point between that and current master. (as the bug also reproduces on the latest master version at the time of writing 945c0793b9fb791698bc6cd94f0e334cde8dc63c)

**Comment by kerryarchibald** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10671

**Comment by MadLittleMods** [comment]
Thanks for investigating and fixing @kerryarchibald :slightly_smiling_face:

**Comment by dannysemi** [comment]
Pretty sure this has regressed again. Trying to "manually verify by text" doesn't do anything when I click the button in the web ui. It doesn't even dismiss the message. I loaded up an older image (1.11.55) and it worked just fine.

**Comment by MrConorAE** [comment]
Yep, it's definitely regressed. Trying to click it prints this message to the console, if that helps:
```Uncaught Error: End-to-end encryption disabled
    checkKeyBackup (client.ts:3385)
    setDeviceVerified (client.ts:2496)
    i (ManualDeviceKeyVerificationDialog.tsx:45)
    d (QuestionDialog.tsx:54)
    > React (11 collapsed messages)
    unstable_runWithPriority (scheduler.production.min.js:18)
    > React (3 collapsed messages)
client.ts:3385:18
```

**Comment by kr428** [comment]
This seems still an issue I see. Is there any way to work around this, currently?

**Comment by worldowner** [comment]
Shouldn't this issue be re-opened? Clearly the issue reappeared.

**Comment by t3chguy** [comment]
@worldowner https://github.com/element-hq/element-web/issues/27201

**Comment by worldowner** [comment]
Thank you for clarification. I didn't encounter the issue you've mentioned when I was browsing bug reports.

**Comment by F-Node-Karlsruhe** [comment]
This issue started for us when we enabled SSO on the matrix server with oidc.

**Comment by Cnly** [comment]
Still seeing this with Element Nightly. Currently there seems to be no way to verify a device controlled by Maubot. This issue should be reopened.
