### ISSUE TITLE
Excessive calls to `GET /relations` and `GET /event`, with MSC3981 enabled and working

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25395]
### Steps to reproduce

1. Restart app
2. Click around a couple rooms
3. Enjoy the flood of http requests

#### What did you expect?

For the app to start up quickly, quietly (this bug causes my CPU fans to be fast-moving), and without duplicating requests.

#### What happened instead?

There's tens of thousands of requests, so haven't identified a pattern yet. A few example URLs are:
* `https://t2l.io/_matrix/client/v1/rooms/!REDACTED:matrix.org/relations/$REDACTED/m.replace/m.room.encrypted?limit=1`
* `https://t2l.io/_matrix/client/v1/rooms/!REDACTED:element.io/relations/$REDACTED/m.replace/m.room.encrypted?limit=1`
* `https://t2l.io/_matrix/client/r0/rooms/!REDACTED:element.io/event/$REDACTED`
* etc

Specifically on the `GET /event` calls, many appear to be duplicated:
![image](https://github.com/vector-im/element-web/assets/1190097/8769eac0-b5fd-44bc-a414-ed8e8e23c832)

I was told ages ago that MSC3981 would fix this, but it hasn't (or the scope of the MSC changed between 6 months ago and now).

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023051701 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
This can cause `/sync` to be suffocated of resources, making it impossible to actually keep up to date for upwards of 30-40 minutes (in my case)

**Comment by clokep** [comment]
> I was told ages ago that MSC3981 would fix this, but it hasn't (or the scope of the MSC changed between 6 months ago and now).

I thought [MSC3925](https://github.com/matrix-org/matrix-spec-proposals/pull/3925) was meant to fix this, not [MSC3981](https://github.com/matrix-org/matrix-spec-proposals/pull/3981)?

**Comment by turt2live** [comment]
I've just turned on MSC3981 support, and while it's reduced a lot of the `/relations` spam, I'm still seeing *plenty* of duplicated requests for `GET /event`.

**Comment by turt2live** [comment]
I spoke too soon: it's now spamming `/relations` too (same request as before).

**Comment by justjanne** [comment]
The implementation of MSC 3981 in element-web was actually slightly faulty, as it still did the old-style /relations requests (though ignored the results). This should be fixed now.

**Comment by turt2live** [comment]
`/relations` is indeed fixed (assuming server support is advertised). `GET /event` is 64% of all requests my client makes, though (as I understand it though, the `/relations` fix wouldn't have fixed this particular one).

**Comment by andybalaam** [comment]
@turt2live I assume your server supports MSC3981? Element Web won't use it unless the server advertises support for it.

**Comment by turt2live** [comment]
Yes, enabling MSC3981 support stopped the `/relations` spam, per above.

**Comment by richvdh** [comment]
> Excessive calls to GET /relations and GET /event, with **MSC3981 enabled and working** [my emphasis]
> Yes, enabling MSC3981 support stopped the /relations spam, per above.

These two statements seem to be in conflict. Which is correct?

In any case, I experienced much the same (cf #25705), and it doesn't seem to be making a `/relations` request for every event in the thread, so how would MSC3981 help?

**Comment by richvdh** [comment]
I think this is mis-triaged. It's basically a show-stopping DoS which happens every time you reload the app.

**Comment by Johennes** [comment]
The `/event` calls might stem from https://github.com/matrix-org/matrix-js-sdk/pull/3427/ which compensates for the absence of server-side support for https://github.com/matrix-org/matrix-spec-proposals/pull/4023.

**Comment by richvdh** [comment]
Even if we have to compensate for lack of a server-side feature, can we do so in a way that doesn't require requesting the *same event* hundreds of times?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/3530 was a dropped attempt at resolving this

**Comment by Johennes** [comment]
@t3chguy you said in chat earlier that you don't think this stems from https://github.com/matrix-org/matrix-js-sdk/pull/3427. I didn't fully understand what you meant by the following though:

> That's the behaviour of constructing a thread without the necessary MSCs iirc

Could you expand on that?

**Comment by t3chguy** [comment]
@Johennes when constructing a Thread object, we use `fetchRoomEvent` (`/event/` API) to load the event if it isn't already locally known. I may have been mistaken wrt to any relation to MSCs here, it may be unavoidable.

**Comment by Johennes** [comment]
@t3chguy and I discussed some more in DM. The O- and S- levels put this below what the WAT would pick up as a fire currently. However, there is uncertainty about whether or not this is a recent regression. @t3chguy will try to do a time-boxed investigation into this tomorrow to help inform further decisions.

**Comment by turt2live** [comment]
tbh, if the fix were a promise cache on `getEvent`, I'd consider this fixed enough for now. I wouldn't expect that to take much more than a day (week with review).
