### ISSUE TITLE
Unread counts don't clear after viewing room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25399]
### Steps to reproduce

1. Receive a few messages, at least one in a thread (not sure if this happens in rooms without threads)
2. Open room
3. Read room and read threads

#### What did you expect?
When I look at the room and the unread thread, the unread count in the left panel clears

#### What happened instead?
The unread count in the left panel seems to be stuck

This has been going on at least since yesterday, possibly the day before

### Operating system

Arch Linux

### Browser information

Chromium 113.0.5672.92 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 0a5173f25802-react-9f574cc764e5-js-a7b1dcaf9514 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/24392
