### ISSUE TITLE
OIDC: Sign up

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25393]
Support sign-up via native OIDC in Element Web. Refer to https://areweoidcyet.com/client-implementation-guide/ for guidance. (You will need to find out what OIDC is before you can understand it.)

You will almost certainly need to break this story up into smaller parts before implementing it.

Below, we assume that https://github.com/vector-im/element-web/issues/25392 is already done.

Currently, Element Web only supports signing up for Matrix-based authorisation.

This task is use the information about whether the homeserver supports OIDC to decide whether to offer sign-up via that, and then to send the user to the OIDC web UI for sign-up if the user so chooses.

TODO: should we also offer legacy sign-up, or do we ONLY offer OIDC if it's available?

<img width="719" alt="Screenshot 2023-10-09 at 15 20 24" src="https://github.com/vector-im/element-web/assets/3055605/606bbdf4-23fd-40e1-ba09-f4c1f59e7a24">

1. Do not query for registration methods/show error
2. Use OIDC discovery openid-configuration, check for `create` in `prompt_values_supported`
3. Where supported, add a register button that starts an OIDC auth flow with `prompt=create`

**Comment by kerryarchibald** [comment]
<img width="719" alt="Screenshot 2023-10-09 at 15 20 24" src="https://github.com/vector-im/element-web/assets/3055605/606bbdf4-23fd-40e1-ba09-f4c1f59e7a24">

1. Do not query for registration methods/show error
2. Use OIDC discovery openid-configuration, check for `create` in `prompt_values_supported`
3. Where supported, add a register button that starts an OIDC auth flow with `prompt=create`
