### ISSUE TITLE
Percy test ` User settings tab - Preferences` and ` User settings tab - General` no longer capture all of the setting flags on the tab

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25391]
### Steps to reproduce

1. Check https://percy.io/dfde73bd/matrix-react-sdk/builds/27461110/changed/1527545851

#### What did you expect?

`mx_SettingsTab` should be captured.

![](https://images.percy.io/d2999ad899ea1408e6c2d2dbbeb57b13b52189e02f9bb39c64c46d72f4f64dd5)

#### What happened instead?

The dialog was captured instead.

![](https://images.percy.io/60ff6007953c00d18115c37bcf562cc67d2f07bae9a6da6c5b61c1ed544af573)

### Will you send logs?

No

**Comment by luixxiul** [comment]
The same thing started to be observed for the General tab: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$rr0aLusnMWWsEdvcRCZA9i6MNtXVKyOnlGlSdWBr7Ew?via=matrix.org&via=element.io&via=envs.net

**Comment by kerryarchibald** [comment]
`cy.findByTestId` and `percySnapshotElement` do not play together.
`percySnapshotElement` uses jquery `element.selector` as the scope. When chained with a `cy.get` this is a selector and works fine, but for `findByTestId` is eg `findByTestId(<testid>)`
