### ISSUE TITLE
Security Verify section reappeared on Percy test

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25409]
### Steps to reproduce

1. Check https://percy.io/dfde73bd/matrix-react-sdk/builds/27537204/changed/1532012807, https://percy.io/dfde73bd/matrix-react-sdk/builds/27576649/changed/1534003776

#### What did you expect?

Security Verify section reappeared on Percy test. It should be checked if it is expected.

### Will you send logs?

No

**Comment by andybalaam** [comment]
I think this might be flaking.

**Comment by richvdh** [comment]
doesn't seem to have happened since? Shall we close?

**Comment by t3chguy** [comment]
It did flake last week, https://github.com/matrix-org/matrix-react-sdk/pull/11399 should fix it
