### ISSUE TITLE
Change default generated room icons to not require canvas access

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [vector-im/element-web#25404]
#### What would you like to do?
Have default character based generated room icons to render without access to canvas in my web browser.
#### Why would you like to do it?
If using a browser with disabled canvas access for privacy reasons, icons become broken when canvas access is not explicitly granted each time.

![Broken Icons](https://github.com/vector-im/element-web/assets/71072643/f5acf71c-3566-47d3-8cae-c63d3380e0e0)

#### How would you like to achieve it?
This could be implemented similarly as in other messaging applications. [Telegram Web](https://web.telegram.org) does not suffer this issue for instance.

### Have you considered any alternatives?

You can explicitly grant canvas access, provided that you have such prompts enabled in Firefox. However, you have to do this every single time you log in to Element Web through your web browser and the page has to be refreshed manually for it to take effect.

![Canvas Prompt](https://github.com/vector-im/element-web/assets/71072643/7abc2fa4-bcf7-42aa-8822-bf73e94b6438)

### Additional context

Do note that with hardened configurations in Firefox. The “Remember this decision” button is redundant. The browser will forget this choice after a restart. This is a Firefox issue, unrelated to Element. Nevertheless, messing with canvas options can be avoided completely using a different implementation.

Another important thing is that the canvas prompt only pops up when the user explicitly clicks on the icon in the URL bar. Users with pre-configured hardened Firefox forks might be completely unaware of such an option, resulting in broken icons across the service, which they might consider a bug.

I believe such steps are unnecessary and overall this should be implemented in a way that allows users with hardened browsers to have all work properly. To clarify, I understand that browsers with 90% of features disabled for “privacy reasons” will break any service eventually. Nonetheless, like I mentioned, other messaging services deal with this issue, and I'd like Element Web to do the same.

**Comment by t3chguy** [comment]
The reason it is done in canvas is to allow it to be configurable (custom themes) yet still fed to the Notifications API which has to take an image url. Plus we need canvas for other things like thumbnail generation so it is unlikely that a stance of avoiding canvas will fly

**Comment by andybalaam** [comment]
Since we currently can't see a way around this problem, closing this issue for now. If we can think of a way of achieving what we need to do, we can re-open.
