### ISSUE TITLE
Stuck Notification Example

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-web#25402]
### Steps to reproduce

DM chat, I am up to date on reading the chat but the room consistently has a 1 unread message badge in the room list. 

It only affects a single room and I can't see an obvious trigger. 

#### What did you expect?
When I read the DM I expect the notification to go away

#### What happened instead?
The notification persists

### Operating system

macOS

### Application version

ElementNightly/20230517

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/24392
