### ISSUE TITLE
Devices without encryption support showing as unverified in "Security & Privacy"

### ISSUE THREAD

**Issue by westerguard** [vector-im/element-web#25413]
### Steps to reproduce

When you setup double puppeting for for instance the Mautrix Telegram Bridge, the session shows up as unverified in the old and the new session manager, also see the printscreen below.

![image](https://github.com/vector-im/element-web/assets/92873680/fb023711-3e8f-4515-bd6d-652cb4a0d4c2)

### Outcome

I asked about this in the Mautrix-Telegram-Bridge room, and this shouldn't be the case, because it doesn't need encryption and it doesn't affect anything else. 
And to quote Tulir: "actually might be a regression, I think there used to be a separate 'Devices without encryption support' section". 

It also affects Element Android (don't know if you need a separate issue for Android).

### Application version

Element version: 1.11.31 Olm version: 3.2.14

### Homeserver

Synapse 1.83.0

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/70b87f8bde7323949ac1dd5417cf5795f1e02a98

**Comment by kerryarchibald** [comment]
It's expected in new session manager for sessions that do not support encryption to be displayed as unverified, but they have an 'unverifiable' status under the hood and should not display the option to verify:
<img width="677" alt="Screenshot 2023-05-22 at 11 24 47" src="https://github.com/vector-im/element-web/assets/3055605/1fc8cec6-d0b7-4b5c-8ff3-dd293f184b84">

**Comment by westerguard** [comment]
Oh, well, mine does show the Verify session button.

![image](https://github.com/vector-im/element-web/assets/92873680/5ef51695-4772-40ee-a7c7-bb63c4e93853)

But even without this button, I feel like a red warning shield for a bridge is not so great.
I get the idea, and technically it is the right way to show it, but I think that every 'normal' user will assume there's something wrong when they see a red shield. 
From the end-user's perspective, it think it's confusing.

**Comment by richvdh** [comment]
This regressed in the old device list (under "Security & Privacy") between Element 1.11.24 and 1.11.25

Before (EW 1.11.24):

![image](https://github.com/vector-im/element-web/assets/1389908/1caaa127-f371-4de6-8093-6dcda024cc60)

After (EW 1.11.25):

![image](https://github.com/vector-im/element-web/assets/1389908/a0014363-4889-43ae-afdf-8fea2f694723)


The *new* session manager regressed between EW 1.11.29 and 1.11.30.

Before (EW 1.11.29):

![image](https://github.com/vector-im/element-web/assets/1389908/26971ddc-6744-4b23-93d8-d26267afd122)

After (EW 1.11.30):

![image](https://github.com/vector-im/element-web/assets/1389908/e1c22633-1807-4e3a-9f55-6ac2caf391f9)

Note that the device without E2E support has *always* shown as an "unverified device"; as @westerguard points out that is arguably a bug, but it's not a regression and is a separate problem.

**Comment by richvdh** [comment]
The regression in the old device list was in matrix-org/matrix-react-sdk/#10200.
As @kerryarchibald notes, the regression in the new session manager was in https://github.com/matrix-org/matrix-react-sdk/pull/10594.

**Comment by richvdh** [comment]
Both PRs have the same issue, which is switching from a version from `isDeviceVerified` which returned `null` for devices with no keys to one which returns `false`.

It's also worth noting that both implementations were subsequently updated by matrix-org/matrix-react-sdk#10663, though that doesn't seem to have changed any behaviour here.
