### ISSUE TITLE
Cannot mark room as read.

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#25411]
### Steps to reproduce

Be in the room and mark it as read 100 times over....

#### What happened instead?
This room will not mark as read: !kLmEuMmrBeOizxKsjm:matrix.org
Has been going on for 1.5 days and all other rooms work with "mark as read"

### Operating system

Fedora 38

### Browser information

Vivaldi 5.1.2567.73 (Stable channel) stable (64-bit) 

### URL for webapp

develop.element.io

### Application version

Element version: 0a5173f25802-react-cc842aac8a0b-js-488390365a12 Olm version: 3.2.14

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by karlabbott** [comment]
Was caused by aggressive browser caching.

**Comment by karlabbott** [comment]
Actually, the room just came back as unread and won't let me mark it as read. Submitting logs now from:

Element version: 0a5173f25802-react-c6f44d305315-js-cd26ba67d4ac
Olm version: 3.2.14

**Comment by t3chguy** [comment]
@andybalaam / @weeman1337

**Comment by weeman1337** [comment]
@karlabbott  I would suggest to do a live debugging session the next time it happens and see if the correct receipts are sent.

**Comment by weeman1337** [comment]
Got a `caught (in promise) TypeError: Cannot read properties of undefined (reading 'getTs')` this morning when marking rooms as read.

**Comment by weeman1337** [comment]
```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'getTs')
    at Room.getLastLiveEvent (room.ts:812:65)
    at clearRoomNotification (notifications.ts:69:28)
    at onClick (RoomGeneralContextMenu.tsx:220:42)
    at Object.Rb (react-dom.production.min.js:52:315)
    at Xb (react-dom.production.min.js:52:468)
    at Yb (react-dom.production.min.js:53:32)
    at Ze (react-dom.production.min.js:100:68)
    at se (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Jb (react-dom.production.min.js:292:182)
```
