### ISSUE TITLE
`Apperance` tab's content overflows with a long display name

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25416]
### Steps to reproduce

1. Set your display name to a long one such as `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`
2. Open `Appearance` tab

#### What did you expect?

The tab's content should not overflow.

#### What happened instead?

It overflows.

![0](https://github.com/vector-im/element-web/assets/3362943/e8fb1859-10a2-400c-9f99-78db52ddcf50)

This is a regression by https://github.com/matrix-org/matrix-react-sdk/commit/b3b03e5dcb527df85fc93d2027f8c30f819df450 (https://github.com/matrix-org/matrix-react-sdk/pull/10827)

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10827
