### ISSUE TITLE
Quote Markdown does not work on the new Editor

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-web#25419]
### Steps to reproduce

1. Enabled the new rich text editor in labs
2. Go to compose a message but hide formatting(to enable markdown mode)
3. Type a message with quote markdown like "> test"

#### What did you expect?
This message should be rendered as a quote in the timeline

#### What happened instead?
This message was not rendered as a quote in the timeline

### Will you send logs?

Yes

**Comment by alunturner** [comment]
Fixed by https://github.com/matrix-org/matrix-rich-text-editor/pull/736
