### ISSUE TITLE
`Manage Integration` section on General user settings tab not aligned

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25426]
### Steps to reproduce

1. Open `General` user settings tab
2. Check `Manage integrations` section

#### What did you expect?

The section should be aligned.

#### What happened instead?

It is not aligned.

![Screenshot from 2023-05-23 21-32-27](https://github.com/vector-im/element-web/assets/3362943/3ad93880-6c16-4dbd-bdbe-f4a0160fc829)

### Operating system

Debian

### Browser information

Firefox

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Part of https://github.com/vector-im/element-web/issues/24922
