### ISSUE TITLE
Stuck notifications due to unread threads not updating rapidly.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#25420]
### Steps to reproduce

1. Spot a room with a high unread count
2. View it, and spot that the unread count doesn't zero
3. Open the thread panel and observe that the unread count is due to unread messages in the two most recent threads in the room.
4. View the older of the two threads; read count immediately drops by the number of unread messages in that thread.
5. View the newer thread; read count doesn't update.
6. Wonder what's going on; are the unread messages on another thread? New messages on the timeline? Or just flakiness?  Check that you're scrolled to the bottom of the thread (you are).
7. Go back to the thread index and see the most recent thread is still marked as unread, despite having you just been in there reading it.
8. At some point later (could be 30s, could be 5s) the badge suddenly disappears.  Unclear what the trigger is (could it be a local echo issue? or the user having to do some other interaction to nudge the app into considering the thread read? or is it a falsey bug where the zero'd count doesn't get picked up rapidly?)

So far i've repro'd this 3 out of 3 times today.

#### What did you expect?

Notif counts to instantly update as you read things in the app

#### What happened instead?

A perception of confused flakiness due to a mix of rapid and super-slow updating of the notif counts.

### Operating system

macOS

### Application version

Element Nightly version: 2023052201
Olm version: 3.2.14

### How did you install the app?

Nightly

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is believed to be fixed by the multiple rounds of work over the past month or two, there were multiple bugs relating to read receipts in threads which caused stuck unreads. If you spot this again please send screenshot of debug notifications devtool along with your rageshake
