### ISSUE TITLE
unable to disconnect user from matrix-network / bridge

### ISSUE THREAD

**Issue by saibug** [vector-im/element-web#25432]
### Steps to reproduce

logged out/in 

### Outcome

I'm unable to disconnect user from matrix, 
recently i have added bridge to irc, and register username from matrix . 

So now, i can't disconnect this account, and when i tried from libera, that tells me the user already used , messages are sent from two user :

Nick:matrix
Nick:libera 

### Operating system

linux

### Will you send logs?

No

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-appservice-irc is the project for the IRC bridge
