### ISSUE TITLE
Font weight of widget permission UI text has become bolder

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25438]
### Steps to reproduce

1. Open a room
2. Have another user add a widget to the room
3. Open the widget

#### What did you expect?

The font weight of the text on the widget should be set to normal, other than the heading text.

![1](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/cd97de47-8228-4e28-8e90-fc1b744b059a)

#### What happened instead?

The font weight of the all lines was set to bold.

![0](https://github.com/matrix-org/matrix-react-sdk/assets/3362943/79ba5ffa-debc-4712-9639-667996a76a27)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by weeman1337** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10939
