### ISSUE TITLE
Update notification settings for intentional mentions

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#25434]
### Your use case

For https://github.com/vector-im/element-web/issues/25267

Update notification setting bindings to use new rules from MSC3952 in mentions rules where server support exists.

#### AC

- When intentional mentions is not supported (<v1.7) no change to push rules.
- When intentional mentions is supported (>=v1.7), mentions notifications settings should toggle both new MSC3952 rules and older [deprecated](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3952-intentional-mentions.md#backwards-compatibility) [.m.rule.contains_display_name](https://spec.matrix.org/v1.5/client-server-api/#default-override-rules), [.m.rule.contains_user_name](https://spec.matrix.org/v1.5/client-server-api/#default-content-rules), and [.m.rule.roomnotif](https://spec.matrix.org/v1.5/client-server-api/#default-override-rules)
MSC3952 rules should be the master rule, with deprecated rules kept in sync. (this can be achieved by adding [`syncedRuleIds`](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/notifications/VectorPushRulesDefinitions.ts#L36) in push rule definitions)*
- Synced rules are not *forced* into sync, if rules are set out-of-sync by another client, EW should not change their values until the user explicitly syncs or changes the setting. (`syncedRuleIds` behaviour will need to be updated, see `monitorSyncedPushRules`)
- When rules are out of sync notify the user in notification settings with a message attached to the relevant rule
<img width="539" alt="Screenshot 2023-05-25 at 15 31 39" src="https://github.com/vector-im/element-web/assets/3055605/3788c2d1-2c18-4cb3-ad16-4198adcc5501">
- The rule is displayed at the 'loudest' value of any of the synced rules. If `.m.rule.roomnotif` is set to On, and `.m.rule.is_room_mention` is set to Noisy - the room mentions settings should display 'Noisy' with a notice about out of sync rules.

| description | master rule | syncedRules |
|--|--|--|
|Notify when someone mentions using @room |`.m.rule.is_room_mention` | `.m.rule.roomnotif`|
| Notify when someone mentions using @displayname or @MXID| `.m.rule.is_user_mention` | `.m.rule.contains_display_name`, `.m.rule.contains_user_name`|

### Additional context

Existing UI:
<img width="652" alt="Screenshot 2023-05-24 at 14 12 31" src="https://github.com/vector-im/element-web/assets/3055605/b4bb8dca-e761-4362-bb4a-47970487177e">

New settings UI uses different language for mention settings:
<img width="681" alt="Screenshot 2023-05-24 at 14 15 35" src="https://github.com/vector-im/element-web/assets/3055605/16328f51-d634-4c7d-9e2d-c315619de535">
https://github.com/vector-im/element-web/issues/24567

**Comment by t3chguy** [comment]
> EW checks push rules on launch and changes to m.push_rules and updates any out of sync rules.

This sounds like it has the potential to continually undo users' actions from different clients? Sure they'd be wanting a weird combination of rules but inherently this feels wrong

**Comment by kerryarchibald** [comment]
@t3chguy Now that I think about it, I'm not sure when intentional mentions support is coming to mobile so even within Element's ecosystem this would break mentions settings.

**Comment by kerryarchibald** [comment]
Updated the AC with:
> - Synced rules are not *forced* into sync, if rules are set out-of-sync by another client, EW should not change their values until the user explicitly syncs or changes the setting. (`syncedRuleIds` behaviour will need to be updated, see `monitorSyncedPushRules`)
> - When rules are out of sync notify the user in notification settings with a message attached to the relevant rule
eg:
<img width="539" alt="Screenshot 2023-05-25 at 15 31 39" src="https://github.com/vector-im/element-web/assets/3055605/3788c2d1-2c18-4cb3-ad16-4198adcc5501">

@daniellekirkwood what do you think?
The situation is:
1. I turn on @room mentions in EW, this sets `.m.rule.is_room_mention` and `.m.rule.roomnotif` to ON
2. On my phone running old Element ios I turn @room mentions off, this only sets `.m.rule.roomnotif` to OFF
3. Open notification settings on EW, how should the @room mention setting toggle display?

**Comment by giomfo** [comment]
@kerryarchibald @daniellekirkwood From my point of view, EW should display ON the @room mention toggle as soon as one of the 2 push rules is ON. Because the user will observe some @room mention on EW then (only a part of them if one of the rule is OFF)

**Comment by daniellekirkwood** [comment]
> Synced rules are not forced into sync, if rules are set out-of-sync by another client, EW should not change their values until the user explicitly syncs or changes the setting. 

Agree

> When rules are out of sync notify the user in notification settings with a message attached to the relevant rule

this will need design input - i think we were thinking of having a banner at the top of the page... but also having an 'error' message next to the switch works also. I'm happy to commit to the suggestion here and raise an 'enhancement' to update the design or copy if needed in the future.

> "Open notification settings on EW, how should the @room mention setting toggle display?"

If the mobile legacy clients integrate with the MSC then this would not be a problem? If yes, then the other clients that need to catch up with this MSC will also be in this state until they add support for it. While we're in this middle-phase I think I'd rather have too many notifications and err on the side of caution here so if _one_ of the push rules is set to ON then EW shows ON but with the warning message pictured there... ? Have I understood the question correctly, WDYT?

**Comment by kerryarchibald** [comment]
Given the extent of Janne's changes to the Notifications screen, I think it would be cleanest to wait for that to land/stabilise a bit more before implementing this.

**Comment by Johennes** [comment]
Spoke to @justjanne and it looks like she already included this work in her ongoing branch

**Comment by justjanne** [comment]
The UI sets the intentional mentions rules correctly and as expected in my tests with our beta server and an element-web build based off the latest develop. I'll close this ticket as completed, if you find issues with this please file them separately (though feel free to link this issue to them)
