### ISSUE TITLE
List items on dropdown menu on Session manager have discs

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25448]
### Steps to reproduce

1. Open Session manager
2. Click `Show: All` of "Other sessions" to display the dropdown

#### What did you expect?

The list on the dropdown menu should not add discs for items

#### What happened instead?

The items have discs as below:

![0](https://github.com/vector-im/element-web/assets/3362943/00803a8b-7504-45c5-bcf6-26d7c50a7cee)

### Application version

Element version: 1.11.31 Olm version: 3.2.14

### Will you send logs?

No

**Comment by justjanne** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/782060a2 replacing the `div` elements with `ul`/`li` without also updating the CSS.

**Comment by t3chguy** [comment]
Not a blocker for the current RC
