### ISSUE TITLE
OIDC: Kicked out

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25443]
When logged in using OIDC, handle and display to the user when our session has been remotely signed out, or is otherwise permanently logged out e.g. because of token expiration.

Refer to https://areweoidcyet.com/client-implementation-guide/ for more info.

**Comment by weeman1337** [comment]
@andybalaam can you triage this issue? I don't really know what to do with it.

**Comment by kerryarchibald** [comment]
this Just Works. The server does not respond with a `soft_logout` as is the case with token expiration from server issued tokens.

Related https://github.com/vector-im/element-web/issues/25957
