### ISSUE TITLE
OIDC: Account settings

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25445]
When our login is done via OIDC, we should offer a link to the OIDC server's account admin page.

TODO: is this instead of our own device management page (and any other account settings pages), or as well as?

**Comment by kerryarchibald** [comment]
We already add this Account section to settings for clients using MSC2965 delegated auth:
<img width="887" alt="Screenshot 2023-05-26 at 14 20 41" src="https://github.com/vector-im/element-web/assets/3055605/f280a2d5-5e72-402c-ad21-6c7ea1a11912">

We still need device management to handle device verification.
We could add similar links to session manager, something like:
<img width="532" alt="Screenshot 2023-05-26 at 14 17 57" src="https://github.com/vector-im/element-web/assets/3055605/a107746b-8a90-4c76-9228-009d3f5ef4c8">

**Comment by weeman1337** [comment]
@andybalaam can you triage this issue? I don't really know what to do with it.

**Comment by kerryarchibald** [comment]
Closed by 
https://github.com/matrix-org/matrix-react-sdk/pull/11432
https://github.com/matrix-org/matrix-react-sdk/pull/11431
