### ISSUE TITLE
Space invite dialog displays `Click to copy` next to `Share invite link`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25458]
### Steps to reproduce

1. Create a Space
2. Click `Invite` button on the Space home

#### What did you expect?

[The invite link click area](https://github.com/matrix-org/matrix-react-sdk/blob/3bba816b105b00c11cffbbd76fe0e41af97da34d/src/components/views/spaces/SpacePublicShare.tsx#L42-L53) should be properly designed.

#### What happened instead?

It looks broken.

![Screenshot from 2023-05-28 03-03-47](https://github.com/vector-im/element-web/assets/3362943/65e8b21c-eb89-4a2d-a20e-e2095c8697f1)

### Operating system

Debian

### Browser information

Firefox

### Application version

Element version: 1.11.31 Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
And the v-align of the icon is broken too, affects RC

<img width="574" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/d98b16aa-14f8-4008-bcaf-b30e23474ebe">
