### ISSUE TITLE
Use compound icons for close, cancel, or delete buttons

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25457]
#### What would you like to do?

Use compound icons (`close-8px.svg` and `close-16px.svg`?) for close, cancel, and delete buttons to make their design consistent, increasing maintainability.

#### Why would you like to do it?

Currently there are multiple close icons under `res/img`:

- `cancel.svg`
- `cancel-small.svg`
- `icon-address-delete.svg`
- `icon-pill-remove.svg`
- `icon_context_delete.svg`
- `icons-close.svg`
- `element-icons/cancel-rounded.svg`
- `element-icons/x-8px.svg`
- `emojipicker/delete.svg`
- `feather-customised/x.svg`
- `image-view/close.svg`

![0](https://github.com/vector-im/element-web/assets/3362943/34ef2355-61c5-4b7c-b690-c75da0766666)

#### How would you like to achieve it?

Except `cancel-rounded.svg` which has rounded ends, they should be replaced with the compound icons, adjusting values such as color and size for each case.

### Additional context

I think that a close icon with rounded ends like `cancel-rounded.svg` should be added to the compound icons.

**Comment by weeman1337** [comment]
@luixxiul thank you for opening the issue. I would recommend to wait for the rollout of the compound design for Element Web. You can find the current compound [here](https://github.com/vector-im/compound). We are getting closer to design compound in Element Web.

The introduction of `close-8px.svg` etc. was only a stopgap until compound is available in Element Web. All icon files should be replaced by using the compound icons.

**Comment by luixxiul** [comment]
Thanks for the comment, but I assume I will not work on that area as I could not see transparency of development work related to Compound stuff.

**Comment by weeman1337** [comment]
> Thanks for the comment, but I assume I will not work on that area as I could not see transparency of development work related to Compound stuff.

Then we should create transparency :slightly_smiling_face: Compound work should be tracked here https://github.com/vector-im/compound .

I've asked Germain to create an issue to follow the integration in Element Web.

**Comment by luixxiul** [comment]
For reference, this is the start of the chat on the theme: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$AmKxrQlH7bTP07CtDqy1wvlR5lnzQQsrVvSpKu-cdeI?via=matrix.org&via=element.io&via=envs.net

And this is the reply to the message: https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$ZuFFWO0XqI_ZuoAxn7Wc0DA6qpaNHwmy511u6fYQWjQ?via=matrix.org&via=element.io&via=envs.net

**Comment by luixxiul** [comment]
closing in favor of https://github.com/vector-im/element-web/issues/25476
