### ISSUE TITLE
Room settings > profile settings not aligned with address settings area

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25455]
### Steps to reproduce

1. Open Room settings tab

#### What did you expect?

Profile settings area should be aligned with address settings area.

On 1.11.31:

![0](https://github.com/vector-im/element-web/assets/3362943/4abcb790-7dc0-4a64-af73-78feae27799b)

#### What happened instead?

They are not aligned.

![Screenshot from 2023-05-26 23-34-15](https://github.com/vector-im/element-web/assets/3362943/c7f73b08-207c-412f-a6d9-2041d93a1271)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Part of https://github.com/vector-im/element-web/issues/24922
https://github.com/matrix-org/matrix-react-sdk/pull/10973
