### ISSUE TITLE
custom changes on the front end codebase, how to make custom changes in UI code

### ISSUE THREAD

**Issue by prncdev** [vector-im/element-web#25459]
### Steps to reproduce

Hello everyone, I hope you all are doing well.
I want to that how can I make custom changes on the front end of the Matrix Element Web app I have cloned the element-web repo and matrix-js-sdk and matrix-react-sdk too, but I am not sure how I can change the frontend UI of Element-web please help me to understand the folder and file structure of the app? I want to make the UI responsive for mobile views, I am very new to the Matrix Element web app project. please tell me where to start I can't even find the public folder and main Reac,t app component entry point where all other components of the app are connected.
Thank you.

### Will you send logs?

Yes

**Comment by seshubonam** [comment]
+ 1

**Comment by t3chguy** [comment]
This is a bug tracker not a support page. 

Follow https://github.com/vector-im/element-web#setting-up-a-dev-environment

Most of the UI code is in https://github.com/matrix-org/matrix-react-sdk
Most of the low level Matrix code is in https://github.com/matrix-org/matrix-js-sdk

https://github.com/vector-im/element-web#development has a link on where to get help
