### ISSUE TITLE
Spacing between rows around the theme switcher on `Appearance` user settings tab is not consistent

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25460]
### Steps to reproduce

1. Open `Appearance` user settings tab

#### What did you expect?

Consistent spacing between rows around the theme switcher.

#### What happened instead?

The spacing between the rows is not consistent:

![1_1](https://github.com/vector-im/element-web/assets/3362943/e797e506-e7df-4a9e-aca8-06427b64c01c)

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by manancodes** [comment]
Is it the spacing inside the `Light` and `Dark` radio selectors?

**Comment by manancodes** [comment]
The space inside the theme selectors needed some alignment, I have created a PR for that.

Do you think the spacing between the "**Match system theme**" and the selectors should also change?

Current UI:
<img width="616" alt="Before" src="https://github.com/vector-im/element-web/assets/54790263/e8053ea2-9e36-40e3-b931-284d5e0c4071">

Proposed UI:
<img width="633" alt="After" src="https://github.com/vector-im/element-web/assets/54790263/187433e7-164f-417d-b454-aea205cbc4d2">
