### ISSUE TITLE
Almost all messages are gone. "Can't load this message (m.room.message)"

### ISSUE THREAD

**Issue by D1rektX** [vector-im/element-web#25474]
### Steps to reproduce

Happens when I use the Web version aswell. 
Just happened that almost all my messages are gone and new ones wont show load aswell.

#### What did you expect?
Expect to see messages.
#### What happened instead?
Every chat and conversation only shows "Can't load this message (m.room.message)"
![image](https://github.com/vector-im/element-web/assets/14914428/39459493-46bc-4316-9678-48c8beb00925)

### Operating system

Windows 10

### Application version

Version von Element: 1.11.31 Version von Olm: 3.2.14

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is related to one of your push rules/keywords creating an invalid regex
