### ISSUE TITLE
Room stuck as unread despite all messages/threads marked as read (to my knowledge)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25481]
### Steps to reproduce

Unclear

#### What did you expect?

No stuck notifications.

#### What happened instead?

See rageshake. The threads list icon indicated that there weren't any unread threads, and I've read all messages in the main timeline to my knowledge. Still have a stuck notification.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023053001 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by turt2live** [comment]
Sending a message to the main timeline fixed this case for me.

**Comment by weeman1337** [comment]
Added to the stuck notifications epic for investigation.

**Comment by audunmb** [comment]
I have this as well. I left click and mark the room as read, still shows as unread. I open all threads and place the marker in the reply field below, to make sure that the thread is marked as read. Still it shows as unread.

**Comment by Standard8** [comment]
I also have this on a room and I've just sent logs for it.

Interestingly if I use the Element mobile app for the room, the room there shows as unread, but if I try and go into the threads view, then I get "RealmList does not accept null values", which is an error that can't be cleared.

**Comment by Standard8** [comment]
One possible step to repeat:

* Have a room that you're subscribed to that receives a new message and thread.
* View the room but not the thread.
* Mark the room as read.
* View the thread.
* Close the thread view.

At this stage, you're now stuck in the unread state.

I've just sent debug logs for this.

**Comment by oliverguenther** [comment]
This happens to me as well on a daily basis using Element on Mac and Linux (Version 1.11.35 both cases)

**Comment by t3chguy** [comment]
Believed to be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3600
