### ISSUE TITLE
Confetti drops from the top almost every time I open the NV internal room after a relaunch of the app

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25489]
### Steps to reproduce

1. Open NV internal room
2. Mark it as read
3. Open another room
4. Exit and relaunch Element Desktop
5. Open NV internal room
6. Notice how part of the timeline at the top remains white as missing events are loaded
7. Notice how confetti drops from the top once the timeline is filled

#### What did you expect?

No confetti since I had already seen it

#### What happened instead?

Confetti

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Looks like https://github.com/vector-im/element-web/issues/24811

**Comment by Johennes** [comment]
Ah, thanks for locating that one. That means this issue already existed before the receipt fixes. So while that's not great, we don't have to block the RC / release on it.

**Comment by Johennes** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/24811
