### ISSUE TITLE
IRC messages don't appear

### ISSUE THREAD

**Issue by ApostolosB** [vector-im/element-web#25490]
### Steps to reproduce

Go to a channel that uses a bridge between matrix and irc. 
Post a comment in IRC
You wont see anything in matrix
Posting a comment on matrix makes it appear on IRC

Started happening 2-3 days ago.

#### What did you expect?
Messages to appear between the bridged channels

#### What happened instead?

No messages appear

### Operating system

LInux

### Browser information

Firefox latest stable

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hi @ApostolosB . Thank you for reporting the issue.

This issue tracker is for Element Web issues only. You should report the problem to your Matrix ↔ IRC Bridge provider.

**Comment by ApostolosB** [comment]
@weeman1337 i contacted the bridge people (#libera-matrix on irc) and say its on the matrix side of things. Thay also said they tried to contat support@matrix.org but no answer.

Anything i can do?
