### ISSUE TITLE
"Permission denied" errors during signup

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2549]
Weird description of signup failures when using email addresses at: https://twitter.com/jotbe/status/795036135118479364

Seems to work okay for me; unclear what's wrong.

**Comment by ara4n** [comment]
assigning to @dbkr in case his grand signup refactor sheds light on this

**Comment by kittykat** [comment]
Closing as it's an old issue without a confirmation that it's still reproducible. If it still happens, please reopen.
