### ISSUE TITLE
Intentional Mentions Testing: Editing a message caused an extra ping

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25496]
### Steps to reproduce

During testing for the new intentional mentions MSC we found that editing a message with someone tagged in it cause an extra ping and it shouldn't have.

We found this in an encrypted room but have a suspicion that the same thing happens in an unencrypted room (notifications are just handled differently there).

To reproduce: 
- Enable intentional mentions on two accounts (both @clokep and @daniellekirkwood can help here if needed)
- Send a message from account A to a room, in this message tag account B 
- Account B should receive a red highlight ping
- Use Account A to edit the message 
- Account B should not get another ping (but does)

### Will you send logs?

Yes

**Comment by kerryarchibald** [comment]
Closed by https://github.com/matrix-org/matrix-js-sdk/pull/3445
