### ISSUE TITLE
Implement MSC4023 in matrix-js-sdk

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25494]

**Comment by Johennes** [comment]
@t3chguy looking at the diff in https://github.com/matrix-org/matrix-js-sdk/pull/3427, I think this should actually already be covered by that PR?

**Comment by t3chguy** [comment]
@Johennes yes that PR implements the unstable identifiers for the MSC, along with a fallback to handle (at a perf hit) compatibility with servers lacking that feature (all of them right now)
