### ISSUE TITLE
Add hint, help, or tooltip to explain `Security Key`, `E2E room key`, and `encryption keys`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25509]
#### What would you like to do?

Add hint, (a link to) [help](https://element.io/help), or tooltip to explain what "[Security Key](https://github.com/matrix-org/matrix-react-sdk/blob/43d9e30673255aa70167a24c8bca5c3121d09492/src/i18n/strings/en_EN.json#L3140)" (and "Security Phrase"), "[E2E room key](https://github.com/matrix-org/matrix-react-sdk/blob/43d9e30673255aa70167a24c8bca5c3121d09492/src/i18n/strings/en_EN.json#LL1347C9-L1347C9)", and so-called "[encryption keys](https://github.com/matrix-org/matrix-react-sdk/blob/43d9e30673255aa70167a24c8bca5c3121d09492/src/i18n/strings/en_EN.json#L1479)" are.

#### Why would you like to do it?

Because it is hard for ordinary non-tech savvy people to understand them. Recently I tried to explain to one of my friends what they were, when they were to be used, how they were different each other, but it took a very long time for the person to grasp the basic reason why there were multiple types of keys.

#### How would you like to achieve it?

I am not sure, but I suspect that some kind of graphical aid or illustration on user onboarding UI would help for them to become familiar with the basic concept, as soon as they signed up.

**Comment by weeman1337** [comment]
Thank you for reporting this issue @luixxiul . This should be solved cross-platform. There is already an existing issue in Element-Meta. Can you add the missing word over there?

**Comment by weeman1337** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/361
