### ISSUE TITLE
Trust & Decoration: Final room sidebar design

### ISSUE THREAD

**Issue by americanrefugee** [vector-im/element-web#25500]
New UX and UI for sidebars on Element X Web

- [Components](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=837-53617&t=UxTBL20pzNmfHlZZ-4)
- [Designs](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=130-28837)
- [Prototype](https://www.figma.com/proto/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?page-id=130%3A28837&type=design&node-id=132-28838&viewport=-1313%2C279%2C1&scaling=min-zoom&starting-point-node-id=132%3A28838)

Views include:

- About room
- About private chat
- People
- Profile
- Threads

**Comment by weeman1337** [comment]
@americanrefugee are there any objections to making the Figma files publicly available?

**Comment by hugeblank** [comment]
Please make the files public! I'd love to see if this is at all associated with #19140 (and the issues that it references)

**Comment by americanrefugee** [comment]
Hi @hugeblank This was meant for internal use. We can't make Figma files public since those permissions are leaky and would impact our commercial contracts.

Sorry for the tease!
