### ISSUE TITLE
We shouldn't be able to make guests admins or mods

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2550]
It makes no sense, plus admins are then hanging around forever which can be confusing (especially if the real user created a proper account afterwards)

**Comment by t3chguy** [comment]
Closing, if you still care about this enhancement request please open an issue in https://github.com/matrix-org/matrix-spec

**Comment by ara4n** [comment]
refiled as https://github.com/matrix-org/matrix-spec/issues/1076
