### ISSUE TITLE
Unlimited amount of visual regression tests with `cypress-visual-regression`

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25516]
#### What would you like to do?

Introduce `cypress-visual-regression` https://github.com/cypress-visual-regression/cypress-visual-regression to add unlimited amount of visual regression tests, regardless of the budget for Percy.

#### Why would you like to do it?

Because it is not optimal to limit the amount of tests due to budget limit. Add tests as many as you need.

### Additional context

I do not know whether `cypress-visual-regression` had been tested by the Element company or not.

**Comment by t3chguy** [comment]
It won't be able to replace Percy as it cannot do snapshot testing in Safari

**Comment by luixxiul** [comment]
Why not using both, instead of replacing percy?

**Comment by t3chguy** [comment]
because that doubles the CI complexity
