### ISSUE TITLE
Matthew not able to see my messages

### ISSUE THREAD

**Issue by juholah** [vector-im/element-web#25512]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Operating system

MacOs

### Application version

Version 1.11.31 (1.11.31)

### How did you install the app?

i dont know

### Homeserver

https://matrix-client.matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing due to lack of info
