### ISSUE TITLE
Stuck notification case

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25513]
### Steps to reproduce

1. Unclear - clicking through my rooms in the morning (post update restart) yielded a stuck room

#### What did you expect?

Unstuck notifications

#### What happened instead?

Stuck notifications - see attached rageshake for debugging details

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023060201 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by rda0** [comment]
Similar for me. Yesterday after the update to 1.11.36 (Windows) and clear cache & reload some previously marked read messages (~60) had stuck notification counts. Today on Linux the same, update, clear cache & reload -> 6 stuck in 1 room. Then app crash + restart 9 stuck in 3 DMs. They went away after a manual mark as read. Sending rage shake now.
