### ISSUE TITLE
Lost message when launching Element after the weekend on nightly

### ISSUE THREAD

**Issue by MatMaul** [vector-im/element-web#25517]
### Steps to reproduce

1. Launch Element Desktop after a while

### Outcome

At least a message sent in the meantime is lost.

This message is available in my Android client.

### Operating system

Linux

### Application version

nightly

### Will you send logs?

Yes

**Comment by MatMaul** [comment]
Logs and impacted message are available [here](https://github.com/matrix-org/element-web-rageshakes/issues/21734).

**Comment by gsouquet** [comment]
Rageshake refers to version `2023060401`. Please update to the latest and see whether this issue is still around

**Comment by t3chguy** [comment]
Closing due to lack of response
