### ISSUE TITLE
Cypress test failure does not remove a PR from the merge queue

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#25520]
### Steps to reproduce

1. Create a PR which fails at least one Cypress test
2. Add the PR to the queue
3. Wait until the PR fails the Cypress test

#### What did you expect?

The test result was synchronized between Cypress Cloud and the merge queue, and the PR should be removed from the queue as soon as the test failed on Cypress Cloud.

#### What happened instead?

The PR was not removed from the queue until all tests of Cypress Cloud ran and the test result was synchronized between Cypress Cloud and GitHub Action.

![0](https://github.com/vector-im/element-web/assets/3362943/4f2967e2-64bf-410b-b97b-f469a4020a15)

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cypress uploads N results, the branch protection is around the Github Actions workflow which runs cypress, that doesn't fail until it actually concludes and finishes running. We could use https://stackoverflow.com/questions/58657895/is-there-a-reliable-way-to-have-cypress-exit-as-soon-as-a-test-fails to make it fail as soon as it finds any error.
