### ISSUE TITLE
Flaky cypress test: `composer.spec > Rich text editor > autocomplete behaviour tests`

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#25527]
### Your use case

```
Composer
       Rich text editor
         Mentions
           Plain text mode
             autocomplete behaviour tests:
     CypressError: Timed out retrying after 10050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:

> <div.mx_AccessibleButton.mx_RoomTile>
```

**Comment by richvdh** [comment]
see also https://cloud.cypress.io/projects/ppvnzg/runs/15076/overview/058bfc61-86c9-4d79-82b2-359efc92abb8

**Comment by kerryarchibald** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/5201232496/jobs/9381103278

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/5601360438/jobs/10245130597 / https://cloud.cypress.io/projects/ppvnzg/runs/16608/overview/d33c63e2-f71a-4d72-827b-06a9b652272a?roarHideRunsWithDiffGroupsAndTags=1

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/11058#pullrequestreview-1469632080 has some thoughts on how to fix this, if anybody has a few minutes spare

**Comment by richvdh** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/16655/overview/aa73b110-7937-473a-8b86-58b8a07f3805
