### ISSUE TITLE
Can't accept the terms of service for the integration manager

### ISSUE THREAD

**Issue by buffless-matt** [vector-im/element-web#25526]
### Steps to reproduce

1. Open Element Desktop.
2. Authenticate with a user that hasn't accepted the integration manager terms of service.
3. Open a room.
4. Click the "Room info" icon (top right).
5. Click "Add widgets, bridges & bots".

#### What did you expect?

The terms prompt to be rendered.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/96466754/4e978678-e120-4249-b824-853faa5cbbaa)

### Operating system

Ubuntu

### Application version

Element version: 1.11.32 Olm version: 3.2.14

### How did you install the app?

From https://element.io/download

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by buffless-matt** [comment]
Root cause:

- https://github.com/matrix-org/matrix-react-sdk/pull/10930/files#diff-5d26068158d0f03c352fea2107b4f75cf65b3496322e522f99ad9f0c8db31c88L157-L162
- [URL.pathname](https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname) seems like it will always contain a leading forward slash.
- https://github.com/matrix-org/matrix-js-sdk/blob/f41fa84e72da0542940d2f712dda0f7ee2758b6f/src/client.ts#L7491-L7491 produces `https://scalar.vector.im//_matrix/integrations/v1/terms` instead of `https://scalar.vector.im/_matrix/integrations/v1/terms` (as it was prior to the change mentioned above, to `URL`).

**Comment by andybalaam** [comment]
Awesome bug report, thank you @buffless-matt

**Comment by andybalaam** [comment]
Fixed in [v1.11.33](https://github.com/vector-im/element-desktop/releases/tag/v1.11.33)
