### ISSUE TITLE
1.11.32 missing rooms in room list

### ISSUE THREAD

**Issue by vsatmydynipnet** [vector-im/element-web#25531]
### Steps to reproduce

After upgrading to 1.11.32 i was missing rooms in the rooms list. Searching the room by name and entering worked. Cache was cleared.

Back to 1.11.31 all is good again.

Running Element-Desktop on Debian Sid

### Outcome

Rooms missing in room list

### Operating system

Debian Sid

### Application version

1.11.32

### How did you install the app?

apt

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
No

Without logs what do you expect us to investigate? You gave no reproduction steps, nothing to go on really.

**Comment by vsatmydynipnet** [comment]
Found it:

In earlier versions if sorted by activity, rooms with unread first, it also sorted muted rooms to the top (my rss news feed room e.g. is muted because the ticker has 1-3 posts every minute).  Now all other rooms are sorted, but muted roomsstays on bottom of my 200 rooms list. This is why i thought they are not listed.

Looks like this change  was not good.

**Comment by MadLittleMods** [comment]
It looks like you're referring to https://github.com/vector-im/element-web/issues/25131 ([epic](https://github.com/vector-im/element-web/issues/25032))

It's intended behavior for now but if it continues to be a friction point for you, feel free to create a new issue framed in that way :fast_forward:
