### ISSUE TITLE
GYU: Update the content on the banner (for mis-matched settings)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25530]
### Your use case

We've updated the copy for the banner that shows when a user's settings don't match the UI

"We’ve simplified Notifications Settings to make options easier to find. Some custom settings you’ve chosen in the past are not shown here, but they’re still active. If you proceed, some of your settings may change.  Learn more <OK>"

the learn more link will go here: https://element.io/help#settings2
which i am working on updating (https://github.com/vector-im/internal-planning/issues/453)

**Comment by giomfo** [comment]
@daniellekirkwood What happens when I click on "OK" button?

**Comment by daniellekirkwood** [comment]
@justjanne will be able to provide a better answer - you can see the behaviour in the netlify link she shared with us a few days ago. I will DM to you :)

**Comment by daniellekirkwood** [comment]
updated the copy in the issue to match the conversation in the room

updated from:
<img width="956" alt="Screenshot 2023-06-07 at 11 23 22" src="https://github.com/vector-im/element-web/assets/89144281/a1e2212d-eae0-435f-a59f-b9bfb1ada5cc">

**Comment by daniellekirkwood** [comment]
@justjanne can we please update this before launch!

**Comment by justjanne** [comment]
Sure!
