### ISSUE TITLE
Starting nightly for the first time seems to trigger notification counter mess in normal Desktop

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#25541]
### Steps to reproduce

1. Element Desktop is running
2. Element Desktop nightly is installed
3. nightly is verified
4. nightly starts getting key but still cannot decrypt much
5. suddenly the unread counter of one of the rooms shoots up in Element Desktop without new messages arriving
![image](https://github.com/vector-im/element-web/assets/640121/b957e7df-9ceb-43fb-a27f-a63bbf85bbec)
7. then it shoots down again 
![image](https://github.com/vector-im/element-web/assets/640121/6be3a273-f7ba-487d-a3cf-6a7d75b8de5e)
9. Meanwhile, in the nightly the counter is zero of the same room
![image](https://github.com/vector-im/element-web/assets/640121/ed185498-38d4-41ba-8017-0ec566405855)

#### What did you expect?
- Unread counters to be stable without new messages arriving
- Unread counters to be consistent across clients

#### What happened instead?
None of the above

### Operating system

Windows

### Application version

Element version 1.11.32

### How did you install the app?

from Element

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by Johennes** [comment]
I suspect this is an instance of https://github.com/vector-im/element-web/issues/25479

**Comment by kittykat** [comment]
I am experiencing this when having two instances of the webapp running (e.g. app.e.i and develop.e.i)

**Comment by t3chguy** [comment]
@kongo09 @Johennes @kittykat have you seen this recently?

**Comment by kittykat** [comment]
I haven't seen it in a while

**Comment by t3chguy** [comment]
Closing as presumed fixed by stuck notifications work
