### ISSUE TITLE
Client Chat logging

### ISSUE THREAD

**Issue by Gubith** [vector-im/element-web#25559]
#### What would you like to do?

Enable room logging similar to Pidgin.

#### Why would you like to do it?

Local text log searching / offline search.

#### How would you like to achieve it?

Each room saves to log folder, one file per room, named with (start) date:  <room> <date>.log

Log folder might default to Documents or as with Pidgin, Roaming.

### Have you considered any alternatives?

Currently the only logging method is manual export.

**Comment by t3chguy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API lacks Safari support
