### ISSUE TITLE
Element creates room on wrong server

### ISSUE THREAD

**Issue by mkarg** [vector-im/element-web#25551]
### Steps to reproduce

# First prepare the following setting:
* On homeserver HS create user U.
* On homeserver SS create space S and invite user U to it.
* User U accepts the invitation to space S.
* On homeserver SS grant administration rights for space S to user U.

# Then reproduce the bug like this:
* User U logs in to homeserver HS using Element.
* User U navigates Element to the overview page of space S.
* User U clicks the "Add"  button on the overview page of space S and invokes the "New Room" menu item to create the new room R.

### Outcome

# Expected Result
* The room R is created on homeserver SS, because it was created using the "New Room" button on the overview page of space S, and space S is hosted on homeserver SS. The benefit is that the room R will survive the eventual dismission of homeserver HS.

# Actual Result
* The room R is created on homeserver HS, because it was created by User U, and user U's homeserver is HS. The drawback is that the room R will become unusable at the eventual dismission of homeserver HS.

### Operating system

Linux

### Browser information

Chrome

### URL for webapp

Latest

### Application version

Version Element: 1.11.32, Version Olm: 3.2.14

### Homeserver

Synapse (Latest)

### Will you send logs?

No

**Comment by t3chguy** [comment]
This just isn't how matrix works. A user cannot create a room on a different server, their access token is for their homeserver only, they can't perform functions on other server.

On the other hand, the server in the room id is for uniqueness only and doesn't make that server own the room. rooms/spaces don't belong to a single server, they're decentralised, fully shared amongst all servers which have at least one user in the room.

**Comment by mkarg** [comment]
> On the other hand, the server in the room id is for uniqueness only and doesn't make that server own the room. rooms/spaces don't belong to a single server, they're decentralised, fully shared amongst all servers which have at least one user in the room.

IIUC this means, if the homeserver HS of the room creator U is dismissed permanently, the room can still be used by all others?

**Comment by t3chguy** [comment]
> IIUC this means, if the homeserver HS of the room creator U is dismissed permanently, the room R can still be used by all others without limitations?

Correct, as long as at least one other server joined the room before the hs died, rooms are only decentralised amongst the servers joined to them. 

> Edit: For example, how can a new user V using his own homerserver HV enter room R in that situation? As R's address apparently is `!R:HS`, and as HS is dismissed (including HS's internet domain not existing anymore), I cannot imagine how that is technically possible?

That's a room id, not an address, they're not joinable over federation. You should use addresses, they start with a #. If the hs in the address dies you'll need to use a different address pointing at the same room. There's no limit to how many addresses point at a given room. They resolve to room id + list of via servers to orchestrate the join into the room over federation.

**Comment by mkarg** [comment]
Thank you for this detailed explanation. Now I have a much better understanding! :-)
