### ISSUE TITLE
Room text copy as displayed in room

### ISSUE THREAD

**Issue by Gubith** [vector-im/element-web#25561]
### Your use case

When copying selected text from room (IRC mode),  CR are added.

Requesting `<time><tab><user><tab><message>`

This would be very helpful when quoting in other rooms / notes.

**Comment by jellykells** [comment]
Maybe this could be a useful enhancement of the message forwarding feature which currently just sends a copy of the message content without any metadata

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/2129
