### ISSUE TITLE
Joining a room silently fails and spins together if you try to join an invalid alias

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#25562]
### Steps to reproduce

1. try to join a plausible but invalid alias - e.g. /join #element-x-android:matrix.org
2. stare at a spinner forever
3. open the JS console
4. observe:

```
rageshake.ts:74 RVS failed to get room id for alias:  M_NOT_FOUND: MatrixError: [404] Room alias #element-x-android:matrix.org not found (https://matrix-client.matrix.org/_matrix/client/r0/directory/room/%23element-x-android%3Amatrix.org)
    at parseErrorResponse (vector://vector/webapp/bundles/b1ea595fc68640b2e59a/bundle.js:114477:12)
    at MatrixHttpApi.requestOtherUrl (vector://vector/webapp/bundles/b1ea595fc68640b2e59a/bundle.js:215854:86)
consoleObj.<computed> @ rageshake.ts:74
00:10:44.268 
```

#### What did you expect?

/join should not silently fail.

### Application version

Element Nightly version: 2023061101 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This isn't specific to `/join` as that reuses the same ViewRoom action as all other mechanisms.

Related https://github.com/vector-im/element-web/issues/9610
Same cause as https://github.com/vector-im/element-web/issues/24783

**Comment by t3chguy** [comment]
The code has an explicit Room not found error to show here
