### ISSUE TITLE
Sessions manager multi action button misaligned

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25579]
### Steps to reproduce

1. Open the sessions manager
2. Select at least one session

#### What did you expect?

Multi action buttons correctly aligned

#### What happened instead?

Multi action buttons misaligned

![image](https://github.com/vector-im/element-web/assets/6216686/7b929d34-d502-4577-9a36-2a270b661a42)

### Operating system

Ubuntu 22.04.2 LTS

### Browser information

Firefox 114.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: 081706435d9c-react-7c9c818f06a5-js-9f6073478f4c Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by luixxiul** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/25545 ?

**Comment by weeman1337** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/25545
