### ISSUE TITLE
Missing reactions for some messages

### ISSUE THREAD

**Issue by MatMaul** [vector-im/element-web#25596]
### Steps to reproduce

Reactions are fully missing for some messages.

I am going to try a clear cache and report after sending the logs.

impacted message (Element private room):
https://matrix.to/#/!SGNQGPGUwtcPBUotTL:matrix.org/$lHK4qgyCBx362J1cYBk6rMCbNkxZ9UbfCzu0ePL2SnA?via=jki.re&via=matrix.org&via=element.io

### Outcome

I should see the reactions but none are present.

This includes one of mine put from the phone (which may be related ? I think the messages was `sync` on EleWeb after I added the reaction on my phone).

### Operating system

Fedora

### Application version

1.11.33

### How did you install the app?

Flatpak

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by Johennes** [comment]
I reproduced this issue on [this message](https://matrix.to/#/!pMBteVpcoJRdCJxDmn:matrix.org/$EUPjLwqX0cvCzqOpOtElsPl66I_Zrftc1Fb8xoroNd0?via=matrix.org&via=tchncs.de&via=mozilla.org) in the public Element iOS room. Element Android shows a 🎉 reaction on this message. Element Desktop nightly (2023061801) does not show a reaction.

**Comment by weeman1337** [comment]
https://github.com/vector-im/element-web/issues/25630#issuecomment-1599254295 provides some useful information about this.
