### ISSUE TITLE
Login with JWT not working

### ISSUE THREAD

**Issue by nmanthena18** [vector-im/element-web#25602]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
in client url I have added query param loginToken="someValidToken" nothing happend

#### What did you expect?
when I have valid JWT it should trigger login flow 
#### What happened instead?
Nothing happend

### Operating system

in All

### Application version

1.11.33

### How did you install the app?

https://chat.intellaire.com/#/home

### Homeserver

latest

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Where did you see that Element Web supported JWT auth? It doesn't. The loginToken param is For SSO only and it doesn't work called cold, has to be part of the sso flow.

**Comment by nmanthena18** [comment]
@t3chguy do you mean there is no possibility with jwt flow?, I can see the functions which are related to jwt flow in web client & server. If call function loginWithToken it’s it’s giving valid response with access token, device and user. Information

**Comment by t3chguy** [comment]
Element web only has support for matrix access tokens and other matrix tokens. Not JWT.

**Comment by nmanthena18** [comment]
Thanks! @t3chguy 
Is there any possibility to achieve jwt and hence matrix supports the jwt

**Comment by t3chguy** [comment]
Use JWT on the server side where element delagates auth to the server vs an sso like mechanism. See the matrix spec for how flexible sso/cas login is.

**Comment by nmanthena18** [comment]
@t3chguy - else once server generate the access token if I give it to element through loginToken will it work?

**Comment by t3chguy** [comment]
Login token the url parameter cannot be used cold like I told you earlier. It has to be used during the sso flow, simply will not work otherwise. It isn't a matrix access token but rather a matrix m.login.token

**Comment by t3chguy** [comment]
@nmanthena18 Synapse's JWT support is non-standard https://matrix-org.github.io/synapse/latest/jwt.html

> Synapse comes with a **non-standard** login type to support [JSON Web Tokens](https://en.wikipedia.org/wiki/JSON_Web_Token).

The SSO flow in Matrix is really more akin to delegated auth. Client asks server to perform authentication on its behalf and give it back a Matrix access token - https://spec.matrix.org/v1.7/client-server-api/#client-login-via-sso

I suggest https://matrix.to/#/#matrix-dev:matrix.org if you have any further queries
