### ISSUE TITLE
"Call is in an unknown state" on receiving call

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#25629]
### Steps to reproduce

1. Place voice call from one element-web to user logged in with another element web
2. On other element web, call sometimes just shows as, "The call is in an unknown state" instead of ringing

Looks like this may be triggered on flaky internet connections (I'm getting it now tethering on a train). Investigated a little and the LegacyCallEventGrouper is ending up with the call state being undefined. That's as far as I've got.

Similar to https://github.com/vector-im/element-web/issues/21832 but that issue is for looking at the call on a third device.

#### What did you expect?
Call rings

#### What happened instead?
Call is in an unknown state

### Will you send logs?

No

**Comment by weeman1337** [comment]
> Similar to https://github.com/vector-im/element-web/issues/21832 but that issue is for looking at the call on a third device.

Isn't that what the description in #21832 is about:
- Call from Element Android → Element iOS
- Look at the call on Element Desktop

**Comment by t3chguy** [comment]
Closing due to no response
