### ISSUE TITLE
Flaky Jest test: `<JoinRuleSettings /> › Restricted rooms › When room does not support restricted rooms › upgrades room when changing join rule to restricted`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25625]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/5312529645/jobs/9617152858?pr=11110:

```
  ● <JoinRuleSettings /> › Restricted rooms › When room does not support restricted rooms › upgrades room when changing join rule to restricted

    expect(element).toBeInTheDocument()

    element could not be found in the document

      201 |
      202 |                 // update spaces
    > 203 |                 expect(await screen.findByText("Updating space...")).toBeInTheDocument();
          |                                                                      ^
      204 |
      205 |                 await flushPromises();
      206 |

      at Object.toBeInTheDocument (test/components/views/settings/JoinRuleSettings-test.tsx:203:70)
```

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6115470605/job/16599051674?pr=11529

**Comment by andybalaam** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6234517455/job/16921863815?pr=11612

Technically the test was `upgrades room when changing join rule to knock` but close enough

**Comment by andybalaam** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6269632562/job/17026351306

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6398283093/job/17368078044

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6398367336/job/17368361962

**Comment by andybalaam** [comment]
I can reproduce this locally.
