### ISSUE TITLE
Reduce rageshakes from custom deployments

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#25635]
Our sample config points at our own rageshake server, which few if any admins change when deploying element. Yet at the same time we do not want to receive or handle rageshakes from custom deployments, as they are often caused by the customizations and provide no information to us.

```[tasklist]
- [x] Ensure Element Web handles a null or missing rageshake URL correctly
- [ ] https://github.com/vector-im/element-web/pull/25772
- [x] Ensure our own deployments keep the rageshake URL in their configs
```

**Comment by t3chguy** [comment]
> Ensure Element Web handles a null or missing rageshake URL correctly

Both removal and `null`-ing work as expected

Feedback option disappears

![image](https://github.com/vector-im/element-web/assets/2403652/a4db8376-a9ad-4fd1-8183-52cbeaac3bcc)

`/rageshake` command disappears

![image](https://github.com/vector-im/element-web/assets/2403652/97bd8bf8-1f9d-42e4-84b8-5f4c9dd72ded)

Submit debug logs button disappears

![image](https://github.com/vector-im/element-web/assets/2403652/fafa5d10-0f0a-4327-9f2d-a089cb3ddec9)
