### ISSUE TITLE
Pressing Escape with focus on the composer does not work anymore

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#25640]
### Steps to reproduce

The same applies for Element Desktop Nightly:

1. Open a room with some messages
2. Scroll up in the timeline
3. Click on the compose and optionally start typing
4. Press Escape

#### What did you expect?
The timeline to scroll to bottom and an eventual read marker to disappear.

#### What happened instead?
Nothing, unless I click on a timeline event before pressing Escape.

### Operating system

Arch Linux

### Browser information

Firefox 114.0.1

### URL for webapp

https://develop.element.io/

### Application version

Element version: 278c494eb368-react-ac3d6ab7dd91-js-8b9672ba43a2 Olm version: 3.2.14

### Will you send logs?

No

**Comment by weeman1337** [comment]
I didn't even know this is a feature :laughing: Maybe it should be mentioned in the keyboard shortcuts.

Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/ba28174ac09f9eaee612f22cdf9ed9c775608a38

**Comment by davidegirardi** [comment]
It is, it's the "Dismiss read marker and jump to bottom" shortcut.

**Comment by weeman1337** [comment]
> It is, it's the "Dismiss read marker and jump to bottom" shortcut.

:+1: I have overlooked this

**Comment by andybalaam** [comment]
My rageshake and a relevant log are in #25641

**Comment by andybalaam** [comment]
> My rageshake and a relevant log are in #25641

Actually, the errors I saw were not relevant, but could be useful in diagnosing some [stuck unreads](https://github.com/vector-im/element-web/issues/24392).
