### ISSUE TITLE
Element Desktop and Web lose reactions on messages in threads over time

### ISSUE THREAD

**Issue by daniel-abramov** [vector-im/element-web#25649]
### Steps to reproduce

I just noticed that the same discussion thread loses emojis over time. E.g. on the first day, there was a thread of 10 messages, some of which had emoji, after some time certain messages displayed fewer emojis than before, after a day, it was even less, and after 2 days there were absolutely zero emojis shown. On the other device, it showed emojis for the past few days right, but certain messages did not have any emojis displayed. On the third device, the state was also different.

### Outcome

The same thread has a different amount of emojis displayed across different devices. It's not even clear which device shows the "truth" since they all look different.

### Operating system

macOS

### Application version

Element Web, Element Nightly Desktop

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
@daniel-abramov sorry I'm confused by your mention of Element Call

**Comment by daniel-abramov** [comment]
Element Web from https://app.element.io/.
Element Desktop Nightly: Version 2023042502 (2023042502).

**Comment by t3chguy** [comment]
Your nightly is months out of date, 2023-04-25

**Comment by t3chguy** [comment]
Closing due to being months out of date
