### ISSUE TITLE
Open another device to load encrypted messages (24267)

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [vector-im/element-web#25647]
## This is a reopening of #24267 

Receive an encrypted message from an iOS client. It seems like the problem may trigger when a message is sent soon before/after an image.

#### What did you expect?
Messages to be decrypted.

#### What happened instead?
I see "Unable to decrypt message" instead message. I can't see text before and other info was instead them. But now I see also

    Open another device to load encrypted messages
    This device is requesting decryption keys from your other devices. Opening one of your other devices may speed this up.

And no way to close that. It's visible all time and it does not confirm keys.

### Operating system

Arch Linux

### Application version

Element version: 1.11.33 Olm version: 3.2.14

### How did you install the app?

pacman

### Homeserver

Synapse Docker container

### Will you send logs?

No

**Comment by t3chguy** [comment]
@f35f0ef9d0e827dae86552d3899f78fc that sounds like an issue with the iOS client, if the user of the iOS client is using the share sheet (Share with Element) then that is known to cause this issue, I suggest having the iOS sender an open an issue containing all required information at https://github.com/vector-im/element-ios
