### ISSUE TITLE
‼️ emoji looks different in composer & timeline from the way it looks in emoji picker

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25652]
### Steps to reproduce

1. Hit CTRL + OPTION + SPACE to open the macOS emoji picker
2. Choose and insert ‼️

![Screenshot 2023-06-22 at 13 21 21](https://github.com/vector-im/element-web/assets/1137962/103cee68-ad51-4a94-8f57-d75a925dce20)

#### What did you expect?

The emoji to look the same in the composer as it did in the picker.

#### What happened instead?

It looked like this:

![Screenshot 2023-06-22 at 13 21 26](https://github.com/vector-im/element-web/assets/1137962/9a7b607c-7c69-43cf-aaf4-90ec46da186a)

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io / element.ems.host

### Will you send logs?

No

**Comment by t3chguy** [comment]
For me it does look the same between the composer & timeline on macOS

<img width="216" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/e313f3bb-8434-4f11-a16d-08a6cda15a08">
<img width="338" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/a9bda3eb-674b-40ec-b5ab-55d4fb34851b">

Looks like the twemoji font styles them in this manner.

Used inspect element to inject that emoji into a tweet

![image](https://github.com/vector-im/element-web/assets/2403652/0050be1a-7e00-426b-8019-46f0fca7bfc3)

https://github.com/twitter/twemoji is the repo for that font

**Comment by Johennes** [comment]
> For me it does look the same between the composer & timeline on macOS

Sorry, what I meant is it looks different in the emoji picker (big red exclamation marks) to both the composer and timeline (normal black exclamation marks).

**Comment by t3chguy** [comment]
Right, well all emoji look different between your system picker and Element. One is using whatever system font, one is using your application font (Inter + Twemoji by default)

<img width="464" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/1fa755e0-b35d-42f8-a54d-a40ac7f6bbc9">

If you use the in-app picker then things match

<img width="330" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/60f06c67-535c-4310-8b8c-f4c005a61443">

This is either a design choice of Twemoji or an issue on their end

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9790

**Comment by weeman1337** [comment]
Is this then somehow expected behaviour and not a defect?

**Comment by t3chguy** [comment]
It is really unknown, it could be a bug in Twemoji that the bangbang renders in a different colour to the single bang. Ultimately, the Design team picked Twemoji, its up to them whether this is fine as we're just delegating to Twemoji or whether they want to start a custom Element emoji font or switch to using system fonts for emoji

**Comment by Johennes** [comment]
Ok, I see. I think this can be closed for now then. I initially considered it a bug because the inserted emoji looked so wildly different from what was in the picker. But that's the case for some others as well now that I look at it.

**Comment by t3chguy** [comment]
As I understand it, EX uses the system font for emoji so it might be worth asking design whether we should follow suit

**Comment by Johennes** [comment]
@rufuskahler WDYT?

**Comment by t3chguy** [comment]
We should probably maintain a common emoji font for SAS verification to ease users comparing emoji visually

**Comment by rufuskahler** [comment]
CC @janogarcia ...
