### ISSUE TITLE
Control+tab and ctrl+shift+tab to go up and down the list of chats

### ISSUE THREAD

**Issue by Kommynct** [vector-im/element-web#25653]
### Your use case

Telegram has this, and it's a little annoying not to be able to immediately switch to the next chat on element

this might be better for element-desktop I don't know

**Comment by t3chguy** [comment]
Web applications really ought not to hijack browser shortcuts. 

Closing in favour of https://github.com/vector-im/element-web/issues/15076 given the shortcuts already exist, just with different bindings, so the ability to set them to whatever you like from other applications is the solution here
