### ISSUE TITLE
Can't switch back to default hs on sign in dialogue

### ISSUE THREAD

**Issue by rltas** [vector-im/element-web#25650]
### Steps to reproduce

1. Go to https://app.element.io/#/login

2. Click "Edit"

3. Enter some custom hs

4. Click "Continue"

5. ![image](https://github.com/vector-im/element-web/assets/112475628/2acad4ac-9dc6-4a3f-8c01-dcfc88fa3dda)

6. Click "Edit" again

7. Select the default "matrix.org" hs

8. Click Continue

9. ![image](https://github.com/vector-im/element-web/assets/112475628/2acad4ac-9dc6-4a3f-8c01-dcfc88fa3dda)

#### What did you expect?
matrix.org hs is used

#### What happened instead?
Custom hs is used

### URL for webapp

app.element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11020
