### ISSUE TITLE
New message count in metaspace doesn't update

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#25679]
### Steps to reproduce

1. Receive a message in a DM while looking at another space

#### What did you expect?
I see an unread marker appear on the people metaspace

#### What happened instead?
No notification of new message

![Screenshot from 2023-06-28 11-25-05](https://github.com/vector-im/element-web/assets/51663/70250902-80af-4383-b034-475d20e1a1eb)

### Browser information

Version 114.0.5735.106 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 6bbc2b82383d-react-a87362a04874-js-acbcb4658a5d Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@robintown did you mean 25331?

**Comment by robintown** [comment]
Oh yes, that's what I meant

**Comment by turt2live** [comment]
Also applies to the Home metaspace ftr

**Comment by daniellekirkwood** [comment]
this applies to other metaspaces as found by @amshakal and Jason R

**Comment by germain-gg** [comment]
This appears to be `O-Frequent` IMO. I have not seen any metaspace notification ever for the past few weeks.

Or is it only happening under specific circumstances that warrants it to be `O-Occasional` ?

**Comment by kittykat** [comment]
I haven't seen any metaspace notifications in a long time now, and missing a lot of notifications in the left panel for about a week

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10517

**Comment by t3chguy** [comment]
This doesn't affect `master` but does affect `staging`
