### ISSUE TITLE
Persistent Threads dot when last message in a thread is redacted

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25670]
### Steps to reproduce

1. In a room with threads
2. Where the latest message in the latest thread has been deleted (redacted). In fact, the last 2 events are redacted
3. The thread read receipt points at the redacted message.

#### What did you expect?

I have read all threads, and the receipt points at the latest message in the thread (which is redacted), so I would expect the dot in the top-right for Threads to disappear.

#### What happened instead?

The dot for unread Threads remains, and this room is a stuck unread room.

![image](https://github.com/vector-im/element-web/assets/76812/f6b9f064-c534-49b4-9911-a9d6f3c37257)

### Operating system

Ubuntu 22.04

### Browser information

Firefox 114.0.1

### URL for webapp

https://develop.element.io

### Application version

Element version: e4bf321e6549-react-0d83a38a3eb5-js-9de4a057df6e Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/845d9025-0fc4-4c36-b825-772abcee512e)

Looks to be fixed

**Comment by mightyiam** [comment]
Thank you!

**Comment by andybalaam** [comment]
Yep, seems to be fixed for me, nice work!
