### ISSUE TITLE
Block elements in messages are very low density

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25685]
### Steps to reproduce

1. Put a numbered or bulleted list in a message

#### What did you expect?

A line density that doesn't look surprising

#### What happened instead?

This looks very low density compared to the rest of the timeline:

![Screenshot 2023-06-29 at 11-40-54 Element 6 Test room](https://github.com/vector-im/element-web/assets/48614497/cf4d38c5-1b35-490b-a064-c715169bf81d)

Here's a screenshot with more visual context:

![Screenshot 2023-06-29 at 11-45-15 Element 6 VoIP Stand-ups](https://github.com/vector-im/element-web/assets/48614497/6f97b753-6cca-455f-8c43-6582c0362345)

### Operating system

NixOS unstable

### Browser information

Firefox 114.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 4f1ce3c39a1c-react-95283d21bb7b-js-182882666168 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by turt2live** [comment]
Likewise headers, code blocks, and pretty much every other block element ftr. Browse the TWIM room for examples.

**Comment by germain-gg** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11103
