### ISSUE TITLE
Text on 1:1 call tiles is massive

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25684]
### Steps to reproduce

1. Place a 1:1 call

#### What did you expect?

The timeline tile should look roughly like it always has

#### What happened instead?

This typographic treatment looks very unintentional:

![Screenshot 2023-06-29 at 11-29-22 Element 5 Cerik](https://github.com/vector-im/element-web/assets/48614497/98a4d5dd-872f-41aa-923f-9b0ce55ab3ce)

### Operating system

NixOS unstable

### Browser information

Firefox 114.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 4f1ce3c39a1c-react-95283d21bb7b-js-182882666168 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by nadonomy** [comment]
Type style suggestions in (now closed) https://github.com/vector-im/element-web/issues/25787
