### ISSUE TITLE
Font size in threads is inconsistent

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25683]
### Steps to reproduce

View a thread

#### What did you expect?

All messages should use the same font sizes

#### What happened instead?

The first message is sized differently from the rest of the messages:

![Screenshot 2023-06-29 at 11-15-51 Element 8 #element-dev matrix org](https://github.com/vector-im/element-web/assets/48614497/48d78304-86ad-453e-baa6-a7ebecd13ae4)

### Operating system

NixOS unstable

### Browser information

Firefox 114.0.1

### URL for webapp

develop.element.io

### Application version

Element version: 4f1ce3c39a1c-react-95283d21bb7b-js-182882666168 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by germain-gg** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11103

**Comment by HarHarLinks** [comment]
can repro a similar case where it seems to be an edited message that uses a larger text size than regular threaded messages

**Comment by germain-gg** [comment]
@HarHarLinks if the message is in the public room would you be able to link to it here, or send it to me via DM? Thank you
