### ISSUE TITLE
wrong users in space

### ISSUE THREAD

**Issue by 532910** [vector-im/element-web#25697]
### Steps to reproduce

I dunno how to reproduce this.

### Outcome

![image](https://github.com/vector-im/element-desktop/assets/14617699/8f31d8db-0d3c-4126-8d14-d082cda782cd)

### Operating system

debian sid

### Application version

1.11.34

### How did you install the app?

https://packages.element.io/debian

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing due to no response
