### ISSUE TITLE
Unable to paste in message

### ISSUE THREAD

**Issue by clehner** [vector-im/element-web#25695]
### Steps to reproduce

In compose field ("Send a message..." or "Send an encrypted message...") or in editing a message: middle-click, press ctrl-v, or choose Paste from context menu (right-click).

### Outcome

No result occurs; nothing is pasted.

Paste is OK in other fields - e.g. search box and New Room fields.

### Operating system

Trisquel GNU/Linux

### Browser information

Abrowser (firefox) 113.0.2 (64-bit)

### URL for webapp

*.element.localhost; also remote hosted ones

### Application version

Element version: 1.11.34 Olm version: 3.2.14

### Homeserver

various Synapse and Conduit

### Will you send logs?

No

**Comment by t3chguy** [comment]
Abrowser isn't officially supported - https://github.com/vector-im/element-web#supported-environments - as per that policy this issue will be closed. My best guess is your browser ships with non-standard settings by default, e.g. disabling clipboard access like https://github.com/vector-im/element-web/issues/25544
