### ISSUE TITLE
Signing out from the session manager does not work

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#25699]
### Steps to reproduce

1. From an Element (Latest version or Nightly) session logged in with SSO open All settings
2. Click on session
3. Select a session and click "Sign out" at the top of the section or "Sign out of this session" under the session
4. Click on "Sign out" on the modal dialog

#### What did you expect?
The session to terminate.

#### What happened instead?
Nothing. Looking in the dev tool shows a POST request to `https://HOMESERVER/_matrix/client/r0/delete_devices` which gets a 404 `{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`.

### Will you send logs?

No

**Comment by t3chguy** [comment]
Seems like your homeserver isn't spec compliant. R0 had the delete_devices API. See https://web.archive.org/web/20210903203205/https://spec.matrix.org/unstable/client-server-api/#post_matrixclientr0delete_devices
