### ISSUE TITLE
Avatar missing in nightly

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-web#25691]
### Steps to reproduce

1. Open the app
2. See no avatar

#### What did you expect?

To see the avatar

#### What happened instead?

I did not see the avatar:

![image](https://github.com/vector-im/element-web/assets/25768714/656bb7e8-0fd3-4b05-bb43-be5ff5effe23)

### Operating system

Debian Trixie

### Application version

Element Nightly version: 2023063001 

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
I was seeing this as well. The issue disappeared. Maybe it was an issue on the server side. Not sending specific media :man_shrugging: Closing now.
