### ISSUE TITLE
Emoji 15.0

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25701]
#### What would you like to do?

Support the new emojis from Emoji 15.0

#### Why would you like to do it?

Because they're new and shiny

#### How would you like to achieve it?

Update our Twemoji and Emojibase sources

**Comment by t3chguy** [comment]
Twemoji itself doesn't yet support Emoji 15.x
https://github.com/twitter/twemoji/releases

**Comment by robintown** [comment]
Ah right, https://blog.emojipedia.org/twemoji-15-0-emoji-changelog/ made me believe it was already available, but it seems that Twitter normally withholds the open source release for about a month.

**Comment by robintown** [comment]
(there's also the distinct possibility that Twitter is taking the project closed-source and we may have to switch emoji fonts, but let's wait to make a call on that…)

**Comment by Aidanboyishere** [comment]
> (there's also the distinct possibility that Twitter is taking the project closed-source and we may have to switch emoji fonts, but let's wait to make a call on that…)

Hi what are you up to

**Comment by nadonomy** [comment]
h/t to @robintown for digging in a little further in this. From your suggestions - my vote would be to switch to the [new twemoji fork](https://github.com/jdecked/twemoji) listing a bunch of the original contributors, recently adopted by Discord.

My rationale would be that this gets us off a stale project dependency, with minimum effort.

**Comment by t3chguy** [comment]
Still blocked, the fork doesn't have a 15.x release yet

**Comment by t3chguy** [comment]
Turns out we accidentally did this as part of https://github.com/matrix-org/matrix-react-sdk/pull/11433 - it'll be improved by https://github.com/matrix-org/matrix-react-sdk/pull/11925

**Comment by ringtailedfox** [comment]
Hello!  I've noticed that this problem has re-surfaced in the Windows application and the web client, tested in Brave for Windows 10 64-bit...  the affected emojis i've detected so far are shaking_face, pink_heart, grey_heart, light_blue_heart,, leftwards_pushing_hand, rightwards_pushing_hand, goose, moose, donkey, jellyfish, hyacinth, ginger_root, pea_pod, folding_hand_fan, hair_pick, maracas, flute, khanda.

I hate to re-open a closed/solved issue, but I think this warrants at least a second inspection... I do apologize for making extra work for everyone, but i'll happily volunteer to test any proposed solutions!
