### ISSUE TITLE
Lots of Olm sessions for the same device

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25716]
For some reason Element is repeatedly creating new sessions for another of my devices. 

So far it is up to 73 of them.

**Comment by weeman1337** [comment]
@richvdh how bad is this? Can you provide some snipped to get the session count for my devices? Just to test with some of my accounts, so that I can triage this issue better.

**Comment by richvdh** [comment]
Having looked at the rageshakes, what happened is a double failure:

 * EA device sends lots (about 70?) of encrypted to-device messages.
 * Those to-device messages get reordered before decryption at EW. We only keep 40 message keys, so end up dropping a load of keys.
 * Once the messages that we have dropped keys for turn up, we decide that the olm session is wedged, and force a new olm session.
 * New-olm-session-creation is *supposed* to be rate-limited, but it is racy, so if lots of requests for new olm sessions happen at once, the rate limit doesn't work.

So, the problems here are:

 1. To-device-messages are being reordered. They shouldn't be reordered at all, though Element tries to process them in parallel, which may be part of the problem.
 2. New-olm-session-creation-rate-limiting is racy.

**Comment by richvdh** [comment]
Have opened https://github.com/vector-im/element-web/issues/25723 to track the reordering. Suggest we use this issue to track "New-olm-session-creation-rate-limiting is racy."
