### ISSUE TITLE
Room tiles clipping in room tiles

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#25718]
### Steps to reproduce

<img width="285" alt="Screenshot 2023-07-05 at 10 11 15" src="https://github.com/vector-im/element-web/assets/4626865/723c778f-132d-4fbd-a048-8bba805fd75a">

Descenders in room tiles are clipped. Likely related to https://github.com/matrix-org/matrix-react-sdk/pull/11189. Heads up @germain-gg.

### Outcome

...

### Application version

Element Nightly version: 2023070501
Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
This might be a more major issue with certain fonts or alphabets
