### ISSUE TITLE
Signing out takes forever

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#25719]
### Steps to reproduce

I was trying to sign out some other sessions, but accidentally signed out my active session (this is not the first time I've done this - I'll raise a separate issue for that).

Anyway, this was 10 minutes ago and my Element Desktop hasn't caught on yet. It doesn't appear to be syncing. I don't imagine it's sending messages, but I can't verify 'cause they're getting stuck at _encrypting_.

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Thank you for reporting the issue @lampholder 

> I was trying to sign out some other sessions, but accidentally signed out my active session (this is not the first time I've done this - I'll raise a separate issue for that).

Can you clarify that? You went to the session management and signed your current device out from there?

> Anyway, this was 10 minutes ago and my Element Desktop hasn't caught on yet. 

What does „hasn't caught on yet“ here mean? Did you sign in again or didn't the application not sign out?

If possible provide step by step instructions and fill in „What did you expect?“ and „What happened instead?“.

**Comment by t3chguy** [comment]
I'm not seeing anything in your logs which shows that your client was ever told by your server that your access token is invalidated. This feels like a server issue.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/9319

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/9319 due to no response
