### ISSUE TITLE
Arrows (and presumably other digraphs) don't render anymore

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25727]
### Steps to reproduce

1. Enter "=>" into the composer

#### What did you expect?

It should be converted into 

![Screenshot 2023-07-07 at 07 55 35](https://github.com/vector-im/element-web/assets/1137962/405cb7b8-b70b-478c-8500-19c9cc4983d8)

It's still like that on app.element.io as of writing.

#### What happened instead?

It stayed 

![Screenshot 2023-07-07 at 07 56 01](https://github.com/vector-im/element-web/assets/1137962/5510ad20-1dcc-4446-9a78-71a77ce66aa0)

It's like that on develop.element.io as of writing.

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io / element.ems.host

### Will you send logs?

No

**Comment by germain-gg** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11103
