### ISSUE TITLE
Add generic and persistent deprecation messaging for customisation points in release notes

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25734]
Following on from https://github.com/vector-im/element-web/issues/25733, we should include the same messaging in release notes – in a persistent way. This task can be closed once the messaging is agreed upon and included in our release docs.

**Comment by t3chguy** [comment]
https://gitlab.matrix.org/new-vector/internal/-/wikis/Element-Web#element-web - retasking to @andybalaam as the next release person
