### ISSUE TITLE
Element Call integration is known to be broken on develop and Nightly

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#25737]
### Steps to reproduce

1. Try to use an Element Call video room or group call

#### What did you expect?

It works

#### What happened instead?

You can't join the call; see https://github.com/vector-im/element-call/issues/1201

### Will you send logs?

No

**Comment by grahhnt** [comment]
[element-call was updated yesterday](https://github.com/vector-im/element-call/releases/tag/v0.4.0) and broke all group call channels

**Comment by robintown** [comment]
Fixed by https://github.com/vector-im/element-call/pull/1234
