### ISSUE TITLE
probleme de connexion+probleme sur google form +bug sur application window

### ISSUE THREAD

**Issue by jblambert210474** [vector-im/element-web#25742]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…
#room:jbl210474.com n’est pas accessible pour le moment.
Réessayez plus tard ou demandez à un administrateur de salle ou d’espace de vérifier si vous y avez accès.

M_UNKNOWN a été retourné alors qu’il tentait d’accéder à la pièce ou à l’espace. Si vous pensez que ce message s’affiche par erreur, veuillez [envoyer un rapport de bogue](https://github.com/vector-im/element-web/issues/new/choose).
de plus ,sur mon application window,la barre laterale ne s'affiche pas et sur google form ,il m'est impossible de telecharger la preuve de mon invitations.cordialement

#### What happened instead?
me too but different bugs block me in the advance of my experience

### Operating system

window

### Application version

Version voyante: !! UNSET!! Version Olm: 3.2.12

### How did you install the app?

a partir du qr code de google form sur mon android

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
1. We only accept bug reports in English, please make use of translation in future
2. A room being inaccessible is a server error and not something a client can do anything about.
3. You're running a custom version which is also without support.

I suggest reaching out to your Matrix server for help, you didn't fill in that bit of the template so can't point you better.
