### ISSUE TITLE
Room events have different sizes of text on room creation

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25778]
### Steps to reproduce

1. Where are you starting? What can you see?

![Screenshot 2023-07-12 at 15 40 47](https://github.com/vector-im/element-web/assets/89144281/a5073d34-108d-43a7-90e9-f01ed2a87dcc)

3. What do you click?

I created a room 

5. More steps…

#### What did you expect?

The same size text

### Operating system

macOS

### Application version

Element Nightly version: 2023070701 Olm version: 3.2.14

### How did you install the app?

Nightly: Element.io

### Homeserver

ems.one.host

### Will you send logs?

No

**Comment by robintown** [comment]
Now they're different colors, too: 
![Screenshot 2023-07-12 at 16-39-00 Element 10 Element Web Announcements](https://github.com/vector-im/element-web/assets/48614497/9b406eec-168d-4869-a80c-840cd46555c0)
