### ISSUE TITLE
Element-R: `bootstrapCrossSigning` does not check if the cross-signing keys are in secret storage

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25781]
https://github.com/matrix-org/matrix-js-sdk/blob/e82b5fe1dbf5302ad70c02f3d648f20778e12119/src/rust-crypto/CrossSigningIdentity.ts#L44

Even if we don't have the secret-storage key which would allow us to decrypt the cross-signing keys, checking if the private keys are in secret storage might prevent a FUBAR where we accidentally overwrite a perfectly good set of keys (cf https://github.com/vector-im/element-web/issues/25773)

**Comment by richvdh** [comment]
The documentation on `bootstrapSecretStorage` says:

> If everything is already set up, then no changes are made, so this is safe to run to ensure cross-signing is ready for use.

That's absolutely not true at the moment and this is a big footgun.

**Comment by BillCarsonFr** [comment]
Will be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3731

There are test (unit) to check that nothing is done if all is setup.

But I think that we should ensure that the current user keys have been downloaded
