### ISSUE TITLE
Element Call 1:1 doesn't connect

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#25784]
### Steps to reproduce

1. call someone in a DM

#### What did you expect?
working call

#### What happened instead?
screen stays on "connecting"
other party sees black screen

### Operating system

Windows

### Homeserver

elementio

### Will you send logs?

Yes

**Comment by kongo09** [comment]
sorry, had to cancel

**Comment by dbkr** [comment]
We will need logs both from you and the party you're calling to investigate. We can help if you're having trouble submitting them.

**Comment by t3chguy** [comment]
Hi, I'm going to close this issue for now as there is not enough info here for us to be able to action it. Please feel welcome to reopen or ask me to reopen the issue if you update the description with steps/screenshots/video/more details so our developers can have a look at it.
