### ISSUE TITLE
Support for custom matrix.to links

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-web#25780]
#### What would you like to do?

Allow administrators to replace all matrix.to links with self-hosted services

#### Why would you like to do it?

Access to matrix.to may be blocked in some countries and regions, and some people may have concerns about large volumes of data flowing through matrix.to

#### How would you like to achieve it?

Add custom configuration for this

**Comment by MomentQYC** [comment]
> You can already override it with permalinkPrefix in config as per https://github.com/vector-im/element-web/blob/develop/docs/config.md

Will this replace **all matrix.to links** ?

**Comment by t3chguy** [comment]
It intends to. If you find any it doesn't feel free to open a defect listing them
