### ISSUE TITLE
matrix.org Homeserver Outage Caused by SSL Certificate Error as Reported by Cloudflare

### ISSUE THREAD

**Issue by 8227846265** [vector-im/element-web#25798]
### Steps to reproduce

Step 1: Visit https://app.element.io/#/login

![image](https://github.com/vector-im/element-web/assets/66582769/6f1bf5ca-942c-4e99-a17e-42f110f1156a)

#### What did you expect?
Can log in

#### What happened instead?
Cannot log in

### Operating system

Windows

### Browser information

Brave v1.52.130

### URL for webapp

https://app.element.io/#/login

### Will you send logs?

No

**Comment by 8227846265** [comment]
![image](https://github.com/vector-im/element-web/assets/66582769/fc66e1de-63e3-46de-9863-d83d59119e9b)

Sending on the desktop / mobile app produces this error today on both mobile data and Wi-Fi.

**Comment by SolninjaA** [comment]
I'm experiencing the same problem, it also doesn't work on the desktop client. I have tried editing the config for Element Desktop but I had no luck. When I went to https://matrix-client.matrix.org Cloudflare says that the SSL certificate is invalid.

For the second comment made by the original poster:
I also get that same error on mobile and desktop.

**Comment by felixsinger** [comment]
Yeah, seems to be a problem with their SSL certificate. sigh.

**Comment by SolninjaA** [comment]
My only guess is that the SSL certificate for https://matrix-client.matrix.org has expired or has some sort of misconfiguration. For context, this is what I see:

![image](https://github.com/vector-im/element-web/assets/51935570/08388594-a36f-4e13-9052-69fe76dead84)

![image](https://github.com/vector-im/element-web/assets/51935570/6cc3e50d-a314-4328-96ad-f5fd05a3a8bd)

**Comment by Zero3K** [comment]
That link is giving a 404 error.

**Comment by SolninjaA** [comment]
> That link is giving a 404 error.

Oh, interesting. You are talking about this link, right?
https://matrix-client.matrix.org/

**Comment by Zero3K** [comment]
Yes.

**Comment by SolninjaA** [comment]
> Yes.

Hm, I see. Maybe the problem is different for certain people? For me it shows a Cloudflare error page as I mentioned above.

**Comment by Zero3K** [comment]
![image](https://github.com/vector-im/element-web/assets/6194332/cf707db3-fc45-43ee-bdeb-bca9a43924b0)

**Comment by alphapapa** [comment]
Ended up here while looking for the proper way to report this outage.  It's not actually a problem with Element, but with the matrix.org homeserver configuration, affecting all users on all clients.  Interestingly, https://status.matrix.org/ shows no problems, suggesting that a test needs to be added to catch this kind of problem.

**Comment by felixsinger** [comment]
Could you try if it's working again for you? It seems it does for me.

**Comment by alphapapa** [comment]
> Could you try if it's working again for you? It seems it does for me.

Indeed, it works now.  But about 10 minutes ago, it was happening intermittently, until it started happening constantly.  Maybe some kind of configuration rollout that was taking time.

Anyway, would be good if https://status.matrix.org/ caught this kind of problem.

**Comment by SolninjaA** [comment]
> ![image](https://user-images.githubusercontent.com/6194332/253463136-cf707db3-fc45-43ee-bdeb-bca9a43924b0.png)

Hm, now I am getting that 404 page. It must have just changed to a 404 error now.

**Comment by felixsinger** [comment]
> > Could you try if it's working again for you? It seems it does for me.
> 
> Indeed, it works now. But about 10 minutes ago, it was happening intermittently, until it started happening constantly. Maybe some kind of configuration rollout that was taking time.
> 
> Anyway, would be good if https://status.matrix.org/ caught this kind of problem.

Yeah, same for me. Is there a place where server maintenances are announced?

**Comment by SolninjaA** [comment]
> Could you try if it's working again for you? It seems it does for me.

Unfortunately, it's still not working for me.

**Comment by SolninjaA** [comment]
> > > Could you try if it's working again for you? It seems it does for me.
> > 
> > 
> > Indeed, it works now. But about 10 minutes ago, it was happening intermittently, until it started happening constantly. Maybe some kind of configuration rollout that was taking time.
> > Anyway, would be good if https://status.matrix.org/ caught this kind of problem.
> 
> Yeah, same for me. Is there a place where server maintenances are announced?

I think that would probably be https://status.matrix.org (to the best of my knowledge). It's interesting how it's not recognizing this problem though.

**Comment by alphapapa** [comment]
Makes me wonder if it's something to do with Cloudflare and geographical caching or redirects.  Maybe it only affects people accessing the server through certain paths.

**Comment by SolninjaA** [comment]
> 

I'm not 100% sure, if the Cloudflare error was still appearing I would agree with you but it seems that now it just shows a 404 page. Are you still seeing the Cloudflare error page?

**Comment by alphapapa** [comment]
> > Makes me wonder if it's something to do with Cloudflare and geographical caching or redirects. Maybe it only affects people accessing the server through certain paths.
> 
> I'm not 100% sure, if the Cloudflare error was still appearing I would agree with you but it seems that now it just shows a 404 page. Are you still seeing the Cloudflare error page?

Element and my other client are working fine now, with my account on matrix.org.

@SolninjaA What is your location?  Maybe consider posting a traceroute to matrix-client.matrix.org.  Also, should probably try the usual stuff like clearing browser cache, swapping VPN endpoint if relevant, etc.

**Comment by 8227846265** [comment]
Now working from my end as well. It seems to be a short outage, but it would be great for Element team to announce what caused the issue.

**Comment by alphapapa** [comment]
@8227846265 Please consider retitling this issue to something like "matrix.org homeserver outage caused by SSL certificate error as reported by Cloudflare".

**Comment by 8227846265** [comment]
@alphapapa Done

**Comment by SolninjaA** [comment]
> > > Makes me wonder if it's something to do with Cloudflare and geographical caching or redirects. Maybe it only affects people accessing the server through certain paths.
> > 
> > 
> > I'm not 100% sure, if the Cloudflare error was still appearing I would agree with you but it seems that now it just shows a 404 page. Are you still seeing the Cloudflare error page?
> 
> Element and my other client are working fine now, with my account on matrix.org.
> 
> @SolninjaA What is your location? Maybe consider posting a traceroute to matrix-client.matrix.org. Also, should probably try the usual stuff like clearing browser cache, swapping VPN endpoint if relevant, etc.

I've just tried to login, it seems like it may be working. I'm in Australia by the way.

**Comment by Zero3K** [comment]
![image](https://github.com/vector-im/element-web/assets/6194332/1956429c-ac0a-4b99-a8a6-2f327d948df4)

**Comment by SolninjaA** [comment]
> > > > Makes me wonder if it's something to do with Cloudflare and geographical caching or redirects. Maybe it only affects people accessing the server through certain paths.
> > > 
> > > 
> > > I'm not 100% sure, if the Cloudflare error was still appearing I would agree with you but it seems that now it just shows a 404 page. Are you still seeing the Cloudflare error page?
> > 
> > 
> > Element and my other client are working fine now, with my account on matrix.org.
> > @SolninjaA What is your location? Maybe consider posting a traceroute to matrix-client.matrix.org. Also, should probably try the usual stuff like clearing browser cache, swapping VPN endpoint if relevant, etc.
> 
> I've just tried to login, it seems like it may be working. I'm in Australia by the way.

It looks like I can see chat messages, so I feel inclined to say that it's working. Hopefully it stays that way.

**Comment by t3chguy** [comment]
Support for matrix.org is support@matrix.org - not the bug tracker for Element Web.

**Comment by alphapapa** [comment]
> Support for matrix.org is [support@matrix.org](mailto:support@matrix.org) - not the bug tracker for Element Web.

It would be good to make that more prominent somewhere on the matrix.org site.  Before I came here I clicked various links in the header and footer of the matrix.org Web site and couldn't find an obvious place to report a problem like this, and since I couldn't access the Matrix network...
