### ISSUE TITLE
Guest mode doesn't seem to work anymore

### ISSUE THREAD

**Issue by therealprof** [vector-im/element-web#25799]
### Steps to reproduce

1. Where are you starting? What can you see?

I used to sometimes check the behaviour of ignored users on a channel I administer via guest mode (which is of course enabled) in another browser. However for some months this feature doesn't work anymore and requires me to log in/sign up.

The channel in question is: https://app.element.io/#/room/#rust-embedded:matrix.org

2. More steps…

As can be seen in the screenshots, the settings should be alright:

<img width="787" alt="Screenshot 2023-07-14 at 08 49 09" src="https://github.com/vector-im/element-web/assets/3321888/472b9046-ad86-4b48-b0c9-142d26e4c1c4">

#### What did you expect?

Guest access to work.

#### What happened instead?

Sign up/Sign in requested.

<img width="1682" alt="Screenshot 2023-07-14 at 08 51 30" src="https://github.com/vector-im/element-web/assets/3321888/4326895a-eb95-4dad-989d-15dcc34629cf">

### Operating system

macOS

### Browser information

Firefox 115.0.2

### URL for webapp

https://app.element.io/#/room/#rust-embedded:matrix.org

### Application version

Element version: 1.11.35 Olm version: 3.2.14

### Homeserver

Matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
What you need isn't guest mode, its peeking. Peeking is controlled by History Visibility, it is only accessible when its set to `Anyone`.

Guest mode controls whether guest accounts can *JOIN* (not view) the room. Element hasn't allowed the use of guest accounts to join rooms in years due to UX issues around it, other clients still might.

**Comment by therealprof** [comment]
Thanks for the clarification, however "Peeking" is also enabled and it still doesn't work.

**Comment by therealprof** [comment]
<img width="1028" alt="Screenshot 2023-07-14 at 10 46 28" src="https://github.com/vector-im/element-web/assets/3321888/4a2c4507-37de-40e4-8e90-c15b7b9dae10">

**Comment by therealprof** [comment]
Again, this used to work in the past but has been broken for many months now.

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/f1f56bd1-55b9-4066-aab9-a9559511b856)

The matrix.org server disagrees

(matrix.org is involved as for guest-peeking the default HS of a given instance is used)

**Comment by t3chguy** [comment]
I suggest reaching out to support@matrix.org given their server seems broken
