### ISSUE TITLE
Topic changes look like messages compared to other state event changes

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25793]
### Steps to reproduce

1. Replicate the screenshot

#### What did you expect?

All state changes to not appear as messages.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/dc0d61ce-ace7-40e0-9bfa-53be5c29e34c)

(redaction of username done by me)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023071301 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment]
<img width="387" alt="Screenshot 2023-07-17 at 09 57 06" src="https://github.com/vector-im/element-web/assets/769871/73dca385-7e37-4d4b-b401-24527942855d">

Already fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11252
