### ISSUE TITLE
Enhancement of Element X on Web and desktop application

### ISSUE THREAD

**Issue by alfredonodo** [vector-im/element-web#25807]
### Your use case

Hi,
I have read the exciting news about [Element X](https://element.io/blog/element-x-experience-the-future-of-element/). However, I don't understand if the speed improvement with the rust SDK is limited to mobile applications or will it also be available for web and desktop applications.
Also, are you going to abandon electron which is a very slow and resource consuming framework?
Thank you

**Comment by t3chguy** [comment]
# This is a bug & feature tracker, not a place of support. I suggest `#element-web:matrix.org` in future. 

The features of Element X coming to EW/ED are:

+ Sliding sync (Labs)
+ Rust crypto (Labs)
+ UX overhaul from Element X redesign

The underlying rust SDK will not be used.

> Also, are you going to abandon electron which is a very slow and resource consuming framework?

Nope, we don't have the bandwidth to maintain a standalone native app. Other Matrix clients exist for this purpose. The Electron app is basically free to maintain given it builds upon the primary platform of Element Web and requires zero additional UI to be built. https://github.com/vector-im/element-desktop/issues/771 is the issue tracking replacing Electron.
