### ISSUE TITLE
Room scroll state is broken

### ISSUE THREAD

**Issue by greentore** [vector-im/element-web#25810]
### Steps to reproduce

Since v1.11.25 of Element (matrix-react-sdk v3.68.0) the scroll state of rooms isn't saved.
Seems like the issue is localized in `src/components/structures/RoomView.tsx` and caused by `this.state.roomId` being initialized to `undefined` instead of `null` and therefore failing a strict check at line 746.

#### Steps to reproduce
1. Open any room and scroll up
2. Open some other room
3. Go back the the first room

#### What did you expect?
The scroll state is restored.

#### What happened instead?
I see the bottom of the room.

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/db6ee53535a1a189bc1c13a6a31ef597c7cbb4a8

**Comment by richvdh** [comment]
> Regressed by [matrix-org/matrix-react-sdk@db6ee53](https://github.com/matrix-org/matrix-react-sdk/commit/db6ee53535a1a189bc1c13a6a31ef597c7cbb4a8)

ie, https://github.com/matrix-org/matrix-react-sdk/pull/10229
