### ISSUE TITLE
Notices have lost their opacity layer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25826]
### Steps to reproduce

1. Send a notice with some custom markup, such as from a bot

#### What did you expect?

Opacity to dull the message contents, like in the old design:

![image](https://github.com/vector-im/element-web/assets/1190097/7356cf31-2c1b-4dd2-b6b8-45b145f868b1)

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/b84bdac5-476b-4e40-913b-5e7298b648fb)

The green text is vibrant (unexpected) and the room pill is less translucent (also unexpected)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023071901 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment]
Relying on opacity has created a class of issues regarding color contrast and accessibility so we're diverging from that.

Notices is now using `--cpd-color-text-secondary` (see https://compound.element.io/?path=/docs/tokens-semantic-colors--docs) which is sufficiently different from the primary events who you to be able to distinguish them.

Same goes for the pills, as it'd make matter worst for cases like https://github.com/vector-im/element-web/issues/22134

**Comment by t3chguy** [comment]
> the primary events who you to be able to distinguish them.

Only if they don't specify a colour using `data-mx-color` or font `color`
