### ISSUE TITLE
Font sizes are a bit wonky after 1.11.36

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#25828]
### Steps to reproduce

1. Since the update to 1.11.36, font sizes are inconsistent and a bit wonky

#### What did you expect?
uniform font sizes like in 1.11.35
#### What happened instead?
<img width="693" alt="grafik" src="https://github.com/vector-im/element-desktop/assets/7354506/fd0a31b0-12f2-43c7-8ba6-4b8f8fe08756">

<img width="840" alt="grafik" src="https://github.com/vector-im/element-desktop/assets/7354506/4f16d88f-8661-429e-83aa-d45ac0fe2a0a">

### Operating system

macOS

### Application version

Element: 1.11.36 Version von Olm: 3.2.14

### Will you send logs?

No

**Comment by germain-gg** [comment]
Thank you for the report,

These two issues have already been fixed, but please do let us know if you encounter other things that look out of place.

- https://github.com/matrix-org/matrix-react-sdk/pull/11285
- https://github.com/matrix-org/matrix-react-sdk/pull/11181
