### ISSUE TITLE
Uses 100% GPU when accepting an invite

### ISSUE THREAD

**Issue by Torxed** [vector-im/element-web#25820]
### Steps to reproduce

Get a slow-responding invite, like a libera.chat IRC bridge invite.
![rec](https://github.com/vector-im/element-web/assets/861439/e774cf96-db52-4203-a6bc-4fc2f1409b49)

### Outcome

The CPU or GPU to not overload when pushing the button.
In general, the invite window draws about 10-20% GPU/CPU by having it open as well.

### Operating system

Arch Linux

### Browser information

Chromium 114.0.5735.133

### URL for webapp

element-v1.11.28

### Application version

element-v1.11.28

### Homeserver

Synapse 1.77.0

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
v1.11.18 is from 1/3rd of a year ago, install a modern version and feel free to open a new issue.

**Comment by Torxed** [comment]
As you wish!

**Comment by t3chguy** [comment]
Thank you very much
