### ISSUE TITLE
Avatar comes over the timestamp in `/me` messages

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#25835]
### Steps to reproduce

1. Send a /me message

2. See:

![image](https://github.com/vector-im/element-web/assets/62639087/03011bc2-3d09-421e-85cc-6c79bab4be7a)

#### What did you expect?

Avatar to be aligned on top of the timestamp

#### What happened instead?

Avatar aligned over the timestamp, blocking it

### Operating system

Fedora

### Browser information

Firefox Nightly 117.0a1 (2023-07-20)

### URL for webapp

https://chat.fairydust.space/

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by bbhtt** [comment]
Could be related to https://github.com/vector-im/element-web/issues/25343, but that seems to be for video rooms/threads panel?

**Comment by ara4n** [comment]
dup https://github.com/vector-im/element-web/issues/2284 sadly
