### ISSUE TITLE
Completing registration does not log me in and instead takes me to registration page

### ISSUE THREAD

**Issue by anushaharish538** [vector-im/element-web#25832]
### Steps to reproduce

It happens in both the scenarios for the users registered with invite link and without invite link.
 Steps to reproduce.

1. User A registers and received confirmation email. The confirmation link address is https://chat.viee.com/_matrix/client/unstable/registration/email/submit_token?token=geKhnRODcntnbFoWDbkAPJUzzsfdUgIY&client_secret=On74yL0LkPHApNuUmMmtBmLrc0VMeF8Z&sid=QtQeefwUWzazXVHK

2.  User clicks on confirmation link. It goes to registration instead of login page

Register with invite:

1. User A sends invitation to User B
2. User B clicks on invitation link and registers and he gets confirmation link.
3. User B clicks confirmation link  and it forwards to registration page again 

### Outcome

When user clicks on email confirmation link  it should get logged IN automatically but it send to registration page again

### Operating system

WEB

### Application version

1.11.31-rc.2

### Homeserver

Synapse 1.18

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
No

Please send logs as you were asked to in the room.

**Comment by t3chguy** [comment]
> 1.11.31-rc.2

Also please update, we don't accept bug reports on old versions, especially unstable ones.

**Comment by anushaharish538** [comment]
> > 1.11.31-rc.2
> 
> Also please update, we don't accept bug reports on old versions, especially unstable ones.

I tried in new version also same thing happens. I just download from https://github.com/vector-im/element-web/releases yesterday.

**Comment by t3chguy** [comment]
Can reproduce this sporadically, it seems like a race condition

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/23601

**Comment by anushaharish538** [comment]
Do in need i update my synapse?
