### ISSUE TITLE
Joining a suggested room from room list switches to Home space

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-web#25838]
### Steps to reproduce

1. Open a Space with more than one suggested room (e.g. #space-test-issue-25838:matrix.mit.edu), such that the room has no preview.
2. Click the suggested room in the left sidebar
3. Below the message saying "This room can't be previewed", click on the join button

See the screencast in the comment below.

#### What did you expect?

Suggested room opens and I'm still on the space, so the sidebar should show that I am in the room that I just joined and the other suggested rooms in the space

![image](https://github.com/vector-im/element-web/assets/24363938/c9d4965d-cfe4-416d-9ffa-6af122ebed6d)

#### What happened instead?

I am kicked to the home page and if I want to continue browsing the space I have to manually navigate to it again.

![image](https://github.com/vector-im/element-web/assets/24363938/dab74f24-e612-4864-9c98-db5ebc5d1e68)

### Operating system

Linux

### Browser information

Firefox 115.0.2

### URL for webapp

Element web 1.11.36

### Application version

Element web 1.11.36

### Homeserver

Synapse 1.88.0+jammy1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Steps to reproduce
Open a Space with more than one suggested room
Join the suggested room

Please be clearer with your steps, there's multiple ways to join the suggested room, be explicit in the exact interactions you are performing so someone else can reproduce. Alternatively a screen recording screams a thousand screams

**Comment by gabrc52** [comment]
Here is the screen recording

[Screencast from 2023-07-25 11-49-26.webm](https://github.com/vector-im/element-web/assets/24363938/985326e1-0903-4d60-ba51-ea0459a0503e)

**Comment by gabrc52** [comment]
I can reproduce this as well from app.element.io with a matrix.org account.

Space for testing: https://matrix.mit.edu/#/room/#space-test-issue-25838:matrix.mit.edu

[Screencast from 2023-07-28 12-20-44.webm](https://github.com/vector-im/element-web/assets/24363938/3a697239-2830-4b4e-9ca3-a40e8c8bbf1f)

Something that differs in your screen recording is that the space had a preview for you, but did not have a preview for me.
