### ISSUE TITLE
Reaction causes stuck notif

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#25845]
### Steps to reproduce

I have a thread that causes a stuck notification.

There is a reaction added to it, that i can see because i show hidden events, but it's nowhere to be seen on events that are part of the thread.

**Room ID:** `!YJUhVuekhcNbIWyeId:matrix.org`
**Event ID:** `$MN4HBucf_lbw7dMbT00kVjIliSMz45q-bNkWmDhLJtI`
**Thread root ID:** `$92it2FcIbiaVd6sUjZk2iI-Foe085CDdlJ6nW8f4LB4`
**Related event ID:** `$PFSlRGkMAxc_PlMIykb8YnpOi1ED_2xXl2AyaT2TJJg`

<img width="472" alt="Screenshot 2023-07-25 at 13 30 28" src="https://github.com/vector-im/element-web/assets/769871/71c2c039-4b56-4fc5-a65a-3f3d004972b8">

#### What did you expect?

No stuck notification

#### What happened instead?

Stuck notification

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
I believe this is fixed due to earlier work in Stuck Notifications, please shout if you can reproduce on latest versions.
