### ISSUE TITLE
Missing messages in timeline

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#25840]
### Steps to reproduce

I sent a message in an E2EE room from Element Android 4 days ago. The latest Nightly (Element Nightly version: 2023072301 Olm version: 3.2.14) and https://develop.element.io do not render it in the timeline, production Element Desktop (Element version: 1.11.36 Olm version: 3.2.14) does.

### Outcome

The message is not rendered. I will rageshake.

### Operating system

Arch Linux

### Application version

See above

### Will you send logs?

Yes

**Comment by davidegirardi** [comment]
I found another instance of this and rageshook.

Both are replies to messages in the main timeline.

**Comment by t3chguy** [comment]
@davidegirardi sounds like this will be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3615

**Comment by davidegirardi** [comment]
I confirm it's fixed.
