### ISSUE TITLE
information while login about last verified sessions by the same device and client-program (browser/app)

### ISSUE THREAD

**Issue by benny-de** [vector-im/element-web#25843]
### Your use case

In my setup I use my own matrix and element-web system. I use it only with one device and one browser.
When I update my element-web it is possible I forgot to log out before. After an update I verify a new session by my laptop/firefox.                     
A user wrote me via an other channel about problems to decrypt my matrix chat. There was more than one session.
After I terminate the older sessions this user was able to decrypt my matrix chat again.                                                     
So my idea is it could be helpful to get an information at login, if there are older verified session by the same device & client (browser/app).

**Comment by t3chguy** [comment]
> So my idea is it could be helpful to get an information at login, if there are older verified session by the same device & client (browser/app).

This would require deep profiling/fingerprinting of your computer & browser, this goes against the privacy goals of Element.
