### ISSUE TITLE
Read marker updates cause notifications

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#25849]
### Steps to reproduce

1. Send a message in a room
2. Switch to another room
3. Wait for the other person to read your message from 1.
4. Watch the room from 1. be marked as unread
5. If you have all notifications to noisy etc, receive notifications for it

#### What did you expect?
No notifications for read markers

#### What happened instead?
Unread markers everywhere

### Operating system

arch

### Browser information

Firefox 115.0.2

### URL for webapp

develop.element.io

### Application version

Element version: cc8afed1968f-react-c57a4cb09090-js-de7959de6c5c Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
@HarHarLinks Thank you for opening an issue. Unfortunately there is not enough information there for me to be able to reproduce it. Please update the description with steps/screenshots/video/more details so our developers can have a look at it.

Can you send the output of the notifications debug (dev tools → notifications debug) in addition to a rageshake? You can access the dev tools from the room context menu without opening the room, if development mode is enabled. Then I can have a look if I can find something about the room or event in the logs.

**Comment by HarHarLinks** [comment]
It was happening all the time this morning, even confirmed by another user, but I have trouble repro-ing on Element version: cc8afed1968f-react-e33a7e41a441-js-29b815b6781d Olm version: 3.2.14. I guess I can close this until it returns.

Rageshake was submitted alongside this report. I don't understand how the notifications debug info can be useful as I have to be in the room which means the notification gets resolved while I open the debug menu.

**Comment by weeman1337** [comment]
> I don't understand how the notifications debug info can be useful as I have to be in the room which means the notification gets resolved while I open the debug menu.

Quote from above:

> You can access the dev tools from the room context menu without opening the room, if development mode is enabled.

![image](https://github.com/vector-im/element-web/assets/6216686/271e7337-8eb0-440c-a652-5fc9d96a108a)

**Comment by HarHarLinks** [comment]
derp, thanks TIL
