### ISSUE TITLE
Stuck unread messages badge in 1.11.36

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#25846]
### Steps to reproduce

I don't know, sorry. Notifications debug:

```
Room ID: !muWFoAazesOnQSqwHZ:matrix.org
Room status
  Room unread status: Bold
  Notification state is mentions_only
  Room is encrypted ✅
Main timeline
  Total: 0
  Highlight: 0
  Dot: true
  User read up to: $oysAhUmIjVOyiggu3MqMDjT0Ma0j25j-lLGinhmSkog
  Last event:
    ID: $ELGWc-Sla59GvdCi3-Es68AGDZfkQBSNYghan9zPG2w
    Type: m.reaction
    Sender: @ganfra:matrix.org
Threads timeline
```

#### What did you expect?

Right clicking on a room in the list and using 'Mark as read' should clear unread indicator (if not reading all messages).

#### What happened instead?

Unread dot is persistent after reading all messages / using 'Mark as read', and even reacting to an arbitrary message.

### Operating system

arch linux

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### How did you install the app?

arch linux package

### Homeserver

Synapse 1.76.0

### Will you send logs?

No

**Comment by weeman1337** [comment]
@jplatte Thank you for opening an issue. Unfortunately there is not enough information there for me to be able to reproduce it. Please update the description with steps/screenshots/video/more details so our developers can have a look at it. It would be helpful if you can send logs/rageshake immediately after this happened.

**Comment by t3chguy** [comment]
This is believed to have been fixed on develop. If you see this again there or in the future 1.11.37 please open a new issue with new logs (new logging was added)
