### ISSUE TITLE
media download fails with cryptic error if it is larger than max_upload_size

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2585]
If you try to download an attachment over federation which is larger than the local `max_upload_size`, you get the following unhelpful error:

    {"errcode":"M_UNKNOWN","error":"Failed to fetch remoted media"}

**Comment by ara4n** [comment]
...and even that error doesn't make it as far as Riot :(

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/1992 fixes the server side of this, to give:
```
{
    "errcode": "M_TOO_LARGE",
    "error": "Requested file is too large > 10485760 bytes"
}
```

I think there is still a problem in the Riot UI, though.

**Comment by turt2live** [comment]
This appears to be a synapse bug, still. At least while testing in chrome, it appears as though synapse isn't reading the entire request body, and chrome ignores the http status code and gives it's own error: ERR_CONTENT_LENGTH_MISMATCH. So even though synapse is throwing a 413 Request Too Large back, Chrome (and probably other browsers) are considering it as some other error. Synapse should probably just read the entire body into /dev/null to prevent it from erroring out.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/3918

**Comment by t3chguy** [comment]
This got fixed
