### ISSUE TITLE
Rename "search" to "Navigation" for room quick search navigation

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#25868]
#### What would you like to do?
Rename "Search" to "Navigation" as it is really about navigating and searching for rooms
#### Why would you like to do it?
Because currently the most obvious place to look for search is only searching rooms, which is more about finding rooms, and if you want to search content, it's behind a button.

#### How would you like to achieve it?
Gather feedback here if it's wanted and then create a pull request to change the localisation/text of the navigation field

### Have you considered any alternatives?

no

### Additional context

![grafik](https://github.com/vector-im/element-desktop/assets/7354506/b5003972-817e-4ec8-a203-6dfc08be2aa8)

**Comment by t3chguy** [comment]
> and searching for rooms

As you literally said, its about searching for users & rooms. I think this is an issue of a language specificity, where in your language (German?) Navigation makes more sense, but in English it does not. If you wish to change the translation then see https://github.com/vector-im/element-web/blob/develop/docs/translating.md

**Comment by JMoVS** [comment]
no, my point was that it's not clear that "search" here means "search for rooms". Intuitively, I would otherwise maybe change to to "Search Rooms & Users" rather than just "Search". It is quite telling that there is an additional notice that one can search content:

<img width="607" alt="grafik" src="https://github.com/vector-im/element-web/assets/7354506/2fb175d6-b9f3-45c5-a52d-5bad45f025b4">

If instead of "Search", it would show the looking glass and then "Search Rooms&Users", I think that would already help a lot

**Comment by t3chguy** [comment]
<img width="187" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/fc6f155d-687c-4e21-8052-20eb7bdc249e">

`Search Rooms & Users` doesn't fit in this space.
It can also be used to search for Spaces if you have that labs flag enabled. And in future also messages. So it is really intended as the search for everything going forward.
