### ISSUE TITLE
No User Can Join My ROOM. They get 'link malformed' message

### ISSUE THREAD

**Issue by optimumpr** [vector-im/element-web#25870]
### Steps to reproduce

Regardless of the clients: Android, Desktop and Browser, users can't join my room:

#JaguarOS:nitro.chat with the link https://matrix.to/#/#JaguarOS:nitro.chat

The link is properly generated and when clicked in browser, it points to my room, but from a client such as element or shildichat, the response is 'link malformed'.

The room is public with encryption disabled. I have no problem login in on shildichat, web app and web browser, but no user can join. Please help.

#### What did you expect? 
Users with invite link able to join

#### What happened instead?
They get a message: link malformed

### Operating system

Android

### Browser information

Chromium 115.xxx

### URL for webapp

https://matrix.to/#/#JaguarOS:nitro.chat

### Homeserver

nitro.chat

### Will you send logs?

Yes

**Comment by Half-Shot** [comment]
I managed to type `/goto https://matrix.to/#/#JaguarOS:nitro.chat` in Element Web and it worked for me.

**Comment by optimumpr** [comment]
I can see that in the room. Could you try to join from an Android client please?

**Comment by optimumpr** [comment]
When I changed the link from 

https://matrix.to/#/#JaguarOS:nitro.chat

to

https://app.element.io/#/room/#JaguarOS:nitro.chat

then the link work, but it could only be done manually. Apparently, nitro.chat server does not work with 'matrix.to' links. I think this needs to be looked into.

**Comment by t3chguy** [comment]
> I have no problem login in on shildichat, web app and web browser

This repo is for the web/desktop apps only. https://github.com/vector-im/element-android for Element Android issues please.

> then the link work, but it could only be done manually. 

https://github.com/vector-im/element-web/assets/2403652/db2217a9-c2a6-42f9-8634-0b2dc477ee12

Works just fine for me.
