### ISSUE TITLE
Non highlight messages do not increase count

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#25881]
### Steps to reproduce

1. Receive a message in an encrypted room

#### What did you expect?

To have a notification count increase

#### What happened instead?

Nothing

####

I have the **Notification Settings** beta enabled.
The incriminated room has "Match default settings"

Only "highlights" caused a count increase

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Sounds like a subset of https://github.com/vector-im/element-web/issues/25794

**Comment by germain-gg** [comment]
I think it's quite different, mentions work perfectly fine. I've been using the beta for a little while now and I only started noticing it with the last nightly update.

**Comment by daniellekirkwood** [comment]
Same here - rooms that are marked "Default" are no longer incrementing the count but should be

**Comment by weeman1337** [comment]
I did not activated the new notification settings and see the same problem. Logs sent.
