### ISSUE TITLE
Unable to reject invite to deleted room

### ISSUE THREAD

**Issue by kieranlane** [vector-im/element-web#25895]
### Steps to reproduce

1. `User A` creates `Room A`
2. `User A` invites `User B` to `Room A`
3. Synapse Admin deletes `Room A`
4. `User B` tries to reject invite to `Room A`

#### What did you expect?

Step 4: `User B` tries to reject the invite to `Room A`, the invite is removed from the list of invites.

#### What happened instead?

Step 4: `User B` tries to reject the invite to `Room A`, `User B` is unable to remove the invite to `Room A`:

![image](https://github.com/vector-im/element-web/assets/7443512/16851d46-be19-4d63-9250-2556e07e5b87) 

### Operating system

Windows

### Browser information

Chromium: 115.0.5790.114

### URL for webapp

app.element.io

### Application version

Element version: 1.11.36 Olm version: 3.2.14

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue with your server not informing your client that the room went away via `/sync`
