### ISSUE TITLE
New threads/new thread messages always show "new messages" at already 20x times read other threads too

### ISSUE THREAD

**Issue by Baertram** [vector-im/element-web#25907]
### Steps to reproduce

1. Where are you starting? What can you see?
I start at the webbowser element view of a "Gitter" element room: https://app.gitter.im/#/room/#esoui_esoui:gitter.im
I'm using the Dark theme.
I see a notification at teh top right "Thread" icon, that new messages occured. I click that therad icon and the threads list opens at the right.
I click the new message (it was a new started thread) and read all new messages, scroll that thread and check screenshots etc.
This thread was totally read!

2. What do you click?
I click on the back link/icon at the top left of that thread to get back to the threads list.
The threads icon at the top still shows there are new messages?
So I scroll up to the other threads and there are "always" (happens for each new thread started, or each new thread message in an existing thread) shown like 3 threads which have been completely read, and where there are definately NO new messages! 
They always show a small white circle telling me there are new messages.

No one updated that threads since >5-7 days meanwhile!
No one posted in them!
They just ALWAYS show as new and this is annoyign as you cannot really see IF there are new messages in threads, because of these false positives.

3. More steps…
Maybe those threads show a "new messages2 because there were added external links and/or images to them?

These are the links to the 3 threads which always show "false positive" new messages:
1) https://matrix.to/#/!NPLzQDvOPApvHsZfEu:gitter.im/$LIzACcE_xMzYKIFedA8FKgN4aUUajdLw-gANdPgSGl8?via=gitter.im&via=matrix.org&via=ntwrk.space

2) https://matrix.to/#/!NPLzQDvOPApvHsZfEu:gitter.im/$j4JPJq9PjURDkyrMRjLUXQL7pxPV92d5-wn5ju2CipQ?via=gitter.im&via=matrix.org&via=ntwrk.space

3)https://matrix.to/#/!NPLzQDvOPApvHsZfEu:gitter.im/$4s7_fDjdR1VK1uckJppbeGBDhLFX3YpxYzYaSvWEfOs?via=gitter.im&via=matrix.org&via=ntwrk.space

Please fix this annoying bug so I can see if there really exist new messages and posts... I manually have to scroll to each of these "false positive" threads then open them and scroll ALL text to remove the "new messages" white circle at them. This happns like 20x a day and is just annoying.

Isn't there any "mark all as read" button in the browser somewhere? If not: PLEASE ADD IT

Many thanks

#### What did you expect?
No "new messages" white circle icon at the threads if there actually were no new messages anymore

#### What happened instead?
A white circle shows at the threads icon AND at 3 threads where there actually were no new messages since days/weeks!

### Operating system

Windows

### Browser information

Microsoft Edge Version 115.0.1901.188 (Official Build) (64-Bit)

### URL for webapp

https://app.gitter.im/#/room/#esoui_esoui:gitter.im

### Application version

Version Gitter: 1.11.36 Version Olm: 3.2.14

### Homeserver

gitter.im ??? 

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Will you send logs?
No

Without logs there is nothing to investigate

Closing in favour of https://github.com/vector-im/element-web/issues/24392
