### ISSUE TITLE
Constantly flashing online status alternately.

### ISSUE THREAD

**Issue by YamatoRyou** [vector-im/element-web#25900]
### Steps to reproduce

n/a

#### What did you expect?
n/a

#### What happened instead?
Since 1.11.37, this problem occurs when the other party is online. It disappears when the other party exits the application (not logout).

The specific performance is shown in the figure, and the Web/desktop version will appear.
![{33E0DE87-909A-7995-0C74-417FC32CC52B}](https://github.com/vector-im/element-web/assets/48104960/d0de4cd3-6bae-475f-9e25-392ecbcf54b7)

### Operating system

x64 Windows 11

### Browser information

Chromium 102.0.5005.167

### Application version

Element Web: b404d2d01406-react-89a92c6351a4-js-88ba4fad716a, Element Desktop: 1.11.37

### Homeserver

Synapse 1.89.0

### Will you send logs?

No

**Comment by stanclai** [comment]
I guess, it's a part of more complex behavior. Yesterday, after the 1.11.37 release, I've noticed abrupt increase in nginx load caused by matrix users requests flood (subjectively it felt kind of DDoS). At the same time synapse metrics showed increase in presence events frequency. After I've turned off presence support in synapse config file, requests flood stopped.

**Comment by davidegirardi** [comment]
Related to https://github.com/matrix-org/synapse/issues/15824? Disabling presence made the "spamming" of sync requests calm down.

**Comment by t3chguy** [comment]
Related https://github.com/matrix-org/synapse/issues/16039

**Comment by t3chguy** [comment]
Possibly related https://github.com/matrix-org/synapse/issues/15082 and https://github.com/matrix-org/synapse/issues/12424

**Comment by QEDeD** [comment]
also relevant and has the next month milestone: https://github.com/matrix-org/synapse/issues/15980

**Comment by karolyi** [comment]
It is reproducible with two element-web clients, one being online while the other being away. They constantly keep switching the presence status back and forth.

It also results in a bigger server load as synapse doesn't take it well.

**Comment by karolyi** [comment]
@t3chguy yes they are. I'm on my own latest element-web instance with both clients.

**Comment by t3chguy** [comment]
Thanks @karolyi - reproduced it locally and it is a Synapse bug - opened https://github.com/matrix-org/synapse/issues/16057 instead of this issue

**Comment by visubesy** [comment]
This bug occurs again since the last update of Element (1.11.55). The server software hasn't been updated: matrix-synapse (1.95.1-1~bpo12+1; Debian bookworm-backports).
Please reopen this issue.

**Comment by t3chguy** [comment]
There have been 0 changes to presence, Synapse 1.95 is outdated, I suggest updating to 1.98 and if it recurs opening your own issue with logs from all running clients and from the server.

**Comment by visubesy** [comment]
> There have been 0 changes to presence, Synapse 1.95 is outdated, I suggest updating to 1.98 and if it recurs opening your own issue with logs from all running clients and from the server.

OK, I disabled presence on Synapse for now to workaround the high CPU load on Synapse caused by the flashing presence. I'm going to update Synapse to 1.98 as soon as it is available via Debian bookworm-backports.

**Comment by jlemangarin** [comment]
Still HARD flooding the browser and the server
1.98.0

**Comment by dima-karpenko-wand** [comment]
Any suggestions how to fight this issue?

**Comment by dima-karpenko** [comment]
Any suggestions how to fight this issue?

**Comment by t3chguy** [comment]
@dima-karpenko use a homeserver which doesn't exhibit this issue.

**Comment by dima-karpenko-wand** [comment]
@t3chguy I'm running my own homeserver, maybe I am missing some config? My synapse version is 1.117.0

**Comment by t3chguy** [comment]
1.117.0 is quite old. You'd need to seek support from them. This was a Synapse issue as tracked by https://github.com/matrix-org/synapse/issues/16057

**Comment by jlemangarin** [comment]
@dima-karpenko You can try [this patch](https://github.com/element-hq/synapse/issues/16843#issuecomment-2007807574)

**Comment by visubesy** [comment]
> Any suggestions how to fight this issue?

You can disable the presence feature on your Synapse server. This successfully workarounded the problem with the latest Synapse package available in Debian bookworm-backports (matrix-synapse 1.95.1-1~bpo12+1) for me. To do this, add the following line to your homeserver.yaml and then restart Synapse: `use_presence: false`

Without this workaround, the original problem appears (huge server load and flashing online status).
