### ISSUE TITLE
Audible ping but no badge on notifications for bot messages

### ISSUE THREAD

**Issue by davidegirardi** [vector-im/element-web#25904]
### Your use case

My default notification settings (new version) look like this:
![image](https://github.com/vector-im/element-web/assets/16451191/a22c0ee8-ac18-4714-8930-a1997b0a92c4)

If I set a room to notify for "All messages", when a bot writes a message I get an audible ping but no badge counter.
I don't know if it's related on the new notification settings or if it has always been like that. I do remember hearing pings with no counters before but never found an explanation until now.

I'd expect to either get a badge or no notification for bot messages at all.

**Comment by davidegirardi** [comment]
Additional context: Element Android shows a notification for the bot messages if the room is set to notify for all message.

**Comment by t3chguy** [comment]
@davidegirardi what version are you on? there's multiple changes in the area of notifications happening with every recent release.

**Comment by davidegirardi** [comment]
I have Element version: 1.11.36 Olm version: 3.2.14 and Element Nightly version: 2023080101Olm version: 3.2.14 running in parallel.

Nightly had the sound turned off. I'm turning it on and turning off the sound for production and see what happens.

**Comment by t3chguy** [comment]
There shouldn't be any differences in handling of audible pings, but definite changes to notification badges happening frequently. Things also depend on your specific push rules in account_data

**Comment by davidegirardi** [comment]
Then there was no difference today.

Nightly had issue with badges not showing up a few days ago but everything seems OK now.

**Comment by t3chguy** [comment]
> Nightly had issue with badges not showing up a few days ago but everything seems OK now.

That was https://github.com/vector-im/element-web/issues/25881

**Comment by davidegirardi** [comment]
Nightly works as expected: no ping and just a dot for bot messages.

See also: https://github.com/vector-im/element-web/issues/25794#issuecomment-1662048371 if your notification stop pinging at all and you run the notification settings beta.
