### ISSUE TITLE
Soft crash when enabling new room header labs flag

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#25909]
### Steps to reproduce

1. Open settings
2. Switch to labs
3. Enable `Under active development, new room header & details interface`
4. Wait for reload
5. Open a room if you haven't already

#### What did you expect?

Pretty new room header

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/2403652/7cd34f5f-354a-4b71-9065-97f73b430c80)

### URL for webapp

develop.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by germain-gg** [comment]
Ping @sandhose @Half-Shot 

Notice that version 0.2.2 was build with NODE_ENV=development and crashes react apps when used in production mode.
