### ISSUE TITLE
Allow the user to easily see the complete dat at which a message was sent, delivered, and read

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-web#25913]
#### What would you like to do?

I would like to easily be able to see the complete date at which a message was sent, delivered, and read.

#### Why would you like to do it?

This can be important information for troubleshooting, or just context for a conversation.

#### How would you like to achieve it?
 
Perhaps simply in the right click menu have a little prompt for "Information", or you could perhaps click on the timestamp beside the message to see it.

### Have you considered any alternatives?

no.

### Additional context

no.

**Comment by yash1378** [comment]
@germain-gg  can you please assing this issue to me

**Comment by K4LCIFER** [comment]
> You can by hovering over the timestamp, its the tooltip.

This is specifically for all 3 states that a message can be in. My original title was improperly worded (it was elaborated on in the body, though).
