### ISSUE TITLE
adding a new space just redisplays the add dialog

### ISSUE THREAD

**Issue by simonmichael** [vector-im/element-web#25916]
### Steps to reproduce

1. Viewing a space's room list, eg
2. Click the Add button
3. Click Add space
4. Fill out Name and Address fields (and optionally image and Description, same result)
5. Click Add button

#### What did you expect?

For this child space to be created and appear in the parent's room list

#### What happened instead?

The add dialog redisplays, showing no error.

### Operating system

macos ventura

### Application version

Element version: 1.11.37 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is specific to public subspace creation, private works fine.

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/10652
