### ISSUE TITLE
notif weird behavior

### ISSUE THREAD

**Issue by Philip-Roy** [vector-im/element-web#25917]
### Steps to reproduce

just weird stuff, no particular action I took tbh.

Got some very weird notification behavior: red notification for 1 new message in one room but no new messages in there, then 10 new black notif in another that just disappeared before I got there, all sort of weird stuff. I then cleared cache which seems to have helped. I also tried to update this morning but it failed with an error then said that no new version is avail. I am on  Element Nightly version: 2023073001 Olm version: 3.2.14

### Operating system

nightly Version 2023062901 (2023062901) on Mac.

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Your Nightly is over a month old. Please update, we have spent many many hours on fixes to notifications in that time. If you are still seeing it please open a new issue and make sure to send logs. I am not seeing any associated with this issue.
