### ISSUE TITLE
Searching fails to find matching messages

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/element-web#25919]
### Steps to reproduce

Search for "Multiply" in #gfx-firefox on chat.mozilla.org

#### What did you expect?

The following message from Wed, Jul 26 2023 to be in the search results:
`gw: we seem to spend quite a bit of main thread time on MotionMark Multiply doing display list building stuff`

#### What happened instead?
This message is not found

If I search for "MotionMark" it is found

### Operating system

macOS

### Application version

1.11.37

### Homeserver

mozilla.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Search in unencrypted rooms is done by the server, I suggest opening an issue in [Synapse](https://github.com/matrix-org/synapse/)

![image](https://github.com/vector-im/element-web/assets/2403652/b6e95fc2-7e16-4daa-8c3f-970038d8cbff)

The room does not appear to exist so I cannot even reproduce this.

**Comment by jrmuizel** [comment]
Here's a link to the room https://matrix.to/#/#gfx:mozilla.org. I'm not sure why you weren't able to find it.

**Comment by t3chguy** [comment]
Maybe because you wrote `#gfx-firefox` which is not the same as `#gfx:mozilla.org`. Either way, the search is done by the Matrix server, not the client.

**Comment by t3chguy** [comment]
https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3search & https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3publicrooms respectively
