### ISSUE TITLE
Regression: No longer easy to "close" or "stop" a jitsi widget video group call

### ISSUE THREAD

**Issue by JMoVS** [vector-im/element-web#25914]
### Steps to reproduce

1.  Start a jitsi widget based group call
2. Try to close it from within the room - previously there was a button so one could remove the widget for everyone
3. now one can only minimise the widget, but then one actually cannot easily get back to it

#### What did you expect?
Actually a group end call button, but at least the old option of removing the widget for everyone
#### What happened instead?
can only minimise the widget but no button on the widget itself to remove it. Only in the room sidebar

<img width="1065" alt="grafik" src="https://github.com/vector-im/element-desktop/assets/7354506/6afae003-332a-48d1-b587-f450d490e988">

### Operating system

macOS

### Application version

Version von Element: 1.11.37 Version von Olm: 3.2.14

### How did you install the app?

element.io/get-started

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11257
