### ISSUE TITLE
Quick reactions when hovering over message 

### ISSUE THREAD

**Issue by omyno** [vector-im/element-web#25927]
### Your use case

Slack and other messengers show quick reactions when hovering over a message. This saves one more click.

It would be great to have this in Element, too.

<img width="328" alt="image" src="https://github.com/vector-im/element-web/assets/2902513/fb1d1c72-059e-4f19-901d-98f48a0fb0f3">

**Comment by germain-gg** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/11238 which suggests a similar enhancement as what you've mentioned here
