### ISSUE TITLE
Sync Error 500 after Login response

### ISSUE THREAD

**Issue by constantinedev** [vector-im/element-web#25922]
### Steps to reproduce

I have 2 account with login problem in https://client-matrix.matrix.org homeserver
![image](https://github.com/vector-im/element-web/assets/1324252/03c5bf96-993e-44e0-9b7e-f9d4d2d0fb8f)
when after loign and where sync 
it keep on repsonse 500

I had try with web and application login also
When this happend start on 28/07/2023

I need server admin support to remove kind of synapse record

#### What did you expect?
In the synapse service my accounts need to remove the recoed with the crash room [version 11 beta]
the room ID's are
`!UrGZNXzzdLHbHDhGcf:matrix.org` room version 10
`!vFKLzpqZLgKkvKpcdf:matrix.org` room version 11
the version 11's are also response 500
#### What happened instead?
it's keep load with the r0/sync api and response 500 like the image I posted

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is the bug tracker for Element Web, not matrix.org - I suggest support@matrix.org
