### ISSUE TITLE
Submit debug logs

### ISSUE THREAD

**Issue by constantinedev** [vector-im/element-web#25920]
### Steps to reproduce

1. Where are you starting? What can you see?
Element Nightly Desktop (ubuntu Linux 20.04.3 LTS)
New debug report in Nightly crash
where request issue in report view. 
2. What do you click?
just login
3. More steps…

#### What did you expect?
Login crash and no response with synapse r0/sync when login
#### What happened instead?
I have used most development tools to review my login state
I have an error respone with 500 when after login complet and when sync the room data

Can I request to remove my problem room and make the sync can complet?

### Operating system

BackBox Linux

### Application version

Element nightly 

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is due to feature_new_room_decoration_ui being broken. Will be fixed in a later nightly. Disable it for now.

**Comment by constantinedev** [comment]
wow not only..... outer server can cross-signle with matrix-homserver now
