### ISSUE TITLE
Terrible performance in searching language without space

### ISSUE THREAD

**Issue by pullopen** [vector-im/element-web#25930]
### Steps to reproduce

1. Try to search a word in an unencrypted, Chinese using room.

#### What did you expect?

All sentences containing this word will come out as an result.

#### What happened instead?
The result only shows if you split this word with space or comma, which is not usual in language like Chinese or Japanese.

### Operating system

Windows

### Browser information

Firefox 116.0.1

### Application version

Element 1.11.38

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Search in unencrypted rooms is done by the Matrix server. I suggest opening an issue with your Matrix server software. Given you didn't specify what homeserver you're using we're unable to point you in the right direction.
