### ISSUE TITLE
Last device acitivy in sessions is wrong

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#25934]
### Steps to reproduce

1. Go to settings → „Sessions“
2. Look at the current and other sessions

#### What did you expect?

„Last activity“ should be a recent date

#### What happened instead?

„Last activity“ seems to be too far in the past

![image](https://github.com/vector-im/element-web/assets/6216686/8f9ff026-f96d-448c-91bc-1601cd61e35e)

### Operating system

Ubuntu 22.04.3 LTS

### Application version

Element Nightly version: 2023080801 Olm version: 3.2.14

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

https://element.ems.host

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Hmm looking at the code we do call `/devices` - @weeman1337 can you open your browser console network tab and find the `/devices` request that opening this panel makes to validate the server is sending sane data here?

**Comment by weeman1337** [comment]
The timestamps provided by the server are out of date.
→ https://github.com/matrix-org/synapse/issues/16084
