### ISSUE TITLE
Stuck unread on a thread that doesn't exist

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#25943]
### Steps to reproduce

Unclear.

#### What did you expect?

Notifications to work.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/1a641ff2-5aec-4e42-ad9a-543a8e5c8ef1)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023080801 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by germain-gg** [comment]
Why are you saying that this thread does not exist? 
Could you add a bit more context to this issue, in its current state we will not be able to investigate it properly.

**Comment by turt2live** [comment]
All the information the app provided me is in the screenshot :(

There's zero events in the thread, but it was saying I hadn't read it. It was fixed by manually sending an unthreaded read receipt for the room.

**Comment by t3chguy** [comment]
Yeah the logs definitely show `$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U` being treated as a thread - including (successful) calls to /relations m.thread for it.

`"$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U":{"events":["$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U"],"numTimelines":1,"liveTimeline":1}`

@turt2live can you share the `unsigned` from a `GET https://t2l.io/_matrix/client/r0/rooms/!YTvKGNlinIzlkMTVRl%3Amatrix.org/event/%24Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U` request?

**Comment by turt2live** [comment]
> > It was fixed by manually sending an unthreaded read receipt for the room.
> 
> @turt2live worth noting that right clicking a room and clicking Mark as read would do this too, no need to wrangle things manually.

I've unfortunately had limited success with this :(



> Yeah the logs definitely show `$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U` being treated as a thread - including (successful) calls to /relations m.thread for it.
> 
> `"$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U":{"events":["$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U"],"numTimelines":1,"liveTimeline":1}`
> 
> @turt2live can you share the `unsigned` from a `GET https://t2l.io/_matrix/client/r0/rooms/!YTvKGNlinIzlkMTVRl%3Amatrix.org/event/%24Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U` request?

```
{
  "type": "m.room.message",
  "event_id": "$Em9tLXv9GQG3d2iLqrrftQxZoMuzVFl6VdKgtJHe31U",
  "unsigned": {}
}
````

worth noting that the UI was not showing any threads to me: nothing in the timeline, and nothing in the threads list, even after a reload.

**Comment by t3chguy** [comment]
This looks identical under the hood to https://github.com/vector-im/element-web/issues/25480
