### ISSUE TITLE
Don't refresh the page when the user session is replaced via the module API

### ISSUE THREAD

**Issue by dhenneke** [vector-im/element-web#25941]
### Steps to reproduce

1. Install the [ILAG module](https://github.com/vector-im/element-web-ilag-module).
   ```yaml
   # build_config.yaml
   modules:
    - "@vector-im/element-web-ilag-module@0.0.4"
   ```
2. Enter your name and click "Ok".

#### What did you expect?

The user is logged in and joins the current room (see [the source](https://github.com/vector-im/element-web-ilag-module/blob/7dfb06bcaa4291911eb7393237585df479d8274b/src/IlagModule.tsx#L55-L56)).

#### What happened instead?

Element reloads the page and the user must click again to join the room.

---

What I found out so far: The reload is triggered by [`MatrixPegClient#onUnexpectedStoreClose`](https://github.com/matrix-org/matrix-react-sdk/blob/v3.77.1/src/MatrixClientPeg.ts#L215) which is called because the IndexedDB [received a `"closed"` event here](https://github.com/matrix-org/matrix-react-sdk/blob/v3.77.1/src/MatrixClientPeg.ts#L241). But in this context, it is not "unexpected" that the database is closed, it was explicitly told to do so [here](https://github.com/matrix-org/matrix-react-sdk/blob/v3.77.1/src/Lifecycle.ts#L709).

**Proposal:** I think the problem is that the `"closed"` event handler must not be called if the database is closed by the own instance of Element and not by external actions (other tabs, "clear storage" in the browser). I'm not sure if we can find out who emitted this event.

What we could do, is, that we explicitly remove the event handler when we want to close the storage:

```ts
// in Lifecycle#doSetLoggedIn
if (clearStorageEnabled) {
  MatrixClientPeg.prepareShutdown(); // a new function that prepares the client that
                                     // we want to shutdown the database
  await clearStorage();
}

// in MatrixPegClient
public prepareShutdown(): void {
  // We also need to add `off` to `IStore`
  this.matrixClient?.store.off?.("closed", this.onUnexpectedStoreClose);
}
```

Any thoughts on the problem or the proposal?

### Operating system

Mac OS

### Browser information

Chrome Version 115.0.5790.114

### Application version

Element 1.11.38

### Will you send logs?

No

**Comment by t3chguy** [comment]
> Proposal: I think the problem is that the "closed" event handler must not be called if the database is closed by the own instance of Element and not by external actions (other tabs, "clear storage" in the browser). I'm not sure if we can find out who emitted this event.

This is not what the docs say

> Note that it is not fired if the database connection is closed normally using [IDBDatabase.close()](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close).

Ref https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/close_event

**Comment by dhenneke** [comment]
But this event is not sent by the database, but by the matrix-js-sdk. It is emitted here: https://github.com/matrix-org/matrix-js-sdk/blob/16ddcb0ed0bcd462588b8e78ae97d1a8641eff6a/src/store/indexeddb.ts#L161-L163 and triggered from here: https://github.com/matrix-org/matrix-js-sdk/blob/16ddcb0ed0bcd462588b8e78ae97d1a8641eff6a/src/store/indexeddb-local-backend.ts#L194 in this situation.

**Comment by t3chguy** [comment]
@dhenneke good point

**Comment by dhenneke** [comment]
Maybe the main issue is, that `onClose` is called in the [`onversionchange` event handler](https://github.com/matrix-org/matrix-js-sdk/blob/f406ffd3dd14b6db86503fc562a399a002a9df3e/src/store/indexeddb-local-backend.ts#L194). @t3chguy's comment makes me assume that this is currently an unexpected behavior.

When I remove the line, it works as expected and I also don't get any failing tests.
