### ISSUE TITLE
Unable to sign out of sessions

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#25956]
### Steps to reproduce

Video on linked rageshake

#### What did you expect?
To be able to sign out of old (90+ day) sesions

#### What happened instead?
Unable to do so.

### Operating system

Linux

### Application version

Element version: 1.11.38 Olm version: 3.2.14

### How did you install the app?

Via debian repository

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This is an issue with the element.io homeserver sending 404s to valid endpoints.
