### ISSUE TITLE
Render Markdown in room topics.

### ISSUE THREAD

**Issue by rokejulianlockhart** [vector-im/element-web#25958]
#### What would you like to do?

I would like to be able to use Markdown in room topics.

#### Why would you like to do it?

Properly format text (in the header bar) and use advanced formatting for users who choose to expand the room topic dialog.

#### How would you like to achieve it?

Modification to the clients.

### Have you considered any alternatives?

Pure HTML. However, I expect that this would not be used much, and Markdown support includes non-indented HTML anyway.

### Additional context

```markdown
Person | Contact                                                                                               | `.VCF`
-------|-------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------
Roke   | https://wim.nl.tab.digital/apps/contacts/All%20contacts/7b002174-34ac-4efb-ba9b-474e8687e111~contacts | https://wim.nl.tab.digital/remote.php/dav/addressbooks/users/rokejulianlockhart/contacts/7A52F4B1-F7F6-41A4-98EB-F83F9468950E.vcf
Dean   | https://wim.nl.tab.digital/apps/contacts/All%20contacts/7b002174-34ac-4efb-ba9b-474e8687e111~contacts | https://wim.nl.tab.digital/remote.php/dav/addressbooks/users/rokejulianlockhart/contacts/7A52F4B1-F7F6-41A4-98EB-F83F9468950E.vcf
```

renders as

> ![image](https://github.com/vector-im/element-web/assets/42837531/ffae31f9-a544-4a6a-ae64-6155e3b2dfe3)

**Comment by t3chguy** [comment]
This is a labs flag you can enable on develop.element.io but tables are not a feature of Commonmark

**Comment by beedell-roke** [comment]
@t3chguy, thanks. However, [`commonmark/commonmark-spec/issues/393#issuecomment-183067940`](https://github.com/commonmark/commonmark-spec/issues/393#issuecomment-183067940) appears to also block this, in retrospect.

**Comment by tmonz** [comment]
Yes ... it's been in labs ... for almost 2 years https://github.com/element-hq/element-web/pull/21671

Feels that many features make it into devolopment (or nightly) in the labs mode ... anyone know who is the person that will push stuff from labs to stable? because all issues on 'markdown/html' seem to get shut down with the comment 'it's in labs already' ... but that's it. is there a typical digestion time for how long it takes from getting from labs to stable?

**Comment by t3chguy** [comment]
@tmonz the MSC is still not accepted: https://github.com/matrix-org/matrix-spec-proposals/pull/3765
