### ISSUE TITLE
Filepicker invoked through xdg-desktop-portal requests directory instead of files

### ISSUE THREAD

**Issue by sylph1o** [vector-im/element-web#25960]
#### Configuration

I use [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) to define my file chooser for the applications that support it. Note that I do not use Flatpak. 

This works with all my other applications: I am able to select and open files or directories when the file chooser is called by the application. This includes my web browsers, and therefore it works with Element web. This issue only happens with Element desktop, which leads me to believe that it comes from it.

#### Issue with Element desktop

Element desktop seems to support xdg-desktop-portal: trying to send a file brings up the file picker called through xdg-desktop-portal. However, Element desktop requests a *directory* instead of files.

I have reproduced this on two different computers with almost identical configurations.

#### Steps to reproduce

1. Install `xdg-desktop-portal` along with a [backend](https://github.com/flatpak/xdg-desktop-portal#using-portals).
2. Start its systemd service.
3. Set the environment variable `GTK_USE_PORTAL=1` (possibly unnecessary).
4. Start Element Desktop.
5. In any room, click on the 'Attachement' button.

#### Expected

The file chooser called by Element desktop should request one (possibly several) files.

#### What happened instead

The file chooser requests a directory. I can only select directories and, unsurprisingly, selecting a directory causes the action to fail. I am unable to send attachments with Element Desktop.

#### My thoughts

According the relevant [documentation](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-FileChooser.OpenFile), it looks like the `OpenFile` method is called with the boolean option `directory` set to `True`.

This is confirmed by looking at the process spawning my file chooser: it passes the flags `directory` and `multiple` both set to `True`. The latter is expected (although not necessary); the former is the issue.

### Operating system

Arch Linux

### Application version

1.11.38

### How did you install the app?

Arch Linux package repository

### Homeserver

matrix.org

### Will you send logs?

Yes.
P.S. Logs sent.

**Comment by t3chguy** [comment]
The arch package isn't maintained by us, seek support from its maintainer.
