### ISSUE TITLE
Encryption iconography is extremelly confusing

### ISSUE THREAD

**Issue by ubitux** [vector-im/element-web#25977]
### Steps to reproduce

Looking at the info of a room (classic room or just a single individual) shows the following:

![2023-08-16-165913-dei0AiK5](https://github.com/vector-im/element-desktop/assets/34467/3d3d8fdd-4b38-4ee1-8071-9a268fea27c6)
 
The encryption information is using exactly the same semantic as the stacked list of avatars:

![2023-08-16-170030-ai6nahJe](https://github.com/vector-im/element-desktop/assets/34467/dadc6c29-df6e-460f-8448-1f5fe88ddc62)

And since the icon is exactly the same overlap, shape and size as any avatar, this can be mistaken for a compact list of users in the room.

Can we have something smaller?

#### What did you expect?

A different semantic for the encryption information.

#### What happened instead?

The encryption information is using the same display mechanism as any avatar.

### Operating system

Arch Linux

### Application version

1.11.38

### How did you install the app?

System packages

### Will you send logs?

No

**Comment by t3chguy** [comment]
@germain-gg is working on a new right panel implementation which improves this

**Comment by germain-gg** [comment]
Closing as this will be updated as part of https://github.com/vector-im/element-web/issues/25883
And can be considered duplicate.
