### ISSUE TITLE
Emoji labels that match the expression on the emoji face

### ISSUE THREAD

**Issue by strypey** [vector-im/element-web#25974]
### Your use case

I would like all of the emoji in Element-web to have word labels that match what the emoji expression looks like. Many of them currently have labels that seem completely mismatched. For example, this one 😋 is labeled "Face Savouring Food".

### Have you considered any alternatives?

Really not sure what alternative there is other than putting very small sticky notes on my screen and writing my own labels on them. Of course, I'd have to keep pulling them off to use other apps, and putting them on again whenever I wanted to use an emoji in matrix 😋

You see? That's what *I* use that emoji for. To indicate a comment that's intended to be cheeky, and slightly sarcastic, but friendly.

### Additional context

Perhaps there's some different in culture or neurotype that causes me interpret 😋 differently from most people, but that's not what that emoji suggests to me, nor what I would use it for.

**Comment by t3chguy** [comment]
https://github.com/milesj/emojibase iamcal is the source of the current labels. We use this in Element Web, Desktop, Element X Android and Element X iOS. If you wish to suggest a change to this I suggest opening an issue in either emojibase or https://github.com/matrix-org/emojibase-bindings
