### ISSUE TITLE
VoIP messages get queued when in bad connectivity, leading to very strange behaviour when you hit 'resend'

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2598]

**Comment by Palid** [comment]
Replaced with:

https://github.com/vector-im/element-web/issues/19965 for "weird behavior"
https://github.com/vector-im/element-web/issues/19967 for missing icon
https://github.com/vector-im/element-web/issues/19968 for wrong layers order

**Comment by turt2live** [comment]
voip != voice messages

**Comment by Palid** [comment]
@turt2live right, lemme test this one again then. I assume it's for the VOIP state messages?

**Comment by turt2live** [comment]
I believe so. 2016 was a long time ago :)

**Comment by Palid** [comment]
@turt2live Retested, still closed. 😄 
Thanks for verifying though!

**Comment by turt2live** [comment]
Can we get more information for the historical record please? What makes this unable to reproduce? Is there more information we need from the author? When was it fixed?
