### ISSUE TITLE
EW: Use 3PID capability to show / hide email UI in settings

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25995]
There is a capability that instructs clients whether or not they can manage 3PIDs: https://spec.matrix.org/v1.7/client-server-api/#m3pid_changes-capability

@kerryarchibald notes that currently:

> We just let the requests fail when the server doesnt support in EW I think, I vaguely remember talking to Travis about this. He suggested we should remove it completely 🤷

When the home server is connected to a MAS deployment, emails will need to be set on MAS rather than in EW.

We'll need to get this into the EW RC currently scheduled for August 22nd.

**AC**

- When the capability is off:
  - The email fields in settings are not editable
  - There is a link to the email / profile management page on MAS
- When the capability is on:
  - Things are as they are today

Note that this has an accompanying Synapse part: https://github.com/matrix-org/synapse/issues/16128

**Comment by hughns** [comment]
FTR, this is now listed as part of MSC3824 [Definition of OIDC aware](https://github.com/matrix-org/matrix-spec-proposals/blob/hughns/sso-redirect-action/proposals/3824-oidc-aware-clients.md#definition-of-oidc-aware) clients
