### ISSUE TITLE
Guide users to MAS UI for changing display name and avatar

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25996]
When the home server is connected to a MAS deployment, the avatar and display name will need to be set on MAS rather than in EW. In this case we need to disable these fields in settings and guide the user to the MAS UI instead.

**Comment by t3chguy** [comment]
Given display name & avatar are per-room things this might need clarification

**Comment by Johennes** [comment]
Yes, indeed. We have a meeting this morning to try and get some more clarification.

**Comment by hughns** [comment]
@Johennes as discussed just now, this isn't actually needed. When MAS is used the existing display name and avatar APIs in C-S API will continue to work as expected.
