### ISSUE TITLE
Case sensitive search in non-English language

### ISSUE THREAD

**Issue by alz-aiva** [vector-im/element-web#25994]
### Steps to reproduce

1. Where are you starting? What can you see?
-When you search something in russian, the search becomes case-sensitive. It can't find "Привет" if you search "привет".
2. What do you click?
Search in Element Web 
4. More steps…

#### What did you expect?
Find "Привет" if you search "привет"
#### What happened instead?
Found only "привет" when searched "привет", and not "Привет"

### Operating system

Fedora

### Browser information

Google Chrome 114.0.5735.198 (Official Build) (64-bit)

### URL for webapp

element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The search is done by the server, I suggest opening an issue in https://github.com/matrix-org/synapse/
