### ISSUE TITLE
Chat effects not shown when accepting a room invite

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-web#26007]
### Steps to reproduce

1. User A starts a new chat with user B with a message containing chat effects
2. User B accepts the invite

#### What did you expect?

Chat effects should appear

#### What happened instead?

Chat effects did not appear

[Screencast from 2023-08-19 00-48-06.webm](https://github.com/vector-im/element-web/assets/24363938/031d068b-cd5f-4c2a-8cc3-b0c61c7e8815)

### Operating system

Linux

### Browser information

Firefox 116.0

### URL for webapp

self-hosted Element or desktop Element from Flathub

### Application version

Element version: 1.11.39

### Homeserver

matrix-synapse-py3 1.90.0+jammy1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Chat effects should only fire for "live" events - events received when you join a room are non-live. So this is functioning as expected. If you wish for it to change I suggest opening an discussion on element-meta given this decision needs to be consistent
