### ISSUE TITLE
1:1 call on GNOME 44.3, screen share endless dialogs

### ISSUE THREAD

**Issue by yajo** [vector-im/element-web#26014]
### Steps to reproduce

1. Video call
3. Screen share

#### What did you expect?
Single system dialog asking me which monitor or window to share.

#### What happened instead?
Endless loop of those dialogs, until one is chosen.

### Operating system

Fedora Linux 38.20230821.0 (Silverblue), GNOME 44.3

### Application version

Versión de Element: 1.11.39, Versión de Olm: 3.2.14

### How did you install the app?

https://flathub.org/apps/im.riot.Riot

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-desktop/issues/683

**Comment by yajo** [comment]
I don't think this is the same issue. I'm not using Jitsi and I don't have enabled element call beta rooms. I'm just using the normal 1:1 element call. See the wrong behavior:


https://github.com/vector-im/element-web/assets/973709/4147c7f6-5bbe-4009-9339-12bd230f91bb

**Comment by t3chguy** [comment]
Sorry my bad, in which case I suggest filing an issue in https://github.com/flathub/im.riot.Riot/ given it isn't a package we maintain.
