### ISSUE TITLE
Can't verify my device on linux debian

### ISSUE THREAD

**Issue by 1nextgenhuman1** [vector-im/element-web#26012]
### Steps to reproduce

Element encountered an error during upload of:

a key signature

{
  "@nextgenhuman:matrix.org": {
    "VSZFXWWPVS": {
      "status": 404,
      "errcode": "M_NOT_FOUND",
      "message": "404: No device keys found"
    }
  }
}

Element encountered an error during upload of:

a new cross-signing key signature

{
  "@nextgenhuman:matrix.org": {
    "VSZFXWWPVS": {
      "status": 404,
      "errcode": "M_NOT_FOUND",
      "message": "404: No device keys found"
    },
    "RTzxcfxZ2eWoY+WP32G1/eBTpxjWFCw0f3PCScktKXk": {
      "status": 404,
      "errcode": "M_NOT_FOUND",
      "message": "404: No device keys found"
    }
  }
}

#### What did you expect?
how can fix it?
### Operating system

Debian

### Will you send logs?

Yes

**Comment by Skaytacium** [comment]
Same as #26011 which I am also [currently stuck in](https://github.com/vector-im/element-web/issues/26011#issuecomment-1685256267).

**Comment by turt2live** [comment]
This specific issue would have been related to an issue on matrix.org : https://status.matrix.org/incidents/0xrbdq5kp1s9

I believe it should fix itself, but if not then logging out and back in should work.
