### ISSUE TITLE
Returning from vacation causes loss of notifications

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#26013]
### Steps to reproduce

1. Where are you starting? What can you see?
Coming back from vacation, changing display name, updating Element Web, trying to read messages.

3. What do you click?
4. More steps…

#### What did you expect?
when returning from vacation, rooms should have unread notification badges on them as I haven't read the message

#### What happened instead?
Unread counter in the room list disappears without opening the room.

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
Still filling this issue out ...

**Comment by t3chguy** [comment]
@daniellekirkwood did you disable notifications before going on notifications (as a form of DND maybe)?

**Comment by t3chguy** [comment]
Ah 

> changing display name

Is the culprit

**Comment by t3chguy** [comment]
This is a Synapse issue - https://github.com/matrix-org/synapse/issues/9716

**Comment by daniellekirkwood** [comment]
I raised this on behalf of @rxl881 who has told me that it's **not** the changing display name bug. I'd like his confirmation on this issue before closing

**Comment by t3chguy** [comment]
If 

> changing display name

happened before the notifications disappeared (event if not immediately, Synapse updates profile room-by-room quite slowly) then it is that bug

**Comment by daniellekirkwood** [comment]
@rxl881 feedback?

**Comment by daniellekirkwood** [comment]
No info but we believe the culprit is linked above so closing:
