### ISSUE TITLE
Encryption Failure Across Multiple Platforms on :matrix.org Homeserver

### ISSUE THREAD

**Issue by kazin-kharizma** [vector-im/element-web#26011]
![IMG_4234](https://github.com/vector-im/element-web/assets/113333610/75a1dd4b-87b3-4025-becd-6ba8254d526b)
![IMG_4235](https://github.com/vector-im/element-web/assets/113333610/11490722-d762-44e9-b8b6-c4d8e74734c2)
![IMG_4236](https://github.com/vector-im/element-web/assets/113333610/a81a406a-7d47-4241-bc2e-ec286c252a0b)
**_Title_: Encryption Failure Across Multiple Platforms on :matrix.org Homeserver**

**Description**
**Steps to Reproduce**

**Starting Point & Issue Encountered:**

- Attempted to start a new chat with encryption.
- Followed troubleshooting steps including creating a new security key and resetting back-up.
- Encountered errors during login, but eventually succeeded.
- Encryption failed across all conversations.

**Click Path**:

- Log-in (confirmed on iOS, Linux Desktop, and Web version).
- Enter Passphrase and/or security key (tried both).
- Error produced (details below) > Retry > Another error > Login succeeds.
- Sessions cannot be verified, and all conversations start unencrypted.

**Additional Steps**:

_Confirmed issue for existing and new accounts on the :matrix.org homeserver.
Not an issue with my own homeserver running Synapse and Element web._

**Specifications**: 
Element 1.10.14, Matrix SDK 0.26.12, Rust Crypto SDK 0.6.0 (Vodozemac 0.3.0).

**Expected Outcome**:

- Ability to start a new encrypted message.
- Message should have started encrypted but did not and could not be encrypted.
- Sessions show as non-verified despite security keys being accepted.

**Actual Outcome**:

- Errors encountered during upload of new cross-signing key signature.
- Issue appears widespread across Web platform, Linux desktop app, iOS mobile device, and Android.
- Issue persists across different releases, including older Flatpak version.

**Error Details**

```
Signature upload failed
Element encountered an error during upload of:
a key signature
{
  "@****************:matrix.org": {
    "NTGGMEFQXS": {
      "status": 404,
      "errcode": "M_NOT_FOUND",
      "message": "404: Unknown device"
    }
  }
}
```

**AFTER RETRY**

```
Signature upload failed
Element encountered an error during upload of:
a new cross-signing key signature
{
  "@*****************:matrix.org": {
    "NTGGMEFQXS": {
      "status": 404,
      "errcode": "M_NOT_FOUND",
      "message": "404: Unknown device"
    },
    "RNzyn4t5tKPQhgoYhWLS0": {
      "status": 400,
      "errcode": "M_INVALID_SIGNATURE",
      "message": "400: Invalid signature"
    }
  }
}
```

**Additional Information**:

_Operating System_: Web, iOS, Linux
_Browser Information_: Brave Version 1.57.47 Chromium: 116.0.5845.96 (64-bit)
_URL for Webapp_: https://app.element.io/
_Application Version_: Element version: 1.11.39, Olm version: 3.2.14
_Homeserver_: matrix.org
Will you send logs? No
```[tasklist]
### Tasks
```

**Comment by Skaytacium** [comment]
I'm running into the same issue, I've reset my keys, changed my password, signed out from all devices but the "404: No device keys found" always returns. I'm unable to communicate at all.

**Comment by mrk67422** [comment]
same problems in my element: android and win desktop

**Comment by kazin-kharizma** [comment]
@Skaytacium and @mrk67422 yeah we are having a huge convo about it on the Matrix web chat and it’s pretty widespread.

**Comment by DorianBenjamin** [comment]
+1 for the issue. i experience the exact same problem

**Comment by kazin-kharizma** [comment]
Thought it would be funny to rest the Federation Tester for matrix.org and I was right:

{
  "WellKnownResult": {
    "m.server": "matrix-federation.matrix.org:443",
    "CacheExpiresAt": 1692553350
  },
  "DNSResult": {
    "SRVSkipped": true,
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": null,
    "Hosts": {
      "matrix-federation.matrix.org": {
        "CName": "matrix-federation.matrix.org.",
        "Addrs": [
          "2606:4700:10::6814:c925",
          "2606:4700:10::ac43:135a",
          "2606:4700:10::6814:c825",
          "104.20.201.37",
          "172.67.19.90",
          "104.20.200.37"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "[2606:4700:10::6814:c925]:443",
      "[2606:4700:10::ac43:135a]:443",
      "[2606:4700:10::6814:c825]:443",
      "104.20.201.37:443",
      "172.67.19.90:443",
      "104.20.200.37:443"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "104.20.200.37:443": {
      "Message": "Get \"https://104.20.200.37:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    },
    "104.20.201.37:443": {
      "Message": "Get \"https://104.20.201.37:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    },
    "172.67.19.90:443": {
      "Message": "Get \"https://172.67.19.90:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    },
    "[2606:4700:10::6814:c825]:443": {
      "Message": "Get \"https://[2606:4700:10::6814:c825]:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    },
    "[2606:4700:10::6814:c925]:443": {
      "Message": "Get \"https://[2606:4700:10::6814:c925]:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    },
    "[2606:4700:10::ac43:135a]:443": {
      "Message": "Get \"https://[2606:4700:10::ac43:135a]:443/_matrix/key/v2/server\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    }
  },
  "Version": {
    "error": "Get \"matrix://matrix.org/_matrix/federation/v1/version\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
  },
  "FederationOK": false
}

**Comment by kazin-kharizma** [comment]
![Screenshot_2023-08-20_10-21-58](https://github.com/vector-im/element-web/assets/113333610/c13e6526-407f-4a95-8d7c-fbc7a1062764)

This feels like some sort of oddly satisfying karma for all the times it was my homeserver that had the issue. :P haha!

**Comment by turt2live** [comment]
This specific issue would have been related to an issue on matrix.org : https://status.matrix.org/incidents/0xrbdq5kp1s9

I believe it should fix itself, but if not then logging out and back in should work.

**Comment by kazin-kharizma** [comment]
> This specific issue would have been related to an issue on matrix.org : https://status.matrix.org/incidents/0xrbdq5kp1s9
> 
> I believe it should fix itself, but if not then logging out and back in should work.

The steps to reproduce above occur after doing precisely as you suggested, logging out and logging back in. In fact this was tried on several sessions before I stopped when I realised none of them could ever get re-verified. I thank you for your suggestion but I may need a bit more because I have only one session left.

**Comment by t3chguy** [comment]
@kazin-kharizma support@matrix.org for issues with matrix.org - https://github.com/matrix-org/synapse/ for issues with Synapse - this repo for issues specific to Element Web
