### ISSUE TITLE
Flaky Cypress test cypress/e2e/widgets/stickers.spec.ts

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26017]
This test is failing occasionally with the assertion about `thumbnail/something?` being in the URL of the tile showing the sticker.

**Comment by richvdh** [comment]
Which test is, specifically, that's failing here? Do you have a link to an example?

**Comment by andybalaam** [comment]
> Which test is, specifically, that's failing here? Do you have a link to an example?

Both tests in cypress/e2e/widgets/stickers.spec.ts are failing sporadically. Apologies for the short descriptions - I mainly made this issue to track the fact that I was working on it under https://github.com/matrix-org/matrix-react-sdk/pull/11440
