### ISSUE TITLE
Add module API for adding extra icons into the room header

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#26028]
# Context

<img width="844" alt="Screenshot 2023-10-05 at 11 20 07" src="https://github.com/vector-im/element-web/assets/769871/4ec38d1d-f9eb-48a2-8eee-afe977df17cb">

- We want to provide the ability to add extra icons to the room header. 
- The displayed icons can change based on which room is currently displayed
- All icons are to be displayed on the left part of the existing ones to avoid unwanted layout shift

# Requirements

- Extend the [`RoomViewLifecycle`](https://github.com/matrix-org/matrix-react-sdk-module-api/blob/main/src/lifecycles/RoomViewLifecycle.ts) to emit a room change event that can be listened to on the module's side.
- Use the [`<IconButton />` Compound component](https://compound.element.io/?path=/story/compound-web_iconbutton--normal). for visual consistency with the room header
- Expose a store of room buttons

## Store

The store should probably expose the following attribute for every button

- An SVG symbol
- And most probably the component props of the [`<IconButton />`](https://compound.element.io/?path=/story/compound-web_iconbutton--normal) however it is probably not desirable to create a direct mapping

We might also want to provide a way to open a hyperlink and use an anchor rather than a button and an `onClick` callback

**Comment by emmaburton1** [comment]
@Johennes Drawing your attention to the A-Timesheet-1 label. 👀

**Comment by emmaburton1** [comment]
@Johennes Do you have an ETA for when work will start on this?

**Comment by Johennes** [comment]
We've clarified IRL.
