### ISSUE TITLE
Video and audio calls fail to start in Librewolf

### ISSUE THREAD

**Issue by Cyberes** [vector-im/element-web#26024]
### Steps to reproduce

1. Start or join a video or audio call using Librewolf
2. Observe errors in console and no audio/video

Audio call error:
```
Uncaught (in promise) DOMException: The object can not be found here. 
```

Video call errors:
```
Failed to play media element with feed for userId @cyberes:evulid.cc with purpose m.usermedia DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
    playMedia VideoFeed.tsx:126
    componentDidMount VideoFeed.tsx:68
    React 13
    setState warning.svg:2
    Ks LegacyCallView.tsx:205
    emit events.js:158
    emit typed-event-emitter.ts:89
    pushRemoteFeedWithoutMetadata call.ts:759
    pushRemoteFeed call.ts:674
    k call.ts:2319
bundle.js:2:3207002
Failed to play media element with feed for userId @admin:other-homerserver.com with purpose m.usermedia DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
    playMedia VideoFeed.tsx:126
    componentDidMount VideoFeed.tsx:68
    React 13
    setState warning.svg:2
    Ks LegacyCallView.tsx:205
    emit events.js:158
    emit typed-event-emitter.ts:89
    pushRemoteFeedWithoutMetadata call.ts:759
    pushRemoteFeed call.ts:674
    k call.ts:2319
```

Android client always shows "Call connecting..." when Librewolf fails to connect.

Normal Firefox and Chrome work fine.

I assume that Librewolf has more restrictive privacy settings. I did disable most of them, though:

![Screenshot from 2023-08-21 13-12-21](https://github.com/vector-im/element-web/assets/64224601/2a63e02f-908a-4a26-9d80-e6e909807ce5)

#### What did you expect?

Calls work.

#### What happened instead?

Calls seem to be stuck in the connecting phase.

### Operating system

Linux Firefox, Andoid Element

### Browser information

LibreWolf Firefox 116.0-1 (without adblock or noscript)

### URL for webapp

app.element.io

### Application version

Element version: 1.11.39, Olm version: 3.2.14

### Homeserver

Two different homeservers.

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Sorry LibreWolf is not a [supported environment](https://github.com/vector-im/element-web#supported-environments)

**Comment by Cyberes** [comment]
Okay, makes sense. Buy why don't you support it? Just curious.

**Comment by t3chguy** [comment]
Not enough people to maintain compatibility with the less populated browsers, they also tend to need more workarounds due to the settings they choose. Contributions to fix issues specific to an [unsupported] browser are welcome though!

**Comment by Cyberes** [comment]
I'd love to provide a patch to fix this, but I have no idea what could be conflicting since I have all the privacy settings turned off. Maybe someday someone will come along...
