### ISSUE TITLE
New room header room name overflow

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26039]
### Steps to reproduce

1. Enable new room header in labs
2. Set a room name to have multiple words (that should fit into one line)
3. Look at the room header

#### What did you expect?

Room name does not overflow

#### What happened instead?

Room name overflows

![image](https://github.com/vector-im/element-web/assets/6216686/496442e2-753d-423b-8dd0-2265388fa92c)

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Firefox 117.0

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 469d11ffcb84-react-d5cacff6c37c-js-85ba0691176c Version von Olm: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by germain-gg** [comment]
Already fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11444
