### ISSUE TITLE
New room icons don't show up correctly in pills

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#26046]
### Steps to reproduce

1. Where are you starting? What can you see?

<img width="78" alt="Screenshot 2023-08-24 at 12 20 40" src="https://github.com/vector-im/element-web/assets/89144281/64ce3668-8393-4e7c-9247-5e30b8f4a4cb">

3. What do you click?
4. More steps…

### Operating system

MacOS

### Application version

Element Nightly version: 2023082401 Olm version: 3.2.14

### How did you install the app?

element.io

### Homeserver

ems

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
Sorry to just assign this to you @germain-gg but as i know you're the only one working on it, it felt simpler 😂  

not sure i've included all the info you need or the right labels - let me know

**Comment by germain-gg** [comment]
I've fixed a couple of issues after going through the percy tests, thank you for that!

However, I can not reproduce the issue listed here?  @daniellekirkwood does that still occur to you?
<img width="520" alt="Screenshot 2023-08-25 at 10 40 11" src="https://github.com/vector-im/element-web/assets/769871/c6f9349b-299e-4419-ab1a-e5936cdfec1b">

**Comment by daniellekirkwood** [comment]
Yes, only with bubbles on though

**Comment by andybalaam** [comment]
Much improved screenshots here!: https://percy.io/dfde73bd/matrix-react-sdk/builds/29824720/changed/1653231969?browser=firefox&browser_ids=47%2C48%2C49&subcategories=approved&viewLayout=overlay&viewMode=new&width=1920&widths=120%2C258%2C260%2C264%2C267%2C285%2C300%2C400%2C500%2C580%2C600%2C796%2C800%2C1024%2C1920
