### ISSUE TITLE
New room header cannot view room member from right panel

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26040]
### Steps to reproduce

1. Enable new room header in labs
2. Click to room name to open the right panel
3. Go to room members
4. Click a member

#### What did you expect?

Open room member view

#### What happened instead?

Nothing

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Firefox 117.0

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 469d11ffcb84-react-d5cacff6c37c-js-85ba0691176c Version von Olm: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
Given this is where one performs/checks verification this is critical (but still only applies to Labs)
