### ISSUE TITLE
Letter avatars are all grey

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26042]
### Steps to reproduce

1. Open current develop https://develop.element.io/
2. Look at the avatars

#### What did you expect?

Colours :paintbrush: 

#### What happened instead?

They are all grey :neutral_face: 

![image](https://github.com/vector-im/element-web/assets/6216686/19974ba3-7589-426b-9413-b9b95f301ec0)

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Firefox 117.0

### URL for webapp

https://develop.element.io/

### Application version

Version von Element: 780da23c702e-react-09c5e06d12ac-js-c5245a887b67 Version von Olm: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by MTRNord** [comment]
This happens for me too on darkmode :) 

In version: Version von Element: 780da23c702e-react-9fb7d94c2bc8-js-c5245a887b67
Version von Olm: 3.2.14

**Comment by MTRNord** [comment]
It seems like the variable exists but the bg css not 
![image](https://github.com/vector-im/element-web/assets/1374914/1b88611f-16c8-44ac-9e89-d642d508dd70)

**Comment by germain-gg** [comment]
This is really strange, things load perfectly fine on my develop.element.io , both for light and dark theme.

<img width="468" alt="Screenshot 2023-08-24 at 14 09 05" src="https://github.com/vector-im/element-web/assets/769871/e3636768-de77-4a2d-827b-f5ec3be598d0">

**Comment by MTRNord** [comment]
That smells like a caching issue potentially? In the past this happened with the language files which is why they had a cachebuster hash attached. Not sure however if that even does something these days still

**Comment by germain-gg** [comment]
Not really, because the design tokens are included in there from the day where Element started using the new colour set.

In here, something makes them either not being applied, but i am yet to figure out what triggers this, continuing the conversation in https://matrix.to/#/#element-dev:matrix.org

**Comment by plui29989** [comment]
Hi,
avatar letters are still grey for me - only in firefox though. Other browsers (Safari, Chrome) seem to be unaffected.
I'm using
Element-Web 1.11.41
Firefox 117.0

**Comment by ftyers** [comment]
I'm running `1.11.41` too and it's the same in Firefox. 

![imatge](https://github.com/vector-im/element-web/assets/449545/d8a1c81d-68e9-4e98-9904-ca93ed0fc7e9)

**Comment by DoruDoLasu** [comment]
yep, just updated. on firefox. not only the username colours look worse (imo) but also that

**Comment by ManuelHu** [comment]
Just some investigation I just did:
Toggling `layout.css.has-selector.enabled` in Firefox's `about:config` "fixes" the issue. Firefox is currently the only mainstream browser [not supporting the CSS `:has()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).

And this selector is used to style the avatar in element 1.11.41.

This has been fixed in https://github.com/vector-im/compound-web/commit/1361a4a114b1d1d78096b6abe0f653e7673da340, but apparently did not make it into the release :-/

**Comment by ftyers** [comment]
@ManuelHu Thanks! I tried enabling that but it still looks the same. I also tried force-refreshing. Isn't it the only browser that isn't based on Chromium too? Any idea of when the next release will be (that will include that fix) ?

**Comment by ManuelHu** [comment]
I am using the beta version of Firefox (118) and there just toggling the pref in about:config and force-reloading Element shows colored avatars.
But anyway, the real fix is in the compound repo, the above was just for testing (it probably has some reasons that the firefox setting is off by default...)

I am not following the Element development closely, but on the `develop` branch the compound fix is already available.

**Comment by t3chguy** [comment]
Tracked in https://github.com/vector-im/element-web/issues/26155
