### ISSUE TITLE
Last room in favourites section cut off

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#26049]
### Steps to reproduce

1. Use develop.element.io
2. See the last room in favourite section is cut off

#### What did you expect?

It shouldn't be cut off

#### What happened instead?

It is cut off

The rooms and people section seems to be fine.

On Develop:

![image](https://github.com/vector-im/element-web/assets/62639087/29ed75b1-f9b3-4150-a3b1-aca6efc4a5d8)

On stable (Element version: 1.11.39 Olm version: 3.2.14):

![image](https://github.com/vector-im/element-web/assets/62639087/3f53111d-93c0-48d1-b427-b5b63a672162)

### Operating system

Fedora 39

### Browser information

118.0a1 (2023-08-22) 

### URL for webapp

https://develop.element.io/

### Application version

Element version: fcd805255c26-react-2d2841930ac8-js-5788d9744b76 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by andybalaam** [comment]
I can reproduce this on develop. @germain-gg I hate to ask, but could this be related to your changes? I don't remember any work happening in the room list recently.
