### ISSUE TITLE
Presence indicators are off-center in their cutouts

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26052]
### Steps to reproduce

1. Use a homeserver that has presence enabled
2. Look at people's avatars in the room list

#### What did you expect?

Presence indicators should be centered within their cutouts

#### What happened instead?

They're off-center:

![Screenshot 2023-08-24 at 21-22-18 Element](https://github.com/vector-im/element-web/assets/48614497/1ca85192-0743-452f-9c83-306812fef721)

### Operating system

NixOS unstable

### Browser information

Firefox 115.0.2

### URL for webapp

develop.element.io

### Application version

Element version: fcd805255c26-react-23897dff4f79-js-5788d9744b76 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by andybalaam** [comment]
@germain-gg was this intended? (I assume this was related to the compound avatars)
