### ISSUE TITLE
Space pills inconsistent/broken layout

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26056]
### Steps to reproduce

1. send a space pill

#### What did you expect?
- square space icon looks proper in rounded pill
- icon is vertically centered
- composer behaves the same as timeline

#### What happened instead?
- square space icon looks strange as the pill around it is completely round, it looks like it doesn't properly fit in there
- slight offset towards the bottom of the pill
- composer uses round avatar for space in pill when it should be square
![image](https://github.com/vector-im/element-web/assets/2803622/adf2a8ad-68bc-4243-92f0-fa377bfcb49c)

### Operating system

arch

### Application version

Element Nightly version: 2023082401 Olm version: 3.2.14

### How did you install the app?

aur

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
somewhat related to #26046

**Comment by germain-gg** [comment]
This was an unexpected change, but does actually uses the correct semantic for space avatars that have square corners.

Follows up on the conversation in https://matrix.to/#/!zzGPdcyFqxIOJEijoI:matrix.org/$8lFyjiAabtD4Br-tbYRqb5c3QT347X9smBAaGddNfYU?via=matrix.org&via=element.io&via=envs.net

**Comment by HarHarLinks** [comment]
i kinda wish the pill was just rounded-square shaped on the left for spaces, but with a bit more padding than
![image](https://github.com/vector-im/element-web/assets/2803622/9dcffd78-4015-4a35-a862-88c4726d72a8)

**Comment by Johennes** [comment]
Chatted about this with @nadonomy and @janogarcia this morning. The desired solution is to make the avatar in space pills circular on the left side and rounded rect on the right. When making this fix, we should also ensure that the pills look the same between the timeline and the composer.
