### ISSUE TITLE
Avatars in user info panel are 30x30

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26051]
### Steps to reproduce

1. Click on someone's avatar in the timeline to bring up user info
2. Blurry image

#### What did you expect?

A decent image. Historically we've tried to calculate avatar size for that panel specifically as it's bound by panel width

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/f8321751-f3c8-4d7d-b869-49dd47a1c2a6)

URL of avatar: https://t2l.io/_matrix/media/v3/thumbnail/t2l.io/fYhaPLjAZLwEYqaSGKwRpQgk?width=30&height=30&method=scale

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023082401 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment]
I have not been able to reproduce this, could you check the logs in your console?

We can pass a list of URLs to the avatar component and if the first one fails it tries to load the second one.

**Comment by weeman1337** [comment]
> I have not been able to reproduce this, could you check and share the logs in your console?
> 
> We can pass a list of URLs to the avatar component and if the first one fails it tries to load the second one.

I can reproduce. It does request the avatar with 30px width from the server

![image](https://github.com/vector-im/element-web/assets/6216686/fdefcd86-e80e-4ece-898b-4b524d99fe8e)
