### ISSUE TITLE
Hovering over a room avatar shows the room ID in a tooltip

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26055]
### Steps to reproduce

1. Hover over the avatar of a room or space that actually has an image set

#### What did you expect?

No tooltip

#### What happened instead?

The room ID appears in a tooltip, which I find surprising - room IDs aren't useful to most people apart from developers, and this seems like an odd place to expose it

![Screenshot from 2023-08-25 08-30-29](https://github.com/vector-im/element-web/assets/48614497/f38bd313-259b-4c85-85a8-3837a259a9b0)

### Operating system

NixOS unstable

### Browser information

Firefox 115.0.2

### URL for webapp

develop.element.io

### Application version

Element version: fcd805255c26-react-23897dff4f79-js-5788d9744b76 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by t3chguy** [comment]
Room IDs leaking out into non-developer/advanced UI is definitely unexpected

**Comment by Johennes** [comment]
This appears to be happening because Compound's `Avatar` component fills the `title` attribute from the `id` property rather than the `title` property.

**Comment by Johennes** [comment]
@germain-gg I'm not sure if that was intentional or not? It feels like it could be somewhat helpful for DMs when the ID is the user ID but less so for rooms.
