### ISSUE TITLE
Can not search Chinese in my instance

### ISSUE THREAD

**Issue by pullopen** [vector-im/element-web#26057]
### Steps to reproduce

1. Try to search a word in an unencrypted, Chinese using room in my instance.

#### What did you expect?
All sentences containing this word (characters) will come out as an result.

#### What happened instead?
The result only shows if you split this word with space or comma, which is not the way we write in Chinese.
For example, we won't say "我 吃饭 了", instead we say "我吃饭了", and when I want to search "吃饭" in this room, I get nothing.
I suppose it's the same in any language that does not use space, like Japanese.

Is there a setting for me as operator of this server can do?

### Operating system

Windows

### Browser information

Firefox 116.0.1

### URL for webapp

chat.pullopen.xyz

### Application version

Element 1.11.39

### Homeserver

pullopen.xyz, Synapse v1.90.0

### Will you send logs?

Yes

**Comment by germain-gg** [comment]
Search in unencrypted rooms is provided by https://github.com/matrix-org/synapse/ 
I would recommend opening an issue there

**Comment by t3chguy** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/901
