### ISSUE TITLE
Viewing Settings Changes Secure Backup State

### ISSUE THREAD

**Issue by Nils1729** [vector-im/element-web#26068]
### Steps to reproduce

1. Register a new user `alice` and log in.
    * Skip use case selection.
2. Switch to another browser session (e.g. private window).
3. Register a new user `bob` and log in.
    * Skip use case selection.
4. As Bob, click on "Start your first private chat".
5. Enter `@alice:homeserver` (replace `homeserver` with your homeserver, I am using `localhost` for testing)
6. Click on the suggestion for Alice.
7. Click "Go"
8. Send a message as Bob.
9. Element asks to set up secure backup. As Bob, click "Continue", "Generate a Security Key", "Copy" and "Continue" and "Done" to set up secure backup.
10. Send a message as Alice to Bob.
11. As Bob, click your avatar and then "Sign out".
    * Element asks to connect to key backup.
 12. Click on "X" to cancel sign-out.
 13. Click your avatar and then on "Security & Privacy"
     * Secure Backup shows "This session is backing up your keys."
 14. Without doing anything in the settings, press "X" to exit them.
 15. Just as in step 11, click on your avatar and then on "Sign out"
     * Element asks for confirmation to sign out. It no longer asks to connect to Key Backup.

#### What did you expect?

* As a user I expect my keys to be backed up when the dialog shows that Secure Backup has been set up (after step 9).
* As a user I expect merely viewing settings (steps 13 and 14) to not alter the application state. 

#### What happened instead?

* Despite having set up key backup, element asks me to do it again on logout.
* This was fixed after I viewed the encryption settings.

### Operating system

Ubuntu 22.04

### Browser information

Firefox 115.0.2

### URL for webapp

https://app.element.io/

### Application version

Element version: 1.11.39, Olm version: 3.2.14

### Homeserver

Synapse (https://github.com/matrix-org/matrix-react-sdk/tree/968213a5d79d4ab8895839d3880e71fd25b3f0bb/cypress/plugins/synapsedocker/templates/default)

### Will you send logs?

No

**Comment by richvdh** [comment]
I think this got fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11640
