### ISSUE TITLE
Deep link to choose a server doesn't seem to work

### ISSUE THREAD

**Issue by alexander-potemkin** [vector-im/element-web#26066]
### Steps to reproduce

I've tried the Desktop app to open the custom server when opening using the URL format https://app.element.io/register/?hs_url=example.com, as recommended at https://github.com/vector-im/element-ios/issues/7632, but it doesn't seem to work.

#### What did you expect?

I expected my self-hosted server to appear, but it didn't happen.

#### What happened instead?

matrix.org server remain as a default one.

### Will you send logs?

No

**Comment by t3chguy** [comment]
An issue in another repository is hardly documentation. This isn't something we support. See https://github.com/vector-im/element-web/issues/5469

**Comment by alexander-potemkin** [comment]
@t3chguy , can't recall I was mentioning 'documentation' anywhere. I was under the impression thought, that the team working on the product could be sharing one view and try to keep features parity.

I can see now that, unfortunately, it's not the case.

**Comment by alexander-potemkin** [comment]
@t3chguy , one more thing - as custom builds don't seem to be supported as well (I had to make my own), how / why do you call messenger federated, if by default it keeps sticking to one server only?

It feels like an internet browser on MS Windows: you can use any, as long as you are tech-savvy enough to change it from IE/Edge, which would still appear here and there every now and then.

Please, correct me if I'm wrong.

**Comment by alexander-potemkin** [comment]
> Sounds like you want https://github.com/vector-im/element-meta/discussions/375

Nop. I believe I have an issue for that at meta as well, if you like: https://github.com/vector-im/element-meta/issues/1946

> What about them isn't supported?

I don't believe I have found any documented and easy-to-start-with solution. That's why I had to work out my own: https://github.com/get-zen-dev/element-customdomain-desktop

**Comment by t3chguy** [comment]
@alexander-potemkin if you have suggestions for how to improve docs https://github.com/vector-im/element-web/#getting-started & https://github.com/vector-im/element-desktop/#building then contributions are welcome.

We perform all releases & publishing using scripts & github actions workflows which are published publicly in those repositories so copying our setup should be trivial though would have costs as Apple code signing & notarisation & Windows EV Code signing are both chargeable.
