### ISSUE TITLE
Room pills in edit and send message composer use old default avatars

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26067]
### Steps to reproduce

1. Mention a room without an avatar
2. Observe the composer state
3. Send that message
4. Observe the new avatar style
5. Edit that message
6. Observe the same legacy avatar you saw in Step 2

#### What did you expect?

Consistency with the new avatar style.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/7d76c4fd-7288-43e0-a19c-dcfd844177c6)
![image](https://github.com/vector-im/element-web/assets/1190097/491dd447-4901-495b-9317-dfeb0eef2b5f)

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023082801 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by germain-gg** [comment]
Fixing this will also fix the issue with the OS notification that @pixlwave just made me aware of

![Screenshot 2023-08-29 at 12 45 34 pm](https://github.com/vector-im/element-web/assets/769871/77885361-6c4a-4f10-b6d4-1f9180e24e9e)
