### ISSUE TITLE
Avatar placeholders in timeline use the wrong font

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26061]
### Steps to reproduce

1. In the timeline, look at the avatar of someone who doesn't have a profile picture set

#### What did you expect?

It should use the Inter font:

![Screenshot 2023-08-26 at 17-56-05 Element 16 kaıkaı](https://github.com/vector-im/element-web/assets/48614497/bd584358-94f6-4e69-bdf3-40c173622fad)

#### What happened instead?

It uses my browser's default font, which happens to be Cantarell:

![Screenshot 2023-08-26 at 17-55-13 Element 15 kaıkaı](https://github.com/vector-im/element-web/assets/48614497/d11f69ae-83ac-4d6a-a92b-8e26ec4ae296)

### Operating system

NixOS unstable

### Browser information

Firefox 115.0.2

### URL for webapp

develop.element.io

### Application version

Element version: fcd805255c26-react-64f762d7b0f3-js-5788d9744b76 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by germain-gg** [comment]
Do you use a custom system font in your setting?

Looking at the current version of Element, using a custom system font does also override the font used to display the initials on avatars.

**Comment by HarHarLinks** [comment]
this seems related, in my room list, I get:
![image](https://github.com/vector-im/element-web/assets/2803622/9420051c-e127-4892-98cb-0b37cbf477d0)
and in the timeline:
![image](https://github.com/vector-im/element-web/assets/2803622/5a1e5bad-5772-4759-99b4-a07a66b8cd9f)

discussed earlier in https://matrix.to/#/!zzGPdcyFqxIOJEijoI:matrix.org/$6SB1-bFdRMYKBCIkryT13Is_fzPlapHnThRApjttnsw?via=matrix.org&via=element.io&via=envs.net

**Comment by MidhunSureshR** [comment]
I can still reproduce this issue, so reopening
