### ISSUE TITLE
Provide official Flatpak package

### ISSUE THREAD

**Issue by DemiMarie** [vector-im/element-web#26072]
#### What would you like to do?

Provide an official Flatpak package for Element.

#### Why would you like to do it?

`.deb` packages are not supported on platforms other than Debian or Ubuntu, whereas Flatpaks work on any distro that supports Flatpak.

#### How would you like to achieve it?

Provide an official Flatpak package.

### Have you considered any alternatives?

None

### Additional context

The current unofficial Flatpak has several bugs.

**Comment by germain-gg** [comment]
Not planned as discussed in https://github.com/vector-im/element-desktop/pull/233
