### ISSUE TITLE
Threads: large space between messages

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26075]
### Steps to reproduce

1. look at a thread where the same person wrote a number of consecutive messages

#### What did you expect?
normal spacing between 
#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/2803622/5d1a9a34-fb0d-4689-b699-43034289adf0)

 caused by senderDetails not collapsing in a stream of messages by the same sender

### Operating system

arch

### Application version

Element Nightly version: 2023082901 Olm version: 3.2.14

### How did you install the app?

aur

### Homeserver

synapse 1.89.0

### Will you send logs?

No

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11448
