### ISSUE TITLE
Invite dialog pills have poor styling

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26098]
### Steps to reproduce

1. In a group chat, click the "Invite to this room" button
2. Search for or add a user to the invite list

#### What did you expect?

Legible text, aligned elements.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/4acdbde5-fb3f-4312-8508-4100473d3e8a)

The user's pill is extremely low contrast, and the `x` next to the pill is not vertically centered with the pill.

### Operating system

Windows 11

### Application version

Element Nightly version: 0.0.1-nightly.2023090101 Olm version: 3.2.14

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

No

**Comment by gabrc52** [comment]
Can reproduce, this seems like a relatively new regression
