### ISSUE TITLE
Closing room search from right panel doesn't change timeline view

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#26105]
### Steps to reproduce

1. Open a room, open the right panel
2. Click 'Search'
3. Submit a search and wait for results
<img width="1091" alt="Screenshot 2023-09-04 at 18 10 19" src="https://github.com/vector-im/element-web/assets/3055605/5eaf0057-2190-45b3-b1f4-9444c8728def">

4. Toggle search by clicking 'Search' in the right panel
5. Search bar goes away, but timeline view is still search results without any way to go back to room timeline
<img width="1095" alt="Screenshot 2023-09-04 at 18 10 31" src="https://github.com/vector-im/element-web/assets/3055605/749a1743-da99-4f58-8537-deb436366d86">

#### What did you expect?
Toggling search from sidebar should revert timeline back to normal view.

### URL for webapp

develop.element.io

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/11507

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/11524 makes this only a problem for the labs flag
