### ISSUE TITLE
Enable new room UI by default on develop

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#26116]

**Comment by weeman1337** [comment]
@Johennes can you add more details and eventually triage this issue?

**Comment by t3chguy** [comment]
@Johennes sounds like it'd want to be in an internal repo then?

**Comment by Johennes** [comment]
Hm, maybe. Though I think there's a difference between something being private and something not being relevant for triage? This issue here wouldn't need to be private. But it's also not relevant for triage. It only lives in the context of the room header project. 🤔
