### ISSUE TITLE
[Epic] Compound + WAT: Room list and Space panel

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#26110]
Currently a holding issue while @daniellekirkwood pulls in the necessary info.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

### Time sheeting ⏱️

`WEB: Compound Adoption
`

**Comment by Johennes** [comment]
Closing as we've changed plans and won't pick this up in the near term.
