### ISSUE TITLE
Access token cannot be rolled

### ISSUE THREAD

**Issue by jekuno** [vector-im/element-web#26128]
### Steps to reproduce

My access token which gives full access to my account has been leaked. I need to roll the access token / create a new one.

What I did:
1. Open settings - help and info
2. Scroll down to view the access token
3. You can only copy the already existing access token

#### What did you expect?

There's an option to roll the access token / invalidate the old access token / create a new one. This option is also missing in the Desktop app.

Resetting the password did not help, as the access token remained the same.

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Rolling an access token in Matrix is logging out and back in. There's no single operation for that and it requires your credentials. I suggest making a feature request in the Matrix repo https://github.com/matrix-org/matrix-spec

**Comment by jekuno** [comment]
Thanks for your quick answer. According to my tests, it seems that logging out and logging back in does not change the access token listed at the very bottom under Settings - Help and Info. Are you perhaps referring to a different type of token?

**Comment by t3chguy** [comment]
Sounds like an issue with your Matrix server then. The token is issued as part of Login and Registration only. As per the spec https://spec.matrix.org/v1.8/client-server-api/#relationship-between-access-tokens-and-devices

**Comment by jekuno** [comment]
Ok. Thanks for your support. I compared the two tokens before signing out and after signing back in and I was fooled by the fact, that the first 27 chars have been exactly the same. Comparing the second part of the token revealed, that the token indeed had been regenerated. Sorry for the confusion!
