### ISSUE TITLE
Room avatars are not properly visible in search dialogue

### ISSUE THREAD

**Issue by bbhtt** [vector-im/element-web#26133]
### Steps to reproduce

1. Open the public room search dialogue
2. See that the room logos are cut off

On Develop:

![image](https://github.com/vector-im/element-web/assets/62639087/934d04f9-35ad-4959-9542-c2d84ee333a0)

On stable:

![image](https://github.com/vector-im/element-web/assets/62639087/4016684d-28ba-4a2f-a1b9-1f9d4921b1b8)

#### What did you expect?

They should be properly visible

#### What happened instead?

Not properly visible

### Operating system

Fedora 39

### Browser information

firefox 119.0a1 (2023-09-05) 

### URL for webapp

https://develop.element.io/

### Application version

Element version: 54fd7a987219-react-c825e34f16fa-js-6c307d4c63e3 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Nivas7** [comment]
Could you please assign me the [#26133/Set Room Logos Visible]?

**Comment by weeman1337** [comment]
> Could you please assign me the [#26133/Set Room Logos Visible]?
> 
> Think I can fix this issue.

Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)

**Comment by t3chguy** [comment]
Affects staging

**Comment by weeman1337** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/09c5e06d12ac15511e8310a572a3295064394dee

**Comment by t3chguy** [comment]
@Nivas7 thanks for your interest here, unfortunately due to it being a release blocker we'll be taking it on just to get it done swiftly.
