### ISSUE TITLE
Message shieds are not aligned to text

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26142]
### Steps to reproduce

1. Try to get a message shield, e.g. send a message from an unverified device
2. Look at message shields

Only affects
- bubble layout
- modern layout without „compact“ flag

#### What did you expect?

Aligned to text

#### What happened instead?

Not aligned. A little too far up / down

![image](https://github.com/vector-im/element-web/assets/6216686/8bd7c933-5d28-4743-97d2-2dd2569d8073)

![image](https://github.com/vector-im/element-web/assets/6216686/bc8dba9b-13c0-407d-9f92-e3917ae2127b)

Replies

![image](https://github.com/vector-im/element-web/assets/6216686/993db6fc-bfae-4e54-8114-33f330947311)

compared to the modern, „compact“ layout

![image](https://github.com/vector-im/element-web/assets/6216686/075b2852-77e4-4ae2-9176-9c5ae68926bb)

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Firefox 117.0

### URL for webapp

https://develop.element.io/

### Application version

Element version: 6dc6c80cc5c6-react-0ee2eac0e592-js-f963ca55627e Olm version: 3.2.14

### Will you send logs?

No

**Comment by bhargavagonugunta** [comment]
hi sir  @weeman1337  i want to solve this issue please assign me sir

**Comment by weeman1337** [comment]
> hi sir @weeman1337 i want to solve this issue please assign me sir

Thank you for your interest in this issue. We will normally not assign the issue to an external contributor until they have provided at least a draft PR which is taking the right direction. For further details, see our [guidance on assigning issues](https://github.com/vector-im/element-meta/wiki/Guidance-on-assigning-issues).

If you have any technical questions about this issue, you can ask for help in [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)
