### ISSUE TITLE
Entering the room #matrix_appservice_slack:cadair.com results in M_UNKNOWN

### ISSUE THREAD

**Issue by mkarg** [vector-im/element-web#26148]
### Steps to reproduce

In Element I was trying to enter the room  #matrix_appservice_slack:cadair.com, but Element says it results in M_UNKNOWN. That room is public, and it is an official room by the vendors of the official matrix-appservice-slack bridge, so I doubt this is a "normal" situation. Hence there is either a bug in Element or a bug in the Synapse.

#### What did you expect?

Element enters the room.

#### What happened instead?

Auf #matrix_appservice_slack:cadair.com kann momentan nicht zugegriffen werden.
Versuche es später erneut oder bitte einen Raum- oder Space-Admin um eine Zutrittserlaubnis.

M_UNKNOWN wurde während des Betretens zurückgegeben. Wenn du denkst, dass diese Meldung nicht korrekt ist, [reiche bitte einen Fehlerbericht ein](https://github.com/vector-im/element-web/issues/new/choose).

### Operating system

Windows

### Application version

Element: 1.11.40, Olm: 3.2.14

### How did you install the app?

Docker Container : latest

### Homeserver

https://headcrashing.eu

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is an issue with your server. I suggest reaching out to headcrashing.eu for help.
