### ISSUE TITLE
Avatar colours just disappeared

### ISSUE THREAD

**Issue by Salamandar** [vector-im/element-web#26155]
### Steps to reproduce

Starting with today's update (1.11.41), avatar colours (for people not having an actual avatar) just disappeared.

All avatars are the usual letter on a gray background.

In the message list : (username is coloured)
![Capture d’écran du 2023-09-12 22-46-00](https://github.com/vector-im/element-web/assets/6552989/de925ade-1fc9-430b-813d-afb4219a92be)

In the rooms list : (username is base color)
![Capture d’écran du 2023-09-12 22-46-05](https://github.com/vector-im/element-web/assets/6552989/11cc21b0-4a8d-4259-b825-d3d0d1802eb4)

#### What did you expect?

The usual colours used for the avatar placeholder.

#### What happened instead?

Grey.

### Operating system

Archlinux

### Browser information

Firefox 115

### URL for webapp

app.element.io

### Application version

Version de Element : 1.11.41 Version de Olm : 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ManuelHu** [comment]
Just some investigation I just did (see #26042):
Toggling layout.css.has-selector.enabled in Firefox's about:config "fixes" the issue. Firefox is currently the only mainstream browser [not supporting the CSS :has() selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).

And this selector is used to style the avatar in element 1.11.41.

This has been fixed in https://github.com/vector-im/compound-web/commit/1361a4a114b1d1d78096b6abe0f653e7673da340, but apparently did not make it into the release :-/

On develop.element.io the fix is already available.

**Comment by CsatiZoltan** [comment]
@ManuelHu On develop.element.io, the colours have come back, but they are different.

**Comment by andybalaam** [comment]
Fixed in 1.11.42

**Comment by CsatiZoltan** [comment]
Indeed fixed. Just a question: why did you change the colours of the icons?

**Comment by Salamandar** [comment]
> > Indeed fixed. Just a question: why did you change the colours of the icons?
> 
> We're changing over lots of parts of the app to use the [Compound](https://compound.element.io) design system. In this case, the change of colours is to make us consistent with the Element mobile apps.

It is now less consistent today with Element Android : The letter is now coloured and the round is now darker than before.

**Comment by Salamandar** [comment]
> > Indeed fixed. Just a question: why did you change the colours of the icons?
> 
> We're changing over lots of parts of the app to use the [Compound](https://compound.element.io) design system. In this case, the change of colours is to make us consistent with the Element mobile apps.

Then the current UI is not compliant with the Compound design system. 
See : https://compound.element.io/?path=%2Fstory%2Fcompound-web_avatar--no-image-fallback

**Comment by WolfspiritM** [comment]
Am I the only one who doesn't like the idea of the colors changing? My color is completely different now and in conversations I always think I've a new message. Especially confusing is that a friend has now a similar color I had before and I have now a color he had before. 

Blue just became purple and purple became blue for example...

Couldn't you've just kept at least a similar color and just made it more faded?

I still hope that there will be a way to set a custom color someday...

**Comment by CsatiZoltan** [comment]
It became significantly less visible on dark theme. In my case, the former pink icon became this:
![new_icon](https://github.com/vector-im/element-web/assets/12742890/c5a77bf0-38ca-4559-919b-8cfd2993886f)

**Comment by andybalaam** [comment]
I'm going to ask one of the designers to look into this. Thanks for the feedback.

**Comment by andybalaam** [comment]
Response: we think the current behaviour does comply with the design system, and would welcome people logging a new issue if you find specific places where it doesn't. Thanks again!

**Comment by Salamandar** [comment]
Thanks @andybalaam .
