### ISSUE TITLE
UTD: DecryptionError: OLM.UNKNOWN_MESSAGE_INDEX

### ISSUE THREAD

**Issue by Hywan** [vector-im/element-web#26150]
### Steps to reproduce

1. Received a message from @manuroe in a 1:1 room
2. The message was a UTD

#### What did you expect?

Not a UTD :-p.

#### What happened instead?

A UTD.

### Browser information

Firefox nightly 119.0a1 (2023-09-04)

### URL for webapp

develop.element.io

### Will you send logs?

Yes

**Comment by manuroe** [comment]
https://github.com/vector-im/element-x-ios-rageshakes/issues/869
