### ISSUE TITLE
Schedule Send

### ISSUE THREAD

**Issue by MidnightSlicer** [vector-im/element-web#26156]
### Your use case

I would like the ability to schedule sending messages in Element. Many other applications (including Signal, Proton Mail, Gmail, Google Messages, etc.) have the ability to write a message and schedule it to send at a certain time. 

### Have you considered any alternatives?

Alternative is to not have it. This is super low priority but could be a nice feature.

### Additional context

None.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/309
