### ISSUE TITLE
Pile of space member avatars is no longer clickable

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26164]
### Steps to reproduce

1. Go to the home page of a space
2. Click the pile of space member avatars (the ones at the bottom of this screenshot: )
![Screenshot 2023-09-13 at 14-33-44 Element 3 Matrix Community](https://github.com/vector-im/element-web/assets/48614497/fe397cd5-8121-4c9b-a169-18d1796990f4)

#### What did you expect?

The member list for the space should open (this is what it did until recently)

#### What happened instead?

Nothing happens. I thought that I might be able to work around this by using the `Ctrl + .` shortcut to open the right panel and show the member list, but that doesn't work either. What *does* still work is clicking the "3277 members" text, which is apparently (surprisingly!) a button

### Operating system

NixOS unstable

### Browser information

Firefox 117.0

### URL for webapp

develop.element.io

### Application version

Element version: 361941e5d44c-react-da1daa1b18ff-js-6d118008b6b3 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by manancodes** [comment]
@germain-gg I have opened Pull Requests for both the solutions to this problem. Please have a look and let me know if any enhancements are needed. Thanks.

**Comment by manancodes** [comment]
> I'm not sure I understand why there's two PRs? #11656 seems to already fix the problem?
> 
> Moreover the solution here with `onClick` on a `div` element is not accessible thus requiring more work. as well as some tests to avoid regressions on this in the future.

@germain-gg The output of these 2 PRs is different. 

1. https://github.com/matrix-org/matrix-react-sdk/pull/11656 - If I click on a user icon, the user profile opens up. If I click the more(...) button, the members list opens.(Explained in detail with recordings in the PR itself)



> This solution makes more sense to me, but the problem is, hovering over this pile shows a tooltip which says "See all 3357 Members" which makes it confusing and is a bad user experience because only the more(...) button will open the list.
> <img width="440" alt="Screenshot 2023-09-25 at 2 42 49 PM" src="https://github.com/matrix-org/matrix-react-sdk/assets/54790263/fe0a1dfe-2dec-4dca-8498-5894068c8970">

2. https://github.com/matrix-org/matrix-react-sdk/pull/11657 - Clicking anywhere on the pile will open the members list. Which is more aligned with the tooltip and the previous implementation before the regression. But again, it is not a complete solution.


Which one should I go ahead with? 

Meanwhile I'll research about best workarounds for onClick on non-accessible elements, any assistance or ideas will surely help.

**Comment by manancodes** [comment]
@germain-gg which one should I go ahead with?

**Comment by manancodes** [comment]
@robintown @germain-gg Please assist what should I go ahead with?

**Comment by germain-gg** [comment]
@manancodes https://github.com/matrix-org/matrix-react-sdk/pull/11657 is the desired output, as the tooltip label suggests that you will see all members.
