### ISSUE TITLE
Buttons in the new room header have duplicate tooltips

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26177]
### Steps to reproduce

1. Enable the new room header in Labs
2. Hover over one of the icon buttons in the header

#### What did you expect?

At most one tooltip

#### What happened instead?

I see two tooltips conveying the same information:

![Screenshot from 2023-09-15 09-44-55](https://github.com/vector-im/element-web/assets/48614497/09b52ee7-c42d-4d0c-b18d-dfd0a64942fa)

### Operating system

NixOS unstable

### Browser information

Firefox 117.0

### URL for webapp

develop.element.io

### Application version

Element version: df6b106b26ed-react-0b50e0279087-js-c9435af63707 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by yash1378** [comment]
@robintown can you please assing this issue to me

**Comment by robintown** [comment]
This appears to have been fixed
