### ISSUE TITLE
Users can no longer register with token and email validation

### ISSUE THREAD

**Issue by 0x416c69** [vector-im/element-web#26172]
### Steps to reproduce

0. Configure the homeserver to only allow registration with token and enable matrix mailer
1. Create a valid token
2. Try to register on my own homeserver with username, password and an email and press register
3. Enter the token and press continue

#### What did you expect?
In Element Desktop, after hitting the Continue button, it'll show me a page that **it's waiting for me to validate my email** and after I do, my user is successfully registered and I can enter.

#### What happened instead?
The token is used (will no longer be valid, it'll be counted as a used token), the validation email is sent but **I'm stuck in a never ending loading**:

https://github.com/vector-im/element-web/assets/10671711/65b907e3-a482-400a-8364-349688d15645

I'm just guessing but I think this is related to this PR: https://github.com/matrix-org/matrix-react-sdk/pull/11398
(Since this only happened after upgrading from an older version to the current version)

---

I sent one rageshake from console with a "test" message, if necessary I'll send one with a unique message.

### Operating system

Windows 10

### Browser information

Google Chrome 117.0.5938.63

### Application version

Element Web 1.11.42

### Homeserver

Synapse v1.92.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> I sent one rageshake from console with a "test" message, if necessary I'll send one with a unique message.


No rageshakes are showing up linked to this issue. Please send again and use the issue field with this issue's link.

<img width="713" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/3c6aa98f-65bf-4cd0-ab4a-455bb78aed94">

**Comment by 0x416c69** [comment]
@t3chguy I don't have access to /rageshake command, I am not logged in, how can I send a rageshake before logging in after I reproduce this?

**Comment by t3chguy** [comment]
`mxSendRageshake(text, withLogs)` from console or log in and then send logs, they'll still include it.

**Comment by 0x416c69** [comment]
@t3chguy 

![image](https://github.com/vector-im/element-web/assets/10671711/af2f7618-767e-43d7-b23b-635debed53fc)

I've reproduced it in a new session, and then used this to send the rageshake.

It's worth noting that when I don't enter the email address, everything works flawlessly and the new user is registered and automatically logged in. It has to be from the email validation stuff and it's not a server issue since it's okay in Element Desktop (Element Desktop is also 1.11.42 but it works without any problems, I'm using Incognito mode so I'm not facing cache issues, also I've deployed this whole thing from https://github.com/spantaleev/matrix-docker-ansible-deploy)

**Comment by 0x416c69** [comment]
@t3chguy Sorry for the ping, is it possible that a hotfix for this is released sooner? Is this an easy fix? Can I be of any help?

**Comment by t3chguy** [comment]
@0x416c69 it has yet to be triaged, then reproduced, then its up to the release maintainer to decide if its worthy of a hotfix (@andybalaam)

**Comment by t3chguy** [comment]
The error you're seeing seems entirely unrelated to https://github.com/matrix-org/matrix-react-sdk/pull/11398

The error you're seeing is due to an invalid or no identity server being configured.

![image](https://github.com/vector-im/element-web/assets/2403652/7c84e088-2291-48e6-8b90-5ed863a4242d)

I suggest visiting seeking help from the ansible deploy script's support for such misconfigurations.

**Comment by 0x416c69** [comment]
@t3chguy I'm sorry but according to https://github.com/vector-im/element-web/blob/develop/docs/config.md#identity-servers and the existing documentations on https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ma1sd.md having an identity server is optional, I haven't configured an identity server and I don't want one. I don't see how sending an email validation (which already does send one, from Element Desktop, and works fine, maybe you'd like me to send proof or logs or something?) is related to having an identity server.

I've also disabled federation and I cannot enable federation due to some reasons, this is the `config.json` of the element client hosted within our website which the ansible deploy script has generated:
```
{
    "brand": "AGMatrix",
    "branding": {
        "auth_footer_links": [
            {
                "text": "Forum",
                "url": "https://forum.arsacia.ir"
            },
            {
                "text": "AG:SA",
                "url": "https://agsa.arsacia.ir"
            },
            {
                "text": "Wiki",
                "url": "https://wiki.arsacia.ir"
            }
        ],
        "auth_header_logo_url": "https://arsacia.ir/img/aglogo.svg",
        "welcome_background_url": "https://arsacia.ir/img/agbg.jpg"
    },
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "default_country_code": "GB",
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.ag5.ir",
            "server_name": "ag5.ir"
        },
        "m.identity_server": {
            "base_url": ""
        }
    },
    "default_theme": "dark",
    "disable_custom_urls": true,
    "disable_guests": true,
    "embedded_pages": {
        "homeUrl": ""
    },
    "enable_presence_by_hs_url": "\n",
    "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/api"
    ],
    "jitsi": {
        "preferred_domain": "jitsi.ag5.ir"
    },
    "permalink_prefix": "https://matrix.to",
    "room_directory": {
        "servers": []
    },
    "setting_defaults": {
        "custom_themes": []
    },
    "show_labs_settings": true,
    "welcome_user_id": null
}
```
`m.identity_server`.`base_url` is an empty string which looks to be intended when you don't have an identity server from:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/7586cecedffa9d0dd6762702d6018492664515dc/roles/custom/matrix-client-element/templates/config.json.j2#L8

I haven't changed any of my configurations and the client was working fine before updating to this version, my theory is that you're looking at an unrelated error and the registration steps are unrelated to the error you're seeing. I don't know if according to the new updates an identity server is required for a mere email validation system but if that's the case, I don't see how that makes any sense and I will have to run an identity server, so please let me know.

**Comment by t3chguy** [comment]
> Element Desktop

Are you using Element Desktop from element.io? That one has an IS pre-configured - https://github.com/vector-im/element-desktop/blob/develop/element.io/release/config.json#L8-L10

AFAIK

```
        "m.identity_server": {
            "base_url": ""
        }
```

is invalid, it should be omitted entirely rather than specifying an empty base_url.

https://spec.matrix.org/v1.8/client-server-api/#getwell-knownmatrixclient says the `base_url` field is required, but the `m.identity_server` field is not. If you're using out-of-spec configurations and things break then that is to be expected.

**Comment by 0x416c69** [comment]
@t3chguy You're right, after configuring the "base_url" to https://vector.im everything works fine now. I guess this is a bug from https://github.com/spantaleev/matrix-docker-ansible-deploy/ after all. I guess I should move away from them and configure everything manually myself from the specifications.

**Comment by cremesk** [comment]
i can see the same error without an defined identity server like:
```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.envs.net",
            "server_name": "envs.net"
        }
    },
..
```

with an identity server like vector it works:
```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.envs.net",
            "server_name": "envs.net"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
...
```

**Comment by 0x416c69** [comment]
@cremesk True, I also got rid of "m.identity_server" but still got the same error, it only works with a valid identity server which is against the specification and could be a bug (?, I still haven't read the specifications for registration flow and email validation):

> **If the m.identity_server property is present**, extract the base_url value for use as the base URL of the identity server. Validation for this URL is done as in the step above, but using /_matrix/identity/v2 as the endpoint to connect to.
