### ISSUE TITLE
Improved room header - Impossible to open user info.

### ISSUE THREAD

**Issue by daedric7** [vector-im/element-web#26176]
### Steps to reproduce

With the _Improved Room Header_ enabled , it's impossible to click a avatar, or select a user from the user list and get it's user pane.

Old style: 
![image](https://github.com/vector-im/element-web/assets/4562461/20c5cd04-48f2-4acf-939f-00a66f71e7f2)

No matter were i click on a user (avatar on the message list, user on the user list) it doesn't open that pane or produce any reaction.

#### What did you expect?

The old, or a newer user pane.

#### What happened instead?

Nothing, no reaction.

### Operating system

Windows 10, Chrome.

### Application version

versão do Element: 361941e5d44c-react-237038aa5634-js-6d118008b6b3 Olm version: 3.2.14

### How did you install the app?

Docker compose, image: vectorim/element-web:develop

### Homeserver

aguiarvieira.pt , Synapse 1.92.1

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
You were using https://github.com/matrix-org/matrix-react-sdk/commit/237038aa5634 - it was fixed in https://github.com/matrix-org/matrix-react-sdk/commit/dce42d32e755fe13cafd2bed8a06831b7412e44d
