### ISSUE TITLE
Latest update breaks using multiple tabs

### ISSUE THREAD

**Issue by opk12** [vector-im/element-web#26182]
### Steps to reproduce

1. Open Element in a few tabs. For example, one tab for the room $PROJECT-users, one for $PROJECT-dev, one for friend, one for personal notes.

#### What did you expect?
Element to work in all tabs.

#### What happened instead?
Since today, one tab works, but the others are blocked with a message that Element only supports one tab open at a time.

### Will you send logs?

No

**Comment by opk12** [comment]
Spaces are permanent and require many clicks to be set up. Tabs depend on what I'm working on at the moment and are quick to create / destroy / reorder. So they're not a replacement.

**Comment by t3chguy** [comment]
This was done intentionally, see https://github.com/vector-im/element-web/issues/25157

**Comment by marcusmueller** [comment]
@t3chguy it being done intentionally to fix a cryptography bug doesn't make this any less of a functional usability regression!

**Comment by Twi1ightSparkle** [comment]
We have customer complaining about this regression

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/26231
