### ISSUE TITLE
Video Room Chat Header Button Removed

### ISSUE THREAD

**Issue by Anthial** [vector-im/element-web#26181]
### Steps to reproduce

1. Create a Video Room.
2. Click said Video Room.
3. If the Chat is available, close it down.
4. There is now no way to reopen the chat

#### What did you expect?
There used to be a header button to open the chat.
#### What happened instead?
The header button is gone, there seems to be no way to reopen the chat once it is closed. There is still a search button, but it is non-functional.

### Operating system

Windows

### Application version

Element Nightly version: 0.0.1-nightly.2023091701 Olm version: 3.2.14

### How did you install the app?

https://element.io/download#nightly

### Homeserver

Synapse v1.89.0

### Will you send logs?

Yes

**Comment by andybalaam** [comment]
I can reproduce this.

**Comment by andybalaam** [comment]
This does not block release since video rooms are a labs feature, but this needs fixing before we unlabs the room header.

**Comment by DoM1niC** [comment]
![image](https://github.com/vector-im/element-web/assets/1436958/9bbb36e2-a232-45ec-b29c-275b6c4e2606)
small remark start Voice / Video Call have to hidden in VoIP Rooms

**Comment by manancodes** [comment]
I cannot reproduce this on Latest Nightly Mac App, app.element.io or develop.element.io

Am I missing any step to reproduce this?
<img width="800" alt="Screenshot 2023-10-15 at 4 50 09 PM" src="https://github.com/vector-im/element-web/assets/54790263/632b08cd-f1a5-46a4-8a78-e1e14807af51">

**Comment by manancodes** [comment]
I'm working on adding this in the new header.

**Comment by manancodes** [comment]
I was working on this issue in https://github.com/matrix-org/matrix-react-sdk/pull/11752 but could not write the tests because of the festive season here in India for a few days. And now I see another PR created to fix this. Should I close my PR?
