### ISSUE TITLE
Window buttons / top bar shifted up in new room header labs feature

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#26184]
### Steps to reproduce

1. Enable the new room header feature in labs
2. Notice how the top part of the UI is shifted up

![Screenshot 2023-09-01 at 07 57 27](https://github.com/vector-im/element-desktop/assets/1137962/702896db-1774-4e85-8eca-0792d5e5c72e)

#### What did you expect?

The top part of the UI not to move up.

#### What happened instead?

The opposite

### Operating system

macOS

### Application version

Element Desktop nightly

### How did you install the app?

https://packages.element.io/nightly/

### Homeserver

element.io / element.ems.host

### Will you send logs?

No

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/26209 as it has more info
