### ISSUE TITLE
Element Call behind ingress controller

### ISSUE THREAD

**Issue by janschaible** [vector-im/element-web#26190]
### Steps to reproduce

1.Deploy element-web behind ingress controller (basepath https://domain/element)
2.Deploy element-call & livekit behind ingress controller (basepath https://domain/element-call  https://domain/livekit)
3.Setup configuration
  "element_call": {
      "url": "https://domain/element-call",
      "use_exclusively": true
  },
  "livekit": {
      "livekit_service_url": "https://domain/livekit"
  },

### Outcome

I would have expected element call to work :)
Id did not.
This is because the path is overwritten by within the Call.ts file.
`
const url = new URL(SdkConfig.get("element_call").url ?? DEFAULTS.element_call.url!);
url.pathname = "/room";
`
instead it should be:
`
const url = new URL(SdkConfig.get("element_call").url ?? DEFAULTS.element_call.url!);
url.pathname = \`${url.pathname}/room\`;
`
or something like that ?:)

### Operating system

Windows

### Browser information

Chrome

### Application version

v1.11.43

### Homeserver

Synapse 1.89.0

### Will you send logs?

No

**Comment by robintown** [comment]
Yes, we have no plans to support hosting Element Call on a path other than the root of a domain.
