### ISSUE TITLE
Drop down next to room name is missing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#26191]
### Steps to reproduce

1. Go to a room
2. Click on the room name

#### What did you expect?
Click on the drop down next to the room name and be able to copy link to room

#### What happened instead?
Don't see a drop down icon next to the room name. Clicking on the room name opens and closes right panel instead of showing the drop down.

### Browser information

Chromium 116.0.5845.140 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: df6b106b26ed-react-0b50e0279087-js-c9435af63707 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is the new room header which is defaulted on for develop & nightly
