### ISSUE TITLE
Element-R: stuck in a loop calling `/keys/query`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26194]
It seems to be continually calling `/keys/query` for itself

**Comment by BillCarsonFr** [comment]
So the loop is due to the `userHasCrossSigningKeys()` that is called as part of `DeviceListener#doRecheck()`.

The `userHasCrossSigningKeys()` is forcing a `keys/query` that will emit a `CryptoEvent.UserTrustStatusChanged`, 
and DeviceListener will trigger a doRecheck on that event
