### ISSUE TITLE
Page is scrolled upwards due to #cpdAvatarClipSvg from Compound Web

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#26209]
### Steps to reproduce

1. Visit a page that features an avatar stack, such as the landing page of a space, or by enabling the new room header labs flag

#### What did you expect?

The app should continue to occupy the entire available window space

#### What happened instead?

It gets scrolled upwards by an SVG element that Compound Web adds to the DOM in order to render an AvatarStack

![Screenshot from 2023-09-19 12-34-04](https://github.com/vector-im/element-web/assets/48614497/022377d3-543b-4611-a4ca-8e97ac7f8959)

### Operating system

NixOS unstable

### Browser information

Firefox 117.0

### URL for webapp

develop.element.io

### Application version

Element version: 29bd206f8522-react-5cb8cbd89316-js-1c16b5cae6e8 Olm version: 3.2.14

### Homeserver

Not relevant

### Will you send logs?

No

**Comment by germain-gg** [comment]
Blocked on https://github.com/vector-im/compound-web/pull/81 being merged and a new npm release being made

**Comment by robintown** [comment]
Fix released: https://github.com/vector-im/compound-web/releases/tag/v0.4.3
