### ISSUE TITLE
Cannot join solid_chat:gitter.im

### ISSUE THREAD

**Issue by RubenVerborgh** [vector-im/element-web#26206]
### Steps to reproduce

1. Where are you starting? What can you see?

I am at https://app.element.io/#/room/#solid_chat:gitter.im
I see

![image](https://github.com/vector-im/element-web/assets/675313/10125be3-13c8-4b25-adc4-9e5b7612941a)

2. What do you click?

I click "Join the discussion"

3. More steps…

I see a spinner that never stops:
![image](https://github.com/vector-im/element-web/assets/675313/310ab891-f7c1-448d-bfeb-1b4556376675)

I tried the above many times on different browsers and operating systems. I can join other rooms, but not this one.

#### What did you expect?

I join the room.

#### What happened instead?

I do not join the room.

### Operating system

macOS

### Browser information

Firefox 117.0.1

### URL for webapp

https://app.element.io/#/room/#solid_chat:gitter.im

### Application version

Element version: 1.11.43 Olm version: 3.2.14

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The join request goes through, seems like your server isn't sending the newly joined room down sync. If the room is large it may take a while. matrix.org is the server which you are using, the support for which is at support@matrix.org
