### ISSUE TITLE
We shouldn't require ops in a room to list it in the room directory

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2621]
I thought we fixed this?

**Comment by ara4n** [comment]
actually, this may be deliberate, in terms of discouraging people from spamming up the roomdir with their own weird aliases. need to think it through some more.

**Comment by richvdh** [comment]
Presumably server admins should be allowed to add directory entries, irrespective of ops in the room.

**Comment by t3chguy** [comment]
Closing, if you still desire this change 5.5 years later please open an issue in https://github.com/matrix-org/matrix-spec
