### ISSUE TITLE
Flaky Cypress test: `Read receipts > redactions > in threads > A thread with a read redaction is still read after restart`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26221]
https://cloud.cypress.io/projects/ppvnzg/runs/19354/overview/dd12f9f1-a071-4f84-b602-ff594683625e?roarHideRunsWithDiffGroupsAndTags=1

```
Timed out retrying after 10000ms: Expected <span.mx_NotificationBadge_count> not to exist in the DOM, but it was continuously found.
```

Or occasionally:

```
MatrixError: [403] User @bot_300:localhost not in room !rgEgoFWyUzrEtGMUsF:localhost (http://localhost:33819/_matrix/client/v3/rooms/!rgEgoFWyUzrEtGMUsF%3Alocalhost/send/m.room.message/m1695374502743.0)
```

**Comment by richvdh** [comment]
https://cloud.cypress.io/projects/ppvnzg/runs/19450/overview/610a5833-2101-4311-947f-9df852120b39

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6352024338/job/17254190464#step:8:24582

**Comment by andybalaam** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6378649434/job/17309657440

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6379119069/job/17310983060#step:8:13954

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6384145126/job/17326188244#step:8:13113

**Comment by andybalaam** [comment]
My next PR will skip this test.
