### ISSUE TITLE
At-room notifications recently starting happening despite being disabled

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#26227]
### Steps to reproduce

1. Use release version of Element Web without joining the notifications beta
2. Set "Messages containing @room" to "Off"
3. Receive an at-room message (such as [this TWIM message](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$yef8LrVcuz5p96IsbZmMdYwNKJ25qoZnhiEzH8oe7_4?via=matrix.org&via=element.io&via=envs.net))

#### What did you expect?

I did not expect any notifications because I have at-room notifs disabled account-wide.

#### What happened instead?

A notification still came through.

### Operating system

macOS 13.5.2

### Browser information

Firefox 119

### URL for webapp

app.element.io

### Application version

Element version: 1.11.43 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by jryans** [comment]
After some initial diagnosis by @t3chguy, it appears it's related to [intentional mentions](https://github.com/matrix-org/matrix-react-sdk/pull/11602). The [TWIM message](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$yef8LrVcuz5p96IsbZmMdYwNKJ25qoZnhiEzH8oe7_4?via=matrix.org&via=element.io&via=envs.net) I used as an example includes the new intentional mention metadata.

IIUC, intentional mentions like this use new push rules which are not controllable from the "old but still default" notifications UI.

**Comment by Johennes** [comment]
We already have rule syncing implemented for the polls push rules and I thought this should do the trick to do the same for the intentional mentions rules:

```
index fb81ac799e..ca60e6cf40 100644
--- a/src/notifications/VectorPushRulesDefinitions.ts
+++ b/src/notifications/VectorPushRulesDefinitions.ts
@@ -111,6 +111,9 @@ export const VectorPushRulesDefinitions: Record<string, VectorPushRuleDefinition
             [VectorState.Loud]: StandardActions.ACTION_HIGHLIGHT_DEFAULT_SOUND,
             [VectorState.Off]: StandardActions.ACTION_DISABLED,
         },
+        syncedRuleIds: [
+            RuleId.IsUserMention,
+        ]
     }),

     // Messages containing @room
@@ -122,6 +125,9 @@ export const VectorPushRulesDefinitions: Record<string, VectorPushRuleDefinition
             [VectorState.Loud]: StandardActions.ACTION_HIGHLIGHT,
             [VectorState.Off]: StandardActions.ACTION_DISABLED,
         },
+        syncedRuleIds: [
+            RuleId.IsRoomMention,
+        ],
     }),
```

It doesn't appear to work though. So I'm obviously missing something.

**Comment by Johennes** [comment]
@kerryarchibald can you spot what's wrong here?

**Comment by kerryarchibald** [comment]
The issue here is [`DEFAULT_OVERRIDE_RULES`](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/pushprocessor.ts#L74-L103) in pushprocessor, which is forcing the actions to the default value.

**Comment by Johennes** [comment]
Ah, thanks for figuring this out @kerryarchibald! 👍
