### ISSUE TITLE
The changes doesn't reflect in browser

### ISSUE THREAD

**Issue by raguct25** [vector-im/element-web#26234]
### Steps to reproduce

I had followed this link : [https://github.com/vector-im/element-web#setting-up-a-dev-environment](url)

I had installed matix-synapse server. The server connection runs on port 8008

![image](https://github.com/vector-im/element-web/assets/35067734/79a2a005-0811-4c20-9cf7-db3e4955ff3a)

**server configuration:** create config.json file and configured server address 

![image](https://github.com/vector-im/element-web/assets/35067734/6018ca80-62a3-42fb-a997-ec633160109d)

When i try to some changes in **matrix-react-sdk folder** it doesn't appears in browser

#### What did you expect?

I just want to hide room headr icons

![image](https://github.com/vector-im/element-web/assets/35067734/41d94d13-63bd-4833-8af7-8f357cc118c3)

I have changed code here **matrix-react-sdk/src/components/views/rooms/LegacyRoomHeader.tsx**

![image](https://github.com/vector-im/element-web/assets/35067734/8a0242b1-6e29-478b-a268-49919b998758)

#### What happened instead?

whenever i changed logics in code but got this ouput in browser

![image](https://github.com/vector-im/element-web/assets/35067734/e4991ebd-0891-4ffc-8729-2d779f086bc3)

### Followed steps:

Whenever I made any changes in code I should followed this steps

1) Clear browser storage
2) Restart matrix synapse server
3) delete **webapp** folder in element-web
4) run : yarn start

```[tasklist]
### Tasks
```

**Comment by t3chguy** [comment]
This is a bug tracker, not a support page. Try #element-dev:matrix.org

I suggest elaborating on exactly what you did for setup, you shouldn't need to do any of your last 4 steps when testing your changes, only refresh your browser.

**Comment by raguct25** [comment]
@t3chguy 

 I had followed this steps

**Step-1**
git clone https://github.com/matrix-org/matrix-js-sdk.git
cd matrix-js-sdk
yarn link
yarn install

**Step-2**
git clone https://github.com/matrix-org/matrix-react-sdk.git
cd matrix-react-sdk
yarn link
yarn link matrix-js-sdk
yarn install

**Step-3**
git clone https://github.com/vector-im/element-web.git
cd element-web

**Step-4**
Create **config.json** file copy all from **config.sample.json** file and replace this property values,

`"default_server_config": {
        "m.homeserver": {
            "base_url": "http://localhost:8008",
            "server_name": "matrix.org"
        },
        "m.identity_server": {
            "base_url": "http://localhost:8008"
        }
    },`

**Step-5**
yarn link matrix-js-sdk
yarn link matrix-react-sdk
yarn install
yarn start

**Step:6**
The element web run in **http://localhost:8080/**

**Step-7**
normally i hide the some piece of code in LegacyRoomHeader.tsx file but modified code not updated in browser.

**Comment by t3chguy** [comment]
> This is a bug tracker, not a support page. Try #element-dev:matrix.org
