### ISSUE TITLE
Unexpected behavior: admin who leaves room and then is re-invited automatically rejoins room as admin

### ISSUE THREAD

**Issue by exercismnow** [vector-im/element-web#26242]
### Steps to reproduce

1. Create new e2ee room
2. In room settings under "Security & Privacy" choose `Private (invite only), Only invited people can join`
3. Invite another user. They have a default power level of 0
4. Promote the user to Admin power level of 100
5. Notice that the user cannot be kicked, now that they are Admin
6. The other user voluntarily leaves the room, perhaps because they no longer have a position of authority in that community
7. Once again invite the user who left
8. The user rejoins, and retains their Admin power level of 100
9. Notice that, once again, there is no longer a way to kick the user, since they are Admin

#### What did you expect?
I expected the re-invited user to re-join the room with a Default power level of 0. I expect that anyone who leaves the room should come back as a normal user, since their special privileges should be revoked the moment they leave the room.

#### What happened instead?
I did not expect inviting someone to the room to automatically create a new Admin, without a conscious decision to do so by the incumbent admin. This is a problem because the new admin cannot be removed by the incumbent admin.

#### Why it matters, and what I would suggest
Room Admins cannot be removed from the room, and have a lot of control over the room. Having extraneous Room Admins sitting around makes it harder to manage the room, and can be an attack vector on the room if an Admin becomes inactive and does not properly maintain their account or maintain digital hygiene. The other Admins cannot remove them, so they become a permanent liability.

When inviting any user to a room, let them join as the Default power level of 0. Or, give the option when inviting to set their power level.

### Operating system

Linux Mint 21

### Browser information

Firefox 118

### URL for webapp

app.element.io

### Application version

Element version: 1.11.44 Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is how permissions in Matrix work, if you think it should be different I suggest you make a suggestion in https://github.com/matrix-org/matrix-spec
