### ISSUE TITLE
ElementR: Device is not connected to Key Backup after verification

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#26244]
### Steps to reproduce

1. Login with a device
2. Click on Verify with device
3. Verify the device with the other device
4. In the `Sessions` panel, the device is verified
5. In the `Security & Privacy`, the session is not connected to Key Backup

https://github.com/vector-im/element-web/assets/2621378/60edfb6f-bb4c-4b92-9082-9d18c58d617b

#### What did you expect?

The session to be connected to key backup

#### What happened instead?

The session is not connected to key backup

### Will you send logs?

Yes

**Comment by richvdh** [comment]
part of https://github.com/vector-im/crypto-internal/issues/114

**Comment by BillCarsonFr** [comment]
Probably a missing call to `checkKeyBackupAndEnable()`

Should be done after the session is verified (generally speaking when the verification status of the current identity has changed)
