### ISSUE TITLE
Can not open or download attachments

### ISSUE THREAD

**Issue by domestomas** [vector-im/element-web#26250]
### Steps to reproduce

1. Send a file (not a picture, for examle pdf) as an attachment to a conversation
2. Click on the file or on the download button to download it
3. Nothing happenst :(

### Expected Outcome

Download file dialogue from my file manager (similar to downloading a photo)

### Operating system

Linux Mint 21.2 Cinnamon

### Application version

Element version: 1.11.43 Olm version: 3.2.14

### How did you install the app?

repository

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by domestomas** [comment]
Sorry, the repository https://packages.element.io/debian/ does not have 1.11.44, I will try it after i get the version

**Comment by t3chguy** [comment]
<img width="627" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/b082bcf0-b078-40fd-8ac0-674fbd5057ff">

It most certainly does

<img width="1052" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/db9c69dd-009e-473a-9a21-7571fd6a6cc3">

**Comment by domestomas** [comment]
It was probably already updated on my pc so i did not see any new updates, all I needed was to restart element to get the new version. Now with 1.11.44 the downloading works. (Although the system dialogue window appears always out of focus, but this is probably so unimportant it is not worth solving). I am sorry for the inconvenience.
