### ISSUE TITLE
Add the function of automatically switching the language of the element interface according to the language of the browser.

### ISSUE THREAD

**Issue by Admin-Account** [vector-im/element-web#26257]
### Your use case

Access the browser's built-in navigator.language property

Then you can realize the function of element to switch interface language automatically.

### Have you considered any alternatives?

There is no other option as of now, as the current element's web side defaults to English after every refresh.

Further, I'd like to have the preferred language option in the account preferences, although **I'm not sure if this suggestion is for you guys or the matrix**, so here it is for now

**Comment by t3chguy** [comment]
This should already happen. 

https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/languageHandler.tsx#L534-L538
https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/languageHandler.tsx#L95-L102

Please provide reproduction steps, a video, and logs for your issue
