### ISSUE TITLE
"Sign in instead" link is not working

### ISSUE THREAD

**Issue by SPiRiT369** [vector-im/element-web#26268]
### Steps to reproduce

When you go to the "Create account" page, there is a link at the bottom to return to the sign-in page.
This link is not working and is not clickable.

Happens to me in latest Element Web (v1.11.45) and can be seen in https://app.element.io/#/register

![image](https://github.com/vector-im/element-web/assets/63514368/a6ab28da-aa6e-46a3-b1c3-3081b19d16fa)

#### What did you expect?
Obviously, the link should be clickable and point to the sign-in page.

#### What happened instead?
Nothing.

### Operating system

Linux

### Browser information

Firefox + Brave

### URL for webapp

https://app.element.io/#/register

### Application version

1.11.45

### Homeserver

matrix.org and others

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Doesn't reproduce on latest develop
<img width="662" alt="Screenshot 2023-10-02 at 10 02 51" src="https://github.com/vector-im/element-web/assets/3055605/bf18290e-a1ca-4935-8b9e-0536701f5ed9">

**Comment by manancodes** [comment]
Already fixed with https://github.com/matrix-org/matrix-react-sdk/pull/11630
