### ISSUE TITLE
Double chat (main + side) when un-maximising a widget with side chat

### ISSUE THREAD

**Issue by Malix-off** [vector-im/element-web#26265]
### Steps to reproduce

- Create an empty room
- Add a custom widget with e.g. https://example.com
- Click the pin from the widget list in the right panel
- Click maximise
- Chat should now be on the right side, widget in the main area
- Click un-maximise widget

#### What did you expect?

![image](https://github.com/vector-im/element-web/assets/76160668/07f017b0-461b-48b5-a9fc-55327f5b25a2)

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/76160668/84381b52-4b71-425e-9126-208221988106)

### Will you send logs?

No

**Comment by weeman1337** [comment]
Can reproduce. Updated repro steps in the issue description.

**Comment by weeman1337** [comment]
Reopened because the fix [was rolled back](https://github.com/matrix-org/matrix-react-sdk/pull/11786)

**Comment by HarHarLinks** [comment]
potential dupe of #23591?

**Comment by t3chguy** [comment]
Duplicate of #23591
