### ISSUE TITLE
Stop bundling emoji fonts

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#26260]
Safari 17 has regressed our bundled emoji font setup (fixed in https://github.com/matrix-org/matrix-react-sdk/pull/11673). This has given reason to reconsider what we're doing here. When we started bundling the fonts years ago, the situation across browsers and operating systems was much different. These days recent versions of macOS and Windows come with their own emoji fonts (see https://emojipedia.org/caniemoji). Major Linux distributions such as Ubuntu or Fedora do the same.

Meanwhile both Element iOS and Element X iOS use native emojis only. This means that emoji are also not part of our brand identity.

We should explore the impact of removing the bundled emoji fonts and falling back to what the operating system supports. This should be verified in terms of support and coverage across major operating systems.

**Comment by t3chguy** [comment]
Unblocks https://github.com/vector-im/element-web/issues/25701
