### ISSUE TITLE
Unoccupied empty column reserved in the message screen?

### ISSUE THREAD

**Issue by nabijaczleweli** [vector-im/element-web#26282]
### Steps to reproduce

1. open a room

#### What did you expect?
Messages are shown in the part of the window that isn't the sidebar

#### What happened instead?
There's a sidebar on the right taht does nothing:
![image](https://github.com/vector-im/element-web/assets/6709544/43754515-8dba-4885-b7c3-9696ed5999d8)

#### Fix
This appears to be an uhhhhhhhhhhhhh this thing
![](https://github.com/vector-im/element-web/assets/6709544/e3189c98-8278-4c3b-b3b5-52029779d2eb)

Which is empty. So unchecking the `width: 90px;` statement for `.mx_EventTile[data-layout=group] .mx_EventTile_msgOption, .mx_EventTile[data-layout=irc] .mx_EventTile_msgOption {` makes the page render correctly:
![image](https://github.com/vector-im/element-web/assets/6709544/da8c0cce-7247-4aba-bffb-aba3f69a44b3)

Well, "correctly". At least it's just the `padding: var(--RoomView_MessageList-padding);` on `.mx_RoomView_MessageList` like in #26281.

Indeed, replacing that clause with
```css
    padding: 0;
    padding-left: calc(var(--RoomView_MessageList-padding)/2);
```
turns it into something that isn't an affront to all screen users:
![](https://github.com/vector-im/element-web/assets/6709544/bbff5953-51c8-4aa8-9ef6-865622652dff)

### Operating system

Windows

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

clicked enter on "Element Setup.exe"

### Homeserver

nabijaczleweli.xyz Synapse 1.93.0-1

### Will you send logs?

No

**Comment by weeman1337** [comment]
@nabijaczleweli  Thank you for opening an issue. Unfortunately there is not enough information there for me to be able to reproduce it. Please update the description with steps/screenshots/video/more details so our developers can have a look at it: Can you send the exact settings from the appearance section?

**Comment by nabijaczleweli** [comment]
Unclear to me how many more screenshots you can possibly want, but sure. Browser:
![image](https://github.com/vector-im/element-web/assets/6709544/682f9450-f2ec-4614-b2af-340acb8d7a9b)
Desktop:
![image](https://github.com/vector-im/element-web/assets/6709544/aab888ee-6b7b-4e45-b362-a03de9603961)


Browser appearance:
![image](https://github.com/vector-im/element-web/assets/6709544/5bcb92e0-4857-440d-b4a3-f5375da334ef)
Desktop appearance:
![image](https://github.com/vector-im/element-web/assets/6709544/240fa213-63fb-4367-9df2-452b40c7b621)
![image](https://github.com/vector-im/element-web/assets/6709544/f07c2abc-af16-42f3-999f-4af56bbb05d7)

**Comment by t3chguy** [comment]
Looks like you mean the read receipts column?

![image](https://github.com/vector-im/element-web/assets/2403652/8013f532-5915-4fbb-8137-7ad791400889)

You can disable it. `.mx_EventTile_msgOption` is controlled by `Show read receipts sent by other users`

**Comment by nabijaczleweli** [comment]
It sure appears to be. But it's even more egregious in your screenshot, why is it so wide? It's not that wide on a phone (otherwise that'd be half your screen)? The empty column has no bearing on the actual receipts (as proven by "if you set it to `width: 0` they still show, and the actual post on which they are shrinks by how wide they are"). The receipts aren't actually that wide? Even in your screenshot? Why is significant hunk of the screen designed to be completely empty?
