### ISSUE TITLE
[e2e] voip event shifted to avatar photo on mouse on

### ISSUE THREAD

**Issue by jeangb** [vector-im/element-web#2628]
To reproduce:
- Have a 1:1 room with encryption enabled
- Start a call then hangout later
- Put the mouse on the voip event

Event is displayed on the top of the avatar photo
![padlock shifted to the right](https://cloud.githubusercontent.com/assets/22364949/20524962/64097828-b0bd-11e6-9259-edd1a38fc27b.jpg)

**Comment by SimonBrandner** [comment]
Closing as this doesn't seem to be a problem anymore. @jeangb, feel free to re-open if it still is
