### ISSUE TITLE
Element-R: After interactive verification the backup decryption key is not in cache

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#26288]
### Steps to reproduce

1. Create a session on web, create an encrypted room then setup recovery.
2. Use another tab/browser to login with the same account
3. Verify the new session with the old one using emoji

#### What did you expect?

Expect to get access to my history.

#### What happened instead?

History messages are `Unable to decrypt`

<img width="508" alt="image" src="https://github.com/vector-im/element-web/assets/9841565/b280165a-2108-48c3-b332-f9252aa58088">

^ the backup decryption key is not cache, it should have been received via secret gossping and stored.

The restore from backup button ask to enter the passphrase
<img width="515" alt="image" src="https://github.com/vector-im/element-web/assets/9841565/2c1e83c0-171d-425f-aa55-05d7f970cefd">

### Operating system

macOS

### Browser information

chrome  117.0.5938.88

### Will you send logs?

No

**Comment by richvdh** [comment]
As I understand it, the problem here is that we are not handling the incoming `m.secret.send` message from the other device that includes the backup decryption key
