### ISSUE TITLE
Egregious bottom padding on .mx_RoomView_MessageList

### ISSUE THREAD

**Issue by nabijaczleweli** [vector-im/element-web#26281]
### Steps to reproduce

1. open a room

#### What did you expect?
The messages end where the edit box begins

#### What happened instead?
Mouse cursor where the arrow is highlights an egregious padding.
![](https://github.com/vector-im/element-web/assets/6709544/1d6dc95a-34db-4b9d-a367-0120515dc72c)

#### Fix
Spec `padding-bottom: 0;`:
![image](https://github.com/vector-im/element-web/assets/6709544/a2e5a29c-2519-417a-a278-f6163f7a491c)

There's still some space there, but it's layout space not "ummmm who up paddin they box" space

### Operating system

Window

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

clicked enter on "Element Setup.exe"

### Homeserver

nabijaczleweli.xyz Synapse 1.93.0-1

### Will you send logs?

No

**Comment by germain-gg** [comment]
Thank you for opening this issue. There are a couple of other things at play with this design decisions, from the Rich Text Editor labs flag, to the update of the new visual language of Element.

I will close that issue as the design team has been working on an upgraded version of this.
