### ISSUE TITLE
reports of RRs interacting badly with collapsed join/parts

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2629]

**Comment by lukebarnard1** [comment]
As far as I can tell, collapsing join/parts don't display read receipts, but when expanded they behave as expected. This will require making `MemberListEventSummary` be a place where RR's can hang around.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/21717

**Comment by justjanne** [comment]
It was decided not to support this functionality for the time being. Read receipts for collapsed event summaries will remain the way they currently are.

See https://github.com/matrix-org/matrix-react-sdk/pull/8446#pullrequestreview-967589502 for clarification.
