### ISSUE TITLE
Flaky cypress test: `Read receipts > Paging up > "before each" hook for "Looking in thread view to find old threads that were never read makes the room unread"`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26298]
https://github.com/matrix-org/matrix-js-sdk/pull/3770 / https://github.com/matrix-org/matrix-js-sdk/actions/runs/6399358566/job/17371275514#step:8:18804

**Comment by andybalaam** [comment]
> https://github.com/matrix-org/matrix-js-sdk/actions/runs/6496998583/job/17645161700

This looks like slow startup of the client. Hopefully fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11742

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/26331
