### ISSUE TITLE
Element-R: "unknown secret request" spam

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26303]
There is lots of this spam in the console:

```
WARN /home/runner/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/bcbb7c6/crates/matrix-sdk-crypto/src/gossiping/machine.rs:767 Unknown outgoing secret request; cannot mark as sent
```

It seems like it is getting logged for every outgoing `m.room_key_request`

**Comment by BillCarsonFr** [comment]
False positive due to https://github.com/matrix-org/matrix-rust-sdk/issues/2662

**Comment by richvdh** [comment]
fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3823
