### ISSUE TITLE
Element-R: Wire up automatic UISI rageshake reporting (same which already exists)

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26304]
Florian suggests that it might anyway be better to streamline the process of manually sending a rageshake (eg right-click on a UISI)

**Comment by richvdh** [comment]
(this issue based on a note from @BillCarsonFr)

**Comment by BillCarsonFr** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3710
