### ISSUE TITLE
ElementR: Secret gossiping fails after verification with error `panicked at 'Parking not supported on this platform'` 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#26301]
### Steps to reproduce

- Create a session on web, create an encrypted room then setup recovery.
- Use another tab/browser to login with the same account
- Verify the new session with the old one using emoji

![parking](https://github.com/vector-im/element-web/assets/9841565/a31e3a8b-7beb-4e50-ad59-9aa7924c23ec)

The new session is not receiving the secret gossip.
If you refresh the first one, then secret gossiping is resumed

=> but not all secrets are received. It changes everytime, sometime usk is missing some time ssk

### Operating system

mac OS M1

### Browser information

chrome

### Will you send logs?

Yes

**Comment by richvdh** [comment]
@BillCarsonFr is this on a local build of the rust-sdk? Or a hosted instance? Or a download?

**Comment by BillCarsonFr** [comment]
happening on full local setup (web , react-sdk, js-sdk, matrix-rust-sdk-crypto-wasm), and local synapse

**Comment by richvdh** [comment]
to be clear, it is the *existing* device that panics, not the new one :roll_eyes:

**Comment by BillCarsonFr** [comment]
Some additional info:

The panic only occurs if there is no pre exiting olm session with the new device.
If for example before starting the verification you send a message in an encrypted room it will be fine.

Recorded that here as it might be worth looking at https://github.com/matrix-org/matrix-rust-sdk/issues/2667
