### ISSUE TITLE
OIDC: account management is not directed to OP for statically configured OPs

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#26305]
### Steps to reproduce

1. Add `M_AUTHENTICATION` to config.json, using a homeserver that does not have a client/well-known
2. Authenticate via native OIDC
3. Go to general settings, expect to see 'your account is managed by OP'

#### What happened instead?
Current code here relies on client well-known
Use `OidcClientStore` instead, which falls back to authenticated issuer.

### Will you send logs?

No

**Comment by kerryarchibald** [comment]
Fix after https://github.com/vector-im/element-web/issues/25394

**Comment by robintown** [comment]
I'm unsure how to triage this since I don't know what 'OP' refers to, and since there's a fix that's ready to merge, I'll leave it untriaged
