### ISSUE TITLE
`Sign in instead` button is not clickable on the `Create account` page

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#26310]
### Steps to reproduce

1. Go to https://app.element.io/#/login
2. Click on `Create an account`
3. `Sign in instead` at the bottom of the page is not clickable 

<img width="737" alt="image" src="https://github.com/vector-im/element-web/assets/2621378/51f34dbf-f1cf-4f80-8dda-06abc220ffeb">

#### What did you expect?

I'm expecting to be back to the sign in page

#### What happened instead?

Nothing happened

### URL for webapp

https://app.element.io

### Will you send logs?

Yes

**Comment by kerryarchibald** [comment]
Closing as duplicate
