### ISSUE TITLE
Emoji cause topics being cut off in new room header

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26326]
### Steps to reproduce

1. enable labs new room headers on develop.element.io
2. try to view topic containing emoji https://matrix.to/#/#element-design:matrix.org

#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/2803622/c030a231-534c-49ca-a9b5-ea20977a47e8)

### Browser information

firefox 117

### URL for webapp

develop.element.io

### Application version

Element version: 22f2b1f9e9df-react-54fa9a572e1c-js-02ca5c78cf4e Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by richvdh** [comment]
For links: the fix to this was reverted by https://github.com/matrix-org/matrix-react-sdk/pull/11774 due to https://github.com/vector-im/element-web/issues/26401
