### ISSUE TITLE
When changing display name, not all rooms are changed, and I have an error "fetch failed: Failed to fetch"

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#26338]
### Steps to reproduce

Try to change display name, this error appears:

> Failed to save your profile
> fetch failed: Failed to fetch

#### What did you expect?

Change all rooms, no error

#### What happened instead?

An error.

### Operating system

macOS

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by benparsons** [comment]
I tried to submit logs, but there is an infinite spinner "Collecting app version information ..."

**Comment by t3chguy** [comment]
This is an issue with the server. The server should not timeout like it does here. The server tries to do it entirely synchronously and its reverse proxy times out causing a CORS error. Nothing the client can do here other than potentially a better error if the spec made a suggestion for such
