### ISSUE TITLE
Cannot turn off notifications for @room.  

### ISSUE THREAD

**Issue by sprfolker** [vector-im/element-web#26332]
### Steps to reproduce

1. Having used Element for years I go to the notification settings 
2. Messages in one to one chats-noisy
-encr messages in one to one chats noisy
-messages in group chats-off
-excr messages in group chats-off

Messages containing display name Noisy
containing username-noisy
Messages containing @room off
Messages containing Keywords off 

Still i get alerts in red for at room.   The problem is I am unable to see when I am specifically tagged and most of the messages are from a different department and unnecessary to me
![image](https://github.com/vector-im/element-web/assets/147224297/6b5fc942-9703-4f60-ab44-40d1fabb7279)

### Operating system

Pop!_OS 22.04 LTS

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

element.io

### Homeserver

chat.serverplus.com

### Will you send logs?

Yes

**Comment by kerryarchibald** [comment]
Duplicate https://github.com/vector-im/element-web/issues/26227, fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11667

This fix is already available on [develop.element.io](https://develop.element.io/) and will be included in the next release.
