### ISSUE TITLE
[Disabled] Flaky test Read receipts > Paging up > "Looking in thread view to find old threads that were never read makes the room unread"

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26331]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6431821008/job/17465454807

```
   1 failing

  1) Read receipts
       Paging up
         Looking in thread view to find old threads that were never read makes the room unread:

      Timed out retrying after 10000ms
      + expected - actual

      -'7'
      +'6'
```

**Comment by t3chguy** [comment]
Another instance https://github.com/matrix-org/matrix-js-sdk/actions/runs/6563825820/job/17828948754

**Comment by andybalaam** [comment]
[Looking in thread view to find old threads that were never read makes the room unread](https://github.com/matrix-org/matrix-react-sdk/actions/runs/6825419149/job/18563219839#step:8:559)

**Comment by andybalaam** [comment]
Re-disabling
