### ISSUE TITLE
„Missing session data“ with fresh session

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26339]
### Steps to reproduce

1. Log in to Element Web
2. Verify your session
3. Close the browser window
4. Reopen the window

#### What did you expect?

Still be logged in

#### What happened instead?

„Missing session data“

### Browser information

Chromium 117.0.5938.132

Ubuntu 22.04.3 LTS

### URL for webapp

https://app.element.io/

### Homeserver

element.io

### Will you send logs?

No

**Comment by weeman1337** [comment]
I am getting the same with Element Desktop:

```
rageshake.ts:74 Failed to open log database: UnknownError
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 Error: Failed to open log database: UnknownError
    at req.onerror (rageshake.ts:158:24)
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 StorageManager.idbLoad failed for account:mx_access_token Event
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 StorageManager.idbLoad failed for account:mx_refresh_token Event
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 getSessionLock[dbc6f150-f9dc-4566-9e3f-14270b0678f5] No other session has the lock: proceeding with startup
rageshake.ts:74 StorageManager.idbLoad failed for account:mx_access_token Event
consoleObj.<computed> @ rageshake.ts:74
rageshake.ts:74 StorageManager.idbLoad failed for account:mx_refresh_token Event
consoleObj.<computed> @ rageshake.ts:74
```

**Comment by robintown** [comment]
@weeman1337 Can you check whether you accepted the 'store data in persistent storage' permission in the browser? (Not sure what the exact message is on Chromium…)

**Comment by robintown** [comment]
Unable to reproduce on Firefox

**Comment by weeman1337** [comment]
> @weeman1337 Can you check whether you accepted the 'store data in persistent storage' permission in the browser? (Not sure what the exact message is on Chromium…)

Unfortunately I cannot find such a permission :shrug:

**Comment by weeman1337** [comment]
I will add a „Send logs“ button to the dialog. We are then going to close this issue and hope, that we get better debug data in the future.

**Comment by weeman1337** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/26464 with logs

**Comment by weeman1337** [comment]
> I will add a „Send logs“ button to the dialog. We are then going to close this issue and hope, that we get better debug data in the future.

The button is already there if a URL is configured
