### ISSUE TITLE
On „Create account“ „Sign in instead“ is not a link any more

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#26340]
### Steps to reproduce

1. Go to https://app.element.io/
2. Click „create account“
3. Try to go back

#### What did you expect?

„Sign in instead“ should be a link

#### What happened instead?

It is only a text

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Chromium 117

### URL for webapp

https://app.element.io/

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/26268

**Comment by t3chguy** [comment]
Already fixed on develop
