### ISSUE TITLE
Element-R: takes **ages** to load

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26352]
If I ctrl-R in an EWR tab for my main account, it takes over 60 seconds for the spinner to go away.

**Comment by poljar** [comment]
One source for the slowness might be the usage of a passphrase when opening the store:

https://github.com/matrix-org/matrix-rust-sdk/blob/a433d51efc44fbab6515a35b2589dcf08920f087/crates/matrix-sdk-indexeddb/src/crypto_store.rs#L320

This step will use PBKDF2 to expand the passphrase into a 32 byte key.

The `StoreCipher` can be initialized with a random key, this skips the PBKDF2 step:

https://github.com/matrix-org/matrix-rust-sdk/blob/a433d51efc44fbab6515a35b2589dcf08920f087/crates/matrix-sdk-store-encryption/src/lib.rs#L317

The above method needs to be exposed in the IndexedDB cryptostore implementation.

**Comment by BillCarsonFr** [comment]
I did some tests and here are the results. Ran 10 refreshs with a legacy and a rust stack with my real account:

<img width="624" alt="image" src="https://github.com/vector-im/element-web/assets/9841565/61a6bcde-e303-479b-8a25-9b041c3be637">

There was a long run for rust (first one) other than that it looks similar?
It's not taking 60s anymore
