### ISSUE TITLE
Element-R: Wire up user verification toast to new crypto

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#26356]
The user verification toast should react to the verification step for the new crypto

**Comment by BillCarsonFr** [comment]
I need more details, I am not sure to understand.
When logged-in as Bob and alice starts a user verification I can see the toast:
![image](https://github.com/vector-im/element-web/assets/9841565/81c36685-728d-41bd-81a2-a8073fc1b75c)

If I cancel from alice, the toast is dismissed

**Comment by BillCarsonFr** [comment]
can't reproduce
