### ISSUE TITLE
UTD from one user when messages sent from Element Web

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-web#26353]
### Steps to reproduce

1. Go on holidays for two weeks and do not open Element at all
2. Come back and catch up
3. All messages received from one user are all UTD in DMs, but they can see messages they send.
4. Ask that user to send messages from Element X and it works...

#### What did you expect?

No UTDs

#### What happened instead?

It seems that the OLM (?!) session is corrupted

### Will you send logs?

Yes

**Comment by germain-gg** [comment]
Triaging as occasional as this happened to me, and @daniellekirkwood after coming back from different holidays. And was also anecdotaly reported in the past

**Comment by weeman1337** [comment]
Had similar problems after one week off. Unfortunately I wasn't able to get logs because other things went wrong quickly and I got logged out.

**Comment by germain-gg** [comment]
Not planned to be worked on as @richvdh is focusing on new crypto (Element R)
