### ISSUE TITLE
sticker error

### ISSUE THREAD

**Issue by niudin** [vector-im/element-web#26372]
### Steps to reproduce

Cannot connect to integration manager
The integration manager is offline or it cannot reach your homeserver.
<img width="358" alt="image" src="https://github.com/vector-im/element-web/assets/110970338/dbac4505-494f-48d4-826f-d4838deae365">
<img width="297" alt="image" src="https://github.com/vector-im/element-web/assets/110970338/2df9e2c8-ed64-4439-8b3e-08e77903810b">
<img width="631" alt="image" src="https://github.com/vector-im/element-web/assets/110970338/01718894-c20a-436f-a7de-629b56f667f5">

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs

**Comment by niudin** [comment]
好像没有看到日志

Michael Telatynski ***@***.***> 于2023年10月16日周一 15:42写道：

**Comment by t3chguy** [comment]
This issue tracker is English only.

**Comment by niudin** [comment]
not look log

Michael Telatynski ***@***.***> 于2023年10月16日周一 19:42写道：

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/9fb16dc7-3721-4d2e-af9d-03c0fa96b913)

**Comment by niudin** [comment]
[image: image.png]

[image: image.png]

[image: image.png]


Michael Telatynski ***@***.***> 于2023年10月17日周二 15:37写道：

**Comment by niudin** [comment]
Oct 20 09:36:53 okchat-im001 matrix-synapse[14266]: 2023-10-20 01:36:53,722
- synapse.access.http.8008 - 450 - INFO - POST-191806 - 61.149.211.94 -
8008 - ***@***.***:okchat.org} Processed request: 0.005sec/0.001sec
(0.002sec, 0.002sec) (0.001sec/0.002sec/1) 117B 200 "POST
/_matrix/client/r0/user/%40testtest%3Aokchat.org/openid/request_token
HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" [0
dbevts]
Oct 20 09:36:54 okchat-im001 matrix-synapse[14266]: 2023-10-20 01:36:54,207
- synapse.access.http.8008 - 450 - INFO - GET-191798 - 61.149.211.94 - 8008
- ***@***.***:okchat.org} Processed request: 30.004sec/0.001sec (0.006sec,
0.000sec) (0.001sec/0.001sec/1) 236B 200 "GET
/_matrix/client/r0/sync?filter=0&timeout=30000&since=s899_8437_192_305_619_1_50_803_1
HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" [0
dbevts]
Oct 20 09:36:54 okchat-im001 matrix-synapse[14266]: 2023-10-20 01:36:54,328
- synapse.access.http.8008 - 450 - INFO - GET-191808 - 61.149.211.94 - 8008
- ***@***.***:okchat.org} Processed request: 0.009sec/0.001sec (0.007sec,
0.001sec) (0.001sec/0.001sec/1) 390B 200 "GET
/_matrix/client/r0/sync?filter=0&timeout=30000&since=s899_8437_192_305_619_1_50_803_1
HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" [0
dbevts]
Oct 20 09:36:56 okchat-im001 matrix-synapse[14266]: 2023-10-20 01:36:56,100
- synapse.util.caches.lrucache - 206 - INFO -
LruCache._expire_old_entries-79842 - Dropped 0 items from caches

Tito ***@***.***> 于2023年10月19日周四 10:15写道：

**Comment by niudin** [comment]
[image: image.png]

Tito ***@***.***> 于2023年10月20日周五 09:37写道：

**Comment by niudin** [comment]
{"errcode":"M_UNKNOWN","error":"Failed to authenticate user"}

Tito ***@***.***> 于2023年10月20日周五 09:40写道：

**Comment by t3chguy** [comment]
Closing due to instructions being ignored.
If you have issues with the server logs then I suggest asking for help with that project, this is the Element Web repo and we only deal with Element Web logs which you were given instructions on how to submit.
