### ISSUE TITLE
Element R reports "Backup key cached: not found locally"

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-web#26377]
### Steps to reproduce

Dogfooding R from https://pr10080--matrix-react-sdk.netlify.app/
Logged in to the element.io HS and done SAS verification.

### Outcome

After successfully decrypting all content I can see in the security preferences: "Backup key cached: not found locally"
Whilst on non-R Element it says: "cached locally, well formed"

### Browser information

Chrome Version 118.0.5993.70 (Official Build) (arm64)

### URL for webapp

https://pr10080--matrix-react-sdk.netlify.app/

### Homeserver

element.io

### Will you send logs?

No

**Comment by BillCarsonFr** [comment]
We think it's fixed, can be re-opened in case of new occurence.
