### ISSUE TITLE
The slash command `/replaceroom`

### ISSUE THREAD

**Issue by erkinalp** [vector-im/element-web#26370]
### Your use case

Replaces previous `/upgraderoom`, with the identical syntax. Needed after [#upgraderoom has been removed](https://github.com/matrix-org/matrix-react-sdk/pull/11744).

### Additional context

@Mikaela

**Comment by Mikaela** [comment]
I am not sure what makes me an additional context, but I understood /devtools lets /upgraderoom still be enabled through the developer mode switch?

**Comment by erkinalp** [comment]
`/replaceroom` ought to be available *regardless of* the setting.

**Comment by t3chguy** [comment]
The issue from the core team asked for the option to be moved into devtools so such has been done - https://github.com/vector-im/element-web/issues/17620

Renaming it to replaceroom just confuses technical people who know the ins and outs of Matrix, as per the issue linked

> we shouldn't be encouraging room proliferation as a solution to problems, and this is largely technical/poweruser button to push anyways

**Comment by erkinalp** [comment]
Wrong type of closure: supposed to be closed as *not planned*

**Comment by erkinalp** [comment]
On GitHub, "closed as completed" means "done", and "closed as not planned" means "won't do"/"duplicate"/"invalid".

**Comment by t3chguy** [comment]
Github is just a tool, not a way of life. We have automations which both drive and depend on the close status so it means what we say it means based on our workflows, not what someone else dictates.
