### ISSUE TITLE
Element R: Clicking on Restore key backup causes performance issues

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#26397]
### Steps to reproduce

STR:

1. Log in and verify your device with another device (verifying may not be necessary, but it's what I did)
2. Go to Settings -> Security & Privacy -> Key backup -> Restore backup
3. Type in your key backup passphrase
4. Wait a little while

#### What did you expect?

A modal appearing showing the progress of the key backup, and for the key backup to eventually complete successfully. 

#### What happened instead?

The app UI begins to freeze every 2-3s for about 5-10s. The modal asking for a key backup passphrase re-appeared, but the app was too laggy to try and enter my key backup passphrase again.

After refreshing the app, it continues to continuously freeze.

### Operating system

NixOS Linux

### Browser information

Chromium 117.0.5938.149

### URL for webapp

https://pr10080--matrix-react-sdk.netlify.app

### Application version

b206e0cea053-react-35577e62f707-js-5595e8497f89

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment]
Duplicate https://github.com/vector-im/element-web/issues/23359
