### ISSUE TITLE
Element Logo in search bar is filling the complete height

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26408]
### Steps to reproduce

1. Click on Search icon in new right panel

<del>maybe regressed from https://github.com/matrix-org/matrix-react-sdk/pull/11664 (ping @germain-gg)</del>

#### What did you expect?
normal search header bar
#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/2803622/ffc67e47-5e5a-4e20-abb4-a6734511266c)

### Operating system

arch

### Browser information

firefox 118.0.2

### URL for webapp

https://develop.element.io

### Application version

Element version: 80ba22aba28f-react-f784a085fdfc-js-c0264954eda2 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
same for files:
![image](https://github.com/vector-im/element-web/assets/2803622/b9c186a2-6c31-4835-9633-3236e3f224ce)

**Comment by germain-gg** [comment]
Unsure i can confirm this has been regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11664 but nonetheless added a fix to bring UI to a sane level again.

**Comment by t3chguy** [comment]
Affects staging, regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11746
