### ISSUE TITLE
It shows "Unsupported browser" when I open my self-host element-web with Chrome

### ISSUE THREAD

**Issue by asuka08** [vector-im/element-web#26402]
### Steps to reproduce

I pull the element-web docker image from hub.docker.com, the version is v1.11.46
When I started it on my cloud server, and browsed it on my mac Chrome, it showed:

Unsupported browser
Your browser can't run Element
Element uses advanced browser features which aren't supported by your current browser.

Please install [Chrome](https://www.google.com/chrome), [Firefox](https://firefox.com/), or [Safari](https://apple.com/safari) for the best experience.

You can continue using your current browser, but some or all features may not work and the look and feel of the application may be incorrect.

I understand the risks and wish to continue

<img width="779" alt="screenshot 2023-10-19 18 43 42" src="https://github.com/vector-im/element-web/assets/5468663/3c792045-40d9-4be6-966f-9232ef964928">

#### What did you expect?
How can I fix it? Or let it skip the browser check?

### Operating system

macOS

### Browser information

 Chrome v117.0.5938.92 (arm64)

### Application version

 Element ： 1.11.45   Olm ： 3.2.14

### Homeserver

synapse, on my self host cloud server

### Will you send logs?

No

**Comment by t3chguy** [comment]
Your browser disables features due to no https

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

**Comment by asuka08** [comment]
OK, I understood.

I just builded a test env, when I deploy a formal on, I will add SSL cert on it.

Ithink, this promt may let some user confuse.
