### ISSUE TITLE
Flaky test: Invite dialog >> should support inviting a user to a room

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26407]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/6586330794

```
  1) Invite dialog
       should support inviting a user to a room:
     AssertionError: Timed out retrying after 10000ms: Unable to find an accessible element with the role "button" and name `/Invite to this room/`
```

**Comment by germain-gg** [comment]
Actually not a flake, some button moved, and caused the test to fail.
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/11664/commits/8470c084159d667dae800d1b8e16df4d7816dd4e
