### ISSUE TITLE
Element-R: lazy loading of members not working

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26419]
Element-R loads all the members of encrypted rooms at startup, making lazy-loading a bit useless

https://github.com/matrix-org/matrix-js-sdk/blob/6e2ac03f7e130ec721fc67176883571547608ee6/src/rust-crypto/rust-crypto.ts#L1237

legacy crypto has code to handle this:  https://github.com/matrix-org/matrix-js-sdk/blob/6e2ac03f7e130ec721fc67176883571547608ee6/src/crypto/index.ts#L2928

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/26418
