### ISSUE TITLE
matrix.to link attempts to open Beeper, not Element Desktop, even when clicking on Element

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#26415]
### Steps to reproduce

1. Follow a matrix.to link
2. Select Element (Desktop) as client

#### What did you expect?
Element Desktop opens and goes to the link

#### What happened instead?
Browser asks to open Beeper

![image](https://github.com/vector-im/element-web/assets/640121/c18e75f3-8314-4f34-88cc-3b2ca676124a)

### Operating system

Windows 11

### Application version

Version von Element: 1.11.46 Version von Olm: 3.2.14

### How did you install the app?

Element

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Sounds like both applications register the same protocol handler, you can choose the preferred one in Settings

https://support.microsoft.com/en-us/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d

**Comment by kongo09** [comment]
`Apps` > `Default apps` does not register Element or Beeper.

There is also no default file type and no default link type registered with Windows.

This cannot be the problem.

**Comment by kongo09** [comment]
I was able to find the following in my registry:

![image](https://github.com/vector-im/element-web/assets/640121/9c13df29-17d4-4dc6-93a2-a08ab1c88a66)

If that's the root cause and Beeper registered it there, this is something we should kindly ask them to not do. Maybe that's because they fork Element Desktop in a proprietary way without thinking about this.

Can we please convert this into a feature request for Element Desktop to actively check if it is still registered correctly with the system and if not to offer the user to re-register. That's a behaviour known from browsers that discover that they're no longer default.

**Comment by kongo09** [comment]
https://github.com/beeper/self-host/issues/34

**Comment by t3chguy** [comment]
> Can we please convert this into a feature request for Element Desktop to actively check if it is still registered correctly with the system and if not to offer the user to re-register.

We continually re-register via the Electron API I linked above. https://github.com/vector-im/element-desktop/blob/ca0a48196c256f597c25604ff27ddf620ea6ed9b/src/protocol.ts#L103
