### ISSUE TITLE
in /register the "Sign in here" link is missing in the german version

### ISSUE THREAD

**Issue by nebocamin** [vector-im/element-web#26412]
### Steps to reproduce

go to 
https://app.element.io/#/register

switch the language to german

#### What did you expect?
after validation or just to sign in instead, i want to click there to switch from sign up to sign in.
![Screenshot from 2023-10-20 22-55-23](https://github.com/vector-im/element-web/assets/3319621/4456c11c-4881-48fb-adc0-51ec59fe1e51)

#### What happened instead?
the "Already have an account?" string in german is there but the green "sign in here" afterwards is missing in the german version.

![Screenshot from 2023-10-20 23-27-02](https://github.com/vector-im/element-web/assets/3319621/478962fa-ccc8-41fe-85f9-76090d68e9fb)

### URL for webapp

https://app.element.io/#/register

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Looks like the translation is broken, those are managed by the community - see https://web-docs.element.dev/Element%20Web/translating.html

**Comment by weeman1337** [comment]
What does broken mean here @t3chguy  ? The translation seems to be there:

![image](https://github.com/vector-im/element-web/assets/6216686/bc1ee911-03c3-455c-bdaf-7d298bf4daa7)

**Comment by t3chguy** [comment]
That's the wrong one, the english is 
![image](https://github.com/vector-im/element-web/assets/2403652/d7d1c789-bf61-42a0-a5cc-2326fdc6736d)

https://localazy.com/p/element-web/phrases/269/edit/_a7632610708388546964

**Comment by weeman1337** [comment]
Upsi :D Thanks
