### ISSUE TITLE
Element-R: Will force download of member list during initial sync with lazy loading

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-web#26418]
### Steps to reproduce

1. Login with an existing account with several big rooms

#### What did you expect?
Lasy loading is enabled, to allow faster loading of rooms.

#### What happened instead?
For each of the rooms a loadRoomMember is called during the initial sync handling.

The rust crypto is doing that when handing the `m.room.encryption` state event:

https://github.com/matrix-org/matrix-js-sdk/blob/6e2ac03f7e130ec721fc67176883571547608ee6/src/rust-crypto/rust-crypto.ts#L1237

```
        // start tracking devices for any users already known to be in this room.
        const members = await room.getEncryptionTargetMembers();
        await this.olmMachine.updateTrackedUsers(members.map((u) => new RustSdkCryptoJs.UserId(u.userId)));
```

This will defeat lazy loading and make the initial sync slow.

Probably one of the source for https://github.com/vector-im/element-web/issues/26352

### Operating system

MacOs

### How did you install the app?

https://pr10080--matrix-react-sdk.netlify.app

### Will you send logs?

No

**Comment by richvdh** [comment]
There are even tests for this in `spec/integ/crypto/crypto.spec.ts` which are disabled for the new backend
