### ISSUE TITLE
Right panel for room opens after update reload

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#26421]
### Steps to reproduce

1. Apply an update on the develop version while in a room

#### What did you expect?

Right panel has the same state as before the reload

#### What happened instead?

The right panel opens up.

Possibly regressed by https://github.com/matrix-org/matrix-react-sdk/pull/11697

### Operating system

Fedora Silverblue 38

### Browser information

Firefox 118.0.1 (64-bit)

### URL for webapp

develop.element.io

### Application version

Version von Element: 80ba22aba28f-react-c44c772246bd-js-2f3f0b340ea4 Version von Olm: 3.2.14

### Homeserver

matrix.midnightthoughts.space

### Will you send logs?

No

**Comment by HarHarLinks** [comment]
simply reloading develop.element.io is sufficient for me, doesn't need an update available
