### ISSUE TITLE
Element X still unverified after successful flow

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-web#26428]
This ticket is for Element X, just wanted to upload logs from the desktop app.

### Steps to reproduce

1. Loging fresh on Element X
2. Emoji verify against Element Desktop
3. See the RustSDK still report the session as unverified

#### What did you expect?

The session to be fully verified

#### What happened instead?

Session still unverified

### Operating system

macOS

### Application version

Element version: 1.11.46 Olm version: 3.2.14

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
> This ticket is for Element X, just wanted to upload logs from the desktop app.

You can also mention an issue from Element X when sending the rageshake.
