### ISSUE TITLE
Rare bug where FilePanel can get stale

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2642]
Amandine ended up with a gap of a few weeks in her FilePanel for a room.  Refreshing fixed it.  No logs; filing in for future reference

**Comment by afranke** [comment]
Just happened to me on Element Web 1.7.34.

**Comment by Palid** [comment]
@SimonBrandner do you think this one is also fixed?

**Comment by SimonBrandner** [comment]
I think this one has been fixed then forgotten about and then regressed again, so hopefully, it is. Scream if you ever see this again!
