### ISSUE TITLE
[Disabled] Flaky cypress test `read receipts > Paging up through old messages after a room is read leaves the room read`

### ISSUE THREAD

**Issue by kerryarchibald** [vector-im/element-web#26437]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6630084876/job/18010786208
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6628219729/job/18006485360
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6627896416/job/18004192721

**Comment by kerryarchibald** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6627896416/job/18004192721

**Comment by kerryarchibald** [comment]
This flakes in the `beforeEach` so disabling this specific case will probably just cause the next test to start flaking.

**Comment by florianduros** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6639269932/job/18037293150

**Comment by kerryarchibald** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6641589338/job/18044477493

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6642883792/job/18048682619#step:8:957

**Comment by richvdh** [comment]
Wonder why this suddenly started failing yesterday. It seems suspicious that https://github.com/matrix-org/matrix-react-sdk/pull/11795 landed yesterday, but given that the test disabled in that PR happens *after* this one, it is difficult to see why they would be related.
