### ISSUE TITLE
Make the feedback link to create a new GitHub issue configurable

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#26443]
#### What would you like to do?
For FOSDEM, we want to make sure that any issues filed by users of chat.fosdem.org are labelled correctly

#### Why would you like to do it?
We modify the app downstream and we want to make sure that we pick up any conference related issues immediately

#### How would you like to achieve it?
We want to use a custom template for new issues with the appropriate labels. In other words, we want the link to point to https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Defect,Z-FOSDEM&template=bug-web.yml&webapp-url=chat.fosdem.org instead of https://github.com/vector-im/element-web/issues/new/choose

### Have you considered any alternatives?

We patched this downstream last year

### Additional context

In an ideal world, that link would be created automagically for the base app anyway to include the URL, app version, browser details, etc so the user can file a new bug without having to spend time copy/pasting those details into the defect template.

![Screenshot from 2023-10-25 10-36-32](https://github.com/vector-im/element-web/assets/51663/f8b50cb3-7830-454b-b94f-96cae088930a)

**Comment by t3chguy** [comment]
Already is, just missing documentation - https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/SdkConfig.ts#L60-L64

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/pull/26446 adds this to docs
