### ISSUE TITLE
Element Web backed by Element R won't decrypt all messages.

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-web#26448]
### Steps to reproduce

1. Where are you starting? What can you see?
After switching to ER backed EW, I cannot see all of my encrypted messages.

#### What did you expect?

To be able to read all of my encrypted messages.

#### What happened instead?

A handful of UTDs preventing me from reading all messages.

I then did a restore from key backup but at 120k keys, while this fixed the reading messages bit, it made Element Web unusable from a performance standpoint. Upon rebooting my computer and trying to re-log in, I killed Element Web after 15 minutes of watching the icon spin. I then deleted the database and restarted the process, preferring to live with the UTDs and a performant Element Web versus all my messages and no performance.

### Operating system

Fedora 38

### Browser information

Vivaldi 5.1.2567.73 (Stable channel) stable (64-bit) ; Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36

### URL for webapp

develop.element.io

### Application version

Element version: 16ec8edd5867-react-5e8d2748e069-js-73a87652fe98 Olm version: <not-enabled>

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by karlabbott** [comment]
On a subsequent restart, keys are now starting to flow in....

**Comment by richvdh** [comment]
There seem to be a couple of separate issues here:

> A handful of UTDs preventing me from reading all messages.

It's unclear at this point whether you have verified your session (so UTDs would be expected), or not (indicating a problem with key backup; in which case, see https://github.com/vector-im/element-web/issues/26312).

> I then did a restore from key backup but at 120k keys, while this fixed the reading messages bit, it made Element Web unusable from a performance standpoint.

This is sad. Possibly related: https://github.com/vector-im/element-web/issues/26488, https://github.com/vector-im/element-web/issues/26470. Unfortunately I don't think we have rageshakes of this bit (the rageshakes only go back as far as 2023-10-25T15:10:50.134Z, which seems to start with the new login.)

I don't think there's anything actionable here that isn't already tracked.
