### ISSUE TITLE
Add a config option to add a custom text on the login page

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#26442]
#### What would you like to do?
We want to show a custom message to our users to help them log into chat.fosdem.org

#### Why would you like to do it?
To make sure that everyone can log in successfully and without problems

#### How would you like to achieve it?
Have a config option somewhere to specify an optional and additional text for the login page

### Have you considered any alternatives?

We currently hard code it into the UI with a downstream patch.

### Additional context

We need to tell users who created accounts for FOSDEM 2021 to change their homeserver as we switched the registration HS for attendees after the first year so the default when they go to login is wrong for them.

We also needed to have the text on the T&S page, if I remember right, so that the UI didn't jump around

**Comment by t3chguy** [comment]
Why not use a custom welcome page for this? https://web-docs.element.dev/Element%20Web/config.html#branding-and-embedded_pages

**Comment by daniellekirkwood** [comment]
Agreed, I believe we already have this through the ESS/EMS capabilities

**Comment by t3chguy** [comment]
@daniellekirkwood anything else to do here in that case?

**Comment by t3chguy** [comment]
Closing due to no response
