### ISSUE TITLE
"Forgot password?" not translated

### ISSUE THREAD

**Issue by estellecomment** [vector-im/element-web#26456]
### Steps to reproduce

1. Where are you starting? What can you see?
Go to login page, in a non-english language. The "Forgot password?" link is not translated, it's in english.

<img width="712" alt="image" src="https://github.com/vector-im/element-web/assets/911434/6631adfe-0a26-4bf9-8fe5-2b674f3f7b54">

#### What did you expect?
Link text in French

#### What happened instead?
Link text in English

### URL for webapp

app.element.io

### Application version

1.11.47 

### Will you send logs?

No

**Comment by t3chguy** [comment]
Translations are community maintained - see the docs https://web-docs.element.dev/Element%20Web/translating.html - the translation is missing 

![image](https://github.com/vector-im/element-web/assets/2403652/0d91aad0-2ed3-4b6d-b1dc-211b0505361e)
