### ISSUE TITLE
Element R: Slow log in time

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-web#26454]
### Steps to reproduce

I log out of Element Web and log back in again to take advantage of Element R

#### What did you expect?
That I would be able to log in after a few minutes
#### What happened instead?
Log in took two attempts. First attempt I gave up, on the second attempt it took multiple hours

### Operating system

macOS

### Browser information

Version 117.0.5938.149 (Official Build) (x86_64)

### URL for webapp

develop.element.io

### Application version

Element version: bce820729393-react-1881fb1ee4da-js-07a9eb3c96bb Crypto version: Rust SDK 0.6.0, Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by robintown** [comment]
https://github.com/vector-im/element-web/issues/26418 is a possible root cause

**Comment by BillCarsonFr** [comment]
Closed #see https://github.com/vector-im/element-web/issues/26418
