### ISSUE TITLE
"Sign in instead" is not a link in non-english version

### ISSUE THREAD

**Issue by estellecomment** [vector-im/element-web#26457]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?

Go to "Register" page, in a non-english language. At the bottom of the page, try clicking "Sign in instead" (e.g. "Se connecter à la place")

<img width="711" alt="image" src="https://github.com/vector-im/element-web/assets/911434/697d97dd-8cf3-4b27-abee-c52373bd83c1">

#### What did you expect?
Clicking link goes to sign in 

#### What happened instead?
it's not a link, I can't click it

### URL for webapp

app.element.io

### Application version

1.11.47

### Will you send logs?

No

**Comment by t3chguy** [comment]
Same as https://github.com/vector-im/element-web/issues/26456 - we don't maintain the translations - see the docs - https://web-docs.element.dev/Element%20Web/translating.html

![image](https://github.com/vector-im/element-web/assets/2403652/c8e31542-fb1d-4807-bbff-4efddb66045b)
