### ISSUE TITLE
Invalid server name

### ISSUE THREAD

**Issue by Beiri22** [vector-im/element-web#26463]
### Steps to reproduce

I run a server under matrix.<mydomain>.de
When having no .well-known delegation, it works ok
When having the .well-known delegation on <mydomain>.de, it works
But when having the .well-known delegation on matrix.<mydomain>.de, element web shows invalid homeserver url when trying to login into my account while choosing the home server. 

For years I used no delegation; no problem; but for the sliding sync proxy I need it. I first put the delegation into the mail domain, which works; but it's not consistent as my homeserver officially is named matrix.<mydomain>.de 

So today I tried putting the well-known files under matrix.<mydomain>.de

Element Android and Element X Android do not have any problem.
Element web does not work; and element desktop does not work

#### What did you expect?
Homeserver is usable.

#### What happened instead?
Homeserver is rejected as invalid homeserver url.

### Will you send logs?

How?

**Comment by t3chguy** [comment]
Without knowing the domain to reproduce or the messages on the console there's nothing to go on

**Comment by Beiri22** [comment]
Ok. I just reinstalled the setting.
the domain is matrix.beiri22.de
now the .well-known is served from both beiri22.de and matrix.beiri22.de

The error occurs just when selecting the homeserver "matrix.beiri22.de" for login, before entering the username and pass.

**Comment by Beiri22** [comment]
Is it because the wellknown-entry states the homeserver address with "https://"?

**Comment by Beiri22** [comment]
Seems like the CORS-Header was added twice, which failed at loading the /versions
