### ISSUE TITLE
Element R became unresponsive

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26470]
When I was using Element from develop.element.io, with a fresh login, meaning it used Rust Crypto, it worked fine for a while, but after a few hours it froze and my browser told me my tab was using too much CPU. I left it for a few minutes, but nothing changed, so I refreshed the tab and rageshook.

Rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/23050

**Comment by richvdh** [comment]
Unfortunately the rageshake is uninformative here. It looks normal up until 13:30:35, at which point, everything stops.

**Comment by richvdh** [comment]
I don't think there's much we can do with this, sadly. Closing, pending repeated reports.
