### ISSUE TITLE
Upgrade your app error

### ISSUE THREAD

**Issue by JustMe0815** [vector-im/element-web#26492]
### Steps to reproduce

web not recognizing installed element app on android.

Steps
-from mobile, go to app.element.io
-install app
-go back to app.element.io
-click on configure

#### What did you expect?
element app opening with correct url.
#### What happened instead?
Error: upgrade to continue.
app is not opening.

### Operating system

Android 

### URL for webapp

app.element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Sounds like the Android app doesn't register the correct handler

**Comment by t3chguy** [comment]
I'm unable to transfer the issue, I suggest opening an issue on https://github.com/vector-im/element-android or https://github.com/vector-im/element-x-android respectively
