### ISSUE TITLE
Composer completely missing

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#26505]
### Steps to reproduce

1. Open app.element.io
2. Go to any room
3. Composer is missing / doesn't render

#### What did you expect?
To see the composer
#### What happened instead?
Not rendered

### Operating system

Linux

### Browser information

Firefox 118.0.2

### URL for webapp

app.element.io

### Application version

Element version: 1.11.47 Olm version: 3.2.14

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
@benparsons a screenshot would be helpful, also please try a fresh browser profile with no extensions, I've seen extensions cause this due to how they draw themselves.

**Comment by benparsons** [comment]
When I resized the window to take a screenshot the composer reappeared. Weird because I already refreshed...
