### ISSUE TITLE
Cannot send messages from electron app to any room

### ISSUE THREAD

**Issue by simon-pau** [vector-im/element-web#26506]
### Steps to reproduce

I want to sent a message to any room. It appears the notification:
`Some of your messages have not been sent`
When I click `Resent`, the same dialog appears again. Also joining and leaving channels does not work.
Receiving messages works flawless.

On one private channel, I have a verification request, where I cannot click decline. When I click verify, it loads forever, probably this is related.

### Outcome

I can sent a message. I can't.

### Operating system

Arch Linux

### Application version

Element version: 1.11.45 Olm version: 3.2.14

### How did you install the app?

pacman

### Homeserver

nitro.chat

### Will you send logs?

Yes

**Comment by simon-pau** [comment]
I uploaded logs.

**Comment by weeman1337** [comment]
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. I was testing with the Desktop package from the official deb repo. Arch / pacman is not a supported platform. You should reach out to the maintainers of the arch package.
