### ISSUE TITLE
Account created with OIDC cannot use secure backup

### ISSUE THREAD

**Issue by tgr** [vector-im/element-web#26502]
### Steps to reproduce

When you create an account using OIDC (I used [wikimedia.onmatrix.chat](https://wikimedia.onmatrix.chat/)) secure backup (and thus the ability to use encrypted channels) still requires a password and thus is broken.

When Element prompts me to set up secure backup and I accept, it shows the "Save your security key" dialog:
![Képernyőkép 2023-11-04 115248](https://github.com/vector-im/element-web/assets/145412/0414ca9c-607a-4ae0-9e20-226f897f5cdd)
After clicking Copy and Continue, I am asked for my password:
![Képernyőkép 2023-11-04 115427](https://github.com/vector-im/element-web/assets/145412/49b7e602-8194-4523-86fd-e9e475fced47)
Since registering via OIDC doesn't involve a password, I of course cannot finish setting up the keys.

When I'm trying to set a password, I'm presented with a form that asks for the old password. When I leave it empty, that causes an error: ![Képernyőkép 2023-11-04 114511](https://github.com/vector-im/element-web/assets/145412/bddabb85-6ad8-47a9-a744-c8ca596d5905)
When I enter something into the current password field, that will of course cause an invalid password error.

When I am trying to cross-verify my Element Android app, it also gets stuck; filed that as https://github.com/vector-im/element-android/issues/8673 Element X doesn't seem to support OIDC at all.

### Operating system

Ubuntu 22.04

### Browser information

Chrome 118.0.5993.118

### URL for webapp

https://element.wikimedia.onmatrix.chat/

### Application version

Element version: 1.11.47 Olm version: 3.2.14

### Homeserver

https://matrix.wikimedia.onmatrix.chat

### Will you send logs?

No

**Comment by t3chguy** [comment]
This seems like an issue on the server-side, the server is asking for the incorrect flow (password) via UIA https://spec.matrix.org/v1.8/client-server-api/#user-interactive-authentication-api

**Comment by tgr** [comment]
@t3chguy wouldn't the part about not being able to change (set) the password still be an Element bug?

**Comment by t3chguy** [comment]
@tgr in an OIDC world you can only set a password via the OIDC provider. The server should be signalling this via https://spec.matrix.org/v1.8/client-server-api/#mchange_password-capability
