### ISSUE TITLE
Can't dismiss invite to room that probably no longer exists

### ISSUE THREAD

**Issue by lnicola** [vector-im/element-web#26514]
### Steps to reproduce

1. Receive an invite to a test room
2. Don't accept it fast enough
3. Make the others leave (or upgrade?) the test room so it's now empty
4. Try to dismiss the invite

#### What did you expect?

Invite goes away.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/308347/0306a6bb-1909-4897-b7db-aa3e1f0b5015)

"Reject" goes to the onboarding screen, invite remains active and **RED**.

### Operating system

Linux

### Browser information

Firefox

### URL for webapp

1.11.47

### Homeserver

Conduit 0.7.0-alpha

### Will you send logs?

Yes

**Comment by lnicola** [comment]
Looks like `/leave` works, but then my server says:

```
WARN conduit::api::client_server::membership: Failed to leave [MY MXID] remotely: M_BAD_STATE: User is not invited.
```

So it might actually be Conduit. Or even Synapse (the room was on a Synapse server).

**Comment by t3chguy** [comment]
Definitely a server issue. The server should be local-rejecting the room invite and removing it from your client via `/sync`.

**Comment by t3chguy** [comment]
> Why exactly didn't the specification allow for redaction of invitation events by both the recipient and sender? I'm not sure if this would work but this seems like a possible solution, although I'm guessing the recipienr has to be a room member to reject the invitation.

The spec does allow for this. The issue happens when the room no longer exists (as per the title of this issue) - then there is no invitation to reject and your server wouldn't have been notified of the room winking out of existence if it wasn't part of the room in the first place.  Either way a closed issue on the client side is not the place to discuss.
