### ISSUE TITLE
Disable room key requests

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26524]
`m.room_key_request` messages are a huge source of to-device messages, and the value they bring is questionable. They also make it harder to track down and fix underlying bugs in the crypto implementation, by making symptoms disappear.

Apparently the mobile Element-X clients do not send room key requests at all, and the world keeps turning.

@ara4n says:

> (i really really think we should just disable them, in order to avoid clouding bugs like this)

Disabling them would fix various issues like https://github.com/vector-im/element-web/issues/26313, https://github.com/vector-im/element-web/issues/19488, https://github.com/matrix-org/matrix-spec/issues/1659.

Given we have key backup as a more reliable mechanism for gossiping keys between devices, why exactly do we still have room_key_request?

(This is proposed for Element-R, though presumably if it's good enough for ER we could do the same on legacy crypto?)

**Comment by dkasak** [comment]
Presumably one edge case is people who deliberately turn off their key backup. It should also be noted that key forwards (that is, trusted key forwards, the only kind remaining today) are authenticated whereas keys retrieved from today's broken backup implementation are not.

**Comment by pmaier1** [comment]
Thanks! As we do not want to maintain focus and improve performance we drop this for now. We don't want to cover up root causes of UTDs with gossiping. We for now rely on backup if the user wants to have message history on new devices. We might want to re-evaluate this decision later but this is it for now.

**Comment by mikebeaton** [comment]
Hi - This was also under discussion here: https://github.com/element-hq/element-web/issues/28349

I just wanted to note that (for me at least) a particularly attractive feature of Element was its ability to retrieve message history from another device, without requiring any backups. I preferred to use it that way, and always did.

Is there any chance of this feature (which I assume was added intentionally originally, and which I and at least some other users - see comments above and in the other issue - found useful) being restored at any point?
