### ISSUE TITLE
Only a couple rooms open when opening Element Web 1.11.48; 1.11.47 works as expected

### ISSUE THREAD

**Issue by eras** [vector-im/element-web#26520]
### Steps to reproduce

1. Restore session by opening https://tsat.mf.variaattori.fi/element-v1.11.48
2. Wait a while

#### What did you expect?

I expected to have access to all my previous rooms and communication, as with 1.11.47.

#### What happened instead?

Only two rooms opened; one of the rooms seems to be the most recently one accessed, the other one is something else.

### Operating system

Debian Bookworm

### Browser information

Firefox 119 flatpak x86_64

### URL for webapp

https://tsat.mf.variaattori.fi/element-v1.11.48

### Application version

Element version: 1.11.48 Crypto version: Olm 3.2.15

### Homeserver

https://matrix.org/

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Reading the stacktrace, `user` is ending up as `undefined` - regressed by https://github.com/matrix-org/matrix-js-sdk/pull/3796

**Comment by Johennes** [comment]
This is a release blocker as per https://handbook.element.io/books/web-app-team-wat/page/release-blockers and ergo might mandate a hot fix. @MidhunSureshR could I ask you to investigate this issue tomorrow?

**Comment by jaywink** [comment]
I've linked 3 rageshakes to this issue that may be related?

> 2023-11-09T14:37:46.727Z E Error starting matrixclient store - falling back to memory store Query failed: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.

**Comment by MidhunSureshR** [comment]
This is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3867, will close this issue once merged!

**Comment by t3chguy** [comment]
We are planning a hotfix release for this

**Comment by WillPittenger** [comment]
Will I need to manually install the update or would Element detect the update even if it's in the described state?

**Comment by t3chguy** [comment]
@WillPittenger depends on how you installed it. Closed issues are also not a forum. Hotfix planned for Monday.
