### ISSUE TITLE
UX : when a tab is locked, the language used is scary

### ISSUE THREAD

**Issue by estellecomment** [vector-im/element-web#26537]
### Steps to reproduce

1. Where are you starting? What can you see?
Open two element-web tabs, switch to the second, which locks the first. Go to the first tab, it is now locked. (as expected, this is fine)

#### What did you expect?
A message that is friendly (since nothing bad has happened) and explains what to do next.

Something like this : 

<img width="868" alt="Screen Shot 2023-11-09 at 3 47 12 PM" src="https://github.com/vector-im/element-web/assets/911434/dc70ebb5-fd06-4125-ba1a-1d4140b69669">

#### What happened instead?

A message that is scary ("Error", and no details about what the error is, so lack of info stresses me out) and does not explain what to do about it. So I am scared that something is wrong, when actually things are functioning as expected.

<img width="567" alt="Screen Shot 2023-11-09 at 3 54 27 PM" src="https://github.com/vector-im/element-web/assets/911434/4f71d313-2912-458a-8fcd-9baa14ed3660">

### URL for webapp

app.element.io

### Application version

Element version: 1.11.48 Crypto version: Olm 3.2.15

### Homeserver

matix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Thanks for raising the issue. I've asked design for better texts.

**Comment by koko1928** [comment]
I've been in a similar situation and agree.

**Comment by gaelledel** [comment]
Thank you @estellecomment 
Slight revision from your proposal:
Title: Element is connected in another tab
Body: Switch to the other tab to connect to Element. This tab can now be closed.

@weeman1337 Good to go
