### ISSUE TITLE
[Disabled] Flaky Cypress test `Read receipts > editing messages > A room with an edit is still read after restart`

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26544]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6818933410/job/18545444679

https://cloud.cypress.io/projects/ppvnzg/runs/19935/test-results/275e4ab8-20a7-4a4d-a223-b7ba8e938bae?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D

**Comment by andybalaam** [comment]
Another instance: https://github.com/matrix-org/matrix-js-sdk/actions/runs/6827923412/job/18571014642

Now disabled.

**Comment by florianduros** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/12007
