### ISSUE TITLE
`#jellyfin-troubleshooting:matrix.org is not accessible at this time.`

### ISSUE THREAD

**Issue by HammyHavoc** [vector-im/element-web#26541]
### Steps to reproduce

1. Try to access #jellyfin-troubleshooting:matrix.org

#### What did you expect?
To connect to the room.

#### What happened instead?
`Try again later, or ask a room or space admin to check if you have access.

M_UNKNOWN was returned while trying to access the room or space. If you think you're seeing this message in error, please [submit a bug report](https://github.com/vector-im/element-web/issues/new/choose).`

### Operating system

Windows

### Will you send logs?

No

**Comment by t3chguy** [comment]
This would be an issue you need to seek help with through your Matrix server administrator.

**Comment by HammyHavoc** [comment]
I am the administrator, and the client said to file the bug report on the repository. If that's not the desired outcome of the message in the client, perhaps it needs changing?

**Comment by t3chguy** [comment]
Whether or not it is "in error" depends on the error the homeserver is experiencing. On a properly set up and federating server that may be the case. You chose to exclude vital information like server & logs so we have no information to determine that.
