### ISSUE TITLE
Can't react from search

### ISSUE THREAD

**Issue by fabianunterstell** [vector-im/element-web#26557]
### Steps to reproduce

1. Use the search to find a message.
2. Use react on the message in the search view to react with an emoji to the message.
3. Use react on the message in the search view to react with the same emoji to the message again.

#### What did you expect?

After 2. the message should show the emoji as a reaction.
After 3. the message should have the emoji reaction removed again. 

#### What happened instead?
After 2. the message does not show the emoji as reaction. But if you then leave the search view the message does show the reaction correctly.

After 3. the no reaction shows or gets removed and you receive the following error:
```
Some of your messages have not been sent
You can select all or individual messages to retry or delete
Delete all | Retry all
```

This seems to be related to: https://github.com/vector-im/element-web/issues/26508

### Operating system

Windows 10

### Application version

Element Nightly version: 0.0.1-nightly.2023111201 Crypto version: Olm 3.2.15

### How did you install the app?

From element website

### Homeserver

Synapse 1.93

### Will you send logs?

No

**Comment by fabianunterstell** [comment]
On further investigation: The search view does not show react emojis at all. So 2. might be intended behaviour. 

But 3. leading to the messages can't be sent error is still an issue.

**Comment by HarHarLinks** [comment]
I can repro.

> After 2. the message should show the emoji as a reaction.

That appears to be the regular behavior, even though I'd argue reactions should be shown during, especially when you're supposed to be able to send them.

**Comment by weeman1337** [comment]
Related to https://github.com/vector-im/element-web/issues/26508
