### ISSUE TITLE
Screen Sharing only Working Once

### ISSUE THREAD

**Issue by stephen-lockett** [vector-im/element-web#26573]
### Steps to reproduce

1. Share your screen via the resp. button and share popup.
2. Finish sharing your screen.
3. Try to share your screen once again by clicking on the resp. button.

#### What did you expect?
Screen sharing popup appears.
#### What happened instead?
Nothing happens: No popup appears.
####Workarounds
1. Restart application. Sharing works again for one pass.
2. The issue does not appear when using SchildiChat instead.

### Operating system

Manjaro Linux

### Application version

Element version: 1.11.45, Olm version: 3.2.14

### How did you install the app?

via pamac (https://software.manjaro.org/package/element-desktop)

### Homeserver

Synapse 1.92.1-1

### Will you send logs?

No

**Comment by t3chguy** [comment]
The pacman package isn't supported by us, please report to your maintainer
