### ISSUE TITLE
Restarting app brings up many notifications

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-web#26584]
### Steps to reproduce

1. Read all rooms and bring notifications down to zero
2. Close app
3. Open app

#### What did you expect?
Zero notifications

#### What happened instead?
Over 50  unread notifications

![image](https://github.com/vector-im/element-web/assets/640121/b21e2e2f-9ebb-4238-981c-14b0fb6a35a5)

### Operating system

Windows 11

### Application version

Version von Element: 1.11.49 Crypto version: Olm 3.2.15

### How did you install the app?

Element

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by kongo09** [comment]
The notifications were limited to only a few rooms, e.g. `#element-x-product-design:matrix.org`

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/25479
