### ISSUE TITLE
Thread panel causes old confetti effects to play.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#26592]
### Steps to reproduce

1. View a room with the thread panel open
2. As the thread panel populates, any confetti emoji present in old scrollback triggers the effect

#### What did you expect?

Effects only on live new messages

#### What happened instead?

Flakey spurious confetti coming out of bugs in the threads implementation.

### Application version

nightly

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/24811
