### ISSUE TITLE
Display an info message to all users easily

### ISSUE THREAD

**Issue by estellecomment** [vector-im/element-web#26600]
#### What would you like to do?

Spread important news to all users. In our current case, a planned service interruption. It could also be for less important news (community events, "did you know" tips, "answer this user study survey", etc)

#### Why would you like to do it?

We want everyone to know.

#### How would you like to achieve it?

Adding it to the config.json would be an easy way, like user_notice. (user_notice is not quite what we want, see below)
This means the webapp needs to poll for a change of config and display the message.

We could consider also a bot system which opens a DM with each user. (inviting all users to a single room would probably not be good performance-wise for us, though I'm not the expert on this)

Or something else !

### Have you considered any alternatives?

Currently we have user_notice in config.json, which does the job but only partially : when a user_notice is pushed to prod, it will only be displayed to the user when the page is reloaded or reopened. Because before that, the new config is not seen by the client.
Some users will just leave the tab open and never reload. So they will never know about the service interruption in our case.

So we need to bump the version, in order for the updateToast to be displayed, which will cause the page reload and the user_notice to be displayed. (and still, if users refuse the new version, they won't see the user_notice.)

Having to bump the version is a lot of overhead, and not very flexible : beta users have a different version than normal users, so we have to change everyone's version, so the version numbers get out of order or weird, ... messy. Also, the info may not be related to the code for the version at all (it's accidental that the service interruption happens during version X)

Conclusion : user_notice is a good way to display info about a new version, but not a very good way to display an info to all users.

**Comment by t3chguy** [comment]
Sounds like a job for https://matrix-org.github.io/synapse/latest/server_notices.html

**Comment by estellecomment** [comment]
Thanks for the info !
