### ISSUE TITLE
Please place config.json in the Debian package somewhere under /etc

### ISSUE THREAD

**Issue by paulvt** [vector-im/element-web#26613]
### Steps to reproduce

1. Install the Debian package as described on https://element.io/download

#### What did you expect?

I'd expect the configuration file `config.json` to be under `/etc/element-web` or `/etc/element-io` (or something).
It should be there and maybe just linked to `/usr/share/element-web/config.json`.
(This is how I had it deployed before the Debian package came into being. Thanks for that!)

#### What happened instead?

The configuration is under `/usr/share/element-web/config.json` and thus not manageable by configuration management tools like etckeeper.

### Operating system

Debian 12

### Will you send logs?

No

**Comment by paulvt** [comment]
This would also have the advantage that `config.sample.json` could be shipped so I can find out what's new in the config. (Although that should also preferably with the README be under `/usr/share/doc/element-web`.)

**Comment by t3chguy** [comment]
`/etc/element-web/config.json` and `/usr/share/doc/element-web` are great suggestions - thanks

> This would also have the advantage that config.sample.json could be shipped so I can find out what's new in the config.

`/usr/share/element-web/config.json` is already set up as a conffile, so whenever the `config.sample.json` changes you'll be shown the diff as part of an apt upgrade

**Comment by paulvt** [comment]
Yes, right, I used to go for a vimdiff before but I guess dpkg will handle that now. I saw that it was already marked as a conffile indeed.

**Comment by paulvt** [comment]
As a side note:
It might be nice to have a "Running from Debian/Ubuntu" in the README and install this to the docs.
Or have and install a separate README.Debian to help the user with: I installed it, now what?
But that's a different issue than this one 😉

**Comment by t3chguy** [comment]
Yeah this is still very early days, it only shipped mere hours ago :)
