### ISSUE TITLE
volume slider is fucking with me

### ISSUE THREAD

**Issue by AdamRGrey** [vector-im/element-web#26611]
### Steps to reproduce

1. in a room where someone has posted a video (with audio)
2. attempt to turn the volume down from the automatic setting of Absolute Maximum Please Rupture My And My Neighbors' Eardums 
2a. hover over the audio icon to enter Volume Fixing Mode :tm: 
2b. move the mouse to the slider to bring the volume to normal levels

#### expected

proceed to be able to drag the volume slider down to where it is for everything else

#### observed instead

as soon as you leave the mute button, you are ejected from Volume Fixing Mode :tm: and the volume slider collapses back in

### Operating system

debian 11

### Browser information

whatever chromium is embedded in hamsket

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Hamsket is not a supported environment - https://github.com/vector-im/element-web#supported-environments

For next time tone down your language or risk being banned from this github organisation.

**Comment by AdamRGrey** [comment]
alright I've toned down the language
