### ISSUE TITLE
"Something went wrong!" when clicking "Room info"

### ISSUE THREAD

**Issue by eiksta** [vector-im/element-web#26625]
### Steps to reproduce

<img width="712" alt="Screenshot-roominfo" src="https://github.com/vector-im/element-web/assets/141136159/d6d903eb-bc9d-4af1-b73a-c09b0cc9c202">
<img width="871" alt="Screenshot-roominfo2" src="https://github.com/vector-im/element-web/assets/141136159/cd780d8e-9aa1-44bf-89b7-7059ba39f90d">

#### What did you expect?
Some info about the room

#### What happened instead?
Error happened

### Operating system

windows

### Browser information

google chrome Versjon 119.0.6045.160  (64 bit)

### URL for webapp

Element web. 1.11.40

### Application version

Olm version: 3.2.14

### Will you send logs?

No

**Comment by t3chguy** [comment]
> URL for webapp
Element web. 1.11.40

This version is 85 days old, please update and open a new issue if you are still encountering this issue.
