### ISSUE TITLE
Holding `ctrl` shows a popup with an avatar

### ISSUE THREAD

**Issue by krnowak** [vector-im/element-web#26631]
### Steps to reproduce

1. Using Microsoft Edge for Business 121.0.2220.3 Ubuntu 22.04.3 LTS.
2. I'm in the chatroom (https://app.element.io/#/room/#flatcar:matrix.org in this case).
3. Message input field is focused.
4. Hold `ctrl`.

#### What did you expect?

Nothing, holding `ctrl` shouldn't trigger anything by itself.

#### What happened instead?

A popup with my avatar showed up, with an thumbs-up, thumbs-down buttons on the bottom right of the popup.

### Operating system

Ubuntu 22.04.3 LTS

### Browser information

Microsoft Edge for Business 121.0.2220.3

### URL for webapp

https://app.element.io/#/room/#flatcar:matrix.org

### Application version

Element version: 1.11.50 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Can you share a screenshot of that?
Also keep in mind Edge for Business is not a supported environment https://github.com/vector-im/element-web#supported-environments

**Comment by krnowak** [comment]
![image](https://github.com/vector-im/element-web/assets/96081/e4f7f8b3-53c4-4bc7-a6a6-fa3e129111fe)

**Comment by t3chguy** [comment]
That isn't anything in Element, Edge for Business is doing something strange. Even those thumb up thumb down icons don't exist in Element.

**Comment by krnowak** [comment]
Ha, interesting. Thanks for help.
