### ISSUE TITLE
System emoji are no longer being used.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-web#26660]
### Steps to reproduce

1. Sign in to develop.element.io
2. Go to Settings | Appearance | Show Advanced
3. Enable the Use a System Font setting and type in `Inter`.
4. Return to a room and send an emoji.

#### What did you expect?
To see an Apple emoji 😃

#### What happened instead?
I saw a Twemoji instead ☹️

### Operating system

macOS Sonoma

### Browser information

Safari 17.1 (19616.2.9.11.7)

### URL for webapp

develop.element.io

### Application version

Element version: 4c182928e101-react-d47f856ba086-js-8ef2ca681c59 Crypto version: Rust SDK 0.6.0 (9c4fe43), Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Untick the box which says "Use bundled emoji font"

![image](https://github.com/vector-im/element-web/assets/2403652/bd8e2474-895a-4f4b-8950-97e455e25402)

**Comment by pixlwave** [comment]
🤦‍♂️ can't believe I missed that. Sorry for the noise.
