### ISSUE TITLE
Editing message containing quotes is causing the quotes to be duplicated within the message

### ISSUE THREAD

**Issue by KeenMaron** [vector-im/element-web#26675]
Hi,

If you quote somebody and then edit your message which includes the quote, it results in the quote being duplicated or even tripled with each subsequent change to the message. The bug appears only on mobile version and is visible on all clients.

This is really a bad bug. I hope it's resolved fast. :/

#### What did you expect?
The quoted message should not be duplicated after editing own message which contains the quote.
#### What happened instead?
Every edit results in duplicating the quote within the message.

### Operating system

on android 

### Application version

1.11.50

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by KeenMaron** [comment]
> > Will you send logs?
> > Yes
> 
> Not seeing any logs from you

i will send logs if needed via direct message

**Comment by t3chguy** [comment]
<img width="871" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/33646a0b-b426-4810-99f3-7bc23e7ec3a9">

**Comment by KeenMaron** [comment]
> <img alt="image" width="871" src="https://private-user-images.githubusercontent.com/2403652/286629275-33646a0b-b426-4810-99f3-7bc23e7ec3a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjg2ODcsIm5iZiI6MTcwMTI2ODM4NywicGF0aCI6Ii8yNDAzNjUyLzI4NjYyOTI3NS0zMzY0NmEwYi1iNDI2LTQ4MTAtOTlmMy03YmMyM2U3ZWMzYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTQzMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQyYzM4NzRmODYyOTM3MjAyN2M1ZWVhM2U1NmY3YmViMmE2ZTc0YjAyOTIxZDg3MjQyNWEyMzIxODM2NzIwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0TxVyk4Xj868CzftCGMMcMx_fpzLQDkWvD1XbYxjgJ8">

Just sent logs via android app

**Comment by t3chguy** [comment]
This repo only concerns issues with Element Web & Desktop - you want https://github.com/vector-im/element-android or https://github.com/vector-im/element-x-android/
