### ISSUE TITLE
Welcome page on fresh account has a floating camera icon

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#26670]
### Steps to reproduce

1. [Unsure if relevant] Log in/create an account with the legacy Google OIDC
2. Note avatar in top left is default, but avatar in the middle of the page is just a camera icon.

#### What did you expect?

A default avatar or something circular to indicate it's an avatar upload and not just a broken icon.

#### What happened instead?

![image](https://github.com/vector-im/element-web/assets/1190097/1df47082-829f-4b10-8eaa-21b594ba812c)

### Operating system

Windows 11

### Browser information

Chrome

### URL for webapp

app.element.io

### Application version

Element version: 1.11.50 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Regression 

![image](https://github.com/vector-im/element-web/assets/2403652/1efc2049-f383-45c6-9909-fd5ae9786a68)
