### ISSUE TITLE
Restore Bulgarian & Turkish language support removed by a commit on Oct 17

### ISSUE THREAD

**Issue by krassle** [vector-im/element-web#26702]
### Steps to reproduce

Bring back Bulgarian and Turkish translation *accidentally?* removed by this commit [22e35c3](https://github.com/vector-im/element-web/commit/22e35c385deefd4bfcac6e59d13da66121a9e50c).

#### What did you expect?
No response
#### What happened instead?
No response

### Operating system

No response

### Browser information

No response

### URL for webapp

No response

### Application version

No response

### Homeserver

No response

### Will you send logs?

No

**Comment by krassle** [comment]
@florianduros  Thanks for the explanation!

Regarding the 80% coverage rule: 

There are multiple translations(e.g. Persian, Hebrew, Lithuanian, Brazilian Portuguese), that _by far_ do not meet this requirement, but are still kept in. Why exactly _those two_ did not make the cut? 

They were at _this_ stage for many years now... And yes, it's not ideal, but to suddenly _disable_ them and with it _cut off_ over 100 million population (equals France & Poland together!), but then to _not even mention_ this in the commit is a bit rude, imo.

It is a regression and should be treated as such.

Thanks a lot!

**Comment by salif** [comment]
@krassle, @florianduros, @t3chguy. Hello, I contributed Bulgarian translations. It's now 60%, please restore Bulgarian language and review my translations at [localazy.com/p/element-web](https://localazy.com/p/element-web)

**Comment by t3chguy** [comment]
![image](https://github.com/element-hq/element-web/assets/2403652/6e029d42-5874-45ef-9f91-00376b43b7d1)

It is only at 48% approved, we have yet to formalise a minimum for enablement. @langleyd was looking into this.

**Comment by salif** [comment]
@t3chguy, @langleyd. Please approve my translations. 80% coverage is too much. I can't reach 80% by myself doing only high quality translations. I also translated 2/3 (66%) of Element X at localazy, I hope it will be approved as well.
