### ISSUE TITLE
Remote emoji not showing correctly in reactions

### ISSUE THREAD

**Issue by filipesmedeiros** [vector-im/element-web#26704]
### Steps to reproduce

1. Open a channel with a person from another server (or another account you own)
2. Send a message there
3. Have the other account react with a custom emoji from their server to your message

#### What did you expect?

Emoji reactions to be correctly federated, like they are in messages.

#### What happened instead?
This:

<img width="217" alt="Screenshot 2023-12-05 at 19 06 39" src="https://github.com/vector-im/element-web/assets/26208850/d514e5a6-ccca-4695-9419-88d9d4d9d7b2">

It shows as the URL, instead of getting the image.

### Operating system

MacOS

### Browser information

Chromium

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by filipesmedeiros** [comment]
I guess this is a duplicate of https://github.com/vector-im/element-web/issues/19559 but it seems to make sense to implement. The Matrix React SDK seems to kinda be ready for it?         if (this.props.customReactionImagesEnabled && content.startsWith("mxc://")) {

**Comment by t3chguy** [comment]
Its in labs until the spec stabilises support for it.

<img width="650" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/b49af93d-8cd6-4de5-8143-e3736227c05c">
