### ISSUE TITLE
Room list Reaction preview shown when reacted-to message is redacted

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#26706]
### Steps to reproduce

1. enable room list reaction previews
2. send message
3. react to message
4. redact message

#### What did you expect?
Preview is not shown, because it is not shown in the Timeline either
#### What happened instead?
![image](https://github.com/vector-im/element-web/assets/2803622/267655cc-a2af-4370-a06f-320f73fcc3a2)

### Operating system

arch

### Browser information

firefox 119

### URL for webapp

develop.element.io

### Application version

Element version: b9d616a0b728-react-236ea44cc82c-js-f31e83fd0375 Crypto version: Olm 3.2.15

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/17893

**Comment by HarHarLinks** [comment]
I can see how the underlying technical reason for this defect may be the same as the dupe, but want to point out this issue concerns (emoji) reactions specifically, which I don't see in the other ticket.
