### ISSUE TITLE
changing password should not log out all your devices (and destroy your e2e history)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2671]
which apparently it does as it logs out all your clients

**Comment by richvdh** [comment]
any suggestions for how to fix this welcome

**Comment by ara4n** [comment]
special-case logout caused by password reset not to destroy e2e keys? password reset should not be used to kick out lost/stolen devices - that should be explicitly done by the lost/stolen device API surely...

**Comment by richvdh** [comment]
Those sentences seem to be opposing suggestions?

> special-case logout caused by password reset not to destroy e2e keys? 

For one, that would require a way to tell the difference, and for two, I worry that keeping e2e keys around on logged-out clients would be surprising to the user and a leak waiting to happen.

> password reset should not be used to kick out lost/stolen devices - that should be explicitly done by the lost/stolen device API surely...

Yes, one option would be to not invalidate access tokens on password reset, and instead get users to manage their access tokens via the device API: but that isn't really an e2e thing. (It doesn't seem to be specced, so I guess it's just a synapse thing).

**Comment by ara4n** [comment]
yup, they were two different suggestions.

let's just make password-reset not log out all your devices, and instead direct the user to use the devices UI to decide which devices to remove (warning them there that it will nuke the e2e history on those devices).  And yes, it has nothing to do with with e2e.

In the short term, please can we just *very* loudly warn that it will destroy your e2e history.

**Comment by madduck** [comment]
I see two points here:

1. Resetting the password should not log out users, but probably inject a password prompt into the existing session to prompt for the new password on all devices, which then gets updated.
2. The e2e keys must not depend on the password itself, but on an underlying per-device secret key. On password change, this secret key gets decrypted with the old password and encrypted anew with the new password. e2e won't be affected.

**Comment by madduck** [comment]
Note that this also applies to changing the password!

**Comment by lhunath** [comment]
Does #2286 obsolete this?

**Comment by richvdh** [comment]
Not really. The fix to #2286 would require the user to validate the new devices. In this case it's better not to invalidate the existing devices, to avoid that step.

**Comment by Mikaela** [comment]
I think https://github.com/vector-im/riot-web/issues/2872 (log out other sessions) is related here or people might find this instead of it.

**Comment by CySlider** [comment]
Just happened to me.
Lost all my history and do not see a way to get it back :-( (Is there?)

Was still logged on with two PCs when wanting to install it on my new phone. Forgot the password.
So I set an e-mail (which I still could do without old password? Why not letting me change the password then in the first place directly without asking the old password?) changed my password. And boom - all devices logged out, all history lost. 

Very bad experience.

**Comment by lhunath** [comment]
IMO, without a central place that stores history, it's critical that clients keep backups in such a way that they can be restored later on, once the account is accessible again.  Which is certainly a challenge, because you wouldn't want those logs accessible by anyone else.

**Comment by CySlider** [comment]
I think changing the password and illegitimating current tokens should be separate actions. So that at least still legitimized devices can restore everything again.

**Comment by MurzNN** [comment]
May be Riot can store E2E keys temporary on current device cache to time when we invalidating old devices and create new access_token via new password, and automatically import them when the process is finished?

**Comment by CySlider** [comment]
Anything that makes this less troublesome.

I have now again the problem with my wife's Riot. Unfortunately I had a small password safe issue around that time and my and her riot passwords were lost due to that.

Now she has a new phone and I can not install it on the new phone without loosing all history despite the old phone currently still having access to it... Really odd situation.

I can not even export the history on the old phone to save it. (Sentimental values)

Any idea what I can do? Will exporting the E2E keys before password reset help afterwards? I guess so, but I only have one shot and she will be furious if I loose her history :worry:

**Comment by ara4n** [comment]
This really is an embarrassing mess.  It should be possible to change your password without logging out your devices; and not supporting this encourages people to never change their passwords. The solution is surely to distinguish between:

 1. logging out a device because it is no longer trusted
 2. re-authorising the user on a device because their password changed.

The former should delete all local state (e.g. e2e keys).  The latter should just freeze the app until the user re-authorised (and only delete their state if they fail).

**Comment by kaiyou** [comment]
More generally, changing password is a standard action during the lifetime of an account and should not affect authenticated sessions in any way. I see no reason why a session token cannot outlive a password and thus no reason for case number 2. to require any change except for not logging out every device when a user changes password. Unless session tokens are somehow derived from the password, which I do not believe is the case and would probably be a bad idea anyway.

I then see two different options: changing password for the account and run a security lockout of the account. The former should only change the authentication password and not affect anything else. The latter should delete local state from devices and disable every authenticated session.

**Comment by lhunath** [comment]
s/different options/distinct user actions/ ?

**Comment by hrj** [comment]
If I try to change my password now, the message prompts me to export E2E keys and then reimport them after re-login.

But I have my keys backed up on the server already. Is restoring from backup the same as export + import of E2E keys? In other words, as far as E2E keys are concerned, do I have to treat password change differently than a logout + login?

**Comment by z3ntu** [comment]
@hrj I've just tried - and the result is, that you have to manually restore the key from the settings but after that I can read my encrypted chats again. But it seems that the "verification of other peoples devices" have been lost.

**Comment by matthijskooijman** [comment]
> I've just tried - and the result is, that you have to manually restore the key from the settings but after that I can read my encrypted chats again. 

So you're saying that the recently introduced "Key backup" feature does *not* help to preserve keys on a password change? Any comment on what prevents this from working? The key backup has a separate password / "recovery key", so that could be unaffected by the password change. Or does a password change clear the server-side backups?

**Comment by jryans** [comment]
Key backup _does_ preserve keys even across password change. If you are using server-side key backup, you can restore from backup after both log out / log in (which creates a new device) and also after password change.

If it's _not_ working that way for you, please file a separate issue so we can investigate.

**Comment by jryans** [comment]
> If I try to change my password now, the message prompts me to export E2E keys and then reimport them after re-login.

This part about the message prompting you to export is simply a bug and very confusing. https://github.com/vector-im/riot-web/issues/9432 is tracking fixing this.

**Comment by matthijskooijman** [comment]
Ok, great. I *think* my observations match your explanation (but I'm not actually using E2E right now, so can't completely confirm). Thanks for pointing at the other issue, since that is indeed the issue I was working towards :-)

**Comment by turt2live** [comment]
Soft logout is now a thing that exists in riot (develop) - we should consider at the spec level invoking a soft logout when the user changes their password (maybe with an explicit flag for "yes, actually delete everything")

**Comment by ara4n** [comment]
We now also have https://github.com/matrix-org/matrix-doc/pull/2457 as an API explicitly for prompting whether to log out all other devices or not, which should be hooked up.

**Comment by schildbach** [comment]
What is the workaround for this? Can I edit the password via SQL on the Postgres database?

**Comment by kylrth** [comment]
Yeah none of my users want to change their passwords (including me) because we don't want to have the chance of losing chat history if we lose E2E keys or don't export/import them properly. Commenting to bump this issue

**Comment by BrenBarn** [comment]
This really needs to be resolved.  Changing a password is a completely normal and everyday operation that should not be this disruptive.

**Comment by hughns** [comment]
There is a proposed implementation of this for Element Web in https://github.com/matrix-org/matrix-react-sdk/pull/8259
