### ISSUE TITLE
Cannot fetch status: ELEMENT_DEPLOYMENT_MISSING_FROM_BODY

### ISSUE THREAD

**Issue by Re1Ser** [vector-im/element-web#26725]
### Steps to reproduce

Hi, i followed the installation from the official website, but i have this error : Cannot fetch status: ELEMENT_DEPLOYMENT_MISSING_FROM_BODY

thanks a lot !

### Operating system

Ubuntu

### Application version

23.10.15

### Will you send logs?

No

**Comment by t3chguy** [comment]
That doesn't look related to this project, our versioning hasn't reached `23.10.15` yet nor is that an error present in this project.
