### ISSUE TITLE
We should stack up rejects to invites so they rate limit nicely

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2686]
rather than this:

<img width="811" alt="screen shot 2016-12-04 at 22 01 30" src="https://cloud.githubusercontent.com/assets/1294269/20869581/46c85112-ba6d-11e6-82de-6380f1d2f786.png">

**Comment by ara4n** [comment]
See also #2758

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/2758 which more strongly advocates for server setting changes.
