### ISSUE TITLE
Notification panel looks like a slider, but they are radio buttons (UX issue)

### ISSUE THREAD

**Issue by AndrewJDR** [vector-im/element-web#2704]
I think the vertical line between the dots in the notification panel makes it intuitively seem like a slider, but it is not:
![notification-panel](https://cloud.githubusercontent.com/assets/1588857/20960787/eb185dde-bc16-11e6-877a-48aa47b4d3ce.png)

That is, it's tempting to try to click/drag up and down to reset the setting, but it doesn't work that way.
I think the fix for this could be as easy as removing the vertical line that connects all the dots together -- this will make them look more like radio buttons, which is what they are.

**Comment by ara4n** [comment]
or we could make the widget draggable :) agreed, though.

**Comment by turt2live** [comment]
we fixed this
