### ISSUE TITLE
No newlines when copying device name/ID/key from "Verify device" dialog

### ISSUE THREAD

**Issue by intelfx** [vector-im/element-web#2715]
If you try to copy the device name/ID/key text from the "Verify device" dialog in Riot, the copied text appears to lack newlines:

```
    Device name: http://localhost:8080/ via Chrome on Mac OSDevice ID: IGSAXQXLKRDevice key: Vglpdm/1WMAuqW9LV4rrHDwGGnO0of3STve7gxjQ/OE
```

**Comment by richvdh** [comment]
all you really need is the device key, anyway...

**Comment by intelfx** [comment]
This is not a justification.

**Comment by ara4n** [comment]
@intelfx on what browser? it works fine on Chrome:

```
Device name:	https://riot.im/develop/ via Chrome on Mac OS
Device ID:	SLAZHXJCYM
Device key:	E7GqHUo1Cw/+FdawwbQFbGUMbR/1hkeRGPqLO2LXS1Q
```

**Comment by intelfx** [comment]
@ara4n FF 50.1.0, still present on develop.

**Comment by kittykat** [comment]
I'm going to close this for now as I don't believe this dialog exists in the same form now. If it does, please reopen the issue or comment with @kittykat and I will :+1:
