### ISSUE TITLE
cordova/phonegap/ionic compatibility and push with gcm apm

### ISSUE THREAD

**Issue by maxlinux2000** [vector-im/element-web#2736]
Hello, I would like this project to work inside a hybrid app Cordova / ponegap / ionic .....

I think there is no greater difficulty to create an app using npm inside Cordova, but what stops me is that I do not know how to implement Push notifications using google gcm as well.

Does anyone have experience with this?

regards

**Comment by ara4n** [comment]
I don't think anyone on the core team has experience with cordova/phonegap/iconic and how push works.  i suspect you'd want to wrap matrix-react-sdk rather than riot, too (although the two are quite entangled currently)

**Comment by t3chguy** [comment]
We will be keeping with the Electron app for now.
