### ISSUE TITLE
bulk reject button only clears 15 or so at a time.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2758]
are we failing to handle rate limiting?

**Comment by MadLittleMods** [comment]
The rate limit retry logic is in there: [`src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx#L190-L210`](https://github.com/matrix-org/matrix-react-sdk/blob/d3771f8a9fb13e5b753cabd9fd24f79f833fc489/src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx#L190-L210).

Given I've recently used this for accepting 400+ invites on Gitter, I'm going to call this good. The code path is the same for reject as far as I can tell.
