### ISSUE TITLE
Cmd-F doesn't exist or work on Electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2764]
How can I find anything?!?! :D

**Comment by aaronraimist** [comment]
Yes Cmd-F is not supported in Electron, see https://github.com/electron/electron/issues/2037. Maybe Cmd-F should be connected to Riot's built in search functionality.

**Comment by t3chguy** [comment]
So this is possible but without wrapping the app in a `<webview>` it yields a focus-stealing bug where a find-in-page will steal your focus on every keydown: https://discuss.atom.io/t/using-webcontents-findinpage-to-implement-typical-find-function/25309/6

Wrapping the app in a webview means a relatively large refactoring :(

**Comment by t3chguy** [comment]
Whilst I do still intend to look at this, it has taken a lower priority.

**Comment by sirocyl** [comment]
Going to bump this issue - have experienced the same behavior.

Expectation is that pressing `Ctrl+F` should perform the same function as clicking or focusing on the Search button in the header. specifically class `mx_RoomHeader_searchButton`.

Observed behavior is that nothing visible happens.

Willing to help debug and test if need be.

**Comment by t3chguy** [comment]
@sirocyl this issue is about a find-in-page like a browser

**Comment by sirocyl** [comment]
Ah, so out of scope. Should I start a new issue? @t3chguy

**Comment by t3chguy** [comment]
Maybe it'd be good to vote to see what users would prefer, 🎉  on the original post (top) for find-in-page, 🚀  for Matrix search

**Comment by sirocyl** [comment]
Sounds good - I also poked the #element-web channel for advice on scoping this issue.

**Comment by sirocyl** [comment]
So, by their advice, I opened a new issue on this - #15816.

**Comment by t3chguy** [comment]
There's now a setting to wire up Cmd+F to the Search function

**Comment by kittykat** [comment]
@t3chguy can we close this issue now as there is a setting to enable the shortcut?
