### ISSUE TITLE
I should be able to answer a call from the button bar

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#2781]
today I can only hang it up whilst it's ringing...

**Comment by ara4n** [comment]
@AmandineLP i don't understand - do you want inbound calls to be show in the StatusBar (where typing notifs etc go)?

**Comment by ara4n** [comment]
ah, i've seen it now - the inbound call causes your voip buttons in the RHS of the composer to turn into a single red hangup button.  I think we should have a green and red button instead for answering/rejecting there.

**Comment by SimonBrandner** [comment]
Closing as this has been reworked and there don't seem to be any problems with this:

![Screenshot_20210222_201816](https://user-images.githubusercontent.com/25768714/108758211-1f1e2b80-754b-11eb-94e2-93a2f90a60d7.png)
