### ISSUE TITLE
Event sending & local echo broke weirdly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2786]
![screen shot 2016-12-21 at 23 12 19](https://cloud.githubusercontent.com/assets/1294269/21409589/07518ac6-c7d3-11e6-90a4-53be967c6d37.png)

irritatingly I had the stacktraces in the console log, but apparently they didn't copy correctly. It was talking about a null event somewhere in the depths of the JS SDK in sendMessage when handling local echo.

**Comment by jryans** [comment]
Haven't seen anything like this in recent times, going to assume it's fixed. If not, a fresh issue with more info would be good to have anyway.
