### ISSUE TITLE
Handle electron's registration next_link better

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#2796]
https://github.com/vector-im/riot-web/blob/master/src/vector/index.js#L139 goes & gets window.location etc. as what to redirect back to after registration, which obviously does not work for Electron. This should be moved to the Platforms, where the electron impl will probably return null in the short term (and change the registration logic to handle that & not give a next_link). In the slightly longer term, it can register a protocol handler with the OS.

**Comment by ara4n** [comment]
a workaround landed in https://github.com/vector-im/riot-web/commit/078493912c97f83971ca225e962077daa0e2dd79.

Keeping this open so that it's handled by Platforms and/or proto handlers in future.

**Comment by turt2live** [comment]
I'm pretty sure we've handled this these days.
