### ISSUE TITLE
Emojis: Wait for the first letter before showing the emojis popup

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-web#2811]
Right now, as soon as we hit `:` the emojis list pops up. But some time we just really want to write `:` as in:

> Example: this is a valid colon.

or 

> Check the list below:
>   * one
>   * two

The GitHub behavior is that if there is a letter just before the colon, then the popup doesn't show.
Personally, I think it's pretty useless to show the popup as soon as `:` is written. I think the rule should be:

```
If there is no letter before `:` and at least one letter after:
    Show the emoji popup filtered with the letter(s) after the `:`
```

**Comment by MightyCreak** [comment]
In slack it even waits for the second letter to be written (but personally I don't like it)

**Comment by MightyCreak** [comment]
Part of #2984

**Comment by Peque** [comment]
As of 1.9.0 I think this may be implemented. At least, I need to type 2 characters to see the pop-over emoji suggestion list.

**Comment by aaronraimist** [comment]
I agree
