### ISSUE TITLE
Riot's debian repo is inexplicably slow

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2816]
35KB/s slow.  Both for me on vbox and mikaela and this guy: https://medium.com/@amblin/huge-thank-you-for-the-debian-ubuntu-repo-but-man-is-it-sloooow-d49922031c27?source=responses---------0----------

**Comment by Typ260** [comment]
2021 and this issue persists...

![Bildschirmfoto von 2021-05-03 10-50-24](https://user-images.githubusercontent.com/20070370/116857617-65ec6980-abfd-11eb-92b5-cb150c8add72.png)

**Comment by sweidac** [comment]
Also slow for me it starts with something okayish like 1Mbit/s and then drops to 5 - 10 kBit/s. Same behavior when downloading with a browser.

I'll be happy to provide more info.

**Comment by t3chguy** [comment]
This is now fixed
