### ISSUE TITLE
option to jump to first unread msg in room rather than most recent msg

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2829]

**Comment by richvdh** [comment]
Isn't this the "unread messages" bar (which doesn't actually work thanks to #1146)?

**Comment by ara4n** [comment]
yes, but the request here was to make the behaviour configurable as to whether when you switch to a room it should default to the bottom or to the 'unread messages' location.  Slack defaults to the latter; we default to the former.

**Comment by grahamperrin** [comment]
> … make the behaviour configurable …

:+1: 

> … to the 'unread messages' location. …

That would be my preference. Largely blocked by https://github.com/vector-im/riot-web/issues/1146, if I understand correctly.

**Comment by buguniaogu** [comment]
😂still not change.
