### ISSUE TITLE
E2E encrypted voip conferences

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2849]
Needs full mesh or a fun SFU which routes purely on metadata and can't transcode

**Comment by JasonLocklin** [comment]
Relates to: https://github.com/matrix-org/matrix-doc/issues/508

**Comment by ara4n** [comment]
Our focus at first is on making confs work well... and then making them work well e2e.  SFU is on the table.

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-doc/pull/2359

**Comment by SimonBrandner** [comment]
https://github.com/vector-im/matrix-video-chat

**Comment by SimonBrandner** [comment]
I am going to close this as I don't think it holds much value anymore... The work on this is happening in https://github.com/matrix-org/matrix-doc/pull/3401 and https://github.com/vector-im/matrix-video-chat
