### ISSUE TITLE
URL preview for some web sites is very long

### ISSUE THREAD

**Issue by radix** [vector-im/element-web#2894]
Here's an example using http://xion.io/drafts/rust-unit-test-placement.html (which I'm not sure will be there permanently). Somehow riot decided that the whole content of the post should be in the preview.

![riot-preview-too-long](https://cloud.githubusercontent.com/assets/227068/21728447/df3a17e8-d40b-11e6-9841-17e72c66f121.png)

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/1430, but I couldn't find an issue open to track it from the riot side, so keeping this open too

**Comment by uhoreg** [comment]
An easy fix to this may be to add some styles to limit the height of the preview.  For example,
```
.mx_LinkPreviewWidget_description {
  max-height: 7em;
  overflow-y: auto;
}
```

**Comment by lukebarnard1** [comment]
Having a scrollbar (using `overflow-y: auto`) seems odd as you end up with something like
![2017-05-17-132052_492x358_scrot](https://cloud.githubusercontent.com/assets/6750344/26153532/ae5763d8-3b03-11e7-87a7-e8b2f98b2518.png)

I think I'd prefer using `text-overflow` somehow

**Comment by uhoreg** [comment]
Yup, using `text-overflow` instead of `overflow-y` seems fine to me.

**Comment by t3chguy** [comment]
Should be fixed by matrix-org/synapse/pull/2243

**Comment by t3chguy** [comment]
Though comments have been made that Riot should handle this too, so reopening for that discussion

**Comment by nukeop** [comment]
Still occurs, can it be solved in frontend somehow? Like limiting the height of the preview box and adding ellipsis?

**Comment by MadLittleMods** [comment]
It looks like this has some webkit specific styles to accomplish this nowadays ⏩ and it even seems like that vendor prefixed property is also supported in everything else except Internet explorer, https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp#browser_compatibility

```
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
```

The preview is cut off after 3 lines of text:

![](https://user-images.githubusercontent.com/558581/135142721-09064edf-da19-4c9d-836d-e83c7170bd8d.png)

vs the full description in the DOM which you can see on wider screens:

![](https://user-images.githubusercontent.com/558581/135142831-f5e4ba84-96c5-4cd7-b7fa-b9f236420083.png)
