### ISSUE TITLE
permalinks only work once

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#2903]
If I jump to a specific message in a channel, then I click the down arrow to return to the bottom of the page, then click the link again, Riot doesn't scroll up to the message again

**Comment by ara4n** [comment]
presumably the problem is that the URL of the room doesn't change, so it doesn't realise anything happened.  We'd need an onClick as well as the target hyperlink to kick it into life?

**Comment by rkfg** [comment]
Workaround: click on the room you're currently in (at the left list), then the URL changes and the link will work once again. Downside: clicking the room will scroll to the bottom (inconvenient if the link is somewhere above).
