### ISSUE TITLE
/!\ icon on invites can confuse users into clicking and getting lost in notif settings

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2911]
The UX of putting a warning ! on badges on invites can be confusing:

<img width="884" alt="screen shot 2017-01-10 at 22 29 09" src="https://cloud.githubusercontent.com/assets/1294269/21827579/39087564-d784-11e6-9cff-07bda0a8f371.png">

**Comment by ara4n** [comment]
i think the solution here is to not use the badge for the volume-control contextual menu at all for invites.

**Comment by turt2live** [comment]
The `!` is not gone, but the confusing menu is.
