### ISSUE TITLE
Electron's desktop notifs don't integrate with linux WM notifs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#2913]
Luke (@lukefaeh:matrix.org):
Hmm, just found a slight issue: Riot doesn't seem to correctly fire off desktop notifications the way that other programs do (on Linux). Meaning to say, while I see pop-up messages when I receive them, they aren't notifications in the way my desktop understands them; Skype, Firefox, terminal emulators, etc. send notifications that my WM understands, but Riot does not. Anybody know if this is something I can fix, or should I report a bug on it?

**Comment by weeman1337** [comment]
Closing this six year old issue. At least the notifications nowadays seem to work on Linux.
