### ISSUE TITLE
Permalinks: ! ids are unroutable, and # aliases are not permanent. Please solve.

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/element-web#2925]
Neither option is satisfactory. Please come up with a solution for this, e.g. by making ! ids routable.

**Comment by ara4n** [comment]
another workaround could be to put the routable server name in the permalink as a separate field - e.g. https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1487464117757368aDcvx:matrix.org?hs=matrix.org or something.

I agree this sucks.  The current implementation assumes your local HS knows about the room already.

Alternatively, making the server routable in the room ID might be preferable - we should already be able to get enough uniqueness in the !prefix if we try hard enough (e.g. by including origin server there....)

**Comment by jcgruenhage** [comment]
Well, the room ID already contains a server, so why shouldn't this suffice?
I mean, this !cURbafjkfsMDVwdRDQ:matrix.org says matrix.org in the id, so one would assume that the room exists on matrix.org.

**Comment by Matrixcoffee** [comment]
Also consider switching to # aliases until a better solution can be achieved. Room ! IDs are definitely unroutable *now*, whereas individual # aliases *might* become unreachable in the future.

**Comment by jcgruenhage** [comment]
Is there something that prevents a server from just trying known servers? I mean if one of your contacts has sent you a link, then your server knows their server, and they probably are in that room. Synapse won't know which server you got the link from (unless it looked in the db but this would only work in unencrypted rooms), but it could just try all of them, maybe sorted by some combination of latest communication/amount of common rooms/etc. 

The only thing I can come up with that makes this kind of bad, is that you would leak to other servers that some user on your server want's to access a room with that ID. To avoid leaking the room ID, synapse could just salt and hash it.

**Comment by richvdh** [comment]
relates to https://github.com/matrix-org/matrix-doc/issues/904

**Comment by Matrixcoffee** [comment]
FYI, this also breaks the "Rejoin" button for people with a personal homeserver, as Riot tries to rejoin the room via its room ID. #7094

**Comment by ara4n** [comment]
these days we have via= params almost everywhere, which combined with a room id gives a permenant link.
