### ISSUE TITLE
Prerelease windows versions of the desktop app update-loop

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#2968]
If you run a version of the windows app that's later than any version on the update servers, it will inform you there's an update available, then when told to update, restart into the same version you had in the first place, then repeat ad infinitum.

This is due to https://github.com/Squirrel/Squirrel.Windows/issues/774

**Comment by peppy** [comment]
Can reproduce this behaviour, and it definitely feels wrong.

**Comment by t3chguy** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/774

**Comment by dbkr** [comment]
This is apparently fixed now. We should look at now nightmareish updating electron-builder will be to get us a newer version of squirrel.

**Comment by turt2live** [comment]
I imagine we've fixed this.
