### ISSUE TITLE
Popup notifications show skin-tone modifiers as separate character

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#3042]
![screenshot_2017-01-24_14-02-19](https://cloud.githubusercontent.com/assets/1389908/22250185/ef3e304e-e23d-11e6-8dbc-04c7eaf48923.png)

**Comment by ara4n** [comment]
this sounds suspiciously like a Chrome bug under Linux... i'd be surprised if this is anything that Riot is doing wrong.

**Comment by richvdh** [comment]
so it is. we should have some sort of label for "yeah it's a bug but we can't fix it".

**Comment by t3chguy** [comment]
This is hopefully fixed upstream by now, this may even just be the chosen font doesn't have that skin variant.
Closing as presumed fixed
