### ISSUE TITLE
Favicon notification count not reflected in highlighted rooms (stuck badge count)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3060]
For quite a while, I had a (1) next on my favicon. I clicked on all of my unread (bold name) rooms to see if was one of them, but it still hadn't disappeared. Then I clicked on all of my _read_ rooms and one of them cleared the notification status on the favicon.

Sadly I didn't catch which room cleared it.

**Comment by grahamperrin** [comment]
Not only the favicon; the count is (to me) more prominently in **the title** of the page. 

Here, for example: 

![riot 1](https://cloud.githubusercontent.com/assets/192271/25372399/2581a05a-298d-11e7-8889-89e561e833f3.png)

– plus, I have the title visible in my main panel in KDE: 

![plasma-desktop](https://cloud.githubusercontent.com/assets/192271/25372458/683b4842-298d-11e7-8eae-923849aec226.png)

(Side note: whilst the red alert has disappeared, I have no recollection of reading any red text. It's disorienting.)

**Comment by jcahill** [comment]
I've had similar notification count problems. I doubt they need a new issue.

For me, the stuck count is recurring. On first description I stated that the value was always [2]. It now occasionally sticks at [1] as well. The [2] case always needs to decrement twice, never 2->0.

The offending rooms remain seemingly arbitrary, as do the most recent event types in those rooms.

In the screenshot below: count was [1], offender was #synapse-community. The room is muted.

![riot-web_3060](https://cloud.githubusercontent.com/assets/4574990/25777585/376a48a0-32af-11e7-88c6-a7d8f7cbe1f3.png)

First mention in #riot:

![riot-web_3060-02](https://cloud.githubusercontent.com/assets/4574990/25777645/689c5772-32b1-11e7-87c3-2fa1cb7a5a83.png)

**Comment by MTRNord** [comment]
Hapens on my side too. On Android it doesn't happen

**Comment by Nostradamos** [comment]
Happens to me too, clicking on some rooms solves the problem after a very short delay.

**Comment by aaronraimist** [comment]
I've had a 1 badge on my favicon that I can't get rid of for a few weeks now. Clear cache doesn't fix it. Where can I look to start debugging where this is happening? 

It is there across all instances of Riot web/desktop but no other clients see it. No badge on Riot iOS and all rooms appear to be read in Riot and in other clients like Quaternion.

**Comment by aaronraimist** [comment]
`@leprasmurf:chat.geekforbes.com` found out a way to find rooms with notifications: 

```
mxMatrixClientPeg.get().getRooms().forEach(function(element) {let count=element['_notificationCounts']['total']; if(count > 0) { console.log( element['name'] + ' (' + element['roomId'] + ') - ' +  count)}})
```

That let me find the room that "had the notification" even though it really didn't. Riot didn't display it with a badge next to it or even with the name written in bold. Viewing that room cleared the badge on my favicon.

**Comment by aaronraimist** [comment]
Seems like this has been happening a lot recently. I’ve helped several people who had the same problem and it seems like it was all notifications from rooms that had been upgraded.

**Comment by tgr** [comment]
Happened to me recently. As far as I can tell the room wasn't upgraded (it's at version 1 now; none of the admins know much about Matrix). It's bridged (manually) to a Freenode IRC channel, not sure if that matters.

**Comment by aaronraimist** [comment]
This should probably be reopened. I still regularly help people with this issue.

**Comment by KB1RD** [comment]
Here is a bit of code to clear all unread notifications:
```javascript
(function(mx){mx.getRooms().forEach(function(element){const count=element['_notificationCounts']['total']; if(count > 0) {mx.sendReadReceipt(function(evs) {return evs[evs.length - 1]}(element.getLiveTimeline()._events), {})}})})(mxMatrixClientPeg.get())
```
... and the slightly easier to read version...
```javascript
(function(mx) {
    mx.getRooms().forEach(function(element) {
        const count = element['_notificationCounts']['total'];
        if (count > 0) {
            mx.sendReadReceipt(function(evs) {
                return evs[evs.length - 1]
            }(element.getLiveTimeline()._events), {})
        }
    })
})(mxMatrixClientPeg.get())
```
It might be nice to have a UI button somewhere to clear all notifications. I think @aaronraimist mentioned putting this near the clear cache button. I put a `javascript:` URL on my bookmarks bar in the mean time.

**Comment by dbkr** [comment]
Looks like one source of this is notifications in previous versions of rooms.

**Comment by turt2live** [comment]
the previous room versions bug is a result of https://github.com/vector-im/riot-web/issues/7843, not this issue. There is UI for exposing notifications in old rooms, but due to a mix of server-side resets and Riot cache problems the "previous" room can be lost so the UI doesn't show up.

**Comment by aaronraimist** [comment]
Got this again with the new wave of +matrix:matrix.org upgrades. Was the old Synapse Announcements room !qBFNwucQebGPQldAnq:matrix.org which didn't even have any new messages...

**Comment by aklys** [comment]
Experienced this with it sticking around for about 5 months. Was given the javascript workaround which cleared it up.

**Comment by Flexmaen** [comment]
The whole notification part does not werk very well for me in Riot-Web. Most of the time I can't figure out why I got the notification. Luckily I got Riot on Android, where I get a notification of the exact message.

**Comment by novocaine** [comment]
@aaronraimist are you still seeing instances of this issue coming up?

**Comment by aaronraimist** [comment]
@novocaine no I have not seen this in a while

**Comment by novocaine** [comment]
Okay! Just ping here if it starts coming up again please, closing for now
