### ISSUE TITLE
rrix says 3pid invites are 500ing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3085]

**Comment by ara4n** [comment]
@rrix they seem okay for me atm - did you have repro steps?

**Comment by rrix** [comment]
@ara4n I sent multiple invites to a 3pid which eventually registered as @cb7:matrix.org (I don't remember his email 3pid offhand, sorry); they all 500'd after 60 second timeout or so. I tried three or four times, and they retried multiple times, ending with him getting something like 20 invites all said and done.

**Comment by ara4n** [comment]
do you remember if they were 500s or 504s?  (we can hopefully hunt these 
down from the synapse http logs tho)

**Comment by rrix** [comment]
They were 500s from Synapse IIRC. Whatever the M_ error was I don't remember offhand but they were HTTP 500s

**Comment by turt2live** [comment]
Is there much we can do about this 2 years later?

**Comment by aaronraimist** [comment]
> Is there much we can do about this 2 years later?

I'm going to say no.
