### ISSUE TITLE
Limit the number of concurrent preview url requests

### ISSUE THREAD

**Issue by kegsay** [vector-im/element-web#3106]
I noticed that I had no avatar images loading in riot-web and then /sync requests were being client side timed out. Logs showed 504 timeouts from preview url requests. It turns out that Riot had done lots of these preview url requests and they all wedged like that, starving the rest of the app from making any connections. We should put a cap on the max requests that we will make to /preview_url

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/7292

Related to https://github.com/vector-im/element-web/issues/10555 and https://github.com/vector-im/element-web/issues/14998
