### ISSUE TITLE
Voip e2e room: "User answered the call" event is highlighted

### ISSUE THREAD

**Issue by jeangb** [vector-im/element-web#3151]
To reproduce:

1. With user 1 on ios device, create a e2e room, invite a user2
2. With the webclient, accept invitation with user 2
3. With user 1, start a voice call, answer the call with user 2

User 2 on the webclient have the voip event highlighted.
I only reproduce it on the first call of an encrypted room.
I guess it's a matrix issue ? I didn't reproduced it with android on user1.
![highlighted user on answering call event](https://cloud.githubusercontent.com/assets/22364949/22656224/f541beb6-ec92-11e6-8da1-06fa8f05a226.png)

**Comment by ara4n** [comment]
i suspect this is because there's an error whilst sending the event, causing it to go red. probably related to #2669

**Comment by SimonBrandner** [comment]
@jeangb, is this still a problem?

**Comment by jryans** [comment]
Let's assume probably not. Please reopen or file a new issue if this still happens.
