### ISSUE TITLE
Support proper zooming when looking at images in lightbox

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3159]
Using the normal browser zoom doesn't work. When the zoom is increased, the download button increases in size, making the image comically _smaller_:
![2017-02-07-130558_742x652_scrot](https://cloud.githubusercontent.com/assets/6750344/22692345/6e340ba0-ed36-11e6-846f-e28316dddb3c.png)

Also, when zooming is decreased, the image is enlarged for similar reasons:

![2017-02-07-130613_981x526_scrot](https://cloud.githubusercontent.com/assets/6750344/22692376/86ae78be-ed36-11e6-8641-9ada365b47c5.png)

**Comment by uhoreg** [comment]
see also #3323

**Comment by vRobM** [comment]
This is not just cosmetic. 
When images are posted in riot, they need to be able to be zoomed in when clicked on
or viewed full screen for the fine details ;]
Now it's just the same size which is pretty useless.. pretty critical usability issue.

**Comment by JPustkuchen** [comment]
I agree this is one of the worst UI problems in riot.

**Comment by krruzic** [comment]
Why has this sat ignored for 3 YEARS? This is a critical feature that should have been implemented almost immediately. Images with text are almost always unreadable, doesn't matter device.

**Comment by t3chguy** [comment]
Because there is a simple workaround to just open the image in browser with a single click

**Comment by JPustkuchen** [comment]
@t3chguy, can you please tell us how that works in the riot Desktop application?

**Comment by t3chguy** [comment]
the `Download this file` button opens it in browser due to another bug, for unencrypted rooms at least. I just put up a bountysource bounty for this

**Comment by JPustkuchen** [comment]
Thank you. For us (encrypted rooms) in the desktop application it opens the Save file browser FYI. So no workaround for us.

Bit anyway @krruzic I agree this is very important, but we should be friendly with each other. I don't think this will rank up in priority, if we're unfriendly in a great open source project like this.

**Comment by rgpublic** [comment]
FWIW if I right-click any image and select "Save image as...", a file browser is openend but immediately at the same time an error message appears: "The image failed to save". I can close the error message and the file browser is still opened. I can then enter a file name and click on the "Save" button, but even though the file browsers closes the images isn't actually saved.

**Comment by t3chguy** [comment]
@rgpublic thats a different issue and is already fixed, will be in the next release.

**Comment by Ruperr** [comment]
Any update on zooming for the desktop client? It hardly needs mentioning that downloading the image is no proper solution.

**Comment by JPustkuchen** [comment]
Whao that is, even if "small" change, really really GREAT news. Thank you so much @turt2live
