### ISSUE TITLE
File uploads can ping but do not highlight

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#3168]
### Description

If a file (such as an image) is uploaded with my name, it can ping me. I see that I was pinged, but don't see what message actually pinged me.

Discovered in `#test:matrix.org`: https://matrix.to/#/!vfFxDRtZSSdspfTSEr:matrix.org/$14865037172430113AheKW:matrix.org

(this is a piggyback off of Erik's situation)

### Steps to reproduce

- Be inactive in a room
- Have a friend upload a file with your name (ie: `travis.png` if you're me)
- Note that you're pinged (favicon, room notif, but no message is highlighted)

Describe how what happens differs from what you expected.

I'd expect that the filename would be highlighted - or some kind of indication that the upload caused the ping. It does seem kinda quirky that file uploads can ping, however I'm personally used to being mis-pinged constantly (Travis-CI is a real annoying thing to have a similar name to in the development world).

Log: sent/not sent?   Not sent - should be easy to reproduce (rename a file and upload) 

![image](https://cloud.githubusercontent.com/assets/1190097/22714052/16cc06c6-ed48-11e6-9c99-9a7accd486bb.png)
![image](https://cloud.githubusercontent.com/assets/1190097/22714079/2e1a8118-ed48-11e6-921b-8f06d33a7864.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Fixed
