### ISSUE TITLE
Disable server-side history room-wide, user-wide and server-wide options.

### ISSUE THREAD

**Issue by cloudyfuel** [vector-im/element-web#3177]
An option to disable server-side history for a room (this could be an agreement between participants, a prompt appears - do you agree? or a normal setting) and as a default for all conversations you make (two options, one for 1:1 chats, one for group chats). Keep it on device, but if the device is lost/removed from account or history is deleted/redacted/self-destructs, there's no way to get history back. Welcomed would be a server-wide setting - disable history by default (but can be changed by each user) and disable history without ability to enable it via client.

All the messages should reach all the devices (registered with the account before message is sent). (So XMPP's Message Carbons equivalent is needed, albeit with a difference that messages are delivered even if a device isn't online at the moment, there should be an expiration time after which they won't be delivered to X device fe. 7 days.)

Similar to:
XMPP - server can have a MAM default setting and per contact setting - never (both chat participants have to set this option for the server to not store history)
Signal - messages are kept on the server until they reach all the devices a given user has

Edit: Important thing is that complete chat history is still available, only that not on server or new devices.

**Comment by ara4n** [comment]
this is basically https://github.com/matrix-org/matrix-doc/issues/447

**Comment by richvdh** [comment]
Or #2497, depending on the implementation

**Comment by t3chguy** [comment]
@richvdh that link doesn't point where I think you want it to point

Closing in favour of the spec issues
