### ISSUE TITLE
if users redact their own joins the event now disappears entirely

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3193]
we should never be hiding redacted state events from the timeline, only the human-visible bits!

**Comment by ara4n** [comment]
n.b. that redacting state events currently causes thundering herd woes

**Comment by ara4n** [comment]
@lukebarnard1 is this something to do with the MELS stuff?

**Comment by lukebarnard1** [comment]
@ara4n yes! https://github.com/matrix-org/matrix-react-sdk/pull/609

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7768.
