### ISSUE TITLE
Ben's riot spins 100% cpu and freezes the tab completely if he goes into a certain room

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#3198]
Can't get chrome to respond enough to actually see what it's doing :/

**Comment by dbkr** [comment]
Now stopped doing it after Ben sent a message into the room from his mobile.

State was that Ben had sent a message with a URL (so URL preview) yesterday, then a couple of messages from Amandine today, then fixed itself when Ben sent a message from mobile.

**Comment by kittykat** [comment]
This is an old issue and not reproducible so closing unless someone is till seeing it.
