### ISSUE TITLE
Allow restricting access to a specific home server in the web application (security)

### ISSUE THREAD

**Issue by smkent** [vector-im/element-web#3209]
### Description

I installed `riot-web` on my own server for use with my own Matrix homeserver.

I set the default home server in my Riot instance's `config.json` to my own home server, but currently nothing prevents someone from using Riot installed on my server to log in with an account on a different home server.

Is it possible to restrict logins in the Riot web app to a specific home server? If not, this feature needs to be added as it should be considered a security issue.

### Steps to reproduce

- Install a Matrix home server for `somedomain.com`
- Install riot-web for use with the above Matrix home server at `riot-app.somedomain.com` or so. Optionally configure the default home server in `config.json` to be `somedomain.com`.
- Navigate to `riot-app.somedomain.com` in your browser
- Log on with a Matrix account on a domain other than `somedomain.com` (ex. `@someuser:matrix.org` instead of `@someuser:somedomain.com`)

**Expected result**: Users not on `somedomain.com` cannot log in

**Actual result**: Users can log into the Riot web app on `riot-app.somedomain.com` using accounts on any Matrix home server

### Version information

- **Platform**: Web
- **Version**: 0.9.7

For the web app:

- **Browser**: All
- **OS**: Tested on Gentoo Linux, but presumably all platforms
- **URL**: Any `riot-web` web installation

**Comment by ara4n** [comment]
why do you consider this a security issue? the ability to change matrix HS is normally considered table stakes for a matrix client...

**Comment by smkent** [comment]
This is specific to the web-based app, not the desktop version of Riot.

Let's say I have users on `example.com` and I want to give them access to a Riot client trusted by the `example.com` organization. To do this, I install Riot at `https://riot.example.com/` with the default home server set to `example.com`.

However, nothing prevents users with Matrix accounts on other domains from using the client installed on `riot.example.com`, so `@someuser:matrix.org` could log into their account using Riot on `riot.example.com`.

It's poor security practice to allow access to organization-specific resources to external or anonymous users. In the above scenario, external users can consume server resources belonging to `example.com`. The server(s) belonging to `example.com` also become a traffic relay if any outside users engage in malicious activity.

**Comment by ParitoshBh** [comment]
> The server(s) belonging to example.com also become a traffic relay if any outside users engage in malicious activity.

Same concern has been bothering me as well! Is there a way to disable this option other than removing it from UI?

**Comment by t3chguy** [comment]
Riot Web has no server component, and with it being Javascript anyone can always modify in browser some js code and remove the restriction you put in place. For the record the latest Dev version has a config option to remove the server selector

**Comment by t3chguy** [comment]
So if someone using riot.example.com connects to matrix.org, no traffic actually goes through riot.example.com, only that to load the webapp. Riot connects directly to a matrix server

**Comment by ParitoshBh** [comment]
That explains a lot.

> For the record the latest Dev version has a config option to remove the server selector

A bit of peace of mind :)

**Comment by turt2live** [comment]
> Why not add an option to disable the ability to change the configured homeserver?

@xoxys directly above your comment is a reference that there's an option to disable the selector. The issue is still open as there's no concrete way to enforce that *only* a specific homeserver can be used, however it can be made incredibly difficult for people to change the server.

To do this, add `"disable_custom_urls": true` to your config.json

**Comment by xoxys** [comment]
Thanks for your reply. Sorry for not reading carefully enough.. My bad

**Comment by t3chguy** [comment]
Closing as `disable_custom_urls` is good enough. At the end of the day someone can jump through the javascript console to get what they want regardless of how difficult we make it. Its javascript.
