### ISSUE TITLE
Bug reporting fails on FF incognito mode

### ISSUE THREAD

**Issue by kegsay** [vector-im/element-web#3230]
Because Firefox doesn't remove the global `window.indexedDB`, they just silently fail all requests made to it, including connecting to the database. This makes the bug reporting code think there is a valid database set up, so it never just sends the in-memory logs.

This isn't as simple as "if I fail to flush logs, just send in-memory logs" because we wipe the logs just before we flush them :/

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15276
