### ISSUE TITLE
Ability to autojoin subrooms when you join a parent room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3266]
https://github.com/vector-im/riot-web/issues/2454 discusses the idea of being able to automatically group rooms together (e.g. with tags).  An extension to this might be if joining one room automatically made other rooms visible - effectively autojoining you to them (at least to the point of peeking).

A variant of this has already landed for RTS at https://github.com/vector-im/riot-web/issues/1636

**Comment by turt2live** [comment]
Until we have the capability to do this, I don't think we should have an issue for it. This would likely be solved by https://github.com/vector-im/element-web/issues/5077 or similar.
