### ISSUE TITLE
VOIP not working in browser/browser but work in android/browser

### ISSUE THREAD

**Issue by kadogo** [vector-im/element-web#3274]
### Description

Hello,

I tried with a friend VOIP using riot.im/app and my personal homeserver.
We receive each other the notification for the call but we couldn't hear each other.
I tried with riot-android and it work nicely.

It's true that I don't have turnserver yet for my homeserver,
but I used my phone on the same network than my computer.

### Steps to reproduce

- Connect on riot.im/app with personnal homeserver
- Call the other person
- The other person answer to the call

The call was working but we didn't hear each other.

Log: not sent    

- Dark theme
- End to end encryption activate
- A chat room with only one person

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox Nigthly
- **OS**: Debian Jessie
- **URL**: riot.im/app /

**Comment by plexorama** [comment]
+ Chrome / Chrome, Firefox / Chrome, etc. does not work at all

**Comment by ara4n** [comment]
Can you please send logs on both sending & receiving device (when it fails) so we can dig into it? thanks.

**Comment by t3chguy** [comment]
Have rageshakes been sent for this?

**Comment by kadogo** [comment]
For my problem I didn't send logs because I never tried it again for now, but maybe the other person have a similar problem and already send logs.

**Comment by SimonBrandner** [comment]
@kadogo, is this still a problem?

**Comment by kadogo** [comment]
Hello @SimonBrandner 

I never tried again so I cannot answer maybe @plexorama have tried later and can anwer if it works now or not.

**Comment by SimonBrandner** [comment]
I will close this as I can not reproduce this and there doesn't seem to be a response from @plexorama or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Comment by alitaheri1985** [comment]
I've gotten an error "Your browser does not support some of the features required for VoIP to work. Please try updating your browser or using a different one." when I tried to make a call on browser but its ok by application like Zoiper. everybody, can you help me to solve that problem?
