### ISSUE TITLE
[Bug] WebRTC riot-web <-> riot-android: only 1 voice channel (android -> web) active

### ISSUE THREAD

**Issue by plexorama** [vector-im/element-web#3278]
### Description

when calling from riot-web (Firefox) to riot-android only 1 voice channel (android -> web) is active. according to the javascript console, ICE RTP session description is correctly setup, but packets (checked via tcpdump) are sent only from the android device via turn server to the Firefox browser. However, Firefox DOES NOT SEND ANY UDP audio packets. Microphone symbol is visible in the Firefox URL bar, indicating activity.

Following warnings can be found in the javascript console prior RTP setup: 

RTCIceServer.url is deprecated! Use urls instead.  bundle.js:84
onaddstream is deprecated! Use peerConnection.ontrack instead.   bundle.js:84

It seems Firefox isn't forwarding the encoded mic stream to the network interface at all.

However, making a call between two android devices located within different networks, works like a charm (voice&video)

### Steps to reproduce

- Start a voice call between Firefox 50.1 and riot-android 
- the devices have to be in different networks  (device <-> NAT <-> TURN <-> NAT <-> device)

Log: attached    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 50.1
- **OS**: macOS
- **URL**: private server, latest github version

Tried testing with Google Chrome 56.02924.87, but got "Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?", although permissions were set correctly and mic/cam usage was allowed.

Javascript Console Log

Created offer: [object RTCSessionDescription]  bundle.js:80:16496
call c1487602924083: Signalling state changed to: have-local-offer  bundle.js:80:16496
Call state in !ERwkXQHfiNCtrcFcHY:matrix.privateserver.local changed to ringback (ringback)  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:0 1 UDP 2122252543 192.168.0.52 57700 typ host  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:0 2 UDP 2122252542 192.168.0.52 52991 typ host  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:1 1 UDP 1686052863 1.1.1.1 57700 typ srflx raddr 192.168.0.52 rport 57700  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:2 1 UDP 92217343 10.1.1.1 50845 typ relay raddr 10.1.1.1 rport 50845  bundle.js:80:16496
Attempting to send 4 candidates  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:1 2 UDP 1686052862 1.1.1.1 52991 typ srflx raddr 192.168.0.52 rport 52991  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:2 2 UDP 92217342 10.1.1.1 51260 typ relay raddr 10.1.1.1 rport 51260  bundle.js:80:16496
Attempting to send 2 candidates  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:3 2 UDP 8331262 10.1.1.1 62219 typ relay raddr 10.1.1.1 rport 62219  bundle.js:80:16496
Got local ICE sdparta_0 candidate: candidate:3 1 UDP 8331263 10.1.1.1 64657 typ relay raddr 10.1.1.1 rport 64657  bundle.js:80:16496
Attempting to send 2 candidates  bundle.js:80:16496
Call state in !ERwkXQHfiNCtrcFcHY:matrix.privateserver.local changed to stop_ringback (ringback)  bundle.js:80:16496
Stream id ARDAMS added  bundle.js:80:16496
Track id ARDAMSa0 added  bundle.js:80:16496
queuing assign on remoteAudio element [object HTMLAudioElement] for blob:http://privateserver.local/f2a258f1-51d8-ca4c-8807-c282d56042fa  bundle.js:80:16496
call c1487602924083: Signalling state changed to: stable  bundle.js:80:16496
Set remote description  bundle.js:80:16496
queuing assign on remoteAudio element [object HTMLAudioElement] for blob:http://privateserver.local/7d8c5d02-2c49-fe40-b611-73dea47991bc  bundle.js:80:16496
queuing play on remoteAudio and element [object HTMLAudioElement]  bundle.js:80:16496
Got remote ICE sdparta_0 candidate: candidate:3844325170 1 udp 2122260223 10.221.80.106 51079 typ host generation 0  bundle.js:80:16496
Got remote ICE sdparta_0 candidate: candidate:1684781446 1 udp 1686052607 20.1.1.1 3849 typ srflx raddr 10.221.80.106 rport 51079 generation 0  bundle.js:80:16496
Got remote ICE sdparta_0 candidate: candidate:2879407042 1 tcp 1518280447 10.221.80.106 34949 typ host tcptype passive generation 0  bundle.js:80:16496
Got remote ICE sdparta_0 candidate: candidate:2303927455 1 udp 41885695 10.1.1.1 65465 typ relay raddr 20.1.1.1 rport 3849 generation 0  bundle.js:80:16496
Got remote ICE sdparta_0 candidate: candidate:2303927455 1 udp 25108223 10.1.1.1 51420 typ relay raddr 20.1.1.1 rport 36588 generation 0  bundle.js:80:16496
queuing play on remoteAudio and element [object HTMLAudioElement]  bundle.js:80:16496
Ice connection state changed to: checking  bundle.js:80:16496
Ice connection state changed to: connected  bundle.js:80:16496
Call state in !ERwkXQHfiNCtrcFcHY:matrix.privateserver.local changed to connected (stop_ringback)  bundle.js:80:16496
queuing assign on remoteAudio element [object HTMLAudioElement] for blob:http://privateserver.local/209b728d-d61e-cc47-9040-3b9441d3e43f  bundle.js:80:16496
queuing play on remoteAudio and element [object HTMLAudioElement]  bundle.js:80:16496
Hangup received  bundle.js:80:16496
queuing pause on remoteVideo and element [object HTMLVideoElement]  bundle.js:80:16496
queuing assign on remoteVideo element [object HTMLVideoElement] for   bundle.js:80:16496
queuing pause on remoteAudio and element [object HTMLAudioElement]  bundle.js:80:16496
queuing assign on remoteAudio element [object HTMLAudioElement] for   bundle.js:80:16496
queuing pause on localVideo and element [object HTMLVideoElement]  bundle.js:80:16496
queuing assign on localVideo element [object HTMLVideoElement] for   bundle.js:80:16496
Call state in !ERwkXQHfiNCtrcFcHY:matrix.privateserver.local changed to ended (-)  bundle.js:80:16496
stopAllMedia (stream=[object LocalMediaStream])  bundle.js:80:16496
call c1487602924083: Signalling state changed to: closed  bundle.js:80:16496
Call state in !ERwkXQHfiNCtrcFcHY:matrix.privateserver.local changed to ended (-)  bundle.js:80:16496

**Comment by ara4n** [comment]
Please can you rageshake on both sender & receiver device (in riot-web it's in 'submit bug report' in User Settings; on Android you physically shake the phone), and then we'll hopefully be able to track this down.

**Comment by BloodyIron** [comment]
Is this still a thing? should we close this?

**Comment by SimonBrandner** [comment]
I don't believe this is relevant anymore. Shout if you disagree
