### ISSUE TITLE
iOS app links don't work if user doesn't have iTunes

### ISSUE THREAD

**Issue by sheldon** [vector-im/element-web#3294]
Update: can't install at all. Details below.

I remove iTunes from my iPhone cause I prefer Spotify as a music service. Trying to open your suggested app for ios tries to open in iTunes, which then forwards to the app store to download iTunes instead of your app.

In the end I can only get your app by installing iTunes or searching manually on the app store. It's a horrible user flow that's eaily fixed by forwarding to the correct app store link instead of the iTunes one.

Cheers for the great work in opening up chat on the Web. Keep at it!

**Comment by sheldon** [comment]
![img_0636](https://cloud.githubusercontent.com/assets/13083/23203446/d9cfe4d0-f8e2-11e6-999e-2283cd2c4bd3.PNG)

To make thing worse, search for your name maybe isn't the best. Riot is the biggest gaming company on PC by number of users playing LoL.

**Comment by sheldon** [comment]
![img_0637](https://cloud.githubusercontent.com/assets/13083/23203539/365c3dfc-f8e3-11e6-8c79-3d7d8c623340.PNG)

Sorry for the spam, but I can't find your app on the app store at all. :(

**Comment by ara4n** [comment]
try searching for Riot Chat? or use the link from riot.im? looks like we should improve our search rankings...
>

**Comment by sheldon** [comment]
The link doesn't work I'm afraid, that was the whole point of the post. There's details from Apple here: https://developer.apple.com/library/content/qa/qa1633/_index.html

It's basically just a domain switch in your url to make it adhere to apple standards and work correctly.

Thanks for the heads up about the riot chat search string, that worked! :)

**Comment by ara4n** [comment]
@sheldon Hm. i'm not sure i'm following precisely which URL is failing to work for you - i'd expect the itunes.apple.com one to work even if you don't have itunes installed.  does https://appstore.com/riotopensourceteamcollaborationviamatrix work for you?

**Comment by sheldon** [comment]
Hey @ara4n 

appstore.com does work yes, since it opens in the iOS "App Store" app, which can't be uninstalled from an iPhone.

itunes.apple.com has this behaviour:

1. Touch link (https://itunes.apple.com/us/app/vector.im/id1083446067)
2. Click dialog to restore iTunes (users mind: wtf, that's not what I want)
3. App Store opens with iTunes app ready to reinstall it (users mind: am I really going to have to install and download iTunes to get this messaging app)
4. (I gave up here, but I guess the next step is) Install iTunes
5. Go back to website with link and click it again (or search on iTunes for riom.im)
6. Install riot.im

Pics below. That flow is so awful (and definitely caused by crazy behaviour from Apple, not really your fault) that I'd call it a bug.

![img_0678](https://cloud.githubusercontent.com/assets/13083/23585254/938eaad4-0179-11e7-96ae-2e22e2789e6d.PNG)

![img_0679](https://cloud.githubusercontent.com/assets/13083/23585255/977bfab6-0179-11e7-8381-a8fc3ef953f8.PNG)
