### ISSUE TITLE
Device IDs overlap in UDD if the window is too narrow

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3296]
![2017-02-22-101720_512x177_scrot](https://cloud.githubusercontent.com/assets/6750344/23207780/646e7a1e-f8ea-11e6-8b4a-1f603970d74b.png)

**Comment by MadLittleMods** [comment]
This looks fixed nowadays in the right panel. Clicking each session gives options to verify.

![](https://user-images.githubusercontent.com/558581/131802914-8144378d-ef3a-4572-95bf-ec2a5f4fee48.png)

![](https://user-images.githubusercontent.com/558581/131803046-29c95273-b560-4b73-a4dd-4ca22458ff47.png)
