### ISSUE TITLE
add ability to save rageshake logs locally

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3304]
as suggested by lazz https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1487800184342672TpnWN:matrix.org.  It could also help with timeout issues as the user could figure out some alternative way of sending logs

**Comment by ara4n** [comment]
@kegsay was this something you considered at all during the impl, ooi?

**Comment by Kegsay** [comment]
I don't know how you plan to save the logs to disk, but the logs themselves are gathered completely in-memory in [this array](https://github.com/vector-im/riot-web/blob/master/src/vector/rageshake.js#L460) so it should be easy to then write these to files if there is a way you can do that in browsers.

**Comment by shirishag75** [comment]
did you mean https://github.com/vector-im/riot-web/blob/master/src/vector/rageshakesetup.js as https://github.com/vector-im/riot-web/blob/master/src/vector/rageshake.js#L460 doesn't seem to be anymore present.

**Comment by Kegsay** [comment]
Yeah, I should've linked to a static commit, my bad. [Here you go](https://github.com/matrix-org/matrix-react-sdk/blob/259d3608ee1cff18c866aaddb8586dc34530a440/src/rageshake/rageshake.js#L455)

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3849 is an attempt at getting the logs at least into an archive and downloaded. Per the PR, it works fine in Firefox but Chrome hates it.
