### ISSUE TITLE
add option to view images full-size in lightbox

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3323]
For very large pictures, the lightbox view may still be too small.  It would be nice to be able to view the full-size image (with scrolling) if the image is bigger than the size available in the lightbox.  Currently, the only way to view the image full-size is downloading the image.  Especially needed for electron app.

**Comment by ara4n** [comment]
surely this is /only/ needed for the electron app? given on the webapp, opening it in its own tab lets you scroll around?

**Comment by ara4n** [comment]
oh, or is the problem that the button to open in its own tab is labelled 'download image' rather than 'view fullscreen' or similar?

**Comment by uhoreg** [comment]
well if #3322 get fixed in such a way that the webapp also downloads, instead of opening in a new tab, then this issue would also be needed for the webapp.  Otherwise, yeah, it would only be needed in the electron app.

**Comment by uhoreg** [comment]
I would imagine that one relatively easy fix for this would be as follows:

1. when the lightbox is shown, check the original size of the image
2. check the size of the lightbox area
3. if either the image's height or width are smaller than the lightbox's height or width respectively, show a magnifying glass toggle button
4. when the magnifying glass is toggled on, then add a class to the image that will override the max-width/max-height styles and allow the image to be full-size; when the magnifying glass is toggled off, remove the class
5. add "overflow:auto" to the lightbox display area so that the image will be scrolled
6. whenever the browser window is resized, re-check the size of the lightbox area

**Comment by pavi** [comment]
Its a very annoying bug for users with low resolutions. 💻  The issue gets worse when we actually use Riot Desktop for sharing screenshots. The low resolutiom implies there is no way someone can see the screenshot and make sense of text inside. 😭 
![screenspace-wasted](https://cloud.githubusercontent.com/assets/971668/25112181/ddc7da24-23ef-11e7-9754-1e03121db747.png)

**Comment by pacien** [comment]
What about using the user's entire screen using the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)?

Displaying "full" pictures using a lightbox in the same window that caused the original image to be scaled down is a bit useless.

**Comment by t3chguy** [comment]
> What about using the user's entire screen using the fullscreen API and Element.requestFullscreen?

This doesn't get great UX,
sure it shows it on full-screen but you have no obvious way to close it (in electron) you have to press Escape. There's also no maginifier functionality

**Comment by pacien** [comment]
> sure it shows it on full-screen but you have no obvious way to close it (in electron) you have to press Escape.

`.exitFullscreen()` when clicking on the "X" in the top-right corner like with the current lightbox?
Riot-web could take some inspiration from the way Telegram desktop shows full-screen images.

**Comment by nmalcolm** [comment]
I'm surprised this has been open for 4 years considering how painfully annoying it is. The lightbox is pretty much useless and I'd quite rather the option to open the image in my browser at this point.

**Comment by danger89** [comment]
Yes please, especially useful on the element-desktop client!
