### ISSUE TITLE
Long tag names don't wrap nicely

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#3332]
### Description

Room sections with long names overflow their container. This can only be reproduced through using the [tags API](http://matrix.org/docs/spec/client_server/r0.2.0.html#room-tagging).

### Steps to reproduce

- Use the tags API to create a long tag name (script [here](https://gist.github.com/turt2live/697d5b3781fb7ab7e11d704ea90e3dbe))
- Note that the UI doesn't wrap/handle the long name nicely

Log: not sent

![image](https://cloud.githubusercontent.com/assets/1190097/23370019/8876614e-fcd0-11e6-9748-ec2f86f71e03.png)

It looks somewhat okay when mushed together with other headers though:
![image](https://cloud.githubusercontent.com/assets/1190097/23370189/220e0f6e-fcd1-11e6-976f-dd63f5c8c61d.png)

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome 56
- **OS**: Windows
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
this isn't really a bug given custom tags aren't really a thing yet. it'll get fixed when we sort #1373

**Comment by turt2live** [comment]
goodbye tags, hello spaces.
