### ISSUE TITLE
display name with hyphens / underscores in causes display name push rule to fail

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#3337]
User with display name 'steve-_-' reported channel icon not turning red on mentions - worked when display names changed to contaisn just letters

**Comment by kittykat** [comment]
Resolved:

![Screenshot from 2021-11-04 09-12-09](https://user-images.githubusercontent.com/51663/140287641-10f310f8-ecf9-4243-a017-777e2eb92352.png)
