### ISSUE TITLE
content previews for permalinks

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3356]

**Comment by robintown** [comment]
https://github.com/vector-im/element-web/issues/22268 related

**Comment by t3chguy** [comment]
I'm wondering if this issue is just about URL previews, 2017 was a long time ago, probably before they were implemented.

**Comment by ara4n** [comment]
no, this is literally asking for us to have URL previews for Matrix permalinks - so that if someone permalinks to a message, you get some meaningful preview rather than a fugly https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$hnn2l_h4UkWyVXGyfFEJxmYaOqrgwpUm9RACn5q9DVw?via=matrix.org&via=envs.net&via=mozilla.org style URL.

However, it is effectively pretty much a duplicate of https://github.com/vector-im/element-web/issues/10478.

(Please don't close issues just because 2017 was a long time ago...)
