### ISSUE TITLE
camera stays on until you close the riot tab

### ISSUE THREAD

**Issue by sbts** [vector-im/element-web#3369]
ken reports this for stable. Develop untested as yet

**Comment by ara4n** [comment]
this may be related to ye olde lost https://github.com/vector-im/riot-web/issues/170

**Comment by lampholder** [comment]
Tenuous security tag here - not really a security issue with Riot, but anything that normalizes camera light being on without conscious user choice to continue using the camera is problematic.

Otherwise assigning the same priority as #170.

**Comment by ara4n** [comment]
@sbts: this is too ambiguous to be able to action. was this on 1:1? conf calling? what browsers? repro steps?

**Comment by kenb0t** [comment]
One to one, Firefox and chrome. Start a video call in an encrypted chat. After ending the call, light stays on

On March 9, 2017 9:04:18 AM EST, Matthew Hodgson <notifications@github.com> wrote:
>@sbts: this is too ambiguous to be able to action. was this on 1:1?
>conf calling? what browsers? repro steps?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3369#issuecomment-285359251

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lukebarnard1** [comment]
I've tested this with an encrypted (over federation) 1:1. It seems that the event to end the call fails to be decrypted (because it appears to be a duplicate?)
```
Error decrypting event (id=$14912279262151075nwkVc:matrix.org): DecryptionError[msg: Error: Duplicate message index, possible replay attack: czemKv7SF771WKjSlLLMN9qsNxlmopP2jZa6rPCCdlg|7KvbDp2tFP4hPcvrb9d4xW9BCNKZIxugOzqroPSZmMQ|12, session: czemKv7SF771WKjSlLLMN9qsNxlmopP2jZa6rPCCdlg|7KvbDp2tFP4hPcvrb9d4xW9BCNKZIxugOzqroPSZmMQ]
EventTimelineSet.addLiveEvent: ignoring duplicate event $14912279262151075nwkVc:matrix.org
... a few seconds pass ...
Starting load of AsyncWrapper for modal
AsyncWrapper load completed with ViewSource
Ice connection state changed to: failed
Ending call c1491227909976
queuing pause on remoteVideo and element [object HTMLVideoElement]
queuing assign on remoteVideo element [object HTMLVideoElement] for null
queuing pause on remoteAudio and element [object HTMLAudioElement]
queuing assign on remoteAudio element [object HTMLAudioElement] for null
queuing pause on localVideo and element [object HTMLVideoElement]
queuing assign on localVideo element [object HTMLVideoElement] for null
Call state in !TCJqMqxxBZLWywVJrY:matrix.org changed to stop_ringback (ringback)
stopAllMedia (stream=MediaStream)
```

**Comment by lukebarnard1** [comment]
I shall un-assign myself as I cannot take further action without more information

**Comment by ara4n** [comment]
@lukebarnard1 but does the camera stay on?

**Comment by lukebarnard1** [comment]
No, the state of the AV in the browser appeared to be updated as the UI did, it just didn't happen immediately.

**Comment by SimonBrandner** [comment]
@sbts, I can't reproduce this. Is this still a problem?

**Comment by SimonBrandner** [comment]
I will close this as I can not reproduce this and there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.
