### ISSUE TITLE
Community UX feedback from GNOME devel land (metabug)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3373]
Metabug to ensure we don't forget the UX feedback from the GNOME community (albeit most of that links straight back here :D)

https://wiki.gnome.org/Initiatives/Matrix/Feedback

**Comment by tessgadwa** [comment]
Thanks @ara4n  this is a great resource. I will add to the general UX thread.

**Comment by taw00** [comment]
My GNOME desktop stuff for the riot RPMs I build...
https://github.com/taw00/riot-rpm/tree/master/source-riot-extras-desktop/riot-extras-desktop/extras
