### ISSUE TITLE
public roomlist 50x error turns up during registration on conf.matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3377]
...despite you seemingly never trying to load a roomlist :(

**Comment by ara4n** [comment]
@lukebarnard1 is the RTS code trying to load the public room list during registration somehow?

This feels vaguely similar to #3371 in terms of unexpected APIs & pages being called at unexpected times...

**Comment by ara4n** [comment]
(#3327 is the actual 500 here)

**Comment by turt2live** [comment]
I think we fixed this, at least RTS is dead.
