### ISSUE TITLE
Unsent images need some indication that they're unsent

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3391]
Images that are unsent appear to have been sent (whilst `color: #f44` is set on the `EventTile_unsent`, there is no text to be `#f44`)

Also, the "Resend" status bar does not appear for unsent images.

**Comment by lampholder** [comment]
Bumping to P3 now it's in the same state as https://github.com/vector-im/riot-web/issues/4531 - the big "some messages haven't sent" bar does most of the work.

**Comment by lukebarnard1** [comment]
But apparently
>Also, the "Resend" status bar does not appear for unsent images.

**Comment by lampholder** [comment]
Ugh, then P2

**Comment by robintown** [comment]
Closing since we now have actual sending indicators
