### ISSUE TITLE
bad things happen when you hoverover a GIF if the preview loaded and the GIF doesn't

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3398]

**Comment by ara4n** [comment]
it flickers badly - as per mxc://sw1v.org/gMIxluaqaYUQUGSWQkTBtnrV

**Comment by lampholder** [comment]
I don't know how to resolve that link, so I wasn't able to make a judgement call on how offensive this behaviour is.

**Comment by MadLittleMods** [comment]
Seems to work fine nowadays whether loaded or not ⏩


![](https://user-images.githubusercontent.com/558581/135146343-ba5da6f6-7378-4bc7-88fc-604d79eb8a07.gif)


In the lightbox:

![](https://user-images.githubusercontent.com/558581/135145566-1c066088-4925-4b62-b375-006aaecc1135.png)

![](https://user-images.githubusercontent.com/558581/135145585-32075ced-832a-49ab-8191-4b9f1bd5a9bf.png)
