### ISSUE TITLE
Make FilePanel work with e2e crypto

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3412]
We should extend the indexeddb stuff to let locally referenced attachments show up in FilePanel.

See also #2591

**Comment by ylecollen** [comment]
Done on the android client.

**Comment by ara4n** [comment]
as #3679 shows, this is a bit surprising - i'd expect the e2e contents to be decryptable in the sidepanel if they can be decrypted in the main panel!

**Comment by thoraj** [comment]
Is this deemed a wontfix?
With e2ee enabled by default perhaps this should be addressed?

**Comment by turt2live** [comment]
It's on the list of things to improve now that we have e2e by default. Anything we don't plan on fixing is closed.

**Comment by t3chguy** [comment]
Am confused, we have this now powered by Seshat in riot-desktop. What's there to improve?

**Comment by aaronraimist** [comment]
Both filepanel and search need some kind of warning in Riot Web that nothing came up because you aren't using Riot Desktop.

**Comment by t3chguy** [comment]
Sure, keeping in mind that rooms don't always start off encrypted so the plaintext ones still can exist and be shown

**Comment by aaronraimist** [comment]
Right but if the room is encrypted there should be a warning below any unencrypted items saying something along the lines of "There may be more files but Riot can't find them because..."

**Comment by thoraj** [comment]
I'm a bit confused. 

Isn't this issue about getting the FilePanel to show links to all files (rather than showing a notice about possibly missing files?)

After all, the main message area can show the links, so I think users will be surprised if files may be missing in the FilePanel?

**Comment by t3chguy** [comment]
> Isn't this issue about getting the FilePanel to show links to all files (rather than showing a notice about possibly missing files?)

This is already done in riot-desktop using Seshat as stated above. On riot-web it'd be a very expensive operation which might literally not be done and instead an explanation of why its infeasible and a link to riot-desktop might be provided instead.,

**Comment by kittykat** [comment]
What are the acceptance criteria for this task being resolved? I have two related problems, but I'm not sure if this task covers them:

1. element-web does not show me encrypted files in the "Show files" part of FilePanel, but it does tell me to go use the desktop app (as mentioned above).

2. The desktop app does not show me files for some encrypted rooms (I don't know when the encryption was enabled, but I suspect on room creation as it's now the default and the room is recent). Desktop app on left, web to the right:
![Screenshot from 2021-08-11 12-10-01](https://user-images.githubusercontent.com/51663/129019368-2034edfc-00af-4a46-b24b-9e9ac9a58584.png)

These same images show up in the right place on Android

**Comment by ara4n** [comment]
The desktop app should in theory support FilePanel in E2EE rooms these days.  If it's not working there on some rooms, let's open a new bug to track it.
