### ISSUE TITLE
Notification sound plays even when active in the conversation

### ISSUE THREAD

**Issue by mvintila** [vector-im/element-web#3434]
### Description

When in a conversation / 1 to 1 room, the notification sound plays on every received message even if i the tab is in focus and you are active in that conversation.

### Steps to reproduce

- Set notifications to "noisy" on "Messages in one-to-one chats" and on "Messages containing my name".
- Start chatting with someone in a one-to-one chat or be mentioned in a bigger room.
- Stay in that window/tab/room.
- Notice the notification sound playing on every message received.

Expectation would be that sound doesn't play when you are active in the conversation.

If notifications are set to anything but noisy, no sound is played at all, regardless of the window being in focus or not.

### Version information

- **Platform**: Desktop

- **OS**: Ubuntu Linux 16.04
- **Version**: 0.9.7

**Comment by lampholder** [comment]
Flinging this question at @dbkr - do you know whether this is the designed behaviour for noisy notifications?

It certainly sounds... noisy :P

**Comment by ara4n** [comment]
i think this is behaving as expected based on reading https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Notifier.js#L224, but it's dumb - we should be surely be suppressing for the room which is active in the foreground (assuming the user isn't idle).

**Comment by dbkr** [comment]
Agreed we should probably suppress notification sounds for the room being viewed when the app is in the foreground and the user isn't idle. Blocker on this is that Notifier doesn't know what room is currently visible.

**Comment by mvintila** [comment]
In my opinion it doesn't really matter which room is in focus, if the app is in focus notification sounds should be disabled.

The purpose of the sound notifications is to let you know that you have messages when away from your device. I would be ok to even mute notifications when you are active on the device (computer not idle, phone screen on, etc).

If the app is in focus i can see the the number of new messages in the left panel (or notification bar on the phone), no need to play sound.

**Comment by t3chguy** [comment]
This should be much easier now with the RVS

**Comment by popsure** [comment]
any update on this? No clue what RVS is, but these notifications are getting pretty annoying.

**Comment by t3chguy** [comment]
RVS=RoomViewStore
and no one is working on this = no update

@ara4n / @dbkr what do you feel the behaviour should be, if window=active && room=active silence the notif, if so I'll get on it

**Comment by popsure** [comment]
personally I don't think it should have anything to do with rooms, if you're using the desktop app of riot, your phone shouldn't be vibrating at any time, its pretty easy to see the notifications in the riot desktop app at that point.

**Comment by t3chguy** [comment]
@popsure that's a completely different issue
the issue you want is https://github.com/vector-im/riot-web/issues/469

**Comment by popsure** [comment]
@t3chguy thanks for clarifying, I got redirected to here from that thread, my mistake.

**Comment by AlexDaniel** [comment]
:musical_note: *PLING!* :musical_note:

**Comment by florealcab** [comment]
This is very annoying for me. Is any fix in preparation for that?

**Comment by squidink7** [comment]
I am still experiencing this 3 years later, I take it not much has happened since.

**Comment by geckolinux** [comment]
Pidgin IM used to have "message starts conversation" and "when in focus" options, which I strongly think should be copied in Riot.

**Comment by henricazottes** [comment]
Same here :(

**Comment by xlrth** [comment]
Please make this change optional. The notification suppression seems to be based on assumptions that can be wrong (unclear if user did recognize new message or maybe already walked away), so not suppressing notifications can have benefits. - Thank you!
