### ISSUE TITLE
Login form: Clicking "Create a new account" resets server settings just entered

### ISSUE THREAD

**Issue by d10r** [vector-im/element-web#3441]
### Description

Login form:
When first switching to a custom server and then clicking "Create account", the changed server settings are reset.

### Steps to reproduce

- Logout from previous account
- In "Sign in" form, select "Custom server" and edit the "Home server URL"
- Click "Create a new account"

At this point I would expect the server url I just entered to persist, but it's reset to the previous state.

### Version information

- **Platform**: web in-browser

For the web app:

- **Browser**: Firefox 52
- **OS**: Ubuntu 14.04
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
This got fixed at some point
