### ISSUE TITLE
Option to hide rooms that don't have unread messages.

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3446]
Currently when a tag is expanded, it will by default display up to 10 rooms in that tag.  However, this may cause rooms further down to be pushed off-screen, and so you may not notice when there are new messages unless you scroll down.

One possible solution to this is to only show rooms that have unread messages (plus the currently-selected room), and hide rooms that have been read.  So, for example, instead of:
![image](https://cloud.githubusercontent.com/assets/1012976/23966849/41e3a0f0-0993-11e7-8b87-22015d9ecbb0.png)
the room list might display something like:
![image](https://cloud.githubusercontent.com/assets/1012976/23967045/e07bf5be-0993-11e7-97d4-84b647860864.png)

So the list will only take up as much space as it actually needs for you to catch up on messages, allowing other rooms from lower down to show up.

**Comment by lukebarnard1** [comment]
In your example if you click on Matrix HQ, will `#elixir-lang` disappear ?

**Comment by uhoreg** [comment]
Yes (maybe with a fancy fade/collapse animation so that it isn't too jumpy and/or maybe after a short delay).

**Comment by lampholder** [comment]
I like the idea, I think the disappearing room would need careful handling so as not to be confusing (fading/collapsing is still a little confusing I think).

**Comment by lukebarnard1** [comment]
If it's optional, I think it could be quite useful. Maybe it could be some special filter option alongside the text filter.

**Comment by ara4n** [comment]
i would really like this (especially on experimental)

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/7185
