### ISSUE TITLE
Dragging from people section to rooms doesn't behave as expected

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#3449]
Should un-set the DM flag, but doesn't, so basically doesn't really work.

This is because of https://github.com/matrix-org/matrix-react-sdk/pull/754

**Comment by lukebarnard1** [comment]
Copied from matrix-org/matrix-react-sdk#754
> you can drag a "People" to "Rooms", but it won't set the direct chat flag. This is because im.vector.fake.direct != m.direct, sadly.

The subtly I think is in the way DMs are stored on the client.

**Comment by t3chguy** [comment]
We no longer have dnd

**Comment by turt2live** [comment]
I think you meant "Closing in favour of https://github.com/vector-im/element-web/issues/8614" ;)
