### ISSUE TITLE
Github announcements, private repository from my organisation: unable to save repo configurations

### ISSUE THREAD

**Issue by karelvanhecke** [vector-im/element-web#3478]
I am unable to integrate announcements from a repository owned by my organisation. My own private repos integrate without any problems. This happens on all platforms.

The exact error message is: 
`unable to save repo configuration.`

I checked my authorized applications. Scalar has the required permissions for my organisation.

**Comment by lampholder** [comment]
@Kegsay could you take a look at this?

**Comment by jcgruenhage** [comment]
I got the same issue for a public repo, of which I am not the owner, but only a collaborator.

**Comment by Kegsay** [comment]
> I got the same issue for a public repo, of which I am not the owner, but only a collaborator.

Collaborators cannot set webhooks on repositories, so you cannot add announcements on them.

**Comment by jcgruenhage** [comment]
Well, than the integration should not show the repository, right?

**Comment by Kegsay** [comment]
Ideally, yes. The integration doesn't check if it's possible or not (and I'm not even sure GH gives us a way to do this check, would need to check their API).

**Comment by lampholder** [comment]
It looks like there is now support in the github API to get a collaborator's permissions for a repo:

GET /repos/:owner/:repo/collaborators/:username/permission

This to me is right on the boundary between bug and feature - it's certainly unexpected behaviour from the user's perspective. I think we should leave it as a P1 bug - @Kegsay if we can modify the documentation to highlight this known limitation I think we could make a case for it being a P2.
