### ISSUE TITLE
No highlights from IRC users if I change my name on IRC with !nick

### ISSUE THREAD

**Issue by devnoname120** [vector-im/element-web#3487]
### Description

If I change my username on IRC with !nick (so that it's different from my Matrix nick), then I don't receive an highlight notification when people type my IRC name.

### Steps to reproduce

- Change your IRC username with !nick.
- Ask someone to type your new IRC name and hit enter.
- No highlight notification is displayed.

Instead, a highlight notification should be displayed for the new IRC username.

Log: no

**Comment by lampholder** [comment]
@Kegsay - can you confirm whether this is a known limitation or a bug? Thanks :)

**Comment by ara4n** [comment]
It's a known limitation - basically a duplicate of https://github.com/vector-im/riot-web/issues/3362

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/376

**Comment by lampholder** [comment]
Since this is a known limitation of the existing implementation I'm going to class this a feature request.

Tagging as P2 for now (I think this is a reasonably significant limitation on the irc bridge) but happy to be argued down.

**Comment by richvdh** [comment]
worth noting this also bites if there is already an irc user with the same nick as my mxid (my freenode nick ends up as `richvdh1`, since I have a direct IRC connection with the nick `richvdh`).

**Comment by richvdh** [comment]
Also: I think it ties into a more general: "senders should be able to tag mxids for notifications in event metadata", which I'm sure we have as an issue somewhere.

**Comment by Half-Shot** [comment]
This has been fixed in https://github.com/matrix-org/matrix-appservice-irc/pull/650 so can be closed here?

**Comment by MadLittleMods** [comment]
Closing as @Half-Shot linked the fix above and no one has reproduced/commented since.
