### ISSUE TITLE
Inbound invites from unknown users for a call (rather than DM or room) should probably be flagged so we can ring appropriately

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3495]
It's perhaps a bit weird that if Alice calls Bob (and Bob doesn't already have a 1:1 with Alice), he sees a 'Alice is inviting you to a room' rather than 'Incoming call from Alice'

**Comment by lampholder** [comment]
This is super weird.

**Comment by SimonBrandner** [comment]
I don't believe this is relevant anymore, shout if you disagree
