### ISSUE TITLE
Ability to detach video call from main window

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/element-web#3510]
### Description

It would be great if I could detach a video call from Riot into a new window, so I can fullscreen it on one monitor and use the app on another monitor.

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Fedora 25
- **Version**: 0.9.7

**Comment by lampholder** [comment]
This would be very nice to have.

**Comment by PureTryOut** [comment]
This could probably be combined with work on the Jitsi integration?

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15887
