### ISSUE TITLE
there are races where if users place & receive video calls at the same time in the same room, one user can end up on a call that looks like a voice call... but is silently sending video

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3520]

**Comment by lampholder** [comment]
This sounds horrendous.

Is it worth taking a step back and rather than fixing this bug in isolation considering whether it's possible to address these races reliably more generally?

**Comment by lampholder** [comment]
We think there's a bug in the 'two people are calling each other at the same time' logic - likely encountered when resolving person 1's calling using video and person 2's calling using audio only.

**Comment by lampholder** [comment]
Options:
 - default to audio (safe)
 - design a bunch of UI that makes this good

We should probably default to audio when resolving glare for now and do something better later.

**Comment by ara4n** [comment]
@superdump does your recent anti-glare stuff fix this?

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant
