### ISSUE TITLE
We should use browser locale to pick the right default phone number on reg/login page?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3528]

**Comment by lampholder** [comment]
@ara4n I modified the title to clarify what I expect you meant - let me know if I've missed your intention.

**Comment by lukebarnard1** [comment]
This would probably make the browser do a pop-up with "Do you wish to share your location with riot.im?", which I don't think we should do without the user selecting some sort of "get my location" option in the drop down.

**Comment by lampholder** [comment]
Not if we just do it based on IP address - it's just a best effort default, so it doesn't matter that it won't always work.

**Comment by lukebarnard1** [comment]
Ah. Would we use something like https://github.com/arve0/node-geoip-country ?

**Comment by lampholder** [comment]
Don't see why not?
