### ISSUE TITLE
Start Chat and Invite dialog boxes should make it clear what a Matrix ID looks like

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3533]
New users might not know how to form a Matrix ID, so it may be helpful to provide an example for users to follow.

**Comment by uhoreg** [comment]
It might also be helpful to give indications in the input box as to what the current method would be.  For example, when a user starts typing something that looks like an email address, it should give some sort of indication that the invite will be sent to an email address.  This would be helpful to both newbies and to people who are just used to typing in email addresses.

**Comment by tessgadwa** [comment]
Totally agree. Maybe also a concise, non-technical definition of what a Matrix ID is.

**Comment by lampholder** [comment]
The invite box could certainly use some work, and this is definitely something we should consider.

**Comment by kittykat** [comment]
I am going to close this issue for now as there are now examples of what an MXID should look like:

![Screenshot from 2021-09-30 18-08-06](https://user-images.githubusercontent.com/51663/135503039-170fd387-a845-4de0-bfb6-a69287520d08.png)

Please re-open if there is anything else that you would like to see improved with suggestions and tagged X-Needs-Design.
