### ISSUE TITLE
Video attachment don't shrink into the FilePanel and push it out too wide

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3539]
<img width="247" alt="screen shot 2017-03-30 at 10 21 02" src="https://cloud.githubusercontent.com/assets/1294269/24497216/9cd659bc-1532-11e7-8e75-d44a6c33ee3e.png">

**Comment by kittykat** [comment]
Works for me on develop.element.io and latest desktop app. Seems to be resolved now, please reopen if it's still happening.
