### ISSUE TITLE
Drop file here to upload flashes

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3541]
When dragging a file over RoomView, the "Drop here to upload" flashes manically as the cursor moves around:
![gifrecord_2017-03-30_135520](https://cloud.githubusercontent.com/assets/6750344/24505198/f5a828fe-1550-11e7-81f5-3be4625dba4a.gif)

This is because the `dragleave` is being fired at the boundaries of children of the `RoomView`. Perhaps the handler of that event should check that the target _is_ the `RoomView`, and not a target. 
**Update**: that doesn't work because if a `dragleave` is fired as the cursor leaves a child _and_ `RoomView`, the only event that fires is one that has a target = child. So there's no difference between that happening and a `dragleave` happening in the middle of `RoomView`, with target = child.

One solution would not to have children in the node that handles the dragging events - perhaps the aux panel that shows the "Drop here".

**Comment by lukebarnard1** [comment]
Sadly using the `_fileDropTarget` as the thing that triggers `ondragleave` has its own problems. The main one being that it's not the same size as `RoomView` when the window width is great enough.

**Comment by turt2live** [comment]
I can also reproduce this without having to move the cursor around, it just flashes erratically and I'm left hoping that when I let go the files get uploaded and not just dropped on the tab.

**Comment by pafcu** [comment]
@lukebarnard1 Can't seem to reproduce quite as badly on Firefox 57. The only thing that flashes is the icon above the "Drop here to upload"

**Comment by turt2live** [comment]
I'm still seeing this often on Chrome 63 windows 10

**Comment by michi7801** [comment]
I can confirm that this is still an issue in the Safari browser and in the MacOS desktop client
