### ISSUE TITLE
Voice channel like in Discord

### ISSUE THREAD

**Issue by Majaspic** [vector-im/element-web#3546]
Hi

It would be nice if Riot integrate this feature. Voice call and video calls should be different than Skype, make it original :)

**Comment by lampholder** [comment]
Discord supports enabling voice in a channel/room, such that everybody within that room is automatically engaged in the voice chat (with push-to-talk/voice level threshold detection to stop it being a mess of background noise, and users can mute themselves/silence the voice chat).

This would be a neat feature to have, but it would need some thought as to how this could/should exist alongside the existing voice paradigms.

**Comment by Hakker** [comment]
voice channels would be greatly appreciated here as well. It's a great thing since people can simply pop in themselves and don't get called all the time.

**Comment by helmi77** [comment]
It seems as though this feature would turn Riot into the only serious self-hosted alternative to Discord.
I find the idea of having "voice rooms" in general much more appealing than the concept of conference calls - I can join a voice room whenever I want to and see who's available, whereas calls have to be scheduled somehow and may be quite intrusive to the unexpecting receiver.

Looking at the [Discord feedback tracker](https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/10346535-allow-self-hosted-servers) a self-hosted solution is one of the more often requested features. So it might be a decent way to attract more attention to Riot/Matrix.

**Comment by BloodyIron** [comment]
I too would like to see this feature added to riot.

**Comment by BloodyIron** [comment]
Any word on this? March 2017 was original post, now it's 2018 :S

**Comment by BloodyIron** [comment]
@helmi77 I'm very much interested in self-hosting for this function! (if that isn't apparent by now, heh).

**Comment by Half-Shot** [comment]
I'm actually wondering if a good way of fixing this is just having two distinct rooms, where one room might be "voice disabled" where users cannot start calls and another room which is a regular voice enabled room. This could all be done in state fairly easily.

As far as a voice channel goes, that's entirely a UI that discord uses to hide the behind the scenes stuff. All Riot would need to do to emulate that would be to replace the call button with a join button and remove the (frankly silly) dialing noises and music.

**Comment by t3chguy** [comment]
@Half-Shot music and dialling don't exist with jitsi anyway which will be replacing freeswitch which has the music anyway

**Comment by Half-Shot** [comment]
Yup. The only thing I've not yet clarified @t3chguy is whether the Jitsi stuff is all behind the scenes and Riot will build it's UI around it rather than being an ugly widget? 

And I will miss the music :(

**Comment by ara4n** [comment]
the idea is to integrate jitsi transparently, just as freeswitch is today. the mobile platforms do this already. one slight issue is that jitsi is also not working perfectly, but we do also have a plan C (which some day we might make some progress with).

**Comment by BloodyIron** [comment]
So will we need too run our own jitsi servers for Riot to use? Or is it baked in there? I'm not sure.

**Comment by ara4n** [comment]
it will (eventually) support running both your own jitsi and using the matrix.org hosted one.

**Comment by Half-Shot** [comment]
Thanks for the clarifications @ara4n. This has gone off topic a bit and I think that answers everyone's questions.

**Comment by BloodyIron** [comment]
So where are we with this one?

**Comment by LickABrick** [comment]
This feature is probably the only thing holding me back from using it.

**Comment by BloodyIron** [comment]
I would use this at my events if this was put in, still really want this!

**Comment by BloodyIron** [comment]
If there's some way we can have users auto join voice for certain channels (as a property of that channel), that would probably contribute to this functional need. Right now, the only way is "opt-in", which works for many cases, but not all.

**Comment by Majaspic** [comment]
Come on Matrix ! You're going to hurt Discord with this feature

**Comment by Aishou** [comment]
I was recently searching for an open, secure and selfhosted alternative Chat/Social/Voice Platform so i found Riot. 

Please implement this, it would be so awesome to have an good alternative to Discord.. precisely a secure alternative.

**Comment by dessalines** [comment]
Doesn't this already exist? Rooms already have voice / video calling.

**Comment by Extarys** [comment]
I discovered Matrix/Riot a couple of weeks ago and this feature would be a huge plus for ppl to switch over.

**Comment by YouveGoatToBeKittenMe** [comment]
With all the controversy going on with discord right now, I think doing this could really bring in a huge user base to the platform.

**Comment by marienuac** [comment]
this has nothing to do with mumble /... ??

**Comment by pottah** [comment]
> this has nothing to do with mumble /... ??

Maybe a Mumble integration? 👍 I really would like to see something like that^^

**Comment by KonoromiHimaries** [comment]
like as discord https://opus-codec.org/examples/ use opus audio codec

**Comment by berserkwarwolf** [comment]
@helmi77

Riot will never be an alternative for self hosting since installing a synapse server is a pain in the ass and not something anyone can do.

**Comment by BloodyIron** [comment]
@berserkwarwolf yeah I disagree about "never be an alternative"... And so do a lot of other people. Spoiler alert: Systems Administration isn't always easy ;P

**Comment by jryans** [comment]
Please remember to keep issue comments on topic. Thanks!

**Comment by hgouveia** [comment]
I am looking a Self-hosted Discord alternative, this have almost everything but not he Voice channel, should be great to have this feature, probably using **jitsi** to provide the voice room functionality, https://jitsi.org/

this will enable also Video Group chat and Screen share

**Comment by berserkwarwolf** [comment]
> @berserkwarwolf yeah I disagree about "never be an alternative"... And so do a lot of other people. Spoiler alert: Systems Administration isn't always easy ;P

If it's not easy, then it's not an alternative to Discord. Discord is easy. Synapse requires sysadmin knowledge.

**Comment by Erudition** [comment]
@hgouveia Yeah honestly, using Jitsi as a stopgap would be fine for now, plus you get videocall rooms for free if you want

**Comment by tweek91330** [comment]
It already has been said a lot but... Yeah, this functionality would be the most important thing to implement in my opinion.

**Comment by ImGunter** [comment]
Adding this would definetly bring the discord crowd over to riot hope it gets implemented to some extent.

**Comment by saturnaal** [comment]
Group voice channels is the #1 feature that would need to be implemented for me to make the push to move my "community" over to Matrix+Riot. All the infrastructure is ready to go, just waiting on this critical functionality.

Subbing to this thread to watch for future developments here.

**Comment by Per0x** [comment]
Need that too. I don't know why all the developers let Discord take off on its own, slack, rocket.chat, mattermost, etc, all the same. This feature is one of the main reasons why everyone uses Discord.

**Comment by fti7** [comment]
Come on guys, that Feature would be a Discord/Teamspeak/Mumble Killer :-)

**Comment by Q-efx** [comment]
Ah was looking for that feature to set up as a private and company server. Too bad...

**Comment by francisrohner** [comment]
This is what I thought Riot did initially.
If this was the case would immediately make the switch and nag friends to do the same.
🤞 🤞 🤞

**Comment by Per0x** [comment]
@francisrohner Not only friends. My entire business and my friend's business ;)
(Discord would be ideal for business, but: no hosting + gaming oriented = no deal)

**Comment by francisrohner** [comment]
Someone fork it and do it hahahaha

**Comment by MurzNN** [comment]
Here https://blog.discord.com/how-discord-handles-two-and-half-million-concurrent-voice-users-using-webrtc-ce01c3187429 is good article with some description, how Discord implement voice channels using WebRTC, hope it may help with implementation in Riot.

**Comment by tensaimon** [comment]
Just a quick comment to say I too am very interested in this feature, I've been looking at discord for hosting a community (I teach at uni so I'd use it for my students) since people seem to love the functionality, but I'm put off by the security / privacy / business model (let me use for free but sell my data.etc.). issues....

**Comment by francisrohner** [comment]
If I figure out how to install matrix on a VPS I will try to help.
This stuff definitely seems complex though. 
I'm excited by the root of riot-im having control of all your own data.

**0_o**

**Comment by patrolez** [comment]
Also this might help a little bit: https://github.com/Johni0702/mumble-web/tree/webrtc

HTML5 client for Mumble Open-Source server.

**Comment by koalp** [comment]
I would like to see this functionnality, but not as an html widget, so that native clients can also make use of it.

**Comment by hramrach** [comment]
There is https://github.com/mumble-voip/libmumble for native applications.

And it is encrypted: https://wiki.mumble.info/wiki/Features#Encryption

**Comment by wdepue** [comment]
Could you not hack together on a Synapse server a voice channel that was always active and thought it had a person in it constantly?

**Comment by ClusterConsultant** [comment]
This is of great interest to myself and my communities.

**Comment by fti7** [comment]
Native Mumble Integration would be very nice :-)
But this Issue here is p3.... so maybe in 10 Years :-(

**Comment by aWeinzierl** [comment]
Except someone has mercy and provides a PR 👀

**Comment by berserkwarwolf** [comment]
To everyone interested in this feature:

I just realized this issue / feature request is labeled as P3:
 Priority Level 3, which is below 1 and 2. 
And is the 4th most commented issue in the P3 label.

Which means, it will never be implemented. 
LOL, FML. My dream of an open source Discord just shattered.

**Comment by t3chguy** [comment]
This is also an Open source project where anyone can contribute, where p3 doesn't hinder that at all.

**Comment by Per0x** [comment]
@berserkwarwolf One day they may realize the importance of this voice chat room feature. If the goal is to make the community grow, it should at least be p2 but in the meantime, let's not wonder why Matrix remains unpopular.
Today I don't see any advantage in using Matrix/element instead of Rocket.chat for example, and if this project just aims to be an umpteenth text chat project without standing out, it will be eaten up by the competitors that stand out. (which are not open source). 
During the covid lockdown, it was really sad to see absolutely every school, middle school and high school use Discord and nothing else because there was no alternative...

**Comment by berserkwarwolf** [comment]
@Per0x indeed.

Riot / Vector / Element has gone through 3 rebrandings.

If they spent that time, money and effort on adding voice channels and a stupid-simple matrix server installer to enable easy self-hosting and LAN gatherings.

It would dominate the market in no time at all.

**Comment by turt2live** [comment]
I'm locking this for now - the thread seems to be deviating from discussing the feature to discussing priorities, which is not a productive way to keep an issue on the radar.

We're well aware of the ask here and would happily accept a contribution that adds it. We currently do not have bandwidth on the team to do it ourselves, and would like to fix other areas of the app so this kind of feature makes sense.

If you'd like to learn more about our prioritization, visit #element-web:matrix.org on Matrix.
