### ISSUE TITLE
Forward pagination failure in #riot

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3547]
Last night I was reading scrollback in #riot; i then switched to another room; i then slept my laptop.  In the morning I unslept, switched back to #riot, and carried on reading scrollback.  I got to the bottom of the pagination window, and it started to spin whilst fwd paginating.  This went on for a few seconds so I got bored and hit the 'skip to bottom' button.  It is now stuck spinning on fwd paginating, even after switching away & back again:

<img width="1044" alt="screen shot 2017-03-31 at 12 07 21" src="https://cloud.githubusercontent.com/assets/1294269/24548041/e716d33e-160a-11e7-811a-f32af366c650.png">

Logs attached.

[pagination failure.txt](https://github.com/vector-im/riot-web/files/885356/pagination.failure.txt)

**Comment by t3chguy** [comment]
Closing as it is likely no longer relevant due to the amount of changes in 5 years
