### ISSUE TITLE
room colour changes temporarily for guests, even though it claims that guests can't change the room colour

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3549]
A guest user reports in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1490967972120924DAWSS:matrix.org: 'When I go to the room settings, change the room color and press 'Save', I get 'Saving room color settings is only available to registered users' with 2 options: 'Cancel' and 'Register'. I choose 'Cancel', but the room color changes, until the next time I visit the settings.'

**Comment by turt2live** [comment]
Closing due to tinting disappearing from the app.
