### ISSUE TITLE
Failure to merge messages from same sender

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3555]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14910920471154321QMHFz:matrix.org

![screen shot 2017-04-02 at 01 17 11](https://cloud.githubusercontent.com/assets/1294269/24583448/4350a91c-1742-11e7-9332-d4e78a308af7.png)

**Comment by alexmat2on** [comment]
It looks fine in my client:
![](http://i.imgur.com/puafLy3.png)

**Comment by t3chguy** [comment]
This code has been rewritten and now considers time too
