### ISSUE TITLE
Add markdown message preview

### ISSUE THREAD

**Issue by superdump** [vector-im/element-web#3570]
Make it possible to see a message preview when using markdown formatting in order to check it when doing something non-trivial, like one can on GitHub.

**Comment by lampholder** [comment]
How necessary will this be once RTE is standard?

**Comment by hho** [comment]
Mattermost also has this; it'd be a great feature, especially as Element is not using the familiar GFM.

**Comment by ShadowJonathan** [comment]
Discord also has this, albeit "live" in the editor tab.

**Comment by kittykat** [comment]
Duplicate of #20360

I'm going to close this issue in favour of the newer one because that has more detail in the description. Please subscribe to the other issue for updates.
