### ISSUE TITLE
Add guidelines for commits in contribution document

### ISSUE THREAD

**Issue by eternaltyro** [vector-im/element-web#3593]
### Description

Please add a section in our contribution document that lays out good-practices for code commit messages and git best practices.

### Reason

Currently, there's no way to reliably figure out which commit addresses which bug or what each commit is trying to do. The problem is even more compounded when trying to view commit history for Change-logs like here: https://github.com/vector-im/riot-web/compare/v0.9.7...v0.9.8-rc.1

To make this better, we need to have sections in the contribution documents that at a very minimum lay out guidelines for:

- Git commit best practices (squashing, cherry-pick, filter, etc.)
- Git commit message best practices
- Git branch nomenclature - to easily identify which issue the said commit / PR is addressing.

Optionally, we could add CI checks for these.

A commit message could have (a.) one line summary (b.) a short description of the problem it addresses. (c.) a short description of what the fix is and how it solves the problem. (d.) Optional additional comments / TODOs/ gotchas. 

### Examples / Resources: 
- https://chris.beams.io/posts/git-commit/
- https://github.com/planningcenter/commit-guidelines

**Comment by lampholder** [comment]
https://github.com/vector-im/riot-web/compare/v0.9.7...v0.9.8-rc.1 is certainly maddening to read, and 
I do like the idea of our agreeing good practices for commit messages.

@eternaltyro Is your commit message summary not more of a PR-level summary (since a single commit mightn't resolve an issue in its entirety).

I'll take a look at those examples and muse further.

**Comment by t3chguy** [comment]
We now squash merge using the PR title so this is resolved - make whatever mess you want. E_TOO_MANY_COOKS
