### ISSUE TITLE
Limit directory listing items to a couple of lines

### ISSUE THREAD

**Issue by realitygaps** [vector-im/element-web#3601]
### Description

Rooms with very long descriptions take up large portions of the directory listing.

Perhaps room descriptions could be trimmed to 2 lines in the directory listing.

### Steps to reproduce

Add a room with many lines of description to the directory listing (eg. #Mastodon:disroot.org)

All the lines of the description will be shown in the directory listing, taking up a large portion of the listing.

![longdirectory](https://cloud.githubusercontent.com/assets/886287/24904635/5d034240-1eb1-11e7-805d-fec91feef808.png)

### Version information

- **Platform**: web and desktop
- **Browser**: all
- **OS**: all
- **URL**:  all riot instances

**Comment by lampholder** [comment]
Ideally this would be truncated with ellipsis with an option to expand to see the full topic text.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/118099278-eca70080-b3cc-11eb-84c0-9d84c81a5277.png)


Fixed with Spaces
