### ISSUE TITLE
We should never delete private keys without confirming with the user

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3611]
but instead give the user to export e2e keys before they re-log in

**Comment by richvdh** [comment]
closely related to https://github.com/vector-im/riot-web/issues/2671

**Comment by lampholder** [comment]
How often and under what circumstances does this happen?

**Comment by richvdh** [comment]
The macaroon secret key is set in the synapse config. The circumstances were that someone regenerated their config (for some reason which now escapes me) and were then surprised when they lost all their e2e history.

**Comment by lampholder** [comment]
Sounds like the situation could also be improved by some additional documentation/warnings around the consequences of regenerating the config.

**Comment by ara4n** [comment]
`@boli:boli.rocks` just hit a variant of this, after resetting his server due to a corrupt DB, all his clients spontaneously logged out and lost his e2e keys & history :(

I am starting to wonder if we should only ever delete e2e keys on clients if the user consents to it, after an explicit logout - or possibly as a special case if the user really does send out an explicit 'kill my logins' instruction to their devices.

**Comment by richvdh** [comment]
basically this is a request to change the behaviour when /sync starts returning 403s (or whatever). Instead of showing "due to security, you have been logged out", perhaps we should show a couple of options for what to do next:

* preserve your e2e state, and enter new login credentials. In this case we need to be careful that, if the new login doesn't happen, and the app is reloaded, we don't end up in a state where it looks like we're properly logged out but actually have a load of sensitive data sitting in local storage - in other words, make sure we come back to this "your accesstoken is invalid" screen until we get a new one which works correctly.
* forget everything and drop back to normal login screen (as we do now).

**Comment by ara4n** [comment]
This really is a very general problem with our key handling - e.g. @lukebarnard1 just lost all his keys because he clicked on an email validation link which opened in his default browser.

I think the real bug and issue here is that "We should never delete private keys without confirming with the user" - other than for the very special case that the user is explicitly deliberately issuing a 'remote kill' on their account (e.g. because they think their account or device has been compromised).

**Comment by richvdh** [comment]
> "We should never delete private keys without confirming with the user"

That's fine. I just want to make sure that the app is unusable until the user has either (a) successfully logged back in or (b) confirmed that they are happy to delete their keys. In particular, I don't want it to *look* like everything has been cleared when actually there is a load of security-sensitive stuff sitting in the browser.

**Comment by ara4n** [comment]
Another trainwreck instance of this over at https://twitter.com/edefic/status/981597890954121216.

I think the best behaviour would be:
 * clients don’t delete e2e state if they see a 403
 * ideally they show an interstitial “confirm login” modal over the top of the app (not to be confused with a fresh login)
 * separately we have a “log all my devices out” button in settings (which we sortof already have through the bull device editing) - and give the user the option to invoke that when they change their password (#2671). Perhaps this could be a 403 with a special body that tells the client to autodestruct.

**Comment by ara4n** [comment]
(incremental e2e backup would make this slightly less worse, but right now it’s *terrible*)

**Comment by RalfJung** [comment]
I think I also ran into this (https://github.com/vector-im/element-web/issues/23698) -- restarting the browser (which did a logout since I still had cookies disabled for this element instance) seems to have wiped my keys, which is definitely not something that I expected.

**Comment by t3chguy** [comment]
IMO Synapse/servers should default to sending soft_logout=true, and only send false when the user explicitly asked for that to occur.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-meta/issues/1868
