### ISSUE TITLE
lightbox wastes a lot of space

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3638]
The lightbox has a large blank area on the left-hand side that is completely wasted, and the right-hand side is mostly wasted as well, which prevents some images from being scaled up more.  e.g. see https://matrix.org/_matrix/media/v1/download/disroot.org/DwmTeyVhKmsYDvsiGBckTjSH  Images should be allowed to expand into the left-hand side, and it may be better to move the information that's currently on the right-hand side to the top or bottom, where they will waste less space, so that images can use almost the full width of the screen.  (somewhat related to #3323)

**Comment by pavi** [comment]
Adding another image for example ![screenspace-wasted](https://cloud.githubusercontent.com/assets/971668/25112181/ddc7da24-23ef-11e7-9754-1e03121db747.png)

**Comment by lukebarnard1** [comment]
This wouldn't be a problem if proper zooming existed (https://github.com/vector-im/riot-web/issues/3159) I'm not convinced that giving an extra N pixels either side is a solution.

**Comment by uhoreg** [comment]
IMHO, since a (10-line) patch for this issue already exists, and #3159 and #3323 will both likely be harder to fix (and are both tagged as p2, so likely won't see much development time in the near future), I don't think that this issue should be held up while we wait for the others to be fixed.

I don't know if "an extra N pixels" is a fair description, since N may be a significant portion of the usable lightbox size.  For example, looking pavi's screenshots, the left-hand padding is over 1/4 of the width of the preview image, so getting rid of the left padding would allow images to be zoomed in an extra >125%.  Getting rid of the padding on both sides would allow images to be zoomed in an extra >150%.

**Comment by lukebarnard1** [comment]
@uhoreg Fair enough, that _was_ an unfair description. 

I like how twitter does it https://twitter.com/instagram?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor which is similar to as you have suggested.

**Comment by uhoreg** [comment]
@lukebarnard1 that Twitter link doesn't seem to go to the right page

**Comment by lukebarnard1** [comment]
@uhoreg sorry, left it mid-edit. I've now updated it properly.

**Comment by uhoreg** [comment]
Yeah, I think something like that, with the info at the bottom, would waste less space.
