### ISSUE TITLE
Trust the first self-signing key you see for a user (TOFU)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3656]

**Comment by lampholder** [comment]
TOFU == Trust on First Use (not the delicious and versatile bean curd).

**Comment by arthurlutz** [comment]
+1

**Comment by uhoreg** [comment]
With cross-signing coming SOOOON, we should do this via the cross-signing mechanism (minus the "verify all" button).

- the first self-signing key that you see for a person gets trusted (maybe display a lock icon with a question mark), if the user enables TOFU
- any subsequent self-signing key that is properly signed by the previous self-signing key is also trusted to the same degree
- a subsequent self-signing key that is *not* properly signed will display a warning (but allow the user to dismiss it if they really want to)

**Comment by lampholder** [comment]
Renamed the issue to reflect the approach we'll take with cross-signing in place

**Comment by dbkr** [comment]
The behaviour with cross-signing now should be much closer to this, so I'm going to close this - if there's any remaining gap in the functionality there should at least be more specific bugs now.
