### ISSUE TITLE
Show redacted messages in an unobstrusive way (e.g. collapse them)

### ISSUE THREAD

**Issue by rubo77** [vector-im/element-web#3657]
If you redact messages, you now get a large message, that fills the whole width of the screen with the redact-bar:

![riot](https://cloud.githubusercontent.com/assets/1591563/25170314/5f4bb188-24ea-11e7-8525-a49baf1f5a0b.png)

This is not really needed for the reader of the history, better would be an unobstrusive way to show that there were messages redacted like with the joined and part messages:

![riot_redact](https://cloud.githubusercontent.com/assets/1591563/25170807/13b24e6a-24ec-11e7-9469-a13b39fea8da.png)

**Comment by Half-Shot** [comment]
If a fix is going to be implemented, can #3931 be sorted at the same time as per @uhoreg 's suggestion :)

**Comment by t3chguy** [comment]
Talked about this with Nad, this is as simple as `N messages deleted`

https://github.com/vector-im/riot-web/issues/8873#issuecomment-620278429
