### ISSUE TITLE
matrix.to links generated in a code block navigate away from the page

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#3681]
### Description

This is an awkward case. Room aliases automatically get converted to matrix.to links in Riot, however if that alias is in a code block, the link doesn't stay on the page and instead throws you over to matrix.to. This used to work just fine, and kinda makes linking markdown-affected rooms a little annoying.

### Steps to reproduce

- Send a message like `#riot:matrix.org` (include applicable markdown)
- Click on alias

I would have expected that the link work like they do outside of code blocks: bring me to the room, not the matrix.to page.

Log: sent (ticket referenced as github link in description)  

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 57
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
From a little debugging it looks like linkify attaches a local click event handler to it then it being mangled by something removes this handler

**Comment by turt2live** [comment]
This got fixed, somehow

**Comment by turt2live** [comment]
Reopening, just experienced this on /develop with a code block as follows:

```
#linux_gaming:matrix.org
```

The linkifier caught it and made it a matrix.to link, which navigates you away.

**Comment by turt2live** [comment]
and no longer an issue. This is somewhat screaming to be a test case.

**Comment by Half-Shot** [comment]
This is still an issue, ex: https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15528445031027051zpSsW:matrix.org?via=matrix.org&via=half-shot.uk&via=linuxgaming.life

**Comment by turt2live** [comment]
Fixed
