### ISSUE TITLE
Dropdown does not do tab-indexing

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3687]
You can focus the `Dropdown` (such as the `CountryDropdown`) but pressing <kbd>Up</kbd> or <kbd>Down</kbd> (when the menu is not expanded) does nothing. Pressing <kbd>Enter</kbd> _does_ expand the menu once you've focused it, but ideally it would expand on focus.

**Comment by t3chguy** [comment]
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
