### ISSUE TITLE
Invite dialog box is very unclear when you try to invite by email

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3703]
There is no confirmation that it's recognised your email as a valid input.  The autosearch also makes performance terrible

**Comment by uhoreg** [comment]
see also #3533, esp. comment 2 (dup?)

**Comment by lukebarnard1** [comment]
At the moment, this looks like 
![2018-05-16-163140_314x118_scrot](https://user-images.githubusercontent.com/6750344/40127143-a4f59264-5926-11e8-800e-8eb6e3f67fec.png)

Maybe we need a "*Email:* luke@..."

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/8489

**Comment by kittykat** [comment]
I am going to close this issue for now as there is now confirmation that emails are recognised and a validity check is done after user presses "Invite":

![Screenshot from 2021-09-30 18-32-50](https://user-images.githubusercontent.com/51663/135503419-715c48ac-c571-4c81-899a-b333bc1a3279.png)

Please re-open with a clear list of requirements and label with X-Needs-Design if there is still something missing.
