### ISSUE TITLE
 we need a more obvious way to see invite coming in

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#3707]
I keep missing them because they're hidden at the top of the room list. We need a (temporary) notif of some kind, the same way we get an obvious notif for calls

**Comment by uhoreg** [comment]
I think this is #3305 and/or #1649

**Comment by turt2live** [comment]
The badge roll up (#1649) is a lot more clear than before, although a more prominent display would be nice.

Here's what it looks like on /develop right now:
![image](https://cloud.githubusercontent.com/assets/1190097/25321034/a8db247e-2868-11e7-9d9a-29ca05d88ba3.png)
![image](https://cloud.githubusercontent.com/assets/1190097/25321035/ab667fa4-2868-11e7-8cd2-2a7119c4234d.png)

**Comment by dbkr** [comment]
Have we signed off on a design for this? Can I implement it?

**Comment by turt2live** [comment]
At some point the badge rollup regressed away. Would be nice to see that come back in some capacity.

**Comment by t3chguy** [comment]
as in the little chat thing with `!` inside it? @turt2live

**Comment by turt2live** [comment]
Yes @t3chguy 

Also, https://www.bountysource.com/issues/41852234-riot-shows-1-1-conversations-i-left-in-the-right-profile-menu

**Comment by t3chguy** [comment]
this seems to have regressed quite a while back, just checked 0.9.7 rc3

**Comment by turt2live** [comment]
![image 6](https://user-images.githubusercontent.com/1190097/29754442-3898326e-8b42-11e7-811e-d4a31507f8d3.png)

@t3chguy accidentally put the color on the wrong element while trying to restore behaviour. To me, this seems more desirable than just the badge, particularly when considering some people (me) have quite a lot of custom tags and the badge would get lost.

Thoughts?

**Comment by t3chguy** [comment]
/me thinks that `temporary notif` is a perfect task for https://github.com/vector-im/riot-web/issues/4908

**Comment by SimonBrandner** [comment]
This doesn't seem to be problematic anymore
