### ISSUE TITLE
hovering over e2e message in notification panel causes it to shift right

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3715]
### Description

In the notification panel on the right-hand side, when you hover over an e2e message, a yellow bar appears and the left margin (or padding?) increases.

no hover:
![screenshot - 230417 - 11 10 01 pm](https://cloud.githubusercontent.com/assets/1012976/25321111/05f3f210-287a-11e7-9c30-7f9bd99f6b1f.png)

hover:
![screenshot - 230417 - 11 09 06 pm](https://cloud.githubusercontent.com/assets/1012976/25321091/eb552bcc-2879-11e7-87b5-c2998ca0e77f.png)

### Steps to reproduce

- receive an e2e message that mentions you
- open the notification panel on the right
- mouse over

Describe how what happens differs from what you expected.

I would expect the left margin to remain the same

Log: not sent

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.8

**Comment by t3chguy** [comment]
Can no longer repro, the panel has been rebuilt
