### ISSUE TITLE
link to the commonmark spec

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#3728]
... somewhere

**Comment by richvdh** [comment]
or, possibly more helpfully, http://commonmark.org/help/

**Comment by aidalgol** [comment]
I've partially implemented this in aidalgol/matrix-react-sdk@f55d34da68803980b4cecd4cc38da827c88e1c5a; it's just not styled properly.  What icon should be used here?  A generic question mark?  Just some text?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/6833 will deviate us from the commonmark spec so we should no longer wish to link to it.
