### ISSUE TITLE
leaving a room not actively being viewed blocks the whole UI with a spinner

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3739]
spake @pik

**Comment by lampholder** [comment]
I get the spinner, though leaving the room was a quick operation so it wasn't a problem for me.

I guess we've got two potential fixes:
- Make leaving a room happen in the background
- Make leaving a room happen more quickly

@ara4n did you get any sense of how long it was taking to leave a room? Niggling < 5 seconds or enraging > 5 seconds?

**Comment by kittykat** [comment]
It took a fraction of a second to leave a room here, which seems like an acceptable amount of time to wait. I'm going to close this issue for now, please re-open with more details on what would be a suitable solution if you feel that it is still valid.
