### ISSUE TITLE
if your server goes down, when it comes back you get messages long before the keys

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#3754]
... And thus you see decryption failures. Can we ask the senders for the keys, somehow?

**Comment by lampholder** [comment]
@richvdh is this a change to the spec? Is this something you're able and planning to tackle as part of your current efforts, or does it need wider discussion/input from a wider group?

**Comment by richvdh** [comment]
It's a change, or at least an extension, to the current e2e mechanism and/or federation protocol, so if they were specced better, it would be a change to the spec...

As for whether I can tackle it: I'd certainly want to seek input from others in the team before going ahead with an implementation, but either way it's going to be difficult and there is probably lower hanging fruit.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/1123
