### ISSUE TITLE
Synced RM 'jump to unread message' target only seems to update when switching away from and back to a room?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3760]
Testing with two machines on the same account; hit 'jump to unread' on both; went to same place.  Then read down a page on one of them.  On the other, hit the 'jump to bottom' button, which correctly produced a 'jump to unread' prompt.  Hitting the 'jump to unread prompt' however returned to where that client was before, rather than to the new RM offset.  Switching away & back to that room however seemingly made it pick up the new RM offset

**Comment by lukebarnard1** [comment]
I can't seem to repro this with the synapse develop branch.

**Comment by kittykat** [comment]
Mine returns to the correct (new) RM offset so seems to be fixed now. Closing as cannot reproduce.
