### ISSUE TITLE
Paging down or up does not page far enough

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/element-web#3763]
At https://riot.im/develop/#/room/#riot:matrix.org/ for example, before paging down: 

![1](https://cloud.githubusercontent.com/assets/192271/25535464/0c6f658a-2c2f-11e7-910d-bc637c640fed.png)

– the last visible line, which I read, was: 

> get rid of count at a point that everything is muted)

After keying Page Down: 

![2](https://cloud.githubusercontent.com/assets/192271/25535480/204319a8-2c2f-11e7-9a14-aaa73145b4c7.png)

– I have pixelised the four paragraphs, plus the name of the user, that certainly need not be seen twice. 

I guess that it's also unnecessary to show, twice, the other lines that are immediately above

> get rid of count at a point that everything is muted)

I reckon, the last line that is entirely visible before paging should be the first line that is visible after paging.

**Comment by lampholder** [comment]
I'd expect that there's a defined behaviour dictating the amount of "context" we see from the previous screenful after a page up/down. 

If that context were defined as a number of messages rather than a number of lines, a large message could make the end result look funny.

**Comment by lampholder** [comment]
I called this a bug at first, but I had a change of heart - to my mind this is really a suggestion of an enhancement to the current behaviour, which is probably just suboptimal for large messages.

**Comment by grahamperrin** [comment]
Thanks. To clarify: it's also suboptimal with small messages.

**Comment by grahamperrin** [comment]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14960739553393992skHTS:matrix.org

> … minor but (to me) it's a **major** drag when reading. The amount that is paged down seems so wrong, so insufficient, I want to hang half of the _Radio Times_ over the top of my display to work around the issue `;-)`

Joking aside: in the absence of the Radio Times, I experimented with an A4 flyer and https://riot.im/develop/#/room/#freenode_#freebsd:matrix.org in full screen mode on a 1,366 x 768 display. The 'half of' guess was spot-on: with exactly half (105 mm) of the flyer draped over the top of the display, the effect of paging down became acceptable. There's a physical border of ~20mm so let's say …

- each page down should be ~85 mm greater.

**Comment by grahamperrin** [comment]
A relatively quick comparison, using frames from a screen recording … 

## Gitter

![gitter example](https://user-images.githubusercontent.com/192271/31851588-ad8369d8-b660-11e7-9051-73e8982859ca.png)

Page down. What was previously close to the foot is now reasonably close to the head of the window: 

![gitter example paged down](https://user-images.githubusercontent.com/192271/31851589-b7b0b064-b660-11e7-93a1-efb761cf42ae.png)

That's normal, expected. 

## Riot

### Example A

![riot example a](https://user-images.githubusercontent.com/192271/31851599-f631c24c-b660-11e7-87e5-51b216c00f7c.png)

Page down. What was previously close to the foot is far from the head: 

![riot example a paged down](https://user-images.githubusercontent.com/192271/31851600-f6572fc8-b660-11e7-8747-a172fe85b2dc.png)

(The on-screen keyboard is enlarged to emphasise the depth to which Riot falls short of what's expected.)

### Example B

![riot example b](https://user-images.githubusercontent.com/192271/31851601-f677087a-b660-11e7-9aca-dd896d6ba9ab.png)

![riot example b paged down](https://user-images.githubusercontent.com/192271/31851602-f6cefeb8-b660-11e7-9cfa-b1782e87c971.png)

----

If a more detailed comparison is required, I can probably provide the recording in its entirety. 02:27 long.

**Comment by lampholder** [comment]
I think that highlights the issue pretty clearly.

Gitter's page jump is the whole page minus ~2 lines; what was the bottom line becomes the second-from-top line.

Slack on the other hand does scroll the _whole page_ - what was the bottom line becomes the first line off the top of the screen. It animates it pageup/down scroll, though, whereas gitter and riot are instantaneous.

Riot's scroll seems more like half a page (which, on reflection, I actually find makes it very _hard_ to maintain good awareness of where I am as I page up/down because I'm expecting a larger jump).

Two thoughts occur to me: 
- gitter's jump size seems more natural
- I think we could generally have more flexibility if we animated the jump - it makes it _soooo_ much easier to follow along

So maybe:
- impl the animation
- increase the jump size to match gitter's

@ara4n - do you have strong opinions on this?

**Comment by grahamperrin** [comment]
Thanks! 

I'm not sure about animation. 

I sometimes use the keyboard to page down very rapidly. Might the animation feel contentious in that case?

----

Firefox 56 with the Scroll Position Highlight extension: https://youtu.be/QcPR35noYbs

> Using a legacy extension to partially ease a keyboard-oriented issue with the Riot client for Matrix, …

**Comment by lampholder** [comment]
I just tried it in slack and found it comfortable to scroll quickly with the animation.

Then I loaded a long wikipedia page in Chrome (I picked https://en.wikipedia.org/wiki/List_of_Advanced_Dungeons_%26_Dragons_2nd_edition_monsters) and page up/downed that and discovered that Chrome animates its page up/downs anyway, so my guess is that it would be fine even when paging down at speed :)

**Comment by grahamperrin** [comment]
I just realised, <kbd>Space bar</kbd> sometimes results in a page down – far enough (possibly a fraction too far in some cases). 

Is this a new feature? 

Note, <kbd>Space bar</kbd> ceases to have the required effect after (for example) a click on _Jump to first unread message._ If the bar does do something, it's invisible; mysterious. 

Still need proper responses, please, to <kbd>Page down</kbd> and <kbd>Page up</kbd>.

**Comment by elfez** [comment]
It would really nice to see this addressed. I find it really jarring when reading to have to search where on the page I should continue reading from. It's fairly unintuitive that PgDn actually means Half-PgDn in this context.

**Comment by grahamperrin** [comment]
It's exasperating. Using the keys in all other apps then _every_ time I use them in Element, I'm disoriented. I can't retrain my eye/brain for this weirdness :-(

**Comment by grahamperrin** [comment]
@claell thanks for looking at this. 

----

From #8455

> … almost impossible to scroll through them slowly …

This #3763 is debatably worse. Beyond _almost_ impossible, it's **_consistently_** impossible to page normally :-(

### Incentives

I'm _begging_ for a fix and will gleefully throw … let's say £200 at a developer. 

Is [Bountysource](https://www.bountysource.com/) still a popular option, or is something else likely to be more attractive? (The array at e.g. https://en.wikipedia.org/wiki/Category:Crowdfunding_platforms is dizzying.)

[Patreon](https://www.patreon.com/), maybe? 

TIA

**Comment by grahamperrin** [comment]
How can this be an _enhancement_? 

Page Down does not page down. Page up does not page up. 

https://github.com/vector-im/element-web/issues/3763#issuecomment-425702601

> <kbd>Space bar</kbd> sometimes results in a page down

In reality: I **never** attempt this workaround, because the space bar typically begins typing a message. 

----

/me abandons hope of a fix for this bug. 

The group with which I most often communicate chose Discord, which has a web app that works with keys.

**Comment by grahamperrin** [comment]
https://github.com/vector-im/element-web/issues/3763#issuecomment-298261669

> … probably just suboptimal for large messages.

No, it's everywhere that longer than two pages, and I can't think of any channel that has less than two pages of messages. 

I can't emphasise this enough: 

* **every** strike of <kbd>Page Down</kbd> does something **wrong**
* **every** strike of <kbd>Page UP</kbd> does something **wrong**

– every time, every day, every week, every month, every year for more than five years.

**Comment by grahamperrin** [comment]
Cool! 

Now, given the pull request, satisfying my curiosity: 

https://github.com/matrix-org/matrix-react-sdk/commit/8b8ee21765722ebebf9558bf293e70881000c7a1#diff-762c0ef38f8d451d35e369a368c94564a7c4c67c84e1952ccf44d7fa64b56742R357

… the half-page effect (exactly `0.5`) was there from the outset. 

https://github.com/vector-im/element-web/issues/3763#issuecomment-304695231

>> hang half of the _Radio Times_ over the top of my display to work around

Genuinely, I used to drape a folded sheet of paper over the display. When I'm not moaning/ranting, I like to do practical things to help myself :-)

![Radio Times 1972-01-01 0 5 rotated](https://user-images.githubusercontent.com/192271/116037226-b55ff200-a65f-11eb-8ae9-47e4c9d78339.png)

Yeah, I'm old enough to remember all of that. Tuppence for a packet of crips, and 5p (decimal money!) for the Radio Times …
