### ISSUE TITLE
allow the user to prefer no more than one avatar per person in a room

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/element-web#3768]
label:ui/ux 

### Description

If I understand correctly: #106 assumes that where person A sets their avatar for the first time, the green circular A – **not** the set avatar – should persist for messages that were posted by that person before the change. 

From the perspective of person B I find that confusing. For me the avatar of a person is simply, **essentially**, the graphical representation of [the user or the user's alter ego or character](https://en.wikipedia.org/wiki/Avatar_(computing)); I associate an avatar: 

- with a user
- not with a point, or a range, in time. 

For me, to find **multiple avatars** for myself, or for any other person, **on a single timeline**, is counterproductive. It goes against my wish to form a mental picture of a person. Multiple avatars = multiple personalities, which might be what's intended by person A, but such inconsistencies make it difficult for me to put thing in context. 

Adding a user preference should satisfy both: 

- people prefer to see multiple avatars per-person on a single timeline
- people (like me?) who prefer to see just one per person on the timeline. 

Thanks

### Clarification

This request is not to discourage any writer from changing his or her avatar. 

This request is to allow the reader to see just one avatar for the writer: the avatar that was most recently preferred by the writer. 

### Cross references

#660 – User Settings refinements 
#106 – Historical user avatars can be buggy 
#2984 – General UX Thread

**Comment by lampholder** [comment]
I'm of a similar mind, but it is interesting that the first reaction was a thumbs-down - do some users have a strong preference for enforcing temporal avatar associations?

**Comment by ara4n** [comment]
temporal avatars and displaynames are a very conscious choice in Matrix (just as in twitter & facebook they aren't temporal).  Matrix rooms are effectively an immutable record of a conversation, which may be on the public record.  Showing the correct avatars for historical conversations are critical, in my opinion, to correctly reflect the conversation that happened (especially if that conversation happened to be about the avatars, which happens relatively often)!

This is why we very deliberately preserve them.  Of course, a client could chose to ignore historical avatars if it so desired, and if someone added an option to riot to do that we'd probably merge it, but it's far from vital imo.

**Comment by grahamperrin** [comment]
[user pill shows current avatar/displayname instead of what it was at the time the message was sent · Issue #4677 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/4677)

To me, showing the current avatar is a feature.

**Comment by turt2live** [comment]
ftr: we have a labs flag for this coming up. https://github.com/matrix-org/matrix-react-sdk/pull/7815

**Comment by T-bond** [comment]
If this feature gets merged, I hope that it will be optional. I also like very much the historical avatars, and I always wanted that in other messengers.

**Comment by turt2live** [comment]
part of the reason for the labs flag is to explore which preference, if any, the product team has based on user feedback. Generally we shy away from adding options, preferring instead to make sensible decisions in favour of the product direction.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22336
