### ISSUE TITLE
Option to change width of screen, linespacing and font (fixed/proportional)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#377]
Lots of powerusers are overriding this with userstyle; would be kind to make it a UI option.

**Comment by richvdh** [comment]
Should this include font size too (per #3160)?

**Comment by ara4n** [comment]
part of #660

**Comment by uhoreg** [comment]
Font and size are configurable now.  People don't seem to be calling for configurable screen width any more, and we have some control over line spacing.  So marking this as O-Uncommon and S-Tolerable.

**Comment by t3chguy** [comment]
when this was reported we used to cap timeline width, we don't anymore except on bubble layout which is tracked in https://github.com/vector-im/element-web/issues/21492 - closing as resolved
