### ISSUE TITLE
Small optimisations to registration email.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#3784]
The registration email contains links to Chrome, Firefox and Safari. In truth, all this does is provide more noise for the user to filter when they want to complete registration. If people want those browsers, they can find them easily enough :)

Also, if _Complete email verification_ instead read _Click here to complete email verification_ it would slightly reduce the thinking time required.

**Comment by aaronraimist** [comment]
Not sure where the code is that generates this email but it does now say "Complete email verification".

![screen shot 2018-09-29 at 9 41 00 am](https://user-images.githubusercontent.com/5855073/46247081-dab6f180-c3cb-11e8-836d-6c7796b046d1.png)

Not sure if I agree on getting rid of the links. I actually think it might be helpful to link to the iOS and Android versions as well.

**Comment by kittykat** [comment]
Closing as the current email is very different:

![Screenshot from 2021-08-24 11-39-01](https://user-images.githubusercontent.com/51663/130602737-d3d26c6e-6378-4b38-9a6d-40eaedcbcca1.png)

(Note: did not check adding email to an account without an email associated)
