### ISSUE TITLE
[desktop] Allow navigation via back and forward mouse buttons

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-web#3793]
### Description

Title pretty much says it all. I'd like to be able to use the back and forward buttons on my mouse the same way as I can use them in my browser: to go back to the last room I was in previously / go to the one I went back from again.

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 0.9.7

**Comment by t3chguy** [comment]
Gonna have a play with this right now (with https://www.npmjs.com/package/mouse-forward-back)

**Comment by t3chguy** [comment]
Apparently this now works as some DE's synthesize Alt left/right on Mouse 4/5.

**Comment by jplatte** [comment]
> Apparently this now works as some DE's synthesize Alt left/right on Mouse 4/5.

I'd be very surprised if anything on my system (arch linux, sway) did this, but this now works regardless.
