### ISSUE TITLE
Support Matrix Groups.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3842]
Matrix Groups are the ability to specify arbitrary sets of users, such that you can use them for permissions (power levels, bans), invites, etc.

They could also be used to define room directories (https://github.com/vector-im/riot-web/issues/1847) and welcome pages for a user, although this overlaps with Communities (https://github.com/vector-im/riot-web/issues/2454).  You'll probably end up with communities which you can only join if you're a member of a given group.

**Comment by albuic** [comment]
I don't know where i should post this and if this will be covered by groups/communities :
It could be great to send a "one read" message to a group : the message is marked as read when one of the  member of the group read it.

**Comment by richvdh** [comment]
can we close this?

**Comment by SimonBrandner** [comment]
> can we close this?

I think we can
