### ISSUE TITLE
one-time-key upload/claim is racy

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#3868]
* Alice tries to upload one-time-key, but doesn't get response
* Bob claims the key
* Alice uploads the key again
* Charlie claims the key

Only one of Bob or Charlie can use the key to talk to Alice.

**Comment by richvdh** [comment]
this is super-unlikely, as it requires Bob to claim the key in the window between Alice's attempts to upload the key. Probably not p1 or major.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/1124
