### ISSUE TITLE
Preview rageshakes before sending

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#3879]
I thought I saw this filed already but might have hallucinated it (or confused it with the rageshaked issue).

Users would like to be able to preview rageshake logs before uploading. Seems sensible.

**Comment by richvdh** [comment]
sensible, but non-trivial.

It's not a regression - users have never been able to preview the logs sent from riot-web.

**Comment by lampholder** [comment]
Cool, in which case it's not a bug, either :P

**Comment by ara4n** [comment]
hang on - can we not just provide a link to download the log archive that'll be sent to the server before sending it?  i assume we have it in RAM somewhere, so we should just be able to use https://github.com/eligrey/FileSaver.js/ or whatever trick the e2e attachment downloader already uses?

**Comment by richvdh** [comment]
Hrm, I suppose we can, actually. We have it in indexeddb, and we'd have to build it into a zip file or something for the user to download, but we could do that. 

On 15 May 2017 00:05:27 BST, Matthew Hodgson <notifications@github.com> wrote:
>hang on - can we not just provide a link to download the log archive
>that'll be sent to the server before sending it?  i assume we have it
>in RAM somewhere, so we should just be able to use
>https://github.com/eligrey/FileSaver.js/ or whatever trick the e2e
>attachment downloader already uses?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3879#issuecomment-301346193

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ara4n** [comment]
what about just providing it in precisely the format we make it when sending to the server anyway? anyone smart enough to dissect their logs is smart enough to ungzip something...

**Comment by richvdh** [comment]
It's a bunch of separate gzipped files in the upload. We could give you a download link for each file.

On 15 May 2017 00:21:09 BST, Matthew Hodgson <notifications@github.com> wrote:
>what about just providing it in precisely the format we make it when
>sending to the server anyway? anyone smart enough to dissect their logs
>is smart enough to ungzip something...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3879#issuecomment-301347000

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by uhoreg** [comment]
related to #3304 (and the proposed solution so far would probably fix that issue)
