### ISSUE TITLE
download errors of encrypted attachments are reported as crypto failures - "Error decrypting image"

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#3892]
If you get an error when downloading an attachment (eg because you can't talk to your HS, or because it's on a remote HS which your HS can't access), we try to decrypt the error message, and hence show a decryption error.

---

> ⚠ Error decrypting image

![](https://user-images.githubusercontent.com/558581/200037090-cb355ed7-9126-439c-bff5-fb39581f6d9d.png)

**Comment by richvdh** [comment]
related to https://github.com/vector-im/riot-web/issues/2749

**Comment by dkasak** [comment]
This also happens if your Synapse has the `max_upload_size` setting set to a lower value than the size of the attachment it's trying to fetch from a remote server.

**Comment by MadLittleMods** [comment]
Seems to be the general catch-all image failure in encrypted rooms but to document another cause that @uhoreg mentioned,

> You get the "Error decrypting image" error if it fails to load the file.  Sometimes that can happen if the file is large and it takes a while for your HS to grab it.  I got the same error yesterday on a different image.  Came back later and it displayed the image fine.

Differentiating the root causes to have better a better error message would be great here. No need to conflate and confuse people with encryption buzzwords here. Especially when the error provides no suggestion to fix things.
