### ISSUE TITLE
Link previews can occupy the entire timeline if window width is small

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#3903]
![image](https://cloud.githubusercontent.com/assets/1922197/26002579/00b5c9f6-3728-11e7-8c0c-c00910e2cbc0.png)

**Comment by uhoreg** [comment]
This could be addressed by the same CSS that I proposed at https://github.com/vector-im/riot-web/issues/2894#issuecomment-293391782

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/7897
