### ISSUE TITLE
Riot keeps ringing after answering the call elsewhere

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#3935]
Filed in response to a rageshake bug report.

Possibly related to https://github.com/vector-im/riot-web/issues/1963 and https://github.com/vector-im/riot-web/issues/1964

**Comment by lampholder** [comment]
P2 major because it's super glitchy and disruptive but is (presumably) not happening that often.

**Comment by t3chguy** [comment]
@ubmarco you perhaps want github.com/vector-im/riot-android - this is the repository for the webapp

**Comment by SimonBrandner** [comment]
This should be improved by the new VoIP spec. If any problems arise it makes sense to open a new issue with specific info
