### ISSUE TITLE
Signalling notifications can get stuck as unread permanently.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#3939]
From @AmandineLP:

I have two stuck unread messages in a 1:1 with Yannick which are really annoying. They're call signalling notifs and keep reappearing on every device even if I refresh.

**Comment by SimonBrandner** [comment]
This probably isn't relevant anymore. Shout if it still is

**Comment by lampholder** [comment]
You're doing amazing work - I am genuinely very happy to keep receiving piles of closure notifs for all the old and dusty bugs I'm attached to 😁
