### ISSUE TITLE
if someone speaks in a room while you are dragging it, the room gets redrawn in its old spot

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3947]
and so is visible in two places, as reported by tomsmeding in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14950471621848491cGkll:matrix.org

**Comment by tomsmeding** [comment]
I have this issue in Firefox 53.0.2 on OS X, if relevant.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/8614
