### ISSUE TITLE
the height of the extended context menu in RoomTiles isn't considered when scrolling RoomTiles into view

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#3950]
so you can end up with the bottom of the menu off the bottom of the window :(

**Comment by lukebarnard1** [comment]
This is a known limitation of how we do context menus; the context menu would have to be implemented as a _child_ of whatever was scrolling up or down, but for now they exist in their own container as with Modals.

As a child, they would be able to update onScroll by receiving a new vertical position via a `prop`.

**Comment by turt2live** [comment]
We fixed this
