### ISSUE TITLE
More useful ordering of users in the 'invite user' dialogue

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#3951]
When searching users to invite to a room/start a one-to-one chat, we want the list of search results to be returned in a more intelligent order such that the person you probably want to talk to is higher up the list.

There are several metrics we might want to use when implementing this ordering:
1. how much you have in common with a user (shared rooms, direct message history)
2. presence
3. how active a user is generally
4. how active a user has been recently
5. whether a user is local or federated
6. how often you pick that user from returned search results

- 1 is probably the most useful
- 3 and 4 would have privacy concerns if implemented with server-side support (it feels leaky to be able to ask a homeserver how active a user is)
- 5 is the easiest, and is probably very useful at the slight cost of reinforcing the idea that people have more in common with and more desire to speak with people on the same homeserver
- 6 mightn't be super useful unless you're adding the same user regularly

What approach will give us the best balance between usability improvement and development complexity/cost?

**Comment by turt2live** [comment]
Once https://github.com/matrix-org/matrix-doc/issues/431 is implemented in some fashion, it would be nice (potentially?) to also exclude bots from from the invite dialog, or at least ranking them lower so the first X users aren't bots.

**Comment by lukebarnard1** [comment]
>1. how much you have in common with a user (shared rooms, direct message history)
Not sure why I'd want to DM someone I've alrady got a DM with, but number of rooms in common would be a simple.
 
>2. presence
In practice this would be filtering out those who aren't online. 

>3. how active a user is generally
This would require some kind of historical presence. Could be a heuristic of how many rooms the user is in? (And could be done client-side if only in-common rooms are considered).

>4. how active a user has been recently
Could be a heuristic of how many messages have been seen in rooms in common

>5. whether a user is local or federated
This feels like an early optimisation for when there are 100s of themed HSs and also kinda reduces the value of federation(!) 

>6. how often you pick that user from returned search results
This could be calculated by actually counting the number of member events of user B where user A is the one doing the inviting.

**Comment by MadLittleMods** [comment]
Here is the current invite dialog as of 2022-08-25 which has "Recently direct messaged" and "Suggestions" (based on idk),

![](https://user-images.githubusercontent.com/558581/186762794-80ac5d03-436e-47cc-974e-0cd6291bc3cb.png)

**Comment by turt2live** [comment]
I'd consider this issue fixed with that new invite dialog. When this issue was opened, it was only fed by the server/local search but now we have a real suggestions engine and such.

**Comment by turt2live** [comment]
ftr, the suggestions are based on various metrics which can/do change. Currently, for each potential suggestion a score is applied using the following conditions:
* How active the user is in rooms you share with them.
* How many rooms you share with them.
* How close of a match your search term is to the user.

The ratios are a bit difficult to parse, but generally the idea is "if you talk to/around this person a lot, they're likely to be invited to a new room you just created".
