### ISSUE TITLE
Read receipt sometimes fails to fall down

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3976]
### Description

Sometimes a read receipt fails to drop down from its old position to its new position.

### Steps to reproduce

- Sit around patiently watching read receipts drop

Seriously, though, I have no idea how to reproduce it.  It seems to happen intermittently, and I haven't notice any pattern, other than the instances that I've checked seem to all be for users with no avatar set, but that could just be coincidental.

This screen shot shows the bug:
![image](https://cloud.githubusercontent.com/assets/1012976/26280728/d17fc272-3dad-11e7-9b14-a6138939aba2.png)

Note the blank space in the middle of the bottom row of RRs.  That space opened up to allow the "S" beside Matthew's RR in the top row to drop down into it.  However, it's just sitting there and not dropping.  At the bottom, you can see the inspector.  The highlighted element is the containing `span` for that RR, and you can see that its `style` attribute has `top: -170px`.  It seems like the animation decided to just quit part way through.

The only possibly relevant thing that I can see in the browser's console log is some 404 errors, but I don't know if it's connected at all.

```
WQyplciIqkMkuusGFQvcqgxb Failed to load resource: the server responded with a status of 404 (Not Found)
https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/WQyplciIqkMkuusGFQvcqgxb?width=30&height=30&method=crop Failed to load resource: the server responded with a status of 404 (Not Found)
WQyplciIqkMkuusGFQvcqgxb Failed to load resource: the server responded with a status of 404 (Not Found)
```

Log: not sent

### Version information

- **Platform**: screenshot is from web, but I've also seen it in desktop

For the web app:

- **Browser**: Chrome 56.0.2924.87
- **OS**: Debian
- **URL**: riot.im/staging (0.9.10-rc.1)

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.9

**Comment by lampholder** [comment]
Ummed and erred about major/minor on this - I think it looks super glitchy so it's important to tackle, but I've never noticed it personally (making me quite possibly erroneously conclude that it is not common to see), hence minor.

If lots of people are seeing and noticing this then we could bump it to higher severity.

**Comment by uhoreg** [comment]
Yeah, it happens quite rarely, so minor is probably about right.

**Comment by uhoreg** [comment]
Dropping to p3 because I haven't seen this happen for a long time.  I'll keep an eye on this for a while longer, and if it still doesn't happen, I'll just close the issue.

**Comment by turt2live** [comment]
I honestly see this a few times a day.

**Comment by uhoreg** [comment]
I also just saw it happen again (in 0.12.2).

**Comment by t3chguy** [comment]
as did I @uhoreg 
#riot:matrix.org ?

**Comment by kittykat** [comment]
#9769 should have covered all the fixes needed for this issue, please comment if it's still present  for you.
