### ISSUE TITLE
"Jump to first unread message" does not appear when the Read Marker scrolls off the top while the room is open

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#3988]
### Description

When a room is open and messages are received without the user interacting with the client, the Read Marker line will scroll up with the last message read.  When there are enough messages that the Read Marker scrolls off the top, it looks like there are no unread messages since there is no Read Marker line, and no "Jump to first unread message" bar

### Steps to reproduce

- open an active room
- clear unread messages, if any
- wait for messages to arrive
- watch Read Marker line go up
- wait for it to go up past the top of the screen
- notice that "Jump to first unread message" bar does not appear
- note that if you scroll up a bit, then the "Jump to first unread message" bar will appear, but not until you scroll up

Describe how what happens differs from what you expected.

I would expect the "Jump to first unread message" bar to appear once the Read Marker is off the screen

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome 56.0.2924.87
- **OS**: Debian
- **URL**: riot.im/app (0.9.10)

**Comment by turt2live** [comment]
Sometimes it also doesn't come back when flipping between rooms, and the only way to find it is to scroll up and hope you see a green line, then either aggressively scroll down to get the banner or scroll casually.

**Comment by florianduros** [comment]
@uhoreg Hi! Can you still reproduce this issue ? Thanks

**Comment by uhoreg** [comment]
I haven't noticed the issue recently, but at the same time, I haven't noticed if I've encountered the right conditions to reproduce it.  I'll self-assign this issue to try to recreate it.

**Comment by uhoreg** [comment]
AFAICT, this seems fixed.
