### ISSUE TITLE
Issues with ctrl-w and input dialog

### ISSUE THREAD

**Issue by qbit** [vector-im/element-web#4016]
### Description

ctrl-w breaks input UI

### Steps to reproduce

- type some text
- type something that causes the autocomplete dialog to open
- tab through the autocomplets
- hit ctrl-w before selecting an autocomplete

Once the above steps are taken, send the message, the input dialog will retain chunks of text garbled together. Only way to fix is refresh.

Log: not sent

Screenshot of garbled text:

![2017-05-24-123148_861x73_scrot](https://cloud.githubusercontent.com/assets/68368/26419885/4d184f80-407e-11e7-9a2f-509876c14f33.png)
### Version information

- **Platform**: web?

- **Browser**: Chromium 58.0.3029.110 (64-bit)
- **OS**: OpenBSD -current
- **URL**: riot.im/staging / riot.im/app (has happened on all versions)

**Comment by brycied00d** [comment]
For what it's worth, I have not been able to reproduce this behaviour whatsoever. Pressing Ctrl-W causes the window/tab/electron app to close.
I do have "New Composer & Autocomplete" enabled.

* Platform: web (nativefier/electron)
* Browser: nativefier 7.0.1 (electron "Chrome/50.0.2661.102")
* OS: Arch Linux (reasonably current)
* URL: riot.im/staging (matrix-react-sdk version: 0.8.9-rc.1, riot-web version: 0.9.10-rc.1, olm version: 2.2.1)

@qbit Do you have "New Composer & Autocomplete" enabled? Have you tried another browser?

**Comment by qbit** [comment]
Yes, "New Composer & Autocomplete" are enabled. I haven't tried other browsers.

**Comment by uhoreg** [comment]
@qbit do you have an extension or something that changes your key behaviour in Chromium?  Ctrl-W by default closes the current tab.

**Comment by qbit** [comment]
Sorry, i should have mentioned, the ctrl-w thing is specific to openbsd.

**Comment by uhoreg** [comment]
what does it do in OpenBSD?

**Comment by qbit** [comment]
Back deletes the previous word.

**Comment by filterfish** [comment]
This problem isn't specific to OpenBSD. It's a general unix thing—I think it came from one of the shells (maybe ksh) but I after a quick search I couldn't find a definitive answer so take that with a pinch of salt—that is pretty much supported by all shells and some browsers. Firefox and Chromium definitely support it. There are a load of similar bindings which are incredibly useful (this list is almost certainly incomplete):

`ctrl-h` → kill character backwards (backspace)
`ctrl-d` → kill character forwards (this is also end of file and will exit from most shells)
`ctrl-b` → more one character backwards
`ctrl-t` → transpose characters
`ctrl-m` → return
`ctrl-j` → newline
`ctrl-w` → kill word backwards
`ctrl-k` → kill line from the current position to the end of the line
`ctrl-u` → kill line from the current position to the beginning of the line
`ctrl-l` → clear the screen

I should point out that not all of these are supported by the browsers (`ctrl-[tmjl]` for example).

gtk calls the above binding "emacs" bindings (which is wrong though emacs does have some of the same bindings) and you need to enable them. See [here](http://kb.mozillazine.org/Emacs_Keybindings_(Firefox)) and [here](https://askubuntu.com/questions/124815/how-do-i-enable-emacs-keybindings-in-apps-such-as-google-chrome#233539) for details.

So back to the problem in hand!

# What works and what doesn't

`ctrl-w` definitely breaks the input box. `crtl-u` also breaks it but in a different way. I'm being vague here as I'm not really sure quite how it breaks but when it does it makes Riot almost impossible to use. However I will _try_ and describe what happens.

When you type `ctrl-w` and then enter to send the message the next message you type will not display the first character but it is actually there.

When you type `ctrl-u` nothing happens (all new text is underlined or nothing depending on the mode) but it doesn't clear the input field so previous message (that should be deleted) is overlaid with "Send a message".

`ctrl-h` works as expected though I can make it not work but I haven't worked how to make it not work!

`ctrl-b` doesn't work at all

`ctrl-f` works

`ctrl-k` doesn't work at all

If I had to make a wild guess as to what was going on I would say the state machine behind the input box is getting out of sync with what's actually being typed.

One last thing the above has been test using latest version of both the electron app and running the app in chromium (full details below) AND an older version (v0.9.0) which has a plain input box and it works perfectly.

This problem renders the newer versions useless for me. I have quite severe RSI and my hands are so hardwired to using these binding the text becomes jumbled very quickly.

For me the solution would be to completely disable the editing widget in the input box so the keybindings are interpreted by the browser and not the widget.

If you need any help debugging this I'm happy to do so. I just need to be told what to do. I am a software dev (but I do tend to avoid javascript like the plague ;) so I can recompile and use the browser debugger.


# Software Versions

## Working version
Chromium: Version 61.0.3163.100 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)
Riot: 0.12.2

## Broken version
Chromium: Version 61.0.3163.100 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)
Riot: 65f0bd04

This has been broken for quite some time though I'm not completely sure when it broke.

**Comment by t3chguy** [comment]
We no longer have that RTE so presuming this is fixed. Shout if you still see it.
