### ISSUE TITLE
Update 'protocol list' to sthg more user friendly

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#4032]
in the directory UI, 'protocol list' is pretty obscure, would 'list of networks' make more sense?

**Comment by lampholder** [comment]
@AmandineLP where does that appear? Is it in the top-right dropdown if it's not been populated with a list of homeservers/bridges?

**Comment by AmandineLP** [comment]
I came across the string when translating it, folks told me it was related to the directory, bt I don't know where it is in the UI

**Comment by t3chguy** [comment]
It is now a lot better
