### ISSUE TITLE
avatars in MELS is messed up in Firefox

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#4096]
Compare:

Firefox | Chrome
---|---
![image](https://cloud.githubusercontent.com/assets/1012976/26603770/093d48e2-4556-11e7-8b97-218ebb7ea054.png) | ![image](https://cloud.githubusercontent.com/assets/1012976/26603792/1a7c8910-4556-11e7-9f42-3e9d7223e33a.png)

**Comment by ara4n** [comment]
This is still broken, possibly in a new way, in FF66 :|

<img width="529" alt="Screenshot 2019-05-01 at 19 50 58" src="https://user-images.githubusercontent.com/1294269/57035765-ba456300-6c4a-11e9-812c-ccf95d6ceea4.png">

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2792
