### ISSUE TITLE
Confusing wording when clicking a join link from email

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4097]
### Description

Started a 1:1 chat with an email address. Clicking the email brings you to a landing as shown:
![image](https://cloud.githubusercontent.com/assets/1190097/26604248/f56d465a-4546-11e7-8b30-a405c04cd51e.png)

This is a confusing landing because it's saying "not associated with this account". As a new Riot user it's not clear that I'm currently using a guest account. Instead, I'm wondering how I already have an account and why my email isn't magically associated with it.

### Steps to reproduce

- Invite an email address to a room (that isn't already a matrix user)
- Click link in email
- Land on page as shown above

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: self-built landing as a guest. Also applies to riot.im/develop

Self built commits:
https://github.com/vector-im/riot-web/commit/64a67583e033601aedbc37f2c04c4db7dde1555e
https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by lampholder** [comment]
Assigning this as P1 because invite by email should be a good way for our user base to grow, but this experience is baffling.

**Comment by turt2live** [comment]
This is still the case and has a minor formatting problem. The wording changed and there's no longer a space between the message and email address.
![image](https://user-images.githubusercontent.com/1190097/40140296-d2c4915c-590f-11e8-996b-3133b9c4b61e.png)

As shown though, the origin post still applies.

**Comment by turt2live** [comment]
we obliterated this copy
