### ISSUE TITLE
ILAG: Username availability checker flashes free-taken-free when hitting enter

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4102]
### Description

Might be firefox slowness?

### Steps to reproduce

- Enter a username that is free
- Press enter to 'take' it
- Note that there is a brief flash of red then green again while the captcha loads

Describe how what happens differs from what you expected.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 53
- **OS**: Windows 10
- **URL**: self built
https://github.com/vector-im/riot-web/commit/64a67583e033601aedbc37f2c04c4db7dde1555e
https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by lampholder** [comment]
I wasn't able to reproduce this on ff 53 or chrome-with-network-throttling on ubuntu, or in ff 53 on windows 7.

**Comment by lukebarnard1** [comment]
I've realised what this is! It's a race between the username availability API request and the request to register :grinning: once you've registered, of course the username becomes unavailable.

Once registration has been requested, we should stop updating whether the username is available.

**Comment by turt2live** [comment]
Just had a particularly ugly encounter while testing this (over the span of <200ms):
* Username free
* Username taken
* Rate limit exceeded
* Username free
* Captcha shown
* Captcha required warning

**Comment by turt2live** [comment]
Farewell, ILAG
