### ISSUE TITLE
Let users clone e2e devices for the special case of logout+login?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4104]
It's confusing that if you export your megolm keys, and then destroy the device and create a new one (by logout/login), you get a new device ID.  For this very special case (i.e. on doing a logout where you are destroying the previous device), perhaps we should let the user dehydrate the device entirely so they can rehydrate it elsewhere in future.  Except everything will break if they rehydrate it twice...

**Comment by ara4n** [comment]
that said, @MatrixCoffee just pointed out that we could refcount the logins for a given device ID.  So if you drop the ref from 1 to 0 when you /logout, and increase when you log back in again, we could perhaps prevent concurrent device disasters (especially if you also stored a checksum of a given device state when you dehydrate it by logging out, so that that state can only then be rehydrated a single time in future?)

**Comment by uhoreg** [comment]
related: https://github.com/vector-im/riot-web/issues/3825 (probably a dup)

**Comment by ara4n** [comment]
in theory dehydrated devices fixes this.
