### ISSUE TITLE
after validating an email address, we could skip the 'click continue' confirmation page at the end

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4130]
see https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1496279564743114yxlSC:matrix.org

**Comment by kittykat** [comment]
Closing because link above doesn't work any more and there is no click to continue view now. The post-confirmation page asks user to log in.

![Screenshot from 2021-08-24 09-28-59](https://user-images.githubusercontent.com/51663/130603226-26cde945-54c2-46e6-9f25-03b3d0a3e361.png)
