### ISSUE TITLE
joining a 1:1 after the person left has wrong error msg

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#4133]
It was right at some point, unsure what happened so that the message is wrong now

![image](https://cloud.githubusercontent.com/assets/8582858/26671525/b7cea092-46ad-11e7-8d96-81a0559998f5.png)

**Comment by lampholder** [comment]
@AmandineLP do you remember what the right message was? Can you advise what you would like it to read?

**Comment by t3chguy** [comment]
I don't believe its possible to know what happened, whether the server has gone offline or whether the room was left empty

**Comment by turt2live** [comment]
We now have an improved error message for this case, or at least the server does. If folks are still seeing this, please open a new issue with fresh information.
