### ISSUE TITLE
Offer down-sizing when uploading large images

### ISSUE THREAD

**Issue by zzottel** [vector-im/element-web#4144]
Like Riot Android does.

In encrypted rooms, large images can be a huge nuisance.

**Comment by zzottel** [comment]
See also #2678

**Comment by lampholder** [comment]
Is it tractable to solve #2678?

**Comment by Thatoo** [comment]
That is really missing on desktop compare to android app.

**Comment by popindavibe** [comment]
Any news on this? Just realized today the inconsistency between the Android app and Element-Web on image uploads.

**Comment by ralphholz** [comment]
Seconded - when using different chats and pasting for different audiences, an automatic downsampling would be much appreciated.

**Comment by progserega** [comment]
It is problem, when send big image to mobile clients over element-desktop. Mobile clients said that they get too long time for get images "in matrix", situation was otherwise whatsapp and other - they was more usable.

**Comment by akoyaxd** [comment]
Pasting Images on Element Web is another use case of compression because Images from "clipboard" are pasted as uncompressed png's. Compressing them to jpeg's (with lower resolution) would be super convenient!

**Comment by hebrides** [comment]
It's trivial to compress images to jpgs using the canvas element... can we start here? Anyone know a script we can run on a self-hosted server to accomplish this?

**Comment by hebrides** [comment]
https://yarnpkg.com/package/image-file-resize

https://www.npmjs.com/package/imagemin

**Comment by ShadowJonathan** [comment]
Related; https://github.com/vector-im/element-ios/issues/4479, they're kinda struggling with the same problem, and ios already has pre-existing design/heuristics for this. Plus it's mentioned that android has as well.

**Comment by t3chguy** [comment]
> Anyone know a script we can run on a self-hosted server to accomplish this?

Adding a server-side component to Element would be a no-go. This would need to be local given the nature of end-to-end encrypted messaging.

**Comment by Fuzzillogic** [comment]
Someone just sent me a screenshot of a game, by pasting the screenshot in Element Desktop. It was a 4K screenshot. The resulting png-compressed image was **15MiB**, which is now stored for a really long time on both our servers. The same information could have been conveyed by a **150KiB** lossy WebP, even at 4K resolution; there was no need for a lossless image here.

Microsoft Teams smashes every pasted image down to an ugly jpeg, even when png would be smaller (let alone lossless webp), which is also a bad decision. However, when pasting large images, some more options would be welcome. A default action of scaling it down to HD with lossy WebP compression would be fine in my book.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14047
