### ISSUE TITLE
Explicitly depend on the right version of electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4149]
Apparently we use whatever electron is randomly hanging around, rather than pinning to the version required for the app to actually work

**Comment by dbkr** [comment]
The version is specified in https://github.com/vector-im/riot-web/blob/master/package.json#L147 although this is only for packaging. We could include electron in the electron dependencies, but you only actually need the electron npm package installed if you run it manually.

**Comment by lampholder** [comment]
@dbkr - does that mean this isn't a problem? Do you mean we only need the electron npm package on the target machine if you're _building_ it locally?

**Comment by t3chguy** [comment]
For building you don't need it, just for running a local instance for the likes of development

**Comment by lampholder** [comment]
So is this just tripping up people who develop?

**Comment by t3chguy** [comment]
and those that run riot-web electron without package / packagers

**Comment by lampholder** [comment]
Are there many people in that position?

**Comment by yannicka** [comment]
Has this issue evolved since 2017?

**Comment by t3chguy** [comment]
It has not, riot-desktop does not depend on electron as electron-builder downloads a statically compiled one

**Comment by t3chguy** [comment]
We do this now https://github.com/vector-im/element-desktop/blob/develop/package.json#L60
