### ISSUE TITLE
MELS handles freeswitch conferencing badly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4172]
<img width="917" alt="screen shot 2017-06-02 at 13 20 04" src="https://cloud.githubusercontent.com/assets/1294269/26746990/c90543dc-47ea-11e7-8f95-10da754f88ac.png">

**Comment by lukebarnard1** [comment]
It looks like this is done for normal event tiles via `TextForEvent.js` with some special handling for when an invite has no `third_party_invite` content.

**Comment by robintown** [comment]
Freeswitch conferencing isn't a thing anymore
