### ISSUE TITLE
Squirrel mac loops if runs as unprivileged user

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4187]
https://www.reddit.com/r/privacy/comments/6f8vc2/riot_im_anyone_unable_to_update_it/

**Comment by dbkr** [comment]
https://github.com/Squirrel/Squirrel.Mac/issues/131

**Comment by kittykat** [comment]
I'm going to close this for now as it looks like the issue was resolved upstream and we haven't had more recent reports of it.
