### ISSUE TITLE
infinite spinner after jump-to-last-unread and scrolling down

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#4202]
### Description

Sometimes I get an infinite spinner at the bottom of the timeline after doing a jump-to-last-unread and then scrolling down.  It looks like some of the messages are out of order too, so maybe Riot is getting confused somehow.
![image](https://cloud.githubusercontent.com/assets/1012976/26802451/891ce966-4a0e-11e7-8b6d-26d7cd1e8d1e.png)
E.g. note the timestamps in the screenshot above.

Also, clicking the "scroll to bottom of the page" button doesn't do anything.

### Steps to reproduce

It's not 100% reproducible, but in general what happens is:
- be away for a while
- open a room with a lot of unread messages
- click on "jump to first unread message"
- scroll down

Describe how what happens differs from what you expected.

Log: sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.10.1

**Comment by turt2live** [comment]
I've had this as well, but have not been able to nail down some reproduction steps.

**Comment by lukebarnard1** [comment]
The out-of-order messages are expected, they are displayed in the order that the HS has put them in the DAG (I think).

Infinispinner is unfortunate and I have sometimes seen the same. It suggests the pagination gives up or fails to start but the view suggests that it has started.

**Comment by uhoreg** [comment]
I haven't seen this issue for a while, so I'm going to close this.  Also, wow, Riot used to look so different.
