### ISSUE TITLE
cachebust ILAG home pages correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4239]
the lack of cache busting on the homepage resources is going to bite us monumentally

**Comment by turt2live** [comment]
now applies to the welcome page as well

**Comment by andrewperry** [comment]
Also getting on logout page.

**Comment by jryans** [comment]
What's being affects on these pages? Images? Translations?

**Comment by turt2live** [comment]
Themselves. Old ones can easily be cached.

**Comment by turt2live** [comment]
Closing now that ILAG isn't a thing. This is a technical consideration we can make if we ever re-add the feature (or a similar feature).
