### ISSUE TITLE
submit button on set password dialog is 'change password' not 'set pasword'

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#4303]

**Comment by pafcu** [comment]
@dbkr Has this changed? There is a a section in the user settings, but is there also a dialog for this?

![image](https://user-images.githubusercontent.com/62835/33982813-3cafbeec-e0b2-11e7-8d38-1e86b6aaf155.png)

**Comment by RinkiyaKeDad** [comment]
I'm new to the Element codebase and would like to fix this if someone isn't already working on it. As far as I understad the "Change Password" has to be replaced with "Set Password" right? Thanks.

**Comment by Half-Shot** [comment]
@vector-im/product This has been this way for a very long time, is it still valid?

**Comment by t3chguy** [comment]
Indeed it is still this way, this flow is legacy and only reachable by old ILAG accounts. The reason it is like this is due to a re-use of the ChangePassword component.
