### ISSUE TITLE
no spinner in set email dialog after clicking continue

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#4304]
This is because the dialog gets recreated and so goes back to its original state

**Comment by lampholder** [comment]
Presumably this is quite confusing?

**Comment by kittykat** [comment]
Is this the flow this issue is about?

1. Settings
2. Add email address, Add, Continue
3. See dialog pop up for entering password, Continue with correct password
4. See spinner while it does it's magic before throwing an error because link in email hasn't been clicked
5.

**Comment by dbkr** [comment]
I can't repro this now - possibly our dialogs now stack sensibly.
