### ISSUE TITLE
Would be nice to have theme setting at a per device level

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#4316]
like desktop notifs, all my laptops don't have the same screen so it would be useful to have one in dark and the other in light theme

**Comment by ara4n** [comment]
@t3chguy can haz granularsettings? O:-)

**Comment by t3chguy** [comment]
@turt2live implemented Granular Settings, we are just lacking a UI for this

**Comment by t3chguy** [comment]
This is a thing now
