### ISSUE TITLE
Minimize UI noise in message feed

### ISSUE THREAD

**Issue by bnvk** [vector-im/element-web#4317]
### Description

Using the metric of "messages are the most important info in the message feed" the current state is a tad bit cluttered with less important visual information.

This is the current state of the message view

- [Before Image](https://brennannovak.com/media/snapper/Riot-chat-tweaks-before-2017-06-15.png)

![](https://user-images.githubusercontent.com/558581/131788000-9d231082-6464-4981-bcb4-87db190a79cf.png)

Here is with my proposed changes.

- [After Image](https://brennannovak.com/media/snapper/Riot-chat-tweaks-after-2017-06-15.png)

*[image no longer available]*

Changes specifically relate to **"... joined the room"** messages:

1. Remove shrunken avatars as they are too small to really see anyway
2. Reduce font from `14px` to `12px` as this is not really interesting info and is redundant with list of people in sidebar and status
3. Remove / make configurable the "Seen by" avatars in the right. I suggest tucking this into checkmarks tooltip
4. Shrunk the "user is typing" height a bit to reduce size it takes up

I realize 3. might be contentious as it's modeled after what other messaging clients do. In one-on-one threads this makes more sense, but in large public group rooms it just adds too much noise.

Additionally, I'd suggest making the **hover on message** styling of "joined the room" messages a simple HREF color change instead of the background.

### Steps to reproduce

Just log in and look at any group message feed, it currently looks like this:

### Version information

- **Platform**: web affects all platforms and browsers

---

I'm happy to submit a pull-req with these changes if they are likely to be accepted :wink:

**Comment by t3chguy** [comment]
You can both hide read avatars (3.)
and make the timeline more compact in settings.

![image](https://user-images.githubusercontent.com/2403652/27176458-7e1dcf5e-51ba-11e7-9174-06d1b747cc3b.png)

**Comment by bnvk** [comment]
@t3chguy nifty this has been somewhat worked on already! 

Using **compact timeline** fixes some of the noise, but is actually quite cramped in a different way. Seeing the joined messages is useful, my proposal is just to make it less important in the interface.

I still argue 3. should be more intelligent. Disabling it means I cannot see in private message thread read receipts. Perhaps making it a **"room"** setting with **default off** for public rooms would suffice?

**Comment by t3chguy** [comment]
As to the per-room thing, I have Granular Settings (setting applicable per device/per room on my todo list, just stuck behind some golang stuff right now)

**Comment by grahamperrin** [comment]
Thumbs up to _any_ preference that will allow the user to minimise noise.

**Comment by MadLittleMods** [comment]
The UI has iterated a lot since 2017 and although it probably hasn't adapted to your standard of noise, future improvements should probably be tracked in new invidual issues.
