### ISSUE TITLE
Capitalize titles programmatically

### ISSUE THREAD

**Issue by thanostx** [vector-im/element-web#4322]
### Description

CSS text-transform property creates a regression when the UI is translated in Greek. More specifically capitalized titles have accented letters, as opposed to the Greek grammar that says when a word is displayed in all caps it shouldn't have accents.

### Steps to reproduce

- Login to riot.im/develop
- Choose "Ελληνικά" for interface language

Titles in user settings (Profile, Account, Notifications etc.), as well in the sidebar have Greek capitalized words with accents.

![riot-capitalize](https://user-images.githubusercontent.com/1238816/27177529-5dd80a42-51cf-11e7-8f5d-35bf5f44a3b1.png)

### Version information

- **Platform**: web and clients that are based on that (e.g. Revolt client on Linux)

**Comment by uhoreg** [comment]
FTR, changing the lang attribute on the html element from "en" to "el" does not seem to help (which might be a browser bug?), at least in Chromium.

**Comment by kittykat** [comment]
Capitalisation is fixed now, shame that the translation coverage isn't as good

![Screenshot from 2021-11-16 21-28-50](https://user-images.githubusercontent.com/51663/142068698-ca29110b-c8be-4c89-8921-e6451bc9192a.png)
