### ISSUE TITLE
Hitting HISTORICAL section populates my ROOMS section with rooms I never join and on which my invitation was withdrew

### ISSUE THREAD

**Issue by jeangb** [vector-im/element-web#4331]
### Description
I hit the HISTORICAL section on the left panel do display the historical rooms.
Suddendly the numbers of ROOMS (in the left panel) goes from 17 to 46.
The ROOMS section become populate with some particular historical rooms: they're rooms where my invitation was withdrew and I never joined them.

### Steps to reproduce

I don't know how to reproduce the state of these rooms.
I can show an example of events:
(I'm riotuser3)
```
riotuser2 joined the room.
riotuser2 made future room history visible to all room members.
riotuser2 invited @riotuser3:matrix.org.
riotuser2 withdrew riotuser3's invitation.
```
 The top of the room is 

> You have been kicked from riotuser2 by riotuser2.
> Rejoin
> Forget

Here are some rooms id: !zxDEUHncGWqHYgvCdD:matrix.org !tfcnjuzqYjuvaHlsVl:matrix.org !HeBLrJCaIvfmwLoalH:matrix.org !UWZYeroOoBVwZKftbj:matrix.org
### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome
- **OS**: Mac OS
- **URL**: riot.im/develop / riot.im/app / with matrix.org

**Comment by turt2live** [comment]
This shouldn't happen in the new room list
