### ISSUE TITLE
profile picture image type determined by file name instead of file contents

### ISSUE THREAD

**Issue by nekomancer** [vector-im/element-web#4342]
Profile pictures of unknown image types are not used in rooms. The image type is determined by the file name extension rather than the file's contents. This means that even if the image is of a known type, it does not appear in rooms.

For example, create a PNG image with the name "avatar.png?12345" or "avatar.foo" and make it your profile picture. You will no longer have a profile picture in rooms you are in. Rename the file to "avatar.png" and upload again. Now it will work correctly and your profile picture will appear in rooms.

To correct this, determine the image type from the contents of the file instead of the name.

**Comment by turt2live** [comment]
Related: #3873

**Comment by t3chguy** [comment]
The determination of image type is done by the browser, not by Element. We rely on `File::type`

**Comment by t3chguy** [comment]
Closing as bundling a file magic header sniffer would be unrealistic, we rely on the tools provided by the browser.
