### ISSUE TITLE
Intent to view settings is lost on ILAG

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4348]
* Launch app as guest
* Click settings button
* Enter MXID
* Find yourself in a PM with RiotBot, rather than on the settings page :(

**Comment by lukebarnard1** [comment]
So I thought this would be trivial but this is actually a race between getting a Riot Bot and dispatching the deferred action to view_user_settings.

My inclination would be to rewrite the `do_after_sync_prepared` hack and have some sort of much less generic thing for deciding what to do when registered. Whatever the intended action was, we should be doing this after starting a chat with RiotBot and probably not after preparing the sync. Maybe `do_when_registered`?

**Comment by lampholder** [comment]
If the only functional result of this bug is the loss of the open settings intention I'd say we fry some bigger fish instead :) 🐟  🔥

**Comment by turt2live** [comment]
Related/dupe: #4329

**Comment by t3chguy** [comment]
This is no longer hittable
