### ISSUE TITLE
[UX] Color choices for room is not at all clear as to what it does

### ISSUE THREAD

**Issue by cjdelisle** [vector-im/element-web#4353]
1. Color choice changes the entire UI instead of just the "room part" of the UI, this feels like it should be a global configuration.  Color-tagging the room should be in the elipses icon for that room of the room selector in the left.
2. Because the setting is in the room choices, it feels like this choice will be imposed on everyone in the room but actually it is personal

Recommendation:
1. Allow global color theming which impacts everything
2. Move the per-room coloring to the elipses for the room on the left side
3. Per-room coloring only affects the color of UI elements specific to the room, the global coloring still impacts the left side menu.

**Comment by turt2live** [comment]
Related: #2308, #3139 and possibly #4146

**Comment by tessgadwa** [comment]
Even just changing the name of the setting from "Room Colour" to "Room Label" (color settings directly below) would help with #2.

If you are a new room admin, you would have no way of knowing that other users in the room don't see the color theme you have picked out.

**Comment by turt2live** [comment]
Closing due to tinting disappearing from the app.
