### ISSUE TITLE
Double warning/success dialogs when changing password

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4365]
When changing password in UserSettings, you see 'Warning',  'Success', 'Warning', (spinner in ChangePassword component), 'Success'

Or if the password was wrong, see "Error 401" instead of "Success", but it follows the same pattern

**Comment by tanius** [comment]
In fact, you get "Error 401" also for a successful password change. Here's what just happened, using a Matrix ID not connected to any e-mail address (so no confirmation e-mails were sent – might be relevant for reproducing):

1. Go to "Settings", fill in "Current password / New password / Confirm password", click "Change Password".
2. This warning is shown: "Warning! Changing password will currently reset any end-to-end encryption keys […]". (_Action: click "Continue"._)
3. This message is shown: "Success. Your password was successfully changed. You will not receive push notifications on other devices until you log back in to them." (_Action: click "OK"._)
4. The warning is shown again: "Warning! Changing password will currently reset any end-to-end encryption keys" (_Action: click "Continue"._)
5. This error message is shown: "Error (HTTP status 401)". (_Action: click "OK"._)

After this, the password has been changed successfully, and you are still logged in. So you can sign out and sign in with your new password – worked for me. But obviously the process above is not as designed :-)

**Comment by novocaine** [comment]
Can't reproduce.
