### ISSUE TITLE
RRs should be at Bottom of event tile so can be seen better on taller events

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#4377]

**Comment by turt2live** [comment]
Android does this. Not sure about ios.

**Comment by lampholder** [comment]
I think this would look fine if it were just aligned with the bottom of the bottom line of text in the event.

**Comment by t3chguy** [comment]
@lampholder its more impactful for tall images, imagine this...but taller
![image](https://user-images.githubusercontent.com/2403652/27378038-8418d652-566e-11e7-9691-f9661edf903a.png)

**Comment by lampholder** [comment]
@t3chguy I _think_ we're saying the same thing - that it would be better and more clear (esp. for tall events) if the read receipt avatar were aligned with the very bottom of every event.

**Comment by t3chguy** [comment]
Yep, thats what I mean :)

**Comment by turt2live** [comment]
for the sake of keywords: read receipts

**Comment by turt2live** [comment]
We've had to revert this due to https://github.com/vector-im/riot-web/issues/12660
