### ISSUE TITLE
Time zones don't update in realtime; you have to refresh the page

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#44]

**Comment by richvdh** [comment]
You don't have to refresh; you do have to force a re-render (eg by switching rooms)

**Comment by afranke** [comment]
What are the reproductibility steps? Where and how do you change your timezone? What version of Element can I reproduce this in, and on which browser and operating system?

Is this [the Chrome specific bug that was fixed](https://github.com/vector-im/element-web/issues/207), or something else?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
