### ISSUE TITLE
Synapse groups support

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4427]
Erik is making some changes in Synapse to support the groups/communities work in Riot.

Unordered list:
- [ ] Visibility management of rooms & users & groups
- [x] Validating of membership attestations
- [ ] Group summary edit API
  - [x] Add/remove rooms w/o categories
  - [x] Add/remove categories
  - [ ] Reorder room and categories
  - [x] Add/remove users w/o roles
  - [x] Add/remove roles
  - [ ] Reorder users and roles
  - [x] Hook up federation APIs for all the above
- [ ] Room categories API
  - [x] Local
  - [x] Federation
- [ ] User roles API
  - [x] Local
  - [x] Federation
- [ ] Sync API
- [ ] Adding additional group admins
- [ ] Group admin flags
- [ ] Flairs
- [ ] Knocking
- [ ] Pagination of user and room directories

**Comment by thekyriarchy** [comment]
Will knocking be exclusive to groups or could the feature work for rooms as well? per #491

**Comment by t3chguy** [comment]
This is no longer desired due to the upcoming Spaces Beta
