### ISSUE TITLE
Group/communites directory page

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4428]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

A page that:
- lists the groups of which you are currently a member
- provides some UX to:
    - create a new group
    - request access to a new group

**Comment by turt2live** [comment]
@lampholder This seems done, although the "request access" isn't. That might be worth it's own issue if it doesn't already exist?

**Comment by thekyriarchy** [comment]
how/where does one access the community directory?

**Comment by turt2live** [comment]
The title and description feel a bit mismatched. The description explains the current "My Groups" page.

**Comment by PhieF** [comment]
Something we would need to join an already existing community

![Capture d’écran de 2019-06-06 12-34-28](https://user-images.githubusercontent.com/26841885/59026808-954e9c00-8857-11e9-8126-a5daf49d1368.png)

![Capture d’écran de 2019-06-06 12-34-21](https://user-images.githubusercontent.com/26841885/59026818-98498c80-8857-11e9-944d-93b5fcdbab8a.png)


Then it redirects to https://riot.im/app/#/group/+community:gauchiste.club


If you agree with the design I can try to do it myself and create a pull request

**Comment by c33s** [comment]
@PhieF please do.

**Comment by martindale** [comment]
Subscribed.  This would be huge for our use-case.

**Comment by 0hq** [comment]
Yeah we need this badly.

**Comment by SimonBrandner** [comment]
Spaces are now in beta, so this isn't relevant anymore

**Comment by MurzNN** [comment]
But how now we can view / find spaces in rooms directory page? "Explore rooms" seems shows only Rooms, or mix of Rooms and Spaces? If mix, there must be filter by room type...

**Comment by MurzNN** [comment]
Ow, this issue is only for list of space, where user is member, so ok to close.

**Comment by SimonBrandner** [comment]
For that: https://github.com/vector-im/element-web/issues/17264
