### ISSUE TITLE
Display flair in member info panel.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4438]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

**Comment by novocaine** [comment]
@lampholder can this be closed, as communities is deprecated in favour of Spaces?

**Comment by afranke** [comment]
No. Flairs are still a thing with Spaces.

**Comment by SimonBrandner** [comment]
> No. Flairs are still a thing with Spaces.

There is an [MSC](https://github.com/matrix-org/matrix-doc/pull/3219)

**Comment by t3chguy** [comment]
Closing as Flair will be entirely re-designed.
