### ISSUE TITLE
Display flair in member list

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4439]
[UX Google Doc](https://docs.google.com/document/d/1wv78GqgG59CLjIKPi7GGkdqI6KOeQUBl9Bnf-uA-Kc0)

**Comment by novocaine** [comment]
@lampholder can this be closed, as communities is deprecated in favour of Spaces?

**Comment by afranke** [comment]
No. Flairs are still a thing with Spaces.

**Comment by novocaine** [comment]
> No. Flairs are still a thing with Spaces.

This ticket does not represent "implement support for Flair in Spaces", it is a specific UI detail of a feature we are deprecating. When flair is added to Spaces, we will need to adapt the design to how Spaces work, so this ticket won't be relevant.
