### ISSUE TITLE
Mark file:// and sftp:// links in messages as url in Riot chat log

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4457]
Our company have private local file storage and very often exchange links to files and folders, for example `file://mnt/share/project1/file2.odt`.

Many messengers convert this links to url via `<a href="file://mnt/share/project1/file2.odt">` and we can open those files directly via single click. 

Same problem is with `sftp` links - url like `sftp://user:pass@example.com/path/to/file.txt` breaks to parts:
sftp:[//user:pass@example.com/path/to/file.txt](//user:pass@example.com/path/to/file.txt)
instead of:
[sftp://user:pass@example.com/path/to/file.txt](#)

Please add same behavior to Riot-web interface.

**Comment by lampholder** [comment]
It looks like Riot highlights `file://stuff/stuff/stuff.txt` as a link, but then clicking it doesn't follow the link.

@MurzNN are you just asking for following file:// links to be enabled?

**Comment by lampholder** [comment]
Are there any considerations here? Any reasons we wouldn't want to do this?

**Comment by lukebarnard1** [comment]
Chome block access to local files and other browsers probably do the same.

https://stackoverflow.com/a/39007324

**Comment by turt2live** [comment]
Browser security may play a factor into the link not working, or result in unreliable functionality. 

Electron might be able to leverage OS things more easily, but still might be subject to security policies.

I'm not 100% sure though. Just seems like something Chrome would prevent at the least.

**Comment by MurzNN** [comment]
Here is screenshot of tests with `file://` links from Riot.im website: http://i.imgur.com/OfHUqQy.png
So all other types of link are detected and converted to `<a href=...>` but `file://` - not.
The problem can be solved via adding `file://` scheme to url detection rules.

Problem with not-working `file://` links in browsers easily solved via extensions and pre-configured enterprise settings:
- Firefox settings: https://stackoverflow.com/a/13083926/1395757
- Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/?src=search
- Chrome extension: https://chrome.google.com/webstore/detail/local-explorer-file-manag/eokekhgpaakbkfkmjjcbffibkencdfkl

So from Riot side - we must only convert `file://...` links to `<a href="file://...>file://...</a>` html code - that's all.

**Comment by MurzNN** [comment]
@lampholder, can you point me to place in Riot code where plaintext message is converting to `<a href>` links? I'll try to add file:// detection in this function.

**Comment by lukebarnard1** [comment]
@MurzNN a lot of logic for Riot lives in https://github.com/matrix-org/matrix-react-sdk. You're looking for `HtmlUtils.js`

**Comment by MurzNN** [comment]
@lukebarnard1 thanks for the info, so seems the issue is in `linkifyjs` - https://github.com/SoapBox/linkifyjs/issues/171
Hope they will fix it

**Comment by MurzNN** [comment]
And from Riot side there are create them clickable in riot-web electron app. At now riot converts links like `file://C:/windows_3.11/roadmap.txt` to url - they works well in browser, but not clickable when I click in electron app. Can we fix this and make open file in riot-web electron app?

**Comment by lukebarnard1** [comment]
>not clickable when I click in electron app

I'm guessing this is because your extensions aren't running in the context of electron (and they can't - https://github.com/electron/electron/issues/1498)

**Comment by MurzNN** [comment]
Same problem is with `sftp` links - url like `sftp://user:pass@example.com/path/to/file.txt` breaks to parts:
sftp:[//user:pass@example.com/path/to/file.txt](//user:pass@example.com/path/to/file.txt)
instead of:
[sftp://user:pass@example.com/path/to/file.txt](#)
For ftp:// links all works well.
Fix for both problems will be the same, so I add this to issue title.

**Comment by MurzNN** [comment]
Here is solution how to fix open local files in Elecron app: https://stackoverflow.com/a/33425619

**Comment by MurzNN** [comment]
Seems here https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/messages/TextualBody.js#L82 is the place where plain text converts to html with links.

**Comment by aaronraimist** [comment]
This is the current behavior (although https://github.com/vector-im/riot-web/issues/8720 wants to unlinkify them)

**Comment by t3chguy** [comment]
> successfully executes file opening process via default application for this file type.

Sure but what if that default action would be executing an executable, or opening a virus, this has many security implications

**Comment by MurzNN** [comment]
If user want to execute a virus, it can download it and open via double click, what is the difference? At now, for open `file://path/to/file.txt` we need every day to do manually copy url to clipboard, and paste it into filemanager.

For example, Firefox works well for those links - it asks user what to do: open file directly, or download it to `Downloads` folder, and this is very useful feature! Did you think, that Firefox doesn't care about security, if still not disable this feature?

But Chromium family browsers historically miss this feature, and have many upvotes for implement it: https://bugs.chromium.org/p/chromium/issues/detail?id=333&q=open%20file%20download&can=2&sort=-stars

**Comment by MurzNN** [comment]
I checked this feature, at now Element-Web successfully linkify "file://" links, but not linkify "sftp://" links:
![image](https://user-images.githubusercontent.com/336662/93777925-0329fd00-fc2e-11ea-9dfe-6a27ad9c45b1.png)
