### ISSUE TITLE
is_direct on invites

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#4460]
We currently only support the is_direct flag on create_room (ie. on invites sent when creating a room). This means that if a user is invited to a room with normal invite, there will be no is_direct flag, meaning the client tries to guess. If they're the first person you invite, they'll assume it's a direct chat.

Quickest fix for this would be to always set the is_direct flag to false on invites sent via the /invite API. In future we could also make the /invite API support is_direct.

**Comment by t3chguy** [comment]
related to #4425?

**Comment by lampholder** [comment]
So the upshot of this is if I create a new room and invite Alice then Bob, if they join in invite order then Alice will be have the room flagged as a direct message and Bob won't?

**Comment by turt2live** [comment]
I think we fixed the assumption at some point.
