### ISSUE TITLE
Closing RoomSubList Room Contextual Menu on outside click

### ISSUE THREAD

**Issue by albuic** [vector-im/element-web#4462]
### Description

The "quick-settings channel window" should close on a click outside of the app (or when the window lost focus)
("quick-settings channel window" = the window you can open when clicking on the icon on the right of a channel name when you hover it)

### Steps to reproduce

- Click on the icon that appear when you hover a channel to open the channel settings
- Click out of your chat window (on a second screen)

Expected : The channel settings should close
Actual : The channel settings stays opened

### Version information

- **Platform**: desktop and web probably

For the web app: not tested

For the desktop app:

- **OS**: Windows
- **Version**: 0.11.4

**Comment by turt2live** [comment]
What's the motivation for this? I'd probably be irritated if I was trying to copy/paste something, or finding an icon, or whatever and the room settings kept closing. I'm not sure what other people's feelings are though. 

@t3chguy - you use the electron app (amoung others), what are your thoughts?

**Comment by t3chguy** [comment]
@turt2live its the RoomSubList Room Contextual Menu he means

![image](https://user-images.githubusercontent.com/2403652/27744500-a0d8a8da-5db7-11e7-8fbc-30189cb11808.png)

**Comment by turt2live** [comment]
ah, well, in that case that makes sense to me then. Apologies for the misunderstanding.

**Comment by albuic** [comment]
Thanks @t3chguy for the answer ;-)

**Comment by aaronraimist** [comment]
Seems to be fixed in recent versions of Riot as that's how I always close it :)

**Comment by turt2live** [comment]
This isn't fixed: the OP is asking for the menu to disappear when you click on a different window, not within the pane.

**Comment by aaronraimist** [comment]
Oh. What other web app behaves like that?

I don't think I'd want anything to change when I clicked on a different app temporarily.

**Comment by teemak** [comment]
The current version has this issue solved. (version 1.0.5)

**Comment by t3chguy** [comment]
> Oh. What other web app behaves like that?

Real context menus behave like this

**Comment by t3chguy** [comment]
As a datapoint; Discord does not behave like this but they have some heuristics on autoclosing it on hover then leave

**Comment by kittykat** [comment]
This appears to be fixed :tada: 

If anyone is still having issues with closing the context menu, please file a new issue
