### ISSUE TITLE
ambiguous "Installation Steps for Debian Stretch" instructions about electron app

### ISSUE THREAD

**Issue by strontium38** [vector-im/element-web#4476]
### Description

The link to the PGP-Key for signing releases is broken. The provided debian stretch repository contains a package named riot-web, but the package seems to be the desktop version of riot based on the dependencies of the package.

**Comment by t3chguy** [comment]
as to the signing key: #4464

`riot-web`  in the provided debian repository *is* the desktop release of the app, there's an issue to track the want of the webapp package: #2777

**Comment by strontium38** [comment]
The fact that this is the desktop app should probably be mentioned in the install instructions.
I think it would be best to move the section "Installation Steps for Debian Stretch" to the "Running as a Desktop app" section.

**Comment by t3chguy** [comment]
edited title

**Comment by t3chguy** [comment]
This has been resolved since
