### ISSUE TITLE
Allow automatic sorting of the favourites (and other automatic tags)

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#4484]
### Description

Feature request: I wish it was possible to have favourites sort automatically based on recent activity as I currently have 15 of them thanks to them working so well with Riot Android (Home display "pin rooms with ... notifications" (which could fix this also on Riot Web)).

Problem: I have 21 favourites and they are in random order which acts to be somehow manual. When "more" isn't clicked it only shows 10 favourites and I don't know what happens in the five other rooms. Also when I click more, most of my screen is took for favourites and I have no idea what happens in normal rooms without scrolling.

### Steps to reproduce

- Mark more than 10 rooms as favourites
- Restart Riot
- Wait for all rooms to become active and try to stay aware on what is happening everywhere.

I expect to be easily be able to be aware of what happens in my favourites and normal priority rooms without scrolling all the time or having half of my screen being used by inactive favourites.

Log: not sent   

![untitled](https://user-images.githubusercontent.com/831184/27792401-35a1b4ec-6002-11e7-96b4-107afbab7115.png)

* 21 favourites taking all the screen in addition to custom tags and with random unread rooms while the behaviour I expect would be having all rooms with unread messages on top of the list visible at glance.

![2017-07-03](https://user-images.githubusercontent.com/831184/27792550-eb22e908-6002-11e7-8a27-0a5df4c25450.png)

* The 10 toppernmost favourites which I would expect to include *Esperanto, Sweden, Helsinki, Mediaseuranta, Disroot, Arch Linux Women, Offtopic, Vent* on top of the list instead of them being hidden under more seen at the first screenshot.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10
- **Version**:  0.11.4

**Comment by turt2live** [comment]
Worth noting: https://github.com/vector-im/riot-web/pull/3928 (and co.) do support this functionality, albeit not merged yet.

**Comment by lampholder** [comment]
I have the same problem, and am also enjoying Riot Android's approach to favourite ordering. I'd like to see us do this :)

**Comment by turt2live** [comment]
This is now possible with the new room list
