### ISSUE TITLE
Numeric IPs in URLs don't linkify.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#45]

**Comment by aviraldg** [comment]
looks like it's fixed on /develop at least @ara4n

**Comment by ara4n** [comment]
pretty sure that 127.0.0.1/foo does not autolinkify into an http link in the manner that google.com/foo does:  Whether we want this or not is slightly debatable.

![Uploading Screen Shot 2016-07-17 at 19.03.07.png…]()

**Comment by richvdh** [comment]
would you also want `127.0.0.1` to be linkified as http://127.0.0.1 ? How about `[::1]` ?

Not keen...

**Comment by t3chguy** [comment]
IP address linkification is uncommon at best, I don't think this is something we really want. Explicit links work.
