### ISSUE TITLE
Send email invitations to room for new users in current Riot language

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4509]
At now Riot send mail invitations to room for new users in English language, which not all people knows. Will be good if Riot looks at current user language and send email in current language.

**Comment by lampholder** [comment]
This would be really nice.

OOI - _does_ Synapse/Sydent know the user's language choice, or is that purely a locally-configured client-side option?

**Comment by MTRNord** [comment]
@lampholder currently it is client side I think.

**Comment by t3chguy** [comment]
it might be in `account_data` ?

**Comment by lampholder** [comment]
I can't remember whether Synapse or Sydent is responsible for the sending of email invitations, but the bigger problem for now seems to be that the information we need lives client side (inaccessible by both Synapse and Sydent)

If all the data we need is client side, then we either need to:
- expose a way for the inviter's client to query the invitee's clients for the preferred language
- expose a way for the server to query the invitee's clients for the preferred language
- expose a mechanism for language preferences to be persisted server side

Alternatively, we could:
- assume that the invitee speaks the same preferred language as the inviter, allowing the inviter's client to specify a preferred language when making the invite request
- do our best to internationalise the invites, either by:
    - translating the current text into every supported language in a huge ugly list, or
    - slapping in a cheesy multilingual image, like this but for inviting:
    ![image](https://user-images.githubusercontent.com/1922197/28459354-0612ea46-6e05-11e7-854f-7e0bacd7eb6c.png)

**Comment by harcesz** [comment]
I've no idea of the structure here, but really need localized invitations for a few hundred people in a single batch, maybe more later. Even if there were any sort of a hack to do it now, would be good, but for invitations in general; predifining to users language, and an option to pick another one from a list of available languages would suit. 

Also, we should have full Polish translations of everything riot by Monday :]

**Comment by devcline** [comment]
its needs to be localized and customized, thanks

thumbs up!

**Comment by dtcg** [comment]
Is there a way to contribute to this, language-wise? Is Element part of some localizing platform like https://weblate.org ?
I'd be happy to translate emails and stuff to my native language (not English).

**Comment by harcesz** [comment]
@dtcg https://github.com/vector-im/element-web#translations

**Comment by SimonBrandner** [comment]
IIRC, the email notifications get sent by the homeserver, so this would probably need to be added to Synapse/Dendrite..., right?

**Comment by t3chguy** [comment]
@SimonBrandner exactly correct

**Comment by SimonBrandner** [comment]
Also, the correct timezone should be used ([#1563](https://github.com/vector-im/element-web/issues/1563))

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/2808
