### ISSUE TITLE
A message that fails to send and that consists only of a URL does not indicate that it was not sent

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#4531]
### Description

Normally, messages that fail to send are in red.  However, if the message consists only of a URL (or maybe just a code block?), the message is coloured as a URL, and not as an unsent message.

![image](https://user-images.githubusercontent.com/1012976/27930221-c611d13e-6263-11e7-86ed-51e9b5e6e2db.png)

(of course, there is still the big bar at the bottom, so this is probably only P3)

Relying on colour to convey information is not always reliable.  Another way that an unsent message can be indicated is a warning (⚠️) icon to the right of the message where the "..." menu button is.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.11.3

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/3391

**Comment by uhoreg** [comment]
It's likely that a fix for 3391 would also fix this, and vice versa.  I'll let someone else decide if it should be considered a dup.

**Comment by turt2live** [comment]
> The second the untrusted devices appear, the warning appears in the StatusBar telling you messages will be queued until you verify them.

It's not exactly the same, but a very similar resolution.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/144594196-b8dffd76-e69b-47a0-bc6f-3118ce47e52b.png)

This has been fixed
