### ISSUE TITLE
Add instructions for Gentoo to use an overlay for installing

### ISSUE THREAD

**Issue by PureTryOut** [vector-im/element-web#4542]
I've created an overlay (repository) and ebuilds to easily compile and install Riot (the Electron build) for Gentoo Linux.

The repository is available [here](https://gitlab.com/puretryout/matrix-overlay).

## Adding the overlay
The  repository can be added manually or using Layman

### Layman

Make sure the Layman overlay list is up-to-date

```
# layman -S
# layman -a matrix
```

### Manually

1. Clone the repository somewhere

```
$ git clone https://github.com/puretryout/matrix-overlay
```

2. Create a new file called `matrix.conf` in `/etc/portage/repos.conf` with the following content:
```
[matrix]
location = /path/to/cloned/repository
```
3. To update the overlay just run `git pull` in the cloned repository

## Installing Riot

Once the overlay is enabled, you can install Riot.

```
# emerge -a riot-web
```

**Comment by lampholder** [comment]
@PureTryOut thanks!

I tried to verify these instructions, but my gentoo familiarity was too low :(

I did notice that I didn't have a `/etc/portage/repos.conf/` with a fresh install - creating one and populating with the `matrix.conf` as described seemed to make `emerge -a riot-web` do reasonable-looking stuff, but then it fell over when trying to install `net-libs/node.js` (implying that my gentoo vagrant box is fairly broken).

**Comment by PureTryOut** [comment]
Yeah `/etc/portage/repos.conf` might not exist. It can be either a file containing the content I mentioned, or a directory with separate file containing the same content. I'm basically assuming most people will use it as a directory, but that might not be.

What is your exact error with `net-libs/node.js`? I don't think there is something I can do about it, as it's a Gentoo maintained package, but maybe I can point you in the right direction.

**Comment by lampholder** [comment]
The (or perhaps 'a') problem was I hadn't run ```emerge --sync```.

Having run ```emerge --sync``` I then hit another hitch:
```
vagrant@local ~ $ sudo emerge -a riot-web

 * IMPORTANT: 3 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] net-libs/http-parser-2.6.2  USE="-static-libs" ABI_X86="(64) -32 (-x32)"
[ebuild   R    ] dev-libs/openssl-1.0.2k  USE="-bindist*"
[ebuild  N     ] dev-libs/libuv-1.10.2  USE="-static-libs" ABI_X86="(64) -32 (-x32)"
[ebuild  N     ] net-libs/nodejs-6.9.4  USE="npm snapshot ssl -debug -doc -icu {-test}" CPU_FLAGS_X86="sse2" PYTHON_TARGETS="python2_7"
[ebuild  N    ~] net-im/riot-web-0.11.4  USE="-websocket" ABI_X86="(64) -32"

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/openssl:0

  (dev-libs/openssl-1.0.2k:0/0::gentoo, ebuild scheduled for merge) pulled in by
    >=dev-libs/openssl-1.0.2g:0=[-bindist] required by (net-libs/nodejs-6.9.4:0/0::gentoo, ebuild scheduled for merge)
                                 ^^^^^^^^

  (dev-libs/openssl-1.0.2k:0/0::gentoo, installed) pulled in by
    >=dev-libs/openssl-0.9.8f:0[bindist=] required by (net-misc/openssh-7.3_p1-r7:0/0::gentoo, installed)
                                ^^^^^^^^


It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously. You may want to try a larger value of
the --backtrack option, such as --backtrack=30, in order to see if
that will solve this conflict automatically.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.


The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by riot-web (argument)
=net-im/riot-web-0.11.4 ~amd64

Would you like to add these changes to your config files? [Yes/No] yes

Autounmask changes successfully written.

 * IMPORTANT: 4 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
```

For completeness, I also ran ```sudo emerge --oneshot portage``` because emerge was nagging me to :)

**Comment by PureTryOut** [comment]
Oof, I detest that issue. I had it before with other packages, and I fixed it by adding both `dev-libs/openssl -bindist` and `net-misc/openssh` to `/etc/portage/package.use`. I'm not actually sure that's the correct way to fix it, but it works. `-bindist` removes stuff that could potentially cause problems in regards with patents and such. Most of the time (also in this case) not a problem, as long as you don't plan on distributing your compiled binary to others.

**Comment by lampholder** [comment]
My ```/etc/portage/package.use``` is a directory - how should I add those things to it?

Sorry for my absolutely lack of familiarity with Gentoo - you can console yourself that this will genuinely be an "idiot's guide" to building Riot on Gentoo once we're done :P

**Comment by PureTryOut** [comment]
Haha no problem. `/etc/portage/package.use` can be either a directory or a file. If it's a directory it just contains files with the same content that would otherwise be in `/etc/portage/package.use` if it were a file. It can just be split up into multiple files that way. It has no actual benefit to split it up, it's just for yourself.

So just put those 2 lines I mentioned in one of the files inside `/etc/portage/package.use`, it does not matter which.

**Comment by lampholder** [comment]
Modifying the files in `/etc/portage/package.use` didn't work for me - in the end I had to ```sudo emerge --oneshot openssh``` to fix the dependency graph conflict, 
Then I had to ```sudo etc-update``` before running ```sudo emerge -a riot-web``` and that finally did the needful and successfully built riot-web :)

I'll talk to someone about getting these instructions linked from https://riot.im/desktop.html

Thanks for your help :D

**Comment by PureTryOut** [comment]
I'm guessing `sudo etc-update` added the proper stuff. Well, it's fixed now, have fun with it 😉

**Comment by lampholder** [comment]
@dbkr - are you the person to link these instructions on the site?

**Comment by Tyil** [comment]
For the record, this ebuild fails if you have certain security options turned on, specifically `network-sandbox` (which ought to be a default). Yarn attempts to download additional (untrusted) packages from the global Internet.

**Comment by PureTryOut** [comment]
@Tyil could you make an issue for it on the repo of the overlay instead? https://gitlab.com/puretryout/matrix-overlay

**Comment by Tyil** [comment]
@PureTryOut I've opened [#12](https://gitlab.com/PureTryOut/matrix-overlay/issues/12) on that repo.

**Comment by TheJJ** [comment]
The repo seems to be abandoned:

> I don't use Gentoo Linux anymore, so I've archived this repository. Anyone is free to fork it and take it over.

alternatives: (via https://gpo.zugaina.org/Search?search=riot-desktop and https://overlays.gentoo.org/):

* new `matrix` overlay: https://gitlab.com/steils/matrix-overlay
* `sft` overlay: https://github.com/SFTtech/gentoo-overlay

**Comment by TheJJ** [comment]
Element desktop is [only](https://gpo.zugaina.org/net-im/element-desktop) in `sft` overlay at the moment, with proper migration from `riot-*`.

**Comment by deepbluev7** [comment]
I think this can be closed, since element is in the gentoo repos now? https://packages.gentoo.org/packages/net-im/element-desktop-bin (Or instructions for that be added)
