### ISSUE TITLE
UTD Error Message should stand out more

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#4563]
### Description

The current form of the UTD error message is easy to spoof. It would be good if there was something distinguishing a UTD error from a regular message other than the little red circle.

![UTD error message next to regular message](https://user-images.githubusercontent.com/17915621/28133684-c4ea0b1e-670e-11e7-830c-39db8fbd14b1.png)

In the picture above, the upper message is a true UTD error, but the message below is a copy-paste of the error message.

### Version information

- **Platform**: web (in-browser) (haven't tested desktop version, but I assume it's the same.)

For the web app:

- **Browser**: Chrome, Safari, Firefox
- **OS**: Windows, macOS, Linux
- **URL**: riot.im/develop, riot.im/app

**Comment by SimonBrandner** [comment]
Now they are in bold and quite hard to miss
