### ISSUE TITLE
User search directory doesn't collate correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4569]
And doesn't realise that Leon ~= Léon

**Comment by lampholder** [comment]
@ara4n - is it obvious to whoever will be resolving this what 'correctly' is?

Also, are you saying that we do not want Léon to come up in search results for Leon?

**Comment by t3chguy** [comment]
@lampholder I think he means the opposite, such that he queried `Leon` with the intent to find `Léon` but failed

**Comment by t3chguy** [comment]
So this requires changes to Synapse, which is simple in Postgres by use of the `unaccent` extension, but not so in SQLite. So will need to be done at app level using something like https://pypi.org/project/Unidecode/

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/7247

Closing in favor of the Synapse issue: https://github.com/matrix-org/synapse/issues/13655

**Comment by squahtx** [comment]
This is closer to https://github.com/matrix-org/synapse/issues/1523 than https://github.com/matrix-org/synapse/issues/13655
