### ISSUE TITLE
TextForEvent does not match matrix-console and riot-android

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#4573]
This occurs when you /unban a user who was never in a room, such message should probably silenced or something...

**Comment by t3chguy** [comment]
for reference, Console blanked on this

![image](https://user-images.githubusercontent.com/2403652/28181358-3b46e772-6800-11e7-84af-2e506844ebed.png)

**Comment by lampholder** [comment]
So if you /unban any (even a made up) non-present userid you get the 'userid left the room' message.
If you /unban the same id again, you get a 'Cannot unban user who was not banned (membership=leave)' message.

**Comment by t3chguy** [comment]
This should be fixed in Synapse too, its not treating no membership as membership=leave for unbanning

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/issues/2370

**Comment by t3chguy** [comment]
more generically applies to /kick also

riot-web on a leave,kick,kick of a user will show
user left the room *3

matrix-console and riot-android show it just once
(ignoring the redundant ones)

**Comment by t3chguy** [comment]
This got fixed
