### ISSUE TITLE
Assorted E2E errors in #megolm

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4592]
UTD and some messages from users on matrix.org were decryptable and others not.

**Comment by aaronraimist** [comment]
This issue is probably not actionable anymore

**Comment by turt2live** [comment]
UISIs are being investigated still, so there's hope.

**Comment by aaronraimist** [comment]
Sure but this issue doesn't have any details or rageshakes right?

**Comment by turt2live** [comment]
it has rageshakes with more details.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2996
