### ISSUE TITLE
Can't kick gitter integration bot (because it's an admin)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4599]
To reproduce:
- Create a public room
- Go to 'manage integrations'
- Add 'Gitter' integration
- Add sourcelair/xterm.js - this will fail (No guest access allowed)
- Gitter Integration bot will still join
- You can't kick Gitter Integration bot because it has joined as an admin

**Comment by t3chguy** [comment]
This is not an Element issue, it should be removed via the Integration Manager which you used to add it.
