### ISSUE TITLE
I haven't received a notification in my notification panel since Wed, Jul 5 2017 13:58

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4604]
I still get desktop notifications, but when I check my notification panel there's nothing (new) there.

**Comment by grahamperrin** [comment]
In my case there was nothing more recent than 2017-04-12, https://matrix.to/#/!NXrvsnxCRgMdLDYZlk:matrix.org/$149201085556745uMRnk:matrix.org for an IRC channel from which I departed a few minutes later. 

----

A test this afternoon resulted in addition to the list. https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15013483652270337AVSIy:matrix.org

I strongly suspect that some prior notifications have disappeared from the list. Amongst the disappearances, almost certainly some that related to spammy and/or offensive messages (maybe from ChanServ (PM on chat.freenode.net)) … 

… but I find it hard to imagine that more than three months passed without any desirable notifications. It does feel as if there's a huge gap.

**Comment by t3chguy** [comment]
Could it possibly just be lost higher up in the panel? 
https://github.com/vector-im/riot-web/issues/3471

**Comment by grahamperrin** [comment]
Here, the order is correct. 

The list comprises notifications on: 

- 2017-04-04
- 2017-04-05
- 2017-04-09
- 2017-04-11
- 2017-04-12
- 2017-07-29

Now I'm _certain_ that the list is incomplete.

**Comment by lampholder** [comment]
My notifications go back further than I care to scroll (and that panel doesn't show the notification date, only the time, which is hugely annoying).

Still nothing since 2017-07-05 for me, though

**Comment by VaiTon** [comment]
Is this still an issue for you @lampholder ?

**Comment by MadLittleMods** [comment]
Closing as there wasn't any follow-up here after VaiTon asked and no new reproductions since.
