### ISSUE TITLE
[Feature request] Registration / Auth via OAuth from popular services - Google, Github, etc

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4610]
Will be good to have support for OAuth from popular services - Google, Github, etc in Riot registration and authentication process.

**Comment by amsomniac** [comment]
I agree! I've been trying to figure out how to get a local LDAPS server that mirrors oauth2 or something set up, but it'd be much easier if I could just authenticate riot.im with oauth.

**Comment by cristiandley** [comment]
is there any status on this feature ?

**Comment by poVoq** [comment]
Is this coming with the experimental refresh? Or does this require also changes on the synapse server side of things?
I guess onboarding / auto-registration might be difficult, but simple linking of accounts for auto login?

**Comment by t3chguy** [comment]
This is already possible with a Synapse which has sso connected to such an oauth

**Comment by bhack** [comment]
What about https://github.com/matrix-org/matrix-react-sdk/pull/5426 ?

**Comment by t3chguy** [comment]
That is just support for the server providing information for multiple buttons rather than just one. Either way it is supported and will even be rolling out to the default matrix.org server in the near-future.
