### ISSUE TITLE
Password reset modal text is double-escaped.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4613]
Reset your password - the password reset email send confirmation message reads:

"An email has been sent to XXX@XXX. Once you&#39;ve followed the link it contains, click below."

The text has been double escaped.

**Comment by novocaine** [comment]
@lampholder are you able to reproduce this in 2021?

**Comment by psrpinto** [comment]
I can no longer reproduce this issue:

![Screenshot 2021-10-13 at 16 28 45](https://user-images.githubusercontent.com/550401/137165084-3799bb9a-89db-4bd7-8878-b01f038a05da.png)

**Comment by novocaine** [comment]
Closing as > 30 days after requesting info and can't repro
