### ISSUE TITLE
Invite dialog scrolls autocomplete suggestions when hovering over items (last/first)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4617]
### Description

This seems like it could be a feature, but also could be a bug. Assuming this a bug, but please correct me if I'm wrong.

When there are >4 suggestions for a user, hovering over the last suggestion causes it to scroll down and show a few more suggestions. The gif below at no point uses the scroll wheel or other navigation techniques, just plain old moving the mouse around.

![gif](http://g.recordit.co/hvvQc8zf8c.gif)

Note: It is easier to reproduce when not recording, apparently. Probably something to do with mouse events being captured and not firing in all of the right places, or this may be truly intermittent. 

Seems to require some distance to be traveled before it'll scroll. This is why the hovering is exaggerated in the gif.

### Steps to reproduce

- Start inviting a user
- Get multiple results
- Hover over a bunch of them
- Note scrolling

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I found this easy to reproduce. Glitchy and annoying - I can't imagine it's a feature (though I can imagine it's a side effect of something that is a feature).

**Comment by turt2live** [comment]
This was deleted
