### ISSUE TITLE
AGC makes microphone volume too loud during conference calls

### ISSUE THREAD

**Issue by foxlet** [vector-im/element-web#4634]
### Description

When running a conference call in a Matrix channel using the Riot desktop app, some type of AGC keeps adjusting the system's microphone level allowing the sound to clip.

### Steps to reproduce

- Start conference call
- Talk for a while
- Volume increases automatically.

Ideally the volume shouldn't change, or be allowed to clip. The Windows Sound panel shows the volume increasing, and bringing it back down only works for a moment. Possibly adding an option to disable automatic gain control could help.

Log: not sent   

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows 7
- **Version**: 0.11.4

**Comment by ahsanshaokat** [comment]
Hi @foxlet , would you please help me, I am trying to do conference call, call made also, and ringing, but the people in my group is not getting that call, SeeCall is mading, but my group member's not getting this, even in console, ti's telling that 2 people are in mading for this call
![softwarequalitygroup1](https://user-images.githubusercontent.com/14543126/28364303-50e06382-6c9d-11e7-9b02-fb7eb08a61e9.png)
![Uploading SeeCall is mading, but my group member's not getting this, even in console, ti's telling that 2 people sending.png…]()

**Comment by foxlet** [comment]
Possible some hints as to what is managing AGC (as part of Google Chrome's WebRTC)?

https://stackoverflow.com/questions/37326846/disabling-auto-gain-conctrol-with-webrtc-app

**Comment by uhoreg** [comment]
@ahsanshaokat please don't pollute issues with unrelated questions.

Regarding the actual issue reported here, part of the blame could be the conferencing server, which is due to be replaced in the next couple of weeks, and hopefully will fix many issues including this.  One way to check would be to see if you have the same issue with 1:1 calls, since 1:1 calls don't use the conferencing server.

**Comment by tleydxdy** [comment]
is this still relevant?

**Comment by SimonBrandner** [comment]
No, it doesn't seem to be - we use Jitsi now and [#6278](https://github.com/vector-im/element-web/issues/6278) seems to cover the problem for 1:1
