### ISSUE TITLE
Improve the fast room switcher

### ISSUE THREAD

**Issue by sandhose** [vector-im/element-web#4658]
The <kbd>C^k</kbd> fast room switcher is a great piece of UI, and can be improved, inspired by what Discord and Slack do.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/1549952/28480221-f42c8f48-6e5f-11e7-8b59-929f67964d2d.png">

Slack shows you the channel with the last mentions first. It lets you jump to the next unread room with a few keystrokes. It also pre-selects the first item.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1549952/28480272-24d03334-6e60-11e7-8c17-da8f18ce1759.png">

Discord does the same, and also pre-selects the last room visited when the search field is empty. It lets you go back and forth a room rapidly.

---

Also, selecting items with the arrow keys (see #3114) seems to have broken recently according to [Michael](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15006653852145yWlRe:riot.ovh)

**Comment by lukebarnard1** [comment]
We now do up/down navigation of the room list. 

Pre-selection is certainly an interesting feature, I can see last channel and most recent mention being both being very useful.

Thinking about it, I mostly click on a very small subset of rooms in my favourites and I wonder how others use their room lists in Riot.

**Comment by kiliankoe** [comment]
The floating panel UI for a switcher is definitely popular, Telegram (at least the macOS desktop client) also features this, incl. preselection of the first element 👍

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19530
