### ISSUE TITLE
Media server thumbnail requests don't honour the method/size parameters

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4673]
As encountered incidentally in https://github.com/vector-im/riot-web/issues/4646.

@lukebarnard1 suggests that the real behaviour might be thumnailing requests' returning thumbnails generated in previous requests.

**Comment by lukebarnard1** [comment]
(which suggests that thumbnails are generated, cached and then an error is encountered.)

**Comment by t3chguy** [comment]
This is not an Element issue
