### ISSUE TITLE
Links with markdown formatting in (eg underscores) are interpreted as markdown

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#4674]
eg. type http://domain.xyz/foo/bar-_stuff-like-this_-in-it.jpg in markdown mode, it ends up as a link with italics instead of the underscores

**Comment by krombel** [comment]
The mentioned link works. Problems occur when the URL has `_` in it. So this is a problematic URL:
http://domain.xyz/foo/bar-_stuff-like-this_-in-it.jpg

**Comment by lukebarnard1** [comment]
http://domain.xyz/foo/bar-_stuff-like-this_-in-it.jpg

**Comment by lukebarnard1** [comment]
Plan of action is to RegExp URLs prior to markdown parsing to make them `[url](url)`-style md links

**Comment by ara4n** [comment]
#1270 introduced #4809 and has been reverted; unfortunately this means that this is open again. #4809 has much discussion over possible better fixes, but the TL;DR is:
 * Either we change back to GFM
 * Or we patch commonmark to behave like GFM (and create a horrible custom MD dialect)
 * Or we write an adhoc parser which goes through and finds things which look like non-code blocks and try to linkify them and then MD-escape them
 * Or we take commonmark's AST and try to guess where commonmark has got it wrong and then modify the AST to remove the spurious italics etc.

**Comment by ara4n** [comment]
twinned with https://github.com/vector-im/riot-web/issues/3428

**Comment by aaronraimist** [comment]
Related Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1635188

**Comment by jryans** [comment]
As a workaround, you could wrap the link in backticks to treat it as inline code to at least present a link that goes to the right place. You could also supply link text as in `[text](link)` style, which will also go to the correct place. Those are just workarounds for now; we should certainly fix this properly.

**Comment by t3chguy** [comment]
Another workaround is wrapping it in angled brackets like `<https://site.com/__foobar__>`

**Comment by kittykat** [comment]
Can confirm that this is still valid:

![Screenshot from 2021-11-04 09-28-32](https://user-images.githubusercontent.com/51663/140289844-15922b01-fb41-4a63-bf8f-af09def9fc43.png)

**Comment by babolivier** [comment]
I'm using latest develop (`f496d6d5bf31-react-4a6d46b76adc-js-87b920698f4c`, which according to https://github.com/matrix-org/matrix-react-sdk/commits/4a6d46b76adc includes the fix from https://github.com/matrix-org/matrix-react-sdk/pull/7200) and this issue still persists:

![image](https://user-images.githubusercontent.com/5547783/144223182-c57ca3c1-a376-410b-93bf-b3f7ecd16c01.png)

So I think this issue needs reopening.

**Comment by babolivier** [comment]
Can confirm it works great now, thanks a lot @Palid! :grin:

**Comment by hho** [comment]
Should this work in 
```
Element version: 1.9.6
Olm version: 3.2.3
```
now?

Because, for me it still doesn't:

My test URL is https://www.bora.com/fileadmin/_processed_/5/e/csm_Headerbild_BORA_Classic_2_L_e8dfdf2889.jpg.webp

It get's rendered as [https://www.bora.com/fileadmin/](https://www.bora.com/fileadmin/)_processed_/5/e/csm_Headerbild_BORA_Classic_2_L_e8dfdf2889.jpg.webp instead.

**Comment by t3chguy** [comment]
This fix is on develop, not yet in a release. Be patient.
