### ISSUE TITLE
Autocompleting a room using a not-primary alias should pill that alias, not the primary

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4696]
### Description

![image](https://user-images.githubusercontent.com/1190097/28724438-3a34b184-7377-11e7-8eb0-c671ed1ec48f.png)

In the above, I'm trying to use a more friendly alias for the telematrix room (`#telematrix:matrix.org` instead of `#telegram_-1001115051775:sijmenschoon.nl`). When I accept the suggestion, it uses the long form. Ideally the suggestion would also use the best matched alias instead of just the primary one.

This is more awkward when typing the whole alias out and trying to get it to pill form, resulting in your hand-crafted alias being obliterated.

Use case of using the non-primary alias: The server with the primary alias is down, leaving clients unable to join. Specifically choosing an alternative alias circumvents this.

### Steps to reproduce

- Have a room with 2+ aliases, 1 being primary
- Try to autocomplete the room with a non-primary alias

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I agree 100%, but expect this might be a little tricky to do with the current impl.

**Comment by aaronraimist** [comment]
I think this has been fixed. I frequently see non-primary aliases being suggested to me and sent by others.
