### ISSUE TITLE
Limit RTE user suggestions after a point

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4697]
### Description

![image](https://user-images.githubusercontent.com/1190097/28724740-59453fac-7378-11e7-81f3-d248b51c3439.png)

### Steps to reproduce

- Be in `#test:matrix.org`
- Type `@test`

I was not expecting so many results to show up.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Agreed.

We might enhance (incrementally) this by:
1. restricting the height to 5 rows (if the username you're looking for isn't there you just have to keep typing until you reach a less ambiguous prefix)
1. supporting scrolling within the restricted space (could this work smoothly?)
1. adding an ︽ button to allow expanding to full height

**Comment by lukebarnard1** [comment]
At the moment, the autocompleter is limited to `50vh`, or 50% of the viewport height. 

> 5 rows 

is about `215px` and in practice looks OK.

**Comment by lampholder** [comment]
> the example above was done in a mahoosively tall viewport.

Ah, that makes sense :)

> what exactly would "full height" mean?

Whatever looks good I guess. If we're limiting the hight to 50vh then I guess that will occupy >50% of the timeline panel - if we could limit it to slighly less than 50% of the timeline panel then it might look a bit less dominating.

Still, understanding that the image was the product of a monster viewport, I don't think this is particularly high priority :)

**Comment by aaronraimist** [comment]
It doesn't get this big anymore. Good to close?

**Comment by turt2live** [comment]
it's still about half of my 1080p monitor

**Comment by turt2live** [comment]
we do this now
