### ISSUE TITLE
Navigating to a different room while waiting for the join screen to load should not eventually redirect you

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4699]
### Description

Hopefully the steps to reproduce this are more clear than I am. This probably requires a slow homeserver/connection.

### Steps to reproduce

- Click room alias in a message
- Before the "Click to join" message shows up, become impatient and go to another room in your room list
- Wait a moment until the "Click to join" message appears

The expected behaviour would be as part of step 2, the intent to join should be canceled therefore preventing the click to join prompt.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
I believe this to no longer be relevant, could not reproduce when throttling network.
