### ISSUE TITLE
White background on .mx_BaseAvatar_image makes dark profile pictures look terrible on dark theme

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/element-web#4712]
When you have a profile picture with a black edge it gets a very thin white border around the image which looks quite bad against the black background of riot.

I assume this is here to make images with transparency visible on all background colors but I would argue that having no default background lets those groups set an icon with a proper background color where as the current setup makes it impossible to have a good looking icon on dark themes.

The background color really should not be visible on the edges of an image with no transparency though.

**Comment by turt2live** [comment]
Related / possible duplicate of https://github.com/vector-im/riot-web/issues/3203

**Comment by lampholder** [comment]
The image in #3203 seems to show the halo in the typing-notification-avatar rather than the inline-with-message-text avatar, so these can stay separate for now (though I expect they are closely linked and would be dealt with simultaneously).

**Comment by turt2live** [comment]
This also affects transparent avatars. Relayed from #riot (starting at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15041096531463006EUJlK:matrix.org)

> there is a white bg behind my profile picture for some reason, which kind of defeats the point of supporting transparency in profile pictures
> if someoen thinks their icon might look bad with transparency enabled they schouldnt enable it :/

Their avatar in question is 100% transparent: https://t2l.io/_matrix/media/v1/thumbnail/matrix.org/KmaJJyCiQMOqIBYSqebjYFzG?width=30&height=30&method=crop

**Comment by robintown** [comment]
Closing as both the dark and transparent cases have been fixed for some time
