### ISSUE TITLE
clicking permalinks and 'jump to unread' for old messages now takes aaaages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#4727]
It seems to take around 10s to reload the timeline when jumping to a permalink which is not known to the local client.  This feels incredibly slow; has something broken on this since ILAG?

**Comment by turt2live** [comment]
This is getting particularly bad. I've been trying to see an event from 5 hours ago in HQ for 10 *minutes* now. It's seemingly faster to just scroll up for a few minutes.

**Comment by turt2live** [comment]
Empirically it has gotten better recently, somehow. I've been clicking on permalinks from years ago and it seems fine (even the first one).

Leaving this open as a synapse issue though.

**Comment by kittykat** [comment]
I'm going to close this for now as loading permalinks has been pretty quick during testing over the last few months. There are still other issues around this (e.g. the loaded message not showing in the correct place in the timeline), but these all have their own issues.
