### ISSUE TITLE
How to LAN ?

### ISSUE THREAD

**Issue by berserkwarwolf** [vector-im/element-web#4741]
Can we get a wiki or a FAQ page on riot's web page? Because I want to know if I can use riot for a lan party with no internet and the answer to this is nowhere to be found.

**Comment by t3chguy** [comment]
If you have a local matrix server then riot can connect to it on any network, whether it be over the Internet or not, that's just a property of networks
You'll just be missing federation

**Comment by richvdh** [comment]
I don't understand this question.

**Comment by richvdh** [comment]
oh, s/root/riot/ ?

**Comment by t3chguy** [comment]
that's what I presumed

**Comment by berserkwarwolf** [comment]
I am sorry for the "root" typo, I meant Riot. I want to run Riot on a LAN, and don't know how. I use discord, and honestly, I've tried setting up mumble for lan parties but I couldn't. Perhaps the Riot team could 1) make detailed documentation on how to achieve this... or 2) add auto-discovery of matrix servers for the local area network environment.

Have you guys tried D-LAN ? It's an open source file transfer tool for LANs with autodiscovery. It works like a charm. No documentation needed, it just works.

**Comment by t3chguy** [comment]
@berserkwarwolf install https://github.com/matrix-org/synapse - point Riot at it and away you go

**Comment by t3chguy** [comment]
For support visit https://matrix.to/#/#element-web:matrix.org
