### ISSUE TITLE
Easy branding of Riot interface - application name, icon, logo and colors

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4745]
At now there are not easy to create a branded version of Riot for companies - we must find all places in source code where icon, logo and application name used and hack source code for replace them to company name and logo. Also seems logo image in source files used with different sizes and formats.

Will be good to move all branding info into config file, for quickly change application tray icon, name, homepage, logo and, default color theme (we already can change them per-room, but default theme is not changed).

After implementing this - Riot team will can provide paid SaaS branded ready-to-use solutions for companies, based on Riot & Matrix.

**Comment by MurzNN** [comment]
At now we already can change via `config.json` file using keys:
- `brand` - name of application - it changes now only tray icon hover text, but not application window name. Also this change name of per-user config folder name.
- `welcomePageUrl` - point name of html file to show on homepage (Riot Home button).
- `roomDirectory` - server address for default rooms directory.
- `default_hs_url` - server address to connect by default.

So problems to solve are:
- Get window title text and other places with "Riot" phrase from `brand` config variable.
- Add `logo_image` config variable and get image for application icon, tray icon and other places from this config variable.
- Add `color_theme` config variable for set default colors - we already can change Riot colors per-room, so set default color theme will be not too hard.

**Comment by abeluck** [comment]
While this issue hasn't been completed yet, is there a list of all the Riot specific text/images that must be replaced to change the brand of riot-web?

**Comment by 3nprob** [comment]
https://github.com/vector-im/element-desktop/pull/396 adds `tray_icon_path` to `config.json`.

**Comment by t3chguy** [comment]
> Get window title text and other places with "Riot" phrase from brand config variable.

Done

> Add logo_image config variable and get image for application icon, tray icon and other places from this config variable.

That's https://github.com/vector-im/element-web/issues/12020

> Add color_theme config variable for set default colors - we already can change Riot colors per-room, so set default color theme will be not too hard.

You can do that with config.json theming https://github.com/vector-im/element-web/blob/develop/docs/config.md#customisation--branding
