### ISSUE TITLE
Message body should be MD even if MD mode is disabled

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4769]
The RTE should be sending markdown in the `body` of a message even if MD mode is disabled.

**Comment by lukebarnard1** [comment]
Actually, the body is still human-readable and clients shouldn't be assuming otherwise.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890

**Comment by t3chguy** [comment]
This no longer applies as we don't have an RTE
