### ISSUE TITLE
Tab on empty composer no longer populates with most recent speaker(s) in room.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#4770]
The composer on /app does this, but it's missing from /develop.

**Comment by t3chguy** [comment]
There are multiple places in the code which explicitly ignore empty queries so it seems like this was done on purpose, another place which explicitly ignores queries of `@[TAB]`

Could you confirm the desired behaviour here

**Comment by SimonBrandner** [comment]
This is intentional since not doing this wouldn't be very accessibility friendly I believe
