### ISSUE TITLE
Allow magnet URL scheme

### ISSUE THREAD

**Issue by zeroware** [vector-im/element-web#4793]
### Description

I'm trying to send a link with the magnet URL scheme `magnet:`
The href attribute is removed when the link is displayed.

### Steps to reproduce

- Post a link using matrix-js-sdk containing a `magnet` URL scheme in the href attribute
- The href attribute is removed

I expect the href attribute to be intact.

I may be wrong but I think we need to add the magnet scheme here : 
https://github.com/matrix-org/matrix-react-sdk/blob/v0.9.7/src/HtmlUtils.js#L131

### Version information

- web

For the web app:

- **Browser**: Firefox 54
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by zeroware** [comment]
Just made a pull request to fix it : https://github.com/matrix-org/matrix-react-sdk/pull/1301

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15018
