### ISSUE TITLE
we should set our presence to idle when the app is in the background

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#4813]
we could use the same metric as we use for sending read-receipts etc: if the user hasn't interacted with the window in some way since the last sync, we should set the flag in /sync which says 'make me idle'

**Comment by lampholder** [comment]
Seems sensible :)

P3'ed just 'cause afaik this isn't on anyone's immedate agenda.

**Comment by MurzNN** [comment]
This feature is successfully implemented already in Android app.

**Comment by andybalaam** [comment]
We've had to revert the fix for this pending a Synapse update: https://github.com/matrix-org/matrix-react-sdk/pull/11365
