### ISSUE TITLE
login still fails with some PW managers

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#4831]

**Comment by lampholder** [comment]
Which PW managers? It would be good to record PW managers with problems here:

LastPass 4.1.63 in Chrome 60.0.3112.78: :white_check_mark:

**Comment by t3chguy** [comment]
http://invicem.pro/pages/passff.html

**Comment by t3chguy** [comment]
Closing due to lack of redcurrant reports in 5.5 years
