### ISSUE TITLE
Widget UX poor when vertical space limited

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4843]
When vertical space is reduced enough, the app draw displays a scrollbar. This should at least be a scrollbar on the box including _just_ the widget body (i.e. not the app tile header and "[+] Add a widget").

Separately, this is still quite bad and widgets should be aware of the amount of space they have available to them vertically, we already do this horizontally.

**Comment by turt2live** [comment]
Screenshot of what this can look like:
![image](https://user-images.githubusercontent.com/1190097/29760552-5c8de936-8b81-11e7-9d20-ed4d8cdc08c2.png)

**Comment by t3chguy** [comment]
Widgets are now resizable, any further nested scrollbars are due to poor integration manager wrappers
