### ISSUE TITLE
Modular logo is the wrong one

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4847]
The modular logo being used is probably not meant to be scaled to such a small size:
![2017-08-23-144338_86x66_scrot](https://user-images.githubusercontent.com/6750344/29618905-7653e9c4-8811-11e7-91f9-0f63eeb0704d.png)

Also, the original image is 411x411 whereas this has been scaled to 50x50, incurring the wrath of poor browser-native downsampling.

**Comment by pafcu** [comment]
@lukebarnard1 Where is this actually used?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/33980992-56a5a41e-e068-11e7-89ba-bd8709f290af.png)

**Comment by pafcu** [comment]
Looks OK to me on FF 57, but might be due to HighDPI screen.

**Comment by jaywink** [comment]
This has been fixed, or rather Modular became EMS.
