### ISSUE TITLE
Widgets break in WebKit browsers due unrecognized <iframe> flags

### ISSUE THREAD

**Issue by aperezdc** [vector-im/element-web#4876]
### Description

On WebKit-based browsers widgets do not work, only a white frame is shown.

### Steps to reproduce

- Load Riot in a WebKit-based browser. I used Epiphany (aka GNOME Web).
- Try to use a widget in a room. 

The inspector console shows the following error:

```
Error while parsing the 'sandbox' attribute:
  'allow-popups-to-escape-sandbox', 'allow-presentation'
  are invalid sandbox flags.
```

### Additional information

I did some investigation (see https://github.com/aperezdc/revolt/issues/76), and:

- The `allow-popups-to-escape-sandbox` flag [has been implemented](https://bugs.webkit.org/show_bug.cgi?id=158875). The next release of WebKitGTK+ (2.18.0) will support this.
- The `allow-presentation` is not implemented because WebKit does _not_ support the [Presentation API](http://w3c.github.io/presentation-api/) yet.

### Possible solution

I wouldn't worry about `allow-popups-to-escape-sandbox`, as it will be in the next release of WebKitGTK+. Dunno how the situation is for Safari, but if it doesn't support it right now, an upcoming version will.

As for `allow-presentation`, one idea could be adding the flag programmatically from JavaScript/React code *if* the browser supports the Presentation API. This would involve doing feature detection for it.

### Version information

- **Platform**: web
- **Browser**: Epiphany 3.24.3 with WebKitGTK+ 2.16.6
- **OS**: Arch Linux
- **URL**: riot.im/develop + riot.im/app

**Comment by lampholder** [comment]
Hey @aperezdc - thanks for the comprehensive write up + suggestions :)

I tried to reproduce on Safari, but Widgets work there without problem. I'll try and reproduce on Gnome Web once I've managed to install it...

**Comment by dbkr** [comment]
Bailing on the whole iframe if it sees a sandbox attribute it doesn't supports seems like a really dumb thing to do. If it doesn't support them, it should surely just ignore it: this would just mean the security feature would remain enabled. Even if it doesn't support them the features behind them, it could recognise the flags as valid flags and ignore them.

The best we could do here is put in an awful  hack to detect WebKitGTK and not add these flags.

**Comment by aperezdc** [comment]
@lampholder @dbkr It is very interesting that things work in Safari. Before adding a workaround in Riot, let me investigate a bit and see whether maybe we can fix that in WebKitGTK+ — it may be doing something different than the Cocoa WebKit port.

**Comment by jryans** [comment]
As these platforms are outside our supported set, it seems unlikely that core team would make a change here, but we're happy to review something from the community as long as it doesn't break supported platforms.
