### ISSUE TITLE
Cannot scroll left when a room has many widgets

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#4878]
### Description

Situation:
![image](https://user-images.githubusercontent.com/1190097/29694804-195c89ba-88fc-11e7-8c5d-a009269d1774.png)

I can scroll right to see the grafana widget, but I can't see the leftmost widget.

### Steps to reproduce

- Have lots of widgets in a room
- Try to scroll left

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Pinned widgets are now capped to 2 (3 really) so its no longer an issue, future iterations include tabs and a grid view.
