### ISSUE TITLE
Alt-up/down for changing rooms can result in strange ordering as the list reorders based on activity

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#49]

**Comment by richvdh** [comment]
... it's even more broken by RoomSublists.

**Comment by Valodim** [comment]
can we please please please get alt + up/down arrow to switch vertically between rooms in the order they are in? and ideally, alt + left/right by latest (own) activity, too? or is there some other method to navigate rooms?

having the mouse as the only way of navigation is ridiculous.

**Comment by t3chguy** [comment]
@Valodim's request is https://github.com/vector-im/riot-web/pull/13133

**Comment by turt2live** [comment]
I believe we've fixed this with the various stable ordering options and some workarounds to avoid jumps on activity-based sorting.
