### ISSUE TITLE
Rich text editor behaves strangely when selected with VimFX

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#4909]
### Description

When the text entry area for the new RTE is selected via "hints" in VimFX, the editor mangles the message badly. Specifically, the cursor randomly resets to the beginning of the message and some characters you typed become impossible to delete and just hang out at the end of your message.

I'll attach a video when I get a chance to take one.

I realize that resolving a problem caused by using one specific browser extension (or set of browser extensions) with Riot probably isn't really a bug, but making the RTE mandatory really exacerbated this issue for me. An option to turn off the RTE would completely remove this problem.

### Steps to reproduce

- Install VimFX in firefox
- Attempt to send a message by pressing `f` and then the appropriate keystrokes that show up in the hint over the message form.
- Begin typing your message
- Mash keyboard in frustration as everything goes awful.
- Switch to different room and switch back.
- Very carefully click on the message entry box this time instead of using keyboard shortcut.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 52.3.0 (and whatever version of FF I have on Windows)
- **OS**: Slackware Linux and Windows
- **URL**: riot.im/develop and riot.im/app

**Comment by JaniM** [comment]
I'm experiencing issues with VimFX too, albeit not similar ones.

If I select the RTE with vimfx's hints, the blinking cursor won't show up. The first letter of what I type is visible, but not the rest. Whatever I type in gets sent correctly when I hit enter.

Meta:

* Platform: web/develop
* Browser: Firefox Nightly 55.0.3 64-bit

**Comment by t3chguy** [comment]
This no longer applies as we don't have an RTE
