### ISSUE TITLE
Add a way to restrict notifications to currently selected channel

### ISSUE THREAD

**Issue by pksadiq** [vector-im/element-web#4927]
Right now then the notifcation button (the top right bell icon) is clicked, the complete notification list is shown.

It would be nice to further add a feature to restrict the notifications list to be shown from the current channel only (like a toggle button?).

Thanks

**Comment by t3chguy** [comment]
Re Notifications Panel

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15189
