### ISSUE TITLE
new composer no longer works with 'It's all Text' browser extension

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#4936]
as reported by Cal in https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1504061870884743UvlPm:matrix.org.

**Comment by non-Jedi** [comment]
Description of problem experienced sounds similar to #4909

**Comment by uhoreg** [comment]
Cal said he does not have VimFX installed.

**Comment by t3chguy** [comment]
This no longer applies as we don't have an RTE
