### ISSUE TITLE
Desktop notifications not working reliably

### ISSUE THREAD

**Issue by Edszx** [vector-im/element-web#4945]
### Description

First, my notification config is as follows:
![riot_2017-08-30_18-08-28](https://user-images.githubusercontent.com/10441078/29897879-05aa2b34-8db1-11e7-9f64-82b556225dc2.jpg)

I just get the visual desktop notifications like 1 or 2 times when i start up the client, after that, i just get sound notifications, if i change my settings to just only visual notifications, i still don't get more than 2 or 3 after reopening the client.

Yes, i know visual notifications are meant to be triggered when the window is minimized, but they don't work.

**Log**: sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 7 x64, Windows 10 x64
- **Version**: 0.12.2

**Comment by Edszx** [comment]
I want to add, it's currently working good in windows 10, (and windows 8 probably too, because it uses the same notification system windows 10 has), but it's still not working in none of my windows 7 systems.

**Comment by CIAvash** [comment]
Do the notifications get triggered only when the window is minimized? Because I use Gnu/Linux with Bspwm window manager and I put Element on a separate workspace and I still expect to get notifications. But I'm not getting any.

**Comment by SimonBrandner** [comment]
@CIAvash, I am on KDE + i3 and everything works just fine. Please open a new issue with a better description or ask for help in [Element Web/Desktop](https://matrix.to/#/#element-web:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org) someone there might know how to help you

**Comment by jryans** [comment]
I am not convinced this issue represents reality today. For those still having issues, I suspect it's quite separate from this Windows 7-specific report, so let's start new issues.
