### ISSUE TITLE
Synapse cuts out some words from search leading to confusion

### ISSUE THREAD

**Issue by gdvine** [vector-im/element-web#4950]
### Description

Desktop client in OS X returns no results, ever.

### Steps to reproduce

- Click on lupe button
- Type any search term, such as "the", click submit lupe. (Either "This Room" or "All Rooms")
- Lupe flashes for 10 seconds or so. Below: "No results"

Expected: some results.

Log: sent

- Desktop 
- OS X
- Version 0.12.2

**Comment by t3chguy** [comment]
@gdvine are you in an E2E encrypted room? Searches are currently server-side and thus cannot be done on E2E messages

**Comment by turt2live** [comment]
Strangely, I can reproduce this on Chrome 60 web as well:
![image](https://user-images.githubusercontent.com/1190097/29933217-203e800c-8e34-11e7-9290-a0181161b733.png)

The response is a 200 OK from the server:
`{"search_categories":{"room_events":{"count":0,"highlights":[],"results":[]}}}`

Other terms, like `e` and `hello` work, but `the` fails every time.

**Comment by t3chguy** [comment]
Weirdly I cannot, on latest Stable Desktop on Windows

**Comment by t3chguy** [comment]
maybe Synapse cuts `the` and other such words out of the search phrase to get more results
because it does do quite a wide search

**Comment by turt2live** [comment]
I'm going to also blame synapse. Words like `it`, `my`, and `on` also fail. Other stop words like `must` work though.

**Comment by gdvine** [comment]
E2E encryption is on, so that explains why the searching fails. Perhaps a conditional should be introduced which bypasses E2E encrypted rooms, and returns a message if no unencrypted rooms are found.

Is there a proposal for client-side search anywhere?

**Comment by gdvine** [comment]
Bad example – not only "the" but any string whatsoever returns no results as all my rooms are E2E.

**Comment by t3chguy** [comment]
@gdvine #2548

turning this thread into better tracking of the implicit behaviour of `the` and co

**Comment by lampholder** [comment]
Yuck!

Whatever else we decide to do, we should tell the user what we're doing if we're modifiying their search.

How easily could we do something like: 
![image](https://user-images.githubusercontent.com/1922197/30070969-083c7e82-925d-11e7-9011-505ec6304974.png)

**Comment by ara4n** [comment]
This is particularly unpleasant when searching for terms in URLs: https://github.com/vector-im/riot-web/issues/4486

**Comment by grahamperrin** [comment]
Today's <https://matrix.to/#/!GdmnfkDxuKZAICnOhe:matrix.org/$15054991507323727AFZiy:matrix.org> ends with this string: 

> to be /theme and /doc :D

Seeking `/theme` in that room does not find that line. 

----

Side note: I stumbled across that example, and others involving non-alphanumeric characters, whilst trying to make `#5007` reproducible.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/10559
