### ISSUE TITLE
jitsi widget && 1:1 calls should cause indication of call in a room

### ISSUE THREAD

**Issue by superdump** [vector-im/element-web#4957]
else people will miss that confs are ongoing

**Comment by BloodyIron** [comment]
It would be nice for this to also be indicated in the room list on the left, so if you are reading chat in another room, you can see conference activity for another channel (is this thing?) without having to switch.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/4957

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/14267 and https://github.com/vector-im/element-web/issues/18709
