### ISSUE TITLE
Add separate "Send message" button to Riot interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#4963]
At now we can send message via Enter button, but most of other messengers also have separate `Send message` button, for send message via mouse click only. Will be good to have same separate "Send message" button in Riot too, for sending message via one mouse click, like in Android app.

**Comment by lampholder** [comment]
At the moment I can't see what this would really get us; pressing <kbd>Enter</kbd> feels intuitive to me, and as far as I can tell most web/desktop chat applications don't implement a message send button so I don't think it's something users would expect.

**Comment by turt2live** [comment]
Some do, like WhatsApp, but they are more subtle:
![image](https://user-images.githubusercontent.com/1190097/30068738-e7c44432-921b-11e7-815b-9479164588f9.png)
![image](https://user-images.githubusercontent.com/1190097/30068749-f1bbe0f8-921b-11e7-8123-4e5bebb78eb8.png)

**Comment by MurzNN** [comment]
Also confusing moment when user use "Quote" button in RTE, pressing "Enter" first time don't send the message, only third Enter really sends the message.

**Comment by MurzNN** [comment]
For design: this button can be shown only when user type something in message area, and in this moment we can hide or collapse audio-video call buttons to one button "More", like in WhatsApp - send button shows only after typing, and replace voice input button.

**Comment by iav** [comment]
Not "user **type**", but "there is any content".
Visual button needed for mouse or touch screen — and often after clipboard operation (if no touch screen).

**Comment by iav** [comment]
Example:
entry before any content entered
![2020-07-25 00_59_27-Skype](https://user-images.githubusercontent.com/325961/88438916-69eb8f80-ce12-11ea-80df-ab81471ea981.png)
Then after any 
![2020-07-25 01_00_50-Skype](https://user-images.githubusercontent.com/325961/88438958-8982b800-ce12-11ea-8c69-ac6a8e6ea2c3.png)
content inserted (keyboard, of clipboard, or other way)

**Comment by kenzabit** [comment]
It's a weird pattern to leave out a send button, I just noticed there's no send button on the desktop client either. Besides the above example of using a touch interface where having a send button can make things easier. One could argue, that it does seem useful with a keyboard and mouse interface too. In where you copy a link or some snippet, and just paste it and send it while only using the mouse. Albeit not a bread and butter ux pattern, it is not an unusual way to use an mouse/keyboard interface either.

**Comment by muelli** [comment]
I just wanted to point out that I cannot send any messages on my tablet, because I cannot find a "send" button. That makes using Element a little bit difficult.

**Comment by SimonBrandner** [comment]
I'd like to give this a go but I am not really sure where to get the icon...

**Comment by MurzNN** [comment]
> I'd like to give this a go but I am not really sure where to get the icon...

Maybe convert from Element-Android source https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/drawable/ic_send.xml to SVG?
