### ISSUE TITLE
some rooms remaining in ROOMS after demotion to LOW PRIORITY or promotion to FAVOURITES

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/element-web#4975]
![2017-09-04 09 23 43 riot 3](https://user-images.githubusercontent.com/192271/30049037-dc65b46e-9210-11e7-8112-fc53c730e080.png)

Screenshot taken on 2017-09-04 but that's probably **not** when the room was moved. I probably moved in some time during the preceding two weeks. 

SeaMonkey 2.48 on FreeBSD-CURRENT

**Comment by lampholder** [comment]
Anecdotally I believe I have also encountered this.

**Comment by turt2live** [comment]
just curious, and this might help lead to a diagnosis: when editing the room is there a tag called `im.vector.fake.recent` or similar?

**Comment by grahamperrin** [comment]
<https://riot.im/develop/#/room/#freenode_#pcbsd:matrix.org> yes there's that tag, `im.vector.fake.recent`. 

This morning I found another room in two sections at the same time – _FAVOURITES_ and _ROOMS_. I made a screen recording but the recording failed and (sorry) I didn't keep a note of which room was affected … I'm ~50% sure it was <https://riot.im/develop/#/room/#freenode_#freebsd-ports:matrix.org> and there, too, is the `im.vector.fake.recent` tag.

**Comment by grahamperrin** [comment]
Another: 

![2017-09-06 07 29 03 riot 5](https://user-images.githubusercontent.com/192271/30097368-3c552372-92d5-11e7-8557-974b03c41afc.png)

<https://riot.im/develop/#/room/#gitter_bsds=2Ffreebsd:matrix.org> there, too, is the `im.vector.fake.recent` tag.

**Comment by turt2live** [comment]
Fixed in the new room list
