### ISSUE TITLE
make it possible to configure 'enter' to insert line break rather than send message

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5006]
Apparently telegram lets you do this and some people prefer it ¯\\_(ツ)_/¯

**Comment by pouladpld** [comment]
See #5005

**Comment by lampholder** [comment]
gitter also has a 'compose mode' (or something like that) which consumes <kbd>Enter</kbd> as line break rather than send message.

Closing this one, though, 'cause it does look like a dup of #5005

**Comment by t3chguy** [comment]
@lampholder it is a dup of 5005, which has been closed

**Comment by pouladpld** [comment]
There was no need for this in the first place. #5005 could be reopened.

**Comment by pouladpld** [comment]
Why people rushing to open or close issues before even understanding what the issue was about?!

**Comment by t3chguy** [comment]
The title of this issue is more apt than that of 5005, easier to reopen than reopen and twiddle a title.

**Comment by MacLemon** [comment]
Semantically correct would be to use Return (⏎) to create a new line and Enter (⌅) to submit the message. Since way too many people don't understand the significant difference between these keys, or have no idea that their laptop keyboard actually does have these keys absurd solutions come up.

My suggestion:
Insert a line break: Return (⏎)
Submit a message: Enter (⌅) or Control-Return (⌃⏎) (For keyboards lacking a real Enter key (which are pretty much none) and for people not knowing that their key indeed does have an Enter key (which are surprisingly common).)

**Comment by pouladpld** [comment]
@MacLemon Both Return (⏎) and Enter (⌅) on a PC keyboard? Where?!

**Comment by MacLemon** [comment]
I expect anyone to know where the return key is. Enter is either on your number-pad to the far right or by pressing fn-return if you have a small keyboard. Many people also remap a spare key to be an enter key.

**Comment by pafcu** [comment]
@MacLemon The very common keyboard I have in front of me label both keys "Enter".

**Comment by MacLemon** [comment]
@pafcu Ouch

**Comment by pouladpld** [comment]
@pafcu Same here

**Comment by quicktrick** [comment]
Riot for Windows (I haven't found its repository, sorry)

I vote for this feature too (Enter to make a new line, Ctlr+Enter to send).  It's a must!  Please, make it as soon as possible!  Thank you in advance!

**Comment by t3chguy** [comment]
PR in the works for this, made for after-switch-to-SlateJS

**Comment by w123475** [comment]
Any progress?

**Comment by t3chguy** [comment]
@w123475 https://github.com/matrix-org/matrix-react-sdk/pull/1966#issuecomment-453820189

**Comment by tanriol** [comment]
What's the way forward to having this option? Should matrix-org/matrix-react-sdk#1966 be updated or is this waiting for the universal keybinding UI?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/71321886-37faff00-24b8-11ea-9f8e-2408f0d66ba3.png)
Slack has the above as the configuration option for this which is even more vague, if ticked you need to Ctrl+Enter to send

**Comment by aybiss** [comment]
Me too!

**Comment by fulljackz** [comment]
Must have !

**Comment by PapaV** [comment]
It's been THREE YEARS, and developers can't do an elementary thing!

**Comment by aybiss** [comment]
Somebody screenshot this before the DD by people who don't know what a return key is.
