### ISSUE TITLE
We seem to have broken pill highlights on search results

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5007]
When you search for something you're meant to see a pill around the matching term in the search results.  It seems to have gone awol.

**Comment by lampholder** [comment]
I can't reproduce this on /develop on Chrome on Ubuntu or Mac OSX

@ara4n are you able to share the search term or the matching text to help diagnose/triage?

**Comment by grahamperrin** [comment]
I get a pill on the search term but not on the authors: 

![2017-09-15 19 12 38 riot 2](https://user-images.githubusercontent.com/192271/30497445-cc280326-9a4a-11e7-9695-49c491e5e2cb.png)

**Comment by turt2live** [comment]
This seems a bit temperamental about when to pill or not:
![image](https://user-images.githubusercontent.com/1190097/38518475-2f015a64-3bfa-11e8-9020-ad43cebdab67.png)

seems to work fine for code blocks:
![image](https://user-images.githubusercontent.com/1190097/38518478-34a05196-3bfa-11e8-94fa-ec32d675422c.png)

(keyword was `draft` in #riot-dev btw)

**Comment by yannicka** [comment]
On Riot Desktop 1.6.0, all results are not highlighted (search for "call" on "#riot-web:matrix.org":

![Peek 21-05-2020 12-04](https://user-images.githubusercontent.com/22885898/82548312-6e1dd700-9b5b-11ea-9808-c8536342ca1e.gif)

**Comment by t3chguy** [comment]
This could well be a Synapse bug as the Synapse FTS is what tells us what to highlight in each message

**Comment by poljar** [comment]
Isn't that a search across all rooms? If so results from encrypted search results won't have the highlight.

**Comment by t3chguy** [comment]
Shouldn't the seshat-backed search have the same API as the Matrix server backed one and thus do that too?

**Comment by t3chguy** [comment]
also looking at the gif, that one is `This room` only

**Comment by poljar** [comment]
Right, I think I forgot how the highlights work. Seems to be Seshat unrelated indeed.

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/9e86952d-601d-40c9-a56c-be4370d728b7)
![image](https://github.com/vector-im/element-web/assets/2403652/060f9060-6e7c-49b8-a248-03c9962e1e29)
![image](https://github.com/vector-im/element-web/assets/2403652/cb47ec25-6e98-4fca-9c82-fa4760859288)

Seems to work far more reliably now
