### ISSUE TITLE
Add obvious save button for renaming devices

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5012]

**Comment by lampholder** [comment]
I didn't even realise you _could_ rename the devices using the Device list in user settings :\

There's a lot wrong with this page, including that all (I think all) changes are instantly persisted (in a way that is entirely different to how room settings are persisted).

If we did want to address this specific problem in advance of a more comprehensive rework of settings, I might suggest something where:
- editability is demonstrated on hover
- clicking to edit actually opens a modal
- the modal gives the option to save/cancel

I'd be afraid though that adding this kind of save confirmation to _just this aspect_ of the user settings might create confusion about how the other user settings are saved, so it's probably worth tackling the problem more holistically.

I made a quick mockup to help me think through the issues, which I've attached here for posterity.
![image](https://user-images.githubusercontent.com/1922197/30321713-e9998874-97ae-11e7-86af-c2ec4859a708.png)

**Comment by turt2live** [comment]
The mockup overall looks good, although I'd personally be annoyed with a dialog. Instead, can the field change to just an input element with save and cancel icons on the right side?

**Comment by t3chguy** [comment]
isn't that section already struggling for space on low width displays?

**Comment by lampholder** [comment]
That's what I thought - a dialog _is_ annoying, but it's not a super common operation.

Something nicer would be something that replaced some of the junk you don't need to look at whilst editing (timestamp, ip) with some save/cancel options, but I'd rather not introduce a radical new settings modfication paradigm without thinking how it would apply to other bits of the UX :)

**Comment by turt2live** [comment]
/me quietly recommends the in-place edit paradigm everywhere ;)

**Comment by lampholder** [comment]
I think I agree, but I want to achieve emphatic consensus before committing to:
- doing that for all new UX
- opportunistically introducing it wherever we touch old UX

:smile:

**Comment by turt2live** [comment]
we did this
