### ISSUE TITLE
allow file uploader to redact file from server

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#5025]
so that the file itself is removed, rather than just redacting the event pointing to the file.  This would require:

* the server to keep track of who uploaded a file
* new endpoint for the user to request deletion of the file (maybe something like DELETE /_matrix/media/r0/download/{serverName}/{mediaId})

To figure out:
* how to propagate the deletion request to other servers?

Note that this may result in forwarded events pointing to no-longer-existing files.

(based on conversation starting from https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15052324193420585vPeiO:matrix.org)

**Comment by t3chguy** [comment]
so redacting a forwarded "copy" of the event might lead to the original being unintentionally deleted? (possibly if the original sender reposted using forward)

**Comment by uhoreg** [comment]
I thought forwarded events were marked as being forwarded, but it looks like they aren't.  I guess if you redact an event, it could prompt the user to ask whether the file should be deleted too, or if it should just redact the event.

**Comment by t3chguy** [comment]
they are not, and yeah sure it should ask, but then it'll need to make clear that it'll delete forwards and potentially the original too

**Comment by turt2live** [comment]
A case to consider (which is common with moderation): Someone else redacting your message, across homeservers. You won't be able to tell the other server to delete the file.

**Comment by turt2live** [comment]
Closing in favour of single tracking issue: https://github.com/vector-im/element-meta/issues/398
