### ISSUE TITLE
riot-web receives multiple m.room.aliases events from synapse when adding/removing aliases

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#5035]
one for each alias you add/remove, but each with the same (correct) content

**Comment by lampholder** [comment]
I've P3'ed this... because I've got no idea how sever it is, but it _sounds_ kinda P3ish.

**Comment by t3chguy** [comment]
not severe whatsoever, just pointless and weird

**Comment by t3chguy** [comment]
So this is because the aliases are added using the `/directory/` APIs, which only support adding one-by-one.

**Comment by t3chguy** [comment]
The UI no longer allows this to be done
