### ISSUE TITLE
Cannot reject invites to rooms you're (possibly) banned in

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5043]
### Description

If your server thinks you're banned from a room, you can't decline an invite. 
![image](https://user-images.githubusercontent.com/1190097/30462127-d2576b4e-9980-11e7-9df8-ad9e97c3c012.png)

Similar/related issues:
* https://github.com/vector-im/riot-web/issues/3666
* https://github.com/vector-im/riot-web/issues/3222 (might be what I'm describing here)
* https://github.com/vector-im/riot-web/issues/4374
* https://github.com/vector-im/riot-web/issues/4225

### Steps to reproduce (using https://github.com/vector-im/riot-web/issues/3666)

*Requires 2 accounts, each on different homeservers*

- Join a room with another user
- Have the other user ban you
- Have the other user unban you
* Have the other user invite you
* Try to decline their invite

The invite should just be declined, instead of persisting. 

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
If you're still experiencing this, please open an issue in https://github.com/matrix-org/synapse/
