### ISSUE TITLE
Devtools: Sending invalid m.room.message event in Riot queues it

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5062]
### Description

This is only possible with devtools, currently. Ideally the people using devtools would understand this kind of failure, but it does feel broken.

### Steps to reproduce

- Open `/devtools`
- Click "send a custom event"
- Set the event type to `m.room.message`
- Press send

The devtools dialog will tell you the event is invalid, but Riot tries to queue it anyways. It shouldn't be queued if the event was invalid.

Result: 
![image](https://user-images.githubusercontent.com/1190097/30525651-c0448574-9bc7-11e7-80ac-c6598affae16.png)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This bug highlights a gap in my knowledge - what is our philosophy on invalid events? Whose job is it to validate them? Should the server persist them? Or the client ignore them?

**Comment by turt2live** [comment]
The server is returning an error code, but the js-sdk is putting it in a backlog (which is the "Some of your messages have not been sent" bar). In my opinion, error codes representing malformed events should be treated as a warning to the user, but not re-queued.

**Comment by t3chguy** [comment]
The repro steps no longer work, Synapse seems to accept a `{}` event.

**Comment by turt2live** [comment]
I've since been convinced this is not a bug but rather a feature, for developer reasons. It's not really worth guarding the case.
