### ISSUE TITLE
add/remove widget events seem to show up in FilePanel

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5076]

**Comment by lampholder** [comment]
I wonder if this is the same cause as for https://github.com/vector-im/riot-web/issues/4480 which @uhoreg put down to:

> This is probably because FilePanel only filters for events containing a url (https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/structures/FilePanel.js#L69) which room avatar events have. It probably needs to explicitly filter out m.room.avatar events.

**Comment by t3chguy** [comment]
rather it should be filtered to `m.room.message` afaict

**Comment by anoadragon453** [comment]
I'm still seeing this today:

![image](https://user-images.githubusercontent.com/1342360/65872233-091d3300-e378-11e9-9f89-560fc1196f8e.png)

**Comment by turt2live** [comment]
This is because Synapse doesn't apply filters correctly: https://github.com/matrix-org/synapse/issues/4299

**Comment by anoadragon453** [comment]
The mentioned issue still mentions `limit` being ignored, but the rest of the issue has been fixed. Is this still a problem? I can't seem to reproduce it.

**Comment by t3chguy** [comment]
We now limit it to `m.room.message` only https://github.com/matrix-org/matrix-react-sdk/blob/5a3bda7eea016fc2a7081208af15c0cb54c05579/src/components/structures/FilePanel.js#L125
