### ISSUE TITLE
Folder structure for rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5077]
To allow tags with subtags with subtags. Ideal for people with a horrendous amount of rooms and want a strict structure

**Comment by lampholder** [comment]
I think these issues, addressing similar _sounding_ concepts, are *not* related:
https://github.com/vector-im/riot-web/issues/2454
https://github.com/vector-im/riot-web/issues/3266

Because I think this would be on a per-user basis, for arranging rooms into groupings dictated by each riot user (rather than by the room owner) - is that correct?

**Comment by turt2live** [comment]
Correct - this would be for the individual user to organize their rooms. If possible, it'd be nice to pull apart communities/subrooms to organize them. For example, if matrix grouped the dev chats with the general chats, I may want to pull out the dev rooms and put them in a different tag/subtag for "development stuff".

**Comment by turt2live** [comment]
I wonder how much of this is solved by groups + custom tags...

**Comment by turt2live** [comment]
Worth noting that a different approach may be better for the UX. The idea is to be able to provide a way for people to organize their rooms such that they can have a dense amount of information without having to see it all the time (ie: grouping all the spec-related rooms into one folder).

**Comment by t3chguy** [comment]
Spaces

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-web/issues/5077#issuecomment-876286686

@t3chguy, that solely provides one level of depth, to my knowledge.

**Comment by t3chguy** [comment]
<img width="263" alt="Image" src="https://github.com/user-attachments/assets/b1a69ec7-0909-40ae-a5ed-c74186855cab" />

@RokeJulianLockhart that is simply not true
