### ISSUE TITLE
riot silently swallows M_FORBIDDEN errors from invites

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5083]
so you have no feedback about the failure

**Comment by t3chguy** [comment]
This causes https://github.com/vector-im/riot-web/issues/4733

**Comment by richvdh** [comment]
The problem is here: https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/utils/MultiInviter.js#L134. We bail out early from the loop so never resolve the deferred.

**Comment by MadLittleMods** [comment]
Haven't tested in the app but it looks like we do at least `reject` the error when it's considered `fatal` so it ends up in the async promise chain somewhere now, https://github.com/matrix-org/matrix-react-sdk/blob/9b99c967f4d65e3446a18a677fa4010612958d90/src/utils/MultiInviter.ts#L286 (probably at least logged somewhere)
