### ISSUE TITLE
riot reproducible crashes (windows - webclient(chrome) and desktopclient) when accepting a voice or video call

### ISSUE THREAD

**Issue by elsbiet** [vector-im/element-web#5084]
### Description

riot passes away without any trace.

### Steps to reproduce

a starts riot(web client or desktop client) and login
b invites a to a voice or video meeting
a accepts the call
a's riot crashes

Log: sent/not sent?  no - as i do not know where to find it.  

### Version information
matrix-react-sdk version: 0.10.3
riot-web version: 0.12.3
olm version: 2.2.1

- **Platform**: web (in-browser) or desktop? web and desktop

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? chrome (version  unknown)
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? windows

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? windows
- **Version**: 10.? (not my pc)
### remark
skype is unable to access the camera of a's ps. maybe the crash is related to this fact.

**Comment by spellauge** [comment]
the camera problem on a's pc was fixed. skype is now able to use the camera but riot still crashes without any trace.

**Comment by SimonBrandner** [comment]
@elsbiet, is this still a problem?

**Comment by elsbiet** [comment]
usure as i can no longer reproduce the environment because i no longer have access to a's computer.
