### ISSUE TITLE
Desktop notifications show square pic rather than rounded pic

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#51]

**Comment by dbkr** [comment]
HTML5 notifications just get an image that you supply to them, so the only ways to do this would either be to generate a rounded image on a server or do it on the client by doing image manipulation in a canvas element and extracting a picture as a data uri or something: is it worth it?

**Comment by turt2live** [comment]
fwiw, round pictures would appear weird to me. Not many chat applications do this, so it could be jarring.

**Comment by MadLittleMods** [comment]
I think we're good to close this. Native platforms do their own things. Windows toast notifications are square and going against the native behavior would be weird for that platform.
