### ISSUE TITLE
Add button "Clear formatting" in Riot RTE interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#5102]
Very often we paste text from webpages or office documents, that contain unnecessary formatting. Now we must paste it to notepad for clear formatting, and after this - move to Riot.

Will be good to have button "Clear formatting" in Riot, like in Google Docs.

**Comment by t3chguy** [comment]
You can ctrl shift v
Or right click and paste as plain text

**Comment by MurzNN** [comment]
Yes, but only I, you and some advanced users know about this tricks :)

**Comment by natrius** [comment]
There is a "Paste and match style" that should be this one.

Anyway, when pasting with "CTRL + Shift + V" the text is pasted twice. Tested on the electron app, via the homepage itself it works fine and just paste it once. (hope its still correct on riot-web ?)

**Comment by t3chguy** [comment]
The RTE is long gone
