### ISSUE TITLE
Feature request: ability to bookmark message (favorite) and list all bookmarked in tab

### ISSUE THREAD

**Issue by daltinn** [vector-im/element-web#5108]
Need ability to bookmark some message (best to bookmark multiple message at time and stack them) and show them in some place with show message and link to place in chat, similar to notification tab but for bookmarked message. Add bookmark message selection in menu for message (three dot on the right of message, between "Forward Message" and "View Source").

For message in bookmark tab, will be nice to have menu with some functions:
- "Go To" - link to place in chat
- "Quote" message in original chat (open original chat and quote message)
- "Forward Message" - as for any message

This function need for all client with sync (may be need changes to protocol).
Will be nice to have ability for organize bookmark by category or tag.

Usage example: 
- sometime hard to find important info in active chat room 
- want to read later (links, large post )
- for reply need long time (kind of to-do list)

Similar function already present in Rocketchat

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/4406

**Comment by uhoreg** [comment]
dup of #2938, though this issue mentions some features not included in the other

**Comment by t3chguy** [comment]
Closing as duplicate
