### ISSUE TITLE
Country names are hardcoded in English

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5113]
### Description

Country / region names used for international phone number prefixes are hard-coded to be in English in https://github.com/matrix-org/matrix-react-sdk/blob/master/src/phonenumber.js#L32. 

### Steps to reproduce

- Go to user settings
- Choose a language with 100% coverage, such as Deutsch
- Click the phone prefix selector
- Notice that it says e.g. "United Kingdom" in English (_perhaps_ acceptable) and "Germany" (clearly not correct).

### Version information

Current git

**Comment by pafcu** [comment]
Potentially the names from https://github.com/umpirsky/country-list could be used for translations.

**Comment by lampholder** [comment]
I guess this was just missed as part of the internationalisation efforts - we should fix that.
