### ISSUE TITLE
overriding avatar for a specific room changes your avatar in user directory

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5123]
i used /devtools to cheekily change my avatar in a test room, which worked amusingly well... other than it overrode it for user directory search results too!

**Comment by t3chguy** [comment]
(same goes for display name)

**Comment by t3chguy** [comment]
I guess Synapse caches the latest avatar_url/displayname value it sees

**Comment by MadLittleMods** [comment]
Closing in favor of the Synapse issue to track this: https://github.com/matrix-org/synapse/issues/5677
