### ISSUE TITLE
riot can't display webp images

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5127]

**Comment by t3chguy** [comment]
related https://github.com/vector-im/riot-web/issues/1527

**Comment by turt2live** [comment]
This is a browser limitation that we can't really work around.

**Comment by Mikaela** [comment]
Do you have links to upstream issues or how do browsers limit it? Most of browsers have been supporting webp for some time and some are bringing it in next versions

https://caniuse.com/#feat=webp

**Comment by turt2live** [comment]
The browsers that don't support it are implicitly limited. 3 years ago when this issue was opened the landscape was very different, and regardless of browser support today the issue would be closed as an upstream problem.

**Comment by Mikaela** [comment]
I am still confused.

When I browse to a page with webp content, it looks like this:

![kuva](https://user-images.githubusercontent.com/831184/91936832-52e56a80-ecf9-11ea-9f76-d52ac3c0dca4.png)

However when I download the image and send it to Element, it looks like this:

![element-webp-vs-png](https://user-images.githubusercontent.com/831184/91936856-6264b380-ecf9-11ea-881b-f50a7190814b.png)

The only issue I saw was that copy-pasting a webp to Element turns it into a png.

Direct link to the test picture: https://www.gstatic.com/webp/gallery/1.webp

What is the upstream issue here exactly, is it reported and known at upstream? I fear I don't understand enough to do that by myself.

Firefox 81.0b4 (64-bittinen) (update pending restart), on Microsoft Windows [Version 10.0.19041.487] / Element 1.7.4 within Radical.

**Comment by turt2live** [comment]
That's a server side issue relating to thumbnails

**Comment by Mikaela** [comment]
Is there an issue about that I could follow? I can only find https://github.com/matrix-org/synapse/issues/4382 which is closed as fixed. I am on Feneas.org, which should be on Synapse v1.19.1.

**Comment by turt2live** [comment]
They're using a customized media repo - you'll have to contact them to enable it.

**Comment by Mikaela** [comment]
Thank you, I opened an issue [towards them](https://git.feneas.org/feneas/association/-/issues/128).

**Comment by t3chguy** [comment]
> The only issue I saw was that copy-pasting a webp to Element turns it into a png.


That's not Element doing that but your browser.

I copied WebP from https://developers.google.com/speed/webp/gallery and pasted into http://madebyevan.com/clipboard-test/

![image](https://user-images.githubusercontent.com/2403652/91956342-7231c700-ecfc-11ea-82f7-94cfb537ed0f.png)


And it pasted a `image/png` file
