### ISSUE TITLE
Commands popup is mangled with narrow window

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#5138]
![screen shot 2017-09-29 at 11 21 48](https://user-images.githubusercontent.com/986903/31012087-6bef00cc-a508-11e7-98f6-32fecdb29dcd.png)

**Comment by lampholder** [comment]
Yuk

**Comment by MadLittleMods** [comment]
This appears better nowadays where each one is on their own line. Squishing all the way still shows them separately and is technically horizontally scrollable to see the content.

![](https://user-images.githubusercontent.com/558581/131803327-c968b74c-c6bf-47a7-923a-24fca413638a.png)

---

![](https://user-images.githubusercontent.com/558581/131803374-7352aa02-cb30-43e4-875b-0722e4acb610.png)
