### ISSUE TITLE
Room option state is not clear enough in the quick dropdown menu

### ISSUE THREAD

**Issue by gagarine** [vector-im/element-web#5146]
### Description
On each room you can quickly change some status. But the state of "Favourite", "Priority" and "Direct chat" is not clear enough.

![screen shot 2017-10-02 at 13 27 01](https://user-images.githubusercontent.com/164074/31075567-7387b6b0-a776-11e7-9554-0bdd22f17c0d.png)

For the moment, it's only but in bold. It would be better to have some kind of checkbox similar to the notification level.

### Version information
-  OS: MacOS
-  Version: Version 0.12.4 (0.12.4)

**Comment by lampholder** [comment]
I'm not quite sure I understand your suggestion yet - do you mean you'd like to see the favourite/low priority/direct chat rendered as a 'sliding scale' of mutually-exclusive options like the notification levels?

I agree that it perhaps isn't as clear as it might be - 'favourite' and 'low priority' _are_ mutually exclusive, but 'direct chat' is an orthogonal property.

Can you provide a bit more detail about what you're suggesting?

**Comment by gagarine** [comment]
Ok... I try to draw :/.

![31075567-7387b6b0-a776-11e7-9554-0bdd22f17c0d](https://user-images.githubusercontent.com/164074/31178045-222b20ec-a918-11e7-9e67-54b3aea6e683.png)

Their is multiple problems:
- mutually-exclusive is not clear
- state (on/off) is not very clear (it's simply bolder)

So I think we can solve that by adding some kind of visual "check box" and radio-button. Also add a separation eventually between "direct chat" and other options.

**Comment by novocaine** [comment]
No longer an issue as it's now clear in EW.
