### ISSUE TITLE
quote text is too dark on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5154]
i fixed this at some point but someone must have broken it again

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/31175807-676f46ca-a908-11e7-8b07-1ca41f9e0e0f.png)
Setting P2 minor 'cause it looks to me to be annoyingly dark rather than enragingly/unusably dark :)

**Comment by bhauer** [comment]
Would *really* appreciate this one getting bumped in priority.  My older eyes struggle to read quoted text in the dark theme, and the alternative of using the light theme is simply not an option since that causes a totally different and worse eye strain.  Thanks!

**Comment by NikolaPi** [comment]
I could be missing something, but in new version this looks like it may have been fixed. Quotes appear to now be the same color as the original post.
![blocktest](https://user-images.githubusercontent.com/42226280/92335034-f14e3480-f047-11ea-9d67-315935bef399.png)

**Comment by t3chguy** [comment]
That's a reply, not a quote

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/92364188-9b7e9880-f0ea-11ea-8d5c-555ed40d33c7.png)
