### ISSUE TITLE
Features for Status

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5157]
* [x] Ability to block room creation on the server (other than for mods/admins)
* [x] `@channel` style bulk-notification, but limited only to mods/admins within the room.
* [x] emoji reactions (when ready)

**Comment by pablanopete** [comment]
- [ ] Threads for conversations 
- [ ] "Pinning" important items that you can look into similar to Slack

**Comment by t3chguy** [comment]
Pinning: #5142

**Comment by pablanopete** [comment]
thanks @t3chguy

**Comment by ara4n** [comment]
* [ ] i’m guessing it’s just a matter of timembefore wanting active policy servers to enforce antiscam in rooms regardless of the origin homeserver. whilst folks on the local server are protected by the current code, we’ll want visitors from other servers to be protected too.

**Comment by ara4n** [comment]
* [ ] ability for admins on the server to be invited to rooms (currently the invite-blocking blocks invites to admins too, which is probably not what is desired)

**Comment by ara4n** [comment]
* [ ] mobile invite link that has home server auto filled

**Comment by pablanopete** [comment]
- [ ] ability to edit messages instead of delete / redact only 
- [ ] fine grained user joining display messages (EG. user joins / changes name)

**Comment by hex-m** [comment]
This issue is confusing to me. Can we clean this up?

> Threads for conversations

#2349 

> i’m guessing it’s just a matter of time before wanting active policy servers to enforce antiscam in rooms regardless of the origin homeserver. whilst folks on the local server are protected by the current code, we’ll want visitors from other servers to be protected too.

Not sure what this means. Room moderation features are requested in #11740. A server-wide moderation UI is requested in #4125. And there is also [mjolnir](https://github.com/matrix-org/mjolnir).

> mobile invite link that has home server auto filled

Not sure what this means. Maybe #12472?

> fine grained user joining display messages (EG. user joins / changes name)

I think we have this.

> :partyparrot: dagger would love custom emojis

#2648

**Comment by t3chguy** [comment]
Indeed, closing out as pretty much all tracked elsewhere - thanks
