### ISSUE TITLE
Open downloaded files directly

### ISSUE THREAD

**Issue by mtausig** [vector-im/element-web#5162]
### Description

It would be convenient, to be able to open downloaded file directly from the riot desktop client without having to open the stored files manually. 
It should work similar to the download dialog in a web browser, where you can choose between "open with" and "save as".

### Steps to reproduce

- Click on a file in a room
- The save file dialog opens

Instead of the save file dialog, a dialog as described above should open.

### Version information

riot 0.12.4, Ubuntu 16.04 Xenial 64 bit

**Comment by t3chguy** [comment]
There is now a toast which comes up when the download is completed with an Open button which you can use
