### ISSUE TITLE
Riot/Chrome state can result in inability to load new messages 

### ISSUE THREAD

**Issue by heyakyra** [vector-im/element-web#5174]
### Description

Riot in Chrome has gotten into a sate where only the messages that were received up to a certain point can be loaded. Trying to view a room with unread messages results in a loading spinner and eventual error: 

> "Connectivity to the server has been lost.
> Sent messages will be stored until your connection has returned."

Trying to post a message seems to work, but the message is gone upon refreshing the page. Viewing a room with new messages (so that they are marked as read and the room isn't in bold anymore) is reset when refreshing the page. It seems nothing can be saved or loaded from after a certain point in time. 

When logging in from an incognito window, the messages that were attempted to send but not visible after refreshing the page *did* in fact go through, but riot couldn't save them locally. 

Have also had strange behavior in Firefox #5173

### Steps to reproduce

- Reproducibility unknown

Log: sent

### Version information

 **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome Beta v62
- **OS**: Fedora 27 
- **URL**: affecting /app /experimental and /develop

**Comment by kittykat** [comment]
I use Chromium and have not come across this issue myself. As this is an old issue, I will close it for now. If you are still experiencing it, please reply with @kittykat and I will re-open it
