### ISSUE TITLE
Handle markdown in topics

### ISSUE THREAD

**Issue by afranke** [vector-im/element-web#5180]
Currently Markdown is not interpreted in the topic. This would be really handy to have cilckable links displayed in a nice (and short) way.

**Comment by t3chguy** [comment]
The issue is that topic doesn't support formatting
So even if the markdown gets parsed to html when you set it it wouldn't work, the matrix m.room.topic spec would need to allow html/formatting

**Comment by t3chguy** [comment]
To add to this, markdown isn't interested on receiving but instead on send

**Comment by svoop** [comment]
Full Markdown is not even possible, allowing `[foo](bar)` and `<br>` would already make a big difference.

**Comment by stratosgear** [comment]
I agree.

Our use case is to use the topic to include useful links relative to the chat channel.  As of now, the links appear very large and confusing (displaying the whole url).  We'd love to have [link](some.large.url) as an option

**Comment by Raph33** [comment]
I'd love to revive this issue. Mattermost supports markdown in topics, and it's incredibly useful to give users quick access to key document and information. 

![Screen Shot 2020-06-27 at 9 29 11 PM](https://user-images.githubusercontent.com/27868414/85937934-3f62f100-b8bd-11ea-9981-2f7c128fd8df.png)

**Comment by MexHigh** [comment]
This may also be a nice addition for the new Spaces. It uses the topic for it's description.
Communities have the ability to use HTML in the description which is really handy, I think.
See #5261

**Comment by tmonz** [comment]
Fully support this request for improvement.
Coming from mattermost, the rendered links [foo](bar) has been used for some many things ... but in particular notably improved readability.

**Comment by robertfoss** [comment]
This is really helpful for organizing a room, and providing information that is useful to members. Emojis + URLs are both really great tools in room descriptions.

**Comment by mimtud** [comment]
Great to see that there is already a pull request draft.
To add: Note that the issue also applies to the topics of spaces. Would that already be covered as well, if it gets fixed for the room topics?

**Comment by t3chguy** [comment]
Yes, a Space is a Room with type=m.space

**Comment by Johennes** [comment]
This now has a spec proposal in [MSC3765](https://github.com/matrix-org/matrix-spec-proposals/pull/3765) and implementation attempts as a labs feature in https://github.com/matrix-org/matrix-react-sdk/pull/8215 and https://github.com/matrix-org/matrix-js-sdk/pull/2272.

**Comment by afranke** [comment]
It doesn’t seem to be working at the moment. I could not find any related settings in labs or elsewhere. I tried to set a Markdown topic in one room and there’s no rendering in any of the places where the topic appears AFAICS.

**Comment by t3chguy** [comment]
<img width="1135" alt="Image" src="https://github.com/user-attachments/assets/6c22ccc6-6f3b-4562-aa46-75deed028382" />

@afranke develop.element.io

**Comment by afranke** [comment]
Ha, so it’s been on develop for almost 3 years now, but not on stable even after all this time? 🤔

**Comment by t3chguy** [comment]
@afranke yes - the MSC hasn't been accepted by the Matrix Protocol yet. https://github.com/matrix-org/matrix-spec-proposals/pull/3765

**Comment by Johennes** [comment]
At least it's in FCP now. So hopefully shouldn't be another 3 years until it becomes stable. 🫠

**Comment by t3chguy** [comment]
Only things promoted to Beta are accessible "Labs" on stable. It is not a Beta therefore it needs `show_labs_settings` in config.json to show up.
