### ISSUE TITLE
notif settings from web is broken

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#5181]
my 1:1 with Matthew is stuck on notifying loudly when a msg comes in, edspite the UI telling me it's set to 'all messages'. When I try to toggle the setting to 'all messages (loud)' it has no effect and everytime I open the menu the selection is back to 'all messages'

**Comment by lukebarnard1** [comment]
I can't reproduce this. @AmandineLP have you seen this again?

**Comment by t3chguy** [comment]
Given lack of ack presuming fixed
