### ISSUE TITLE
Computer freezes when uploading large file in encrypted room

### ISSUE THREAD

**Issue by abueide** [vector-im/element-web#5183]
### Description
My computer froze when I tried to upload a 1.1 GB file to an encrypted room. I was mainly just curious if there was a file size limit. I forgot about encryption.

### Steps to reproduce
Attempt to upload a file >1 GB in an encrypted room.

Describe how what happens differs from what you expected.
It should not freeze the computer when encrypting a large file.
### Version information

- **Platform**: Desktop, does not occur on the web version.

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Arch Linux
- **URL**: riot.im/app

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.12.6

**Comment by lampholder** [comment]
Was this uploading to matrix.org?

There's a (configurable) file size limit set to 100MB on matrix.org; interesting that that seems to have... not worked correctly in the encrypted room.

**Comment by lampholder** [comment]
Was this on matrix.org?

Synapse has a configurable max media filesize limit (set at 100MB on matrix.org).

Interesting though that something did work here...

**Comment by t3chguy** [comment]
riot has no way of knowing the limit until synapse rejects the file
after it finishes uploading

**Comment by lampholder** [comment]
Could the homeserver advertise its max filesize limit (a la https://github.com/vector-im/riot-web/issues/5193)? Then Riot could handle the UX better.

Is there a reason we _wouldn't_ want to publish max filesize information?

**Comment by turt2live** [comment]
The freezing was probably related to riot trying to encrypt a 1.1gb file. That's a fair amount of data to shove through an encryption stream, particularly if the system ends up swapping to disk due to memory constraints.

**Comment by Palid** [comment]
Testes by unyin on community testing session, could not reproduce anymore. Closing!
