### ISSUE TITLE
RTE Mentions popup selected item doesn't stay visible

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#5206]
Trying to tab complete a user where there are a lot of possible users (eg. 'Rob' in #riot:matrix.org) results in the selected user being outside of the popup a lot of the time, although I'm currently failing to repro this reliably enough to record it.

**Comment by lukebarnard1** [comment]
>the selected user 

The selected user should always be the first user.

>being outside of the popup

Could you elaborate on this, @dbkr?

**Comment by turt2live** [comment]
Related based on symptoms: https://github.com/vector-im/riot-web/issues/4617

**Comment by t3chguy** [comment]
This got fixed
