### ISSUE TITLE
No notification of group invite being accepted/declined

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5227]
### Description

There should probably be something, somewhere, somehow.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
(or accepted)

**Comment by novocaine** [comment]
@turt2live is this a communities bug, or does it still exist in Spaces?

**Comment by turt2live** [comment]
This is communities before it was called communities.
