### ISSUE TITLE
Group members should update in realtime

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5228]
### Description

Otherwise when someone accepts an invite, you have no idea until you re-open the group. The RHS should also show who has a pending invite.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This also affects people who just joined a group: They don't see themselves on the RHS.

**Comment by lampholder** [comment]
Yep - this is a known gap in the current impl (but definitely something that needs addressing).

**Comment by turt2live** [comment]
Updated description to also include pending invites.

**Comment by lampholder** [comment]
This still seems to be broken (as per discussion this morning).

**Comment by lampholder** [comment]
There are two aspects to this:
- invities should be:
    - visible
    - locally echoed after issue
- realtime updates to membership are (hugely) desirable but are being _excluded_ from the current phase

**Comment by lampholder** [comment]
I think we should scope this issue to the lack of real time updates, and leave #5391 to track the bug that we're not showing invites in the RHS (and that locally issued invites should echo locally).

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
