### ISSUE TITLE
No obvious way to go back to group dashboard from looking at a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5229]
### Description

This is only awkward for when you're looking to manage several groups at a time. It'd be nice to be able to do that from the top of the screen instead of having to travel to the bottom left and click the groups icon again.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome, 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
The back button works :D

**Comment by turt2live** [comment]
I rarely use the back button personally. In-app hints are much more preferable ;)

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
