### ISSUE TITLE
If no rooms, RHS feels too empty

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5233]
### Description

![image](https://user-images.githubusercontent.com/1190097/31459373-3d164c3e-ae80-11e7-8802-a7a4d73e1f8a.png)

Something like "There are no groups, consider adding one below".

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
