### ISSUE TITLE
Group avatar not saving immediately is inconsistent

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5234]
### Description

I spent a good 10 minutes debugging an issue with flair because I thought the avatar was changed without needing to hit save, like with UserSettings and RoomSettings. For consistency, it should be the same.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/5208

At the moment we know we have an unholy mix of paradigms; the goal is for all changes to persist immediately (as per the discussion on #5208)

**Comment by lampholder** [comment]
I'm pushing the settings-paradigms-resolution into the next phase :( :( :(

**Comment by t3chguy** [comment]
This looks to be stale as we have now moved to an explicit save everywhere
