### ISSUE TITLE
Prevent leaving from specific groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5243]
### Description

For cases such as workplaces, an overarching admin should be able to define specific groups as manual membership, including the prevention of leaving. This would be for +developers:company.com or +support:company.com, where employees aren't allowed to say they aren't part of a department (logically).

However, there still needs to be a way for people to be removed (people quit, get fired, transferred, etc). 

This should prevent FFA groups, as described in https://github.com/vector-im/riot-web/issues/5242. A group should either be 'forced membership', 'ffa', or 'default' (current behaviour). Not any combination of the 3.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I think this is an absolutely key feature for groups.

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
