### ISSUE TITLE
Auto-invite/join rooms as part of a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5244]
### Description

If I join the +woodworkers group, I also probably want to be in the #woodworkers chat if I'm not already.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16490
