### ISSUE TITLE
Should be able to /invite entire communities to rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5250]
### Description

Either through commands or through the "Invite to this room" UI, I should be able to invite a group to the room.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yep - this will be great.

**Comment by dkasak** [comment]
The title should probably be changed to mention communities instead of groups.

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
