### ISSUE TITLE
Powerlevel syncing for members of a particular group in a room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5251]
### Description

Ie: All current members of +core:matrix.org should be moderator. If someone leaves, they get demoted to the next most appropriate value (default PL).

This should be overridable with per-user power levels.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I have opinions on the implementation of this, but 100% agreed this is how the feature should be experienced by users/group admins.

**Comment by turt2live** [comment]
What are your opinions on the implementation? Just curious in the event someone (myself) gets bored and decides to write a bunch of code.

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
