### ISSUE TITLE
Aliases for groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5252]
### Description

Much like aliases for rooms, aliases for groups would be a potentially useful feature. The use case would be to have different variants of the group (+woodworkers, +woodworkersguild, +woodworking, etc) or just to have the cross-server feel.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by thekyriarchy** [comment]
Should this be filed against synapse instead/in addition to here?

**Comment by turt2live** [comment]
It should be against matrix-doc, but the group docs aren't there. Then it falls to synapse, which isn't monitored as closely. So here is the best chance of it being seen, prioritized, and implemented. Arguably it is coming from a user-facing perspective and not a backend perspective, but happens to require a spec/backend component to be implemented (ie: "As a user, I'd like to be able to set multiple aliases to by groups").

**Comment by thekyriarchy** [comment]
Ah, I see. Thanks! 

Also curious of whether group aliases will be case insensitive as there is already #617 and #618 open for MXIDs and rooms

**Comment by turt2live** [comment]
They're currently enforced to be lowercase in the synapse RC

**Comment by thekyriarchy** [comment]
Just so it's mentioned explicitly, it should probably also be possible to change the main/canonical alias

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17244
