### ISSUE TITLE
Pill-ify users, groups, and rooms in a group's long_description

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5256]
### Description

For when you want to feature a room/user in more detail. Eg: `Owners and operators of t2bot.io. Primary contact is @travis:t2l.io`.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
I'm glad I'm not the only one who wants Pills everywhere :smile:

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
