### ISSUE TITLE
Group-ception

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5259]
### Description

Groups in groups to imply multiple membership. For example, a member of +developers would also be part of +employees.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
This has potential to be good and potential to be unlimitedly complicated :laughing:. It certainly needs thought before progressing.

**Comment by thekyriarchy** [comment]
Maybe this could be solved by creating an organizational hierarchy of the rooms within groups. For example, the optional "lobby" room as a top-level room, with other sub-level rooms operating as lobbies of sub-"groups". Are there use cases that this misses and that group-ception would solve?

**Comment by jfrederickson** [comment]
@heyakyra I'm not sure what you mean by "lobbies" there, but it seems like that wouldn't give you the ability to grant only certain people in an organization access to a room... right?

(The assumption here being that at some point in the future, you'll be able to grant people access to a room contingent on group membership.)

**Comment by DonaldTsang** [comment]
Well you guys should take a look at Discord and get some ideas. Sub-categories in Discord servers are common.

**Comment by t3chguy** [comment]
Resolved by Spaces
