### ISSUE TITLE
RTE/WYSIWYG/Markdown for group long_description

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5261]
### Description

To make it clear how to format the content, as it accepts HTML (apparently).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
There's a vague plan to reuse the RTE here and have the description stored as HTML (but written in 
rich text or markdown)

**Comment by turt2live** [comment]
Updated the title to better reflect what people are asking for.

**Comment by MexHigh** [comment]
Just to add more info: With the new Spaces Beta feature, the Space description does not allow HTML or Markdown in any way as far as I can see.

![image](https://user-images.githubusercontent.com/50419884/118980494-d1626500-b979-11eb-8cc0-b4d9dfad675f.png)

**Comment by t3chguy** [comment]
The Matrix spec for spaces doesn't support it. It uses `m.room.topic` which is plaintext only.

**Comment by t3chguy** [comment]
Communities are going away. Spaces doesn't have this at this time and it isn't clear if it will.
