### ISSUE TITLE
Adding "Accept" in the invite notification menu

### ISSUE THREAD

**Issue by thepaka** [vector-im/element-web#5271]
### Description

Invitations can only be rejected when clicking on the red icon.
That can be confusing for newcomming users. 
So I propose to add "Accept" in this menu.

![image](https://user-images.githubusercontent.com/5007328/31511128-04a06fbc-af87-11e7-9660-856a8bb861f4.png)

### Version information

- **Platform**: all
- **Browser**: all
- **URL**:  riot.im/app
matrix-react-sdk version: 0.10.4
riot-web version: 0.12.4
olm version: 2.2.1

**Comment by lukebarnard1** [comment]
AFAICS, this is blocked on an "Accept" icon appearing next to the option to accept the invitation.

**Comment by t3chguy** [comment]
the whole accept invite accept logic is in RoomView so needs to be thrown out to MatrixChat or something to be reusable

**Comment by t3chguy** [comment]
annoyingly I already started on this but can't find it and it stalled

**Comment by lukebarnard1** [comment]
Ah okay, no worries @t3chguy. I hadn't realised that there was specific accepting logic that needed moving, assumed it would be a quick `join_room` dispatch now that we have that at our disposal.

**Comment by t3chguy** [comment]
I may have missed a trick but it seemed like RoomView had a load of stuff for accepting invites

https://github.com/matrix-org/matrix-react-sdk/blob/8c84c3f92906c49fd9ff17002fdafdc4efba0f35/src/components/structures/RoomView.js#L766-L836

like adding it to the DM map if appropriate

**Comment by lukebarnard1** [comment]
Yep you're right. It'd be nice to factor out the `join_room` "Set MxID" dialog to `ONBOARDING_FLOW_STARTERS` of `MatrixChat` at the same time, whilst accounting for 3pid invites. The DM stuff would be trickier 😕

**Comment by turt2live** [comment]
We removed this menu entirely.
