### ISSUE TITLE
Flair on image/file uploads

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5274]
### Description

Please add :)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
/me realises he's slapping bug/feature on some of these somewhat nondeterministically :\

**Comment by lampholder** [comment]
I'd flagged this as a release-blocker, 'cause I thought it was a trivial bug to fix. However, looking at the image/file upload entries in the timeline, I'm not 100% certain that just including the flair next to the name as per normal messages would look right (it might make interrupt the existing 'user verbed noun' readability).

So this certainly isn't a no; it's just an acknowledgement that it's not important enough to do the thinking we'd need to do to make sure we were doing the right thing for the first release 😁

**Comment by turt2live** [comment]
I'm not strongly attached to the feature. Ticket was created as a result of an immediate reaction to not seeing flair. 

Much like /me being a pill, it sounds cool in theory, but the UI/UX might be a disaster.

**Comment by turt2live** [comment]
This is more of a feature request than a bug ftr.

**Comment by turt2live** [comment]
Overall I'm not convinced that this should actually be a thing. Of course if someone else feels otherwise, this can be re-opened or a new issue filed.

**Comment by turt2live** [comment]
oh wait, this is flair not pills... /me re-opens

**Comment by SimonBrandner** [comment]
As far as I know, this should work now
