### ISSUE TITLE
Ability to ban users from groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5320]
### Description

In a world where https://github.com/vector-im/riot-web/issues/5242 is implemented, people should be able to banned from groups.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
