### ISSUE TITLE
It's very surprising that searching for matrix-dev doesn't return #matrix-dev:matrix.org as the top hit

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5348]
when adding it to a group

**Comment by turt2live** [comment]
or really anything matrix
![image](https://user-images.githubusercontent.com/1190097/31777208-c0cf5ffe-b4aa-11e7-8623-664cc50b2559.png)

**Comment by lampholder** [comment]
Do we match the domain part of the room alias?

**Comment by ara4n** [comment]
part of the problem here is that we're searching topics. let's not search topics.

**Comment by lukebarnard1** [comment]
We're now not searching through topics, which has improved the situation. But searching "matrix" instead of "#matrix" still gives decidedly un-matrix-y results, maybe because rooms have aliases which have the "matrix" domain in them.

**Comment by turt2live** [comment]
It might be best to not consider the domain part. For added complexity, only consider it if the search has a colon?

**Comment by lukebarnard1** [comment]
I'd vote for only considering the localpart, for simplicity. I suppose the edge case there is two rooms with the same alias localpart but differing serverparts.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
