### ISSUE TITLE
Add rooms to group autocomplete truncates too early

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5350]
### Description

![image](https://user-images.githubusercontent.com/1190097/31777242-d96257ce-b4aa-11e7-8ff5-7489f686843c.png)

The last one is `milkshakesoftware/PreMailer.Net`. There's enough space for it to continue, so it should use that space.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment]
Spaces are now in beta
