### ISSUE TITLE
Fields in group edit view appear to grow as you type.

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5351]
### Description

See gif.
![topicmoving](https://user-images.githubusercontent.com/1190097/31777511-733f883a-b4ab-11e7-954f-445dff5f7bcc.gif)

### Steps to reproduce

- Repeat steps in gif

They probably shouldn't do that, and should instead behave like rooms where each expands independently, but only when you hit the absolute right edge, not the padding.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment]
Spaces are now in beta
