### ISSUE TITLE
we need a spinner after you invite rooms or people to a group

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5353]

**Comment by lampholder** [comment]
Ideally we'd show the pending invites as per rooms (!) - are you saying you want a spinner as a stopgap?

**Comment by turt2live** [comment]
A spinner between the send button and it showing up in the UI would be ideal. Currently when you send a kick, ban, invite, etc it can take a while to send, leading to confusion for a couple seconds.

**Comment by t3chguy** [comment]
Groups are on their way out
