### ISSUE TITLE
No way to disband a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5354]
### Description

This would be helpful to release the ID and start over, or if the community falls apart and no one wants to maintain it anymore.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lectrode** [comment]
(Adding some search terms to make this a tad easier to find)
delete community
remove community
Something went wrong whilst creating your community Group already exists

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
