### ISSUE TITLE
Show groups the user has publicized in MemberInfo

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5366]
### Description

The title should be fairly clear. But just in case,
![image](https://user-images.githubusercontent.com/1190097/31806193-747a02d4-b523-11e7-917b-035e9596d8e4.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
FTR I'm P3'ing a bunch of these groups feature requests to represent that they're "not something we're committed to developing in the immediate term" - I fully expect that after we've had a chat about groups priorities a bunch of these will become higher priority :smile:

**Comment by turt2live** [comment]
Closing because its from the groups era. If someone wants this for spaces, please open a new issue.
