### ISSUE TITLE
Notifications panel, and room unread count, don't include keyword notifications

### ISSUE THREAD

**Issue by heyakyra** [vector-im/element-web#5382]
If keyword notifications are enabled, they only go to push notifications, which if missed are really difficult to track down because there is no other way to find out where the title bar notification count is coming from, and the user simply has to go from room to room until the notification count disappears, and then to find the notification itself has to manually search the room! Very bad UX which would be fixed by adding the keyword notification to the room unread count as well as the notification panel

**Comment by lampholder** [comment]
I think the world of notifications (still) needs some serious thought :cry:

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/3339
