### ISSUE TITLE
Configure visibility of group details (description, members, room-list)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#5389]
Ultimately we want to support more fine-grained controls for which rooms/people/etc. can be seen by members/non-members/etc. of a given group.

As a high-value quick win, however, we want to implement a flag on groups that dictates whether a user who is _not_ a member of that group can see any of the group details.

I think we should avoid calling this feature _'public' or 'private' groups_ because:

- The existence of a group-with-details-hidden-from-non-members will _still_ be public - even if we don't list it in a directory, users outside of the group can discover its name by trying to register it
- A 'public' group sounds like it pertains to ability to join rather than visibility of details

I think we want to:
1.  add an option to group settings:
    - ☑️  Show group details (description, members, room-list) to non-members
    - This feature should default to 'on'
1. show non-members (who will still find the group through clicking on flair) a notification:
    - `The details of this group cannot be seen by non-members.`, or

**Comment by turt2live** [comment]
Probably not part of the quick-win goal, but it would be nice to further supply a different long/short description for non-members. For joining instructions, or to show exclusive content to members of the group.

**Comment by lukebarnard1** [comment]
- [x] Add `is_public` to groups on synapse - matrix-org/synapse#2582

**Comment by lampholder** [comment]
We've decided that we can impl https://github.com/vector-im/riot-web/issues/5480 for the first cut of groups, meaning this isn't a release blocker :)

**Comment by t3chguy** [comment]
We have this in spaces (the group replacement)
