### ISSUE TITLE
need powerlevel setting exposed in RoomSettings for pinning messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5396]

**Comment by turt2live** [comment]
This is easiest done when it comes out of labs ftr

**Comment by lampholder** [comment]
Is it possible to put the powerlevel setting behind labs in just the same way? I like the... completeness of a feature's being fully baked before coming out of labs :)

**Comment by turt2live** [comment]
It's possible, but it feels like the work to gain ratio isn't high enough (imo).
