### ISSUE TITLE
Pinned message thoughts

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#5405]
- Pinning a message could (should?) open the pinned message drawer automatically.
- Pinned messages should perhaps show the date/time of sending
- Pinned message drawer openness should persist moving between rooms
    - how? per-user setting? per-user-per-room? per-room?
- Since pinned messages exist in a drawer very like a widget drawer, should they be a widget (I think _probably_ not, just raising here for consideration)?

**Comment by turt2live** [comment]
While reading this, please be aware that I'm biased as I wrote the thing :p

* I don't like the auto-opening at all, so if it does get implemented, I'd strongly recommend (yet another) setting for it.
* The date/time feels less important as, in general, the age of a pin doesn't usually affect the message.
  * Using the jump to message button would also help, particularly with sticky headers.
* I also don't like the idea of it persisting open/closed between rooms and suspect that this is a result of not having the indicator visible for unread pins (PR open and in progress). Granular settings (also wip) would definitely help on this front.
* There was some talk about using widgets for this, and overall I agree provided widgets can be made more powerful. They're very limited in what they can do, how they work, and where they go. All of which affects the usefulness of them.

**Comment by ara4n** [comment]
Going to adopt this as the canonical bug for 'getting pinned messages out of labs'

**Comment by turt2live** [comment]
A bit more feedback beyond me and @lampholder disagreeing would be appreciated. I'm happy to write out the code to make some of this happen, but a few more voices about the features would be nice to guide the features.

**Comment by pafcu** [comment]
Auto-open on pinned message should probably follow the same logic as the app drawer.

**Comment by allquixotic** [comment]
This might be outside the scope of what just riot-web can do from the clientside, but some of us using Matrix after long being on the https://chat.stackexchange.com platform would like pinned messages to be shared across users in a room, communally. So, if someone else pins a message, you would see it pinned, too. And then the number of users who pinned a message would determine the "weight" of the pin, and that weight (along with the message's age) would factor in a calculation to determine the sorting order of the pins in the list of pins (in the drawer, I guess).

Not sure how near or far from the design this request would be.

**Comment by turt2live** [comment]
Pinned messages are stored in the room, so everyone in the room can see them. Riot also goes a step further to give an indication of "unread" pins on a per-user basis.

The frequency-based ordering is an interesting addition. Currently only moderators (by default) can pin messages, so there wouldn't be a whole lot of competition for pinning messages. The ability to move the pinned messages around might work better for most rooms. I can foresee opening up pinning messages to all members of the room going really badly, and would recommend against that (unless some sort of restriction gets put in place).

**Comment by allquixotic** [comment]
The "star wall" mechanic in chat.stackexchange rooms works as follows (replace "star" with "pin" to muse about how this would work in Matrix/Riot):

 - Any registered user who can participate in chat, can star messages. They can also cancel *their own* stars at any time. Users can only star 25 messages in a 24-hour period.
 - Room Owners (basically like Matrix Moderators) can cancel all stars on a message, to prevent abuse. When cancelling stars, the stars still count against each user's 25 message per day limit.
 - Room Owners can *pin* messages. Pins in chat.SE parlance are actually a higher "priority" category of stars. Any pinned message will always be listed above messages that are *merely* starred on the Star Wall. Pinned messages can also be starred by regular users, adding weight to them, which affects the sort order of pinned messages relative to one another. Pins are distinguished from stars in that regular users can't pin anything, they can only star it, and no amount of stars will ever cause a message to be sorted higher than a pin in the list.
 - Moderators (basically like Matrix Admins) can't do anything special with stars that Room Owners can't do, but they also have the privileges of a Room Owner by default.

I can see this system as being next to useless in a room like #matrix:matrix.org or #riot:matrix.org, but for smaller rooms, star abuse is rare. Allowing regular users to star messages, and then allowing moderators/admins to pin messages that are really important, is a nice way to give people awareness of the recent goings-on in the room without having to read the entire scrollback.

Here are a few interesting features of the star wall:

 - Sort order: If two messages are of the same star "priority" (regularly starred or pinned) and have the same number of stars, the newer message will be higher in the sort order. Sometimes, older messages receive a higher position in the star wall than newer ones, if they receive more stars. I'm not clear on the exact algorithm used to determine how much an additional star counts for, but let's say, for example, that each additional star for a message will subtract 24 hours from that message's "age". If you just convert the number of stars into an adjustment on the message's age, then you perform a simple numerical sort on each message's age to come up with the sort order for the stars. Then repeat the same process for the pinned messages, if there's more than one.
 - Star wall limit: Messages remain levied with star metadata indefinitely (it never goes away), but only the top X number of starred messages get displayed on the chat client. It actually depends on your screen size, as far as I can tell, in the chat.SE client. Better vertical screen real estate will get you a longer star wall than a small and squishy screen. You can read the scrollback of the star wall itself with a separate view of the chatroom that lists starred messages in descending order of when they were posted. An alternative might be to dynamically load more (lower-sorted) stars upon request as you scroll down, in infinite scroll style.
 - Every message on the star wall is timestamped and provides a direct link back to the normal, chronological chat backlog at the particular point in time where that message was sent. This allows you to capture context if it's missing.

The purpose of this post was to give you hopefully some ideas for how to improve this feature, not to say "I want this exactly in Matrix!" or anything like that. I feel that the best chat system possible would end up being a fusion of the best ideas from many different present and past products, so shamelessly lifting ideas from StackExchange (while they, and every other chat client, shamelessly do the same from their forebears) is fair game.

**Comment by drseussofporn** [comment]
+1 for an auto-open pinned messages setting. I can see a couple use cases for that and including it as a user setting (and maybe a default setting in the config) could prevent it from getting abused.

**Comment by heyakyra** [comment]
Is pinning gone in Element?

**Comment by t3chguy** [comment]
Nope, it is still behind Labs like it was in Riot. develop.element.io Settings > Labs > Message pinning

**Comment by odiferousmint** [comment]
Why is there no Labs menu in the Arch Linux package, has it been compiled without those experimental features?

What is the status of message pinning? Is it on a per-room basis, and is there an icon to view ALL pinned messages as well? That would be neat. Plus I hope it does not have a limit as it does on Discord.

**Comment by auscompgeek** [comment]
> Why is there no Labs menu in the Arch Linux package, has it been compiled without those experimental features?

Labs features are disabled by default, see [docs/config.md](https://github.com/vector-im/element-web/blob/develop/docs/config.md).

**Comment by t3chguy** [comment]
> Plus I hope it does not have a limit as it does on Discord.

The app imposes no artificial limits. Any limits would be applied by the server your user is on, but none apply to pinning.

> Are pinned messages visible by everyone or only me?

They are part of the room state, there is another open issue about "Starring" messages which would just be personal to you.

**Comment by LecrisUT** [comment]
Has this feature been removed? I can't find it in element desktop/android anymore

**Comment by t3chguy** [comment]
@LecrisUT its in labs on develop.element.io - same place its only ever been

**Comment by almereyda** [comment]
As of https://github.com/matrix-org/synapse/issues/10422#issuecomment-882522550 it is only available for Element Web/Desktop:

- https://github.com/element-hq/element-meta/issues/1624
- https://github.com/element-hq/element-android/issues/357
- https://github.com/element-hq/element-ios/issues/4573

**Comment by t3chguy** [comment]
Pinned Messages has been in the Matrix spec for many years at this point, other clients not following the spec is their own concern.
