### ISSUE TITLE
Alone warning is truncated

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#5416]
The 'There's no one else here' warning is truncated on my client and truncates in a way that it's not obvious that it's truncated:

![screen shot 2017-10-24 at 15 17 40](https://user-images.githubusercontent.com/986903/31948410-c4c0074e-b8ce-11e7-9b68-ef1032edf7fb.png)

(making the window wider reveals more of the text, but I only realised that after reading the source)

**Comment by lampholder** [comment]
What causes this warning to appear? I don't think I've ever seen it...

**Comment by turt2live** [comment]
New feature. If you speak in a room that has only ever had yourself in it, it will appear.

**Comment by t3chguy** [comment]
This warning seems to have been removed
