### ISSUE TITLE
@room should require a direct, intentional, action to ping

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5420]
### Description

![image](https://user-images.githubusercontent.com/1190097/31950177-4235193a-b898-11e7-8e02-e0248c694ad2.png)

This is a tweet brought into matrix through a bridge. That should not ping me.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I was about to 100% agree, then I wondered - what metric would we use to decide that the twitter bridge can't use @room notifs? It's a bridge - so are IRC and Slack, and I can certainly see supporting @room notifs from those being valuable. Even if it were a bot, I can still see @room being useful (though open to abuse, certainly).

The reason we'd be happy to exclude all @room notifis from twitter is that we no nobody on twitter is trying to get our attention - it's a one-way broadcast and the @room paradigm doesn't map to twitter at all. So maybe this should be something that the bridge impl takes care of - specifically agreeing with the homeserver that its messages won't be processed for @room notifs (and whatever else makes sense here).

There might already be support for this in synapse/matrix fwiw; I'm not intimately familiar with the details of bridging.

**Comment by pafcu** [comment]
I can imagine a situation where you want some existing software, that only has Twitter support, to alert everyone in the room because a message is important.

Is this not actually a problem of non-admins being able to alert the entire room? Or is there a reason for the RSS feed to be an admin in the Matrix room?

**Comment by turt2live** [comment]
The spec for `@room` should include some way to indicate on a message that it is intentional, to avoid accidental and unwelcome pings. Something like `{ body: "@room: Hello world!", mentions: ['@room'] }` in the `m.room.message`. This could potentially also be expanded to user mentions. 

Clients would probably end up just doing `if (message.contains('@room')) content.mentions = ['@room'];`. Bridges could handle this on an individual basis (where the Twitter bridge would probably leave `mentions` empty/omitted).

**Comment by turt2live** [comment]
worth noting that other platforms like Slack warn you before you do this, which would be a good way to stop most of the cases. Bridging through Twitter is a whole other story, but maybe we can stop people from accidentally sending `@room` (either in a reply or in a message).

**Comment by t3chguy** [comment]
Fixed by intentional mentions MSC, support already in labs.
