### ISSUE TITLE
Riot should accept mixed-case group IDs and handle them as lowercase

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5434]
### Description

Creating groups for instance results in a server-generated error. It should probably be tolerant of mixed case and just convert it to lowercase.
![image](https://user-images.githubusercontent.com/1190097/32007840-e7b274c8-b967-11e7-8ec4-e3184cec942f.png)

Further, it should handle mixed case mentions of group IDs to avoid screens like this:
![image](https://user-images.githubusercontent.com/1190097/32007965-40842286-b968-11e7-812c-add11d569c06.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
> Further, it should handle mixed case mentions of group IDs to avoid screens like this:

Agreed; if group names are case insensitve, then loading +MATRIX:Matrix.org should always 'just work' (whilst making sure never to show anything but the canonical lower case +matrix:matrix.org in any UX)

> Creating groups for instance results in a server-generated error. It should probably be tolerant of mixed case and just convert it to lowercase.

I wonder what's the right UX for this? It would be good for people camel-casing their group name to know as quickly as possible that that isn't going to be persisted (to avoid pen island fun). Would it be offensive to style the textbox to show only lower case? With a warning perhaps? What does: http://jsfiddle.net/5ocu2cqk/2/ feel like?

**Comment by turt2live** [comment]
Showing the mixed case ID might hint that mixed case IDs are possible. It might be better to just correct the user, so instead of +MATRIX they see +matrix in the group views (the message would remain unchanged though, unless it gets pilled 😇)

The fiddle feels a bit intrusive and distracting; I found that I stopped typing to read the prompt, which is good, but it had me think (briefly) about what I was trying to type before the prompt. Maybe a post-entry prompt is suitable? ie: "Only lowercase letters are allowed for group IDs, is +mygroup:matrix.org okay? [yes] [no]". Clicking 'no' would probably bring you back to where you can fix the group ID. This isn't to say the prompt isn't bad though, it could use a little bit more time being open (possibly just persist), and it doesn't handle caps lock.

**Comment by lampholder** [comment]
Yeah, I got into making it handle capslock (surprisingly hard - the js event seems to give you every bit of keyboard state, _apart_ from capslock) and then realised I was spending too long on a throwaway illustration :D 

I think you're right - post-entry substitution and confirmation sounds good to me.

**Comment by lampholder** [comment]
On the other hand - if you forget the prompt and just leave it as auto-styling everything to lower case, how invasive does that feel?

**Comment by turt2live** [comment]
The user may feel disappointed that their pen island got clobbered, but they'd always have the option to abandon the group and create a new one. Chances are this would only happen on initial setup anyways, so they shouldn't be too broken hearted about it.

**Comment by lampholder** [comment]
OKAY so I dived into this a little too deeply perhaps and came up with: http://jsfiddle.net/5ocu2cqk/5/

You have to click 'Run' on the fiddle to get the headers to have the right styling for some reason.

**Comment by lampholder** [comment]
aaaaaand I've just learned that we (currently) don't allow dashes in group ids! Client side (server side it is allowed). Maybe we could change that..

**Comment by turt2live** [comment]
That feels much better overall :D A timeout on the shake could probably help, to avoid the constant shaking when capslock.

**Comment by lukebarnard1** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/1558 will make Riot use the same validation as the server.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
