### ISSUE TITLE
Do Not Escape All HTML (Or Add An Option To Do So)

### ISSUE THREAD

**Issue by benrob0329** [vector-im/element-web#5466]
### Description

Almost all HTML is escaped, even HTML that is allowed in the Matrix specification, and disabling Markdown also disables what little HTML is not escaped. It is inconsistent and annoying for people who do want to use HTML for a bit more flexibility over the formatting of messages.

### Steps to reproduce

- Enable Markdown (Otherwise **all** formatting is disabled outside of WYSIWYG)
- Enter some HTML, such as \<b> (\<del> and \<u> are allowed)
- Message is either plaintext, or if other formatting was entered then the HTML will be escaped

I would expect that supported HTML would be allowed in messages un-escaped, or that an option would exist to disable escaping of allowed HTML. What would work, is having a third option in the WYSIWYG editor, to enable HTML and disable Markdown, while leaving formatting on.

Example UX idea:
![1509241764](https://user-images.githubusercontent.com/19180682/32140103-2ea64740-bc2b-11e7-834b-04af66adf7de.png)

### Version information

- **Platform**: web 

- **Browser**: Chromium Version 61.0.3163.100 (Developer Build) (64-bit)
- **OS**: Gentoo Linux (64 Bit GNU)
- **URL**: riot.im/develop /

**Comment by ara4n** [comment]
We are very deliberately super-conservative about what HTML is allowed in messages.  This is to avoid the huge range of XSS and phishing attacks that can otherwise occur.  What formatting in particular are you missing?

**Comment by benrob0329** [comment]
Simple things like \<b> or \<p>, even \<img> (with an mxc link) to be able to specify size.

**Comment by dbkr** [comment]
Just a note to say that whether this is a good thing or not is contested: see https://github.com/matrix-org/matrix-react-sdk/pull/1551

**Comment by t3chguy** [comment]
Though by not allowing it we are diverging from CommonMark yet further:

![image](https://user-images.githubusercontent.com/2403652/35409076-1af5d5a2-0209-11e8-9f61-a5d3be843382.png)

**Comment by martinvonwittich** [comment]
Markdown without HTML isn't really Markdown IMO. The original idea behind Markdown was to have a simple syntax for the simple things, but also to always have the ability to fall back to HTML as soon as the simple syntax doesn't cut it anymore. That's also why CommonMark explicitly allows for HTML:

https://spec.commonmark.org/0.28/#html-blocks

> An HTML block is a group of lines that is treated as raw HTML (and will not be escaped in HTML output).

https://spec.commonmark.org/0.28/#raw-html

> Text between < and > that looks like an HTML tag is parsed as a raw HTML tag and will be rendered in HTML without escaping.

The proper solution is to allow Markdown with HTML, and then filter dangerous content before displaying it.

**Comment by t3chguy** [comment]
We added the `/html` command
