### ISSUE TITLE
URL Previews don't play nicely with non-English sites

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5473]
Example URL: https://www.diorismos.gr/epixeirhmatikothta/26708/se-troxia-ylopoiisis-to-agrotiko-internet

The preview ends up with non-Greek letters

**Comment by turt2live** [comment]
For reference, the preview looks like this:
![image](https://user-images.githubusercontent.com/1190097/32179522-3a113fba-bd55-11e7-8bfc-691e971f76d6.png)

but the title of the article is:
> Σε τροχιά υλοποίησης το αγροτικό Internet

**Comment by MadLittleMods** [comment]
This now works as expected ⏩

![](https://user-images.githubusercontent.com/558581/135140231-9efc7175-4393-4e2a-b8e0-774dbee6fc80.png)
