### ISSUE TITLE
Feature request: poll widget

### ISSUE THREAD

**Issue by uppps** [vector-im/element-web#5499]
Now that we are able to insert widgets in Riot rooms I think it will be great to have a poll widget.

**Comment by lampholder** [comment]
100% agreed, this would be super useful - you could of course make your own poll widget to include as a custom widget for now... 😄

**Comment by hex-m** [comment]
sounds like a duplicate: #6255

**Comment by jryans** [comment]
Yes, let's close this as the other one has a bit more traction.
