### ISSUE TITLE
Explicitly prompt users to request keys when faced with a UISI?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5532]
At the moment we silently request keys for undecryptable messages in the background.  This may be undesirable, as key verification is currently out of band, yet the person being verified might not have any idea why they are being verified as they don't realise they did a key share in the first place.

We might want to instead just always provide a "request keys?" button next to UISIs, as per Tom's UX thoughts at https://docs.google.com/document/d/12r21OrXYEvzKclKCUWX2a-2ckU6Se0IJHoZaLicVxFc/edit#heading=h.1t5ui387zzvs.

**Comment by turt2live** [comment]
We do this I believe. If not, https://github.com/vector-im/element-web/issues/20532
