### ISSUE TITLE
Group attestation renewals should happen in bulk

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5545]
This is a server-side bug really, but adding a bug here to track it:

We currently make a federation request for every group attestation renewal. We should batch them up.

**Comment by lampholder** [comment]
@richvdh Is this a bug or a feature? I.e. is the lack of batching causing problems right now?

**Comment by richvdh** [comment]
It contributed to https://github.com/matrix-org/synapse/issues/2592, though that has been mitigated by #2593.

I think it will cause problems for large groups.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
