### ISSUE TITLE
Entering an invalid room results in the group picker suggesting room IDs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5548]
### Description

![image](https://user-images.githubusercontent.com/1190097/32558782-e2082cce-c462-11e7-8c8f-794c86c0f0c1.png)

Improved text might read something like "That room could not be found. Try entering the name again or looking up rooms by their alias."

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Yeah, I think something like:

`Sorry, we couldn't find that room. Start typing the room name to see suggestions, or enter a full room alias (of the form #room:example.com)`.

I _don't_ know whether we want to mention that people can enter a room id. @ara4n - are power users generally just aware that you can use a room id anywhere you use an alias? (Is that actually even true?) How do people become aware of this? Do we want to mention it here?

**Comment by turt2live** [comment]
I feel power users would just know, or would find out from other power users. Even for a power user, entering a room ID would probably be rare though and only useful in a limited set of scenarios. 

As for "Does it work?" - yes, but not in a pretty way:
![image](https://user-images.githubusercontent.com/1190097/33034517-52686296-cde5-11e7-85bd-a88e24057006.png)
(accepting the suggestion also shows the room ID. "Matrix HQ" is only shown after clicking "Add to community")

**Comment by aaronraimist** [comment]
> Entering an invalid room 

or a valid room but one that you aren't a member of

**Comment by SimonBrandner** [comment]
Spaces are now in beta
