### ISSUE TITLE
Consent warnings

### ISSUE THREAD

**Issue by SoniEx2** [vector-im/element-web#5550]
### Description

I'd like a simple inline consent warnings mechanism. Implementation details TBD.

Some examples of how to display them:

![my IRC client](https://vgy.me/8fFG1C.png)

[image description: my IRC client, showing lines "Soni | can matrix do this? [Hidden Text 1]" and "* | Hidden Text 1 >  < (Copy and paste to expand)"]

![mastodon (closed)](https://user-images.githubusercontent.com/1779619/32582471-272aa6ba-c4d6-11e7-90b3-597c072322ad.png)
![mastodon (open)](https://user-images.githubusercontent.com/1779619/32582469-26fe2f40-c4d6-11e7-9be5-3c5a6b877025.png)

[image description: mastodon, showing a post with a consent warning. first image shows "cw example" followed by a "show more" button, second image shows "cw example" followed by a "show less" button and the text "hello world"]

(Note that in the IRC client case above, the client supports true inline CWs, and even multiple CWs per message, with text in between. For compatibility reasons it would be nice if we did so too, even if we only send "normal" CWs.)

**Comment by turt2live** [comment]
(for the purposes of adding more keywords: this is also known as spoiler text)

**Comment by SoniEx2** [comment]
yeah but suicide notes are often considered too much for "spoiler text", while acceptable for content warnings.

**Comment by turt2live** [comment]
The user-facing feature probably wouldn't have a label (it would just be something that says "click to reveal"). Just wanted to add more keywords to the ticket to avoid duplicates in the repository.

**Comment by SoniEx2** [comment]
that's dangerous UX for mental health channels...

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/604 is the spec issue for this fwiw

**Comment by uhoreg** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3018 implements spoilers, but only as an inline element so might not completely solve this issue

**Comment by SoniEx2** [comment]
inline element is the only proper way to solve this issue.

**Comment by shmerl** [comment]
I'd add that this should also apply to images, not just to text.

**Comment by robintown** [comment]
The original request of this issue, inline spoilers, has been supported for some time, so I'm closing this. https://github.com/vector-im/element-web/issues/10882 tracks having a nicer way to send them, and https://github.com/vector-im/element-web/issues/18061 and https://github.com/vector-im/element-web/issues/18062 track support for non-inline content warnings.
