### ISSUE TITLE
failure to get mic/camera permissions appears as (unknown failure: user_media_failed?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#5552]
From https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15102329623965WjLwr:matrix.veritasgenetics.com

**Comment by lukebarnard1** [comment]
related ? https://github.com/vector-im/riot-web/issues/5046

**Comment by florianjacob** [comment]
I can confirm this using Firefox 57 on Linux. I can circumvent this by setting the firefox permissions for riot for Microphone and Camera from ”always ask” to ”allow“.

But another aspect of the problem is that I don't have a webcam, and it seems therefore video calls always return `user_media_failed` as Riot can't get a video stream. Would be nice if it worked with one-way video in that case, so the other person can show me something with their phone showing me their video stream while I sit in front of my desktop, together with two-way audio streams.

**Comment by MurzNN** [comment]
Same problem on Firefox 60 & Riot 0.15.3 - Riot don't ask for Microphone and Camera permissions, I only can force enable them via manual changing ”always ask” to ”allow“ in page permissions.

 @florianjacob did you find any solution for your problem?

**Comment by t3chguy** [comment]
@MurzNN did you try pressing the `Missing Media Permissions, click here to request.` in Settings?

**Comment by MurzNN** [comment]
@t3chguy Yes, it shows the window:
```
No media permissions
You may need to manually permit Riot to access your microphone/webcam
```
with no permission popups in browser.

**Comment by t3chguy** [comment]
which implies at an earlier point you pressed Deny do not ask again or your browser ignores the site requesting permissions. When you click that option riot fires a gUM (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) request for which the browser should prompt you. If it doesn't there is nothing riot can do further. The same call is used when making/answering a call to prompt you for permission.

**Comment by MurzNN** [comment]
In Riot webpage settings there are default "Always ask" instead of "Block" for riot.im website:
![](http://i.imgur.com/c6UKWTC.png)

**Comment by t3chguy** [comment]
no actually its set to `Use Default`, which is a value specified elsewhere.

**Comment by MurzNN** [comment]
Discord on same browser asks permissions normally with same permission settings "Always ask": http://i.imgur.com/c6UKWTC.png

**Comment by ngorohov** [comment]
Same problem in Riot-web 0.15.4 on Kubuntu 18.04. In 0.13.5 everything works fine.

**Comment by SimonBrandner** [comment]
Is this still an issue for all of you?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
