### ISSUE TITLE
Avatars need a bit of maintenance

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#5554]
Lots of things import the `MatrixClient` just to be able to use `mxcUrlToHttp`, when the function doesn't actually do much. Maybe this is an indicator that the way fetch media in general is a bit gnarly, at least in Riot. The full rant is https://docs.google.com/document/d/1mC15YV2iStGumTQ3_8P7ZzerS72t_UaRjki2oG6A7CI/edit#heading=h.ml70befq92eu

**Comment by lampholder** [comment]
/me realises he has no idea how to prioritise this.

**Comment by turt2live** [comment]
From an externalish perspective: Having to think "Which avatar do I use?" is a bit annoying. Granted, I've dealt with avatars a lot more recently than before.

**Comment by t3chguy** [comment]
This got fixed by the mxc helper stuff
