### ISSUE TITLE
Option to whitelist the file types (mimetype and extensions) allowed in the media repository

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5588]
Server admins should be able to restrict the file types of content being transferred, in case they want to stop the media repo serving up (or caching remote versions of) .exe's or .aspx or .html or equivalent.

**Comment by ara4n** [comment]
see also https://github.com/matrix-org/synapse/issues/2588

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/2588
