### ISSUE TITLE
Sanity-check whether E2E VoIP calls are working reliably

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5596]
There have been lots of bugs over the last year about VoIP not working reliably over E2E rooms between various combinations of platforms.  This includes:
 * A regression in sending ICE candidates on web which Dave fixed (for both E2E and non-E2E rooms)
 * A bug on iOS which Manu fixed: https://github.com/vector-im/riot-web/issues/2669

However, I'm not entirely convinced that we've tracked them all down, and we should work through testing all the various different combinations of platforms to doublecheck.

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
