### ISSUE TITLE
Ability for HS admins to force users to join (and never leave) a given room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5617]
Somewhat related to #5243 and #5507: a useful feature (similar to https://github.com/matrix-org/matrix-doc/issues/759) is the ability to autojoin users on a given server to a room (which synapse now supports anyway)... but then prevent them from ever leaving that room, so that it can be used as a WALL channel or for other important broadcasts.

**Comment by t3chguy** [comment]
Synapse supports the join part, if you care about the prevent leave part I suggest opening an issue in https://github.com/matrix-org/synapse/
