### ISSUE TITLE
Chrome uses native desktop notifs now on Linux, which don't support HTML

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5622]
So we're leaking HTML into our desktop notifs now :(

**Comment by erikjohnston** [comment]
Turns out that some do, e.g. `xfce4-notifyd`

**Comment by lampholder** [comment]
Can whatever handles desktop notifs detect the OS and strip HTML accordingly?

If so a P3 stretch goal could be to implement forcing HTML notifs as an option (for the xfce4-notifyd fans)

**Comment by robintown** [comment]
Does anyone know if this situation has changed in the last 5 years?

**Comment by turt2live** [comment]
Closing as presumed fixed. If this is untrue, please open a new issue with fresh reproduction steps.
