### ISSUE TITLE
Default theme isn't picked up correctly from config.json

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5623]
Repro steps:
 * Set default theme to 'status' in config.json
 * Load login page
 * See a weird hybrid 'light' theme CSS mixed with the HTML from the status theme (implying that LoginPage.js is seeing the theme correctly as 'status').

**Comment by ara4n** [comment]
![screen shot 2017-11-16 at 16 47 36](https://user-images.githubusercontent.com/1294269/32905188-2c5372cc-caf1-11e7-8913-6b2d3edf4f56.png)

**Comment by turt2live** [comment]
This was caused by the `index.js` not checking the config.json value at all (in fact, the config wasn't even loaded fully at the time of the check), but `MatrixChat` found a different value for the theme. This meant that the basic login components got `light`, but the rest of the UI got `status`.

In other words, https://github.com/vector-im/riot-web/pull/5630 fixes this by loading the config fully ahead of asking for the theme.

**Comment by turt2live** [comment]
@ara4n this should be fixed now

**Comment by uhoreg** [comment]
closing because @turt2live says it's fixed ;)

**Comment by ara4n** [comment]
i'm not entirely sure that it is fixed tbh - @lampholder was saying that we now pick themes at random at startup...

**Comment by turt2live** [comment]
That sounds bad... Is there any more information I can get?

**Comment by uhoreg** [comment]
well, that'll teach me to trust @turt2live when he says he's fixed something 😛

**Comment by skylord123** [comment]
I'm trying to use this to set the dark theme as the default. This does not work.

**Comment by turt2live** [comment]
@skylord123 what are you seeing instead?

**Comment by skylord123** [comment]
@turt2live uses the light theme instead: https://chat.skylar.tech

**Comment by turt2live** [comment]
@skylord123 that looks like a different bug that hasn't been reported yet. At first glance, your Riot setup looks correct for what you're trying to achieve. Are you able to open a new issue? Including a copy of your config.json in the issue would be appreciated.

**Comment by skylord123** [comment]
Yes I will open a new issue. Thanks for clarifying :)

**Comment by ara4n** [comment]
i just tested this (setting `"default_theme": "dark"` and it worked.
