### ISSUE TITLE
Accept/Reject buttons on group invites are ugly on develop

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5625]

**Comment by lampholder** [comment]
![screen shot 2017-11-22 at 16 36 45](https://user-images.githubusercontent.com/1922197/33138840-66ad51a2-cfa3-11e7-9c70-ec70bda42a34.png)

They don't look _too_ bad to me? Fairly standard Rioty buttons?

**Comment by SimonBrandner** [comment]
Communities are being replaced by spaces
