### ISSUE TITLE
Forwarding UX is unexpected

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5641]
### Description

From a user:
> weird
> when you forward everything goes grey
> then I clicked a room and it forwarded it there
> that's not what I'd have expected as a behavior
> I would have expected a menu

This isn't the first time I've heard of this either :(

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: tang.ents.ca (riot 0.13.1)

**Comment by lampholder** [comment]
I agree, the UX is a little surprising (it's a nice feature but right now it works fairly unlike anything else in Riot)

**Comment by eMPee584** [comment]
had this today; "**a little surprising**" is a nice euphemism for "**inadequate UX**"... :rofl:

**Comment by TR-SLimey** [comment]
Any news here? The forwarding system is still useless in the post-redesign 1.7.1 version.
