### ISSUE TITLE
Firefox 57 preemptively loads all CSS files, even if they're disabled

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5668]
It looks like it may also load their dependencies, e.g. WOFFs, which then leaks usage of the app to status.im(!) for their hosted WOFF.  To fix we probably need to load the CSS programmatically via JS rather than using link tags.  This will also close up the bug I can't find about needlessly preloading theme data

**Comment by turt2live** [comment]
I believe the situation has improved and we no longer have status.im as a theme. If this is still a problem, a new issue with more information would be appreciated.
