### ISSUE TITLE
status.im mxids for Matthew & Amandine are higher in the matrix.org user dir results than for matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5669]
This seems very strange; surely the matrix.org MXIDs should be weighted higher as we are in 100x times more rooms with them than with our status.im IDs...

**Comment by ara4n** [comment]
this is starting to get really annoying :(

**Comment by t3chguy** [comment]
Closing as a Synapse issue, if it recurs please open an issue in https://github.com/matrix-org/synapse/
