### ISSUE TITLE
Have a mechanism for showing flair across all rooms on a homeserver (and configuration thereof)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#5676]
> we could also perhaps set default 'show flair for' on a HS if certain badges should be visible everywhere - eg for server admins

**Comment by lampholder** [comment]
Separated from https://github.com/vector-im/riot-web/issues/5648

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/1508

**Comment by t3chguy** [comment]
Closing as Flair will be entirely re-designed.
