### ISSUE TITLE
RTE formatting buttons also react to right-clicking

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5681]
### Description

Unlike all other buttons, the RTE formatting buttons (bold, italic, etc.) also perform their action when right-clicked, rather than only on left-click.

### Steps to reproduce

- In a room, press "Show Text Formatting Toolbar"
- Right-click on "B" button 
- Notice that text is inserted into text editor, rather than showing the context menu of the browser

### Version information
Riot web 0.13.1 on FF57

**Comment by aaronraimist** [comment]
Appears to be fixed
