### ISSUE TITLE
RTE uses non-styled scrollbar

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5682]
### Description

When writing a message with many lines a un-styled scroll-bar appears

### Steps to reproduce

- Open a room
- Type 6+ lines (shift+return for newline)
- Observe an unstyled scrollbar:

![image](https://user-images.githubusercontent.com/62835/33224673-48fb957c-d16c-11e7-8f9c-8cde67aee979.png)

### Version information

Riot web 0.13.1 on FF57

**Comment by t3chguy** [comment]
No longer an issue

![image](https://user-images.githubusercontent.com/2403652/144599767-c2ab4f4b-7471-4031-bb97-24a44790c53d.png)
