### ISSUE TITLE
Inconsistent state vs. message redaction

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5684]
### Description

When a state event (X joined, etc). is removed it is actually removed from the timeline. When a message from a user is removed the message remains but the contents is redacted. 

I would expect either both events to be shows as redacted, or both events to be completely removed.

### Steps to reproduce

- Join a channel
- Write a message
- Remove the event announcing your joining by hovering over it, clicking "..." and selecting "Remove"
- Remove the message

Observe that the state message is gone, but the message you wrote is redacted.

![image](https://user-images.githubusercontent.com/62835/33229313-e30d78aa-d1cc-11e7-89fb-f2ae4cb4f38b.png)

![image](https://user-images.githubusercontent.com/62835/33229324-03d8b554-d1cd-11e7-8cdf-8e0f66f661ef.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by dbkr** [comment]
FTR, I've just found this is because of https://github.com/matrix-org/matrix-react-sdk/pull/739

**Comment by t3chguy** [comment]
This got fixed
