### ISSUE TITLE
Feature request: Option to rename images on upload

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5687]
It would be nice to be able to rename images when you upload them so that you can give them a descriptive name. E.g. when pasting an image into the RTE the image is automatically named "image.png" which does not really say much. Giving a descriptive name makes it easier to find later, and gives vision-impaired people some idea of what the image is showing.

You might also name images on your own computer in a way that you don't want to share with the whole world when uploading images.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/17617
