### ISSUE TITLE
Notifications pane shows mxids rather than display names

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5692]
### Description

The notifications pane (opened by the bell icon in right sidebar) shows the mdxid of a sender rather than their display name. This is not consistent with the rest of the UI where the display name is shown when possible (and may be confusing to users as they may not actually know the mxid of some people).

![image showing mxid instead of display name](https://user-images.githubusercontent.com/62835/33238765-1948d104-d294-11e7-9499-a57b3dade411.png)

### Version information

Riot web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by turt2live** [comment]
I see this more often when I scroll up in the notifications list, but many look like this:
![image](https://user-images.githubusercontent.com/1190097/33243110-ea735d5a-d29c-11e7-94ae-f9ca90005e19.png)

**Comment by lampholder** [comment]
Having incidentally just refreshed my local riot instance, I see nothing but mxids in the notification panel. I wonder if there's a difference between historic and received-in-this-browser-session notifications as regards resolution of mxids to display names?

**Comment by SimonBrandner** [comment]
As far as I can tell, mxids are shown for events that were not loaded to the timeline. For those events `EventTimeline::setEventMetadata` (the function that sets `event.sender`) was not run, it seems

**Comment by SimonBrandner** [comment]
This issue seems to have the same cause as the fact that if you try to open some images from the right panel the new Image View doesn't work. This is because the new Image View also tries to load `event.sender` for the avatar but fails because it doesn't exist

**Comment by t3chguy** [comment]
> For those events EventTimeline::setEventMetadata (the function that sets event.sender) was not run, it seems

Yeah looks like the js-sdk will only run it for the live unfiltered timeline and never else, not sure if we want to consciously make it run for the notifications & files timelines or not or just have the fallback in the react-sdk after all
