### ISSUE TITLE
[Bug] URL preview requires http:// or https:// prefix (nobody types that any more)

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#5699]
- Platform: Riot web 0.13.1 (served on the riot website)

- Browser: Vivaldi : 1.13.1008.32 (Stable channel) (64-bit)
- OS: Ubuntu Linux 17.10

In my private testing channel, I have URL preview set to on. However, URL previews only ever happen when they are prefixed with http:// and https:// , but if someone is typing in say.... google.com , it never gets "previewed".

**Comment by lampholder** [comment]
I'm surprised we don't URL preview anything that we linkify :\

**Comment by BloodyIron** [comment]
Can we get this tied to a milestone perhaps? :)

**Comment by t3chguy** [comment]
<img width="995" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/384180bf-e6db-4870-bef8-8fb566df974f">

This is no longer the case

**Comment by BloodyIron** [comment]
Yay! Thanks @t3chguy ! :DDD This is an old one heheh ;P
