### ISSUE TITLE
Login page tries to communicate with HS when partial URL is given

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5703]
### Description

The login page apparently tries to communicate with the HS entered in the Home server URL field before clicking "SIGN IN". If the field contains an incorrect URL at any point the user is presented with an error message

### Steps to reproduce

- Open the login page
- Click "Custom server"
- Remove the last letter in the Home server URL box (i.e. so that it says "https://matrix.or")
- Observe a "Can't connect to homeserver" error 

![image](https://user-images.githubusercontent.com/62835/33284955-14d29c5e-d3b1-11e7-8b77-5cb8283d1223.png)

### Version information

Riot web 5f4d01160657-react-81ae081f1521-js-0d6ffa3935d5 on FF57

**Comment by lampholder** [comment]
This is certainly a little surprising - it looks like today it's doing the request after a debounced onchange; perhaps this should be onblur/onlogin?

**Comment by t3chguy** [comment]
This got fixed with the change to the modal experience where it only validates on blur and gives you details on `Continue`
