### ISSUE TITLE
Desktop version in Linux freezes in some cases

### ISSUE THREAD

**Issue by akontsevich** [vector-im/element-web#5704]
### Description

Observe some UI freeze today

### Steps to reproduce

1st on incoming contact request (killed and restart)
2nd freezes when messages were sent in chat during call:
- started a call
- messages coming
- UI freezes
- to avoid call interruption started riot-web in browser: https://riot.im/app
- after few minutes riot had unfreezed on desktop and worked normal again

3rd freezes on incoming call. System monitor shows some riot-web processes are zombie.

### Version information

- **Platform**: desktop
- **OS**: openSUSE Linux Tumbleweed
- **Version**: 
riot-web: 0.13.1
olm: 2.2.1

**Comment by fmcd** [comment]
Observing something similar here in the last few months on LMDE 2 Betsy 64 bit kernel 3.16 Cinnamon desktop.

Hard to pin down.. but it seems to coincide with when system is low on memory and firefox (58.0.2) becomes sluggish and then reports crashed tabs: at this point, when attempting to maximize riot from minimized/sys tray state, one finds the windows appears but blank/white. No redraw. Riot can be still closed though from the tray icon.
riot-web 0.13.5

**Comment by akontsevich** [comment]
Still happen very often on new message or call come. Please fix. Thanks!

**Comment by akontsevich** [comment]
Some observation: if I run second Riot in browser, message or call marked as read and desktop version unfreezes.

**Comment by akontsevich** [comment]
Hmm, same issue exists in Skype, only unfreezes more quickly. Seems electron problem. Is there related issue created in [electron repo](https://github.com/electron/electron/issues)?

**Comment by akontsevich** [comment]
Recent time I switched from Wicked to NetworkManager for connections control in SUSE. Do not observe freezes for now. Could it be the case?

**Comment by akontsevich** [comment]
No, freezes with NetworkManager as well - electron bug.

**Comment by akontsevich** [comment]
I have localized the problem: Riot freezes only if "Enable desktop notifications" checkbox enabled in the settings. Repeated in KDE and MATE. Exact same problem exists in Skype which also built on Electron. On disabling notifications problem is gone in both Riot and Skype.

**Comment by akontsevich** [comment]
@lampholder bug still there in Riot 0.15.2 (Electron 2.0.1).

**Comment by t3chguy** [comment]
Closing due to no updates in years, we've moved up 15 major electron versions since
