### ISSUE TITLE
[Feature Request]:  Bookmarking Public Communities(I'm not a member)

### ISSUE THREAD

**Issue by dineshdb** [vector-im/element-web#5706]
### Description
Communities are great. They link all the related channels together and makes it easier to follow the rooms when many similarly named rooms are available. However, for the communities in which I'm not a member, I need to remember the name/URL of the community to enter that page. It would be great if I could bookmark it so that I can visit that community and then rooms whenever I want without having to remember the Community ID.  Currently only communities which I'm part of, is listed in communities list.

**Comment by lampholder** [comment]
The intention is for this (or something very like this) to be considered as part of the left hand side group/tag/filter piece that's currently underway (and available as a beta 'labs' setting on https://riot.im/develop).

Right now that feature just uses the groups you're in (so, specifically **not** address your specified usecase) but we have spoken about extending it to include public groups of which you are not a member.

**Comment by turt2live** [comment]
Related issues to the left hand side would be:
* https://github.com/vector-im/riot-web/issues/5734
* https://github.com/vector-im/riot-web/issues/5730

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/5730
