### ISSUE TITLE
MatrixBridge can only be contacted via start chat button, not /user page link

### ISSUE THREAD

**Issue by heyakyra** [vector-im/element-web#5712]
### Description

The page https://riot.im/develop/#/user/@freenode_MatrixBridge:matrix.org does not load, but using the start chat button to contact @freenode_MatrixBridge:matrix.org does (albeit I can't see the room until I refresh Riot). 

Possibly causes https://github.com/matrix-org/matrix-appservice-irc/issues/524

Log: sent/not sent?   not sent

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: FF57
- **OS**: Fedora 26
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This has been fixed
