### ISSUE TITLE
Some UI issues with the new communities sidebar

### ISSUE THREAD

**Issue by pafcu** [vector-im/element-web#5725]
### Description

Some UI issues with the new groups sidebar:

- It is not obvious how to show all rooms, once you have clicked on a community Perhaps add an "all rooms" button, or show all rooms when clicking again on an already shown community
- The bar does not respect themes, and stays green even when the dark or status theme is selected
- The Create Community button:
  - looks exactly like the Create room button
  - looks disabled until you hover over it
  - does not have any tooltip (or "faux" tooltip like the other buttons at the bottom of the left sidebar) 
  - has no aria-label for accessibility
  - is one pixel lower than the other buttons
 
![image](https://user-images.githubusercontent.com/62835/33397837-3cb76752-d54d-11e7-9c44-ab1fbdb2761e.png)

![image](https://user-images.githubusercontent.com/62835/33398320-dc80595a-d54e-11e7-8292-9f2cc9120676.png)

### Version information
Riot web 72563e611421-react-7118f7a38f79-js-0238ecebedfc on FF57

**Comment by lukebarnard1** [comment]
> show all rooms when clicking again on an already shown community

Having received a lot of feedback asking for this, we'll definitely add this in.

>does not respect themes

Yep, this is known and hopefully something that'll be fixed soon.

As for the button, we will certainly add a tooltip and move it by 1px. I agree that it appears disabled, I wonder what @ara4n thinks about that. It _is_ the same icon as the room create button but I think that's fine given it's in a different context.

>no aria-label for accessibility

It should be using <AccessibleButton/> so I'm not sure why it hasn't got the right attributes.

**Comment by pafcu** [comment]
> It is the same icon as the room create button but I think that's fine given it's in a different context.

True, but if you are not in any groups that context is not clear. You also can't tell people to press the "plus button". You can't even tell them to "press the plus button in the lower left corner" because both are quite close to the corner. Finally, context is not as clear as you'd think for many people, and instead they memorize things. This is harder with identical buttons.

I'd go with the communities icon with a small "+" sign.

**Comment by lukebarnard1** [comment]
@pafcu actually, on my browser - Quantum, the icon is aligned correctly. Which browser are you using (it's useful for the browser to be included in the issue).

>I'd go with the communities icon with a small "+" sign.

Not a bad suggestion.

**Comment by pafcu** [comment]
> Quantum, the icon is aligned correctly

Also Quantum (FF57) :-( On Linux, if that makes a difference

**Comment by lukebarnard1** [comment]
Oh. So it turns out the important fact is screen dpi. Apparently, yours is double mine, meaning their 0.5px out of line:

![2017-11-30-105936_1552x352_scrot](https://user-images.githubusercontent.com/6750344/33427598-b6c5909e-d5bd-11e7-9337-7112eab4ab1e.png)

**Comment by pafcu** [comment]
Hmm, could be. That image is taken on a high-dpi screen. But I just tested on a 1920x1080 96 DPI screen, and I get the same result.

**Comment by robintown** [comment]
UI has changed, this is all irrelevant now
