### ISSUE TITLE
[LLP] Community invites shown when looking at a group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5728]
### Description

*LLS = Left Left Sidebar*

![image](https://user-images.githubusercontent.com/1190097/33399636-92a9b134-d510-11e7-8505-961018897f46.png)

Note I'm looking at a group, but I can also see a community invite for a different group

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Hmm, I don't think we'd discussed invites at all when thinking about filtering that left hand panel.

This is perhaps another reason to have a 'global' view icon on the LLS - invites not associated with any of your current groups/tags/filters could appear as some sort of visual notification there.

**Comment by turt2live** [comment]
ftr, I thought a global icon was always on the roadmap... so +1 to that.

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
