### ISSUE TITLE
Ability to add communities you're not a member of to LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5730]
### Description

To avoid having to run your own homeserver and creating groups to mimic those already existing, it would be nice to be able to add `+matrix:matrix.org` to the Left Left Sidebar.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment]
Spaces are now in beta
