### ISSUE TITLE
[Feedback on LLP] Seeing direct chats and tags when looking at a community feels awkward

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5732]
### Description

I realize this is currently part of the design, however it just doesn't feel right. Considering most groups I'm in only have a couple rooms, there's a lot of empty tags or tags that don't make sense.

For instance, here's one of my groups:
![image](https://user-images.githubusercontent.com/1190097/33399890-6d41cb24-d511-11e7-88fa-aeb95f913004.png)

Instead of showing so many tags, just show me the room list for that group. Having all of my actual tags shown on the home view (no group selected) should still be maintained, so I can organize my rooms at multiple levels.

### Direct Chats

Showing the direct chats doesn't make sense at first. Each and every time I've had to answer my own question of "why are these people here?". Similar feedback was received when asking a couple people to try out the feature as well.

Adding https://github.com/vector-im/riot-web/issues/5570 would probably help solve this problem as it would show conversations I already have with those people, and I can more easily chat with them.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Cadair** [comment]
I quite like the direct chats, certainly once roles are a thing that's exposed communities are likely to be larger I can see that being a useful addition.

I think hiding empty tags is a good idea though.

**Comment by turt2live** [comment]
I'm not sure how roles would play into the direct chats, but they seem like distinct features. The current approach gives me the impression that I should be talking to my friends more than I should be talking in a community's rooms, making me a bit sad.

**Comment by ara4n** [comment]
heads up the current implementation is not *remotely* finished, and almost all the intended functionality (tagging rooms to groups, etc) is missing. even the tint is broken :)

**Comment by turt2live** [comment]
@ara4n completely understand, just lodging tickets now so they don't get too lost or forgotten. Much like the initial round of groups, many of these are wishlist items.

**Comment by aaronraimist** [comment]
Nowadays this only shows People/Direct Messages + the tags that the community rooms are in so I think this can be closed.

**Comment by t3chguy** [comment]
only an issue for `People` sublist on new room list

**Comment by SimonBrandner** [comment]
Spaces are now in beta
