### ISSUE TITLE
tab-complete in Composer probably shouldn't append whitespace after the completed thing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5753]
If it's at the beginning of the line, appending ': ' is probably fine. But if it's in the middle of a line, we probably shouldn't assume that there should be a trailing ' '

**Comment by lampholder** [comment]
For comparison:
- slack adds a space, but deletes it if you type punctuation
- android stock keyboard does not add a space, but adds one if you type a non-punctuation character
- fb messenger doesn't add a space
- gitter adds a space just like us
- whatsapp adds a space just like us
- telegram doesn't autocomplete names

**Comment by t3chguy** [comment]
+ discord adds a space just like us

**Comment by kittykat** [comment]
Closing as the product team are happy with the current behaviour of adding a space at the end
