### ISSUE TITLE
Permalinking (or navigating) to events which are not visible dumps you in the middle of the timeline

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5762]
### Description

An example of this is https://github.com/vector-im/riot-web/issues/5761 where clicking "Jump to read receipt" ended up leaving me somewhere in the timeline with no hint as to what the event is.

Some kind of feedback like "That looks like a valid event, but we can't display it to you" would probably be best.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Er yes I guess
I put code in place to show hidden events if they are permalinked to but I guess if riot has no renderer for them that won't happen

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/22123
