### ISSUE TITLE
reports that FF57 on Linux doesn't prompt for webrtc perms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5769]
and so silently fails with 'media failure' if you try to initiate a 1:1 call

**Comment by alduder** [comment]
Audio or video 1:1 calls in FF57 seem to fail. FF to FF: no stream on both sides. Chrome to FF: FF does send audio and video, visible on Chrome, but receives nothing. Can't see any errors in the console. The ringing tone is also missing on FF.

**Comment by SimonBrandner** [comment]
This seems to be no longer relevant
