### ISSUE TITLE
Audio/video is sent, but there is no indication of a call

### ISSUE THREAD

**Issue by AlexDaniel** [vector-im/element-web#5770]
This issue should probably be marked as `critical`.

### Description

Under some conditions you can make a one-sided call: the other party can see and hear you, but Riot does not show that there is an ongoing call (you can't see or hear the other party and there's no way to cancel the call from your side).

### Steps to reproduce

* You and someone else should start a video call at exactly the same time. That's it.
* You will see something like this in the chat log, but it can be different:
```
00:09 OtherGuy placed a video call.
00:09 AlexDaniel placed a video call.
00:09 AlexDaniel ended the call. (unknown failure: true)
00:09 AlexDaniel answered the call.
00:09 OtherGuy ended the call.
```
* At this point the call starts. You can hear the other party, but not see. Riot does not show that there is an ongoing call, and you can call the same person *again*.
* If you press the call button again, it gets into some double-call state. You hear the person from the first call, and you also hear the beeps from the second call. Sometimes you can see the other person as well.
* Once you end that second call attempt, you can no longer see or hear the other person. Riot shows that there's no call, but the other side can hear and see you. **At this point the only way to know if there's a one-sided outgoing call is if you have an LED on the webcam.**

### Version information

- **Platform**: desktop
- **OS**: Debian unstable
- **Version**: riot-web 0.13.1

**Comment by turt2live** [comment]
How many users were in the room (including bots)?

This sounds very similar to https://github.com/vector-im/riot-web/issues/3520 and possibly https://github.com/vector-im/riot-web/issues/2199 / https://github.com/vector-im/riot-web/issues/1325

**Comment by AlexDaniel** [comment]
Just 2, this is a 1-to-1 conversation (not a room).

**Comment by AlexDaniel** [comment]
Yes, that sound identical to #3520 (but this ticket is probably a bit more detailed).

Oh, by the way. To reproduce it one person can send a “go!” text message, after which both participants hit the video call button. Reproducible 100% of the times.

**Comment by t3chguy** [comment]
@AlexDaniel a 1-to-1 is still a room

**Comment by lampholder** [comment]
Apparently #3520 was downgraded from critical to major by @ara4n, then from major to minor by me.

I can't imagine why I would have downgraded this (curse past me for not including context with my label change). @ara4n can you remember?

**Comment by lampholder** [comment]
For the record, we typically use `critical` to mean "the whole app is broken", whereas `major` means "this whole feature is broken"

**Comment by AlexDaniel** [comment]
@lampholder it's not just broken, users are at risk. Not only that, but I already managed to make an unwanted “call” as described, which is why we have this bug report… Looking at other `major` bug reports, this one seems to be quite a bit more important.
