### ISSUE TITLE
Internationalized domain names

### ISSUE THREAD

**Issue by Valodim** [vector-im/element-web#5808]
I just noticed Riot doesn't support [punycode](https://en.wikipedia.org/wiki/Punycode) ([RFC3492](https://www.ietf.org/rfc/rfc3492.txt)), domains just show up in their xn-- form.

**Comment by pafcu** [comment]
Punycode has security problems: https://securityintelligence.com/news/punycode-enables-invisible-phishing-attacks/

**Comment by Mikaela** [comment]
Does this issue include links like https://стопкоронавирус.рф/ (Russian COVID-19 infosite) not being clickable in ~~Riot~~ Element Web? The punycode version https://xn--80aesfpebagmfblc0a.xn--p1ai/ is correctly shown as a link.

**Comment by t3chguy** [comment]
Yes

Upstream issue: https://github.com/Soapbox/linkifyjs/issues/251
