### ISSUE TITLE
vertical stack of bottom buttons in collapsed LHS panel takes up too much room

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#5811]
since the addition of the home and community buttons, the bottom buttons in the LHS panel is starting to get really tall when the panel collapsed, and can take up siginificant screen space (e.g see https://matrix.org/_matrix/media/v1/download/matrix.org/CEKIZVTIHDNjKazjziUWGzbB )

**Comment by pafcu** [comment]
Perhaps hide all the buttons behind a menu button?

**Comment by t3chguy** [comment]
They are gone :)
