### ISSUE TITLE
Microcopy on create community dialogue

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#5814]
When I was playing around trying to introduce sensible defaults on the create community dialogue (http://jsfiddle.net/5ocu2cqk/5/), I wrote some microcopy for the two fields.<hr>

### Community Name
Your community name is how people will know your community - it should be as descriptive as possible to help people know what your community is all about.
Remember: your community name is **not** unique across Matrix.

### Community ID
Your community ID is a unique identifier; people will see it when you invite them to your community. Try to choose something that is easy to read and clearly represents your community.
Matrix community IDs are **lowercase only**; words should be **separated-with-dashes**.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
