### ISSUE TITLE
Crypto migration warning appears even if you get signed out

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5815]
If you return to riot with an invalid access token, we go ahead and migrate the crypto data anyway, and then pop up a notification dialog *after* we log the user out. We should abort the migration on logout.

**Comment by poljar** [comment]
I don't think that we're doing any large migrations of any crypto data nowadays. I think this is describing the `Localstorage` -> `IndexedDB` migration, so I don't think this is relevant anymore.

Please reopen if I'm wrong.
