### ISSUE TITLE
Option to associate groups at room creation time

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5819]
### Description

Something like the following could work:
![image](https://user-images.githubusercontent.com/1190097/33897866-db3eb594-df23-11e7-8f27-600d600884e3.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by SimonBrandner** [comment]
Spaces are now in beta
