### ISSUE TITLE
rageshake logs go missing

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#5822]
I've seen various cases (possibly related to having multiple tabs open?) where it's clear that a client has been online, but there is nothing in the rageshake logs about it despite there being older sessions present.

Needless to say, this makes debugging a nightmare.

See https://riot.im/bugreports/listing/2017-12-12/094450/ as an example

**Comment by turt2live** [comment]
I'm closing this as it's not really come up since 2017. If this is still a problem worth fixing, please open a new issue with fresh information.
