### ISSUE TITLE
Bad timing in some cases causes the Chat UI to render even after you clicked "log out"

### ISSUE THREAD

**Issue by MTRNord** [vector-im/element-web#5823]
### Description

After logging out in the spinner my client deadlocked in a room with rendered Chat UI and no buttons working.

### Steps to reproduce

- Start the app
- Click while the loading spinner at the near end the Logout button

The Client lands in a deadlock and refuses to work

Log: not sent (cant get into any menu. I will attach a file) [crashLog.log](https://github.com/vector-im/riot-web/files/1552754/crashLog.log)   

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: Can't check Settings but path in the logs says "app-0.13.3"

**Comment by turt2live** [comment]
from #riot:

> yea, that's probably what broke the client:
> * Grab settings promise started
> * Log out clicked
> * Log out completed (possibly only partially)
> * Matrix client disappeared
> * Settings promise continued, but the client is missing
> * Explosion of errors
> 
> The fix is to probably block the logout button on the other promises.

**Comment by t3chguy** [comment]
This has been fixed
