### ISSUE TITLE
Add a configuration option to a homeserver to automatically join new users to all the rooms associated with a configured community.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#5865]

**Comment by lampholder** [comment]
This is a suggested optimisation for a specific usecase - this is certainly worth thinking about in some depth.

This feature is intended to recreate the Slack-like experience of being joined to some rooms automatically when you join a new community. This certainly makes sense where the community in question is a new company you've started working for - in Matrixland it will not always be that simple.

So, we want to be able to support that experience, in a way that doesn't take control away from individuals.

It seems reasonable that certain communities might mandate your presence in certain rooms (the #general of the new company you've just joined, for example), whilst others might encourage it in all or some cases , (the #general analogue of the Badger fanclub you've just joined, or #newbies in the mushroom-picking community you've just joined) and others might have no opinion on the matter.

Ideally, we'd give communities the tools they need to offer all of the above experiences, whilst giving sufficient UX/user control that they don't get tricked into joining a whole bunch of rooms just because they joined +freebeer:matrix.org.

**Comment by turt2live** [comment]
A dialog saying "Joining this community will add you to 345,422 rooms. Are you sure you'd like to continue?" might work.

Assuming an arbitrary number to not show that dialog (3?)

There could also be options to not join particular rooms in that dialog. With that there's also some kind of solution for showing rooms you haven't joined yet, but also won't be automatically joined

**Comment by t3chguy** [comment]
Closing this as communities are going away and it really needs to be a Synapse issue if there's any chance of synapse devs seeing this.
