### ISSUE TITLE
Adding rooms to a community where the group server is not aware of the room leads to "Unamed room"

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5866]
### Description

This does require a bit of database surgery as I don't think it's possible in the current form of groups. As groups progress, this probably will come up more often.

When a room is added to a group where no users of the room are part of the group server, the room shows up as "Unamed room".

### Steps to reproduce

*This is best reproduced on a fresh homeserver.* You'll need two homeservers to do this.

- On homeserver1 create a new group
- Add your homeserver2 user to the group
- Make your homeserver2 user an admin in the group (requires a DB update)
- On homeserver2's user, add a room which homeserver1 has never seen the group
- Observe "Unamed room".

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
Solved by Spaces
