### ISSUE TITLE
Pinned messages take forever to load if they were pinned a long time ago

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5871]
### Description

This is probably more of a server-side problem as it seems like the server is frantically trying to find the event for you, making you wait while it digs through the database.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by phil-flex** [comment]
![image](https://user-images.githubusercontent.com/34325924/54405468-ab920380-4711-11e9-970a-cff80ceb151a.png)
Riot's console (with Riot v1.0.3), upper image is the room able to display pinned message without problem, lower image is the room unable to display pinned message.

![image](https://user-images.githubusercontent.com/34325924/54405638-50144580-4712-11e9-92ac-434ff9b21bdf.png)
Firefox's console (with Riot v0.17.9)

I have a similar issue, some rooms are not able to display the pinned messages.
