### ISSUE TITLE
Can't package dmg electron app on MacOS

### ISSUE THREAD

**Issue by apinter** [vector-im/element-web#5876]
### Description

Can't package electron app to dmg on MacOS High Sierra v10.13.2, process hangs.

### Steps to reproduce

- git clone https://github.com/vector-im/riot-web.git && cd riot-web
- npm install
- npm run build
- npm install electron
- node_modules/.bin/build -m --x64

Describe how what happens differs from what you expected.
The process just hangs. But even before trying to build the app open with ```npm run electron``` but get only a white window.
![screen shot 2017-12-25 at 3 15 54 pm](https://user-images.githubusercontent.com/13173679/34336078-afcf822c-e986-11e7-9fee-9e88802f17aa.png)

### Version information
0.13.3

- **Platform**: web (in-browser) or desktop?
Desktop app, MacOS High Sierra 10.13.2

P.S: I'm pretty much a noob so it is absolutely possible that I'm doing something wrong, but following the instructions provided in the README.

**Comment by t3chguy** [comment]
Click view at the top and hit open developer tools to see the Javascript console and show the error it has

**Comment by apinter** [comment]
@t3chguy ok so it turns out that I was an utter idiot and seems like that in the rush to test again the dmg build I missed the ```npm run build``` ... Sorry, now it runs ok with ```npm run electron```, but still not packaging to dmg.

**Comment by t3chguy** [comment]
What happens when you try to build to dmg?

**Comment by apinter** [comment]
It just hangs. Left it for 12 hours to run, but nothing happened.
![screen shot 2017-12-25 at 8 16 49 pm](https://user-images.githubusercontent.com/13173679/34340128-c749f2fa-e9b0-11e7-9e1f-7535793a954d.png)

**Comment by t3chguy** [comment]
Might be more valuable to ask in https://github.com/electron-userland/electron-builder or maybe @dbkr will know whats up with it

**Comment by apinter** [comment]
Thanks, I'm guessing it might be related to this issue: https://github.com/electron-userland/electron-builder/issues/2346

**Comment by dbkr** [comment]
Yeah, this is electron-builder being special, unfortunately. Debug mode might offer more insight. You could also try a newer version of electron-builder as we use quite an old one.

**Comment by apinter** [comment]
@dbkr yea had the same conclusion. Ended up packaging a dist and using nativefier on it, works like a charm. Once I get a hold on that Mac again will take a deeper look.

**Comment by aaronraimist** [comment]
Are you still having trouble with this?

**Comment by aaronraimist** [comment]
Closing since there has been no update. Reopen if you are still experiencing this.
