### ISSUE TITLE
bulk redact API

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5885]
lots of requests for bulk redaction support after FN spambot attacks over christmas. plus we probably need it for GDPR too. It could be as simple as 'redact all messages from this user' for now.

**Comment by 4nd3r** [comment]
> we probably need it for GDPR too

b-b-but event content still stays in database after redaction.

also again this: https://github.com/matrix-org/synapse/issues/1621#issuecomment-269857023

**Comment by uhoreg** [comment]
related: https://github.com/vector-im/riot-web/issues/3689

Might make sense to use this issue to track "redact all messages from this user", and the other issue for selecting multiple messages to redact.

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/34694298-daef636e-f4c6-11e7-8e02-9a0fad65fdc1.png)
Telegram has this menu in groups btw

**Comment by lampholder** [comment]
Related:
- https://github.com/vector-im/riot-web/issues/2158 
- https://github.com/vector-im/riot-web/issues/3689
- https://github.com/vector-im/riot-web/issues/5885
- https://github.com/vector-im/riot-web/issues/5898

**Comment by ara4n** [comment]
cf GDPR issue at https://github.com/vector-im/riot-meta/issues/149

**Comment by alittlebitofit** [comment]
Any updates on this?

**Comment by t3chguy** [comment]
@alittlebitofit yes see https://github.com/matrix-org/matrix-spec-proposals/pull/2244

Closing in favour of #3689 now that https://github.com/matrix-org/matrix-spec-proposals/pull/2244 landed
