### ISSUE TITLE
D&D of Room into a collapsed sublist doesn't work

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#5890]
it drops the room into the nearest uncollapsed/shown sublist. Collapsed not always being intentional, sometimes automatic due to lack of space

**Comment by lampholder** [comment]
I find drag and drop of rooms between tag-lists/favourites/people(?)/low priority to be quite difficult to use generally.

It looks like we're going to implement dragging rooms into LLP filter things, so that might be a good opportunity to revisit the d&d usability in this area generally.

**Comment by novocaine** [comment]
I don't think room sublists are a feature in the same way they were when this was filed.
