### ISSUE TITLE
TagPanel - make filtering quick (by caching rooms and users associated with a group) and accurate (by loading the most recent data when selecting a filter)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#5902]
- [x] Pull `/users` and `/rooms` for groups that the user in joined to when ~`TagPanel`~ `RoomList` mounts. https://github.com/matrix-org/matrix-react-sdk/pull/1686
 - [x] Optimise for many rooms being displayed. This might be quite generic performance work on the room list.  
   - So far, we have at least optimised for selecting tags: https://github.com/matrix-org/matrix-react-sdk/pull/1687
   - We have also optimised to cache isConfCallRoom, which inspects the other members of the room but only needs to calculated once per-room. https://github.com/matrix-org/matrix-react-sdk/pull/1693
- [ ] Pull `/users`, `/rooms` and the group profile when the user filters by that group

**Comment by ara4n** [comment]
This is option 6 of https://docs.google.com/document/d/1GzwhGdnWWMENYOaXMFP8CD-M9ny1vznxHnNqT3I3NZI/edit fwiw.

**Comment by t3chguy** [comment]
The TagPanel is gone
