### ISSUE TITLE
Systray icon quit function doesn't quit when active in voice conference

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#5909]
I'm using Riot 0.13.3 Desktop on Ubuntu 17.10.

When I am in a voice conference (freeswitch? unsure), and I click on the system tray icon, tell it to quit, the app will not quit at all. However when I leave the voice conference, it then will quit after I tell it to quit again.

It seems like the voice conference is forcefully preventing the application from quitting completely.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4628

Seems unrelated to the conference.

**Comment by BloodyIron** [comment]
Yup! The quit instruction is issued from the tray icon (in this case, XFCE4 systray).

**Comment by BloodyIron** [comment]
Don't mean to be a bug, but any chance we could get this categorized/set to a milestone? :)

**Comment by t3chguy** [comment]
@BloodyIron during the weekend? When no one is in the office? Noooope
I'm sure toml will get around to it, he triages all the issues

**Comment by BloodyIron** [comment]
D'oh! Weekends have become a blur for me, sorry :(

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore as we use Jitsi now
