### ISSUE TITLE
Gaps in history after a federation outage, fixed by refreshing cache

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5915]
@erdnaxeli says:

> hi, I got a weird case

> my HS got disconnected from the network for a week, and on reconnection an user scrolled on a federated room (actually #irc:matrix.org)

> but the history was missing two days of messages

> I told him to empty his cache and it works better after that

> it does not really surprise me, but my users find this behavior a bit strange

> and I'm not really sure of what actually happened

> to detail: the first user was missing 4 days of history, I joined the room with a user on the same HS, I had only 2 days of history missing

> we both emptied our cache, and it was ok

> so I thinking something like riot got confused, ask for some history, then stop ; then I went to the room, ask for a little more, then stop too

> with an empty cache riot correctly asked for the whole history, forcing the HS to ask to others too

**Comment by lampholder** [comment]
Anything that undermines trust in the timeline's completeness is very bad :(

**Comment by MadLittleMods** [comment]
This could be a client problem but can also happen easily if Synapse returns `/messages` with gaps in it. [MSC3871](https://github.com/matrix-org/matrix-spec-proposals/pull/3871) will help with this sort of thing so Element will know when there is gaps and allow users to retry fetching that part of the timeline.

Given the federation outage, it's very possible that the HS fell behind very far, then you paginated `/messages` and Synapse only backfilled 100 messages while you scrolled past that 2-day area leaving the gap.
