### ISSUE TITLE
Animate avatars on hover

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5922]
Like Discord

**Comment by turt2live** [comment]
> "On the discord desktop program, when you hover over a users message, if their avatar is a gif, it will play."

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15151283293464906msfqu:matrix.org

**Comment by specing** [comment]
Can the client be made more efficient as far as processor utilization goes instead of adding features that are of no real use and only slow things down?

**Comment by turt2live** [comment]
@specing this is just a feature request from someone, not a guarantee it'll be implemented tomorrow. Performance is an ongoing battle.

**Comment by The-Steel-Talon** [comment]
This is the most useful feature.
If one finds it less useful then that doesn't mean that others find it useless too.

 turt2live : Thank you for acknowledging such an useful feature. :)

**Comment by turt2live** [comment]
As a point of information: riot uses server-side thumbnails to render the avatars and relies on those. Due to a bug in the media repo project I'm working on, it didn't thumbnail gifs and instead returned the source gif, causing riot to play the image.

![animated avatars](https://t2l.io/_matrix/media/v1/download/t2l.io/JBxdPdAbxhGrxRetWcolFEgW)

So in reality this is probably a lot easier than it seems: Synapse could be made to resize the gif (through a fourth query param or automatically) and riot just needs to allow the image to play on hover (to avoid the screenshot I've posted here).

**Comment by SethFalco** [comment]
I think this is the same as https://github.com/vector-im/element-web/issues/18442 ?

Maybe one of them should be closed? (I'd favor this one since the other issue has more details.)

**Comment by t3chguy** [comment]
Closing in favour of #18442
