### ISSUE TITLE
UnknownDeviceDialog flow is still very clunky

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5936]
I just tried to send a message in an e2e 1:1 with uhoreg on /develop.
 * First I got in the statusbar: "Unable to send message; try again?" error, or similar words.
 * *Then* it told me: "There are unknown messages in the room - view devices or cancel?" or similar.
 * *Then* i had to look at the UDD and hit 'send anyway'.

Surely the first stage is a bug.  And on the second one, rather than forcing me to look at the devices, I wonder if we should be providing a "send anyway" button on the preview bar.  This was my intention when proposing the UDD simplification in the first place: that at least until we have cross signing, we should give users the easy way out rather than trying to force them to use unusable verification process.  Paranoid folks can use the UDD to check the keys, but folks who don't care can just hit "send" on the status bar.

@dbkr, wdyt?

**Comment by dbkr** [comment]
IRLed on this, but yes, first is definitely a bug and adding a shortcut to the 'send anyway' button seems fine

**Comment by dbkr** [comment]
Those 2 PRs should fix the 2 aspects of this between them

**Comment by richvdh** [comment]
I feel sad about a workflow which closes bugs before the PR is even merged, never mind released :/

**Comment by ara4n** [comment]
i just had a variant of this again:
 * I sent a message and an image into an e2e room
 * I hit 'send anyway' on the unknown device warning that came up in statusbar.
 * Then statusbar said "failed to send message" and gave me retry/cancel buttons; so i hit retry.
 * Then it worked.

It feels like the unknown device warning fired twice somehow.

**Comment by t3chguy** [comment]
UDD got killed off
