### ISSUE TITLE
Permalinking invisible events causes infinite back pagination

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5937]

**Comment by ara4n** [comment]
e.g. $15153218301304484Fpgds:matrix.org in HQ

**Comment by turt2live** [comment]
This appears to be because Riot doesn't have a rendered event tile to stop at, so it just keeps going forever.

**Comment by t3chguy** [comment]
Closing in favuour of https://github.com/vector-im/element-web/issues/22123
