### ISSUE TITLE
Reset password with phone number

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5947]
I couldn't find an issue for this already, so here it is. If it's a duplicate, please close.

**Comment by vrtxf** [comment]
I can't reset password at all actually :/

**Comment by CuriousA62A2A** [comment]
Bump. Probably signed up with phone number since my email isn't connected to an account and I know I created an account way back.

**Comment by turt2live** [comment]
We don't really support phone numbers properly these days, and this would actually be a spec issue. Closing as not entirely helpful for the element-web repo in the current decade.
