### ISSUE TITLE
Pinned messages should use /room/{roomId}/event/{eventId} when it lands/is stable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5958]
synapse pr: https://github.com/matrix-org/synapse/pull/2766

Currently pinned messages use the event context API with a very narrow scope. Using the dedicated endpoint would hopefully mean the request goes by faster.

**Comment by Half-Shot** [comment]
Not sure this is a P1?

Anyway, this should probably be done at the js-sdk level where we just check for compatibility with the new endpoint and fallback to context?

**Comment by t3chguy** [comment]
Also I don't think they can? Surely we want historical displayname and avatar for the pinned event..?

**Comment by turt2live** [comment]
It currently doesn't use the historical display name/avatar, which is arguably a bug or design decision.

**Comment by t3chguy** [comment]
Sounds like an inconsistency, I'm not personally a fan of historical avatars etc but am of consistency so 🤷‍♂️

**Comment by t3chguy** [comment]
Needs decision of whether pinned messages should use Current or Historical avatar&displayname

**Comment by turt2live** [comment]
The whole feature needs design, so for now let's leave it out of the product queue.
