### ISSUE TITLE
When composing rich replies, use a different popover on the message composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5973]
### Description

The current one looks too much like the autocomplete, implying that these things can be autocompleted. Some CSS to make it appear different would probably improve usability. I'd also recommend removing the message hover effect in that window.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I agree with removing the message hover effect (the highlight when I mouse over the message body of the message we're replying to) - it feels out of place in the reply to popover.

I don't get the same sense of autocompleting or autocompletability, but I'd be interested to hear what other people think.

**Comment by t3chguy** [comment]
> I'd also recommend removing the message hover effect in that window.

Fixed by https://github.com/vector-im/riot-web/pull/6017

**Comment by t3chguy** [comment]
Related to #5997

**Comment by PifyZ** [comment]
I'm not sure I understand the issue. Is it possible to elaborate it?

**Comment by yannicka** [comment]
I'm not sure I understand the problem. Is it possible to elaborate it?

**Comment by SimonBrandner** [comment]
I believe this is no longer relevant, so I am going to close it. Shout if you disagree
