### ISSUE TITLE
Multiple blockquote messages from same user not visually distinct under some conditions with compact theme

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#5976]
If a user sends a message that ends in a blockquote and then sends another message that starts with a blockquote, it looks like both blockquotes are part of the same blockquote.

![riot_blockquotes](https://user-images.githubusercontent.com/17915621/34839362-5e4e04fe-f6cf-11e7-9fd7-58f9dab9feca.png)

OS: voidlinux
browser: qutebrowser (whatever version of blink qtwebengine is currently on)

**Comment by non-Jedi** [comment]
Looking at attached image, messages from same user in series aren't visually distinct even outside blockquotes, but the problem feels worse on the blockquote side of things for some reason.

**Comment by turt2live** [comment]
Cannot reproduce on Chrome 63/Windows 10
![image](https://user-images.githubusercontent.com/1190097/34839641-9208ba88-f6bf-11e7-9442-c3f8be9c0fab.png)

**Comment by non-Jedi** [comment]
Can't seem to replicate on another user's message within the same browser tab:

![riot_blockquotes_2](https://user-images.githubusercontent.com/17915621/34839682-8936d8fc-f6d0-11e7-98a7-e97303a955ea.png)

**Comment by non-Jedi** [comment]
Expanding the width of the browser gave this:

![riot_blockquotes_3](https://user-images.githubusercontent.com/17915621/34839779-cedef786-f6d0-11e7-8448-47e302392e59.png)

**Comment by non-Jedi** [comment]
seequ:
> TravisR: it's the compact theme

Issue is compact theme specific.

**Comment by gsouquet** [comment]
<img width="796" alt="Screen Shot 2022-01-31 at 11 41 23" src="https://user-images.githubusercontent.com/769871/151787789-106e48dc-dabd-40c5-8476-160757463f4f.png">

Issue fixed, it looks as the screenshot above in the compact theme
