### ISSUE TITLE
Long display names get pushed over their container when hovered in the user list

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5980]
### Description

![image](https://user-images.githubusercontent.com/1190097/34887555-22da2406-f784-11e7-9028-b6ab8c2e7210.png)

the IRC appservice is hovered in this example.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by gsouquet** [comment]
I have not been able to reproduce this one, closing.
