### ISSUE TITLE
Community ID input height is inconsistent

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#6016]
![image](https://user-images.githubusercontent.com/2403652/35183451-5d3f433c-fdde-11e7-920f-18ed3b516e22.png)

The input is 1px taller (and lower) than the blocks on both left and right of it

**Comment by lampholder** [comment]
On which browser? I think I've seen discrepancies on this between chrome/firefox (or perhaps between linux/mac).

**Comment by t3chguy** [comment]
Desktop app on Windows

**Comment by turt2live** [comment]
Chrome and firefox render inputs slightly differently, often leading to this 1px padding difference. I can't remember the fix I've applied to other projects though :(

**Comment by MTRNord** [comment]
I had a similar issue with a not centered cross in the room directory. Matthew mentioned a css reset might help. Maybe it helps here too?

**Comment by t3chguy** [comment]
They're dead
