### ISSUE TITLE
Dragging a group can cause weird text effects on pinged messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6025]
### Description

I can only really describe this with a gif:
![ping_move_group](https://user-images.githubusercontent.com/1190097/35303123-1a0fcf60-004e-11e8-969b-b10b16a63560.gif)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This has changed slightly where the effect only occurs while a group is moving in the LLP (no movement = no weird effect)

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/6137
