### ISSUE TITLE
Google docs widget doesn't load when strict tracking protection is enabled

### ISSUE THREAD

**Issue by tkolo** [vector-im/element-web#6034]
### Description

Since Firefox 58 their tracking protection can be enabled outside of private mode. When enabled and set to use "strict protection" blocklist, it seems to interfere with google docs widget embedded in riot.

### Steps to reproduce

- Go to firefox optoins -> Privacy & Security -> Set Tracking Protection to "Always"
- Click "Change Block List" and choose "Disconnect.me strict protection"
- Go to riot and create google docs widget. My sample document was https://docs.google.com/document/d/1MOoIA9qEKIhUQ3UmKZG-loqA8e0BzgWKKlKRUGMynVc/edit, but it seems any doc will do.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox Developer Edition 59.0b3 (64-bit)
- **OS**: Windows 10
- **URL**: private riot web instance, riot-web version: 0.13.3

**Comment by lampholder** [comment]
P1 for us to consider how large a problem this is/how we can mitigate (I think we can expect tracking protection to become generally ubiquitous over 2018.

**Comment by bwindels** [comment]
True for any widget? I also noticed it with our feature dashboard fwiw.

**Comment by turt2live** [comment]
The Google Docs widget was removed from Scalar.
