### ISSUE TITLE
Wrong avatar used for historical messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6046]
### Description

on develop:
![image](https://user-images.githubusercontent.com/1190097/35451645-2cd9d99e-0281-11e8-8890-5c7f3de68724.png)

someone else's riot (desktop, windows 7):
![image](https://user-images.githubusercontent.com/1190097/35451661-3d194f24-0281-11e8-85a3-c61578feaf86.png)

my other riot develop:
![image](https://user-images.githubusercontent.com/1190097/35451734-6b805164-0281-11e8-95fb-cbde1c167c30.png)

The difference between image 1 and image 3 (which are my clients) is that the first client (image 1) wasn't online/syncing at the time of the event, and loaded it several hours later. 

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
I'm going to guess this is because RoomMember goes to huge pains (i.e. the whole sentinel thing) to track accurate historic display names... and then entirely fails to do the same thing for avatar URLs.

**Comment by ara4n** [comment]
actually, it looks like the only reason it tracks names separately is for disambiguation. so that's not it.

**Comment by turt2live** [comment]
I think this got fixed somewhere btw.
