### ISSUE TITLE
Whitespace in inline markdown code elements should not be collapsed

### ISSUE THREAD

**Issue by cmcaine** [vector-im/element-web#6051]
### Description

White space in code blocks sent in markdown mode should not be collapsed.

### Steps to reproduce

- Send a message: \`1  2   3    4\` with a varying amount of whitespace between each number
- Observe that whitespace is collapsed (as on github).

Whitespace is preserved in non-inline code blocks:

 ```
1  2   3    4
```

Whitespace is significant in code elements. Please don't strip it.

View source shows the whitespace, so it's presumably being removed by riot's js.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 59
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment]
Is that not just because it's not in a pre element and thus html rules apply=spaces are collapsed

**Comment by t3chguy** [comment]
It's not an issue with riot, instead commonmark and for the above reason

http://spec.commonmark.org/dingus/

![](https://i.imgur.com/gJae6FA.jpg)

**Comment by cmcaine** [comment]
If commonmark didn't remove the spaces you could just CSS them back with `white-space: pre`.

Commonmark may change the spec. See discussion: https://talk.commonmark.org/t/leading-and-trailing-white-spaces-in-code-blocks/628/21

Doesn't look like commonmark.js has an option to change this behaviour. Other parsers keep internal runs of whitespace (e.g. marked).

I definitely don't care about this enough to do a PR of my own. but maybe someone who already has the dev environment set up will.
