### ISSUE TITLE
ordering of my favs is now out of sync between ios and web

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6053]
top item on web is now bottom item on ios

**Comment by lukebarnard1** [comment]
Is it possible that all of your rooms apart from the top item in your favourites had unread messages? Because iOS orders favourites with unread messages and notifications first.

**Comment by lampholder** [comment]
@ara4n is this something you still see?

**Comment by turt2live** [comment]
@ara4n second call for if you're seeing this still

**Comment by SimonBrandner** [comment]
Closing as reordering favs isn't a feature anymore
