### ISSUE TITLE
Signed Out For security, this session has been signed out. Please sign in again. & Unrecognised access token - not in store

### ISSUE THREAD

**Issue by NikkyAI** [vector-im/element-web#6054]
### Description

whenever i try to login on any Riot client (except on phone) the following appears
![Signed Out For security, this session has been signed out. Please sign in again.](https://i.imgur.com/uFp0lRt.png)

matrix-synapse logs 
```
2018-01-29 01:28:44,617 - synapse.api.auth - 485 - WARNING - PUT-138- Unrecognised access token - not in store:
```

i can still login using riot-android, i suspect that is because a different matrix-sdk is being used

### Steps to reproduce

- try to log in

Describe how what happens differs from what you expected.

Log: cannot sent when not logged in  

### Version information

- **Platform**: web and desktp

For the web app:

- **Browser**: Chrome
- **OS**: Windows + Arch Linux
- **URL**: private server: v0.13.4

For the desktop app:

- **OS**: Windows + Arch Linux
- **Version**: 0.13.3

**Comment by ara4n** [comment]
@NikkyAI - what is your homeserver's `expire_access_token` setting? Also, have you changed the `pepper` parameter?

**Comment by NikkyAI** [comment]
access token expiration is set ot tre and i did not modify the pepper parameter
althouhg i found out only my laptop is affected, my desktop and phone can log in fine, but no via chromium or google chrome or the electron wrapper app

**Comment by ara4n** [comment]
okay - any idea how expire_access_token got set to `true`? i strongly suspect that you want `false`.

**Comment by NikkyAI** [comment]
well i set it to false, but i have no idea how to revalidate such a token..

**Comment by NikkyAI** [comment]
or can i completely change the device id of my laptop to get around this .. banning myself issue ?

**Comment by ara4n** [comment]
just logging in again (once set to false) should be enough to fix things

**Comment by NikkyAI** [comment]
it evidently did not fix things.. in fact after following suggestions from irc to delete all devices other than the one i wasl ogged in though from my phone it also killed my access on my windows machine

and it seems to try to use the same access token whe ni log in from there

**Comment by xsteadfastx** [comment]
one user of my server has exactly the same problem? any ideas to get around that?

**Comment by cuibonobo** [comment]
I have a user that is also experiencing this issue. If I clear his cache manually, he will enter his login and then get kicked out immediately with the "For security, this session has been signed out" error. If he attempts to log in again, he gets an infinite spinner.

I checked his developer console and the relevant line seems to be:

```
<homeserver>/_matrix/client/r0/presence/<mxid>/status:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

After this, the client attempts to log out, but fails again with:
```
<homeserver>/_matrix/client/r0/logout:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

At this point, the client is stuck in an infinite loading screen.

During the times of these login attempts, the server logs show:
```
2019-02-01 11:43:52,963 - synapse.api.auth - 500 - WARNING - PUT-41560652- Unrecognised access token - not in store.
2019-02-01 11:43:52,998 - synapse.api.auth - 500 - WARNING - POST-41560654- Unrecognised
access token - not in store.
```

**Comment by Salzi** [comment]
Running into the same problem with one user (using LDAP). Is there a solution/workaround for this?

**Comment by martindale** [comment]
One of our users is running into this now, as well.  Details will come if we get them...

**Comment by BlackWolfDEsign** [comment]
use only lower case for username when login via riot...

synapse requires lower case when registering

**Comment by xsteadfastx** [comment]
i cant believe this has something to do with ldap or user authentication.

**Comment by martindale** [comment]
> synapse requires lower case when registering

Can this be configured and/or expanded to include non-ASCII characters?

**Comment by NullIsNot0** [comment]
This still happens. Is there a solution besides recommending users to use lowercase letters for usernames?

**Comment by jryans** [comment]
At this point, I don't think this issue is actually tracking a single problem any more. For anyone still facing this problem, I would recommend starting a new issue specific to your use case and server details. I would suspect in many cases, it may be a server configuration issue, so I would also suggest asking in #synapse:matrix.org if your are self-hosting.

**Comment by ristein** [comment]
getting same problem every time when trying to change notification settings for one room
