### ISSUE TITLE
User media failure due to capture device settings

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6082]
I just had electron fail to place a call with a user media failure: on opening settings, the webcam was on 'Default Device' but mic was blank. On changing mic to 'Default' (why is it 'Default' for mic and 'Default Device' for camera?), it then worked.

**Comment by t3chguy** [comment]
Default for Mic is an OS thing
Default Device for Camera is just whatever the first camera is and thats at the application level

Some OSes say Default for Mic some say other things

**Comment by dbkr** [comment]
Myself & @lampholder have just both devices be blank on Electron. Setting them back to 'Default' makes calls work again. We noticed this after installing 0.16.

**Comment by dbkr** [comment]
NB. we could also improve the error message to mention what device we're trying to open.

**Comment by SimonBrandner** [comment]
@dbkr, is this still an issue?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
