### ISSUE TITLE
Cannot scroll plain pre blocks

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6087]
### Description

![image](https://user-images.githubusercontent.com/1190097/35786926-e326a5a2-09e7-11e8-94a6-e3b95ab3ddba.png)

The text can be scrolled by highlighting the text out of view, however Riot should probably supply a scrollbar for this.

Note: In the screenshot above the cursor is hovering over the block. The desired effect was to have the preformatted text displayed in a monospace font.

Event body (essentially): `<pre>Text\ngoes\nhere</pre>`

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Transfusion** [comment]
![image](https://user-images.githubusercontent.com/3119646/96336681-0b9e1800-10b4-11eb-9c9b-cba6f6bcbe7e.png)
A scrollbar on `overflow-x` seems to be present, however, the scrollbar's style causes it to have the same color as the background of the `<pre>` container in dark mode.
![image](https://user-images.githubusercontent.com/3119646/96336743-997a0300-10b4-11eb-9d3c-f4a636aefa33.png)

**Comment by t3chguy** [comment]
That's an unrelated issue @Transfusion .

That's https://github.com/vector-im/element-web/issues/9052

**Comment by SimonBrandner** [comment]
![Screenshot_20210314_101148](https://user-images.githubusercontent.com/25768714/111063227-b244e400-84ad-11eb-9b29-b91e08bb043d.png)
Closing as this doesn't seem to be a problem anymore
