### ISSUE TITLE
3PID invites do not preserve DMness

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6104]
So that when a user registers a 3PID and picks up the pending invites for that 3PID, whether they should be considered DM or not is lost.

**Comment by uhoreg** [comment]
This looks like a dup of #2794 which is supposedly fixed two days ago? (ping @t3chguy )

**Comment by t3chguy** [comment]
I only tested sending side tbf

**Comment by ara4n** [comment]
it's the receiving side which was broken in this instance

**Comment by t3chguy** [comment]
Yah I'll investigate
