### ISSUE TITLE
Pills can cause scrollbars in the composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6113]
### Description

Seems to only be a problem for people without avatars:
![image](https://user-images.githubusercontent.com/1190097/36042211-567c98a6-0d88-11e8-874d-2a9cdda361f5.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by weeman1337** [comment]
I cannot reproduce this issue any more. Close because it was presumably solved in the last five years.

If you keep experiencing this defect, reopen the issue.
