### ISSUE TITLE
Hide invite-only rooms on community page

### ISSUE THREAD

**Issue by chriswep** [vector-im/element-web#6114]
Right now: Rooms are listed on the community page (with the tag "Guests can join", which is [another issue](https://github.com/vector-im/riot-web/issues/5317)).

Maybe there are use cases where those rooms need to be visible for non-invited members. But i would expect the default behaviour to be that private rooms are only visible to room-members.

**Comment by t3chguy** [comment]
I don't think the group server would be able to check whether you are in the room to be able to do this

**Comment by turt2live** [comment]
fwiw, when adding the room (in develop) there's a checkbox that allows you to hide rooms.
![image](https://user-images.githubusercontent.com/1190097/36051600-e781b920-0da7-11e8-8450-702991793d0f.png)

**Comment by t3chguy** [comment]
but thats show/hide to group-members
rather than to the room-members as the issue asks for

**Comment by turt2live** [comment]
I really need to practice reading the entire post. Sorry, don't mind me.

**Comment by t3chguy** [comment]
it might still be sufficient for the user - who knows

**Comment by chriswep** [comment]
@t3chguy you are right that the current setting does not help here.

desired use case: within a team (= community) not every member should take part in every conversation. not being able to hide private rooms from non-room-members can cause confusion or other problems (both on the UX level and on the team culture level).

@t3chguy if i get you right this needs to be additionally posted as a feature request on the synapse repo?

**Comment by t3chguy** [comment]
It's fine here, but I doubt feasible as then you run into allowing arbitrary group servers to look at the list of room members. I'll leave for a more groups minded person to take a look at and triage

**Comment by chriswep** [comment]
ok. i'm don't have enough insight into how all those things are linked together behind the scenes. But isn't the use case a very basic one from a high level perspective? Maybe it has also to do with how one defines "community". I have a more slack like environment in mind for a community/team. Actually the issue came up moving from mattermost, which in addition to slack allows having a multiple teams on a common user-space. Matrix in addition to that has a completely open user-space which is one step more in the right direction (among other things). So coming from the perspective of an (i think quite common) use case here.

**Comment by t3chguy** [comment]
The issue is with the decentralization involved, the Group Server might not be a Homeserver and thus might not have access to the room to see who is actually in it

**Comment by matthijskooijman** [comment]
One way I can imagine to solve this, is to hide the rooms on the client side (which should know about all joined rooms, right?) instead of on the Group Server side. This will not really make them private, but will prevent user confusion (at the risk of users expecting more privacy then they actually get...)

**Comment by t3chguy** [comment]
Solved by Spaces
