### ISSUE TITLE
clicking permalinks for search results can result in permalinks being off the bottom of the page

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6126]
by quite a long way. i think this is a regression. although my window was quite large

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4121

**Comment by t3chguy** [comment]
This was fixed recently through [RAF](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
