### ISSUE TITLE
exception if pushRules.global.override is missing

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#6128]

**Comment by jevolk** [comment]
To reproduce, have the server respond to `/_matrix/client/r0/pushrules` with an object missing an "override" member or the "override" member is an iterable type.

**Comment by lampholder** [comment]
Anyone fancy helping me triage this? How often does it happen? How does it manifest to the user? What doesn't work as a result?

For now I'll just triage it as 'bug'.

**Comment by turt2live** [comment]
We rewrite the push rules these days, which includes a check for this case implicitly.
