### ISSUE TITLE
focus and blur of the MessageComposer send typing notifs?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6129]
says jzk

**Comment by jevolk** [comment]
To reproduce, simply click on the input box and a `{"typing":false,"timeout":30000}` will be sent when no text is entered. When clicking off the input box, after having entered nothing, the same typing=false is sent again.

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by jryans** [comment]
Needs more info, going to assume it's not.
