### ISSUE TITLE
RoomTiles that are :hover :focus are now darker

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6142]
Following the beautiful dnd changes that included changing the background colour of RoomList. This affects all themes.

**Comment by lampholder** [comment]
@lukebarnard1 I've `p2` `minor`ed this because I can't notice the difference on riot/develop - if I'm missing a more dramatic change let me know 'cause this might be higher priority

**Comment by lukebarnard1** [comment]
0.13:
![2018-02-15-152803_260x114_scrot](https://user-images.githubusercontent.com/6750344/36264565-f4b658a0-1264-11e8-8a77-8f8ba9763c26.png)

0.14:
![2018-02-15-152847_235x100_scrot](https://user-images.githubusercontent.com/6750344/36264564-f49fe2c8-1264-11e8-8cac-e8c939f46bbb.png)

**Comment by yannicka** [comment]
Is this issue still relevant?

**Comment by t3chguy** [comment]
I don't believe so
