### ISSUE TITLE
Failed attempt to get Flair avatar media results in weirdness

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6151]
![2018-02-15-103247_488x77_scrot](https://user-images.githubusercontent.com/6750344/36252186-a27c6238-123b-11e8-8729-359e00cd2953.png)

**Comment by lampholder** [comment]
Yuck yuck yuck yuck yuck yuck yuck yuck yuck yuck

**Comment by novocaine** [comment]
Wont fix - this is specific to communities, deprecated in favour of spaces.
