### ISSUE TITLE
Sandbox integrations iframe

### ISSUE THREAD

**Issue by rugk** [vector-im/element-web#6165]
The integrations/site at https://scalar.vector.im/ are always embedded via an iframe.

One big advantage of decentralization is, that, if one service is hacked you can still use another one.
The problem now here is if https://scalar.vector.im/ is hacked, it has full access to the whole page (and thus chats, etc.), so we've got another single point of failure 

See e.g. https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/ for how to do it.

Without that it may be better to disable that feature. (https://github.com/vector-im/riot-web/issues/6163)

BTW, if you have other iframes loaded from somewhere else, that of course also applies there. You'd don't want any not-sandboxed iframe on your site.

**Comment by turt2live** [comment]
The iframe needs access to the page so that it can interact with Riot. There's a communication channel between Scalar and your client so it can configure the various integrations.

However, some additional security (if it's not already in place) wouldn't hurt - provided that communication channel is still maintained.

**Comment by rugk** [comment]
Oh, no. You know this completely defeats the purpose of self-hosting?

So yeah, maybe if you can use a sandbox without `allow-top-navigation` that would already help. I did not try that.

**Comment by turt2live** [comment]
There's the option of using third party integration managers (I happen to be the author of one - Dimension).

**Comment by rugk** [comment]
Okay if that is self-hosted then, that's good, yeah.

**Comment by t3chguy** [comment]
We use sandbox attributes now
