### ISSUE TITLE
Group name, description, etc should also be draggable from the groups page

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6169]
### Description

I can't seem to see a reason why - dropping them in various places doesn't do anything. I also can't drag the text next to the avatars, so it feels like a bug.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
And we were worried their draggability wasn't discoverable!

You can drag them onto the Left Left Panel :) We have an outstanding item to add some microcopy (plus perhaps an animated gif) to show users _why_ they might want to drag those avatars :P

**Comment by turt2live** [comment]
I only found out because I was wondering what https://github.com/vector-im/riot-web/issues/6156 was talking about.

I'll change this to be a request to have the text also draggable (making the whole widget draggable).

**Comment by lampholder** [comment]
I think we might actually solve this differently; adding some UX hints to the avatars to show that they are what you use. But yeah, the work to make this interaction in the slightest bit discoverable or friendly has not yet been done.

**Comment by turt2live** [comment]
@lampholder I think the microcopy that was added (see https://github.com/vector-im/riot-web/issues/5830) makes this more complete. Is there something else that you were thinking of?

I know the issue title says "please make it all draggable", however the microcopy makes a huge difference in making it more obvious to me.

**Comment by lampholder** [comment]
@ara4n plans to do some UX work to make either the avatars or the avatars+text look more 'dragable'. There's also a thought that we might add either a image (or an animated image, though ideally that would somehow be dismissable) to draw attention to the dragableness.

**Comment by robintown** [comment]
Spaces are in beta, and dragging groups is no longer possible
