### ISSUE TITLE
Removing a group you're filtering on can leave you in a confused UI state

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6178]
### Description

I'm not sure what the expected action should be (perhaps going back to 'global'?). If you click on a group to filter by it then remove it your LLP is updated correctly however your room list is still filtered. In my case, I didn't realize what happened until a few moments later when I was done removing groups from the LLP.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
>perhaps going back to 'global'?

Sounds sensible. :+1:

**Comment by aaronraimist** [comment]
Fixed by spaces
