### ISSUE TITLE
Riot forgets which groups are selected in the LLP when refreshed

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6193]
### Description

I was a bit surprised when I refreshed Riot and it forget which groups I had selected. I realize it's not implemented as a feature, but this would be nice. Probably only needs to apply to the current device (local granular sentinels).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
