### ISSUE TITLE
Show placeholder avatar as flair for groups with no avatar set

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6202]
### Description

As a relatively experienced user this pains me to admit, but I spent an hour troubleshooting why a group didn't have flair. I was playing with synapse settings, riot versions, and even double checking the visibility settings for the user. Eventually I opened riot-android to see the placeholder avatar and realized that riot-web wasn't showing flair for the group.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Heh - certainly if somebody has gone to the trouble of honouring flair in a room and choosing to display that flair on their account then showing the placeholder avatar is going to make the next step much more obvious.

**Comment by turt2live** [comment]
I'm closing this because Groups don't really exist anymore. If someone would like this for Spaces, please open a new issue.
