### ISSUE TITLE
Clicking member avatar sometimes doesn't display preview

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6206]
Having a chat (1:1) with a specific user, I click the MemberInfo Avatar (in RightPanel) but nothing happens, nothing logged.

**Comment by t3chguy** [comment]
It wasn't a 3pid invite by chance was it?

**Comment by lukebarnard1** [comment]
Nope, but it was someone who had just signed up.

**Comment by ara4n** [comment]
can haz rageshake?

**Comment by airblag** [comment]
Not sure what preview means in the ticket, but I think I have the same issue while trying to view the avatar picture in the member list of communities. 

What work : 
- go into a room with some users
- select a user in the right panel 
- click on the avatar (it shows the (+) magnifying glass)
-> the image is shown in big and a link proposes download 

What doesn't work:
- go into a community home page
- select a user in the community members list in the right panel
- click on the avatar (it shows the (+) magnifying glass)
-> nothing happens. Dev tools of firefox don't show any request being sent while clicking on the avatar.

**Comment by yannicka** [comment]
Is this issue still relevant?

**Comment by jryans** [comment]
Hmm, seems to be fixed here. The communities case is likely not relevant any more, as that will soon be rebuilt.
