### ISSUE TITLE
Rooms without explicit names are badly shown in group room list

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6209]
<img width="650" alt="screen shot 2018-02-20 at 11 59 40" src="https://user-images.githubusercontent.com/1294269/36422819-8dc4120c-1635-11e8-94b8-00621f3e348d.png">

^ is a room with an alias, but no m.room.name. We should show it by its alias, just as we do in the RoomList.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
