### ISSUE TITLE
key sharing requests seem to be a lot less frequent since indexeddb

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6211]
previously i was constantly pestered with key share requests whenever one of my devices had a UISI. something seems to have changed meaning that even if i have the keys for a session on one device, i can still find myself staring at a UISI for the same message on another device without keys being requested

**Comment by lampholder** [comment]
I have also noticed this.

**Comment by poljar** [comment]
We don't notify users anymore about incoming key share requests and they do seem to be sent out if there's an UISI. This probably isn't relevant anymore so closing.
