### ISSUE TITLE
Double clicking the close button on a widget's title bar selects the entire frame

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6218]
### Description

![double-click-close-selects](https://user-images.githubusercontent.com/1190097/36494211-b244e5a2-16ee-11e8-9740-394ba62d8ecd.gif)

The green tint is the highlight effect. It can be clicked through to get it to go away. Can only reproduce with a double click.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm confused - this widget close button doesn't look like my widget close button (I have a bin), and doubleclicking that bin doesn't do what this does :package:

Also, github, you win. `:P` autocompletes to :package:, so from now on :package: is me sticking my tongue out.

Anyway, do we know why we have different widget UX?

**Comment by turt2live** [comment]
@lampholder it's an X when you're not able to modify widgets in the room

**Comment by lampholder** [comment]
Thanks for the prod!

**Comment by turt2live** [comment]
button removed
