### ISSUE TITLE
Unexpected ordering when dragging room tiles while filtered in the LLP

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6219]
### Description

In the GIF below, I was filtered on a group which does not show "Synapse Homeowners" in my favourites. When I dragged the riot-dev room above the riot room, I expected it to be just above that room when I switched back to showing everything. Instead, the riot-dev room was above the synapse homeowners room.

![unexpected-ordering](https://user-images.githubusercontent.com/1190097/36495229-d6ff8d18-16f1-11e8-886b-c480be42f7a9.gif)
(ps: the X is shown because I manually applied the styling for the change - it hasn't landed as of writing this)

The GIF doesn't show it, but the favourites ordering before dragging/filtering is:
* Synapse Homeowners
* Riot
* Riot dev
* ... other rooms

I can only reproduce this if the hidden rooms are at the top or bottom of the tag.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
However we implement the ordering of favourites or any sublist, we will have this problem (so long as we allow reordering of rooms whilst filtering in some way).

**Comment by turt2live** [comment]
If the reordering considers tiles that aren't visible, I suspect it won't be too bad. In the demo, I was trying to get riot-dev in the slot above riot, so the homeowners room would be considered as a non-visible tile.

**Comment by lukebarnard1** [comment]
But essentially it's a guessing game where you're inserting a tile where there would otherwise be tiles that are currently hidden.

For example you could have dragged room A between room B and room G where rooms C thru F are hidden, but each have their respective `order`. What `order` could you possibly give room A at that point?

**Comment by turt2live** [comment]
I spent a little bit of time with paper and came up with this (apologies for bad handwriting):
![image](https://user-images.githubusercontent.com/1190097/36502630-c4e2ffb4-1707-11e8-8269-ce6788e70ff8.png)

It does consider direction in order to make an estimate as to where the tile should be placed.
* riot-dev becomes `0.15` when moved above riot because `riot < riot-dev` (and homeowners is hidden)
* riot-dev becomes `0.65` when moved below matrix-dev because `matrix-dev > riot-dev` (arch being hidden doesn't apply here)
* riot-dev becomes `0.45` when moved below core because `core > riot-dev` (same as above)
* riot-dev cannot be moved below HQ because the tile isn't visible

Does this make sense?

**Comment by lukebarnard1** [comment]
The issue here is when dragging it below core, the user might expect it to be above matrix-dev. Basically there's nothing to tell you whether to put it below core or above matrix-dev.

**Comment by turt2live** [comment]
Right, and I think that's a better compromise than the current situation. There's the option of disabling reordering while filtering, but that seems a bit extreme to be honest.

Having the new ordering being as close as possible to the original position is a bit less jarring than having it be in the wrong spot, imho.

**Comment by t3chguy** [comment]
Manual ordering in the room list is dead, esp dnd
