### ISSUE TITLE
Dedupe groups for flair on users

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6222]
### Description

Issue described here: https://github.com/matrix-org/synapse/issues/2905

Riot should probably also protect against this in the event of a server returning strange data.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by novocaine** [comment]
Wont fix - this is specific to communities, deprecated in favour of spaces.
