### ISSUE TITLE
We don't tint $panel-divider-color

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6228]
![2018-02-22-120451_313x98_scrot](https://user-images.githubusercontent.com/6750344/36537625-a646c808-17c8-11e8-803a-0cc5f2a4ec83.png)

**Comment by lampholder** [comment]
@lukebarnard1 am I right in thinking there's an agreed approach to resolving this now?

**Comment by lukebarnard1** [comment]
Nothing agreed, I'd suggest we opt for something like picking a colour with saturation 0, lightness whatever, opacity whatever for each theme.

**Comment by turt2live** [comment]
Closing due to tinting disappearing from the app.
