### ISSUE TITLE
Tag in LLP for just private chats

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6234]
### Description

Now that I'm forcing myself to use groups in the LLP to organize my rooms, I'm finding it surprisingly common that I go looking for a "private chats" icon in the LLP before clearing the filter and scrolling the room list. Part of this may also be that clearing the filter causes my room list to freeze the browser while it renders, however a dedicated icon might not hurt for private chats (a la Discord).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
As long as we can maintain a system that is easy to understand I'm up for the LLP's being as flexible as possible - we will need to consider each change carefully, though. ATM everything in that LLP is a community - if we change that, we need to make sure users can still maintain a good idea of what those things on the left are :)

**Comment by turt2live** [comment]
This is being experimented upon with Spaces
