### ISSUE TITLE
when you drag & drop a RoomTile, if you move the mouse whilst you drag it to pick it up, the tile can end up floating far away from the cursor

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6237]

**Comment by lampholder** [comment]
I was able to reproduce this occasionally on Chrome on my mac and on Windows; I wasn't able to reproduce it on my (more capable) desktop ubuntu machine.

**Comment by lampholder** [comment]
`minor` `p2` 'cause I think it's relatively hard to trigger - please note here if you're seeing it often.

Also, I think react-dnd-beautiful goes to some pains to handle the dragee being in the right place relative to the mouse pointer, so it's possibly a bug in there.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/8614
