### ISSUE TITLE
Self hosted Riot Web personalize

### ISSUE THREAD

**Issue by raa0x0** [vector-im/element-web#6238]
Hello, I have two questions.
One:
There is the way to personalize "welcome" site? There are a lot of rooms from riot and matrix server.
>https://chat.xxx.xx/#/home

We have self hosted riot-web, matrix-synapse with own identify server and we want only see our rooms.

Two:
In directory listing we have unnecessary "Matrix" field in drop down menu. How we can remove this? We have only our server in config file.
>https://chat.xxx.xx/#/directory

Here is our config.json:

> {
>     "update_base_url": "https://riot.im/download/desktop/update/",
>     "default_hs_url": "https://chat.xxx.xx",
>     "default_is_url": "https://chat.xxx.xx",
>     "brand": "XXX",
>     "integrations_ui_url": "",
>     "integrations_rest_url": "",
>     "integrations_widgets_urls": [
>         "",
>         ""
>     ],
>     "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
>     "welcomeUserId": "@riot-bot:matrix.org",
>     "roomDirectory": {
>         "servers": [
>             "chat.xxx.xx"
>         ]
>     },
>     "piwik": {
>         "url": "",
>         "siteId": 1
>     }
> }

Thanks for answers.

**Comment by t3chguy** [comment]
Edit the home.html file at the root of the app.

**Comment by raa0x0** [comment]
After edit and cache clear, web server restart "https://chat.xxx.xx/home.html" is ok, but in riot everything is the same. When I edit index.html <title>, when I refreshing riot site new name appears only for second.

**Comment by t3chguy** [comment]
That's #3973

**Comment by kittykat** [comment]
I'm going to close this for now as this looks like a support request.
