### ISSUE TITLE
Clicking a permalink in the files panel closes it

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6249]
### Description

This is really annoying when you're scrolled up to try and find a specific file and find out you clicked the wrong file.

### Steps to reproduce

- Open the file panel
- Click the timestamp next to a file
- Observe the file panel returning to the member list

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Seems to have been fixed at some point
