### ISSUE TITLE
window state saving on electron can get make window disappear completely

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6252]
I just had desktop Riot become completely invisible after OS X resized it to whatever silly size it resizes windows to on changing monitors. Only way I could get the window back was to delete window-state.json.

This was my window-state.json:

```
{"width":1,"height":22,"x":1280,"y":23,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}}
```

**Comment by turt2live** [comment]
fwiw, this happens to pretty much every application on windows in the same circumstances. The best way to get it back (I've found) is to maximize it then use the snapping hotkeys to get it back. Not sure if there's a similar way to do this on mac.

**Comment by dbkr** [comment]
Much as I'm sure this bug would like to see it's 5th birthday, I haven't had it since so let's assume it's fixed.
