### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by ptman** [vector-im/element-web#6255]
It would be great to be able to post polls (like twitter or like doodle) into rooms. I did try searching for an open issue but didn't find anything

**Comment by MTRNord** [comment]
I think there is a issue in the Matrix wishlist by TravisR

**Comment by genofire** [comment]
Why is this not implemented like in android?

https://github.com/vector-im/element-android/pull/810

**Comment by PxBCPG** [comment]
This is a very interesting feature that we need to have in all clients

**Comment by witchent** [comment]
One question that I did not find anything on github (but maybe I just missed it):
The MSC states that one should pin polls to keep them visible, which makes a lot of sense. But somehow, while I can pin normal messages with the lab flag enabled, I can't seem to pin polls. Is this known or even intended, or should I create an issue?

**Comment by robintown** [comment]
Polls have been released
