### ISSUE TITLE
MyGroups needs to be QA'd for accessibility

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6256]
Firstly, pressing space (which is how to select something for dragging) will open the focused group's page, regardless of the focused element (the user can tab through to select either the Draggable (indicated with orange square) or the group avatar/AccessibleButton itself).

Secondly, the drag-n-drop aspect needs reconsideration - although react-beautiful-dnd might be able to support dragging avatars via keyboard, it's not exactly intuitive (in-fact it's about as intuitive as the mouse equivalent).

**Comment by SimonBrandner** [comment]
Spaces are now in beta
