### ISSUE TITLE
IRC bridge integration fails

### ISSUE THREAD

**Issue by mstenta** [vector-im/element-web#6263]
### Description

I am trying to bridge #farmOS:matrix.org to the IRC room #farmOS on Freenode.

When I click "Request Integration" (the final step in the process), the progress wheel spins for a little while and then I get the following error message:

`Unexpected token < in JSON at position 0`

### Steps to reproduce

- Create new Riot room.
- Create new Freenode IRC room.
- Add IRC integration to bridge the two.
- Click "Request Integration"

The MatrixBot user joins the IRC room just fine, but only stays for a few seconds:

`* MatrixBridge (matrixirc@gateway/shell/matrix.org/x-lfkgoqumatceqvdr) has joined
* MatrixBridge (matrixirc@gateway/shell/matrix.org/x-lfkgoqumatceqvdr) has left ("User left")`

And in the Riot room: `@appservice-irc:matrix.org joined the room.` (and stays there)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
- **OS**: Ubuntu 16.04 (64-bit)
- **URL**: https://riot.im/app/#/room/#farmOS:matrix.org

**Comment by mstenta** [comment]
Update: Just noticed that one of the times I tried I got a DM from MatrixBridge in IRC:

> @mstenta:matrix.org has requested to bridge 'farmOS' (https://matrix.to/#/#farmOS:matrix.org) with #farmos on this IRC network. Respond with 'yes' or 'y' to allow, or simply ignore this message to disallow. You have 300 seconds from when this message was sent.

I've tried requesting integration 7 times, and this only happened once (on the 6th try), but I didn't notice it an the 300 seconds went by.  On my 7th attempt I didn't get the message.

So maybe it's just an issue with MatrixBridge messaging?

**Comment by mstenta** [comment]
Ah ha! Got it!

It took a few tries to get the message to come through - but it looks like it worked.

**Comment by icarito** [comment]
Seeing this same issue.

**Comment by jwflory** [comment]
I have seen this issue continually for about a year. This is one of the biggest needs for some of the communities I manage that use IRC and Riot. It would be nice to see this reviewed more closely.

**Comment by abbec** [comment]
I also have this issue and it seems like a gateway timeout. Is there any workarounds or anything I can do?

**Comment by mstenta** [comment]
I will reopen this since others are having trouble as well. I did get it to work myself, and haven't had problems since.

**Comment by abbec** [comment]
My particular error was solved by a restart of the scalar IRC bridge :)

**Comment by jwflory** [comment]
For what it's worth, I had a friend in Europe (@Nolski) add the integration and it worked on the first try. I tried doing this from North America (New York specifically) with no success. Perhaps this is a geographical issue.

**Comment by t3chguy** [comment]
If you are still experiencing this issue I suggest reaching out to the host of the bridges
