### ISSUE TITLE
communities in RoomSettings for flair etc should be pillified

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6268]
and link through to the room in question and show the avatar etc

**Comment by lukebarnard1** [comment]
It'd be fun to make this like editing a list of pills as if in a restricted message composer...

E.g. for room aliases:

![2018-02-28-175847_598x153_scrot](https://user-images.githubusercontent.com/6750344/36803959-0a0e9702-1cb1-11e8-9caf-ee1acde0b51d.png)

and we should finally [pillify groups](https://github.com/vector-im/riot-web/issues/5253) in the process.

(and maybe even pillify entries into AddressPicker :innocent:)

**Comment by t3chguy** [comment]
Closing as Flair will be entirely re-designed.
