### ISSUE TITLE
api to redact images from your HS across fed

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6274]

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/5025 (probably)

Related:
* https://github.com/turt2live/matrix-media-repo/issues/31
* https://github.com/matrix-org/synapse/issues/1263

As outlined on the related issues, something to consider would be the media being used in other events - should it also redact those?

**Comment by lampholder** [comment]
I think this needs reconciling with #5025 but it's coming from a slightly different angle, so I'm going to leave this one open too for now.

**Comment by turt2live** [comment]
Closing in favour of single tracking issue: https://github.com/vector-im/element-meta/issues/398
