### ISSUE TITLE
Option to disable AGC

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/element-web#6278]
### Description

Automatic Gain Control keeps increasing my recording volume constantly, despite it causing the volume to clip. This is rather annoying and it took me ages to find out what was even causing it (apparently it's a Chromium feature)

### Steps to reproduce

- Have a voice or video call
- Notice recording volume rising at random points

Log: not sent    

### Version information

- **Platform**: web
- **OS**: Fedora 27
- **Version**: 0.13.5

#4634 seems to be related, but I only ever do one-on-one chats so haven't experienced it in conference calls.

**Comment by lampholder** [comment]
Do you know if this is possible to do in Chrome/Chromium?

From my 30 seconds of searching it looks like disabling AGC is supported in Firefox but maybe not elsewhere?

**Comment by jkalousek** [comment]
As this is still a problem I searched and in Chorme's "chrome://flags/" I found flag for "WebRTC hybrid Agc2/Agc1" and there is also "WebRTC Echo Canceller 3" which might be good option to be able to disable. Can these options be utilized?

**Comment by MazeChaZer** [comment]
I too have problems with AGC, it constantly keeps lowering the microphone volume until it's too low that I could be understood. I always have to fiddle around with system volume control and it's super annoying :(
OS: Arch Linux, riot-desktop 1.1.2

**Comment by darkmattercoder** [comment]
Any status update? I did my first matrix audio conference a few days ago, and everything went to shit because the auto gain constantly changed the mic level.

**Comment by dingodoppelt** [comment]
having the same problem here. In firefox i disabled autogaincontrol, echo and noise cancellation and audio quality is terrific. I would love to turn those features off in riot-desktop as well since it makes it unusable for me when transmitting anything other than speech.

**Comment by BloodyIron** [comment]
This problem isn't going away. Google isn't interested in fixing this in Chromium/derivatives. Can we please get this implemented?

More details from a Chromium developer: https://bugs.chromium.org/p/chromium/issues/detail?id=435112#c3

This is hurting the experience for Element VoIP in the most popular browsers. And there is a method to solve this already. Can we get this added to a milestone already? It's been years.

**Comment by tleydxdy** [comment]
yes, this problem causes the other side to hear deafeningly loud static, I would consider this a major bug

**Comment by lumbo7332** [comment]
I think this is quite important. I was on a call with my friend, and the volume was just fine. But the next day, my microphone volume was fluctuating wildly and really hurting his ears. That only happens in the Desktop client though.

**Comment by Mewsen** [comment]
This is so important, how is this not implemented yet... imo the element desktop client is unusable for conference calls without it...

**Comment by BloodyIron** [comment]
The auto-gain is really obnoxious, it keeps turning it down way too low and people can't hear me. Need to turn volume back up, only for it to go back down. :/ no way to turn off or adjust behaviour...

**Comment by tleydxdy** [comment]
I have resorted to using https://github.com/joeywatts/disable-autogain-control-extension

**Comment by BloodyIron** [comment]
While that can work as a stop-gap, convincing others to use that is really problematic. Also, using that on mobile?

**Comment by t3chguy** [comment]
> Also, using that on mobile?

Any solution from this repo won't work on mobile

**Comment by vi** [comment]
I see this issue as "closed as completed by a commit", but on app.element.io I see only "Noise suppression" and
"Echo cancellation" advanced audio settings, not "Automatic microphone gain control".

Shall the issue be reopened?
