### ISSUE TITLE
Report of initial sync never completing for one account.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6292]
Issue reported via rageshake. Works fine for new accounts, never completes for established account.

**Comment by grahamperrin** [comment]
Was any particular browser associated with this report?

**Comment by lampholder** [comment]
If I'm reading the user agent correctly it looks like Electron

**Comment by jryans** [comment]
The seems too old and specific to one user without any detail on what's happening. Let's close this and file new issues with more details if it comes back.
