### ISSUE TITLE
Markdown formatting intermittently fails in E2E rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6298]
I've had this happen twice now:

<img width="382" alt="screen shot 2018-03-12 at 09 45 36" src="https://user-images.githubusercontent.com/1294269/37276621-23485b7c-25da-11e8-9b0e-caa33053ecd5.png">

The bogus event is:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "### HAPPY MONDAY EVERYONE"
  }
}
```

There are no JS errors or anything weird there (but i'll rageshake anyway)

**Comment by ara4n** [comment]
(and markdown was enabled on the room all along; nothing changed between sending the 2 MD-formatted messages above).

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment]
Assuming no
