### ISSUE TITLE
Clicking (not dragging) a community on the communities page should open the community settings

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6299]
### Description

I spent an embarrassing amount of time mashing left click on the avatar until I remembered that dragging was a thing and that was probably eating my click.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Agreed.

I think react dnd beautiful even handles that well (inasmuch as it has some consideration for clumsy clicks if I remember correctly)

**Comment by SimonBrandner** [comment]
Spaces are now in beta
