### ISSUE TITLE
Notified on string that's a substring of my full displayname

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#6307]
### Description

My displayname is "&Adam". My mxid is "@adam:thebeckmeyers.xyz". I receive notifications when someone includes the string "Adam" in their message `body` despite not having set it up as a keyword. My notification settings look like this:

![riot_notification_settings](https://user-images.githubusercontent.com/17915621/37344940-2640a53c-26a2-11e8-9cca-ed88e9dbf0f0.png)

and my keywords look like this:

![riot_notification_keywords](https://user-images.githubusercontent.com/17915621/37344990-42f99602-26a2-11e8-8e43-b67f767efd54.png)

I see no reason I should be notified on the string "Adam".

### Steps to reproduce

See above.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome (ish)
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by non-Jedi** [comment]
Potentially related synapse bug: https://github.com/matrix-org/synapse/issues/2172

**Comment by ShadowJonathan** [comment]
I'm currently working on something like this with [MSC3517](https://github.com/matrix-org/matrix-doc/pull/3517)

**Comment by clokep** [comment]
This should be solved by [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952), which is available in Element Web, but might take some time to rollout to the entire ecosystem.
