### ISSUE TITLE
Changing your password does not update the devices table automatically

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6308]
### Description

Every other device is removed, however the table shows all the devices until you close and re-open the settings.

### Steps to reproduce

- Have many devices
- Open your user settings
- Change your password
- Scroll down to the devices table
- Note the number of devices (should be 1, but is instead many)
- Close and re-open the settings
- Note the number of devices (is 1)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This got fixed as session management is now on a different tab
