### ISSUE TITLE
Narrow group avatar seems to get stretched when rendered as flair

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6309]
I was testing how quickly changes to group avatar are reflected locally (the good news - it is indeed immediately) when I noticed that using this particular image as flair:

![vintage_phone_gif_animation](https://user-images.githubusercontent.com/1922197/37349980-9b3b161a-26cf-11e8-8eca-909b6d2adef0.gif)

resulted in an ugly stretching effect:

![image](https://user-images.githubusercontent.com/1922197/37349968-95954a32-26cf-11e8-87a9-c86b20c9765d.png)

Chrome Ubuntu /develop

**Comment by SimonBrandner** [comment]
Spaces are now in beta
