### ISSUE TITLE
Group/community long description remains (superficially) editable to admins even after they leave the group

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6310]
- Create a group
- Leave the group
- Click on the long description box
- Typey typey typey

You're not the admin any more, so it should be styled disabled.

It's no biggy, since you can't actually save your changes, but it looks glitchy.

**Comment by turt2live** [comment]
Sounds like a duplicate of https://github.com/vector-im/riot-web/issues/6180 by symptoms only

**Comment by turt2live** [comment]
The root of this issue appears fixed, however there's a small delay between the time you leave and when you can no longer reach the settings. During this time, you're able to go back and poke around.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
