### ISSUE TITLE
Markdown headers don't look different enough

### ISSUE THREAD

**Issue by k80w** [vector-im/element-web#6319]
### Description

The headers that appear when you use markdown in a chat have little variation in size, weight, or style. Header styles 1 and 2 both appear identical. There should be at least a slight change between them.

### Steps to reproduce

Send two headers in any chat:

```md
# header 1
## header 2
```

![](https://i.imgur.com/qJJPZK8.png)

Both headers appear to have their `font-size` property set to `1.5em`, from what I can gather.

### Version information

- **Platform**: Both

For the web app:

- **Browser**: All
- **OS**: All
- **URL**: riot.im/develop

For the desktop app:

- **OS**: All
- **Version**: 0.13.5

**Comment by turt2live** [comment]
h1 and h2 are intentionally the same size as h3.

**Comment by lampholder** [comment]
I guess this _is_ unexpected - to my mind it's unexpected that markdown headers would work at all, and then further unexpected that, seeing as they do work, there is no distinction between h{1,2,3}.

I'm not sure I understand the original rationale for their working at all - does somebody know why we decided to support it?

**Comment by turt2live** [comment]
Going way back, it looks like it was an explicit request as per https://github.com/vector-im/riot-web/issues/1772 (which was implemented in https://github.com/vector-im/riot-web/pull/3719). I'm sure Matthew has more information about why though.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/19551
