### ISSUE TITLE
Dismiss the desktop notification if I read a message on another client/device

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6328]
### Description

This is probably closer to a me problem, so feel free to deprioritize this to oblivion. 

My common workflow is to be logged in to Riot on my web browser, however I also often have an remote session open to another device with Riot open. When I receive a desktop notification on the local machine and read the message, the notification disappears. The remote session's desktop notification doesn't go away though and instead has to time out, even if I've already replied to said message.

The 'fix' would probably be to have Riot listen for read receipt/marker changes and dismiss notifications accordingly.

This could also be reproduced if one reads a message on their mobile and glances back up to their desktop to see a notification hanging around.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
We do this now
