### ISSUE TITLE
AddressPicker <kbd>tab</kbd> behaviour is wrong

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6337]
This includes: start chat; invite to room; invite to group; add room to group.
Actual:
 - start typing entry
 - hit tab -> completes
 - hit tab (on any element in the dialog!!) -> "You have entered an invalid address" (I haven't)

Expected:
 - If tab is hit but there is nothing to complete, the "Start chat" button should be selected.
 - If tab is hit and the entry box doesn't have focus, the tab index should be incremented.

**Comment by t3chguy** [comment]
This is only used for Groups now, closing as Groups is on its way to being deleted.
