### ISSUE TITLE
recaptcha doesn't work with torbrowser

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6345]

**Comment by ara4n** [comment]
which seems like a daft reason not to support tor :(

**Comment by lampholder** [comment]
critical - registration is totally broken for tor users
p2 - I think supporting tor users is very important, but not our absolute mission critical top priority right at this moment (happy to be convinced otherwise on this)

**Comment by patcon** [comment]
fwiw, i just signed up with most recent tor browser, and it worked fine, through took a few runs a recaptha, and seemed like the app kept forgetting state (related to recaptcha, and the agreement to ToS)

But yesh, I'm on via tor (with noscript deactived, as it is now by default)

**Comment by novocaine** [comment]
Closing as comment above suggests this is now working
