### ISSUE TITLE
Some links no longer get tinted

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#6351]
![image](https://user-images.githubusercontent.com/1012976/37615828-92a3f404-2b84-11e8-8afa-ab902f6b0a7d.png)
![image](https://user-images.githubusercontent.com/1012976/37615921-c8a8da06-2b84-11e8-99fd-9a25b44cbeb0.png)

It looks like links in the topic, in URL previews, and automatically-detected links in text are not tinted, whereas links that are sent as part of the formatted body are tinted

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 58
- **OS**: Debian
- **URL**: riot.im/staging (0.14.0-rc.2)

**Comment by uhoreg** [comment]
Tinting is not in the latest Riot, so this is no longer an issue.

**Comment by turt2live** [comment]
there's plans on potentially bringing it back, so I think we should leave this open as a reminder: https://github.com/vector-im/riot-web/issues/8421

**Comment by turt2live** [comment]
Closing due to tinting disappearing from the app.
