### ISSUE TITLE
Available rooms section for Community filters

### ISSUE THREAD

**Issue by dali99** [vector-im/element-web#6360]
### Description

Community filters could have a section for rooms not currently joined but which are associated with the community. This would remove the annoying steps:
1. Go to the community dashboard
1. Click the relevant community
1. Click the room
1. Click "Join Conversation"

to just

1. Click the room
1. Click "Join Conversation"

![2018-03-12-003318_288x543_scrot](https://user-images.githubusercontent.com/990767/37688330-cd6b26fe-2c9f-11e8-948b-8396e4dcfeb7.png)

I aired the idea in the riot channel, but didn't get much of a response.

**Comment by lampholder** [comment]
I'm not sure I _100%_ like it as a peer of the other tags, but I really do like the idea of one being able to view the other rooms associated with a community in the roomlist. Certainly worth considering.

**Comment by dali99** [comment]
This seems to added with https://github.com/matrix-org/matrix-react-sdk/pull/5736 :smile:

**Comment by SimonBrandner** [comment]
@dali99, thanks for letting us know! Hopefully, Spaces will land soon!
