### ISSUE TITLE
Beautiful drag and drop can get into a broken state

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6367]
This seemed to happen when I:
- picked up (it happened to be RiotBot) and was dragging him around
- a group invite appeared
- either immediately before or after the group invite appeared, I dropped riot bot

The result was RiotBot got wedged in PEOPLE section, with the slightly wider appearance of a room tile being dragged, and **all drag and drop was broken** (even the LLP it seems).

Room tiles still worked to be clicked upon + ellipsis context menu also worked.

**Comment by lampholder** [comment]
I've since been able to reproduce this without an invite appearing at the same time. The room tile ends up sitting on top of the tag header and all DnD is broken.

This is difficult to reproduce reliably

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/8614
