### ISSUE TITLE
Lots of room members can cause the browser to crash during autocomplete

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6371]
> for the devs: typing [at] in this room crashes Riot... as there seem to be a lot of names that the autocomplete tries to show and firefox refuses to render them all and kills the render process for me

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15216557001832JYKqi:matrix.ffslfl.net

**Comment by turt2live** [comment]
also affects chrome (as per #6394)

**Comment by lukebarnard1** [comment]
Previously, we didn't autocomplete after 1 character for users (i.e. "@"). Now we do, it reveals how unperformant it is to render 15k things.

**Comment by ara4n** [comment]
Actually, is there a reason why we don't just cap the number of autocomplete things it tries to render at 100 or something?

**Comment by lukebarnard1** [comment]
@ara4n we could also do this, absolutely

**Comment by gsouquet** [comment]
Closing as a cap for autocomplete has been added recently and that should very much alleviate this issue. View matrix-org/matrix-react-sdk#6016
