### ISSUE TITLE
Underline on links inconsistent depending on whether or not the message is formatted

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6374]
### Description

![image](https://user-images.githubusercontent.com/1190097/37794533-5cdf10ec-2dd7-11e8-99af-79656c1d265e.png)

The first link is just a plain `m.text` event:
```
{
    "body": "https://matrix.org",
    "msgtype": "m.text"
}
```

The second link is sent with a custom format though:
```
{
    "body": "https://matrix.org",
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "formatted_body": "https://matrix.org"
}
```

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
BOO LINKS WITHOUT UNDERLINES BOO

**Comment by t3chguy** [comment]
These are gone, https://github.com/vector-im/element-web/issues/14737 is about bringing them back
