### ISSUE TITLE
Pills and usernames with /

### ISSUE THREAD

**Issue by Sorunome** [vector-im/element-web#6381]
mentioning pills don't work correctly if the username (localpart) contains a `/`, which is valid as to spec

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/riot-web/issues/4867

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/element-web/issues/10994

**Comment by Johennes** [comment]
Not reproducible anymore on current nightly.

<img width="436" alt="Screenshot 2023-06-28 at 19 55 14" src="https://github.com/vector-im/element-web/assets/1137962/ac58c11b-1c12-4b07-b603-5ec9c4cf85a4">
