### ISSUE TITLE
message sending ordering is still broken on bad connections

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6398]
send two messages on eurostar. first fails and is prompted for manual retry.. but the second then gets queued and eventually sent. so you end up sending messages out of order. has happened to me twice now (and made me look incoherent both times)

**Comment by lampholder** [comment]
So the fix here is to make sure that messages queue behind one another, so whilst you can't guarantee that your messages will interleave sensibly with the rest of the conversation, you can at least guarantee that your sequence of messages will be delivered in the order in which you wrote them.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/22885
