### ISSUE TITLE
can't invite users or save email in account section

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6400]
can't invite users or save email in account section
500 error shown. This is the response while saving email.
Request Url: Request URL: https://matrix.org/_matrix/client/r0/account/3pid/email/requestToken
{"errcode":"M_EMAIL_SEND_ERROR","error":"Failed to send email"}

**Comment by lampholder** [comment]
From a rageshake

**Comment by lampholder** [comment]
I can't reproduce this.

We might be able to find out something useful by looking through the logs, but grepping through sydent.log turned out to be more faff that I felt was worth my doing (so I gave up).

Leaving this open for now in case more people experience the same issue.

**Comment by t3chguy** [comment]
Closing due to lack of reproduction
