### ISSUE TITLE
user avatar in group you-have-been-invited section is in wrong aspect ratio

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6407]
![screen shot 2018-03-28 at 10 45 04](https://user-images.githubusercontent.com/986903/38021559-185fa7ea-3275-11e8-95c4-3e34e898fd9a.png)
because it doesn't specify method=crop to the thumbnail URL

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
