### ISSUE TITLE
Underscores in code blocks cause italics

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6434]
### Description

![image](https://user-images.githubusercontent.com/1190097/38205369-9589b7aa-3663-11e8-89b3-eba7b3d0d14c.png)

Subtle, but it's there.

Here's the full code block posted in a message:
```
synapse=# select event_id, type, sender from events where event_id = '$1416421084971UjKCA:matrix.org';
            event_id            |       type        |      sender
--------------------------------+-------------------+-------------------
 $1416421084971UjKCA:matrix.org | m.room.join_rules | @kegan:matrix.org
(1 row)
```

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Gnh

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_162624](https://user-images.githubusercontent.com/25768714/109423915-b539d200-79e1-11eb-98cf-b854562c1e46.png)

Closing as this doesn't seem to be a problem anymore
