### ISSUE TITLE
Conference calls never work! 

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/element-web#6444]
### Description

Conference calling on my server frequently fails. You press the call button and it rings, but nobody else in the room is notified that this is happening.

Then of other members do eventually see the conference call, the red bar appears only for 1 second before vanishing. The original user who started the conference looses connection instead of being placed in a 1 person lobby.

There is also this matrix.org user who has to be invited in order for it to work, huge bottleneck when matrix.org is down, which happens all the time.

### Steps to reproduce

- Set up your own synapse server.
- Have a variety of clients in a room together.
- Try start a conference call.
- Experience total failure for 10-20 minutes.
- Give up and use another voice chat software.

### Describe how what happens differs from what you expected.

The person initiating the conference call is supposed to enter a 1 person lobby where guitar music plays. Other members can then choose to join as voice or video.

### Log: 

No logs collected, would like instructions on which ones are relevant and i can try recreate the problem.

### Version information

- **Platform**: both web client and 2 desktop clients.

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: https://perthchat.org

For the desktop app:

- **OS**: Debian, Ubuntu
- **Version**: 0.13.5

Is there any roadmap to fix this nasty conferencing system? And removing the matrix.org dependency? If every server needs matrix.org to perform normally then it's not very 'decentralized' at all to be honest. Makes me wonder why i run a Matrix server when it keeps failing so much. :(

**Comment by MTRNord** [comment]
I think the Roadmap is to replace that system with jitsi

**Comment by MTRNord** [comment]
(also about decentralisation-> @turt2live has written matrix-dimension which allows you to host your own jitsi to use it with conference calls)

**Comment by PC-Admin** [comment]
This is the latest error message i get:
```
Call Timeout
The remote side failed to pickup
```
> I think the Roadmap is to replace that system with jitsi

Thanks for the response, do you know when this is due?

> (also about decentralisation-> @turt2live has written matrix-dimension which allows you to host your own jitsi to use it with conference calls)

Where can i find steps to install this? And will it require users to take any extra steps to make conference calls? I don't really want to alter it if it makes things more difficult for the users.

**Comment by PC-Admin** [comment]
That's not a good solution because most of my users have the standard Riot client installed and this wouldn't work for them. I'll have to encourage them to use Jitsi until it becomes the standard.

Only like half a dozen more steps involved in making a conference call now. :P

**Comment by lampholder** [comment]
This is a known problem and it is on our immediate roadmap to address.

**Comment by BloodyIron** [comment]
What exactly broke this?

**Comment by smacz42** [comment]
The OSU Open source club tried conference calling during the Fall '17 semester, which went just fine. However, it now seems to be broken beyond usage.

As an added note, attempting to create multiple VoIP calls ended in each of the participants in the room having the same number of rooms created named "VoIP Conference".

This to me appears to be more of a regression than a bug.

**Comment by t3chguy** [comment]
The old conferencing system has been replaced with Jitsi
