### ISSUE TITLE
Replies (minor) snagging list.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6445]
I built and tested the latest m.relates_to branches and hosted it on https://lant.uk/riot/new_replies

Things I tested:
- Replying to your own message ✅ 
- Replying to your own reply ✅
- Replying to a message from someone else ✅
- Replying to a reply from someone else ✅
- Replying to an emote ✅
- Replying to a picture ✅
- Replying to a file ✅
- Not being able to reply _with_ an emote ✅
- Not being able to reply _with_ a file ⚠️ 
- Replying on a narrow screen ⚠️ 
- Replying with a single emoji ✅
- Replying in an E2E room when there are unknown devices in the room ⚠️ 
- Representation on today's /app ✅ ([In reply to](example.com) link links to the original message)
- Representation over IRC bridge ✅ (reply is rendered sensibly)
    ![screen shot 2018-04-04 at 09 56 53](https://user-images.githubusercontent.com/1922197/38298165-8c83c6e6-37ee-11e8-878b-b896bf884a09.png)

In conclusion, for the most part it's great and nothing was show-stoppingly broken, but the ⚠️s represent tests where the outcome could have been a little bit better (mostly from a UX perspective).

### Issues Identified
- [x] **P1** _Reply UX slow to disappear_ - The replies UX was sometimes slow to disappear (taking ~a second to disappear after the reply has been sent)
- [x] **P2** _Replying in an E2E room when there are unknown devices in the room_ - The current experience is:
    - initiate reply
    - type message
    - click send
    - receive 'unknown devices' prompt (which shows the reply as a red pending message, rather than a reply)
    - click 'send message'
    - message rendered to the timeline **as a message**
    - a few seconds later, the message appears (correctly) as a reply
- [ ] **P2** _Replying on a narrow screen_ - we get a return of the one-character-wide super tallness:
![screen shot 2018-04-04 at 10 00 54](https://user-images.githubusercontent.com/1922197/38298393-204ba52e-37ef-11e8-89ed-7f345d00cf16.png)
- [x] **P3** _Not being able to reply with a file_ - If you open the reply function then upload a file, the file uploads behind the reply UX (and not as a reply). It is a known limitation of the current impl that we can't reply with a file, but the UX doesn't make that obvious (in the way that it _does_, say, for our not being able to reply with an emote).
- [x] **P3** _Replying with a single emoji_ - it renders in the small style rather than the usual large style of a single... emojus

**Comment by Cadair** [comment]
I have just been giving this a little test a couple of quick thoughts:

1. there seems to be no way to click the rendered reply to jump back in the timeline to the location of the original message (to get extra context etc). Where as there is only this on `/app` currently, it would be nice if the (body of the) reply was clickable to jump back in the timeline imo.

2. When the `in reply to` of a reply to a reply is collapsed, the user pill is not clickable, either to take you to that user or to expand the reply. (I was expecting the latter)

Finally, I can't quite put my finger on what it is, but I feel that chains of two+ replies get's a little unclear. It's not visually obvious to me that I am effectively viewing a thread.

**Comment by t3chguy** [comment]
> message rendered to the timeline as a message

is VERY weird

**Comment by lampholder** [comment]
I've stuck bug p1 major on this because all these minor snags being addressed added up to a major improvement on the replies UX

**Comment by t3chguy** [comment]
`2.` of @Cadair 's thoughts has broken out into https://github.com/vector-im/riot-web/issues/6670

**Comment by turt2live** [comment]
Not sure if the design is up for consideration as well, however I'm kinda a fan of this:
![image](https://user-images.githubusercontent.com/1190097/41196991-0a1c3588-6c0c-11e8-9711-454327674fde.png)

It feels like it takes up a lot less space, despite only saving a line or two.

**Comment by ara4n** [comment]
ironically i think that matches @jounih’s proposed design in the rework

-- 
Matthew Hodgson
Matrix.org

**Comment by aaronraimist** [comment]
When replying to a /me, the sent time is displayed on top of the avatar ![Screen Shot 2019-09-27 at 9 59 16 AM](https://user-images.githubusercontent.com/5855073/65779499-79744c00-e10d-11e9-809f-9275caf2e5c6.png)

**Comment by penloy** [comment]
I'd like the ability to remove user avatars from replies in order to make them much more compact. Any other way of reducing screen space bloat would be appreciated.

Thank you.

**Comment by robintown** [comment]
Going off the task list above, it looks like the last outstanding issue has been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3553. Since the avatar is now removed from the preview, and the preview now stretches across the entirety of the composer, it's much harder to squish replies.
