### ISSUE TITLE
click handler on community description placeholder triggers on drag mouseup

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6453]
![apr-05-2018 18-00-30](https://user-images.githubusercontent.com/986903/38380335-4aac1cce-38fb-11e8-84d2-18debaf0fb53.gif)

**Comment by lukebarnard1** [comment]
This actually affects any element that is a HTML DOM element with text that can be selected, including community desc, name, member names in the member list (rooms/groups), member info action links, like "Disinvite", and many many others.

**Comment by lampholder** [comment]
:scream:

**Comment by lukebarnard1** [comment]
FTR this isn't communities specific, it affects a lot of the app, as I've mentioned.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
