### ISSUE TITLE
flash of unstyled content whenever you load the stickerpicker

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6455]

**Comment by rxl881** [comment]
@ara4n - I'm not sure what you are referring to here. Is it just a spinner, or something else (I've not seen / been able to replicate this). Any chance you can get a screenshot or something?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
