### ISSUE TITLE
Autocomplete is frustratingly unreliable

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6464]
### Description

There's a certain level of expectation that when I type `Please join #riot-and<tab><enter>` that I'll end up with `Please join [#riot-android:matrix.org]` as a message. However, if the browser stalls even for a moment (usually while calculating my autocomplete suggestions), I often end up with `Please join [#riot-ios:matrix.org]and` as a message. Having the wrong message be sent is incredibly frustrating and reduces my confidence that what I type is what is going to be sent.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
i wonder if this is related to https://github.com/vector-im/riot-web/issues/4708

**Comment by wsmwk** [comment]
@turt2live can you still reproduce this issue?

FWIW,  #4708 has since been closed

**Comment by novocaine** [comment]
Closing as no answer from OP
