### ISSUE TITLE
We expose the E2E fudge button even when we (probably) know that it is hopeless.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6465]
I was invited to an E2E DM room, and the other participant had already said some things. This rendered thus:
![image](https://user-images.githubusercontent.com/1922197/38430335-e1d69d96-39b8-11e8-8849-7a19b97e2e2f.png)

I'm guessing that in rendering the OLM.UNKNOWN_MESSAGE_INDEX error we probably know that there is no way we can recover the key from any of our other devices (is this true?). If this is the case, we might not want to expose the (in this case futile) E2E fudge button.

**Comment by lukebarnard1** [comment]
Another thing we might want to do is to tell the sender, "no one will be able to read these messages but you" before they can send a message into an e2e room if the sender is the only one joined.

**Comment by t3chguy** [comment]
The fudge button is gone
