### ISSUE TITLE
Embeddable vector (with guest autojoin to a given room and prompt for display name setting)

### ISSUE THREAD

**Issue by Xe** [vector-im/element-web#647]
It'd be nice to be able to embed a URL like `https://xeserv.us/chat/#/room/!iaQvHPVzpiSEwQCZlr:xeserv.us` into a webpage so people can join a webchat or the like.

**Comment by rubo77** [comment]
What exactly is missing? Doesn't that already work?

**Comment by BloodyIron** [comment]
Uhhh why was this closed exactly?

**Comment by t3chguy** [comment]
Doesn't look closed to me?

**Comment by BloodyIron** [comment]
I was mistaken, and you guys are super fast to respond, D:

Any chance we could have web-embedding along the lines of, too? : https://github.com/vector-im/riot-web/issues/5714

Sorry, didn't mean to make a mess here D:

**Comment by BloodyIron** [comment]
Oh, and just to clarify, the embedding I was talking about, was a watered-down app we can frame on a page to show some info, like who's in rooms, click to join, # of ppl online, etc. Not just a direct link.

**Comment by BloodyIron** [comment]
So, what's the feasibility of this?

**Comment by TaaviE** [comment]
Any updates on this? Any reasons its stalled?

**Comment by reesericci** [comment]
I need this and it seems stalled. any ideas?

**Comment by t3chguy** [comment]
It sounds like the role of another web client given that Element by product decision doesn't allow guests to join rooms.

**Comment by TaaviE** [comment]
@t3chguy Read-only would suffice though, messages being restricted to signed-in users can be dealt with.

**Comment by t3chguy** [comment]
This issue clearly asks for 

> with guest autojoin to a given room and prompt for a display name setting

If all you want is to iframe an Element defaulting to a given room then there is absolutely nothing stopping you.
You can't use the official Element instances as they prevent iframing due to clickjacking concerns but its not hard to host your own given that Element is just a bunch of static files.

**Comment by MadLittleMods** [comment]
https://cactus.chat/ does this. It's embeddable can add comments without logging in (guests)
