### ISSUE TITLE
If you quote a message including pills with no explicit avatar, they get mangled

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6476]
If you quote a message including pills with no explicit avatar, they get mangled as the letter from the avatar placeholder gets copied.

**Comment by MadLittleMods** [comment]
Seems to work fine nowadays. Replying or quoting

![](https://user-images.githubusercontent.com/558581/131796057-05127ca4-81fb-45af-a349-c7932ed8b65b.png)
