### ISSUE TITLE
Riot becomes permanently unresponsive (whilst typing a message)

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6484]
Typing a message, Riot seemed to pause but then became totally unresponsive. Rageshake sent!

**Comment by turt2live** [comment]
Possibly related: #6464 (due to the stop-the-world pauses)

**Comment by PipC** [comment]
I also find the lagging problem in desktop client V0.14.1 on Win10. But same build no problem on another Win7 desktop. Using browser web edition doesn't have this problem.

**Comment by orbitz** [comment]
This happens to me on Chrome running on FreeBSD.  Riot will just stop responding while I'm typing and another event happens.  I either have to wait for Chrome to tell me the page is unresponsive or kill the tab myself.

**Comment by Palid** [comment]
I haven't seen new reports with that, so I assume this has been fixed already.
