### ISSUE TITLE
e2e fudge button is enabled even if encryption is disabled

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6486]
and apparently claims to have sent the request: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$152345590267188WXvDo:matrix.org

**Comment by lukebarnard1** [comment]
Arguably, e2e rooms should be inaccessible if e2e is disabled. Generally we could do a lot better than spamming the timeline with error messages imo.

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/6465

**Comment by lampholder** [comment]
P2 minor because even if running riot with E2E disabled is a supported mode of operation, it's not super common (or at least, where it is being used without E2E, users are not expected to be accessing encrypted content).

**Comment by t3chguy** [comment]
The fudge button is gone
