### ISSUE TITLE
Riot doesn't show no-op member events

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#6493]
which can happen seemingly, and when permalinked to cause infinite back-pagination, so at least show them if they're parmalinked to

**Comment by lampholder** [comment]
Permalinking to an invisible event shouldn't cause infinite back-pagination (I'm sure we've hit that before).

Not sure we should render no-op member events, though - how would they be rendered?

**Comment by t3chguy** [comment]
It does with show hidden events enabled
