### ISSUE TITLE
Microcopy on community dashboard says "Drag a community to the left side" even when the tag panel is disabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6496]
### Description

It's somewhat difficult to drag the group to something that doesn't exist :(

### Steps to reproduce

- Disable the tag panel in your settings
- Click on the communities icon
- Read the help text

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: tang.ents.ca (0.14 - based on /app)

**Comment by lampholder** [comment]
Ugh. There are a number of ways we could fix this:
1. change the copy to advise the user how to enable LLP if it's not already enabled
1. include a link to 'enable llp' within the copy if LLP is not enabled
1. enable LLP on drag (and disable again if nothing is dragged there)
1. remove the copy and disable dragging if LLP is disabled

I think I like 3 best, esp. if it was supported by a nice animation to grow the llp on drag (and shrink again if nothing is dropped there)

**Comment by turt2live** [comment]
Just for a bit of perspective: The instance I noticed this on has the LLP disabled by default in the config because most (if not all) users are unlikely to interact with it at all, particularly considering they are all in the same 10 rooms. It'd be nice if there was a way to disable the microcopy's suggestion of the LLP entirely, however it's equally fine for us to maintain a fork for our weird use case.

**Comment by Palid** [comment]
@turt2live this one seems irrelevant now, can we close it?

**Comment by SimonBrandner** [comment]
Yeah, I am pretty sure we can
