### ISSUE TITLE
Joining a community over federation doesn't give you an avatar/display name in the community

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6497]
### Description

![image](https://user-images.githubusercontent.com/1190097/38642087-35f14cb0-3d96-11e8-90e6-5131105fc27c.png)

Both matrix.org users self-joined a community on tang.ents.ca. My account (TravisR) was invited, and ENTS Archive created the community. The matrix.org users should have display names and avatars set.

### Steps to reproduce

- Create a community on Server1
- Make it accessible to everyone
- Join the group from an account on Server2
- Note lack of avatar/display name

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: tang.ents.ca (0.14 - based on /app)

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
