### ISSUE TITLE
Enable flair automatically when joining a public group

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6507]
### Description

To reduce the "road to flair" (#5957)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I'm (perhaps unduly) nervous of enabling flair automatically for anything, though I agree the road to flair needs to be as short and painless as possible.

I wonder if we could modify/enhance the join community UX to include the concept of adding flair smoothly?

**Comment by turt2live** [comment]
perhaps a checkbox near the join button that says "Enable flair after joining the group"? Default checked imho :)

A dialog could also be used ("You joined X! Enable flair?"), however that feels way too intrusive to me.

**Comment by turt2live** [comment]
I'm closing this because Groups don't really exist anymore. If someone would like this for Spaces, please open a new issue.
