### ISSUE TITLE
Horrible error trying to add the same room twice to a community

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6509]
<img width="779" alt="screen shot 2018-04-13 at 00 21 45" src="https://user-images.githubusercontent.com/1294269/38708994-b84d4234-3eb0-11e8-8d70-1e65d354b5f4.png">

**Comment by dkasak** [comment]
This just happened to me too. However, the room didn't get added to the community on the first try either, so now I can't add the room to the community at all.

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
