### ISSUE TITLE
User panel desync

### ISSUE THREAD

**Issue by aidalgol** [vector-im/element-web#6525]
### Description

User details panel in the right-hand side panel gets out of sync.

![image](https://user-images.githubusercontent.com/2313201/38774414-3c82b6d0-40bc-11e8-963b-34191e81afc5.png)

### Steps to reproduce

1. Select a user by clicking their avatar in the events list or right panel.
2. Click "Ignore"
3. Select another user by clicking their avatar in the events list.

The "Ignore" button instead reads "Unignore", and clicking it appears to have no effect on your ignore list.

### Version information

- **Platform**: web _and_ Electron app
- **Browser**: Chromium version 64.0.3282.119 (Developer Build) built on Debian 9.3, running on Debian 9.4 (64-bit)
- **OS**: Windows, Debian
- **URL**: develop
- **App Version**: 0.14.1

**Comment by aidalgol** [comment]
Upon closer inspection, it appears that the callback is being rebound for the newly-selected user, and that this is a cosmetic issue (i.e. the "Unignore" button is not being changed to read "Ignore").

**Comment by yannicka** [comment]
Is this issue still relevant? I can't reproduce it.

**Comment by t3chguy** [comment]
It is not, that entire panel has been thrown out and replaced.
