### ISSUE TITLE
Starting a 1:1 chat with a user over federation, the UX appears to drop you in an empty room for a while before the invite is processed.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6535]

**Comment by turt2live** [comment]
@lampholder what's the expected fix here? Local echo on the invite or something smarter with the spinner where it waits longer before switching rooms?

**Comment by jaywink** [comment]
This also causes that if the homeserver is not federating but Riot is configured to auto-invite Riot Bot, there will be an empty room as a result.

**Comment by Palid** [comment]
@lampholder is this still reproducable? If yes, do you have any suggestions how should be action it? Probably adding some additional text would be good enough...?

**Comment by novocaine** [comment]
Closing as no answer from the OP
