### ISSUE TITLE
Getting an error message "Unable to join community" when clicking "Join this community" button on the community page for +community:matrix.org

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6537]
From a rageshake!

**Comment by thekyriarchy** [comment]
I clicked the join button on a community I admin and after the unable to join error, it said unable to display the community. The message shows up even after a hard refresh as well. Hard to to test because when communities do load they take several minutes to do so

**Comment by turt2live** [comment]
I think this is https://github.com/matrix-org/synapse/issues/2633 (or a closely related variant of it).

**Comment by SimonBrandner** [comment]
Spaces are now in beta
