### ISSUE TITLE
We've had a report of email address verification emails not making it to the destination

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6543]
Affected domain: free.fr

**Comment by ti-nico** [comment]
Hello, Any update on this ?
I am in the same situation, not receiving the verification email.
The process worked successfully with two other email adresses.
@gmail.com --> OK
@free.fr --> OK
@duret.as --> KO (I have registered that email on hover.com)

**Comment by Palid** [comment]
@lampholder @ti-nico Is this still a problem? If yes, let me know, as this issue is quite old now.

**Comment by ti-nico** [comment]
Hello,
According to my email history I received a verification email and I managed to register my email @duret.as on Oct 31, 2019.
So it sounds like this is not a problem any more.
