### ISSUE TITLE
Email verification not working, just keeps saying email needs to be verified after email verification says to return to matrix chat.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6544]
From a rageshake

**Comment by lampholder** [comment]
This is possibly a password reset bug.

**Comment by ara4n** [comment]
probably a facet of https://github.com/vector-im/riot-web/issues/2780.

**Comment by aheidemann** [comment]
At my tests at android, web and desktop no email was ever send at several tests with different email address to any acount, it was impossible to register an email address. 
To register a mobile number in germany worked well.

**Comment by turt2live** [comment]
The logs associated with this don't really reveal anything except that it is indeed looping. No cause is recorded, however. Is there any more information on this or anyone who has been experiencing it recently?

**Comment by ctwelve** [comment]
Hello, I have a new install at https://riot.arkmuse.org/ which is manifesting this exact error. I’ve instructed my users to register without email and add it afterwards, when they’re successfully logged in.

**Comment by jryans** [comment]
@ctwelve I'd suggest asking #riot-web:matrix.org about this, as it might be a config issue or similar.

**Comment by ctwelve** [comment]
> @ctwelve I'd suggest asking #riot-web:matrix.org about this, as it might be a config issue or similar.

I have, and they're aware of the bug. It's reproducible, but I don't know if it's just my server or specific to the client.

**Comment by novocaine** [comment]
@ctwelve are you still able to reproduce this issue?

**Comment by ctwelve** [comment]
Inconsistently, yes. Which is exactly what you want to hear of course :-/

On Aug 4, 2021, at 8:14 AM, James Salter ***@***.***> wrote:

﻿


@ctwelve are you still able to reproduce this issue?

**Comment by novocaine** [comment]
Great, next time it happens can you please provide a screenshot of the error in Element Web, and grabs of any errors you can see in the console?

**Comment by novocaine** [comment]
I think this is most likely confusion due to https://github.com/vector-im/element-web/issues/18752
