### ISSUE TITLE
Replies are padded too much

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#6579]

**Comment by lukebarnard1** [comment]
This doesn't have any actionable content, could you give more detail, @t3chguy?

**Comment by t3chguy** [comment]
Sure, its the complaint from another user that native replies take up way more space than the fallback.

 
![image](https://user-images.githubusercontent.com/2403652/39176404-a7238da4-47a4-11e8-85c7-0e1c5240a6eb.png)

**Comment by Bubu** [comment]
I was about to report a new bug, but I guess this fits here:
![image](https://user-images.githubusercontent.com/105185/82492492-94555f80-9ae6-11ea-887b-e3657721639e.png)


This is on a 1920x1200 screen, riot-desktop tiled horizontally and the right side panel expanded.
