### ISSUE TITLE
No information about the community I want to create

### ISSUE THREAD

**Issue by bluddy** [vector-im/element-web#6585]
I'm trying to create the OCaml community. When I try to create it, riot tells me the community may already exist. But I have no way to join it, or find out who started it etc. It's possible somebody just took the community name without doing anything with it. What to do?

**Comment by lukebarnard1** [comment]
Which platform are you using? Electron, web, your own build?

If you're using Electron, there isn't a way to view a community by ID (this is a design oversight which we hope to resolve). 

You can view communities on the web by browsing to https://matrix.to/#/+group_id:matrix.org, where you should be able to see the group.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
