### ISSUE TITLE
Inviting a user twice to a community breaks that community

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6589]
This feels particularly crap, and it's apparently been broken for months - i've seen two breakages of it already today.

https://github.com/matrix-org/synapse/issues/2633

**Comment by ara4n** [comment]
Also https://github.com/matrix-org/riot-web-rageshakes/issues/817 and https://github.com/matrix-org/riot-web-rageshakes/issues/818

**Comment by turt2live** [comment]
Loosely related: https://github.com/vector-im/riot-web/issues/6509

It's worth mentioning that with public groups it's possible to end up in the same situation as https://github.com/matrix-org/synapse/issues/2633 by just joining the group twice.

**Comment by lampholder** [comment]
I'm guessing that we can try to mitigate this client-side but really should be fixing it in synapse?

**Comment by Cadair** [comment]
I hit this *again* today, it's really going to break my planned deployment of matrix for a conference next week if I effectively have an open community because it randomly double joins. :cry:

**Comment by Cadair** [comment]
Also, although I can't back this up, this appeared to break more than just the single community in Riot. On my Riot instance yesterday this broke all the communities (in the LLP panel and their profiles) and on another account I couldn't load *any* community profile page at all.

**Comment by turt2live** [comment]
@Cadair that's probably more https://github.com/vector-im/riot-web/issues/6413 or https://github.com/vector-im/riot-web/issues/6592

**Comment by Cadair** [comment]
Yeah I am guessing it buggers the group store or whatever, but it's a very nasty side effect, that comes back everytime you reload the app, because so does the 500 from synapse for the room and user info for the group LLP stuff

**Comment by t3chguy** [comment]
This to be appears fixed, I could not repro (https://github.com/matrix-org/synapse/issues/2633 is closed also)

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
