### ISSUE TITLE
/ddg doesn't tell you if the request is blocked/failed/pending

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6591]

**Comment by lampholder** [comment]
How does /ddg even work? Is it an integration or a hardcoded feature in Riot web?

**Comment by turt2live** [comment]
It acts similar to autocomplete in Riot. Typing `/ddg matrix` for instance will give you an autocomplete-looking thing with results from ddg. Pressing enter will cause an "unknown command" dialog. It's part of riot.

**Comment by turt2live** [comment]
the command was removed/disabled
