### ISSUE TITLE
When you set a room to invite-only, the browseable checkbox should be greyed out!

### ISSUE THREAD

**Issue by steliosmilidonis** [vector-im/element-web#6596]
### Description

When you set a room to invite-only, the browseable checkbox should be greyed out! Right now you can set a room to invite only and have the browsable checkbox checked. This gives the impression that the room is still browsable but in fact its not.

For the web app:

- **Browser**: Chrome, Safari, Firefox

**Comment by aaronraimist** [comment]
@kylerankin why would you want rooms to show up in the directory if they are invite only? That would be a pretty bad experience for users trying to join rooms.

I think the better solution is just to disable the "Publish this room to the public in ____ room directory?" checkbox when a room isn't publicly joinable.
