### ISSUE TITLE
Received old keyshare requests after syncing for the first time in a long while

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6597]
### Description

One of my devices got turned on for the first time in several months and finished a sync (after a couple hours of trying, but that's an issue due to the size of my account). When it finally finished I had t oclick through several dialogs from my other devices requesting keys. These dialogs were already responded to on yet another device, so surely I shouldn't be getting them here?

### Steps to reproduce

- Setup 3 devices to sync with your account
- Turn off "device 1" (or stop syncing, whatever)
- Encounter a situation where "device 2" needs to request keys from other devices
- Respond to the prompt on "device 3"
- Start syncing again on "device 1"
- See the prompt for keys again :(

Log: sent (referencing this issue, may be several hours old however due to lack of time to report this)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
I asked @richvdh about whether this was expected based on the current impl; this is what he had to say:

> it's kinda expected
> the client which sent the keyshare requests will send cancellations when it gets the keys
> but there might be lots of to-device messages waiting for device 1
> which includes the original keyshare requests and the cancellations
> which means that there may be windows where device 1 has seen a request but not the cancellation

Which goes some way to explaining _why_ this might be happening. The end effect is certainly undesirable, though (so there is certainly a bug in the management of these keyshare request popups)

**Comment by richvdh** [comment]
(ideally we need a proper way to cancel the keyshare request messages)

**Comment by turt2live** [comment]
keyshare dialogs aren't a thing anymore
