### ISSUE TITLE
Joining large rooms takes forever (and never suceeds)

### ISSUE THREAD

**Issue by schmittlauch** [vector-im/element-web#6619]
### Description

When trying to join certain rooms – I suspect the issue are especially big rooms (many users/ many messages) – they are never joined successfully, the spinner is displayed forever

### Steps to reproduce

- try to join a big room (reproduced with `#riot:matrix.org` and `#e2e:matrix.org`)
- join the room by clicking the *Click here to join the room*
- wait and watch the spinner graphics rotate
- after 10 minutes you still havent't joined the room

Log: sent, referencing this issue's URL

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 59.0.2
- **OS**: Gentoo Linux amd64
- **URL**: riot.im/app

**Comment by schmittlauch** [comment]
Update: After an hour or so, I can now read the current messages in `#riot:matrix.org` and get notifications for it. The room is categorized under *Archive*.
But room interactions are still deactivated, I clicked the *join* link again and am still watching the spinner animation.

**Comment by schmittlauch** [comment]
Update 2: When logging in with Riot mobile Android, I' have properly joined the rooms. But back in Riot Web I'm still stuck in the previous mode, but getting live notifications as described above.

**Comment by lampholder** [comment]
Hi @schmittlauch - thanks for reporting; this sounds very annoying.

Can you confirm the exact sequence of events? Do you know how #riot:matrix.org ended up in _Archive_ (aka _Historical_)? Did it go straight there after you tried to join? Had you previously been in #riot but left?

Thanks!

**Comment by lampholder** [comment]
For the record I suspect we might have at least two bugs here - the (known) issue that joining large rooms can be slow (especially over federation) and a separate issue that a room that appears to be in Historical/Archiv can still generate notifications.

**Comment by schmittlauch** [comment]
I indeed had joined the room before, so it was still present in the *Archive* section. But I just noticed that, after deleting the room from the *Archive*, it reappears there as soon as you select the room and end up in the room preview before joining.

Right now I can't reproduce the issue anymore.
