### ISSUE TITLE
Sketch exports SVGs pretty printed. We could add a compilation step to strip the formatting.

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#662]

**Comment by ara4n** [comment]
(heads up that I'm relying on them being pretty-printed in source control, as i've been hand-sculpting tweaks to the SVG XML.  agreed it'd be nice if we squonsched them up during compilation though, but hardly a big issue given they're tiny anyway.  even nicer might be to work out how to magically inline them into the HTML and get rid of all the unperformant <object/> tags.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16856
