### ISSUE TITLE
Direct Message metadata can get out of sync with who is actually in the room... with bad results.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6626]

**Comment by lukebarnard1** [comment]
This is the whole "Direct messages are flaky" fiasco. It's likely that the room is listed in you account data as a direct message for isobelle despite her not being in there.

**Comment by lampholder** [comment]
I couldn't find another issue for this, so I'll leave this here for now. Title edited to be more suitable.

**Comment by yannicka** [comment]
Is this still the case?

**Comment by turt2live** [comment]
Without a description of what "bad results" are, closing. If people have further information, please open a new issue.
