### ISSUE TITLE
Can not see messages from IRC nick with underscore

### ISSUE THREAD

**Issue by axyd** [vector-im/element-web#6628]
### Description
The messages from IRC names with underscores are not received.

### Steps to reproduce
  - Example nick:  qwerty_ 
  - When qwerty_ sends a message, riot.im users can not see the message

### Version information
- **Platform**: desktop app
- **OS**: Windows
- **Version**: 
  - riot-web version: 0.14.1
  - olm version: 2.2.1

**Comment by t3chguy** [comment]
Not enough information to do anything with but sounds like an issue for https://github.com/matrix-org/matrix-appservice-irc
