### ISSUE TITLE
Switch to using sandboxed iframes for displaying attachments

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6639]
https://github.com/matrix-org/matrix-react-sdk/pull/1864 switches us from using data URIs to blobs for displaying e2e attachments (to fix vector-im/riot-web#2678, vector-im/riot-web#2866).

However, a much more robust solution would be to display them as object URLs within a sandboxed iframe - the same trick as proposed in https://github.com/vector-im/riot-web/issues/6173 for rendering secure download links.

**Comment by turt2live** [comment]
We've since introduced yet another way of doing this
