### ISSUE TITLE
Firefox logs me out on every restart

### ISSUE THREAD

**Issue by ildar** [vector-im/element-web#6659]
### Description

... and creates a new device in device list. AFAIK this isn't a normal case.

### Steps to reproduce

Logs are following

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 59.0.2
- **OS**: Linux x86_64
- **URL**: riot.im/app

**Comment by kannes** [comment]
Does it do so if you disable all your addons?

**Comment by t3chguy** [comment]
> ... and creates a new device in device list. AFAIK this isn't a normal case.

each time you log in thats a new device as its impossible to track you between devices.

Do you have clear cookies on close or similar enabled, or it could be one of your addons?

**Comment by TZer0** [comment]
I have this issue on web riot too on two different platforms.

Close browser -> have to log in again, new keys

System nr 1:
OS: Linux Mint 18.3 x86_64
Browser: Firefox 61.0.1 (64-bit)

Tested with all addons-disabled.

System nr 2:
OS: Win 10
Browser (probably, I'll double-check later if important): Firefox 61.0.2 (64-bit)

The issue seems to lie with this setting and riot's interaction with it:
![screenshot](https://i.imgur.com/PDPGYUy.png)

Once I added the domain I'm chatting from to my exceptions this stopped happening.

**Comment by jryans** [comment]
It sounds like all users here have Firefox configured (either through preferences or add-ons) to remove site data. Riot uses various forms of browser storage to know that you are logged in and which device you are using, so for the best experience, you may want to allow storage to persist across browser restarts.

**Comment by aaronraimist** [comment]
@TZer0 Yeah, you can't have Firefox set like that. Riot needs that stuff so you would need to make an exception for Riot.

**Comment by ildar** [comment]
@jryans , no, I had this problem while all sites data set to remain.

**Comment by ildar** [comment]
Just tested and see that Element-web inherits this problem.

On Sun, May 6, 2018 at 5:36 PM Michael Telatynski ***@***.***) wrote:

> ... and creates a new device in device list. AFAIK this isn't a normal
> case.
>
> each time you log in thats a new device as its impossible to track you
> between devices.
>
> Do you have clear cookies on close or similar enabled, or it could be one
> of your addons?
>
No.
Sorry, missed this question.

**Comment by kittykat** [comment]
@ildar Can you confirm that you still have the issue with Firefox 92.0 with default settings and no extensions or plugins, using app.element.io?

I will close this issue for now as it's against a very old version of Firefox, please respond with @kittykat in your reply if you're still seeing the issue and I will reopen it for you.
