### ISSUE TITLE
Collapsable replies to long messages

### ISSUE THREAD

**Issue by rkfg** [vector-im/element-web#6692]
I see that replies in riot.im/develop/ quote the whole message which might be quite long (multiple lines or a long story). I didn't find any issues about this so posting one. It could be a simple expand/collapse button like the one for spoilers on forums, by default it could display the first 10 words or 100 characters (whichever is bigger) and the user can expand the whole message by clicking a button or ellipsis in the end. That would save the screen space greatly.

**Comment by t3chguy** [comment]
This surely applies to all long messages?

**Comment by turt2live** [comment]
it does, but it's particularly annoying if someone posts an entire essay, then 8 people reply to it with 'looks good!'.

**Comment by rkfg** [comment]
Yes, I think clients should be able to _optionally_ autocollapse all long messages, not just replies. It could be nice to have adjustable exceptions. For example, I'd like the messages from a particular bot to always appear in full because it sends them after an explicit request and I know I want to read the whole message. OTOH, I'm not so sure this applies to other regular users so I'd like their messages be collapsed by default.

**Comment by turt2live** [comment]
Collapsible messages in general are https://github.com/vector-im/riot-web/issues/4388 btw

Maybe the solution for replies is to truncate the original message at some point.

**Comment by rkfg** [comment]
Sadly, it's almost a year old and P4 which doesn't look encouraging. And the feature is relatively simple to implement at the same time. But I agree that it's not that important by itself while the quotes in replies must be collapsable or else they wouldn't be of much use.

**Comment by ara4n** [comment]
it'd be pretty trivial to collapse the quoted portion via CSS, which sounds like it'd be good enough for this (and probably handle collapsible messages a la #4388 at the same time)

**Comment by rkfg** [comment]
Celebrating the first anniversary of this issue! :tada: As I said before, the fix is trivial at least for Chrome:
```css
.mx_EventTile_reply {
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```
I use this via Stylus extension in web Riot but it's not trivial in the desktop version. I wish there was a userstyle feature in the client so I could attach my own styles there.

**Comment by pedro-nonfree** [comment]
very annoying, let me add an example to ilustrate it

this first what you expect in a chat, send and receive [1]

and this is the *reply in long messages*, all the screen is filled with the content of a previous message that you might read before (and I still don't know what's the response itself!! Then I have to scroll down) [2]. But when I scrolled down, there is a small message, and I lost the previous context.

I think this proposal applies here very well too https://github.com/vector-im/riot- web/issues/4388#issuecomment-619257146  collapse (*read more*) if the reply message takes more than 1/3 of the screen

[1] 

![image](https://user-images.githubusercontent.com/39959198/80260698-c65ed780-8688-11ea-9267-a1d1a30d3c63.png)

[2]

![image](https://user-images.githubusercontent.com/39959198/80260768-ed1d0e00-8688-11ea-9f37-d2d78371713c.png)

**Comment by SimonBrandner** [comment]
Related: [#4388](https://github.com/vector-im/element-web/issues/4388)
