### ISSUE TITLE
URL previews don't wrap

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6693]
### Description

![image](https://user-images.githubusercontent.com/1190097/39837703-77e0632c-5394-11e8-95b6-dffe5fac05c2.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by rkfg** [comment]
Same on riot android btw.

**Comment by turt2live** [comment]
If the issue happens on riot-android, a sister issue on https://github.com/vector-im/riot-android would likely be appreciated by the team (if one doesn't already exist).

**Comment by MadLittleMods** [comment]
Constrained URL previews seem to have ellipsis nowadays at least.

![](https://user-images.githubusercontent.com/558581/134752762-c2813be2-ec6b-492c-8f5c-78b5b9e8ed09.png)
