### ISSUE TITLE
Do not automatically download large media in encrypted rooms

### ISSUE THREAD

**Issue by gloomy-ghost** [vector-im/element-web#6710]
### Description
It didn't appear like an issue for me at first, as I'm on an unlimited boardband plan. Until I shared ~10 videos in my group...

### Steps to reproduce
- Share videos
- Close tab
- Restore tab
- Videos are downloaded automatically with no way to stop it. In my case it literally costs ~1GiB (!) every time I reload the tab. It's really a waste of bandwidth, for both client and server. Also the interface gets constantly updated as the videos complete loading, which renders it unusable until the loading is finished.

Describe how what happens differs from what you expected.
Large media should not be automatically downloaded. Thumbnails plus streaming should do the trick.

Log: not sent
![default](https://user-images.githubusercontent.com/13086421/39957074-a0c734b0-5640-11e8-8ee0-19ade869c12c.png)

### Version information
- **Platform**: web

For the web app:

- **Browser**:  Firefox 61b3
- **OS**: Windows
- **URL**: https://riot.im/app/

**Comment by lampholder** [comment]
I haven't had a chance to verify this, but it sounds like very annoying behaviour.

@gloomy-ghost do you know how this is affected if you disable `autoplay gifs and videos` in user settings? Does Riot still download the videos even without playing them?

**Comment by gloomy-ghost** [comment]
yes this is affected even with autoplay disabled

**Comment by cuongnv** [comment]
Any update with current version of RIOT ?

**Comment by jryans** [comment]
If there's an update, it will find it's way here.

**Comment by MatthewCroughan** [comment]
A friend who lives in Florida with RFC2549 style speeds can confirm this is an issue that needs a solution, otherwise he cannot use the client.

**Comment by Half-Shot** [comment]
This is limited to encrypted rooms. In an unencrypted room, the media url is passed straight to the <video> element and so the browser controls the download behavior (through `preload=`). We set this to none for thumbnailed videos, so I'm going to say it's mostly not a problem.

For encrypted rooms however we download and decrypt the file ahead of time, and pass a blob url to the video handler. This isn't strictly required to make the video tags work, so I'm going to work on a little PR to only download the video once play is clicked (unless autoplay is set)
