### ISSUE TITLE
electron app renders white

### ISSUE THREAD

**Issue by plus13** [vector-im/element-web#6711]
Hi,

this problem now persists for a few month and I already tried all suggestions I could find.
I was using riot-desktop (eletron version of riot, all last versions) under Archlinux with AwesomeWM for quite a while until the whole electron app turned itself blank. Look at:

[https://img.vim-cn.com/c9/83da992ac183ae13fa959ad97d997d90321868.jpg](https://img.vim-cn.com/c9/83da992ac183ae13fa959ad97d997d90321868.jpg)

If I now click on the white window and drag the content I can see it within the drag animation:

[https://img.vim-cn.com/0e/325168b789c2bf82cf81df82257ea69aa66e96.jpg](https://img.vim-cn.com/0e/325168b789c2bf82cf81df82257ea69aa66e96.jpg)

When I stop dragging it's all white again. I am not able to resolve this problem even though I tried to proceed similar like this one:

https://www.christianengvall.se/electron-white-screen-app-startup/

I cannot get my way through the logs-button in the settings menu, but when I start riot-desktop from a terminal I get the following of which I believe that's not causing the problem:

```
$ riot-deskop
Starting auto update with base URL: null
Auto update not supported on this platform
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```

Kind regards

**Comment by t3chguy** [comment]
Does this happen to other electron based apps? Sadly riot can't do much about how electron renders stuff, the libGL errors **DO** seem related.

**Comment by plus13** [comment]
@t3chguy 
No, this does not happen to other electron based apps.
I think the cause might lay in how riot in implemented in electron. I also tried to play with files like this /usr/share/webapps/riot/index.html , which has a `<meta name="theme-color" content="#ffffff">` section:

[https://www.cryptob.in/19PCdj6Hzpz/#!/T-0o2wFhQn9Yi2ndBbJYMOrhoczO17FNjkHP7DCbebg](https://www.cryptob.in/19PCdj6Hzpz/#!/T-0o2wFhQn9Yi2ndBbJYMOrhoczO17FNjkHP7DCbebg)

I vaguely remember that the libGL errors appeared already while riot-desktop was working a few month ago.

**Comment by t3chguy** [comment]
`theme-color` is not something electron utilizes, it is primarily for mobile web browsers.

**Comment by t3chguy** [comment]
Riot simply uses electron as a chromium web browser, the rendering error might be down to the version of electron or whatever

**Comment by plus13** [comment]
But why is it than working with other applications than riot-desktop?

**Comment by t3chguy** [comment]
potentially different versions of electron and an electron bug

**Comment by lampholder** [comment]
P2 only because it doesn't seem to be affecting a lot of people (sorry @plus13)

**Comment by TheJJ** [comment]
The issue was fixed for me after I updated (Archlinux) and rebooted the machine (the nvidia driver was among the updates). `riot-desktop` was not updated and is still `0.15.4-1`.

**Comment by DC7IA** [comment]
I had the same behaviour. Killing, but not closing, the client solved it for now.

**Comment by kittykat** [comment]
I'm closing this issue as it hasn't had any new reports recently and seems to have been fixed by updating to newer versions (see also #12903

Please feel welcome to reopen if it still persists
