### ISSUE TITLE
Can't forward stickers to other rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6725]
### Description

The context menu option is missing

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/cd6d18cf-e835-4049-87e3-69f9a3070068)

This got fixed
