### ISSUE TITLE
E2E messages get stuck

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#6729]
Twice today I've experienced:
- returning to riot after a period of inactivty
- trying to send a message in an E2E room
    - message is grey and pending send
- repeat in a few E2E rooms
    - all messages stay grey and pending
- send a message in a non-E2E room
    - message sends right away and seems to 'push through' the pending E2E messages

On riot/develop today on my macbook air chrome  66.0.3359.139

**Comment by lampholder** [comment]
Still only anecdotal - leaving here incase anyone else/I experience it again

**Comment by ara4n** [comment]
without logs this is useless, plus haven't seen it forever.
