### ISSUE TITLE
URL preview settings in the room are just confusing

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6736]
![image](https://user-images.githubusercontent.com/1190097/40073514-42218ac8-5834-11e8-87e8-ece74bfd5c86.png)

Reading this as a user the 3 lines read something like this mentally:
* Okay great, I have them enabled
* Oh, but they are disabled because I'm in this room?
* But there's this checkbox that tells me they are enabled

Evidently they are enabled in the room because the user would see previews, however this particular section of the room settings is needlessly complicated. 

Some efforts to improve it were done as part of granular settings to try and convey the different levels, although I seriously wonder if it helped at all. The old approach is just as bad in my opinion.

**Comment by lampholder** [comment]
Yes, this is very unclear :(

This could largely be improved with better words, but at the core is the confusing question - _if I have chosen to have URL previews on by default for **my account** but the room admin has chosen to have URL previews off by default for **their room**, who wins?

We certainly need to represent the truth more clearly here.

**Comment by axelsimon** [comment]
Maybe use a "general ➡ specific" logic:
Start with the general case: "URL previews are disabled by default for participants in this room."
Then confirm to the user's general case: "You have *enabled* URL previews by default."
Then the tick box: "☑ Enable URL previews for this room (affects only you)"

This last line could probably benefit from a mention of the fact it's a setting to override the user's general setting:
> You can override this behaviour for this specific room 

I'm wondering if also saying "__However,__ you have *enabled* URL previews by default" could also help.

**Comment by turt2live** [comment]
The issue also becomes communicating the 3 possible states for each of those options. In the screenshot, 2 of them are using the default settings for the level which adds to the confusion of whether or not previews should be disabled. For instance, it says that previews are *disabled* for participants of the room, however in truth the value is *undefined* for participants of the room which causes the app to consider other levels instead.

**Comment by MadLittleMods** [comment]
This looks to be updated now and seems more clear ⏩

**Room settings** -> **General** -> **URL Previews**

> **URL Previews**
> 
> When someone puts a URL in their message, a URL preview can be shown to give more information about that link such as the title, description, and an image from the website.
> 
> In encrypted rooms, like this one, URL previews are disabled by default to ensure that your homeserver (where the previews are generated) cannot gather information about links you see in this room.
> 
> Enable URL previews for this room (only affects you) [x]

![](https://user-images.githubusercontent.com/558581/134748780-cd1fe0bf-a63b-42ae-99bf-a77a5636c6cb.png)
