### ISSUE TITLE
replace ugly spinners with http://tobiasahlin.com/spinkit/

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6740]
shamelessly stealing from travis & dimension :D'

**Comment by lampholder** [comment]
We show a lot of spinners; it _is_ a shame the one we have is so ugly :P

**Comment by t3chguy** [comment]
Using spinkit seems like it'll become messy as it means manually sizing stuff unless we have a consistent size between all our spinners (not the case)
http://better-react-spinkit.benjamintatum.com/ lets us around this very easily so picking one of those is trivial.

**Comment by t3chguy** [comment]
if we want fallback for browsers which don't support css animations we need to update the Modernizr baked into riot-web

**Comment by nadonomy** [comment]
Closing given https://github.com/matrix-org/matrix-react-sdk/pull/5680.

**Comment by t3chguy** [comment]
That hasn't landed yet though, this would have auto-closed when it merged.
