### ISSUE TITLE
e2e image placeholder spinner is wrong size causing scroll jumps

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#6742]
This is a fairly easy fix: the placeholder for e2e images while they're decrypted is just a plan spinner, so when the image loads, the tile gets bigger and all the messages shift around.

This should be an easy fix: we just need to show the spinner in the middle of a correctly sized placeholder box instead (since the message contains display size hints).

**Comment by kittykat** [comment]
The images are now loaded as a blurred thumbnail in the right size, I believe, so I'm going to close this issue for now (please reopen if it's still valid)
