### ISSUE TITLE
noisy notifications in e2e rooms

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/element-web#6745]
I have noisy notifications turned off.

riot-web 0.15.0 (also with 0.14.2)
chromium 66.0.3359.139

**Comment by lampholder** [comment]
But... are you still getting them? Is that the bug?

**Comment by 4nd3r** [comment]
yes.

my notification settings:

![image](https://user-images.githubusercontent.com/7166727/40714977-c9967692-640c-11e8-81af-a024283c1551.png)

for both chats (regular and e2e):

![image](https://user-images.githubusercontent.com/7166727/40715018-e85412b0-640c-11e8-86c5-b7180c2821d1.png)

when i send message from test account to regular chat, i get only desktop notification as configured.

when i send message from test account to e2e chat, i get noisy desktop notification.

**Comment by lampholder** [comment]
Confirmed - notifs in the e2e room are playing the notif sound even though noisy notifs are not enabled.

**Comment by kittykat** [comment]
I am going to close this issue for now as we cannot reproduce it. Please comment with @kittykat if you are still experiencing the problem and I will re-open the issue.
