### ISSUE TITLE
Reply thread automatically collapses when switching from in flight to sent

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6746]
### Description

This is more of a minor annoyance than anything.

### Steps to reproduce

* Have a really slow homeserver
* Type out a reply to a message such that it creates a chain
* While the message is sending, expand the previous messages (click "in reply to")
* Be sad when your message flips to sent and your thread gets collapsed on you

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 66
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
This will be a PITA to fix :(

**Comment by turt2live** [comment]
I'd say it's safe to put it at p4 minor - it's disappointing to see the thread go away, but realistically it's not the end of the world. Of course, someone may have other thoughts.

**Comment by t3chguy** [comment]
To explain why this happens, the EventTile must be getting remounted instead of just updating and thus a new ReplyThread is mounted. Maybe some React magic can see that if the underlying Event goes from local-echo to remote-echo we can skip this remount

**Comment by t3chguy** [comment]
This got fixed
