### ISSUE TITLE
<mx-reply/> blocks which trigger highlights should be highlighted

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6747]

**Comment by t3chguy** [comment]
because ![](https://riot.ovh/_matrix/media/v1/download/matrix.org/VAQdAzPxaJLNNSjVZxJEUULx) is a little jarring

**Comment by ara4n** [comment]
The problem is probably more that the highlight (Matthew) should be highlit rather than mx-reply blocks being excluded, in retrospect.

The quickest solution is probably to just make the whole thing red.

**Comment by t3chguy** [comment]
the mx-reply fallback is going away as per the spec change
