### ISSUE TITLE
Room directory is irresponsibly ignoring multiple results from a thirdparty location request and joining the first result

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#6768]
### Description

When hitting enter or clicking join room after selecting a network from a protocol, we will do a request for all matching location**S** but will just join the first result if it exists. Given that almost every search result is going to return multiple results, hitting enter should at least give you a preview of the results.

https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/structures/RoomDirectory.js#L326

### Version information

All versions

**Comment by lampholder** [comment]
Sorry @Half-Shot I don't quite understand the flow yet - can you make a gif or describe it more simply?

I tried to reproduce by going to the room directory, choosing '#Freenode' from the dropdown and pressing enter, but nothing happened :P

**Comment by lampholder** [comment]
Thanks for the explanation! I've triaged as P2 due to it's being _relatively_ unlikely to occur, though if I'm wrong in that assessment please shout up.

**Comment by Half-Shot** [comment]
Sure, it's a personal gripe that I'll probably end up fixing anyway :laughing:

**Comment by robintown** [comment]
My understanding is that we can call this "fixed" since the new room directory doesn't even support third-party location requests anymore. I see no references to `MatrixClient.getThirdpartyLocation` at all.
