### ISSUE TITLE
Resize widget area height in room via Riot interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-web#6785]
Riot interface have fixed height of widget area in room, that sometimes is not comfortable. Will be good to have ability for resize height of widgets via mouse drag&drop. Can't find older issue about this, so post new.

**Comment by lampholder** [comment]
Yeah, I'm surprised we didn't already have an issue for this - this is certainly something that's been discussed for widgets, and is a good idea.

**Comment by delandtj** [comment]
is there any status update on that ?
Thankz

**Comment by MurzNN** [comment]
![image](https://user-images.githubusercontent.com/336662/52562704-6a57bc80-2e10-11e9-91b0-004421ec300d.png)
Here is screenshot with example of any popup window in Riot Jitsi widget at 1366 x 768 resolution (notebook) - it have only one line of text in content area :(

**Comment by wilkie** [comment]
I'm able to resize the iframe and container divs with dev tools and the widgets seem to handle it fine. Is there a particular challenge I am not aware of for this feature?

**Comment by MurzNN** [comment]
Without resize feature users can't select "View full screen" menuitem in Jitsi widget:
![изображение](https://user-images.githubusercontent.com/336662/77577055-35f57180-6ee7-11ea-9c07-43d000d5b56f.png)

Here is same menu in meet.jit.si webpage:
![изображение](https://user-images.githubusercontent.com/336662/77577251-7e149400-6ee7-11ea-9374-69b9195f629a.png)

**Comment by dwehrmann** [comment]
I also think that this should be updated. Is there any update to this issue or is there any entry point to fix this?

**Comment by passw0rd123** [comment]
The Jitsi widget should really be bigger by default. If there are more than two participants its really hard to use it without opening jitsi in a new window. Maybe it should default to the size of the Video Call window and stick to the sides aswell (even if the user list is not shown) but be adjustable in height.

Additionally for the **Desktop App** there should be a **fullscreen-mode** for the widget, so you don't have to switch to the Browser to use jitsi fullscreen and  be forced to leave the App.

<img width="569" alt="bigger-jitsi-widget" src="https://user-images.githubusercontent.com/16052268/79692675-c9ac2a80-8266-11ea-99bf-185ba4e20753.png">
.
