### ISSUE TITLE
add doc about granular settings to the README

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6791]
e.g. that   settingDefaults: {
TagPanel.disableTagPanel: true
}
is a thing

**Comment by tulir** [comment]
Keywords: default settings config.json

(I only found this issue because it had the exact setting I wanted to change)

**Comment by jryans** [comment]
Closing this and using #7174 instead, which is a bit easier to search for and has more details.

**Comment by ara4n** [comment]
this still isn't documented.

**Comment by turt2live** [comment]
it is now
