### ISSUE TITLE
Unable to add #e2e-dev:matrix.org to +community:matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6823]
<img width="761" alt="screen shot 2018-05-29 at 23 53 00" src="https://user-images.githubusercontent.com/1294269/40689748-7ec40038-639b-11e8-9743-8ee6c25a9f9a.png">

**Comment by lukebarnard1** [comment]
I can't reproduce this on a test room on my own server.

**Comment by p1otr** [comment]
I have the same problem. matrix-client.matrix.org server responds to Riot's request with: `{"errcode":"M_UNKNOWN","error":"Internal server error"}`
 (PUT gets status code: 500)

**Comment by t3chguy** [comment]
This is a matrix.org failure.

**Comment by p1otr** [comment]
I already sent them an email with a trace in HAL file, but the internal server error might be caused by invalid request too (just saying ;)

**Comment by piqueza** [comment]
Adding my comment to confirm that I cannot create a room in a community. The behavior I see is that when I created the room in the community, the room appears under my own rooms, and the community has no rooms added. Using Riot Linux Desktop App and Matrix-Synapse-Py3 on Ubuntu 20.04

**Comment by t3chguy** [comment]
@piqueza you are misunderstanding communities.

You cannot create a room in a community. You create a room, in 0 communities, then you add it to as many or few communities as you desire. A room is not limited to one community.

![image](https://user-images.githubusercontent.com/2403652/81401104-7ff88680-9126-11ea-8b32-aed44a9f9da7.png)

See `Add rooms to this community button`

**Comment by piqueza** [comment]
@Techguy ok fair enough, trying to add a room to a communit also fails though. Similar failure as in some of the linked issues. Is this the right thread to discuss that or should I continue in those threads?

**Comment by t3chguy** [comment]
Seems like only adding a room by its ID is working at present, the communities implementation is due a redesign and communities on matrix.org server have a lot of issues.

**Comment by piqueza** [comment]
Thank you. OK I'll leave it be for now not to add a lot of noise to the signal out there already. Do you know where I can subscribe to notifications for updates that I can test in our lab here? Appreciate your help.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
