### ISSUE TITLE
Notification level config in context menu is still very flakey

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#6828]
Changing the notif level from the context menu of the room list has been quite flakey but lately it's got even worse. I'm getting noisy notifs on rooms set to 'mentions only' or 'all messages'. On a room with 'all messages' if I set to 'noisy' then come back later, the cursor is back to 'all messages' (might be server slowness?). Basically changing the setting doesn't seem to have much effect in some rooms. It's not reproducible on every room, I suspect it's linked to when I did change the setting and whether I did it on mobile or web, but it's *really* annoying.

**Comment by z3ntu** [comment]
For me it's the other way around. Many rooms I'm in have the level set to "All messages" by default but the behavior is as it were "Mentions only".
