### ISSUE TITLE
sticker picker is empty

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#6853]
looks like something specific to me. I refreshed Riot several times, I updated chrome and relaunched it, and I still have it. the Console logs are:

![image](https://user-images.githubusercontent.com/8582858/41154797-39673a08-6b13-11e8-89b2-280cdcc89b62.png)

**Comment by AmandineLP** [comment]
Thanks @rxl881 for the steps, unfortunately it didn't change anything :(

**Comment by lukebarnard1** [comment]
I think this got fixed. @AmandineLP are you still experiencing issues?

**Comment by PureTryOut** [comment]
I'm having almost the same problem, although for me it says it's forbidden...

![screenshot_20180615_000447](https://user-images.githubusercontent.com/1565836/42055820-92c09080-7b18-11e8-9c91-5f92f16c3d68.png)

And yes this is still happening right now.

**Comment by mpnordland** [comment]
I'm seeing the same as @PureTryOut, When I look in the browser dev tools, I see it's pulling from https://scalar-staging.riot.im/scalar/api/widgets/id/<redacted>/stickers.html?widgetId=<redacted>&parentUrl=<redacted>. That url returns 403.

**Comment by mpnordland** [comment]
@rxl881 's solution worked for me.

**Comment by superjey** [comment]
hello.
when i want add a sticker with my own homeserver i have this image .
![riot](https://user-images.githubusercontent.com/1514922/53830517-eb732100-3f82-11e9-943e-062e4b72a549.png)

**Comment by Jaedotmoe** [comment]
Hey, still stuck with this bug.
Even when clearing `m.widgets` with the dev tools, the bug persists.
![image](https://user-images.githubusercontent.com/76598503/103142648-e1498600-4706-11eb-82ac-6805753bd718.png)
I am using the desktop Element client on my own homeserver (matrix.jae.moe).
In the console, I can see an output like this:
```
[Dimension] Received toWidget request at widget ID dimension-stickerpicker-1608934322743: {"api":"toWidget","widgetId":"dimension-stickerpicker-1608934322743","requestId":"widgetapi-1608934534718","action":"openid_credentials","data":{"state":"allowed","original_request_id":"[secret]","access_token":"[secret]","token_type":"Bearer","matrix_server_name":"jae.moe","expires_in":3600}}
```
Which makes me believe some kind of configuration is needed on the side of Synapse.
Any ideas?

**Comment by jryans** [comment]
This old issue is a mishmash of unrelated and possibly solved problems, so I'm going to close this. Please file a new issue for your specific case if you are still having trouble here.
