### ISSUE TITLE
e2e room has no timeline (indexeddb full, error handling incomplete)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6879]
![image](https://user-images.githubusercontent.com/1190097/41445996-4ece254a-700a-11e8-8964-954f802b8b29.png)

Error from the console (repeated several times):
```
rageshake.js:66 Error decrypting event (id=$1527REDACTEDHbo:matrix.org): TypeError: Cannot read property 'message' of undefined
    at MegolmDecryption._callee4$ (megolm.js:638)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(/develop/anonymous function) [as throw] (https://riot.im/develop/bundles/59c5a97589583c924c54/bundle.js:260369:22)
    at Generator.tryCatcher (util.js:16)
    at PromiseSpawn._promiseRejected (generators.js:107)
    at Promise._settlePromise (promise.js:576)
    at Promise._settlePromise0 (promise.js:614)
    at Promise._settlePromises (promise.js:689)
    at Async._drainQueue (async.js:133)
    at Async._drainQueues (async.js:143)
    at Async.drainQueues (async.js:17)
    at run (es6.promise.js:75)
    at es6.promise.js:92
    at MutationObserver.flush (_microtask.js:18)
```

**Comment by turt2live** [comment]
The megolm test room has a similar fate:
![image](https://user-images.githubusercontent.com/1190097/41446045-8f0b0f74-700a-11e8-8719-f9339a1916ad.png)

**Comment by dbkr** [comment]
Looks like something is throwing `undefined` here. If you open chrome dev tools and brea on exceptions, you may be able to see what's throwing it.

**Comment by turt2live** [comment]
Windows restarted, causing Riot to update/refresh. I've now lost the ability to reproduce this :(

Closing due to being unable to reproduce. Will re-open if it happens again.

**Comment by turt2live** [comment]
I got this again. The issue at hand is indexeddb being full, again: #6120 

I'm reopening it as "please fix the error so it fails semi-gracefully". Previously, the messages would show up as "Cannot decrypt: encryption not enabled" (as per #6120), but blank is a new failure mode. 

The particular code block throwing the exception is:
```
try {
        res = await this._olmDevice.decryptGroupMessage(
            event.getRoomId(), content.sender_key, content.session_id, content.ciphertext,
            event.getId(), event.getTs(),
        );
    } catch (e) {
        if (e.message === 'OLM.UNKNOWN_MESSAGE_INDEX') {
            this._requestKeysForEvent(event);
        }
        throw new base.DecryptionError(
            e.toString(), {
                session: content.sender_key + '|' + content.session_id,
            },
        );
    }
```

In particular, it's mad about `e.message` being used in the `catch`. As expected, `e` is in fact undefined.

**Comment by lukebarnard1** [comment]
The offending code is:
https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/store/indexeddb-crypto-store.js#L85-L87

MDN doesn't say anything about `event.target.error` but does claim that `event.target.errorCode` is a thing: https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/store/indexeddb-crypto-store.js#L85-L87

**Comment by richvdh** [comment]
Given that this hasn't seen much attention in over 4 years, I wonder if it's still a thing, or if it's better covered by things like https://github.com/vector-im/element-web/issues/14174.

**Comment by turt2live** [comment]
I'm inclined to believe the error handling side is fixed, though the underlying cause is still problematic. If there's a more useful tracking issue, let's use that one.
