### ISSUE TITLE
Videos can expand to massive sizes if dimensions are zero

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6881]
Event (redacted for privacy):
```
{
  "origin_server_ts": 1529077392256,
  "sender": "@redacted:matrix.org",
  "event_id": "$1529...KmaO:matrix.org",
  "unsigned": {
    "age": 9619
  },
  "content": {
    "body": "redacted.mov",
    "info": {
      "mimetype": "video/quicktime",
      "thumbnail_info": {
        "mimetype": "",
        "h": 0,
        "w": 0,
        "size": 0
      },
      "h": 0,
      "thumbnail_url": "",
      "w": 0,
      "duration": 0,
      "size": 31788779
    },
    "msgtype": "m.video",
    "url": "mxc://matrix.org/StbgzQeZPW..."
  },
  "type": "m.room.message",
  "room_id": "!FPU...:matrix.org"
}
```

Result (blurred for privacy):
![image](https://user-images.githubusercontent.com/1190097/41477818-bf38c042-7082-11e8-8712-4e75e7c73e70.png)

**Comment by lukebarnard1** [comment]
So seemingly, we need to use `videoWidth` and `.videoHeight` once the video is loaded. 

We should handle `info` being present but values being set to `0`.

Perhaps if the ratio in `info` is not < 1.0 and > 0.0, we should just default to `naturalXXX`.

**Comment by turt2live** [comment]
Brief testing shows that this also applies to negatives, so capping between 0..1 seems like a good plan.

A 1x1 video renders as expected: a single pixel.

**Comment by ara4n** [comment]
just tested this with current thumbnailing logic and it seems to be okay.
