### ISSUE TITLE
Clicking "Link to most recent message" in share dialog over and over causes the matrix logo to flicker

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6887]
I'd say this is extremely minor, but it is distracting. The logo flickers *after* the QR code has been generated. 

Having the logo remain static (not flickering) would give a smoother experience, although minor.

**Comment by t3chguy** [comment]
to fix this would require to modify the underlying library which is something toml wants to avoid doing at this time. It is the thing that adds it onto the canvas :(

**Comment by turt2live** [comment]
> ***extremely minor***

Honestly, if this got a `p10` label I wouldn't be sad. It's a little distracting, but not really worth the effort to investigate or fix in my opinion. Just lodging the bug now before I forget :p

**Comment by t3chguy** [comment]
it annoys me more than that :P

**Comment by robintown** [comment]
Pretty sure this can be closed since there doesn't seem to be a Matrix logo overlay any more
