### ISSUE TITLE
It's easy to forget which room you're sharing from Riot (due to lack of URL previews on matrix.to links)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6888]
## Description
Having tested the share options, Twitter, Reddit, and Email all show you the actual link. Facebook and LinkedIn are different stories though:

![image](https://user-images.githubusercontent.com/1190097/41500567-5ba00d4a-7151-11e8-90b2-8774d66b756f.png)

![image](https://user-images.githubusercontent.com/1190097/41500570-643de3be-7151-11e8-857b-7f8a9578ee1a.png)

**Comment by turt2live** [comment]
Also affects the QR code to some degree, although in theory you'd have enough visual context from looking at the room in the background.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/7870
