### ISSUE TITLE
slate weird autocomplete

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#6891]
`/dev` in HQ in Draft completes to /dev/ponies, in Slate it completes without the `/`

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/41501850-184196f6-71a4-11e8-97db-1969dbb2f498.png)

**Comment by lukebarnard1** [comment]
This should really be filed against the [slate PR](https://github.com/matrix-org/matrix-react-sdk/pull/1890)

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
