### ISSUE TITLE
Notification settings are broken

### ISSUE THREAD

**Issue by z3ntu** [vector-im/element-web#6893]
### Description

In the notification settings the "Messages in group chats" doesn't have a radio button ticked.
![image](https://user-images.githubusercontent.com/3768500/41507422-77b0a0e4-7232-11e8-8a7c-9283f9cdcf4e.png)

### Steps to reproduce

?

**Describe how what happens differs from what you expected.**

One of the radio buttons should be ticked.

Log: sent

unrelated, but this template says logs can be sent with the 'Report bug' button but the button is called 'Submit debug logs' 

### Version information

- **Platform**: Desktop
- **OS**: Arch Linux
- **Version**: 0.15.5

**Comment by t3chguy** [comment]
Fixed by new notifications panel in labs
