### ISSUE TITLE
Wishlist: status.im derived dark theme

### ISSUE THREAD

**Issue by tidux** [vector-im/element-web#6916]
The new status.im theme is generally good if you prefer light themes, but for something I keep open as long and often as a chat client, a bright white theme is like staring into the sun.  There are workarounds like Stylus and custom CSS, but those don't typically apply to bundled Electron versions like riot-desktop.

**Comment by lampholder** [comment]
The status theme was provided by status.im - if somebody were interested in contributing a dark theme derived from the status theme we could look at merging it.

**Comment by eeeeeta** [comment]
Someone's already done so: https://github.com/vector-im/riot-web/pull/6816

**Comment by MTRNord** [comment]
@eeeeeta well it is indeed using the Status.im source as base. But not sure If it counts as dark theme of the Status im theme :) (but I let the community decide)

**Comment by turt2live** [comment]
@tidux how does the new dark theme released today feel with respect to this issue?

**Comment by tidux** [comment]
It looks good on a sufficiently wide screen.  Splitting a 1920x1200 monitor in half vertically makes it uncomfortably compact until you fiddle with the sidebars.

**Comment by turt2live** [comment]
We've gone years without the status.im theme in the app and have better support for custom themes these days. Instead of keeping this open, I trust the theme community will work on something if truly desired for this decade :)
