### ISSUE TITLE
"Reply" composition lost if switching rooms during message composition

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#6918]
Repoducible on /develop :

- have two rooms
- "reply" to a message in room1, partially compose a reply
- switch to room2
- switch to room1

Looking at the message to be sent, it has lost the 'reply' popout box and if sent will not include the message being replied to, which can lead to some odd messages that assume context from the message being replied to.

The UI is consistent - if it doesn't show it'll send a reply it doesn't send the reply, but we should retain the message composition state in general.

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/6006 (yes, closed, but it describes a failure that should be avoided when fixing the OP)

**Comment by lukebarnard1** [comment]
We currently store a single `replyingToEvent` in `RoomViewStore`. We should really store a map between rooms and the `replyingToEvent`.

**Comment by t3chguy** [comment]
unless we also want it persisted across restarts, like composer history is

**Comment by turt2live** [comment]
storing that between restarts doesn't seem worth the effort to me. Chances are people won't click `Reply` then F5

**Comment by t3chguy** [comment]
It'd be consistent though, if someone hits Reply, types a message and then F5/browser crashes/whatever their reply-text will still be there but the replying state&target will have gone

**Comment by t3chguy** [comment]
there was also another point brought up IRL, should it persist in up/down arrow history, so say I reply to someone, send it and hit UP arrow, should the reply state be brought back? Semantically this seems right

**Comment by t3chguy** [comment]
Related to https://github.com/vector-im/element-web/issues/10353
