### ISSUE TITLE
Option to disable command syntax staying open

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6920]
I'm finding it more annoying than helpful, particularly given the most popular command I use is `/me` - I know how to use this, and I'd rather see the message under the popover.

**Comment by lampholder** [comment]
Would it be enough if it stayed dismissed after you'd pressed <kbd>Esc</kbd>?

**Comment by turt2live** [comment]
That'd be one option, although I fear my escape key would get hit with frustration.

**Comment by t3chguy** [comment]
and it obscures the last 1-2 messages

**Comment by erikjohnston** [comment]
This is mostly annoying as it has a tendency to obscure the last (and therefore new) messages

**Comment by turt2live** [comment]
We changed how autocomplete works for commands
