### ISSUE TITLE
Messages lost in transit, devices out of sync

### ISSUE THREAD

**Issue by MathiasRenner** [vector-im/element-web#6925]
### Description

It happened to me that several messages were lost in transit using the flagship app Riot. Also, I sometimes encountered sync problems between devices.

### Steps to reproduce

I cannot describe steps to reproduce, basically wanna just share my experience. Matthew, an admin from the MatrixHQ chat room proposed to at least open an issue about it here.

I just can say that I tried out different use cases: 
  - encr on and off, 
  - contacting users on different servers/same matrix server, 
  - different devices/single device.

### Version information

Riot on Desktop on Debian 9, and Android (LineageOS). All latest versions.

**Comment by ara4n** [comment]
what do you mean by 'lost in transit'? that they were never sent to the room? or were undecryptable for other people in the room? what sort of sync problems were you seeing between your own devices? undecryptable messages or missing messages or old history?

What server was this on?

**Comment by MathiasRenner** [comment]
@ara4n Lost in transit = were never sent to the room.

Sync problem = order of messages turned around: I send message A and B. The receiver devices got B and then A. On my side the desktop app or Android app showed not the same but one of them A and B and the other one B and A.
This happend especially in combination with sending media (audio or image) and text messages. After some time, like 1h or so, the sync was OK again. This might be related to the performance issues.

I always used the disroot.org server with my account. The receivers were either on that one, matrix.org or other synapse servers.

In addition, upload of media in general was very slow, and sometimes did not upload at all. But I got the feeling that you have the performance problems alread on your issue list.
Also calling did not work on Android and Desktop, probably also related to performance issues.

**Comment by Thovthe** [comment]
I am encountering the same problem with messages not getting to the other side between two accounts on matrix.org.

I don't have both clients to fiddle with right now but the other party called me (pstn because riot didn't work) and swears that they never received a few of my messages from yesterday.

Summary:
Silently dropped messages on matrix.org
Calls not connecting

**Comment by eeeeeta** [comment]
fwiw, I've also found that matrix.org can occasionally delay messages sent in a 1:1 room between a matrix.org user and me on my own HS, waiting up to a week to send the message, or just not sending it until my synapse is restarted.

**Comment by Thovthe** [comment]
Can anyone think of a good way to test this?  I think the issue may have disappeared.

**Comment by yousefamar** [comment]
I don't know if this is the same issue, but I've been having messages not show up randomly recently until I fully close element (desktop) and reopen it again. Could it be related? My console just gives a bunch of these, which don't seem related (rageshake.js)

![image](https://user-images.githubusercontent.com/999235/125262803-62124d00-e2fa-11eb-9b99-22019497d974.png)

**Comment by t3chguy** [comment]
Definitely not the same issue @yousefamar

**Comment by MadLittleMods** [comment]
> In addition, upload of media in general was very slow, and sometimes did not upload at all.

Related to https://github.com/vector-im/element-web/issues/21343

> order of messages turned around: I send message A and B. The receiver devices got B and then A. On my side the desktop app or Android app showed not the same but one of them A and B and the other one B and A.
This happend especially in combination with sending media (audio or image) and text messages. After some time, like 1h or so, the sync was OK again. This might be related to the performance issues.

Related to:

 - https://github.com/vector-im/element-web/issues/23662
 - https://github.com/vector-im/element-web/issues/22885
 - https://github.com/vector-im/element-web/issues/20024
 - https://github.com/vector-im/element-web/issues/1173
 - https://github.com/vector-im/element-web/issues/9234

**Comment by MadLittleMods** [comment]
Closing in favor of linked issues. Anything I missed should be moved to its own dedicated issue.
