### ISSUE TITLE
Empty room list when no results found 

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6938]
![image](https://user-images.githubusercontent.com/1190097/41867370-39499100-7870-11e8-925e-d3f9fd1cd641.png)

Would be nice to have a "No room found" message, otherwise the app feels a little bit broken.

**Comment by lampholder** [comment]
Shares a cause with https://github.com/vector-im/riot-web/issues/6941

**Comment by turt2live** [comment]
#6941 and this are independent.

**Comment by t3chguy** [comment]
Still a thing post redesign
![image](https://user-images.githubusercontent.com/2403652/53293786-a3117180-37d2-11e9-9a4b-9b96aa752cbf.png)

**Comment by turt2live** [comment]
and in the 2020 room list :D

**Comment by turt2live** [comment]
we fixed this
