### ISSUE TITLE
linkify mxc:// urls as links to the media repo of the HS you're connected to

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#6942]

**Comment by lampholder** [comment]
So if you render a mxc:// url in the timeline it will be automatically reconciled into a (clickable, copy+pastable) media repo https:// url for you HS?

**Comment by joepie91** [comment]
I'd say that this is actually also partly a bug, not just a feature request:

![Selection_538](https://user-images.githubusercontent.com/1663259/72337363-b9fad400-36c2-11ea-84d6-43f208dd439f.png)

As there's no explicit MXC URL parsing, it's being caught by the generic URL linkifier, which misinterprets it as a protocol-relative (ie. usually HTTPS) URL, and produces a broken link.

**Comment by grinapo** [comment]
So, indeed, 
`mxc://matrix.org/xYADvTIVsAuDwmEfjLjTxPLJ`
shall become 
`<server url>/_matrix/media/r0/download/<locator>`
like on my local server:
`https://matrix.grin.hu:8448/_matrix/media/r0/download/matrix.org/xYADvTIVsAuDwmEfjLjTxPLJ`

**Comment by t3chguy** [comment]
If only it was easy with the existing linkification library :D

Blocked on https://github.com/Soapbox/linkifyjs/issues/194 or us finding a new linkification lib

**Comment by grinapo** [comment]
> Blocked on [Soapbox/linkifyjs#194](https://github.com/Soapbox/linkifyjs/issues/194) or us finding a new linkification lib

Noticing that this issue is not touched since 2017 I ain't particularly hopeful.

[This SO answer](https://stackoverflow.com/questions/37684/how-to-replace-plain-urls-with-links) lists a few viable alternatives.

**Comment by t3chguy** [comment]
Not easy to move off linkifyjs, as that's what is used to linkify room aliases, mxid references and community references. Autolinker has special handlers for @grinapo style mentions and #hashtags but not generic to extend to MXID, room aliases and community ids.
