### ISSUE TITLE
Sometimes reply threads fail, appear as small spinner

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#6951]
The error thrown was 
```js
Unhandled rejection Error: No such component: undefined
    at Skinner.getComponent (https://riot.im/develop/bundles/be5abbecb3cab1c5c883/bundle.js:79172:24)
    at Object.module.exports.getComponent (https://riot.im/develop/bundles/be5abbecb3cab1c5c883/bundle.js:653:31)
    at Object.render (https://riot.im/develop/bundles/be5abbecb3cab1c5c883/bundle.js:166329:34)
```

where the last line is EventTile.js, line 487.

**Comment by lukebarnard1** [comment]
This was in an E2E room and I'm assuming the other clients were Riot web (this was in an internal chat).

**Comment by t3chguy** [comment]
I wonder if a failed decrypt or something similar could cause this, I'll take a look

**Comment by t3chguy** [comment]
for the time being will add a null guard to that EventTile line which spits out the eventType and whether or not it is state so you can get more data if it occurs again

**Comment by yannicka** [comment]
Is this still the case?

**Comment by kittykat** [comment]
I'm going to close this for now as we haven't had any more reports of this and it is an old issue. If anyone still experiences this, please file a new issue with more details and rageshakes from all people involved :+1:
