### ISSUE TITLE
Messages randomly do not send

### ISSUE THREAD

**Issue by c4ch3c4d3** [vector-im/element-web#6960]
### Description

Sometimes, message sending (encrypted & unencrypted) will hang for long periods of time (30 min+).  I've checked my server logs, and they show that the matrix instance I'm hosting does appear to be working properly (shows events for typing, messages, etc.) but the message on my end stays greyed out, and the receiver never gets anything.  Eventually, this will seem to clear up on its own, and the message will go through.

### Steps to reproduce
I've been unable to determine any sort of root cause.  Can happen during heavy usage, or within the first couple of messages sent in a morning.

Log: sent

### Version information

- **Platform**: Desktop

- **OS**: MacOS
- **Version**: 0.15.5

**Comment by lampholder** [comment]
It strikes me that this could be very tough to diagnose - would you be able to submit some logs (User Settings -> *scroll to bottom* -> SUBMIT DEBUG LOGS -> paste in the link to this github issue) to help?

Thanks!

**Comment by cachecade** [comment]
Followed the work flow to submit the logs, should they actually show up in the comments here?

**Comment by MadLittleMods** [comment]
> Followed the work flow to submit the logs, should they actually show up in the comments here?

Your debug logs are linked here but they aren't visible to you because it's in our private rageshake repo.

It looks like this didn't get the proper attention at the time. If you're still seeing issues like this feel free to post with new details and we can re-open.
