### ISSUE TITLE
Interpret quotes from fallback when they fail to load

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#6977]
With some sort of warning next to it. At least this way it's not a sad pile of sad when the event is missing

**Comment by t3chguy** [comment]
What? You mean use the reply fallback when the ev fails to load?

**Comment by t3chguy** [comment]
The issue then is you lose nesting

**Comment by turt2live** [comment]
This is the general idea (UI needs a lot of improvement):
![image](https://user-images.githubusercontent.com/1190097/42328413-69e2d8c2-802b-11e8-9395-45460890a72d.png)

The idea is to just take the fallback text and stick it into the quote structure. I'd say nested replies are safe to lose in this scenario.

**Comment by t3chguy** [comment]
Clients/Bridges other than riot-web don't send the fallback so it seems like it'd be seldom used

**Comment by t3chguy** [comment]
yup I agree its better than erroring

**Comment by t3chguy** [comment]
also no timestamp though :(

**Comment by t3chguy** [comment]
@lampholder do you have ideas on a design for the above?

**Comment by lampholder** [comment]
Hmmmmmm.

It's tough, 'cause the distinction between its working (we can find the event) and not (we can't) is not something we'd expect a user necessarily to understand.

If we were to render the fallback instead, would this be risking users being able to put words in other users' mouths through malcrafted events?

I think on balance I might prefer we do nothing (except fail and explain why we've failed)?

**Comment by t3chguy** [comment]
> If we were to render the fallback instead, would this be risking users being able to put words in other users' mouths through malcrafted events?


Yes which is why Travis's Render has the yellow warning text

**Comment by lampholder** [comment]
Understood, but it's... a new and potentially surprising thing for users to see and understand.

So I'd prefer we keep it simple :smile:

**Comment by kittykat** [comment]
@turt2live do those two PRs fix it to your satisfaction? Or what is left to do on this issue?

**Comment by turt2live** [comment]
Sure :D
