### ISSUE TITLE
Visibility setting of a room on a community page is hard to find

### ISSUE THREAD

**Issue by vsund** [vector-im/element-web#6979]
When adding a room to a community, there's a checkbox for "Show these rooms to non-members on the community page and room list?". I'm unable to find a setting for editing the visibility of a room after initially adding it to the list.

Might be that I just cannot find the setting, or that it's not possible due to some internal things. Feel free to close if that's the case or point me to the setting if I just couldn't find it :)

The current version (I'm using) is `v0.15.6`.

**Comment by turt2live** [comment]
I'd say leave it open, yea.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
