### ISSUE TITLE
shutdown room API should mute rooms before masskicking

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6996]

**Comment by lampholder** [comment]
@ara4n Did you mean to file this with riot-web rather than synapse?

**Comment by t3chguy** [comment]
as in some magical local mute thing which doesn't get sent over federation as the local HS may not have powers in said room? (given room shutdown just force leaves local HS from room)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/12622
