### ISSUE TITLE
Sorting memberlist by community

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#7000]
Seems like a good idea, if you want to ensure your staff/community/whatever remain on top of the memberlist ala Discord:

![image](https://user-images.githubusercontent.com/2072976/42505565-02da32c8-8437-11e8-98fc-ea24b863266f.png)

(I thought an issue was open for this, but I can't find it. Please close if found.)

**Comment by t3chguy** [comment]
what about for people like you who are in *ALL THE COMMUNITIES* will we see your face plastered in every subsectrion :P?

**Comment by Half-Shot** [comment]
@t3chguy Clearly it would be a feature /s. Moreover though, you raise a good point. I would have first suggested canonical communities be a thing per user, but we have no concept of that atm.

**Comment by turt2live** [comment]
Rooms should probably have the option of which communities to sort by in the list. Just so that `+community:matrix.org` can have flair and not be at the top of every room in the ecosystem.

**Comment by Half-Shot** [comment]
Discords roles do this by first setting which roles should appear at all, and then they are ranked by the powerlevels those roles give. However in this case we don't have powerlevels as a thing for roles..but we could probably use a state event for ordering them.

**Comment by Half-Shot** [comment]
Ooo. Could we (after speccing it :anger: ) use ``m.room.related_groups`` and just make the ordering of the list determine the order of the groups?

**Comment by turt2live** [comment]
The concern I have with using `m.room.related_groups` is the flair problem I mentioned earlier. Would be nice to have flair and the memberlist not tightly bound like that, giving the member list more autonomy.

**Comment by Half-Shot** [comment]
You could easily have ``groups`` and ``visible_in_memberlist:[]`` though I worry this is leaking out into Riot specific land.

**Comment by kevinfaguiar** [comment]
Any news on this issue?

**Comment by kittykat** [comment]
I am going to close this issue for now as Spaces is replacing Communities. Please open a new issue against Spaces for improvements.
