### ISSUE TITLE
Wrong avatar used in community

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-web#7010]
### Description

I have changed my avatar around mid-May. I just joined a community on matrix.org (`+linuxfr:matrix.org`) from my own HS, and my old avatar is showing up in the community's members list, instead of my current one. Other communities show my current avatar in their members lists.

I tried clearing the cache and reloading, but it didn't fix the issue. I haven't rageshaken since I didn't think of doing so before that.

### Version information

- **Platform**: web through Rambox

For the web app:

- **Browser**: Rambox 0.5.17
- **OS**: Arch Linux
- **URL**: riot.im/develop
- **MXID**:  `@Brendan:matrix.trancendances.fr`

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
