### ISSUE TITLE
If you don't have any keywords set for notifications, you can't change the notif level on 'Message containing keywords' to 'off' or 'noisy'.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7011]
And your clicks are just ignored, which is confusing.

To reproduce:
- go to user settings
- click on the _keywords_ link in notifs
- delete all your keywords
- try and change the notif level to 'off' or 'noisy'
- observe you clicks being ignored

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/2188
