### ISSUE TITLE
Redacting an event doesn't redact the fallback in replies

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7014]
This is probably impossible without aggregations, but it is something that should happen

**Comment by t3chguy** [comment]
but +10000 to dropping the on-wire fallback, as it'll allow us to reply with files and emotes :D

**Comment by yannicka** [comment]
Is this still the case?

**Comment by SimonBrandner** [comment]
> but it is something that should happen

Yes
![Screenshot_20211211_192207](https://user-images.githubusercontent.com/25768714/145687403-cab095d1-87d3-459f-a120-91d680ebd531.png)

**Comment by t3chguy** [comment]
Its also not something that is possible to fix other than just removing the fallback in spec.

Redacting event X cannot mutate other events to strip their copy of the event as it would break the room DAG.

**Comment by turt2live** [comment]
Closing as a spec issue. Note that as of  Matrix 1.3 (coming soon) the fallback is optional and thus clients can stop sending it, in theory. Whether they want to stop sending it is a whole other question.
