### ISSUE TITLE
riot hangs when you open a large room

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#7015]
for example, `#_rizon_#horriblesubs:matrix.org`. Possibly because there are lots of membership events, which then get collapsed, so we end up paging in millions of events

**Comment by bwindels** [comment]
Good to have a channel to try lazy loading on!

**Comment by dbkr** [comment]
Actually I *think* this is the same as https://github.com/vector-im/riot-web/issues/7163 (I initially thought it wasn't)
