### ISSUE TITLE
flickering typo indicator whilst typing in slate in Chrome is irritating

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7044]
every keystroke i press makes all the squiggly red lines flicker. and the word which is currently being typed also gets typo-flagged, which seems a bit surprising

**Comment by t3chguy** [comment]
This seems to happen on https://www.slatejs.org/#/rich-text too :(

**Comment by ara4n** [comment]
this really isn't p1

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment]
Assuming no
