### ISSUE TITLE
Pressing <ENTER> Empties Email Field (Should Submit Form, Advance Flow)

### ISSUE THREAD

**Issue by martindale** [vector-im/element-web#7048]
After;
1. Upgrading from a Guest Account to Registered Account
2. Clicking "Set Password" Alert at Top
3. Fill out "Do you want to set an email address?"
4. Press `<ENTER>`

Note the form is cleared and not submitted.

**Comment by t3chguy** [comment]
I think you're on an outdated version. Don't ignore the issue template. It is there for a reason. The clearing of the field was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1982

**Comment by t3chguy** [comment]
Whilst yes enter does not advance the form, the field is not cleared:
![7048](https://user-images.githubusercontent.com/2403652/42839837-d5138882-89fc-11e8-8341-726e9486f956.gif)

**Comment by lampholder** [comment]
@martindale - can you confirm whether this was the case?

Thanks!

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
