### ISSUE TITLE
Triple-clicking the text in the slate composer doesn't select all of it if there's a pill in there.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7053]

**Comment by t3chguy** [comment]
Double click in Slate is select this block, where a pill interrupts that

**Comment by lampholder** [comment]
On reflection I'm not sure whether I mean doubleclick or tripleclick, but your response is valid either way - the pill interrupts the entity that I would otherwise be selecting all of with a (I think) tripleclick.

It 'feels right' that tripleclicking in a block level element (like a quote) would only select all of the element. It 'feels wrong' to me that a pill is a separating block.

Is this fixable? Trivially or complicatedly?

**Comment by turt2live** [comment]
I think you meant triple click - updated title accordingly.

**Comment by turt2live** [comment]
(transferred labels from https://github.com/vector-im/riot-web/issues/7107)

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by yannicka** [comment]
For my part, I can select all by triple-clicking the text on Riot Desktop 1.6.0, but not on Firefox 76 with Riot Web 1.6.1.

**Comment by t3chguy** [comment]
I can't reproduce this, shout if it is widespread
