### ISSUE TITLE
browser undo/redo greyed out doesn't match reality on Composer

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#7054]
originally reported as
> Also the state of when the 'undo' menu action is available seems incorrect. Sometimes cmd+z works even when the undo menu item is greyed out(!)

in https://github.com/vector-im/riot-web/issues/7052 by @dbkr 

I'm not sure this is something we can do about as Slate manages history itself instead of relying on the browser

**Comment by lampholder** [comment]
You mean in the context menu? Is the 'undo' state displayed anywhere else?

**Comment by t3chguy** [comment]
I believe thats what is meant yes
It is not currently shown but it could be as per: https://www.slatejs.org/#/history

**Comment by dbkr** [comment]
(I meant in both the context menu and in the normal menu bar menu)

**Comment by kittykat** [comment]
I can't reproduce this issue. If anyone knows how to, please add steps and reopen.
