### ISSUE TITLE
People without profiles have very small pills

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7063]
![image](https://user-images.githubusercontent.com/1190097/42956213-a4e74482-8b3c-11e8-8b76-122e46f8a35e.png)

Before it'd either try to get the real profile for the user or stick with the user ID. I'm not sure what steps are required to trigger this, but it did take a little while for it to convert itself to a pill.

Event source:
```
{
  "origin_server_ts": 1532016861803,
  "sender": "@travis:t2l.io",
  "event_id": "$15320168611058mxKeL:t2l.io",
  "unsigned": {
    "age": 532,
    "transaction_id": "m1532016863356.52"
  },
  "content": {
    "body": "@benpa:matrix.org: done. Now what? :P https://docs.google.com/document/d/162-54jvFa_i_blLhg_MEhe5fWZD_MGlIdzwz4KK5j0E/edit?usp=sharing",
    "msgtype": "m.text",
    "formatted_body": "<a href=\"https://matrix.to/#/@benpa:matrix.org\">@benpa:matrix.org</a>: done. Now what? :P https://docs.google.com/document/d/162-54jvFa_i_blLhg_MEhe5fWZD_MGlIdzwz4KK5j0E/edit?usp=sharing",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!QtykxKocfZaZOUrTwp:matrix.org"
}
```

**Comment by lampholder** [comment]
Does benpa not have a profile?

**Comment by turt2live** [comment]
Not at the time of the screenshot (note the previous message is Riot falling back to mxid)

**Comment by kittykat** [comment]
I'm going to close this issue as it now shows the first part of MXID if no display name is set
