### ISSUE TITLE
Reports of some users' GDPR links resulting in "missing string query parameter 'u'".

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7064]
We received a report that a user clicked the link presented by Riot to review the Privacy Notice, etc., but the page that opened was `https://matrix.org/_matrix/consent?h=bdfs67sdf79sdf7890sdf789sdf789` - crucially missing the `&u=username` from the end.

Ubuntu 16.04.4 LTS, Firefox 61.0.1 64 bit

I haven't been able to reproduce this using my machine (Ubuntu 16.04.2 LTS, Firefox 61.0.1 64 bit) on either pre- or post-GDRP compatible versions of Riot - the link always works for me just fine (whether it's the link provided in the System Alerts room, or the one that pops up in the modal error in compatible versions of Riot web.

I _haven't_ been able to check the link that's provided in the message send status bar when you try and send a message but are denied due to not having provided consent.

Creating this issue to see if anyone else has observed a similar problem.

**Comment by lampholder** [comment]
The user who reported this had followed the instructions https://github.com/vector-im/riot-web#installation-steps-for-debian-stretch to install the Electron client.

They tried clicking on both the modal button and the link from System Alerts, both of which linked to the incomplete URL. Only right-clicking the link revealed that it should have had the username supplied at the end of the URL.

I have not been able to reproduce this so far - leaving open to catch more instances in the wild.

**Comment by t3chguy** [comment]
The links come as `consent_uri` from Synapse - closing as lack of reports in 3.5 years

If you experience this again, please open an issue in https://github.com/matrix-org/synapse/
