### ISSUE TITLE
 Disable history download from the server

### ISSUE THREAD

**Issue by cavabanga26** [vector-im/element-web#7067]
It is necessary that the history is stored on the server, but  not load from it when I opened the client
I can not find this code in bundle.js

**Comment by lampholder** [comment]
Do you mean that you want to be able to use matrix-js-sdk to be able to connect to the homeserver without syncing in message history from the user's rooms?

**Comment by cavabanga26** [comment]
Yes, users do not need to see their history after updating the page

**Comment by kittykat** [comment]
I'm going to close this for now, please file a new issue with more details if you are still experiencing any issues.
