### ISSUE TITLE
Images are sometimes sent as files (without preview/thumbnail) when upload speed is slow

### ISSUE THREAD

**Issue by Edszx** [vector-im/element-web#7069]
### Description

This problem has been there since forever, but i'm finally not being lazy an reporting it properly, when the computer's upload speed is low, say 40KBps for example, sometimes images uploaded to riot are sent as files, meaning, without preview/thumbnail, just a single line of text with the filename that you can click to download, and "X uploaded a file" over it instead of "X sent an image".
I think it happens if there is any packet loss while the image is being uploaded.

### Steps to reproduce

- The upload speed has to be terribly low
- Try to send a 1MB image, for example.
- It will take 35+ seconds to upload (again, because for this to happen upload speed has to be low)
- If it doesn't fail/timeout in the process (again, because of the slow upload) it will be sent as a file, without preview and the message "X sent a file" instead of an image.

**Log:** sent 

### Screenshots

![riot_2018-07-22_01-18-30](https://user-images.githubusercontent.com/10441078/43042522-5dea3170-8d4e-11e8-90b6-d6b09a425302.png)

![riot_2018-07-21_16-02-15](https://user-images.githubusercontent.com/10441078/43042559-59cf42e6-8d4f-11e8-9dc9-6b616f409115.png)

### Version information

- **Platform**: desktop and web
- **Browser**: Chrome and Firefox, possibly others.
- **OS**: Windows
- **Version**: 0.15.7

**Comment by lampholder** [comment]
Just recording that I haven't been able to reproduce this _yet_ - Chromes 'Slow 3G' network throttling preset didn't work for a 1.1MB png.

**Comment by Edszx** [comment]
@lampholder I suggest https://github.com/jagt/clumsy to make your network drop packets, thank you for looking into this.

**Comment by t3chguy** [comment]
This happens when local thumbnailing fails (and thus riot-web is not sure the file is an image after all)

**Comment by Half-Shot** [comment]
Ugh, https://github.com/matrix-org/matrix-react-sdk/blob/2dc94ac277bfaed6e7a8116ff08bba22ee8fb642/src/ContentMessages.js#L306

**Comment by bisongde** [comment]
@t3chguy this also still reliably happens with video files across all browsers (see [1752](https://github.com/vector-im/riot-ios/issues/1752) , [6426](https://github.com/vector-im/riot-web/issues/6426)). If this could get a little love it would be a huge benefit to quality of life - multimedia is a big part of how users communicate.

**Comment by t3chguy** [comment]
I tried this and it came down to a browser/low level library fault
its the browser passing up an error from some C library, I can't remember the specifics

**Comment by sevmonster** [comment]
Is this still an issue? I have users that are uploading videos and they are saved as `m.file` events rather than `m.video`. I don't know if it's related to this issue, but all the other "my video won't play" issues that I can find were closed as duplicates of this one. It's not #6426 either (if that is still an issue), as the video in question was a 3MB webm.

**Comment by SamiLehtinen** [comment]
I were one of users suffering from this problem way too often. Haven't seen the problem for a good while. Yet I also switched to much faster server. But based on my experience, I could assume it's not a practical problem anymore. Of course test cases should cover the situations where post fails. If that's done, then this is also technically fixed.

**Comment by ara4n** [comment]
Just got bitten by this yet again, while on poor wifi.  Have rageshaked on it.
