### ISSUE TITLE
In Community description, specify that <img> tags require a Matrix URL

### ISSUE THREAD

**Issue by Xananax** [vector-im/element-web#7100]
As someone who knows nothing about the protocol, but knows HTML, I thought I could use any URL for the `<img>` tag. It didn't occur to me that only Matrix urls would be allowed, which tripped me up for a good hour.

I think the text should somehow say that only Matrix urls are accepted

**Comment by uhoreg** [comment]
The input box for the community description initially looks like this:
![image](https://user-images.githubusercontent.com/1012976/43361861-41e95fc6-92aa-11e8-8526-ba785f8a4cf6.png)
The "You can even use 'img' tags" sentence should probably mention that only mxc URLs are allowed.  
This seems to trip people up frequently.

**Comment by turt2live** [comment]
As an alternative, it could make use of https://github.com/matrix-org/matrix-doc/issues/1270 (or similar) and automatically upload the image.

**Comment by fduraibi** [comment]
How do I get a martix URL and how to use it?

**Comment by uhoreg** [comment]
The easiest way to get one is to upload the image to a room somewhere, click on the "..." button that appears when you hover-over the image, click on "View Source", and look for the "mxc://..." URL.  Once you have that, then you can use it in the img tag as "\<img src="mxc://..."\>"

**Comment by turt2live** [comment]
Or invite `@mediabot:t2bot.io` to a room and upload an image. It will tell you the mxc uri.
