### ISSUE TITLE
Power level change resets in MemberInfo when someone sends a message

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7111]
1. Open the member info for a moderator (probably applies to others as well)
2. Select "Custom Level" and start entering a new level
3. Receive message
4. Dropdown has reset to moderator.

**Comment by turt2live** [comment]
worth noting that a message in *any* room causes this.

**Comment by t3chguy** [comment]
@turt2live are you still seeing this? I've not been able to reproduce

**Comment by turt2live** [comment]
I'm inclined to say no.
