### ISSUE TITLE
Decrypting a series of events, which happen to contain a Jitsi widget, leads to a 1/4 second call notification

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7117]
1. Have someone start a call in an encrypted room
2. Finish the call
3. Give Riot some time to store the events
4. Experience https://github.com/vector-im/riot-web/issues/7116 (easiest way to reproduce)

**Comment by lampholder** [comment]
Related? https://github.com/vector-im/riot-web/issues/4607

**Comment by turt2live** [comment]
I don't think this is a problem anymore
