### ISSUE TITLE
Two-sided chat interface: Own chat history on right side

### ISSUE THREAD

**Issue by Hoeze** [vector-im/element-web#7125]
### Description
Currently all chat history is aligned to the left side.
Since most empty profile pictures are just green, it is hard to differ between my own and foreign messages at first glance:

![image](https://user-images.githubusercontent.com/1200058/43555536-085a1fbc-95fb-11e8-927f-b9ee939e825d.png)

It would be cool, if my own text would be shown on the right side, similar to WhatsApp.
This would significantly improve clarity of the chat history:
![image](https://user-images.githubusercontent.com/1200058/43555600-736aecdc-95fb-11e8-80a4-d670a7301fdd.png)
(source: https://www.androidpolice.com/2016/06/28/whatsapp-received-many-small-ui-changes-lately-continuous-scroll-history-finally-new-group-broadcast-layouts-olympic-emoji/)

### Version information

- **Platform**: web
- **Browser**: Firefox 61
- **OS**: Linux
- **URL**: https://riot.im/app/

**Comment by NotAFile** [comment]
I'm not sure this is a good idea on the desktop. This becomes very hard to read on larger screens. I think that instead, your messages should be marked more clearly in some way, perhaps?

**Comment by Hoeze** [comment]
Yes, in theory you're right, but if you try whatsapp web you can see that this actually is no problem.
1) I'm using it on 16:9 without any problems
2) It is possible to set a maximum boundary of chat width
3) There could be an option for the user to change this behavior

Nevertheless, a colored background for messages would be VERY important anyways.
It's really hard to differ users currently.

**Comment by Soundtoxin** [comment]
If we're discussing solutions to it being hard to tell users apart, I'd love an IRC emulation option. Username and time stamps next to each line, hide avatars, get really good text density, maybe support hiding all the sidebars and such. That'd make it work better in a small window as well.

**Comment by NotAFile** [comment]
That sounds a lot like the "compact" mode like slack and a few other programs have.

**Comment by raarts** [comment]
Just weighing in, new user here, I'd really like my own chats on the right side too. Microsoft Teams does this too. Maybe this is hard to read on large screens, but I would reckon many if not most people work on laptops these days.

**Comment by NotAFile** [comment]
What telegram does is switch to the two-sided mode when the window is small enough.

**Comment by robintown** [comment]
Closing in favor of #4635 (coming soon to an Element near you!)
