### ISSUE TITLE
bad scale video call in full window mode

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#7130]
### Description

If I press "full screen" button in video call mode - then I see only part of video image (if remote video grab in portrait mode). Video image scale to fit screen by width. But Riot is must  scale to width or height of local monitor - it is must not lose part of video image.

### Steps to reproduce

1. Start video call from android riot in portrait orientation to web-riot.
2. See in web riot - that all is good.
3. Press "full screen"
4. See, that video-image wrong scaled.

### Version information
riot-web: 0.15.2
olm: 2.2.1

- **Browser**: chromium-browser                            68.0.3440.75-0ubuntu0.16.04.1
- **OS**:  Ubuntu 16.04
- **URL**: it is a private server. version of riot-web 0.15.2
Not in full screen mode:
![no_full](https://user-images.githubusercontent.com/1297163/43578614-a023e1c4-9692-11e8-83a3-69a4df54566b.png)
In "full screen" mode we see only part of video image and not see our preview:
![full](https://user-images.githubusercontent.com/1297163/43578613-9feb0c46-9692-11e8-9d8b-b0029c0daf54.png)

**Comment by bwindels** [comment]
Unexpected video aspect ratio breaks full screen webrtc call.

**Comment by afranke** [comment]
FWIW portrait orientation is not the single source of this issue. My 1 year old laptop apparently has a 4/3 webcam which triggers the problem on the other side of the conversation where the screen is 16/9.

**Comment by SimonBrandner** [comment]
Should be fixed by [#5676](https://github.com/matrix-org/matrix-react-sdk/pull/5676)
