### ISSUE TITLE
Add config.json option for disabling the register form

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7135]
Request from #riot: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$2458-3-3-2T84501.844208|Night_Gliders_Panicky_Seahorse_Burns_Prince_Crompuss_Ugly_Peafowl:ponies.im

**Comment by ananace** [comment]
Having deployed Element for use at a university where people are only allowed to log in with their OIDC account, this would help reduce confusion a bit when a user arrives and is greeted with the option to either log in or create an account - both of which take them to the same login prompt.

Skipping the entire login/create account screen would probably be the most ergonomic for us, so the user's dropped directly to the login prompt.

**Comment by t3chguy** [comment]
We have this as part of UIFeature flags
