### ISSUE TITLE
Riot stopped storing syncs for me

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7147]
```
indexeddb-store-worker.js:114 Error running command: syncToDatabase
(anonymous) @ indexeddb-store-worker.js:114
indexeddb-store-worker.js:115 Eventbubbles: truecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: truepath: []returnValue: truesrcElement: IDBRequest {result: undefined, error: DOMException: The serialized value is too large (size=135103244 bytes, max=133169152 bytes)., source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", …}target: IDBRequest {result: undefined, error: DOMException: The serialized value is too large (size=135103244 bytes, max=133169152 bytes)., source: IDBObjectStore, transaction: IDBTransaction, readyState: "done", …}timeStamp: 0type: "error"__proto__: Event
(anonymous) @ indexeddb-store-worker.js:115
bundle.js:122131 sync fail: Error running command
```

Repeats every so often, doesn't appear to be every sync.

**Comment by bwindels** [comment]
Indexeddb getting full I guess. We could try to trim off some events and try storing again on error I guess. Full solution would be store events more granularly, but that would mean a big refactoring of the js sdk, so not for anytime soon.

**Comment by turt2live** [comment]
It's not nearly full yet (still has another 12gb to go on this device). It looks like one of my syncs was just massive and goes over the size limit by a few mb?

**Comment by bwindels** [comment]
Changing to major as it breaks sync completely.

**Comment by turt2live** [comment]
I "fixed" this by logging completely out of my account and logging back in. Would still be nice to have this fixed so it doesn't happen again :(

**Comment by bwindels** [comment]
Indeed, something to keep in mind

**Comment by turt2live** [comment]
Good luck, 2018 Travis
