### ISSUE TITLE
Scroll to message when a reply is clicked

### ISSUE THREAD

**Issue by NotAFile** [vector-im/element-web#7151]
### Description

It is often useful to see the context of a reply. Because of this, it would be useful to be able to jump to the message that was replied to. Most clients (Telegram, Whatsapp, Signal, etc.) allow you to do this by clicking on the reply. 

### Version information

- **Platform**: web
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
You can achieve this by clicking on the timestamp of the replied to message (though it's more of a 'jump to' than 'scroll to' I think).

Is this the behaviour you're looking for? Though (I'm guessing) you'd like it to be more easily discoverable?

**Comment by NotAFile** [comment]
Yep. I don't see why you couldn't have the whole message be clickable.

**Comment by BearerOfHonesty** [comment]
Can we have the 'Scroll to bottom' button scroll down to the message that was clicked last (FILO queue), like it works in Telegram, instead of going all the way to the bottom which is inconventien if you're catching up on backlog at the time.

**Comment by BrenBarn** [comment]
The fact that the timestamp is the link is a ludicrous UX decision.  There is no visual indication that the timestamp would do this.  There is no UI convention that timestamps will do this.  There is not even a message on hover that tells you that clicking on the timestamp will do this.  There is absolutely no way for the user to know that clicking on the timestamp goes to the original message.  Also, accidentally clicking on the user avatar (right next to the timestamp, but much bigger) open the user info side panel, so the user has to know to specifically and carefully click on one random piece of screen real estate for no apparent reason to magically activated a totally unrelated action.

Most egregiously, the entire rest of the message area has no click functionality, so there's no reason the entire message can't be a clickable link to the replied to message.

I love Matrix and Element in theory but, I'm sorry, issues like this just make me wonder what universe the developers are living in.  This is an unequivocally terrible UI choice, there was no reason to ever do it this way, and it should never have been implemented, let alone left unfixed for three years.  Please fix it.
