### ISSUE TITLE
Jitsi widget stays in sidebar even after leaving meeting && collapsing widget

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#7154]
### Description

After leaving a jitsi conference but leaving the widget up, and switching to another room, the widget continues to jump into the sidebar. Even collapsing the widget in the original room does not stop it from leaving the sidebar.

Only also clicking inside the jitsi widget while it's in the sidebar does it disappear. Very odd behaviour.

### Steps to reproduce

- Add jitsi widget to a room
- Join conference
- Leave conference but leave widget up
- Switch to another room. Notice that widget jumps to sidebar, but you've left the meeting
- Switch back to original room
- Collapse jitsi widget
- Switch to another room. Jitsi still goes to sidebar
- Click somewhere inside the jitsi widget
- Sidebar widget finally disappears

Log: not sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian Linux
- **Version**: 0.16.0

**Comment by lampholder** [comment]
I could reproduce this when I left the Jitsi conference but didn't dismiss the 'rate your meeting experience' UX - is that what you did?

When I had dismissed that UX, the 'right thing' happened and the conference widget no longer appeared in the left panel (for me).

**Comment by anoadragon453** [comment]
Yes, that's exactly what I did, and what I expect not a lot of people to dismiss

**Comment by bwindels** [comment]
Still happening on 1.0 fwiw:

![jitsi](https://user-images.githubusercontent.com/274386/52852953-55ce3980-311a-11e9-9408-bea5a6677f08.png)

**Comment by turt2live** [comment]
This is not something we can fix - the dialog must be dismissed for the Jitsi Meet API to say the call is over and for us to do the right thing. Flagging as an upstream issue.

**Comment by turt2live** [comment]
we've improved this flow, and it is indeed something we can't fix easily.
