### ISSUE TITLE
Replies don't work for files

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7156]
And apparently crash the browser entirely.

See https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15338291021458aQsex:t2l.io

**Comment by turt2live** [comment]
The crash was unrelated.

**Comment by dessalines** [comment]
I see now that element gives the message: 

"At this time it is not possible to reply with a file. Would you like to upload this file without replying?"

Is this a spec limitation, or UI only limitation? Replying with pictures especially is very common, and currently not possible.

**Comment by t3chguy** [comment]
Spec limitation, you can't form the mandatory fall-back when making a reply to a file.

**Comment by t3chguy** [comment]
Some designs for voice message replies specifically https://www.figma.com/file/uaWc62Ux2DkZC4OGtAGcNc/Voice-Messages?node-id=2475%3A67136

**Comment by t3chguy** [comment]
With MSC3676 this is now possible https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc3676/proposals/3676-transitioning-away-from-reply-fallbacks.md
