### ISSUE TITLE
Widgets with limited height do not scroll/trim correctly

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7172]
![image](https://user-images.githubusercontent.com/1190097/44158045-20646880-a071-11e8-9cc9-09620444f7b8.png)

Background color of the widget changed for visibility. Easiest way to reproduce is to open chrome dev tools (on the bottom).

Tested with Riot 0.16

**Comment by lampholder** [comment]
@dbkr - probably another one linked with the persistent widget fun :\

**Comment by turt2live** [comment]
we since fixed this I believe
