### ISSUE TITLE
Riot doesn't persist non-sent messages (as it says it does) 

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7177]
Noticed this while matrix.org went down for maintenance:

Repro steps:
- go to a room
- make server go offline
- type some messages, you'll be told the connectivty to the server was lost and your messages were saved and will be sent when the server comes back
- close riot
- open riot again
- unsent messages are not shown anymore
- make server come online again
- unsent messages are never sent

**Comment by JuniorJPDJ** [comment]
I will then repaste my message from closed issue:

Riot allows to refresh page when there are messages waiting to be sent.
IMO it should ask for confirmation or at least save them or save them in local storage.

The infobox telling user "messages will be sent when server is available" is confusing, it makes user feel like messages are saved at user side, but it's not the case, you can't close browser nor refresh page.

Just asking user if he really want to close page should be enough.
