### ISSUE TITLE
Failure to remove user avatar is not handled gracefully

### ISSUE THREAD

**Issue by spantaleev** [vector-im/element-web#7202]
I can reproduce this on riot-web `0.16.0`.

The problem happens when going to User Settings and trying to remove your avatar.

If the `{"avatar_url": null}` HTTP request to `/_matrix/client/r0/profile/@user-id/avatar_url` fails (in my case it fails with a 403 error for reasons which are expected and not related to this bug) the riot-web UI would not show any error message.

Even worse, it would display an empty avatar, as if removal really worked (while in actuality, it didn't). I'm guessing the latter is caused by optimistically removing the avatar for better UX, and never restoring it when the HTTP request fails.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/8632
