### ISSUE TITLE
A user tried to reset their password, but the threepid association with their email address was not present in synapse (it was present in sydent).

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7206]
So they weren't able to trigger the reset email.

I'll follow up to see if there was anything out of the ordinary about their signup experience.

**Comment by akirak** [comment]
Thanks for filing this ticket. 

I signed up for my account using Riot web application. I have logged in via the web application of Riot, the Android application, and [matrix-client](https://github.com/jgkamat/matrix-client-el) Emacs client. I joined a couple of channels and sent a few messages, but after clearing my browser cache, I can neither sign in nor reset my password. I cannot sign in via the Android app either.

**Comment by lampholder** [comment]
Hi @akirak - thanks for this additional information. I'll see what we can do.

**Comment by novocaine** [comment]
@lampholder do you think this might still be occurring?

**Comment by turt2live** [comment]
If folks are still running into this, please open a new issue with fresh information.
