### ISSUE TITLE
Some direct chat rooms without avatar show my avatar

### ISSUE THREAD

**Issue by madduck** [vector-im/element-web#7235]
It is my understanding that rooms used for a direct chat (i.e. those with just one other party in the room, not necessarily those tagged direct-chat) will display the name of the other party, as well as their avatar, if those aren't explicitly set.

While this works for most rooms (I am using `/develop`), there are a handful of unnamed rooms that correctly display the name of the other party, but they also show *my* avatar, not theirs. I have tried setting an avatar explicitly (which gets shown), then removing that again, but the result stays the same.

This only applies to some rooms, and I cannot figure out what it is about these rooms that distinguishes them from the other rooms, where the other party's avatar is displayed, as it should.

FWIW, the correct avatar is shown in Riot-Android.

**Comment by bwindels** [comment]
@madduck do you have "Increase performance by only loading room members on first view" enabled in the lab settings?

**Comment by bwindels** [comment]
@madduck do you have the issue only with rooms marked as DM (e.g. appearing under People), non-DM but just with two people in it, or both?

**Comment by tulir** [comment]
I have the issue in 29 out of 114 1:1 rooms. Lazy loading is not enabled.

**Comment by madduck** [comment]
I do not have that lazy loading enabled, and I think clearing the cache would have addressed that.

I only see this in DM rooms. Curiously, when I clear the DM flag, the avatar gets loaded properly. If I then reset the DM flag to on, there is no avatar shown (but just the initial letter in a circle).

**Comment by madduck** [comment]
Restarting the browser, the avatar is now back to *mine* (when it should be theirs). Upon mouse-over, it changes to the initial letter in the room list only. It stays as *mine* in the room header (main pane).

I can also confirm that this is not the case with `/app`.

**Comment by bwindels** [comment]
Ok, thanks for the info. This seems to be wrong m.direct account data, marking some rooms as a DM with yourself. Working on a fix.

**Comment by bwindels** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/706 & https://github.com/matrix-org/matrix-react-sdk/pull/2141 should fix this.

**Comment by bwindels** [comment]
Please reopen if you still see this once the fix is available on /develop

**Comment by dbkr** [comment]
https://github.com/vector-im/riot-web/issues/7269 seems to be this, so re-opening.

**Comment by turt2live** [comment]
Presuming fixed.
