### ISSUE TITLE
Riot is reluctant to reload config.json

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7241]
It seems really keen to rely on the cached version, which is a PITA when you make a change and wonder why it hasn't worked, and could also be a problem if we're hoping for changes made to hosted riot instances to propogate out without advising users to press [whatever key chord is sufficiently refreshy](https://xkcd.com/1854/) to actually pull the fresh config.

**Comment by mrdrogdrog** [comment]
I had the same problem just a minute ago.
My "solution" is a quick & dirty fix:

`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<button onclick="localStorage.clear(); window.location='https://myriothost/#/login'">Click here to reset Riot and delete your loginsession</button>
</body>
</html>`

I placed it in the riot directory so it runs under the same subdomain as my riot instance and can delete the browsers local storage.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/9784
