### ISSUE TITLE
Start a chat with oneself should work or fail more gracefully than 'you hit a bug'

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#7242]
When trying to start a chat with oneself it either fails with the default 'Server overloaded or you hit a bug' popup (if the user has no ongoing 1:1 chats), or one first gets presented the list of existing 1:1s (I think) and then when selecting 'create new chat' get the same default error:

![image](https://user-images.githubusercontent.com/8582858/44795431-8d641c00-aba2-11e8-9ab0-9c4476dd4c4c.png)

Creating a chat with oneself should either create a room with only oneself, or it should fail immediately and with a more explicit error

**Comment by lampholder** [comment]
`p2` 'cause in daily use this I can't imagine this being often encountered

The 'generic failure' message is generally terrible, though :(

**Comment by aaronraimist** [comment]
Related to #4062

**Comment by turt2live** [comment]
Also related: https://github.com/vector-im/riot-web/issues/4933

(maybe even a duplicate if we confirm https://github.com/vector-im/riot-web/issues/4933 as a feature)
