### ISSUE TITLE
Case-insensitive user name search does not work for Russian characters

### ISSUE THREAD

**Issue by cavabanga26** [vector-im/element-web#7247]
The client can not find the user when the "Start Chat" button is pressed, if the first letter does not registry match. The problem is only in Russian, the English is all right.

For example, in the database there is a user "Ivanov".
When a user searches for "Ivanov", the client finds a match, but the user with the small first letter "ivanov" will not be found.

**Comment by lampholder** [comment]
Hi @cavabanga26 - I've modified the issue title - I hope that's accurate.

**Comment by MurzNN** [comment]
Have the same problem, seems fix may be very easy. Can anybody point me to right place in Riot code, where this search is implemented?

**Comment by t3chguy** [comment]
User Directory Search is done server-side so in Synapse over the API: https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-user-directory-search

**Comment by MurzNN** [comment]
Thanks, so this is Synapse issue, here is bug report: https://github.com/matrix-org/synapse/issues/3116

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/matrix-org/synapse/issues/13655

**Comment by MurzNN** [comment]
Seems it's more related to https://github.com/matrix-org/synapse/issues/3116
