### ISSUE TITLE
When starting a new session in a different tab, make it clear the session in the old tab is now invalid and needs to be closed.

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7248]
Benoit saw this after logging in to a different account in a second tab and then going back to the first:

![secondsessionfail](https://user-images.githubusercontent.com/274386/44860098-cfaa5d80-ac75-11e8-92ed-da3af259e520.png)

We only support one session at this point, so we should fail in an obvious way in the first tab, like show the signout/export e2e dialog.

**Comment by t3chguy** [comment]
This got done by monitoring the IDB closed event, the old tab's client will stop and a modal tells the user the db stopped.
