### ISSUE TITLE
Automatically replace emoji shortcodes with emoji

### ISSUE THREAD

**Issue by k80w** [vector-im/element-web#7256]
Currently, sending a message containing `:grinning:` without clicking on the emoji in the autocomplete palette will cause `:grinning:` to be sent in plain text. It would be convenient if, when messages are sent, shortcodes were automatically replaced with emoji.

This should be separate from "Automatically replace plain text emoji"

---

 - emoji syntax

**Comment by sirocyl** [comment]
I'd like to bump this up - I've been experiencing this issue as well, and it just adds unnecessary steps to the emoji userflow - like, ensuring to click on or select an emoji with the TAB key when you've already composed its shortcode in markup.

Attached: an example of what I'm talking about, in a conversation with someone who gave me permission to use this recording.
![riot-example](https://user-images.githubusercontent.com/944067/85961947-f1f98900-b97b-11ea-8610-024bcae13120.gif)

**Comment by martindale** [comment]
Subscribed to this, hoping to see this feature get some love.  As a daily user, would be a huge quality of life improvement.

**Comment by Twi1ightSparkle** [comment]
May also want to add the recognition of for example `(y)` as 👍

**Comment by t3chguy** [comment]
@Twi1ightSparkle that would be a suggestion for https://github.com/milesj/emojibase/ which is the source of all the shortcuts we provide

**Comment by Twi1ightSparkle** [comment]
https://github.com/milesj/emojibase/issues/55

**Comment by hho** [comment]
This is probably my main gripe with Element at the moment.

Especially at the end of a line: I type `:D` – the emoji picker doesn't even open, and if I then hit `Enter`  to send the line, it gets sent verbatim (even though I have "Automatically replace plain text emoji" activated).

This seems like such a basic feature, everyone else gets it right (Slack, Mattermost, Teams etc.).

**Comment by robintown** [comment]
Closing as a duplicate of https://github.com/vector-im/element-web/issues/19178, since that issue has more recent context
