### ISSUE TITLE
Open app when accessing via mobile device

### ISSUE THREAD

**Issue by 8sd** [vector-im/element-web#7258]
It would be awesome if the web pages opens the app (if installed) when accessing the page (eg: riot.im/app) via mobile browser. Otherwise the now shown alert is appropriate.

**Comment by 8sd** [comment]
I think the tactic of [telegram](https://telegram.me/testbot) is quite convenient.
I'm not totally sure how this is achieved.

**Comment by MadLittleMods** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/9814
