### ISSUE TITLE
Edit room directory directly?

### ISSUE THREAD

**Issue by ukcb** [vector-im/element-web#7267]
Please see this issue: https://github.com/matrix-org/synapse/issues/3787

riot-web v0.16.3

**Comment by ukcb** [comment]
I do not want to manage the whole server, just add a remote room to the room_list. The option is there, but it is disabled.

**Comment by aaronraimist** [comment]
Duplicate of #112 but maybe close that in favor of this since it has the 👍s

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/287
