### ISSUE TITLE
scroll bounces around even more than ever when scrollbacking in e2e rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7279]

**Comment by lampholder** [comment]
Interesting - scrolling back in E2E rooms on my electron is really quite smooth now.

@ara4n @dbkr @bwindels - Is there a way we can quantitatively measure 'bounciness' and track it over time?

**Comment by lampholder** [comment]
This is much more noticable without intertial scrolling enabled.

**Comment by grahamperrin** [comment]
Using the scroll bar to scroll, or a scroll wheel?

**Comment by kittykat** [comment]
We couldn't reproduce this issue, scrolling was smooth. Please re-open if you're still experiencing the issue
