### ISSUE TITLE
Changing your device name in DEVICES SETTINGS persists on enter, not on blur or on settings page close.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7285]
It should work like at least one of our other settings fields

**Comment by t3chguy** [comment]
Still a thing even given all the user settings refinements and field changes

**Comment by turt2live** [comment]
see also https://github.com/vector-im/riot-web/issues/8319 and co.

**Comment by uhoreg** [comment]
I think this is fixed by the new redesign, which has :heavy_check_mark: and :x: buttons when you rename.
