### ISSUE TITLE
avatars and url previews should have a lower priority than syncs and messages

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#7292]
I think if we tuned the priority of our http requests as per https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Changing_the_priority_of_HTTP_requests, it might keep things responsive rather than getting blocked behind a queue of slow media requests.

**Comment by t3chguy** [comment]
Safari & Firefox still lack fetch priority support

**Comment by t3chguy** [comment]
We already specify `lazy` loading for avatar imgs
