### ISSUE TITLE
m.direct gets posted to HS on every room member state change in a DM room

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7298]
`RoomView` calls `Rooms.setDMRoom` on every member state change, which always calls `client.setAccountData('m.direct', dmRoomMap)` so account data gets update too often in DM.

**Comment by yannicka** [comment]
Is this still the case?

**Comment by SimonBrandner** [comment]
I don't think I can repro, so I am going to close this. Shout if you disagree
