### ISSUE TITLE
WebRTC calls should be timed out in the UI (and signalling) if the media has disappeared

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#73]

**Comment by SimonBrandner** [comment]
@ara4n, it's not clear to me what this issue is talking about, could you please provide more info?

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
