### ISSUE TITLE
Facebook's preview of Riot is massive

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7308]
I'm not sure if this is something that Riot can actually fix, but it is hilariously large for a preview:
![image](https://user-images.githubusercontent.com/1190097/45273895-f9336800-b471-11e8-9b5d-5b99efd94e26.png)

**Comment by lampholder** [comment]
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Friot.im%2Fapp%2F%23%2Froom%2F!yRBQwAWlyanQJFrMuw%3Amatrix.org

**Comment by turt2live** [comment]
Might be a Facebook thing then. The screenshot is from the pages manager messaging centre inbox thingy.

**Comment by turt2live** [comment]
Fixed with rebrand
