### ISSUE TITLE
Advanced room directories

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#7309]
It would be very useful if the room list to the left, and the room list on community pages, and possibly room lists elsewhere, would be more advanced directories.  Such a directory would be a folder, and a folder can contain rooms or other folders - like files in many file systems.  Folders could have an ordering principle: either the order in which the elements were dragged, or any property whatsoever: so 'order by most recent activity', 'order alphabetically', 'put folders first, and then order by size (number of elements: folders/rooms or users in the room)' - let the user have complete freedom.
Likewise, folders could expand or not, either by user clicking or dynamically ('open if it contains open folders or rooms with unread messages')

**Comment by lampholder** [comment]
This is an interesting idea, but a little hard to visualise.

If I understand correctly then fundamentally this is an ask for a better way to manage/inspect room associations, which is worth exploring.

**Comment by Biep** [comment]
Think of how a file explorer typically has a directory tree to the left.  The room list could be like that - wherever a list of rooms is shown.
In its simplest form, the structure would be made simply by clicking "add folder" in the context menu, and by dragging and dropping things in place.
But dynamic structuring would be much more interesting.  We have a bit of that, in that the room with the most recent action tends to move to the top, and on a community page it seems the rooms are ordered by age.  Giving the user more power over this would lead to a rule-based system, not unlike the way mail filters work in many mail applications.

**Comment by SimonBrandner** [comment]
@Biep, I feel like what you described here is basically the space panel. Do spaces satisfy your needs or would you say they don't fix this issue?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.

**Comment by Biep** [comment]
Sorry - it seems I missed your last reply/question.
My server doesn't support spaces yet, so I can't check what a deep hierarchy of spaces looks like in the room list.  I hope it does look like a file manager's directory tree - which would mean that spaces can replace tags and DM/group chats/low priority and so on.
