### ISSUE TITLE
Riot wants to update, but there is no new version

### ISSUE THREAD

**Issue by jorgeelmundoso** [vector-im/element-web#7310]
### Description

Riot tells me:

```
A new version of Riot is available.
```

but there is no new version available, i am on 0.16.3, which is the latest release while writing.
### Steps to reproduce

I am on OSX desktop with riot 

<img width="1439" alt="screen shot 2018-09-10 at 19 34 45" src="https://user-images.githubusercontent.com/40537777/45313943-9a80f380-b530-11e8-8f1b-500b7e6dafd6.png">

You can see the window that RIOT inserts from time to time, when i press the update button it just closes the application.

I have a firewall in place, so there is the possibility that riot is blocked from communicating with the update server, but this is just a guess.

**Comment by jorgeelmundoso** [comment]
Ok i just downloaded 0.16.3 again and i am a bit surprised:

```
▊ diff /Applications/Riot.app/Contents/MacOS/Riot /Volumes/Riot\ 0.16.3/Riot.app/Contents/MacOS/Riot
Binary files /Applications/Riot.app/Contents/MacOS/Riot and /Volumes/Riot 0.16.3/Riot.app/Contents/MacOS/Riot differ
```

<img width="282" alt="screen shot 2018-09-10 at 19 39 27" src="https://user-images.githubusercontent.com/40537777/45314129-40ccf900-b531-11e8-991f-2a45efc6785c.png">

The about tab states i am running the same version that i just downloaded, still the binaries differ.

Do i miss something here?

**Comment by lampholder** [comment]
@dbkr any clue what's going on here?

**Comment by lampholder** [comment]
FWIW my guess is the two are unrelated - our 'new version' check I believe should be keyed off of version numbers, not the actual binary file content.

**Comment by lampholder** [comment]
P2 rather than P1 just 'cause I've not heard anyone else report this.

**Comment by dbkr** [comment]
0.16.4 is out now so Riot should be updating to that. It's probably not your firewall as the 'latest version' file and the update itself come from the same place, so if it was blocked you'd just get no updates at all. One thing to check is if you're running Riot as a limited user on mac - this has been known to cause problems.

**Comment by wsmwk** [comment]
@jorgeelmundoso, have you seen this problem since?

**Comment by wsmwk** [comment]
@SimonBrandner, the reporter appears to be gone

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
