### ISSUE TITLE
Quoting a codeblock adds spurious backslashes into markdown characters

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7324]
This is very similar to #4809 (and thus entangled with #4674) but not necessarily the same.

If you are in MD mode in Slate and try to quote a message with a code block, then any MD content in the codeblock gets escaped with a backslash, which then leaks into the final message.  We should not be escaping content in code blocks.

Presumably we can just fix this in the MessageComposer code by ensuring that the quote code only applies MD escaping to things which aren't in code blocks - and now that Slate gives us a nice parse tree for finding code blocks, this should be easy?

**Comment by lampholder** [comment]
`major` because even though the feature is far from completely broken, it is particularly visible in a common use case

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by yannicka** [comment]
I can't duplicate the issue on Riot Desktop 1.6.0.

**Comment by t3chguy** [comment]
Assuming fixed
