### ISSUE TITLE
If you try to launch riot/web whilst your server is 503ing it panics with "Unable to restore session"?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7329]
This may be coincidence, but:

<img width="2032" alt="screenshot 2018-09-13 at 14 28 02" src="https://user-images.githubusercontent.com/1294269/45491328-617b9580-b761-11e8-876d-c577436305ed.png">

is not ideal at all. also, shouldn't it be giving me the option to export keys?

**Comment by ara4n** [comment]
now the server's back, everything's recovered fine.

**Comment by turt2live** [comment]
This needs some design feedback for what we should say/do instead. The dialog comes up from a generic error handler during startup, of which there's nothing we can make optional. This means if your homeserver 503's a request for push rules, you're unable to start Riot. It's true that your session is not corrupted though, so we are needlessly scaring users.

**Comment by novocaine** [comment]
Desired behaviour is to show a general error message if a 5xx error is received from the home server during init.

Suggested wording:

> We encountered an error loading Element while communicating with your home server. 
>
> The problem may be temporary - try logging in again in a few minutes.
>
> If the problem persists, check the address of your home server is correct, or contact your home server's administrator.

**Comment by novocaine** [comment]
Desired behaviour is to show a general error message if a 5xx error is received from the home server during init.

Suggested wording:

We encountered an error loading Element while communicating with your home server.

The problem may be temporary - try logging in again in a few minutes.

If the problem persists, check the address of your home server is correct, or contact your home server's administrator.

**Comment by t3chguy** [comment]
> The problem may be temporary - try logging in again in a few minutes.

if they're starting the app already authenticated then this may scare them because logging in means new e2ee identity

**Comment by Palid** [comment]
@ara4n at which point should this scary screen appear? I can't figure out how to reproduce it locally.

**Comment by novocaine** [comment]
> > The problem may be temporary - try logging in again in a few minutes.
> 
> if they're starting the app already authenticated then this may scare them because logging in means new e2ee identity

Removed reference to logging in

**Comment by Palid** [comment]
Can't reproduce anymore, would require losing your keys from local storage and server going 503 at the same time, which at that point would show this scary and real message.
