### ISSUE TITLE
Impossible to backfill over federation on joining a room on a new server

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7335]
Repro steps (I hope):

 * A room exists like #seaglass:matrix.org
 * A user joins it from a virginal HS (e.g. `@neil:sandbox.modular.im`)
 * They do not yet backpaginate any history for that room over federation for whatever reason
 * Another user joins the room from the same HS (e.g. `@matthew:sandbox.modular.im`)
 * The /sync as the new user joins it does not include a backwards pagination token at all (we think, assuming this is not a js-sdk bug).
 * Therefore the new user can never paginate backwards in the room to pull in old history.

**Comment by ara4n** [comment]
Looks like user 1 also can't back-paginate at all. So this is a federation bug somehow.

**Comment by ara4n** [comment]
However, on clearing the cache (by logging in with the same account on a new riot), back pagination works fine - we get a prevbatch on the initial sync for the room which we can follow back via /messages into the night.

**Comment by ara4n** [comment]
(this happened at the same time as https://github.com/vector-im/riot-web/issues/7332)

**Comment by ara4n** [comment]
@bwindels this is screaming out for an E2E test

**Comment by ara4n** [comment]
(although tbh it can probably also be reproduced via sytest if it's really a federation-only bug)

**Comment by bwindels** [comment]
Matthew said: i synced with Erik on that at lunch btw, and it became obvious that the reason we couldn't repro that is because the room has to start off federated

**Comment by t3chguy** [comment]
If you are still experiencing this, please open an issue in https://github.com/matrix-org/synapse/
