### ISSUE TITLE
Riot does not handle invalid config.json particularly cleanly

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#7338]
When editing a config.json for riot, if a typo is introduced (such as a missing comma), when the riot-web instance is refreshed in browser, then the page just goes blank with no user-facing error saying "Bad config, please talk to your admin" or something.

The error does exist in the console, but somehow managing the error into an informative message would help (mainly to prevent compulsive "refresh the blank page because the network has gone" syndrome)

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/pull/6844/commits/026a0722786ebd04a5e695c9899f694151d146b8 makes it show an error and should be safe to cherry-pick out

**Comment by turt2live** [comment]
we fixed this
