### ISSUE TITLE
rooms without canonical aliases published in a group directory are unjoinable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7339]
as riot apparently ignores non-canonical aliases. we should surely fall back to non-canonical aliases if the canonical alias is missing

**Comment by ara4n** [comment]
So there are at least 5 problems here:

* [ ] We are no longer defaulting the canonical alias of a room to the first alias that is set. 
* [ ] Somehow Gnosis were able to publish rooms in their directory without setting an alias at all, which means they can't be joined over federation.
* [ ] Apparently you can publish rooms in a group without canonical aliases, which means they can't be joined over federation
* [ ] The groups API only ever returns a canonical alias for a room in your `/groups/+group:example.com/rooms` response, so if one isn't set, you can't join it over federation, even if it has aliases.
* [ ] The JS SDK puts the result of the /groups/rooms API into a GroupRoomType object (but doesn't check the type), and then coerces that into a RoomShape object (without checking the type).  The former doesn't have an aliases field; the latter does, but it's too late by that point.

It would be sufficient to fix the first 3 here, i think.

**Comment by turt2live** [comment]
iirc the conclusion on the remainder of this is to fix the groups stuff relying on the canonical alias so much. This probably requires a change to the API to return any alias it can find, but also potentially minor changes in Riot to have it understand this.

**Comment by turt2live** [comment]
It looks like https://github.com/matrix-org/matrix-react-sdk/pull/2173 is the place that fixes a bunch of this. @ara4n what's the status on this?

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
