### ISSUE TITLE
Invite unbanned users over federation - user can't join, user can't reject invite.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7362]

**Comment by lampholder** [comment]
I was trying to invite isobelle.mtp:matrix.org to a room on lant.uk, but she'd been banned previously.

I unbanned her, then invited again - invite seemed to work from the invitor's perspective.

isobelle.mtp saw the invite, but could neither accept nor reject it:

```{"errcode": "M_BAD_STATE", "error":"Cannot join user who was banned"}```

**Comment by t3chguy** [comment]
This is a Synapse issue, not an Element one, feel free to open upstream
