### ISSUE TITLE
Onboarding should prompt users to set an avatar

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7374]
In ILAG, we should prompt for an avatar about the same time that we set a password.  We got this right pre-matrix.

Alternatively, libravatar?

**Comment by lampholder** [comment]
It should certainly be part of the flow.

Seeing as [rumours of its death](https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/) were [premature](https://blog.libravatar.org/posts/Libravatar.org_is_not_going_away/), I think it would be nice for us to [run our own Libravatar node](https://wiki.libravatar.org/running_your_own/) - I'd like to see us cross-pollenate more with other decentralised tech.

**Comment by t3chguy** [comment]
This is done now

Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5383
