### ISSUE TITLE
Riot is not respecting audible and call settings

### ISSUE THREAD

**Issue by gerroon** [vector-im/element-web#7382]
Hi

The Linux version of Riot desktop is not respecting the audible notifications and the p2p call settings. 

I disabled audible notifications and p2p calls and I still get loud notifications with messages and calls, and I still get p2p calls. It seems to me that the settings are not respecting for such things. 

I do not have any "noisy" notifications enabled either. I also tried enabling and disabling back with no luck

Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
matrix-react-sdk version: <local>
riot-web version: 0.16.4
olm version: 2.2.1

**Comment by lampholder** [comment]
I wasn't able to reproduce this, but (anecdotally) I feel like my Riot client might have ended up in a similar state previously.

**Comment by aaronraimist** [comment]
In Firefox on macOS, it plays audio for notifications whether or not the audible notification setting is enabled. It works correctly in Safari.

**Comment by gdvine** [comment]
Cannot disable some audible notifications in macOS Element desktop v1.7.7.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15591
