### ISSUE TITLE
Clicking on an encrypted image before it has decrypted yields a lightbox with a white border

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7410]
![image](https://user-images.githubusercontent.com/1190097/46166535-ab2faa00-c250-11e8-912f-3aae2fdd52e3.png)

This is after clicking on the image. The image itself loaded before the screenshot could be taken, and is blurred in the background.

1. Send a large image from another account in an encrypted room
2. On the receiving side, click where the image would be (the spinner)
3. Receive bordered lightbox

**Comment by lampholder** [comment]
In this case the 'Download this file' link doesn't do anything, either.

**Comment by turt2live** [comment]
we now have a loading animation
