### ISSUE TITLE
Drop file here to upload does not work in Safari

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#7420]
### Description

Can't drag and drop a file into Safari

### Steps to reproduce

- Open Riot in Safari
- Drag a file over the room

Describe how what happens differs from what you expected.

Riot should show "Drop file here to upload", instead nothing happens and I can't drag the file in to upload it.

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Safari Technology Preview Release 66 (Safari 12.1, WebKit 13607.1.7.2) 
ALSO 
Safari Version 12.0 (13606.2.11)
- **OS**: macOS 10.13.6
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment]
Looks like Safari doesn't support https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList. Other websites seem to support drag and drop file in Safari though so I'm going to look in to how they do it.

**Comment by t3chguy** [comment]
What is happening is for Privacy Safari is saying 0 files are being dragged on dragOver event, other browsers say quantity and type here. https://stackoverflow.com/a/34866211 

WhatWG agrees https://html.spec.whatwg.org/multipage/dnd.html#the-datatransfer-interface

> This version of the API does not expose the types of the files during the drag.


Instead we can check the `types` property.
