### ISSUE TITLE
Blacklisted devices continue to spam you with keyshare reqs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#7423]
ネプギｱ (nepugia) says: Could the key verification popup be fixed? I blacklisted my other device and the popup keeps spamming me (incidentally when someone sends me an e2ee message) (as a consequence the popup appears usually while i am typing (and the stupid dialog accepts keyboard input, ffs)).

**Comment by lampholder** [comment]
So, two things:
- [ ] silently reject key share requests from blacklisted devices 
- [ ] reduce the likelihood of dismissing the keyshare popup dialogue by mistake

The first seems very tractable.

The second is tricky, though we can't be the first people in the world to encounter this problem. How do we reconicle keyboard usability with not accidentally misinterpreting keypresses intended for the composer? Some sort of minimum visibility time on the modal?

**Comment by kittykat** [comment]
We don't support blacklisting any more, but rather have the option of logging out from other devices which we don't want to verify.
