### ISSUE TITLE
I have to click "Decrypt" to then download an image when it appears to have already been decrypted

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7431]
This is more of a usability thing: an image appears in my encrypted room and looks like it has already magically been decrypted for me (because I can see it). If I want to download it though, I have to click decrypt *then* download (or open the lightbox). From my perspective as a user, it should have already been decrypted.

My hypothesis is that thumbnail has been decrypted (because I can see it) but the underlying file has not been, hence the link. There might be better UX we can apply here, such as hiding the decryption behind a plain download button?

**Comment by lampholder** [comment]
Yeah, your hypothesis is correct.

There's certainly scope for improved UX here.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/9035

**Comment by turt2live** [comment]
We now have a single button for this.
