### ISSUE TITLE
Should be able to dedupe editor state across all rooms

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7434]
A brief look through my localstorage reveals a ton of editor_state values - most of which look identical to each other. Deduping this would save roughly 135kb (not a whole lot, but still sizable)

```javascript
var editorStateLen = 0; for(var key in localStorage) { if (key.startsWith("editor_state")) { editorStateLen += localStorage.getItem(key).length; } } console.log(editorStateLen);
// > 135973
```

**Comment by lampholder** [comment]
Even with lazy loading enabled my riot uses ~350MB RAM :D 

Hopefully one day we will be at the point where 135kb of wasted memory is worth saving, but it might be a little while yet :P

**Comment by t3chguy** [comment]
We now only store the state if it is non-empty
