### ISSUE TITLE
Permalink to an image covered the top half of the image

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7445]
Observed on riot.im/develop and made sure I was scrolled to the bottom of the timeline before clicking the permalink in another room. The image itself was well above the fold.

Viewport was 1920x1080 and the thumbnail was 337x600. Original image size was 2160x3840 (portrait photo from a phone).

**Comment by SimonBrandner** [comment]
@turt2live, is this still relevant?

**Comment by turt2live** [comment]
let's just say no - I have no idea what it's talking about
