### ISSUE TITLE
Trivial differences in room searching hide rooms from groups

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7461]
![image](https://user-images.githubusercontent.com/1190097/46515466-35fc4000-c821-11e8-9421-97a4f00e63c5.png)

![image](https://user-images.githubusercontent.com/1190097/46515468-3a285d80-c821-11e8-8ec0-121d7d528a7d.png)

**Comment by lampholder** [comment]
Sorry, I don't understand this one... I can see the differences, but _where_ are you seeing them?

**Comment by turt2live** [comment]
Trying to add a room to my group's homepage

**Comment by turt2live** [comment]
Spaces do this differently.
