### ISSUE TITLE
Avatars getting switched around between rooms?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#7471]
@ara4n reports rooms having incorrect avatars, possibly getting the avatar from a different room

**Comment by bwindels** [comment]
any reason to suspect this is LL related? Or just added the tag because it might be?

**Comment by bwindels** [comment]
no console errors said M. when it happened

**Comment by lampholder** [comment]
Media repo giving different images for different size thumbnails of the same media item :(

**Comment by dbkr** [comment]
I'm going to assume this is fixed now...
