### ISSUE TITLE
Clicking autocomplete name suggestions doesn't work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7491]
In the composer, type a name leading to 2 or more results. Left click the second result - nothing happens. Broken since 0.16.4 at least, and reproduced on develop

**Comment by aaronraimist** [comment]
This is what my current experience is like on /develop in Firefox and Safari. I can click any suggestion and it works as long as I never press tab. The end of the gif shows me tabbing to the third suggestion and then clicking the second and that is where it is broken for me.

![autocomplete](https://user-images.githubusercontent.com/5855073/46910665-b865bd80-cf0d-11e8-8b5a-bd5bb9ef7676.gif)

**Comment by turt2live** [comment]
Hmm. Might be a Chrome issue only then

**Comment by turt2live** [comment]
@bwindels has some notes here: https://github.com/vector-im/riot-web/issues/10172#issuecomment-507168537

**Comment by SimonBrandner** [comment]
@turt2live, is this still a problem for you? I can't repro

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
