### ISSUE TITLE
At times riot-web is unresponsive and hides characters written. 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#7493]
In the newish version of riot-web it is sometimes unresponsive and hides characters written . 

I know testing/buster isn't supported but it largely works apart from the irritant shared above. This has happened quite a few times today itself otherwise wouldn't have reported. 

Using riot-web 0.16.5 

```
-- System Information:
Debian Release: buster/sid
  APT prefers testing-debug
  APT policy: (500, 'testing-debug'), (500, 'testing'), (100, 'unstable-debug'), (100, 'experimental-debug'), (100, 'experimental'), (100, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-3
ii  libnss3           2:3.39-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information
```

**Comment by shirishag75** [comment]
exactly. Thank you for being articulate. For me though the session either hangs or crashes. It's only in the next session, I come to know that the keypresses were there and is in some sort of probably 'temporary cache' or something and I can continue. When keypresses vanish or disappear I just can't use riot, it's simply unresponsive and unsuable :(

**Comment by shirishag75** [comment]
As well as the 1.0.1 series as well. So the issue still continues.

**Comment by t3chguy** [comment]
This issue is likely no longer relevant due to how much the app has changed
