### ISSUE TITLE
Clicking red X in upper left corner of MacOS Riot app makes app blackscreen

### ISSUE THREAD

**Issue by 4onen** [vector-im/element-web#7495]
### Description

As the title says, clicking the red X button causes the app to enter a black-screen state, instead of exiting. 

### Steps to reproduce

- Launch Riot application
- Enter any room
- Maximize application
- Click red X in upper left of Riot 

I expected this to close the window, removing its maximized location. Instead, the window remained maximized and became a completely blank solid black. (State can be cleared by bringing the mouse to the bottom of the screen, bringing up the dock, and clicking the riot icon.)

Log: not sent. Is that necessary for such a simple bug?    

### Version information

- **Platform**: Desktop
- **OS**: macOS Sierra 10.12.6
- **Version**: 0.16.5 

Low priority, but I ran into it within thirty seconds of installing and thought y'all should know.

**Comment by lampholder** [comment]
I can reproduce this.

**Comment by t3chguy** [comment]
@lampholder can you still reproduce this?

**Comment by aaronraimist** [comment]
@t3chguy I can. (to be clear it only happens if the app is in full screen mode)
