### ISSUE TITLE
[Feature Request] Hold/Join button when someone calls while on call

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#7545]
I'm in a call on riot, then someone calls me, on riot.

Options? Answer/Reject

What happens when I Answer? Other call hangs up.

Can we get an option to put the first call on hold? And/or Join? And then other related hold functionality?

**Comment by BloodyIron** [comment]
Oh, also, this request is for Desktop/Web/Android/iOS too ;)

**Comment by SimonBrandner** [comment]
Should auto-hold now or whatever
