### ISSUE TITLE
Redesign: implement top-left menu (without communities)

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7562]
- show currently selected community
- add community settings and invite options
- add toggles for show historical/low-pri rooms

might depend on reworking communities so we can assume there is default community?
or do we add a "fake" my stuff community?

Questions:
what does "show profile" do?

**Comment by bwindels** [comment]
After talking with Nad, we leave out community stuff and the Show profile option for now, we keep the current behaviour where it shows the users in the top left and not the community.

**Comment by bwindels** [comment]
https://github.com/vector-im/riot-web/issues/8010 as well

**Comment by bwindels** [comment]
important to fix cursor on menu items

**Comment by turt2live** [comment]
We're exploring a bunch of options in this area - I don't think it's quite ready to get its own issue nowadays.
