### ISSUE TITLE
Redesign: timeline: timestamp placement

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7564]
the first message in a group has the timestamp after the sender name; subsequent messages in a group and /me actions show the timestamp after the message, but only on hover.

**Comment by bwindels** [comment]
Make sure we fix #2284 in the process

**Comment by turt2live** [comment]
I'm going to close this in favour of modern tracking issues if/when we get them. If people have suggestions for modernized UX, please open new issues for consideration.
