### ISSUE TITLE
Redesign: timeline: implement new file transfer UX

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7565]
- [ ] show preview of images in timeline while uploading
- [ ] add caption
- [ ] show download button on hover
- [ ] add file icons for common extensions
- [x] update design of upload dialog.
- [ ] from #8508 - ensure the progress bar doesn't butt right up against the right hand side

Questions:
 - do we have design for multiple images? What if images and other files are mixed? Revert to just showing as file icons?

**Comment by MurzNN** [comment]
> do we have design for multiple images?

At now Matrix don't allow attaching multiple images to single `m.room.message` event, only sending each image as separate `m.image` event (without text). For right implementation will be good to extend `m.room.message` via message attachments, here is my feature request about this: https://github.com/matrix-org/matrix-doc/issues/2289

**Comment by turt2live** [comment]
We've since modified the appearance here. If there's further work to be done, we can track it with new issues. If people have suggestions for such UX, please open new feature requests for consideration.
