### ISSUE TITLE
Redesign: timeline: message states

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7571]
- [ ] design all states for all contexts (e2e etc) with all content types (images/syntax/etc)
- [ ] consider compact mode
- [ ] consider increasing font size, and adding font size setting
- [ ] show sending / spinner next to message
- [ ] show resent / cancel options next to individual message
- [ ] restyle option at bottom of timeline to cancel / resent all failed messages.

**Comment by turt2live** [comment]
I'm going to close this in favour of modern tracking issues if/when we get them. If people have suggestions for modernized UX, please open new issues for consideration.
