### ISSUE TITLE
Redesign: update message style

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7573]
- [ ] update color scheme of code snippets
- [ ] update general code block looks / bg color, ...
- [ ] quote
- [ ] reply style
- [ ] sender name and avatar are top-aligned

**Comment by MadLittleMods** [comment]
@bwindels Is this still relevant after the iterations in the past 2 years?

**Comment by robintown** [comment]
Closing due to lack of info and this almost certainly not being relevant anymore
