### ISSUE TITLE
Redesign: composer: restyle autocomplete popup list

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7577]

**Comment by lampholder** [comment]
Need to decide exactly how the keyboard is going to interact with the autocomplete suggestions:
- how do you navigate the options?
- how do you dismiss the autocomplete?
- etc.?

**Comment by turt2live** [comment]
I'm going to close this in favour of modern tracking issues if/when we get them. If people have suggestions for modernized UX, please open new issues for consideration.
