### ISSUE TITLE
Redesign: memberlist

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7587]
- [x] make invite button full width on top
- [x] move filter field to bottom and add icon
- [ ] font changes
- [ ] margins
- [ ] iterate on the invite button style, as it's visually heavy
- [ ] confirm how we want to invite users when the right panel is closed
- [ ] ~~add status dot, style presence info~~ not important for mvp

**Comment by bwindels** [comment]
it's not in zeplin, does that means it's not approved yet?

**Comment by turt2live** [comment]
I'm going to close this in favour of modern tracking issues if/when we get them. If people have suggestions for modernized UX, please open new issues for consideration.
