### ISSUE TITLE
Redesign: files panel

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7588]
- [ ] restyle
- [ ] list and "grid" (large image preview) view
- [ ] add file icons
- [ ] add filter field

**Comment by bwindels** [comment]
the files panel actually doesn't show non-image files at the moment

**Comment by bwindels** [comment]
I assume we would use the same icons for files in the main timeline.

**Comment by turt2live** [comment]
I'm going to close this in favour of modern tracking issues if/when we get them. If people have suggestions for modernized UX, please open new issues for consideration.
