### ISSUE TITLE
Redesign: mentions panel

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7594]
- restyle
- add "All rooms" option

**Comment by bwindels** [comment]
we don't currently support showing notifications for all rooms

**Comment by MadLittleMods** [comment]
Is the mentions panel the "Notification panel" nowadays (accessed from the bell icon in the top-right)?

The notification panel nowadays shows mentions across all of your rooms. Perhaps this can be closed now?

**Comment by SimonBrandner** [comment]
> Perhaps this can be closed now?

Yeah, probably
