### ISSUE TITLE
Suggestion for bridging chats!

### ISSUE THREAD

**Issue by Warfields** [vector-im/element-web#7600]
Matter Bridge, it links:

    Mattermost 3.8.x - 3.10.x, 4.x, 5.x
    IRC
    XMPP
    Gitter
    Slack
    Discord
    Telegram
    Hipchat
    Rocket.chat
    Matrix
    Steam
    Twitch
    Ssh-chat
    Zulip

https://github.com/42wim/matterbridge

**Comment by lampholder** [comment]
I don't think this is something the core team will be able to look at any time soon, but this would be a neat thing to exist if somebody felt keen :P

**Comment by t3chguy** [comment]
Bridges for many of these things already exist around the fediverse, e.g https://t2bot.io/ has some, Element is just a Matrix client, bridges run on Matrix servers.
