### ISSUE TITLE
Redesign: timeline: read receipt placeholder

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7601]
Currently no design for read receipts, will they change?

**Comment by bwindels** [comment]
> Eric: is it known that when you expand list of read receipts you can't actually click on most of them since the hover background of a message is over the receipts

![image](https://user-images.githubusercontent.com/274386/47574661-9fa6d000-d92f-11e8-8139-c0fd7b611d1d.png)

Maybe this is something we can fix when we redesign this.

**Comment by aaronraimist** [comment]
Some issues to consider when redesigning them: https://github.com/vector-im/riot-web/issues/5746 https://github.com/vector-im/riot-web/issues/4377 https://github.com/vector-im/riot-web/issues/9595 https://github.com/vector-im/riot-web/issues/8716

**Comment by robintown** [comment]
A new read receipt design has been implemented in https://github.com/matrix-org/matrix-react-sdk/pull/8389
