### ISSUE TITLE
Weird error trying to leave a room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7628]
![image](https://user-images.githubusercontent.com/1190097/47676495-64e8a600-db82-11e8-8527-2db98ba4c892.png)

**Comment by lampholder** [comment]
Do you know what you did to trigger this? Is it reproducable?

And it really is a terrible error message :(

**Comment by turt2live** [comment]
I just clicked "Leave room" from the context menu. Unfortunately I haven't seen it since.

This might be something to close as "weird transient error that probably doesn't happen".

**Comment by turt2live** [comment]
I don't know
