### ISSUE TITLE
Trim replies after some amount

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7633]

**Comment by turt2live** [comment]
Here's the bottom quarter of a reply:
![image](https://user-images.githubusercontent.com/1190097/47732581-1db6ef80-dc2c-11e8-945c-127d5c2d78fc.png)

**Comment by tulir** [comment]
The reply content thing should just be significantly simplified:
* Max one row of text (replace images with the fallback-style "Sent an image" or something)
* Click to jump to message
* Avatar not really necessary, though it could be included

**Comment by lampholder** [comment]
I think a single row of text might be too limited, but unlimited obviously has drawbacks :)

Definitely one to add to the UX rework queue.
