### ISSUE TITLE
Migrate away from browser-request

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7634]
It's ancient and not really maintainable as thing we should be using the future.

When migrating away, consider the nightmare that is https://github.com/vector-im/riot-web/issues/7620, which may require https://github.com/request/request/pull/3053 (or similar). At the time of writing, there is an unknown piece of `request` (or its dependencies - browserified or otherwise) besides the one in the PR that is causing promises to freeze when dealing with `request`. This is assumed to be something preventing the callback being called, therefore preventing the promise from resolving.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-js-sdk/issues/801
