### ISSUE TITLE
Timed message delivery (scheduled)

### ISSUE THREAD

**Issue by gerroon** [vector-im/element-web#7648]
Not sure if this is a Synapse issue or Riot issue but it sounds like a client thing to me.

The idea is to time a message for delivery, the reason is that sometimes you know the person you are sending is busy at the moment and they wont pay attention to your message but you might guess when they will be available so you time your message, and the message is delivered at that time. It will still look like you just sent a message but it will have a tag with timing of it so you know it still is not delivered.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-meta/issues/309
