### ISSUE TITLE
[Feature Request] Add "clear chat history" option or multiple message selection

### ISSUE THREAD

**Issue by adalvigi** [vector-im/element-web#7660]
### Description

I find it very, very useful that we can delete an old conversation for all devices and users (at least in direct messages or chats where we are admins) by just deleting the messages, but it's very hard to do if we have to delete one at the time. Could we have either an option to clear the entire history for a chat (also deleting it for the other user)  or simply the option to select some messages and delete them all at once? It would make it all a lot faster to do!

### Version information

This holds true for at least Windows, Linux and Android.

**Comment by BurnyBoi** [comment]
Would be nice if this could be done per-user as well. For example, being able to say "redact the last X messages sent by me in this room"

**Comment by lampholder** [comment]
l think this could be valuable (not least for moderators who might want to redact everything an individual user has 'contributed' to a room) but it could be fiddly to implement on top the 'redaction' feature as it is today (each redaction is another event written to the timeline and is written to redact a specifed event, so the client would have to page through the room history finding all the relevent event ids and then write redactions for each, which could place a lot of load on the server).

**Comment by csculley** [comment]
Adding on to this, Matrix just recently merged in mass redactions to the api: https://github.com/matrix-org/matrix-doc/pull/2244

**Comment by maisiliymBridj** [comment]
Wait long enough and innocents will be imprisonned/tortured/killed over the matrix messages they couldnt delete. Add a 'clear history' button on the first day you use the client! Anyone and their dog knows that! What the fuck!? Get your fucking act together!

**Comment by 532910** [comment]
multiple message selection should not be only for deletion but also for forwarding for example

**Comment by PhieF** [comment]
a /clear option would be great, indeed !

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/3689. Scream if you disagree
