### ISSUE TITLE
Clicking Settings gear throws error if guest user on HS where registration is disabled

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#7663]
### Description

If you are using Riot as a guest user (perhaps by clicking "Try the app first") on a homeserver where registration is disabled, clicking the Settings gear icon will do nothing.

Riot tries to POST to `https://localhost:8448/_matrix/client/r0/register`, but receives a 403 error.

The following error is logged to the console:

```
Unhandled rejection M_UNKNOWN: Registration has been disabled
```

I am assuming this is caused by the `SetMxIdDialog` modal dialog (since we are in guest mode) trying to query registration methods, since that dialog would appear after clicking the Setting gear when registration is possible.

### Steps to reproduce

- Start a local HS that allows guest access but disables registration
- Start a local Riot for that local HS
- Using the local Riot, try out the app as a guest user
- Click the Settings gear icon

Instead of displaying the Settings panel as expected, nothing happens, and the error above is logged.

### Version information

- **Platform**: web

- **Browser**: Firefox 65
- **OS**: macOS 10.13.6
- **URL**: Local Riot build from develop branch at eef4f7c4

**Comment by kittykat** [comment]
I'm going to close this issue for now as the settings gear now pops up a nice dialog asking user to log in:

![Screenshot from 2021-11-04 15-38-14](https://user-images.githubusercontent.com/51663/140362216-e106bf64-089e-4b42-bc1d-5a6ef50e6282.png)
