### ISSUE TITLE
Registration SMS not delivered to France - classify SMS as non-commercial

### ISSUE THREAD

**Issue by neitsab** [vector-im/element-web#7672]
### Description

When registering an account on the default home server via the Android/F-Droid application, 2FA SMS is never received on a French number. Country code was correctly detected, email token was correctly received but three attempts at SMS verification of number never succeeded.

Operator is Bouygues Telecom.

### Steps to reproduce

- install application from F-Droid
- click on Register
- at the optional stage of email/phone number linking, add a French number like 667889955 (without leading 0) or 0667889955 (the leading 0 being correctly detected and removed in favor of +33)
- click OK and wait forever to receive the SMS without any sign of failure.

Log: not sent    

### Version information

- **Platform**: mobile (Android 6.0.1/CyanogenMod 13.0/F-Droid) version 0.8.18 (F-d9d8db49) 

**edit**: just tried via the web version of Firefox for Android and it is the same result, SMS is never received despite correct number (*e.g* +33667889955).

Thanks

**Comment by lampholder** [comment]
I just looked into this and found what might be the problem, Bouygues Telecom (and SFR) will only accept commercial messages for delivery between 8.30am and 8pm local time Monday to Saturday. Were you trying to register outside of these hours? 

Obviously our 2FA message is _not_ a commercial message, but I'd guess the necessary configuration hasn't been done with the carrier to get our messaging correctly classified.

If you were trying to register outside of these hours, can you try again between these hours and let me know how you get on? Thanks!

**Comment by neitsab** [comment]
Hi, sorry for the long delay, I was AFK for a few months.

You were spot on, as soon as I tried during daytime I correctly received the 2FA message. So your analysis is correct.

Thank you for the help!
