### ISSUE TITLE
The search field on the top left is too large

### ISSUE THREAD

**Issue by rubo77** [vector-im/element-web#7679]
The search field on the top left of the Riot app really is too large. On low resolution screens, you use a 10th of the height only for this search field and it is not even all clickable. 

I can think of two solutions:

**Comment by rubo77** [comment]
Make the search box only as high as needed to save the height to show more rooms.

**Comment by rubo77** [comment]
2. Make the space around the Search field also clickable by the mouse, so you don't have to "aim" the input field directly.

This could be done by a `<label>` html tag

**Comment by aaronraimist** [comment]
Can you post a screenshot of what you are seeing?

**Comment by turt2live** [comment]
There's a ton of whitespace around the search field: 
![image](https://user-images.githubusercontent.com/1190097/48501736-221e0380-e7fb-11e8-9994-43825b22e738.png)

**Comment by lampholder** [comment]
There's different (smaller) styling associated with this filter in the redesign, so I think we needn't worry about this for now.

**Comment by turt2live** [comment]
We've since redesigned this component.
