### ISSUE TITLE
Make my own messages more visible

### ISSUE THREAD

**Issue by awabik** [vector-im/element-web#7687]
### Description
When talking with people with no avatar, and when I myself have no avatar, then my general impression looking at the conversation is that it's not very readable. I can't quickly (meaning, at first glance at any point in the conversation) identify my own messages.

I'd suggest implementing an optional change of style of the conversation window, to make my own messages more visible. This might be solved by giving other background color to my own messages, or different alignment (my own messages on the left, all others on the right?)

This is what any user of literally every other messaging application would expect. This might not be a top-prio for chats with multiple participants, but two-person rooms would gain much better user experience with this.

### Version information

- **Platform**:  all (Desktop Linux, Desktop Windows, Web, Android)

**Comment by lampholder** [comment]
One to consider for DMs under the redesign.

**Comment by martindale** [comment]
This should have a dedicated view, "My Messages", which enumerates all messages sent by the current user (and their replies).  I'd even go so far as to set this as my personal default...
