### ISSUE TITLE
Messages missing from chat, but still show in search

### ISSUE THREAD

**Issue by BurnyBoi** [vector-im/element-web#7688]
### Description
Messages from June 16th, 2018 to November 10th, 2018 are missing from #offtopic:matrix.org. However, if I search for them, I am able to see them, so the messages are definitely still there.

### Steps to reproduce
- Scroll up to the first message sent on November 10th, then look at the date of the message above it, and you'll see it is June 16fh. Then, search for a message sent between those dates (ex. search "newspaper", and you'll see some of the messages sent in September and October of 2018). 

## Describe how what happens differs from what you expected.

If the messages between these dates still exist, then they should show sequentially.

Log: sent/not sent?   Will include log if necessary, but this seems easy to reproduce. Let me know

Gap between messages:
https://imgur.com/a/UcDdJjw
https://imgur.com/a/q6AL0xI

Messages between these dates still shows in the search:
https://imgur.com/a/eRE8t8x

### Version information

- **Platform**: web
- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: https://riot.im/app/#/room/#offtopic:matrix.org

**Comment by BurnyBoi** [comment]
Just to expand on this, I'm on another computer now, and the gap is between June 16th and November 13th on this other session.

**Comment by lampholder** [comment]
Is this on matrix.org or another homeserver?

**Comment by BurnyBoi** [comment]
This is happening on matrix.org for me

**Comment by ptman** [comment]
We're seeing a problem with web riot now, where the first message after being idle doesn't make it to the recipient, but if the browser tab is refreshed, the message is shown. On our own hs, running synapse 0.99.4 via docker

**Comment by SimonBrandner** [comment]
Are you still seeing this?

**Comment by BurnyBoi** [comment]
> Are you still seeing this?

As far as the original issue: That original room is long gone at this point and so many room versions and software updates have come out since then that I don't think this issue is applicable any more.
