### ISSUE TITLE
Look at the UX for new/returning users to riot.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7691]
We want returning users to have a clear path to login.

We want new users to have a clear path to registration should they want it - we might expect most new users to click around a bit and go through ILAG, but the registration path should be obvious if they want to head straight for it.

Things to consider:
- the buttons should be easy to find
- they should always be visible - i.e. their visibility should not be dependent upon:
    - the size of the screen
    - whether the roomlist is expanded/contracted
    - whether the central pane is displaying a composer
    - etc.

**Comment by the-moog** [comment]
The lack of progress in this area is the reason that we are struggling to get adoption after over a year.  People fine the onramp just too confusing.  #10026 is the icing on the cake as (from a user perspective) they just get stuck in a loop.  Registration should be trivial.

**Comment by nadonomy** [comment]
Closing this issue in lieu of organising more specific ones speaking to specific user journeys/contexts.
