### ISSUE TITLE
[Feature request] create a simple talking/help bots

### ISSUE THREAD

**Issue by warshell** [vector-im/element-web#7702]
I saw the documentation on bots and i think the ability to create a simple talk bot like in #slack would be nice. thx

**Comment by turt2live** [comment]
Can you elaborate on what a "talk bot like in #slack" is?

**Comment by devcline** [comment]
https://get.slack.help/hc/en-us/articles/202026038-An-introduction-to-Slackbot

**Comment by lampholder** [comment]
This would be nice to have; this is more of a matrix request than a Riot-specific one, but I'll leave it here for now.

**Comment by ltfschoen** [comment]
https://github.com/Giveth/giveth-bot

**Comment by t3chguy** [comment]
We had such a bot with riotbot and the general consensus was negative
