### ISSUE TITLE
Custom homeserver URL doesn't behave sensibly if no protocol is specified.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7706]
![image](https://user-images.githubusercontent.com/1922197/48550735-7d1f2b80-e8cb-11e8-8eda-122f078760e6.png)

If you don't specify a protocol (http/https) for the custom homeserver URL, Riot just assembles the URL it's poking as a relative path (so if you're using https://riot.im/app and you put in the domain example.com then it will poll https://riot.im/app/example.com/_matrix/client/r0/login - in the case of https://riot.im it'll get a 404, but that'll obviously depend on the particular configuration of the server serving the riot web client.

It would probably be best to validate on the presence of a protocol and if it's not there tell the user to correct their URL.

**Comment by lampholder** [comment]
https://github.com/vector-im/riot-web/issues/7651

**Comment by aaronraimist** [comment]
Note that this issue is applies to every(?) URL field in RIot. See #6333 for another example, specifically

> If you leave off the https:// and simply type "myserver.com" for the id server, you are shown the screen that says an email confirmation has been sent.

**Comment by turt2live** [comment]
@lampholder should we just make this do .well-known when someone does this? As per https://github.com/vector-im/riot-web/issues/8310 I think
