### ISSUE TITLE
Riot doesn't follow 301 redirects on custom homeserver

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7707]
I haven't thought through the consequences of this at all, and I'm far from certain that we'd want it to follow redirects, but separating this out from https://github.com/vector-im/riot-web/issues/7651 for clarity.

**Comment by t3chguy** [comment]
Element will follow all redirects, as much as the browser allows (and does so), so all redirects also need a valid ACAO header to allow them to be taken from the given origin.
