### ISSUE TITLE
element-web uses a lot of CPU and memory and frequently crashes

### ISSUE THREAD

**Issue by cdauth** [vector-im/element-web#7732]
I have the current riot-web Docker image running on my server. My client is running on https://matrix.rankenste.in/

I'm accessing it through the current version of Chromium on an Arch Linux. My processor is an Intel Core i7-7500U 2.7 GHz.

riot-web constantly uses around 50% CPU, while nothing is happening inside. After a while (an hour or so), Chromium usually tells me that the tab is not reacting anymore and whether to kill it, or often the tab just crashes by itself.

Also, it seems that there is a memory leak, I just had to kill it because it was using 2.5 GiB of memory, increasing a couple of megabytes per second.

![image](https://user-images.githubusercontent.com/1801792/48860923-8d9b3e80-edc2-11e8-9551-6b8bfe23186a.png)

This makes riot-web impossible to keep open constantly. It slows down my computer and increases battery usage a lot.

I'm not sure if it helps, but in the dev tools there are hundreds of messages coming in about every 2 seconds:

![image](https://user-images.githubusercontent.com/1801792/48861712-99880000-edc4-11e8-851c-3135582a1eca.png)

**Comment by lampholder** [comment]
I can't see what version of riot-web this is running, but it looks to be using a recent version of react-sdk (0.14.5).

As far as I can tell the message traffic arriving regularly looks like legitimate traffic - just encrypted messages that the client doesn't have the keys to decrypt.

Is this a large account (how many rooms/how old)? How long does it take to reach 2.5 GiB? Do you get the same problem if you use the riot instance on https://riot.im/app (or /develop)? Or the electron client?

**Comment by lampholder** [comment]
P2 because as best I can tell this is a problem affecting this specific account (rather than a more general performance problem). If other people are seeing perf problems please add your voice here!

**Comment by lampholder** [comment]
Hmm, 10 rooms and a couple of months doesn't sound dramatically large.

I think I missed that it was _hundreds of messages every two seconds_ - are they all the same decryption error messages? Would you be happy to send some logs (via user settings -> 'Submit debug logs')?

**Comment by cdauth** [comment]
I sent the debug logs.

Yes, the messages are all the messages in the screenshot (and even more) repeating over and over again.

**Comment by rebastion** [comment]
Bringing this up (sorry), Elment still using way too much CPU on idle, about 17 percent on my system

**Comment by 0lm** [comment]
same here
im on the windows element client (not web, but the downloadable dektop version).
whenever i receive a message or i send one, the cpu usage goes up and my HDD makes noises (as when a big files is written on it). i guess its the encryption process while sending and receiving messages, but the cpu usage spike and the HDD usage spike in these moments are insanly high.

**Comment by cdauth** [comment]
2½ years later this is still an issue with Element version 1.7.23. The Element tab uses 100% of one CPU both in Chromium and in Firefox. In Chromium the dev tools freeze immediately when opening them, in Firefox lots and lots of messages as in the screenshot above are appearing every second or so. I'm still not able to use Matrix at all because of this.

It seems that at least the memory leak is not an issue anymore.

**Comment by cdauth** [comment]
Here is a performance profile from Chromium and from Firefox, maybe it helps: [performance.zip](https://github.com/vector-im/element-web/files/6561913/performance.zip)

**Comment by turt2live** [comment]
Unfortunately for this issue, the app has changed quite a bit over the years. If folks are still seeing performance issues then please open fresh issues with fresh information for us to take a look at.

**Comment by cdauth** [comment]
For me the issue seems to be solved.
