### ISSUE TITLE
Disambiguation doesn't work on 1/3 users

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7739]
![image](https://user-images.githubusercontent.com/1190097/48922935-5c287e80-ee67-11e8-91b4-a3055895c2b7.png)

All 3 "Hello World" users are created exactly the same with the only difference being the homeserver they are on. All 3 should be disambiguated, surely?

**Comment by SimonBrandner** [comment]
This doesn't seem to be an issue anymore
