### ISSUE TITLE
Markdown-based links URL are not shown

### ISSUE THREAD

**Issue by axelsimon** [vector-im/element-web#7748]
### Description

Markdown-based links are not previewed and one can't see their URL on mouse-hover (putting the mouse cursor on the link) when using Riot Web in Desktop version (Electron-based app).

### Steps to reproduce
- Put your mouse cursor on a link in a message
- Expect to be able to have an idea of where the link will take you and see its full URL somewhere, as you would in a browser
- Be sad, as you realise no URL is shown to you, and hesitate to click on the link

I would expect to always be able to see the URL to which a link points, no matter what setting URL previewing is set to. I'm thinking about links such as the ones in the screenshot below:
![screenshot from 2018-11-26 13-31-49](https://user-images.githubusercontent.com/1172256/49014374-34dff300-f180-11e8-9667-ed45a96fed5a.png)
As you can see, these links are not previewed by Riot, and putting one's mouse cursor on them gives no info.

### Version information

- **Platform**: desktop?
- **OS**: Fedora 29
- **Version**: 0.17.5

**Comment by lampholder** [comment]
This works 'fine' with browser-based Riot (ff on mac at least) with the default status-bar link target preview, but you're right you get nothing on the electron client, which isn't great.

**Comment by t3chguy** [comment]
IIRC if you right click the link in Electron app the top context menu option will be the actual URL

**Comment by axelsimon** [comment]
@t3chguy Thanks, that's a useful trick to know.
However, it doesn't explain or solve why these links are not previewed…
And I still think the link should be shown more readily, either in the preview, or if previews are disabled in the bottom left corner of the window, as is classic in web browser. This is more likely to be an issue with Electron.

@lampholder Yes, this is a bug report using the desktop version of Riot-web (Electron-based), I realise I didn't make that particularly clear. I'll amend my initial message.

**Comment by pacien** [comment]
Would it be possible to at least have a confirmation pop-up displaying the actual target when clicking on a forged link? Currently, nothing stops someone from sending `[http://legit.corp/password-reset](http://evil.site/phishing-form)` and have it rendered as expected.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/6532
