### ISSUE TITLE
Url preview issue when url at the end 

### ISSUE THREAD

**Issue by krrisis** [vector-im/element-web#7749]
### Description

When you link to twitter urls that are a retweet you always have the url at the bottom that gives an error when you click it directly bcs a space is missing between the url and the "

### Steps to reproduce

An example of this you can see [here](https://matrix.to/#/!vwFGsktMNkdorFWJRi:matrix.org/$15432431231093467hirgP:matrix.org?via=matrix.org&via=giveth.io&via=status.im&via=matrix.decent.fund), see also the comment directly under this. 

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 
riot-web version: 0.17.6
olm version: 3.0.0

**Comment by lampholder** [comment]
At a guess, I'd say that whatever mechanism we're using to generate the URL previews is surrounding all of the text pulled from twitter with quote marks, and is _not_ doing anything to turn the URL into a link. Then, I'd guess that Riot's linkifier is seeing a perfectly valid URL and turning it (the original URL + the quote) into a clickable link. Which in this case doesn't get you where you want to go.

**Comment by krrisis** [comment]
Well, almost.... as you can see it doesn't take the entire quote+url, it really sees the url in the quote and all is good. But because of the quotation marks at the end the url throws an error. As you'll see in the example above this will always happen with retweets (where the url is at the end), so actually you just need an extra space at the end before the quotation marks.

**Comment by t3chguy** [comment]
Can you still reproduce this?

**Comment by robintown** [comment]
Closing as it's not clear that this issue still exists, and we haven't seen any other reports of this
