### ISSUE TITLE
share message should directly link to riot message

### ISSUE THREAD

**Issue by krrisis** [vector-im/element-web#7750]
### Description

Would it be possible that when you hit the 3 dots next to any message and hit 'share message' that you don't get the matrix.to url but directly the riot.im link? We link to messages all the time between one room and another, now you have to always take this extra step. When I link to riot, people stay in the app and are redirected to the specific message in the other room, when I link to matrix.to people get confused and click away.
99% of users prob need the riot link anyways.

And YES - I know I can fwd the message, but very often I don't want to, to not clutter other rooms OR bcs the message is not mine (when you forward, the message always seems to be yours, but that's another bug)

### Steps to reproduce

Example: 

1) I want to share a message in another room, I click 'share message' and get this message: https://matrix.to/#/!vwFGsktMNkdorFWJRi:matrix.org/$15432431231093467hirgP:matrix.org?via=matrix.org&via=giveth.io&via=status.im&via=matrix.decent.fund

2) I have to copy this link, paste it in my browser, and over there copy the link from riot

3) now I have to go to the other room and copy https://riot.im/app/#/room/!vwFGsktMNkdorFWJRi:matrix.org/$15432438671096733xLwNj:matrix.org?via=matrix.org&via=giveth.io&via=status.im&via=matrix.decent.fund over there

(also no idea why decent & status are in this message but anyways :) )

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: desktop

- **OS**: Windows 10
- **Version**: 

Logged in as: @krrisis:matrix.org
Access Token: <click to reveal>
Homeserver is https://matrix.org
Identity Server is https://vector.im
matrix-react-sdk version: <local>
riot-web version: 0.17.6
olm version: 3.0.0

**Comment by lampholder** [comment]
A couple of interesting UX issues jump out of this:

1. you can actually just paste the matrix.to link into riot - anyone clicking that link in riot will go to the right place without leaving riot (they won't be bounced via the matrix.to interface). It looks like this behaviour isn't easily enough discoverable :)

1. the reason `decent` and `status` are in the list (along with `matrix`) is because of a recent change - if you are trying to access a room on a server which doesn't (yet) know about that room, it will _now_ check the servers listed in the 'via' list to see if they know about the room. But - this just looked peculaiar to you :)

Are you happy enough that 1. solves your problem?

Thanks!

**Comment by asajeffrey** [comment]
My use-case is pasting the link into github messages, so the URL rewriting in riot doesn't help (and in fact was very confusing the first time it happened to me).

**Comment by asajeffrey** [comment]
For instance https://matrix.to/#/!pcfWjiETvnVuspPLPl:mozilla.org/$POVW1kNh386zivL6qT5BGrs51iwxXqh7Gjgd6Ja9Rms?via=mozilla.org&via=matrix.org&via=tilosp.de is the link to our chat about this, but it takes you to an off-putting page that looks a lot like a 404 page :/

**Comment by t3chguy** [comment]
> Would it be possible that when you hit the 3 dots next to any message and hit 'share message' that you don't get the matrix.to url but directly the riot.im link?

This is possible, your Element instance just needs to be configured for it using config.json

https://github.com/vector-im/element-web/blob/develop/docs/config.md `permalinkPrefix`

matrix.to will soon be able to deep-link through to any Element Web instance you use by means of the `matrix://` protocol handler, so the experience will get even smoother

**Comment by t3chguy** [comment]
> > https://github.com/element-hq/element-web/issues/7750#issuecomment-1055402698
> 
> @t3chguy, is this feature documented anywhere?

Yes. See the link you sent. It contains a link to a config documentation

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-web/issues/7750#issuecomment-2130151903

@t3chguy, I've not provided a URI except to the comment I responded to (which immediately preceded mine) to my knowledge.

**Comment by t3chguy** [comment]
> > https://github.com/element-hq/element-web/issues/7750#issuecomment-2130151903
> 
> @t3chguy, I've not provided a URI except to the comment I responded to (which immediately preceded mine) to my knowledge. Can you cite the link you refer to?

![Screenshot_20240525_002239_GitHub.png](https://github.com/element-hq/element-web/assets/2403652/c2722c83-8e00-4445-802c-dbb15e59e39b)
