### ISSUE TITLE
Document .well-known setup, etc (including ACAO headers)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7760]
So far there's been about 80% of people I've seen caught by not having `Access-Control-Allow-Origin: *` (or similar) on the .well-known file

**Comment by jryans** [comment]
Is something that would be added the spec?

**Comment by turt2live** [comment]
yes and no:

yes - it would be something that would fit nicely as a reminder in the spec

no - we should have our own documentation on how to set up .well-known and not rely on the spec here. The spec is overly complicated for "I want to log in to my homeserver".

**Comment by n1trux** [comment]
Just found out that if you get the error `Invalid /api/v1 response` it could be because you specified an identity server in `.well-known/matrix/client` which doesn't provide that functionality (e.g. synapse which is only a home server, not an identity server).

**Comment by aaronraimist** [comment]
Definitely still an issue since the flagship Mozilla server ran into the same thing #12311

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-meta/issues/1602 + https://spec.matrix.org/v1.6/client-server-api/#web-browser-clients
