### ISSUE TITLE
Double clicking 'Message' in UserInfo sends two invites

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7763]

**Comment by lampholder** [comment]
🙀 
That's nasty; presumably we should debounce click actions across the board?

**Comment by t3chguy** [comment]
I tried to repro this but the dialog vanished the moment I clicked it.

![7763](https://user-images.githubusercontent.com/2403652/64700283-843ca900-d49e-11e9-9d1d-255cdaec2ceb.gif)

**Comment by turt2live** [comment]
Wrong 'start chat': this is talking about the one in memberinfo
