### ISSUE TITLE
Per-room config for spellcheck language

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7773]

**Comment by jo-so** [comment]
It would be helpful to have spelling checks in the input field. To use the right language the browser (and the app) need a hint. Can Riot save a language preference for each room on the homeserver using the [client config](https://matrix.org/docs/spec/client_server/latest.html#id535) and set this for the input field?

**Comment by geckolinux** [comment]
How does Riot currently set the spellcheck language? User environment variables?

**Comment by jo-so** [comment]
AFAIK it doesn't set anything. I has to set the *lang* attribute on the
input field. You can try it with the example for the *contenteditable*
attribute by adding different `lang=…` after *contenteditable*

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

**Comment by SimonBrandner** [comment]
Closing as I believe this is cover by [#5452](https://github.com/matrix-org/matrix-react-sdk/pull/5452)

**Comment by jo-so** [comment]
If I get it right PR#5452 implements a built-in spellchecking and doesn't use the spellchecking of the browser. I use an external spellchecker in my browser that checks grammar and other spelling rules. Hence, I don't want to step down to a spellchecker provided by Element. I don't think #5452 solved this issue.

**Comment by SimonBrandner** [comment]
@jo-so, [#5452](https://github.com/matrix-org/matrix-react-sdk/pull/5452) uses the Electron spell-checker. If you're using the web app you're relying on the browser's spell-checker. I don't think we are able to influence what language is used by the browser's spell-checker... Please let me know if there is something I missing here

**Comment by SimonBrandner** [comment]
You can open a new issue for configurable browser spell-checking. There might be a way to do this, but I'll have to take a closer look.

**Comment by jo-so** [comment]
@SimonBrandner Yes, I'm using Element web. Have you seen comment <https://github.com/vector-im/element-web/issues/7773#issuecomment-617593295>?

**Comment by SimonBrandner** [comment]
@jo-so, oh sorry, missed it... I'll open a new issue give me a moment

**Comment by SimonBrandner** [comment]
@jo-so, [here](https://github.com/vector-im/element-web/issues/16582)

**Comment by SimonBrandner** [comment]
@jo-so, please comment on the new issues, if you have any relevant thoughts. It might be nice to know what are you using for spell-checking
