### ISSUE TITLE
Desktop app is hiding one of my rooms from me!

### ISSUE THREAD

**Issue by loietaylor** [vector-im/element-web#7775]
### Desktop app is hiding one of my rooms from me!

There's a room ("Kris's Unicorn Onboarding!") that I favorited, and it's right there on my mobile but nowhere to be found on desktop. Not in favorites, not in rooms, not coming up when I search for it by name. 

### Steps to reproduce

- Open riot desktop, can't find my room
- Open riot on my phone, it's right there
- Try searching for the room on desktop, can't find it thru any route
- Have ppl in the room message to test it: notification and messages show up fully in mobile, nothing to see or hear on desktop. 

Describe how what happens differs from what you expected. 

Log: sent/not sent?    

<img width="374" alt="screen shot 2018-12-04 at 11 58 46 am" src="https://user-images.githubusercontent.com/38163206/49470314-86aafd80-f7be-11e8-9ec6-f0927927de3d.png">

![ima_c61fd0f](https://user-images.githubusercontent.com/38163206/49470463-02a54580-f7bf-11e8-92af-b245ea6dd475.png)

### Version information

- **Platform**: desktop

For the web app:

- haven't tried this on web at all

For the desktop app:

- **OS**: macOS
- **Version**: riot-web version: 0.16.2
olm version: 2.2.1

**POSSIBLY RELEVANT:** 
- I just got a new google fi pixel phone and put riot on it. Have been using my account on there, but mainly using my old iphone still. The "Kris's Unicorn Onboarding" room shows up on both old and new phone.

**Comment by turt2live** [comment]
@lorelei1 in Riot Desktop, please open the settings (gear icon on the bottom left) and scroll to where it says "Submit debug logs". Click that button and when it asks for a github issue, enter this one. 

This should supply us with some logs to help figure out where the room went, hopefully.

**Comment by lorelei1** [comment]
Ok, log sent! Thank you.

**Comment by lampholder** [comment]
This might be fixed with a 'clear cache and refresh' (an option in the user settings).

**Comment by lampholder** [comment]
I feel like we're seeing a spike in local-room-membership-state != server-side (or another client) state issues. Definitely something worth investigating.

**Comment by t3chguy** [comment]
@loietaylor did you try a `Clear cache and reload` as per @lampholder's suggestion? Are you still seeing this?

**Comment by turt2live** [comment]
Closing as we believe this issue is fixed. If this is untrue, please open a new issue with fresh information and reproduction steps.
