### ISSUE TITLE
hided file name after deencrypt in riot-desktop

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#7789]
1. encrypted room with 2 users
2. user1 send 3 files in room
3. user2 see 3 files as "Decode file1 ...\n Decode file2 e.t.c.":
![default](https://user-images.githubusercontent.com/1297163/49559841-df63cd00-f95b-11e8-8cc7-e55cca3f283c.JPG)
4. User2 press to links for decode this files and links hide:
![2](https://user-images.githubusercontent.com/1297163/49559888-1803a680-f95c-11e8-90ee-16f0540e9b8f.PNG)

P.S.: on riot-web in firefox all work fine. Error only in riot-desktop.

riot-web: 0.17.6 
olm: 3.0.0

**Comment by t3chguy** [comment]
This area has changed and this bug should be gone
