### ISSUE TITLE
When the user directory search request errors, you can't manually invite people

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7792]
I should be able to invite email addresses (and users) even if the user directory is throwing back `400 Bad Request` or `500 Internal Server Error`. This probably applies to all address pickers.

**Comment by turt2live** [comment]
Note that if you enter a full MXID and press tab, it bypasses the check. I suspect that's more of a bug though.

**Comment by turt2live** [comment]
As demonstrated by https://github.com/vector-im/riot-web/issues/11665, this is now more likely with Synapse 1.7.0 being out.

**Comment by turt2live** [comment]
uhh, wrong directory @turt2live

**Comment by t3chguy** [comment]
This got fixed
