### ISSUE TITLE
E2E: Registration and Login: Secure Messages interstitial after account creation

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#7794]
Implements a portion of vector-im/riot-meta#229.

See the [UX reference](https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#heading=h.yovjudod9bqj) for more detail.

**Comment by jryans** [comment]
After discussing more, we'd like to track whether this has been seen once per platform (web, iOS, Android). While we currently have per-account and per-device settings, I don't believe there's a existing per-platform setting concept, so we may need to align with the mobile team on how to do this.

To avoid dialog overload, we decided to show this message on first visit to an encrypted room.

For now, I'll stop working on this because we want to prepare the image assets first.

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.6ojk5yl2sbr7

**Comment by kittykat** [comment]
I'm going to close this for now as the designs have been updated and new ones implemented.
