### ISSUE TITLE
Sydent seems to be very slow

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7799]

**Comment by lampholder** [comment]
Calls to https://vector.im/_matrix/identity/api/v1 were taking ~20 seconds to validate (and it was easy to trigger multiple requests with the .well-known login UX).

**Comment by lampholder** [comment]
p1 major 'cause it makes login feel super slooooow

**Comment by uhoreg** [comment]
This is a really old issue, and doesn't seem to be a problem at the moment, so closing.
