### ISSUE TITLE
E2E: Account Settings: My Devices Section: Location information

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7807]
Part of https://github.com/vector-im/riot-meta/issues/228

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.26nq3b78b51w

**Comment by kittykat** [comment]
I'm going to close this for now as the designs have been updated and new ones implemented.
