### ISSUE TITLE
E2E: Account Settings: My Devices Section: Editable device names

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7808]
Part of https://github.com/vector-im/riot-meta/issues/228

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.26nq3b78b51w

**Comment by uhoreg** [comment]
I think this is fixed by the new redesign.
