### ISSUE TITLE
 E2E: Account Settings: Security and trust section: Don't display message sent from untrusted devices

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7810]
Part of https://github.com/vector-im/riot-meta/issues/228

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.26nq3b78b51w

**Comment by lampholder** [comment]
Bob will treat a device as 'untrusted' if:
- the device has not been verified by its owner, or
- the device belongs to a user Bob hasn't himself verified

**Comment by kittykat** [comment]
I'm going to close this for now as the designs have been updated and new ones implemented.
