### ISSUE TITLE
E2E: Security Notifications: Immutable security messages in the timeline

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7821]
Part of https://github.com/vector-im/riot-meta/issues/232

Immutable security messages in the timeline - we are happy that these messages will appear at different points in the timeline on different devices, and will be ephemeral.

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.2tsmbascrbtf

**Comment by lampholder** [comment]
QUESTION: The spec says that these immutable security messages can be ephemeral... - I just want to make sure we do all have a shared understanding of what's happening here.

**Comment by kittykat** [comment]
After discussion with the Product Management team, I'm closing this issue in favour of a note/epic which is to be added to the roadmap.
