### ISSUE TITLE
E2E: Security Notifications: Immutable notifications in the notif. centre

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7822]
Part of https://github.com/vector-im/riot-meta/issues/232

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.2tsmbascrbtf

**Comment by kittykat** [comment]
After discussion with the Product Management team, I'm closing this issue in favour of a note/epic which is to be added to the roadmap.
