### ISSUE TITLE
E2E: Security Notifications: Show warnings against messages sent from untrusted devices (if enabled in user/room settings)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7824]
Part of https://github.com/vector-im/riot-meta/issues/232

Show warnings against messages sent from untrusted devices (if enabled in user/room settings)

**Comment by lampholder** [comment]
Direct link to relevant wireframes:

https://docs.google.com/document/d/1TIZarCxP0UHcn52o3YdKrFs_ESB3YvDxvCY_SoY-FUk/edit#bookmark=id.2tsmbascrbtf

**Comment by kittykat** [comment]
I'm going to close this for now as the designs have been updated and new ones implemented.
