### ISSUE TITLE
Consider what ES level Riot uses

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#7825]
The times, they are a changin'.

Look like we are probably going to switch to exporting ES6 from js-sdk: https://github.com/matrix-org/matrix-js-sdk/issues/803 - if we do, the same question in that bug applies here: do we start babel-ing our deps or do we let our generated bundle use ES6? I haven't checked properly but we use plenty of other features that restrict us to only modern browsers, so there is no advantage to babel-ing our code down to ES5 to support, say, IE. This would eliminate the need to build <del>react-sdk and</del> js-sdk making our build process much simpler.

Edit: obviously we still have to build react-sdk because JSX.

**Comment by turt2live** [comment]
+1 to ES6

**Comment by jryans** [comment]
I think it should be safe to use ES6 in the bundle. From the [ES6 compat table](http://kangax.github.io/compat-table/es6/), it's well supported by modern versions of each browser.

**Comment by lampholder** [comment]
@dbkr how should we prioritise this?
