### ISSUE TITLE
webpack dev server doesn't fail to compile if you screw up ternary syntax

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7840]
and maybe other things.

I had the following (no else condition) and the dev server kept saying "compilation succeeded".
```
const label = text ? <span>{ text }</span>;
```

This also lead to weird problems like "Not a valid component" errors.

**Comment by lampholder** [comment]
Is there something we can change to fix this?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/91923315-4b887780-ec8d-11ea-9732-fb85946a3bf1.png)
