### ISSUE TITLE
Revisit usage of Babel plugin `transform-async-to-bluebird`

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#7846]
I discovered while working on a failing test that the Babel plugin `transform-async-to-bluebird` can eat errors (such as `TypeError`s when a method is not defined), leading to lots of wasted time trying to figure out what went wrong.

I can see that there is some history with this plugin:

* [Converted](https://github.com/matrix-org/matrix-js-sdk/commit/8a4a1dfadf7ddb24927dbfff7bd8c50eac399921) from `transform-async-to-generator` to `transform-async-to-bluebird` because of a previous change to the transform runtime
* [Converted](https://github.com/matrix-org/matrix-js-sdk/commit/0fb0c1b71b1776ab12dd4520756d53cef569e052) from `regenerator-runtime` to `transform-runtime` because of some fun dependency hell

Note that the problem package `transform-async-to-bluebird` [doesn't appear](https://www.npmjs.com/package/babel-plugin-transform-async-to-bluebird) to be from the Babel core team.

I think we should investigate options such as: 

* Revert to `transform-async-to-generator` (which fixes this error issue) in some safe way
* Explore Babel 7 and its plugins in case they also fix this issue

**Comment by MTRNord** [comment]
Seems like I am working on a fix for this by a sideeffect. Fix seems to be this:

```
["@babel/plugin-transform-async-to-generator", {
      "module": "bluebird",
      "method": "coroutine"
    }]
```

(Taken from https://babeljs.io/docs/en/babel-plugin-transform-async-to-generator )

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/91923268-298ef500-ec8d-11ea-80b7-5415549c64da.png)
