### ISSUE TITLE
Cookie consent on desktop app

### ISSUE THREAD

**Issue by Extarys** [vector-im/element-web#7849]
I hope this wasn't reported before.

### Description

I got a cookie consent on the desktop app when asked if I'd like to help inprove the app

### Steps to reproduce
Create an account, log in on desktop.

Describe how what happens differs from what you expected.

I would expect to not see the word "cookie" on a desktop app.

### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**: Linux Mint 19
- **Version**: 0.17.8

**Comment by t3chguy** [comment]
The desktop app is an embedded chromium browser so it has cookies too

**Comment by Extarys** [comment]
I understand your point.
But the end user, in a desktop app, should not have to deal with this.
I think the message on the desktop app should be modify. I don't see Atom, Bracket or VS Code asking my consent for cookies. they just ask if I accept to send some telemetry data.

**Comment by t3chguy** [comment]
This is now gone, the analytics consent is still relevant
