### ISSUE TITLE
I can't rageshake from any current Riot version on Firefox 66.0a1 (2018-12-13) (64-bit) (latest Nightly)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7864]
I get an error:
![image](https://user-images.githubusercontent.com/1922197/50000823-b4e4c600-ff92-11e8-955e-fbbc1cc7d969.png)

And my indexeddb looks like:
![image](https://user-images.githubusercontent.com/1922197/50000868-d3e35800-ff92-11e8-96d1-d28ddbd1b821.png)

**Comment by lampholder** [comment]
Seems to be affecting just me at the moment - if anyone else sees this please upvote

**Comment by jryans** [comment]
@lampholder Let me know if you'd like to try debugging this together on your machine to see what's wrong.

**Comment by t3chguy** [comment]
Closing due to lack of repro
