### ISSUE TITLE
It's hard to tell whether your messages have sent or not, and so whether people are responding them or not (i.e. "did people even see my answer by the time they sent their response"?)

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#7888]
Also, unsent messages get pinned to the bottom of the page until they've sent, so the ordering looks really weird for unsent messages.

I think we might need something like a small subtle spinner on the RHS which appears immediately as you send and then disappears once the msg has sent.  This is obviously a change from the proposed existing redesign where the spinner would only appear after a few seconds of the message not yet having sent.

**Comment by t3chguy** [comment]
The new sending & sent indicators clean this up a lot
