### ISSUE TITLE
Token validation email should be reworded

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#793]
Gillian says we might want to reword the bold parts of the email validation email below which doesn't read very nicely:
Hello,
We have received a request from 89.101.139.230 to use this email address on vector.im. **If this was you who made this request, you may use the following link to complete the verification of your email address:**
Complete email verification
...or copy this link into your web browser:
https://vector.im/_matrix/.......
Please note that you will need to use Chrome, Firefox or Safari.
If your client requires a code, the code is 487005
**If you aren't aware of making such a request, please disregard this email.**

**Comment by ReneB** [comment]
A similar suggestion: the subject of the e-mail is very "technically" worded: "Your Riot Validation Token." A developer or tech-oriented person will probably know what this means and go "OK, I get what this is." But an average user does not care about such things. Maybe something like "Verify your e-mail address for Riot" or similar wording would be better and less off-putting?

**Comment by aaronraimist** [comment]
See https://github.com/vector-im/riot-web/issues/3784#issuecomment-425650273, I think this email has been reworded to be much less technical.

**Comment by ReneB** [comment]
The body seems to have been clarified, but I can't see the subject in the screenshot provided in #3748. Could you verify if that's been made more user-friendly as well?

**Comment by aaronraimist** [comment]
Oh. No, it hasn't.

Subject "Your Riot Validation Token"

**Comment by aaronraimist** [comment]
Alright I created https://github.com/matrix-org/sydent/pull/84 to change it to "Comfirm your email address for Riot", I think that is a little better but still could probably be improved.

**Comment by kittykat** [comment]
Email is now very different, so closing this issue. Please open a new issue if there are any new enhancement requests to be implemented.

![Screenshot from 2021-09-03 14-31-52](https://user-images.githubusercontent.com/51663/132013578-e7b1d173-4e21-41f0-9fb3-36e04ee98ee1.png)
