### ISSUE TITLE
Setting a custom status on a large account can cause /sync to temporarily not work

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7931]
This would be fixed with profile rooms

**Comment by lampholder** [comment]
I guess we're not planning to address this here and rather for it to be resolved when profile rooms are implemented?

In what way (and how temporarily) does /sync not work?

**Comment by turt2live** [comment]
Yea, this is fixed by profile rooms. It's unlikely people are in ~700 direct chats, but when they are their client can go silently offline. The sync request ends up being queued at the end of the line because the syncer cancels and request it. In my single test, it took 30 minutes to recover.

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
