### ISSUE TITLE
Minor aesthetic change to t's and c's consent on registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#7939]
Sorry, should have picked this up earlier - the spacing around the checkbox is a little off.

It looks like this:
![screenshot 2018-12-21 at 11 43 04](https://user-images.githubusercontent.com/1922197/50341246-0f8f9c00-0516-11e9-81e4-570e37b8c854.png)

But would be more pleasing if it looked like this (margin-left/margin-right: 11px):
![screenshot 2018-12-21 at 11 45 05](https://user-images.githubusercontent.com/1922197/50341247-0f8f9c00-0516-11e9-9278-3b43d08f8fa8.png)

A very small change indeed, but one that it would be nice to make if there's a good opportunity to do so.

**Comment by ara4n** [comment]
also wondering if we should centre align it or put it in a plinth or something to make it look less unstyled. @nadonomy did you have UI for this?

**Comment by turt2live** [comment]
Note that component here is the same component used in the ILAG dialogs. There's already some not-great properties flying around to have the "Accept" button show up on the registration form. 

Just something to consider when implementing any fixes.

**Comment by t3chguy** [comment]
This got fixed
