### ISSUE TITLE
"call ended" events cause an unread notification in the systray although all messages in the room have been read

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/element-web#7941]
### Description

If the last event in a room is a "call ended" event, there is an unread notification in the systray icon that won't go away until other events are received and read in that room.

### Steps to reproduce

- Make a one-to-one call
- Hang up

I expect: No unread notification
Actual: Unread notificatin in systray icon

Log: Sent

### Version information

- **Platform**: Desktop
- **OS**: Windows, Arch Linux
- **Version**: 0.17.8

Possibly related: #6617

**Comment by lampholder** [comment]
We have multiple instances of this - how tractable is it to knock non-message events counting towards unread state/message counts/whatever on the head once and for all?

**Comment by hughwilliams94** [comment]
For what it is worth, I think this affects all platforms not just the web client. On my girlfriends iPhone, there are notification badges which cannot be cleared.

**Comment by msrd0** [comment]
Can confirm that this affects multiple platforms. Can reproduce with Riot 1.2.1 on Firefox and Electron on ArchLinux, as well as 0.8.28a on Android installed via F-Droid.

**Comment by Thatoo** [comment]
Yes, it affects Riot Desktop on Ubuntu and Riot on Android 6.0 at least.

**Comment by SimonBrandner** [comment]
The only proper solution here is to use to-device messages as proposed by https://github.com/matrix-org/matrix-doc/pull/3401

**Comment by HarHarLinks** [comment]
Maybe this, but maybe not quite?

### Steps to reproduce

1. get called 1:1 e2ee while offline/only online on E android
2. press phone's standby button to silence ringing
3. start E desktop to see notification count of 5 (on the room in the room list)

### Outcome

Really this should count as 1 if there is only 1 event in the timeline (the call thingy in missed call state).

I wonder if it should be a "ping" event (red) or something else.

---

However I don't have a problem with "stuck" notifications badges in either systray nor room list. The confusing part about this is that you expect to see 5 unread messages, that is the call plus 4 before that, however there are not 4.
