### ISSUE TITLE
react-sdk builds claim to fail to compile but yet are green

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#7985]
`ERROR in   TypeError: Cannot read property 'entry' of undefined` - should this be causing a failure? The tests seem to pass otherwise...

**Comment by jryans** [comment]
This message appears when running the `test` script for `riot-web` as part of integration testing for React SDK builds.

The message seems to appear in [Travis builds](https://travis-ci.org/matrix-org/matrix-react-sdk/builds/474563553) as well as locally. It's quite confusing to see "ERROR" without failure, especially when something else is the actual failure elsewhere in the log, so it would be good to address this to improve confidence in our CI results.

**Comment by turt2live** [comment]
iirc we fixed this
