### ISSUE TITLE
Room upgrades: tags not copied to new room

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#7993]
tbh this is probably a server-side issue, but let's track it here for now

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/synapse/issues/4391

**Comment by turt2live** [comment]
fixed by synapse

**Comment by Cadair** [comment]
I noticed this occurring with the matrix.org website room, it was in low priority when I got the notif and it wasn't post upgrade.

**Comment by turt2live** [comment]
Closing in favour of synapse issues - if this is still not working, please open a new issue there.
