### ISSUE TITLE
Infinispinnering memberlist after accepting an invite

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#7995]
some people [on riot-web experimental] have reported an infinispinnering memberlist after accepting an invite. Not sure if this is a client-side or server-side issue.

**Comment by turt2live** [comment]
I'm not able to reproduce this. Is it possible the server is just slow? Logs would maybe show the issue here.

**Comment by t3chguy** [comment]
Closing due to lack of reproduction & response, please shout if you see this again
