### ISSUE TITLE
[Feature] Channels

### ISSUE THREAD

**Issue by danimesq** [vector-im/element-web#8000]
Like on Rocket.chat, Discord and Slack, every room could add custom channels.
Also, those channels haves some set of permissions; for example, on news channels all users can't post, but just who have "owner" or other specific role.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/vector-im/riot-web/issues/8001

**Comment by t3chguy** [comment]
Channels are what rooms are, and guilds/servers are what communities are in riot...

**Comment by DaniellMesquita** [comment]
How it works is some weird compared to Discord. It needs some modifications

**Comment by lampholder** [comment]
We definitely have work to do to communities to get their meaning and use across more clearly, esp. seeing as the concept it represents is (in my mind at least) in many ways very similar to a discord server/slack workspace.

**Comment by robintown** [comment]
This should be solved by spaces and the recent IA changes. For any further UX problems regarding spaces, please open new, more specific issues.
