### ISSUE TITLE
[Feature] User roles

### ISSUE THREAD

**Issue by DaniellMesquita** [vector-im/element-web#8001]
Every user role is relative to the room or specific channel, and haves its permissions set

**Comment by lampholder** [comment]
It would be useful if you could provide a bit more detail describing how what you want is not served by the existing power levels system. Thanks!

**Comment by DaniellMesquita** [comment]
@lampholder
The power levels doesn't shows and doesn't haves custom permissions.
Would be better a system for applying roles (labels with color and alongside user name on userlist), and setting permissions for each role the admin creates on roles list.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/12548
