### ISSUE TITLE
Last read marker bar won't go away

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8006]
In this screenshot there is a green bar I can't get rid of:
![image](https://user-images.githubusercontent.com/1190097/50660976-d9fba180-0f5e-11e9-9878-0a02cfaf1924.png)

The only way to clear it was to send a new message.

**Comment by turt2live** [comment]
As far as I can tell, have a room with a very small timeline such that there's no scrollbar.

**Comment by anoadragon453** [comment]
Also getting this currently in #riot-dev with your last message @bwindels. Can reproduce every time I look back at this room.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/10992 which has a couple 👍
