### ISSUE TITLE
Images scale to the timeline width

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8011]
It would be great to get the best of a wider timeline and not have images which consume the entire view.

Related: https://github.com/vector-im/riot-web/issues/1520

**Comment by ara4n** [comment]
We currently cap images at 600px high to prevent them from stealing lots of screen width.  They will only scale horizontally to fit the whole timeline if it doesn't waste height.

@nadonomy do you think we should also cap the width too?

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/1520

**Comment by nadonomy** [comment]
> @nadonomy do you think we should also cap the width too?

Yeah. The bigger the images can get the less comfortable your gaze is when scanning and reading messages.

I'd argue for a max width/height of around 400px even, treating them as large thumbnails in the knowledge users can browse messages more comfortably and view them in a full screen lightbox to see more detail.

**Comment by turt2live** [comment]
There's now an image size setting (on develop)
