### ISSUE TITLE
New direct chat was behaving like it was mentions only instead of the default 'all messages'

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8016]
I didn't witness it, and am proxying the issue on behalf of someone.

Steps:
1. Alice creates a direct chat with Bob
2. Bob accepts and waits for the room to load before going to a different room
3. Alice sends some messages
4. Bob does not receive notifications
5. Alice is sad that Bob is ignoring them

**Comment by lampholder** [comment]
There's probably not a lot we can do to investigate this with so many steps of removal :\

**Comment by turt2live** [comment]
Well, to make it worse: I've seen it happen to me since reporting. Didn't happen to all new chats though

**Comment by turt2live** [comment]
This is now trivial to reproduce in any new room:
1. Receive an invite to a direct chat
2. Accept it
3. Receive a message

After viewing the message, everything is fine. The time delay between accepting the invite and receiving a message can be months.

**Comment by turt2live** [comment]
This particular case has been fixed.
