### ISSUE TITLE
Missing sender profile after a clear cache & reload. Member appears fine in member list and in RR

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8017]
![image](https://user-images.githubusercontent.com/1190097/50670138-ab91bc80-0f86-11e9-8296-1f13e46f9dbf.png)

Matthew happened to be the victim in my scenario. This is from new HQ.

**Comment by yannicka** [comment]
By clearing the cache with the button "Clear cache and reload", I did not have this problem. Do you still have it?

The only minor problem I have is that with a previous unsended message in the composer, the avatar is not displayed:
![image](https://user-images.githubusercontent.com/22885898/82575976-7a208d80-9b89-11ea-9f30-052660795f37.png)

**Comment by MadLittleMods** [comment]
Possibly related https://github.com/vector-im/element-web/issues/7418

**Comment by turt2live** [comment]
I don't think this is a useful ticket in 2021/22 - if people are still seeing this, please open a new issue with more details.
