### ISSUE TITLE
integrate reminder bot?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8024]
https://twitter.com/danfinlay/status/1081259266890186759?s=21

**Comment by uhoreg** [comment]
related: https://github.com/vector-im/riot-web/issues/2938#issuecomment-449362364

**Comment by lampholder** [comment]
What about (in the fullness of time) widgets' being able to enrich context menu? So when you add the Remember The Milk widget it could add a little cow-head icon to the onhover of a message letting you add it as a task...

**Comment by lampholder** [comment]
In the short term, though, this feature would be neat enough that a less flexible/immediately extensible impl might be worth exploring

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/15726
