### ISSUE TITLE
Dharma theme still triggers Open Sans download

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8026]
At least in Firefox, the redesign / dharma theme triggers both Nunito and Open Sans to download.

We should ensure all components are using the right variables for font-family and investigate any other causes of the extra download.

**Comment by aaronraimist** [comment]
This is (at least temporarily) fixed by https://github.com/vector-im/riot-web/pull/8280

**Comment by turt2live** [comment]
Presuming fixed by the new font family.
