### ISSUE TITLE
Decide how to proceed with conflicting custom status / presence features

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8029]
There are at least 2 styles of UX that have been explored in the space of custom status / presence:

* Custom Statuses (https://github.com/vector-im/riot-web/issues/1528)
  * [UX](https://docs.google.com/document/d/1uLc_KhcWhlQ7r0IyjFLAh2WSV4kJAyIwAN8j6db_VHM/edit)
  * Merged as an experimental feature (disabled by default) in https://github.com/matrix-org/matrix-react-sdk/pull/2347
* Custom Presence (https://github.com/vector-im/riot-web/issues/478)
  * Historical unmerged PR in https://github.com/matrix-org/matrix-react-sdk/pull/412

[Quoting](https://github.com/matrix-org/matrix-js-sdk/pull/805#issue-238172674) @turt2live to explain the distinction between the two features:

> Status messages are completely unrelated to the presence status message in that they do not expire and have a different intent. Presence status messages are intended to be read as "Online reading documentation" whereas status messages would be just "Reading documentation" (no associative presence).

Unfortunately, each of these features seems to compete for the same UX space, so it's unclear how they might both coexist together (if that's desired). A decision should be taken on how to proceed.

**Comment by hex-m** [comment]
Related:
* https://github.com/vector-im/element-web/issues/16608
* https://github.com/vector-im/element-android/issues/70
* https://github.com/vector-im/element-web/issues/14964
* https://github.com/vector-im/element-web/issues/4706

"Presence" and "Custom Status" are also both mentioned in the [Roadmap](https://github.com/vector-im/roadmap/projects/1).

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
