### ISSUE TITLE
Resizable "Send a message" panel?

### ISSUE THREAD

**Issue by kascana** [vector-im/element-web#8030]
Would it be possible to make the "Send a message" panel at the bottom resizable? It is often more convenient to start writing a message not at the very bottom of the screen. Other programs (such as Skype) have this functionality of a resizable panel for writing a message. Another very useful feature would be to have the ability to correct typos in sent messages.

**Comment by kascana** [comment]
This is great to know. Hopefully you could implement this feature soon. Thanks!

What about the editable sent messages. Is this going to be possible?

**Comment by nadonomy** [comment]
Hey @kascana—heads up I'm removing the redesign label from this issue as it's unrelated to the redesign and is essentially a new feature request.

**Comment by kascana** [comment]
Any chance to get a resizable bottom section any time soon?

**Comment by kascana** [comment]
Even though the useful feature I asked for one year ago was thought to be "fairly easily doable in the redesign", until now unfortunately nothing seems to have been done in this regard. Is there anyone who might wish to implement this?

**Comment by yannicka** [comment]
It seems to be in duplicate with #5882.

**Comment by kascana** [comment]
I don't get it! Has anyone addressed the issue raised here and in #5882 ? The composer space is still unresizable which at least for some users is extremely inconvenient. Why not add this option and make the composer more user friendly?
