### ISSUE TITLE
Redesign: Greater contrast between "all read" and "X unread" rooms

### ISSUE THREAD

**Issue by AllienWorks** [vector-im/element-web#8045]
The visual difference between _unread_ vs. _all-read_ rooms is low. It's not exactly clear which rooms have unread messages on a first glance.

I'd like to suggest "graying-out" the _all-read_ rooms a bit more (used `#61708bb3` in example):

### Currently

![screenshot from 2019-01-07 22-59-50](https://user-images.githubusercontent.com/1965795/50795884-fdf91300-12cf-11e9-8fda-427f2b57ee9b.png)

### Proposed

![screenshot from 2019-01-07 22-59-07](https://user-images.githubusercontent.com/1965795/50795900-0a7d6b80-12d0-11e9-8a6f-941385341337.png)

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/7946

**Comment by Cadair** [comment]
I think that it would be better to make the unread rooms more stark rather than lowering the contrast on the unread ones.

**Comment by fladd** [comment]
Here is my custom CSS to fix the problem in my browser. Simple solution. Looks great.

```
.mx_RoomTile_name {
    font-weight: normal;
}

.mx_RoomTile_unread .mx_RoomTile_name {
    font-weight: bold;
}

.mx_RoomSubList_label {
  text-decoration: underline;
}
```

**Comment by turt2live** [comment]
@lampholder I've set this as p1 a bit selfishly - I keep fielding complaints about this, and have finally been worn down enough to do something about it. Please prioritize as needed.

**Comment by turt2live** [comment]
I believe this is fixed in the new room list design
