### ISSUE TITLE
I have different statuses in different rooms.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8054]

**Comment by lampholder** [comment]
Well, at the time I thought I was seeing different custom statuses associated with my account when I opened different rooms. The reason I thought this was, having set my status to 'Available', I went to another room and saw my status still set to 'Is there a maximum length for a status...' (or similar).

Looking again, I can see that my status was set to 'Is there a maximum length...' across the board. Despite at some point having been 'Available', the previous status had ressurrected itself across my account.

I'm _fairly_ certain I saw different statuses in different rooms, too, but not 100% - I'll grab a screencap next time.

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
