### ISSUE TITLE
Chrome's URL tooltip can easily cover the composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8068]
![image](https://user-images.githubusercontent.com/1190097/50856015-d002e580-1346-11e9-888d-3c9f1a378581.png)

Full text:
> I am typing a lot of words here
> and now I am on the second line, as shown by my words peeking over the side

This happens when your mouse is hovering over an anchor of some kind. In my case, it was hovering over an image as that's where I left the mouse.

**Comment by jryans** [comment]
Hmm... I suppose the only workaround would be to have empty space below the composer to anticipate this possibly appearing tooltip, which doesn't really sound great...

**Comment by lampholder** [comment]
I see this tooltip all the while - it's pretty annoying.

Looks to me like Slack leaves exactly one chrome URL tooltip's height of whitespace beneath the composer.

**Comment by yannicka** [comment]
In Slack and Discord, there is indeed a margin under the composer, about the height of the tooltip.

**Comment by robintown** [comment]
As per https://github.com/vector-im/element-web/issues/21457#issuecomment-1072271035, we're using https://github.com/vector-im/element-web/issues/17362 as a canonical source of information for this issue
