### ISSUE TITLE
Ability to peek into invites

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#807]
I invited a user already registered using his email and later his matrix ID but he couldn't peek despite the setting being turned on

**Comment by ara4n** [comment]
@AmandineLP any idea what flow they were trying to use to peek?

**Comment by AmandineLP** [comment]
I just reproduced it on /beta clicking on the invite. I just get the "would you like to accept or decline the invite" msg. but I cna't see history despite the room being peekable.

**Comment by ara4n** [comment]
So we deliberately don't let people peek into invites yet.  We do let people peek when they explicitly join rooms, but given the problems we're seeing there I'd like to get that stable first before we open up a whole new level of complexity with this.  Going to bump it to v1.

The relevant code is:

https://github.com/matrix-org/matrix-react-sdk/blob/9a0ea56bba49fb6324a199b55c02cc11662e48f0/src/components/structures/RoomView.js#L1492

**Comment by ara4n** [comment]
...and bumping this to v2...

**Comment by ara4n** [comment]
actually, this is harder than I recalled as it requires server-side stuff.  We can't currently peek into arbitrary invites because we're not yet joined to the room(!)

**Comment by ara4n** [comment]
filed as SPEC-368

**Comment by ara4n** [comment]
This would also stop us having send invite stale metadata snapshots around the place for name/alias/avatar etc, as we can preview the correct live metadata for the room.

**Comment by MurzNN** [comment]
Wow, seems some improvement happens with this issue: https://github.com/matrix-org/matrix-react-sdk/commit/f0333b5b1caf7ccf2458646dc74fee31bf246365 :rocket:

**Comment by t3chguy** [comment]
@MurzNN nope, that is an explicit invite reason as specified by the inviter, not the ability to peek into the room.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/9594 which suggests a "Preview" button to avoid being shown spam from an unwanted invite.
