### ISSUE TITLE
What happens if you try and quickly join #freenode_#someroom:matrix.org as a guest

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8074]
1. Go to https://matrix.to/#/#freenode_#someroom:matrix.org
1. Click on the Riot link
1. Open Riot and get asked to provide a username
1. Confirm you're not a robot
1. Accept the server's terms and conditions
1. Confirm you want to join #freenode_#someroom:matrix.org
1. Join #freenode_#someroom:matrix.org
1. Get kicked from #freenode_#someroom:matrix.org
1. Get an invite to _Freenode IRC Bridge Status_ room
1. This room tells you _Could not join #someroom on 'chat.freenode.net': err_needreggednick_
1. Get an invite to freenode-connect
1. freenode-connect tells you _Welcome to freenode. To protect the network all new connections will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified._
1. Riot-Bot says hello
1. By divine inspiration guess that you need to invite @ freenode_nickserv:matrix.org to a chat
1. Get an invite from @ freenode_NickServ:matrix.org
1. Camel cases NickServ has your reply; he's telling you how to register your nick
1. Tell NickServ _register password email@mydomain.com_
1. Get an email telling you what to do next
1. Tell NickServ _verify register NICK CODE_
1. Try to join #freenode_#someroom:matrix.org again
1. Get an infinite spinner
1. Refresh the app
1. Where's #freenode_#someroom:matrix.org gone?
1. Try to join again
1. Boom, you're in

**Comment by t3chguy** [comment]
Element no longer offers the ability to join as a guest and forces login/registration
