### ISSUE TITLE
Riot web login page reported malicious by Google Safe Browsing ?

### ISSUE THREAD

**Issue by Linuxine** [vector-im/element-web#8089]
Hi,

I dont' really understand why, but yesterday Google decided the url to my Riot web client installed  on my server was not safe, and going to the page displays me the awful red page "This site is not safe !".

I have checked and Riot seems to be the only URL on all the pages I host that is tagged as "not safe". My server does not seems to have been compromised, I have found no evidence of intrusion, or malicious code. The few details I can get seems to indicate the site is a fishing one, encouraging user to give personal information.

Anyone with the same issue ? I was wondering if maybe the feature for login with a phone number for example could be tagged as some fishing by mistake ?

Thanks for you help !

**Comment by turt2live** [comment]
Are you able to get a screenshot of the page? It's quite common for local malware to alter the page to be bright red to match chrome's legitimate warning, and the exact wording of the page can help identify which it is and potentially what the issue is.

**Comment by Linuxine** [comment]
You can see the page at https://linuxine.net/riot/. 
I did not find any difference in the page, on anything altered in the source code :/ 
The page is the exact default Riot login page, as far as I can tell.
The strange thing is that the site is NOT taged as "malware detected", but as "fishing" : "this site encourage user to give personal information". As it is a login page, this seems like a stupid feature of the safe browsing bots to me ?

**Comment by lampholder** [comment]
That's very peculiar. 

I diffed the bundle.js running on linuxine.net/riot and riot.im/app - they're the same. Which isn't to say that something more subtle isn't going on.

As a first step it would certainly be worth report this as a mistake using https://safebrowsing.google.com/safebrowsing/report_error/?hl=en-GB&url=https%3A%2F%2Flinuxine.net%2Friot%2F 

Have you tried hosting a fresh copy of riot on a different path?

**Comment by Linuxine** [comment]
Thanks for investigating !

Actually, I just created another Apache alias on the same Riot installation and there is no warning about it... But I guess the Google Bot does not crawl my server so often, so it may just no have detected the change.

Me and my users already reported the mistake using their form, yes. But I am not sure this is very effective, or it may take a while to process, no effect for now :/

**Comment by MadLittleMods** [comment]
@Linuxine Did it ever sort itself out? It looks like https://linuxine.net/riot/ doesn't exist anymore and I also checked for `element/`

**Comment by Linuxine** [comment]
> @Linuxine Did it ever sort itself out? It looks like https://linuxine.net/riot/ doesn't exist anymore and I also checked for `element/`

Hi, thanks for taking a look ! Actually I changed my server, so yes, this url is not valid anymore. I do not have the issue with the new server. However, I was never able to solve the issue, I  have tried registering the site on the Google form dedicated to reporting a mistake, but it did nothing :/

**Comment by MadLittleMods** [comment]
Given we have no way to reproduce now, I am going to close.

Wish Google gave some more specific details and the form to report a false-positive actually worked for you 😪
