### ISSUE TITLE
Possible future suggestion for custom status UX

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8118]
Github landed custom user status in beta this week, which takes the form of a whole dialog:
![image](https://user-images.githubusercontent.com/1190097/51080611-5ea39980-169c-11e9-8bb3-3cab31aa5e95.png)

It might be worth mimicking this in some way, particularly the bit covered by #7796. Associating emoji with status also seems to be a popular theme among these kinds of features - maybe we should support the same?

**Comment by nadonomy** [comment]
Yeah absolutely— ftr we actually started in this direction, and have UI comps and design docs exploring the relationships between the intent and use of presence and status. We just intentionally scoped down the first implementation.

Looking forward to revisiting this in due course.

**Comment by lampholder** [comment]
Slack has a nice option to set the expiry on a status, too (with default expiries to match the default statuses).

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
