### ISSUE TITLE
fails to build if olm is not installed

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-web#8121]
even though olm is listed as an optional dependency.  Build fails on src/vector/index.js importing olm, as reported in https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1547500579920641XBXCW:matrix.org?via=matrix.org&via=t2bot.io&via=riot.tenx.tech

**Comment by kittykat** [comment]
@uhoreg could you please confirm if this is still a valid issue?

**Comment by uhoreg** [comment]
Yes, this looks like it is still an issue.  Although now the import for olm is in `src/vector/init.tsx`.

**Comment by uhoreg** [comment]
Actually, olm is now listed as a dependency rather than an optional dependency, so this should no longer be an issue.
