### ISSUE TITLE
Custom Status: Status message UI drifts on zoom

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8129]
With the custom status feature, if you do the following:

1. Click your avatar to set a status message (triggering the context menu to display)
2. Zoom the page

...then the context menu will no longer be aligned your avatar.

<img width="292" alt="2019-01-15 at 09 33" src="https://user-images.githubusercontent.com/279572/51190817-aa2a9300-18a8-11e9-8bbf-56c685cfab65.png">

**Comment by lampholder** [comment]
This is only if you zoom with the status setter open - if you zoom and then open it, it appears in the right place.

So +1 for having a general context menu component that handles zooming properly, but I think fixing this specific case is very low priority :)

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
