### ISSUE TITLE
Add quick actions to invite friends on empty screens

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#8141]
It could be the member button pulsating, or the invite button popping out, or right panel being open by default when creating a room (but then having to close it when going in another room is a pain)

**Comment by lampholder** [comment]
Perhaps shrinking to a floating ![image](https://user-images.githubusercontent.com/1922197/51481540-ffc0dd00-1d8b-11e9-9661-294e9645d090.png) in the top right? If that doesn't mess with widget UX too much.

**Comment by t3chguy** [comment]
We could more proactively show the lonely prompt instead, currently, it shows when you send a message into an empty room

![image](https://user-images.githubusercontent.com/2403652/96732452-3fc55180-13b0-11eb-96c8-feae1d77de05.png)

**Comment by niquewoodhouse** [comment]
Something like this I think scales well to allow for more buttons.  I'm just not sure about what's easy enough to change layout wise in a new room - with encryption banner, timestamp etc - lots of parts.  @t3chguy maybe you're free to look at some of [these](https://www.figma.com/file/pH7XfY5KgETURskbscd0B8/Web-Quick-add-people-in-a-new-room?node-id=4%3A3432) with me? 

<img width="1440" alt="Frame 12" src="https://user-images.githubusercontent.com/1587166/98095186-23321a80-1e82-11eb-8861-7bbc3645649a.png">

**Comment by niquewoodhouse** [comment]
We settled on the following as it's pretty basic and can scale i

**Rooms**

<img width="1440" alt="Room_ with image" src="https://user-images.githubusercontent.com/1587166/98153974-ea1e9800-1ecb-11eb-8f6a-28173e29636a.png">

And if a topic has not been added in the creation of the room:

<img width="1440" alt="Room_ with no image" src="https://user-images.githubusercontent.com/1587166/98221805-03652a00-1f48-11eb-926a-86857cf7687b.png">
 
@t3chguy I changed the CTA copy to be the same as the button in the right panel members list `invite to this room,` just to aim for consistency.  I personally preferred `add people` or `invite people` - just sounds simpler but I think consistency is more important atm (and it will already be something that's translated)

**DMs**

<img width="1440" alt="DM" src="https://user-images.githubusercontent.com/1587166/98150373-729a3a00-1ec6-11eb-86c4-dc6465c3977b.png">

The second line `Only the two of you are in this conversation, unless either of you invites anyone to join.` would only appear if no bots/other people have been automatically added already.
