### ISSUE TITLE
Custom Status: Settings status randomly reorders people section

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8144]
Could be a dup, but I couldn't find one.

Setting a custom status sends a state event to every DM, some part of this is resolving in a random order, and I'm guessing that the people section is ordered by most recent event (rather than most recent _visible_ event), so what happens is my people section gets ordered randomly each time I set a status.

**Comment by turt2live** [comment]
Effectively https://github.com/vector-im/element-web/issues/12063 and associates
