### ISSUE TITLE
Lock icon shift right when mousing over second message in series

### ISSUE THREAD

**Issue by vimenepa** [vector-im/element-web#8171]
- **Browser**: Firefox 64.0 64-bit
- **OS**: Xubuntu 18.04.1 LTS

### Description

When mouse hovers over second message below the first in a series of three, lock icon corresponding to first message shifts right. 

![screenshot_2019-01-18_23-29-29](https://user-images.githubusercontent.com/42646958/51423130-5fe33380-1b80-11e9-88d8-074ac1cb4154.jpg)

![screenshot_2019-01-18_23-29-12](https://user-images.githubusercontent.com/42646958/51423117-36c2a300-1b80-11e9-892c-eb7698d06136.jpg)

### Steps to reproduce

This wasn't reproduced in groups of messages before or after this series of three messages. Once I received more messages in this chat, this issue was not able to be reproduced.

- Mouse over second message in a series of messages received in individual chat.

When scrolling through messages, I didn't anticipate that the lock icon would move; I expected the icons to remain static while scrolling.

**Comment by turt2live** [comment]
This icon no longer exists
