### ISSUE TITLE
Assorted console errors in chromium/firefox

### ISSUE THREAD

**Issue by grinapo** [vector-im/element-web#8174]
### Description

As we talked on #riot:matrix.org the console contains a lot of red stuff, which may or may not hurt performance. I try to attach debug logs per your instruction.

Feel free to close.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chromium 72.0.3626.7, Firefox nightly
- **OS**: Debian GNU/Linux
- **URL**: private server, latest version of riot-web (riot-web version: 0.17.9-rc.1; olm version: 3.0.0)

**Comment by ara4n** [comment]
received; thanks

**Comment by lampholder** [comment]
Perhaps related (I haven't verified this _at all_, it just rang a bell): https://github.com/vector-im/riot-web/issues/7409

**Comment by aaronraimist** [comment]
@lampholder those warnings have been disabled so they shouldn't appear anymore (even though they are still relevant), probably not related this issue

**Comment by jryans** [comment]
I believe we're resolved a good number of these, so I believe this issue can be closed now.
