### ISSUE TITLE
Missing unread messages notification when room view filtered

### ISSUE THREAD

**Issue by rxl881** [vector-im/element-web#8179]
- **Browser**: Chrome
- **OS**: Ubuntu,

### Description

When the room view is filtered (on experimental) it is not obvious that there are unread notifications in other rooms (until the filter is cleared). This is different from the old behaviour.

### Steps to reproduce

- Enter some filter text in the "filter room names" input box.
- Notification badges indicating that there are unread messages in other rooms are no longer visible.

I have given @lampholder animated GIFs of the behaviour (not attached here due to unredacted content).

Although this is a relatively small change, it is very important for my workflow as I use the filter to find and switch between rooms and typically don't clear the filter that often, which can result in notifications being missed. This might be an even bigger problem on Electron, where tab notification badges are not present.

**Comment by t3chguy** [comment]
The room list filter is gone
