### ISSUE TITLE
Image button content not (always) centered

### ISSUE THREAD

**Issue by rxl881** [vector-im/element-web#8185]
- **Browser**: Chrome
- **OS**:  Ubuntu

### Description

Minor UI issue, but it seems that the content of the round buttons / badges for notifications and adding rooms are not (always?) quite centred.

It has proven a little difficult to capture an image of this in practice (especially for notifications), but I think that I have managed to capture it in the following image.

For the add room button the plus symbol seems to be consistently too close to the bottom edge (seems to be fixed by setting the height of .mx_RoomSubList_addRoom to 17px, rather than 16px).

The notification badge content seems to be inconsistently centred horizontally (compare the content of the two '2's in the following image -- this one is more subtle.

![selection_037](https://user-images.githubusercontent.com/6763606/51480021-d736e400-1d87-11e9-8ab3-9b2659dadd13.png)

**Comment by turt2live** [comment]
I think this was fixed
