### ISSUE TITLE
Bing/notification highlight colour isn't strong enough

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#8189]
I find the highlight colour isn't strong enough to stand out while scrolling, in fact it looks slightly fainter than the normal text to my eyes. The colour also looks similar/identical to that used for some of the display name colours.

What it is at the moment:

![screenshot from 2019-01-21 15-38-28](https://user-images.githubusercontent.com/8428120/51484122-a0b29680-1d92-11e9-88a4-a8e3f149296e.png)

I think just changing it to `red` is quite an improvement, though possible still a bit dull:

![screenshot from 2019-01-21 15-41-42](https://user-images.githubusercontent.com/8428120/51484322-2898a080-1d93-11e9-8ebb-ed1f1007680c.png)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/13963
