### ISSUE TITLE
Option to flag my messages to not display flair

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8196]
I recognize this might be a problem specific to me, and that it requires some amount of spec work. Opening here so it can be prioritized from the UI side backwards (or closed as a single-person problem that doesn't really benefit anyone else).

Sometimes when speaking in a room I want to take my +matrix:matrix.org flair off during a conversation because of the multiple hats I carry around. It doesn't make sense to go to my settings and disable flair while I'm in that conversation because 1) it takes far too long to replicate to everyone else and 2) when I re-enable it, the historical record will be wrong. 

I imagine this would be some sort of extensible event thing to flag a message to not have (or have) specific flairs.

**Comment by lampholder** [comment]
Hmm, yeah - could be implemented as an enhacement to the composer and message events could allow the supressing of association with a given piece of flare.

I'm going to put this as a P3 feature - we can review that if there's a lot of interest in in it :)

**Comment by turt2live** [comment]
I'm closing this because Groups don't really exist anymore. If someone would like this for Spaces, please open a new issue.
