### ISSUE TITLE
Allow variables in room names

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#8211]
If room names can accept variables (especially %me% and %them%), it would be possible to have rooms such as '%them% - work' vs. '%them% - private', which would translate into significant names on all sides.

**Comment by t3chguy** [comment]
This seems like it'd be not as powerful as https://github.com/vector-im/riot-web/issues/3130

Because what if One person wants it to be `Person B - Work` and the other wants it to be `Person A - Praca` (Work in a different language). Personal room names would be a much more flexible solution to this problem.

**Comment by Biep** [comment]
It is orthogonal to that, though having more useful generic names ought to diminish the need for pet names a little.  I'd still like to be able to change to a pet name, however flexible the generic name.

Flexible generic names are about less _need_ for changing the local name; pet names are about the _ability_ to change it.

**Comment by Biep** [comment]
As a counsellor, I often want to observe interactions.  So I want to create rooms and invite two parties (e.g. spouses), and give the room a name such that each spouse sees the name of the other - and not "Biep and <spouse name>".  I want them basically to "forget" my presence and interact naturally.
Of course there still is the "read" marker to the right indicating that I am there lurking..

**Comment by t3chguy** [comment]
If you still care about this, please open an issue in https://github.com/matrix-org/matrix-spec
