### ISSUE TITLE
requests start to run against public_baseurl

### ISSUE THREAD

**Issue by verymilan** [vector-im/element-web#8232]
I am running synapse with an nginx reverse-proxy.
Since the documentation states *"The public-facing base URL for the client API (not including _matrix/...)"*, i configured the `public_baseurl` to a subdomain pointing directly to the box where synapse is running on.
I don't know if it is a weird coincidence but since the latest release of riot-web, new logins started to fail because they got redirected to the public_baseurl and ended in a 405.

Stangely enough, i changed this setting to the main url (with the reverse-proxy at /_matrix) and it seems to work just fine again.
At this point i don't know if i may broke something i am not aware of yet or if i simply fixed a bad setting in my synapse configuration, so i'd appreciate clarification on what just happened / what this setting is for - i had it like that for maybe a year or so without issues before.

Regards! :3

**Comment by kittykat** [comment]
I'm going to close this for now as it sounds like an issue in synapse. Please re-open or file a new issue with more details if you feel differently.
