### ISSUE TITLE
Redesign: removing an image causes a large gap at the bottom of the chat window

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#8242]
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

![image](https://user-images.githubusercontent.com/1342360/51627631-a64ae080-1f3a-11e9-8c9e-d37fcf0cb010.png)
A large image was removed in the room. The messages moved up but the scroll view still has the same height.

**Comment by turt2live** [comment]
Presuming fixed (I can't reproduce)
