### ISSUE TITLE
Custom Status: My status sometimes reverts to a previous status

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8243]
This is now happening reliably on refresh on my main account - I haven't been able to reproduce this on a test account so far, suggesting it might be a function of the number of 1:1s (perhaps)

**Comment by turt2live** [comment]
it should be using the most recent event it sees, which has me wondering if this is part of the whole "client and server state mismatch" class of bugs.

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
