### ISSUE TITLE
desktop app now doesn't honour self-signed certs imported into Windows?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#8260]
As of 0.17.x apparently

**Comment by mbaeten** [comment]
Can confirm for Linux & Windows. 0.17 is correct (if in doubt)

**Comment by lampholder** [comment]
Do we want the electron app to support self-signed certs?

I guess the answer to that is "probably". For anyone running their own HS, federation will soon require not self-signed certs, so letsencrypt wrangling is going to be a basic required skill.

However, for people wanting to start developing either synapse or riot against a local synapse install, the ability to run with self-signed certs is one fewer hurdle to hurdle.

**Comment by mbaeten** [comment]
What about intranet usage, e.g. for company-intern messaging? Is that even possible?

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/3003
