### ISSUE TITLE
MELS should collapse invited+joined+left repeat patterns (e.g. IRC bridged users in private rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8261]
Membership `EventListSummary` (MELS) should collapse invited+joined+left repeat patterns (e.g. IRC bridged users in private rooms

**Comment by MadLittleMods** [comment]
Duplicate or highly related to https://github.com/vector-im/element-web/issues/5720

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/5720
