### ISSUE TITLE
Setting the canonical alias to an empty string renders an empty event

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8272]
![image](https://user-images.githubusercontent.com/1190097/51782401-c74f3500-20e4-11e9-96fe-60e56e8987e9.png)

**Comment by t3chguy** [comment]
![image](https://github.com/vector-im/element-web/assets/2403652/e3cbea1a-94fb-429f-93ea-194b622a1a85)

No longer the case

![image](https://github.com/vector-im/element-web/assets/2403652/9f7e09c2-4ee1-47e9-a2b0-9ad3d63edde3)
