### ISSUE TITLE
Redesign: Expanding MELS leaves a gap at the bottom

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8289]
https://matrix.to/#/!XIydWLOEJvcDBKwWKE:matrix.org/$154870374840571lanqS:maunium.net?via=matrix.org&via=disroot.org&via=matrixim.cc

**Comment by bwindels** [comment]
should only happen if you expand while somebody is typing.
to fix it we'd have to clear the min-height when you click collapse again...

**Comment by turt2live** [comment]
Presuming fixed (I can't easily reproduce)
