### ISSUE TITLE
Add server name as contextual label to username input

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8295]

**Comment by t3chguy** [comment]
Issue with this is that as per https://github.com/vector-im/element-web/issues/9648#issuecomment-730447993 - the MXID is not guaranteed to be `@localpart:server_name` and as a client we cannot query a HS URL for its `server_name`

**Comment by turt2live** [comment]
I don't think this has enough information to be actionable anymore, so closing in favour of a fresh issue with new information about the request.
