### ISSUE TITLE
Add server name input using .well-known for custom servers

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8310]

**Comment by jryans** [comment]
To clarify, a "server name" input would take something like `example.com` and then do `.well-known` discovery (instead of asking for HS / IS URLs).

This is related to https://github.com/vector-im/riot-web/issues/8309, but both login and registration have a "server name" input in the latest designs.

**Comment by turt2live** [comment]
fwiw this is fairly simple to support even without adding a whole new field: we can reuse the custom server selector and support server names in the input fields. Question would be how we do discovery on the identity server (if we even need to?)
