### ISSUE TITLE
Using CMD+A & CMD+X in the composer causes weirdness

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#8330]
Haven't quite debugged this properly, but typing out a message then hitting CMD+A & CMD+X can cause any of (a) the right menu to momentarily jiggle (b) the timeline to flash white or (c) the timeline to scroll up. Doesn't happen in every room. Safari.

**Comment by lampholder** [comment]
I haven't been able to reproduce this on chrome at least

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment]
Assuming no
