### ISSUE TITLE
Users are starting to see blank thumbnails

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8333]
I know Bruno was/is having this problem, and it appears that others are having it too. Reported on Arch/FF

**Comment by lampholder** [comment]
Bruno was also having this problem on linux/ff.

I haven't been able to reproduce (uploading a bunch of different images to a range of encrypted/unencrypted rooms)

**Comment by Ryonez** [comment]
Trowing this in as a possible related issue:
https://github.com/matrix-org/synapse/issues/2182

**Comment by turt2live** [comment]
This does not have enough information to be a useful ticket in 2021/22 - if people are still seeing this, please open a new issue with more details.

**Comment by karolyi** [comment]
I think this might be related to #9605
