### ISSUE TITLE
/ command for custom status

### ISSUE THREAD

**Issue by fladd** [vector-im/element-web#8354]
- **Browser**: Chrome, Safari, Firefox? which version?
All of them

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
All of them

### Description
/ command for the custom status (probably /status makes sense here).

### Steps to reproduce

n.a.

Describe how what happens differs from what you expected.
I expect it to exist. It doesn't.

Log: sent/not sent?   No

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
