### ISSUE TITLE
setting in which room/community to show custom status

### ISSUE THREAD

**Issue by fladd** [vector-im/element-web#8355]
- **Browser**: Chrome, Safari, Firefox? which version?
all
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
all

### Description

It would be good to have the option to set in which room/community custom status is shown. One might use status for work only (e.g a specific community), or one just does not want to boradcast status in some large general rooms (e.g. #riot).

### Steps to reproduce

n.a.

Describe how what happens differs from what you expected.
Feature doesn't exist.

Log: sent/not sent?    no

**Comment by turt2live** [comment]
This labs flag has been removed. If required for a future feature, please open a new issue with fresh information.
