### ISSUE TITLE
Unable to upload Sims 4 .png screenshots to unencrypted rooms. Renaming or zipping the file works.

### ISSUE THREAD

**Issue by magykjames** [vector-im/element-web#8357]
### Description

When uploading a Sims 4 screenshot with a .png extension, the upload fails. You can rename the file to any other photo extension and it still fails. If you remove the extension, zip it, or give it a non-image extension, or upload to an encrypted room, the upload succeeds.

- Issue affects both web and desktop versions of the Riot.im client.
- Issue happens on multiple PCs and with multiple accounts.

### Steps to reproduce

- Take a screenshot in The Sims 4.
- Try sending it to a room.
- Upload fails.
- Rename or zip the file to give it a non-image extension.
-- Upload succeeds.
- Encrypt the room and send file as .png.
-- Upload succeeds.

Log: sent/not sent?    

### Version information

- **Platform**: 

For the web app:

- **Browser**: Firefox 64
- **OS**: Windows 7 Pro x64
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows 7 Pro x64
- **Version**: 0.17.9
![01-31-19_5-49-51 pm](https://user-images.githubusercontent.com/20302956/52095619-5054e900-2589-11e9-967f-c3a051b10db7.png)

**Comment by lampholder** [comment]
This appears to be failing at the synapse level...

```
builtins.AttributeError: 'PngStream' object has no attribute 'chunk_prOP'
```

If I (fairly aribitrarily) convert the png to a tiff and then the tiff back to a png in GIMP, the new png loads fine.

![sims_via_gimp](https://user-images.githubusercontent.com/1922197/52119752-0b28c980-2612-11e9-9af6-4c6e9cf2251c.png)

**Comment by t3chguy** [comment]
If you are still seeing this issue I suggest opening a bug in https://github.com/matrix-org/synapse/
