### ISSUE TITLE
Key Backup setup has an invisible back button

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8362]
The key backup setup modal seems to have an invisible back button that will mess you up if you tab to it and press <kbd>Enter</kbd>.

To reproduce this:
- start a new key backup
- type in your passphrase
- press tab
- press enter
- get surprised at the message telling you setting up key backup is important

The same happens if you <kbd>Tab</kbd><kbd>Enter</kbd> on the next screen, too - it takes you back to the 'set a passphrase' stage of the flow.

**Comment by michaelkaye** [comment]
So the precise issue above is not present any more - the back button is clearly displayed, and while entering the passphrase and hitting tab does take you to the "go back" button - it's at least visible on screen that you could be sent there.

A related issue is that using tab to move between the items in the dialog is not very clear as to what's selected - especially the red "go back" button has no visible marker at all at present.

This is a problem throughout the app and not just here - any time you tab to a red button in the settings for instance, there's no visible highlight. 

The problem as a whole is being looked at more generally.
