### ISSUE TITLE
accepting invites can land you in an entirely blank timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8372]

**Comment by ara4n** [comment]
i've  seen this ~3 times today:

![meh](https://user-images.githubusercontent.com/1294269/52156122-9774d400-2686-11e9-86f7-3b18cf1425d4.jpg)

the room has no scrollbar

**Comment by ara4n** [comment]
@richvdh this might be yet another instance of synapse being weird on delivering membership changes perhaps? (given i'm still shown as invited in the RightPanel, despite having accepted the invite)

**Comment by richvdh** [comment]
presumably related to https://github.com/matrix-org/synapse/issues/4533 / https://github.com/matrix-org/synapse/issues/4422
