### ISSUE TITLE
Improve discoverability of rageshake

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#8389]
Now that we have the lifebuoy it seems counterintuitive to have to dig through settings to rageshake. Should we iterate on the modal to also include rageshake?

**Comment by lampholder** [comment]
Yes yes yes - I even went to the buoy to find it before remembering where I had to go.

**Comment by t3chguy** [comment]
Its now under Feedback

![image](https://user-images.githubusercontent.com/2403652/110151934-fc0c3b00-7dd8-11eb-99ab-b2c3b4644a96.png)
![image](https://user-images.githubusercontent.com/2403652/110151949-00d0ef00-7dd9-11eb-983b-1a2ba525dd6a.png)
