### ISSUE TITLE
Update https://github.com/vector-im/policies/blob/master/docs/matrix-org/privacy_notice.md#28-who-can-see-my-messages-and-files

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8411]
Change the tense https://github.com/vector-im/policies/blob/master/docs/matrix-org/privacy_notice.md#28-who-can-see-my-messages-and-files

**Comment by lampholder** [comment]
Specifically, we need to replace:

> In future we may allow users to optionally backup an encrypted copy of their keys on the Service to aid recovery if they lose all their keys and devices. This key backup would be encrypted by a recovery key that only the user has access to. This means that nobody, even New Vector engineers (employees and contractors) can see your message content in our database, and if you lose access to your encryption keys you lose access to your messages forever.

with:

> Users can optionally back up an encrypted copy of their keys on to the Service to aid recovery if they lose all their keys and devices. This key backup is encrypted by a recovery key that only the user has access to. Nobody, even New Vector engineers (employees and contractors) can see your encrypted message content in our database. If you lose access to your encryption keys you lose access to your messages forever.

**Comment by t3chguy** [comment]
This got done
