### ISSUE TITLE
Leaves sometimes show the MXID rather than display name

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8419]
This may be a duplicate. 
![](https://t2l.io/_matrix/media/v1/thumbnail/matrix.org/DMEsKKOkQvjmkMmskmcnuXGO?width=800&height=600)

**Comment by lampholder** [comment]
The closest I could find was https://github.com/vector-im/riot-web/issues/7853 so I don't think this is a dup.

**Comment by weeman1337** [comment]
I tried to join and leave some rooms and was not able to reproduce the issue.

Considering the age of the issue, I would assume that it has been fixed.
