### ISSUE TITLE
Username notification filter is too lax

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/element-web#8431]
My username is `@me:jonas-schuermann.name`, and whenever someone uses the word "me", I get a notification. I know that I can disable notifications for my username and I did so, but now I won't get a notification even if someone mentions my full username.

riot-web version: 5030410dd647-react-f517928d76bf-js-9e12fc4d7d42 (current https://riot.im/develop)

**Comment by osnyx** [comment]
Having carelessly chosen my matrix ID as `@os:domain` I am affected by that as well when hanging around in tech rooms.

IMHO mentioning someone via their user name shall only be done through their full mxid, not just by writing down the local part of it and leaving out the domain. Or at least there shall be an option for that.

**Comment by osnyx** [comment]
> Also, is this the only version of this issue around?

I think I just subscribed to ~10 issues more or less related to wrong substring (or whole local part) matches in domain name or user name causing a mention. I guess all of them would indeed be resolved by requiring the full mxid like in MSC3517 for a mention to be triggered, at least by default.

**Comment by ShadowJonathan** [comment]
Could you maybe link them here? It'd help with an issue wrangler being able to deduplicate this problem across issues.

**Comment by osnyx** [comment]
These are the ones I found similar enough to make me subscribe them, they do differ in their main aspects though:

- https://github.com/vector-im/element-web/issues/8497
- https://github.com/matrix-org/matrix-spec/issues/550
- https://github.com/vector-im/element-web/issues/4973
- https://github.com/vector-im/element-web/issues/9302
- https://github.com/vector-im/element-web/issues/19545

All other related issues I found where alredy closed.

**Comment by turt2live** [comment]
Unfortunately this is a spec issue as the notifications system is server-side (or intended to be server-side). Possibly once the notifications system is replaced it'll be fixed, however for now please upvote https://github.com/matrix-org/matrix-spec/issues/550 or similar to try and foster contributions in this area.
