### ISSUE TITLE
Auth dialog after starting keybackups is ugly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8436]
<img width="685" alt="screenshot 2019-02-07 at 11 07 07" src="https://user-images.githubusercontent.com/1294269/52407540-8681f380-2ac8-11e9-8a54-e705c44744fc.png">

**Comment by lampholder** [comment]
You see this whenever you do anything that requires interactive auth (deleteing a device from the devicelist, modifying your cross-sign keys)

**Comment by t3chguy** [comment]
This got fixed
