### ISSUE TITLE
Greyed out E2E icon in the composer is confusing.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8437]
<img width="387" alt="screenshot 2019-02-07 at 11 14 28" src="https://user-images.githubusercontent.com/1294269/52407968-9bab5200-2ac9-11e9-89d6-2896076c459f.png">

I think the icon is too large, and the fact that it's greyed out (despite it being a warning!) makes it look like the warning is somehow disabled or irrelevant.

I think we should switch to smaller green/red icons to remind the user that they're encrypted and trusted (or not).

**Comment by yannicka** [comment]
The icon has changed to a shield (here on Element Web 1.7.14):

![image](https://user-images.githubusercontent.com/22885898/100515999-e7d4f400-3180-11eb-8c2e-93cac0533ca8.png)

**Comment by t3chguy** [comment]
and the shield now matches the colour of the rest of the icons around the app, so warning state would be red.
