### ISSUE TITLE
register page on riot-web develop makes two calls to the /register endpoint

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#8457]
When you first open the page, it makes two calls to the /register endpoint with an empty `auth` dict, which will create two UI auth sessions on the server

**Comment by jryans** [comment]
This is related to (but not the same as) #8458.

**Comment by turt2live** [comment]
no longer an issue
![image](https://user-images.githubusercontent.com/1190097/167234545-1277f1cd-7f13-4c52-b180-7d1ab207cc77.png)

preflight+actual request is normal, whereas this issue was describing a case of 2 preflights and 2 actual requests (4 lines).
