### ISSUE TITLE
Can't verify messages whose keys were forwarded

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#8470]
We currently never show messages whose keys have been forwarded from another device as validated, even if we've verified all the devices in question, 'cos the js-sdk doesn't implement verification of the forwarding key chain: https://github.com/matrix-org/matrix-js-sdk/blob/master/src/crypto/index.js#L588

**Comment by lampholder** [comment]
I can't quite fully reason through whether we'll need to fix this as part of our E2E UX push, or whether it will almost always not be a problem if all the other components (existing and pending) are doing their job properly. One to revisit later.

**Comment by dbkr** [comment]
I think it depends whether we're relying on key sharing. If we're expecting key sharing to never normally be necessary then fixing this is not so important.

**Comment by ShadowJonathan** [comment]
Messages that were forwarded from different devices currently show as (properly) verified on other devices, is this still applicable?

**Comment by kittykat** [comment]
@dbkr I'm going to close this for now as it seems resolved, could you please re-open if it's still valid?
