### ISSUE TITLE
Sending email invite to the same person after they've already accepted it does not use their MXID

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8489]
1. Invite friend@example.org
2. Friend accepts invite, associating the email with their account
3. Invite friend@example.org to another room
4. Friend receives another email (wrong behaviour: should invite the Matrix user)

**Comment by lampholder** [comment]
Does this have to be in the same room? Did Friend already have a matrix account?

**Comment by turt2live** [comment]
Different rooms. I'm not sure if it matters if Friend had an account previously, but they did before step 1 and just added the email to their account in this case.

**Comment by kittykat** [comment]
Recent discussion in (I think) Delight channel was that there should probably be a check about when user last logged in stale accounts are pinged by email and recently used accounts are not.

Needs re-testing with two emails to an existing account (no emails should be sent atm) and two emails to addresses which are not associated with accounts.

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23353
