### ISSUE TITLE
Badges on communities need design

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8509]
The sizing of the badge seems way too big, and there's no border.

<img width="60" alt="screenshot 2019-02-10 at 23 01 33" src="https://user-images.githubusercontent.com/1294269/52541001-f70a6800-2d87-11e9-8c12-fc525ec2d52d.png">

**Comment by aaronraimist** [comment]
Related: #8509

**Comment by SimonBrandner** [comment]
Communities are being replaced by spaces
