### ISSUE TITLE
An error with a rubbish error message adding rooms to a group.

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8535]
### Failed to add the following rooms to +groupname:domain.tld

!akdfjklhdfalhdfl:domain.tld !uogifdgfdhglfkhgg:domain.tld !dkshfkjdshgeagfsg:domain.tld

---
I don't know why it failed, or which rooms failed (3 of ~12 didn't invite properly)

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/7785

**Comment by SimonBrandner** [comment]
Spaces are now in beta
