### ISSUE TITLE
Markdown'd links without http(s):// are relative

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#8547]
### Description

Entering:

```
[www.bla.com](www.bla.com)
```

produces a link to https://riot.im/develop/www.bla.com.

However:

```
[www.bla.com](https://www.bla.com)
```

works as intended.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: https://riot.im/develop

**Comment by lampholder** [comment]
Is this wrong? I think this is probably (usually) desired markdown behaviour. People wouldn't usually have a good reason to make a relative link in their riot conversation, but I'd rather we avoid specialcasing the commonmark behaviour :)

**Comment by yannicka** [comment]
Isn't this an upstream issue (or the intended behaviour)?

By testing this on the [reference implementation of CommonMark](https://spec.commonmark.org/dingus/), I was able to reproduce the issue.

**Comment by anoadragon453** [comment]
I guess it's expected ¯\\\_(ツ)_/¯
