### ISSUE TITLE
On answering an invite to a DM, scrollback is entirely missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8572]
It looks like Riot is either not calling /messages on joining the room to backpaginate the timeline, or the server is lying about there not being any scrollback immediately after you having joined.  Hitting refresh however fixes it.

**Comment by ara4n** [comment]
reproduced this 1 in 3 times.

**Comment by ara4n** [comment]
rageshooked

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/8372
