### ISSUE TITLE
Invite to a DM showed the mxid rather than the displayname + avatar

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8573]
tom invited me to a dm with a test user, but the DM invite displayed in my invites was to his mxid rather than having any eyecandy for displayname or avatar.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/1604

**Comment by turt2live** [comment]
This will almost certainly be a server-side issue that we're unable to action. Closing pending a new issue with further information.
