### ISSUE TITLE
We don't set device display names when registering

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#8575]
Only when logging in.

The fun part about this is that we can easily send the parameter, but because they are cached by the server, the device you click the registration email link on will get the display name from the one you started the registration on. :/

**Comment by lampholder** [comment]
We should think about and resolve this - no device name makes some of the e2e ux very confusing.

**Comment by janvlug** [comment]
See also issue #2295.

**Comment by aaronraimist** [comment]
Was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3992
