### ISSUE TITLE
canceling the register dialog to chat with riot bot doesn't cancel the action

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#8577]
From the landing (sign-in) page, click 'chat with riot bot'. It tells you you need to register. Click 'cancel'. Sign in. After signing in, you'll still be dumped into a chat with riot-bot even though you cancelled.

**Comment by lampholder** [comment]
Wait, isn't this because _every_ new user gets a chat with riot bot? Or do you mean after logging in you get a new chat with riot bot?

**Comment by t3chguy** [comment]
Cannot repro

1. Click chat with riot-bot
2. Click cancel
3. Log in
4. Observe no new rooms have been created

**Comment by kittykat** [comment]
Closing as I haven't seen the chat with riot-bot option (it was probably removed in one of the designs), please re-open if the issue still persists.
