### ISSUE TITLE
New animation for sending a message

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#8588]
### Description

The current UI for indicating that a message is being sent is to have greyed out text, then bright white text. This is alright, but a bit boring, and may be unusable for some people that can't pick out contrast that well.

As we've now gotten rid of showing the 'green lock' for encrypted messages, we have some room to the left of messages that you send. Thus I propose in there we put some sort of loading indicator.

I'm not a huge fan of having the current spinner put in there (it doesn't look that great at a reduced size). Instead, something like Signal's loading indicator is both simple and attractive:

![image](https://user-images.githubusercontent.com/1342360/52729549-4bdcf700-2fb1-11e9-8792-df482eb996b9.png)

It just spins around until it sends, at which point it could disappear.

**Comment by lampholder** [comment]
I think a small change like this could have a large impact in the feel of the app

**Comment by yannicka** [comment]
The current color change is too subtle.

**Comment by robintown** [comment]
Closing since we now have actual sending indicators
