### ISSUE TITLE
you can't open settings if you're not in any rooms

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#8596]

**Comment by dbkr** [comment]
It looks like we are never getting our own user put into the local store since the server never sends it (and settings obviously tries to get the local user and panics if it can't)

**Comment by dbkr** [comment]
Looks like this is probably only relevant to matrix.org which has presence disabled, so you'd only get this if you were on matrix.org *and* didn't have a chat with riot-bot.

**Comment by dbkr** [comment]
`src/components/views/settings/ProfileSettings.js` shouldn't be trying to get the avatar url from local user in the store, as these will only be there if the presence event is there: it should be querying the profile endpoint.

**Comment by aaronraimist** [comment]
I can't reproduce this.
