### ISSUE TITLE
Custom tags should not filter rooms out of the main LeftPanel by default

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8609]
I believe @turt2live's feedback on making matrix-org/matrix-react-sdk#2575 more usable for actual custom tag powerusers is:

 * Show all rooms by default in the RoomList
 * As you select custom tags, they "pull rooms" out of the overall roomlist in order to file them in a dedicated section for that tag.  The  rest of the list is still present.
   * (or should we filter the whole list to just be that tag?)

**Comment by turt2live** [comment]
that's pretty much what I wanted, yes. I do like the idea of treating tags similar to communities though: the tags you select end up filtering `Rooms` instead of being pulled.

**Comment by vberger** [comment]
I'm much in favor of "tags as filters" as well, with full support of "multi-tags" as well.

In short : a room can have as many tags as the user wishes, and selecting multiple tags in the UI would be an "intersection" filter, so only the rooms having all of the selected tags would be displayed.

**Comment by alphapapa** [comment]
Please do not invert the room user-tags paradigm this way.  I don't want to have to repeatedly select and de-select tags to find the rooms I'm looking for.  That requires lots of clicking, and it hides rooms that I want to see.  It would not be as useful.

The way the "old" Riot used to work was great: each room user-tag created a group in the UI, and all of the tag groups were visible, so I could see all of my rooms at once, and I could collapse groups I wasn't interested in.  No rooms were *actually hidden*, just in collapsed, still-visible groups.  (Yes, I had to set those tags outside of Riot; that's beside the point.)

**Comment by turt2live** [comment]
Custom tags are replaced by spaces, and removed formally in https://github.com/matrix-org/matrix-react-sdk/pull/8027
