### ISSUE TITLE
Consider an option to keep grey badges on rooms but not raise desktop notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8610]
For people that want the quiet nature of 'Mentions Only' without losing the number of unread messages

**Comment by carriejv** [comment]
This honestly feels like it should be default behavior. Having no indicator of new messages at all is pretty counter-intuitive UX.

+1

**Comment by lampholder** [comment]
Not sure whether we'd want to implement exactly this, but sorting our notifs behaviour would be super good.

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/528
