### ISSUE TITLE
Dynamic favicons

### ISSUE THREAD

**Issue by evoL** [vector-im/element-web#8616]
The new blue icons are pretty nice!
However, I'm not a fan of the default favicon, because the color is pretty bright and it makes me think that I have unread messages all the time.

Would you consider having a toned down favicon (e.g. gray) when there are no unread messages?
It can revert to the current blue one once there are unread messages.

Bonus feature idea: make it stand out even more (red?) if there are mentions.

**Comment by nadonomy** [comment]
(Just to capture some of the brief discussion in #riot:matrix.org)

Thinking out loud it might make more sense to use:

- A grayscale favicon for offline
- A full colour one for 'normal'
- One with a dot for notifications (grey or red depending on outstanding)

P.S. Stripping the redesign label as this issue predates it, and we're on the precipice of release!

**Comment by evoL** [comment]
The ideas make sense and I agree it's definitely worth exploring. The dot suggestion is very good, because it helps colorblind users more. (Yay for accessibility!)

Just to add another angle to the discussion: here are the icons I'm looking at most of the time: 
![image](https://user-images.githubusercontent.com/155995/52779074-c0fb0b80-3047-11e9-82ed-b8bba4c1b747.png)

The third topmost icon is Hangouts Chat, which I'm using at work. Here's what happens when I receive a message there:
![image](https://user-images.githubusercontent.com/155995/52779468-85ad0c80-3048-11e9-90c9-14f36d69f864.png)

Riot's icon color is very similar to Chat's unread message one, which is probably what's causing me to check for unread messages in Riot as well :stuck_out_tongue:
It would be nice if the full-color version were a bit less bright for that reason.

**Comment by kittykat** [comment]
I'm going to close this issue for now as the favicon and notifications are both different. If you would like to see futher improvements, please file a new issue against the current favicon :+1:
