### ISSUE TITLE
Hide CSS scrollbars after a few seconds of inactivity

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#8627]

**Comment by lampholder** [comment]
Where don't we do this at the moment?

**Comment by nadonomy** [comment]
Room list & timeline.

**Comment by nadonomy** [comment]
Also member list & settings, so possibly everywhere?

**Comment by lampholder** [comment]
Ah - we do on firefox. On chrome they seem to appear on hover. Do you think this is something we need to chagne?

**Comment by aaronraimist** [comment]
This should be fixed since Gemini is gone right?

**Comment by t3chguy** [comment]
Well we hide them instantly now, purely in CSS using overlay scrollbars following browser behaviour. It kinda sounds like this issue asks for them disappearing to be delayed

**Comment by SimonBrandner** [comment]
This seems to be no longer relevant
