### ISSUE TITLE
Use configurable logo inside the welcome page

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8636]
The logo is configurable (for non-welcome screens) and the welcome page is configurable, but I think most people would expect the default welcome page to also pick up the configured logo.

**Comment by Zauberstuhl** [comment]
The the hyper-reference for the welcome-logo has to be configured too.
Also I think the message `Welcome to Riot.im` is a bit misleading if it is a custom domain.

For `chat.feneas.org` I patched it like following:

```
sed -i 's#\(Riot.im":.*\)Riot.im#\1chat.feneas.org#' $wwwdir/i18n/*.json
sed -i 's#\(https://\)riot.im#\1feneas.org#' $wwwdir/welcome.html
sed -i "s#welcome/images/logo.svg#$logo#" $wwwdir/welcome.html
sed -i 's#height: 54px;#height: 200px;#' $wwwdir/welcome.html
```

I suggest adding to the branding hash:

* authLogoUrl
* authLogoHrefUrl

and using the `brand` in the i18n files as a replacement for the static `Riot.im`.

Thoughts?

**Comment by jryans** [comment]
> I suggest adding to the branding hash:
>
>  * authLogoUrl
>  * authLogoHrefUrl

From this, it sounds like you'd prefer to control the welcome page logo and existing auth header logo separately? If so, maybe we'd end up with:

* authHeaderLogoUrl (existing)
* welcomeLogoUrl
* welcomeLogoHrefUrl

However, if you want to customize everything in this way, is it actually helpful to add all these specific branding knobs, or is it easier in the end to just edit the template like you did? (I'm not sure, so let's try to talk it out!)

**Comment by Ryonez** [comment]
Extending the branding options would be better.
I use the docker image and can't change the files so easily. It also makes sense to have all of the configuration options in the config file.
