### ISSUE TITLE
Using tag folds resets custom tag container sizes

### ISSUE THREAD

**Issue by fladd** [vector-im/element-web#8644]
- **Browser**: Firefox 66
- **OS**: macOS

### Description
Having changed the default size of tag containers (e.g. PEOPLE, ROOMS), when then closing the tag folds, the size of the tag containers is not the same after reopening them as they were before
closing them.

### Steps to reproduce
-  make PEOPLE smaller such that only 3 contacts are visible
- close all tag containers
- reopen them one by one from the top
- PEOPLE will be much larger than 3 contacts, and ROOMS (the last opened one) will only have a single rooms visible (was 8 before folding)

I expect the custom size I set before closing the folds to be restored when I open them.

Log: not sent?

**Comment by t3chguy** [comment]
Custom tags are gone
