### ISSUE TITLE
Incorrect icons on Debian

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#8656]
I get either small or multiple riot-web icon sizes . Sharing examples of both. What is needed is moving to Ayatana indicators which Debian is going to use in Debian buster. 

https://wiki.debian.org/Ayatana/IndicatorsTransition

A good example of the ones is the guake system tray icon 

```
$ ls -lh /usr/share/guake/data/pixmaps/guake-notification.png /usr/share/guake/data/pixmaps/guake-tray.png
-rw-r--r-- 1 root root 3.0K Oct  2 09:07 /usr/share/guake/data/pixmaps/guake-notification.png
-rw-r--r-- 1 root root  987 Oct  2 09:07 /usr/share/guake/data/pixmaps/guake-tray.png
```

In Debian it has only one 

/opt/Riot/resources/webapp/vector-icons/favicon-96x96.png . I guess this is what it uses in the sytem-tray. 

Have no clue. 

![riot-1 0-systemtray-issue](https://user-images.githubusercontent.com/727626/52816569-773b1100-3099-11e9-97e2-dc6f00c80fc4.png)

and 

![riot-1 0-systemtray-fuzzy-icon](https://user-images.githubusercontent.com/727626/52816575-7d30f200-3099-11e9-9f0e-50abaf95899a.png)

**Comment by kittykat** [comment]
@shirishag75 are you still experiencing this issue?

**Comment by robintown** [comment]
Closing due to lack of info, and the icon having changed since 2019
