### ISSUE TITLE
Peeking has regressed and isn't skinned properly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8674]
We no longer have a MemberList when peeking.

Also, we have the oldschool lozenge buttons for Login & Register.  Instead, this should be skinned to match the designs in zeplin.

**Comment by t3chguy** [comment]
Lack of memberlist: https://github.com/matrix-org/matrix-react-sdk/commit/dd911d18cb2209a8db603732919e602528f25f68

**Comment by turt2live** [comment]
The memberlist seems intentional now: https://github.com/vector-im/riot-web/issues/10769

**Comment by t3chguy** [comment]
Closing as matches design
