### ISSUE TITLE
Reports of typing notifications not sliding in nicely on FF 65

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8675]

**Comment by Cadair** [comment]
I can reproduce this.

**Comment by lampholder** [comment]
It looks like this in FF 67:
https://matrix.lant.uk/_matrix/media/v1/download/lant.uk/txKVExyKwyiyPKehlDJIuENo

How does it look in 65?

**Comment by turt2live** [comment]
Apaprently they don't slide in on Chrome either (like your video). Are they even supposed to slide in?

**Comment by SimonBrandner** [comment]
This seems to be no longer relevant
