### ISSUE TITLE
UI for enabling encryption needs to be more obvious

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8678]
c.f. https://banana.dog/@migratory/101593735981017517

@nadonomy how about turning the lost e2e icon by the composer into a way to enable encryption for non-encrypted rooms?

**Comment by turt2live** [comment]
Borderline duplicate of https://github.com/vector-im/riot-web/issues/4213

**Comment by kittykat** [comment]
Closing as UI has been updated
