### ISSUE TITLE
There should be narrow scope when submitting debug logs and be able to preview debug logs. 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#8687]
In riot-web 1.0 when you submit the debug-logs it gives the following information - 

> Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages.

There are privacy issues and possible privacy violations along with this. I have not taken permission from other users to include their usernames in the debug log I am uploading. 

Also there should be able to preview debug logs so people can understand and relate to know what information is being sent. It would improve trust and transparency to the project than now. 

```
Package: riot-web
Version: 1.0.0
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-4
ii  libnss3           2:3.42-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.
```

**Comment by aaronraimist** [comment]
Being able to preview the logs is https://github.com/vector-im/riot-web/issues/3879

**Comment by shirishag75** [comment]
@aaronraimist thank you for pointing me at the right direction. Reading and subscribing to the bug-report.

**Comment by turt2live** [comment]
Unfortunately there's not a practical way to rewrite the logs to remove information at this granularity, however our rageshake/bug reporting process is reviewed by the DPO (Data Protection Officer) at Element and so far has been considered compliant.

Obviously, as we no longer need information we'll exclude it from logging to avoid overly exposing information anyways.

**Comment by t3chguy** [comment]
And the ability to download and inspect the logs before sending them has been in the app for quite some time
