### ISSUE TITLE
Default avatar url and colors should be skinnable

### ISSUE THREAD

**Issue by abeluck** [vector-im/element-web#8697]
Since the default avatar urls are images, not css, they cannot be changed by a skin/theme.

ref:  https://github.com/matrix-org/matrix-react-sdk/blob/master/src/Avatar.js#L53-L60

In #7569  it was mentioned removing the images and replacing them with background colors. This seems like a good idea. I think that issue got lost/ignored since #8474.

**Comment by jryans** [comment]
Yes, I agree we should change to CSS for these. It's a bit silly to use images here.

**Comment by bl1mp** [comment]
indeed

**Comment by fooness** [comment]
It also would be great to define `config.json` css variables in `light-custom/css/_custom.css` to be able to customize the avatar background AND foreground color …

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4503
