### ISSUE TITLE
Don't switch to that room when getting "Failed to load timeline position"

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-web#8700]
### Description

When there is a timeout on `/context`, riot gives a modal error:

> Failed to load timeline position
> Tried to load a specific point in this room's timeline, but was unable to find it.

then switches context to the room. It should not switch to the room, as in most cases if you're seeing this dialog you will have moved already.

### Steps to reproduce

Click the "go up to unread" at a time when `/context` is timing out.

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**:macOS
- **URL**: riot.im/develop ( 674b8c3561ff-react-b19a1a018871-js-03a54353be98)

**Comment by lampholder** [comment]
> It should not switch to the room, as in most cases if you're seeing this dialog you will have moved already.

This feels like a bug in itself. Why can events return and replace the room you're viewing if you've gone on to visit other rooms?

But yes, certainly the symptom that you can end up jumping to an unexpected room if `/context` is slow needs fixing.

**Comment by benparsons** [comment]
Haven't seen this in years, closing.
