### ISSUE TITLE
UX elements along the top of the page are drifting out of alignment

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8705]
Esp. with the marvellous breadcrumbs enabled, but in any rooms with an embedded widget, we're losing some of the lovely symmetry and alignment from the design refresh:

BEFORE:
![image](https://user-images.githubusercontent.com/1922197/52866277-3fce7200-3136-11e9-9de6-5a33886c1788.png)

AFTER:
![image](https://user-images.githubusercontent.com/1922197/52865857-6d66eb80-3135-11e9-9a3c-f8ae5b462c12.png)

**Comment by bwindels** [comment]
move breadcrumbs between filter field and room list @nadonomy ?

**Comment by lampholder** [comment]
People might expect the filter to filter the breadcrumbs then, too (though would it be so bad if they did? they could always grey out/drop the opacity of non-matching breadcrumbs maybe).

Another option would be to leave breadcrumbs aligned with the invite button, and bring the filter for the memberlist in line with the filter for the room list? Then we'd also have a consisted "filter field filters the list beneath it" paradigm?

**Comment by nadonomy** [comment]
Yeah, I'd prefer filter to be at the bottom for both the member list and room lists, it's a natural place for it too as you arrive at the bottom when you can't find what you're looking for.

That said, we also have some multi-account and community related jiggering on the horizon, so might make sense to action this kind of stuff then?

**Comment by lampholder** [comment]
I wouldn't want us to block small UX tweaks on multi-account - it's not a small job for riot web, so I wouldn't be surprised if it were still some distance out (behind all the other things we want to get in to riot web)

**Comment by turt2live** [comment]
Design has been spending a lot of time playing with the Information Architecture of the app to handle this sort of case. Closing in favour of that ongoing project work.
