### ISSUE TITLE
Incoming call UI needs love

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#8706]
Wasn't attended to in the redesign. Could do with spit polish in both the light and dark themes.

**Comment by turt2live** [comment]
fwiw, looks like this atm:
![image](https://user-images.githubusercontent.com/1190097/53525419-f61f4900-3a9e-11e9-9878-c9c3a16c0046.png)

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_174925](https://user-images.githubusercontent.com/25768714/109426312-4febde00-79ed-11eb-8511-2204dfb9b860.png)

The UI has been redesigned
