### ISSUE TITLE
UX Suggestion: have the right-bar default to file list in a 1-1 direct chat room -- instead of the member list?

### ISSUE THREAD

**Issue by alexmat2on** [vector-im/element-web#8719]
Typically when somebody opens a personal/direct chat with another user, the only two users who will ever be in that room are those two users. Case in point, a 1-1 chat with a friend of mine that has existed for 2 years without ever inviting somebody else. I feel this use-case is probably pretty common.  

Thus, I feel like showing the member list in 1-1 rooms is a bit redundant. I already know I'm in the room, and I already know the other person is in the room because I invited them/they invited me! 

Why not display something that will be more useful for this use-case by default? I propose that rooms that are tagged with "Direct Chat" should default to opening the file list. It's slightly more useful than the member list (hey, I wanna find that picture I shared a few days ago without back-scrolling 1000 lines of messages). I think it would also help with new users who may not realize that are different options for the right-bar, and may not realize that they can browse through uploaded files at all.

**Comment by unroasted** [comment]
I would like to work on this if that is ok with this project.

**Comment by ara4n** [comment]
sure!

**Comment by lampholder** [comment]
My thoughts copied over from the PR:

I'm afraid I am a little worried about this change.

Right now, a room's being a DM is only a flag - it can have two users, or more. The only way a user knows exactly who they're talking to is through the memberlist.

The most important psycological benefit of a dm is that it gives the user a sense of trust and privacy - that they're talking in a small, controlled group and that they're not going to be taken by surprise and accidentally share something with people they didn't mean to.

I worry that this change being made in isolation would reduce that sense of confidence, privacy and trust.

**Comment by MadLittleMods** [comment]
Did Element/Riot used to always show the member list? This doesn't feel like a problem anymore and doesn't seem likely to be implemented based on what @lampholder mentioned.

By default, the member list is not shown and you have to open it via the **Room Info** -> **People** or via the **Room Options** dropdown in the room header.
