### ISSUE TITLE
Linkify should limit its URI schemes to those supported by our HTML msgs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8720]
it's daft to stop someone hyperlinking a file:/// URI in an HTML msg if the first thing we do on displaying the message is to turn the URI back into a hyperlink via linkify. Thanks to `@pwn3d:matrix.org` for pointing it out

**Comment by MurzNN** [comment]
I vote to make this configurable! We often send via Riot direct links to internal files like `file:///mnt/share/project/file.txt` or sftp path to file, and want to open them via single click, instead of manually copy-paste them to file open dialog.

**Comment by t3chguy** [comment]
@MurzNN that's https://github.com/vector-im/riot-web/issues/4457 (YOUR OWN ISSUE) and is one which is upstream https://github.com/SoapBox/linkifyjs/issues/171

**Comment by bardiharborow** [comment]
An example where this is particularly nasty is [the "hxxp" URL scheme](https://tools.ietf.org/html/draft-salgado-hxxp-01), used to quarantine malicious URLs. Riot relinks them, making them dangerous again.

**Comment by besendorf** [comment]
Im not sure if this is the right issue to mention this but other links than those starting with http or https are not clickable properly for example atom link dont work.
atom://teletype/portal/xxxxxxx

**Comment by t3chguy** [comment]
@besendorf the permitted url schemes are https://github.com/matrix-org/matrix-react-sdk/blob/369446a94f77ae81a881fd0aefacb3a35b434e0b/src/HtmlUtils.js#L58

**Comment by besendorf** [comment]
@t3chguy thanks for the link. That seems quite arbitrary though. Why not allow all url schemes? For example why allow ftp but not sftp?

**Comment by t3chguy** [comment]
Because https://github.com/Soapbox/linkifyjs/issues/194

![image](https://user-images.githubusercontent.com/2403652/83977918-c0048200-a8fb-11ea-82f8-bd3d7aeb685e.png)
![image](https://user-images.githubusercontent.com/2403652/83977919-c135af00-a8fb-11ea-9ee9-5bc2d6d5ba10.png)
