### ISSUE TITLE
visibility labels on roomdirectory need to be designed and inverted on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8721]

**Comment by aaronraimist** [comment]
https://github.com/vector-im/riot-web/issues/8554

**Comment by lampholder** [comment]
At the moment they're the same as they are on light theme (though I don't think they look that bad; perhaps they are too bright compared to everything else).

**Comment by lampholder** [comment]
This is how it looks right now:
![image](https://user-images.githubusercontent.com/1922197/54363948-e2114500-4663-11e9-801e-e55926a55273.png)

**Comment by t3chguy** [comment]
Will be fixed by the new search dialog

cc @gsouquet

**Comment by SimonBrandner** [comment]
Do we even have those now? I don't I can see them?

**Comment by t3chguy** [comment]
Oh yeah they are gone, good spot
