### ISSUE TITLE
Enable custom tags by default

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#8723]
I've seen several people who think custom tags are just gone in the redesign. Why not enable this by default? If someone doesn't have any custom tags then they won't be affected.

**Comment by aaronraimist** [comment]
> I think there may have been performance issues with it, so behind labs for now.

https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1550291581141853uttqM:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org

**Comment by lampholder** [comment]
Yeah, it was perf. issues and some usability issues (clicking a tag currently has a very different impact on the room list to clicking on a community) - we wanted people to be able to use tags if they wanted, but to know that the UX is very much in development.

**Comment by alphapapa** [comment]
> > I think there may have been performance issues with it, so behind labs for now.
> 
> https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1550291581141853uttqM:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org

Which says:

> Still there you just need to enable them in labs "Group & filter rooms by custom tags (refresh to apply changes)"

Yet in labs, I see only these choices:

* Show recent room avatars above the room list (refresh to apply changes)
* Enable widget screenshots on supported widgets

Where is the labs setting to re-enable room user-tags?  I used this feature extensively.

**Comment by jryans** [comment]
> Where is the labs setting to re-enable room user-tags? I used this feature extensively.

I believe it's currently exposed on https://riot.im/develop only.

**Comment by turt2live** [comment]
With the new room list it might be more feasible to do this without the performance penalties imposed by the current implementation, once the new room list supports custom tags.

**Comment by openarun** [comment]
It would be easier and great to have a custom category or grouping of the rooms with custom names ("Work", "Office", "Fun", Friends", and what not) .
Something like Folders in Telegram or Category in Discord or something or may be Tags?

**Comment by t3chguy** [comment]
Custom tags are going to be incompatible (at least initially) with Matrix Spaces which is being worked on currently, it aims to solve most usecases.

**Comment by alphapapa** [comment]
Custom tags are a very simple solution to the common need to group rooms in a way that's meaningful to the user.  In `matrix-client.el`, it's as simple as typing, e.g. `/tag Friends`, and the room then appears in the "Friends" group of rooms.

I don't know what Matrix Spaces will entail, but it would be good if support for custom tags were restored in Element's Web UI.  Rooms are already grouped by, e.g. "Favorites," "People," "Low priority," so it would seem to be simply a matter of "plugging in" custom tags to that framework.

**Comment by aaronraimist** [comment]
To be clear, tags are already supported in Element and have been for a while (although with a more Communities like UI rather than the UI for favorites, people, low priority). You just have to enable them. Turn on `showLabsSettings` and then go to the Labs settings and turn on Custom Tags https://github.com/vector-im/element-web/blob/develop/docs/config.md

**Comment by alphapapa** [comment]
1.  @aaronraimist Thanks, but that doc seems to indicate that I would have to set up my own instance of Element so I could customize that config JSON file.  Is that correct, or is there a way to enable labs settings for app.element.io?
2.  Could this feature be moved out of labs, please?  I'm not even in that many rooms, but it's already very difficult to find specific rooms in the list in Element.  When the bar only shows room avatars, it's just a long, jumbled list of pictures; and when I expand it to show names, they're still not in a useful order, and each room's entry is so large that I have to do a lot of scrolling to find the one I need.  If I could use custom tags, I could easily navigate them, like I do in matrix-client.el.

**Comment by aaronraimist** [comment]
1. Not on app.element.io but you can turn it on in the Desktop app or in another instance of Element that already has labs settings enabled such as https://riot.raim.ist
2. That's what this issue is for. It doesn't seem likely that it would happen now with Spaces being so close to being released.

**Comment by aaronraimist** [comment]
Closing in favor of spaces

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-web/issues/8723#issuecomment-840392821

@aaronraimist, spaces are hierarchical. Tags are inherently not so. Why would the former replace the latter?
