### ISSUE TITLE
Encryption warning icon collides with 12hr timestamp

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8726]
![image](https://user-images.githubusercontent.com/1190097/52895377-c9059900-3176-11e9-9e23-86086afb8965.png)

**Comment by lampholder** [comment]
Ugh.

**Comment by aaronraimist** [comment]
This seems to be fixed

**Comment by turt2live** [comment]
Not quite:
![image](https://user-images.githubusercontent.com/1190097/71912275-6d4b5200-3132-11ea-919c-fbd04e29f555.png)

**Comment by kittykat** [comment]
Closing as this has been fixed.
