### ISSUE TITLE
Distinguishing rooms with new events is hard in the dark theme

### ISSUE THREAD

**Issue by dkasak** [vector-im/element-web#8729]
The difference between rooms with new events and rooms without is not very clear in the dark theme (whitish vs grey text), especially if the room name is short. Previously the room names were also bolded, if I remember correctly, which was much easier to see.

**Comment by iav** [comment]
Better to add separate clear mark like circle, dot, line etc. Color, intensity and other font properties just not enough for some environments.

**Comment by yannicka** [comment]
Here is the current rendering:
![image](https://user-images.githubusercontent.com/22885898/100544742-0f4ac000-3258-11eb-8d48-d4a651659ea2.png)

Does this solve the issue?

**Comment by dkasak** [comment]
I stopped having this problem, so I guess the answer is yes, at least from my side.
