### ISSUE TITLE
changelog isn't useful

### ISSUE THREAD

**Issue by Valodim** [vector-im/element-web#8731]
In almost all cases, the changelog in riot-web doesn't really say what relevant changes happened compared to the previous release. That's because technically those changes happen in matrix-react-sdk, but for someone who deploys riot-web to their users this is not clear at all.

Case in point: Version 1.0.1 contains *no* changes, and one has to dig in matrix-react-sdk's changelog to figure out "Fix community invites crashing the app" is the relevant issue that was fixed in this release. And this of course requires knowledge of the implementation detail that most of the changes are going on over there.

This might be fixable simply by copying the changelog from matrix-react-sdk, or even linking to it in the relevant revision?

It's also worth mentioning that the opposite is true for synapse, which has one of the most accessible and helpful changelogs I know :)

**Comment by ara4n** [comment]
yeah, we should just roll up the changelogs from matrix-react-sdk into riot-web (and matrix-js-sdk in turn into matrix-react-sdk).  A bit daft we didn't do so before tbh.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/6613

**Comment by shirishag75** [comment]
I had asked for this as well, see https://github.com/vector-im/riot-web/issues/4879 as well.  Ideally changelog.gz should be much more useful.

**Comment by BloodyIron** [comment]
This is a task that really should be automated, so devs don't have to worry how it gets there ;P

**Comment by Valodim** [comment]
This is stil a thing. Maybe just link the "Updated to React SDK" text to react sdk's changelog? Or include the link on top or bottom?

**Comment by Valodim** [comment]
Still a thing. In fact, it's gotten worse: The changelog doesn't even say that matrix-react-sdk was updated anymore, much less which version. It's literally impossible to tell what actual changes happened.

**Comment by jryans** [comment]
We're aware the changelogs aren't great right now. I'm hoping to improve them post-FOSDEM.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/9899

**Comment by shirishag75** [comment]
Having a changelog.gz would make it so easier. There are just so many ways . See for e.g. - 

https://stackoverflow.com/questions/3523534/good-ways-to-manage-a-changelog-using-git#22492425

Or/and 

https://keepachangelog.com/en/1.0.0/

I hope both give you an idea as to where or how it should be hopefully :)

**Comment by aaronraimist** [comment]
Significantly improved in the latest version https://github.com/vector-im/element-web/releases/tag/v1.7.34

**Comment by SimonBrandner** [comment]
Yeah, I'd say it improved enough to close this. Would you agree, @Valodim?

**Comment by Valodim** [comment]
Yep, I think so. It's not particularly easy to tell where which changes come from, but as a user that doesn't bother me :)

Thanks y'all! Lord knows long-standing tickets like this aren't closed often, so I'm glad this one was. Keep up the good fight! :+1:

**Comment by BloodyIron** [comment]
OH DIP this is so much better now! Yum! Thanks to all involved! :D
