### ISSUE TITLE
Profile memory usage of the new app.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8732]
There are anecdotal reports that our reported RAM has increased, e.g. https://www.reddit.com/r/opensource/comments/aqpa4j/riot_flagship_client_for_the_decentralized/eghserp

My guess is that this is due to the LeftPanel no longer lazyloading rooms, or possibly CSS pulling in more resources somehow - need to check and compare between the old app and 1.0.

**Comment by fr1kin** [comment]
Having the same issue. I am using the Windows desktop app and noticed it was freezing when I changed the room I was chatting in. Checked memory usage and saw [this](https://i.imgur.com/YOarfeT.png). I ran the old client 24/7 for weeks, and while it used a lot of memory it was never this much.

**Comment by lampholder** [comment]
@bwindels @turt2live - is it likely that any of the changes you've made in this area in the last 10 days have improved (or made worse) this?

**Comment by turt2live** [comment]
My changes probably would have made it worse, but nothing measurable. I guess I'll run a profiler over my account and see what it drags up.

**Comment by turt2live** [comment]
A quick peek into the allocation profile during startup shows that roughly 300mb of memory is spent on read receipts in the js-sdk.

**Comment by turt2live** [comment]
More random stats from a relatively-cold Riot tab (still under my account):
![image](https://user-images.githubusercontent.com/1190097/53452665-2dc6bc00-39df-11e9-9220-38d6fe7c5f1c.png)
![image](https://user-images.githubusercontent.com/1190097/53452738-6797c280-39df-11e9-9611-bf23906114d3.png)
(not pictured: a bunch more entries)

Tracking which rooms are encrypted is also quite heavy at ~52mb for ~30 rooms in my case. 

After that it kinda falls off a cliff in terms of expensive objects: highlight.js reserves about 4mb and the next object after that is under 1mb

Looking at the object distribution, some Room objects have sizes in the 13mb range. Most of the usage appears to be tracking current state (which somehow balloons 4mb of members to 13mb _currentState?) 
118mb of my memory is taken up tracking rooms.

also whatever this is doesn't look fun:
![image](https://user-images.githubusercontent.com/1190097/53453015-408dc080-39e0-11e9-9d20-d54d6f1a92e2.png)
It seemingly goes on forever, and references `create-token-class.js`, which looks like magic webpack things.

After that, it's mostly read receipts as previously mentioned. Everything else falls away as statistically insignificant.

**Comment by bwindels** [comment]
> My guess is that this is due to the LeftPanel no longer lazyloading rooms, or possibly CSS pulling in more resources somehow - need to check and compare between the old app and 1.0.

With the lazy rendering put in place, the left panel should not significantly render more rooms than in the old design ... 

You did mention seeing that CSS masks (used for the icons) use more memory. Any idea how to profile "CSS memory usage"? Looking at GPU memory in the chrome task manager, Riot stays around 70mb for me fwiw.

**Comment by turt2live** [comment]
Unfortunately I don't think we can really debug this. A whole lot of memory/CPU optimizations were done for the 2020 room list, which might have helped. If this is still a problem then a new issue with fresh profiles would be appreciated.
