### ISSUE TITLE
Request: Ability to import messages from other platforms

### ISSUE THREAD

**Issue by michaelsmoody** [vector-im/element-web#8738]
macOS with Riot.im

### Description

Ideally, for those that would like to move from platforms like Slack, it would be great to leverage data portability to import histories from other platforms. This would lower the barrier to entry for other corporate teams as well. I've looked, but cannot find any way to do this, even manually.

If I had the ability to import history from years of Slack use, this would enable a nice clean migration for community and FLOSS teams that we have on Slack, and have also had in other places, like Hipchat, Google Hangouts, and Office 365 Teams.

(I wasn't able to find a duplicate bug/feature here, so opening this for comment)

**Comment by aaronraimist** [comment]
Note that https://modular.im does offer/will offer some migration tools. My understanding is those probably won't be open to all Riot users. https://www.modular.im/tools/account-migration

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec-proposals/pull/2716
