### ISSUE TITLE
zalgo breaks if you don't have nunito as a system font?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8750]

**Comment by Half-Shot** [comment]
Straaaange. I installed the font and pasted it into an editor with that font and it shows up correctly. However, it still doesn't on Riot.

![image](https://user-images.githubusercontent.com/2072976/52918520-0477a300-32f0-11e9-9b18-ee4a669ae143.png)

**Comment by jryans** [comment]
[anoa's test case](https://matrix.to/#/!WCHwNGGsrVwPeRtAnq:matrix.org/$15504139281522RdkVx:amorgan.xyz?via=matrix.org&via=sw1v.org&via=lant.uk)

It works here with the font installed locally on Firefox for macOS, at least:

<img width="305" alt="2019-02-18 at 10 07" src="https://user-images.githubusercontent.com/279572/52943447-147d9a00-3365-11e9-8f00-5d4af3a5cabb.png">

**Comment by jryans** [comment]
I assume when it's used as a web font, we're missing characters in the font needed for it to work, or something like that? We only download the extended Latin and Vietnamese character sets for the web font currently.

**Comment by turt2live** [comment]
Presuming fixed by the new font family.
