### ISSUE TITLE
Roomlist context menu should say 'Move to People' and 'Move to Rooms' rather than be a Direct Message toggle

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8768]
Originally filed by @ara4n as part of https://github.com/vector-im/riot-web/issues/8454.

![image](https://user-images.githubusercontent.com/1922197/52969272-a908ec00-33a7-11e9-9c24-cdaeb52522a6.png)

We could probably get away with that even leaving the little person icon unchanged.

**Comment by yannicka** [comment]
Does this context menu still exist?

**Comment by SimonBrandner** [comment]
This is no longer relevant, so I am going to close this
