### ISSUE TITLE
Two finger touchpad scrolling roomlist on riot-desktop on windows doesn't work.

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/element-web#8778]
### Description

Scrolling through the rooms in the tag doesn't work with two-finger scroll touchpad on windows 7 on my thinkpad. Scroll-wheel on the mouse works fine.

### Version information
- **Platform**: riot-desktop

For the desktop app:

- **OS**: Windows 7
- **Version**: 1.0.1

**Comment by MparkG** [comment]
Is there any hope left for this to actually be finally for once fixed?

The scrolling works in every other web-page and web-chat that i use, just riot seems to be made such that it does not recognize scrolling, except in the settings window.

**Comment by mvgorcum** [comment]
I diagnosed, though not fixed, this as a probable driver issue for my thinkpad on windows 7, what touchpad drivers are you using?

**Comment by t3chguy** [comment]
This got fixed
