### ISSUE TITLE
Join room as guest should prompt you to register _or_ login.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8808]
whereas you might already have an account. it should prompt for login or register instead

**Comment by r4dh4l** [comment]
...and it should just choose you a temporary user name because "join as guest" (even if this is not a real guest account) was a very useful feature providing external users access to a room without bothering them to create an account. Would you please provide this "guest access" option again?

**Comment by t3chguy** [comment]
This got fixed

<img width="1302" alt="image" src="https://github.com/vector-im/element-web/assets/2403652/678f2815-234b-4be4-9370-ec993af2b7fc">
