### ISSUE TITLE
VoIP hangup button is not very eyecatching in the new design

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8809]

**Comment by jryans** [comment]
Is the about the button that should appear in the composer during a call? Or somewhere else?

**Comment by ara4n** [comment]
actually, we do - it's just very hard to spot; it's no longer red but grey, and the wrong weight (too thin) and looks greyed out.

**Comment by ara4n** [comment]
(and yes, it's this one:

<img width="167" alt="screenshot 2019-02-25 at 16 04 22" src="https://user-images.githubusercontent.com/1294269/53350490-0e645c00-3917-11e9-8242-a4949c6e250a.png">
)

**Comment by SimonBrandner** [comment]
Closing this since the hangup button has been removed by [#5693](https://github.com/matrix-org/matrix-react-sdk/pull/5693)
