### ISSUE TITLE
Key Backup reminder asks again too soon after clicking "Not now"

### ISSUE THREAD

**Issue by Skirmisher** [vector-im/element-web#8816]
The Key Backup notification that appears at the top of E2E rooms is quite persistent; after clicking "Not now" to dismiss it temporarily, merely switching to another E2E room causes it to reappear. When I click it, I expect to be reminded half a day later at the earliest—the point of "Not now" is to stop it from nagging me when I'm not in a position to set it up, so that it can remind me at a more appropriate time.

Observed on Riot desktop version 1.0.1 on Debian 9.

**Comment by lampholder** [comment]
Yeah, we understand this is not an optimal reminder schedule, but it was better than anything else we could implement in the same time window (it's better than dismiss-once-gone-forever). 

We certainly plan to make something that reminds you in a more natural and less annoying way :P

**Comment by kittykat** [comment]
I am going to close this issue for now as the reminders feel more infrequent now. Please reply with @kittykat if you are still experiencing it and I will reopen the issue.
