### ISSUE TITLE
Strange reports of Scalar not working in incognito browsers

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8831]
Not sure how much we need to investigate this, but if it comes up again then there's at least an issue to track it. Conversation starts at https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1550683243135lBoFX:targodan.de?via=matrix.org&via=linuxgaming.life&via=disroot.org

**Comment by targodan** [comment]
Summary:

- My HS + Riot Desktop: works
- My HS + Self hosted Riot in Google Chrome (normal mode): works
- My HS + Self hosted Riot in Google Chrome (incognito mode): doesn't work

Working refers to being able to open the integrations panel. Doesn't work means I can't open it. In the console I was able to find this:

```
Failed to load resource: the server responded with a status of 500 ()
rageshake.js:99 Error whilst initialising scalarClient for ManageIntegsButton Object
e.(anonymous function) @ rageshake.js:99
```

The related call was to `https://scalar.vector.im/api/register` with the content `{"expires_in":3600,"access_token":"REDACTED","matrix_server_name":"targodan.de","token_type":"Bearer"}`.

This responded with a 500 and `{"message":"Failed to authenticate user"}`

**Comment by NgoHuy** [comment]
Hi guys,
I found the solution that your setting from firefox: `tracker blocking`.
There 2 problem here:
1. Server name should be parent domain `example.com` not `chat.example.com`
2. Shoud not block tracker from Scala to appear sticker packs.

**Comment by turt2live** [comment]
I don't believe this is actionable in 2021/22 in its current state. If people are still seeing this, please open a new issue with more details.
