### ISSUE TITLE
URL preview of Riot itself has invisible text on the dark theme

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8834]
![image](https://user-images.githubusercontent.com/1190097/53118039-737c1400-3509-11e9-8dbb-bbd367ec0cb5.png)

It says "RIOT.IM" down the right side of the R, but you wouldn't know that unless you hover and look carefully.

**Comment by SimonBrandner** [comment]
Since the branding has changed this shouldn't be a problem anymore
