### ISSUE TITLE
Add option to remove confusing warning when using disable_custom_urls: true on login error

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8848]
![image](https://user-images.githubusercontent.com/1190097/53148957-7eff2780-3569-11e9-9a41-61cb5efee07f.png)

For this server, I intentionally want to disable the custom URLs so people don't try and log in to matrix.org (and generally hide the complexity of Matrix from the less-technical users). It would be nice to disable this warning to avoid confusing people.

**Comment by jryans** [comment]
Huh, looks like the message was added a while ago for status.im. I agree that's confusing, since we're trying to simplify by locking down the HS, but now we're confusing people again with complexity.

**Comment by turt2live** [comment]
re-triaged to be lower because it really doesn't impact anyone.

**Comment by turt2live** [comment]
actually, let's close this. EMS and friends appear to rely on this sufficiently where it makes enough sense. If someone really wants to fix it, feel free, but I don't think it's enough of a problem to have an open issue for it explicitly (at the moment).
