### ISSUE TITLE
Maximize Jitsi widget to whole chat area

### ISSUE THREAD

**Issue by akontsevich** [vector-im/element-web#8851]
### Description
Good to have ability to maximize Jitsi widget to whole chat area or even whole Riot window for convenience like Skype or other messaging applications have. Not convenient to switch to separate browser tab or window - good to have all the stuff inside Riot. Also some things does not work for example in my default FF browser (screensharing).

### Steps to reproduce
Good to add some maximize buttons for this, and for P2P calls as well.

**Comment by HansJK** [comment]
This is a must! You can now get fullscreen by clicking on the video, and the press "S", but this is a very bad design. All the alert boxes and menus looks horrible on that tiny window.

**Comment by Mathias-g** [comment]
It would also be nice that while it is small you make the height of the settings modal bigger, because right now the content area is so tiny you can only see the tabs.

**Comment by toger5** [comment]
Should we close this in favor of #15741. (Allow widgets to use maximum vertical space)

**Comment by SimonBrandner** [comment]
Yeah, I think so
