### ISSUE TITLE
Lots of people get confused as to how to readd a community to the sidebar after hiding it

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#8869]
Lots of people get confused as to how to readd a community to the sidebar after hiding it

EDIT: To solve this we might want to add a right click menu item for adding a community to LLP

**Comment by lampholder** [comment]
Sorry to brutally edit this issue, but the key issue we shouldn't lose track of is that people get confused trying to (re)add communities to the sidebar. Right click might be how we fix it (or we might get rid of right-click altogether)

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
