### ISSUE TITLE
Invite new room members by mxid doesn't show image and name

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#8877]
### Description

When inviting new users to a room you get two different views on the same person based on whether you search for their display name and find it in the directory, or if you paste their mxid directly (see images)

### Steps to reproduce

In a room, invite new room members.

Try to search someone by name, then having found a mxid, try typing that mxid into the box instead.

Given i can see their image and name by looking for their displayname, it feels odd that knowing /exactly/ which user i want to invite is not visible.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by michaelkaye** [comment]
![notworking-invite](https://user-images.githubusercontent.com/1917473/53240688-4bbab680-3697-11e9-9efa-7e33f45196ef.png)
![working-invite](https://user-images.githubusercontent.com/1917473/53240690-4bbab680-3697-11e9-9320-eba76355d77f.png)

**Comment by aaronraimist** [comment]
This seems to have been fixed
