### ISSUE TITLE
E2E: Key backup recovery key creation UI confusing

### ISSUE THREAD

**Issue by matthijskooijman** [vector-im/element-web#8878]
### Description
I just tried setting up key backup. Part of that is optionally downloading a recovery key. Currently, this happens through a two-step interface. First, you get:

![image](https://user-images.githubusercontent.com/194491/53244199-6cd8d280-36aa-11e9-91e7-59e5b39c8204.png)

Then, when you click "Download", a file is offered for download and then you get:

![image](https://user-images.githubusercontent.com/194491/53244229-867a1a00-36aa-11e9-98a3-031b583d08bf.png)

When you click "Copy to clipboard", you get a similar screen.

Now, this is a bit confusing:
 - What if write down my recovery key from the first screen and do not want to copy or download it? How should I proceed?
 - On the second screen, what does "back" really do? It moves back to the first screen, but as a user that was not entirely clear to me and both options were a bit confusing.

I wonder if these two screens might just need to become a single screen? The info on the second screen could be included in the first screen as well (partly it already is). Even more, "Your Recovery Key is in your Downloads folder" is not even generally true and heavily depends on OS, browser and configuration.

### Version information
https://riot.im/app
matrix-react-sdk version: <local>
riot-web version: 1.0.1
olm version: 3.0.0

**Comment by kittykat** [comment]
I'm going to close this for now as the UI has changed significantly since this issue was filed. Please create a new issue for the current UI with details on how that could be improved if you feel that there are further improvements to be made.
