### ISSUE TITLE
e2e encryption needs to be made quantum-resistant

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8889]
Wire has done this: https://wire.com/en/blog/post-quantum-resistance-wire/

Disclaimer: I have no idea what this entails.

**Comment by ShadowJonathan** [comment]
Likely a spec issue, https://github.com/matrix-org/matrix-doc/issues/3520 and https://github.com/matrix-org/matrix-doc/issues/3516 are related.

**Comment by turt2live** [comment]
moved to https://github.com/matrix-org/matrix-doc/issues/3678
