### ISSUE TITLE
Flow to update password should be improved (in settings)

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-web#889]
When resetting password the user might have forgotten which email he linked to his account. 
We need to at least send an email saying that the email is wrong rather than having the flow unfold successfully only to find out the email was wrong at the very end.

I got also feedback that it was strange to enter the pwd and confirm on the first screen and may the email should be validated first by sending a message with a link allowing to set the new pwd, but I'm unconvinced... To be reconsidered.

**Comment by ara4n** [comment]
see also https://github.com/vector-im/riot-web/issues/2761

**Comment by ara4n** [comment]
dup https://github.com/vector-im/riot-web/issues/2780

**Comment by ara4n** [comment]
actually, it's not a dup - #2780 is password reset; this is password **change**.

**Comment by t3chguy** [comment]
> We need to at least send an email saying that the email is wrong rather than having the flow unfold successfully only to find out the email was wrong at the very end.

would be very strange behaviour, I've not seen any platforms which do this

**Comment by novocaine** [comment]
The concern over entering pwd before the email is now covered by https://github.com/vector-im/element-web/issues/18743

**Comment by novocaine** [comment]
Closing the ticket as I agree with https://github.com/vector-im/element-web/issues/889#issuecomment-568508273 that we won't implement that behaviour.
