### ISSUE TITLE
modular MAU limit text is illegible

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8896]
blue link on blue bg.

<img width="1165" alt="screenshot 2019-02-23 at 01 35 33" src="https://user-images.githubusercontent.com/1294269/53279798-69296800-370b-11e9-821c-6a738d19630b.png">

**Comment by lampholder** [comment]
Can we just replace it with white (underlined) text?

**Comment by Half-Shot** [comment]
These have been totally legible toasts since forever. I'm going to close this.
