### ISSUE TITLE
Backup has an invalid signature from verified device

### ISSUE THREAD

**Issue by schiessle** [vector-im/element-web#8905]
I did a online backup of my encryption keys a few days ago with Riot-web 1.0.1
Today I got a update of Riot 0.8.23 (B-b164) on Android which asked me as well If I want to backup the encryption keys. I followed the dialog, entered the password I used for the backup with Riot-web a few days ago and everything looked fine. 

But if I go the the security settings in Riot-web I see now:

````
Backup has a valid signature from this device
Backup has an invalid signature from verified device Mobilgerät
````

and a similar message in the Android app.

After I couldn't find a way in the settings to cross-verify my devices. I created a new end-to-end encrypted room and tried to type a message. Now a dialog popped up asking for verification. The new verification didn't worked (maybe it is not yet implemented on Android?) so I opted for the legacy verification and performed it on both devices. On Android now everything is green, but on the Desktop I still see the warning from above.

What's the right thing to do now? How do I fix it?

**Comment by subversion23** [comment]
I had the same issue, deleted the backup and made a new one. 
Now my web client says:  
```
This device is backing up your keys. ✅
Advanced
Backup version: 3
Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
All keys backed up
Backup has a valid signature from verified device Mobile
This backup is trusted because it has been restored on this device
```

On my mobile the web client doesn't show up. It just says "All Keys are backed up", but on the web client all devices are unverified.   
I don't know how to fix this, except manually verify approx. 50 devices AGAIN, which is really annoying.
#9245 would help very much.

**Comment by poljar** [comment]
Element Web and Android seem to construct valid signatures for the backup key/version nowadays. 

While there are other problems with the backups this one doesn't seem to be relevant anymore, please reopen if I'm wrong.
