### ISSUE TITLE
Support FLIF image format

### ISSUE THREAD

**Issue by yangm97** [vector-im/element-web#8910]
FLIF stands for Free Lossless Image Format, it has a good compression ratio and is natively responsive, meaning that there's no need to encode multiple versions of the same file to get thumbnails/lower resoltion versions, the client decides how much resolution it wants and then stops downloading once it has enough bits, thus saving the client's bandwidth and the home server disk space.

It can also be used for animations (gifs), the same principles apply.

http://flif.info/index.html

**Comment by t3chguy** [comment]
https://caniuse.com/?search=flif shows that FLIF has been superseded by JPEG XL which will be supported by browsers in the future, current support is behind a jxl flag
