### ISSUE TITLE
Up Arrow to navigate through sent message history in composer can surprise people not familiar with this

### ISSUE THREAD

**Issue by nunoperalta** [vector-im/element-web#8916]
### Description & Steps to reproduce

In Riot Web, you can use the Up Arrow to put the previous message in the textbox.
(although I honestly don't understand the purpose of that, if it's not to Edit that previous message)

However, I was typing a big message in the textbox, that I haven't sent yet.
I was pressing the Up Arrow to go up and review it, and at some point, it REPLACED my whole message with the previous message.

### Version information

- **Platform**: Web
- **Browser**: Chrome 72
- **OS**: Windows 10
- **URL**: Private Server - Riot v1.0.1

**Comment by t3chguy** [comment]
You can also press down arrow until it returns though, unless you've changed rooms since.

**Comment by nunoperalta** [comment]
I see that does happen, yes (thank you for the tip).

However, when I raised this ticket, I actually lost a message because I pressed Enter right after it changed to the previous message.

As a user of different Messenger systems, I wasn't expecting this behavior to happen, as no other system does this. I don't even see a benefit of having this feature. Seems dangerous to me.

**Comment by lampholder** [comment]
This is a pretty well established feature in IRC clients (and the terminal generally) so I don't think it's something we're going to get rid of - I'll tweak this issue to reflect that it's weird/risky for people who are not familiar with it.

**Comment by nunoperalta** [comment]
@lampholder Thank you for explaining.
Totally understand if IRC members like this. What about it as an option, so that we can decide whether we want it or not? :)

**Comment by t3chguy** [comment]
This is no longer the behaviour, it now navigates messages to edit in the timeline.

![image](https://user-images.githubusercontent.com/2403652/94193506-5ad39d00-fea8-11ea-89e2-35b6c676e303.png)
