### ISSUE TITLE
mxids are leaking into pills

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8921]
i mentioned rom1dep[x] in HQ, and the pill had the full mxid in it. in the composer, it was correct

<img width="991" alt="screenshot 2019-02-24 at 22 52 37" src="https://user-images.githubusercontent.com/1294269/53306590-f80ebf80-3886-11e9-8627-e3b824590edd.png">

**Comment by weeman1337** [comment]
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @weeman1337 to let me know that it’s ready to be reopened.
