### ISSUE TITLE
Re-add tests for room list sorting behaviour

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8922]
Now that there's a new room list algorithm, we need tests to make sure it sorts things correctly. This is higher priority because bugs keep cropping up with the implementation.

**Comment by turt2live** [comment]
I'm going to go ahead and bump this out of the current sprint (which ends pretty quick here) because nothing in the chain here has testability in mind. Tests are a good thing that we should have, but the SettingsStore wasn't really made with testing in mind, nor was `Unread`. There's a lot more work to do this than what appears on the surface.

**Comment by Johennes** [comment]
Closing because `RoomListStore` appears to have tests now.
