### ISSUE TITLE
minimised 1:1 video call under TopLeftMenu no longer has UI to de-minimise

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#8932]

**Comment by ara4n** [comment]
although this might be due to the whole DOM no longer responding to events (although the webrtc call is still working)

**Comment by ara4n** [comment]
(in fact, amandine's entire laptop had apparently crashed other than the webrtc video window, which seems a bit suspicious)

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
