### ISSUE TITLE
Error decrypting image is not redesign-friendly

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8937]
The "⚠" icon doesn't align with the Element redesign. This issue is meant to track the design requirements for it

> ⚠ Error decrypting image

![](https://i.imgur.com/MEzC44i.png)

**Comment by jcalfee** [comment]
I had a file permission error, synapse could not write to the data/media_store directory.  I messed that up moving files around.

**Comment by sl0th2** [comment]
I am getting these as well - however no errors in my logs. Clicking "download" simply spins a wheel that says "Decrypting" for a very long time to new fruition. Tried on a 2MB file. Uploads are restricted to 30MB.

**Comment by sl0th2** [comment]
`Uncaught (in promise) TypeError: Failed to fetch`
 `Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH `
 and
 `synapse.rest.media.v1.upload_resource - 101 - INFO - POST-1890 - Uploaded content with URI 'mxc://hungynet.xyz/PLpfHPyItWDjKWrFecquFiQo'` are my errors i've found so far.

**Comment by MadLittleMods** [comment]
For those reporting random root causes displaying the "Error decrypting image" error message, these should be tracked in https://github.com/vector-im/element-web/issues/3892 instead ⏩

**Comment by MadLittleMods** [comment]
Closing as the Element redesign happened a while ago and the icon doesn't stand out to me as wrong. Design can open another issue if they care about changing it with a new icon proposed.

The alignment of the icon and text is even better nowadays,

![](https://user-images.githubusercontent.com/558581/200037090-cb355ed7-9126-439c-bff5-fb39581f6d9d.png)
