### ISSUE TITLE
Backdrop flickers when clicking "Create New Room" from directory

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8942]
Seems like the modal unmounts fast enough to cause the backdrop to disappear momentarily.

**Comment by gsouquet** [comment]
@turt2live would it be fair to say that you're not experiencing this issue anymore?
@Palid 's work has probably mitigated this problem enough that we can close this issue

**Comment by Palid** [comment]
Pretty sure this one can be closed now

**Comment by Palid** [comment]
Backdrop panel should not unmount so easily now, so I'm closing this one.
