### ISSUE TITLE
Consider adding stronger warning when last admin leaving community

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#8951]
https://github.com/matrix-org/matrix-react-sdk/pull/2242 was not enough warning

It is not uncommon to see people requesting help after they were the last to leave a community

> i saw it, did it anyway though hoping it was more foolproof

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/2855

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
