### ISSUE TITLE
"Idiot mode" as default

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#8952]
Feedback on the latest medium.com blog post:

>My biggest gripe with Riot in general and why I’m unable to convert business users to it —they get confused, can’t find their rooms, keep creating new rooms every time they want to say hello, don’t know how keys work or why…
>
>The updates are in the right direction, but there should be an “idiot mode” included and it should be the default, because business users don’t have 10 minutes to learn a new UI other than the default “skype-like” ones.

**Comment by robintown** [comment]
The app's IA has been completely reworked since 2019, and further UX problems should be opened as more specific issues.
