### ISSUE TITLE
Declining a call results in an unbolded room with unread notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8982]
![image](https://user-images.githubusercontent.com/1190097/53525659-85c4f780-3a9f-11e9-8305-0ec3c7380964.png)

It should probably either be fully bold or dismiss the count.

**Comment by SimonBrandner** [comment]
![Screenshot_20210228_174725](https://user-images.githubusercontent.com/25768714/109426275-07342500-79ed-11eb-9dbc-a021057cefb6.png)

This doesn't seem to be a problem anymore
