### ISSUE TITLE
Cannot autocomplete people who just joined the room

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9008]
![image](https://user-images.githubusercontent.com/1190097/53612419-85a42500-3b8f-11e9-886f-5ec55bbdc9d0.png)

No matter how much I slam tab, I'll keep getting a flash of red until I switch rooms and back.

**Comment by SimonBrandner** [comment]
@turt2live, is this still an issue for you? I cannot repro

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
