### ISSUE TITLE
Clicking the "This message is not encrypted" icon brings up a dialog explaining how the message is encrypted

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9010]
It doesn't give you anything really helpful though. It should probably just not have a click action imo

![image](https://user-images.githubusercontent.com/1190097/53614912-ca808980-3b98-11e9-8f81-c180a12c1fb3.png)

**Comment by turt2live** [comment]
No idea why this was closed. It's very much a bug and very much a case of us losing the user's trust.

**Comment by lampholder** [comment]
Sorry - I mixed this up with the "End-to-end encryption information" option that was incorrectly appearing in the context menu for plaintext messages.

**Comment by lampholder** [comment]
p2 minor since it's not actually telling you anything inaccurate, it's just not as clear as it could be

**Comment by kittykat** [comment]
@turt2live Could you please add steps to reproduce?

**Comment by robintown** [comment]
This dialog no longer exists
