### ISSUE TITLE
avoid layout when thumbnails load

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#9016]
set the thumbnail dimensions from the event on the <img> before the image loads in MImageBody, so they don't resize when the image is loaded.

**Comment by bwindels** [comment]
#8565 should have already improved this for Chrome, but as this is probably the biggest cause for scroll jumping, seems like a no-brainer to do this for other browsers as well.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/9670

**Comment by t3chguy** [comment]
Duplicate of #9670
