### ISSUE TITLE
Can't install riot on Windows

### ISSUE THREAD

**Issue by adalvigi** [vector-im/element-web#9024]
### Description
The `Riot Setup 1.0.1` Windows installer doesn't prompt me to install the program but only opens it once and leaves no trace. How do I install it?

**Comment by BloodyIron** [comment]
That installs it, but it installs it in your user profile. Try looking in your start menu for riot, you'll probably find it there.

**Comment by jryans** [comment]
@adalvigi Thanks for filing! What's the current status here? Were you able to find Riot after install?

**Comment by adalvigi** [comment]
Yep but I had to create a link on my desktop manually... also I could find it by Win + typing name but no start menu entry

**Comment by vioBF** [comment]
I have the same problem. I build the app and i can start it on windows, but there is no desktop shortcut and no entry in the menu. There is an entry in the apps section in the system preferences. I can also deinstall the app but that's it.

**Comment by kittykat** [comment]
I;m going to close this issue for now as there have been newer versions of Element available since this was reported. Please file a new issue for any problems installing the latest version of Element on Windows.
