### ISSUE TITLE
Highlighting IRC nicknames does not work if nick contains ` character

### ISSUE THREAD

**Issue by tobbi** [vector-im/element-web#9028]
### Description
IRC allows \` characters in nicknames. They do work fine in both Matrix and IRC; however, when you try to highlight a user with a \` in their nick, matrix understands the \` as part of the syntax highlighting which causes an odd problem with the highlighting.

### Steps to reproduce

- Log into an IRC channel bridged to a matrix room with a nick containing a `character.
- Ping that nick from the Matrix channel.

Nick highlight gets treated as a code highlight.

### Version information

- **Platform**: web (in-browser) or desktop?
web (using Rambox)

For the web app:

- **Browser**: Rambox (based on Chrome)
- **OS**: macOS
- **URL**: https://riot.im/app/ version 1.0.1

**Comment by lampholder** [comment]
Related:
- https://github.com/vector-im/riot-web/issues/7134
- https://github.com/vector-im/riot-web/issues/4867

**Comment by Half-Shot** [comment]
*Wishes IRC hadn't decided to put silly chars in peoples nicks*

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/7134
