### ISSUE TITLE
Blank screen when sending file

### ISSUE THREAD

**Issue by scaiper** [vector-im/element-web#9030]
### Description

When I'm trying to send a file containing non-ascii characters in filename, I get stuck in blank window.
![screenshot from 2019-03-03 15-14-44](https://user-images.githubusercontent.com/9356384/53695006-2a5c7780-3dc7-11e9-9dbb-a81d8e611341.png)

### Steps to reproduce

- Press "Upload file" button in chat
- Select file containing non-ascii characters in name (e.g. "фото.jpg" or "IMG_8571±.jpg")
- "Upload files" dialog appears briefly, then app becomes blank.

Describe how what happens differs from what you expected.
"Upload files" dialog should work as expected.

### Version information

- **Platform**: desktop
- **OS**: Debian buster
- **Version**: 1.0.1
Installed via flatpak.

**Comment by scaiper** [comment]
I've sent logs in app.

**Comment by lampholder** [comment]
I can confirm that this _doesn't_ occur on the electron desktop client on macOS (uploading a very small text file called `马马虎虎.txt`).

**Comment by turt2live** [comment]
This is almost certainly a crash due to low memory. I can't find it at the moment, but there is an issue about buffering large files in memory causing crashes.

**Comment by t3chguy** [comment]
@turt2live think you wanted https://github.com/vector-im/riot-web/issues/4264

**Comment by scaiper** [comment]
No, that's not the case. I can send videos tens MB in size as long as they contain only ascii characters, but can't send 100KB image if it contains non-ascii characters.
Also, my machine has over 10GB of free memory.

**Comment by t3chguy** [comment]
Is this still affecting you?

**Comment by weeman1337** [comment]
I am closing this issue because there has been no response in the last two weeks. If you keep experiencing this defect, please add a comment with @weeman1337 to let me know that it should be reopened.
