### ISSUE TITLE
Sticker loading icon needs new design

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9053]
![image](https://user-images.githubusercontent.com/1190097/53830659-31f35c00-3f40-11e9-8046-4f2e643ddc3f.png)

**Comment by lampholder** [comment]
![image](https://user-images.githubusercontent.com/1922197/54378934-4fcb6a00-4680-11e9-8f0c-0cd981292783.png)

**Comment by kittykat** [comment]
Fixed since the issue was filed
