### ISSUE TITLE
Mentions in encrypted rooms swallowed by backfill are not reflected in the client

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9069]
As per https://github.com/matrix-org/matrix-js-sdk/pull/851#issuecomment-470018133

If the user goes offline and receives a substantial amount of messages, when they come back online they will almost certainly miss a bunch of events. The wrong mention count will be shown because Riot relies on counting it client-side using the visible timeline as a reference.

https://github.com/matrix-org/matrix-doc/pull/1796 or similar would probably fix this.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/17223
