### ISSUE TITLE
consider making key request uisi warnings a spinner rather than a warning

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9080]
eg 'loading keys... rerequest?' rather than 'cannot load keys'

**Comment by lampholder** [comment]
Worth thinking about, but I think we should take a step back and look at what message we're trying to send about UISIs.

Spinners say "this is in progress, you can expect to see this resolve without your intervention (and soon)". Spinners are also annoying if they sit spinning indefinitely. 

My ideal UISI message might:
- show that the message is currently undecryptable
- show a spinner whilst waiting for key share requests from other devices
- show me which devices it heard back from confirming that they _don't_ have a copy of the key
    - give me an option to trigger another key request (perhaps with instructions based on the above: "check devices x, y, z to see if they're turned on/have waiting key share requests")
- show me whether a copy of the key exists in the backup
- tell me whether this message was just never encrypted for me by the sender

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/20532
