### ISSUE TITLE
Riot doesn't follow 301 responses during homeserver discovery

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/element-web#9084]
### Description

When I enter in my mxid @adam:thebeckmeyers.xyz, Riot sends a request to https://thebeckmeyers.xyz/.well-known/matrix/client and gets back:

```
HTTP/2.0 301 Moved Permanently
content-length: 0
location: https://www.thebeckmeyers.xyz/.well-known/matrix/client
X-Firefox-Spdy: h2
```

It then fails to request the specified location and says "Invalid homeserver discovery response"

### Steps to reproduce

Enter `@adam:thebeckmeyers.xyz` in the username field of Riot sign-in.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 65.0.1
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
fwiw, the spec is super strict in this respect and doesn't let us follow 301 redirects: https://matrix.org/docs/spec/client_server/r0.4.0.html#server-discovery

[MSC1700](https://github.com/matrix-org/matrix-doc/pull/1700) could probably be brought back to life, and take this into consideration. Have opened https://github.com/matrix-org/matrix-doc/issues/1919 to track this.

**Comment by non-Jedi** [comment]
Ah. Not sure what the practice is on bugs on riot-web where a spec issue causes a Riot ux issue. Feel free to close this if that's the best way of handling.

**Comment by turt2live** [comment]
riot-web is the dumping ground for UX of Matrix, still :(

**Comment by hex-m** [comment]
[MSC2499](https://github.com/matrix-org/matrix-doc/pull/2499) would clarify this.

**Comment by tulir** [comment]
Element already follows redirects, but https://thebeckmeyers.xyz/.well-known/matrix/client is missing CORS headers.

**Comment by turt2live** [comment]
Overall this issue isn't one of Element (if anything it shouldn't follow the redirect), but of the spec: https://github.com/matrix-org/matrix-doc/issues/1919

Closing in favour of the spec issue. In general I think we should continue to follow the redirect and work on making the spec sensible.
