### ISSUE TITLE
Broken initial letter offsets on Chrome in MELS

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9088]
<img width="1013" alt="screenshot 2019-03-08 at 15 07 02" src="https://user-images.githubusercontent.com/1294269/54033189-e812ac00-41b3-11e9-8bbc-bb49dfb3401e.png">

**Comment by jryans** [comment]
See also the Firefox version in https://github.com/vector-im/riot-web/issues/5594

**Comment by jryans** [comment]
So far, I haven't been able to duplicate this happening Chrome. If you have any more specific steps, that would be great!

**Comment by turt2live** [comment]
I have to admit that I have seen this, but all of my examples don't seem to trigger it.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/95075640-76407280-0708-11eb-936b-81bf7266f711.png)


Assuming this got fixed at some point, probably by the above PR
