### ISSUE TITLE
Add tests to ensure resolved modules are singleton instances

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#9093]
There may be cases today where `require('<X>')` gives different instances depending on where you are requiring from. This is generally not expected or intended for a well-functioning JS module system. (It is believed this may occur today across the high-level boundaries like Riot vs. SDKs, perhaps because we have not yet integrated them into a single build.)

We should ensure this works as expected for a consistent developer experience and add tests to ensure it stays that way going forward.

See also: https://github.com/matrix-org/matrix-react-sdk/pull/2770#discussion_r263862163

**Comment by Johennes** [comment]
Closing as this doesn't appear to have caused any practical issues since March 2019.
