### ISSUE TITLE
After logging in to Riot Desktop (Web), one contact's messages are undecryptable on all devices

### ISSUE THREAD

**Issue by chaoscommander** [vector-im/element-web#9099]
### Description

I have been using Riot on Android for a while with two contacts. A short while ago I also installed Riot Desktop (based on riot-web) on my Gentoo Linux machine. At first all the messages were unreadable, as would be expected. I then exported a key backup on Android, imported it into Riot Desktop and all the past messages became readable. BUT.. from that moment on, all the new messages received from one of my contacts show up as "unable to decrypt". Apart from the known issue that the subsequent key request never shows up on my Android device, their messages also are now undecryptable by the Android app, which was neither reinstalled nor reset.

I tried creating a new room with that person in hopes it would reset the encryption key exchange (or something), but that didn't work either. In the new room all of their messages to me are unreadable, too.

### Steps to reproduce

- use riot.im exclusively on Android with encryption turned on
- install riot desktop (on Linux?)
- import key backup into desktop app
- receive an encrypted message in an existing chatroom

Log: sending momentarily    

### Version information

- **Platform**: desktop
- **OS**: Gentoo Linux
- **Version**: 1.0.0

**Comment by chaoscommander** [comment]
I sent a corresponding error report using the tool in Riot for Android.

**Comment by lampholder** [comment]
Extracting keys from your Android phone and importing them into the desktop session would only allow you to decrypt _old_ message - to decrypt new messages, your devices have to be encrypting messages for one another (which sounds like isn't happening).

Have you enabled the setting to only encrypt messages to verified devices? And have you verified your desktop session from you mobile (and vice versa)?

**Comment by chaoscommander** [comment]
I have not. The other person doesn't seem to be sure. We'll try verifying each other the next time we meet.

**Comment by kittykat** [comment]
I am going to close this issue for now as the user interface and code have changed since then. Please file a new issue and submit a rageshake if you are still experiencing the problem.
