### ISSUE TITLE
Tabbing into the phone field on registration doesn't focus any useful component

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9128]
Using keyboard navigation to work your way through the registration form, you can enter a username, password, and email just fine but when you tab from email to phone it doesn't really do anything. The field turns blue but neither the textbox or country code are selected (at least, it's not super obvious which is and the arrow keys don't do anything). Tabbing again leaves you in the text box.

**Comment by kittykat** [comment]
@turt2live Can we close this issue as we don't show a phone field on registration any more?

**Comment by t3chguy** [comment]
https://user-images.githubusercontent.com/2403652/231449328-30ef95db-29d1-4656-9e0f-756d76ca8fbf.mov

This works fine nowadays
