### ISSUE TITLE
Macro emoji (:words: -> custom sentence)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9136]
https://github.com/vector-im/riot-web/issues/7505#issuecomment-472070480

---

*Half-Shot adds:*
Have :arbitrary-string: map to whatever the user wants (eg: :hello: to "Hey there! Welcome to #community, how are you?")

**Comment by cremesk** [comment]
suggestion:
```
/alias <list|add|del>

/alias list
/alias add <name> <value>
/alias del <name>
```

eg: `/alias add hello "Hey there! Welcome to #community, how are you?"`
to use `/hello`

**Comment by turt2live** [comment]
@cremesk that would be a different issue. This one is about emoji.

**Comment by cremesk** [comment]
> @t3chguy Sure, that sounds like #9136 for the third time.

**Comment by t3chguy** [comment]
@turt2live his suggestion is about how to manage the list of macros

**Comment by t3chguy** [comment]
except `to use /hello`

@cremesk if you're hell-bent on it being a slash command to execute rather than this more generic approach then you'd need to open another issue

**Comment by cremesk** [comment]
> except `to use /hello`
> 
> @cremesk if you're hell-bent on it being a slash command to execute rather than this more generic approach then you'd need to open another issue

i open a new feature request: https://github.com/vector-im/riot-web/issues/13891

**Comment by ShadowJonathan** [comment]
I wouldn't recommend using emoji shortcode symbols for this, maybe `;` instead?

**Comment by Palid** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/19747
