### ISSUE TITLE
Smileys are too small

### ISSUE THREAD

**Issue by Hoeze** [vector-im/element-web#9146]
Smileys are too small to read if they are in text blocks:
![grafik](https://user-images.githubusercontent.com/1200058/54244316-6365bc00-452c-11e9-980e-08cd39146d7b.png)

**Comment by jryans** [comment]
Thanks for reporting this issue!

Do you feel that the font size of text generally is also too small, or only the emojis in text?

**Comment by Hoeze** [comment]
The font size is OK IMHO, but I think it would be cool to have an option to configure the font somewhere in the advanced settings :)

**Comment by aaronraimist** [comment]
#3160 is for configurable font sizes

**Comment by rkfg** [comment]
Duplicate of #2890
