### ISSUE TITLE
Registration spinner doesn't appear until after the POST to /r0/register completes, which makes registration look broken on v. slow connections

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#9148]

**Comment by jryans** [comment]
Hmm, it seemed to work fine for me: 2 / 2 attempts worked. Maybe an ephemeral issue...?

**Comment by kittykat** [comment]
Thank you for opening an issue. Unfortunately I wasn’t able to reproduce it. If you keep experiencing this defect, please update your description with steps/screenshots/video/more details and add a comment with @kittykat to let me know that it’s ready to be reopened.
