### ISSUE TITLE
Chinese characters overlap each other and make them hard to read

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9160]
### Description

In addition to the other big Chinese character bugs we have: https://github.com/vector-im/riot-web/issues/5913 https://github.com/vector-im/riot-web/issues/6923

Chinese characters seem to overlap each other in both the composer field and the message list.

![image](https://user-images.githubusercontent.com/1342360/54311334-484a8900-45cc-11e9-8de4-c2f78cc9a28b.png)
![image](https://user-images.githubusercontent.com/1342360/54311350-513b5a80-45cc-11e9-9530-6d09db8e0daa.png)

### Steps to reproduce

- Copy 可能是字体问题 into Riot
- Notice it doesn't look the same as Github, but some characters are overlapped.

Log: not sent    

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: independent build of riot.im/develop

**Comment by turt2live** [comment]
Assuming this is fixed by the new font, or the option to use a custom font

**Comment by KennanChan** [comment]
Any more information about this issue? I encountered the same bug in browser environment? Is it a font rendering error?
