### ISSUE TITLE
Unable to decrypt anything else than what I send by myself

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-web#9169]
### Description

![Kuvakaappaus 2019-03-14 11-34-02](https://user-images.githubusercontent.com/831184/54346084-5801b600-463c-11e9-95cb-b781a19e1c44.png)

I can only read messages I send from this device regardless of trusting all devices.

### Steps to reproduce

- I have no idea.

I expect to be able to read all messages from everyone, especially as I have key backup enabled and trust all my devices from all my devices.

Log: sent

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian Testing
- **Version**: 1.0.1 (*Could you submit 1.0.3 to Flathub by merging https://github.com/flathub/im.riot.Riot/pull/36?*)

**Comment by Mikaela** [comment]
![Screenshot_20190314-114159](https://user-images.githubusercontent.com/831184/54346810-a4012a80-463d-11e9-89fc-43390b823448.png)

Interestingly my phone has a warning mark for the Riot from which I sent logs and it says both key ID and fingerprint key ID to be none and that the sender is unknown device.

**Comment by dbkr** [comment]
The device key has changed here, so this is probably another instance of https://github.com/vector-im/riot-web/issues/9107. Interestingly this is an Electron client. The appearance of the bug doesn't seem to coincide with a client update so it looks like chromium is deleting the indexeddb in the same way.

**Comment by Mikaela** [comment]
I sent another debug log for this, the only change is that Riot version is now 1.3.0 (and Debian Testing is nowadays 11/Bullseye).

**Comment by Mikaela** [comment]
I have "resolved" this by removing all devices from my account and running `rm -rf ~/.var/app/im.riot.Riot` and clearing data on my Androids.

**Comment by poljar** [comment]
We're now notifying the user about the error state here via https://github.com/vector-im/element-web/issues/9109. I'm afraid there's not much more we can do if indexeddb gets cleared.
