### ISSUE TITLE
Typing notifications are often coming after messages arrive

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9173]
I've only really noticed this with matrix.org users, but that might be population bias.

![image](https://user-images.githubusercontent.com/1190097/54367311-cf811680-4637-11e9-9d6e-15a23deb5e64.png)

**Comment by lampholder** [comment]
I've stuck the 'synapse' label on this 'cause I'd guess that they're involved somehow (either directly, sending typing notif events with a higher delay than message events, or indirectly just by being overloaded).

**Comment by turt2live** [comment]
I think we can close this, yea.
