### ISSUE TITLE
Consider formally supporting Edge

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9175]
We don't really support it (if it works, yay! if it doesn't, use $NotEdge). Maybe we should? It has the advantage of being heavily encouraged to Windows users, but has the downside of being less proficient in API compatibility.

**Comment by lampholder** [comment]
Does anybody know when the new Chromium-internals Edge is due to be released? Once the latest version of edge is Chromium-powered would be a good time to officially support it - there should be a smaller delta between it and Chrome, and we won't waste time fixing current impl weirdnesses.

**Comment by jryans** [comment]
The best date I could find for Edge using Chromium release was second half of 2019.

**Comment by lampholder** [comment]
We have agreed that we do not support Edge today, but will reevaluate the situation once they've released their Chromium-powered Edge (whenever that may be).

**Comment by jryans** [comment]
Preview builds of the Chromium-based Edge are [now available](https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/). It can be used side by side with legacy Edge. I haven't seen any new guidance on when a stable release would happen.

**Comment by aaronraimist** [comment]
The new Edge came out on the 15th. I started using Riot in it yesterday and so far I haven't noticed any new issues.

**Comment by jryans** [comment]
After reviewing recent browser stats and community feedback, the core team has agreed it's appropriate to add Edge to our supported set of browsers.
