### ISSUE TITLE
option to hide the country dropdown in the phone number picker on the login page

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9182]
for people who are trying to log into LDAP using a non-internationalised phone number, and so just want to be able enter 0123456789 without a +7 prefix.

**Comment by lampholder** [comment]
@ara4n Do you have thoughts on how this option be exposed? Riot's `config.json` or something server side? Or user-facing UX to dismiss the country-picker dropdown?

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author or anyone else. _Feel free_ to reopen or ping me if this is still a problem.
