### ISSUE TITLE
Expanding a really large Event List Summary causes it to spontaneously collapse again

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9192]
Reproduction steps

1. have a room that has experienced LOT of membership events (in this case, 700)
2. expand the summary (MELS), possibly scroll up, watch it get replaced and thus collapse again

Notes:

* presumably expanding it triggers backpagination or something which causes a rerender which then renders a collapsed MELS
* in theory not a horribly hard thing to fix, just needs a cache in the TimelinePanel to track which events are shown in a MELS and use that cache when building MELSes so that when you back paginate you don't change its key causing React to throw away the existing state
* to put more words on the cause, we have to key every tile in the timeline with a unique string, for MELS we use the event ID of the first event shown, the issue with that is, when backpaginating, that first event may change (an older event may be found) so then the key changes and React throws the whole subtree away

**Comment by aaronraimist** [comment]
Example of this in `#matrix:matrix.org` https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1562545524706814mhcdy:matrix.org?via=matrix.org&via=half-shot.uk&via=privacytools.io

**Comment by t3chguy** [comment]
Yup, if the backpagination loads more events into the MELS then its key changes and thus it loses its state

**Comment by novocaine** [comment]
This is uncommon as membership events of this scale are relatively rare.

**Comment by t3chguy** [comment]
MELS is no longer Membership-specific as it used to be in 2019, now includes hidden events, redactions etc
