### ISSUE TITLE
Don't recreate desktop shortcut on update if it doesn't already exist

### ISSUE THREAD

**Issue by khionu** [vector-im/element-web#9210]
Each time Riot updates, it recreates the shortcut on my desktop. This is quite annoying, as I keep my desktop pretty clean.

**Comment by t3chguy** [comment]
electron-builder does not give us control over this: https://www.electron.build/configuration/squirrel-windows

**Comment by khionu** [comment]
Discord uses Squirrel as well, and does not have this issue.

**Comment by t3chguy** [comment]
Is there any certainty in them using electron-builder though or are they rocking some custom in-house thing?

**Comment by khionu** [comment]
I'll get back to you on that.

**Comment by aaronraimist** [comment]
@t3chguy the link you sent says

> Squirrel.Windows target is maintained, but deprecated. Please use nsis instead.

and nsis does have an option you can set https://www.electron.build/configuration/nsis

> createDesktopShortcut = true Boolean | “always” - Whether to create desktop shortcut. Set to always if to recreate also on reinstall (even if removed by user).

**Comment by t3chguy** [comment]
@aaronraimist this is known but Riot at least disliked nsis due to its update mechanism which was basically an uninstall followed by a new install which wasn't the most friendly flow.

**Comment by BloodyIron** [comment]
Surely there's some way to get this done, cmon this is really frustrating.

**Comment by ajayyy** [comment]
Yea, this is very frustrating

**Comment by ryanfleury** [comment]
Extremely frustrating that this has not been addressed in nearly 3 years. I mean, come on.

**Comment by aminomancer** [comment]
if we can't get low enough into Squirrel.Windows to prevent the shortcut from being created in the first place, can we at least script something to log whether the shortcut exists at the time the in-app update button is pressed, then remove the shortcut on app startup if the shortcut did not exist? it's not the most glamorous solution but it's better than making an unwanted file on every update (which is pretty frequent for me)

**Comment by elibroftw** [comment]
@t3chguy, what is used to auto update then?

**Comment by t3chguy** [comment]
@elibroftw https://github.com/vector-im/element-web/issues/9210#issuecomment-474338819

**Comment by elibroftw** [comment]
@t3chguy okay, then check if the shortcut exists before starting the auto install, and then delete the file afterwords. Use a settings key like "post-install" and then upon a launch, element should do the actions specified in the "post-install" key and then delete the post-install setting.

**Comment by elibroftw** [comment]
https://github.com/electron-archive/grunt-electron-installer#handling-squirrel-events

**Comment by elibroftw** [comment]
@t3chguy https://github.com/vector-im/element-desktop/blob/develop/src/squirrelhooks.ts#L41

**Comment by elibroftw** [comment]
Specifically, `--shortcut-locations=Desktop,StartMenu` https://stackoverflow.com/questions/30105150/handle-squirrels-event-on-an-electron-app

**Comment by elibroftw** [comment]
Actually, I don't think you're actually supposed to call the Updater to do the work for you. The docs clearly say you only need to handle the argument, not that you need to call an Updater executable.

**Comment by elibroftw** [comment]
```
Manages Squirrel packages

Commands
      --install=VALUE        Install the app whose package is in the specified
                               directory
      --uninstall            Uninstall the app the same dir as Update.exe
      --download=VALUE       Download the releases specified by the URL and
                               write new results to stdout as JSON
      --checkForUpdate=VALUE Check for one available update and writes new
                               results to stdout as JSON
      --update=VALUE         Update the application to the latest remote
                               version specified by URL
      --releasify=VALUE      Update or generate a releases directory with a
                               given NuGet package
      --createMsi=VALUE      Update or generate a releases directory with a
                               given NuGet package
      --createShortcut=VALUE Create a shortcut for the given executable name
      --removeShortcut=VALUE Remove a shortcut for the given executable name
      --updateSelf=VALUE     Copy the currently executing Update.exe into the
                               default location

Options:
  -h, -?, --help             Display Help and exit
  -r, --releaseDir=VALUE     Path to a release directory to use with releasify
  -p, --packagesDir=VALUE    Path to the NuGet Packages directory for C# apps
      --bootstrapperExe=VALUE
                             Path to the Setup.exe to use as a template
  -g, --loadingGif=VALUE     Path to an animated GIF to be displayed during
                               installation
  -i, --icon=VALUE           Path to an ICO file that will be used for icon
                               shortcuts
      --setupIcon=VALUE      Path to an ICO file that will be used for the
                               Setup executable's icon
  -n, --signWithParams=VALUE Sign the installer via SignTool.exe with the
                               parameters given
  -s, --silent               Silent install
  -l, --shortcut-locations=VALUE
                             Comma-separated string of shortcut locations, e.g.
                               'Desktop,StartMenu'
      --no-msi               Don't generate an MSI package
      --no-delta             Don't generate delta packages to save time
      --framework-version=VALUE
                             Set the required .NET framework version, e.g.
                               net461
```

**Comment by elibroftw** [comment]
Yeah there's no reason to create shortcuts on an update.

**Comment by t3chguy** [comment]
You're welcome to contribute it yourself, I don't use Windows anymore.

**Comment by joshsleeper** [comment]
@elibroftw while I agree with your sentiment and also want this feature, remember that github issues isn't a chat platform and people get emails for each new message.

instead of sending a bunch of messages in a row, consider either editing one comment to add more context or just not hitting send until you've fleshed it out more.

not trying to nag or shame, just trying to reduce everyone's email intake 😅
