### ISSUE TITLE
Replies to a mesage on a previous day should not include the horizontal rule and day header

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-web#9217]
### Steps to reproduce
- Send messages over a few days in a channel, specifically:
- Send a message on monday,
- Send a message on tuesday in-reply-to the message on monday
- Then: view the message on wednesday

Describe how what happens differs from what you expected.

The timeline looks like (note it is Wednesday today) this:

While it is useful to know that the replied to message was sent on Monday, at a glance this page looks like two messages sent today, then two messages sent on Monday, then further messages sent "before Monday" - you have to look hard to see that the Monday line ends in the White Line Of Reply To, and so the horizontal bar can be ignored.

I would ask that the Monday and line not be shown in this case.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: ubnutu
- **URL**: riot.im/app (also develop)

**Comment by michaelkaye** [comment]
![to-edit](https://user-images.githubusercontent.com/1917473/54676891-a52cce80-4af9-11e9-86e8-901943006d83.png)

**Comment by t3chguy** [comment]
This used to look less confusing pre-redesign but now is abysmal

**Comment by lampholder** [comment]
For reference:

Old style: 
![image](https://user-images.githubusercontent.com/1922197/57075348-74d27580-6cde-11e9-8980-483a795a42ef.png)

New style:
![image](https://user-images.githubusercontent.com/1922197/57075390-959acb00-6cde-11e9-8ad4-b216a54fb0d6.png)

**Comment by lampholder** [comment]
It's bad but not the end of the world I think. We do need to include the day on which a previous message was sent (to avoid taking messages out of context).

@nadonomy - is there already a design for this?

**Comment by nadonomy** [comment]
We don't. Original message metadata should be visualised with similar weight in the info hierarchy as general timestamps in messages. I can visualise a design though once we're arriving at it in our backlog.

Also worth mentioning that in the (hopefully near) future replies should be supplanted in usage by threads.

**Comment by lampholder** [comment]
Just leaving a note on this issue - I would be surprised if replies were supplanted by threads. Unless we can make threads super lightweight, I think they serve a different usecase. It's true that some replies will likely identify the need for a thread (indeed, when planning the replies feature originally I imagined a 'start a thread' button hanging off a sequence of replies to see a thread with the three or four messages that have already gone back and forth inreply).
