### ISSUE TITLE
Rich messages wrapped in p tags break emote rendering

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9230]
as the p tag is rendered as a block, causing a linefeed between the nick and the message body. we should probably specialcase the first p tag in a message to be an inline block via CSS.

**Comment by lampholder** [comment]
@ara4n how do you make this happen?

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by jryans** [comment]
Not enough info, going to assume it's not.

**Comment by ara4n** [comment]
yeah, it got fixed in the new composer.
