### ISSUE TITLE
Backslashes added when quoting a message containing markdown formatting

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9231]
### Description

Quoting a message that contains some markdown will causing spurious backslashes to be added, escaping punctuation and parentheses etc.

![image](https://user-images.githubusercontent.com/1342360/54749043-4899e400-4bcb-11e9-83ba-6efbd160fc87.png)

I presume it's because we convert the HTML back to non-markdown or something? But we can just take the `body` which is perfectly fine:

```
"body": "This is a *message* containing markdown. Thanks for listening (<3)"
```

Might be related to https://github.com/vector-im/riot-web/issues/7324

### Steps to reproduce

- Send a message with markdown such as `This is (really) *great*.`
- Quote the message
- Notice `\` escape characters inserted

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: independent build of riot.im/develop

**Comment by t3chguy** [comment]
> I presume it's because we convert the HTML back to non-markdown or something? But we can just take the body which is perfectly fine:


The body being correct markdown is just a riot-web thing, mobile clients don't match iirc and other clients probably don't either so this is definitely not a good approach.

**Comment by anoadragon453** [comment]
Ah, unfortunate :/

Well then perhaps just a second pass after the parser goes would work.

**Comment by ssokolow** [comment]
I've found that trying to escape `*chuckle*` so it doesn't get interpreted as italics results in the escape showing up in the output too (`\*chuckle*`).

Would this be the same bug or should I file a new one?

**Comment by jryans** [comment]
This does not seem to an issue with the current composer.
