### ISSUE TITLE
Toggling the 'blacklist unverified devices' option on and off is an easy way to get UISIs

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9258]
Steps:
1. Alice starts an encrypted chat with Bob. Neither has verified each other's devices, and neither has the blacklist unverified devices option enabled.
2. Alice sends a message to Bob. Bob should receive this.
3. Alice disables sending to unverified devices (either per-room or global)
4. Alice sends a message to Bob. Bob should not be able to decrypt this.
5. Alice toggles off the option set in step 3.
6. Alice sends another message to Bob. Bob should be able to receive this, but needs to send a keyshare request to have it decrypt.
7. If Alice continues to send messages, Bob will eventually be able to decrypt the history without sending keyshare requests.

**Comment by anoadragon453** [comment]
So the bug here is that a keyshare request is required even though it would not have been had the option not been toggle on/off?

**Comment by turt2live** [comment]
Yes, teh bug is in step 6 where Bob can't decrypt messages. The bad UX for step 4 is https://github.com/vector-im/riot-web/issues/3831

**Comment by anoadragon453** [comment]
Hmm, following this steps on a test setup has Bob decrypting the messages just fine.

But this is two HS's with just one user on each.

**Comment by turt2live** [comment]
I wonder if federation (for once) isn't the problem: I tested them on the same homeserver. It's also possible your keys rotated at a really convenient time? I suspect that's what the problem is here given "if Alice sends enough messages, Bob's history magically works"

**Comment by anoadragon453** [comment]
The test was between two homeservers. Room freshly created, then encrypted. Tried it twice when one user enabled/disabled (which worked) then the other user enabled/disabled (which worked).

I can try on the same hs though.

**Comment by anoadragon453** [comment]
Same results when using the same HS.

Interestingly the error is initially "Unable to decrypt: the sender has not sent us the keys for this message".

But as soon as the second message comes in successfully, it switches to "Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX".

**Comment by turt2live** [comment]
I've also just tried it and can reproduce it 100% of the time :/

The OLM_MESSAGE_INDEX thing is also known, and a result of https://github.com/vector-im/riot-web/issues/3831 being a thing.

**Comment by duxovni** [comment]
Could no longer reproduce in recent community testing session, closing
