### ISSUE TITLE
Riot cannot show 3gp films

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#9262]
The format is not supported, it seems.
And when I try to download it tries to open in my browser instead, and fails, which means I have no way to watch it.  Opening the link directly in VLC doesn't work either, even though VLC supports the format.

**Comment by Biep** [comment]
Wait - the file is empty!  size 0.  Still, _download_ ought to download, not open a browser tab.

**Comment by jryans** [comment]
If you hover the video message in Riot, click "..." -> View Source, what do you see for the video event?

**Comment by Biep** [comment]
I see the size 0, which no doubt is the problem.
{
  "content": {
    "body": "VID_20190320_092041.3gp",
    "info": {
      "mimetype": "video/mp4",
      "size": 0
    },
    "msgtype": "m.file",
    "url": "mxc://matrix.org/RXNRzQOKNgXXKiHhuJMWieKZ"
  },
  "event_id": "$1553368048489576WOfwc:matrix.org",
  "origin_server_ts": 1553368048881,
  "sender": "@rateba:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 241
  },
  "room_id": "!wUWprjzEfijmuhyCHo:matrix.org"
}

**Comment by jryans** [comment]
I believe the core issue is that the Synapse media repository is set up for recognizing specific media types, and currently `3gp` isn't recognized.

See also https://github.com/matrix-org/matrix-doc/issues/1938 which suggests specifying which media types are supported.

**Comment by t3chguy** [comment]
Closing as a Synapse issue, if you are still experiencing this then please open an issue in https://github.com/matrix-org/synapse/
