### ISSUE TITLE
missing welcomeUserId doesn't disable matrix-bot button on welcome page

### ISSUE THREAD

**Issue by killua-eu** [vector-im/element-web#9263]
### Description

With `"welcomeUserId": "@riot-bot:matrix.org",` removed from the config.js, the "Chat with the Riot Bot" button is still visible/actionable on https://chat.example.com/#/welcome. On servers with federation turned off, clicking the button leads unsuspecting users into an empty room.

### Version information

- **Platform**: web 
- **Version**: 1.0.5

**Comment by jaywink** [comment]
I was playing around this and it seems that setting it to an empty string does disable Riot Bot, at least it stops the initial chat room invitation made on signup.

**Comment by jryans** [comment]
> it stops the initial chat room invitation made on signup

Removed key _should_ also work as well, from what I can tell, to stop the invite on registration. The issue here about the button on welcome still applies, however, since welcome isn't checking the config yet.

**Comment by turt2live** [comment]
fwiw the expectation in the implementation of the welcome page was originally that people would simply overwrite the HTML document with their own rather than it be dynamic content.

**Comment by turt2live** [comment]
our default welcome page has removed the button
