### ISSUE TITLE
Implement text and gui size customization

### ISSUE THREAD

**Issue by anon88391** [vector-im/element-web#9265]
The text on the client is very small and difficult to read for some people such as myself. 
A solution to that would be simply implementing a feature to customize the size of the text and gui in the settings. Discord has such feature and the lack of it in Riot is very annoying.
Below I'll link a screenshot of the appearance settings in Discord which, in my opinion, Riot should implement.
https://i.imgur.com/EYZ6OR0.png

**Comment by t3chguy** [comment]
This now exists:
![image](https://user-images.githubusercontent.com/2403652/98845428-9836be80-2445-11eb-934a-d72528555fcf.png)
