### ISSUE TITLE
sometimes typing notifications get squashed into room content

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#9356]
Seen this a couple of times on /develop:

![image](https://user-images.githubusercontent.com/1389908/55390951-3c4d4980-5530-11e9-939a-92100eeabbbc.png)

**Comment by bwindels** [comment]
Hm, interesting. Haven't seen this myself. Looks like something has a negative margin, but no immediate idea what it is. If you see this again, would be great to see what the inline CSS looks like of the ScrollPanel, WhoIsTyping, ReadMarker nodes.

**Comment by bwindels** [comment]
Wrt to the inline style, I meant anything set through the style property on an element itself. To capture these, you could copy the outer html in the inspector of either FF or Chrome of the element with class `mx_RoomView_timeline` and add them to this ticket.

**Comment by richvdh** [comment]
I think I managed to catch this. Html spew at http://www.sw1v.org/~rav/x.html. I can't see any interesting inline styles, but it's a bit hard to see anything.

**Comment by bwindels** [comment]
Thanks for the html spew, unfortunately it didn't make me much wiser :/
Indeed no inline style that could explain it. How often are you seeing this? Anything you've noticed that seems to trigger it?

**Comment by richvdh** [comment]
A few times a day? And no, I can't figure out a pattern.

**Comment by richvdh** [comment]
I'm still seeing this sort of thing occasionally:

![image](https://user-images.githubusercontent.com/1389908/57011360-2f884800-6bf9-11e9-98fa-69bdf42b1294.png)

**Comment by richvdh** [comment]
it seems to me that the height of the WhoIsTypingTile is too small:

![image](https://user-images.githubusercontent.com/1389908/57363972-1859d500-717a-11e9-9b62-a14a71b903d4.png)
