### ISSUE TITLE
no call notification (desktop app)

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/element-web#9364]
### no call notification

When I receive a (video)call I don't see and I don't hear nothing.

### Steps to reproduce

- receive a video call
- you don't see and you don't hear anything.
- only opening riot.im you can notice the call

### 1.0.6

- **Platform**: desktop

For the desktop app:

- **OS**: Kubuntu
- **Version**: 18.04

### to notice  
This problem is only on desktop (PC) app, in android app it's all right.

**Comment by jryans** [comment]
Do you get notifications for regular messages?

**Comment by DoctorSubtilis** [comment]
Do you mean text messages? No, I don't. But I don't care of text messages, the important is video call.

**Comment by jryans** [comment]
I guess what I trying to discover is: Is it possible for Riot to send any form of notification on your system? Temporarily enabling notifications for text would be a quick way to check.

This will help us understand if notifications are somehow broken in general or if it's specific to video calls.

**Comment by DoctorSubtilis** [comment]
> I guess what I trying to discover is: Is it possible for Riot to send any form of notification on your system? Temporarily enabling notifications for text would be a quick way to check.
> 
> This will help us understand if notifications are somehow broken in general or if it's specific to video calls.

Already enabled (I checked it). :(  
And this problem is also in PC of my sister (Kubuntu 18.04)...

**Comment by jryans** [comment]
> Already enabled (I checked it). :(

So you have tried enabling notifications for text and sending a message that would potentially trigger one? Did the notification for text appear or not?

**Comment by DoctorSubtilis** [comment]
Notifications of text messages work well.

**Comment by DoctorSubtilis** [comment]
So: what do you tell me?

**Comment by DoctorSubtilis** [comment]
Fireworks with notifications: now appear notifications even already read and there is nothing to to to cancel them. Sometimes Riot-web does not start.

**Comment by SimonBrandner** [comment]
> After update and reboot all seems ok: I get sound and pop-up notification. The wrong notifications have disappeared.

I am going to close this as the issue seems to be fixed for you. Let me know if you ever see this again!

> However, why don't appear a pop-up with green (accept) end red (refuse) choice? It would be the best thing. Thank you.

That is due to Electron and browsers not allowing us to do that easily... It is a separate issue though
