### ISSUE TITLE
[Feature] Cordova API

### ISSUE THREAD

**Issue by DaniellMesquita** [vector-im/element-web#9372]

**Comment by aaronraimist** [comment]
Riot Web does not target mobile platforms at the moment https://github.com/vector-im/riot-web/issues/9329#issuecomment-478498091 and there are no plans to do so. 

> We would need to very consciously choose to support mobile web and invest in making it work for there to be any chance of it working well as each new feature lands over time. At the moment, we're focusing on the Riot apps for mobile, so I'll close this issue.

**Comment by jryans** [comment]
@DaniellMesquita Can you be more specific about what "Cordova API" would mean in this context? You'd like Riot to use Cordova? You'd like Riot to offer some of API...?

**Comment by DaniellMesquita** [comment]
> @DaniellMesquita Can you be more specific about what "Cordova API" would mean in this context? You'd like Riot to use Cordova? You'd like Riot to offer some of API...?

The same Riot Web that supports Electron, supporting Cordova, being an alternative to the native app

**Comment by jryans** [comment]
> The same Riot Web that supports Electron, supporting Cordova, being an alternative to the native app

Normally when I read "Cordova", I think of "web site packaged as a mobile app using the Cordova APIs". It see now that Cordova also supports desktop platform as well.

@DaniellMesquita Can you describe the use case you have in mind? Why do you want this? Are you thinking of desktop, mobile, or both? Apologies if I am being daft, but I am still not sure I understand the goal here, so more detail would help.

**Comment by SimonBrandner** [comment]
Thank you for opening an issue. Unfortunately, we don't seem to have enough info here, please update your description with steps/screenshots/video/more details and add a comment with `@SimonBrandner` to let me know that it’s ready to be reopened.
