### ISSUE TITLE
js-sdk goes and hits the profile API whenever we ask what our displayname is. surely we should cache this?

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#940]
It seems nuts that the JS SDK doesn't know what its client is called(!)

A corollary is: how do we get told when our own profile data gets updated?  (@erikjohnston: are you replacing m.presence mess with m.profile account_data for this?)

**Comment by ara4n** [comment]
This is a particular issue for things like displaying the right placeholder avatar in UserSettings

**Comment by dbkr** [comment]
on a quick check, it doesn't seem to be making calls to the profile endpoint when I open settings, so I guess this is fixed
