### ISSUE TITLE
Add option to change font

### ISSUE THREAD

**Issue by tim77** [vector-im/element-web#9403]
Apologize if this already asked but please add option to change manually font or at least using system default font option. Non-English font look weird and something wrong with kerning probably.

For example default font in Fractal app look much better and more readable.

**Comment by jryans** [comment]
Hmm, it sounds like the real issue is "UI font should look good for all character sets", instead of needing an option? If the current looked good for non-Latin characters, you wouldn't need an option, correct?

**Comment by tim77** [comment]
@jryans i want to say yes, "UI font should look good for all character sets", but in same time i still want to have option for font choice or using system font option. 🙂 Because of consistent looking UI probably.

Riot font is not bad itself especially English latin font family, but dunno. Feeling some kind of discomfort especially when mixing EN with non-EN messages.

**Comment by jryans** [comment]
Let's use https://github.com/vector-im/riot-web/issues/7949 to track the issue of the current font (Nunito) looking bad for non-Latin characters.

We can use this issue to track the idea of a font option in a general sense then, independent from specific issues with the current font.

**Comment by Yrr0r** [comment]
I suggest to use another font that covers more character sets. 
Nunito has only European characters covered, when I type Chinese it falls back to SimSun, which is a print font and looks horrible on screens. 
It seems not possible for the author to add Chinese/Japanese/Korean characters into this font, so instead I suggest to use font with wider charset.

Here is a nice one I found which covers almost everything: [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) .

**Comment by BrenBarn** [comment]
The issue is not just about picking a single font that "looks good".  Individual users should be able to choose the fonts they individually prefer.

**Comment by bitrage** [comment]
I support the initial idea of an additional option. I would like to change the desktop client to a monospace font, to make it look more like a cli (irc nostalgia).

**Comment by hakavlad** [comment]
What about Noto fonts by default?

**Comment by aquatix** [comment]
This would also make it possible to have it integrate better with the desktop environment: it's one of the few applications that have a different font than the rest of my applications and DE. Also, somehow the font that's used is a bit blurrier than my system font, which makes me want to change it even more :)

**Comment by svito3** [comment]
Browsers already have font options for preferred `sans-serif`, `serif` and `monospace` fonts. I'm for removing all web fonts (including emoji #9790) and just have `font-family:sans-serif;`.

**Comment by bwindels** [comment]
I'm working on font support for custom themes in https://github.com/matrix-org/matrix-react-sdk/pull/4814 fwiw

**Comment by aquatix** [comment]
@bwindels that's really cool! It would just be nice if Riot would take a clue from the desktop environment to use its default font. If that is error-prone (which I can understand, considering the amount of different DE's like Gnome, KDE, xfce, Windows, Mac :) ), it would at least help me to have a font chooser.

Custom themes would be interesting of course, as I can tailor it even more to my current GTK theme, but it would be a bit overkill just for setting the font in the default theme, which I already find rather satisfying :)

**Comment by turt2live** [comment]
This is now supported in the appearance tab of settings under "Advanced"

**Comment by AgentOak** [comment]
@turt2live Is there a way to set a non-regular font?

For example, `Liberation Sans` works fine, but `Liberation Sans Bold` falls back to some default serif font. That is the name according to the Windows Font Settings:
![element-font-name](https://user-images.githubusercontent.com/1313295/97377217-ca7de300-18bf-11eb-94ab-7ef423130510.PNG)

**Comment by turt2live** [comment]
Please use #element-web:matrix.org for support, not old issues.
