### ISSUE TITLE
Pinned message dialog can get stuck behind the E2EE key backup warning

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9423]
Just had this rather amusing bug report from a user. They first thought the pinned messages button wasn't working at all. Then they realized that it did work but only in unencrypted rooms.

Finally, once removing the key backup warning dialog, low and below pinned messages started working again!

We should probably raise its z-depth.

**Comment by turt2live** [comment]
I think we need to take a serious look at our AuxPanel usage as there's 10 or so different things that can be displayed there, all with their own state machine.

**Comment by SimonBrandner** [comment]
This doesn't seem to be relevant anymore
