### ISSUE TITLE
If you try to change your password and enter an incorrect existing password, you get a dumb 401 error dialog :(

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9449]
<img width="160" alt="Screenshot 2019-04-12 at 22 08 48" src="https://user-images.githubusercontent.com/1294269/56063467-9db2bb00-5d6f-11e9-82cf-efe8715d4bb8.png">

**Comment by anoadragon453** [comment]
Also just ran into this. Seems silly.

![image](https://user-images.githubusercontent.com/1342360/58320572-d8e6e600-7e13-11e9-9db5-b79c07899e63.png)

**Comment by Ulimn** [comment]
I ran into this after trying to change my password because riot cut it short on register. Without any notice. This project is garbage.

**Comment by dkasak** [comment]
Bump. Just ran into this myself. Seems horrible from a UX perspective.

**Comment by novocaine** [comment]
Can't reproduce; I see this which is pretty ugly but not as reported

<img width="753" alt="Screenshot 2021-08-19 at 14 14 04" src="https://user-images.githubusercontent.com/57377/130074773-e1007153-527b-4122-82e0-a6f6bc6c34a8.png">

**Comment by novocaine** [comment]
closing as can't repro
