### ISSUE TITLE
Language template warning on password reset

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9458]
```
rageshake.js:107 safeCounterpartTranslate called with undefined interpolation name: serverName
```

**Comment by novocaine** [comment]
@turt2live can you provide more context about this one?

**Comment by turt2live** [comment]
The password reset page spits out a warning to the console about translation stuff. It doesn't appear to affect operation, but is console noise.

**Comment by novocaine** [comment]
Okay, I can't reproduce so maybe it's been fixed .. if you get a moment, could you see if it's still happening?

**Comment by SimonBrandner** [comment]
Yeah, I also had a quick look through the code and didn't manage to find the cause of this

**Comment by turt2live** [comment]
I'm inclined to believe it was a temporary failure at the time of reporting.
