### ISSUE TITLE
Delete email addresses of deactivated accounts / MXIDs on identity servers

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-web#9464]
### Description

I still can find a disabled MXID created on matrix.org looking for the mail address provided for the disabled account.

### Steps to reproduce

Create a MXID on matrix.org and provide a mail address.
Disable the MXID.
Choose "Start a chat" by using another account and provide the mail address linked to the disabled MXID. A room will be created inviting the disabled MXID.

> Describe how what happens differs from what you expected:

I find the disbaled account but would expect that I can not find it because it is disabled.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox
- **OS**: Debian
- **URL**: riot.im/app

**Comment by lampholder** [comment]
Hmm, I haven't been able to reproduce this. I created a new account, used it briefly, disabled it (_without_ checking the erase all history button) and then invited its email address to a romo

Can you advise when was the disabled account disabled? (_very_ approximate timelines are fine)

**Comment by r4dh4l** [comment]
Sorry for my late reply @lampholder 

> Can you advise when was the disabled account disabled? (very approximate timelines are fine)

According to my KeePass entry until 2018-01-26.

**Comment by turt2live** [comment]
This appears to be a synapse/deployment issue, so closing here. If this can still be reproduced then please open an issue on the Synapse repo with relevant information.
