### ISSUE TITLE
No system tray icon in Gnome 3.32

### ISSUE THREAD

**Issue by Bendodroid** [vector-im/element-web#9477]
![image](https://user-images.githubusercontent.com/26770477/56131132-f019f480-5f86-11e9-95c6-379d00e4c216.png)

### Description

There is no system tray icon. So no ability to hide it to system tray etc.

I suppose its since the tray thing changed in one of the last GNOME versions.

### Steps to reproduce

Install Riot from the Manjaro Repositories and start it.

I also get an Integrations error, but I can't click on it to see the cause.

![Screenshot from 2019-04-15 14-03-59](https://user-images.githubusercontent.com/26770477/56131722-81d63180-5f88-11e9-8a44-88a1abc6ecab.png)

### Version information

Desktop app from Manjaro 18.0 testing Repos.

![image](https://user-images.githubusercontent.com/26770477/56131581-20ae5e00-5f88-11e9-99c2-ba051cac6393.png)

**Comment by jryans** [comment]
> I also get an Integrations error, but I can't click on it to see the cause.

This bit is unrelated. It's happening because the integration server was down at the time.

**Comment by jryans** [comment]
@Bendodroid Do you happen to use any other Electron-based apps on your system? I'm curious if all Electron apps are facing this problem, or only Riot.

**Comment by Bendodroid** [comment]
@jryans  The Mullvad VPN app has the same issue, I already reported the bug there as well. I'm not sure if the JetBrains Toolbox uses electron or something else. Other than that, I'm not aware of any other electron apps on my system that should have system tray icons.

**Comment by enzingerm** [comment]
I had to install `libappindicator-sharp` and `libappindicator-gtk3` to get the tray icon to work again (together with Gnome and the extension [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/)

**Comment by Bendodroid** [comment]
Great! Just installing `libappindicator-gtk3` is enough for me. This should probably be added as a dependency for the package or at least be documented somewhere in this repo for people to find.

**Comment by t3chguy** [comment]
The dependencies are managed by electron-builder and cannot be modified from this level, if you feel like it should be a dep then you should open an issue there

**Comment by bugger11** [comment]
> I had to install `libappindicator-sharp` and `libappindicator-gtk3` to get the tray icon to work again (together with Gnome and the extension [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/)

Why would `libappindicator-sharp` (and mono) be required for Riot / electron? 
I am on Arch Linux with KDE. I first installed  `libappindicator-gtk3` but that did not resolve the issue. So I reluctantly tried installing `libappindicator-sharp` (which pulls in mono), and that did resolve the issue. But I would prefer not to have to install mono. Is it really a dependency now? Or am I missing something?

**Comment by t3chguy** [comment]
Are people still experiencing this?

**Comment by MountainX** [comment]
> Are people still experiencing this?

I guess that depends on what you mean by "this". Like other commenters above, I'm running Element (desktop) on KDE and I had to manually install `libappindicator-gtk3`. 

In Arch Linux, libappindicator-gtk3 is listed as an optional dependency for electron17. I guess that might be the expected situation. If so, then things are working as expected on Arch Linux & KDE for me. Hope that helps.

**Comment by t3chguy** [comment]
Is this an issue for anyone on the official `deb` or only on community maintained packages e.g arch?

**Comment by t3chguy** [comment]
Closing due to lack of ayes, presuming fixed by Gnome 40 or specific to community packages.
