### ISSUE TITLE
"Back to Riot.im" on mobile redirect page on independent Riot instances

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9479]
![](https://i.imgur.com/6orBEqW.png)

"Back to riot.im" is shown when on a separate instance of Riot that's not hosted on Riot.im.

I recommend changing the button text to "Back to Riot", which is more generic.

**Comment by turt2live** [comment]
The product is Riot.im though :(

Does it at least go back to the self hosted page?

**Comment by anoadragon453** [comment]
It does indeed.

**Comment by jryans** [comment]
These days, we usually refer to the product as just "Riot", so it seems go to update the name here.

**Comment by turt2live** [comment]
I'm going to throw this to @nadonomy instead, as he's been in the area recently.

**Comment by anoadragon453** [comment]
These days this just says "Go to Desktop Site":

![image](https://user-images.githubusercontent.com/1342360/132841564-a276a0c5-9bc1-4624-8e83-56d17b4252a5.png)

So I think this issue can be closed.
