### ISSUE TITLE
SenderProfile doesn't give colour to usernames for file uploads, etc

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9482]
![image](https://user-images.githubusercontent.com/1342360/56147938-2a908b00-5fa1-11e9-82c6-c11b956ff856.png)

The "someuser uploaded a file" text is in white, which makes it tricky to distinguish it from a normal message. Perhaps the text (or part of it) should be in the user's color instead?

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This is probably because we don't give the username any of the colouring
