### ISSUE TITLE
Keys Backup can be setup twice

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-web#9510]
I reproduced on Riot-web the issue described here: https://github.com/vector-im/riot-android/issues/2973

Indeed while setup banner is displayed on the top of an encrypted room, if I create the backup on another client, and then click on the "Start using Key Backup" button of this banner, I will create a new backup.

When clicking on "Start using Key Backup" button, a force refresh should be done

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot reproduce it. Please reopen with more info if you are still experiencing it
