### ISSUE TITLE
--no-update, maybe unrelated error

### ISSUE THREAD

**Issue by vsatmydynipnet** [vector-im/element-web#9513]
I downloaded 1.0.8 today, so I am on the last release. Users are able to connect to their matrix homeserver also without proxy, so i start with --no-update only now. Works, but raises an error. After the error Riot starts and users are able to use it. So no stress with this one.

On a Terminal Server you must extract the  setup.exe, then the nupg, followed by copying the riot-x-x-x-full to a special directory. then all users can start if from one location. worked perfect for the first start, confirmed device all fine.

System: Windows 2016 Terminal Server

>C:\Programme\riot-web\lib\net45\Riot.exe  --no-update

C:\Programme\riot-web\lib\net45>
 Starting auto update with base URL: https://riot.im/download/desktop/update/
(node:5628) UnhandledPromiseRejectionWarning: ReferenceError: win is not defined
    at WebContents.<anonymous> (C:\ProgrammeZ\riot-web\lib\net45\resources\app.asar\src\tray.js:68:17)
    at WebContents.emit (events.js:182:13)
(node:5628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5628) UnhandledPromiseRejectionWarning: ReferenceError: win is not defined
    at WebContents.<anonymous> (C:\Programme\riot-web\lib\net45\resources\app.asar\src\tray.js:68:17)
    at WebContents.emit (events.js:182:13)
(node:5628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by turt2live** [comment]
Looks like Riot requires a task tray, which I don't think terminal server offers by default (especially at the system level).

**Comment by jryans** [comment]
This seems like an unsupported configuration.
