### ISSUE TITLE
Deleting current device disconnects but the settings modal remains visible

### ISSUE THREAD

**Issue by yzaroui** [vector-im/element-web#9523]
### Description

When you delete your current device, you are disconnected and "routed" to the login UI but the settings modal remains visible and hides the login form.

### Steps to reproduce

- Open user settings
- Select the Security & Privacy tab
- Select your current device (bold line)
- Click on Delete Device button

The user is disconnected and the login form is added behind the settings modal that stays visible.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 73.0.3683.103, Firefox 65.0.1
- **OS**: macOS,
- **URL**: riot.im/app 1.0.7

**Comment by jryans** [comment]
Thanks for reporting! I am sort of curious why we allow you to delete the current device at all...

What was your use case for deleting the current device? Is that really what you wanted to do?

**Comment by yzaroui** [comment]
It has the same behavior if let say I am on the settings on firefox, and from chrome I delete my firefox device. I get disconnected on firefox while the settings are still visible.

**Comment by lampholder** [comment]
fwiw when I was thinking of how this UX could be improved (https://github.com/vector-im/riot-web/issues/8319) I proposed that we _remove_ the ability for you to delete your current device from your own device list.

**Comment by robintown** [comment]
The checkbox to delete your own device has been replaced with a more normal 'Sign out' button that does what you'd expect.
