### ISSUE TITLE
On-Screen Keyboard Pops Up When any Text Field gains Focus

### ISSUE THREAD

**Issue by Skynet00** [vector-im/element-web#9531]
### Description

Whenever a text field is in focused for the first time using the mouse, Window's on-screen keyboard pops up. Expected behaviour is the on-screen keyboard should only pop up when the text field is focused using the touch screen.

### Steps to reproduce
Left click on a text field (or tab until a text field is in focus)
On-screen keyboard blocks a chunk of my screen

Log: sent    

![image](https://user-images.githubusercontent.com/3169721/56446677-018a3600-62d2-11e9-847a-ea519d1495b4.png)

### Version information

- **Platform**: Desktop
- **OS**: Windows 8.1 Pro
- **Version**:
matrix-react-sdk version: <local>
riot-web version: 1.0.8
olm version: 3.0.0

**Comment by jryans** [comment]
@Skynet00 If you try https://riot.im/app in a browser instead of using the desktop app, does this happen there as well?

**Comment by Skynet00** [comment]
Nope. It does not happen on the browser version.

**Comment by Skynet00** [comment]
Not sure if this might be related. I do have google japanese input installed as well and it behaves strangely in Riot desktop. Maybe I'll try uninstalling it and test again after.

**Comment by tinywrkb** [comment]
I'm also hitting this with Safari on iPadOS 14.3 when installing Element as a progressive web app.  
Every time I enter the app it focuses on the composer input field and opens the on-screen keyboard.  
It would be nice to see this resolved as the native iOS app looks pretty bad on the iPad.

**Comment by kittykat** [comment]
@Skynet00 @tinywrkb Are you still seeing this issue? If you are, please reply with @kittykat (so I get a notification), detailed information about your setups (browser versions and/or Element versions, device, operating system version, peripherals) and submit a new rageshake linking it to this issue.

I am going to close this issue for now as we can't reproduce it and will reopen it if you're still experiencing it.
