### ISSUE TITLE
password reset form lacks feedback while it is password-resetting

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#9539]
1. open password reset form
2. enter new password and submit
3. open confirmation link in email
4. go back to "reset" tab. Click on "I have confirmed my email".
5. Nothing happens. I think it's sending the request, but I have no idea.
6. Hammer on the button a bit more.
7. give up and reset your password via postgres

**Comment by lampholder** [comment]
Our password reset mechanics are super weird, so I'd rather we replace them entirely with something more normal. That said, if we _can_ make this a lot better with a simple spinner we should consider doing so.

**Comment by richvdh** [comment]
I think this is also a dup of #11531

**Comment by Palid** [comment]
Duplicate, closing in favor of https://github.com/vector-im/element-web/issues/11531
