### ISSUE TITLE
SYSTEM ALERTS section in the room list makes the room list wonky

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#9541]
I accepted an invite to the System Alerts room and then my roomlist looked like this:

![image](https://user-images.githubusercontent.com/1922197/56574340-e3b31e80-65ba-11e9-93d6-176c639a0663.png)

**Comment by jryans** [comment]
I also had such a section, but then visiting the alerts room (plus maybe opening the room's context menu but not changing anything in it) triggered the room to move to the general "Rooms" sublist and the "System Alerts" section vanished.

**Comment by andybalaam** [comment]
@lampholder can you reproduce this? We think this may have become irrelevant with recent changes.

**Comment by t3chguy** [comment]
The room list has been entirely rewritten since then I believe! Do shout if you see it again though
