### ISSUE TITLE
E2E explosion

### ISSUE THREAD

**Issue by rxl881** [vector-im/element-web#9544]
E2E seems to have exploded on one of my devices (laptop - MBP, MacOS, Chrome). I suddenly became unable to read messages in encrypted rooms, that I had been able to read in previously. I tried restoring keys from backup. Historic messages were then readable, but new messages from the previously readable devices were not. 

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: riot.im/app

**Comment by kittykat** [comment]
@BillCarsonFr is it worth keeping this open? I think this area may have been reworked enough that this issue is outdated now.

**Comment by BillCarsonFr** [comment]
> @BillCarsonFr is it worth keeping this open? I think this area may have been reworked enough that this issue is outdated now.

Can be closed, too olf. Logs shows broken sync due to CORS issues
