### ISSUE TITLE
Rename 'kick' as 'remove from chat'

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9547]
as 'kick' is needlessly aggressive

**Comment by BurnyBoi** [comment]
It hasn't been considered aggressive for the decades it's been an IRC command, so why would it be now? Put a nice message in the reason field if you don't want to hurt their feelings. It's not like you're actually physically kicking them...

**Comment by jryans** [comment]
We have the option to be less aggressive, so let's go ahead and do that. There's no need to comply with the idiosyncratic norms of IRC culture in the labelling of UI features.

**Comment by BurnyBoi** [comment]
My main point was that it's not aggressive at all. Being "kicked out" of somewhere is a common term that is mutually understood to mean you were removed. Removing someone from a room against their will is going to potentially upset them regardless of what you call it. 

I don't really care what the UI says, but please keep the /command as "/kick" for the sake of familiarity and efficiency.

**Comment by VindictiveViolator** [comment]
Um excuse me, sweetie, this is 2019﻿...

'ban' as in 'banish' is also unnecessarily aggressive and totally inappropriate if you consider African American history. It should be renamed to "Adorn Chastity Device" instead.

**Comment by CounterPillow** [comment]
Aggressive terminology in the "riot" project, we can't have that, oh no no.

**Comment by ara4n** [comment]
empirically we’ve seen people unfamiliar to the app see the word “kick user” and say “wtf? is this like poking them?” rather than extrapolating it to “kick the user out”.

so, as amusing as it is to see people getting so overexcited about such a trivial change, i’m going to lock the issue to contributors. thanks!

**Comment by gaelledel** [comment]
Let's remove the wording "X kicked X" when someone is removed from a room and replace with "X removed X"
The word "kick" can create very negative emotional responses from users and we have evidence of this.
Also, as Element is evolving with a wider variety of user base, it makes sense to use more appropriate and friendlier language in throughout the product. 
FYI @ara4n
