### ISSUE TITLE
Settings > Profile is using wrong profile information when using per-room nicks/avatars

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-web#9551]
My settings window displays:

![image](https://user-images.githubusercontent.com/2072976/56624321-4d214480-6630-11e9-97a5-20e957dda393.png)

which seems to be getting info from #watercooler:half-shot.uk:

![image](https://user-images.githubusercontent.com/2072976/56624359-67f3b900-6630-11e9-8d98-f73e4489f193.png)

wheras my profile is:

```
> curl https://matrix.half-shot.uk/_matrix/client/r0/profile/@Half-Shot:half-shot.uk
{
    "displayname": "Half-Shot",
    "avatar_url": "mxc://half-shot.uk/6fc3fb176d5246f1e7cf7d89ad4248b8"
}
```

**Comment by Half-Shot** [comment]
Looked into this as it's still happening:

- Riot gets user profile info from `MatrixClient.getUser` (https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/settings/ProfileSettings.js#L30-L31)
- `getUser` fetches it from the backing store.
- Presumably, `storeUser` is called with the data from the per-room profile data at some point but I've not been able to track it down.

**Comment by t3chguy** [comment]
> I've not been able to track it down.

Nor I, which could imply its a Synapse thinko

**Comment by Half-Shot** [comment]
Well, it concerns me that we don't call `/profile` when opening the profile page to be honest. We should be doing that anyway to ensure we have the latest data for the user.

**Comment by Half-Shot** [comment]
So, Synapse sends member state down `/sync` when I talk in a room occasionally:

![image](https://user-images.githubusercontent.com/2072976/71001536-64d49e00-20d5-11ea-9891-45bff09ff459.png)

You can see here a membership event in `state`, despite setting that state in the room some time ago.

**Comment by t3chguy** [comment]
The js-sdk Memory Store updates the global `User` displayName on `m.room.member` events, they also get updated on Presence events (correct). `m.room.member` events should only affect RoomMember displayName not the global `User` displayName.

**Comment by Half-Shot** [comment]
Turns out, this is because of lazy loading. We will send redundant membership events down sync due to `include_redundant_members`.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/riot-web/issues/940
