### ISSUE TITLE
The installation instructions for Ubuntu seem wrong

### ISSUE THREAD

**Issue by hiredgunhouse** [vector-im/element-web#9569]
On the page https://riot.im/download/desktop/ in the section about installation on Ubuntu 16.04 the part regarding gpg key seems wrong, at least for me. 

I had to replace this:

`sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`

with this (put the in a different location):

`sudo wget -O /etc/apt/trusted.gpg.d/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`  

Only then I was able to preform apt-get update without an error saying that the public key for Riot.im is missing.

**Comment by turt2live** [comment]
I think we've fixed this

**Comment by aaronraimist** [comment]
@turt2live the instructions on element.io are the same as what the @hiredgunhouse wrote that they were in this issue. (I'm not sure if they are correct or not)

**Comment by turt2live** [comment]
They seem to work, so I'm inclined to believe that the issue is fixed.
