### ISSUE TITLE
Labels on materialesque text inputs should be greyed out, not black

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9582]
I'm finding it very confusing to find an input control like this...

<img width="416" alt="Screenshot 2019-04-28 at 22 13 00" src="https://user-images.githubusercontent.com/1294269/56870158-ebcbed80-6a02-11e9-86c4-e50efbd0b694.png">

...and see the label having the same font colour as the contents of the box would have.  I have to really think twice as to whether this is an unlabelled text field with contents of "State event" or if it's just a label which looks like field contents.

Can we just make the labels grey in this situation?

**Comment by jryans** [comment]
Seems like a design question for @nadonomy. The current implementation follows the validation summary at https://zpl.io/VDqejkr.

**Comment by nadonomy** [comment]
@jryans thanks for the tag. :)

I concur with @ara4n. Adding to my list to update that Zeplin artboard with (a) the updated UI palette & (b) a disabled state.

**Comment by t3chguy** [comment]
This happened 

![image](https://github.com/vector-im/element-web/assets/2403652/e45e2460-2e3b-4f51-bbb4-b92aa41dc47e)
