### ISSUE TITLE
/devtools UI for switching between creating message & state event is incredibly confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9583]
To tell the UI to create a state event, it transpires you have to click on a big red button labelled 'message event', which then rotates to show you a soft green button labelled 'state event'. wtf?

**Comment by DantrazTrev** [comment]
A similar toggle could be found in Explore Account Data and Send Account Data.
 However, the send account data is much more confusing as there is no visual confirmation if anything has changed at all.
( Something that could be found in the other two toggles )
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43457420/116504164-5c00f880-a8d5-11eb-8879-0bdb70519c30.gif)

This becomes even more confusing as these could be easily mistaken for the main action buttons. 

A solution could be placing them on the left and also if possible replacing them with a toggle switch?

**Comment by ShadowJonathan** [comment]
From #18967;

![image](https://user-images.githubusercontent.com/22740616/132695417-77ec11f7-64dc-4983-83f7-4adb8ac4c3f1.png)

When editing some data, the button doesn't do much of anything at all. In fact, im inclined to press it because it's the brightest button in the bottom right, "Send" should be brighter.

**Comment by ShadowJonathan** [comment]
Some more from #18966;

![image](https://user-images.githubusercontent.com/22740616/132694110-cac0a1f0-6005-466c-b49c-cddec5157fa8.png)

The big red button makes me tentative to press it, as red is most often associated with destructive actions. I had to check (browser) devtools to see if it wasn't missing any text or such.

**Comment by t3chguy** [comment]
This is gone now
