### ISSUE TITLE
Can't navigate long topics

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#9623]
I'm in a room with a long topic, and I can't read it all. Specifically, I'm trying to click on a link which is clipped out of bounds, and it's not clickable when viewing room settings making it even more frustrating.

Should we implement a mechanic that reveals more of the room topic? Either by making it reveal more on hover, or scrollable, or with a 'Show more/Show less' interaction. Simple first option:

- Click topic -> modal
- Room avatar & room name as modal title
- Topic as modal body
- X button/ESC to close

**Comment by lampholder** [comment]
I'd never considered the link-clicking case. It's not uncommon for links to get stuffed into the room topic, so it would be nice to improve this.

**Comment by jryans** [comment]
I do wish there was some minimal Markdown support in the topic, or at least some way to express `[text](url)` so you can compactly show a link without resorting to URL shorteners.

**Comment by hwine** [comment]
> I do wish there was some minimal Markdown support in the topic, 

@jryans you might want to upvote [#5180](https://github.com/vector-im/riot-web/issues/5180#issue-263652206) as well.

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/vector-im/riot-web/issues/1836

**Comment by anoadragon453** [comment]
I do like the way Discord tackle this. Very simply, you can click on the topic in order to reveal the full thing.


https://user-images.githubusercontent.com/1342360/117278120-60d72680-ae58-11eb-9b3d-3570dbfdbb28.mp4

You'll need to think about what happens when a user tries to click a link in the unexpanded topic, but that's the only UX complication I can see.

**Comment by SimonBrandner** [comment]
> With a simple tweak, e.g. clicking to reveal in a low touch dedicated modal with:
>  + Room avatar & room name as modal title
>  + Topic as modal body
>  + X button to close

From [#17367](https://github.com/vector-im/element-web/issues/17367)

**Comment by ShadowJonathan** [comment]
From #17916:

> Or maybe in the sidebar. For that matter, maybe it's interesting to place the topic somewhere under "about" in this section anyways;
> ![image](https://user-images.githubusercontent.com/22740616/124933581-49f1b380-e004-11eb-8400-f6d5648b3ff7.png)

**Comment by williamkray** [comment]
would love to see this feature, and agree the 1 modal mockup looks great.

**Comment by niquewoodhouse** [comment]
@nadonomy @kittykat I was looking for some smallish existing web issues that are to do with IA and this seems a good fit.  It's all about being able to find the content you want (eg read the whole topic).  If you agree its part of it, we could look to fix shortly?

**Comment by williamkray** [comment]
not to throw yet another solution into the mix, but what about just making the full topic expand on hover? users can still use the modals to view/edit by clicking on it, but it might be more indicative that you _can_ click on the topic if it were to do something on hover. seems like expanding would be a nice indicator that "this does a thing" and people could opt not to click on it if they just wanted to read it.

**Comment by anoadragon453** [comment]
The full topic is already displayed in a tool tip when hovering over the topic?

**Comment by ShadowJonathan** [comment]
> The full topic is already displayed in a tool tip when hovering over the topic?

I've often found this to be disorienting, as f.e. linux has a radically different tool-tip design on hover than element's overall design, differing in font, font size, colour, etc.

> but what about just making the full topic expand on hover?

I'm not sure, this may be unexpected and "unwarranted" behaviour, does any other chat app do this?

**Comment by williamkray** [comment]
yes, slack does this. examples below:
![Screenshot_20220213083724](https://user-images.githubusercontent.com/8409433/153764586-dc89ea0c-321d-4c5f-a437-4dd7221a9a8e.png)
![Screenshot_20220213083750](https://user-images.githubusercontent.com/8409433/153764675-25aaccad-d628-4fe1-a82d-3e721f505f17.png)

**Comment by niquewoodhouse** [comment]
> yes, slack does this. examples below: 

Nice spot @williamkray.  They also have, when you click, the dialog that appears with the topic in it with an edit button.  When the topic is short on Slack, the user can click to go the edit dialog.  When it's longer (has the `...` this custom tooltip appears on hover.  

https://user-images.githubusercontent.com/1587166/155513526-f69654d9-f93d-44bf-a7cc-1791c89f0634.mov

There might be drawbacks to doing custom hover things here, like, if we later alter the header a bit we have to consider how this works with it.  It might be strange to have it here but not elsewhere in the product.  

https://user-images.githubusercontent.com/1587166/155513640-fd64cf27-a91f-4771-a880-ceaf96bab2cc.mov

I think the interaction from Slack is nicer than clicking to see the topic but I feel overall like this just needs to work for now and it's ok to just go straight to the full length topic for the first version to keep it a simple, consistent solution, using mostly existing things, even if it means a couple of extra clicks.


Figma [link](https://www.figma.com/file/Srbth0BvhsneR3K5sxie9u/%5BWeb%5D-Can't-read-long-room-topic?node-id=211%3A15787) for reference.

**Comment by gsouquet** [comment]
I personally prefer the second approach as it will probably survive future redesign as Nique explained.
@daniellekirkwood are we happy to go ahead with this?

**Comment by kittykat** [comment]
Second option looks better to me, we should go with that

**Comment by daniellekirkwood** [comment]
If by "second approach" we mean this one (below) then yes, let's do it! 

https://user-images.githubusercontent.com/89144281/166971510-fd0668ec-9b0b-4a2e-b352-5914abb9bbfa.mov
