### ISSUE TITLE
hitting 'enter' after searching the room list loses focus

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9627]
so you can no longer type a name, hit enter, and then use the cursor keys to navigate the results

**Comment by t3chguy** [comment]
Enter after searching room list now selects the first one, should this no-op unless you first arrow-key to select one?

**Comment by turt2live** [comment]
should probably no-op if sent within X milliseconds (where X < 750?) of typing.

**Comment by t3chguy** [comment]
> should probably no-op if sent within X milliseconds (where X < 750?) of typing.

That'd mean for me I'd have to either spam enter or learn to wait for the cooldown as I only ever use the room list to search for a single specific room and I keep typing until its the top result.

**Comment by turt2live** [comment]
ah, I don't even use enter personally. If I'm looking for riot-dev I just type "riot" or "dev" and hope for useful results.

**Comment by t3chguy** [comment]
This is no longer an issue with spotlight
