### ISSUE TITLE
Windows 10 - Notification not cleared on task bar when cleared by Android app

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/element-web#9652]
matrix-react-sdk version: <local>
riot-web version: 1.1.0
olm version: 3.1.0

Using Riot Desktop on Windows 10

I had a couple 1:1 messages, which I read on my Android phone. However on my Windows 10 system, the "Riot" taskbar (not system tray) icon kept "highlighted" as if an alert was present. However, all Riot alerts for my account were cleared, and the taskbar icon did not clear the "alert highlighting" as one would expect.

**Comment by BloodyIron** [comment]
Still happening D:

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/469

(not quite a duplicate because riot-web doesn't receive push)

**Comment by t3chguy** [comment]
We now call `Notification::close` which functions in all supported environments when `Room::getUnreadNotificationCount() === 0`
