### ISSUE TITLE
Reactions: Encrypt aggregation key in E2E rooms

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#9672]
The aggregation key / reaction value should be encrypted using the message key of the original event being reacted to.

**Comment by jryans** [comment]
This is no longer required for shipping reactions. We plan to add metadata to the encrypted aggregation keys so that it's clear to the client when they do need decryption.

**Comment by turt2live** [comment]
This is a spec issue, for which I believe an issue already exists (or at least a comment on the ***STILL*** unmerged MSC)
