### ISSUE TITLE
Inbound messages get delayed for ~30s or more

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/element-web#9673]
### Description

Occasionally *inbound* messages take ages to appear in a room, despite them appearing quickly on other devices.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome,
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by erikjohnston** [comment]
I just caught it in the act again, and it looks like this time it was due to `/sync` tight looping (it was returning a single presence update). So at least one cause of this might be a bug in synapse.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/issues/5503 is the synapse issue for `/sync` tight looping, but I don't really see how that would stop events coming down sync.

**Comment by t3chguy** [comment]
@erikjohnston was this issue in the end that Synapse wasn't returning events other than presence down sync (and thus hopefully now fixed) or something client side?

**Comment by erikjohnston** [comment]
@t3chguy I believe it was client side, but I don't think I've seen it for a while?

**Comment by t3chguy** [comment]
Will close, but if you do see it please shout and we can re-open
