### ISSUE TITLE
Key backup: No signature from key

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9674]
> Bad signature from key ID ed25519:redacted No signature

Possibly related:
* https://github.com/vector-im/riot-web/issues/9529
* https://github.com/vector-im/riot-web/issues/9357

From a rageshake (see attached).

**Comment by poljar** [comment]
This seems to be yet another no signature bug, I think all the implementations nowadays upload and check the signatures correctly. This instance was likely fixed by https://github.com/matrix-org/matrix-js-sdk/pull/944.
