### ISSUE TITLE
registration should not warn about invalid characters in username unless you actually have invalid characters present

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9683]
doing so preemptively is very confusing

**Comment by lampholder** [comment]
I don't find it confusing - we just tell people what characters they _should_ be using without any of the _invalid entry_ styling (red border, red text) that would suggest they've done anything wrong so far.

@nadonomy what do you think?

**Comment by nadonomy** [comment]
To ensure we're talking about the same thing, currently we display the following tooltip immediately when focusing input:

<img width="671" alt="Screenshot 2019-05-16 at 10 53 59" src="https://user-images.githubusercontent.com/4626865/57844999-02c35b80-77c9-11e9-8d1a-c05fbcddf984.png">

then this upon entering an invalid character:

<img width="642" alt="Screenshot 2019-05-16 at 10 54 07" src="https://user-images.githubusercontent.com/4626865/57845088-2e464600-77c9-11e9-8815-6ca88da1fe6d.png">

As the tooltip is displayed in response to input, and the user hasn't discovered any of the invalid entry styling yet, I can see the room for confusion.

**Comment by ara4n** [comment]
This jars every single time, for me.  Why is it warning me when I got it right?!
