### ISSUE TITLE
Ability to deselect all chats so the read-marker doesn't get updated while I don't pay attention

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#9702]
Desktop app. Web too if it lacks it.

**Comment by t3chguy** [comment]
Read marker only gets updated on activity like mouse movement with the window focused or typing into the composer

**Comment by BearerOfHonesty** [comment]
Accidentally giving the window focus is still relatively easy for people with configurations where focus follow the mouse cursor or with virtual desktops where Riot might be open on one by itself that briefly gets focus while using keyboard shortcuts to cycle through virtual desktops.

**Comment by aaronraimist** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/16691
