### ISSUE TITLE
Aggregations: Move relations processing up to the room

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#9712]
The relations processing in `EventTimelineSet.js` feels a bit awkward, especially since it's unclear whether we really want relations added to the timeline at all.

We should investigate moving the relations collection up to the `Room` class instead.

**Comment by bwindels** [comment]
one thing that is currently hard to implement is local echo for unsent messages, as the event being edited is not yet in the timelineset (it's in room.pendingEvents). Maybe something that can be made easier when working on this.

**Comment by t3chguy** [comment]
This happened
