### ISSUE TITLE
Pasting code in markdown mode, switching to RTE, and adjusting formatting breaks the composer

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9724]
As reported by Linda:

> 1. Enable Markdown composer in Riot
> 2. Paste the whole body of https://paste.debian.net/plainh/5a9957eb into it
> 3. Turn off Markdown composer
> 4. Ctrl + A to select all text
> 5. With the editor toolbar enabled, click "quote" and "code" buttons to do the whole text.
> 6. Try to send the message, a big "unknown command" error happens.
> 7. Try clicking the Markdown button again, nothing happens.
> 8. Restart client and you're stuck until clearing `editor_state` from devtools.

My suspicion is the copyright header happens to have markdown-related characters in it, and that's confusing the composer. Because it starts with a slash, it probably amplifies the problem. At worst I'd expect the wrong output from the composer, not a command error that results in a bricked composer.

**Comment by lampholder** [comment]
P2 'cause this is hard to trigger and I suspect we'll replace the composer before we get to look into this specific issue.

**Comment by inthewaves** [comment]
A similar bug?

1. Enable Markdown composer
2. Write and send a code block
3. Disable Markdown composer
4. Quote the code block
5. Copy the monospace typeface text that has the code
6. Paste it into the composer
7. See bug

![riotbug](https://user-images.githubusercontent.com/26474149/57889346-223ba200-7824-11e9-84f1-c63f8376e0f1.gif)

**Comment by turt2live** [comment]
We don't have RTE
