### ISSUE TITLE
Rick's Riot is too big for his browser (Chrome, OS X)

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-web#9729]
It persists over refreshes and browser resizing/switching to/from fullscreen:
![Screen Recording 2019-05-15 at 10 02 19 2019-05-15 10_14_27](https://user-images.githubusercontent.com/1922197/57763899-44390580-76fa-11e9-8ec0-7735acd7572e.gif)

Has anybody else seen this?

**Comment by turt2live** [comment]
Looks a bit like it got stuck in full screen mode, but chrome didn't adjust its dimensions after closing or something. Does popping it in and out of full screen help?

**Comment by lampholder** [comment]
Popping in and out of full screen mode didn't help. Plus the riot always seems to about 10% larger than the browser (even if you shrink the size of the browser).

Super weird, but p2ing until we see another instance of this anywhere (sorry Rick)

**Comment by t3chguy** [comment]
@lampholder has this been reproduced since?

**Comment by turt2live** [comment]
Closing as presumed fixed.
