### ISSUE TITLE
Files panel should tell you which rooms files it's displaying

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#9754]
Neither in production nor the outstanding redesign work does the files panel label whether it's displaying files from all rooms or the one you're viewing.

Considering the top right icons can mix both (e.g. notifications are global, members are not) we should label this better, and sometime in future possibly allow the ability to toggle between This room & All rooms like search.

We could solve this by either labelling the right panel as 'Files in #x' or similar, or by labelling each file as 'posted in #x'.

**Comment by t3chguy** [comment]
There is pending work to make all the right panel (and top right buttons) relate to the current room only which obsoletes this issue
