### ISSUE TITLE
ship WOFF2 fonts, and review how we reference them

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9764]
we currently ship a random bunch of TTF fonts with matrix-react-sdk. We should be shipping WOFF2 instead, which are about 2-3x smaller thanks to smarter compression (although still truetype under the hood). We also created the current set of fonts by copy-pasting the output from google fonts, which apparently was a bad idea because google fonts does UA detection on its output, so we're forcing the Chrome output on everything...

**Comment by jryans** [comment]
Yes, I had been wondering why we were using TTF... All of our supported browsers should be able to handle WOFF2.

**Comment by t3chguy** [comment]
We now ship woff
