### ISSUE TITLE
i can scroll on the settings screen, but nowhere on the main screen.

### ISSUE THREAD

**Issue by MparkG** [vector-im/element-web#9777]
### Description

i can not scroll on web-riot,
using my mouse wheel/ tack pads two finger based scrolling.
Scrolling through the "Persons" list, "Room" list, "low priority" list,
member list of a room on the right does work.
Nor does the actual chat scroll.
It works with the click-and-drag scrollbars on the right though.

### Steps to reproduce

- open web-riot
- attempt to scroll
Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?
this applies to
- https://riot.im/app/
- my personal instance 

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
This applies to:
- Google Chrome ist auf dem neuesten Stand.
    Version 74.0.3729.157 (Offizieller Build) (64-Bit)
- Maxthon
    Version: 5.2.7.2000

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
windows7

However, scrolling in the Settings window works.

**Comment by turt2live** [comment]
@MparkG please fill out the template, as it's hard to figure out what you mean from just the title. This could also be a localized issue, and without knowing what platform or version you're on it is hard to diagnose. 

Screenshots/video would also be helpful here.

**Comment by MparkG** [comment]
i have filled it out so far, as to what i know to answer.

**Comment by SimonBrandner** [comment]
@MparkG, are you still seeing this?

**Comment by MparkG** [comment]
idk, i cant tell, i try to stay away from element.
Its probably repaired by now.

**Comment by SimonBrandner** [comment]
Okay, since we don't have a repro case, I am going to close this. Let me know if you ever see this again
