### ISSUE TITLE
Cite instead of reply in 2-person rooms

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#9781]
The big 'reply' arrow that shows up when hovering over a message is great - but replying is a bit overkill in a 2-person room.  It would be better if the same arrow would do  a 'cite' there.

**Comment by PureTryOut** [comment]
I disagree that replying is overkill in a 2-person room. It's how all other chat clients call it, and it makes it consistent. You're still replying to that specific message, not just citing it.

**Comment by Biep** [comment]
In that case, please provide a condensed format (useful) for replying in 2-person rooms.  Replies take a lot of precious screen real estate.

**Comment by tulir** [comment]
>  Replies take a lot of precious screen real estate.

That will be fixed by matrix-org/matrix-react-sdk#3553

**Comment by robintown** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3553 is merged, so replies hopefull won't feel like 'overkill' anymore
