### ISSUE TITLE
Navigate emoji composer with left & right arrows

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#9783]
Although tab, and up/down works, it'd be nice to navigate the emoji input directionally using any of up/down/left/right on your keyboard.

@bwindels pointed out this could be problematic, as we correctly use left/right to manipulate the caret in the composer. We could perhaps use up/down/left/right once a user hits tab to shift their keyboard focus to the emoji input area?

**Comment by bwindels** [comment]
This is coming to the main composer with https://github.com/matrix-org/matrix-react-sdk/pull/2966 ftr.

**Comment by mcint** [comment]
I want to submit an issue for tabbing order in the emoji picker.

Use of the arrow keys immediately (or at least after typing has begun) will conflict with the use of arrow keys for editing in the text box.


The tabbing order does not (easily? quickly? ever?) reach the emoji grid, focus starts in the text box, then the input reset X, then, no visible element during repeated tabbing.

**Comment by SimonBrandner** [comment]
Related: https://github.com/vector-im/element-web/issues/17574

**Comment by SimonBrandner** [comment]
We now show the autocomplete suggestions vertically, so this is no longer relevant
