### ISSUE TITLE
Allow key sharing with other e2ee room members

### ISSUE THREAD

**Issue by Biep** [vector-im/element-web#9788]
See https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1558446962351776PkSTK:matrix.org?via=matrix.org&via=linuxgaming.life&via=privacytools.io

**Comment by turt2live** [comment]
for context:
> The recent forced logout has caused a lot of pain - and driven many people away from Matrix.
> Providing a key sharing option would go a good way towards healing. Just "share my keys for this room with room member X".

**Comment by eras** [comment]
Another case where builtin key sharing in the client would have been tremendously useful: https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$-ET4NAvOxkfKe4_upq1rES4jy6gixmhxX7pw1hHykO4?via=matrix.org&via=privacytools.io&via=mozilla.org

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/12275
