### ISSUE TITLE
new monospace font renders weird on Windows

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9807]
empirically through crowdsourced testing, see https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15585385401535sWucT:t2l.io?via=matrix.org&via=kde.org&via=t2bot.io

**Comment by lordievader** [comment]
Since a picture says more than a thousand words, here is what it looks like:

![riot](https://user-images.githubusercontent.com/3618054/69821532-3b2a0480-1204-11ea-8e8e-67e33925dad4.png)

**Comment by turt2live** [comment]
@lordievader what OS and browser is that in?

**Comment by lordievader** [comment]
@turt2live This is Windows 10 version 1903 using the desktop version of Riot.im (v1.5.5).

**Comment by turt2live** [comment]
I think you're having some other problem unrelated to this - your screenshot isn't of a code block, so the monospace font isn't in effect. It might be a mismatch of UI scale settings (DPI) in Windows?

**Comment by lordievader** [comment]
I see. I figured this problem was related since it occured after an update between v1.5.2 and v1.5.5. I dont think there is a mismatch in DPI since v1.5.2 didn't have the problem. Should I create a new issue for this?

**Comment by turt2live** [comment]
Yes please.

**Comment by odiferousmint** [comment]
> Since a picture says more than a thousand words, here is what it looks like:
> 
> ![riot](https://user-images.githubusercontent.com/3618054/69821532-3b2a0480-1204-11ea-8e8e-67e33925dad4.png)

Jeez, that looks really ugly. :D

**Comment by turt2live** [comment]
We have since fixed this
