### ISSUE TITLE
Ability to expand code blocks to the size of the content

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#9826]
Slack has a neat feature with code blocks where you can expand them to their original size, so essentially a button to expand the code block to the point where it wouldn't have any height capped.

We could possibly add another floating button similar to the "Copy" button that appears in the top right of code blocks that could toggle this functionality.

The use case is just being able to read large functions/documents without having to scroll all the time.

**Comment by behrmann** [comment]
I agree, I regularly get sent large code blocks that I then need to copy out to read them. Being able to enlarge them, e.g. to full screen, would be great.

**Comment by anoadragon453** [comment]
@behrmann it wouldn't be so much full screen, but more allowing a much larger height for the code block within the timeline.

I suppose full-screen could be a separate option that could be presented initially or only after expanding the height.
