### ISSUE TITLE
Opening registration silently logs out existing user

### ISSUE THREAD

**Issue by tleydxdy** [vector-im/element-web#9842]
### Description

When I was trying out fractal, I decided to create a test user (didn't want to bother people with a new device in e2ee rooms) but it opended riot registration page in the browser. I finished resigtration, and it automatically signed it in, silently logging out my existing user, the other tab with my account logged in shows 
```
** Unable to decrypt: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. **
```
and a refresh I was in the test account again. now I have to verify keys again.....

### Steps to reproduce

- Open fractal, select "create account"
- firefox opens a new tab for registration (in a container tab, just fyi)
- finish registration
- old account automatically logged out

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 67.0
- **OS**: Arch
- **URL**: riot.im/app

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/6875

**Comment by t3chguy** [comment]
This got fixed
