### ISSUE TITLE
"Re-join" room button doesn't feel like it does anything

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9850]
It starts a join request in the background, but doesn't change state. Could do with a spinner.

**Comment by t3chguy** [comment]
This button seems to no longer exist

![image](https://user-images.githubusercontent.com/2403652/94937790-f926ba80-04c7-11eb-9354-5c3de32e3f53.png)

Looks more like
![image](https://user-images.githubusercontent.com/2403652/94937824-05127c80-04c8-11eb-8f06-5c1f765a39bb.png)

which seems to work immediately

**Comment by turt2live** [comment]
it exists - I've clicked it several times over the last week.

**Comment by t3chguy** [comment]
Can you please point me at the "Rejoin room" button you are seeing

![image](https://user-images.githubusercontent.com/2403652/94940169-0abd9180-04cb-11eb-9a8e-12b74841f26f.png)

**Comment by turt2live** [comment]
I assume this one: https://github.com/matrix-org/matrix-react-sdk/blob/72498df28f3e20cc968cea692a9fd49ebb64973e/src/components/views/rooms/RoomPreviewBar.js#L357

**Comment by aaronraimist** [comment]
Closing in favor of https://github.com/vector-im/element-web/issues/24598 which has a screen recording and more labels.
