### ISSUE TITLE
Report user or message as abusive or spam

### ISSUE THREAD

**Issue by astrojuanlu** [vector-im/element-web#9853]
**Is your suggestion related to a problem? Please describe.**

> riot-web doesn't implement the report API, but the mobile apps do

https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$15589826402856WXWOo:t2l.io?via=matrix.org&via=linuxgaming.life&via=privacytools.io

**Describe the solution you'd like**

A way to report a user or message as abusive or spam.

**Describe alternatives you've considered**

The current procedure is

> In general, if it's a matrix.org user then send an email over to abuse@matrix.org or contact the room's moderators.

**Comment by MadLittleMods** [comment]
The **Report** action looks to be in place nowadays. Also for Matrix.org homeserver, there is a whole Trust and Safety team triaging the reports,

![](https://user-images.githubusercontent.com/558581/132743289-61b06c51-b67d-474f-944f-da0914f8acbc.png)


And more recently in [1.7.32-rc.1 (2021-06-29)](https://github.com/vector-im/element-web/blob/develop/CHANGELOG.md#changes-in-1732-rc1-2021-06-29), a report to room moderators feature is now available to test under a labs feature flag.

> Report to moderators prototype. In rooms that support moderation, the `report` button will let you report abuse to room moderators
