### ISSUE TITLE
BigEmoji wrapped in <p> have 43px top/bottom margins

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9854]
![](https://t2l.io/_matrix/media/v1/download/maunium.net/vVoyOETWLNcImWbZnjqcbfBv)

**Comment by lampholder** [comment]
Is there a common way to produce emoji in `<p>` tags?

**Comment by turt2live** [comment]
send them from RiotX I think. riot-android seems unaffected. unsure about iOS

**Comment by turt2live** [comment]
cannot reproduce
