### ISSUE TITLE
Editing messages removes <font>

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9856]
mah rainbows!

**Comment by yannicka** [comment]
Is it possible to have more explanations? I don't quite understand the issue.

**Comment by t3chguy** [comment]
If you do `/rainbow XYZ` it'll send a HTML message with a bunch of `<font...>` but if you go back and Edit that message, the `<font...>`s aren't there so editing will remove the rainbow effect

**Comment by robintown** [comment]
Editing now preserves /rainbow
