### ISSUE TITLE
Some extension (passbolt?) breaks emoji font

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#9870]

**Comment by bwindels** [comment]
from Nad: twemoji have been working really inconsistently for me, I debugged with Ryan and basically some chrome plugins seem to break them, but really inconsistently and unreliably hence the lack of issues/reporting on it

I'd imagine once end users with way more eccentric OS's/browser setups than mine get their hands on it we'll get a flood of hard to repro/fix issues :/

**Comment by bwindels** [comment]
Rick was falling back to the native emoji font on mac with chrome74 with passbolt extension enabled, and seeing twemoji with passbolt disabled, at least on one try.

**Comment by jryans** [comment]
@nadonomy says the font is now working consistently for him this week... 😖

**Comment by t3chguy** [comment]
Closing due to it looking to be fixed
