### ISSUE TITLE
Emoji shortcode is missing on hover

### ISSUE THREAD

**Issue by progserega** [vector-im/element-web#9911]
In old version of Riot (before 1.2.0) - when move mouse pointer to emoji - we was see description:
![1](https://user-images.githubusercontent.com/1297163/58682322-69449e00-83b3-11e9-8436-04727d9405dc.png)

It help found needed emoji (select emoji on phone, and see it "name" in web-riot). Now it is impossible. No description, no interface to select needed emoji (I do not know how developers named some emoji on english)... Now (in 1.2.0) emoji is not usable.

Some emoji is renamed O_o
`:blush:` no in new riot. When I type :bl - no autocomplete. Only when I type full name `:blush:` - it is show `:anxious:`

For non english users - it is very unclear. May be possible add translations for emoji-alias?

Version of Riot: 1.2.0
https://riot.im/app
Firefox 67.0
Linux ubuntu 16.04

**Comment by progserega** [comment]
May be add interface to select emoji with tabs for recent emoji, people, symbols ant etc...

**Comment by jryans** [comment]
Thanks for the report. This is known change as part of switching away from emojione. I imagine we can try to bring it back if there's interest in having it from the community.

**Comment by MurzNN** [comment]
I confirm the problem, very often have problems with finding needed emoji via text.
But for most users will be easier to select emoji by picker, instead of remember text representation, so people wait when https://github.com/vector-im/riot-web/issues/1107 will be implemented.

**Comment by rkfg** [comment]
I think both ways of inserting emojis should be supported. Sometimes it's easier to use a picker (when you don't know the code or not sure what you want), sometimes typing a couple of letters and pressing <kbd>Tab</kbd> is faster. Anyway, seeing the code is essntial.

**Comment by medusacle** [comment]
i'd really love to have this functionality back: i can't be the only one that sometimes doesn't recognize what an emoji is visually, and seeing the shortcode on mouse-over would help

**Comment by MightyCreak** [comment]
I think this feature is a good way to discover new emojis (and it also helps if English is not your mother tong :wink: (#11013))

**Comment by MightyCreak** [comment]
I'd like to mention that, if possible, it would be nice to know the exact name of the emoji the user chose.

This is particularly important because the same emoji can have different names, and the name the user chose when he wrote down his message can change drastically the meaning of the message.

For instance, astonished is also known as drunk: https://emojipedia.org/astonished-face/

And there's lots and lots of examples like this one.

**Comment by rkfg** [comment]
If matrix-org/matrix-react-sdk#5401 is accepted/merged it should be easy to add shortcodes now that emojis are extracted in individual spans.

**Comment by t3chguy** [comment]
> This is particularly important because the same emoji can have different names, and the name the user chose when he wrote down his message can change drastically the meaning of the message.


That would need the Matrix spec to encode emoji in some non-standard way. The standard way is just using the unicode codepoint, which does not differ depending on what the name the software suggested was.
