### ISSUE TITLE
Links in chat are appended with invisible characters

### ISSUE THREAD

**Issue by agilob** [vector-im/element-web#9923]
### Description

Links in chat are prepended with invisible characters / whitespaces and are often impossible to click without removing them from URL bar manually.

### Steps to reproduce

- Send a link

Describe how what happens differs from what you expected.
![Screenshot_20190531_181939](https://user-images.githubusercontent.com/2544251/58722952-5092b300-83c8-11e9-8b14-3bf5dd92cf4b.png)

### Version information
I think this bug appeared a while ago, but got more aggressive recently.

- **Platform**: 

* web - both clients on latest firefox linux

**Comment by agilob** [comment]
Forgot: walkaround it to press spacebar after the link

**Comment by lampholder** [comment]
I _still_ haven't been able to reproduce this, but @turt2live said he has seen it.

If anyone can produce reliable, comprehensive repro steps I'd really appreciate it - the details of how exactly the URL gets into the composer (including precisely how and from where it is copy/pasted if it is copy/pasted).

Also @agilob - what OS are you running?

https://www.thetraveltester.com/game-thrones-locations-malta-gozo/ for the testing of copy/paste

**Comment by agilob** [comment]
>Also @agilob - what OS are you running?

Firefox, Archlinux, had the same problem a while ago when I had Ubuntu.

>(including precisely how and from where it is copy/pasted if it is copy/pasted).

Copy link literally from anywhere, URL bar or right click on link and copy, CTRL+V into message box.

**Comment by lampholder** [comment]
Hmm, I can't repro on FF 66.0.3 Ubuntu 18.04.

I:
- copied a URL from the ff addressbar (I used http://smbc-comics.com/) by selecting it, right clicking and selecting 'copy'
- pasted it into the riot composer with Ctrl+V
- it rendered properly in the timeline
- it got a proper URL preview
- it showed no invisible characters when I hovered over the link
- the page loaded correctly when I clicked on the link

Is any of that different from what you're doing?

**Comment by agilob** [comment]
That's step by step what I do, looks to be related to some browser features as it doesn't happen on new profile of firefox, but still happens when I have addons disabled. I'll keep digging to find more specific source of this problem.

**Comment by lampholder** [comment]
Interesting - do you have any sort of link safety checker (like an antivirus plugin) that might be trying to decorate the links with some sort of safety/unsafety icon? (I think AVG used to put a bunch of green ticks next to links it deemed 'safe')

**Comment by agilob** [comment]
No, nothing like that

**Comment by kittykat** [comment]
I'm going to close this issue for now as we cannot reproduce it. Please comment with @kittykat if you are still experiencing it and I will re-open the issue for you.
