### ISSUE TITLE
DMs with multiple parties now get an avatar of a random member

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#9929]

**Comment by lampholder** [comment]
I can't remember what it's _meant_ to do - just show the avatar of the first member?

**Comment by turt2live** [comment]
it's meant to show the first character of the generated room name. If the room is named "Giphy and 3 others", should be a G.

Same semantics as non-DMs.

**Comment by kittykat** [comment]
Closing as DMs with multiple parties now behave like rooms. Please reopen with reproduction steps if there is a way to make them behave like DMs.
