### ISSUE TITLE
Can't select or delete things in the composer

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#9961]
![help](https://user-images.githubusercontent.com/4626865/58946163-36b4ef80-877d-11e9-8438-636193995baf.gif)

macOS, latest Chrome on `/develop`.

Admittedly, struggling to reproduce this in other rooms, but rageshaked.

**Comment by bwindels** [comment]
![help](https://user-images.githubusercontent.com/274386/58946152-d28e2d80-8774-11e9-9495-85b8a616ec72.gif)

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment]
Assuming no
