### ISSUE TITLE
Message Editing: Server should block edits from other senders

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#9967]
Depends on https://github.com/matrix-org/synapse/issues/5364.

We can use this issue track the Synapse work and / or add any workaround in Riot as needed.

**Comment by richvdh** [comment]
As I understand https://github.com/matrix-org/synapse/issues/5364, it's asking for the homeserver to return a 4xx when you try to `PUT /_matrix/client/v3/rooms/{roomId}/send` an event that edits someone else's message. How exactly does this manifest in element-web? Given the UI doesn't offer the option to edit someone else's message, I'm surprised you care about the behaviour here.

**Comment by richvdh** [comment]
I'm going to go ahead and close this, because I don't think it's relevant to element-web. If anyone knows otherwise, let me know.
