### ISSUE TITLE
Pressing the + button for rooms on community should add the room to the current community

### ISSUE THREAD

**Issue by PhieF** [vector-im/element-web#9970]
Hi,

Pressing the + button for rooms on community should add the room to the current community.

Right now, when I'm in a community, pressing the + button on the left column to add a room will add or create the room in the general section of Riot but not in the current community

I guess it looks like a bug

thanks for your work :)

**Comment by t3chguy** [comment]
That specific community is invite-only so you can only join it if invited, this is a setting in the settings of the community: 
![image](https://user-images.githubusercontent.com/2403652/58994620-1589e880-87e9-11e9-83fb-dd0a2283ec4a.png)

**Comment by t3chguy** [comment]
To add a room to a community first make a room then add it using the controls at top right:

(whilst looking at community click the Hash to see rooms list then Add rooms to this community)
![image](https://user-images.githubusercontent.com/2403652/58994694-4ff38580-87e9-11e9-90d7-7969e7aa2141.png)

**Comment by PhieF** [comment]
Yes I know about this option, but the plus button on the left should have the same behavior when a community is open, for example Discord does that and it seem logical

**Comment by t3chguy** [comment]
But rooms can belong to 0-N communities, the `+` buttons on the left are on specific categories, People and Rooms, and conflating the idea of communities there would be confusing IMO

**Comment by PhieF** [comment]
Then perhaps we should remove the + button on the left when entering the community because this is confusing: After creating the room, we expect it to appear somewhere in the list but it doesn't because it is only in the global view
this + is confusing when we are inside a community, it looks like the main "add room to the community" button

**Comment by t3chguy** [comment]
Reopening for discussion

**Comment by PhieF** [comment]
OK thank you !

so for me the ideal would be to create the room and add it immediately to the community, instead of just creating the room

**Comment by tompinzler** [comment]
> so for me the ideal would be to create the room and add it immediately to the community, instead of just creating the room
I second that

**Comment by vpzomtrrfrt** [comment]
Just ran into this. It's very unclear how to add a room to a community at first glance, and the plus button was the first thing I tried

**Comment by PhieF** [comment]
The same here, even today I found it hard again to add a room, and I'm a technical user. I've asked some friends around me as a test and they all made the mistake

**Comment by ell1e** [comment]
If multiple communities are selected, maybe just do an additional popup when clicking plus with a warning (like "this will create a room in all X communities you selected. continue? [yes, continue] [no, abort]") I assume most beginners won't even realize that is multi selection is possible, so it's not like a lot of people will run into this.

**Comment by PhieF** [comment]
I didn't even know it was possible, but still, creating a room and not seeing it appearing looks like a bug for users

**Comment by neurodynamic** [comment]
Are there any plans to implement one of the suggested fixes for this issue? Hoping to convince a team to adopt this over Slack, but creating rooms is probably one of the first things people will try, and if the UX for something that simple is this confusing, it's gonna be really hard to convince people to adopt. The conversation is going to start with "I promise the rest of the UX isn't this bad" instead of "look how cool this is".

**Comment by turt2live** [comment]
We've introduced prototype behaviour which does this, though it's part of a larger communities rework. Follow #element-web:matrix.org for updates on the communities work.

**Comment by neurodynamic** [comment]
@turt2live Will do! Thanks!

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
