### ISSUE TITLE
Add CSS selectors to the sub DIVs within the "mx_MemberInfo_container"

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#9987]
Please add CSS selectors to the sub DIVs within the "mx_MemberInfo_container" class to identify these sub DIVs, see attached image.

![2019-06-08_102817](https://user-images.githubusercontent.com/41576848/59144453-7592b180-89d8-11e9-91dc-e7271027d6a1.jpg)

**Comment by t3chguy** [comment]
This got done
