### ISSUE TITLE
Integrate tiny minifier to speed up CSS load time

### ISSUE THREAD

**Issue by menturion** [vector-im/element-web#9997]
Currently, every "second" line of CSS code there is a huge block of Apache license comment. For every tiny change there will be an additional license block which overall significantly slows down the load time of the CSS theme file. 

(For me, this is a good example of a disadvantage of the Apache license agreement.)

Maybe, it could be overcome by Integrating a tiny minifier that will minify a given CSS theme file (based on the file's last modified timestamp), dump it into a "temp" folder and load this minified CSS file instead.

**Comment by jryans** [comment]
Have you measured the performance impact of this on Riot or other sites before?

**Comment by menturion** [comment]
Depending on the minification rate you gain a reduction of 30 to 40%.

**Comment by t3chguy** [comment]
CSS minification now works fine

https://app.element.io/bundles/d5476ab08e6ef7b2ef2d/theme-legacy-light.css
https://app.element.io/bundles/d5476ab08e6ef7b2ef2d/bundle.css
